### ISSUE TITLE
API documentation "Core graph data structures"

### ISSUE THREAD

**Issue by PierreAndreNoel** [tensorflow/tensorflow#7300] opened 2017-02-06 19:49 UTC
A few things are wrong in the documentation around [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/framework.md#tfgraphadd_to_collectionname-value-graphadd_to_collection](url).

* Near the end of tf.Graph.name_scope, the line about ValueError is incomplete.
* The paragraph at the very end of tf.Graph.name_scope should be in tf.Graph.add_to_collection.
* Both tf.Graph.add_to_collection and tf.Graph.add_to_collections (plural) exist.

**Comment by girving** [comment] 2017-02-07 15:55
The link you posted is broken.

**Comment by PierreAndreNoel** [comment] 2017-02-07 16:03
Sorry. Please use https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/framework.md then scroll down to the end of tf.Graph.name_scope .

**Comment by girving** [comment] 2017-02-07 16:11
@mrry Looks like you changed the documention in cl/126447618 to the rules are the

**Comment by mrry** [comment] 2017-02-07 23:12
I'm submitting a fix for the broken docstring in `tf.Graph.name_scope()`.

The bad formatting between `tf.Graph.name_scope()` and the paragraph describing collections is (I believe) a function of the doc generator, which @josh11b touched last and will be best placed to fix.

I don't know what the problem is about having `tf.Graph.add_to_collection()` and `tf.Graph.add_to_collections()`, other than it seems a bit redundant. Regardless, we're stuck with supporting both of those methods because of the 1.0 API freeze.

**Comment by wolffg** [comment] 2017-04-13 22:00
I'm closing this, as the formatting and paragraph whatnot is fixed on this new page:  https://www.tensorflow.org/api_docs/python/tf/Graph#name_scope
Please re-open or re-file if I'm missing something.

**Closed by wolffg** 2017-04-13 22:00 UTC
Labels: type:docs
