### ISSUE TITLE
Is `full_matrices=False` working for `tf.svd()`?

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#12158] opened 2017-08-09 20:58 UTC
I am working with tensorflow svd decomposition,  and I notice that the svd results do not have any differences for singular matrix no matter I set `full_matrices=False` or to be `True`. For example, 

```
a = tf.Variable([[1.0, 0.0, 0.0], [0.0, 4.0, 0.0], [0.0, 0.0, 0.0]])  # Singular Matrix
s, u, v = tf.svd(a, full_matrices=False)
init_op = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init_op)
sess.run([s, u, v])
```

The results are always same no matter `full_matrices=False` or `True`. However, the online doc says "If true, compute full-sized u and v. If false (the default), compute only the leading P singular vectors". So I wonder if there is a bug for this argument. Thanks!

**Comment by yaroslavvb** [comment] 2017-08-10 04:33
I think it's not a bug.

Note from helpstring `Tensor` of shape `[..., M, N]`. Let `P` be the minimum of `M` and
        `N`."

The result is different if you use non-square a
`a = tf.Variable([[1.0, 0.0, 0.0]])  # Singular Matrix`

**Comment by reedwm** [comment] 2017-08-15 00:07
Closing as this does not appear to be a bug. @RuofanKong reopen if you still believe it is a bug.

**Closed by reedwm** 2017-08-15 00:07 UTC
