### ISSUE TITLE
tf.check_numerics does not raise error when used in tf.control_dependencies

### ISSUE THREAD

**Issue by korepwx** [tensorflow/tensorflow#11098] opened 2017-06-28 03:53 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.0
- **Bazel version (if compiling from source)**: none
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: run the code below

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

`tf.check_numerics` does not raise error when used in `tf.control_dependencies`.  The code below should raise error, but it does not in TensorFlow 1.2.0

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import numpy as np
import tensorflow as tf

x = tf.constant(np.nan)
with tf.control_dependencies([tf.check_numerics(x, 'nan')]):
    x = tf.identity(x)

with tf.Session().as_default():
    print(x.eval())
```

**Comment by ali01** [comment] 2017-06-30 23:50
Thanks for reaching out. This works as intended.

tf.check_numerics adds an operation to the graph that is only executed if its return value is fetched. The code snippet above ignores the return value of tf.check_numerics. The only tensor that is fetched is x, so check_numerics never runs.

The right way to use check_numerics is to assign its return value to the handle of the original tensor:
    x = tf.check_numerics(x, 'nan')

**Closed by ali01** 2017-06-30 23:50 UTC

**Comment by korepwx** [comment] 2017-07-02 02:06
I think your justification is weird.  Take a look at the documentation of [tf.control_dependencies](https://www.tensorflow.org/api_docs/python/tf/control_dependencies):

>  `control_inputs`: A list of Operation or Tensor objects which must be executed or computed before running the operations defined in the context. Can also be None to clear the control dependencies.

I have fed `tf.check_numerics` into `tf.control_dependencies` via `control_inputs`, no matter what it is, it should have been executed before any operation in the context being called.  And since I set `x = tf.identity(x)` within this control dependencies context, when `x.eval()` is being executed, the `tf.check_numerics` should have been done.

However, it turns out not to have been called.  As a contrary, if you replace `tf.check_numerics` by `tf.Print`, you will see the value of x, right there in the output.  So I think there must be something wrong with `tf.check_numerics` and `tf.control_dependencies`.
