### ISSUE TITLE
ERROR: /tensorflow_src/tensorflow/compiler/aot/BUILD:277:1: C++ compilation of rule '//tensorflow/compiler/aot:embedded_protocol_buffers' failed (Exit 1)

### ISSUE THREAD

**Issue by Amarnathde** [tensorflow/tensorflow#40113] opened 2020-06-03 07:30 UTC
**System information**
- OS Platform: host: mac 14.10 
- docker image:  tensorflow/tensorflow:latest-devel
- TensorFlow version: 2.2
- Python version: 3.6.9
- building tensorflow from source using docker on mac with ubuntu in docker image
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NONE ( cpu only build)
- GPU model and memory: NONE 

**the problem**
```
ERROR: /tensorflow_src/tensorflow/compiler/aot/BUILD:277:1: C++ compilation of rule '//tensorflow/compiler/aot:embedded_protocol_buffers' failed (Exit 1)
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:41:0,
                 from ./tensorflow/core/framework/numeric_types.h:24,
                 from ./tensorflow/compiler/xla/types.h:23,
                 from ./tensorflow/compiler/xla/array.h:34,
                 from ./tensorflow/compiler/xla/array2d.h:29,
                 from ./tensorflow/compiler/xla/literal.h:32,
                 from ./tensorflow/compiler/xla/service/llvm_ir/llvm_util.h:33,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:31:
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:30:41: warning: ignoring attributes on template argument '__m256i {aka __vector(4) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m256i, 20> Packet32q8i;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:31:41: warning: ignoring attributes on template argument '__m256i {aka __vector(4) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m256i, 21> Packet16q16i;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:32:41: warning: ignoring attributes on template argument '__m256i {aka __vector(4) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m256i, 22> Packet32q8u;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:33:41: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m128i, 23> Packet16q8i;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:34:41: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m128i, 25> Packet16q8u;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:35:41: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m128i, 26> Packet8q16i;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:36:41: warning: ignoring attributes on template argument '__m256i {aka __vector(4) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m256i, 27> Packet8q32i;
                                         ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:37:41: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 typedef eigen_packet_wrapper<__m128i, 28> Packet4q32i;
                                         ^
In file included from ./tensorflow/compiler/xla/index_util.h:24:0,
                 from ./tensorflow/compiler/xla/literal.h:35,
                 from ./tensorflow/compiler/xla/service/llvm_ir/llvm_util.h:33,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:31:
./tensorflow/compiler/xla/shape.h: In member function 'void xla::Shape::clear_dynamic_dimensions()':
./tensorflow/compiler/xla/shape.h:139:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int64 i = 0; i < dynamic_dimensions_.size(); ++i) {
                         ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/compiler/xla/service/llvm_ir/llvm_util.h:34:0,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:31:
./tensorflow/compiler/xla/service/hlo_instruction.h: In member function 'void xla::HloInstruction::ReplaceCalledComputations(std::function<xla::HloComputation*(xla::HloComputation*)>)':
./tensorflow/compiler/xla/service/hlo_instruction.h:1431:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int64 i = 0; i < called_computations_.size(); ++i) {
                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:29:0,
                 from ./tensorflow/core/platform/logging.h:27,
                 from ./tensorflow/core/platform/status.h:24,
                 from ./tensorflow/core/lib/core/status.h:19,
                 from ./tensorflow/compiler/xla/status.h:19,
                 from ./tensorflow/compiler/xla/statusor.h:18,
                 from ./tensorflow/compiler/aot/embedded_protocol_buffers.h:24,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
./tensorflow/compiler/xla/shape_util.h:129:5:   required from here
./tensorflow/core/platform/default/logging.h:388:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
./tensorflow/core/platform/macros.h:88:49: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                 ^
./tensorflow/core/platform/default/logging.h:388:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/compiler/xla/array2d.h:29:0,
                 from ./tensorflow/compiler/xla/literal.h:32,
                 from ./tensorflow/compiler/xla/service/llvm_ir/llvm_util.h:33,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:31:
./tensorflow/compiler/xla/array.h: In instantiation of 'bool xla::Array<T>::operator==(const xla::Array<T>&) const [with T = long long int]':
./tensorflow/compiler/xla/service/hlo_sharding.h:190:38:   required from here
./tensorflow/compiler/xla/array.h:430:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int64 i = 0; i < sizes_.size(); ++i) {
                       ~~^~~~~~~~~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:29:0,
                 from ./tensorflow/core/platform/logging.h:27,
                 from ./tensorflow/core/platform/status.h:24,
                 from ./tensorflow/core/lib/core/status.h:19,
                 from ./tensorflow/compiler/xla/status.h:19,
                 from ./tensorflow/compiler/xla/statusor.h:18,
                 from ./tensorflow/compiler/aot/embedded_protocol_buffers.h:24,
                 from tensorflow/compiler/aot/embedded_protocol_buffers.cc:16:
./tensorflow/compiler/xla/array.h: In instantiation of 'tensorflow::int64 xla::Array<T>::dim(tensorflow::int64) const [with T = int; tensorflow::int64 = long long int]':
./tensorflow/compiler/xla/array2d.h:71:44:   required from 'tensorflow::int64 xla::Array2D<T>::height() const [with T = int; tensorflow::int64 = long long int]'
./tensorflow/compiler/xla/service/computation_placer.h:47:45:   required from here
./tensorflow/compiler/xla/array.h:406:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     CHECK(n < sizes_.size());
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/compiler/xla/array.h:406:5: note: in expansion of macro 'CHECK'
     CHECK(n < sizes_.size());
     ^
tensorflow/compiler/aot/embedded_protocol_buffers.cc: At global scope:
tensorflow/compiler/aot/embedded_protocol_buffers.cc:152:1: fatal error: opening dependency file bazel-out/host/bin/tensorflow/compiler/aot/_objs/embedded_protocol_buffers/embedded_protocol_buffers.pic.d: Structure needs cleaning
 }  // namespace tensorflow
 ^
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tensorflow_src/tensorflow/python/tools/BUILD:82:1 C++ compilation of rule '//tensorflow/compiler/aot:embedded_protocol_buffers' failed (Exit 1)
INFO: Elapsed time: 82780.701s, Critical Path: 581.17s
INFO: 16036 processes: 16036 local.
FAILED: Build did NOT complete successfully

```
- I am trying to build tensorflow from source to enable the AVX and FMA instruction. i followed the exact set of instructions inorder to start building. As given [here](https://www.tensorflow.org/install/source#docker_linux_builds) i am building the cpu only version.
- Since i am building from the latest one, I should be building from master branch. so I initiated using the below command: 

` bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --local_cpu_resources=1 --local_ram_resources=2048  //tensorflow/tools/pip_package:build_pip_package`

- after this the analysis phase was done. The error occurred during compilation.

unable to diagnose the error. Please help

EDIT: update: I tried to build again. but the error this arror occured: 
```ERROR: /tensorflow_src/tensorflow/compiler/aot/BUILD:295:1: failed to create output directory '/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/compiler/aot/_objs/aot_only_var_handle_op': /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/compiler/aot/_objs/aot_only_var_handle_op (Structure needs cleaning)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /tensorflow_src/tensorflow/python/tools/BUILD:99:1 failed to create output directory '/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/compiler/aot/_objs/aot_only_var_handle_op': /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/compiler/aot/_objs/aot_only_var_handle_op (Structure needs cleaning)```

**Comment by ymodak** [comment] 2020-06-08 18:02
Duplicate of #40141 
Probably we can follow it on that thread.

**Closed** 2020-06-22 18:53 UTC
Labels: TF 2.2, stalled, stat:awaiting response, subtype:macOS, type:build/install
