### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 294912 values, but the requested shape has 73728

### ISSUE THREAD

**Issue by arunikayadav42** [tensorflow/tensorflow#34737] opened 2019-12-01 18:06 UTC
I downloaded the precomputed image features from 
[https://github.com/kuanghuei/SCAN](url)

and then tried to store them in a tfrecord file and trying to read them from that file but then i get this array. any help will be appreciated.

**Comment by ymodak** [comment] 2019-12-04 23:21
Please provide minimal code snippet to reproduce the reported behavior.

**Comment by ymodak** [comment] 2019-12-16 20:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-12-16 20:03 UTC
Labels: comp:data, stat:awaiting response, type:support
