### ISSUE TITLE
BatchNorm doesn't work in custom Model or Layer.

### ISSUE THREAD

**Issue by FancyVin** [tensorflow/tensorflow#34132] opened 2019-11-10 06:53 UTC
**System information**
-Windows10
- TensorFlow: 2.0.0
- Python version: 3.7

**Describe the current behavior**

`InaccessibleTensorError: The tensor 'Tensor("batch_normalization/batch_normalization_trainable:0", dtype=bool)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=build_graph, id=3078774714504); accessed from: FuncGraph(name=keras_graph, id=3077450685512).`

**Code to reproduce the issue**

```
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, BatchNormalization, LeakyReLU

def get_norm(norm_type):
    if norm_type == "batch":
        return BatchNormalization()
    else:
        raise ValueError(f"Unrecognized norm_type {norm_type}")

class Discriminator(Model):
    def __init__(self,
                 base_filters=32,
                 lrelu_alpha=0.2,
                 pad_type="same",
                 norm_type="batch"):
        super(Discriminator, self).__init__(name="Discriminator")
        # 1------------------------------------------
        self.conv1 = Conv2D(
                filters=base_filters, # 32
                kernel_size=3,     
                padding=pad_type
                )
        self.relu1 = LeakyReLU(alpha=lrelu_alpha)
        
        # 2-------------------------------------------
        self.conv2a = Conv2D(
                filters=base_filters*2, # 64
                strides=2,
                kernel_size=3, 
                padding=pad_type
                )
        self.relu2a = LeakyReLU(alpha=lrelu_alpha)
        self.conv2b = Conv2D(
                filters=base_filters*4, # 128
                kernel_size=3, 
                padding=pad_type
                )
        self.norm2 = get_norm(norm_type)
        self.relu2b = LeakyReLU(alpha=lrelu_alpha)
        
        # 3-----------------------------------------------
        self.conv3a = Conv2D(
                filters=base_filters*4, # 128
                strides=2,
                kernel_size=3, 
                padding=pad_type
                )
        self.relu3a = LeakyReLU(alpha=lrelu_alpha)
        self.conv3b = Conv2D(
                filters=base_filters*8, # 256
                kernel_size=3, 
                padding=pad_type
                )
        self.norm3 = get_norm(norm_type)
        self.relu3b = LeakyReLU(alpha=lrelu_alpha)
        
        # 4----------------------------------------------
        self.conv4 = Conv2D(
                filters=base_filters*8, # 256
                kernel_size=3, 
                padding=pad_type
                )
        self.norm4 = get_norm(norm_type)
        self.relu4 = LeakyReLU(alpha=lrelu_alpha)
        
        # final--------------------------------------------
        self.conv_final = Conv2D(
                filters=1, # 256
                kernel_size=3, 
                padding=pad_type
                )

    def build(self, input_shape):
        super(Discriminator, self).build(input_shape)

    def call(self, input_tensor, training=False):
        # 1---------------------------------------------------
        x = self.conv1(input_tensor, training=training)
        x = self.relu1(x, training=training)
        
        # 2--------------------------------------------------
        x = self.conv2a(x, training=training)
        x = self.relu2a(x, training=training)
        x = self.conv2b(x, training=training)
        x = self.norm2(x, training=training)
        x = self.relu2b(x, training=training)
        
        # 3------------------------------------------------
        x = self.conv3a(x, training=training)
        x = self.relu3a(x, training=training)
        x = self.conv3b(x, training=training)
        x = self.norm3(x, training=training)
        x = self.relu3b(x, training=training)
        
        # 4-------------------------------------------------
        x = self.conv4(x, training=training)
        x = self.norm4(x, training=training)
        x = self.relu4(x, training=training)
        
        # final--------------------------------------------
        x = self.conv_final(x, training=training)
        
        return x

if __name__ == "__main__":
    import numpy as np

    shape = (1, 128, 128, 3)
    nx = np.random.rand(*shape).astype(np.float32)
    t = tf.keras.Input(shape=nx.shape[1:], batch_size=nx.shape[0])

    #tf.keras.backend.clear_session()
    d = Discriminator()
    out = d(t)
    d.summary()
    print(f"Input  Shape: {t.shape}")
    print(f"Output Shape: {out.shape}")
```

**Comment by rmothukuru** [comment] 2019-11-11 10:03
@FancyVin,
When trying to reproduce your error, an intermediate error, shown below has occurred,  `ModuleNotFoundError: No module named 'keras_contrib'`. Can you please help us reproduce the error. Thanks!

**Comment by cecabert** [comment] 2019-11-11 17:41
Related / Duplicate of [32477](https://github.com/tensorflow/tensorflow/issues/32477) I guess.

**Comment by rmothukuru** [comment] 2019-11-15 10:07
@FancyVin,
As @cecabert mentioned, it is a duplicate of [32477](https://github.com/tensorflow/tensorflow/issues/32477). Please confirm if we can close this issue as it's being tracked there. Thanks!

**Comment by FancyVin** [comment] 2019-11-16 01:43
> @FancyVin,
> When trying to reproduce your error, an intermediate error, shown below has occurred, `ModuleNotFoundError: No module named 'keras_contrib'`. Can you please help us reproduce the error. Thanks!

I updated the code, it should work now.

**Comment by rmothukuru** [comment] 2019-11-19 05:58
Closing the issue as it is the duplicate of [32477](https://github.com/tensorflow/tensorflow/issues/32477). Thanks!

**Closed by rmothukuru** 2019-11-19 05:58 UTC
Labels: TF 2.0, comp:keras, type:bug
