### ISSUE TITLE
tf_nightly_gpu_2.0_preview-2.0.0.dev20190420  import error

### ISSUE THREAD

**Issue by AiIsBetter** [tensorflow/tensorflow#28044] opened 2019-04-22 14:24 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip install 
- TensorFlow version (use command below):tf_nightly_gpu_2.0_preview2.0.0.dev20190420
- Python version:3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
import tensorflow as tf
**Describe the expected behavior**
Able to import
**Code to reproduce the issue**
import tensorflow as tf
**Other info / logs**
Traceback (most recent call last):
  File "D:/Python/Project/PythonProject/TF20/code/NFFM/code/NFFM-2.0.py", line 21, in <module>
    import tensorflow as tf
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 42, in <module>
    from tensorflow._api.v2 import compat
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 21, in <module>
    from tensorflow._api.v2.compat import v1
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 643, in <module>
    'tensorflow_estimator.python.estimator.api._v1.estimator'))
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\tools\component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\api\_v1\estimator\__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.api._v1.estimator import experimental
  File "C:\Users\Z&J\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\api\_v1\estimator\experimental\__init__.py", line 29, in <module>
    _sys.modules[__name__], "estimator.experimental")
TypeError: __init__() missing 1 required positional argument: 'deprecated_to_canonical'

**Comment by wdirons** [comment] 2019-04-23 21:30
I think this is a duplicate of https://github.com/tensorflow/tensorflow/issues/27955, it should be fixed in newer nightly builds.

**Comment by AiIsBetter** [comment] 2019-04-24 00:53
> I think this is a duplicate of #27955, it should be fixed in newer nightly builds.

ok，thanks.

**Comment by gadagashwini** [comment] 2019-04-24 04:50
@AiIsBetter This issue is not present in Tensorflow version: tf-nightly-gpu-2.0-preview-2.0.0.dev20190423. You might want to give it a try instead. Thanks!

**Comment by AiIsBetter** [comment] 2019-04-24 05:33
> @AiIsBetter This issue is not present in Tensorflow version: tf-nightly-gpu-2.0-preview-2.0.0.dev20190423. You might want to give it a try instead. Thanks!

Okay, I'll try. Thank you.

**Comment by gadagashwini** [comment] 2019-04-30 04:01
@AiIsBetter Were you able to resolve this issue ?

**Comment by gadagashwini** [comment] 2019-05-14 04:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-05-14 04:17 UTC
Labels: 2.0, stat:awaiting response, type:build/install
