### ISSUE TITLE
explicit GPU device placement failed due to runtime error "unknown CPU"

### ISSUE THREAD

**Issue by ifsheldon** [tensorflow/tensorflow#34718] opened 2019-11-30 06:39 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf2.0
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10
- GPU model and memory: NV V100 32GB

**Describe the current behavior**
The graphic memory of the specified GPU has been allocated, but a runtime error occurred, saying `RuntimeError: /job:localhost/replica:0/task:0/device:CPU:1 unknown device.`
**Describe the expected behavior**
Successfully deploy the model to the specified GPU
**Code to reproduce the issue**
```python
with tf.device('GPU:1'):
    mobile_net_local_path = "/mobilenet" # the local model is the same as the one on https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4, which is runnable on GPU:0
    mobile_net = hub.KerasLayer(mobile_net_local_path,output_shape = [1280] , trainable=True)
```

**Other info / logs**
The logical devices(given by `tf.config.experimental.list_logical_devices()`) are below:
```python
[LogicalDevice(name='/job:localhost/replica:0/task:0/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_CPU:0', device_type='XLA_CPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:GPU:0', device_type='GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:GPU:1', device_type='GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:GPU:2', device_type='GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:GPU:3', device_type='GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:GPU:4', device_type='GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_GPU:0', device_type='XLA_GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_GPU:1', device_type='XLA_GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_GPU:2', device_type='XLA_GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_GPU:3', device_type='XLA_GPU'),
 LogicalDevice(name='/job:localhost/replica:0/task:0/device:XLA_GPU:4', device_type='XLA_GPU')]
```
and physical devices are below:
```python
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:4', device_type='GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:1', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:2', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:3', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:4', device_type='XLA_GPU')]
```

the error is 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-f31b7e9deb50> in <module>
      3 with tf.device('GPU:1'):
      4     mobile_net_local_path = "HandGestureRecognizer/tf2models/mobilenet"
----> 5     mobile_net = hub.KerasLayer(mobile_net_local_path,output_shape = [1280] , trainable=True)

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py in __init__(self, handle, trainable, arguments, **kwargs)
    102       self._func = handle
    103     else:
--> 104       self._func = module_v2.load(handle)
    105       if not callable(self._func):
    106         raise ValueError("Non-callable result from hub.load('%s')" %

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_hub/module_v2.py in load(handle, tags)
     75   if hasattr(tf_v1.saved_model, "load_v2"):
     76     module_handle = resolve(handle)
---> 77     return tf_v1.saved_model.load_v2(module_handle, tags=tags)
     78   else:
     79     raise NotImplementedError("hub.load() is not implemented for TF < 1.14.x, "

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py in load(export_dir, tags)
    515     ValueError: If `tags` don't match a MetaGraph in the SavedModel.
    516   """
--> 517   return load_internal(export_dir, tags)
    518 
    519 

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py in load_internal(export_dir, tags, loader_cls)
    539       loader = loader_cls(object_graph_proto,
    540                           saved_model_proto,
--> 541                           export_dir)
    542       root = loader.get(0)
    543     root.tensorflow_version = meta_graph_def.meta_info_def.tensorflow_version

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py in __init__(self, object_graph_proto, saved_model_proto, export_dir)
    126     self._setup_functions_structures()
    127     self._setup_functions_captures()
--> 128     self._restore_checkpoint()
    129 
    130     for node in self._nodes:

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py in _restore_checkpoint(self)
    277     saver = util.TrackableSaver(graph_view.ObjectGraphView(self.get(0)))
    278     with ops.device("CPU"):
--> 279       saver._file_prefix_placeholder = constant_op.constant(variables_path)
    280     load_status = saver.restore(variables_path)
    281     load_status.assert_existing_objects_matched()

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py in constant(value, dtype, shape, name)
    225   """
    226   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 227                         allow_broadcast=True)
    228 
    229 

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    233   ctx = context.context()
    234   if ctx.executing_eagerly():
--> 235     t = convert_to_eager_tensor(value, ctx, dtype)
    236     if shape is None:
    237       return t

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     94       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     95   ctx.ensure_initialized()
---> 96   return ops.EagerTensor(value, ctx.device_name, dtype)
     97 
     98 

RuntimeError: /job:localhost/replica:0/task:0/device:CPU:1 unknown device.
```
After executing the python codes above, it can be seen in `nvidia-smi` that the graphic memory of the specified GPU (GPU:1) has been allocated.
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12253      C   ...user/anaconda3/envs/tf2/bin/python   307MiB |
|    0     20120      C   python3                                     2617MiB |
|    0     27393      C   python3                                     1701MiB |
|    0     68670      C   python3                                      941MiB |
|    0     73404      C   python3                                     1209MiB |
|    1     12253      C   ...user/anaconda3/envs/tf2/bin/python 31009MiB |
|    2     12253      C   ...user/anaconda3/envs/tf2/bin/python   307MiB |
|    3     12253      C   ...user/anaconda3/envs/tf2/bin/python   307MiB |
|    4     12253      C   ...user/anaconda3/envs/tf2/bin/python   307MiB |
+-----------------------------------------------------------------------------+
```

**Comment by gowthamkpr** [comment] 2019-12-04 22:49
Dis you use `pip install tensorflow-gpu==2.0 or `pip install tensorflow == 2.0 ` If you have installed tensorflow using the later command, this might cause this error.

**Comment by ifsheldon** [comment] 2019-12-05 02:57
> Dis you use `pip install tensorflow-gpu==2.0 or `pip install tensorflow == 2.0 ` If you have installed tensorflow using the later command, this might cause this error.

I didn't. I just used conda to install tensorflow-gpu.

**Comment by sanjoy** [comment] 2019-12-21 00:27
@tomhennigan I noticed you added the explicit `with ops.device("CPU")` in `_restore_checkpoint` (internal CL 244133653).  Do you think we need to have a more specific `CPU:0` device setting?

**Comment by tomhennigan** [comment] 2020-04-24 19:07
Sorry I didn't notice this bug. CPU:0 sounds fine, although I can't reproduce this in a colab. The following snippet prints `CPU:0`:

```python
with tf.device("/device:TPU:1"):
  with tf.device("CPU"):
    print(tf.ones([]).device)
```

**Comment by sushreebarsa** [comment] 2021-08-11 08:00
@ifsheldon It looks like you are using an older Version of Tensorflow 2.0. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-25 09:16 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:gpu, TF 2.0
