### ISSUE TITLE
Why is op:BatchMatMul listed in file(.pbtxt), when there is no call to such op?

### ISSUE THREAD

**Issue by vinayonchip** [tensorflow/tensorflow#26239] opened 2019-03-01 05:15 UTC
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 1.12
- Python version: 3.6 

**Describe the current behavior**
There is no usage of op named _**BatchMatMul**_ in my code. But the op is listed in the file(.pbtxt) which gives me other issues while converting the graph to tflite.

**Describe the expected behavior**
If there is no explicit usage of the particular op, it should not be listed in file(.pbtxt)

**Comment by jvishnuvardhan** [comment] 2019-03-01 21:18
@vinayonchip Can you provide a code to reproduce the bug? Also, mention more details about the bug and its context. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-18 20:31
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-18 20:31 UTC
Labels: comp:ops, stat:awaiting response, type:bug/performance
