### ISSUE TITLE
Can not use Tokenizer() to tokenize the input words in text classification in TF1.14 without eager execution for TPU..

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#31790] opened 2019-08-20 10:20 UTC
I am trying to write my code for using TPUs. However, I can not simply just tokenize the texts. I have tried many things to make it work but it just can not. There is NO documentation on Tensorflow on how to do it without enabling eager execution in TF1.14. 
````
tokenizer = tfds.features.text.Tokenizer()
vocabulary_set = set()
for text_tensor, _ in all_labeled_data:
  some_tokens = tokenizer.tokenize(text_tensor)
  vocabulary_set.update(some_tokens)
````
I am receiving following error
`TypeError: Expected binary or unicode string, got <tf.Tensor 'IteratorGetNext_5:0' shape=() dtype=string>`
I can not get the valiue of this iterator even by using `session.run`. THere is literally no help from Tensorflow on how to tokenize inputs for simple text classification without eager mode.

**Comment by ravikyram** [comment] 2019-08-21 11:03
Can you please provide the sample code to reproduce the issue reported here. Thanks!

**Comment by rishabhsahrawat** [comment] 2019-08-21 11:58
Hi @ravikyram , thank you for your response. I have opened another issue in which I tried to solve it by using `session.run()`. I am really not sure if I did it correctly. Below is the way I used.
````
tokenizer = tfds.features.text.Tokenizer()
vocabulary_set = set()

my_iterator = all_labeled_data.make_initializable_iterator()
text_tensor, _ = my_iterator.get_next()
with tf.Session() as sess1: 
  sess1.run(my_iterator.initializer)
  try:
    while True:
      text_string = sess1.run(text_tensor)
      #print text_string
      some_tokens = tokenizer.tokenize(text_string)
      vocabulary_set.update(some_tokens)
  except tf.errors.OutOfRangeError:
    pass
`````
After this fix, I am facing the problem described in this [issue](https://github.com/tensorflow/tensorflow/issues/31832). Thank you for your help and patience.

**Comment by ravikyram** [comment] 2019-08-22 12:34
@rishabhsahrawat 
Thanks for providing the code.

**Comment by jvishnuvardhan** [comment] 2019-08-22 23:33
@rishabhsahrawat I cannot reproduce the issue. If it was fixed already, please close the issue. we will track any related issues in the [other issue](https://github.com/tensorflow/tensorflow/issues/31832) that raised. Thanks!

**Comment by rishabhsahrawat** [comment] 2019-08-23 06:38
@jvishnuvardhan If you think the approach (`make_initializable_iterator`) I used to access each element in the dataset for tokenizing then we can move to next issue mentioned [here](https://github.com/tensorflow/tensorflow/issues/31832) and close this one. But if you think this is not the good way of performing tokenizing then please share your suggestions.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:06
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jvishnuvardhan** [comment] 2021-02-02 00:52
Closing this issue as this was already resolved. Please feel free to reopen If I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-02-02 00:52 UTC
Labels: TF 1.14, comp:data, comp:tpus, stat:awaiting tensorflower, type:docs-bug
