### ISSUE TITLE
TF1.5 configure overwrites export TF_CUDA_VERSION=9.1

### ISSUE THREAD

**Issue by ahundt** [tensorflow/tensorflow#16526] opened 2018-01-28 22:44 UTC
It seems `configure` overwrites the BASH flag:
```bash
export TF_CUDA_VERSION="9.1"
```
Here is the 1.5 branch of my [tensorflow.sh](https://github.com/ahundt/robotics_setup/blob/tf-1.5/tensorflow.sh) install script.

Here are the key code lines from the [tensorflow.sh specific hash to reproduce this error](https://github.com/ahundt/robotics_setup/blob/8a7940f74945f09d2a6bfc1a08d06f156a4c79f9/tensorflow.sh) install script,  and 161 at the time of writing:
```
    # line 134 at the time of writing
    export TF_NEED_CUDA=1
    export TF_CUDA_VERSION="9.1"
    export TF_CUDNN_VERSION=7
    export CUDA_TOOLKIT_PATH=/usr/local/cuda-9.1/targets/x86_64-linux/lib/
    # ...snip... to line 161 at the time of writing
    yes "" | ./configure
```

I believe the problem is either in the `configure` script, [configure.py set_tf_cuda_version() ask_cuda_version](https://github.com/tensorflow/tensorflow/blob/r1.5/configure.py#L805) or in the call to [set_tf_cuda_version](https://github.com/tensorflow/tensorflow/blob/r1.5/configure.py#L1320), none of which seem to check the environment variable first and possibly overwrite it.

The result is the following error:
```
Invalid path to CUDA 9.0 toolkit. /usr/local/cuda/lib64/libcudart.so.9.0 cannot be found
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 9.0]:

Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:

Invalid path to CUDA 9.0 toolkit. /usr/local/cuda/lib64/libcudart.so.9.0 cannot be found
Traceback (most recent call last):
  File "configure.py", line 1365, in <module>
    main()
  File "configure.py", line 1320, in main
    set_tf_cuda_version(environ_cp)
  File "configure.py", line 850, in set_tf_cuda_version
    _DEFAULT_PROMPT_ASK_ATTEMPTS)
__main__.UserInputError: Invalid TF_CUDA_SETTING setting was provided 10 times in a row. Assuming to be a scripting mistake.
-> [1]
ahundt@femur|~/src/robotics_setup on tf-1.5!?
± ls /usr/local/cuda/lib64/
stubs                  libcusparse.so.9.1     libnppist.so.9.1
libaccinj64.so         libcusparse.so.9.1.85  libnppist.so.9.1.85
libaccinj64.so.9.1     libcusparse_static.a   libnppist_static.a
libaccinj64.so.9.1.85  libnppc.so             libnppisu.so
libcublas_device.a     libnppc.so.9.1         libnppisu.so.9.1
libcublas.so           libnppc.so.9.1.85      libnppisu.so.9.1.85
libcublas.so.9.1       libnppc_static.a       libnppisu_static.a
libcublas.so.9.1.128   libnppial.so           libnppitc.so
libcublas.so.9.1.85    libnppial.so.9.1       libnppitc.so.9.1
libcublas_static.a     libnppial.so.9.1.85    libnppitc.so.9.1.85
libcudadevrt.a         libnppial_static.a     libnppitc_static.a
libcudart.so           libnppicc.so           libnpps.so
libcudart.so.9.1       libnppicc.so.9.1       libnpps.so.9.1
libcudart.so.9.1.85    libnppicc.so.9.1.85    libnpps.so.9.1.85
libcudart_static.a     libnppicc_static.a     libnpps_static.a
libcufft.so            libnppicom.so          libnvblas.so
libcufft.so.9.1        libnppicom.so.9.1      libnvblas.so.9.1
libcufft.so.9.1.85     libnppicom.so.9.1.85   libnvblas.so.9.1.128
libcufft_static.a      libnppicom_static.a    libnvblas.so.9.1.85
libcufftw.so           libnppidei.so          libnvgraph.so
libcufftw.so.9.1       libnppidei.so.9.1      libnvgraph.so.9.1
libcufftw.so.9.1.85    libnppidei.so.9.1.85   libnvgraph.so.9.1.85
libcufftw_static.a     libnppidei_static.a    libnvgraph_static.a
libcuinj64.so          libnppif.so            libnvrtc-builtins.so
libcuinj64.so.9.1      libnppif.so.9.1        libnvrtc-builtins.so.9.1
libcuinj64.so.9.1.85   libnppif.so.9.1.85     libnvrtc-builtins.so.9.1.85
libculibos.a           libnppif_static.a      libnvrtc.so
libcurand.so           libnppig.so            libnvrtc.so.9.1
libcurand.so.9.1       libnppig.so.9.1        libnvrtc.so.9.1.85
libcurand.so.9.1.85    libnppig.so.9.1.85     libnvToolsExt.so
libcurand_static.a     libnppig_static.a      libnvToolsExt.so.1
libcusolver.so         libnppim.so            libnvToolsExt.so.1.0.0
libcusolver.so.9.1     libnppim.so.9.1        libOpenCL.so
libcusolver.so.9.1.85  libnppim.so.9.1.85     libOpenCL.so.1
libcusolver_static.a   libnppim_static.a      libOpenCL.so.1.0
libcusparse.so         libnppist.so           libOpenCL.so.1.0.0
```

**Comment by ahundt** [comment] 2018-01-28 22:56
I managed to hack around this by manually setting [configure.py](https://github.com/tensorflow/tensorflow/blob/master/configure.py#L39):
```
_DEFAULT_CUDA_VERSION = '9.0'
```
to
```
_DEFAULT_CUDA_VERSION = '9.1'
```

However, it would be nice if the script was updated to read the export variables correctly again. 👍

**Comment by ahundt** [comment] 2018-01-28 22:59
...and then I immediately ran into the following interesting error which is apparently some sort of odd globbing bug?

```
+ bazel build --copt=-march=native -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
........................................
ERROR: /home/ahundt/src/tensorflow/tensorflow/tools/pip_package/BUILD:106:1: no such package 'third_party/eigen3': error globbing [**/*]: /home/ahundt/src/tensorflow/third_party/eigen3/mkl_include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include (Too many levels of symbolic links) and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package 'third_party/eigen3': error globbing [**/*]: /home/ahundt/src/tensorflow/third_party/eigen3/mkl_include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include (Too many levels of symbolic links)
INFO: Elapsed time: 25.548s
FAILED: Build did NOT complete successfully (41 packages loaded)
    currently loading: tensorflow/python ... (4 packages)
    Fetching https://mirror.bazel.build/www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz
    Fetching https://mirror.bazel.build/github.com/hfp/libxsmm/archive/1.8.1.tar.gz
    Fetching https://mirror.bazel.build/.../highwayhash/archive/dfcb97ca4fe9277bf9dc1802dd979b071896453b.tar.gz
    Fetching https://mirror.bazel.build/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz
    Fetching https://mirror.bazel.build/curl.haxx.se/download/curl-7.49.1.tar.gz
    Fetching https://mirror.bazel.build/github.com/jemalloc/jemalloc/archive/4.4.0.tar.gz
    Fetching https://mirror.bazel.build/.../google/re2/archive/26cd968b735e227361c9703683266f01e5df7857.tar.gz
-> [1]
```

**Comment by ahundt** [comment] 2018-01-28 23:28
I needed an additional hack from https://github.com/tensorflow/tensorflow/issues/11903#issuecomment-332718012 to avoid an MPI error:
`export CC_OPT_FLAGS="-DOMPI_SKIP_MPICXX=1 -march=native"`

**Comment by drpngx** [comment] 2018-01-30 02:24
Sounds like a good idea to me. Feel free to send a PR and CC @gunan.

I prefer config options as suggested by in #16518.

**Comment by ahundt** [comment] 2018-01-30 04:18
I agree, config options would be even better

**Comment by gunan** [comment] 2018-01-30 05:08
@case540 Could you take a look.

Our aim is in the end you will only need to set config options, and no need to run configure.
Mike, what is the environment variable to use for setting the CUDA version we use for the configure script?

**Comment by tensorflowbutler** [comment] 2018-02-13 14:23
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by case540** [comment] 2018-02-21 00:32
oops, missed this.

TF_CUDA_VERSION is the correct env variable to be setting. I'm not able to reproduce this error. The configure script appears to look in the correct path for CUDA. Note, that IF configure.py script does not find CUDA, then it will set the TF_CUDA_VERSION env variable to empty string (and then reask user again where it should look for CUDA).

**Comment by ahundt** [comment] 2018-02-21 06:13
were you able to try with 9.1 on tf 1.5? Perhaps something was updated already but before it would look for 9.0 anyway.

**Comment by tensorflowbutler** [comment] 2018-03-07 13:13
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-26 22:07
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-10 12:32
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-25 18:57
Nagging Assignees @case540, @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:02
Nagging Assignees @case540, @gunan: It has been 94 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:51
Nagging Assignees @case540, @gunan: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging Assignees @case540, @gunan: It has been 124 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging Assignees @case540, @gunan: It has been 139 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:00
Nagging Assignees @case540, @gunan: It has been 154 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:03
Nagging Assignees @case540, @gunan: It has been 169 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:45
Nagging Assignees @case540, @gunan: It has been 184 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:39
Nagging Assignees @case540, @gunan: It has been 199 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:45
Nagging Assignees @case540, @gunan: It has been 214 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:45
Nagging Assignees @case540, @gunan: It has been 229 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by case540** [comment] 2018-10-09 00:09
Hmm, taking another look at this, it seems like if you set either of CUDA_TOOLKIT_PATH  or TF_CUDA_VERSION  incorrectly, then both of those ENV variables will be reset and ununsed.

It could be the case that CUDA_TOOLKIT_PATH was incorrectly set, then both those env variables were set to the defaults, and some default cuda path with default cuda 9.0 version was used.

If this is the case, then it's more of an issue of a very confusing error. I dont think the CUDA_VERSION variable should ever be reset by the configure script, since if a user sets a specific version we should use that version probably

**Comment by case540** [comment] 2018-10-09 00:12
On the other hand, since...

yes "" | ./configure

... is run by the above script, it kinda just skips through all of the prompts. I think a potential solution to this is to make a much friendly way for scripts to run configure.py. Such just add actual python args to the script instead of just setting env variables and then skipping over user prompts lol

**Comment by tensorflowbutler** [comment] 2018-10-23 12:48
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:09
Nagging Assignees @case540, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:44
Nagging Assignees @case540, @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ahundt** [comment] 2018-12-07 20:53
>  I think a potential solution to this is to make a much [friendlier] way for scripts to run configure.py

That would be an excellent solution, I agree!

**Comment by ymodak** [comment] 2019-08-23 23:35
Closing this issue due to staleness. Please check with the latest version of TensorFlow. Feel free to reopen if issue still persists. Thanks!

**Closed by ymodak** 2019-08-23 23:35 UTC
