### ISSUE TITLE
Building From Source on Ubuntu TMP directory defaults to 'C:\Windows\Temp

### ISSUE THREAD

**Issue by lacvapps** [tensorflow/tensorflow#41924] opened 2020-07-31 04:18 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version:2.3.0
- Python version:3.8.0
- Bazel version (if compiling from source):3.1.0

**Describe the problem**

$ bazel build -c opt //tensorflow/tools/lib_package:libtensorflow

Warning shows 

`Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default`

Full output

```
bazel build -c opt //tensorflow/tools/lib_package:libtensorflow
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=179
INFO: Reading rc options for 'build' from /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/russell/git/go/src/github.com/tensorflow/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/russell/anaconda3/bin/python3 --action_env PYTHON_LIB_PATH=/home/russell/anaconda3/lib/python3.8/site-packages --python_path=/home/russell/anaconda3/bin/python3 --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.5 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:linux in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/russell/git/go/src/github.com/tensorflow/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/russell/.cache/bazel/_bazel_russell/8890081aadea2dff92679e25965ee39c/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default

```

**Comment by ravikyram** [comment] 2020-07-31 06:55
@lacvapps 

This looks like a duplicate of #40614. We can track the issue in #40614.Thanks!

**Comment by lacvapps** [comment] 2020-08-01 00:07
Okay, thank you for the respose

**Comment by ravikyram** [comment] 2020-08-04 06:05
@lacvapps 

Can you please close this issue since it is being tracked in #40614.Thanks!

**Closed** 2020-08-04 14:21 UTC
Labels: TF 2.3, stat:awaiting response, subtype: ubuntu/linux, type:build/install
