### ISSUE TITLE
tensorflow-gpu 1.13.0rc0 requires minimum CUDA compute capability 6.0

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#25329] opened 2019-01-30 18:39 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.0rc0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0, CUDNN 7.4.1
- GPU model and memory: GeForce GTX 980 Ti

**Describe the problem**

The 1.13 release candidate requires a minimum compute capability of 6.0 (so it ignores lower-level devices).  Is this an intentional change that we can expect to see in the full release? Or just an artifact of the release candidate build?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
2019-01-30 14:29:07.690292: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-01-30 14:29:07.883552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.291
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-01-30 14:29:07.888807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1483] Ignoring visible gpu device (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.
2019-01-30 14:29:07.894771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-30 14:29:07.898191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-01-30 14:29:07.901776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 8036038049545966896
]
```

**Comment by EWouters** [comment] 2019-01-30 21:15
I'm experiencing a similar issue, on 1.13.0rc0. I compiled TensorFlow with [this](https://pastebin.com/csWDkhvU) script on Ubuntu 18.04.

```
>>> from tensorflow.python.client import device_lib
>>> device_lib.list_local_devices()
2019-01-30 22:09:44.883940: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394450000 Hz
2019-01-30 22:09:44.884404: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e57095ebb0 executing computations on platform Host. Devices:
2019-01-30 22:09:44.884426: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-01-30 22:09:44.930354: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-30 22:09:44.931240: I tensorflow/compiler/xla/service/platform_util.cc:194] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0
2019-01-30 22:09:44.931352: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
```

**Comment by ymodak** [comment] 2019-01-31 01:37
@gunan Can you  PLTAL? The cuda compute capability 3.5 or higher for TF-GPu support right? Thanks

**Comment by gunan** [comment] 2019-02-01 18:46
I think our windows package has this problem. This is a duplicate of #18652
@EWouters unfortunately in your case your GPU is too old. for 3.0, you will need to rebuild TF.

**Comment by drasmuss** [comment] 2019-02-01 19:13
I think this is a different issue.  If I'm understanding 18652 correctly, the problem there is that compute capabilities > 6.0 were not supported, which caused a performance issue (dating back to TF 1.7).  The problem here is that GPUs with compute capability < 6.0 are no longer supported (can't use the GPU at all).  And this is a new issue introduced in TF 1.13.

**Comment by gunan** [comment] 2019-02-01 21:20
What happened is, looks like our builders are only building for the GPU they have.
They used to have K80s, so anything never than K80 was slow to startup waiting for JIT compiler.
But we switched our builders to P100s a while ago. Anything newer than P100 still waits for JIT compilation, but older ones are cannot do this so they fail.

either way, the solution is for us to fix the CUDA capabilities we need to build for.

**Comment by Worthy7** [comment] 2019-02-05 11:07
Seeing this error in 2.0-preview '2.0.0-dev20190130' too, "The minimum required Cuda capability is 6.0." - my GPU is 5.2, but that's definitely faster than my CPU.

**Comment by gunan** [comment] 2019-02-05 17:49
We just checked in a change to update our windows build bots to include more cuda compute capabilities.
If you upgrade to a dev version 20190205, it should be resolved.
This both applies to 2.0 preview and tf-nightly.

1.13.0rc1 will also have more compute capabilities.

**Comment by Worthy7** [comment] 2019-02-05 23:04
Thanks! yep that's working!

**Comment by mikaelhg** [comment] 2019-02-15 12:30
Had the same problem with the CUDA 6.0 minimum requirement with the 1.12.0 Java libs from Maven Central.

**Comment by christian-rauch** [comment] 2019-03-26 20:47
The pre-build binaries ([`libtensorflow-gpu-linux-x86_64-1.13.1.tar.gz`](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.13.1.tar.gz)) for the C API have the same limitation:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.304
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 2.81GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1483] Ignoring visible gpu device (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.
```

**Comment by NPetsky** [comment] 2019-04-10 10:06
I have the same issue (The minimum required Cuda capability is 6.0) with a bazel built tensorflow 1.13 for c++ (libtensorflow_cc.so)

**Comment by elf128** [comment] 2019-05-08 17:54
I would like to confirm presence of this regression in r1.13.1 
I've built TF 1.13.1 from sources yesterday, specifically for Cuda3.0 support.
After install, following check failed the same way as for many people in this thread.
```python
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```
I've got **StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 3.0** followed by python crash.

Then I've found this thread and tried to follow the same way.

I've checked out **r1.12.2**, apply same settings and build it over night.
Same test is passing without error.
```
2019-05-08 13:26:11.192724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 1290 MB memory) -> physical GPU (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0, compute capability: 3.0)
```

**Comment by rsingh2083** [comment] 2019-06-20 17:02
System reboot worked for me

**Comment by gadagashwini** [comment] 2019-08-06 12:11
@drasmuss Is this still an issue? Thanks!

**Comment by drasmuss** [comment] 2019-08-06 14:12
This was fixed after this change https://github.com/tensorflow/tensorflow/issues/25329#issuecomment-460735683 as far as I've seen.

**Comment by mikaelhg** [comment] 2019-08-06 14:23
@drasmuss, not true, https://repo1.maven.org/maven2/org/tensorflow/libtensorflow_jni_gpu/1.14.0/libtensorflow_jni_gpu-1.14.0.jar was published with 6.0 requirements.

**Comment by drasmuss** [comment] 2019-08-06 14:48
That seems like a problem specific to the Java implementation, which is different than what is described in this issue.

**Comment by mikaelhg** [comment] 2019-08-06 15:00
Same issue, which is just a bit more broadly spread out in the build infrastructure than the initial report.

**Comment by drasmuss** [comment] 2019-08-06 15:11
Then I'd recommend making a new issue specific to your problem, since it doesn't match the initial report here, to avoid confusion and help your problem get resolved faster. But up to you 😄

**Comment by gadagashwini** [comment] 2019-08-07 05:57
@drasmuss Thanks for confirmation. Closing the issue since its fixed.
@mikaelhg, Can you please post a new issue by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

**Closed by gadagashwini** 2019-08-07 05:57 UTC
Labels: TF 1.13, subtype:windows, type:build/install

**Comment by johan-andersson01** [comment] 2020-02-18 10:23
> The pre-build binaries ([`libtensorflow-gpu-linux-x86_64-1.13.1.tar.gz`](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.13.1.tar.gz)) for the C API have the same limitation:
> 
> ```
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
> name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.304
> pciBusID: 0000:01:00.0
> totalMemory: 3.94GiB freeMemory: 2.81GiB
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:1483] Ignoring visible gpu device (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.
> ```

@christian-rauch I have now opened an issue for this: https://github.com/tensorflow/tensorflow/issues/36853 (although for the 1.14 and 1.15 releases)
