### ISSUE TITLE
x86_64 compilation failed

### ISSUE THREAD

**Issue by rlehman221** [tensorflow/tensorflow#16231] opened 2018-01-18 23:51 UTC
### System information

- **MacOS High Sierra 10.13.2**:
- **Python 3.6.3**:
- **TensorFlow Latest Pull from 1/17/18**:

### Describe the problem
I am following Pete Warden's TensorFlow for Mobile Poets guide and seem to have a found an error. When I run "tensorflow/contrib/makefile/build_all_ios.sh" after about 20 minutes it returns an error. 

I have tried running lipo -info /Users/ryan/Downloads/tensorflow2/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a

and this returns: 

Architectures in the fat file:
/Users/ryan/Downloads/tensorflow2/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a are: i386 

I have the entire error script here:
https://drive.google.com/file/d/1JovTMGBJKbqzRPBzXy3cIQ-hbz76n0ab/view?usp=sharing

### Source code / logs
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see 
invocation)
make: *** [/Users/ryan/Desktop/tensorflow-
master/tensorflow/contrib/makefile/gen/bin/ios_X86_64/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'x86_64 compilation failed.'
x86_64 compilation failed.
+ exit 1

**Comment by rlehman221** [comment] 2018-01-18 23:52
@petewarden

**Comment by aselle** [comment] 2018-01-22 04:02
@petewarden , could you take a quick look?

**Comment by petewarden** [comment] 2018-01-31 19:42
This is a duplicate of #12904, which I believe I've just fixed.

**Closed by petewarden** 2018-01-31 19:42 UTC
Labels: stat:awaiting tensorflower, type:build/install
