### ISSUE TITLE
Tensorboard not showing any curves

### ISSUE THREAD

**Issue by rohitgirdhar** [tensorflow/tensorflow#3829] opened 2016-08-15 21:24 UTC
No curves appear in Tensorboard 25 when I click on a heading to open one.
Maybe related to #3782

### Environment info
Operating System: Ubuntu 14.04

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): 008bcaea38815f46804fc3f56492f4dd93837a56
2. The output of `bazel version` 0.3.0

**Comment by danmane** [comment] 2016-08-15 21:57
When you say no curves appear, do you mean that no charts appear, or that the charts appear without curves?

I suspect its a duplicate of #3750

**Closed by danmane** 2016-08-15 21:57 UTC

**Comment by rohitgirdhar** [comment] 2016-08-15 22:13
Yes it's the same issue; sorry didn't see it was already reported.
