### ISSUE TITLE
Tensorflow Quantum not installing in Colab

### ISSUE THREAD

**Issue by radres2019** [tensorflow/tensorflow#60428] opened 2023-04-27 21:03 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.7

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu

### Python version

3.11, 3.8

### Current Behaviour?

In attempting the tutorials in TFQ, Colab now says it does not recognize any TF less than 2.80 and therefore won't install TFQ 0.2.7. I attempted various other permutations of TF and TFQ versions but to no avail. 

### Standalone code to reproduce the issue

```shell
!pip install tensorflow==2.7.0 tensorflow-quantum==0.7.2
```

### Relevant log output

```shell
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==2.7.0
```
</details>

**Comment by synandi** [comment] 2023-04-28 09:32
Hi @radres2019, Thank you for reporting the issue!
You are seeing this error because Colab has python version 3.10. Tensorflow quantum 0.7.2 is compatible with Python 3.7, 3.8, 3.9  and does not support Python 3.10. 

Please refer to the gist where I was able to install Tensorflow quantum sucessfully [here](https://colab.sandbox.google.com/gist/synandi/b733cccf4a90d29e5feefb606f02f843/60428.ipynb). Thank you!

**Comment by Nischitkr** [comment] 2023-04-28 11:33
I think I can help you resolve this issue

**Comment by Nischitkr** [comment] 2023-04-28 11:34
It seems like you are trying to use TensorFlow Quantum (TFQ) on Colab, but you are getting an error when installing the TFQ package. According to the [installation guide](https://www.tensorflow.org/quantum/install) for TFQ, the current stable release of TFQ requires TensorFlow version 2.11.0, not 2.7.0. You can try changing your pip command to:

!pip install tensorflow==2.11.0 tensorflow-quantum==0.7.2

Alternatively, you can use the nightly builds of TFQ and TensorFlow with:

!pip install -U tfq-nightly

You can also check out some [tutorials](https://www.tensorflow.org/quantum/tutorials) on how to use TFQ on Colab, such as [Quantum Convolutional Neural Network](https://www.tensorflow.org/quantum/tutorials/qcnn).

**Comment by radres2019** [comment] 2023-04-28 15:29
> Hi @radres2019, Thank you for reporting the issue! You are seeing this error because Colab has python version 3.10. Tensorflow quantum 0.7.2 is compatible with Python 3.7, 3.8, 3.9 and does not support Python 3.10.
> 
> Please refer to the gist where I was able to install Tensorflow quantum sucessfully [here](https://colab.sandbox.google.com/gist/synandi/b733cccf4a90d29e5feefb606f02f843/60428.ipynb). Thank you!

Thank you so much for your assistance. This allows the installation now; however, I am unable to import cirq or tensorflow-quantum:

ModuleNotFoundError: No module named 'cirq'

ModuleNotFoundError: No module named 'tensorflow_quantum'

Perhaps this is installing these within a virtual environment?

**Comment by radres2019** [comment] 2023-04-28 15:32
Thank you for taking the time to help

> It seems like you are trying to use TensorFlow Quantum (TFQ) on Colab, but you are getting an error when installing the TFQ package. According to the [installation guide](https://www.tensorflow.org/quantum/install) for TFQ, the current stable release of TFQ requires TensorFlow version 2.11.0, not 2.7.0. You can try changing your pip command to:
> 
> !pip install tensorflow==2.11.0 tensorflow-quantum==0.7.2
> 
> Alternatively, you can use the nightly builds of TFQ and TensorFlow with:
> 
> !pip install -U tfq-nightly
> 
> You can also check out some [tutorials](https://www.tensorflow.org/quantum/tutorials) on how to use TFQ on Colab, such as [Quantum Convolutional Neural Network](https://www.tensorflow.org/quantum/tutorials/qcnn).

Thank you for taking the time to help me. I followed your instructions as well as the alternative strategies on the TFQ installation page, yet I receive this error when trying to install tensorflow-quantum==0.7.2:

ERROR: Could not find a version that satisfies the requirement tensorflow-quantum==0.7.2 (from versions: none)
ERROR: No matching distribution found for tensorflow-quantum==0.7.2

**Comment by synandi** [comment] 2023-05-10 04:37
@radres2019 
Apologies for the delay.
Looks like this is a duplicate of issue https://github.com/tensorflow/quantum/issues/768. Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2023-05-10 10:57 UTC
Labels: stat:awaiting response, type:build/install, subtype: ubuntu/linux, TF 2.7
