### ISSUE TITLE
cudnnFindConvolutionForwardAlgorithmEx vs cudnnGetConvolutionForwardAlgorithm

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8928] opened 2017-04-03 16:38 UTC
Following up on https://github.com/tensorflow/tensorflow/issues/7187#issuecomment-290284053, why does Tensorflow use [`cudnnGetConvolutionForwardAlgorithm`](https://github.com/tensorflow/tensorflow/blob/904edee4456a61d50d5b1ffe9858a7772acc423e/tensorflow/stream_executor/cuda/cuda_dnn.cc#L1844) rather than `cudnnFindConvolutionForwardAlgorithmEx`?  It looks like [Tensorflow tries to do the more complete profiling itself](https://github.com/tensorflow/tensorflow/blob/f8d8172c0086a42dfc1ed732fcf083dbd62c42e4/tensorflow/core/kernels/conv_ops.cc#L664-L689). 

For reference, `cudnnGetConvolutionForwardAlgorithm` serves as a heuristic for obtaining the best suited algorithm for cudnnConvolutionForward for the given layer specifications. Based on the input preference, this function will either return the fastest algorithm or the fastest algorithm within a given memory limit. For an exhaustive search for the fastest algorithm, please use `cudnnFindConvolutionForwardAlgorithm`.

Whereas:
`cudnnFindConvolutionForwardAlgorithmEx` function attempts all available cuDNN algorithms for cudnnConvolutionForward, using user-allocated GPU memory, and outputs performance metrics to a user-allocated array of cudnnConvolutionFwdAlgoPerf_t. These metrics are written in sorted fashion where the first element has the lowest compute time.

Looking at a number of other DNN, they seem to use `cudnnFindConvolutionForwardAlgorithmEx` / `cudnnFindConvolutionForwardAlgorithm`:
* [pytorch](https://github.com/pytorch/pytorch/blob/e50a1f19b3dc735f0710929b97b0af384aafe09b/torch/csrc/cudnn/Conv.cpp#L214) (when benchmark is on): 
* [Theano](https://github.com/Theano/Theano/blob/c6ffa460d43b6650aefbe7939f332084caafeaa4/theano/gpuarray/dnn_fwd.c#L125) (if `time_once` or `time_on_shape_change`)
* [cntk](https://github.com/Microsoft/CNTK/blob/5651d574c8f3fecf2533cf01beebaaa6e07453e2/Source/Math/CuDnnConvolutionEngine.cu#L229) (non-static finder)

/CC @Yangqing @zheng-xq

**Comment by asimshankar** [comment] 2017-04-03 17:39
@zheng-xq @vrv : Might one of you have some historical background on this choice, or general comments?

**Comment by zheng-xq** [comment] 2017-04-03 17:50
cudnnGetConvolutionForwardAlgorithm is the fallback path. By default, TensorFlow does the autotuning by itself before cudnnFindConvolutionForwardAlgorithmEx is available. Also the custom implementation enables us to filter out the noise through multiple run steps. At this point, cudnnFindConvolutionForwardAlgorithmEx doesn't seem to offer more functionalities to justify a change. 

In the future, the plan is to autotune both Cudnn algorithms and other custom kernels together, so we can also pick the fastest among both worlds.

**Comment by asimshankar** [comment] 2017-04-03 18:02
@cancan101 : Does that answer your question? (Will wait a while before closing this out as intended behavior)

**Comment by cancan101** [comment] 2017-04-03 18:06
Yea, it does make sense. As an aside, might be nice to logout the results of the profiling runs. I think pytorch  / torch7 [has an option to do this](https://github.com/soumith/cudnn.torch#modes).

**Comment by asimshankar** [comment] 2017-04-04 00:03
Thanks. Closing this out.

It might make sense for the selected algorithm to be logged either to the logging system or maybe in the `RunMetadata` protocol buffer. If you'd like to make a contribution towards that, we'll be glad to take a look!

**Closed by asimshankar** 2017-04-04 00:03 UTC
