### ISSUE TITLE
Error when using batch renormalisation option under a strategy

### ISSUE THREAD

**Issue by ahmadsalim** [tensorflow/tensorflow#31531] opened 2019-08-12 08:23 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS: Windows 10
- TensorFlow installed from (source or binary): tensorflow-gpu binary on pip
- TensorFlow version (use command below): 1.14
- Python version: 3.6.8
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When I try to use `renorm=True` with `tf.keras.layers.BatchNormalization` under `tf.distribute.MirroredStrategy` I get the following error: `handle` is not available outside the replica context or a `tf.distribute.Strategy.update()` call.

**Describe the expected behavior**
I can use batch renormalisation under mirrored strategy.

**Code to reproduce the issue**
```
import tensorflow as tf

strat = tf.distribute.MirroredStrategy()
with strat.scope():
  inp = tf.keras.Input((28, 28))
  tf.keras.layers.BatchNormalization(renorm=True)(inp)
```

**Other info / logs**

The following is the stack trace:
```
<ipython-input-3-d17cda041220> in <module>()
      2 with strat.scope():
      3   inp = tf.keras.Input((28, 28))
----> 4   tf.keras.layers.BatchNormalization(renorm=True)(inp)

16 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    632                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    633                 else:
--> 634                   outputs = call_fn(inputs, *args, **kwargs)
    635 
    636             except TypeError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in call(self, inputs, training)
    734       if self.renorm:
    735         r, d, new_mean, new_variance = self._renorm_correction_and_moments(
--> 736             new_mean, new_variance, training, inputs_size)
    737         # When training, the normalized values (say, x) will be transformed as
    738         # x * gamma + beta without renorm, and (x * r + d) * gamma + beta

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _renorm_correction_and_moments(self, mean, variance, training, inputs_size)
    598     new_mean = _update_renorm_variable(self.renorm_mean,
    599                                        self.renorm_mean_weight, mean,
--> 600                                        inputs_size)
    601     new_stddev = _update_renorm_variable(self.renorm_stddev,
    602                                          self.renorm_stddev_weight, stddev,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _update_renorm_variable(var, weight, value, inputs_size)
    593       def _fake_update():
    594         return array_ops.identity(var)
--> 595       return tf_utils.smart_cond(training, _do_update, _fake_update)
    596 
    597     # TODO(yuefengz): colocate the operations

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in smart_cond(pred, true_fn, false_fn, name)
     56         pred, true_fn=true_fn, false_fn=false_fn, name=name)
     57   return smart_module.smart_cond(
---> 58       pred, true_fn=true_fn, false_fn=false_fn, name=name)
     59 
     60 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     57   else:
     58     return control_flow_ops.cond(pred, true_fn=true_fn, false_fn=false_fn,
---> 59                                  name=name)
     60 
     61 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in cond(pred, true_fn, false_fn, strict, name, fn1, fn2)
   1975     try:
   1976       context_t.Enter()
-> 1977       orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
   1978       if orig_res_t is None:
   1979         raise ValueError("true_fn must have a return value.")

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in BuildCondBranch(self, fn)
   1812     """Add the subgraph defined by fn() to the graph."""
   1813     pre_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
-> 1814     original_result = fn()
   1815     post_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
   1816     if len(post_summaries) > len(pre_summaries):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _do_update()
    582           weight_value = array_ops.constant(1., dtype=weight.dtype)
    583         new_var = self._assign_moving_average(var, value, self.renorm_momentum,
--> 584                                               inputs_size)
    585         new_weight = self._assign_moving_average(weight, weight_value,
    586                                                  self.renorm_momentum,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _assign_moving_average(self, variable, value, momentum, inputs_size)
    447   def _assign_moving_average(self, variable, value, momentum, inputs_size):
    448     with K.name_scope('AssignMovingAvg') as scope:
--> 449       with ops.colocate_with(variable):
    450         decay = ops.convert_to_tensor(1.0 - momentum, name='decay')
    451         if decay.dtype != variable.dtype.base_dtype:

/usr/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _colocate_with_for_gradient(self, op, gradient_uid, ignore_existing)
   4398   def _colocate_with_for_gradient(self, op, gradient_uid,
   4399                                   ignore_existing=False):
-> 4400     with self.colocate_with(op, ignore_existing):
   4401       if gradient_uid is not None and self._control_flow_context is not None:
   4402         self._control_flow_context.EnterGradientColocation(op, gradient_uid)

/usr/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in colocate_with(self, op, ignore_existing)
   4447       raise ValueError("Trying to reset colocation (op is None) but "
   4448                        "ignore_existing is not True")
-> 4449     op = _op_to_colocate_with(op)
   4450 
   4451     # By default, colocate_with resets the device function stack,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _op_to_colocate_with(v)
   6714   # happen soon, perhaps this hack to work around the circular
   6715   # import dependency is acceptable.
-> 6716   if hasattr(v, "handle") and hasattr(v.handle, "op") and isinstance(
   6717       v.handle.op, Operation):
   6718     return v.handle.op

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/values.py in handle(self)
    641       device = distribute_lib.get_update_device()
    642       if device is None:
--> 643         raise ValueError("`handle` is not available outside the replica context"
    644                          " or a `tf.distribute.Strategy.update()` call.")
    645     return self.get(device=device).handle
```

**Comment by rmothukuru** [comment] 2019-08-13 10:36
Could reproduce this issue with Tensorflow Version 1.14. Gist is in [this link](https://colab.sandbox.google.com/drive/1wYqgjX92dhHmOBH1-Q9u_XQ0ckoY5TSJ#scrollTo=v3HKUlHOhuLa). 

Thanks.

**Comment by isaprykin** [comment] 2019-08-15 18:07
Thanks, this seems to be real issue.  We are going to try to fix it.

**Comment by isaprykin** [comment] 2019-08-15 18:07
@rmothukuru could you please update the permissions on that link?

**Comment by jvishnuvardhan** [comment] 2019-08-15 21:16
@isaprykin [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1dcc12d3ab39170115bc7aa066f4d3e5/tf_31531.ipynb) is the gist. The same error is in `tf-nightly-gpu` along with `tensorflow==1.14.0`. Same error is in TF2.0 and the [gist is here](https://colab.sandbox.google.com/gist/jvishnuvardhan/127973ecc9e4087b2d018c4e52452c35/tf20_31531_batchnorm.ipynb). Thanks!

**Comment by ghannum** [comment] 2019-10-31 19:49
I am running into this issue as well. Any update on the fix?

**Comment by fbmoreira** [comment] 2019-12-17 18:02
Any updates on this?

**Comment by faroit** [comment] 2020-01-13 13:48
still existing in tf 2.1

**Comment by orwa-te** [comment] 2020-07-10 13:19
Hello there,
Any update on this issue?!!

**Comment by ghannum** [comment] 2020-07-10 14:45
Is there a system for voting on issue priority? This one is a real showstopper for training large models.

**Comment by orwa-te** [comment] 2020-07-11 07:16
I tried updating my TensorFlow to the latest version (2.2.0) and it fixed the issue for me

**Comment by ryangillard** [comment] 2020-07-31 18:38
Still have this issue in TF 2.1.0, 2.2.0, and 2.3.0 all for CPU and GPU (with Intel MKL-DNN/MKL and CUDA 10.1). This is in Debian 9, GCP CAIP Notebook env, python 3.7.6.

It seems to be mostly fixed in tf-nightly 2.4.0-dev20200731 using fit, however with a custom training loop the number of gradients fails the below assertion. My guess is gamma and beta aren't being picked up either in the func_graph outputs (LHS) or in the model.trainable_variables (RHS).

`        gradients = gradient_tape.gradient(
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py:1083 gradient  **
        unconnected_gradients=unconnected_gradients)
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py:162 _gradient_function
        return grad_fn(mock_op, *out_grads)
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py:123 _IfGrad
        true_graph, grads, util.unique_grad_fn_name(true_graph.name))
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py:386 _create_grad_func
        func_graph=_CondGradFuncGraph(name, func_graph))
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:986 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py:385 <lambda>
        lambda: _grad_fn(func_graph, grads), [], {},
    /home/jupyter/.local/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py:361 _grad_fn
        assert len(func_graph.outputs) == len(grads)

    AssertionError: `

Code used:
`import tensorflow as tf

strat = tf.distribute.MirroredStrategy()
with strat.scope():
    inp = tf.keras.Input((28, 28))
    tf.keras.layers.BatchNormalization(renorm=True)(inp)`

**Comment by d-miketa** [comment] 2020-10-26 18:24
I have the same issue as @ryangillard in TF 2.3.1 using batch normalization in a custom training loop.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:05
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:55 UTC
Labels: TF 1.14, comp:dist-strat, stat:awaiting tensorflower, type:bug

**Comment by anth2o** [comment] 2021-11-08 15:10
I think this issue is still present in TF2.5. I opened an other issue since I'm having the same bug or only a similar one: #52986
