### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Jonarain** [tensorflow/tensorflow#22890] opened 2018-10-11 09:17 UTC
please help me

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
2018-10-11 18:04:48.044220: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-10-11 18:04:48.293316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2018-10-11 18:04:48.305478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-11 18:04:49.064648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-11 18:04:49.075159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-10-11 18:04:49.079229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-10-11 18:04:49.084288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4699 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-10-11 18:05:04.242432: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 4.59G (4927577088 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
WARNING:tensorflow:From D:\Project\practice_pysc2\RDRL\rl\model.py:63: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
W1011 18:05:41.685944 12328 tf_logging.py:125] From D:\Project\practice_pysc2\RDRL\rl\model.py:63: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Engineer\Anaconda\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Engineer\Anaconda\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 页面文件太小，无法完成操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Engineer\Anaconda\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Engineer\Anaconda\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Engineer\Anaconda\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Engineer\Anaconda\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Engineer\Anaconda\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Engineer\Anaconda\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Engineer\Anaconda\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Project\practice_pysc2\RDRL\main.py", line 3, in <module>
    import tensorflow as tf
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Engineer\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Engineer\Anaconda\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Engineer\Anaconda\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 页面文件太小，无法完成操作。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
2018-10-11 18:05:48.218204: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at constant_op.cc:207 : Resource exhausted: OOM when allocating tensor with shape[76800,256] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

**Comment by tensorflowbutler** [comment] 2018-10-11 18:52
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Jonarain** [comment] 2018-10-16 07:07
> 
> 
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce
> Mobile device

Thanks for your comments
im sorry for the late reply

> Have I written custom code
 I think I did not write custom code

> OS Platform and Distribution
win10

> TensorFlow installed from
I installed all package by Anaconda3 include Tensorflow

> TensorFlow version
1.10.0

> Bazel version
not installed

> CUDA/cuDNN version
CUDA 9.0    cuDNN 7.1.4

> GPU model and memory
Nvidia Geforce GTX 1060   6GB

> Exact command to reproduce
I tried to running code from https://github.com/inoryy/pysc2-rl-agent

**Comment by tensorflowbutler** [comment] 2018-11-03 12:33
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-11-14 18:48
@Jonarain I apologize for my delayed response. Is this still an issue for you? From the snap you have provided, its complaining about running low on GPU memory for your computation. To free some memory, Can you try by aborting all python processes which require GPU computation and execute the script in a new terminal window?

**Comment by ymodak** [comment] 2018-11-21 18:09
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-21 18:09 UTC
Labels: stat:awaiting response, type:build/install
