### ISSUE TITLE
Cannot import tf.keras.engine

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#33786] opened 2019-10-28 14:55 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14 and 2.0 (gpu)
- Python version: 3.6.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10/6.7.4
- GPU model and memory: RTX 2060 6GB

After switching my code to tf.keras I cannot import tf.keras.engine:
with Keras:
```
import keras.layers as KL
import keras.models as KM
import keras.engine as KE
```
`>>>OK`

with tf.keras:
```
import tensorflow.keras.layers as KL
import tensorflow.keras.models as KM
import tensorflow.keras.engine as KE
```

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-004966c96ded> in <module>
      1 import tensorflow.keras.layers as KL
      2 import tensorflow.keras.models as KM
----> 3 import tensorflow.keras.engine as KE

ModuleNotFoundError: No module named 'tensorflow.keras.engine'
```

**Comment by Sooryakiran** [comment] 2019-10-28 18:57
Hi,
You are not able to import it because the is no module tensorflow.keras.engine.

This answer might help you:
https://stackoverflow.com/questions/51337558/how-to-import-keras-engine-topology-in-tensorflow

Similar functionalities are provided by tf in other modules.

**Comment by ravikyram** [comment] 2019-10-29 07:13
I have tried on colab with TF version 2.0 ,1.14, 1.15.0-rc3, 2.1.0-dev20191028 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/857ee7fdf5e48e7e54c913f8eaf91624/untitled308.ipynb) Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-29 21:50
@kiflowb777 As mentioned by @Sooryakiran there is no module named 'tensorflow.keras.engine'. All of the submodules unders the `keras.engine` are under different modules within `tf.keras`. I am sure you are trying to migrate from `keras` to `tf.keras`. In the process, if you notice any bugs, please file them as new issues.

I am closing this issue as it is resolved. Please feel free to open a new issue when you notice any bug. Thanks!

**Closed by jvishnuvardhan** 2019-10-29 21:50 UTC
Labels: TF 1.14, TF 1.15, TF 2.0, comp:keras, type:bug

**Comment by danielgarzonotero** [comment] 2024-10-10 15:04
The error ModuleNotFoundError: No module named 'tensorflow.keras.engine' occurs because the structure of tensorflow.keras has changed in recent versions of TensorFlow (from TensorFlow 2.x onwards).

In newer versions, the tensorflow.keras.engine module has been removed or reorganized. Instead, you should use the updated modules. Here's how to fix the error:

**from tensorflow.keras.engine import Layer**

Should be changed to:

**from tensorflow.keras.layers import Layer**
