### ISSUE TITLE
windows bazel build failed: undeclared inclusion 

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#11985] opened 2017-08-03 03:24 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
2ab9cb209babf905091dcff2f7cdce38da616cfe
- **Python version**: 
3.5.3
- **Bazel version (if compiling from source)**:
0.5.3
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:
None
- **Exact command to reproduce**:
bazel --output_base C:\t  build  //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
ERROR: C:/os/tensorflow/tensorflow/core/BUILD:1271:1: undeclared inclusion(s) in rule '//tensorflow/core:lib_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/framework/variant_tensor_data.cc':
  'C:/os/tensorflow/tensorflow/core/framework/tensor.h'
  'C:/os/tensorflow/tensorflow/core/framework/allocator.h'
  'C:/os/tensorflow/tensorflow/core/framework/numeric_types.h'
  'C:/os/tensorflow/tensorflow/core/framework/type_traits.h'
  'C:/os/tensorflow/tensorflow/core/framework/variant.h'
  'C:/os/tensorflow/tensorflow/core/framework/type_index.h'
  'C:/os/tensorflow/tensorflow/core/framework/tensor_shape.h'
  'C:/os/tensorflow/tensorflow/core/framework/tensor_types.h'
  'C:/os/tensorflow/tensorflow/core/framework/types.h'
  'C:/os/tensorflow/tensorflow/core/framework/bfloat16.h'

### Source code / logs

**Comment by snnn** [comment] 2017-08-03 03:25
If no one is working on this, I'll take it.

**Comment by StatML** [comment] 2017-08-03 05:57
Hi, @snnn I met the following problem when building from source. Do you know how to fix it? Thx!

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04.4
TensorFlow installed from (source or binary):
source
TensorFlow version (use command below):

Python version:
3.5.3
Bazel version (if compiling from source):
0.5.3
CUDA/cuDNN version:
6.0.21
GPU model and memory:

Exact command to reproduce:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

> tensorflow-git$ sudo bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
WARNING: ignoring http_proxy in environment.
.......
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
INFO: Elapsed time: 4.064s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by meteorcloudy** [comment] 2017-08-03 09:19
Culprit is https://github.com/tensorflow/tensorflow/commit/7ed4beea18c2aecaa0a1f600427e8452933df7b3

I've commented on the internal change.

**Comment by poxvoculi** [comment] 2017-08-03 21:07
Looks like fix is on its way.  Assigning to @gunan for tracking.

**Closed** 2017-08-08 18:40 UTC
Labels: type:bug/performance
