### ISSUE TITLE
build_pip_package error on Mac+Python3

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1033] opened 2016-02-09 19:05 UTC
See detailed build log at: http://ci.tensorflow.org/view/Experimental/job/experimental-cais-tensorflow-mac-python3-copt_pip_install-test/1/consoleFull

> In file included from tensorflow/core/kernels/conv_ops.cc:22:
> In file included from ./tensorflow/core/framework/numeric_op.h:19:
> In file included from ./tensorflow/core/framework/op_kernel.h:22:
> In file included from ./tensorflow/core/framework/allocator.h:25:
> In file included from ./tensorflow/core/framework/type_traits.h:22:
> In file included from ./tensorflow/core/framework/types.h:23:
> In file included from third_party/eigen3/unsupported/Eigen/CXX11/Tensor:2:
> In file included from external/eigen_archive/eigen-eigen-8cd7c2c6e9e1/unsupported/Eigen/CXX11/Tensor:92:
> external/eigen_archive/eigen-eigen-8cd7c2c6e9e1/unsupported/Eigen/CXX11/src/Tensor/TensorContractionBlocking.h:29:31: error: no type named 'Scalar' in 'Eigen::internal::TensorContractionInputMapper<float, long, 0, Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<const Eigen::DSizes<long, 2>, const Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const float, 4, 1, long>, 16> > >, Eigen::ThreadPoolDevice>, Eigen::array<long, 1>, Eigen::array<long, 1>, 4, false, false, 0>'
>   typedef typename RhsMapper::Scalar RhsScalar;
>           ~~~~~~~~~~~~~~~~~~~~^~~~~~

This error doesn't occur if Python2 is used on Mac.

**Comment by martinwicke** [comment] 2016-02-09 23:46
Probably a swig difference.

**Comment by martinwicke** [comment] 2016-02-10 02:21
@benoitsteiner have you seen this before? It only happens if you configure for python3, on a Mac, so I'm assuming it's a swig issue, but it's deep inside Eigen, so maybe you have an idea?

**Comment by benoitsteiner** [comment] 2016-02-10 18:01
@caisq It looks like you're fetching an older version of Eigen. How recently have you sync'ed with the TensorFlow repository? A similar issue has been reported either last week or a couple of weeks ago and fixed since. I wonder if you have the fix in your codebase.

**Comment by caisq** [comment] 2016-02-10 18:44
@benoitsteiner Today I ran the build again and this time the compilation error didn't occur: 
http://ci.tensorflow.org/view/Experimental/job/experimental-cais-tensorflow-mac-python3-copt_pip_install-test/3/consoleFull

My branch has been synced with the TensorFlow master. So not sure what changed. Do you think adding "bazel clean" before every build (which I'm not currently doing) will help?

**Comment by benoitsteiner** [comment] 2016-02-11 01:53
I have noticed that calling bazel clean every time you sync can help. bazel caches a lot of build data internally and it may not always properly react when the WORKSPACE file changes.

**Comment by martinwicke** [comment] 2016-02-11 03:07
Should we report this to bazel? Changing the workspace file is cheating, in
a way. I don't know many build systems that can work with that, but maybe
bazel should aspire to more?

**Comment by caisq** [comment] 2016-02-11 04:29
@benoitsteiner @martinwicke @vrv Hmm...  Although the C++ compilation error seems to be gone for now, there is another problem: Many of the Python unit tests fail under Mac+Python3:
`bazel test -c opt //tensorflow/python/...`

> Executed 155 out of 155 tests: 109 tests passed and 46 failed locally. 

Note that the same build worked perfectly under Mac+Python2. 

Similarly, a lot of the Python uni tests failed during the Python3 pip test-on-install. 

For detailed error logs, see:
http://ci.tensorflow.org/view/Experimental/job/experimental-cais-tensorflow-mac-python3-copt_pip_install-test/11/console

A lot of them show things like:

> tensorflow.python.pywrap_tensorflow.StatusNotOK: Out of range: FIFOQueue '_20_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: ReaderRead = ReaderRead[_device="/job:localhost/replica:0/task:0/cpu:0"](test_reader, fifo_queue)]]

> tensorflow.python.pywrap_tensorflow.StatusNotOK: Invalid argument: _ProdGrad NaN test : Tensor had NaN values
> 	 [[Node: CheckNumerics = CheckNumerics[T=DT_FLOAT, message="_ProdGrad NaN test", _device="/job:localhost/replica:0/task:0/cpu:0"](CheckNumerics/tensor)]]

> ......W tensorflow/core/common_runtime/executor.cc:1094] 0x7fc314c15bd0 Compute status: Invalid argument: batch_dim == seq_dim == 0
> 	 [[Node: ReverseSequence_3 = ReverseSequence[T=DT_FLOAT, batch_dim=0, seq_dim=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_6_0, _recv_Placeholder_7_0)]]
> F.

...

**Comment by martinwicke** [comment] 2016-02-11 05:56
No changes to the repo happened in the period between the last passing test and the first failing test. So it should be in the Jenkins config. Did you change anything there around 4pm EST today?

**Comment by caisq** [comment] 2016-02-11 14:04
@martinwicke Sorry I didn't make it clear: The passing build I showed earlier was actually using Python2, not Python3 as it was meant to use.  This is a tools issue that will be fixed in PR https://github.com/tensorflow/tensorflow/pull/1051 
This has nothing to do with Jenkins. I did it on the Mac slave without Jenkins or Docker and got the errors. 

Can you try it on your Mac with Python3? 
```
bazel clean
bazel test -c opt //tensorflow/python/...
```

**Comment by caisq** [comment] 2016-02-11 16:10
@martinwicke @benoitsteiner @vrv Further information: I thought this might have to do with the special bazel flags required in Mac. So I tested the following flag combinations for "bazel test //tensorflow/python/..."

```
-c opt	
--linkopt=headerpad_max_install_names
-c opt --linkopt=headerpad_max_install_names
-c opt --genrule_strategy=standalone --linkopt=headerpad_max_install_names
```

All of them failed in the same way, i.e., 46 of the 151 Python unit tests failed.

**Comment by martinwicke** [comment] 2016-02-11 21:52
Testing now

**Comment by martinwicke** [comment] 2016-02-11 22:46
It seems to be a problem with exceptions. All the errors I see are of the form:

```
FAIL: testBadDefault (__main__.SparseToDenseTest)
----------------------------------------------------------------------
tensorflow.python.pywrap_tensorflow.StatusNotOK: Invalid argument: default_value
 should be a scalar.
         [[Node: SparseToDense = SparseToDense[T=DT_INT32, Tindices=DT_INT32, va
lidate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseToDe
nse/sparse_indices, SparseToDense/output_shape, SparseToDense/sparse_values, SparseToDense/default_value)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_wicke/83710fbf544c1dff5a44a1c6171bc2ec/tensorflow/bazel-out/local_darwin-py3-opt/bin/tensorflow/python/sparse_to_dense_op_py_test.runfiles/tensorflow/python/framework/test_util.py", line 497, in assertRaisesWithPredicateMatch
    yield
  File "/private/var/tmp/_bazel_wicke/83710fbf544c1dff5a44a1c6171bc2ec/tensorflow/bazel-out/local_darwin-py3-opt/bin/tensorflow/python/sparse_to_dense_op_py_test.runfiles/tensorflow/python/kernel_tests/sparse_to_dense_op_py_test.py", line 112, in testBadDefault
    dense.eval()
  File "/private/var/tmp/_bazel_wicke/83710fbf544c1dff5a44a1c6171bc2ec/tensorflow/bazel-out/local_darwin-py3-opt/bin/tensorflow/python/sparse_to_dense_op_py_test.runfiles/tensorflow/python/framework/ops.py", line 465, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
SystemError: <built-in function delete_Status> returned a result with an error set
```

That final system error is the problem. I think these are the tests that have at least one test method which relies on an exception somewhere.

**Comment by martinwicke** [comment] 2016-02-12 02:16
Duplicate of #830, closing this one.

**Closed by martinwicke** 2016-02-12 02:16 UTC
