### ISSUE TITLE
FP16 Batch Matmul still does not run

### ISSUE THREAD

**Issue by dingsiyu** [tensorflow/tensorflow#21467] opened 2018-08-08 02:32 UTC
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Slightly.

OS Platform and Distribution : centos6.3

TensorFlow installed from: conda

TensorFlow version (use command below): v1.8.0(it already has the code TF_CALL_half(REGISTER_BATCH_MATMUL_GPU);)

Python version: 3.6

CUDA/cuDNN version: 9.2

GPU model and memory: V100 

Exact command to reproduce:

with tf.device("/gpu:0"):
    a = tf.random_normal(dtype=tf.float16, shape=[5, 2, 3], name='a')
    b = tf.random_normal(dtype=tf.float16, shape=[5, 3, 2], name='b')
    c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True, allow_soft_placement=False))
print(sess.run(c).shape)

the problem:

Source code / logs

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'MatMul_1': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]

         [[Node: MatMul_1 = BatchMatMul[T=DT_HALF, adj_x=false, adj_y=false, _device="/devic

**Comment by Zrachel** [comment] 2018-08-08 03:40
I meet the same problem, with code:
```
import tensorflow as tf
a = tf.random_normal(dtype=tf.float16, shape=[5, 2, 3], name='a')
b = tf.random_normal(dtype=tf.float16, shape=[5, 3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True, allow_soft_placement=False))
print(sess.run(c).shape)
tf.__version__
```


, tf 1.8.0 shows:
```
>>> print(sess.run(c).shape)
b/RandomStandardNormal: (RandomStandardNormal): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832338: I tensorflow/core/common_runtime/placer.cc:886] b/RandomStandardNormal: (RandomStandardNormal)/job:localhost/replica:0/task:0/device:GPU:0
b/mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832374: I tensorflow/core/common_runtime/placer.cc:886] b/mul: (Mul)/job:localhost/replica:0/task:0/device:GPU:0
b: (Add): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832389: I tensorflow/core/common_runtime/placer.cc:886] b: (Add)/job:localhost/replica:0/task:0/device:GPU:0
a/RandomStandardNormal: (RandomStandardNormal): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832404: I tensorflow/core/common_runtime/placer.cc:886] a/RandomStandardNormal: (RandomStandardNormal)/job:localhost/replica:0/task:0/device:GPU:0
a/mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832417: I tensorflow/core/common_runtime/placer.cc:886] a/mul: (Mul)/job:localhost/replica:0/task:0/device:GPU:0
a: (Add): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832431: I tensorflow/core/common_runtime/placer.cc:886] a: (Add)/job:localhost/replica:0/task:0/device:GPU:0
MatMul: (BatchMatMul): /job:localhost/replica:0/task:0/device:CPU:0
**2018-08-08 11:36:17.832439: I tensorflow/core/common_runtime/placer.cc:886] MatMul: (BatchMatMul)/job:localhost/replica:0/task:0/device:CPU:0**
b/stddev: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832454: I tensorflow/core/common_runtime/placer.cc:886] b/stddev: (Const)/job:localhost/replica:0/task:0/device:GPU:0
b/mean: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832468: I tensorflow/core/common_runtime/placer.cc:886] b/mean: (Const)/job:localhost/replica:0/task:0/device:GPU:0
b/shape: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832482: I tensorflow/core/common_runtime/placer.cc:886] b/shape: (Const)/job:localhost/replica:0/task:0/device:GPU:0
a/stddev: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832495: I tensorflow/core/common_runtime/placer.cc:886] a/stddev: (Const)/job:localhost/replica:0/task:0/device:GPU:0
a/mean: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832509: I tensorflow/core/common_runtime/placer.cc:886] a/mean: (Const)/job:localhost/replica:0/task:0/device:GPU:0
a/shape: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2018-08-08 11:36:17.832522: I tensorflow/core/common_runtime/placer.cc:886] a/shape: (Const)/job:localhost/replica:0/task:0/device:GPU:0
(5, 2, 2)
```

Environment:
python 2.7
tf 1.8.0 installed from pip (pip install tensorflow-gpu==1.8.0 -t $PYTHONHOME/lib/python2.7/)
V100,  driver 396.26
cuda9.2,  cudnn7

**Comment by tensorflowbutler** [comment] 2018-08-23 19:10
Nagging Assignee @robieta: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-10 18:49
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by smit-hinsu** [comment] 2018-09-12 01:36
Duplicate of #21226

**Closed by smit-hinsu** 2018-09-12 01:36 UTC
