### ISSUE TITLE
Session::Run() allocates a lot of memory after the first call

### ISSUE THREAD

**Issue by zo7** [tensorflow/tensorflow#15669] opened 2017-12-27 22:03 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**: Binary ([CPU C API](https://www.tensorflow.org/install/install_c))
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

I am working on an application that deploys several TensorFlow models using TensorFlow's C API. I have noticed that there seems to be a behavior where TensorFlow takes a long time to run the first time `TF_SessionRun()` is called, and it allocates a lot of extra memory that hangs around until the session is destroyed. In my case, my program's memory footprint is ~85MB after all of the models are loaded (which makes sense, that's about how large the model .pb files are on disk) but after the first call to `TF_SessionRun()` it jumps to ~250MB. After profiling my code it appears that TensorFlow is the culprit, and I've observed similar behavior on Android as well.

TensorFlow seems to be doing some lazy initialization, but there doesn't appear to be much documentation or discussion about this. Could someone shed some light on what is happening here? Why does it require so much memory? Is this a bug or expected behavior?

### Source code / logs

Here's a memory call tree from Xcode showing *persistent* memory allocations after the first call to `TF_SessionRun()` for one of my models:

<img width="996" alt="screen shot 2017-12-27 at 1 14 59 pm" src="https://user-images.githubusercontent.com/3229244/34394457-1af8625c-eb0e-11e7-8cd8-ff61737dcb50.png">

Let me know if there is any more information that I can provide. I'm curious what's going on here.

**Comment by bignamehyp** [comment] 2017-12-28 19:36
This is kind of expected since tensorflow also runs graph rewriting code to optimize the graph.

**Comment by tensorflowbutler** [comment] 2018-01-12 18:59
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by zo7** [comment] 2018-01-12 20:40
Not sure if waiting for a response from me – but if it runs a graph optimization step why is the memory usage so large? Does it do a deep copy of the old graph+weights but persists the unoptimized graph somewhere?

We are trying to use TF in a somewhat memory-sensitive environment, so we currently delete the TF session when we don't need it. This is less than ideal though, since the next time we need it we have to re-load the graph from file and let TF do this graph optimization process again.

**Comment by tensorflowbutler** [comment] 2018-01-23 22:55
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by reedwm** [comment] 2018-01-30 00:32
@mrry, can you comment? It looks like the constant op is taking some memory from the memory call tree.

**Comment by mrry** [comment] 2018-01-30 00:50
> Does it do a deep copy of the old graph+weights but persists the unoptimized graph somewhere?

Yes, it does. There's currently no API to release the unoptimized graph, which must be kept around because the Session API allows the user to execute node in the graph. The current `ConstantOp` implementation also keeps two copies of the constant data in memory, in the `NodeDef` and in a `Tensor` object.

To avoid this blowup in memory consumption, you might be better off using the [`ConvertConstantsToImmutable()` utility](https://github.com/tensorflow/tensorflow/blob/4ab2d8531c461169cd6a33bc0fef1129b419e9df/tensorflow/contrib/util/convert_graphdef_memmapped_format_lib.h#L28), which removes large constants from the graph and replaces them with a mmappable form.

/cc @gunan @aselle

**Comment by skye** [comment] 2018-02-06 23:35
I'm closing this given mrry@'s at response. Please reopen if you think this is something that a community member could work on.

**Closed by skye** 2018-02-06 23:35 UTC

**Comment by mrry** [comment] 2018-02-06 23:53
FWIW, fc09f65a5d283baa9af182536e3e3652c7a41dd7 should halve the amount of memory that is consumed by each `tensorflow::ConstantOp` object. The first `Run()` call will probably still cause a spike in memory consumption, since there are other copies of the `ConstantOp` data that will be retained, but it should be a little less tall now.

**Comment by Hema414** [comment] 2021-05-23 16:16
@mrry  I am facing similar issue. 
I am using a SCNN model, model size is 90MB.
In Windows, during the first call to the session->Run, the working set memory increases 200MB and the peak working set increases by 600MB. 

Is this still a expected behavior ?
