### ISSUE TITLE
tf.keras.utils.multi_gpu_model use only one GPU when using sequential model

### ISSUE THREAD

**Issue by mungsoo** [tensorflow/tensorflow#30330] opened 2019-07-03 01:21 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.14
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
The tf.keras.utils.multi_gpu_model doesn't work well with sequential model. Only one GPU is working.
**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone who use keras with multi-gpu system.

**Any Other info.**

**Comment by rmothukuru** [comment] 2019-07-04 12:33
@mungsoo ,
Thank you for pointing this out. Can you please provide a reproducible code snippet which helps us in identifying the location of bug exactly.

**Comment by rmothukuru** [comment] 2019-07-15 06:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-07-15 06:28 UTC
Labels: stat:awaiting response, type:bug/performance
