### ISSUE TITLE
feature request: "a trou"  (with hole algorithm)

### ISSUE THREAD

**Issue by laurentk67** [tensorflow/tensorflow#1815] opened 2016-04-07 19:48 UTC
To generate dense feature maps (e.g. semantic segmentation) the convolution and the maxpooling operators should have the option to define "holes" in the kernel.
The concept is used  in the paper:
Semantic Image Segmentation with Deep Convolutional Nets and Fully Connected CRFs
(Liang-Chieh Chen, George Papandreou, Iasonas Kokkinos, Kevin Murphy, Alan L. Yuille)

and it is implemented in the excellent  deeplab library based on Caffe.

**Comment by martinwicke** [comment] 2016-04-08 00:10
I believe this is a duplicate of #889, which contains a workaround. I'll close this one, but we still have to fix it.

**Comment by vrv** [comment] 2016-04-08 00:11
It's not a duplicate, atrous convolution is adding holes in the input patch, whereas #889 is about dense patches.

**Comment by laurentk67** [comment] 2016-04-08 02:22
Hello Martin,

Thanks for the super quick reply.
I attached a short PPT to illustrate the a-trou Algorithm.

Let me know if you need additional details.
Your tutorial on deep dream was great !!

**Comment by fyu** [comment] 2016-04-08 04:32
For future reference, this is supported in Caffe master branch now and it is one of the features in Caffe rc3 https://github.com/BVLC/caffe/releases/tag/rc3. It is called dilation in convolution parameter and added by pull request https://github.com/BVLC/caffe/pull/3487.

There was detailed discussion about whether this feature should be named dilation, hole or atrous in this pull request https://github.com/BVLC/caffe/pull/3452. Relevant discussion started on Dec 18, 2015 in the pull request. This feature is eventually called dilation in convolution or dilated convolution following the term in Holschneider et al. (1987). The Caffe developers concluded that "dilated convolution" is a historically more accurate name than "à trous convolution".

**Comment by martinwicke** [comment] 2016-04-08 15:32
@gpapan I assigned you based on your email to @yaroslavvb. Thanks!

**Comment by gpapan** [comment] 2016-04-15 14:00
Thanks. This will be ready in the next few days.

**Comment by gpapan** [comment] 2016-04-22 01:18
The change is in the process of being committed to github's Tensorflow.

**Closed** 2016-04-22 17:42 UTC
Labels: contributions welcome, enhancement

**Comment by fyu** [comment] 2016-04-22 17:59
Thank @gpapan to add this to TensorFlow!

**Comment by gpapan** [comment] 2016-04-27 17:14
You are very welcome @fyu! Hope that people find this feature useful.

**Comment by laurentk67** [comment] 2016-04-28 08:06
Hi,
Thank you for having implemented the new feature. I'm doing some test and so far it looks great. What is the reason the regular stride parameter has been removed from the API ? 
Does it make sense to have dilated input map processed with different overlapped receptive field (stride parameter) ?

all the best
Laurent

**Comment by gpapan** [comment] 2016-04-28 16:48
@laurentk67 
I have not yet come across a use case that needs both stride > 1 and rate > 1, so I decided to omit the stride parameter from the API:
You typically use atrous_conv2d() in order to preserve the spatial resolution of your input feature map, whereas conv2d() with stride greater than one lowers the resolution. Not exposing conv2d's stride parameter thus prevents the user from using atrous convolution incorrectly. If some legitimate use case of atrous convolution comes up where both stride and rate may be greater than one, we can easily add a stride parameter and pass it along to conv2d().

**Comment by chris-scott** [comment] 2016-05-17 16:52
Having atrous convolution in TensorFlow is great - thank you @gpapan. I'd like access to strides for learning multi-scale raw audio filters, where using a stride of 1 is computationally infeasible.

**Comment by martinwicke** [comment] 2016-05-17 22:28
You should file a new issue with that feature request, I doubt it will be seen hidden in this thread.
