### ISSUE TITLE
TFLite Micro, bugfix for MicroAllocator::AllocateTensors()

### ISSUE THREAD

**Issue by driedler** [tensorflow/tensorflow#34057] opened 2019-11-07 03:02 UTC
Latest master:
tensorflow/lite/experimental/micro/micro_allocator.cc

`MicroAllocator::AllocateTensors()`

```
    for (size_t n = 0; n < op->outputs()->size(); ++n) {
      const int tensor_index = op->outputs()->Get(n);
      TensorInfo* current = &tensor_info[tensor_index];
      if ((current->first_created == -1) || (current->first_created > i)) {
        current->first_created = i;
      }
```

The operations list is iterated in reverse so need to change:
```(current->first_created > i)```
 to 
```(current->first_created < i)```

**Comment by MeghnaNatraj** [comment] 2019-11-21 21:57
The latest copy of the file has the updated fix -- [tensorflow/lite/experimental/micro/micro_allocator.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/micro_allocator.cc#L279)

Closing the issue as it seems to be resolved.

**Closed** 2019-11-21 21:58 UTC
Labels: comp:lite, stat:awaiting tensorflower, type:support

**Comment by ChristofPetig** [comment] 2019-11-27 09:29
I am sorry but I don't follow your logic on why the **largest** number for **first_created** should win, the search order shouldn't make any difference. As far as I can tell we are looking for the first operator using the tensor (minimum) which recommends "i<current->first_created". Additionally I think that a similar mistake was made in the last_used logic - here you look for the largest number. I feel confirmed by testing a complex graph with the logic in master versus my reversed implementation.

**Comment by driedler** [comment] 2019-12-15 22:43
I was testing mobilenetv2 and found that the model didn't work without the suggested change.
It was clear that RAM was incorrectly being shared by concurrent tensors.

From what I can tell, the logic is trying the find the very first operation and the very last operation the tensor is used. Thus, we want to find the smallest operation index (i.e. smallest current->first_created) and the largest operation index (i.e. largest current->last_used)

With this logic, the search order makes a difference as (current->first_created > i) causes lower operation ids to not be considered.

**Comment by ChristofPetig** [comment] 2019-12-19 09:04
I see a similar problem (wrong comparison) with the calculation of last_used (here the code in master wrongly looks for the minimum). I was quite surprised to see inputs with a first_used of greater than zero and outputs with a last_use smaller than the maximum. I agree to your description of what this code should do (find the min of first and the max of last). [My test case is an unrolled RNN with parallel paths, early outputs and inputs into late operators]

Still I don't see why the order of comparison makes any difference to the end result as to me this clearly is a min/max search (random order should also be fine here).

Honestly I have a hard time reading it expressed as "if (first>i) first=i" instead of "if (i<first) first=i" . My understanding of your patch is that it changes it to calculate first as the maximum of candidates "if (i>first) first=i". (I swapped the sides for better readability (according to my feelings))

**Comment by driedler** [comment] 2020-05-27 02:32
From what I can tell there is a regression in the latest master:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/micro_allocator.cc#L177
The inverted logic is back.
