### ISSUE TITLE
why is the tensor value of the dimension resolved when reading tfrecord files is twice as much as is required to rescontruct the dimension？

### ISSUE THREAD

**Issue by nannanliuliuliu** [tensorflow/tensorflow#18285] opened 2018-04-06 03:34 UTC
-----------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: pip install tensorflow
- **TensorFlow version (use command below)**: tensorflow1.4
- **Python version**: Python 3.6.3
- **Bazel version (if compiling from source)**: --
- **GCC/Compiler version (if compiling from source)**: --
- **CUDA/cuDNN version**: --
- **GPU model and memory**:Tesla K80 
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
![image](https://user-images.githubusercontent.com/35683771/38402256-8349acbc-398d-11e8-8f27-a6393ddf9b7e.png)
image Segmentation:why is the tensor value of the dimension resolved when reading tfrecord files is twice as much as is required to rescontruct the dimension？

### Source code / logs

2018-04-06 10:39:40.367069: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-04-06 10:39:40.845083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:05:00.0
totalMemory: 11.17GiB freeMemory: 6.90GiB
2018-04-06 10:39:40.845182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:05:00.0, compute capability: 3.7)
No checkpoint file found
ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 26136 values, but the requested shape has 13068
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_87, Reshape/shape)]]
	 [[Node: random_crop_1/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_80_random_crop_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]2018-04-06 10:39:51.060248: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.060359: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.060728: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.060779: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.060868: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.060926: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]

ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 26136 values, but the requested shape has 13068
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_87, Reshape/shape)]]
	 [[Node: random_crop_1/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_80_random_crop_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]2018-04-06 10:39:51.066487: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 26136 values, but the requested shape has 13068
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_87, Reshape/shape)]]
2018-04-06 10:39:51.066576: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 26136 values, but the requested shape has 13068
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_87, Reshape/shape)]]

2018-04-06 10:39:51.074663: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
2018-04-06 10:39:51.074663: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
	 [[Node: random_crop/All/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_33_random_crop/All", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
	 [[Node: random_crop_1/_101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_80_random_crop_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 8712 values, but the requested shape has 4356
	 [[Node: Reshape_1 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_1/_71, Reshape_1/shape)]]
ERROR:tensorflow:Exception in QueueRunner: Input to reshape is a tensor with 26136 values, but the requested shape has 13068
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_87, Reshape/shape)]]
Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:

**I am attaching below my code snippet **

**Comment by poxvoculi** [comment] 2018-04-06 19:35
You have not specified whether you're executing custom code or a provided model exactly as documented.  Probably your model is not getting input of the size it expects, but it's impossible to tell from this information.

Usage questions are better posed on StackOverflow.  This forum is for bug reports.  If you believe you have discovered a bug in tensorflow please post a small, reproducible example.

**Comment by tensorflowbutler** [comment] 2018-04-21 18:25
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by poxvoculi** [comment] 2018-04-23 16:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-05-14 17:51 UTC
Labels: stat:awaiting response
