### ISSUE TITLE
the calculation results of matmul OP are inconsistent

### ISSUE THREAD

**Issue by LeonardoPhysh** [tensorflow/tensorflow#51240] opened 2021-08-05 08:57 UTC
I was running the following code, the results were supposed to be the same but they did not.

```python
def run_matmul_test():
    a = tf.random.normal([2452,2992], dtype=tf.float16)
    a_b = tf.random.normal([2992], dtype=tf.float16)

    b = tf.random.normal([1, 2452], dtype=tf.float16)
    c = tf.repeat(b, 8, 0)

    out1_1 = tf.matmul(b, a)
    out1 = tf.nn.bias_add(out1_1, a_b)

    out2_1 = tf.matmul(c, a)
    out2  = tf.nn.bias_add(out2_1, a_b)


    with tf.Session() as sess:
        a_out,b_out = sess.run([out1, out2])

        print(a_out[0] - b_out[0])
        print((a_out[0] - b_out[0]).max())
        print((a_out - b_out[1]).max())
        print((a_out - b_out[2]).max())
        print((a_out - b_out[3]).max())
```

Result for 1 test run.

```
[-0.01563 -0.0742   0.1289  ... -0.1406  -0.0625   0.02344]
0.625
0.625
0.625
0.625
```

**Comment by sushreebarsa** [comment] 2021-08-05 12:19
@LeonardoPhysh  I tried to run your code on **`colab`** with **`TF v2.5`** and didn't get the error reported here.Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0bb85b609b5740755c20553eb45f58b2/untitled356.ipynb#scrollTo=j3gX_Z5kOpH2) for your reference .Thank you!

**Comment by LeonardoPhysh** [comment] 2021-08-09 08:24
> @LeonardoPhysh I tried to run your code on **`colab`** with **`TF v2.5`** and didn't get the error reported here.Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0bb85b609b5740755c20553eb45f58b2/untitled356.ipynb#scrollTo=j3gX_Z5kOpH2) for your reference .Thank you!

@sushreebarsa I was running the above code on CPU with TF V1.15(sorry for missing the version info), and I checked with TF v2.5 and it has no error also. 

I also tested on GPU(also v1.15), It has no error on GPU。

**Comment by sushreebarsa** [comment] 2021-08-09 11:47
@LeonardoPhysh Thank you for the update.Could you please let us know if the issue is resolved for you & please confirm if we can close the issue ? Thanks!

**Comment by LeonardoPhysh** [comment] 2021-08-11 06:23
@sushreebarsa Is it a known issue in TF v1.15? if it is, I think the issue can be closed.

**Closed** 2021-08-11 06:53 UTC
Labels: stat:awaiting response, type:others, comp:ops, TF 2.5

**Comment by mazeltovlee** [comment] 2021-10-05 06:29
Hi, thanks for bringing up this issue, can I know how this inconsistency bug is fixed? Maybe a related PR link can help?
