### ISSUE TITLE
toco fails to convert to tflite "TypeError: 'NoneType' object has no attribute '__getitem__'"

### ISSUE THREAD

**Issue by obg2sens** [tensorflow/tensorflow#22506] opened 2018-09-25 16:53 UTC
`toco --graph_def_file=frozen_inference_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=oren.tflite --inference_type=QUANTIZED_UINT8 --input_type=FLOAT --input_arrays=ImageTensor --output_arrays=SemanticPredictions --input_shapes=1,321,321,3`

2018-09-25 19:48:04.857732: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/obg1/.local/bin/toco", line 11, in <module>
    sys.exit(main())
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main
    _convert_model(tflite_flags)
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 143, in _convert_model
    output_data = converter.convert()
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 374, in convert
    dump_graphviz_video=self.dump_graphviz_video)
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 243, in toco_convert
    *args, **kwargs)
  File "/home/obg1/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 210, in build_toco_convert_protos
    input_array.mean_value, input_array.std_value = quantized_input_stats[idx]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by tensorflowbutler** [comment] 2018-09-26 00:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by freedomtan** [comment] 2018-09-26 03:35
as you can see from the `tensorflow/contrib/lite/python/convert.py`, for `--inference_type=QUANTIZED_UINT8`,  `--std_dev_values` and ` --mean_values` are anticipated.

**Comment by harshini-gadige** [comment] 2018-10-04 00:09
@obg2sens Is this issue resolved ?

**Comment by tofulawrence** [comment] 2018-10-15 17:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-10-15 17:03 UTC
Labels: comp:lite, stat:awaiting response

**Comment by ZJPUBG** [comment] 2018-10-24 16:51
@freedomtan @harshini-gadige @tofulawrence Hi, I'm wondering what are the mean_values and std_values? Are they values for the testing data, or the data I used during training? Thanks.

**Comment by harshini-gadige** [comment] 2018-10-24 17:05
@ZJPUBG  
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by ZJPUBG** [comment] 2018-10-25 18:17
@harshini-gadige nvm, I found it in the comments of lite.py file. I hope you guys can have a more detailed tflite documentation for users, this will also help questions on StackOverflow to be answered more correctly.
