### ISSUE TITLE
Retraining explanation with tf-hub

### ISSUE THREAD

**Issue by malibu** [tensorflow/tensorflow#20148] opened 2018-06-20 14:02 UTC
Trying to go through this tutorial below to retrain ssd_inception_v2_coco_11_06_2017 to fine tune and retrain on coco + additional set of images:
https://www.tensorflow.org/tutorials/image_retraining#creating_a_set_of_training_images

This tutorial seems to be different from others I've seen where labelling images and creation of tfrecord are necessary steps. However, this tutorial seems to accept a directory of images and retrains the model with the image dir. 
Question: Is the tf-hub automating the tfrecord creation process using the directory name. If so, is it using the full image size and not tagging the bounding boxes of contained boxes?

**Comment by tensorflowbutler** [comment] 2018-06-21 00:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-07-05 18:45
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-20 12:50
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by achowdhery** [comment] 2018-07-20 20:05
The example is for classification not detection

**Comment by achowdhery** [comment] 2018-08-01 19:55
Is this still an open issue?

**Comment by tensorflowbutler** [comment] 2018-08-16 20:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-08-31 19:32
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-15 18:44
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 20:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 20:52 UTC
Labels: stat:awaiting response
