### ISSUE TITLE
ValueError: Cannot add function 'TRTEngineOp_0_native_segment' because a different function with the same name already exists.

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#31286] opened 2019-08-02 17:46 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubunti 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.13.1
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:T4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Not able to call trt.create_inference_graph more than  once to create TF-TRT nodes for  disjointed sub-graphs.  Throws the above error. 

**Describe the expected behavior**

Should not throw the above error.

**Code to reproduce the issue**

Should not be difficult to create a sample code.  Will try to get one soon. 

**Other info / logs**

```
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Cannot add function 'TRTEngineOp_0_native_segment' because a different function with the same name already exists.
```

**Comment by ravikyram** [comment] 2019-08-05 10:20
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-08-13 05:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-13 05:37 UTC
Labels: TF 1.13, comp:gpu, stat:awaiting response, type:support

**Comment by sgambient** [comment] 2019-08-14 03:00
Hi, with the following code I see the error in the "docker pull nvcr.io/nvidia/tensorflow:19.07-py2" container.  However in the "docker pull tensorflow/tensorflow:devel-gpu" , I did not observe the error. My suspicion is TF-TRT is not working in "tensorflow/tensorflow:devel-gpu" !! Can you please confirm both ? 

```
rom tensorflow.contrib.slim.nets import resnet_v1
import tensorflow as tf
import tensorflow.contrib.slim as slim
import numpy as np
import time
import os
from PIL import Image
#import tensorflow.contrib.tensorrt as tftrt
from tensorflow.python.compiler.tensorrt import trt_convert as tftrt
import argparse

PATH_TO_CKPT = "resnet_v1_50.ckpt"
TEST_IMAGE_PATHS = [ "elephant_small.jpg", "tabby_tiger_cat.jpg"]
BATCH_SIZE=25
MAX_BATCH_SIZE=1000
HEIGHT=224
WIDTH=224
CHANNELS=3


def load_image_into_numpy_array(image, batch_size=1):
  (im_width, im_height) = image.size
  x = np.array(image.getdata()).reshape(
      (HEIGHT, WIDTH, CHANNELS)).astype(np.uint8)
  x = np.expand_dims(x, axis=0)
  xsl = list (x.shape)
  xsl[0] = batch_size#MAX_BATCH_SIZE
  x = np.broadcast_to(x[0,:,:,:], xsl) 
  return x

def run_resnet_50():
    # Create graph
    inputs = tf.placeholder(tf.float32, shape=[BATCH_SIZE, HEIGHT, WIDTH, CHANNELS])
    with slim.arg_scope(resnet_v1.resnet_arg_scope()):
            net, end_points = resnet_v1.resnet_v1_50(inputs, is_training=False)
    
    saver = tf.train.Saver()
    
    with tf.Session() as sess:
            saver.restore(sess, PATH_TO_CKPT)
            representation_tensor = sess.graph.get_tensor_by_name('resnet_v1_50/pool5:0') # if you don't know names like these, consider referring to corresponding model file or generate .pbtxt file as mentioned in  @civilman628 's answer above
            img = np.ones((batch_size, height, width, channels))   #load image here with size [1, 224,224, 3]
            features = sess.run(representation_tensor, {'Placeholder:0': img})
            print ( "features", features)

def renamed_ckpt_save(name):
    with tf.Session() as sess:# Restore the TF checkpoint

        for var_name, var_shape in tf.contrib.framework.list_variables(PATH_TO_CKPT):
            var = tf.contrib.framework.load_variable(PATH_TO_CKPT, var_name)
            new_name_parts = [name] + var_name.split('/')[1:]
            new_name = '/'.join(new_name_parts)
            var = tf.Variable(var, name=new_name)
            print var_name, var_shape, var.name

        ckpt_dir = "/tmp/"+name
        if not os.path.exists(ckpt_dir):
            os.mkdir(ckpt_dir)
        sess.run(tf.global_variables_initializer())
        saver = tf.train.Saver()
        saver.save(sess, ckpt_dir)

def renamed_ckpt_mem(sess, name):

        for var_name, var_shape in tf.contrib.framework.list_variables(PATH_TO_CKPT):
            var = tf.contrib.framework.load_variable(PATH_TO_CKPT, var_name)
            new_name_parts = [name] + var_name.split('/')[1:]
            new_name = '/'.join(new_name_parts)
            var = tf.Variable(var, name=new_name)
            print var_name, var_shape, var.name

def build_graph (sess, input_graph, name='graph1'):

    inputs = tf.placeholder(tf.float32, shape=[BATCH_SIZE, HEIGHT, WIDTH, CHANNELS])
    with slim.arg_scope(resnet_v1.resnet_arg_scope()):
            net, end_points = resnet_v1.resnet_v1_50(inputs, is_training=False, scope=name)

    with input_graph.as_default():
      # Get handles to input and output tensors
      ops = tf.get_default_graph().get_operations()
      all_tensor_names = {output.name for op in ops for output in op.outputs}
      tensor_dict = {}
      for key in [
          'pool5',
      ]:
        if name == '':
            tensor_name = key + ':0'
        else :
            tensor_name = name+'/'+key + ':0'
        if tensor_name in all_tensor_names:
                tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
                tensor_name)
                print ( "tensor_name", tensor_name, tensor_dict[key])
        else:
           print( "tensor_name ", tensor_name, " not found")


    # Restore the TF checkpoint
    saver = tf.train.Saver()
    saver.restore(sess, "/tmp/"+name)
    return tensor_dict

class TfTrt():

    @staticmethod
    def build(sess, graph, name='', import_name='import'):
        tensor_dict = build_graph(sess, graph, name=name, )

        outputl = []
        for i,nname in enumerate(tensor_dict):
            nvalue = tensor_dict[nname].name.split(":")[0]
            print( i, nname, tensor_dict[nname].name )
            outputl.append(nvalue)
        print ( "outputl ", outputl)

        #node_names = [n.name for n in graph.as_graph_def().node]
        #import pdb
        #pdb.set_trace()

        # Freeze the graph:
        frozen_graph = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names= outputl)

        # remove training nodes
        frozen_graph = tf.compat.v1.graph_util.remove_training_nodes(frozen_graph)
        # Now you can create a TensorRT inference graph from your frozen graph

        tftrt_graph = tftrt.create_inference_graph(
            input_graph_def=frozen_graph,
            outputs = outputl,
            max_batch_size = MAX_BATCH_SIZE ,
            max_workspace_size_bytes= 1024*1024*1024,
            precision_mode="FP16")

        output_nodes = tf.import_graph_def(
            tftrt_graph,
            return_elements = outputl,
            name=import_name
        )

        tensor_dict = {}
        for opname, opnode in zip (outputl, output_nodes):
            tensor_dict[opnode.name] = opnode.outputs[0]

        print ( "tensor_dict", tensor_dict)

        return tensor_dict

    @staticmethod
    def run(sess, tensor_dict, image_tensor, image_np_expanded):
        output_dict = sess.run(tensor_dict, feed_dict={image_tensor: image_np_expanded})
        return output_dict

class Tf():

    @staticmethod
    def build(sess, graph, name='', import_name=None):
        return build_graph(sess, graph, name=name)

    @staticmethod
    def run(sess, tensor_dict, image_tensor, image_np_expanded):
        output_dict = sess.run(tensor_dict, feed_dict={image_tensor: image_np_expanded})
        return output_dict

def run (runtime='TF'):

    if runtime=='TF':
        RunClass = Tf
        import_name1= ''
        import_name2= ''
        placeholder_name1 = 'Placeholder:0'
        placeholder_name2 = 'Placeholder_1:0'
    elif runtime=='TFTRT':
        RunClass = TfTrt
        import_name1 = 'import1'
        import_name2 = 'import2'
        placeholder_name1 = 'import1/Placeholder:0'
        placeholder_name2 = 'import2/Placeholder_1:0'

    graph = tf.Graph()

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    #config.gpu_options.per_process_gpu_memory_fraction = 0.33
    config.graph_options.rewrite_options.auto_mixed_precision = 1
    with tf.Session(graph=graph, config=config) as sess:
        #renamed_ckpt_mem(sess, 'resnet_v1_50_1')
        #renamed_ckpt_mem(sess, 'resnet_v1_50_2')
        tensor_dict1 = RunClass.build(sess, graph, name='resnet_v1_50_1', import_name=import_name1)
        tensor_dict2 = RunClass.build(sess, graph, name='resnet_v1_50_2', import_name=import_name2)
        tensorboard_dir = os.environ['TENSORBOARD_DIR']
        file_writer = tf.summary.FileWriter(tensorboard_dir, sess.graph)
        image_path = TEST_IMAGE_PATHS[0]
        print ( "image_path {}".format(image_path))
        image = Image.open(image_path)
        image = image.resize((WIDTH, HEIGHT))
        image_np_expanded = load_image_into_numpy_array(image, batch_size=BATCH_SIZE)
        image_tensor1 = graph.get_tensor_by_name(placeholder_name1)
        image_tensor2 = graph.get_tensor_by_name(placeholder_name2)
        time0 = time.time()
        for i in range(1,1001):
            output_dict1 = RunClass.run(sess, tensor_dict1, image_tensor1, image_np_expanded)
            output_dict2 = RunClass.run(sess, tensor_dict2, image_tensor2, image_np_expanded)
            if i % 100 == 0:
                time_taken = (time.time() - time0 )/(i * 1.0)
                print (i, time_taken)
        time_taken = (time.time() - time0 )/(i * 1.0)
        print ("time_taken ", time_taken, "output_dict", output_dict1, output_dict2)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--runtime', default='TF', help='TF or TFTRT')
    parser.add_argument('--rewrite_ckpt', action='store_true',  help='rename checkpoints')
    args = parser.parse_args()
    if args.rewrite_ckpt:
        renamed_ckpt_save('resnet_v1_50_1')
        renamed_ckpt_save('resnet_v1_50_2')

    run (args.runtime)



```

**Comment by sgambient** [comment] 2019-08-14 18:26
Is this  code and info enough for you to reopen the issue ?

**Comment by CLIsVeryOK** [comment] 2020-01-19 11:03
use tf.Graph().as_default() to separate differnt Scope, it works.

with tf.Graph().as_default() as g:
            sess = tf.Session(config=config_gpu)
            meta_graph_def = tf.saved_model.loader.load(sess, ["serve"], model_path)
            signature = meta_graph_def.signature_def
