### ISSUE TITLE
Where is device_attributes.pb.h 

### ISSUE THREAD

**Issue by Zealoe** [tensorflow/tensorflow#12128] opened 2017-08-09 03:30 UTC
I have to use the  device_attributes.pb.h  and I don't know where it is.

Thank you !

**Comment by FiveTechSoft** [comment] 2017-08-09 03:32
Create it as an empty dummy file

**Comment by asimshankar** [comment] 2017-08-09 22:51
Closing this as a duplicate of #11899 - like for the file mentioned there, `device_attributes.pb.h` is generated during the build and is placed in `bazel-genfiles`

**Closed by asimshankar** 2017-08-09 22:51 UTC
