### ISSUE TITLE
Is there any support anywhere for Tensorflow on Apple Silicon?

### ISSUE THREAD

**Issue by TheMartian32** [tensorflow/tensorflow#45631] opened 2020-12-12 22:16 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Not sure what this means?

**Describe the feature and the current behavior/state.**

**Will this change the current API? How?**
Not sure. I'm unaware of what changes need to be made.

**Who will benefit with this feature?**
People who own machines running Apple Silicon. 

**Any Other info.**
Currently trying to import TF and Keras and I keep getting an error stating that it's an illegal hardware instruction.

**Comment by bhack** [comment] 2020-12-13 19:50
It Is a duplicate of https://github.com/tensorflow/tensorflow/issues/44751

**Comment by amahendrakar** [comment] 2020-12-14 11:24
@TheMartian32,
Could you please try installing TensorFlow as per [this guide](https://github.com/apple/tensorflow_macos#installation) from Apple and check if it works.

Also, as mentioned by @bhack please go through issue [#44751](https://github.com/tensorflow/tensorflow/issues/44751) for more information. Thanks!

**Comment by mabidou** [comment] 2020-12-14 15:23
It seems no support yet. @amahendrakar is posting same response to anyone reporting the issue as happened with me here https://github.com/tensorflow/tensorflow/issues/45645  #45645

**Comment by TheMartian32** [comment] 2020-12-14 16:21
@mabidou Actually there seems to be a solution. This is what got it working for me ( although so far I've only imported Tensorflow and Keras ): https://github.com/apple/tensorflow_macos/issues/3

But it seems to be working great! 👍

**Comment by mabidou** [comment] 2020-12-14 16:28
> @mabidou Actually there seems to be a solution. This is what got it working for me ( although so far I've only imported Tensorflow and Keras ): [apple/tensorflow_macos#3](https://github.com/apple/tensorflow_macos/issues/3)
> 
> But it seems to be working great! 👍

Which version you ended in? Regular `tensorflow   2.3.1 ` or  `tensorflow-macos   0.1a1`
My target is to have the regular `tensorflow   2.3.1 `

**Comment by mihaimaruseac** [comment] 2020-12-14 18:04
Closing as duplicate of #44751

`tensorflow-macos` issues should go to that repository, as that is a fork of this one with code we don't maintain.

**Closed by mihaimaruseac** 2020-12-14 18:04 UTC
Labels: TF 2.3, stat:awaiting response, subtype:macOS, type:build/install

**Comment by mabidou** [comment] 2020-12-14 18:08
If #44751  is already closed, where is the solution then?

**Comment by mihaimaruseac** [comment] 2020-12-14 18:11
TF on Apple Silicon is supported only via the fork at the moment.

**Comment by bhack** [comment] 2020-12-14 18:17
@mabidou:
> In the near future, we’ll be making updates like this even easier for users to get these performance numbers by integrating the forked version into the TensorFlow master branch. 

https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html

**Comment by TheMartian32** [comment] 2020-12-14 18:51
@mabidou 

So I ended up with TF 2.4 or whichever version is specified in that specific fork. Anyway, the solution was in the comments somewhere. It used mini conda, the fork of TF, and a virtual environment.

**Comment by mabidou** [comment] 2020-12-15 13:55
We should expect a solution from TensorFlow team not to delegate it to Apple. Hope that TensorFlow team is working on that @mihaimaruseac

**Comment by mihaimaruseac** [comment] 2020-12-27 01:03
Apple Silicon support is provided via a fork from Apple, At the moment there is no way TF team at Google can maintain that build.

**Comment by mabidou** [comment] 2020-12-27 02:32
Hi @mihaimaruseac 
TF is your product and it's expected to be supported from you in upcoming versions but I think that it's inconvenient to leave Apple Silicon users to use that fork.

**Comment by mihaimaruseac** [comment] 2020-12-27 16:53
We only provide official support for [these wheels](https://pypi.org/project/tensorflow/#files). Anything else is community driven. Time is limited for everyone, we cannot support everything. Due to diminishing returns, headcount and priority issues, we only target the most common platforms.
