### ISSUE TITLE
TF Lite nightly: Model with Fully Connected layer can't be converted, fully quantization, int8

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#39718] opened 2020-05-20 14:15 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (or github SHA if from source): tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1l3VnLtWBCP_IR8CV7bTps1UXPoDfT2ok?usp=sharing

```
import numpy as np
import tensorflow as tf

mnist = tf.keras.datasets.mnist
train_data, test_data = mnist.load_data()

pre_process = lambda x: x / 255.0
num_calib = 1000
calib_data = pre_process(
            train_data[0][0 : num_calib].astype(np.float32)
        )

model = tf.keras.Sequential(
            [
                tf.keras.layers.InputLayer(input_shape=(28, 28)),
                tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
                tf.keras.layers.Conv2D(
                    filters=12, kernel_size=(3, 3), activation=tf.nn.relu
                ),
                tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
                tf.keras.layers.Flatten(),
                tf.keras.layers.Dense(10, activation=tf.nn.softmax),
            ]
        )
model.summary()

train_images = pre_process(train_data[0])
train_labels = train_data[1]
test_images = pre_process(test_data[0])
test_labels = test_data[1]
# Train the digit classification model
model.compile(
  optimizer="adam",
  loss="sparse_categorical_crossentropy",
  metrics=["accuracy"],
)
model.fit(
  train_images,
  train_labels,
  epochs=1,
  validation_data=(test_images, test_labels),
)

def _get_calib_data_func():
  def representative_data_gen():
    for input_value in calib_data:
      input_value = np.expand_dims(input_value, axis=0).astype(np.float32)
      yield [input_value]

  return representative_data_gen

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.representative_dataset = _get_calib_data_func()

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_model_INT8 = converter.convert()
```

```
**RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor sequential_2/reshape_2/Shape
Empty min/max for tensor sequential_2/reshape_2/Shape**
```

**Also, please include a link to the saved model or GraphDef**

```
https://colab.research.google.com/drive/1l3VnLtWBCP_IR8CV7bTps1UXPoDfT2ok?usp=sharing
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-05-20 15:20
@wwwind,
I was able to reproduce the issue with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/4a4ea0178b34597d6035794ba3eb3e36/39718-nightly.ipynb). However, the code works with the stable version [TF v2.2](https://colab.research.google.com/gist/amahendrakar/54d9272a3c32841d1532a994cc5820bb/39718-2-0.ipynb). Please check the linked gist.

Could you please try running the code with TF v2.2 and let us know if it works. Thanks!

**Comment by wwwind** [comment] 2020-05-20 15:35
@amahendrakar Yes, I confirm - it works in tensorflow 2.2.0

**Comment by amahendrakar** [comment] 2020-05-20 17:41
@wwwind,
Thank you for the update. Please feel free to close the issue if resolved. Thanks!

**Comment by sramirez** [comment] 2020-05-25 15:52
I get the same error when dealing with tf-nightly. However, I can't go back to 2.2 because a new error suddenly shows up: Tensor 'input_1' has invalid shape '[None, None, None, 3]'. I've seen in other thread it's recommended to use tf-nightly to fix the last error.

So I can see here kind of deadlock between versions.

**Comment by amahendrakar** [comment] 2020-05-27 07:35
> @amahendrakar Yes, I confirm - it works in tensorflow 2.2.0

Closing this issue as resolved.

**Comment by amahendrakar** [comment] 2020-05-27 07:36
@sramirez,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template along with the complete code, so that we can track the issue there. Thanks!

**Comment by wwwind** [comment] 2020-05-27 09:27
@amahendrakar Could this bug be fixed in tf-nightly ? 
I am working with tf-nightly and I really appreciate if it will be fixed in the current code.

**Comment by jvishnuvardhan** [comment] 2020-06-03 18:39
@wwwind I have updated your code and [here](https://colab.research.google.com/gist/jvishnuvardhan/05d9d1bcfe32caead45728ac250e8dbf/39718-nightly.ipynb) is the working version of your code with `tf-nightly`. Thanks!

**Comment by gargn** [comment] 2020-06-03 18:41
At a high level there are two ways to fix this issue (one of which @jvishnuvardhan pointed out).

1. Try setting it in keras and keeping conversion the same way:
```
input = tf.keras.layers.Input(shape=(225, 225, 3), batch_size=1)
```

2. Use `set_shape` on the model input and fix the batch size to `1` (example here: https://www.tensorflow.org/lite/convert/python_api#examples_).

**Closed** 2020-06-05 19:20 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, type:bug
