### ISSUE TITLE
How to install 0.9 or 1.0.0 in 2018?

### ISSUE THREAD

**Issue by ihteshamraza** [tensorflow/tensorflow#20306] opened 2018-06-26 13:43 UTC
i have posted this issue on stackoverflow as well, i have searched all over internet but my issue is still unresolved. I want to use tensorflow 0.9 or 1.0.0 or earlier versions on windows 10. a project needs older version of tensorflow to run. can somebody please guide me? and sorry if this question does not follow guidelines, i just need to install tensorflow earlier version.

**Comment by tensorflowbutler** [comment] 2018-06-27 00:53
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karmel** [comment] 2018-06-27 23:19
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. It sounds like you have already cross-posted there, so I will close this issue in favor of that question.

**Closed by karmel** 2018-06-27 23:19 UTC
Labels: stat:awaiting response

**Comment by ihteshamraza** [comment] 2018-06-28 08:59
yes i have posted this on stackoverflow, but i haven't found a solution yet. i just need a solution that's all
