### ISSUE TITLE
A bug of tfdbg : Non-OK-status: env->NewWritableFile(file_path, &f) status: Not found: Failed to create a NewWriteableFile:

### ISSUE THREAD

**Issue by SilenceWinter** [tensorflow/tensorflow#23622] opened 2018-11-09 09:14 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary):pip install tensorflow
- TensorFlow version (use command below):1.10.0
- Python version: 3.6.5 
- Bazel version (if compiling from source):no
- GCC/Compiler version (if compiling from source):no
- CUDA/cuDNN version:no
- GPU model and memory:no

When I use tfdbg, I input "run" in the console, the error info  like this:

2018-11-09 17:07:18.381547: F T:\src\github\tensorflow\tensorflow\core\debug\debug_io_utils.cc:621] Non-OK-status: env->NewWritableFile(file_path, &f) status: Not found: Failed to create a NewWriteableFile: C:\Users\winter\AppData\Local\Temp\tfdbg_312ol3zm/_tfdbg_device_,job_localhost,replica_0,task_0,device_CPU_0/train_step/gradients/bi-lstm/bidirectional_rnn/fw/fw/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3/Const_0_DebugIdentity_1541754438373045 : ϵͳ�Ҳ���ָ����·����
; No such process

Process finished with exit code -1073740791 (0xC0000409)

**Comment by SilenceWinter** [comment] 2018-11-09 09:29
Perhaps I know the reason， the path and file name is too long . It beyonds the windows 10 limit. So it cannot create .

**Comment by harshini-gadige** [comment] 2018-11-19 19:52
> Perhaps I know the reason， the path and file name is too long . It beyonds the windows 10 limit. So it cannot create .

Feel free to close if you find the reason. Or please share sample code snippet which helps us to reproduce the error and look into the issue.

**Comment by harshini-gadige** [comment] 2018-11-29 18:58
Closing this as a root cause is found.

**Closed by harshini-gadige** 2018-11-29 18:58 UTC
Labels: comp:tfdbg, stat:awaiting response

**Comment by mmkamani7** [comment] 2019-02-17 17:15
Although there is a problem with Windows not allowing to create a folder or file with such a large name, it should be addressed in Tensorflow, since it is nothing that we can do to resolve it.

**Comment by mmkamani7** [comment] 2019-02-17 17:18
> Although there is a problem with Windows not allowing to create a folder or file with such a large name, it should be addressed in Tensorflow, since it is nothing that we can do to resolve it.

However, I found out someone has a workaround on Windows side [here](https://github.com/tensorflow/tensorflow/issues/18750#issuecomment-435654042). But it is still nice to have a solution on Tensorflow side.
