### ISSUE TITLE
keras multi_gpu_model broken going from 1.6.0-rc0 to 1.6.0-rc1

### ISSUE THREAD

**Issue by agdownes** [tensorflow/tensorflow#17081] opened 2018-02-17 04:01 UTC
Have I written custom code: Yes
OS Platform and Distribution: Linux Ubuntu 17.04
TensorFlow installed from: source
TensorFlow version: 1.6.0-rc1
Python version: 3.6 
Bazel version: 0.10
GCC/Compiler version: 6.0
CUDA/cuDNN version: CUDA 9.1 cuDNN 7.0.5
GPU model and memory: NVIDIA Titan Z 12GB
`Exact` command to reproduce: multi_gpu_model(model, gpus=2)

Just upgraded from rc0 to rc1 of release 1.6.0 and I'm now getting the following crash when running the multi_gpu_model function (was working fine with rc0):

    parallel_model = multi_gpu_model(model, gpus=2)

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/utils/training_utils.py", line 207, in multi_gpu_model

    return Model(model.inputs, merged)

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 694, in __init__

    self._init_graph_network(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 733, in _init_graph_network

    if layer.is_placeholder:

AttributeError: 'Lambda' object has no attribute 'is_placeholder'

I rolled back to the 1.5 branch and I'm not having any issues running multi_gpu_model there.

**Comment by facaiy** [comment] 2018-02-17 10:23
Could you provide a minimal reproducible example?

**Comment by agdownes** [comment] 2018-02-17 11:40
I just recompiled and reinstalled the 1.6.0-rc1 and the exact same code which produced the above error now seems to work perfectly. The only difference I can think of is last time I compiled 1.6 I used the compile flags "-O3 -msse4.2 -mavx2 -mfma" suggested in https://github.com/tensorflow/tensorflow/issues/17043 to prevent tf from seg faulting when run on a skylake CPU (which did fix that issue) I might try recompile again with these flags included but it seems like this might be a non-issue if 17043 gets fixed.

**Comment by gunan** [comment] 2018-02-22 21:36
Thanks for checking again. Then I will be closing this issue as a duplicate of #17043

**Closed by gunan** 2018-02-22 21:36 UTC
