### ISSUE TITLE
TF Lite Documentation and Raspberry Pi Demo Request

### ISSUE THREAD

**Issue by alberto139** [tensorflow/tensorflow#18351] opened 2018-04-09 17:10 UTC
Hi All,

I want to request further documentation for running TF Lite on a Raspberry Pi.
I was really impressed by the SSD demo shown by Andrew Selle during the TensorFlow Dev Summit and would love to see documentation to reimplement something like that.

At some point the tensorflow/contrib/lite/README.md stated something about a Raspberry Pi demo app coming soon, but it is no longer there. Is this something that you still plan to support?

Thanks!

**Comment by alberto139** [comment] 2018-04-09 22:15
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: master
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by freedomtan** [comment] 2018-04-16 02:45
@alberto139  I think it's in [g3doc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/rpi.md)

**Comment by tensorflowbutler** [comment] 2018-05-10 12:43
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:46
Nagging Assignee @aselle: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-06-04 17:55
Sorry, it is on my list to open source this.

**Comment by tensorflowbutler** [comment] 2018-06-27 18:48
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-12 19:07
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-27 18:53
Nagging Assignee @aselle: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-08-02 22:37
This is a dupe of #19110.

**Comment by tensorflowbutler** [comment] 2018-08-17 18:57
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-08-23 18:33
Dupliate.

**Closed by tofulawrence** 2018-08-23 18:33 UTC
Labels: comp:lite, type:feature
