### ISSUE TITLE
Crash when running tensorflow.python.ops.math_ops.sparse_segment_sum

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59201] opened 2023-01-09 22:03 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Abort when running .python.ops.math_ops.sparse_segment_sum
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import math_ops
try:
  try:
    with tf.device('/CPU'):
      data_tensor = tf.random.uniform([1], dtype=tf.float64)
      data = tf.identity(data_tensor)
      indices = []
      segment_ids = []
      out = math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      data = tf.identity(data_tensor)
      data = tf.cast(data, tf.float64)
      indices = []
      segment_ids = []
      math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-09 17:01:07.909340: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_INVALID_VALUE: invalid argument; host dst: 0x7f6e6ec00000; GPU src: 0xfffffffffffffffc; size: 4=0x4
Error:{{function_node __wrapped__SparseSegmentSum_device_/job:localhost/replica:0/task:0/device:GPU:0}} SparseSegmentSum: failed to copy last_segment_id from device [Op:SparseSegmentSum]
2023-01-09 17:01:07.910082: F tensorflow/core/common_runtime/gpu/gpu_util.cc:386] CPU->GPU Memcpy failed
Aborted

```
```
</details>

**Comment by tiruk007** [comment] 2023-01-10 15:48
@nimashiri 
This seems to be a duplicate of #59200 . This issue will be triaged on #59200. Could you please close this issue ?
Thank you!

**Comment by nimashiri** [comment] 2023-01-10 17:19
> @nimashiri This seems to be a duplicate of #59200 . This issue will be triaged on #59200. Could you please close this issue ? Thank you!

Sure thanks.

**Closed** 2023-01-10 17:20 UTC
Labels: type:bug, comp:ops, TF 2.11
