### ISSUE TITLE
c_api.h no such file or directory

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#41362] opened 2020-07-14 02:47 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.4.0
- GCC/Compiler version (if compiling from source):  7.5.0
- CUDA/cuDNN version: 11.0 / 8.0.1
- GPU model and memory: GTX1080Ti GDDR5X 11GB

**Describe the problem**
build failed
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
/home/wmind/.cache/bazel/_bazel_wmind/a0a15f0a32d3688786619e94912711cf/external/llvm-project/llvm/BUILD:712:11: C++ compilation of rule '@llvm-project//llvm:Analysis' failed (Exit 1)
In file included from external/llvm-project/llvm/lib/Analysis/TFUtils.cpp:14:0:
external/llvm-project/llvm/include/llvm/Analysis/Utils/TFUtils.h:12:10: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include "tensorflow/c/c_api.h"
```

**Comment by mihaimaruseac** [comment] 2020-07-14 17:08
This should be fixed now. The error was caused by LLVM including a feature that needs TF but TF depends on LLVM so we needed to cut the circular compile dependency.

 @joker-eph fixed this last night.

**Comment by jvishnuvardhan** [comment] 2020-07-14 19:07
@alanpurple Can you please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2020-07-15 06:50 UTC
Labels: stat:awaiting response, subtype: ubuntu/linux, type:build/install
