### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by PeterBeukelman** [tensorflow/tensorflow#562] opened 2015-12-19 23:43 UTC
I try to install tensorflow on Ubuntu 15
uname -a
Linux peter-linux 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
peter@peter-linux:~/tensorflow$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
peter@peter-linux:~/tensorflow$ set|grep LD_LIBRARY
LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib/python2.7/dist-packages/tensorflow/python/:
peter@peter-linux:~/tensorflow$ set|grep CUDA
CUDA_HOME=/usr/local/cuda-7.0
ll /usr/local/cuda
lrwxrwxrwx 1 root root 8 nov 14 11:39 /usr/local/cuda -> cuda-7.0/
peter@peter-linux:~/tensorflow$ ls  /usr/local/cuda/lib64/libcudnn*
/usr/local/cuda/lib64/libcudnn.so      /usr/local/cuda/lib64/libcudnn.so.6.5.48  /usr/local/cuda/lib64/libcudnn.so.7.0.64
/usr/local/cuda/lib64/libcudnn.so.6.5  /usr/local/cuda/lib64/libcudnn.so.7.0     /usr/local/cuda/lib64/libcudnn_static.a
peter@peter-linux:~/tensorflow$ pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
......
 warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    changing mode of /home/peter/.local/bin/f2py to 775
Successfully installed tensorflow six numpy
Cleaning up...
 python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

or as it looks now
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (50.5MB): 50.5MB downloaded
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from tensorflow==0.5.0)
Requirement already up-to-date: numpy>=1.9.2 in /home/peter/.local/lib/python2.7/site-packages (from tensorflow==0.5.0)
Installing collected packages: tensorflow
Successfully installed tensorflow
Cleaning up...
(tensorflow)peter@peter-linux:~/tensorflow$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python.util import compat
ImportError: cannot import name compat

**Comment by mrry** [comment] 2015-12-21 15:31
Can you try installing the version 0.6.0 package and see if this problem persists?

https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl

**Comment by PeterBeukelman** [comment] 2015-12-22 21:49
Thanks, but I am giving up. I used to have a problem with my neural network on windows. Now with tensorflow I had one getting to run tensorflow and now my linux won't boot or shutdown anymore after doing some updates. For evenings and weekends I have been trying to revive it, digging through numerous fora and it only sets me back further. Linux is something not to work with to solve a problem, but if you like recompiling your kernel all day long without doing anything productive.

**Comment by mrry** [comment] 2015-12-22 22:15
Sorry to hear that! If you're used to running on Windows, I'd suggest trying the Docker packages, which should avoid any complications with your Linux configuration. Here are some [instructions](http://www.netinstructions.com/how-to-install-and-run-tensorflow-on-a-windows-pc/) that might be helpful.

Since it sounds like the problem is related to your particular machine's configuration, I'm going to close this issue for now, but please feel free to reach out if you have other problems.

**Closed by mrry** 2015-12-22 22:15 UTC
