### ISSUE TITLE
Tensorflow 2.0/1.14 GPU build fails in debug mode

### ISSUE THREAD

**Issue by sayanmandal** [tensorflow/tensorflow#30601] opened 2019-07-11 14:00 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 3.6
- Installed using virtualenv? pip? conda? 
- Bazel version (if compiling from source):0.25.2
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:10.0/7
- GPU model and memory: p40 

**Describe the problem**

tensorflow 1.14 gpu build doesn't succeed in debug mode

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=opt --config=cuda --compilation_mode=dbg //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

1 error detected in the compilation of "/tmp/tmpxft_000029e6_00000000-6_spacetodepth_op_gpu.cu.cpp1.ii".
ERROR: /home/core/tensorflow/tensorflow/core/kernels/BUILD:4483:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/spacetodepth_op_gpu.cu.pic.o' was not created
ERROR: /home/core/tensorflow/tensorflow/core/kernels/BUILD:4483:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 394.154s, Critical Path: 51.10s
INFO: 4640 processes: 4640 local.
FAILED: Build did NOT complete successfully

**Comment by sayanmandal** [comment] 2019-07-11 14:24
Pasting another log:

INFO: From Compiling tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.cc:
external/com_google_absl/absl/strings/string_view.h(495): error: constexpr function return is non-constant

**Comment by mihaimaruseac** [comment] 2019-07-11 16:05
Can you also test with 1.13 to see if this is a regression?

**Comment by gadagashwini** [comment] 2019-07-19 06:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-19 06:06 UTC
Labels: TF 1.14, stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by sayanmandal** [comment] 2019-07-19 06:34
This solved the problem:

bazel build --config cuda --strip=never -c dbg --copt="-DNDEBUG" //tensorflow/tools/pip_package:build_pip_package

**Comment by gadagashwini** [comment] 2019-07-19 08:18
Glad it resolved.
