### ISSUE TITLE
tf.train.Saver setting `max_to_keep` parameter to 0 or None unintended behavior

### ISSUE THREAD

**Issue by nrhine1** [tensorflow/tensorflow#13381] opened 2017-09-29 15:44 UTC
As the [tf.train.Saver](https://www.tensorflow.org/api_docs/python/tf/train/Saver) documentation says:

"`max_to_keep` indicates the maximum number of recent checkpoint files to keep. As new files are created, older files are deleted. If None or 0, all checkpoint files are kept. Defaults to 5 (that is, the 5 most recent checkpoint files are kept.)"

However, when I use `max_to_keep=0`, the `checkpoint` file attribute `all_model_checkpoint_paths` only records the most recent checkpoint file (and I'm unable to load older checkpoint files). I believe this is due to the block:

```python
if len(self._last_checkpoints) > self.saver_def.max_to_keep:
    self._checkpoints_to_be_deleted.append(self._last_checkpoints.pop(0))
```

It should probably instead read something like:

```python
if len(self._last_checkpoints) > self.saver_def.max_to_keep > 0:
    self._checkpoints_to_be_deleted.append(self._last_checkpoints.pop(0))
```

**Comment by facaiy** [comment] 2017-09-30 01:15
Hi, @nrhine1 . Could you give a reproduceble case? 

`max_to_keep=0` is checked at the beginning of the function:

https://github.com/tensorflow/tensorflow/blob/f807b39667e84a28e83105fd29533262c257a53e/tensorflow/python/training/saver.py#L1321-L1322

And there exists the corresponding test case as well:

https://github.com/tensorflow/tensorflow/blob/f807b39667e84a28e83105fd29533262c257a53e/tensorflow/python/training/saver_test.py#L1199-L1225

**Comment by cy89** [comment] 2017-10-08 23:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by cy89** 2017-10-08 23:58 UTC

**Comment by vikotse** [comment] 2018-06-15 04:02
I meet the same issue that 

> checkpoint

 file only record the most recent checkpoint file.

**Comment by facaiy** [comment] 2018-06-15 05:37
@vikotse Could you open a new issue and provide all necessary information for reproducing the issue?
