### ISSUE TITLE
"TypeError: Not JSON Serializable: Tensor" when save model!

### ISSUE THREAD

**Issue by Aaron9477** [tensorflow/tensorflow#36084] opened 2020-01-21 03:34 UTC
Hi,
I just meet a problem when add a Variable to model as a changable weight for loss. But I have error when I save model. I don't find any way work for this problem.

This is my code. if I don't use changable weights, it works good.
`model.alpha = tf.Variable(args.alpha, trainable=False, name='alpha', dtype=tf.float32)
model.compile(optimizer=opt, loss=['mae', TVdist], loss_weights=[1.0 / (1 + model.alpha), model.alpha / (1 + model.alpha)])`

This is my error info:
Traceback (most recent call last):
  File "train_sgdnet_change.py", line 321, in <module>
    save_best_only=False), reduce_lr, AlphaChange])
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/callbacks.py", line 457, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/saving.py", line 138, in _serialize_model
    }, default=get_json_type).encode('utf8')
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/bpfsrw1/wangmingkai/python_env/lib/python2.7/site-packages/keras/engine/saving.py", line 74, in get_json_type
    raise TypeError('Not JSON Serializable: %s' % (obj,))
TypeError: Not JSON Serializable: Tensor("truediv:0", shape=(), dtype=float32)

This is my environment:
keras 2.2.4
tensorflow 1.10.1

Looking forward for a solution!
Aaron

**Comment by ravikyram** [comment] 2020-01-21 13:25
@Aaron9477 

Looks like code is incomplete. Please, help us with the minimal standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-01-30 10:17
@Aaron9477 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-02-10 11:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-10 11:46 UTC
Labels: comp:keras, stat:awaiting response, type:support
