### ISSUE TITLE
There is not `python/ops/gen_spectral_ops.py` in github

### ISSUE THREAD

**Issue by Lebhoryi** [tensorflow/tensorflow#39302] opened 2020-05-08 08:02 UTC
When I have to learn how to compute mfcc, there is a question in compute fft.

The question is not finding 'python/ops/gen_spectral_ops.py' in github, how could I read it? 

However,  there is a 'python/ops/gen_spectral_ops.py' in tf1.14.0 in my computer, is the same file?

**Comment by Saduf2019** [comment] 2020-05-08 10:16
@Lebhoryi 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Lebhoryi** [comment] 2020-05-08 10:18
copy

**Comment by Saduf2019** [comment] 2020-05-08 11:47
moving this to closed status with confirmation

**Closed by Saduf2019** 2020-05-08 11:47 UTC
Labels: TF 1.14, stat:awaiting response, type:others
