### ISSUE TITLE
tfjs model converted from Keras model cannot be loaded

### ISSUE THREAD

**Issue by changkaizhao** [tensorflow/tensorflow#29103] opened 2019-05-29 03:09 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.9
- Python version:3.7.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

***Step 1***
Train a keras model, and test it OK. saved as `model.h5`
model as below:
```
model = Sequential()

model.add(SeparableConv2D(32,
                          kernel_size=(3, 3),
                          padding='same',
                          activation='relu',
                          input_shape=input_shape))

model.add(SeparableConv2D(64,
                          kernel_size=(3, 3),
                          padding='same',
                          activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(SeparableConv2D(256,
                          kernel_size=(3, 3),
                          padding='same',
                          activation='relu' ))
model.add(AveragePooling2D(pool_size=(14, 14)))
model.add(Flatten())
```
***Step 2***
use `tensorflowjs_converter` to convert keras model to JS model.
```
>$ tensorflowjs_converter --input_format=keras ./my_model.h5 ./assets
```
and generate 2 files `group1-shard1of1` and `model.json`

***Step 3***
use converted model in JS project.
```
this.model = await tf.loadLayersModel(model_path);
```
and get errors like below:
```
core.js:15724 ERROR Error: Uncaught (in promise): Error: Fields kernelInitializer, kernelRegularizer and kernelConstraint are invalid for SeparableConv2D. Use depthwiseInitializer, depthwiseRegularizer, depthwiseConstraint, pointwiseInitializer, pointwiseRegularizer and pointwiseConstraint instead.
Error: Fields kernelInitializer, kernelRegularizer and kernelConstraint are invalid for SeparableConv2D. Use depthwiseInitializer, depthwiseRegularizer, depthwiseConstraint, pointwiseInitializer, pointwiseRegularizer and pointwiseConstraint instead.
    at new t (tf-layers.esm.js:17)
    at t [as constructor] (tf-layers.esm.js:17)
    at new t (tf-layers.esm.js:17)
    at e.fromConfig (tf-core.esm.js:17)
    at deserializeKerasObject (tf-layers.esm.js:17)
    at deserialize (tf-layers.esm.js:17)
    at t.fromConfig (tf-layers.esm.js:17)
    at deserializeKerasObject (tf-layers.esm.js:17)
    at deserialize (tf-layers.esm.js:17)
    at tf-layers.esm.js:17
    at resolvePromise (zone.js:831)
    at zone.js:741
    at rejected (tslib.es6.js:69)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
```

## Note: if I replace the `SeparableConv2D` by `Conv2D`, everything will be OK.

**Comment by achandraa** [comment] 2019-05-30 11:50
It looks from the error that SeparableConv2D uses depthwiseInitializer, depthwiseRegularizer etc therefore need to use these instead. For better help and faster resolution, you can post this issue on [tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues/new) repo. Please let me know in case you have any clarification. Thanks!

**Comment by achandraa** [comment] 2019-06-04 06:28
Closing the issue. Please let us know in case of any clarification. Thanks!

**Closed by achandraa** 2019-06-04 06:28 UTC
Labels: stat:awaiting response, type:support

**Comment by changkaizhao** [comment] 2019-06-19 09:10
**SOLUTION**    There is a **BUG** when using`tensorflowjs_converter` to convert a network containing `SeparableConv2D ` to `jsmodel`.
You need to remove the fields `kernelInitializer ` `kernelRegularizer ` and `kernelConstraint ` in `model.json`.

**Comment by changkaizhao** [comment] 2019-06-19 09:12
I used `tensorflowjs==0.8.0` , latest version not test yet.

**Comment by jerrydeng** [comment] 2019-07-12 21:27
@changkaizhao how do you remove those fields from model.json?  Just remove those pairs from the JSON completely?

**Comment by ldenoue** [comment] 2019-10-18 19:40
error disappears for me when I export as a tfjs_graph_model instead.
`tensorflowjs_converter --input_format tfjs_layers_model --output_format tfjs_graph_model your_exported_tfjs_model/model.json graph_model`

**Comment by SwatiModi** [comment] 2021-04-11 19:02
How to solve this? I facing the same issue

**Comment by vcucu** [comment] 2021-09-06 06:46
The issue is not solved for me when using the tfjs_graph model. 
But you can solve it by replacing all "kernel_initializer" with "depthwise_initializer", "kernel_regularizer" with "depthwise_intializer" and "kernel_contraint" with "depthwise_constraint" in  model.json file.
