### ISSUE TITLE
how to build v2.8.0 with verbs under centos7.8?

### ISSUE THREAD

**Issue by zhucan** [tensorflow/tensorflow#55528] opened 2022-04-07 09:05 UTC

**Comment by sushreebarsa** [comment] 2022-04-11 07:35
@zhucan 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), 
Please refer to this[ link](https://www.tensorflow.org/install/source) and let us know if it helps?Thanks!

**Comment by zhucan** [comment] 2022-04-12 02:36
This link only for ubuntu and mac. @sushreebarsa

**Comment by sushreebarsa** [comment] 2022-04-18 12:26
@zhucan Could you please confirm if it is a duplicate ticket of this issue #55524 ?
Thanks!

**Comment by zhucan** [comment] 2022-04-19 05:41
Yes, because of I had compiled the tensorflow2.0 with verbs successfully. @sushreebarsa

**Comment by sushreebarsa** [comment] 2022-04-19 05:44
@zhucan Could you please move this issue to closed status if it is resolved?
Thanks!

**Comment by zhucan** [comment] 2022-04-19 05:49
But with the v2.8.0, I hadn't fixed @sushreebarsa

**Comment by zhucan** [comment] 2022-04-19 05:49
[Tensorflow2.0.md](https://github.com/tensorflow/tensorflow/files/8510195/Tensorflow2.0.md)

**Comment by zhucan** [comment] 2022-04-19 05:51
Chinese: https://github.com/zhucan/kubernetes-study/blob/master/Tensorflow2.0.pdf

**Comment by mihaimaruseac** [comment] 2022-04-28 22:56
Duplicate of #55524?

**Comment by gadagashwini** [comment] 2022-05-05 10:20
@zhucan,
Can we close this issue, since it is duplicate of [#55524 ](https://github.com/tensorflow/tensorflow/issues/55524).
We can follow up on other thread. Thanks

**Comment by zhucan** [comment] 2022-05-05 10:59
yes, but no anyone answer the question.

**Comment by tilakrayal** [comment] 2024-10-23 08:15
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

**Comment by mihaimaruseac** [comment] 2024-10-23 11:40
closed as duplicate of #55524

**Closed by mihaimaruseac** 2024-10-23 11:40 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:build/install, subtype:centos, TF 2.8
