### ISSUE TITLE
How can I warm up the cache by calling the predict method with an all zero inputs in browsers?

### ISSUE THREAD

**Issue by XdyGoGo** [tensorflow/tensorflow#27746] opened 2019-04-11 08:29 UTC
You can warm up the cache by calling the predict method with an all zero inputs

**Comment by XdyGoGo** [comment] 2019-04-15 01:53
Sorry, I do not know what you mean is?

**Comment by gadagashwini** [comment] 2019-04-15 08:16
@XdyGoGo This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.  If you think it is a bug/feature request, please fill the respective template inorder to start triaging. Thanks !

**Comment by gadagashwini** [comment] 2019-04-22 07:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-04-22 07:14 UTC
Labels: stat:awaiting response, type:support
