### ISSUE TITLE
different result from tf.image.resize in tensorflow 2

### ISSUE THREAD

**Issue by kja815** [tensorflow/tensorflow#44038] opened 2020-10-15 04:34 UTC
I use tensorflow 2.2 and python 3.6.9

I tried to convert tf 1.12 version model to tf 2.2 version model

but in tf 2.2
tf.image.resize(image, [299, 299], method="bilinear", antialias=True)
tf.image.resize(image, [299, 299], method="bilinear", antialias=False)

are different results with tf.compat.v1.image.resize(image, [299,299], method='bilinear')

for the same image.

**Comment by amahendrakar** [comment] 2020-10-15 12:21
@kja815,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by mkuchnik** [comment] 2020-10-15 18:41
@kja815 
TF1 [resize](https://www.tensorflow.org/api_docs/python/tf/compat/v1/image/resize) has a different set of parameters than the TF2 [version](https://www.tensorflow.org/api_docs/python/tf/image/resize). Namely, `align_corner` is dropped, which will likely impact the image. Have you checked that the parameters are configured to be the same?

**Comment by kja815** [comment] 2020-10-16 00:28
@mkuchnik 

I know that parameter 'align_corner' is dropped.
I tested various combination of parameter sets for tf.image.resize with bilinear method. but any combination can't get the same result with tf.compat.v1.image.resize(image, [299,299], method='bilinear').
there wasn't same resize method in tf 2 ? 
I want to get the same result without tf.compat.v1.image.resize because compat was deprecated soon.

**Comment by amahendrakar** [comment] 2020-10-21 07:33
> @kja815,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

@kja815,
Any updates regarding this? Thanks!

**Comment by kja815** [comment] 2020-10-21 09:03
@amahendrakar 
with tf.io.gfile.GFile(image_path, 'rb') as input_file:
    image = input_file.read()
image = tf.cast(tf.io.decode_image(image, channels=3, expand_animations=False), dtype=tf.float32)
compat_image = tf.compat.v1.image.resize(image, [299,299], method='bilinear', align_corners=False, preserve_aspect_ratio=False)
tf2_image_true = tf.image.resize(image, [299, 299], method="bilinear", antialias=True)
tf2_image_false = tf.image.resize(image, [299, 299], method="bilinear", antialias=False)

compat_image is different result from tf2_image_true and tf2_image_false

**Comment by amahendrakar** [comment] 2020-10-26 08:43
Was able to reproduce the issue with TF v2.2, TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c8295826ae5ccaa4908e1804a7ccfdc3/44038.ipynb). Thanks!

**Comment by hyeygit** [comment] 2020-12-19 19:32
This is because `half_pixel_centers` attribute was added in tf2 which assumes that pixels are 0.5, 0.5 for more reliable and correct resizes.

Commit: https://github.com/tensorflow/tensorflow/commit/3ae2c6691b7c6e0986d97b150c9283e5cc52c15f

To me, this looks like an intended change (that breaks backwards compat) to fix known issues with resizes.

An option is to add `half_pixel_centers` attribute to `tf.image.resize` as well (currently it calls `resize_bilinear` with this option set to True) and give the option to users to set it to False which will revert the behavior back to <tf2.x. But, given that this was intended to fix / improve the behavior of old resizes, the new behavior should be used.

**Comment by rmothukuru** [comment] 2021-05-12 11:56
@kja815,
Closing this issue as the behavior is intended as per the above comment. Please feel free to reopen the issue if you disagree with that comment. Thanks!

**Closed by rmothukuru** 2021-05-12 11:56 UTC
Labels: TF 2.2, comp:ops, type:support
