### ISSUE TITLE
tflite Model Maker installation Error metadata-generation-failed, No such file or directory: '..\\VERSION'

### ISSUE THREAD

**Issue by Erik6209** [tensorflow/tensorflow#59261] opened 2023-01-15 15:32 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

3.10.4

### Current Behaviour?

```shell
Hello everyone, I hope you can help me with the following problem

I have checked the requirements several times but always get the same error:

pip install tflite-model-maker results in FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION' 

Clone source code from GitHub and install results in TypeError: 'WindowsPath' object is not subscriptable
```

### Standalone code to reproduce the issue

```shell
pip install tflite-model-maker
```

### Relevant log output

```shell
Using cached sentencepiece-0.1.83.tar.gz (497 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\1\AppData\Local\Temp\pip-install-uny2d85u\sentencepiece_d8babf4dcc3a48be9b4874119d6463fb\setup.py", line 29, in <module>
          with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
        File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

-------------------------------------------------------------------------

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\1\Desktop\Dev\tflite_model_maker\examples\tensorflow_examples\lite\model_maker\pip_package\setup.py", line 122, in <module>
          INTERNAL_NAME).run()
        File "C:\Users\1\Desktop\Dev\tflite_model_maker\examples\tensorflow_examples\lite\model_maker\pip_package\setup_util.py", line 163, in run
          namespace_packages = find_namespace_packages(where=self.build_dir)
        File "C:\Users\1\Desktop\Dev\tflite_model_maker\tfliteMM-venv\lib\site-packages\setuptools\__init__.py", line 64, in find
          convert_path(where),
        File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\distutils\util.py", line 123, in convert_path
          if pathname[0] == '/':
      TypeError: 'WindowsPath' object is not subscriptable
      [end of output]
```
</details>

**Comment by DURGESH716** [comment] 2023-01-15 18:57
Hello @Erik6209, I have tested the `pip install tflite-model-maker` code on my system of windows 11, and its working great. I think  the problem is with your side only.

**Comment by DURGESH716** [comment] 2023-01-15 18:58
Here are a couple of things you can try to resolve the issue:

1. Make sure that you have the latest version of pip installed by running `pip install --upgrade pip`

2. Try installing the package using `pip install --no-dependencies tflite-model-maker`

3. Try installing the package using a virtual environment.

4. Check the compatibility of the package with the version of python you are using.

5. Try installing the package from the source code by running `pip install .` in the directory where you cloned the source code.

6. The package is not fully compatible with Windows, so it's better to use it in a Linux or MacOS environment.

Please let me know if you have more information about the error message and the environment you are running on, so I can help you more specifically.

**Comment by Erik6209** [comment] 2023-01-16 18:06
Thank you @DURGESH716. Point two and three helped me. additionally while using python 3.9 i noticed that the latest numpy version is not compatible. I had to downgrade numpy to get rid of importerrors. But now everything works, thanks for the quick help!

**Comment by tiruk007** [comment] 2023-01-16 18:08
@Erik6209  
Could you please close the issue if it is resolved ?

Thank you!

**Comment by DURGESH716** [comment] 2023-01-16 18:11
It's My Pleasure, @Erik6209. If everything seems perfect, You can close the issue as Completed. 
Thank You !!!

**Closed** 2023-01-16 19:08 UTC
Labels: type:build/install, subtype:windows, TF 2.11

**Comment by HripsimeS** [comment] 2023-01-20 11:59
@DURGESH716 Hello. I am trying to install tflite-model-maker package in order to use it for training of mobile models.
I found only once source for the installation https://pypi.org/project/tflite-model-maker/

I have tried all 3 methods mentioned there, but every time I try to import the package, there is always some issues or errors.
In all cases the issue is connected mostly with scann package.
**Could not find a version that satisfies the requirement scann==1.2.6 (from tflite-model-maker) (from versions: none)
No matching distribution found for scann==1.2.6**

Do you know how is possible to successfully install tflite-model-maker package for Windows 11? Thanks a lot in advance!

**Comment by Paryavi** [comment] 2023-05-04 01:16
The TFLite model maker library is broken. We can not install it. Not in Windows or Colab(Linux):

Also, the following code did not help resolve the issue.
pip install --no-dependencies tflite-model-maker

You can test it for yourself; I can not install it on Colab when I run TFLite model maker examples provided by Google people;
https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb

TFLite model maker installation on Tensorflow.org is not up to date either. It does not explain what dependencies are needed.

**Comment by darkladen** [comment] 2023-05-26 13:03
This package is absolutely broken. I never found other package that make so very hard to install. Not work by using no way.

**Comment by UsamaHameed1** [comment] 2023-06-03 22:38
Any solution so far for installing TFlite Model Maker

**Comment by Arya-rgb** [comment] 2023-07-23 13:23
omg, what should i do haha

**Comment by itssidhere** [comment] 2023-08-05 09:23
There's something wrong. It doesn't even install in collab

**Comment by kasfulanwar** [comment] 2023-08-08 08:04
> There's something wrong. It doesn't even install in collab

yess... still not working today (2023-08-08) in google collab

**Comment by 3du4rd0PI** [comment] 2023-10-11 17:07
I installed it in a env, however I can't call it. It's there but callable; If someone is interest I build the env in Colab with the following commands.
!pip install virtualenv
!virtualenv venv
!source venv/bin/activate
!python3 -V
!sudo add-apt-repository ppa:deadsnakes/ppa
!sudo apt install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10.12
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
!sudo update-alternatives --config python3!pip install virtualenv
!virtualenv venv
!source venv/bin/activate
!python --version
!sudo apt install python3.9-distutils -y
!sudo apt install python3.9-lib2to3 -y
!sudo apt install python3.9-gdbm -y
!sudo apt install python3.9-tk -y
!sudo apt install python3-pip
!python -m pip install --upgrade pip
!pip install -q tflite-model-maker
!pip install -q tflite-support

**Comment by ammarhamzi** [comment] 2023-11-18 12:35
still aint working ffs

**Comment by fransay** [comment] 2023-11-28 13:21
> This package is absolutely broken. I never found other package that make so very hard to install. Not work by using no way.

Just crazy mate!
Being here all night trying to get this package installed on an Ubuntu server sitting thousands of miles around from me.
