### ISSUE TITLE
tensorflow2rc1 import bug  

### ISSUE THREAD

**Issue by schoettner** [tensorflow/tensorflow#32574] opened 2019-09-17 08:31 UTC
Hi,
I was trying to convert one of my training templates to TensorFlow2 but encountered several issues. I can not reach a point where my code is even executed because many imports already terminate the application at start. 
```python
from tensorflow_core.python.client.session import InteractiveSession

def main():
    print('hello world')

if __name__ == "__main__":
    main()
```
This code results instantly in an error and the print is never reached.
```
2019-09-17 09:18:51.362815: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/python/session_create_counter
Traceback (most recent call last):
  File "/home/xxx/dev/tf2xxx/bug.py", line 1, in <module>
    from tensorflow_core.python.client.session import InteractiveSession
  File "/home/xxx/.virtualenv/tf2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 49, in <module>
    'Counter for number of sessions created in Python.')
  File "/home/xxx/.virtualenv/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/monitoring.py", line 183, in __init__
    name, description, *labels)
  File "/home/xxx/.virtualenv/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/monitoring.py", line 121, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```
Next to _InteractiveSession_ there are multiple other imports that cause problems with monitoring.py. Changing to tf2's eager mode and not worry about the session did not do the trick.

Keras however runs fine and does not cause any problems (except the conv2d layer + CUDA what causes problems for a while already). 

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: pip3
- TensorFlow version: 2.0.0rc1
- Python version: 3.6.8

**Comment by ravikyram** [comment] 2019-09-17 11:45
I have tried on colab with TF version 2.0.0rc1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/3a294d09dddd2f1fc218bd4bc30cc47c/untitled197.ipynb).Thanks!

**Comment by mihaimaruseac** [comment] 2019-09-17 16:02
Don't import directly from `tensorflow_core`, that is private API and will change under you and break you.

This import is what's causing your problem

**Comment by jvishnuvardhan** [comment] 2019-09-17 21:40
@schoettner I can confirm that @mihaimaruseac suggestion is working without any issues in `TF1.15rc1` and `2.0rc1`.  Just change first line to 
`from tensorflow.python.client.session import InteractiveSession`

I am closing this issue as it was resolved. Please feel free to open the issue if the suggested approach is not working for you. Thanks!

**Closed by jvishnuvardhan** 2019-09-17 21:40 UTC
Labels: TF 2.0-rc0, comp:eager, type:bug

**Comment by mihaimaruseac** [comment] 2019-09-17 22:34
Note that both importing from `tensorflow_core` and directly importing from `.python` are not supported and will break without any rollback.

The recommended way to use TensorFlow is `import tensorflow as tf` and accessing the API via the `tf` symbol and it's attributes.

**Comment by schoettner** [comment] 2019-09-18 13:10
Hi, thanks for your feedback. However, I can not confirm your solution. The imports are actually resolved by my IDE (IntelliJ Ultimate) because I could not use the imports I used in earlier versions.

```python
import tensorflow as tf

def main():
    with tf.Session() as sess:
        a = tf.constant(1, tf.float32)
        b = tf.constant(2, tf.float32)
        c = a + b
        sess.run([c])
    return

if __name__ == "__main__":
    main()
```

This code runs fine with tf14.0 while it does not run in tf2.0.0rc1
```
AttributeError: module 'tensorflow' has no attribute 'Session'
```
I tried the code in your colab code too. Same result.

**Comment by mihaimaruseac** [comment] 2019-09-18 15:38
Oh, this is because TF 2.0 is eager by default, no longer has sessions.

Try this instead:

```python
import tensorflow as tf

def main():
    a = tf.constant(1, tf.float32)
    b = tf.constant(2, tf.float32)
    c = a + b

if __name__ == "__main__":
    main()
```

Note that I also removed the not needed `return`

**Comment by schoettner** [comment] 2019-09-19 07:28
Hi Mihai,
removing the session is not a solution. I am aware that tf2 executes in eager mode. Session is only an example. I am not able to import a bunch of dependencies with tf.xxx

**Comment by jvishnuvardhan** [comment] 2019-09-19 13:48
@schoettner Can you describe with little more details on which of the tf.xxx dependencies you are not able to import? Thanks!

**Comment by mihaimaruseac** [comment] 2019-09-19 15:37
If you really need TF1.x symbols, look into `tf.compat.v1` but note that symbols from there will disappear at one point when we assume that most of our users have switched to using 2.x APIs.

**Comment by schoettner** [comment] 2019-09-19 17:08
@jvishnuvardhan i am working on it at the moment. Since most of the code broke after the migration (i am not used to eager mode) it takes some time to fix it. I am not sure why, but my IDE also does not support tf imports as it used to. When I worked through all the issues I am happy to provide the full list.

**Comment by mihaimaruseac** [comment] 2019-09-19 17:14
There is a converter to automatically change your code to TF2.0.

**Comment by schoettner** [comment] 2019-09-22 11:54
@mihaimaruseac To get a better understanding of changes from TF1 to TF2 I did not want to use the converter but do it myself. However, after several hours I resign. Many (but not all) imports could be fixed with adding 
```python
from __future__ import absolute_import, division, print_function, unicode_literals
```.
But I failed to get non-eager mode working without **tf.compact.v1**. So my current situation is:
- I can not access private library calls because they break my code before startup. Also not sure if they would help solve my problems anyway.
- For session based training I would have to add legacy code from **tf.compact.v1**,  what I want to avoid.
- Big chunks of my code are deprecated, because I am using tf instead of keras layers.

Due to those points I decided to drop my current templates and start from scratch. I follow the suggestion to switch to Keras and hope the issues I encountered some time ago are fixed (e.g. CUDA errors with the Conv2D layer or wrong mean updating of BatchNorm during inference). Thank you for your support!

**Comment by rodrigovimieiro** [comment] 2019-09-23 12:12
I am having a similar problem, which I posted [here](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam). If I import tensorflow 2.0 twice in the same IPython console, I get the same error posted here.

**Comment by mihaimaruseac** [comment] 2019-09-23 14:07
@rodrigovimieiro I answered there but summarizing here: TF imports have side effects which should be only executed once. Doing the same import twice in the same app results in that error. Please always use the only supported method of `import tensorflow as tf` (once) and then accessing the API via `tf`.

Note that this should go in a different issue, too.
