### ISSUE TITLE
Add eager with estimator

### ISSUE THREAD

**Issue by xiaocai00** [tensorflow/tensorflow#19706] opened 2018-06-01 23:16 UTC
By adding 
```
import tensorflow.contrib.eager as tfe
tf.enable_eager_execution()
```
at the beginning of the [python code](https://raw.githubusercontent.com/aymericdamien/TensorFlow-Examples/90bb4de75322f8c01048dd98c7f194442051d257/examples/3_NeuralNetworks/neural_network.py), I got the following RuntimeError: Estimators are not supported when eager execution is enabled.. 

```
File "neural_network.py", line 88, in <module>
    model = tf.estimator.Estimator(model_fn)
  File "/.../anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 171, in __init__
    'Estimators are not supported when eager execution is enabled.')

```

**Comment by tensorflowbutler** [comment] 2018-06-02 13:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment] 2018-06-04 18:18
@xiaocai00 : Could you please fill in the details asked for and provide a [minimal, verifiable, complete](https://stackoverflow.com/help/mcve) example to reproduce the problem?

That said though, a recent change (https://github.com/tensorflow/tensorflow/commit/0385bfe0726ad9710bfcca145e19611e9e2391bb), which is not included in TensorFlow 1.8 but will be in TensorFlow 1.9, makes it possible to use `Estimator` objects even after eager execution is enabled.

So most likely the feature you desire should be in the next version of TensorFlow. (The release branch for which was just cut recently).

Hope that helps!

**Comment by tensorflowbutler** [comment] 2018-06-19 18:44
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-06-19 18:50
Closing this since `Estimator` objects can now be used with eager execution enabled.

**Closed by asimshankar** 2018-06-19 18:50 UTC
Labels: stat:awaiting response

**Comment by tgrel** [comment] 2019-07-08 15:49
This issue is fixed in a sense that eager is simply disabled throughout the estimator code. See for example: [](https://github.com/tensorflow/estimator/blob/r2.0/tensorflow_estimator/python/estimator/estimator.py#L340) for the details. 

Are there any plans to actually enable eager execution in estimator? This way developers could use eager e.g. to debug their model function or custom metrics.
