### ISSUE TITLE
 configure script crashing in virtuealenv due to issues with site.getsitepackages()

### ISSUE THREAD

**Issue by mfernezir** [tensorflow/tensorflow#3933] opened 2016-08-19 20:38 UTC
In the current master, the line https://github.com/tensorflow/tensorflow/blob/master/util/python/python_config.sh#L63

causes a crash stating 

> AttributeError: module 'site' has no attribute 'getsitepackages'

 if running confgure inside virtualenv Python environment.

The underlying issue is that virtualenv uses an older site package that doesn't have getsitepackages. It is still an open bug in virtualenv after 4 years (!): https://github.com/pypa/virtualenv/issues/355.

For reference, I am using Python 3, virtualenv and virtualenvwrapper on Ubuntu 16.04 with CUDA 8.0. The v0.10.0rc0 release works for me, but this recent fix in python_config.sh breaks virtualenv usage.

**Comment by po0ya** [comment] 2016-08-21 00:52
I'm facing the same issue

**Comment by aselle** [comment] 2016-08-22 17:50
@danmane, you merged this change I believe, but it was originally authored by @itsmeolivia. Could @itsmeolivia look at fixing this so it can work with the older site interface so that virtualenv doesn't break. Thanks!

**Comment by itsmeolivia** [comment] 2016-08-22 21:27
I ran it and it doesn't crash because of the AttributeError.  It crashes because it expects user input for the python library path and defaults to providing nothing if the python library path cannot be found nor provided by the user.  Right now it is working as intended but the installation can always be made a little smoother.

Here's a quick workaround to find your path manually while I change the script a lil more:

In your virtualenv run:
`$ python`
`>>> from distutils.sysconfig import get_python_lib`
`>>> print(get_python_lib())` 

Copy that output and when you run `./configure` paste it into the line that says 
`Please input the desired Python library path to use.  Default is []`

**Closed** 2016-08-24 19:02 UTC
Labels: installation/startup

**Comment by guoyejun** [comment] 2018-07-19 02:15
looks that the issue is still there. I'm using virtualenv 15.0.1 and the latest tensorflow code (ae62a692ddb53253462c1f79702fbc45baeb4ae3) on ubuntu 16.04 x64.

$virtualenv -p python3 ~/pyenv/tfbuild
$source ~/pyenv/tfbuild/bin/activate
(tfbuild) yguo18@yguo18-skl-u1604:/work/ml/tensorflow_work/tensorflow$ ./configure 
WARNING: ignoring http_proxy in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0 installed.
Please specify the location of python. [Default is /home/yguo18/pyenv/tfbuild/bin/python]: 


Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
Found possible Python library paths:
  /home/yguo18/pyenv/tfbuild/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/yguo18/pyenv/tfbuild/lib/python3.6/site-packages]
/home/yguo18/pyenv/tfbuild/lib/python3.6/site-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: n
No jemalloc as malloc support will be enabled for TensorFlow.
...
