### ISSUE TITLE
Error in training ssd_mobilenet_v1_pets.config for my own dataset

### ISSUE THREAD

**Issue by ShilpaJagadeeshappa** [tensorflow/tensorflow#30116] opened 2019-06-25 11:09 UTC
Hi,
Iam getting this error when i run the command-  python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/opt/tensorflow/models/research/object_detection/legacy/trainer.py", line 416, in train
    saver=saver)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 790, in train
    ignore_live_threads=ignore_live_threads)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1279, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/shilpa.j/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]
         [[{{node cond_1/RandomCropImage/sample_distorted_bounding_box/SampleDistortedBoundingBoxV2}}]]
shilpa.j@Theorem-TrainUP:/opt/tensorflow/models/research/object_detection$

**Comment by Arritmic** [comment] 2019-06-26 07:59
`tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]`

I think you should review your train CSV files CSV files to see if there are any entries with Width and Height as 0 or missing some value.

**Comment by ravikyram** [comment] 2019-06-26 11:14
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Can you please provide full code snippet to reproduce the issue 

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2019-07-03 05:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-03 05:14 UTC
Labels: comp:model, stat:awaiting response, type:support

**Comment by ShilpaJagadeeshappa** [comment] 2019-07-03 05:27
> 
> 
> `tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]`
> 
> I think you should review your train CSV files CSV files to see if there are any entries with Width and Height as 0 or missing some value.

Thanks @Arritmic .Yes this has resolved my problem.

**Comment by ShilpaJagadeeshappa** [comment] 2019-07-03 05:40
This is my system config -

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Ubuntu
    TensorFlow installed from (source or binary):
    TensorFlow version: 1.14.0
    Python version: 3.5.0
    Installed using virtualenv? pip? conda?: virtualenv
    GCC/Compiler version (if compiling from source):
    CUDA/cuDNN version: Using Linux server 8GB RAM with 4 cored on windows machine
    Windows OS config:
 	processor:i3 CPU@3.40GHz 
	RAM:4GB
	System type:64 bit
      GPU model and memory: N/A
 I solved it by reviewing csv data for train set and test set for zeros in width column and height column.
Thank you all
