### ISSUE TITLE
tensorflow.keras IDE auto-completion fails

### ISSUE THREAD

**Issue by Yuri-Su** [tensorflow/tensorflow#56231] opened 2022-05-24 01:53 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8 2.9

### Custom Code

Yes

### OS Platform and Distribution

win mac

### Python version

3.10

### Current Behaviour?

```shell
A bug happened!
tensorflow.keras IDE auto-completion fails.
Using "from tensorflow." does not pop up keras, pycharm will report red but it works.
Also, tf 2.5 is normal.
I see there are other people who have had this problem
```

### Standalone code to reproduce the issue

```shell
from tensorflow.keras import layers
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment] 2022-05-24 13:35
@Yuri-Su ,
Could you provide the error log which you are facing issue. It helps to debug the issue. Thank you!

**Comment by Dadealos** [comment] 2022-05-24 19:54
So... there's no "error log" for code completion failures. As Yuri-Su mentioned, everyone is having the same issue.

Steps to reproduce:
1. from tensorflow.keras import Model

That's literally it. If you want to rule out other IDEs, configuration issues, etc etc, just go to https://www.tensorflow.org/tutorials/quickstart/advanced

Run the first cell:
![image](https://user-images.githubusercontent.com/36662766/170120811-739ade36-f3cf-4da8-9e7e-ba263a91fea1.png)

**Comment by Dadealos** [comment] 2022-05-24 20:05
A side question - does everyone just use Notepad++? This has been a persistent issue with VSCode and Pycharm since at least 2017. I'm baffled that it's not fixed, but I don't understand it well enough to fix it myself.

I would happily just buy a different IDE if there's one that supports code completion and doesn't break on every new TF release.

**Comment by Yuri-Su** [comment] 2022-05-25 00:47
> A side question - does everyone just use Notepad++? This has been a persistent issue with VSCode and Pycharm since at least 2017. I'm baffled that it's not fixed, but I don't understand it well enough to fix it myself.
> 
> I would happily just buy a different IDE if there's one that supports code completion and doesn't break on every new TF release.

![image](https://user-images.githubusercontent.com/45455052/170154766-581c4426-1c00-486a-97c9-8ef77e2ed432.png)
As far as I know, this problem appeared from 2.6 and lasted until 2.9, if it is not solved, I am willing to use pytorch in the future.

**Comment by tilakrayal** [comment] 2022-05-26 09:05
@Yuri-Su ,
I was able to import and execute the code in tensorflow version 2.8. Could you find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/654f3927ab97d7e30ddc75374bf7889d/advanced.ipynb). Thanks you!

**Comment by Yuri-Su** [comment] 2022-05-26 09:11
> @Yuri-Su , I was able to import and execute the code in tensorflow version 2.8. Could you find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/654f3927ab97d7e30ddc75374bf7889d/advanced.ipynb). Thanks you!

Maybe you misunderstood what I meant. The code will run, but there will be red lines and no code completion

**Comment by cpuimage** [comment] 2022-05-30 08:58
@Yuri-Su try this:
 https://github.com/tensorflow/tensorflow/issues/53144#issuecomment-985179600

**Comment by Yuri-Su** [comment] 2022-05-31 05:54
> @Yuri-Su try this: [#53144 (comment)](https://github.com/tensorflow/tensorflow/issues/53144#issuecomment-985179600)

![image](https://user-images.githubusercontent.com/45455052/171102216-7c26a877-6371-4d1c-98ac-257deb934b2f.png)
I have made the changes as suggested and cleared the cache, but it still doesn't work.

**Comment by cpuimage** [comment] 2022-05-31 06:19
try this:

before:

```# Explicitly import lazy-loaded modules to support autocompletion.
# pylint: disable=g-import-not-at-top
if _typing.TYPE_CHECKING:
  from tensorflow_estimator.python.estimator.api._v2 import estimator
# pylint: enable=g-import-not-at-top
```

after:

```# Explicitly import lazy-loaded modules to support autocompletion.
# pylint: disable=g-import-not-at-top
if _typing.TYPE_CHECKING:
  from tensorflow_estimator.python.estimator.api._v2 import estimator
  from keras.api._v2 import keras
# pylint: enable=g-import-not-at-top
```

**Comment by Yuri-Su** [comment] 2022-05-31 06:42
> @Yuri-Su try this:
> 
> before:
> 
> ```
> # Explicitly import lazy-loaded modules to support autocompletion.
> # pylint: disable=g-import-not-at-top
> if _typing.TYPE_CHECKING:
>   from tensorflow_estimator.python.estimator.api._v2 import estimator
> # pylint: enable=g-import-not-at-top
> ```
> 
> after:
> 
> ```
> # Explicitly import lazy-loaded modules to support autocompletion.
> # pylint: disable=g-import-not-at-top
> if _typing.TYPE_CHECKING:
>   from tensorflow_estimator.python.estimator.api._v2 import estimator
>   from keras.api._v2 import keras
> # pylint: enable=g-import-not-at-top
> ```

![image](https://user-images.githubusercontent.com/45455052/171108704-7070d41b-1efc-4894-862d-25757527695a.png)
![image](https://user-images.githubusercontent.com/45455052/171108712-f2aca7fd-765c-45b7-980c-c985af454d81.png)
Thank you very much for your help, but still can't solve the problem.
Bye tensorflow, hello **pytorch**！！！

**Comment by cpuimage** [comment] 2022-05-31 07:05
@Yuri-Su 
site-packages\tensorflow\keras is removed in tf 2.8 and tf 2.9

so you can't import it like that.

The temporary solution can only be:

before:
`from tensorflow.keras.callbacks import EarlyStopping`
after:
`from tensorflow.python.keras.callbacks import EarlyStopping`

or:
`import tensorflow as tf`
then 
`tf.keras.~`

**Comment by alkatar21** [comment] 2022-05-31 13:54
This has been a problem for a while now, see #53144. It would be really nice if this would be fixed. It can't be that everyone who uses an IDE and code completion, which should be normal by now, has to hack around in his installation.

**Comment by qlzh727** [comment] 2022-05-31 16:42
Sorry for the very long wait. 

This issue should be addressed by https://github.com/tensorflow/tensorflow/pull/54104, which is landed on tf-nightly (but didn't included in tf 2.9). I was able to verify this locally with the latest tf-nightly pip package. 

Could any of you test with latest tf-nightly on the IDE and see if it fix the issue? Thanks.

**Comment by gadagashwini** [comment] 2022-06-01 01:56
Hi @qlzh727, I could able to replicate the issue on Tf-nightly.
Please find the attached screenshot below. 
<img width="1680" alt="Screen Shot 2022-06-01 at 7 25 44 AM" src="https://user-images.githubusercontent.com/99852755/171312589-f2b58e16-74e0-4846-8ddb-8696df564c11.png">

**Comment by qlzh727** [comment] 2022-06-01 02:35
Humm, that's quite weird. Not sure if it is a colab issue. Please check my screenshot in pycharm.

<img width="1027" alt="Screen Shot 2022-05-31 at 7 33 25 PM" src="https://user-images.githubusercontent.com/5118881/171316319-a7db7db8-8193-4fbb-b7ae-30dc23aee9db.png">

**Comment by mshijie** [comment] 2022-06-01 06:40
<img width="602" alt="image" src="https://user-images.githubusercontent.com/2002700/171343234-ad911e0f-9677-4fd4-9a2e-dbf9741edb87.png">

PyCharm 2021.3 . No code completion.

**Comment by alkatar21** [comment] 2022-06-01 09:47
@qlzh727 This version actually fixes one bug, but various others not. I tested it in the current docker container:
```py
>>> tf.__version__
'2.10.0-dev20220531'
```
With #54104 the bug originally reported in #53144 is fixed, that the autocompletion for `tf.keras.<autocompletion>` does not work.

However, it does not fix the problem described in https://github.com/tensorflow/tensorflow/issues/53144#issuecomment-1133027918. For example, it still does not work `from tensorflow.keras import Model`.

In the following a test protocol, which should help to solve this. It does not show all possible problems, but should help to solve all of them if implemented well (I used VSCode 1.67.2 with Pylance v2022.5.3 and the docker container for each version):
```python
"""Testing tensorflow.keras autocompletion."""
# pyright: basic, reportMissingTypeStubs=false

''' Test 1: tf.keras.<autocompletion>'''
import tensorflow as tf

tf.keras.Model()
tf.keras.preprocessing.image_dataset_from_directory(None)

# Broken in 2.5.0, 2.7.0, 2.9.0 (resolves to (keras: LazyLoader) -> everything resolves to Any == No autocompletion)
# Works in 2.10.0-dev20220531

''' Test 2: from tf import keras -> keras.<autocompletion>'''
from tensorflow import keras

keras.Model()
keras.preprocessing.image_dataset_from_directory(None)

# Broken in 2.5.0, 2.7.0, 2.9.0 (resolves to (keras: LazyLoader) -> everything resolves to Any == No autocompletion)
# Broken in 2.10.0-dev20220531 (keras is resolved to tensorflow/__init__.py)

''' Test 3: from tensorflow.keras import Model'''
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense

# Works in 2.5.0, 2.7.0
# Broken in 2.9.0, 2.10.0-dev20220531 (Import "tensorflow.keras" could not be resolved -> Model: Unknown)
```

In 2.7.0 the fix for all the issues was to add the following to `tensorflow/__init__.py#L394-L400`:
```diff
# Explicitly import lazy-loaded modules to support autocompletion.
# pylint: disable=g-import-not-at-top
if not _six.PY2:
  import typing as _typing
  if _typing.TYPE_CHECKING:
    from tensorflow_estimator.python.estimator.api._v2 import estimator
+   from keras.api._v2 import keras
# pylint: enable=g-import-not-at-top
```

For 2.10/nightly i do not know the solution.
- I do not completly understand the problem for Test 2, but I think it would resolve to `tensorflow/keras/__init__.py` if the package still exists (at least it does in 2.7 with the fix).
- I think the reason for fail of Test 3 is that the `tensorflow.keras` package is no longer generated in 2.8 and onwards.

@mshijie You tested the wrong tensorflow version. That it does not work there is known.

**Comment by qlzh727** [comment] 2022-06-01 17:18
Thanks for the detailed report. Let me take a closer look and see how can we address the test2/3 there.

**Comment by prjrg** [comment] 2022-06-05 16:52
I've tested tensorflow v2.8-2.9-(nightly with the fix) and autocompletion for "import tensorflow.anypublicmodule" yields syntax error (not found) eg tf.keras, tf.data, ..., either in PyCharm and VS Code and jupyter with plugins when attached to IPy kernel.

Can someone estimate when the issue will be solved?

Thank you for your time.

**Comment by alkatar21** [comment] 2022-06-06 10:44
@qlzh727 As an extension to my last [comment](https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1143377838). I looked again in the current build and actually it would be enough to generate the `keras.api._v2.keras` folder just under `tensorflow.keras`. It was similar to this in tf2.7. However, this is probably more of a hack than an optimal solution. I don't know enough about python to know if there is another way to detect a module without running the code than that it is actually present in that location.

@prjrg I can't reproduce this using VSCode with pylance. The following all autocomplete in nightly:
```py
import tensorflow as tf
tf.keras.Model()
tf.keras.preprocessing.image_dataset_from_directory(None)
tf.data.Dataset(None)
```
Are you sure you have autocompletion for 3rd-party packages at all? Parts of the autocompletion work for sure.

**Comment by alkatar21** [comment] 2022-06-06 13:22
Yes, that is what the issue is about and I am trying to help with that to get this finally fixed.
https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1146847236 had suggested that `import tensorflow.anypublicmodule` does not work and not `from tensorflow.keras import layers`.
But `from tensorflow.data import Dataset` is not supported on purpose as far es I know, but keras should of course. I can't find the statement for this right now.

**Comment by qlzh727** [comment] 2022-06-23 23:34
Sending https://github.com/tensorflow/tensorflow/commit/e65b68a0914408118995d2f8b55c4286859362f8.

1. This change should fix the test case 2 in https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1143377838.
2. I don't think the test case 3 in https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1143377838 was ever supported, eg if I do "from tensorflow.data import Dataset" or "from tensorflow.math import add", it will not auto complete for me.

With this case, I think it should fix the majority of the use case:
1. "import tensorflow as tf; tf.keras.xxx"
2. "from tensorflow import keras; keras.xxx"

**Comment by alkatar21** [comment] 2022-06-24 08:12
@qlzh727 Thanks for fixing case 2. When will it be possible to try this out?

Test case 3 was supported up to and including 2.7. It is true that this never applied to many parts of tensorflow and this is probably intended, as far as I know.
But for Keras it was always supported and to my knowledge it is/was the recommended standard to use `from tensorflow.keras.layers import Dense` or for many layers `from tensorflow.keras import layers`. The syntax is also used in all keras examples, for example: https://keras.io/examples/vision/autoencoder/

(This has always worked up to and including 2.7, because there was actually always the package `tensorflow.keras` with all submodules, which was generated (`# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.`) and thus accessible to linters.
This also always fixed case 2 before, because the module was probably loaded before the `__init__.py`, but e65b68a probably makes it more future-proof.)

**Comment by alkatar21** [comment] 2022-06-24 16:42
I have just tested nightly:
```python
>>> tf.__version__
'2.10.0-dev20220624'
```

There test case 2 (with pylance v2022.6.30) still does not work. `from tensorflow import keras` is still resolved to `tensorflow/__init__.py` which results in no autocompletion for keras, but for tensorflow.


Case 3 has nothing directly to do with `tensorflow/python/keras`. A package `tensorflow/keras` was autogenerated, which would be equivalent to the `keras.api._v2.keras` folder by now. If you copy the folder to tensorflow, it works again as before. Or is copying/generating the same folder under `tensorflow/` the problem? According to the files in nightly, they are still generated by tensorflow ( `# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.`), which should make generating them in a different location not so complicated?

**Comment by qlzh727** [comment] 2022-06-24 22:15
Humm, weird. I was able to get auto completion on my local pycharm.

<img width="1792" alt="Screen Shot 2022-06-24 at 3 14 24 PM" src="https://user-images.githubusercontent.com/5118881/175699862-afa5e6be-4d6f-4bf1-87e3-902d23c85e38.png">

**Comment by alkatar21** [comment] 2022-06-26 10:19
This are my results with VSCode (with pylance v2022.6.30 and a pycharm like theme) :
```py
>>> tf.__version__
'2.10.0-dev20220624'
```
![grafik](https://user-images.githubusercontent.com/61387986/175809390-de74cc9a-93a9-4c8f-a4f2-04b4c2a6cd62.png)
![grafik](https://user-images.githubusercontent.com/61387986/175809419-32ac8880-18bc-46dc-84a0-c9dbdbe51bfd.png)
![grafik](https://user-images.githubusercontent.com/61387986/175809445-58aceebc-987d-45d5-b416-28809a6119c8.png)

**Comment by qlzh727** [comment] 2022-06-28 16:48
let me install vscode and play with it. Not sure which part triggers this difference.

**Comment by GF-Huang** [comment] 2022-07-09 08:23
Issue still, no IntelliSense for parameters.

It only show `Dense`, no parameters IntelliSense.

![image](https://user-images.githubusercontent.com/4510984/178097893-6f3c5ffe-0a0c-4700-932a-97508f864b34.png)

**Comment by alkatar21** [comment] 2022-07-09 10:40
@GF-Huang This is the case because tf.keras is not yet resolved properly (resolves to LazyLoader which resulsts in Any) in 2.9.1. There is a commit in nightly (e65b68a) that will probably be in 2.10 that fixes this case.

**Comment by YouJiacheng** [comment] 2022-07-28 05:30
Pylance auto-completion works before https://github.com/tensorflow/tensorflow/commit/e65b68a0914408118995d2f8b55c4286859362f8. Pylance does recognize the overwriting by the explicit import statement in the TYPE_CHECKING block
It doesn't work for release version because changes in https://github.com/tensorflow/tensorflow/pull/54104 haven't included in release yet.

**Comment by hilanzy** [comment] 2022-09-07 10:18
@qlzh727  This issue is still happened on v2.10.0
https://github.com/tensorflow/tensorflow/issues/53271#issuecomment-1239103757

**Comment by qlzh727** [comment] 2022-09-07 17:49
Mimic my response from other thread in https://github.com/tensorflow/tensorflow/issues/53271#issuecomment-1239696497

=======================================


Thanks for the information.

Based on my rough knowledge for auto completion, I think the issue probably caused by difference between package/directory/module.

Most of the IDE will try to auto complete by the package tree structure, so if there is a directory with init under tensorflow call "keras", then it will resolve correctly when you do "from tensorflow.keras.xxxx import yyy". This was working before 2.7 since Keras was part of the Tensorflow PIP package.

Note that the "import tensorflow as tf; tf.keras.xxx.yyy" is resolved differently. tf.keras is firstly resolved into the logic in the tensorflow/init.py, and then the keras becomes the "keras.apis._v2.keras", which resolved correctly to the keras PIP package.

Before TF 2.7, I think the we did some manual mimic for the keras APIs to tensorflow/keras folder from tensorflow/python/keras/apis, so that it the package level auto completion works, but that is not the case anymore after 2.7 since the keras is a standalone package.

As a quick test on my local, I manually created a symlink under venv/lib/python3.10/site-packages/tensorflow by ln -s ../keras/api/_v2/keras/ keras (assuming you have tensorflow and keras pip package installed properly), and then the IDE can resolve the package level auto completion correctly.

I am not sure if this fix can be applied to TF direclty, since the symlink is not well supported on windows, and might be in different location if the package is installed differently.

**Comment by alkatar21** [comment] 2022-09-14 15:18
@qlzh727 I just tested what is suggested in https://github.com/tensorflow/tensorflow/issues/53271#issuecomment-1239141639. 
This would at least allow to use `from tensorflow import keras` (case 2 from https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1143377838).
I have not found anything in a quick search that no longer works. Would it be possible to change this?

**Comment by Dadealos** [comment] 2022-09-25 02:12
Man, I can't believe this is still an issue 😒

Symlink works fine on Windows, at least as of TF 2.9. Windows users - just open an elevated cmd prompt, go to your site-packages\tensorflow directory and type:

**mklink /D keras ..\keras\api\_v2\keras**

If for whatever reason you can't make a symlink, a junction works just as well:

**mklink /J keras C:\fullpath\site-packages\keras\api\_v2\keras**

**Comment by spottenn** [comment] 2022-11-04 22:37
> 

Thank you! Worked for me. I'm on windows 11, VS Code, python 3.10.8, tensorflow 2.10.0

**Comment by swap-10** [comment] 2023-01-09 08:26
This still seems to be an issue with TF 2.11.0 Python 3.9.4 and VSCode
`from tensorflow.keras import applications`
generates a warning that `tensorflow.keras` could not be resolved

Is it just not recommended to use this form of import now and rather use
`import tensorflow as tf; from tf.keras import ...` ?

**Comment by mxxndawn** [comment] 2023-02-11 06:15
macOS : Ventura 13.2
VSCode : 1.75.1
miniconda : 23.1.0
python : 3.9.16
    - pip : 22.3.1
    - TensorFlow : 2.11.0
    -  numpy : 1.24.2

The same problem occurs in the above specification.
The code is written by vscode.

'from tensorflow.python import keras'
No error occurs, but intelisense still does not work.

**Comment by alkatar21** [comment] 2023-02-11 10:13
@mxxndawn With the current stable pylance version 2023.2.20 there is nearly no autocompletion for tensorflow at all. That will probably solved with https://github.com/microsoft/pylance-release/issues/3937? Which has the start of https://github.com/python/typeshed/issues/7144 as an underlying reason. You can use 2023.2.10 until a version with the fix is released.

I don't know whether this solves your specific problem, as there are many other problems with tensorflow autocompletion, but with this it should be possible to use autocompletion etc. at least in a basic way.

Furthermore it was pointed out in some places (for example here https://github.com/tensorflow/tensorflow/issues/53271#issuecomment-1239400795) by tensorflow/google people that it is intended to use keras as follows (I also know that this is not done even in tutorials, because the other way also works, but then without intellisense.)
```py
import tensorflow as tf
tf.keras.xxx.yyy
```

**Comment by mxxndawn** [comment] 2023-02-11 10:33
@alkatar21 Simply 'pylance' version 2023.2.10 resolved the issue.

I don't know much because I've recently started studying, but I hope the problems that have occurred will be solved as soon as possible.

Thanks for your help.  Have a great day :)

**Comment by rogerwaldvogel** [comment] 2023-02-16 13:51
Please fix this issue.

**Comment by alkatar21** [comment] 2023-02-16 13:55
@rogerwaldvogel This issue has been fixed in [pylance](https://github.com/microsoft/pylance-release) prerelease version 2023.2.31. See: https://github.com/microsoft/pylance-release/issues/3937#issuecomment-1432301102

**Comment by Vrajs16** [comment] 2023-03-10 03:02
I am also having this problem. Its kinda of annoying not having autocomplete.

**Comment by haifeng-jin** [comment] 2023-03-10 20:51
We are working on a new keras import mechanism, which I expect would solve this issue along the way. Will post here when it is ready.

**Comment by haifeng-jin** [comment] 2023-03-26 09:22
The new import mechanism is in the nightly now.
Welcome to try out!
🎉🎉

[Related post](https://twitter.com/fchollet/status/1639776922019454976?s=20)

**Comment by haifeng-jin** [comment] 2023-04-12 20:53
I am closing this issue.
Please reopen if TF 2.13 release still have this problem.

**Closed by haifeng-jin** 2023-04-12 20:53 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.8

**Comment by ashwin8121** [comment] 2023-05-22 11:38
Just **copy** the folder **keras** from site-packages/tensorflow/python to site-packages/tensorflow. And the auto completion will start working perfectly

**Comment by brorro** [comment] 2023-06-28 05:41
It still shows tensorflow.keras could not be resolved in VScode.
Tested in:
TensorFlow version: 2.13.0-rc2
Pylance: v2023.6.31
Python: 3.11

**Comment by Hacker1337** [comment] 2023-07-14 18:13
> before:
> `from tensorflow.keras.callbacks import EarlyStopping`
> after:
> `from tensorflow.python.keras.callbacks import EarlyStopping`

Be careful with that. It fixed the issue for me. But then I found out that it harmed performance really strong and increased model learning time 12 times....

**Comment by bermeitinger-b** [comment] 2023-07-14 19:08
Use a recent version of tensorflow.

**Comment by Darkdragon84** [comment] 2023-07-19 09:29
@haifeng-jin a change in keras will not solve anything. The problem is in tensorflow and the problem is still there in the latest pypi release `2.13.0` as nothing changed in the lazy import in `tensorflow.__init__.py`
```python
_keras_module = "keras.api._v2.keras"
_keras = _LazyLoader("keras", globals(), _keras_module)
_module_dir = _module_util.get_parent_dir_for_name(_keras_module)
if _module_dir:
  _current_module.__path__ = [_module_dir] + _current_module.__path__
setattr(_current_module, "keras", _keras)
```
and most IDEs thus can't find `tensorflow.keras` in during code inspection. @bermeitinger-b which version are you referring to that would change this?

The problem will persist until either
 - tensorflow does a normal `from  keras.api._v2 import keras` (can anyone elaborate why this isn't done?)
 or
 - All IDEs adapt to understand that particular tensorflow specific import syntax.
 
 I don't find it realistic to require all dev tools and IDEs to adapt to that design choice. Imho it would be very beneficial for tensorflow in the future if the tensorflow dev team heeded the requests of hitherto loyal tensorflow users and responded to this somewhat annoying issue.

**Comment by kruthi-sb** [comment] 2023-07-29 08:25
> Man, I can't believe this is still an issue 😒
> 
> Symlink works fine on Windows, at least as of TF 2.9. Windows users - just open an elevated cmd prompt, go to your site-packages\tensorflow directory and type:
> 
> **mklink /D keras ..\keras\api_v2\keras**
> 
> If for whatever reason you can't make a symlink, a junction works just as well:
> 
> **mklink /J keras C:\fullpath\site-packages\keras\api_v2\keras**

This worked for me! thanks

**Comment by weidler** [comment] 2023-11-29 09:52
This issue has resurfaced in PyCharm with TF/Keras 2.15.

**Comment by michelkok** [comment] 2023-11-29 09:55
Not a real solution at all, but I just want to mention that Keras V3 came out yesterday. If you can already use it, then you have no problem with this anymore.

**Comment by OlegNovosad** [comment] 2023-12-06 09:19
This is so crazy. 

PyCharm 2023.2.5 and VSCode 1.84.2 (pylance v2023.11.10) still issue with tensorflow 2.15.0.
I'm starting learning tensorflow, keras and all of that stuff and not being able to see autocompletion and being forced to memorising optimisers, layers, metrics, params and all other stuff is frustrating.

**Comment by haifeng-jin** [comment] 2023-12-10 01:52
@weidler @OlegNovosad Are you using `import keras` or `from tensorflow import keras`?
`import keras` should always work for autocompletion.

**Comment by OlegNovosad** [comment] 2023-12-10 08:48
@haifeng-jin I'm using `import tensorflow as tf` and then `tf.keras.<whatever>`

**Comment by Jasonsey** [comment] 2023-12-19 12:55
我实在搞不懂，就这么一个代码提醒的问题，从2.6开始到现在都2.15了还没解决？维护人员是吃屎的吗？你看看隔壁pytorch，生态一个比一个好，各种组件不断完善。而你们现在LLM一个都没赶上，之前的问题也都没有解决，你让我们有什么信息继续使用你们这个框架。如果实在不想玩了，想混日子，直接关掉这个项目好了，苦苦支撑真是浪费资源

**Comment by haifeng-jin** [comment] 2023-12-19 22:23
@OlegNovosad @weidler , Thanks for the reply! Unfortunately, I don't think we can do much about the `tf.keras` import path.

On the Keras side, we have implemented a new mechanism for API exporting, which works for both Keras 2 (since TF 2.13) & 3 for code completion. It creates real directories and files under the import path instead of just adding attributes. So it should work with all code completion tools in IDEs.

**A note for new users**:
Please `import keras` directly in order to use the code completion feature.

**Comment by lllllllllaa** [comment] 2023-12-30 13:54
i made it autocompleting by changing import keras section in init.py tf 2.14 to:
```
# Lazy-load Keras v2/3.
import typing as _typing
if _typing.TYPE_CHECKING:
  from keras.api._v2 import keras
else:
  _tf_uses_legacy_keras = (
          _os.environ.get("TF_USE_LEGACY_KERAS", None) in ("true", "True", "1"))
  setattr(_current_module, "keras", _KerasLazyLoader(globals()))
  _module_dir = _module_util.get_parent_dir_for_name("keras._tf_keras.keras")
  _current_module.__path__ = [_module_dir] + _current_module.__path__
  if _tf_uses_legacy_keras:
    _module_dir = _module_util.get_parent_dir_for_name("tf_keras.api._v2.keras")
  else:
    _module_dir = _module_util.get_parent_dir_for_name("keras.api._v2.keras")
  _current_module.__path__ = [_module_dir] + _current_module.__path__
```
can someone please tell me if it's going to crash

**Comment by claCase** [comment] 2024-01-27 17:23
@haifeng-jin On older tf versions this method of importing keras directly and then using tf functions used to have conflicts between the two. It seems this is still an issue

**Comment by steveepreston** [comment] 2024-08-28 13:36
this issue still exist in 2024.2 with TensorFlow 2.16.1

**Comment by olurocks** [comment] 2024-09-19 02:19
Issue still persists on vscode .... 7 years down the line and no fix

interesting

**Comment by steveepreston** [comment] 2024-09-19 17:02
This issue still exist in PyCharm 2024.2.1 with TensorFlow 2.17

i'm wondering why issue is closed

**Comment by yuanxiqd** [comment] 2024-11-08 09:22
This issue still exist in VScode 1.95.2 with Tensorflow 2.18.

**Comment by steveepreston** [comment] 2024-11-08 20:41
@haifeng-jin Please re-open the issue. problem still exists in TensorFlow 2.17

**Comment by steveepreston** [comment] 2024-11-08 20:43
@haifeng-jin @Yuri-Su Please re-open the issue. problem still exists in TensorFlow 2.17

**Comment by Letronxis** [comment] 2024-12-01 18:41
TensorFlow's team really really fail me for many times. Changing installation methods multiple times, annoying warnings after running code, and compatibility issues between "import"  and IDE

**Comment by steveepreston** [comment] 2024-12-07 07:42
@Letronxis Sadly worst thing is that long time issues like this are marked as closed and no one trying to open and follow it

**Comment by Roobahist** [comment] 2025-04-14 02:21
Still unresolved. VSCode 1.99.2 Tensorflow 2.18.0.
