### ISSUE TITLE
Unsupported data type in placeholder op:2

### ISSUE THREAD

**Issue by Archernarkiu** [tensorflow/tensorflow#24825] opened 2019-01-10 08:31 UTC
When I tried to convert a .pb to .tflite, an error occurred.
The command line shows below:

 > tflite_convert \
>   --output_file=model_file.tflite \
>   --graph_def_file=model_file.pb \
>   --input_arrays=input1,input2 \
>   --output_arrays=output1,output2 \
>   --input_shapes=512,512,3:2

And the errors :

> RuntimeError: TOCO failed see console for info.
> 2019-01-10 16:03:15.168961: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] **Unsupported data type in placeholder op: 2**
> 2019-01-10 16:03:15.168987: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] **Unsupported data type in placeholder op: 2**
> 2019-01-10 16:03:15.168995: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] Unsupported data type in placeholder op: 2
> 2019-01-10 16:03:15.169013: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] Unsupported data type in placeholder op: 2
> 2019-01-10 16:03:15.169019: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] Unsupported data type in placeholder op: 2
> 2019-01-10 16:03:15.169025: I tensorflow/contrib/lite/toco/import_tensorflow.cc:181] Unsupported data type in placeholder op: 2
> 2019-01-10 16:03:15.177018: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 740 operators, 1073 arrays (0 quantized)
> 2019-01-10 16:03:15.191193: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 740 operators, 1073 arrays (0 quantized)
> 2019-01-10 16:03:15.205171: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 126 operators, 296 arrays (0 quantized)
> 2019-01-10 16:03:15.207152: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 126 operators, 296 arrays (0 quantized)
> 2019-01-10 16:03:15.208723: F tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:164] **An array, detect/cast, still does not have a known data type after all graph transformations have run.**
> Aborted (core dumped)
> 
> None

I have no idea about this error, can anyone offer help.

**Comment by Oceania2018** [comment] 2019-01-10 10:58
@Archernarkiu Hope this can help you:

```cc
ArrayDataType ConvertDataType(tensorflow::DataType dtype) {
  if (dtype == DT_UINT8)
    return ArrayDataType::kUint8;
  else if (dtype == DT_FLOAT)
    return ArrayDataType::kFloat;
  else if (dtype == DT_BOOL)
    return ArrayDataType::kBool;
  else if (dtype == DT_INT32)
    return ArrayDataType::kInt32;
  else if (dtype == DT_INT64)
    return ArrayDataType::kInt64;
  else if (dtype == DT_STRING)
    return ArrayDataType::kString;
  else
    LOG(INFO) << "Unsupported data type in placeholder op: " << dtype;
  return ArrayDataType::kNone;
}
```

**Comment by miaout17** [comment] 2019-01-11 21:50
Type 2 is DOUBLE (see also `tensorflow::DataType` definition). 

TensorFlow Lite doesn't support double type now. The easiest way is modify your graph and use float instead. 

I'm closing this ticket as this is working as intended. Please file a feature request if you think double is required for your use case. Then we'll prioritize accordingly. Thanks!

**Closed by miaout17** 2019-01-11 21:50 UTC
Labels: comp:lite

**Comment by anilsathyan7** [comment] 2019-11-19 10:49
Hey i'am facing similar problem with tflite conversion of a  keras model(plain keras not tf.keras) with Input layer type float16 in TF 1.15.0. 

` I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 19
F tensorflow/lite/toco/import_tensorflow.cc:2679] Check failed: status.ok() Unexpected value for attribute 'T'. Expected 'DT_FLOAT'
Aborted (core dumped)`

Is float16 placeholder not still supported, even though other operators are supported?
