### ISSUE TITLE
The unexpected training behavior if read data from tf.record file

### ISSUE THREAD

**Issue by congchan** [tensorflow/tensorflow#27777] opened 2019-04-12 07:14 UTC
To save time I skip writing data into the tf.record files. Instead data is read from tf.record files created in other training experiments (from the same source raw data). But training step marked as finished much earlier than the requested steps. This problem will not happen if I write the rf.record from scratch.

Noted that the training data are basically the same, it is possibly caused by some inner training mechanism in tensorflow data management that I have not noticed. 

**Code to reproduce the issue**
Here I define the model with 
```python
num_train_steps = 200000
model_fn_builder(
      ...
      num_train_steps=num_train_steps,
)
```
```python
train_file = os.path.join(FLAGS.output_dir, "train.tf_record")
train_input_fn = file_based_input_fn_builder(
        input_file=train_file,
       )
```
the training is marked as finished at, say step `1008`. 

If I rewrite the tf.record again, the training step will run as expected.
```python
writer = tf.python_io.TFRecordWriter(output_file)
writer.write(tf_example.SerializeToString())
...

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.11
- Python version: py3.6

**Comment by achandraa** [comment] 2019-04-17 12:22
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-04-23 14:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-23 14:16 UTC
Labels: comp:data, type:support
