### ISSUE TITLE
Error freezing saved model if it contains a tf.keras.layer.BatchNormalisation layer

### ISSUE THREAD

**Issue by geometrikal** [tensorflow/tensorflow#31331] opened 2019-08-05 11:53 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 1903
- TensorFlow installed from: pip
- TensorFlow version: 1.14.0
- Python version: 3.7.3
- GPU model and memory: RTX 2080 Ti 

**Problem**

To make a frozen graph, I first create a saved model using `tf.saved_model.simple_save` and then freeze it using `tensorflow.python.tools.freeze_graph.freeze_graph`.

If a model contains some `tf.keras.layers.BatchNormalisation` layers, freezing will fail in TF 1.14.0 with:

`ValueError: Tensor name 'batch_normalization/cond/ReadVariableOp/Switch:1' is invalid.`

TF 1.13.1 does not give an error

**Code to reproduce the issue**

```
import tensorflow as tf
import tensorflow.keras.backend as K
import os
import datetime
from tensorflow.python.tools import freeze_graph
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input, Activation, BatchNormalization
from tensorflow.keras.models import Model

inputs = Input(shape=(128, 128, 1))
x = Conv2D(4, (3, 3))(inputs)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = Flatten()(x)
x = Dense(5, activation='softmax')(x)
model = Model(inputs, x, name='test')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

K.set_learning_phase(0)
save_dir = "./tmp_{:%Y-%m-%d_%H%M%S}".format(datetime.datetime.now())
tf.saved_model.simple_save(K.get_session(),
                           save_dir,
                           inputs={"input": model.inputs[0]},
                           outputs={"output": model.outputs[0]})

freeze_graph.freeze_graph(None,
                          None,
                          None,
                          None,
                          model.outputs[0].op.name,
                          None,
                          None,
                          os.path.join(save_dir, "frozen_model.pb"),
                          False,
                          "",
                          input_saved_model_dir=save_dir)
```

**Update:**

Seems to be a problem in `graph_util_impl.py`, in particular https://github.com/tensorflow/tensorflow/commit/0f486fc67070ba888204741c404a55a5f1a41fbc#diff-2d2827fd48cee6884e3587c901ad6952

@gargn 

If I change this file back to its 1.13 version there is no more error.

**Update 2:**

I put `K.set_learning_phase(0)` before creating the model, then it works. I don't know what effect this has though? Does it just turn off batch normalisation altogether?

**Update 3**

Final remarks:
- Putting `K.set_learning_phase(0)` before creating the model will let it save, however the Batch Normalisation layer doesn't seem to do anything (updating turned off?) so it is not a solution.
- Changing `graph_util_impl.py` to its 1.13.1 version will let it save without error, however there will be an error `ValueError: Input 0 of node batch_normalization/cond/ReadVariableOp/Switch was passed float from batch_normalization/gamma:0 incompatible with expected resource.` when loading the frozen graph from the protobuf.
- The workaround is to save the model weights, clear the session (so that tensor names are not different because of having two graphs), set learning phase to 0, recreate the model, load the weights, and then freeze (example code in my comment [below](https://github.com/tensorflow/tensorflow/issues/31331#issuecomment-518655879))

**Comment by wenshuangwang** [comment] 2019-08-06 02:32
Same problem here with tensorflow-gpu 1.14.0, Ubuntu 16.04, Python 3.5.2.

**Comment by geometrikal** [comment] 2019-08-06 04:51
@wenshuangwang I found if I put `K.set_learning_phase(0)` before constructing the model, then it works. But I don't know how this affects training?!

**Comment by wenshuangwang** [comment] 2019-08-06 08:34
@geometrikal Thank you very much, it works for me as well. I think it's ok if training and freezing separately.
I know the second way, but I must use tf.keras to use tensorflow_model_optimization.sparsity.

**Comment by geometrikal** [comment] 2019-08-06 09:44
@wenshuangwang Actually, I think putting `K.set_learning_phase(0)` before loading the model stops the batch normalisation layer from updating. I can tell a difference - I get worse accuracy (same as when not using batch normalisation) and the accuracy vs epochs graph looks different.

**Comment by geometrikal** [comment] 2019-08-06 12:52
@wenshuangwang I finally found a workaround:

1. Create the model using a function (do *not* use `K.set_learning_phase(0)`):
```
def create_model():
    inputs = Input(...)
    ...
    return model

model = create_model()
```
2. Train model
3. Save weights: 
`model.save_weights("weights.h5")`
4. Clear session and set learning phase to 0:
```
K.clear_session()
K.set_learning_phase(0)
```
5. Recreate model and load weights:
```
model = create_model()
model.load_weights("weights.h5")
```
6. Freeze as before

I have confirmed this works with no errors for creating the frozen model protobuf. Also there are no errors when loading the model either (using `tf.import_graph_def`), and it is working in my production code (using tensorflow java 1.14)

Here is full working example:

```
import tensorflow as tf
import tensorflow.keras.backend as K
import os
import datetime
from tensorflow.python.tools import freeze_graph
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input, Activation, BatchNormalization, Lambda
from tensorflow.keras.models import Model


def create_model():
    inputs = Input(shape=(128, 128, 1))
    x = Conv2D(4, (3, 3))(inputs)
    x = BatchNormalization()(x)
    # x = Lambda((lambda x: tf.layers.batch_normalization(x)))(x)
    x = Activation('relu')(x)
    x = Flatten()(x)
    x = Dense(5, activation='softmax')(x)
    model = Model(inputs, x, name='test')
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model


model = create_model()

# Training goes here...

model.save_weights("weights.h5")

K.clear_session()
K.set_learning_phase(0)

model = create_model()
model.load_weights("weights.h5")

save_dir = "./tmp_{:%Y-%m-%d_%H%M%S}".format(datetime.datetime.now())
tf.saved_model.simple_save(K.get_session(),
                           save_dir,
                           inputs={"input": model.inputs[0]},
                           outputs={"output": model.outputs[0]})

freeze_graph.freeze_graph(None,
                          None,
                          None,
                          None,
                          model.outputs[0].op.name,
                          None,
                          None,
                          os.path.join(save_dir, "frozen_model.pb"),
                          False,
                          "",
                          input_saved_model_dir=save_dir)
```

**Comment by wenshuangwang** [comment] 2019-08-07 02:29
@geometrikal Yes, this is what I said to train and freeze the network separately. Thank you for explaining patiently.

**Comment by jvishnuvardhan** [comment] 2019-08-08 00:28
@geometrikal Is this resolved by the suggestion of @wenshuangwang . Can we close the issue? Thanks!

**Comment by geometrikal** [comment] 2019-08-08 01:21
@jvishnuvardhan I think this is a bug and should be left open.

The bug does not occur in normal keras, and it is clunky to have to create a copy of the graph and transfer the weights across just because you have a batch normalisation layer in there.

In TF 1.13.1 the models would be frozen without error, but this leads to an error when loading the frozen model: #3628

**Comment by gargn** [comment] 2019-08-08 01:24
I tested the code in the latest `tf-nightly` (`1.15.0.dev20190807`) and the model froze without issue.

**Comment by geometrikal** [comment] 2019-08-08 01:51
@gargn I tested as well to confirm. It does save without issue, but when loading the frozen graph there is a new error: `ValueError: Node 'batch_normalization/cond/ReadVariableOp/Switch' has an _output_shapes attribute inconsistent with the GraphDef for output #0: Shapes must be equal rank, but are 1 and 0`

Test code:
```
import tensorflow as tf
from tensorflow.python.platform import gfile
import tensorflow.keras.backend as K

source = "./freeze_test/frozen_model.pb"

session = K.get_session()
with gfile.Open(source, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    session.graph.as_default()
    tf.import_graph_def(graph_def, name='')
```

**Comment by jvishnuvardhan** [comment] 2019-08-15 17:08
@geometrikal As @gargn mentioned the original issue was resolved in `!pip install tf-nightly-gpu`. Please close the issue and open a new issue for the `loading graph` if it was not already resolved. I think `loading graph` was also resolved as I could not reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/b3a72cb75dd9b2ed5e05d260ad0247b0/tf_31331_freezing_savedmodel.ipynb). Thanks!

**Comment by geometrikal** [comment] 2019-08-16 00:30
@jvishnuvardhan `loading_graph` is not resolved - the code you are using in your gist is my workaround for the problem.
I have opened a new issue #31668 with a bigger scope to cover the general issue of freezing and loading models with batch normalization.

**Comment by gargn** [comment] 2019-08-20 16:57
This should work on the latest nightly.

**Closed by gargn** 2019-08-20 16:57 UTC
Labels: TF 1.14, comp:keras, stat:awaiting tensorflower, type:bug

**Comment by randallsalvares** [comment] 2020-12-17 07:20
import backend from tf.keras not simply keras, shown below:
from tensorflow.keras import backend as K

**Comment by mahaoyanghb** [comment] 2021-09-08 15:33
> import backend from tf.keras not simply keras, shown below:
> from tensorflow.keras import backend as K

awesome!
it works
