### ISSUE TITLE
Failed to Load the Native Tensorflow runtime

### ISSUE THREAD

**Issue by ParekhVivek09** [tensorflow/tensorflow#20049] opened 2018-06-15 08:37 UTC
I am using WINDOWS10 64bit, Anaconda 4.5.4 and PyCharm as an IDE. I have NVIDIA Quadro4000m GPU installed. Now I want to use Keras-GPU with tensorflow as backend and I am getting the following error?
One more thing I could not create environment with tensorflow versionb 1.8.0 with keras-gpu all versions as it shows unsatisfiable error due to conflicts in dependency. It is related to mkl file version  I dont know how to fix the dependancy.

Thanks

Using TensorFlow backend.
```
Traceback (most recent call last):
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/pav7rt/PycharmProjects/CADImage_Classification/CAD_Classification.py", line 5, in <module>
    import keras
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\keras\backend\__init__.py", line 84, in <module>
    from .tensorflow_backend import *
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
```
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\pav7rt\AppData\Local\Continuum\anaconda3\envs\CADImageClassification\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment] 2018-06-15 18:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment] 2018-06-15 18:42
Technically, I think this should go to the keras issues.

Your problem is probably that you don't have the right libraries installed. Please follow the installation procedure carefully. You can use the windows dependency walker to see what libraries you're missing. Typically it's a problem with the CUDA version.

**Comment by ParekhVivek09** [comment] 2018-06-15 18:49
I am using c onda environment version 3.5.2
Gpu capacity 6gb nvidiaqudro4000m 
Tensorflow installed from Fonda
Cudnn 8.0 installed from vonda
Though I wanted upgrade but could not allowed because conflict error I mentioned 
In my post
Bazel I dont know 
OS windows 10 enterprise version
Intel Lenovo core i5 processor

**Comment by ParekhVivek09** [comment] 2018-06-15 18:51
I feel this problem is related to anaconda virtual environment conflict error 
As I am not able to install specific version in it because of conflict error I mentioned

**Comment by drpngx** [comment] 2018-06-15 19:00
Right, you are probably correct. What was the exact message about mkl?

/CC @tatianashp

**Comment by ParekhVivek09** [comment] 2018-06-15 19:18
Error: Unsatisfiable package specifications.

.mkl versions for two different libraries are conflicting. Check Conda info <package name > for the dependency. 

When I check I found dependance in deadlock so it's not possible but can you help in this case

**Comment by tensorflowbutler** [comment] 2018-06-30 18:34
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-15 18:35
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-30 18:50
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by ymodak** [comment] 2018-10-24 21:31
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!

**Closed by ymodak** 2018-10-24 21:31 UTC
Labels: stat:community support, type:build/install
