### ISSUE TITLE
Can't build tensorflow master with CUDA & MPI enabled

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#25638] opened 2019-02-09 12:09 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.5.2
- Bazel version (if compiling from source): 0.22.0 (tried with 0.21.0, 0.20.0, 0.19.0)
- GCC/Compiler version (if compiling from source): 5.4.0
- Nvidia Driver: 410.48
- CUDA/cuDNN version: 10.0.130 / 7.4.2
- GPU model and memory: Tesla V100

I use nvidia-docker/docker to build and test the master branch of tensorflow. Since a few days, I consistently get the same error over and over.

```shell
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc: In lambda function:
tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:125:49: error: no matching function for call to 'tensorflow::TensorResponse::InitPartial(const tensorflow::RecvTensorResponse&)'
           tr.InitPartial(mpi_response.response());
                                                 ^
In file included from tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:31:0:
./tensorflow/core/distributed_runtime/tensor_coding.h:79:8: note: candidate: void tensorflow::TensorResponse::InitPartial(const tensorflow::RecvTensorResponse&, const tensorflow::AllocationAttributes&)
   void InitPartial(const RecvTensorResponse& response,
        ^
./tensorflow/core/distributed_runtime/tensor_coding.h:79:8: note:   candidate expects 2 arguments, 1 provided
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/contrib/mpi/mpi_utils.h:25,
                 from ./tensorflow/contrib/mpi/mpi_rendezvous_mgr.h:34,
                 from tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc:18:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:467:54:   required from here
./tensorflow/core/util/tensor_format.h:441:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
                             ^
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:441:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 555.689s, Critical Path: 278.37s
INFO: 7384 processes: 7384 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

I build using the following:

```dockerfile
ENV LD_LIBRARY_PATH='/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64/:/usr/local/cuda/extras/CUPTI/lib64' \
    BLAS_INCLUDE='/usr/local/cuda/targets/x86_64-linux/include' \
    BLAS_LIB='/usr/local/cuda/targets/x86_64-linux/lib' \
    CPLUS_INCLUDE_PATH='/usr/local/cuda/$CPLUS_INCLUDE_PATH' \
    CUDA_TOOLKIT_PATH="/usr/local/cuda" \
    GCC_HOST_COMPILER_PATH="/usr/bin/gcc" \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.0,6.1,7.0,7.5 \
    TF_CUDA_VERSION=10.0 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=2 \
    TF_ENABLE_XLA=1 \
    TF_NEED_CUDA=1 \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_HDFS=1 \
    TF_NEED_MPI=1 \
    TF_NEED_VERBS=0 \
    TF_NEED_OPENCL=0 \
    TF_NEED_GDR=0 \
    TF_NEED_GCP=0 \
    TF_NEED_S3=0 \
    TF_NEED_TENSORRT=0

# Get the TF branch for later build
RUN rm -rf /opt/tensorflow && \
    git clone --branch=$TF_BUILD_BRANCH --depth=1 $TF_REPO /opt/tensorflow && \
    cd /opt/tensorflow && \
    rm -f /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf && \
    echo "/usr/local/cuda/targets/x86_64-linux/lib/stubs" > /etc/ld.so.conf.d/cuda-stubs.conf && \
    bazel clean && \
    ldconfig && \
    tensorflow/tools/ci_build/builds/configured GPU \
    bazel build -c opt --copt=-mavx --config=cuda --verbose_failures \
        --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
        --action_env=LD_LIBRARY_PATH=${LD_LIBRARY_PATH} \
        tensorflow/tools/pip_package:build_pip_package && \
    mkdir /opt/tensorflow/pip_pkg && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /opt/tensorflow/pip_pkg --gpu && \
    pip --no-cache-dir install --upgrade /opt/tensorflow/pip_pkg/tensorflow_*.whl && \
    rm -f /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    rm -rf /root/.cache && \
    rm -rf opt/tensorflow/pip_pkg
```

My script is perfectly working for the branches:  `r1.12` and `r1.13`. and fails on `master`. I guess that you have updated something, because it seems that your CI builds are still passing.

**Comment by SippieCup** [comment] 2019-02-09 17:32
I had to downgrade to bazel 18.1 in order to get it to build

**Comment by DEKHTIARJonathan** [comment] 2019-02-09 17:40
There is no chance you can build `master` branch with Bazel 0.18.1

```
Cloning into '/opt/tensorflow'...
Extracting Bazel installation...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.cache/bazel/_bazel_root/install/cdf71f2489ca9ccb60f7831c47fd37f1/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
/opt/tensorflow /opt/tensorflow
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.cache/bazel/_bazel_root/install/cdf71f2489ca9ccb60f7831c47fd37f1/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.18.1 installed.
Please upgrade your bazel installation to version 0.19.0 or higher to build TensorFlow!
```

**Comment by JesseFarebro** [comment] 2019-02-10 01:20
Seems to be caused by [this](https://github.com/tensorflow/tensorflow/commit/2dcb0a07c88ce34196d8fe55ab8f415e537e1484#diff-e7a427f0a288fee9dca5408b8d4f5ef6). `TensorResponse::InitPartial` now takes `AllocationAttributes`. If you pass in the default `AllocationAttributes` from `tensorflow/core/framework/allocator.h` it ends up compiling fine (I compiled `r1.96`).

I think @poxvoculi would have a better idea of how he wants to proceed. I'm not sure if the default `AllocationAttributes` are sensible (e.g., do we want to log failures? retry failures?). I'm also not sure if he would want a PR to `tensorflow` or `tensorflow/networking` now that contrib is going away.

Note that all the CI builds don't enable MPI hence why they are succeeding. You could either disable MPI or apply the patch I'll post below. Hopefully, this helps.

<details> 
<summary>
mpi.patch
</summary>

```patch
diff --git a/tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc b/tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc
index b9967fe76d..67a76c5856 100644
--- a/tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc
+++ b/tensorflow/contrib/mpi/mpi_rendezvous_mgr.cc
@@ -24,6 +24,7 @@ limitations under the License.
 #include <utility>
 #include <vector>
 
+#include "tensorflow/core/framework/allocator.h"
 #include "tensorflow/core/common_runtime/device.h"
 #include "tensorflow/core/common_runtime/device_mgr.h"
 #include "tensorflow/core/common_runtime/gpu/gpu_util.h"
@@ -122,7 +123,7 @@ void MPIRemoteRendezvous::RecvFromRemoteAsync(
         } else {
           TensorResponse tr;
           tr.InitAlloc(dst_device, recv_args.alloc_attrs);
-          tr.InitPartial(mpi_response.response());
+          tr.InitPartial(mpi_response.response(), AllocationAttributes());
           const size_t nBytes = tr.tensor().TotalBytes();
           void* data = const_cast<void*>(DMAHelper::base(&tr.tensor()));
           MPI_Status status;
```
</details>

**Comment by byronyi** [comment] 2019-03-06 04:44
@jbedorf mind to take a look here?

**Comment by jbedorf** [comment] 2019-03-07 04:35
The patch from Jesse seems to be the correct way to solve it. I'll submit the patch next week.

**Comment by jbedorf** [comment] 2019-03-25 15:09
This has been fixed in: https://github.com/tensorflow/tensorflow/pull/26720

**Comment by jvishnuvardhan** [comment] 2019-03-25 16:13
I am closing the issue as it was resolved. Please open a new issue if the bug persists in future. Thanks!

**Closed by jvishnuvardhan** 2019-03-25 16:13 UTC
Labels: subtype: ubuntu/linux, subtype:bazel, type:build/install
