### ISSUE TITLE
Error with TFlite hello world example on ESP-EYE

### ISSUE THREAD

**Issue by rajeevdm** [tensorflow/tensorflow#41931] opened 2020-07-31 09:36 UTC
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.4.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP-EYE

**Describe the problem**

I am trying to setup the ESP-EYE for TFlite. I have been able to set up the ESP-EYE for basic setup as per: https://docs.espressif.com/projects/esp-idf/en/stable/get-started/index.html. I am also able to use the AWS IoT example https://github.com/espressif/esp-aws-iot/tree/master/examples.

For TFlite, I am trying out the example for ESP-EYE at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/README.md

When I try to compile this per the instructions above for ESP-EYE, I am getting a compiler error:

cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: all warnings being treated as errors

**Please provide the exact sequence of commands/steps when you ran into the problem**

Per the steps at the TFlite link above:

Generate the examples The example project can be generated with the following command:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project

Building the example Go the the example project directory
cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf

Then build with idf.py

idf.py build
I get this error repeatedly:

cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: all warnings being treated as errors

The error does go away if I remove -Werror in the below line in components/tfmicro/CMakeLists.txt:

target_compile_options(${COMPONENT_LIB} PRIVATE $<$<COMPILE_LANGUAGE:CXX>: -std=c++11 -DTF_LITE_STATIC_MEMORY -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -DNDEBUG -O3 -Wno-return-type -Wno-strict-aliasing -Wno-ignored-qualifiers -Wno-return-type -Wno-strict-aliasing -Wno-ignored-qualifiers -Wno-return-type -Wno-strict-aliasing -Wno-return-type -Wno-strict-aliasing >)

But the image when flashed, does not work. It keeps crashing with a register dump.

Any suggestions for this issue?

**Comment by Saduf2019** [comment] 2020-07-31 16:55
@rajeevdm 
Please provide simple stand alone code for us to replicate the issue faced or share a colab gist with the error for us to analyse the issue.

**Comment by rajeevdm** [comment] 2020-07-31 23:25
Thanks for the response. 

Here are the steps to replicate. 

System information

Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): source
Tensorflow version (commit SHA if source): 2.4.0
Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP-EYE (the one mentioned in https://www.tensorflow.org/lite/microcontrollers/get_started)

Basic setup of ESP-EYE documented here: https://docs.espressif.com/projects/esp-idf/en/v4.0.1/get-started/index.html (I have used the v4.0.1, latest stable release). I have followed the steps exactly as listed in the link there, except that some packages had to be manually installed on the host system. Here are the steps followed:

Basic python and git install steps:
1. sudo apt-get install python3-pip
2. sudo apt-get install git
3. mkdir esp
4. cd ~/esp
5. git clone -b v4.0.1 --recursive https://github.com/espressif/esp-idf.git
6. cd ~/esp/esp-idf
7. ./install.sh
This step, for some reason, does not install all required packages automatically. I had to manually install the following:
8. sudo apt-get install cmake bison flex gperf libncurses5-dev libncursesw5-dev
9. . $HOME/esp/esp-idf/export.sh (this step to be done in any shell/terminal that will use ESP IDF)

Start a new hello_world project
10. cd ~/esp
11. cp -r $IDF_PATH/examples/get-started/hello_world .
12. cd ~/esp/hello_world
13. idf.py menuconfig
14. idf.py build
15. idf.py -p PORT [-b BAUD] flash
16. idf.py -p /dev/ttyUSB0 monitor

This completes basic setup of ESP-EYE IDF and sample hello_world project from ESP. 

Now, getting to TFlite: I am trying out the example for ESP-EYE at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/README.md

Steps followed are listed here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/README.md#deploy-to-esp32

1. cd esp/examples
2. git clone https://github.com/tensorflow/tensorflow.git
3. cd tensorflow
4. make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
5. cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf
6. . $HOME/esp/esp-idf/export.sh
7. idf.py build

Error:
rajeev@ubuntu:~/esp/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf$ idf.py build
Checking Python dependencies...
Python requirements from /home/rajeev/esp/esp-idf/requirements.txt are satisfied.
Executing action: all (aliases: build)
Running make in directory /home/rajeev/esp/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/build
Executing "make -j 6 all"...
[  0%] Built target _project_elf_src
Partition table binary generated. Contents:
[  0%] Built target esp32_linker_script
*******************************************************************************
[  0%] Built target __idf_app_trace
[  0%] Built target __idf_cxx
# Espressif ESP32 Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,24K,
phy_init,data,phy,0xf000,4K,
factory,app,factory,0x10000,1M,
[  1%] Built target __idf_newlib
*******************************************************************************
[  2%] Built target partition_table
[  2%] Built target __idf_vfs
[  2%] Performing build step for 'bootloader'
[  4%] Built target __idf_freertos
[  1%] Built target _project_elf_src
[  4%] Built target __idf_log
[  4%] Built target __idf_heap
[  4%] Built target __idf_log
[ 12%] Built target __idf_xtensa
[  7%] Built target __idf_soc
[ 50%] Built target __idf_soc
[  7%] Built target __idf_esp_rom
[ 53%] Built target __idf_micro-ecc
[  8%] Built target __idf_esp_common
[ 79%] Built target __idf_bootloader_support
[  9%] Built target __idf_xtensa
[ 87%] Built target __idf_efuse
[ 90%] Built target __idf_spi_flash
[ 12%] Built target __idf_esp32
[ 93%] Built target __idf_main
[ 98%] Built target bootloader.elf
[ 13%] Built target __idf_espcoredump
[100%] Built target gen_project_binary
[ 14%] Built target __idf_pthread
[100%] Built target app
[ 15%] Built target __idf_esp_event
[ 15%] No install step for 'bootloader'
[ 15%] Completed 'bootloader'
[ 15%] Built target __idf_tcpip_adapter
[ 16%] Built target bootloader
[ 25%] Built target __idf_lwip
[ 26%] Built target __idf_esp_eth
[ 27%] Built target __idf_esp_wifi
[ 28%] Built target __idf_nvs_flash
[ 30%] Built target __idf_spi_flash
[ 30%] Built target __idf_app_update
[ 31%] Built target __idf_bootloader_support
[ 31%] Built target __idf_efuse
[ 41%] Built target __idf_wpa_supplicant
[ 42%] Built target mbedtls
[ 50%] Built target mbedcrypto
[ 52%] Built target mbedx509
[ 55%] Built target __idf_driver
[ 55%] Built target __idf_esp_ringbuf
[ 56%] Built target __idf_esp_adc_cal
[ 56%] Built target __idf_console
[ 59%] Built target __idf_nghttp
[ 59%] Building CXX object esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/simple_memory_allocator.cc.obj
[ 60%] Built target __idf_protobuf-c
[ 61%] Built target __idf_asio
[ 62%] Built target __idf_coap
[ 62%] Building CXX object esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/all_ops_resolver.cc.obj
[ 62%] Building CXX object esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/micro_error_reporter.cc.obj
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
[ 63%] Built target __idf_esp_gdbstub
[ 63%] Built target __idf_expat
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
[ 63%] Built target __idf_mdns
[ 63%] Building CXX object esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/memory_helpers.cc.obj
cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: all warnings being treated as errors
esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/build.make:94: recipe for target 'esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/micro_error_reporter.cc.obj' failed
make[2]: *** [esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/micro_error_reporter.cc.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 64%] Built target __idf_wear_levelling
[ 64%] Built target __idf_sdmmc
[ 67%] Built target __idf_freemodbus
[ 68%] Built target __idf_jsmn
[ 81%] Built target __idf_libsodium
[ 81%] Built target __idf_json
[ 82%] Built target __idf_openssl
[ 83%] Built target __idf_spiffs
[ 83%] Built target __idf_ulp
[ 84%] Built target __idf_unity
[ 85%] Built target __idf_esp_http_server
[ 85%] Built target __idf_esp-tls
[ 87%] Built target __idf_fatfs
[ 88%] Built target __idf_protocomm
[ 89%] Built target __idf_tcp_transport
[ 90%] Built target __idf_wifi_provisioning
[ 91%] Built target __idf_esp_local_ctrl
[ 91%] Built target __idf_esp_websocket_client
[ 91%] Built target __idf_esp_http_client
[ 92%] Built target __idf_mqtt
[ 92%] Built target __idf_esp_https_ota
cc1plus: all warnings being treated as errors
esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/build.make:81: recipe for target 'esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/simple_memory_allocator.cc.obj' failed
make[2]: *** [esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/simple_memory_allocator.cc.obj] Error 1
cc1plus: all warnings being treated as errors
esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/build.make:120: recipe for target 'esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/memory_helpers.cc.obj' failed
make[2]: *** [esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/memory_helpers.cc.obj] Error 1
cc1plus: all warnings being treated as errors
esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/build.make:107: recipe for target 'esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/all_ops_resolver.cc.obj' failed
make[2]: *** [esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/tensorflow/lite/micro/all_ops_resolver.cc.obj] Error 1
CMakeFiles/Makefile2:4097: recipe for target 'esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/all' failed
make[1]: *** [esp-idf/tfmicro/CMakeFiles/__idf_tfmicro.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
make failed with exit code 2

The error goes away if I remove -Werror in the below line in components/tfmicro/CMakeLists.txt:

target_compile_options(${COMPONENT_LIB} PRIVATE $<$<COMPILE_LANGUAGE:CXX>: -std=c++11 -DTF_LITE_STATIC_MEMORY -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -DNDEBUG -O3 -Wno-return-type -Wno-strict-aliasing -Wno-ignored-qualifiers -Wno-return-type -Wno-strict-aliasing -Wno-ignored-qualifiers -Wno-return-type -Wno-strict-aliasing -Wno-return-type -Wno-strict-aliasing >)

But the image when flashed, does not work. It keeps crashing with a register dump. Pls let me know if you want to see the register dump as well.

Thanks a lot.

**Comment by melon675** [comment] 2020-08-03 13:03
Also have this problem with building hello_world for ESP32 board. 
If I deleted "-std=c11" flag from CMakeList in tfmicro directory building goes well, but then I got exception:
"Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled."
Exeption happens when line "input->data.f[0] = x_val;" from main_funstions.cc is executed. Looks like I'm trying to save data out of flash memory.

**Comment by rajeevdm** [comment] 2020-08-03 23:49
Yes, same error if I either delete "-std=c11" or "-Werror" (to not treat warnings as errors). From the TFlite documentation, it seems like C++11 standard is quite a fundamental requirement (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro - Requirements section). So we cannot remove "std=c++11" I think.

**Comment by umgefahren** [comment] 2020-08-04 11:44
There is currently no fix other then to reverse to the previous Tensorflow version 2.2.0. That worked for me, it seems like an error that the dev team has to fix and results from a minor change. It's probably not your fault.

**Comment by advaitjain** [comment] 2020-08-04 17:03
adding @petewarden for issues related to the espressif integration.

**Comment by rajeevdm** [comment] 2020-08-05 01:29
> There is currently no fix other then to reverse to the previous Tensorflow version 2.2.0. That worked for me, it seems like an error that the dev team has to fix and results from a minor change. It's probably not your fault.

I tried checking out r2.2 with this:
git clone https://github.com/tensorflow/tensorflow tensorflow -b r2.2

Got this error:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp  
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz" "02c64880acb89dbd57eebacfd67200d8" tensorflow/lite/micro/tools/make/downloads/flatbuffers  
downloading https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.11.0.tar.gz
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_int8_grayscale_2020_01_13.zip" "8a7d2c70325f53136faea6dde517b8cc" tensorflow/lite/micro/tools/make/downloads/person_model_int8  
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_int8_grayscale_2020_01_13.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/mborgerding/kissfft/archive/v130.zip" "438ba1fef5783cc5f5f201395cc477ca" tensorflow/lite/micro/tools/make/downloads/kissfft patch_kissfft 
downloading https://github.com/mborgerding/kissfft/archive/v130.zip
Finished patching kissfft
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2019_11_21.zip" "fe2934bd0788f1dcc7af3f0a954542ab" tensorflow/lite/micro/tools/make/downloads/person_model_grayscale  
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2019_11_21.zip
make: *** No rule to make target 'tensorflow/lite/micro/examples/hello_world/esp/sdkconfig.defaults', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/sdkconfig.defaults'.  Stop.

I will try going back one more version to 2.1

**Comment by rajeevdm** [comment] 2020-08-05 02:13
So, in summary:

Tensorflow r2.1 does not have a micro directory. So quite likely support for microcontrollers was added later. 

With r2.2, I get the error during make:
make: *** No rule to make target 'tensorflow/lite/micro/examples/hello_world/esp/sdkconfig.defaults', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/sdkconfig.defaults'. Stop.

With r2.3, we get the issue with "-std=c++11" described earlier. 

@umgefahren - did you face any issues with compiling r2.2?

**Comment by uthantvicentin** [comment] 2020-08-05 02:30
r2.2 worked for me.
[https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0](url)

**Comment by rajeevdm** [comment] 2020-08-05 02:31
Ok, got it working with TF r2.2.

For the error:
make: *** No rule to make target 'tensorflow/lite/micro/examples/hello_world/esp/sdkconfig.defaults', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/sdkconfig.defaults'. Stop.

I just did:
touch tensorflow/lite/micro/examples/hello_world/esp/sdkconfig.defaults

Then
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf
idf.py build
idf.py -p /dev/ttyUSB0 flash
idf.py monitor

That seems to work, I see continuous output like this:
x_value: 1.2566366*2^-2, y_value: 1.2133837*2^-2
x_value: 1.5707957*2^0, y_value: 1.9224760*2^-1
x_value: 1.8849551*2^0, y_value: 1.8043820*2^-1
x_value: 1.995567*2^1, y_value: 1.5224055*2^-1
x_value: 1.2566366*2^1, y_value: 1.1094990*2^-1
x_value: 1.4137159*2^1, y_value: 1.374219*2^-2
x_value: 1.5707957*2^1, y_value: -1.4249528*2^-5
x_value: 1.7278753*2^1, y_value: -1.4295994*2^-2
x_value: 1.8849551*2^1, y_value: -1.2867725*2^-1
x_value: 1.210171*2^2, y_value: -1.7542459*2^-1
x_value: 1.995567*2^2, y_value: -1.9749510*2^-1

TFlite team - It will be good to update the build instructions and/or put in an errata/known issues / fixes.

Will continue to other examples now.

**Comment by njeffrie** [comment] 2020-08-06 20:54
Upon closer inspection, it looks like we have two errors related to build flags when I follow the repro steps.
1. We are enabling strict pointer aliasing with -Werror=strict-aliasing, which fails for some of our core files (specifically tensorflow/lite/micro/micro_string.h, I will look into fixing this aliasing error). We should be able to turn off strict aliasing with a compiler flag.
2. We are building with -std=c11 which is invalid for c++. This should be a relatively simple compiler flag fix as well.

Do those errors match with what you're seeing? I do see micro_allocator.cc, micro_interpreter.cc, etc. failing, but I think those fail because they are cut short by the micro_string.cc error on a different thread.

Pete is much more familiar with the Makefile and relevant compiler flags, so he may be able to weigh in with more specific fixes when he is available to do so.

**Comment by rajeevdm** [comment] 2020-08-07 02:04
Thanks Nat. 

Please let us know if you make progress with the issues on the latest branch. I think it will be important as more hardware start supporting Tflite and also MLPerf.org starts publishing TinyML benchmarks, which is already in the works. 

For now, I will stick to R2.2 on my ESP-EYE device. 

Regards
Rajeev

**Comment by mr-goldhands** [comment] 2020-08-11 15:31
To not clone similar bug reports...
**Unable to build "Hello World" for ESP32**
I have received a similar error just trying to compile the "Hello World" example.

**Software environment to reproduce:**
- TF sources commit hash: aee9ca5dbd
- ESP-IDF v4.0.1

**Steps to reproduce:**
1. Clone TF sources repo
2. make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
3. cd tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf
4. idf.py build

**Most informative part of error message:**

`cc1plus: error: command line option '-std=c11' is valid for C/ObjC but not for C++ [-Werror]
../components/tfmicro/tensorflow/lite/micro/micro_string.cc: In function 'char* {anonymous}::FastFloatToBufferLeft(float, char*)':
../components/tfmicro/tensorflow/lite/micro/micro_string.cc:128:23: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   const uint32_t u = *reinterpret_cast<uint32_t*>(&f);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
`

**Comment by mr-goldhands** [comment] 2020-08-18 11:03
I have ried to build Hello World with TF sources SHA 387414f.
Now compilation is successful but the application always cyclically rebooting.
Logs attached.
[Cyclically_rebooting__Hello_World__for_ESP32.txt](https://github.com/tensorflow/tensorflow/files/5089943/Cyclically_rebooting__Hello_World__for_ESP32.txt)

**Comment by AdityaHPatwardhan** [comment] 2020-10-01 06:28
This issue has been fixed with [this PR](https://github.com/tensorflow/tensorflow/pull/42275), Please check. If the problem is solved, you may close the issue.
Thank you.

**Comment by tensorflowbutler** [comment] 2021-06-10 18:15
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment] 2021-07-15 17:22
@rajeevdm Could you please let us know if this issue has been fixed with this PR. If the problem is solved, you may close the issue.
Thank you.

**Comment by rajeevdm** [comment] 2021-07-16 11:18
Hi team

Thanks a lot. Yes this can be closed now. Sorry for the delay in my
response.

Rajeev

**Comment by sushreebarsa** [comment] 2021-07-18 11:38
@rajeevdm thank you for your response ,closing this issue

**Closed by sushreebarsa** 2021-07-18 11:38 UTC
Labels: TF 2.4, comp:lite, comp:micro, comp:micro:espressif, type:bug
