### ISSUE TITLE
2019-03-05 12:24:39.106 18565-18583/org.tensorflow.lite.demo W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-2147483648

### ISSUE THREAD

**Issue by aravindchaluvadi** [tensorflow/tensorflow#26347] opened 2019-03-05 06:59 UTC
When i run the tfLite demo app in my mobile I am getting the following error:

2019-03-05 12:24:39.106 18565-18583/org.tensorflow.lite.demo W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-2147483648

**Comment by ymodak** [comment] 2019-03-07 00:43
Please provide following information. Thanks!
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-03-11 17:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-11 17:03 UTC
Labels: comp:lite, stat:awaiting response

**Comment by Ehtasha** [comment] 2020-02-26 10:42
@aravindchaluvadi 
I'm also facing this issue while running custom model with the app.

Have you resolve this ?
