### ISSUE TITLE
 ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda'

### ISSUE THREAD

**Issue by StatML** [tensorflow/tensorflow#11991] opened 2017-08-03 06:04 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**: 0.5.3
- **CUDA/cuDNN version**: 6.0.21
- **GPU model and memory**:
- **Exact command to reproduce**: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem

I know someone had reported the same issue. Their solution is to roll back bazel to 0.5.2. But it does not work on my machine. Does anyone know how to fix this problem without the need of rolling back bazel? Thx!

> tensorflow-git$ sudo bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
> WARNING: ignoring http_proxy in environment.
> .......
> ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 1039
> 		_create_local_cuda_repository(repository_ctx)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
> 		_host_compiler_includes(repository_ctx, cc)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
> 		get_cxx_inc_directories(repository_ctx, cc)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
> 		set(includes_cpp)
> depsets cannot contain mutable items
> WARNING: Target pattern parsing failed.
> ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 1039
> 		_create_local_cuda_repository(repository_ctx)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
> 		_host_compiler_includes(repository_ctx, cc)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
> 		get_cxx_inc_directories(repository_ctx, cc)
> 	File "/home/intel/DevLib/tensorflow-git/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
> 		set(includes_cpp)
> depsets cannot contain mutable items
> INFO: Elapsed time: 4.064s
> FAILED: Build did NOT complete successfully (0 packages loaded)
>     currently loading: tensorflow/tools/pip_package
>

**Comment by balajipandian** [comment] 2017-08-03 16:37
Got this same problem -- You need to downgrade your Bazel version to 0.5.2. There is an unresolved conflict with using 0.5.3

**Comment by poxvoculi** [comment] 2017-08-03 22:42
duplicate of #11859

**Closed by poxvoculi** 2017-08-03 22:42 UTC

**Comment by StatML** [comment] 2017-08-04 00:06
Hi, @poxvoculi I know it is a duplicate of #11859 and I hope there are other solutions which are different from "rolling back bazel". Thanks!

**Comment by StatML** [comment] 2017-08-04 00:25
I am very happy to see this issue had been solved without the need of "rolling back bazel". Thanks!

**Comment by chzhong** [comment] 2017-08-14 04:26
Hi @poxvoculi , I still have this issue with **r1.2** branch or **v1.2.1** tag. 
For reasons I have to use 1.2.x, is there any solution?

**Comment by omarmaree** [comment] 2019-03-21 06:31
hello , i'm trying to build bazel with CPU by this command: 
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
i followed the instructions here as well : https://www.tensorflow.org/install/source_windows , 
the error: 
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Unable to load package for '@local_config_syslibs//:build_defs.bzl': The repository could not be resolved
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Unable to load package for '@local_config_syslibs//:build_defs.bzl': The repository could not be resolved
INFO: Elapsed time: 0.480s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
  

could anyone help me to fix this problem ?! i tried to roll back bezel but it didn't work

**Comment by WuDiDaBinGe** [comment] 2020-06-23 14:56
When I build   tf2.0，I met the  same issue.
i use bazel version is 0.24.1 
tf2.0 request bazel version is :
`_TF_MIN_BAZEL_VERSION = '0.24.1'
_TF_MAX_BAZEL_VERSION = '0.26.1'`

i think my bazel version is right?? 
i want to know other method to solve the issue without   "rolling back bazel"
