### ISSUE TITLE
Python crashes when computing max/min of a complex tensor

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#37446] opened 2020-03-09 14:42 UTC
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1
- Python version: 3.6.8

**Describe the current behavior**
When taking (by mistake) the max value of a tensor with complex dtype, tf crashes python.

**Describe the expected behavior**
Tf should fail gracefully, i.e. throwing an error.

**Standalone code to reproduce the issue** 
```python
import tensorflow as tf
tf.reduce_max(tf.ones((9,), dtype=tf.complex64))
```

**Other info / logs** 
```
2020-03-09 15:40:04.604547: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-03-09 15:40:04.604625: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-09 15:40:04.604723: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (zaccharie-Latitude-7490): /proc/driver/nvidia/version does not exist
2020-03-09 15:40:04.605857: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-09 15:40:04.645752: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112000000 Hz
2020-03-09 15:40:04.647241: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4c32870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-09 15:40:04.647293: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-09 15:40:04.671854: F tensorflow/compiler/xla/literal_util.cc:212] C64 element type has no minimum value
[1]    23558 abort (core dumped)  ipython
```

I tried on machine with and without GPU for the same result.

**Comment by Leslie-Fang** [comment] 2020-03-10 15:48
Hi @zaccharieramzi, I think the input type of tf.complex64 is not support in reduce_max.
Here make a PR to pick out this condition and avoid core_dump.

**Comment by zaccharieramzi** [comment] 2020-03-10 16:02
yes of course, you can't use `reduce_max` on a complex tensor, but I mean there should be a way to fail nicely: hopefully your PR does the job.
What is the new output with this fix?

**Comment by Leslie-Fang** [comment] 2020-03-11 01:32
@zaccharieramzi you will failed to create the max op and see the error message as this:
```
OP_REQUIRES failed at reduction_ops.cc:88 : Invalid argument: Unsupported PrimitiveType of MaxOp: 'C64'
```

**Comment by amahendrakar** [comment] 2020-03-11 08:49
Was able to reproduce the issue with TF-2.1 and TF-nightly. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/2fa295dab88e61fe31881f421504e3ac/37446-tf-nightly.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-12 23:10
@Leslie-Fang Can you please update related doc also? Thanks!

**Comment by Leslie-Fang** [comment] 2020-03-13 00:53
@jvishnuvardhan Thanks for the remind. I think it's already in the doc  https://github.com/tensorflow/tensorflow/blob/78b09356f5c1a17d869a2fbc571bd720b3450d9b/tensorflow/python/ops/math_ops.py#L2409
```
input_tensor: The tensor to reduce. Should have real numeric type.
```

**Comment by zaccharieramzi** [comment] 2020-03-13 09:55
You could add that it raises an exception in the style of https://github.com/tensorflow/tensorflow/blob/78b09356f5c1a17d869a2fbc571bd720b3450d9b/tensorflow/python/ops/math_ops.py#L376-L378

**Comment by Leslie-Fang** [comment] 2020-03-24 00:35
Hi @zaccharieramzi Thanks for the suggestions. I think this PR (https://github.com/tensorflow/tensorflow/pull/37483) has been merged.  Please take a look when feasible.

**Comment by zaccharieramzi** [comment] 2020-03-24 09:55
Ha, I didn't take the time to review the PR, sorry. Had I done it, I would have suggested to do the same also for the `reduce_min` operator which suffers from the same problem (just tested). I am going to change the title of the issue to reflect that the problem is for both operators and leave this open. I can actually even make the PR.

**Comment by Patryk999** [comment] 2020-07-05 00:13
I would like to work on this issue

**Comment by mjkim720** [comment] 2020-07-17 20:56
The same problem occurs for `tf.keras.backend.max` and `tf.keras.backend.min` when passing a complex dtype tensor for the argument `x`.

**Comment by Rprabudeva** [comment] 2020-10-21 15:24
I like to contribute in this project.

**Comment by Rendok** [comment] 2020-11-15 22:41
@jvishnuvardhan, is it feasible to support complex numbers instead? How much work will it take?

**Comment by zaccharieramzi** [comment] 2020-11-16 10:33
@Rendok what would it mean to compute the max/min of a complex tensor?

**Comment by Rendok** [comment] 2020-11-16 10:45
@zaccharieramzi, agree, there is no total order in complex space

**Comment by sachinprasadhs** [comment] 2021-05-25 10:04
Now the issue produces proper error message in both Tensorflow GPU 2.4.1 and Tf Nightly 2.6 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/690f5d93dc63d1f9edf39e6bd34fc63a/untitled7.ipynb).

**Comment by sachinprasadhs** [comment] 2021-05-25 10:05
Closing this issue since the error message is proper now, feel free to reopen the issue.

**Closed by sachinprasadhs** 2021-05-25 10:05 UTC
Labels: TF 2.1, comp:ops, stat:contributions welcome, type:bug
