### ISSUE TITLE
tf.stack on windows gives wrong result

### ISSUE THREAD

**Issue by DanielMorales9** [tensorflow/tensorflow#21955] opened 2018-08-29 17:12 UTC
### System information
- Custom code:
- Windows 7 x64:
- Anaconda distributed
- Tensorflow version 1.8.0:
- python 3.6.0 :
- CUDA  V9.0.176 /cuDNN 7.0:
- NVIDIA QUADRO K1100M :

### The problem
``````python
import tensorflow as tf
n_users = tf.placeholder(dtype=tf.int64, shape=[], name='n_users')
n_items = tf.placeholder(dtype=tf.int64, shape=[], name='n_items')
shape = tf.stack([n_users, n_items])

sess = tf.Session()
sess.run(shape, feed_dict={n_users: 100, n_items: 100})
# array([-4631544634021885188,  4529727110648879041], dtype=int64)
``````
It seems that it overflows. 

I also tried by using np.int64 instead of python native integers and it gives: 
array([ 10, 4357074203494797000], dtype=int64). 
It works if I define int32 placeholders.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment] 2018-08-31 22:03
Can you try upgrading to the most recent version of TF (1.10)?

**Comment by DanielMorales9** [comment] 2018-09-04 10:31
@skye I tried with tensorflow 1.10 and it works

**Comment by skye** [comment] 2018-09-04 16:52
Great, thanks for reporting back! I'll go ahead and close this since it works now.

**Closed by skye** 2018-09-04 16:52 UTC
Labels: stat:awaiting response
