### ISSUE TITLE
tf.keras.Model#load_weights() cannot be used on a directory generated by tf.keras.callback.ModelCheckpoint

### ISSUE THREAD

**Issue by nikvaessen** [tensorflow/tensorflow#38745] opened 2020-04-21 10:18 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04, Windows 10
- TensorFlow installed from (source or binary): pipy, anaconda
- TensorFlow version (use command below): 2.1
- Python version: 3.7

**Describe the current behavior**

When using the `tf.keras.callbacks.ModelCheckpoint('path/to/checkpoint.tf', save_weights_only=False)` callback when training with `tf.keras.Model#fit()`,  tensorflow stores a checkpoint as a directory with the following content:

```
/path/to/checkpoint.tf/
|  saved_model.pb
|  assets/
     | ....
| variables
     | variables.data-00000-of-x
     | ....
     | variables.index
```

According to the documentation of [`ModelCheckpoint`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint), `save_weights_only=False` uses [`tf.keras.Model#save()`](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save), which will save:

> * The model architecture, allowing to re-instantiate the model.
> * The model weights.
> * The state of the optimizer, allowing to resume training exactly where you left off.

When `tf.keras.callbacks.ModelCheckpoint('/path/to/weights.tf', save_weights_only=True)`  is used, a checkpoint is stored as:
```
/path/to/
| checkpoint
| weights.tf.data-00000-of-00002
| weights.tf.data-00001-of-00002
| weights.tf.index
```
Side note: `save_weights_only=False` expects a directory path, `save_weights_only=True`expects a file path. 

Using `save_weights_only=True` uses [`tf.keras.Model#save_weights()`](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save_weights).

Consequently, the model can be loaded by using

```python
# this works
def build_model():
    ...
    return tf.keras.Model()

model1 = tf.keras.models.load_model("path/to/checkpoint.tf")

model2 = build_model()
model2.load_weights("path/to/weights.tf")
```

However, using `path/to/checkpoint.tf` with `tf.keras.Model#load_weights()` fails.

```python
model3 = build_model()
model3.load_weights("path/to/checkpoint.tf")
```
outputs:
```

OSError                                   Traceback (most recent call last)
<ipython-input-16-af9095619790> in <module>()
----> 1 model = build_model().load_weights(str(save_full))

3 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file read failed: time = Tue Apr 21 10:08:58 2020
, filename = 'checkpoint.tf', file descriptor = 60, errno = 21, error message = 'Is a directory', buf = 0x7ffced128070, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)
```
Instead, I need to do:

```python
# this works
new_model = build_model()
new_model.load_weights("path/to/checkpoint.tf/variables/variables")
```

**Describe the expected behavior**

As `tf.keras.callbacks.ModelCheckpoint` hides the differences between `tf.keras.Model#save()` and `tf.keras.Model#save_weights()` from users, I expect the following code to work:

```python
def build_model():
    ...

path = "path/to/checkpoint.tf"
callbacks = [tf.keras.callbacks.ModelCheckpoint(path, save_weights_only=False)]
model = build_model()
model.fit(..., callbacks=callbacks)

# now I can either load the whole model
new_model = tf.keras.models.load_model(path)

# or I can only load the weights
another_new_model = build_model()
another_new_model = another_new_model.load_weights(path)
```

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/104UFbStlddH8tH_xOD58dTbjEAj9SsKE

**Comment by nikvaessen** [comment] 2020-04-21 13:48
I'm willing to look into making a PR if it is a bug.

**Comment by amahendrakar** [comment] 2020-04-22 05:20
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/fecda942b8d8dcc16d2a0db53547c9f6/38745-2-1.ipynb), [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/2c080a1673c1dd1df03f96ea37774bf7/38745.ipynb#scrollTo=hE1uriFRRyW1), and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/db6e53e41b9d4bf21c3fe4abc5857be9/38745-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by fr3fou** [comment] 2020-07-15 20:53
any news regarding this issue? i'm experiencing the same thing

**Comment by jvishnuvardhan** [comment] 2020-09-18 00:59
@nikvaessen I had answered similar question sometime back. This is not a bug. It is implementation related issue.

As you correctly mentioned that  `ModelCheckpoint`, with  `save_weights_only=False` uses  `tf.keras.Model#save()` which saves entire model architecture, optimizer status and weights. When you want to load the model, you need to use `load_model` as in your `model1`.

`ModelCheckpoint`, with  `save_weights_only=True` uses `tf.keras.Model#save_weights()` which saves weights. When you want to load the saved weights, you need to use `load_weights` as in your `model2`.

In your `model3`, you built a model and need to use `load_weights` with the saved weights file as you had used in `model2` example. However, you are using entire saved_model while the code is expecting weights only. This is the reason the code is throwing error.

```
new_model = build_model()
new_model.compile(loss='mse')
model.load_weights(str(save_full))

```

Please verify once and close the issue if the issue was resolved for you. Thanks!

**Closed** 2020-09-25 20:50 UTC
Labels: TF 2.1, TF 2.2, comp:keras, stalled, stat:awaiting response, type:bug

**Comment by Po-Hsuan-Huang** [comment] 2021-11-17 06:30
@jvishnuvardhan 
I think @nikvaessen was asking for correcting the implementation based on the tutorial [here](https://www.tensorflow.org/tutorials/keras/save_and_load#checkpoint_callback_usage).

        checkpoint_path = "training_1/cp.ckpt"
        checkpoint_dir = os.path.dirname(checkpoint_path)
        
        # Create a callback that saves the model's weights
        cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                         save_weights_only=True,
                                                         verbose=1)
        
        # Train the model with the new callback
        model.fit(train_images, 
                  train_labels,  
                  epochs=10,
                  validation_data=(test_images, test_labels),
                  callbacks=[cp_callback])  # Pass callback to training
        
        # This may generate warnings related to saving the state of the optimizer.
        # These warnings (and similar warnings throughout this notebook)
        # are in place to discourage outdated usage, and can be ignored.


        # Loads the weights
        model.load_weights(checkpoint_path)
        
        # Re-evaluate the model
        loss, acc = model.evaluate(test_images, test_labels, verbose=2)
        print("Restored model, accuracy: {:5.2f}%".format(100 * ACC))
