### ISSUE TITLE
Using tfdbg with errors.

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#14993] opened 2017-11-30 07:55 UTC
VERSION: TF-1.4.0

Problem:
  I want to use tfdbg to debug NaN problem with `tf_debug.LocalCLIDebugHook()` , but encounter thie problem.
  One more question, how to lower the size of dump files?

Logging is below:
```
Traceback (most recent call last):
  File "./train.py", line 166, in <module>
    _, loss, l2_loss, predicted, labels, label_lengths, step = sess.run(ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1032, in run
    run_metadata=run_metadata))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/wrappers/hooks.py", line 157, in after_run
    self._session_wrapper.on_run_end(on_run_end_request)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 321, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 495, in __init__
    self._load_all_device_dumps(partition_graphs, validate)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 517, in _load_all_device_dumps
    self._load_partition_graphs(partition_graphs, validate)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 798, in _load_partition_graphs
    self._validate_dump_with_graphs(debug_graph.device_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 874, in _validate_dump_with_graphs
    (node, datum.timestamp, repr(pending_inputs[node])))
ValueError: Causality violated in timing relations of debug dumps: model_train/model/model/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Merge (1512027705071447): these input(s) are not satisfied: [(u'model_train/model/model/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Switch_1', 1)]
```

**Comment by tatatodd** [comment] 2017-11-30 19:12
@zh794390558 Is it possible to share a minimum reproducible program, to help debug the problem?

@caisq might have some suggestions here.

**Comment by caisq** [comment] 2017-11-30 19:19
@zh794390558 One way to reduce the size of the dump is to reduce your batch size.

Also, as @tatatodd suggested, a reproduction code would be helpful for me to diagnose the problem.

**Comment by caisq** [comment] 2017-11-30 19:20
@zh794390558 another question for you: what operating system are you using with TF?

**Comment by zh794390558** [comment] 2017-12-01 08:52
@caisq my OS  is centos, and the code is too large which is attention-based seq-2-seq model.   The https://github.com/tensorflow/nmt  repo is same to my.

**Comment by caisq** [comment] 2017-12-01 19:20
I tried running tfdbg on the nmt model, so far I can't repro the issue on CPU yet. Will try again on a GPU machine soon.

**Comment by resec** [comment] 2017-12-06 09:05
@caisq I met the same problem in a GPU machine, but when switched to CPU, the issue is gone.

**Comment by caisq** [comment] 2017-12-08 05:25
@zh794390558 @reset I tested the nmt model with tfdbg on a GPU machine
* GeForce GTX 1050 Ti 4GB
* Ubuntu 16.04
* tf-nightly-gpu version: 1.5.0-dev20171206. (This is close to HEAD, installed with `pip install tf-nightly-gpu`)

The code I used to activate tfdbg is at: https://github.com/caisq/nmt/commit/a0591f3b7650f1be0d16ac681ec5df0686daaf65

I couldn't reproduce the error. I ran a few training iterations and couldn't observe any crashes of the sort you mentioned. Am I missing any keys to reproducing this issue?

**Comment by resec** [comment] 2017-12-08 06:08
@caisq tensorflow version maybe? both @zh794390558 and I are working on tf 1.4.0. I installed it with `pip` directly. maybe you can give it a try.

**Comment by tensorflowbutler** [comment] 2017-12-22 19:00
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-06 18:55
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:17
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-08 19:18
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 13:54
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:10
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:30
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:33
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:12
Nagging Assignee @caisq: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:57
Nagging Assignee @caisq: It has been 169 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:46
Nagging Assignee @caisq: It has been 184 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:11
Nagging Assignee @caisq: It has been 199 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:02
Nagging Assignee @caisq: It has been 214 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:01
Nagging Assignee @caisq: It has been 244 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:43
Nagging Assignee @caisq: It has been 259 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:37
Nagging Assignee @caisq: It has been 274 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:44
Nagging Assignee @caisq: It has been 289 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-10-05 22:13
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-05 22:13 UTC
