### ISSUE TITLE
(venv) (base) razafimandimby@razafimandimby-Lenovo-G50-30:~$ python3 -c 'import tensorflow as tf; print(tf._version_)' Instruction non permise (core dumped)

### ISSUE THREAD

**Issue by hrazafim** [tensorflow/tensorflow#43670] opened 2020-09-30 12:22 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by hrazafim** [comment] 2020-09-30 12:24
can you help me please ?

**Comment by bhack** [comment] 2020-09-30 14:13
Are you on 64bit or 32bit machine? Please fill you template as it is empty.

**Comment by hrazafim** [comment] 2020-09-30 14:27
I'm on 64bit machine. What kind of template should I fill in ?  I'am a beginner on this platform and on IT in general. Thanks for your understanding.

**Comment by bhack** [comment] 2020-09-30 14:34
This one https://github.com/tensorflow/tensorflow/issues/43670#issue-711899548. You haven't filled any info.

**Comment by hrazafim** [comment] 2020-09-30 14:53
System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.1 TLS
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Laptop Lenovo G50-30
    TensorFlow installed from (source or binary): TensorFlow installed from source 
    TensorFlow version: 2.3.1
    Python version: 3.8.2
    Installed using virtualenv? pip?9 conda?: virtualenv 
    Bazel version (if compiling from source):
    GCC/Compiler version (if compiling from source):
    CUDA/cuDNN version:
    GPU model and memory: Graphic Pilote Nvidia for Windows 8.1 (64 bits) - Lenovo G50-30

I'm sorry, I don't know for the rest.

**Comment by bhack** [comment] 2020-09-30 14:55
Can you run in python:
```
import sys
print(sys.maxsize > 2**32)
```

**Comment by hrazafim** [comment] 2020-09-30 15:01
(venv) (base) razafimandimby@razafimandimby-Lenovo-G50-30:~$ import sys

La commande « import » n'a pas été trouvée, mais peut être installée avec :

sudo apt install graphicsmagick-imagemagick-compat  # version 1.4+really1.3.35-1, or
sudo apt install imagemagick-6.q16                  # version 8:6.9.10.23+dfsg-2.1ubuntu11.1
sudo apt install imagemagick-6.q16hdri              # version 8:6.9.10.23+dfsg-2.1ubuntu11.1

**Comment by hrazafim** [comment] 2020-09-30 15:01
this is the error message that i have

**Comment by bhack** [comment] 2020-09-30 15:05
It Is python code

**Comment by hrazafim** [comment] 2020-09-30 15:10
(venv) (base) razafimandimby@razafimandimby-Lenovo-G50-30:~$ sudo apt install imagemagick-6.q16hdri
(venv) (base) razafimandimby@razafimandimby-Lenovo-G50-30:~$ import sys
import-im6.q16hdri: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
This is the last command that i do and the error message

**Comment by hrazafim** [comment] 2020-09-30 15:11
can you take my laptop with TeamViewer please ?

**Comment by bhack** [comment] 2020-09-30 15:35
It is not a bug it is just a support request. 
I think that you can close this ticket and reformulate as a support question at https://stackoverflow.com/questions/tagged/tensorflow

**Closed** 2020-09-30 16:08 UTC
Labels: stat:awaiting response, type:build/install
