### ISSUE TITLE
gradient_transformers throw autograph errors when trying to maintain state in tensorarray

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#44784] opened 2020-11-11 22:56 UTC
I'm trying to implement automatic gradient clipping, where the norm of the gradient is stored on each train step, and the gradient is clipped based off the accumulated distribution of gradient norms. However, I seem to be running into some autograph issue.

Here's the code to reproduce the issue

```python
import tensorflow as tf
import tensorflow_probability as tfp

class AutoClipper:
    def __init__(self, clip_percentile):
        self.clip_percentile = clip_percentile
        self.grad_history = None
        self.i = None

    def __call__(self, grads_and_vars):
        if self.grad_history is None:
            self.grad_history = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
            self.i = 0

        grad_norms = [_get_grad_norm(g) for g, _ in grads_and_vars]
        total_norm = tf.norm(grad_norms)
        self.grad_history = self.grad_history.write(self.i, total_norm)
        self.i += 1
        clip_value = tfp.stats.percentile(self.grad_history.stack(), q=self.clip_percentile)
        return [(tf.clip_by_norm(g, clip_value), v) for g, v in grads_and_vars]

def _get_grad_norm(t, axes=None, name=None):
    values = tf.convert_to_tensor(t.values if isinstance(t, tf.IndexedSlices) else t, name="t")

    # Calculate L2-norm, clip elements by ratio of clip_norm to L2-norm
    l2sum = tf.math.reduce_sum(values * values, axes, keepdims=True)
    pred = l2sum > 0
    # Two-tap tf.where trick to bypass NaN gradients
    l2sum_safe = tf.where(pred, l2sum, tf.ones_like(l2sum))
    return tf.squeeze(tf.where(pred, tf.math.sqrt(l2sum_safe), l2sum))


model = tf.keras.models.Sequential(
        [
            tf.keras.layers.Flatten(input_shape=(28, 28)),
            tf.keras.layers.Dense(128, activation="relu"),
            tf.keras.layers.Dropout(0.2),
            tf.keras.layers.Dense(10),
        ]
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=0.001,
            gradient_transformers=[AutoClipper(10)],
        ),
        loss="mean_absolute_error",
        metrics=["accuracy"],
    )

    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0

    model.fit(x_train, y_train)
```

It seems to fail when trying to update the tensorarray, but I thought tensorarrays could be created outside `tf.function`:
```python
op_name = '__inference_train_function_13337', num_outputs = 4
inputs = [<tf.Tensor: shape=(), dtype=resource, numpy=<unprintable>>, <tf.Tensor: shape=(), dtype=variant, numpy=<unprintable>>...ensor: shape=(), dtype=resource, numpy=<unprintable>>, <tf.Tensor: shape=(), dtype=resource, numpy=<unprintable>>, ...]
attrs = ('executor_type', '', 'config_proto', b'\n\x07\n\x03CPU\x10\x01\n\x07\n\x03GPU\x10\x002\x02J\x008\x01\x82\x01\x00')
ctx = <tensorflow.python.eager.context.Context object at 0x7fa34a9b2f50>
name = None

    def quick_execute(op_name, num_outputs, inputs, attrs, ctx, name=None):
      """Execute a TensorFlow operation.
    
      Args:
        op_name: Name of the TensorFlow operation (see REGISTER_OP in C++ code) to
          execute.
        num_outputs: The number of outputs of the operation to fetch.
                     (Explicitly provided instead of being inferred for performance
                     reasons).
        inputs: A list of inputs to the operation. Each entry should be a Tensor, or
          a value which can be passed to the Tensor constructor to create one.
        attrs: A tuple with alternating string attr names and attr values for this
          operation.
        ctx: The value of context.context().
        name: Customized name for the operation.
    
      Returns:
        List of output Tensor objects. The list is empty if there are no outputs
    
      Raises:
        An exception on error.
      """
      device_name = ctx.device_name
      # pylint: disable=protected-access
      try:
        ctx.ensure_initialized()
        tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
>                                           inputs, attrs, num_outputs)
E                                           TypeError: An op outside of the function building code is being passed
E                                           a "Graph" tensor. It is possible to have Graph tensors
E                                           leak out of the function building context by including a
E                                           tf.init_scope in your function building code.
E                                           For example, the following function will fail:
E                                             @tf.function
E                                             def has_init_scope():
E                                               my_constant = tf.constant(1.)
E                                               with tf.init_scope():
E                                                 added = my_constant * 2
E                                           The graph tensor has name: Adam/TensorArrayV2Write/TensorListSetItem:0

./lib/python3.7/site-packages/tensorflow/python/eager/execute.py:60: TypeError
```

**System information**
- tensorflow 2.4.0-rc1
- python 3.5
- ubuntu 20.04

**Comment by ravikyram** [comment] 2020-11-12 07:45
I have tried in colab with TF version 2.4-rc1 and nightly version(`2.5.0-dev20201111`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/258ea3c0234e12f0c82dbd9e9f1e3b7d/untitled516.ipynb#scrollTo=07fbRaD5Zolp). Thanks!

**Comment by omalleyt12** [comment] 2020-11-12 22:55
@lminer Thanks for the issue!

I think it'd be better to do this with `tf.Variables`. There's a few things I think won't work with the current approach:

(1) Access to a TensorArray element created in one tf.function call and accessed in another
(2) Python control flow via `self.i += 1`

(1) is the issue you're hitting now, (2) will mean only the first TensorArray element ever gets updated:

```
grads_and_vars = [(tf.convert_to_tensor(1.), tf.Variable(1.))]
autoclipper = AutoClipper(10)

@tf.function
def my_fn(gv):
  return autoclipper(gv)

my_fn(grads_and_vars)
my_fn(grads_and_vars)

print(autoclipper.i)
```

Instead I'd recommend creating a `tf.Variable` of shape `N` and doing running statistics over the last `N` batches for a similar result. Closing because I don't think this is an issue with the `gradient_transformers` but feel free to re-open if I've misunderstood

**Closed by omalleyt12** 2020-11-12 22:55 UTC
Labels: TF 2.4, comp:keras, type:bug

**Comment by lminer** [comment] 2020-11-13 00:06
Thanks @omalleyt12 I think that fixed it.
