### ISSUE TITLE
map_fn() missing GPU implementation

### ISSUE THREAD

**Issue by kwaegel** [tensorflow/tensorflow#28458] opened 2019-05-07 00:41 UTC
It appears that `map_fn()` does not have a GPU implementation for integer tensors, which seems to be causing performance issues for some networks I'm designing (e.g. excessive data copying).

This may be related to #5965, but `map_fn()` isn't explicitly mentioned there.

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04 & Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Ubuntu apt-get repo, WinPython
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7.4.1.5
- GPU model and memory: nVidia K80 & nVidia GTX 1050 Ti

**Describe the current behavior**
`tf.map_fn()` is located on the CPU when calling with integer tensors. Forcing GPU location results in an error message.

**Describe the expected behavior**
`tf.map_fn()` should have a GPU implementation to avoid excessive data copying.

**Code to reproduce the issue**
```
import tensorflow as tf

initial_integers = tf.zeros((10,), dtype=tf.int32)
initial_floats = tf.zeros((10,), dtype=tf.float32)
                
with tf.Session(config=tf.ConfigProto(allow_soft_placement=False)) as sess:
    with tf.device('/device:GPU:0'):

        # This works on GPU:
        results1 = tf.map_fn(tf.square, initial_floats)
        output1 = sess.run(results1)

        # This fails to locate on GPU, and results in an error.
        results2 = tf.map_fn(tf.square, initial_integers)
        output2 = sess.run(results2)
```

**Comment by caissalover** [comment] 2019-05-07 08:16
Yes, map_fn is central for parallelization. In https://github.com/tensorflow/tensorflow/issues/24774 ,  hansok has mentioned the problems 4 months ago, we request you to make this better.

4 years into tf, finding that a central op for parallelization on this lower layer isn't fast enough is a shame. https://github.com/tensorflow/tensorflow/issues/27644 issue is also related

**Comment by aaroey** [comment] 2019-05-14 17:40
@reedwm would you please take a look? Thanks.

**Comment by reedwm** [comment] 2019-05-14 18:49
The error message I get is:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation map_1/TensorArray: Could not satisfy explicit device specification '' because the node {{colocation_node map_1/TensorArray}} was colocated with a group of nodes that required incompatible device '/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='' supported_device_types_=[CPU, XLA_CPU, XLA_GPU] possible_devices_=[]
TensorArrayScatterV3: CPU XLA_CPU XLA_GPU 
TensorArrayReadV3: CPU XLA_CPU XLA_GPU 
Enter: GPU CPU XLA_CPU XLA_GPU 
Const: GPU CPU XLA_CPU XLA_GPU 
TensorArrayV3: CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  zeros (Const) 
  map_1/TensorArray (TensorArrayV3) 
  map_1/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3 (TensorArrayScatterV3) 
  map_1/while/TensorArrayReadV3/Enter (Enter) /device:GPU:0
  map_1/while/TensorArrayReadV3 (TensorArrayReadV3) /device:GPU:0

	 [[{{node map_1/TensorArray}}]]
```

The core problem is that TensorArray does not have a GPU implementation for most integer types, although int64 support was added in #22157.

Marking as contributions welcome for support for other integer types.

**Comment by ila96** [comment] 2019-05-16 09:59
Hi, I would like to work on this issue. Is that ok?

**Comment by reedwm** [comment] 2019-05-16 18:48
@ila96, that sounds good. Thank you for working on this.

**Comment by ebrevdo** [comment] 2019-06-14 17:00
Hi, while I think we can enable support for int8 and int16, the int32 support is problematic because we often use int32s to represent shapes and sizes.  writing int32s to the GPU just to pull them off again to get a shape will create performance regressions for many existing users.

**Comment by ebrevdo** [comment] 2019-06-14 17:01
The current workaround is to store int32s that you want to have on GPU as int64s.  We are working on some grappler optimizers to determine whether a Tensor should be on CPU or GPU in a more intelligent fashion, but again we need to resolve some performance regressions before turning that on.  Once that's in, we can probably add a full non-host int32 gpu kernel.

**Comment by arman-kazemi** [comment] 2019-06-17 16:42
Hi, I am also trying to use tf.map_fn to apply a function to all the elements in a tensor, but I have a custom function(binary search) to apply to the tensor. Here is a MWE:

```python
import numpy as np
import tensorflow as tf

xaxis = tf.placeholder(tf.float32, shape=65, name='xaxis')
query = tf.placeholder(tf.float32, shape=(100,200,300), name='query')

# Binary search finding the closest value in xaxis to query
vals = tf.map_fn(lambda x: xaxis[tf.argmin(tf.cast(x >= xaxis, dtype=tf.int32)[1:] - tf.cast(x >= xaxis, dtype=tf.int32)[:-1])], tf.reshape(query,[-1]))

vals = tf.reshape(vals,[100,200,300])

q = np.random.uniform(0,1,[100,200,300])
x = np.array([ 0., 0.01351199363, 0.01605320922, 0.01919331, 0.02307077696, 0.02783668021, 0.03369964045,  0.0408574876, 0.04963394341, 0.06031676052, 0.07331958337, 0.08909202547, 0.1081556385,
            0.1311039123, 0.1586382439, 0.1914780151, 0.2305044681, 0.2810934435, 0.2836346591, 0.2867747599, 0.2906522269, 0.2954181301, 0.3012810904, 0.3084389375, 0.3172153933, 0.3278982104,
            0.3409010333, 0.3566734754, 0.3757370884, 0.3986853622, 0.4262196938, 0.459059465, 0.4980859181, 0.4991494381, 0.5016906537, 0.5048307545, 0.5087082214, 0.5134741247, 0.5193370849,
            0.5264949321, 0.5352713879, 0.545954205, 0.5589570279, 0.57472947, 0.593793083, 0.6167413568, 0.6442756884, 0.6771154595, 0.7161419126, 0.7830075255, 0.7855487411, 0.7886888419,
            0.7925663088, 0.7973322121, 0.8031951723, 0.8103530195, 0.8191294753, 0.8298122924, 0.8428151152, 0.8585875573, 0.8776511704, 0.9005994441, 0.9281337758, 0.9609735469, 1 ])

with tf.Session() as sess:
    start_time = time.time()
    value = sess.run(vals, feed_dict={xaxis: x, query: q})
    duration = time.time() - start_time
print(duration)
```
The GPU utilization when running this code is on 2%, while the GPU memory consumption is at maximum. Is this problem related to the tf.map_fn?

**Comment by vcarpani** [comment] 2019-06-19 06:48
@ebrevdo, thanks for the feedback, I will change my PR to remove int32 then ;)

**Comment by ymodak** [comment] 2021-08-12 21:47
This is now fixed with recent TF 2.X versions.
I have tested TF 2.5, please refer the colab [gist](https://colab.sandbox.google.com/gist/ymodak/72706ea02f26fc3d63f12fb60fb4dd3a/gh_issue_28458.ipynb) Thanks!

**Closed by ymodak** 2021-08-12 21:47 UTC
Labels: stat:contributions welcome, type:bug, comp:gpu
