### ISSUE TITLE
High RAM Usage for TF Runtime?

### ISSUE THREAD

**Issue by yetanotheryeti** [tensorflow/tensorflow#36459] opened 2020-02-04 10:13 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-gpu==2.0.0 or tensorflow==2.1.0
- Python version: 3.6.8
- CUDA/cuDNN version: CUDA Toolkit 10.1.243 / cuDNN 7.6.5.32
- GPU model and memory: 8 x GeForce RTX 2080 Ti, 11019MiB
- System memory: 32GB

**Describe the current behavior**

Even the smallest 'computation' leads to very high RAM usages of the system memory (not GPU memory). As shown in the following, a simple single-float-Variable initialization leads to more than 2GB RAM increase. The fewer graphics cards are visible for tensorflow, the less RAM is used after all. 

**Describe the expected behavior**

The expected behavior is way less memory usage and also a constant amount, independently of the number of GPUs visible to tensorflow. More than 2GB per instance is not viable for my (/our) situation, since multiple users are working on the machine. 

**Code to reproduce the issue**

```
import os, psutil
p = psutil.Process(os.getpid())

print("Memory Usage (before import):", p.memory_info().rss/1024/1024, "MB")

import tensorflow as tf
num_visible_gpus = 8 # OPTIONAL
gpu_devs = tf.config.experimental.list_physical_devices("GPU") # OPTIONAL
tf.config.experimental.set_visible_devices(gpu_devs[:num_visible_gpus], "GPU") # OPTIONAL

print("Memory Usage (after  import):", p.memory_info().rss/1024/1024, "MB")

tf.Variable(42.0) # Do some pseudowork...

print("Memory Usage (after var-def):", p.memory_info().rss/1024/1024, "MB")
```

Output:
> Memory Usage (before import): 47.62109375 MB
> Memory Usage (after  import): 340.15625 MB
> Memory Usage (after var-def): 2485.1796875 MB

Lesser GPUs result in less memory usage (after var-def):

> num_visible_gpus=8 => 2626.039063 MB
> num_visible_gpus=7 => 2488.765626 MB
> num_visible_gpus=6 => 2267.289063 MB
> num_visible_gpus=5 => 2173.917968 MB
> num_visible_gpus=4 => 2011.917968 MB
> num_visible_gpus=3 => 1809.957031 MB
> num_visible_gpus=2 => 1681.316406 MB
> num_visible_gpus=1 => 1539.554688 MB
> num_visible_gpus=0 => 1201.152343 MB

These results were obtained in a jupyter-notebook environment. When run as a py-file, the usages are slightly (by ~200MB) lower (e.g. num_visible_gpus=8 => 2347.7148437 MB).

**Comment by gadagashwini** [comment] 2020-02-05 08:48
I tried on colab, it took around 1GB of RAM with Tf 2.1 and 2.0.
Please take a look at the gist [here](https://colab.research.google.com/gist/gadagashwini/c0fb1823be9b1feb7bcd78705a20b5ba/untitled375.ipynb). Thanks!

**Comment by yetanotheryeti** [comment] 2020-02-05 12:29
This is because Colab does not have the same setup as me. Colab only utilizes a single GPU:
`tf.config.experimental.list_physical_devices("GPU")`
outputs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

This aggrees somehow with my observations when I turn only one of the eight GPUs visible (num_visible_gpus=1 => 1539.554688 MB) or zero (num_visible_gpus=0 => 1201.152343 MB). 

So does this mean, that Tensorflow simply aquires this much of memory in such a minimal scenario?
Also: Is it not possible to lower the usage while more GPUs are visible?

**Comment by gowthamkpr** [comment] 2020-02-05 20:51
@yetanotheryeti Please go through this [doc ](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let me know if it helps. Thanks!

**Comment by yetanotheryeti** [comment] 2020-02-06 12:18
Sorry, this does not help, since it is not the GPU-memory, but the system memory, which is the bottleneck for us. 

Nevertheless, I tried setting the memory growth to true and it surprisingly lowers the usage a little bit  (about 200 MB). Still, 2.3 GB usage is too much for our usecase. 

What I'm interested in is if this is reproducable for other systems with more than one GPU. 
If the answer to this problem is simply: "Well tensorflow simply needs to allocate this much memory, because ..., so you can not do anything about it." then I'd be happy. 
However, I am still unsure if the high usage is a "bug" or a "mishandling" on my side or simply how it is.

**Comment by gowthamkpr** [comment] 2020-02-06 20:40
@sanjoy Can you PTAL? Thanks!

**Comment by yetanotheryeti** [comment] 2020-02-13 09:34
@sanjoy 
Hello, are there any updates? This is a somewhat blocking issue for our team.
Thank you!

**Comment by sanjoy** [comment] 2020-02-16 06:05
I believe RSS includes all of the CUDA libraries TensorFlow loads which could explain the large memory footprint you're seeing.  Given that, I would expect multiple TF gpu processes to share the actual physical memory for these loaded shared objects.

**Comment by billythegod** [comment] 2020-02-24 05:54
please update if possible, facing the same issue. too much CPU memory used for pinned memory

**Comment by sanjoy** [comment] 2020-02-25 05:18
I think this is working as intended (so I'm closing the issue).  The CUDA libraries are provided by NVIDIA and we can't do much to reduce their size.  On the other hand, I would expect RSS to be shared with other processes so the motivating concern

> More than 2GB per instance is not viable for my (/our) situation, since multiple users are working on the machine.

does not apply.

@yetanotheryeti, please reopen the issue if you disagree.

> too much CPU memory used for pinned memory

@billythegod I believe you have a different issue, this issue is not about pinned host memory.  Please open a separate issue with a reproducer.

**Closed by sanjoy** 2020-02-25 05:18 UTC
Labels: TF 2.1, comp:runtime, type:bug

**Comment by yetanotheryeti** [comment] 2020-02-25 14:40
> On the other hand, I would expect RSS to be shared with other processes

To clarify: *each* process has the described RSS-footprint (such as ~2GB), so it is not shared, even among processes of the same user. Sorry, I did not clearly state this before.

> The CUDA libraries are provided by NVIDIA and we can't do much to reduce their size.
Ok, this is what I fairly expected (similar to as I stated before: "Well tensorflow (or CUDA) simply needs to allocate this much memory, because ..., so you can not do anything about it."). This leaves us with either figuring out if and how the CUDA libraries can be shared between processes, or finding another strategy for our team.

**Comment by sanjoy** [comment] 2020-02-25 20:12
> To clarify: each process has the described RSS-footprint (such as ~2GB), so it is not shared, even among processes of the same user. Sorry, I did not clearly state this before.

Are you sure this ~2GB number is not misleading?  I believe that a page loaded in memory will be accounted in the RSS count for all processes that have that page in their page table.  So the sum of RSS footprints for all running processes can exceed the total amount of RAM in the system.

**Comment by yetanotheryeti** [comment] 2020-02-26 10:10
> Are you sure this ~2GB number is not misleading?

I am quite sure. We had multiple OOMs, leading to process kills by the OOM killer or even system crashes. Also, according to (h)top the total system memory consumption is rising per process as well:

Four python instances with tensorflow loaded. Each instance has its own GPU assigned via 'set_visible_devices':
<img src="https://user-images.githubusercontent.com/5852533/75334278-d4aa9600-5887-11ea-931d-1750e4f6b722.png" alt="drawing" width="500"/>

After initializing 'tf.Variable(42.)' for each instance: 
<img src="https://user-images.githubusercontent.com/5852533/75334299-df652b00-5887-11ea-85ba-6aa928819b45.png" alt="drawing" width="500"/>

**Comment by loicsacre** [comment] 2020-03-25 17:15
I have experienced the same observation and have been wondering why the rss is higher when using tensorflow working with the GPU vs CPU only. For a same running program, I have observed these rss percentages:

- CPU only : 6.7%
- GPU : 13,7%
- GPU (and allow_growth set to True) : 11.6%

**Comment by ASRodrigo1** [comment] 2020-09-13 00:58
https://github.com/tensorflow/tensorflow/issues/31312#issuecomment-691583440

**Comment by nistarlwc** [comment] 2020-11-05 10:19
run 6 small models(.pb about 44MB ), inference with 6 multiprocessing in python3.7 and tensorflow1.13.1.
In windows, use 4G memory, but in Ubuntu use 12G memory, don't know why.

**Comment by gioxc88** [comment] 2020-12-10 13:01
> run 6 small models(.pb about 44MB ), inference with 6 multiprocessing in python3.7 and tensorflow1.13.1.
> In windows, use 4G memory, but in Ubuntu use 12G memory, don't know why.

I noticed the same behavior in linux vs windows

**Comment by Wabinab** [comment] 2020-12-28 16:39
It seems like whatever computation we're doing, the RAM (and CPU) overhead are used for maintaining the GPUs to run, so it seems like for small models we need to deliberately turn off some GPU to prevent excess memory usage. If that's not the case, I also noticed in my case that using tf.Dataset API .cache() for large dataset will just cache all the data and run out of memory eventually so I disable .cache() and everything works fine for me.

**Comment by rajasd27** [comment] 2021-03-19 20:05
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
> * TensorFlow installed from (source or binary): pip
> * TensorFlow version (use command below): tensorflow-gpu==2.0.0 or tensorflow==2.1.0
> * Python version: 3.6.8
> * CUDA/cuDNN version: CUDA Toolkit 10.1.243 / cuDNN 7.6.5.32
> * GPU model and memory: 8 x GeForce RTX 2080 Ti, 11019MiB
> * System memory: 32GB
> 
> **Describe the current behavior**
> 
> Even the smallest 'computation' leads to very high RAM usages of the system memory (not GPU memory). As shown in the following, a simple single-float-Variable initialization leads to more than 2GB RAM increase. The fewer graphics cards are visible for tensorflow, the less RAM is used after all.
> 
> **Describe the expected behavior**
> 
> The expected behavior is way less memory usage and also a constant amount, independently of the number of GPUs visible to tensorflow. More than 2GB per instance is not viable for my (/our) situation, since multiple users are working on the machine.
> 
> **Code to reproduce the issue**
> 
> ```
> import os, psutil
> p = psutil.Process(os.getpid())
> 
> print("Memory Usage (before import):", p.memory_info().rss/1024/1024, "MB")
> 
> import tensorflow as tf
> num_visible_gpus = 8 # OPTIONAL
> gpu_devs = tf.config.experimental.list_physical_devices("GPU") # OPTIONAL
> tf.config.experimental.set_visible_devices(gpu_devs[:num_visible_gpus], "GPU") # OPTIONAL
> 
> print("Memory Usage (after  import):", p.memory_info().rss/1024/1024, "MB")
> 
> tf.Variable(42.0) # Do some pseudowork...
> 
> print("Memory Usage (after var-def):", p.memory_info().rss/1024/1024, "MB")
> ```
> 
> Output:
> 
> > Memory Usage (before import): 47.62109375 MB
> > Memory Usage (after  import): 340.15625 MB
> > Memory Usage (after var-def): 2485.1796875 MB
> 
> Lesser GPUs result in less memory usage (after var-def):
> 
> > num_visible_gpus=8 => 2626.039063 MB
> > num_visible_gpus=7 => 2488.765626 MB
> > num_visible_gpus=6 => 2267.289063 MB
> > num_visible_gpus=5 => 2173.917968 MB
> > num_visible_gpus=4 => 2011.917968 MB
> > num_visible_gpus=3 => 1809.957031 MB
> > num_visible_gpus=2 => 1681.316406 MB
> > num_visible_gpus=1 => 1539.554688 MB
> > num_visible_gpus=0 => 1201.152343 MB
> 
> These results were obtained in a jupyter-notebook environment. When run as a py-file, the usages are slightly (by ~200MB) lower (e.g. num_visible_gpus=8 => 2347.7148437 MB).

Hi yetanotheryeti, I have ran into a similar situation. Did you get a fix for this?

**Comment by orthand** [comment] 2021-04-03 00:23
I'm in the same boat. Training my models on Windows+CPU is no problem and takes ~8 GB RAM. On Linux+GPU it's easily above 28 GB and tends to get terminated (oom, exit code 139 (interrupted by signal 11: SIGSEGV)).
I've tried most of the ideas from [#31312](https://github.com/tensorflow/tensorflow/issues/31312) but the problem still persists - with or without validation data. Both systems are on TF 2.1, same code and files.

**Comment by ASRodrigo1** [comment] 2021-04-03 01:20
> 
> 
> I'm in the same boat. Training my models on Windows+CPU is no problem and takes 13 GB RAM. On Linux+GPU it's easily above my installed 32 GB (probably aiming for ~37 GB as the factor between the two systems stays around x2.8 with smaller datasets) and gets terminated (oom, exit code 139 (interrupted by signal 11: SIGSEGV)).
> I've tried most of the ideas from [#31312](https://github.com/tensorflow/tensorflow/issues/31312) but the problem still persists - with or without validation data. Both systems are on TF 2.1, same code and files.

Try to run a simple model, like Keras simple example for MNIST dataset.

**Comment by orthand** [comment] 2021-04-03 09:50
> 
> Try to run a simple model, like Keras example for MNIST dataset.
> https://keras.io/examples/vision/mnist_convnet/
> Tell us if you still facing the same problem with this simple one
> Btw, i'm using TF-GPU 2.3.0, Cuda 10.1 and Cudnn 7.6.5.
> I can train models on my GTX 1660 with no problem.

Are you on Windows or Linux? I haven't managed to run the MNIST example yet but was able to start a short test run of my code on the CPU under Linux. It has the same multiplier as the GPU so my problem seems to be on Linux only and independent of CPU/GPU. In RAM (not VRAM) numbers:
Win/CPU: ~4.2 GB used
Linux/CPU: ~11.8 GB

I've seen the same problem with/without memory_growth = True, validation_data, run_eagerly=True and garbage collector in callbacks.

**Comment by ASRodrigo1** [comment] 2021-04-03 12:10
> 
> 
> > Try to run a simple model, like Keras example for MNIST dataset.
> > https://keras.io/examples/vision/mnist_convnet/
> > Tell us if you still facing the same problem with this simple one
> > Btw, i'm using TF-GPU 2.3.0, Cuda 10.1 and Cudnn 7.6.5.
> > I can train models on my GTX 1660 with no problem.
> 
> Are you on Windows or Linux? I haven't managed to run the MNIST example yet but was able to start a short test run of my code on the CPU under Linux. It has the same multiplier as the GPU so my problem seems to be on Linux only and independent of CPU/GPU. In RAM (not VRAM) numbers:
> Win/CPU: ~4.2 GB used
> Linux/CPU: ~11.8 GB
> 
> I've seen the same problem with/without memory_growth = True, validation_data, run_eagerly=True and garbage collector in callbacks.

Gotcha.
So you could try to use another tensorflow version.

**Comment by eirikaso** [comment] 2021-05-26 11:27
any updates here? I'm also having trouble with CPU memory usage. I'm using linux.
