### ISSUE TITLE
While using tf.while_loop , the _Slicehelper chooses strided_slice op(req 4 args) instead of slice op(req 3 args)

### ISSUE THREAD

**Issue by Aashit-Sharma** [tensorflow/tensorflow#16279] opened 2018-01-22 07:15 UTC
I am facing this issue while creating a decoder using tf.while_loop

`
train_decoder = tf.while_loop(self.coarse_decoder_condition, self.coarse_decoder_function,
[self.iter_decoder_c, tf.zeros([1,self.c_dec_size]), tf.ones([self.c_dec_size])] ,
				shape_invariants =[self.iter_decoder_c.get_shape(),tf.TensorShape([None,self.c_dec_size]),tf.TensorShape([self.c_dec_size]) ] )`

here is what comes up in the cmd

```
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2576, in _BuildLoop
    c = ops.convert_to_tensor(pred(*packed_vars))

  File "C:\Users\HP\Music\Final\nn.py", line 200, in coarse_decoder_condition
    return it[0] < self.oplen_c[0]

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 538, in _SliceHelper
    name=name)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 706, in strided_slice
    shrink_axis_mask=shrink_axis_mask)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5429, in strided_slice
    name=name)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_he
lper
    op_def=op_def)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs

    shapes = shape_func(op)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shap
e_fn
    require_shape_fn)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_sha
pe_fn_impl
    raise ValueError(err.message)
ValueError: Index out of range using input dim 0; input has only 0 dims for 'Coarse_Decoder/while/strided_slice' (op: 'StridedSlice') with input shape
s: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.


```

Essentially what is happening is that the while_loop => buildloop => _SliceHelper

the _sliceHelper chooses strided_slice op(which requires 4 args instead of 3) instead of just slice op

This is causing me to get an error while passing 3 args , which is what my requirement is.

A similar issue highlighted [here ](https://github.com/tensorflow/models/issues/817)

I can't manually choose slice() over strided_slice()

Any help would be appreciated @michaelisard

**Comment by tensorflowbutler** [comment] 2018-01-24 13:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Aashit-Sharma** [comment] 2018-01-25 03:23
OS Platform and Distribution : Windows 7 Professional
TensorFlow version 1.4.0
GPU model and memory : currently running on CPU (i5) , 8GB RAM
Rest are not relevant to my case
Exact command to reproduce:

I was creating a decoder rnn with GRU cell. Here is the function:

`def nl_decoder(self):
		
		with tf.variable_scope("NL_Decoder"):
			self.decoder_nl_cell = tf.contrib.rnn.GRUCell(self.nl_dec_size)
			
			self.iter_decoder_nl = tf.constant(0)
			self.iter_decoder_nl_test = tf.constant(0)
			
			train_decoder = tf.while_loop(self.nl_decoder_condition,self.nl_decoder_function, [ self.iter_decoder_nl, tf.zeros([1,self.nl_dec_size]) , tf.ones([self.nl_dec_size])],\
			shape_invariants = [self.iter_decoder_nl.get_shape(), tf.TensorShape([None,self.nl_dec_size]),\
			tf.TensorShape([self.nl_dec_size])])

		return train_decoder[1][1:]`

**Comment by tatatodd** [comment] 2018-01-26 21:49
@Aashit-Sharma Please provide a minimum reproducible example.

The snippets of code you've provided above don't define self.nl_decoder_{condition,function}, or other critical pieces of information.

**Comment by Aashit-Sharma** [comment] 2018-01-29 02:11
`def nl_decoder_condition(self,it,outputs,hidden):
			return it[0] < self.oplen_nl[0]
																					
		# This is the step where we concatenate hidden state with context hidden state 			
		def nl_decoder_function(self,it,outputs,hidden):
			out,hidden = self.decoder_nl_cell(tf.stack([tf.concat(0,[outputs[-1,:],self.nl_context_concat])]) , tf.stack([hidden]))
			
			outputs = tf.concat(0,[outputs,out])
			return it+1,outputs,hidden[0,:]		`

Sorry for the delayed response. These are all the functions necessary to run the nl_decoder .

**Comment by tatatodd** [comment] 2018-01-29 17:58
@Aashit-Sharma I think you've misunderstood my request.  Please provide a standalone example that exhibits the problem when it is run.  I.e. provide the full python program.  Otherwise it's hard to know exactly what's going wrong.  Thanks!

**Comment by Aashit-Sharma** [comment] 2018-01-30 02:10
Generate.py -

```
import pickle
from mrrnn import MRRNN
from mrrnn import Configuration


# tokenid's for end of utterance
end_nl = 12575
end_c = 15

if __name__ == "__main__":

	# import dictionaries and test data
	nldict_path = "./data/Dataset.dict.pkl"
	with open(nldict_path,"rb") as file:
		nlvocab = pickle.load(file)
		nlvocab = sorted( nlvocab,key=lambda tup: tup[1] )
	
	cdict_path = "./data/AE_Rep/abstract_dict.pkl"
	with open(cdict_path,"rb") as file:
		cvocab = pickle.load(file)
		cvocab = sorted(cvocab,key=lambda tup: tup[1] )

		
	nltest_path = "./data/Test.dialogues.pkl"
	with open(nltest_path,"rb") as file:
		nltest = pickle.load(file)
		
	ctest_path = "./data/AE_Rep/abstract_test.pkl"
	with open(ctest_path,"rb") as file:
		ctest = pickle.load(file)

	config = Configuration()
	
	config.learning_rate = 0.0003
	config.nlvocab = len(nlvocab)
	config.cvocab = len(cvocab)
	config.end_of_word_utt = end_nl 
	config.end_of_coarse_utt = end_c


#the model
	model = MRRNN(config)
	N_dialogue = 10

	file_name = "./ckpts/ckpt_files/checkpoint.ckpt"
	model.restore(file_name)
	nlDialog,cDialog = model.split_utterances([nltest[N_dialogue]],[ctest[N_dialogue]])
	prediction = model.generate(nlDialog[0][:-1],cDialog[0][:-1],20,20)
	# print nlDialog[0]
	for curr_utt in xrange(len(nlDialog[0])-1):
		curr_str = ""
	 	for k in xrange(len(nlDialog[0][curr_utt])-1):
	 		curr_str += nlvocab[nlDialog[0][curr_utt][k]][0] + " "
	 	print (curr_str)

	curr_str = ""
	for k in xrange(len(prediction)):
		curr_str += nlvocab[prediction[k]][0] + " "
	print (curr_str)`
```

**Comment by Aashit-Sharma** [comment] 2018-01-30 02:11
Train.py -

```
`import random
import pickle
from HRED import MRRNN
from HRED import Configuration



# tokenid's for end of utterance
end_nl = 12575
end_c = 15
if __name__ = "__main__":

#Importing training , testing , validation and dictionary data

	nltrain_path = "./data/Training.dialogues.pkl"
	with open(nltrain_path,"r") as file:
		nltrain = pickle.load(file)
		
	ctrain_path = "./data/abstract.train.dialogues.pkl"
	with open(ctrain_path,"r") as file:
		ctrain = pickle.load(file)

		
	nltest_path = "./data/Test.dialogues.pkl"
	with open(nltest_path,"r") as file:
		nltest = pickle.load(file)
		
	ctest_path = "./data/abstract.test.dialogues.pkl"
	with open(ctest_path,"r") as file:
		ctest = pickle.load(file)

		
	nlvalid_path = "./data/Validation.dialogues.pkl"
	with open(nlvalid_path,"r") as file:
		nlvalid = pickle.load(file)
		
	cvalid_path = "./data/abstract.valid.dialogues.pkl"
	with open(cvalid_path,"r") as file:
		cvalid = pickle.load(file)

		
	nldict_path = "./data/Dataset.dict.pkl"
	with open(nldict_path,"r") as file:
		nlvocab = pickle.load(file)
		nlvocab = sorted( nlvocab,key=lambda tup: tup[1] )
	
	cdict_path = "./data/abstract.dict.pkl"
	with open(cdict_path,"r") as file:
		cvocab = pickle.load(file)
		cvocab = sorted(cvocab,key=lambda tup: tup[1] )
		
		
	config = Configuration()
	config.learning_rate = 0.0003
	config.nlvocab = len(nlvocab) #to be changed in mrrnn
	config.cvocab = len(cvocab)
	config.end_of_word_utt = end_nl 
	config.end_of_coarse_utt = end_c
	

#the model
	model = MRRNN(config)

	batchSize = 80	
	print_every = 1
	n_train = len(nltrain)
	n_epochs = 5
	maxtrain_id = n_train - batchSize

	saveDir = "./ckpts/training_5/"
	fileRestore = "./ckpts/training_5/trained.ckpt"
	fileName = "./ckpts/training_5/trained.ckpt"

	if fileRestore:
		model.restore(fileRestore)

	loss = model.cost(nlvalid[:100],cvalid[:100])
	print (loss)

	for ep in xrange(n_epochs):
		start_id = 0
		iter = 0
		while start_id < maxtrain_id:
			end_id = start_id + batchSize
			model.partial_fit(nltrain[start_id:end_id],ctrain[start_id:end_id])
			
			if not (iter % print_every):
				loss = model.cost(nlvalid[:10],cvalid[:10])
				model.save(fileName)
				print ("{0} of {1}: {2}".format(start_id,n_train,loss))
			
			start_id += batchSize
			iter += 1
`
```

**Comment by tatatodd** [comment] 2018-01-30 19:07
@Aashit-Sharma Can you minimize this to a small standalone example that exhibits the problem?

Sorry for the back-and-forth.  But note that our policy on github issues is that it must be a bug or a feature request.  Without a small standalone example, it's impossible for me to know whether this is an actual bug.

**Comment by Aashit-Sharma** [comment] 2018-01-31 04:11
If you refer to my 1st and 2nd reply , where i mention of the main decoder function and in the following comment , of its sub-functions and placeholders (and graph variables) that is all the required stuff for the main function BUT the graph function does refer to other functions in the code to which it is related.
```
`def nl_decoder(self):
		
		with tf.variable_scope("NL_Decoder"):
			self.decoder_nl_cell = tf.contrib.rnn.GRUCell(self.nl_dec_size)
			
			self.iter_decoder_nl = tf.constant(0)
			self.iter_decoder_nl_test = tf.constant(0)
			
			train_decoder = tf.while_loop(self.nl_decoder_condition,self.nl_decoder_function, [ self.iter_decoder_nl, tf.zeros([1,self.nl_dec_size]) , tf.ones([self.nl_dec_size])],\
			shape_invariants = [self.iter_decoder_nl.get_shape(), tf.TensorShape([None,self.nl_dec_size]),\
			tf.TensorShape([self.nl_dec_size])])

		return train_decoder[1][1:]
        
 def nl_decoder_condition(self,it,outputs,hidden):
			return it[0] < self.oplen_nl[0]
																					
		# This is the step where we concatenate hidden state with context hidden state 			

def nl_decoder_function(self,it,outputs,hidden):
			out,hidden = self.decoder_nl_cell(tf.stack([tf.concat(0,[outputs[-1,:],self.nl_context_concat])]) , tf.stack([hidden]))
			
			outputs = tf.concat(0,[outputs,out])
			return it+1,outputs,hidden[0,:]

            
self.oplen_nl = tf.placeholder(tf.int32,[1],name="nl_oplen")

#this comes in the graph function
self.nl_context_concat = tf.concat(0,[self.current_hidden_nl_context,self.encoded_prediction])`

```

This can't be avoided as this is an implementation of HRED , which essentially involves a encoder , a context and a decoder RNN

The feed into the decoder RNN comes from context , to which comes from encoder .


I think if you take a look at the command prompt log , you can do with just glancing through the code to specific areas. 

essentially these lines , where the slicehelper is referenced , which references the stridedslice instead of general slice method (which requires 3 params)

  ```
File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2576, in _BuildLoop
    c = ops.convert_to_tensor(pred(*packed_vars))

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 538, in _SliceHelper
    name=name)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 538, in _SliceHelper
    name=name)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 706, in strided_slice
    shrink_axis_mask=shrink_axis_mask)

  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5429, in strided_slice
    name=name) 
```

essentially it automatically references to strided slice instead of just tf.slice.  Just have a look at shape_invariants and the code around it in the decoder function

Feel free to ask me any questions or correct me if I am wrong

**Comment by skye** [comment] 2018-02-07 00:02
Can you try with TensorFlow 1.5? It looks like this code has changed, so maybe it's fixed. If not, can you please send us the relevant code/stack traces again?

**Comment by tensorflowbutler** [comment] 2018-02-21 13:18
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-08 19:30
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 00:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:48
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-04-18 05:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-04-18 05:49 UTC
Labels: stat:awaiting response
