### ISSUE TITLE
maskrcnn convert error

### ISSUE THREAD

**Issue by chuqnzhao** [tensorflow/tensorflow#45199] opened 2020-11-26 08:42 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):2.3.1

**tflite_convert code**

```
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("./saved/")

converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS] # enable TensorFlow ops.

converter.experimental_new_converter = True
#converter.allow_custom_ops=True
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**the issue information** 
```
2020-11-26 00:41:12.251078: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: ./saved/
2020-11-26 00:41:12.272903: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2020-11-26 00:41:12.272975: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: ./saved/
2020-11-26 00:41:12.273052: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-26 00:41:12.342434: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:252] None of the MLIR optimization passes are enabled (registered 0 passes)
2020-11-26 00:41:12.432545: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2020-11-26 00:41:12.978910: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 727829 microseconds.
2020-11-26 00:41:13.202547: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2020-11-26 00:41:13.703742: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
loc("mrcnn_detection/DenseToDenseSetOperation"): error: 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
loc("mrcnn_detection/DenseToDenseSetOperation_1"): error: 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
2020-11-26 00:41:21.116517: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1670] Graph contains TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3 op(s), that use(s) resource type. Currently, the resource type is not natively supported in TFLite. Please consider not using the resource type if there are issues with either TFLite converter or TFLite runtime.
error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.DenseToDenseSetOperation {T = i64, device = "", set_operation = "intersection", validate_indices = true}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 210, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc("mrcnn_detection/DenseToDenseSetOperation"): 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
<unknown>:0: error: loc("mrcnn_detection/DenseToDenseSetOperation_1"): 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
<unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.DenseToDenseSetOperation {T = i64, device = "", set_operation = "intersection", validate_indices = true}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 745, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 636, in convert_saved_model
    data = toco_convert_protos(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("mrcnn_detection/DenseToDenseSetOperation"): 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
<unknown>:0: error: loc("mrcnn_detection/DenseToDenseSetOperation_1"): 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
<unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.DenseToDenseSetOperation {T = i64, device = "", set_operation = "intersection", validate_indices = true}

```

Looking forward to your prompt reply，thanks！

**Comment by ravikyram** [comment] 2020-11-26 09:33
@chuqnzhao 

Will it be possible to share the model file which helps us to reproduce the issue.
Also, please try with nightly version and see if the issue still persists. Thanks!

**Comment by chuqnzhao** [comment] 2020-11-26 09:46
> @chuqnzhao
> 
> Will it be possible to share the model file which helps us to reproduce the issue.
> Also, please try with nightly version and see if the issue still persists. Thanks!

I've already tried nightly version and  have encountered the same problem.
the model file link:  https://pan.baidu.com/s/1QbeUVM13tnQHG60Bv5faeg
Extract the code:  bcmz
thanks!

**Comment by ravikyram** [comment] 2020-11-26 10:25
I have tried in colab with TF version 2.3 and was able to reproduce the issue. With TF nightly version it crashes.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ca5af72d7f99aec5ffdc48ef377ae07d/untitled540.ipynb).Thanks!

**Comment by chuqnzhao** [comment] 2020-11-27 02:28
> I have tried in colab with TF version 2.3 and was able to reproduce the issue. With TF nightly version it crashes.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ca5af72d7f99aec5ffdc48ef377ae07d/untitled540.ipynb).
> @chuqnzhao
> 
> I am not able to access the link you have provided.
> 
> Thanks!

I'm terribly sorry about that. Please visit this link：https://github.com/chuqnzhao/maskrcnn.git

Looking forward to your prompt reply，thanks！

**Comment by jvishnuvardhan** [comment] 2020-12-11 02:50
@chuqnzhao I am seeing lot of warnings (before `OutOfRangeError:  Read less bytes than requested`) the as shown below. Looks like while loading model, it was not able to access `tf.Variable`). Please check below.

Can you please share model building code? Thanks! 

```
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
```

**Comment by chuqnzhao** [comment] 2020-12-11 06:00
> @chuqnzhao I am seeing lot of warnings (before `OutOfRangeError: Read less bytes than requested`) the as shown below. Looks like while loading model, it was not able to access `tf.Variable`). Please check below.
> 
> [Here](https://colab.research.google.com/gist/jvishnuvardhan/e63a664c1df8181acb3dcb1e98ae3d56/untitled540.ipynb) is a gist for our reference. Thanks!
> 
> Can you please share model building code? Thanks!
> 
> ```
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> ```

@jvishnuvardhan 
Thank you for your reply，I used the following link to generate the TensorFlow model, and then used the TensorFlow tool to convert the model to the savedModel type.
https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py

**Comment by chuqnzhao** [comment] 2020-12-11 07:02
> > @chuqnzhao I am seeing lot of warnings (before `OutOfRangeError: Read less bytes than requested`) the as shown below. Looks like while loading model, it was not able to access `tf.Variable`). Please check below.
> > [Here](https://colab.research.google.com/gist/jvishnuvardhan/e63a664c1df8181acb3dcb1e98ae3d56/untitled540.ipynb) is a gist for our reference. Thanks!
> > Can you please share model building code? Thanks!
> > ```
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'conv1/bias:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'bn_conv1/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
> > ```
> 
> @jvishnuvardhan
> Thank you for your reply，I used the following link to generate the TensorFlow model, and then used the TensorFlow tool to convert the model to the savedModel type.
> https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py
I use your conversion code to prompt for the following error
 ```
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model("./saved/", signature_keys=['serving_default'])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1101, in from_saved_model
    raise ValueError("Invalid signature key '{}' found. Valid keys are "
ValueError: Invalid signature key 'serving_default' found. Valid keys are 'predict'.

 ```
Please use the following code：
converter = tf.lite.TFLiteConverter.from_saved_model("./saved/", signature_keys=['predict'])

**Comment by jvishnuvardhan** [comment] 2020-12-11 19:30
@chuqnzhao When I made the change from `serving_defaullt` to 'predict`, the error and warnings remain same. 

`If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().` based on this warning, can you rebuild the SavedModel and try the conversion? Thanks!

**Comment by chuqnzhao** [comment] 2020-12-14 01:04
> @chuqnzhao When I made the change from `serving_defaullt` to 'predict`, the error and warnings remain same.
> 
> `If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().` based on this warning, can you rebuild the SavedModel and try the conversion? Thanks!

@jvishnuvardhan 
First of all, thank you for your reply and answer.  Could you please share the code of how to convert the meta model file to savedModel to avoid the above error and warnings, thank you!

**Comment by chuqnzhao** [comment] 2020-12-14 02:25
> > @chuqnzhao When I made the change from `serving_defaullt` to 'predict`, the error and warnings remain same.
> > `If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().` based on this warning, can you rebuild the SavedModel and try the conversion? Thanks!
> 
> @jvishnuvardhan
> First of all, thank you for your reply and answer. Could you please share the code of how to convert the meta model file to savedModel to avoid the above error and warnings, thank you!

I use the following code transformation model, please correct me.
‘’‘
 export_path = get_export_path(export_path_base,VERSIONCONTROLL)

    print('Exporting trained model to', export_path)
    builder = tf.saved_model.builder.SavedModelBuilder(export_path)

    legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
    signature = predict_signature_def(
                                inputs = {'images': model.keras_model.input[0],
                                            'meta':model.keras_model.input[1],
                                            'anchor':model.keras_model.input[2]},
                                outputs={'detection': model.keras_model.outputs[0],
                                         'mask':model.keras_model.outputs[3]}
                                )
    with K.get_session() as sess:
        builder.add_meta_graph_and_variables(sess=sess,
                                             tags=[tag_constants.SERVING],
                                             signature_def_map={'predict': signature},
                                             #legacy_init_op=legacy_init_op,
                                             clear_devices=True,
                                             )
        builder.save()

’‘’

**Comment by chuqnzhao** [comment] 2020-12-14 02:29
> @chuqnzhao When I made the change from `serving_defaullt` to 'predict`, the error and warnings remain same.
> 
> `If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().` based on this warning, can you rebuild the SavedModel and try the conversion? Thanks!
@jvishnuvardhan 
First of all, thank you for your reply and answer. Could you please share the code of how to convert the meta model file to savedModel to avoid the above error and warnings, thank you!
I use the following code transformation model, please correct me.
```
def save_pb(export_path_base, model):
    export_path = get_export_path(export_path_base,VERSIONCONTROLL)

    print('Exporting trained model to', export_path)
    builder = tf.saved_model.builder.SavedModelBuilder(export_path)

    legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
    signature = predict_signature_def(
                                inputs = {'images': model.keras_model.input[0],
                                            'meta':model.keras_model.input[1],
                                            'anchor':model.keras_model.input[2]},
                                outputs={'detection': model.keras_model.outputs[0],
                                         'mask':model.keras_model.outputs[3]}
                                )
    with K.get_session() as sess:
        builder.add_meta_graph_and_variables(sess=sess,
                                             tags=[tag_constants.SERVING],
                                             signature_def_map={'predict': signature},
                                             #legacy_init_op=legacy_init_op,
                                             clear_devices=True,
                                             )
        builder.save()
        print ('build done!')
    DESTINATION = export_path + '/category.json'
    copyfile(LABELS_FILE, DESTINATION)
```

**Comment by chuqnzhao** [comment] 2020-12-14 09:50
> > @chuqnzhao When I made the change from `serving_defaullt` to 'predict`, the error and warnings remain same.
> > `If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().` based on this warning, can you rebuild the SavedModel and try the conversion? Thanks!
> 
> @jvishnuvardhan
> First of all, thank you for your reply and answer. Could you please share the code of how to convert the meta model file to savedModel to avoid the above error and warnings, thank you!
> I use the following code transformation model, please correct me.
> 
> ```
> def save_pb(export_path_base, model):
>     export_path = get_export_path(export_path_base,VERSIONCONTROLL)
> 
>     print('Exporting trained model to', export_path)
>     builder = tf.saved_model.builder.SavedModelBuilder(export_path)
> 
>     legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
>     signature = predict_signature_def(
>                                 inputs = {'images': model.keras_model.input[0],
>                                             'meta':model.keras_model.input[1],
>                                             'anchor':model.keras_model.input[2]},
>                                 outputs={'detection': model.keras_model.outputs[0],
>                                          'mask':model.keras_model.outputs[3]}
>                                 )
>     with K.get_session() as sess:
>         builder.add_meta_graph_and_variables(sess=sess,
>                                              tags=[tag_constants.SERVING],
>                                              signature_def_map={'predict': signature},
>                                              #legacy_init_op=legacy_init_op,
>                                              clear_devices=True,
>                                              )
>         builder.save()
>         print ('build done!')
>     DESTINATION = export_path + '/category.json'
>     copyfile(LABELS_FILE, DESTINATION)
> ```

Use the following code to remove the warning message, Is the DenseToDenseSetOperation operation not currently supported?
```
converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model("./",input_arrays=['input_image',"input_image_meta","input_anchors"],input_shapes={'input_image' : [1, 1024, 1024, 3],'input_image_meta' : [1, 93],'input_anchors' : [1, 261888, 4]},output_arrays=["mrcnn_detection/Reshape_1", "mrcnn_mask/Reshape_1"],signature_key='predict')
```

**Comment by abattery** [comment] 2021-01-13 01:42
DenseToDenseSetOperation will be supported through Flex. Please use tf-nightly once the necessary change is merged.

**Closed** 2021-01-13 02:34 UTC
Labels: TF 2.3, comp:lite, stat:awaiting tensorflower, type:support

**Comment by abattery** [comment] 2021-01-13 02:35
You can try the tomorrow's tf-nightly version. That will have the Flex delegate, which can support the DenseToDenseSetOperation op.

**Comment by chuqnzhao** [comment] 2021-01-13 02:37
> You can try the tomorrow's tf-nightly version. That will have the Flex delegate, which can support the DenseToDenseSetOperation op.
@abattery 
Ok, I will try. Thanks for your reply.
