### ISSUE TITLE
Convert TensorArray to RaggedTensor

### ISSUE THREAD

**Issue by chris-opendata** [tensorflow/tensorflow#36232] opened 2020-01-27 07:12 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TensorFlow-gpu 1.14+
- Are you willing to contribute it (Yes/No): No.
  Not this stage.

**Describe the feature and the current behavior/state.**
  As tf.keras.model could take a raggedtensor as an input, there is a need to convert a TensorArray to a RaggedTensor.

**Will this change the current api? How?**
   Yes, it requires a new api to TensorArray (say, to_ragged).

**Who will benefit with this feature?**
   This allows the output (no rectangle tensors of same shape) of tf.map_fn of batch-based slicing operation as an input to a tf.keras.layers.Conv2D seamlessly. 

**Any Other info.**
  No.

Thank you

**Comment by edloper** [comment] 2020-05-21 01:33
Extending TensorArray to allow an op similar to stack() that generates a ragged tensor seems reasonable.  But if your goal is to use `tf.map_fn` with ragged outputs, then note that `map_fn` already supports this in `tf_nightly`.  You just need to use `fn_output_signature` to specify what the output of your function looks like.  E.g.:

```
>>> x = tf.constant([5, 3, 0, 4])
>>> tf.map_fn(tf.range, x,
...           fn_output_signature=tf.RaggedTensorSpec(shape=[None], dtype=tf.int32))
<tf.RaggedTensor [[0, 1, 2, 3, 4], [0, 1, 2], [], [0, 1, 2, 3]]>
```

**Comment by leandro-gracia-gil** [comment] 2020-06-03 11:04
I'm hitting this use case too, and in my case the goal is the ragged tensor itself.

I'm writing some code to recursively parse protobufs in the TF graph from their descriptors as part of the input pipeline (using `tf.io.decode_proto`). My input data is highly structured, so the goal is to automatically produce nested named tuples based on the different proto messages that allow me to keep data structured in `tf.data.Dataset` objects.

For repeated message fields I stack together the tensors contained by each message. Since their size depends on the data, I'm forced to use `tf.TensorArray` to do the stacking. However, if the messages I'm stacking happen contain other repeated data with different sizes, regular stacking will fail due to mismatching shapes. For that I need to stack them into a ragged tensor if appropriate.

Since it seems like a reasonable feature with no clear alternative for the cases where you're forced to use `tf.TensorArray`, would it be possible to add it?

**Comment by leandro-gracia-gil** [comment] 2020-06-09 10:23
After many attempts, I've managed to get my use case working with `tf.map_fn` and `fn_output_signature` applied recursively over my proto parsing function. However, in the process I've found a couple of issues worth sharing. @edloper : you might want to take a look.

Let me start with a example that works fine so I can show small variations of it.
```python
x = tf.constant([1, 2, 3], tf.int32)
tf.map_fn(tf.ragged.range, x, fn_output_signature=tf.RaggedTensorSpec([1, None], tf.int32))
```
This correctly returns `<tf.RaggedTensor [[[0]], [[0, 1]], [[0, 1, 2]]]>` as expected.

However, if I pass an empty tensor I get not an exception but a segmentation fault. This seems to happen every time I use a `tf.RaggedTensorSpec` (no matter its shape) in `fn_output_signature` with an empty tensor passed to `tf.map_fn`.
```python
x = tf.zeros([0], tf.int32)
tf.map_fn(tf.ragged.range, x, fn_output_signature=tf.RaggedTensorSpec([1, None], tf.int32))
```

I also found a more subtle issue when using regular tensors.
```python
x = tf.zeros([1], tf.int32)
tf.map_fn(tf.range, x, fn_output_signature=tf.TensorSpec([None], tf.int32))
```
This returns `tf.Tensor([], shape=(1, 0), dtype=int32)`.

However, if the tensor is empty, you're forced to change the shape of the tensor spec.
```python
x = tf.zeros([0], tf.int32)
tf.map_fn(tf.range, x, fn_output_signature=tf.TensorSpec([], tf.int32))
```
This returns `tf.Tensor([], shape=(0,), dtype=int32)` but only if the shape is `[]`. If you leave it as `[None]` you get the following exception:
> ValueError: Tensor's shape (0,) is not compatible with supplied shape (None, None)

This means that the correct `tf.TensorSpec` to pass depends not only on the number of dimensions of the data, but on the data itself. This sounds conceptually wrong to me.

**Comment by kentslaney** [comment] 2020-08-20 12:43
Should we put a note about the segmentation fault in the ragged tensor api documentation/guide somewhere? I ran into the problem @leandro-gracia-gil was having, and it was kind of a hard issue to track down/google. The reason I'm not sure it's worth the effort is because it's not clear how much time the warning will be relevant after the docs update gets merged.

Would it be possible to add tags or something to confirmed GitHub issues that correspond to different documentation pages, then have a "known issues" section at the bottom of docs pages that pulls from the GitHub API? Or at least a link to the open issues for that page? I bet it would be useful, and maybe cut down on duplicate issues. Sorry this is kind of more general than is directly relevant to the thread.

**Comment by edloper** [comment] 2020-08-20 13:45
@leandro-gracia-gil Thanks for pointing out these issues!  I'll look into things further, but it looks to me like the root cause for both the problems you describe may be the same: `tf.TensorArray` is returning tensors with the wrong rank when it can't infer a complete shape for the result.  E.g.:

```python
>>> ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=False, element_shape=[5, 3])
>>> print(ta.stack())  # Good: we get the expected shape.
tf.Tensor([], shape=(0, 5, 3), dtype=int32)
>>> ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=False, element_shape=[None, 3])
>>> print(ta.stack())  # Bad: shape is not consistent w/ `element_shape`.
tf.Tensor([], shape=(0,), dtype=int32)
```

(Note that `ta.stack()` doesn't really have a good way to decide what the size of the second dimension in its return tensor should be -- i.e., it could return a tensor with shape `[0, 0, 3]` or `[0, 1000, 3]`, or `[0, 124131, 3]`, and all of those would be consistent with what we asked for.  But it probably should return a tensor with shape `[0, 0, 3]`.)

The reason that this causes problems for `RaggedTensors` is that the `TensorArray` is giving us a tensor with an unexpected rank, and that's causing problems when we try to unpack it.  (It shouldn't be giving a segfault -- that's always a bug if it occurs in TensorFlow -- but it should be raising an exception.)

@kentslaney Sorry that this issue was hard to track down, and that it's been left unaddressed/unresolved for so long.

**Comment by edloper** [comment] 2020-08-20 14:44
@leandro-gracia-gil I just wrote a fix for the segfault, and it should hopefully show up in nightly later this week.  

Unfortunately, because the underlying kernel that's building the RaggedTensor doesn't have access to the expected shape info, we'll have the same kind of issue that you saw with dense tensors.  I.e., if you do something like:

```
>>> x = tf.zeros([0], tf.int32)
>>> tf.map_fn(lambda x: tf.zeros(x, 10), x, fn_output_signature=tf.RaggedTensorSpec([None, 10], tf.int32))
```

Then the result will be a `RaggedTensor` with shape `[0, 0]`, whereas the result *should* be a `RaggedTensor` with shape `[0, ?, 10]` (where `?` could technically be any value, but should probably default to zero).  Fixing that will can't be done without modifying the API of the RaggedTensorFromVariant kernel, which can't be done in a backwards-compatible way -- so we'll need to introduce a RaggedTensorFromVariantV2 to fix this.  I'll try to get to that eventually, but at least for now you won't get a segmentation fault, and the behavior for RaggedTensors will be consistent w/ the behavior for dense tensors.

**Comment by leandro-gracia-gil** [comment] 2020-08-20 14:47
Sounds great. Thanks!

**Comment by tensorflowbutler** [comment] 2021-02-01 14:12
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:53 UTC
Labels: TF 1.14, TF 1.15, comp:ops, stat:awaiting tensorflower, type:feature
