### ISSUE TITLE
convert to tflite in tensorflow 2.0 not fold batchnorm

### ISSUE THREAD

**Issue by anhtu812** [tensorflow/tensorflow#27707] opened 2019-04-10 08:00 UTC
pip install tf-nightly-2.0-preview==2.0.0.dev20190405, it don't fold BatchNorm therefore it generate error tflife not support BatchNormalization. It must auto fold BatchNorm?
code:
model is tensorflow.keras model have BatchNormalization layer
```
@tf.function(input_signature=[tf.TensorSpec([None,300,300,3], tf.float32, name='fts_input_images'), tf.TensorSpec([], tf.float32, name='fts_input_threshold_confident')])
def func(x, confident_threshold):
	x = model(x)
	x = tf.identity(x, name='fts_output_no_merge')
	x = fn(x, confident_threshold)
	x = tf.identity(x, name='final_fts_output_full')
	return x
concrete_func = func.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
tflite_model = converter.convert()
```

log error:
```
2019-04-12 16:48:44.545659: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-04-12 16:48:44.545815: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-04-12 16:48:44.617968: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:684] Optimization results for grappler item: graph_to_optimize
2019-04-12 16:48:44.618014: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 1313 nodes (0), 1509 edges (0), time = 8.142ms.
2019-04-12 16:48:44.618027: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 1313 nodes (0), 1509 edges (0), time = 3.993ms.
2019-04-12 16:48:45.135108: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-04-12 16:48:45.135255: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-04-12 16:48:45.667690: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:684] Optimization results for grappler item: graph_to_optimize
2019-04-12 16:48:45.667785: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   model_pruner: Graph size after: 1285 nodes (-28), 1493 edges (-16), time = 33.469ms.
2019-04-12 16:48:45.667826: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   implementation_selector: Graph size after: 1285 nodes (0), 1493 edges (0), time = 4.814ms.
2019-04-12 16:48:45.667843: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 1285 nodes (0), 1493 edges (0), time = 4.937ms.
2019-04-12 16:48:45.667857: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   constant folding: Graph size after: 1216 nodes (-69), 1426 edges (-67), time = 194.179ms.
2019-04-12 16:48:45.667880: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   shape_optimizer: Graph size after: 1216 nodes (0), 1426 edges (0), time = 7.638ms.
2019-04-12 16:48:45.667897: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   arithmetic_optimizer: Graph size after: 727 nodes (-489), 1397 edges (-29), time = 37.714ms.
2019-04-12 16:48:45.667912: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   loop_optimizer: Graph size after: 727 nodes (0), 1397 edges (0), time = 7.935ms.
2019-04-12 16:48:45.667927: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   dependency_optimizer: Graph size after: 717 nodes (-10), 1318 edges (-79), time = 14.987ms.
2019-04-12 16:48:45.668006: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   memory_optimizer: Graph size after: 717 nodes (0), 1318 edges (0), time = 80.326ms.
2019-04-12 16:48:45.668021: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   model_pruner: Graph size after: 717 nodes (0), 1318 edges (0), time = 6.515ms.
2019-04-12 16:48:45.668032: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   implementation_selector: Graph size after: 717 nodes (0), 1318 edges (0), time = 2.238ms.
2019-04-12 16:48:45.668043: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 717 nodes (0), 1318 edges (0), time = 2.07ms.
2019-04-12 16:48:45.668054: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   constant folding: Graph size after: 717 nodes (0), 1318 edges (0), time = 30.632ms.
2019-04-12 16:48:45.668065: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   shape_optimizer: Graph size after: 717 nodes (0), 1318 edges (0), time = 5.239ms.
2019-04-12 16:48:45.668075: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   arithmetic_optimizer: Graph size after: 717 nodes (0), 1318 edges (0), time = 32.872ms.
2019-04-12 16:48:45.668086: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   dependency_optimizer: Graph size after: 717 nodes (0), 1318 edges (0), time = 20.462ms.
Traceback (most recent call last):
  File "convert_h5_to_tflite.py", line 192, in <module>
    tflite_model = converter.convert()
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 276, in convert
    **converter_kwargs)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
    input_data.SerializeToString())
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-04-12 16:13:57.979333: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 652 operators, 925 arrays (0 quantized)
2019-04-12 16:13:57.999356: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 652 operators, 925 arrays (0 quantized)
2019-04-12 16:13:58.034861: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 486 operators, 761 arrays (0 quantized)
2019-04-12 16:13:58.058513: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 486 operators, 761 arrays (0 quantized)
2019-04-12 16:13:58.074463: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 486 operators, 761 arrays (0 quantized)
2019-04-12 16:13:58.101510: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 32761600 bytes, theoretical optimal value: 28800000 bytes.
2019-04-12 16:13:58.107182: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, BATCH_TO_SPACE_ND, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FLOOR_DIV, FLOOR_MOD, GATHER, GREATER, GREATER_EQUAL, LOGICAL_AND, LOGICAL_NOT, LOGISTIC, MAXIMUM, MEAN, MINIMUM, MUL, PACK, RANGE, REDUCE_ANY, REDUCE_MAX, REDUCE_PROD, RESHAPE, RSQRT, SHAPE, SPACE_TO_BATCH_ND, SQUARED_DIFFERENCE, STRIDED_SLICE, SUB, SUM, TILE, TOPK_V2. Here is a list of operators for which you will need custom implementations: BatchNormalization.
Traceback (most recent call last):
  File "/docker_environment/home/docker/anaconda3/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/docker/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/docker/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, BATCH_TO_SPACE_ND, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FLOOR_DIV, FLOOR_MOD, GATHER, GREATER, GREATER_EQUAL, LOGICAL_AND, LOGICAL_NOT, LOGISTIC, MAXIMUM, MEAN, MINIMUM, MUL, PACK, RANGE, REDUCE_ANY, REDUCE_MAX, REDUCE_PROD, RESHAPE, RSQRT, SHAPE, SPACE_TO_BATCH_ND, SQUARED_DIFFERENCE, STRIDED_SLICE, SUB, SUM, TILE, TOPK_V2. Here is a list of operators for which you will need custom implementations: BatchNormalization.
```

**Comment by achandraa** [comment] 2019-04-11 10:08
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gargn** [comment] 2019-04-15 20:28
The issue should have been resolved within the last week. Please try running your code using the latest nightly. If that doesn't work, please update this issue with the model or a minimally reproducible example (the weights don't need to be correct).

Additionally, the converter functionality was changed in https://github.com/tensorflow/tensorflow/commit/312222d2a0657d4e0086ec0add4331063d0b2264. `from_concrete_function` is now `from_concrete_functions`. `from_keras_model` and `from_saved_model` have been added.

**Comment by gargn** [comment] 2019-04-19 21:35
If this is a 1.X Keras model, then it should work after https://github.com/tensorflow/tensorflow/commit/c767cbf14c6133e6cfc782bc373b0ef0f4b1e2c6.

**Comment by achandraa** [comment] 2019-04-22 05:05
@anhtu812 - Is this still an issue ? Please let us know. Thanks!

**Comment by anhtu812** [comment] 2019-04-23 02:19
in version: pip install tf-nightly-2.0-preview==2.0.0.dev20190422 have new errors
```
Traceback (most recent call last):
  File "convert_h5_to_tflite.py", line 221, in <module>
    tflite_model = converter.convert()
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 289, in convert
    self._funcs[0])
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 133, in convert_variables_to_constants_v2
    "data": tensor.numpy(),
AttributeError: 'Tensor' object has no attribute 'numpy'
```
when i run: out = func(tf.ones((2,300,300,3)), 0.5), it out error relate to Conv2D with dilation_rate!=1 (forward_6_1b_conv2D). It can relate to https://github.com/tensorflow/tensorflow/issues/27711
```
Traceback (most recent call last):
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: forward_6_1b_conv2D/stack:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_h5_to_tflite.py", line 163, in <module>
    out = func(tf.ones((2,img_size,img_size,3)), 0.5)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 454, in __call__
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 566, in _filtered_call
    (t for t in nest.flatten((args, kwargs), expand_composites=True)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 646, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 422, in call
    ctx=ctx)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 70, in quick_execute
    raise core._SymbolicException
tensorflow.python.eager.core._SymbolicException
```

**Comment by gargn** [comment] 2019-04-23 20:24
@anhtu812 Can you provide the `model` in your code so that I can reproduce your error? Or provide a minimal example that reproduces your error?

**Comment by anhtu812** [comment] 2019-04-24 02:52
key of error is BatchNormalization(scale=False)
```
import tensorflow as tf

input_data = tf.keras.layers.Input(name='fts_input', shape=(None,None,3), dtype='float32')
x = tf.keras.layers.Conv2D(filters=3, kernel_size=3, dilation_rate=2)(input_data)
x = tf.keras.layers.BatchNormalization(scale=False)(x)
model = tf.keras.models.Model(inputs=[input_data], outputs=x)

img_size = 200
@tf.function(input_signature=[tf.TensorSpec([None,img_size,img_size,3], tf.float32, name='fts_input_images'), tf.TensorSpec([], tf.float32, name='fts_input_threshold_confident')])
def func(x, confident_threshold):
	x = model(x)
	return x
concrete_func = func.get_concrete_function()

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
path = "model.tflite"
open(path, "wb").write(tflite_model)
```

**Closed** 2019-04-24 18:23 UTC
Labels: 2.0, comp:lite, type:support
