### ISSUE TITLE
Tensorflow does not work with python 3.7 when using Virtualenv

### ISSUE THREAD

**Issue by clankill3r** [tensorflow/tensorflow#22153] opened 2018-09-07 22:54 UTC
I am not sure where it goes wrong, but after reading tons of posts online I figured the combination tensor flow, Virtualenv en python 3.7 is not valid on Mac OSX.
I use python3.6 now and it is fine.
Sorry I can not provide more info, I'm broken by the struggle and want to sleep and forget about it.

**Comment by tensorflowbutler** [comment] 2018-09-08 06:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by gunan** [comment] 2018-09-11 19:55
Virtualenv is a red herring, tensorflow does not yet work with python 3.7
We are waiting for all of our dependencies to merge python 3.7 support.

Closing as duplicate of https://github.com/tensorflow/tensorflow/issues/20517

**Closed by gunan** 2018-09-11 19:55 UTC
Labels: stat:awaiting response

**Comment by zw232618** [comment] 2018-09-13 02:45
emm

**Comment by zw232618** [comment] 2018-09-13 02:47
emm

**Comment by zw232618** [comment] 2018-09-13 02:47
emm

**Comment by zw232618** [comment] 2018-09-13 03:03
emm

**Comment by zw232618** [comment] 2018-09-13 03:03
> emm

emm

**Comment by zw232618** [comment] 2018-09-13 03:03
emm
