### ISSUE TITLE
Value of sqrt(2) is calculated incorrectly and inconsistently

### ISSUE THREAD

**Issue by tarokiritani** [tensorflow/tensorflow#31408] opened 2019-08-07 11:36 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): not known
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): not known
- CUDA/cuDNN version: 10.0/7.6.0
- GPU model and memory: Tesla K-80 12gb

**Describe the current behavior**
I just computed sqrt(2) 100 times in google colab. The values are computed inconsistently, and a bit incorrectly, in a single tensor.

**Describe the expected behavior**
sqrt(2) should be computed the same way every time.

**Code to reproduce the issue**
```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

tf.enable_eager_execution()

sqrt2s = tf.sqrt(tf.constant([2.0]*100, dtype=tf.float32))
print(sqrt2s)
print(sqrt2s[0].numpy())
print(sqrt2s[-1].numpy())
print(sqrt2s[0].numpy() == sqrt2s[-1].numpy())
```
The results:
```
tf.Tensor(
[1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134
 1.4142134 1.4142134 1.4142134 1.4142134 1.4142134 1.4142135 1.4142135
 1.4142135 1.4142135], shape=(100,), dtype=float32)
1.4142134
1.4142135
False
```
**Other info / logs**
The notebook is here:
https://colab.research.google.com/drive/1PQp2KtFUoaUEHETrIUne-J1Cu2blg2cG

**Comment by mihaimaruseac** [comment] 2019-08-07 14:02
Also confirmed on TF2.0-beta.

**Comment by gowtham-kp** [comment] 2019-08-07 20:09
Can reproduce this issue. Please find the github gists for [TF1.14](https://colab.sandbox.google.com/gist/gowtham-kp/ebc07211502d3ce2b8f0e2762e342ef7/untitled70.ipynb) and [TF2.0](https://colab.sandbox.google.com/gist/gowtham-kp/13031e254142d509da0dc9998047c239/untitled72.ipynb)

**Comment by alextp** [comment] 2019-08-13 22:53
@rmlarsen is this the scalar vs vectorized path difference we saw in the other bug?

**Comment by yqtianust** [comment] 2019-08-14 09:00
I tested in GPU, there is no such problem.
However, this problem occurs when I use CPU (9900K).

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 LTS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
TensorFlow installed from (source or binary): pip3 install tensorflow-gpu==1.14
TensorFlow version (use command below): 1.14.0
Python version: 3.6.8
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source): not known
CUDA/cuDNN version: 9.0/7.6.1
GPU model and memory: RTX 2080Ti

**Comment by yqtianust** [comment] 2019-08-14 09:28
If we use `dtype=tf.float16`, there is no such problem.

**Comment by gadagashwini** [comment] 2020-03-13 11:01
This issue is still replicating with Tf2.1 and tf-nightly==2.2.0.dev20200313.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/a0f428a577715b5da0277410c610da51/untitled455.ipynb). Thanks

**Comment by saikumarchalla** [comment] 2020-04-14 09:00
Both numbers are correct to within 1 ulp (unit in last place). The inconsistency is due to the difference between the vectorized and scalar path in the underlying Eigen code. In short, please don't rely on exact equality of floating point numbers.

Closing this issue as it was the intended behavior. Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by saikumarchalla** 2020-04-14 09:00 UTC
Labels: TF 1.14, TF 2.0, TF 2.1, comp:ops, type:bug

**Comment by yqtianust** [comment] 2020-04-22 03:01
@saikumarchalla Thanks. 
A similar issue is #31619. It seems running the above code using GPU has no such issues. 

What the meaning of "the difference between the vectorized and scalar path in the underlying Eigen code"? Is there any reference? I want to learn more about this. Thanks.
