### ISSUE TITLE
TF 2.1: ModelCheckpoint save best model fails

### ISSUE THREAD

**Issue by johntmyers** [tensorflow/tensorflow#43540] opened 2020-09-24 13:15 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**

Mac OS 10.15.16

```
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v2.1.0-rc2-17-ge5bf8de410 2.1.0
```

**Describe the current behavior**

When trying to use `tf.keras.callbacks.ModelCheckpoint` a crash occurs when setting `save_best_only` to `True`

**Describe the expected behavior**

Training should not crash between epochs

**NOTE**: Upgrading to TF 2.3 does not cause this to happen. However the 2.1 docs still say this option should work.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/18jS5tqPo-PRaoxR1qSMMlgUjyM0sIll1?usp=sharing

**Comment by amahendrakar** [comment] 2020-09-25 10:37
@johntmyers,
I was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/f19bd537f51e19c32c69c25fa96e90c1/43540-2-1.ipynb), and as you mentioned the issue seems to be fixed with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/308b04bce2d7ed59a70859ac72c6dee7/43540-2-3.ipynb). In this case, could you please update TensorFlow to the latest version.


Also, I was able to use `tf.keras.callbacks.ModelCheckpoint` with `save_best_only` set to `True` on TensorFlow 2.1. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a4b2da4c26698ca78da5b2af163858be/modelcheckpoint.ipynb). Thanks!

**Closed** 2020-10-09 12:11 UTC
Labels: TF 2.1, comp:keras, stalled, stat:awaiting response, type:support
