### ISSUE TITLE
MirroredStrategy and Optimizer Compatibility

### ISSUE THREAD

**Issue by dcyoung** [tensorflow/tensorflow#22550] opened 2018-09-26 20:48 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, duplicated the minimal code from documentation snippet [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute#example-with-keras-api)

But the included [keras_mnist.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/examples/keras_mnist.py) example is broken as well.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Docker container `tensorflow/tensorflow:1.11.0-rc2-gpu-py3`
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
2 x 1080ti
- **Exact command to reproduce**:

### Describe the problem

[keras_mnist.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/examples/keras_mnist.py) example seems to break. Investigating further... 

Optimizers other than `tf.train.GradientDescentOptimizer` are not working with `MirroredStrategy` for Keras models as shown in this official [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute#example-with-keras-api)

### Source code / logs
**Setup**, copied from the [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute#example-with-keras-api):

```python
inputs = tf.keras.layers.Input(shape=(1,))
predictions = tf.keras.layers.Dense(1)(inputs)
model = tf.keras.models.Model(inputs=inputs, outputs=predictions)

features = tf.data.Dataset.from_tensors([1.]).repeat(10000).batch(10)
labels = tf.data.Dataset.from_tensors([1.]).repeat(10000).batch(10)
train_dataset = tf.data.Dataset.zip((features, labels))

distribution = tf.contrib.distribute.MirroredStrategy()
```

**Then, this works**:
```python
model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.2),
              distribute=distribution)
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```

But, **Keras optimizers** don't seem to work:
```python
model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.SGD(lr=0.2, momentum=0.9),
              distribute=distribution)
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```

and these **Tensorflow Optimizers** are throwing errors as well:

```python
model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.AdamOptimizer(learning_rate=0.2),
              distribute=distribution)
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```

```python
model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.MomentumOptimizer(learning_rate=0.2, momentum=0.9),
              distribute=distribution)
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```

```python
model.compile(loss='categorical_crossentropy',
              optimizer=tf.train.RMSPropOptimzier(learning_rate=0.2),
              distribute=distribution)
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```

Error looks like:
```bash
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1590, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 125, in fit_loop
    orig_model_weights = model.get_weights()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 483, in get_weights
    return backend.batch_get_value(weights)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 2717, in batch_get_value
    return get_session().run(tensors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 465, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 710, in _initialize_variables
    variables = _get_variables(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 704, in _get_variables
    variables.update(opt.optimizer.variables())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 785, in variables
    optimizer_variables = [v for v in self._non_slot_variables()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 786, in <listcomp>
    if _from_current_graph(v)]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 779, in _from_current_graph
    return variable.op.graph is current_graph
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 305, in op
    return self.get().op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 73, in get
    (device, self._index.keys(), device_util.current())), e)
  File "<string>", line 3, in raise_from
ValueError: Device /replica:0/task:0/device:CPU:0 not found in dict_keys(['/replica:0/task:0/device:GPU:1', '/replica:0/task:0/device:GPU:0']) (current device )
```

**Comment by tksj09** [comment] 2018-09-27 08:45
I meet same problem.
I specify the cpu
strategy = tf.contrib.distribute.MirroredStrategy(
   ['/device:CPU:0', '/device:GPU:0', '/device:GPU:1'])
the code can be run
but GPU:0 Util more than 90%
GPU:1 Util is lower

**Comment by erwa** [comment] 2018-10-15 16:20
Hi @anj-s ,

Could you tell me which commit fixed this issue? Also, is the fix in 1.12.0-rc0?

**Comment by anj-s** [comment] 2018-10-28 23:54
@erwa The commit that fixed this issue is: 6ebe9baae06c06d0a70a424a55c78f5af07b49f7
This fix is in 1.12.0-rc0. 

Closing this issue now. Please reopen this issue if needed. Thanks!

**Closed by anj-s** 2018-10-28 23:54 UTC
Labels: comp:dist-strat

**Comment by oleksandrlazariev** [comment] 2019-02-07 10:22
the issue is still present in release version 1.12.0. I've just called `K.get_session()` inside of an estimator hook in  the `end` method

**Comment by ssstuvz** [comment] 2019-03-04 09:08
Still the same problem in 1.13.0-rc0.

**Comment by kariya2** [comment] 2019-03-14 13:51
Have this issue in 1.12.0.. Any tips on how to get around this?
