### ISSUE TITLE
Gradients for tf.py_function with mixed arguments

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#38870] opened 2020-04-24 14:02 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.3
- TensorFlow installed from (source or binary): conda binary
- TensorFlow version (use command below): 2.1
- Python version: 3.7

**Describe the current behavior**
gradient calculation throws an error if a py_function is used that has both integer and floating point inputs/outputs.

**Describe the expected behavior**
Gradients with respect to all integers should be zero/None, and others should be correctly calculated.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

def pf(x, y):
    return x ** 2, y ** 2

def pyf(x, y):
    return tf.py_function(pf, [x, y], [tf.int32, tf.float32])

x = tf.constant(5)
v = tf.Variable(0.5)
with tf.GradientTape() as tape:
    y, m = pyf(x, v)
    z = tf.cast(y, tf.float32) * m

print(tape.gradient(z, v))
```
When calling `pf`, gradient computation works, but for `pyf` we get first a warning and then an error. 

The problematic code seems to be in `script_ops.py`:
```
@ops.RegisterGradient("EagerPyFunc")
def _EagerPyFuncGrad(op, *dy):
  """Computes the gradient of an EagerPyFunc."""

  token = op.get_attr("token")

  def eagerly_executed_grad(*dy):
    tape, eager_inputs, eager_outputs = tape_cache.pop(compat.as_bytes(token))
    return tape.gradient(eager_outputs, eager_inputs, output_gradients=dy)

  with ops.control_dependencies(op.outputs):
    return _internal_py_func(
        func=eagerly_executed_grad,
        inp=dy,
        Tout=[tensor.dtype for tensor in op.inputs],
        eager=True,
        is_grad_func=True)
```

**Comment by Saduf2019** [comment] 2020-04-27 05:05
i am able to replicate the issue please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e42e9f9409902a15edef04ef4eb9b3b2/38870.ipynb)

**Comment by Saduf2019** [comment] 2020-04-27 05:30
@ngc92 
i ran your code in nightly and do not face any error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/9ef6582d4190888740409bc944dae316/38870.ipynb)
the error faced in 2.1 is as per [this gist](https://colab.sandbox.google.com/gist/Saduf2019/cbed748edb5e596abacd846dfcc28b32/untitled155.ipynb), can you please confirm.

**Comment by ngc92** [comment] 2020-04-27 07:51
yes, this is the expected error. This is strange, because as far as I can see the code for `def _EagerPyFuncGrad` has not been changed. Do you know if there is already a test case for this behaviour?

**Comment by alextp** [comment] 2020-04-27 17:10
if it doesn't reproduce in nightly let's close the issue

**Closed by alextp** 2020-04-27 17:10 UTC
Labels: TF 2.1, comp:ops, type:bug

**Comment by ngc92** [comment] 2020-04-27 17:24
does a test case for this behaviour already exist?

**Comment by AroMorin** [comment] 2020-07-06 23:17
I see a similar issue, also using a pyfunc and get the error message "Tensor is unhashable. Instead, use tensor.ref() as the key". It seems to be raised also from within "script_ops.py:363 _EagerPyFuncGrad". I don't have code to reproduce the issue. I'm using tf 2.2.0 on Ubuntu Linux.
