### ISSUE TITLE
Problem with tf.keras.metrics.Mean

### ISSUE THREAD

**Issue by quantitative-technologies** [tensorflow/tensorflow#39421] opened 2020-05-11 17:24 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
From source
- TensorFlow version (use command below):
v2.1.0-0-ge5bf8de410 2.1.0
- Python version:
3.7
- Bazel version (if compiling from source):
? (built a while ago)
- GCC/Compiler version (if compiling from source):
? 
- CUDA/cuDNN version:
10.2
- GPU model and memory:
GeForce GTX 1080 8G

**Describe the current behavior**

The following code:

    tf.keras.metrics.Mean(name='train_loss')

results in the error:

    tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse

This same behaviour has been observed many times, for example:

https://stackoverflow.com/questions/61321380/gpu-out-of-memory-error-just-by-declaring-tf-keras-metrics

There is also the (same?) issue which should not have been closed:

https://github.com/tensorflow/tensorflow/issues/38518

In my case, the code was working and then began giving this error even though no code changes were made. Moreover, this persisted even when I killed all python processes first.

**Comment by amahendrakar** [comment] 2020-05-11 17:52
@quantitative-technologies,
I was able to run the code without any issues on [TF v2.1](https://colab.research.google.com/gist/amahendrakar/6169c4eab69d248cb83950eb17431d20/39421-2-1.ipynb) and [TF v2.2](https://colab.research.google.com/gist/amahendrakar/45eab1d9eb03ffa7a08cab3efd28da3c/39421.ipynb). Please find the attached gist. 

Could you please check if you are facing the same error in a virtual environment. Thanks!

**Comment by quantitative-technologies** [comment] 2020-05-11 18:02
I was running in a virtual environment when I made this bug report.

I just tried starting the python console from my virtualenv, and running the two lines of code from your gist. Here is the complete output:

>>> import tensorflow as tf
>>> tf.__version__
'2.1.0'
>>> tf.keras.metrics.Mean(name='train_loss')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py", line 460, in __init__
    reduction=metrics_utils.Reduction.WEIGHTED_MEAN, name=name, dtype=dtype)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py", line 296, in __init__
    'total', initializer=init_ops.zeros_initializer)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py", line 276, in add_weight
    aggregation=aggregation)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 446, in add_weight
    caching_device=caching_device)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 744, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 142, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2596, in default_variable_creator
    shape=shape)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1557, in _init_from_args
    graph_mode=self._in_graph_mode)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 232, in eager_safe_variable_handle
    shape, dtype, shared_name, name, graph_mode, initial_value)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 164, in _variable_handle_from_shape_and_dtype
    math_ops.logical_not(exists), [exists], name="EagerVariableNameReuse")
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_logging_ops.py", line 55, in _assert
    _ops.raise_from_not_ok_status(e, name)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse


This is an intermittent error. I believe it will work for a while if I restart my system.

**Comment by quantitative-technologies** [comment] 2020-08-18 23:20
No, but that is because I am exclusively using Tensorflow 2 now.

**Comment by Saduf2019** [comment] 2020-08-21 06:35
@quantitative-technologies,
In that case can we move this issue to closed status.

**Comment by pavithrasv** [comment] 2020-08-25 20:36
Marking as closed as the issue is not reproducible in TF 2. Please feel free to comment on the issue if there are more questions.

**Closed by pavithrasv** 2020-08-25 20:36 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug
