### ISSUE TITLE
"import_meta_graph" fails

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#28131] opened 2019-04-25 01:49 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.0 with cuDNN7
- GPU model and memory: GTX1080 with 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
error occurs when calling `import_meta_graph`

**Describe the expected behavior**

**Code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow.contrib.tensorrt as trt

meta_graph_path = "bert-eng/model.ckpt-7300.meta"
graph = tf.Graph()
with graph.as_default():
    with tf.Session() as sess:

        saver = tf.train.import_meta_graph(meta_graph_path) // error occurs here
```
When I run the above code, I get error at line:
```python
saver = tf.train.import_meta_graph(meta_graph_path) // error occurs here
```

**Other info / logs**
stack trace:
```
2019-04-25 10:40:52.107550: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-25 10:40:52.119933: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099880000 Hz
2019-04-25 10:40:52.122488: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5431820 executing computations on platform Host. Devices:
2019-04-25 10:40:52.122547: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "tf_to_trt.py", line 15, in <module>
    saver = tf.train.import_meta_graph(meta_graph_path)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/msl/.virtualenvs/venv_waveglow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'ExperimentalFunctionBufferingResource'
```

**Comment by jvishnuvardhan** [comment] 2019-04-26 02:43
@ThisIsIsaac Could create a reproducible code (a gist or colab) to reproduce the issue. The above code is not complete. Thanks!

**Comment by tensorflowbutler** [comment] 2019-05-10 13:27
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-05-13 17:25
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-13 17:25 UTC
Labels: comp:ops, contrib, stat:awaiting response, type:bug/performance

**Comment by prateethvnayak** [comment] 2019-06-13 17:55
Similar Issues [#27752](https://github.com/tensorflow/tensorflow/issues/27752#issue-432019580)
[#29751](https://github.com/tensorflow/tensorflow/issues/29751#issue-455874429)
