### ISSUE TITLE
No event files found within logdir in tensorboard

### ISSUE THREAD

**Issue by MyAusweis** [tensorflow/tensorflow#8129] opened 2017-03-06 15:34 UTC
Dear Sir/mam

I confuse how to display using tensorboard. here is my program
graph = "d://"
import tensorflow as tf

# Build our graph nodes, starting from the inputs
a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")
c = tf.multiply(a,b, name="mul_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")

# Open up a TensorFlow Session
sess = tf.Session()

# Execute our output node, using our Session
output = sess.run(e)

# Open a TensorFlow SummaryWriter to write our graph to disk
writer = tf.summary.FileWriter(graph, sess.graph)

# Close our SummaryWriter and Session objects
writer.close()
sess.close()

the events file has been created in drive D (i'm using windows 8.1, and tensorflow 1.0). and i found it when using explorer

When I type 
tensorboard --inspect --logdir ="d:\\"
tensorboard --inspect --logdir ="d:\"
tensorboard --inspect --logdir ="d://"
tensorboard --inspect --logdir ="d:/"

tensorboard --inspect --logdir ='d:\\'
tensorboard --inspect --logdir ='d:\'
tensorboard --inspect --logdir ='d://'
tensorboard --inspect --logdir ='d:/'

the result are : No event files found within logdir, 

pls tell me why this happened.

Thx

**Comment by prb12** [comment] 2017-03-06 17:25
Closing as a duplicate of #7856. 
Please reopen if the workaround in that issue doesn't fix the problem.

**Closed by prb12** 2017-03-06 17:25 UTC

**Comment by MyAusweis** [comment] 2017-03-07 02:24
Dear prb12

I already changed the windows command prompt to d: and write like this

d:>tensorboard --logdir = D:\ 
but the data still not shown, even in drive D there are several events data.

Thx

**Comment by prb12** [comment] 2017-03-07 04:30
Could you please reread the comment from mrry@ in the issue I referenced which explains that file name parsing interprets the leading drive letter component as a ‘tag’ and hence you will need to prefix your pathname with an extra ‘tag:’ to workaround this on Windows.

On March 6, 2017 at 6:25:59 PM, MyAusweis (notifications@github.com) wrote:

Dear prb12

I already changed the windows command prompt to d: and write like this

d:>tensorboard --logdir = D:\
but the data still not shown, even in drive D there are several events data.

Thx

**Comment by prajwalmv** [comment] 2017-12-10 01:16
(i) Open a command prompt in admin mode 
(ii) Change your directory to where your event files are located;
 run tensor board works with the appropriate logdir, works beautifully !
