### ISSUE TITLE
problem with hashes to install tensorflow

### ISSUE THREAD

**Issue by miguel1396** [tensorflow/tensorflow#27794] opened 2019-04-12 17:02 UTC
Has anyone had this problem when installing tensorflow? How did they solve it? Thank you

THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp35-none-linux_armv7l.whl#sha256=6c00dd13db0791e83cb08d532f007cc7fd44c8d7b52662a4a0065ac4fe7ca18a:
        Expected sha256 6c00dd13db0791e83cb08d532f007cc7fd44c8d7b52662a4a0065ac4fe7ca18a
             Got        b3233a35689ec7246f10b55ba82e10a951f9e4ee6205cfb77d90a6fc7b959b76

**Comment by xNebula69** [comment] 2019-04-14 21:59
Having the same problem here, not found a fix yet

**Comment by muddham** [comment] 2019-04-16 12:10
@miguel1396 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-18 00:10
@miguel1396 Could you try downloading tensorflow from [pypi.org](https://pypi.org/project/tensorflow/), [GitHub source](https://github.com/tensorflow/tensorflow) or [Google api](https://www.tensorflow.org/install/pip#package-location). *.whl files are available with the Googleapi site. Thanks!

**Comment by vlasov01** [comment] 2019-04-19 02:32
I had the same issue. Run it again and was able to install it without any errors.

**Comment by shahruk10** [comment] 2019-04-21 10:34
I ran into the same problem but running only `pip install tensorflow`  worked. I was trying to install on the raspberry pi

**Comment by jvishnuvardhan** [comment] 2019-05-01 22:45
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!

**Closed by jvishnuvardhan** 2019-05-01 22:45 UTC
Labels: stat:awaiting response, type:build/install

**Comment by jwpalermo28** [comment] 2019-06-06 00:26
I have the same issue...

**Comment by badcab** [comment] 2019-06-26 23:45
I was having this issue, I eventually downloaded the whl file with wget

`wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp35-none-linux_armv7l.whl`

 I kept getting errors in the download, example shown below

`Read error at byte 88145920/92452292 (A TLS packet with unexpected length was received.). Retrying.`

Eventually the file finished after throwing the above error a few times and I was able to install it locally using the command below

`pip install tensorflow-1.13.1-cp35-none-linux_armv7l.whl`

I also had the same problem with a few smaller packages but got those to work by trying again. I think this problem is caused by a less than idea network connection.

**Comment by AeroWRX** [comment] 2019-08-16 22:16
tensorflow "these packages do not match the hashes from the requirements file"

I just ran pip3 install tensorflow on a fresh new board and I get this error again now.... it's  August 2019

**Comment by BeamCtrl** [comment] 2019-08-18 07:38
One up! I got this error on both ”pip install tensorflow” and ”pip3 install tensorflow”

**Comment by InputMoe** [comment] 2019-08-25 11:31
Another One up! I also have the error with "pip3 install tensorflow"

**Comment by chrisnurse** [comment] 2019-09-08 11:19
I get the same HASH problem 8th September 2019

(cv2_env) pi@pi-hub:~$ pip3 install tensorflow
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tensorflow
  Downloading https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp37-none-linux_armv7l.whl (93.2MB)
    8% |???                             | 7.9MB 6.9kB/s eta 3:27:43
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp37-none-linux_armv7l.whl#sha256=25f4ff027beec1e568baf8e90a07bad59d354560533d6b37318b9efeb70beeb1:
        Expected sha256 25f4ff027beec1e568baf8e90a07bad59d354560533d6b37318b9efeb70beeb1
             Got        04e0bd34cbb02f1b9cbdc63d457d0308f1591e4f0b286b0aa2c22ac64cb83b72

**Comment by mihaimaruseac** [comment] 2019-09-08 14:10
These seem to be issues associated with Pypi or the network between you and them (potential man in the middle changing the files is potential). Not a TensorFlow issue

**Comment by soswow** [comment] 2020-04-25 10:08
Same problem. Downloading with `wget` and checking with sha256sum confirms same has as was previously "expected". So I feel safe and do what suggested above - manual install

**Comment by maximveksler** [comment] 2020-07-30 16:32
#13 22.05 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
#13 22.05     tensorflow-gpu==1.15.* from https://files.pythonhosted.org/packages/32/d9/f977cb032856d7f65cc42541da1ff12dafc4ff35fddb819836cf5c4cab60/tensorflow_gpu-1.15.3-cp37-cp37m-manylinux2010_x86_64.whl#sha256=1fe69cc4c60f4cce9af9594bfc55970805a76c613b257ba2f7f1defc8d53b201 (from -r requirements-gpu.txt (line 17)):
#13 22.05         Expected sha256 1fe69cc4c60f4cce9af9594bfc55970805a76c613b257ba2f7f1defc8d53b201
#13 22.05              Got        a73c34b80b19f7905f54d787c877b738c670111fbdcdc86ec4a50821784fbcd8
#13 22.05 
#13 ERROR: executor failed running [/bin/bash -c python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements-gpu.txt]: runc did not terminate sucessfully

**Comment by mihaimaruseac** [comment] 2020-07-30 21:55
@maximveksler what is the contents of `requirements-gpu.txt`?

```
[tf] λ sha256sum *
1344a3541e19e5b5cfde1c7b71fb02cb2f593262841a0e064df033619137f609  tensorflow_gpu-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl
bd68d17b14c91f62c9dd031fe02f57cb9f4b4028aef6e83141885120b285fcdd  tensorflow_gpu-1.15.2-cp37-cp37m-manylinux2010_x86_64.whl
1fe69cc4c60f4cce9af9594bfc55970805a76c613b257ba2f7f1defc8d53b201  tensorflow_gpu-1.15.3-cp37-cp37m-manylinux2010_x86_64.whl
```

There is no `a73c34b80b19f7905f54d787c877b738c670111fbdcdc86ec4a50821784fbcd8` hash. Its only presence could be explained by someone tampering with the network. This is not a TF issue, it should not be reported here

**Comment by rmanak** [comment] 2020-08-09 00:59
same problem now in tensorflow 2.3

**Comment by rmanak** [comment] 2020-08-09 01:00
17:53:26  ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
17:53:26      tensorflow from https://files.pythonhosted.org/packages/97/ae/0b08f53498417914f2274cc3b5576d2b83179b0cbb209457d0fde0152174/tensorflow-2.3.0-cp36-cp36m-manylinux2010_x86_64.whl#sha256=5c9f9a36d5b4d0ceb67b985486fe4cc6999a96e2bf89f3ba82ffd8317e5efadd:
17:53:26          Expected sha256 5c9f9a36d5b4d0ceb67b985486fe4cc6999a96e2bf89f3ba82ffd8317e5efadd
17:53:26               Got        75b3e7adccf80b3e638be35a8b244a69a3d34089e4ade11c7551ab55d139dfd0

**Comment by mihaimaruseac** [comment] 2020-08-09 01:14
The issue is not from TF or from PyPI. You either have a spotty internet connection, a bad package cache or someone mitm-ing.

TF team cannot do anything.

**Comment by maximveksler** [comment] 2020-08-09 10:32
> The issue is not from TF or from PyPI. You either have a spotty internet connection, a bad package cache or someone mitm-ing.
> 
> TF team cannot do anything.

This clearly makes sense, but the problem is it's occurring only with TF dependency (maybe) because of the large file size of the package. In our case it's happening on Github Actions hosted CI worker, so unless we assume MITM malice actions by a 3rd party player it could perhaps indicate a bug that reproduces when tf is involved. It's also not consistently failing, which makes it harder to catch for obvious reasons.

**Comment by mihaimaruseac** [comment] 2020-08-09 16:24
We are aware of the huge size of the pip package. I will add this item to the tracker too to further motivate reduction of the pip's size.

Meanwhile, I think using ` --no-cache-dir  ` during `pip install` might alleviate this issue, at the cost of longer time spent in downloading the dependency.

**Comment by dasunNimantha** [comment] 2021-01-24 08:25
> We are aware of the huge size of the pip package. I will add this item to the tracker too to further motivate reduction of the pip's size.
> 
> Meanwhile, I think using `--no-cache-dir ` during `pip install` might alleviate this issue, at the cost of longer time spent in downloading the dependency.

This worked for me

**Comment by bhavika** [comment] 2021-02-26 01:04
> Meanwhile, I think using `--no-cache-dir ` during `pip install` might alleviate this issue, at the cost of longer time spent in downloading the dependency.

This worked for me as well.
