### ISSUE TITLE
[Tensorflow Lite] GPU delegate problem, SSD-mobilenetV2 converted from object detection API

### ISSUE THREAD

**Issue by anywhere133** [tensorflow/tensorflow#48044] opened 2021-03-24 14:56 UTC
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: i used object detection demo app, some change for gpu delegate
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 64 bit
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: emulator : Google Pixel 4  (android 10.0 / 11.0)
    and real device : Samsung Galuxy Note 10+ / Android 11.0
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 2.4.1
-   **Python version**: 3.6
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:11.0 / 8.0
-   **GPU model and memory**: Nvidia 1070 8gb, 32gb
-   **Exact command to reproduce**:

### Describe the problem
I use custom model from Object Detection API Model Zoo, its SSD-Moblienet-v2-fpnlite-640x640.
my trained model run Object detection demo app successfully, but i want to run demo app on GPU with my trained model.

So, I change some demo app code, and run it on real device.
with some error message, the application is shutdown.

I Just wonder PostProcessing operation, in my model is not supported?
or something other problem?

### Source code / logs
demo app : https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

some code change, lib_interpreter/TFLiteObjectDetecionAPIModel.java
like this
```
    CompatibilityList compatList = new CompatibilityList();
    try {
      Interpreter.Options options = new Interpreter.Options();
      if (compatList.isDelegateSupportedOnThisDevice()){
        System.out.println("This walking on GPU!");
        GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
        GpuDelegate gpuDelegate = new GpuDelegate(delegateOptions);
        options.addDelegate(gpuDelegate);
      } else {
        System.out.println("This walking on CPU!");
      }

      options.setNumThreads(NUM_THREADS);
      options.setUseXNNPACK(true);
      d.tfLite = new Interpreter(modelFile, options);
      d.tfLiteModel = modelFile;
      d.tfLiteOptions = options;
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
```

error logs
```
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
I/System.out: This walking on GPU!
I/tflite: Created TensorFlow Lite delegate for GPU.
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created 0 GPU delegate kernels.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 12798
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
    154 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
    TfLiteGpuDelegate Init: PACK: Tensor "tfl.pack" has bad input dims size: 5.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 155 (TfLiteGpuDelegateV2) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:162)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:168)
        at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:453)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
        at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
        at android.view.TextureView.getTextureLayer(TextureView.java:402)
and more...
```

Searching very hard, but I can't found solution.

**Comment by abattery** [comment] 2021-03-24 20:33
@impjdi could you take a look?

**Comment by impjdi** [comment] 2021-03-24 21:54
never knew we support `PACK`.  the reason why it failed is stated:

> TfLiteGpuDelegate Init: PACK: Tensor "tfl.pack" has bad input dims size: 5.

IIRC we don't support 5D tensors in OpenGL.  We might support 5D tensors in OpenCL for some operations.

**Comment by anywhere133** [comment] 2021-03-24 23:53
thank you for answering,
so I can change OpenGL to OpenCL manually?

**Comment by pautho** [comment] 2021-06-04 18:44
Is there any solution? I am facing the same issue using `org.tensorflow:tensorflow-lite:2.4.0` or `org.tensorflow:tensorflow-lite:2.5.0`, 2.3.0 is working fine.

**Comment by impjdi** [comment] 2021-06-07 21:26
@anywhere133 Sorry for the belated reply, must have missed the email.  There are a couple of prerequisites: (a) your phone needs to have OpenCL installed, and (b) you want to set the experimental flag that enforce OpenCL unconditionally.  I am lazy and just comment out the InitializeOpenGlApi (or whatever it's called) In the delegate.cc.

@pautho The download of the model fails: http://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip  so I'm not sure what model you are working with.  If the tflite file is the same, but only works in 2.3 but not in 2.4, there's gotta be some regression which must be identified and fixed.  If it's the converter that broke and produces a tflite file that is no more compatible with the GPU delegate, we might have to assign it to the tflite converter people.  Can you identify why it stopped working?

**Comment by sanatmpa1** [comment] 2021-11-03 06:02
@anywhere133,

Can you take a look at the above comment by @impjdi and let us know if it helps in resolving your issue? Thanks!

**Closed** 2021-11-17 06:36 UTC
Labels: stat:awaiting response, type:support, stalled, comp:lite, TF 2.4, TFLiteGpuDelegate
