### ISSUE TITLE
bug when supplying metadata files for embeddings in tensorboard callback

### ISSUE THREAD

**Issue by ophiry** [tensorflow/tensorflow#32902] opened 2019-09-29 07:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0-dev20190927
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
getting the error:
`ValueError: Unrecognized `Embedding` layer names passed to `keras.callbacks.TensorBoard` `embeddings_metadata` argument: dict_keys(['char_embeddings'])`
when passing embeddings_metadata to tensorflow.keras.callback.TesnorBoard
**Describe the expected behavior**
use the metadata in tensorboard
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L1547

```
            if layer.name in embedding.metadata_path:
              embedding.metadata_path = self.embeddings_metadata.pop(layer.name)

```
should be:
```
            if layer.name in self.embeddings_metadata:
              embedding.metadata_path = self.embeddings_metadata.pop(layer.name)

```

**Comment by gadagashwini** [comment] 2019-09-30 08:54
@ophiry,
Do you have sample code to reproduce the issue. Thanks!

**Comment by ophiry** [comment] 2019-09-30 12:41
code to reproduce:
```
import tensorflow
import numpy
embedding_layer = tensorflow.keras.layers.Embedding(input_dim=1, output_dim=1, name='e')
model = tensorflow.keras.models.Sequential([embedding_layer])
model.compile(loss='mse')
model.fit(numpy.zeros((10, 1)), numpy.zeros((10, 1)), steps_per_epoch=1, callbacks=[
    tensorflow.keras.callbacks.TensorBoard(embeddings_freq=1, embeddings_metadata={'e': '/tmp/x'})
])

```

output is: 

> ValueError: Unrecognized `Embedding` layer names passed to `keras.callbacks.TensorBoard` `embeddings_metadata` argument: dict_keys(['e'])

**Comment by gadagashwini** [comment] 2019-10-01 04:05
@ophiry, Thanks. I could reproduce the issue with Tf 2.0 latest preview version on colab. Please take a look at [gist here](https://colab.sandbox.google.com/gist/gadagashwini/231b054a770f2af69ca8ca782f3c49e3/untitled170.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2019-10-01 09:58
@ophiry,
As per the explanation provided in [this link](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard), the value of the Dictionary of the parameter, `embeddings_metadata` should be a File, not a Folder. Can you please modify it accordingly.

Please refer [this link](https://www.tensorflow.org/tensorboard/r1/summaries#metadata_optional) for more information on the MetaData Files. Thanks!

**Comment by ophiry** [comment] 2019-10-01 19:39
It is a file - but from inspecting the code it's clear the value isn't used.

note that changing the code as I described in the original message fixes the issue

**Comment by skearnes** [comment] 2019-10-14 03:05
+1

**Comment by tomtang110** [comment] 2020-03-18 14:08
> It is a file - but from inspecting the code it's clear the value isn't used.
> 
> note that changing the code as I described in the original message fixes the issue

Could you tell me the metadata format? 
```
with open('./logs/text_classify/word.tsv','w') as f:
    f.write('{}\t{}\n'.format('id','words'))
    for k, v in word_index.items():
        f.write('{}\t{}\n'.format(v,k))
```
```
callback = [
            tf.keras.callbacks.TensorBoard(log_dir='./logs/text_classify',histogram_freq=5000,
            write_graph=True, write_images=False,
            embeddings_freq=1,
            update_freq='epoch',
            embeddings_metadata ={layer_embed.name:'./logs/text_classify/word.tsv'} )
```
I wrote the code above, but I found it doesn't works, it still shows the id of word rather than the word itself.

**Comment by saikumarchalla** [comment] 2020-04-17 04:22
@ophiry I think the issue is resolved and closing this as of now. Please feel free to reopen the issue if you still have a concern.Thanks!

**Closed by saikumarchalla** 2020-04-17 04:22 UTC
Labels: TF 2.0, comp:keras, stat:awaiting tensorflower, type:bug
