### ISSUE TITLE
tf2.0.0-rc0: tensor shape check failed when using tf.function in tf.distribute.Strategy scope.

### ISSUE THREAD

**Issue by 3fen** [tensorflow/tensorflow#32099] opened 2019-08-30 02:43 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- TensorFlow installed from (source or binary): binary(docker image: 2.0.0rc0-gpu-py3-jupyter)
- TensorFlow version (use command below): 2.0.0-rc0
- Python version:3.6.8
- CUDA/cuDNN version: V10.0.130
- GPU model and memory: P40

**Describe the current behavior**
I followed the document for writing custom training loop([ref](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/distribute/Strategy#in_short)), and caught an ValueError exception:
> ValueError: Input tensor 'Const_1:0' enters the loop with shape (), but has shape (None, 110, 110, 1) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

If I removed 'tf.function' decorator, the code worked fine with a warning:
> WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `experimental_run_v2` inside a tf.function to get the best performance.

**Describe the expected behavior**
It should work, and run faster than eager mode.

**Code to reproduce the issue**
```python
import tensorflow as tf
mirrored_strategy = tf.distribute.MirroredStrategy()
def get_net():
    net = tf.keras.Sequential()
    net.add(tf.keras.layers.Conv2D(filters=10,
                                   kernel_size=(3, 3)))
    net.add(tf.keras.layers.Dense(1))
    return net

data = tf.random.normal(shape=(1280, 112, 112, 3))
label = tf.random.normal(shape=(1280, ))
multi_db = tf.data.Dataset.from_tensor_slices((data, label)).batch(80)
dist_dataset = mirrored_strategy.experimental_distribute_dataset(multi_db)

with mirrored_strategy.scope():
    net = get_net()
    @tf.function
    def replica_fn(input):
        d, l = input
        return net(d)

    @tf.function
    def distribute_train_epoch(dataset):
        total_result = 0
        for x in dataset:
            per_replica_result = mirrored_strategy.experimental_run_v2(replica_fn, args=(x,))
            total_result = mirrored_strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_result, axis=None)
        return total_result

    for _ in range(100):
        f = distribute_train_epoch(dist_dataset)
```

**Comment by gadagashwini** [comment] 2019-08-30 06:16
I could reproduce the issue with Tensorflow 2.0.0-rc0. Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/58c3a0dd2d43c4cfd56ef5ffdd222a3f/untitled115.ipynb). Thanks!

**Comment by alextp** [comment] 2019-09-04 21:46
There is one serious TF issue here: the error message is somewhat confusing. If instead of `Const_1:0` it said the actual name of the tensor whose shape is changing (`total_result`) it'd be clear that there's a workaround; at the end of the loop doing `total_result = tf.reduce_sum(total_result)` since you seem to want `total_result` to be a scalar and `mirrored_strategy.reduce` sums across the replicas, not across the dimensions of the tensor.

**Comment by guptapriya** [comment] 2019-09-11 19:51
Yeah we should improve the error message. I checked that the error message is better for regular for loops / for loops over dataset without using distribution strategy. Only when using the for loop over distributed dataset do we run into the issue where the error message has the name of the loop variable wrong. 

BTW, this is the workaround Alex suggested above in code in case it helps (the tf.reduce_sum should happen within the loop, not outside):
```
@tf.function
    def distribute_train_epoch(dataset):
        total_result = 0.0
        for x in dataset:
            per_replica_result = mirrored_strategy.experimental_run_v2(replica_fn, args=(x,))
            total_result = tf.math.reduce_sum(mirrored_strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_result, axis=None))
        return total_result
```

**Comment by sushreebarsa** [comment] 2021-06-28 15:40
Was able to replicate the issue with TF 2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/3dc74f43690066028236059bb2694c12/untitled115.ipynb#scrollTo=yqEiBzYxKRUY) ..Thanks!

**Comment by mdanatg** [comment] 2021-06-28 16:23
This bug should be fixed in the latest TF version. Note that the repro script needs some corrections:

```
    ...
        total_result = 0.0
    ...
            per_replica_result = mirrored_strategy.run(replica_fn, args=(x,))
```

With those corrections, the error message is cleaner:

```
ValueError: 'total_result' has shape () before the loop, but shape (None, 110, 110, 1) after one iteration. Use tf.autograph.experimental.set_loop_options to set shape invariants.
```

Note that total_result will still need to be initialized properly, but hopefully the error message is now clearer in what needs to be done.

**Closed by mdanatg** 2021-06-28 16:23 UTC
Labels: TF 2.0, comp:dist-strat, type:bug
