### ISSUE TITLE
Memory leak in TensorFlow 2.0 DataSet when using group_by_window.

### ISSUE THREAD

**Issue by akanyaani** [tensorflow/tensorflow#36877] opened 2020-02-19 07:12 UTC
**System information**
- OS Platform: - Google Cloud Linux Ubuntu 16.04 
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.01
- GPU model and memory: Tesla P100, 16GB
- Running on GRAPH MODE:- YES

This is creating memory leak.
```
def pairwise_batch_iterator(tf_records,
                           no_threads=14,
                           batch_size=64,
                           num_epochs=50):
    
    dataset = make_dataset(tf_records, no_threads)
    dataset = dataset.repeat(num_epochs)
    
    dataset = dataset.apply(tf.data.experimental.group_by_window(
        key_func=lambda elem, *args: elem,
        reduce_func=lambda _, window: window.batch(batch_size),
        window_size=batch_size))
    
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    
    return dataset
```

This works fine
```
def pairwise_batch_iterator(tf_records,
                           no_threads=14,
                           batch_size=64,
                           num_epochs=50):
    
    dataset = make_dataset(tf_records, no_threads)
    dataset = dataset.repeat(num_epochs)
    
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    
    return dataset
```
***
I am training a pairwise ranking model where I have to group by query id that's why I am using tf.data.experimental.group_by_window and this is creating a memory leak. If I use the second version of code I don't face any issue but I have to group by query id.
***

**Comment by amahendrakar** [comment] 2020-02-19 11:47
@akanyaani,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by plooney** [comment] 2020-02-20 13:50
Could you change 

   `buffer_size=tf.data.experimental.AUTOTUNE`

to a fixed size and see if the problem persists?

**Comment by amahendrakar** [comment] 2020-02-29 07:15
@akanyaani,
Any updates regarding the reproducible code? Also, could you please check @plooney's comment and check if it works. Thanks!

**Comment by amahendrakar** [comment] 2020-03-07 05:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by akanyaani** [comment] 2020-03-26 13:45
Hi, @amahendrakar I was out of town, now I have updated the issue please reopen it.

**Comment by amahendrakar** [comment] 2020-03-27 17:49
@akanyaani,
Could you please provide the complete code to reproduce the issue reported here? Thanks!

**Comment by akanyaani** [comment] 2020-03-27 17:56
Hi @amahendrakar ,

I have created a new issue, link is:-https://github.com/tensorflow/tensorflow/issues/37969

**Comment by amahendrakar** [comment] 2020-03-27 17:58
Hello @akanyaani,
Since the issue is being tracked there, can we mark this as a duplicate and close this issue? Thanks!

**Comment by akanyaani** [comment] 2020-03-27 18:47
Hi @amahendrakar, Yes you can mark it as duplicate.

**Closed** 2020-03-27 18:47 UTC
Labels: TF 2.0, comp:data, type:bug
