### ISSUE TITLE
XLA Invalid __global__ read in fusion_514 (cublas bug?)

### ISSUE THREAD

**Issue by thorjohnsen** [tensorflow/tensorflow#24458] opened 2018-12-20 01:46 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Maybe. I modified the BERT network to do fp16 math and compiled with XLA.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a
- TensorFlow installed from (source or binary):
NVIDIA 18.12 development container
- TensorFlow version (use command below):
1.12
- Python version:
3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0.130
- GPU model and memory:
Tesla V100-SXM2-32GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Code runs for a while and then suddenly generates NaNs. Code runs normally when XLA is disabled.
cuda-memcheck caught a bunch of these:

========= Invalid __global__ read of size 4
=========     at 0x00000880 in fusion_514
=========     by thread (959,0,0) in block (10,0,0)
=========     Address 0x7f359f6e6e04 is out of bounds
=========     Device Frame:fusion_514 (fusion_514 : 0x880)
=========     Saved host backtrace up to driver entry point at kernel launch time

[xla_invalid_read_fusion_514_hlo_dumps.zip](https://github.com/tensorflow/tensorflow/files/2697101/xla_invalid_read_fusion_514_hlo_dumps.zip)
**Describe` the expected behavior**
Code runs without generating NaNs.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Should be reviewed by @jlebar 
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jlebar** [comment] 2018-12-20 22:20
I can reproduce...something.  Not the same failure you're seeing.

```
CUDA_LAUNCH_BLOCKING=1 cuda-memcheck tensorflow/compiler/xla/tools:replay_computation_gpu --use_fake_data=true --print_result=false --logtostderr --num_runs=100 $(ls ~/Downloads/xla-invalid-read-fusion/unoptimized_hlo_proto/* | grep _80__) --vmodule=gpu_executable=10

[...]

I1220 14:16:10.896196   49661 gpu_executable.cc:142] Executing the thunk for %dot.20474.9628 = f16[4096,768]{1,0} dot(f16[4096,768]{1,0} %fusion.1215, f16[768,768]{1,0} %convert.20474.8970), lhs_contracting_dims={1}, rhs_contracting_dims={0}, metadata={op_type="MatMul" op_name="bert/encoder/layer_0/attention/self/key/MatMul"} on stream 0

I1220 14:16:10.896224   49661 gpu_executable.cc:142] Executing the thunk for %fusion.1213 = f16[32,12,128,64]{3,2,1,0} fusion(f16[4096,768]{1,0} %dot.20474.9628, f32[768]{0} %arg167.20474.8683), kind=kLoop, calls=%fused_computation.1213, metadata={op_type="Transpose" op_name="bert/encoder/layer_0/attention/self/transpose_1"} on stream 0

E1220 14:16:10.899636   49661 cuda_driver.cc:1027] Internal: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_INSTRUCTION: an illegal instruction was encountered :: Stack trace:
    @     0x55fc241a94cb  stream_executor::cuda::CUDADriver::SynchronizeStream()
    @     0x55fc241a1ee7  stream_executor::cuda::CUDAExecutor::BlockHostUntilDone()
    @     0x55fc241dc03f  stream_executor::StreamExecutor::BlockHostUntilDone()
    @     0x55fc241af4a3  stream_executor::Stream::BlockHostUntilDone()
    @     0x55fc214f8f9d  xla::gpu::GpuExecutable::ExecuteThunks()
```

Interestingly this only happens on the second run of cluster 80.

I am not sure if this is a failure in XLA's generated code or in the cublas kernel that ran right before fusion.1213.  But in general ILLEGAL_INSTRUCTION is not our bug...

Anyway let me dig in a bit to this.  Strange that it's different from what you're seeing (i.e. no cuda-memcheck failure), but maybe the two failure modes are related somehow.

I'm on cuda 10.0.130 with cudnn 7.4.1 and driver 410.78.

**Comment by jlebar** [comment] 2018-12-20 22:22
(I'm using XLA compiled from head, so it's also possible that we fixed the error that was causing your cuda-memcheck failure after the TF 1.12 release.)

**Comment by jlebar** [comment] 2018-12-20 22:37
If I make all `dot` ops (i.e. matmuls) nops, the ILLEGAL_INSTRUCTION error goes away.

This strongly points a bug in cublas, at least for the failure I'm hitting.  Still no idea why what I'm seeing is different than what you're seeing.

Let me add optimization fuel to `gemm_thunk` to figure out which gemm call is the problem. http://blog.ezyang.com/2011/06/debugging-compilers-with-optimization-fuel/

**Comment by jlebar** [comment] 2018-12-20 22:53
It still hits an `ILLEGAL_INSTRUCTION` if I disable gemm autotuning and use the default gemm algorithm for each call.

**Comment by jlebar** [comment] 2018-12-20 23:37
I'm having some difficulty pinning this down, it seems to be nondeterministic exactly which gemm causes the problem.  :-/

**Comment by jlebar** [comment] 2018-12-20 23:57
Based on everything I've been able to see, I think what I'm seeing is a cublas bug.  I've filed nvbugs/2470403.  Let's see what they say.

My best guess is that you're seeing something different from me because you were using TF 1.12 instead of building from head or using an XLA nightly.

**Comment by jlebar** [comment] 2018-12-20 23:59
Because of the nondeterminism and the likelihood that it's cublas, I think this will be hard for me to debug much further.

cc @mruberry

**Comment by mruberry** [comment] 2018-12-21 17:56
Thanks for taking a look, Justin. We're investigating now.

**Comment by jlebar** [comment] 2019-01-17 22:31
We discussed this at a meeting today.  @benbarsdell indicated that he can't reproduce the failure he was seeing at head, and neither can I reproduce the failure I was seeing at head.

I want to bisect to see what changed to make this work.

**Comment by jlebar** [comment] 2019-01-18 19:22
I bisected this to 3a10998daf52ea922aa7ff895af3012afe956866.  That is extremely interesting, as I didn't expect that change to fix any actual bugs.

I think what may have been happening is that we were creating "too many" active cubins, and, when I tested, cublas was not properly handling the "cannot load a cubin" case, thus leading to the illegal_instruction error.  When you tested, some other kernel must have been failing to launch.

As for how we ended up with so many cubins in the first place, my guess is that making the fake arguments to the computation is the problem, as that uses the plain Client API, see implementation of MakeFakeArgumentsOrDie.

It does seem like there's a bug in error reporting somewhere...  This situation should not lead to illegal-instruction errors.

**Comment by mruberry** [comment] 2019-01-18 23:12
We would like to investigate the "too many" active cubins theory on our side, as a separate issue.

**Comment by jlebar** [comment] 2019-01-28 06:51
@mx8435, the problem fixed by that commit is the problem referenced in the subject of this bug -- an invalid __global__ read, apparently caused by the XLA replay_computation tool that I was using for debugging loading too many cubins at once.

I wouldn't expect fixing that issue to affect the TF case.  That is, now that we understand this bug, we understand that it's actually unrelated to the TF bug, and is a separate bug in the XLA tool we were using to isolate the TF issue.  I believe @thorjohnsen has updated the BERT PR to incorporate some fixes that make it work.

I'm going to close this particular issue, as it's resolved by that commit.

Sorry this is confusing.  :(

**Closed by jlebar** 2019-01-28 06:51 UTC
Labels: comp:xla
