### ISSUE TITLE
New Version of NVIDIA CUDA (10.1 Update 2)

### ISSUE THREAD

**Issue by nhubbard** [tensorflow/tensorflow#31728] opened 2019-08-17 17:44 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): Yes, I have a system that supports CUDA 10.1u2 and am willing to test issues with it.

**Describe the feature and the current behavior/state.** NVIDIA has released the newest version of CUDA, 10.1u2, and I would like to know if anyone familiar with NVIDIA/CUDA programming knows of any major changes that we would need to make in the future. Otherwise, I am available to compile and test on a system with a newer NVIDIA card to see how it works.

**Will this change the current api? How?** Not applicable.

**Who will benefit with this feature?** Newer hardware support.

**Any Other info.**

**Comment by nhubbard** [comment] 2019-08-18 23:34
I can **confirm** that a build of TensorFlow, using the 2.0 API, works in the following configuration at commit b0fee96b1dd893fe3fea6b746cf1965c8ca9f114 (current HEAD of branch `r2.0`):
* CUDA 10.1u2
* cuDNN 7.6.2
* TensorRT 5.1.5.0
* NCCL 2.4.8
* MKL-DNN 0.20
* Bazel 0.24.1
* GCC 8.2.1
* Red Hat Enterprise Linux 8.0

**Comment by oanush** [comment] 2019-08-19 12:52
@nhubbard ,
Can you confirm if the feature requested is working after the commit [b0fee96](https://github.com/tensorflow/tensorflow/commit/b0fee96b1dd893fe3fea6b746cf1965c8ca9f114) ?Thanks!

**Comment by nhubbard** [comment] 2019-08-20 00:30
It is working completely. Both the integrated tests and the tests that I use to test features for my use case are functioning as expected.

**Comment by oanush** [comment] 2019-08-20 03:46
Closing since the issue is resolved.Thanks!

**Closed by oanush** 2019-08-20 03:46 UTC
Labels: stat:awaiting response, type:build/install
