### ISSUE TITLE
Build error for Android quickstart - Toolchain missing

### ISSUE THREAD

**Issue by dominiklay** [tensorflow/tensorflow#39164] opened 2020-05-04 19:48 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.1
- Python version: 3.8
- Bazel version (if compiling from source):  3.1.0

**Describe the problem**

I want to build a shared library that contains the C API for TensorflowLite.
Building a .dll with `bazel build -c opt //tensorflow/lite/c:tensorflowlite_c`  was no problem. My goal now is to build the C API on Windows for Android to get a an .so and i was running into some problems, while i followed the instructions on ../g3doc/guide/android.md  under "Build TensorFlow Lite locally"

I am missing some toolchains and i do not know how to get them or how to set the correct Path. According to the tutorial i guess i probably should have them. Maybe the sdk/ndk paths are not set correctly since the ./configure file didn't react as expected (described further down).

**Build command:**
`bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite`

**ERROR message:**
D:\ComputerVision\tensorflow-master3\tensorflow-master>bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/python.exe
INFO: Reading rc options for 'build' from d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from d:\computervision\tensorflow-master3\tensorflow-master\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/lib/site-packages --python_path=C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:windows in file d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\computervision\tensorflow-master3\tensorflow-master\.bazelrc: --define framework_shared_object=false
ERROR: C:/users/nutzer/_bazel_nutzer/cncesu4u/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x86'
ERROR: Analysis of target '//tensorflow/lite/java:tensorflow-lite' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 4.042s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 395 targets configured)

**Steps executed before running into the problem**

I followed the instructions on ../g3doc/guide/android.md  under "Build TensorFlow Lite locally". I already have Bazel, sdk and ndk installed. So i ran ./configure.py but were not asked to to interactively configure the `./WORKSPACE` for Android builds, which seemed wrong according to the guide. Here is the ./configure promt:

`C:\Users\Nutzer\AppData\Local\Programs\Python\Python38\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Nutzer\AppData\Local\Programs\Python\Python38\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.`

To fix the `./configure` problem i already tried:

1) Setting `ANDROID_SDK_HOME` and`ANDROID_NDK_HOME` in cmd (the highest API level should automatically be used right?)

2) Manually adding the env entries in `.tf_configure.bazelrc` so it looked like this:

`build --action_env PYTHON_BIN_PATH="C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/lib/site-packages"
build --action_env ANDROID_NDK_HOME="C:/Users/Nutzer/AppData/Local/Android/NDK/android-ndk-r17c"
build --action_env ANDROID_NDK_API_LEVEL="21"
build --action_env ANDROID_BUILD_TOOLS_VERSION="28.0.3"
build --action_env ANDROID_SDK_API_LEVEL="29"
build --action_env ANDROID_SDK_HOME="C:/Users/Nutzer/AppData/Local/Android/Sdk"
build --python_path="C:/Users/Nutzer/AppData/Local/Programs/Python/Python38/python.exe"
build --config=xla
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"`

3) Adding the following sniped to the `WORKSPACE`:

android_sdk_repository(
    name = "androidsdk", # Required. Name *must* be "androidsdk".
    path = "C:/Users/Nutzer/AppData/Local/Android/Sdk", # Optional. Can be omitted if `ANDROID_HOME` environment variable is set.
)
android_ndk_repository(
    name = "androidndk", # Required. Name *must* be "androidndk".
    path = "C:/Users/Nutzer/AppData/Local/Android/NDK/android-ndk-r17c", # Optional. Can be omitted if `ANDROID_NDK_HOME` environment variable is set.
)

**Thank You for Your time and expertise!**

**Comment by dominiklay** [comment] 2020-05-06 16:22
Should a file called _toolchain_ normally be in the folder: _bazel_tools//tools/cpp_ ? If so why could mine be missing? Or do i missunderstand `host_crosstool_top=@bazel_tools//tools/cpp:toolchain`

**Comment by dominiklay** [comment] 2020-05-11 16:30
I figured out that changing `environ_cp['TF_SET_ANDROID_WORKSPACE'] = '0'`  to 1 in configure.py i now get asked for sdk and ndk path. But now i get a new error after running the build command.  After all i still do not know if my real problem even originates in the sdk and ndk settings. Help is still appreciated very much! 

This is the now generated `.tf_configure.bazelrc` file:

```
build --action_env PYTHON_BIN_PATH="C:/Users/Nutzer/AppData/Local/Programs/Python/Python36/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Users/Nutzer/AppData/Local/Programs/Python/Python36/lib/site-packages"
build --python_path="C:/Users/Nutzer/AppData/Local/Programs/Python/Python36/python.exe"
build --config=xla
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
build --action_env ANDROID_NDK_HOME="C:\Users\Nutzer\AppData\Local\Android\Sdk\ndk\21.1.6352462"
build --action_env ANDROID_NDK_API_LEVEL="21"
build --action_env ANDROID_BUILD_TOOLS_VERSION="30.0.0-rc4"
build --action_env ANDROID_SDK_API_LEVEL="29"
build --action_env ANDROID_SDK_HOME="C:\Users\Nutzer\AppData\Local\Android\Sdk"
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

And this is the resulting error:

ERROR: D:/computervision/tensorflow-master/tensorflow-master/WORKSPACE:65:1: //external:android/sdk depends on @androidsdk//:sdk in repository @androidsdk which failed to fetch. no such package '@androidsdk//': The repository's path is "C:UsersNutzerAppDataLocalAndroidSdk" (absolute: "D:/computervision/tensorflow-master/tensorflow-master/C:UsersNutzerAppDataLocalAndroidSdk") but a symlink could not be created for it, because: D:/computervision/tensorflow-master/tensorflow-master/C:UsersNutzerAppDataLocalAndroidSdk (No such file or directory)
ERROR: Analysis of target '//tensorflow/lite/java:tensorflow-lite' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.436s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 114 targets configured)

**Comment by terryheo** [comment] 2020-05-13 02:01
Did you revert your modification on WORKSPACE ?

**Comment by dominiklay** [comment] 2020-05-13 09:47
Yes i am testing on a freshly downloaded and unmodified TF Environment. The only thing changed is this part of the configure.py file:

```
  if is_windows():
    environ_cp['TF_NEED_OPENCL_SYCL'] = '0'
    environ_cp['TF_NEED_COMPUTECPP'] = '0'
    environ_cp['TF_NEED_OPENCL'] = '0'
    environ_cp['TF_CUDA_CLANG'] = '0'
    environ_cp['TF_NEED_TENSORRT'] = '0'
    # TODO(ibiryukov): Investigate using clang as a cpu or cuda compiler on
    # Windows.
    environ_cp['TF_DOWNLOAD_CLANG'] = '0'
    environ_cp['TF_NEED_MPI'] = '0'
    environ_cp['TF_SET_ANDROID_WORKSPACE'] = '1'
```
also i am running `python configure.py` directly instead of `./configure` but that should not be a problem right?

The line 65 in WORKSPACE which results in the error is this one: `android_workspace()`

What also confuses me in the error is the file and path he is searching. What file is he looking for and where should it actually be located?

**Comment by terryheo** [comment] 2020-05-15 00:36
Oh, I didn't know Android configuration is disabled for Windows.
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1390
@jdduke, any idea on this?

**Comment by jdduke** [comment] 2020-05-15 17:03
See also issue #38525.

**Comment by jdduke** [comment] 2020-05-15 17:56
Duplicate of #38525

**Closed by jdduke** 2020-05-15 17:56 UTC
Labels: TF 2.1, comp:lite, subtype:windows, type:build/install

**Comment by dominiklay** [comment] 2020-05-18 08:01
I am now building on Linux, where it is working without trouble. I have not tested if the issue would be resolved, but thank you for your help!
