### ISSUE TITLE
Creating pip package for TensorFlow with GPU support results in 0 byte simple_console_for_windows.zip

### ISSUE THREAD

**Issue by rcorvus** [tensorflow/tensorflow#22382] opened 2018-09-19 14:19 UTC
Here is the stackoverflow question: https://stackoverflow.com/questions/52394305/creating-pip-package-for-tensorflow-with-gpu-support-results-in-0-byte-simple-co

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.2/7.2.1
- **GPU model and memory**: Nvidia M1000M
- **Exact command to reproduce**: bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg

### Describe the problem
After successfully building TensorFlow with GPU support, I'm trying to build the pip package and I'm getting an error saying it can't read the simple_console_for_windows.zip file.  

I've confirmed that the file is in C:\tensorflow\bazel-bin\tensorflow\tools\pip_package folder, but it is 0 bytes.

This is my pip build command:
    bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg

My build command was:
    bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Source code / logs
This is the full error:

    Unzipping simple_console_for_windows.zip to create runfiles tree...
    [./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip or
            ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.zip, and cannot find ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.ZIP, period.

**Comment by bstriner** [comment] 2018-09-24 07:08
Just started happening to me, too. Tossing the zip files manually seems to fix. Linking the other issue directly: https://github.com/tensorflow/tensorflow/issues/20332

**Comment by meteorcloudy** [comment] 2018-09-24 08:18
This is a duplicate of #22390, I'm closing this one. Let's follow the progress in #22390.

**Closed by meteorcloudy** 2018-09-24 08:18 UTC
