### ISSUE TITLE
tfio.audio.AudioIOTensor doesn't prepare data in time in loop.

### ISSUE THREAD

**Issue by asterisk37n** [tensorflow/tensorflow#43604] opened 2020-09-27 12:26 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No mobile device used.
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CPU
- GPU model and memory: CPU

**Describe the current behavior**
Training loop crashes. It seems ```tfio.audio.AudioIOTensor``` doesn't prepare data in time when processing. It lazy loads and supposed to prepare data when called.

**Describe the expected behavior**
```tfio.audio.AudioIOTensor``` prepares audio data and process in time.

**Standalone code to reproduce the issue**

dataloader.py
```py
import os

import tensorflow as tf
import tensorflow_io as tfio


duration = 5
rate = 20000
samples = duration * rate


def process_paths(file_paths):
  """receive a batch of filepaths and return a batch of db mel-spectrogram and batch of labels
  params
  filepaths: string[]
  
  return
  (db_mel_spectrograms: Tensor<tf.float32>, labels: Tensor<tf.string>)
  """
  db_mel_spectrograms, labels = tf.map_fn(
    fn=process_path,
    elems=file_paths,
    fn_output_signature=(tf.float32, tf.string)
  )
  return db_mel_spectrograms, labels

def process_path(file_path):
  label = tf.strings.split(file_path, os.sep)[-2]
  audio = tfio.audio.AudioIOTensor(file_path, dtype=tf.float32)
  re_audio = tfio.audio.resample(
    audio.to_tensor(),
    rate_in=tf.cast(audio.rate, tf.int64),
    rate_out=rate
  )
  re_audio_1c = tf.reduce_mean(re_audio, axis=-1)  # [samples, channels] => [samples]
  zeros = tf.math.maximum(samples - tf.shape(re_audio_1c)[0], 0)
  paddings = [[zeros // 2, zeros // 2 + zeros % 2]]
  pad_audio = tf.pad(re_audio_1c, paddings=paddings, mode='CONSTANT')  # pad if audio is too short
  cropped_audio = tf.image.random_crop(pad_audio, [samples])

  return cropped_audio, label

def get_data(glob_path, batch_size):
  """
  get optimized tf.data.Dataset. Use like
  data = get_data(path, 128)
  epochs = 10
  for epoch in range(epochs):
    for spectrograms, labels in data:
      train_this_batch(spectrograms, labels)
      
  Args:
    glob_path: string like /path/to/data/*.mp3
    batch_size: int
  Returns:
    tf.data.Dataset with optimization
  """
# The code in this comment is not optimized (no parallel, no prefetch), but even when I use this code, training loop fails miserably.
#  data = (
#    tf.data.Dataset.list_files(glob_path)
#    .batch(
#      batch_size,
#      drop_remainder=True
#    )
#    .map(
#      process_paths,
#      num_parallel_calls=1
#    )
#  )
#  

# This is optimized data preparation
  data = (
    tf.data.Dataset.range(2)
    .interleave(
      lambda *args: tf.data.Dataset.list_files(glob_path),
      num_parallel_calls=tf.data.experimental.AUTOTUNE
    )
    .batch(
      batch_size,
      drop_remainder=True
    )
    .map(
      process_paths,
      num_parallel_calls=tf.data.experimental.AUTOTUNE
    )
    .cache()
    .prefetch(tf.data.experimental.AUTOTUNE)
  )

  return data
```

main.py
```py
import time

import dataloader

data = dataloader.get_data('path/to/audio/*/*.mp3', 64)  # Sorry I updated this line to call function.
# path/to/audio/メジロ/1.mp3
# path/to/audio/メジロ/2.mp3
# ...
# path/to/audio/ウグイス/1.mp3
# path/to/audio/ウグイス/2.mp3
# ...

for f, l in data:
  # Training code is left out as it is irrelevant. This time.sleep is enough to reproduce.
  time.sleep(0.01)  
```

**Other info / logs** 

When I replace ```tfio.audio.AudioIOTensor(path)``` with ```tf.zeros((6000,), dtype=tf.float32)``` , whole epoch run finely. I think tfio.audio.AudioIOTensor has no data when read, so below error happens as it describes. I have no idea how to data prepared when reading.

```
> python main.py2020-09-27 21:32:37.473956: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: AVX2 FMA
2020-09-27 21:32:37.582070: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-27 21:32:37.593090: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc74c15d830 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-27 21:32:37.593109: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-27 21:32:47.870608: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at audio_kernels.cc:212 : Invalid argument: read 1100254 from 0 failed: 0
2020-09-27 21:32:47.895352: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at audio_kernels.cc:212 : Invalid argument: read 1100254 from 0 failed: 0
2020-09-27 21:32:48.574386: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at audio_kernels.cc:212 : Invalid argument: read 9796964 from 0 failed: 0
2020-09-27 21:32:50.874190: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at audio_kernels.cc:212 : Invalid argument: read 307678 from 0 failed: 0
2020-09-27 21:32:56.575449: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at audio_kernels.cc:212 : Invalid argument: read 3505630 from 0 failed: 0
Traceback (most recent call last):
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: read 1100254 from 0 failed: 0
	 [[{{node map/while/body/_1/map/while/IO>AudioReadableRead}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 21, in <module>
    for f, l in data:
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/Users/asterisk37n/my_awesome_project/.venv/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: read 1100254 from 0 failed: 0
	 [[{{node map/while/body/_1/map/while/IO>AudioReadableRead}}]]
2020-09-27 21:33:04.393965: W tensorflow/core/kernels/data/cache_dataset_ops.cc:798] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.```

**Comment by ravikyram** [comment] 2020-09-28 07:28
@asterisk37n 

Can you please share the dataset you are using in the code.Thanks!

**Comment by asterisk37n** [comment] 2020-09-28 09:29
@ravikyram Sure. This is just 1GB data but I reproduced with it.
https://drive.google.com/file/d/1WRywjR8pJaPkur3pPpd81mxMf1vRnZMv/view?usp=sharing

**Comment by ravikyram** [comment] 2020-09-29 11:26
@asterisk37n 

I have tried in colab with TF 2.3 and i am seeing the  error message(`TypeError: 'module' object is not callable`). Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/67d0a29ccb8d51a02e6bfe60d0df0228/untitled403.ipynb). Please, help me with reproducible code, to localize the issue faster.Thanks!

**Comment by asterisk37n** [comment] 2020-09-29 13:22
@ravikyram 
Sorry the data loading line should be
```data = dataloader.get_data('path/to/audio/*/*.mp3', 64)```
, not
```data = dataloader('path/to/audio/*/*.mp3', 64)```
. I fixed and updated the code I shared in this issue (Scroll up to see).
I reproduced in colab:
https://colab.research.google.com/drive/1AGxb0cYWEHxpj-cWL_X6YT3lfW57H92Q?usp=sharing

**Comment by ravikyram** [comment] 2020-09-29 16:55
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200929`) and was able to reproduce the issue.PLease, find the gist [here.](https://colab.research.google.com/gist/ravikyram/a6214cf24cad63043638daa58d38325c/untitled403.ipynb)Thanks!

**Comment by sushreebarsa** [comment] 2021-08-11 09:19
@asterisk37n  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by asterisk37n** [comment] 2021-08-18 10:00
Thank you for fixing! Sorry I don't have time to review

**Comment by sushreebarsa** [comment] 2021-08-31 13:49
@asterisk37n I don't have the access to the files to reproduce the issue from my end.Could you please try to execute your code using the latest TF v2.6 and let us know if the issue still persists ? Thank you!

**Closed** 2021-09-14 14:42 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.3
