### ISSUE TITLE
./configure: line 26: ./util/python/python_config.sh: no such file or directory 

### ISSUE THREAD

**Issue by Jiuses** [tensorflow/tensorflow#819] opened 2016-01-20 13:52 UTC
While running ./configure and then comes to an issue, ./configure: line 26: ./util/python/python_config.sh: no such file or directory. Could somebody give me a little help?

**Comment by martinwicke** [comment] 2016-01-20 16:33
That's mysterious. The file is clearly in the repo ([here](https://github.com/tensorflow/tensorflow/blob/master/util/python/python_config.sh)). Can you make sure that you checked everything out properly?

**Comment by vrv** [comment] 2016-02-06 22:13
Closing due to staleness / lack of reproducibility.  Please request to re-open if it's still a problem.

**Closed by vrv** 2016-02-06 22:13 UTC
Labels: installation/startup

**Comment by johndpope** [comment] 2017-06-08 14:59
was working on a different fork - it seems the file isn't there for me. although there's a BUILD file. 
<img width="797" alt="screen shot 2017-06-08 at 10 58 56 am" src="https://user-images.githubusercontent.com/289994/26935270-80e478f4-4c39-11e7-900a-f1a09fea11f0.png">
