### ISSUE TITLE
Possible bug with rejection sampling

### ISSUE THREAD

**Issue by laghaout** [tensorflow/tensorflow#39195] opened 2020-05-05 17:04 UTC
This is about the [official TensorFlow tutorial on input pipelines](https://www.tensorflow.org/guide/data). In the [section](https://www.tensorflow.org/guide/data#rejection_resampling) on rejection sampling, the very last cell, namely
```
for features, labels in balanced_ds.take(10):
    print(labels.numpy())
```
produces a set of labels which are all zeros, indicating that the dataset hasn't been balanced.

**System information**
- Windows 10
- Python 3.7.4 under conda 4.8.3
- tensorflow-datasets 1.3.0
- tensorflow-estimator 2.0.1
- tensorflow-gpu 2.1.0 
- tensorflow-gpu-estimator 2.1.0
- gast 0.2.2

**Comment by ravikyram** [comment] 2020-06-05 07:57
@laghaout 
I have tried in colab in TF version 2.1,2.2.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c77f99292e6e5b0c15dadb6527f548e5/untitled51.ipynb).Is this the expected behavior?.Thanks!

**Comment by laghaout** [comment] 2020-06-13 11:27
@ravikyram What you're getting is indeed the expected behaviour, but what I get is a 10-by-10 matrix of all zeros.

**Comment by ravikyram** [comment] 2020-06-15 06:18
@laghaout 

This is not a bug in Tensorflow as we see the results as expected in the colab. Can you try again in virtual environment and see if the problem is still persists.Thanks!

**Comment by ravikyram** [comment] 2020-06-19 06:13
Automatically closing this out since I understand it is not a bug in Tensorflow, but please let me know if I'm mistaken.Thanks!

**Closed by ravikyram** 2020-06-19 06:13 UTC
Labels: TF 2.1, comp:data, stat:awaiting response, type:bug
