### ISSUE TITLE
tensorflow build 1.13 build fails

### ISSUE THREAD

**Issue by cindy951357** [tensorflow/tensorflow#25479] opened 2019-02-04 05:22 UTC
I need tensorflow 1.13 (1.12 or below doesn't fit my need.)
But for now I can only build from source.
command:
` bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`
returned:
> **ERROR: /Users/cindy951357/Documents/pythonworkspace/sphinxenv/tensorflow-1.13.0-rc0/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
> Traceback (most recent call last):
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
>     from tensorflow.python.tools.api.generator import doc_srcs
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 72, in <module>
>     from tensorflow.python.ops.standard_ops import *
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/standard_ops.py", line 25, in <module>
>     from tensorflow.python import autograph
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/autograph/__init__.py", line 37, in <module>
>     from tensorflow.python.autograph.core.converter import ConversionOptions
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/autograph/core/converter.py", line 74, in <module>
>     from tensorflow.python.autograph.pyct import cfg
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/autograph/pyct/cfg.py", line 41, in <module>
>     from tensorflow.python.autograph.pyct import compiler
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/autograph/pyct/compiler.py", line 30, in <module>
>     import astor
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/astor_archive/astor/__init__.py", line 14, in <module>
>     from .code_gen import to_source  # NOQA
>   File "/private/var/tmp/_bazel_cindy951357/121f1294318945434311585d2ce28ccd/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/astor_archive/astor/code_gen.py", line 311
>     def visit_FunctionDef(self, node, async=False):
>                                           ^
> SyntaxError: invalid syntax
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 8612.039s, Critical Path: 400.52s
> INFO: 9224 processes: 9224 local.
> FAILED: Build did NOT complete successfully**

[this discussion](https://github.com/tensorflow/tensorflow/issues/25151) says that we can wait for **rc2**.
But when will rc2 release?
Or can I use python3.6 to build tensorflow 1.13?

**Comment by jvishnuvardhan** [comment] 2019-02-04 21:03
@cindy951357 Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thank

**Comment by cindy951357** [comment] 2019-02-04 23:18
Thank you for your response. I am not quite understanding what you mean by **update them if they are relevant in your case, or leave them as N/A**. 
For your information, from my experience( after some testing), tensorflow 1.13 can be installed with python 3.6.5 but **NOT** python 3.7.

**Comment by jvishnuvardhan** [comment] 2019-02-04 23:31
@cindy951357 We want the system information in order to provide faster resolution. For example, if you don't have GPU, then you will write N/A for "GPU model and memory:". Regarding TF 1.13, python 3.7 was not listed on the download [page](https://pypi.org/project/tf-nightly/). Please try Python 3.6.5. Thanks!

**Comment by martinwicke** [comment] 2019-02-05 00:55
Alex, Mark -- I believe you are users of astor in TF. The message above indicates that astor is not compatible with Py 3.7 (use or reserved word). This means that we must replace astor, or fix it. 

Can it be fixed?

**Comment by martinwicke** [comment] 2019-02-05 00:57
@aselle @goldiegadde this would prevent 3.7 binaries for 1.13, right?

**Comment by aselle** [comment] 2019-02-05 00:58
@gunan @av8ramit

**Comment by MarkDaoust** [comment] 2019-02-05 01:16
This looks like it's fixed in the latest `astor` release:

https://github.com/berkerpeksag/astor/blob/0.7.1/astor/code_gen.py#L312

And it looks like tensorflow is using 0.71.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L287

@cindy951357 what version of astor do you have installed. It looks like 0.6.* or before is broken.

I don't see how it would make a difference, AFAIK the builds are supposed to run from the workspace file, but try:

```
pip install -U astor
```
Maybe something in your local installation is masking the 0.7.1 version.

**Comment by av8ramit** [comment] 2019-02-05 01:34
@martinwicke yes unfortunately I'm running into this issue on the r1.13 branch. It seems to be fixed in master. I think we need to cherrypick https://github.com/tensorflow/tensorflow/commit/868a11a8de788134caeadc895625583e8b44b660

**Comment by alexbw** [comment] 2019-02-05 01:34
@mdanatg

**Comment by av8ramit** [comment] 2019-02-05 01:38
PR is out: https://github.com/tensorflow/tensorflow/pull/25503

**Comment by av8ramit** [comment] 2019-02-05 18:47
It has been merged. @cindy951357 is this still an issue?

**Comment by av8ramit** [comment] 2019-02-08 19:18
I'm going to close this issue for now. Please comment if this is still an issue.

**Closed by av8ramit** 2019-02-08 19:18 UTC
Labels: TF 1.13, type:build/install
