### ISSUE TITLE
Change Kernel dimension(height * width * input_channel * output_channel) to NCHW format

### ISSUE THREAD

**Issue by allencho1222** [tensorflow/tensorflow#17062] opened 2018-02-16 10:49 UTC
First of all, it seems that no one tries this due to the fact that I couldn't get any answers from stackoverflow or googling.

I'm trying to use cudnn inside the custom op.

Basically, custom op receives kernel layout (height * width * input_channel * output_channel).

But, according to cudnn policy, kernel layout has to be (output_channel * input_channel * height * width) inside custom op. But, I couldn't find anything regarding this issues.

Are there any solutions for converting layout like this(HWCN to NCHW)?

**Comment by cy89** [comment] 2018-02-16 18:38
@allencho1222 um, could you please be more specific about what were you failing to find? The layout conversion issue is central to GPU performance. The TF Performance Guide has a section on Data Formats: https://www.tensorflow.org/performance/performance_guide

I see a number of hits on StackOverflow. This one talks about how to convert layouts: https://stackoverflow.com/questions/37689423/convert-between-nhwc-and-nchw-in-tensorflow

**Comment by tensorflowbutler** [comment] 2018-02-16 19:38
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-03-03 15:04
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-18 16:03
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:38
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-02 18:41
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jart** [comment] 2018-05-04 01:08
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jart** 2018-05-04 01:08 UTC
Labels: stat:awaiting response
