### ISSUE TITLE
[feature request] differentiate through eager_py_func

### ISSUE THREAD

**Issue by chengchingwen** [tensorflow/tensorflow#20839] opened 2018-07-16 13:03 UTC
According to the [`tf.contrib.eager.py_func`](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/py_func) api doc,

> tf.contrib.eager.py_func is not differentiable, though a gradient may be implemented in the future; if you would like to differentiate through it, please file an issue on Github.

so I open an issue here.

**Comment by tensorflowbutler** [comment] 2018-07-17 01:06
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by reedwm** [comment] 2018-07-17 22:15
Looks like this was fixed in c2493ed5aa9eaf375d88331c7cdb70e428614dc8. That commit will be in TensorFlow 1.10.

**Closed by reedwm** 2018-07-17 22:15 UTC
Labels: stat:awaiting response
