### ISSUE TITLE
TPUStrategy does not export graph to TensorBoard while TPUEstimator does it

### ISSUE THREAD

**Issue by harrydrippin** [tensorflow/tensorflow#40372] opened 2020-06-11 01:42 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Both Tested
- OS Platform and Distribution: Linux Ubuntu 18.04 on GCE
- TensorFlow installed from: PyPI, with `tensorflow==2.1.0`
- TensorFlow version: `v2.1.0-rc2-17-ge5bf8de 2.1.0`
- Python version: 3.6
- CUDA/cuDNN version: N/A (Issue from TPU environment)
- GPU model and memory: N/A (Same as above)
- (Additional) TensorBoard version: 2.1.0

**Describe the current behavior**

I've found [the official document from Google Cloud](https://cloud.google.com/tpu/docs/cloud-tpu-tools#xla_graphs) says that I can access to the graph by clicking `GRAPHS` tab inside TensorBoard without setting any other configuration to my code, so I constructed the graph and executed the training steps by using `TPUStrategy`. But I failed to find those informations on TensorBoard.

I additionally tested the official model by using `TPUEstimator` on V1 Compat API, and I could successfully obtain the graph data on TensorBoard. I assume this is a bug, but may need several help if not. Thank you!

**Describe the expected behavior**

The code below successfully export graph data on TensorBoard.

**Standalone code to reproduce the issue**

I've tested [the official tutorial using ResNet](https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_main.py), and saw it is successfully working.

Problem is at the code below:

> `Model` is very small toy model like `Linear-ReLU-Linear`, and was subclassed using `tf.keras`.

```python 
import tensorflow as tf
import os

from project.model import Model

def main():
    storage_name = "google-cloud-storage-name"
    GRAPH_LOGDIR = f"{storage_name}/logs/"

    writer = tf.summary.create_file_writer(GRAPH_LOGDIR)

    resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=os.environ["TPU_NAME"])
    tf.config.experimental_connect_to_cluster(resolver)
    tf.tpu.experimental.initialize_tpu_system(resolver)
    strategy = tf.distribute.experimental.TPUStrategy(resolver)

    with strategy.scope():
        model = Model()

        @tf.function
        def trace_model(model_input):
            return model(model_input)

        model_input = tf.ones((3, 48), tf.int64)

        tf.summary.trace_on(graph=True, profiler=True)
        trace_model(model_input)
        with writer.as_default():
            tf.summary.trace_export(name="model_trace", step=0, profiler_outdir=GRAPH_LOGDIR)

if __name__ == "__main__":
    main()
```

I estimated this code should work and export graph data to TensorBoard, but no any graph data was found.

**Other info / logs**

Every single examples were tested on Google Cloud, using Cloud TPU, Compute Engine, and Cloud Storage.
CC @ddehun

**Comment by ravikyram** [comment] 2020-06-11 06:09
@harrydrippin 

I tried reproducing the issue in colab and i am seeing error (`ModuleNotFoundError: No module named 'project'`).Request you to procide colab link or simple standalone code with supporting files to reproduce the isse in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ddehun** [comment] 2020-06-15 12:40
@ravikyram , I'm working with @harrydrippin for this issue. We just made the[ issue regeneration step example on Colab.](https://colab.research.google.com/drive/1rDXQacODUQ-ycJM-HIPMcsn_wVgoBZoK?usp=sharing)

Due to the restriction about file system on Colab environment, **You may need to apply some changes for the appropriate setting to use TPU-based model training and logging.** 

By the result of this notebook, you can see two log files: one for Estimator-based, and another one for Strategy-based. And, as you can check on the images, Strategy-based code CANNOT generate the graph while Estimator-based code can.

### Estimator-based

<img width="1501" alt="스크린샷 2020-06-15 오후 9 37 34" src="https://user-images.githubusercontent.com/20228985/84658182-74338780-af50-11ea-81c3-b419ed2c6407.png">

### Strategy-based

<img width="1497" alt="스크린샷 2020-06-15 오후 9 38 07" src="https://user-images.githubusercontent.com/20228985/84658211-8281a380-af50-11ea-9ed6-d2ed14873300.png">

Thank you for your support, and let us know if you need any other information.

**Comment by sushreebarsa** [comment] 2021-08-11 09:10
@harrydrippin  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-25 10:16 UTC
Labels: comp:tensorboard, stat:awaiting response, type:bug, stalled, comp:tpus, TF 2.1
