### ISSUE TITLE
How to Read tensorflow source code with an IDE ?

### ISSUE THREAD

**Issue by thesby** [tensorflow/tensorflow#5320] opened 2016-11-01 09:05 UTC
Is there any IDE support bazel so that I can use IDE to read the source code ?

**Comment by aselle** [comment] 2016-11-01 17:24
Most IDEs have options to setup "builders" that can be arbitrary commands. Just make a new "builder" that runs "bazel build <whatevertarget you want>"... You can ask on stackoverflow is you want to query a larger audience about what they use as an IDE. Closing, as this is not a bug. Thanks!

**Closed by aselle** 2016-11-01 17:24 UTC
