### ISSUE TITLE
Tensorflow 1.3.0 not buildable because bazel fails to download protobuf

### ISSUE THREAD

**Issue by eLvErDe** [tensorflow/tensorflow#13214] opened 2017-09-21 15:52 UTC
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 2,859,576 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,046,594 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,235,206 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,422,448 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,609,690 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,796,932 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 3,985,320 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 4,172,562 bytes
> ____Downloading https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz via codeload.github.com: 4,359,804 bytes
> ERROR: /build/python-tensorflow-cuda-1.3.0/tensorflow/tools/pip_package/BUILD:100:1: no such package '@protobuf//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz, http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz] to /build/python-tensorflow-cuda-1.3.0/.cache/bazel/_bazel_pbuilder/f9c4bbbece8e6d872cda536e5e92a13c/external/protobuf/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: Checksum was e5fdeee6b28cf6c38d61243adff06628baa434a22b5ebb7432d2a7fbabbdb13d but wanted 6d43b9d223ce09e5d4ce8b0060cb8a7513577a35a64c7e3dad10f0703bf3ad93 and referenced by '//tensorflow/tools/pip_package:licenses'.
> ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
> ____Elapsed time: 12.129s

It's not a local issue, reproduced several time with different Internet connection....

Thanks

**Comment by aselle** [comment] 2017-09-21 16:21
This is a duplicate of #12979. Please see that issue for more information.

**Closed by aselle** 2017-09-21 16:21 UTC
