### ISSUE TITLE
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 51 (FlexResizeNearestNeighbor) failed to prepare.

### ISSUE THREAD

**Issue by Ben-Lee-2019** [tensorflow/tensorflow#45143] opened 2020-11-24 07:29 UTC
Hello.,sorry to bother you. I am learning to build Android programs using tflite. The environment I use is
tensorflow-2.2,SDK 29.0.3,NDK 21.
When I use the model.tflite to build app,I get an error:

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'  Registration failed.
``` 
I don't know how to solve this problem,maybe the conversion failed？
The program  of yolo-tiny I used  is https://github.com/bubbliiiing/yolov4-tiny-tf2.
The model of yolo-tiny can be used for detecting correctly.
I have build tensorflow-lite-select-tf-ops.aar in Android project.
My English is poor,please excuse me.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):tensorflow2.2

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
from tensorflow.keras.models import load_model
from nets.yolo4_tiny import yolo_body,yolo_eval

from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Input, Lambda
from train import get_anchors
from train import get_classes

model=load_model('yolo_voc.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, 
                                      tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
with tf.io.gfile.GFile('fmodel.tflite', 'wb') as f:
  f.write(tflite_model)
 
from tflite_support import metadata as _metadata
populator = _metadata.MetadataPopulator.with_model_file("fmodel.tflite")
populator.load_associated_files(["model_data/voc_classes.txt"])
populator.populate() 
```

**The output from the converter invocation**

When I run the code above,the terminal prints:
```
UserWarning: File, 'voc_classes.txt', does not exsit in the metadata. But packing it to tflite model is still allowed.
  "tflite model is still allowed.".format(f)
```
If I use tf2.2 to get the details of tflite_model,I would get the error:

```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 51 (FlexResizeNearestNeighbor) failed to prepare.

```

if I use tf2.3,I would get:

```
TfLiteFlexDelegate delegate: 1 nodes delegated out of 56 nodes with 1 partitions.
[  1 416 416  3]
<class 'numpy.float32'>
[ 1 13 13 75]
<class 'numpy.float32'>

```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/drive/folders/1sXTFLk5xkFSao7edJXFIsFIcojtR8wjK?usp=sharing
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

**Comment by Ben-Lee-2019** [comment] 2020-11-24 07:46
Sorry,the mobile is HUAWEI mate30

**Comment by jvishnuvardhan** [comment] 2020-11-24 22:36
@Ben-Lee-2019 Can you please share a gist or a jupyter notebook. I am getting different error because of some `nets` dependencies. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c3bf509b0905bdf0e4fe530b95eb4790/untitled.ipynb). Thanks!

**Comment by Ben-Lee-2019** [comment] 2020-11-25 02:07
> @Ben-Lee-2019 Can you please share a gist or a jupyter notebook. I am getting different error because of some `nets` dependencies. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c3bf509b0905bdf0e4fe530b95eb4790/untitled.ipynb). Thanks!

HI，I am so sorry that I didn't describe the problem clearly,this conversion should be ran under this.(https://github.com/bubbliiiing/yolov4-tiny-tf2)

**Comment by karimnosseir** [comment] 2020-12-02 07:10
@Ben-Lee-2019 It looks you're trying to use model converted using newer version than the runtime.

Can you please convert and run your model from the same TF version - it will be better if you used a newer version 2.4 may be

Thanks

**Comment by Ben-Lee-2019** [comment] 2020-12-02 09:02
> @Ben-Lee-2019 It looks you're trying to use model converted using newer version than the runtime.
> 
> Can you please convert and run your model from the same TF version - it will be better if you used a newer version 2.4 may be
> 
> Thanks

Thank you for your advice,I will try as soon as possible.

**Comment by jvishnuvardhan** [comment] 2020-12-10 03:06
@Ben-Lee-2019 Was this resolved with recent `tf-version` or provide a simple standalone code to reproduce the issue. Thanks!

**Closed** 2020-12-24 04:33 UTC
Labels: TF 2.2, TFLiteConverter, comp:lite, stalled, stat:awaiting response, type:support
