### ISSUE TITLE
 tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine. 

### ISSUE THREAD

**Issue by weisong82** [tensorflow/tensorflow#6896] opened 2017-01-17 08:05 UTC
# export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp27-none-linux_x86_64.whl
# pip install --upgrade $TF_BINARY_URL

then got errors!

**Comment by asimshankar** [comment] 2017-01-17 19:50
Could you please add some detail as to which OS / architecture etc. you're running on (the details asked for in the "New Issue" template)?

That said, it seems that your processor doesn't have AVX2 support and so your best bet is to [install from source](https://www.tensorflow.org/get_started/os_setup#installing_from_sources). Going forward, we haven't yet finalized what architectures are releases should be optimized for, but in general if the architecture is "too old", then you'll have to compile from source instead of using the release.

CCing @petewarden and closing this out as a duplicate of #6809. That issue isn't precisely the same, but it deals with the same overarching problem - what set of optimizations should the releases be built for.

Hope that helps!

**Closed by asimshankar** 2017-01-17 19:50 UTC

**Comment by weisong82** [comment] 2017-01-18 01:58
**I got error even build from source . when run this project.https://github.com/koth/kcws**

Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64)

Linux nlpDemo 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# dmidecode 2.12
SMBIOS 2.8 present.
10 structures occupying 495 bytes.
Table at 0x000F0C80.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: SeaBIOS
	Version: rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.org
	Release Date: 04/01/2014
	Address: 0xE8000
	Runtime Size: 96 kB
	ROM Size: 64 kB
	Characteristics:
		BIOS characteristics not supported
		Targeted content distribution is supported
	BIOS Revision: 0.0

Handle 0x0100, DMI type 1, 27 bytes
System Information
	Manufacturer: QEMU
	Product Name: Standard PC (i440FX + PIIX, 1996)
	Version: pc-i440fx-2.1
	Serial Number: 350d21c1-fd7c-4e8e-a596-bbbb031714a7
	UUID: 350D21C1-FD7C-4E8E-A596-BBBB031714A7
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Handle 0x0300, DMI type 3, 21 bytes
Chassis Information
	Manufacturer: QEMU
	Type: Other
	Lock: Not Present
	Version: pc-i440fx-2.1
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: Unknown
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: Unspecified
	Contained Elements: 0

Handle 0x0400, DMI type 4, 42 bytes
Processor Information
	Socket Designation: CPU 0
	Type: Central Processor
	Family: Other
	Manufacturer: QEMU
	ID: F2 06 03 00 FF FB 8B 0F
	Version: pc-i440fx-2.1
	Voltage: Unknown
	External Clock: Unknown
	Max Speed: Unknown
	Current Speed: Unknown
	Status: Populated, Enabled
	Upgrade: Other
	L1 Cache Handle: Not Provided
	L2 Cache Handle: Not Provided
	L3 Cache Handle: Not Provided
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 8
	Core Enabled: 8
	Thread Count: 1
	Characteristics: None

Handle 0x1000, DMI type 16, 23 bytes
Physical Memory Array
	Location: Other
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 16 GB
	Error Information Handle: Not Provided
	Number Of Devices: 1

Handle 0x1100, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: Unknown
	Data Width: Unknown
	Size: 16384 MB
	Form Factor: DIMM
	Set: None
	Locator: DIMM 0
	Bank Locator: Not Specified
	Type: RAM
	Type Detail: Other
	Speed: Unknown
	Manufacturer: QEMU
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Rank: Unknown
	Configured Clock Speed: Unknown
	Minimum voltage:  Unknown
	Maximum voltage:  Unknown
	Configured voltage:  Unknown

Handle 0x1300, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x000BFFFFFFF
	Range Size: 3 GB
	Physical Array Handle: 0x1000
	Partition Width: 1

Handle 0x1301, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00100000000
	Ending Address: 0x0043FFFFFFF
	Range Size: 13 GB
	Physical Array Handle: 0x1000
	Partition Width: 1

Handle 0x2000, DMI type 32, 11 bytes
System Boot Information
	Status: No errors detected

Handle 0x7F00, DMI type 127, 4 bytes
End Of Table


oot@nlpDemo:~# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
stepping	: 2
microcode	: 0x1
cpu MHz		: 2494.224
cache size	: 30720 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt
bogomips	: 4988.44
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by Noahsark** [comment] 2017-01-30 19:04
I have exactly same issue. My cpu does not support avx2 and it will cause core dumped each time when import tensorflow.

**Comment by jehoshua7** [comment] 2018-01-17 11:51
I had installed DeepSpeech and also a DeepSpeech server. Went to start the server and got an error message - "2018-01-17 08:21:49.120154: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
Aborted (core dumped)"

Apparently I need to compile TensorFlow on the same computer. Is there a list somewhere to match Kubuntu 17.10.1 and a HP Probook 4330S please ?

**Comment by 275761919** [comment] 2018-12-07 02:15
I have exactly same issue
System: Ubuntu 18.04
CPU:  Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz

**Comment by VishvajeetRamanuj** [comment] 2018-12-10 16:35
i have just installed tensorflow and run simple program by copy paste of correct program. I got this error. Does anyone know how to solve??

**Comment by 275761919** [comment] 2018-12-11 09:42
This error ocuured because the computer cpu was too old to support the newer instructions. But we can [compile tensorflow from source](https://www.tensorflow.org/install/source#install_python_dependencies).
