### ISSUE TITLE
Tensorboard callback not writing the training metrics

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#34276] opened 2019-11-14 15:32 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: pip
- TensorFlow version: 2.0.0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: Quadro P5000 (16Gb)

**Describe the current behavior**
When I fit a model that takes time to infer (either with a big enough data size, or enough parameters), the `TensorBoard` calback doesn't log the training metrics (or just the first few epochs), or at least they don't appear on Tensorboard.

Although I first noticed the problem on GPU, it also appears on CPU.

**Describe the expected behavior**
I would like to have the training metrics logged as well.

**Code to reproduce the issue**
```python
import os.path as op
import time

import numpy as np
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.layers import Conv2D, Input
from tensorflow.keras.models import Model

size = 512
im = Input((size, size, 1))
im_conv = Conv2D(512, 3, padding='same', activation='relu')(im)
im_conv = Conv2D(1, 3, padding='same', activation='linear')(im_conv)
model = Model(im, im_conv)
model.compile(loss='mse', optimizer='adam', metrics=['mae'])

data = np.random.rand(1, size, size, 1)

run_id = f'{int(time.time())}'
log_dir = op.join('logs', run_id)
tboard_cback = TensorBoard(
    log_dir=log_dir, 
    histogram_freq=0, 
    write_graph=False, 
    write_images=False, 
    profile_batch=2,
)

model.fit(
    x=data, 
    y=data, 
    validation_data=[data, data], 
    callbacks=[tboard_cback,], 
    epochs=100, 
    verbose=0,
);
```

**Other info / logs**
I have posted an [SO question](https://stackoverflow.com/questions/58823959/tensorboard-callback-not-writing-the-training-metrics) which didn't get too much traction, that's why I am asking here.

Here is what I observe on Tensorboard: 
![tboard_fail_mre](https://user-images.githubusercontent.com/6387497/68871144-48230000-06fc-11ea-8b7b-b4fd317877d7.png)

**Comment by leonardoaraujosantos** [comment] 2019-11-14 18:04
Agree..., have the same issue here, tried your code and the tutorials same issue occurs.

**Comment by psybuzz** [comment] 2019-11-15 18:12
Thanks for the report.  The details look very similar to issue https://github.com/tensorflow/tensorboard/issues/2084.  Currently, there is a bug with TensorBoard's Keras callbacks that prevent training metrics from showing up/updating.

The current workaround for this, while we work on a solution, is to disable profiling entirely by adding `profile_batch=0` to the callback options.

**Comment by psybuzz** [comment] 2019-11-15 18:14
Duplicate of https://github.com/tensorflow/tensorboard/issues/2084

**Closed by psybuzz** 2019-11-15 18:14 UTC
Labels: TF 2.0, comp:tensorboard, stat:awaiting tensorflower, type:bug

**Comment by psybuzz** [comment] 2019-11-15 18:24
Please let us know if the workaround doesn't work!

Side note: I noticed in the screenshot that the Runs selector on the left is more narrow than the full sidebar.  This issue should be fixed in the most recent Tensorboard

**Comment by zaccharieramzi** [comment] 2019-11-18 09:45
The workaround does work, I will follow #2084 to be aware of when the satisfying fix is be available. Thanks for this and the side note!
