### ISSUE TITLE
Bug - freeze_graph producing invalid graph_def in tensorflow 1.4

### ISSUE THREAD

**Issue by GPhilo** [tensorflow/tensorflow#14452] opened 2017-11-10 15:18 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: release 1.4
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: 8/6
- **GPU model and memory**: GTX 970, 4GB
- **Exact command to reproduce**: 

1. Download [dbg.zip](https://github.com/tensorflow/tensorflow/files/1461735/dbg.zip) (contains `graph.pbtxt`, checkpoint and the resulting `frozen_model.pb` generated on my machine .)
2. Unzip and open terminal in the unzipped folder
3. Run <tensorflow_root>/python/tools/freeze_graph.py --input_graph=graph.pbtxt --input_binary=False --input_checkpoint=model.ckpt-1 --output_node_names=softmax_tensor --output_graph=frozen_model_test.pb --clear_devices=True
4. Start python, attempt to import the frozen graph:
```
import tensorflow as tf
from tensorflow.python.platform import gfile
with gfile.FastGFile('frozen_model_test.pb','rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, name='')
```
### Describe the problem
Trying to import the graph, I get this error:
> ValueError: graph_def is invalid at node 'IsVariableInitialized': Input tensor 'global_step:0' Cannot convert a tensor of type int64 to an input of type int64_ref.

The error is raised in `tf.import_graph_def(graph_def, name='')`. The dump of `str(graph_def)` can be seen in this text file: [graph_def_dbg.txt](https://github.com/tensorflow/tensorflow/files/1461768/graph_def_dbg.txt)

The error happens sine the upgrade to TF 1.4, with TF 1.3 the graph freezing and importing works as expected.

**Comment by bignamehyp** [comment] 2017-11-10 17:32
Looks like a bug in freeze graph, right @petewarden ?

**Comment by asoehlke** [comment] 2017-11-12 20:52
@GPhilo: Have you tried to blacklist IsVariableInitialized with the --variable_names_blacklist argument?
I had the same issue with my graph, which were solved by blacklisting the variables.
The problematic variables were used in model to transfer the states of rnn cells from one iteration to another, these really had to remain variables and must not be converted to constants.

**Comment by GPhilo** [comment] 2017-11-13 08:55
@asoehlke Just tried that, still the same error

**Comment by asoehlke** [comment] 2017-11-13 20:11
I have a similar problem with non-trainable variables (trainable=False) which are also modified within the model. A description of what I found out so far is below.

@GPhilo: Can it be that the value of global_step is modified when processing the model? The name sounds like a kind of counter?
If it is modeled like this then I guess it needs to remain a variable, a const value could not be changed in the model.


Unfortunately, blacklisting the variables seems not to be enough, when trying to use the model I now got the error that these variables are not initialized:
Attempting to use uninitialized value rnn_state_c_0
	 \[\[Node: rnn_state_c_0/read = Identity\[T=DT_FLOAT, _class=["loc:@rnn_state_c_0"], _device="/job:localhost/replica:0/task:0/cpu:0"](rnn_state_c_0)]]

Some further investigation: The init node of the model is gone in the frozen model. 
In the attached files:
- BachAccompanist.exported.pbtxt is the original exported graph
- BachAccompanist.patched.pbtxt is a patched version of the exported graph, I manually copied the init node to a new node "initVars" and kept only the blacklisted variables as input.

When I imported the patched frozen graph and ran the initVars node first, then the "uninitialized variables" error is gone.
I reexported this model that I imported from the frozen model as BachAccompanist.frozen.reexported.pbtxt

Unfortunatly I now seem to get only get a None result when running the model:
 output_step = sess.run("output", {in_data : tick_data})
 print(output_step)
-> None
But this might also be a different problem.

Suggestions:
- when freezing the model it would be good to have an option to only freeze the trainable variables. 
- the init node should remain for the blacklisted variables 

**System information**

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Studio 16.04
    TensorFlow installed from (source or binary): source and binary
    TensorFlow version (use command below): release 1.4.0
    Python version: 3.6.3 (source installation), 3.4.5 (binary installation)
    Bazel version (if compiling from source): 0.7.0
    GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
    CUDA/cuDNN version: -
    GPU model and memory: -
    Exact command to reproduce:
freeze_graph --input_checkpoint BachAccompanist.pb.ckpt --input_graph BachAccompanist.exported.pbtxt --output_node_names output,state_update,initVars --input_binary False  --variable_names_blacklist rnn_state_h_0,rnn_state_c_0,rnn_state_h_1,rnn_state_c_1,rnn_state_h_2,rnn_state_c_2,rnn/multi_rnn_cell/cell_0/lstm_cell/w_f_diag,rnn/multi_rnn_cell/cell_0/lstm_cell/w_i_diag,rnn/multi_rnn_cell/cell_0/lstm_cell/w_o_diag,rnn/multi_rnn_cell/cell_1/lstm_cell/w_f_diag,rnn/multi_rnn_cell/cell_1/lstm_cell/w_i_diag,rnn/multi_rnn_cell/cell_1/lstm_cell/w_o_diag,rnn/multi_rnn_cell/cell_2/lstm_cell/w_f_diag,rnn/multi_rnn_cell/cell_2/lstm_cell/w_i_diag,rnn/multi_rnn_cell/cell_2/lstm_cell/w_o_diag --output_graph BachAccompanist.frozen.pb

Used models:
[models.zip](https://github.com/tensorflow/tensorflow/files/1468266/models.zip)

**Comment by GPhilo** [comment] 2017-11-21 09:18
Any updates on this?

From what I could see, it seems `freeze_graph` fails to remove the `global_step/*` part of the graph. I believe this is due to the introduction of the initialization check for `global_step`, which introduces an `add` node whose control output is then input to many `Const` or `NoOp` further nodes in the graph.

It seems that the control input breaks `tensorflow.python.framework.graph_util_impl.convert_variables_to_constants()`. This is because, without the control output of the `add` node, the `global_step` subgraph is not connected to the graph output, so it gets pruned when calling `convert_variables_to_constants`. Since now there is a control input based on `add`, however, the function doesn't automatically prune the `global_step` and things break.

This is the only node in the frozen graph where the `^add` input is still preserved:
```
node {
  name: "Reshape_1/shape"
  op: "Const"
  input: "^add"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
          dim {
            size: 2
          }
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\377\377\377\377\000\006\000\000"
      }
    }
  }
}
```

What is the purpose of this control input?

**Comment by asoehlke** [comment] 2017-11-28 22:34
Hello @GPhilo,
I solved my issue now by defining the initial values of the problematic variables as additional placeholders.
This means I have to feed the initializing values additionally when using the model, but at least this got the model usable.
The initializers are the init_states variables in https://github.com/asoehlke/neuronal-music-accompanist-bach/blob/master/MusicAccompanistInferenceGraph.ipynb.

With this change, freeze_graph works without any blacklisted variables.

**Comment by GPhilo** [comment] 2017-11-29 09:01
@asoehlke for my use-case though, everything has to be made constant, since I won't be running inference in tensorflow.

**Comment by tensorflowbutler** [comment] 2017-12-20 01:24
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:01
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by dratini6** [comment] 2018-01-12 18:53
I also experienced this issue and got exactly the same error message. My model was also trained on tensorflow 1.4. Any updates on this issue?

**Comment by Tauranis** [comment] 2018-01-15 17:45
Same as @dratini6 .

**Comment by dratini6** [comment] 2018-01-16 18:59
Thanks @Tauranis.  I tried your suggestion and it worked perfectly!

**Comment by GPhilo** [comment] 2018-01-18 11:24
Also from me, thank you very much, this does solve the problem.

As a comment, for those like me using directly `freeze_graph.py` as a script, add the argument `--variable_names_blacklist=global_step` to the call instead of modifying the python script itself.

I won't close the issue yet (although, given the attention it received, that would make no difference..) since the original problem is IMO still there (the script should output a valid file without the need for users to know they have to exclude a variable to make it work).

**Comment by Tauranis** [comment] 2018-01-18 15:05
I believe the problem is that the global_step cannot be converted to a constant.
More over. After freezing the graph, some weird ops regarding global step appear on my graph, mainly on batch norm ops. And by then, the quantization could not be done. On issue #3628  I present a workaround that worked for me.

**Comment by GPhilo** [comment] 2018-01-19 09:31
Ok, what seemed to work yesterday is not working anymore...

I also tried modifying the call to `tf.graph_util.convert_variables_to_constants` in `python/tools/freeze_graph.py` as follows:

```
if input_meta_graph_def:
      output_graph_def = graph_util.convert_variables_to_constants(
          sess,
          input_meta_graph_def.graph_def,
          output_node_names.split(","),
          variable_names_whitelist=variable_names_whitelist,
          variable_names_blacklist=variable_names_blacklist + ['global_step'])
    else:
      output_graph_def = graph_util.convert_variables_to_constants(
          sess,
          input_graph_def,
          output_node_names.split(","),
          variable_names_whitelist=variable_names_whitelist,
          variable_names_blacklist=variable_names_blacklist + ['global_step'])
```

but once I convert the generated .pb file back to .pbtxt to inspect it, I get:

```
node {
  name: "global_step/Initializer/zeros"
  op: "Const"
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@global_step"
      }
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT64
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT64
        tensor_shape {
        }
        int64_val: 0
      }
    }
  }
}
node {
  name: "global_step"
  op: "VariableV2"
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@global_step"
      }
    }
  }
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
        }
      }
    }
  }
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT64
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
```

For conversion I use this code:
```
def graphdef_to_pbtxt(filename): 
  with gfile.FastGFile(filename,'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, name='')
    tf.train.write_graph(graph_def, 'pbtxt/', 'protobuf.pbtxt', as_text=True)
  return
```

I really don't understand, even when I explicitly exclude global_step, it ends up in the frozen file as a variable.

**Comment by GPhilo** [comment] 2018-01-19 11:38
I found a workaround by deleting via script any `input: "^add"` line from the `graph.pbtxt` file before running `freeze_graph`. This way, the global_step branch of the graph is not connected anymore to the inference graph and is correctly removed by `convert_variables_to_constants`.

**Comment by tensorflowbutler** [comment] 2018-02-06 07:45
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-07 13:23
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 01:01
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by reedwm** [comment] 2018-03-28 01:19
/CC @petewarden can you take a look at this issue?

**Comment by tensorflowbutler** [comment] 2018-04-12 12:35
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-27 18:42
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-12 18:32
Nagging Assignee @petewarden: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 12:37
Nagging Assignee @petewarden: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-11 18:48
Nagging Assignee @petewarden: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-26 12:42
Nagging Assignee @petewarden: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-11 12:47
Nagging Assignee @petewarden: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-26 19:10
Nagging Assignee @petewarden: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-14 19:46
Nagging Assignee @petewarden: It has been 135 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:52
Nagging Assignee @petewarden: It has been 156 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:32
Nagging Assignee @petewarden: It has been 171 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:43
Nagging Assignee @petewarden: It has been 186 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:44
Nagging Assignee @petewarden: It has been 201 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:39
Nagging Assignee @petewarden: It has been 216 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 18:57
Nagging Assignee @petewarden: It has been 231 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-29 19:03
Nagging Assignee @petewarden: It has been 246 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2019-02-23 00:14
Since there are workarounds and this is pretty old, closing this issue.

**Closed by petewarden** 2019-02-23 00:14 UTC
