### ISSUE TITLE
Allow slots to be initialized with different shapes + values than primary var in Keras optimizer

### ISSUE THREAD

**Issue by mathemakitten** [tensorflow/tensorflow#41675] opened 2020-07-23 20:05 UTC
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): probably not

**Describe the feature and the current behavior/state.**
Currently the `add_slot` method in the optimizer class [(link)](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L694-L730) only allows you to create slots which are the same shape as the original var, and you cannot set it to a custom value (i.e. it forces you to use an initializer).

**Will this change the current api? How?**
Either `add_slot` should be modified to include this functionality, or there should be a tf.keras equivalent to the old `_get_or_make_slots` method which gives the developer the option to pass in a value for the slot to be initialized with (which may be a different shape than the var). 

**Who will benefit with this feature?**
Anyone implementing custom optimizers which require slots which may be custom values or shapes (i.e. the SM3 optimizer creates accumulators which are differently shaped than their corresponding vars).

**Any Other info.**
This feature seems to be present in the base optimizer class via `_get_or_make_slot` which calls [create_slot()](https://github.com/tensorflow/tensorflow/blob/d8dcead44017aa0381ca16254a161099eeb7c2e4/tensorflow/python/training/slot_creator.py#L104), which allows you to pass in an initial value.

**Comment by cserpell** [comment] 2020-09-01 21:52
Maybe you can use hyper parameters, check [this question](https://stackoverflow.com/questions/62042342/what-are-get-hyper-and-set-hyper-in-tensorflow-optimizers).

**Comment by amitport** [comment] 2020-09-20 08:56
duplicate of https://github.com/tensorflow/tensorflow/issues/19457 (opened May 2018...)

**Comment by jvishnuvardhan** [comment] 2022-02-25 18:21
@mathemakitten Since it was opened long time back, I would like to know whether there is any actionable items like raising PR? If this is still an issue and want to contribute, please feel free to open this issue in keras-team/keras repo.

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues). Thanks!

**Closed** 2022-03-11 19:27 UTC
Labels: stat:awaiting response, type:feature, stalled, comp:keras
