### ISSUE TITLE
 ./tensorflow/contrib/lite/java/build_aar_for_release.sh command build .so library failed 

### ISSUE THREAD

**Issue by JuiYang** [tensorflow/tensorflow#21671] opened 2018-08-17 06:51 UTC
### Output information for the command :
```
++ mktemp -d
+ TMPDIR=/tmp/tmp.1epU8vtRBz
+ trap 'rm -rf /tmp/tmp.1epU8vtRBz' EXIT
+ VERSION=1.0
+ BUILDER=bazel
+ BASEDIR=tensorflow/contrib/lite
+ CROSSTOOL=//external:android/crosstool
+ HOST_CROSSTOOL=@bazel_tools//tools/cpp:toolchain
+ BUILD_OPTS='--cxxopt=--std=c++11 -c opt'
+ CROSSTOOL_OPTS='--crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain'
+ test -d tensorflow/contrib/lite
+ rm -rf /tmp/tmp.1epU8vtRBz
+ mkdir -p /tmp/tmp.1epU8vtRBz/jni
+ build_basic_aar /tmp/tmp.1epU8vtRBz
+ local OUTDIR=/tmp/tmp.1epU8vtRBz
+ bazel build --cxxopt=--std=c++11 -c opt tensorflow/contrib/lite/java:tensorflowlite.aar
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //tensorflow/contrib/lite/java:tensorflowlite.aar (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/java:tensorflowlite.aar up-to-date:
  bazel-bin/tensorflow/contrib/lite/java/tensorflowlite.aar
INFO: Elapsed time: 0.499s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
+ unzip -d /tmp/tmp.1epU8vtRBz bazel-bin/tensorflow/contrib/lite/java/tensorflowlite.aar
Archive:  bazel-bin/tensorflow/contrib/lite/java/tensorflowlite.aar
  inflating: /tmp/tmp.1epU8vtRBz/AndroidManifest.xml  
  inflating: /tmp/tmp.1epU8vtRBz/classes.jar  
   creating: /tmp/tmp.1epU8vtRBz/res/
  inflating: /tmp/tmp.1epU8vtRBz/R.txt  
+ sed -i -e 's/<application>/<uses-sdk android:targetSdkVersion="25"\/><application>/' /tmp/tmp.1epU8vtRBz/AndroidManifest.xml
+ build_arch arm64-v8a arm64-v8a /tmp/tmp.1epU8vtRBz
+ local ARCH=arm64-v8a
+ local CONFIG=arm64-v8a
+ local OUTDIR=/tmp/tmp.1epU8vtRBz
+ mkdir -p /tmp/tmp.1epU8vtRBz/jni/arm64-v8a/
+ bazel build --cxxopt=--std=c++11 -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=arm64-v8a tensorflow/contrib/lite/java:libtensorflowlite_jni.so
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //tensorflow/contrib/lite/java:libtensorflowlite_jni.so (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/tclxa/tensorflow/tensorflow/contrib/lite/profiling/BUILD:37:1: C++ compilation of rule '//tensorflow/contrib/lite/profiling:time' failed (Exit 1)
In file included from tensorflow/contrib/lite/profiling/time.cc:15:
./tensorflow/contrib/lite/profiling/time.h:18:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
Target //tensorflow/contrib/lite/java:libtensorflowlite_jni.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.575s, Critical Path: 0.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
+ rm -rf /tmp/tmp.1epU8vtRBz
```
when I try again, this information would changed.
```
.....
.....
.....
ERROR: /home/tclxa/tensorflow/tensorflow/contrib/lite/BUILD:272:1: C++ compilation of rule '//tensorflow/contrib/lite:util' failed (Exit 1)
In file included from tensorflow/contrib/lite/util.cc:15:
./tensorflow/contrib/lite/util.h:24:10: fatal error: 'vector' file not found
#include <vector>
         ^
1 error generated.
Target //tensorflow/contrib/lite/java:libtensorflowlite_jni.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
....
....
```

It`s a kind of problem.  I try to change gcc-5.4 into gcc-4.7 and g++-5.4 into g++-4.7 .  but its don`t work. so how to solve this problem,  very thanks.

**Comment by tensorflowbutler** [comment] 2018-08-17 18:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by JuiYang** [comment] 2018-08-20 01:32
OS Platform and Distribution
ubuntu 16.04LTS

TensorFlow installed from
Source
TensorFlow version
tensorflow-1.9.0
CUDA/cuDNN version
N/A
GPU model and memory
N/A
Exact command to reproduce
sudo  ./tensorflow/contrib/lite/java/build_aar_for_release.sh 
Mobile device
N/A

**Comment by tensorflowbutler** [comment] 2018-09-04 19:04
Nagging Assignee @miaout17: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment] 2018-09-13 19:54
What Android NDK revision are you using?

**Comment by tensorflowbutler** [comment] 2018-09-28 12:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-14 18:38
Nagging Assignee @jdduke: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment] 2018-10-16 17:05
Looks like this might have been fixed in https://github.com/bazelbuild/bazel/issues/5585. Can you give it another try?

**Comment by jdduke** [comment] 2018-10-16 17:19
I was able to compile with NDK r18b (on Linux) using the latest bazel build. Feel free to reopen if you find otherwise.

**Closed by jdduke** 2018-10-16 17:19 UTC
Labels: comp:lite
