### ISSUE TITLE
LazyAdamOptimizer  is not faster than AdamOptimizer 

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#27456] opened 2019-04-03 09:24 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux redhat
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
1.12
- Python version:
Python 3.6.8 |Anaconda,
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
There are 2.7 hundred million variables in my embedding files.And instread of adamOptimer,i used lazyadam.But it cost the same time as adamOptimizer
**Describe the expected behavior**
it should be faster than adamOptimizer when sparse update.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
return tf.estimator.DNNClassifier(
        model_dir=FLAGS.model_dir,
        feature_columns=deep_columns,
        #optimizer=tf.train.AdamOptimizer(learning_rate=0.001),
        optimizer =  tf.contrib.opt.LazyAdamOptimizer(learning_rate = 0.001),
        hidden_units=hidden_units,
        config=my_checkpointing_config
```
and it cost 200s for every 100 steps ,the same time as AdamOptimizer

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by dshahid380** [comment] 2019-04-04 08:01
I would like to work on this issue.

**Comment by achandraa** [comment] 2019-04-04 12:34
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by achandraa** [comment] 2019-04-12 12:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-12 12:58 UTC
Labels: comp:ops, type:support
