### ISSUE TITLE
Import statement for Tensorflow returning error

### ISSUE THREAD

**Issue by jothamsl** [tensorflow/tensorflow#34561] opened 2019-11-24 14:46 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.6.2
- Installed using: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- UserBenchmarks: Game 11%, Desk 12%, Work 11%
- CPU: Intel Pentium D 3.40GHz - 1.4%
- GPU: Nvidia GeForce 8600 GT - 1%
- HDD: Seagate Barracuda 7200.10 320GB - 17.9%
- USB: JetFlash Transcend 8GB - 1.5%
- RAM: Unknown 3GB - 2.8%
- MBD: Gigabyte GA-945PL-S3

<em>Hi, I recently installed tensorflow using pip (after going through so much problems), and just when i tried to import tensorflow as tf in my project it returns this error:</em>

<p>Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lase\Documents\Programming stuff\Python\demo 1\.vs\demo 1\main.py", line 137, in <module>
    import tensorflow as tf
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
</p>

<em>Steps taken to solve problem</em>
1. Repeatedly uninstalling and reinstalling tensorflow to see any change, but none worked
2. I also noticed the same thing happens when i try to import keras . Keras tries to import tensorflow and returns the same error
3. Tried installing it on a virtual environment using virtualenv but still didnt work

**Comment by nikochiko** [comment] 2019-11-24 17:53
Maybe a duplicate of https://github.com/tensorflow/tensorflow/issues/19584.
@jothamsl , you have installed with pip which means you have installed the binary and not from the source. Please make that correction. Thank you.

**Comment by ymodak** [comment] 2019-11-25 19:28
**Installing **TensorFlow** (TF) prebuilt binaries**

*TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.*

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

*Please let us know if this helps.*

**Comment by jothamsl** [comment] 2019-12-01 10:09
<p>Ok i'm using Google colab and it works perfectly, thanks!</p>

**Closed** 2019-12-01 10:09 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install
