### ISSUE TITLE
Duplication indices in the results of hessian_vector_product()

### ISSUE THREAD

**Issue by ZHTLoveYC** [tensorflow/tensorflow#30903] opened 2019-07-20 19:48 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code.
- OS Platform and Distribution: Ubuntu 18.04.
- TensorFlow installed from pip
- TensorFlow version 1.14 with GPU support
- Python version: 3.7.3
- CUDA/cuDNN version: 10

**Describe the current behavior**

Hi, when I am using the hessian_vector_product() to computer the hessian_vector_product of my model, it returns results organized as IndexedSliceValue. This is OK because the model include data structure like embeddings. 

However, when I do the assert on the indices of the returned IndexedSliceValue. I notice that there are duplicated indices with different corresponding values. May I know how to deal with these conflict <indices, values>? Thanks in advance.

**Comment by anush-o** [comment] 2019-07-22 11:25
@ZHTLoveYC ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by anush-o** [comment] 2019-07-30 11:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by anush-o** 2019-07-30 11:14 UTC
Labels: TF 1.14, comp:ops, stat:awaiting response, type:support
