### ISSUE TITLE
tf.ragged.map_flat_values with tf.argmax on ragged axis produces wrong operation

### ISSUE THREAD

**Issue by stevemance** [tensorflow/tensorflow#37397] opened 2020-03-06 18:21 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): Pip
 - TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: Python 3.7.4
- Bazel
version (if compiling from source): N/A
- GCC/Compiler version (if compiling from
source): N/A
- CUDA/cuDNN version: V10.1.243
- GPU model and memory: GeForce RTX 2080 8G

**Describe the current behavior**
Using a RaggedTensor flat mapped into tf.argmax and the flattened ragged dimension as the axis to argmax against, the wrong shape/operation results.  [batch, None, N] using map_flat_values(tf.argmax, <tensor>, -2) results in a [batch, None] tensor.

**Describe the expected behavior**
I'd expect to result in a [batch, N] tensor.

**Standalone code to reproduce the issue** 
```
import tensorflow as tf
foo = tf.ragged.constant([[[0,1],[2,3]],[[4,5]],[[6,7]],[[8,9]]], dtype=tf.int64, ragged_rank=1)

# Mapped into the ragged axis (should produce a [4, 2])
bar = tf.ragged.map_flat_values(tf.argmax, foo, -2)
bar
<tf.RaggedTensor [[4, 4], [], [], []]>
bar.shape
TensorShape([4, None])

# Mapped into the non-ragged axis
bar = tf.ragged.map_flat_values(tf.argmax, foo, -1)
bar
<tf.RaggedTensor [[1, 1], [1], [1], [1]]>
# Notice the same shape...
bar.shape
TensorShape([4, None])
```
What I expect is something like this:
```
import tensorflow as tf
foo = tf.ragged.constant([[[0,1],[2,3]],[[4,5]],[[6,7]],[[8,9]]], dtype=tf.int64, ragged_rank=1)
row_splits = foo.row_splits
old_row=row_splits[0]
bar = []
for row in row_splits[1:]:
    bar.append(tf.argmax(foo.values[old_row:row, ...],-2))
    old_row=row
bar = tf.stack(bar)
bar
<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0]])>
bar.shape
TensorShape([4, 2])
```

**Comment by ravikyram** [comment] 2020-03-09 09:23
I have tried on colab with TF version 2.1.0 beta,2.2.0-dev20200308 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1344668f02641b79a34e585d3e1b7f2c/untitled713.ipynb). Thanks!

**Comment by leandro-gracia-gil** [comment] 2020-05-22 12:35
I'm also hitting this bug in TF 2.2. Are there updates on this?

Some temporary workaround for argmax in ragged tensors that does not involve manually looping the ragged dimension or relying on eager mode would be much appreciated.

**Comment by leandro-gracia-gil** [comment] 2020-05-23 08:29
I'm using tf.argmax(ragged_tensor.to_tensor(np.NINF), axis) as an alternative for now.

**Comment by edloper** [comment] 2020-06-15 14:16
`tf.ragged.map_flat_values(tf.argmax, foo, -2)` **should** raise an exception, since you're constructing an invalid RaggedTensor.  In particular, this is equivalent to the following, which *does* raise an exception:

```
>>>foo.with_flat_values(tf.argmax(foo.flat_values, -2))
ValueError: Shapes (5,) and (2,) are incompatible
```

I'll look into adding a shape check that will make map_flat_values fail here.

In general, `map_flat_values` should only be used on operations that operate independently on rows of a ragged tensor -- in particular, the number of rows that the function returns needs to match the number of rows in the original version.  This is trivially true for elementwise operations.  Operations that do aggregation within rows are ok too.  But operations that do aggregation ***across*** rows are not.  In your case, `foo.flat_values` is a 2D tensor, so doing argmax with axis=-2 reduces across those values.  I.e., this is what's effectively happening in your code:

```
new_values = tf.argmax(foo.flat_values, -2)  # = [4, 4]
bar = tf.RaggedTensor.from_row_lengths(new_values, foo.row_lengths())
```

This is invalid, since the row_lengths indicates that we should have 5 values, but we only have 2.

Your work-around of using to_tensor seems reasonable.  I think it would also be possible to put together a solution based on `tf.map_fn`, but it would probably be more complex and slower.

**Comment by edloper** [comment] 2020-08-10 19:13
Closing this issue, since the behavior is expected.  I will add a static shape check that should give a better error message.

**Closed by edloper** 2020-08-10 19:13 UTC
Labels: TF 2.1, comp:ops, type:bug
