### ISSUE TITLE
session->Run

### ISSUE THREAD

**Issue by tianhongbao** [tensorflow/tensorflow#37833] opened 2020-03-23 14:49 UTC
```
/home/sy/tf_test/mnist/tf.cpp: In function ‘int main(int, char**)’:
/home/sy/tf_test/mnist/tf.cpp:219:142: error: no matching function for call to ‘tensorflow::Session::Run(<brace-enclosed initializer list>, <brace-enclosed initializer list>, <brace-enclosed initializer list>, std::vector<tensorflow::Tensor>*)’
 n = session->Run({{inputt, inputm}}, {"code2str_conversion/chars_conversion/cond/Merge:0","init_all_tables"}, {}, &outputs);
                                                                                                                           ^
In file included from /home/sy/tf_test/mnist/tf.cpp:25:0:
/home/sy/tensorflow/tensorflow/core/public/session.h:121:18: note: candidate: virtual tensorflow::Status tensorflow::Session::Run(const std::vector<std::pair<std::__cxx11::basic_string<char>, tensorflow::Tensor> >&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<tensorflow::Tensor>*)
   virtual Status Run(const std::vector<std::pair<string, Tensor> >& inputs,
                  ^~~
/home/sy/tensorflow/tensorflow/core/public/session.h:121:18: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<std::pair<std::__cxx11::basic_string<char>, tensorflow::Tensor> >&’
/home/sy/tensorflow/tensorflow/core/public/session.h:150:18: note: candidate: virtual tensorflow::Status tensorflow::Session::Run(const tensorflow::RunOptions&, const std::vector<std::pair<std::__cxx11::basic_string<char>, tensorflow::Tensor> >&, const std::vector<std::__cxx11::basic_string<char> >&, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<tensorflow::Tensor>*, tensorflow::RunMetadata*)
   virtual Status Run(const RunOptions& run_options,
                  ^~~
/home/sy/tensorflow/tensorflow/core/public/session.h:150:18: note:   candidate expects 6 arguments, 4 provided
CMakeFiles/tf_test.dir/build.make:62: recipe for target 'CMakeFiles/tf_test.dir/tf.cpp.o' failed
make[2]: *** [CMakeFiles/tf_test.dir/tf.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tf_test.dir/all' failed
make[1]: *** [CMakeFiles/tf_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

when I run a model of EAST,the program run successfully。
But,when I run the second model, the program fails.(python ok )
Can the C ++ API initialize the model?

（ubuntu18.04,tensorflow c++ 1.13）

**Comment by ravikyram** [comment] 2020-03-24 05:41
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github new issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tianhongbao** [comment] 2020-03-24 10:22
What statement should I use to initialize in C ++.
python code:
`sess_id.run(graph_id.get_operation_by_name("MyGraphID/init_all_tables")) `


other infermation:
```
def initialize_all_tables(name="init_all_tables"):
  """Returns an Op that initializes all tables of the default graph.

  Args:
    name: Optional name for the initialization op.

  Returns:
    An Op that initializes all tables.  Note that if there are
    not tables the returned Op is a NoOp.
  """
  return tables_initializer(name)


@tf_export(v1=["initializers.tables_initializer", "tables_initializer"])
def tables_initializer(name="init_all_tables"):
  """Returns an Op that initializes all tables of the default graph.

  Args:
    name: Optional name for the initialization op.

  Returns:
    An Op that initializes all tables.  Note that if there are
    not tables the returned Op is a NoOp.
  """
  initializers = ops.get_collection(ops.GraphKeys.TABLE_INITIALIZERS)
  if initializers:
    return control_flow_ops.group(*initializers, name=name)
  return control_flow_ops.no_op(name=name)

```

**Comment by mihaimaruseac** [comment] 2020-03-27 20:09
Please fill in issue template and don't just paste error message with no formatting.

TF 1.13 is no longer supported. Can you try 1.15 or 2.1 or master instead?

**Comment by jvishnuvardhan** [comment] 2020-04-17 18:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-04-17 18:18 UTC
Labels: TF 1.13, comp:runtime, type:support
