### ISSUE TITLE
Eigen core linking errors (iOS camera example)

### ISSUE THREAD

**Issue by graphific** [tensorflow/tensorflow#2799] opened 2016-06-11 06:24 UTC
when compiling the ios camera example there's a few linking errors where it cant link to:
`#include <Eigen/src/Core/util/DisableStupidWarnings.h>`
a simple hack does the trick. 

Replace with:
`#include "../../../Eigen/src/Core/util/DisableStupidWarnings.h" `
in Eigen/Core and a couple of other places (Tensor)

similar for
`#include "../../../Eigen/src/Core/util/ReenableStupidWarnings.h"`
instead of 
`#include <Eigen/src/Core/util/ReenableStupidWarnings.h>
`

**Comment by StephenOman** [comment] 2016-06-11 13:59
This is being caused by changes to the version of Eigen being used by TensorFlow.

To fix this without changing the code, modify the Header Search Paths reference to Eigen in Xcode to the version in makefile/downloads/.

For example, change
`$(SRCROOT)/../../makefile/downloads/eigen-eigen-d02e6a705c30`
to
`$(SRCROOT)/../../makefile/downloads/eigen-eigen-5f86b31739cd`

**Comment by benoitsteiner** [comment] 2016-06-13 19:02
This appears to be due to an incorrect iOS Makefile that attempts to link against version d02e6a705c30 instead of version 5f86b31739cd of the Eigen codebase. This is fixed in [pull request 2805](https://github.com/tensorflow/tensorflow/pull/2805/files).

**Comment by prb12** [comment] 2016-06-20 16:18
Closing as fixed.  Please sync to most recent versions, and reopen if the problem reoccurs.

**Closed by prb12** 2016-06-20 16:18 UTC
