### ISSUE TITLE
Operation missing on iOS despite being added to tf_op_files.txt and ops_to_register.h

### ISSUE THREAD

**Issue by naktinis** [tensorflow/tensorflow#17956] opened 2018-03-23 17:00 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.3
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.7.0-rc1
- **Python version**: 2.7.10
- **Bazel version (if compiling from source)**: bazel release 0.11.1-homebrew
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.0.0 (clang-900.0.39.2)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
I believe it's a bug. We're trying to run a TensorFlow model on an iOS app by performing the steps described in the [official](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#optimization) [docs](https://www.tensorflow.org/mobile/prepare_models). I've previously successfully built and ran this graph and its related libraries on Android.

We build the libraries like this:

    tensorflow/contrib/makefile/build_all_ios.sh -a arm64 -g our_inference_graph.pb

We make sure the operations in question (`fft_ops.cc`) are built:

1. `tensorflow/core/framework/ops_to_register.h` contains `|| isequal(op, "RFFT")`

1. `android_extended_ops_group1` in `tensorflow/core/kernels/BUILD` contains `fft_ops.cc`

1. `tensorflow/contrib/makefile/tf_op_files.txt` contains `tensorflow/core/kernels/fft_ops.cc`

1. The fft object file is built as `tensorflow/contrib/makefile/gen/obj/fft_ops.o`

However, we get the following error when loading the graph:

    2018-03-23 13:04:06.618259: E tensorflow/core/framework/op_kernel.cc:1197] OpKernel ('op: "RFFT" device_type: "CPU"') for unknown op: RFFT
    2018-03-23 13:04:06.618616: E <App path>/TensorFlow/Adapter/TensorFlowUtils.mm:152] Could not create TensorFlow Graph: Not found: Op type not registered 'RFFT' in binary running on Foolish. Make sure the Op and Kernel are registered in the binary running in this process.
    2018-03-23 13:04:06.618827: F <App path>/TensorFlow/Adapter/TensorFlowProcessor.mm:73] Couldn't load model: Not found: Op type not registered 'RFFT' in binary running on Foolish. Make sure the Op and Kernel are registered in the binary running in this process.

Here's my question on SO (no repsonse): https://stackoverflow.com/questions/49452489/opkernel-op-rfft-device-type-cpu-for-unknown-op-rfft

Related issues: issues #15921 and #5518 suggest adding the operation to `tf_op_files.txt`, which we've done (see above).

### Source code / logs
Here's how we load the graph: https://gist.github.com/nerthase/22f54c040a195f87b7a9b241536be2a1

**Comment by tensorflowbutler** [comment] 2018-03-25 00:47
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by reedwm** [comment] 2018-03-26 21:30
/CC @petewarden, can you take a look?

**Comment by nerthase** [comment] 2018-03-29 15:29
The issue is still here with latest release, 1.7.0.

**Comment by tensorflowbutler** [comment] 2018-04-13 18:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by nerthase** [comment] 2018-04-16 16:01
Yes, I'm still having this issue. Maybe the tag `avaiting response` is no more valid? @naktinis

**Comment by naktinis** [comment] 2018-04-27 13:31
@petewarden is there anything else we could provide that would make it easier for you to look into this issue?

**Comment by tensorflowbutler** [comment] 2018-05-12 18:33
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 12:36
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-11 18:49
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by naktinis** [comment] 2018-06-15 16:11
Could someone please look into this issue?

**Comment by tensorflowbutler** [comment] 2018-06-30 18:33
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-15 18:34
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-30 18:49
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:53
Nagging Assignee @petewarden: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by NPetsky** [comment] 2018-08-22 10:06
I don't know if this is still an issue for you but I think you also have to add tensorflow/core/ops/spectral_ops.cc to tf_op_files.txt because in this file the RFFT-op is registered

**Comment by tensorflowbutler** [comment] 2018-09-06 18:53
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-21 19:00
Nagging Assignee @petewarden: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-06 18:39
Nagging Assignee @petewarden: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-05 18:54
Nagging Assignee @petewarden: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 13:20
Nagging Assignee @petewarden: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-05 18:56
Nagging Assignee @petewarden: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2019-02-23 00:25
We're deprecating the older iOS mainline TensorFlow build process in favor of TF Lite, so closing this issue.

**Closed by petewarden** 2019-02-23 00:25 UTC
