### ISSUE TITLE
CTC Beam Search Decoder in TensorFlow android

### ISSUE THREAD

**Issue by im-ranu** [tensorflow/tensorflow#33242] opened 2019-10-11 10:14 UTC
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):
How to decode output float array into string using CTC beam search decoder in android. I'm not using tflite as of now. 

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined
Float Array
Are return values defined? 
Yes

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by oanush** [comment] 2019-10-15 10:50
@im-ranu ,
Can you provide documentation link where the issue is being faced ?Thanks!

**Comment by oanush** [comment] 2019-10-22 09:48
@im-ranu ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2019-10-29 09:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-10-29 09:48 UTC
Labels: comp:lite, stat:awaiting response, type:docs
