### ISSUE TITLE
The gif encoding and decoding is not lossless in tf and tfio

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#54266] opened 2022-02-04 06:53 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: running on CPU
- GPU model and memory: running on CPU

**Describe the current behavior**
The gif encoding and decoding is not lossless. The input after gif encoding and decoding is not equivalent to the original input.

**Describe the expected behavior**
The image encoded by gif and then decoded should be lossless.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
need to install tensorflow=2.7.0 and tensorflow_io=0.22.0
```
import tensorflow as tf
import tensorflow_io as tfio
import numpy as np

input = np.array(
    [[[[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,],],
    [[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,],],
    [[13, 54, 87,],
    [56, 210, 195,],
    [230, 135, 61,]]]]
)

input_uint8 = tf.cast(input, tf.uint8)
encoded_file = tfio.image.encode_gif(input_uint8)
input_decoded = tf.io.decode_gif(encoded_file) 
print(np.allclose(input_uint8, input_decoded))  # False
```
The input after gif encoding and decoding is not equivalent to the original input. But gif itself should be lossless.

**Comment by Curry-yilongxu** [comment] 2022-02-04 11:08
k

**Comment by tilakrayal** [comment] 2022-02-07 04:17
@jiannanWang ,
I was facing different error while executing the mentioned code.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/361adb568f56a2339301b18749337680/untitled215.ipynb) and confirm.

**Comment by jiannanWang** [comment] 2022-02-07 04:27
Hi tilakrayal! Thank you for your response. I found a bug in my code. It lies in the last line and I've fixed that. I confirmed on the gist that the fixed code is working as I expected. Can you please try it again?

**Comment by tilakrayal** [comment] 2022-02-07 04:31
@jiannanWang ,
Can you pleaase feel free to close the issue as it is related to code and got resolved.Thanks!

**Comment by jiannanWang** [comment] 2022-02-07 04:33
There might be some misunderstanding. The problem is not solved. I fixed my code so now it can trigger the bug of gif encoding and decoding.

**Comment by tilakrayal** [comment] 2022-02-07 16:04
@jiannanWang ,
I was able to get the same error result with the old and updated code.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/b8387b8b5aa40c7948872f31426f9a21/untitled216.ipynb).If possible can you please provide the error log which helps to analyse the issue.

**Comment by jiannanWang** [comment] 2022-02-07 16:12
Hi tilakrayal. I created a gist(https://colab.research.google.com/drive/16Cd-eiB5KnGR_nLF4KK0XmB8zSZtVUMM?usp=sharing) here. You can check it. On my computer, the code will print "False" which indicates the encoded and decoded input is not equivalent to the original input.

**Comment by tilakrayal** [comment] 2022-02-09 10:53
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.7, v2.8 and different error in nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/2e647699835f7fdb0131931bfbe226ee/54266.ipynb).

**Comment by jsmeredith** [comment] 2022-03-03 19:46
Thanks for the report and investigation!

I think this is fine, after digging a bit deeper.

First, image formats in general are not lossless, so "saving as image in tensorflow" is not intended to be a lossless operation.  And the docs (https://www.tensorflow.org/io/api_docs/python/tfio/image/encode_gif) don't suggest that GIF uses a lossless variation.

For saving and loading data (without loss), there are other mechanisms.  

Specifically for GIF, there are a few potential sources of loss.  While we don't (I believe) use a lossy encryption, we do use a palettized encoding.  This CAN be exact/lossless for small int8 tensors, but a simple heuristic like histogram each color is perceptually more accurate if you quantize to a smaller color space first.  In fact, this is what the common giflib does and we do here; quantize to 32 bits per channel first.

I don't think we're likely to change this commmitment (i.e. lossy) without a strong reason, so I'm closing the ticket for now, but always happy to hear suggestions.  Thanks!

**Closed by jsmeredith** 2022-03-03 19:46 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:apis, TF 2.7
