### ISSUE TITLE
High memory consumption with model.fit in TF 2.x

### ISSUE THREAD

**Issue by gdudziuk** [tensorflow/tensorflow#40942] opened 2020-06-30 12:08 UTC
**System information**

- Have I written custom code: Yes
- OS Platform and Distribution: CentOS Linux 7
- Mobile device: Not verified on mobile devices
- TensorFlow installed from: binary, via `pip install tf-nightly`
- TensorFlow version: 2.5.0-dev20200626
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1 / 7
- GPU model and memory: Tesla V100 32 GB

**Describe the current behavior**

Model training with the Keras API consumes high amount of system memory. It looks like the memory used by `model.fit` is proportional to the size of the training data provided as numpy arrays, with the proportionality constant being approximately 1. In other words, if the numpy arrays `x` and `y` are, say, 8 GB in total, then `model.fit(x,y,...)` will use another 8 GB (plus some overhead). So the memory usage by `model.fit` uses is twice the data size (plus some overhead).

The same concerns the validation data. If validation data are passed as numpy arrays to `model.fit` via the argument `validation_data`, then the memory use of `model.fit` seems to duplicate the size of the validation data arrays.

The described effect is also present if I wrap the numpy arrays containing the data in TF Datasets.

In the code attached below, one may change the variable `K` to vary the size of the data and test the above described behavior. It is straightforward to estimate the data size (e.g. with `K=5000` the data arrays in the below code should be ca. 7.32 GB in total). The whole Python process associated with this code uses approximately twice this much RAM plus some overhead independent of the data size. One may comment out the line containing `model.fit` to check that it is the point at which the high memory consumption starts.

**Describe the expected behavior**

It would be reasonable to expect that the memory usage by the test code was approximately the data size plus some overhead independent of the data size (not twice the data size plus overhead).

**A bit of history**

This is a continuation of the issue #35030, concerning TF 2.0 and 2.1. I opened the latter issue in December 2019 and now @karmel have stated that that issue is very long and asked me to test if the issue persists in TF-nightly and open a new issue if necessary. So yes, the problem persists, and here I open a new issue.

The problem appeared first in the release `2.0.0-rc0`. In the earlier releases up to `2.0.0-b1` inclusive the memery usage by the below test code was ca. the size of the data arrays plus an overhead independent of the data size. Starting from `2.0.0-rc0` it became twice the data size plus overhead and it was true at least until `2.1.0`.

Next, in `2.2.0`, the situation changed a bit:

- When using numpy arrays to pass data to `model.fit`, there was a memory leak about 0.5 x data size in each epoch. In other words, if the size of the data arrays was ca. 8 GB, then the memory usage was increasing ca. 4 GB each epoch.
- When wrapping the data arrays in TF datasets and then passing to `model.fit`, then the behavior was the same in TF 2.2 as in 2.1 and 2.0, namely the memory usage was twice the data size plus overhead.

Now, in the nightly release `2.5.0-dev20200626` we are back to the previous situation, namely the memory usage is twice the data size plus overhead, regardless of whether numpy arrays or datasets are used to pass the data to `model.fit`.

**An important note on reproducibility**

The issue has occurred to be not reproducible in colab! In #35030, I reported the issue for my local machine and some other participants also managed to reproduce it locally but not in colab. Some were trying to reproduce it in colab without success. Similarly, the results I report now are not from colab.

Also, for some reason the issue cannot be captured when using `libmemusage.so` to measure the memory usage. To capture the issue, I use `ps au` in Linux terminal or Python module `psutil`.

**Standalone code to reproduce the issue**

Since this issue is in fact a continuation of #35030, I use the same test code here.

```python
import tensorflow as tf
import numpy as np

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Lambda, Conv2D

print("Tensorflow version: {}".format(tf.__version__),flush=True)

K = 5000 # Number of images
N = 512  # Image size

MAX_SIGNAL = 5000 # The values of the training data range from 0 to this

def build_model():
  '''Create a simple test model.'''
  
  inputs = Input((N,N,1))
  s = Lambda(lambda x: x / MAX_SIGNAL) (inputs)
  s = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(s)
  outputs = s

  return Model(inputs=[inputs], outputs=[outputs])

# Generate some random data
x_train = np.random.randint(MAX_SIGNAL+1,size=(K,N,N,1),dtype=np.uint16) # Should be 2 560 000 kB
y_train = np.random.randint(1+1         ,size=(K,N,N,1),dtype=np.bool)   # Should be 1 280 000 kB
x_val   = np.random.randint(MAX_SIGNAL+1,size=(K,N,N,1),dtype=np.uint16) # Should be 2 560 000 kB
y_val   = np.random.randint(1+1         ,size=(K,N,N,1),dtype=np.bool)   # Should be 1 280 000 kB
# In total, the above arrays should be 7 680 000 kB

model = build_model()

optimizer = tf.keras.optimizers.Adam()
loss = tf.keras.losses.BinaryCrossentropy()

model.compile(optimizer=optimizer, loss=loss)
model.fit(x=x_train, y=y_train, validation_data=(x_val,y_val), batch_size=8, epochs=10)
```

The above is meant to reproduce the issue with data passed to `model.fit` as numpy arrays. To test the behavior with TF datasets, replace the last line with the following:

```python
ds_train = tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(8)
ds_val = tf.data.Dataset.from_tensor_slices((x_val,y_val)).batch(8)
model.fit(ds_train, validation_data=ds_val, epochs=10)
```

**Comment by Saduf2019** [comment] 2020-07-01 13:44
@gdudziuk 
I ran the code shared above please fin the [gist here](https://colab.research.google.com/gist/Saduf2019/12f843ce9e8e30807edbe271d307a5e5/untitled251.ipynb), Please let us know if it confirms your issue.

**Comment by gdudziuk** [comment] 2020-07-02 10:51
@Saduf2019, thanks for your gist but it doesn't confirm the issue. As I have explicitly stated in the issue description, the problem is not reproducible in colab. It is possible to reproduce the issue on local machines. It has been confirmed for older versions of TF 2.x in #35030.

Also, for some reason, not every memory profiling tool can capture the issue. I can capture it measuring the memory usage with `ps au` in the Linux terminal or with the Python module `psutil`. Some participants of #35030 were using Python's `memory_profiler` to capture the issue. On the other hand, it was not possible to reproduce it with `libmemusage.so`.

**Comment by gdudziuk** [comment] 2020-07-02 12:07
I guess I should carry out some memory measurements in my test code. So, here is the origonal test code enriched with RSS memory measurements:

```python
import tensorflow as tf
import numpy as np
import psutil
import os

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Lambda, Conv2D
from tensorflow.keras.callbacks import Callback

print("Tensorflow version: {}".format(tf.__version__),flush=True)

K = 5000 # Number of images
N = 512  # Image size

MAX_SIGNAL = 5000 # The values of the training data range from 0 to this

class MemoryUsageCallback(Callback):
  '''Monitor memory usage on epoch begin and end.'''

  def on_epoch_begin(self,epoch,logs=None):
    print('**Epoch {}**'.format(epoch))
    print('Memory usage on epoch begin: {}'.format(psutil.Process(os.getpid()).memory_info().rss))

  def on_epoch_end(self,epoch,logs=None):
    print('Memory usage on epoch end:   {}'.format(psutil.Process(os.getpid()).memory_info().rss))
    
def build_model():
  '''Create a simple test model.'''
  
  inputs = Input((N,N,1))
  s = Lambda(lambda x: x / MAX_SIGNAL) (inputs)
  s = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(s)
  outputs = s

  return Model(inputs=[inputs], outputs=[outputs])

# Generate some random data
x_train = np.random.randint(MAX_SIGNAL+1,size=(K,N,N,1),dtype=np.uint16) # Should be 2 560 000 kB
y_train = np.random.randint(1+1         ,size=(K,N,N,1),dtype=np.bool)   # Should be 1 280 000 kB
x_val   = np.random.randint(MAX_SIGNAL+1,size=(K,N,N,1),dtype=np.uint16) # Should be 2 560 000 kB
y_val   = np.random.randint(1+1         ,size=(K,N,N,1),dtype=np.bool)   # Should be 1 280 000 kB
# In total, the above arrays should be 7 680 000 kB

model = build_model()

callbacks = [MemoryUsageCallback()]
optimizer = tf.keras.optimizers.Adam()
loss = tf.keras.losses.BinaryCrossentropy()

model.compile(optimizer=optimizer, loss=loss)
model.fit(x=x_train, y=y_train, validation_data=(x_val,y_val), batch_size=8, epochs=10, callbacks=callbacks, verbose=0)
```

to test the memory usage with TF datasets, replace the last line with the following:

```python
ds_train = tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(8)
ds_val = tf.data.Dataset.from_tensor_slices((x_val,y_val)).batch(8)
model.fit(ds_train, validation_data=ds_val, batch_size=8, epochs=10, callbacks=callbacks, verbose=0)
```

**Comment by gdudziuk** [comment] 2020-07-02 12:27
I have tested this code on a different machine (Kubuntu 18.04, GeForce GTX 1050 Ti 4GB). The tests have been carried out with tf-nightly version `2.4.0-dev20200702`. The originally reported version `2.5.0-dev20200626` seems to be not available via pip at the moment.

Output for numpy arrays:

```
Tensorflow version: 2.4.0-dev20200702
**Epoch 0**
Memory usage on epoch begin: 12781158400
Memory usage on epoch end:   18143223808
**Epoch 1**
Memory usage on epoch begin: 18143223808
Memory usage on epoch end:   18434109440
**Epoch 2**
Memory usage on epoch begin: 18434109440
Memory usage on epoch end:   18492579840
**Epoch 3**
Memory usage on epoch begin: 18492579840
Memory usage on epoch end:   18593259520
**Epoch 4**
Memory usage on epoch begin: 18593259520
Memory usage on epoch end:   18589122560
**Epoch 5**
Memory usage on epoch begin: 18589122560
Memory usage on epoch end:   18598289408
**Epoch 6**
Memory usage on epoch begin: 18598289408
Memory usage on epoch end:   18610733056
**Epoch 7**
Memory usage on epoch begin: 18610733056
Memory usage on epoch end:   18616848384
**Epoch 8**
Memory usage on epoch begin: 18616848384
Memory usage on epoch end:   18624794624
**Epoch 9**
Memory usage on epoch begin: 18624794624
Memory usage on epoch end:   18623217664
```

The output for datasets:

```
Tensorflow version: 2.4.0-dev20200702
**Epoch 0**
Memory usage on epoch begin: 16711708672
Memory usage on epoch end:   17472192512
**Epoch 1**
Memory usage on epoch begin: 17472225280
Memory usage on epoch end:   17472245760
**Epoch 2**
Memory usage on epoch begin: 17472266240
Memory usage on epoch end:   17472266240
**Epoch 3**
Memory usage on epoch begin: 17472266240
Memory usage on epoch end:   17490911232
**Epoch 4**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
**Epoch 5**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
**Epoch 6**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
**Epoch 7**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
**Epoch 8**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
**Epoch 9**
Memory usage on epoch begin: 17490911232
Memory usage on epoch end:   17490911232
```
One can check how the memory usage changes manipulating the variable `K` in the code. The above results are for `K=5000`, for which the size of the data arrays is 7 680 000 kB. The resulting memory usage is definitely too high.

Later I will try test on the original machine reported for this issue (Centos 7, Tesla V100 32 GB).

**Comment by jammm** [comment] 2020-07-25 03:47
> I have tested this code on a different machine (Kubuntu 18.04, GeForce GTX 1050 Ti 4GB). The tests have been carried out with tf-nightly version `2.4.0-dev20200702`. The originally reported version `2.5.0-dev20200626` seems to be not available via pip at the moment.
> 
> Output for numpy arrays:
> 
> ```
> Tensorflow version: 2.4.0-dev20200702
> **Epoch 0**
> Memory usage on epoch begin: 12781158400
> Memory usage on epoch end:   18143223808
> **Epoch 1**
> Memory usage on epoch begin: 18143223808
> Memory usage on epoch end:   18434109440
> **Epoch 2**
> Memory usage on epoch begin: 18434109440
> Memory usage on epoch end:   18492579840
> **Epoch 3**
> Memory usage on epoch begin: 18492579840
> Memory usage on epoch end:   18593259520
> **Epoch 4**
> Memory usage on epoch begin: 18593259520
> Memory usage on epoch end:   18589122560
> **Epoch 5**
> Memory usage on epoch begin: 18589122560
> Memory usage on epoch end:   18598289408
> **Epoch 6**
> Memory usage on epoch begin: 18598289408
> Memory usage on epoch end:   18610733056
> **Epoch 7**
> Memory usage on epoch begin: 18610733056
> Memory usage on epoch end:   18616848384
> **Epoch 8**
> Memory usage on epoch begin: 18616848384
> Memory usage on epoch end:   18624794624
> **Epoch 9**
> Memory usage on epoch begin: 18624794624
> Memory usage on epoch end:   18623217664
> ```
> 
> The output for datasets:
> 
> ```
> Tensorflow version: 2.4.0-dev20200702
> **Epoch 0**
> Memory usage on epoch begin: 16711708672
> Memory usage on epoch end:   17472192512
> **Epoch 1**
> Memory usage on epoch begin: 17472225280
> Memory usage on epoch end:   17472245760
> **Epoch 2**
> Memory usage on epoch begin: 17472266240
> Memory usage on epoch end:   17472266240
> **Epoch 3**
> Memory usage on epoch begin: 17472266240
> Memory usage on epoch end:   17490911232
> **Epoch 4**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> **Epoch 5**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> **Epoch 6**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> **Epoch 7**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> **Epoch 8**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> **Epoch 9**
> Memory usage on epoch begin: 17490911232
> Memory usage on epoch end:   17490911232
> ```
> 
> One can check how the memory usage changes manipulating the variable `K` in the code. The above results are for `K=5000`, for which the size of the data arrays is 7 680 000 kB. The resulting memory usage is definitely too high.
> 
> Later I will try test on the original machine reported for this issue (Centos 7, Tesla V100 32 GB).

Can you try adding the following in the beginning on your code and then run it on a multi-core machine?

```
tf.config.threading.set_inter_op_parallelism_threads(1)

tf.config.threading.set_intra_op_parallelism_threads(1)
```

If after calling the above you don't have high memory usage, then the underlying issue could be related to https://github.com/tensorflow/tensorflow/issues/41718

**Comment by gdudziuk** [comment] 2020-08-10 12:09
Thanks for your suggestion but as I understand #41718 is a CPU-related issue while the present issue occurs for both CPU and GPU versions of TensorFlow.

To be sure, I have just run a test (for both `tf-nightly` and `tf-nightly-cpu`, version `2.4.0-dev20200807`). I can confirm that the issue occurs regardless of whether I add the lines you suggest or no.

Said that, there is some small difference for the CPU version. Namely, with your extra lines the memory usage is ca. 1 GB lower than without them.  Interestingly, for the case of passing data as numpy arrays, this effect occurs also with the GPU version. However, lowering the memory usage by 1 GB does not solve the present issue.

**Comment by Simon-Coetzee** [comment] 2020-08-14 01:03
@gdudziuk I have the same issue as you, unable to even finish your example before I run out of memory. However if I use the tensorflow/tensorflow:latest-gpu-jupyter docker image - for example, the problem does not occur. Before I was installing from conda.

**Comment by tirear** [comment] 2020-12-23 01:56
To temporarily escape this problem, the following function works:
```
import gc
...
model.fit(x=x, y=y)
gc.collect()
```

**Comment by jvishnuvardhan** [comment] 2021-03-27 02:23
@gdudziuk Is this still an issue for you? There were some good performance related updated over the last few months. 

Can you please check with a recent `tf` version and also adding `gc.collect()` as mentioned by @tirear . 

There ([1](https://github.com/tensorflow/tensorflow/issues/44711#issuecomment-736186819) and [2](https://github.com/tensorflow/tensorflow/issues/41973#issuecomment-668361074)) are couple of responses from @tomerk on performance related issues that might help you. 

Please verify once and let us know whether the issue persists with recent `tf` versions. Thanks!

**Comment by gdudziuk** [comment] 2021-04-03 17:14
Thank you for the information, @jvishnuvardhan. I will run tests with the most recent TF release in the forthcoming week and let you know about the results.

**Comment by gdudziuk** [comment] 2021-04-12 15:55
I have just run the test with TF `2.4.1`. Unfortunately, the issue is still there. The results are very similar to those reported above for `2.4.0-dev20200702`. I will check with `tf-nightly` in a moment...

**Comment by jvishnuvardhan** [comment] 2021-04-12 16:04
@gdudziuk If possible, Can you please check with `TF2.5rc0` also. Thanks!

**Comment by gdudziuk** [comment] 2021-04-12 20:57
Ok, it was a longer moment, because both TF `2.5.0-rc0` and tf-nightly (`2.6.0-dev20210412` at the moment) depend on `libcusolver.so.11` while it seems that the latter is not available via APT (or at least I haven't succeeded to install it). So eventually, I have just run the test code on my Kubuntu 18.04 machine in CPU mode only.

And I don't have good news to share. The issue is there, both in `2.5.0-rc0` and in `2.6.0-dev20210412`, and both for data passed to `model.fit` as numpy arrays and as tf.Dataset. The output is very similar to the one [already posted in this issue](https://github.com/tensorflow/tensorflow/issues/40942#issuecomment-652975769), but for reference I attach it as text files.

[TF-2.5.0-rc0_data_as_datasets.txt](https://github.com/tensorflow/tensorflow/files/6299769/TF-2.5.0-rc0_data_as_datasets.txt)
[TF-2.5.0-rc0_data_as_numpy.txt](https://github.com/tensorflow/tensorflow/files/6299771/TF-2.5.0-rc0_data_as_numpy.txt)
[TF-2.6.0-dev20210412_data_as_datasets.txt](https://github.com/tensorflow/tensorflow/files/6299773/TF-2.6.0-dev20210412_data_as_datasets.txt)
[TF-2.6.0-dev20210412_data_as_numpy.txt](https://github.com/tensorflow/tensorflow/files/6299774/TF-2.6.0-dev20210412_data_as_numpy.txt)

**Comment by thusinh1969** [comment] 2021-07-17 10:58
Calling a fit (CPU, for testing mostly) a ESRGAN GAN model with 46M parameters can suddently consume +100G bytes of RAM and keep growing, finally it crashes machine with 256G :( ... ! TF 2.4.1.

HELP !

Steve

**Comment by pluxj** [comment] 2021-07-22 08:22
Found multiple copies during training
data size: 20GB
memory used：70GB

**Comment by Dhruv-Mohan** [comment] 2021-07-31 23:53
I encountered the issue while on version `2.5.0-dev20200626` but it seems that the release version of `2.5.0` has fixed the issue.
The training function I've used is as follows along with a routine batching loop.
```python
@tf.function
def train_step(images, labels):
    with tf.GradientTape() as tape:
      predictions = model(images, training=True) #Keras model subclass
      loss = loss_object(labels, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    train_loss(loss)
```
I however have not tested it against `model.fit` or `train_on_batch`.

**Comment by tensorflowbutler** [comment] 2021-12-14 23:11
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by 1860yk** [comment] 2021-12-19 20:19
Hey, did 2.7 fix this issue?

**Comment by gdudziuk** [comment] 2022-01-11 00:59
No, it doesn't. With TF 2.7 I get scores similar as before.

The output for numpy arrays:

```
**Epoch 0**
Memory usage on epoch begin: 12127035392
Memory usage on epoch end:   18409664512
**Epoch 1**
Memory usage on epoch begin: 18409664512
Memory usage on epoch end:   18484998144
**Epoch 2**
Memory usage on epoch begin: 18484998144
Memory usage on epoch end:   18638782464
**Epoch 3**
Memory usage on epoch begin: 18638782464
Memory usage on epoch end:   18586607616
**Epoch 4**
Memory usage on epoch begin: 18586607616
Memory usage on epoch end:   18652651520
**Epoch 5**
Memory usage on epoch begin: 18652651520
Memory usage on epoch end:   18744152064
**Epoch 6**
Memory usage on epoch begin: 18744152064
Memory usage on epoch end:   18654404608
**Epoch 7**
Memory usage on epoch begin: 18654404608
Memory usage on epoch end:   18792071168
**Epoch 8**
Memory usage on epoch begin: 18792071168
Memory usage on epoch end:   18691829760
**Epoch 9**
Memory usage on epoch begin: 18691829760
Memory usage on epoch end:   18831183872
```

The output for datasets:

```
**Epoch 0**
Memory usage on epoch begin: 16053436416
Memory usage on epoch end:   17169522688
**Epoch 1**
Memory usage on epoch begin: 17170001920
Memory usage on epoch end:   17233149952
**Epoch 2**
Memory usage on epoch begin: 17233141760
Memory usage on epoch end:   17204260864
**Epoch 3**
Memory usage on epoch begin: 17204252672
Memory usage on epoch end:   17161564160
**Epoch 4**
Memory usage on epoch begin: 17161555968
Memory usage on epoch end:   17226149888
**Epoch 5**
Memory usage on epoch begin: 17226141696
Memory usage on epoch end:   17219477504
**Epoch 6**
Memory usage on epoch begin: 17219497984
Memory usage on epoch end:   17210036224
**Epoch 7**
Memory usage on epoch begin: 17210028032
Memory usage on epoch end:   17234489344
**Epoch 8**
Memory usage on epoch begin: 17234481152
Memory usage on epoch end:   17211543552
**Epoch 9**
Memory usage on epoch begin: 17211535360
Memory usage on epoch end:   17218691072
```

(Kubuntu 18.04, CPU mode)

**Comment by jvishnuvardhan** [comment] 2022-03-01 09:06
Duplicate of #https://github.com/keras-team/keras/issues/15887

Let's track the progress in the above lined issue. Thanks!

**Closed by jvishnuvardhan** 2022-03-01 09:06 UTC
Labels: stat:awaiting tensorflower, comp:keras, type:performance, TF 2.3
