### ISSUE TITLE
Bug: Bazel 3.7.2 fails to build with GCC 11.1.0 on ARMv8

### ISSUE THREAD

**Issue by samcom12** [tensorflow/tensorflow#50277] opened 2021-06-15 05:10 UTC
Hi, 
`Bazel 3.7.2.` is failing to build on  `ARMv8`, hopefully, in the latest Bazel, they have fixed it.
Any plan to use upgraded Bazel?

**Comment by eli-osherovich** [comment] 2021-06-15 18:54
What error do you get?

**Comment by samcom12** [comment] 2021-06-16 09:50
With GCC-11 we need to explicitely add `#include <limits>` and `#include <stdexcept>`.

**Comment by eli-osherovich** [comment] 2021-06-16 10:19
This issue was fixed upstream. See #50176 and link therein.

**Comment by tilakrayal** [comment] 2021-06-16 14:44
@samcom12 ,

Looks like this is duplicate of issue #50303.Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2021-07-05 19:13 UTC
Labels: stalled, stat:awaiting response, subtype:bazel, type:build/install
