### ISSUE TITLE
__name__ becomes 'tensorflow.keras.layers' when import tf.keras.layers

### ISSUE THREAD

**Issue by coelacanthus** [tensorflow/tensorflow#27940] opened 2019-04-18 04:01 UTC
**System information**
Google Colaboratory with tensorflow nightly build 2.0.0.dev20190417.
Any runtime

**Code to reproduce**
```
!pip install tf-nightly-2.0-preview
import tensorflow as tf
from tensorflow.keras.layers import *
print(__name__)  # output is 'tensorflow.keras.layers'
```

**Code to avoid the problem**
```
!pip install tf-nightly-2.0-preview
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense # Import layers explicitly
print(__name__)  # output is '__main__'
```

**Comment by shravankumar147** [comment] 2019-04-21 15:10
I have tried the same but couldn't see the issue. Please check out here https://github.com/shravankumar147/tensorflow/blob/master/__name___becomes_'tensorflow_keras_layers'_when_import_tf_keras_layers_27940.ipynb

**Comment by muddham** [comment] 2019-04-22 05:36
@coelacanthus We get ouput as _main_ in both of the code scenarios.
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by coelacanthus** [comment] 2019-04-22 07:55
I have tried a new nightly build(2.0.0.dev20190421), and the issue seems to have been fixed.

Currently, how to reproduce the issue is:
```
!echo 'tf-nightly-2.0-preview==2.0.0.dev20190417' > /tmp/requirements.txt
!echo 'tensorflow-estimator-2.0-preview==1.14.0.dev2019041700' >> /tmp/requirements.txt
!echo 'tb-nightly==1.14.0a20190417' >> /tmp/requirements.txt
!pip install -r /tmp/requirements.txt
import tensorflow as tf
from tensorflow.keras.layers import *
print(tf.__git_version__, tf.__version__)
print(__name__)
```
Please check out below: https://github.com/coelacanthus/tensorflow/blob/master/__name___becomes_%27tensorflow_keras_layers%27_when_import_tf_keras_layers_27940.ipynb


**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-12697-g4a1931ae46 2.0.0-dev20190417
- Python version: 3.6.7
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla T4

I am sorry for not enough information. Thanks.

**Comment by jvishnuvardhan** [comment] 2019-04-22 23:20
I am closing the issue as it was resolved. Please open a new ticket if you see similar issue again. Thanks!

**Closed by jvishnuvardhan** 2019-04-22 23:20 UTC
Labels: 2.0, comp:keras, type:support
