### ISSUE TITLE
tf.float16 not in allowed list?

### ISSUE THREAD

**Issue by lizaigaoge550** [tensorflow/tensorflow#21871] opened 2018-08-25 12:33 UTC
when i call dynamic_rnn,  i counter a TypeError: Value passed to parameter 'x' has DataType float16 not in list of allowed values: float32. the dynamic_rnn only support the type of float32?

**Comment by tensorflowbutler** [comment] 2018-08-31 07:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-16 02:31
It has been 21 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-25 17:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-25 17:00 UTC
Labels: stat:awaiting response
