### ISSUE TITLE
module 'tensorflow._api.v1.nn' has no attribute 'seq2seq'

### ISSUE THREAD

**Issue by mohlondon** [tensorflow/tensorflow#37172] opened 2020-02-28 17:46 UTC
when i execute this command 
python tensorflow/models/rnn/translate/translate.py 

i get 

Preparing WMT data in /home/baba055h_s/
2020-02-28 17:45:29.997997: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-28 17:45:30.002826: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-02-28 17:45:30.003172: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c1f9a006a0 executing computations on platform Host. Devices:
2020-02-28 17:45:30.003209: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Creating 3 layers of 1024 units.
WARNING:tensorflow:From /home/baba055h_s/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py:117: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py:122: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:At least two cells provided to MultiRNNCell are the same object and will share weights.
Traceback (most recent call last):
  File "./translate.py", line 290, in <module>
    tf.app.run()
  File "/home/baba055h_s/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./translate.py", line 287, in main
    train()
  File "./translate.py", line 152, in train
    model = create_model(sess, False)
  File "./translate.py", line 131, in create_model
    dtype=dtype)
  File "/home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py", line 168, in __init__
    self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'seq2seq'

please can any one help

**Comment by amahendrakar** [comment] 2020-03-02 06:40
@mohlondon,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by mohlondon** [comment] 2020-03-05 13:54
thank you for your reply i did managed to fix this by downgrading tensorflow to 0.12.1 version then it worked but i have a problem the chat i created it doesn't work correctly i guess it keep gigin me this resault no matter how much time i train it 
python3 ./translate.py  --en_vocab_size=40000 --fr_vocab_size=40000 --data_dir=/home/baba055h_s/ --train_dir=/home/baba055h_s/ --decode
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:463: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:464: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:466: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:467: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
WARNING:tensorflow:From /home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py:188 in __init__.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Created model with fresh parameters.
WARNING:tensorflow:From ./translate.py:138 in create_model.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
> hi
sample sample sample sample sample sample sample sample letter-sized letter-sized
> what's up
sample sample sample soil soil soil neski neski neski neski


see what is that all about is it something wrong with the data i provided
please help me

**Comment by mohlondon** [comment] 2020-03-05 13:55
thank you for your reply i did managed to fix this by downgrading tensorflow to 0.12.1 version then it worked but i have a problem the chat i created it doesn't work correctly i guess it keep gigin me this resault no matter how much time i train it 
python3 ./translate.py  --en_vocab_size=40000 --fr_vocab_size=40000 --data_dir=/home/baba055h_s/ --train_dir=/home/baba055h_s/ --decode
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:463: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:464: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:466: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:467: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
WARNING:tensorflow:From /home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py:188 in __init__.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Created model with fresh parameters.
WARNING:tensorflow:From ./translate.py:138 in create_model.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
> hi
sample sample sample sample sample sample sample sample letter-sized letter-sized
> what's up
sample sample sample soil soil soil neski neski neski neski


see what is that all about is it something wrong with the data i provided
please help me

**Comment by mohlondon** [comment] 2020-03-05 13:56
i didn't close it it's a mistake i'm waiting for an answer

**Comment by mohlondon** [comment] 2020-03-05 13:56
i didn't close it it's a mistake i'm waiting for an answer

**Comment by amahendrakar** [comment] 2020-03-12 09:22
@mohlondon,
I was able to reproduce the error `AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'seq2seq'` with [TF1.15](https://colab.sandbox.google.com/gist/amahendrakar/91c7aaada701ffd291ce90a73d652373/37172.ipynb#scrollTo=6m5QcJq4YXLi). 

However, running the code with [TF 0.12](https://colab.sandbox.google.com/gist/amahendrakar/33999ac65f2885262d08f9384d0e9a0c/37172-0-12.ipynb), gives a different error `TypeError: cannot use a bytes pattern on a string-like object`. Please find the attached gist. Thanks!

**Comment by amahendrakar** [comment] 2020-03-19 10:24
Any updates regarding this issue? Thanks!

**Comment by mohlondon** [comment] 2020-03-19 10:37
The error you got it cz you need to use 0.12.1 version of tf
But,  I am trying to build my own model because i couldn't find the problem

**Comment by amahendrakar** [comment] 2020-03-20 05:50
@mohlondon,
Sorry for the confusion. Even though the comment says TF v0.12, I am using TF v0.12.1, to run the code.

> But, I am trying to build my own model because i couldn't find the problem

Could you please elaborate your concern. Thanks!

**Comment by Zer0-dev115** [comment] 2020-03-26 07:27
> @mohlondon,
> I was able to reproduce the error `AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'seq2seq'` with [TF1.15](https://colab.sandbox.google.com/gist/amahendrakar/91c7aaada701ffd291ce90a73d652373/37172.ipynb#scrollTo=6m5QcJq4YXLi).
> 
> However, running the code with [TF 0.12](https://colab.sandbox.google.com/gist/amahendrakar/33999ac65f2885262d08f9384d0e9a0c/37172-0-12.ipynb), gives a different error `TypeError: cannot use a bytes pattern on a string-like object`. Please find the attached gist. Thanks!

I am facing the same issue. Did you get any solution?

**Comment by amahendrakar** [comment] 2020-03-27 15:16
@mohlondon,
> Could you please elaborate your concern. Thanks!

Any updates on this issue?

@Zer0-dev115,
I am still facing the same issue, no solution as of now. 

Thanks!

**Comment by amahendrakar** [comment] 2020-04-03 12:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-03 12:42 UTC
Labels: TF 1.15, comp:model, stat:awaiting response, type:support

**Comment by Godwin45** [comment] 2021-01-13 17:23
AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'seq2seq'

**Comment by amahendrakar** [comment] 2021-01-17 10:02
@Godwin45,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
