### ISSUE TITLE
Error:  tf.device does not support functions

### ISSUE THREAD

**Issue by deprekate** [tensorflow/tensorflow#48684] opened 2021-04-21 22:20 UTC
Tensorflow crashes when following current guide.

**System information**
Tensorflow Version: 
v2.4.0-49-g85c8b2a817f 2.4.1

**Describe the current behavior**
Following the [guide](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/replica_device_setter) on how to use `replica_device_setter`, the code crashes with the error: `RuntimeError: tf.device does not support functions.`

**Describe the expected behavior**
It should not crash

**Standalone code to reproduce the issue**
```
import tensorflow as tf
cluster_spec = {"ps": ["ps0:2222"],"worker": ["worker0:2222", "worker1:2222"]}
with tf.device(tf.compat.v1.train.replica_device_setter(cluster=cluster_spec)):
    pass
```

**Other info / logs** Include any logs or source code that would be helpful to
```
...
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in device_v2(device_name)
   5271   """
   5272   if callable(device_name):
-> 5273     raise RuntimeError("tf.device does not support functions.")
   5274   return device(device_name)
   5275 

RuntimeError: tf.device does not support functions.
```

**Comment by UsharaniPagadala** [comment] 2021-04-22 08:32
@amahendrakar 

I reproduced the code in tf 2.5rc1 ,tf-nightly and tf2.4.1,but facing the same [error.](https://colab.research.google.com/gist/UsharaniPagadala/98d5766b0cb51c516dddf2c32f8ec1c9/-48684.ipynb) Could you please look at this issue .Thanks

**Comment by deprekate** [comment] 2021-04-22 20:27
After digging though ops.py, I saw that I could call the old v1 method, and fixed the error by changing to
```
import tensorflow as tf
cluster_spec = {"ps": ["ps0:2222"],"worker": ["worker0:2222", "worker1:2222"]}
with tf.compat.v1.device(tf.compat.v1.train.replica_device_setter(cluster=cluster_spec)):
    pass
```

So I guess the guide needs to be updated or `device_v2()` to fall back on `device()` if a function is provided?

**Comment by rohan100jain** [comment] 2021-05-13 18:45
As part of the migration to TF2, we explicitly disabled functions as input to tf.device. So we should just update the guide to call tf.compat.v1.device instead of tf.device. It'll be great if you wanted to contribute a PR with the documentation fix!

**Comment by chunduriv** [comment] 2021-09-29 11:56
Since the above [PR](https://github.com/tensorflow/tensorflow/pull/52095) was merged. I am closing this issue. Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by chunduriv** 2021-09-29 11:56 UTC
Labels: stat:contributions welcome, type:bug, comp:ops, TF 2.4
