### ISSUE TITLE
importing and running frozen graph from old version TF produces empty output.

### ISSUE THREAD

**Issue by dzhyeon** [tensorflow/tensorflow#17897] opened 2018-03-21 16:08 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.06
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.6
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: GTX 1080 Ti
- **Exact command to reproduce**: 

I have a exported graph file in tensorflow 1.3 version with ubuntu 14.04 (CUDA 7.5 / cudnn 6), and it is working well under the same system so far. 
The graph was frozen and I cleared device names when exported it, so it can run both on cpu/gpu mode in my previous machine ubuntu 14.04.

The problem is when I try to run the same graph file in new machine (ubuntu 16.04, tensorflow 1.6, CUDA 9, cudnn 7), the output is just empty.
There were no problem of importing the graph file and no error messages when running it. 
Also the output was produced and shape is what expected except the content is empty.
My graph takes an image as input and produce an image as output. And when imported and run the graph in 16.04, the result is just black image.

I also opened the graph using tensorflow/python/tools/import_pb_to_tensorboard.py, and tensorboard visualized the right network I designed. 

Also tested with tensorflow version 1.5, 1.4 but the result was same.

Any solution for this problem?

**Comment by dzhyeon** [comment] 2018-03-22 13:06
After trying installing and uninstalling, it looks like it only happens when installing from source.
pip install tensorflow or tensorflow-gpu works well. But once installed from source with bazel, this problem happens.

**Comment by asimshankar** [comment] 2018-04-07 01:45
So, if I understand correctly - things work well if you install TensorFlow binaries for any of the new recent versions (1.5, 1.6, 1.7 etc.)? But the output tensor is empty only if building from source?

Hard to say what's happening without more details, or ideally an ability to reproduce the problem. Are you building from unedited source? When you say the "output is empty", is there no output tensor returned, or is the output tensor of the wrong shape, or is it full of zeroes, or something else?

**Comment by tensorflowbutler** [comment] 2018-04-21 18:26
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-04-22 02:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2018-04-22 02:35 UTC
Labels: stat:awaiting response
