### ISSUE TITLE
Unresolved external symbol, C++, Windows 7, TensorFlow 2.0

### ISSUE THREAD

**Issue by Randryn0** [tensorflow/tensorflow#34159] opened 2019-11-11 16:46 UTC
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Windows 7 Enterprise
- TensorFlow installed from: Source
- TensorFlow version: 2.0
- Python version: 3.6.8
- Bazel version: 0.26.1
- GCC/Compiler version: VS2017 15.7.5
- GPU model and memory: Intel HD 530

[edit]
The build was based on commit 1cf0898dd4331baf93fe77205550f2c2e6c90ee5 from the r2.0 branch.
[/edit]

I tried to build the shared C++ library on Windows 7 for TensorFlow 2 with the recommended version of bazel and I was quite happy that it seems to be a lot more straightforward now (previously I was only able to build 1.6 with cmake).

However, the problem that now occurs when I try to use TensorFlow in a program. I have custom written code but for the time being I only tried to run a few simple examples.

This small program

```
#define NOMINMAX
#define COMPILER_MSVC
#include "tensorflow/core/platform/logging.h"

int main(int argc, char * argv[])
{
  LOG(ERROR) << "test";
}
```

compiles and works without problems but when I try to run the [example trainer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/tutorials/example_trainer.cc) the program compiles but fails to link with the following errors:
```
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::Operation::Operation(class tensorflow::Node *)" (??0Operation@tensorflow@@QEAA@PEAVNode@1@@Z)" in function ""public: __cdecl tensorflow::Input::Input<int,void>(int const &)" (??$?0HX@Input@tensorflow@@QEAA@AEBH@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::Input::Initializer::Initializer(class std::initializer_list<struct tensorflow::Input::Initializer> const &)" (??0Initializer@Input@tensorflow@@QEAA@AEBV?$initializer_list@UInitializer@Input@tensorflow@@@std@@@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::Scope::~Scope(void)" (??1Scope@tensorflow@@QEAA@XZ)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: static class tensorflow::Scope __cdecl tensorflow::Scope::NewRootScope(void)" (?NewRootScope@Scope@tensorflow@@SA?AV12@XZ)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::Scope::GetUniqueNameForOp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?GetUniqueNameForOp@Scope@tensorflow@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV34@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: void __cdecl tensorflow::Scope::UpdateStatus(class tensorflow::Status)const " (?UpdateStatus@Scope@tensorflow@@QEBAXVStatus@2@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: void __cdecl tensorflow::Scope::UpdateBuilder(class tensorflow::NodeBuilder *)const " (?UpdateBuilder@Scope@tensorflow@@QEBAXPEAVNodeBuilder@2@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: bool __cdecl tensorflow::Scope::ok(void)const " (?ok@Scope@tensorflow@@QEBA_NXZ)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: class tensorflow::Graph * __cdecl tensorflow::Scope::graph(void)const " (?graph@Scope@tensorflow@@QEBAPEAVGraph@2@XZ)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: class tensorflow::Status __cdecl tensorflow::Scope::ToGraphDef(class tensorflow::GraphDef *)const " (?ToGraphDef@Scope@tensorflow@@QEBA?AVStatus@2@PEAVGraphDef@2@@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: class tensorflow::Status __cdecl tensorflow::Scope::DoShapeInference(class tensorflow::Node *)const " (?DoShapeInference@Scope@tensorflow@@QEBA?AVStatus@2@PEAVNode@2@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""private: class tensorflow::Scope __cdecl tensorflow::Scope::WithOpNameImpl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?WithOpNameImpl@Scope@tensorflow@@AEBA?AV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""class tensorflow::Output __cdecl tensorflow::ops::Const(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (?Const@ops@tensorflow@@YA?AVOutput@2@AEBVScope@2@AEBUInitializer@Input@2@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""struct tensorflow::NodeBuilder::NodeOut __cdecl tensorflow::ops::AsNodeOut(class tensorflow::Scope const &,class tensorflow::Input const &)" (?AsNodeOut@ops@tensorflow@@YA?AUNodeOut@NodeBuilder@2@AEBVScope@2@AEBVInput@2@@Z)" in function ""class tensorflow::Output __cdecl tensorflow::ops::Const<float>(class tensorflow::Scope const &,struct tensorflow::Input::Initializer const &)" (??$Const@M@ops@tensorflow@@YA?AVOutput@1@AEBVScope@1@AEBUInitializer@Input@1@@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::ops::Div::Div(class tensorflow::Scope const &,class tensorflow::Input,class tensorflow::Input)" (??0Div@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::ops::MatMul::MatMul(class tensorflow::Scope const &,class tensorflow::Input,class tensorflow::Input)" (??0MatMul@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::ops::Sqrt::Sqrt(class tensorflow::Scope const &,class tensorflow::Input)" (??0Sqrt@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::ops::Square::Square(class tensorflow::Scope const &,class tensorflow::Input)" (??0Square@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::ops::Sum::Sum(class tensorflow::Scope const &,class tensorflow::Input,class tensorflow::Input)" (??0Sum@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1@Z)" in function ""class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)".
1>  main.obj : error LNK2019: unresolved external symbol ""public: __cdecl tensorflow::SessionOptions::SessionOptions(void)" (??0SessionOptions@tensorflow@@QEAA@XZ)" in function ""void __cdecl tensorflow::example::ConcurrentSteps(struct tensorflow::example::Options const *,int)" (?ConcurrentSteps@example@tensorflow@@YAXPEBUOptions@12@H@Z)".
1>  main.obj : error LNK2019: unresolved external symbol ""class tensorflow::Session * __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &)" (?NewSession@tensorflow@@YAPEAVSession@1@AEBUSessionOptions@1@@Z)" in function ""void __cdecl tensorflow::example::ConcurrentSteps(struct tensorflow::example::Options const *,int)" (?ConcurrentSteps@example@tensorflow@@YAXPEBUOptions@12@H@Z)".
1>  main.obj : error LNK2001: unresolved external symbol ""const tensorflow::GraphDef::`vftable'" (??_7GraphDef@tensorflow@@6B@)".
```

Now I read [here](https://github.com/tensorflow/tensorflow/issues/30647) in a post by [gunan](https://github.com/gunan) that this has to do with the fact that not all symbols are exported, however, I am not sure whether this is the case here since I find it strange that compiling a tensorflow .lib and .dll without any custom changes results in a library that is not able to compile/work with official example code.
Am I missing something?

Cheers

**Comment by ringdk** [comment] 2019-11-28 18:02
I'm hitting the same issue when trying to compile and link the 'example_trainer' executable with the standard tensorflow C++ libs:

`cl tensorflow/tensorflow/cc/tutorials/example_trainer.cc -DNOMINMAX /I tensorflow/bazel-genfiles/tensorflow/include /I eigen /I abseil-cpp /I protobuf/src /EHsc protobuf\cmake\build\release\libprotobuf.lib tensorflow\bazel-genfiles\tensorflow\tensorflow_cc.lib`

With error like:

`example_trainer.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::Input::Initializer::Initializer(class std::initializer_list<struct tensorflow::Input::Initializer> const &)" (??0Initializer@Input@tensorflow@@QEAA@AEBV?$initializer_list@UInitializer@Input@tensorflow@@@std@@@Z) referenced in function "class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)
example_trainer.obj : error LNK2019: unresolved external symbol "public: __cdecl tensorflow::Scope::~Scope(void)" (??1Scope@tensorflow@@QEAA@XZ) referenced in function "class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)
example_trainer.obj : error LNK2019: unresolved external symbol "public: static class tensorflow::Scope __cdecl tensorflow::Scope::NewRootScope(void)" (?NewRootScope@Scope@tensorflow@@SA?AV12@XZ) referenced in function "class tensorflow::GraphDef __cdecl tensorflow::example::CreateGraphDef(void)" (?CreateGraphDef@example@tensorflow@@YA?AVGraphDef@2@XZ)
example_trainer.exe : fatal error LNK1120: 21 unresolved externals`

Can someone from the dev team please give an example of how to compile and link the 'example_trainer' code with the default tensorflow c++ libs on Windows, without using Bazel?

I'm aware of the "add TF_EXPORT to each function" workaround from [here](https://github.com/tensorflow/tensorflow/issues/30647) and [here](https://github.com/tensorflow/tensorflow/issues/24885), however I want to build TF libs once and don't know what functions I'll need ahead of time.

I'm also aware of the 'def_file_filter.py.tpl' trick, but as @gunan has mentioned [here](https://github.com/tensorflow/tensorflow/issues/30647#issuecomment-529315280), it seems that not all symbols can be linked against.

Thanks in advance for any help or suggestions!

**Comment by conradjones** [comment] 2019-12-15 12:35
I made the following changes to get my app to link against the Tensorflow dll

I feel potentially the TF_EXPORT is not the best route, it looks like a few people are having these kinds of issues.. I'm quite happy to submit a PR but I feel the TF_EXPORT is a bit of a hack, 

https://github.com/conradjones/tensorflow/commit/ffdbaa25411340cf49b2eba8e180733340af61cd

**Comment by ymodak** [comment] 2020-06-02 19:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2020-06-02 19:31 UTC
Labels: TF 2.0, subtype:windows, type:build/install

**Comment by jeffhwang02** [comment] 2020-07-04 23:42
Same issue here,  I  think  tx-export macro can not be a final solution.

**Comment by RS-Hoptroff** [comment] 2021-09-15 19:13
Why dont you just generate dlls subdivided for the subset of operations to avoid the 2^16 EOT issue

**Comment by kilasuelika** [comment] 2022-01-22 04:04
I have the same issue.
If I didn't link with `tensorflow_cc.lib`, then there will 8 unresolved symbols. If linked with it, there are only 5 unresolved symbols. So I assume the problem is indeed not all symbols were exported.
But the building process takes 18 hours in my laptop. I would prefer a more releastic solution than using `TF_EXPORT` and recompile.
