### ISSUE TITLE
meta_optimizer.cc layout failed on frozen_graph

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#28663] opened 2019-05-13 10:14 UTC
TF 2.0 preview gpu
Python 3.6.3

Importing a frozen graph def leads to an error: `... meta_optimizer.cc:486] layout failed: Invalid argument: Invalid graph: Frame ids for node ...`

**What I did**
Checkpoint: http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz

Run in `research/slim/` found here: https://github.com/tensorflow/models/tree/master/research/slim
1. GraphDef:
```python export_inference_graph.py --model_name=inception_v3 --output_file=MODELS/inception_v3_inf_graph.pb```
2. Obtain a copy of: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py and place it in `research/slim`
3. Create Frozen Graph:
```python freeze_graph.py --input_graph=MODELS/inception_v3_inf_graph.pb --input_checkpoint=MODELS/inception_v3.ckpt --input_binary=true --output_graph=MODELS/frozen_inception_v3.pb --output_node_names=InceptionV3/Predictions/Reshape```
4. Pack into `tar.gz`.

I then imported the frozen graph with
```python
import tensorflow as tf
import tarfile
import os

from tensorflow.core.framework import graph_pb2
from tensorflow.python.framework import importer

INCEPTION_V3_FILE_NAME = 'frozen_inception_v3.tar.gz'
INCEPTION_V3_FROZEN_GRAPH = 'frozen_inception_v3.pb'
# Shape[None x 299 x 299 x 3]
INCEPTION_V3_INPUT = 'input:0'
# Shape[None x 1 x 1 x 2048]
INCEPTION_V3_OUTPUT = 'InceptionV3/Logits/AvgPool_1a_8x8/AvgPool:0'


def graph_def_from_tarball(filename, tar_filename):
    with tarfile.open(tar_filename, 'r:gz') as tar:
        proto_str = tar.extractfile(filename).read()
    return graph_pb2.GraphDef.FromString(proto_str)


graph_def = graph_def_from_tarball(
    INCEPTION_V3_FROZEN_GRAPH,
    INCEPTION_V3_FILE_NAME
)


@tf.function
def run_classifier(images):

    def classifier_fn(images):
        input_map = {INCEPTION_V3_INPUT: images}
        output_tensor = [INCEPTION_V3_OUTPUT]
        classifier_outputs = importer.import_graph_def(
            graph_def,
            input_map,
            output_tensor,
            'InceptionV3'
        )
        return classifier_outputs[0]

    logits = tf.map_fn(
        fn=classifier_fn,
        elems=tf.expand_dims(images, 0),
        parallel_iterations=1,
        back_prop=False,
        swap_memory=True,
        dtype=tf.float32,
        name='RunClassifier')

    logits = tf.concat(tf.unstack(logits), 0)
    return logits


images = tf.random.normal([1, 299, 299, 3])

r = run_classifier(images)
print(r)

```

Error message (the node it errors on varies):
```
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:486] layout failed: Invalid argument: Invalid graph: Frame ids for node RunClassifier/while/body/_1/InceptionV3/InceptionV3/Mixed_6b/Branch_2/Conv2d_0b_7x1/BatchNorm/moving_mean does not match frame ids for it's fanout RunClassifier/while/body/_1/InceptionV3/InceptionV3/InceptionV3/Mixed_6b/Branch_2/Conv2d_0b_7x1/BatchNorm/FusedBatchNorm/Mul2
```
Sometimes it is:
```
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: Invalid graph: Frame ids for node RunClassifier/while/body/_1/InceptionV3/InceptionV3/Mixed_6c/Branch_1/Conv2d_0a_1x1/BatchNorm/beta does not match frame ids for it's fanout RunClassifier/while/body/_1/InceptionV3/InceptionV3/InceptionV3/Mixed_6c/Branch_1/Conv2d_0a_1x1/BatchNorm/FusedBatchNorm/Offset
```

**What I expect**
No error or some better description of what went wrong.
Note: The imported graph def works, it just throws this error and it is unclear to me if it does the right thing considering the error message.

**Comment by sleighsoft** [comment] 2019-05-13 10:26
This example was extracted from a large codebase and tested on my machine!

This extracted example also causes the following problem: https://github.com/tensorflow/tensorflow/issues/27141
When I run this code within a large code base (cannot share) I do not get the aforementioned CUDNN error but I get the `layout failed` one.

**Comment by petewarden** [comment] 2019-08-02 00:15
I'm not familiar with the grappler code, so I'm unassigning myself.

**Comment by Some-random** [comment] 2021-03-30 16:01
any updates on this issue? I'm trying to convert my model to tensorrt and faced a similar issue. The error log looks like this:

` layout failed: Invalid argument: Invalid graph: Frame ids for node StatefulPartitionedCall/while/body/_378/while/transformer_decoder/transformer_decoder_layer/multi_head_attention_12/dense_73/BiasAdd/ReadVariableOp does not match frame ids for it's fanout StatefulPartitionedCall/while/body/_378/while/Identity_2`

**Comment by pskiran1** [comment] 2021-06-29 16:02
Hi,

Tagging @bixia1 for better visibility. cc: @DEKHTIARJonathan 
Requesting Tensorflow team to please help on following issue.
When we try converting tensorflow model to TRT getting following error messages (related to frame ids):
```
During conversion:
layout failed: Invalid argument: Invalid graph: Frame ids for node StatefulPartitionedCall/while/body/_378/while/transformer_decoder/transformer_decoder_layer_2/multi_head_attention_17/dense_100/BiasAdd/ReadVariableOp does not match frame ids for it's fanout StatefulPartitionedCall/while/body/_378/while/Identity_4
```
```
During execution:
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node Func/StatefulPartitionedCall/while/body/_378/output_control_node/_1118}} has inputs from different frames. The input {{node StatefulPartitionedCall/while/body/_378/while/transformer_decoder/transformer_decoder_layer_2/sequential_14/dense_101/Tensordot/ReadVariableOp}} is in frame 'StatefulPartitionedCall/while'. The input {{node StatefulPartitionedCall/while/body/_378/while/y_net/embedding/embedding_lookup}} is in frame ''. [Op:__inference_signature_wrapper_89313]
```
Steps to reproduce:
- Download [runnables.zip](https://drive.google.com/file/d/1ZEAymONsLzl96Ee5yLYnYCK00sgZ_nR7/view?usp=sharing) 
- Run "python jdw_convert_to_trt.py [model-path-./jdw_model] [output-model-path]"

For your reference, error logs:
[execution_log.txt](https://github.com/tensorflow/tensorflow/files/6734803/execution_log.txt)
[conversion_log.txt](https://github.com/tensorflow/tensorflow/files/6734804/conversion_log.txt)
Original post : [What is “frame ids” in tf-trt conversion](https://forums.developer.nvidia.com/t/what-is-frame-ids-in-tf-trt-conversion/173743)


Thank you.

**Comment by sushreebarsa** [comment] 2021-08-06 09:16
@sleighsoft 
It looks like you are using an older Version of Tensorflow 2.0. Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable Version(2.5) and let us know if the issue still persists? Thanks!

**Closed** 2021-08-20 10:52 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:grappler, TF 2.0
