### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'variable_scope'

### ISSUE THREAD

**Issue by anamariaUIC** [tensorflow/tensorflow#53073] opened 2021-11-15 20:16 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):2.7.0
- TensorFlow version (use command below):
- Python version:Python 3.8.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):GCC 10.2.0
- CUDA/cuDNN version:nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
- GPU model and memory:
gpu-2-0.saber
     properties = batch_gpu,gpu-g3,dell,saber,x86_64,nvidia
     status = opsys=linux,uname=Linux gpu-2-0.saber 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64,sessions=274505 349523 380034 397050,nsessions=4,nusers=2,idletime=8805,totmem=101384352kb,availmem=99296204kb,physmem=97190052kb,ncpus=16,loadave=0.00,gres=,netload=40652996470,state=free,varattr= ,cpuclock=Fixed,version=6.1.3,rectime=1637006909,jobs=
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I run my script:

python train.py
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    nn = NeuralNetwork(F=args.num_features,           
  File "/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master/neural_network/NeuralNetwork.py", line 53, in __init__
    with tf.variable_scope(self.scope):
AttributeError: module 'tensorflow' has no attribute 'variable_scope'

**Describe the expected behavior**
Following previous issues I tried replacing in my code:
this line:
 tf.global_variables_initializer().run()
with this one:
 tf.compat.v1.global_variables_initializer().run()

the error stated above remains the same in both instances.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment] 2021-11-16 06:13
@anamariaUIC 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by anamariaUIC** [comment] 2021-11-16 13:56
Hello,

Please find the attached code.
[train.txt](https://github.com/tensorflow/tensorflow/files/7546842/train.txt)


Thanks
[Ana[](url)](url)

**Comment by anamariaUIC** [comment] 2021-11-17 16:07
Hi @sushreebarsa can you please tell me if they are any updates on this issue? I attached my code in the previous comment.

Thanks
Ana

**Comment by sushreebarsa** [comment] 2021-11-18 10:03
@anamariaUIC I tried to replicate the issue on colab using TF v2.7.0 but didn't face the error reported here. Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c4993b524d7eba838e5a9374f1b94ad6/53073.ipynb) and confirm the same ? Thanks!

**Comment by anamariaUIC** [comment] 2021-11-18 12:54
@sushreebarsa I can see from the gist that you used Python 2.7. While I am using:
module load Python/3.8.6-GCCcore-10.2.0
module load CUDA/11.1.1-GCC-10.2.0

Because I am trying to run this on GPU. Can you please test this with my Python and CUDA version?

**Comment by sachinprasadhs** [comment] 2021-11-18 23:35
Hi, did you try using `tf.compat.v1.variables_initializer` to initialize variables.

**Comment by anamariaUIC** [comment] 2021-11-18 23:43
@sachinprasadhs do you mean replacing in the code I attached:
tf.global_variables_initializer().run()
with
tf.compat.v1.variables_initializer.run()

I tried that and I got this:

python train.py 
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    nn = NeuralNetwork(F=args.num_features,           
  File "/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master/neural_network/NeuralNetwork.py", line 53, in __init__
    with tf.variable_scope(self.scope):
AttributeError: module 'tensorflow' has no attribute 'variable_scope'


If this is not what you meant please send me precise instructions on what to do.

Thanks

**Comment by sachinprasadhs** [comment] 2021-11-19 23:05
From your error log I could notice that you're creating a `nn` class object by calling NeuralNetwork.py, which I assume the same file [here](https://github.com/MMunibas/PhysNet/blob/master/neural_network/NeuralNetwork.py), in line 53 where it uses `tf.variable_scope` is depreciated in Tensorflow 2.x and instead you need to use `tf.compat.v1.variable_scope`.
Even with this modification you may find other issues since the code is not compatible in Tensorflow 2.x, you can see [this](https://www.tensorflow.org/guide/migrate) migration documentation for code migration from 1.x to 2.x. Thanks!

**Comment by anamariaUIC** [comment] 2021-11-19 23:48
@sachinprasadhs ok I installed different version of tensorflow with:

module load Python/3.6.6-fosscuda-2018b
pip3 install tensorflow-gpu==1.10.1  --user

while I was logged on my GPU node.
Yes indeed I am running [this code](https://github.com/MMunibas/PhysNet/blob/master/train.py):

I via:
anamaria@gpu-2-0.saber:/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master $ python train.py
Traceback (most recent call last):
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    import tensorflow as tf
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/anamaria/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


here is what is in my ENV:

anamaria@gpu-2-0.saber:/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master $ module list

Currently Loaded Modules:
  1) GCCcore/7.3.0                  8) XZ/5.2.4-GCCcore-7.3.0           15) FFTW/3.3.8-gompic-2018b                      22) SQLite/3.24.0-GCCcore-7.3.0
  2) zlib/1.2.11-GCCcore-7.3.0      9) libxml2/2.9.8-GCCcore-7.3.0      16) ScaLAPACK/2.0.2-gompic-2018b-OpenBLAS-0.3.1  23) GMP/6.1.2-GCCcore-7.3.0
  3) binutils/2.30-GCCcore-7.3.0   10) libpciaccess/0.14-GCCcore-7.3.0  17) fosscuda/2018b                               24) libffi/3.2.1-GCCcore-7.3.0
  4) GCC/7.3.0-2.30                11) hwloc/1.11.10-GCCcore-7.3.0      18) bzip2/1.0.6-GCCcore-7.3.0                    25) Python/3.6.6-fosscuda-2018b
  5) CUDA/9.2.88-GCC-7.3.0-2.30    12) OpenMPI/3.1.1-gcccuda-2018b      19) ncurses/6.1-GCCcore-7.3.0
  6) gcccuda/2018b                 13) OpenBLAS/0.3.1-GCC-7.3.0-2.30    20) libreadline/7.0-GCCcore-7.3.0
  7) numactl/2.0.11-GCCcore-7.3.0  14) gompic/2018b                     21) Tcl/8.6.8-GCCcore-7.3.0

 

anamaria@gpu-2-0.saber:/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master $ echo $PATH
/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/SQLite/3.24.0-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Tcl/8.6.8-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libreadline/7.0-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/ncurses/6.1-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/bzip2/1.0.6-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/FFTW/3.3.8-gompic-2018b/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/OpenMPI/3.1.1-gcccuda-2018b/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/hwloc/1.11.10-GCCcore-7.3.0/sbin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/hwloc/1.11.10-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libxml2/2.9.8-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/XZ/5.2.4-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/numactl/2.0.11-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30/nvvm/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/binutils/2.30-GCCcore-7.3.0/bin:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/GCCcore/7.3.0/bin:/software/linux-el7-x86_64/apps/anaconda3/anaconda3/condabin:/projects/com_grassim/anamaria/anamaria/plink:/usr/local/bin:/usr/lib64/qt-3.3/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/anamaria/.local/bin:/software/linux-el7-x86_64/services/hadoop-2.8.2/sbin:/software/linux-el7-x86_64/services/hadoop-2.8.2/bin
anamaria@gpu-2-0.saber:/mnt/lustre/anamaria/AI/tensorflow/PhysNet/PhysNet-master $ echo $LD_LIBRARY_PATH
/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib/python3.6/site-packages/numpy-1.15.0-py3.6-linux-x86_64.egg/numpy/core/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Python/3.6.6-fosscuda-2018b/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libffi/3.2.1-GCCcore-7.3.0/lib64:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libffi/3.2.1-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/GMP/6.1.2-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/SQLite/3.24.0-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/Tcl/8.6.8-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libreadline/7.0-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/ncurses/6.1-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/bzip2/1.0.6-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/ScaLAPACK/2.0.2-gompic-2018b-OpenBLAS-0.3.1/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/FFTW/3.3.8-gompic-2018b/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/OpenMPI/3.1.1-gcccuda-2018b/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/hwloc/1.11.10-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libpciaccess/0.14-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/libxml2/2.9.8-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/XZ/5.2.4-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/numactl/2.0.11-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30/nvvm/lib64:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30/extras/CUPTI/lib64:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/CUDA/9.2.88-GCC-7.3.0-2.30/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/binutils/2.30-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/zlib/1.2.11-GCCcore-7.3.0/lib:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/GCCcore/7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/GCCcore/7.3.0/lib64:/software/linux-el7-x86_64/tools/EasyBuild-4.1.0/software/GCCcore/7.3.0/lib

Please advise

**Comment by sachinprasadhs** [comment] 2021-11-24 17:11
Currently we don't support Tensorflow 1.x issues, you can consider upgrading your code to Tensorflow 2.x by following migration guide.
For any different issue other than the issue reported in the template, please raise a new issue and close this, Thanks!

**Closed** 2021-12-08 17:51 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:apis, TF 2.7
