### ISSUE TITLE
Tensorflow lite conversion from h5 to tflite increases file size

### ISSUE THREAD

**Issue by kartikye** [tensorflow/tensorflow#28137] opened 2019-04-25 05:56 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2070 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Tflite conversion from h5 file increases in size from 141KB to 508KB
**Describe the expected behavior**
A reduction in size

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(11, activation=tf.nn.softmax)
])

model.compile(optimizer='adam', 
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])
model.fit(TrainingData, TrainingLabels, epochs=400)

tf.keras.models.save_model(model, keras_file)

converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file(keras_file)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment] 2019-04-26 02:58
@kartikye Could you create a reproducible code and share the link to that gist? It will help us resolve the issue faster. Thanks!

**Comment by kartikye** [comment] 2019-04-28 19:58
What should i include in the reproducible code?

**Comment by jvishnuvardhan** [comment] 2019-04-29 06:17
@kartikye If you can create a google colab gist or any other way that we can run to reproduce the issue   would be great. The above code is not complete to reproduce the issue. It will make issue resolutions faster. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-17 06:14
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-17 06:14 UTC
Labels: comp:keras, comp:lite, type:bug/performance
