### ISSUE TITLE
Stateful LSTMLite conversion

### ISSUE THREAD

**Issue by razor1179** [tensorflow/tensorflow#37025] opened 2020-02-24 17:15 UTC
**System information**
- Red Hat Enterprise Linux Server release 7.7:
- TensorFlow installed from binary:
- TensorFlow version 1.15:

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED, LOGISTIC, UNIDIRECTIONAL_SEQUENCE_LSTM, UNPACK. Here is a list of operators for which you will need custom implementations: Assign.
Traceback (most recent call last):
  File "/home/xyz/anaconda3/envs/tf15/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/xyz/anaconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/xyz/anaconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/xyz/anaconda3/envs/tf15/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/xyz/anaconda3/envs/tf15/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/xyz/anaconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED, LOGISTIC, UNIDIRECTIONAL_SEQUENCE_LSTM, UNPACK. Here is a list of operators for which you will need custom implementations: Assign.
```

**Standalone code to reproduce the issue** 
```python
import os
os.environ['TF_ENABLE_CONTROL_FLOW_V2'] = '1'
import tensorflow as tf
from tensorflow_core.python.keras.models import Model, Sequential
from tensorflow_core.python.keras.layers.core import Dense, Activation, Lambda, Reshape
from tensorflow_core.python.keras.engine.input_layer import Input
from tensorflow_core.python.keras.layers.recurrent import RNN, StackedRNNCells
from tensorflow_core.lite.experimental.examples.lstm.rnn_cell import TFLiteLSTMCell, TfLiteRNNCell
from tensorflow_core.lite.experimental.examples.lstm.rnn import dynamic_rnn
from tensorflow_core.python.ops.rnn_cell_impl import LSTMStateTuple
from tensorflow_core.lite.python.interpreter import Interpreter
from tensorflow_core.python.ops.rnn_cell_impl import MultiRNNCell

def get_state_variables(batch_size, cell):
    # For each layer, get the initial state and make a variable out of it
    # to enable updating its value.
    state_variables = []
    for state_c, state_h in cell.zero_state(batch_size, tf.float32):
        state_variables.append(tf.contrib.rnn.LSTMStateTuple(
            tf.Variable(state_c, trainable=False),
            tf.Variable(state_h, trainable=False)))
    # Return as a tuple, so that it can be fed to dynamic_rnn as an initial state
    return tuple(state_variables)


def get_state_update_op(state_variables, new_states):
    # Add an operation to update the train states with the last state tensors
    update_ops = []
    for state_variable, new_state in zip(state_variables, new_states):
        # Assign the new state to the state variables on this layer
        update_ops.extend([state_variable[0].assign(new_state[0]),
                           state_variable[1].assign(new_state[1])])
    # Return a tuple in order to combine all update_ops into a single operation.
    # The tuple's actual value should not be used.
    return tf.tuple(update_ops)


def buildMultiCell(cells):
    return MultiRNNCell(cells)


def buildRNNLayer(inputs, rnn_cells, initial_state=None):
  """Build the lstm layer.

  Args:
    inputs: The input data.
    num_layers: How many LSTM layers do we want.
    num_units: The unmber of hidden units in the LSTM cell.
  """
  # Assume the input is sized as [batch, time, input_size], then we're going
  # to transpose to be time-majored.
  transposed_inputs = tf.transpose(inputs, perm=[1, 0, 2])
  outputs, new_state = dynamic_rnn(
      rnn_cells,
      transposed_inputs,
      initial_state=initial_state,
      dtype='float32',
      time_major=True)
  unstacked_outputs = tf.unstack(outputs, axis=0)
  # update_op = get_state_update_op(initial_state, new_state)
  return unstacked_outputs[-1], new_state


def build_rnn_lite(model, state=False):
    tf.reset_default_graph()
    # Construct RNN
    cells = []
    for layer in range(3):
        if model == 'LSTMLite':
            cells.append(TFLiteLSTMCell(192, name='lstm{}'.format(layer)))
        else:
            cells.append(TfLiteRNNCell(192, name='rnn{}'.format(layer)))

    rnn_cells = Lambda(buildMultiCell, name='multicell')(cells)
    states = get_state_variables(1, rnn_cells)
    if state:
        spec_input = Input(shape=(5, 64,), name='rnn_in', batch_size=1)
        x, new_states = Lambda(buildRNNLayer, arguments={'rnn_cells': rnn_cells, 'initial_state': states}, name=model.lower())(spec_input)
        updated_states = Lambda(get_state_update_op, arguments={'new_states': new_states}, name='update_state')(states)
    else:
        spec_input = Input(shape=(5, 64,), name='rnn_in')
        x, new_states = Lambda(buildRNNLayer, arguments={'rnn_cells': rnn_cells}, name=model.lower())(spec_input)
        updated_states = Lambda(get_state_update_op, arguments={'new_states': states}, name='update_state')(states)

    out = Dense(64, activation='sigmoid', name='fin_dense')(x)
    return Model(inputs=spec_input, outputs=[out, updated_states])

model = build_rnn_lite('LSTMLite', True)
```
This now creates a stateful LSTM model which returns the updated states of the LSTM.
```python
###### TF LITE CONVERSION
sess = tf.keras.backend.get_session()
input_tensor = sess.graph.get_tensor_by_name('rnn_in:0')
output_tensor = []
output_tensor.append(sess.graph.get_tensor_by_name('fin_dense/Sigmoid:0'))
all_tensors = [tensor for op in tf.get_default_graph().get_operations() for tensor in op.values()]
# output_tensor = sess.graph.get_tensor_by_name('fin_dense/Sigmoid:0')

# imp_tensor = []
for ten in all_tensors:
    if 'update_state/Assign' in ten.name:
        output_tensor.append(ten)

converter = tf.lite.TFLiteConverter.from_session(sess, [input_tensor], output_tensor)
# Note: It will NOT work without enabling the experimental converter!
# `experimental_new_converter` flag.
converter.experimental_new_converter = True
tflite_seg = converter.convert()
```
The output tensor list throws an error, if only the `fin_dense/Sigmoid:0` tensor is used the model does get converted but behaves as a stateless model therefore the `update_state` needs to be included in the output tensor list.
I am trying to create a stateful LSTMLite model, I was able to get the model to behave as a stateful model as described here [https://stackoverflow.com/questions/59962348/how-to-create-a-stateful-tensorflowlite-rnn-model-in-tf1-15](url) but am unable to convert the model to TFLite.

**Comment by jvishnuvardhan** [comment] 2020-03-05 22:54
@razor1179 Can you please provide a simple standalone code to reproduce the issue? I tried but got an error `NameError: name 'MultiRNNCell' is not defined`. Please check the [gist here](
https://colab.sandbox.google.com/gist/jvishnuvardhan/dd69c6005d2afdd176df3870697c070b/untitled865.ipynb#scrollTo=GQGYzikS4Hok). Thanks!

**Comment by razor1179** [comment] 2020-03-06 01:32
> @razor1179 Can you please provide a simple standalone code to reproduce the issue? I tried but got an error `NameError: name 'MultiRNNCell' is not defined`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/dd69c6005d2afdd176df3870697c070b/untitled865.ipynb#scrollTo=GQGYzikS4Hok). Thanks!

Please add line
`from tensorflow_core.python.ops.rnn_cell_impl import MultiRNNCell`

**Comment by jvishnuvardhan** [comment] 2020-03-06 21:10
@razor1179 When I enable custom_ops as mentioned by the error description, I was able to convert the model. 
I added this line just before the conversion. 
`converter.allow_custom_ops = True `

Added this line to write the tf_lite_model.
`open("my_tflitemodel.tflite",'wb').write(tflite_seg)`

Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/3bf9170ef111f9bb0b3aaaf2ab8bb2a8/untitled865.ipynb). 

Another thing I want to point out is Importing using `tensorflow_core.` is not a suggested way for importing any module as mentioned [here](https://github.com/tensorflow/tensorflow/issues/32957#issuecomment-543819065) and [another resource](https://github.com/tensorflow/tensorflow/issues/33075#issuecomment-539070546). Thanks!

Please let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-06 21:12
@razor1179 If possible, can you please try `TF2.1` or `tf-nightly`? I suspect statefull LSTM was not part of `TF1.x`. Thanks!

**Comment by razor1179** [comment] 2020-03-13 19:57
@jvishnuvardhan sure will try and get back to you.

**Comment by jvishnuvardhan** [comment] 2020-03-18 16:46
@razor1179 Any update from your side. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-30 22:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-03-30 22:52 UTC
Labels: TF 1.15, TFLiteConverter, comp:lite, type:support
