### ISSUE TITLE
version 1.2 doesn't show CUDA and cuDNN information

### ISSUE THREAD

**Issue by TengdaHan** [tensorflow/tensorflow#10827] opened 2017-06-19 14:32 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: `pip install tensorflow-gpu`
- **TensorFlow version (use command below)**: ('v1.2.0-rc2-21-g12f033d', '1.2.0')
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 5.1
- **GPU model and memory**: GTX 970M, 3GB

### Describe the problem
In previous version, after importing tensorflow like `import tensorflow as tf` following output will be shown:
```
>>> import tensorflow as tf;
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.7.5 locally
```
However, after I installed CUDA and cuDNN, and then installed Tensorflow v1.2, I found there is NO output for `import tensorflow as tf` in python. And I cannot check whether gpu successfully uses CUDA or cuDNN.
I have checked my GPU as follows and GPU works well. I have tried the method in #566 to adjust `TF_CPP_MIN_LOG_LEVEL`, but it seems have no effect.
I suggest it would be great to include CUDA and cuDNN info when importing tensorflow.

```
>>> import tensorflow as tf
>>> sess = tf.Session()
2017-06-20 00:24:38.111017: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-20 00:24:38.111060: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-20 00:24:38.111074: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-20 00:24:38.111086: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-20 00:24:38.111097: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-20 00:24:38.215890: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-06-20 00:24:38.216159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 970M
major: 5 minor: 2 memoryClockRate (GHz) 1.038
pciBusID 0000:01:00.0
Total memory: 2.95GiB
Free memory: 2.63GiB
2017-06-20 00:24:38.216174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-06-20 00:24:38.216180: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-06-20 00:24:38.216191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0)
```

**Comment by tatatodd** [comment] 2017-06-20 01:58
@TengdaHan I've reproduced your issue on TF 1.2.0.

This is odd, since the code to dump the "successfully opened CUDA library ..." code still seems to exist:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L139

@zheng-xq might know more about why these log messages aren't showing up.  I'm suspecting that either the dso_loader.cc code isn't actually being used anymore, or there's some weird interaction with the logging system at the time the shared libraries are being loaded.

**Comment by liangxiao05** [comment] 2017-06-21 09:52
I got the same question with you,since I installed tensorflow-gpu yestarday.The tf version is 1.2,and my gpu card is gtx1060. Although the CUDA and cuDNN info is not showed,  it seems that the GPU card is  working absolutely  , my demo is running much faster then before.
But, I want to make sure too.

**Comment by shivenmian** [comment] 2017-06-22 10:05
Facing this as well, I have GTX 1080 and tensorflow-gpu 1.2. I get no output on `import tensorflow as tf`, but when I put `log_device_placement=True` I get the CPU-can-be-sped-up instructions (SSE etc) and device mappings. It does look like GPU is being used though from my mappings, but still, I don't get the 'opened CUDA' logs.

**Comment by TengdaHan** [comment] 2017-06-22 10:58
@liangxiao05 Yes, I also feel GPU is working well, but just prefer to have the info.

**Comment by shivenmian** [comment] 2017-06-23 03:40
hi @puneith do you know of this?

**Comment by zero2hero2020** [comment] 2017-06-27 02:37
same problem here! with tensorflow 1.2.0

**Comment by perone** [comment] 2017-07-28 14:28
Same problem on tensorflow-gpu==1.3.0rc0

**Comment by leonchen417** [comment] 2017-07-31 22:05
I'm facing the same issue too tensorflow-gpu==1.2.1

**Comment by Yolanda-FuTengYu** [comment] 2017-08-20 04:26
I'm faceing the same issue when i update tensorflow-gpu to the version of 1.3.0. Also, it produces an error which shows the version of 1.3.0 need cudnn 6. So i updated the cudnn to the version of 6.0.21 and it produced this issue. After that, i reinstall ubuntu and install anaconda in order to install the old version of tensorflow. But it doesn't work. Now i'm not sure if the gpu is running.

**Comment by saikishor** [comment] 2017-10-19 07:50
I am also facing the same issue, as we end up in a confusion whether it is using CUDA or not.

**Comment by xtknight** [comment] 2017-10-31 11:34
same issue

**Comment by BumwooPark** [comment] 2017-11-07 01:00
i have same issue   
tensorflow - 1.4.0
tensorflow-gpu - 1.4.0
GeForce GTX 980 TI 
cuda_8.0 
cudnn-8.0 -v6

**Comment by qiushi223** [comment] 2017-12-05 03:14
same issue in 1.4.0

**Comment by tatatodd** [comment] 2017-12-05 17:57
Any thoughts on this @zheng-xq, or suggestions for who might know more?

**Comment by zheng-xq** [comment] 2017-12-05 18:29
Adding @jlebar, the owner of stream_executor

**Comment by jlebar** [comment] 2017-12-05 18:47
Hi, folks.

Loading the CUDA shared libraries is fraught, and complex.  Sometimes we go through this DSO loader, sometimes we can get the shared library through more normal means, sometimes we have to use static libraries.  Frankly I have trouble keeping it all straight.

I don't know offhand what changed back in June, but I don't think relying on these log messages from the DSO loader is the right way for you all to tell whether CUDA support is working, since, as you've observed, we can load the libraries *without* going through the DSO loader.

It seems reasonable to me that TF might want to print a log message indicating that CUDA support is enabled and working.  That's a question for someone higher up in the stack than myself, so, back to XQ to figure that out.  Or, I suppose, someone here could just send a patch.  :)

**Comment by tensorflowbutler** [comment] 2017-12-22 07:37
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yzhwang** [comment] 2018-01-05 18:57
I agree with @jlebar on not relying on the log messages from the DSO loader. It seems that there are two possible solutions to this issue: either adding a log message indicating CUDA support is enabled at a higher level or providing an API for users to retrieve these info. Both solutions would require poking around with stream executor code. Please refer to comments in https://github.com/tensorflow/tensorflow/issues/4090 to find out why currently in TensorFlow there is not an API for retrieving CUDA related library info. I will add  "contributions welcome" label for this issue as I do not have any cycle to work on this in the near future.

**Comment by XingyuGuUCSD** [comment] 2018-01-24 22:30
same issue, and the training process seems really slow

**Comment by yzhwang** [comment] 2018-01-24 22:36
@XingyuGuUCSD I think the slow training process is probably another issue. When you say slow, what are you comparing to? Also, could you verify that you have correctly set the GPU support during the configuration and have put nodes on the GPU when building the graph? If you believe the slow training process is an issue, please search for other similar ones or open a new one with more detailed logging info, so that we can take a look. Thank you!

**Comment by XingyuGuUCSD** [comment] 2018-01-24 22:48
@yzhwang I just update tensorflow and cuda. The GPU-util is high, while the training process is slower, compared with the previous same training program. And the log shows no info for cudnn and  gpu. Thus, I think it may be the problem with the cudnn

**Comment by yzhwang** [comment] 2018-01-25 00:21
@XingyuGuUCSD Since this issue is about cuda/cudnn logging, it has nothing to do with performance regression. Please do feel free to open up a new issue for others to investigate. Thank you.

**Comment by hmeine** [comment] 2019-04-02 10:37
> A quick hack that might be useful:
> `python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib() + "/python/_pywrap_tensorflow_internal.so")' | xargs ldd`

Thanks a lot! Unfortunately, (as with many hacks) this stops working for TF 2.x.  I have not found another hack yet; all .so I found in the TF libs directory (which are also fewer than with 1.13.1) do not link against libcudnn.so; maybe it is now dynamically dlopened.

**Comment by bionicles** [comment] 2019-10-04 15:01
would love a 2.0 solution for this to promote reproducible research without hardcoding everything.

**Comment by bionicles** [comment] 2019-10-04 15:16
```
def get_cudnn_version():
    S = check_output(
        'cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2', shell=True)
    N = [int(s) for s in S.split() if s.isdigit()]
    V = f'{N[0]}.{N[1]}.{N[2]}'
    print(V)
    return V
```

> 7.6.3

**Comment by mihaimaruseac** [comment] 2019-10-04 16:29
Closing as TF 1.2 is old and no longer supported.

**Closed by mihaimaruseac** 2019-10-04 16:29 UTC
Labels: stat:contributions welcome
