### ISSUE TITLE
Tensorflow registering GPU with a lot less memory than available

### ISSUE THREAD

**Issue by baozzhao** [tensorflow/tensorflow#55818] opened 2022-05-02 03:38 UTC
I recently installed a new GPU in my workstation - the EVGA Nvidia RTX 3080 with 12Gb. After successfully installing the corresponding drivers on my Ubuntu 18.04, as well as installing the latest CUDA and cuDNN, I opened Python in a terminal to test Tensorflow.

However, despite my GPU having exactly 12288MiB according to nvidia-smi (and only 435 Mb in usage by running processes Xorg and Gnome-Shell), tensorflow registered a device with only 9663 Mb. The exact message is:

2022-05-01 22:59:37.900290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9663 MB 
memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:81:00.0, compute capability: 8.6

Note that while related to the closed issue **https://github.com/tensorflow/tensorflow/issues/22623**, mine cannot be explained in the same fashion because I am on Ubuntu (so the Windows issue described there does not apply) and also I do have nearly the entire 12Gb of GPU memory available per nvidia-smi - so no secondary processes are occupying the missing memory that Tensorflow is not allocating.

Details:

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.8

### CUDA/cuDNN version

11.6

### GPU model and memory

RTX 3080 12Gb

### Current Behaviour?

```shell
I recently installed a new GPU in my workstation - the EVGA Nvidia RTX 3080 with 12Gb. After successfully installing the corresponding drivers on my Ubuntu 18.04, as well as installing the latest CUDA and cuDNN, I opened Python in a terminal to test Tensorflow.

However, despite my GPU having exactly 12288MiB according to nvidia-smi (and only 435 Mb in usage by running processes Xorg and Gnome-Shell), tensorflow registered a device with only 9663 Mb. The exact message is:

2022-05-01 22:59:37.900290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9663 MB 
memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:81:00.0, compute capability: 8.6

Note that while related to the closed issue **https://github.com/tensorflow/tensorflow/issues/22623**, mine cannot be explained in the same fashion because I am on Ubuntu (so the Windows issue described there does not apply) and also I do have nearly the entire 12Gb of GPU memory available per nvidia-smi - so no secondary processes are occupying the missing memory that Tensorflow is not allocating.
```

### Standalone code to reproduce the issue

```shell
Since the problem described is with the registration of GPU devices upon starting a Tensorflow code, the message appears with nearly any Tensorflow related command. For instance:

import tensorflow as tf
tf.test.gpu_device_name()
```

### Relevant log output

```shell
2022-05-01 22:59:37.900290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9663 MB 
memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:81:00.0, compute capability: 8.6
```
</details>

**Comment by mkxyh** [comment] 2022-05-03 22:00
Hi I'm not sure what is going on with your new Nvidia RTX 3080 set up, 
But  while looking at the file:--> tensorflow/core/common_runtime/gpu/gpu_device 
-line 1536

There is a note that states:

-line 1536:   // 'memory_limit
 // 'memory_limit' is the required memory size, but if the allocator with
  // given tf_device_id was created before, we'll use it instead of creating a
  // new one (as TF gpu device is a shared resource), in which case the actual
  // memory limit represented by 'stats.bytes_limit' used by that allocator
  // may be different (which should be an error).
  //
  // TODO(laigd): report error if memory_limit doesn't match
  // stats->bytes_limit.

I'm not sure if this helps. You could try rebooting your computer,

**Comment by sushreebarsa** [comment] 2022-05-05 07:40
@baozzhao Could you please try with the [comment](https://github.com/tensorflow/tensorflow/issues/55818#issuecomment-1116704080) above and let us know if it helps?Thanks!

**Comment by baozzhao** [comment] 2022-05-05 17:40
@sushreebarsa do you mean simply restarting the computer? I tried and it did not help much: now my nvidia-smi shows there are only 281 Mb being used by other processes (which are Xorg and gnome-shell) out of the 12288 Mb available in the GPU. So, there are 12007 Mb available. Yet, after starting a Python prompt and entering:

```
import tensorflow as tf
tf.test.gpu_device_name()
```

> I get this output:
> 2022-05-05 13:31:33.835176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /device:GPU:0 with 9849 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:81:00.0, compute capability: 8.6
> '/device:GPU:0'

That is, TensorFlow is allocating 2158 Mb less than actually available.

I also tried setting tf.GPUOptions(per_process_gpu_memory_fraction=1.0) to see if that helped, but it did not.

**Comment by sushreebarsa** [comment] 2022-05-09 08:07
@baozzhao Thank you for the update!
I tried to replicate the issue reported here on colab,could you please have a look at this[ gist ](https://colab.research.google.com/gist/sushreebarsa/0ed4ce25a9a97cd034f0c8fc736f106c/55818.ipynb#scrollTo=c2bKtsKv1AX-) and confirm the same?
Thanks!

**Comment by baozzhao** [comment] 2022-05-12 05:39
@sushreebarsa thanks for checking on this issue. I checked your gist, and yeah, if I run either code snippet on my machine, the problem originally described shows up: Tensorflow registers the GPU device allocating around 2 Gb less of the available GPU memory.

As per the link you suggested, I read it all but I can't see how could it be of any help. That link is about profiling and optimizing the usage of GPUs. My problem comes clearly from a Tensorflow bug: Tensorflow is registering my GPU with around 2 Gb less memory than the GPU has available (already discounting the few Mb being used by system processes).

**Comment by sushreebarsa** [comment] 2022-05-12 06:48
@baozzhao Thank you for the update!

@chunduriv I was able to replicate the issue on colab , please have a look at the [gist](https://colab.research.google.com/gist/sushreebarsa/0ed4ce25a9a97cd034f0c8fc736f106c/55818.ipynb#scrollTo=c2bKtsKv1AX-) .
Thank you!

**Comment by gowthamkpr** [comment] 2022-06-02 23:08
@baozzhao As mentioned in this [forum](https://forums.developer.nvidia.com/t/2-5gb-of-video-memory-missing-in-tensorflow-on-both-linux-and-windows-rtx-3080/190128), this issues persists for both linux and windows for Nvidia RTX 3080.

**Comment by gaikwadrahul8** [comment] 2022-12-17 12:43
Hi, @baozzhao 

Apologies for the delay and I found similar issue #[56661](https://github.com/tensorflow/tensorflow/issues/56661) and @hahouari provided workaround please check this [comment](https://github.com/tensorflow/tensorflow/issues/56661#issuecomment-1213286290), even I replicated the same issue on Google Colab It's working fine, for your reference I have attached Gist file [here](https://colab.research.google.com/gist/gaikwadrahul8/c91572a19740260e9071b7bf39c4b29f/55818.ipynb), please refer this official documentation about [tf.config.LogicalDeviceConfiguration](https://www.tensorflow.org/api_docs/python/tf/config/LogicalDeviceConfiguration)

Could you please try above workaround and check, Is it resolving your issue ? If it's resolving your issue please feel free to close this issue ?

If issue still persists, please let us know and if possible help us with error log to do further investigation to find out root cause for your issue ?

Thank you!

**Closed** 2022-12-31 13:19 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:bug, stalled, comp:gpu, TF 2.8
