### ISSUE TITLE
Unexpected `tf.cast` behavior between signed and unsigned integers

### ISSUE THREAD

**Issue by zicofish** [tensorflow/tensorflow#30215] opened 2019-06-28 07:26 UTC
It is tested on Google's own platform `https://colab.research.google.com`:
**System information**
- OS Platform and Distribution: Linux version 4.14.79+ (chrome-bot@swarm-cros-634)
- TensorFlow installed from (source or binary): The platform is provided by Google
- TensorFlow version: 1.14.0-rc1  (also tested on my own machine with TF 1.13.1)
- Python version: 3.6.8

**Describe the current behavior**
Type casting `tf.cast` from `tf.int32` to `tf.uint32` will make the Tensor become 0.

**Describe the expected behavior**
`tf.cast` should not change the bit representation of values.

**Code to reproduce the issue**
```
import tensorflow as tf

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
y = tf.cast(c, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw, y_raw = sess.run([x, y])
    print(x_raw.dtype, y_raw.dtype)
    print(x_raw)
    print(y_raw)
    
print(tf.__version__)
```
Running this code gives the result:
```
uint32 uint32
[0 0 0 0 0 0]
[0 0 0 0 0 0]
1.14.0-rc1
```

**Comment by eduardofv** [comment] 2019-06-28 17:21
This is really odd... @acs6610987, can you explain why are you assigning to `d` but never actually using it?
I've run your example and get the same results:
```
import tensorflow as tf

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
y = tf.cast(c, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw, y_raw = sess.run([x, y])
    print(x_raw.dtype, y_raw.dtype)
    print(x_raw)
    print(y_raw)
    
print(tf.__version__)
```
Yields:
```
2019-06-28 17:17:28.815499: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-28 17:17:28.842292: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-06-28 17:17:28.843186: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4739440 executing computations on platform Host. Devices:
2019-06-28 17:17:28.843243: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
uint32 uint32
[0 0 0 0 0 0]
[0 0 0 0 0 0]
1.13.1
```
But if I comment that single line I get the correct results!
```
import tensorflow as tf

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
#d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
y = tf.cast(c, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw, y_raw = sess.run([x, y])
    print(x_raw.dtype, y_raw.dtype)
    print(x_raw)
    print(y_raw)
    
print(tf.__version__)
```
Yields:
```
2019-06-28 17:15:10.449152: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-28 17:15:10.470490: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-06-28 17:15:10.471184: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x44bae00 executing computations on platform Host. Devices:
2019-06-28 17:15:10.471227: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
uint32 uint32
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
1.13.1
```
Running on a docker container with TF 1.13, Python 3.5.2 and 
```
tf-docker /root > uname -a
Linux bc59301e4081 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by eduardofv** [comment] 2019-06-28 17:25
A similar code running on TF2.0 (eager) seems to be correct:
```
import tensorflow as tf

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
y = tf.cast(c, dtype=tf.uint32)
#with tf.Session() as sess:
    #x, y = sess.run([x, y])
print("x,y")
print(x.dtype, y.dtype)
print(x)
print(y)

#c, d = sess.run([c, d])
print("c,d")
print(c.dtype, d.dtype)
print(c)
print(d)

print(tf.__version__)
```
Gives
```
tf-docker /root > python --version
Python 3.6.7
tf-docker /root > python tmp/test-eager.py 
2019-06-28 17:23:06.690077: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-28 17:23:06.728827: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-06-28 17:23:06.729713: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2465ae0 executing computations on platform Host. Devices:
2019-06-28 17:23:06.729737: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
x,y
<dtype: 'uint32'> <dtype: 'uint32'>
tf.Tensor([ 5  6  7  8  9 10], shape=(6,), dtype=uint32)
tf.Tensor([ 5  6  7  8  9 10], shape=(6,), dtype=uint32)
c,d
<dtype: 'int32'> <dtype: 'int32'>
tf.Tensor([ 5  6  7  8  9 10], shape=(6,), dtype=int32)
tf.Tensor([ 5  6  7  8  9 10], shape=(6,), dtype=int32)
2.0.0-beta0
tf-docker /root > uname -a
Linux ccc7b6654656 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by acs6610987** [comment] 2019-06-29 06:13
@eduardofv , about the `d`, I actually meant to use it for `y`, so I meant to post the following code:
```
import tensorflow as tf

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
y = tf.cast(d, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw, y_raw = sess.run([x, y])
    print(x_raw.dtype, y_raw.dtype)
    print(x_raw)
    print(y_raw)
    
print(tf.__version__)
```
This would also give the wrong result. I made a typo for using `c` but not `d` in the issue description, but this did not change the observed weird behavior...:( There must be something wrong in the TF runtime.

**Comment by eduardofv** [comment] 2019-06-30 02:30
You are right @acs6610987. I've done several tests and can confirm your findings. This is very odd and, unless there's something I don't understand from the execution model, this must be a bug.

In [this colab notebook](https://colab.research.google.com/drive/1FRH7p31Nl2qEo3WCm9dHw_4yZzmyOIzw) I can reproduce your results.

In [this one](https://colab.research.google.com/drive/1duKokwg4fMuz_1shg2GpDd6wmxXEvr52) just commenting the creation of the second const the cast operation is correct.

In [this other notebook](https://colab.research.google.com/drive/1k_kzUCyUP-qsjjli6Gzvry_0o7LEWxut) I separated the second const definition and cast, and run independently. When only one operation is performed the results are correct. But when the second operation is performed the results are zeroes again as shown below:

```
import tensorflow as tf
print(tf.__version__)

c = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
x = tf.cast(c, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw = sess.run([x])
    print(type(x_raw))
    #print(x_raw.dtype)
    print(x_raw)

d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
y = tf.cast(d, dtype=tf.uint32)
with tf.Session() as sess:
    x_raw, y_raw = sess.run([x, y])
    print(type(x_raw))
    print(x_raw.dtype)
    print(x_raw)
    print(type(y_raw))
    print(y_raw.dtype)
    print(y_raw)
```
```
1.14.0
<class 'list'>
[array([ 5,  6,  7,  8,  9, 10], dtype=uint32)]
<class 'numpy.ndarray'>
uint32
[0 0 0 0 0 0]
<class 'numpy.ndarray'>
uint32
[0 0 0 0 0 0]
```
I went as far as I could, reproducing the tf.cast python operation and debugging [on this notebook](https://colab.research.google.com/drive/1as229hGZ_uK8_YszziRfL4Js99Ew4iRU), but couldn't find any point of failure up to the moment the C++ operations are invoked. I gave a glimpse to the implementation but it's been long since I worked on C++!! I think this issue will have to be revised by someone with deeper knowledge of the TF kernel.

**Comment by eduardofv** [comment] 2019-06-30 23:02
After some [other](https://colab.research.google.com/drive/13WotBr941mpvUgZjNAMiItRAOt6a_Wr7) [tests](https://colab.research.google.com/drive/1dJ9-iiCKGsjtIiwoEfcB4W6uERPqL5Da), it seems that the error occurs when casting from ints or floats to uint32 or uint64. uint8 and unit16 seems to be OK. I wonder if it may have to do something with this LSBZeroSetter at [cast_op.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cast_op.cc)

**Comment by ravikyram** [comment] 2019-07-01 07:53
I have tried on colab with TF version 1.14 & 1.13.1 with and without commenting d and was able to reproduce the  issue.Also, i replaced with d, which actually meant to use it for y (by mistake used c) and checked,still i am able to reproduce the issue.Thanks!

**Comment by alextp** [comment] 2019-07-01 20:52
@rmlarsen the problem doesn't happen in eager or if you replace the tf.constant in the original bug with a placeholder_with_default, so I think it's a constant folding issue.

Do you know who should take a look? It seems bad...

**Comment by Leslie-Fang** [comment] 2019-07-19 04:54
same issue as: https://github.com/tensorflow/tensorflow/issues/30691
Please refer to this PR: https://github.com/tensorflow/tensorflow/pull/30707
I try it and fix this issue

**Comment by Leslie-Fang** [comment] 2019-07-19 05:16
The reason when we comment this line:
#d = tf.constant([5, 6, 7, 8, 9, 10], dtype=tf.int32)
would fix the issue is that: the nodes numbers need to be greater than 4 then that the code would go through this optimization path(which cause the problem).
Please refer to this code, if you change the min_graph_nodes larger than 4, the problem wouldn't happen
```
from tensorflow.core.protobuf import rewriter_config_pb2
rewriteOptions = rewriter_config_pb2.RewriterConfig(**min_graph_nodes=10**)
graphOptions = tf.GraphOptions(rewrite_options=rewriteOptions)
config = tf.ConfigProto(graph_options=graphOptions)

sess = tf.Session(config=config)
```

Could anyone help to have a review of this PR?

**Comment by rmothukuru** [comment] 2021-04-28 10:27
@zicofish,
Your code could be run successfully and is resulting in `Expected Output`. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/04b83f38b3fe97529fca8f773ab94480/gh_30215.ipynb) of the working code. Thanks!

**Comment by saikumarchalla** [comment] 2021-05-20 08:34
@zicofish  I executed the code in TF 2.5 version and  it is returning the output as expected. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/147b32ec410157ead26e53a6bd8aa89d/untitled78.ipynb). Thanks!

**Closed** 2021-05-20 08:34 UTC
Labels: TF 1.14, comp:ops, type:bug
