### ISSUE TITLE
gpu support error(sampled_loss)

### ISSUE THREAD

**Issue by ad26kt** [tensorflow/tensorflow#2621] opened 2016-06-02 10:19 UTC
I'm now a little bit hesitated that I have found a similar issue before, however I can't find it now

in the file seq2seq_model.py in translate foloder, I use    with device("/gpu:0')     instead of cpu, there's an error like this : 
```javascript
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-10-84f5fbeb6a90> in <module>()
      1 sess = tf.InteractiveSession()
----> 2 nmt.train(sess, train_data, valid_data, EVALUATE_PER)

<ipython-input-6-ca1988aa7469> in train(self, sess, train_data, valid_data, evaluate_per)
    190 
    191             _, cost = self.step(sess, train_encoder_batches[batch_i], train_decoder_batches[batch_i], 
--> 192                                train_target_batches[batch_i], train_target_weight_batches[batch_i], self.train_flag)
    193 
    194             # if the loss is equal to NaN(not a number), raise error

<ipython-input-6-ca1988aa7469> in step(self, sess, encoder_data, decoder_data, target_data, tw_data, train_flag)
    122                 output_feed.append(self.final_outputs[idx])
    123 
--> 124         output = sess.run(output_feed, input_feed)
    125         return output
    126 

/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict)
    313         `Tensor` that doesn't exist.
    314     """
--> 315     return self._run(None, fetches, feed_dict)
    316 
    317   def partial_run(self, handle, fetches, feed_dict=None):

/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict)
    509     # Run request and get response.
    510     results = self._do_run(handle, target_list, unique_fetches,
--> 511                            feed_dict_string)
    512 
    513     # User may have fetched the same tensor multiple times, but we

/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict)
    562     if handle is None:
    563       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 564                            target_list)
    565     else:
    566       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    584         # pylint: disable=protected-access
    585         raise errors._make_specific_exception(node_def, op, error_message,
--> 586                                               e.code)
    587         # pylint: enable=protected-access
    588       six.reraise(e_type, e_value, e_traceback)

InvalidArgumentError: Cannot assign a device to node 'sequence_loss_by_example/sampled_softmax_loss_39/embedding_lookup_1': Could not satisfy explicit device specification '/device:GPU:0'
	 [[Node: sequence_loss_by_example/sampled_softmax_loss_39/embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, validate_indices=true, _device="/device:GPU:0"](proj_b/read, sequence_loss_by_example/sampled_softmax_loss_39/concat)]]
Caused by op u'sequence_loss_by_example/sampled_softmax_loss_39/embedding_lookup_1', defined at:
  File "/opt/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/opt/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 403, in start
    ioloop.IOLoop.instance().start()
  File "/opt/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/opt/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 260, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "/opt/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 175, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2902, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3006, in run_ast_nodes
    if self.run_code(code, result):
  File "/opt/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-bfcd832d993d>", line 2, in <module>
    BATCH_SIZE, NUM_SAMPLES, MAX_GRADIENT_NORM, LEARNING_RATE, decay_factor = LEARNING_RATE_DECAY_FACTOR)
  File "<ipython-input-6-ca1988aa7469>", line 88, in __init__
    self.loss_sequence = seq2seq.sequence_loss_by_example(self.outputs, self.targets, self.tw, self.target_voca, softmax_loss_function = softmax_loss_function)
  File "seq2seq_mod070_ver5.py", line 974, in sequence_loss_by_example
    crossent = softmax_loss_function(logit, target)
  File "<ipython-input-6-ca1988aa7469>", line 66, in sampled_loss
    self.target_voca)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn.py", line 865, in sampled_softmax_loss
    name=name)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn.py", line 661, in _compute_sampled_logits
    all_b = embedding_ops.embedding_lookup(biases, all_ids)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 86, in embedding_lookup
    validate_indices=validate_indices)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 423, in gather
    validate_indices=validate_indices, name=name)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2040, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1087, in __init__
    self._traceback = _extract_stack()
```
what's the problem with this?

I heard that there are many device related things modified in release 0.8.0 just because of many of ops are coded with cuda(?)  then why not this part, I mean sampled_loss part in seq2seq_model.py

**Comment by aselle** [comment] 2016-06-02 21:31
Could you please include exact instructions on how you are running this (command line usage) so I can reproduce the problem. Thank you!

**Comment by ad26kt** [comment] 2016-06-03 08:06
Actually the problem occured when I run my own code which is very similar to translate.py + seq2seq_model.py. Im now using ver 0.7.1 . I found that there is no error when i change all of the "/cpu:0" to "/gpu:0" (please refer to below code) from seq2seq_model.py but my own code . with my code when they are not changed, code runs well, but when changed, outputs the error (error above)

```javascript
if num_samples>0 and num_samples<self.target_vocab_size:
with tf.device("/cpu:0"):
w = tf.get_variable("proj_w", ..........
.......
def sampled_loss(inputs, labels):
with tf.device("/cpu:0"):
...

```

can you explain what does the error exactly mean?
and I have one more question is that : even it works with those tf.device("/gpu:0"), why there are still using tf.device("/cpu:0")  (files in the path tensorflow/python/ops ), any other reason?

**Comment by aselle** [comment] 2016-07-09 03:52
At this point I'd recommend trying things on 0.9 since 0.7.1 is quite old at this point. If you want further help, a complete reproducible test case would be necessary.

**Comment by aselle** [comment] 2016-07-18 18:06
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-18 18:06 UTC
Labels: awaiting response, installation/startup
