### ISSUE TITLE
glog macros are redefined by platform/logging.h, included by refcount.h

### ISSUE THREAD

**Issue by abcdabcd987** [tensorflow/tensorflow#25913] opened 2019-02-20 06:37 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): `42c4f4ab6b53bce8639c203d7839d27eac11bd2f`
- Python version: 3.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 5.4.0-6ubuntu1~16.04.10
- CUDA/cuDNN version: 9.0 / 7
- GPU model and memory: 8x GTX 1080 Ti 12GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

```
In file included from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/logging.h:25:0,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/lib/core/refcount.h:22,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/tensor_coding.h:21,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/resource_handle.h:19,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/allocator.h:24,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/tensor.h:22,
                 from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/public/session.h:24,
                 from bug.cc:2:
/tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/default/logging.h:95:0: warning: "LOG" redefined
 #define LOG(severity) _TF_LOG_##severity
 ^
In file included from bug.cc:1:0:
/usr/local/include/glog/logging.h:506:0: note: this is the location of the previous definition
 #define LOG(severity) COMPACT_GOOGLE_LOG_ ## severity.stream()
 ^
```

**Describe the expected behavior**

No leaking `platform/logging.h` and no those warnings about redefining `glog` macros.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```c++
#include <glog/logging.h>
#include "tensorflow/core/public/session.h"

int main() {
    tensorflow::SessionOptions gpu_option;
}
```

```bash
export TF_INC_DIR=/tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include
g++ bug.cc -std=c++11 -I$TF_INC_DIR -I$TF_INC_DIR/external/com_google_absl
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I know TensorFlow has tried to avoid leaking the logging macros (#7480), but [`core/lib/core/refcount.h`](https://github.com/tensorflow/tensorflow/blob/42c4f4ab6b53bce8639c203d7839d27eac11bd2f/tensorflow/core/lib/core/refcount.h) is leaking them again. It seems that one way to fix it is to remove `#include "tensorflow/core/platform/logging.h"` from the headers and add them back in the `.cc` files. However, as said in `core/lib/core/refcount.h`, those are "Inlined routines, since these are performance critical" thus cannot be moved to a `.cc` file. But I'm sure there must be a way to stop leaking the logging macros.

**Comment by gunan** [comment] 2019-05-11 00:09
duplicate of #7480

**Closed by gunan** 2019-05-11 00:09 UTC
Labels: stat:awaiting tensorflower, type:bug/performance, type:build/install

**Comment by txyluffy** [comment] 2021-08-12 12:50
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): source
> * TensorFlow version (use command below): `42c4f4ab6b53bce8639c203d7839d27eac11bd2f`
> * Python version: 3.7
> * Bazel version (if compiling from source): 0.21.0
> * GCC/Compiler version (if compiling from source): 5.4.0-6ubuntu1~16.04.10
> * CUDA/cuDNN version: 9.0 / 7
> * GPU model and memory: 8x GTX 1080 Ti 12GB
> 
> You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with
> python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
> 
> **Describe the current behavior**
> 
> ```
> In file included from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/logging.h:25:0,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/lib/core/refcount.h:22,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/tensor_coding.h:21,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/resource_handle.h:19,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/allocator.h:24,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/framework/tensor.h:22,
>                  from /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/public/session.h:24,
>                  from bug.cc:2:
> /tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include/tensorflow/core/platform/default/logging.h:95:0: warning: "LOG" redefined
>  #define LOG(severity) _TF_LOG_##severity
>  ^
> In file included from bug.cc:1:0:
> /usr/local/include/glog/logging.h:506:0: note: this is the location of the previous definition
>  #define LOG(severity) COMPACT_GOOGLE_LOG_ ## severity.stream()
>  ^
> ```
> 
> **Describe the expected behavior**
> 
> No leaking `platform/logging.h` and no those warnings about redefining `glog` macros.
> 
> **Code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> 
> ```c++
> #include <glog/logging.h>
> #include "tensorflow/core/public/session.h"
> 
> int main() {
>     tensorflow::SessionOptions gpu_option;
> }
> ```
> 
> ```shell
> export TF_INC_DIR=/tmp/tensorflow/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/tensorflow/include
> g++ bug.cc -std=c++11 -I$TF_INC_DIR -I$TF_INC_DIR/external/com_google_absl
> ```
> 
> **Other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> I know TensorFlow has tried to avoid leaking the logging macros (#7480), but [`core/lib/core/refcount.h`](https://github.com/tensorflow/tensorflow/blob/42c4f4ab6b53bce8639c203d7839d27eac11bd2f/tensorflow/core/lib/core/refcount.h) is leaking them again. It seems that one way to fix it is to remove `#include "tensorflow/core/platform/logging.h"` from the headers and add them back in the `.cc` files. However, as said in `core/lib/core/refcount.h`, those are "Inlined routines, since these are performance critical" thus cannot be moved to a `.cc` file. But I'm sure there must be a way to stop leaking the logging macros.

Have you resolve this problem ? thank you
