### ISSUE TITLE
MemoryError in the middle of training after x epochs: _XlaCompile error at beginning

### ISSUE THREAD

**Issue by arjay55** [tensorflow/tensorflow#29696] opened 2019-06-12 15:10 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- custom code
- Windows 10 1803
- TensorFlow installed using pip with conda as environment manager. 
    `pip install --ignore-installed --upgrade tensorflow-gpu==2.0.0-beta0`
- TensorFlow version unknown 2.0.0-beta0
- Python version: 3.6.8
- CUDA version: 10.0
- GPU model and memory: Nvidia GeForce 1060 3GB

**Describe the current behavior**
While training the model after a number of epochs, a MemoryError suddenly occurs with top Error as `Operation 'simple_rnn_1/while' has no attr named '_XlaCompile'`. This occured while extending the training epochs by executing `model.fit()` subsequently. However, restarting the computer resolves the problem. 

_The problem occurred only once so far._ 

**Describe the expected behavior**
The training should finish after the set number of epochs.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
uniform_regularizer=0
model=tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(
    units=5,
    kernel_initializer='he_normal',
    recurrent_initializer='he_normal',
    kernel_regularizer=tf.keras.regularizers.l1(l=uniform_regularizer),
    use_bias=False,
    stateful=True,
    batch_input_shape=(3, 20, 3)),
    tf.keras.layers.Dense(3,
        kernel_initializer='he_normal',
        kernel_regularizer=tf.keras.regularizers.l1(l=uniform_regularizer),
        use_bias=False)
])
def loss(explanvar, targetvar):
  return tf.keras.metrics.mean_absolute_error(
    explanvar,
    targetvar)
model.compile(
    optimizer='adam',
    loss = loss)
checkpoint_path = "training_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create checkpoint callback
cp_callback = tf.keras.callbacks.ModelCheckpoint(checkpoint_path,
                                                 save_weights_only=True)
history = model.fit(train, 
                    epochs=55, 
                    steps_per_epoch=10,
                    callbacks=[cp_callback],
                    class_weight={0:0.4,
                                  1:0.2,
                                  2:0.4},                   
                    validation_data=test)
```
**Other info / logs**
_See attached file_
[stacktrace.txt](https://github.com/tensorflow/tensorflow/files/3281953/stacktrace.txt)

**Comment by ravikyram** [comment] 2019-06-20 08:46
@arjay55 Please provide us complete code to reproduce the issue.Thanks

**Comment by ravikyram** [comment] 2019-06-28 06:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-06-28 06:28 UTC
Labels: 2.0.0-beta0, comp:keras, stat:awaiting response, type:support
