### ISSUE TITLE
Help with object detection project

### ISSUE THREAD

**Issue by egamez099** [tensorflow/tensorflow#45630] opened 2020-12-12 17:49 UTC
Hi all,

I successfully trained my custom ssd_mobilenet_v2_quantized_300x300_coco model with 7 classes to detect.

However, I'm having the next issue when tried to run [this code](https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/TFLite_detection_webcam.py) for object detection:

`RuntimeError: tensorflow/lite/kernels/detection_postprocess.cc:404 ValidateBoxes(decoded_boxes, num_boxes) was not true.Node number 98 (TFLite_Detection_PostProcess) failed to invoke.`

The weirdest thing of all is the fact that if I run the exact same code in my workstation (with tf 1.15.1), the code works flawlessly, so it makes me think that there's something wrong with the raspberry.

The model was trained in Colab with tensorflow 1.15, and compiled with the following sintax:

!tflite_convert --graph_def_file=compiler/tflite_graph.pb --output_file=compiler/detect.tflite --output_format=TFLITE --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=128 --change_concat_input_ranges=false --allow_custom_ops

Any help will be so pleased. Thanks in advance!

**Comment by egamez099** [comment] 2020-12-12 17:50
I also googled some answers, which said that downgrading to tf 1.13 will solve the issue. Done that, downgrading and upgrading to every version that i can but the issue still occurs...Thanks for all

**Comment by Saduf2019** [comment] 2020-12-13 15:04
@egamez099 
Please refer to this resolved [issue](https://github.com/tensorflow/tensorflow/issues/42587#issuecomment-678813034) with same error and let us know. [ also verify if your pip version is latest]

**Comment by egamez099** [comment] 2020-12-13 15:18
Yes, actually tried to open the issue on EdjeElectronics repository as it's the author of the code that i'm using to test. Is there something that I've done wrong?

**Comment by srjoglekar246** [comment] 2020-12-14 17:10
@egamez099 How did you run the model on your workstation? Also, could you share what commands you ran before TFlite conversion? (As in, how did you get the intermediate graph for conversion to TFLite?)

**Comment by LSnyd** [comment] 2020-12-14 22:14
I am trying to run the same object detection model and I get the same error message. 
I am using tf 2.3 and tf-nightly 2.5 though.

Before the conversion I got the intermediate graph via export_tflite_graph_tf2.py

**Comment by srjoglekar246** [comment] 2020-12-14 22:29
@LSnyd There is no quantized model in the TF2 [detection zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). Which one did you download? And what command did you run for conversion? Note that the quantization parameters should not be specified if the model itself is not quantized.

**Comment by LSnyd** [comment] 2020-12-14 22:43
Ah sorry about that! I've used the SSD MobileNet v2 320x320 from the detection zoo. 

For the conversion I ran
`tflite_convert --saved_model_dir=/../my_model/saved_model --output_file=detect.tflite`

I tried to use the  tf.lite.TFLiteConverter.from_saved_model() approach before, but that didn't work either.

**Comment by srjoglekar246** [comment] 2020-12-15 16:51
@LSnyd  If you are following the instructions from [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md), the model *should* work fine. I am not fully sure of the inference code that @egamez099 pointed to, but anything equivalent to the `Test .tflite model` section in [this notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb) should work (in whichever language you are coding).

**Comment by egamez099** [comment] 2020-12-15 17:22
So I tried the following:

1. Exported the inference graph with:

`!python export_tflite_ssd_graph.py --pipeline_config_path="/content/drive/My Drive/Colab Data/models/research/object_detection/training/ssd_mobilenet_v1_quantized_300x300_coco14_sync.config" --trained_checkpoint_prefix=training/model.ckpt-2178 --output_directory=compiler/ --add_postprocessing_op=true
`
2. Converted the model with:

```
output_file=detect.t!tflite_convert \
--graph_def_file=compiler/tflite_graph.pb \
--output_file=compiler/detect.tflite \
--output_format=TFLITE \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_dev_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops

```

So, as you might notice, I changed the model to mobilenet v2 to v1, and surprisingly now runs fine on the rpi....Don't know why and how, but it runs flawlessly with the exact same code.

Now the error happens when I compile the model on Ubuntu for the Coral TPU, and running with the same script...Things only got weirder at this time

**Comment by LSnyd** [comment] 2020-12-15 20:58
@srjoglekar246  the inference code works fine, I've tested it on a pretrained model. 

When I followed the instructions that you pointed to, I didn't receive a meaningful model after conversion. The file was only a couple bytes large and netron didn't show any meaningful content within the model. I did not add a representative dataset though, so maybe that's the reason. 

With `tflite_convert --saved_model_dir=/../my_model/saved_model --output_file=detect.tflite`
I've received only a meaningful model for 

- ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8 
- ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8

 when using tf-nightly==2.5.0.dev20201213. The newest tf-nightly release didn't work either. 

The conversion for the ssd_mobilenet_v2_320x320_coco17_tpu-8 still does not work via the same approach. 
I'll just keep going with the ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 model now. Thank you for your help!

**Comment by dragonSwords98** [comment] 2020-12-25 06:15
Hello,

I've transferred learned the [ssd_mobilenet_v2_320x320_coco17_tpu-8](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz) from tf2 model zoo. I'm trying to convert this model to tflite to uint8 (quantized) to work on the edge tpu. However, I am currently stuck on the converter step, not the edge-tpu compiling step. Here's my training [gist](https://gist.github.com/dragonSwords98/b6bfae0c5021044041a65040f03a281f) and my converting [gist](https://gist.github.com/dragonSwords98/bab7796969c7684b333aa5259cdaa351). They are a bit lengthy, the important things are at the bottom of the gist.

In my converting gist, I took the problem in a few directions and took clues from recent forums on this topic.

Without tf-nightly, using tensorflow 2.5 as of 2020/12/24, I encounter this error:
`<unknown>:0: error: loc(callsite(callsite("Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/Size@__inference_call_func_21233" at "StatefulPartitionedCall@__inference_signature_wrapper_21902") at "StatefulPartitionedCall")): 'tf.Size' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Size {device = ""}`

Once I install tf-nightly and as of the v.12/24 and for the past few weeks of builds, have all brought me to the same errors.

Attempt: _Whenever I try a representative dataset that casts my training images into float32_
`Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: serving_default_input_tensor:0`

There is not really any web search that yields someone with this exact FLOAT32 - UINT8 issue. However, I would assume this is because the input tensor images from the rep dataset maybe need to be in uint8. However:

Attempt: _Whenever I try a representative dataset that casts my training images into uint8_
`Max and min for dynamic tensors should be recorded during calibration: Failed for tensor Cast
Empty min/max for tensor Cast`

I must be missing some important dtype knowledge, because most code snippets I have seen through web searching did not try to convert the images to uint8 before feeding it to the converter. This current open ticket and this open ticket #45302 are the closest matches to my issue.

I'm wondering if there's some model fundamentals or dtypes logic I need to read up on?

Is anyone else trying to use tf2 detection models zoo to make some full integer, edge tpu compatible models too? Did anyone come up with a fallback if this method did not work?

What's a good way to debug this?

Hopefully, others may benefit from solving this problem too?

Thanks, Happy Holidays all~

**Comment by srjoglekar246** [comment] 2020-12-28 18:49
@dragonSwords98 Before we look into quantization, it might be good to check if floating-point conversion & inference works for you as intended. Maybe using our Python API like the `Test .tflite model` section [here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb).

In your gist, I see that the SavedModel path given to the TFLite Converter is not the same as what you output from `export_tflite_graph_tf2.py`. Or am I missing something? That script essentially creates an SSD model that is TFLite-compatible. The error you see seems to be from trying to convert a non-TFLite-compatible model.

For the representative dataset gen function, you can do something like this:

```
for i in range(num_calibration_steps):
    image = tf.io.read_file(os.path.join(data_dir, image_files[i]))
    image = tf.compat.v1.image.decode_jpeg(image)
    image = preprocess_fn(image)
```
You can find an implementation of `preprocess_fn` [here](https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py#L258). I *think* the preprocessing you are using is similar, though I haven't taken a deeper look.

If the model converts & does inferences fine on float, the quantization should happen as expected with the representative data gen code above.

**Comment by dragonSwords98** [comment] 2021-01-03 22:34
@srjoglekar246 Hello Sachin, thanks for the response.

One of the models I tried did end up passing inference tests as you suggested. Thanks for that. And that same model did work on the edge tpu.

I may have too many models, so likely provided different pieces from various attempts. Apologies for that.

As you mentioned in your last paragraph, all these points checked out when I finally got it working. Thanks!

**Comment by mohantym** [comment] 2022-10-27 08:45
Hi @egamez099 !
1.x versions are not supported any more.  
For 2.x version, You can refer [lite model maker library ](https://www.tensorflow.org/lite/models/modify/model_maker/object_detection). Please use metadata writer to normalize your lite model prior deploying in android/edge devices to avoid configuration errors.

Thank you!

**Closed** 2022-11-10 10:02 UTC
Labels: stat:awaiting response, stalled, comp:lite, type:others
