### ISSUE TITLE
bad performance when build with jemalloc

### ISSUE THREAD

**Issue by chengdianxuezi** [tensorflow/tensorflow#21272] opened 2018-07-31 11:53 UTC
I try to build tf r1.8 with jemalloc.
I test the perfermance of r1.8 with jemalloc, found that the model use more sys use. the result as follow:

```
tf r1.8 with jemalloc:
    virturl memory: 29581 MB,real memory: 16185 MB, user cpu: 751.623, sys cpu: 145.979
tf r1.8 without  jemalloc:
    virturl memory: 24491 MB,real memory: 14520 MB, user cpu: 748.362, sys cpu: 18.4359
```
I tested several models and found that they all have this phenomenon.

**Comment by tensorflowbutler** [comment] 2018-07-31 19:00
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment] 2018-07-31 19:03
@gunan do you know the state of the jemalloc build? Does anyone maintain it?

**Comment by gunan** [comment] 2018-08-01 19:49
@jhseu may know.
I thought we moved to tcmalloc, which is nowadays faster than jemalloc?

**Comment by jhseu** [comment] 2018-08-01 20:27
It's actually known that there are situations where jemalloc performs worse, but on average it performs better.

Switching to tcmalloc is blocked at the moment.

**Comment by chengdianxuezi** [comment] 2018-08-02 02:27
@gunan @jhseu I test tcmalloc、jemalloc、ptmalloc performance with 60 threads,found that when alloc small memory,tcmalloc is a lillter beter than jemalloc, ptmalloc  has the worst performance.but when alloc 
large memory, ptmalloc is the best.  the reason may be that when alloc small memory,jemalloc and tcmalloc 
use thread cache memory. Can we use tcmalloc when applying for small memory, and use a self define memory pool when applying for large memory?

the performance result as follow:
```
when alloc memmory <= 32 KB  :  tcmalloc > jemalloc > ptmalloc
when alloc 32KB < memmory <= 256 KB  :  tcmalloc > ptmalloc > jemalloc
when alloc > 256 KB :  ptmalloc > jemalloc > tcmalloc
```

the code as follow:
```
#include <iostream>
#include <ctime>
#include <cstdlib>
#include <thread>

void malloc_test(int time, int size) {
    char *p = NULL;
    for (int i = 0; i < time; i++) {
        p = (char*)malloc(size);
        free(p);
    }
}

int main(int argc, char *argv[]) {
    int num_thread = atoi(argv[1]);
    int time = atoi(argv[2]);
    int size = atoi(argv[3]);
    std::cout << "num_thread is " << num_thread << " ,malloc time is " << time << " ,malloc size is " << size << std::endl;
    clock_t start_time = clock();
    std::thread threads[num_thread];
    for (int i = 0; i < num_thread; i++) {
        threads[i] = std::thread(malloc_test, time, size);
    }

    for(auto& t: threads) {
        t.join();
    }

    clock_t finish_time = clock();

    std::cout << "total time (s) is  " << (finish_time - start_time) / CLOCKS_PER_SEC << std::endl;
    return 0;
}
```

**Comment by tensorflowbutler** [comment] 2018-08-17 19:00
Nagging Assignee @skye: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-01 18:45
Nagging Assignee @skye: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by skye** [comment] 2018-09-06 22:18
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by skye** 2018-09-06 22:18 UTC
