### ISSUE TITLE
ValueError: Unknown loss function:smooth_l1_loss

### ISSUE THREAD

**Issue by lxz1104** [tensorflow/tensorflow#34731] opened 2019-12-01 07:32 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):  anaconda
- TensorFlow version (use command below): 2.0
- Python version: 3.7.5
- CUDA/cuDNN version: 10.1

**Error info**
```
Traceback (most recent call last):
  File "/home/lxz/PycharmProjects/PoseREN_tf2/src/train_baseline.py", line 115, in <module>
    baseline_model_load = tf.keras.models.load_model(MODEL_DIR, 'baseline.h5')
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 93, in load
    model._training_config))  # pylint: disable=protected-access
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 336, in compile
    self.loss, self.output_names)
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1351, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1351, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1087, in get_loss_function
    loss_fn = losses.get(loss)
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 1183, in get
    return deserialize(identifier)
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 1174, in deserialize
    printable_module_name='loss function')
  File "/home/lxz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 210, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown loss function:smooth_l1_loss
```

**Code crop**
```
# Loss func
@tf.function
def smooth_l1_loss(y_true, y_pred):
    return tf.compat.v1.losses.huber_loss(y_true, y_pred)


baseline_model.compile(optimizer=keras.optimizers.SGD(learning_rate=LEARNING_RATE, momentum=MOMENTUM, decay=DECAY),
                           loss=smooth_l1_loss, 
                           metrics=['MeanAbsoluteError'])  

history = baseline_model.fit(x=train_images, y=train_labels, validation_data=(vali_images, vali_labels),
                                 steps_per_epoch=np.ceil(train_images.shape[0] / BATCH_SIZE),
                                 validation_steps=np.ceil(vali_images.shape[0] / BATCH_SIZE),
                                 epochs=EPOCHS, batch_size=BATCH_SIZE,
                                 callbacks=callbacks)

baseline_model.save(MODEL_DIR, 'baseline.h5')

baseline_model_load = tf.keras.models.load_model(MODEL_DIR, 'baseline.h5')

test_data = np.random.random((1, 96, 96)).reshape((-1, 96, 96, 1))
print(baseline_model_load.predict(test_data))
```

**Comment by oanush** [comment] 2019-12-02 05:00
@lxz1104 ,
Hi,can you please provide complete code to reproduce the error ?Thanks!

**Comment by oanush** [comment] 2019-12-12 08:53
@lxz1104 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2019-12-20 08:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-12-20 08:57 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:bug
