### ISSUE TITLE
What does BuiltinOperator Resolver does ? what is custom ops in resolver.

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#37232] opened 2020-03-02 14:09 UTC
I was trying to run Inference on Tflite Models. I want to know what BuiltinOperator Resolver does ? what are the custom ops in resolver operator

**Comment by ravikyram** [comment] 2020-03-03 06:13
@pranathibl 

Can you please go through[ link1](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/op-resolver), [link2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/all_ops_resolver.cc) and see if it helps you.
![opresolver](https://user-images.githubusercontent.com/51902062/75747876-16ce4e80-5d44-11ea-9026-927ff62bfee5.png).
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by pranathibl** [comment] 2020-03-03 06:21
Hi ravikyram, 

Thanks for the information provided.

Could you please share the book/pdf where you took the screenshot. I would like to have better understanding of classes/methods used in tensorFlow lite. That would be very helpful.

Thanks,

**Comment by ravikyram** [comment] 2020-03-03 06:44
@pranathibl 
Please, find the pdf link [here](https://books.google.co.in/books?id=tH3EDwAAQBAJ&pg=PT470&dq=what+is+custom+ops+in+resolver&hl=en&sa=X&ved=0ahUKEwjpyL3Tzf3nAhVI7HMBHSpNAIQQ6AEIKjAA#v=onepage&q=what%20is%20custom%20ops%20in%20resolver&f=true).Please, close this thread if it solves your question. Thanks!

**Comment by pranathibl** [comment] 2020-03-03 06:53
Hi ravikyram,

Thanks for sharing the pdf. 

As per my understanding, opResolver fetches the operations implemtations needed to run Inference on model without fetching all function implementations. Let me know I am wrong ?

I didn't understand what does custom op resolver actually mean ? Will the user do any modifications to Model ? 
Please provide details on what custom resolver does ?

Once I got clarity on this, I would close this thread ?

**Comment by ravikyram** [comment] 2020-03-03 08:49
@pranathibl 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by pranathibl** [comment] 2020-03-04 05:18
Thanks for the info

**Closed** 2020-03-04 05:18 UTC
Labels: comp:lite, stat:awaiting response, type:support
