### ISSUE TITLE
Tensorflow AOT compiled graph does not use GPU

### ISSUE THREAD

**Issue by Kwander** [tensorflow/tensorflow#25539] opened 2019-02-06 09:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0 (tensorflow-gpu, tensorflow-base)
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA/cuDNN version: 7.1.2
- GPU model and memory: GeForce GTX 1080, 8GB

**Describe the current behavior**
Following the https://gist.github.com/carlthome/6ae8a570e21069c60708017e3f96c9fd tutorial, which is based on https://www.tensorflow.org/xla/tfcompile, all the compilation steps succeed. I am also able to invoke the compiled graph, producing correct prediction results. A non-compiled predict of a single image using RestNet50 takes 5ms, a compiled version takes ~140ms.

Note: I have ran ./configure via a terminal to use force CUDA support (such option is not accepted in the example).

**Describe the expected behavior**
The compiled version prediction of a single image should be as fast as a non-compiled prediction. I suspect the compiled graph uses CPU for the inference.

**Code to reproduce the issue**
Follow the https://gist.github.com/carlthome/6ae8a570e21069c60708017e3f96c9fd tutorial. To evaluate the compiled and the non-compiled graph prediction of a single image duration, add these two lines to the end of the notebook:

`%timeit -n 20 predict(x)`
`%timeit -n 20 model.predict(x)`

**Comment by jvishnuvardhan** [comment] 2019-03-01 00:48
@Kwander Is this related to [this](https://github.com/tensorflow/tensorflow/issues/25548). If it is duplicate, please close this. If it is not duplicate, did you enable/disable XLA here. Thanks!

**Comment by jlebar** [comment] 2019-03-01 18:15
> Tensorflow AOT compiled graph does not use GPU

This behavior is WAI.  AOT compilation only uses the CPU.  If you want to use the GPU, you can't use AOT compilation.

**Comment by jvishnuvardhan** [comment] 2019-03-07 00:44
I think it was resolved. I am closing this issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-07 00:44 UTC
Labels: comp:gpu, stat:awaiting response, type:bug/performance

**Comment by mati1994** [comment] 2019-04-28 03:46
> > Tensorflow AOT compiled graph does not use GPU
> 
> This behavior is WAI. AOT compilation only uses the CPU. If you want to use the GPU, you can't use AOT compilation.

Sorry to bother. I just did something similar to this issue. Since I can't find what WAI is, could you please tell me what it is?
Besides, do you know is there another way to use pure GPU acceleration for compiled DL model since AOT won't use GPU and JIT requires compiling every time the model runs. Just Thank you!

**Comment by jlebar** [comment] 2019-04-28 04:33
WAI = working as intended.

There is no way today to use XLA:GPU without recompiling every time.  It's
not something on our roadmap.

**Comment by oscarriddle** [comment] 2019-12-26 06:57
@jlebar Just wonder is there any progress to improve the every recompiling?

**Comment by jlebar** [comment] 2019-12-26 14:41
Hi, happy holidays.

I left the project a few months ago, you'll want to check with sanjoy@.
