### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by bash-s** [tensorflow/tensorflow#72888] opened 2024-07-31 14:46 UTC
Numpy's version has been already upgraded to 2.x, but now tensorflow can't support it.Can you upgrade the tensorflow library?

**Comment by bash-s** [comment] 2024-07-31 14:47
I'll appreciate it if you can upgrade it.

**Comment by mihaimaruseac** [comment] 2024-07-31 16:45
duplicate of #67291

**Closed by mihaimaruseac** 2024-07-31 16:45 UTC
