### ISSUE TITLE
cannot set tf.Variable as model input

### ISSUE THREAD

**Issue by w19787** [tensorflow/tensorflow#38463] opened 2020-04-12 02:52 UTC
Tensorflow: 2.1.0

I intend to utilize a pre-trained model and input a trainable input noise. but it is not allowed in tensorflow 2.0. want to find out whether it is a bug or by design.

```python
init_value = tf.random.normal((1, 512, 512, 3))
noise_input = tf.Variable(init_value, trainable=True)

pretrained_vgg19 = tf.keras.applications.VGG19(include_top=False, input_shape=(512, 512, 3))
pretrained_vgg19.predict(noise_input)
```
![image](https://user-images.githubusercontent.com/731496/79059341-60974680-7cab-11ea-957c-6e57f5fc237c.png)

**Comment by khimraj** [comment] 2020-04-12 12:06
@w19787, `tf.Variable` is used for trainable variables such as weights (W) and biases (B) for your model. Tensor is given as input to model. Working code:
```
import tensorflow as tf
init_value = tf.random.normal((1, 512, 512, 3))
pretrained_vgg19 = tf.keras.applications.VGG19(include_top=False, input_shape=(512, 512, 3))
pretrained_vgg19.predict(init_value)
```

**Comment by w19787** [comment] 2020-04-13 10:18
> @w19787, `tf.Variable` is used for trainable variables such as weights (W) and biases (B) for your model. Tensor is given as input to model. Working code:
> 
> ```
> import tensorflow as tf
> init_value = tf.random.normal((1, 512, 512, 3))
> pretrained_vgg19 = tf.keras.applications.VGG19(include_top=False, input_shape=(512, 512, 3))
> pretrained_vgg19.predict(init_value)
> ```

The above code is working for normal predict case. but if we want to use pretrained vgg model to trained a noise input, it is not the solution. Actually, we expect the input tf.Variable to be trainable.  I believe in tensorflow 1.0, tf.Variable as model input can be trainable, but it seems that it is not the case in 2.0.

**Comment by amahendrakar** [comment] 2020-04-13 14:03
Was able to run the code without any issues with [TF v2.0](https://colab.research.google.com/gist/amahendrakar/e15e448f640f9d02fc65668d91e757c6/38463-2-0.ipynb). 

Facing an error stating `ValueError: Failed to find data adapter that can handle input: <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>, <class 'NoneType'>`, while running with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/efa9fb1d2732e992d84e72346e525906/38463.ipynb#scrollTo=tceBD5eJyuT7) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/c1e12c2cdf4ca657eaadbd069323c0ff/38463-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by gowthamkpr** [comment] 2020-04-13 21:04
@w19787 Can you provide a reproducible case of tensorflow 1.0 showing tf.Variable as model input can be trainable. Thanks!

**Comment by w19787** [comment] 2020-04-14 13:51
> @w19787 Can you provide a reproducible case of tensorflow 1.0 showing tf.Variable as model input can be trainable. Thanks!

You can refer to the below project training file:
https://github.com/LouieYang/deep-photo-styletransfer-tf/blob/master/photo_style.py

the line 228 create the input image as tf.Variable and line 291 to optimize/computing the gradients only on this input image. 
thanks in advance.

**Comment by ymodak** [comment] 2020-04-19 02:39
@w19787 This is fixed with latest tf-nightly version ''2.2.0-dev20200418' as well TF 2.2.0-rc3. Thanks!

**Comment by ravikyram** [comment] 2020-07-09 13:38
I have tried in colab with TF version 2.3-rc1 and nightly versions(`2.4.0-dev20200709`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/67488abbfa79405c8687e7fb865bb7f2/untitled107.ipynb).Thanks!

**Comment by ravikyram** [comment] 2020-07-29 09:33
I have tried in colab with TF version 2.3.0, nightly version(`2.4.0-dev20200729`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a0ccdab8ae5d0093753b7c84026b4741/untitled196.ipynb).Thanks!

**Comment by saikumarchalla** [comment] 2020-11-05 15:14
@w19787 Closing this issue since it was the intended behavior.Thanks!

**Closed by saikumarchalla** 2020-11-05 15:14 UTC
Labels: TF 2.3, comp:keras, regression issue, type:bug
