### ISSUE TITLE
Can't access resource variable using GetResourceFromContext in a custom op, probably because of binary incompatibility

### ISSUE THREAD

**Issue by liamuk** [tensorflow/tensorflow#25113] opened 2019-01-22 19:22 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Mojave
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- GCC/Compiler version (for custom op): g++ 4.2.1 Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Describe the problem**

When I try to use `GetResourceFromContext` with `T` being `Var` from a custom op, I get the following error ```InvalidArgumentError (see above for traceback): Trying to access resource using the wrong type. Expected N10tensorflow3VarE got N10tensorflow3VarE```

So it seems like the types match up, but for whatever reason the `std::type_index`s generated from them don't? My hypothesis is it's because using `std::type_index` across a shared library is implementation defined behavior and the compiler does not produce the same `std::type_index` for the same type in both the custom op library and `libtensorflow_framework`.

For context, I'm trying to get access to the resource's underlying tensor so that I can modify it.

**Comment by jvishnuvardhan** [comment] 2019-02-15 00:05
@liamuk Could you provide more details about the error and context? Thanks!

**Comment by liamuk** [comment] 2019-02-15 00:43
This bug is no longer relevant to me, and I don't have the original code that triggered it.

You should be able to reproduce it, though, if you create a c++ custom op that takes an argument of type `resource` like how `ResourceApplyGradientDescent` in `ops/training_ops.cc` does, and then attempt to use `GetResourceFromContext` defined in `framework/resource_mgr.h` to access it from the op.

The context is trying to write a custom op that manipulates the buffer underlying a resource variable.

**Comment by aselle** [comment] 2019-07-29 18:50
Is this bug still an issue?

**Comment by liamuk** [comment] 2019-07-29 19:54
Not an issue for me personally bc I’m no longer working with custom ops.

Not sure if it still exists in Tensorflow.

**Comment by anush-o** [comment] 2019-07-31 10:48
@liamuk ,
Can you confirm if we can proceed for closure?Thanks!

**Comment by liamuk** [comment] 2019-07-31 22:04
I don't mind if you close it.

**Comment by jvishnuvardhan** [comment] 2019-07-31 22:09
I am closing this issue. If the issue persists with latest TF versions, please feel free to open the issue again. Thanks!

**Closed by jvishnuvardhan** 2019-07-31 22:09 UTC
Labels: comp:ops, stat:awaiting response, type:bug

**Comment by zhezherun** [comment] 2020-09-30 13:07
I am facing the same issue when trying to compile a custom op on Mac and on Windows (it works fine on Linux though), using Tensorflow 2.3. When running on Mac, I get the same error, i.e.:

```Trying to access resource using the wrong type. Expected N10tensorflow3VarE got N10tensorflow3VarE [Op:CustomOp]```

On Windows, the error is similar:

```Trying to access resource using the wrong type. Expected class tensorflow::Var got class tensorflow::Var [Op:CustomOp]```

On Linux, there is no error and the op works as expected.

I think this issue is due to the use of an address of a static variable ```hash_bit``` in ```TypeIndex::Make<T>``` as a hash. When the shared library with the custom is compiled, it will have its own copy of ```TypeIndex::Make<Var>::hash_bit```, so the hash codes for the same type (e.g. ```Var```) will be different. I think it works on Linux because a STB_GNU_UNIQUE symbol is generated for ```hash_bit```, so that there is only one definition of it (per type) in the whole process. Mac and Windows don't have this feature though.

Is it possible to rewrite TypeIndex in a way that will make it work across shared libraries on all platforms? Or perhaps various instantiations of ```TypeIndex::Make<T>``` could be exported from tensorflow framework library?

For some reason I cannot attach a zipped reproducer to this comment, so I will try pasting the code in a reply below.

**Comment by zhezherun** [comment] 2020-09-30 13:12
Reproducer: a simple custom op to set a value of a variable.
```
#define EIGEN_USE_THREADS

#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/resource_mgr.h"
#include "tensorflow/core/framework/register_types.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/kernels/training_op_helpers.h"

using namespace tensorflow;


template<typename Device, typename T>
class CustomOp: public OpKernel {
 public:
  explicit CustomOp(OpKernelConstruction* c) : OpKernel(c) {
    OP_REQUIRES_OK(c, c->GetAttr("use_locking", &use_exclusive_lock_));
  }

  void Compute(OpKernelContext* c) override {
    core::RefCountPtr<Var> v;
    OP_REQUIRES_OK(c, LookupResource(c, HandleFromInput(c, 0), &v));
    OP_REQUIRES_OK(c, EnsureSparseVariableAccess<Device, T>(c, v.get()));
    const Tensor& value = c->input(1);
    if (use_exclusive_lock_) {
      mutex_lock lock(*v->mu());
      DoCompute(c, *v->tensor(), value);
    } else {
      tf_shared_lock lock(*v->mu());
      DoCompute(c, *v->tensor(), value);
    }
  }

 private:
  bool use_exclusive_lock_;

  void DoCompute(OpKernelContext* c, Tensor& v, const Tensor& value) {
    OP_REQUIRES(c, v.IsInitialized(),
                errors::FailedPrecondition("Null ref for var"));
    OP_REQUIRES(c, TensorShapeUtils::IsVector(v.shape()),
                errors::InvalidArgument("var must be 1-D, got shape ",
                                        v.shape().DebugString()));
    OP_REQUIRES(c, TensorShapeUtils::IsScalar(value.shape()),
                errors::InvalidArgument("value must be a scalar, got shape ",
                                        value.shape().DebugString()));
    if (!c->status().ok()) return;

    T* data = v.flat<T>().data();
    T set_to = *value.flat<T>().data(); 
    for (size_t i = 0; i < v.NumElements(); ++i) {
      data[i] = set_to;
    }
  }
};
  

#define REGISTER_CUSTOM_KERNEL(type, dev, name) \
  REGISTER_KERNEL_BUILDER(Name(name) \
                              .Device(DEVICE_##dev) \
                              .HostMemory("var") \
                              .TypeConstraint<type>("T"), \
                          CustomOp<dev##Device, type>)
                              
#define REGISTER_CUSTOM_CPU(type) \
  REGISTER_CUSTOM_KERNEL(type, CPU, "CustomOp");

TF_CALL_REAL_NUMBER_TYPES(REGISTER_CUSTOM_CPU);

#undef REGISTER_CUSTOM_CPU
#undef REGISTER_CUSTOM_KERNEL

REGISTER_OP("CustomOp")
    .Input("var: resource")
    .Input("value: T")
    .Attr("T: type")
    .Attr("use_locking: bool = true")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      return Status::OK();
    });
```

**Comment by zhezherun** [comment] 2020-09-30 13:15
Reproducer: build scripts and Python test.
Linux:
```
#!/bin/sh
TF_CFLAGS=( $(python3 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python3 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

g++ -shared -O2 -std=c++11 -fPIC -o custom_op.so custom_op.cpp ${TF_CFLAGS[@]} ${TF_LFLAGS[@]}
```
Mac:
```
#!/bin/sh
TF_CFLAGS=( $(python3 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python3 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

g++ -shared -O2 -std=c++11 -fPIC -o custom_op.dylib custom_op.cpp ${TF_CFLAGS[@]} ${TF_LFLAGS[@]}
```
Windows:
```
set TF_CFLAGS=/Ic:\\Python\\lib\\site-packages\\tensorflow\\include
set TF_LFLAGS=/LIBPATH:c:\\Python\\lib\\site-packages\\tensorflow\\python _pywrap_tensorflow_internal.lib

cl /LD /O2 /EHsc /MD /DNOMINMAX /wd4624 /Fecustom_op.dll custom_op.cpp %TF_CFLAGS% /link %TF_LFLAGS%
```
Python test:
```
import sys
import tensorflow as tf

if sys.platform == 'win32':
    custom_module = tf.load_op_library('custom_op.dll')
elif sys.platform == 'darwin':
    custom_module = tf.load_op_library('custom_op.dylib')
else:
    custom_module = tf.load_op_library('custom_op.so')

def custom_op(var, value, use_locking=True, name=None):
    custom_module.custom_op(var.handle, value, use_locking=use_locking, name=name)

v = tf.Variable([1.0, 2.0, 3.0])
print(v)
custom_op(v, 2.22)
print(v)
```

**Comment by zhezherun** [comment] 2020-10-21 16:18
Since the is no activity here, I submitted a new bug report #44209.
