### ISSUE TITLE
[TF 2.0 keras] tf.keras.Concatenate Graph Disconnected when concatenating non-sequentially

### ISSUE THREAD

**Issue by mketcha** [tensorflow/tensorflow#30355] opened 2019-07-03 14:12 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary, pip install 
- TensorFlow version (use command below): tensorflow-gpu==2.0.0-beta1
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Error arises during Concatenate when I run the following code:

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, Concatenate

inputs = keras.Input(shape=(256,256,3))
x  = Conv2D(16,3, padding='same',activation='relu')(inputs)
x_list = [x]
for i in range(3):
    x = Conv2D(16,3, padding='same',activation='relu')(x)
    x_list.append(x)
    x = Concatenate(3)(x_list)

model = keras.Model(inputs=inputs, outputs=x)
model.summary()
```

`ValueError: Graph disconnected: cannot obtain value for tensor Tensor("conv2d_31/Identity:0", shape=(None, 256, 256, 16), dtype=float32) at layer "concatenate_8". The following previous layers were accessed without issue: ['input_9', 'conv2d_29', 'conv2d_30']`

This issue does not occur in a Tensorflow 1.X environment, only TF 2.0

**Describe the expected behavior**
Now the Concatenate function works properly when using a sequential model. That is, if I swap in "for i in range(1):" rather than "for i in range(3):" above, the code executes cleanly. However, the non-sequential repeated Concatenation in the loop leaves the  a Graph disconnected error.

Furthermore, the error is also eliminated when using tf.concat, so the following code also executes cleanly.

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, Concatenate

inputs = keras.Input(shape=(256,256,3))
x  = Conv2D(16,3, padding='same',activation='relu')(inputs)
x_list = [x]
for i in range(3):
    x = Conv2D(16,3, padding='same',activation='relu')(x)
    x_list.append(x)
    x = tf.concat(x_list, 3)

model = keras.Model(inputs=inputs, outputs=x)
model.summary()
```

Therefore, I do have a working alternative, but there does appear to be an issue with the keras Concatenate function

**Comment by gadagashwini** [comment] 2019-07-04 08:32
@mketcha Just to verify, Which Concatenate function of Keras did you use.I could find tf.keras.backend.concatenate and tf.keras.layers.Concatenate on Tensorflow website. Thanks!

**Comment by gadagashwini** [comment] 2019-07-04 08:43
@mketcha If it is tf.keras.layers.Concatenate then Concatenate function takes at least two list and syntax will be
 `x = Concatenate(3)([list1,list2])` 
Let us know if this helps. Thanks!

**Comment by mketcha** [comment] 2019-07-05 14:45
It is the tf.keras.layers.Concatenate.

 I don't believe it is an issue with my arguments as analagous code works in tensorflow 1.13, and the argument passes cleanly if I use "for i in range(1):"

It seems to be an issue with passing an argument that had previously already been used in a concatenation call

**Comment by sedghi** [comment] 2019-08-01 16:27
same error here,
but the tf.concat works as a workaround as @mketcha mentioned

**Comment by jvishnuvardhan** [comment] 2019-10-02 23:11
@mketcha I changed one line in your code to append all the three layers to `x_list` and then applied `concatenation` and the [gist is here](https://colab.sandbox.google.com/gist/jvishnuvardhan/d6f7c83b0315f3051023e8f915cce1ba/untitled527.ipynb). With that modification, it runs without any error. I have also plotted the model and is shown below. 
![image](https://user-images.githubusercontent.com/46058173/66087634-00219280-e52d-11e9-9f42-f3c9531d1c34.png)

# When I plot your workaround using tf.concat(), model looks like this shown below.
![image](https://user-images.githubusercontent.com/46058173/66088214-306a3080-e52f-11e9-829f-99276d476d3e.png)

Please let us know what you think. If this was res

**Comment by mketcha** [comment] 2019-10-04 17:57
@jvishnuvardhan While your workaround may run, it does not achieve the same desired architecture

**Comment by csachs** [comment] 2019-11-13 10:27
Hi, this is a regression in TF Keras. In standalone Keras, it was fixed by https://github.com/keras-team/keras/pull/6035 .

And it seems to be a duplicate of https://github.com/tensorflow/tensorflow/issues/32023 .

The workaround in user code is to copy the list at call time, e.g. by changing above example to:
```
    x = Concatenate(3)(x_list[:])
```

The fix for TF would be to copy the list at call time of the layer object, to prevent later outside modification.

**Comment by omalleyt12** [comment] 2020-03-15 05:39
Thanks for the issue!

This commit fixes the issue: 

https://github.com/tensorflow/tensorflow/commit/816ec796ea6a96940188356628566ed11a11c186

The fix should be available in tomorrow's nightly build

**Closed by omalleyt12** 2020-03-15 05:39 UTC
Labels: TF 2.0, comp:keras, type:bug
