### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by hn2** [tensorflow/tensorflow#28303] opened 2019-05-01 10:29 UTC
Python 3.7.3
tensorflow-gpu                     2.0.0a0
NVIDIA CUDA runtime 10.1 with cudnn-10.1-windows10-x64-v7.5.1.10

Traceback (most recent call last):
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hanna\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hanna\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 410, in main
    run()
  File "c:\Users\hanna\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\hanna\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\hanna\Google Drive\hannannussbaum\Data Science\TensorFlowTest.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hanna\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hanna\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by rootkitchao** [comment] 2019-05-01 15:07
Tensorflow requires cuda10.0 instead of 10.1.Please reinstall the correct version of CUDA and cuDNN.

**Comment by hn2** [comment] 2019-05-01 16:20
I installed cuda 10 and cudnn for cuda 10.
I followed instructions on:
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html
I get this: 

python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2019-05-01 19:15:16.317636: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-01 19:15:16.544680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.92GiB
2019-05-01 19:15:16.551192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-01 19:15:17.055182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-01 19:15:17.058195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-01 19:15:17.060549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-01 19:15:17.062575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4639 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
>>> print(sess.run(hello))
b'Hello, TensorFlow!'

Does this mean that installation is ok and it is using gpu with cuda and cudnn?
I also downgraded tensorflow from ver 2.0 to 1.13 
Is ver 2 supported?

**Comment by rootkitchao** [comment] 2019-05-01 21:12
> I installed cuda 10 and cudnn for cuda 10.
> I followed instructions on:
> https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html
> I get this:
> python
> Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> 
> 
> import tensorflow as tf
> hello = tf.constant('Hello, TensorFlow!')
> sess = tf.Session()
> 2019-05-01 19:15:16.317636: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 2019-05-01 19:15:16.544680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
> name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.77
> pciBusID: 0000:01:00.0
> totalMemory: 6.00GiB freeMemory: 4.92GiB
> 2019-05-01 19:15:16.551192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
> 2019-05-01 19:15:17.055182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-05-01 19:15:17.058195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
> 2019-05-01 19:15:17.060549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
> 2019-05-01 19:15:17.062575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4639 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
> print(sess.run(hello))
> b'Hello, TensorFlow!'
> 
> 
> 
> Does this mean that installation is ok and it is using gpu with cuda and cudnn?
> I also downgraded tensorflow from ver 2.0 to 1.13
> Is ver 2 supported?
 
Sorry, I don't use Anaconda, and I'm not sure Tensorflow 1.13 supports Python 3.7.

**Comment by gadagashwini** [comment] 2019-05-02 06:08
@hn2 This is duplicate of 26364[https://github.com/tensorflow/tensorflow/issues/26364](url). Thanks!

**Comment by gadagashwini** [comment] 2019-05-14 04:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-05-14 04:29 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install
