### ISSUE TITLE
Blas SGEMM launch failed

### ISSUE THREAD

**Issue by JWarlock** [tensorflow/tensorflow#9105] opened 2017-04-10 16:07 UTC
I just installed  TensorFlow-GPU 1.0.1 on Win10 GTX GEFORCE 850M with CUDA 8.0 and Cudnn v5.1, Anaconda3 4.2.0 64bit
when I try to figure out if the installation was successful, I run the 

> mnist_with_summaries.py
in 
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py](url)

When I run the code in Jupyter Notebook, it prints 

> Accuracy at step 0: 0.068
Accuracy at step 10: 0.6795
Accuracy at step 20: 0.8062
Accuracy at step 30: 0.8455
Accuracy at step 40: 0.8737
Accuracy at step 50: 0.8735
Accuracy at step 60: 0.8851
Accuracy at step 70: 0.8815
Accuracy at step 80: 0.8863
Accuracy at step 90: 0.8918

And the kernel just died.

When I try to run the code in command prompt, I get following error:

> >I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
> Extracting /tmp/tensorflow/mnist/input_data\train-images-idx3-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\train-labels-idx1-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\t10k-images-idx3-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\t10k-labels-idx1-ubyte.gz
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
> name: GeForce GTX 850M
> major: 5 minor: 0 memoryClockRate (GHz) 0.9015
> pciBusID 0000:0a:00.0
> Total memory: 4.00GiB
> Free memory: 3.35GiB
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 850M, pci bus id: 0000:0a:00.0)
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
> Traceback (most recent call last):
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
>     return fn(*args)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
>     status, run_metadata)
>   File "C:\Users\airfo\Anaconda3\lib\contextlib.py", line 66, in __exit__
>     next(self.gen)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : a.shape=(10000, 784), b.shape=(784, 500), m=10000, n=500, k=784
>          [[Node: layer1/Wx_plus_b/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_input/x-input_0/_45, layer1/weights/Variable/read)]]
>          [[Node: accuracy/accuracy/Mean/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_69_accuracy/accuracy/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "mnist_with_summaries.py", line 209, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "mnist_with_summaries.py", line 185, in main
>     train()
>   File "mnist_with_summaries.py", line 160, in train
>     summary, acc = sess.run([merged, accuracy], feed_dict=feed_dict(False))
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
>     run_metadata_ptr)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
>     feed_dict_string, options, run_metadata)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
>     target_list, options, run_metadata)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : a.shape=(10000, 784), b.shape=(784, 500), m=10000, n=500, k=784
>          [[Node: layer1/Wx_plus_b/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_input/x-input_0/_45, layer1/weights/Variable/read)]]
>          [[Node: accuracy/accuracy/Mean/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_69_accuracy/accuracy/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
> 

> Caused by op 'layer1/Wx_plus_b/MatMul', defined at:
>   File "mnist_with_summaries.py", line 209, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "mnist_with_summaries.py", line 185, in main
>     train()
>   File "mnist_with_summaries.py", line 101, in train
>     hidden1 = nn_layer(x, 784, 500, 'layer1')
>   File "mnist_with_summaries.py", line 95, in nn_layer
>     preactivate = tf.matmul(input_tensor, weights) + biases
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1765, in matmul
>     a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1454, in _mat_mul
>     transpose_b=transpose_b, name=name)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
>     op_def=op_def)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "C:\Users\airfo\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
>     self._traceback = _extract_stack()
> 
> InternalError (see above for traceback): Blas SGEMM launch failed : a.shape=(10000, 784), b.shape=(784, 500), m=10000, n=500, k=784
>          [[Node: layer1/Wx_plus_b/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_input/x-input_0/_45, layer1/weights/Variable/read)]]
>          [[Node: accuracy/accuracy/Mean/_49 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_69_accuracy/accuracy/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
> And this Internal error message appears three times.It shows that all dll files were successfully opened. ( too many error message, I just write down something I think useful. If anyone need more information, tell me).
> 

I found an answer on stackoverflow [http://stackoverflow.com/questions/41117740/tensorflow-crashes-with-cublas-status-alloc-failed](url), and I add :
```
`config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)`
```
just after:
`if __name__ == '__main__':`
this time the error is:

> > I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
> name: GeForce GTX 850M
> major: 5 minor: 0 memoryClockRate (GHz) 0.9015
> pciBusID 0000:0a:00.0
> Total memory: 4.00GiB
> Free memory: 3.35GiB
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 850M, pci bus id: 0000:0a:00.0)
> Extracting /tmp/tensorflow/mnist/input_data\train-images-idx3-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\train-labels-idx1-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\t10k-images-idx3-ubyte.gz
> Extracting /tmp/tensorflow/mnist/input_data\t10k-labels-idx1-ubyte.gz
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 850M, pci bus id: 0000:0a:00.0)
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
> Accuracy at step 0: 0.0886
> Accuracy at step 10: 0.6844
> Accuracy at step 20: 0.7995
> Accuracy at step 30: 0.8564
> Accuracy at step 40: 0.876
> Accuracy at step 50: 0.8819
> Accuracy at step 60: 0.8892
> Accuracy at step 70: 0.8881
> Accuracy at step 80: 0.8843
> Accuracy at step 90: 0.8912
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:126] Couldn't open CUDA library cupti64_80.dll
> F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\default\gpu\cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: cuptiActivityRegisterCallbacks not found)could not find cuptiActivityRegisterCallbacksin libcupti DSO

 I am totally lost. Could someone tell me why?

**Comment by tensorflowbutler** [comment] 2018-04-04 23:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-04-19 18:59
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-27 03:09
It has been 21 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-06-10 18:36
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by bhack** [comment] 2018-06-13 22:36
@tensorflowbutler Can you count days with a cumulative approach excluding your posts? So instead of 14 days is 14+21+29+14=78 days. I think that it is more informative as notification.

**Comment by bhack** [comment] 2018-06-13 22:41
@drpngx What do you think? This approach was already adopted in `Nagging Assignee`.

**Comment by drpngx** [comment] 2018-06-13 23:13
Yeah that makes sense. @yifeif @av8ramit ?

**Comment by yifeif** [comment] 2018-06-13 23:51
I think that is supposed to be the behavior by design (see comment on May 4, which says 29 days instead of 15 days). Not sure why it got regressed.

**Comment by bhack** [comment] 2018-06-14 00:00
The origin was in https://github.com/tensorflow/tensorflow/pull/12408#issuecomment-373941577 but then something regressed with `awaiting response` label `but on `Nagging Assignee` it still performs well with the new behavior.

**Comment by bhack** [comment] 2018-06-14 00:08
After solving this topic I think that we can close a bug on TF 1.0.1 after more then one year without response.
Remember the bottleneck theory and the "attention is all you need" :smile: or we will lost in the information noise expecially if you don't have enough bandwidth for all the `awaiting response` labels.

**Comment by yifeif** [comment] 2018-06-14 00:10
I think I know why. Fixing this.

**Comment by bhack** [comment] 2018-06-14 01:54
Can we close this?

**Comment by yifeif** [comment] 2018-06-14 17:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by yifeif** 2018-06-14 17:19 UTC
Labels: stat:awaiting response
