### ISSUE TITLE
TF Lite ESP32 make License issue

### ISSUE THREAD

**Issue by LEMAOR** [tensorflow/tensorflow#37601] opened 2020-03-14 22:50 UTC
**System information**
- Windows 10
-tensorflow cloned from git directly

**Describe the problem**
While trying to use make i get an issue with License:
```
C:\>make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
make: *** No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/LICENSE'.  Stop.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Using the batch file provided by esp32 i setup the path variables:

```
Using Python in C:\Program Files\Python36\
Python 3.6.8
Using Git in C:\Program Files\Git\cmd\
git version 2.21.0.windows.1
Setting IDF_PATH: C:\Esp_IDF_Release_4_0\esp-idf

Adding ESP-IDF tools to PATH...
    C:\Esp_IDF_Release_4_0\.espressif\tools\xtensa-esp32-elf\esp-2019r2-8.2.0\xtensa-esp32-elf\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\xtensa-esp32s2-elf\esp-2019r2-8.2.0\xtensa-esp32s2-elf\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\cmake\3.13.4\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\openocd-esp32\v0.10.0-esp32-20191114\openocd-esp32\bin
    C:\Esp_IDF_Release_4_0\.espressif\tools\ninja\1.9.0\
    C:\Esp_IDF_Release_4_0\.espressif\tools\idf-exe\1.0.1\
    C:\Esp_IDF_Release_4_0\.espressif\tools\ccache\3.7\
    C:\Esp_IDF_Release_4_0\.espressif\python_env\idf4.2_py3.6_env\Scripts
    C:\Esp_IDF_Release_4_0\esp-idf\tools

Checking if Python packages are up to date...
Python requirements from C:\Esp_IDF_Release_4_0\esp-idf\requirements.txt are satisfied.

Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build
```

**Any other info / logs**

make is working

idf.py --version
ESP-IDF v4.2-dev-701-g0ae960f2f

I made sure tensorflow folder is on c:/

**Comment by LEMAOR** [comment] 2020-03-17 04:32
Just tried with a fresh VM ubuntu, 
followed the installation for idf esp32 for linux successfully

but tensorflow make still fails:

```
sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
make: * No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/LICENSE'.  Stop.
```
$PATH has the xtensa files
and $IDF_PATH points to the proper folder

**Comment by cptang2007** [comment] 2020-03-17 09:40
Hello i got the same issue too
From the error prompt it seems the sdkconfg.defaults is missing in
` tensorflow/lite/micro/examples/hello_world/esp`

A workaround is copy the sdkconfig.defaults from another example folder, e.g. 
`tensorflow/lite/micro/examples/person-detection/esp/sdkconfig.defaults`
into the hello_world/esp folder

After that i can build and flash the hello_world example to the ESP32

**Comment by fredrec** [comment] 2020-03-17 11:07
Hi,

Thanks for reporting this issue. We identified the root cause and will push a fix soon.
Automated builds to detect that kind of problems early are coming as well.

The workaround mentioned by @cptang2007 seems to work, otherwise just creating an empty file should do:
```
touch tensorflow/lite/micro/examples/hello_world/esp/sdkconfig.defaults
```

**Comment by LEMAOR** [comment] 2020-03-17 14:14
After trying both workaruond im still unable to compile, I tried a non hello world project, and still getting the same error, this on ubuntu:

```
lm@LMvmub:/$ ls -l tensorflow/lite/micro/examples/hello_world/esp
total 4
-rw-r--r-- 1 root root 821 mar 16 21:43 main.cc
-rw-r--r-- 1 root root   0 mar 17 07:51 sdkconfig.defaults
lm@LMvmub:/$ sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
make: *** No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/LICENSE'.  Stop.
lm@LMvmub:/$ sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_micro_speech_esp_project
make: *** No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/micro_speech/esp-idf/LICENSE'.  Stop.
```

**Comment by cptang2007** [comment] 2020-03-17 16:07
> 
> 
> After trying both workaround I am still unable to compile, I tried a non hello_world project, and still getting the same error, this on ubuntu:
> 
> ```
> lm@LMvmub:/$ ls -l tensorflow/lite/micro/examples/hello_world/esp
> total 4
> -rw-r--r-- 1 root root 821 mar 16 21:43 main.cc
> -rw-r--r-- 1 root root   0 mar 17 07:51 sdkconfig.defaults
> lm@LMvmub:/$ sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
> make: *** No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/LICENSE'.  Stop.
> lm@LMvmub:/$ sudo make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_micro_speech_esp_project
> make: *** No rule to make target 'LICENSE', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/micro_speech/esp-idf/LICENSE'.  Stop.
> ```

seems the 'LICENSE' file is absent in the path 
`'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/micro_speech/esp-idf/LICENSE'`

I do have that LICENSE file in there though, maybe you can do the same trick to copy the LICENSE file to that folder ?

**Comment by LEMAOR** [comment] 2020-03-17 18:16
Just tried to do it, to no avail. It didn't Work.

```
lm@LMvmub:/$ sudo ls -l tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/
total 8
drwxr-xr-x 3 root root 4096 mar 16 21:51 components
-rw-r--r-- 1 root root    5 mar 17 12:08 LICENSE
```


I tried using debug tag on make and see what it prints, 

`sudo make -d -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project`

```
Successfully remade target file 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/components/tfmicro/tensorflow/lite/micro/memory_planner/greedy_memory_planner.h'.
  Considering target file 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/LICENSE'.
    Considering target file 'LICENSE'.
     File 'LICENSE' does not exist.
     Looking for an implicit rule for 'LICENSE'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.o'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.c'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.cc'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.C'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.cpp'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.p'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.f'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.F'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.m'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.r'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.s'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.S'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.mod'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.sh'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE,v'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'RCS/LICENSE,v'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'RCS/LICENSE'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 's.LICENSE'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'SCCS/s.LICENSE'.
     Trying pattern rule with stem 'LICENSE'.
     Trying implicit prerequisite 'LICENSE.o'.
```
it just keeps looking/iterating for a rule

**Comment by LEMAOR** [comment] 2020-03-23 08:18
I'm still unable to compile keep getting LICENSE error, is there something I could be doing wrong?
could it be the version of the esp IDF?

**Comment by LEMAOR** [comment] 2020-03-24 02:10
@fredrec any ideas or updates on what is going on here? cptang made an input but my particular issue got off the hook

**Comment by fredrec** [comment] 2020-05-15 15:18
@LEMAOR, I believe this issue was resolved last month. Can you check again using the master branch ?

**Comment by amahendrakar** [comment] 2020-11-19 13:38
> @LEMAOR, I believe this issue was resolved last month. Can you check again using the master branch ?

@LEMAOR,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

**Closed** 2020-12-03 14:51 UTC
Labels: comp:lite, comp:micro, comp:micro:espressif, stalled, stat:awaiting response, type:build/install

**Comment by mcuml** [comment] 2021-06-30 13:19
i meet the same problems

Must remake target 'tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/base.h'.
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/base.h', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/doorbell_camera/esp-idf/components/tfmicro/third_party/flatbuffers/include/flatbuffers/base.h'.  Stop.
root@ubuntu:/home/feng/esp/tf_test/tensorflow# make -f tensorflow/lite/micro/tools/make/Makefile  TARGET=esp generate_doorbell_camera_esp_project
tensorflow/lite/micro/tools/make/Makefile:295: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:295: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:295: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:295: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:295: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:295: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/base.h', needed by 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/doorbell_camera/esp-idf/components/tfmicro/third_party/flatbuffers/include/flatbuffers/base.h'.  Stop.
