### ISSUE TITLE
BroadcastTo

### ISSUE THREAD

**Issue by byronlan** [tensorflow/tensorflow#41574] opened 2020-07-21 02:57 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by amahendrakar** [comment] 2020-07-21 12:19
@byronlan,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by dipendra009** [comment] 2020-07-23 22:09
Hi,
I am trying to convert a mobilenetv3 model implemented using tensorflow2.2 into a TFLite model using the tf-lite convertor using the following command for LPCV competition:

python3 tensorflow/lite/python/tflite_convert.py --graph_def_file=~/Projects/save_models/mobilenetv4-1009/saved_model.pb --output_file=mobilenetv4-1009.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=FLOAT --input_shape="1,224,224,3" --input_array="input_1" --output_array=probs --mean_value="123.675,116.28,103.53" --std_dev_value="58.395,57.12,57.375" --saved_model_dir=/Users/z004njq/Projects/save_models/mobilenetv4-1009 --allow_custom_ops

I am having the following issue:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, CONV_2D, DEPTHWISE_CONV_2D, DIV, FULLY_CONNECTED, HARD_SWISH, MAXIMUM, MEAN, MINIMUM, MUL, PACK, RESHAPE, SHAPE, SOFTMAX, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: BroadcastTo.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/Users/z004njq/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/z004njq/Library/Python/3.7/lib/python/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/z004njq/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, CONV_2D, DEPTHWISE_CONV_2D, DIV, FULLY_CONNECTED, HARD_SWISH, MAXIMUM, MEAN, MINIMUM, MUL, PACK, RESHAPE, SHAPE, SOFTMAX, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: BroadcastTo.

I tried using --enable_select_tf_ops, but it did not work. Could you please guide me how to solve this issue? It's little time-sensitive.

**Comment by amahendrakar** [comment] 2020-07-26 09:44
@dipendra009,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by mihaimaruseac** [comment] 2020-07-27 16:01
You will need a custom implementation for `BroadcastTo` or replace it with operators which exist in the TFLite dialect

```
Here is a list of operators for which you will need custom implementations: BroadcastTo.
```

Since this is not an error in the TF code, closing the issue.

**Closed by mihaimaruseac** 2020-07-27 16:01 UTC
Labels: comp:lite, stat:awaiting response, type:others
