### ISSUE TITLE
TensorFlow produces arbitrary results without error when using large amounts of GPU memory

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#4968] opened 2016-10-14 15:01 UTC
### Environment info

Operating System: Docker container based on `nvidia/cuda:7.5-cudnn5-devel` running on CentOS

If installed from binary pip package, provide:
1. A link to the pip package you installed: `pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp34-cp34m-linux_x86_64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
0.11.0rc0
```
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

``` python
import numpy as np
import tensorflow as tf

mb = 100
sz = int(mb * 1e6 / 4)
total_gb = 11
n = int(total_gb / mb * 1000)
x = np.array(np.random.randn(sz), dtype=np.float32)

with tf.Graph().as_default():
    place = tf.placeholder(tf.float32, shape=[sz])
    with tf.device('/gpu:0'):
        x_gpu = [tf.Variable(place, dtype=tf.float32) for i in range(n)]
    init = tf.initialize_all_variables()
    with tf.Session() as sess:
        sess.run(init, feed_dict={place: x})
        # I know it's not optimal, but to make it more comparable to the Theano code below
        x_out = [sess.run(v) for v in x_gpu]

delta = [np.sum(np.abs(xi - x)) for xi in x_out]
print(delta)
```

Executed using `python3 memcheck_tensorflow.py`
#### Expected output:

```
some tensorflow output ...

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
#### Actual output:

```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:81:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:81:00.0)
[28209880.0, 28208760.0, 28208760.0, 28209880.0, 28206538.0, 28208760.0, 28212806.0, 28209880.0, 28209880.0, 28208760.0, 28211926.0, 28209880.0, 28208760.0, 28209880.0, 28209880.0, 28206538.0, 28206538.0, 28209880.0, 28208760.0, 28212806.0, 28208760.0, 28209880.0, 28209880.0, 28209880.0, 28207726.0, 28208760.0, 28206538.0, 28209880.0, 28206538.0, 28210806.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209880.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28209472.0, 28206602.0, 28209472.0, 28209472.0, 28208760.0, 28208760.0, 28209880.0, 28208760.0, 28207726.0, 28209880.0, 28208760.0, 28208760.0, 28209880.0, 28209880.0, 28206602.0, 28209880.0, 28209880.0, 28208760.0, 28209880.0, 28209880.0, 28209880.0, 28208760.0, 28206538.0, 28209880.0, 28209880.0, 28208760.0, 28208760.0, 28206602.0, 28207726.0, 28209880.0, 28207726.0, 28209880.0, 28209880.0, 28209880.0, 28211926.0, 28209880.0, 28208760.0, 28209880.0, 28208760.0, 28208760.0, 28209880.0, 28209880.0, 28209880.0, 28209880.0, 28209880.0, 28209880.0, 28206538.0, 28209880.0, 28209880.0, 28209880.0, 28209880.0, 28210806.0, 28209880.0, 28208760.0, 28208760.0, 28209880.0, 28206538.0, 28208760.0, 28209880.0, 28206602.0, 28208760.0, 28208760.0]
```
### What other attempted solutions have you tried?

I've verified that this problem exists on at least one other GPU (I've seen it on Nvidia GPUs K40m and K80).

I've run similar code in Theano without any problems (same GPU, same Docker container):

``` python
import numpy as np
import theano

mb = 100
sz = int(mb * 1e6 / 4)
total_gb = 11
n = int(total_gb / mb * 1000)
x = np.array(np.random.randn(sz), dtype=np.float32)

x_gpu = [theano.shared(x) for i in range(n)]
x_out = [v.get_value() for v in x_gpu]

delta = [np.sum(np.abs(xi - x)) for xi in x_out]
print(delta)
```

Executed using `THEANO_FLAGS=device=gpu,floatX=float32 python3 memcheck_theano.py`
#### Output

```
Using gpu device 0: Tesla K40m (CNMeM is disabled, cuDNN 5103)
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

**Comment by asimshankar** [comment] 2016-10-21 04:40
@jonasrauber : Thanks for the report. Unfortunately (or perhaps fortunately :), I've been unable to reproduce this, albeit I tried this on a K40c, not a K40m. 

Two requests of you:
- Take a look at what I tried below and let me know if (a) the same commands yield different output  for you, and/or (b) If you spot some differences between what I did and what you're doing 
- Does the output consist of all zeros if you use less than 11GB of memory?

Here's what I did:
```
nvidia-docker run -it nvidia/cuda:7.5-cudnn5-devel
apt-get update
apt-get install -y python3 python3-pip
pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp34-cp34m-linux_x86_64.whl
# Created memcheck.py from your code snippet above
python3 memcheck.py
```

And this is the output:
```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:05:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:05:00.0)
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

**Comment by jonasrauber** [comment] 2016-10-21 13:52
Unfortunately, I see this output:

```
root@ce0a1cd826d9:/tmp# python3 memcheck.py 
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:81:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:81:00.0)
[28218290.0, 28205566.0, 28205566.0, 28218290.0, 28220230.0, 28218290.0, 28205376.0, 28205566.0, 28218290.0, 28207506.0, 28221894.0, 28221212.0, 28219170.0, 28218290.0, 28218290.0, 28220834.0, 28203484.0, 28207506.0, 28207506.0, 28205566.0, 28221212.0, 28217608.0, 28217608.0, 28204444.0, 28204444.0, 28204184.0, 1418863.9, 28204444.0, 28219348.0, 28222026.0, 28221894.0, 2839692.5, 28220834.0, 0.0, 28218290.0, 28220834.0, 28203254.0, 28218290.0, 28220834.0, 28221894.0, 28204444.0, 28205570.0, 28222026.0, 28221894.0, 28220508.0, 28220834.0, 28204444.0, 28220834.0, 28220834.0, 28221894.0, 28204444.0, 28203254.0, 28220834.0, 28221894.0, 28221894.0, 28220834.0, 0.0, 28219480.0, 28220508.0, 28204444.0, 0.0, 28205376.0, 28220834.0, 28205376.0, 28205376.0, 2839692.5, 0.0, 28204444.0, 28221894.0, 28203254.0, 4258556.5, 28205376.0, 28221894.0, 28222026.0, 0.0, 2839692.5, 4258556.5, 2839692.5, 28219480.0, 28204184.0, 28204444.0, 28220834.0, 28219348.0, 28221894.0, 28220834.0, 28220834.0, 28221894.0, 28220834.0, 0.0, 28221894.0, 28204184.0, 28221894.0, 3286809.0, 0.0, 26801648.0, 28220834.0, 2839692.5, 28221894.0, 0.0, 0.0, 28220834.0, 28221894.0, 28221894.0, 28220834.0, 25380614.0, 5679584.0, 0.0, 28221894.0, 4258556.5, 0.0]
```

At least on one GPU, I get this starting at **5 GB**.

When I limit the `per_process_gpu_memory_fraction` to 0.7 (to 8 GB), it works fine until 8 GB (I get zeros!) and for 9 GB and higher, it's out of memory.

```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
config = tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False)
with tf.Session(config=config) as sess:
```

In principle, I would think it's a hardware or driver issue, but then I should be able to reproduce it with another framework.

**Comment by gunan** [comment] 2016-10-24 17:34
@zheng-xq Any ideas?

**Comment by jonasrauber** [comment] 2016-10-24 18:29
Still not sure, but it looks more and more like a hardware issue on some but not all of our GPUs. But we are still investigating, I'll keep you posted. In the meantime, I would be very happy to hear from anyone being able to reproduce this or encountering other related problems. We originally spotted the problem when running VGG-19 evaluations and sometimes obtaining obviously wrong accuracies but no errors.

**Comment by yifeif** [comment] 2016-10-24 20:54
Not sure what is the root cause of this issue, but wondering if upgrading to CUDA 8.0 and using the latest release 0.11.0rc1(w/ CUDA support) would help?

**Comment by jonasrauber** [comment] 2016-10-28 12:17
I have some news to share. After upgrading the nvidia drivers from 352.39 to 367.48, I was not able to reproduce this problem anymore (neither with cuda7.5 nor cuda8.0). When I have some more time, I'll run some additional experiments but until then I consider the upgrade to 367.48 as a solution to this problem and propose to close this issue.

**Comment by gunan** [comment] 2016-10-28 18:55
Thanks for the update.
Old drivers have some known GPU memory issues, so driver update solving this makes sense.
I will unblock the release on this issue now, but please keep us posted.

**Comment by asimshankar** [comment] 2016-10-31 20:02
@jonasrauber : I'll close this out for now. Do re-open if you start suspecting something other than the driver-version/CUDA-library compatibility. Thanks!

**Closed by asimshankar** 2016-10-31 20:02 UTC
Labels: awaiting response

**Comment by eigen2017** [comment] 2018-05-11 10:33
same issue on NVIDIA-SMI 381.22




➜  data_in_446Hz_and_uV nvidia-smi
Fri May 11 18:32:08 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 0000:02:00.0     Off |                  N/A |
| 49%   82C    P2   262W / 250W |  10650MiB / 11172MiB |     85%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 0000:03:00.0     Off |                  N/A |
| 23%   38C    P8    17W / 250W |   8166MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      8197    C   python                                        3995MiB |
|    0     19069    C   python                                        6611MiB |
|    1      8197    C   python                                         151MiB |
|    1     19069    C   python                                        7971MiB |
+-----------------------------------------------------------------------------+
➜  data_in_446Hz_and_uV
