### ISSUE TITLE
delete pycharm project issue(Pycharm project deletion problem due to cache deletion)

### ISSUE THREAD

**Issue by spirid0n** [tensorflow/tensorflow#46279] opened 2021-01-08 07:47 UTC
The project was deleted while using pycharm for tensorflow developer certification. It seems that the pycharm project was deleted while deleting the Mac OS cache and junk. Developers preparing for certification should be aware of this issue.

**Comment by ravikyram** [comment] 2021-01-08 17:19
@spirid0n 

Thanks for filing the issue and share the information.

I am closing the issue since it is not a bug or feature request related to Tensorflow. Thanks!

**Comment by spirid0n** [comment] 2021-01-08 18:01
Do you know why I am writing here? I have ignored my mail more than 10 times. I couldn't stand it, so I left a post here. I'll keep it elsewhere. I will close that issue

**Closed** 2021-01-08 18:02 UTC
Labels: stat:awaiting response, type:others

**Comment by spirid0n** [comment] 2021-01-08 18:03
Don't ignore it.

**Comment by ymodak** [comment] 2021-01-13 21:42
cc @JosBecker
