### ISSUE TITLE
Android Demo build error

### ISSUE THREAD

**Issue by ToxidoLiu** [tensorflow/tensorflow#4832] opened 2016-10-07 20:21 UTC
The error I saw is as follows, don't quit know how this permission error occurs
```
ERROR: /home/toxido/.cache/bazel/_bazel_root/e7444205eb7a78f2fb0f6da55e24d78b/external/androidsdk/BUILD:5:1: Executing genrule @androidsdk//:aapt_runner failed: linux-sandbox failed: error executing command /home/toxido/.cache/bazel/_bazel_root/e7444205eb7a78f2fb0f6da55e24d78b/execroot/tensorflow/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
src/main/tools/linux-sandbox-pid1.cc:233: "mount(/, /home/toxido/.cache/bazel/_bazel_root/e7444205eb7a78f2fb0f6da55e24d78b/bazel-sandbox/28d014be-3643-4295-b588-2ed7789511a4-1/tmp, NULL, MS_BIND | MS_REC, NULL)": Permission denied
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by tatatodd** [comment] 2016-10-07 21:49
@ToxidoLiu Please fill out the following information, which was the default template when you clicked on the green "New issue" button.  Also include the exact command-line that you ran, that causes the error.

---

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)


### What other attempted solutions have you tried?


### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by ToxidoLiu** [comment] 2016-10-08 14:11
@tatatodd
OS & Environment : Ubuntu 16.04 LTS , Android Studio v2.2
tensorflow version : 0.8.0
bazel version: 0.3.2
Android SDK version: 24.0.3
NDK version: 13.0.3315539

The above error occured when I tried to do
'$ bazel build //tensorflow/examples/android:tensorflow_demo'
as instructed here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

Thanks!

**Comment by tatatodd** [comment] 2016-10-08 18:52
@ToxidoLiu Please try the latest version of TensorFlow 0.11, since 0.8 is quite old at this point:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

**Comment by andrewharp** [comment] 2016-10-08 22:21
@toxidoliu Have you checked that relevant binaries all have the execute bit set? If you're still having issues after you upgrade TF can you paste the error log running with --verbose_failures?

**Comment by aselle** [comment] 2016-10-17 17:15
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.

**Closed by aselle** 2016-10-17 17:15 UTC
Labels: awaiting response
