### ISSUE TITLE
tf.image.resize_images differs from PIL/scipy.misc.imresize

### ISSUE THREAD

**Issue by gongbudaizhe** [tensorflow/tensorflow#12632] opened 2017-08-27 18:24 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"                                                              
VERSION_ID="7"                                                                  
CENTOS_MANTISBT_PROJECT_VERSION="7"                                             
REDHAT_SUPPORT_PRODUCT_VERSION="7"     

- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
tf.VERSION = 1.2.1
tf.GIT_VERSION = v1.2.1-0-gb4957ff
tf.COMPILER_VERSION = v1.2.1-0-gb4957ff
Sanity check: array([1], dtype=int32)

- **Python version**: 
2.7

- **Bazel version (if compiling from source)**:
0.4.5

- **CUDA/cuDNN version**:
CUDA8.0/CUDNN6.0

- **GPU model and memory**:
GeForce GTX 1080  8113MiB

- **Exact command to reproduce**:
See Source code

### Describe the problem
As the title states, tf.image.resize_images returns different values compared to imresize in scipy or PIL. This is important because we expect the same behaviour for migrating code originally written using scipy.misc.imresize or PIL.

### Source code / logs
```python
import numpy as np
import tensorflow as tf
from scipy.misc import imresize

image = (255 * np.random.rand(127, 127, 3)).astype(np.uint8)
resize_size = [255, 255]

image_resized = tf.image.resize_images(image, resize_size, method=tf.image.ResizeMethod.BILINEAR)
with tf.Session() as sess:
    image_resized_tf = sess.run(image_resized)

image_resized_np = imresize(image, resize_size, interp='bilinear')

diff = image_resized_np.astype(np.float32) - image_resized_tf.astype(np.float32)
print('resized image diff: {}'.format(np.mean(np.abs(diff))))
# resized image diff: 31.6155033112
```

**Comment by ppwwyyxx** [comment] 2017-08-28 03:27
https://github.com/tensorflow/tensorflow/issues/6720#issuecomment-298112231

**Comment by ali01** [comment] 2017-08-28 04:47
This seems to be a duplicate of #6720. Closing here.

**Closed by ali01** 2017-08-28 04:47 UTC
