### ISSUE TITLE
Can we auto-convert a tensor into a numpy value when necessary in computing graph executing mode(&tf.function mode)?

### ISSUE THREAD

**Issue by clockzhong** [tensorflow/tensorflow#38887] opened 2020-04-25 12:35 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (2.1): 2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
```
  def testTensorAndNumpy():
    npArray=np.random.uniform(0, 10000, size=200)
    #npArray=tf.random.uniform((200,), 0, 10000)
    @tf.function
    def myFunc(tensorValue):
      return(npArray[tensorValue])

    #tensorValue=3
    tensorValue=tf.convert_to_tensor(3)
    print(myFunc(tensorValue))
    print(npArray[tensorValue])

```
The above code works fine if we comment the @tf.function, but when we use @tf.function, it'll reporting the following errors:
```

....
    NotImplementedError: Cannot convert a symbolic Tensor (tensorValue:0) to a numpy array.
....
```
The root cause should be that the tensorflow's computing graph executing mode couldn't auto-convert the tensor to numpy value, but when in eager mode, this conversion could happen correctly and automatically. It seems not only my test case could trigger this bug, many other bugs report also relate to this root cause.

**Will this change the current api? How?**
No, it seems no need change the API spec, but we need change the implementation for tensorflow's tf.function.

**Who will benefit with this feature?**
Many engineers, it seems not only my test codes could trigger this error, many other tensorflow users also found similar issue. I searched "NotImplementedError: Cannot convert a symbolic Tensor ", about 10 issues exists, I guess the root cause for most them should be same as this test failure's root cause. 
https://github.com/tensorflow/tensorflow/issues?q=NotImplementedError%3A+Cannot+convert+a+symbolic+Tensor

**Any Other info.**
We could change the npArray to a tensor, and then we could use tensor as the index for another tensor, this works fine(by disabling the first line and enable the second line). But because in my usage scenario, I need use numpy data array as the data source, and use tensor variable to access different part of this numpy data array. Because this combination could help me save lots of GPU memory, the GPU memory is much more expensive than CPU memory, and all tensors malloc need consume GPU memory. So I consider this issue as a new feature request instead of a bug report. 
After implmenting this feature, engineers could feel more nature when switching between tensorflow's eager mode and graph mode, and most of those old connected bugs should also be fixed automatically.

**Comment by ravikyram** [comment] 2020-04-27 07:34
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by clockzhong** [comment] 2020-04-29 03:10
@ravikyram yes, I've use case to require this feature. The test codes I've provided could show that our current version tensorflow couldn't support this feature:

```
  def testTensorAndNumpy():
    npArray=np.random.uniform(0, 10000, size=200)
    #npArray=tf.random.uniform((200,), 0, 10000)
    @tf.function
    def myFunc(tensorValue):
      return(npArray[tensorValue])

    #tensorValue=3
    tensorValue=tf.convert_to_tensor(3)
    print(myFunc(tensorValue))
    print(npArray[tensorValue])
```

But I've no solution to implement this feature yet, so I couldn't submit a PR(pull request, right?).
My usage scenario is using a huge numpy data array as my tensorflow model's database, my tf model need freequently access data randomly from it, and the numpy data array is very huge, it couldn't be loaded into GPU because GPU's memory space is always much smaller than CPU's memroy space.

And I've found a workaround to this limitation for myself already. I could use tf.convert_to_tensor() to generate a tensor which will be always stored in CPU's memory, so the above test code could be changed to:
```
....
npArray=np.random.uniform(0, 10000, size=200)
tfArray=tf.convert_to_tensor(npArray)
print(tfArray.device)
# the following codes will handle tfArray
...... 

```

You could freely close this issue or use it to trace this new feature request: using tensor data array as slice index to access numpy data array in computing graph mode and tf.function mode (eager mode already suport this feature).

Thanks!

**Comment by mdanatg** [comment] 2020-05-03 12:40
Fundamentally, one cannot convert a graph tensor to numpy array because the graph does not execute in Python - so there is no NumPy at graph execution. The only way to achieve this mix is by using tf.py_function, which is ok assuming you don't want a portable model, but which will negatively affect the performance of your graph. py_function has a number of other shortcomings as well, which is the reason why it's not inserted by default into the graph.

That said, I believe the correct conversion here would be for the NumPy array to be auto-converted to Tensor. That actually happens most of the time:

 * `tesor_array[numpy_index]` converts `numpy_index` to tensor
 * `tensor_x + numpy_y` converts `numpy_y` to tensor

Therefore, the following should also be true:

 * `numpy_array[tensor_index]` converts `numpy_array` to tensor

So from that perspective, we have a bug.

So this FR could generalize as: "any operation involving mixes of numpy and tensors should consistently upcast all non-tensor values to tensor". Unfortunately, that behavior is impossible to obtain in eager mode, which is what will probably make it infeasible.

**Comment by clockzhong** [comment] 2020-05-03 13:07
@mdanatg Thanks for your clear explanation.
"one cannot convert a graph tensor to numpy array because the graph does not execute in Python - so there is no NumPy at graph execution. "

Yes, agree. And your explanation remind me to change the test codes to the following:
```
  def testTensorAndNumpy():
    npArray=np.random.uniform(0, 10000, size=200)
    @tf.function
    def myFunc(tensorValue, inputNPArray):
      return(inputNPArray[tensorValue])

    #tensorValue=3
    tensorValue=tf.convert_to_tensor(3)
    print(myFunc(tensorValue, npArray))
    print(npArray[tensorValue])

```

Because I've put the numpy array into the tf.function's parameter, so the tensorflow could auto-convert the numpy array into tensor. then the test could pass. But in my original test, the npArray is a bigger scope variale, the tf.function current mechanism couldn't catch the opportunity to do the auto-coversion from numpy to tensor. If we put it into function's parameter, the numpy-tensor conversion could happen by current tf.function mechanism.

**Comment by clockzhong** [comment] 2020-05-03 13:15
"So this FR could generalize as: "any operation involving mixes of numpy and tensors should consistently upcast all non-tensor values to tensor". Unfortunately, that behavior is impossible to obtain in eager mode, which is what will probably make it infeasible."
Yes, it's infeasible. but I've confirmed that in the eager mode:
`numpy_array[tensor_index]` 
will auto-convert the tensor_index into numpy value, and it works fine so far. So how to define the data type auto-conversion princple in tensorflow is decided by your team, I just report what I've found.

**Comment by mdanatg** [comment] 2020-05-03 16:27
@clockzhong Thank you, I agree that this is an important observation that we should document.

The difference between function arguments and values captured through the function's closure is an important one too, and is related to another known limitation in which the function is not retraced if any of the variable it closes over change.

I think both of these aspects should be mentioned in the docstring of tf.function.

**Comment by saikumarchalla** [comment] 2020-05-20 10:29
@clockzhong  Closing this issue as it is the Intended Behavior.Please feel free to re-open the issue if you have any concerns.Thanks!

**Closed by saikumarchalla** 2020-05-20 10:29 UTC
Labels: comp:autograph, comp:core, type:feature

**Comment by clockzhong** [comment] 2020-05-20 10:41
@saikumarchalla  Ok, got it, thanks!
