### ISSUE TITLE
export step of Experiment fails in python 3.5 (likely due to string-type mismatch)

### ISSUE THREAD

**Issue by yufengg** [tensorflow/tensorflow#10399] opened 2017-06-02 15:00 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yep
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX
- **TensorFlow installed from (source or binary)**: binary 1.1.0
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**:
git clone https://github.com/amygdala/tensorflow-workshop
python tensorflow-workshop/workshop_sections/wide_n_deep/widendeep/model.py

### Describe the problem

When running Experiment stuff, it works fine in 2.7 but breaks in 3.5. From what I can tell, it's happening in gc.py, which is being called _after_ the model has been exported and everything is done. 

My best guess from looking at similar bugs on SO is that there's a mismatch somewhere between 'byte' strings and python strings, possibly because the base folder path of the export is generated (e.g. /exports/Servo/123456789/saved_model.py), so the somehow the concat isn't happy with this.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

File "/Users/yufengg/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/utils/gc.py", line 202, in get_paths
    p = parser(Path(os.path.join(base_dir, r), None))
  File "/Users/yufengg/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/yufengg/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

**Comment by asimshankar** [comment] 2017-06-02 17:41
Thanks for the report @yufengg . Can you include the full stracktrace and ideally a reproducible test case?

**Comment by martin-gorner** [comment] 2017-07-04 12:32
Same problem here. All you need in your code is to include an export strategy and the checkpoints garbage collector will raise an exception:

saved_model_export_utils.make_export_strategy(
            model.serving_input_fn,
            default_output_alternative_key=None,
            exports_to_keep=1

**Comment by mino98** [comment] 2017-07-11 09:30
Same here, exactly the same code that @martin-gorner pointed out is causing the crash.

**Comment by xiejw** [comment] 2017-07-20 16:30
Does https://github.com/tensorflow/tensorflow/pull/9719/files fix this?

**Comment by pusj** [comment] 2017-07-25 20:46
@xiejw ,

Do you know which ver. of TF is that https://github.com/tensorflow/tensorflow/pull/9719/files is released in? Or which ver is this going to be released in?

**Comment by xiejw** [comment] 2017-07-25 20:56
I did not see r1.2 branch has this change. So, it should go to v1.3

r1.2
https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/learn/python/learn/utils/gc.py

**Comment by pusj** [comment] 2017-08-02 18:20
@xiejw ,

Correct, this is now workin in TF 1.3...however, I can only get the CPU ver of TF running, the GPU ver of 1.3 throws the pywrap error, although the GPU ver for TF 1.2 works like a charm....strange, that's what is it...

**Comment by tensorflowbutler** [comment] 2017-11-09 20:27
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Closed** 2017-11-09 20:27 UTC
Labels: stat:awaiting response
