### ISSUE TITLE
tensorboard doesnt display y-axis correctly.

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#9056] opened 2017-04-07 21:20 UTC
![image](https://cloud.githubusercontent.com/assets/11971499/24820310/61102b8a-1bb6-11e7-8128-36ac5ab99bf4.png)

This plot makes it look like AUC is greater than 1.0 when it is not.

c:\Python35\Scripts>pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.1.0rc1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\python35\lib\site-packages
Requires: numpy, wheel, protobuf, six, werkzeug

**Comment by asimshankar** [comment] 2017-04-07 22:19
@isaacgerg : Can you provide any more detail that helps reproduce the problem? For example, a pointer to the logdir you use?

CCing @dandelionmane just in case he has thoughts on this.

**Comment by isaacgerg** [comment] 2017-04-07 23:32
@asimshankar I cannot send you any more detail unfortunately other than the values that make up the curve just from the screenshots as the data is proprietary.

**Comment by asimshankar** [comment] 2017-04-08 00:11
@isaacgerg : Sure, I just wanted to make sure that the AUC scalar being plotted is really less than 1.0 :)

**Comment by isaacgerg** [comment] 2017-04-08 00:35
The hover text is for that point that's plotted wrong.

**Comment by asimshankar** [comment] 2017-04-08 00:55
Ah, thanks for pointing that out. @dandelionmane?

**Comment by isaacgerg** [comment] 2017-04-08 01:31
I wonder if its a render issue and the 1.00 should be moved up to the next y tick.

**Comment by wih1** [comment] 2017-04-11 09:20
This looks like a rounding/precision error. The labels for 0.999 and 0.998 appear twice, so the top most label should probably also be 1.00 and so your value is between 1.00 and 1.00 :), which is ok for 0.9999 when the "real" labels are 0.995 rounded to 1.00 and 1.0 rounded to 1.00.

So everything is displayed correctly but there are not enough decimal places for the labels to see it.

**Comment by isaacgerg** [comment] 2017-04-11 12:49
> So everything is displayed correctly

I understanding the rounding error but the graph is still wrong.  There is no way one could put a plot like that in a journal.

**Comment by wih1** [comment] 2017-04-11 13:01
I agree with you. The graph is not good and I wouldn't show such a graph to anyone, this only creates confusion and questions.

What I wanted to say, there is no error in the graph (so there is nothing to fix there) but the axis labeling of the graph is confusing (so the selection of the y-axis range and decimal places should be changed).

**Comment by isaacgerg** [comment] 2017-04-11 13:05
Makes sense -- thanks!

**Comment by dandelionmane** [comment] 2017-05-04 21:13
Please provide a dataset (or code snippet) that reproduces this and we'll dig into it. @isaacgerg

**Comment by isaacgerg** [comment] 2017-05-04 21:44
@dandelionmane  I've moved on from this issue - sorry but its been over 3 weeks.  I not longer get the problem based on my new training scheme, the number have a much larger derivative.  Feel free to close if you'd like.

**Comment by wchargin** [comment] 2017-06-16 18:41
If we get a repro script—even with constant data—I'd like to look into this. Until then, closing.

Please feel free to re-open on our new repository at https://github.com/tensorflow/tensorboard.

**Closed by wchargin** 2017-06-16 18:41 UTC
Labels: stat:awaiting tensorflower, tensorboard, type:bug/performance
