### ISSUE TITLE
Triplet loss semi hard function does not work

### ISSUE THREAD

**Issue by zhasulan** [tensorflow/tensorflow#24833] opened 2019-01-10 16:43 UTC
The triplet loss semi hard function does not work in the line where have an assertion which checking variable dimension

**Comment by jvishnuvardhan** [comment] 2019-01-15 22:58
@zhasulan Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? 

Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by thebeancounter** [comment] 2019-01-28 11:48
You can make it work by removing the dimension assert in the function, Another issue is that this function often returns nan values that are messing with the training, I have created another function that works with tensorflow eager execution, it still needs optimization, I will create a pull request.

**Comment by jvishnuvardhan** [comment] 2019-02-05 23:59
@thebeancounter Thanks for the workaround and also for working on the solution. I will close this issue. Please feel free to open If you see the issue again. Thanks!

**Closed by jvishnuvardhan** 2019-02-05 23:59 UTC
Labels: stat:awaiting response, type:bug/performance
