### ISSUE TITLE
error when building from source

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#1413] opened 2016-03-07 07:57 UTC
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Warning: ignoring LD_PRELOAD in environment.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:87:1: no such package '@grpc//': Error cloning repository: https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack caused by https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack caused by https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_channel'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 342.460s

**Comment by girving** [comment] 2016-03-07 17:05
@mrry: Looks like a distributed-related issue.

**Comment by mrry** [comment] 2016-03-07 17:07
Are you able to run `git clone https://boringssl.googlesource.com/boringssl` locally?

**Comment by vrv** [comment] 2016-03-07 21:24
#1387 might be relevant...

**Comment by Vesnica** [comment] 2016-03-08 00:53
I can run git clone https://boringssl.googlesource.com/boringssl locally, but in bazel that didn't work.

Maybe bazel didn't honor the proxy env vars when download the deps of deps. (tensorflow -> grpc -> boringssl)

**Comment by fayeshine** [comment] 2016-03-08 01:57
@mrry @Vesnica I can only run it with proxy since I'm behind the firewall. However, when I run bazel with proxy, it seems cannot work

**Comment by mrry** [comment] 2016-03-08 05:07
Can you please try upgrading to the latest HEAD of Bazel? It looks like a fix was added for proxy support in https://github.com/bazelbuild/bazel/commit/d4c00d42b7ac3939f7041ba3bcb920088857adbd.

**Comment by Vesnica** [comment] 2016-03-09 01:03
Latest bazel didn't fix this problem:

```
ERROR: /home/vesnica/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:158:1: no such package '@grpc//': Error cloning repository: https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack caused by https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack caused by https://boringssl.googlesource.com/boringssl: cannot open git-upload-pack and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_remote_master'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 161.436s
```

All proxy settings is correct, and there is no issue if I simply run:
```
git clone --depth 1 --recurse-submodules https://github.com/grpc/grpc.git
```

```
Cloning into 'grpc'...
remote: Counting objects: 3401, done.
remote: Compressing objects: 100% (2631/2631), done.
remote: Total 3401 (delta 1667), reused 1305 (delta 596), pack-reused 0
Receiving objects: 100% (3401/3401), 3.65 MiB | 81.00 KiB/s, done.
Resolving deltas: 100% (1667/1667), done.
Checking connectivity... done.
Submodule 'third_party/boringssl' (https://boringssl.googlesource.com/boringssl) registered for path 'third_party/boringssl'
Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'third_party/nanopb'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into 'third_party/boringssl'...
remote: Sending approximately 23.14 MiB ...
remote: Counting objects: 3021, done
remote: Finding sources: 100% (424/424)
remote: Total 23388 (delta 14683), reused 23347 (delta 14683)
Receiving objects: 100% (23388/23388), 22.97 MiB | 327.00 KiB/s, done.
Resolving deltas: 100% (14683/14683), done.
Checking connectivity... done.
Submodule path 'third_party/boringssl': checked out '9f897b25800d2f54f5c442ef01a60721aeca6d87'
```

**Comment by myme5261314** [comment] 2016-03-10 03:43
@Vesnica I'd like to know whether just set http.proxy and https.proxy for git is enough to fetch google's boringssl repo?

I set my proxy to git via:
```shell
git config --global http.proxy http://localhost:127.0.0.1:8118
git config --global https.proxy http://localhost:127.0.0.1:8118
```
And then run the command.
```shell
GIT_TRACE_PACKET=1 GIT_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://boringssl.googlesource.com/boringssl
```
And the clone failed, the output is like below:
```
trace: built-in: git 'clone' 'https://boringssl.googlesource.com/boringssl'
Cloning 'boringssl'...
trace: run_command: 'git-remote-https' 'origin' 'https://boringssl.googlesource.com/boringssl'
* Couldn't find host boringssl.googlesource.com in the .netrc file; using defaults
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8118 (#0)
* Establish HTTP proxy tunnel to boringssl.googlesource.com:443
> CONNECT boringssl.googlesource.com:443 HTTP/1.1
Host: boringssl.googlesource.com:443
User-Agent: git/1.9.1
Proxy-Connection: Keep-Alive
Pragma: no-cache

< HTTP/1.1 503 Connect failed
< Content-Length: 7690
< Content-Type: text/html
< Cache-Control: no-cache
< Date: Thu, 10 Mar 2016 03:33:42 GMT
< Last-Modified: Wed, 08 Jun 1955 12:00:00 GMT
< Expires: Sat, 17 Jun 2000 12:00:00 GMT
< Pragma: no-cache
< Connection: close
< 
* Received HTTP code 503 from proxy after CONNECT
* Connection #0 to host 127.0.0.1 left intact
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Received HTTP code 503 from proxy after CONNECT
```

PS: I've tried to set HTTP_PROXY and HTTPS_PROXY environment variable for latest bazel, but it doesn't work.
```
tensorflow/WORKSPACE:39:1: no such package '@grpc//': Error cloning repository: https://boringssl.googlesource.com/boringssl: 503 Connect failed caused by https://boringssl.googlesource.com/boringssl: 503 Connect failed and referenced by '//external:grpc_cpp_plugin'.
ERROR: Loading failed; build aborted.
```
So they all give me `503` as failed code. Is that the problem of my proxy? I use shadowsocks locally with Privoxy to redirect the http 8118 port to shadowsocks. I can confirm that the http proxy for my daily use is ok.

**Comment by Vesnica** [comment] 2016-03-10 05:55
@myme5261314 Make sure your ~/.gitconfig have this section:
```
[http]
        proxy = PROXY_IP:PROXY_PORT
```
This should be enough for all https git url.

boringssl in bazel is another issue, which I believe not related to your proxy settings(git or system).

**Comment by myme5261314** [comment] 2016-03-10 06:38
I find my issue and have it fixed. My proxy has a configuration problem. And I fixed it. Now I can clone boringssl locally through git. But failed for boringssl in bazel. It's weird that they said the proxy improve commits had been merged but problem still exists about proxy in HEAD of bazel.

**Comment by fayeshine** [comment] 2016-03-22 00:06
I've noticed grpc about this problem, and they've fixed it: https://github.com/grpc/grpc/issues/5853
Should I submit a PR to update the grpc commit version in tensorflow to include this fix ?

**Comment by fayeshine** [comment] 2016-03-22 03:33
I tried to use this new version of grpc to build tensorflow, Now I can clone it behind the wall.
However there's another problem:

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/wenjian/.cache/bazel/_bazel_wenjian/d25f05b3e081482e9605a49c384a6c89/external/grpc/BUILD:852:1: Label '@grpc//:src/cpp/common/core_codegen.h' is duplicated in the 'srcs' attribute of rule 'grpc++'.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/workspace.bzl:84:3: Target '@grpc//:grpc_cpp_plugin' contains an error and its package is in error and referenced by '//external:grpc_cpp_plugin'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.176s

**Comment by zszhong** [comment] 2016-03-23 23:37
Hi, I also have this problem. 

I'm trying to use `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` to build the package from source. And I met an error on `boringssl`. The error message is as follows:
![1](https://cloud.githubusercontent.com/assets/8293993/14003987/dc05a9b4-f191-11e5-88aa-1022013d087f.png)
After blocking with several minitus... the error is shown:
![2](https://cloud.githubusercontent.com/assets/8293993/14003988/dc067cb8-f191-11e5-8171-698bb03f4e29.png)
After checking the `grpc` repository [https://github.com/grpc/grpc.git], I found the `boringssl` submodule has been updated with the new mirror in [https://github.com/google/boringssl.git]. 
After cloning the `grpc` repository into my local disk, I try to find where the `boringssl` is needed. 
![3](https://cloud.githubusercontent.com/assets/8293993/14004056/4caa29b0-f192-11e5-9fb2-9e7324464bcc.png)
It seems nowhere for [https://boringssl.googlesource.com/boringssl] is needed. 
So,could you please change the dependency of `grpc` for [https://boringssl.googlesource.com/boringssl] into [https://github.com/google/boringssl.git], completely?

**Comment by shengjt** [comment] 2016-03-24 02:57
@zszhong https://github.com/tensorflow/tensorflow/issues/1387 this fix works for me

**Comment by shengjt** [comment] 2016-03-24 02:59
@fayeshine have you successfully completed the build for distributed tensorflow? I hit different compile errors for each build after fix the boringssl issue.

**Comment by zszhong** [comment] 2016-03-24 04:12
@shengjt Thank you very much! Problem solved!

**Comment by shengjt** [comment] 2016-03-24 05:34
@zszhong have you passed the rest build process?

**Comment by zszhong** [comment] 2016-03-24 06:17
@shengjt Yes, I have modified the `tensorflow/workspace.bzl` as follows:

        native.git_repository(
          name = "grpc",
          # commit = "73979f4",
          commit = "403cd6c",
          init_submodules = True,
          # remote = "https://github.com/grpc/grpc.git",
          remote = "https://github.com/melody-rain/grpc.git",
         )

Then, use `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` to build the pip package, and install it into python packages. Then, the `tensorflow/models/image/mnist/convolutional.py` can be run correctly.

**Comment by zszhong** [comment] 2016-03-24 11:59
Another possible solution is:

        native.git_repository(
            name = "grpc", 
            commit = "3d62fc6",
            init_submodules = True,
            remote = "https://github.com/grpc/grpc.git", 
         )

Why `3d62fc6`? Because after this commit, the `boringssl` from the original googlesouce was changed into `https://github.com/google/boringssl.git`. See `https://github.com/grpc/grpc/commit/3d62fc68349a5ef31b9c2b0250818343bf9cca68#diff-8903239df476d7401cf9e76af0252622`.

Why not the latest commit? I have tried to set the value of `commit` as the latest commit, but it seems have some problems. 

I think the error in the main post is from the commit `73979f4`. In commit `73979f4`, the submodule of `boringssl` was still from googlesource. 

Maybe anybody could try this solution and submit a pull request into the master branch.

**Comment by shengjt** [comment] 2016-03-25 01:43
@zszhong it seems we build different packages, I am trying to run: bazel build -c opt --verbose_failures //tensorflow/core/distributed_runtime/rpc:grpc_tensorflow_server, the distributed tensorflow, but failed.

**Comment by myme5261314** [comment] 2016-03-25 01:52
There's no need to be so complicated to compile tensorflow via bazel.
I've just compiled it successfully.
```
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 591.058s, Critical Path: 552.93s
```

Just use the bazel compiled from its HEAD instead of the released 0.2 version, and the command I use to compile tensorflow pip package is as follows:
```
HTTPS_PROXY=http://proxyip:proxyport ../bazel/output/bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
Use bazel compiled from HEAD!

**Comment by fayeshine** [comment] 2016-03-25 01:55
@myme5261314 , thanks, however many people may not have proxy, we could solve for all peoples by using a modified grpc commit version

**Comment by myme5261314** [comment] 2016-03-25 02:02
@fayeshine Yes, you are right, just tell somebody who has proxy but failed to compile tensorflow.

It will save a lot of time for the people who doesn't have a proxy.

But, I don't think the contributors of `boringssl` have no need to follow us transfer their coding place from google's site to github or this will waste their time, right?

Anyway, I only know this workaround with proxy.

I also want this useful library (tensorflow) to be easy to use for us who has been blocked from part of the Internet.

:-)

**Comment by fayeshine** [comment] 2016-03-25 02:09
@myme5261314 actually they already have a boringssl in github, and grpc have used this github version boringssl in some commit version, see my pull request #1626  and @zszhong 's idea. Just modify one line and we don't need  proxy and we can build standalone and distributed version of tensowflow successfullt.

**Comment by fayeshine** [comment] 2016-03-25 02:10
@shengjt with #1626 , I can built the distributed version using your command as well.

**Comment by zszhong** [comment] 2016-03-25 02:47
Hi, @fayeshine @myme5261314 @shengjt , I cloned the latest master branch [b1aeb4495bd10b3f1f0d4aed64880f8896fe990b] and modified the `tensorflow/workspace.bzl` with #1626. 
Now the following binaries can be built successfully.

        bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
        bazel build -c opt --verbose_failures //tensorflow/core/distributed_runtime/rpc:grpc_tensorflow_server
        bazel build -c opt --config=cuda //tensorflow/core/distributed_runtime/rpc:grpc_testlib_server
        bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
        bazel build -c opt --config=cuda //tensorflow/libtensorflow.so
        bazel build -c opt --config=cuda //tensorflow/core/ops/compat/update_ops
        bazel build -c opt --config=cuda //tensorflow/examples/label_image:label_image

**Closed** 2016-05-10 22:03 UTC
Labels: installation/startup

**Comment by greenSnot** [comment] 2016-06-28 05:38
repalce "https://boringssl.googlesource.com/boringssl" by "https://github.com/google/boringssl.git" in tenserflow/tensorflow/workspace.bzl
