### ISSUE TITLE
Tensorflow 2.0 make_csv_dataset reads files too slowly

### ISSUE THREAD

**Issue by wkzqn** [tensorflow/tensorflow#38293] opened 2020-04-07 02:56 UTC
It takes 10 seconds to read a batch of 1024 data from the csv file. After setting the num_parallel_reads parameter to 2, the time becomes 5 seconds. But continue to increase the reading thread, the time will not be reduced. Am I setting something wrong?

**Comment by aniketmaurya** [comment] 2020-04-07 04:06
Try num_parallel_calls= tf.data.experimental.AUTOTUNE

**Comment by ravikyram** [comment] 2020-04-07 06:52
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the code snippet to reproduce the issue in our environment. It helps us in localizing the issue faster. If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by wkzqn** [comment] 2020-04-07 07:58
The tensorflow version is 2.0.0(gpu).
The system information is as follows：
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

**Comment by ravikyram** [comment] 2020-04-07 08:46
@wkzqn 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-04-20 11:37
@wkzqn 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-04-24 07:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-24 07:23 UTC
Labels: TF 2.0, stat:awaiting response, type:support
