### ISSUE TITLE
Messed up dimentions expanding within transform calling

### ISSUE THREAD

**Issue by mikhailkin** [tensorflow/tensorflow#19667] opened 2018-05-31 11:55 UTC
https://github.com/tensorflow/tensorflow/blob/25b2f01d5fc9ae500bc5969291ba90e48b25cceb/tensorflow/contrib/image/python/ops/image_ops.py#L252

If image has no channels, we have to add one in the last dim
So the code have to be:
images = image_or_images[ :, :, :, None]

**Comment by mikhailkin** [comment] 2018-05-31 12:06
But code might be useful to process one picture.
I've got errors when I tried to process multiple images k*32*32 with multiple transforms k*8 with no good info

**Comment by tensorflowbutler** [comment] 2018-06-17 18:42
Nagging Assignee @tatianashp: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-03 12:48
Nagging Assignee @tatianashp: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-18 19:04
Nagging Assignee @tatianashp: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-02 19:08
Nagging Assignee @tatianashp: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-17 18:58
Nagging Assignee @tatianashp: It has been 78 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-01 18:44
Nagging Assignee @tatianashp: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment] 2018-09-01 22:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mikhailkin** [comment] 2018-09-11 21:50
Hi, @tatianashp!
What do you mean? All info is provided.

**Comment by yongtang** [comment] 2018-09-12 14:59
@mikhailkin In the documentation:
```
    images: A tensor of shape (num_images, num_rows, num_columns, num_channels)
       (NHWC), (num_rows, num_columns, num_channels) (HWC), or
       (num_rows, num_columns) (HW). The rank must be statically known (the
       shape is not `TensorShape(None)`.
```

It looks like if the rank is 3, then the expected input is `HWC`. So the `N` (batch) will be added instead, which will be dim 0. 

I think this might be expected behavior?

**Comment by tensorflowbutler** [comment] 2018-09-27 19:06
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-12 12:47
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-27 12:34
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-11-11 18:36
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by yongtang** [comment] 2018-11-11 19:19
@mikhailkin I think this is the expected behavior. Will close the issue for now but feel free to reopen if issue still exists.

**Closed by yongtang** 2018-11-11 19:19 UTC
Labels: stat:contributions welcome
