### ISSUE TITLE
tf.keras.layers.Lambda deserialization fails due to `KeyError: 'name'`

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#37056] opened 2020-02-25 18:14 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  `macOS Catalina 10.15.2 (19C57)`
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): nightly binary (`v1.12.1-25814-g2e81bc66c5 2.2.0-dev20200225`)
- Python version: 3.7.6
- CUDA/cuDNN version: - GPU model and memory: n/a

**Describe the current behavior**
Trying to serialize and then deserialize a simple `tf.keras.layers.Lambda` results in `KeyError: 'name'`.

**Describe the expected behavior**
No `KeyError: 'name'` exception is thrown and the model is deserialized correctly.

**Standalone code to reproduce the issue** 
```python
import tensorflow as tf


inputs = tf.random.uniform((4, 3))

sequential_model = tf.keras.Sequential((
    tf.keras.layers.Lambda(lambda x: tf.concat(tf.nest.flatten(x), axis=-1)),
))

_ = sequential_model(inputs)

sequential_model_2 = tf.keras.Model.from_config(sequential_model.get_config())
```

**Other info / logs**
```
$ python ./tests/test_lambda_layer_serialization.py
Traceback (most recent call last):
  File "./tests/test_lambda_layer_serialization.py", line 12, in <module>
    sequential_model_2 = tf.keras.Model.from_config(sequential_model.get_config())
  File "/Users/hartikainen/conda/envs/softlearning-tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 950, in from_config
    config, custom_objects)
  File "/Users/hartikainen/conda/envs/softlearning-tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1987, in reconstruct_from_config
    process_layer(layer_data)
  File "/Users/hartikainen/conda/envs/softlearning-tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1956, in process_layer
    layer_name = layer_data['name']
KeyError: 'name'
```

**Comment by hartikainen** [comment] 2020-02-25 19:16
Just realized that the code works with `tf.keras.Sequential.from_config(sequential_model.get_config())`, so maybe this is a user error.

**Comment by gadagashwini** [comment] 2020-02-26 09:26
@hartikainen, Can we close this, since the issue is resolved. Thanks!

**Closed** 2020-02-26 10:09 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug

**Comment by hartikainen** [comment] 2020-02-26 10:11
@gadagashwini yeah, I'm closing it. I wonder what the difference between `tf.keras.Sequential.from_config` and `tf.keras.Model.from_config` is? Why does the latter one fail in this case? I'd imagine that `Sequential` models could be safely deserialized through `tf.keras.Model.from_config`? I might be wrong though.

**Comment by gadagashwini** [comment] 2020-02-26 11:41
@jvishnuvardhan, Can you PTAL. Thanks
