### ISSUE TITLE
"Error computing ByteSize (possible overflow?)" when trying to save tensorflow model

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#666] opened 2016-01-02 08:50 UTC
[libprotobuf ERROR google/protobuf/src/google/protobuf/message_lite.cc:293] Error computing ByteSize (possible overflow?).

This happens for my mlp model, hidden size > 60, 
tf.train.Saver().save(self.session, model_path + '/model.ckpt', global_step = epoch)

How to avoid this?

**Comment by josh11b** [comment] 2016-01-12 00:47
Do you have a link to a model that reproduces this problem?

**Comment by v-shinc** [comment] 2016-02-28 12:34
I met this problem too, it seems that the variable is too big. In my model, when the size of variable is [10000000, 192],  it reports "[libprotobuf ERROR google/protobuf/src/google/protobuf/message_lite.cc:293]Error computing ByteSize (possible overflow?).", when the size of variable is [20000000, 192], it reports "[libprotobuf FATAL google/protobuf/src/google/protobuf/message_lite.cc:72] This shouldn't be called if all the sizes are equal."

**Comment by hillelt** [comment] 2016-03-16 10:05
I get this error when trying to save a text classification model that uses pre-trained word embeddings.  I was able to reproduce it with the minimal snippet below. It definitely looks like a variable size issue since the example completes successfully once you switch from 3,000,000 rows to 300,000 rows.

The issue looks important since since these models are common in NLP and not being able to save them means you can't really use them in production.

```
# Reproducing the error:
import tensorflow as tf
import numpy as np

with tf.device('/cpu:0'):
    rows = 3000000
    cols = 300
    input_W = tf.placeholder(tf.float32, [rows, cols])
    W = tf.Variable(input_W)
    sess = tf.Session()
    sess.run(tf.initialize_all_variables(), feed_dict={input_W: np.random.rand(rows, cols)})
    saver = tf.train.Saver(tf.all_variables())
    path = saver.save(sess, "dump.bin")
    print "Done."

```

**Comment by nidleo** [comment] 2016-04-13 07:54
+1. same problem here.

**Comment by sherrym** [comment] 2016-04-18 18:14
If you don't use the meta_graph feature, please add "write_meta_graph=False" option to saver.save().

Sherry

**Comment by hillelt** [comment] 2016-05-06 19:53
Sherry, I added `write_meta_graph=False` to the snippet from my previous comment (see modified snippet above, using TensorFlow 0.8), but I'm getting the same error, this doesn't seem to help.

**Comment by byzhang** [comment] 2016-05-15 16:19
Same error here.

**Comment by sherrym** [comment] 2016-05-15 18:47
The error is due to current size limit on protocol buffers in the implementation of message lite. Can you shard the Variable so it's not so large? 

bool MessageLite::SerializePartialToCodedStream(
    io::CodedOutputStream* output) const {
  const int size = ByteSize();  // Force size to be cached.
  if (size < 0) {
    // Messages >2G cannot be serialized due to overflow computing ByteSize.
    GOOGLE_LOG(ERROR) << "Error computing ByteSize (possible overflow?).";
    return false;
  }

**Comment by byzhang** [comment] 2016-05-15 18:53
The variables are the embeddings of word2vec with a large vocabulary. It
seems not easy to shard them without changing the NegTrainOp and python
caller code a lot?

Thanks,
-B

**Comment by girving** [comment] 2016-06-08 23:44
Closing since this issue seems to have been diagnosed.  Please direct further questions about sharding variables to StackOverflow.

**Closed by girving** 2016-06-08 23:44 UTC
