### ISSUE TITLE
`tensorflow.examples.tutorials.mnist` not currently downloadable

### ISSUE THREAD

**Issue by asross** [tensorflow/tensorflow#6742] opened 2017-01-09 15:03 UTC
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```python
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
```

raises `http.client.RemoteDisconnected: Remote end closed connection without response`, if you don't already have the data cached. I believe this is because the underlying data [SOURCE_URL](http://yann.lecun.com/exdb/mnist/) is currently [down](http://downforeveryoneorjustme.com/http://yann.lecun.com/exdb/mnist/).

**Comment by asross** [comment] 2017-01-09 15:17
...It's back up again now. Looks like it was just a temporary disruption.

**Comment by joethompson1961** [comment] 2017-02-13 21:29
I encountered the same problem just now.  how do I fix it?

**Comment by asross** [comment] 2017-02-14 13:25
> Using the same code:
> 
> from tensorflow.examples.tutorials.mnist import input_data
> mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
> 
> raises a timeout error: TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> 
> What would cause this?

The issue is that the website where MNIST is canonically hosted sometimes goes down. I think an ideal solution would be to find or set up a mirror, then fall back to it? Or just find a more stable source.

**Comment by gdfishhannah** [comment] 2017-03-01 23:33
I also have the 10060 problem and it always happened. This seems like not the host problem. Do you know what caused this?

**Comment by asross** [comment] 2017-03-01 23:51
Reopening because others seem to have this problem.

**Comment by asross** [comment] 2017-03-01 23:52
I would suggest that if you encounter this problem, check http://downforeveryoneorjustme.com/http://yann.lecun.com/exdb/mnist/ just to make sure.

**Comment by gdfishhannah** [comment] 2017-03-01 23:59
I cannot reach this website

**Comment by awilliamson** [comment] 2017-03-05 19:23
Confirmed. I'm also having MNIST issues. Is there any alternative URL we can use for this which will still be compatible with existing MNIST tutorials. I'm relying on these as baselines for experiments, I'd rather keep the data and TF format the same.

**Comment by kakawait** [comment] 2017-03-06 13:05
Still down seems few days... Other related issue #8116

**Comment by auserdude** [comment] 2017-03-06 14:16
Same project here, solved by downloading file from a different source. I think we should put in place a mirror somewhere.

**Comment by jeffheaton** [comment] 2017-03-06 21:56
Also cannot access.

**Comment by prb12** [comment] 2017-03-07 23:36
Closing as duplicate of https://github.com/tensorflow/tensorflow/issues/8126

**Closed by prb12** 2017-03-07 23:36 UTC

**Comment by prb12** [comment] 2017-03-08 00:27
@auserdude If you retrieve the `.gz` files from any other source (wayback machine?) and drop them in your data_dir then TF will just use them.  It does not validate a checksum AFAIK.
