### ISSUE TITLE
tf.nn.bias_add does not work right after tf.map_fn

### ISSUE THREAD

**Issue by fingerblister** [tensorflow/tensorflow#38173] opened 2020-04-02 18:36 UTC
tf-nightly-gpu 2.2.0.dev20200402
Ubuntu 18.04.4 LTS

Bug:
File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 672, in bias_add
    tld.op_callbacks, value, bias, "data_format", data_format)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:
...
 x = tf.nn.bias_add(x, self.bias)  # Where self.bias is a tf.Variable
  File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 3018, in bias_add
    value, bias, data_format=data_format, name=name)
  File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 677, in bias_add
    value, bias, data_format=data_format, name=name, ctx=_ctx)
  File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 710, in bias_add_eager_fallback
    ctx=ctx, name=name)
  File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File ".../anaconda3/envs/tf-nightly-gpu/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: .../StatefulPartitionedCall_1:0

Hotfix:
x = tf.map_fn(...)
Lambda(lambda x: x)(x) // or any other keras layer
tf.nn.bias_add(x)

**Comment by amahendrakar** [comment] 2020-04-03 07:06
@fingerblister,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment] 2020-04-10 14:08
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-21 09:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-21 09:58 UTC
Labels: stalled, stat:awaiting response, type:bug
