### ISSUE TITLE
tf.scatter_update to variable pinned on GPU fails

### ISSUE THREAD

**Issue by muhadriy** [tensorflow/tensorflow#12046] opened 2017-08-04 19:05 UTC
### System information
- Linux Ubuntu 16.04
- tensorflow-gpu v1.2.0 binary installed from pip
- Python 3.5
- CUDA 8.0, cuDNN v5.1 
- GeForce GTX 1080 Ti, 11GB
- A simple example I came up with which reproduces the error follows below:
**************************************************************************************************
```python
import tensorflow as tf
with tf.device("/gpu:0"):
    a = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8])
    c = tf.Variable([0, 0, 0, 0, 0, 0, 0, 0])
    step_sos = tf.Variable([False, False, True, True, False, False, True, True])
    write_ops = []
    for b in range(8):
        write_ops.append(tf.cond(step_sos[b], lambda: tf.scatter_update(a, b, 0), lambda: a))

    with tf.control_dependencies(write_ops):
       d = tf.assign(c, a)


session_config = tf.ConfigProto(allow_soft_placement=False, log_device_placement=True)

with tf.Session(config=session_config) as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    sess.run(d)
    print(sess.run(c))
```
********************************************************************************************************              

### 
When setting allow_soft_placement=True the error is solved but the variable and some operations which are often used are placed in the CPU, which leads to fluctuating GPU utilization.

### Source code / logs
```
Traceback (most recent call last):
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1117, in _run_fn
    self._extend_graph()
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1166, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Variable_2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU 
VariableV2: CPU 
	 [[Node: Variable_2 = VariableV2[container="", dtype=DT_BOOL, shape=[8], shared_name="", _device="/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scatter_test.py", line 20, in <module>
    sess.run(init_op)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Variable_2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU 
VariableV2: CPU 
	 [[Node: Variable_2 = VariableV2[container="", dtype=DT_BOOL, shape=[8], shared_name="", _device="/device:GPU:0"]()]]

Caused by op 'Variable_2', defined at:
  File "scatter_test.py", line 7, in <module>
    step_sos = tf.Variable([False, False, True, True, False, False, True, True])
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 200, in __init__
    expected_shape=expected_shape)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 297, in _init_from_args
    name=name)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 128, in variable_op_v2
    shared_name=shared_name)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 684, in _variable_v2
    name=name)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ylli/neuralattention/code/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Variable_2': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU 
VariableV2: CPU 
	 [[Node: Variable_2 = VariableV2[container="", dtype=DT_BOOL, shape=[8], shared_name="", _device="/device:GPU:0"]()]]
```

**Comment by reedwm** [comment] 2017-08-14 17:06
I'm able to reproduce with this simplified case:

```python
import tensorflow as tf

with tf.device("/gpu:0"):
  tf.Variable([False, False, True, True, False, False, True, True])

session_config = tf.ConfigProto(allow_soft_placement=False, log_device_placement=True)

with tf.Session(config=session_config) as sess:
  init_op = tf.global_variables_initializer()
  sess.run(init_op)
```

So it seems boolean Variables cannot be placed (or at least initialized) on the GPU. 

@mrry, can you take a look?

**Comment by mrry** [comment] 2017-08-14 17:46
It looks like the kernel backing `tf.Variable` isn't registered for `tf.bool` on GPU devices. See the use of `TF_CALL_GPU_NUMBER_TYPES()` to register the kernel for different types [here](https://github.com/tensorflow/tensorflow/blob/b93fd37e143bcdd6339f8e6081c948384a262e0b/tensorflow/core/kernels/variable_ops.cc#L85), and note that the macro's definition [here](https://github.com/tensorflow/tensorflow/blob/b93fd37e143bcdd6339f8e6081c948384a262e0b/tensorflow/core/framework/register_types.h#L171) doesn't include `bool`.

**Comment by reedwm** [comment] 2017-08-14 19:01
Marking as contributions welcome if someone wants to add GPU boolean variable support.

**Comment by nolanliou** [comment] 2017-08-15 10:03
Have sent a PR for this issue.

**Comment by jhseu** [comment] 2017-09-01 20:49
We had to revert the fix. A minimal reproducible breakage is here:
```
def main(unused_argv):
  dtype = tf.bool
  bool_var = tf.get_variable("bool_var", dtype=dtype,
                             initializer=tf.cast(1, dtype),
                             trainable=False)
  def set_bool_var_false():
    return tf.group(tf.assign(bool_var, tf.cast(0, dtype)))

  conditional_on_bool_var = tf.cond(pred=tf.cast(bool_var, tf.bool),
                                    true_fn=set_bool_var_false,
                                    false_fn=tf.no_op)

  with tf.train.MonitoredSession() as sess:
    print(sess.run(bool_var))
    print(sess.run(conditional_on_bool_var))
    print(sess.run(bool_var))
```

**Comment by nolanliou** [comment] 2017-09-02 04:22
I'm confused where the attribute type will become the ref-type.

**Comment by mohantym** [comment] 2022-01-12 14:17
Hi @muhadriy ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more.  I could not find issue in [2.7 ](https://colab.sandbox.google.com/gist/mohantym/c0cdb3e63396b18b9d2aeec9b4035171/github_12046.ipynb)though. Thanks!

**Closed** 2022-01-26 15:26 UTC
Labels: stat:awaiting response, stalled
