### ISSUE TITLE
Reopened : Is tf2xla used even when jit_compile=False

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#55957] opened 2022-05-06 14:48 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

linux 64 bit

### Python version

3.9

### Current Behaviour?

```shell
Reopening https://github.com/tensorflow/tensorflow/issues/55207
```

### Standalone code to reproduce the issue

```shell
See https://github.com/tensorflow/tensorflow/issues/55207
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment] 2022-05-09 07:16
Hello @whatdhack ,
Issue #55207 is in open state.Looks like this is duplicate of issue [#55207](https://github.com/tensorflow/tensorflow/issues/55207).Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2022-05-09 14:38 UTC
Labels: stat:awaiting response, type:bug, comp:xla, TF 2.8
