### ISSUE TITLE
Customized loss can't get the shape of input data (BUG?)

### ISSUE THREAD

**Issue by RitchieAlpha** [tensorflow/tensorflow#29642] opened 2019-06-11 12:06 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta
- Python version:
- Bazel version (if compiling from source): 3.7.3
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.0 with cudnn 7.6
- GPU model and memory: 12GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I write a custom loss function (dice coefficient) with following code:
``` python
def dice_coef(y_true, y_pred, smooth=1e-7):
    _, W, H, D, C = y_pred.get_shape()

    y_pred = tf.reshape(y_pred, shape=[-1, W * H * D * C])
    y_true = tf.reshape(y_true, shape=[-1, W * H * D * C])

    y_pred = tf.cast(y_pred, dtype=tf.float32)
    y_true = tf.cast(y_true, dtype=tf.float32)

    dice_numerator = 2.0 * tf.reduce_sum(y_true * y_pred, axis=1) + smooth
    dice_denominator = tf.reduce_sum(y_pred + y_true, axis=1) + smooth

    dice_coefficient = dice_numerator / dice_denominator
    dice_coefficient = tf.reduce_mean(dice_coefficient)
    return dice_coefficient
```
when i run code like this:
``` python
mirrored_strategy = tf.distribute.MirroredStrategy()
    with mirrored_strategy.scope():
        model = unet3d(input_shape=input_shape, num_class=num_class, activation='sigmoid')
        model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.001),
                      loss=bce_dice,
                      metrics=[
                          tf.keras.metrics.BinaryAccuracy(),
                          tf.keras.metrics.BinaryCrossentropy(),
                      ])
```
i got the following error 
``` python
Traceback (most recent call last):
  File "/tmp/pycharm_project_317/opt/train.py", line 84, in <module>
    epochs=50)
  File "/tmp/pycharm_project_317/opt/train.py", line 21, in train
    callbacks=callbacks)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_distributed.py", line 681, in fit
    steps_name='steps_per_epoch')
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 294, in model_iteration
    batch_outs = f(actual_inputs)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/distribute/distributed_training_utils.py", line 813, in execution_function
    return [out.numpy() for out in distributed_function(input_fn)]
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 416, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 359, in _initialize
    *args, **kwds))
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1360, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:

    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/distribute/distributed_training_utils.py:804 distributed_function  *
        outputs = strategy.experimental_run_v2(
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:708 experimental_run_v2
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1710 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:708 _call_for_each_replica
        fn, args, kwargs)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:195 _call_for_each_replica
        coord.join(threads)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py:389 join
        six.reraise(*self._exc_info_to_raise)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/six.py:693 reraise
        raise value
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py:297 stop_on_exception
        yield
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py:926 run
        self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:908 train_on_batch
        output_loss_metrics=self._output_loss_metrics)
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_eager.py:307 train_on_batch
        output_loss_metrics=output_loss_metrics))
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_eager.py:237 _process_single_batch
        training=training))
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_eager.py:152 _model_loss
        per_sample_losses = loss_fn.call(targets[i], outs[i])
    /home/tanjl/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:215 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /tmp/pycharm_project_317/app/losses/binary.py:26 bce_dice
        return -dice_coef(y_true, y_pred, smooth) + \
    /tmp/pycharm_project_317/app/losses/binary.py:7 dice_coef
        y_pred = tf.reshape(y_pred, shape=[-1, W * H * D * C])

    TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

bash: 行 1:  7597 段错误               (核心已转储) env "PYCHARM_HOSTED"="1" "PYTHONUNBUFFERED"="1" "PYTHONIOENCODING"="UTF-8" "PYCHARM_MATPLOTLIB_PORT"="52949" "JETBRAINS_REMOTE_RUN"="1" "PYTHONPATH"="/home/tanjl/.pycharm_helpers/pycharm_matplotlib_backend:/tmp/pycharm_project_317" /home/tanjl/anaconda3/envs/tensorflow2/bin/python3.7 -u /tmp/pycharm_project_317/opt/train.py
```
**Describe the expected behavior**
it have no error when i run code with tf-2.0.0-alpha but the error happend with beta version tensorflow 
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
it can't get the input shape in loss function, is that right? and i wish u could help me, thanks

**Comment by ravikyram** [comment] 2019-06-25 10:41
Please provide us complete code to reproduce the issue.Thanks.

**Comment by ravikyram** [comment] 2019-07-02 04:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-02 04:37 UTC
Labels: 2.0.0-beta0, comp:dist-strat, stat:awaiting response, type:support

**Comment by kristofgiber** [comment] 2019-09-01 05:56
I'm having the same error. The [TF example VAE code](url) doesn't run with distribute strategy (see code below). I'm on tf2.0.0.0-beta1 (tried rc0 but it has too many issues at this stage to upgrade, I have to stick with beta). 

Error: 
> per_sample_losses = loss_fn.call(targets[i], outs[i]) 
> IndexError: list index out of range

(See full error stack in the bottom)

Any workaround to this?

```

import numpy as np
import os
import tensorflow_probability as tfp
tfd = tfp.distributions
import tensorflow as tf
from tensorflow.keras import layers

load_model = 1

latent_dim = 8
learning_rate = 1e-4

BATCH_SIZE = 100
TEST_BATCH_SIZE = 10

color_channels = 1
(train_images, _), (test_images, _) = tf.keras.datasets.mnist.load_data()

train_images = train_images[:5000,::]
test_images = test_images[:1000,::]
n_trainsamples = np.shape(train_images)[0]
n_testsamples = np.shape(test_images)[0]
imsize = np.shape(train_images)[1]
np.random.shuffle(train_images)
train_images = train_images.reshape(-1, imsize, imsize, 1).astype('float32')
test_images = test_images.reshape(-1, imsize, imsize, 1).astype('float32')
train_images /= 255.
test_images /= 255.
train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(n_trainsamples).batch(BATCH_SIZE)
test_dataset = tf.data.Dataset.from_tensor_slices((test_images)).shuffle(n_testsamples).batch(TEST_BATCH_SIZE)

strategy = tf.distribute.MirroredStrategy()


with strategy.scope():

    optimizer = tf.keras.optimizers.Adam(learning_rate)

    class Sampling(tf.keras.layers.Layer):
        """Uses (z_mean, z_log_var) to sample z, the vector encoding an image."""
        def call(self, inputs):
            z_mean, z_log_var = inputs
            batch = tf.shape(z_mean)[0]
            dim = tf.shape(z_mean)[1]
            epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
            return z_mean + tf.exp(0.5 * z_log_var) * epsilon


    original_dim = 784
    intermediate_dim = 64
    latent_dim = 32

    # Define encoder model.
    original_inputs = tf.keras.Input(shape=(imsize, imsize, color_channels), name='encoder_input')
    x = layers.Dense(intermediate_dim, activation='relu')(original_inputs)
    z_mean = layers.Dense(latent_dim, name='z_mean')(x)
    z_log_var = layers.Dense(latent_dim, name='z_log_var')(x)
    z = Sampling()((z_mean, z_log_var))
    encoder = tf.keras.Model(inputs=original_inputs, outputs=z, name='encoder')

    # Define decoder model.
    latent_inputs = tf.keras.Input(shape=(latent_dim,), name='z_sampling')
    x = layers.Dense(intermediate_dim, activation='relu')(latent_inputs)
    outputs = layers.Dense(original_dim, activation='sigmoid')(x)
    outputs = tf.keras.layers.Reshape(target_shape=(imsize, imsize, color_channels))(x)
    decoder = tf.keras.Model(inputs=latent_inputs, outputs=outputs, name='decoder')

    # Define VAE model.
    outputs = decoder(z)
    vae = tf.keras.Model(inputs=original_inputs, outputs=outputs, name='vae')

    # Add KL divergence regularization loss.
    kl_loss = - 0.5 * tf.reduce_mean(
        z_log_var - tf.square(z_mean) - tf.exp(z_log_var) + 1)
    vae.add_loss(kl_loss)

    # Train.
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
    vae.compile(optimizer, loss=tf.keras.losses.MeanSquaredError())
    vae.fit(train_dataset, epochs=n_trainsamples//BATCH_SIZE)

```


Logs:

> 2019-09-01 05:47:53.856027: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
> 2019-09-01 05:47:53.860170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 7a50:00:00.0
> 2019-09-01 05:47:53.860377: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2019-09-01 05:47:53.861509: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
> 2019-09-01 05:47:53.862528: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
> 2019-09-01 05:47:53.862808: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
> 2019-09-01 05:47:53.864211: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
> 2019-09-01 05:47:53.865345: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
> 2019-09-01 05:47:53.868965: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2019-09-01 05:47:53.869575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
> 2019-09-01 05:47:53.869944: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-09-01 05:47:53.948861: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x52c0430 executing computations on platform CUDA. Devices:
> 2019-09-01 05:47:53.948905: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
> 2019-09-01 05:47:53.951820: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2596990000 Hz
> 2019-09-01 05:47:53.952412: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5330710 executing computations on platform Host. Devices:
> 2019-09-01 05:47:53.952439: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
> 2019-09-01 05:47:53.952837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 7a50:00:00.0
> 2019-09-01 05:47:53.952893: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2019-09-01 05:47:53.952914: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
> 2019-09-01 05:47:53.952931: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
> 2019-09-01 05:47:53.952948: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
> 2019-09-01 05:47:53.952965: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
> 2019-09-01 05:47:53.952981: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
> 2019-09-01 05:47:53.952999: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2019-09-01 05:47:53.953570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
> 2019-09-01 05:47:53.953614: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2019-09-01 05:47:53.955775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-09-01 05:47:53.955803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
> 2019-09-01 05:47:53.955816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
> 2019-09-01 05:47:53.956462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 224 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 7a50:00:00.0, compute capability: 3.7)
> 2019-09-01 05:47:53.970613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
> name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
> pciBusID: 7a50:00:00.0
> 2019-09-01 05:47:53.970682: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2019-09-01 05:47:53.970703: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
> 2019-09-01 05:47:53.970720: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
> 2019-09-01 05:47:53.970736: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
> 2019-09-01 05:47:53.970751: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
> 2019-09-01 05:47:53.970767: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
> 2019-09-01 05:47:53.970783: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2019-09-01 05:47:53.971338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
> 2019-09-01 05:47:53.971377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-09-01 05:47:53.971391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
> 2019-09-01 05:47:53.971401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
> 2019-09-01 05:47:53.971990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 224 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 7a50:00:00.0, compute capability: 3.7)
> Train on 50 steps
> Epoch 1/50
> Traceback (most recent call last):
>   File "/home/kristofgiber/pycharm_project/VAE/save_issue_reproduction.py", line 82, in <module>
>     vae.fit(train_dataset, epochs=n_trainsamples//BATCH_SIZE)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 681, in fit
>     steps_name='steps_per_epoch')
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 294, in model_iteration
>     batch_outs = f(actual_inputs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/distribute/distributed_training_utils.py", line 813, in execution_function
>     return [out.numpy() for out in distributed_function(input_fn)]
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/def_function.py", line 416, in __call__
>     self._initialize(args, kwds, add_initializers_to=initializer_map)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/def_function.py", line 359, in _initialize
>     *args, **kwds))
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 1360, in _get_concrete_function_internal_garbage_collected
>     graph_function, _, _ = self._maybe_define_function(args, kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 1648, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 1541, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py", line 716, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/def_function.py", line 309, in wrapped_fn
>     return weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/func_graph.py", line 706, in wrapper
>     raise e.ag_error_metadata.to_exception(type(e))
> tensorflow.python.autograph.impl.api.StagingError: in converted code:
>     relative to /usr:
> 
>     local/lib/python3.5/dist-packages/tensorflow/python/keras/distribute/distributed_training_utils.py:804 distributed_function  *
>         outputs = strategy.experimental_run_v2(
>     local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py:708 experimental_run_v2
>         return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
>     local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py:1710 call_for_each_replica
>         return self._call_for_each_replica(fn, args, kwargs)
>     local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:708 _call_for_each_replica
>         fn, args, kwargs)
>     local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:195 _call_for_each_replica
>         coord.join(threads)
>     local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py:389 join
>         six.reraise(*self._exc_info_to_raise)
>     lib/python3/dist-packages/six.py:686 reraise
>         raise value
>     local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py:297 stop_on_exception
>         yield
>     local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py:926 run
>         self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
>     local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py:908 train_on_batch
>         output_loss_metrics=self._output_loss_metrics)
>     local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_eager.py:307 train_on_batch
>         output_loss_metrics=output_loss_metrics))
>     local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_eager.py:237 _process_single_batch
>         training=training))
>     local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_eager.py:152 _model_loss
>         per_sample_losses = loss_fn.call(targets[i], outs[i])
> 
>     IndexError: list index out of range
> 
> 
> Process finished with exit code 1
>

**Comment by ragnariock** [comment] 2020-02-12 08:33
I have same error
