### ISSUE TITLE
404 Error during oxford-pets tutorial dataset loading

### ISSUE THREAD

**Issue by janprz** [tensorflow/tensorflow#31171] opened 2019-07-30 20:03 UTC
**System information**
- OS Platform and Distribution (Windows 10):
- TensorFlow installed from (binary):
- TensorFlow version: GPU 2.0 beta
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory: nvidia GTX 1050 4gb

**Describe the problem**
problematic tutorial: https://www.tensorflow.org/beta/tutorials/images/segmentation
In the segmentation tutorial, with the copied code from the tutorial, when loading oxford pet dataset from tensorflow_datasets I get:
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.

I can  go to the site with the web browser with no problems (and even download the dataset).
**Provide the exact sequence of commands / steps that you executed before running into the problem**
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow_examples.models.pix2pix import pix2pix
import tensorflow_datasets as tfds
tfds.disable_progress_bar()
from IPython.display import clear_output
import matplotlib.pyplot as plt
#problematic line:
dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)

**Any other info / logs**
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.

Am i doing something wrong, or the site structure changed?

**Comment by gadagashwini** [comment] 2019-07-31 08:29
@janprz I tried executing the code on Colab but i didn't see any error message. It successfully downloaded the dataset. Please look at the below output.
```
Dataset oxford_iiit_pet downloaded and prepared to /root/tensorflow_datasets/oxford_iiit_pet/3.0.0. Subsequent calls will reuse this data.
W0731 08:24:33.067447 140505681938304 dataset_builder.py:397] Warning: Setting shuffle_files=True because split=TRAIN and shuffle_files=None. This behavior will be deprecated on 2019-08-06, at which point shuffle_files=False will be the default for all splits.
``` 
Could you please try once and let us know. Thanks!

**Comment by janprz** [comment] 2019-07-31 16:13
Hello, I have tried again, but the problem still exists. I am connected to the internet so I have no idea why I am getting 404, because I haven't edited any url path or something.

**Comment by janprz** [comment] 2019-07-31 16:14
> @janprz I tried executing the code on Colab but i didn't see any error message. It successfully downloaded the dataset. Please look at the below output.
> 
> ```
> Dataset oxford_iiit_pet downloaded and prepared to /root/tensorflow_datasets/oxford_iiit_pet/3.0.0. Subsequent calls will reuse this data.
> W0731 08:24:33.067447 140505681938304 dataset_builder.py:397] Warning: Setting shuffle_files=True because split=TRAIN and shuffle_files=None. This behavior will be deprecated on 2019-08-06, at which point shuffle_files=False will be the default for all splits.
> ```
> 
> Could you please try once and let us know. Thanks!

Hello, I have tried again, but the problem still exists. I am connected to the internet so I have no idea why I am getting 404, because I haven't edited any url path or something.

**Comment by janprz** [comment] 2019-07-31 16:38
I have also tried connecting through the other internet provider with same effect.

**Comment by janprz** [comment] 2019-07-31 16:54
Using Colab it worked, but why I can't do it locally on my pc? I want to work later with little or no internet on holidays.

**Comment by ymodak** [comment] 2019-07-31 23:05
You can download the data from this link
https://www.robots.ox.ac.uk/~vgg/data/pets/

**Comment by janprz** [comment] 2019-08-01 07:47
Thanks a lot for the answers,  I have already downloaded it myself manually.
However it is interesting that only this dataset cannot be downloaded by me with tfds.load().

Since the problem isn't resolved I shouldn't close the issue?

**Comment by maracuja-orange** [comment] 2019-08-01 13:58
Hi,
I've got the exact same problem with a similar setup.

    OS Platform and Distribution (Windows 10):
    TensorFlow version: GPU 2.0 beta
    Python version: 3.6
    Installed using virtualenv? pip? conda?: pip
    CUDA/cuDNN version: 10.0/7.6
    GPU model and memory: nvidia GTX 1060 6gb

**Comment by ymodak** [comment] 2019-08-01 18:54
That's surprising I am not able reproduce it.  Can you try with TF 2.0 nightly version?
```!pip install tf-nightly-2.0-preview```

**Comment by maracuja-orange** [comment] 2019-08-02 11:27
> 
> 
> Can you try with TF 2.0 nightly version?
> `!pip install tf-nightly-2.0-preview`

Thanks for your answer,
but I tried it and I still get the same error

**Comment by ymodak** [comment] 2019-08-02 22:25
@rsepassi Can you please take a look?
https://www.tensorflow.org/beta/tutorials/images/segmentation
Apparently windows users cannot download the dataset with this
```python
dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)
```

**Comment by aqmalafiq** [comment] 2019-08-03 02:25
im having the same problem

**Comment by SylvainArd** [comment] 2019-08-07 13:35
I'm having the same problem I do these lines : 
dataset = tf.keras.utils.get_file("images.tar.gz",
"file:C:/Users/Sylvain ARD/Desktop/test segmentation semantique/images.tar.gz",extract=True)
in place of : 
dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)

but how to get the info please ??
thank you !
bye

**Comment by janprz** [comment] 2019-08-28 12:58
Yes, it is still the issue. I have tried yesterday. No difference.

śr., 28 sie 2019 o 14:39 Alfred Sorten Wolf <notifications@github.com>
napisał(a):

**Comment by davidpagnon** [comment] 2019-08-29 10:27
Same here...
I can download the dataset with `tf.keras.utils.get_file` but then the structure is not the same as in the tutorial, which makes it harder to work on.

It works fine on colab, but it doesn't on windows.

It must be a classic Windows/Linux path incompatibility, since this is the error.  
`Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.`

One could probably edit the code to make it work, but for now I just want to learn how to segment with tensorflow (in order to use it on my own datasets), so I'll just stick to colab. I'm still interested the issue is fixed!

**Comment by davidpagnon** [comment] 2019-08-29 10:29
Same here...
I can download the dataset with `tf.keras.utils.get_file`, or else use another dataset from tfds, but then the structure is not the same as in the tutorial, which makes it harder to work on.

It works fine on colab, but it doesn't on windows.

It must be a classic Windows/Linux path incompatibility, since this is the error.  
`Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.`

One could probably edit the code to make it work, but for now I just want to learn how to segment with tensorflow (in order to use it on my own datasets), so I'll just stick to colab. I'm still interested the issue is fixed!

**Comment by isaacgs44** [comment] 2019-09-08 04:48
Hi, the problem is caused by the os.path.join function for Windows.
Open tensorflow_datasets / image / oxford_iiit_pet.py and replace these lines:
85 replace with `url = _BASE_URL +" /images.tar.gz "`
88 replace with `url = _BASE_URL +" /annotations.tar.gz "`

I hope it helps you

**Comment by XingyuChen01** [comment] 2019-10-06 14:37
> Hi, the problem is caused by the os.path.join function on Windows.
> Open tensorflow_datasets / image / oxford_iiit_pet.py and replace these lines:
> 84 replace with `url = _BASE_URL + "/images.tar.gz",`
> 87 replace with `url = _BASE_URL + "/annotations.tar.gz",`
> 
> 91 replace with ` images_path_dir = dl_paths["images"] + "/images"`
> 92 replace with `annotations_path_dir = dl_paths["annotations"] + "/annotations"`
> 
> I hope it helps you

This is the correct solution for windows users. Classic unix/windows incompatibility due to path conventions

**Comment by xuthus** [comment] 2019-10-08 19:56
only replaced `84` and `87` lines in `tensorflow_datasets/image/oxford_iiit_pet.py` and dataset have been installed successfully
```python
    dl_paths = dl_manager.download_and_extract({
        "images": tfds.download.Resource(
            url= "{}/images.tar.gz".format(_BASE_URL),  # <-- this line changed
            extract_method=tfds.download.ExtractMethod.TAR),
        "annotations": tfds.download.Resource(
            url="{}/annotations.tar.gz".format(_BASE_URL), # <-- this line changed
            extract_method=tfds.download.ExtractMethod.TAR)
    })
```

**Comment by SylvainArd** [comment] 2019-10-08 20:09
thank you
Sylvain Ard
0549507724
0778380991
sylvain.ard@gmail.com
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le mar. 8 oct. 2019 à 22:04, Sergey Yanzin <notifications@github.com> a
écrit :

**Comment by weidadeyaqhhya** [comment] 2019-12-22 05:31
Hi,
have you ever encountered problem of "NonMatchingChecksumError: file has wrong chencksum" when 
downloading the oxford-iiit-pet dataset？ I use tfds.load( )

**Comment by Saduf2019** [comment] 2020-03-24 06:57
@janprz 
please let us know if the issue still persist

**Comment by Saduf2019** [comment] 2020-04-01 09:37
@janprz 
please update on the above comment

**Comment by kevinleeex** [comment] 2020-04-26 16:31
In fact I got this problem recently, my working envs as below:

- mac OSX Catalina 10.15.3
- python 3.7 with virtualenv
- coding in Jupyter notebook
- tensorflow 2.1.0
- tensorflow_datasets 2.1.0

After I run the code below:
```
tfds.load('oxford_iiit_pet:3.1.0')
```
I got the raised error:
```
...images.tar.gz, has wrong checksum.
```
I checked the file size and compared with the version downloaded from [official site](https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz). It looks like the ```tfds``` downloaded the incomplete one with the different size and sha 256 checksum, but the ```tfds``` one looks normal and can be loaded by the code.

Thus there are two options to solve this:
1. Modify and pass the download_config parameter.**(Recommended)**
  ```python
  builder = tfds.builder('oxford_iiit_pet:3.1.0')
  info = builder.info
  print(info)
  config = tfds.download.DownloadConfig()
  # by setting register_checksums as True to pass the check
  config.register_checksums = True
  cats_vs_dogs.download_and_prepare(download_config=config)
  ```
2. Modify the ```checksumurl_checksums/oxford_iiit_pet.txt```
  Just modify the sha 256 checksums and the number sizes of files.

**Comment by janprz** [comment] 2020-04-26 19:13
For me, the problem is solved. Thank You!

śr., 31 lip 2019 o 10:36 gadagashwini <notifications@github.com> napisał(a):

**Comment by MrJiangZhongZheng** [comment] 2020-04-29 15:01
> ```python
> builder
> ```

666

**Comment by sarithdivakarm** [comment] 2020-04-29 18:04
> Hi,
> have you ever encountered problem of "NonMatchingChecksumError: file has wrong chencksum" when
> downloading the oxford-iiit-pet dataset？ I use tfds.load( )

Yes. Same issue here

**Comment by Saduf2019** [comment] 2020-05-02 15:24
@rsepassi 
As confirmed by you that it is resolved for you, let us know if we may move this to closed status.

**Comment by Abhishek2028** [comment] 2020-06-07 15:08
Tensorflow updated this dataset to tfds nightly. "pip install -q -U tfds-nightly"
Use this command. Now you're free to use

**Comment by xixilog** [comment] 2020-06-20 15:46
error download_manager.py

        if self._register_checksums:
            self._record_sizes_checksums()
        elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
            raise NonMatchingChecksumError(resource.url, tmp_path)

**Comment by x5675602** [comment] 2020-12-14 23:54
Downloading and preparing dataset oxford_iiit_pet/3.2.0 (download: 773.52 MiB, generated: 774.69 MiB, total: 1.51 GiB) to /root/tensorflow_datasets/oxford_iiit_pet/3.2.0...
Dl Completed...: 0%
0/2 [00:32<?, ? url/s]
Dl Size...:
0/0 [00:31<?, ? MiB/s]
Extraction completed...:
0/0 [00:31<?, ? file/s]



---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/urllib3/connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

38 frames
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f343b58e470>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPConnectionPool(host='www.robots.ox.ac.uk', port=80): Max retries exceeded with url: /~vgg/data/pets/data/annotations.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f343b58e470>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='www.robots.ox.ac.uk', port=80): Max retries exceeded with url: /~vgg/data/pets/data/annotations.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f343b58e470>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by saikumarchalla** [comment] 2021-05-20 09:28
@janprz Closing this issue since the issue is resolved  for you.

@x5675602 Please  submit a new issue and we can track it seperately. Thanks!

**Closed by saikumarchalla** 2021-05-20 09:28 UTC
Labels: TF 2.0, comp:data, type:bug
