### ISSUE TITLE
Tensorflow 2.1.0 causing all RAM to be consumed on model.fit

### ISSUE THREAD

**Issue by HadiSDev** [tensorflow/tensorflow#37185] opened 2020-02-29 13:18 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 19

- Tensorflow version: 2.1.0cp37
- CUDA/cuDNN version: - GPU model and memory:
1070 GTX 8 GB GDDR5

**Describe the current behavior**
I am using tf.data dataset API. When using model.fit, on the first epoch, I am already consuming 16 GB of RAM when I run with GPU, but when I run with CPU the memory consumption is very small. 

EDIT: tensorflow-cpu actually has the same issue with high memory consumption

Same dataset, same code. This only happens in Tensorflow 2.>

Is this a known issue? What can I do as a temporarily fix?

**Standalone code to reproduce the issue** 
Just a simpel model, with a dataset which loads images:
```
model = models.Sequential()
model.add(Conv2D(4, (9, 9), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(8, (9, 9), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (9, 9), activation='relu'))
model.add(MaxPooling2D((2, 2)))


model.add(Flatten())
model.add(Dense(5, activation='sigmoid'))

model.summary()

model.compile(optimizer='adam', loss=losses.binary_crossentropy, metrics=['accuracy'])

history = model.fit(ds_train,
                    steps_per_epoch=steps_per_epoch,
                    validation_data=ds_val,
                    validation_steps=validation_steps,
                    epochs=10)
```

I should also mention that the images I am using are concatenated images that are 320px * 4 in width and 180 in height

**Comment by HadiSDev** [comment] 2020-02-29 13:31
Actually even when I use tensorflow-cpu, memory consumption is still very high:
![image](https://user-images.githubusercontent.com/10367624/75608492-252c2880-5b00-11ea-913a-fd0ac85dcdff.png)

**Comment by ravikyram** [comment] 2020-03-02 09:36
@HadiSDev 

Could you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by HadiSDev** [comment] 2020-03-03 22:23
Here is the colab link: https://colab.research.google.com/drive/19p1PTKnje-tldQfYCTPimBT99bYK1y7N

It is working on colab but not on my own pc.

**Comment by HadiSDev** [comment] 2020-03-03 22:23
Exact same code and the same pictures

**Comment by HadiSDev** [comment] 2020-03-03 22:52
Might be related to: https://github.com/tensorflow/tensorflow/issues/35030

**Comment by HadiSDev** [comment] 2020-03-04 12:51
It gets worse when I use concatenated images where it is 320px * 4 in width.

**Comment by gowthamkpr** [comment] 2020-03-05 05:11
Yes @HadiSDev Looks like it is indeed duplicate of #35030

**Comment by gowthamkpr** [comment] 2020-03-06 19:50
Did you try using the latest tf-nightly version i.e., 2.2dev0 @HadiSDev ?

**Comment by HadiSDev** [comment] 2020-03-07 22:29
I was going to try but when I try to import tensorflow i get:
```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 48, in <module>
    from ._api.v2 import compat
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py", line 39, in <module>
    from . import v1
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 34, in <module>
    from . import compat
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 39, in <module>
    from . import v1
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 673, in <module>
    _module_dir = _module_util.get_parent_dir_for_name(_estimator_module)
  File "/home/hadi/.local/lib/python3.7/site-packages/tensorflow/python/tools/module_util.py", line 62, in get_parent_dir_for_name
    if not spec.origin:
AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by gowthamkpr** [comment] 2020-05-14 05:21
@HadiSDev Can you try reinstalling tensorflow 2.2.0 and let me know if the issue still persists. Thanks!

**Comment by gowthamkpr** [comment] 2020-05-28 00:29
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!

**Closed by gowthamkpr** 2020-05-28 00:29 UTC
Labels: TF 2.1, comp:keras, stalled, stat:awaiting response, type:performance
