### ISSUE TITLE
An exception has occurred, use %tb to see the full traceback.

### ISSUE THREAD

**Issue by bidhouilles** [tensorflow/tensorflow#21742] opened 2018-08-20 20:31 UTC
### System information
- I copied/pasted the classify_image.py
- window 10 64 bits
- anaconda 64 bits / anaconda navigator 1.8.7 / spyder 3.3.1
- TensorFlow version 1.10 installed form anaconda/python prompt
- **Python version**: 3.5 spyder (installed 3.7)

Hello guys,

I opened classify_image.py in spyder from the master of tensorflow (cloned on my PC before), When I executed the script I have this  message:
![classify](https://user-images.githubusercontent.com/17961650/44364942-9a10b200-a4c8-11e8-9edc-04fd48fb0d60.jpg)

"""""""""""""""""""
runfile('E:/developpements/tensorflow_projects/models-master/tutorials/image/imagenet/classify_image.py', wdir='E:/developpements/tensorflow_projects/models-master/tutorials/image/imagenet')
giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca (score = 0.89632)
indri, indris, Indri indri, Indri brevicaudatus (score = 0.00766)
lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens (score = 0.00266)
custard apple (score = 0.00138)
earthstar (score = 0.00104)
An exception has occurred, use %tb to see the full traceback.

SystemExit

E:\developpements\anaconda\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2969: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
"""""""""""""""""""""

(tensorflow) C:\Users\david>python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0

thanks,

David.

**Comment by tensorflowbutler** [comment] 2018-08-21 06:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-04 19:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-19 12:47
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment] 2018-09-27 19:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-09-27 19:03 UTC
Labels: stat:awaiting response

**Comment by tahirashehzadi** [comment] 2019-02-25 16:13
When I executed the script I have this message:
![p1](https://user-images.githubusercontent.com/47982518/53350986-3337df80-38d5-11e9-8073-a1a3b7b26153.PNG)
master\p1.PNG
               [C:\Users\Tahira Shehzadi\Desktop\Master\semester1\MLCS\Image-Super-Resolution-master\p1.PNG ...]
main.py: error: the following arguments are required: C:\Users\Tahira Shehzadi\Desktop\Master\semester1\MLCS\Image-Super-Resolution-master\p1.PNG
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\Tahira Shehzadi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2969: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by Ruhan123** [comment] 2019-07-17 09:02
can any one help me  how  to remove  this error An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by 72ohit** [comment] 2019-11-09 11:31
"parser = argparse.ArgumentParser(description='Code for Changing the contrast and brightness of an image! tutorial.')
parser.add_argument('--input', help='Path to input image.', default='id1.jpg')
args = parser.parse_args()"    remove this part and replace this code (image = cv.imread(cv.samples.findFile(args.input))) to image = cv.imread("your_image_path")

**Comment by Pratyusha23** [comment] 2019-11-28 10:31
@72ohit this does not solve the error. Did you figure out why the error is occurring due to parse_args()?

**Comment by Krishna-Aditya** [comment] 2020-02-18 07:08
> can any one help me how to remove this error An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit: 2

python my_programme.py --arg1=5 --arg2=7

**Comment by ronakkjain** [comment] 2020-03-24 05:18
just put square brackets in [-arg], [--arg2]
ap = argparse.ArgumentParser()
ap.add_argument(["-i"],["--image"],required = True,
               help = "Path to the image to be scanned")
args = vars(ap.parse_args())

**Comment by AbdelfattahMohamed** [comment] 2020-04-21 02:12
can anyone help me ?
my error:
the following arguments are required: -i/--images/example_test.png
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by hasanaltariq** [comment] 2020-09-01 17:05
the function takes -i and image_name as argument. So to run the app you need to type on the console: 
python color_detection.py -i colorpic.jpg

**Comment by Hemanthkumar2112** [comment] 2021-03-19 10:06
use 
app.run(debug=True, use_reloader=False)

**Comment by woneuy01** [comment] 2021-03-23 05:53
https://community.plotly.com/t/dash-pythonanywhere-deployment-issue/5062

**Comment by krishnadfs** [comment] 2021-05-09 06:40
> ### System information
> * I copied/pasted the classify_image.py
> * window 10 64 bits
> * anaconda 64 bits / anaconda navigator 1.8.7 / spyder 3.3.1
> * TensorFlow version 1.10 installed form anaconda/python prompt
> * **Python version**: 3.5 spyder (installed 3.7)
> 
> Hello guys,
> 
> I opened classify_image.py in spyder from the master of tensorflow (cloned on my PC before), When I executed the script I have this message:
> ![classify](https://user-images.githubusercontent.com/17961650/44364942-9a10b200-a4c8-11e8-9edc-04fd48fb0d60.jpg)
> 
> """""""""""""""""""
> runfile('E:/developpements/tensorflow_projects/models-master/tutorials/image/imagenet/classify_image.py', wdir='E:/developpements/tensorflow_projects/models-master/tutorials/image/imagenet')
> giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca (score = 0.89632)
> indri, indris, Indri indri, Indri brevicaudatus (score = 0.00766)
> lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens (score = 0.00266)
> custard apple (score = 0.00138)
> earthstar (score = 0.00104)
> An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit
> 
> E:\developpements\anaconda\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2969: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
> warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
> """""""""""""""""""""
> 
> (tensorflow) C:\Users\david>python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
> b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0
> 
> thanks,
> 
> David.

Hi 
I am also facing the same issue. Can you please share the solution. 

Regards,
Krishna

**Comment by antonasiri** [comment] 2021-07-19 01:34
> use
> app.run(debug=True, use_reloader=False)

It worked for me, tnx a lot.

**Comment by besmaGuesmi** [comment] 2021-08-17 11:48
I have the same problem: `usage: get_frozen_graph.py [-h] --checkpoint CHECKPOINT
                           [--out_graph_name OUT_GRAPH_NAME]
get_frozen_graph.py: error: the following arguments are required: --checkpoint
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2` could you please tell me how can I use `app.run(debug=True, use_reloader=False)` in my code

**Comment by RahulGhu** [comment] 2021-12-10 19:31
> > use
> > app.run(debug=True, use_reloader=False)
> 
> It worked for me, tnx a lot.

it showing error like app no define . i tried other things but not solve error ..plzz suggest .

**Comment by fath9010yasar** [comment] 2022-02-14 10:43
I have the same problem: usage: untitled1.py [-h] video
untitled1.py: error: the following arguments are required: video
An exception has occurred, use %tb to see the full traceback.
could you please tell me how can I use app.run(debug=True, use_reloader=False) in my code

**Comment by Dr-Olami** [comment] 2022-04-04 11:54
use
 app.run_server(debug=True, use_reloader=False)
