### ISSUE TITLE
cuda 7.5 // AttributeError: type object 'NewBase' has no attribute 'is_abstract'

### ISSUE THREAD

**Issue by aabramovrepo** [tensorflow/tensorflow#2016] opened 2016-04-19 08:54 UTC
Hello everyone,

   have the following problem after the tensorflow installation via pip:

`>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 94, in <module>
    from tensorflow.python.platform import test
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 62, in <module>
    from tensorflow.python.framework import test_util
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/test_util.py", line 41, in <module>
    from tensorflow.python.platform import googletest
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 112, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 107, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'`

I'm using Nvidia GTX Titan X (comp. capability 5.2) and CUDA 7.5. Does anybody have an idea?

Many thanks in advance for your help!

Cheers,
A

**Comment by mrry** [comment] 2016-04-19 09:18
This looks like the same issue as #1965, so I'm closing this issue as a duplicate. (On the other thread, somebody suggested upgrading the `six` library to fix this problem.)

**Closed by mrry** 2016-04-19 09:18 UTC

**Comment by aabramovrepo** [comment] 2016-04-19 10:36
this does not help... that's why I have posted this issue. I have updated Six library, but still have the same problem...

**Comment by mrry** [comment] 2016-04-19 13:24
That's a pity - can you comment on the other issue with the version of Six you're using, to help narrow down the cause (since the underlying error is the same).

**Comment by yhlleo** [comment] 2016-04-28 07:51
I met it, too. If you have solved this problem, would you like to provide the solution on this website? Thank you very much!

**Comment by yhlleo** [comment] 2016-04-29 10:07
I solved this problem by reinstall the package six:
`sudo pip uninstall six`
`sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"`
You can check the path of `python2.7/dist-packages`, and have a try.

**Comment by PierreGe** [comment] 2016-05-14 19:27
I solved this problem on mac osx doing this : 
`python`
`import six`
Then we localize the package six:
`>>> six.__file__`
`'/Library/Python/2.7/site-packages/six.pyc'`
Then we upgrade the concerned package 
`sudo pip install six --upgrade --target="/Library/Python/2.7/site-packages/"`

**Comment by petulla** [comment] 2016-06-04 23:39
I resolved this by uninstalling and reinstalling six -- without needing to flag a target.

**Comment by mayank-kgp** [comment] 2016-11-15 09:57
@petulla  @PierreGe  @yhlleo 
I have tried all the solution. But I am facing same error.
I am using six - 1.10.0

**Comment by mayank-kgp** [comment] 2016-11-15 10:23
It worked after sudo pip install six --upgrade --target="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"

**Comment by yhlleo** [comment] 2016-11-15 11:08
It may be a version problem. You can check the version of `six`:
`>> pip --version`
`>> pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)`

The `1.10.0` version may be too old. @mayank-kgp

**Comment by dearLilian** [comment] 2017-11-03 03:14
Hi, It didn't work by doing uninstall and reinstall six..Because, my six is already the newest version.

**Comment by mayank-kgp** [comment] 2017-11-03 06:13
Hi @dearLilian , If it is not working for you then you can use Anaconda. One of my friends was not able to resolve this error so he installed Anaconda.

**Comment by dearLilian** [comment] 2017-11-03 06:58
Ok, thanks for you answer.
