### ISSUE TITLE
tf.rank returns incorrect value in trace-compiled conditional when a SparseTensor is involved

### ISSUE THREAD

**Issue by sgrabli** [tensorflow/tensorflow#54790] opened 2022-03-01 22:55 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.9
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.7.7
- CUDA/cuDNN version: CUDA 11.2.152 / cuDNN 8.1.1
- GPU model and memory: GeForce RTX 2080 Ti 11GBytes

**Describe the current behavior**
`tf.rank()` returns the wrong value (at runtime) when used for conditional branching in trace-compiled code and when one of branches involves a `SparseTensor`.
Specifically, `tf.rank(v)` returns `2` for a tensor `v` of shape `(2,10,3)` when called as part of a conditional test, when one of the execution branches runs `tf.sparse.sparse_dense_matmul(L,v)` where `L` is a sparse matrix and `v` is a dense tensor.

**Describe the expected behavior**
In this scenario, I would expect `tf.rank(v)` to return `3` for a tensor `v` of shape `(2,10,3)`.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

@tf.function(input_signature=[
    tf.SparseTensorSpec(shape=(None,None), dtype=tf.float32),
    tf.TensorSpec(shape=None, dtype=tf.float32)
])
def f(L,v):
    tf.print("runtime: tf.rank(v) = ", tf.rank(v))
    tf.print("runtime: tf.shape(v) = ", tf.shape(v))
    if (tf.rank(v) == 2):
        return tf.sparse.sparse_dense_matmul(L, v)
    else:
        return v[0,0,0] * v
        
L = tf.sparse.from_dense(tf.eye(10,dtype=tf.float32))
f(L,tf.ones((2,10,3), dtype=tf.float32))
```
The code above prints:
```
runtime: tf.rank(v) =  2
runtime: tf.shape(v) =  [2 10 3]
```
Because `tf.rank` returns the wrong value, the wrong branch is executed and results in the Traceback below.
Note that if `L` is a dense matrix then `tf.rank` returns the correct result and the correct branch is executed -- here is a version of the code above with this modification:
```
import tensorflow as tf

@tf.function(input_signature=[
    tf.TensorSpec(shape=(None,None), dtype=tf.float32),
    tf.TensorSpec(shape=None, dtype=tf.float32)
])
def f(L,v):
    tf.print("runtime: tf.rank(v) = ", tf.rank(v))
    tf.print("runtime: tf.shape(v) = ", tf.shape(v))
    if (tf.rank(v) == 2):
        return tf.matmul(L, v)
    else:
        return v[0,0,0] * v
        
L = tf.eye(10,dtype=tf.float32)
f(L,tf.ones((2,10,3), dtype=tf.float32))
```

**Other info / logs**
Traceback obtained when running the first code example above:
```
runtime: tf.rank(v) =  2
runtime: tf.shape(v) =  [2 10 3]
Traceback (most recent call last):
  File "tmp/tf_cond.v3.py", line 16, in <module>
    f(L,tf.ones((2,10,3), dtype=tf.float32))
  File "/lucas/ilm/dept/rnd/home/sgrabli/src/fluxml/venv/lib64/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/lucas/ilm/dept/rnd/home/sgrabli/src/fluxml/venv/lib64/python3.7/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Tensor 'b' is not a matrix
         [[node cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul
 (defined at tmp/tf_cond.v3.py:11)
]] [Op:__inference_f_61]

Errors may have originated from an input operation.
Input Source operations connected to node cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul:
In[0] cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul/L:
In[1] cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul/L_1:
In[2] cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul/L_2:
In[3] cond/SparseTensorDenseMatMul/SparseTensorDenseMatMul/v:

Operation defined at: (most recent call last)
>>>   File "tmp/tf_cond.v3.py", line 16, in <module>
>>>     f(L,tf.ones((2,10,3), dtype=tf.float32))
>>> 
>>>   File "tmp/tf_cond.v3.py", line 10, in f
>>>     if (tf.rank(v) == 2):
>>> 
>>>   File "tmp/tf_cond.v3.py", line 11, in f
>>>     return tf.sparse.sparse_dense_matmul(L, v)
>>> 

Function call stack:
f -> cond_true_30
```

**Comment by sushreebarsa** [comment] 2022-03-03 14:06
@sgrabli I tried to  replicate the issue on colab using TF v2.8.0 , and faced different outcome.Could you please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/31fc4d6b3204bc2fa5884470d6ac4dfc/54790.ipynb)and  confirm the same?Thanks!

**Comment by sgrabli** [comment] 2022-03-03 17:04
@sushreebarsa , thanks for taking a look.
I ran your colab and got the same incorrect result I observed on my end:
![image](https://user-images.githubusercontent.com/10070473/156614236-c9f53204-67e2-4338-bfe8-776ecfc149c2.png)

**Comment by sushreebarsa** [comment] 2022-03-07 07:36
@gadagashwini  I was able to reproduce the issue on colab using TF v2.8.0 and tf-nightly ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/31fc4d6b3204bc2fa5884470d6ac4dfc/54790.ipynb#scrollTo=dgx37EQmTQJS).Thanks!

**Comment by tomytsai1** [comment] 2022-09-20 01:12
Hi,
The cause of this problem is due to the behavior of condition tracing in TensorFlow: the same input is applied to both true and false sides for graph tracing, when the condition is based on a non-static value (i.e. `tf.rank(v) == 2`). 

To fix this, we can change the condition to use static value instead: `v.shape.ndims == 2`. With this, tf.function still re-traces when the input (v) shape changes, to generate the graph corresponding to that rank, so it gives the correct result.

Let me know how it works.

**Comment by tomytsai1** [comment] 2022-09-23 17:58
Closing this issue. Let us know if you see any further problems.

**Closed by tomytsai1** 2022-09-23 17:58 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, TF 2.7

**Comment by danielenricocahall** [comment] 2022-10-12 17:44
Just wanted to mention this here since I recently answered a similar [SO](https://stackoverflow.com/questions/74044292/if-else-statement-returns-both-in-tf-cuntion) question, for the case of checking `tf.rank`, since it returns a 0-D Tensor (https://www.tensorflow.org/api_docs/python/tf/rank), you could evaluate the value using `tf.rank(t).numpy()` or `tf.get_static_value(tf.rank(t))` in the `tf.function` to ensure both sides of the conditional aren't traced.
