### ISSUE TITLE
TFLite No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int)

### ISSUE THREAD

**Issue by wosiu** [tensorflow/tensorflow#31114] opened 2019-07-28 15:14 UTC
**System information**
- OS Platform and Distribution: Android 5.1.1, API 22
- Mobile device: Xiaomi Redmi 3
- TensorFlow installed from: official binary
- TensorFlow version : tensorflow-lite:1.14.0

**Describe the current behavior**
Tensorflow-lite 1.13.1 works fine on all devices I tested. Whereas tensorflow-lite 1.14.0 is broken for Xiaomi Redmi 3 (Android 5.1.1, API 22), other devices are ok.
I get a runtime error when `Interpreter` is created.

**Describe the expected behavior**
No error.

**Code to reproduce the issue**
```
interpreter = new Interpreter(tfliteModel, null);
```

**Other info / logs**
```
W/linker: /data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so: unused DT entry: type 0x6ffffffe arg 0x2020
    /data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so: unused DT entry: type 0x6fffffff arg 0x3
E/art: dlopen("/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so"...
W/System.err: TensorFlowLite: failed to load native library: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so"...
W/linker: /data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so: unused DT entry: type 0x6ffffffe arg 0x2020
    /data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so: unused DT entry: type 0x6fffffff arg 0x3
E/art: dlopen("/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so"...
W/System.err: TensorFlowLite: failed to load native library: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/eu.yesse.readerdemo.debug-2/lib/arm64/libtensorflowlite_jni.so"...
E/art: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.yesse.readerdemo.debug, PID: 12710
    java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
        at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:58)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
        at eu.yesse.reader.commons.internal.detector.BlockingCornersClassSingleDetector.<init>(BlockingCornersClassSingleDetector.java:76)
        at eu.yesse.reader.commons.internal.detector.BlockingCornersClassMultiDetector.<init>(BlockingCornersClassMultiDetector.java:25)
        at eu.yesse.reader.commons.shared.detector.AsyncCornersClassMultiDetectorImpl.<init>(AsyncCornersClassMultiDetectorImpl.java:36)
        at eu.yesse.reader.tempregdoc.internal.TempRegDocReaderManager.createDetector(TempRegDocReaderManager.java:79)
        at eu.yesse.reader.tempregdoc.internal.TempRegDocReaderManager.<init>(TempRegDocReaderManager.java:48)
        at eu.yesse.reader.TempRegDocReader.getReader(TempRegDocReader.java:20)
        at eu.yesse.readerdemo.activities.TempRegDocActivity.onCreate(TempRegDocActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5296)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by anonym24** [comment] 2019-07-29 06:55
did you solve it?

Firebase crashlytics reports this issue for Android 5 users of my app

I've added Tensorflow like this:

    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'

`Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)`

**Comment by wosiu** [comment] 2019-07-29 10:44
>Did you solve it?

@anonym24 nope :( I guess we can't do much about it without a fix in tf. BTW I guess you should not put both `org.tensorflow:tensorflow-lite` and `org.tensorflow:tensorflow-lite-gpu` in your gradle file at the same time. But that's not the issue here anyway...

**Comment by anonym24** [comment] 2019-07-29 11:07
@wosiu yes, we need them both: https://www.tensorflow.org/lite/performance/gpu

![image](https://user-images.githubusercontent.com/8851301/62043870-2fa0df80-b20a-11e9-9c14-d56096189366.png)

**Comment by anonym24** [comment] 2019-07-29 13:37
@wosiu 
in my case, yes:

![image](https://user-images.githubusercontent.com/8851301/62052901-29692e00-b21f-11e9-8b3a-fee666ab05f1.png)

**Comment by anonym24** [comment] 2019-08-05 12:28
Does it work fine with 1.13.1?

How can I use it with GPU?

    implementation 'org.tensorflow:tensorflow-lite:1.13.1'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'

Will it work?

**Comment by wosiu** [comment] 2019-08-07 01:21
@liyunlu0618 are there any updates on that?

**Comment by ProgrammerYuan** [comment] 2019-08-23 10:07
I also encounter this problem, I resolve this by reconfigure my ndk abifilter settings. My project originally was only built for 'armeabi' architecture. When I add any other abi options, it works like a charm. However, I'm still confused because on the tutorial page of Tensorflow Lite, it says that the library support all kinds of architecture(which should include armeabi). Or is it because arm support was removed in ndk r17? Hope someone can help me to find a workaround for tflite to run on armeabi devices.

**Comment by ramjiv31989** [comment] 2019-09-06 03:02
Did anyone find solution for this? I am also facing the same issue.
I tested in Oneplus3.
2019-09-06 08:28:18.799 15233-15233/ai.fritz.tflitedemo E/ritz.tflitedem: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
2019-09-06 08:28:18.802 15233-15233/ai.fritz.tflitedemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.fritz.tflitedemo, PID: 15233
    java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
        at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)

Gradle:
   implementation 'org.tensorflow:tensorflow-lite:0.1.2-nightly'
    implementation 'org.tensorflow:tensorflow-lite:0.1'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'

**Comment by hsiaoer** [comment] 2019-09-19 14:03
Any update on this? I'm also facing the same issue on 1.14.0

**Comment by runnableapps** [comment] 2019-09-21 15:53
I'm also got this crash

**Comment by kongaskristjan** [comment] 2019-09-23 10:15
I had a similar issue from NDK, namely that arm64 Android 5.x devices failed to load the shared library libtensorflowlite.so because of __register_atfork being missing.

The problem is that for at least arm64, __register_atfork usage is somehow generated in the shared library, but [this function is introduced in Android 6](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md). As suggested in the link, I tried compiling with lower NDK target API level, but this didn't seem to help. I also tried searching for "atfork" in tensorflow lite's source code, but couldn't find any.

**Workaround for at least NDK users:** Disassembling libtensorflowlite.so left an impression that __register_atfork is only called while reporting errors, so at least theoretically it shouldn't be called in production anyway. The workaround was thus to introduce fake __register_atfork() declaration and definition in cpp and h files, so that linker wouldn't complain anymore. So I put

```
extern "C" {
    int __register_atfork(void (*prepare) (void), void (*parent) (void), void (*child) (void), void *__dso_handle);
}
```

into tensorflow/lite/util.h, and

```
#include <cassert>
extern "C" {
    int __register_atfork(void (*prepare) (void), void (*parent) (void), void (*child) (void), void *__dso_handle) {
        assert(0 && "Using dummy __register_atfork(). This is dangerous, so asserting.");
        return 0; // Avoid warning
    }
}
```

into tensorflow/lite/util.cc (the exact files aren't important, the definition just has to be compiled and linked to libtensorflowlite.so) and recompiled. After that neural networks seem to work fine on all devices. I guess something similar should work for JNI users as well.

**Comment by FunmiKesa** [comment] 2019-10-19 12:40
I had the same issue. I fixed it by adding 
        ```
ndk {
            abiFilters "armeabi-v7a", "x86"
        }
```
to the app build.gradle file.

**Comment by wosiu** [comment] 2019-10-19 13:31
@kongaskristjan and @FunmiKesa - big thanks for investigating and sharing that! Said that, I feel propsed changes are more like workarounds and not solutions. It still would be nice to have a fix inside the tensorflow lib.

**Comment by jdduke** [comment] 2019-11-15 22:05
Hi all, apologies for the delayed response, just now seeing this issue.

We set our Android NDK API level to 18 when building, but it's possible there's something wrong with the config and it's assuming API 23. I'll take a look.

**Comment by jdduke** [comment] 2019-11-19 16:42
This is fixed in the latest nightly, and we'll try to pull the fix in to the 2.1 release (https://github.com/tensorflow/tensorflow/pull/34419). Thanks again for your patience.

**Closed by jdduke** 2019-11-19 16:42 UTC
Labels: TF 1.14, comp:lite, type:bug

**Comment by hsiaoer** [comment] 2019-11-19 17:19
Hi @jdduke , thanks for the fix. Just to understand how we can resolve this issue on android, would we be able to pull in the nightly build of TFL in gradle and have this fixed

```
dependencies: {
     implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
}
```

or do we have to also reconvert our models to TFL using the nightly build?

**Comment by wosiu** [comment] 2019-11-19 17:22
@jdduke are you going to backport the fix to 1.* version?

**Comment by jdduke** [comment] 2019-11-19 17:31
There won't be any backport, however, you can safely use the latest 2.x or nightly version with both 1.X and 2.X TF models.

**Comment by runnableapps** [comment] 2019-11-19 22:03
Hello @jdduke, please show me what I need to put in gradle.build to use latest fix

**Comment by wosiu** [comment] 2019-11-19 22:33
@runnableapps 
Answer:
```
dependencies: {
     implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
}
```
or wait for `2.1` release.

**Comment by runnableapps** [comment] 2019-11-21 10:12
implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
does not fix crash

**Comment by jdduke** [comment] 2019-11-21 17:30
You might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache). I've manually inspected the [nightly build](https://bintray.com/google/tensorflow/tensorflow-lite#files/org%2Ftensorflow%2Ftensorflow-lite%2F0.0.0-nightly) and verified that `__register_atfork` is no longer referenced. There might be another issue with your usage, in which case please attach the log from adb.

**Comment by alexeyvasilyev** [comment] 2019-12-21 11:25
Got the same problem with org.tensorflow:tensorflow-lite:2.0.0
Device T8-PLUS, Android 5.1

**Comment by jdduke** [comment] 2019-12-26 18:21
@alexeyvasilyev the fix did not make it into 2.0, but it will be in the upcoming 2.1 release (expected to be finalized soon). In the meantime, please try the nightly build.

**Comment by mabdullahrafique** [comment] 2020-01-09 11:45
@jdduke Thanks. Lets hope nightly build can sort out this issue in android 5.

**Comment by jdduke** [comment] 2020-01-09 18:06
The 2.1 release is now available (`org.tensorflow:tensorflow-lite:2.1.0`), please give it a try.

**Comment by wosiu** [comment] 2020-01-10 05:07
I confirm - 2.1.0 works on the device I originally issued the problem with :)
