### ISSUE TITLE
sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#26097] opened 2019-02-25 18:32 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-  OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS - docker images tensorflow/tensorflow:latest and tensorflow/devel
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit a2bb5db1bf7931b0dc2cd08e53b8798489568198
- Python version: Python 2.7.12
- Installed using virtualenv? pip? conda?: sources
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Some of the tests don't compile because of the incorrect order of parameters and cause the following error: 
`sorry, unimplemented: non-trivial designated initializers not supported`

Problem is caused by the order in designated initializer which is different from the order in struct.

How should be tensorflow tested so that this test passes? It even doesn't pass on official Google tensorflow images.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test --config=opt --test_size_filters=small,medium -- tensorflow/lite/toco/tflite:operator_test

**Any other info / logs**

**Comment by herbakamil** [comment] 2019-03-04 10:01
@jianlijianli you've recently worked on this code. Is it tested on some internal Google compiler which behaves differently form gcc on official TF docker image?

**Comment by jvishnuvardhan** [comment] 2019-03-04 22:38
@herbakamil I am closing this as this is a duplicate of #26097. We will resolve in the other issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-04 22:38 UTC
Labels: comp:lite, type:bug/performance
