### ISSUE TITLE
Erroneously triggering tf.function retracing warnings when rapidly creating new TF models.

### ISSUE THREAD

**Issue by PaulPauls** [tensorflow/tensorflow#42441] opened 2020-08-17 22:01 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04, Google Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): occurs in v2.3.0 and tf-nightly v2.4.0a20200817; NOT in v2.2.0
- Python version: 3.7.7

**Related Issues**
- https://github.com/tensorflow/tensorflow/issues/34025
- https://github.com/tensorflow/tensorflow/issues/38561

**Describe the current behavior**
The function retracing warning (see below) is triggered constantly when creating multiple independent models. Similar bugs occured recently in the above mentioned issues, though while those occur when doing rapid predictions on the same model does this bug occur solely when creating and predicting multiple new models rapidly (which is necessary e.g. for TF evolutionary frameworks). The tf.function retracing warning is triggered after the creation of the first 5 models. The bug occurs in v2.3.0 and todays tf-nightly, though not in v2.2.0. I attempted workarounds mentioned in previous issues (setting `experimental_relax_shapes` to True, disabling eager execution and setting `step` to 1), though none worked. I also attempted to provide fixed input shape and batch_size as mentioned in the warning message, though this was also unsuccessful. 
While I am no expert in tf.function does it seem to me that the counter to trigger the warning seems to be a global variable and not seperate for each model, therefore triggering the warning that excessive retracings for the current model occured even though it was only fast consecutive initial retracing for each one of multiple models. Just a hunch though.

Exact warning message:

> WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f3c67c45a60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

**Standalone code to reproduce the issue**

```
import numpy as np
import tensorflow as tf

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

for i in range(50):
    tf.print(f'Model {i}...')

    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(units=2))
    model.add(tf.keras.layers.Dense(units=1))

    prediction = model.predict(x)
```

Google colab reproducing code: https://colab.research.google.com/drive/1QLFNCDWw37x6kP2AajB4g3Lidn1oLRx7?usp=sharing

**Comment by ravikyram** [comment] 2020-08-18 09:07
@PaulPauls 

I have tried in colab with TF 2.3.0 and nightly version(`2.4.0-dev20200817`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e1a45329766517a33e5783fd40d3a750/untitled259.ipynb).Thanks!

**Comment by nikitamaia** [comment] 2020-08-18 18:54
Hi @PaulPauls, to clarify, for your use case you _are_ expecting retracing to happen on each pass through the loop? This is because you're using a different model each time, correct? If so, it seems different to me compared the issues you've linked to, where they were trying to prevent extra retraces from happening on each pass through the loop. So I'm not sure the warnings are too unexpected since most of the time you would want to prevent excessive retracing.

Have you tried using `model.predict_step()` instead of `model.predict`? predict is a high-level end point that manages its own tf.function, so I think you're seeing the warning because you're falling into case (1). predict_step is just the logic of an inference step and shouldn't trigger the warning.

**Comment by PaulPauls** [comment] 2020-08-18 21:33
Hi @nikitamaia, thank you for your response. I am no expert in function retracing, though my understanding is that due to the functional way TF allows for model creation does TF also retrace the whole model graph the first time it is called to ensure that it is correctly generated. I therefore _do_ expect retracing to happen once for each model when it is predicting for the first time - that is correct.

However, because I consider this normal behaviour am I confused from the warning. If functionally each model works fine and is not retraced multiple times and TF only displays this warning because it keeps track of model retracings globally (and not per model), then everything is resolved from my side. I do disagree with the decision to track model retracing globally and not per model (as it triggers the unnecessary warning when multiple models are created in a short time, even though everything is in order), though this then would be a deliberate developer decision and not a bug. I however would suggest to adjust the warning message accordingly, as the warning references a single model instance for which the warning is displayed and doesn't refer to global tracking of model retracings (therefore making me think something went wrong with my models).

I did link the related issues as according to the warning message I assumed that somehow through the creation of multiple models in a short time multiple function retracings occured for a single model. This would make the problem similar to the ones discussed in the related issues. At the time it was only a possible assumption that TF tracks function retracings globally.

**Comment by nikitamaia** [comment] 2020-08-24 18:36
Closing this issue now since it seems to be expected behavior and a workaround was found.

**Closed by nikitamaia** 2020-08-24 18:36 UTC
Labels: TF 2.3, comp:core, comp:keras, type:bug

**Comment by purpleyun** [comment] 2020-11-04 07:12
tf2.1.0: predict --> predict_on_batch

**Comment by sehoffmann** [comment] 2021-03-23 14:33
This "workaround" is not applicable to me, as I want to rely on the functionality of `predict()` (in particular its conversion to a graph-based model). The original author is completely right, that warnings should only trigger for the same model.

**Comment by nikitamaia** [comment] 2021-03-23 15:52
Any progress on suppressing these warnings will be tracked in #43555. Please check in there for updates.
