### ISSUE TITLE
tf.estimator.Estimator with distribution strategy messes up TensorBoard readability

### ISSUE THREAD

**Issue by patzm** [tensorflow/tensorflow#22058] opened 2018-09-04 17:36 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.12.0
- **Python version**: 2.7
- **Bazel version**: N/A
- **Mobile device**: N/A
- **CUDA/cuDNN version**: cuda-9-0 / libcudnn.so.7
- **GPU model and memory**: 2x NVIDIA T4, 16GB
- **Exact command to reproduce**: example provided here: https://github.com/patzm/tf-estimator-distribute-so

### Describe the problem
Using a `tf.estimator.Estimator` with a distribution strategy like `OneDeviceStrategy` or `MirroredStrategy` creates a lot of tensors / operations that are not enclosed in a common scope.
If one views the graph in TensorBoard, it is very annoying.
TensorBoard automatically zooms out until all nodes are visible, making everything so tiny and unreadable.
Also TensorBoard becomes pretty slow.
In essence this is the
```python
    run_config = tf.estimator.RunConfig(
        model_dir='/tmp/some/dir',
        session_config=session_config,
        train_distribute=MirroredStrategy(num_gpus=2),  # or OneDeviceStrategy(device)
        save_summary_steps=1,
        save_checkpoints_steps=1e4,
    )

    estimator = tf.estimator.Estimator(
        model_fn=model_fn,
        config=run_config,
        params={},
    )
```
Here are two example images:

* `OneDeviceStrategy`:
  
  ![OneDeviceStrategy](https://raw.githubusercontent.com/patzm/tf-estimator-distribute-so/master/images/OneDeviceStrategy.png)

* `MirroredStrategy`:

  ![MirroredStrategy](https://raw.githubusercontent.com/patzm/tf-estimator-distribute-so/master/images/MirroredStrategy.png)

The row / column of `Read_<num>` / `group_deps_<num>` nodes continues way beyond the area of the screenshot.
The initial view of the TensorBoard could look like this, with the nodes almost invisible, because they are so tiny:
![TensorBoardInitialView](https://i.imgur.com/iuhxLCK.png)

### Source code / logs
example provided here: https://github.com/patzm/tf-estimator-distribute-so
I also raised the issue on StackOverflow: https://stackoverflow.com/questions/50924287/how-to-influence-the-name-scope-of-collated-variables-slots

**Comment by karmel** [comment] 2018-09-05 18:26
@yuefengz , can you take a look?

**Comment by patzm** [comment] 2018-09-19 15:33
any news on this? If you point me to the right direction, I can also do some debugging :slightly_smiling_face:

**Comment by karmel** [comment] 2018-09-20 19:51
@yuefengz , can you comment/advise here?

**Comment by tensorflowbutler** [comment] 2018-10-21 19:03
Nagging Assignees @yuefengz, @seemuch: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-05 18:59
Nagging Assignees @yuefengz, @seemuch: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-05 19:00
Nagging Assignees @yuefengz, @seemuch: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Jasonnor** [comment] 2018-12-18 02:08
Same problem, It made me difficult to read graphs of tensorboard. Any solution here? 😞

**Comment by ustcyue** [comment] 2018-12-19 03:52
same here, will it be fixed in the next release?

**Comment by jvishnuvardhan** [comment] 2019-02-13 22:14
@patzm is this still an issue? Could you load TF 1.12 (stable) or latest version and check whether the issue persists? It is be good if you can share a simplified code to reproduce the issue. If it was solved by newer version, please close the issue. Thanks!

**Comment by patzm** [comment] 2019-02-18 10:43
@jvishnuvardhan yes it still is an issue. I just tried it on TF 1.12 and got the same result. I already provided an example code in a repository I linked above. Here is the link again: https://github.com/patzm/tf-estimator-distribute-so
If you point me in the right direction, I am also motivated to contribute :smiley: And thanks for picking this up again!

**Comment by dsmilkov** [comment] 2019-02-19 18:36
I'm no longer working on TensorBoard. Can you reassign to someone from the TensorBoard team? Thanks!

**Comment by nfelt** [comment] 2019-02-19 22:18
There's a related tensorboard issue here: https://github.com/tensorflow/tensorboard/issues/403  I'm not sure if it's the exact same situation with Estimator (chains of conditionals) but the effect of many nodes in a long row that force a too-far-out initial zoom is the same.

As described here though, it would be ideal to fix this on the Estimator side by introducing some scope to contain these, since it's hard for TensorBoard to necessarily determine what makes sense to collapse automatically.  I'll leave our GitHub issue open for possible mitigations on our end (feel free to follow along there), but I'm unassigning myself from this issue because I'm not familiar enough with Estimator to know what we'd need to change on that side.

**Comment by bhack** [comment] 2019-02-19 22:28
@nfelt So, do you want to close this here and move on https://github.com/tensorflow/estimator if it is in the estimator perimeter?

**Comment by nfelt** [comment] 2019-02-19 22:57
Estimator doesn't have its own issue tracker, so this is still the right place for an issue asking for changes to Estimator.

**Comment by patzm** [comment] 2019-04-01 15:10
ping :-)

**Comment by karmel** [comment] 2019-04-02 00:48
The solution here is likely some combination of scoping in model_fn plus cleanup in the way dist strat and estimator replicate the graph. That said, we don't have the ability to look into this in the short term; opening up for contributions.

**Comment by patzm** [comment] 2019-04-02 07:33
I already tried my best to scope all variables well in the `model_fn`. I am certain that the not-well-scoped helper variables originate from the distribution strategy or the estimator graph replication.
I am motivated to contribute, if you can point me in the right direction.

**Comment by sushreebarsa** [comment] 2021-07-08 05:48
@patzm We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!

**Closed by sushreebarsa** 2021-07-08 05:48 UTC
Labels: comp:tensorboard, stat:contributions welcome, type:bug
