### ISSUE TITLE
Fail to build from source with gcc 7.3.1

### ISSUE THREAD

**Issue by mrodozov** [tensorflow/tensorflow#25323] opened 2019-01-30 15:47 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.5.1804 run as image under Singularity and/or Docker on Scientific Linux CERN SLC release 6.10 (Carbon)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: master, on commit 8eb3cbcb423c4d840e88a910c5db47404207b8a4
- Python version: 2.7
- Installed using virtualenv? pip? conda?: manually compiling using bazel
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): GCC 7.3.1
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
When compiling with gcc 7.3.1 rev 257125 (from gcc.gnu.org/svn) build chokes like this 
```
ERROR: /tensorflow/tensorflow/core/kernels/BUILD:3206:1: C++ compilation of rule '//tensorflow/core/kernels:reduction_ops' failed (Exit 1)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:124:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/kernels/reduction_ops_common.h:27,
                 from tensorflow/core/kernels/reduction_ops_sum.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Functor = Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tileable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >; bool Vectorizable = true; bool Tileable = false]::<lambda(Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex, Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex)>; _ArgTypes = {long int, long int}]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801:9: internal compiler error: in emit_move_insn, at expr.c:3698
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
         ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 74.923s, Critical Path: 51.44s
INFO: 2018 processes: 2018 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
exactly as described here:
https://github.com/sylabs/singularity/issues/2536
When we changed the 
gcc to 
8.2.0 tag 2d79333765b691fa27d82c1737cb2f00ec6a4499 (from https://github.com/gcc-mirror/gcc)
and to
7.4.0 rev 268351 (from gcc.gnu.org/svn)
the build went fine. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
export CXX_OPT_FLAGS=-std=c++11
BAZEL_OPTS="--output_user_root ../build build -s --verbose_failures -c opt --cxxopt=${CXX_OPT_FLAGS}"
BAZEL_EXTRA_OPTS="--action_env PYTHONPATH=${PYTHON27PATH} --distinct_host_configuration=false"
bazel $BAZEL_OPTS $BAZEL_EXTRA_OPTS //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2019-01-30 16:27
This might be gcc's fault, not Tensorflow's.

**Comment by lhelontra** [comment] 2019-02-18 17:09
With tf 1.12.0 works fine, but with tf 1.13.0-rc2 I got same issue in my project [tensorflow-on-arm](https://github.com/lhelontra/tensorflow-on-arm/)

**Comment by mrodozov** [comment] 2019-02-19 15:49
@lhelontra please see: https://github.com/tensorflow/tensorflow/issues/24318 and also https://docs.bazel.build/versions/master/command-line-reference.html
I'm trying this just now.

**Comment by lhelontra** [comment] 2019-02-20 19:06
@mrodozov works with gcc-8.2 only.

**Comment by mrodozov** [comment] 2019-02-22 10:36
@lhelontra for me it was working with 8.2 also without the extra flags, so local resources flags didn't help. it's something else (gcc 7.3.x related)

**Comment by lissyx** [comment] 2019-03-13 14:37
> @lhelontra for me it was working with 8.2 also without the extra flags, so local resources flags didn't help. it's something else (gcc 7.3.x related)

It looks like we are reproducing that with GCC 7.2 from Linaro as well. Looks to be confirmed as an upstream GCC issue: https://bugzilla.redhat.com/show_bug.cgi?id=1570308

**Comment by eLvErDe** [comment] 2019-03-19 08:24
Hello,

I can confirm TensorFlow cannot be built anymore on Debian Stable (Stretch) and Ubuntu LTS (Bionic) due to this "internal compiler error":

```
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Functor = Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tileable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >; bool Vectorizable = true; bool Tileable = false]::<lambda(Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex, Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, false>::StorageIndex)>; _ArgTypes = {long int, long int}]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801:9: internal compiler error: in emit_move_insn, at expr.c:3547
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
         ^~~~~~
```

Debian Stable comes with GCC 6.3 while Ubuntu LTS uses 7.3.

Regards,

**Comment by petertorelli** [comment] 2019-04-02 04:46
@mrodozov @lhelontra ... what flavor compiler are you using in the module list? I'm using gcc/g++ 8.2 from the ARM website and `/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/gcc` and I still get the error but on a different file/function (`internal compiler error: in emit_move_insn`), whilst on branch v1.13.1 (and bazel 0.19.0)

```
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function 'void Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::operator()(const DataMapper&, const LhsScalar*, const RhsScalar*, Index, Index, Index, Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar, Index, Index, Index, Index) [with LhsScalar = Eigen::half; RhsScalar = Eigen::half; Index = long int; DataMapper = Eigen::internal::blas_data_mapper<Eigen::half, long int, 0, 0>; int mr = 2; int nr = 4; bool ConjugateLhs = false; bool ConjugateRhs = false]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h:1879:3: internal compiler error: in emit_move_insn, at expr.c:3722
   }
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Comment by mrodozov** [comment] 2019-04-02 06:39
7.4 and 8.3 would do

**Comment by npanpaliya** [comment] 2019-04-02 14:39
Even with gcc 7.2, TF 2.0.0-alpha0 seems to be working. Not sure which TF commit has fixed the issue.

**Comment by petertorelli** [comment] 2019-04-02 22:39
@mrodozov I rebuilt gcc 8.3.0 from sources this morning (6hr compile time!) and still the same error. 

So now I've seen the error on TF v1.13.1 on my Ubuntu 16.04 AWS a4.xlarge compiling with native gcc 7.3.0, Linaro's generic gcc-8.2.0 (_Generic-AArch64_Ubuntu-16.04_aarch64-linux), and GCC's natively built 8.3.0. (And yes, I verified that the failing command is, in fact, using the correct compiler path). They all generate the same compiler error on the same line of code.

I suppose I could compile gcc 7.4.0, but I'm beginning to think this is not GCC issue. Would be great if you could make your 1.13.1 aarch64 wheel file available if you've been successful on multiple compilers.

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 

$ /usr/local/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/aarch64-unknown-linux-gnu/8.3.0/lto-wrapper
Target: aarch64-unknown-linux-gnu
Configured with: ./configure
Thread model: posix
gcc version 8.3.0 (GCC) 

$ /opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/gcc
COLLECT_LTO_WRAPPER=/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/../libexec/gcc/aarch64-linux-gnu/8.2.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix /tmp/plgbuild/abs_build/761279_27578/trunk/rel_work/arm_builder/components/builder/work/current_tree/AArch64/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux --enable-languages=c,c++,go,fortran --disable-multilib --enable-lto --disable-werror --enable-stage1-checking --enable-checking=release --with-build-config=bootstrap-debug --enable-plugins --enable-gnu-indirect-function --target aarch64-linux-gnu --host aarch64-linux-gnu --enable-multiarch --with-build-sysroot=/tmp/plgbuild/abs_build/761279_27578/trunk/rel_work/arm_builder/components/builder/roots/armada/SysRoots/Ubuntu/Ubuntu_16.04_aarch64.rootfs --with-pkgversion=ARM-build-7
Thread model: posix
gcc version 8.2.0 (ARM-build-7) 
```

**Comment by ariesadel** [comment] 2019-04-04 20:20
We also run into the same problem trying to compile TensorFlow in our CentOS 7 with devtoolset-7. Does anyone have a solution for this?

**Comment by byronyi** [comment] 2019-04-08 12:28
It might because the usable memory of your system is too low compared to the number of parallel Bazel compilation tasks. 

You could try setting it to a smaller value using: ``bazel build --jobs 4 //...``

**Comment by sathyamoorthyrr** [comment] 2019-04-15 12:59
Using Ubuntu 18.04, GCC-7.3.0, faced the same issue by running,
`bazel build -c opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" tensorflow_serving/...`

Similar to @byronyi's comment,  adding `--config=nativeopt` does not give any error.

However, I have also used `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` to let the build be compatible with older ABI. Refer [here](https://www.tensorflow.org/install/source#bazel_build_options)

My bazel build command,
`bazel build --config=nativeopt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" tensorflow_serving/...`

Build completed _successfully_.

I installed the **.deb** file generated under `tensorflow_serving/model_servers/` in another system with same configuration(Ubuntu 18.04, GCC-7.3.0)

Installing the same file under the Ubuntu 16.04, GCC-5.4.0 says the `required CXX ABI version not found`.

Don't `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` in the build command have any effect?
or is that being used incorrectly?

**Comment by gunan** [comment] 2019-05-11 00:01
I think there is a known gcc 7 issue. It is fixed in the later versions of gcc 7 and 8.

CXXABI issue is different. If you build TF on ubuntu 18, that binary wont run on ubuntu 16 or 14. Using D_GLIBCXX_USE_CXX11_ABI will only make it possible for TF to be able to run properly with binaries that are compiled using older libstdc++ versions.

As the main issue reported is a gcc issue, and fixed with patch releases in gcc, I will close this bug.

**Closed by gunan** 2019-05-11 00:01 UTC
Labels: stat:awaiting tensorflower, subtype:centos, type:build/install

**Comment by zhuangli1987** [comment] 2019-05-23 23:25
> @mrodozov I rebuilt gcc 8.3.0 from sources this morning (6hr compile time!) and still the same error.
> 
> So now I've seen the error on TF v1.13.1 on my Ubuntu 16.04 AWS a4.xlarge compiling with native gcc 7.3.0, Linaro's generic gcc-8.2.0 (_Generic-AArch64_Ubuntu-16.04_aarch64-linux), and GCC's natively built 8.3.0. (And yes, I verified that the failing command is, in fact, using the correct compiler path). They all generate the same compiler error on the same line of code.
> 
> I suppose I could compile gcc 7.4.0, but I'm beginning to think this is not GCC issue. ~Would be great if you could make your 1.13.1 aarch64 wheel file available if you've been successful on multiple compilers.~
> 
> **EDIT: I just found @lhelontra's wheel files for 1.13.1 at https://github.com/lhelontra/tensorflow-on-arm/releases**
> 
> ```
> $ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> Target: aarch64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
> Thread model: posix
> gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 
> 
> $ /usr/local/bin/gcc -v
> Using built-in specs.
> COLLECT_GCC=/usr/local/bin/gcc
> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/aarch64-unknown-linux-gnu/8.3.0/lto-wrapper
> Target: aarch64-unknown-linux-gnu
> Configured with: ./configure
> Thread model: posix
> gcc version 8.3.0 (GCC) 
> 
> $ /opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/gcc -v
> Using built-in specs.
> COLLECT_GCC=/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/gcc
> COLLECT_LTO_WRAPPER=/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux/bin/../libexec/gcc/aarch64-linux-gnu/8.2.0/lto-wrapper
> Target: aarch64-linux-gnu
> Configured with: ../configure --prefix /tmp/plgbuild/abs_build/761279_27578/trunk/rel_work/arm_builder/components/builder/work/current_tree/AArch64/opt/arm/gcc-8.2.0_Generic-AArch64_Ubuntu-16.04_aarch64-linux --enable-languages=c,c++,go,fortran --disable-multilib --enable-lto --disable-werror --enable-stage1-checking --enable-checking=release --with-build-config=bootstrap-debug --enable-plugins --enable-gnu-indirect-function --target aarch64-linux-gnu --host aarch64-linux-gnu --enable-multiarch --with-build-sysroot=/tmp/plgbuild/abs_build/761279_27578/trunk/rel_work/arm_builder/components/builder/roots/armada/SysRoots/Ubuntu/Ubuntu_16.04_aarch64.rootfs --with-pkgversion=ARM-build-7
> Thread model: posix
> gcc version 8.2.0 (ARM-build-7) 
> ```

did you resolve this issue? I can not compile it  with 7.4.0 7.3.0 too. I believe it is not gcc problem. Please do reopen this ticket. @gunan

**Comment by npanpaliya** [comment] 2019-05-24 06:36
Try with gcc 5.4. It worked for me.

**Comment by wormwang** [comment] 2019-06-12 10:13
Ubuntu 18.04.2
gcc 7.4 & gcc 8.3 meet same this error

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/products/GeneralBlockPanelKernel.h:1879:3: internal compiler error: in emit_move_insn, at expr.c:3723
   }
   ^

**Comment by nSircombe** [comment] 2019-06-12 14:54
I believe this is fixed with the latest 7.x, 8.x and 9.x releases:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90075
although I've not been able to confirm for myself yet.

**Comment by mrodozov** [comment] 2019-06-12 15:12
yes we are building with 7.4.1
@npanpaliya sure, I might as well try assembler or something :laughing:

**Comment by zhuangli1987** [comment] 2019-06-12 16:31
I did apply the patch from
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89752 and now the compiling
works.
This patch hasn't been applied on branch of 7.x or lower version. Please do
it manually, and re-compile gcc on arm.

**Comment by didier-devel** [comment] 2019-11-08 11:23
With this workaround, you can compile tensorflow with gcc 6.3 

In external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801
(you can find the file in a subdirectory of ~/.cache/bazel )

replace

values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
                                                                    num_values_to_reduce, reducer);

by two instructions instead

Self::CoeffReturnType a = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
								    num_values_to_reduce, reducer);
values[i] = a;

**Comment by liyue201** [comment] 2019-11-15 03:42
> With this workaround, you can compile tensorflow with gcc 6.3
> 
> In external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801
> (you can find the file in a subdirectory of ~/.cache/bazel )
> 
> replace
> 
> values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
> num_values_to_reduce, reducer);
> 
> by two instructions instead
> 
> Self::CoeffReturnType a = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
> num_values_to_reduce, reducer);
> values[i] = a;
it works， thanks

**Comment by liyue201** [comment] 2019-11-15 03:43
> With this workaround, you can compile tensorflow with gcc 6.3
> 
> In external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801
> (you can find the file in a subdirectory of ~/.cache/bazel )
> 
> replace
> 
> values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
> num_values_to_reduce, reducer);
> 
> by two instructions instead
> 
> Self::CoeffReturnType a = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
> num_values_to_reduce, reducer);
> values[i] = a;

it works， thanks

**Comment by loisaidasam** [comment] 2020-01-07 16:06
The workaround didn't work for me.

I'm working from a stretch-based Docker instance, looking to install TF from source.

What worked for me was upgrading to gcc 8.3.0

## Instructions

(for other Debian rooks out there like me)

First I added the following line to the bottom of my `/etc/apt/sources.list`:

```
deb http://ftp.us.debian.org/debian testing main contrib non-free
```

Then I ran:

```
# apt-get update
# apt-get install gcc-8 g++-8
```

The default gcc for me was 6.3.0:

```
# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So I needed to update my gcc to point to the new one:

```
# update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
update-alternatives: using /usr/bin/gcc-8 to provide /usr/bin/gcc (gcc) in auto mode
# update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6
```

The default is now 8.3.0:

```
# gcc --version
gcc (Debian 8.3.0-26) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If I wanted to default to a different gcc version, I can now use:

```
# update-alternatives --config gcc
```

## References

- https://stackoverflow.com/questions/43151627/installing-g-7-0-1-on-debian-8-7/43151826#43151826
- https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/#installing-multiple-gcc-versions

**Comment by jesen8** [comment] 2020-08-15 04:59
> We also run into the same problem trying to compile TensorFlow in our CentOS 7 with devtoolset-7. Does anyone have a solution for this?

have you slove this problem?

**Comment by xingfeT** [comment] 2021-11-04 09:59
> With this workaround, you can compile tensorflow with gcc 6.3
> 
> In external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:801 (you can find the file in a subdirectory of ~/.cache/bazel )
> 
> replace
> 
> values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce, num_values_to_reduce, reducer);
> 
> by two instructions instead
> 
> Self::CoeffReturnType a = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce, num_values_to_reduce, reducer); values[i] = a;

thanks, it's work
