### ISSUE TITLE
tf.data.Dataset.flat_map shape assertion bug on Dataset with single tensor 

### ISSUE THREAD

**Issue by alenaschnurr** [tensorflow/tensorflow#28694] opened 2019-05-14 08:51 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes which I have added as an example
- Windows 7 Enterprise
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- Python version: 3.5
- CUDA/cuDNN version: 10.0
- GPU model and memory:  GeForce GTX 1050, 4GB

**Describe the current behavior**
Applying tf.data.Dataset.flat_map() to a dataset that just contains one tensor (in contrast to a tupled pair of tensors) leads to an incorrect error (from the example below):
ValueError: Tensor's shape (2,) is not compatible with supplied shape (None, 2)
The supplied shape seems to be incorrectly derived. This works without problem when the dataset contains two tensors (see example.)

**Describe the expected behavior**
The tensor with Tensor's shape (2,) is the correct output when apllying flat_map to a dataset containing x sample, each consting of two values.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

mode = 1  # 1 for single tensor example, 0 for two tensor example


def get_sample(n_element):
    if mode == 1:
        samples = np.random.sample((n_element.numpy(), 2))
    else:
        samples = (np.random.sample((n_element.numpy(), 2)), np.random.sample((n_element.numpy(), 2)))

    tensors = []
    for t in samples:
        tensors.append(tf.convert_to_tensor(t, dtype=tf.float64))
    return tensors


def read_wrapper(number_ds):
    if mode == 1:
        dtypes = [tf.float64]
    else:
        dtypes = [tf.float64, tf.float64]

    ex = tf.py_function(get_sample, [number_ds], dtypes)

    tensors = []
    for t in ex:
        t.set_shape([None, 2])
        tensors.append(t)

    return tensors


def get_dataset(n_element_list):
    print('Initial List: ', n_element_list)
    ds = tf.data.Dataset.from_tensor_slices(n_element_list)
    print('After Slicing: ', ds)
    ds = ds.map(map_func=read_wrapper)
    print('After Mapping: ', ds)
    if mode == 1:
        ds.flat_map(lambda x: tf.data.Dataset.from_tensor_slices(x))
    else:
        ds = ds.flat_map(lambda e, l: tf.data.Dataset.zip((
            tf.data.Dataset.from_tensor_slices(e),
            tf.data.Dataset.from_tensor_slices(l))))

    print('After Flattening: ', ds)
    return ds


if __name__ == '__main__':
    np.random.seed(42)
    n_e_list = np.random.randint(2, 4, size=3)
    n_e_list = tf.squeeze(tf.convert_to_tensor(n_e_list))
    data_set = get_dataset(n_e_list)
    data_set = data_set.prefetch(1)

    if mode == 1:
        for x_train in data_set:
            print('Finished Batch: ', x_train)
    else:
        for x_train, y_train in data_set:
            print('Finished Batch: ', x_train, y_train)
```

**Other info / logs**

with mode= 1  The erros occures. Output:

2019-05-14 10:37:23.354903: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-14 10:37:23.354903: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-05-14 10:37:23.554905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.43
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.86GiB
2019-05-14 10:37:23.554905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-05-14 10:37:24.124911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-14 10:37:24.124911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-05-14 10:37:24.124911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-05-14 10:37:24.124911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3581 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Initial List:  tf.Tensor([2 3 2], shape=(3,), dtype=int32)
After Slicing:  <TensorSliceDataset shapes: (), types: tf.int32>
After Mapping:  <MapDataset shapes: ((None, 2),), types: (tf.float64,)>
Traceback (most recent call last):
  File "DirectoryName/Documents/Repositories/LiverSegmentation/scripts/test_dataset.py", line 60, in <module>
    for x_train in data_set:
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 557, in __next__
    return self.next()
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 586, in next
After Flattening:  <MapDataset shapes: ((None, 2),), types: (tf.float64,)>
[TensorShape([None, 2])]
    return self._next_internal()
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 580, in _next_internal
    return self._structure._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\data\util\structure.py", line 393, in _from_compatible_tensor_list
    flat_ret.append(structure._from_compatible_tensor_list(sub_value))
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\data\util\structure.py", line 473, in _from_compatible_tensor_list
    flat_value[0].set_shape(self._shape)
  File "DirectoryName\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 928, in set_shape
    (self.shape, shape))
ValueError: Tensor's shape (2,) is not compatible with supplied shape (None, 2)

Process finished with exit code 1

with mode =0 everything runs correctly:

2019-05-14 10:36:57.849895: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-14 10:36:57.859895: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-05-14 10:36:58.041899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.43
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.86GiB
2019-05-14 10:36:58.041899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-05-14 10:36:58.621912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-14 10:36:58.621912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-05-14 10:36:58.621912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-05-14 10:36:58.621912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3581 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Initial List:  tf.Tensor([2 3 2], shape=(3,), dtype=int32)
After Slicing:  <TensorSliceDataset shapes: (), types: tf.int32>
After Mapping:  <MapDataset shapes: ((None, 2), (None, 2)), types: (tf.float64, tf.float64)>
After Flattening:  <FlatMapDataset shapes: ((2,), (2,)), types: (tf.float64, tf.float64)>
[TensorShape([2]), TensorShape([2])]
Finished Batch:  tf.Tensor([0.18343479 0.779691  ], shape=(2,), dtype=float64) tf.Tensor([0.09997492 0.45924889], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([0.59685016 0.44583275], shape=(2,), dtype=float64) tf.Tensor([0.33370861 0.14286682], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([0.65088847 0.05641158], shape=(2,), dtype=float64) tf.Tensor([0.61748151 0.61165316], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([0.72199877 0.93855271], shape=(2,), dtype=float64) tf.Tensor([0.00706631 0.02306243], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([7.78765841e-04 9.92211559e-01], shape=(2,), dtype=float64) tf.Tensor([0.52477466 0.39986097], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([0.04666566 0.97375552], shape=(2,), dtype=float64) tf.Tensor([0.61838601 0.38246199], shape=(2,), dtype=float64)
Finished Batch:  tf.Tensor([0.23277134 0.09060643], shape=(2,), dtype=float64) tf.Tensor([0.98323089 0.46676289], shape=(2,), dtype=float64)

Process finished with exit code 0

**Comment by muddham** [comment] 2019-05-15 08:42
@alenaschnurr Able to reproduce the issue with provided code.

ValueError: Tensor's shape (2,) is not compatible with supplied shape (None, 2)

**Comment by jvishnuvardhan** [comment] 2019-06-28 00:38
@alenaschnurr I changed shape in one function as follows. I don't see any error for both mode=1 or 2. Please let me know what you think? Thanks!

```
def read_wrapper(number_ds):
    if mode == 1:
        dtypes = [tf.float64]
    else:
        dtypes = [tf.float64, tf.float64]

    ex = tf.py_function(get_sample, [number_ds], dtypes)

    tensors = []
    for t in ex:
      if mode == 1:
        t.set_shape([2])
      else:
        t.set_shape([None, 2])
      tensors.append(t)

    return tensors
```

**Comment by tensorflowbutler** [comment] 2019-07-12 12:33
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-07-12 16:50
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-07-12 16:50 UTC
Labels: comp:data, comp:ops, stat:awaiting response, type:bug/performance
