### ISSUE TITLE
tf-slim resnet-50 pretrained model get wrong results when inference

### ISSUE THREAD

**Issue by auroua** [tensorflow/tensorflow#17426] opened 2018-03-05 05:38 UTC
I have asked this question on stackoverflow, but no one answer. Does any can help me.
The question link to stackoverflow is [here](https://stackoverflow.com/questions/49094123/tf-slim-resnet-pretrained-model-cant-get-correct-results).
The following is the code I used to do inference.The image preprocess method following this issue [ResNet pre-processing: VGG or Inception?](https://github.com/tensorflow/models/issues/2217)
```Python
import tensorflow as tf
import tensorflow.contrib.slim.nets as nets
import imagenet
import urllib.request
from preprocessing import inception_preprocessing
import matplotlib.pyplot as plt
import numpy as np
slim = tf.contrib.slim
resnet = nets.resnet_v1

if __name__ == '__main__':
    ckpt_file_path = '../model_weights/resnet_v1_50.ckpt'
    url = 'https://upload.wikimedia.org/wikipedia/commons/7/70/EnglishCockerSpaniel_simon.jpg'
    image_string = urllib.request.urlopen(url).read()
    image = tf.image.decode_jpeg(image_string, channels=3)
    processed_image = inception_preprocessing.preprocess_image(image, 224, 224, is_training=False)
    processed_images = tf.expand_dims(processed_image, 0)
    with slim.arg_scope(nets.resnet_utils.resnet_arg_scope()):
        resnet_50, end_points = resnet.resnet_v1_50(inputs=processed_images, num_classes=1000, scope='resnet_v1_50')
        prob = tf.squeeze(resnet_50, axis=[1, 2])
    probabilities = tf.nn.softmax(prob, dim=-1)
    sess = tf.Session()
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file_path)
    np_image, results = sess.run([image, probabilities])
    results = results[0, 0:]

    plt.figure()
    plt.imshow(np_image.astype(np.uint8))
    plt.axis('off')
    plt.show()

    sorted_inds = [i[0] for i in sorted(enumerate(-results), key=lambda x: x[1])]
    names = imagenet.create_readable_names_for_imagenet_labels()
    for i in range(5):
        index = sorted_inds[i]
        print('Probability %0.2f%% => [%s]' % (results[index] * 100, names[index]))
```
The following is result:
```
Probability 1.00% => [moving van]
Probability 0.69% => [television, television system]
Probability 0.63% => [English foxhound]
Probability 0.63% => [beagle]
Probability 0.61% => [German short-haired pointer]
```

**Comment by tensorflowbutler** [comment] 2018-03-05 13:12
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by auroua** [comment] 2018-03-05 15:53
OS platform  Ubuntu 16.04
Tensorflow installed from   pip 
Tensorflow version    1.4.1
Bazel version    0.8
CUDA/cuDNN version   CUDA 8.0  cuDNN 6.0
GPU model and memory  GTX 1060 6G

**Comment by John1231983** [comment] 2018-03-06 12:38
@auroua : It must be vgg preprocessing as default. Your code almost correct, except the preprocessing

**Comment by auroua** [comment] 2018-03-06 12:47
@John1231983 The preprocessing method is following the issue  [ResNet pre-processing: VGG or Inception?](https://github.com/tensorflow/models/issues/2217). I will test the vgg preprocessing.

**Comment by auroua** [comment] 2018-03-06 13:04
The following is result when I changed the preprocessing method from `inception_preprocessing` to `vgg_preprocessing`.
```
Probability 0.96% => [moving van]
Probability 0.71% => [television, television system]
Probability 0.67% => [broom]
Probability 0.62% => [German short-haired pointer]
Probability 0.62% => [sundial]
```

This is the modified code:
```Python
    processed_image = vgg_preprocessing.preprocess_image(image, 224, 224, is_training=False)
    # processed_image = inception_preprocessing.preprocess_image(image, 224, 224, is_training=False)
    processed_images = tf.expand_dims(processed_image, 0)
```

I think the results is not correct.

**Comment by tatianashp** [comment] 2018-04-05 00:39
Automatically closing due to lack of recent activity.

**Closed by tatianashp** 2018-04-05 00:39 UTC
Labels: type:support

**Comment by auroua** [comment] 2018-04-05 15:12
This problem still exists. Can you solve it? @tatianashp

**Comment by aavishkarmishra** [comment] 2020-07-24 09:22
@tatianashp I want to contribute to this issue can anyone help me with this.

**Comment by sanjoy** [comment] 2020-07-24 16:47
I think this should be reported on https://github.com/google-research/tf-slim, not here.
