### ISSUE TITLE
Cannot load model in TF2.1.0 AttributeError: 'h5py.h5f.FileID' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#34756] opened 2019-12-02 11:16 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0rc0
- Keras version: 2.2.4-tf
- Python version: 3.6.1
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: RTX 2060 6GB

**Describe the current behavior**
I cannot load a model that has been trained with previous versions of the TensorFlow 1.x

```
Traceback (most recent call last):
  File "C:\project\model.py", line 56, in load_weights
    weights = model.load_weights(file, by_name=True)
  File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1183, in load_weights
    if _is_hdf5_filepath(filepath):
  File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1500, in _is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'h5py.h5f.FileID' object has no attribute 'endswith'
```

**Comment by oanush** [comment] 2019-12-03 03:27
@kiflowb777 ,
Can you please provide the code to reproduce the error faced ?Thanks!

**Comment by tensorflowbutler** [comment] 2019-12-17 12:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by oanush** [comment] 2019-12-18 10:15
@kiflowb777 ,
Any update on the issue ?Thanks!

**Comment by hf-sky-hf** [comment] 2019-12-18 10:30
Need help phone is not att

**Comment by oanush** [comment] 2019-12-24 08:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-12-24 08:40 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support

**Comment by ashwanth0203** [comment] 2020-12-17 21:49
I am facing this issue. What is the ideal solution this. Using Tensorflow 2.3
