### ISSUE TITLE
2.3 Nightly build produces error when initializing system in TF documentation's Colab tutorial

### ISSUE THREAD

**Issue by jasonbrancazio** [tensorflow/tensorflow#40196] opened 2020-06-05 13:50 UTC
**System information**
- Have I written custom code: NO
- TensorFlow installed from: pip (tf-nightly)
- TensorFlow version: 2.3.0-dev20200605

**Describe the current behavior**
TPU won't initialize in colab using the nightly build.

**Describe the expected behavior**
Run the https://www.tensorflow.org/guide/tpu notebook successfully, as one would if using TF 2.2.

**Standalone code to reproduce the issue**
1. Load https://www.tensorflow.org/guide/tpu in colab.
2. Run `!pip install tf-nightly` in a new cell before running anything else.
3. Run the TPU initialization section of the notebook.
4. Observe the following error:

```InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}
```

**Comment by ravikyram** [comment] 2020-06-06 11:25
@jasonbrancazio 

I have tried in  colab with TF nightly version (`2.3.0-dev20200605`) .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0dcb9b852c34d150ef74573641eeef22/untitled54.ipynb).Is this expected behavior?.Thanks!

**Comment by jasonbrancazio** [comment] 2020-06-06 17:10
@ravikyram Yes, the InvalidArgumentError is the same error I experienced.

**Comment by rxsang** [comment] 2020-06-09 20:28
That indicates a version mismatch between your colab client and TPU worker. Is your TPU worker also nightly?

**Comment by jasonbrancazio** [comment] 2020-06-09 20:54
@rxsang I don't see how to determine without modifying the steps indicated above whether the TPU worker is using a nightly version of tf. Would you mind posting how to determine this? 

I did see your trick here, which seems to be related to provisioning a worker at a certain version level rather than inspecting its properties: https://github.com/tensorflow/tensorflow/issues/34346#issuecomment-598399912

Regardless, I just retried the steps outlined in my bug report. I no longer see the error I reported.  

Perhaps the default versions in colab notebooks are no longer mismatched.

**Comment by jvishnuvardhan** [comment] 2020-10-10 04:08
@jasonbrancazio Looks like this was already resolved. I cannot reproduce the error with `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f3e731ccbb301541790371112502f50c/tpu.ipynb).

I am closing this issue as this was already resolved. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2020-10-10 04:08 UTC
Labels: TF 2.3, comp:tpus, type:docs-bug
