### ISSUE TITLE
TypeError: Cannot convert value dtype([('resource', 'u1')]) to a TensorFlow DType.

### ISSUE THREAD

**Issue by zhouhao-learning** [tensorflow/tensorflow#34665] opened 2019-11-28 01:39 UTC
Hello, I just started learning tf2.0, I tried to implement Chinese word2vec using tf2.0, I trained the model and passed `tf.compat.v1.train.Saver (). Save (session, ckpt_file_path, global_step = 2) The `command saves the trained model. However, when I load tf2.0 for prediction, an unexpected error occurs. I tried many methods but it was not resolved, but I used tf1.x to load the model prediction without any problems. In .0, the unexpected errors are as follows:
```
home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/client/session.py:1443: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  run_metadata)
Traceback (most recent call last):
  File "predict2.py", line 34, in <module>
    norm = tf.sqrt(tf.reduce_sum(input_tensor=tf.square(embeddings), axis=1, keepdims=True), name="norm")
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 10931, in square
    "Square", x=x, name=name)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 530, in _apply_op_helper
    raise err
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 472, in make_tensor_proto
    numpy_dtype = dtypes.as_dtype(nparray.dtype)
  File "/home/zh/sda3/Anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow_core/python/framework/dtypes.py", line 721, in as_dtype
    (type_value,))
TypeError: Cannot convert value dtype([('resource', 'u1')]) to a TensorFlow DType.

```

my predict code:
```
dictionary = {"UNK": 0, "，": 1, "的": 2, "。": 3, "了": 4, "是": 5, "『": 6, "』": 7, "萧炎": 8}
reverse_dictionary = {"0": "UNK", "1": "，", "2": "的", "3": "。", "4": "了", "5": "是", "6": "『", "7": "』", "8": "萧炎"}
valid_word = ['萧炎']

valid_size = 1
valid_examples =[dictionary[li] for li in valid_word]
# valid_dataset = tf.constant(valid_examples, dtype=tf.int32)
valid_dataset = np.array(valid_examples)
with tf.compat.v1.Session() as sess:
    saver = tf.compat.v1.train.import_meta_graph('./model/-2
[model.zip](https://github.com/tensorflow/tensorflow/files/3899434/model.zip)
.meta')  
    saver.restore(sess, tf.train.latest_checkpoint('./model/'))  
    gragh = tf.compat.v1.get_default_graph()
    tensor_name_list = [tensor.name for tensor in gragh.as_graph_def().node]
    input_x = sess.graph.get_tensor_by_name('x:0')
    input_y = sess.graph.get_tensor_by_name('y:0')
    embeddings = sess.graph.get_tensor_by_name('embedding:0')
    feed_dict = {input_x: valid_dataset}
    embeddings = sess.run(embeddings,feed_dict)
    norm = tf.sqrt(tf.reduce_sum(input_tensor=tf.square(embeddings), axis=1, keepdims=True), name="norm")
    normalized_embeddings = embeddings / norm
    valid_embeddings = tf.nn.embedding_lookup(params=normalized_embeddings, ids=valid_dataset)
    similarity = tf.matmul(valid_embeddings, normalized_embeddings, transpose_b=True)
    sim = similarity.eval()
    for i in xrange(valid_size):
        valid_word = reverse_dictionary[str(valid_examples[i])]
        top_k = 8  # number of nearest neighbors
        nearest = (-sim[i, :]).argsort()[:top_k]
        log_str = "Nearest to %s:" % valid_word
        for k in xrange(top_k):
            close_word = reverse_dictionary[str(nearest[k])]
            log_str = "%s %s," % (log_str, close_word)
        print(log_str)
```
`model.zip` is the model used for testing. Could you please help me to see what problems I encountered? I have tried many methods but still not solved, please give me more guidance, thanks!

**Comment by zhouhao-learning** [comment] 2019-11-28 01:41
@ry @jmhodges @eggie5 
test model
[model.zip](https://github.com/tensorflow/tensorflow/files/3899448/model.zip)

**Comment by ravikyram** [comment] 2019-11-29 09:30
I have tried on colab with TF version 2.0 and i am seeing the below error`.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 43: invalid continuation byte`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/632f6fced0f3c6f09ed283ea4dbc0124/untitled421.ipynb).Please, help me in reproducing the issue. It helps in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2019-12-14 12:21
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2019-12-18 10:48
@zhouhao-learning 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2019-12-27 09:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-12-27 09:09 UTC
Labels: TF 2.0, comp:apis, stat:awaiting response, type:support
