### ISSUE TITLE
Compiling TensorFlow 1.4.0 GPU on Windows 10 x64

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#13962] opened 2017-10-25 01:25 UTC
There doesn't seem to be any detailed documentation for how to compile TensorFlow 1.4.0 GPU on Windows 10 x64.

I need to recompile TF to add missing functionality for a Windows 7 x64 production system.

 I can use Bazel or CMake to compile something but how do I incorporate the Python and NVIDIA dependencies into that build?

How are the Windows wheels at https://pypi.python.org/pypi/tensorflow-gpu compiled?

**Comment by Carmezim** [comment] 2017-10-25 15:35
Could you try taking a look on [theses instructions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md) to compile with CMake? When you're configuring TensorFlow you will be prompted to choose if your binary will support GPU or not. You can't incorporate CUDA or cuDNN into the binary AFAIK, each user of that compiled binary needs to install CUDA and cuDNN separately.

**Comment by johnsrude** [comment] 2017-10-25 20:47
Thanks, @Carmezim that worked.
Additional issues that came up are addressed at https://github.com/tensorflow/tensorflow/issues/5600

distutils is no longer available on the Anaconda3 win-64 channel.

-

**Comment by Carmezim** [comment] 2017-10-25 21:01
Cool! Thanks for following up. If you have any further questions let us know. This can be closed now.

**Comment by johnsrude** [comment] 2017-10-25 21:07
Not yet. I've still got some compile error issues I'm working through.

**Comment by Carmezim** [comment] 2017-10-25 21:12
Oh I thought by "that worked" you had success compiling. No problem though. Could you post them so we can take a look and if possible how to reproduce?

**Comment by johnsrude** [comment] 2017-10-26 16:18
I'm working with the tensorflow r1.4 branch.   When I CMake configure
`cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/Users/Kevin/dev/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=python.exe -DPYTHON_LIBRARIES=C:/ProgramData/Anaconda3/libs/python36.lib -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\include -DNUMPY_INCLUDE_DIR=C:\ProgramData\Anaconda3\Lib\site-packages\numpy\core\include -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX `
and run 
`MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`
I get the error
```
"C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
(PostBuildEvent target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal\r [C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cm
ake\build\tf_python_build_pip_package.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E copy C:/Users/Kevin/dev/tensorflow-r1.4/t
ensorflow/tools/pip_package/setup.py C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/build/tf_python/\r [C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake\build\tf_pyt
hon_build_pip_package.vcxproj]
...
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 9009. [C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contr
ib\cmake\build\tf_python_build_pip_package.vcxproj]
    7016 Warning(s)
    1 Error(s)
Time Elapsed 03:53:21.42
```
Full error listing attached.
[CMakeOutput.log](https://github.com/tensorflow/tensorflow/files/1419162/CMakeOutput.log)
[CMakeError.log](https://github.com/tensorflow/tensorflow/files/1419163/CMakeError.log)

**Comment by mrry** [comment] 2017-10-26 16:34
Neither of those log files seems to include that error message (I searched for "1 Error(s)" and got no hits in either). Can you send the full log of the failing build?

This substring in the error message is suspicious: `C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/build/tf_python/\r`. Assuming the `\r` is part of the intended target path, it looks like there is a stray line break in some part of the configuration.

**Comment by johnsrude** [comment] 2017-10-26 16:40
Oops, sorry.  The CMake* files only show the CMake errors.  Builds on Windows aren't dumped to a logfile but to command prompt output.  Here's the last 9999 lines of that output.
[tf bug.txt](https://github.com/tensorflow/tensorflow/files/1419225/tf.bug.txt)

**Comment by johnsrude** [comment] 2017-10-26 17:53
I'm currently trying to build a Python wheel with `MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`

While I wait for your answer on the compilation error I'm trying to build the test trainer with `MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj`   This appears to be rebuilding the TF code from scratch.

That can't be right, can it?

**Comment by mrry** [comment] 2017-10-26 18:54
The build isn't hermetic (its only supported purpose is building the PIP package on our CI server), so I believe MSBuild isn't able to detect opportunities for incremental building. If this is easy to fix, and somebody who knows how to do that is reading, we'd welcome contributions on that topic.

This suggests a possible cause for the error you are seeing: if your build directory contains some files created during a previous failed build, these could be causing the new build to fail. It might be easiest to try deleting the entire `tensorflow/contrib/cmake/build/` directory, then creating a new build from scratch.

**Comment by johnsrude** [comment] 2017-10-26 19:03
I've already done that once.  What CMake and MSBuild command lines do you use on your CI server?  I'm wondering if there's a problem with the particular arg combination I'm using.

**Comment by mrry** [comment] 2017-10-26 19:11
Here's the script: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/gpu/cmake/run_build.bat

**Comment by johnsrude** [comment] 2017-10-26 19:40
This build together with the CMake listed above compiled without errors
`>MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj`

so the problem is specifically with this build
`MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`

**Comment by johnsrude** [comment] 2017-10-26 20:55
I believe the '\r' in the MSBuild message is just an artifact of the way that MSBuild prints messages and the way that Windows uses "\r\n" instead of "\n"

**Comment by johnsrude** [comment] 2017-10-26 21:12
For the always rebuilding issue see https://stackoverflow.com/questions/4185638/solving-the-visual-studio-2010-alwayscreate-rebuild-issue

**Comment by johnsrude** [comment] 2017-10-26 21:13
https://stackoverflow.com/questions/14916729/visual-studio-rebuilds-unmodified-projects

**Comment by johnsrude** [comment] 2017-10-26 21:39
The reason why these are completely rebuilt from scratch is that you have MSBuild running CMake commands like this every time you build:
`"C:\Program Files\CMake\bin\cmake.exe" -E copy_directory C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/core C:/Users/Kevin/dev/tensorflow-r1.4/tensorflow/contrib/cmake/build/tf_python/tensorflow/include/tensorflow/core`

**Comment by johnsrude** [comment] 2017-10-26 22:21
I think I may have found the problem with the failed wheel build.

In the CMake command I replaced
```-DPYTHON_EXECUTABLE=python.exe```
with
```-DPYTHON_EXECUTABLE=C:/ProgramData/Anaconda3/python.exe```

The problem appears to be that despite python.exe being in the PATH, CMake will prepend a local pathname to python.exe if it doesn't have an absolute pathname.

Testing now.

The "build always" problem still unresolved.

**Comment by johnsrude** [comment] 2017-10-27 16:04
Compiled successfully after almost 5 hours.  Haven't tested the running of the wheel yet.  Need to resolve "build always" problem.

**Comment by johnsrude** [comment] 2017-10-27 17:56
```
c:\python35\scripts\pip3 install PythonWheels/tensorflow_gpu-1.4.0rc1-cp36-cp36m-win_amd64.whl
tensorflow_gpu-1.4.0rc1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

What could cause this error?  

Is it compiling on Windows 10 rather than Windows 7?  What version of Windows is your CI build server?

Could it be a difference in the CMake flags?

Yours (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/gpu/cmake/run_build.bat):
`%CMAKE_EXE% %CMAKE_DIR% -A x64 -DSWIG_EXECUTABLE=%SWIG_EXE% -DPYTHON_EXECUTABLE=%PY_EXE% -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARIES=%PY_LIB% -Dtensorflow_BUILD_PYTHON_TESTS=%BUILD_PYTHON_TESTS% -Dtensorflow_BUILD_CC_TESTS=%BUILD_CC_TESTS% -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME=%CUDNN_HOME% -Dtensorflow_TF_NIGHTLY=%TF_NIGHTLY%`

Mine:
`cmake C:\Users\Kevin\dev\tensorflow-r1.4\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/Users/Kevin/dev/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=C:/ProgramData/Anaconda3/python.exe -DPYTHON_LIBRARIES=C:/ProgramData/Anaconda3/libs/python36.lib -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\include -DNUMPY_INCLUDE_DIR=C:\ProgramData\Anaconda3\Lib\site-packages\numpy\core\include -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX `

In yours but not mine:
- -Dtensorflow_BUILD_PYTHON_TESTS=%BUILD_PYTHON_TESTS% 
- -Dtensorflow_BUILD_CC_TESTS=%BUILD_CC_TESTS% 
- -Dtensorflow_TF_NIGHTLY=%TF_NIGHTLY%

In mine but not yours:
- -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX  

To confirm that we're on the same page, what is the exact MSBuild line that you use in your CI server? I use: 
`MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`

**Comment by Carmezim** [comment] 2017-10-27 23:46
@johnsrude `not a supported wheel` is related to the Python distribution you're trying to install it this binary for. Is your Python is 3.5?

**Comment by johnsrude** [comment] 2017-10-28 00:03
@Carmezim  Yes, that's definitely a possibility.  I'll test it.

**Comment by johnsrude** [comment] 2017-10-30 18:16
@Carmezim Yes, the problem here was Python 3.5 vs 3.6. Thanks!   

Still need to resolve "build always" problem.

**Comment by mrry** [comment] 2017-10-31 05:28
I'm glad to hear it's building now! I'm going to close this issue, but feel free to open another one to track work on making the CMake build more incremental. (To set expectations, it's unlikely that anyone from the TF team will spend time on this, but we would welcome contributions that make things better for CMake users.)

**Closed by mrry** 2017-10-31 05:28 UTC

**Comment by zhangcong2009** [comment] 2017-12-11 06:59
@johnsrude I get the same error "error MSB3073". But I have input the full path of Anaconda pothon.exe in the cmake command, like  -DPYTHON_EXECUTABLE="D:\Program Files\Anaconda3\python.exe", and this error still happens. How can I solve this to compile wheel? Thanks!
