### ISSUE TITLE
tests inside tflite/kernels/internal fail to build

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#26674] opened 2019-03-13 15:48 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-  OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit 6583b83dc9393118c60a9c11f15453c650fab89f
- Python version: 2.7.15rc1
- Installed using virtualenv? pip? conda?: sources
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Some tests inside tflite/kernels/internal (6 out of 11) fail to build. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test --verbose_failures --config=opt //tensorflow/lite/kernels/internal/... -k

**Any other info / logs**
```
ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:713:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/batch_to_space_nd_test/batch_to_space_nd_test.o: undeclare
d inclusion(s) in rule '//tensorflow/lite/kernels/internal:batch_to_space_nd_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/batch_to_space_nd_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/batch_to_space_nd_test.cc:15:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
                      ^
ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:619:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/resize_bilinear_test/resize_bilinear_test.o: undeclared in
clusion(s) in rule '//tensorflow/lite/kernels/internal:resize_bilinear_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/resize_bilinear_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/resize_bilinear_test.cc:20:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
                      ^
ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:631:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/resize_nearest_neighbor_test/resize_nearest_neighbor_test.
o: undeclared inclusion(s) in rule '//tensorflow/lite/kernels/internal:resize_nearest_neighbor_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/resize_nearest_neighbor_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/resize_nearest_neighbor_test.cc:20:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;

ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:660:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/logsoftmax_quantized_test/logsoftmax_quantized_test.o: und
eclared inclusion(s) in rule '//tensorflow/lite/kernels/internal:logsoftmax_quantized_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/logsoftmax_quantized_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/logsoftmax_quantized_test.cc:26:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
                      ^
ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:643:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/softmax_quantized_test/softmax_quantized_test.o: undeclare
d inclusion(s) in rule '//tensorflow/lite/kernels/internal:softmax_quantized_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/softmax_quantized_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/softmax_quantized_test.cc:26:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;

ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/kernels/internal/BUILD:682:1: Couldn't build file tensorflow/lite/kernels/internal/_objs/log_quantized_test/log_quantized_test.o: undeclared inclusion(s) in rule '//tensorflow/lite/kernels/internal:log_quantized_test':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/kernels/internal/log_quantized_test.cc':
  'tensorflow/lite/kernels/internal/tensor_ctypes.h'
In file included from ./tensorflow/lite/kernels/internal/common.h:42:0,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:37,
                 from tensorflow/lite/kernels/internal/log_quantized_test.cc:30:
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'void vst1q_lane_f32(float32_t*, float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:9725:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(ptr) =  *((float*)&ilane);
                               ^
external/arm_neon_2_x86_sse/NEON_2_SSE.h: In function 'float32_t vgetq_lane_f32(float32x4_t, int)':
external/arm_neon_2_x86_sse/NEON_2_SSE.h:11964:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *(float*)&ilane;
```

**Comment by terryheo** [comment] 2019-12-11 06:38
I've tested this and couldn't reproduce the issue. @herbakamil , it seems that the issue is fixed now. Please feel free to reopen it if you still have the issue.

**Closed by terryheo** 2019-12-11 06:38 UTC
Labels: comp:lite
