### ISSUE TITLE
tf.shape shape mismatched in custom loss function

### ISSUE THREAD

**Issue by acmilannesta** [tensorflow/tensorflow#35744] opened 2020-01-10 16:11 UTC
Running on tf2.1.0-rc and python 3.6.8/ I wrote a custom loss function, but somehow I always get tf.shape error message

```
import tensorflow as tf
from scipy.stats import rankdata
from tensorflow.python.framework import ops
from tensorflow import keras

BATCH_SIZE = 4
num_targets =9

# Define custom py_func which takes also a grad op as argument:
def py_func(func, inp, Tout, name=None, grad=None):
    
    rnd_name = 'PyFuncGrad' + str(np.random.randint(0, 1E+8))
    
    tf.RegisterGradient(rnd_name)(grad)  
    g = tf.compat.v1.get_default_graph()
    with g.gradient_override_map({"PyFunc": rnd_name}):
        return tf.py_function(func, inp, Tout, name=name)

# Def custom square function using np.square instead of tf.square:
def myrankdata(x, name=None):
    
    with ops.op_scope([x], name, "MyGrad") as name:
        rank = py_func(rankdata,
                        [x],
                        [tf.float32],
                        name=name,
                        grad=_MyGrad)  
        return rank

# Actual gradient:
def _MyGrad(op, grad):
    return grad * 20 * op.inputs[0]  

def custom_loss(num_targets):
    def custom_rhos(y_true, y_pred):
        rhos = []
        y_true, y_pred = tf.reshape(y_true, [-1, num_targets]), tf.reshape(y_pred, [-1, num_targets])
        for ind in range(num_targets):
            a = tf.slice(y_true, [0, ind], [-1, 1])
            a = tf.reshape(a, [-1])
            b = tf.slice(y_pred, [0, ind], [-1, 1])
            b = tf.reshape(b, [-1])
            rank_a, rank_b = myrankdata(a)[0], myrankdata(b)[0]
            rho = 1 - 6 * tf.reduce_sum((rank_a - rank_b) ** 2) / (BATCH_SIZE ** 3 - BATCH_SIZE)
            rhos.append(rho)
        return -tf.reduce_sum(rhos)
    return custom_rhos

```

My model summary is
```
Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_category (InputLayer)     [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_host (InputLayer)         [(None, 1)]          0                                            
__________________________________________________________________________________________________
q_input_word_ids (InputLayer)   [(None, None)]       0                                            
__________________________________________________________________________________________________
q_input_masks (InputLayer)      [(None, None)]       0                                            
__________________________________________________________________________________________________
q_segment_ids (InputLayer)      [(None, None)]       0                                            
__________________________________________________________________________________________________
embedding_6 (Embedding)         (None, 1, 32)        192         input_category[0][0]             
__________________________________________________________________________________________________
embedding_7 (Embedding)         (None, 1, 32)        2080        input_host[0][0]                 
__________________________________________________________________________________________________
keras_layer_3 (KerasLayer)      [(None, 768), (None, 109482241   q_input_word_ids[0][0]           
                                                                 q_input_masks[0][0]              
                                                                 q_segment_ids[0][0]              
__________________________________________________________________________________________________
spatial_dropout1d_6 (SpatialDro (None, 1, 32)        0           embedding_6[0][0]                
__________________________________________________________________________________________________
spatial_dropout1d_7 (SpatialDro (None, 1, 32)        0           embedding_7[0][0]                
__________________________________________________________________________________________________
global_average_pooling1d_3 (Glo (None, 768)          0           keras_layer_3[0][1]              
__________________________________________________________________________________________________
concatenate_6 (Concatenate)     (None, 2, 32)        0           spatial_dropout1d_6[0][0]        
                                                                 spatial_dropout1d_7[0][0]        
__________________________________________________________________________________________________
dropout_3 (Dropout)             (None, 768)          0           global_average_pooling1d_3[0][0] 
__________________________________________________________________________________________________
flatten_3 (Flatten)             (None, 64)           0           concatenate_6[0][0]              
__________________________________________________________________________________________________
concatenate_7 (Concatenate)     (None, 832)          0           dropout_3[0][0]                  
                                                                 flatten_3[0][0]                  
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 9)            7497        concatenate_7[0][0]              
==================================================================================================
Total params: 109,492,010
Trainable params: 109,492,009
Non-trainable params: 1
__________________________________________________________________________________________________
```

Here is my error message

```
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input to reshape is a tensor with 1 values, but the requested shape has 4
	 [[node Reshape_41 (defined at <ipython-input-147-9b8e1e62f3d2>:10) ]]
	 [[Reshape_74/_626]]
  (1) Invalid argument:  Input to reshape is a tensor with 1 values, but the requested shape has 4
	 [[node Reshape_41 (defined at <ipython-input-147-9b8e1e62f3d2>:10) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_868236]

Function call stack:
distributed_function -> distributed_function
```

**Comment by ravikyram** [comment] 2020-01-13 10:37
@acmilannesta 

Looks like code is incomplete. Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-01-30 10:07
@acmilannesta 
Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-02-04 09:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-04 09:36 UTC
Labels: TF 2.1, comp:ops, stat:awaiting response, type:support
