### ISSUE TITLE
there is log about cannot enable peer access from device ordinal 0 to device ordinal 2

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#2145] opened 2016-04-28 09:04 UTC
I tried to install tensorflow with gpu ,and then run demo code,hello word,it will report

I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 0 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 0 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 1 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 1 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 2 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 2 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 3 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:59] cannot enable peer access from device ordinal 3 to device ordinal 1

is it a issue?
How can it prevent it ?

**Comment by liumilan** [comment] 2016-04-28 09:05
there are 4 gpus in my machine
Thu Apr 28 17:05:37 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 0000:0A:00.0     Off |                    0 |
| N/A   36C    P0    62W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          Off  | 0000:0D:00.0     Off |                    0 |
| N/A   32C    P0    61W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          Off  | 0000:2B:00.0     Off |                    0 |
| N/A   36C    P0    63W / 235W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          Off  | 0000:30:00.0     Off |                    0 |
| N/A   35C    P0    62W / 235W |     22MiB / 11519MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by poxvoculi** [comment] 2016-04-28 17:24
The NIVIDIA driver function cuDeviceCanAccessPeer is returning false for all pairs of GPUs in your environment.   Perhaps your installation does not have correct access to the proper or full CUDA libraries?   @zheng-xq  Any clue how this should be diagnosed?

**Comment by zheng-xq** [comment] 2016-04-29 00:08
Today, you are not losing much if peer-to-peer access is not enabled. But it might have performance implication for future TensorFlow releases. 

If you want to debug this issue locally, you can run the Cuda SDK sample simpleP2P and see if there is a problem.

**Comment by yzhang87** [comment] 2016-04-30 21:58
Hi, I have the same issue. Is this a driver issue or a card issue?

here is the output from simpleP2P:

```
CUDA-capable device count: 4
> GPU0 = "GeForce GTX TITAN X" IS  capable of Peer-to-Peer (P2P)
> GPU1 = "GeForce GTX TITAN X" IS  capable of Peer-to-Peer (P2P)
> GPU2 = "GeForce GTX TITAN X" IS  capable of Peer-to-Peer (P2P)
> GPU3 = "GeForce GTX TITAN X" IS  capable of Peer-to-Peer (P2P)

Checking GPU(s) for support of peer to peer memory access...
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU1) : Yes
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU2) : No
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU3) : No
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU0) : Yes
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU2) : No
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU3) : No
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU0) : No
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU1) : No
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU3) : Yes
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU0) : No
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU1) : No
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU2) : Yes
```

**Comment by yaroslavvb** [comment] 2016-05-01 00:30
Maybe your GPU0 and GPU2 each occupy a different Pcie Root Complex? That would force communication to go through QPI link, so maybe that prevents peering? FB supposedly open-sourced it's Big Sur design which shows to configure all 8 GPUs to be on the same root complex, although I'm having trouble finding the actual specs

**Comment by liumilan** [comment] 2016-05-01 13:23
So how it can make sure gpu0,gpu1 can communicate with gpu2,gpu3?
should need to be configure the hardware?

**Comment by liumilan** [comment] 2016-05-01 14:50
btw,where can I download the simpleP2P code from cuda website,
I can't find it in cuda website.
Could you offer the related link?

**Comment by liumilan** [comment] 2016-05-01 15:31
I have the same result after running simpleP2P
[@sjs_88_31 release]# ./simpleP2P 
[./simpleP2P] - Starting...
Checking for multiple GPUs...
CUDA-capable device count: 4
> GPU0 = "     Tesla K40m" IS  capable of Peer-to-Peer (P2P)
> GPU1 = "     Tesla K40m" IS  capable of Peer-to-Peer (P2P)
> GPU2 = "     Tesla K40m" IS  capable of Peer-to-Peer (P2P)
> GPU3 = "     Tesla K40m" IS  capable of Peer-to-Peer (P2P)

Checking GPU(s) for support of peer to peer memory access...
> Peer access from Tesla K40m (GPU0) -> Tesla K40m (GPU1) : Yes
> Peer access from Tesla K40m (GPU0) -> Tesla K40m (GPU2) : No
> Peer access from Tesla K40m (GPU0) -> Tesla K40m (GPU3) : No
> Peer access from Tesla K40m (GPU1) -> Tesla K40m (GPU0) : Yes
> Peer access from Tesla K40m (GPU1) -> Tesla K40m (GPU2) : No
> Peer access from Tesla K40m (GPU1) -> Tesla K40m (GPU3) : No
> Peer access from Tesla K40m (GPU2) -> Tesla K40m (GPU0) : No
> Peer access from Tesla K40m (GPU2) -> Tesla K40m (GPU1) : No
> Peer access from Tesla K40m (GPU2) -> Tesla K40m (GPU3) : Yes
> Peer access from Tesla K40m (GPU3) -> Tesla K40m (GPU0) : No
> Peer access from Tesla K40m (GPU3) -> Tesla K40m (GPU1) : No
> Peer access from Tesla K40m (GPU3) -> Tesla K40m (GPU2) : Yes
Enabling peer access between GPU0 and GPU1...
Checking GPU0 and GPU1 for UVA capabilities...
> Tesla K40m (GPU0) supports UVA: Yes
> Tesla K40m (GPU1) supports UVA: Yes
Both GPUs can support UVA, enabling...
Allocating buffers (64MB on GPU0, GPU1 and CPU Host)...
Creating event handles...
cudaMemcpyPeer / cudaMemcpy between GPU0 and GPU1: 9.52GB/s
Preparing host buffer and memcpy to GPU0...
Run kernel on GPU1, taking source data from GPU0 and writing to GPU1...
Run kernel on GPU0, taking source data from GPU1 and writing to GPU0...
Copy data back to host from GPU0 and verify results...
Disabling peer access...
Shutting down...
Test passed

**Comment by mrry** [comment] 2016-05-18 23:31
The results from `simpleP2P` seem like the problem is a CUDA configuration issue and not a TensorFlow-specific issue. I'm closing this for now.

**Closed by mrry** 2016-05-18 23:31 UTC
