### ISSUE TITLE
incompatibility : Keras LearningRateScheduler callback and tf.train.optimizer

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#20999] opened 2018-07-20 18:38 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
To make it short, there is an incompatibility between Keras LearningRateScheduler callback and tf.train.optimizer.  Keras optimizers have some specific attributes which are required for Keras callbacks and that does not seem to be the case for tf.train.optimizer.

Unfortunately, Keras optimizers are incompatible with the eager execution mode. So, basically, the user is compelled to choose between using Keras callbacks and the eager execution mode.

Here is a code proving that. It runs fine with a typical Keras optimizer and fails with the tensorflow one.

### Source code / logs
```
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras 
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import LearningRateScheduler

def step_decay(epoch):
  initial_rate = 1e-3
  factor = int(epoch / 5)
  lr = initial_rate / (10 ** factor)
  return lr

lr_schedule = LearningRateScheduler(step_decay)

input1 = Input(shape=(10,), name="input")
out = Dense(5, activation="relu")(input1)
model = Model(inputs=input1, outputs=out)
model.compile(optimizer= tf.train.AdamOptimizer(1e-3), loss='mse')

np.random.seed(0)
X = np.random.random((20, 10)).astype(np.float32)
Y = np.random.random((20, 5)).astype(np.float32)

model.fit(x=X, y=Y, batch_size=1, epochs=10, callbacks=[lr_schedule])
```

### Logs

Epoch 1/10

ValueErrorTraceback (most recent call last)
<ipython-input-9-c41c71fed68e> in <module>()
     24 Y = np.random.random((20, 5)).astype(np.float32)
     25 
---> 26 model.fit(x=X, y=Y, batch_size=1, epochs=10, callbacks=[lr_schedule])

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1346           initial_epoch=initial_epoch,
   1347           steps_per_epoch=steps_per_epoch,
-> 1348           validation_steps=validation_steps)
   1349 
   1350   def evaluate(self,

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.pyc in fit_loop(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    183       m.reset_states()
    184     # Update callbacks
--> 185     callbacks.on_epoch_begin(epoch)
    186     epoch_logs = {}
    187     if steps_per_epoch is not None:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.pyc in on_epoch_begin(self, epoch, logs)
     79     logs = logs or {}
     80     for callback in self.callbacks:
---> 81       callback.on_epoch_begin(epoch, logs)
     82     self._delta_t_batch = 0.
     83     self._delta_ts_batch_begin = deque([], maxlen=self.queue_length)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.pyc in on_epoch_begin(self, epoch, logs)
    635   def on_epoch_begin(self, epoch, logs=None):
    636     if not hasattr(self.model.optimizer, 'lr'):
--> 637       raise ValueError('Optimizer must have a "lr" attribute.')
    638     lr = self.schedule(epoch)
    639     if not isinstance(lr, (float, np.float32, np.float64)):

ValueError: Optimizer must have a "lr" attribute.

**Comment by nairouz** [comment] 2018-07-20 19:12
Even when I added the attribute "lr" to the model  `model.optimizer.lr`. It is producing another error:

### Log
AttributeErrorTraceback (most recent call last)
<ipython-input-11-3f77add48361> in <module>()
     24 
     25 model.optimizer.lr = 0.01
---> 26 model.fit(x=X, y=Y, batch_size=1, epochs=10, callbacks=[lr_schedule])

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1346           initial_epoch=initial_epoch,
   1347           steps_per_epoch=steps_per_epoch,
-> 1348           validation_steps=validation_steps)
   1349 
   1350   def evaluate(self,

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.pyc in fit_loop(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    183       m.reset_states()
    184     # Update callbacks
--> 185     callbacks.on_epoch_begin(epoch)
    186     epoch_logs = {}
    187     if steps_per_epoch is not None:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.pyc in on_epoch_begin(self, epoch, logs)
     79     logs = logs or {}
     80     for callback in self.callbacks:
---> 81       callback.on_epoch_begin(epoch, logs)
     82     self._delta_t_batch = 0.
     83     self._delta_ts_batch_begin = deque([], maxlen=self.queue_length)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.pyc in on_epoch_begin(self, epoch, logs)
    640       raise ValueError('The output of the "schedule" function '
    641                        'should be float.')
--> 642     K.set_value(self.model.optimizer.lr, lr)
    643     if self.verbose > 0:
    644       print('\nEpoch %05d: LearningRateScheduler reducing learning '

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.pyc in set_value(x, value)
   2669           (of the same shape).
   2670   """
-> 2671   value = np.asarray(value, dtype=dtype(x))
   2672   if context.executing_eagerly():
   2673     x.assign(value)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.pyc in dtype(x)
    914   ```
    915   """
--> 916   return x.dtype.base_dtype.name
    917 
    918 

AttributeError: 'float' object has no attribute 'dtype'

**Comment by tanzhenyu** [comment] 2018-07-24 20:01
Yes there is discrepancy and we're currently working on it. #20619

**Comment by tensorflowbutler** [comment] 2018-08-08 18:59
Nagging Assignee @tanzhenyu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tanzhenyu** [comment] 2018-08-08 19:39
still in review.

**Comment by tensorflowbutler** [comment] 2018-08-23 19:09
Nagging Assignee @tanzhenyu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-07 18:54
Nagging Assignee @tanzhenyu: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tanzhenyu** [comment] 2018-09-09 18:48
Last update: Review is completed and still working on implementation. It appears to be more challenging  in distributed version.

**Comment by tensorflowbutler** [comment] 2018-09-24 12:47
Nagging Assignee @tanzhenyu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by brge17** [comment] 2018-10-01 22:28
Hi @tanzhenyu any update? I'm also keen on this :)

**Comment by tensorflowbutler** [comment] 2018-10-16 12:49
Nagging Assignee @tanzhenyu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dmus** [comment] 2018-10-19 09:14
Having the same issue here, any update?

**Comment by tanzhenyu** [comment] 2018-10-19 14:53
Hi @brge17, @dmus, @nairouz, still working on this, stay tuned for  [https://www.tensorflow.org/community/roadmap](2.0)

**Comment by tensorflowbutler** [comment] 2018-11-03 12:31
Nagging Assignee @tanzhenyu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:47
Nagging Assignee @tanzhenyu: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Selimonder** [comment] 2019-03-07 09:57
I am having this error, I guess the issue is still up

`FailedPreconditionError (see above for traceback): Error while reading resource variable Adam_1/lr from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/Adam_1/lr/N10tensorflow3VarE does not exist.
	 [[node Adam_1/lr/Read/ReadVariableOp (defined at <ipython-input-23-341669cfc441>:123) ]]`

**Comment by MichelangeloConserva** [comment] 2019-03-08 11:01
Same here, news?

**Comment by tanzhenyu** [comment] 2019-04-26 17:03
It's probably because this version is too old. Can you upgrade to 1.13.1 and compile with tf.keras.optimizers.Adam?

**Comment by harshitAgr** [comment] 2019-05-10 07:15
I had same problem I changed the learning rate scheduler callback as below and it worked,

previous implementation:

class LearningRateScheduler(Callback):
    """Learning rate scheduler.
    # Arguments
        schedule: a function that takes an epoch index as input
            (integer, indexed from 0) and current learning rate
            and returns a new learning rate as output (float).
        verbose: int. 0: quiet, 1: update messages.
    """

    def __init__(self, schedule, verbose=0):
        super(LearningRateScheduler, self).__init__()
        self.schedule = schedule
        self.verbose = verbose

    def on_epoch_begin(self, epoch, logs=None):
        if not hasattr(self.model.optimizer, 'lr'):
            raise ValueError('Optimizer must have a "lr" attribute.')
        lr = float(K.get_value(self.model.optimizer.lr))
        try:  # new API
            lr = self.schedule(epoch, lr)
        except TypeError:  # old API for backward compatibility
            lr = self.schedule(epoch)
        if not isinstance(lr, (float, np.float32, np.float64)):
            raise ValueError('The output of the "schedule" function '
                             'should be float.')
        K.set_value(self.model.optimizer.lr, lr)
        if self.verbose > 0:
            print('\nEpoch %05d: LearningRateScheduler setting learning '
                  'rate to %s.' % (epoch + 1, lr))

    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        logs['lr'] = K.get_value(self.model.optimizer.lr)

new implementation: replacing 'lr' to 'learning_rate' everywhere in the code.

class LearningRateScheduler(keras.callbacks.Callback):
    """Learning rate scheduler.
    # Arguments
        schedule: a function that takes an epoch index as input
            (integer, indexed from 0) and current learning rate
            and returns a new learning rate as output (float).
        verbose: int. 0: quiet, 1: update messages.
    """

    def __init__(self, schedule, verbose=0):
        super(LearningRateScheduler, self).__init__()
        self.schedule = schedule
        self.verbose = verbose

    def on_epoch_begin(self, epoch, logs=None):
        if not hasattr(self.model.optimizer, 'learning_rate'):
            raise ValueError('Optimizer must have a "learning_rate" attribute.')
        learning_rate = float(K.get_value(self.model.optimizer.learning_rate))
        try:  # new API
            learning_rate = self.schedule(epoch, learning_rate)
        except TypeError:  # old API for backward compatibility
            learning_rate = self.schedule(epoch)
        if not isinstance(learning_rate, (float, np.float32, np.float64)):
            raise ValueError('The output of the "schedule" function '
                             'should be float.')
        K.set_value(self.model.optimizer.learning_rate, learning_rate)
        if self.verbose > 0:
            print('\nEpoch %05d: LearningRateScheduler setting learning '
                  'rate to %s.' % (epoch + 1, learning_rate))

    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        logs['lr'] = K.get_value(self.model.optimizer.learning_rate)

**Comment by iridiumblue** [comment] 2019-05-27 07:54
Thanks for that patch!

**Comment by tanzhenyu** [comment] 2019-05-28 15:49
This should have already worked in 1.14 (it seems that the new optimizers is not released before that). Closing it.

**Closed by tanzhenyu** 2019-05-28 15:49 UTC
