### ISSUE TITLE
tensorflow_serving build error on Windows, bazel 0.7, tensorflow 1.4

### ISSUE THREAD

**Issue by AKhilGarg91** [tensorflow/tensorflow#14835] opened 2017-11-23 12:32 UTC
C:\serving>bazel build //tensorflow_serving/example:mnist_saved_model
ERROR: error loading package 'tensorflow_serving/example': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 119
_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 111, in _apply_patch
_execute_and_check_ret_code(repo_ctx, cmd)
File "C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/tensorflow/workspace.bzl", line 92, in _execute_and_check_ret_code
fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/protobuf_archive -i C:/users/akhil/appdata/local/temp/_bazel_akhil/-8r_kqmg/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
.
INFO: Elapsed time: 42.062s

**Comment by AKhilGarg91** [comment] 2017-11-23 14:37
Bazel build command trying to download
https://mirror.bazel.build/github.com/google/protobuf/archive/b04e5cba356212e4e8c66c61bbe0c3a20537c5\b9.tar.gz
and this file is not accessible.

**Comment by tatatodd** [comment] 2017-11-28 01:42
@nfiedel might have some ideas here.

**Comment by kirilg** [comment] 2017-11-28 17:24
I think the problem is that the 'patch' command is not installed (see [this thread](https://github.com/tensorflow/tensorflow/issues/8919)).

It looks like you're trying to build on Windows and though we never tried it, I think TensorFlow Serving is likely not to compile there. You may want to use a Docker container.

**Comment by AKhilGarg91** [comment] 2017-11-28 19:05
@kirilg  yes I am trying on windows and its not possible. Tensorflow serving is also not compatible.

**Comment by kirilg** [comment] 2017-11-28 21:27
Perhaps not natively, but you can try compiling in a docker container - https://www.tensorflow.org/serving/docker

If you're going to use a docker container that sets up a linux environment, you can also just `apt-get install` the ModelServer (v1.4 uses TF 1.4), unless you wanted to compile from source. Apt-get instructions can be found [here](https://www.tensorflow.org/serving/setup).

**Comment by AKhilGarg91** [comment] 2017-11-29 07:24
@kirilg thanks I was just asking like in anyway it possible on windows. But I dont think so its possible. I hope they make tensorflow serving compatible to python 3.5 and later. because tensorflow need python 3.5 and serving need python 2.7.

**Comment by ymodak** [comment] 2018-10-24 21:14
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!

**Closed by ymodak** 2018-10-24 21:14 UTC
Labels: stat:community support
