### ISSUE TITLE
error LNK 2001 private:void _cdecl tensorflow::GraphDef::InternalSwap(class tensorflow::GraphDef *)

### ISSUE THREAD

**Issue by ywchen1994** [tensorflow/tensorflow#20621] opened 2018-07-08 11:58 UTC
I have built tensorflow.lib and tensorflow.dll successfully in visual studio 2015,but I'm trying to use those two files I got this error LNK 2001 private:void _cdecl tensorflow::GraphDef::InternalSwap(class tensorflow::GraphDef *)
Can anyone help me to fix this error?

OS:Win 10 visual studio 2015 
CMake 3.12.0
swigwin-3.0.12
GPU:Nivdia 1080 ti
Cuda 9.0 
Cudnn 7
I just following this website
https://hk.saowen.com/a/e1c9146c6f02026ab6d25f79c5a21a847be18c734ff0dfe58bf74b72331b604b

**Comment by tensorflowbutler** [comment] 2018-07-08 18:32
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ywchen1994** [comment] 2018-07-10 12:17
OS:Win 10 visual studio 2015
CMake 3.12.0
swigwin-3.0.12
GPU:Nivdia 1080 ti
Cuda 9.0
Cudnn 7
After compiler I added  include Path 
C:\tensorflow-master\tensorflow\contrib\cmake\build\Release;
C:\tensorflow-master\tensorflow\contrib\cmake\build\external\nsync\public
C:\tensorflow-master\tensorflow\contrib\cmake\build\protobuf\src\protobuf\src;
C:\tensorflow-master\tensorflow\contrib\cmake\build\external\eigen_archive;
C:\tensorflow-master\tensorflow\contrib\cmake\build;C:\tensorflow-master;
C:\tensorflow-master\third_party\eigen3

lib Path:
C:\tensorflow-master\tensorflow\contrib\cmake\build\Release

And 
tensorflow.lib

**Comment by drpngx** [comment] 2018-07-23 16:45
It shouldn't happen if you built from scratch. Can you confirm that you did that? You used the cmake build, right? Did you try bazel?

**Comment by tensorflowbutler** [comment] 2018-08-07 19:04
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by VCBE123** [comment] 2018-08-24 02:36
I just meet the same problem,error LNK2001

**Comment by tensorflowbutler** [comment] 2018-09-07 18:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-22 12:37
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-07 12:36
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by MetaPeak** [comment] 2018-10-18 02:41
I meet the same problem in tensorflow 1.9 and 1.10 version, tensorflow 1.8 doesn't have this problem. May be this is a bug in tensorflwo windows version, since google say they won't support build tensorflow on windows with cmake.

**Comment by ymodak** [comment] 2018-10-26 21:13
Closing due to staleness. Please use the latest version for TensorFlow and build again. Feel free to open a new issue if it still persists. Thanks!

**Closed by ymodak** 2018-10-26 21:13 UTC
Labels: stat:awaiting response, type:build/install
