### ISSUE TITLE
When ryzen build tf_to_gpu_binary.exe failed: error executing command error

### ISSUE THREAD

**Issue by woojh3690** [tensorflow/tensorflow#46680] opened 2021-01-26 02:16 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS : Windows 10 20H2
- TensorFlow version: 2.4.1
- Python version: python=3.9
- Building anaconda env
- Bazel version : using bazelisk
- CUDA/cuDNN version: cuda 11.1, cuDNN 8.0.5
- GPU model and memory: RTX2080, 8G

When i build tensorflow in 10900k build succeed. But error is occur when i try to build ryzen 5600x or ryzen3700x.

> INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/user/_bazel_user/d3ty3xtx/sandbox
ERROR: C:/users/user/documents/cpplibrarys/tensorflow/tensorflow/core/kernels/mlir_generated/BUILD:149:1: compile tensorflow/core/kernels/mlir_generated/abs_i64_kernel_cubin.sm_75.bin failed (Exit 1): tf_to_gpu_binary.exe failed: error executing command
  cd C:/users/user/_bazel_user/d3ty3xtx/execroot/org_tensorflow
bazel-out/x64_windows-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.exe --same_shape=0,1 --unroll_factors=4 --tile_sizes=256 --arch=sm_75 --input=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_i64.mlir --output=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_i64_kernel_cubin.sm_75.bin
Execution platform: @local_execution_config_platform//:platform
2021-01-26 17:38:55.379641: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
warning: Linking two modules of different data layouts: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/nvvm/libdevice/libdevice.10.bc' is 'e-i64:64-v16:16-v32:32-n16:32:64' whereas 'acme' is 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'
2021-01-26 17:38:55.768832: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
2021-01-26 17:38:55.845907: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295
2021-01-26 17:38:55.847744: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:97] Internal: Lowering to LLVM IR failed.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/users/user/documents/cpplibrarys/tensorflow/tensorflow/python/data/experimental/service/BUILD:11:1 compile tensorflow/core/kernels/mlir_generated/tanh_f32_kernel_cubin.sm_75.bin failed (Exit 1): tf_to_gpu_binary.exe failed: error executing command
  cd C:/users/user/_bazel_user/d3ty3xtx/execroot/org_tensorflow
bazel-out/x64_windows-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.exe --same_shape=0,1 --unroll_factors=4 --tile_sizes=256 --arch=sm_75 --input=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/tanh_f32.mlir --output=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/tanh_f32_kernel_cubin.sm_75.bin
Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 69.840s, Critical Path: 24.63s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by amahendrakar** [comment] 2021-01-28 08:15
@woojh3690,
TensorFlow 2.4 is compatible with only upto Python v3.8. Could you please building TensorFlow with Python v3.8 and check if you are facing the same error?

For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu). 
Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1

Thanks!

**Comment by woojh3690** [comment] 2021-01-28 08:55
Ok, i'll try python=3.8, cuDnn 8.0, cuda 11.0

**Comment by woojh3690** [comment] 2021-01-28 14:17
> INFO: Found 1 target...
ERROR: C:/users/user/documents/cpplibrarys/tensorflow/tensorflow/core/kernels/mlir_generated/BUILD:149:1: compile tensorflow/core/kernels/mlir_generated/abs_f16_kernel_cubin.sm_80.bin failed (Exit 1): tf_to_gpu_binary.exe failed: error executing command
  cd C:/users/user/_bazel_user/d3ty3xtx/execroot/org_tensorflow
bazel-out/x64_windows-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.exe --same_shape=0,1 --unroll_factors=4 --tile_sizes=256 --arch=sm_80 --input=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_f16.mlir --output=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_f16_kernel_cubin.sm_80.bin
Execution platform: @local_execution_config_platform//:platform
2021-01-28 18:26:08.630923: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
warning: Linking two modules of different data layouts: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/nvvm/libdevice/libdevice.10.bc' is '' whereas 'acme' is 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'
2021-01-28 18:26:08.753770: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
2021-01-28 18:26:08.979474: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295
2021-01-28 18:26:08.982849: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:97] Internal: Lowering to LLVM IR failed.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2002.509s, Critical Path: 284.78s
INFO: 4364 processes: 4364 local.
FAILED: Build did NOT complete successfully


Yep, same error

**Comment by amahendrakar** [comment] 2021-01-31 10:32
@woojh3690,
Please run the `bazel clean --expunge` command before building and let us know if you are facing the same issue. Thanks!

**Comment by woojh3690** [comment] 2021-02-01 02:25
Steel same error.

>DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/user/_bazel_user/d3ty3xtx/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/user/_bazel_user/d3ty3xtx/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (410 packages loaded, 26423 targets configured).
INFO: Found 1 target...
ERROR: C:/users/user/documents/cpplibrarys/tensorflow/tensorflow/core/kernels/mlir_generated/BUILD:149:1: compile tensorflow/core/kernels/mlir_generated/abs_i32_kernel_cubin.sm_80.bin failed (Exit 1): tf_to_gpu_binary.exe failed: error executing command
  cd C:/users/user/_bazel_user/d3ty3xtx/execroot/org_tensorflow
bazel-out/x64_windows-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.exe --same_shape=0,1 --unroll_factors=4 --tile_sizes=256 --arch=sm_80 --input=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_i32.mlir --output=bazel-out/x64_windows-opt/bin/tensorflow/core/kernels/mlir_generated/abs_i32_kernel_cubin.sm_80.bin
Execution platform: @local_execution_config_platform//:platform
2021-02-01 11:12:03.899522: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
warning: Linking two modules of different data layouts: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/nvvm/libdevice/libdevice.10.bc' is '' whereas 'acme' is 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'
2021-02-01 11:12:04.042150: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0
2021-02-01 11:12:04.119817: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295
2021-02-01 11:12:04.122477: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:97] Internal: Lowering to LLVM IR failed.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3896.167s, Critical Path: 287.98s
INFO: 9422 processes: 9422 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment] 2021-02-08 17:24
Error is

```
2021-01-26 17:38:55.847744: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:97] Internal: Lowering to LLVM IR failed.
```

Adding MLIR people

**Comment by jpienaar** [comment] 2021-02-08 17:35
This is failure in TF KernelGen component (@sherhut FYI), could you set MLIR_CRASH_REPRODUCER_DIRECTORY and attach the produced logs? I recall seeing an error like this but also saw it fixed. Would it also be possible to verify at head?

**Comment by pifon2a** [comment] 2021-02-08 18:33
Interesting. `tf_to_gpu_binary` was removed 2 month ago. I also think that it was before the MLIR-GPU-KERNEL build was fixed by @sherhut on Windows at all.

**Comment by sherhut** [comment] 2021-02-08 20:45
This should be disabled by default. The tool that fails should only be triggered when building with `--define tensorflow_enable_mlir_generated_gpu_kernels=1`, which is true for CUDA but should be false for ROCm.

Can you share your exact bazel invocation and the contents of your bazelrc file?

**Comment by woojh3690** [comment] 2021-02-09 01:32
bazel call is

bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\users\woojh\source\repos\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/woojh/Anaconda3/envs/tf/python.exe
INFO: Reading rc options for 'build' from c:\users\woojh\source\repos\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --_**define=tensorflow_enable_mlir_generated_gpu_kernels=0**_ --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2


.bazelrc file in line 191

//#Enable the mlir generated GPU kernels only for cuda builds.
build --define=tensorflow_enable_mlir_generated_gpu_kernels=0
//# This is a more specific option, so it takes precedence over the line above for cuda builds.
build:using_cuda --define=tensorflow_enable_mlir_generated_gpu_kernels=1

**Comment by woojh3690** [comment] 2021-02-09 02:09
Oh my mistake.
I should delete the comment in bazel build command.
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package`

Build success when i delete comment like this.
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true

**Comment by sherhut** [comment] 2021-02-09 08:33
This looks like the invocation for the cuda build. If I understand the original report correctly, the cuda build is working but it is failing for the rocm version. Is this correct?

Can you share the rocm build invocation, as well?

Also, do you have the `TF_NEED_CUDA` environment variable set? 

Finally, could you try and pass the `--define=tensorflow_enable_mlir_generated_gpu_kernels=0` directly in the bazel invocation?

**Comment by TimIgoe** [comment] 2021-02-11 16:10
I'm getting what looks to me as the same error, however, I'm building on a Ubuntu instance running on an older AMD APU, with an nVidia GPU (trying to build cuda, not rocm).

`ERROR: /home/timigoe/MachineLearning/tensorflow/tensorflow/core/kernels/mlir_generated/BUILD:149:1: compile tensorflow/core/kernels/mlir_generated/abs_f16_kernel_cubin.sm_30.bin failed (Exit 1): tf_to_gpu_binary failed: error executing command
  (cd /home/timigoe/.cache/bazel/_bazel_timigoe/4b1b04ca1aff23a878ffc3a3edf46634/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary '--same_shape=0,1' '--unroll_factors=4' '--tile_sizes=256' '--arch=sm_30' '--input=bazel-out/host/bin/tensorflow/core/kernels/mlir_generated/abs_f16.mlir' '--output=bazel-out/host/bin/tensorflow/core/kernels/mlir_generated/abs_f16_kernel_cubin.sm_30.bin')
Execution platform: @local_execution_config_platform//:platform
2021-02-11 16:04:53.175192: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
warning: Linking two modules of different data layouts: '/usr/local/cuda-11.2/nvvm/libdevice/libdevice.10.bc' is 'e-i64:64-v16:16-v32:32-n16:32:64' whereas 'acme' is 'e-i64:64-i128:128-v16:16-v32:32-n16:32:64'

2021-02-11 16:04:53.360741: W tensorflow/stream_executor/gpu/asm_compiler.cc:235] Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal   : Value 'sm_30' is not defined for option 'gpu-name'

2021-02-11 16:04:53.363705: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:97] Internal: Lowering to LLVM IR failed.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

**Comment by sherhut** [comment] 2021-02-11 16:51
That error message is misleading. In fact your CUDA installation is too new for the compute version you are requesting. I believe `sm_30` was dropped in CUDA 11. The fallback to the driver is not currently implemented for build time compilation.

If your card really requires `sm_30` I would suggest downgrading to an older CUDA version that supports it.

**Comment by TimIgoe** [comment] 2021-02-11 17:10
That wasn't clear from nVidia's end. Just assumed it was like GPU drivers where they just seem to keep going - will look and report back if its still a problem, sorry for any interruptions! :D

**Comment by woojh3690** [comment] 2021-02-15 09:04
Oh @sherhut you right!
Build completed successfully when I pass the `--define=tensorflow_enable_mlir_generated_gpu_kernels=0` directly in the bazel invocation!
like
`bazel build --config=opt --config=cuda --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package`

Oh thank you! 😍😍

**Closed** 2021-03-25 08:33 UTC
Labels: TF 2.4, subtype:windows, type:build/install
