### ISSUE TITLE
RuntimeError when using distribution strategy (Distributed training in TensorFlow: Keras Tutorial throws error)

### ISSUE THREAD

**Issue by johnstill** [tensorflow/tensorflow#28931] opened 2019-05-22 14:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Cent OS 7
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0 / 7.3.1 (conda installed cudnn)
- GPU model and memory: 8x GeForce RTX 2080 / 7951MiB each

**Describe the current behavior**
Model fails to train, raising a `RuntimeError: Replica-local variables may only be assigned in a replica context.` I was able to reproduce this issue just by using the official tutorial, so that's the code given below rather than mine.

**Describe the expected behavior**
This code should correctly utilize my GPUs.

**Code to reproduce the issue**
This code is taken straight from [the tutorial](https://www.tensorflow.org/tutorials/distribute/keras)
```python
#!/usr/bin/env python
import tensorflow as tf
import tensorflow_datasets as tfds

import os
datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)

mnist_train, mnist_test = datasets['train'], datasets['test']
strategy = tf.distribute.MirroredStrategy()

num_train_examples = info.splits['train'].num_examples
num_test_examples = info.splits['test'].num_examples

BUFFER_SIZE = 10000
BATCH_SIZE_PER_REPLICA = 64
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

train_dataset = mnist_train.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
eval_dataset = mnist_test.map(scale).batch(BATCH_SIZE)

with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(loss='sparse_categorical_crossentropy',
                  optimizer=tf.keras.optimizers.Adam(),
                  metrics=['accuracy'])
# Define the checkpoint directory to store the checkpoints
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
    tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                    save_weights_only=True),
    tf.keras.callbacks.LearningRateScheduler(decay),
]

model.fit(train_dataset, epochs=10, callbacks=callbacks)
```

**Other info / logs**
Full output including traceback:
```sh
$ CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python -m mnist_tf_check

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING: Logging before flag parsing goes to stderr.
W0522 08:53:17.781122 140396075140928 deprecation.py:323] From /home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-22 08:53:17.916369: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-05-22 08:53:17.931970: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200015000 Hz
2019-05-22 08:53:17.934971: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55cb744b5090 executing computations on platform Host. Devices:
2019-05-22 08:53:17.935018: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-22 08:53:20.146420: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55cb74533ed0 executing computations on platform CUDA. Devices:
2019-05-22 08:53:20.146509: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.146535: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.146556: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (2): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.146591: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (3): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.146613: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (4): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.146634: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (5): GeForce RTX 2080, Compute Capability 7.5
2019-05-22 08:53:20.148829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:08:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.149286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:09:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.149717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 2 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:84:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.150156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 3 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:85:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.150586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 4 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:88:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.151019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 5 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:89:00.0
totalMemory: 7.77GiB freeMemory: 7.62GiB
2019-05-22 08:53:20.152662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1, 2, 3, 4, 5
2019-05-22 08:53:20.169207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-22 08:53:20.169256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 2 3 4 5
2019-05-22 08:53:20.169281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N N N N N N
2019-05-22 08:53:20.169326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N N N N N
2019-05-22 08:53:20.169345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 2:   N N N N N N
2019-05-22 08:53:20.169379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 3:   N N N N N N
2019-05-22 08:53:20.169398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 4:   N N N N N N
2019-05-22 08:53:20.169416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 5:   N N N N N N
2019-05-22 08:53:20.171379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7416 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:08:00.0, compute capability: 7.5)
2019-05-22 08:53:20.171960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7416 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080, pci bus id: 0000:09:00.0, compute capability: 7.5)
2019-05-22 08:53:20.172517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 7416 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080, pci bus id: 0000:84:00.0, compute capability: 7.5)
2019-05-22 08:53:20.173011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 7416 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080, pci bus id: 0000:85:00.0, compute capability: 7.5)
2019-05-22 08:53:20.173526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 7416 MB memory) -> physical GPU (device: 4, name: GeForce RTX 2080, pci bus id: 0000:88:00.0, compute capability: 7.5)
2019-05-22 08:53:20.174043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 7416 MB memory) -> physical GPU (device: 5, name: GeForce RTX 2080, pci bus id: 0000:89:00.0, compute capability: 7.5)
2019-05-22 08:53:20.184131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1, 2, 3, 4, 5
2019-05-22 08:53:20.185576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-22 08:53:20.185617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 2 3 4 5
2019-05-22 08:53:20.185638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N N N N N N
2019-05-22 08:53:20.185656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N N N N N
2019-05-22 08:53:20.185673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 2:   N N N N N N
2019-05-22 08:53:20.185692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 3:   N N N N N N
2019-05-22 08:53:20.185709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 4:   N N N N N N
2019-05-22 08:53:20.185749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 5:   N N N N N N
2019-05-22 08:53:20.187543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 7416 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:08:00.0, compute capability: 7.5)
2019-05-22 08:53:20.188006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:1 with 7416 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080, pci bus id: 0000:09:00.0, compute capability: 7.5)
2019-05-22 08:53:20.188405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:2 with 7416 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080, pci bus id: 0000:84:00.0, compute capability: 7.5)
2019-05-22 08:53:20.188747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:3 with 7416 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080, pci bus id: 0000:85:00.0, compute capability: 7.5)
2019-05-22 08:53:20.189115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:4 with 7416 MB memory) -> physical GPU (device: 4, name: GeForce RTX 2080, pci bus id: 0000:88:00.0, compute capability: 7.5)
2019-05-22 08:53:20.189446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:5 with 7416 MB memory) -> physical GPU (device: 5, name: GeForce RTX 2080, pci bus id: 0000:89:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stilljm/tensorflow_is_terrible/mnist_tf_check.py", line 38, in <module>
    metrics=['accuracy'])
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 499, in compile
    sample_weights=self.sample_weights)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1844, in _handle_metrics
    return_stateful_result=return_stateful_result))
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1800, in _handle_per_output_metrics
    stateful_metric_result = _call_stateful_fn(stateful_fn)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1773, in _call_stateful_fn
    fn, y_true, y_pred, weights=weights, mask=mask)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 852, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 438, in __call__
    update_op = self.update_state(*args, **kwargs)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 98, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 651, in update_state
    matches, sample_weight=sample_weight)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 604, in update_state
    update_total_op = state_ops.assign_add(self.total, values)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/ops/state_ops.py", line 191, in assign_add
    return ref.assign_add(value)
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/distribute/values.py", line 911, in assign_add
    _assert_replica_context()
  File "/home/stilljm/.conda/envs/tf-1.13/lib/python3.7/site-packages/tensorflow/python/distribute/values.py", line 894, in _assert_replica_context
    "Replica-local variables may only be assigned in a replica context.")
RuntimeError: Replica-local variables may only be assigned in a replica context.
```

**Comment by gadagashwini** [comment] 2019-05-23 10:44
I was able to reproduce the issue reported here with Tensorflow 1.13.1. I got the error RuntimeError: Replica-local variables may only be assigned in a replica context.

**Comment by guptapriya** [comment] 2019-05-29 01:23
Hi, this tutorial is supposed to work only with TF 1.x nightly, and the upcoming 1.14 release. It is expected to fail with 1.13. 
@yashk2810 - would you mind updating the tutorial to install tf-nightly at the top so that it's clear what it is supposed to work with? by default, the external colab currently uses 1.13 so this fails. 
Would be good to check this for all the other tutorials as well.

**Comment by yashk2810** [comment] 2019-05-29 01:29
The notebook should be updated by tomorrow. Also, I would recommend looking at tensorflow.org/alpha. See the distributed keras notebook here (https://www.tensorflow.org/alpha/tutorials/distribute/keras)

**Comment by AlainConnor** [comment] 2019-05-29 01:32
I want to know where can be find the tutorial about tf1.13 at low level api ?

**Comment by nikitamaia** [comment] 2020-06-24 20:23
Closing this issue since the tutorial mentioned was expected to fail with 1.13.

**Closed by nikitamaia** 2020-06-24 20:23 UTC
Labels: comp:dist-strat, comp:keras, type:bug

**Comment by dtlam26** [comment] 2020-12-22 01:17
I am using 1.14 and when I start my eval session I got the same termination error
