### ISSUE TITLE
Tensorflow 2.2 takes much more time than 2.1/2.0 to start training with "keras.fit"

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#40036] opened 2020-06-01 00:53 UTC
**System information**
- OS Platform and Distribution:Ubuntu 18.04
- TensorFlow installed from (source or binary):conda (I trided pip, same)
- TensorFlow version:2.2
- Python version:3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory:  Titan RTX * 2  = 48GB

Tensorflow 2.2 takes much more time than 2.1/2.0 to start training, after called "keras.fit".

```
2020-06-01 10:16:44.991459: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-01 10:16:46.235945: W tensorflow/stream_executor/gpu/asm_compiler.cc:81] Running ptxas --version returned 256
2020-06-01 10:16:46.328871: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-06-01 10:16:48.148004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-01 10:23:36.473814: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
```

It stucks about 7 mins to start training.

However, in 2.1

```
INFO:tensorflow:batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
I0531 20:55:03.956965 139684401002304 cross_device_ops.py:760] batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
I0531 20:55:14.695299 139684401002304 cross_device_ops.py:760] batch_all_reduce: 436 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
2020-05-31 20:55:39.932592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-31 20:55:41.811100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-31 20:55:48.718710: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
```

**Comment by zhen8838** [comment] 2020-06-01 02:07
I have same issue. https://github.com/tensorflow/tensorflow/issues/35346#issuecomment-636463855

I think it cause by AutoGraph compiled slow.

**Comment by Saduf2019** [comment] 2020-06-01 04:45
@edwardyehuang 
Please provide with simple indented stand alone code for us to replicate the issue faced.

**Comment by MakeCent** [comment] 2020-06-01 12:39
Same issue here. I think the suspicious output is below message:

_Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once._

But I don't know how to fix it. I seems to be the cuda problem and I use cuda and cudnn installed automatically by using `conda install tensorflow=2.2.0`

**Comment by zhen8838** [comment] 2020-06-02 04:43
[code for TF 2.2 ](https://colab.research.google.com/drive/1YDTrSobTvRCx2IJOWANVrKTMvkG7qnK6?usp=sharing)
get_concrete_function Cost  155.99647617340088
Run First Time Cost  115.89516520500183
Run Second Time Cost  20.85046076774597

[code for TF 2.1 ](https://colab.research.google.com/drive/1RJ_owqFyNyerfFfrHxy8u9thkwVzQCnK?usp=sharing)
get_concrete_function Cost  136.64350962638855
Run First Time Cost  127.72333002090454
Run Second Time Cost  19.65573525428772

@Saduf2019 Can you check my code ? My model may be a little complicated, but every time I start training, I have to wait for tf.function to compile for a long time, which is unbearable.

I want to know is there any way to speed up the compilation of tf.function, or is it necessary for me to modify the code?

**Comment by Saduf2019** [comment] 2020-06-02 14:12
I am able to replicate this issue, please find the gist for [tf2.2](https://colab.sandbox.google.com/gist/Saduf2019/76937519e979fc5a7794b9ca3f17709f/gou2_2.ipynb) and [tf 2.1](https://colab.sandbox.google.com/gist/Saduf2019/3e0ace846be0178c03c33311c477f176/untitled215.ipynb).

**Comment by tomerk** [comment] 2020-06-22 19:41
@rohan100jain this is an example of a painfully slow tf.function tracing + compilation

**Comment by nathanin** [comment] 2020-06-28 17:20
Hi for what it's worth I also get this with a much simpler model, although only really noticeably when using tf.distribute.MirroredStrategy where I'm seeing it take about 8 mins to spin up a VGG16 on 4 GPUS. I'm not aware of a way to attach multiple GPU's to a colab, and when I paste my script into colab with a GPU runtime the lag before training start is just fine, but here is is a self-contained [gist](https://gist.github.com/nathanin/c2fe9fd8a5af341997bed35ce9a96f5e) anyway. I can also say that running with the `strategy.experimental_run_v2` function in TF 2.1 mitigates the issue in my case.

In both cases I'm running Docker containers built on top of `rapidsai/rapidsai:cuda10.1-base-ubuntu18.04` where TensorFlow was installed via pip, and using 2080Ti's.

**Comment by Daniel451** [comment] 2020-07-16 16:24
> Same issue here in TF 2.2.0. That makes each model.fit only start after 1 minitue waiting which not occurs in TF 2.1.0. I think the suspicious output is below message:
> 
> _Relying on driver to perform ptx compilation. 
> Modify $PATH to customize ptxas location.

I'd also suspect that. To me, this looks like (cu)bins for the different `sm_XX` levels (compute capabilities for the different NVIDIA GPUs) are not included in the `cmake` builds (anymore?), thus TensorFlow needs to contact the driver and compile stuff "on the fly", which takes a forever.

Can someone official confirm that?

**Comment by tkoch96** [comment] 2020-07-24 20:04
Does anyone have a fix for this?

**Comment by Daniel451** [comment] 2020-07-24 20:48
@tkoch96 @edwardyehuang @nathanin @MakeCent 

I was having a look into the problem and definitely suspect cubins and libraries missing to be the root of the problem.

For example, if you base your docker image on `rapidsai/rapidsai:cuda10.1-base-ubuntu18.04`, the `-base` will not include some cuda binaries, including `ptxas` for the "just in time" compilation of kernels and whatever else TensorFlow might need. If TensorFlow itself now does not include pre-compiled kernels for the requested operations / your GPU, then you run into the problem of having neither pre-compiled kernels to execute nor ptxas itself and the necessary cubins to let it compile itself during runtime.
This is why TensorFlow then delegates this responsibility to the driver. Takes very long and for me this always fails.

My current workaround:
- build a docker container based on `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04`
This includes `ptxas` binary and all the other cuda bins we need to compile stuff
- build TensorFlow 2.2 from source in this container
- enable all necessary optimization and cuda flags
- include all cuda compute capabilities you need for your GPUs

This works and then TensorFlow 2.2 GPU runs smooth again. Tested on a compute server with 4x TITAN RTX.

Your custom TensorFlow docker images should look something like this:
```
# get bazel 2.0.0 up and running
WORKDIR /build/tmp
RUN wget https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-linux-x86_64.sh -O bazel.sh
RUN chmod +x bazel.sh

RUN ./bazel.sh --prefix=/tmp/bazel

ENV PATH="$PATH:/tmp/bazel/bin"
```
Then you'll download TensorFlow and checkout to `r2.2`
```
WORKDIR /build-tf
RUN git clone https://github.com/tensorflow/tensorflow.git tensorflow
WORKDIR /build-tf/tensorflow
RUN git checkout r2.2
```

And do not forget to set all necessary variables for TF compilation and later on for your container:
```
ENV GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-7"
ENV CI_BUILD_PYTHON=python
ENV PYTHON_PATH="/path/to/python/bin/python"
ENV PYTHON_BIN_PATH="/path/to/python/bin/python"
ENV PYTHON_LIB_PATH="/path/to/python/lib/python3.8/site-packages"
ENV LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV CUDA_TOOLKIT_PATH="/usr/local/cuda-10.1"
ENV TF_NEED_CUDA=1
ENV TF_NEED_TENSORRT=0
ENV TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.0,7.5
ENV TF_CUDA_VERSION=10.1
ENV TF_CUDNN_VERSION=7
```

Most import step here is:
```
ENV TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.0,7.5
```
This includes kernels for all GTX 1000, RTX 2000, RTX Titan GPUs.

Then compile and build wheel
```
RUN bazel build --config=v2 --config=cuda --config=xla //tensorflow/tools/pip_package:build_pip_package

RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

Make sure that all CUDA paths are set correctly. I noticed that even the NVIDIA image itself links stuff to `/lib/nvidia/` and other paths that **do not** exist in the container. For `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04` the `LD_LIBRARY_PATH` is `/usr/local/cuda...`.

Additionally, to have `ptxas` and other cuda bins, you need to add the cuda bin path to your `$PATH`:
```
ENV PATH="/usr/local/cuda/bin:$PATH"
```

**Comment by tomerk** [comment] 2020-07-24 21:43
Adding @sanjoy who may have more familiarity with the cuda setup than I do.

It also seems related to https://github.com/tensorflow/tensorflow/issues/33002

**Comment by Daniel451** [comment] 2020-07-30 02:06
@dspyrhsu @tkoch96 @edwardyehuang @nathanin @MakeCent
Interestingly, self-compiled container with `TF 2.3.0` starts trainings fast with 1 GPU, but takes very long to start with 4 GPUs. Any experiences already with that?

I will test this a little more with 1-4 GPUs, different scripts and also vanilla TF GPU docker / conda TF GPU setups (as soon as available) and report.

**Comment by edwardyehuang** [comment] 2020-07-30 04:27
I did not try the single GPU. I tried 2 or 8 GPUs (Titan RTX or V100). Both are slow. I even feel it is slower than 2.2

**Comment by edwardyehuang** [comment] 2020-08-10 08:47
@Saduf2019 @zhen8838 @tomerk 
In my recent experiments, I observed some insteresting result.
I have 4 machines. Seems this training slow start issue only happened on 2 of them.

```
Machine 0: Intel i9 9820X, 64GB, 2 * Titan RTX
Machine 1: Intel Xeon ?, 186GB, 2 * RTX 6000
Machine 2: Intel Xeon ?, 32GB, 2 * V100 32GB
Machine 3: Intel Xeon Gold 6126, 98GB, 2 * V100 32GB
```

The issue only occur on machine = 0 or 1

**Comment by viet2411** [comment] 2020-09-03 02:00
Does anyone have a fix for this? 
It takes about 8~10mins before each epoch
I'm using 8 GPUs (Titan Xp) with TF 2.3

**Comment by Harrypotterrrr** [comment] 2020-10-01 19:26
@viet2411  same GPU  Titan Xp with TF 2.3
I use about 5min before the first epoch.

**Comment by fantasyearl** [comment] 2020-10-14 07:56
The method provided by @Daniel451 is worked. Tested on RTX 2080.
The only problem is the built docker image is too large. Make it hard to deploy.
I already try my best to optimize the Dockerfile, however, the image size is still about 20GB...
BTW, Thank you @Daniel451

**Comment by dev0x13** [comment] 2020-10-27 09:25
@sanjoy 

I think I found the root cause of the slowdown.

Here is the problematic block of code in TF 2.2.0 PTX compiler (https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/stream_executor/gpu/asm_compiler.cc#L174): 
```cpp
  if (!env->FileExists(ptxas_path).ok()) {
    // Rely on subprocess invocation to find the correct binary.
    ptxas_path = "ptxas";
  }
  VLOG(2) << "Using ptxas at " << ptxas_path;
```

While this is the exact same place, but in TF 2.1.0 (https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/stream_executor/gpu/asm_compiler.cc#L173) is:
```cpp
  TF_RETURN_IF_ERROR(env->FileExists(ptxas_path));
  VLOG(2) << "Using ptxas at " << ptxas_path;
```

Now here is the workflow of what is happening in the TF 2.2.0:
1. `CheckRedzones` method is being invoked for hundred times during initialization/inference on a CUDA GPU (e.g. when autotuning cuDNN kernels).
2. Each invocation leads to redzone checker PTX code blob compilation or retrieving a precompiled blob from cache. Normally, this PTX code should be compiled once and then cached, and it really happens when `ptxas` is installed to the system within a CUDA toolkit. However, if if is not installed (e.g. if only CUDA runtime libraries are presented), then ptxas binary name resolution is being delegated to the OS at the asm_compiler.cc:L174.
3. After ptxas binary name resolution was delegated to the OS, the asm_compiler code does some actions trying to compile the PTX code: **it writes the PTX blob to the filesystem temporary folder**, constructs the compilation command, invokes the command, obviously fails (since ptxas is not installed), deletes the temporary file and then returns with an error.

Thus, during the GPU model initialization/inference, this workflow repeats _hundreds_ or _thousands_ of times leading to _hundreds_ or _thousands_ of IO operations. You can make sure of it by setting the TF logging environment variable `TF_CPP_VMODULE=asm_compiler=2` and then running GPU stuff with TF. You'll see a continuous log of unsuccessful attempts to compile PTX for redzone checking consisting of continuous writes to the disk.

Now let's take a look at the TF 2.1.0 code (see above). The major difference is that TF 2.1.0 does not rely on subprocess invocation to find the correct ptxas binary and immediately returns with an error if it fails to find the binary itself. By this simple action, TF 2.1.0 avoid doing a lot of repeating and useless stuff which TF 2.2.0 does. I was able to fix the slowdown in TF 2.2.0 by changing this tiny piece of code back to 2.1.0 version and it worked like a charm.

Hope this helps!

**Comment by sanjoy** [comment] 2020-10-30 04:35
Wow, good catch!  Would you be willing to send a PR?  It seems it'd be sufficient to cache the first failure (to find `ptxas`) and short circuit the subsequent invocations?

CC @cheshire

**Comment by cheshire** [comment] 2020-10-30 19:21
@dev0x13 Thanks a lot for finding this!

The change you've mentioned was introduced to fix another bug (https://github.com/tensorflow/tensorflow/issues/33375), so it's not that easy to rollback (users have complained that `ptxas` is not found in their `PATH`).

As far as I understand, the gist of the problem is that we cache the success, but not the failure of the lookup. Would you be willing to write a PR fixing this?

**Comment by cheshire** [comment] 2020-10-30 21:22
Subprocess invocation is hard/resource consuming to do in general.

Note that this should also be fixed for good with CUDA 11.1 which bundles ptxas as a library which can be linked in instead, cf. https://docs.nvidia.com/cuda/ptx-compiler-api/index.html

**Comment by dev0x13** [comment] 2020-10-30 21:45
@sanjoy @cheshire 

Thank you, guys. I am going to submit a PR fixing this within a week or so.
That's a good point about CUDA 11.1, hopefully this feature will be employed in the future TF versions.

**Comment by jakkes** [comment] 2020-12-01 10:23
Can confirm upgrading to CUDA toolkit 11.1 solved this for me.

**Closed** 2020-12-15 18:32 UTC
Labels: TF 2.2, comp:keras, type:performance

**Comment by xehartnort** [comment] 2021-02-06 00:04
I am sorry to open this issue again, but I was experiencing a similar problem when installing tensorflow-gpu from conda. I found out that ptxas a some more executables are missing in the cudatoolkit packages provided by conda (I've tried nvidia and conda-forge channels). After installing the package cudatoolkit-dev from the conda-forge channel (`conda install -c conda-forge cudatoolkit-dev`), the binary ptxas appeared in my conda environment and finally the problem was solved :)

**Comment by nosound2** [comment] 2021-02-09 21:59
I hit the same problem (major slowdown) after upgrading to `CUDA 11.2` and `tf 2.4.1`. Downgrading to `CUDA 11.1` and then also to `tf 2.4.0` did not help. But then I noticed that @xehartnort is speaking about missing ptxas executables. I checked that the executables are in place:

```
[user.user@gauss local]$ find . -name ptxas
./cuda-10.2/bin/ptxas
./cuda-10.0/bin/ptxas
./cuda-10.1/bin/ptxas
./cuda-11.2/bin/ptxas
./cuda-11.1/bin/ptxas
```

but the PATH variable was not set, as required. Adding these lines to `~/.bash_profile` solved the problem:

```
PATH=$PATH:/usr/local/cuda-11.1/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.1/lib64
```

Now I am happy man again, until the next tensorflow issue.

**Comment by Cyril9227** [comment] 2021-02-10 04:03
> I am sorry to open this issue again, but I was experiencing a similar problem when installing tensorflow-gpu from conda. I tried all the fixes given in this issue but none of them worked. I found out that ptxas a some more executables are missing in the cudatoolkit packages provided by conda (I've tried nvidia and conda-forge channels). After installing the package cudatoolkit-dev from the conda-forge channel (`conda install -c conda-forge cudatoolkit-dev`), the binary ptxas appeared in my conda environment and finally the problem was solved :)

Worked for me (cuda 10.1), thank you

**Comment by yywangvr** [comment] 2021-02-25 08:57
In ubuntu, the following codes fixed my issue:

```console
ptxas --version
sudo apt install nvidia-cuda-toolkit

```

**Comment by vfinel** [comment] 2021-03-12 09:30
> 
> 
> I am sorry to open this issue again, but I was experiencing a similar problem when installing tensorflow-gpu from conda. I tried all the fixes given in this issue but none of them worked. I found out that ptxas and some more executables are missing in the cudatoolkit packages provided by conda (I've tried nvidia and conda-forge channels). After installing the package cudatoolkit-dev from the conda-forge channel (`conda install -c conda-forge cudatoolkit-dev`), the binary ptxas appeared in my conda environment and finally the problem was solved :)

Worked for me too ! Thanks 
Tensorflow 2.4.1
CUDA Version: 11.2

**Comment by ironbar** [comment] 2021-03-18 14:04
In the case that there is no cudatoolkit-dev version available, for example for cuda 11. I have found that it is possible to simply copy that file from the cuda docker to conda and it works like charm.

```
docker run nvidia/cuda:11.2.2-devel-ubuntu20.04 cat /usr/local/cuda/bin/ptxas > /home/gbarbadillo/miniconda3/envs/goose_dev/bin/ptxas
chmod u+x /home/gbarbadillo/miniconda3/envs/goose_dev/bin/ptxas
```

**Comment by gitlabspy** [comment] 2022-01-19 09:11
CUDA11.0 + tf2.4.0 with the ptxas executable in the right place, still suffer from slow start. I observed that more gpus cause slower training start up .... 🆘  😢
