### ISSUE TITLE
GPU usage is extremely unstable in distributed setup on aws

### ISSUE THREAD

**Issue by perhapszzy** [tensorflow/tensorflow#4047] opened 2016-08-25 20:26 UTC
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN:  CUDA 7.5, cuDNN 4.0

If installed from binary pip package, provide:
Installed from the following pip package: (0.10.0rc)
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

### Steps to reproduce
I'm running distributed tf with GPU on 3 machines (the ps machine doesn't have GPU). The commands to start the cluster:
On ps machine0:
```
python async.py \
--job_name='ps' \
--task_id=0 \
--ps_hosts='machine0:2222' \
--worker_hosts='machine1:2222,machine2:2222'
```

On g2.2xlarge machine 1:
```
python async.py \
--job_name='worker' \
--task_id=0 \
--ps_hosts='machine0:2222' \
--worker_hosts='machine1:2222,machine2:2222'
```

On g2.2xlarge machine 2:
```
python async.py \
--job_name='worker' \
--task_id=1 \
--ps_hosts='machine0:2222' \
--worker_hosts='machine1:2222,machine2:2222'
```

The code:  [async.txt](https://github.com/tensorflow/tensorflow/files/437980/cifar10_async_dist_train.txt)

For the first few thousands of iteration, it worked perfectly fine, but the GPU usage drop to almost 0 after that. (actually it fluctuated a lot from 80 -> 50 ->0 ->80)

### What have you tried?
1.  I tried to restart the works and it worked for a few rounds then the problem come over again.

### Logs or other output that would be helpful
The log after restart. The speed for the first few rounds is ~0.36 sec/batch and the GPU usage is ~90%. But the speed drop down to ~1 sec/batch quickly.

```
2016-08-25 20:04:08.950429: step 110 (global_step 8318), loss = 0.85 (354.3 examples/sec; 0.361 sec/batch)
2016-08-25 20:04:12.356555: step 120 (global_step 8338), loss = 0.77 (381.3 examples/sec; 0.336 sec/batch)
2016-08-25 20:04:15.832075: step 130 (global_step 8358), loss = 0.93 (369.8 examples/sec; 0.346 sec/batch)
2016-08-25 20:04:19.269496: step 140 (global_step 8377), loss = 0.92 (345.1 examples/sec; 0.371 sec/batch)
2016-08-25 20:04:22.709284: step 150 (global_step 8398), loss = 1.00 (383.3 examples/sec; 0.334 sec/batch)
2016-08-25 20:04:26.071762: step 160 (global_step 8418), loss = 0.75 (464.1 examples/sec; 0.276 sec/batch)
2016-08-25 20:04:29.580850: step 170 (global_step 8438), loss = 0.99 (359.5 examples/sec; 0.356 sec/batch)
2016-08-25 20:04:33.029791: step 180 (global_step 8457), loss = 1.04 (357.4 examples/sec; 0.358 sec/batch)
2016-08-25 20:04:36.491314: step 190 (global_step 8478), loss = 0.93 (358.7 examples/sec; 0.357 sec/batch)
2016-08-25 20:04:39.939553: step 200 (global_step 8498), loss = 1.08 (358.7 examples/sec; 0.357 sec/batch)
2016-08-25 20:04:43.318268: step 210 (global_step 8518), loss = 1.09 (363.6 examples/sec; 0.352 sec/batch)
2016-08-25 20:04:46.716990: step 220 (global_step 8538), loss = 0.98 (411.3 examples/sec; 0.311 sec/batch)
2016-08-25 20:04:50.069852: step 230 (global_step 8557), loss = 0.95 (433.2 examples/sec; 0.295 sec/batch)
2016-08-25 20:04:53.607222: step 240 (global_step 8577), loss = 1.02 (364.5 examples/sec; 0.351 sec/batch)
2016-08-25 20:04:57.162343: step 250 (global_step 8597), loss = 0.96 (357.5 examples/sec; 0.358 sec/batch)
2016-08-25 20:05:00.765804: step 260 (global_step 8617), loss = 1.07 (329.9 examples/sec; 0.388 sec/batch)
2016-08-25 20:05:04.435059: step 270 (global_step 8637), loss = 0.85 (332.6 examples/sec; 0.385 sec/batch)
2016-08-25 20:05:08.196024: step 280 (global_step 8656), loss = 0.89 (306.1 examples/sec; 0.418 sec/batch)
2016-08-25 20:05:12.412322: step 290 (global_step 8676), loss = 1.10 (268.2 examples/sec; 0.477 sec/batch)
2016-08-25 20:05:21.793992: step 300 (global_step 8696), loss = 0.72 (119.5 examples/sec; 1.071 sec/batch)
2016-08-25 20:05:32.548282: step 310 (global_step 8716), loss = 0.80 (119.6 examples/sec; 1.070 sec/batch)
2016-08-25 20:05:43.400207: step 320 (global_step 8736), loss = 1.03 (116.0 examples/sec; 1.104 sec/batch)
2016-08-25 20:05:54.547412: step 330 (global_step 8755), loss = 0.84 (114.6 examples/sec; 1.117 sec/batch)
2016-08-25 20:06:05.457404: step 340 (global_step 8775), loss = 1.09 (119.4 examples/sec; 1.072 sec/batch)
2016-08-25 20:06:16.434271: step 350 (global_step 8795), loss = 0.83 (115.2 examples/sec; 1.111 sec/batch)
2016-08-25 20:06:27.296998: step 360 (global_step 8815), loss = 0.90 (116.7 examples/sec; 1.097 sec/batch)
2016-08-25 20:06:38.130229: step 370 (global_step 8835), loss = 0.99 (119.2 examples/sec; 1.074 sec/batch)
2016-08-25 20:06:48.918992: step 380 (global_step 8855), loss = 1.09 (115.5 examples/sec; 1.108 sec/batch)
2016-08-25 20:07:00.132937: step 390 (global_step 8874), loss = 0.87 (119.0 examples/sec; 1.076 sec/batch)
```

**Comment by prb12** [comment] 2016-08-26 16:09
@perhapszzy  I presume you're following the tutorial code from [here](https://www.tensorflow.org/versions/r0.10/how_tos/distributed/index.html)?

It looks like you have mistyped several of the command lines, especially the `worker_hosts` and `ps_hosts` args:
```--worker_hosts='machine2:2222,machine2:2222'```

- It's unclear what machine the PS is running on (is there a `machine0` or `machine3`?)
- You start 'worker' processes on `machine1` and `machine2`
- You tell the workers that the PS is on `machine1` so they connect to the first worker instead!
- You tell each worker about the process on `machine2` twice, but don't mention `machine1`

I'm not 100% sure what would happen in this case, i.e. using the same worker twice (@mrry Any ideas?)
...but it's unlikely you are going to scale well, since 
a) The parameter service is unused
b) You are either using just one worker, or trying to run two training steps simultaneously on the same worker.
  
Please can you double check these command lines and let me know if it fixes the problem.

**Comment by perhapszzy** [comment] 2016-08-26 16:15
Ops, I mistyped the machines.
Shouldn't have problem setting the cluster up. And I tried no matter how many workers are used, the speed slowed down after ～10K iteration.

I tried 2 workers and 1 worker. They slowed down at ~10k iteration (for 2 workers, each worker finished ~5k iteration, for 1 worker, it slowed down after 10k iteration).

**Comment by mrry** [comment] 2016-08-26 16:20
Can you try with the nightly build? The release candidate 0.10.0rc0 has a memory leak in the distributed code that could be causing the slowdown.

**Comment by perhapszzy** [comment] 2016-08-26 16:21
Thanks for the advice. I'll try it today.

**Comment by perhapszzy** [comment] 2016-08-26 21:00
I tried the following methods, none of them helped:

1. tried to run the code using docker image tensorflow/tensorflow:nightly-gpu, the behavior is almost the same. Slowed down after ~10k iteration

2. tried to use 0.9.0, with pip package at 
```
 https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
```
This slows down even faster. More over, the GPU usage is only ~30% at beginning and ~10% after slowed down. However, the speed is ~0.160-0.250 sec/batch; while for the 0.10.0rc version, GPU usage is ~90% but the speed is only 0.330-0.360 sec/batch. I'll report this problem in another issue. Anyhow, the slowing down problem still exists.

I'll try to install tf from lastest source code and see if that helps or not. Will report later.

using nightly build didn't help.

**Comment by vrv** [comment] 2016-08-26 21:18
What is your memory usage like?  I have a totally random guess that this is caused by memory fragmentation and swapping.

Try:
- Enabling TCMalloc in your binary
- Turning off swap so it hard fails when you run out of memory

**Comment by perhapszzy** [comment] 2016-08-26 21:47
@mrry If I install from the master branch, the code hang at prepare_or_wait_for_session.

**Comment by perhapszzy** [comment] 2016-08-26 22:01
@vrv will try this and report later.

**Comment by perhapszzy** [comment] 2016-08-26 22:33
@vrv There's the memory status:

KiB Mem:  15400928 total, 11319472 used,  4081456 free,   456428 buffers
KiB Swap:        0 total,        0 used,        0 free.  7998028 cached Mem

**Comment by perhapszzy** [comment] 2016-08-26 23:33
if I turn off swap using ```sudo swapoff -a ``` it's still running

**Comment by vrv** [comment] 2016-08-26 23:38
Hm, did you try tcmalloc?

**Comment by perhapszzy** [comment] 2016-08-26 23:43
Still trying to learn how to use it.

**Comment by perhapszzy** [comment] 2016-08-27 00:11
Still have trouble installing the gperftools ... But I found if I don't run cifar10_eval with the training, the slow down became less severe. It only slows down from time to time
```
2016-08-27 00:06:55.565748: step 16220 (global_step 16220), loss = 0.92 (409.7 examples/sec; 0.312 sec/batch)
2016-08-27 00:06:59.056398: step 16230 (global_step 16230), loss = 0.86 (336.3 examples/sec; 0.381 sec/batch)
2016-08-27 00:07:03.097942: step 16240 (global_step 16240), loss = 0.82 (366.3 examples/sec; 0.349 sec/batch)
2016-08-27 00:07:08.687517: step 16250 (global_step 16250), loss = 0.97 (52.4 examples/sec; 2.443 sec/batch)
2016-08-27 00:07:12.856141: step 16260 (global_step 16260), loss = 1.05 (354.0 examples/sec; 0.362 sec/batch)
2016-08-27 00:07:17.285705: step 16270 (global_step 16270), loss = 0.79 (101.0 examples/sec; 1.268 sec/batch)
2016-08-27 00:07:22.531608: step 16280 (global_step 16280), loss = 0.83 (156.5 examples/sec; 0.818 sec/batch)
2016-08-27 00:07:26.008164: step 16290 (global_step 16290), loss = 0.79 (380.7 examples/sec; 0.336 sec/batch)
2016-08-27 00:07:31.529857: step 16300 (global_step 16300), loss = 0.92 (379.1 examples/sec; 0.338 sec/batch)
2016-08-27 00:07:35.004310: step 16310 (global_step 16310), loss = 1.10 (358.1 examples/sec; 0.357 sec/batch)
2016-08-27 00:07:39.766474: step 16320 (global_step 16320), loss = 0.85 (368.9 examples/sec; 0.347 sec/batch)
2016-08-27 00:07:44.046154: step 16330 (global_step 16330), loss = 0.90 (413.7 examples/sec; 0.309 sec/batch)
2016-08-27 00:07:49.655521: step 16340 (global_step 16340), loss = 0.71 (170.9 examples/sec; 0.749 sec/batch)
2016-08-27 00:07:54.041737: step 16350 (global_step 16350), loss = 0.85 (171.1 examples/sec; 0.748 sec/batch)
2016-08-27 00:07:57.530356: step 16360 (global_step 16360), loss = 0.88 (382.9 examples/sec; 0.334 sec/batch)
```

**Comment by perhapszzy** [comment] 2016-08-27 00:43
After start cifar10_eval, the speed slowed down dramatically even is cifar10_eval is not active for most of time.

```
2016-08-27 00:41:21.811675: step 20550 (global_step 20550), loss = 0.71 (236.8 examples/sec; 0.540 sec/batch)
2016-08-27 00:41:27.253400: step 20560 (global_step 20560), loss = 0.97 (223.2 examples/sec; 0.573 sec/batch)
2016-08-27 00:41:32.632130: step 20570 (global_step 20570), loss = 0.82 (237.2 examples/sec; 0.540 sec/batch)
2016-08-27 00:41:38.078019: step 20580 (global_step 20580), loss = 0.92 (222.5 examples/sec; 0.575 sec/batch)
2016-08-27 00:41:43.456795: step 20590 (global_step 20590), loss = 0.67 (235.5 examples/sec; 0.543 sec/batch)
2016-08-27 00:41:48.906125: step 20600 (global_step 20600), loss = 0.76 (222.7 examples/sec; 0.575 sec/batch)
2016-08-27 00:41:54.273064: step 20610 (global_step 20610), loss = 0.82 (238.0 examples/sec; 0.538 sec/batch)
2016-08-27 00:41:59.687229: step 20620 (global_step 20620), loss = 0.70 (236.5 examples/sec; 0.541 sec/batch)
2016-08-27 00:42:05.096757: step 20630 (global_step 20630), loss = 0.86 (237.3 examples/sec; 0.539 sec/batch)
2016-08-27 00:42:11.584223: step 20640 (global_step 20640), loss = 0.95 (253.4 examples/sec; 0.505 sec/batch)
2016-08-27 00:42:17.028177: step 20650 (global_step 20650), loss = 0.73 (222.9 examples/sec; 0.574 sec/batch)
```

**Comment by vrv** [comment] 2016-08-27 00:46
Are the two processes sharing the same GPU?

**Comment by perhapszzy** [comment] 2016-08-27 01:01
The machine only has 1 GPU, but for the cifar10_eval, I just run it using CPU by specifying ``` tf.device("/cpu:0")```

**Comment by vrv** [comment] 2016-08-27 03:17
So maybe it's only slowing down when the two are doing computation at the same time?

**Comment by perhapszzy** [comment] 2016-08-27 03:43
No, even the eval is sleeping, the train process is slowed down.

**Comment by vrv** [comment] 2016-08-27 03:46
Weird, I'm not really sure then -- you'll probably have to do some performance debugging to figure out what's going on.  The fact that it seems to run okay with just one process suggests inter-process interference.

**Comment by perhapszzy** [comment] 2016-08-27 14:19
I tried to start to workers on different machine, only 1 machine run the eval job, but the speed of another machine also slowed down. I suspected the problem might be caused by ps server, but the cpu & mem usage for the ps server were very low, so it's unlikely that the problem is caused by ps server

**Comment by chhwang** [comment] 2016-09-02 07:47
I see the same performance problem on my benchmark. I use one ps server and one worker with synchronized parameter update (SyncReplicasOptimizer). I expect no synchronization overhead because there is only one worker, but the worker throughput(examples/sec) is 0.57x in average than the case not using sync optimizer. Also the throughput fluctuates very much, just like what @perhapszzy posted.

**Comment by tatatodd** [comment] 2016-10-07 00:42
@perhapszzy @chhwang are you still seeing the same problems?  One thing to try is TensorFlow version 0.11, just to make sure we're not dealing with an issue that's been fixed already.

https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

**Comment by yaroslavvb** [comment] 2016-10-07 00:55
@chhwang I've been doing similar debugging recently and on a [simple benchmark](https://gist.github.com/yaroslavvb/1124bb02a9fd4abce3d86caf2f950cb2) I observing that transferring data between TF workers on same machine is about 500-1GB/second, while making data available to Python client in another process on same machine is <100MB/second

**Comment by chhwang** [comment] 2016-10-07 03:41
@yaroslavvb I'm not exactly sure how is your benchmark related to my problem. I think my problem is that the SyncReplicasOptimizer itself gives a significant overhead, and it is not the communication overhead. Anyway, it was a few months ago, so let me test it again with the recent version of TensorFlow as @tatatodd suggested.

**Comment by asimshankar** [comment] 2016-10-17 23:19
@chhwang : Were you able to get more recent results?

**Comment by chhwang** [comment] 2016-10-18 06:55
@asimshankar @tatatodd  Sorry for late response. Actually I couldn't test exactly the same benchmark as before because my batchnorm layers (which worked well with TF version 0.9.0) returned "Incompatible shapes" error with TF version 0.10.0, and I don't have enough time to work on this...

Thus my new benchmark removed batchnorm layers and also used newer TF/CUDA version (0.9.0 -> 0.10.0 / 7.5 -> 8.0) and GPU (GTX Titan X -> GTX 1080). With this setting, I can't see those problems I found before. Using SyncReplicasOptimizer doesn't affect the training throughput and the worker throughput (trained samples/sec) is very consistent now.

**Comment by asimshankar** [comment] 2016-10-18 07:36
Thanks for the update. Since quite a bit of time has passed and we can't reproduce the original problem anymore, I'm going to go ahead and close this issue. If you run into this or something like it again, please do file a new one.

Thanks!

**Closed by asimshankar** 2016-10-18 07:36 UTC
