### ISSUE TITLE
TypeError: unhashable type: 'ListWrapper' after adding losses to tf.keras model

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#34962] opened 2019-12-09 14:15 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14, 1.15, 2.0, 2.1rc0
- Keras version: 2.2.4-tf
- Python version: 3.6
- CUDA/cuDNN version: 10.0 and 10.1 / 7.6.5
- GPU model and memory: RTX 2060 6GB

**Describe the current behavior**
In project based on Mask_RCNN I got `TypeError: unhashable type: 'ListWrapper'` during training in add_loss(loss) method:
```

File "C:\Project\project.py", line 41, in build_Model
	maskRcnn = MaskRCNN(mode, config, model_dir)
File "C:\Project\project.py", line 58, in __init__
	maskRcnn.compile()
File "C:\Project\MaskRCNN\model.py", line 2175, in compile
	self.keras_model.add_loss(loss)
File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1132, in add_loss
	self._graph_network_add_loss(symbolic_loss)
File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1433, in _graph_network_add_loss
	self._insert_layers(new_layers, new_nodes)
File "C:\python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1392, in _insert_layers
	layer_set = set(self._layers)
File "C:\python36\lib\site-packages\tensorflow_core\python\training\tracking\data_structures.py", line 547, in __hash__
	raise TypeError("unhashable type: 'ListWrapper'")
TypeError: unhashable type: 'ListWrapper'
```

It's what happens when I use  tf.keras instead of keras.

**Comment by kiflowb777** [comment] 2019-12-09 14:16
Related topics:
https://github.com/matterport/Mask_RCNN/issues/1889
https://github.com/tensorflow/tensorflow/issues/33471
https://github.com/tensorflow/tensorflow/issues/32127

**Comment by oanush** [comment] 2019-12-10 05:17
@kiflowb777 ,
Can you share a standalone code to reproduce the error reported here?Thanks!

**Comment by dankor** [comment] 2019-12-12 11:16
It's a bug from Mask_RCNN:
https://github.com/matterport/Mask_RCNN/issues/1889

The source of the error is:
https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L2175

**Comment by tensorflowbutler** [comment] 2019-12-27 12:29
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by dankor** [comment] 2019-12-31 15:11
It's not really a TF bug. Fixed against the following code of Mask_RCNN:
 https://github.com/matterport/Mask_RCNN/tree/295c802f0bebbc4a34ec4855f4960a52a701271d/mrcnn

**Comment by oanush** [comment] 2020-01-03 03:27
@kiflowb777 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2020-01-08 09:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2020-01-08 09:58 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support

**Comment by dhruvgoel99** [comment] 2022-03-24 17:50
Hi, I got the same error, i tried some solution to resolve them:
just comment out line 2163 & 2164
i.e.,
self.keras_model._losses = []
self.keras_model._per_input_losses = {}

**Comment by SindhuKodali** [comment] 2022-06-16 19:51
> https://github.com/matterport/Mask_RCNN/tree/295c802f0bebbc4a34ec4855f4960a52a701271d/mrcnn

Hey, could you please tell at which line in which file you changed the code, to fix the ListWrapper error?

**Comment by aalbaiaa** [comment] 2022-08-27 19:13
> > https://github.com/matterport/Mask_RCNN/tree/295c802f0bebbc4a34ec4855f4960a52a701271d/mrcnn
> 
> Hey, could you please tell at which line in which file you changed the code, to fix the ListWrapper error?

at path :
/yourpathToPytho/anaconda3/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py

change file model.py 

just comment out line 2163 & 2164
i.e.,
self.keras_model._losses = []
self.keras_model._per_input_losses = {}

**Comment by yaoliu0803** [comment] 2022-09-01 10:49
> It's a bug from Mask_RCNN: [matterport/Mask_RCNN#1889](https://github.com/matterport/Mask_RCNN/issues/1889)
> 
> The source of the error is: https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L2175

I have this same problem. you solve it?

**Comment by anya-chan** [comment] 2022-10-28 11:31
I have commented two lines 2163 & 2164, but problem not solved.

**Comment by arifulai** [comment] 2023-09-26 03:37
how to solve?
TypeError: unhashable type: 'ListWrapper'

**Comment by arifulai** [comment] 2023-09-26 03:39
my problem is 
TypeError                                 Traceback (most recent call last)
Cell In[118], line 1
----> 1 model.train(_train_dataset, _val_dataset, 
      2             learning_rate=TrainConfig.LEARNING_RATE / 10,
      3             epochs=50, 
      4             layers="all")

File /workspace/Mask_RCNN/mrcnn/model.py:2371, in MaskRCNN.train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)
   2369 log("Checkpoint Path: {}".format(self.checkpoint_path))
   2370 self.set_trainable(layers)
-> 2371 self.compile(learning_rate, self.config.LEARNING_MOMENTUM)
   2373 # Work-around for Windows: Keras fails on Windows when using
   2374 # multiprocessing workers. See discussion here:
   2375 # https://github.com/matterport/Mask_RCNN/issues/13#issuecomment-353124009
   2376 if os.name is 'nt':

File /workspace/Mask_RCNN/mrcnn/model.py:2192, in MaskRCNN.compile(self, learning_rate, momentum)
   2188         continue
   2189     loss = (
   2190         tf.reduce_mean(layer.output, keepdims=True)
   2191         * self.config.LOSS_WEIGHTS.get(name, 1.))
-> 2192     self.keras_model.add_loss(loss)
   2194 # Add L2 Regularization
   2195 # Skip gamma and beta weights of batch normalization layers.
   2196 reg_losses = [
   2197     keras.regularizers.l2(self.config.WEIGHT_DECAY)(w) / tf.cast(tf.size(w), tf.float32)
   2198     for w in self.keras_model.trainable_weights
   2199     if 'gamma' not in w.name and 'beta' not in w.name]

File /usr/local/lib/python3.8/dist-packages/keras/engine/base_layer_v1.py:1156, in Layer.add_loss(self, losses, inputs)
   1154 for symbolic_loss in symbolic_losses:
   1155     if getattr(self, "_is_graph_network", False):
-> 1156         self._graph_network_add_loss(symbolic_loss)
   1157     else:
   1158         # Possible a loss was added in a Layer's `build`.
   1159         self._losses.append(symbolic_loss)

File /usr/local/lib/python3.8/dist-packages/keras/engine/functional.py:1013, in Functional._graph_network_add_loss(self, symbolic_loss)
   1011 new_nodes.extend(add_loss_layer.inbound_nodes)
   1012 new_layers.append(add_loss_layer)
-> 1013 self._insert_layers(new_layers, new_nodes)

File /usr/local/lib/python3.8/dist-packages/keras/engine/functional.py:950, in Functional._insert_layers(self, layers, relevant_nodes)
    947         self._nodes_by_depth[depth].append(node)
    949 # Insert layers and update other layer attrs.
--> 950 layer_set = set(self._self_tracked_trackables)
    951 deferred_layers = []
    952 for layer in layers:

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/trackable/data_structures.py:674, in ListWrapper.__hash__(self)
    671 def __hash__(self):
    672   # List wrappers need to compare like regular lists, and so like regular
    673   # lists they don't belong in hash tables.
--> 674   raise TypeError("unhashable type: 'ListWrapper'")

TypeError: unhashable type: 'ListWrapper'
