### ISSUE TITLE
tensorflowjs_converter install fails due to tf-nightly-2.0-preview missing from Python 3.7

### ISSUE THREAD

**Issue by MonarkA** [tensorflow/tensorflow#28712] opened 2019-05-14 16:37 UTC
**Describe the problem**

Command used:
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names=final_result  output/saved_model.pb web_model

Getting below error:
tensorflowjs_converter: command not found

**Comment by ymodak** [comment] 2019-05-14 17:21
You need to pip install tensorflowjs before running the converter.
```pip install tensorflowjs```

**Comment by MonarkA** [comment] 2019-05-14 18:38
Hi @ymodak ,

tensorflowjs is already installed on my system. Still, I am getting above error.

**Comment by ymodak** [comment] 2019-05-14 19:20
Please provide following information:
*System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by MonarkA** [comment] 2019-05-15 10:14
could you please check below explanation?

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.3
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not on mobile device
TensorFlow installed from (source or binary): installed pip from terminal using command "pip install tensorflow"
TensorFlow version (use command below):1.13.1
Python version:2.7.10
Bazel version (if compiling from source):No
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: could you please tell how the check this?
GPU model and memory:are you talking about tensorflow GPU or system GPU here?

I was training AI model and I got stuck at below command:
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names=final_result  output/saved_model.pb web_model
Please check the above command on below page:
https://medium.com/testdotai/training-data-for-app-classifier-f217dc005523

Thanks!!

**Comment by tafsiri** [comment] 2019-05-21 12:09
@MonarkA this looks like a path issue where your system can't locate the `tensorflowjs_converter` script. Did you get any errors when doing `pip install tensorflowjs`? (note its a separate pip package from `tensorflow`). Could you try re-installing it?

cc @pyu10055 @caisq

**Comment by cfkxzsat** [comment] 2019-05-22 07:19
Same here. Use
```bash
sudo pip3 install tensorflowjs
```
got

**ERROR: Could not find a version that satisfies the requirement tf-nightly-2.0-preview>=2.0.0.dev20190502 (from tensorflowjs) (from versions: none)
ERROR: No matching distribution found for tf-nightly-2.0-preview>=2.0.0.dev20190502 (from tensorflowjs)**

my python version: 3.7.3
pip3 --version
pip 19.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)

Anybody can help me out?

**Comment by caisq** [comment] 2019-05-22 12:52
@cfkxzsat It is weird that your pip can't find a suitable version of tensorflow.
Can you try the standalone install command `pip install tf-nightly-2.0-preview` and see what version you get?

**Comment by cfkxzsat** [comment] 2019-05-23 01:51
Same,bro...
```bash
pip3 install tf-nightly-2.0-preview
Collecting tf-nightly-2.0-preview
  ERROR: Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: none)
ERROR: No matching distribution found for tf-nightly-2.0-preview
```

**Comment by caisq** [comment] 2019-05-23 02:11
@cfkxzsat Is it possible that you are configured to use a non-public (custom) PyPI? 

tf-nightly-2.0-preview is clearly available: https://pypi.org/project/tf-nightly-2.0-preview/

**Comment by MonarkA** [comment] 2019-05-23 06:15
@tafsiri ,

I tried reinstalling tensorflow but I am getting same issue.

**Comment by csaroff** [comment] 2019-05-24 03:48
For anyone still running into this, you need to be using python 3.6(and it's associated pip version).  I was still running into issues after `conda install python=3.6`.  It turns out that I had an alias in my bashrc between pip and pip3.  If things still aren't working after changing python versions, try `unalias pip`.

**Comment by caisq** [comment] 2019-05-24 13:44
@csaroff Interesting. So this is because tf-nightly-2.0-preview is unavailable for Python 3.7. Changed the title of the issue to reflect that.

cc @gunan @yifeif @av8ramit

**Comment by rthadur** [comment] 2021-09-23 18:11
This is working with latest version , closing this issue. Thank you

**Closed by rthadur** 2021-09-23 18:12 UTC
Labels: type:others
