### ISSUE TITLE
error __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by mtrth** [tensorflow/tensorflow#49] opened 2015-11-09 23:51 UTC
I have Ubuntu 14.04 system I installed tensor flow using
pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

then when I try to import tensorflow in my python window, I get the error:
 __init__() got an unexpected keyword argument 'syntax'

Is it a protobuf version problem ?
I have $ protoc --version
libprotoc 2.5.0

**Comment by Yangqing** [comment] 2015-11-09 23:53
I think so - tensorflow requires protobuf 3. Issue #11 may be helpful.

**Comment by vrv** [comment] 2015-11-10 00:16
Closing as duplicate of 11 to keep discussion to one issue.  Thanks!

**Closed by vrv** 2015-11-10 00:16 UTC
