### ISSUE TITLE
DataHandler intermittent InvalidArgumentError for large input dimension

### ISSUE THREAD

**Issue by phil0stine** [tensorflow/tensorflow#42696] opened 2020-08-27 03:54 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc2-77-gaad398b5e9 2.2.0-rc3
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: V100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Based on tracing an error for a call to the `fit` method of a model, I determined that an `InvalidArgumentError` was contingent on both the number of inputs N in a dataset batch (in this case the data is of the form BxNxC) as well as whether `class_weights` were being set.

**Describe the expected behavior**
Setting `class_weights` as shown in the online [docs](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data) would not break calls to `fit` depending on the number of input data. I determined that the DataHandler was the object that threw the exception during the `model.fit` call, so the min example below is based on a DataHandler object.

This is related to this [issue](https://github.com/tensorflow/tensorflow/issues/23698), but I don't see how the issue is resolved for arbitrary models. In particular, it has nothing to do with NLP, as is mentioned in a [comment](https://github.com/tensorflow/tensorflow/issues/23698#issuecomment-673667914)

**Standalone code to reproduce the issue**
Colab [link](https://colab.research.google.com/drive/1jAPPKv5yKMNvwzJV4dvJZFBFzfrn6h8W#scrollTo=FinvXcZG3K67)

Same code posted here:
``` python
import tensorflow as tf
import numpy as np
from tensorflow.python.keras.engine import data_adapter
def test_weights(model, n_samples, use_weights=True):
    def test_data():
        def test_data_gen():
            n_classes = 5
            x = np.random.randn(n_samples,3)
            y = np.random.randint(0,n_classes,n_samples)
            yield (x.astype(np.float32),
                   y.astype(np.int32))
        gen_func = test_data_gen
        gen_types = (tf.float32, tf.int32)
        gen_shapes = ([None, 3], [None])
        return gen_func, gen_types, gen_shapes
    gen_fn, gen_tp, gen_sh = test_data()
    ds_tst = tf.data.Dataset.from_generator(gen_fn, gen_tp, gen_sh)
    ds_tst = ds_tst.batch(2)
    ds_tst = ds_tst.prefetch(2)
    cw = {0 : 0.0, 1 : 1.5, 2 : 0.5,
          3 : 0.5, 4 : 0.5}
    data_handler = data_adapter.DataHandler(
        x=ds_tst,
        y=None,
        sample_weight=None,
        batch_size=None,
        steps_per_epoch=10,
        initial_epoch=0,
        epochs=1,
        shuffle=True,
        class_weight=(cw if use_weights else None),
        max_queue_size=10,
        workers=1,
        use_multiprocessing=False,
        model=model)
    print ('NEXT',next(iter(data_handler._dataset)))

model = tf.keras.Model()
test_weights(model, 5) # Always succeeds
test_weights(model, 50000) # Sometimes fails
test_weights(model, 50000, use_weights=False) # Always succeeds
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
``` bash
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2101       ctx.executor = executor_new
-> 2102       yield
   2103     finally:

11 frames
InvalidArgumentError: indices[0] = 5 is not in [0, 5)
	 [[{{node GatherV2}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

InvalidArgumentError: indices[0] = 5 is not in [0, 5)
	 [[{{node GatherV2}}]]
```

**Comment by Saduf2019** [comment] 2020-08-27 05:26
@phil0stine 
I ran the code shared and able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d4fe3d6cc9c4bc8f78a3abcbc68e584b/untitled396.ipynb)
#23698  (please modify the input size and let us know) [link](https://stackoverflow.com/questions/51223936/tensorflow-invalidargumenterror-indices-while-training-with-keras) [link1](https://stackoverflow.com/questions/46940073/tensorflow-object-detection-aborts-with-invalidargumenterror-indices0-2-is/49745588)  [link2](https://blog.csdn.net/u011585024/article/details/88938194)

**Comment by phil0stine** [comment] 2020-08-27 12:49
@Saduf2019 
I have looked at the references you provided, but they all involve NLP and [Embedding](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding) layers that have the incorrect input dimension as the `input_dim` argument.

My network has no such layers, and is similar to the architectured described in a related issue https://github.com/tensorflow/tensorflow/issues/23698#issuecomment-673667914.

This minimum example in fact has no layers, so problem seems to be independent of model architecture.

**Comment by qlzh727** [comment] 2020-09-07 21:32
Assigning to Tom. It seems that we do special handling for class weights based on the shape of y, and do arg_max for it. So the error might be caused by the dataset element shape.

**Comment by sachinprasadhs** [comment] 2021-05-26 15:04
The issue is fixed in Tf Nightly version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/26ecbbef63780e37e88654175a021c69/42696.ipynb). Thanks!

**Comment by sachinprasadhs** [comment] 2021-05-26 15:05
Closing the issue since the issue is fixed in Tf Nightly, feel free to reopen. Thanks!

**Closed by sachinprasadhs** 2021-05-26 15:05 UTC
Labels: TF 2.2, comp:keras, type:bug
