### ISSUE TITLE
//tensorflow/python:function_test is passing without GPU support but failing with GPU support

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#10281] opened 2017-05-30 06:34 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
     Installed from source (v1.0.1)
- **TensorFlow version (use command below)**:
    ('v1.0.1-0-ge895d5c-dirty', '1.0.1')
- **Bazel version (if compiling from source)**:
    0.4.4-2017-05-26 (@80a07b5)
- **CUDA/cuDNN version**:
     CUDA = 8.0 and cuDNN = 5.1
- **GPU model and memory**:  
     GPU 0: Tesla P100-SXM2-16GB 
     GPU 1: Tesla P100-SXM2-16GB
- **Exact command to reproduce**:
      bazel test --config=opt --config=cuda  //tensorflow/python:function_test

### Describe the problem
If we run this test without CUDA then its passing, however with CUDA getting failure i.e.  "array mismatch 0.64697265625%" error , see below for details : 

### Source code / logs
```
$ bazel test --config=opt --config=cuda //tensorflow/python:function_test

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: Tesla P100-SXM2-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.4805
pciBusID 0002:01:00.0
Total memory: 15.89GiB
Free memory: 15.61GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x10002b8ea90
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 1 with properties:
name: Tesla P100-SXM2-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.4805
pciBusID 0006:01:00.0
Total memory: 15.89GiB
Free memory: 15.61GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 0 and 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 1 and 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y N
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   N Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 2 visible devices
I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 160 visible devices
I tensorflow/compiler/xla/service/service.cc:180] XLA service executing computations on platform Host. Devices:
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (0): <undefined>, <undefined>
I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 2 visible devices
I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 160 visible devices
I tensorflow/compiler/xla/service/service.cc:180] XLA service executing computations on platform CUDA. Devices:
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (0): Tesla P100-SXM2-16GB, Compute Capability 6.0
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (1): Tesla P100-SXM2-16GB, Compute Capability 6.0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcupti.so.8.0 locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
..I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
..I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
.
.
.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
F.I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0002:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0)
..
======================================================================
FAIL: testUnrollLSTMGrad (__main__.UnrollLSTMTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amit/.cache/bazel/_bazel_amit/c2069970ba4ea955300413b19a88640d/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/function_test.runfiles/org_tensorflow/tensorflow/python/framework/function_test.py", line 832, in testUnrollLSTMGrad
    self.assertAllClose(d0, d1, rtol=1e-4)
  File "/home/amit/.cache/bazel/_bazel_amit/c2069970ba4ea955300413b19a88640d/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/function_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 485, in assertAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=1e-06

(mismatch 0.64697265625%)
 x: array([[[ 4.276238,  0.15792 ,  0.614052, ...,  2.567241,  0.883315,
          0.162565],
        [ 3.256324,  0.069458,  1.132122, ...,  2.211422,  0.491486,...
 y: array([[[ 4.276276,  0.15792 ,  0.614058, ...,  2.567239,  0.883316,
          0.162566],
        [ 3.256359,  0.069458,  1.132127, ...,  2.211414,  0.491488,...

----------------------------------------------------------------------
Ran 41 tests in 14.361s

FAILED (failures=1)
255.971 13.0395
255.971 13.0395
not close where =  (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0]), array([ 0,  1,  4,  6,  6,  8,  8,  9, 11, 12, 12, 13, 13, 15, 18, 19, 26,
       26, 26, 28, 28, 29, 29, 30, 30, 31, 31, 32, 33, 34, 34, 34, 39, 41,
       41, 42, 42, 43, 45, 47, 48, 48, 50, 50, 50, 52, 55, 55, 55, 57, 59,
       61, 62]), array([110,  49,  28, 110, 117,  24,  45,  24, 117,  45,  85,  28, 110,
       104,  20,  13,  21,  28, 109,  24, 104, 110, 117,  45, 117, 104,
       110, 106,  23,   0,  77,  87,  13,  28,  49,  53,  89, 110,  49,
        28,  49, 122,  21,  23,  87,  45,  45,  87, 112, 124,  28,   7,  36]))
not close lhs =  [ 0.00964716  0.0108541  -0.02481478  0.01410314 -0.01004539 -0.00598446
 -0.06178713 -0.00234316  0.00250508  0.13677871  0.01347511  0.03004426
 -0.02344483  0.03969495 -0.00342371  0.06425443  0.04404789  0.01697282
  0.00173055  0.00629981 -0.07690701  0.01800087  0.00182568  0.10605431
 -0.00270458  0.01780143  0.00939897 -0.01084067 -0.00755548  0.00419208
 -0.00418841 -0.00287345  0.05488337 -0.03028315  0.00747772 -0.00952677
  0.01471797 -0.00804311  0.01273583  0.00947097  0.00700331 -0.00019016
  0.03132032  0.14848644 -0.00288739 -0.01046085  0.0042536   0.04803397
  0.0140109  -0.03605841 -0.00635294  0.16805029 -0.01475533]
not close rhs =  [ 0.0096446   0.01085714 -0.02482039  0.01410037 -0.01004928 -0.00598631
 -0.06180775 -0.00234506  0.00250115  0.13676071  0.01347163  0.03003997
 -0.02344918  0.03968659 -0.00342231  0.06426588  0.04405451  0.0169698
  0.00172922  0.00629799 -0.07691711  0.01799804  0.00182213  0.1060307
 -0.0027072   0.01779342  0.00939631 -0.01084429 -0.00755821  0.00418651
 -0.00418626 -0.00287483  0.05489143 -0.03027856  0.0074747  -0.00952475
  0.01471417 -0.00804621  0.01273203  0.00946853  0.00700712 -0.00019156
  0.03132723  0.14846958 -0.00288068 -0.01046896  0.00425826  0.04802619
  0.01401426 -0.03605241 -0.00635018  0.16807139 -0.01475281]
not close dif =  [  2.56299973e-06   3.04728746e-06   5.60283661e-06   2.77161598e-06
   3.88920307e-06   1.84774399e-06   2.06232071e-05   1.89989805e-06
   3.93390656e-06   1.80006027e-05   3.47942114e-06   4.29153442e-06
  4.35113907e-06   8.35955143e-06   1.40070915e-06   1.14440918e-05
   6.61611557e-06   3.02493572e-06   1.32620335e-06   1.81794167e-06
   1.01029873e-05   2.83122063e-06   3.54647636e-06   2.36034393e-05
   2.62260437e-06   8.01682472e-06   2.65240669e-06   3.62098217e-06
   2.72691250e-06   5.57303429e-06   2.15321779e-06   1.37463212e-06
   8.05780292e-06   4.58955765e-06   3.01748514e-06   2.02655792e-06
   3.79979610e-06   3.09944153e-06   3.79979610e-06   2.44379044e-06
   3.81469727e-06   1.40070915e-06   6.91413879e-06   1.68532133e-05
   6.71669841e-06   8.10623169e-06   4.66406345e-06   7.78585672e-06
   3.36393714e-06   5.99771738e-06   2.75671482e-06   2.11000443e-05
   2.51457095e-06]
not close tol =  [  1.96445990e-06   2.08571419e-06   3.48203866e-06   2.41003727e-06
   2.00492832e-06   1.59863112e-06   7.18077490e-06   1.23450559e-06
   1.25011445e-06   1.46760713e-05   2.34716254e-06   4.00399631e-06
   3.34491824e-06   4.96865869e-06   1.34223126e-06   7.42658722e-06
   5.40545079e-06   2.69698012e-06   1.17292200e-06   1.62979904e-06
   8.69171163e-06   2.79980395e-06   1.18221283e-06   1.16030706e-05
   1.27071985e-06   2.77934168e-06   1.93963137e-06   2.08442907e-06
   1.75582113e-06   1.41865110e-06   1.41862574e-06   1.28748252e-06
   6.48914238e-06   4.02785645e-06   1.74746981e-06   1.95247480e-06
   2.47141656e-06   1.80462098e-06   2.27320288e-06   1.94685254e-06
   1.70071212e-06   1.01915577e-06   4.13272301e-06   1.58469575e-05
   1.28806778e-06   2.04689604e-06   1.42582599e-06   5.80261849e-06
   2.40142572e-06   4.60524143e-06   1.63501818e-06   1.78071386e-05
   2.47528124e-06]
dtype = float32, shape = (1, 64, 128)
```
Any comments/suggestions ?

**Comment by asimshankar** [comment] 2017-05-31 08:59
Thanks for the report. I haven't traced down how, but it seems this was fixed in a later release (I'm unable to reproduce the failure in TensorFlow 1.1 or the release candidate for the next version - 1.2.0-rc0).

Is it possible for you to upgrade to a later version (1.1.0 for example)?

**Comment by sandipmgiri** [comment] 2017-06-01 11:05
Hi @asimshankar, I have upgraded TF version from 1.0.1 to 1.1.0 , and now this test is passing 

Thanks for your suggestion!

**Closed** 2017-06-01 11:18 UTC
Labels: stat:awaiting response
