### ISSUE TITLE
Fake quantization is much slower when decorated with tf.function

### ISSUE THREAD

**Issue by ifed-ucsd** [tensorflow/tensorflow#35718] opened 2020-01-09 21:14 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-21967-gd80fda0 2.1.0-dev20200109
- Python version: 3.6.9
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA Version 10.1.243 / cuDNN 7.6.4.38-1
- GPU model and memory: TITAN V, 12GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Executing `tf.quantization.fake_quant_with_min_max_vars` within a `tf.function` decorator is much slower than executing without the decorator. On my system, the code below prints:

TF forward 0.27578210830688477 ms
TF forward w/ tf.function 0.4100463390350342 ms

**Describe the expected behavior**
I expect the speed to be the same.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`
import tensorflow as tf
import numpy as np
import time

assert tf.executing_eagerly()

gpus_p = tf.config.experimental.list_physical_devices('GPU')
if gpus_p:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus_p:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

@tf.function
def tf_forward_tf_function(x,xmin,xmax):
    return tf.quantization.fake_quant_with_min_max_vars(inputs=x,
                                                        min=xmin,
                                                        max=xmax,
                                                        num_bits=8)

def tf_forward(x,xmin,xmax):
    return tf.quantization.fake_quant_with_min_max_vars(inputs=x,
                                                        min=xmin,
                                                        max=xmax,
                                                        num_bits=8)

x = tf.random.uniform(shape=[10000,1000])
times = {'tf':[],'tf_function':[]}
xmax = tf.Variable(0.5)

tf_forward(x,-xmax,xmax)
tf_forward_tf_function(x,-xmax,xmax)

for n in range(1000):
    start = time.time()
    tf_forward(x,-xmax,xmax)
    stop = time.time()
    times['tf'].append(stop-start)

    start = time.time()
    tf_forward_tf_function(x,-xmax,xmax)
    stop = time.time()
    times['tf_function'].append(stop-start)
    
print('TF forward ' + str(1000 * np.mean(times['tf'])) + ' ms')
print('TF forward w/ tf.function ' + str(1000 * np.mean(times['tf_function'])) + ' ms')   

`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-01-10 14:38
@ifed-ucsd,
I have observed that this issue is similar to [#35720](https://github.com/tensorflow/tensorflow/issues/35720). Please confirm if I can close this issue as it is already being tracked there.

**Comment by ifed-ucsd** [comment] 2020-01-10 15:18
I would like to keep this open because this issue highlights that decorating a single call to a TF function with tf.function leads to slower execution, whereas #35720 is about decorating a sequence of TF function calls. Moreover, this issue is about the tf.quantization API specifically, whereas #35720 is not.

**Comment by amahendrakar** [comment] 2020-01-13 11:02
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/556336666ea4fed9d12d0e22da535879/35718.ipynb). Thanks!

**Comment by mdanatg** [comment] 2020-01-14 14:20
I think this highlights the same fundamental issue as #35720, that is, `tf.function` does not yield a speed gain for small computations.
Since `tf.fake_quant_with_min_max_vars` is a single op kernel, this is a particular case. Conceptually, it is similar e.g. to how in Python, `x + y` is faster when executed directly, compared to executing it in a function.

**Closed by mdanatg** 2020-01-14 14:20 UTC
Labels: TF 2.1, comp:autograph, stat:awaiting tensorflower, type:performance
