### ISSUE TITLE
TOCO fails to handle Dilated Convolution properly

### ISSUE THREAD

**Issue by gashmish** [tensorflow/tensorflow#22146] opened 2018-09-07 15:17 UTC
### System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N/A
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
TensorFlow installed from (source or binary):source
TensorFlow version (use command below):1.10.0
Python version: 2.7.12
Bazel version (if compiling from source):0.15.0
GCC/Compiler version (if compiling from source):5.4.0
CUDA/cuDNN version:N/A
GPU model and memory:N/A
Exact command to reproduce:N/A

### Problem description
I have frozen_model.pb which works well.

I build toco with command:
`bazel build -c opt //tensorflow/contrib/lite/toco:toco`
 
Then i'm trying to convert model to TfLite:
`toco --allow_custom_ops --input_file='frozen_model.pb'  --output_file='wavenet.tflite' --input_arrays='original_input' --input_shapes='1,48000,1' --output_arrays='activation_2/Softmax' --dump_graphviz=graph --dump_graphviz_video=true`

and geting error:

```
2018-09-07 17:45:53.870648: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 412 operators, 674 arrays (0 quantized)
2018-09-07 17:45:53.876846: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 412 operators, 674 arrays (0 quantized)
2018-09-07 17:45:53.877237: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:161] Identified sub-network emulating dilated convolution.
2018-09-07 17:45:53.877266: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:209] Replaced with Dilated Conv2D op outputting "dilated_conv_2_tanh/convolution/Conv2D".
2018-09-07 17:45:53.877487: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:161] Identified sub-network emulating dilated convolution.
2018-09-07 17:45:53.877512: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:209] Replaced with Dilated Conv2D op outputting "dilated_conv_2_sigm/convolution/Conv2D".
2018-09-07 17:45:53.877852: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:116] Check failed: dim_x == dim_y (48002 vs. 48000)Dimensions must match
```

This is Dilated Convolution block in original frozen_model.pb visualized in tensorboard, it has input and output shape [?, 48000, 40]:

[?, 48000, 40] ->Pad->[?, 48002, 40]->SpaceToBatchND -> ExpandDims -> Conv2D -> Squeeze -> BatchToSpaceND->[?, 48000, 40]

![img2](https://user-images.githubusercontent.com/673872/45226776-67d4c200-b2c8-11e8-9886-1aa498559a00.png)

TOCO tries to substitute with
[?, 48000, 40] ->Pad->[?, 48002, 40]->Reshape -> Conv1x1/S -> Squeze->[?, 48002, 40]
![img3](https://user-images.githubusercontent.com/673872/45227203-cf8b0d00-b2c8-11e8-9092-7a4a94a731c0.png)

so ouput of resulted block is [?, 48002, 40] instead of [?, 48000, 40], it causes error in subsequent operations.

I managed to avoid this issue by removing line 102:
`transformations->Add(new IdentifyDilatedConv);`
from tensorflow/contrib/lite/toco/toco_tooling.cc and rebuilding TOCO,
but unfortunately this causes new problems, because some operations like SpaceToBatchND and BatchToSpaceND don't support 3D tensors in current TfLite verison.

**Comment by jdduke** [comment] 2018-09-07 21:17
Thanks for the report, would it be possible to share the model (or truncated model) which yields this error? Thanks.

**Comment by gashmish** [comment] 2018-09-10 17:21
Here is simplified model created in Keras 2.2.2:

[keras-dilated-conv.tar.gz](https://github.com/tensorflow/tensorflow/files/2367670/keras-dilated-conv.tar.gz)

![1](https://user-images.githubusercontent.com/673872/45313167-bd160b00-b536-11e8-99a8-4b40255245cb.png)

images for converted graph are also in archive

**Comment by tensorflowbutler** [comment] 2018-09-25 12:40
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dev0x13** [comment] 2018-10-22 15:12
Hello! What's the status of this issue? It seems like I have faced this bug too.

**Comment by tensorflowbutler** [comment] 2018-11-06 18:55
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-21 18:56
Nagging Assignee @suharshs: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-06 18:57
Nagging Assignee @suharshs: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gashmish** [comment] 2019-03-13 20:19
This error always oppears when you try to convert Keras model with Conv1D when dilation_rate > 1 and padding  != 'same'

Still on TF 1.13

**Comment by ANSHUMAN87** [comment] 2019-04-29 08:05
@gashmish : Recently i uploaded 2 PRs to address SpaceToBatchND and BatchToSpaceND arbitrary dimension support, i have verified with the model you uploaded in this issue, it works fine. Would you please consider these 2 PRs into your workspace and check with your real time data once. Just need to know if it solves your blocking issue, Thanks!
2 PRs are #27867 & #28179

**Comment by gashmish** [comment] 2019-05-02 02:36
Hello @ANSHUMAN87 !
I tested your PRs for our model in TF Lite and it works well, great job!

Regarding current issue, if those PRs are applied, some option for disabling ResolveDilatedConv transflormation in TOCO could solve the problem

However, strainforward disabling ResolveDilatedConv may cause some other errors in subsequent graph nodes, like this:

`ERROR: tensorflow/lite/kernels/strided_slice.cc:152 op_context.input->type != op_context.output->type (2 != 1)
ERROR: Node number 216 (STRIDED_SLICE) failed to prepare.`

I managed to avoid this by removing Reshape layer in Keras model, but in general there can be other problems

**Comment by ANSHUMAN87** [comment] 2019-05-02 04:59
@gashmish : Thanks a lot for confirming! 
I am unsure why you need to disable ResolveDilatedConv().
As i can reproduce the issue:

> NumDimensions(op_context.input) != kInputDimensionNum (3 != 4)Node number 1 (SPACE_TO_BATCH_ND) failed to prepare.

without any change in code with the model you shared in zip file earlier.
Then i applied my 2 PRs, and the inference is successful.
Please let me know if i miss anything.
TIA!

**Comment by gashmish** [comment] 2019-05-02 13:20
@ANSHUMAN87, may be it was other model accidentally? By default TOCO tries to substitute dilated convolution subgraph with subgraph without SpaceToBatch and BatchToSpace

Converting model.pb to model.tflite from attached zip in TF nightly build with command
```
toco \
    --graph_def_file='model.pb' \
    --output_file="model.tflite" \
    --input_arrays='input' \
    --input_shapes='1,48000,40' \
    --output_arrays='dilated_conv_2/Tanh' \
    --dump_graphviz_video \
    --dump_graphviz_dir='graph'
```
[toco_AT_IMPORT.dot.pdf](https://github.com/tensorflow/tensorflow/files/3138076/toco_AT_IMPORT.dot.pdf)
[toco_AFTER_TRANSFORMATIONS.dot.pdf](https://github.com/tensorflow/tensorflow/files/3138078/toco_AFTER_TRANSFORMATIONS.dot.pdf)

In latest TF version you can use this script to create sample model:

```
import tensorflow as tf
from keras        import backend as K
from keras.layers import Input, Conv1D 
from keras.models import Model

K.set_learning_phase(False)

input  = Input(
    name =  'input',
    shape = (48000, 40))

output = Conv1D(
    name          ='dilated_conv_2',
    filters       = 40, 
    kernel_size   = 2,
    dilation_rate = 2,
    padding       = 'causal',
    activation    = 'tanh'
)(input)

model = Model(input, output)
model.summary()
model.save("sample.h5")

converter = tf.lite.TFLiteConverter.from_keras_model_file("sample.h5")
tflite_model = converter.convert()
open("sample.tflite", "wb").write(tflite_model)
```

Point of current issue is that subgraph substitution in this case works inproperly, so i needed to disable it in TOCO source

**Comment by ANSHUMAN87** [comment] 2019-05-03 06:18
@gashmish : I have used tensorflow 1.13 for your model conversion to tflite with the script you shared. It executed perfectly fine. Also i went through the *.dot files you shared, the conversion is perfectly fine. The output shape is supposed to be [?, 48002, 40] as per padding. So still i am not sure where you are facing the issue. Would you please try converting your model using 1.13 version or later, and post your results.

**Comment by gashmish** [comment] 2019-05-03 16:18
@ANSHUMAN87: Everything i all right, by "this issue" i mean current topic about TOCO converter.

1) In TF 1.13.1 if I create and convert simple model with above script I get model with Conv2d and without BatchToSpace and SpaceToBatch. Output size is  [?, 48002, 40] instead of  [?, 48000, 40], so my production model will not work. This is ResolveDilatedConv transformation Bug.

2) If I disable ResolveDilatedConv transformation in toco I get model with BatchToSpace and SpaceToBatch. Then I apply your patches to TF Lite and everything works perfect. 

[Script and resulting models](https://github.com/tensorflow/tensorflow/files/3142712/sample.tar.gz)

So my problem is solved, but I still need to disable ResolveDilatedConv in TOCO source by hand, which also caused STRIDED_SLICE problem, which i avoided by also slightly changing or production model.

Regarding your BatchToSpace and SpaceToBatch ops changes everything works perfectly with our production model.

**Comment by gashmish** [comment] 2019-05-03 16:47
@ANSHUMAN87:

> The output shape is supposed to be [?, 48002, 40] as per padding

In original Keras model and in Tensorflow model we get 48000 when using padding='causal'

```
Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           (None, 48000, 40)         0         
_________________________________________________________________
dilated_conv_2 (Conv1D)      (None, 48000, 40)         3240      
=================================================================
```

**Comment by ANSHUMAN87** [comment] 2019-05-04 19:11
@gashmish : I am extremely sorry, i did some misinterpretation of the issue. Now i got the issue clearly.
There is a missed scenario which need to be handled in ResolveDilatedConv(). I will upload a fix for this and update you on that. Thanks a lot for your detailed reply.

Also i am little curious about your STRIDED_SLICE problem. Because no matter you disable as many Transformation like ResolveDilatedConv(), it should not break the Graph in the manner that subsequent Subgraphs will get impacted. If it is okay for you, would you be able to share small piece of code where this scenario is reproducible, i have tried with the steps you mentioned(like disable ResolveDilatedConv(), upload 2 PRs i shared), but did not reproduce.

**Comment by ANSHUMAN87** [comment] 2019-05-05 08:19
@gashmish : I have uploaded fix for your problem, please refer #28410. I have verified. Request you also to verify with this change. And do let me know your results.

Also request you to share the code snippet or steps to reproduce STRIDED_SLICE problem. I suspect this could be some other issue. 

Thanks a lot!

**Comment by alanchiao** [comment] 2019-05-06 16:14
@ANSHUMAN87 : thanks for the PR. Hopefully with your change, we'll be able to convert the WaveRNN model through TOCO. 

@gashmish: like Jared asked, may i ask for a direct pointer to where you got the WaveRNN model from? (e.g. Tensorflow Model Zoo, Github, etc ..). This is an important enough model that there should be conversion test to ensure conversion support stays going forward. If not, it's ok, I can try to find a canonical model online

**Comment by gashmish** [comment] 2019-05-06 18:47
@ANSHUMAN87: I tried to test PR [#28410](https://github.com/tensorflow/tensorflow/pull/28410), unfortunately it didn't work for me.

I use this script:
```
model_name = 'sample'
model_h5     = model_name + '.h5'
model_tflite = model_name + '.tflite'

# 1. Create

K.set_learning_phase(False)

input  = Input(
    name =  'input',
    shape = (48000, 40))

output = Conv1D(
    name          ='dilated_conv_2',
    filters       = 40,
    kernel_size   = 2,
    dilation_rate = 2,
    padding       = 'causal',
    activation    = 'tanh'
)(input)

model = Model(input, output)
model.summary()
model.save(model_h5)

# 2. Convert

converter = tf.lite.TFLiteConverter.from_keras_model_file(model_h5)
tflite_model = converter.convert()
open(model_tflite, "wb").write(tflite_model)

# 3. Test

interpreter = tf.lite.Interpreter(model_path=(model_tflite))
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(input_details)
print(output_details)
```

On TF master with your commit I get same results with 48002 size:
```
python3 create_tflite_dilated_conv_model.py 
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0506 21:28:29.620581 140263933794048 deprecation_wrapper.py:119] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:153: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0506 21:28:29.628713 140263933794048 deprecation_wrapper.py:119] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0506 21:28:29.630243 140263933794048 deprecation_wrapper.py:119] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           (None, 48000, 40)         0         
_________________________________________________________________
dilated_conv_2 (Conv1D)      (None, 48000, 40)         3240      
=================================================================
Total params: 3,240
Trainable params: 3,240
Non-trainable params: 0
_________________________________________________________________
W0506 21:28:29.653485 140263933794048 deprecation_wrapper.py:119] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0506 21:28:29.653728 140263933794048 deprecation_wrapper.py:119] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-05-06 21:28:29.657524: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3311950000 Hz
2019-05-06 21:28:29.657663: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a7e880 executing computations on platform Host. Devices:
2019-05-06 21:28:29.657677: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-06 21:28:29.669086: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1328] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
W0506 21:28:29.717485 140263933794048 hdf5_format.py:221] No training configuration found in save file: the model was *not* compiled. Compile it manually.
2019-05-06 21:28:29.719565: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-05-06 21:28:29.719639: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-05-06 21:28:29.725718: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:710] Optimization results for grappler item: graph_to_optimize
2019-05-06 21:28:29.725747: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:712]   function_optimizer: Graph size after: 51 nodes (0), 48 edges (0), time = 0.035ms.
2019-05-06 21:28:29.725753: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:712]   function_optimizer: Graph size after: 51 nodes (0), 48 edges (0), time = 0.055ms.
W0506 21:28:29.727740 140263933794048 deprecation.py:323] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/tensorflow/lite/python/util.py:237: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0506 21:28:29.727875 140263933794048 deprecation.py:323] From /home/tema/Work/voicesdk/data2/init/antispoof2/wavenent/wn/p3-tf-night/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2019-05-06 21:28:29.732639: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-05-06 21:28:29.732706: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-05-06 21:28:29.738309: E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node dilated_conv_2/kernel/Assign doesn't exist in graph
INFO: Initialized TensorFlow Lite runtime.
[{'quantization': (0.0, 0), 'name': 'input', 'shape': array([    1, 48000,    40], dtype=int32), 'index': 10, 'dtype': <class 'numpy.float32'>}]
[{'quantization': (0.0, 0), 'name': 'dilated_conv_2/Tanh', 'shape': array([    1, 48002,    40], dtype=int32), 'index': 2, 'dtype': <class 'numpy.float32'>}]
```

Can you please check this script in your workspace, may be i did something incorrectly?

**Comment by ANSHUMAN87** [comment] 2019-05-07 04:07
@gashmish: Thanks a lot for confirming. Even i was also suspecting there might be some more cases missed out. If possible please try to share, the cases where it has not converted. Will try to make solution for converter more generic.
  Yes you are right, together 3 PRs #28410, #27867 & #28179 will help the model works fine.

Just to remind you, are you able to reproduce the STRIDED_SLICE problem? If yes would you please share steps or pseudo code to reproduce it.
Thanks a lot for your efforts!

**Comment by gashmish** [comment] 2019-05-07 13:55
@ANSHUMAN87:
Here is 2 models in archive, almost identical to what we are using. Input is (48000,) and output is (4,).
[models.tar.gz](https://github.com/tensorflow/tensorflow/files/3152890/models.tar.gz)

With 3 RPs applied, running model wavenet_classifier.tflite :
```
ERROR: tensorflow/lite/kernels/strided_slice.cc:152 op_context.input->type != op_context.output->type (2 != 1)
ERROR: Node number 207 (STRIDED_SLICE) failed to prepare.
```
This is coused by Keras layer Reshape.

In model wavenet_classifier_fixed.tflite Reshape is changed to Squeeze, it runs correctly.

Thank you very much for support!

**Comment by ANSHUMAN87** [comment] 2019-05-22 05:08
@gashmish : Sorry i was busy in other tasks. Now i checked your new models shared. But i could not find anywhere BatchToSpace and SpaceToBatch Ops in h5 files which needs to be converted to Dilated Conv. Would you please cross check. Please let me know if i miss anything. Thanks!

**Comment by ANSHUMAN87** [comment] 2019-05-23 08:09
@gashmish : Please ignore my last comment i have deleted that. 
It was some tool issue.
I am analyzing the issue currently, will update you as soon as possible. Thanks!

**Comment by karolbadowski** [comment] 2019-06-10 11:35
Hello. I believe I have a similar issue. My model based on TCN has 3 issues. Last of which is probably similar to what is mentioned here. I would highly appreciate an advice.

First my environment:

> I am working with Pycharm, python3, Keras 2.2.4 tensorflow-gpu 1.12.0
> I have probelm using convert() method in pycharm, just like other people voicing it in https://stackoverflow.com/questions/52599110/tensorflow-tococonverter-gives-toco-from-protos-error , so I have changed a constant in /home/[MYUSER]/.virtualenvs/[MYPROJECTNAME]lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite_constants.py:  EXPERIMENTAL_USE_TOCO_API_DIRECTLY = True

Now the problem:
I am using keras-tcn library from https://github.com/philipperemy/keras-tcn/blob/master/tcn/tcn.py in ordet to create a Temporal convolutional Neural Network.
My model has 3 issues in conversion to TFLite.

1. It has problem with Abs() layer, so I have changed code of library in line 25 from:
> max_values = K.max(K.abs(x), 2, keepdims=True) + 1e-5
to:
> max_values = K.max(K.pow(x*x,0.5), 2, keepdims=True) + 1e-5
It is an ugly solution, but conversion proceeds further.

2. This code gets error during conversion, whenever nb_stacks is changed from 2 to 1:
> new_layer = TCN(kernel_size=3,dilations=[1],return_sequences=False,nb_filters=128,nb_stacks=2)(previous_layer)
Error says : "A merge layer should be called on a list of inputs." 

3. Another error shows up whenever any of the dilation is >1 while kernel_size being >1, so for example:
new_layer=TCN(kernel_size=3,dilations=[2,4],return_sequences=False,nb_filters=128,nb_stacks=2)(previous_layer)
If previous layer had the time dimension equal 31, the error would look like:
Error states: "Check failed: dim_x == dim_y (31 vs. 35)Dimensions must match"

When is the new set of improvements estimated to show up? I will gladly perform an update then. Is there any temporary hack I can apply to go around this issue till then?

**Comment by ANSHUMAN87** [comment] 2019-07-03 11:07
@karolbadowski : I will try find a solution for you. By any chance, do you have some small reproducible code or model for your issues? Please share if possible.
And if you think it is related, have you tried with the PRs i shared in this issue links?
Please do let me know the results post the PRs.
Thanks!

**Comment by karolbadowski** [comment] 2019-07-03 11:57
@ANSHUMAN87 Hello.  For now I use a hack in which I try to express same shape of TCN neural network with usage of "same" padding instead of "causal". It is not perfect solution, but at least something for a demo that I am preparing.
To make it work I have created own PR to Keras-TCN library: https://github.com/philipperemy/keras-tcn/pull/56

I did not have opportunity to try your PR's yet, as I use prebuild version of TF-Lite from official installation. However I voted here: https://github.com/tensorflow/tensorflow/issues/21526 for your changes to be accepted / reviewed (I see that they are awaiting review from someone with write privilages).

Lightweight example of TCN neural network with "causal" padding can be created with this library: https://github.com/philipperemy/keras-tcn by calling constructor of class TCN().

For example:

```
input_tensor = Input(shape=(31, 1024))  # it would be input of 31 moments in time, each having 1024 features
temporal_tensor = TCN(kernel_size=3,dilations=[1,2,4,8],return_sequences=False,nb_filters=32)(input_tensor)
output_tensor = Dense( 1 )(temporal_tensor)
m = Model(inputs=[input_tensor], outputs=[output_tensor])
m.compile(optimizer='adam', loss='mse')
```

**Comment by ANSHUMAN87** [comment] 2019-07-09 10:49
@karolbadowski : Thanks for sharing details.
I have verified the TCN conversion & Inference in TFLite.
My 3 PRs #28410, #27867 & #28179 solve the blocking issue you are facing.
So i would suggest, as it is taking long time to get merged, you can setup one build environment of Tensorflow latest code locally, and merge my 3 PRs mentioned above.
Then you can convert the TCN models and will be able to inference as well.
That will be just one time effort.

NOTE: I have used mnist_example TCN to verify my changes, and i believe it coincides with your requirement also.

Please let me know if you need anything else, Thanks!

**Comment by peachthiefmedia** [comment] 2019-10-22 23:16
@ANSHUMAN87 Thanks for the PRs will help with the same issue I'm having too.

**Comment by karolbadowski** [comment] 2019-11-07 12:55
Thank you @ANSHUMAN87 
Do you know if the change is already merged with release version of TensorFlow (if so, since which one)?

**Comment by karolbadowski** [comment] 2020-04-08 07:05
Hello. Do you know for which release version of TensorFlow this change is planned?

**Comment by mohantym** [comment] 2021-09-16 15:55
Hi @gashmish ,
We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions.  Thanks!

**Closed** 2021-09-30 16:59 UTC
Labels: stat:awaiting response, stalled, comp:lite
