### ISSUE TITLE
Attempting to convert model from basic_classification dataset to TFLite

### ISSUE THREAD

**Issue by RobinHSanner** [tensorflow/tensorflow#26708] opened 2019-03-14 16:48 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- OS Platform: Windows 10 x64
- Tensorflow installed from: tf-nightly-2.0-preview
- TensorFlow version: 2.0 Preview
- Python version: 3.6
- Installed using: pip
- Doc Link:
https://www.tensorflow.org/alpha/tutorials/keras/basic_classification
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r2/convert/concrete_function.md

I am starting from the basic_classification dataset and attempting to save the model result as tflite but can't figure out how to perform the operation correctly.  When I export the saved model it tells me that the function will only be available through the v1 compatibility library and that 'Export includes no default signature'.  Trying to create the concrete function directly off the generated model returns the error 'Sequential object has no attribute 'signatures''.  

It would be really nice if those example datasets included in their instructions how to save the model as a tflite model.

I'd also like to restore a v1 frozen model and save it as a tflite model but can't figure that out either.  The instructions about concrete functions appear to imply that only Tensorflow 2.0 models (properly created) can be converted to tflite models.

Can v1 models be saved as v2 tflite models or do v1 models have to be saved using the compat.v1 TFLiteConverter only?

**Comment by gargn** [comment] 2019-03-14 17:22
Can you provide the following so that I can reproduce the errors you are getting and suggest the next steps you should take:

1. Your 2.0 model file that you generated from the basic_classification dataset that you are trying to convert
2. Your conversion code
3. The exact error message that you are getting

Late yesterday, I added a short section to the `python_api.md`[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r2/convert/python_api.md] document for clarification on what's supported in the 2.0 converter:

> `TFLiteConverter` in 2.0 supports SavedModels and Keras model files generated in both 1.X and 2.0. However, the conversion process no longer supports frozen `GraphDefs` generated in 1.X. Users who want to convert frozen GraphDefs to TensorFlow Lite should use `tensorflow.compat.v1`.

This means some 1.X models can be converted using the 2.0 converter, but not 1.X frozen graphs.

Hope this helps. Thanks for your patience!

**Comment by RobinHSanner** [comment] 2019-03-14 20:02
[saved.zip](https://github.com/tensorflow/tensorflow/files/2968142/saved.zip)
First I was just trying to save and load the regular Tensorflow 2.0 model in saved model format but ran into problems with that.
To save this model I followed the directions in https://www.tensorflow.org/alpha/tutorials/keras/basic_classification and then used the Python command:
>>> tf.saved_model.save(model, './saved')
which created a model in the format 'TensorFlow Saved Model v1'

When I attempt to load it with the Python command:
>>> loaded = tf.saved_model.load('./saved')
I get the AttributeError: '_UserObject' object has no attribute '_create_or_restore_slot_variable'
So I couldn't create a concrete_function from a model signature.

I then tried to create the concrete function using:
>>> run_model = tf.function(lambda x: model(x))
>>> concrete_func = run_model.get_concrete_function(tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
and got the error: 
WARNING: Entity <function <lambda> at 0x000002B660E61BF8> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function <lambda> at 0x000002B660E61BF8>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function <lambda> at 0x000002B660E61BF8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

I then tried:
>>> class BasicModel(tf.Module):
>>>     @tf.function(input_signature=[tf.TensorSpec(shape=[None,28,28], dtype=tf.float32)])
>>>     def get_x(self, x):
>>>         return x
>>> img = test_images[0]
>>> img = (np.expand_dims(img,0))
>>> input_data = tf.constant(img, shape=[1,28,28])
>>> concrete_func = root.get_x.get_concrete_function(input_data)
with the same error as above

**Comment by RobinHSanner** [comment] 2019-03-14 20:05
I eventually used:
>>> concrete_func = root.get_x.get_concrete_function(img)
>>> converter = tf.lite.TFLiteconverter.from_concrete_function(concrete_func)
>>> tflite_model = converter.convert()
and received the error: 
ValueError: Unsupported tf.dtype <dtype: 'float64'>

**Comment by gargn** [comment] 2019-03-19 00:32
When I try converting the model you provided, I ran into an issue with optimizers. However, I believe that's  been resolved since. I tried reproducing the model and converting it locally and I was successfully able to convert it with the following code:

```
run_model = tf.function(lambda x: model(x))
concrete_func = run_model.get_concrete_function(
      tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
tflite_model = converter.convert()
open("/tmp/mnist_fashion/converted_model.tflite", "wb").write(tflite_model)
```

For reference, this was the complete code:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
from tensorflow import keras
import numpy as np


def get_data_set(num_images):
  """Returns the training and testing data base."""
  fashion_mnist = keras.datasets.fashion_mnist
  (train_images, train_labels), (test_images, test_labels) = (
      fashion_mnist.load_data())
  train_images = train_images / 255.0
  test_images = test_images / 255.0

  num_images = min(num_images, len(train_images))
  train_images = train_images[:num_images]
  train_labels = train_labels[:num_images]
  return train_images, train_labels


def build_model(train_images, train_labels, epochs=5):
  """Build the model."""
  model = keras.Sequential([
      keras.layers.Flatten(input_shape=(28, 28)),
      keras.layers.Dense(128, activation='relu'),
      keras.layers.Dense(10, activation='softmax')
  ])
  model.compile(
      optimizer='adam',
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy'])
  model.fit(train_images, train_labels, epochs)
  return model


def main():
  export_dir = '/tmp/mnist_fashion'

  # Build the model.
  train_images, train_labels = get_data_set(num_images=100)
  model = build_model(train_images, train_labels, epochs=1)
  tf.saved_model.save(model, export_dir) # not needed for this code

  # Convert the model directly.
  run_model = tf.function(lambda x: model(x))
  concrete_func = run_model.get_concrete_function(
      tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
  converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
  tflite_model = converter.convert()
  open("/tmp/mnist_fashion/converted_model.tflite", "wb").write(tflite_model)


if __name__ == '__main__':
  main()
```

I was also able to convert the SavedModel with the following code:
```
model = tf.saved_model.load(export_dir)
concrete_func = model.signatures[
    tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 28, 28])
converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
tflite_model = converter.convert()
open("/tmp/mnist_fashion/converted_model.tflite", "wb").write(tflite_model)
```

**Comment by RobinHSanner** [comment] 2019-03-19 16:29
Are you using the nightly build?

I get this:
>>> concrete_func = run_model.get_concrete_function(tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
W0319 12:28:09.571433 40164 tf_logging.py:161] Entity <function <lambda> at 0x00000276D2AF62F0> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function <lambda> at 0x00000276D2AF62F0>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function <lambda> at 0x00000276D2AF62F0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING: Entity <function <lambda> at 0x00000276D2AF62F0> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function <lambda> at 0x00000276D2AF62F0>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function <lambda> at 0x00000276D2AF62F0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

**Comment by gargn** [comment] 2019-03-27 16:37
I tested on today's nightly `2.0.0.dev20190327` and I was able to successfully run the script in https://github.com/tensorflow/tensorflow/issues/26708#issuecomment-474152784.

**Comment by gargn** [comment] 2019-04-11 00:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

Adding here for documentation for future users. This functionality has been changed in https://github.com/tensorflow/tensorflow/commit/312222d2a0657d4e0086ec0add4331063d0b2264. `from_concrete_function` is now `from_concrete_functions`. Additionally, `from_keras_model` and `from_saved_model` have been added.

**Closed by gargn** 2019-04-11 00:28 UTC
Labels: 2.0, comp:lite
