### ISSUE TITLE
tf.math.sign() gives inconsistent output for the same input values for small complex numbers

### ISSUE THREAD

**Issue by pawlick2** [tensorflow/tensorflow#50883] opened 2021-07-21 19:54 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: X
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.6.12
- Bazel version (if compiling from source): X
- GCC/Compiler version (if compiling from source): X
- CUDA/cuDNN version: X
- GPU model and memory: X

**Describe the current behavior**
The function `tf.math.sign()` gives inconsistent results for `tf.complex64` values with small magnitudes.  When passing `tf.math.sign()` two slices of the same Tensor, one of which wholly includes the elements of the other, the same numerical inputs result in different values.

Referencing the code example below:
tf.math.sign(z[23:26]) -> [1.+0.j, 1.+0.j, 1.+0.j]
tf.math.sign(z[23:27]) -> [nan+nanj, nan+nanj, nan+nanj, nan+nanj]

I've also demonstrated this behavior when using the docker image `tensorflow/tensorflow:2.5.0`

**Describe the expected behavior**
Referencing the code example below:
tf.math.sign(z[23:26]) -> [1.+0.j, 1.+0.j, 1.+0.j]
tf.math.sign(z[23:27]) -> [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j (or some other value)]

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
print(tf.__version__)
x = tf.constant([10 ** -n for n in range(47)], dtype=tf.float32)
z = tf.complex(x, 0.0)

q0 = tf.math.sign(z[23:26])  # result: [1.+0.j, 1.+0.j, 1.+0.j]
q1 = tf.math.sign(z[23:27])  # result: [nan+nanj, nan+nanj, nan+nanj, nan+nanj]
```

**Comment by saikumarchalla** [comment] 2021-07-30 03:10
@pawlick2  I can able to replicate the issue in TF 2.5 version but in TF -Nightly 2.7 i am getting different output instead of nan. Please check it once.

**Comment by Alex-Pawlicki-Bose** [comment] 2021-08-04 17:28
Yes, looks like this doesn't happen when using 2.7 nightly.

**Comment by saikumarchalla** [comment] 2021-08-05 04:26
@pawlick2 Seems the issue is resolved in TF nightly version. Please feel free to re-open the issue if needed . Thanks!

**Closed by saikumarchalla** 2021-08-05 04:26 UTC
Labels: TF 2.5, comp:ops, stat:awaiting response, type:bug
