### ISSUE TITLE
bug in rsqrt

### ISSUE THREAD

**Issue by BlueSkyyyyyy** [tensorflow/tensorflow#51043] opened 2021-07-30 06:47 UTC
---------------------------------------------------------------------------part 1-----------------------------------------------------------------
**my code:**
````
import tensorflow as tf
import os
import numpy as np
np.set_printoptions(threshold=np.inf)

def test():
    with tf.device("/device:CPU:0"):
    # with tf.device('/gpu:1'):
        a=tf.constant([1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38])
        b = tf.rsqrt(a)
    return b

if __name__=='__main__':
    with tf.Session() as sess:
        print(sess.run(test()))
````

**expect the right result:**
_[9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18, 9.223371843921341e+18]_

in the env: **tensorflow== 1.14.0  python=3.6.8**
get the wrong result:
[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
 1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18]

in the env: **tensorflow== 1.14.0  python=3.6.8**
get the wrong result:
_[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
 1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18]_

in the env: **tensorflow== 1.14.0  python=2.7.18**
get the wrong result:
_[         inf          inf          inf          inf          inf
          inf          inf          inf 9.223372e+18]_

note:if I use the gpu device, also get the wrong result
----------------------------------------------------------------------part 2-----------------------------------------------------------------
**my code2:**
````
import tensorflow as tf
import os
import numpy as np
np.set_printoptions(threshold=np.inf)
import math

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
def test():
    a=tf.constant([1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38])
    b = tf.math.rsqrt(a)
    print(b)
    return
    
if __name__=='__main__':
    test()
````

in the env: **tensorflow== 2.4.0  python=3.8.5**
get the wrong result:
_[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
 1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18]_

in the same env **tensorflow== 2.4.0  python=3.8.5** if I use GPU, I mean os.environ["CUDA_VISIBLE_DEVICES"] = "1"
get the right result:
[9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18
 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18]

----------------------------------------------------------------------part 3-----------------------------------------------------------------
note:
1、the small shape tend to get the right result
2、similarity bug also in tf.floor

**Comment by tilakrayal** [comment] 2021-07-30 12:01
@BlueSkyyyyyy ,

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue.Thanks!

**Comment by BlueSkyyyyyy** [comment] 2021-07-31 14:03
> @BlueSkyyyyyy ,
> 
> We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Thanks!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**no**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **cpu**
- TensorFlow installed from (source or binary):**binary**
- TensorFlow version (use command below):**2.4.0**
- Python version:**3.8.5**
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA


**Describe the current behavior**
use tf.math.rsqrt to cal:
 a=tf.constant([1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38])
    b = tf.math.rsqrt(a)

get the wrong results:
[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18]

**Describe the expected behavior**
[9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18
9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18]

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):no
- Briefly describe your candidate solution(if contributing):no

**Standalone code to reproduce the issue**
my code 
```
import tensorflow as tf
import os
import numpy as np
np.set_printoptions(threshold=np.inf)
import math

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
def test():
    a=tf.constant([1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38])
    b = tf.math.rsqrt(a)
    print(b)
    return
    
if __name__=='__main__':
    test()

```

**Other info / logs** Include any logs or source code that would be helpful to
**no**

**Comment by BlueSkyyyyyy** [comment] 2021-07-31 14:13
> @BlueSkyyyyyy ,
> 
> We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Thanks!

I use the template to describe the problem as above. not only tf 2.4 but also other version has the similarity problem( I have trytensorflow== 1.14.0+ python=3.6.8  and tensorflow== 1.14.0 python=2.7.18 ).

**Comment by tilakrayal** [comment] 2021-08-02 13:14
@Saduf2019 ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f4397520f5bf766bf99160a9f4d6a996/51043.ipynb).

**Comment by BlueSkyyyyyy** [comment] 2021-08-05 09:27
@Saduf2019 ,@tensorflowbutler， 
do you know why tensorflow has this bug and how to solve it

**Comment by Saduf2019** [comment] 2021-08-06 14:24
@BlueSkyyyyyy 
Can you try setting the dtype of the tf.constant to tf. float 64 bit floating point tensor)
2)avoid using main, check if you can get better result by removing main.
If you really have to use main then try putting your code in py file in colab and try to execute using filename.py. [the loss of precision, due to the large number you have chosen causing the issue]

**Comment by BlueSkyyyyyy** [comment] 2021-08-09 03:52
@Saduf2019
1）I remove main ,but have the same problem;
2)  if I use tf.float64, can get the right ans, but it is not a same question; float32 should support the precision. 

as i use float32 in numpy or python,  can get the right ans:
code:
````
import numpy as np
np.set_printoptions(threshold=np.inf)
import math

a = [1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38,1.1754944e-38]

ans_py = []
for aa in a:
    ans_py.append(float(1.0/math.sqrt(float(aa))))
print("ans_py:{}".format(ans_py))

a_np = np.array(a,dtype="float32")
ans_np = 1.0/np.sqrt(a_np)
print("ans_np:{}".format(ans_np))
````
run get the ans:
```
ans_py:[9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18, 9.22337184392134e+18]
ans_np:[9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18
 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18
 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18]
```
so i think float32 is enough for this case .

**Comment by Saduf2019** [comment] 2021-08-09 10:21
@BlueSkyyyyyy 
This is not a bug or performance issue, please move this to closed status and for any further queries open this at the tf discussion forum.

**Comment by BlueSkyyyyyy** [comment] 2021-08-13 12:04
@Saduf2019 
Why it is not a bug, I get obviously wrong result by tf .  Is there any knowledge or I have neglect lead to the wrong use ? thanks you r patient

**Comment by ymodak** [comment] 2021-08-24 20:11
I tested in colab both cpu and gpu implementation results match and I get
```python
tf.Tensor(
[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
 1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18], shape=(9,), dtype=float32)
```
I wonder why you are seeing different results. You may try test with google colab.

**Comment by BlueSkyyyyyy** [comment] 2021-09-07 06:12
@ymodak

> tf.Tensor(
[1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19 1.383168e+19
 1.383168e+19 1.383168e+19 1.383168e+19 9.223372e+18], shape=(9,), dtype=float32)
this result is not right, that is the key poit. 1.383168e+19 is wrong ,9.223372e+18 is right.

**Comment by cantonios** [comment] 2021-09-16 19:16
This is likely due to an Eigen approximation.  If `EIGEN_FAST_MATH = 1` (the default), then Eigen uses the fast reciprocal sqrt approximation, which is *much* faster, but less accurate (particularly as you deviate away from zero).  See [here](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/arch/AVX/MathFunctions.h#L133).

If compiling TF from source, you can try explicitly disabling this (adding `-DEIGEN_FAST_MATH=0` to the set of compile flags).

**Comment by BlueSkyyyyyy** [comment] 2021-09-24 08:44
@cantonios 
thank you so much

**Comment by sachinprasadhs** [comment] 2021-12-04 01:41
> @cantonios thank you so much

If your issue is resolved, could you please close the issue. Thanks!

**Closed** 2021-12-07 13:38 UTC
Labels: stat:awaiting response, type:bug, comp:ops, TF 2.4
