### ISSUE TITLE
tensorflow c++ api session->Run segv for batch size>1

### ISSUE THREAD

**Issue by luochao436** [tensorflow/tensorflow#22827] opened 2018-10-09 05:43 UTC
Hi,

  i build tensorflow 1.4.0 to .so and call c++ session api Run to predict, when the input batch size is 1, the  Run api works well, but  batch_size    > 1, the Run will segv as follows:

#12 0x00002b12e0122c72 in tensorflow::LaunchMatMulBase<Eigen::ThreadPoolDevice, float>::launch(tensorflow::OpKernelContext*, tensorflow::Tensor const&, tensorflow::Tensor const&, Eigen::array<Eigen::IndexPair<long>, 1ul> const&, std::vector<long long, std::allocator<long long> >*, bool, tensorflow::Tensor*) () from lib/64bit/libtensorflow_cc.so                                                                                                                                 
#13 0x00002b12e0123231 in tensorflow::MatMulOp<Eigen::ThreadPoolDevice, float, false>::Compute(tensorflow::OpKernelContext*) () from lib/64bit/libtensorflow_cc.so                                                                                                                                           
#14 0x00002b12e20e6a4c in tensorflow::ThreadPoolDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) () from lib/64bit/libtensorflow_framework.so                                                                                                                                            
#15 0x00002b12e20b7669 in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) () from lib/64bit/libtensorflow_framework.so                                                                                                    
#16 0x00002b12e20a6290 in std::_Function_handler<void ()(), std::_Bind<std::_Mem_fn<void (tensorflow::(anonymous namespace)::ExecutorState::*)(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> ()(tensorflow::(anonymous namespace)::ExecutorState*, tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> >::_M_invoke(std::_Any_data const&) () from lib/64bit/libtensorflow_framework.so                                                  
#17 0x00002b12e1d576b7 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) () from lib/64bit/libtensorflow_framework.so                                                                                                                                              
#18 0x00002b12e1d565a2 in std::_Function_handler<void ()(), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from lib/64bit/libtensorflow_framework.so                                                                       
#19 0x00002b12e7726f50 in execute_native_thread_routine_compat () from /icd/dlsh_t2b/luther/tf.integ2.dev/tools.lnx86/lib/64bit/libstdc++.so.6                                
#20 0x0000000004385269 in create_head(void*) ()                                                                                                                               
#21 0x00002b12e71309d1 in start_thread () from /lib64/libpthread.so.0        
    
*** Stack trace in log file.
free model
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided

the predict code :
   std::vector<tensorflow::Tensor> outputs;
    tensorflow::Status run_status = session_->Run({input},{model_outputs_name_}, {}, &outputs);

After i upgrade tensorflow to 1.8.0, crash too, please help to review this issue.

chao

**Comment by tensorflowbutler** [comment] 2018-10-09 18:42
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-09 23:28
Can you please test it against the latest version of TensorFlow and post your findings?
Thanks!

**Comment by ymodak** [comment] 2018-10-15 19:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-15 19:13 UTC
Labels: stat:awaiting response
