### ISSUE TITLE
AlreadyExistsError: Resource _tensor_arrays

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/tensorflow#5437] opened 2016-11-07 06:33 UTC
I was trying to use a tf.while loop inside another tf.while loop . I cross checked many times , but I am getting this error . If somehow managed to get over this error , I am getting another error called nothing to read from index 0 of tensor array , as nothing has been written to it . If you guys want , I can post the full code . This code is based on the modification of code by @alrojo , from his wondeful tutorial . 

![issue1](https://cloud.githubusercontent.com/assets/10637096/20048372/1d95eeda-a4e2-11e6-8011-36fdfaf35f8c.png)
![issue2](https://cloud.githubusercontent.com/assets/10637096/20048373/1d96cf9e-a4e2-11e6-9c78-e8e8836767f9.png)

**Comment by aselle** [comment] 2016-11-07 19:14
Please try to reduce it to a meaningful and minimal test case that reproduces the Error. Screenshots are good to show context, but it is very important to post logs in text form so future users can benefit from this issue (it is also difficult to read and follow). Please provide information about exactly your version and environment (see the template for what to include).

**Comment by s4sarath** [comment] 2016-11-08 04:36
@aselle - I will provide a detailed explanation of what the code is and where I am getting the error . 
What I am trying to do is , I will get a 3 x 10 matrix in we_project and I am having 3 x 10 x 5 matrix in attention_input_mod . I need to do a matmul of each row of 3 x 10 matrix to corresponding matrix batch in 3 x 10 x 5 . That is , first row 0f 3 x 10 will take a  matmul with first batch of 3 x 10 x 5 ( [0, : ,:]) and so on . For that , I am making use of tf.while_loop inside the other loop which is mostly a duplication of @alrojo code . So , I use sub_initial and sub_input to hold the 2d and 3d matrix respectively and inside sub_decoder function I will try to iterate until I reach batch_len ( 3 by default ) and I read each row and matrix from sub_initial and sub_input respectively and then trying to store the result in temp_holder TensorArray . But getting the following error

AlreadyExistsError: Resource _tensor_arrays/temp_holder/N10tensorflow11TensorArrayE 


```
target_dims = 8
attention_dims = 10
input_max_len =  5
attn_len = 3
max_sequence_length = 3
num_units = 10
batch_len = 3

weight_initializer = tf.truncated_normal_initializer(stddev=0.1)

attention_input = tf.convert_to_tensor(np.random.rand(3,5,10).astype(np.float32)) ##### consider it as RNN encoder output
attention_input_mod = tf.transpose(attention_input , [0,2,1])
initial_state = tf.convert_to_tensor(np.random.rand(3,10).astype(np.float32)) ######## Last states of 3 batches of RNN
target_input = tf.convert_to_tensor(np.random.rand(3,3,8).astype(np.float32))   ###### target input
inputs = tf.transpose(target_input, perm=[1, 0, 2])

var = tf.get_variable # for ease of use

W_z_x = var('W_z_x', shape=[target_dims, num_units], initializer=weight_initializer)
W_z_h = var('W_z_h', shape=[num_units, num_units], initializer=weight_initializer)
b_z = var('b_z', shape=[num_units], initializer=weight_initializer)
W_r_x = var('W_r_x', shape=[target_dims, num_units], initializer=weight_initializer)
W_r_h = var('W_r_h', shape=[num_units, num_units], initializer=weight_initializer)
b_r = var('b_r', shape=[num_units], initializer=weight_initializer)
W_c_x = var('W_c_x', shape=[target_dims, num_units], initializer=weight_initializer)
W_c_h = var('W_c_h', shape=[num_units, num_units], initializer = weight_initializer)
b_c = var('b_c', shape=[num_units], initializer=weight_initializer)
middle_matrix = var('middle', shape=[num_units, num_units], initializer = weight_initializer)


###### Reading the first element in target of each batch and creating a new state
input_ta = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True, name = 'input_ta')
input_ta = input_ta.unpack(inputs)
# calculate the GRU
time = tf.constant(0)
x_t = input_ta.read(time)
z = tf.sigmoid(tf.matmul(x_t, W_z_x) + tf.matmul(initial_state, W_z_h) + b_z) # update gate
r = tf.sigmoid(tf.matmul(x_t, W_r_x) + tf.matmul(initial_state, W_r_h) + b_r) # reset gate
c = tf.tanh(tf.matmul(x_t, W_c_x) + tf.matmul(r*initial_state, W_c_h) + b_c) # proposed new state
new_state = (1-z)*c + z*initial_state # new state
initial_state = new_state
       
def decoder_cond(time, state, output_ta_t, attention_tracker):
    return tf.less(time, max_sequence_length)


def decoder_body_builder(feedback=False):
    def decoder_body(time, old_state, output_ta_t, attention_tracker):
        if feedback:
            def from_previous():
                prev_1 = tf.matmul(old_state, W_out) + b_out
                return tf.gather(embeddings, tf.argmax(prev_1, 1))
            x_t = tf.cond(tf.greater(time, 0), from_previous, lambda: input_ta.read(0))
        else:
            x_t = input_ta.read(time)

        # calculate the GRU



        def sub_decoder_cond(sub_time,temp_holder_):
                return tf.less(sub_time, 3) 

        def sub_decoder_body_builder():

            def sub_decoder_body(sub_time ,temp_holder_t):
                sub_x_t = tf.reshape(sub_initial_.read(sub_time) , [1,-1])
                sub_i_t = sub_input.read(sub_time)
                sub_res = tf.matmul(sub_x_t, sub_i_t)
                temp_holder_t.write(sub_time, sub_res)

                return(sub_time+1, temp_holder_t )
            return sub_decoder_body


        we_project = tf.tanh(tf.matmul( initial_state , middle_matrix ))
        
        sub_initial_ = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True ,tensor_array_name='sub_initial')
        sub_input = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True, tensor_array_name = 'sub_input')
        temp_holder = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True , tensor_array_name = 'temp_holder'  )

        sub_initial_ = sub_initial_.unpack(we_project)
        sub_input = sub_input.unpack(attention_input_mod)
        sub_time = tf.constant(0)

        sub_loop_vars = [sub_time, temp_holder]

        _, temp_holder_out = tf.while_loop(sub_decoder_cond,
                                       sub_decoder_body_builder(),
                                       sub_loop_vars,
                                       swap_memory=False)



        alpha_time = temp_holder_out.pack()
        # temp_holder.close()
        alpha = alpha_time
        alpha_softmax = alpha
        # alpha_softmax = tf.nn.softmax(alpha)
        z = tf.sigmoid(tf.matmul(x_t, W_z_x) + tf.matmul(old_state, W_z_h) + b_z) # update gate
        r = tf.sigmoid(tf.matmul(x_t, W_r_x) + tf.matmul(old_state, W_r_h) + b_r) # reset gate
        c = tf.tanh(tf.matmul(x_t, W_c_x) + tf.matmul(r*old_state, W_c_h) + b_c) # proposed new state
        new_state = (1-z)*c + z*old_state # new state

        # writing output
        output_ta_t = output_ta_t.write(time+1, new_state)
        attention_tracker = attention_tracker.write(time, alpha_softmax)
        # context = tf.reduce_sum(tf.expand_dims(alpha_softmax, 2) * attention_input, [1])


        return (time + 1, new_state, output_ta_t, attention_tracker)
    return decoder_body


output_ta = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True, infer_shape=False)
attention_tracker = tensor_array_ops.TensorArray(tf.float32, size=1, dynamic_size=True, infer_shape=False)
time = tf.constant(0)
loop_vars = [time, initial_state, output_ta, attention_tracker]

_, state, output_ta, attention_tracker_holder = tf.while_loop(decoder_cond,
                                               decoder_body_builder(),
                                               loop_vars,
                                               swap_memory=False)
A = attention_tracker_holder.pack()
O = output_ta.pack()
    
sess = tf.InteractiveSession()
sess.run(tf.initialize_all_variables())
```

**Comment by alrojo** [comment] 2016-11-08 15:35
Without testing the code:
`AlreadyExistsError` might be because you redefine the TensorArray at every iteration of the `while_loop`.

It does not seem like the the TensorArrays you define are dependent on anything in the `while_loop`. Try defining them outside (before).

**Comment by s4sarath** [comment] 2016-11-09 02:32
@aselle @alrojo - But , 3 Tensor array has to be empty , at each start of firs loop ( tf.while loop for attention ) . Moreover , I tried initializing the 3 Tensor Arrays outside the loop , which results in UnboundLocalError: local variable 'sub_initial_' referenced before assignment , which makes sense from the Python Point of View . I have no idea , where the code is doing wrong from the logical aspect .

**Comment by s4sarath** [comment] 2016-11-11 04:56
@aselle @alrojo  @ebrevdo - Is this a bug or is this how , tf while loop is supposed to work ?

**Comment by ebrevdo** [comment] 2016-11-12 23:24
What version of tf are you using? What happens if you don't pass the TensorArrays name arguments?

**Comment by s4sarath** [comment] 2016-11-14 02:23
@ebrevdo @aselle - Without passing tensor array name as arguments also , I am getting the same error . Tensor array name was more of a debugging mode for me , to understand which Tensor array is causing the error . AlreadyExistsError: Resource _tensor_arrays/while/TensorArray_6/N10tensorflow11TensorArrayE

The tensorflow version was 0.9 

I upgraded it to 0.11 . Now the error has changed . 
InvalidArgumentError: TensorArray while/TensorArray_6_3: Could not read from TensorArray index 0 because it has not yet been written to.
How come this error is happening , if we are properly writing it in each iteration. Please have a look .

**Comment by ebrevdo** [comment] 2016-11-14 15:40
Do you read multiple times from the same index?

On Nov 13, 2016 6:23 PM, "s4sarath" <notifications@github.com> wrote:

> <https://github.com/ebrevdo>

> @ebrevdo <https://github.com/ebrevdo> @aselle <https://github.com/aselle>
- Without passing tensor array name as arguments also , I am getting the
same error . Tensor array name was more of a debugging mode for me , to
understand which Tensor array is causing the error . AlreadyExistsError:
Resource _tensor_arrays/while/TensorArray_6/N10tensorflow11TensorArrayE
>
> The tensorflow version was 0.9
>
> I upgraded it to 0.11 . Now the error has changed .
> InvalidArgumentError: TensorArray while/TensorArray_6_3: Could not read
from TensorArray index 0 because it has not yet been written to.
> How come this error is happening , if we are properly writing it in each
iteration. Please have a look .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/5437#issuecomment-260234116>,
or mute the thread

**Comment by s4sarath** [comment] 2016-11-15 01:45
@ebrevdo Yes , but at different iterations . So the idea is we are having a main while loop , which will run say 5 times . Inside that I calculate a (m =3 x 10) matrix ( 3 here is batch size , but may vary dynamically ) . My aim is , this 3 x 10 has to multiply with a (am= 3 x 10 x 5) matrix in the following way 
In numpy way it is 
```
store = []
for i in range(batch_size=3):
    store.append( np.dot( m[i, :] , am[i,:,:]))
store = np.array(store)
```
This process has to happen every time the main while loop is running . So to achieve this , I make use of tensor array , which is storing the 3 x 10 and 2 x 10 x 5 matrix to separate Tensor Array , each time the main loop is running , because , this value changes with each loop of main while loop . In simple words , it is a nested for loop . Please have a look at the code in the top comments .

**Comment by girving** [comment] 2016-11-17 17:14
@ebrevdo Further comments?

**Comment by s4sarath** [comment] 2016-11-24 03:50
@aselle @ebrevdo Why no response from anyone ?

**Comment by ebrevdo** [comment] 2016-11-24 05:30
There is an argument you can pass to the TensorArray constructor so it won't erase the tensor after a read.  You need to enable that parameter.

**Comment by s4sarath** [comment] 2016-11-24 10:54
@aselle @ebrevdo I think you are mentioning about clear_after_read argument. I tried that also, still same error. Can anyone have a look at the code ?

**Comment by ebrevdo** [comment] 2016-11-24 17:38
Probably won't make a difference but try creating your TensorArrays with size 0.

**Comment by s4sarath** [comment] 2016-11-25 05:11
Now sess.run(A) results in

array([], shape=(3, 0, 1, 10), dtype=float32) .

But no value. Error remains the same for sess.run(O). I think, if
someone familiar with Tensor

Array, it is just a matter of few minutes. If the way, the code has
been written is wrong, can anyone suggests

me an alternative, but make sure that it is differentiable.

**Comment by skye** [comment] 2017-06-16 17:40
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by skye** 2017-06-16 17:40 UTC
Labels: stat:awaiting tensorflower

**Comment by eram1205** [comment] 2017-11-10 11:02
Hi @s4sarath. I'm having the same issue, also using tf.while_loop. How did you solve it? Thanks!

**Comment by s4sarath** [comment] 2017-11-10 11:59
Hi , I did not resolve it yet . Find some complex alternate hacks .

**Comment by ebrevdo** [comment] 2017-11-10 16:52
What version of TF are you using?  I am not able to replicate the issue.  Can you repost a **minimal** example that causes it?  And have you tried in TF 1.4?
