### ISSUE TITLE
tensorboard --logdir=runs not working: Abort trap: 6

### ISSUE THREAD

**Issue by asmitapoddar** [tensorflow/tensorflow#40407] opened 2020-06-12 11:24 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: pip3
- CUDA/cuDNN version: -

I am trying to run tensorboard: `tensorboard --logdir=runs`.  
I have also tried: `tensorboard --logdir=runs --host=127.0.0.1`.  
I am running the command from the terminal from within the the directory, which contains the `runs` folder.

I get the following error:
```[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:393] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1367] 
CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: 
CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Abort trap: 6
```

My Python code contains the following lines:
```
tb_path = './runs/SimpleLSTM_MNIST'
if os.path.isdir(tb_path):
    shutil.rmtree(tb_path)

writer = tb.SummaryWriter(log_dir=tb_path)
```
My `runs` folder contains the folder `SimpleLSTM_MNIST`, which contains `events.out.tfevents.1591953948.computername.local.29440.0`.

I also tried installing `protobuf version 3.8.0`, as suggested [here](https://stackoverflow.com/questions/60028929/failing-to-launch-tensorboard-from-jupyter), but still get the same issue.

**Comment by gowthamkpr** [comment] 2020-06-16 10:06
As mentioned in this [comment](https://github.com/tensorflow/tensorflow/issues/35573#issuecomment-596863684), try using latest version of protobuf and lt me know if it works. Thanks!

**Comment by asmitapoddar** [comment] 2020-06-16 11:38
(This)[https://stackoverflow.com/questions/62342221/tensorboard-logdir-runs-not-working-abort-trap-6] is how I resolved the issue.

**Comment by gowthamkpr** [comment] 2020-06-17 18:31
@asmitapoddar I am glad this issue has been resolved. Please go ahead and close this issue. Thanks!

**Comment by asmitapoddar** [comment] 2020-06-18 08:41
@gowthamkpr resolving this issue required downgrading `tensorflow` to version 2.0.0 as well as `protobuf` to version 3.8.0. Is it possible to have `tensorboard` to be compatible on macOS with `tensorflow 2.2.2`?

**Comment by nfelt** [comment] 2020-07-02 02:20
Based on https://github.com/tensorflow/tensorflow/issues/35573 this sounds like a generic issue with importing TensorFlow at all, when using a certain combination of TF versus protobuf versions.  But in that issue it sounds mostly like newer versions of protobuf might fix it.

FWIW, I can't reproduce the issue myself (on macOS Catalina, with TF 2.2.0, it installs protobuf 3.12.2, and it all seems to work fine).

So my advice would be to try updating TF to 2.2.0, and you should also get protobuf 3.12.2, and see if you still have the issue.  If so, I would try `python -c import tensorflow` to confirm if it's a generic TF issue, and if that results in the same error I would follow up on #35573 directly instead of here.

If you do see this happening again with tensorboard but _not_ with tensorflow generally, then please launch `tensorboard` with `--verbosity=1` so we can pinpoint at what point TensorBoard hits this issue, and please provide as much detail as you can about how you installed TF/TB and their dependencies to trigger the issue (i.e. ideally commands you ran from scratch to get to that point, or at least the output of `pip freeze`).

I'm going to close proactively since this looks a lot like a duplicate, but if you can trace this back to tensorboard just leave a comment and we can revisit.

**Closed by nfelt** 2020-07-02 02:20 UTC
Labels: TF 2.2, comp:tensorboard, stat:awaiting tensorflower, type:bug
