### ISSUE TITLE
Feature Request: Update tf.image.sample_distorted_bounding_box to use Scalar Tensor Inputs

### ISSUE THREAD

**Issue by blake-varden** [tensorflow/tensorflow#10715] opened 2017-06-14 23:36 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0/5.1
- **GPU model and memory**:
Titan X
- **Exact command to reproduce**:

Can you please update the scalar inputs to tf.image.sample_distorted_bounding_box to also be accepted as Tensors.  I am dynamically creating min_object_covered values (random values) but currently can not input them to the function

**Comment by aselle** [comment] 2017-06-15 21:23
This looks like it could be done w/o breaking shape inference, but it would need to be done w/o breaking graphdef compatibility by creating a duplicate of the sample bounding box op as a V2. I am labeling as contributions welcome since this is not likely going to be worked on soon.

One work around would be to make a few discrete values that would be acceptible and use a switch statement to select between several bounding box ops.

**Comment by yongtang** [comment] 2017-06-20 01:44
Created a PR #10840 for this issue.

**Closed** 2017-07-24 22:38 UTC
Labels: stat:contributions welcome, type:feature
