### ISSUE TITLE
Tensorflow does not build in a python3 only environment

### ISSUE THREAD

**Issue by jhdulaney** [tensorflow/tensorflow#15618] opened 2017-12-24 23:02 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Fedora 27
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.4.1
- **Python version**: 
3.6.3
- **Bazel version (if compiling from source)**:
0.8.1
- **GCC/Compiler version (if compiling from source)**:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) 
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:

export LANG="en_US.UTF-8"
export PYTHON_BIN_PATH="/usr/bin/python3"
export PYTHON_LIB_PATH="/usr/lib64/python3.6/site-packages"
export TF_NEED_JEMALLOC="1"
export TF_NEED_S3="0"
export TF_NEED_GCP="0"
export TF_NEED_OPENCL="0"
export TF_ENABLE_XLA="0"
export TF_NEED_GDR="0"
export TF_NEED_VERBS="0"
export TF_NEED_MPI="0"
export TF_NEED_CUDA="0"
export TF_NEED_HDFS="0"
export CC_OPT_FLAGS="-march=native"
./configure

bazel build --action_env PATH="$PATH" --verbose_failures //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

When building tensorflow in an environment with only python3 (e.g. no /usr/bin/python but instead /usr/bin/python3) build fails.  As this is likely to become increasingly the case as other distributions drop python2.7 from default installs (and, eventually drop it altogether), this ought to be addressed.

### Source code / logs

ERROR: /builddir/build/BUILD/tensorflow-1.4.1/tensorflow/python/BUILD:4363:1: Executing genrule //tensorflow/python:framework_fast_tensor_util_cython_translation failed (Exit 127): bash failed: error executing command 
  (cd /builddir/.cache/bazel/_bazel_mockbuild/88de5ec7248fb8215eb84aeff796b606/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/builddir/.local/bin:/builddir/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib64/python3.6/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 bazel-out/host/bin/external/cython/cython_binary --cplus tensorflow/python/framework/fast_tensor_util.pyx && python -c '\''import shutil, sys; n = len(sys.argv); [shutil.copyfile(src.split(".")[0] + ".cpp", dst) for src, dst in zip(sys.argv[1:], sys.argv[1+n//2:])]'\'' tensorflow/python/framework/fast_tensor_util.pyx bazel-out/k8-py3-opt/genfiles/tensorflow/python/framework/fast_tensor_util.cpp')
/usr/bin/env: 'python': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 575.085s, Critical Path: 26.26s
FAILED: Build did NOT complete successfully

**Comment by skye** [comment] 2018-01-03 01:34
@gunan could you take a look or redirect? Thanks!

**Comment by gunan** [comment] 2018-01-03 06:36
I think the cause is in our bzl rules we defined, we try to execute python files like binaries. Here is my hacks to get around this problem, it is not working yet but I believe I touch all the necessary pieces on this commit:
https://github.com/gunan/tensorflow/commit/77eaad46df1fb6532577c130a2508665c17de049

The files we need to edit are:
Remove shebang in these files:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/gen_git_source.py#L1
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/build_info/gen_build_info.py

Edit the following rules to avoid trying to execute the files, build them as py_binaries first and then execute the built pieces:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L1564
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L1578
https://github.com/tensorflow/tensorflow/blob/master/third_party/git/git_configure.bzl#L15

And finally fix this rule. From what I can see the python command here is a noop, but I will need to verify it later:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl#L77

+CC @case540 @jart I may need help from you to guide me in this endeavor into skylark.

**Comment by tensorflowbutler** [comment] 2018-01-17 19:14
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 22:55
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tz579** [comment] 2018-02-06 17:04
@gunan @case540 Another 14 days has passed. Is there any other track page that I may have not known? Thanks a lot!

**Comment by tz579** [comment] 2018-02-06 17:06
@gunan @case540 Another 14 days has passed. Is there any other track thread(s) that I may have not known? Thanks a lot!

**Comment by jart** [comment] 2018-02-06 17:56
@gunan I could be of some assistance with review. Last time I touched this code was #14467. From the looks of https://github.com/gunan/tensorflow/commit/77eaad46df1fb6532577c130a2508665c17de049 this seems like a tough nut to crack. I barely understand this git/python autoconf code and my intuition tells me it *should* or *could* be significantly simpler. But not something I have cycles to think too deeply about right now.

**Comment by tz579** [comment] 2018-02-08 18:05
@jart Thanks a lot and I will try to use Miniconda2 for invoking like "/usr/bin env python" in the meantime.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:01
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-02-23 18:36
I thought I fixed everything (not merged to master yet), where I realized that any `py_test` or `py_binary` rule outputs get `/usr/bin/env python` by bazel.
So this is blocked by a bazel bug.
I am contacting bazel team to see how we can fix this.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:08
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:35
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-03-25 22:42
Looks like this is blocked on a bazel bug.
Bazel silently inserts the line "/usr/bin/env python" at the first line of each file.
Sometimes python3 does not get symlinked to "python" and without python2 build fails.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:35
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:02
Nagging Assignees @case540, @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:58
Nagging Assignees @case540, @gunan: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-05-28 06:43
This is still blocked on a bazel bug.

**Comment by tensorflowbutler** [comment] 2018-06-11 18:48
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-26 12:42
Nagging Assignees @case540, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-11 12:48
Nagging Assignees @case540, @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-26 19:11
Nagging Assignees @case540, @gunan: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jlisee** [comment] 2018-08-10 03:49
@gunan is there a bug tracking Bazel's insertion of that line?  Looks like [it's here](https://github.com/bazelbuild/bazel/blob/7a3e39fc20f1fba810d8023ff1608e39f501492a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L188)?

**Comment by gunan** [comment] 2018-08-10 06:18
It has been a while, I do not remember completely.
But I remember discussing this with @ulfjack 
Ulf,  is there a bug for this in bazel?

**Comment by tensorflowbutler** [comment] 2018-08-24 21:44
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:38
Nagging Assignees @case540, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:45
Nagging Assignees @case540, @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:44
Nagging Assignees @case540, @gunan: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:47
Nagging Assignees @case540, @gunan: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-10-23 16:53
This is still a bazel bug, we still have not received confirmation that it is fixed.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:08
Nagging Assignees @case540, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:43
Nagging Assignees @case540, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2019-05-10 23:41
Looks like now python2 is an actual dependency of bazel apt package.
I am quite surprised about that.
@meteorcloudy do you know why python2 is now a bazel dependency?

**Comment by meteorcloudy** [comment] 2019-05-13 07:07
https://github.com/bazelbuild/bazel/blob/5e34534fe6108277843632e5fd206052ca296ce3/scripts/packages/debian/control#L13
@ulfjack Do we still need `python` as a dependency for Bazel's apt package?

**Comment by ulfjack** [comment] 2019-05-13 09:23
We're still shipping a bunch of python files as part of the Bazel binary. There are some Android tools as well as a couple of packaging build_defs under tools/. They should all be unbundled, but I'm not sure what the timeline is:
```
$ unzip -l $(which bazel) | grep ".py"
...
     3510  1980-01-01 00:00   embedded_tools/tools/android/aar_embedded_jars_extractor.py
     3135  1980-01-01 00:00   embedded_tools/tools/android/aar_native_libs_zip_creator.py
     5244  1980-01-01 00:00   embedded_tools/tools/android/aar_resources_extractor.py
     3882  1980-01-01 00:00   embedded_tools/tools/android/build_incremental_dexmanifest.py
     3416  1980-01-01 00:00   embedded_tools/tools/android/build_split_manifest.py
    30331  1980-01-01 00:00   embedded_tools/tools/android/incremental_install.py
     5031  1980-01-01 00:00   embedded_tools/tools/android/instrumentation_test_check.py
     6254  1980-01-01 00:00   embedded_tools/tools/android/junction.py
     3094  1980-01-01 00:00   embedded_tools/tools/android/resource_extractor.py
     1825  1980-01-01 00:00   embedded_tools/tools/android/strip_resources.py
     5725  1980-01-01 00:00   embedded_tools/tools/android/stubify_manifest.py
     1225  1980-01-01 00:00   embedded_tools/tools/build_defs/hash/sha256.py
    15830  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/archive.py
    10986  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/archive_test.py
    12708  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/build_tar.py
    11617  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/make_deb.py
     8457  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/make_rpm.py
     4632  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/make_rpm_test.py
     2548  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/path_test.py
      748  1980-01-01 00:00   embedded_tools/tools/build_defs/pkg/testenv.py
     4784  1980-01-01 00:00   embedded_tools/tools/j2objc/j2objc_header_map.py
    19390  1980-01-01 00:00   embedded_tools/tools/j2objc/j2objc_wrapper.py
     3055  1980-01-01 00:00   embedded_tools/tools/jdk/proguard_whitelister.py
     2725  1980-01-01 00:00   embedded_tools/tools/jdk/proguard_whitelister_test.py
    20019  1980-01-01 00:00   embedded_tools/tools/objc/j2objc_dead_code_pruner.py
     2056  1980-01-01 00:00   embedded_tools/tools/objc/make_hashed_objlist.py
      820  1980-01-01 00:00   embedded_tools/tools/objc/protobuf_compiler.py
       20  1980-01-01 00:00   embedded_tools/tools/python/2to3.sh
     2456  1980-01-01 00:00   embedded_tools/tools/python/BUILD
     4060  1980-01-01 00:00   embedded_tools/tools/python/python_version.bzl
      107  1980-01-01 00:00   embedded_tools/tools/python/runfiles/BUILD
     9560  1980-01-01 00:00   embedded_tools/tools/python/runfiles/runfiles.py
    11050  1980-01-01 00:00   embedded_tools/tools/python/srcs_version.bzl
     3139  1980-01-01 00:00   embedded_tools/tools/python/toolchain.bzl
```

**Comment by saippuakauppias** [comment] 2019-05-14 07:31
Solution: https://github.com/tensorflow/tensorflow/issues/10289#issuecomment-492102920

**Comment by ymodak** [comment] 2019-08-06 22:28
Closing due to staleness. Please check with the latest version of TensorFlow. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-08-06 22:28 UTC

**Comment by alfosucan** [comment] 2019-10-13 10:25
Issie seems to persist. Symlinking **/usr/bin/python** to **/usr/bin/python3** seems to work.
`link /usr/bin/python3 /usr/bin/python`

Hope it helps!

**Comment by pratik-segmind** [comment] 2020-11-16 17:16
overcame this by `sudo ln -sf /usr/bin/python3 /usr/bin/python`
