### ISSUE TITLE
'Tensor' object has no attribute 'initializer' after import from meta graph

### ISSUE THREAD

**Issue by austinzh** [tensorflow/tensorflow#9747] opened 2017-05-08 06:10 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution**: Darwin Austins-MBP 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Mac OS X 10.12.4
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:v1.1.0-rc0-61-g1ec6ed5 1.1.0
- **Bazel version (if compiling from source)**:0.4.5
- **CUDA/cuDNN version**:None
- **GPU model and memory**:None
- **Exact command to reproduce**: Ref to Codes

### tensorflow import 
    tf.VERSION = 1.1.0
    tf.GIT_VERSION = v1.1.0-rc0-61-g1ec6ed5
    tf.COMPILER_VERSION = v1.1.0-rc0-61-g1ec6ed5
    Sanity check: array([1], dtype=int32)

### Describe the problem
After export and import a meta graph with uninitialized local variables,
You can not inittialize them with sess.run(tf. local_variables_initializer()), cause
TF do not register variable's proto function with key 'LOCAL_VARIABLES' and when 
export meta graph to protobuf, source code can not find to_proto function from repository.

### Source code / logs
```python
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
    x = tf.Variable(1, collections=[tf.GraphKeys.LOCAL_VARIABLES])
    y = tf.Variable(1)
    z = x + y
origin_meta_graph = tf.train.export_meta_graph(graph=graph)
new_graph = tf.Graph()
with new_graph.as_default():
    tf.train.import_meta_graph(origin_meta_graph)
    init = tf.local_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
```

```bash
Traceback (most recent call last):
  File "/Users/austin/workspace/aip/3rd/tensorflow/tensorflow/test.py", line 12, in <module>
    init = tf.local_variables_initializer()
  File "/Users/austin/workspace/aip/3rd/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1184, in local_variables_initializer
    return variables_initializer(local_variables())
  File "/Users/austin/workspace/aip/3rd/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1149, in variables_initializer
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
  File "/Users/austin/workspace/aip/3rd/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1149, in <listcomp>
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
AttributeError: 'Tensor' object has no attribute 'initializer'
```

```python
import tensorflow as tf

graph = tf.Graph()
with graph.as_default():
    x = tf.Variable(1, collections=[tf.GraphKeys.LOCAL_VARIABLES])
    y = tf.Variable(1)
    z = x + y
origin_meta_graph = tf.train.export_meta_graph(graph=graph)
new_graph = tf.Graph()
with new_graph.as_default():
    tf.train.import_meta_graph(origin_meta_graph)
print(graph.get_collection(tf.GraphKeys.LOCAL_VARIABLES))
print(new_graph.get_collection(tf.GraphKeys.LOCAL_VARIABLES))
```

```bash
[<tf.Variable 'Variable:0' shape=() dtype=int32_ref>]
[<tf.Tensor 'Variable:0' shape=() dtype=int32_ref>]
```
As it show above, in origin graph local_variable collection is a list of **tf.Variable**
but in the new graph, is a list of **tf.Tensor**

### Work around
Add following registration in your model core
OR Ref to this [PR](https://github.com/tensorflow/tensorflow/pull/9674)

```python
from tensorflow.core.framework import variable_pb2
from tensorflow.python.framework import ops
from tensorflow.python.ops import variables
from tensorflow.python.framework.ops import register_proto_function

register_proto_function(
    ops.GraphKeys.LOCAL_VARIABLES,
    proto_type=variable_pb2.VariableDef,
    to_proto=variables.Variable.to_proto,
    from_proto=variables.Variable.from_proto)
```

**Comment by girving** [comment] 2017-05-09 16:13
`tf.local_varliabe_initializer()` might not be the right spelling.

**Comment by girving** [comment] 2017-05-09 16:15
@josh11b Looks like metagraph import isn't creating Variable objects.  Any ideas why?

**Comment by bsautermeister** [comment] 2017-05-18 14:13
I'm just facing the same problem. To be more precise, I'm using [tf.metrics.accuracy()](https://www.tensorflow.org/api_docs/python/tf/metrics/accuracy) in my training script, which uses local count variables internally.

```
_, accuracy_ = tf.metrics.accuracy(labels=y_ph, predictions=tf.argmax(model_y, axis=1))
tf.add_to_collection('accuracy', accuracy_)
```

After saving and restoring the graph using [tf.train.import_meta_graph()](https://www.tensorflow.org/api_docs/python/tf/train/import_meta_graph), I'n not able so reuse the accuracy metric, because the required call to [tf.initialize_local_variables()](https://www.tensorflow.org/versions/master/api_docs/python/tf/initialize_local_variables) fails as desribed  @austinzh.

```
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('checkpoint/model.ckpt.meta')
    new_saver.restore(sess, 'checkpoint/model.ckpt')
    # ...
    accuracy_ = tf.get_collection('accuracy')[0]
    sess.run(tf.local_variables_initializer())
    accuracy = sess.run(accuracy_, feed_dict={...})
```


is there already any progress on this?

**Comment by davsuacar** [comment] 2017-05-19 07:40
Same case for me. I'm using tf.metrics.accuracy() in my training process.
`self.accuracy_metrics, self.update_accuracy_metrics = tf.metrics.accuracy(self.label,
                                                                                  self.one_hot,
                                                                                  name='accuracy')`

When I try to restore the saved model:
`new_saver = tf.train.import_meta_graph(save_path + '.meta')
    new_saver.restore(sess, save_path)
    graph = tf.get_default_graph()`
 and use the function accuracy again:
`accuracy_update = graph.get_operation_by_name('accuracy/update_op').outputs[0]

input_data, output_data = validator.read_batch(config['READ_BUFFER_SIZE'], sys.stdin,
                                                       config['SEPARATOR'], config['OUTPUT_SIZE'])
input_data = input_data.reshape(input_data.shape[0], config['SEQ_LENGTH'], config['N_FEATURES'])
output_data = output_data.reshape(output_data.shape[0], config['OUTPUT_SIZE'])

accuracy = sess.run(accuracy_update, {"data:0": input_data, "target:0": output_data,
                                                         "keep_prob:0": config['KEEP_PROB']})
print(accuracy)
`
it fails:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value accuracy/count_1
	 [[Node: accuracy/AssignAdd_3 = AssignAdd[T=DT_FLOAT, _class=["loc:@accuracy/count_1"], use_locking=false, _device="/job:localhost/replica:0/task:0/cpu:0"](accuracy/count_1, accuracy/ToFloat_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 46, in main
    {"data:0":input_data.reshape(200, 10, 16), "label_aux:0": output_data, "keep_prob:0": config['KEEP_PROB']})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value accuracy/count_1
	 [[Node: accuracy/AssignAdd_3 = AssignAdd[T=DT_FLOAT, _class=["loc:@accuracy/count_1"], use_locking=false, _device="/job:localhost/replica:0/task:0/cpu:0"](accuracy/count_1, accuracy/ToFloat_2)]]

Caused by op 'accuracy/AssignAdd_3', defined at:
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 43, in main
    accuracy_metrics, update_accuracy_metrics = tf.metrics.accuracy(label_operation, one_hot)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/metrics_impl.py", line 332, in accuracy
    updates_collections, name or 'accuracy')
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/metrics_impl.py", line 267, in mean
    update_count_op = state_ops.assign_add(count, num_values)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 75, in assign_add
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value accuracy/count_1
	 [[Node: accuracy/AssignAdd_3 = AssignAdd[T=DT_FLOAT, _class=["loc:@accuracy/count_1"], use_locking=false, _device="/job:localhost/replica:0/task:0/cpu:0"](accuracy/count_1, accuracy/ToFloat_2)]]

**Comment by josh11b** [comment] 2017-05-19 16:12
@sherrym Any ideas?

**Comment by AlbertXiebnu** [comment] 2017-06-23 07:13
@bsautermeister any solution for this problem? I face the same problem as yours.

**Comment by bsautermeister** [comment] 2017-06-23 08:01
@AlbertXiebnu Unfortunately no. But I have not check if this has been fixed in TF 1.2. I try to check that in the next days...

**Comment by AlbertXiebnu** [comment] 2017-06-23 09:30
@bsautermeister I have tried in TF1.2, seems that still not work.

**Comment by alexwal** [comment] 2017-06-25 23:05
Same issue here; for me, it seems to be related to https://github.com/tensorflow/tensorflow/issues/1045. When I set num_epochs to a value other than None in the file where I save the model, I will get the "'Tensor' object has no attribute 'initializer'" error in the file where I restore the model.

**Comment by gauravsindhwani** [comment] 2017-07-24 10:50
Same issue here, while restoring a graph and using string input producer to evaluate model , first I get 
"Attempting to use uninitialized value input_producer/limit_epochs/epochs 	 [[Node: input_producer/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/limit_epochs/epochs)]]"

If to fix above issue I run tf.local_variable_intializer() then I get  "'Tensor' object has no attribute 'initializer' error on (TF 1.2, Python 3.6.1+)

**Comment by gauravsindhwani** [comment] 2017-07-25 05:49
I did manage to find a work around, upon restoring i removed queue_runners and local_variables from restored graph and it worked 
get_default_graph().clear_collection("queue_runners")
      get_default_graph().clear_collection("local_variables")

**Comment by jiqiujia** [comment] 2017-08-01 10:01
@gauravsindhwani , can you still run the code successfully after you remove these two collections since they are actually part of the graph. I try your way but find the program is stuck after restoring.

**Comment by guoyinwang** [comment] 2017-09-18 21:02
@gauravsindhwani, this approach seams working ok for me. I use streaming_accuracy and it seems create many local variable "accuracy", which are no longer used. So remove local_variables seems to be a good way to hack it.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:27
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:06
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:12
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tatatodd** [comment] 2018-01-25 01:26
@suharshs has been working on MetaGraphDef related stuff, and might have some ideas.

**Comment by tensorflowbutler** [comment] 2018-02-08 19:30
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:04
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by yanboliang** [comment] 2018-03-05 22:17
It works well on TF 1.4.1, it seems this issue have been fixed by https://github.com/tensorflow/tensorflow/commit/2d1823f7be0d65d4ee28b7c6ea2acaac01f1db61 . Thanks.

**Comment by tensorflowbutler** [comment] 2018-03-20 10:21
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Closed** 2018-03-27 23:02 UTC
Labels: stat:awaiting tensorflower, type:bug/performance
