### ISSUE TITLE
TFLite conversion coredumps

### ISSUE THREAD

**Issue by vk1z** [tensorflow/tensorflow#38073] opened 2020-03-31 14:11 UTC
**System information** : Ubuntu18.04, CUDA 10
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No. Problem exists even when using tflite_convert OR writing custom code as described in [documentation](https://www.tensorflow.org/lite/performance/post_training_quantization)
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): Binary/Tensorflow: 2.0.1
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: Cuda 10/GTX1070Ti, 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

Describe the current behavior
Tensorflow lite conversion dumps core both for 8 bit and 16 bit quantizations and no tflite file is generated when using the from_saved_model converter. The model shape (as can be seen from saved_model_cli) is below. The model is a SSD-mobilenetv2 transfer learned by using tensorflow detection API on Tensorflow 1.14
==

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, 300, 300, 3)
        name: image_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['detection_boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 30, 4)
        name: detection_boxes:0
    outputs['detection_classes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 30)
        name: detection_classes:0
    outputs['detection_multiclass_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 30, 5)
        name: detection_multiclass_scores:0
    outputs['detection_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 30)
        name: detection_scores:0
    outputs['num_detections'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: num_detections:0
    outputs['raw_detection_boxes'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 4)
        name: raw_detection_boxes:0
    outputs['raw_detection_scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 5)
        name: raw_detection_scores:0
  Method name is: tensorflow/serving/predict
==
**Describe the expected behavior**

I expect the tflite file to be generated by following the public documentation on Tensorflow site and don't expect core dumps.
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
2020-03-31 06:46:09.156599: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-03-31 06:46:09.156683: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-31 06:46:09.157414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:07:00.0
2020-03-31 06:46:09.157448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-31 06:46:09.157459: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-31 06:46:09.157469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-31 06:46:09.157478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-31 06:46:09.157487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-31 06:46:09.157496: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-31 06:46:09.157505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-31 06:46:09.157937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-31 06:46:09.157973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-31 06:46:09.157980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-03-31 06:46:09.157986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-03-31 06:46:09.158409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6624 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:07:00.0, compute capability: 6.1)
2020-03-31 06:46:09.471641: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2020-03-31 06:46:09.471673: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 1765 nodes (-1299), 2239 edges (-1452), time = 191.291ms.
2020-03-31 06:46:09.471681: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 1765 nodes (0), 2239 edges (0), time = 51.045ms.
Traceback (most recent call last):
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 502, in run_main
    _convert_tf2_model(tflite_flags)
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 221, in _convert_tf2_model
    tflite_model = converter.convert()
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 446, in convert
    **converter_kwargs)
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-03-31 06:46:11.117660: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.117740: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128695: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128746: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128807: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128829: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128838: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128846: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128887: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.128899: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128907: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.128914: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128921: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128930: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.128937: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128945: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128951: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128956: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.128965: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128972: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.128978: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.128993: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.129001: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.129007: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.129011: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.129022: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-03-31 06:46:11.129035: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.129045: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.129051: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.129066: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.129075: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.129086: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.129097: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.129114: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.129123: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.130076: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130091: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130100: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130107: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130115: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130122: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130130: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130136: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130144: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130150: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130158: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130165: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130173: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130179: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130186: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130196: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130202: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130208: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130214: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130220: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-03-31 06:46:11.130226: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130234: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130240: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130245: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.130253: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130259: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130265: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130271: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130276: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.130283: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130291: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130297: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130313: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130319: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130323: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130328: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130332: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130336: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.130344: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130350: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130354: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.130363: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130370: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130376: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130380: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130387: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130395: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130401: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130406: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130412: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-03-31 06:46:11.130418: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130424: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130435: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130442: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.130455: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-03-31 06:46:11.130474: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.130482: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.130490: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.130499: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.130506: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-03-31 06:46:11.130514: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.130521: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.130940: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.130952: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.130960: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.130967: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.130974: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.130981: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.130988: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-03-31 06:46:11.130993: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-03-31 06:46:11.131050: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-03-31 06:46:11.131059: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.131068: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.131078: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.131091: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.131099: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-03-31 06:46:11.131105: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-03-31 06:46:11.131181: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-03-31 06:46:11.131191: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-03-31 06:46:11.131199: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-03-31 06:46:11.131207: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-03-31 06:46:11.131285: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-31 06:46:11.131358: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-31 06:46:11.131403: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.131510: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.131520: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.131531: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.131538: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-03-31 06:46:11.157600: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1120 operators, 2034 arrays (0 quantized)
2020-03-31 06:46:11.214243: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 1113 operators, 2018 arrays (0 quantized)
2020-03-31 06:46:11.277956: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1113 operators, 2018 arrays (0 quantized)
2020-03-31 06:46:11.340779: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 610 operators, 1209 arrays (0 quantized)
2020-03-31 06:46:11.358315: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 610 operators, 1209 arrays (0 quantized)
2020-03-31 06:46:11.372161: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 610 operators, 1209 arrays (0 quantized)
2020-03-31 06:46:11.401094: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 1080704 bytes, theoretical optimal value: 1080704 bytes.
2020-03-31 06:46:11.404128: F tensorflow/lite/toco/tooling_util.cc:2275] Check failed: array.data_type == array.final_data_type Array "image_tensor" has mis-matching actual and final data types (data_type=uint8, final_data_type=float).
Fatal Python error: Aborted

Current thread 0x00007fbd58971740 (most recent call first):
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/absl/app.py", line 299 in run
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/home/vk1z/.virtualenvs/tensorflow-lite-convert/bin/toco_from_protos", line 8 in <module>
Aborted (core dumped)

==
Yes, I am aware of [35376](https://github.com/tensorflow/tensorflow/issues/35736) but I don't think that a coredump is an expected output of any conversion process.

**Comment by vk1z** [comment] 2020-03-31 14:11
Sorry about the unexpected capitalization above.

**Comment by vk1z** [comment] 2020-03-31 14:35
Follow up; The exact same behavior is observed when trying to convert the SSD Mobilenet model from the tensorflow detection Zoo - specifically: ssd_mobilenet_v2_coco_2018_03_29. 

The model there was also converted to have input shape (None, 300, 300, 3) (since tflite conversions from (None, None, None, 3) fail). Consequently I believe that should be an easy bug to repro and hopefully fix since this makes the export of tensorflow lite models unusable on Tensorflow 2.0.1.

**Comment by ravikyram** [comment] 2020-04-01 07:00
@vk1z 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by vk1z** [comment] 2020-04-01 10:22
Will do so today.

**Comment by ravikyram** [comment] 2020-04-17 11:56
@vk1z 

Any update on this issue please. Thanks!

**Comment by vk1z** [comment] 2020-04-17 12:08
Will do on the weeend. Apologies.

**Comment by ravikyram** [comment] 2020-04-24 07:20
@vk1z 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-04-30 07:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-30 07:50 UTC
Labels: TF 2.0, comp:lite, stat:awaiting response, type:bug
