### ISSUE TITLE
Keras fit with generators not executing in the main thread when setting workers=0

### ISSUE THREAD

**Issue by dfalbel** [tensorflow/tensorflow#47321] opened 2021-02-22 19:04 UTC
Can be reproduced on colab with TensorFlow (`v2.4.1-0-g85c8b2a817f 2.4.1`)

**Describe the current behavior**

Generator code is executed in other threads when using `model.fit`.

From the docs, it looks like that setting workers=0 would execute the generator code in the main thread.

> workers Integer. Used for generator or keras.utils.Sequence input only. Maximum number of processes to spin up when using process-based threading. If unspecified, workers will default to 1. **If 0, will execute the generator on the main thread**.

This doesn't seem to work though as only the first iterations seems to be executed in the main thread.

For example:

```
import tensorflow as tf
import threading
model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
model.compile(loss = "mse", optimizer = "adam")

def gen ():
  for i in range(100):
    print(threading.current_thread())
    yield (tf.random.normal(shape=(100,1)), tf.random.normal(shape = (100,)))

model.fit(gen(), epochs = 1, workers = 0, verbose = 0, steps_per_epoch = 3, max_queue_size=0)
```

I get:

```
<_MainThread(MainThread, started 140516450817920)>
<_DummyThread(Dummy-4, started daemon 140514717599488)>
<_DummyThread(Dummy-5, started daemon 140514709206784)>
<tensorflow.python.keras.callbacks.History at 0x7fcc1d7223c8>
```

**Describe the expected behavior**

I'd expect that all calls from the generator to be executed in the main thread. This is problematic because in my use case the generator is not thread safe and crashes the program when executed from other threads. 

Note: I have opened a [SO question](https://stackoverflow.com/questions/66320198/keras-fit-with-generator-function-always-execute-in-the-main-thread) but I feel this behavior should be treated as a bug.

**Comment by Saduf2019** [comment] 2021-02-24 11:39
i am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/821b3a7d1b9bfe7978d4f48410592fbf/untitled.ipynb).

**Comment by fchollet** [comment] 2021-02-26 01:48
Hi,

Thanks for reporting this issue. The documentation appears to be outdated: the generator would only execute on the main thread in graph-mode TensorFlow (v1.x). We'll update the documentation,

In your case, there's a simple trick you can use to get the old behavior without reverting to TF 1.x: you can call `tf.compat.v1.disable_eager_execution()` at the start of your program. This will use the old behavior.

The root cause of the issue is that in 2.x Keras converts your generator to a `tf.data.Dataset` before training (this enables Keras to use a unified training path for all types of inputs). Converting a generator to a dataset results in the use of threading, as you can see in the following example:

```python
def gen ():
  for i in range(100):
    print(threading.current_thread())
    yield (tf.random.normal(shape=(100, 1)), tf.random.normal(shape=(100, 1)))

ds = tf.data.Dataset.from_generator(
    gen,
    output_signature=(tf.TensorSpec(shape=(100, 1), dtype=tf.float32), tf.TensorSpec(shape=(100, 1), dtype=tf.float32))).batch(32)
model.fit(ds, verbose=0, steps_per_epoch=3)
```

Which will print:

```
<_DummyThread(Dummy-5, started daemon 140597821310720)>
...
```

This problem cannot be fixed in the Keras codebase without creating an exception to our unified training code path (i.e. *not* converting generators to Datasets), which would be highly impractical.

In the future, two things you could do if you don't want threads involved in your generator training, would be 1. write your own training loop based on `model.train_on_batch()` (where you iterate on your generator yourself), or 2. write your own low-level training loop [as per this guide](https://keras.io/guides/writing_a_training_loop_from_scratch/).

**Closed by fchollet** 2021-02-26 01:48 UTC
Labels: TF 2.4, comp:keras, stat:awaiting tensorflower, type:bug

**Comment by dfalbel** [comment] 2021-02-26 17:10
Thanks very much for your answer! I'll try the eager execution trick.
I wonder if you think we could have a codepath in tf.data that allows executing the generator in a thread safe manner. 

I would write a custom training loop if this was for an applied project, but in the **Keras for R** project we would need to support all callbacks, and etc for the generator codepath and it's probably too much work.

**Comment by fchollet** [comment] 2021-02-26 18:07
> I wonder if you think we could have a codepath in tf.data that allows executing the generator in a thread safe manner.

I think it is a reasonable ask. It could be an option in `tf.data.Dataset.from_generator`. @jsimsa would be the best contact point. Consider creating a new issue (referencing this one) to track it.

**Comment by jsimsa** [comment] 2021-02-26 18:19
It is not clear how feasible this is for the following reasons:

1) `tf.data.Dataset.from_generator` uses the `py_func` TensorFlow op for invoking the user-defined function because tf.data implementation needs to transfer execution between C++ and Python and `py_func` provides a robust mechanism for this. `py_func` implementation uses a separate thread to run the user-provided function.

2) tf.data input pipeline can contain downstream asynchrony, which means that the thread executing the `from_generator` C++ kernel can be different from the main thread irrespective of how is the `from_generator` C++ kernel is implemented (and what options it is executed with).

I would be happy to review external proposals / PRs for how to achieve it, but it is unlikely that the tf.data team will develop this functionality themselves. From my perspective this is a niche scenario, which would require non-trivial engineering effort to address.

**Comment by dfalbel** [comment] 2021-02-26 20:31
Thanks very much @jsimsa ! This makes sense to me! I don't think it's worth the effort. I think there might still exist other workarounds in the R side like using an event loop and scheduling the generator call to the main thread.
