### ISSUE TITLE
How to force TF Eigen to use openBLAS library for GEMM calls?

### ISSUE THREAD

**Issue by avinashcpandey** [tensorflow/tensorflow#37805] opened 2020-03-22 16:54 UTC
Hi,
I am trying to link OpenBLAS to Tensorflow Eigen, Basically I want to override Eigen gemm call to OpenBLAS gemm call using below command which is not working.

Command to building TF.
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-DEIGEN_USE_BLAS --linkopt=-L<path to BLAS> --linkopt=-lopenblas //tensorflow/tools/pip_package:build_pip_package   

I did't find anything with TF documentation. Is there any way to achieve the same?

**Comment by ravikyram** [comment] 2020-03-23 06:18
Please, refer #8350 and see if it helps you.This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by tensorflowbutler** [comment] 2020-04-07 01:14
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-04-17 11:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-17 11:49 UTC
Labels: stat:awaiting response, type:others, type:support
