### ISSUE TITLE
Tensorflow Keras: all Keras optimizers throw an error when training in eager mode

### ISSUE THREAD

**Issue by mjarosie** [tensorflow/tensorflow#29556] opened 2019-06-08 14:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.8

**Describe the current behavior**

When creating a model with SGD optimizer in eager mode and setting its `run_eagerly` attribute to true when I fit the model using some tf.Dataset (created using [tf.data.experimental.CsvDataset](https://www.tensorflow.org/api_docs/python/tf/contrib/data/CsvDataset) if that matters) as an input, I get the following error:

```
AttributeError: 'SGD' object has no attribute 'apply_gradients'
```

**Describe the expected behavior**

I'd like to set Keras model's run_eagerly property to true so that I'd be able to step into custom-defined loss functions when being in eager mode when using SGD as an optimiser.

**Code to reproduce the issue**

```
import tensorflow as tf

sgd = tf.keras.optimizers.SGD(lr=0.01, decay=0.0025, momentum=0.5)

inputs = tf.keras.Input(shape=(123,))

# First layer
x = tf.keras.layers.Dense(50, kernel_regularizer=tf.keras.regularizers.l2(0.01))(inputs)
x = tf.keras.layers.LeakyReLU(alpha=0.1)(x)

# Second layer
x = tf.keras.layers.Dense(20, kernel_regularizer=tf.keras.regularizers.l2(0.01))(x)
x = tf.keras.layers.LeakyReLU(alpha=0.1)(x)

# Output
outputs = tf.keras.layers.Dense(
	51,
	kernel_regularizer=tf.keras.regularizers.l2(0.01),
	activation='sigmoid'
)(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs, name='MLP')

model.compile(
	optimizer=sgd,
	loss=weighted_cross_entropy_loss, # Some custom-defined loss function of mine
	metrics=[shared_metrics.balanced_accuracy_per_class_avg] # Some custom-defined metric function of mine
)

# Define train_dataset variable which holds tf.Dataset
# train_dataset = ...

model.fit(train_dataset, validation_data=validation_dataset, epochs=400, steps_per_epoch=1000, validation_steps=1000)
```

**Other info / logs**

Full traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/QMUL/user-state-recognition/src/train_MLP.py", line 331, in <module>
    main()
  File "C:/QMUL/user-state-recognition/src/train_MLP.py", line 171, in main
    validation_steps=steps_per_epoch_val, callbacks=[tb_callback], verbose=1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 851, in fit
    initial_epoch=initial_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 191, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1179, in train_on_batch
    self, x, y, sample_weights=sample_weights)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_eager.py", line 260, in train_on_batch
    model, inputs, targets, sample_weights=sample_weights, training=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_eager.py", line 225, in _process_single_batch
    model.optimizer.apply_gradients(zip(grads,
AttributeError: 'SGD' object has no attribute 'apply_gradients'
```

Regarding `run_eagerly` attribute: I need to step into my custom loss and metric functions. The code takes the decision in [Model.train_on_batch() function](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/engine/training.py#L1123) in [this](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/engine/training.py#L1177) line. If run_eagerly parameter will not be set explicitly to `True` before calling model.fit function, the modell will take [this](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/engine/training.py#L1180) path instead, which will make it impossible to step into custom loss function nor custom metric function. When `run_eagerly` is set to true the code will eventually get to [this](https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/engine/training_eager.py#L225) line and that's where the code fails, as Keras's optimizer interface doesn't have `apply_gradients` method defined.

**Comment by mjarosie** [comment] 2019-06-08 19:02
As it turns out the error appears for any Keras optimiser taken from here: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers I'm going to change the title of the issue.

**Comment by mtn** [comment] 2019-06-10 23:22
I'm also pretty sure the docs are wrong. For now, I'm just using an optimizer from `tf.train`.

**Comment by achandraa** [comment] 2019-06-11 09:23
@mjarosie : Thank you for reaching out  to us. Will it be possible to provide the full minimal code snippet to reproduce the error caught by you. It will help us to proceed faster. Thanks!

**Comment by achandraa** [comment] 2019-06-17 06:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-06-17 06:39 UTC
Labels: TF 1.13, comp:keras, stat:awaiting response, type:support

**Comment by mjarosie** [comment] 2019-06-17 22:52
Hi @achandraa I've modified the original code, it reproduces the exact issue now.

**Comment by Abhinavfreecodecamp** [comment] 2020-09-15 07:41
Hi, too face the same issue when running under eager execution. please provide a solution for this @achandraa
