### ISSUE TITLE
Saved model by TensorForestEstimator can not be freezed

### ISSUE THREAD

**Issue by ManSoSec** [tensorflow/tensorflow#5938] opened 2016-11-29 15:40 UTC
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I asked a question in stackoverflow, but I guess it is a bug or inconsistency in tensorflow.

http://stackoverflow.com/questions/40849477/error-in-saving-and-using-model-of-tensorforestestimator-for-android

### Environment info
Operating System:

Mac OSX 10.10.2
Python 2.7.12

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0rc0-py2-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. Version: 0.12.0-rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

import tensorflow as tf
import numpy as np
from freeze_graph import freeze_graph
import os
from tensorflow.contrib.learn.python.learn.estimators.random_forest import TensorForestEstimator

Creating the model and saving:
=========================
hparams = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
        num_trees=3, max_nodes=1000, num_classes=3, num_features=4)
classifier = TensorForestEstimator(hparams, model_dir='test/')
iris = tf.contrib.learn.datasets.load_iris()
data = iris.data.astype(np.float32)
target = iris.target.astype(np.float32)
classifier.fit(x=data, y=target, steps=100)

Freezing the model:
=========================
model_name = 'test/'
checkpoint_state_name = "checkpoint"
input_graph_name = "graph.pbtxt"
output_graph_name = "newgraph.pb"
input_graph_path = os.path.join(model_name, input_graph_name)
input_saver_def_path = model_name
input_binary = False
input_checkpoint_path = os.path.join(model_name, checkpoint_state_name)
output_node_names = "sample"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_graph_path = os.path.join(model_name, output_graph_name)
clear_devices = True
freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, input_checkpoint_path,
                          output_node_names, restore_op_name,
                          filename_tensor_name, output_graph_path,
                          clear_devices, "")

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

The code can create and save the model perfectly (I can open the graph by tensorboard), but I get the following error for freezing the graph:

Traceback (most recent call last):
  File "/XXXXX/model/test.py", line 41, in <module>
    clear_devices, "")
  File "/XXXXX/model/freeze_graph.py", line 99, in freeze_graph
    _ = tf.import_graph_def(input_graph_def, name="")
  File "/XXXXX/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'TreePredictions'

When I am building the model, I get the following warning:

Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************

**Comment by poxvoculi** [comment] 2016-11-30 00:37
I tried reproducing your problem, but there seems to be something wrong in your description.  The input_saver_def_path has value 'test/' which is a directory, but I think maybe it should be the pathname of a  Saver proto def?

**Comment by poxvoculi** [comment] 2016-11-30 00:38
Adding @petewarden because you're building on Mac.

**Comment by ManSoSec** [comment] 2016-11-30 09:05
Thanks, @poxvoculi! 
'test/' is a local directory that TensorForestEstimator saves the model there.

**Comment by ManSoSec** [comment] 2016-12-05 10:12
Can I kindly ask if there is any update on this issue ? Thanks a lot!

**Comment by gilberthendry** [comment] 2016-12-06 15:35
I also tried reproducing the problem but ran into the same issue as @poxvoculi.  Supplying your checkpoint directory for input_saver is not valid.   Regardless, I can't get past tf.import_graph_def because it seems that internally it uses a V2 checkpoint, but tf.learn still uses a V1 checkpoint (which is hard coded into the underlying graph_actions.py).

**Comment by qwertmax** [comment] 2017-03-06 13:00
how can I fix this issue ? does anyone have idea?

**Comment by gilberthendry** [comment] 2017-03-06 13:45
Is it still around in TF 1.0?  The first problem was a checkpoint version mismatch, which should be gone in 1.0.

**Comment by qwertmax** [comment] 2017-03-06 13:56
@gilberthendry  nope, the issue still present in 1.0

**Comment by petewarden** [comment] 2017-07-12 23:06
The underlying error seems to indicate that the "TreePredictions" op isn't registered when the graphdef is being imported before the graph is frozen. This is surprising, since it's clearly being used successfully earlier in the script, so I'm wondering if it's a bug with how the op_dict in Python is populated, maybe related to the fact that the Random Forest ops are in contrib?

**Comment by gilberthendry** [comment] 2017-07-13 00:11
It's likely due to being in contrib.  We're looking to move it to core, will hopefully happen this quarter.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:40
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:10
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:22
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2018-01-29 22:38
Closing this bug as obsolete, please re-open if you're still running into this.

**Closed by petewarden** 2018-01-29 22:38 UTC
Labels: stat:awaiting tensorflower
