### ISSUE TITLE
Fit under TPU strategy fails on cardinality

### ISSUE THREAD

**Issue by jonyvp** [tensorflow/tensorflow#37504] opened 2020-03-11 09:54 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ran on colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: /
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0 (Colab)
- Python version: - 3.6.9
version (if compiling from source): /
- GCC/Compiler version (if compiling from
source): /
- CUDA/cuDNN version: - GPU model and memory: Using the TPU runtime

When running the `fit` function on a model after compiling the model with the TPUStrategy as in [this post on the colab github](https://github.com/googlecolab/colabtools/issues/1056) the cardinality is implicitely calculated.
A TFRecordDataset is used as Dataset for the fit function. 
The error below is raised:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-db3ea26a4a48> in <module>()
----> 1 mh.start_training()

8 frames
/content/modelling/NN/ModelHandler.py in start_training(self)
     73                 steps_per_epoch=self.dataloaders[0].amount_of_batches,
     74                 validation_steps=self.dataloaders[1].amount_of_batches,
---> 75                 verbose=1
     76                 )
     77 

/content/modelling/NN/Model.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    312                              validation_steps=validation_steps, validation_freq=validation_freq,
    313                              max_queue_size=max_queue_size, workers=workers,
--> 314                              use_multiprocessing=use_multiprocessing, **kwargs)
    315         return out
    316 

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    258           steps_per_epoch,
    259           steps_name='steps_per_epoch',
--> 260           epochs=0)
    261 
    262       steps_per_epoch = (

/tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_utils.py in infer_steps_for_dataset(model, dataset, steps, epochs, steps_name)
   1747     return None
   1748 
-> 1749   size = K.get_value(cardinality.cardinality(dataset))
   1750   if size == cardinality.INFINITE and steps is None:
   1751     raise ValueError('When passing an infinitely repeating dataset, you '

/tensorflow-2.1.0/python3.6/tensorflow_core/python/data/experimental/ops/cardinality.py in cardinality(dataset)
     49   """
     50 
---> 51   return ged_ops.dataset_cardinality(dataset._variant_tensor)  # pylint: disable=protected-access

/tensorflow-2.1.0/python3.6/tensorflow_core/python/ops/gen_experimental_dataset_ops.py in dataset_cardinality(input_dataset, name)
    663         pass  # Add nodes to the TensorFlow graph.
    664     except _core._NotOkStatusException as e:
--> 665       _ops.raise_from_not_ok_status(e, name)
    666   # Add nodes to the TensorFlow graph.
    667   _, _, _op, _outputs = _op_def_library._apply_op_helper(

/tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6604   message = e.message + (" name: " + name if name is not None else "")
   6605   # pylint: disable=protected-access
-> 6606   six.raise_from(core._status_to_exception(e.code, message), None)
   6607   # pylint: enable=protected-access
   6608 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Unable to parse tensor proto [Op:DatasetCardinality]
```

When calculating the cardinality without calling the TPUStrategy context as shown below, a value of `-2` is yielded:
```
import tensorflow.keras.backend as K
K.get_value(tf.data.experimental.cardinality(ds))
```

**Comment by ravikyram** [comment] 2020-03-12 06:13
@jonyvp 

Can you please help us with  colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-27 01:18
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-27 07:40
@jonyvp 

Any update on this issue please. Thanks!

**Comment by tensorflowbutler** [comment] 2020-04-12 00:40
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-04-13 04:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-13 04:54 UTC
Labels: TF 2.1, comp:data, stat:awaiting response, type:support

**Comment by dails08** [comment] 2021-04-22 15:05
I'm getting a similar problem.  Running fit locally runs no problem, but running it on a TPU fails.  The error message is less informative, but it seems to be failing in the same spot: calculating cardinality.  See the below notebook.

https://colab.research.google.com/drive/13KUPcl8o03jYfIFj_UjAL3xPtlHH8umH?usp=sharing
