### ISSUE TITLE
Detected cudnn out-of-bounds write in conv scratch buffer! This is likely a cudnn bug

### ISSUE THREAD

**Issue by xxxzhi** [tensorflow/tensorflow#32836] opened 2019-09-26 10:00 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): both source and binary
- TensorFlow version (use command below): 1.14.0
- Python version:3.7
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: cuda10, cuda10.1,  7.6.0, 7.6.2
- GPU model and memory: 2080Ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

2019-09-26 17:28:07.044771: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.044827: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.044863: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.044874: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.044881: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.044889: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.044896: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.044907: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.065798: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.065836: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.065866: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.065877: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.065885: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.065892: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.065899: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.065909: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.082404: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.082436: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.082464: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.082474: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.082482: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.082490: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.082497: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.082506: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.109990: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.110017: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.110045: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.110055: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.110064: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.110071: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.110078: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.110088: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.144289: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.144361: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.144396: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.144406: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.144414: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.144422: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.144429: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.144440: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.161422: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.161467: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.161501: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.161512: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.161520: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.161529: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.161536: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.161547: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.176122: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.176175: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.176206: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.176217: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.176226: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.176234: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.176241: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.176253: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.191145: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.191200: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.191232: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.191243: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.191251: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.191259: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.191266: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.191279: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.207762: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.207808: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.207856: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.207867: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.207874: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.207881: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.207889: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.207901: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.225787: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:157] Detected cudnn out-of-bounds write in conv input/output buffer! This is likely a cudnn bug. We will skip this algorithm in the future, but your GPU state may already be corrupted, leading to incorrect results. Within Google, no action is needed on your part. Outside of Google, please ensure you're running the latest version of cudnn. If that doesn't fix the problem, please file a bug with this full error message and we'll contact nvidia.
2019-09-26 17:28:07.225859: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:166] Redzone mismatch in LHS redzone of buffer 0x7fd3e5090200 at offset 0; expected ffffffffffffffff but was 3b0387303ca4a820.
2019-09-26 17:28:07.225900: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:167] HloInstruction %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}"
2019-09-26 17:28:07.225934: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:112] Device: GeForce RTX 2080 Ti
2019-09-26 17:28:07.225948: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:113] Platform: Compute Capability 7.5
2019-09-26 17:28:07.225966: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:114] Driver: 10010 (418.87.0)
2019-09-26 17:28:07.225981: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:115] Runtime: <undefined>
2019-09-26 17:28:07.226003: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:122] cudnn version: 7.6.2
2019-09-26 17:28:07.226796: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:525] Internal: All algorithms tried for convolution %custom-call = (f32[5,5,2,64]{1,0,2,3}, u8[0]{0}) custom-call(f32[155,2,64,64]{3,2,1,0} %arg8.9, f32[155,64,60,60]{3,2,1,0} %select.42), window={size=5x5}, dim_labels=bf01_01io->bf01, custom_call_target="__cudnn$convBackwardFilter", metadata={op_type="Conv2DBackpropFilter" op_name="HICO_1/gradients/HICO_0/resnet_v1_50_3/conv1_sp/Conv2D_grad/Conv2DBackpropFilter"}, backend_config="{\"convResultScale\":1}" failed.  Falling back to default algorithm.

**Comment by ravikyram** [comment] 2019-09-27 05:54
Can you please provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by xxxzhi** [comment] 2019-09-27 08:13
well, I just try to merge two branch (ResNet50) to construct new loss. And then, it will run into the problem occasionally. My program will continue to run even though running into that problem.

here is my peseude code:

      with sess.graph.as_default(), tf.device('/cpu:0'):
           
            for i in range(2):
                gpu_idx = i
                if len(os.environ['CUDA_VISIBLE_DEVICES'].split(',')) == 1:  # 1 gpu is ok.
                    gpu_idx = 0
                with tf.device('/gpu:%d' % gpu_idx):
                    with tf.name_scope('%s_%d' % ('test', i), ) as scope:

                        self.net.set_ph(tensor_from_dataset_api) # image

                        # Build the main computation graph
                        layers = self.net.create_architecture(True)  # is_training flag: True

                        # Define the loss
                        loss = layers['total_loss']
                        tower_losses.append(loss)
                        if i == 1:
                            variables = tf.trainable_variables()
                            grads_and_vars = self.optimizer.compute_gradients(tf.reduce_sum(tower_losses), variables)

            capped_gvs = [(tf.clip_by_norm(grad, 1.), var) for grad, var in grads_and_vars if grad is not None]
            train_op = self.optimizer.apply_gradients(capped_gvs, global_step=global_step)
            tf.summary.scalar('lr', lr)
            # tf.summary.scalar('merge_loss', new_loss)
            self.net.summary_op = tf.summary.merge_all()


when I use the average_gradients style, everything is right. here is my successful code. 

       with sess.graph.as_default(), tf.device('/cpu:0'):
            for i in range(2):
                gpu_idx = i
                if len(os.environ['CUDA_VISIBLE_DEVICES'].split(',')) == 1: 
                    gpu_idx = 0
                with tf.device('/gpu:%d' % gpu_idx):
                    with tf.name_scope('%s_%d' % ('test', i), ) as scope:
         
                        self.net.set_ph(tensor_from_dataset_api ) # image

                        # Build the main computation graph
                        layers = self.net.create_architecture(True)  # is_training flag: True

                        # Define the loss
                        loss = layers['total_loss']
                        tower_losses.append(loss)
                        variables = tf.trainable_variables()
                        grads_and_vars = self.optimizer.compute_gradients(loss, variables)
                        tower_grads.append(grads_and_vars)
            grads_and_vars = self.average_gradients(tower_grads)
            capped_gvs = [(tf.clip_by_norm(grad, 1.), var) for grad, var in grads_and_vars if grad is not None]
            train_op = self.optimizer.apply_gradients(capped_gvs, global_step=global_step)
            tf.summary.scalar('lr', lr)
            self.net.summary_op = tf.summary.merge_all()

Noticeably, the two images putted into GPU have different size. And my network is Resnet50 for Detection. It don't know whether it does matter.

Besides, **if I run the code within one GPU, it won't run into that problem.**

**Comment by ravikyram** [comment] 2019-09-30 10:02
@xxxzhi 
Looks like code is incomplete.In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-10-11 11:48
@xxxzhi 

Any update please?

**Comment by ravikyram** [comment] 2019-10-18 11:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-10-18 11:22 UTC
Labels: TF 1.14, comp:gpu, stat:awaiting response, type:support
