### ISSUE TITLE
[TF2.0] tf.reduce_mean crashes Python (Floating point exception) if the count becomes zero due to overflow

### ISSUE THREAD

**Issue by csachs** [tensorflow/tensorflow#34390] opened 2019-11-18 19:54 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary, source tested as well
- TensorFlow version: 2.0
- Python version: 3.7

**Describe the current behavior**

Running the script:
```python
import tensorflow as tf
data = tf.zeros(256, dtype=tf.uint8)
print(tf.reduce_mean(data))
```
Crashes the Python interpreter (e.g. `Floating point exception (core dumped)`).
(Likely as 256 overflows in `uint8` to 0, leading to an uncaught division by zero.

**Describe the expected behavior**
A result, possibly incorrect (due to too small dtype), or some other way to deal with the issue, e.g. assertion errors or other exceptions, however no crashing of Python.
*Ideally*, `tf.reduce_mean` could yield correct results for non-floating-point dtypes as well.

**Code to reproduce the issue**
See above.

**Comment by oanush** [comment] 2019-11-19 06:28
Issue replicating for TF-2.0 and tf-nightly, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/dcb73f2c1dea1d095f2acaf69df575f0/34390.ipynb) of colab.Thanks!

**Comment by Leslie-Fang** [comment] 2019-11-19 13:07
from the call stack, the core dump happens in the eigen lib

`#0  0x00007f2e1fe1f527 in std::_Function_handler<void (long, long), Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<unsigned char, 0, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::bind2nd_op<Eigen::internal::scalar_quotient_op<unsigned char const, unsigned char const> >, Eigen::TensorReductionOp<Eigen::internal::SumReducer<unsigned char>, Eigen::IndexList<Eigen::type2index<0l>> const, Eigen::TensorMap<Eigen::Tensor<unsigned char const, 1, 1, long>, 16, Eigen::MakePointer> const, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice, false, (Eigen::internal::TiledEvaluation)0>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<unsigned char, 0, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::bind2nd_op<Eigen::internal::scalar_quotient_op<unsigned char const, unsigned char const> >, Eigen::TensorReductionOp<Eigen::internal::SumReducer<unsigned char>, Eigen::IndexList<Eigen::type2index<0l>> const, Eigen::TensorMap<Eigen::Tensor<unsigned char const, 1, 1, long>, 16, Eigen::MakePointer> const, Eigen::MakePointer> const> const> const&, Eigen::ThreadPoolDevice const&)::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()`

**Comment by jvishnuvardhan** [comment] 2020-02-26 23:47
@csachs Looks like this was resolved. I couldn't reproduce the issue. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1f50643112231016fa21d70942febf93/untitled838.ipynb) is the gist.

I am closing this issue as it was resolved. Please feel free to open if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2020-02-26 23:47 UTC
Labels: TF 2.0, comp:ops, type:bug

**Comment by csachs** [comment] 2020-03-03 09:59
Looks good in nightly.
