### ISSUE TITLE
Tensorboard does not list any event

### ISSUE THREAD

**Issue by jaycode** [tensorflow/tensorflow#1671] opened 2016-03-27 20:46 UTC
Tensorboard does not list any event stored in disk.

### Environment info
Operating System: Docker on Windows 10

Tensorflow version 0.7.1

### Steps to reproduce
```
graph = tf.Graph()
with graph.as_default(), tf.device('/cpu:0'):
  a = tf.constant(5.0)
  b = tf.constant(6.0)
  c = a * b
  
  # Enter data into summary.
  c_summary = tf.scalar_summary("c", c)
  merged = tf.merge_all_summaries()

with tf.Session(graph=graph) as session:
  writer = tf.train.SummaryWriter("log/test_logs", session.graph_def)

  result = session.run([merged])
  tf.initialize_all_variables().run()
  writer.add_summary(result[0], 0)
```

I then ran `tensorboard --logdir={absolute path to log/test_logs}` but no event was listed there. Is there anything I should have written differently in the code maybe?

Note that `log/test_logs` does contain files like `events.out.tfevents.1459102927.0a8840dee548`.

### What have you tried?
Running `https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py` did not correct this (despite the events correctly outputted to disk).

**Comment by mrry** [comment] 2016-03-28 16:17
Just a quick suggestion: have you tried adding `writer.flush()` or `writer.close()` after `writer.add_summary(...)`? The `tf.train.SummaryWriter` class writes events to a file asynchronously, so if you exist immediately after writing the event, it may not appear in the log.

**Comment by jaycode** [comment] 2016-03-28 18:14
Yeah, I have tried `writer.flush()`, did not do anything. Thing is the logs are already there, in file format, so I think the problem lies in tensorboard not reading them properly, somehow.

**Comment by mrry** [comment] 2016-03-28 18:20
You could try using a [`tf.train.summary_iterator(filename)`] in a separate Python program to scan over the contents of your event files, and check that the expected events are in the file.

**Comment by jaycode** [comment] 2016-03-28 18:39
Yes, that works, it shows reports like:
```
wall_time: 1459102927.0
file_version: "brain.Event:2"

wall_time: 1459102927.88
graph_def: "\nK\n\013Placeholder\022\013Placeholder\"\r/device:CPU:0*\013\n\005dtype\022\0020\001*\023\n\005shape\022\n:\010\022\002\010\002\022\002\010\002\nU\n\005Const\022\005Const\"\r/device:CPU:0*\013\n\005dtype\022\0020\001*)\n\005value\022 B\036\010\001\022\010\022\002\010\002\022\002\010\002\"\020\000\000\200?\000\000\200?\000\000\000@\000\000\000@\nb\n\006MatMul\022\006MatMul\032\013Placeholder\032\005Const\"\r/device:CPU:0*\021\n\013transpose_b\022\002(\000*\021\n\013transpose_a\022\002(\000*\007\n\001T\022\0020\001\nM\n\024HistogramSummary/tag\022\005Const\"\r/device:CPU:0*\013\n\005dtype\022\0020\007*\022\n\005value\022\tB\007\010\007\022\000B\001c\nZ\n\020HistogramSummary\022\020HistogramSummary\032\024HistogramSummary/tag\032\006MatMul\"\r/device:CPU:0*\007\n\001T\022\0020\001\nS\n\031MergeSummary/MergeSummary\022\014MergeSummary\032\020HistogramSummary\"\r/device:CPU:0*\007\n\001N\022\002\030\001\"\002\010\010"
```

I'm suspicious that the problem is with `--logdir={$PWD}` where somehow logdir does not get sent to tensorboard. How to test this?

**Comment by mrry** [comment] 2016-03-28 21:25
When you run the `tf.train.summary_iterator()` does it only show those two records, or do you see any records that contain `wall_time:` and `summary:`? (The log you showed doesn't contain summaries, and so TensorBoard would not generate any plots, but it should show the graph visualization.)

**Comment by danmane** [comment] 2016-03-30 07:38
@jaycode: If you think the logdir isn't getting through properly, you can test that by launching TensorBoard with the --debug flag. [See details here.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong)

I think this might be a duplicate of [#1421](https://github.com/tensorflow/tensorflow/issues/1421). It seems that there's an issue with open-source TensorBoard sometimes not loading any data from events files. The trouble is, I've never been able to reproduce this on any of my machines. A co-worker had it reproducing once, but it disappeared when he re-installed the package. I now think it might be consistently repro'ing on docker, so I plan to look into that next.

**Comment by jaycode** [comment] 2016-04-02 06:42
@danmane Aha! This is where the issue was:

> INFO:tensorflow:TensorBoard path_to_run is: {'/notebooks/learn/udacity/nanodegree_ml_engineer/Deep Learning/assignments/Research/log/mnist_logs/{/notebooks/learn/udacity/nanodegree_ml_engineer/Deep': None}

Turns out there was a problem with `{$PWD}` variable that was provided. I changed the command to `tensorboard --logdir='mnist_logs' --debug` (from `logs` directory) and everything works perfectly.

More than anything, thanks for pointing out `--debug` option, wouldn't have find out without it.

**Closed** 2016-04-02 06:42 UTC
