### ISSUE TITLE
bazel version 0.6.0 unable to build latest stable release (v1.3.1)

### ISSUE THREAD

**Issue by samwhitlock** [tensorflow/tensorflow#13377] opened 2017-09-29 09:44 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.3.1
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 0.6.0
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: `bazel build //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem

With bazel version 0.6.0, building on the latest stable tagged release (v1.3.1) is not possible. I get the following error:

```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/8ea56cff279f39ec6c0003641e649819/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 0.569s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

When I pass the flag mentioned in the error message (`--incompatible_disallow_set_constructor=false`) to the pip package build command, I get a similar message:

```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/8ea56cff279f39ec6c0003641e649819/external/org_python_pypi_backports_weakref/BUILD.bazel:17:1: no such package '@org_python_license//': The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false and referenced by '@org_python_pypi_backports_weakref//:license'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 0.626s
FAILED: Build did NOT complete successfully (28 packages loaded)
    currently loading: tensorflow/core
```

This problem does not exist on `master`. It would be very useful to have even a tiny stable release (v1.3.2 or something) to include this fix for those of us that like to build against a stable release.

**Comment by yaroslavvb** [comment] 2017-09-29 16:58
I guess it's because stable release was cut before Bazel 0.6 was released https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu

I think 1.4 is coming shortly

**Comment by thelaurence** [comment] 2017-09-30 00:28
I uninstalled Bazel 0.6.0 and downloaded 0.5.4 from https://github.com/bazelbuild/bazel/releases.

It worked.

**Comment by znmeb** [comment] 2017-09-30 07:11
Thanks!! I have this too and will downgrade bazel!!

**Comment by yaroslavvb** [comment] 2017-09-30 09:54
cc @martinwicke perhaps https://github.com/tensorflow/tensorflow/blob/e55574f28257bdacd744dcdba86c839e661b1b2a/tensorflow/docs_src/install/install_sources.md should specify a bazel version? I've had similar issues before -- the latest version of bazel couldn't build any stable release on Mac

**Comment by martinwicke** [comment] 2017-09-30 14:06
@damienmg Bazel making backwards incompatible changes faster than we can release fixes is not ideal. 

@av8ramit we could do 1.3.2 the same way we did 1.3.1. But 1.4 is close enough so maybe not. In any case, we should definitely test for exact Bazel version (down to patch) in configure. It seems necessary.

**Comment by damienmg** [comment] 2017-09-30 14:48
Humm we have been testing for that incompatible change and upstreaming several fixes to lot of projects including tensorflow. We have also got a green build from Tensorflow team with 0.6.0rc. I would be interested in knowing how those breakage have not been caught during release testing.


There is a flag to deactivate that behavior to ensure people can use Bazel 0.6 until the problem is fixed. /Cc @vladmos who can say more about that.

**Comment by damienmg** [comment] 2017-09-30 14:49
(PS breaking change should only happen in minor version change, we forbid them in patch release now)

**Comment by martinwicke** [comment] 2017-09-30 15:17
I bet you are testing TF at head, which works. This is about the latest
stable (released) version of TF. Apparently, the flag alone does not fix
the issue though (see above).

If you guarantee no breaking changes for patch, we can check for Bazel
minor version in configure and issue a stern warning if it doesn't match
exactly.

It's a little sad because I'd love to get rid of configure and the less we
rely on it the better. The problem is that the compatibility check and
error message inside our build files is useless if Bazel dies before
executing it. That happened before, so we went back to a configure based
solution.

**Comment by damienmg** [comment] 2017-09-30 15:48
We should probably think of a better way to test for Bazel version. Also we
should definitely include your stable release in bazel release testing of
tensorflow.

/cc @gunan

**Comment by jerry73204** [comment] 2017-09-30 18:47
In file `third_party/gpus/cuda_configure.bzl` at line 120 `includes_cpp_set = set(includes_cpp)`:
May it be patched to become `depset(includes_cpp)`?

**Comment by gunan** [comment] 2017-10-02 07:25
It definitely may be. Would you like to send a pull request making the
change you proposed?

**Comment by jerry73204** [comment] 2017-10-02 13:24
Oops. I just submit a duplicated pull request (#13447). Please close it soon. Thanks.

**Closed** 2017-10-02 17:05 UTC

**Comment by LanYangXiXi** [comment] 2018-03-12 11:40
I meet the same problem, now I want know how to uninstall/downgrade my bazel0.10.0 to 0.5.4?
<img width="812" alt="screen shot 2018-03-12 at 19 17 45" src="https://user-images.githubusercontent.com/31690605/37281786-32f74f3a-262d-11e8-96a5-97974853055c.png">

**Comment by rameshjesswani** [comment] 2018-03-14 15:35
@LanYangXiXi I am looking for bazel 0.5.4, did you find any source to download that?
