### ISSUE TITLE
TypeError: ones_initializer() got multiple values for keyword argument 'dtype' when execute the inception_train

### ISSUE THREAD

**Issue by masanao-miyamoto** [tensorflow/tensorflow#5742] opened 2016-11-21 06:59 UTC
## Exception:

```
...
File "inception/slim/variables.py", line 290, in variable
  trainable=trainable, collections=collections)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
  custom_getter=custom_getter)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
  custom_getter=custom_getter)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
  validate_shape=validate_shape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
  caching_device=caching_device, validate_shape=validate_shape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
  expected_shape=shape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 224, in __init__
  expected_shape=expected_shape)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
  initial_value(), name="initial_value", dtype=dtype)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
  shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for keyword argument 'dtype'
```

I think recently changes of tensorflow.python.init_ops influence to this issue.

## [init_ops.py](https://github.com/tensorflow/tensorflow/commit/cfb2280d3f6ced298681bd1141479a59a06abde8)
```diff
< def ones_initializer(dtype=dtypes.float32, partition_info=None):
---
> def ones_initializer(shape, dtype=dtypes.float32, partition_info=None):
```

## [variable_scope.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L665)

```python
 655     # Create the tensor to initialize the variable.
 656     if initializer is None:
 657       initializer = init_ops.uniform_unit_scaling_initializer()
 658     # Clear control dependencies while creating the initializer.
 659     with ops.control_dependencies(None):
 660       if initializing_from_value:
 661         init_val = initializer
 662         variable_dtype = None
 663       else:
 664         init_val = lambda: initializer(
 665             shape.as_list(), dtype=dtype, partition_info=partition_info)
 666         variable_dtype = dtype.base_dtype
```

`lambda:initiallizer` calls with three parameters. So, parameter missmatch occured.

I think it needs to change `variable_scope.py` source code.

**Comment by anujsharma1** [comment] 2016-11-21 08:26
@masanao-miyamoto That's correct !! I am having same error too.. please [have a look here](https://github.com/tensorflow/models/issues/672)

**Comment by jayhwan91lee** [comment] 2016-11-21 16:18
thanks for the code references, 
I could temporaily fix this issue by reverting 'ones_initializer' back to the previous version

**Comment by prb12** [comment] 2016-11-21 17:41
This is not a TensorFlow bug, but a breaking change to the API which was introduced 11 days ago in this commit: https://github.com/tensorflow/tensorflow/commit/cfb2280d3f6ced298681bd1141479a59a06abde8

I assume that you are using a nightly build of TensorFlow?

The inception model hasn't been updated to use the new API yet. @shlens

**Comment by shlens** [comment] 2016-11-21 18:04
The issue seems to be a duplicate of this [issue](https://github.com/tensorflow/models/issues/672) due to an API change. @itsmeolivia Would you be able to take a look?

**Comment by masanao-miyamoto** [comment] 2016-11-22 05:15
@prb12, @shlens thanks for your advise.

I understood an API changes.

I tried to fix [model/inception/inception/slim/ops.py](https://github.com/tensorflow/models/blob/master/inception/inception/slim/ops.py#L92) . And successfully execute inception training jobs. Like below

```diff
      gamma = variables.variable('gamma',
                                 params_shape,
-                                 initializer=tf.ones_initializer,
+                                 initializer=tf.ones_initializer(),
                                 trainable=trainable,
                                 restore=restore)
```

**Comment by civilman628** [comment] 2016-11-22 23:33
only change one line above will fix this issue?

**Comment by panovr** [comment] 2016-11-24 17:13
@civilman628 I changed two lines for fixing this issue.

**Comment by masanao-miyamoto** [comment] 2016-11-25 12:51
@civilman628 @panovr I changed two lines. 

``` diff 
 91     if scale:
 92       gamma = variables.variable('gamma',
 93                                  params_shape,
- 94                                  initializer=tf.ones_initializer,
+ 94                                  initializer=tf.ones_initializer(),
 95                                  trainable=trainable,
 96                                  restore=restore)
 97     # Create moving_mean and moving_variance add them to
 98     # GraphKeys.MOVING_AVERAGE_VARIABLES collections.
 99     moving_collections = [moving_vars, tf.GraphKeys.MOVING_AVERAGE_VARIABLES]
100     moving_mean = variables.variable('moving_mean',
101                                      params_shape,
102                                      initializer=tf.zeros_initializer,
103                                      trainable=False,
104                                      restore=restore,
105                                      collections=moving_collections)
106     moving_variance = variables.variable('moving_variance',
107                                          params_shape,
- 108                                          initializer=tf.ones_initializer,
+ 108                                          initializer=tf.ones_initializer(),
109                                          trainable=False,
110                                          restore=restore,
111                                          collections=moving_collections)
```

**Comment by ppwwyyxx** [comment] 2016-11-27 05:07
I think it's very counter-intuitive that `tf.zeros_initializer` and `tf.ones_initializer` has different APIs..

**Comment by maxim5** [comment] 2016-12-14 11:06
The problem is still actual in `batch_normalization`:

```
        moving_mean = vs.variable(scope + 'moving_mean',
                                  input_shape[-1:],
                                  initializer=tf.zeros_initializer,
                                  trainable=False,
                                  restore=restore)
        moving_variance = vs.variable(scope + 'moving_variance',
                                      input_shape[-1:],
                                      initializer=tf.ones_initializer,
                                      trainable=False,
                                      restore=restore)
```

Any workaround?

**Comment by luisbanjo** [comment] 2016-12-17 00:55
Having this same error msg following: https://tensorflow.github.io/serving/serving_inception
At this point: 
root@c97d8e820ced:/serving# bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export

"""    expected_shape=expected_shape)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 322, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/root/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 672, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: zeros_initializer() got multiple values for keyword argument 'dtype'"""

**Comment by suiyuan2009** [comment] 2017-01-19 05:23
@luisbanjo try to change all `tf.zeros_initializer` to `tf.zeros_initializer()`, same as `tf.ones_initializer`.

**Comment by luisbanjo** [comment] 2017-01-19 18:36
yup, that we did already, but it is not a permanent solution :)

**Comment by Coderx7** [comment] 2017-01-22 07:02
I had the same problem when using batchnormalization from tflearn. 
I followed @suiyuan2009's suggestion and changed the `tf. ones_initializer` to `tf.ones_initializer()`
and the error is gone (changing `tf.zeros_initializer `to `tf.zeros_initializer()` would generate error! so I left it as was)

**Comment by itsmeolivia** [comment] 2017-01-23 18:38
I did a search on tensorflow for any zeros_initializer and ones_initializer instances that may have been missed and there are none.  tflearn is not a tensorflow supported library so you should report those issues to the actual tflearn repo on github.  Likewise, tensorflow_serving issues should be reported to the tensorflow_serving repo.

**Comment by ibadami** [comment] 2017-01-25 12:14
@itsmeolivia 

```
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    net = model[network](inputshape, num_classes, img_prep, img_aug)
  File "/home/badami/Codes/deeplearning/src/models.py", line 103, in vggAnet
    net = batch_normalization(net)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/layers/normalization.py", line 69, in batch_normalization
    restore=restore)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/variables.py", line 54, in variable
    collections=collections)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for argument 'dtype'
```
My error message suggest that the error come s from ``` tensorflow/python/ops/variables.py```.
Are you sure that all ones_initializer instances are fixed?

I am using tensorflow_gpu 12.1 .

**Comment by aselle** [comment] 2017-02-15 19:07
Please update to TensorFlow 1.0. The initializer API should be consistent for all functions in 1.0.

**Closed by aselle** 2017-02-15 19:07 UTC
