### ISSUE TITLE
resnet model in tf slim does not take is_training param

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4887] opened 2016-10-11 03:49 UTC
Compare the [resnet_v2 model](https://github.com/tensorflow/tensorflow/blob/8e48ec6ea0492e2cb9fd19c0a2ccf41afc7b4dc6/tensorflow/contrib/slim/python/slim/nets/resnet_v2.py) to the [vgg model](https://github.com/tensorflow/tensorflow/blob/8e48ec6ea0492e2cb9fd19c0a2ccf41afc7b4dc6/tensorflow/contrib/slim/python/slim/nets/vgg.py). The vgg model takes `is_training` whereas the resnet model does not. This param should be taken and passed to the `batch_norm` layers.

The docs for the v1 model do reference `is_training`, but I don't see it used.

**Comment by cancan101** [comment] 2016-10-11 03:58
I guess you do something like this:
```
with slim.arg_scope(resnet_v2.resnet_arg_scope(is_training)):
  ....
```
Not sure if docs can be improved here?

**Comment by jart** [comment] 2016-10-14 00:50
Tangential: I'm surprised you can reference `tf.contrib.framework.arg_scope` as `tf.contrib.slim.arg_scope`. We're going to have to do something about that. I filed #4950.

Maybe the `is_training` param should be deprecated on the vgg model and display a warning to use `tf.contrib.framework.arg_scope` instead. I'm going to mark this as contributions welcome if anyone wants to send us a PR with that cleanup. CC: @sguada

**Comment by haosdent** [comment] 2016-10-16 11:22
I am going to send a PR shortly.

**Comment by sguada** [comment] 2016-10-17 22:42
See https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v2.py which is going to replace this soon.

**Comment by dhaneshr** [comment] 2017-03-15 15:28
Passing `is_training=False` during inference messes up the output for the resnet_v1 model. Tried doing 
`with slim.arg_scope(resnet_v2.resnet_arg_scope(is_training)):`  but getting


` with slim.arg_scope(resnet_arg_scope(is_training)):
NameError: name 'is_training' is not defined`

How exactly does one go about passing the `is_training` parameter to the model ? BTW, will a pre-trained checkpoint be released for resnet_v2?

**Comment by sguada** [comment] 2017-03-16 02:35
you need to define is_training

`with slim.arg_scope(resnet_arg_scope(is_training=False)):`

**Comment by skye** [comment] 2017-06-16 19:21
@sguada what's the status on this? Can we close this or is there still something being requested?

**Comment by jccaicedo** [comment] 2017-07-19 01:36
I also have an experience similar to @dhaneshr : Passing `is_training=False` messes up the output (resnet_v2 with TFv1.2.0). That means the feed-forward pass diverges to large numbers, and sometimes even to NaN. I wonder if that's a problem of `slim` or `layers`. 

I train my own ResNet model, which successfully converges after a few epochs. However, after I save the model and then recover it for inference, everything seems wrong, even with images used during training. If I do `is_training=True` the outpus are mostly random (caused by BatchNormalization). When I recover the model for additional training epochs, it works just fine, and keeps the accuracy improving. I checked the weights of the network, and they're alright.

It seems like the flag `is_training=False` is not being passed correctly somewhere, and the BatchNormalization layers fail to keep the activations bounded. Does anybody have a suggestion for fixing this? Or maybe I'm missing something?

**Comment by windid** [comment] 2017-09-23 14:08
@jccaicedo I'm suffering the same problem, have you got any solution?

**Comment by gaosanyuan** [comment] 2017-11-29 10:42
I'm suffering the same problem

**Comment by tasx0823** [comment] 2017-12-02 08:04
I am meeting the same problem. I have tried to decrease my loss in training, however,in testing I find the outout is all messed!   @jccaicedo  Have you found any way out?

**Comment by mingxingtan** [comment] 2018-02-07 23:39
It is most likely somethings (e.g. batchnorm) are not set properly for is_training=False. However, since this is a departure from our official models, I would recommend using the official resnet models (https://github.com/tensorflow/models).

I am closing this bug now. If you have similar issues for the official models, please feel free to filea separate bug.

**Closed** 2018-02-07 23:39 UTC
Labels: stat:contributions welcome
