### ISSUE TITLE
[TF 2.0 API Docs] tf.audio.encode_wav

### ISSUE THREAD

**Issue by missaugustina** [tensorflow/tensorflow#28238] opened 2019-04-28 18:58 UTC
API Doc update for https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/audio/encode_wav

Correct links? No
Clear Description? No
Usage Example?
Parameters Defined? Yes, not verified against current code
Returns defined? Yes, not verified against current code
Raises listed and defined? No
Visuals, if applicable? No

I will submit a PR, please assign this bug to me.

Part of Issue #28237 & Issue #28236

**Comment by muddham** [comment] 2019-04-29 14:24
@missaugustina Can you please let us know if this is the duplicate of [#28237](https://github.com/tensorflow/tensorflow/issues/28237), if so please let us know so that we will close this issue as the same issue is being referenced in #28237

**Comment by missaugustina** [comment] 2019-04-30 21:34
I thought I was supposed to file one issue per api call?

**Comment by missaugustina** [comment] 2019-04-30 21:37
See also Issue #28237 & Issue #28236

**Comment by missaugustina** [comment] 2019-05-01 00:54
I plan to submit a PR for this issue

**Comment by sachinprasadhs** [comment] 2021-11-04 18:10
These details are generated through .pbtxt file, you can see the same details [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_EncodeWav.pbtxt). 
For tutorials and usage examples on tf.audio, you can refer this [link](https://github.com/tensorflow/docs/tree/master/site/en/tutorials/audio), Thanks.

**Closed** 2021-11-18 18:36 UTC
Labels: type:docs-bug, stat:awaiting response, stalled, comp:ops, TF 2.0
