### ISSUE TITLE
Keras way of auto-naming layers triggers a naming issues when loading an existing model, and slicing its output

### ISSUE THREAD

**Issue by scd75** [tensorflow/tensorflow#43824] opened 2020-10-06 16:17 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7

**Describe the current behavior**
When adding a strided_slice layer using "numpy-style" syntax (eg [: , :....]), Keras auto-names this layer "tf_op_layer_strided_slice_{i}", incrementing i every time such layer is created.
However, when opening an already-existing model, without creating any layer in the session, i restarts at 0. Hence, when adding at strided_slice operation at the end of the model, an error is triggered as the model now has 2 layers with the same name "tf_op_layer_strided_slice"

PS: i cannot use the explicit tf.strided_slice layer with naming, as it does not have the same "shape-inference" capabilities as numpy-style slicing

**Describe the expected behavior**
auto-naming shall carry on incrementing from all known layer in the session, whether they have been created or loaded from a model file.

**Standalone code to reproduce the issue**
Run this code first with initial_builing = True, then False

```
import tensorflow as tf

initial_builing = False
model_loading = True

if initial_builing:

    layer1 = tf.keras.Input((1,),)
    layer2 = tf.keras.layers.Dense(1)

    model_output = layer2(layer1)[:,:-1]

    model = tf.keras.Model(layer1, model_output)
    model.summary()
    model.save('testmodel')

if model_loading:
    model = tf.keras.models.load_model('testmodel')
    model = tf.keras.Model(model.inputs, model.layers[-1].output[:,:-1])
```

**Other info / logs** 
```
Exception has occurred: ValueError
The name "tf_op_layer_strided_slice" is used 2 times in the model. All layer names should be unique.
  File "C:\tests_v2.py", line 19, in <module>
    model = tf.keras.Model(model.inputs, model.layers[-1].output[:,:-1])
```

**Comment by bhack** [comment] 2020-10-06 19:36
I  cannot reproduce this on Colab.

**Comment by scd75** [comment] 2020-10-06 22:10
you have to first run with (to build the model)
initial_builing = True

then run a second time (to only load the model)
initial_builing = False

**Comment by bhack** [comment] 2020-10-06 22:11
> you have to first run with (to build the model)
> initial_builing = True
> 
> then run a second time (to only load the model)
> initial_builing = False

Yes

**Comment by ravikyram** [comment] 2020-10-07 06:32
@scd75 

I have tried in colab with TF version 2.3.1 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/204cabefa50b64d006a6fb90acb94c14/untitled428.ipynb).Please, correct me if i am doing something wrong.Thanks!

**Comment by scd75** [comment] 2020-10-07 07:58
I think that since you are running on jupyter, the variables stay in the cache between the 2 cells. Can you try relaunching the Google colab environment between the 2 executions ? to make sure the model is loaded purely from scratch ?

Here is the full log I get when executing, with the script located in a .py file:

first execution,  with "initial_building" = True

``` 

PS C:\Users\xxxxxxxxxxxxxxxxxxxxx>  & 'c:\Users\xxxxxxxxxxxxxxxxxxxxxx\Scripts\python.exe' 'c:\Users\xxxxxxxxxxxxxxxxxxxxx\.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\lib\python\debugpy\launcher' '52248' '--' 'c:\tests_v2.py'
2.3.1
2020-10-07 09:44:45.381325: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-07 09:44:45.460688: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x25f3f56a4e0 initialized for platform Host (this 
does not guarantee that XLA will be used). Devices:
2020-10-07 09:44:45.509832: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 1)]               0
_________________________________________________________________
dense (Dense)                (None, 1)                 2
_________________________________________________________________
tf_op_layer_strided_slice (T [(None, 0)]               0
=================================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-10-07 09:44:46.091859: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the fuWARNING:tensorflow:From C:\xxxxxxxxxxxx.venv\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
```

second execution, with "initial_building" = False
```
PS C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/.venv/Scripts/Activate.ps1
(.venv) PS C:\Users\xxxxxxxxxxxxxxxxxxxxxxxxxxx\scripts python SC>  cd 'c:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\scripts python SC'; & 'c:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\Scripts\python.exe' 'c:\xxxxxxxxxxxxxxxxxxxxxx\.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\lib\python\debugpy\launcher' '52319' '--' 'c:\tests_v2.py' 
2.3.1
2020-10-07 09:45:24.173098: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-07 09:45:24.196648: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1d7ddd78b00 initialized for platform Host (this 
does not guarantee that XLA will be used). Devices:
2020-10-07 09:45:24.209542: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "C:\xxxxxxxxxxxxxxxxxxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\xxxxxxxxxxxxxxxxxxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\xxxxxxxxxxxxxxxxxxx\.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\xxxxxxxxxxxxxxxxxxx\.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\xxxxxxxxxxxxxxxxxxx\.vscode\extensions\ms-python.python-2020.9.112786\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\xxxxxxxxxxxxxxxxxxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\xxxxxxxxxxxxxxxxxxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\xxxxxxxxxxxxxxxxxxx\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\tests_v2.py", line 20, in <module>
    model = tf.keras.Model(model.inputs, model.layers[-1].output[:,:-1])
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 242, in __new__
    return functional.Functional(*args, **kwargs)
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper 
    result = method(self, *args, **kwargs)
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 115, in __init__       
    self._init_graph_network(inputs, outputs)
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper 
    result = method(self, *args, **kwargs)
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 191, in _init_graph_network
    self.inputs, self.outputs)
  File "C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\.venv\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 942, in _map_graph_network
    str(all_names.count(name)) + ' times in the model. '
**ValueError: The name "tf_op_layer_strided_slice" is used 2 times in the model. All layer names should be unique.**

```

**Comment by bhack** [comment] 2020-10-07 09:52
Ok I've tried with https://github.com/tensorflow/tensorflow/pull/43841 but I don't know if it will have side effects. Let's wait for a review.

**Comment by bhack** [comment] 2020-10-07 20:51
@tomerk you can reproduce on Colab with:
```
!pip install tf-nightly-cpu
import tensorflow as tf
import gc 

initial_builing = True
model_loading = True

if initial_builing:

    layer1 = tf.keras.Input((1,),)
    layer2 = tf.keras.layers.Dense(1)

    model_output = layer2(layer1)[:,:-1]

    model = tf.keras.Model(layer1, model_output)
    model.summary()
    model.save('testmodel')
del model, model_output
tf.keras.backend.clear_session()
gc.collect()
if model_loading:
    model = tf.keras.models.load_model('testmodel')
    model = tf.keras.Model(model.inputs, model.layers[-1].output[:,:-1])
```

**Comment by tomerk** [comment] 2020-10-07 21:13
Hmm okay that's surprising to me that it still happens in the nightlies, because the name-gen for op layers should follow similar logic as for other layers. I'll take a look.

**Comment by bhack** [comment] 2020-10-07 21:21
@tomerk Is name in  that land in ` name=_TF_OP_LAYER_NAME_PREFIX + name` already autoincrement/unique?

**Comment by tomerk** [comment] 2020-10-07 21:21
So, I've confirmed that this is a general saving/loading issue with the auto-naming layers *whenever adding any layer after loading the model* not just when slicing the output. (I repro'd it w/ e.g. another dense layer at the end instead of slicing.)

I'll go ahead and escalate this because this seems like a pretty serious issue.

**Comment by bhack** [comment] 2020-10-07 21:25
@tomerk So can I close https://github.com/tensorflow/tensorflow/pull/43841 or do you have any hints for change that PR?

**Comment by tomerk** [comment] 2020-10-07 21:27
yeah that pr won't fix this problem. We'll have to fix either the save/load code or the backend unique_object_name code or both.

**Comment by bhack** [comment] 2020-10-07 21:31
@tomerk Let me know If you have any pinpoint I could try to modify that PR if you are out of bandwidth.

**Comment by tomerk** [comment] 2020-10-07 22:32
I have a tentative fix ready internally. Once it's submitted it should get synced out to github pretty quickly.

**Comment by tomerk** [comment] 2020-10-09 17:19
Okay, this should now be working in the nightlies.

The fix in commit 62d414b works by adding any names seen during layer creation to an avoid-list that is used when generating names for auto-gen'd op layers. Note that we *don't* do this for all layers (even though auto-naming can run into name collisions for other layers as well), because:
1. it would have the practical affect of changing actual layer names when people do transfer learning w/ a loaded model as a layer in their outer model. This would break a lot of tf1-style name-based checkpoint loading and model manipulation code.
2. for layers other than tf op layers, users can explicitly pass a `name` if needed to get around accidental name collisions, so it's not as big of a problem as for auto-gen'd op layers.

**Closed by tomerk** 2020-10-09 17:19 UTC
Labels: TF 2.3, comp:keras, type:bug

**Comment by bhack** [comment] 2020-10-09 18:05
@tomerk I've a question. `OBSERVED_NAMES` in not as `PER_GRAPH_OBJECT_NAME_UIDS` with `Graph` key (As PER_GRAPH in the name). Is it ok that it is global?

**Comment by bhack** [comment] 2020-10-15 21:11
@tomerk Can you clarify?

**Comment by tomerk** [comment] 2020-10-15 21:20
The per-graph stuff is primarily legacy-compatibility. The new op layers and the OBSERVED_NAMES set are only used in an eager-first tf2 setting, so it doesn't need special graph-specific logic. A lot of the graph-specific logic in backend has been prone to be fairly buggy and prone to error, which is why I try to avoid it when working on things that aren't needed in tf v1 graph compatibility.

**Comment by bhack** [comment] 2020-10-15 21:43
@tomerk Thank you for exposing some history
