### ISSUE TITLE
[TF2.0] Not JSON Serializable error wasn thrown when using tf.keras.activations operators in keras model.

### ISSUE THREAD

**Issue by KichangKim** [tensorflow/tensorflow#28010] opened 2019-04-21 02:57 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 1809
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-gpu 2.0.0a0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: Geforce 1070

**Describe the current behavior**
When I used tf.keras.activations operators in my keras model, serialization of model was failed due to Not JSON Serializable error.

**Describe the expected behavior**
It should be serialized without any error.

**Code to reproduce the issue**
```
from tensorflow import keras
from tensorflow.keras import layers

inputs = keras.Input(shape=(784,), name='digits')
x = layers.Activation('relu')(inputs)
# x = keras.activations.relu(inputs)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)


model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')
model.summary()

model.save('path_to_my_model.h5')
```
If you changed from Activation() to relu, it failed to serialize.

**Comment by ymodak** [comment] 2019-04-29 19:43
I have slightly edited your code to be consistent with ```python tf.keras``` and was able to reproduce the error using TF-gpu 2.0 alpha.
```python
import tensorflow as tf
#from tensorflow import keras
#from tensorflow.keras import layers

inputs = tf.keras.Input(shape=(784,), name='digits')
#x = tf.keras.layers.Activation('relu')(inputs)
x = tf.keras.activations.relu(inputs)
outputs = tf.keras.layers.Dense(10, activation='softmax', name='predictions')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')
model.summary()

model.save('path_to_my_model.h5')
```
Output:
```python
---> 13 model.save('path_to_my_model.h5')
TypeError: ('Not JSON Serializable:', b'\n\x06Relu_8\x12\x04Relu\x1a\tdigits_25*\x07\n\x01T\x12\x020\x01')
```

**Comment by arthurflor23** [comment] 2019-05-01 03:19
I got the same error, but with:

* tf.keras.backend.expand_dims
* tf.keras.backend.squeeze
* tf.expand_dims
* tf.squeeze

**Comment by KichangKim** [comment] 2019-05-10 00:40
Additionally, using "+" operator instead of tf.keras.layers.Add makes this issue same.

**Comment by luaGeeko** [comment] 2019-05-26 16:09
I am facing the same issue, any suggestions or solutions for work around for now ??

**Comment by mketcha** [comment] 2019-07-03 15:10
I am having the same issue when using tf.concat in an otherwise keras-only model (can't use keras Concatenations due to issue #30355 ).

Only work around I have found so far is to use model.save_weights(). When loading, you need to redefine the model and then use model.load_weights()

**Comment by ismael-elatifi** [comment] 2019-07-17 08:05
Having same issue with `tf.transpose` :
`W0717 09:24:35.629342 14908 summary_ops_v2.py:1110] Model failed to serialize as JSON. Ignoring... ('Not JSON Serializable:', b'\n\ttranspose\x12\tTranspose\x1a\ndense/Relu\x1a\x0etranspose/perm*\x0b\n\x05Tperm\x12\x020\x03*\x07\n\x01T\x12\x020\x01')`
Thus `callbacks.ModelCheckpoint` fails to backup my model and all I get is a model file of 6 KB.

**Comment by Daniel451** [comment] 2019-07-20 16:21
Same problem here. Is this being worked on?

**Comment by omalleyt12** [comment] 2019-07-22 18:41
Was able to repro and have a fix out for this, should be in in a day or two

**Comment by loiccordone** [comment] 2019-07-29 08:02
Hello,
Any news? Thanks

**Comment by ppham27** [comment] 2019-07-29 16:31
> Hello,
> Any news? Thanks

Should be fixed: https://github.com/tensorflow/tensorflow/commit/7cc180f107f142432358ac33787466de90afd776

**Comment by ymodak** [comment] 2019-08-02 21:43
Closing this issue since its fixed in latest tf nightly build '2.0.0-dev20190802'
Thanks!

**Closed by ymodak** 2019-08-02 21:43 UTC
Labels: 2.0, comp:keras, type:bug

**Comment by yassinetb** [comment] 2020-03-15 20:07
Had the problem `callbacks.ModelCheckpoint`, setting `save_weights_only=True` solved the problem for me.

**Comment by 2020zyc** [comment] 2020-09-02 07:55
> Had the problem `callbacks.ModelCheckpoint` and `ModelCheckpoint`, setting `save_weights_only=True` solved the problem for me.

@yassinetb Did you have any solution for the error "TypeError: ('Not JSON Serializable:', tf.float32)" from setting save_weights_only=False

**Comment by ravinderkhatri** [comment] 2021-11-08 12:01
I am facing the same issue using tf.keras.callbacks.ModelCheckpoint . Any solution ?
