### ISSUE TITLE
Model learns with keras but doesn't learn with tf.keras

### ISSUE THREAD

**Issue by kmadhugit** [tensorflow/tensorflow#21738] opened 2018-08-20 15:41 UTC
The below code would just work fine on keras,

````python
import tensorflow as tf

from keras.layers import Flatten,Dense,Dropout
from keras.models import Sequential

#from tensorflow.python.keras.layers import Flatten,Dense,Dropout
#from tensorflow.python.keras.models import Sequential

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

import keras
print(f'tf version = {tf.__version__} ')

model = Sequential([
  Flatten(input_shape=(28,28)),
  Dense(512, kernel_initializer='uniform', activation=tf.nn.relu),
  Dropout(0.2),
  Dense(10, kernel_initializer='uniform', activation=tf.nn.softmax)
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1)
model.evaluate(x_test, y_test)
````

**KERAS**
````Using TensorFlow backend.
tf version = 1.10.0 
Epoch 1/1
2018-08-20 20:57:06.754898: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

   32/60000 [..............................] - ETA: 14:00 - loss: 2.3347 - acc: 0.1250
  224/60000 [..............................] - ETA: 2:14 - loss: 2.1174 - acc: 0.3839 
  416/60000 [..............................] - ETA: 1:19 - loss: 1.8965 - acc: 0.4712
  576/60000 [..............................] - ETA: 1:03 - loss: 1.7533 - acc: 0.5365
  ....
 .....
59744/60000 [============================>.] - ETA: 0s - loss: 0.2369 - acc: 0.9308
59936/60000 [============================>.] - ETA: 0s - loss: 0.2363 - acc: 0.9310
60000/60000 [==============================] - 22s 360us/step - loss: 0.2363 - **acc: 0.9310**
````
but if you the import layers from tf.keras instead of the keras(i.e comment lines 3 & 4 and uncomment lines 6 & 7), the weights won't be updated and model doesn't learn at all.

**tf.keras**
````
Using TensorFlow backend.
tf version = 1.10.0 
Epoch 1/1
2018-08-20 21:08:05.112916: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
   32/60000 [..............................] - ETA: 10:26 - loss: 14.1033 - acc: 0.1250
  224/60000 [..............................] - ETA: 1:42 - loss: 14.0464 - acc: 0.1205 
  448/60000 [..............................] - ETA: 58s - loss: 14.3412 - acc: 0.1027 
....
....
59744/60000 [============================>.] - ETA: 0s - loss: 13.2745 - acc: 0.1744
59904/60000 [============================>.] - ETA: 0s - loss: 13.2730 - acc: 0.1745
60000/60000 [==============================] - 19s 323us/step - loss: 13.2708 - **acc: 0.1746**
````

The problem is with **kernel_initalizer**, if you give a unsupported initalizer instead of giving an error tf.keras just fails somewhere. However keras works just fine.

**Comment by tensorflowbutler** [comment] 2018-08-21 00:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by kmadhugit** [comment] 2018-08-21 02:47
OS Platform and Distribution - Macbook Pro , MacOS High Sierra - 10.13.5
TensorFlow installed from - Conda install
TensorFlow version - 1.10.0
Bazel version - NA
CUDA/cuDNN version - NA
GPU model and memory  - NA
Exact command to reproduce - Given Above
Mobile device NA

**Comment by omalleyt12** [comment] 2018-08-22 18:03
Hi @kmadhugit, it looks like the default values for some tf.keras initializers are different than those in external Keras, causing this problem. I have a fix in progress, in the meantime you can get the desired behavior with:

```python
import tensorflow as tf

from tensorflow.python.keras.layers import Flatten,Dense,Dropout
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.initializers import RandomUniform

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

import keras
print(f'tf version = {tf.__version__} ')

model = Sequential([
  Flatten(input_shape=(28,28)),
  Dense(512, kernel_initializer=RandomUniform(minval=-0.05, maxval=0.05), activation=tf.nn.relu),
  Dropout(0.2),
  Dense(10, kernel_initializer=RandomUniform(minval=-0.05, maxval=0.05), activation=tf.nn.softmax)
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1)
model.evaluate(x_test, y_test)
```

I'll update this thread when the fix is available

**Comment by kmadhugit** [comment] 2018-08-23 03:03
The default initializers seems to be working fine, if I comment  kernel_initializer it would work fine as below,

````python
import tensorflow as tf

#from keras.layers import Flatten,Dense,Dropout
#from keras.models import Sequential

from tensorflow.python.keras.layers import Flatten,Dense,Dropout
from tensorflow.python.keras.models import Sequential

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

import keras
print(f'tf version = {tf.__version__} ')

model = Sequential([
  Flatten(input_shape=(28,28)),
  Dense(512,
#       kernel_initializer='uniform',
        activation=tf.nn.relu),
  Dropout(0.2),
  Dense(10,
#       kernel_initializer='uniform',
        activation=tf.nn.softmax)
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1)
model.evaluate(x_test, y_test)
````
it fails only when I give a wrong initializer.

**Comment by cy89** [comment] 2018-08-31 22:05
@kmadhugit I'm not quite following--are you saying that an unknown value for kernel_initializer is handled fine by keras, but not for tf.keras?

**Comment by omalleyt12** [comment] 2018-08-31 22:56
Just pushed the fix for this yesterday, it should be available in the nightly build shortly. The 'uniform' initializer is known, the issue was that the default values for `minval` and `maxval` for this initializer were set too large for the model to converge. I sync'd up their defaults with those in external Keras

**Comment by kmadhugit** [comment] 2018-09-01 08:46
I thought TF doesn't understand the 'uniform' initializer but @omalleyt12 just mentioned that its a problem with minval and maxval.

**Comment by omalleyt12** [comment] 2018-09-02 19:30
@kmadhugit the fix should be available in the nightly build now, could you try ```pip install tf-nightly``` (or ```pip install tf-nightly-gpu``` for GPU support) and let me know if the model is now training in tf.keras for you?

**Comment by kmadhugit** [comment] 2018-09-03 03:32
Hi @omalleyt12, Thank you. The model starts learning now, I think you have capped min and max values for 'uniform' initializer to (-0.05, 0.05) from (0,1). Can you give me the link to the PR, I like to have a look at the code changes.

**Comment by omalleyt12** [comment] 2018-09-04 16:55
Great, sure here's the PR:

https://github.com/tensorflow/tensorflow/commit/de05ebe296d83607ca0ab1803bd8eed6afa7f74f

Affected initializers were RandomUniform, RandomNormal, and TruncatedNormal

**Closed by omalleyt12** 2018-09-04 16:55 UTC
