### ISSUE TITLE
Android build failed using custom tensorflow model. Conflict workspace Error

### ISSUE THREAD

**Issue by alokranjan007** [tensorflow/tensorflow#21602] opened 2018-08-14 10:24 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
   Yes, I have modified no. of classes to be detect while training the model
- **OS Platform and Distribution: 14.04 LTS
- **Mobile device if the issue happens on mobile device**: Motoroloa, Android version 7.1.1
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: 4GB RAM, 64-bit

### Describe the problem
I had trained my custom model with different objects for the detection purpose. I had used ssd_mobilenet_v2_coco for my training. I could pull out the object detection on desktop with the customised trained model by using the webcam or passing an image. But I am unable to port it on android app. 
It is interesting that I am able to convert the file in .tflite format (the one which will be used by bazel) and for android. However, after the app installation it is getting crashed. The app is forcibly closed. It may be noted here that the classifier and speech app is working fine and there is no force shut down, but the problem remained the same with detect app. I then followed this [link](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) for change in the DetectorActivity.java inside  tensorflow/contrib/lite/examples/android/app/src/main/java/org/tensorflow/demo/DetectorActivity.java as below `private static final int TF_OD_API_INPUT_SIZE = 300;
  private static final boolean TF_OD_API_IS_QUANTIZED = true;
  private static final String TF_OD_API_MODEL_FILE = "detect.tflite";
  //private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/coco_labels_list.txt";
  private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/labelmap.txt";`

where detect.tflite and labelmap.txt both files are from the customized model.

Then I ran the command 
`bazel build -c opt --cxxopt='--std=c++11' "//tensorflow/contrib/lite/examples/android:tflite_demo"` and this successfully build the apk file and other dependencies. Meanwhile, it showed a conflict error. Errors read as below:
`CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
	external/tflite_mobilenet/WORKSPACE
	external/tflite_conv_actions_frozen/WORKSPACE

CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
	external/tflite_mobilenet_ssd/WORKSPACE
	external/tflite_conv_actions_frozen/WORKSPACE`

When I tried to build the apk over phone, the app is installed but it is getting closed forcefully. However,  the classifier and speech apps are working perfectly fine.

NOTE: The pre trained models are working absolutely fine on both desktop and as an app. However, the issue is with importing the custom app on phone.

**Comment by jdduke** [comment] 2018-08-14 20:59
> When I tried to build the apk over phone, the app is installed but it is getting closed forcefully. However, the classifier and speech apps are working perfectly fine.

Can you provide more details about the crash? Would you mind capturing the logcat entry for the crash? Or capturing and attaching a bug report?

**Comment by alokranjan007** [comment] 2018-08-16 05:10
Hi jdduke,
Thank you for your response. After the installation on android device, other two apps are opening fine. However, when I am opening the detection app it is saying **"TFLite Demo has stopped"** close the app.

I have followed all the steps [https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193]  under the section **"Running our model on Android"**. I have changed as instructed in the blog for the custom models. Following steps have been followed.
step 1.
`assets = [
   "//tensorflow/contrib/lite/examples/android/app/src/main/assets:labels_mobilenet_quant_v1_224.txt",
     "@tflite_mobilenet//:mobilenet_quant_v1_224.tflite",
     "@tflite_conv_actions_frozen//:conv_actions_frozen.tflite",
     "//tensorflow/contrib/lite/examples/android/app/src/main/assets:conv_actions_labels.txt",
     "@tflite_mobilenet_ssd//:mobilenet_ssd.tflite",
     "//tensorflow/contrib/lite/examples/android/app/src/main/assets:detect.tflite",
     "//tensorflow/contrib/lite/examples/android/app/src/main/assets:box_priors.txt",
     "//tensorflow/contrib/lite/examples/android/app/src/main/assets:labelmap.txt",
],`

step 2.
`private static final int TF_OD_API_INPUT_SIZE = 300;
private static final boolean TF_OD_API_IS_QUANTIZED = true;
private static final String TF_OD_API_MODEL_FILE = "detect.tflite";
private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/labelmap.txt";
`
Step 3. Building the apk 
bazel build -c opt --cxxopt='--std=c++11' "//tensorflow/contrib/lite/examples/android:tflite_demo".

However, it throws following conflict warnings.

`INFO: Analysed target //tensorflow/contrib/lite/examples/android:tflite_demo (64 packages loaded).
INFO: Found 1 target...
INFO: From Processing Android resources for //tensorflow/contrib/lite/examples/android:tflite_demo:
Aug 16, 2018 10:12:23 AM com.google.devtools.build.android.AndroidDataMerger doMerge
WARNING: 
CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
	external/tflite_mobilenet/WORKSPACE
	external/tflite_conv_actions_frozen/WORKSPACE

CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
	external/tflite_mobilenet_ssd/WORKSPACE
	external/tflite_conv_actions_frozen/WORKSPACE
Target //tensorflow/contrib/lite/examples/android:tflite_demo up-to-date:
  bazel-bin/tensorflow/contrib/lite/examples/android/tflite_demo_deploy.jar
  bazel-bin/tensorflow/contrib/lite/examples/android/tflite_demo_unsigned.apk
  bazel-bin/tensorflow/contrib/lite/examples/android/tflite_demo.apk
INFO: Elapsed time: 88.021s, Critical Path: 24.14s
INFO: 10 processes: 9 local, 1 worker.
INFO: Build completed successfully, 17 total actions`.

Attaching here the logcat file named android_build.txt




[android_build.txt](https://github.com/tensorflow/tensorflow/files/2292450/android_build.txt)

Thank you,

**Comment by achowdhery** [comment] 2018-08-18 15:00
Did it work with ssd_mobilenet_v1_coco?

**Comment by alokranjan007** [comment] 2018-08-19 05:52
Hi @achowdhery ,
Thank you for your response. I had not tried with ssd_mobilenet_v1_coco. But I had used ssd_mobilnet_v2_coco and it worked perfect on my device. Every apps are running perfectly fine for this case. However, when I am  trying to port the custom model using tflite; installed app is getting closed repeatedly. 

I was trying again. While converting from .pb file to tflite format, I used inference_type=FLOAT and made a change in the DetectorActivity.java file for `private static final boolean TF_OD_API_IS_QUANTIZED = false;`. After this I rebuild the apk and installed on my device. The app is installed, but after sometime (10 sec) it is getting closed again  with a message "TFLite Demo has stopped" close the app. Since, I have not changed anything for the Classifier and speech files, both are working fine. Only concern is with the Detection.

Please find the detailed steps below from converting frozen graph into the tflite format. (I retrained my model with my data set and have frozen_graph.pb files and labelmap.pbtxt). It may be noted here that I have not downloaded any tflite file from any source. 

Step 1:
`DETECT_PB=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/frozen_inference_graph.pb`
`STRIPPED_PB=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/frozen_inference_graph_stripped.pb`

step 2:
`cd $HOME/tensorflow-master`
`touch WORKSPACE`

step 3 :
`bazel build tensorflow/python/tools:optimize_for_inference && \
bazel-bin/tensorflow/python/tools/optimize_for_inference \
--input=$DETECT_PB \
--output=$STRIPPED_PB \
--frozen_graph=True \
--input_names=Preprocessor/sub \
--output_names=concat,concat_1 \
--alsologtostderr`

step 4:
`bazel run -c opt tensorflow/python/tools/optimize_for_inference -- \
--input=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/frozen_inference_graph.pb \
--output=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/frozen_inference_graph_stripped.pb \
--frozen_graph=True \
--input_names=Preprocessor/sub \
--output_names=concat,concat_1 \
--alsologtostderr`

step 5: Converting in tflite format
`bazel run -c opt //tensorflow/contrib/lite/toco:toco -- \
--input_file=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/frozen_inference_graph_stripped.pb \
--output_file=$HOME/tensorflow-master/models/research/object_detection/customized_model/inference_graph/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=Preprocessor/sub \
--output_arrays=concat,concat_1 --inference_type=FLOAT --logtostderr`

Let me know if you need any further information.

Thank you,

**Comment by jdduke** [comment] 2018-08-20 18:16
It looks like this is an issue with a mismatched Tensor + input buffer size.

When you use ByteBuffer as the input argument, you need to explicitly resize the input Tensor to match the size/shape of the ByteBuffer (assuming the runtime input size might differ from the default size expected by the model). See also https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L176.

The relevant error in the logs is 

> 08-16 10:26:42.107 28242 28257 E AndroidRuntime: FATAL EXCEPTION: inference
> 08-16 10:26:42.107 28242 28257 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 28242
> 08-16 10:26:42.107 28242 28257 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.

**Comment by alokranjan007** [comment] 2018-08-21 09:06
Hi @jdduke,

Thank you for your help and response. I could figure out the error in the log file. However, I am unable to fix this mismatch. Could you please suggest/share instructions about fixing this mismatch error.

I would appreciate your pain if you could share which file has to be changed for the FLOAT inference. Is the error is applicable to all models at tensorflow zoo directory which are not quantized? I had tried with ssd_mobilnet_v1_coco also, but the QUANTIZED_UINT8 is not working for the custom trained model.

Look forward to learn about this.

**Comment by jdduke** [comment] 2018-08-21 15:37
Just to confirm, for the FLOAT inference with the float model that you created, did you double check that `TF_OD_API_IS_QUANTIZED = false` is set in [DetectorActivity.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/android/app/src/main/java/org/tensorflow/demo/DetectorActivity.java#L53)? That should cause the ByteBuffer to be sized to 1080000 (300 * 300 * 3 * 4), whereas from the error message it looks to be using the quantized size (300 * 300 * 3).

**Comment by achowdhery** [comment] 2018-08-21 17:28
@alokranjan007 
In DetectorActivity.java if you have a float model, the following lines should be used to change the size:

  private static final boolean TF_OD_API_IS_QUANTIZED = false;
  private static final String TF_OD_API_MODEL_FILE = "detect.tflite";

This should automatically correct line 128 in TFLiteObjectDetectionAPIModel.java
// Pre-allocate buffers.
    int numBytesPerChannel;
    if (isQuantized) {
      numBytesPerChannel = 1; // Quantized
    } else {
      numBytesPerChannel = 4; // Floating point
    }

**Comment by alokranjan007** [comment] 2018-08-21 17:42
Hello @achowdhery,

Thank you for your reply. Yes, I had changed the mentioned lines in the DetectorActivity.Java filE ( This was mentioned in first response to your question). However, as mentioned for ssd_mobilenet_v2 the app is getting closed after 10 sec. 

I am currently training with the quantized model (the one from tensorflow zoo , ssd_mobilenet_v1_quantized). I will share the details with you people.

I wonder if one can convert float type model (for example ssd_mobilenet_v1_coco and ssd_mobilenet_v2_coco) into qunatized one by following some modifications in the scripts. Whats your suggestion?

**Comment by alokranjan007** [comment] 2018-08-21 17:45
Hi @jdduke,

Thanks for your help. I am currently training with the quantized model and will port the model on android. I will share the results soon for both float and quant inferences.

**Comment by alokranjan007** [comment] 2018-08-22 08:51
Hello @achowdhery @jdduke,

As mentioned in the previous comment, I trained ssd_mobilenet_v1_0.75_depth_quantized_coco model downloaded from the tensorflow zoo [Download Link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). I changed the config file for my custom classes and changed the paths for training and testing records. 

After the training I converted the frozen graph into .tflite format (as mentioned in the blog by @achowdhery and have also mentioned in the above comments). Unfortunately after the necessary changes also in the `DetectorActivity.java` file the installed app is getting closed. 

Note: Since the model i have downloaded is quantized, i used `inference_type=QUANTIZED_UINT8` but it threw errors as:

> Array FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Relu6, which is an input to the DepthwiseConv operator producing the output array FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results.
Aborted (core dumped).

Then I changed the `inference_type=FLOAT` and it created the `detect.tflite` file of size 12.4 Mb. I could not understand this particular reason. Due to this I changed 

> private static final boolean TF_OD_API_IS_QUANTIZED = false;
private static final String TF_OD_API_MODEL_FILE = "detect.tflite";
after this also the installed detect app is getting stopped again and again.

Could you help me to understand why such behavior of qunatized model. 

I am attaching here my `pipeline.config` file used for train the model. I have used 2500 training steps.

> model {
  ssd {
    inplace_batchnorm_update: true
    freeze_batchnorm: false
    num_classes: 5
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    encode_background_as_zeros: true
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        class_prediction_bias_init: -4.6
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            random_normal_initializer {
              stddev: 0.01
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.97,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 0.75
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.97,
          epsilon: 0.001,
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    loss {
      classification_loss {
        weighted_sigmoid_focal {
          alpha: 0.75,
          gamma: 2.0
        }
      }
      localization_loss {
        weighted_smooth_l1 {
          delta: 1.0
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    normalize_loc_loss_by_codesize: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}
train_config: {
  fine_tune_checkpoint: "/home/alok/tensorflow_master/models/research/object_detection/ssd_mobilenet_v1_0.75_quantized/model.ckpt"
  fine_tune_checkpoint_type:  "detection"
  batch_size: 24
  sync_replicas: true
  startup_delay_steps: 0
  replicas_to_aggregate: 8
  num_steps: 2500
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
  optimizer {
    momentum_optimizer: {
      learning_rate: {
        cosine_decay_learning_rate {
          learning_rate_base: 0.7
          total_steps: 2500
          warmup_learning_rate: 0.3
          warmup_steps: 50
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
}
train_input_reader: {
  tf_record_input_reader {
    input_path: "/home/alok/tensorflow_master/models/research/object_detection/customized_model/train.record"
  }
  label_map_path: "/home/alok/tensorflow_master/models/research/object_detection/customized_model/training/label_map.pbtxt"
}
eval_config: {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
  num_examples: 81
}
eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/alok/tensorflow_master/models/research/object_detection/customized_model/test.record"
  }
  label_map_path: "/home/alok/tensorflow_master/models/research/object_detection/customized_model/training/label_map.pbtxt"
  shuffle: false
  num_readers: 1
}


Please share you expertise. Let me know if any further information or file is needed.


Thank you,

**Comment by alokranjan007** [comment] 2018-08-23 11:28
Hi @achowdhery @jdduke: I have resolved the error with the inference type, but now facing other problem.


 Could you please help me regarding the results of the trained model. 

I trained two different models from tensorflow zoo directory named `ssd_mobilenet_v1_0.75_depth_quantized_coco` and `ssd_mobilenet_v1_quantized_coco` each with 10000 training steps. I had changed the no of classes to 5 (for my data set) and used a batch size of 10 for both the models. However, the total no of of images are limited to 205.


Both the model trained well with all files generated. I tested the trained model using webcam and it worked perfectly fine.

As a next step, I used your blog [Link here](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) and converted the .pb file into `.tflite` format. The generated `detect.tflite` is of size 3.2 Mb (This is what you have also suggested in the blog that the file should be less than 4 Mb). However, after build over android device, there is no detection at all.

I tried to hold it for at least 2 minutes for each classes (by showing images of each class), but there is no result in detection. It did not even overfit of showed any false detections. 


What I have done wrong? Please share your thoughts. 

I am trying with both the models but no luck at all. I wonder the same model (frozen graph) is working perfectly fine for webcam based detection.

Thank you,

**Comment by alokranjan007** [comment] 2018-08-27 09:16
Hi @jdduke,
Since the quantized model is not detecting any thing after building over android. I tried my luck with `ssd_mobilenet_v2_coco` model. I  trained the model for 20000 training steps. 

Then, I converted the trained model to get a frozen graph using `export_tflite_ssd_graph` then converted the .pb file into `tflite`. 

I followed your suggestion and have used `inference_type=FLOAT` and made a change accordingly in the DetectorActivity.java file i.e. `private static final boolean TF_OD_API_IS_QUANTIZED = false;`.

Then i build it over phone. The detector app is installed.  But the concern is the app is getting crashed after a minute. It shows the detection, but getting crashed.

I used the logcat and found a fatal error about 

> 08-27 12:13:54.129 11179 11208 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 602112 bytes.


I am not getting I have used float inference and have changed the detector file also then why this is throwing such error.

Note: For configuration I had used image size as 300 and 300. But learning from the log file it is taking somewhere (224*224*3*4=602112). For the conversion also I had used `--input_shapes=1,300,300,3`.

I am attaching the txt file for your perusal.
[ssd_mobilenet_v2_27_Aug.txt](https://github.com/tensorflow/tensorflow/files/2323215/ssd_mobilenet_v2_27_Aug.txt)

Could you please share your views on this? How should I rectify this?

Thank you for your help.

**Comment by alokranjan007** [comment] 2018-08-30 08:53
Hello all, is there any update ?

**Comment by jdduke** [comment] 2018-08-30 15:16
Right, the problem is that the model expects a buffer of shape 300x300x3, but you're feeding it an image buffer of shape 224x224x3. The shape has to match exactly. You need to crop/resize your image to 300x300 first.

**Comment by alokranjan007** [comment] 2018-08-30 15:28
@jdduke  I completely agree with you. Correct me if I am wrong, the image_resizer will take care of the size of the input image? 

If this is the case then the one should not train the model with large input size for eg. 512*512? 
Does it mean that if you have a image size other than 300*300 then you have to resize it manually and then use as training and testing data set?

Thank you,

**Comment by alokranjan007** [comment] 2018-08-30 16:16
@jdduke Thank you so much for your prompt reply. I am excited to know more details from @achowdhery about this image input.  I wonder if we  could handle this dynamically.  Do all ssd_mobilnet models on the tensorflow zoo directory is strictly limited to 300x300 image size?

**Comment by alokranjan007** [comment] 2018-09-07 06:12
Hey @jdduke,  I would appreciate your pain, if you could share some insights about the input image size for training and annotations. I have followed the tutorial about data processing available in the object detection API, but could not find about the image size for SSD_mobilenet_v2.

**Comment by jdduke** [comment] 2018-09-07 15:03
I don't believe the image_resizer gets backed into the model, so you need to make sure that 1) you're training on the same size that you feed into --input_shapes, and that the dimensions you give to --input_shapes match that specified in [TF_OD_API_INPUT_SIZE](https://github.com/tensorflow/tensorflow/blob/b390be62ad0514f4fd3347b9db3446c84e08a38e/tensorflow/contrib/lite/examples/android/app/src/main/java/org/tensorflow/demo/DetectorActivity.java#L52)

**Comment by tensorflowbutler** [comment] 2018-09-22 12:39
Nagging Assignees @jdduke, @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-09-27 18:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-09-27 18:41 UTC
Labels: comp:lite, stat:awaiting response

**Comment by M1thun** [comment] 2019-01-21 16:52
Hello guys!! I am facing same issue with TFL detect app.
I trained ssd mobilenet v2 for my custom dataset for 5 classes.
The TFL detect app is getting crashed by showing the bug mentioned below.Please help me out..

java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.
	at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:251)
	at org.tensorflow.lite.Tensor.setTo(Tensor.java:110)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:145)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
	at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:193)
	at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:247)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by achowdhery** [comment] 2019-01-22 14:45
@M1thun Please ensure that input data type Quantized/Float in the app matches the model you have provided.  This seems to be data type mismatch at input

**Comment by M1thun** [comment] 2019-01-22 15:00
yeah thanks!! @achowdhery  i was able to resolve this issue

**Comment by corlov** [comment] 2019-02-11 17:11
Hi all!
I use inception_v3 model in a simple app for smartphone (Android OS).
An input images have an arbitrary sizes and I have some trouble and confuse.

tflite.run(imgData, labelProbArray);

This instruction generates the exception:
```
W/System.err: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 602112 bytes and a ByteBuffer with 338688 bytes.
W/System.err:     at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:221)
                  at org.tensorflow.lite.Tensor.setTo(Tensor.java:93)
                  at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:136)
                  at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
                  at org.tensorflow.lite.Interpreter.run(Interpreter.java:195)
                  at com.example.root.neuralnetworks01.MainActivity.classifyFrame(MainActivity.java:239)
                  at com.example.root.neuralnetworks01.MainActivity$2.onClick(MainActivity.java:169)
```
I suppose an author of the model has created a config file and written something like I wrote bellow:

   ```
 image_resizer {
        fixed_shape_resizer {
                width: 224
                height: 224
        }
    }
```
Do I understand it right?
I think so because 602112 = 224 * 224 * 3 * 4
Therefore I can't use this tflite-file for images with size other than 224*224 pixels. Am I right?
Thank you!

**Comment by jdduke** [comment] 2019-02-11 17:40
> Therefore I can't use this tflite-file for images with size other than 224*224 pixels. Am I right?

You can, but you'll need to manually crop and resize them first. You can look at our samples as a guide for doing this, either by way of [TextureView](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/Camera2BasicFragment.java#L824) or directly with a [Canvas transform](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/ClassifierActivity.java#L110).

**Comment by corlov** [comment] 2019-02-11 18:30
Thanks.

**Comment by inakaaay** [comment] 2019-04-27 13:26
how did you solve the problem with  Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.? @M1thun ?

**Comment by M1thun** [comment] 2019-04-27 15:26
> how did you solve the problem with Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.? @M1thun ?

@inakaaay  this error occur because of mismatch in the input shape given to the model.

**Comment by syedrz** [comment] 2019-08-15 05:23
> Hi @jdduke and @achowdhery ,
> Since the quantized model is not detecting any thing after building over android. I tried my luck with `ssd_mobilenet_v2_coco` model. I trained the model for 20000 training steps.
> 
> Then, I converted the trained model to get a frozen graph using `export_tflite_ssd_graph` then converted the .pb file into `tflite`.
> 
> I followed your suggestion and have used `inference_type=FLOAT` and made a change accordingly in the DetectorActivity.java file i.e. `private static final boolean TF_OD_API_IS_QUANTIZED = false;`.
> 
> Then i build it over phone. The detector app is installed. But the concern is the app is getting crashed after a minute. It shows the detection, but getting crashed.
> 
> I used the logcat and found a fatal error about
> 
> > 08-27 12:13:54.129 11179 11208 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 602112 bytes.
> 
> I am not getting I have used float inference and have changed the detector file also then why this is throwing such error.
> 
> Note: For configuration I had used image size as 300 and 300. But learning from the log file it is taking somewhere (224 _224_ 3* 4=602112). For the conversion also I had used `--input_shapes=1,300,300,3`.
> 
> I am attaching the txt file for your perusal.
> [ssd_mobilenet_v2_27_Aug.txt](https://github.com/tensorflow/tensorflow/files/2323215/ssd_mobilenet_v2_27_Aug.txt)
> 
> Could you please share your views on this? How should I rectify this?
> 
> Thank you for your help.
==================
----Error is----
 E AndroidRuntime: FATAL EXCEPTION: inference
 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 6556
 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 5
-----Solution-----
Solved by Adding a "???" string inside my Label file, it seems that the App follows the pbtxt format of having the first ID which is 1.
===================

**Comment by rash1994** [comment] 2019-09-01 13:55
> > Hi @jdduke and @achowdhery ,
> > Since the quantized model is not detecting any thing after building over android. I tried my luck with `ssd_mobilenet_v2_coco` model. I trained the model for 20000 training steps.
> > Then, I converted the trained model to get a frozen graph using `export_tflite_ssd_graph` then converted the .pb file into `tflite`.
> > I followed your suggestion and have used `inference_type=FLOAT` and made a change accordingly in the DetectorActivity.java file i.e. `private static final boolean TF_OD_API_IS_QUANTIZED = false;`.
> > Then i build it over phone. The detector app is installed. But the concern is the app is getting crashed after a minute. It shows the detection, but getting crashed.
> > I used the logcat and found a fatal error about
> > > 08-27 12:13:54.129 11179 11208 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 602112 bytes.
> > 
> > 
> > I am not getting I have used float inference and have changed the detector file also then why this is throwing such error.
> > Note: For configuration I had used image size as 300 and 300. But learning from the log file it is taking somewhere (224 _224_ 3* 4=602112). For the conversion also I had used `--input_shapes=1,300,300,3`.
> > I am attaching the txt file for your perusal.
> > [ssd_mobilenet_v2_27_Aug.txt](https://github.com/tensorflow/tensorflow/files/2323215/ssd_mobilenet_v2_27_Aug.txt)
> > Could you please share your views on this? How should I rectify this?
> > Thank you for your help.
> > ==================
> > ----Error is----
> > E AndroidRuntime: FATAL EXCEPTION: inference
> > E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 6556
> > E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 5
> > -----Solution-----
> > Solved by Adding a "???" string inside my Label file, it seems that the App follows the pbtxt format of having the first ID which is 1.
> > ===================

hie 
could you solve it somehow?
I followed the same process just for moilenetV1. I is getting crashed.
