### ISSUE TITLE
Unexpected warning during GeneratorDataset iterator finalization

### ISSUE THREAD

**Issue by selitvin** [tensorflow/tensorflow#24570] opened 2018-12-26 07:54 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `('v1.12.0-0-ga6d8ffae09', '1.12.0')`
- Python version: 2.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M2000M       Off  | 00000000:01:00.0  On |                  N/A |
| N/A   57C    P0    N/A /  N/A |    832MiB /  4043MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
```

**Describe the current behavior**
When using `from_generator` to create a `tf.data.Dataset` instance, reading from a one_shot_iterator and not explicitly closing the session object, I observe a warning: 
```
 W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
```

**Describe the expected behavior**
Would expect the program to finish without a warning.

**Code to reproduce the issue**
```
import itertools

import tensorflow as tf

def gen():
    for i in itertools.count(1):
        yield (i, [1] * i)

ds = tf.data.Dataset.from_generator(
    gen, (tf.int64, tf.int64), (tf.TensorShape([]), tf.TensorShape([None])))

iterator = ds.make_one_shot_iterator()

sess = tf.Session()
iterator = iterator.get_next()

sess.run(iterator)
# sess.close()   <-- no warning is shown if closing the session explicitly
```

**Other info / logs**
```
2018-12-25 23:43:21.645869: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-25 23:43:21.684610: W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64], token="pyfunc_2"](arg0)]]
```

**Comment by alsrgv** [comment] 2018-12-26 09:13
I'm experiencing a very similar issue with Keras API:
```python
import itertools
import tensorflow as tf
import tensorflow.keras.backend as K

config = tf.ConfigProto(device_count={'GPU': 0})
K.set_session(tf.Session(config=config))

def train_fn():
    i = tf.keras.layers.Input(shape=(1,))
    x = tf.keras.layers.Dense(100, activation='relu')(i)
    o = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.Model(i, o)
    model.compile('adam', 'mae')

    def gen():
        for i in itertools.count(1):
            yield [float(i)], [float(i)]

    ds = tf.data.Dataset.from_generator(
        gen, (tf.float32, tf.float32), (tf.TensorShape([1]), tf.TensorShape([1])))

    model.fit(ds, steps_per_epoch=10)

train_fn()
```

Oddly, if I in-line `train_fn()` or register model globally (e.g. via `globals()['_model'] = model`), the warning goes away.

Affects uber/horovod#606.

**Comment by alsrgv** [comment] 2018-12-26 09:14
cc @mrry

**Comment by feihugis** [comment] 2019-01-24 20:05
@selitvin @alsrgv I could not reproduce the warning on tf-nightly (1.13.0.dev20190124).

**Comment by pwais** [comment] 2019-06-23 20:03
Is this fixed in TF 1.14?

**Comment by alsrgv** [comment] 2019-07-01 07:59
I can still reproduce this issue in TF 1.14.0.

**Comment by zh794390558** [comment] 2019-07-22 04:53
Same problem when using tf1.14.

**Comment by jsimsa** [comment] 2019-07-22 17:25
@rachellim can you please take a look?

**Comment by jvishnuvardhan** [comment] 2019-07-26 20:41
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by bionicles** [comment] 2019-08-15 14:46
@jvishnuvardhan we have this issue in 2.0b1

**Comment by jvishnuvardhan** [comment] 2019-08-15 16:35
@bionicles Could you open a new issue by filling issue template and also provide a standalone code to reproduce the issue? As the origianal issue with TF1.x was resolved, it is better to open a new issue so that it will help the community that are using TF2.0. Thanks!

**Comment by zhidaole** [comment] 2020-06-23 07:08
I meet the same problem in tf 2.2 and python 3.6

**Comment by rachellim** [comment] 2020-06-23 16:58
@zhidaole, you can share a code snippet so we can reproduce this issue?

**Comment by Manoj-M-97** [comment] 2020-06-23 22:24
> I meet the same problem in tf 2.2 and python 3.6

I have the same issue as well

**Comment by rachellim** [comment] 2020-06-24 18:06
@Manoj-M-97 can you share a code snippet to reproduce the issue? Thanks.

**Comment by TonyD-BME** [comment] 2020-07-30 20:05
I'm having the same issue using TF 2.2.0 and Python 3.8.4. I'm trying to run a simplified convnet with the following code:

```python
import numpy as np
import tensorflow as tf
from tensorflow import keras
import os
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D, MaxPooling2D
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

train_path = os.path.join(os.path.dirname(__file__), "./CNN Data/Training Set")
valid_path = os.path.join(os.path.dirname(__file__), "./CNN Data/Validation Set")
test_path = os.path.join(os.path.dirname(__file__), "./CNN Data/Testing Set")

train_batches = ImageDataGenerator().flow_from_directory(train_path, target_size=(251,388), classes=['Cortex','Medulla', 'Pelvis'], batch_size=6)
valid_batches = ImageDataGenerator().flow_from_directory(valid_path, target_size=(251,388), classes=['Cortex','Medulla', 'Pelvis'], batch_size=7)
test_batches = ImageDataGenerator().flow_from_directory(test_path, target_size=(251,388), classes=['Cortex','Medulla', 'Pelvis'], batch_size=7)

model = keras.Sequential([
    Conv2D(64, (3,3), strides=(1, 1), activation='relu', padding='same', input_shape=(251,388, 1)),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'),
    Flatten(),
    Dense(3, activation='softmax')
])

EPOCHS = 20
INIT_LR = 0.001

model.compile(Adam(learning_rate=INIT_LR), loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(
    train_batches, steps_per_epoch=4, epochs=EPOCHS, verbose=1,
    validation_data=valid_batches, validation_steps=18
)
```

Running the above code yields the following error message:

> tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
         [[node sequential/conv2d/Conv2D (defined at c:/Users/adonaldson/Documents/Tang Lab/TinyNet/Reproduce the Error.py:43) ]] [Op:__inference_train_function_684]
> 
> Function call stack:
> train_function
> 
> 2020-07-30 14:39:37.905975: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
>          [[{{node PyFunc}}]]

**Comment by SarfarazHabib** [comment] 2020-09-10 18:50
Hi Any luck on this issue, I am having the same error.

**Comment by emoen** [comment] 2020-10-09 08:46
same error here:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[12,1632,12,12] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node functional_1/block6h_dwconv/depthwise (defined at train_cod.py:149) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_36493]

Errors may have originated from an input operation.
Input Source operations connected to node functional_1/block6h_dwconv/depthwise:
 functional_1/block6h_expand_activation/mul (defined at /usr/local/lib/python3.6/dist-packages/efficientnet/model.py:115)

Function call stack:
train_function

2020-10-09 08:28:48.954550: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.

**Comment by rachellim** [comment] 2020-10-09 19:17
@emoen , I'd suspect that your issue is something different - looks like your error is an OOM with tensor allocation, and the GeneratorDataset warning is a red herring.

**Comment by karliell** [comment] 2021-04-11 00:19
I have the same error

**Comment by sachinprasadhs** [comment] 2021-05-20 18:04
@selitvin , I was able to run your code without any warning in Tensorflow 2.5 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/2d8c26de036ca88f3b6e05760eb21387/24570.ipynb).

**Comment by sachinprasadhs** [comment] 2021-05-20 18:06
Closing the issue since it is not showing any error in the recent Tensorflow version, if you face any issue again feel free to open new issue by filling the issue template. Thanks!

**Closed by sachinprasadhs** 2021-05-20 18:06 UTC
Labels: comp:data, type:bug

**Comment by ai-rafique** [comment] 2021-06-17 13:45
To anyone experiencing the same error, I was training a multi class network and got this error on the first epoch.
My problem was that the classes I needed to predict were 3 but in the last layer I had written 7 for some reason.
Prediction classes =/= Output nodes count made my error.
