### ISSUE TITLE
build android 

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#12166] opened 2017-08-10 07:55 UTC
ERROR: /home/wangmeng/RSTensorFlow_mobile/tensorflow/examples/android/BUILD:67:1: Building tensorflow/examples/android/libtensorflow_demo.jar (23 source files) failed: Worker process sent response with exit code: 1.
tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java:365: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    inferenceInterface = new TensorFlowInferenceInterface(getAssets(), MODEL_FILE);
                         ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java:544: error: cannot find symbol
    inferenceInterface.feed(
                      ^
  symbol:   method feed(String,float[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java:546: error: cannot find symbol
    inferenceInterface.feed(STYLE_NODE, styleVals, NUM_STYLES);
                      ^
  symbol:   method feed(String,float[],int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java:548: error: cannot find symbol
    inferenceInterface.run(new String[] {OUTPUT_NODE}, isDebug());
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java:549: error: cannot find symbol
    inferenceInterface.fetch(OUTPUT_NODE, floatValues);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java:90: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    c.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java:93: error: cannot find symbol
    final Operation operation = c.inferenceInterface.graphOperation(outputName);
                                                    ^
  symbol:   method graphOperation(String)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java:132: error: cannot find symbol
    inferenceInterface.feed(inputName, floatValues, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,float[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java:137: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java:142: error: cannot find symbol
    inferenceInterface.fetch(outputName, outputs);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowMultiBoxDetector.java:90: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    d.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowMultiBoxDetector.java:221: error: cannot find symbol
    inferenceInterface.feed(inputName, floatValues, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,float[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowMultiBoxDetector.java:226: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowMultiBoxDetector.java:233: error: cannot find symbol
    inferenceInterface.fetch(outputNames[0], outputLocationsEncoding);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowMultiBoxDetector.java:234: error: cannot find symbol
    inferenceInterface.fetch(outputNames[1], outputScoresEncoding);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:68: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    d.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:98: error: cannot find symbol
    inferenceInterface.feed(inputName, bytePixels, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,byte[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:105: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:114: error: cannot find symbol
    inferenceInterface.fetch(outputNames[3], numDetectionsArray);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:119: error: cannot find symbol
    inferenceInterface.fetch(outputNames[0], boxes);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:120: error: cannot find symbol
    inferenceInterface.fetch(outputNames[1], scores);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowSingleShotDetector.java:121: error: cannot find symbol
    inferenceInterface.fetch(outputNames[2], classes);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java:107: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    d.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java:154: error: cannot find symbol
    inferenceInterface.feed(inputName, floatValues, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,float[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java:161: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java:172: error: cannot find symbol
    inferenceInterface.fetch(outputNames[0], output);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 19.243s, Critical Path: 7.19s
FAILED: Build did NOT complete successfully

**Comment by andrewharp** [comment] 2017-08-10 19:00
Please add the info requested for the bug report so we can have some context how you got this, thanks.

**Comment by wm901115nwpu** [comment] 2017-08-14 03:42
I use bazel 0.5.3, but the branch requires 0.4.2

**Comment by reedwm** [comment] 2017-08-14 17:38
Please fill out the entire [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

**Comment by gunan** [comment] 2017-09-03 06:51
Closing due to lack of debugging information.
If you are still seeing this problem, please fill out all of the fields in the template we provide for new issues.

**Comment by Talor-A** [comment] 2017-09-14 22:48
@gunan I believe I'm having the same problem. here's my issue report, could this get reopened?
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, but the error occurs in the example `TensorFlowImageClassifier.java` file
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from**: android library binary (only using tensorflow on android, not in python)
- **TensorFlow version (use command below)**: n/a
- **Python version**: n/a
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
the problem appears to be in the `TensorFlowInferenceInterface` interface.

error log: 
```
/home/ta/git/MLtest/node_modules/react-native-machine-learning/android/src/main/java/com/reactlibrary/TensorFlowImageClassifier.java:97: error: constructor TensorFlowInferenceInterface in class TensorFlowInferenceInterface cannot be applied to given types;
    c.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFilename);
                           ^
  required: no arguments
  found: AssetManager,String
  reason: actual and formal argument lists differ in length
```

code in question: see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java) line 103 for the constructor in question.

I can get past this by replacing the line with this code: 

```
c.inferenceInterface = new TensorFlowInferenceInterface();
c.inferenceInterface.initializeTensorFlow(assetManager, modelFilename);
```

but then I'm left with these errors, which makes me think that something else is causing these problems:

```
/home/ta/git/MLtest/node_modules/react-native-machine-learning/android/src/main/java/com/reactlibrary/TensorFlowImageClassifier.java:101: error: cannot find symbol
    final Operation operation = c.inferenceInterface.graphOperation(outputName);
                                                    ^
  symbol:   method graphOperation(String)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
/home/ta/git/MLtest/node_modules/react-native-machine-learning/android/src/main/java/com/reactlibrary/TensorFlowImageClassifier.java:140: error: cannot find symbol
    inferenceInterface.feed(inputName, floatValues, 1, inputSize, inputSize, 3);
                      ^
  symbol:   method feed(String,float[],int,int,int,int)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
/home/ta/git/MLtest/node_modules/react-native-machine-learning/android/src/main/java/com/reactlibrary/TensorFlowImageClassifier.java:145: error: cannot find symbol
    inferenceInterface.run(outputNames, logStats);
                      ^
  symbol:   method run(String[],boolean)
  location: variable inferenceInterface of type TensorFlowInferenceInterface
/home/ta/git/MLtest/node_modules/react-native-machine-learning/android/src/main/java/com/reactlibrary/TensorFlowImageClassifier.java:150: error: cannot find symbol
    inferenceInterface.fetch(outputName, outputs);
                      ^
  symbol:   method fetch(String,float[])
  location: variable inferenceInterface of type TensorFlowInferenceInterface
4 errors

```

### Source code / logs
I can include more code if necessary, but I'm attempting to use tensorflow in a react-native project so it might be difficult to provide a bare minimum example.

**Comment by gunan** [comment] 2017-09-14 22:51
@Talor-A thanks for the information.
Bug reopened.

**Comment by Talor-A** [comment] 2017-09-14 22:52
update: I noticed the `TensorFlowInterferenceInterface` class [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java) has a constructor that takes AssetManager and ModelFile as arguments, is it possible I'm using an outdated version?

**Comment by andrewharp** [comment] 2017-09-14 23:12
@taylor-a Yes, a version mismatch is the most likely culprit. Are you using a hardcoded version of the AAR (specified in build.gradle)?

**Comment by Talor-A** [comment] 2017-09-14 23:31
@andrewharp no, I manually added `libandroid_tensorflow_inference_java.jar` and the other `.so` files to my `libs/` folder, and this to `build.gradle`:
```
android {
    ...
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.facebook.react:react-native:+'
}
```
Is there a way I can install the library automatically in build.gradle?

**Comment by andrewharp** [comment] 2017-09-14 23:45
Ok, it sounds like you grabbed an older version of libandroid_tensorflow_inference_java.jar than the demo code you're compiling against. Where did you find the file?

To use the AAR you can add this to your gradle config:
```
allprojects {
    repositories {
        jcenter()
    }
}

dependencies {
    compile 'org.tensorflow:tensorflow-android:+'
}
```

You can (and should) replace the + with a known compatible version number of TensorFlow.

**Comment by Talor-A** [comment] 2017-09-15 22:03
thanks, that solved it @andrewharp .

**Closed** 2017-10-11 22:23 UTC
Labels: stat:awaiting tensorflower, type:build/install
