### ISSUE TITLE
Entity <function pfor.<locals>.f at 0x644d84950> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team

### ISSUE THREAD

**Issue by dmitry-kabanov** [tensorflow/tensorflow#36731] opened 2020-02-13 16:54 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.6 (18G2022)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: binary, from Anaconda
- **TensorFlow version (use command below)**: unknown 1.14.0
- **Python version**: 3.7.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: cudatoolkit-9.0
- **GPU model and memory**: not used
- **Exact command to reproduce**: run the attached script `get_partial_derivatives.py`.

### Describe the problem
I ran into a bug when I run the following small code:

```python
import tensorflow as tf
tf.enable_v2_behavior()

input = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
w = tf.Variable([[1.0, 7.0], [3.0, 5.0]])

with tf.GradientTape(persistent=True) as t:
    f = tf.matmul(input, tf.transpose(w))

print("f:")
print(f)

print("Derivative:")
print(t.jacobian(f, input))
```

### Source code / logs
Log of the error:

```
WARNING:tensorflow:Entity <function pfor.<locals>.f at 0x644d84950> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function pfor.<locals>.f at 0x644d84950>: AssertionError: Bad argument number for Name: 3, expecting 4
```

The full log (with AUTOGRAPH_VERBOSITY=10) is attached.

[get_partial_derivatives.py.txt](https://github.com/tensorflow/tensorflow/files/4199640/get_partial_derivatives.py.txt)
[logfile.txt](https://github.com/tensorflow/tensorflow/files/4199641/logfile.txt)

**Comment by Saduf2019** [comment] 2020-02-14 05:43
@dmitry-kabanov I have executed the code provided by you [on 1.14 as mentioned in by you] and do not find any warning/issue faced by you, please find the gist here for the same[.](https://colab.sandbox.google.com/gist/Saduf2019/3365818269fe056f5fae5b39f737d9fe/36731.ipynb)

if you still face an issues please share a gist of the issue.

**Comment by dmitry-kabanov** [comment] 2020-02-14 12:05
Well, I do not know how to explain it. I can see this bug but I have Tensorflow provided by Anaconda distribution.

If it is irreproducible, then should I close it?

**Comment by Saduf2019** [comment] 2020-02-17 11:42
@dmitry-kabanov could you please install tensorflow using pip and try on virtual environment, let us know if that helps resolve the issue.

**Comment by dmitry-kabanov** [comment] 2020-02-17 12:30
@Saduf2019 I installed Python 3.7 via conda in a conda environment and install tensorflow and all dependencies via `pip`. I still get the same issue. Please see the attached logfile.

My version of Python is `3.7.6 h359304d_2`.

[logfile.txt](https://github.com/tensorflow/tensorflow/files/4213714/logfile.txt)

**Comment by Saduf2019** [comment] 2020-02-18 06:05
@dmitry-kabanov 
Can you please refer to [link](https://github.com/tensorflow/tensorflow/issues/32859) where workaround is working by installing gast ( pip install gast==0.2.2).
let us know if that helps.

**Comment by dmitry-kabanov** [comment] 2020-02-21 14:18
Somehow I replied three days ago but my last comment is not here.

I confirm that the workaround works. Installing gast 0.2.2 removed gast 0.3.3 and then it worked correctly.

```
~/dev/2020-02-17-tensorflow-jacobian-bug via 🅒 /Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env
➜ pip install "gast==0.2.2"
Processing /Users/dima/Library/Caches/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd/gast-0.2.2-cp37-none-any.whl
Installing collected packages: gast
  Attempting uninstall: gast
    Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
Successfully installed gast-0.2.2

~/dev/2020-02-17-tensorflow-jacobian-bug via 🅒 /Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env took 2s
➜ python get_partial_derivatives.py
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/dima/dev/2020-02-17-tensorflow-jacobian-bug/conda-env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From get_partial_derivatives.py:2: The name tf.enable_v2_behavior is deprecated. Please use tf.compat.v1.enable_v2_behavior instead.

2020-02-18 12:33:29.302126: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
f:
tf.Tensor(
[[15. 13.]
 [31. 29.]], shape=(2, 2), dtype=float32)
Derivative:
tf.Tensor(
[[ 4. 12.]
 [ 4. 12.]], shape=(2, 2), dtype=float32)
Jacobian:
tf.Tensor(
[[[[1. 7.]
   [0. 0.]]

  [[3. 5.]
   [0. 0.]]]


 [[[0. 0.]
   [1. 7.]]

  [[0. 0.]
   [3. 5.]]]], shape=(2, 2, 2, 2), dtype=float32)
```

**Comment by Saduf2019** [comment] 2020-02-24 05:57
@dmitry-kabanov Moving this issue to resolved status and as the issue is resolved.

**Closed by Saduf2019** 2020-02-24 05:57 UTC
Labels: TF 1.14, comp:autograph, type:support
