### ISSUE TITLE
4D and higher dimensional convolutional layers

### ISSUE THREAD

**Issue by alexgkendall** [tensorflow/tensorflow#9513] opened 2017-04-28 14:49 UTC
Are there any plans to implement 4D or higher convolutional layers?

**Comment by aselle** [comment] 2017-04-28 15:36
Not that I am aware of.  Conv2d's are clearly used a ton and Conv3ds much less so. What kinds of applications do you have in mind. Do you have any intention to work on them yourself?

**Comment by alexgkendall** [comment] 2017-04-28 15:46
The specific research is unpublished but it is for computer vision. They fundamentally require 4-D convolution and it would be great to get them working in TF. I understand cudnn supports this so i thought it might not be too much effort for someone in the bowels of it to implement it.

**Comment by aselle** [comment] 2017-04-28 20:34
It probably isn't a ton of effort, but we are not working on it currently, so I'm leaving it as contributions welcome, in case anybody wants to work on it. Thanks for bringing it up. @zheng-xq, confirming that we don't have any effort.

**Comment by alexgkendall** [comment] 2017-05-02 21:23
@aselle I'm thinking of giving this a go myself, would you please be able to detail the steps to doing this?

**Comment by aselle** [comment] 2017-05-03 17:50
Best way is to look at another op that is similar (like conv). Try to get a prototype working quickly and submit a draft pull request. @martinwicke, do we have a design document process yet?

**Comment by martinwicke** [comment] 2017-05-03 19:07
We don't. I think since this is a straightforward extension of existing ops, I don't think there's a huge design space to consider anyway. I'd guess it would go into contrib first, although if it is basically parallel to the 3D ops, we may just add them to core directly.

**Comment by bhack** [comment] 2017-05-04 10:23
Is it a duplicate of https://github.com/tensorflow/tensorflow/issues/1661?

**Comment by bhack** [comment] 2017-05-04 10:28
@alexgkendall I don't know if you [can divulgate](https://github.com/tensorflow/tensorflow/issues/9513#issuecomment-298033948) this info but is this for a follow up of GC-NET?

**Comment by girving** [comment] 2017-06-16 21:10
I think this is unlikely to happen in a way that makes anyone happy, so closing. All applications of 4D convs that I know of will almost certainly be forced to use special factorizations for efficiency.

**Closed by girving** 2017-06-16 21:10 UTC
Labels: stat:awaiting tensorflower, type:feature

**Comment by QuntuamLoop** [comment] 2018-01-05 10:31
@aselle  I think the high dimention in dataset is a good application. You can see about the future computer vision have the colorful 3-D sight in the time series. [batch, [x,y,z ],rgb-channel, time]

**Comment by bhack** [comment] 2018-04-14 13:01
I think that we can investigate to expand [separable approachs](https://github.com/tensorflow/tensorflow/issues/6437). 
What do you think?

**Comment by funkey** [comment] 2018-05-15 10:34
By the way, this issue is a duplicate of https://github.com/tensorflow/tensorflow/issues/1661.

**Comment by shuyiii** [comment] 2018-10-30 15:57
My research really needs layers for arbitrary dimensional data, I'm not a good engineer while my advisor tells me to write n dimensional convolutional layer by myself, anyone has experience? I know it might need to first define a n dimensional tensor and rewrite all the architectures, Thanks...

**Comment by OrodRazeghi** [comment] 2019-11-26 13:37
@funkey thank you for sharing a nice clean implementation of a 4D conv layer in tensorflow. I was wondering if you could help me with the transpose version of this 4D conv layer. How would that look like in this implementation? Also, do you think your suggested 4D conv can be used for image+time data, where the image is 3D and the 4th dimension is time?

**Comment by funkey** [comment] 2019-11-27 21:19
A transposed convolution version of `conv4d` would be great. Happy to review your solution.

Yes, all our use cases are 3D+t.

**Comment by OrodRazeghi** [comment] 2019-12-03 15:14
@funkey thanks for your response. Do you have any suggestions on how the transpose would look like in your implementation? It seems that in the case of conv4d, frame_results is the output and is the result of summing the convolution of the current input frame with its previous kernel frame. The reverse would be the result of summing the 3D transpose layers? or there is more to it? any comments will be very appreciated, thanks.
