### ISSUE TITLE
Using a `tf.Tensor` as a Python `bool` is not allowed

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#29823] opened 2019-06-15 12:30 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): official site
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory:

**Describe the current behavior**
I built a custom activation function in Keras' and call tf functions. When I call the custom function, I encountered error:

  TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

The line of code where the error happened is this one
`  inputs = tf.where(orig > 0 and orig <= 0.25, 0.25 / (1+K.exp(-self.sharp*((inputs-0.125)/0.5))), inputs)`
**Describe the expected behavior**
I tested all variables, all of them are tf.Tensor
**Code to reproduce the issue**
`import tensorflow as tf

class QPWCX(Layer):

    def __init__(self, sharp=100, **kwargs):
        super(QPWCX, self).__init__(**kwargs)
        self.supports_masking = True
        self.sharp = K.cast_to_floatx(sharp)

    def call(self, inputs):
        orig = inputs
        inputs = tf.where(orig <= 0, tf.zeros_like(inputs), inputs)
        inputs = tf.where(orig > 0 and orig <= 0.25, 0.25 / (1+K.exp(-self.sharp*((inputs-0.125)/0.5))), inputs)
        inputs = tf.where(orig > 0.25 and orig <= 0.5, 0.25 / (1+K.exp(-self.sharp*((inputs-0.5)/0.5))) + 0.25, inputs)
        inputs = tf.where(orig > 0.5 and orig <= 0.75, 0.25 / (1+K.exp(-self.sharp*((inputs-0.75)/0.5))) + 0.5, inputs)
        return K.where(orig > 0.75, 1, inputs)

    def get_config(self):
        config = {'sharp': float(self.sharp)}
        base_config = super(QPWCX, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

    def compute_output_shape(self, input_shape):
        return input_shape
`

**Comment by achandraa** [comment] 2019-06-17 11:44
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-06-24 06:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-06-24 06:26 UTC
Labels: TF 1.13, comp:ops, stat:awaiting response, type:support
