### ISSUE TITLE
@aliashori75

### ISSUE THREAD

**Issue by aliashori75** [tensorflow/tensorflow#58436] opened 2022-11-03 19:06 UTC
@aliashori75 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and elaborate about your issue.
I was able to execute the given code snippet without any error on Colab using TF v2.10. Please find gist [here](https://colab.research.google.com/gist/tiruk007/2fb83dfb02ff71ef212749a877cc0ce4/58374.ipynb) for reference.

Thank you !

_Originally posted by @tiruk007 in https://github.com/tensorflow/tensorflow/issues/58374#issuecomment-1297930943_

**Comment by mihaimaruseac** [comment] 2022-11-03 19:53
Please stop spamming with duplicate issues or we might be required to block you from the org. 

Closing as duplicate of #58374

**Closed by mihaimaruseac** 2022-11-03 19:53 UTC
