### ISSUE TITLE
Issue with tensorflow/core/lib/core/threadpool.cc

### ISSUE THREAD

**Issue by julialintern** [tensorflow/tensorflow#2324] opened 2016-05-11 14:20 UTC
Operating System:  Ubuntu 14.04.4
CUDA version: 7.5
cuNN: 4.0.7

Installed from sources:
commit 5681406

running : bazel build -c opt //tensorflow/cc:tutorials_example_trainer --verbose_failures --genrule_strategy=standalone --spawn_strategy=standalone

Note : that i have configured my WORKSPACE file as per : https://github.com/bazelbuild/bazel/issues/623#issuecomment-158151936: 

(made the following corrections:) 
download jpeg.BUILD.txt, png.BUILD.txt, and WORKSPACE.txt from @srsaharoy 's message #623 (comment) . (the 2nd post with attachments) and place these files in the tensorflow lib without the .txt extension instead of the existing files (in my case ~/git/tensorflow/tensorflow).
create folder with external source files: ~/git/tensorflow/fix/files/re2 ~/git/tensorflow/fix/files/jpeg-9a/jpeg-9a ~/git/tensorflow/fix/files/gemmlowp ~/git/tensorflow/fix/files/libpng-1.2.53/libpng-1.2.53 ~/git/tensorflow/fix/files/six-1.10.0 Note the dir-in-dir for jpeg-9a and libpng-1.2.53. This is necessary.
change paths in WORKSPACE file to match the location of the aux source files
 .... 

Now I am just stuck with the following error: 

ERROR: /home/julialintern/tensorflow/tensorflow/core/BUILD:756:1: C++ compilation of rule '//tensorflow/core:lib_internal' failed: gcc failed: error executing command 
  (cd /home/julialintern/.cache/bazel/_bazel_julialintern/1a7b4f00b1b7d4c4a3ca618f554c7ad8/tensorflow && \
  exec env - \
    PATH=/home/julialintern/torch/install/bin:/home/julialintern/bin:/usr/local/cuda/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/julialintern/bin \
    TMPDIR=/tmp/user/1001 \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/jpeg_archive -iquote bazel-out/host/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/re2 -iquote bazel-out/host/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/host/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/host/genfiles/external/png_archive/libpng-1.2.53 -isystem third_party/eigen3 -isystem bazel-out/host/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-50812b426b7c -isystem bazel-out/host/genfiles/external/eigen_archive/eigen-eigen-50812b426b7c -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -DTENSORFLOW_USE_EIGEN_THREADPOOL -pthread -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/tensorflow/core/_objs/lib_internal/tensorflow/core/lib/core/threadpool.o' -MD -MF bazel-out/host/bin/tensorflow/core/_objs/lib_internal/tensorflow/core/lib/core/threadpool.d -c tensorflow/core/lib/core/threadpool.cc -o bazel-out/host/bin/tensorflow/core/_objs/lib_internal/tensorflow/core/lib/core/threadpool.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/core/lib/core/threadpool.cc:83:49: error: expected template-name before '<' token
 struct ThreadPool::Impl : Eigen::ThreadPoolTempl<EigenEnvironment> {
                                                 ^
tensorflow/core/lib/core/threadpool.cc:83:49: error: expected '{' before '<' token
tensorflow/core/lib/core/threadpool.cc:83:49: error: expected unqualified-id before '<' token
tensorflow/core/lib/core/threadpool.cc:221:1: error: expected '}' at end of input
 }  // namespace tensorflow
 ^
tensorflow/core/lib/core/threadpool.cc:221:1: error: expected '}' at end of input
Target //tensorflow/cc:tutorials_example_trainer failed to build

**Comment by benoitsteiner** [comment] 2016-05-13 23:12
This looks like a duplicate of https://github.com/tensorflow/tensorflow/issues/2324

**Closed by benoitsteiner** 2016-05-13 23:12 UTC
