### ISSUE TITLE
Support for TensorList crossing the XLA/TF boundary is not implemented

### ISSUE THREAD

**Issue by EgorLakomkin** [tensorflow/tensorflow#39162] opened 2020-05-04 18:04 UTC
A colab notebook to reproduce the issue: https://colab.research.google.com/drive/1O-ht27_h4d6qf_65nmK52qLTrMyDLMVr

I am trying to implement a simple RNN compiled with XLA. The code works without XLA, but when I try to compile one tf function with XLA and I get a strange error:

```
UnimplementedError:  Support for TensorList crossing the XLA/TF boundary is not implemented
	 [[node dummy_name/StatefulPartitionedCall (defined at <ipython-input-12-b36d3a96b1c7>:30) ]] [Op:__inference_simple_train_5054]

Errors may have originated from an input operation.
Input Source operations connected to node dummy_name/StatefulPartitionedCall:
 data (defined at <ipython-input-15-3f954a2dcc35>:38)
```

I am not sure what goes wrong when experimental_compile is added and if thats an expected behavior?

**Comment by Saduf2019** [comment] 2020-05-05 08:20
@EgorLakomkin 
I ran your code on tensorflow 2.1 and do not face any issues, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/196583ede82231e3e735f608b6bd154b/2.ipynb).
However, i am able to replicate the issue on nightly,please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/46d5e3cf5a8c3fed81a49eb7878a6d2d/untitled163.ipynb).
Thanks!

**Comment by EgorLakomkin** [comment] 2020-05-12 11:22
Any additional info is needed from me?

**Comment by Saduf2019** [comment] 2020-05-12 14:17
@EgorLakomkin
As you have not specified the tf version, we ran the code on 2.1 and nightly. please verify the gist and as the code works fine in 2.1, can we consider this as resolved.

**Comment by EgorLakomkin** [comment] 2020-05-12 16:50
It fails for me when I run it with tf-nightly. I guess it could indicate a regression from 2.1 -> 2.2?

**Comment by Saduf2019** [comment] 2020-05-13 04:17
@EgorLakomkin 
Sure we will do so, will working on 2.1 help you for now, meanwhile we will look into nightly issue.

**Comment by cheshire** [comment] 2020-05-26 15:56
@EgorLakomkin This is expected behavior, this feature is not implemented.
We do plan on doing this, but it is non-trivial.

`TensorArray` is supported in XLA, but not in crossing the TF/XLA boundary. The problem is that taking a derivative from *outside* exposes the TensorArray to the boundary, and the conversion is not implemented.

The workaround is to make the outer function compile (your `simple_train`), and potentially remove the inner compiled function (might be not necessary, but to avoid stumbling into your other issue in github.com/tensorflow/tensorflow/issues/39060)

**Comment by Saduf2019** [comment] 2020-05-27 04:30
@EgorLakomkin 
Please update as per above comment.

**Comment by EgorLakomkin** [comment] 2020-05-27 11:24
@cheshire thank you, then maybe we can close this ticket.

**Comment by Saduf2019** [comment] 2020-05-27 13:10
Moving this to closed status with confirmation.

**Closed by Saduf2019** 2020-05-27 13:10 UTC
Labels: TF 2.2, comp:xla, stat:awaiting response, type:bug
