### ISSUE TITLE
Bazel build Failed in compiling libtensorflow.so from source using the mkl config in windows 10

### ISSUE THREAD

**Issue by Danielzxliu** [tensorflow/tensorflow#20240] opened 2018-06-23 07:17 UTC
### System information
- **OS Platform and Distribution )**: win10 x64
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: R1.9
- **Python version**:  Anaconda3 Python3.6.2
- **Bazel version (if compiling from source)**: 0.14.0
- **GCC/Compiler version (if compiling from source)**: VS2015 Update3
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: 
bazel build -c opt --copt=/arch:AVX  --config=mkl\
  tensorflow:libtensorflow.so \
  tensorflow/tools/lib_package:clicenses_generate \
  tensorflow/java:libtensorflow_jni.so \
  tensorflow/tools/lib_package:jnilicenses_generate

### Describe the problem
I want to build libtensorflow.so with "cpu + mkl"  in win10 os.

I had builded the libtensorflow.so using the script (run_libtensorflow.bat) in the directory: tensorflow/tools/ci_build/windows/cpu/bazel/.This script works very well,but then a link error occur 
if I add --config=mkl to the option of bazel build. 

I think this link error is about mkl library,and this link error exist a period of time.
I tried to build libtensorflow.so r1.8,after fixing some compilation error the same link error occur. 

### The verbose log are following 

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=C:/tools/Anaconda3/python.exe
INFO: Reading rc options for 'build' from d:\tensorflow_git_reps\tensorflow_r1.9\tools\bazel.rc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --define=grpc_no_ares=true --spawn_strategy=standalone --genrule_strategy=standalone -c opt
INFO: Reading rc options for 'build' from d:\tensorflow_git_reps\tensorflow_r1.9\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/tools/Anaconda3/python.exe --action_env PYTHON_LIB_PATH=C:/tools/Anaconda3/lib/site-packages --python_path=C:/tools/Anaconda3/python.exe --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_CUDA=0 --action_env TF_DOWNLOAD_CLANG=0 --define grpc_no_ares=true --strip=always --config monolithic --copt=-w --host_copt=-w --verbose_failures
INFO: Found applicable config definition build:monolithic in file d:\tensorflow_git_reps\tensorflow_r1.9\tools\bazel.rc: --define framework_shared_object=false
INFO: Found applicable config definition build:mkl in file d:\tensorflow_git_reps\tensorflow_r1.9\tools\bazel.rc: --define=using_mkl=true -c opt --define=using_mkl=true
WARNING: G:/tf/_bazel_50219889/4o2fzunw/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in G:/tf/_bazel_50219889/4o2fzunw/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: G:/tf/_bazel_50219889/4o2fzunw/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in G:/tf/_bazel_50219889/4o2fzunw/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: G:/tf/_bazel_50219889/4o2fzunw/external/grpc/BUILD:1960:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in G:/tf/_bazel_50219889/4o2fzunw/external/grpc/bazel/grpc_build_system.bzl:172:12
INFO: Analysed target //tensorflow:libtensorflow.so (77 packages loaded).
INFO: Found 1 target...
ERROR: D:/tensorflow_git_reps/tensorflow_r1.9/tensorflow/BUILD:480:1: Linking of rule '//tensorflow:libtensorflow.so' failed (Exit 1169): link.exe failed: error executing command 
  cd G:/tf/_bazel_50219889/4o2fzunw/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/tools/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/tools/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\50219889\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TMP=C:\Users\50219889\AppData\Local\Temp
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /DLL /WHOLEARCHIVE:external/mkl_windows/lib/libiomp5md.lib /WHOLEARCHIVE:external/mkl_windows/lib/mklml.lib /SUBSYSTEM:CONSOLE -DEFAULTLIB:advapi32.lib -pthread /MACHINE:X64 @bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow.so-2.params /DEFAULTLIB:msvcrt.lib
LINK : warning LNK4044: unrecognized option '/pthread'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/ldl'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : warning LNK4044: unrecognized option '/lm'; ignored
**mklml.lib(mklml.dll) : error LNK2005: __NULL_IMPORT_DESCRIPTOR already defined in libiomp5md.lib(libiomp5md.dll)**
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow.exp
libbatch_kernels.lo(batch_kernels.o) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "void __cdecl tensorflow::`dynamic initializer for 'registrar__body__0__object''(void)" (??__Eregistrar__body__0__object@tensorflow@@YAXXZ)
libarithmetic_optimizer.a(arithmetic_optimizer.o) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
libarithmetic_optimizer.a(arithmetic_optimizer.o) : warning LNK4217: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported in function "private: bool __cdecl tensorflow::grappler::`anonymous namespace'::ReorderCastAndTranspose::NodeIsOnCpuOrGpu(class tensorflow::NodeDef const *)const " (?NodeIsOnCpuOrGpu@ReorderCastAndTranspose@?A0x3f420f79@grappler@tensorflow@@AEBA_NPEBVNodeDef@4@@Z)
liblayout_optimizer.a(layout_optimizer.o) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
bazel-out/x64_windows-opt/bin/tensorflow/libtensorflow.so : fatal error LNK1169: one or more multiply defined symbols found
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 150.103s, Critical Path: 34.36s
INFO: 2 processes, local.
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment] 2018-06-23 18:31
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by zxliu1984** [comment] 2018-06-24 14:37
Have I written custom code: No.

**Comment by tensorflowbutler** [comment] 2018-07-09 18:45
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-24 12:59
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-08 18:57
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-23 19:08
Nagging Assignee @mrry: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mrry** [comment] 2018-08-23 21:53
@tatianashp @gunan @meteorcloudy Do we currently support the MKL build on Windows? It looks like the BUILD rules might not be correct... that error message corresponds to [linking a static library multiple times](https://social.msdn.microsoft.com/Forums/en-US/5d79a108-6516-42d9-9626-05c622d2a007/want-to-fix-a-linker-warning?forum=winappswithnativecode).

**Comment by meteorcloudy** [comment] 2018-08-24 08:18
@mrry I never tried to build tensorflow with MKL support on Windows, I believe it's currently not support.

**Comment by tatianashp** [comment] 2018-08-24 17:14
+ @agramesh1

**Comment by agramesh1** [comment] 2018-08-27 05:18
@tatianashp @mrry  We only have verified Windows build using CMake. We are testing bazel  Windows build now.

**Comment by claynerobison** [comment] 2018-09-07 23:11
I'm taking a look at this and have reproduced the error. WIP.

**Comment by tensorflowbutler** [comment] 2018-09-22 12:37
Nagging Assignee @mrry: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment] 2018-09-23 01:32
@claynerobison Thank you!

**Comment by harshini-gadige** [comment] 2018-10-31 16:30
@claynerobison  -  Any update ?

**Comment by claynerobison** [comment] 2018-10-31 18:52
@harshini-gadige We are working the feature into our sprints.

**Comment by tensorflowbutler** [comment] 2018-11-15 18:56
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-11-30 18:55
Nagging Assignee @TensorFlow-MKL: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by claynerobison** [comment] 2018-12-20 04:03
See https://github.com/tensorflow/tensorflow/issues/23420

**Comment by TensorFlow-MKL** [comment] 2019-01-17 19:40
addressed in comments on [#23420](https://github.com/tensorflow/tensorflow/issues/23420)

Closing

**Closed by TensorFlow-MKL** 2019-01-17 19:40 UTC
Labels: comp:mkl, type:build/install
