### ISSUE TITLE
 in tutorials/load_data/csv ,when trying twice, the test_data is different?

### ISSUE THREAD

**Issue by trembous** [tensorflow/tensorflow#33931] opened 2019-11-02 09:02 UTC
## URL(s) with the issue:

https://tensorflow.google.cn/tutorials/load_data/csv

### Clear description

when run the last code :loop, retry it ,the result is different 

then run the last code 
>>>list(test_data)[0][1][:10]
>>>list(test_data)[0][1][:10]
why the test_data is not shuffled,but result is different

if this ,the actual label is not trustworthy
![5I7`)`M@7HBT@04EG5~(5~6](https://user-images.githubusercontent.com/41684325/68068668-16bc4300-fd92-11e9-992b-9bf9fa743a8c.png)

**Comment by a927** [comment] 2019-11-02 17:25
#
Duplicate of #

**Comment by trembous** [comment] 2019-11-03 06:59
if duplicate,please tell me the original issue (๑>◡<๑)

**Comment by trembous** [comment] 2019-11-03 07:00
> Duplicate of #

if duplicate,please tell me the original issue (๑>◡<๑)

**Comment by oanush** [comment] 2019-11-04 06:04
@trembous ,
Hello, yes test data is different every time the last code is run. Its the intended behavior.
If you can see the section  `read the CSV data from the file and create a dataset` data with batch_size of 5 is imported every time.

**Comment by trembous** [comment] 2019-11-05 07:31
> @trembous ,
> Hello, yes test data is different every time the last code is run. Its the intended behavior.
> If you can see the section `read the CSV data from the file and create a dataset` data with batch_size of 5 is imported every time.

thanks, but  I remain want to know that how to accquire the started label 'actual outcome',
so the example is not precise.
if this,I suggest the example will like give a record of csv '(feature , label)' , then the test data is stable 
otherwise,the actual label is not trustworthy

**Comment by jvishnuvardhan** [comment] 2019-11-18 23:02
@trembous This is intended behavior. I updated code to show the actual labels and corresponding features selected for prediction. When you run the last cell like this

## Ran first time (last block)
```
predictions = model.predict(test_data)
show_batch(temp_dataset)
print("")
# Show some results
for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))
```
The result is something like this (not exactly same as yours as the dataset frame may be different)

```
tf.Tensor([1 1 1 0 0], shape=(5,), dtype=int32)

age                 : [28. 19. 19. 28. 25.]
n_siblings_spouses  : [1. 1. 0. 0. 0.]
parch               : [0. 0. 2. 0. 0.]
fare                : [146.521  26.     26.283   8.05    7.05 ]

Predicted survival: 36.86%  | Actual outcome:  SURVIVED
Predicted survival: 12.31%  | Actual outcome:  DIED
Predicted survival: 41.52%  | Actual outcome:  DIED
Predicted survival: 36.76%  | Actual outcome:  DIED
Predicted survival: 5.32%  | Actual outcome:  SURVIVED
```

After that you are running code below `#Show some results` and not running the prediction code `predictions = model.predict(test_data)` again as follows

## Ran second time (last block)
```
show_batch(temp_dataset)
print("")
# Show some results
for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))
```

I have added `show_batch(temp_dataset)` to show which batch was selected for the second time execution. 

```
 tf.Tensor([0 0 0 0 0], shape=(5,), dtype=int32)

age                 : [26.  28.5 46.  28.  33. ]
n_siblings_spouses  : [0. 0. 0. 0. 0.]
parch               : [0. 0. 0. 0. 0.]
fare                : [ 8.05   7.229 79.2    8.05  12.275]

Predicted survival: 36.86%  | Actual outcome:  DIED
Predicted survival: 12.31%  | Actual outcome:  SURVIVED
Predicted survival: 41.52%  | Actual outcome:  DIED
Predicted survival: 36.76%  | Actual outcome:  DIED
Predicted survival: 5.32%  | Actual outcome:  DIED
```

In the above two outputs, you could see that inputs (labels and features) are different between first execution and second execution. However, you didn't ran the prediction code  `predictions = model.predict(test_data)`, so the predictions are same after first and second executions. 

[Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1b3f06da80aea817c51678a954f7fe79/csv.ipynb) is the gist for your reference.

I am closing the issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-11-18 23:02 UTC
Labels: TF 2.0, comp:data, type:support

**Comment by trembous** [comment] 2019-11-21 02:34
> @trembous This is intended behavior. I updated code to show the actual labels and corresponding features selected for prediction. When you run the last cell like this
> 
> ## Ran first time (last block)
> ```
> predictions = model.predict(test_data)
> show_batch(temp_dataset)
> print("")
> # Show some results
> for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
>   print("Predicted survival: {:.2%}".format(prediction[0]),
>         " | Actual outcome: ",
>         ("SURVIVED" if bool(survived) else "DIED"))
> ```
> 
> The result is something like this (not exactly same as yours as the dataset frame may be different)
> 
> ```
> tf.Tensor([1 1 1 0 0], shape=(5,), dtype=int32)
> 
> age                 : [28. 19. 19. 28. 25.]
> n_siblings_spouses  : [1. 1. 0. 0. 0.]
> parch               : [0. 0. 2. 0. 0.]
> fare                : [146.521  26.     26.283   8.05    7.05 ]
> 
> Predicted survival: 36.86%  | Actual outcome:  SURVIVED
> Predicted survival: 12.31%  | Actual outcome:  DIED
> Predicted survival: 41.52%  | Actual outcome:  DIED
> Predicted survival: 36.76%  | Actual outcome:  DIED
> Predicted survival: 5.32%  | Actual outcome:  SURVIVED
> ```
> 
> After that you are running code below `#Show some results` and not running the prediction code `predictions = model.predict(test_data)` again as follows
> 
> ## Ran second time (last block)
> ```
> show_batch(temp_dataset)
> print("")
> # Show some results
> for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
>   print("Predicted survival: {:.2%}".format(prediction[0]),
>         " | Actual outcome: ",
>         ("SURVIVED" if bool(survived) else "DIED"))
> ```
> 
> I have added `show_batch(temp_dataset)` to show which batch was selected for the second time execution.
> 
> ```
>  tf.Tensor([0 0 0 0 0], shape=(5,), dtype=int32)
> 
> age                 : [26.  28.5 46.  28.  33. ]
> n_siblings_spouses  : [0. 0. 0. 0. 0.]
> parch               : [0. 0. 0. 0. 0.]
> fare                : [ 8.05   7.229 79.2    8.05  12.275]
> 
> Predicted survival: 36.86%  | Actual outcome:  DIED
> Predicted survival: 12.31%  | Actual outcome:  SURVIVED
> Predicted survival: 41.52%  | Actual outcome:  DIED
> Predicted survival: 36.76%  | Actual outcome:  DIED
> Predicted survival: 5.32%  | Actual outcome:  DIED
> ```
> 
> In the above two outputs, you could see that inputs (labels and features) are different between first execution and second execution. However, you didn't ran the prediction code `predictions = model.predict(test_data)`, so the predictions are same after first and second executions.
> 
> [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/1b3f06da80aea817c51678a954f7fe79/csv.ipynb) is the gist for your reference.
> 
> I am closing the issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!

good job!
