### ISSUE TITLE
Getting an "Unimplemented" error when using tensorflow-gpu built from source on TF Object Detection API model. 

### ISSUE THREAD

**Issue by farzaa** [tensorflow/tensorflow#27761] opened 2019-04-11 20:54 UTC
My model is `faster_rcnn_inception_v2_coco` found within the TensorFlow object detection API located [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

When I use `tensorflow-gpu` `1.13.1` and simply install it via Docker w/ the instructions found [here](https://www.tensorflow.org/install/docker#gpu_support) everything works perfectly upon inference. 

But when I use the try to run `tensorflow-gpu` built from source (running TF `1.13.1`) built from source (via Docker w/ the instructions [here](https://www.tensorflow.org/install/source#gpu_support_2)) to take advantage of CPU optimizations I get hit with the following error upon attempting to do inference. 

```
[evhttp_server.cc : 237] RAW: Entering the event loop ...
2019-04-11 20:27:59.196073: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:27:59.196141: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
2019-04-11 20:28:01.013470: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:28:01.013541: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
2019-04-11 20:28:02.892400: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:28:02.892476: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
```

This is super odd, because things worked fine with tensorflow-gpu installed normally with Docker when doing inference. But, after building it from source, something breaks!

**Comment by muddham** [comment] 2019-05-03 13:20
@farzaaCould you please provide the exact steps followed? In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. This is  the [link](https://www.tensorflow.org/install/source) for installation. Thanks!

**Comment by muddham** [comment] 2019-05-08 06:24
@farzaa Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-08 06:24 UTC
Labels: stat:awaiting response, type:support
