### ISSUE TITLE
IOS #include "unsupported/Eigen/CXX11/Tensor"

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorflow#4729] opened 2016-10-03 13:43 UTC
### Environment info
Operating System: Mac OS X EI captain 10.11.6

Installed version of CUDA and cuDNN: 
No

If installed from binary pip package, provide:

1. A link to the pip package you installed:
I install tensorflow from source following this site: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
But It seems i cant get the tensorflow version command, there is no module named tensorflow; I also installed tensorflow with docker on my Mac.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) 
6218ac2be3cc530da866ec32da4cb86c6ac5bb85

2. The output of `bazel version`
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:58:27 2016 (1470304707)
Build timestamp: 1470304707
Build timestamp as int: 1470304707

### What other attempted solutions have you tried?
Search on stackoverflow

I followed the ios_example from here, https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples
I successfully installed the static library containing the core code of tensorflow;
I downloaded the incetption v1, and I have xcode 7.3.1 installed on my Mac;
When I launch xcode from tf_ios_makefile_example.xcodeproj in the subfolder tensorflow/tensorflow/contrib/ios_examples/simple, I got un error:
#include "unsupported/Eigen/CXX11/Tensor"

What did I miss? the version of eigen is not right? I do install eigen.

Any suggestion will be appreciated
Thanks

**Comment by concretevitamin** [comment] 2016-10-03 17:16
This seems to be a duplicate of #4680.  Please follow the development there, thanks.

**Closed by concretevitamin** 2016-10-03 17:16 UTC
