### ISSUE TITLE
Reading .tfrecords files greater than 64mb brings up errors

### ISSUE THREAD

**Issue by jgv115** [tensorflow/tensorflow#13575] opened 2017-10-09 02:47 UTC
I have already read this thread: https://github.com/tensorflow/tensorflow/issues/7311 but I am still encountering this issue with version 1.3.0. Was wondering if anyone knows why?

Tested on 2 systems:
OS: Windows 10, Ubuntu 16.04
Tensorflow installed from source,
Tensorflow version: 1.3.0
One system running tensorflow non gpu and another system running CUDA 8 and cuDNN v6
GPU model: none and GTX Titan Z

The error I get is:

`  File "C:\Users\benja\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse example input, value: '
�ם9
ѻ
csvȻ
Ļ
��@CQ�.�������M�B

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\write_to_tfrecords.py", line 581, in <module>
    main()
  File "D:\write_to_tfrecords.py", line 577, in main
    read_dataset_from_tfrecords()
  File "D:\write_to_tfrecords.py", line 554, in read_dataset_from_tfrecords
    image_dataset, csv_dataset = sess.run([image_out_reshaped, csv_out_reshaped])
  File "C:\Users\benja\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\benja\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse example input, value: '
�ם9
ѻ
csvȻ
Ļ
��@CQ�.�������M�B
>>> 
`

When I try to read .tfrecords files that are less than 64mb this error does not occur.

My code is here:
`        with tf.Session() as sess:
            try:
                feature = {'images': tf.FixedLenFeature([], tf.string),
                           'csv': tf.FixedLenFeature([], tf.string)
                           }

                filename_queue = tf.train.string_input_producer([data_path], num_epochs=1)

                reader = tf.TFRecordReader()

                _, serialized_example = reader.read(filename_queue)

                features = tf.parse_single_example(serialized_example, features=feature)

                image_out = tf.decode_raw(features['images'], tf.uint8)
                csv_out = tf.decode_raw(features['csv'], tf.float32)

                image_out_reshaped = tf.reshape(image_out, [1000, 200, 200, 3])
                csv_out_reshaped = tf.reshape(csv_out, [1000, 6])

                sess.run(tf.global_variables_initializer())
                sess.run(tf.local_variables_initializer())

                # Create a coordinator and run all QueueRunner objects
                coord = tf.train.Coordinator()
                threads = tf.train.start_queue_runners(coord=coord)

                image_dataset, csv_dataset = sess.run([image_out_reshaped, csv_out_reshaped])

                coord.request_stop()
                coord.join(threads)
`

**Comment by bodokaiser** [comment] 2017-10-09 15:38
Can confirm this issue though it only occurs on windows. To reproduce you can use [this][1] modified 3d volume from the RIRE dataset with following decoder:

```python
class Decoder:
  """Decodes a tfrecord volume to tensor."""

  def __init__(self):
    self.features = {
        'volume/encoded': tf.FixedLenFeature((), tf.string),
        'volume/shape': tf.VarLenFeature(tf.int64),
        'volume/vmin': tf.FixedLenFeature((), tf.int64),
        'volume/vmax': tf.FixedLenFeature((), tf.int64),
    }

  def decode(self, example):
    """Returns tensor from tfrecord string.

    Args:
      example: tfrecord string
    Returns:
      volume: volume tensor
    """
    with tf.name_scope('decode'):
      features = tf.parse_single_example(example, features=self.features)

      return tf.reshape(tf.decode_raw(features['volume/encoded'], tf.int32),
                        features['volume/shape'].values)
```

this script should read volume and let the error occur:

```python
decoder = Decoder()

dataset = tf.contrib.data.TFRecordDataset('mr.tfrecord').map(decoder.decode)

volume = dataset.make_one_shot_iterator().get_next()

with tf.Session() as session:
  session.run(volume)
```

yielding:

```
2017-10-09 17:30:13.903542: W C:\tf_jenkins\home\workspace\tf-nightly-windows\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Could not parse example input, value: '
«µ½'
▀σ½'
volume/encoded╩σ½'
┼σ½'
└σ½'
2017-10-09 17:30:14.626344: W C:\tf_jenkins\home\workspace\tf-nightly-windows\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Could not parse example input, value: '
«µ½'
▀σ½'
volume/encoded╩σ½'
┼σ½'
└σ½'
Traceback (most recent call last):
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 467, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse example input, value: '
\udcae\udce6\udcab'
\udcdf\udce5\udcab'
volume/encoded\udcca\udce5\udcab'
\udcc5\udce5\udcab'
\udcc0\udce5\udcab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\Bodo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse example input, value: '
\udcae\udce6\udcab'
\udcdf\udce5\udcab'
volume/encoded\udcca\udce5\udcab'
\udcc5\udce5\udcab'
\udcc0\udce5\udcab'
```

[1]: https://www.dropbox.com/s/ka9ximgj65dibtr/mr.tfrecord?dl=0

**Comment by bodokaiser** [comment] 2017-10-10 08:51
```
import numpy as np
import tensorflow as tf


SIZE = int(64e6)

def _bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))


def decode(example):
  feature_keys = {'encoded': tf.FixedLenFeature((), tf.string)}
  features = tf.parse_single_example(example, features=feature_keys)
  return tf.decode_raw(features['encoded'], tf.int32)


def encode(array):
  return tf.train.Example(features=tf.train.Features(feature={
      'encoded': _bytes_feature([array.astype(np.int32).tobytes()]),
    })).SerializeToString()


with tf.python_io.TFRecordWriter('foo.tfrecord') as writer:
  writer.write(encode(np.ones([SIZE], np.int32)))


dataset = tf.data.TFRecordDataset('foo.tfrecord').map(decode)

data = dataset.make_one_shot_iterator().get_next()

with tf.Session() as session:
  print(session.run(data).shape)
```

This should fail too on windows. I will check this later.

If the case: Can it be that the windows build still uses the protobuf version which is limited to 64mb?

**Comment by bodokaiser** [comment] 2017-10-10 10:39
@martinwicke

**Comment by martinwicke** [comment] 2017-10-10 16:02
@mrry Does Windows Protobuf still have the 64M limit? 

@bodokaiser You built from source, can you check your protobuf version?

**Comment by bodokaiser** [comment] 2017-10-10 16:25
@martinwicke I used `tf-nightly-gpu` package [built by the tensorflow team](http://ci.tensorflow.org/view/tf-nightly/job/tf-nightly-windows/M=windows-gpu,PY=36/). Protobuf version is `3.4.0` (as on `tf-nightly` for macOS)

However I noticed I had to do `from google import protobuf; protobuf.__version__` on the windows machine as `import google; google.protobuf.__version__` would fail with `module "google" has no attribute "protobuf"` what however works under macOS (could this be relevant somehow?).

**Comment by JefChiu** [comment] 2017-10-10 16:41
I will be out of the office starting  2017/10/11 and will not return until
2017/10/20.

During my absence, you can contact the system owner listed below for any
urgency. And I will get back to you as soon as I return. Thanks for your
support.

Image Process Platform - 郭益銘 ( 774-2020)
HelpDesk 2.0 - 林沂星 (774-2018 )

For any urgent support need, please call my cell phone  0988737530

 --------------------------------------------------------------------------- 
                                                         TSMC PROPERTY       
 This email communication (and any attachments) is proprietary information   
 for the sole use of its                                                     
 intended recipient. Any unauthorized review, use or distribution by anyone  
 other than the intended                                                     
 recipient is strictly prohibited.  If you are not the intended recipient,   
 please notify the sender by                                                 
 replying to this email, and then delete this email and any copies of it     
 immediately. Thank you.                                                     
 ---------------------------------------------------------------------------

**Comment by mrry** [comment] 2017-10-10 17:28
@martinwicke I believe we're using the same version of the library on both platforms. Is it possible that there's a missing configuration option needed to disable the limit?

**Comment by martinwicke** [comment] 2017-10-11 15:37
The default limit starting at 3.2 is 2G -- there doesn't seem to be anything platform related in that code.

**Comment by bodokaiser** [comment] 2017-10-11 19:46
@martinwicke what do u suggest where the error originates from?

**Comment by martinwicke** [comment] 2017-10-12 17:01
I believe the error "Could not parse example input" originates [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/example_parsing_ops.cc#L341). 

This would also mean you're parsing Sequence Examples, which your code doesn't match, and is confusing.

**Comment by bodokaiser** [comment] 2017-10-12 18:05
What about [here][1]?

I followed `tf.parse_single_example` to [here] however `tensorflow.python.ops.gen_parsing_ops` seems to be a generated file. Any idea what generates this?

[1]: https://github.com/tensorflow/tensorflow/blob/e062447136faa0a3513e3b0690598fee5c16a5db/tensorflow/core/util/example_proto_fast_parsing.cc#L461-L462
[2]: https://github.com/tensorflow/tensorflow/blob/a2d9b3bf5f9e96bf459074d079b01e1c74b25afa/tensorflow/python/ops/parsing_ops.py#L698

**Comment by martinwicke** [comment] 2017-10-12 23:29
You are right of course. gen_parsing_ops is generated from parsing_ops.cc. The core you pointed to is the ultimate source of the error.

**Comment by bodokaiser** [comment] 2017-10-13 08:06
Any suggestion on how I could trace tensorflow core calls in C++ land so we can identify the problem? 

I tried dtrace and tfdbg, however dtrace got me only syscalls and tfdbg only python / graph related things.

**Comment by bodokaiser** [comment] 2017-10-13 10:11
Okay this is really weird.

If I replace `tf.parse_single_example` with `tf.parse_single_sequence_example` and reference to the resulting features with `features[0]['encoded']` instead of `features['encoded']` I do not get an error but the decoded bytes are just about 1/5 of the size it should be. On macOS it works as expected.

**Comment by bodokaiser** [comment] 2017-10-18 11:08
@martinwicke @mrry are there any updates?

I found that you can use

```python
import numpy as np

from tensorflow.core.example import example_pb2

example = example_pb2.Example.FromString(serialized)
feature = example.features.feature

encoded = feature['encoded'].bytes_list.value[0]

return np.fromstring(encoded, np.int32)
```

however this is not very practical.

**Comment by saxenasaurabh** [comment] 2017-10-26 01:42
Thanks @bodokaiser  for the detailed repro examples. I was able to reproduce using this example on Windows.
```python
import numpy as np
import tensorflow as tf
SIZE = int(64e6)
def _bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))

def decode(example):
  feature_keys = {'encoded': tf.FixedLenFeature((), tf.string)}
  features = tf.parse_single_example(example, features=feature_keys)
  return tf.decode_raw(features['encoded'], tf.int32)

def encode(array):
  return tf.train.Example(features=tf.train.Features(feature={
      'encoded': _bytes_feature([array.astype(np.int32).tobytes()]),
    })).SerializeToString()

with tf.python_io.TFRecordWriter('foo.tfrecord') as writer:
  writer.write(encode(np.ones([SIZE], np.int32)))

dataset = tf.data.TFRecordDataset('foo.tfrecord').map(decode)

data = dataset.make_one_shot_iterator().get_next()

with tf.Session() as session:
  print(session.run(data).shape)
```

However, changing from `BytesList` to `Int64` seems to work (for this example at least). I'll am looking into this further.

**Comment by bodokaiser** [comment] 2017-10-26 08:23
@saxenasaurabh yes indeed using `Int64List` does work as intended on windows.

```python
import numpy as np
import tensorflow as tf
SIZE = int(64e6)
def _int64_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def decode(example):
  feature_keys = {'encoded': tf.VarLenFeature(tf.int64)}
  features = tf.parse_single_example(example, features=feature_keys)
  return tf.sparse_tensor_to_dense(features['encoded'])

def encode(array):
  return tf.train.Example(features=tf.train.Features(feature={
      'encoded': _int64_feature(array.astype(np.int64)),
    })).SerializeToString()

with tf.python_io.TFRecordWriter('foo.tfrecord') as writer:
  writer.write(encode(np.ones([SIZE], np.int64)))

dataset = tf.data.TFRecordDataset('foo.tfrecord').map(decode)

data = dataset.make_one_shot_iterator().get_next()

with tf.Session() as session:
  print(session.run(data).shape)
```

In this case the problem may not be caused by the decoding part but by the [type switch](https://github.com/tensorflow/tensorflow/blob/e062447136faa0a3513e3b0690598fee5c16a5db/tensorflow/core/util/example_proto_fast_parsing.cc#L566-L570). What do you think?

**Comment by saxenasaurabh** [comment] 2017-10-26 22:36
Even this fails with `SIZE = int(64e7)` on my machine :(

**Comment by bodokaiser** [comment] 2017-10-27 09:04
@saxenasaurabh unfortunately can confirm too for `SIZE = int(64e7)`...

**Comment by bodokaiser** [comment] 2017-11-01 09:03
@saxenasaurabh Can you give an honest estimate on when (or if) this issue will get resolved? It may make sense for me to pursue the path of somehow pressing a linux workstation.

**Comment by angersson** [comment] 2017-12-11 21:20
Assigning to @saxenasaurabh as part of triage.

**Comment by tensorflowbutler** [comment] 2018-01-03 07:42
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by martinwicke** [comment] 2018-01-22 04:20
@saxenasaurabh any update?

**Comment by tensorflowbutler** [comment] 2018-02-06 07:50
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by saxenasaurabh** [comment] 2018-02-28 19:48
I am unable to reproduce this even with `SIZE = int(64e7)`. Closing for now. Please re-open if you are still seeing this.

**Closed by saxenasaurabh** 2018-02-28 19:48 UTC
