### ISSUE TITLE
NotFoundError:  No algorithm worked! when using Conv2D

### ISSUE THREAD

**Issue by thephet** [tensorflow/tensorflow#43174] opened 2020-09-12 09:27 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see below.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux fully updated
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Installed from pacman
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Cuda is 11.0, cuDNN is 8.0.2
- GPU model and memory: RTX 2070 Super

**Describe the current behavior**

I am running the following code: https://github.com/davidADSP/GDL_code/blob/tensorflow_2/02_03_deep_learning_conv_neural_network.ipynb

entry 11, when it does the fit, it fails. It returns:

NotFoundError:  No algorithm worked!
	 [[node functional_1/conv2d/Conv2D (defined at <ipython-input-7-10b06c61fca5>:1) ]] [Op:__inference_train_function_2021]

Function call stack:
train_function

This used to work ok previously, 1-2 months ago. I was just testing some other conv2d today, and it failed, so I went to test this example which I know it worked, and it also fails

**Describe the expected behavior**

The code should work

**Standalone code to reproduce the issue**
See the previous link. It's a github jupyter code

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-7-10b06c61fca5> in <module>
----> 1 model.fit(x_train
      2           , y_train
      3           , batch_size=32
      4           , epochs=10
      5           , shuffle=True

/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1096                 batch_size=batch_size):
   1097               callbacks.on_train_batch_begin(step)
-> 1098               tmp_logs = train_function(iterator)
   1099               if data_handler.should_sync:
   1100                 context.async_wait()

/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    838         # Lifting succeeded, so variables are initialized and we can run the
    839         # stateless function.
--> 840         return self._stateless_fn(*args, **kwds)
    841     else:
    842       canon_args, canon_kwds = \

/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2827     with self._lock:
   2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 
   2831   @property

/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1841       `args` and `kwargs`.
   1842     """
-> 1843     return self._call_flat(
   1844         [t for t in nest.flatten((args, kwargs), expand_composites=True)
   1845          if isinstance(t, (ops.Tensor,

/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1921         and executing_eagerly):
   1922       # No tape is watching; skip to running the function.
-> 1923       return self._build_call_outputs(self._inference_function.call(
   1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(

/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    543       with _InterpolateFunctionError(self):
    544         if cancellation_manager is None:
--> 545           outputs = execute.execute(
    546               str(self.signature.name),
    547               num_outputs=self._num_outputs,

/usr/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

NotFoundError:  No algorithm worked!
	 [[node functional_1/conv2d/Conv2D (defined at <ipython-input-7-10b06c61fca5>:1) ]] [Op:__inference_train_function_2021]

Function call stack:
train_function

**Comment by bhack** [comment] 2020-09-12 11:14
Do you have a very minimal  but runnable standalone code/colab example?
Also I suggest you to import and use Keras from Tensorflow `tf.keras`

**Comment by thephet** [comment] 2020-09-12 14:46
@bhack the imports are such as "import tensorflow.keras", I have updated the link above, which pointed to the master branch which is for tf 1, but I am using tf2

The example code is this: https://github.com/davidADSP/GDL_code/blob/tensorflow_2/02_03_deep_learning_conv_neural_network.ipynb

The code would be like:

```
import numpy as np

from tensorflow.keras.layers import Input, Flatten, Dense, Conv2D, BatchNormalization, LeakyReLU, Dropout, Activation
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
import tensorflow.keras.backend as K 

from tensorflow.keras.datasets import cifar10

NUM_CLASSES = 10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
y_train = to_categorical(y_train, NUM_CLASSES)
y_test = to_categorical(y_test, NUM_CLASSES)



input_layer = Input((32,32,3))

x = Conv2D(filters = 32, kernel_size = 3, strides = 1, padding = 'same')(input_layer)
x = BatchNormalization()(x)
x = LeakyReLU()(x)


x = Conv2D(filters = 32, kernel_size = 3, strides = 2, padding = 'same')(x)
x = BatchNormalization()(x)
x = LeakyReLU()(x)


x = Conv2D(filters = 64, kernel_size = 3, strides = 1, padding = 'same')(x)
x = BatchNormalization()(x)
x = LeakyReLU()(x)


x = Conv2D(filters = 64, kernel_size = 3, strides = 2, padding = 'same')(x)
x = BatchNormalization()(x)
x = LeakyReLU()(x)


x = Flatten()(x)

x = Dense(128)(x)
x = BatchNormalization()(x)
x = LeakyReLU()(x)
x = Dropout(rate = 0.5)(x)

x = Dense(NUM_CLASSES)(x)
output_layer = Activation('softmax')(x)

model = Model(input_layer, output_layer)

opt = Adam(lr=0.0005)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

model.fit(x_train
          , y_train
          , batch_size=32
          , epochs=10
          , shuffle=True
          , validation_data = (x_test, y_test))
```

**Comment by bhack** [comment] 2020-09-12 17:20
This last example It works for me. 
Generally CUDA 11 still requires Tensorflow ningthly.
Can you try with tf-nightly?

**Comment by thephet** [comment] 2020-09-13 11:08
@bhack I don't think it's related to CUDA.

I have just tested it on another computer, same OS (Arch Linux), same libraries.

The only difference is that the computer where it doesn't work uses a RTX 2070 Super. The computer where it works uses a GTX 1080 TI.

**Comment by bhack** [comment] 2020-09-13 11:12
I think that It Is an installation/packaging issue on your machine cause It Is working on colab.

Can you try an installation with pip?
https://www.tensorflow.org/install/pip

**Comment by thephet** [comment] 2020-09-13 11:13
Adding the following lines fixes the issue:

```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```

Odd, because I didnt need them before.

**Comment by bhack** [comment] 2020-09-13 11:16
Also double check CUDA versions cause CUDA 11 Is on nightly. I don't know what Arch Linux maintainers done but in that case It Is an Arch Linux issue. See https://github.com/tensorflow/tensorflow/issues/40227

**Comment by ninnghazad** [comment] 2020-09-21 22:57
I have the same problem on pip-installed tf-nightly with CUDA11 in nvidia's cuda-ubuntu-18.04 docker container.
@thephet 's fix workaround fixed it for me.
Interesting enough, the system showing the issue is using a RTX 2060 Super.

**Comment by Saduf2019** [comment] 2020-09-25 08:18
@ninnghazad 
Is this still an issue.

**Comment by aaronyw** [comment] 2020-11-20 07:26
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.

Yes!!! This solved my problem on RTX 2070 card!

**Comment by aquahika** [comment] 2020-12-09 09:21
> > Adding the following lines fixes the issue:
> 
> > 
> 
> > ```
> 
> > from tensorflow.compat.v1 import ConfigProto
> 
> > from tensorflow.compat.v1 import InteractiveSession
> 
> > 
> 
> > config = ConfigProto()
> 
> > config.gpu_options.allow_growth = True
> 
> > session = InteractiveSession(config=config)
> 
> > ```
> 
> > 
> 
> > Odd, because I didnt need them before.
> 
> > 
> 
> > This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.
> 
> 
> 
> Yes!!! This solved my problem on RTX 2070 card!


Same here!
My environment is RTX1660 Super and running on docker with `tensorflow/tensorflow:2.4.0rc3-gpu-jupyter` image.
It perfectly works with this few lines.

**Comment by heytanay** [comment] 2021-01-04 05:59
I faced this very same error and turns out that when you read a Grayscale Image as an RGB Image (as I was using ImageDataGenerator and did not provide `color_mode="grayscale"` as an argument to the generator when flowing the data), it throws the "Algorithm did not work" sort of error.

Hopefully it helps someone!

**Comment by sanjoy** [comment] 2021-01-06 00:31
CC @imintz

**Comment by L-ashwin** [comment] 2021-01-12 15:25
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.

Yes, this fixed the problem for me on 1660Ti. Does anyone know the reason for this behavior?

**Comment by bastian-f** [comment] 2021-01-14 10:27
This just happened to me too on an RTX 2070 Super. It worked before but after restarting the container I get the same error message. It still works when I run it on CPU.

The lines mentioned by @thephet did *not* help.

**Comment by hayday100** [comment] 2021-01-18 14:12
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.

This works for me.  I have 2080 GPU and was also trying to run Colab code when running into this issue.  Thanks!

**Comment by abrarum** [comment] 2021-01-21 09:48
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.

The issue still persists. Adding those line didn't helped me.

**Comment by homofortis** [comment] 2021-01-23 13:45
same issue here with docker image `tensorflow/tensorflow:2.4.0-gpu-jupyter` RTX 2070 Super.

**Comment by ricvo** [comment] 2021-01-27 21:17
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.


I am using tf 2.4.0, cuda 11.0 on a GeForce RTX 2060 
nvidia drivers 455.45.01 on Ubuntu 20.04

Those lines are needed for me too, to make the gpu work.
On cpu all works fine without errors even without that.

I also get another error when running RNNs, 
```
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1514 : Unknown: Fail to find the dnn implementation.
```
which also get fixed with the preamble mentioned by thephet above.
This issue might be related to https://github.com/tensorflow/tensorflow/issues/36508

**Comment by bernatGene** [comment] 2021-02-10 10:27
I had the exact same error but for a much more stupid mistake than people mentioned above. Model was defined with input shape (height, width, 1) but images were RGB, not grayscale.

**Comment by otaviomguerra** [comment] 2021-02-19 17:30
A code from other issue helped me to find a way to limit tensorflow GPU memory usage and solved the issue, please see:

https://github.com/google-research/text-to-text-transfer-transformer/issues/57#issuecomment-704160406

the code is:

```python
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 4GB of memory on the first GPU
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=4096)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)
 ```

**Comment by fabianscode** [comment] 2021-03-15 19:30
> same issue here with docker image `tensorflow/tensorflow:2.4.0-gpu-jupyter` RTX 2070 Super.
> P.S. Restarting the kernel and adding the code below resolves the issue.
> 
> ```
> import tensorflow as tf
> physical_devices = tf.config.list_physical_devices('GPU') 
> tf.config.experimental.set_memory_growth(physical_devices[0], True)
> ```

Same worked for me on 2070 Super tf 2.4.1
Thanks

**Comment by skku-dhkim** [comment] 2021-03-26 09:02
> same issue here with docker image `tensorflow/tensorflow:2.4.0-gpu-jupyter` RTX 2070 Super.
> P.S. Restarting the kernel and adding the code below resolves the issue.
> 
> ```
> import tensorflow as tf
> physical_devices = tf.config.list_physical_devices('GPU') 
> tf.config.experimental.set_memory_growth(physical_devices[0], True)
> ```

Same issue on RTX 2060 Ti with TF 2.4.1 
If I upgrade TF 2.4.1 to tf-nightly, the missing CUDA library error occurs. 

The proposed above solution was best for me. 
But still, it has drawbacks that limit the GPU memories. 
It could be a temporary solution.

**Comment by berserkrambo** [comment] 2021-04-08 09:12
> > same issue here with docker image `tensorflow/tensorflow:2.4.0-gpu-jupyter` RTX 2070 Super.
> > P.S. Restarting the kernel and adding the code below resolves the issue.
> > ```
> > import tensorflow as tf
> > physical_devices = tf.config.list_physical_devices('GPU') 
> > tf.config.experimental.set_memory_growth(physical_devices[0], True)
> > ```
> 
> Same issue on RTX 2060 Ti with TF 2.4.1
> If I upgrade TF 2.4.1 to tf-nightly, the missing CUDA library error occurs.
> 
> The proposed above solution was best for me.
> But still, it has drawbacks that limit the GPU memories.
> It could be a temporary solution.

Worked for me:
OS: Ubuntu 18.04
TensorFlow version: 2.4.1
Python version: 3.7.10
CUDA/cuDNN version: Cuda is 11.0, cuDNN is 8.0.4
GPU model and memory: GeForce GTX 1660 SUPER

Still doesn't make any sense, thanks anyway :)

**Comment by anujonthemove** [comment] 2021-04-26 09:56
This might be too late but still be of help to post it here since I too faced the exact same issue. For me, I just restricted the amount of GPU that the model was allowed to use. Also, the way I did is an older way to do it which I did it in tf 1.15 but it for sure works on the latest tf 2.4 version as well. Below is the code:

```
def set_tensorflow_config(per_process_gpu_memory_fraction=0.8):
    config = tf.compat.v1.ConfigProto()
    # config = tf.ConfigProto()
    config.gpu_options.per_process_gpu_memory_fraction = per_process_gpu_memory_fraction
    config.gpu_options.allow_growth=True
    # sess = tf.Session(config=config)
    sess = tf.compat.v1.Session(config=config)
    
    print("== TensorFlow Config options set ==")
    print("\nThis process will now utilize {} GPU Memeory Fraction".format(per_process_gpu_memory_fraction))

```

`set_tensorflow_config()`


**GPU:** NVIDIA GeForce RTX 2070, 8GB

**Comment by kphanipavan** [comment] 2021-05-09 09:17
> Adding the following lines fixes the issue:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> config = ConfigProto()
> config.gpu_options.allow_growth = True
> session = InteractiveSession(config=config)
> ```
> 
> Odd, because I didnt need them before.
> 
> This is needed for the computer with the RTX 2070 Super. The one with GTX 1080 TI doesnt need them. Same libraries.

Confirmed to fix the same issue
OS: Kubuntu 20.04LTS
TF: 2.4.0
GPU: Nvidia RTX 3060 mobile (100w)
Python: 3.8.5
Cuda: 11.0

I was trying ![TFLite export using this fork](https://github.com/zldrobit/yolov5/tree/tf-android)

**Comment by xoikia** [comment] 2021-05-31 05:47
I am facing the same issues ,I have tried all the solutions given above but its not resolving my issues.

**Comment by sushreebarsa** [comment] 2021-06-03 14:31
Was able to replicate the issue in TF nightly-2.6.0.dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9c11fa36f8e99d40b11583956a18b0d7/untitled205.ipynb)..Thanks !

**Comment by sanjoy** [comment] 2021-06-21 05:38
Can you try rerunning with TF 2.5 and with the env var `TF_DEVICE_MIN_SYS_MEMORY_IN_MB` set to something high, like `1000`?

**Comment by matonima** [comment] 2021-06-25 21:25
anybody has a solution for this in 3080?

**Comment by yasirroni** [comment] 2021-07-02 02:17
In my case, this error appears because the memory is full. Try to check `nvidia-smi` via terminal. In my case, I use cloud server using `jupyter`. Shutdown all kernels (not only close the file, but shutdown), and restarting solve the issue.

Hope it helps anyone stumble upon this.

**Comment by ligang1841** [comment] 2021-07-05 11:00
I solved my problem,
use cuda 11.0 and cudnn 8.0.5(with cuda11.0), in ubuntu 20.04,and nvidia driver = 460.84, for my GTX 1660ti
other version of cuda(11.2 , 11.1) will get the error

**Comment by aliosmankaya** [comment] 2021-08-03 16:36
> 
> 
> I faced this very same error and turns out that when you read a Grayscale Image as an RGB Image (as I was using ImageDataGenerator and did not provide `color_mode="grayscale"` as an argument to the generator when flowing the data), it throws the "Algorithm did not work" sort of error.
> 
> Hopefully it helps someone!

That works for me, thank you! I use opencv for RGB to GRAY:
```python
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
```

**Comment by betteryjs** [comment] 2021-08-15 04:40
Yes!!! This solved my problem on GTX 1660 TI card!

**Comment by Saduf2019** [comment] 2021-08-15 17:06
@thephet 
Please confirm if this is still an issues, it seems to have been resolved, can you try on the latest version and let us know.

**Closed** 2021-08-29 18:36 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:keras, comp:gpu, TF 2.3

**Comment by thusinh1969** [comment] 2021-10-02 03:10
To check and will solve easily:
1) Check your image input, maybe you are wrong with dimensions (usually channels) and all 
2) Out of GPU memory

Steve

**Comment by demconpeter** [comment] 2021-10-07 19:12
Same here today; the extra config lines for gpu_options.allow_growth = True fixed the "NotFoundError: No algorithm worked!" issue for me for code that was running fine on one PC but gave the above problem on another PC with AFAIK the same TensorFlow configuration, same libraries etc but a different GPU (both NVIDIA).

OS: Windows 10 64-bit
TF: 2.4.1
GPU: NVIDIA Quadro T1000 with Max-Q Design (on the other Windows 10 64-bit system PC w/o problems it was NVIDIA Quadro P1000)
Python: 3.7.6
CUDA: 11.2
nvcc --version: 11.2, V11.2.67 (on the PC w/o problems: 11.2, V11.2.142)
RAM: 32GB (on the PC w/o problems 16GB)

Why is this fix needed only in some cases and why does it work?

BTW, the shorter "os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'" also worked fine for me.

**Comment by PiotrDabkowski** [comment] 2022-03-06 23:05
I see there is a "solution", but this should never happen in a popular library in the first place. Why is this happening, and why users need to add this extra code to get tensorflow to work? I have another process that uses 6gb memory and for some reason tf cannot simply coexist with it, when I kill it the super helpful error message "UNIMPLEMENTED: DNN library is not found" disappears. No issues with pytorch. Ehh, I can only hope Jax works out much better.
