### ISSUE TITLE
Disable display “successfully opened CUDA library ****” when import tensorflow

### ISSUE THREAD

**Issue by tornadomeet** [tensorflow/tensorflow#5537] opened 2016-11-11 08:47 UTC
Hello, 
  when ```import tensorflow``` it will output some info which is boring to me , how to disable this dispaly without compile again? set CUDA_VISIBLE_DEVICES seems no work.  
```
In [1]: import tensorflow as tf;
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.7.5 locally
```

thanks

**Comment by girving** [comment] 2016-11-14 17:25
Duplicate of https://github.com/tensorflow/tensorflow/issues/566.

**Closed by girving** 2016-11-14 17:25 UTC

**Comment by tornadomeet** [comment] 2016-11-15 01:02
@girving  i'm so sorry cannot found a solution there.

**Comment by rbunn80110** [comment] 2016-12-17 02:36
Does anyone know of a solution to this problem?  Specifically for those using Python?

**Comment by yaroslavvb** [comment] 2016-12-17 18:15
Do this before importing TensorFlow
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
import tensorflow

```

**Comment by tornadomeet** [comment] 2016-12-23 01:11
@yaroslavvb  thanks.  it indeed work, but is not succinct enough, we need set it everytime.  
i just put `export TF_CPP_MIN_LOG_LEVEL=3``` in my env, but why it does't work?

**Comment by alyato** [comment] 2017-06-02 13:47
@tornadomeet it doest't work by the @yaroslavvb suggestion. the version is `0.11.0rc1`
