### ISSUE TITLE
comparison between signed and unsigned integer

### ISSUE THREAD

**Issue by pdnote99** [tensorflow/tensorflow#20428] opened 2018-06-29 20:19 UTC
### System information
No need. It is about comparison warning happening in cc/framework/ops.h
ops.h:153:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (t.NumElements() != v.size()) {
                            
cc1plus: all warnings being treated as errors

Unfortunately, due to policy out of my control, 
I cannot change the compiler option to treat warning as an error. 
I hope this to be fixed so that I can compile.

### Describe the problem
Same as above.
### Source code / logs
tensorflow/cc/framework/ops.h

**Comment by tensorflowbutler** [comment] 2018-06-30 06:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pdnote99** [comment] 2018-07-02 17:24
Hi,
Those are not relevant.
Please consider them as N/A.

Thank you for your help!
JW

**Comment by reedwm** [comment] 2018-07-02 18:54
I'm slightly confused what the issue is. Is the issue that TensorFlow has compiler warnings, and someone has changed a BUILD or bzl file to treat warnings as errors? If so, what was done to treat warnings as errors?

Also for future reference, you should always fill out the form, since we might not respond to issues if the form is not filled out.

**Comment by tensorflowbutler** [comment] 2018-07-18 19:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by pdnote99** [comment] 2018-07-18 19:36
When used the compiler flag, -Werror, I cannot compile Tensorflow.
Because it is an enforced policy to use -Werror, which is out of my control,
yes, it is an issue for me.

JW

**Comment by reedwm** [comment] 2018-07-20 22:23
Unfortunately, there are lots of TensorFlow warnings, so it would be difficult to remove all of them.

/CC @gunan, any plans to remove the TensorFlow warnings? If not, can you mark as contributions welcome?

**Comment by tensorflowbutler** [comment] 2018-08-04 18:41
Nagging Assignee @reedwm: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by reedwm** [comment] 2018-08-08 19:01
Marking as contributions welcome to remove warnings, since no one internally is working on it.

**Comment by tensorflowbutler** [comment] 2018-08-23 19:08
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by again4you** [comment] 2018-09-10 09:17
My RP is already merged so I think that  this issue would be fixed. Could someone in charge close this issue?

**Comment by reedwm** [comment] 2018-09-10 16:10
Closing, as @again4you fixed this in #21966.

**Closed by reedwm** 2018-09-10 16:10 UTC
Labels: stat:contributions welcome
