### ISSUE TITLE
Error: Nodes were connected by a reference connection

### ISSUE THREAD

**Issue by aayushgarg** [tensorflow/tensorflow#3198] opened 2016-07-05 22:46 UTC
I am running distributed TF 0.8 for Py 3.5. I have followed the initialization of tf.train.Server() as in the imagenet_distributed_train.py. I am getting the following error while executing sv.prepare_or_wait_for_session(). I am passing remote ps server and local workers as the arguments. I do have blocks of code using tf.device('/cpu:0') at some places.

sv = tf.train.Supervisor(is_chief=is_chief,
                                       init_op=init_op,
                                        summary_op=None,
                                        global_step=global_step)
sess_config = tf.ConfigProto(
                 allow_soft_placement=True,
               log_device_placement=True)
 # Get a session.
sess = sv.prepare_or_wait_for_session(target, config=sess_config)

Error while executing last line:
tensorflow.python.pywrap_tensorflow.StatusNotOK: Invalid argument: Nodes were connected by a reference connection (requiring them to be on the same device), but the two nodes were assigned two different devices: Cannot colocate nodes 'Variable' and 'Assign: Cannot merge devices with incompatible jobs: '/job:ps/task:0' and '/job:worker/task:0'
         [[Node: Assign = Assign[T=DT_FLOAT, use_locking=false, validate_shape=true, _device="/job:worker/task:0"](Variable, mul)]]

Any idea what is happening?

**Comment by aselle** [comment] 2016-07-09 00:24
@mrry, could you please take a look.

**Comment by aayushgarg** [comment] 2016-07-11 12:07
Specifically, I have converted [translate.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py) to run in the TF synchronous distributed mode. The above error occurs while preparing the session:-

sess = sv.prepare_or_wait_for_session(target, config=sess_config)

**Comment by mrry** [comment] 2016-07-12 04:57
Hi there! I'm on vacation right now, but if this is still a problem in a fortnight, feel free to reassign to me.

**Comment by vrv** [comment] 2016-07-12 04:59
You cannot place the assign op on a different device than the variable -- fix that and the problem goes away -- as far as I can tell this isn't a bug, so any follow ups should probably be on StackOverflow.

**Closed by vrv** 2016-07-12 04:59 UTC
Labels: triaged

**Comment by aayushgarg** [comment] 2016-07-12 19:26
Hi - I am not doing any assignment in the code. As noted above, I am changing translate.py example in TF to the distributed one. It is using seq2seq implementation from TF code itself. I suspect there is bug in the seq2seq implementation in TF which is assigning nodes to the different devices.

**Comment by vrv** [comment] 2016-07-12 20:10
Try updating to r0.9 -- I checked in a change that ignores impossible placements a month or so ago. :)

**Comment by kaizhigaosu** [comment] 2017-12-26 03:04
The similar problem occurs again in TF 1.4. My distributed tf codes work fine for TF 1.2,  when I update TF to version 1.4, below errors are reported for some codes, take seq2seq as example:

------------------------------------------
2017-12-25 11:00:50.946656: I tensorflow/core/distributed_runtime/master_session.cc:1004] Start master session 8f2200ccca936616 with config: allow_soft_placement: true
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Cannot colocate nodes 'tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/read_tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases_0' and 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/RMSProp_1: Cannot merge devices with incompatible jobs: '/job:worker/task:1/device:CPU:0' and '/job:ps/task:0/device:CPU:0'
	 [[Node: tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/read_tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases_0 = Identity[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases"], _device="/job:ps/task:0/device:CPU:0"](tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/cond/Merge)]]

Caused by op u'tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/read_tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases_0', defined at:
  File "/home/peng/letrain/applications/letrain.py", line 241, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/peng/letrain/applications/letrain.py", line 238, in main
    LeTrain().model_train(user_mode)
  File "/home/peng/letrain/platform/base_train.py", line 1046, in model_train
    tvars_ps, acc_grads = self._gen_ps_model_and_acc_grads(variables_to_train, deploy_config)
  File "/home/peng/letrain/platform/base_train.py", line 679, in _gen_ps_model_and_acc_grads
    trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 805, in _get_single_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 345, in _init_from_args
    self._build_initializer_expr(self._initial_value),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 777, in _build_initializer_expr
    new_op = self._build_initializer_expr(initial_value.op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 813, in _build_initializer_expr
    attrs=initial_value.node_def.attr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot colocate nodes 'tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/read_tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases_0' and 'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/RMSProp_1: Cannot merge devices with incompatible jobs: '/job:worker/task:1/device:CPU:0' and '/job:ps/task:0/device:CPU:0'
	 [[Node: tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases/read_tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases_0 = Identity[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/biases"], _device="/job:ps/task:0/device:CPU:0"](tvars_ps35_embedding_attention_seq2seq_embedding_attention_decoder_attention_decoder_AttnOutputProjection_biases/cond/Merge)]]

**Comment by ankushagarwal** [comment] 2018-04-11 23:59
FWIW, I am running into this issue on Tensorflow 1.7.0

I am using a single parameter server and a single worker. I am training a seq2seq model and using the `tf.train.replica_device_setter(...)` function to assign variables to the parameter server and ops to the worker node.

Here is the error message that I am getting: 
```
InvalidArgumentError (see above for traceback): Cannot colocate nodes 'Decoder-Word-Embedding/embeddings' and 'training/Nadam/gradients/Decoder-Word-Embedding/Gather_grad/Shape: Cannot merge devices with incompatible jobs: '/job:worker/task:0' and '/job:ps/task:0'
   [[Node: Decoder-Word-Embedding/embeddings = VariableV2[container="", dtype=DT_FLOAT, shape=[4278,300], shared_name="", _device="/job:ps/task:0"]()]]
```
