### ISSUE TITLE
'tflite_convert' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by inakaaay** [tensorflow/tensorflow#20832] opened 2018-07-16 08:10 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: none
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9
- **Python version**:  3.5.1-32 bit
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: nothing since i have AMD radeon
- **GPU model and memory**:
- **Exact command to reproduce**:
```
tflite_convert \
  --output_file=/saved_model/maonani.tflite \
  --saved_model_dir=/saved_model/saved_model
```

### Describe the problem
 when i enter the command on cmd i get a response saying:

**'tflite_convert'** is not recognized as an internal or external command,
operable program or batch file.

i dont know why im getting this since i already have cloned the git repository of tensorflow

### Source code / logs

C:\Users\LENOVO-PC\tensorflow> tflite_convert \ --output_file=/saved_model/maonani.tflite \ --saved_model_dir=/saved_model/saved_model
'tflite_convert' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shashishekhar** [comment] 2018-07-16 15:59
@inakaaay : Is tflite_convert in the path, this looks like it cannot find the binary. Can you check the format of the file as well.
file tflite_convert

**Comment by inakaaay** [comment] 2018-07-16 16:07
did you mean that it is on the folder of tensorflow? @shashishekhar

**Comment by shashishekhar** [comment] 2018-07-16 16:24
Can you use something like:
bazel run //tensorflow/contrib/lite/python:tflite_convert --  --output_file=/saved_model/maonani.tflite \ --saved_model_dir=/saved_model/saved_model

**Comment by inakaaay** [comment] 2018-07-16 16:30
I did but it has a lot of errors too. check this out [https://github.com/tensorflow/tensorflow/issues/20804](url) @shashishekhar

**Comment by weishengchong** [comment] 2018-07-16 23:15
@inakaaay , how about try Linux solutions at https://stackoverflow.com/questions/51349873/tflite-convert-is-not-recognized-as-an-internal-or-external-command-in-window/51354656#51354656

**Comment by shashishekhar** [comment] 2018-07-17 15:08
No I meant:
cd C:\Users\LENOVO-PC\tensorflow
then run 
C:\Users\LENOVO-PC\tensorflow> bazel run //tensorflow/contrib/lite/python:tflite_convert -- --output_file=/saved_model/maonani.tflite \ --saved_model_dir=/saved_model/saved_model

**Comment by inakaaay** [comment] 2018-07-18 06:08
yes i did. it says ```
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/python/BUILD:1598:1: Linking of rule '//tensorflow/python:gen_linalg_ops_py_wrappers_cc' failed (Exit 1181)
LINK : warning LNK4044: unrecognized option '/lm'; ignored
LINK : fatal error LNK1181: cannot open input file 'tensorflow_framework.obj'
```

**Comment by andrehentz** [comment] 2018-08-01 18:30
Hi @inakaaay Sorry for the problems your are encountering. Unfortunately TF Lite doesn't support windows at the moment. We are hoping to have some form of support soon.

**Comment by jdduke** [comment] 2018-08-01 18:42
Duplicate of #20975.

**Closed** 2018-08-01 18:43 UTC
Labels: comp:lite

**Comment by tensorflowbutler** [comment] 2018-08-01 18:55
Nagging Assignee @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Tourenathan-G5organisation** [comment] 2018-11-29 12:58
I also have this problem which says "**tflite_convert: command not found**" . I'm running Ubuntu 18.04 and tensorflow 1.5

**Comment by ik024** [comment] 2018-12-30 06:59
I am too not able to run tflite_convert on windows. Any help ?
![image](https://user-images.githubusercontent.com/4861930/50545059-6855e780-0c2e-11e9-8f0b-4d60f3e2bde8.png)

**Comment by narin-anongchai** [comment] 2019-02-06 20:49
![image](https://user-images.githubusercontent.com/13518093/52372699-6718a580-2a8b-11e9-94b2-a7c907be2b21.png)

**Comment by MCiuzelis** [comment] 2022-10-02 12:47
> 

I am also running in an identical error, do you know a solution?

**Comment by MCiuzelis** [comment] 2022-10-02 12:48
> I also have this problem which says "**tflite_convert: command not found**" . I'm running Ubuntu 18.04 and tensorflow 1.5 I'm running the code lab code for getting tensorflow on android . Below is the code tflite_convert --graph_def_file=tf_files/retrained_graph.pb --output_file=tf_files/optimized_graph.lite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 --input_array=input --output_array=final_result --inference_type=FLOAT --input_data_type=FLOAT

I am also running in an identical error, do you know a solution?
