### ISSUE TITLE
Problem when saving/loading keras model with '.tf' extension and stateful ConvLSTM2D as a layer

### ISSUE THREAD

**Issue by nguerinjr** [tensorflow/tensorflow#31300] opened 2019-08-03 04:39 UTC
**System information**
- WSL Win10 Ubuntu 18.04 (it also happens in a real ubuntu 18)
- tf-nightly-gpu-2.0-preview==2.0.0.dev20190802 (happens in cpu and gpu)
- python3.7

**Describe the current behavior**

I have a simple test to serialized and deserialize a model which has a stateful LSTM. The 'tf' version returns an error, the 'h5' version works ok.

**Describe the expected behavior**

Correct serialization and deserialization of the code in both cases.

**Code  to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential()
model.add(layers.ConvLSTM2D(32, (3, 3), activation='relu', batch_size=32, input_shape=(1, 28, 28, 1), padding='same', strides=2,
                            stateful=True))
model.add(layers.Conv2DTranspose(64, (3, 3), strides=2, padding='same'))
model.add(layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same'))
model.compile(optimizer='adam', loss=['mse'])
model.save('teste.tf')
model = tf.keras.models.load_model('teste.tf')
print(model)
```

```python
2019-08-03 04:32:09.606349: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-08-03 04:32:09.606533: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-08-03 04:32:09.606718: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-GUERINJR): /proc/driver/nvidia/version does not exist
2019-08-03 04:32:09.607091: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-03 04:32:09.616262: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-08-03 04:32:09.617989: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ffff2cf88d0 executing computations on platform Host. Devices:
2019-08-03 04:32:09.618144: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING: Logging before flag parsing goes to stderr.
W0803 04:32:10.136887 140094640752448 save.py:130] Skipping full serialization of object <tensorflow.python.keras.layers.convolutional_recurrent.ConvLSTM2D object at 0x7f69f49960f0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
2019-08-03 04:32:10.714903: W tensorflow/python/util/util.cc:288] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
W0803 04:32:10.904490 140094640752448 deprecation.py:506] From /home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1784: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/home/nguerinjr/Documents/deep_coding_project/img_common/teste.py", line 21, in <module>
    model.save('teste.tf')
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1164, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 107, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 86, in save
    save_lib.save(model, filepath)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 855, in save
    meta_graph_def, saveable_view, signatures)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 585, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 459, in _generate_signatures
    function, mapped_inputs, resource_map)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 411, in _call_function_with_mapped_captures
    function.graph.captures, resource_map)
  File "/home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 333, in _map_captures_to_created_tensors
    .format(interior))
AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_4:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.

Process finished with exit code 1
```

**Working code  for comparisons**

When not stateful, the code works ok

```python
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential()
model.add(layers.ConvLSTM2D(32, (3, 3), activation='relu', batch_size=32, input_shape=(1, 28, 28, 1), padding='same', strides=2))
model.add(layers.Conv2DTranspose(64, (3, 3), strides=2, padding='same'))
model.add(layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same'))
model.compile(optimizer='adam', loss=['mse'])
model.save('teste.tf')
model = tf.keras.models.load_model('teste.tf')
print(model)
```

```python
2019-08-03 04:36:08.915912: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-08-03 04:36:08.916094: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-08-03 04:36:08.916278: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-GUERINJR): /proc/driver/nvidia/version does not exist
2019-08-03 04:36:08.916617: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-03 04:36:08.925594: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-08-03 04:36:08.927217: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fffe038cb10 executing computations on platform Host. Devices:
2019-08-03 04:36:08.927361: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-08-03 04:36:10.081493: W tensorflow/python/util/util.cc:288] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING: Logging before flag parsing goes to stderr.
W0803 04:36:10.614284 140013092800320 deprecation.py:506] From /home/nguerinjr/Documents/deep_coding_project/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1784: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
<tensorflow.python.keras.saving.saved_model.load.Sequential object at 0x7f56a80c2cf8>

Process finished with exit code 0
```

** Working code 2 for comparisons**

When 'h5' works ok in both cases

```python
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential()
model.add(layers.ConvLSTM2D(32, (3, 3), activation='relu', batch_size=32, input_shape=(1, 28, 28, 1), padding='same', strides=2))
model.add(layers.Conv2DTranspose(64, (3, 3), strides=2, padding='same'))
model.add(layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same'))
model.compile(optimizer='adam', loss=['mse'])
model.save('teste.h5')
model = tf.keras.models.load_model('teste.h5')
print(model)
```

```python
2019-08-03 04:37:27.733190: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-08-03 04:37:27.733380: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-08-03 04:37:27.733531: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-GUERINJR): /proc/driver/nvidia/version does not exist
2019-08-03 04:37:27.733891: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-03 04:37:27.743100: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-08-03 04:37:27.745015: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fffd380cc50 executing computations on platform Host. Devices:
2019-08-03 04:37:27.745198: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f32b028f550>

Process finished with exit code 0
```

```python
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential()
model.add(layers.ConvLSTM2D(32, (3, 3), activation='relu', batch_size=32, input_shape=(1, 28, 28, 1), padding='same', strides=2,
                            stateful=True))
model.add(layers.Conv2DTranspose(64, (3, 3), strides=2, padding='same'))
model.add(layers.Conv2D(1, (3, 3), activation='sigmoid', padding='same'))
model.compile(optimizer='adam', loss=['mse'])
model.save('teste.h5')
model = tf.keras.models.load_model('teste.h5')
print(model)
```

```python
2019-08-03 04:37:48.546310: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-08-03 04:37:48.546554: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-08-03 04:37:48.546700: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-GUERINJR): /proc/driver/nvidia/version does not exist
2019-08-03 04:37:48.547055: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-03 04:37:48.556123: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-08-03 04:37:48.557773: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fffcde1a9a0 executing computations on platform Host. Devices:
2019-08-03 04:37:48.557917: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f091c0ac860>

Process finished with exit code 0
```

**Comment by gadagashwini** [comment] 2019-08-05 07:02
I am able to reproduce the issue on Colab with tf-nightly-gpu-2.0-preview==2.0.0.dev20190802. Please take a look at [Colab](https://colab.research.google.com/drive/1QbZwhKN62RicooTE2CAzoDMmuOgWCPLk). Thanks!

**Comment by qlzh727** [comment] 2019-08-16 16:45
Assign to Kathy who works on save model.

**Comment by jvishnuvardhan** [comment] 2020-03-03 21:15
@nguerinjr  Looks like this was resolved in recent `tf-nightly`. I was not able to reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/386c2ee4d3b2ec7268bc8f576f2e7b56/31300.ipynb).

Please close the issue if it was resolved for you. Thanks!

**Comment by goldiegadde** [comment] 2020-03-04 22:13
Closing this as this issue has been fixed.

**Closed by goldiegadde** 2020-03-04 22:13 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:bug

**Comment by q-55555** [comment] 2020-04-26 13:30
I have noticed the same problem on stable tensorflow 2.1.
Is there a regression test for this ? Does it pass ?

Maybe we need to reopen this issue.

**Comment by ludwig980** [comment] 2020-06-16 02:52
I also have a similar issue on 2.2 with saving/loading models with stateful GRU layers in TF format. 

I think the issue should be reopened.
