### ISSUE TITLE
Saver is broken

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#755] opened 2016-01-12 22:16 UTC
Upon calling `self.saver.save(self.sess, os.path.join(checkpoint_dir, model_name), global_step=step)`, I get the following stack trace. 

```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 50, in main
    dcgan.train(FLAGS)
  File "/home/panmari/DCGAN-tensorflow/model.py", line 140, in train
    self.save(config.checkpoint_dir, counter)
  File "/home/panmari/DCGAN-tensorflow/model.py", line 245, in save
    global_step=step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 886, in save
    self.last_checkpoints, latest_filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 485, in update_checkpoint_state
    elif all_model_checkpoint_paths[-1] != model_checkpoint_path:
IndexError: list index out of range
```

The problem lies in this line:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L483

`all_model_checkpoint_paths` passed is not none, but an empty list, leading to the wrong branch of this if statement.

**Comment by vrv** [comment] 2016-01-12 22:18
Dupe of #751.

**Comment by panmari** [comment] 2016-01-12 22:21
@vrv is it? It could have the same cause, but the exception is raised in a completely different place.

**Comment by vrv** [comment] 2016-01-12 22:37
oh, sorry, I didn't look carefully enough.  do you think you know how to fix it?

**Comment by panmari** [comment] 2016-01-12 22:43
Well, my issue went away after changing https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L483 from

    if all_model_checkpoint_paths is None:

to 

    if all_model_checkpoint_paths is None or len(all_model_checkpoint_paths) == 0:

But it's more of a workaround than a proper fix. Still, should I make a PR?

**Comment by vrv** [comment] 2016-01-12 23:02
I would say that's a proper fix :).  The logic is just incorrect when you pass in an empty list, which seems like a valid thing to pass.  Feel free to send us a PR, or else let us know you don't want to, and we'll fix it.

**Closed** 2016-01-13 18:17 UTC
