### ISSUE TITLE
libtensorflowlite.so build not correct

### ISSUE THREAD

**Issue by 406747925** [tensorflow/tensorflow#33959] opened 2019-11-04 08:35 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): build use Linux Ubuntu 16.04,deploy on android 9.0(arm64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:None
- TensorFlow installed from (source or binary): git clone source code from master branch
- TensorFlow version:master
- Python version:anaconda python 3.6
- Installed using virtualenv? pip? conda?:source code ,none
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):ndk r19c
- CUDA/cuDNN version:none
- GPU model and memory:none

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I want to build c++ interface of tflite on android device ,using command:
bazel build -s //tensorflow/lite:libtensorflowlite.so --config=android_arm64 --cxxopt='--std=c++11' -c opt
the build could be succeed ,but the libtensorflowlite.so built is only 5784 Byte, and doesn't work correctly.

I use the same command on tensorlfow 1.15 ,and can get the right lib ,which is 2MB.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by PINTO0309** [comment] 2019-11-04 12:24
I followed this tutorial and installed the NDK r17c and SDK 29 and built it on Ubuntu. A 3.6MB aar file was generated.
**https://www.tensorflow.org/lite/guide/android**

Tensorflow v2.0.0 + Bazel 0.26.1 + Ubuntu 18.04 + Python 3.6 + ndk r17c + sdk 29
![java - ファイルマネージャー_050](https://user-images.githubusercontent.com/33194443/68120491-dce16d00-ff48-11e9-89aa-0e4df6c909af.png)
![Terminal - b920405@ubuntu: -media-b920405-Windows1-git-tensorflow2 0 0_049](https://user-images.githubusercontent.com/33194443/68120507-e539a800-ff48-11e9-8b92-13f172091171.png)

**Comment by PINTO0309** [comment] 2019-11-04 12:33
The only difference from your environment is the Ubuntu and NDK versions, but the following steps were successful.

**Tensorflow v2.0.0 + ndk r17c + sdk 29 + Ubuntu 18.04 + Python 3.6**
```bash
$ bazel build \
-s //tensorflow/lite:libtensorflowlite.so \
--config=android_arm64 \
--cxxopt='--std=c++11' \
-c opt \
--config=v2
```
![Terminal - b920405@ubuntu: -media-b920405-Windows1-git-tensorflow2 0 0_051](https://user-images.githubusercontent.com/33194443/68121012-0ea70380-ff4a-11e9-8e7f-705f737abe84.png)
![lite - ファイルマネージャー_052](https://user-images.githubusercontent.com/33194443/68121151-62195180-ff4a-11e9-8f8d-9c0f4edb25b2.png)

**Comment by fernand** [comment] 2019-11-06 17:09
I have the exact same issue: Running `bazel build -c opt --config android_arm64 //tensorflow/lite:libtensorflowlite.so` on the latest commit `965f4b71f0c719f5466fe0f25f326593ae9e220a` yields a 5.7K `libtensorflowlite.so` (no build errors), while the randomly picked commit `1cf6cb79156d488fd97504ecc6744cd0ab2d31fa` from ~2 weeks ago properly yields 2.3 MB binary .so file.
Using the recommended Bazel and Android NDK versions.

**Comment by jdduke** [comment] 2019-11-07 03:51
Thanks for flagging the issue, this does look like a recent regression, likely due to our use of the TF build rule for generating a binary. We'll try to get a fix out quickly, but in the meantime you can sync to a slightly earlier build.

**Comment by multiverse-tf** [comment] 2019-11-07 06:02
FYI, this is caused by commit f58c9f835c32e02895bdd629c7660567ae011001. So, another alternative is to comment out "build --incompatible_remove_legacy_whole_archive" in tensorflow/.bazelrc.

**Comment by fernand** [comment] 2019-11-07 06:12
Thank you!

**Comment by terryheo** [comment] 2019-12-10 07:51
Let me close this since it's working well now.

**Closed by terryheo** 2019-12-10 07:51 UTC
Labels: TF 1.15, comp:lite, type:support
