### ISSUE TITLE
Tensorflow 1.14.0 with C++17 Custom Op Has Binary Incompatibility

### ISSUE THREAD

**Issue by golden0080** [tensorflow/tensorflow#31568] opened 2019-08-12 23:36 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, I have a custom op written in CUDA.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.14.0
- Python version: 3.5.6
- Bazel version (if compiling from source): 0.25.1
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia GTX 1080

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I ran ```tf.load_library("my_ops.so")```
It will complain about:
```
NotFoundError: my_ops.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeESt17basic_string_viewIcSt11char_traitsIcEE
```

**Describe the expected behavior**
Successfully `load_library`

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Tensorflow 1.14 was built with `bazel build --config=opt --config=cuda  --copt=-march=native --copt=-mfpmath=both //tensorflow/tools/pip_package:build_pip_package`
My custom op is built with Bazel.

**Comment by ravikyram** [comment] 2019-08-13 06:34
@golden0080 

Can you please provide detailed reproduction instructions to reproduce it on our environment.Thanks!

**Comment by golden0080** [comment] 2019-08-19 22:30
@ravikyram Sorry I was busy. I'm trying to get you a reproducible example for my issue.

**Comment by ravikyram** [comment] 2019-09-05 08:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-09-05 08:26 UTC
Labels: TF 1.14, comp:runtime, stat:awaiting response, type:support

**Comment by pmh47** [comment] 2019-10-29 00:05
I ran into the same issue using tensorflow 1.13.1 and gcc 7.4, and fixed it by patching `tensorflow/include/absl/base/config.h` to not define `ABSL_HAVE_STD_STRING_VIEW` even when the C++17 `string_view` is detected (by commenting line 432).

**Comment by golden0080** [comment] 2019-12-13 23:07
I tested in my code base, using bazel to patch absl, and it worked! I think the TF were not using `C++ string_view` correctly thus resulted in missing symbols.
