### ISSUE TITLE
Merge bn with depthwise conv for *.bp 

### ISSUE THREAD

**Issue by holyhao** [tensorflow/tensorflow#28958] opened 2019-05-23 07:19 UTC
**System information**
- TensorFlow version (you are using):1.10
- Are you willing to contribute it (Yes/No):yes

I used graph_transforms  and optimize_for_inference to optimize the freeze_graph. I  focus on merging bn with  conv layers to speed up the inference time. But both method can only merge bn with CONV2D, and can not merge bn with DEPTHWISE CONV. As far as  i know, the tool toco can merge all the conv with  bn to *.tflite. So, will the graph_transforms support to do so for *.bp.

**Comment by muddham** [comment] 2019-05-27 11:07
@holyhao Please refer the [link](https://github.com/google-research/morph-net/issues/32) and let us know if that answers your query

**Comment by holyhao** [comment] 2019-05-27 12:17
@muddham It has nothing to do with it, i want a optimizer for *bp to merge the bn with  DEPTHWISE CONV.

**Comment by jvishnuvardhan** [comment] 2019-05-29 18:48
@holyhao Can you try latest version of TF (1.13.1 or 2.0) and check whether the issue is persisting? Could you provide any standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-06 03:03
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-06 03:03 UTC
Labels: comp:keras, stat:awaiting response, type:feature
