### ISSUE TITLE
bug report:All feature_columns must be _FeatureColumn instances. Given: SequenceNumericColumn(key='volume', shape=(1,), default_value=0.0, dtype=tf.float32, normalizer_fn=None)

### ISSUE THREAD

**Issue by anavanab99** [tensorflow/tensorflow#39316] opened 2020-05-08 14:01 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install 
- TensorFlow version (use command below): tensorflow-gpu 2.2.0 and 2.1.0
- Python version:python3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:8g

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
my code is:
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow import feature_column
from tensorflow.keras.experimental import SequenceFeatures

volume = feature_column.sequence_numeric_column('volume')
lstm_columns = [volume]
features = tf.io.parse_example(..., features=feature_column.make_parse_example_spec(lstm_columns))

sequence_feature_layer = SequenceFeatures(lstm_columns) #返回特征列的长度和 tensor
sequence_input, sequence_length = sequence_feature_layer(features)

**Describe the current behavior**

Traceback (most recent call last):
  File "/home/zy/PycharmProjects/keras-tcn-master/brain_LD.py", line 104, in <module>
    features = tf.io.parse_example(..., features=feature_column.make_parse_example_spec(lstm_columns))
  File "/home/zy/anaconda3/envs/tf1/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column.py", line 806, in make_parse_example_spec
    'Given: {}'.format(column))
ValueError: All feature_columns must be _FeatureColumn instances. Given: SequenceNumericColumn(key='volume', shape=(1,), default_value=0.0, dtype=tf.float32, normalizer_fn=None)

 it looks like a bug ? can you fix it?

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2020-05-12 07:17
@anavanab99 
Code provided seems incomplete, In order to expedite the trouble-shooting process, please provide a simple standalone code to reproduce the issue reported here, if possible share a colab gist to analyse the error Thanks!

**Comment by anavanab99** [comment] 2020-05-12 10:25
I solved the problem by reinstalling tensorflow, but another problem bothered me. The cases in the official tensorflow documentation are as follows:
        dnn_activation='relu'
        volume = tf.feature_column.numeric_column('volume', shape=number_shape)
        l_list=[volume]
        features = tf.io.parse_example(
                serialized=record, features=tf.feature_column.make_parse_example_spec(l_list))
        input_l=keras.layers.DenseFeatures(l_list)
        dnn1=keras.layers.Dense(300,activation=dnn_activation)(input_l)
        output=keras.layers.Dense(1,activation='tanh')(dnn1)
        model = Model(inputs = [input_l],outputs = [output])
        model.compile(loss = "mae",optimizer = "Adam")


I tried to input the feature column to keras model, but the code features = tf.io.parse_example (
                 serialized = record, features = tf.feature_column.make_parse_example_spec (l_list))
In the case of serialized = record, what type of object should be filled here to complete parse_example? I studied the official API carefully, but the official API filled in serialized = ... instead. I can't understand how to complete the code. I tried to fill in various methods such as tfrecord, fill in tensor, and I couldn't complete the code. My data is a csv file. Can you provide a complete example, including data reading, feature column processing, and training?? I really cannot complete the code. Thank you very much, this is very important to me. Thank you very much, my email: 402868327@qq.com

**Comment by anavanab99** [comment] 2020-05-13 04:15
> @anavanab99
> Code provided seems incomplete, In order to expedite the trouble-shooting process, please provide a simple standalone code to reproduce the issue reported here, if possible share a colab gist to analyse the error Thanks!

I solved the problem by reinstalling tensorflow, but another problem bothered me. The cases in the official tensorflow documentation are as follows:
dnn_activation='relu'
volume = tf.feature_column.numeric_column('volume', shape=number_shape)
l_list=[volume]
features = tf.io.parse_example(
serialized=record, features=tf.feature_column.make_parse_example_spec(l_list))
input_l=keras.layers.DenseFeatures(l_list)
dnn1=keras.layers.Dense(300,activation=dnn_activation)(input_l)
output=keras.layers.Dense(1,activation='tanh')(dnn1)
model = Model(inputs = [input_l],outputs = [output])
model.compile(loss = "mae",optimizer = "Adam")

I tried to input the feature column to keras model, but the code features = tf.io.parse_example (
serialized = record, features = tf.feature_column.make_parse_example_spec (l_list))
In the case of serialized = record, what type of object should be filled here to complete parse_example? I studied the official API carefully, but the official API filled in serialized = ... instead. I can't understand how to complete the code. I tried to fill in various methods such as tfrecord, fill in tensor, and I couldn't complete the code. My data is a csv file. Can you provide a complete example, including data reading, feature column processing, and training?? I really cannot complete the code. Thank you very much, this is very important to me. Thank you very much, my email: 402868327@qq.com

**Comment by anavanab99** [comment] 2020-05-13 04:17
> @Saduf2019 
> Code provided seems incomplete, In order to expedite the trouble-shooting process, please provide a simple standalone code to reproduce the issue reported here, if possible share a colab gist to analyse the error Thanks!

I solved the problem by reinstalling tensorflow, but another problem bothered me. The cases in the official tensorflow documentation are as follows:
dnn_activation='relu'
volume = tf.feature_column.numeric_column('volume', shape=number_shape)
l_list=[volume]
features = tf.io.parse_example(
serialized=record, features=tf.feature_column.make_parse_example_spec(l_list))
input_l=keras.layers.DenseFeatures(l_list)
dnn1=keras.layers.Dense(300,activation=dnn_activation)(input_l)
output=keras.layers.Dense(1,activation='tanh')(dnn1)
model = Model(inputs = [input_l],outputs = [output])
model.compile(loss = "mae",optimizer = "Adam")

I tried to input the feature column to keras model, but the code features = tf.io.parse_example (
serialized = record, features = tf.feature_column.make_parse_example_spec (l_list))
In the case of serialized = record, what type of object should be filled here to complete parse_example? I studied the official API carefully, but the official API filled in serialized = ... instead. I can't understand how to complete the code. I tried to fill in various methods such as tfrecord, fill in tensor, and I couldn't complete the code. My data is a csv file. Can you provide a complete example, including data reading, feature column processing, and training?? I really cannot complete the code. Thank you very much, this is very important to me. Thank you very much, my email: 402868327@qq.com

**Comment by Saduf2019** [comment] 2020-05-13 04:31
@@anavanab99 
As the reported issue is resolved please create a new issue for the new issue faced.

**Comment by Saduf2019** [comment] 2020-06-05 05:39
@anavanab99
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by Saduf2019** 2020-06-05 05:39 UTC
Labels: TF 2.1, type:bug

**Comment by Zachary4biz** [comment] 2021-05-15 03:35
I have this "bug" in applying "sequence_numeric_column" tf1.15.
exactly same error! but what should I do to fix this?
I've tried reinstall tensorflow, nothing changes. Plz help
