### ISSUE TITLE
interperter with GPU Delegate blocks Android from rendering on Main thread.

### ISSUE THREAD

**Issue by noamfreeman** [tensorflow/tensorflow#43073] opened 2020-09-09 11:29 UTC
**System information**
- Have I written custom code: Yes.
- OS Platform and Distribution: Android 27, 28, 29, and more
- Mobile device Samsong Galaxy S10, A30, J6, Pixel 3, 4a, ....
- TensorFlow imported as a gradle dependancy. 
- TensorFlow version 2.2.0 / 2.3.0

**Describe the current behavior**
I've created an interperter, and ran it without the `GpuDelegate`, everyting works fine.
both creation and `interperter.run` are running **not** on the main thread, but on another thread.
this thread has it's own GL context, which is **not** the same as the main thread.

When i add the `GpuDelegate` to the interperter options, aside from the model running much faster,
it blocks me from rendering animations in the main thread. 
this happens with Lottie animations, View animations, and simple android views like `ProgressBar`.
all the animations freeze while the interperter is running.

the included image shows the main thread and the tread running the interperter.
the tiny stack in the left in the main therad, is a Lottie animation view render call, and the main thread is stuck in `syncAndDrawFrame` until the interperter is finished (which in this case is  ~200ms on a flagship device, which is super fast for this interperter, but an eternity for the main thread.)
![202009092340696141122502934](https://user-images.githubusercontent.com/37263856/92591818-4045d500-f2a7-11ea-8f52-53da69a74f5a.jpg)

I assume the `GpuDelegate` consumes all the GPU resources for my interperter.

**Describe the expected behavior**
the interperter invocation should not interfere with other threads, or at least other GL context, and should not block the main thread.

**Comment by bhack** [comment] 2020-09-09 12:11
Can you take a look at https://github.com/tensorflow/tensorflow/issues/25657 about  GL context handling?

**Comment by noamfreeman** [comment] 2020-09-09 12:19
AFAIK, there are 3 issues there:
* blocking the calling thread (when it is not the same as the one creating the interpreter)
* overheating 
* frame rate dropping *after* the inrefence.

here, i have a different thread (and GL context), that creates and runs the interpreter,
and the Delegate blocks the *main* thread.
i'm pretty sure it has something to do with the GL Context, but i didn't find something usefull there.

**Comment by teijeong** [comment] 2020-09-22 05:41
HI @lrdxgm, can you take a look?

**Comment by lrdxgm** [comment] 2020-09-22 19:21
I'm not really familiar with OpenGL contexts in multithreaded environment, so I'm no good if the issue is related to that.

Are you using OpenGL backend? (The alternative is the OpenCL backend.) Is the data source for the inference an OpenGL object (e.g. a texture)? If the answer to both questions is no, you can try building TFLite and the GPU delegate with -DCL_DELEGATE_NO_GL to disable the OpenGL ES integration. This compile flag was introduced to target desktop Linux, but it should also work on Android.

Also do note that some GPUs are not capable doing compute and graphics concurrently; As far as I understand this includes Qualcomm Adrenos, so long-running kernels will affect graphics. Make sure threads running GPU inference are lower priority than threads doing graphics, so context switches are possible.

**Comment by noamfreeman** [comment] 2020-09-23 05:56
we just imported the regular artifact using gradle, so i assume it's GL backend. `org.tensorflow:tensorflow-lite-gpu:2.2.0`
the data is not an openGL object, but a direct buffer allocated in JAVA.

changing proirities of threads does not have any effect. 
most of our devices have Adernos GPU, but i'l check if it happens also on Mali.

**Comment by GEllickson-Hover** [comment] 2021-05-12 18:46
Hello, I have a similar issue, and I'm wondering if we can get any more clarity on how the GpuDelegate works. 

I'm currently trying a fairly heavyweight feature extraction model with GpuDelegate from tf lite `2.4.0`. I have a simple CameraX setup that analyzes images async, so I can see how it performs over repetitions. On my Samsung S10+, the model takes about 300ms with the delegate, but the entire OS graphics layer will jank very badly. I turned on their GpuWatch feature in developer settings to see Gpu usage, and running it in this fashion will lead to 100% Gpu spikes and slow down the entire OS graphical output. I tried setting low thread priority on the analyzer thread that runs the delegate as well, which didn't seem to do anything. Alternatively, running on CPU instead and setting 4 threads leads to about 80% CPU utilization at highest, albeit much slower inference times.

I'm wondering then, will using GpuDelegate with a long running model starve the OS graphics layer of frame updates or is there maybe a way to de-prioritize or batch the model's GPU computations? I had been hoping there's some built in mechanism of some sort that the system can prefer frame updates over heavy computations like this.

**Comment by sushreebarsa** [comment] 2021-08-09 14:25
@noamfreeman It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Comment by piisku78** [comment] 2021-09-01 07:19
I am using the latest TF 2.5 and the problem still exists. @sushreebarsa could you re-open this and check the issue, thanks.

**Comment by GEllickson-Hover** [comment] 2021-09-01 17:31
@piisku78 I believe this is at least partly due to how at least some GPU work as @lrdxgm alluded to as well. Taking a look this [Adreno GPU doc](https://developer.qualcomm.com/qfile/33472/80-nb295-11_a.pdf) (one of the most common GPUs) in section 3.4 it says that long-running GPU compute kernels can block the graphics pipeline, so they recommend making sure the work is in the 10s of milliseconds. We similarly had an issue with a model that ran for 150ms or longer depending on the device and it was totally unusable on GPU because of the jank that it caused on the entire OS UI. I get the sense that using GPU is unviable for long-running models at this time.

Not entirely sure what TF Lite could do then, but maybe it's possible work could be batched for GPU, but that might get pretty complicated. That doc is also for OpenCL, so not sure if using OpenGL would make any difference in how the work is distributed on GPU.

**Comment by sushreebarsa** [comment] 2021-09-20 06:49
@noamfreeman @piisku78 Reopening this issue as the problem still persists as per the [comment](https://github.com/tensorflow/tensorflow/issues/43073#issuecomment-910000033).Thanks!

**Comment by noamfreeman** [comment] 2023-07-23 07:25
i think not. thanks

**Comment by pkgoogle** [comment] 2023-07-25 18:47
@noamfreeman, awesome, do you mind closing the issue as completed if you have no more open items here? Thanks!

**Closed** 2023-07-26 10:44 UTC
Labels: stat:awaiting response, type:bug, comp:lite, TF 2.5, TFLiteGpuDelegate
