### ISSUE TITLE
No OpKernel was registered to support Op 'OneHot' with these attrs. Tensorflow1.4

### ISSUE THREAD

**Issue by cuevas1208** [tensorflow/tensorflow#15049] opened 2017-12-01 21:53 UTC
I have trained and saved a CNN model in python Tensorflow 1.3. 
I can successfully load and run the graph previously saved from my python model in Tensorflow 1.4 using CPU and c++ with no problem; but when I tried to load the same graph using Tensorflow 1.4 using GPU c++ and I get the following error:

`-		status	{state_=unique_ptr {code=INVALID_ARGUMENT (3) msg="No OpKernel was registered to support Op 'OneHot' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:\n  <no registered kernels>\n\n\t [[Node: one_hot = OneHot[T=DT_FLOAT, TI=DT_INT32, _... } }	tensorflow::Status
`

My system:
Windows 10
Cuda 8.0
Cudnn 6
cmake cmake-3.9.4-win64-x64
Python 3.5.2
VS2015
@cuevas1208

**Comment by tensorflowbutler** [comment] 2017-12-02 06:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cuevas1208** [comment] 2017-12-04 14:10
OS Platform and Distribution   = Windows 10 Pro 64-bit (build 15063) 
TensorFlow installed from        = https://github.com/tensorflow/tensorflow/archive/v1.4.0.zip
TensorFlow version                  = 1.4.0
Bazel version                            = N/A I am using cmake cmake-3.9.4-win64-x64
CUDA/cuDNN version              = Cuda 8.0/Cudnn 6
GPU model and memory         = NVIDIA Quadro M4000, VRAM 8152MB
Exact command to reproduce  = N/A running it in visual studio 2015

**Comment by facaiy** [comment] 2017-12-07 16:46
Could you give more details about your code and log? AFAIK, OneHot[T=DT_FLOAT, TI=DT_INT32] kernel is registered for GPU.

**Comment by reedwm** [comment] 2017-12-08 20:21
As @facaiy stated, can you post a code sample to reproduce the problem? OneHot does have both CPU and GPU implementations, but the error messages implies it has no implementation.

**Comment by tensorflowbutler** [comment] 2018-01-03 07:46
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by BrightJoy** [comment] 2018-01-05 04:31
When creating a Project file using the CMake program, one_hot_op.cc and one_hot_op.h files are not included in the tf_core_kernels.vcxproj file.

After the build is done manually, I can check the result properly by applying the simple C ++ code const-> one_hot-> clientsession class using the corresponding library and object file.

However, a little more complex sample code
Using FifoQueue, QueueEnQueue
Samples using FixedLengthRecordReader-> ReaderReadUpTo-> DecodeRaw-> OneHot will show abnormal termination in r1.5 version.
This sample performs normal operation in r1.3.

This sample works normally when the OneHot is disconnected, but it ends abnormally when connecting OneHot. (stack -> PollLoop, PoolEvent....)

CMake generation will require one_hot_op.cc and one_hot_op.h files to be included.
and OneHot ...

**Comment by reedwm** [comment] 2018-01-05 19:11
@mrry can you resolved the CMake issue?

**Comment by mrry** [comment] 2018-01-05 22:07
You could try removing this line from `tf_core_kernels.cmake`:

https://github.com/tensorflow/tensorflow/blob/5386775e64aac0bb5020974122645da900bc312a/tensorflow/contrib/cmake/tf_core_kernels.cmake#L188

I believe it was disabled on GPU due to an Eigen/MSVC compilation error, but perhaps the tools have advanced sufficiently to make it no longer a problem?

**Comment by tensorflowbutler** [comment] 2018-01-24 13:16
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-08 19:18
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-23 13:54
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment] 2018-02-23 18:15
Closing for now due to a lack of a response to @mrry's comment. @BrightJoy @cuevas1208, feel free to reopen if @mrry's comment does not resolve the issue.

**Closed by reedwm** 2018-02-23 18:15 UTC
Labels: stat:awaiting response
