### ISSUE TITLE
GradientDescentOptimizer requires explicit variable listing after being called once in a different session

### ISSUE THREAD

**Issue by samgalen** [tensorflow/tensorflow#829] opened 2016-01-21 16:55 UTC
When I run 
[debugger.txt](https://github.com/tensorflow/tensorflow/files/99486/debugger.txt), I get a TypeError because the operation gradstep yields an empty list. However, when I comment out the first attempt to gather a gradient, or add the argument `var_list=[W,b]` to the second attempt, this error does not occur. It seems like somehow there's an issue with identifying the var_list implicitly, after having run (and closed) the previous session.

**Comment by yaroslavvb** [comment] 2016-01-28 21:46
Hm....can't reproduce this at head. Closing/reopening the session doesn't seem to affect the list of trainable variables. Can you check at which point you are losing the trainable variables? That's the list that optimizer uses to identify the variables implicitly --
[v.name for v in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)]

**Comment by vrv** [comment] 2016-02-06 22:12
I think we fixed this some time in December but after our last 0.6.0 release.  We're hoping to release a newer version soon, but it should also be fixed at HEAD if you have the ability / patience to install from sources.

Feel free to re-open if it's still broken at HEAD.

**Closed by vrv** 2016-02-06 22:12 UTC
