### ISSUE TITLE
install TF using Anaconda

### ISSUE THREAD

**Issue by Leepengfei** [tensorflow/tensorflow#21342] opened 2018-08-02 14:21 UTC
Hi

Using "Use pip in Anaconda" installation method to install TF on ubuntu 16.04 system with Intel Xeon E5645 CPU, I test installation which give a error message "Illegal instruction (core dumped)". **Why?**

But when I use conda in Anaconda to install TF directly ("conda install tensorflow"), I can test installation successfully. **Can this installation method install TF-CPU and TF-GPU versions at the same time？**

Alan

**Comment by param087** [comment] 2018-08-02 15:29
Alan tf-gpu and tf-cpu are completely different to install and some items the tf-gpu is default when downloading.
Please check that you can import tensorflow as
- import tensorflow as tf
It might happen that you install tf-gpu and your pc does not support it. So uninstall the tensorflow and download CPU version from tensorflow website using pip/pip3 in anaconda command line or from the anaconda website to import tensorflow special to your pc configuration.

**Comment by param087** [comment] 2018-08-02 15:31
Try this https://anaconda.org/conda-forge/tensorflow

**Comment by gunan** [comment] 2018-08-02 16:09
The issue is about your CPU model, not the installation. closing.

**Closed by gunan** 2018-08-02 16:09 UTC
