### ISSUE TITLE
Android Demo build Error

### ISSUE THREAD

**Issue by Kuntal-G** [tensorflow/tensorflow#1598] opened 2016-03-23 14:46 UTC
Get an error when building the Android demo on Ubuntu 14.04.

My Workspace setting for Android SDK and NDK are given below:

android_sdk_repository(
name = "androidsdk",
api_level = 23,
build_tools_version = "23.0.1",
path = "/home/kuntal/Android/Sdk"
)

android_ndk_repository (
name = "androidndk",
path = "/home/kuntal/knowledge/IDE/android/android-ndk-r10e/",
api_level = 21
)

Also i have the proper version in the SDK/NDk repo. NDK version (r10e).

Now im trying to build with bazel using the following command:

sudo bazel build tensorflow_demo -c opt --copt=-mfpu=neon

And i even tried with sudo bazel build tensorflow_demo

_but i'm getting the following error:_

INFO: Found 1 target...
**ERROR: **/home/kuntal/knowledge/codebase/PRACTICE/BIG-DATA/TensorFlow/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar ... (remaining 13 argument(s) skipped).
src/main/tools/namespace-sandbox.c:558: mount(opt->mount_sources[i], full_sandbox_path, NULL, MS_REC | MS_BIND | MS_RDONLY, NULL): Permission denied
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.950s, Critical Path: 0.14s

Please suggest how to fix this issue??

**Comment by petewarden** [comment] 2016-03-24 17:18
Andrew, does this look familiar?

**Comment by andrewharp** [comment] 2016-03-24 20:06
@Kuntal-G Which version of Bazel are you using?

**Comment by Kuntal-G** [comment] 2016-03-25 07:12
I'm using Bazel version 0.2.0 and i installed bazel with this  bazel-0.2.0-installer-linux-x86_64.sh

**Comment by andrewharp** [comment] 2016-04-01 18:27
WORKSPACE parsing should be just about the first thing that happens when building, so make sure there are no other changes introduced there that could be causing an issue.

Also, other users have had problems with a trailing slash on paths, so I'd try removing the one on your ndk path and see what happens.

**Comment by Kuntal-G** [comment] 2016-04-03 10:13
@andrewharp  I tried with new ndk path as mentioned.but getting same error.

But i was able to build my android .apk file by importing the project into Android studio and building with gradle.

May be i will give deeper look into this bazel build failure issue later on.

**Comment by andrewharp** [comment] 2016-04-27 22:40
Glad you were able to find a workaround. Closing this now as I can't reproduce myself. Please reopen if you try again and still experience issues.

**Closed by andrewharp** 2016-04-27 22:40 UTC
