### ISSUE TITLE
quantization: errror during quantizing bert model

### ISSUE THREAD

**Issue by huanghaifeng1** [tensorflow/tensorflow#31680] opened 2019-08-16 09:48 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux version 3.10.107-1-tlinux2_kvm_guest-0048, Red Hat 4.8.2-16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
i want to use quantize_graph.py to quantize bert model under tensorflow/tool/quantization on git branch r1.11, but load generated pb file generated error
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
i use the script to convert the model
```
python quantize_graph.py --input=/root/batch-bert-op/2layer_model.pb --output_node_names="classifier/predict_probability" --output=/root/batch-bert-op/eight_bit.pb --mode=eightbit
```
in which 2layer_model.pb is the original pb and eight_bit.pb is the generated pb. 2layer_model.pb can be loaded and get inference result successfully but eight_bit.pb produce error. the code to load the pb file is:
```
with tf.Session() as sess:
    g = tf.Graph().as_default()
    pb_file = sys.argv[1]
    with open(pb_file, "rb") as f:
        g_def = tf.GraphDef()
        g_def.ParseFromString(f.read())
        _ = tf.import_graph_def(g_def, name="")
```
after i remove this line in quantize_graph.py I can load quantized pb successfully but inference take 4s while the original pb takes only 200ms
```
self.set_input_graph(graph_util.remove_training_nodes(self.input_graph, protected_nodes=output_node_names))
```
probability the error is introduced by remove_training_nodes, but without it, inference time is tremendous.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
The full traceback is below:
```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

-I/root/anaconda3/envs/py36tf113/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
2019-08-16 19:09:44.358947: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-08-16 19:09:44.384488: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494140000 Hz
2019-08-16 19:09:44.384818: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7f2a68c2d470 executing computations on platform Host. Devices:
2019-08-16 19:09:44.384885: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #213: KMP_AFFINITY: cpuid leaf 11 not supported - decoding legacy APIC ids.
OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 1 packages x 8 cores/pkg x 1 threads/core (8 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 4 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 5 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 6 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 7 
OMP: Info #250: KMP_AFFINITY: pid 9830 tid 9830 thread 0 bound to OS proc set 0
2019-08-16 19:09:44.419205: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/root/anaconda3/envs/py36tf113/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bert/embeddings/cond/Slice/begin}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pb_inference_test.py", line 122, in <module>
    _ = tf.import_graph_def(g_def, name="")
  File "/root/anaconda3/envs/py36tf113/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/py36tf113/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bert/embeddings/cond/Slice/begin}}



```

**Comment by zhoujianqian** [comment] 2019-08-19 12:47
Are you quantize bert in CPU or in mobile phone.

**Comment by huanghaifeng1** [comment] 2019-08-19 14:49
> Are you quantize bert in CPU or in mobile phone.

i want to use it in CPU instead of mobile phone.

**Comment by oanush** [comment] 2019-08-20 09:34
@huanghaifeng1 ,
In order to expedite the trouble-shooting process, please provide compelete code snippet to reproduce the issue reported here. Thanks!

**Comment by zhoujianqian** [comment] 2019-08-20 09:50
I  also quantize bert model in CPU，i quantized it success，but the output result is wrong。precision is lost.

**Comment by oanush** [comment] 2019-08-27 12:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-27 12:13 UTC
Labels: TF 1.13, comp:apis, stat:awaiting response, type:support
