### ISSUE TITLE
tf.while_loop allow to vary shapes by default

### ISSUE THREAD

**Issue by vasilevskykv** [tensorflow/tensorflow#45538] opened 2020-12-09 10:57 UTC
I tried everything with tf.while_loop. In nested loops I always get ValueError due to the shape. 
I think the problem is with **shape_invariants**.
In my opinion, it's a **bad feature that a developer should think about the initial shape of the loop variable**. I think that **to allow the shape to vary across iterations must be by deafult**. 
So one more parameter should be, for exmaple, **shape_variation**, that can be **True** or **False**. If **shape_variation = False** - we need to define **shape_invariant**. If **shape_variation = True** - shape has been allowed to vary across iterations, so **shape_invariant doesn't need to be defined**.

So in my opinion, it is necessary to correct this feature in the way I suggested

**Comment by ravikyram** [comment] 2020-12-09 11:48
@vasilevskykv 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by vasilevskykv** [comment] 2020-12-09 12:29
The case of every loop. The developer doesn't need to be concerned about the shape. It is impossible to make a correct nested loop because of the **shape_invariant**. Because the ValueError will be always:
`ValueError: Input tensor 'while/while/Const:0' enters the loop with shape (), but has shape (3,) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.`

**Comment by ravikyram** [comment] 2020-12-09 12:42
@vasilevskykv 

Looks like duplicate of #45337. Can we close the issue here and track in #45337. Thanks!

**Comment by vasilevskykv** [comment] 2020-12-09 12:54
The problem in 45337 didn't solve

**Comment by pandrey-fr** [comment] 2020-12-10 18:20
> The developer doesn't need to be concerned about the shape.

Yes, they do. Providing exact shapes yields optimized computation graphs, which is often critical in writing efficient operations, layers and models. Similarly, while `shape_invariants` allows to relax part of the loop variables' shapes, it also enables optimizing what can be (by partially or fully defining the shape of some of the variables). Having a coercive behavior as default can also be seen as a way to have developers offer some thoughts to what they are doing, and therefore push them towards writing better code - which is what they are supposed to do, in my humble opinion.

If you are truly annoyed about writing specs, you may try to write loops in a pythonic way and have Autograph take on part of the work.

**Closed** 2021-01-27 20:37 UTC
Labels: stalled, stat:awaiting response, type:feature
