### ISSUE TITLE
tf.estimator package not installed appears in ops_to_register.h when bazel-bin/tensorflow/python/tools/print_selective_registration_header is executed

### ISSUE THREAD

**Issue by iamagirlforios** [tensorflow/tensorflow#23920] opened 2018-11-22 09:51 UTC
**System information**
OS Platform and Distribution: maxOS High Sierra 10.13.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.0
- Python version: 2.7
- Installed using virtualenv? pip? conda?:conda
- Bazel version:0..18.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:   Not supported when confugurate

**Comment by karmel** [comment] 2018-12-03 22:13
I do not understand what exactly the issue is from the title above-- can you clarify what command you executed, and what the error was?

**Comment by harshini-gadige** [comment] 2018-12-14 21:54
Closing this as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen(if required).

**Closed by harshini-gadige** 2018-12-14 21:54 UTC
Labels: stat:awaiting response
