### ISSUE TITLE
Input shape for convolution1D 

### ISSUE THREAD

**Issue by gharshini** [tensorflow/tensorflow#44082] opened 2020-10-16 10:43 UTC
PI have sparse coefficients array of shape 1D. Each value in the 1D array corresponds to one class. For example, I just have an array
a = [1,2,3,4,4,5,6,78,8543,35,878,.............]
class_label = [1,1,1,2,2,3,3,1,2,......]

How should I input this to Convolution1D? It always gives me an error of input dimensions.

**Comment by ravikyram** [comment] 2020-10-16 10:52
@gharshini 

This is the duplicate of #44065.Please, close the issue here and can track the issue in #44065. THanks!

**Closed** 2020-10-16 13:48 UTC
Labels: stat:awaiting response, type:support
