### ISSUE TITLE
Tensorflow Training Freezes for sometime, then continue on its own, happen multiple times when training a model

### ISSUE THREAD

**Issue by todpole3** [tensorflow/tensorflow#9061] opened 2017-04-08 01:34 UTC
I recently upgraded to Tensorflow 0.12.1, Python3, Ubuntu 14.04, Cuda 8.0, Cudnn 5.1

Then I run my old code written for Tensorflow 0.10.1, which is a simple sequence-to-sequence model. And the training keeps freeze in the middle.

After some time the training will continue normally. Sometimes it 1 or 2 minutes, and sometimes it takes about 5 to 6 hours.

Anyone has opinion on how to trouble-shoot this?

**Comment by asimshankar** [comment] 2017-04-08 01:39
Are you able to try with TensorFlow 1.0? 

To troubleshoot, it would help greatly if you can provide a small self-contained piece of code that reproduces the problem.

**Comment by todpole3** [comment] 2017-04-08 01:48
The code worked no problem with TF 0.10.1 + Cuda 7.5 + Cudnn 4. 
I didn't upgrade to TF 1.0 hence cannot try it immediately.

The code that occasionally cause the freezing problem is very similar to the TF seq2seq example.
https://github.com/TellinaTool/learning_module/blob/master/encoder_decoder/framework.py

I'm not sure if it's possible to pin-point at which line it freezes.

**Comment by asimshankar** [comment] 2017-04-08 05:00
Unfortunately, that information isn't much to go by - there are many variables at play here - CUDA versions, NVIDIA driver versions, TensorFlow version, any hiccups in the input feeding etc.

Since there isn't enough information available to help track this down, I'm going to close this issue out. If you are able to get new information (preferably with release 1.0+) that can help zone in on the problem a bit more, please do reopen this issue and/or file a new one with more information.

Thanks!

**Closed by asimshankar** 2017-04-08 05:00 UTC

**Comment by peterfig** [comment] 2017-09-18 02:23
I'm having the same problem.  I'm on CPUs so we can rule out CPU/GPU issues.  Also occuring with Keras 2.0.8, TF 1.3, both python 2.7 and 3.5, and also a TF 1.4-dev compiled from sources.  This leads me to believe it's an input feed issue.

Another note, the same code and inputs run fine on my Macbook.  I'm getting the problem with a new install on a workstation.   It's a VirtualBox instance running Ubuntu server 16.04.

Maybe someone could suggest an input feed diagnostic?
