### ISSUE TITLE
inter_op_parallelism_threads on Window for GPU models

### ISSUE THREAD

**Issue by MatthiasDING** [tensorflow/tensorflow#10187] opened 2017-05-25 08:41 UTC
I need to limit CPU usage of tensorflow on Windows by setting inter_op_parallelism_threads = 1 , ( intra_op_parallelism_threads = 1  also for CPU)

When I run a model on CPU, inter_op_parallelism_threads = 1  works perfectly, and only one logical core is used.

But when I run a model on GPU,  inter_op_parallelism_threads =1 doesn't work,  tensorflow still uses all the available logical cores.

**Comment by jart** [comment] 2017-05-26 03:49
This might be a duplicate of https://github.com/tensorflow/tensorflow/issues/4455. See mrry's comment. Maybe what you want to do is pass that option to the server.

**Closed by jart** 2017-05-26 03:49 UTC
