### ISSUE TITLE
Internal error while saving an image to GCS (during evaluation)

### ISSUE THREAD

**Issue by Hafplo** [tensorflow/tensorflow#22833] opened 2018-10-09 09:00 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian (c2-deeplearning-tf-1-11-cu100-20181001)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: Nvidia V100 , 16GB
- **Exact command to reproduce**: models/research/object_detection/legacy/eval.py

### Describe the problem
While evaluating my model using the [object detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) , I am saving images with the export_dir flag. The images are saved to GCS (google cloud bucket).
Once in a while, I encounter an InternalError that I traced back to [here](https://github.com/tensorflow/tensorflow/blob/ce1cdd52eda4b40ff8fb8c09bc178210883b3773/tensorflow/core/platform/cloud/gcs_file_system.cc#L410)
I am unable the reproduce it, since this happens unexpectedly, and on rare occasions, but it stops the evaluation job and requires restarting the machine.

Might be related - just before this error, I recieve a RuntimeWarning about true_divide

### Source code / logs
`
models/research/object_detection/utils/metrics.py:142: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
Traceback (most recent call last):
  File "object_detection/legacy/eval.py", line 150, in <module>
    tf.app.run()
  File "models/.env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "models/.env/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "object_detection/legacy/eval.py", line 146, in main
    graph_hook_fn=graph_rewriter_fn)
  File "models/research/object_detection/legacy/evaluator.py", line 276, in evaluate
    losses_dict=losses_dict)
  File "models/research/object_detection/eval_util.py", line 438, in repeated_checkpoint_run
    losses_dict=losses_dict)
  File "models/research/object_detection/eval_util.py", line 309, in _run_checkpoint_once
    tensor_dict, sess, batch, counters, losses_dict=losses_dict)
  File "models/research/object_detection/legacy/evaluator.py", line 238, in _process_batch
    keep_image_id_for_visualization_export=eval_config.
  File "models/research/object_detection/eval_util.py", line 196, in visualize_detection_results
    vis_utils.save_image_array_as_png(image, export_path)
  File "models/research/object_detection/utils/visualization_utils.py", line 76, in save_image_array_as_png
    image_pil.save(fid, 'PNG')
  File "models/.env/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 208, in __exit__
    self.close()
  File "models/.env/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 240, in close
    pywrap_tensorflow.Set_TF_Status_from_Status(status, ret_status)
  File "models/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Could not write to the internal temporary file.`

**Comment by Hafplo** [comment] 2018-10-16 09:38
The crash happened again during the weekend. I had 2 evaluation machines, they crashed within 5 minutes of each other (both of them were operating from the same region and writing to the same bucket).

@wt-huang , do you have any suggestions?

**Comment by wt-huang** [comment] 2018-10-16 14:48
@Hafplo It is likely associated with the groud truth. In .config file under object_detection, see if you can capture some eval results. In the meantime, try to change `eval_config.num_examples` to the size of evalution data, also change `eval_input_reader.shuffle` to true.

**Comment by wt-huang** [comment] 2018-10-23 14:20
Closing this, feel free to reopen if problem persists.

**Closed** 2018-10-23 14:22 UTC

**Comment by Hafplo** [comment] 2018-10-25 08:33
@wt-huang 
Thank you for your response and sorry for delaying my response.

I am aware of the importance of setting `num_examples` , and checked your suggestion of 'eval_input_reader.shuffle'.
According to [this](https://github.com/tensorflow/models/issues/1856#issuecomment-315290571), it is a solution to the same issue of missing some labels since you don't evaluate over all of your dataset:
Let's say you have 1000 images but only evaluates 100 of them, and assume they are ordered by labels. By shuffling the order you increase chances of getting images from the 'last' labels.

Since I was evaluating all my images anyway, I don't think it will solve the problem if it persists.
My current guess is that for some reason, the model couldn't detect any objects of a specific label - this can occur even if you evaluates images with those objects, if the model simply 'misses' them (low accuracy, bad model etc.) - and this causes the error, or the error was caused by something else (perhaps OOM?).

For now, this error did not happen again - but it might - and I still don't have a solution. This causes me to invest time and effort in monitoring, which I would happily divert elsewhere, so I am eager to other suggestions.

Thank you.

**Comment by wt-huang** [comment] 2018-10-25 20:55
@Hafplo 
I don't think this issue is TensorFlow related. 
Moreover this issue is not reproducible hence it is difficult for us to diagnose and provide solutions. Root cause analysis can point to numerous possibilities.
I would suggest to capture some evaluation results and go from there.
