### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS but never on low power mode

### ISSUE THREAD

**Issue by manuel-masiello** [tensorflow/tensorflow#31068] opened 2019-07-26 10:27 UTC
**System information**
- Windows 10
- TensorFlow version 1.14 from PIP
- python 3.6.8
- cudatoolkit 10.0.130
- cudnn 7.6.0
- vs2015_runtime  14.15.26706
- GPU model and memory: RTX 2070 - 6315 MB memory

**Describe the current behavior**

When I run TF code ildoonet/tf-pose-estimation on my RTX 2070 I have an issue about:

`2019-07-26 11:57:11.701402: E tensorflow/stream_executor/cuda/cuda_driver.cc:1003] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-07-26 11:57:11.710473: E tensorflow/stream_executor/gpu/gpu_timer.cc:55] Internal: error destroying CUDA event in context 0x227ca310ac0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-07-26 11:57:11.717344: E tensorflow/stream_executor/gpu/gpu_timer.cc:60] Internal: error destroying CUDA event in context 0x227ca310ac0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-07-26 11:57:11.729093: F tensorflow/stream_executor/cuda/cuda_dnn.cc:189] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.`
and... sometimes that crach windows.

But, If I disconnect the power plug in my laptop, It's works. 

**Code to reproduce the issue**
- Install https://www.github.com/ildoonet/tf-pose-estimation
- Execute the example about Web camera: `python .\run_webcam.py --camera 0`

Thx :-)

**Comment by anush-o** [comment] 2019-07-29 11:54
@manuel-masiello ,
Can you please provide minimal code to reproduce the issue.Thanks!

**Comment by manuel-masiello** [comment] 2019-07-29 12:27
Hello @anush-o,

The code to reproduce the error is not mine. You have to make a GIT clone on the project https://www.github.com/ildoonet/tf-pose-estimation, install the different libraries then launch the python script run_webcam.py

Thx for your help.

**Comment by anush-o** [comment] 2019-07-31 09:07
@manuel-masiello ,
Will it be possible to provide minimal code using which we can reproduce the same error?Thanks!

**Comment by oanush** [comment] 2019-08-09 09:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-09 09:15 UTC
Labels: comp:gpu, stat:awaiting response, type:support
