### ISSUE TITLE
Incorrect Hessian of the tf.nn.sigmoid function

### ISSUE THREAD

**Issue by cjf00000** [tensorflow/tensorflow#3767] opened 2016-08-12 10:36 UTC
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Linux 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
tensorflow

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Steps to reproduce
I am trying to evaluate hessian of a logistic function via the following program.
```
# x = 1
# logistic(x) = 0.7310585786300049
# gradient(x) = logistic(x) * (1 - logistic(x)) = 0.19661193324148185
# hessian(x) = logistic(x) * (1 - logistic(x)) ^ 2 + -logistic(x) * (1 - logistic(x)) * logistic(x) = -0.09085774767294841
import tensorflow as tf

x = tf.Variable(1, name='x', dtype=tf.float32)
#logistic = 1. / (1 + tf.exp(-x))
logistic = tf.nn.sigmoid(x, name='logistic')

gradient = tf.gradients(logistic, x, name='gradient')[0]
hessian = tf.gradients(gradient, x, name='hessian')[0]

sess = tf.Session()
sess.run(tf.initialize_all_variables())
print(sess.run([logistic, gradient, hessian]))
```

I directly run the program, it produce the wrong result. 

```TypeError: Fetch argument None of None has invalid type <type 'NoneType'>, must be a string or Tensor```

It seems that `hessian` is `None`.

However, if I write the logistic function manually `logistic = 1. / (1 + tf.exp(-x))`, it produces the correct result.  `[0.7310586, 0.19661197, -0.090857767]`

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by girving** [comment] 2016-08-12 15:08
The problem is that the gradient of `tf.sigmoid` is a dedicated C++ op called `SigmoidGrad`...which has no registered gradient:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L34

**Comment by girving** [comment] 2016-08-12 15:08
This would be great to fix, and `TanhGrad` could be fixed at the same time.

**Comment by girving** [comment] 2016-08-12 15:09
To clarify: there's no need to make new custom ops.  A few lines of Python writing the gradient of these two routines in terms of other existing ops suffices.

**Comment by cjf00000** [comment] 2016-08-12 15:42
Thanks for the clarification! So for my problem, the current solution is just replacing tf.sigmoid(x) with 1/(1+exp(-x)), right?

**Comment by girving** [comment] 2016-08-12 16:17
@cjauvin Yep, that works, though registering the gradient is only a couple lines of code.

**Comment by chemelnucfin** [comment] 2016-08-14 17:48
@girving I didn't see tests for the other gradient functions, but I submitted a pull request for the two gradients. https://github.com/tensorflow/tensorflow/pull/3807

**Comment by hholst80** [comment] 2016-08-16 07:53
@girving for completeness can you show how this is done?

**Comment by girving** [comment] 2016-08-16 14:27
@hholst80 Take a look at #3807.

**Comment by DjangoPeng** [comment] 2016-08-25 03:01
@girving Have you fixed the bug? I can directly run the program and get right outpus

**Comment by girving** [comment] 2016-08-25 16:07
@DjangoPeng: @chemelnucfin got part of the way through https://github.com/tensorflow/tensorflow/pull/3807 but then got pulled away.  You're welcome to take over if you want!

**Comment by DjangoPeng** [comment] 2016-09-04 07:43
@girving Do I need create a new PR? Or, how to take it over?

**Comment by girving** [comment] 2016-09-04 17:38
Whoops, sorry: @rmlarsen just fixed this, and it should be pushed out soon.  Should have commented earlier.

**Comment by chemelnucfin** [comment] 2016-09-05 21:09
@girving, so should I close this PR?

**Comment by girving** [comment] 2016-09-06 16:24
Yep, please close the PR.  Don't close this bug, though; that should wait until @rmlarsen's change is pushed out.

**Comment by rmlarsen** [comment] 2016-09-08 16:53
The fix has been pushed: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L443

**Closed by rmlarsen** 2016-09-08 16:53 UTC
Labels: enhancement
