### ISSUE TITLE
Casting from real to complex lacks gradient

### ISSUE THREAD

**Issue by whdc** [tensorflow/tensorflow#3346] opened 2016-07-16 19:33 UTC
The operation of casting from `float32` to `complex64` lacks a gradient:
```
>>> x = tf.Variable(tf.zeros([10]))
>>> tf.gradients(tf.cast(x, dtype=tf.complex64), x)
[None]
```
Surely this is not intentional?

(FWIW, I'm on Tensorflow 0.9.0, running on the CPU on OS X.)

**Comment by whdc** [comment] 2016-07-16 19:42
I just realized that what I wanted is to be accomplished this way:
```
>>> x = tf.Variable(tf.zeros([10]))
>>> tf.gradients(tf.complex(x, tf.zeros([10])), x)
[<tf.Tensor 'gradients_4/Complex_5_grad/Real:0' shape=(10,) dtype=float32>]
```

**Comment by ibab** [comment] 2016-07-17 00:46
The reason that there is no gradient in your first example is that complex numbers haven't been included in the gradient code for `tf.cast`.
Right now it only returns a gradient if you convert between floats.
This is something that should be fixed, in my opinion.
Here's the code that would need to be changed: https://github.com/tensorflow/tensorflow/blob/e95f4e760c6b6713b6b686ebeff9a1586a5831dd/tensorflow/python/ops/math_grad.py#L746

**Comment by whdc** [comment] 2016-07-17 02:15
Thanks!  I'll use the workaround for now, and if my schedule ever frees up, will try to submit a PR.

**Comment by ibab** [comment] 2016-07-17 03:41
Note that I'm not a googler, though (Just wanted to point out where the issue is so others won't have to search for it).
So it would be worth waiting until one of the core developers assigns the "contributions welcome" label.

**Comment by ibab** [comment] 2016-08-08 13:13
@whdc: Are you still planning to have a look at this?
I can submit a quick fix if you're not planning to work on it.

**Comment by whdc** [comment] 2016-08-08 15:22
Please do! I've had too much to do!

**Comment by ibab** [comment] 2016-08-08 16:46
I just realized that casting from/to complex numbers isn't actually supported by TensorFlow.
It will raise an error like
```
UnimplementedError: Cast float to complex64 is not supported
```
at runtime if you try to cast from/to complex numbers.
That also explains why the gradient for `cast` ignores complex numbers :(

@vrv: Is there interest in supporting casting complex numbers?
This would mirror what can be done in `numpy`, for example with
```python
In [24]: np.cast['complex64']([1, 2, 3])
Out[24]: array([ 1.+0.j,  2.+0.j,  3.+0.j], dtype=complex64)
```
or
```python
In [25]: np.array([1, 2, 3]).astype(np.complex64)
Out[25]: array([ 1.+0.j,  2.+0.j,  3.+0.j], dtype=complex64)
```

**Comment by vrv** [comment] 2016-08-08 16:53
Casting to complex numbers like numpy seems like a good idea!

**Closed** 2016-08-12 22:02 UTC
Labels: contributions welcome
