### ISSUE TITLE
Java: The result of  SavedModelBundle is different every time!

### ISSUE THREAD

**Issue by gramce** [tensorflow/tensorflow#34819] opened 2019-12-04 09:31 UTC
The model was trained by python and was saved using tf.train.Saver.

I use the SavedModelBundle api to load and predict in java. However, the result is different every time. It seems some tensor was not loaded randomly. And in the same main programe，the result is same notever how many times I load the model. But in different programs, the result may be different. 

PS: model maybe partial load. Because some median result was right, but unstable.

python==1.14 java==1.14

My code:

```
//load model
            String modelDir = "/data/model";
            File file = new File(modelDir);
            SavedModelBundle savedModelBundle = null;
            if (file.exists() && file.isDirectory()) {
                savedModelBundle = SavedModelBundle.load(modelDir, "serve");
                System.out.println("load succ");
            } else {
                System.out.println("load fail");
            }
            Session session = savedModelBundle.session();
//feed
            ModelFeature modelFeature = new ModelFeature();
            buildModelFeature(modelFeature);
            Session.Runner tfrunner = session.runner();
            for (FeatureItem item : modelFeature.featureItems) {
                Tensor tensor;
                if (item.getValue().getClass().equals(String[][].class)) {
                    byte[][][] tmpString = new byte[1][1][1];
                    tmpString[0][0] = ((String)item.getValue()[0][0]).getBytes();
                    tensor = Tensor.create(tmpString, String.class);
                } else {
                    tensor = Tensor.create(item.getValue());
                }
                tfrunner = tfrunner.feed(item.getName(), tensor);
                System.out.println("succ to create tensor name = " + item.getName());
            }
//fetch
            //List<Tensor<?>> tensorList = tfrunner.fetch(output).run();
            List<Tensor<?>> tensorList = tfrunner.fetch("concat_input_layer_1/concat:0").run();
//print
            for (int ade = 0; ade < tensorList.size(); ade++) {
                Tensor out;
                System.out.println("tensorList size is " + tensorList.size());
                out = tensorList.get(ade);
                System.out.println(out);

                final long[] shape = out.shape();
                float[][] trans = new float[(int)shape[0]][(int)shape[1]];
                out.copyTo(trans);
                for (int i = 0; i < shape[0]; i++){
                    for (int j = 0; j < shape[1]; j++){
                        System.out.println("final result = " + trans[i][j]);
                    }
                }
                out.close();
            }}         
```

**Comment by gadagashwini** [comment] 2019-12-05 09:38
@gramce, Please post the Tensorflow version and also provide the complete code snippet including all supporting files to reproduce the reported issue. Thanks!

**Comment by gramce** [comment] 2019-12-06 05:45
> @gramce, Please post the Tensorflow version and also provide the complete code snippet including all supporting files to reproduce the reported issue. Thanks!

Sorry. The problem has been fixed. The problem is using the Object Float[] to init Tensor<float>. I fix this just by using float[]. However, I still think this is really a problem.

**Comment by gadagashwini** [comment] 2019-12-10 07:57
@gramce, Glad it fixed. Please provide the complete standalone code to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-12-23 07:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-12-23 07:57 UTC
Labels: comp:apis, stat:awaiting response, type:bug
