### ISSUE TITLE
Unexpected output size for depthwise convolution with stride=2, dilation=3

### ISSUE THREAD

**Issue by olegarch** [tensorflow/tensorflow#27667] opened 2019-04-09 04:37 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **CentOS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **Apr5 tf-nightly-gpu**
- TensorFlow version (use command below): **v1.12.0-11808-ga1e3d4490d 1.14.1-dev20190405**
- Python version: **3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **10.1**
- GPU model and memory: **Tesla**

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
input shape = [?, 128, 128, 8]
output = depthwise_conv2d(input, filters=8, kernel_size=3,
                                 strides=(2, 2),
                                 dilation_rate=(3, 3),
                                 padding='same')

output shape = [?, 65, 65, 8]

**Describe the expected behavior**
Expected output shape:
output = [?, 64, 64, 8]

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-04-10 07:52
@olegarch, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-04-15 08:08
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2019-04-15 08:08 UTC
Labels: stat:awaiting response
