### ISSUE TITLE
cuda libraries cannot be found during linking

### ISSUE THREAD

**Issue by igory1999** [tensorflow/tensorflow#19280] opened 2018-05-14 23:43 UTC
Hi All,

I am trying to build tensorflow 1.8 with bazel 0.13, gcc 4.8.5, cuda 9.0, Anaconda3 5.1.0 on Scientific LInux 7.

This is HPC environment and applications packages are installed in non-standard locations.
I set up environment so that I can use all the above software from command line.
In addition I specify path to cuda and cudnn during configuration and use --action_env.
Nevertheless, the build process fails at linking stage because it cannot find cuda libraries:

bazel build --config=opt --config=cuda --action_env=LD_LIBRARY_PATH=$LD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package
...
ERROR: /home/ivy2/tmp11/tensorflow/tensorflow/python/BUILD:1473:1: Linking of
rule '//tensorflow/python:gen_io_ops_py_wrappers_cc' faile
d (Exit 1)
/usr/bin/ld: warning: libcublas.so.9.0, needed by
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Spython_Cgen_Uio_Uops_Upy_Uwrappers_U
cc___Utensorflow/libtensorflow_framework.so, not found (try using -rpath or
-rpath-link)

The reason I am building tensorflow from sources is because I got a request for C++ interface to tensorflow. My understand is that I need to build from source to get it. Is that right or is there a simpler way?

Thank you,
Igor

==========
Have I written custom code

N/A

OS Platform and Distribution

Scientific Linux 7

TensorFlow installed from

N/A

TensorFlow version

1.8

Bazel version

0.13

CUDA/cuDNN version

9/7

GPU model and memory

Tesla K80, 64G RAM

Exact command to reproduce

bazel build --config=opt --config=cuda --action_env=LD_LIBRARY_PATH=$LD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package

**Comment by tensorflowbutler** [comment] 2018-05-15 06:34
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-06-02 00:00
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-06-16 18:32
It has been 32 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-06-22 16:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-06-22 16:11 UTC
Labels: stat:awaiting response
