### ISSUE TITLE
Unable to run cifar10_multi_gpu_train as is in TensorFlow master

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#5744] opened 2016-11-21 10:01 UTC
Ubuntu 14.04
commit used: a154b6a7826760f30e368e84f51048218002d376

Simply changed num_gpus to 2. I have 2 GPUs. A 1060 and 970. Shows this error:

`ValueError: Variable tower_1/tower_1/conv1/weight_loss/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

**Comment by prb12** [comment] 2016-11-21 17:32
Please can you provide all of the information requested in the issues template.

**Comment by ptrendx** [comment] 2016-11-21 17:38
@prb12, @jkschin This is a duplicate of #5652

**Comment by prb12** [comment] 2016-11-21 20:55
Ok - closing as dup of #5652

**Closed by prb12** 2016-11-21 20:55 UTC
Labels: awaiting response
