### ISSUE TITLE
Random functions always return 0 when using CUDA 7.5 

### ISSUE THREAD

**Issue by luanjunyi** [tensorflow/tensorflow#1734] opened 2016-03-31 22:51 UTC
### Environment info
Operating System:
Ubuntu 14.04.3 LTS

If installed from sources, provide the commit hash: 48e6165fc864d0a222571507613c63c77ec6bf61

### Steps to reproduce
1. Compile from source and during `./configure` process specify CUDA 7.5
2. Run the following script
```
import tensorflow as tf
v = tf.Variable(tf.truncated_normal([3,2], mean = 12.0, stddev = 0.1))
sess = tf.InteractiveSession()
sess.run(tf.initialize_all_variables())
sess.run(v)
```
3. The result is 3x2 array of zeros rather than random value centered at 12.0. The same happens for all random variables

### To solve it

Use CUDA 7.0 solved the problem for me.

**Comment by zheng-xq** [comment] 2016-04-01 17:00
I cannot reproduce the problem at commit 3c8780451007c27b69f10925d43d1f3501d94106, Cuda 7.5. 

For both CPU and GPU, this is what I got

[[ 11.89173698  11.91889286]
 [ 11.91601562  11.93181419]
 [ 11.83213997  12.00035954]]

**Comment by zheng-xq** [comment] 2016-04-01 17:02
Closing this issue for now. We will reopen it if more people hit into the same issue.

**Closed by zheng-xq** 2016-04-01 17:02 UTC
