### ISSUE TITLE
Complie error with cuda9.0+cudnn7.0+tensorflow-r1.4 on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by JIWW** [tensorflow/tensorflow#14705] opened 2017-11-20 03:24 UTC
```
ERROR: /home/wavy/Ten/tensorflow/tensorflow/contrib/factorization/BUILD:116:1: Linking of rule '//tensorflow/contrib/factorization:gen_gen_factorization_ops_py_wrappers_cc' failed (Exit 1)
```
This is the error output.

Thanks!

**Comment by CangHaiQingYue** [comment] 2017-11-21 08:30
tf-1.4 did't support cudnn7.0. Only for cudnn6.0.

**Comment by MikulasZelinka** [comment] 2017-11-21 09:38
> tf-1.4 did't support cudnn7.0. Only for cudnn6.0.

I don't think this is the case as I built tensorflow 1.4.0 with CUDA 9.0, cuDNN v7 on Ubuntu 16.04 LTS without any issues (specified CUDA and cuDNN versions when running the `configure` script, then ran `bazel build -c opt --action_env PATH="$PATH" //tensorflow/tools/pip_package:build_pip_package`).

**Comment by CangHaiQingYue** [comment] 2017-11-21 10:03
I didn't try cudnn7.0  but in the official release claim that tf didn't supprot for cudnn7.0.

**Comment by ofirbb** [comment] 2017-11-21 16:11
It actually says that the precompiled binaries were released with CUDA 8, it doesn't mention the issue of supporting it. The fix seemed to have been merged a while back, but it's still not clear if there is support for it or not. Can someone from the TF team respond and say if it should work properly when compiled against CUDA 9 and cuDNN 7?
Thanks 👍

**Comment by JIWW** [comment] 2017-11-22 01:40
I had compiled successfully with cuda9.0+cudnn7.0 several days ago，howerver it had some warning, when I tested it with the simple code. I didn't success when I tried two days ago...

**Comment by MikulasZelinka** [comment] 2017-11-22 08:51
@ofirbb I only ran some of my experiments (mostly with RNNs) and the results were identical to CUDA 8.0 and cuDNN v6. Which tensorflow tests should I run and how?

**Comment by ofirbb** [comment] 2017-11-22 11:18
@MikulasZelinka I meant something in the form of [running the TF unit tests](https://stackoverflow.com/questions/34204551/run-tensorflow-unit-tests)

**Comment by tatatodd** [comment] 2017-12-01 00:51
TensorFlow 1.4 supports CUDA 8, cuDNN 6.  Here are the configurations we support:
https://www.tensorflow.org/install/install_sources#tested_source_configurations

We anticipate releasing TensorFlow 1.5 with CUDA 9 and cuDNN 7:
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

Also note that this is a duplicate of #14244

**Closed by tatatodd** 2017-12-01 00:51 UTC
