### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by ZYG151541155** [tensorflow/tensorflow#44583] opened 2020-11-04 14:12 UTC
Anybody can help me to solve this problem:
![image](https://user-images.githubusercontent.com/37329790/98122003-fcf49500-1eea-11eb-8809-c068104943a5.png)

Infos:
    
1. tf_nightly_gpu-2.4.0.dev20201023
2.     cuda version:  11.1
3.     cudnn version :  8.0.4

these question cause:  can't not use GPU to train my model, Thank's all of you!

**Comment by Saduf2019** [comment] 2020-11-04 18:50
@ZYG151541155 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by ZYG151541155** [comment] 2020-11-09 07:49
> @ZYG151541155
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
> 
> Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

Oh, Thank's, I get it and already solve this question, the reasons are all environmental mistakes.

**Comment by Saduf2019** [comment] 2020-11-09 11:40
@ZYG151541155 
Thank you for your update, as the issue is resolved please the this to closed status,

**Comment by Saduf2019** [comment] 2020-12-10 13:02
Moving this to closed status as resoved.

**Closed by Saduf2019** 2020-12-10 13:02 UTC
Labels: TF 2.4, type:others
