### ISSUE TITLE
Training fails when a multi-output Keras model has one output without a loss function

### ISSUE THREAD

**Issue by tomwphillips** [tensorflow/tensorflow#35267] opened 2019-12-19 16:21 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see minimal example.
- OS Platform and Distribution: Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  N/A
- TensorFlow installed from (source or binary): binary (specifically, `tensorflow/tensorflow:nightly-py3` Docker image)
- TensorFlow version (use command below): 2.1.0-dev20191216
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

A multi-output Keras model compiled so that one output doesn't have a loss function raises an exception when calling `.fit`.

**Describe the expected behavior**

Training should minimise the losses defined for the other output(s).

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

input_a = keras.layers.Input(shape=(10,), name="input_a")
input_b = keras.layers.Input(shape=(20,), name="input_b")
output_a = keras.layers.Dense(1, name="output_a")(input_a)
output_b = keras.layers.Dense(1, name="output_b")(input_b)
model = keras.Model(inputs=[input_a, input_b], outputs=[output_a, output_b])
model.compile(optimizer="sgd", loss={"output_a": None, "output_b": "mse"})

n = 128
input_a = np.ones((n, 10))
input_b = np.ones((n, 20))
output_a = np.ones((n, 1))
output_b = np.ones((n, 1))

dataset = tf.data.Dataset.from_tensor_slices(
    ((input_a, input_b), (output_a, output_b))
).batch(64)

model.fit(dataset)
```

Raises:

```
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), for inputs ['output_b'] but instead got the following list of 2 arrays: [<tf.Tensor 'args_2:0' shape=(None, 1) dtype=float64>, <tf.Tensor 'args_3:0' shape=(None, 1) dtype=float64>]...
```

**Comment by amahendrakar** [comment] 2019-12-20 09:20
Was able to reproduce the issue with TF version 2.1.0-rc1. Please find the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/2c1f1df27ea0beffcf85ce142a1d21ce/35267.ipynb) here. Thanks!

**Comment by ymodak** [comment] 2020-01-09 19:54
You need to define two dictionaries since you have two outputs. Perhaps you can try defining a dummy loss function for one of the inputs.

**Comment by tomwphillips** [comment] 2020-01-13 11:01
Yes, that's what I did in the end:

```
import tensorflow.keras.backend as K

def null_loss(y_true, y_pred):
    return K.zeros_like(y_true)
```

Perhaps a more descriptive error message is neccesary to guide users in the right direction? It took me a while to figure out what was going on.

**Comment by mmilosav** [comment] 2020-02-07 14:50
There is a bug in the block [in training_eager.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_eager.py#L145).  The block: ```loss_fns = [
        loss_fn for loss_fn in model.loss_functions if loss_fn is not None
    ]``` **excludes** `None` losses from `loss_fns`.  But then enumerated index `i` in ```for i, loss_fn in enumerate(loss_fns):
      weights = sample_weights[i] if sample_weights else None
      mask = masks[i]
      with backend.name_scope(model.output_names[i] + '_loss'):``` then no longer matches positions of the **included** losses in `model.output_names[...]`.  E.g., if the first loss is `None` and excluded from `loss_fns`, and `loss_fns[0] is model.loss_functions[1]`, then when `i == 0`, the second loss callable gets paired with the name of the first loss.

**Comment by pavithrasv** [comment] 2020-02-08 04:05
@tomwphillips this is by design. You do not need to feed target data for the output for which there is no loss function during training. You can pass a dictionary with just the other output like `{'output_b': ...}`.

**Comment by mmilosav** [comment] 2020-02-08 16:01
@pavithrasv I think the following modification of @tomwphillips 's design more clearly shows there is in fact a bug in training_eager.py, please see the comments in code:
```import tensorflow as tf
from tensorflow.data import Dataset

# a model that forks into two independent heads 'one' and 'two'
inputs = tf.keras.layers.Input(shape=(1,))
one = tf.keras.layers.Dense(units=1, name='one')(inputs)
two = tf.keras.layers.Dense(units=1, name='two')(inputs)
model = tf.keras.Model(inputs=inputs, outputs=dict(one=one, two=two))

losses = dict(one=None, two='mse')  # 'one' loss is None, training should not affect weights of 'one'

model.compile(loss=losses, optimizer='adam')

x = Dataset.from_tensor_slices([0., 1.])
y = Dataset.from_tensor_slices([1., 2.])
yy = Dataset.zip(dict(one=y, two=y))  # targets on both heads, but ONLY 'two' has loss
dataset = Dataset.zip((x, yy)).batch(1).repeat()

model.fit(dataset, steps_per_epoch=1000, epochs=10)  # should NOT fit 'one' weights, only 'two' weights

 # printout shows that, unexpectedly, 'one' weights WERE fitted, 'two' weights WERE NOT fitted
for var in model.trainable_weights: 
    print(f'{var.name}: {var.numpy()}')
```

**Comment by pavithrasv** [comment] 2020-02-08 22:25
@mmilosav you are right, This is a duplicate of #36044

**Comment by pavithrasv** [comment] 2020-02-08 22:27
Duplicate of #36044

**Comment by saikumarchalla** [comment] 2020-04-14 08:47
@tomwphillips Closing this issue as it was the expected behavior. Please feel free to re-open the issue if you have any concerns still. Thanks!

**Closed by saikumarchalla** 2020-04-14 08:47 UTC
Labels: TF 2.1, comp:keras, type:bug
