### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by AineKiraboMbabazi** [tensorflow/tensorflow#28067] opened 2019-04-23 08:31 UTC
<em>Upgraded the tensorflow for poets codelab to tf_2.*.alpha, returns the following on attempt to retrain</em>

python3 -m scripts.retrain   --bottleneck_dir=tf_files/bottlenecks   --how_many_training_steps=500   --model_dir=tf_files/models/   --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}"   --output_graph=tf_files/retrained_graph.pb   --output_labels=tf_files/retrained_labels.txt   --architecture="${ARCHITECTURE}"   --image_dir=tf_files/flower_photos
[sudo] password for Beast: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/Beast/work/newAI/tensorflow-for-poets-2/scripts/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
AttributeError: module 'tensorflow' has no attribute 'app'

**Comment by muddham** [comment] 2019-04-24 12:25
@AineKiraboMbabazi It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation. In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by muddham** [comment] 2019-05-03 06:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-03 06:48 UTC
Labels: 2.0.0-alpha0, comp:apis, stat:awaiting response, type:support

**Comment by Starscream9559** [comment] 2019-06-17 18:25
I'm having the same issue as well. TF2.0 Beta1.
Installed on Anaconda environment. Python 3.7.

**Comment by jscul** [comment] 2019-07-26 17:58
Same issue

**Comment by BerryRB** [comment] 2019-10-18 07:41
Can you solved this problem?

**Comment by mihaimaruseac** [comment] 2019-10-18 17:15
Please open a new issue, filling in the template and providing minimal code reproducing the issue
