### ISSUE TITLE
Loding dataset with TFRecord throws incompatible with the layer

### ISSUE THREAD

**Issue by ll01** [tensorflow/tensorflow#38915] opened 2020-04-26 14:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (also colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3.8.2 64 bit
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080 8gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Model.fit throws
    
> ValueError: Input 0 of layer srcnn is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

**Describe the expected behavior**
trains network with loaded dataset from TFRecord

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1GcIhMHv8GJff03WADzTo29oUFgjdMd_N

**Other info / logs** 
```
ValueError                                Traceback (most recent call last)

<ipython-input-96-ee31b3c773a3> in <module>()
     20     train_dataset_count/BATCH_SIZE).numpy()
     21 model.fit(parsed_dataset, epochs=epochs, steps_per_epoch=steps_per_epoch,
---> 22           callbacks=[cp_callback], use_multiprocessing=True)

10 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    849                 batch_size=batch_size):
    850               callbacks.on_train_batch_begin(step)
--> 851               tmp_logs = train_function(iterator)
    852               # Catch OutOfRangeError for Datasets of unknown size.
    853               # This blocks until the batch has finished executing.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    616       # In this case we have not created variables on the first call. So we can
    617       # run the first trace but we should fail if variables are created.
--> 618       results = self._stateful_fn(*args, **kwds)
    619       if self._created_variables:
    620         raise ValueError("Creating variables on a non-first call to a function"

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2417     """Calls a graph function specialized to the inputs."""
   2418     with self._lock:
-> 2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2772           and self.input_signature is None
   2773           and call_context_key in self._function_cache.missed):
-> 2774         return self._define_function_with_shape_relaxation(args, kwargs)
   2775 
   2776       self._function_cache.missed.add(call_context_key)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _define_function_with_shape_relaxation(self, args, kwargs)
   2704         relaxed_arg_shapes)
   2705     graph_function = self._create_graph_function(
-> 2706         args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
   2707     self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
   2708 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2665             arg_names=arg_names,
   2666             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2667             capture_by_value=self._capture_by_value),
   2668         self._function_attributes,
   2669         # Tell the ConcreteFunction to clean up its graph once it goes out of

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980 
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982 
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    439         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    440         # the function a weak reference to itself to avoid a reference cycle.
--> 441         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    442     weak_wrapped_fn = weakref.ref(wrapped_fn)
    443 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:531 train_step  **
        y_pred = self(x, training=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:886 __call__
        self.name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py:168 assert_input_compatibility
        layer_name + ' is incompatible with the layer: '

    ValueError: Input 0 of layer srcnn is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.
```

**Comment by amahendrakar** [comment] 2020-04-27 15:25
Was able to reproduce the issue with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/3f4df88d93e65ad47fbf3b41eaeb7df8/38915-2-2.ipynb#scrollTo=Z7Ph0RJHNxcp) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/c013ed797a1a56d6efd3d15322299120/38915-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by amahendrakar** [comment] 2020-04-27 15:27
@ll01,
Please take a look at these comments from similar issues and let us know if it helps? 

Link 1 - https://github.com/tensorflow/tensorflow/issues/18079#issuecomment-377986751

Link 2 - https://github.com/tensorflow/tensorflow/issues/36321#issuecomment-581660542

Thanks!

**Comment by ll01** [comment] 2020-04-27 23:38
Hi but these links all relate from creating the dataset from a generator. This code is creating the dataset from a tfrecord.

**Comment by jsimsa** [comment] 2020-05-22 19:18
@tomerk can you please take a look? thanks

**Comment by tomerk** [comment] 2020-06-22 20:07
Hi @ll01 , sorry for the delay!

What's happening here is your tfrecord loading function does not specify any shapes for the read values, so the end dataset has an unknown shape and rank. This is insufficient information for the keras model to construct & run, which is why it raises that error about the input being incompatible.

You can fix this by specifying the shape of the parsed values in your dataset construction using `tf.ensure_shape`

e.g. the colab gists above work if you set it as such:
```
def _parse_image_function(example_proto):
    # Parse the input tf.Example proto using the dictionary above.
    example = tf.io.parse_single_example(
        example_proto, image_feature_description)
    label_normalized = normalize_image(example['label'], False)
    label_normalized = tf.ensure_shape(label_normalized, (33, 33, 3))
    feature_normalized = normalize_image(example['feature'], False)
    feature_normalized = tf.ensure_shape(feature_normalized, (33, 33, 3))
    return feature_normalized, label_normalized
```

@aaudiber I'm reassigning this to you to triage if `tf.io.decode_image` should include an optional `shape` argument for the output that it tries to ensure. Perhaps it might be nice if we can somehow be more aggressive about not returning unknown ranks from `decode_image`?

**Comment by aaudiber** [comment] 2020-06-22 21:45
`decode_image` is a wrapper around `decode_jpeg`, `decode_bmp`, `decode_png`, and `decode_gif`. `decode_image` automatically detects the file format based on a file's contents, then uses one of those functions. The rank of the result will depend on the file contents, since GIFs will have rank 4 while other images have rank 3. Shape inference happens before reading file data, so there is no way to know the rank ahead of time.

In addition to using `ensure_shape`, there are a few other workarounds:

- If the file type is known, use `tf.io.decode_bmp`, `tf.io.decode_jpeg`, `tf.io.decode_png`, or `tf.io.decode_gif` instead. These produce tensors of known rank (3 for non-GIF, 4 for GIF).
- If you are ok with truncating GIFs to a single frame, pass `expand_animations=False` to `tf.io.decode_image`, so that the rank is guaranteed to be 3.

**Comment by ll01** [comment] 2020-06-22 22:05
Thanks such an embarising mistake ...

**Closed** 2020-06-22 22:05 UTC
Labels: TF 2.1, TF 2.2, comp:data, comp:keras, type:support
