### ISSUE TITLE
Tf lite: Array activation1, which is an input to the Div operator producing the output array dropout/div, is lacking min/max data

### ISSUE THREAD

**Issue by mjuvilla** [tensorflow/tensorflow#18919] opened 2018-04-27 10:22 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS X High Sierra
- **TensorFlow version (use command below)**: 1.8.0rc1
- **Python version**: 3.5

I'm trying to save a very simple NN model to tflite format, with weight quantization, following this documentation: https://www.tensorflow.org/performance/quantization.

However, when converting with toco, I get this error:

Array Relu, which is an input to the Div operator producing the output array dropout/div, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results.\n"

This is the graph:

![image](https://user-images.githubusercontent.com/8360740/39358075-28e18702-4a15-11e8-82de-8f2d705b1f78.png)

The code to reproduce:

```
    inputs = tf.placeholder(tf.float32, shape=(1, train_X.shape[1]), name='inputs')
    label = tf.placeholder(tf.float32, shape=(1, num_classes), name='labels')

    # First layer
    hid1_size = 128
    w1 = tf.Variable(tf.random_normal([hid1_size, train_X.shape[1]], stddev=0.01), name='w1')
    b1 = tf.Variable(tf.constant(0.1, shape=(hid1_size, 1)), name='b1')
    y1 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(w1, tf.transpose(inputs)), b1, name="layer1"), "activation1"),
                       keep_prob=0.5)

    # Second layer
    hid2_size = 256
    w2 = tf.Variable(tf.random_normal([hid2_size, hid1_size], stddev=0.01), name='w2')
    b2 = tf.Variable(tf.constant(0.1, shape=(hid2_size, 1)), name='b2')
    y2 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(w2, y1), b2, name="layer2"), name="activation2"), keep_prob=0.5)

    # Output layer
    wo = tf.Variable(tf.random_normal([num_classes, hid2_size], stddev=0.01), name='wo')
    bo = tf.Variable(tf.random_normal([num_classes, 1]), name='bo')
    yo = tf.transpose(tf.add(tf.matmul(wo, y2), bo), name="logits")

    # Loss function and optimizer
    lr = tf.placeholder(tf.float32, shape=(), name='learning_rate')
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=yo, labels=label), name="loss")

    # Call the training rewrite which rewrites the graph in-place with
    # FakeQuantization nodes and folds batchnorm for training. It is
    # often needed to fine tune a floating point model for quantization
    # with this training tool. When training from scratch, quant_delay
    # can be used to activate quantization after training to converge
    # with the float graph, effectively fine-tuning the model.
    #tf.contrib.quantize.create_training_graph(quant_delay=3)

    optimizer = tf.train.GradientDescentOptimizer(lr).minimize(loss)

    # Prediction
    pred = tf.nn.softmax(yo, name="prediction")
    pred_label = tf.argmax(pred, 1)
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(label, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

    # Create operation which will initialize all variables
    init = tf.global_variables_initializer()

    # Configure GPU not to use all memory
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True

    # Start a new tensorflow session and initialize variables
    sess = tf.InteractiveSession(config=config)

    writer = tf.summary.FileWriter("tensorboard", sess.graph)

    sess.run(init)

    # This is the main training loop: we train for 50 epochs with a learning rate of 0.05 and another
    # 50 epochs with a smaller learning rate of 0.01
    for learning_rate in [0.05, 0.01]:
        for epoch in range(50):
            avg_cost = 0.0

            # For each epoch, we go through all the samples we have.
            for i in range(train_X.shape[0]):
                # Finally, this is where the magic happens: run our optimizer, feed the current example into X and the current target into Y
                _, c = sess.run([optimizer, loss], feed_dict={lr: learning_rate,
                                                              inputs: train_X[i, None],
                                                              label: train_y[i, None]})
                avg_cost += c
            avg_cost /= train_X.shape[0]

            # Print the cost in this epcho to the console.
            if epoch % 10 == 0:
                print("Epoch: {:3d}    Train Cost: {:.4f}".format(epoch, avg_cost))

    # Call the eval rewrite which rewrites the graph in-place with
    # FakeQuantization nodes and fold batchnorm for eval.
    #tf.contrib.quantize.create_eval_graph()

    writer.close()

    graph_path = os.path.join("models", "model.pbtxt")
    checkpoint_path = os.path.join("models", "model.ckpt")

    # Save the checkpoint and eval graph proto to disk for freezing and providing to TFLite.
    with open(graph_path, 'w') as f:
        f.write(str(sess.graph.as_graph_def()))

    saver = tf.train.Saver()
    saver.save(sess, checkpoint_path)

    frozen_graphdef = tf.graph_util.convert_variables_to_constants(
        sess, sess.graph_def, ["prediction"])
    open("models/frozen_model.pb", "w").write(str(frozen_graphdef))

    tflite_model = tf.contrib.lite.toco_convert(
        frozen_graphdef, [inputs], [pred], inference_type=tf.contrib.lite.QUANTIZED_UINT8,
        quantized_input_stats=[(127.5, 127.5)])
    open("models/converted_model.tflite", "wb").write(tflite_model)
```

Not sure if this is the problem, but could it be that the quantization scripts (quantize.create_training_graph quantize.create_eval_graph) are not detecting the first layer, not fake quantizing it and for this reason I get an error at activation1 when converting?

**Comment by suharshs** [comment] 2018-05-01 00:59
It seems to me that you are trying to create an eval graph from your training graph. Since your graph contains a lot of things that are different between training and eval (i.e. batchnorm, dropout), you should create two separates graphs, either in two files or graph construction code that has a eval vs training parameter. One file creates the training graph and calls `tf.contrib.quantize.create_training_graph()` and the other creates the eval graph, restores the values from training, and calls `tf.contrib.quantize.create_eval_graph()`.

**Comment by mjuvilla** [comment] 2018-05-02 08:54
So if I understand correctly, the correct training code is until the "saver.save(sess, checkpoint_path)" line. Then, I create a new file to create the eval graph and load the trained parameters:

`
import tensorflow as tf


def build_eval_model(num_feat, num_classes):
    inputs = tf.placeholder(tf.float32, shape=(1, num_feat), name='inputs')

    # First layer
    hid1_size = 128
    w1 = tf.get_variable("w1", [hid1_size, num_feat])
    b1 = tf.get_variable("b1", [hid1_size, 1])
    y1 = tf.nn.relu(tf.add(tf.matmul(w1, tf.transpose(inputs)), b1, name="layer1"), "activation1")

    # Second layer
    hid2_size = 256
    w2 = tf.get_variable("w2", [hid2_size, hid1_size])
    b2 = tf.get_variable("b2", [hid2_size, 1])
    y2 = tf.nn.relu(tf.add(tf.matmul(w2, y1), b2, name="layer2"), name="activation2")

    # Output layer
    wo = tf.get_variable("wo", [num_classes, hid2_size])
    bo = tf.get_variable("bo", [num_classes, 1])
    yo = tf.transpose(tf.add(tf.matmul(wo, y2), bo), name="logits")

    pred = tf.nn.softmax(yo, name="prediction")

    saver = tf.train.Saver()

    with tf.Session() as sess:
        writer = tf.summary.FileWriter("tensorboard_eval", sess.graph)

        saver.restore(sess, "models/model.ckpt")

        # Call the eval rewrite which rewrites the graph in-place with
        # FakeQuantization nodes and fold batchnorm for eval.
        tf.contrib.quantize.create_eval_graph()

        writer.close()

        frozen_graphdef = tf.graph_util.convert_variables_to_constants(
            sess, sess.graph_def, ["prediction"])
        tflite_model = tf.contrib.lite.toco_convert(
            frozen_graphdef, [inputs], [pred], inference_type=tf.contrib.lite.QUANTIZED_UINT8,
            quantized_input_stats=[(127.5, 127.5)])
        open("models/converted_model.tflite", "wb").write(tflite_model)


if __name__ == '__main__':
    build_eval_model(200, 11)
`  
But I still get the same error. Maybe it's because I'm not loading the quantization nodes, so when I call toco it doesn't know the min/max information? How to load this information?

**Comment by suharshs** [comment] 2018-05-05 02:04
Note that the create_training_graph and create_eval_graph rewrite adds variables to the graph that store the quantization information needed by toco. So when you save a checkpoint from training, it will have these extra variables stored in it. Thus, when restoring that checkpoint into the eval graph, you need to restore *after* you call the rewrite. 

In particular, your code should be updated like this: 

        saver.restore(sess, "models/model.ckpt")

        # Call the eval rewrite which rewrites the graph in-place with
        # FakeQuantization nodes and fold batchnorm for eval.
        tf.contrib.quantize.create_eval_graph()

Also check out this file for some instructions: 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/quantize 

That being said, the documents can likely be improved more and I will work to do that. Thanks for your feedback!

**Comment by mjuvilla** [comment] 2018-05-07 08:02
Hi, tried your changes but I still got the same error. If I inspect the eval graph in tensorboard it's the same as my last reply, for some reason `tf.contrib.quantize.create_eval_graph()` is not rewriting the graph (or not adding the quantization nodes) so when I restore the checkpoint only the weights and biases are restored, not the min/max information or the weights_quant/act_quant nodes.

**Comment by suharshs** [comment] 2018-05-07 17:57
Hi, thanks for trying. I ran your code and can reproduce what you are seeing exactly. I will take a look to see what the issue is soon. Thanks for the repro case!

**Comment by suharshs** [comment] 2018-05-07 18:38
I have found the issue, the rewriter currently only recognizes one ordering of inputs to MatMul. I will work on a fix for that. But in the meantime you can change all of you Matmuls to `tf.matmul(y1, w2)` (having the weight as the second parameter to get thing working in the meantime. Thanks!

**Comment by mjuvilla** [comment] 2018-05-09 07:09
Ok, so now the `tf.contrib.quantize.create_eval_graph()` is working:

![image](https://user-images.githubusercontent.com/8360740/39800010-a5fb7766-5366-11e8-8378-42b87be5c99b.png)

But now I get an error when freezing the model (in the eval graph code, attached below, function `convert_variables_to_constants`):

`tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value weights_quant_2/min
	 [[Node: _retval_weights_quant_2/min_0_16 = _Retval[T=DT_FLOAT, index=16, _device="/job:localhost/replica:0/task:0/device:CPU:0"](weights_quant_2/min)]]`

Looks like when I perform the restore from the checkpoint, the quantization nodes are not restored (but the weights and biases are correctly restored).

Here's the new training code:

```inputs = tf.placeholder(tf.float32, shape=(1, train_X.shape[1]), name='inputs')
label = tf.placeholder(tf.float32, shape=(1, num_classes), name='labels')

# First layer
hid1_size = 1000
w1 = tf.Variable(tf.random_normal([train_X.shape[1], hid1_size], stddev=0.01), name='w1')
b1 = tf.Variable(tf.constant(0.1, shape=(1, hid1_size)), name='b1')
y1 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(inputs, w1), b1, name="layer1"), "activation1"), keep_prob=0.5)

# Second layer
hid2_size = 1000
w2 = tf.Variable(tf.random_normal([hid1_size, hid2_size], stddev=0.01), name='w2')
b2 = tf.Variable(tf.constant(0.1, shape=(1, hid2_size)), name='b2')
y2 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(y1, w2), b2, name="layer2"), name="activation2"), keep_prob=0.5)

# Output layer
wo = tf.Variable(tf.random_normal([hid2_size, num_classes], stddev=0.01), name='wo')
bo = tf.Variable(tf.random_normal([1, num_classes]), name='bo')
yo = tf.add(tf.matmul(y2, wo), bo, name="logits")

# Loss function and optimizer
# lr = tf.placeholder(tf.float32, shape=(), name='learning_rate')
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=yo, labels=label), name="loss")

# Call the training rewrite which rewrites the graph in-place with
# FakeQuantization nodes and folds batchnorm for training. It is
# often needed to fine tune a floating point model for quantization
# with this training tool. When training from scratch, quant_delay
# can be used to activate quantization after training to converge
# with the float graph, effectively fine-tuning the model.
tf.contrib.quantize.create_training_graph(quant_delay=50)

optimizer = tf.train.AdamOptimizer().minimize(loss)

# Prediction
pred = tf.nn.softmax(yo, name="prediction")
pred_label = tf.argmax(pred, 1)
correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(label, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

# Create operation which will initialize all variables
init = tf.global_variables_initializer()

# Start a new tensorflow session and initialize variables
sess = tf.Session()

writer = tf.summary.FileWriter("tensorboard", sess.graph)

sess.run(init)

saver = tf.train.Saver()

# This is the main training loop: we train for 50 epochs with a learning rate of 0.05 and another
# 50 epochs with a smaller learning rate of 0.01
for epoch in range(10):
    print("Epoch: {:3d}".format(epoch))
    avg_cost = 0.0

    # For each epoch, we go through all the samples we have.
    for i in tqdm.tqdm(range(train_X.shape[0])):
        # Finally, this is where the magic happens: run our optimizer, feed the current example into X and the current target into Y
        _, c = sess.run([optimizer, loss], feed_dict={inputs: train_X[i, None],
                                                      label: train_y[i, None]})
        avg_cost += c
    avg_cost /= train_X.shape[0]

    # Print the cost in this epcho to the console.
    if epoch % 10 == 0:
        print("Epoch: {:3d}    Train Cost: {:.4f}".format(epoch, avg_cost))

graph_path = os.path.join("models", "model.pbtxt")
checkpoint_path = os.path.join("models", "model.ckpt")

# Save the checkpoint and eval graph proto to disk for freezing and providing to TFLite.
with open(graph_path, 'w') as f:
    f.write(str(sess.graph.as_graph_def()))

saver.save(sess, checkpoint_path)

writer.close()
```

And the eval graph code:

```
inputs = tf.placeholder(tf.float32, shape=(1, num_feat), name='inputs')

# First layer
hid1_size = 1000
w1 = tf.Variable(tf.random_normal([num_feat, hid1_size], stddev=0.01), name='w1')
b1 = tf.Variable(tf.constant(0.1, shape=(1, hid1_size)), name='b1')
y1 = tf.nn.relu(tf.add(tf.matmul(inputs, w1), b1, name="layer1"), "activation1")

# Second layer
hid2_size = 1000
w2 = tf.Variable(tf.random_normal([hid1_size, hid2_size], stddev=0.01), name='w2')
b2 = tf.Variable(tf.constant(0.1, shape=(1, hid2_size)), name='b2')
y2 = tf.nn.relu(tf.add(tf.matmul(y1, w2), b2, name="layer2"), name="activation2")

# Output layer
wo = tf.Variable(tf.random_normal([hid2_size, num_classes], stddev=0.01), name='wo')
bo = tf.Variable(tf.random_normal([1, num_classes]), name='bo')
yo = tf.add(tf.matmul(y2, wo), bo, name="logits")

pred = tf.nn.softmax(yo, name="prediction")

saver = tf.train.Saver()

with tf.Session() as sess:
    # Call the eval rewrite which rewrites the graph in-place with
    # FakeQuantization nodes and fold batchnorm for eval.
    tf.contrib.quantize.create_eval_graph()

    writer = tf.summary.FileWriter("tensorboard_eval", sess.graph)

    saver.restore(sess, "models/model.ckpt")

    writer.close()

    frozen_graphdef = tf.graph_util.convert_variables_to_constants(
        sess, sess.graph_def, ["prediction"])

    tflite_model = tf.contrib.lite.toco_convert(
        frozen_graphdef, [inputs], [pred], inference_type=tf.contrib.lite.FLOAT)

    open("models/converted_model.tflite", "wb").write(tflite_model)
```

Do I need to do something else when saving or restoring the graph parameters?

**Comment by suharshs** [comment] 2018-05-09 18:13
Using your code I am able to successfully get a frozen graph. Here is the code I used (copy pasted from your snippets): 

```
def train_model(num_feat, num_classes):
  g = tf.Graph()
  with tf.Session(graph=g) as sess:
    inputs = tf.placeholder(tf.float32, shape=(1, num_feat), name="inputs")
    label = tf.placeholder(tf.float32, shape=(1, num_classes), name='labels')

    # First layer
    hid1_size = 1000
    w1 = tf.Variable(tf.random_normal([num_feat, hid1_size], stddev=0.01), name='w1')
    b1 = tf.Variable(tf.constant(0.1, shape=(1, hid1_size)), name='b1')
    y1 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(inputs, w1), b1, name="layer1"), "activation1"), keep_prob=0.5)

    # Second layer
    hid2_size = 1000
    w2 = tf.Variable(tf.random_normal([hid1_size, hid2_size], stddev=0.01), name='w2')
    b2 = tf.Variable(tf.constant(0.1, shape=(1, hid2_size)), name='b2')
    y2 = tf.nn.dropout(tf.nn.relu(tf.add(tf.matmul(y1, w2), b2, name="layer2"), name="activation2"), keep_prob=0.5)

    # Output layer
    wo = tf.Variable(tf.random_normal([hid2_size, num_classes], stddev=0.01), name='wo')
    bo = tf.Variable(tf.random_normal([1, num_classes]), name='bo')
    yo = tf.add(tf.matmul(y2, wo), bo, name="logits")

    # Loss function and optimizer
    # lr = tf.placeholder(tf.float32, shape=(), name='learning_rate')
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=yo, labels=label), name="loss")

    # Call the training rewrite which rewrites the graph in-place with
    # FakeQuantization nodes and folds batchnorm for training. It is
    # often needed to fine tune a floating point model for quantization
    # with this training tool. When training from scratch, quant_delay
    # can be used to activate quantization after training to converge
    # with the float graph, effectively fine-tuning the model.
    tf.contrib.quantize.create_training_graph(quant_delay=50)

    optimizer = tf.train.AdamOptimizer().minimize(loss)

    sess = tf.Session()
    sess.run(tf.global_variables_initializer())

    saver = tf.train.Saver()
    saver.save(sess, '/tmp/oink.ckpt')


def eval_model(num_feat, num_classes):
  g = tf.Graph()
  with tf.Session(graph=g) as sess:
    inputs = tf.placeholder(tf.float32, shape=(1, num_feat), name='inputs')

    # First layer
    hid1_size = 1000
    w1 = tf.Variable(tf.random_normal([num_feat, hid1_size], stddev=0.01), name='w1')
    b1 = tf.Variable(tf.constant(0.1, shape=(1, hid1_size)), name='b1')
    y1 = tf.nn.relu(tf.add(tf.matmul(inputs, w1), b1, name="layer1"), "activation1")

    # Second layer
    hid2_size = 1000
    w2 = tf.Variable(tf.random_normal([hid1_size, hid2_size], stddev=0.01), name='w2')
    b2 = tf.Variable(tf.constant(0.1, shape=(1, hid2_size)), name='b2')
    y2 = tf.nn.relu(tf.add(tf.matmul(y1, w2), b2, name="layer2"), name="activation2")

    # Output layer
    wo = tf.Variable(tf.random_normal([hid2_size, num_classes], stddev=0.01), name='wo')
    bo = tf.Variable(tf.random_normal([1, num_classes]), name='bo')
    yo = tf.add(tf.matmul(y2, wo), bo, name="logits")

    pred = tf.nn.softmax(yo, name="prediction")

    tf.contrib.quantize.create_eval_graph()

    saver = tf.Saver()
    saver.restore(sess, "/tmp/oink.ckpt")

    frozen_graphdef = tf.graph_util.convert_variables_to_constants(
          sess, sess.graph_def, ["prediction"])


def main(_):
  train_model(3, 1000)
  eval_model(3, 1000)
```

In particular make sure you delete your old checkpoints from before you swapped the order of the params, the above code seems to work for me. Hope that works! (I have a fix in progress for the ordering issue.)

**Comment by nrothGIT** [comment] 2018-05-16 05:35
I had a related follow up. I am following the pattern shown above. But when I restore a trained graph, and evaluate the 'preds', I seem to get substantially different (and worse) outputs than in my train graph. Is there some extra step I need to take to make the eval graph line up with the train graph for quantization? Or what is the best way to confirm that the eval graph quantization is working?

**Comment by suharshs** [comment] 2018-05-17 00:52
Do you have a specific example of the mismatch? IIUC, there is an expected difference since you are using dropout during training but not eval. If you want to compare training and eval predictions, you should try with keep_prob=1 during training.

Otherwise the graphs should matchup. If there are still differences between the graphs, i would recommend viewing them to see if there is anything unexpected or running corresponding intermediate nodes to try to identity where the difference appears.

**Comment by eejackliu** [comment] 2018-05-28 11:14
@suharshs 
You said “I have found the issue, the rewriter currently only recognizes one ordering of inputs to MatMul. ” Did it means that it couldn't recognize the conv2d if I use it in the training part ?

**Comment by fgr1986** [comment] 2018-05-28 14:37
@suharshs As you pointed out, a more comprehensive documentation could be of great help.
Especially, a full example showing:

- training_graph quantization +  **exporting/displaying  weights/activations already quantized** 
- evaluation_graph quantization + **exporting/displaying weights/activations already quantized**

would be of great help, allowing us developers to access and debug the layers and check whether the quantization is being correctly performed.

Thanks

**Comment by suharshs** [comment] 2018-05-28 16:35
@eejackliu The rewriter uses pattern matching to find layers. Prior to the fix, if `tf.matmul(w, y)` would be ignored but `tf.matmul(y, w)` would be matched. These should both be matched. This is fixed now.

@fgr1986 Thanks. Yes, i will work to add better docs in the coming weeks. Thanks for the specific examples of what would be helpful!

**Comment by fgr1986** [comment] 2018-05-28 16:44
@suharshs Thank you. Let me know if I can be of help with the documentation/examples, in case you need a hand.

Thanks.

**Comment by fgr1986** [comment] 2018-05-28 18:52
@suharshs Tahnk you very much, let me know if you need a hand with the documentation.
In the mean time, I tried myself the following example, but unfortunately couldn't show how the quantization is correctly working.
Please note that I use `experimental_create_training_graph` instead `create_training_graph` only to be able to determine the quantization bits more easily:

```
import numpy as np
import tensorflow as tf

D_SIZE = 2048
BATCH_SIZE = 32
EPOCHS = 1000
W_B = 3
A_B = 3


def train_quantization():

    g_tr = tf.Graph()
    with g_tr.as_default():

        # prepare dataset
        features_arr = tf.constant(2 * np.arange(D_SIZE), dtype=tf.float32)
        labels_arr = tf.constant(np.arange(D_SIZE), dtype=tf.float32)
        trn_data = tf.data.Dataset.zip(
            (tf.data.Dataset.from_tensor_slices(features_arr),
             tf.data.Dataset.from_tensor_slices(labels_arr))
        )
        trn_data = trn_data.shuffle(1000)
        trn_data = trn_data.batch(BATCH_SIZE)
        trn_data = trn_data.repeat(EPOCHS)
        trn_data = trn_data.prefetch(1)

        iterator = tf.data.Iterator.from_structure(trn_data.output_types,
                                                   trn_data.output_shapes)
        feat, labels = iterator.get_next()
        data_init_op = iterator.make_initializer(trn_data)

        # global step
        global_step = tf.train.get_or_create_global_step()

        # simple model dense, WITH ACTIVATION TO TEST QUANTIFICATION
        flow = tf.identity(feat, name='input_tensor')
        print(feat)
        flow = tf.reshape(flow, (-1, BATCH_SIZE))
        # require activation for quantization
        flow = tf.layers.dense(flow, units=BATCH_SIZE,
                               activation=tf.nn.relu, name='out')

        # Build forward pass of model.
        # Make the loss op
        with tf.variable_scope('loss'):
            tf.logging.debug('[loss] size of out: %s',
                             flow.get_shape().as_list())
            power = tf.pow(labels - flow, 2)
            power = tf.reduce_sum(power, 1)
            loss = tf.reduce_mean(power, name='m_loss')
        tf.summary.scalar('loss', loss)

        # Optimizer
        opt_op = tf.train.AdamOptimizer(1e-4).minimize(loss, global_step)


        # Call the training rewrite which rewrites the graph in-place with
        # FakeQuantization nodes and folds batchnorm for training. It is
        # often needed to fine tune a floating point model for quantization
        # with this training tool. When training from scratch, quant_delay
        # can be used to activate quantization after training to converge
        # with the float graph, effectively fine-tuning the model.
        tf.contrib.quantize.experimental_create_training_graph(weight_bits=W_B,
                                                               activation_bits=A_B,
                                                               quant_delay=int(EPOCHS / 2))

        # Merge all the summaries
        merged = tf.summary.merge_all()

        with tf.Session(graph=g_tr) as sess:
            # global variables Initializing
            sess.run(tf.global_variables_initializer())
            # local variables Initializing
            sess.run(tf.local_variables_initializer())

            train_writer = tf.summary.FileWriter('./tmp/train', sess.graph)

            # re-initialize the iterator, but this time with training data
            sess.run(data_init_op)

            epoch_counter = 0
            for i in range(int(D_SIZE/BATCH_SIZE) * EPOCHS):
                _, nn_out, nn_loss, gs, summary = sess.run(
                    [opt_op, flow, loss, global_step, merged])
                # tensorboard and  statistics
                train_writer.add_summary(summary, gs)
                if i % BATCH_SIZE == 0:
                    print(epoch_counter, ': loss ', nn_loss)
                    epoch_counter += 1

            saver = tf.train.Saver()
            saver.save(sess, './tmp/oink.ckpt')

        # debug
        print('loss: ', nn_loss)
        print('nn_out bits:', len(np.unique(nn_out)))
        print('nn_out: ', nn_out[0:8])


        print('[debug] exit training')

def inference_quantization():

    #################################
    # Reset default graph
    tf.reset_default_graph()
    #################################

    g_inf = tf.Graph()
    with g_inf.as_default():
        # create inference graph
        data_init_op, feat, labels, flow, loss = _create_model(False)

        with tf.Session(graph=g_inf) as sess:
            # Call the eval rewrite which rewrites the graph in-place with
            # FakeQuantization nodes and fold batchnorm for eval.
            tf.contrib.quantize.experimental_create_eval_graph(weight_bits=W_B,
                                                               activation_bits=A_B)

            saver = tf.train.Saver()
            saver.restore(sess, "./tmp/oink.ckpt")
            # frozen_graphdef = tf.graph_util.convert_variables_to_constants(
            #       sess, sess.graph_def, ["out"])
            print('[debug] restored')

            # re-initialize the iterator, but this time with training data
            sess.run(data_init_op)

            nn_out, nn_labels, nn_loss = sess.run([flow, labels, loss])

        # debug
        print('loss: ', nn_loss)
        print('nn_out bits:', len(np.unique(nn_out)))
        print('nn_out: ', nn_out[0:8])
        print('nn_labels: ', nn_labels[0:8])

def test_quantization():

    train_quantization()
    inference_quantization()

test_quantization()
```

**Comment by tensorflowbutler** [comment] 2018-06-26 12:44
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-11 12:50
Nagging Assignee @suharshs: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-26 19:12
Nagging Assignee @suharshs: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by suharshs** [comment] 2018-08-02 22:41
@mynameischaos this seems like a separate issue. Please create a new issue for that with a repro details. 

This issue seems resolved so I will close. Please reopen if i am wrong.

**Closed by suharshs** 2018-08-02 22:41 UTC
Labels: comp:lite
