### ISSUE TITLE
UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods

### ISSUE THREAD

**Issue by nijat-ahmadli** [tensorflow/tensorflow#62173] opened 2023-10-19 11:27 UTC
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

- TensorFlow Lite initialisation crashes when using versions 2.12 and above on any Android Emulator with API level between 21 and 25 included.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Steps to reproduce:
1. Create a new Android project.
2. Add TensorFlow Lite dependencies:
```
    implementation("org.tensorflow:tensorflow-lite:2.14.0")
    implementation("org.tensorflow:tensorflow-lite-support:0.4.3")
```
3. [Download](https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/latest/blaze_face_short_range.tflite) BlazeFace tflite model and add to src/main/assets folder
4. Initialise Tensorflow Lite Interpreter in `onCreate()` of MainActivity:
```
        val model = FileUtil.loadMappedFile(this, "blaze_face_short_range.tflite")
        val options = Interpreter.Options()
        options.numThreads = 4
        val interpreter = Interpreter(model, options)
```
5. Run the app on any Android Emulator using API Level between 21 and 25 included.
6. App crashes with the following error:
```
 E  FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 8645
    java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.example.myapplication-2/base.apk!/lib/arm64-v8a/libtensorflowlite_jni.so"...
    	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
    	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
    	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
    	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:35)
    	at android.app.Activity.performCreate(Activity.java:6679)
    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:154)
    	at android.app.ActivityThread.main(ActivityThread.java:6119)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
    	at org.tensorflow.lite.TensorFlowLite.nativeDoNothing(Native Method)
    	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:132)
    	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62) 
    	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36) 
    	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232) 
    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:35) 
    	at android.app.Activity.performCreate(Activity.java:6679) 
    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    	at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
    	at android.os.Handler.dispatchMessage(Handler.java:102) 
    	at android.os.Looper.loop(Looper.java:154) 
    	at android.app.ActivityThread.main(ActivityThread.java:6119) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by pjpratik** [comment] 2023-10-26 10:00
Hi @nijat-ahmadli 

This seems to be an issue with Android < 8 compatibility with latest TF Versions. Can you please provide the Android version you are using?

Please check this relevant issue #61951 

Thanks.

**Comment by nijat-ahmadli** [comment] 2023-10-26 10:44
Hi @pjpratik Thanks for your reply.
I am using following versions for the project:
```
    minSdkVersion 21
    targetSdkVersion 33
    compileSdkVersion 33
```

**Comment by pkgoogle** [comment] 2023-10-26 17:26
Hi @nijat-ahmadli, let's follow the progress on https://github.com/tensorflow/tensorflow/issues/61951 as this looks basically the same.

**Comment by fergushenderson** [comment] 2023-11-02 18:39
Duplicate of 61951

**Comment by fergushenderson** [comment] 2023-11-02 18:40
Duplicate of #61951

**Comment by gaikwadrahul8** [comment] 2024-11-27 09:44
Hi, @nijat-ahmadli 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/106

Let us know if you have any questions. Thanks.

**Comment by pkgoogle** [comment] 2024-11-27 18:38
Closing as duplicate. Thanks.

**Closed by pkgoogle** 2024-11-27 18:38 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:lite, TF2.14
