### ISSUE TITLE
Session.run() doesn't accepts string of image bytes(2nd Parameter), as it usually does

### ISSUE THREAD

**Issue by AnandAron** [tensorflow/tensorflow#26657] opened 2019-03-13 09:52 UTC
*System information**
- Os Ubuntu 
- Tensorflow 1.13.1
- Python 2.7
Code:
`image_data = tf.gfile.FastGFile(image_path, 'rb').read()`
`prediction = sess.run('final_result:0', {'Placeholder:0': image_data})`

Error:
`could not convert string to float`

**Comment by jvishnuvardhan** [comment] 2019-03-14 21:54
@AnandAron Could you provide a code to reproduce the bug? Thanks!

**Comment by tensorflowbutler** [comment] 2019-03-29 13:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-03-29 16:05
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-29 16:05 UTC
Labels: TF 1.13, comp:ops, stat:awaiting response, type:bug/performance
