### ISSUE TITLE
HashTable lookup performance very low in comparison to plain Python dictionaries (~5,000x)

### ISSUE THREAD

**Issue by simonsays1980** [tensorflow/tensorflow#29687] opened 2019-06-12 10:04 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.2 LTS (Bionic Beaver)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Don't know (Colab)
- **TensorFlow version (use command below)**: 1.13.1
- **Python version**: 3.6.7
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: - 
- **CUDA/cuDNN version**: 10.0.130
- **GPU model and memory**: 
- **Exact command to reproduce**:  tf.contrib.lookup.HashTable..lookup()

### Describe the problem
While writing a document ranking algorithm in TensorFlow we found out that TensorFlow `HashTable`s appear to be very slow (~5,000x) in comparison to plain Python `dict`ionaries. 

Looking into the TensorFlow source code in `lookup_table_op.cc` (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/lookup_table_op.cc) shows that the underlying object structure appears to be an `unordered_map`. So we wonder, why the performance is so low? 

### Source code / logs
Here is the source code that is similar to a part of what we use and can be easily executed on any system. There is actually a __Colab__ notebook that can be used: https://colab.research.google.com/drive/1bB_sir7-sVd3bNrSgkcdT9UlU9eoyA2Q 

```python
import urllib.request
import tensorflow as tf
import re, time
from nltk.corpus import stopwords
from nltk import word_tokenize, download
# For loading the 'punkt' module of 'nltk'. This has to be done only once.
download( 'punkt' )
download( 'stopwords' )

url = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/cowper.txt'
urllib.request.urlretrieve( url, './cowper.txt' )

def parse_text( input_path = './cowper.txt', output_path = 'cowper_tf.txt' ):
    stop_words      = set( stopwords.words( 'english' ) )    
    with open( output_path, 'w+' ) as output_file:
        document = []
        with open( input_path, 'r' ) as file:
            for line in file:
                for token in map( str.lower, word_tokenize( line ) ):                    
                    if not token in stop_words and bool( re.match( r'[a-zA-Z]', token ) ):
                        document.append(token)             
            output_file.write(' '.join( document ) ) 

parse_text()

with open( 'cowper_tf.txt' ) as file:
    for line in file:
        document = re.split( r'\s', line )[1:-1]

k = 100
dictionary_list = []
hashtable_list  = []
frequencies     = {}
for i in range( k ):
    for word in document:    
        if word not in frequencies:
            frequencies[word] = 0        
            frequencies[word] += 1        
    keys           = tf.constant( list( frequencies.keys() ) )
    values         = tf.constant( list( frequencies.values() ) )
    frequencies_tf = tf.contrib.lookup.HashTable( 
        tf.contrib.lookup.KeyValueTensorInitializer(
            keys   = keys,
            values = values ),
        default_value = 0 )
    hashtable_list.append( frequencies_tf )
    dictionary_list.append( frequencies )

n = 100
test_word = tf.constant( 'sing', dtype = tf.string, shape = () )
global tf_time
def test_lookup( test_word, n = 100 ):
    start = time.clock()
    for i in range( n ):    
        a = [hashtable.lookup( test_word ) for hashtable in hashtable_list]
    tf_time = ( time.clock() - start ) / n
    print( 'time elapsed per lookup: ', tf_time )
    return a
with tf.Session() as sess:
    sess.run( tf.global_variables_initializer() )
    sess.run( tf.tables_initializer() )
    sess.run( test_lookup( test_word, n ) )

test_word = 'add'
start = time.clock()
for i in range( n ):
    a = [dictionary[test_word] for dictionary in dictionary_list]
plain_python_time = ( time.clock() - start ) / n
print( 'elapsed time:', plain_python_time )
```

**Comment by gadagashwini** [comment] 2019-06-18 12:03
I am able to reproduce the issue on Colab with Tensorflow 1.13.1. Thanks!

**Comment by azaks3** [comment] 2019-07-26 16:08
1. I think you are measuring graph construction time not the runtime for the TF numbers.
2 However even more importantly the benchmark does not even run any lookups at all since "return test_word" does not depend on looked up values,
3. Overall once you run the lookup ops performance will be even more dismal than what you currently claim, since you are creating > 10000 ops and per op overhead is huge. For a more realistic comparison you should be looking up a batch of keys at a time.

**Comment by gadagashwini** [comment] 2019-08-02 05:41
@simonsays1980, Did you get a chance to look at @azaks3's comment. Thanks!

**Comment by novog** [comment] 2019-08-02 15:28
I didn't open this ticket, but I did try to create a simple test in TF 2.0 that addresses @azaks3's points. To allow the `StaticHashTable` to work efficiently, I batched the inputs in that mode in groups of 1000:

    keys = range(1,11)
    values = [0, 1, 1, 0, 1, 0, 1, 0, 0, 0]
    randomizer = tf.random_uniform_initializer(1, 10, 0)
    
    py_dict = dict(zip(keys, values))
    py_input = randomizer.__call__((sample_count,), tf.int64)
    py_ds = tf.data.Dataset.from_tensor_slices(py_input)
    py_iter = iter(py_ds)
    py_start = time.clock()
    py_results = [py_dict[x.numpy()] for x in py_iter]
    py_time = (time.clock() - py_start)
    py_time_str = '{:10f}'.format(py_time)
    print(f'{py_time}s - total python time')

    tf_dict_init = tf.lookup.KeyValueTensorInitializer(keys, values, tf.int64, tf.int64)
    tf_dict = tf.lookup.StaticHashTable(tf_dict_init, -1)
    tf_input = randomizer.__call__((round(sample_count/1000), 1000), tf.int64)
    tf_ds = tf.data.Dataset.from_tensor_slices(tf_input)
    tf_iter = iter(tf_ds)
    tf_start = time.clock()
    tf_results = [tf_dict.lookup(x) for x in tf_iter]
    tf_time = (time.clock() - tf_start)
    tf_time_str = '{:10f}'.format(tf_time)
    print(f'{tf_time}s - total TensorFlow time')

On my computer, the python version took about 9.8s for 100k records, while the TensorFlow version took about 0.4s.

**Comment by simonsays1980** [comment] 2019-08-03 09:29
> 1. I think you are measuring graph construction time not the runtime for the TF numbers.
>    2 However even more importantly the benchmark does not even run any lookups at all since "return test_word" does not depend on looked up values,
> 2. Overall once you run the lookup ops performance will be even more dismal than what you currently claim, since you are creating > 10000 ops and per op overhead is huge. For a more realistic comparison you should be looking up a batch of keys at a time.

@azaks3 First of all, thank you for your efforts looking into this issue and for your comments. In the [Colab notebook](https://colab.research.google.com/drive/1bB_sir7-sVd3bNrSgkcdT9UlU9eoyA2Q) I added two more cells, in which I repeat the example with a batch of 1,000 keys. There is still a difference of 7x between TensorFlow and pure Python, however your second comment is totally right: increasing the batch size decreases relative overhead. It's actually impressive to see how the time remains almost the same for TensorFlow `HashTable`s in comparison to the significantly longer run times for pure Python dictionaries when looking up more keys at once. 

Now, our use case is actually rather the one with not many keys (~20-50) per lookup but a lookup through many `HashTable`s (or in pure Python dictionaries) and this operation repeated many times (e.g. in inference). I understand now that the overhead is quite a lot and that this might be the reason why we have such a long runtime for the TensorFlow version of our application. I was hoping to find a solution in TensorFlow - something about `HashTable`s I have not known, yet - to make the requests faster. This becomes especially demanding when turning towards inference.

**Comment by simonsays1980** [comment] 2019-08-03 09:45
> I didn't open this ticket, but I did try to create a simple test in TF 2.0 that addresses @azaks3's points. To allow the `StaticHashTable` to work efficiently, I batched the inputs in that mode in groups of 1000:
> 
> ```
> keys = range(1,11)
> values = [0, 1, 1, 0, 1, 0, 1, 0, 0, 0]
> randomizer = tf.random_uniform_initializer(1, 10, 0)
> 
> py_dict = dict(zip(keys, values))
> py_input = randomizer.__call__((sample_count,), tf.int64)
> py_ds = tf.data.Dataset.from_tensor_slices(py_input)
> py_iter = iter(py_ds)
> py_start = time.clock()
> py_results = [py_dict[x.numpy()] for x in py_iter]
> py_time = (time.clock() - py_start)
> py_time_str = '{:10f}'.format(py_time)
> print(f'{py_time}s - total python time')
> 
> tf_dict_init = tf.lookup.KeyValueTensorInitializer(keys, values, tf.int64, tf.int64)
> tf_dict = tf.lookup.StaticHashTable(tf_dict_init, -1)
> tf_input = randomizer.__call__((round(sample_count/1000), 1000), tf.int64)
> tf_ds = tf.data.Dataset.from_tensor_slices(tf_input)
> tf_iter = iter(tf_ds)
> tf_start = time.clock()
> tf_results = [tf_dict.lookup(x) for x in tf_iter]
> tf_time = (time.clock() - tf_start)
> tf_time_str = '{:10f}'.format(tf_time)
> print(f'{tf_time}s - total TensorFlow time')
> ```
> 
> On my computer, the python version took about 9.8s for 100k records, while the TensorFlow version took about 0.4s.

@novog Thanks for posting your example code in TensorFlow 2.0 here. This points again out - in a more elegant implementation - that overhead is actually the reason for the duration issue when looking up a lot of times only a few keys in many tables. Looking up many keys only a few times is where TensorFlow glances. 

@azaks3 @novog For the above mentioned use case of looking up many times only a few keys in a lot of tables: how would you implement this in TensorFlow to get good performance?

**Comment by azaks3** [comment] 2019-08-03 17:09
I think the standard technique would be to combine the tables and encode table name in the key/output values

**Comment by gadagashwini** [comment] 2019-08-20 05:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-20 05:41 UTC
Labels: TF 1.13, comp:runtime, stat:awaiting response, type:bug
