### ISSUE TITLE
TFLite expermimental_new_converter error with tf.keras Bidirectional Wrapper or attribute go_backwards=True

### ISSUE THREAD

**Issue by am15h** [tensorflow/tensorflow#35551] opened 2020-01-02 21:33 UTC
**System information**
- OS Platform and Distribution: Linux Ubuntu  18.04
- TensorFlow installed from (source or binary): 
- TensorFlow version (or github SHA if from source):
Used to build model: 2.0.0
Used to run converter : 2.1.0-dev20191227

**Command used to run the converter or code if you’re using the Python API**

```
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

print(tf.__version__)

model = tf.keras.models.load_model("/home/amish/PycharmProjects/myproject/scripts/temp.h5")
model.summary()
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental_new_converter = True  # Add this line

tflite_model = converter.convert()
```

**The output from the converter invocation**

```
WARNING:tensorflow:Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
2.1.0-dev20191227
2020-01-03 02:45:22.187710: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-03 02:45:22.193838: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-01-03 02:45:22.193908: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: enigma
2020-01-03 02:45:22.193928: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: enigma
2020-01-03 02:45:22.207575: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 430.50.0
2020-01-03 02:45:22.207706: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.50.0
2020-01-03 02:45:22.207730: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 430.50.0
2020-01-03 02:45:22.208264: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-03 02:45:22.384583: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 2496000000 Hz
2020-01-03 02:45:22.391769: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cbc700ede0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-03 02:45:22.391868: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
masking_14 (Masking)         (None, 50, 36)            0         
_________________________________________________________________
bidirectional_6 (Bidirection (None, 50, 256)           168960    
_________________________________________________________________
dropout_16 (Dropout)         (None, 50, 256)           0         
_________________________________________________________________
dense_16 (Dense)             (None, 50, 10)            2570      
=================================================================
Total params: 171,530
Trainable params: 171,530
Non-trainable params: 0
_________________________________________________________________
2020-01-03 02:45:24.787867: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-01-03 02:45:24.788386: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-03 02:45:25.204179: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: graph_to_optimize
2020-01-03 02:45:25.204249: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: Graph size after: 255 nodes (0), 310 edges (0), time = 121.027ms.
2020-01-03 02:45:25.204268: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: Graph size after: 255 nodes (0), 310 edges (0), time = 9.261ms.
2020-01-03 02:45:25.204281: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_forward_lstm_56_while_body_3164
2020-01-03 02:45:25.204300: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.004ms.
2020-01-03 02:45:25.204316: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-03 02:45:25.204332: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_forward_lstm_56_while_cond_3163
2020-01-03 02:45:25.204345: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-01-03 02:45:25.204360: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-03 02:45:25.204376: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_backward_lstm_56_while_body_3360
2020-01-03 02:45:25.204391: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-01-03 02:45:25.204406: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-03 02:45:25.204422: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_backward_lstm_56_while_cond_3359
2020-01-03 02:45:25.204440: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-01-03 02:45:25.204460: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-03 02:45:25.373374: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-01-03 02:45:25.373537: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-03 02:45:25.447623: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: graph_to_optimize
2020-01-03 02:45:25.447671: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 177 nodes (-78), 225 edges (-85), time = 50.718ms.
2020-01-03 02:45:25.447678: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 177 nodes (0), 225 edges (0), time = 3.89ms.
2020-01-03 02:45:25.447702: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_backward_lstm_56_while_body_3360_frozen
2020-01-03 02:45:25.447707: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 71 nodes (-1), 96 edges (0), time = 2.225ms.
2020-01-03 02:45:25.447730: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 71 nodes (0), 96 edges (0), time = 1.116ms.
2020-01-03 02:45:25.447752: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_forward_lstm_56_while_body_3164_frozen
2020-01-03 02:45:25.447757: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 71 nodes (-1), 96 edges (0), time = 2.118ms.
2020-01-03 02:45:25.447761: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 71 nodes (0), 96 edges (0), time = 1.179ms.
2020-01-03 02:45:25.447766: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_backward_lstm_56_while_cond_3359_frozen
2020-01-03 02:45:25.447771: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 17 nodes (0), 4 edges (0), time = 0.339ms.
2020-01-03 02:45:25.447795: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 17 nodes (0), 4 edges (0), time = 0.214ms.
2020-01-03 02:45:25.447800: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: sequential_14_bidirectional_6_forward_lstm_56_while_cond_3163_frozen
2020-01-03 02:45:25.447817: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 17 nodes (0), 4 edges (0), time = 0.311ms.
2020-01-03 02:45:25.447822: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 17 nodes (0), 4 edges (0), time = 0.213ms.
Traceback (most recent call last):
  File "convert.py", line 15, in <module>
    tflite_model = converter.convert()
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 490, in convert
    **converter_kwargs)
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 476, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 215, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
WARNING:tensorflow:Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
2020-01-03 02:45:27.257206: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:108] Ignored output_format.
2020-01-03 02:45:27.257267: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:114] Ignored drop_control_dependency.
2020-01-03 02:45:27.478616: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-03 02:45:27.500564: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 2496000000 Hz
2020-01-03 02:45:27.500991: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555ae8caec30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-03 02:45:27.501033: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-03 02:45:27.502780: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-03 02:45:27.505700: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-01-03 02:45:27.505725: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: enigma
2020-01-03 02:45:27.505732: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: enigma
2020-01-03 02:45:27.505775: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 430.50.0
2020-01-03 02:45:27.505796: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.50.0
2020-01-03 02:45:27.505801: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 430.50.0
loc(callsite("sequential_14/bidirectional_6/backward_lstm_56/ReverseV2_1"("/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py":853:0) at callsite("/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py":947:0 at callsite("/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py":409:0 at "convert.py":9:0)))): error: 'tfl.reverse_v2' op operand #0 must be tensor of 32-bit float or 16-bit integer or 32-bit integer or 64-bit integer values, but got 'tensor<50x1x1xi1>'
Traceback (most recent call last):
  File "/home/amish/anaconda3/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/amish/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/amish/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py:853:9: error: 'tfl.reverse_v2' op operand #0 must be tensor of 32-bit float or 16-bit integer or 32-bit integer or 64-bit integer values, but got 'tensor<50x1x1xi1>'
        self._initialize(args, kwargs, add_initializers_to=initializers)
        ^
/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py:947:5: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
    ^
/home/amish/anaconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py:409:5: note: called from
    concrete_func = func.get_concrete_function()
    ^
convert.py:9:1: note: called from
converter = tf.lite.TFLiteConverter.from_keras_model(model)

```

**This issue caused due to Bidirectional Wrapper. Also same error occurs when ```go_backwards=True``` in the LSTM layer**.

Please tell a workaround(if any) for this so that I can temporarily fix this.

**Comment by jvishnuvardhan** [comment] 2020-01-03 23:23
@am15h Can you please share the model or the code to create that model. Thanks!

**Comment by am15h** [comment] 2020-01-04 13:10
@jvishnuvardhan The code to create model.
```
model = tf.keras.Sequential()
model.add(layers.Bidirectional(layers.LSTM(128, return_sequences=True)))

#model.add(layers.LSTM(128, return_sequences=True)) #Works fine without Birdirectional
model.add(layers.Dense(20, activation='softmax'))

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

model.summary()

model.fit(x_train, y_train, batch_size=32, epochs=13, shuffle=True, validation_data=(x_test, y_test))
```

**Comment by haozha111** [comment] 2020-01-06 23:05
I couldn't reproduce your issue. I used the below code to build the model and convert:

model = tf.keras.Sequential()
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True), input_shape=(128, 128)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Dense(20, activation='softmax'))
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()

This could convert with no error reported. Could you confirm if this model is the same as yours? Also, is there a Masking layer as the first layer? And what's the input data type/shape?

**Comment by am15h** [comment] 2020-01-07 10:34
@haozha111 Yes there is a masking layer, I accidentally remove that line while sharing code, 

```
model = tf.keras.Sequential()
model.add(layers.Masking(input_shape=(50,36)))
model.add(layers.Bidirectional(layers.LSTM(128, return_sequences=True)))
model.add(layers.Dense(20, activation='softmax'))

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

model.summary()

model.fit(x_train, y_train, batch_size=32, epochs=13, shuffle=True, validation_data=(x_test, y_test))

```

**Comment by haozha111** [comment] 2020-01-07 21:27
Thanks!

I can reproduce the error now. The issue is that tflite's reverse op doesn't support bool type. So the conversion fails. I'm working on a fix for that.

**Comment by haozha111** [comment] 2020-01-08 00:07
I've completed a fix for this issue and the code will be merged into tf-nightly soon. Please try again with the tf-nightly (tomorrow's version should contain the fix) and then try if your issue is resolved.

Cheers.

**Closed** 2020-01-08 00:48 UTC
Labels: TF 2.0, comp:lite, type:bug
