### ISSUE TITLE
error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sathyamoorthyrr** [tensorflow/tensorflow#25576] opened 2019-02-07 06:22 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): [source](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)
- TensorFlow version: 1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): Not used Bazel. Built static library
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: No
- GPU model and memory: No GPU. RAM-8GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the exact steps [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)

Upon running benchmark file,
`tensorflow/contrib/makefile/gen/bin/benchmark \
 --graph=$HOME/graphs/inception/tensorflow_inception_graph.pb`

I get the following error,
> error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sathyamoorthyrr** [comment] 2019-02-07 07:05
somehow managed to work by copying `tensorflow/tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf.so.17` to `/usr/local/lib` and running `sudo ldconfig`
right approach?

**Comment by varun046** [comment] 2019-03-14 08:01
"tensorflow/tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf.so.17 to /usr/local/lib and running sudo ldconfig"

Sorry to say, but this approach is also not working

**Comment by jvishnuvardhan** [comment] 2019-03-14 12:31
@varun046 Which TF version you have installed. If it is not TF1.12, then open a new issue for your environment and fill issue template accordingly. Thanks!

**Comment by gunan** [comment] 2020-04-21 01:34
makefile is not a supported build strategy.
This was caused by incomplete configuration of the makefiles, as they were there, kept surviving with little to no support.
Closing this issue as they are removed now.

**Closed by gunan** 2020-04-21 01:34 UTC
Labels: TF 1.12, stat:awaiting tensorflower, type:build/install
