### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by prathikPrabhakara** [tensorflow/tensorflow#30794] opened 2019-07-17 09:14 UTC
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 2, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet, tensorboard_dir='log')

I am facing below issue 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-8507f364adee> in <module>
----> 1 import tflearn
      2 from tflearn.layers.conv import conv_2d, max_pool_2d
      3 from tflearn.layers.core import input_data, dropout, fully_connected
      4 from tflearn.layers.estimator import regression
      5 

~\Anaconda3\Lib\site-packages\tflearn\__init__.py in <module>
      2 
      3 # Config
----> 4 from . import config
      5 from .config import is_training, get_training_mode, init_graph
      6 

~\Anaconda3\Lib\site-packages\tflearn\config.py in <module>
      3 import tensorflow as tf
      4 
----> 5 from .variables import variable
      6 
      7 # -------------------

~\Anaconda3\Lib\site-packages\tflearn\variables.py in <module>
      5 import tflearn
      6 
----> 7 from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
      8 from tensorflow.python.framework import ops
      9 from tensorflow.python.ops import variable_scope

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by pandrey-fr** [comment] 2019-07-17 09:59
What versions of tensorflow are you using?
`tensorflow.contrib` is being removed in version 2.0, you therefore need version <= 1.14 to operate tflearn (by the way, this is a TFlearn issue, not a tensorflow one).
In your case, I would consider moving to tensorflow (instead of tflearn) and use the tf.keras API, which provides the higher-level API tflearn aimed at offering in times when tf.keras was not out yet.

**Comment by prathikPrabhakara** [comment] 2019-07-17 10:13
Thank you for the reply. I am using tensorflow 2.0. I will uninstall and reinstall tensor flow 1.14

**Comment by prathikPrabhakara** [comment] 2019-07-17 10:28
Thank you. It works 😊

**Comment by pandrey-fr** [comment] 2019-07-17 10:46
You are welcome! Don't forget to close the issue :)

**Closed** 2019-07-17 10:59 UTC

**Comment by samruddhik3** [comment] 2019-10-01 05:49
This is my code:
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression



convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 2, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet, tensorboard_dir='log')


And this is the error I am receiving:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-4fdf924eb21a> in <module>
----> 1 import tflearn
      2 from tflearn.layers.conv import conv_2d, max_pool_2d
      3 from tflearn.layers.core import input_data, dropout, fully_connected
      4 from tflearn.layers.estimator import regression
      5 

C:\ProgramData\Anaconda3\lib\site-packages\tflearn\__init__.py in <module>
      2 
      3 # Config
----> 4 from . import config
      5 from .config import is_training, get_training_mode, init_graph
      6 

C:\ProgramData\Anaconda3\lib\site-packages\tflearn\config.py in <module>
      3 import tensorflow as tf
      4 
----> 5 from .variables import variable
      6 
      7 # -------------------

C:\ProgramData\Anaconda3\lib\site-packages\tflearn\variables.py in <module>
      5 import tflearn
      6 
----> 7 from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
      8 from tensorflow.python.framework import ops
      9 from tensorflow.python.ops import variable_scope

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by youngkyle2019** [comment] 2019-10-25 02:03
"I will uninstall and reinstall tensor flow 1.14"..... how to do this in jupyter notebook ? ( anaconda 3) Thanks..

**Comment by pandrey-fr** [comment] 2019-10-25 07:51
> "I will uninstall and reinstall tensor flow 1.14"..... how to do this in jupyter notebook ?

In the command line (_not_ the notebook), `conda install tensorflow=1.14` (or `tensorflow-gpu=1.14` if you want GPU support ; or `pip install` rather than `conda install` depending on what you are used to do).

**Comment by youngkyle2019** [comment] 2019-10-26 04:30
It worked ! Thanks ! 

One problem left though is that, by using tflearn package, we will miss new features in tensorflow 2.0 and later versions. Would tflearn be upgraded in the future ?

**Comment by pandrey-fr** [comment] 2019-10-26 07:19
I cannot speak for `tflearn` developers, but I think the all idea of making TF 2.0 revolve around the built-in keras implementation (which is also available in the latest 1.x versions) is to make it easier to use tensorflow without requiring an external high-level wrapper. In other words, I do not know whether `tflearn` will allow to run TF 2 as backend, but I think you can probably envision making the move to using the tensorflow built-in high level API (thus dropping tflearn). But, you know, that is up to you and depending on context too :)

**Comment by sickWill** [comment] 2019-11-06 23:10
Does anybody knows why this pop ups? 

ERROR: Could not find a version that satisfies the requirement 1.14 (from versions: none)

I was trying to do de uninstall install earlier version of tensorflow but it seems it's deprecated right now. 
I hope somebody see this.

**Comment by pandrey-fr** [comment] 2019-11-07 10:36
@sickWill Could you please share the line you executed that triggered this error?

`pip install tensorflow==1.14` or `pip install tensorflow-gpu==1.14` should work (or you could target the recently-released 1.15 version ; `pip install tensorflow==1.15` which works both with and without GPU usage)

**Comment by cluzier** [comment] 2019-12-22 05:48
> @sickWill Could you please share the line you executed that triggered this error?
> 
> `pip install tensorflow==1.14` or `pip install tensorflow-gpu==1.14` should work (or you could target the recently-released 1.15 version ; `pip install tensorflow==1.15` which works both with and without GPU usage)

Thank you, this worked. Here is what I had to do since I had permission issues:
`pip3 install --user tensorflow==1.14`

**Comment by Joshiokk** [comment] 2020-01-14 04:00
Thanks! It worked.

**Comment by sickWill** [comment] 2020-01-15 11:29
@pandrey-fr Thank you, that worked pretty well.
@cluzier And thank you too for bothering to come with an answer.

**Comment by shambhuraje037** [comment] 2020-03-18 01:30
> Which version of tensorflow are you using?
> 
> `tensorflow.contrib` is being removed in version 2.0, you therefore need version <= 1.14 to operate tflearn (by the way, this is a TFlearn issue, not a tensorflow one).
> 
> In your case, I would consider moving to tensorflow (instead of tflearn) and using the tf.keras API, which provides the higher-level API tflearn aimed at offering in times when tf.keras was not out yet.

Can you share a example how to convert from tflearn to tensorflow in the code

**Comment by ShivanshGaur6096** [comment] 2020-03-25 17:19
> > "I will uninstall and reinstall tensor flow 1.14"..... how to do this in jupyter notebook ?
> 
> In the command line (_not_ the notebook), `conda install tensorflow=1.14` (or `**tensorflow-gpu==1.14`** if you want GPU support ; or `pip install` rather than `conda install` depending on what you are used to do).

**Comment by chinju-murali** [comment] 2020-05-01 17:25
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by testote** [comment] 2020-05-31 18:40
When I do "sudo -H pip2 install tensorflow==1.15" I get
ERROR: Package 'mock' requires a different Python: 2.7.18 not in '>=3.6'

When I do "sudo -H pip3 install tensorflow==1.15" I get
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0).

The fact that  tensorflow.contrib was removed from python3 tensorflow is causing quite pain. Any help?

**Comment by pandrey-fr** [comment] 2020-06-02 07:54
> When I do "sudo -H pip2 install tensorflow==1.15" I get
ERROR: Package 'mock' requires a different Python: 2.7.18 not in '>=3.6'

This looks like an issue with the 'mock' dependency not being compatible with python 2 (which, as a reminder, has been officially deprecated as of January 1st, 2020). You may try to `python2 -m pip install -h mock`, possibly specifying a compatible version of the dependency to install, before resuming tensorflow installation.

> When I do "sudo -H pip3 install tensorflow==1.15" I get
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0).

This should be working, but PyPi seems to have trouble parsing the version number. Could you try with `python3 -m pip install -h tensorflow==1.15.3`?

> The fact that tensorflow.contrib was removed from python3 tensorflow is causing quite pain. 

`tensorflow.contrib` was not removed from python3, but from TF 2.0, as part of a major API clean-up, which has been documented for a year. I understand that this is causing some troubles with code maintenance, but most features can actually be found back either in tensorflow, tensorflow_addons or other third-party packages.

**Comment by testote** [comment] 2020-06-02 22:52
Thanks for the response.

* Tensorflow v1.15.x on Python2 requires mock, but now mock requires python 3.7 or above.
* Tensorflow v.1.15.x on Python3 is no available anymore, only 2.2.x.
* I cannot find a pointers list of old 1.15.x tensorflow.contrib packages to the new 2.2.x tensorflow versions' distribution.

Thus, I am stuck.

**Comment by testote** [comment] 2020-06-03 00:15
Tensorflow 1.15.x is only avaliable on python 3.5, 3.6 and 3.7.

trizen -S python37 --noconfirm
sudo -H python3.7 -m pip install tensorflow==1.15.3
sudo -H python3.7 -m pip install tf_slim
sed -i "s/from tensorflow.contrib import slim/import tf_slim as slim/g" file.py
sudo -H python3.7 -m pip install opencv-python

**Comment by riteshahlawat** [comment] 2020-07-11 22:54
Just yesterday TF OD API is now officially compatible with TF 2.X, FINALLY!!!
https://blog.tensorflow.org/2020/07/tensorflow-2-meets-object-detection-api.html?m=1

**Comment by geo-dingky** [comment] 2021-04-27 01:54
from tensorflow.contrib.layers.python import layers as tf layers 

 ModuleNotFoundError: No module named 'tensorflow.contrib'

Do I need to change tensorflow2.41 to 1.14? Do I need to delete tensorflow2.4?

**Comment by Chethan187** [comment] 2021-05-29 17:19
Installed tf version 1.14, but still facing the same issue:
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by ravohasina** [comment] 2021-11-28 12:41
Can someone help me how to install tensorflow 1.14? 
I try with the command 
pip install tensorflow == 1.14
and it displays :
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow==1.14

So what do I do?

**Comment by yangli1715977** [comment] 2021-12-16 13:39
> 
Because your python version is too high, if you want to install tensorflow 1.14, you should use python 3.5 - 3.7

**Comment by yamini4292** [comment] 2022-07-13 17:54
> Thank you. It works 😊

can you tell me how to uninstall tensorflow and reinstall 1.14 in jupiter notebook

**Comment by cluzier** [comment] 2022-07-17 03:32
> > Thank you. It works 😊
> 
> can you tell me how to uninstall tensorflow and reinstall 1.14 in jupiter notebook

Hi there, to uninstall tensorflow try out:
`pip uninstall tensorflow-cpu`
or
`pip uninstall tensorflow-gpu`

as for reinstalling 1.14 jupiter notebook, try out:
`pip install tensorflow==1.14`

hopefully this is of some help 🤞

**Comment by mkestane15** [comment] 2022-12-04 05:47
Hi, I'm using   Python 3.8.15 as default on Google Colab, how can I downgrade the python version to 3.7 on Google colab?
