### ISSUE TITLE
build errors on missing "//base"

### ISSUE THREAD

**Issue by jmhodges** [tensorflow/tensorflow#4476] opened 2016-09-19 22:18 UTC
When running ./configure on OS X with CUDA support enabled with bazel 0.3.1-homebrew, these errors occur:

    ERROR: /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/BUILD:692:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core:ios_tensorflow_test_lib'.
    ERROR: /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
    ERROR: /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
    ERROR: /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such target '//tensorflow/core:android_proto_lib_no_rtti_lite_runtime': target 'android_proto_lib_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /Users/jmhodges/src/github.com/tensorflow/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
    ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

This seems to be because of targets like "ios_tensorflow_test_lib" and, so on, depending on a `//base` and `//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime` that do not exist.

Off hand, I'm not able to figure out what this was trying to refer to. Perhaps it used to exist?

**Comment by jmhodges** [comment] 2016-09-19 22:19
(Added bazel version to ticket: 0.3.1-homebrew)

**Comment by jmhodges** [comment] 2016-09-19 22:21
This seems to have been introduced in ed87884e50e1a50f7dc7b36dc7a7ff225442bee0. Perhaps, it's a Google internal thing that just slipped in?

**Comment by jmhodges** [comment] 2016-09-19 22:26
Same deal with `//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime`. It just doesn't exist.

**Comment by jmhodges** [comment] 2016-09-19 22:27
Looks like this only happens when you try to build with CUDA.

**Comment by andrewharp** [comment] 2016-09-19 22:27
@jmhodges Yes, those are some references that weren't meant to be interpreted by the external version of TF.

This is a duplicate of #4312, where you can find workarounds for the errors you're seeing -- essentially just revert/comment out the new functions.

**Comment by jmhodges** [comment] 2016-09-19 22:28
Ah, it's been 10 days since that ticket. Is there no fix I could send up to handle this?

**Comment by jmhodges** [comment] 2016-09-19 22:31
(I'm trying to confirm #4145 now that configure has some nice new CUDA smarts, and it's a little bit harder to confirm with these changes not in master. I'm sure I'm not the only external contributor trying to help and having to rediscover this!)

**Closed** 2016-09-19 22:37 UTC
Labels: duplicate
