### ISSUE TITLE
 output ImportError libcudart.so.7.5. in window 7 pycharm

### ISSUE THREAD

**Issue by ismymajia** [tensorflow/tensorflow#2771] opened 2016-06-10 00:27 UTC
### Environment info
Operating System:  
      
     tensorflow in Ubuntu 14.04 
     pycharm in window 7

Installed version of CUDA and cuDNN: 

     cuda 7.5 and cudnn v4.0

If installed from binary pip package, provide:

1. Which pip package you installed.

     tensorflow-0.8-GPU-whl 
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

     0.8

### Steps to reproduce
1. start samba in ubuntu
2. import remote  mnist example by pycharm in window 7
3. change python interpreter to remote ubuntu python
4. run mninst

### What have you tried?
1.  according to above step , output ImportError libcudart.so.7.5.  but ok if run mnist directly 
by pycharm and command line in ubuntu machine .

### Logs or other output that would be helpful
ImportError libcudart.so.7.5

**Comment by girving** [comment] 2016-06-10 21:46
We wouldn't be able to reproduce this since it involves Windows, but it could be a path issue (maybe LD_LIBRARY_PATH?).

**Comment by aselle** [comment] 2016-07-09 03:33
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-09 03:33 UTC
Labels: awaiting response
