### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by KathiravanNatarajan** [tensorflow/tensorflow#18042] opened 2018-03-28 08:05 UTC
Hi, 

Please find the link to my [code](https://github.com/KathiravanNatarajan/MAWILAB_classfication/blob/master/Conv_1D.ipynb). 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-5960795275b2> in <module>()
     10 
     11 # Output of the model
---> 12 output = conv1D_Net1(features)
     13 
     14 # Calculating cost

<ipython-input-8-80fe61955189> in conv1D_Net1(input_1d)
      8     pool1 = tf.nn.pool(conv1d, [2], 'MAX', 'SAME', strides = [2])
      9      #Flattenning the output of ConvNets
---> 10     flat_conv2 = tf.contrib.layers.flatten(pool1)
     11 
     12     datasize = flat_conv2.get_shape().as_list()[1]

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\__init__.py in __getattr__(self, item)
     33     # Replace the lazy loader with the imported module itself.
     34     import importlib  # pylint: disable=g-import-not-at-top
---> 35     contrib = importlib.import_module('tensorflow.contrib')
     36     return getattr(contrib, item)
     37 

C:\Anaconda\envs\tensorflow\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap_external.py in exec_module(self, module)

C:\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\__init__.py in <module>()
     27 from tensorflow.contrib import deprecated
     28 from tensorflow.contrib import distributions
---> 29 from tensorflow.contrib import factorization
     30 from tensorflow.contrib import framework
     31 from tensorflow.contrib import graph_editor

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\factorization\__init__.py in <module>()
     22 from tensorflow.contrib.factorization.python.ops.clustering_ops import *
     23 from tensorflow.contrib.factorization.python.ops.factorization_ops import *
---> 24 from tensorflow.contrib.factorization.python.ops.gmm import *
     25 from tensorflow.contrib.factorization.python.ops.gmm_ops import *
     26 # pylint: enable=wildcard-import

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\factorization\python\ops\gmm.py in <module>()
     30 from tensorflow.contrib.framework.python.framework import checkpoint_utils
     31 from tensorflow.contrib.framework.python.ops import variables
---> 32 from tensorflow.contrib.learn.python.learn import graph_actions
     33 from tensorflow.contrib.learn.python.learn import monitors as monitor_lib
     34 from tensorflow.contrib.learn.python.learn.estimators import estimator as estimator_lib

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\__init__.py in <module>()
     81 
     82 # pylint: disable=wildcard-import
---> 83 from tensorflow.contrib.learn.python.learn import *
     84 # pylint: enable=wildcard-import
     85 

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\__init__.py in <module>()
     21 
     22 # pylint: disable=wildcard-import
---> 23 from tensorflow.contrib.learn.python.learn import *
     24 # pylint: enable=wildcard-import

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py in <module>()
     23 from tensorflow.contrib.learn.python.learn import basic_session_run_hooks
     24 from tensorflow.contrib.learn.python.learn import datasets
---> 25 from tensorflow.contrib.learn.python.learn import estimators
     26 from tensorflow.contrib.learn.python.learn import graph_actions
     27 from tensorflow.contrib.learn.python.learn import learn_io as io

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py in <module>()
    308 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
    309 from tensorflow.contrib.learn.python.learn.estimators.constants import ProblemType
--> 310 from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
    311 from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNRegressor
    312 from tensorflow.contrib.learn.python.learn.estimators.dnn_linear_combined import DNNLinearCombinedClassifier

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py in <module>()
     27 from tensorflow.contrib.layers.python.layers import optimizers
     28 from tensorflow.contrib.learn.python.learn import metric_spec
---> 29 from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
     30 from tensorflow.contrib.learn.python.learn.estimators import estimator
     31 from tensorflow.contrib.learn.python.learn.estimators import head as head_lib

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py in <module>()
     31 from tensorflow.contrib.layers.python.layers import optimizers
     32 from tensorflow.contrib.learn.python.learn import metric_spec
---> 33 from tensorflow.contrib.learn.python.learn.estimators import estimator
     34 from tensorflow.contrib.learn.python.learn.estimators import head as head_lib
     35 from tensorflow.contrib.learn.python.learn.estimators import model_fn

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py in <module>()
     49 from tensorflow.contrib.learn.python.learn.estimators import tensor_signature
     50 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
---> 51 from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
     52 from tensorflow.contrib.learn.python.learn.utils import export
     53 from tensorflow.contrib.learn.python.learn.utils import saved_model_export_utils

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py in <module>()
     30 from tensorflow.contrib.learn.python.learn.learn_io.graph_io import read_keyed_batch_examples
     31 from tensorflow.contrib.learn.python.learn.learn_io.graph_io import read_keyed_batch_features
---> 32 from tensorflow.contrib.learn.python.learn.learn_io.numpy_io import numpy_input_fn
     33 from tensorflow.contrib.learn.python.learn.learn_io.pandas_io import extract_pandas_data
     34 from tensorflow.contrib.learn.python.learn.learn_io.pandas_io import extract_pandas_labels

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\numpy_io.py in <module>()
     20 
     21 import collections
---> 22 from tensorflow.contrib.learn.python.learn.dataframe.queues import feeding_functions
     23 
     24 # Key name to pack the target into dict of `features`. See

C:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\dataframe\queues\feeding_functions.py in <module>()
     36 # pylint: disable=g-import-not-at-top
     37 try:
---> 38   import pandas as pd
     39   HAS_PANDAS = True
     40 except ImportError:

C:\Anaconda\envs\tensorflow\lib\site-packages\pandas\__init__.py in <module>()
     35 
     36 # let init-time option registration happen
---> 37 import pandas.core.config_init
     38 
     39 from pandas.core.api import *

C:\Anaconda\envs\tensorflow\lib\site-packages\pandas\core\config_init.py in <module>()
     12 import warnings
     13 
---> 14 import pandas.core.config as cf
     15 from pandas.core.config import (is_int, is_bool, is_text, is_instance_factory,
     16                                 is_one_of_factory, get_default_val,

AttributeError: module 'pandas' has no attribute 'core'
```

Regards, 
Kathir
​

**Comment by tensorflowbutler** [comment] 2018-03-28 18:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kr-ish** [comment] 2018-04-02 19:59
maybe try tf.layers.flatten instead of tf.contrib.layers.flatten?

also see this: https://stackoverflow.com/questions/36521691/importing-pandas-gives-error-attributeerror-module-pandas-has-no-attribute-c

**Comment by angersson** [comment] 2018-04-03 17:07
Thanks @kr-ish!

This looks like a problem resolved by the links, so I'm closing the issue.

**Closed by angersson** 2018-04-03 17:07 UTC
Labels: stat:awaiting response
