### ISSUE TITLE
No gradients exist for a sub-classed model

### ISSUE THREAD

**Issue by Zodaztream** [tensorflow/tensorflow#48916] opened 2021-05-05 15:28 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: using CPU
- GPU model and memory: using CPU

**Describe the current behavior**
No gradients provided for any variable of a simple subclassed model. The weights are not zero. 

**Describe the expected behavior**
The gradients for all the variables should exist

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): No - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
The full model is quite large/complex, in the full architecture, this basic block is the only part of the model that throws this issue. It is the most fundamental part of the architecture.

For google colab:
Add this to "My Drive" on google drive:
https://drive.google.com/drive/folders/1epROVNfvO10Ksy8CwJQdamSK96JZnWW9?usp=sharing
and then run the code: 
https://colab.research.google.com/drive/18sMqNn8IpTQLZBlInWSbX0ITd2GWDDkz?usp=sharing

```
class BasicBlock(tf.keras.Model):
        def __init__(self, ncIn, ncOut, batchNorm_type=0, strides=(1,1), dynamic=True, name=None):
        super(BasicBlock, self).__init__(dynamic=True)
        self.ncIn = ncIn
        self.ncOut = ncOut
        self.conv_1 = SeparableConv2D(self.ncOut, kernel_size=(1,1), strides=(1,1), padding="same", use_bias=False, name=f'BB_conv_1_{name}')
        self.conv_2 = SeparableConv2D(self.ncOut, kernel_size=(1,1), strides=(1,1), padding="same", use_bias=False, name=f'BB_conv_2_{name}') 
        self.bn = BatchNormalization(name=f'BN_0_{name}')
        def call(self, inputs):
            x = inputs[0]
            out = self.conv_1(x)
            out = self.bn(out)
            out = Activation('relu')(out) 
            out = self.conv_2(out)
            out = self.bn(out) 
            out = Activation('relu')(out)
            return out 
```

For the network architecture itself  and,

```        
        epoch = 0
        optimizer = Adam()
        bb = BasicBlock(1, 32)

        while True:
            real_samples = self.generate_real_samples(n_batch, n_patch)
            [X_real_img, X_real_sh, X_gt_sh], y_real = real_samples
            X_real_img = np.concatenate(X_real_img)
            X_target_sh = np.concatenate(X_real_sh)
            X_gt_sh = np.concatenate(X_gt_sh)
            
            with tf.GradientTape() as tape:
                test = bb([X_real_img])
                loss_value = MSE(X_gt_sh, X_target_sh) #dummy loss

            #retrieve gradients of trainable variables w.r.t the loss
            grads = tape.gradient(loss_value, bb.trainable_weights)
            #Run SGD
            optimizer.apply_gradients(zip(grads, bb.trainable_weights))
```

for the training.

**Other info / logs** Include any logs or source code that would be helpful to

`ValueError: No gradients provided for any variable: ['basic_block_8/BB_conv_1_None/depthwise_kernel:0', 'basic_block_8/BB_conv_1_None/pointwise_kernel:0', 'basic_block_8/BB_conv_2_None/depthwise_kernel:0', 'basic_block_8/BB_conv_2_None/pointwise_kernel:0', 'basic_block_8/BN_0_None/gamma:0', 'basic_block_8/BN_0_None/beta:0']`

**Comment by RandinAk** [comment] 2021-05-05 18:32
[thanks]()

**Comment by tilakrayal** [comment] 2021-05-06 07:13
@Zodaztream ,

In order to reproduce the issue reported here, could you please provide the complete code and the dataset  or colab link you are using. 
Also please refer these issues for similar error log  #45604,#47445,#47288


Thanks!

**Comment by Zodaztream** [comment] 2021-05-06 11:51
> @Zodaztream ,
> 
> In order to reproduce the issue reported here, could you please provide the complete code and the dataset or colab link you are using.
> Also please refer these issues for similar error log #45604,#47445,#47288
> 
> Thanks!

Thanks, I have added a google colab and google drive link (for the necessary files

**Comment by sachinprasadhs** [comment] 2021-05-07 07:09
@Zodaztream , This can be due to multiple reasons, but to bring numerical stability in your gradient you can use `tf.custom_gradient` decorator by following the documentation [here](https://www.tensorflow.org/api_docs/python/tf/custom_gradient).

**Comment by Zodaztream** [comment] 2021-05-07 08:47
> @Zodaztream , This can be due to multiple reasons, but to bring numerical stability in your gradient you can use `tf.custom_gradient` decorator by following the documentation [here](https://www.tensorflow.org/api_docs/python/tf/custom_gradient).

I have implemented a custom gradient with that wrapper and unfortunately it still throws the same warning

```
    @tf.custom_gradient
    def loss_fn(self, L_hat, X_gt_sh):
        x = tf.subtract(X_gt_sh, L_hat)
        def grad(upstream):
            dl_L_hat = tf.subtract(L_hat,X_gt_sh)
            dl_L_hat = tf.reshape(dl_L_hat, (1,1,1,9))
            dl_gt_sh = tf.subtract(X_gt_sh,L_hat)
            dl_gt_sh = tf.reshape(dl_gt_sh, (1,1,1,9))
            return upstream * dl_L_hat, upstream * dl_gt_sh
        return tf.nn.l2_loss(x), grad
```

The reshape is required because for some reason dl_L_hat spit out (1,1,1,1,1,1,1,1,9) in shape

**Comment by Zodaztream** [comment] 2021-05-07 14:57
> @Zodaztream you can also try with[ tape.watch](https://www.tensorflow.org/api_docs/python/tf/GradientTape#watch) to record and trace every operation that involves any tensors.
> This can be useful in some cases, like if you want to implement a
> regularization loss that penalizes activations that vary a lot when the
> inputs vary little: the loss will be based on the gradient of the activations
> with regard to the inputs. Since the inputs are not variables, you would
> need to tell the tape to watch them.

Hey. So, we decided to rework the entire network and remove all the subsubclassed models and thus only have one model with all the layers in sequential manner. This worked. No longer do we get that gradients do not exist. However, I still feel that the first network (which is essentially the same as this sequential one, just without the calls to other subclassed models) should work. 

```
class HourglasSequential(tf.keras.models.Model):
    def __init__(self):
        super(HourglasSequential, self).__init__()
        self.nrSH_in = 27 #number of input spherical harmonics coeff.
        self.baseFilter = 16
        self.nrSH_out = 9 #if gray else 27 #nr output SH
        self.ncPre = self.baseFilter #This is the amount required for the pre-convolution step

        self.ncHG3 = self.baseFilter #this is the amount of output channels for the first and last hourglass block
        self.ncHG2 = self.baseFilter * 2
        self.ncHG1 = self.baseFilter * 4
        self.ncHG0 = self.baseFilter * 8 + self.nrSH_in # Bottleneck layer. 
      
        self.pre_conv = SeparableConv2D(self.ncPre, kernel_size=(5,5), strides=(1,1), padding="same", name="pre_conv")
        self.pre_bn = BatchNormalization(name="pre_bn")
        self.relu_1 = ReLU()
        self.HG3_BB_Upper_conv1 = SeparableConv2D(16, 3, 1, padding="same", use_bias=False)
        self.HG3_BN1 = BatchNormalization()
        #self.HG3_upper_conv1 = SeparableConv2D(16, kernel_size=(3,3), strides=(1,1), padding="same", use_bias=False) 
        #self.HG3_upper_conv2 = SeparableConv2D(16, kernel_size=(3,3), strides=(1,1), padding="same", use_bias=False) 
        #self.HG3_upper_bn = BatchNormalization()
        #self.HG3_upper_relu_1 = ReLU()
        #self.HG3_upper_relu_2 = ReLU()
    def compute_output_shape(self, input_shape):
        return [tf.TensorShape((1,1,1,9))] #Must somehow add L_hat to the dimensions
    
    def setup_model(self):
        x = tf.keras.Input(shape=(512,512,1))
        return tf.keras.models.Model(inputs=[x], outputs=self.call(x))
    
    def call(self, inputs):
        x = inputs[0]
        feat = self.pre_conv(x)
        feat = self.pre_bn(feat)
        feat = self.relu_1(feat)
        #HG3 tar in  16 som ncout, ncin = 16 som IN
        #HG3 basic block upper som tar in 16 som input och 16 som output
        feat = self.HG3_BB_Upper_conv1(feat)
        feat = self.HG3_BN1(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(16,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG3 downsample
        feat = MaxPool2D(2,2)(feat)
        #HG3 LOW1 basic block med ncIn 16 och 16 Ncout
        feat = SeparableConv2D(16, 3, 1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(16,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG2 ncIn 16, ncout = 32
        #HG2 bb upper 
        feat = SeparableConv2D(16,3,1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(16,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG2 downsample
        feat = MaxPool2D(2,2)(feat)
        #HG2 LOW1 basic block med ncIn 16 och 16 Ncout
        feat = SeparableConv2D(32, 3, 1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(32,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG1 ncIn 32, ncout = 64
        #HG1 bb upper 
        feat = SeparableConv2D(32,3,1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(32,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG1 downsample
        feat = MaxPool2D(2,2)(feat)
        #HG1 LOW1 basic block med ncIn 16 och 16 Ncout
        feat = SeparableConv2D(64, 3, 1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(64,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG0 ncIn 64, ncout = 128 + 27 = 155
        #HG0 bb upper 
        feat = SeparableConv2D(64,3,1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(64,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #HG0 downsample
        feat = MaxPool2D(2,2)(feat)
        #HG0 LOW1 basic block
        feat = SeparableConv2D(155, 3, 1, padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        feat = SeparableConv2D(155,3,1,padding="same", use_bias=False)(feat)
        feat = BatchNormalization()(feat)
        feat = ReLU()(feat)
        #LightingNet ncIn 27, out 9, middle 128
        feat = feat[:,:,:,0:27]
        feat = tf.math.reduce_mean(feat, axis=(1,2), keepdims=True)
        feat = SeparableConv2D(128, 1, 1, use_bias=False)(feat)
        feat = PReLU()(feat)
        #print(feat.shape)
        L_hat = SeparableConv2D(9,1,1, use_bias=False)(feat)

        return L_hat

```

**Comment by sachinprasadhs** [comment] 2021-05-10 14:36
@Zodaztream Please go ahead and close the issue if you don't have further queries. Thanks!

**Closed** 2021-05-24 15:48 UTC
Labels: TF 2.4, comp:ops, stalled, stat:awaiting response, type:bug
