### ISSUE TITLE
cannot import name bayesflow Error

### ISSUE THREAD

**Issue by zerok01** [tensorflow/tensorflow#18163] opened 2018-04-01 21:20 UTC
Hi, 
I get the error I mentioned in the title. I did a search on Google and I usually found a solution to update dask. I updated Dask to version 0.17.2 but I still get the same error. I can not import BayesFlow. The Tensorflow version is 0.12.1. Thanks for the answers ...

Code :  
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/")

OS : Ubuntu 16.04 LTS
Tensorflow version is 0.12.1
Cuda : 8.0
CuDNN : 5.1
GPU : 4  GB GTX 1050Ti
Dask : 0.17.2

**Comment by tensorflowbutler** [comment] 2018-04-02 06:26
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zerok01** [comment] 2018-04-02 09:09
Oh sorry, I updated my post. Thanks...

**Comment by asimshankar** [comment] 2018-04-02 17:32
0.12.1 is a very old TensorFlow release, prior to the 1.x series where we provide API stability guarantees.

This doesn't directly address your question, but is it possible for you to use a more recent (or at least a 1.x version) of TensorFlow?

Thanks!

**Comment by tensorflowbutler** [comment] 2018-04-17 12:40
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-04-17 17:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2018-04-17 17:27 UTC
Labels: stat:awaiting response
