### ISSUE TITLE
Increased Inference time after doing optimization.

### ISSUE THREAD

**Issue by purvang-ai** [tensorflow/tensorflow#37268] opened 2020-03-03 19:03 UTC
Hello,

I am trying to get an optimized graph by doing quantization and removing redundant nodes from frozen_graph.pb.  os features are

os features:
ubuntu 16.0.4 LTS
nvidia driver version = Driver Version: 440.33.01
cuda version = 10
cuDNN version = 7.4
tensorflow = 1.14.1 (built from source with cuda and tensorRT support)
GPU = NVIDIA Corporation GV100GL [Tesla V100 SXM2 16GB]
Python version: 3.6.8 (pyenv)
- Bazel version: 0.25

I ran the command which has to build the new frozen model for me.
when I tested it in production, Though the size is reduced to around 20MB but inference time is increased from  average 15ms to 26 ms.

the command to produced new optimized graph: 

bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph="/home/ubuntu/test/resnetV150_frozen.pb" \
--out_graph="/home/ubuntu/test/optimized_inception_graph.pb" \
--inputs='image_tensor' \
--outputs='resnet_v1_50/predictions/Reshape_1' \
--transforms='  
 add_default_attributes  
 strip_unused_nodes(type=float, shape="1,1280,720,3")  
 remove_nodes(op=Identity, op=CheckNumerics)  
 fold_constants(ignore_errors=true)  
 fold_batch_norms  
 fold_old_batch_norms  
 quantize_weights  
 quantize_nodes  
 strip_unused_nodes 
 sort_by_execution_order'

**Comment by amahendrakar** [comment] 2020-03-04 12:48
@purvang-ai,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment] 2020-03-11 14:52
Any update regarding the code to reproduce this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-03-18 05:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-03-18 05:37 UTC
Labels: stat:awaiting response, type:performance
