### ISSUE TITLE
can not load custom op

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#3119] opened 2016-06-30 05:39 UTC
I just do as the document'adding a new op', when i used the Op in Python, i got the error as below:
 I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    zero_out_module = tf.load_op_library('zero_out.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    raise RuntimeError(compat.as_text(py_tf.TF_Message(status)))
RuntimeError: zero_out.so: undefined symbol: _ZN10tensorflow10DEVICE_CPUE

where am i wrong?

**Comment by ibab** [comment] 2016-06-30 12:18
How did you compile the shared library?
Did you use `bazel` or a manual compilation command?

If you feel that a problem you're having might not be a bug, but just a problem with how you're using tensorflow, it's better to post it to the tensorflow Discuss group: https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss

**Comment by andydavis1** [comment] 2016-06-30 21:14
More information is required to understand the issue. Can you please provide the information requested in the "NewIssue" template:

GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by aselle** [comment] 2016-07-09 03:33
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-09 03:33 UTC
Labels: awaiting response, triaged
