### ISSUE TITLE
XLA creates CUDA contexts on GPUs not in gpu_options.visible_device_list

### ISSUE THREAD

**Issue by nluehr** [tensorflow/tensorflow#23458] opened 2018-11-02 15:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12.0-rc2
- Python version: 3.5
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: CUDA 10.0, cuDNN 7.4
- GPU model and memory: 8xV100 32GB

**Describe the current behavior**
When XLA is enabled, CUDA contexts are created on every device visible to the CUDA driver (excluding devices with CUDA_VISIBLE_DEVICES works, but gpu_options.visible_device_list in ConfigProto does not).

**Describe the expected behavior**
When gpu_options.visible_device_list is specified, CUDA contexts should only be created on the devices listed.

**Code to reproduce the issue**
To reproduce, run the following on a multi-gpu system and check nvidia-smi during the 20 second sleep.

```
import tensorflow as tf
import numpy as np
import time

config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
config.gpu_options.visible_device_list="0"

input = tf.placeholder(tf.float32, [1000])
data = np.random.rand(1000).astype('float32')
output = tf.nn.softmax(tf.nn.relu(input))

with tf.Session(config=config) as sess:
  res = sess.run(output, feed_dict={input: data})
  print("Session executed, check devices with nvidia-smi")
  time.sleep(20)
  print("Exiting")
```

**Other info / logs**

**Comment by harshini-gadige** [comment] 2018-11-07 17:44
@tatatodd   PTAL

**Comment by smit-hinsu** [comment] 2018-11-14 02:53
Assigning back to Todd as I don't see any of the GPUOptions being used in the tensorflow/compiler and I doubt if we use BaseGPUDevice for XLA.

**Comment by DEKHTIARJonathan** [comment] 2018-11-30 21:10
@smit-hinsu @tatatodd @harshini-gadige any news possible ? This issue is really limiting when using XLA...

**Comment by jlebar** [comment] 2018-12-01 01:42
I have forwarded this to the team at nvidia that has started to work on XLA:GPU.  Perhaps this will be a good first bug for someone there.

**Comment by DEKHTIARJonathan** [comment] 2018-12-01 01:47
:+1:

**Comment by samikama** [comment] 2018-12-05 21:04
#24158 should fix this.

**Comment by DEKHTIARJonathan** [comment] 2018-12-07 04:10
Thanks @samikama. It could have solved the issue, but it didn't

**Comment by DEKHTIARJonathan** [comment] 2018-12-07 04:39
Any way you can point me to this work?
Thanks a lot

**Comment by samikama** [comment] 2018-12-07 23:06
@DEKHTIARJonathan ,

Could you please try running command below with tensorflow-gpu==1.12 and tensorflow-nightly-gpu using tensorflow/benchmarks repository and post the results here.

```
mpiexec --allow-run-as-root --output-filename  RUNLOG --bind-to socket -np 4 python tf_cnn_benchmarks.py     --batch_size=256     --num_batches=90 --display_every=100     --model=resnet50     --optimizer=momentum     --variable_update=horovod       --use_fp16=True     --nodistortions    --xla     --num_gpus=1     --loss_type_to_report=base_loss --print_training_accuracy -compute_lr_on_cpu=True --single_l2_loss_op=True
```
Thanks,
Sami

**Comment by DEKHTIARJonathan** [comment] 2018-12-13 11:17
Still not solved sorry

**Comment by gongzg** [comment] 2018-12-18 08:41
@samikama  I tested the latest master branch which has all the patches in #24303 . Still met the following error message:

`2018-12-18 16:36:39.158400: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA
node, so returning NUMA node zero
2018-12-18 16:36:39.164734: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0xd7a8650 executing computations on platform CUDA. Devices:
2018-12-18 16:36:39.164800: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2018-12-18 16:36:39.167879: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500135000 Hz
2018-12-18 16:36:39.176563: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0xdb76e50 executing computations on platform Host. Devices:
2018-12-18 16:36:39.176602: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2018-12-18 16:36:39.177118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1434] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:00:07.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2018-12-18 16:36:39.177152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1513] Adding visible gpu devices: 0
2018-12-18 16:36:39.210918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-18 16:36:39.210949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:991]      0
2018-12-18 16:36:39.210958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1004] 0:   N
2018-12-18 16:36:39.211299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1116] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10466 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:00:07.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/pretraining_output/model.ckpt.
2018-12-18 16:37:03.376000: E tensorflow/core/grappler/grappler_item_builder.cc:595] Graph preprocessing failed: Invalid argument: Invalid device ordinal value (1). Valid range is [0, 0].
        while setting up XLA_GPU_JIT device number 1
`

It's a single process and set the config.gpu_options.visible_device_list = 0 .

**Comment by gongzg** [comment] 2018-12-18 09:17
@samikama  I did a quick test and found the the function XlaGpuDeviceFactory::CreateDevices() was called twice. At the first time, the session_options.config.gpu_options().visible_device_list() has correct value "0", thus we can see that it created xla device correctly. At the second time, the visible_device_list become empty, thus it will enumerate all the devices and encounter that assertion.

**Comment by samikama** [comment] 2018-12-18 18:00
@gongzg 

I don't have access to a tpu. Can you give me a GPU based reproducer, similar to one above.

Thanks,
Sami

**Comment by jlebar** [comment] 2018-12-18 18:10
> I don't have access to a tpu.

What's leading us to think that this has something to do with TPUs?

**Comment by samikama** [comment] 2018-12-18 18:20
Can I use tpu estimator to run on GPUs? 
snippet above is using TPU estimator.

**Comment by jlebar** [comment] 2018-12-18 19:18
> snippet above is using TPU estimator.

Ah, I see that now -- my browser wasn't showing the most recent edit to the comment.

This code is very clearly running on a machine with at least one GPU.

> 2018-12-18 16:36:39.177152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1513] Adding visible gpu devices: 0

Are you imagining that this machine contains both a GPU and a TPU?

**Comment by jlebar** [comment] 2018-12-18 19:36
>> Are you imagining that this machine contains both a GPU and a TPU?
> I don't know. 

Well, can we think through this a bit?

It seems to me that based on the evidence we have, either (a) you need a TPU in order to run this code and this machine has both a GPU and a TPU, or (b) you don't need a TPU in order to run this code.  Right?  Do we have a sense of which of these is more likely?  Are there simple experiments we could conduct that would e.g. tell us whether (b) is true?

**Comment by gongzg** [comment] 2018-12-18 23:55
@samikama  @jlebar   My environment only has GPU installed and without enable XLA, it could run smoothly on GPU.  You can also refer https://github.com/google-research/bert， you can see “on All of the code in this repository works out-of-the-box with CPU, GPU, and Cloud TPU.“ Actually， the TPU estimator will fallback to GPU when it could not find TPU available.

@samikama You can simply add the config option to the bert's code and run the pretraining example.

**Comment by samikama** [comment] 2018-12-20 03:48
optimize_dataset_op is ignoring GPU configuration and constructing devices for everything leading to allocations on GPUs even if XLA was not compiled in. The issue is coming from grappler_item_builder.cc file which instantiates devices with an empty session configuration which leads to allocation. Since with #24303 we started filter the xla devices to prevent allocations, issue that @gongzg observed surfaced. 
#24461 addresses this issue.

**Comment by DEKHTIARJonathan** [comment] 2019-01-08 12:46
@nluehr you can close the issue. TF Nightly build shows that the problem is fixed.

**Closed** 2019-01-08 18:02 UTC
