### ISSUE TITLE
Tflite own trained model is not running

### ISSUE THREAD

**Issue by syedali1621** [tensorflow/tensorflow#46524] opened 2021-01-19 04:24 UTC
I am using tflite object detection android sample the project is running perfectly with default model but when i change my custom object trained model and build on phone then application crushed. Is there are some steps to change model ? I just imported my tflite model in asset folder and changed name in DetectorActivity.java and DetectorTest.java. Is there any more step i need to do please let me know.
 
 Thank you

**Comment by rmothukuru** [comment] 2021-01-21 16:31
@syedali1621,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2021-01-29 10:15
@syedali1621,
Please find the steps for using a [Custom Object Detection Model](https://docs.google.com/spreadsheets/d/1LozyRzbCo8GbofYEZxG0Yl37qFmRV3kVrCTJ_mEtB-M/edit?ts=5ebdba16#gid=0). 
Thanks!

**Comment by rmothukuru** [comment] 2021-02-05 07:20
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2021-02-05 07:20 UTC
Labels: comp:lite, stalled, stat:awaiting response, type:support
