### ISSUE TITLE
error in validating tensorflow installation

### ISSUE THREAD

**Issue by mikistra** [tensorflow/tensorflow#17167] opened 2018-02-21 12:34 UTC
i installed tensorflow with cuda support on windows 10 and i'm trying to validate it,
i used this script https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c and the result is
![11](https://user-images.githubusercontent.com/15125749/36480211-c33bef0a-170b-11e8-89e6-8167389c5812.PNG)

then i tried import tensorflow as tf from python console and:
![22](https://user-images.githubusercontent.com/15125749/36480256-ecba34e0-170b-11e8-9860-53b33ce49d21.PNG)

**Comment by Carmezim** [comment] 2018-02-21 14:25
Hi @mikistra, thanks for reporting the issue. Could you please fill up the template form so we can better assess what is happening and help you?

**Comment by mikistra** [comment] 2018-02-21 17:34
hi, i'm using CUDA 8 and cuDNN 6.... sorry for the template, i missed it, wher i can find it?

**Comment by bignamehyp** [comment] 2018-02-22 23:39
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by mikistra** [comment] 2018-02-23 10:56
i'm trying to remove tensorflow, cuda, and cuDnn to start the process from the beginning, but i get errors also trying to uninstall tensorflow: 
![ca](https://user-images.githubusercontent.com/15125749/36590883-6d9e422e-1890-11e8-9dd2-9e289508df81.PNG)

if i try to install it again, it says it's already present..... is there a way to remove all tensorflow files manually??

**Comment by Carmezim** [comment] 2018-02-23 13:46
@mikistra Did you make sure your `pip` is linked to the correct Python installation. For instance, did you mean to use Python 3 and so should use `pip3 install\uninstall`?

**Comment by mikistra** [comment] 2018-02-24 00:50
@Carmezim  you were right, I feel so dumb. Now i'm going to have a fresh installation of everything and then in case of problem start a thread filling the template correctly. So maybe you can can close this...

**Comment by Carmezim** [comment] 2018-02-25 20:57
@mikistra No worries, it happens :). Thank you for reporting the issue and following up, glad it's working now. Feel free to close the issue.

**Closed** 2018-02-25 21:48 UTC
Labels: stat:awaiting response
