### ISSUE TITLE
Tensorflow compile error with win7

### ISSUE THREAD

**Issue by taotaolin** [tensorflow/tensorflow#22268] opened 2018-09-14 02:50 UTC
**Have I written custom code** No
**OS Platform and Distribution** WIN7  Visual Studio 2015
**TensorFlow installed from**  source  r1.10
**Bazel version** N/A
**CUDA/cuDNN version** CUDA9.0  /   CUDNN  7.0
**GPU model and memory**   1080Ti / 11G 
**Mobile device**  N/A
**Exact command to reproduce** 
**1, cmake** 
```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Debug 
-T host=x64 -DSWIG_EXECUTABLE=D:/lib/swigwin-3.0.12/swig.exe 
-DPYTHON_EXECUTABLE=C:/Users/tao/AppData/Local/Programs/Python/python35/python.exe 
-DPYTHON_LIBRARIES=C:/Users/tao/AppData/Local/Programs/Python/python35/libs/python35.lib 
-Dtensorflow_ENABLE_GPU=ON 
-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF 
-Dtensorflow_BUILD_SHARED_LIB=ON
```
**2. build**
`MSBuild /p:Configuration=Debug /p:Platform=x64 ALL_BUILD.vcxproj`

### Describe the problem
When I compiled the Tensorflow with source code, there exist some errors:
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl tensorflow::NewRemoteDevices(class tensorflow::Env *,class tensorflow::WorkerCacheInterface *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<void __cdecl(class tensorflow::Status const &,class std::vector<class tensorflow::Device *,class std::allocator<class tensorflow::Device *> > *)>)" (?NewRemoteDevices@tensorflow@@YAXPEAVEnv@1@PEAVWorkerCacheInterface@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXAEBVStatus@tensorflow@@PEAV?$vector@PEAVDevice@tensorflow@@V?$allocator@PEAVDevice@tensorflow@@@std@@@std@@@Z@5@@Z)，该符号在函数 "class tensorflow::Status __cdecl `anonymous namespace'::GetAllRemoteDevices(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class tensorflow::WorkerCacheInterface *,class std::unique_ptr<class tensorflow::DeviceMgr,struct std::default_delete<class tensorflow::DeviceMgr> > *)" (?GetAllRemoteDevices@?A0x02eb28b0@@YA?AVStatus@tensorflow@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEAVWorkerCacheInterface@3@PEAV?$unique_ptr@VDeviceMgr@tensorflow@@U?$default_delete@VDeviceMgr@tensorflow@@@std@@@5@@Z) 中被引用	tensorflow	G:\tensorflow\tensorflow\contrib\cmake\build\c_api.cc.obj	1	
错误	LNK2019	无法解析的外部符号 "public: class tensorflow::Status __cdecl tensorflow::SessionMgr::CreateSession(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class tensorflow::ServerDef const &,bool)" (?CreateSession@SessionMgr@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVServerDef@2@_N@Z)，该符号在函数 "class tensorflow::Status __cdecl `anonymous namespace'::NewRemoteAwareTFE_Context(struct TFE_ContextOptions const *,struct TFE_Context * *)" (?NewRemoteAwareTFE_Context@?A0x02eb28b0@@YA?AVStatus@tensorflow@@PEBUTFE_ContextOptions@@PEAPEAUTFE_Context@@@Z) 中被引用	tensorflow	G:\tensorflow\tensorflow\contrib\cmake\build\c_api.cc.obj	1	
错误	LNK2019	无法解析的外部符号 "public: class tensorflow::Status __cdecl tensorflow::SessionMgr::WorkerSessionForSession(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::shared_ptr<struct tensorflow::WorkerSession> *)" (?WorkerSessionForSession@SessionMgr@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$shared_ptr@UWorkerSession@tensorflow@@@5@@Z)，该符号在函数 "class tensorflow::Status __cdecl `anonymous namespace'::NewRemoteAwareTFE_Context(struct TFE_ContextOptions const *,struct TFE_Context * *)" (?NewRemoteAwareTFE_Context@?A0x02eb28b0@@YA?AVStatus@tensorflow@@PEBUTFE_ContextOptions@@PEAPEAUTFE_Context@@@Z) 中被引用	tensorflow	G:\tensorflow\tensorflow\contrib\cmake\build\c_api.cc.obj	1	
错误	LNK2019	无法解析的外部符号 "class tensorflow::eager::EagerClientCache * __cdecl tensorflow::eager::NewGrpcEagerClientCache(class std::shared_ptr<class tensorflow::GrpcChannelCache>)" (?NewGrpcEagerClientCache@eager@tensorflow@@YAPEAVEagerClientCache@12@V?$shared_ptr@VGrpcChannelCache@tensorflow@@@std@@@Z)，该符号在函数 "class tensorflow::Status __cdecl `anonymous namespace'::NewRemoteAwareTFE_Context(struct TFE_ContextOptions const *,struct TFE_Context * *)" (?NewRemoteAwareTFE_Context@?A0x02eb28b0@@YA?AVStatus@tensorflow@@PEBUTFE_ContextOptions@@PEAPEAUTFE_Context@@@Z) 中被引用	tensorflow	G:\tensorflow\tensorflow\contrib\cmake\build\c_api.cc.obj	1	
错误	LNK1120	4 个无法解析的外部命令	tensorflow	G:\tensorflow\tensorflow\contrib\cmake\build\Debug\tensorflow.dll	1	
```
can anyone help me , thx

**Comment by taotaolin** [comment] 2018-09-17 01:36
i try using bazel to build on windows, but tips:

**Have I written custom code** No
**OS Platform and Distribution** WIN7 Visual Studio 2015
**TensorFlow installed from source**  master
**Bazel version**  0.17.1
**CUDA/cuDNN version** CUDA9.0 / CUDNN 7.2.1
**GPU model and memory** 1080Ti / 11G
**Mobile device** N/A
**Exact command to reproduce**
**1. python ./configure.py**
**2.bazel build --config=opt --config=cuda //tensorflow:libtensorflow.so**
```
G:\tensorflow>bazel build --config=opt --config=cuda //tensorflow:libtensorflow.
so
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeata
ble flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow
ERROR: Skipping '//tensorflow:libtensorflow.so': error loading package 'tensorfl
ow': Encountered error while reading extension file 'cuda/build_defs.bzl': no su
ch package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1458
                _create_local_cuda_repository(repository_ctx)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1185, in
_create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 909, in _
get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 584, in _
cudnn_version
                find_cuda_define(repository_ctx, cudnn_header_dir, "c...", ...)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 534, in f
ind_cuda_define
                auto_configure_fail(("Error reading %s: %s" % (str(h...)))
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 315, in a
uto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Error reading G:/cudnn/include/cudnn.h: java.io.IOExce
ption: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("gre
p" --color=never -A1 -E "#define CUDNN_MAJOR" G:/cudnn/include/cudnn.h): ???????
????

WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow': Encountered error while reading exten
sion file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Tra
ceback (most recent call last):
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1458
                _create_local_cuda_repository(repository_ctx)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1185, in
_create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 909, in _
get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 584, in _
cudnn_version
                find_cuda_define(repository_ctx, cudnn_header_dir, "c...", ...)
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 534, in f
ind_cuda_define
                auto_configure_fail(("Error reading %s: %s" % (str(h...)))
        File "G:/tensorflow/third_party/gpus/cuda_configure.bzl", line 315, in a
uto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Error reading G:/cudnn/include/cudnn.h: java.io.IOExce
ption: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("gre
p" --color=never -A1 -E "#define CUDNN_MAJOR" G:/cudnn/include/cudnn.h): ???????
????

INFO: Elapsed time: 3.607s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by gunan** [comment] 2018-09-17 03:27
```
Cuda Configuration Error: Error reading G:/cudnn/include/cudnn.h: java.io.IOExce
ption: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("gre
p" --color=never -A1 -E "#define CUDNN_MAJOR" G:/cudnn/include/cudnn.h): ???????
????
```
This means either cudnn.h is unreadable for bazel, or it is not located at `G:/cudnn/include/cudnn.h`
What is the location of your cudnn headers on your machine?
Did you follow these:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installwindows

**Comment by taotaolin** [comment] 2018-09-17 05:35
> G:/cudnn/include/cudnn.h
Now tips:
```
G:\tensorflow>bazel build --config = opt --config = cuda //tensorflow:libtensorf
low.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Options provided by the client:
  'build' options: --python_path=C:/Python27/python.exe
INFO: Reading rc options for 'build' from g:\tensorflow\tools\bazel.rc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_p
rotos=true --define=allow_oversize_protos=true --define=grpc_no_ares=true --spaw
n_strategy=standalone --genrule_strategy=standalone -c opt
INFO: Reading rc options for 'build' from g:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/tao/AppData/Local/Progr
ams/Python/Python35/python.exe --action_env PYTHON_LIB_PATH=C:/Users/tao/AppData
/Local/Programs/Python/Python35/lib/site-packages --python_path=C:/Users/tao/App
Data/Local/Programs/Python/Python35/python.exe --action_env TF_NEED_OPENCL_SYCL=
0 --action_env TF_NEED_CUDA=1 --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NV
IDIA GPU Computing Toolkit/CUDA/v9.0 --action_env TF_CUDA_VERSION=9.0 --action_e
nv CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 --
action_env TF_CUDNN_VERSION=7 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5 --ac
tion_env TF_CUDA_CLANG=0 --config=cuda --define grpc_no_ares=true --strip=always
 --config monolithic --copt=-w --host_copt=-w --verbose_failures
INFO: Found applicable config definition build:cuda in file g:\tensorflow\tools\
bazel.rc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using
_cuda=true --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:monolithic in file g:\tensorflow\
tools\bazel.rc: --define framework_shared_object=false
ERROR: Config value = is not defined in any .rc file
```

**Comment by gunan** [comment] 2018-09-17 05:51
Did you run configure script?
Also, in bazel command line syntax, you are not allowed to have empty spaces around `=`, so you need to provide the options as `--config=opt --config=cuda`

**Comment by taotaolin** [comment] 2018-09-17 05:58
> Did you run configure script?
> Also, in bazel command line syntax, you are not allowed to have empty spaces around `=`, so you need to provide the options as `--config=opt --config=cuda`

It has been complied. but have err:
```
G:\tensorflow>bazel build --config=opt --config=cuda //tensorflow:libtensorflow.
so
WARNING: The following configs were expanded more than once: [cuda]. For repeata
ble flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow
Loading: 0 packages loaded
    currently loading: tensorflow
Loading: 0 packages loaded
    currently loading: tensorflow
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest
Visual C++ installed.
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variabl
es, eg. VS140COMNTOOLS
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x8
6)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest
Visual C++ installed.
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variabl
es, eg. VS140COMNTOOLS
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x8
6)\Microsoft Visual Studio 14.0\VC\
Analyzing: target //tensorflow:libtensorflow.so (1 packages loaded)
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest
Visual C++ installed.
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variabl
es, eg. VS140COMNTOOLS
DEBUG: C:/users/tao/_bazel_tao/ic7qrvhc/external/bazel_tools/tools/cpp/lib_cc_co
nfigure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x8
6)\Microsoft Visual Studio 14.0\VC\
Analyzing: target //tensorflow:libtensorflow.so (10 packages loaded)
Analyzing: target //tensorflow:libtensorflow.so (45 packages loaded)
Analyzing: target //tensorflow:libtensorflow.so (72 packages loaded)
Analyzing: target //tensorflow:libtensorflow.so (84 packages loaded)
ERROR: G:/tensorflow/tensorflow/core/platform/default/build_config/BUILD:188:1:
no such package '@png_archive//': Traceback (most recent call last):
        File "G:/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "G:/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "G:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_chec
k_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch
 -p1 -d C:/users/tao/_bazel_tao/ic7qrvhc/external/png_archive -i G:/tensorflow/t
hird_party/png_fix_rpi.patch':
Stdout:
Stderr: Timed out and referenced by '//tensorflow/core/platform/default/build_co
nfig:png'
ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted:
 Analysis failed
INFO: Elapsed time: 56.491s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (84 packages loaded)
FAILED: Build did NOT complete successfully (84 packages loaded)
```
i can't understand why`no such package '@png_archive//': Traceback (most recent call last):` is produced

**Comment by gunan** [comment] 2018-09-17 06:10
@meteorcloudy to help with that quqestion.
Yun, looks like this is happening for a few users now.
Our CI cannot reproduce the problem.
Any idea what is going on?

**Comment by meteorcloudy** [comment] 2018-09-17 08:00
Indeed, I couldn't reproduce this, either.
But @taotaolin can you try to reinstall patch by `C:\msys64\usr\bin\pacman.exe -S patch`?

**Comment by taotaolin** [comment] 2018-09-17 08:07
> Indeed, I couldn't reproduce this, either.
> But @taotaolin can you try to reinstall patch by `C:\msys64\usr\bin\pacman.exe -S patch`?
It still remains like this
```
C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/tao/_bazel_tao/ic7qrvhc/external/png_archive -i G:/tensorflow/third_party/png_fix_rpi.patch:
```
can't work but 

```
C:\msys64\usr\bin\bash.exe -l -c "patch -p1 -d C:/users/tao/_bazel_tao/ic7qrvhc/external/png_archive -i G:/tensorflow/third_party/png_fix_rpi.patch"
```
it can work

**Comment by meteorcloudy** [comment] 2018-09-17 08:16
I believe Bazel does pass the arguments as
`C:\msys64\usr\bin\bash.exe -l -c "patch -p1 -d C:/users/tao/_bazel_tao/ic7qrvhc/external/png_archive -i G:/tensorflow/third_party/png_fix_rpi.patch"`

It's just missing the quotes when printing the command in terminal.

Can you try to add `-f` here:
https://github.com/tensorflow/tensorflow/blob/f1d42c8967410db1e08c0b6d62dc1fc4844165a8/third_party/repo.bzl#L71
like:
`["patch", "-f", "-p1", "-d", ctx.path("."), "-i", ctx.path(patch_file)], `

**Comment by taotaolin** [comment] 2018-09-17 08:39
> I believe Bazel does pass the arguments as
> `C:\msys64\usr\bin\bash.exe -l -c "patch -p1 -d C:/users/tao/_bazel_tao/ic7qrvhc/external/png_archive -i G:/tensorflow/third_party/png_fix_rpi.patch"`
> 
> It's just missing the quotes when printing the command in terminal.
> 
> Can you try to add `-f` here:
> [tensorflow/third_party/repo.bzl](https://github.com/tensorflow/tensorflow/blob/f1d42c8967410db1e08c0b6d62dc1fc4844165a8/third_party/repo.bzl#L71)
> 
> Line 71 in [f1d42c8](/tensorflow/tensorflow/commit/f1d42c8967410db1e08c0b6d62dc1fc4844165a8)
> 
>  ["patch", "-p1", "-d", ctx.path("."), "-i", ctx.path(patch_file)], 
> 
> like:
> `["patch", "-f", "-p1", "-d", ctx.path("."), "-i", ctx.path(patch_file)],`

Can provide `tensorflow.dll` and `tensorflow.lib` for windows tensorflow, preferably DEBUG version？thx.

**Comment by meteorcloudy** [comment] 2018-09-17 09:50
@taotaolin , can you run `bazel clean --expunge` and then try to rebuild?

**Comment by meteorcloudy** [comment] 2018-09-17 14:56
@taotaolin If that didn't work, can you type `where patch` in your terminal? Just trying to make sure you have the correct patch binary in `PATH`

**Comment by taotaolin** [comment] 2018-09-17 15:43
> @taotaolin If that didn't work, can you type `where patch` in your terminal? Just trying to make sure you have the correct patch binary in `PATH`

It can now be compiled, but it seems that something went wrong, maybe because my Windows language is Chinese ，so it's error is garbled, I can't understand what went wrong. tips:
```
tensorflow\bazel-out\x64_windows-opt\genfiles\external\local_config_cuda\cuda\cu
da\include\crt\host_defines.h
脳垄脪芒: 掳眉潞卢脦脛录镁:       bazel-out/x64_windows-opt/genfiles/external/lo
cal_config_cuda/cuda/cuda/include\math_constants.h
脳垄脪芒: 掳眉潞卢脦脛录镁:       bazel-out/x64_windows-opt/genfiles/external/lo
cal_config_cuda/cuda/cuda/include\crt/func_macro.h
脳垄脪芒: 掳眉潞卢脦脛录镁:   c:\users\tao\appdata\local\temp\nvcc_inter_files_t
mp_dir\conv_ops_gpu_2.cu.fatbin.c
脳垄脪芒: 掳眉潞卢脦脛录镁:    bazel-out/x64_windows-opt/genfiles/external/local
_config_cuda/cuda/cuda/include\fatBinaryCtl.h
脳垄脪芒: 掳眉潞卢脦脛录镁:     c:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_te
nsorflow\bazel-out\x64_windows-opt\genfiles\external\local_config_cuda\cuda\cuda
\include\fatbinary.h
**external/com_google_absl\absl/container/inlined_vector.h(651): error C3083: 隆掳
`global namespace'隆卤:隆掳::隆卤脳贸虏脿碌脛路没潞脜卤脴脨毛脢脟脪禄脰脰脌脿脨
脥**
external/com_google_absl\absl/container/inlined_vector.h(92): note: 卤脿脪毛脌脿
 脛拢掳氓 鲁脡脭卤潞炉脢媒隆掳absl::InlinedVector<__int64,6,std::allocator<_Ty>>
::InlinedVector(unsigned __int64,const std::allocator<_Ty> &)隆卤脢卤
        with
        [
            _Ty=__int64
        ]
.\tensorflow/core/util/tensor_format.h(497): note: 虏脦录没露脭脮媒脭脷卤脿脪毛
碌脛潞炉脢媒 脛拢掳氓 脢碌脌媒禄炉隆掳absl::InlinedVector<__int64,6,std::allocat
or<_Ty>>::InlinedVector(unsigned __int64,const std::allocator<_Ty> &)隆卤碌脛脪
媒脫脙
        with
        [
            _Ty=__int64
        ]
.\tensorflow/core/util/tensor_format.h(497): note: 虏脦录没露脭脮媒脭脷卤脿脪毛
碌脛脌脿 脛拢掳氓 脢碌脌媒禄炉隆掳absl::InlinedVector<__int64,6,std::allocator<_
Ty>>隆卤碌脛脪媒脫脙
        with
        [
            _Ty=__int64
        ]
.\tensorflow/core/util/tensor_format.h(451): note: 虏脦录没露脭脮媒脭脷卤脿脪毛
碌脛脌脿 脛拢掳氓 脢碌脌媒禄炉隆掳absl::Span<const __int64>隆卤碌脛脪媒脫脙
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 25.775s, Critical Path: 23.45s
INFO: 14 processes: 14 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by gunan** [comment] 2018-09-17 17:29
The latest is an issue that was fixed last week. You will need to sync your code to head and retry.
At this point, this is becoming a technical support issue. It is now clear that this is not a bug in TensorFlow, but rather setup problems in your environment.

Please make sure to follow this page to be able to build TF on windows:
https://www.tensorflow.org/install/install_sources_windows
All the solutions to the issues you faced are already documented there.

Closing this issue.

**Closed by gunan** 2018-09-17 17:29 UTC
Labels: stat:awaiting tensorflower, type:build/install

**Comment by taotaolin** [comment] 2018-09-18 01:06
> The latest is an issue that was fixed last week. You will need to sync your code to head and retry.
> At this point, this is becoming a technical support issue. It is now clear that this is not a bug in TensorFlow, but rather setup problems in your environment.
> 
> Please make sure to follow this page to be able to build TF on windows:
> https://www.tensorflow.org/install/install_sources_windows
> All the solutions to the issues you faced are already documented there.
> 
> Closing this issue.

I tried to recompile the latest version of git, prompting CUDA to compile. Is this a problem with my CUDA?Rename the compiled tensorflow.so to tensorflow.dll and it will work?
tips:
```
c:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_tensorflow\external\eigen_archive\
unsupported\eigen\src/SpecialFunctions/SpecialFunctionsImpl.h(712): warning: mis
sing return statement at end of non-void function "Eigen::internal::igamma_serie
s_impl<Scalar, mode>::run [with Scalar=double, mode=Eigen::internal::SAMPLE_DERI
VATIVE]"
          detected during:
            instantiation of "Scalar Eigen::internal::igamma_series_impl<Scalar,
 mode>::run(Scalar, Scalar) [with Scalar=double, mode=Eigen::internal::SAMPLE_DE
RIVATIVE]"
(863): here
            instantiation of "Scalar Eigen::internal::igamma_generic_impl<Scalar
, mode>::run(Scalar, Scalar) [with Scalar=double, mode=Eigen::internal::SAMPLE_D
ERIVATIVE]"
(2108): here
            instantiation of "Eigen::internal::gamma_sample_der_alpha_retval<Eig
en::internal::global_math_functions_filtering_base<Scalar, void>::type>::type Ei
gen::numext::gamma_sample_der_alpha(const Scalar &, const Scalar &) [with Scalar
=double]"
c:\users\tao\_bazel_tao\ic7qrvhc\execroot\org_tensorflow\external\eigen_archive\
unsupported\eigen\src/SpecialFunctions/arch/CUDA/CudaSpecialFunctions.h(154): he
re

1 error detected in the compilation of "C:/Users/tao/AppData/Local/Temp/nvcc_int
er_files_tmp_dir/scatter_nd_op_gpu.cu.compute_70.cpp1.ii".
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 604.372s, Critical Path: 166.44s
INFO: 1476 processes: 1476 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

**Comment by meteorcloudy** [comment] 2018-09-18 07:55
@taotaolin Can you sync TF repo to HEAD, this issue should be fixed already.

**Comment by taotaolin** [comment] 2018-09-18 12:04
> @taotaolin Can you sync TF repo to HEAD, this issue should be fixed already.

How should I choose to compile the debug version or the realse version?

**Comment by rychnal** [comment] 2018-09-26 15:58
I have same problem like @taotaolin but add -f not help for me

`bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram -- --input_wav=C:\Users\Lukas\Downloads\music.wav --output_image=C:\Users\Lukas\Downloads\spectogrammmm.png

Starting local Bazel server and connecting to it...
ERROR: C:/users/lukas/documents/source/tensorflow-new/tensorflow/core/platform/default/build_config/BUILD:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/lukas/documents/source/tensorflow-new/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/lukas/documents/source/tensorflow-new/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/lukas/documents/source/tensorflow-new/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c patch -p1 -d C:/users/lukas/_bazel_lukas/zizotpgp/external/png_archive -i C:/users/lukas/documents/source/tensorflow-new/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: p┼Ö├şkaz nenalezen
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram' failed; build aborted: Analysis failed
INFO: Elapsed time: 94,156s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (71 packages loaded)
FAILED: Build did NOT complete successfully (71 packages loaded)`
bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram -- --input_wav=C:\Users\Lukas\Downloads\music.wav --output_image=C:\Users\Lukas\Downloads\spectogrammmm.png

I use bazel 0.17.2
Windwos 10
tensofrlow: master branch with HEAD 

Can you give me any advice? Thanks

**Comment by taotaolin** [comment] 2018-09-27 02:04
@rychnal 
I seem to have this error due to a bad network, it becomes normal after using the proxy.
