### ISSUE TITLE
Building the pip package on Windows

### ISSUE THREAD

**Issue by majo451** [tensorflow/tensorflow#23078] opened 2018-10-18 19:16 UTC
Hi,

I'm trying to build tensorflow from source. I managed to successfully finish the bazel build step (CPU-only), but when I run the command 

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

what happens is that the build_pip_package process spawns itself and the bash process multiple times (like a 1000 times) and the whole process ends with an out of memory error. Here's the output of the command:

bazel-bin\tensorflow\tools\pip_package\build_pip_package .\tfbuild
/usr/bin/bash: warning: shell level (1000) too high, resetting to 1
LAUNCHER ERROR: Cannot launch process: "C:/msys64/usr/bin/bash.exe
Reason: (error: 8): Not enough memory resources are available to process this command.

Is there a way to limit the number of spawned processes? I cannot find any help online.

Update:
**Have I written custom code: NO
OS Platform and Distribution: Windows 10
TensorFlow installed from: N/A
TensorFlow version: latest sources
Bazel version: 0.18.0 x64 (2018-10-15)
CUDA/cuDNN version: N/A
GPU model and memory: Intel HD graphics
Exact command to reproduce: bazel-bin\tensorflow\tools\pip_package\build_pip_package .\tfbuild
Mobile device: NO**

Thank You

**Comment by tensorflowbutler** [comment] 2018-10-19 06:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by gunan** [comment] 2018-10-31 03:52
From your logs, I am pretty certain this is an msys issue on your system.
Googling your problem gets me to this:
https://github.com/mintty/wsltty/issues/6

Have to tried looking through msys issues?

**Comment by ymodak** [comment] 2018-11-14 21:55
Is this still an issue? Did you a chance to look at ?

> From your logs, I am pretty certain this is an msys issue on your system.
> Googling your problem gets me to this:
> [mintty/wsltty#6](https://github.com/mintty/wsltty/issues/6)
> 
> Have to tried looking through msys issues?

**Comment by tensorflowbutler** [comment] 2018-11-29 19:16
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-11-29 21:44
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-29 21:44 UTC
Labels: stat:awaiting response, type:build/install
