### ISSUE TITLE
freeze_graph returns with error

### ISSUE THREAD

**Issue by roche-k** [tensorflow/tensorflow#21670] opened 2018-08-17 06:26 UTC
I used `bazel-bin/tensorflow/python/tools/freeze_graph` to freeze my graph. This program complied with bazel several minutes ago.
But this returns with error:

```
Traceback (most recent call last):
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 27, in <module>
    from tensorflow.python.framework import function
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 39, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/home/roche/git/download/tensorflow-1.10.0/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 181, in <module>
    class _ReuseMode(enum.Enum):
NameError: name 'enum' is not defined
```

Here's my environment specification:
Sys:Debian 9.5
python:python 3.5.3
Tensorflow: tensorflow (1.10.0) from pip3
bazel:0.16.1
gcc:gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

tensorflow souce code from 1.10.0 release.

**Comment by tensorflowbutler** [comment] 2018-08-17 18:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by roche-k** [comment] 2018-08-20 02:10
OS: Debian 9.5
python: python 3.5.3
Tensorflow: tensorflow (1.10.0) installed from pip3, CPU version
CPU: Intel i5 3470
bazel: 0.16.1
freeze_graph complied from: tensorflow 1.10.0 release
gcc: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Exact command to reproduce: ./bazel-bin/tensorflow/python/tools/freeze_graph

**Comment by asimshankar** [comment] 2018-08-23 05:11
Is the source modified at all? 
The `enum` symbol it is complaining about should be coming from the Python standard library imported [here](https://github.com/tensorflow/tensorflow/blob/0e53c66f338a60be5ea348fdeb7b19e5b579971f/tensorflow/python/ops/variable_scope.py#L24).

**Comment by roche-k** [comment] 2018-08-24 14:01
No modification.
I just download the tf 1.10 release, then complied it.

**Comment by asimshankar** [comment] 2018-09-04 19:57
Seems like some quirk of the environment this is being run in. Does the following work:

```python
import enum

class Foo(enum.Enum):
  pass
```
?

Marking as "Community Support" to engage the broader community in this (also, I'm unable to reproduce this in my environment, using:

```sh
./configure
bazel build -c opt //tensorflow/python/tools:freeze_graph
./bazel-bin/tensorflow/tools/python/freeze_graph --help
```

**Comment by tilakrayal** [comment] 2021-08-25 11:00
@roche-k ,
We see that you are using older version of tensorflow (1.x) which is not actively supported. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!

**Closed** 2021-09-08 11:42 UTC
Labels: stat:awaiting response, stat:community support, type:support, stalled, comp:ops
