### ISSUE TITLE
MutilGPU Model can't restore model

### ISSUE THREAD

**Issue by junqiangchen** [tensorflow/tensorflow#15551] opened 2017-12-21 09:47 UTC
Hi,I use multiple GPU training with tensorflow1.0, and save the model sucessfully, when I restore the model, the error appear here  #line:saver=tf.train.Saver(tf.all_variables()),ValueError:No Variable to save.
I try restore model in training,it works.So,i am confused what is wrong?can anybody help me.
Thank you

**Comment by tensorflowbutler** [comment] 2017-12-22 07:26
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-05 19:07
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-01-24 13:14
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-08 19:23
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-23 14:00
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-10 13:07
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 12:31
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatatodd** [comment] 2018-05-17 01:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatatodd** 2018-05-17 01:02 UTC
Labels: stat:awaiting response
