### ISSUE TITLE
RuntimeError: Can't copy Tensor with type string to device

### ISSUE THREAD

**Issue by karansaxena** [tensorflow/tensorflow#38343] opened 2020-04-08 06:36 UTC
**System information** 
- 
- OS Platform and Distribution: Ubuntu 18.04.2 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.7
- CUDA/cuDNN version: CUDA 10.2 
- GPU model and memory: Tesla V100-SXM2-32GB 

**Describe the current behavior**
RuntimeError: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0.

**Describe the expected behavior**
Runs perfectly on CPU

**Standalone code to reproduce the issue** 
 https://tfhub.dev/google/universal-sentence-encoder-large/5 **ON A GPU**.

    import tensorflow_hub as hub

    embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/5")

    with tf.device('GPU:0'):
    
        embeddings = embed(["The quick brown fox jumps over the lazy dog."])

    print embeddings

**Other info / logs**
Traceback (most recent call last):
  File "create_sentence_embeddings.py", line 25, in <module>
    temp = embed(ele)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 438, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 636, in _call
    *args, **kwds)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2185, in canonicalize_function_inputs
    self._flat_input_signature)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2240, in _convert_inputs_to_signature
    value, dtype_hint=spec.dtype)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1302, in convert_to_tensor
    value, dtype=preferred_dtype, name=name, as_ref=as_ref)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 317, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
RuntimeError: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0.

**Comment by amahendrakar** [comment] 2020-04-08 09:29
@karansaxena,
I was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/6d6771bfe50c85641669ea0f99bf3d3a/38343-2-1.ipynb). However, the issue seems to be fixed with [TF v2.2.0-rc2](https://colab.research.google.com/gist/amahendrakar/5ebf14eda7b2a936d60698664446c064/38343-2-2.ipynb). Please find the attached gist. Thanks!

**Comment by karansaxena** [comment] 2020-04-08 18:09
@amahendrakar yes, looks like TF v2.2.0-rc2 is working.
If I extend the list of sentences, I am consistently running into:
     E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
     F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
     Aborted (core dumped)

Although this looks like a CUDA/cudnn error, but do you happen to know?

`nvcc --version` output:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

cudnn version: 7.6.5

`nvidia-smi` gives CUDA version as 10.2

**Comment by karansaxena** [comment] 2020-04-08 18:56
@amahendrakar The CUDA_ERROR_ILLEGAL_ADDRESS does not come when I use the 'small' model from https://tfhub.dev/google/universal-sentence-encoder/4.

**Comment by amahendrakar** [comment] 2020-04-14 17:03
> @amahendrakar The CUDA_ERROR_ILLEGAL_ADDRESS does not come when I use the 'small' model from https://tfhub.dev/google/universal-sentence-encoder/4.

@karansaxena,
Regarding this, could you please create a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and close this one, so that we can track it there. Thanks!

**Comment by amahendrakar** [comment] 2020-04-21 10:45
Any updates regarding this issue? Thanks!

**Comment by pjherron** [comment] 2020-04-22 17:01
Getting same error.  Also wondering if the following behavior happens with anyone else.

Ubuntu 18.04.4 LTS/CUDA 10.2, v10.2.89/Tesla V100-SXM2-16GB/Python 3.6.6/TF 2.1.0

Surprisingly not only can I work around with
        `with tf.device('/device:CPU:0'):`
instead of
        `with tf.device('/device:GPU:0'):`  
my nvidia-smi shows usage of the GPU even though I called the CPU. The gpu usage is showing usage at a level that I would have expected had I explicitly called for use of the GPU.

Could this be a problem with` tf.device()`? Or is ` tf.device()` just no longer needed?

**Comment by amahendrakar** [comment] 2020-04-28 07:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by amahendrakar** [comment] 2020-04-28 07:28
@pjherron,
Could you please create a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track it there. Thanks!

**Closed by amahendrakar** 2020-04-28 07:27 UTC
Labels: TF 2.0, comp:gpu, stat:awaiting response, type:bug
