### ISSUE TITLE
resize_image_with_crop_or_pad loses channel information

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4268] opened 2016-09-08 06:50 UTC
```python
png = tf.image.resize_image_with_crop_or_pad(png_raw, 100, 100)
```
before:
```
TensorShape([Dimension(None), Dimension(None), Dimension(3)])
```
after:
```
TensorShape([Dimension(100), Dimension(100), Dimension(None)]
```

`tf.image.pad_to_bounding_box` has the same problem.
The combination of these two lines seems questionable:
```
height, width, depth = _ImageDimensions(image, static_only=False)
padded_shape = [None if is_tensor(i) else i
                  for i in [target_height, target_width, depth]]
```
why set `static_only=False`? The docs for `_ImageDimensions` say:
>    list of integers `[batch, height, width, channels]`, when static shape is
    fully defined or `static_only` is `True`.
    list of integer scalar tensors `[batch, height, width, channels]`, when
    static shape is not fully defined.

so unless all dimensions of the image are defined you will get tensors which will then be changed to `None`.

**Comment by tatatodd** [comment] 2016-09-09 18:24
Thanks for the report @cancan101!  Please add additional information (e.g. tensorflow version) - try to fill out the template that appears when you click the green "New issue" button, and add it to this issue.  Thanks!

**Comment by cancan101** [comment] 2016-09-09 18:43
here, though the code snippet I reference is (still) in master:
```
 bazel version
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```
```
 git rev-parse HEAD
58b37cf745c6c30d44878ddf5987c4283ed12c3c
```
```
ls -l /usr/lib/x86_64-linux-gnu/libcud*
lrwxrwxrwx 1 root root       29 Aug 12 05:11 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root       17 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn.so.5 -> libcudnn.so.5.1.3
-rw-r--r-- 1 root root 60696704 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.3
lrwxrwxrwx 1 root root       32 Aug 12 05:11 /usr/lib/x86_64-linux-gnu/libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 59715990 Jun 10 13:07 /usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
```
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
```

**Comment by tatatodd** [comment] 2016-09-10 01:08
@cancan101 I see what you're saying, and I agree there seems to be a bug here.

WRT the details, I don't think calling `_ImageDimensions(image, static_only=True)` sounds right, since the sizes are not actually statically known.  Instead I think we want to treat the depth separately from the width and height, but I'm not sure what the right fix is.

@gaohuazuo I believe you wrote the current version in PR #2737 - can you comment on whether you agree there's a problem here, and how we might fix things?

Thanks all!

**Comment by cancan101** [comment] 2016-09-10 01:12
Ok then perhaps the bug is here:
```
padded_shape = [None if is_tensor(i) else i
                  for i in [target_height, target_width, depth]]
```
which ignore tensors even if they are constant values.

**Comment by gaohuazuo** [comment] 2016-09-10 03:51
I think the problem is that `_ImageDimensions` returns tensors even if integer is possible for some dimensions.

Possible fix (not tested) https://github.com/gaohuazuo/tensorflow/commit/85ce1fbb7d7d190b9cb5c6d8c87b986fb1358467

**Comment by tatatodd** [comment] 2016-09-13 21:55
Thanks @gaohuazuo!  I think that's right.  I'll add some tests and update this bug when the fix is in.

**Comment by tatatodd** [comment] 2016-09-19 23:33
I committed the fix and it's now visible in the public repo:
https://github.com/tensorflow/tensorflow/commit/2e7b5c3ee82673fe5affd8de32eed0b350a451bf

FYI the basic idea behind the fix is exactly what @gaohuazuo said; we now return python integers rather than tensors for known dimensions.

Thanks again for filing the bug @cancan101!

**Closed by tatatodd** 2016-09-19 23:33 UTC
