### ISSUE TITLE
FAILED: Build did NOT complete successfully (101 packages loaded)

### ISSUE THREAD

**Issue by sxsxsx** [tensorflow/tensorflow#21163] opened 2018-07-26 13:32 UTC
lyq@lyq-virtual-machine:~/yqli/tensorflow$ sudo bazel build tensorflow/tools/quantization:quantize_graph
ERROR: /home/lyq/yqli/tensorflow/tensorflow/BUILD:449:1: no such package '@grpc//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/grpc/grpc/archive/v1.13.0.tar.gz, https://github.com/grpc/grpc/archive/v1.13.0.tar.gz] to /home/lyq/.cache/bazel/_bazel_root/aa56a649b479b5a19f4ce65a6e36da7d/external/grpc/v1.13.0.tar.gz: Checksum was 8ed4a3a6eeed153cc54921c8f3aebb9a5fe2a9d9923b5bbbce7e2989c42f2039 but wanted 50db9cf2221354485eb7c3bd55a4c27190caef7048a2a1a15fbe60a498f98b44 and referenced by '//tensorflow:grpc++'
ERROR: Analysis of target '//tensorflow/tools/quantization:quantize_graph' failed; build aborted: Analysis failed
INFO: Elapsed time: 775.107s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by sxsxsx** [comment] 2018-07-27 01:41
This is my negligence, I am sorry for that
OS :  ubauntu 16.04 64bit
TensorFlow installed from :  pip install tensorflow
TensorFlow version :  1.9.0
NO CUDA/cuDNN
use only CPU

my device is rk3288

**Comment by gunan** [comment] 2018-07-29 21:34
Looks like your connection was interrupted when downloading one of tensorflow's dependencies:
```
Error downloading [https://mirror.bazel.build/github.com/grpc/grpc/archive/v1.13.0.tar.gz, https://github.com/grpc/grpc/archive/v1.13.0.tar.gz] to /home/lyq/.cache/bazel/_bazel_root/aa56a649b479b5a19f4ce65a6e36da7d/external/grpc/v1.13.0.tar.gz: Checksum was 8ed4a3a6eeed153cc54921c8f3aebb9a5fe2a9d9923b5bbbce7e2989c42f2039 but wanted 50db9cf2221354485eb7c3bd55a4c27190caef7048a2a1a15fbe60a498f98b44 and referenced by '//tensorflow:grpc++'
```
Did you retry? Can you access the URLs listed?

**Comment by sxsxsx** [comment] 2018-07-31 07:29
Yes, I have tried many times,  but all failed,  maybe it's a network problem,  I am in China now...

**Comment by gunan** [comment] 2018-07-31 17:14
Then it is indeed a network problem. mirror.bazel.build is hosted on GCS, which I think is blocked in china.
github should be accessible, but maybe sometimes it is not.

**Comment by reedwm** [comment] 2018-08-08 17:33
Closing since this is caused by a network issue

**Closed by reedwm** 2018-08-08 17:33 UTC

**Comment by peterpanw** [comment] 2023-11-20 13:08
Have you finally resolved this issue？
