### ISSUE TITLE
Error during testing of Object Detection API

### ISSUE THREAD

**Issue by Abhit05** [tensorflow/tensorflow#27582] opened 2019-04-06 19:00 UTC
**System information**
- OS Platform and Distribution :Windows 10
- TensorFlow installed from (source or binary):cmd
- TensorFlow version:1.13.1
- Python version:3.7
- Installed using virtualenv? pip? conda?:pip
- CUDA/cuDNN version: don't know
- GPU model and memory: 1.13.1

**Describe the problem**

python object_detection/builders/model_builder_test.py

**Any other info / logs**
Traceback (most recent call last):
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Abhitm\mawa\abc\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Abhitm\mawa\abc\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    import tensorflow as tf
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Abhitm\mawa\abc\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Abhitm\mawa\abc\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Abhitm\mawa\abc\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by amanp592** [comment] 2019-04-06 21:04
@Abhit05 i once faced this issue and mine was due to the wrong version of CUDNN. For a better help can you tell me the version of CUDA and CUDNN you're using??

**Comment by achandraa** [comment] 2019-04-08 12:59
In order to expedite the trouble-shooting process, please provide a code snippet/steps to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-04-15 08:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-15 08:09 UTC
Labels: comp:model, stat:awaiting response, type:support
