### ISSUE TITLE
how to assign a different gpu to each session in a process .

### ISSUE THREAD

**Issue by liupengkd** [tensorflow/tensorflow#34030] opened 2019-11-06 05:05 UTC
tensorflow c API：I want to create multiple sessions for different models in a process, how to assign a different gpu to each session.

**Comment by nikochiko** [comment] 2019-11-06 05:34
Wrap your sessions in `with` commands like this:
```
with tf.device('/GPU:0'):
    .... (code for GPU:0) ....

with tf.device('/GPU:1'):
    .... (code for GPU:1) ....
```

**Comment by ravikyram** [comment] 2019-11-07 05:59
@liupengkd 

Looks like this issue is duplicate of # 33996 ?. Please, confirm.Thanks!

**Comment by developer22-university** [comment] 2019-11-07 06:15
@liupengkd

@ravikyram 
i have solved please check my file

**Comment by ravikyram** [comment] 2019-11-11 11:50
@liupengkd 

Please, let me know if we can close this issue since it looks to be fixed. Thanks!

**Closed** 2019-11-18 18:59 UTC
Labels: comp:runtime, type:support
