### ISSUE TITLE
S3 reads eventually fail with tensorflow's dataset API

### ISSUE THREAD

**Issue by thunterdb** [tensorflow/tensorflow#15190] opened 2017-12-07 19:07 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.3 LTS
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CPU
- **GPU model and memory**: N/A
- **Exact command to reproduce**: https://gist.github.com/thunterdb/d5f86c79457eea0f1021117ea4bce0ba

### Describe the problem
The given script reads the MNIST data from S3 repeatedly from a public bucket, on an EC2 machine in the same region as the S3 bucket.

Running this script eventually leads to python crashing after a few hours, and the following error:

```
Finished step 31890, time: 05:45:28 12/07/17, result: 32
Finished step 31920, time: 05:46:01 12/07/17, result: 32
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted
```

### Source code / logs
https://gist.github.com/thunterdb/d5f86c79457eea0f1021117ea4bce0ba

It is hard to say what is happening without debugging symbols. From the very generic error, I suspect this is an issue with the S3 SDK. As a workaround, it would be nice for tensorflow's S3 plugin to retry or be more resilient to networking issues.

It is currently an annoying issue when running large distributed training jobs, because they crash after a few hours of reading data. Is anyone having a similar experience with S3?

**Comment by thunterdb** [comment] 2017-12-07 19:10
cc @smurching

**Comment by mrry** [comment] 2017-12-07 19:11
I suspect the problem is this line:

```python
                  res = sess.run(iterator.get_next())
```

`iterator.get_next()` creates a new op each time it's called, and this op happens to be an especially heavyweight one that owns a thread, so calling it in a loop will eventually cause a resource leak. The fix is  simple, and we'll shortly start printing a warning message to advise users to do it when we detect this situation:

```python
      # ...
      next_element = iterator.get_next()
      with tf.Session() as sess:
            sess.run(iterator.initializer)
            for i in xrange(num_steps):
                  res = sess.run(next_element)
                  # ...
```

**Comment by thunterdb** [comment] 2017-12-07 19:17
@mrry thanks for the response, I am going to give it a try and get back to you.

**Comment by thunterdb** [comment] 2017-12-07 19:27
By the way, one suggestion I would have for the documentation of `get_next` is emphasize that calling the resulting op repeatedly is going to return sequential batches of data. From the documentation at [1] and from most iterator interfaces (java, c++), the convention assumes that you would have to call `get_next` to fetch a new batch.

[1] https://www.tensorflow.org/versions/master/api_docs/python/tf/data/Iterator#get_next

**Comment by thunterdb** [comment] 2017-12-08 23:18
@mrry I updated the gist following your suggestion. It failed after ~ 10M reads on S3 (a few hours) with the following stack trace.

Has anyone else encountered this issue before? Our current workaround is to copy the data locally to the machines' drives before starting the training, but this adds some complexity.

```
  File "/databricks/python2/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop
    self.interact(display_banner=display_banner)
  File "/databricks/python2/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 567, in interact
    self.run_cell(source_raw, store_history=True)
  File "/databricks/python2/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2741, in run_cell
    interactivity=interactivity, compiler=compiler)
  File "/databricks/python2/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes
    if self.run_code(code):
  File "/databricks/python2/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-201cc217ea8a>", line 1, in <module>
    test_s3_read_singlemachine(worker_index=0, num_workers=2, data_dir=data_dir, num_readers=2, shuffle_buffer_size=32, batch_size=32, num_prefetch_batches=1, num_steps=int(1e7))
  File "<ipython-input-7-58d40f4ce8d4>", line 15, in test_s3_read_singlemachine
    it_op = iterator.get_next()
  File "/databricks/python2/local/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 259, in get_next
    name=name))
  File "/databricks/python2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 706, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/databricks/python2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/databricks/python2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/databricks/python2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): truncated record at 785862
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
```

**Comment by mrry** [comment] 2017-12-08 23:25
I believe the S3 filesystem was contributed by @yongtang... hopefully he will have some suggestions!

**Comment by yongtang** [comment] 2017-12-11 15:26
I tried the script and it is still running
```
Finished step 1764750, time: 15:23:37 12/11/17, result: 32
Finished step 1764780, time: 15:23:38 12/11/17, result: 32
Finished step 1764810, time: 15:23:39 12/11/17, result: 32
Finished step 1764840, time: 15:23:40 12/11/17, result: 32
Finished step 1764870, time: 15:23:42 12/11/17, result: 32
Finished step 1764900, time: 15:23:43 12/11/17, result: 32
Finished step 1764930, time: 15:23:44 12/11/17, result: 32
Finished step 1764960, time: 15:23:46 12/11/17, result: 32
Finished step 1764990, time: 15:23:46 12/11/17, result: 32
```

Probably it is not long enough. Will see if I could reproduce it.

**Comment by drpngx** [comment] 2017-12-12 00:34
Note that S3 can fail every so often. I am not sure if we have retry logic.

**Comment by yongtang** [comment] 2017-12-12 15:53
My test is still running and I haven't been able to reproduce yet:
```
Finished step 3888180, time: 15:52:12 12/12/17, result: 32
Finished step 3888210, time: 15:52:14 12/12/17, result: 32
Finished step 3888240, time: 15:52:14 12/12/17, result: 32
```

**Comment by yongtang** [comment] 2017-12-12 15:55
I think adding retry logic to S3 support would be great.

I can't commit to have it done in the short term but will give it a try at some point once I have some spare time.

In the meantime, if anyone is interested in working on retry logic for S3 that would be excellent as well.

**Comment by quaeler** [comment] 2017-12-13 00:47
Something is slightly fishy here - the AWS SDK has retry logic baked in to it which `Aws::S3::S3Client` should pick up.

`Aws::Client::ClientConfiguration` has [a default value for `retryStrategy`](https://sdk.amazonaws.com/cpp/api/LATEST/struct_aws_1_1_client_1_1_client_configuration.html#a48715e0c06bcf958694d1223657b51c7) which provides [a max retry count of 10](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_client_1_1_default_retry_strategy.html) and we don't appear to doing anything that would change that default value in [`s3_filesystem.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L40)

**Comment by yongtang** [comment] 2017-12-13 01:17
By the way my test on the script has been running for more than a day and it is still OK:
```
Finished step 4701000, time: 01:16:31 12/13/17, result: 32
Finished step 4701030, time: 01:16:33 12/13/17, result: 32
Finished step 4701060, time: 01:16:33 12/13/17, result: 32
```

**Comment by andydavis1** [comment] 2017-12-13 01:32
Closing this out is it looks as though we have not been able to reproduce it on our end.

**Closed by andydavis1** 2017-12-13 01:32 UTC

**Comment by thunterdb** [comment] 2017-12-13 02:18
Interesting. I will try to reproduce it with more information, and reopen the ticket if something occurs again.

**Comment by rahul003** [comment] 2019-02-20 00:29
thunterdb@, sorry for being a blast from the past. Did you not see this issue later? I believe I'm seeing something similar on my end. I am curious if there was anything you had to do to get around it.

**Comment by mark-saad** [comment] 2019-03-08 18:35
@yongtang We're running into the same issue. Is there a workaround or are we missing a config param somewhere?
