### ISSUE TITLE
Failed to allocate tensors : Xcode 10 

### ISSUE THREAD

**Issue by michael-stram** [tensorflow/tensorflow#23890] opened 2018-11-20 19:15 UTC
**System information**
- OS Platform and Distribution:  macOS Mojave 10.14.2 Beta
- Mobile device : iPhone 8P / IPhone XR
- TensorFlow installed from (source or binary):  SOURCE
- TensorFlow version:  Newest 
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Unknown
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Xcode Crashed when I import my models into the TF-Lite example project. I don't know what to do or try to get he models to work.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Import the TFlite and txt files 
2. copy the path if needle ( Xcode asks this )
3. rename model_file_name to imported tflite model
4. rename label_file_name to imported txt file

**Any other info / logs**
 Loaded model 1resolved reportertensorflow/contrib/lite/kernels/squeeze.cc:64 current >= 0 && current < input_num_dims && input_dims->data[current] == 1 was not true.
Node 66 failed to prepare.

Failed to allocate tensors!2018-11-20 13:08:26.664470-0600 tflite_camera_example[9610:2085000] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-11-20 13:08:26.664721-0600 tflite_camera_example[9610:2085000] [MC] Reading from public effective user settings.
(lldb)

**Comment by michael-stram** [comment] 2018-11-20 23:56
I am still lost on what the error exactly means? The TFLite models were given to me to get in the demo iOS app. but that's it.

**Comment by aselle** [comment] 2018-11-27 20:37
What models are you using can you provde links? It sounds like the conversion didn't work properly. Did the person that gave them you test them with the tflite interpreter? You can dump a graphviz representation of the model using TocoConvert if you have the original savedmodel or .pb tensorflow model.

**Comment by karimnosseir** [comment] 2019-02-08 00:39
Closing the bug since it has been few months waiting on reply. @michael-stram please feel free to open new one or reopen this one if the problem is still happening with the details in @aselle  reply above.

Thanks

**Closed by karimnosseir** 2019-02-08 00:39 UTC
Labels: comp:lite
