### ISSUE TITLE
Cannot convert a Tensorflow GraphDef model to tflite format

### ISSUE THREAD

**Issue by osheenn** [tensorflow/tensorflow#31161] opened 2019-07-30 10:55 UTC
<h1> Description </h1>

I have been trying to convert a custom fastai based model to tflite and tf-js for deployment purpose. I was able to convert my fastai based model to onnx format and then to tensorflow format. I was able to perform inference on tensorflow model. However, when i try to convert the same model to tflte and tf-js i get error using the tflite converter API.
I get multiple errors in sequence.
1. the converter always searches for saved_model.pb | saved_model.pbtxt file only
![image](https://user-images.githubusercontent.com/16400126/62123641-fe95dd00-b2e5-11e9-9d12-dacc246024bc.png)
1. This error is solved by saving the pb file by name of saved_model.pb However, i face the next error after this which is something related to not finding right tags in metagraph.
![image](https://user-images.githubusercontent.com/16400126/62123741-37ce4d00-b2e6-11e9-82ed-2e1744dfe88d.png)

I am not able to resolve this issue, I have tried to create a session and add variables an tags to my graph but to no success. 
![image](https://user-images.githubusercontent.com/16400126/62123900-90054f00-b2e6-11e9-9e56-ed4dd69f8070.png)

Please help with this.

**Comment by anush-o** [comment] 2019-07-31 05:07
@osheenn ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by anush-o** [comment] 2019-08-07 07:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by anush-o** 2019-08-07 07:06 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by osheenn** [comment] 2019-08-20 03:58
@oanush sorry for the delay, i am using windows 10, the tensorflow version is 1.13.1. I have converted a pytorch model to tensorflow using onnx but now i cant convert it into tf-js.
Let me know what details you are looking for.
