### ISSUE TITLE
Tensorflow 2.0 (GPU) throws CancelledErrors while fitting models 

### ISSUE THREAD

**Issue by darthbhyrava** [tensorflow/tensorflow#35523] opened 2020-01-01 12:58 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **r2.0**
- Python version: **3.6.9**
- Bazel version (if compiling from source): **0.26.0**
- GCC/Compiler version (if compiling from source): **7.4.0**
- CUDA/cuDNN version: **v10.1**
- GPU model and memory: **GeForce RTX 2070 Super (8GB)**

**Describe the current behavior**
The script throws a `CancelledError` when fitting the model (very 1st epoch)

**Describe the expected behavior**
`$ model.fit( ... )` is executed without throwing any errors.

**Code to reproduce the issue**
```
model = Sequential()
model.add(Embedding(vocab_size, dimensions,weights=[embedding_matrix], input_length=pad2, trainable=True))
model.add(GRU(128, return_sequences=True))
model.add(MaxPooling1D())
model.add(AveragePooling1D())
model.add(GRU(128))
model.add(Dense(len(set(outputs)), activation='sigmoid'))
checkpoint = ModelCheckpoint('model-%s-%s-%s-%s' %(setting, indicators, case, str(window_size)), verbose=1, monitor='val_acc', save_best_only=True, mode='auto')
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print(model.summary())
# The summary is as expected
train, dev = padded_docs[:split], padded_docs[split:]
y_train, y_dev = y[:split], y[split:]
model.fit(train, y_train, epochs=epochs, verbose=1, callbacks=[checkpoint], batch_size=batch_size, validation_data=(dev, y_dev))
# This is where the script fails
```

**Other info / logs**
```
CancelledError                            Traceback (most recent call last)
<ipython-input-18-ba796bf236a0> in <module>
     70         train, dev = padded_docs[:split], padded_docs[split:]
     71         y_train, y_dev = y[:split], y[split:]
---> 72         model.fit(train, y_train, epochs=epochs, verbose=1, callbacks=[checkpoint], batch_size=batch_size, validation_data=(dev, y_dev))
     73         pred = model.predict(dev, batch_size=batch_size)
     74         model.save('./cross-fold-models/model-%s-%s-%s-%s-%s' %(setting, indicators, case, str(window_size), str(number)))

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    518         # Lifting succeeded, so variables are initialized and we can run the
    519         # stateless function.
--> 520         return self._stateless_fn(*args, **kwds)
    521     else:
    522       canon_args, canon_kwds = \

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   1821     """Calls a graph function specialized to the inputs."""
   1822     graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 1823     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   1824 
   1825   @property

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in _filtered_call(self, args, kwargs)
   1139          if isinstance(t, (ops.Tensor,
   1140                            resource_variable_ops.BaseResourceVariable))),
-> 1141         self.captured_inputs)
   1142 
   1143   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_45}}]]
	 [[Reshape_14/_42]] [Op:__inference_distributed_function_18141]

Function call stack:
distributed_function
```

**Comment by darthbhyrava** [comment] 2020-01-01 13:04
I see that this error has been raised before: 
- [33721](https://github.com/tensorflow/tensorflow/issues/33721): Downgrading TF to 1.14 'solved' the issue. I cannot downgrade TF from 2.0
- [33200](https://github.com/tensorflow/tensorflow/issues/33200): Fixing `gast` did **not** solve the issue.
- [SO Question](https://stackoverflow.com/questions/58359153/cancellederror-derived-recvasync-is-cancelled): My CUDA version isn't an issue.

**Comment by realSaddy** [comment] 2020-01-02 04:18
I am having the same issue.

**Comment by ravikyram** [comment] 2020-01-02 05:59
@darthbhyrava 

Looks like code is incomplete. Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-16 12:39
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-01-17 03:58
@darthbhyrava 
Any update on this issue please. Thanks!

**Comment by realSaddy** [comment] 2020-01-17 04:04
Not OP, but I am not longer receiving this issue

**Comment by darthbhyrava** [comment] 2020-01-18 07:05
> @darthbhyrava
> 
> Looks like code is incomplete. Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

Thanks for the response, apologies for the delay in replying. 

I cannot provide supporting files or the entire code, they're proprietary in nature. However I can provide details for the parameters in the embedding layer, and the nature of the data set with simple examples:

```
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# vocab_size
t = Tokenizer(split=" ",lower=True, filters='@')
t.fit_on_texts(X)
vocab_size = len(t.word_index) + 1

# dimensions
dimensions = 300

# embedding_matrix
embedding_matrix = np.zeros((vocab_size, dimensions))
# zeros replaced with GloVe embeddings, shape remains same

# pad2 and padded_docs
encoded_docs = t.texts_to_sequences(X)
max_len = []
for each in encoded_docs:
	max_len.append(len(each))
pad2 = max(max_len)
padded_docs = pad_sequences(encoded_docs, maxlen=pad2, padding='post')

# outputs
Number of labels for classification

# y
Corresponding labels for the input sequences
```
Please let me know if additional info is needed.

Also, my workaround was to eventually downgrade tensorflow (to r1.15) and CUDA (to 10.0).

**Comment by jvishnuvardhan** [comment] 2020-01-21 21:10
@darthbhyrava As mentioned in the other [post](https://github.com/keras-team/keras/issues/12379#issuecomment-471339468), did you import modules from `tensorflow.keras.**any_sub_module`? If the issue was cleared by using tensorflow.keras.* then please close the issue. 

If the issue is with keras module (if you are using `keras.**any_module`) , then please post it in the [`keras repository here](https://github.com/keras-team/keras/issues). If the issue persists even after importing modules from tensorflow.keras.**, then please use a public data to create a standalone code to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-02-06 18:46
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2020-02-06 18:48 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:bug

**Comment by stefan-falk** [comment] 2020-11-18 15:07
Maybe my comment can help you: https://github.com/tensorflow/tensorflow/issues/33721#issuecomment-729738471
