### ISSUE TITLE
Default build options creating larger(~3x) binary in linux 

### ISSUE THREAD

**Issue by AnupAka** [tensorflow/tensorflow#29644] opened 2019-06-11 14:56 UTC
**System information**
- OS Platform and Distribution : ubuntu 16.04.10
- TensorFlow installed from (source or binary): Not Installing. Building Binary
- TensorFlow version: 1.13.1 and 1.14-rc0
- Python version: 3.5
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 4.9
- CUDA/cuDNN version: NA. Not building with CUDA
- GPU model and memory: NA

**Describe the problem**

The size of TF binary we are building has increased from 54.3 MB(in TF 1.8) to 148.1 MB (int TF 1.14-rc0 and 1.13.1). 

We have used all default settings in configure.py in 1.8. Building 1.14-rc0 with defaults is anyways giving a larger binary. Additionally we tried to disable many optional dependencies (like aws,kafka etc), but still the size was around 148 MB. 

Is there any new optional dependency added by default after 1.8 ? 

**Steps Followed**

We are building with default settings (except we say NO to XLA JIT support in 1.14.1-rc0 and 1.13.1). We are using following command to build : 

1) bazel build --config=opt //tensorflow:tensorflow
2) bazel build --config=opt --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=nonccl  //tensorflow:tensorflow

**Comment by gunan** [comment] 2019-06-20 00:42
@yifeif

**Comment by yifeif** [comment] 2019-06-20 01:06
Doesn't seem related to dynamic loading of cuda libraries, but I can take a closer look.

**Comment by testerGit100** [comment] 2019-06-21 10:26
> Doesn't seem related to dynamic loading of cuda libraries, but I can take a closer look.

Thanks for looking into this! I will be really helpful if you provide us a solution. 

I thought I will provide some information in the context of CUDA. During configuration step, we get a specific option to enable/disable CUDA support. And we select "NO" for CUDA support. 

Is there any new optional dependency added by default after 1.8 ? I ask this question because TF 1.8 binaries had lesser size (as mentioned in the issue information above)

**Comment by gunan** [comment] 2019-11-20 00:17
Looks like the majority of the size increase came in v 14.
But there were two 10 MB increases before.

I cannot promnise a fix to this, but the best I can do is to maybe find an explanation for this increase.

**Comment by gunan** [comment] 2019-11-20 00:24
From what I can see, there are 30 MBs of additional python files due to "tf.compat" module, 15 MB size increase in libtensorflow_framework, which may be explained by starting to use MKL-DNN for contraction kernels, 8 MB increase in XLA, another 9 MB in contrib, and a few megabytes of new headers. I think due to the preparation to 2.0, we did a lot of things, which accumulated.

I do not think we can make it as small as 1.8, unfortunately. Closing this issue as working as intended.

**Closed by gunan** 2019-11-20 00:24 UTC
Labels: subtype:bazel, type:build/install
