### ISSUE TITLE
could not create a primitive descriptor iterator, in file tensorflow/core/kernels/mkl_relu_op.cc:871

### ISSUE THREAD

**Issue by alexmil2019** [tensorflow/tensorflow#29011] opened 2019-05-24 22:32 UTC
I am using tensorflow 1.13.1 on mac os sierra.
when I try to use tf.contrib.predictor.from_saved_model to do prediction on a trained model I get this error:

could not create a primitive descriptor iterator, in file tensorflow/core/kernels/mkl_relu_op.cc:871

**Comment by gadagashwini** [comment] 2019-05-27 05:53
@alexmil2019 In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by alexmil2019** [comment] 2019-05-27 17:59
def _get_predictor(export_dir):
    """Get predictor
    """
    return tf.contrib.predictor.from_saved_model(export_dir=export_dir)

def predict(export_dir, data_dir):
    # let's create a predictor
    predictor = _get_predictor(export_dir)
    feed_tensor = list(predictor.feed_tensors.keys())[0]
    fetch_tensor = list(predictor.fetch_tensors.keys())[0]

    feats = _compute_features(data_dir) # a generator to compute features
    for feat in feats:
        Y = predictor({feed_tensor: feat[:]})
        r = Y[fetch_tensor]

**Comment by gadagashwini** [comment] 2019-05-28 09:14
@alexmil2019 Code snippet looks incomplete to reproduce the issue. Please provide code to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-06-04 06:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-04 06:45 UTC
Labels: TF 1.13, comp:mkl, contrib, stat:awaiting response

**Comment by deadsoul44** [comment] 2019-06-09 06:28
I have the same problem:

AbortedError: Operation received an exception:Status: 5, message: could not create a primitive descriptor iterator, in file tensorflow/core/kernels/mkl_relu_op.cc:871
	 [[{{node activation_1/Relu}}]]

It is a keras and hyperas script. Hard to provide a code snippet to reproduce the error.

**Comment by alexmil2019** [comment] 2019-06-09 07:17
it seems the problem is with multi gpu model. I created a model, I trained it with single gpu and it works but when I train it with multiple gpu, it gives this error. the codes are exactly the same. tf.keras, Estimator API, and tf.contrib.predictor.from_saved_model have issues with multi gpu training.

**Comment by deadsoul44** [comment] 2019-06-09 09:27
It may not be due to gpu because I got this error with cpu.

**Comment by kumarmanas** [comment] 2019-12-18 09:45
> It may not be due to gpu because I got this error with cpu.

Hey have you got solution for this. I am facing same problem on my CPU.

**Comment by deadsoul44** [comment] 2019-12-18 10:00
> > It may not be due to gpu because I got this error with cpu.
> 
> Hey have you got solution for this. I am facing same problem on my CPU.

I don't remember exactly how I solved this. Maybe installing mkl package or something like that or updating keras. It might be also due to using generator. Currently, I am not using generator. I am using tf 2.0 in a conda env and importing keras from tf like from tensorflow.keras import etcetc.

**Comment by JohanHaggmark** [comment] 2020-02-19 13:32
I was getting this error when defining the layers to the same variable:
```
l0 = layers.Conv2D(2, (3,3), strides=2, activation='relu', padding='same', name='conv_1')(input_layer)
l1 = layers.Conv2D(2, (5,5), strides=2, activation='relu', padding='same', name='conv_2')(input_layer)
l =  layers.concatenate([l0,l1])
l = layers.Conv2D(8,(1,1), strides=1, activation='relu', padding='same', name='conv_3')(l)
```

The solution for me was to defining new variables for new layers:
```
l0 = layers.Conv2D(2, (3,3), strides=2, activation='relu', padding='same', name='conv_1')(input_layer)
l1 = layers.Conv2D(2, (5,5), strides=2, activation='relu', padding='same', name='conv_2')(input_layer)
lc1 =  layers.concatenate([l0,l1])
l2 = layers.Conv2D(8,(1,1), strides=1, activation='relu', padding='same', name='conv_3')(lc1)
```
