### ISSUE TITLE
tf.image.random_jpeg_quality only products images of single jpeg quality

### ISSUE THREAD

**Issue by serycjon** [tensorflow/tensorflow#25882] opened 2019-02-19 09:14 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09
- Python version: 2.7.13
- CUDA/cuDNN version: 9.0 / 7.0.3
- GPU model and memory: GeForce GTX 1080 Ti, 10405 MB

**Describe the current behavior**
tf.image.random_jpeg_quality generates random jpeg quality on graph creation, which is then fixed.

**Describe the expected behavior**
tf.image.random_jpeg_quality generates random jpeg quality for each image/batch of images passed through it.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf

img = np.random.randint(0, 256, (100, 200, 3), dtype=np.uint8)

tf_img = tf.placeholder(tf.uint8)
jpeg_augment = tf.image.random_jpeg_quality(tf_img,
                                            min_jpeg_quality=20,
                                            max_jpeg_quality=90)

sess_config = tf.ConfigProto()
sess_config.gpu_options.allow_growth = True

with tf.Session(config=sess_config) as sess:
    sess.run(tf.global_variables_initializer())
    results = []
    for i in range(25):
        augmented = sess.run([jpeg_augment], feed_dict={tf_img: img})[0]
        results.append(augmented)

results = np.array(results)
same_as_first = results == results[0, ...]
all_equal = np.all(same_as_first)
print('all_equal: {}'.format(all_equal))
assert not all_equal
```

The code causing this is located at:
https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/ops/image_ops_impl.py#L1634

**Comment by facaiy** [comment] 2019-02-22 12:46
@drpngx Can you answer the issue or reassign?

**Comment by serycjon** [comment] 2019-02-22 12:57
I think this is more of a "type:bug" than "type:feature"

**Comment by frreiss** [comment] 2019-03-15 21:15
The root cause of this problem is that the `EncodeJpeg` op's `quality` parameter is a fixed `Attr`, not a variable `Input`. Fixing `random_jpeg_quality` will necessitate a new version of `EncodeJpeg` with a different signature. @drpngx I'd be happy to put in a PR for this issue if that's ok.

**Comment by drpngx** [comment] 2019-03-18 17:25
Sounds like a good idea. @frreiss are you familiar with the op replacement process? You have to:

1. Create a new op, call it v2.
2. Check it in, with tests etc and wait for two weeks.
3. Replace the call from v1 to v2.

The v2 version should be a strict superset of v1. Ideally it should behave exactly like v1 with the default options.

**Comment by frreiss** [comment] 2019-03-19 17:14
@drpngx yes, I've done an op replacement in the past with the `accumulate_n` op.

I'll break this work down into a few smaller PRs to make the diff size more manageable:
1. Add a new C++ op, `EncodeJpegV2`, along with C++ regression tests.
2. Modify the `random_jpeg_quality` Python API to use `EncodeJpegV2` and also fix issue #25882.
3. Change the other Python code in `image_ops_impl.py` that uses `gen_image_ops.encode_jpeg` to use `gen_image_ops.encode_jpeg_v2`. 

Regarding the first step: I see that `EncodeJpeg` has a number of other arguments that are currently static attributes:
```c++
REGISTER_OP("EncodeJpeg")
    .Input("image: uint8")
    .Attr("format: {'', 'grayscale', 'rgb'} = ''")
    .Attr("quality: int = 95")
    .Attr("progressive: bool = false")
    .Attr("optimize_size: bool = false")
    .Attr("chroma_downsampling: bool = true")
    .Attr("density_unit: {'in', 'cm'} = 'in'")
    .Attr("x_density: int = 300")
    .Attr("y_density: int = 300")
    .Attr("xmp_metadata: string = ''")
    .Output("contents: string")

```
Do you have any preference about which arguments I should turn into 0-D tensors in the new op?

**Comment by drpngx** [comment] 2019-03-20 00:17
I will let the API reviewer comment. My general intuition is that numbers can be changed, and everything else, in the worst case put in the graph. So `quality`, `{x,y}_density` would be input tensors.

**Comment by karmel** [comment] 2019-03-20 20:28
(For API owners) This might be more appropriate for the [TensorFlow Addons](https://github.com/tensorflow/addons) repository, which has a number of special use ops like this. In either case, in the op registration code above, the Attrs should be Inputs. (Inputs are more flexible.)

**Comment by frreiss** [comment] 2019-04-02 01:35
I was about to start work on this, but it looks like an anonymous Googler has already committed a patch. Someone should close this issue.

**Closed** 2019-04-25 20:16 UTC
Labels: stat:contributions welcome, type:bug/performance
