### ISSUE TITLE
ImportError: No module named nets, r0.12

### ISSUE THREAD

**Issue by codeloverr** [tensorflow/tensorflow#6211] opened 2016-12-09 12:02 UTC
I am trying to run `resnet_v2.py`  from provided modles but getting error `ImportError: No module named nets
`.
I have done following 
First installing slim
`cd $HOME/tensorflow
git clone https://github.com/tensorflow/models/`

To verify that this has worked, execute the following commands; it should run
without raising any errors.

```
`cd $HOME/tensorflow/models/slim
python3 -c "from nets import cifarnet; mynet = cifarnet.cifarnet"`
```
I got no error.

But when I run following gives error **"ImportError: No module named nets"**. I have also tried
`cd $HOME/tensorflow/models/slim/
python3 -c "from nets import resnet_utils"`

Got not error.  Also build  using `bazel build nets` output 
`INFO: Found 1 target...
Target //slim:nets up-to-date (nothing to build)
INFO: Elapsed time: 0.096s, Critical Path: 0.00s
`

I don't know why this is not working.

**Comment by michaelisard** [comment] 2016-12-09 17:38
Closing as duplicate of [tensorflow/models #729](https://github.com/tensorflow/models/issues/729)

**Closed by michaelisard** 2016-12-09 17:38 UTC
