### ISSUE TITLE
Cannot build TensorFlow Lite iOS framework for benchmark tool due to '@XNNPACK//:neonv8_ukernels' rule compilation failure

### ISSUE THREAD

**Issue by user-vm** [tensorflow/tensorflow#40026] opened 2020-05-31 13:41 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): source
- TensorFlow version: master (edbe5e189c1ec14d3a3386aa29e6118d807d9379)
- Python version: 3.7.7 (also fails in the same way with 2.7.16)
- Installed using virtualenv? pip? conda?: not installed
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.17)
- CUDA/cuDNN version: none
- GPU model and memory: AMD Radeon R9 M370X 2 GB

**Describe the problem**
Building the benchmark framework for the TFLite iOS benchmark app (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/ios) fails with 'C++ compilation of rule '@XNNPACK//:neonv8_ukernels' failed'. XNNPack has been upgraded in April to fix an AArch64 compilation issue (#38400 #38436), perhaps this is the cause?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`./tensorflow/lite/tools/benchmark/ios/build_benchmark_framework.sh`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
$ ./configure 

You have bazel 3.0.0 installed.
Please specify the location of python. [Default is /usr/local/opt/python/bin/python3.7]: 


Found possible Python library paths:
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: 
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: 
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: y
iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

$ ./tensorflow/lite/tools/benchmark/ios/build_benchmark_framework.sh

++ bazel info workspace
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'info' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'info' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'info' from /Users/valentinmiu/2019/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/usr/local/opt/python/bin/python3.7 --action_env PYTHON_LIB_PATH=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/usr/local/opt/python/bin/python3.7 --config=xla --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:macos in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
+ WORKSPACE_ROOT=/Users/valentinmiu/2019/tensorflow
+ BENCHMARK_DIR=tensorflow/lite/tools/benchmark
+ DEST_DIR=tensorflow/lite/tools/benchmark/ios/TFLiteBenchmark/TFLiteBenchmark/Frameworks
+ FRAMEWORK_TARGET=TensorFlowLiteBenchmarkC_framework
+ PROFILING_ARGS=
+ getopts p opt_name
+ shift 0
+ pushd /Users/valentinmiu/2019/tensorflow
~/2019/tensorflow ~/2019/tensorflow
+ bazel build --config=ios_fat -c opt //tensorflow/lite/tools/benchmark/experimental/ios:TensorFlowLiteBenchmarkC_framework
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=272
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/opt/python/bin/python3.7 --action_env PYTHON_LIB_PATH=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/usr/local/opt/python/bin/python3.7 --config=xla --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:ios_fat in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --config=ios --ios_multi_cpus=armv7,arm64,i386,x86_64
INFO: Found applicable config definition build:ios in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/lite/tools/benchmark/experimental/ios:TensorFlowLiteBenchmarkC_framework (115 packages loaded, 9402 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_valentinmiu/94cd6c8db58787268db4435bda1fd58c/external/XNNPACK/BUILD.bazel:2048:1: C++ compilation of rule '@XNNPACK//:neonv8_ukernels' failed (Exit 1)
external/XNNPACK/src/math/roundne-neonv8.c:24:23: error: initializing 'const float32x4_t' (vector of 4 'float32_t' values) with an expression of incompatible type 'int'
    const float32x4_t vy = vrndnq_f32(vx);
                      ^    ~~~~~~~~~~~~~~
1 error generated.
Target //tensorflow/lite/tools/benchmark/experimental/ios:TensorFlowLiteBenchmarkC_framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1327.686s, Critical Path: 96.87s
INFO: 5060 processes: 5060 local.
FAILED: Build did NOT complete successfully```

**Comment by yyoon** [comment] 2020-06-08 04:24
@Maratyszcza I think this started to happen with a04c8be3e7086d9e14ba37c3c0945a3ea98414ce.

Could you please check what's going on? Looks like it's trying to use NEON v8 operator for armv7 target.

You could easily reproduce this with iOS armv7 build with the following command, after enabling iOS build with `./configure` script.

```sh
bazel build -c opt --config=ios_armv7 //tensorflow/lite/tools/benchmark/experimental/ios:TensorFlowLiteBenchmarkC_framework
```

**Comment by yyoon** [comment] 2020-06-10 23:43
This should be fixed in master branch now.

@user-vm Can you please try again after updating the repo, and close the issue if it's working for you? Thanks.

**Comment by yyoon** [comment] 2020-06-12 02:44
Since this issue is confirmed to be fixed by multiple people, let me close it now. Feel free to reopen if it doesn't work.

**Closed by yyoon** 2020-06-12 02:44 UTC
Labels: comp:lite, stat:awaiting response, subtype:macOS, type:build/install
