### ISSUE TITLE
Support for half-floats (float16/fp16)

### ISSUE THREAD

**Issue by sesse** [tensorflow/tensorflow#1300] opened 2016-02-26 15:07 UTC
This is a tracking bug for adding support for the half type (aka float16, or fp16) in TensorFlow. Half computation is supported by GPUs only, although newer Intel CPUs (Haswell and newer) have support for converting back and forth between fp16 and fp32 in hardware (F16C). CUDA has some support for half since 7.5, although it's a bit cumbersome (it's not a first-class type, but relies on macros containing asm statements; effectively intrinsics).

fp16 is interesting for two primary reasons: It would allow us to fit twice as large models in available GPU RAM, and it reduces memory bandwidth use, a precious resource on the GPU. The next generation of NVIDIA GPUs (Pascal) will also be able to do computation directly on two half-floats (in a SIMD-like structure) as fast as on a single float, although that would be somewhat more intrusive in code.

It is not 100% clear exactly how much of TensorFlow we need fp16 support for; interested parties are asked to comment. CuBLAS and CuDNN already has some support for half in their latest versions (so it would be natural to provide those interfaces), and Eigen also has beginning support.

**Comment by frankcarey** [comment] 2016-03-03 02:21
+1 for this.. other reasons include reducing data storage. (on disk only, since 64bit CPU arch still uses just as much RAM), which means the storage and reading to and from disk for large datasets is a lot faster.

**Comment by ffmpbgrnn** [comment] 2016-03-03 09:05
I currently save my input in the format of HDF5 with np.fp16, and then transform to fp32 before feeding to the network. It would be great to support fp16 ops.

**Comment by sesse** [comment] 2016-03-03 10:21
I'm currently working on this. There's a fair amount of work to do—the CUDA “half” type is just a struct of uint16_t, which doesn't really match what Eigen expects. In particular, Eigen expects all such arithmetic types to have operator overloads, converts to and from other arithmetic types (including even bool), etc. The actual arithmetic intrinsics require CUDA compute 5.3 (which right now means essentially Tegra X1 only), so mostly, we'll have to rely on casting on both sides and then doing the actual calculations in float.

Also, we're going to need conversions on the CPU because e.g. cuBLAS functions might require the alpha and beta to be in half, we often need a definition of zero, etc.. We don't need these to be fast, though; fp16 is generally not a win on CPU.

**Comment by sesse** [comment] 2016-03-09 15:36
An update here; the Eigen::half class (making half look roughly like any other arithmetic type) works. I've added half support to a bunch of ops (with the class in place, it's mostly only about adding the right template instantiations), including some a very few select cuDNN and cuBLAS operations. I can do training of a CNN example with most ops in float16 (I need to cast back to float32 for some operations, like maxpool and dropout, that don't have implementations yet), but if I have too many of them, training starts to go slower, I believe this has something to do with gradients, but it's hard to say without the tests.

Some operations that are about composing Eigen stuff probably would be faster (and more accurate) by just being a composition of cast to float32, the operation, and then cast back. We'll see about that later.

Overall I'm going to try to put things piecewise through code reviews, although it is going somewhat slowly, mostly due to boring fiddly issues about build environments.

**Comment by sesse** [comment] 2016-03-16 10:53
The half class is out in Eigen upstream (still some things to fix, though): https://bitbucket.org/eigen/eigen/commits/7aa6310352e789f118b28456ab14de4baf5720fa

Working on code review for the new type in TF core; after that, we'll see about getting some of the ops in.

**Comment by ffmpbgrnn** [comment] 2016-03-16 12:34
@sesse , that's fast. Great work!

**Comment by Froskekongen** [comment] 2016-03-22 11:50
Good stuff. How does float16 perform in training compared to, for instance, fixed point number representations with stochastic rounding? http://arxiv.org/abs/1502.02551

**Comment by sesse** [comment] 2016-03-23 11:04
Base commit in 9d03824d6740be0c043c431566c917ec0cf6cf3f. There's still a lot of work left to be done, of course—it's not very useful yet.

Froskekongen: I don't know of any detailed analysis of float16 versus fixed16; it's probably going to be dependent on a number of factors including your model and compilation flags. TensorFlow supports quantized models for inference, but as far as I know not training them.

**Comment by bhack** [comment] 2016-03-23 14:13
Also some interesting "VBR" approach is emerging http://arxiv.org/abs/1511.06393

**Comment by bhack** [comment] 2016-03-23 15:01
For who is interested in RAM consumption on more constrained contests I have also added https://github.com/tensorflow/tensorflow/issues/1592

**Comment by sesse** [comment] 2016-04-01 09:26
9b71f96ae83bbc7a7f8ce91d94e3c1de408ac07f contains support for half cast and const. Still working on (most of) the rest of the ops.

**Comment by sesse** [comment] 2016-04-18 09:38
31fd4868711f393bec74200231c2936bf3df079a contains fp16 support for all the componentwise ops, both unary (sqrt, sigmoid, etc.) and binary (add, sub, mul, …).

**Comment by sesse** [comment] 2016-04-25 09:29
36c0475865ec103b5a3c2de4a69b17eddf7a9903 and dbd35a75bfe2dc9c98858806c3b48602281d1a46 together enable fp16 optimizers, so now it should be possible to train simple pipelines in fp16, as long as they don't have convolutions or matrix multiplications in them. (Granted, those are pretty heavy restrictions, and we're working to have them lifted.)

**Comment by sesse** [comment] 2016-04-28 09:24
b8e73a5d5fb9f1dc4c654f163329a9e8ffb6bd76 fp16-enables the cross-entropy op. 4640ab5d3971bcc4f20951a211bd457cdfa56bc5 fp16-enables the random ops.

**Comment by sesse** [comment] 2016-05-02 09:33
63fd88065526c6301569743b1cec12fd2561589f enables inf/NaN debugging (if requested) for fp16, like you already can with fp32 and fp64.

**Comment by sesse** [comment] 2016-05-12 09:36
Some changes from @benoitsteiner: d526527a7f2bb3d29fed58b9f759f59e9a49c890 enables fp16 support for the tiling ops, 7ae67a14e273a000e5b306d335dc0f1d7c0650c1 enables fp16 support for the l2loss kernel.

**Comment by sesse** [comment] 2016-05-13 14:10
523055469c8a61425e3b8f104be67787c2933ccb adds support for fp16 GEMM (matrix multiplications) to StreamExecutor. 61b12f567ad167556bf55d4375112ed262d37975 does the same for convolution operations via cuDNN. (Both require CUDA 7.5.) Unfortunately there were some late changes to how convolutions are done in TensorFlow proper, so we'll need a followup commit for updating the cuDNN use.

Note that neither of these actually add support to the TensorFlow MatMul and Conv2D ops, but they're necessary building blocks for that.

**Comment by sesse** [comment] 2016-05-18 09:24
6350f17524f0f6f3761e84589846191a90fef061 does the required fixups to StreamExecutor.

**Comment by sesse** [comment] 2016-05-19 10:22
4d55cb5c55fcc85009171b6a4657cbd966fd85e5 adds fp16 support to the MatMul op (gated on CUDA 7.5 or higher). This is a major milestone for fp16 support; it means that many real graphs can probably be  trained and run in fp16.

Convolutions are missing still.

**Comment by kunal-bajpai** [comment] 2016-05-21 06:35
@sesse great job with adding all these operations! Any estimate on how long it might take to support convolutions?

**Comment by sesse** [comment] 2016-05-21 09:23
@kunal-bajpai: It will almost certainly happen next week.

**Comment by benoitsteiner** [comment] 2016-05-21 23:03
@kunal-bajpai I'm hoping to land a set of improvements necessary to make the convolution code work on fp16 ready in a couple of days. We should be able to support convolutions on fp16 shortly thereafter.

**Comment by sesse** [comment] 2016-05-25 09:42
Some image ops while we're waiting (I'm trying to make Inception train with fp16 end-to-end): 48b52d88a419d26beb9ee5cb3c19dba61c68cc3b makes SummarizeImageOp support fp16, c3465a857fcef34fcf2894e90af882f11007762e makes DrawBoundingBox support fp16 (although the bounding box is still fp32).

**Comment by kunal-bajpai** [comment] 2016-05-26 10:23
That sounds good @benoitsteiner. Looking forward to the commit. Please let me know when it happens. Thanks!

**Comment by benoitsteiner** [comment] 2016-05-27 04:07
https://github.com/tensorflow/tensorflow/commit/36357e7e1127873165694a38e3a989df4e0b6ffe adds support for fp16 to the batch normalization operations.

**Comment by sesse** [comment] 2016-05-27 20:52
99671f3a705789ef217c7bca92409add3cf529e5 fp16-enables ReverseOp. 6164d02144239c58a8f19cd12ff2a3ff7b7605d4 (by @benoitsteiner) fp16-enables AddN. bb0190f6c26bf11f601102dfe2166a68a7833020 (also by @benoitsteiner) fp16-enables the softmax ops. 80da0a63200cb7c9c449188620992c7a8d18c8b9 fp16-enables the resize ops, although you should note that some of them always output float no matter the input (this was preserving existing behavior, although I'm not sure it makes sense for half or double).

And… 4f257a2427ba0414bd7513c9b61fb835870bd3cf fp16-enables convolutions on GPU, assuming you have CUDA 7.5 or newer.

You still can't MaxPool/AvgPool, but that's up for next week. After that, I will declare this feature complete, since you can actually do useful stuff with it. There's always more performance to be had, though (currently it's pretty much performance-neutral on Maxwell, so it's mostly about the memory savings), more ops that need conversion and so on, but that should probably live outside this bug. And that work will be continued by Benoit alone, as I'm leaving Google and thus TensorFlow. :-)

**Comment by kunal-bajpai** [comment] 2016-06-02 07:09
@benoitsteiner does TensorFlow support ReLU half float yet?

**Comment by benoitsteiner** [comment] 2016-06-02 16:34
@kunal-bajpai Most if not all the coefficient-wise operations should work on half floats. I have checked that this is the case for ReLU.

**Comment by RyanCarey** [comment] 2016-06-06 17:31
Thanks for this - looking forward to MaxPool, (not yet present on last night's .whl).

**Comment by alexatknit** [comment] 2016-06-06 23:02
Also looking forward to seeing elu added.

**Comment by benoitsteiner** [comment] 2016-06-07 18:57
I have added support for pooling on fp16 in https://github.com/tensorflow/tensorflow/commit/b7c416926e4d31f7d7a924bfdc97580bf7d44c04. I have also added a --use_fp16 option the convolutional mnist model at tensorflow/models/image/mnist/convolutional.py to make it train using fp16 instead of fp32.

**Comment by kunal-bajpai** [comment] 2016-06-08 13:43
Great @benoitsteiner ! We can start working with this. 

Can you tell me if these operations are present in a 0.9rc or when you will be adding it to a stable version?

**Comment by benoitsteiner** [comment] 2016-06-08 16:06
I don't think the pooling operations made the 0.9 cut, but they'll be available in the release that comes after 0.9. In the meantime, you can always [install from source].(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources)

**Comment by kunal-bajpai** [comment] 2016-06-08 17:51
@benoitsteiner we will be building from source but were just looking for some clarity on when a stable release might include these operations. Any ETA for the next release?

**Comment by benoitsteiner** [comment] 2016-06-21 21:23
@rizar

**Comment by benoitsteiner** [comment] 2016-06-27 15:03
https://github.com/tensorflow/tensorflow/commit/bcb8f33b788bd02f1b6bdf813129d5668c6c4e5e introduces a new --use_fp16 option to train the cifar10 model using half floats instead of regular floats.

**Comment by alexatknit** [comment] 2016-07-07 01:03
It looks like fp16 is very slow:
```
Alexs-MacBook-Pro:~ alexatknit$ python3 tensorflow/tensorflow/models/image/cifar10/cifar10_train.py --use_fp16
>> Downloading cifar-10-binary.tar.gz 100.0%
Successfully downloaded cifar-10-binary.tar.gz 170052171 bytes.
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
2016-07-06 17:54:28.997546: step 0, loss = 2.54 (2.5 examples/sec; 50.208 sec/batch)
2016-07-06 18:01:15.998456: step 10, loss = 2.49 (3.7 examples/sec; 34.673 sec/batch)
...
```

vs fp32:
```
Alexs-MacBook-Pro:~ alexatknit$ python3 tensorflow/tensorflow/models/image/cifar10/cifar10_train.py
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
2016-07-06 18:02:25.860620: step 0, loss = 4.67 (18.9 examples/sec; 6.789 sec/batch)
2016-07-06 18:02:35.978002: step 10, loss = 4.63 (122.8 examples/sec; 1.042 sec/batch)
2016-07-06 18:02:44.049841: step 20, loss = 4.48 (150.6 examples/sec; 0.850 sec/batch)
...
```

**Comment by sbrodehl** [comment] 2016-07-13 17:13
Thanks for work done here!

I am not sure what hardware @alexatknit uses, but I can confirm the slow speed on a 1080 using CUDA 8 and cuDNN 5.0:
fp16
```
cifar10_train.py --use_fp16
2016-07-13 18:50:51.374002: step 0, loss = 4.66 (8.8 examples/sec; 14.572 sec/batch)
2016-07-13 18:51:00.050748: step 10, loss = 4.62 (173.7 examples/sec; 0.737 sec/batch)
2016-07-13 18:51:07.455344: step 20, loss = 4.47 (172.1 examples/sec; 0.744 sec/batch)
2016-07-13 18:51:14.891447: step 30, loss = 4.52 (172.7 examples/sec; 0.741 sec/batch)
```

vs. fp32
```
cifar10_train.py
2016-07-13 18:51:38.791134: step 0, loss = 4.67 (9.2 examples/sec; 13.928 sec/batch)
2016-07-13 18:51:41.009791: step 10, loss = 4.62 (845.5 examples/sec; 0.151 sec/batch)
2016-07-13 18:51:42.653312: step 20, loss = 4.52 (785.7 examples/sec; 0.163 sec/batch)
2016-07-13 18:51:44.270884: step 30, loss = 4.42 (792.6 examples/sec; 0.161 sec/batch)
```

What need's to be done to make this fast?

**Comment by benoitsteiner** [comment] 2016-07-13 22:56
The performance of the cifar10 model is limited by the speed at which we can perform the local response normalization. This operation is currently implemented for CPU only. Since most CPUs don't support fp16, we have to emulate the corresponding computations, which is incredibly slow.

The performance should improve significantly once we add support for LRN on GPU. Another option would be to compile tensorflow with support for the f16c instruction that's been introduced with the Haswell architecture. That should reduce the performance gap between fp16 and fp32.

**Comment by thinxer** [comment] 2016-07-14 02:48
@sbrodehl GTX 1080's fp16 performance is well under 1Tflops. See reddit discussions [here](https://www.reddit.com/r/MachineLearning/comments/4lhrfj/fp16_performance_on_gtx_1080_is_artificially/?st=iqlpu3i4&sh=0afda9d6).

**Comment by sbrodehl** [comment] 2016-07-14 15:17
Thanks @thinxer , I noticed that one later. :-/ 
NVidia did not specify any half precision intrinsics either in CUDA 8.
And thanks @benoitsteiner for the deeper insight.

**Comment by alexatknit** [comment] 2016-07-15 21:23
@sbrodehl my benchmark was simply done on a cpu only 2015 macbook pro 13"

**Comment by benoitsteiner** [comment] 2016-07-27 01:35
In https://github.com/tensorflow/tensorflow/commit/7d3f838f76e34cde680d9815ba300a989e641e86 I extended the ptb_word_lm model used in our [RNN tutorial](https://www.tensorflow.org/versions/r0.7/tutorials/recurrent/index.html) to train using fp16.

**Comment by benoitsteiner** [comment] 2016-08-11 22:44
Starting with https://github.com/tensorflow/tensorflow/commit/0e91b8b4db9c40bc8c45bcc69dd18e03d9f898a3, it's now possible to train our reference translation model using fp16.

I'm closing this issue since we now have several reference models that demonstrate the use of fp16 in TensorFlow. Please file separate bugs if you encounter specific limitations or bug in the functionality.

**Closed by benoitsteiner** 2016-08-11 22:44 UTC

**Comment by icyblade** [comment] 2017-03-13 08:18
Confirm a slow speed on fp16 just like @sbrodehl .

## Environment

Tesla K80 + CUDA 8.0 + cuDNN v5.1

Tensorflow v0.12.1

`nvidia-smi` information:

```
# nvidia-smi
Mon Mar 13 16:14:44 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:08.0     Off |                  Off |
| N/A   52C    P0    57W / 149W |   1543MiB / 12205MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:00:09.0     Off |                  Off |
| N/A   39C    P0    68W / 149W |   1458MiB / 12205MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

## FP32 result

```
# python cifar10_train.py
2017-03-13 16:08:27.988583: step 0, loss = 4.68 (7.6 examples/sec; 16.831 sec/batch)
2017-03-13 16:08:29.203714: step 10, loss = 4.61 (805.1 examples/sec; 0.159 sec/batch)
2017-03-13 16:08:30.726646: step 20, loss = 4.50 (759.7 examples/sec; 0.168 sec/batch)
2017-03-13 16:08:32.171580: step 30, loss = 4.43 (965.8 examples/sec; 0.133 sec/batch)
2017-03-13 16:08:33.639704: step 40, loss = 4.40 (831.2 examples/sec; 0.154 sec/batch)
2017-03-13 16:08:35.092967: step 50, loss = 4.34 (964.5 examples/sec; 0.133 sec/batch)
2017-03-13 16:08:36.590003: step 60, loss = 4.28 (865.6 examples/sec; 0.148 sec/batch)
```

`nvidia-smi` shows that GPU-util is around 50%.

## FP16 result

```
# python cifar10_train.py --use_fp16
2017-03-13 16:12:18.382315: step 0, loss = 4.67 (7.2 examples/sec; 17.864 sec/batch)
2017-03-13 16:12:28.586276: step 10, loss = 4.64 (130.9 examples/sec; 0.978 sec/batch)
2017-03-13 16:12:38.912454: step 20, loss = 4.44 (126.1 examples/sec; 1.015 sec/batch)
2017-03-13 16:12:49.141316: step 30, loss = 4.52 (130.9 examples/sec; 0.978 sec/batch)
2017-03-13 16:12:59.328050: step 40, loss = 4.43 (129.4 examples/sec; 0.989 sec/batch)
2017-03-13 16:13:09.573551: step 50, loss = 4.42 (132.3 examples/sec; 0.967 sec/batch)
2017-03-13 16:13:20.116336: step 60, loss = 4.49 (106.9 examples/sec; 1.197 sec/batch)
```

`nvidia-smi` shows that GPU-util is around 10% only.

**Comment by sbrodehl** [comment] 2017-03-13 10:07
This is because K80 has no FP16 support.
The only card which really benefits from FP16 is a P100, all others have limited support.

**Comment by icyblade** [comment] 2017-03-13 10:57
@sbrodehl K80 do have 5591–8736 GFLOPS processing power

Ref: https://en.wikipedia.org/wiki/Nvidia_Tesla

**Comment by tblaschke** [comment] 2017-05-30 08:38
@icyblade 
No. FP16 is half precision, not single precision. The stated 5591–8736 GFLOPS are single precision (FP32) performance. As sbrodehl mentioned: Up to now only the P100 supports FP16. Other cards have crippled FP16 support/performance

**Comment by wodesuck** [comment] 2017-06-06 07:50
I test an rnn model with float16 on Tesla P4, also slower than float32..

**Comment by sergey-serebryakov** [comment] 2017-06-14 21:13
@wodesuck I think P4 does not really support half precision natively. NVIDIA mentions only FP32 and INT8. I am observing similar behavior with P4

**Comment by aditbhrgv** [comment] 2017-07-26 05:35
@icyblade What changes did you do in Tensorflow, cuDNN5.1 to run inference for FP16 ? Can you please provide your code if possible

**Comment by sbrodehl** [comment] 2017-07-26 12:53
See commit bcb8f33b788bd02f1b6bdf813129d5668c6c4e5e.

**Comment by ashokbugude** [comment] 2017-08-19 03:10
@benoitsteiner  or anyone,  Please Help - **'half' is not a member of 'Eigen'**

**Task :** 
I am trying to build TensorFlow Library using OpenCL in order to run the operations on GPU without enabling GPU  of Tensorflow (without CUDA/NVIDIA). 
Basically want to run on mobile GPU with the help of Android NDK and the built opencl-tensorflow library)

**Steps Taken:** 
Replace the eigen_archive libray in /home/ashok/.cache/bazel/_bazel_ashok/337a0d8d7fbaddcaa8098e349718a6d6/external with
'eigen-opencl' library of https://bitbucket.org/benoitsteiner/eigen-opencl and build TensorFlow using bazel

**Issues Faced:  'half' is not a member of 'Eigen'**
INFO: Found 1 target...
ERROR: /home/ashok/Ashok/tensorflow-1.0.1/tensorflow/core/BUILD:814:1: C++ compilation of rule '//tensorflow/core:android_tensorflow_lib_lite' failed (Exit 1)
In file included from ./tensorflow/core/framework/allocator.h:25:0,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from ./tensorflow/core/util/guarded_philox_random.h:19,
                 from tensorflow/core/util/guarded_philox_random.cc:16:
./tensorflow/core/framework/type_traits.h:69:52: error: 'half' is not a member of 'Eigen'
       std::is_trivial<T>::value || std::is_same<T, Eigen::half>::value ||
                                                    ^
./tensorflow/core/framework/type_traits.h:69:52: error: 'half' is not a member of 'Eigen'
./tensorflow/core/framework/type_traits.h:69:63: error: template argument 2 is invalid
       std::is_trivial<T>::value || std::is_same<T, Eigen::half>::value ||
                                                               ^
Target //tensorflow/examples/android:tensorflow_demo failed to build
 
Kindly provide an insight in resolving the issue

**Comment by suke27** [comment] 2018-03-29 06:22
i have a float 32 model, can i direct run it in float16 case? for pytorch it is ok. but tensorflow. i don't know how to run it as float 16, any body know about it?

**Comment by sbrodehl** [comment] 2018-03-29 07:19
Use `dtype` `tf.float16` in your model, e.g. bcb8f33b788bd02f1b6bdf813129d5668c6c4e5e.

**Comment by suke27** [comment] 2018-03-29 08:06
do you mean train using float 16? currently I have a model which training using float 32. can I convert to float 16 model, In pytorch we just using as model.half(). I am not sure, how tensorflow support
