### ISSUE TITLE
AssertAllCloseToAccordingToType()  Error

### ISSUE THREAD

**Issue by Junzhewang** [tensorflow/tensorflow#23038] opened 2018-10-17 10:45 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
no
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.08
- **Python version**:
3.0
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
CPU

Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
Comparing two results from division (Array-a / Array-b), if I use self.AssertAllEqual(a,b), it works perfectly, however, if I use self.AssertAllCloseAccordingToType(a , b), it gives me an error, saying:
not close where =  (array([], dtype=int64),)
not close lhs =  []
not close rhs =  []
not close dif =  []
not close tol =  []

I figured that there is a NaN in the array, but AssertAllEqual handles the NaN perfectly.

**Comment by tensorflowbutler** [comment] 2018-10-17 19:14
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-10-30 22:43
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by harshini-gadige** [comment] 2018-11-01 20:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-01 20:49 UTC
Labels: comp:ops, stat:awaiting response, type:bug/performance
