### ISSUE TITLE
Valid device NotFoundError when running BatchNormalization op of Tensorflow 2.0.0

### ISSUE THREAD

**Issue by bugpromax** [tensorflow/tensorflow#46638] opened 2021-01-24 13:36 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 2019
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):  N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
As declared in the specification, tf.keras.layers.BatchNormalization should support to set the dtype to 'float64' . However, per our experiment, running it as the Norm layer in float64  will trigger some unexpected error: tensorflow.python.framework.errors_impl.NotFoundError: Could not find valid device for node.Node:{{node FusedBatchNormV3}}

**Describe the expected behavior**
No exception during execution

**Standalone code to reproduce the issue**
x = np.random.randn(1, 2, 4, 4)
x=tf.convert_to_tensor(x, dtype=tf.float16)
tf__Norm_64=tf.keras.layers.BatchNormalization(
        axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
        beta_initializer='zeros', gamma_initializer='ones',
        moving_mean_initializer='zeros', moving_variance_initializer='ones',dtype='float64'
)
out_16_64 = tf_Norm_64(x_16)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2021-01-25 07:12
@bugpromax 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/512a982aa8add5b3f5ad3a359d5bed80/untitled507.ipynb) and share all dependencies for us to replicate the issue reported.

**Comment by bugpromax** [comment] 2021-01-26 10:36
the code should be:
x = np.random.randn(1, 2, 4, 4)
x=tf.convert_to_tensor(x, dtype=tf.float16)
tf_Norm_64=tf.keras.layers.BatchNormalization(
axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
beta_initializer='zeros', gamma_initializer='ones',
moving_mean_initializer='zeros', moving_variance_initializer='ones',dtype='float64'
)
out_16_64 = tf_Norm_64(x_16)

**Comment by bugpromax** [comment] 2021-01-26 12:36
please check the [gist here](https://colab.research.google.com/drive/1VL5Mn55HmOAYaMWtLTpsVzipGhwtKbhe?usp=sharing)

**Comment by Saduf2019** [comment] 2021-01-27 10:51
@bugpromax
Please share all dependencies, we do not have access to the gist shared.

**Comment by bugpromax** [comment] 2021-01-28 05:37
import tensorflow as tf
import numpy as np

x = np.random.randn(1, 2, 4, 4)
x_16=tf.convert_to_tensor(x, dtype=tf.float16)
tf_Norm_64=tf.keras.layers.BatchNormalization(
axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True,
beta_initializer='zeros', gamma_initializer='ones',
moving_mean_initializer='zeros', moving_variance_initializer='ones',dtype='float64'
)
out_16_64 = tf_Norm_64(x_16)

**Comment by Saduf2019** [comment] 2021-01-29 05:17
@bugpromax 
I ran the code shared on tf 2.4 and this error has been fixed in the stable version can you please upgrade to tf 2.4 and let us know.
Please fidn the gist here for [tf 2.4](https://colab.research.google.com/gist/Saduf2019/2fbfe8dcd7bbd4f3ff3ecb3c9c64eb74/untitled511.ipynb)

**Comment by bugpromax** [comment] 2021-01-29 13:45
I ran the code on tf 2.4 and found that the error can be fixed. Thanks for your reply！

**Comment by Saduf2019** [comment] 2021-01-29 13:59
@bugpromax 
Glad the issue is resolved, can you please move this to closed status.

**Closed** 2021-01-30 02:09 UTC
Labels: TF 2.0, stat:awaiting response, type:bug
