### ISSUE TITLE
Which API can implement tensor expansion in tensorflow ？

### ISSUE THREAD

**Issue by goljx** [tensorflow/tensorflow#28208] opened 2019-04-27 07:54 UTC
If  I have a tensor of (30,40,50), and I want to expand it out to the first order, then I get a second order tensor of (30,2000), and I don't know if tensorflow has an API that implements it.
For example

import tensorflow as tf
import numpy as np
data1=tf.constant([[[2,5,7,8],[6,4,9,10],[14,16,86,54]],
                 [[16,43,65,76],[43,65,7,24],[15,75,23,75]]])

data5=tf.reshape(data1,[3,8])

data2,data3,data4=tf.split(data1,3,1)
data6=tf.reshape(data2,[1,8])
data7=tf.reshape(data3,[1,8])
data8=tf.reshape(data4,[1,8])
data9=tf.concat([data6,data7,data8],0)

with tf.Session() as sess:
    print(sess.run(data5))
    print(sess.run(data))

data5
 [[ 2  5  7  8  6  4  9 10]
 [14 16 86 54 16 43 65 76]
 [43 65  7 24 15 75 23 75]]

data9
[[ 2  5  7  8 16 43 65 76]
 [ 6  4  9 10 43 65  7 24]
 [14 16 86 54 15 75 23 75]]

How do I get data9 directly(Or maybe I got it wrong)

**Comment by muddham** [comment] 2019-04-29 15:22
@goljx Request you to use the reference [link1](https://stackoverflow.com/questions/55878846/which-api-can-implement-tensor-expansion-in-tensorflow),[link TF1.13](https://www.tensorflow.org/api_docs/python/tf/keras/backend/expand_dims?hl=en), [link TF1.13](url),[link TF2.0](https://www.tensorflow.org/versions/r2.0/api_docs/cc/class/tensorflow/ops/expand-dims?hl=en).
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-05-03 06:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-03 06:54 UTC
Labels: comp:ops, stat:awaiting response, type:support

**Comment by goljx** [comment] 2019-05-05 06:08
I think tf. Reshape just realized dimension to get data5, and I want to get is mathematical dimension to get data9.
Dgumo in stackoverflow suggested I can try data9 = tf.layers.flatten(tf.transpose(data1, 0, 2)). Actually I could get what I want from this.
And latter I found I could get the right result by data9=tl.unfold(data1, mode=2) by  import tensorly as tl             
and from tensorly.decomposition import parafac
