### ISSUE TITLE
distribut data io problem and I want to know way

### ISSUE THREAD

**Issue by datemoon** [tensorflow/tensorflow#35494] opened 2019-12-30 11:16 UTC
hi, I find some bug. Code is

import tensorflow as tf

if __name__ == '__main__':
    def Gen():
        for i in range(10):
            yield(i,2,3,4,5,6,7,8)

    dataset = tf.data.Dataset.from_generator(Gen, output_types=(tf.float32,tf.float32,tf.int32,tf.int32,tf.int32,tf.float32,tf.int32,tf.int32),output_shapes=None,args=None)
    for one_batch in dataset:
        print('one batch',one_batch)

    print("******end**********")

    num_gpu=1
    devices = ['/device:GPU:{}'.format(i) for i in range(num_gpu)]
    strategy = tf.distribute.MirroredStrategy(devices)

    input_context = tf.distribute.InputContext(num_input_pipelines=1,
            input_pipeline_id=0,
            num_replicas_in_sync=1)

    with strategy.scope():
        def dataset_fn(input_context):
            dataset = tf.data.Dataset.from_generator(Gen, output_types=(tf.float32,tf.float32,tf.int32,tf.int32,tf.int32,tf.float32,tf.int32,tf.int32),output_shapes=None,args=None)
            return dataset.shard(
                    input_context.num_input_pipelines, input_context.input_pipeline_id)

        train_dist_dataset = strategy.experimental_distribute_datasets_from_function(dataset_fn)

        for one_batch  in train_dist_dataset:
            print('****one batch*******',one_batch)

The code can be run, but in distribut "for one_batch  in train_dist_dataset:" at the end batch will be error.
Traceback (most recent call last):
  File "/usr/local/python35/lib/python3.5/pdb.py", line 1665, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/python35/lib/python3.5/pdb.py", line 1546, in _runscript
    self.run(statement)
  File "/usr/local/python35/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/search/speech/hubo/git/tf-code-acoustics/tf2.0-model/io_test.py", line 45, in <module>
    for one_batch  in train_dist_dataset:
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 275, in __next__
    return self.get_next()
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 304, in get_next
    global_has_value, replicas = _get_next_as_optional(self, self._strategy)
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 200, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 878, in get_next_as_list
    lambda: _dummy_tensor_fn(data.value_structure))
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1204, in cond
    result = false_fn()
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 878, in <lambda>
    lambda: _dummy_tensor_fn(data.value_structure))
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 801, in _dummy_tensor_fn
    result.append(create_dummy_tensor(feature_shape, feature_type))
  File "/usr/local/python35/lib/python3.5/site-packages/tensorflow_core/python/distribute/input_lib.py", line 784, in create_dummy_tensor
    for dim in feature_shape.dims:
TypeError: 'NoneType' object is not iterable
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

I want to know why.

**Comment by anj-s** [comment] 2020-01-04 02:28
datemoon@ I am unable to reproduce the error using the tf-nightly pip package. Which version of TF are you using? Can you share a colab where this error is produced?

**Comment by saikumarchalla** [comment] 2020-04-14 07:24
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2020-04-14 07:24 UTC
Labels: comp:dist-strat, type:bug
