### ISSUE TITLE
Can't build the demo app, run this bazel command from the tensorflow directory:

### ISSUE THREAD

**Issue by ZackPashkin** [tensorflow/tensorflow#23055] opened 2018-10-17 21:37 UTC
Can't figure out how to build the demo app. Tried different ways doesn't work. 
I have tried:

**`bazel build -c opt --cxxopt='--std=c++11' --fat_apk_cpu=armeabi-v7a //tensorflow/contrib/l
ite/examples/android:tflite_demo`**

**`bazel build -c opt --cxxopt='--std=c++11' --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a 
//tensorflow/contrib/lite/examples/android:tflite_demo`**

**`bazel build -c opt --config=android_arm{,64} --cxxopt='--std=c++11' \
//tensorflow/contrib/lite/examples/android:tflite_demo`
`**

**System information**
 Ubuntu 16.04 on GCP 
run  Docker

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`kaisenaiko@tpu-cv-app:~$ **sudo docker run --rm -it --privileged -p 6006:6006 detect-tf**
root@c567d9e05859:/tensorflow# 
root@c567d9e05859:/tensorflow# bazel build -c opt --config=android_arm{,64} --cxxopt='--std=c++11' \
> //tensorflow/contrib/lite/examples/android:tflite_demo
WARNING: The following configs were expanded more than once: [android]. For repeatable flags, repeats are counted twice and
 may lead to unexpected behavior.
WARNING: option '--crosstool_top' was expanded to from both option '--config=download_clang' (source /tensorflow/.tf_config
ure.bazelrc) and option '--config=android_arm' (source command line options)
WARNING: option '--cpu' was expanded to from both option '--config=android_arm' (source command line options) and option '-
-config=android_arm64' (source command line options)
WARNING: option '--fat_apk_cpu' was expanded to from both option '--config=android_arm' (source command line options) and o
ption '--config=android_arm64' (source command line options)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdow
n".
ERROR: No default_toolchain found for cpu 'arm64-v8a'. Valid cpus are: [
  k8,
  local,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]
INFO: Elapsed time: 5.567s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded)
root@c567d9e05859:/tensorflow# **bazel build -c opt --config=android_arm{,32} --cxxopt='--std=c++11' //tensorflow/contrib/lit
e/examples/android:tflite_demo**
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=123
INFO: Reading rc options for 'build' from /etc/bazel.bazelrc:
  'build' options: --spawn_strategy=standalone --genrule_strategy=standalone
INFO: Reading rc options for 'build' from /tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=t
rue --define=grpc_no_ares=true --spawn_strategy=standalone --genrule_strategy=standalone -c opt --define=grpc_no_ares=true 
--define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/lib/python2.7/dist-packag
es --python_path=/usr/bin/python --config=xla --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_ROCM=0 --action_env T
F_NEED_CUDA=0 --action_env TF_DOWNLOAD_CLANG=1 --config=download_clang
INFO: Found applicable config definition build:xla in file /tensorflow/.tf_configure.bazelrc: --define with_xla_support=tru
e
INFO: Found applicable config definition build:download_clang in file /tensorflow/.bazelrc: --crosstool_top=@local_config_d
ownload_clang//:toolchain --define=using_clang=true
INFO: Found applicable config definition build:android_arm in file /tensorflow/.bazelrc: --config=android --cpu=armeabi-v7a
 --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file /tensorflow/.bazelrc: --crosstool_top=//external:android/cro
`
`
root@c567d9e05859:/tensorflow# **bazel build -c opt --cxxopt='--std=c++11' --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
> //tensorflow/contrib/lite/examples/android:tflite_demo**
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdow
n".
Unhandled exception thrown during build; message: //tensorflow/contrib/lite/examples/android:tflite_demo BuildConfiguration
Value.Key[347ce3beb85cc56b9abdec126d2f85bd] false -> ErrorInfo{exception=com.google.devtools.build.lib.analysis.config.Inva
lidConfigurationException: No default_toolchain found for cpu 'arm64-v8a'. Valid cpus are: [
  k8,
  local,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
], rootCauses={BuildConfigurationValue.Key[785f82d034ad1259081f051c32361d64]}, cycles=[], isCatastrophic=false, rootCauseOf
Exception=BuildConfigurationValue.Key[785f82d034ad1259081f051c32361d64], isDirectlyTransient=false, isTransitivelyTransient
=false}
INFO: Elapsed time: 5.027s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded)
    currently loading: tensorflow/contrib/lite/java
java.lang.IllegalStateException: //tensorflow/contrib/lite/examples/android:tflite_demo BuildConfigurationValue.Key[347ce3b
eb85cc56b9abdec126d2f85bd] false -> ErrorInfo{exception=com.google.devtools.build.lib.analysis.config.InvalidConfigurationE
xception: No default_toolchain found for cpu 'arm64-v8a'. Valid cpus are: [
  k8,
  local,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
], rootCauses={BuildConfigurationValue.Key[785f82d034ad1259081f051c32361d64]}, cycles=[], isCatastrophic=false, rootCauseOf
`
`root@c567d9e05859:/tensorflow# **bazel build -c opt --cxxopt='--std=c++11' --fat_apk_cpu=armeabi-v7a   //tensorflow/contrib/l
ite/examples/android:tflite_demo**
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: /tensorflow/tensorflow/contrib/lite/kernels/internal/BUILD:666:1: no such package '@androidndk//': The repository could not be resolved and referenced by '//tensorflow/contrib/lite/kernels/internal:cpu_check'
ERROR: Analysis of target '//tensorflow/contrib/lite/examples/android:tflite_demo' failed; build aborted: Analysis failed
INFO: Elapsed time: 10.508s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (59 packages loaded)
    Fetching https://mirror.bazel.build/github.com/google/gemmlowp/archive/38ebac7b059e84692f53e5938f97a9943c120d98.zip
    Fetching https://mirror.bazel.build/bitbucket.org/eigen/eigen/get/fd6845384b86.tar.gz
    Fetching https://mirror.bazel.build/.../ARM_NEON_2_x86_SSE/archive/0f77d9d182265259b135dad949230ecbf1a2633d.tar.gz
root@c567d9e05859:/tensorflow# `

**Comment by tensorflowbutler** [comment] 2018-10-18 06:44
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by leo-nullptr** [comment] 2018-10-18 09:41
You should config NDK and SDK tool path first.

**Comment by ymodak** [comment] 2018-10-24 02:51
Did you try leo's suggestion?

> You should config NDK and SDK tool path first.

Please refer this link [to build NDK and SDK](https://www.tensorflow.org/lite/demo_android#install_android_ndk_and_sdk) if haven't already.

**Comment by ymodak** [comment] 2018-10-30 17:07
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-30 17:07 UTC
Labels: comp:lite, stat:awaiting response
