### ISSUE TITLE
Segfault upon importing tensorflow

### ISSUE THREAD

**Issue by Tobs40** [tensorflow/tensorflow#46534] opened 2021-01-19 11:58 UTC
Linux Mint 20
Python 3.8.5
No virtual environment
i7 870 (old processor)
pip3 install tensorflow, also fails with tf-nightly
TensorFlow version 2.4.0
GTX 1060 3GB

"import tensorflow" caues a segfault

**Comment by ravikyram** [comment] 2021-01-19 15:24
@Tobs40 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source#gpu).
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).Thanks!

**Comment by Tobs40** [comment] 2021-01-19 16:50
...so I have to buy a new computer in order to use tensorflow?

**Comment by mihaimaruseac** [comment] 2021-01-19 17:13
No. You can use TensorFlow via Google Colab or by compiling it from source (if AVX is the issue).

Does it crash on TF 2.3 too? Can you provide more logs?

**Comment by mihaimaruseac** [comment] 2021-01-19 18:26
#46516 looks similar

**Comment by Tobs40** [comment] 2021-01-19 20:34
> No. You can use TensorFlow via Google Colab or by compiling it from source (if AVX is the issue).
> 
> Does it crash on TF 2.3 too? Can you provide more logs?

Compiling from source looks complicated. Haven't tried TF 2.3 yet. If you can tell me where those logs are stored or how I can create them, then I'd be happy to post them here.

**Comment by mihaimaruseac** [comment] 2021-01-19 22:12
Try `python -vvv -c "import tensorflow as tf" > log.txt` and then attach `log.txt`

**Comment by Tobs40** [comment] 2021-01-20 11:57
The command you suggested created an empty file log.txt
I used the following instead:

`python3 -vvv -c "import tensorflow as tf" 2>&1 | tee log.txt`

[log.txt](https://github.com/tensorflow/tensorflow/files/5842192/log.txt)
`

**Comment by mihaimaruseac** [comment] 2021-01-21 18:08
There doesn't seem to be anything relevant there either. Except, maybe, what is the Python version you use, ouput of `python3 --version`?

**Comment by Tobs40** [comment] 2021-01-21 18:09
> 
> 
> There doesn't seem to be anything relevant there either. Except, maybe, what is the Python version you use, ouput of `python3 --version`?

Already mentioned it in the main post: 3.8.5

**Comment by mihaimaruseac** [comment] 2021-01-21 20:09
Can you try with the 2.4.1 release?

**Comment by Tobs40** [comment] 2021-01-21 20:26
> Can you try with the 2.4.1 release?

I thought my CPU is too old for AVX? Is 2.4.1 supposed to work for non-AVX CPU's again?

**Comment by mihaimaruseac** [comment] 2021-01-21 21:41
Oh, wait. I thought the issue is that you get an import but the CPU supports all extensions needed. Was confusing with a different issue.

If your CPU does not support AVX then the segfault is to be expected

**Comment by Tobs40** [comment] 2021-01-21 21:43
Ok, I've been wondering

**Comment by ravikyram** [comment] 2021-01-28 13:27
@Tobs40

Please, close this thread if your query has been answered. Thanks!

**Closed** 2021-01-28 14:13 UTC
Labels: TF 2.4, stat:awaiting response, type:bug

**Comment by Tobs40** [comment] 2021-01-28 14:14
Sorry, this was one of my first issues, I'm fairly new to githubAm 28.01.2021 14:27 schrieb ravikyram <notifications@github.com>:
@Tobs40
Please, close this thread if your query has been answered. Thanks!
