### ISSUE TITLE
Segfault on tf.linalg.svd

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#39446] opened 2020-05-12 04:35 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04, macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.linalg.svd` segfaults when input shape has at least one element being 0.

Also tested on the latest [tf-2.2.0](https://colab.research.google.com/drive/1cmER2YqlgwtXANSi8YbYW8TtEnt7wSPt?usp=sharing) in Colab, and segfault still exists.
**Describe the expected behavior**
Should not segfault.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import numpy as np

tf.linalg.svd(np.random.rand(2, 0)) # segfault
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2020-05-12 05:35
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/1f7a170a38966efcbe309ac24068627b/untitled177.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-05-12 12:41
I am able to reproduce the issue. This doesn't segfault when `numpy`'s svd was used as follows

```
np.linalg.svd(np.random.rand(2, 0))
# output 
(array([[1., 0.],
        [0., 1.]]),
 array([], dtype=float64),
 array([], shape=(0, 0), dtype=float64))
```

**Comment by jvishnuvardhan** [comment] 2020-07-31 01:03
@leeyeetonn Looks like this was resolved in recent `tf-nightly`. I could not reproduce this with `tf-nightly`.
[here](https://colab.research.google.com/gist/jvishnuvardhan/111c438d32c76902a0c831ed2c26317b/untitled177.ipynb) is a gist for your reference.

I am closing this issue as this was resolved. Please feel free to reopen if you notice the error again. Thanks!

**Closed by jvishnuvardhan** 2020-07-31 01:03 UTC
Labels: TF 2.1, comp:ops, type:bug
