### ISSUE TITLE
Performance issue with ParameterServerStrategy and Gather

### ISSUE THREAD

**Issue by nateagr** [tensorflow/tensorflow#28993] opened 2019-05-24 09:53 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I've developed a custom logistic regression using Estimator API. The model itself is quite simple and is composed of two variables, one for the bias b (scalar) and one for weights w which shape is (n,). n~60 millions:
```
...
with tf.variable_scope("weights"):
        w = tf.get_variable(
            "weights", initializer=tf.zeros([n]),
             trainable=True, partitioner=tf.fixed_size_partitioner(w_nb_shards)
        )

with tf.variable_scope("bias"):
        b = tf.get_variable("bias", initializer=tf.zeros([1]), trainable=True)

logits = \
        tf.add(
            b,
            tf.reduce_sum(
                tf.multiply(
                    tf.cast(tf.gather(w, feature_indices), tf.float32),
                    feature_values
                ),
                axis=1
            )
        )
batch_size = tf.shape(feature_indices)[0]
logits = tf.reshape(logits, [batch_size, -1])

predictions = tf.sigmoid(logits)

if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions={"predictions": predictions}
        )

tf.losses.sigmoid_cross_entropy(
        labels,
        logits,
        reduction=tf.losses.Reduction.SUM,
        weights=weight_column
)

if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = params.get("optimizer", tf.train.AdamOptimizer())
        train_op = optimizer.minimize(
            loss=loss, global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(
            mode=mode, loss=loss, train_op=train_op)
...
```

The training is distributed on yarn with tf-yarn (https://github.com/criteo/tf-yarn) and ParameterServerStrategy. The variable w (weights) is sharded (fixed size) across all parameter servers. The training itself runs successfully but I have performance issues, it is slow. I've used the profiler hook (tf.train.ProfilerHook) to detect what ops take time (cumulative or not) and I noticed that most of the time is spent on op Ftrl/update_weights/weights/part_0/Unique (about 6 sec). Besides the execution time, I was surprised to see that this op , run by all parameter servers for weight updates, only take that much time for ps/1. The same op takes about 5ms for other parameter servers.

![image](https://user-images.githubusercontent.com/41445208/58318802-d0dd7500-7e18-11e9-8085-db8ff087bdf4.png)

After having taken a closer look at events Ftrl/update_weights/weights/part_X/Unique, I noticed that op Unique is applied to ~1 millions integers for ps/1 and less than 15000 integers for other parameter servers. ~1 milions integers seem to match with the number of weights in the model. You can find a subset of events matching ops Unique in the file below.

Is it an expected behavior or known issue ? Should I implement the linear regression part of the model in a different way ? Thanks a lot in advance.

[EventsOpsUnique.txt](https://github.com/tensorflow/tensorflow/files/3216246/EventsOpsUnique.txt)

**Comment by gadagashwini** [comment] 2019-05-27 09:57
@nateagr Please provide a code snippet to reproduce the performance issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-06-03 04:24
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-03 04:24 UTC
Labels: comp:dist-strat, stat:awaiting response

**Comment by liyi193328** [comment] 2019-10-11 16:54
Same issue

**Comment by gadagashwini** [comment] 2019-10-14 05:25
@liyi193328, 
Can you please post a new issue by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!
