### ISSUE TITLE
Using learning-rate decay schedule and verbose=1 creates fatal TypeError

### ISSUE THREAD

**Issue by bsugerman** [tensorflow/tensorflow#41639] opened 2020-07-22 20:49 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 and Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): Binary (pip3)
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

In the following minimal example, setting `verbose=1` in the fitting creates a fatal error. I realize that `ReduceLROnPlateau` isn't needed when also using `ExponentialDecay` but the fact that this error happens if `verbose=1` and not when `verbose=0` in training shows there is a deeper problem. 

```
# minimum keras example
import tensorflow as tf
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.optimizers.schedules import ExponentialDecay
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.callbacks import TerminateOnNaN,EarlyStopping,ReduceLROnPlateau

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8,input_shape=(16,)))
model.add(tf.keras.layers.Dense(1))
callbacks=[#TerminateOnNaN(),EarlyStopping(monitor='val_loss'),
          ReduceLROnPlateau(monitor='val_loss')]
optimizer=SGD(learning_rate=ExponentialDecay(initial_learning_rate=1.e-3,
                                            decay_steps=2,decay_rate=0.5))
model.compile(optimizer=optimizer, loss='mse')
x=tf.ones((32,16))
y=tf.ones((32,1))
v=tf.ones((8,1))
model.fit(x, y, batch_size=4, epochs=8, callbacks=callbacks,
         validation_split=0.2,steps_per_epoch=4,verbose=1)
```
yields the following error:
```
Epoch 1/8
1/4 [======>.......................] - ETA: 0s - loss: 1.4363

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-138-2120310fffef> in <module>
     19 v=tf.ones((8,1))
     20 model.fit(x, y, batch_size=4, epochs=8, callbacks=callbacks,
---> 21          validation_split=0.2,steps_per_epoch=4,verbose=1)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    874           epoch_logs.update(val_logs)
    875 
--> 876         callbacks.on_epoch_end(epoch, epoch_logs)
    877         if self.stop_training:
    878           break

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    363     logs = self._process_logs(logs)
    364     for callback in self.callbacks:
--> 365       callback.on_epoch_end(epoch, logs)
    366 
    367   def on_train_batch_begin(self, batch, logs=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    892 
    893   def on_epoch_end(self, epoch, logs=None):
--> 894     self._finalize_progbar(logs)
    895 
    896   def on_test_end(self, logs=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in _finalize_progbar(self, logs)
    933       self.progbar.target = self.seen
    934     logs = logs or {}
--> 935     self.progbar.update(self.seen, list(logs.items()), finalize=True)
    936 
    937 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py in update(self, current, values, finalize)
    568         value_base = max(current - self._seen_so_far, 1)
    569         if k not in self._values:
--> 570           self._values[k] = [v * value_base, value_base]
    571         else:
    572           self._values[k][0] += v * value_base

TypeError: unsupported operand type(s) for *: 'ExponentialDecay' and 'int'
```

**Describe the expected behavior**

Model should fit without any errors. Here is what happens if I don't use the callbacks:

```
Epoch 1/8
4/4 [==============================] - 0s 20ms/step - loss: 6.3209 - val_loss: 4.6678
Epoch 2/8
4/4 [==============================] - 0s 10ms/step - loss: 4.4087 - val_loss: 4.0870
Epoch 3/8
4/4 [==============================] - 0s 9ms/step - loss: 4.0231 - val_loss: 3.9547
Epoch 4/8
4/4 [==============================] - 0s 10ms/step - loss: 3.9385 - val_loss: 3.9224
Epoch 5/8
4/4 [==============================] - 0s 9ms/step - loss: 3.9185 - val_loss: 3.9143
Epoch 6/8
4/4 [==============================] - 0s 9ms/step - loss: 3.9131 - val_loss: 3.9123
Epoch 7/8
4/4 [==============================] - 0s 9ms/step - loss: 3.9121 - val_loss: 3.9118
Epoch 8/8
4/4 [==============================] - 0s 11ms/step - loss: 3.9117 - val_loss: 3.9117
```

**Standalone code to reproduce the issue**

see above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-07-23 11:54
@bsugerman,
I was able to reproduce the issue with TF v2.2. However, the issue seems to be fixed in the latest TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/697836288a6d02f048d11e08b7044079/41639-tf-nightly.ipynb). Thanks!

**Closed** 2020-08-06 12:23 UTC
Labels: Fixed in Nightly, TF 2.2, comp:keras, stalled, stat:awaiting response, type:bug

**Comment by jhetherly** [comment] 2022-03-20 22:12
Running the [gist](https://colab.research.google.com/gist/amahendrakar/697836288a6d02f048d11e08b7044079/41639-tf-nightly.ipynb) linked above with the latest nightly (`2.9.0-dev20220320`) fails with the exact same error.
