### ISSUE TITLE
build fail: ERROR: no such target '@local_config_cuda//crosstool:toolchain'

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#6094] opened 2016-12-05 18:46 UTC
I just sync the latest code and meet build error. in fact i already assign to use GPU support during run **./configure**. but it can't find.

I am using Ubuntu 16.04, cuda 8.0 and bazel 0.32

git rev-parse HEAD

dca48e8b5adbb328c09a43b7d19300b52680d7ac

======

ERROR: /home/scopeserver/.cache/bazel/_bazel_scopeserver/b562266fb6ddaaff7ca2ee0b31316144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/scopeserver/.cache/bazel/_bazel_scopeserver/b562266fb6ddaaff7ca2ee0b31316144/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/scopeserver/.cache/bazel/_bazel_scopeserver/b562266fb6ddaaff7ca2ee0b31316144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: **Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.**
ERROR: **no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/scopeserver/.cache/bazel/_bazel_scopeserver/b562266fb6ddaaff7ca2ee0b31316144/external/local_config_cuda/crosstool/BUILD.**
INFO: Elapsed time: 0.352s

**Comment by civilman628** [comment] 2016-12-05 19:41
i just run  **bazel version** and it returns:
**Build label: 0.3.2**
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110


However, when i run **sudo apt-get upgrade bazel**, it returns: 

**bazel is already the newest version (0.4.1).**

why these 2 versions are different, one is 0.3.2 and another is 0.4.1 ?

**Comment by gunan** [comment] 2016-12-06 00:05
Could you run `which bazel`
It looks like you have two different bazel installations. 

Your bazel log says
```
Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
```
Could you retry running `./configure` and see if it helps.

**Comment by civilman628** [comment] 2016-12-06 00:31
I just download bazel 0.41 install file and install it from local, now the bazel is 0.41. 

when i run ./configure, i already assign use GPU to to Y. 
however, when i run build again. it still report the same error.

===========

scopeserver@scopephotos:~/RaidDisk/DeepLearning/mwang/tensorflow$ sudo ./configure 
[sudo] password for scopeserver: 
~/RaidDisk/DeepLearning/mwang/tensorflow ~/RaidDisk/DeepLearning/mwang/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
**Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0**
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
........
INFO: All external dependencies fetched successfully.
Configuration finished
scopeserver@scopephotos:~/RaidDisk/DeepLearning/mwang/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/scopeserver/.cache/bazel/_bazel_scopeserver/4bbf7fc8d0645aa96f0d41866ce2885c/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/scopeserver/.cache/bazel/_bazel_scopeserver/4bbf7fc8d0645aa96f0d41866ce2885c/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/scopeserver/.cache/bazel/_bazel_scopeserver/4bbf7fc8d0645aa96f0d41866ce2885c/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/scopeserver/.cache/bazel/_bazel_scopeserver/4bbf7fc8d0645aa96f0d41866ce2885c/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 0.129s

**Comment by gunan** [comment] 2016-12-06 00:45
Wait, why are you running `sudo ./configure` ?
You are running `./configure` and `bazel build ...` as different users.

Please check out the tensorflow repository to a folder your user can write to, and then run ./configure without sudo.

**Comment by gunan** [comment] 2016-12-06 07:44
I reproduced your setup with ubuntu, bazel 0.3.2 and bazel 0.4.1, and cuda 8.0
Tried to run the commands (without `sudo`) and for me everything ran successfully.

Please try running `./configure` without sudo. In your current local repository it will fail, because there are now some files owned by the root, so I would suggest removing your folder with the code in it and checking the code out again.

As I tried with a few settings and could not reproduce the problem, I will now close the issue. If you still run into this issue please reopen.

**Closed by gunan** 2016-12-06 07:44 UTC
Labels: awaiting response, type:build/install

**Comment by civilman628** [comment] 2016-12-06 19:32
oh, yeah, i change the permission for the python folder and build pass.

**Comment by mishra69** [comment] 2017-02-15 01:05
I have the same issue during build on MAC

`ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /private/var/tmp/_bazel_admin/f2f2e0ebb105daeebb988f12401380fc/external/local_config_cuda/crosstool/BUILD.`

`./configure` was run with these options 
```
admins-MacBook-Pro:tensorflow admin$ ./configure
Please specify the location of python. [Default is /Users/admin/miniconda3/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /Users/admin/miniconda3/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/Users/admin/miniconda3/lib/python3.5/site-packages]

Using python library path: /Users/admin/miniconda3/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 8.0
Please specify the location where cuDNN 8.0 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to cuDNN  toolkit. Neither of the following two files can be found:
/usr/local/cuda/lib/libcudnn.8.0.dylib
/usr/local/cuda/libcudnn.8.0.dylib
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0	
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
INFO: All external dependencies fetched successfully.
```

I noticed your guide for mac+GPU expects different output from configure script. 
these parts are missing 
```
Setting up Cuda include
Setting up Cuda lib
Setting up Cuda bin
Setting up Cuda nvvm
Setting up CUPTI include
Setting up CUPTI lib64
```


Please let me know if I should open a new issue.
