### ISSUE TITLE
Cannot save to SavedModel when custom layers accepts args and kwargs

### ISSUE THREAD

**Issue by kriskorrel-cw** [tensorflow/tensorflow#38384] opened 2020-04-09 09:49 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes and no
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or
binary): pip
- TensorFlow version (use command below): 2.2.0rc2
- Python version: 3.7.3

**Describe the current behavior**
I was having trouble with saving a custom tf.keras model to the SavedModel format, while saving to .h5 would go fine. The model is a custom ResNet model, subclassing tf.keras.Model.
https://stackoverflow.com/a/55386355/11470044 and https://www.tensorflow.org/guide/keras/save_and_serialize#part_ii_saving_and_loading_of_subclassed_models have led me to believe that it should now be possible to save such custom imperative models.
After some digging around, I've found the issue to be the following: A custom keras layer's `call()` method may not be defined like `def call(self, *args, **kwargs)`, but should strictly adhere to `def call(self, inputs, **kwargs)`.

I can show with the following [gist](https://gist.github.com/kriskorrel-cw/c90e349fddec1c2a20a031660431f80a), which is almost entirely the same as in https://www.tensorflow.org/guide/keras/save_and_serialize#part_ii_saving_and_loading_of_subclassed_models 
Using `BatchNormalization` or `BatchNormalization1`, all goes well. But when using `BatchNormalization2`, we get the following stack trace:
```
Traceback (most recent call last):
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1008, in save
    signatures, options)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 886, in save
    checkpoint_graph_view)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/saved_model/signature_serialization.py", line 74, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 142, in list_functions
    self._serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2420, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/base_serialization.py", line 91, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 80, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 162, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 258, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 172, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 513, in add_function
    self.add_trace(*self._input_signature)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 428, in add_trace
    trace_with_training(True)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 523, in wrapper
    inputs = call_collection.get_input_arg_value(args, kwargs)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 463, in get_input_arg_value
    self._input_arg_name, args, kwargs, inputs_in_args=True)
  File "/home/kriskorrel/.local/share/virtualenvs/blicker-1BQtdZDZ/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1991, in _get_call_arg_value
    return args_dict[arg_name]
KeyError: 'inputs'
```

Although this is somewhat easy to debug in the toy example, you could imagine that such an exception is hard to find in a large codebase.

**Describe the expected behavior**
I therefore think that either (a) using the `*args, **kwargs` signature should be supported, (b) a warning/exception should be raised whenever a `Model` is defined or compiled with incorrect signatures, or (c) the error message above must be improved such that a similar issue can be tracked down more easily.

**Standalone code to reproduce the issue** 
[gist](https://gist.github.com/kriskorrel-cw/c90e349fddec1c2a20a031660431f80a)

**Other info / logs**
P.S. I first tried to reproduce the issue by subclassing `Dense` instead of `BatchNormalization`, but this does not work since `Dense.call()` only accepts `inputs`. It does not support kwargs (like 'training'). I also find this inconsistency between different Layers weird, but I'm sure there's a reason for it.

**Comment by ravikyram** [comment] 2020-04-09 10:44
I have tried on colab with TF version 2.2 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1b729d38569460d39c110b9bf86b6324/untitled30.ipynb).Using **BatchNormalization1,** all goes well. But when using **BatchNormalization2** we are facing the issue. Thanks!

**Comment by objectc** [comment] 2020-10-07 18:26
Same problem with TF Nightly 2.4.0-dev20201005.

**Comment by sachinprasadhs** [comment] 2021-05-26 09:56
Was able to run your code without any errors in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/47f9a19be3bd9e26e056d52486af8863/38384.ipynb). Thanks!

**Comment by sachinprasadhs** [comment] 2021-05-26 09:58
Closing the issue since issue has been fixed in latest version, feel free to reopen the issue in case of any concerns. Thanks!

**Closed by sachinprasadhs** 2021-05-26 09:58 UTC
Labels: TF 2.2, comp:keras, stat:awaiting tensorflower, type:bug
