### ISSUE TITLE
latest-devel-gpu and devel-gpu docker images out of sync

### ISSUE THREAD

**Issue by settle** [tensorflow/tensorflow#38813] opened 2020-04-22 20:05 UTC
latest-devel and devel are the same image as expected, but that's not the case for latest-devel-gpu and devel-gpu.

$ docker images
REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
-|-|-|-|-
tensorflow/tensorflow | latest-devel | 468b5e19fd6a | 6 hours ago | 1.97GB
tensorflow/tensorflow | devel | 468b5e19fd6a | 6 hours ago | 1.97GB
tensorflow/tensorflow | latest-devel-gpu | 08aacdcc1422 | 7 hours ago | 4.17GB
tensorflow/tensorflow | devel-gpu | 72b4573fd1c4| 30 hours ago | 4.17GB

**Comment by Saduf2019** [comment] 2020-04-23 11:01
@settle 
this issue seems like a duplicate of #38811 in that case can you please close one of them as duplicate.

**Comment by settle** [comment] 2020-04-23 18:37
@Saduf2019 #38811, #38812, and this one (#38813) are related but all different issues regarding various docker images being out of date or out of sync.

**Comment by angerson** [comment] 2020-04-23 22:57
I am closing this as a duplicate of #38812, because they are very similar.

**Closed by angerson** 2020-04-23 22:57 UTC
Labels: stat:awaiting response, type:bug
