### ISSUE TITLE
Unable to safely terminate tensor flow running on gpu

### ISSUE THREAD

**Issue by suniliitm** [tensorflow/tensorflow#1203] opened 2016-02-19 20:03 UTC
I have implement a network using tensorflow on a Nvidia GPU. Even after I call sess.close(), the program won't stop. When I hit ctrl+c for termination, the program crashes the nvidia driver and creates a zombie process named "python". I am not able to kill the zombie process, neither can I reboot ubuntu system by sudo reboot.

Is this a known issue? Please help!

**Comment by Lazare** [comment] 2016-02-23 16:47
Same problem here with tensorflow 0.7.1 on Ubuntu 15.10
Mxnet 0.5 works fine so it's probably not a problem with cuda(7.5) or cudnn(v4)

**Comment by Lazare** [comment] 2016-02-23 17:20
here's the kernel trace if it can help

Feb 23 17:36:53 bob kernel: [  784.040306] nvidia_uvm: Loaded the UVM driver, major device number 247
Feb 23 17:38:38 bob kernel: [  889.142620] BUG: unable to handle kernel NULL pointer dereference at 0000000000000020
Feb 23 17:38:38 bob kernel: [  889.142657] IP: [<ffffffffc14e2b4d>] _nv002815rm+0x51d/0x610 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142658] PGD 0
Feb 23 17:38:38 bob kernel: [  889.142659] Oops: 0000 [#1] SMP
Feb 23 17:38:38 bob kernel: [  889.142671] Modules linked in: nvidia_uvm(POE) bnep arc4 nls_iso8859_1 nvidia(POE) intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel ath10k_pci ath10k_core kvm btusb crct10dif_pclmul snd_hda_codec_hdmi crc32_pclmul btrtl btbcm ath btintel mac80211 bluetooth aesni_intel snd_hda_codec_realtek snd_hda_codec_generic aes_x86_64 cfg80211 snd_hda_intel snd_hda_codec drm lrw gf128mul sb_edac mxm_wmi edac_core snd_hda_core glue_helper ablk_helper cryptd serio_raw snd_hwdep snd_pcm mei_me snd_timer snd mei soundcore shpchp lpc_ich mac_hid wmi autofs4 psmouse alx ahci mdio libahci
Feb 23 17:38:38 bob kernel: [  889.142673] CPU: 3 PID: 1216 Comm: python Tainted: P           OE   4.2.0-30-generic #35-Ubuntu
Feb 23 17:38:38 bob kernel: [  889.142674] Hardware name: MSI MS-7883/X99A GODLIKE GAMING (MS-7883), BIOS 1.20 10/30/2015
Feb 23 17:38:38 bob kernel: [  889.142674] task: ffff881041fb5280 ti: ffff881041fcc000 task.ti: ffff881041fcc000
Feb 23 17:38:38 bob kernel: [  889.142699] RIP: 0010:[<ffffffffc14e2b4d>]  [<ffffffffc14e2b4d>] _nv002815rm+0x51d/0x610 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142700] RSP: 0018:ffff881041fcfa08  EFLAGS: 00010246
Feb 23 17:38:38 bob kernel: [  889.142700] RAX: 0000000000000000 RBX: ffff88107037c008 RCX: 0000000000000000
Feb 23 17:38:38 bob kernel: [  889.142700] RDX: 0000000000000000 RSI: 0000000000000011 RDI: 0000000000000000
Feb 23 17:38:38 bob kernel: [  889.142701] RBP: ffff881071f82f58 R08: 00000002f6a4c439 R09: ffff8810705d4700
Feb 23 17:38:38 bob kernel: [  889.142701] R10: 0000000056cc8b0e R11: ffffffffc19037f0 R12: 0000000000000000
Feb 23 17:38:38 bob kernel: [  889.142701] R13: 0000000000000001 R14: 0000000000000001 R15: ffff881071f46808
Feb 23 17:38:38 bob kernel: [  889.142702] FS:  00007f2e30ff9700(0000) GS:ffff88107f2c0000(0000) knlGS:0000000000000000
Feb 23 17:38:38 bob kernel: [  889.142703] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Feb 23 17:38:38 bob kernel: [  889.142703] CR2: 0000000000000020 CR3: 0000000002c0c000 CR4: 00000000001406e0
Feb 23 17:38:38 bob kernel: [  889.142703] Stack:
Feb 23 17:38:38 bob kernel: [  889.142704]  ffff88107037c008 ffff881074831008 ffff881071f49008 0000000000000000
Feb 23 17:38:38 bob kernel: [  889.142705]  ffff881072108008 ffffffffc14dcb50 ffff881074831008 ffff88107037c008
Feb 23 17:38:38 bob kernel: [  889.142706]  0000000000001100 0000000000000000 0000000000000026 ffffffffc14d3881
Feb 23 17:38:38 bob kernel: [  889.142706] Call Trace:
Feb 23 17:38:38 bob kernel: [  889.142731]  [<ffffffffc14dcb50>] ? _nv003017rm+0xf0/0x1c0 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142755]  [<ffffffffc14d3881>] ? _nv003008rm+0x11/0x50 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142809]  [<ffffffffc16fba40>] ? _nv002021rm+0x2640/0x3c30 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142833]  [<ffffffffc194ea69>] ? _nv000654rm+0x2b9/0x340 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142857]  [<ffffffffc1944f9a>] ? rm_disable_adapter+0x6a/0x130 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142882]  [<ffffffffc1960da6>] ? nv_uvm_notify_stop_device+0x46/0x60 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142906]  [<ffffffffc195523e>] ? nvidia_close+0x19e/0x3d0 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142930]  [<ffffffffc1952e5d>] ? nvidia_frontend_close+0x4d/0x90 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142932]  [<ffffffff811ff954>] ? __fput+0xe4/0x220
Feb 23 17:38:38 bob kernel: [  889.142933]  [<ffffffff811ffade>] ? ____fput+0xe/0x10
Feb 23 17:38:38 bob kernel: [  889.142935]  [<ffffffff810991c3>] ? task_work_run+0x73/0x90
Feb 23 17:38:38 bob kernel: [  889.142936]  [<ffffffff8107e180>] ? do_exit+0x3a0/0xb10
Feb 23 17:38:38 bob kernel: [  889.142936]  [<ffffffff8107e983>] ? do_group_exit+0x43/0xb0
Feb 23 17:38:38 bob kernel: [  889.142937]  [<ffffffff8108aa94>] ? get_signal+0x274/0x600
Feb 23 17:38:38 bob kernel: [  889.142940]  [<ffffffff81014467>] ? do_signal+0x37/0xa40
Feb 23 17:38:38 bob kernel: [  889.142943]  [<ffffffff810fc011>] ? SyS_futex+0x81/0x180
Feb 23 17:38:38 bob kernel: [  889.142944]  [<ffffffff810ed88d>] ? getrawmonotonic64+0x2d/0xc0
Feb 23 17:38:38 bob kernel: [  889.142945]  [<ffffffff81014ecb>] ? do_notify_resume+0x5b/0x70
Feb 23 17:38:38 bob kernel: [  889.142947]  [<ffffffff817f2f44>] ? int_signal+0x12/0x17
Feb 23 17:38:38 bob kernel: [  889.142954] Code: f8 73 00 31 c9 44 89 f2 be 2c 00 00 00 48 89 c7 ff 50 20 48 85 c0 49 89 c4 0f 84 d6 00 00 00 31 c9 31 d2 be 11 00 00 00 4c 89 e7 <41> ff 54 24 20 be 30 00 00 00 48 8b b8 a8 05 00 00 48 89 c3 ff
Feb 23 17:38:38 bob kernel: [  889.142978] RIP  [<ffffffffc14e2b4d>] _nv002815rm+0x51d/0x610 [nvidia]
Feb 23 17:38:38 bob kernel: [  889.142979]  RSP <ffff881041fcfa08>
Feb 23 17:38:38 bob kernel: [  889.142979] CR2: 0000000000000020
Feb 23 17:38:38 bob kernel: [  889.143700] ---[ end trace a558f3a5039f98c9 ]---
Feb 23 17:38:38 bob kernel: [  889.143700] Fixing recursive fault but reboot is needed!

**Comment by Lazare** [comment] 2016-02-25 10:48
here's a few more information

I use 
cudnn : 4.0.7 (can't find the 4.0.4 that seems to be the one that's officialy supported)
cuda : 7.5.18
drivers : 352.79 

maybe that will help find the bug
just to be clear because the title doesn't reflect this :
**the nvidia driver crash. you can't use the cards anymore until you physicaly reboot the server.
if you try a soft reboot it it will crash the system completly.**

**Comment by Lazare** [comment] 2016-02-26 17:19
I've switched to ubuntu 15.04 and it fixed my problem

**Comment by jmhessel** [comment] 2016-04-15 05:06
I had the same problem. Went from 14.04 -> 15.10, everything started working. Cudnn 4.0.7, CUDA 7.5.

**Comment by flow-ryan** [comment] 2016-06-03 15:14
have the same problem with exactly the same driver and cuda versions, do I really have to switch my OS for it to work? #1947

**Comment by vrv** [comment] 2016-06-03 16:47
I've heard it's a problem with cuda 7.5 and ubuntu 14 -- downgrading cuda to 7.0 also apparently works.  Hopefully cuda 8.0 doesn't have this problem, but it's still in RC, so our pip installations still require 7.5.

**Comment by flow-ryan** [comment] 2016-06-06 09:21
unfortunately downgrading using 7.0 with 4.0.7 did not work and I tried it with the drivers 352.39 and 346.46

**Comment by girving** [comment] 2016-06-06 22:02
@vrv: Should we close, or is a fix possible on our end?

**Comment by vrv** [comment] 2016-06-06 23:08
I have a way to reproduce or debug, so we either need a fix from the community, or a repro

**Comment by vrv** [comment] 2016-06-06 23:08
*I don't

**Comment by flow-ryan** [comment] 2016-06-07 07:46
I did write down all steps while setting up a g2 aws instance where I encountered that problem. Maybe I forgot some apt-get or cd but the majority should be here.

The os was ubuntu server 14.04 - ami-fce3c696.

```
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y build-essential

sudo apt-get install -y make pkg-config xorg-dev zip zlib1g-dev

# Blacklist Noveau which has some kind of conflict with the nvidia driver
echo -e "blacklist nouveau\nblacklist lbm-nouveau\noptions nouveau modeset=0\nalias nouveau off\nalias lbm-nouveau off\n" | sudo tee /etc/modprobe.d/blacklist-nouveau.conf
echo options nouveau modeset=0 | sudo tee -a /etc/modprobe.d/nouveau-kms.conf
sudo update-initramfs -u
sudo reboot # Reboot

# install nvidia driver, cuda, cud
wget http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.18_linux.run
# wget http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/cuda_7.0.28_linux.run

sudo apt-get install -y linux-image-extra-`uname -r` linux-headers-`uname -r` linux-image-`uname -r`

chmod +x cuda_7.5.18_linux.run
./cuda_7.5.18_linux.run -extract=`pwd`/nvidia_installers
cd nvidia_installers
#install driver
sudo ./NVIDIA-Linux-x86_64-352.39.run 
cd ..

#install cuda
sudo ./nvidia_installers/cuda-linux64-rel-7.5.18-19867135.run 

echo 'export LD_LIBRARY_PATH=/usr/local/cuda-7.5/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
echo 'export CUDA_HOME=/usr/local/cuda-7.5' >> ~/.bashrc
echo 'export PATH=$PATH:/usr/local/cuda-7.5/bin' >> ~/.bashrc

#install cudnn --> first download cudnn-7.5-linux-x64-v5.0-rc.tar or 7.0-v4
tar -xf cudnn-7.5-linux-x64-v5.0-rc.tar
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo cp cuda/include/cudnn.h /usr/local/cuda/include/

# install all package dependencies
sudo apt-get install -y \
zip \
vim \
swig \
fortran \
git \
libboost-all-dev \
libatlas-base-dev \
libblas-dev \
liblapack-dev \
python-dev \
python-pip \
vim \
software-properties-common \
libjpeg8-dev \
byobu \
libfreetype6-dev \
libpng-dev

sudo pip install -U pip

sudo pip install -U \
virtualenv \
bumpy \
scipy \
matplotlib \
gensim \
sacred \
scikit-learn \
langdetect \
pymongo \
jupiter \
scikit-image \
pyyaml \
pandas \
bs4

# install jdk 1.8 for bazel
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer

# install bazel
git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout tags/0.2.0
./compile.sh
sudo cp output/bazel /usr/bin
cd ..

# install tensorflow
git clone -b r0.8 --recurse-submodules https://github.com/tensorflow/tensorflow
cd tensorflow
./configure

# bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow
sudo pip install /tmp/tensorflow/tensorflow-0.8.0rc0-py2-none-any.whl
```

**Comment by girving** [comment] 2016-06-07 14:57
@flow-ryan: Thank you for the instructions, but unfortunately this sounds like a bug below the level of TensorFlow, either in Linux or the GPU driver.  Since it's already fixed in more recent Ubuntu, I'm going to close.  We'll happily accept a PR if you find a reasonable workaround for the problem, though.

**Closed by girving** 2016-06-07 14:57 UTC
Labels: contributions welcome, triaged

**Comment by taifeng1205** [comment] 2016-07-14 06:40
@jmhessel @suniliitm @Lazare , we are facing with the same problem you mentioned above. Our setting is ubuntu14.04 lts, cuda 7.5.18, cudnn 4.0. (hardware, 2*titanX per machine, or 8*tesla k40 per machine).  As chivee said, tensorflow can work correctly in the case when some process else related to GPU started(e.g. x server, or another tf/torch/theano process keep running). And what's more we have further checked, if there is just one GPU in the server, this issue doesn't exist as well. I would like to make sure you said updating the Ubuntu version would get through, did you check whether another Linux version has triggered x server inside which starting to use GPU? @girving , do you have any suggestion for us, if we want to check the detail code?

**Comment by girving** [comment] 2016-07-14 15:49
@chivee @taifeng1205 Unfortunately, as noted above this seems like a bug in Linux or the GPU driver, so we may not be able to fix it on our end.  We're happen to accept PRs if you find a fix, but upgrading may be the easiest route.

**Comment by Qwlouse** [comment] 2016-07-20 13:10
On my Debian machine enabling [persistence mode](http://docs.nvidia.com/deploy/driver-persistence/) resolved the problem.

**Comment by chivee** [comment] 2016-07-22 02:28
@Qwlouse it works! thank you so much.

**Comment by cdubout** [comment] 2018-02-15 15:03
@Qwlouse thanks!

**Comment by phoenixbai** [comment] 2018-06-21 09:16
I am having the same problem with redhat el7, cuda9.0.
How can I fix it? reboot is not an option. please help.
