### ISSUE TITLE
in train_validation_split raise ValueError( ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found: (array([[[[0.24705882]

### ISSUE THREAD

**Issue by domindominik** [tensorflow/tensorflow#38613] opened 2020-04-16 21:20 UTC
**PyCharm
Debian 10.3
Python 3.8.2
Cuda 10.2
cuDNN 7.6
Quadro K5200d drivers 440.82
Tensorflow 2.2.0-rc2**

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle

pickle_in = open('X.pickle', 'rb')
X = pickle.load(pickle_in)
pickle_in = open('y.pickle', 'rb')
y = pickle.load(pickle_in)
X = X/255.0

model = Sequential()
model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(64))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(X, y, batch_size=64, epochs=3, validation_split=0.3)

2020-04-16 23:15:02.420846: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-16 23:15:02.438037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: Quadro K5200 computeCapability: 3.5
coreClock: 0.771GHz coreCount: 12 deviceMemorySize: 7.94GiB deviceMemoryBandwidth: 179.05GiB/s
2020-04-16 23:15:02.438206: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-04-16 23:15:02.439862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-16 23:15:02.441466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-16 23:15:02.441717: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-16 23:15:02.443456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-16 23:15:02.444460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-16 23:15:02.448122: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-16 23:15:02.448136: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-04-16 23:15:02.448470: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-16 23:15:02.480562: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2394460000 Hz
2020-04-16 23:15:02.484972: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd3dc000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-16 23:15:02.484998: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-16 23:15:02.487117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-16 23:15:02.487134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Traceback (most recent call last):
  File "/home/dominik/PycharmProjects/TensorFlow/dog_cat/model.py", line 25, in <module>
    model.fit(X, y, batch_size=64, epochs=3, validation_split=0.3)
  File "/home/dominik/PycharmProjects/TensorFlow/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/dominik/PycharmProjects/TensorFlow/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 732, in fit
    data_adapter.train_validation_split((x, y, sample_weight),
  File "/home/dominik/PycharmProjects/TensorFlow/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", **line 1314, in train_validation_split
    raise ValueError(
ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found:** (array([[[[0.24705882],
         [0.3372549 ],
         [0.36078431],

**Comment by amahendrakar** [comment] 2020-04-17 10:51
@domindominik,
In order to reproduce the error, could you please share both the pickle files you are using in the code? Thanks!

**Comment by domindominik** [comment] 2020-04-17 11:37
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import random
import pickle
from tqdm import tqdm

DATADIR = '/home/dominik/PetImages'
CATEGORIES = ['Dog', 'Cat']

for category in CATEGORIES:
    path = os.path.join(DATADIR, category)
    for img in os.listdir(path):
        img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
        plt.imshow(img_array, cmap='gray')
        plt.show()
        break
    break
print(img_array.shape)

IMG_SIZE = 60
new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
plt.imshow(new_array, cmap='gray')
plt.show()

training_data = []

def create_training_data():
    for category in CATEGORIES:

        path = os.path.join(DATADIR, category)
        class_num = CATEGORIES.index(category)

        for img in tqdm(os.listdir(path)):
            try:
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass
create_training_data()

random.shuffle(training_data)

for sample in training_data:
    print(sample[1])
X = []
y = []

for features, label in training_data:
    X.append(features)
    y.append(label)

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

pickle_out = open('X.pickle', 'wb')
pickle.dump(X, pickle_out)
pickle_out.close()
pickle_out = open('y.pickle', 'wb')
pickle.dump(y, pickle_out)
pickle_out.close()

**Comment by meghasn** [comment] 2020-04-21 05:34
I got the same error and resolved it by changing y into a numpy array

**Comment by amahendrakar** [comment] 2020-04-22 06:53
@domindominik,
I was able to run the code without any issues with TF v2.2.0-rc3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0bde199280812170ec898e5f680127cc/38613.ipynb). Thanks!

**Comment by Dogus-1** [comment] 2020-04-22 15:01
> I got the same error and resolved it by changing y into a numpy array

I have no experience in coding, so can you show me how the code looks if you chance y into a numpy array?

**Comment by meghasn** [comment] 2020-04-24 12:20
sure y=np.array(y) this is the only change you have to make.I have attatched the code below.Since I am getting some issue while uploading the folder .I have added a screenshot below
![Screenshot (8)](https://user-images.githubusercontent.com/41339621/80211779-ede77d00-8653-11ea-9e86-c682f70dae22.png)

**Comment by convolutionalNN** [comment] 2020-04-26 07:29
To add to that, after making "y" an array, I had to append the labels in a different way to avoid a different error. Here's what I had:
![Conv Fix](https://user-images.githubusercontent.com/42564419/80300835-c9bf9500-8754-11ea-9369-c9ed67cf9c87.png)
I commented out the previous code that caused the post-numpy array-ization error.
This seemed to work on my custom dataset.

**Comment by Dogus-1** [comment] 2020-04-28 13:20
Thank you very much!! Very helpful.

**Comment by masterkenoobi5812** [comment] 2020-04-29 13:13
> I got the same error and resolved it by changing y into a numpy array

perfect

**Comment by amahendrakar** [comment] 2020-04-29 15:38
> I was able to run the code without any issues with TF v2.2.0-rc3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0bde199280812170ec898e5f680127cc/38613.ipynb). Thanks!

@domindominik,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment] 2020-05-06 04:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2020-05-06 04:47 UTC
Labels: TF 2.2, comp:keras, stat:awaiting response, type:support

**Comment by Raevel** [comment] 2020-05-06 13:22
I tried everything propose up here but nothing worked. 

Until i changed 'categorical_crossentropy' to 'sparse_categorical_crossentropy', in the compiling function.

Hope this will help someone.

**Comment by priyanshib22** [comment] 2020-05-21 09:54
I am still having issues.
please help..

error is:

Traceback (most recent call last):
  File "C:/Users/priyanshi burad/Desktop/color_train.py", line 29, in <module>
    model.fit(X,y,batch_size=32,validation_split=0.1)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 797, in fit
    shuffle=False))
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1338, in train_validation_split
    functools.partial(_split, indices=train_indices), arrays)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\nest.py", line 617, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\nest.py", line 617, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1335, in _split
    return array_ops.gather_v2(t, indices)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 4541, in gather_v2
    batch_dims=batch_dims)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 4524, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3755, in gather_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\priyanshi burad\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 0 is not in [0, 0) [Op:GatherV2]



I don't know how to resolve it.


my code is:

import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
D="C:\\Users\\priyanshi burad\\Desktop\\colour"
CATEGORIES=["red","blue","green"]

img_size=50
training_data = []
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(D,category)
        class_num=CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array=cv2.imread(os.path.join(path,img))
                img_size=50
                new_array=cv2.resize(img_array,(img_size,img_size))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
create_training_data()
print(len(training_data))



import random
random.shuffle(training_data)
for sample in training_data:
    print(sample[1])



X = []
y = []
y=np.array(y)
for features,label in training_data:
    X.append(features)
    np.array((y,label))
X = np.array(X).reshape(-1,img_size, img_size,1)



import pickle

pickle_out= open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out= open("y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()
pickle_in=open("X.pickle","rb")
X= pickle.load(pickle_in)
print(X[1])



import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten,Conv2D, MaxPooling2D
import pickle

X=pickle.load(open("X.pickle","rb"))
y=pickle.load(open("y.pickle","rb"))

X=X/255.0

model= Sequential()
model.add(Conv2D(64, (3,3), input_shape = X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=['accuracy'])

model.fit(X,y,batch_size=32,validation_split=0.1)

**Comment by amahendrakar** [comment] 2020-05-21 11:41
> I am still having issues.
> please help..

@priyanshib22,
Please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track it there. Thanks!

**Comment by ofirattia** [comment] 2020-10-11 14:18
> sure y=np.array(y) this is the only change you have to make.I have attatched the code below.Since I am getting some issue while uploading the folder .I have added a screenshot below
> ![Screenshot (8)](https://user-images.githubusercontent.com/41339621/80211779-ede77d00-8653-11ea-9e86-c682f70dae22.png)

After changing to array you will face range issues while doing the split.

**Comment by sruthisentil** [comment] 2020-11-16 03:35
I get a "IndexError: list index out of range" message on the model.fit(X, y, batch_size=5, epochs=3, validation_split=0.1). Did anybody else get this issue, and how do I fix this?

**Comment by amahendrakar** [comment] 2020-11-22 18:21
@sruthisentil,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by Zerpington** [comment] 2020-11-27 21:42
> 
> 
> I got the same error and resolved it by changing y into a numpy array

This one worked ^^

**Comment by Hedibouchelliga** [comment] 2020-12-07 09:58
import numpy as np
X = np.array(X)
y= np.array(y)
that will change your X,y  to numpy arrays and solve the problem
this would be also done just before feeding your neural network to make sure that the NN received numpy arrays

**Comment by ikram-hamizi** [comment] 2021-04-19 19:13
My answer is not related to your issue since you used Sequential. But this could be helpful to others.

I got the same error when I used the Keras functional API. _I **named both my NN outputs and my training set `x`** by mistake._

So the trainset **`x`** was overwritten by the NN output **`x`** which made it of type:
`tensorflow.python.keras.engine.keras_tensor.KerasTensor` 

and resulted in this error:
`# ValueError:  ``validation_split`` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'tensorflow.python.keras.engine.keras_tensor.KerasTensor'>]`

**Comment by DebottamMajilla** [comment] 2021-08-16 08:02
> My answer is not related to your issue since you used Sequential. But this could be helpful to others.
> 
> I got the same error when I used the Keras functional API. _I **named both my NN outputs and my training set `x`** by mistake._
> 
> So the trainset **`x`** was overwritten by the NN output **`x`** which made it of type:
> `tensorflow.python.keras.engine.keras_tensor.KerasTensor`
> 
> and resulted in this error:
> `` # ValueError: ``validation_split`` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'tensorflow.python.keras.engine.keras_tensor.KerasTensor'>] ``


**You can solve this by converting the y to array ,then drop into the y to y.pickle file**

X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y = np.array(y)

**Comment by DebottamMajilla** [comment] 2021-08-16 08:06
**80% + percent validation accuracy achieved by increasing feature map to 128 and using more epoch (=5)**

_use below model_

model = Sequential()

model.add( Conv2D(64, (3, 3), input_shape=X.shape[1:]) )
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

m=model.fit(X, y, batch_size=32, epochs=5, validation_split=0.1)
