### ISSUE TITLE
Unable to use canned RNN Estimator

### ISSUE THREAD

**Issue by dippynark** [tensorflow/tensorflow#30456] opened 2019-07-07 09:29 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): not really (very close to stock example [here](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/RNNEstimator))
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Version 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip (from binary?)
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

`TypeError: Input must be a SparseTensor.` when using [RNNEstimator](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/RNNEstimator).

**Describe the expected behavior**

No errors when used correctly (maybe that is the issue).

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf

sequence_feature_colums = [tf.contrib.feature_column.sequence_numeric_column("test")]

estimator = tf.contrib.estimator.RNNEstimator(
    head=tf.contrib.estimator.regression_head(),
    sequence_feature_columns=sequence_feature_colums)

def input_fn_train():
  dataset = tf.data.Dataset.from_tensor_slices(({"test": [0]}, [0]))
  dataset = dataset.batch(1)
  return dataset

estimator.train(input_fn=input_fn_train, steps=1)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rmothukuru** [comment] 2019-07-08 12:52
Could reproduce the issue with TF Version 1.14.

**Comment by qlzh727** [comment] 2019-07-24 04:26
@arthurarg who worked on RNN esitmator

**Comment by qlzh727** [comment] 2019-07-24 04:27
Also, just FYI, contrib is going away in tf 2.0, and we are not actively fixing anything in contrib.

**Comment by arthurarg** [comment] 2019-07-24 18:45
The input tensor needs to be a sparse tensor, and you need to specify the
number of cells. The following code should work:
```

sequence_feature_colums =
[tf.contrib.feature_column.sequence_numeric_column("test")]

estimator = tf.contrib.estimator.RNNEstimator(
num_units=[3],
head=tf.contrib.estimator.regression_head(),
sequence_feature_columns=sequence_feature_colums)

def input_fn_train():
dataset = tf.data.Dataset.from_tensor_slices((
{"test": tf.SparseTensorValue([[0, 0]], [0.], (1, 1))},
[0]))
dataset = dataset.batch(1)
return dataset

estimator.train(input_fn=input_fn_train, steps=1)
```

**Comment by gadagashwini** [comment] 2019-08-07 09:59
@dippynark Did @arthurarg's solution helped you to resolve this issue? Thanks!

**Comment by tensorflowbutler** [comment] 2019-08-22 12:32
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gadagashwini** [comment] 2019-08-23 07:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-23 07:02 UTC
Labels: TF 1.14, comp:apis, contrib, stat:awaiting response, type:bug
