### ISSUE TITLE
Array mul  lacking min/max data

### ISSUE THREAD

**Issue by raninbowlalala** [tensorflow/tensorflow#22138] opened 2018-09-07 03:18 UTC
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:N/A
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.10.1
- **Python version**:2.7.3
- **Bazel version (if compiling from source)**:0.12.0
- **GCC/Compiler version (if compiling from source)**:c++11
- **CUDA/cuDNN version**:7.5.18
- **GPU model and memory**:TITAN,12GB
- **Exact command to reproduce**:
 ./bazel-bin/tensorflow/contrib/lite/python/tflite_convert --output_file=~/foo.cc   --graph_def_file!/frozen_inference_graph.pb   --inference_type=QUANTIZED_UINT8   --input_arrays=Imageholder --output_arrays=ResizeBilinear_2   --mean_values=127.5   --std_dev_values=127.5

### Describe the problem

I modified deeplabv3+(mobilenetv2) model, and train/eval a quantized model with "tf.contrib.quantize.create_training_graph(quant_delay=0)
 tf.contrib.quantize.create_eval_graph". The graph show as below:

Placeholder->mul->sub->mobilenetv2

When I convert this frozen model to tflite quantized model, I use input_node = Placeholer. There are error occurred. Does any one know how to solve this problem?

### Source code / logs

2018-09-07 10:59:40.172018: F tensorflow/contrib/lite/toco/tooling_util.cc:1635] Array mul, which is an input to the Sub operator producing the output array sub, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
tf.estimator package not installed.
Aborted (core dumped)

**Comment by jdduke** [comment] 2018-09-07 21:30
Over to Suharsh to advise.

**Comment by suharshs** [comment] 2018-09-20 14:31
The issue is that the contrib/quantize rewriter is not very robust to any arbitrary model yet. In particular the Mul and Sub at the start of your network need quantization information for TOCO. This can be resolved by either manually adding a FakeQuantWithMinMaxVars node after mul and sub, see how the rewriter does it: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantize/python/quantize.py#L475

That being said this can be complicated, if you goal is to just get a smaller and faster model, I recommend trying the --post_training_quantize flag to tflite_convert. With that you keep the inference_type=FLOAT and pass a *floating point* version of your model (no need to call the contrib/quantize tool). That may provide sufficient speedup for your use case.

**Comment by tensorflowbutler** [comment] 2018-10-05 19:09
Nagging Assignee @suharshs: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-10-15 17:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-10-15 17:09 UTC
Labels: comp:lite

**Comment by hufenghufeng** [comment] 2019-02-12 02:33
In feature_extractor.py, there is a function named '_preprocess_zero_mean_unit_range'. 'return (2.0 / 255.0) * tf.to_float(inputs) - 1.0' here will cause this problem. Make this function do nothing, just return the input and declare the input as  'input_image = tf.placeholder(tf.float32, [1, None, None, 3], name=_INPUT_NAME)' will help

**Comment by NEU-Gou** [comment] 2019-04-25 09:14
@suharshs I'm facing the similar problem due to a layer consistent with several basic tensorflow ops (like Add, Mul, Sigmoid, etc.) Is there any update on the contrib/quantize tool? Or we still have to manually add FakeQuantWithMinMaxVars? 
Thanks!

**Comment by 406747925** [comment] 2019-05-09 02:04
> The issue is that the contrib/quantize rewriter is not very robust to any arbitrary model yet. In particular the Mul and Sub at the start of your network need quantization information for TOCO. This can be resolved by either manually adding a FakeQuantWithMinMaxVars node after mul and sub, see how the rewriter does it: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantize/python/quantize.py#L475
> 
> That being said this can be complicated, if you goal is to just get a smaller and faster model, I recommend trying the --post_training_quantize flag to tflite_convert. With that you keep the inference_type=FLOAT and pass a _floating point_ version of your model (no need to call the contrib/quantize tool). That may provide sufficient speedup for your use case.

I'm wondering how to manually adding a FakeQuantWithMinMaxVars node. I've looked into the link you provided and still cannot find that code .
