### ISSUE TITLE
Calculating Gradients Through tf.complex64 Numbers

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#2255] opened 2016-05-06 19:09 UTC
Hey TF,

Its very nice that you support so many complex number calculations like `tf.complex_abs` and `fft`. I am trying replicate this [Associative LSTM paper ](http://arxiv.org/abs/1602.03032)where complex numbers are needed. 

However, when I try to calculate the gradient using `tf.gradient`, I get the traceback below. Is it not possible to calculate the gradient if complex numbers are used with type `tf.complex64`? If not, this would be an incredibly useful feature as there are several new RNN papers that require complex numbers to be used. 

I am initializing a `tf.complex64` dtype weight matrix as follows:
```python
      if complex_weights: 
        a = tf.truncated_normal([total_arg_size, output_size], stddev=0.1)
        weight_matrix = tf.Variable(tf.complex(a,a), name="Complex_Weight")
```

Perhaps I'm missing something or not writing the code properly. I have TF 0.8 installed. 

```python
    gradients = tf.gradients(self.average_mean_loss, params)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py", line 481, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py", line 414, in _DivGrad
    return (array_ops.reshape(math_ops.reduce_sum(grad / y, rx), sx),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 526, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py", line 94, in _IndexedSlicesToTensor
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1759, in unsorted_segment_sum
    num_segments=num_segments, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 486, in apply_op
    _Attr(op_def, input_arg.type_attr))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 59, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: DataType complex64 for attr 'T' not in list of allowed values: float32, float64, int32, int64, uint8, int16, int8, uint16```

**Comment by mrry** [comment] 2016-05-16 16:48
Re-assigning this to @yuanbyu, who knows the current gradients code best, and would be able to estimate the changes needed. (I suspect that this would require a considerable amount of work to update the existing gradient functions, which may have latent assumptions about expecting `tf.float32` or `tf.float64` values.)

**Comment by LeavesBreathe** [comment] 2016-05-16 18:34
Thanks @mrry 

Here's the full situation. TensorFlow has operations such as batch_ifft which only accept complex64 numbers. To implement papers like unitary RNN's http://arxiv.org/abs/1511.06464, we need these transforms. 

We also need to operate in the complex domain. Now you can simulate imaginary numbers with float32 numbers, but still -- we can't use FFT's which is a critical piece. 

There are many other networks that use complex numbers like Associative LSTMs which could receive significant speed boosts if complex64 could be backproped. Thanks!

**Comment by ibab** [comment] 2016-05-19 09:07
Hi, I'm a bit surprised about this issue, as it seems that calculating gradients for expressions involving `complex64` seems to work, even if `tf.fft` is involved.
Maybe it's a specific op that hasn't been extended to `complex64` yet that's causing the problem?

```python
import tensorflow as tf
x = tf.linspace(0., 1., 10)
z = tf.complex(x, x)
expr = tf.reduce_sum(tf.complex_abs(tf.fft(z)))
print(s.run(tf.gradients(expr, x)))
```
```
[array([ -7.51478004e+00,  -1.36133647e+00,   1.19209290e-07,
         6.93636179e-01,   1.19022393e+00,   1.63820338e+00,
         2.13479161e+00,   2.82842731e+00,   4.18976402e+00,
         1.03432074e+01], dtype=float32)]
```

**Comment by LeavesBreathe** [comment] 2016-05-19 18:01
I have been using a gpu as well but I do run other operations like `tf.embedding_lookup` which do require cpu operations. I was very careful to check that all calculations I do accept `complex64` and this error only happens upon compilation.

I use float32 for the majority of operations, but i use complex64 within the RNN and then convert the output back to float32. This would be a critical issue for RNN's that use imaginary numbers as described above.

**Comment by stevenhutt** [comment] 2016-05-22 22:41
As a temporary solution you could replace the FFT with a DFT. More memory and slower, but at least you can replicate the paper.

**Comment by stevenhutt** [comment] 2016-05-22 22:43
As a temporary solution you could use DFT instead of FFT. Slower but will allow you to replicate the paper.

**Comment by khaotik** [comment] 2016-05-29 01:36
I'm trying to implement unitary RNN and I have the exactly same issue. It appears TF can't calculate gradient complex through transpose op. But otherwise complex gradient works well.

        out_ = vec_in * diag0
        refl0 = normalize_c(refl0)
        refl1 = normalize_c(refl1)
        out_ = refl_c(math_ops.batch_fft(out_)*fft_scale,refl0)
        out_ = diag1 * tf.transpose(tf.gather(tf.transpose(out_), perm0))
        #above line works if changed to out_=diag1 * out_
        out_ = diag2 * refl_c(math_ops.batch_ifft(out_)*fft_scale, refl1)

Error message:

	File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 481, in gradients
		in_grads = _AsList(grad_fn(op, *out_grads))
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_grad.py", line 260, in _TransposeGrad
		return [array_ops.transpose(grad, array_ops.invert_permutation(p)), None]
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 694, in transpose
		ret = gen_array_ops.transpose(a, perm, name=name)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1905, in transpose
		result = _op_def_lib.apply_op("Transpose", x=x, perm=perm, name=name)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/op_def_library.py", line 455, in apply_op
		as_ref=input_arg.is_ref)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
		ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 94, in _IndexedSlicesToTensor
		name=name)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2147, in unsorted_segment_sum
		num_segments=num_segments, name=name)
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/op_def_library.py", line 530, in apply_op
		_Attr(op_def, input_arg.type_attr))
	  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/op_def_library.py", line 61, in _SatisfiesTypeConstraint
		", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
	TypeError: DataType complex64 for attr 'T' not in list of allowed values: float32, float64, int32, int64, uint8, int16, int8, uint16, float16

**Comment by ibab** [comment] 2016-05-29 13:02
Looks like the problem is that `tf.unsorted_segment_sum` is only enabled for real number types.
Seeing as `tf.reduce_sum` does work for complex numbers, I would say that `tf.unsorted_segment_sum` (and `_prod`) should also be enabled for consistency.

**Comment by ibab** [comment] 2016-05-29 14:19
I've submitted a PR that enables complex numbers for the segment reduction ops.
If this gets merged, @khaotik and @LeavesBreathe should have another look at whether their model runs using the current `master`.

**Closed** 2016-05-29 20:29 UTC

**Comment by ibab** [comment] 2016-05-29 20:58
@khaotik and @LeavesBreathe: The PR has been merged. It would be great if you could test your model with the latest `master`.

**Comment by LeavesBreathe** [comment] 2016-05-30 00:35
@ibab thanks for the update. I was using the transpose op as well, so this is probably what was causing the issue. I'm in the middle of testing other architectures right now, but when I get a chance, i will test the Unitary RNN  and Associative LSTM and post back. I will build from the current master.

**Comment by LeavesBreathe** [comment] 2016-06-10 14:14
@ibab thanks for your pull as it did resolve the `tf.transpose` issue that was occuring. However, a new issue has arisen. When I `optimizer.apply_gradients()`, I get the following error message:

gradient code:
```python
         params = tf.trainable_variables()
          gradients = tf.gradients(self.losses[b], params) #aggregation_method = 2
          for i, grad in enumerate(gradients):
            if grad is not None and grad.dtype.name != 'complex64':
              gradients[i] = tf.clip_by_norm(grad, max_gradient_norm)


        self.gradient_norms.append(norm)
        self.updates.append(opt.apply_gradients(
            zip(gradients, params), global_step=self.global_step))
```


```python
Traceback (most recent call last):
  File "train_seq2seq.py", line 778, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train_seq2seq.py", line 775, in main
    train()
  File "train_seq2seq.py", line 393, in train
    model = create_model(sess, False)
  File "train_seq2seq.py", line 328, in create_model
    description_text = description_text)
  File "/home/nick/Project_RNN_Enhancement/rnn_enhancement/seq2seq_model_enhanced.py", line 305, in __init__
    zip(gradients, params), global_step=self.global_step))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 291, in apply_gradients
    self._assert_valid_dtypes([g, v])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 365, in _assert_valid_dtypes
    dtype, t.name, [v for v in valid_dtypes]))
ValueError: Invalid type tf.complex64 for gradients/model_with_buckets/embedding_attention_seq2seq/RNN/MultiRNNCell/Cell0/AssociativeBasicLSTMCell/gate_multiplication/Enhanced_Linear/MatMul_grad/MatMul_1:0, expected: [tf.float32, tf.float64, tf.float16].
```


Basically, there are both complex64 and float32 trainable variables that I have in the `seq2seq.py` which is based upon tensorflow's `seq2seq.py`. These trainable variables enter the params argument in `apply_gradients`.

Is there a problem when you use trainable variables of both `float32` and `complex64` types? I really appreciate your help. I'm running rc version 0.9.

**Comment by ibab** [comment] 2016-06-10 15:08
That's strange, as MatMul has support for `complex64`, although only on the CPU.
Maybe you are somehow forcing the op to execute on the GPU?
Currently complex support is a bit poor for GPU ops, as discussed in this issue: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/matmul_op.cc#L219

**Comment by LeavesBreathe** [comment] 2016-06-10 16:53
Thanks again @ibab -- can't believe I didn't think of that. I'll try that out and get back to you with results.

**Comment by LeavesBreathe** [comment] 2016-06-11 01:12
Reporting back to @ibab  -- I tried `tf.complex(var,var)` and unfortunately it produced the same error as above. I looked at your crossed out message and I am running this on a titan x -- so this could be the problem. Here's my weight matrix code:

```python
  with tf.variable_scope(scope or "Enhanced_Linear"):
  #this will make a class for these variables so you can reference them in the future. 

    '''initialize weight matrix properly'''
    if weight_initializer == "uniform_unit":
      matrix = tf.get_variable("Uniform_Matrix", [total_arg_size, output_size], initializer = tf.uniform_unit_scaling_initializer()) 
    elif weight_initializer == "truncated" or weight_initializer == "truncated_uniform":
      if complex_weights: 
        real_w = tf.Variable(tf.truncated_normal([total_arg_size, output_size], stddev=0.1), name = "complex_weight_real")
        imag_w = tf.Variable(tf.truncated_normal([total_arg_size, output_size], stddev=0.1), name = "complex_weight_imag")
        matrix = tf.complex(real_w, imag_w)
```

**Comment by ibab** [comment] 2016-06-11 22:26
My guess is that the problem is caused by some of the gradients being complex.
If you post your loss function, I might be able to help.
Alternatively, you could post this to StackOverflow, as people there are usually very quick at responding to tensorflow questions (and it might be more appropriate, as I suspect that this isn't a bug in tensorflow).

**Comment by LeavesBreathe** [comment] 2016-06-12 18:51
@ibab, the loss function is the seq2seq sequence loss function from tensorflow ops:

```python 
def sequence_loss_by_example(logits, targets, weights,
                             average_across_timesteps=True,
                             softmax_loss_function=None, name=None):
  """Weighted cross-entropy loss for a sequence of logits (per example).
  Args:
    logits: List of 2D Tensors of shape [batch_size x num_decoder_symbols].
    targets: List of 1D batch-sized int32 Tensors of the same length as logits.
    weights: List of 1D batch-sized float-Tensors of the same length as logits.
    average_across_timesteps: If set, divide the returned cost by the total
      label weight.
    softmax_loss_function: Function (inputs-batch, labels-batch) -> loss-batch
      to be used instead of the standard softmax (the default if this is None).
    name: Optional name for this operation, default: "sequence_loss_by_example".
  Returns:
    1D batch-sized float Tensor: The log-perplexity for each sequence.
  Raises:
    ValueError: If len(logits) is different from len(targets) or len(weights).
  """
  if len(targets) != len(logits) or len(weights) != len(logits):
    raise ValueError("Lengths of logits, weights, and targets must be the same "
                     "%d, %d, %d." % (len(logits), len(weights), len(targets)))
  with ops.op_scope(logits + targets + weights, name,
                    "sequence_loss_by_example"):
    log_perp_list = []
    for logit, target, weight in zip(logits, targets, weights):
      if softmax_loss_function is None:
        # TODO(irving,ebrevdo): This reshape is needed because
        # sequence_loss_by_example is called with scalars sometimes, which
        # violates our general scalar strictness policy.
        target = array_ops.reshape(target, [-1])
        crossent = nn_ops.sparse_softmax_cross_entropy_with_logits(
            logit, target)
      else:
        crossent = softmax_loss_function(logit, target)
      log_perp_list.append(crossent * weight)
    log_perps = math_ops.add_n(log_perp_list)
    if average_across_timesteps:
      total_size = math_ops.add_n(weights)
      total_size += 1e-12  # Just to avoid division by 0 for all-0 weights.
      log_perps /= total_size
  return log_perps


def sequence_loss(logits, targets, weights,
                  average_across_timesteps=True, average_across_batch=True,
                  softmax_loss_function=None, name=None):
  """Weighted cross-entropy loss for a sequence of logits, batch-collapsed.
  Args:
    logits: List of 2D Tensors of shape [batch_size x num_decoder_symbols].
    targets: List of 1D batch-sized int32 Tensors of the same length as logits.
    weights: List of 1D batch-sized float-Tensors of the same length as logits.
    average_across_timesteps: If set, divide the returned cost by the total
      label weight.
    average_across_batch: If set, divide the returned cost by the batch size.
    softmax_loss_function: Function (inputs-batch, labels-batch) -> loss-batch
      to be used instead of the standard softmax (the default if this is None).
    name: Optional name for this operation, defaults to "sequence_loss".
  Returns:
    A scalar float Tensor: The average log-perplexity per symbol (weighted).
  Raises:
    ValueError: If len(logits) is different from len(targets) or len(weights).
  """
  with ops.op_scope(logits + targets + weights, name, "sequence_loss"):
    cost = math_ops.reduce_sum(sequence_loss_by_example(
        logits, targets, weights,
        average_across_timesteps=average_across_timesteps,
        softmax_loss_function=softmax_loss_function))
    if average_across_batch:
      batch_size = array_ops.shape(targets[0])[0]
      return cost / math_ops.cast(batch_size, dtypes.float32)
    else:
      return cost

```
I can post on this on Overflow, but I do believe it is a bug. I think inherently some of the gradients are complex because i'm doing several complex computations for the associative LSTM (and likewise would be doing the same for the unitary RNN). 

Associative LSTM paper
https://arxiv.org/abs/1602.03032

Here is an example of part of the cell:

```python 
        '''in_gate, out_gate, forget_gate have dim/2 each'''
        with tf.variable_scope("gate_multiplication"):
          concat = lfe.enhanced_linear([inputs, prev_state], int(1.5 * self._num_units), True, weight_initializer = self._weight_initializer, complex_weights = True)
          in_gate, out_gate, forget_gate = tf.split(1, 3, concat)
          in_gate, out_gate, forget_gate = tf.sigmoid(in_gate), tf.sigmoid(out_gate), tf.sigmoid(forget_gate + self._forget_bias)

        with tf.variable_scope("key_multiplication"):
          #in_key, out_key, and u are double the size -- 3 units
          concat = lfe.enhanced_linear([inputs, prev_state], int(1.5 * self._num_units), True, weight_initializer = self._weight_initializer, complex_weights = True)
          in_key, out_key, u = tf.split(1, 3, concat)
          in_key, out_key, u = self.bound(in_key), self.bound(out_key), self.bound(u) #dimension might need to be higher here

        #B = Batch size F = dimension size
        # B x F --> C x B x F
        in_keys = self.permute(in_key)
        # B x F --> C x B x F
        out_keys = self.permute(out_key)

        '''equation 27 -- forming next_cells'''
        f_x_c = tf.expand_dims(forget_gate,0) * c #takes on shape of c
        print('u\n', u)
        print('in_gate\n',in_gate)
        i_x_u = tf.expand_dims(in_gate * u,0) 
        next_cells = f_x_c + self.complex_mult(in_keys, i_x_u)
```

I guess my question is: are complex gradients possible? And if not, can these be implemented in soon? There are many applications that complex gradients would immensely benefit from. Currently non-complex versions take far longer to run in tensorflow and its very inefficient.

**Comment by ibab** [comment] 2016-06-12 20:18
Note that the gradient of a complex expression can be complex, even if the variables that you take the derivative with respect to are real.
For example, the derivative of `(1 + 1j * x)` with regard to `x` is `1j`, even if `x` is a real parameter.
That means you have to explicitly make sure that all expressions that you differentiate are real.
Unfortunately, the associative LSTM paper doesn't seem to explain how they've taken this into account Maybe I have to read it more carefully.

That said, I just tried running the following code:
```
import tensorflow as tf

s = tf.Session()
x = tf.placeholder(tf.float32)
z1 = tf.complex(0., x)

print(s.run(tf.gradients(z, [x]), feed_dict={x: 1}))
```
and it prints out `[0.]`, which seems wrong to me (I expected `[0 + 1j]`).
My guess is that the gradient code only returns the real part of a complex gradient, if the variable that we differentiate by is real. I'll open a bug report on this.

**Comment by LeavesBreathe** [comment] 2016-06-13 14:05
Thanks @ibab -- the Associative LSTM paper was done in Theano and their code is here. They do not use any complex variables, but rather simulate it with real ones. This can be done in tensorflow as well, but for unitary RNN's this can not be done since the `ifft` args require complex inputs.

https://github.com/mohammadpz/Associative_LSTM

Basically the main issue with using non-complex variables is that the implementation is much slower. If complex gradients could be handled, this would be a major advantage for tensorflow, and would open many doors.

**Comment by khaotik** [comment] 2016-06-14 01:20
@LeavesBreathe In my TF unitary RNN implementation, I had real and complex parameters, and my cost function was real. It seems working well. However I'm not sure if the above "cast away imag part gradient" runtime issue occurred in my implementation.

```python
from math import sqrt

import numpy as np

import tensorflow as tf
from tensorflow.python.ops import variable_scope as vs
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn_ops

rnn_cell = tf.nn.rnn_cell
seq2seq = tf.nn.seq2seq

def complex_mul_real( c, r ):
    return tf.complex(tf.real(c)*r, tf.imag(c)*r)


def refl_c(in_, normal_):
    normal_rk2 = tf.expand_dims( normal_, 1 )
    scale = 2*tf.matmul( in_, tf.conj( normal_rk2 ) )
    return in_ - tf.matmul(scale, tf.transpose(normal_rk2))


def complex_abs_sq(z):
    return tf.real(z)*tf.real(z) + tf.imag(z)*tf.imag(z)


def normalize_c(in_):
    norm = tf.sqrt(tf.reduce_sum(complex_abs_sq(in_)))
    scale = 1./(norm + 1e-5)
    return complex_mul_real( in_, scale )


def get_complex_variable( name, scope, shape ):
    re, im = vs.get_variable(name+'_re', shape=shape), vs.get_variable(name+'_im', shape=shape)
    return tf.complex(re,im, name=name)


'''multiply complex vector by parameterized unitary matrix'''
def ulinear(vec_in, out_size, scope=None):
    shape = vec_in.get_shape().as_list()
    if len(shape) != 2:
        raise ValueError( 'argument vec_in must be a batch of vectors (2D tensor)' )
    in_size = shape[1]
    fft_scale = 1./sqrt(out_size)
    with vs.variable_scope(scope or 'ULinear') as _s:
        diag0 = get_complex_variable('diag0', _s, shape=[out_size])
        diag1 = get_complex_variable('diag1', _s, shape=[out_size])
        diag2 = get_complex_variable('diag2', _s, shape=[out_size])
        refl0 = get_complex_variable('refl0', _s, shape=[out_size])
        refl1 = get_complex_variable('refl1', _s, shape=[out_size])
        perm0 = tf.constant(np.random.permutation(out_size), name='perm0',dtype='int32')
        out_ = vec_in * diag0
        refl0 = normalize_c(refl0)
        refl1 = normalize_c(refl1)
        out_ = refl_c(math_ops.batch_fft(out_)*fft_scale,refl0)
        out_ = math_ops.batch_fft(out_)*fft_scale
        out_ = diag1 * tf.transpose(tf.gather(tf.transpose(out_), perm0))
        #out_ = diag1 * out_
        out_ = diag2 * refl_c(math_ops.batch_ifft(out_)*fft_scale, refl1)
        #out_ = diag2 * math_ops.batch_ifft(out_)*fft_scale
        return out_


def modReLU(in_c, bias, scope=None):
    with vs.variable_scope(scope or "ULinear"):
        n = tf.complex_abs(in_c)
        scale = 1./(n+1e-5)
    return complex_mul_real(in_c, ( nn_ops.relu(n+bias)*scale ))


def abssigm(in_c, scope=None):
    with vs.variable_scope(scope or 'ULinear'):
        re,im = tf.real(in_c), tf.imag(in_c)
        scale = 1./tf.sqrt(re*re + im*im + 1.)
    return complex_mul_real(in_c,scale)


class URNNCell(rnn_cell.RNNCell):
    def __init__(self, num_units, input_size=None):
        self._num_units = num_units
        self._input_size = num_units if input_size==None else input_size

    @property
    def input_size(self):
        return self._input_size

    @property
    def output_size(self):
        return self._num_units

    @property
    def state_size(self):
        return self._num_units

    def __call__(self, inputs, state, scope=None ):
        with vs.variable_scope(scope or type(self).__name__):
            mat_in = vs.get_variable('mat_in', [self.input_size, self.state_size*2])
            mat_out = vs.get_variable('mat_out', [self.state_size*2, self.output_size])
            in_proj = math_ops.matmul(inputs, mat_in)
            in_proj_c = tf.complex( in_proj[:, :self.state_size], in_proj[:, self.state_size:] )
            out_state = modReLU( in_proj_c + 
                ulinear(state, self.state_size),
                vs.get_variable(name='bias', dtype=tf.float32, shape=[self.state_size]),
                scope=scope)
            '''
            out_state = abssigm( in_proj_c +
                                ulinear(state, self.state_size),
                                scope=scope )
            '''
            out_ = math_ops.matmul( array_ops.concat(1,[tf.real(out_state), tf.imag(out_state)] ), mat_out)
        return out_, out_state
```

**Comment by LeavesBreathe** [comment] 2016-06-14 22:49
@khaotik thanks for sharing your unitary code. I have a similar script for unitary. I think as the implementation stands right now, the gradient you're processing from your Unitary Cell is not correct as @ibab illustrated with his newly raised issue. 

---
Completely on the side (and we can start a separate thread for this) but I do have some questions about your unitary implementation. 

1. Why do you multiply 3 separate times by `fft_scale` -- in the original paper this is not called for.
2. Your `diag` variables do not appear to be diagonal, but rather normal complex matrices. 
3. In your `modrelu` function you multiply by `in_c`. From my impression, the paper simply uses as `modrelu` as an activation function and do not multiply the output by `in_c`.

**Comment by ibab** [comment] 2016-06-14 22:59
The issue with casting away the imaginary part of the gradient shouldn't affect either of you.
It only seems to affect the final result that's returned by `tf.gradients`, not any of the intermediate computations. If your gradients are all real (as they should be if you want to run an optimization), then you won't have any issues with this.

**Comment by LeavesBreathe** [comment] 2016-06-14 23:09
@ibab maybe I'm misunderstanding something here. In both the Associative LSTM and Unitary, there are intermediate complex calculations that are called for. How could all gradients be real if there are complex calculations occurring? 

I understand that you can initialize all the trainable variables with `tf.complex(var1, var2)`. However, when I run the `tf.gradient` function on a real cost function, some of the gradients are indeed `dtype` `complex64`. Mathematically, this makes sense as well since the gradient had to flow through complex calculations for each of the trainable variables. 

Perhaps I'm missing something here, but it seems clear that complex gradients need to be established before either of these two types of RNN's can work.

**Comment by ibab** [comment] 2016-06-14 23:24
If both the function that you are computing and the variables that you differentiate with respect to are real, then the gradients must be real, even if there were intermediate complex calculations involved.
You can see this from the following argument:
 - If both the differentiated function and the variables are real, then we can construct a fully real function by simply keeping track of the real and imaginary part separately
 - The gradient of such a real function must necessarily be real (as there were no complex calculations involved)
 - Because the real version of our function produces identical results to the original (complex) one, the gradients of the two functions must be the same, and therefore they must be real.

Apart from that, it looks like `tf.gradients` only returns complex numbers if the diff variables are complex at the moment. 
Maybe some of the variables that you differentiate by are still complex?

**Comment by khaotik** [comment] 2016-06-15 01:07
@LeavesBreathe
> Why do you multiply 3 separate times by fft_scale -- in the original paper this is not called for.

My bad. One line in the code is supposed to be commented out, already edited. There should be only one FFT/IFFT pair.
As for why I multiply `fft_scale`, is due to TF's FFT is not a normalized FFT, it will scale the norm of the vector being FFTed. For example:
```python
print(raw_fft( [1.,1.] )) #[2.,0.]
print(normalized_fft([1., 1.]) #[1.4142, 0.]
```

> Your `diag` variables do not appear to be diagonal, but rather normal complex matrices.

They are diagonal.
If you multiply (NOT `matmul`) tensor `x` of shape `[4]` with tensor `y` of shape `[100,4]`, you get broadcasted multiplication in TF, which is equivalent to `matmul( y, diag(x) )`.

> In your `modrelu` function you multiply by `in_c`. From my impression, the paper simply uses as `modrelu` as an activation function and do not multiply the output by `in_c`

`modrelu`, by design, changes the abs of input complex number to its ReLU-ed value while keeping phase intact. My `modReLU` does this: Calculated ReLU-ed abs, then multiply it by normalized input complex number. This is consistent with original paper.

**Comment by LeavesBreathe** [comment] 2016-06-15 04:04
> Apart from that, it looks like tf.gradients only returns complex numbers if the diff variables are complex at the moment. 
Maybe some of the variables that you differentiate by are still complex?

@ibab  You could be right. I will carefully analyze all of my `trainable variables` and ensure that they are all real.

Thank you very much for the comprehensive mathematical explanation for gradient understanding. Makes much more sense to me now. 

----

@khaotik 

Apologies for some of my misunderstandings. Makes complete sense how your variables are indeed diagonal. Really clever how you avoided wasting memory for the diagonal matrix.

Thanks for the `fft_scale` explanation. Its logical that you only want this multiplication to occur twice, before it enters `batch_fft` and after its inverse `batch_ifft`. 

Your `mod_relu` implementation is completely correct. I just did not notice the `z` in the numerator which is what threw me off (don't know how I missed that). Will go back through my implementation and make the correction. We should either push your or mine implementation to TensorFlow so others have it. 

I'll also try stacking multiple layers of the uRNN and see how they do. I've heard that uLSTM is also very powerful, but hasn't been published yet. 

Will post back with findings a few days from now as I am away from my gpu's at the moment.

**Comment by khaotik** [comment] 2016-06-15 10:57
@LeavesBreathe Thanks for improving my code. I just put the new code in a new [repo](https://github.com/khaotik/char-rnn-tensorflow), which is a fork of [char-rnn-tensorflow](https://github.com/sherjilozair/char-rnn-tensorflow). Feel free doing experiments or contributing.
