### ISSUE TITLE
Re-initializing backends on demand

### ISSUE THREAD

**Issue by kaushikb11** [tensorflow/tensorflow#50144] opened 2021-06-08 11:56 UTC
**Describe the current behavior**

While using Jax, I have a use case where I wish to control the CPU devices being used based on `num_devices` input. But this couldn't be changed once the backend has been initialized.

```python
>>> import os
>>> import jax
>>> from jax.lib import xla_bridge
>>> from jaxlib import xla_client
>>> print(jax.devices("cpu"))
[CpuDevice(id=0)]
>>> os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8"
>>> print(xla_client.get_local_backend("cpu").devices())
[CpuDevice(id=0)]
```

**Describe the expected behavior**

I wish to re-initialize the backend and the new backend pick up the env variables, and return 8 CPU devices in the above example.

**Comment by sachinprasadhs** [comment] 2021-06-11 06:41
Hi, Looks like the issue is related to Jax, since [Jax](https://github.com/google/jax/issues) has a separate repository, you can raise the issue there and close the issue here.

**Closed** 2021-06-17 07:31 UTC
Labels: comp:xla, type:bug, type:others
