### ISSUE TITLE
Empty step_stats from context.export_run_metadata() in TF 2.1

### ISSUE THREAD

**Issue by dtim1985** [tensorflow/tensorflow#36314] opened 2020-01-29 14:14 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab

As sessions are no more available in TF 2 API we are using `context.enable_run_metadata()` and `context.export_run_metadata()` to accure `run_metadata.step_stats` which then we feed to `timeline.Timeliner` to export tracing information about session execution and visualise it usgin chrome://tracing. This approch worked well with TF 2.0 but once we updated to 2.1 `run_metadata.step_stats` appears to be empty.

Here is code which acquires and prints step stats:
TF 2.0: https://colab.research.google.com/drive/1Jsk7Dn_gTd3xCTTxgQPx3bJvza4oRu1t
TF 2.1: https://colab.research.google.com/drive/1JQ7rqyH5VOAmpHbjMuLGYLwU9dJ7xwk2

I know that according to docs we should use `summary.trace_on` or `profiler_client .start_tracing` to acquire tracing information, however, there is seems an issue with GPU tracing https://github.com/tensorflow/tensorflow/issues/34844

**Comment by amahendrakar** [comment] 2020-01-30 11:40
Was able to reproduce the issue with [TF 2.0](https://colab.sandbox.google.com/gist/amahendrakar/3dab2da9961c6834738404f87f7f4deb/36314_2-0.ipynb), [TF 2.1](https://colab.sandbox.google.com/gist/amahendrakar/b8b246d084c420e8ef224879dc45182d/36314_2-1.ipynb) and [TF nightly](https://colab.sandbox.google.com/gist/amahendrakar/0461a8d5f0df8ee909c2fa395df9f546/36314_nightly.ipynb). Please find the attached Gists. Thanks!

**Comment by trisolaran** [comment] 2020-02-06 21:12
probably a duplicate of 34844
can you make sure that running "!ldconfig -p | grep cupti" in your colab?

**Comment by dtim1985** [comment] 2020-02-13 16:11
Here is the output of `!ldconfig -p | grep cupti`
```
libcupti.so.10.1 (libc6,x86-64) => /usr/local/cuda-10.1/extras/CUPTI/lib64/libcupti.so.10.1
libcupti.so (libc6,x86-64) => /usr/local/cuda-10.1/extras/CUPTI/lib64/libcupti.so
```
So seems 34844 has been already fixed in colab
But no step stats
Anyway after using fix from 34844 we are able to get GPU profile using tensorboard, so this issue is not so critical anymore (yet traces converted from step_stats are more informative then those in tensorboard)

**Comment by trisolaran** [comment] 2020-02-13 17:55
unfortunately, profiler team don't support step_stats anymore in favor of new "tf 2.0 profiler".

**Comment by qiuminxu** [comment] 2020-03-14 17:40
We have just released a new profiler in TF 2.2 rc0.
https://tensorflow.org/guide/profiler
One of the profiler output is trace.json.gz, that can be directly upload to chrome://tracing to visualize. 

Please try if the new profiler fixes your issue. 
If it doesn't, we will follow up with you.

thanks

**Comment by qiuminxu** [comment] 2020-03-14 19:38
Verifies the fix in tf-nightly works in this colab.
https://colab.research.google.com/gist/gadagashwini/2c9946a562d22127690069c4013da8bc/untitled449.ipynb

Cherrypick request sent out:
https://github.com/tensorflow/tensorflow/pull/37599

**Comment by saikumarchalla** [comment] 2020-04-24 14:17
@dtim1985  it seems the issue is resolved  with the update.Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by saikumarchalla** 2020-04-24 14:17 UTC
Labels: TF 2.1, comp:eager, type:bug
