### ISSUE TITLE
Python API Docs broken at r0.11

### ISSUE THREAD

**Issue by bc-lee** [tensorflow/tensorflow#5741] opened 2016-11-21 06:00 UTC
#4969 isn't fixed at branch r0.11.
https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#constant_initializer

**Comment by prb12** [comment] 2016-11-21 17:22
Closing as duplicate of #4969

**Closed by prb12** 2016-11-21 17:22 UTC
