### ISSUE TITLE
How about supporting delegation of OEM operations in TFL ?

### ISSUE THREAD

**Issue by VincentLin78** [tensorflow/tensorflow#18170] opened 2018-04-02 07:55 UTC
Currently, the interpreter delegates only built-in ops to NN API. I'm writing here to see if any plan to support to delegate OEM operations(ANEURALNETWORKS_OEM_OPERATION) defined in
https://android.googlesource.com/platform/frameworks/ml/+/master/nn/runtime/include/NeuralNetworksOEM.h

My understanding is it's just a minor change on TOCO and interpreter, right ?

**Comment by tensorflowbutler** [comment] 2018-04-02 17:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by VincentLin78** [comment] 2018-04-09 14:30
Have I written custom code: No
OS Platform and Distribution: Android
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment] 2018-05-10 12:38
Nagging Assignee @andrehentz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:45
Nagging Assignee @andrehentz: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:59
Nagging Assignee @andrehentz: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:20
Nagging Assignee @andrehentz: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:10
Nagging Assignee @andrehentz: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anitha-v** [comment] 2018-07-19 22:09
Can you please share the usecase you are trying to get to work ? There is no plan to support delegation of OEM ops currently. Your usecase will help us understand if this is needed.

**Comment by tensorflowbutler** [comment] 2018-08-03 18:51
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-18 18:42
Nagging Assignee @andrehentz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-08-23 18:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-08-23 18:18 UTC
Labels: comp:lite
