### ISSUE TITLE
(CONCATENATION) failed to prepare

### ISSUE THREAD

**Issue by derrkater** [tensorflow/tensorflow#56804] opened 2022-07-18 08:54 UTC
### 1. System information

- OS Platform and Distribution: MacOS Monterey 12.4
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.9.1
- Python: 3.7.10

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
converted checkpoint: https://drive.google.com/file/d/1iWPcJ3wC2xV-xz3lIiGQrgteGXZOLt5P/view?usp=sharing

```
interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()
input_data = np.ones([1, 3, 416, 416], dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs

When model is converted:

> 2022-07-18 10:49:42.054397: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1901] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
> Flex ops: FlexConv2D, FlexRange
> Details:
> 	tf.Conv2D(tensor<?x?x?x?xf32>, tensor<3x3x12x24xf32>) -> (tensor<?x?x?x24xf32>) : {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
> 	tf.Range(tensor<i64>, tensor<i64>, tensor<i64>) -> (tensor<?xi64>) : {device = ""}
> See instructions: https://www.tensorflow.org/lite/guide/ops_select

Model fails on `invoke` with:

> INFO: Created TensorFlow Lite delegate for select TF ops.
> 2022-07-18 10:28:53.074011: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> INFO: TfLiteFlexDelegate delegate: 13 nodes delegated out of 797 nodes with 3 partitions.
> RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (9 != 13)Node number 250 (CONCATENATION) failed to prepare.

**Comment by mohantym** [comment] 2022-07-18 10:17
Hi @derrkater !
Could you put select ops syntax in TFLite conversion and let us know whether it resolves.
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by derrkater** [comment] 2022-07-18 10:22
@mohantym I should have mentioned it, but I use select ops syntax already. My conversion code is the same as you've posted and the problem persists :/

**Comment by mohantym** [comment] 2022-07-18 11:38
@derrkater !
Could you confirm that you have added [select ops dependency ](https://www.tensorflow.org/lite/guide/ops_select#:~:text=dependencies%20%7B%0A%C2%A0%20%C2%A0%20implementation%20%27org.tensorflow%3Atensorflow%2Dlite%3A0.0.0%2Dnightly%2DSNAPSHOT%27%0A%C2%A0%20%C2%A0%20//%20This%20dependency%20adds%20the%20necessary%20TF%20op%20support.%0A%C2%A0%20%C2%A0%20implementation%20%27org.tensorflow%3Atensorflow%2Dlite%2Dselect%2Dtf%2Dops%3A0.0.0%2Dnightly%2DSNAPSHOT%27%0A%7D)in build.gradle file too.
Please enable the permissions for above Google drive as it is not accessible to me yet.

**Comment by derrkater** [comment] 2022-07-18 14:51
@mohantym the permissions are set now :) I did not add the dependency to the build.gradle file as I'm trying to run prediction on my mac first. 

It's first time for me using tflite from the scratch so I wanted to establish that it works first in python and run my evaluation to check if the model has same metrics after conversion, before going to mobile device.

**Comment by mohantym** [comment] 2022-07-19 03:53
Ok @derrkater !

For IOS projects , You need to [force load](https://www.tensorflow.org/lite/guide/ops_select#ios) the select ops file after declaring the dependencies in pod file.

Thank you!

**Comment by derrkater** [comment] 2022-07-19 05:44
@mohantym I haven't really tried iOS nor Android inference yet :) I just want to run this tflite checkpoint in python on my Mac  using the code I've originally provided.

I might try to jump directly to mobile device but I'd rather have inference script on my computer as well.

**Comment by mohantym** [comment] 2022-07-19 09:53
Hi @derrkater !
Could you share a minimal model file too. I am getting Dimension mismatch issue though with above TFlite model. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/e24c9105ba4a60c3866841df85b1e769/git_56804.ipynb#scrollTo=7CtFKa-Yu_FF)for reference.
Thank you!

**Comment by mohantym** [comment] 2022-07-19 13:03
Hi @sachinprasadhs ! 
Could you look at this issue.
Thank you!

**Comment by karimnosseir** [comment] 2022-07-20 16:16
Can you please verify that the model is running correctly in TF ? We saw in some cases the Pytorch->ONNX->TF sometimes generates an invalid TF model.

Thanks

**Comment by derrkater** [comment] 2022-07-21 07:24
@karimnosseir inference in `pb` format works just fine and the problems begin only with tflite.

**Comment by derrkater** [comment] 2022-07-25 09:20
@mohantym @karimnosseir @sachinprasadhs is it possible for someone to take over the bug?

**Comment by derrkater** [comment] 2022-08-04 19:50
@mohantym @karimnosseir @sachinprasadhs is there any plan to go back to this problem? I'm stuck without support with this problem

**Comment by haozha111** [comment] 2022-08-08 18:33
It seems that your tflite model has the input tensor of size : float32[1,3,416,416]. Is it always the case? Did you feed the model with a different shape? If you changed the input shape, you will need to resize input shape before calling `AllocateTensors`.

**Comment by derrkater** [comment] 2022-08-08 19:55
@haozha111 the model always operates on this datatype (float32) and shape ([1,3,416,416]). Onnx version works just fine and it breaks after being transferred to tflite.

**Comment by haozha111** [comment] 2022-08-08 20:44
> Hi @derrkater ! Could you put select ops syntax in TFLite conversion and let us know whether it resolves.
> 
> ```
> import tensorflow as tf
> 
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> tflite_model = converter.convert()
> open("converted_model.tflite", "wb").write(tflite_model)
> ```

How did you convert your model? Are you using this code to convert it to TF Lite? Could you share your SavedModel (pb + variables) you used for conversion? If the shape doesn't change, I guess there might be a bug in our converter, and we will need to regenerate the tflite model to debug it further.

**Comment by derrkater** [comment] 2022-08-09 08:58
@haozha111 as I have mentioned before, I’m using select ops syntax and my conversion code is identical as yours.



> @mohantym I don't actually have a tensorflow model .py file as it was converted from pytorch via onnx format. I can provide a pb file with variables - is that helpful?
> 
> https://drive.google.com/file/d/1oni3uxg_2gKJvF5zQMPH70l8061KLBr9/view?usp=sharing https://drive.google.com/drive/folders/1WHRhOsEgUrPxHy7ZI3dnETZ7ERSanRVA?usp=sharing
> 
> I was using different input format - BCHW. Maybe that caused Dimension mismatch?

Here i have provided model in pb format and it works just fine. The problems arise in tflite. I do think it is a problem with a converter indeed.

**Comment by haozha111** [comment] 2022-08-16 20:30
@LukeBoyer could you take a look on this issue? Thanks!

**Comment by Raj-Gohil** [comment] 2022-10-07 13:25
Hello,
Is there any update on this?
I am facing the same error

**Comment by LukeBoyer** [comment] 2022-10-07 22:18
Thanks for following up. Didn't get a chance to fix this yet but will
reprioritize. I will keep thread posted.

**Comment by Raj-Gohil** [comment] 2022-10-08 11:02
Hello @LukeBoyer it would be great to have fixed this error.
Looking forward to it
I am facing the error which is reproducible using https://github.com/tensorflow/tensorflow/issues/57988
Thank You

**Comment by LukeBoyer** [comment] 2022-10-13 18:23
@Raj-Gohil Please link the model you are using when encountering this issue.

**Comment by Raj-Gohil** [comment] 2022-10-13 18:27
@LukeBoyer please refer to #57988 and the https://github.com/tensorflow/tensorflow/files/9724024/test_new1.zip for the files to reproduce the error.

**Comment by LukeBoyer** [comment] 2022-10-13 18:41
> @LukeBoyer please refer to #57988 and the https://github.com/tensorflow/tensorflow/files/9724024/test_new1.zip for the files to reproduce the error.

I see. Thanks.

**Comment by LukeBoyer** [comment] 2022-10-26 22:06
@derrkater The issue here is that concat expects non-axis dimensions of all the inputs to be equal. At runtime concat is being passed shapes: (1, 13, 13, 192), (1, 9, 9, 192), (1, 5, 5, 192) which is invalid. These dimensions are unknown at compile time. The Ops that introduce the inconsistent shapes are the max_pool_2d ops a few back from concat. Here are their authored compile time definitions. These are tflite but inspection of saved_model.pb is the same.
```
%318 = "tfl.max_pool_2d"(%317) {filter_height = 9 : i32, filter_width = 9 : i32, fused_activation_function = "NONE", padding = "VALID", stride_h = 1 : i32, stride_w = 1 : i32} : (tensor<?x?x?x192xf32>) -> tensor<?x?x?x192xf32>
 
%323 = "tfl.max_pool_2d"(%322) {filter_height = 5 : i32, filter_width = 5 : i32, fused_activation_function = "NONE", padding = "VALID", stride_h = 1 : i32, stride_w = 1 : i32} : (tensor<?x?x?x192xf32>) -> tensor<?x?x?x192xf32>
   
%313 = "tfl.max_pool_2d"(%312) {filter_height = 13 : i32, filter_width = 13 : i32, fused_activation_function = "NONE", padding = "VALID", stride_h = 1 : i32, stride_w = 1 : i32} : (tensor<?x?x?x192xf32>) -> tensor<?x?x?x192xf32>
```
At runtime these three ops take in the same shape (1, 13, 13, 192). It's clear that given the values for filter_height and filter_width and stride that these will return different shapes (1, 5, 5, 192), (1, 9, 9, 192), (1, 13, 13, 192) respectively. These shapes are transposed and then fed to the concat which is failing because 5 != 9 != 13. 
  
This looks to me to be an issue authoring the model, or at least upstream of tensorflow lite. This can be fixed by adjusting the filter size values or by setting padding to "SAME" such that the output shape of the all of these max_pool are the padded to be 1, 13, 13, 192. 
  
https://www.tensorflow.org/api_docs/python/tf/concat 
  
Here is a textual representation of the tensorflow model so you can confirm for yourself.  The max_pool ops in question can be searched for with, input: "transpose_89:y:0", transpose_87:y:0", transpose_91:y:0". 

https://drive.google.com/file/d/194VpOmlqWJzEbd2ZF4W-Ffz5T3kCoW6U/view?usp=sharing

**Closed** 2022-10-26 22:06 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:lite, TFLiteConverter, TF 2.9
