### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Colabnoob** [tensorflow/tensorflow#59481] opened 2023-01-28 00:48 UTC
Can anyone help me with this error? I have been trying to get this solved for a month. I think the code is outdated on the colab notebook and have no idea how to change the code to make it compatible for TF 2. Thanks if anyone can solve this 

/usr/local/lib/python3.8/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1qTdOAdKmMKe-HZA-1SXCAARBAdZXeSAN
To: /content/merged.dict.txt
100% 7.94M/7.94M [00:00<00:00, 254MB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-50620fa974be> in <module>
     49 
     50 # initialize Tacotron2 with the pretrained model
---> 51 hparams = create_hparams()

/content/tacotron2/hparams.py in create_hparams(hparams_string, verbose)
      6     """Create model hyperparameters. Parse nondefault from given string."""
      7 
----> 8     hparams = tf.contrib.training.HParams(
      9         ################################
     10         # Experiment Parameters        #

AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by synandi** [comment] 2023-01-30 10:13
Hi @Colabnoob,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist] to reproduce the issue faced. Thanks!

**Comment by Colabnoob** [comment] 2023-01-30 12:25
I filled out the template, i would really appreciate if you can solve this, i have been facing this problem for nearly two months. https://github.com/tensorflow/tensorflow/issues/59492#issue-1562342276

**Comment by synandi** [comment] 2023-02-01 14:10
Hi @Colabnoob, This seems to be a duplicate of [#59492](https://github.com/tensorflow/tensorflow/issues/59492). This issue will be triaged on [#59492](https://github.com/tensorflow/tensorflow/issues/59492) . Could you please close this issue? Thanks!

**Closed** 2023-02-01 14:54 UTC
Labels: stat:awaiting response, comp:core, TF 1.15
