### ISSUE TITLE
Distributed cluster manager support: Slurm

### ISSUE THREAD

**Issue by cgorman** [tensorflow/tensorflow#1686] opened 2016-03-29 02:02 UTC
Per the comment on [this introduction](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md), i.e. 

> N.B. Manually specifying these cluster specifications can be tedious, especially for large clusters. We are working on tools for launching tasks programmatically, e.g. using a cluster manager like Kubernetes. If there are particular cluster managers for which you'd like to see support, please raise a GitHub issue.

Is there is any possibility of supporting [Slurm](http://slurm.schedmd.com/)? Forgive my ignorance but I've really only played around with TensorFlow and I've only used Slurm for fairly simple MPI projects, but I recently got access to a cluster with some GPU nodes and I'd like to incorporate TF in my research project. It would be great if I was able to use all the resources I could to speed things along.

If it helps, specific info about the setup can be found [here](https://wiki.auckland.ac.nz/display/CER/Centre+for+eResearch+User+Documentation+Start).

**Comment by mrry** [comment] 2016-03-29 02:54
From a quick look at the Slurm docs, it looks like it could well support running TensorFlow, since (i) there's [decent support for running Python jobs](https://support.nesi.org.nz/hc/en-gb/articles/207782537-Python). I don't have access to a Slurm cluster, so I'm going to tag this "Contributions welcome", but I'd be happy to work with you on this Issue to get your cluster running on Slurm.

Here's how you could get started:

1. Create a Slurm job that sets up a Python virtualenv, installs a recent nightly PIP package, and runs a Python script. (Version 0.8 should include distributed cluster support.)
2. In your Python script, parse the `$SLURM_NODELIST` environment variable to get a list of the hosts involved in the computation.
3. Similarly, extract the [`$SLURM_STEP_RESV_PORTS` environment variable](https://computing.llnl.gov/linux/slurm/mpi_guide.html#open_mpi) and somehow decide what port to use in that range.
4. Create a `tf.ClusterSpec` based on the information from the environment variables, and use that to create a `tf.GrpcServer` (documentation coming soon; see [`server_lib.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/server_lib.py)) in each process.
5. Define a TensorFlow graph that is distributed across the nodes in your Slurm job.

Let me know if you have any questions!

**Comment by cgorman** [comment] 2016-03-29 03:20
Awesome, thanks for the quick reply. I will definitely try that out with one of the TF tutorial programs when I can, probably tomorrow, and post updates.

**Comment by cgorman** [comment] 2016-03-31 02:17
Well after a ton of struggling I am unable to fully test this solution due to the issue outlined in #527, i.e. the cluster has an older glibc version and I can't build TF manually or run it from pip. I'll e-mail the cluster admins but I don't know if they would be willing to do that update. I'll update this issue if I can get anything figured out.

**Comment by Ottunger** [comment] 2016-06-24 08:00
About your issue with #527 I was able to get tensorflow running on the cluster by fully installing myself, see attach script if it can help you.

About clustering myself, I do not see how to as I have but experience in using distributed tf over several machines, any help appreciated: will it work with a clusterspec that specifies several localhost:<port> mappings then attaching one task to each cpu and listen on a different port?

[pip_setup.txt](https://github.com/tensorflow/tensorflow/files/331412/pip_setup.txt)

**Comment by jhollowayj** [comment] 2016-07-13 01:53
@cgorman, have you made any progress?  I'm thinking of taking a stab at it soon but didn't want to duplicate any work.

**Comment by cgorman** [comment] 2016-07-13 03:12
@jhollowayj Not really, no. After 0.9 came out I tried again but still wasn't able to get it installed on the cluster. I asked the support staff to try and they weren't able to either, so I just gave up.

**Comment by jhollowayj** [comment] 2016-07-19 18:22
Sounds good.  We got it installed here just a little bit ago, so I'll take a stab at it sometime.  

In case I don't, the slurm manager here pointed me to two scripts he wrote to parse out the slurm nodelist in perl that may be helpful for generating that list:
https://github.com/SchedMD/slurm/blob/slurm-16.05/contribs/torque/generate_pbs_nodefile.pl
https://github.com/SchedMD/slurm/blob/78bb5093c37da90ab4206639d6028b358a296370/contribs/torque/generate_pbs_nodefile.pl
He said the second might be easier, since it wasn't using the slurm perl API that the first link uses.

**Comment by jhollowayj** [comment] 2016-07-19 18:42
@mrry If we did have this nodelist parsing code written, where would it sit in the project?

I'm not familiar with the internals to see where and the best that I would have would be to write a separate python script that parses the nodes, picks ports, and then just formats arguments like `--ps_hosts=ps1:2222,ps2:2222, --worker_hosts=wk1:2223,wk2:2223,wk3:2223,`  which then call my regular scrips with those as the flags, changing the index/job based on which computer it is in the nodelist.  But that doesn't seem very well thought through.

**Comment by jhollowayj** [comment] 2016-08-19 14:21
http://stackoverflow.com/questions/34826736/running-tensorflow-on-a-slurm-cluster has a few pointers

**Comment by jhollowayj** [comment] 2016-08-27 00:47
I've spent some time reading up on slurm and it's allocation stuff.  What I have so far is [here](https://github.com/jhollowayj/tensorflow_slurm_manager/blob/master/slurm_manager.py) (still a work in progress).  

I've been trying to figure out how to best support all possible slurm clusters (slurm adds environment variables, but not everyone runs the same version of slurm) as well as possible run configurations (x Nodes running y processes, each process on it's own exclusive node, etc.). 

Some Questions I have are:
 * Do other cluster managers force each process on it's own physical node, or do multiple processes occasionally get put on the same node?
    * Note: our setup here will probably be the later as we only have a few GPU nodes.  However, I wanted to try and be consistent across other cluster managers like Kubernetes.
 * Are there any benefits to having multiple PS on the same physical node?  I've set it up to limit PS to one per node if the user has multiple processes on the same physical node.
   * Do PS use multiple cores?  If so, I feel like network bandwidth will be the bottle neck over CPU usage.  If not, I can try to write a better assigner.
 * Are there any rules for importing pip packages once the manager is included in TF?  (I used python-hostlist to help parse slurm's list of hostnames)
 * Where would this file go in the Tensorflow repo once it's accepted?  (i.e. /tf/tf/contrib/cluster_managers/slurm.py ?)

**Comment by ahundt** [comment] 2017-03-13 18:42
#2 also has several useful links (and this appears to be a duplicate of that).

**Comment by ahundt** [comment] 2017-06-27 19:17
Some work has been done on this here:
https://github.com/jhollowayj/tensorflow_slurm_manager/

**Comment by alextp** [comment] 2018-02-07 23:10
Sharing physical nodes across ps is usually a bad idea as ps is very network-heavy. PS also can use multiple cores (most tf code does) when updating variables.

The suggested file location is good.

I'll close this issue for now since it's old, but please reopen as a pull request if you want to contribute.

**Closed by alextp** 2018-02-07 23:10 UTC
Labels: stat:contributions welcome

**Comment by ahundt** [comment] 2018-02-11 07:20
FYI I'm pretty sure this is achievable with https://github.com/uber/horovod in combination with a standard SLURM launch shell script, assuming all the proper software is installed.
