### ISSUE TITLE
AttributeError: 'IndexedSlices' object has no attribute '_copy'

### ISSUE THREAD

**Issue by pminervini** [tensorflow/tensorflow#24024] opened 2018-11-28 18:43 UTC
Hello,
This is puzzling, as this only happens with `tensorflow-gpu` version 1.12.0 -- `tensorflow` version 1.12.0 works flawlessly (both on GNU/Linux and OSX).

```
Traceback (most recent call last):
  File "./bin/moe-cli.py", line 476, in <module>
    main(sys.argv[1:])
  File "./bin/moe-cli.py", line 372, in main
    gradients = tape.gradient(loss, trainable_variables)
  File "/home/testing/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 901, in gradient
    output_gradients=output_gradients)
  File "/home/testing/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 64, in imperative_grad
    output_gradients)
  File "/home/testing/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 858, in grad_fun
    return [dresult._copy(device_name=self_device)]
AttributeError: 'IndexedSlices' object has no attribute '_copy'
```

**Comment by pminervini** [comment] 2018-12-26 12:32
Since the problematic line seems to be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L852, I have fixed the TF source code as follows:

```
  def _copy(self, ctx=None, device_name=None):
    """Copies tensor to dest device."""
    new_tensor = self._copy_nograd(ctx, device_name)
    # Record the copy on tape and define backprop copy as well.
    if context.executing_eagerly():
      self_device = self.device
      def grad_fun(dresult):
        # return [dresult._copy(device_name=self_device)]
        return [dresult]
      tape.record_operation("_copy", [new_tensor], [self], grad_fun)
    return new_tensor
```

**Comment by ymodak** [comment] 2019-01-02 21:48
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2019-01-02 21:48 UTC
Labels: comp:ops

**Comment by pminervini** [comment] 2019-01-02 21:54
@ymodak it is not really resolved - I just hacked that "fix" into my tensorflow installation, but the problem persists

**Comment by ymodak** [comment] 2019-01-02 22:04
Can you please fill the information asked by the template and we can reopen your issue? Thanks!
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by meyerjo** [comment] 2019-03-04 09:40
Having the same issue:
* CUDA 10.0 
* Ubuntu 16.04
* GPU Nvidia TITAN
* Tensorflow version: 2.0.0-dev20190225

The fix mentioned above seems to work.

**Comment by netpaladinx** [comment] 2019-04-16 21:06
I got the same issue when I enabled the eager execution and called `tf.gather()` on a custom variable. I found it was okay when I used the keras Embedding layer that basically calls the same `gather()` function on a low level. I did the debug in TensorFlow code and then found the reason. There is a piece of code in the keras `embeddings.py`:

`  def build(self, input_shape):
    # Note: most sparse optimizers do not have GPU kernels defined. When
    # building graphs, the placement algorithm is able to place variables on CPU
    # since it knows all kernels using the variable only exist on CPU.
    # When eager execution is enabled, the placement decision has to be made
    # right now. Checking for the presence of GPUs to avoid complicating the
    # TPU codepaths which can handle sparse optimizers.
    if context.executing_eagerly() and context.context().num_gpus():
      with ops.device('cpu:0'):
        self.embeddings = self.add_weight(
            shape=(self.input_dim, self.output_dim),
            initializer=self.embeddings_initializer,
            name='embeddings',
            regularizer=self.embeddings_regularizer,
            constraint=self.embeddings_constraint)
    else:
      self.embeddings = self.add_weight(
          shape=(self.input_dim, self.output_dim),
          initializer=self.embeddings_initializer,
          name='embeddings',
          regularizer=self.embeddings_regularizer,
          constraint=self.embeddings_constraint)
    self.built = True`

And my custom variable was defined on GPU by default.

To fix it, try to define your variable on CPU if you are going to call `tf.gather()` or other sparse ops on it.

**Comment by pminervini** [comment] 2019-04-17 11:35
> To fix it, try to define your variable on CPU if you are going to call tf.gather() or other sparse ops on it.

it's not really a fix tho, just an inefficient workaround

**Comment by pminervini** [comment] 2019-04-19 22:01
@netpaladinx @meyerjo you may be interested in this pull request of mine: https://github.com/tensorflow/tensorflow/pull/27986
