### ISSUE TITLE
problem of compiler libtensorflow_cc.so with debug info

### ISSUE THREAD

**Issue by yuwang89thu** [tensorflow/tensorflow#21987] opened 2018-08-31 04:05 UTC
I want to compiler libtensorflow_cc.so with debug info by bazel .
try with lines :bazel build -c dbg --strip=never //tensorflow:libtensorflow_cc.so.
but it's not work .when I gdb .so, (no debug info ).
version info: tf-r1.4 ,bazel-10.0.
What's worng with my lines ?  thanks a lot .

**Comment by tensorflowbutler** [comment] 2018-08-31 19:27
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-16 02:33
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment] 2018-09-28 20:51
@yuwang89thu [New Issue Template](https://github.com/tensorflow/tensorflow/issues/new)

**Comment by ymodak** [comment] 2018-10-12 22:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-12 22:07 UTC
Labels: stat:awaiting response
