### ISSUE TITLE
Tensorflow build issue in RHEL6 machine

### ISSUE THREAD

**Issue by Abinayasandhiya** [tensorflow/tensorflow#20333] opened 2018-06-27 07:11 UTC
-----------------------

### System information
- [root@abinaya-tensorflow ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)

-TensorFlow installed from source
- TensorFlow version 
- Python 2.7.11 
- Bazel version :

[root@abinaya-tensorflow tensorflow-r1.6]$ bazel version
Build label: 0.14.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 27 06:45:12 2018 (1530081912)
Build timestamp: 1530081912
Build timestamp as int: 1530081912

- GCC/Compiler version :

[root@abinaya-tensorflow ~]$ gcc --version
gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Describe the problem

We are trying to build Tensorflow 1.6 from source code as per the help of below guide:

https://www.tensorflow.org/install/install_sources

please find below steps which i tried:

***********************************************************************************************************
[root@abinaya-tensorflow tensorflow-r1.6]$ bazel version
**Build label: 0.14.1- (@non-git)**
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 27 06:45:12 2018 (1530081912)
Build timestamp: 1530081912
Build timestamp as int: 1530081912

[root@abinaya-tensorflow tensorflow-r1.6]$ ./configure
Traceback (most recent call last):
  File "configure.py", line 1459, in <module>
    main()
  File "configure.py", line 1346, in main
    check_bazel_version('0.5.4')
  File "configure.py", line 459, in check_bazel_version
    curr_version = run_shell(['bazel', '--batch', 'version'])
  File "configure.py", line 154, in run_shell
    output = subprocess.check_output(cmd)
AttributeError: 'module' object has no attribute 'check_output'

Already available bazel version is 0.14.1 but i couldn't run the "configure" script of tensorflow.

Can you please help us to build the tensorflow from source code.

### Source code / logs

Available version of gcc and JAVA and bazel in our machine:

#################################################################
[root@abinaya-tensorflow ~]$ which gcc
/opt/gcc/x86_64/8.1.0/bin/gcc

[root@abinaya-tensorflow ~]$ echo $JAVA_HOME
/opt/j2se/x86_64/1.8.0_172

[root@abinaya-tensorflow ~]$ bazel version
WARNING: ignoring http_proxy in environment.
Build label: 0.14.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 27 06:45:12 2018 (1530081912)
Build timestamp: 1530081912
Build timestamp as int: 1530081912
#################################################################

Issue which we are facing while run the configure script of tensorflow is:

################################################################
[root@abinaya-tensorflow tensorflow-r1.6]$ ls
ACKNOWLEDGMENTS     AUTHORS             CODEOWNERS    CONTRIBUTING.md    models.BUILD  tensorflow   util
ADOPTERS.md         BUILD               configure     ISSUE_TEMPLATE.md  README.md     third_party  WORKSPACE
arm_compiler.BUILD  CODE_OF_CONDUCT.md  configure.py  LICENSE            RELEASE.md    tools
[root@abinaya-tensorflow tensorflow-r1.6]$ ./configure
Traceback (most recent call last):
  File "configure.py", line 1459, in <module>
    main()
  File "configure.py", line 1346, in main
    check_bazel_version('0.5.4')
  File "configure.py", line 459, in check_bazel_version
    curr_version = run_shell(['bazel', '--batch', 'version'])
  File "configure.py", line 154, in run_shell
    output = subprocess.check_output(cmd)
AttributeError: 'module' object has no attribute 'check_output'
####################################################################

**Comment by tensorflowbutler** [comment] 2018-06-27 18:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gunan** [comment] 2018-06-29 05:40
I suspect you are running into this:
https://stackoverflow.com/questions/26894024/subprocess-check-output-module-object-has-out-attribute-check-output

Could you print the output of `python --version` just to make sure that your main python is a python 27 binary?

**Comment by tensorflowbutler** [comment] 2018-07-13 19:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-07-13 19:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-07-13 19:07 UTC
Labels: stat:awaiting response
