### ISSUE TITLE
Kernel Died Issue

### ISSUE THREAD

**Issue by k1i2m4** [tensorflow/tensorflow#8309] opened 2017-03-11 18:59 UTC
Can anybody know why kernel is always died? When I excute this cell, a part of Lenet CNN.

1. Code : 
```
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    num_examples = len(X_train)
    
    print("Training...")
    print()
    for i in range(EPOCHS):
        X_train, y_train = shuffle(X_train, y_train)
        for offset in range(0, num_examples, BATCH_SIZE):
            end = offset + BATCH_SIZE
            batch_x, batch_y = X_train[offset:end], y_train[offset:end]
            sess.run(training_operation, feed_dict={x: batch_x, y: batch_y})
            
        validation_accuracy = evaluate(X_validation, y_validation)
        print("EPOCH {} ...".format(i+1))
        print("Validation Accuracy = {:.3f}".format(validation_accuracy))
        print()
    try:
        saver
    except NameError:
        saver=tf.train.Saver()       
    saver.save(sess, './lenet')
    print("Model saved")
```
2. Error Message :
``` 
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
```
Then, the kernel is died....it is crazy. Please let me know the solution 

3. Environment 
Window 10 (No Ubantu)
Anaconda w/Jupyter Notebook 
Tensorflow w/GPU (Cuda 8.0, cuDNN 5.1)

Thank you!!

**Comment by prb12** [comment] 2017-03-11 19:15
This does look like TensorFlow is unable to find the cuDNN library.  
Could you please double check that you followed the instructions on [this](https://www.tensorflow.org/install/install_windows) page for installation of cuDNN and adding the installation directory to  your `%PATH%` environment variable?

**Comment by prb12** [comment] 2017-03-11 19:16
Potentially a duplicate of #6698

**Comment by yaroslavvb** [comment] 2017-03-11 23:02
Sometimes you get unrelated GPU errors when you run of RAM, as in https://github.com/tensorflow/tensorflow/issues/7025

**Comment by asimshankar** [comment] 2017-04-05 10:20
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-05 10:20 UTC
Labels: stat:awaiting response
