### ISSUE TITLE
*** The TAGS command line option is no longer supported in the TFLM Makefile..

### ISSUE THREAD

**Issue by angsiokcheng** [tensorflow/tensorflow#46721] opened 2021-01-27 06:26 UTC
@tensorflow/micro

i was following guides from Build Arm Cortex-M voice assistant with Google TensorFlow Lite, link as below:
https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/build-arm-cortex-m-voice-assistant-with-google-tensorflow-lite 

so when i come across the command below:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_micro_speech_mbed_project

This error pops out:
*** The TAGS command line option is no longer supported in the TFLM Makefile..

i tried to remove TAGS="..." but it after it compiles it did not work as expected.
I also tried OPTIMIZED_KERNEL_DIR, it returns error below:
tensorflow/lite/micro/tools/make/Makefile:552: disco_f746ng.inc: No such file or directory
make: *** No rule to make target 'disco_f746ng.inc'.  Stop.

Correct me if i am wrong, based on my understanding CMSIS and disco_f746ng are folders specified in ./tensorflow/tensorflow/lite/micro/examples/micro_speech
Which the original TAGS are used to search out the makefile.inc inside both folders and make the file. So the question may be what can i use to replace what TAGS? OR are there any other ways to use OPTIMIZED_KERNEL_DIR?

Thank you in advanced for helping.

**Comment by terryheo** [comment] 2021-02-03 01:33
@jvishnuvardhan  plz don't assign TFL Micro issue to me.

**Comment by advaitjain** [comment] 2021-02-03 19:11
The mbed project generation bits might be a bit out of date.

Tagging @MatthiasHertel80 to check what the current recommended approach is for using TFLM with mbed.

From my perspective (as a TFLM maintainer, but not the one maintaining the mbed integration), you should be able to rename [this folder](https://github.com/tensorflow/tensorflow/blob/8ddc7459a8f7d2526249f8b9d496d0812a7aff55/tensorflow/lite/micro/examples/micro_speech/arduino/Makefile.inc#L1) to mbed,

and modify this line:
https://github.com/tensorflow/tensorflow/blob/8ddc7459a8f7d2526249f8b9d496d0812a7aff55/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc#L2

to check for the target (instead of tage) similar to arduino:
https://github.com/tensorflow/tensorflow/blob/8ddc7459a8f7d2526249f8b9d496d0812a7aff55/tensorflow/lite/micro/examples/micro_speech/arduino/Makefile.inc#L1


Then `TARGET=mbed OPTIMIZED_KERNEL_DIR=cmsis_nn` should do the trick.

**Comment by zyang498** [comment] 2021-02-04 07:34
@advaitjain 

Hi, thank you for the reply. I am modifying this line

[https://github.com/tensorflow/tensorflow/blob/8ddc7459a8f7d2526249f8b9d496d0812a7aff55/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc#L2](url)

to the code like this

`ifeq ($(TARGET),$(filter $(TARGET),disco_f746ng))`

and then I run the make command

`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed OPTIMIZED_KERNEL_DIR=cmsis_nn generate_micro_speech_mbed_project`

But I result in the error

> make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/hello_world/mbed/tensorflow/lite/c/common.c', needed by 'generate_hello_world_mbed_project'.  Stop.

Does that mean I have something need to modify in the Makefile? Thank you.

**Comment by marconi1964** [comment] 2021-02-21 12:23
I have similar issue, but slightly different (no modification on Makefile.inc)

I was able to make without problem with the make command
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed OPTIMIZED_KERNEL_DIR=cmsis_nn generate_micro_speech_mbed_project`

But audio_provider.cc under directory make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/tensorflow/lite/micro/examples/micro_speech was not replaced by the one under disco_f746ng/audio_provider.cc

When I modified the make command of setting TARGET=stm32f4,
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=stm32f4 OPTIMIZED_KERNEL_DIR=cmsis_nn generate_micro_speech_mbed_project`

It did reproduce the similar error message.
> make: *** No rule to make target 'generate_micro_speech_mbed_project'. Stop.

**Comment by patriklaurell** [comment] 2021-04-21 15:20
@angsiokcheng @marconi1964 @zyang498 I don't know if this is still relevant for you but I just uploaded PR #48659 . It updates the micro_speech mbed generation. It should enable you to compile the micro_speech example for STM32F746, if you follow the instructions in tensorflow/lite/micro/examples/micro_speech/README.md. The instructions on developer.arm.com that you posted above have not been updated yet.

**Comment by marconi1964** [comment] 2021-04-24 15:15
@patriklaurell your PR works very well on micro_speech example. Thank you very much.
Since it changes the way how 'make' works, the other examples of DISCO_F746NG needs to be updated accordingly, too.

**Comment by patriklaurell** [comment] 2021-04-26 12:13
@marconi1964 Good to hear that it at least partly solved the problem. For micro_speech I can compile locally using the instructions in the readme. Could you provide some more details on how to reproduce?
For hello_world, I will upload a PR today to update the example

**Comment by wdjose** [comment] 2021-04-26 13:45
@patriklaurell I [uploaded a PR](https://github.com/tensorflow/tensorflow/pull/48740) for the `hello_world` example, and also updated some of the other outdated information in the README.md of both `hello_world` and `micro_speech` (like confirming Python 3/pip3 support, and updating the reference to the MBED CLI installation instructions). I also added command for copying the old `arm_math.h` and `cmsis_gcc.h` dependencies that you linked to the [other issue I posted](https://github.com/tensorflow/tensorflow/issues/48741).

**Comment by marconi1964** [comment] 2021-04-26 14:45
@patriklaurell Just to confirm my issue reproduction, I remove the repo and git clone again. And (nice) surprisingly, it works well with cmsis_nn enabled. The issue is gone. Great and thanks.

**Comment by marconi1964** [comment] 2021-04-28 06:31
@angsiokcheng With all these discussions with fixes and code merged, assume this issue can be closed?

**Comment by advaitjain** [comment] 2021-04-28 16:29
Thanks for the great work on this. I'm going to close this issue. Feel free to reopen if needed.

**Closed by advaitjain** 2021-04-28 16:29 UTC
Labels: comp:micro, type:bug
