### ISSUE TITLE
configure issues

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#4335] opened 2016-09-12 12:40 UTC
```
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /home/wenjian/pkgs/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such target '//tensorflow/core:android_proto_lib_no_rtti_lite_runtime': target 'android_proto_lib_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /home/wenjian/pkgs/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

```

**Comment by wilesdaliglass** [comment] 2016-09-12 15:14
I am having the same issue (fresh pull of master); it seems to reference a different package each time I try to run `./configure`, e.g.

> ERROR: /opt/local/src/tensorflow/tensorflow/core/BUILD:689:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core:ios_tensorflow_test_lib'.
> ERROR: /opt/local/src/tensorflow/tensorflow/core/BUILD:689:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core:ios_tensorflow_test_lib'.
> ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

and

> ERROR: /opt/local/src/tensorflow/tensorflow/contrib/session_bundle/BUILD:237:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by /opt/local/src/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature_lite'.
> ERROR: /opt/local/src/tensorflow/tensorflow/contrib/session_bundle/BUILD:237:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /opt/local/src/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature_lite'.
> ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

presumably because of bazel is running more than one job at a time.

**Comment by raix852** [comment] 2016-09-12 17:38
Yes, it's duplicate of #4312.

**Closed** 2016-09-12 18:33 UTC
Labels: awaiting googler, installation/startup
