### ISSUE TITLE
“grp c++/grpc++.h”: No such file or directory ( D:\tensorflow-master\tensorflow\core\common_runtime\eager\context.cc)

### ISSUE THREAD

**Issue by mm1860** [tensorflow/tensorflow#19893] opened 2018-06-10 15:59 UTC
“D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj”(默认目标) (1) ->
“D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj”(默认目标) (130) ->
(ClCompile 目标) ->
  D:\tensorflow-master\tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h(21): fatal error C1083: 无法打开包括文件: “grp
c++/grpc++.h”: No such file or directory (编译源文件 D:\tensorflow-master\tensorflow\core\common_runtime\eager\context.cc) [
D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj]
  D:\tensorflow-master\tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h(21): fatal error C1083: 无法打开包括文件: “grp
c++/grpc++.h”: No such file or directory (编译源文件 D:\tensorflow-master\tensorflow\core\common_runtime\eager\eager_operati
on.cc) [D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj]
  D:\tensorflow-master\tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h(21): fatal error C1083: 无法打开包括文件: “grp
c++/grpc++.h”: No such file or directory (编译源文件 D:\tensorflow-master\tensorflow\core\common_runtime\eager\execute.cc) [
D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj]
  D:\tensorflow-master\tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h(21): fatal error C1083: 无法打开包括文件: “grp
c++/grpc++.h”: No such file or directory (编译源文件 D:\tensorflow-master\tensorflow\core\common_runtime\eager\tensor_handle
.cc) [D:\tensorflow-master\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj]

**Comment by tensorflowbutler** [comment] 2018-06-11 01:31
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mm1860** [comment] 2018-06-11 02:28
Thank you，
i want to cmake c++ api at win10 ,setup like this:
1.install git,CMake ,SWIG,vs2015update3 and set system environment variable
2.-Dtensorflow_ENABLE_GRPC_SUPPORT OFF,-Dtensorflow_ENABLE_SSL_SUPPORT OFF,-Dtensorflow_ENABLE_GPU OFF,tensorflow_BUILD_SHARED_LIB ON
3.D:\temp> cd tensorflow\tensorflow\contrib\cmake
D:\temp\tensorflow\tensorflow\contrib\cmake> mkdir build
D:\temp\tensorflow\tensorflow\contrib\cmake> cd build
D:\temp\tensorflow\tensorflow\contrib\cmake\build>cmake ..
4.MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj

**Comment by tazr** [comment] 2018-07-17 09:00
I am having the same issue.

I don't believe this is covered by #16480, because in the present case the build explicitly exclude support of GRPC:

    -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF

**Comment by asimshankar** [comment] 2018-07-18 02:17
I see, IIUC, you're having trouble building TensorFlow on Windows 10 when setting a non-default value for a build option (GRPC)?

If so, marking this as "Contributions Welcome"

**Comment by mm1860** [comment] 2018-07-18 02:30
-Dtensorflow_ENABLE_GRPC_SUPPORT=OFF or -Dtensorflow_ENABLE_GRPC_SUPPORT=On, having the same exception

**Comment by stakemura** [comment] 2018-07-25 03:06
I encoutered the same issue under the following environment.

OS Platform and Distribution: Windows 10 Enterprise
TensorFlow installed: from GitHub
TensorFlow version: 1.9.0
Bazel version: not used (cmake)
CUDA/cuDNN version: not used
GPU model and memory: not used
Exact command to reproduce: build with -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF

**Comment by hujunyao** [comment] 2018-08-06 09:02
I am having the same issue when
MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj
whatever -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF or On.

But I compile succussfully with Dtensorflow_ENABLE_GRPC_SUPPORT=OFF in
msbuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj

**Comment by cvJie** [comment] 2018-08-07 00:52
me too,how to solve it?

**Comment by asimshankar** [comment] 2018-08-07 01:00
(BTW, bazel can now be used to build TensorFlow on Windows. @gunan I believe is in the process of updating the build instructions for that)

**Comment by gunan** [comment] 2018-08-07 07:41
Sorry for the inconvenience.
@meteorcloudy for bazel instructions.
For cmake build, if you build from the 1.10 branch, it is still working.

**Comment by mm1860** [comment] 2018-08-07 07:56
i using tensorflowsharp now,build file has been put in NUGET,this is a good idea

**Comment by LJXLJXLJX** [comment] 2018-08-14 13:38
Hello
Have you solved this problem? 
I meet the same

**Comment by meteorcloudy** [comment] 2018-08-14 14:27
@LJXLJXLJX We'll soon publish a documentation for Windows Bazel build, people can then build TensorFlow following that instruction.

**Comment by LJXLJXLJX** [comment] 2018-08-14 14:42
@meteorcloudy Thank you , that's wonderful ! This is driving me crazy 😵

**Comment by meteorcloudy** [comment] 2018-08-14 14:50
@LJXLJXLJX If you're interested, I have a preview of the doc here you can try:
https://gist.github.com/meteorcloudy/8e5f1aab7c7fa87b16ae28e6f8fd3fd2

I'll be glad to hear some feedback. ;)

**Comment by Goldesel23** [comment] 2018-08-23 08:26
@meteorcloudy The bazel build will allow you to build the C++/C APIs for windows or just the pip package? I tried to build the shared lib but with no success.

**Comment by meteorcloudy** [comment] 2018-08-23 08:37
@Goldesel23 Yes, it should be able to build `//tensorflow:libtensorflow.so` and `//tensorflow/java:libtensorflow_jni.so`. We have CI job running for them, it should work.

Can you file another issue to report the exact problem you encountered?

**Comment by Goldesel23** [comment] 2018-08-23 17:41
@meteorcloudy, after some research I was able to build the `//tensorflow:libtensorflow_cc.so` project after applying a Eigen patch (already discussed in #19198 ) 

The generated files Is there going to be possible to generate a dll similar to cmake build for windows? The project only builds the so libs not dlls.

**Comment by meteorcloudy** [comment] 2018-08-24 08:15
@Goldesel23 Glad it worked! The .so file is in fact the .dll file you need. You can just rename the file or the target to libtensorflow.dll. :)

**Comment by Goldesel23** [comment] 2018-08-24 15:36
@meteorcloudy Thanks! I wanted to link the shared lib in a project without bazel. I generated the .lib file with the references from the dll, but I am having some  linking problems. I will try to work them out. Thanks for the help!

**Comment by LJXLJXLJX** [comment] 2018-08-27 06:37
@meteorcloudy Thanks for your instruction,  I have built the libtensorflow.so and libtensorflow.so.if.lib successfully, but when I tried to use them in a test project , there are 4101 errors , like

严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E1696	无法打开 源 文件 "google/protobuf/util/type_resolver_util.h"	tf_test	d:\tensorflow\tensorflow\core\platform\default\protobuf.h	33	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “unsupported/Eigen/CXX11/Tensor”: No such file or directory	tf_test	d:\tensorflow\third_party\eigen3\unsupported\eigen\cxx11\tensor	1

**Comment by Goldesel23** [comment] 2018-08-27 07:12
@LJXLJXLJX You need to add the tensorflow, bazel-genfiles, eigen-archive and protobuf/src to the include directories of the project.

**Comment by Goldesel23** [comment] 2018-09-01 12:08
@LJXLJXLJX sorry for the late response. You'll probably will need to add these to the include paths:

```
tensorflow
tensorflow/bazel-tensorflow/external/eigen_archive
tensorflow/bazel-tensorflow/external/protobuf_archive/src
tensorflow/bazel-genfiles
```

**Comment by Goldesel23** [comment] 2018-09-03 08:52
After adding the include headers I still get some linker errors: 

`unresolved external symbol "char const * __cdecl tensorflow::core::GetVarint32PtrFallback`

and a lot of member `google::protobuf ........ may not be initialized`

Any ideia what the problem could be? Is that a problem with the version of the protobuf?

**Comment by LJXLJXLJX** [comment] 2018-09-03 09:03
@Goldesel23 I guess you don't added the lib files to the project. 
tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib

**Comment by LJXLJXLJX** [comment] 2018-09-03 09:13
I think the my configuration is correct， but there are still some errors in loggin.h 
`TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
                        ==);  // Compilation error with CHECK_EQ(NULL, x)?
TF_DEFINE_CHECK_OP_IMPL(Check_NE, !=)  // Use CHECK(x == NULL) instead.
TF_DEFINE_CHECK_OP_IMPL(Check_LE, <=)
TF_DEFINE_CHECK_OP_IMPL(Check_LT, <)
TF_DEFINE_CHECK_OP_IMPL(Check_GE, >=)
TF_DEFINE_CHECK_OP_IMPL(Check_GT, >)
`
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E0040	应输入标识符	tf_test	d:\tensorflow\tensorflow\core\platform\default\logging.h	231

**Comment by Goldesel23** [comment] 2018-09-03 12:48
Actually I did! But I got those linking errors.

**Comment by taotaolin** [comment] 2018-09-12 08:09
> I am having the same issue

I am having the same issue,how to solve it?。

**Comment by taotaolin** [comment] 2018-09-27 00:32
> @Goldesel23 I guess you don't added the lib files to the project.
> tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib


but i don't have tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib file

**Comment by taotaolin** [comment] 2018-09-27 07:32
> @Goldesel23 I guess you don't added the lib files to the project.
> tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib

but i don't have tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib file

**Comment by taotaolin** [comment] 2018-09-27 07:33
@LJXLJXLJX but i don't have tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib file

**Comment by meteorcloudy** [comment] 2018-09-27 08:09
@taotaolin tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib should be generated when you build libtensorflow.so. Look into your `tensorflow\bazel-bin/tensorflow` directory.

**Comment by EdwardVincentMa** [comment] 2018-10-09 08:06
> > @Goldesel23 I guess you don't added the lib files to the project.
> > tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib
> 
> but i don't have tensorflow\bazel-bin\tensorflow\libtensorflow.so.if.lib file

这里又看到你了啊

**Comment by yinggaohai** [comment] 2019-03-09 02:36
I meet the same problem, how to solve it? Anyone can give me some good idea.

**Comment by NeroLoh** [comment] 2019-05-07 09:06
Enable the the 

> GRPC_SUPPORT

 handled this  for me. My Tensorflow version is 1.9.

**Comment by tilakrayal** [comment] 2022-09-25 07:13
@mm1860,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.10 and let us know if you are facing the same issue. Thank you!

**Closed** 2022-10-09 07:49 UTC
Labels: stat:contributions welcome, stat:awaiting response, stalled
