### ISSUE TITLE
[TF 2.0] Keras in graph mode crashes when fitting data with L2 regularizer set to 0.

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#26788] opened 2019-03-16 15:08 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Debian Stable**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **CPU, both TF-2.0.0a0 and tf-nightly-2.0-preview-2.0.0.dev20190315**
- Python version: **3.5.3**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**
The below code (using zero L2 regularization) fails with
```
AttributeError: Tensor.graph is meaningless when eager execution is enabled.
```

**Describe the expected behavior**
The code runs without a failure.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf

inputs = np.arange(10)
outputs = 2 * inputs

l2 = tf.keras.regularizers.L1L2(l2=0.0)
model = tf.keras.Sequential(
    [tf.keras.layers.Dense(1, input_shape=[1], kernel_regularizer=l2)]
)
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.MeanSquaredError(),
    metrics=[tf.keras.metrics.MeanSquaredError()]
)
model.fit(inputs, outputs)
```

**Other info / logs**
- Running with `model.run_eagerly` works.
- Running with non-zero L2 regularization works.

The problem is in https://github.com/tensorflow/tensorflow/blob/b57c7d71eff5914a503d15130cb90a240b3bcf40/tensorflow/python/keras/engine/network.py#L651
where a `ops.get_default_graph()` is called.

The problem is probably connected to the fact that L1L2 regularizer returns an explicit 0 (`K.constant(0.)`) when no l1/l2 is set (while otherwise summing weights and applying l1/l2).

**Comment by omalleyt12** [comment] 2019-03-19 17:52
Thanks for the bug! I was able to reproduce, looking into now

**Comment by jvishnuvardhan** [comment] 2019-08-08 23:12
I could not reproduce the issue with `!pip install tf-nightly-gpu-2.0-preview==2.0.0.dev20190808`. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/5b56a644fd9e48c4cdde180460950b66/tf26788.ipynb).

Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-08-08 23:12 UTC
Labels: 2.0.0-alpha0, comp:keras, type:bug
