### ISSUE TITLE
My GCP instance runs around 3 times slower than Gcolab with same configs

### ISSUE THREAD

**Issue by YeYuanS** [tensorflow/tensorflow#29375] opened 2019-06-03 22:23 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS
- TensorFlow version (use command below): b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.8
- CUDA/cuDNN version: CUDA 10.0/cuDNN 7.6
- GPU model and memory: T4 GPU with 15079MB memory

**Describe the current behavior**
I have an `GCP instance` with T4 GPU with same `tensorflow` `keras` `CUDA` version as `Gcolab`. However, for the same piece of code, my GCP instance is more than 3 times slower than `Gcolab`. Can anyone please give any clue that what should I do to improve the performance of my GCP instance. Thanks!
#### Log on my GCP instance
```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-06-03 14:37:25.721579: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-06-03 14:37:25.983647: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-03 14:37:25.986134: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x43fea10 executing computations on platform CUDA. Devices:
2019-06-03 14:37:25.986176: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-06-03 14:37:26.015456: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000160000 Hz
2019-06-03 14:37:26.016362: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4468690 executing computations on platform Host. Devices:
2019-06-03 14:37:26.016393: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-03 14:37:26.016745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
totalMemory: 14.73GiB freeMemory: 14.52GiB
2019-06-03 14:37:26.016772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-03 14:37:26.018593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-03 14:37:26.018618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-03 14:37:26.018625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-03 14:37:26.018699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14127 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
Epoch 1/5
2019-06-03 14:37:28.721949: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
600000/600000 [==============================] - 5s 8us/sample - loss: 10.2455 - acc: 0.3423
Epoch 2/5
600000/600000 [==============================] - 4s 6us/sample - loss: 7.3609 - acc: 0.5225
Epoch 3/5
600000/600000 [==============================] - 4s 7us/sample - loss: 5.8075 - acc: 0.6186
Epoch 4/5
600000/600000 [==============================] - 4s 7us/sample - loss: 5.4575 - acc: 0.6382
Epoch 5/5
600000/600000 [==============================] - 5s 8us/sample - loss: 5.3016 - acc: 0.6465
```
#### Log on Gcolab
```
Epoch 1/5
600000/600000 [==============================] - 2s 3us/sample - loss: 10.2666 - acc: 0.3293
Epoch 2/5
600000/600000 [==============================] - 2s 3us/sample - loss: 7.5881 - acc: 0.4941
Epoch 3/5
600000/600000 [==============================] - 2s 3us/sample - loss: 7.2098 - acc: 0.5236
Epoch 4/5
600000/600000 [==============================] - 2s 3us/sample - loss: 6.8803 - acc: 0.5298
Epoch 5/5
600000/600000 [==============================] - 2s 3us/sample - loss: 6.1390 - acc: 0.5506
<tensorflow.python.keras.callbacks.History at 0x7f708c110a20>
```
**Describe the expected behavior**
The performance on my GCP instance should be the same with Gcolab since everything is the same

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images.repeat(10, axis=0)
train_labels = train_labels.repeat(10, axis=0)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5, batch_size=60000)
```
**Other info / logs**
#### My GCP instance info
![Screen Shot 2019-06-03 at 2 53 17 PM](https://user-images.githubusercontent.com/41984177/58838297-23861080-8613-11e9-827c-70eb8fa1923a.png)
![Screen Shot 2019-06-03 at 2 58 08 PM](https://user-images.githubusercontent.com/41984177/58838309-2aad1e80-8613-11e9-9617-c1fdcae7bdb7.png)
![Screen Shot 2019-06-03 at 3 00 14 PM](https://user-images.githubusercontent.com/41984177/58838319-33055980-8613-11e9-813a-784cabffe8a1.png)
![Screen Shot 2019-06-03 at 2 58 28 PM](https://user-images.githubusercontent.com/41984177/58838327-3b5d9480-8613-11e9-9a69-7ce7cdd3819a.png)

#### Gcolab info
![Screen Shot 2019-06-04 at 9 54 30 AM](https://user-images.githubusercontent.com/41984177/58898181-d9526d00-86ae-11e9-9a1b-da6ab5de79ea.png)

**Comment by lgeiger** [comment] 2019-06-03 23:15
Could you remove the following lines and check if the performance difference is still there?
```python
import keras
print(keras.__version__)
```
`import keras` and `from tensorflow import keras` execute different code paths, thus mixing both can lead to unexpected behaviour.

**Comment by YeYuanS** [comment] 2019-06-04 16:57
@lgeiger Thanks for the reply, I update the script and the results are similar. Gcolab is still much faster than my GCP instance

**Comment by ymodak** [comment] 2019-06-10 18:45
Closing this issue since its resolved. Feel free to reopen if still have further problems. Thanks!

**Closed by ymodak** 2019-06-10 18:45 UTC
Labels: comp:keras, type:support
