### ISSUE TITLE
no protobuf package for macos Python 3.6

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#15417] opened 2017-12-16 20:33 UTC
Following instructions on
https://www.tensorflow.org/install/install_mac

`pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp35-none-macosx_10_11_x86_64.whl
`

This doesn't work for Python 3.6 with error
`protobuf-3.1.0-cp35-none-macosx_10_11_x86_64.whl is not a supported wheel on this platform.
`
If I just change URL cp36, there's no such file

```pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl

  Could not install requirement protobuf==3.1.0 from https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl
Could not install requirement protobuf==3.1.0 from https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl for URL https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp36-none-macosx_10_11_x86_64.whl

```

**Comment by tensorflowbutler** [comment] 2017-12-17 07:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gunan** [comment] 2017-12-18 05:56
Looks like this is something we missed.
@jhseu FYI

**Comment by jhseu** [comment] 2017-12-18 21:19
We don't build protobuf versions anymore, so we should probably just delete that from the instructions.

**Comment by yaroslavvb** [comment] 2017-12-18 22:42
So what's the recommended version of getting cpp version of protobuf? The default python version is slow (ie, timeline generation takes forever)

**Comment by jhseu** [comment] 2017-12-20 00:49
The protobuf team has committed to building it for Linux upon every release to PyPI. For Mac, users will have to build it on their own.

**Comment by jhseu** [comment] 2017-12-20 00:50
I deleted the mention of it in our documentation internally, and it should be reflected in the next push.

**Closed** 2017-12-20 00:50 UTC
Labels: stat:awaiting tensorflower

**Comment by kartiknagappa** [comment] 2018-02-27 19:22
I still see the mention of `Protobuf pip package 3.1` here:<br> https://www.tensorflow.org/install/install_mac

Running the command listed under Python 3.n results in an error:<br>`protobuf-3.1.0-cp35-none-macosx_10_11_x86_64.whl is not a supported wheel on this platform.`

**Comment by black-puppydog** [comment] 2018-03-20 15:31
Just to clarify: this means that for linux the default `pip install protobuf` should just work fine? Asking because we're debugging some slow data loading here at the moment...
