### ISSUE TITLE
AutoGraph could not transform function

### ISSUE THREAD

**Issue by Volker-Weissmann** [tensorflow/tensorflow#37670] opened 2020-03-17 17:11 UTC
I have tried to reproduce https://www.tensorflow.org/guide/function , and got a "Please report this to the TensorFlow team." message:

```
#!/usr/bin/env python
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import os
assert os.getenv("AUTOGRAPH_VERBOSITY") == "10"
@tf.function
def add(a, b):
  return a + b
add(tf.ones([2, 2]), tf.ones([2, 2]))
```

output:

> 2020-03-17 18:06:18.294500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> 2020-03-17 18:06:19.371349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-03-17 18:06:19.384766: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.385191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
> coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
> 2020-03-17 18:06:19.385217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> 2020-03-17 18:06:19.386622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-03-17 18:06:19.387892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-03-17 18:06:19.388198: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-03-17 18:06:19.389675: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-03-17 18:06:19.390453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-03-17 18:06:19.393493: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-03-17 18:06:19.393632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.394206: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.394571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2020-03-17 18:06:19.394880: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
> 2020-03-17 18:06:19.414984: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3301330000 Hz
> 2020-03-17 18:06:19.415262: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55714b447370 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-03-17 18:06:19.415294: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-03-17 18:06:19.415474: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.416213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
> coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
> 2020-03-17 18:06:19.416246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> 2020-03-17 18:06:19.416275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-03-17 18:06:19.416299: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-03-17 18:06:19.416319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-03-17 18:06:19.416337: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-03-17 18:06:19.416369: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-03-17 18:06:19.416392: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-03-17 18:06:19.416469: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.417223: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.417977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2020-03-17 18:06:19.418016: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> 2020-03-17 18:06:19.888411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-03-17 18:06:19.888453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
> 2020-03-17 18:06:19.888461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
> 2020-03-17 18:06:19.888673: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.889087: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.889446: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-03-17 18:06:19.889799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5327 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2020-03-17 18:06:19.891138: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55715b807340 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2020-03-17 18:06:19.891155: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
> WARNING:tensorflow:AutoGraph could not transform <function add at 0x7f2cdacf68b0> and will run it as-is.
> Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
> Cause: Bad argument number for Name: 3, expecting 4
> 
> 

**System information** 
- Have I written custom code: No
- OS Platform and Distribution: Arch Linux
- TensorFlow installed from: pacman -S python-tensorflow-cuda
- TensorFlow version (use command below): GIT_VERSION="unknown" VERSION=2.1.0
- Python version: 3.8.2
- CUDA/cuDNN version: Output of nvcc --version :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
- GPU model and memory: GeForce GTX 1060 6GB

**Comment by foxik** [comment] 2020-03-18 07:34
I just tried TF 2.1.0 on Linux, Python 3.7.3, and everything works.

It is surprising that you have TF 2.1 on Python 3.8, given that the official 2.1 packages do not support Python 3.8. Maybe Arch Linux compiles their own versions? But that may be the cause of the problem.

**Comment by Volker-Weissmann** [comment] 2020-03-20 22:11
You're right, TF 2.x does not support Python 3.8 as written here: https://www.tensorflow.org/install
I use TF 2.1 because it's the newest official version and python 3.8 because it is the newest official version and installing an older version of Python including tensorflow and other python packages is quite a hassle under arch linux. You can either close this issue or rename this issue to "feature request: support Python 3.8"

**Comment by foxik** [comment] 2020-03-21 14:46
BTW, TF 2.2 does support Python 3.8 and a rc1 is already available, so you can just `pip install tensorflow==2.2.0rc1` with working Python 3.8 support.

**Comment by Volker-Weissmann** [comment] 2020-03-21 15:03
Thank you. I have also flagged the arch package as out of date (here: https://www.archlinux.org/packages/community/x86_64/tensorflow/). I included a link to this thread in the message to the arch tensorflow maintainer, because I couldn't find another source that said that TF 2.2. support Python 3.8.

**Comment by foxik** [comment] 2020-03-21 15:07
The Github release https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc1 contains information about Python 3.8 being available for Windows and Linux (OS X support should be coming soon I believe).

**Comment by Volker-Weissmann** [comment] 2020-03-21 15:10
Ok, thank you.

**Comment by ravikyram** [comment] 2020-03-23 10:16
@Volker-Weissmann 

 Windows/Linux binaries for py3.8 are available in TF 2.2 .Can you try installing ``!pip install tensorflow==2.2.0rc1` and see still you are facing the issue?. Thanks!
`

**Comment by Volker-Weissmann** [comment] 2020-03-23 13:05
The autograph error no longer occurs if I use pip install tensorflow==2.2.0rc1 :+1: 

> 2020-03-23 14:02:45.808164: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-03-23 14:02:45.830684: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but th
> ere must be at least one NUMA node, so returning NUMA node zero                                                                                            
> 2020-03-23 14:02:45.831287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
> coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
> 2020-03-23 14:02:45.831384: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: lib
> cudart.so.10.1: cannot open shared object file: No such file or directory                                                                                  
> 2020-03-23 14:02:45.901102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-03-23 14:02:45.929450: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-03-23 14:02:45.936238: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-03-23 14:02:45.990984: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-03-23 14:02:45.998184: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-03-23 14:02:46.090721: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-03-23 14:02:46.090760: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing librarie
> s mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and se
> tup the required libraries for your platform.                                                                                                              
> Skipping registering GPU devices...
> 2020-03-23 14:02:46.091027: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled
>  to use: AVX2 FMA                                                                                                                                          
> 2020-03-23 14:02:46.111318: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3301250000 Hz
> 2020-03-23 14:02:46.111578: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fafe0000b60 initialized for platform Host (this does not guaran
> tee that XLA will be used). Devices:                                                                                                                       
> 2020-03-23 14:02:46.111593: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-03-23 14:02:46.112797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-03-23 14:02:46.112807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]

**Comment by ravikyram** [comment] 2020-03-24 04:08
@Volker-Weissmann 

Please, let me know if we can close this issue since it looks to be fixed. Thanks!

**Closed** 2020-03-24 09:58 UTC
Labels: stat:awaiting response, type:bug
