### ISSUE TITLE
GPU does not work 

### ISSUE THREAD

**Issue by Chugua** [tensorflow/tensorflow#49190] opened 2021-05-14 10:37 UTC
```
model.compile(

**Comment by bhack** [comment] 2021-05-14 13:11
Can you share a very very minimal standalone code example that we could copy, paste and run or a Colab to reproduce this?
Please fill also the ISSUE template as it was removed.

Thanks.

**Comment by Chugua** [comment] 2021-05-14 13:21
> Can you share a very very minimal standalone code example that we could copy, paste and run or a Colab to reproduce this?
> Please fill also the ISSUE template as it was removed.
> 
> Thanks.

You can have an access through my Google Drive: https://drive.google.com/drive/folders/10KVkoMz4p5siSrO2LGWP0BU0pYjX_7U2?usp=sharing

**Comment by bhack** [comment] 2021-05-14 13:27
Please minimize your code surface with a single minimal Colab example to reproduce this cause It will take time to just read and analyze long examples.

**Comment by Chugua** [comment] 2021-05-14 13:35
> Please minimize your code surface with a single minimal Colab example to reproduce this cause It will take time to just read and analyze long examples.

The code is whole, you can't only part of it. But in the beginning, there is also an Errors which was not before:

`!pip install tensorflow-gpu >> /dev/null`

```
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
```

`!pip install --upgrade grpcio >> /dev/null`

```
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.37.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
ERROR: tensorflow-gpu 2.5.0 has requirement grpcio~=1.34.0, but you'll have grpcio 1.37.1 which is incompatible.
```

**Comment by bhack** [comment] 2021-05-14 14:59
Please use the default TF 2.4.1 version in Colab (don't execute ``!pip install --upgrade tensorflow``):
```
import tensorflow as tf

print(tf.version.VERSION)
from tensorflow.python.client import device_lib

device_lib.list_local_devices()
```
Wth the new TF 2.5.0 version you will not have the GPU available in Colab (probably CUDA versions misalignment)

You can close this and subscribe and upvote https://github.com/googlecolab/colabtools/issues/2013

**Comment by Chugua** [comment] 2021-05-14 15:02
> Please use the default TF 2.4.1 version in Colab (don't execute `!pip install --upgrade tensorflow`):
> 
> ```
> import tensorflow as tf
> 
> print(tf.version.VERSION)
> from tensorflow.python.client import device_lib
> 
> device_lib.list_local_devices()
> ```
> 
> Wth the new TF 2.5.0 version you will not have the GPU available in Colab (probably CUDA versions misalignment)
> 
> You can close this and subscribe and upvote [googlecolab/colabtools#2013](https://github.com/googlecolab/colabtools/issues/2013)

is it possible to use an older version of tf to continue my analyses?

**Comment by bhack** [comment] 2021-05-14 15:05
Yes don't execute any `pip install tensorflow`just use the `import` directly.

**Comment by Chugua** [comment] 2021-05-14 15:07
> Yes don't execute any `pip install tensorflow`just use the `import` directly.

How to import previous version of tf? Because I do need to use GPU in colab.

**Comment by bhack** [comment] 2021-05-14 15:08
The default Is already installed

**Comment by bhack** [comment] 2021-05-14 15:12
On your local setup `pip install tensorflow==2.4.1`

**Comment by bhack** [comment] 2021-05-14 16:55
Can we close this?

**Comment by pythonic2020** [comment] 2021-05-15 12:50
Hello,

I just installed tf 2.5.0 and also find that my GPU is suddenly not detected.  @bhack above wrote that could be caused by "(probably CUDA versions misalignment)."  Could we get more info on that misalignment?  Will a future update of 2.5.0 correct this misalignment?  Must I update the various CUDA-related NVIDIA packages I installed to correct the problem?  

Is re-installing tf 2.4.1 using pip the only current way to get my GPU back?

Thank you...

**Comment by bhack** [comment] 2021-05-15 13:04
TF 2.5.0 pip works with Cuda 11.2

**Comment by pythonic2020** [comment] 2021-05-15 13:11
Thank you for responding.  

Hmm.  I have 11.3 installed.  What should i do?  Is there a way to downgrade CUDA to 11.2?

I just downgraded tf to 2.4.1 (and tensorflow-io) and my GPU is recognized again, thank heavens.

**Comment by bhack** [comment] 2021-05-15 13:22
I only know that there was an issue compiling with 11.3 from sources. Probably you can try to comment at https://github.com/tensorflow/tensorflow/pull/48803

**Comment by pythonic2020** [comment] 2021-05-15 13:24
Ok, thanks for the info.

**Comment by tilakrayal** [comment] 2021-05-17 06:10
@Chugua ,

In order to reproduce the issue reported here, could you please provide the Tensorflow version,complete code and the dataset you are using. Thanks!

**Closed** 2021-05-17 06:20 UTC
Labels: comp:gpu, stat:awaiting response, type:performance
