### ISSUE TITLE
Tensor Flow gives different results on INTEL and AMD CPUs

### ISSUE THREAD

**Issue by GChaitanya2001** [tensorflow/tensorflow#56529] opened 2022-06-22 07:44 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

<s>source</s>

### Tensorflow Version

2.3

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

>= 3.6 

### Bazel version

<s>0.26.1</s>

### Current Behaviour?

I tried running a sample sqrt computation on INTEL and AMD CPUs. I used a tolerance of 0.0000001 i.e., the values are printed in the log output, only if the difference between corresponding values is >= 0.0000001.
The values obtained on INTEL and AMD CPUs are not matching.

#### Note: 
* Please refer this discussion for more details, https://discuss.tensorflow.org/t/tf-sqrt-computations-are-different-on-two-diff-cpu-architectures-intel-and-amd/10208
* the raw files generated by numpy sqrt computation by the provided script has no difference across both the architectures.

<s> Steps to reproduce building TF from source: ~~

* Used tensorflow 1.15.5 which is built from source ( [Build from source | TensorFlow](https://www.tensorflow.org/install/source#configuration_options)).
* Disabled all supports during ./configure step (XLA, CUDA, etc.,).
* Provided “-march=x86-64” for --copt and --host_copt flags while doing bazel build and set --config=v1. </s>

######  test.py
```shell
import numpy as np
import tensorflow.compat.v1 as tf

print(tf.__version__)
tf.disable_v2_behavior()
# float32 NumPy array
a = np.arange(100, dtype=np.float32)
# The same array with the same dtype in TensorFlow
a_tf = tf.constant(a, dtype=tf.float32)
# Square root with NumPy
sqrt = np.sqrt(a)
sqrt.tofile('../np_exp/sqrt.raw')
# Square root with TensorFlow
with tf.Session() as sess:
    sqrt_tf = sess.run(tf.sqrt(a_tf))
    sqrt_tf.tofile('./sqrt.raw')
```

###### compare.py - script to compare raw files

```shell
import csv
import os
import argparse
import json
import numpy as np
import math
# import cv2
result_data = ''
tolrence = 0.0000001

np.set_printoptions(precision=17, suppress=True)

def csv_reader(abc1, abc2, ):
    reader1 = np.fromfile(abc1, dtype=np.float32)
    reader2 = np.fromfile(abc2, dtype=np.float32)
    #print(reader1)
    i = 0
    c = 0
    count = 0
    anti_count = 0
    isNan = 0
    try:
       for (index1, index2) in zip(np.nditer(reader1), np.nditer(reader2)):
           i = i + 1
           if math.isnan(index2):
                continue
           if abs(index1 - index2) >= tolrence:
               count = count + 1
               if count != 0:
                 print(str(index1) + " " + str(index2) + " " + str(i))
           else:
                anti_count = anti_count + 1
       if count != 0:
             print(abc1)
             print(abc2)
             print("Total Matches :  ", anti_count, "Mismatches  : ", count)

    except:
        pass
      
def list_files_from_dir(root):
    all_raw_list = list()
    for path, subdirs, files in os.walk(root):
        for name in files:
            if name not in ['model.cpp', 'model.bin', 'model_net.json']:
                 all_raw_list.append(os.path.join(path, name))

    return all_raw_list


def compare_all(dir1, dir2):
    list1 = list_files_from_dir(dir1)
    list2 = list_files_from_dir(dir2)
    list1.sort()
    list2.sort()
    for i in range(len(list1)):
        csv_reader(list1[i], list2[i])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='parser')
    parser.add_argument('-i1', '--input1', help='The path to the directory containing raw files.', required=True)
    parser.add_argument('-i2', '--input2', help='The path to the directory containing raw files', required=True)
    args = parser.parse_args()

    input1 = args.input1
    input2 = args.input2
    compare_all(input1, input2)

```
## Sample commands to run

* python3 test.py                        => script to run the sqrt computation
* python3 compare.py -i1 ./AMD -i2 ./INTEL     => compares the raw files generated by AMD and INTEL (transfer the raw files to one of the machines, ./AMD folder has raw files generated on AMD and ./INTEL has raw files generated on INTEL)

### Relevant log output

```shell
1.4142135 1.4142134 3
2.0 1.9999999 5
2.4494898 2.4494896 7
2.828427 2.8284268 9
3.0 2.9999998 10
3.162278 3.1622777 11
3.6055512 3.6055508 14
4.0 3.9999998 17
4.5825763 4.5825753 22
4.6904163 4.6904154 23
4.795831 4.7958307 24
4.8989797 4.898979 25
5.099019 5.0990186 27
5.1961527 5.196152 28
5.385165 5.3851647 30
5.656854 5.6568537 33
5.7445626 5.744562 34
5.830952 5.830951 35
6.0 5.9999995 37
6.0827627 6.0827622 38
6.324556 6.3245554 41
6.557439 6.557438 44
7.0000005 6.9999995 50
7.0710683 7.0710673 51
7.2111025 7.2111015 53
7.2801104 7.280109 54
7.416199 7.4161983 56
8.0 7.9999995 65
8.062258 8.062257 66
8.124039 8.124038 67
8.306624 8.306623 70
8.42615 8.426149 72
8.5440035 8.544003 74
8.6602545 8.660254 76
9.0 8.999999 82
9.055386 9.055385 83
9.110435 9.110433 84
9.165153 9.165151 85
9.273619 9.273618 87
9.380833 9.380831 89
9.486833 9.486834 91
9.539392 9.5393915 92
9.591662 9.591661 93
./AMD/sqrt.raw
./INTEL/sqrt.raw
Total Matches :   57 Mismatches  :  43
```
</details>

**Comment by tilakrayal** [comment] 2022-06-22 16:09
Hi @GChaitanya2001,
Tensorflow version 1.x is not actively supported. Hence, kindly update to the latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

**Comment by GChaitanya2001** [comment] 2022-06-23 06:39
Hi @tilakrayal,
Thank you for the response. Is the support provided for TF version 2.3? Please let me know. Thanks!

**Comment by tilakrayal** [comment] 2022-06-24 13:03
@GChaitanya2001,
Its unlikely for TF 2.3 version to receive any bug fixes except when we have security patches. There is a high possibility that this was fixed with later TF versions. 
As there is no difference in results and the bug was resolved on tensorflow latest stable v2.9, we request to continue with the same version. Thank you!

**Comment by GChaitanya2001** [comment] 2022-06-27 04:32
Hi @tilakrayal,
Thank you for the response. I am trying build Tensorflow from source. How can I provide MKL (one-DNN.,) built from source while building Tensorflow from source? Please let me know. Thank you!

**Comment by tilakrayal** [comment] 2022-06-29 05:06
@GChaitanya2001,
Related issue #56586 was already escalated. Kindly feel free to move this issue to closed status and follow #56586 for the updates. Thank you!

**Comment by GChaitanya2001** [comment] 2022-07-01 13:29
Hi @tilakrayal,

I had to reopen this issue as I wanted to refer the code for a clarification. 

I tried converting the input tensors (which are in float32) in the above code (test.py) to float64 before running tf.Session and executed sess.run with float64 tensors and finally re-converted back the float64 result to float32. I used TF v2.3 to do this. The final re-converted answer of TF v2.3 for this modified test.py is matching with TF v2.9 answer of the original test.py code where only float32 tensors are used. And now for this modified test.py code, TF v2.3 doesn't have any difference across INTEL and AMD. Does that mean TF v2.9 is implicitly using 64-bit math even when the tensors are in float32 while using tf.session? Please let me know your views on this. 

**Note**: Please find the below code for this experiment, test.py (modified)
```shell
import numpy as np
import tensorflow as tf
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'   #debug mode
np.set_printoptions(precision=7, floatmode="fixed")

print ("We are using Tensorflow version", tf.__version__)

print(tf.executing_eagerly())
tf.compat.v1.disable_v2_behavior()
print(tf.executing_eagerly())

# float32 NumPy array
a = np.arange(100, dtype=np.float32)
# The same array with the same dtype in TensorFlow
a_tf = tf.constant(a, dtype=tf.float32)

############### Square root with NumPy
sqrt = np.sqrt(a)
print(sqrt)
print(type(sqrt))
sqrt.tofile('../np_exp/sqrt.raw')
a.tofile('../np_exp/a_np.raw')


############### Square root with TensorFlow
with tf.compat.v1.Session() as sess:
    print(a_tf.dtype)
    a_tf = tf.cast(a_tf, tf.float64)
    print(a_tf.dtype)

    sqrt_tf = sess.run(tf.sqrt(a_tf))

    print(sqrt_tf)
    print(type(sqrt_tf), sqrt_tf.dtype)

    sqrt_tf = sqrt_tf.astype('float32')

    print(sqrt_tf)
    print(type(sqrt_tf), sqrt_tf.dtype)

    sqrt_tf.tofile('./sqrt.raw')
```

**Comment by tilakrayal** [comment] 2022-07-11 04:23
@GChaitanya2001,
I was trying to execute the provided and found a different error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/21ca8f469acb736ef099e98d7c174cb8/untitled424.ipynb) and share the dependencies. Thank you!

**Comment by GChaitanya2001** [comment] 2022-07-11 04:51
Hi @tilakrayal,
Please create folder structure, as mentioned below,
```shell
-- tf_exp
    -- AMD
    -- INTEL
-- np_exp 
   -- AMD
   -- INTEL
```
Run the script inside **tf_exp** folder, it will create relevant raw dumps in the respective folders. Change the './AMD/ans.raw' to './INTEL/ans.raw' inside test.py while using INTEL CPU. You can change the relevant paths accordingly.

Thank you!

**Comment by GChaitanya2001** [comment] 2022-07-14 05:40
Hi @tilakrayal,

I explored the Tensorflow source code and finally got a TF build which wasn't showing any difference across INTEL and AMD CPUs. I disabled EIGEN_FAST_MATH macro while building TF from source which worked (Tried this for v1.15).

Thank you!

**Comment by tilakrayal** [comment] 2022-08-17 06:13
@GChaitanya2001,
Glad the issue is resolved for you, please feel free to move this to closed status.

**Closed** 2022-08-17 08:50 UTC
Labels: stat:awaiting response, type:bug, comp:apis, TF 2.9

**Comment by xinario** [comment] 2022-10-21 21:13
@GChaitanya2001 Hey, I came across the same inconsistency issue when building TF from source. Do you mind sharing where did you make the change to disable the macro? Thanks.

**Comment by GChaitanya2001** [comment] 2022-10-22 09:05
@xinario Hi, you can disable the macro by setting the macro to 0. You can use a -copt option for doing that while building tensorflow from source.

**Comment by xinario** [comment] 2022-10-25 22:32
@GChaitanya2001 Thank you very much for the reply. Do you mind explain a bit the cause for the difference, like why the EIGEN_FAST_MATH would result this difference on different CPU? I also experienced tiny difference across a customized build across Mac and Windows. Wondering if there're other type of optimization going on there.
