### ISSUE TITLE
Unable to remove model from memory

### ISSUE THREAD

**Issue by acvander** [tensorflow/tensorflow#36703] opened 2020-02-12 17:28 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, it can be found in the following repository https://github.com/acvander/kaggle_real_or_not
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v2.1.0-rc2-17-ge5bf8de 2.1.0
- **Python version**:
3.7.5
- **CUDA/cuDNN version**:
10.2
- **GPU model and memory**:
1060 6GB
- **Exact command to reproduce**:
These are for data preprocessing

```python main.py --mode=preprocess```
```python main.py --mode=preprocess_bert```

This is the training command

```python main.py --mode=train_bert --model_dir=./tmp/k_bert --model_name=bert --epochs=2 --subset=0.25```

### Describe the problem
I believe this is a similar problem to #36587. Upon starting to train the second fold, the first model is not properly removed from memory and results in an OOM error.
I run the ```del``` command to delete the model and bert_layers as well as ```tf.keras.backend.clear_session()```
### Source code / logs
```
2020-02-12 12:22:44.782689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-02-12 12:22:44.784338: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvrtc.so.10.2: cannot open shared object file: No such file or directory
2020-02-12 12:22:44.784352: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
I0212 12:22:46.138824 139915467714688 train_bert.py:72] loading data
I0212 12:22:46.162351 139915467714688 train_bert.py:80] loading model
I0212 12:22:46.163624 139915467714688 train_bert.py:95] training fold #1
I0212 12:22:46.164219 139915467714688 resolver.py:79] Using /tmp/tfhub_modules to cache modules.
Train on 635 samples, validate on 1268 samples
Epoch 1/2
632/635 [============================>.] - ETA: 0s - loss: 0.5996 - f1_score: 0.6930   
Epoch 00001: val_f1_score improved from -inf to 0.75631, saving model to ./tmp/k_bert/bert_0.h5
635/635 [==============================] - 89s 141ms/sample - loss: 0.6001 - f1_score: 0.6929 - val_loss: 0.5407 - val_f1_score: 0.7563
Epoch 2/2
632/635 [============================>.] - ETA: 0s - loss: 0.4509 - f1_score: 0.8212 
Epoch 00002: val_f1_score improved from 0.75631 to 0.80126, saving model to ./tmp/k_bert/bert_0.h5
635/635 [==============================] - 51s 80ms/sample - loss: 0.4508 - f1_score: 0.8205 - val_loss: 0.4792 - val_f1_score: 0.8013
I0212 12:25:23.587857 139915467714688 train_bert.py:95] training fold #2
Train on 634 samples, validate on 1269 samples
Epoch 1/2
  8/634 [..............................] - ETA: 29:17WARNING:tensorflow:Can save best model only with val_f1_score available, skipping.
W0212 12:26:02.588592 139915467714688 callbacks.py:1018] Can save best model only with val_f1_score available, skipping.
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    app.run(main)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 99, in main
    subset=FLAGS.subset)
  File "/home/adam/machine_learning/real_or_not/training/train_bert.py", line 125, in train_bert
    callbacks=callbacks)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 85, in distributed_function
    per_replica_function, args=args)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 763, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1819, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2164, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 433, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 312, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 273, in _process_single_batch
    model.optimizer.apply_gradients(zip(grads, trainable_weights))
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 434, in apply_gradients
    self._create_slots(var_list)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/adam.py", line 149, in _create_slots
    self.add_slot(var, 'm')
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 599, in add_slot
    initial_value=initial_value)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 65, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2080, in creator
    return next_creator(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 65, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2080, in creator
    return next_creator(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 65, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2080, in creator
    return next_creator(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 65, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 485, in variable_capturing_scope
    lifted_initializer_graph=lifted_initializer_graph, **kwds)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 178, in __init__
    initial_value() if init_from_fn else initial_value,
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/init_ops_v2.py", line 98, in __call__
    return array_ops.zeros(shape, dtype)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2446, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 233, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3244, in fill
    _ops.raise_from_not_ok_status(e, name)
  File "/home/adam/.pyenv/versions/real-or-not/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4096,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Fill] name: Adam/bert_model/encoder/layer_4/output/kernel/m/Initializer/zeros/
```

**Comment by gadagashwini** [comment] 2020-02-13 06:12
@acvander, Can you provide the code snippet to reproduce the issue. Thanks!

**Comment by acvander** [comment] 2020-02-13 18:52
```
def train_bert(model_dir: str = './tmp/bert_default',
               model_name: str = 'bert_default',
               shuffle: bool = True,
               fig_name: str = 'bert',
               epochs: int = 3,
               subset: float = 1.0):
    # load data
    logging.info('loading data')
    with shelve.open('./tmp/bert_data/bert_shelf') as shelf:
        train_input = shelf['train_input']
        train_output = shelf['train_output']
        test_input = shelf['test_input']
        max_token_len = shelf['max_token_len']
        bert_url = shelf['bert_url']

    logging.info('loading model')
    bert = hub.load(bert_url)
    bert_layer = hub.KerasLayer(bert_url, trainable=True)
    model = build_bert_model(bert_layer, max_len=max_token_len)()
    initial_model_path = os.path.join(model_dir, 'initial_model.h5')
    model.save(initial_model_path)

    os.makedirs(model_dir, exist_ok=True)

    splitter = StratifiedKFold(n_splits=3, shuffle=shuffle, random_state=2020)

    # Subset data for debugging
    train_output = train_output[:int(subset * len(train_output))]

    x = range(len(train_output))
    k_folds = list(splitter.split(
        x, train_output[:, 0]))  # only need to use one value for grouping

    histories = []
    for i, (valid_idxs, train_idxs) in enumerate(k_folds):
        logging.info('training fold #{}'.format(i + 1))

        model = load_model(initial_model_path,
                           custom_objects={'KerasLayer': hub.KerasLayer},
                           compile=False)

        model_path = os.path.join(model_dir, '{}_{}.h5'.format(model_name, i))

        # compile modelf
        compile_model(model, learn_rate=2e-6, model_path=model_path)

        # separate data
        fold_train_input = {
            key: val[train_idxs]
            for (key, val) in train_input.items()
        }
        fold_train_output = train_output[train_idxs]
        fold_valid_input = {
            key: val[valid_idxs]
            for (key, val) in train_input.items()
        }
        fold_valid_output = train_output[valid_idxs]

        callbacks = create_callbacks(model_path=model_path)

        history = model.fit(fold_train_input,
                            fold_train_output,
                            validation_data=(fold_valid_input,
                                             fold_valid_output),
                            epochs=epochs,
                            batch_size=8,
                            callbacks=callbacks)
        plot_training_data(
            history.history,
            '{}_{}.png'.format(os.path.join(model_dir, fig_name), i))
        histories.append(history)

    plot_k_fold_data(
        histories, '{}_combined.png'.format(os.path.join(model_dir, fig_name)))

    return
```

**Comment by gadagashwini** [comment] 2020-02-17 11:02
@acvander, Thanks for the code but looks like code is incomplete to replicate the reported issue. Please provide more information to debug. Thanks

**Comment by gadagashwini** [comment] 2020-02-28 11:33
@acvander, Any update on reproducible code snippet. Thanks

**Comment by gadagashwini** [comment] 2020-03-06 06:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-03-06 06:18 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support
