### ISSUE TITLE
ImportError: cannot import name gen_collective_ops

### ISSUE THREAD

**Issue by Krishnaprasad-T** [tensorflow/tensorflow#20523] opened 2018-07-03 16:09 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:centos-release-7-3.1611.el7.centos.x86_64
- **TensorFlow installed from (source or binary)**:Source
- **TensorFlow version (use command below)**:1.7
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**:0.11.0
- **GCC/Compiler version (if compiling from source)**: 7.2.0
- **CUDA/cuDNN version**:No (CPU only)
- **GPU model and memory**: No
- **Exact command to reproduce**: 

### Describe the problem
I am working on distributed tensorflow using horovod in CPU cluster mode.
Below is the run command used:
mpirun -x LD_LIBRARY_PATH -x OMP_NUM_THREADS -cpus-per-proc 20 --map-by socket --overscribe --report-bindings  -n 2 python  $python_script      --mkl=True --forward_only=False --num_batches=200 --kmp_blocktime=0 --num_warmup_batches=50 --num_inter_threads=$inter_op --distortions=False --optimizer=sgd --batch_size=$batch_size --num_intra_threads=$intra_op --data_format=NCHW --model=$MODEL --variable_update horovod --horovod_device cpu --data_dir=XXX

Error Stack:
 Traceback (most recent call last):
  File "/tensorflow/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 27, in <module>
    import benchmark_cnn
  File "/tensorflow/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 53, in <module>
    import variable_mgr
  File "/tensorflow/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 25, in <module>
    import allreduce
  File "/tensorflow/benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 28, in <module>
    from tensorflow.python.ops import collective_ops
  File "/.local/lib/python2.7/site-packages/tensorflow/python/ops/collective_ops.py", line 21, in <module>
    from tensorflow.python.ops import gen_collective_ops
ImportError: cannot import name gen_collective_ops

**Comment by karmel** [comment] 2018-07-11 20:04
Hi @Krishnaprasad-T -- tf_cnn_benchmarks expects the nightly release of TensorFlow when run from master. Can you try with the nightly version of TensorFlow (`pip install tf-nightly` or `pip install tf-nightly-gpu`)?

**Comment by tensorflowbutler** [comment] 2018-07-26 19:15
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by guileryu01** [comment] 2018-08-07 02:13
Same problem here. Here is the traceback when I import tensorflow.contrib with code in master:

```
import tensorflow.contrib
Traceback (most recent call last):
  Python Shell, prompt 11, line 1
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import distribute
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\__init__.py", line 22, in <module>
    from tensorflow.contrib.distribute.python.collective_all_reduce_strategy import CollectiveAllReduceStrategy
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\collective_all_reduce_strategy.py", line 24, in <module>
    from tensorflow.contrib.distribute.python import cross_tower_ops as cross_tower_ops_lib
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_ops.py", line 24, in <module>
    from tensorflow.contrib.distribute.python import cross_tower_utils
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_utils.py", line 31, in <module>
    from tensorflow.python.ops import collective_ops
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\python\ops\collective_ops.py", line 21, in <module>
    from tensorflow.python.ops import gen_collective_ops
builtins.ImportError: cannot import name 'gen_collective_ops'
```
Does the module gen_collective_ops never exist?

**Comment by karmel** [comment] 2018-08-07 17:30
@guileryu01 , if you are seeing the same issue, please provide the details requested in the issue template for yourself as well. As I note above, a possible cause is an older version of TF than the benchmark expects.

**Comment by guileryu01** [comment] 2018-08-07 17:48
@karmel I wasn't running the benchmark code. All I did was import tensorflow.contrib, although it hit the same error as above. Here is system information:

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: master (as of 8/4/2018)
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: Visual Studio 2017
- **CUDA/cuDNN version**: 9.2/7.1
- **GPU model and memory**: GTX 1080
- **Exact command to reproduce**: import tensorflow.contrib


### Describe the problem
ImportError when importing tensorflow.contrib
### Source code / logs
```
import tensorflow.contrib
Traceback (most recent call last):
  Python Shell, prompt 11, line 1
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import distribute
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\__init__.py", line 22, in <module>
    from tensorflow.contrib.distribute.python.collective_all_reduce_strategy import CollectiveAllReduceStrategy
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\collective_all_reduce_strategy.py", line 24, in <module>
    from tensorflow.contrib.distribute.python import cross_tower_ops as cross_tower_ops_lib
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_ops.py", line 24, in <module>
    from tensorflow.contrib.distribute.python import cross_tower_utils
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_utils.py", line 31, in <module>
    from tensorflow.python.ops import collective_ops
  File "C:\Anaconda3\envs\python36\Lib\site-packages\tensorflow\python\ops\collective_ops.py", line 21, in <module>
    from tensorflow.python.ops import gen_collective_ops
builtins.ImportError: cannot import name 'gen_collective_ops'
```

**Comment by karmel** [comment] 2018-08-07 20:00
@guptapriya -- this seems to be related to dependencies introduced for distribution; is this something you've seen? My guess is there's some version mismatch or missing flag (cc @gunan )-- any ideas?

**Comment by guptapriya** [comment] 2018-08-08 21:32
hey @karmel - thanks for bringing to attention. collective ops was added to tf_cnn_benchmarks by @poxvoculi and @yuefengz added them to the distribution strategy - will let them address why this is failing imports

**Comment by tensorflowbutler** [comment] 2018-08-24 21:52
Nagging Assignees @karmel, @yuefengz, @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-08-27 20:43
@martinwicke @allenlavoie 
Not sure where the issue is, for me things seem to be working.
Is it possible this is happening because you did not run "import tensorflow" first?
Or are you running this as:
```
import tensorflow as tf
import tensorflow.contrib as tfc
```

**Comment by tensorflowbutler** [comment] 2018-09-11 18:53
Nagging Assignees @karmel, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karmel** [comment] 2018-09-26 19:59
@Krishnaprasad-T -- is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-11 18:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-26 12:47
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-10-26 21:11
Closing due to staleness. Please use the latest version for TensorFlow and build again. Feel free to open a new issue if it still persists. Thanks!

**Closed by ymodak** 2018-10-26 21:11 UTC
Labels: stat:awaiting response
