### ISSUE TITLE
[TF2.1][TPU] Connection reset by peer during training

### ISSUE THREAD

**Issue by EthanPhan** [tensorflow/tensorflow#38257] opened 2020-04-06 01:46 UTC
**System information** 
- TensorFlow version: 2.1
- Python version: 3.6.9
- TPU version: - 2.0

**Describe the current behavior**
I'm using TPU to train a model for Named Entity Disambiguation task using a BERT model from the huggingface. During training I randomly get this error saying the connection is reset by peer.

**Standalone code to reproduce the issue** 
Training code: 
```
with strategy.scope():
    model, ent_model, comp_model = distilbert_ned(seq_len_1 = entity_text_len,
                                                  seq_len_2 = company_text_len,
                                                  num_finetune_bert_layers=0)
    adam = tf.keras.optimizers.Adam(clipnorm=.5, lr=lr)
    model.compile(optimizer=adam,
                  loss=triplet_loss,
                  )
    if cuda_dev == 'tpu':
        cb = ACC_Callback(comp_model, ent_model, model, val_set, unique_entities, best_model_dir='gs://{}/ned/out/'.format(cloud_bucket,))
    else:
        cb = ACC_Callback(comp_model, ent_model, model, val_set, unique_entities, best_model_dir='./')
    ds_train, ds_val = get_tfrecord_dataset(batch_size)
    model.fit(ds_train,
          validation_data=ds_val,
          epochs=8, verbose=1,
          callbacks=[cb],
    )
```

What the callback does is it calls `comp_model.predict()` and `ent_model.predict` to make predictions and calculate the accuracy on the validation set.

**Other info / logs**:
```
2020-04-05 06:25:27.447473: E tensorflow/core/common_runtime/eager/context.cc:459] Failed to register function remotely due to Connection reset by peer
This shouldn't happen, please file a bug to tensorflow team.
2020-04-05 06:25:41.771929: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:79] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find a context_id matching the specified one (4329004720033007128). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1586067941.771818685","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (4329004720033007128). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}
Traceback (most recent call last):
  File "train_ned.py", line 696, in <module>
    model.save_weights('last_ned.tf')
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1123, in save_weights
    self._trackable_saver.save(filepath, session=session)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1168, in save
    file_prefix=file_prefix_tensor, object_graph_tensor=object_graph_tensor)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1108, in _save_cached_when_graph_building
    object_graph_tensor=object_graph_tensor)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1076, in _gather_saveables
    feed_additions) = self._graph_view.serialize_object_graph()
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 381, in serialize_object_graph
    trackable_objects, path_to_root)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 344, in _serialize_gathered_objects
    object_names=object_names)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 96, in _serialize_slot_variables
    or hasattr(trackable, "_create_or_restore_slot_variable")):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py", line 830, in __getattr__
    return super(TPUVariableMixin, self).__getattr__(name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py", line 392, in __getattr__
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd3173f00b8>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Connection reset by peer [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd3173e6c18>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Connection reset by peer [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd3173e67b8>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Connection reset by peer [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd3173e6358>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Connection reset by peer [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd31735aeb8>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Connection reset by peer [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fd31735a4e0>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "train_ned.py", line 685, in <module>
    if False:
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
2020-04-06 01:31:10.561321: E tensorflow/core/common_runtime/eager/context.cc:459] Failed to register function remotely due to Unable to find a context_id matching the specified one (10922957604321251792). Perhaps the worker was restarted, or the context was GC'd?
This shouldn't happen, please file a bug to tensorflow team.
    use_multiprocessing=use_multiprocessing)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397, in fit
    prefix='val_')
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 771, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 302, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "train_ned.py", line 619, in on_epoch_end

  File "train_ned.py", line 636, in get_company_embeddings
    return entity_embd
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/util/nest.py", line 568, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/util/nest.py", line 568, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 130, in _non_none_constant_value
    constant_value = tensor_util.constant_value(v)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 822, in constant_value
    return tensor.numpy()
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 942, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 910, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.AbortedError: RecvTensor expects a different device incarnation: 15132506705170928619 vs. 17767066468299283119. Your worker job ("/job:tpu_worker/replica:0/task:0") was probably restarted. Check your worker job for the reason why it was restarted.
Additional GRPC error information:
{"created":"@1586136670.549528961","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"RecvTensor expects a different device incarnation: 15132506705170928619 vs. 17767066468299283119. Your worker job ("/job:tpu_worker/replica:0/task:0") was probably restarted. Check your worker job for the reason why it was restarted.","grpc_status":10}
2020-04-06 01:31:11.529445: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:79] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find a context_id matching the specified one (10922957604321251792). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1586136671.529360273","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (10922957604321251792). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fc6e47cdef0>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unable to find a context_id matching the specified one (10922957604321251792). Perhaps the worker was restarted, or the context was GC'd? [Op:DeleteIterator]
Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7fc700031c18>>
Traceback (most recent call last):
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ethan/SEER/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unable to find a context_id matching the specified one (10922957604321251792). Perhaps the worker was restarted, or the context was GC'd? [Op:DeleteIterator]
```

**Comment by amahendrakar** [comment] 2020-04-06 12:29
@EthanPhan,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by EthanPhan** [comment] 2020-04-06 13:02
@amahendrakar I can give you the code but not the data, do you still need it?

**Comment by amahendrakar** [comment] 2020-04-08 17:38
@EthanPhan,
I tried to reproduce the issue, but I'm facing an error stating `NoSectionError: No section: 'IOB-format'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/dad3df4c05cfa3b874e8a14dadbdefd5/38257.ipynb).

Is it possible for you to provide a minimal reproducible code with a sample dataset? Thanks!

**Comment by amahendrakar** [comment] 2020-04-16 17:34
> @EthanPhan,
> I tried to reproduce the issue, but I'm facing an error stating `NoSectionError: No section: 'IOB-format'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/dad3df4c05cfa3b874e8a14dadbdefd5/38257.ipynb).
> 
> Is it possible for you to provide a minimal reproducible code with a sample dataset? Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-23 18:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-23 18:31 UTC
Labels: TF 2.0, comp:tpus, stalled, stat:awaiting response, type:bug

**Comment by innat** [comment] 2022-07-17 20:20
@amahendrakar I've just faced this issue with tf 2.6. The TPU resource may be exhausted and cause such issue. But during the time of training, it's frustrating. Please reopen the ticket.
