### ISSUE TITLE
Issues running jupyter notebook to do object detection api

### ISSUE THREAD

**Issue by theman162** [tensorflow/tensorflow#38783] opened 2020-04-22 05:57 UTC
Hi i have facing this issues and i am using tensorflow 2 cpu version and i have  AMD radeon graphics card in my laptop
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
Couldn't find program: 'bash'
%%bash 
cd models/research
pip install .
Couldn't find program: 'bash'

ImportError                               Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\AppData\Local\Programs\Python\Python37\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\AppData\Local\Programs\Python\Python37\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-6-cdfb01024084> in <module>
      4 import sys
      5 import tarfile
----> 6 import tensorflow as tf
      7 import zipfile
      8 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\vilsuresh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\vilsuresh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\vilsuresh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\vilsuresh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\vilsuresh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by ravikyram** [comment] 2020-04-22 07:56
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the[ latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Also, refer similar issues.
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by theman162** [comment] 2020-04-22 08:05
CPU intel core i1-6500u  and currently using the google colab for my project as gpu requires nividia support which my laptop does not support

**Comment by ravikyram** [comment] 2020-04-22 09:22
@theman162 

In order to expedite the trouble-shooting process, please provide colab link or  minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by oke-aditya** [comment] 2020-04-22 12:12
```
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
Couldn't find program: 'bash'
%%bash
cd models/research
pip install .
Couldn't find program: 'bash'
```

Please change to
```

%cd models/research/
! protoc object_detection/protos/*.proto --python_out=.

%cd models/research
! pip install .



```


- Since you are using google colab using %cd to change directory and ! when you use linux commands.

**Comment by ravikyram** [comment] 2020-05-05 03:36
@theman162 

was this resolved by following @oke-aditya suggestion? Please close the issue if it was resolved already. Thanks!

**Closed** 2020-05-19 05:44 UTC
Labels: stalled, stat:awaiting response, subtype:windows, type:build/install
