### ISSUE TITLE
TFLite 'Minimum' Operator

### ISSUE THREAD

**Issue by SaqibS** [tensorflow/tensorflow#17289] opened 2018-02-27 06:09 UTC
I have a fine-tuned MobileNet model, in frozen graph format. I ran Toco to create a TFLite model, but got the following error:

```Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: TensorFlowMinimum.```

Examining the ops in the graph, I see ones like `mobilenet_1.00_224/conv1_relu/Minimum`.

**Comment by aureliengervasi** [comment] 2018-03-01 15:32
Same issue on my side.

I have retrained a MobileNet model with Keras and converted it to TensorFlow. The model is ready for inference.

With `tensorflow==1.6.0.rc1`, it is the only operation which is said to be not supported.
I'm a bit suprised, as [the doc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md) says that this kind of ops "are usually removed from the graph".

**Comment by andrehentz** [comment] 2018-03-08 17:39
In most cast 'minimum' will be removed from the graph because it is only attached to const nodes. It seems this is not the case with the retraining of mobilenet with keras. Hopefully we will have an implementation of 'minimum' soon.

**Comment by tensorflowbutler** [comment] 2018-04-17 12:36
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by andrehentz** [comment] 2018-04-25 17:40
TensorflowMinimum should be supported now. Closing, but please reopen if you still find issues.

**Closed by andrehentz** 2018-04-25 17:40 UTC
Labels: comp:lite

**Comment by nixingyang** [comment] 2018-05-24 11:14
@SaqibS @aureliengervasi Did you manage to get rid of "TensorFlowMinimum" issue?

**Comment by nixingyang** [comment] 2018-06-07 16:38
@saeed68gm You may try to pull the latest TensorFlow from the master branch. Use "bazel run ***" command as mentioned here (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md) to convert the weights.

**Comment by saeed68gm** [comment] 2018-06-07 17:47
Thanks @nixingyang I tried that but the build was broken due to a gcc version issue. I don't know if it has been resolved since two days ago.

**Comment by saeed68gm** [comment] 2018-06-07 19:27
@nixingyang see this:
https://github.com/tensorflow/tensorflow/issues/19434#issuecomment-394651764

**Comment by saeed68gm** [comment] 2018-06-08 13:46
@nixingyang yeah, correct. I did that because libtensorflow_inference.so was failing to build on master so I had to revert. I will try a bit later and see if the issues have been fixed for that. Do we know the commit that fixed this? I may just cherry-pick that and try.

**Comment by mrgloom** [comment] 2018-11-27 16:25
Seems get the same error on:
```
tensorflow.__version__
'1.5.0
keras.__version__
'2.1.6'
```

Steps to reproduce:

1. Create MobileNet

```
from keras.applications.mobilenet import MobileNet

model = MobileNet(input_shape=(128, 128, 3),
                      alpha=1.0,
                      depth_multiplier=1,
                      include_top=False,
                      weights='imagenet'
                      )

model.summary()

model.save('keras_model.h5')
```

2. Convert to tensorflow .pb
```
from keras import backend as K
from keras.utils.generic_utils import CustomObjectScope
import keras
from tensorflow.python.framework import graph_util
from tensorflow.python.framework import graph_io

K.set_learning_phase(0) # Leave only needed for inference in graph

with CustomObjectScope({'relu6': keras.applications.mobilenet.relu6,
                        'DepthwiseConv2D': keras.applications.mobilenet.DepthwiseConv2D}):
    model = keras.models.load_model('keras_model.h5')
    sess = K.get_session()

    output_node_names = [node.op.name for node in model.outputs]
    print('output_node_names', output_node_names) # output_node_names ['conv_pw_13_relu/Minimum']
    constant_graph = graph_util.convert_variables_to_constants(
        sess,
        sess.graph.as_graph_def(),
        output_node_names)

    graph_io.write_graph(constant_graph, '.', 'tf_model.pb', as_text=False) 
```

Tried to convert using `toco` tool:

Simple version:

```
toco --input_file="tf_model.pb" --output_file="model.tflite" --input_format="TENSORFLOW_GRAPHDEF" --output_format="TFLITE"

2018-11-27 19:12:07.800286: F tensorflow/contrib/lite/toco/tooling_util.cc:1103] Check failed: model->flags.output_arrays_size() > 0 (0 vs. 0)This model does not define output arrays, so a --output_arrays flag must be given on the command-line.
Abort trap: 6
```

With specifying `--output_arrays`:

```
toco --input_file="tf_model.pb" --output_file="model.tflite" --input_format="TENSORFLOW_GRAPHDEF" --output_format="TFLITE" --output_arrays='conv_pw_13_relu/Minimum'

2018-11-27 19:13:13.433366: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 446 operators, 650 arrays (0 quantized)
2018-11-27 19:13:13.457227: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 68 operators, 164 arrays (0 quantized)
2018-11-27 19:13:13.458602: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 68 operators, 164 arrays (0 quantized)
2018-11-27 19:13:13.459898: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:313] Total transient array allocated size: 0 bytes, theoretical optimal value: 0 bytes.
2018-11-27 19:13:13.460489: F tensorflow/contrib/lite/toco/tflite/export.cc:303] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: TensorFlowMinimum.
Abort trap: 6
```

Using `--allow_custom_ops`:

```
toco --input_file="tf_model.pb" --output_file="model.tflite" --input_format="TENSORFLOW_GRAPHDEF" --output_format="TFLITE" --output_arrays='conv_pw_13_relu/Minimum' --allow_custom_ops
2018-11-27 19:23:43.537074: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 446 operators, 650 arrays (0 quantized)
2018-11-27 19:23:43.561828: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 68 operators, 164 arrays (0 quantized)
2018-11-27 19:23:43.563117: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 68 operators, 164 arrays (0 quantized)
2018-11-27 19:23:43.564334: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:313] Total transient array allocated size: 0 bytes, theoretical optimal value: 0 bytes.
```

No errors, but not sure if everything is ok.

**Comment by andrehentz** [comment] 2018-11-27 16:41
Please try with a more recent version of tensorflow. Support for tf.min was added around mid-april.

**Comment by mrgloom** [comment] 2018-11-27 17:06
With 
```
tensorflow.__version__
'1.12.0'
keras.__version__
'2.1.6
```
I have tried 

```
toco --keras_model_file='keras_model.h5' --output_file='model.tflite'

Traceback (most recent call last):
  File "/Users/myuser/sandbox/tflite/bin/toco", line 11, in <module>
    sys.exit(main())
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
    process_layer(layer_data)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1606, in from_config
    return cls(**config)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 330, in __init__
    self.activation = activations.get(activation)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 206, in get
    return deserialize(identifier)
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 197, in deserialize
    printable_module_name='activation function')
  File "/Users/myuser/sandbox/tflite/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 193, in deserialize_keras_object
    function_name)
ValueError: Unknown activation function:relu6
```

And this command seems was runned without errors:
`toco --graph_def_file="tf_model.pb" --output_file="model.tflite" --output_format="TFLITE" --input_arrays='input_1_1' --output_arrays='conv_pw_13_relu_1/Minimum'`
