### ISSUE TITLE
model/rnn/translate reads the data model after creating network

### ISSUE THREAD

**Issue by h4ck3rm1k3** [tensorflow/tensorflow#5782] opened 2016-11-22 12:31 UTC
The translate module reads the data files after creating the network, this leads to long waits if there are problems in the data files. 

I have moved the read file section forward in my branch 
https://github.com/h4ck3rm1k3/tensorflow/commit/62d46a3b8687e0b7d5e37320b545ffe63a9361a1#diff-4dada032ac312625f74be392b009cc00R152

**Comment by lukaszkaiser** [comment] 2016-11-22 20:55
This is a feature request, not a bug. Since the translation example will be going away (in favour of a better model in TF-models later), I'm closing this.

**Closed by lukaszkaiser** 2016-11-22 20:55 UTC

**Comment by h4ck3rm1k3** [comment] 2016-11-22 23:15
alles klar....
