### ISSUE TITLE
Timeline's reported memory usage not properly displayed in Chrome

### ISSUE THREAD

**Issue by stepelu** [tensorflow/tensorflow#3268] opened 2016-07-11 10:27 UTC
I am attempting to debug out-of-memory issues using the recently introduced support for timeline:

```
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()
sess.run(..., options=run_options, run_metadata=run_metadata)
train_writer.add_run_metadata(run_metadata, 'step' + repr(i))
tl = timeline.Timeline(run_metadata.step_stats)
trace_file = tf.gfile.Open(name='timeline', mode='w')
trace_file.write(tl.generate_chrome_trace_format(show_memory=True))
```

The file is generated, but when opened via `chrome://tracing/` the memory usage events are not displayed at all, only the names. Moreover, opening such memory section results in the CPU-usage events disappearing as well:

<img width="665" alt="screen shot 2016-07-11 at 7 23 59 pm" src="https://cloud.githubusercontent.com/assets/6617696/16727681/2fcce290-479d-11e6-8ce4-8563e16f3212.png">

<img width="699" alt="screen shot 2016-07-11 at 7 24 09 pm" src="https://cloud.githubusercontent.com/assets/6617696/16727688/35cf0cf4-479d-11e6-9fc2-1bdc8706e227.png">

Possibly too many datapoints results in failure to display them?

**Comment by jmchen-g** [comment] 2016-07-12 06:32
@prb12 Could you take a look at this please?

**Comment by stepelu** [comment] 2016-07-12 06:37
Update: zooming out a lot in the browser make the dots appear, but that's more of a workaround than a real solution.

By the way, are the colours related in any way to the size of memory allocations?

**Comment by prb12** [comment] 2016-07-12 15:42
> Update: zooming out a lot in the browser make the dots appear, but that's more of a workaround than a real solution.

@stepelu I'm not sure exactly what is going on in this case to produce the UI issues you are seeing - from your description of things changing with zoom levels, it could very easily be an issue with the chrome viewer (which is nothing to do with TensorFlow).  To reproduce it would be helpful if you could provide a copy of the `StepStats` protobuf (preferably) or at least the JSON of the chrome trace.

> By the way, are the colors related in any way to the size of memory allocations?

The colors of everything in the GUI are chosen by the chrome trace viewer based on the 'name' of the event (usually the Op name).  They are not under the control of TensorFlow unfortunately  :-(

**Note:** There are a number of reasons that the show_memory option is disabled by default:

- The most important is that there isn't really enough information in the `StepStats` to correctly determine the order of allocation/frees (which is non-deterministic in reality) and so the histogram is at best an approximation of the truth.  The `Timeline` code is effectively replaying a trace of allocs and frees where the timestamps are taken with a very coarse clock, and simulating the memory usage.  Fixing this would require adding much more expensive instrumentation which would hurt the common case performance.

- The second problem is that the ops which are executed and recorded in the `StepStats` are not necessarily those in the original `GraphDef` due to substantial graph rewriting (e.g. adding Send/Recv nodes when partitioning the graph across devices) and various optimization passes (constant folding, CSE, etc).  It is impossible for the `Timeline` code to correctly determine the dataflow dependencies of these ops - and it currently has a very fragile heuristic based on parsing the string 'description' field of the op to guess its inputs.  It would be possible to do a much better job if somebody implemented a way to retrieve the post-optimization graphs in the `RunMetadata`.  

- Another, often more important issue, is that a lot of memory consumption is by **stateful** ops such as Queues and Variables which aren't included in this analysis.  e.g. I have seen multiple cases where poorly configured Queues have been consuming many gigabytes of memory.  

So - in summary, I wouldn't recommend relying too heavily on the Timeline memory analysis at the moment.

**Comment by michaelisard** [comment] 2016-07-25 22:47
Closing for now, but if you would like to supply a timeline for debugging, please reopen.

**Closed by michaelisard** 2016-07-25 22:47 UTC
Labels: triaged

**Comment by MrWanter** [comment] 2018-06-14 02:55
@prb12 Hi! I'm wondering if the timeline memory analysis is currently able to capture more accurate memory statistics in the latest TF version?
