### ISSUE TITLE
WARNING : [ W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found] Windows 10, TF2.10.1, CUDA 11.2, cuDNN 8.1.

### ISSUE THREAD

**Issue by kamil5b** [tensorflow/tensorflow#59229] opened 2023-01-11 17:40 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.10.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 22H2

### CUDA/cuDNN version

CUDA=11.2; cuDNN = 8.1

### GPU model and memory

NVIDIA GTX 1070 8GB VRAM

### Current Behaviour?

```shell
I did everything like its instructed in https://www.tensorflow.org/install/pip but the warning still come up. I need GPU Support for my project. But when I just import tensorflow inside my python, the warning come up

I am sure 100% in my conda and my environment Path, there is cudart64_110.dll 
I tried to reinstall my Nvidia Drivers, CUDA, and my cuDNN but it still doesnt work.
Is there any solution for this?
```

### Standalone code to reproduce the issue

```shell
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
python3 -m pip install "tensorflow<2.11"
python3 -c "import tensorflow as tf"
```

### Relevant log output

```shell
W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
```
</details>

**Comment by gaikwadrahul8** [comment] 2023-01-12 18:41
Hi, @kamil5b 

Apologize for the delay and I found [similar issue ](https://github.com/tensorflow/tensorflow/issues/57103) and user was able to resolve issue and please make sure that to install `tensorflow==2.10` on windows 10 you should follow this [instructions](https://www.tensorflow.org/install/pip#windows-wsl2) with system requirements and it seems like in your case you haven't added system paths in environment variable after extracting your `cudnn` folder you'll find `cuda` folder copy paste that complete folder in your `C Drive` after that you'll find 03 folder with names `bin`,`include`,`lib` add each one of those path in environment variable so `cudart64_110.dll` file should detect and after that everything should work fine, for your reference I found one [youtube video](https://www.youtube.com/watch?v=StH5YNrY0mE), you can follow initial steps for how to add path in environment variable after that please follow official documentation instructions as mentioned in the above link

Could you please try above workaround and let us know whether is it resolving your issue or not ? if issue still persists please let us know with error log to find out root cause for your issue ?

Thank you!

**Comment by kamil5b** [comment] 2023-01-12 19:01
I did everything including adding it to my path environment variable (user and system), placing cuDNN in my CUDA directory, uninstall ALL about Nvidia (including drivers and CUDA) and reinstall all of it to the latest and downgrading the CUDA to 11.2, rewrite path environment variable.
Eventually I did everything that I can do in Native Windows 10 but none of it resolve my issue. Tensorflow still not reading my GPU.
I cannot afford downgrading the Tensorflow lower than 2.10 because I need the causal_mask parameter to make my model easier.
I know that TF 2.10 is the last version for gpu support for Windows 10.

Oh yeah, I have Ryzen 6 3650X if its relevant to the case.

**Comment by SuryanarayanaY** [comment] 2023-01-13 05:45
@kamil5b ,
Could you please confirm the output of following codes:

`python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"`

`nvidia-smi`

**Comment by kamil5b** [comment] 2023-01-14 17:13
Sorry for the late response, this is the result + i did
`nvcc -V`
![image](https://user-images.githubusercontent.com/79760043/212485796-0284f9a5-0a02-4e7b-abfe-24882b041ae8.png)
additional : 
![image](https://user-images.githubusercontent.com/79760043/212485898-8ec64387-61b6-4f70-acc7-333041745b6a.png)
![image](https://user-images.githubusercontent.com/79760043/212485930-f5a025dc-5a7d-4475-b246-dd4444025002.png)
![image](https://user-images.githubusercontent.com/79760043/212485995-8db0bdbf-2a4a-4f24-a75e-0cdd593e0874.png)

**Comment by SuryanarayanaY** [comment] 2023-01-16 07:39
Hi @kamil5b ,
I see the CUDA driver(from `nvidia-smi` command) you are using as 12.0 which may not be compatible to CUDA 11.2 library.Could you please install CUDA driver compatible with CUDA 11.2 library and check whether the issue will resolve for you ?

Thankyou!

**Comment by SuryanarayanaY** [comment] 2023-01-17 09:26
@kamil5b ,

The CUDA Driver version (528.02) may not compatible with the CUDA library i.e CUDA-11.2 here. You may try to install Driver version compatible with CUDA 11.2 library from [here](https://www.nvidia.com/Download/index.aspx). For example Driver Version 470.161.03 may be suitable for CUDA 11.2-11.4. Please try this and let us know if it works.

**Closed** 2023-01-31 10:07 UTC
Labels: stat:awaiting response, type:build/install, type:support, stalled, subtype:windows, TF 2.10

**Comment by SuryanarayanaY** [comment] 2023-01-31 14:41
I have tested it on a windows PC with Tf2.10 v with CUDA driver 516.41 and CUDA 11.2 toolkit and the GPU is able to be detected.

![image](https://user-images.githubusercontent.com/116063290/215784610-a5f180e0-50e4-4d23-88ad-7d983a6589b5.png)

@kamil5b , Could you please confirm if this is still an issue for you?
