### ISSUE TITLE
tf.function doesn't see methods of class

### ISSUE THREAD

**Issue by Oktai15** [tensorflow/tensorflow#30800] opened 2019-07-17 11:50 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from binary
- TensorFlow version: 2.0beta
- Python version: 3.6
- CUDA/cuDNN version: 10.0 

**Describe the current behavior**

I am working with GAN. I have `Trainer` class which has the following methods:  `pass_one_step_gan`, `__pass_critic` and `__pass_generator`. It looks like around that:
```python
@tf.function
def pass_one_step_gan(self, inputs, target_imgs, it, stage, training):
        with tf.GradientTape() as g_tape, tf.GradientTape() as c_tape:
            new_imgs = self.model(inputs, training=training)

            if training:
                c_loss, c_loss_with_gp = self.__pass_critic(target_imgs, new_imgs)
                g_loss = self.__pass_generator(new_imgs, it)

```

I got the following error:
```
.../trainer.py:254 __pass_one_step_gan  *
    c_loss, c_loss_with_gp = self.__pass_critic(
    .../tensorflow/python/autograph/impl/api.py:329 converted_call
            f = getattr(owner, f)
    AttributeError: 'Trainer' object has no attribute '__pass_critic'
```

I tried to wrap `__pass_critic` in `tf.function`, but it didn't help.

**Describe the expected behavior**

It should work, but doesn't.

**Code to reproduce the issue**

See above.

**Other info / logs**

I don't know why but it seems that python doesn't see my method and, thus, tf.function can't track it.

**Comment by ravikyram** [comment] 2019-07-18 10:06
@Oktai15 
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-07-25 05:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-25 05:19 UTC
Labels: 2.0.0-beta0, comp:autograph, stat:awaiting response, type:support
