### ISSUE TITLE
_dataset_ops.so not found

### ISSUE THREAD

**Issue by elksie5000** [tensorflow/tensorflow#20320] opened 2018-06-26 20:52 UTC
Hi, 

Trying to run this code https://towardsdatascience.com/implementing-a-generative-adversarial-network-gan-dcgan-to-draw-human-faces-8291616904a

However, I keep running into an error:

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-8-c79e12159a4e> in <module>()
----> 1 g = generator(noise, keep_prob, is_training)
      2 print(g)
      3 d_real = discriminator(X_in)
      4 d_fake = discriminator(g, reuse=True)
      5 

<ipython-input-7-61000d187a2b> in generator(z, keep_prob, is_training)
     42         x = tf.layers.dense(x, units=d1 * d1 * d2, activation=activation)
     43         x = tf.layers.dropout(x, keep_prob)
---> 44         x = tf.contrib.layers.batch_norm(x, is_training=is_training, decay=momentum)
     45 
     46         x = tf.reshape(x, shape=[-1, d1, d1, d2])

D:\anaconda\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

D:\anaconda\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

D:\anaconda\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

D:\anaconda\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

D:\anaconda\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\anaconda\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

D:\anaconda\lib\importlib\_bootstrap.py in _load_unlocked(spec)

D:\anaconda\lib\importlib\_bootstrap_external.py in exec_module(self, module)

D:\anaconda\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

D:\anaconda\lib\site-packages\tensorflow\contrib\__init__.py in <module>()
     32 from tensorflow.contrib import crf
     33 from tensorflow.contrib import cudnn_rnn
---> 34 from tensorflow.contrib import data
     35 from tensorflow.contrib import deprecated
     36 from tensorflow.contrib import distribute

D:\anaconda\lib\site-packages\tensorflow\contrib\data\__init__.py in <module>()
     65 from tensorflow.contrib.data.python.ops.counter import Counter
     66 from tensorflow.contrib.data.python.ops.enumerate_ops import enumerate_dataset
---> 67 from tensorflow.contrib.data.python.ops.error_ops import ignore_errors
     68 from tensorflow.contrib.data.python.ops.get_single_element import get_single_element
     69 from tensorflow.contrib.data.python.ops.grouping import bucket_by_sequence_length

D:\anaconda\lib\site-packages\tensorflow\contrib\data\python\ops\error_ops.py in <module>()
     18 from __future__ import print_function
     19 
---> 20 from tensorflow.contrib.data.python.ops import contrib_op_loader  # pylint: disable=unused-import
     21 from tensorflow.contrib.data.python.ops import gen_dataset_ops
     22 from tensorflow.python.data.ops import dataset_ops

D:\anaconda\lib\site-packages\tensorflow\contrib\data\python\ops\contrib_op_loader.py in <module>()
     22 
     23 _dataset_ops = loader.load_op_library(
---> 24     resource_loader.get_path_to_datafile("../../_dataset_ops.so"))

D:\anaconda\lib\site-packages\tensorflow\contrib\util\loader.py in load_op_library(path)
     54       return None
     55   path = resource_loader.get_path_to_datafile(path)
---> 56   ret = load_library.load_op_library(path)
     57   assert ret, 'Could not load %s' % path
     58   return ret

D:\anaconda\lib\site-packages\tensorflow\python\framework\load_library.py in load_op_library(library_filename)
     54     RuntimeError: when unable to load the library or get the python wrappers.
     55   """
---> 56   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     57 
     58   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: D:\anaconda\lib\site-packages\tensorflow\contrib\data\python\ops\..\..\_dataset_ops.so not found

I'm running Python 3.6 and have same problem on Windows 10 and Mac Osx. Tensorflow is latest available through Anaconda. Cuda 9.0. Tensorflow 1.8.0

This error also affects my efforts to look at MNIST tutorials for commands such as:

from tensorflow.examples.tutorials.mnist import input_data

**Comment by tensorflowbutler** [comment] 2018-06-27 06:42
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by elksie5000** [comment] 2018-06-27 07:02
Have I written custom code? Yes - https://towardsdatascience.com/implementing-a-generative-adversarial-network-gan-dcgan-to-draw-human-faces-8291616904a
OS Platform and Distribution - Mac OSX and Windows 10
TensorFlow installed from - Anaconda
TensorFlow version - 1.8.0
Bazel version - N/A
CUDA/cuDNN version - 9.0 (or NA for Mac OSX)
GPU model and memory - NVIDIA GeForce GTX 650 Ti Boost - 2 GB video. 16 GB RAM (Mac OSX no GPU, 16GB RAM)
Exact command to reproduce

**Comment by CanPhi** [comment] 2018-06-27 09:39
+1 I get the same error when trying to load tensorboard. 

OS Platform and Distribution - Windows 10
TensorFlow installed from - pip
TensorFlow version - 1.8.0
Bazel version - N/A
CUDA/cuDNN version - 9.0 
GPU model and memory -NVIDIA)
Exact command to reproduce - callbacks.append(TensorBoard(log_dir=save_path_logs, write_graph=True, write_images=False))

**Comment by CanPhi** [comment] 2018-06-27 10:10
This solved it for me: 

https://stackoverflow.com/questions/50609845/tensorflow-1-8-0-with-python-3-6-4-in-anaconda-show-error-dataset-ops-so-not-fo/50942347

"follow this path and locate _dataset_ops.so

D:\programfiles\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\contrib\data

then move _dataset_ops.so file out of that folder to another location."

**Comment by tensorflowbutler** [comment] 2018-07-12 19:10
Nagging Assignee @aselle: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-07-23 16:16
@gunan, it seems contrib ops are not loading in  Windows. Could you PTAL?

**Comment by mrry** [comment] 2018-07-25 17:38
@gunan The file `_dataset_ops.so` should not be generated in the Windows/CMake build: those kernels are statically linked into the main Python extension DLL. The [StackOverflow answer](https://stackoverflow.com/questions/50609845/tensorflow-1-8-0-with-python-3-6-4-in-anaconda-show-error-dataset-ops-so-not-fo/50942347) suggests that the file *is* being generated, and moving it away should fix things.

Perhaps one of the PIP packages is broken (e.g. for TF 1.8, since that seems to be a common factor)?

**Comment by gunan** [comment] 2018-07-30 04:09
@case540 @av8ramit 
Is it possible that one of our recent changes are causing windows pip packages to include .so files?

**Comment by tensorflowbutler** [comment] 2018-08-15 02:59
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by deepanshib** [comment] 2018-08-18 06:43
follow the path and locate _dataset_ops.so

\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\contrib\data

then move _dataset_ops.so file out of that folder to another location.

I got the same issue and doing this solved the issue.

**Comment by tensorflowbutler** [comment] 2018-09-01 18:44
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-16 12:31
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-16 21:49
@case540 @av8ramit ping!

**Comment by tensorflowbutler** [comment] 2018-10-01 18:55
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-16 12:48
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yifeif** [comment] 2018-10-19 22:28
Is this still an issue now that we moved to using bazel for windows?

**Comment by av8ramit** [comment] 2018-10-19 22:38
I'm not sure with regards to the .so files. I haven't made any modifications.

**Comment by aselle** [comment] 2018-10-19 22:50
ClosingAutomatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2018-10-19 22:50 UTC
Labels: type:build/install

**Comment by AleLustosa** [comment] 2018-11-21 21:36
>           follow the path and locate _dataset_ops.so
> \Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\contrib\data
> then move _dataset_ops.so file out of that folder to another location.
> I got the same issue and doing this solved the issue.

Tks!!!! Work fine!

**Comment by mandal4** [comment] 2019-01-22 11:39
> follow the path and locate _dataset_ops.so
> 
> \Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\contrib\data
> 
> then move _dataset_ops.so file out of that folder to another location.
> 
> I got the same issue and doing this solved the issue.

Thx!! it works for me.. but is there any one knows what caused this error?!
i got no this error just 3 hours ago. I have no idea about it.

**Comment by soumen29dec** [comment] 2019-03-23 05:55
I am getting peculiar issue while running detector_utils.py. while hand_label_map.pbtxt is very much there in the specified folder, i am still getting following error - please help me how to resolve:
NotFoundError                             Traceback (most recent call last)
<ipython-input-20-a486b1bd49eb> in <module>
----> 1 label_map = hand_label_map_util.load_labelmap(PATH_TO_LABELS)

C:\Anaconda\envs\tf_gpu\lib\site-packages\utils\hand_label_map_util.py in load_labelmap(path)
    115     """
    116     with tf.gfile.GFile(path, 'r') as fid:
--> 117         label_map_string = fid.read()
    118         label_map = string_int_label_map_pb2.StringIntLabelMap()
    119         try:

C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    123       string if in string (regular) mode.
    124     """
--> 125     self._preread_check()
    126     with errors.raise_exception_on_not_ok_status() as status:
    127       if n == -1:

C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     83       with errors.raise_exception_on_not_ok_status() as status:
     84         self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 85             compat.as_bytes(self.__name), 1024 * 512, status)
     86 
     87   def _prewrite_check(self):

C:\Anaconda\envs\tf_gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

NotFoundError: NewRandomAccessFile failed to Create/Open: C:/Anaconda/envs/tf_gpu/Lib/site-packages/tensorflow/models/research/object_detection/utils/hand_detection_inference_graph/hand_label_map.pbtxt : The system cannot find the file specified.
; No such file or directory

**Comment by zhangjh915** [comment] 2019-04-10 19:43
> This solved it for me:
> 
> https://stackoverflow.com/questions/50609845/tensorflow-1-8-0-with-python-3-6-4-in-anaconda-show-error-dataset-ops-so-not-fo/50942347
> 
> "follow this path and locate _dataset_ops.so
> 
> D:\programfiles\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\contrib\data
> 
> then move _dataset_ops.so file out of that folder to another location."

I am having the same error using TensorFlow on win10 and installed from Anaconda with tensorflow version of 1.10. I tried to follow this method but there is no "_dataset_ops.so" file in that directory. There are only three folders of "_pychache", "kernels", "python" and a file "__init__.py". Did I miss anything?
