### ISSUE TITLE
translate.py in the seq2seq model is missing in sitepackages for python3.5 cpu only release

### ISSUE THREAD

**Issue by patrickbreen** [tensorflow/tensorflow#4574] opened 2016-09-25 19:25 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
searched github issues for "translate.py" no hits

### Environment info
Operating System:
Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
NA, CPU only

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
NA

### What other attempted solutions have you tried?
NA

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by concretevitamin** [comment] 2016-09-27 21:57
Can you let us know which exact file this refers to?

**Comment by patrickbreen** [comment] 2016-09-28 14:11
tensorflow/tensorflow/models/rnn/translate/translate.py

**Comment by lukaszkaiser** [comment] 2016-09-28 21:59
Please assign to someone with more build expertise, that's not me.

**Comment by concretevitamin** [comment] 2016-09-28 22:03
@lukaszkaiser - oh right, I blindly assigned based on the prefix `tf/models/rnn` :)  Re-assigning to @gunan.

**Comment by gunan** [comment] 2016-09-28 22:27
It is possible we omit models on purpose.
@martinwicke Could you confirm?

**Comment by patrickbreen** [comment] 2016-09-29 13:36
Yes it would seem like you omitted it from the pip release which would perhaps make sense because it's supposed to be run as a "main" ie its not part of a library. And I mean its no real problem for me to just get the file from "master" but the problem is that the translate.py file that I get from master may not be compatible with the release version that I installed via pip.

Do you see what I mean? So I think that files like tensorflow/tensorflow/models/rnn/translate/translate.py should be accessible in the pip-installed version of tensorflow to make sure your pip installation of tensorflow is on the same version as the provided models.

**Comment by martinwicke** [comment] 2016-09-29 13:44
You can always get the files corresponding to the binary releases by
checking out the corresponding branch in the repo. Eg for the 0.10 release,
check out the r0.10 branch.

**Comment by gunan** [comment] 2016-09-29 16:51
So marking this as working as intended, and using the same files from the release branch should give you compatible files.
Closing this issue.

**Closed by gunan** 2016-09-29 16:51 UTC
