### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by Exception4U** [tensorflow/tensorflow#27261] opened 2019-03-28 21:03 UTC
```
2019-03-28 20:17:05.067925: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cast_op.cc:109 : Resource exhausted: OOM when allocating tensor with shape[612,612,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 
by allocator cpu
Traceback (most recent call last):
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[427,640,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[{{node rgb_to_grayscale/convert_image/Cast}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node superpoint/IteratorGetNext}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node superpoint/vgg/conv1_1/bn/beta/read}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment.py", line 148, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 86, in _cli_train
    train(config, config['train_iter'], output_dir)
  File "experiment.py", line 27, in train
    keep_checkpoints=config.get('keep_checkpoints', 1))
  File "/home/models/codes/SuperPoint/superpoint/models/base_model.py", line 313, in train
    options=options, run_metadata=run_metadata)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/models/TF-2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[427,640,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[{{node rgb_to_grayscale/convert_image/Cast}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node superpoint/IteratorGetNext (defined at /home/models/codes/SuperPoint/superpoint/models/base_model.py:260) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

TF version: 1.13.1
cudnn: 7
cuda: 10.0

Question: I do not understand what is meaning of it. Is GPU memory exhausted. Which is api by which I can change policy of cacheing etc.

**Comment by AndreiMaga** [comment] 2019-03-29 08:11
Hello, some points for your issue:
First of all, please use the issue templates
Second, you're using a CPU to train not a GPU as this line states ```/job:localhost/replica:0/task:0/device:CPU:0```

If you want to use the GPU install tensorflow-gpu by running 
`pip uninstall tensorflow & pip install tensorflow-gpu`

The problem seems to be that your ram is getting filled, you can reduce the batch size so the data will fit into your RAM.

**Comment by jvishnuvardhan** [comment] 2019-04-05 22:59
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by tensorflowbutler** [comment] 2019-04-20 12:47
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Exception4U** [comment] 2019-04-20 14:19
let me point out the detail code ....
the policy I adapted for memory allocation during training was using CPU
memory for augmented data to appear in ram and batches come in GPU memory
sequentially.
https://github.com/Exception4U/SuperPoint/blob/491189c96c9561c1829eeeb45890a70436ae2d49/superpoint/datasets/base_dataset.py#L109
it seems to me that even if the ram is getting filled Virtual memory could
be used. which is not observed.

--
Tushar

**Comment by jvishnuvardhan** [comment] 2019-05-01 21:45
@Exception4U 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-08 21:03
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-08 21:03 UTC
Labels: 2.0, stat:awaiting response, type:support
