### ISSUE TITLE
Tensorflow AOT compilation error: No registered 'DecodeJpeg' OpKernel for XLA_CPU_JIT 

### ISSUE THREAD

**Issue by Kwander** [tensorflow/tensorflow#25548] opened 2019-02-06 11:57 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0 (tensorflow-gpu, tensorflow-base)
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA/cuDNN version: 7.1.2
- GPU model and memory: GeForce GTX 1080, 8GB

**Describe the current behavior**
I am trying to compile a pretrained InceptionV4 model from TF models repository. The last layer is modified to produce our custom set of classes (we're doing transfer learning). I successfully produced both graph.pb and graph.pb.txt files. When I tried to compile the graph, I received an error (see logs below).

* I have managed to successfully compile and run Keras ResNet50 and MobileNetV2 models before.
* I disabled XLA & CUDA when compiling TF from source.

**Other info / logs**
```
INVALID ARGUMENTS: Detected unsupported operations when trying to compile graph tfcompile on XLA_CPU_JIT: DecodeJpeg (No registered 'DecodeJpeg' OpKernel for XLA_CPU_JIT devices compatible with node {{node DecodeJpeg}}
	.  Registered:  <no registered kernels>
){{node DecodeJpeg}}

```

**Comment by jvishnuvardhan** [comment] 2019-02-25 21:47
@Kwander I have couple of questions. 
1) You mentioned that you are able to successfully compiled for two models before. Did you disable XLA and CUDA while you compiled them? 
2) What is the reason behind the disabling XLA & CUDA? Want to understand context. Thanks!

**Comment by Kwander** [comment] 2019-02-28 16:05
@jvishnuvardhan Hey!

1. Yes, I have.
2. I thought this might help, as I later discovered that GPU compiling was not supported by TF AOT then.

**Comment by jvishnuvardhan** [comment] 2019-02-28 18:12
@Kwander Iam not sure what will be the root cause of the issue. Could you share a code to reproduce the issue? I just want to make sure that there is nothing wrong from the coding side. Thanks!

**Comment by jlebar** [comment] 2019-02-28 18:17
I believe this is working as intended.

If you want to use tfcompile to do AOT compilation on CPU, all of the ops in the compiled graph must be supported on XLA:CPU.

XLA:CPU does not support JPEG decoding.

**Comment by jlebar** [comment] 2019-02-28 18:18
> I disabled XLA & CUDA when compiling TF from source.

Note that tfcompile AOT *requires XLA*.  So if you disable XLA in the build and try to use tfcompile...I'm not sure what's supposed to happen.  :)

**Comment by jlebar** [comment] 2019-03-07 01:06
Eagerly closing this, but please reopen if you have other questions / need more assistance.

**Closed by jlebar** 2019-03-07 01:06 UTC
Labels: comp:xla, stat:awaiting tensorflower, type:bug/performance
