### ISSUE TITLE
Tensorflow (cpu) vs concurrent.futures: Exception 

### ISSUE THREAD

**Issue by ikamensh** [tensorflow/tensorflow#28001] opened 2019-04-20 07:21 UTC
I am using Tensorflow v2.0.0-alpha on MacBook (CPU only). Python version: 3.7.2.

I am testing a rl agent on multiple environments. For this I am using concurrent.futures.ProcessPoolExecutor.map function. Roughly around the time when first processes are done, exception occurs:

```
 objc[44717]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[44717]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Traceback (most recent call last):
  File "/Users/ikkamens/PycharmProjects/ilya_agents/ilya_agents/launch/launch.py", line 38, in <module>
    for env, result in zip(envs, metrics):
  File "/Users/ikkamens/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/ikkamens/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/Users/ikkamens/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/ikkamens/.pyenv/versions/3.7.2/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by ikamensh** [comment] 2019-04-20 09:06
Using futures.ProcessPoolExecutor.submit() and futures.as_completed() results in the same crash. Code I have used:
```
    from concurrent import futures

    executor = futures.ProcessPoolExecutor()
    todos = {}
    for env in envs:
        todos[executor.submit(maping, env)] = env

    scores = {}
    for future in futures.as_completed(todos):
        scores[ str(todos[future]) ] = future.result()
```

where function `maping` involves creating a tf-based agent, training it and testing on a gym environment.

**Comment by ymodak** [comment] 2019-04-23 20:01
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ikamensh** [comment] 2019-04-25 19:55
I have not saved the version of the project and the problem does not reoccur anymore.

**Comment by ymodak** [comment] 2019-04-27 00:02
Okay. Closing this issue since its resolved. Feel free to reopen if further problems persist. Thanks!

**Closed by ymodak** 2019-04-27 00:02 UTC
Labels: 2.0.0-alpha0, comp:ops, type:support
