### ISSUE TITLE
protobuf error when saving model

### ISSUE THREAD

**Issue by yanyanglu** [tensorflow/tensorflow#36885] opened 2020-02-19 09:37 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04.3 
- TensorFlow installed from: pip
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de
- Python version: 3.7.0 from anaconda
- CUDA/cuDNN version: 10.1.243
- GPU model and memory: GTX 2080 Ti, 11091 MB

**Describe the current behavior**

when save the model by
```
saver = tf.compat.v1.train.Saver(tf.compat.v1.global_variables(), max_to_keep=3)
path = saver.save(sess, checkpoint_prefix, global_step=current_step)
                            print("Saved model checkpoint to {}".format(path))
```
error occurs:

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'tensorflow.TensorShapeProto.Dim.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
Traceback (most recent call last):
  File "cnn.py", line 374, in <module>
    train(args, x_train, y_train, vocab_size, x_dev, y_dev)
  File "cnn.py", line 279, in train
    path = saver.save(sess, checkpoint_prefix, global_step=current_step)
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1203, in save
    save_debug_info=save_debug_info)
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1246, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3134, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3051, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by yanyanglu** [comment] 2020-02-19 13:08
my protobuf version: protobuf=3.11.3=pypi_0

**Comment by yanyanglu** [comment] 2020-02-19 13:35
when I call ` print(tf.compat.v1.get_default_graph().as_graph_def())`
this error also appears:
```
File "cnn.py", line 267, in train
    print(tf.compat.v1.get_default_graph().as_graph_def())
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3135, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "xxx/anaconda3/envs/li/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3052, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by gadagashwini** [comment] 2020-02-20 08:22
@yanyanglu, Can you provide the complete code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2020-02-20 08:26
@yanyanglu, I tried it on colab with Tf 2.1 and with Protobuf version 3.10.0.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/51980b41e0bdc4346b0fde1be7a8646f/untitled397.ipynb). Can you try with Protobuf 3.10.0. Let us know how it works. Thanks!

**Comment by gadagashwini** [comment] 2020-03-06 08:40
@yanyanglu, Is this still an issue?

**Comment by gadagashwini** [comment] 2020-03-13 09:40
Closing this issue, since its resolved.
 Please feel free to open if still issue persists. Thanks

**Closed by gadagashwini** 2020-03-13 09:40 UTC
Labels: TF 2.1, stat:awaiting response, type:bug

**Comment by X-ray-L** [comment] 2021-08-06 10:15
i meet this  error too 
tensorlfow = 2.2 
protobuf=3.15.6
