### ISSUE TITLE
Marginal Probablities in CRF

### ISSUE THREAD

**Issue by FallakAsad** [tensorflow/tensorflow#38359] opened 2020-04-08 14:39 UTC
After training a CRF model, I can get the best tag sequence y and its unormalized score for each test input sequence x through tf.contrib.crf.viterbi_decode() or tf.contrib.crf.crf_decode() but what changes might require in CRF implementation to get the marginal probabilities?

Tensorflow version: 1.15.0

**Comment by amahendrakar** [comment] 2020-04-09 09:57
@FallakAsad,
If this is a bug, could you please provide the complete code to reproduce the issue reported here.

If the issue reported here is not a bug or a feature request, the question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) as there is a larger community that reads questions there. Thanks!

**Comment by amahendrakar** [comment] 2020-04-16 17:34
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-23 19:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-23 19:00 UTC
Labels: stalled, stat:awaiting response, type:others

**Comment by sakusss** [comment] 2020-06-11 07:58
I also want to know how to calculate the margin probability in CRF

**Comment by agarwalishan** [comment] 2020-08-10 06:53
I also want the same.

**Comment by amahendrakar** [comment] 2020-08-11 14:40
@sakusss, @agarwalishan,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
