### ISSUE TITLE
request for more general einsum

### ISSUE THREAD

**Issue by godefv** [tensorflow/tensorflow#22649] opened 2018-10-01 14:17 UTC
### Describe the problem
Tensors have sometimes a lot of dimensions and explicitly writing them helps a lot for writing concise and readable code without bugs. For this, notations like in tf.einsum is invaluable. Unfortunately, the current implementation of tf.einsum is only a subset of what could be done with it : 
* As documented, "Subscripts that are summed across multiple inputs (e.g., ij,ij,jk->ik)." are not supported.
* Sums are not supported (eg. ij+ik->ijk, or even both products and sums ij*jk+i*k->ik)
* Expanding dimensions could also be useful (eg. ij,jk->ikl).

**Comment by tensorflowbutler** [comment] 2018-10-02 01:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-10-17 13:12
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment] 2018-10-31 20:17
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by harshini-gadige** 2018-10-31 20:17 UTC
Labels: stat:awaiting response, type:feature
