### ISSUE TITLE
Index error in decoding

### ISSUE THREAD

**Issue by Devadath** [tensorflow/tensorflow#3390] opened 2016-07-19 13:35 UTC
When I tried  --decode  and gave a sentence, I got this error
Traceback (most recent call last):
  File "translate.py", line 279, in <module>
    tf.app.run()
  File "/home/devadath/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 274, in main
    decode()
  File "translate.py", line 244, in decode
    print(" ".join([tf.compat.as_str(rev_hi_vocab[output]) for output in outputs]))
  File "translate.py", line 244, in <listcomp>
    print(" ".join([tf.compat.as_str(rev_hi_vocab[output]) for output in outputs]))
IndexError: list index out of range

Any help is appreciated

**Comment by concretevitamin** [comment] 2016-07-20 06:55
We will need more info.  See #3366 as an example.

**Comment by aselle** [comment] 2016-07-28 16:13
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-28 16:13 UTC
Labels: awaiting response

**Comment by LiuYaKu** [comment] 2018-01-30 16:36
Check that your rev_hi_vocab array is crossed.

**Comment by soonel333** [comment] 2018-04-17 03:36
I am also getting the exact same error. Waiting for help.
Traceback (most recent call last):
  File "translate.py", line 432, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 425, in main
    decode()
  File "translate.py", line 395, in decode
    print(" ".join([tf.compat.as_str(rev_en_vocab[output]) for output in outputs]))
IndexError: list index out of range

**Comment by avi-jain** [comment] 2019-09-10 20:09
Facing this issue too. 
I was following the [seq2seq tutorial](https://chromium.googlesource.com/external/github.com/tensorflow/tensorflow/+/r0.7/tensorflow/g3doc/tutorials/seq2seq/index.md) for a similar task. Since the tutorial is dated, and the code now nowhere to be found on the official repos, I used this [repo](https://github.com/petewarden/tensorflow_makefile/) as source. 
Tensorflow 0.12.1
Python 3.6.2 
OS - Amazon Linux

**Data and Configuration**
Trained a small model (2 layers, 256 units) using 50k rows as the training set, and another 25k for eval. Note that the task isn't translation, it is similar to Named Entity Recognition. Hence, the length of the target is very small (<5 tokens), and the length of the source isn't that large either. 
I set the target_vocab_size to 4000, and kept the source_vocab_size at its default of 40000.   
**Steps**
I trained the model for 5k steps, at the end of which the perplexity dropped to ~1. I expected the model to give good results, but when I decoded a sentence, the output tokens ids were beyond 4000, which is what resulted in this error. 
Here is the log

```
Input Token IDs :[159, 10, 5, 6, 3387, 2827, 1363, 315, 156, 70, 1194, 4, 13, 59, 15, 7, 71, 16, 4, 17, 20, 76, 118] 
Outputs [11229, 11229, 11229, 11229, 11229, 11229, 11229, 11229, 24412, 24412, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050, 5050]

Traceback (most recent call last):
  File "translate.py", line 287, in <module>
    tf.app.run()
  File "/home/ec2-user/anaconda3/envs/tfseq2seq/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 282, in main
    decode()
  File "translate.py", line 252, in decode
    print(" ".join([tf.compat.as_str(rev_fr_vocab[output]) for output in outputs]))
  File "translate.py", line 252, in <listcomp>
    print(" ".join([tf.compat.as_str(rev_fr_vocab[output]) for output in outputs]))
IndexError: list index out of range
```

Any pointers as to what could be the cause of this?
