### ISSUE TITLE
When we save the model with the api of model.save, received the error of 'TpyeError call() missing 1 required positional argument'. 

### ISSUE THREAD

**Issue by a1391651300** [tensorflow/tensorflow#50186] opened 2021-06-10 02:47 UTC
When we save the model with the api of model.save, received the error of 'TpyeError call() missing 1 required positional argument'. But when we try to send one tuple that includes one more parameters to the net instead of parameters directly,the net worked smoothly.Could someone tells me the reason?

**Comment by tilakrayal** [comment] 2021-06-10 05:32
@a1391651300 ,

Looks like this is duplicate of issue #50187.Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2021-06-14 21:03 UTC
Labels: stat:awaiting response, type:support
