### ISSUE TITLE
model.fit() raise FailedPreconditionError after applying "tf.distribute.MirroredStrategy()" 

### ISSUE THREAD

**Issue by BoysFight** [tensorflow/tensorflow#32769] opened 2019-09-24 09:10 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tf1.14/tf2.0.0rc1
- Python version:3.7.4
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: 9.0/7.6.0(tf1.14.0) , 10.0.130/7.6.0(tf2.0.0rc1) 
- GPU model and memory: 8G*2

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I create and complie the keras model under `with mirrored_strategy.scope():` ，then i got "FailedPreconditionError " when i excute model.fit();
if i move the code out from `with mirrored_strategy.scope():`, everything is ok.

**Describe the expected behavior**
when I create and complie the keras model under `with mirrored_strategy.scope():` , do not raise the exception and  multi GPU  can come into use.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
    # Create the base model from the pre-trained model MobileNet V2
    base_model = tf.keras.applications.InceptionV3(input_shape=IMG_SHAPE,
                                                   include_top=False,
                                                   weights='imagenet')
    base_model.trainable = False
    model = tf.keras.Sequential([
      base_model,
      keras.layers.GlobalAveragePooling2D(),
      keras.layers.Dense(len(label_names), activation='sigmoid')
    ])

    model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
                  loss='binary_crossentropy',
                  metrics=['categorical_accuracy'])

callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir=log_dir),
    tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                       save_weight_only=True)
]

epochs = 10
history = model.fit(train_dataset, 
                    epochs=epochs,
                    callbacks=callbacks)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

--------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-28-35cd9d3d6f8f> in <module>
      9                               validation_data=validation_ds,
     10                               validation_steps=validation_steps,
---> 11                               callbacks=callbacks)

/usr/local/miniconda3/envs/tf_2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

/usr/local/miniconda3/envs/tf_2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_distributed.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    683         validation_steps=validation_steps,
    684         validation_freq=validation_freq,
--> 685         steps_name='steps_per_epoch')
    686 
    687   def evaluate(self,

/usr/local/miniconda3/envs/tf_2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    297           else:
    298             actual_inputs = ins()
--> 299           batch_outs = f(actual_inputs)
    300         except errors.OutOfRangeError:
    301           if is_dataset:

/usr/local/miniconda3/envs/tf_2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3465 
   3466     fetched = self._callable_fn(*array_vals,
-> 3467                                 run_metadata=self.run_metadata)
   3468     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3469     output_structure = nest.pack_sequence_as(

/usr/local/miniconda3/envs/tf_2.0/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable conv2d_64/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/conv2d_64/kernel/N10tensorflow3VarE does not exist.
	 [[{{node inception_v3_1/conv2d_64/Conv2D/ReadVariableOp}}]]
	 [[batch_normalization_42/Const/_189]]
  (1) Failed precondition: Error while reading resource variable conv2d_64/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/conv2d_64/kernel/N10tensorflow3VarE does not exist.
	 [[{{node inception_v3_1/conv2d_64/Conv2D/ReadVariableOp}}]]
0 successful operations.
1 derived errors ignored.

**Comment by jvishnuvardhan** [comment] 2019-09-26 23:09
@BoysFight Can you provide a standalone code to reproduce the issue? Thanks!

**Comment by guptapriya** [comment] 2019-09-27 09:09
+1. Complete code to repro would be helpful in debugging this further.
The stack trace above is confusing because it seems like it is from TF 2.0, but also seems to be using TF session which is only a 1.x thing. Can you confirm if the stack trace if from 2.0 rc1?

**Comment by tensorflowbutler** [comment] 2019-10-12 12:25
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-10-14 16:31
@BoysFight Just a reminder for a standalone code to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-21 23:12
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-10-21 23:12 UTC
Labels: TF 2.0-rc0, comp:dist-strat, stat:awaiting response, type:bug
