### ISSUE TITLE
Retraining inception tutorial bazel error

### ISSUE THREAD

**Issue by saurabhvyas** [tensorflow/tensorflow#8726] opened 2017-03-26 14:06 UTC
Hi , I am following along this tutorial https://www.tensorflow.org/tutorials/image_retraining , I performed all the steps and they went fine even training but when I entered the command below for evaluating the model , I got an error after few minutes 

```
bazel build tensorflow/examples/label_image:label_image && \
bazel-bin/tensorflow/examples/label_image/label_image \
--graph=/tmp/output_graph.pb --labels=/tmp/output_labels.txt \
--output_layer=final_result \
--image=$HOME/flower_photos/daisy/21652746_cc379e0eea_m.jpg
```

```
ERROR: /home/saurabh/saurabh/tensorflow/tensorflow/core/kernels/BUILD:1468:1: C++ compilation of rule '//tensorflow/core/kernels:resource_variable_ops' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 106 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
No space left on device
No space left on device
No space left on device
No space left on device
No space left on device
Target //tensorflow/examples/label_image:label_image failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 201.779s, Critical Path: 150.97s
saurabh@saurabh-MS-7923:~/saurabh/tensorflow$ 

```

**Comment by mckinziebrandon** [comment] 2017-03-26 20:42
Have you tried passing the ```--local_resources``` option to bazel build? It seems that you've run out of space, and that option is useful if you're constrained by RAM for example. 

Description given in the output of "bazel help build":
```
 --local_resources (comma-separated available amount of RAM (in MB), CPU (in cores) and available I/O (1.0 being average workstation); default: see description)
```

Example usage (what I use):
```
--local_resources 4096,2.0,1.0
```

Just a guess to try before hearing back from the tensorflow folks.

**Comment by saurabhvyas** [comment] 2017-03-27 01:25
I'll give that a shot today , thanks

**Comment by BKJackson** [comment] 2017-04-02 03:12
I ran into a possibly similar memory problem with label_image.py.  It worked correctly on the first run, but every run after that crashed with memory error.  

Here is the error output:
W tensorflow/core/common_runtime/bfc_allocator.cc:274] ************************************************************************************xxxxxxxxxxxxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 1.5KiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:965] Internal: Dst tensor is not initialized.
E tensorflow/core/common_runtime/executor.cc:390] Executor failed to create kernel. Internal: Dst tensor is not initialized.
	 [[Node: mixed_3/conv/batchnorm/beta = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [384] values: -1.1053501 -0.46053475 -0.92515361...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _do_call
    return fn(*args)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1003, in _run_fn
    status, run_metadata)
  File "/Applications/anaconda/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: mixed_3/conv/batchnorm/beta = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [384] values: -1.1053501 -0.46053475 -0.92515361...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_files/label_image.py", line 22, in <module>
    predictions = sess.run(softmax_tensor, {'DecodeJpeg/contents:0': image_data})
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: mixed_3/conv/batchnorm/beta = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [384] values: -1.1053501 -0.46053475 -0.92515361...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'mixed_3/conv/batchnorm/beta', defined at:
  File "tf_files/label_image.py", line 16, in <module>
    _ = tf.import_graph_def(graph_def, name='')
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    op_def=op_def)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Applications/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Dst tensor is not initialized.
	 [[Node: mixed_3/conv/batchnorm/beta = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [384] values: -1.1053501 -0.46053475 -0.92515361...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by itsmeolivia** [comment] 2017-06-16 20:57
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by itsmeolivia** 2017-06-16 20:57 UTC
Labels: stat:awaiting response, type:build/install
