### ISSUE TITLE
C:/users/******/_bazel_quickride/obpmm2rb/external/double_conversion/BUILD.bazel:7:1: C++ compilation of rule '@double_conversion//:double-conversion' failed (Exit -1)

### ISSUE THREAD

**Issue by prasanna532** [tensorflow/tensorflow#21263] opened 2018-07-31 06:39 UTC
I stuck with this problem i had installed cmake also but iam not able to build the the tensarflow demo application.

C:/users/*****/_bazel_quickride/obpmm2rb/external/double_conversion/BUILD.bazel:7:1: C++ compilation of rule '@double_conversion//:double-conversion' failed (Exit -1)

**Comment by tensorflowbutler** [comment] 2018-07-31 19:00
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by prasanna532** [comment] 2018-08-01 05:08
OS Platform and Distribution -  Windows
TensorFlow installed from -  https://github.com/tensorflow/
TensorFlow version - I dint know exactly which version i took from the git hub latest pull.
Bazel version - I think  it latest 
CUDA/cuDNN version - NA
GPU model and memory - NA
Exact command to reproduce - Iam building the APK in which readme file sepecified in tensarflow/android.
Mobile device - One Plus 3, Samsung J7, Moto g

**Comment by tensorflowbutler** [comment] 2018-08-16 20:06
Nagging Assignee @tatianashp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by abcoep** [comment] 2018-08-25 16:13
You may be compiling with GCC 5 or later. I faced the same issue due to this and got it fixed by passing `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` as an argument to the `bazel build` command. It is required for GCC 5 or later as mentioned under [GPU Support](https://www.tensorflow.org/install/install_sources#gpu_support). The other alternative is to build with GCC 4.8.

**Comment by tensorflowbutler** [comment] 2018-09-09 18:36
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-24 12:47
Nagging Assignee @tatianashp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-09 18:43
Nagging Assignee @tatianashp: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment] 2018-10-10 01:20
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-10-10 01:20 UTC
