### ISSUE TITLE
reduce_sum and reduce_prod Permuting order of columns on Power9 CPUs

### ISSUE THREAD

**Issue by ajyeager** [tensorflow/tensorflow#43469] opened 2020-09-22 23:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary - community build
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: V100  32gb

**Describe the current behavior**
tf.reduce_sum is permuting the columns when producing the result.  Stand-alone code below produces a tensor [3.,4.,1.,2.]
This only happens when computation is on CPU and we've only been able to reproduce it on our Power9 machines.

**Describe the expected behavior**
tf.reduce_sum should preserve the order of columns.  It should produce [1.,2.,3.,4.]

**Standalone code to reproduce the issue**
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''

import tensorflow as tf
import numpy as np

x = tf.constant(np.array([[1.0,2.0,3.0,4.0],
       [0.0,0.0,0.0,0.0]]),
      dtype=tf.float32)

out = tf.reduce_sum(x, axis=0)
print(out)
```

Prints:

> tf.Tensor([3. 4. 1. 2.], shape=(4,), dtype=float32)
<img width="469" alt="Screen Shot 2020-09-22 at 6 57 33 PM" src="https://user-images.githubusercontent.com/11985639/93945751-8407f800-fd05-11ea-8008-793b0c72084e.png">

tf.reduce_prod is producing similar results:
<img width="470" alt="Screen Shot 2020-09-22 at 6 59 50 PM" src="https://user-images.githubusercontent.com/11985639/93945902-d9dca000-fd05-11ea-8496-e878adc64b19.png">

We notice the same thing in more complicated examples breaking the UnitNorm constraint, as it's using reduce_sum when computing the norm and then dividing vectors by a permutation of the relevant lengths.

**Comment by Saduf2019** [comment] 2020-09-23 04:22
@ajyeager 
I ran the code shared above and get the expected output, please have a look at the [gist here](https://colab.research.google.com/gist/Saduf2019/8ef665342db639e5f5af3746e04df85a/untitled.ipynb), could you please share a colab gist with the error reported.

**Comment by bhack** [comment] 2020-09-23 10:58
@tfboyd Do you still have any Power team contact for this?

**Comment by ajyeager** [comment] 2020-09-23 13:41
@Saduf2019  it's only happening on our Power based machines - I don't think it'll be reproducible on colab.

**Comment by jvishnuvardhan** [comment] 2020-09-25 20:09
@ajyeager Looks like this is related to your `Power9` machines. I tried [colab](https://colab.research.google.com/gist/jvishnuvardhan/78015a8265a1fcafd4796e9f1ead5df6/untitled.ipynb), windows, and Mac and I could not reproduce the issue. 

This is clearly not a bug or performance related issue related to TF. Thanks!

**Comment by bhack** [comment] 2020-09-25 21:06
@ajyeager I've tried your example with Docker/Qemu but It Is not working well with the official IBM image https://hub.docker.com/r/ibmcom/tensorflow-ppc64le

**Comment by ajyeager** [comment] 2020-09-28 18:58
I'm going to look into getting IBM involved, as I just tested and it happens in their official image too.

**Comment by tfboyd** [comment] 2020-09-30 16:05
@jayfurmanek   Jay was my contact in the past.

**Comment by jayfurmanek** [comment] 2020-09-30 16:32
There is a TF2.2 version in WML CE that doesn't have this problem:
https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/

There are no patches in that build for this problem. The community builds recently moved to the manylinux2014 compliant quay.io container, which has a devtoolset-8 compiler toolchain. The WMLCE one above uses Anaconda's 7.3 based toolchain. 

I've not proven it, but this problem is likely because of that devtoolset-8 compiler..

**Comment by jvishnuvardhan** [comment] 2021-01-13 18:02
@ajyeager Is this still an issue? 

Please close the issue If this was already resolved. Thanks!

**Closed** 2021-01-27 18:37 UTC
Labels: TF 2.2, comp:ops, stalled, stat:awaiting response, type:bug
