### ISSUE TITLE
no such package '@llvm//'

### ISSUE THREAD

**Issue by tycho** [tensorflow/tensorflow#13106] opened 2017-09-17 22:43 UTC
Trying to build latest git tree (`git describe --tags` calls it `v1.3.0-rc1-2262-g74cfc64734`):

>ERROR: /build/tensorflow-git/src/tensorflow/tensorflow/tools/pip_package/BUILD:101:1: no such package '@llvm//': java.io.IOException: Error downloading [http://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/9aafb854cc7cb8df8338c50cb411a54ce1e09796.tar.gz, https://github.com/llvm-mirror/llvm/archive/9aafb854cc7cb8df8338c50cb411a54ce1e09796.tar.gz] to /build/.cache/bazel/_bazel_builduser/a152fcd393afbe6f0b02d283bc9e6174/external/llvm/9aafb854cc7cb8df8338c50cb411a54ce1e09796.tar.gz: Checksum was e8f07137a3a0b95e143c0665cd19160dd5040114b34a48653fa7f5f91cf4c136 but wanted 2a6d4c23f6660d9130d8d5f16267db53a87f8d0104f9618b558c033570f110af and referenced by '//tensorflow/tools/pip_package:licenses'.

Surely the correct fix is *not* to just to change the expected checksum to match the observed one?

**Comment by tycho** [comment] 2017-09-17 22:49
Attempted the build a second time and it worked. I'm puzzled as to why this failed in the first place, because as far as I can tell, nothing changed. Both build attempts were done in fresh chroots, and the git repo didn't change either as far as I saw.

**Comment by yslai** [comment] 2017-09-18 07:59
This is usually due to GitHub's hash change, and you not downloading from mirror.bazel.build successfully (therefore falling back to GitHub and picking up the changed hash):

```
$ wget -q -O - http://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/9aafb854cc7cb8df8338c50cb411a54ce1e09796.tar.gz | sha256sum
2a6d4c23f6660d9130d8d5f16267db53a87f8d0104f9618b558c033570f110af  -
$ wget -q -O - http://github.com/llvm-mirror/llvm/archive/9aafb854cc7cb8df8338c50cb411a54ce1e09796.tar.gz | sha256sum
e8f07137a3a0b95e143c0665cd19160dd5040114b34a48653fa7f5f91cf4c136  -
```

**Comment by tycho** [comment] 2017-09-18 21:07
Hm, it's frustrating that the hash on the GitHub copy can change.

What kind of retry logic is there around trying to fetch from mirror.bazel.build, in the case of transient errors? If we can't rely on the github copy's hash to validate then we should try really hard not to get that one, I would think...

**Comment by aselle** [comment] 2017-09-21 16:29
@gunan, I assume this is a duplicate of #12979.

**Closed** 2017-09-21 16:35 UTC
Labels: stat:awaiting tensorflower, type:build/install
