### ISSUE TITLE
No module 'sparse_softmax_cross_entropy_with_logits' in cifar10_train.py on master

### ISSUE THREAD

**Issue by cuongduc** [tensorflow/tensorflow#1235] opened 2016-02-22 11:04 UTC
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: Ubuntu 15.10

I have the following issue when running cifar10_train.py on master

```
python cifar10_train.py
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Traceback (most recent call last):
  File "cifar10_train.py", line 101, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 98, in main
    train()
  File "cifar10_train.py", line 41, in train
    loss = cifar10.loss(logits, labels)
  File "/home/kde/Code/tf/cifar10/cifar10.py", line 244, in loss
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(
AttributeError: 'module' object has no attribute 'sparse_softmax_cross_entropy_with_logits'
```

**Comment by ebrevdo** [comment] 2016-02-23 06:26
Are you using tf compiled from git? If so, how recent?

**Comment by cuongduc** [comment] 2016-02-23 08:56
@ebrevdo No, I installed TensorFlow via the following command

```
# Ubuntu/Linux 64-bit, CPU only:
$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
```

**Comment by ebrevdo** [comment] 2016-02-28 03:21
That version may not have the function. Try building the package from HEAD.

**Comment by ebrevdo** [comment] 2016-03-09 17:16
Did that solve the problem?

**Comment by yazabaza** [comment] 2016-03-24 21:23
I had the same problem. I tried building Tensorflow from the latest source (cloned on March 23 2016). However, the build fails with the following error, so we are still stuck:
ERROR: /Users/ron/Documents/Software/Neural/tensorflow-git-repository/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@plottable//': Error cloning repository: Unexpected end of file from server caused by Unexpected end of file from server caused by Unexpected end of file from server and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Loading failed; build aborted.

**Comment by martinwicke** [comment] 2016-03-24 23:43
@danmane This looks like a tensorboard dependency, can you verify?

**Comment by danmane** [comment] 2016-03-30 07:40
Yes, that is a TensorBoard dependency. It looks like something went wrong in the connection to GitHub while Bazel was downloading plottable (unexpected end of file from server).

Can you try re-building and see if it works? If it still doesn't work try `bazel clean` and try again?

**Comment by yazabaza** [comment] 2016-03-30 23:44
I rebuilt succesfully with Bazel. However, installation broke something:
```
ImportError: No module named protobuf
Error importing tensorflow.  Unless you are using bazel, you should not try to import tensorflow from its source directory; please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```
Others reported this also, see issue 498. Will keep at it.

**Comment by girving** [comment] 2016-06-06 22:01
Closing since the original issue is fixed.

**Closed by girving** 2016-06-06 22:01 UTC
