### ISSUE TITLE
Optimization flags are erroneously ignored in compilation of Tensorflow 1.1.0-rc1

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#9149] opened 2017-04-11 23:42 UTC
I am getting a large number of optimization flag related warnings in compilation of Tensorflow 1.1.0-rc1 from source

```
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
```
System Information:  
OS:CentOS 7
GCC: gcc 4.8.5
Python: python3.5
Tensorflow version:  TensorFlow 1.1.0-rc1
Bazel:  version 0.4.5
CUDA: CUDA 8.0 with GTX 1080 GPU

in the prompt of ./configure:

```
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] Y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
```
explicitly typing `-march=native -O2` or `-O2` in the line `Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: `"doesn't help. 

to compile I used:

`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

I tried as early as tensorflow version 1.0.0 and I always get the "`warning _FORTIFY_SOURCE requires compiling with optimization (-O)`". Tensorflow version 0.12.1 doesn't seem to have this problem for me. 

Related issue:
#2153

**Comment by jart** [comment] 2017-04-12 00:16
Could you pass `-s` to bazel build so we can see what the flags are that are being passed to g++ when this error is raised? I just tried compiling a little bit at HEAD and it seems to be passing `-O2` when I say `--config=opt`.

**Comment by maomaocode** [comment] 2017-04-12 00:39
@jart 
Thanks so much for your help. Here is my ./configure prompt
```
./configure
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib/python3.5/site-packages
  /usr/lib64/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3.5/site-packages]

Using python library path: /usr/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N] 
nvcc will be used as CUDA compiler
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the cuDNN version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
```
I have attached the 
executing` bazel build -s --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

The output looks like the following, I am not sure if I am copying the right snippet with the information you need. 

`external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++11' '-march=native' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_stream.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_stream.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -DSNAPPY -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/jemalloc -iquote bazel-out/local_linux-py3-opt/genfiles/external/jemalloc -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-py3-opt/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -iquote external/snappy -iquote bazel-out/local_linux-py3-opt/genfiles/external/snappy -iquote external/local_config_cuda -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda -isystem external/jemalloc/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/jemalloc/include -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/stream_executor/cuda/cuda_stream.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_stream.pic.o)
`

**Comment by jart** [comment] 2017-04-12 01:40
It helps if you can identify the specific invocation that triggered the warning, because -O2 is present in that one.

Also for future reference, we have an on-call rotation for triaging issues. It's not necessary to tag individuals when filing tickets. Let us take care of that for you.

**Comment by jart** [comment] 2017-04-12 01:40
cc: @wichtounet @vladfi1 who also reported this in https://github.com/tensorflow/tensorflow/issues/2153.

**Comment by maomaocode** [comment] 2017-04-12 02:50
Thanks jart. I have removed all individual tags. Sorry about that.

Here is the snipped of one file that has this not using optimization warning

```
>>>>> # //tensorflow/core/kernels:segment_reduction_ops [action 'Compiling tensorflow/core/kernels/segment_reduction_ops.cc']
(cd /home/user/.cache/bazel/_bazel_chongli/f272c01b20e6327aedaf5e56025f70d2/execroot/tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/lib:/home/cad/MATLAB/R2016b/sys/os/glnxa64:/usr/lib64:/usr/local/lib:/home/cad/gurobi/linux64/lib:/usr/local/cuda/lib64 \
    PATH=/usr/local/cuda/bin:/home/cad/gurobi/linux64/bin:/usr/local/cuda/bin:/home/cad/intel/compilers_and_libraries_2017.1.132/linux/bin/intel64:/home/cad/intel/compilers_and_libraries_2017.1.132/linux/mpi/intel64/bin:/home/cad/intel/debugger_2017/gdb/intel64_mic/bin:/home/cad/gurobi/linux64/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/user/.local/bin:/home/user/bin \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION='' \
    TF_CUDNN_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++11' '-march=native' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/core/kernels/_objs/segment_reduction_ops/tensorflow/core/kernels/segment_reduction_ops.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/core/kernels/_objs/segment_reduction_ops/tensorflow/core/kernels/segment_reduction_ops.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -DSNAPPY -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_sycl -iquote external/jemalloc -iquote bazel-out/local_linux-py3-opt/genfiles/external/jemalloc -iquote external/protobuf -iquote bazel-out/local_linux-py3-opt/genfiles/external/protobuf -iquote external/gif_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -iquote external/snappy -iquote bazel-out/local_linux-py3-opt/genfiles/external/snappy -iquote external/local_config_cuda -iquote bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive -isystem external/jemalloc/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/jemalloc/include -isystem external/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/protobuf/src -isystem external/gif_archive/lib -isystem bazel-out/local_linux-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-py3-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-py3-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda/include -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/external/local_config_cuda/cuda -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-DGOOGLE_CUDA=1' -msse3 -pthread '-DGOOGLE_CUDA=1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/kernels/segment_reduction_ops.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/core/kernels/_objs/segment_reduction_ops/tensorflow/core/kernels/segment_reduction_ops.pic.o)
INFO: From Compiling tensorflow/core/kernels/depthtospace_op_gpu.cu.cc:
In file included from external/local_config_cuda/cuda/include/host_config.h:173:0,
                 from external/local_config_cuda/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from external/local_config_cuda/cuda/include/host_config.h:173:0,
                 from external/local_config_cuda/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)

```

Please let me know if there is any other information that I can provide. Thanks!

**Comment by jart** [comment] 2017-04-12 03:36
That's interesting. It still says that, even though `-O2` is being passed.

CentOS7 is definitely in our support matrix. However this is a problem Bazel might need to solve. There seems to be a bug tracking this. https://github.com/bazelbuild/bazel/issues/1762 It might help if you tell them your OS and GCC version combos.

Since this is only a warning, no workaround should be necessary.

cc: @wichtounet @vladfi1
See also: https://github.com/tensorflow/serving/issues/137

**Comment by maomaocode** [comment] 2017-04-12 04:33
jart I would say it is more than just a warning. It was mentioned in #2153 that that a tensorflow binary compiled with this warning is 10% slower than the binary provided by Google. Can you further advise please?

**Comment by jart** [comment] 2017-04-12 05:01
10%, while nontrivial, is still a tenth of a order of a magnitude. As you mentioned, the binary provided by Google is still a possibility. I agree that this is an issue that needs to be solved. However it only appears to affect certain platforms. It doesn't appear to be an issue in TensorFlow itself. Please let me know if my assessment is inaccurate.

**Comment by maomaocode** [comment] 2017-04-12 05:16
jart I agree with your assessment. Meanwhile, can you please tag someone who may have more information regarding this issue?

**Comment by jart** [comment] 2017-04-12 05:34
If you're Mao Mao then I'm Cao Cao when it comes to build systems. You have my assurance that I've offered you first class support today.

**Comment by maomaocode** [comment] 2017-04-12 05:39
Thank you jart.

**Comment by XapaJIaMnu** [comment] 2017-05-09 19:48
Any updates on this?

**Comment by maomaocode** [comment] 2017-05-10 17:05
The problem continues with v1.1.0 release.

**Comment by jart** [comment] 2017-05-10 20:39
Since this is only a build warning for CentOS, and multiple users are now reporting this, I'm going to reopen and mark it contributions welcome.

**Comment by ipoletaev** [comment] 2017-05-18 17:09
I have the same issue with openSUSE, python 2.7, GTX 980 Ti, gcc 4.8.3. and the latest version of bazel.

**Comment by alessandroaimar** [comment] 2017-05-26 18:22
same error on Fedora 25, anaconda 3, GTX 750 TI, gcc54, bazel 5

**Comment by gunan** [comment] 2017-06-16 22:46
I think the problem is, we configure using SIMD instruction sets when running with `--config=opt`. You should be able to solve this by adding `--copt=-O2` to our bazelrc when running configure.
As I cannot test this, I will leave this as contributions welcome.

**Comment by wt-huang** [comment] 2018-11-10 03:42
Closing as this is resolved

**Closed by wt-huang** 2018-11-10 03:42 UTC
Labels: stat:contributions welcome, type:build/install
