### ISSUE TITLE
Select TensorFlow op（FlexTensorArrayV3）is not supported by this interpreter

### ISSUE THREAD

**Issue by Clara2333333** [tensorflow/tensorflow#58833] opened 2022-12-09 13:28 UTC
**System information**
- OS Platform and Distribution (Win10):
- TensorFlow version (TensorFlow_v1):

**Provide the text output from tflite_convert**
I have already followed the instructions: [https://www.tensorflow.org/lite/guide/ops_select](https://www.tensorflow.org/lite/guide/ops_select)
When I'm trying to convert, I used:
```
import tensorflow as tf
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file="D:\myhome\\fish_detection-master\models\\research\object_detection\\fish_inception_v2_graph2\\frozen_inference_graph.pb",
                    # both `.pb` and `.pbtxt` files are accepted.
    input_arrays=['image_tensor'],
    input_shapes={'image_tensor' : [None,None,None,3]},
    output_arrays=['SecondStagePostprocessor/Softmax']
)
converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
]
tflite_model = converter.convert()
# Save the model.
with open('model.tflite', 'wb') as f:
    f.write(tflite_model) 
```
It's all right when converting.
Then, I add the "org.tensorflow:tensorflow-lite-select-tf-ops" dependency in Android Studio by using the following code:
`implementation 'org.tensorflow:tensorflow-lite:2.11.0`
`implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.11.0`

However,there is something wrong.

This is the model that I used [https://github.com/kwea123/fish_detection/tree/master/fish_inception_v2_graph2/frozen_inference_graph.pb](https://github.com/kwea123/fish_detection/tree/master/fish_inception_v2_graph2/frozen_inference_graph.pb)

Here is my error in Android Studio:
E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
E/tflite: Node number 3 (FlexTensorArrayV3) failed to prepare.
E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
E/tflite: Node number 3 (FlexTensorArrayV3) failed to prepare.
E/TaskJniUtils: Error getting native address of native library: task_vision_jni
    java.lang.IllegalStateException: Error occurred when initializing ObjectDetector: AllocateTensors() failed.
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithModelFdAndOptions(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$000(ObjectDetector.java:88)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:156)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:149)
        at org.tensorflow.lite.task.core.TaskJniUtils$1.createHandle(TaskJniUtils.java:70)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromFdAndOptions(TaskJniUtils.java:66)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromFileAndOptions(ObjectDetector.java:147)
        at org.tensorflow.lite.examples.objectdetection.ObjectDetectorHelper.setupObjectDetector(ObjectDetectorHelper.kt:96)
        at org.tensorflow.lite.examples.objectdetection.ObjectDetectorHelper.detect(ObjectDetectorHelper.kt:107)
        at org.tensorflow.lite.examples.objectdetection.fragments.CameraFragment.detectObjects(CameraFragment.kt:289)
        at org.tensorflow.lite.examples.objectdetection.fragments.CameraFragment.bindCameraUseCases$lambda-9$lambda-8(CameraFragment.kt:264)
        at org.tensorflow.lite.examples.objectdetection.fragments.CameraFragment.$r8$lambda$trA1WWYM4Jg8atYGW5F6kpxoOW8(Unknown Source:0)
        at org.tensorflow.lite.examples.objectdetection.fragments.CameraFragment$$ExternalSyntheticLambda7.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:476)
        at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda0.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:283)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(Unknown Source:14)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/Test: TFLite failed to load model with error: Error getting native address of native library: task_vision_jni
D/EGL_emulation: eglMakeCurrent: 0xebf41200: ver 2 0 (tinfo 0xe0075a30)

 **Whether the op called FlexTensorArrayV3 can be used to inference on Android device by using org.tensorflow:tensorflow-lite-select-tf-ops:2.11.0 Android project .Dose it mean that FlexTensorArrayV3 is unlikely to be used in inference on Android device and  I should change my model?**

**Comment by mohantym** [comment] 2022-12-13 08:58
Hi @Clara2333333 !
I think it is a compatibility issue coming tf.compat.v1.lite.TFLiteConverter.from_frozen_graph with 2.x select ops syntax.

Can you convert the above frozen graph  to 2.x saved model format  using tf.io.gfile.Gfile and test the conversion again  with select ops syntax  to see whether the error exists.

Thank you!

**Comment by Clara2333333** [comment] 2022-12-24 04:14
> Hi @Clara2333333 ! I think it is a compatibility issue coming tf.compat.v1.lite.TFLiteConverter.from_frozen_graph with 2.x select ops syntax.
> 
> Can you convert the above frozen graph to 2.x saved model format using tf.io.gfile.Gfile and test the conversion again with select ops syntax to see whether the error exists.
> 
> Thank you!

I'll try this method~ Thanks for your reply!!!

**Comment by mohantym** [comment] 2022-12-26 16:53
@Clara2333333 !

We are checking to see whether you still need help in this issue . 
Could you confirm whether the issue is resolved or not .

Thank you!

**Comment by Clara2333333** [comment] 2022-12-27 00:48
> @Clara2333333 !
> 
> We are checking to see whether you still need help in this issue . Could you confirm whether the issue is resolved or not .
> 
> Thank you!

The issue is resolved by using other ways to transfer. Thanks!

**Comment by mohantym** [comment] 2022-12-27 04:18
@Clara2333333 !

Thanks for the confirmation. Marking this as resolved.
Feel free to open if you still need further assistance.

Thank you!

**Closed by mohantym** 2022-12-27 04:18 UTC
Labels: type:bug, comp:lite, TF 2.11
