### ISSUE TITLE
not even getting detected for the python3.8.1

### ISSUE THREAD

**Issue by vishwas1234567** [tensorflow/tensorflow#36197] opened 2020-01-25 06:04 UTC
![image](https://user-images.githubusercontent.com/48592314/73117091-98bda180-3f66-11ea-9ad4-163ea27b8904.png)

**Comment by ashutosh1919** [comment] 2020-01-25 11:47
@vishwas1234567, Please take a look at [this issue](https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-577331441). It says that tensorflow is not supported for python 3.8 as of now. And if we talk about tensorflow 2.0 specifically, it supports the python range 3.4 to 3.7. If your computer has python 3.8 installed then you can install 3.7 too and use virtualenv to install tensorflow. Below is what you can do : 

```sh
$ virtualenv --python=python3.7 my_venv  
$ source my_venv/bin/activate 
$ pip install tensorflow  
```

If your issue resolves by this method then please close the issue.

**Comment by mihaimaruseac** [comment] 2020-01-26 02:46
Closing as duplicate of #33374. Please use search before opening new issues, especially when opening multiple related ones.

**Closed by mihaimaruseac** 2020-01-26 02:46 UTC
