### ISSUE TITLE
No data found in layer when fitting TF 2.0 Keras model with DenseFeatures as input

### ISSUE THREAD

**Issue by thisisandreeeee** [tensorflow/tensorflow#35151] opened 2019-12-16 10:40 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-4.14.106+-x86_64-with-debian-buster-sid
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.6

**Describe the current behavior**
I am trying to train a model using:
* TF 2.0 Keras functional API
* Feature columns and `DenseFeatures` as the input layer
* tf.data.Dataset API as the `x` parameter in model.fit()

This raises a ValueError, and I'm not sure why because this doesn't work even with (what I think is) a minimal example. I suspect that this might be due to TF trying to match the feature columns to the inputs by name, but the name of the Input tensor contains a suffix e.g. `age:0`, but I may very well be mistaken.

Might be related to: https://github.com/tensorflow/tensorflow/issues/30143

**Describe the expected behavior**
I expect to be able to train a model using the Keras functional API using data from the Dataset API, with feature_columns being fed into Input layers.

**Code to reproduce the issue**
The following test case does not represent my use case, but it does reproduce the problem. Despite what the simplistic example suggests, I explicitly require both feature_columns and the functional API so suggesting that I use other TF libraries would not be an option, unless I can replicate the same functionality with minimal effort.

```python
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import DenseFeatures, Dense, Input

def make_model(features):
    feature_columns = [tf.feature_column.numeric_column(key) for key in features]
    nn_input = {key: Input(name=key, shape=(), dtype=tf.float32) for key in features}

    feat = DenseFeatures(feature_columns)(nn_input)
    dense = Dense(16)(feat)
    output = Dense(1)(dense)
    model = tf.keras.Model(inputs=nn_input, outputs=output)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
        metrics=[tf.keras.metrics.AUC()],
    )
    return model

features = ["age", "income"]
label = "is_male"

input_dataset = tf.data.Dataset.from_tensor_slices(
    {key: np.ones((1000, 1), dtype=np.float) for key in features}
)
target_dataset = tf.data.Dataset.from_tensor_slices(
    {label: np.ones((1000, 1), dtype=np.int)}
)
complete_dataset = tf.data.Dataset.zip((input_dataset, target_dataset)).shuffle(10000)

model = make_model(features)
model.summary()
model.fit(complete_dataset)
```

This code references the issue created by @durandg12. Thank you.

**Stack trace**
```bash
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    498           if data[x].__class__.__name__ == 'DataFrame' else data[x]
--> 499           for x in names
    500       ]

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py in <listcomp>(.0)
    498           if data[x].__class__.__name__ == 'DataFrame' else data[x]
--> 499           for x in names
    500       ]

KeyError: 'dense_1'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-0081a84113eb> in <module>
     27 model = make_model(features)
     28 model.summary()
---> 29 model.fit(complete_dataset)

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    322                 mode=ModeKeys.TRAIN,
    323                 training_context=training_context,
--> 324                 total_epochs=epochs)
    325             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    326 

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in distributed_function(input_iterator)
     71     strategy = distribution_strategy_context.get_strategy()
     72     outputs = strategy.experimental_run_v2(
---> 73         per_replica_function, args=(model, x, y, sample_weights))
     74     # Out of PerReplica outputs reduce or pick values to return.
     75     all_outputs = dist_utils.unwrap_output_dict(

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in experimental_run_v2(self, fn, args, kwargs)
    758       fn = autograph.tf_convert(fn, ag_ctx.control_status_ctx(),
    759                                 convert_by_default=False)
--> 760       return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    761 
    762   def reduce(self, reduce_op, value, axis):

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in call_for_each_replica(self, fn, args, kwargs)
   1785       kwargs = {}
   1786     with self._container_strategy().scope():
-> 1787       return self._call_for_each_replica(fn, args, kwargs)
   1788 
   1789   def _call_for_each_replica(self, fn, args, kwargs):

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in _call_for_each_replica(self, fn, args, kwargs)
   2130         self._container_strategy(),
   2131         replica_id_in_sync_group=constant_op.constant(0, dtypes.int32)):
-> 2132       return fn(*args, **kwargs)
   2133 
   2134   def _reduce_to(self, reduce_op, value, destinations):

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    290   def wrapper(*args, **kwargs):
    291     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 292       return func(*args, **kwargs)
    293 
    294   if inspect.isfunction(func) or inspect.ismethod(func):

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in train_on_batch(model, x, y, sample_weight, class_weight, reset_metrics)
    251   x, y, sample_weights = model._standardize_user_data(
    252       x, y, sample_weight=sample_weight, class_weight=class_weight,
--> 253       extract_tensors_from_dataset=True)
    254   batch_size = array_ops.shape(nest.flatten(x, expand_composites=True)[0])[0]
    255   # If `model._distribution_strategy` is True, then we are in a replica context

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2517           shapes=None,
   2518           check_batch_axis=False,  # Don't enforce the batch size.
-> 2519           exception_prefix='target')
   2520 
   2521       # Generate sample-wise weight values given the `sample_weight` and

/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    501     except KeyError as e:
    502       raise ValueError('No data provided for "' + e.args[0] + '". Need data '
--> 503                        'for each key in: ' + str(names))
    504   elif isinstance(data, (list, tuple)):
    505     if isinstance(data[0], (list, tuple)):

ValueError: No data provided for "dense_1". Need data for each key in: ['dense_1']
```

**Comment by thisisandreeeee** [comment] 2019-12-16 11:04
I've also borrowed code from [this medium tutorial](https://towardsdatascience.com/how-to-build-a-wide-and-deep-model-using-keras-in-tensorflow-2-0-2f7a236b5a4b), and it works up till the point of `model.compile()` but it fails when I try to run `model.fit()`. I suspect the format which the data is being passed to the fit function may be incorrect but I'm not too sure why.

Any help here would be deeply appreciated. Thanks!

**Comment by durandg12** [comment] 2019-12-16 11:14
Simply calling the model on some inputs works:
```
for x, y in complete_dataset.take(1):
    pass
model(x) 
```

**Comment by durandg12** [comment] 2019-12-16 13:06
Your issue is not tied to feature columns nor the DenseFeatures layers, as the code reproduce your error:
```
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense, Input

def make_model(features):
    nn_input = {key: Input(name=key, shape=(1), dtype=tf.float32) for key in features}
    
    dense = Dense(16, name='dense1')(nn_input['age'])
    output = Dense(1, name='dense2')(dense)
    model = tf.keras.Model(inputs=nn_input, outputs=output)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
    )
    return model

features = ["age"]
label = "is_male"

input_dataset = tf.data.Dataset.from_tensor_slices(
    {key: np.ones((1000, 1), dtype=np.float) for key in features}
)
target_dataset = tf.data.Dataset.from_tensor_slices(
    {label: np.ones((1000, 1), dtype=np.int)}
)
complete_dataset = tf.data.Dataset.zip((input_dataset, target_dataset)).shuffle(10000)

model = make_model(features)
model.summary()
model.fit(complete_dataset)
```

**Comment by durandg12** [comment] 2019-12-16 13:42
I have found the cause of your issue, it is because you feed target data as a dict instead of just a numpy array. If you feed a dict, the key of the dict must not be `label`but must be the name of the layer outputting your prediction, in this case, `dense_1`, so the two following modifications of your code work:
```
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import DenseFeatures, Dense, Input

def make_model(features):
    feature_columns = [tf.feature_column.numeric_column(key) for key in features]
    nn_input = {key: Input(name=key, shape=(), dtype=tf.float32) for key in features}

    feat = DenseFeatures(feature_columns)(nn_input)
    dense = Dense(16)(feat)
    output = Dense(1)(dense)
    model = tf.keras.Model(inputs=nn_input, outputs=output)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
        metrics=[],
    )
    return model

features = ["age", "income"]
label = "is_male"

input_dataset = tf.data.Dataset.from_tensor_slices(
    {key: np.ones((1000, 1), dtype=np.float) for key in features}
)
target_dataset = tf.data.Dataset.from_tensor_slices(
    np.ones((1000, 1), dtype=np.int)
)
complete_dataset = tf.data.Dataset.zip((input_dataset, target_dataset)).shuffle(10000)

model = make_model(features)
model.summary()
model.fit(complete_dataset)
```
or 
```
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import DenseFeatures, Dense, Input

def make_model(features):
    feature_columns = [tf.feature_column.numeric_column(key) for key in features]
    nn_input = {key: Input(name=key, shape=(), dtype=tf.float32) for key in features}

    feat = DenseFeatures(feature_columns)(nn_input)
    dense = Dense(16)(feat)
    output = Dense(1)(dense)
    model = tf.keras.Model(inputs=nn_input, outputs=output)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
        metrics=[],
    )
    return model

features = ["age", "income"]
label = "is_male"

input_dataset = tf.data.Dataset.from_tensor_slices(
    {key: np.ones((1000, 1), dtype=np.float) for key in features}
)
target_dataset = tf.data.Dataset.from_tensor_slices(
    {'dense_1': np.ones((1000, 1), dtype=np.int)}
)
complete_dataset = tf.data.Dataset.zip((input_dataset, target_dataset)).shuffle(10000)

model = make_model(features)
model.summary()
model.fit(complete_dataset)
```
In the first I have replaced the dict by a numpy array, in the second I have changed the key of the dict.
In both modifications I have removed the metric as it caused another error.

**Comment by thisisandreeeee** [comment] 2019-12-17 02:09
@durandg12 thank you, this works really well. I think the reason why there was an error calculating the AUC was that all of the target values were of the same class.

On a side note, is it intended behaviour for tensorflow to raise an exception when the final layer is not named according to the output tensors? Or does tensorflow only accept target inputs where the target is a list, instead of a dictionary of tensors as you would expect of the feature inputs?

**Comment by jvishnuvardhan** [comment] 2020-04-10 14:28
@thisisandreeeee Is this resolved. If this was resolved already, please close the issue. Thanks!

**Closed** 2020-04-15 15:00 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support
