### ISSUE TITLE
error: 'is_final' is not a member of 'std'

### ISSUE THREAD

**Issue by mahmoodn** [tensorflow/tensorflow#31866] opened 2019-08-21 21:23 UTC
With 
  bazel 0.26.1
  gcc 7.4
  cuda 10.1 update 2

and the latest git clone of tensorflow, I hit the following error at the bazel build command

```
ERROR: /home/mh.naderan/.cache/bazel/_bazel_mh.naderan/dacf7a124fc721f30ac789c201b3b139/external/llvm/BUILD.bazel:201:1: C++ compilation of rule '@llvm//:llvm-tblgen' failed (Exit 1)
In file included from external/llvm/include/llvm/TableGen/Record.h:27:0,
                 from external/llvm/utils/TableGen/SubtargetFeatureInfo.h:13,
                 from external/llvm/utils/TableGen/SubtargetFeatureInfo.cpp:9:
external/llvm/include/llvm/Support/TrailingObjects.h: In static member function 'static void llvm::TrailingObjects<BaseTy, TrailingTys>::verifyTrailingObjectsAssertions()':
external/llvm/include/llvm/Support/TrailingObjects.h:252:24: error: 'is_final' is not a member of 'std'
     static_assert(std::is_final<BaseTy>(), "BaseTy must be final.");
                        ^~~~~~~~
external/llvm/include/llvm/Support/TrailingObjects.h:252:24: note: suggested alternative: 'is_heap'
     static_assert(std::is_final<BaseTy>(), "BaseTy must be final.");
                        ^~~~~~~~
                        is_heap
external/llvm/include/llvm/Support/TrailingObjects.h:252:39: error: expected primary-expression before '>' token
     static_assert(std::is_final<BaseTy>(), "BaseTy must be final.");
                                       ^
external/llvm/include/llvm/Support/TrailingObjects.h:252:41: error: expected primary-expression before ')' token
     static_assert(std::is_final<BaseTy>(), "BaseTy must be final.");
                                         ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 442.171s, Critical Path: 25.05s
INFO: 1254 processes: 1254 local.
FAILED: Build did NOT complete successfully

```

**Comment by bas-aarts** [comment] 2019-08-21 22:33
see https://github.com/tensorflow/tensorflow/commit/09c588de14f02bc2f07e6de8fca01093f92ba4f0

**Comment by plopresti** [comment] 2019-08-21 23:21
@bas-aarts I get the same failure. (Doesn't everyone? Why not?) Reverting 09c588d fixes it for me.

**Comment by mahmoodn** [comment] 2019-08-22 07:53
OK. I fixed that. I am looking for a working version of tensorflow. I hit another error on 1.14.0 which is described in another thread.

**Comment by plopresti** [comment] 2019-08-22 16:02
@mahmoodn What was the fix?

**Comment by plopresti** [comment] 2019-08-22 16:48
Re-filed as #31900, since this is definitely not fixed.

**Comment by jvishnuvardhan** [comment] 2019-09-04 04:08
@mahmoodn Is this duplicate of https://github.com/tensorflow/tensorflow/issues/31900? If yes, close this as the code owner is communicating with the user in that issue. Thanks!

**Comment by mahmoodn** [comment] 2019-09-06 10:04
Yes. Mine was fixed.
However, @plopresti still has the problem based on his last post.

**Comment by jvishnuvardhan** [comment] 2019-09-06 18:32
@mahmoodn I am closing this issue are it was resolved. @plopresti had opened another issue https://github.com/tensorflow/tensorflow/issues/31900. Thanks!

**Closed by jvishnuvardhan** 2019-09-06 18:32 UTC
Labels: stat:awaiting response, subtype:bazel, type:build/install
