### ISSUE TITLE
No gradient for argmax

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#15278] opened 2017-12-11 16:00 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: 1.5.0-dev20171210 (nightly from today)
- **Python version**: 3.6.2

`ArgMax` crashes with `no gradient` error. I had a working version before I made slight adjustments to my code. I am very confused how this error can happen.

Stacktrace:
```
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_runner.py", line 46, in _execute_schedule
    return task()
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 377, in train
    saving_listeners=self._saving_listeners)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 824, in _call_train
    saving_listeners=saving_listeners)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\python\estimator\estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\python\estimator\estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\python\estimator\estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\gan\python\estimator\python\gan_estimator_impl.py", line 162, in _model_fn
    add_summaries)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\gan\python\estimator\python\gan_estimator_impl.py", line 235, in _gan_model_fn
    labels=None)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\gan\python\estimator\python\head_impl.py", line 189, in create_estimator_spec
    self._discriminator_optimizer)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\gan\python\train.py", line 540, in gan_train_ops
    **kwargs)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\contrib\training\python\training\training.py", line 447, in create_train_op
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\python\training\optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Development\Tools\miniconda\envs\mpgan-nightly\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'Generator/cond/generator/generator/while/BasicDecoderStep/TrainingHelperSample/ArgMax' (op type: ArgMax)
```

**Comment by facaiy** [comment] 2017-12-12 02:23
It seems duplicate of https://github.com/tensorflow/tensorflow/issues/14931#issuecomment-347751803

>Ah sorry, brain freeze. Actually, we could create a practical implementation of gradient for argmax, but it just wouldn't be very useful for learning.

**Comment by sleighsoft** [comment] 2017-12-12 07:18
What makes me wonder is that my generator worked in a previous configuration and the error originates from `tf.contrib.seq2seq.TrainingHelper` which is a common class for seq2seq training. The only thing I believe I have changed is switching from tf1.4 to tf1.5 nightly

**Comment by sleighsoft** [comment] 2017-12-12 08:58
So I tested my code with tensorflow 1.4 instead of tf-nightly from yesterday and I do not get the `ArgMax no gradient` bug. This seems to be an issue in 1.5 (nightly)

**Comment by joel-shor** [comment] 2017-12-12 09:37
It seems likely unrelated to your particular code, but just in case (and for completion) can you include the code snippet that is throwing this error?

**Comment by sleighsoft** [comment] 2017-12-12 09:41
I cannot share the whole code, it is rather large.
But it comes from the `TrainingHelper`

```python
embedded_input = tf.nn.embedding_lookup(
            params=embedding,
            ids=input_data)
helper = tf.contrib.seq2seq.TrainingHelper(
              inputs=embedded_input,
              sequence_length=sequence_length,
              time_major=self.time_major)

rnn_initial_state = tf.zeros([batch_size, self.cell_
rnn_initial_state = tf.contrib.rnn.LSTMStateTuple(
          rnn_initial_state, rnn_initial_state)

rnn_initial_state = tf.zeros([batch_size, self.cell_size])
rnn_initial_state = tf.contrib.rnn.LSTMStateTuple(
    rnn_initial_state, rnn_initial_state)

decoder = tf.contrib.seq2seq.BasicDecoder(
    cell=rnn_cell,
    helper=helper,
    initial_state=rnn_initial_state,
    output_layer=output_projection)
final_outputs, state, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder=decoder,
    maximum_iterations=maximum_iterations,
    output_time_major=self.time_major,
    swap_memory=True,
    scope=scope)
```

**Comment by facaiy** [comment] 2017-12-12 10:52
Perhaps it is related to 69c32459 , which removed the `tf.cast` about 5 days ago.

```python
import tensorflow as tf

a = tf.constant([1.0])
b = a * 2

def use_cast(b):
    c = tf.argmax(b, axis=-1)
    c = tf.cast(c, tf.int32)
    return c

def not_use_cast(b):
    return tf.argmax(b, axis=-1, output_type=tf.int32)

print("use cast:")
print(tf.gradients(use_cast(b), a))

print("===========")
print("not use cast")
print(tf.gradients(not_use_cast(b), a))
```
Output:
```python
~/Downloads ❯❯❯ python test.py                                                               ⏎
use cast:
[None]
===========
not use cast
Traceback (most recent call last):
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 551, in gradients
    grad_fn = ops.get_gradient_function(op)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2134, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: ArgMax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    print(tf.gradients(not_use_case(b), a))
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 555, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'ArgMax_1' (op type: ArgMax)
```

**Comment by sleighsoft** [comment] 2017-12-12 10:55
That seems to be a hot lead.
Will it be added back then :D

**Comment by sleighsoft** [comment] 2017-12-13 21:44
Must be. The helper is of no use for me with that bug being present

**Comment by facaiy** [comment] 2017-12-13 23:33
@sleighsoft could you revert the change of 69c3245 on your tensorflow (I mean, the python file,  which is installed on your computer) and test whether it works?

**Comment by sleighsoft** [comment] 2017-12-14 09:12
Probably not today but I can try it out by tomorrow

**Comment by sleighsoft** [comment] 2017-12-14 16:51
I tested it with the reverted code and then it works.
Another interesting thing is that with tfnightly I get the
```
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Create CheckpointSaverHook.
```
twice. And also 2x
```
INFO:tensorflow:Saving checkpoints for 1 into tmp/adversarial\model.ckpt.
INFO:tensorflow:Saving checkpoints for 1 into tmp/adversarial\model.ckpt.
```

**Comment by facaiy** [comment] 2017-12-15 01:44
Hi, @martinwicke @joel-shor , could you take a look ? I find we don't register argmax (and argmin) as `ops.NotDifferentiable` or `REGISTER_OP_NO_GRADIENT`, is it intentional? Thanks.

**Comment by tensorflowbutler** [comment] 2018-01-03 07:36
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by joel-shor** [comment] 2018-01-11 02:54
This seems to be fixed by the above PR.

**Comment by tocab** [comment] 2018-01-14 19:04
I have the same error with seq2seq Model using Tensorflow 1.5rc1. In TensorFlow 1.4, it works without errors.

**Comment by sleighsoft** [comment] 2018-01-14 20:28
Can you upload some console logs?

**Comment by tocab** [comment] 2018-01-14 21:22
This is the error code i receive when i run my code with tensorflow 1.5rc1:

~~~~ Traceback (most recent call last):
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 577, in gradients
    grad_fn = ops.get_gradient_function(op)
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\ops.py", line 2305, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\framework\registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: ArgMax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Pycharm Projects/YahooSemEval/yahoo_main.py", line 48, in <module>
    main()
  File "D:/Pycharm Projects/YahooSemEval/yahoo_main.py", line 44, in main
    mode=args.mode, attention=args.attention)
  File "D:\Pycharm Projects\YahooSemEval\model\pre_train_model.py", line 80, in __init__
    self.build_mle_modul(target_output, self.final_outputs.rnn_output)
  File "D:\Pycharm Projects\YahooSemEval\model\pre_train_model.py", line 284, in build_mle_modul
    self.mle_train_op = tf.train.AdamOptimizer().minimize(self.loss)
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\optimizer.py", line 355, in minimize
    grad_loss=grad_loss)
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\training\optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Users\Tobi\AppData\Local\conda\conda\envs\tensorflow1.5\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'train_decoder/decoder/while/BasicDecoderStep/TrainingHelperSample/ArgMax' (op type: ArgMax) ~~~~ 

With tensorflow 1.4, it runs correctly. My code has a similar structur as the code postet from sleighsoft.

**Comment by martinwicke** [comment] 2018-01-29 07:06
@av8ramit, It seems the innocent-looking 69c3245 has broken gradients for argmax in 1.5. Did this make it into final? If this is easy to trigger, we probably have to patch it. Not sure though given the timeline for 1.6.

**Comment by angersson** [comment] 2018-01-29 18:30
@martinwicke 69c324591ba4dfeafb403ee59de56ffe063c1e94 is present in 1.5.0 (Github shows it being a part of 1.5.0, as does `git co google/r1.5 && git log --grep 'Use argmax output_type'`)

**Comment by martinwicke** [comment] 2018-01-29 18:40
That probably means argmax gradients would fail in 1.5. Bummer. 

We need to fix this though. I'd love to understand why it fails, it looks like a bug in argmax itself, since using the dtype shouldn't break gradients. And we have to fix this soon, otherwise we'll have to patch 1.6.

**Comment by tensorflowbutler** [comment] 2018-02-20 19:31
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-07 13:12
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment] 2018-03-19 18:58
Ok what happened here is that ArgMax never had a gradient, but really should have a gradient of `None` registered (telling TF that it's not differentiable). 

Previously, the cast would swallow that error though, since it isn't differentiable, therefore TF never even looked for the inner (argmax) gradient. 

This should have been fixed in 18bab99ac33f31192d400aebcfb7670a121655bd.

**Closed by martinwicke** 2018-03-19 18:58 UTC

**Comment by facaiy** [comment] 2018-03-19 23:28
@martinwicke Thanks for fix. I think argmin is not differentiable as well.

**Comment by sleighsoft** [comment] 2018-03-24 11:37
So the revert change could be applied again?

**Comment by martinwicke** [comment] 2018-03-24 15:31
I believe so. At least we can try.
