### ISSUE TITLE
TF crashes when tensor size is increased

### ISSUE THREAD

**Issue by lermag** [tensorflow/tensorflow#26316] opened 2019-03-04 10:38 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): not sure 
- TensorFlow version (use command below): 1.12.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: release 9.0, V9.0.176/ 9.0
- GPU model and memory: GeForce RTX 2080 Ti 11GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I am running a custom code using TF. Part of the code includes a 2d convolution using tf.nn.conv2d. The code is running great, but when I increase the size of one of the tensors by a factor of 2 then everything crashes and I get this error:
2019󈚧󈚨 12:29:56.729188: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019󈚧󈚨 12:29:56.988944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:65:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019󈚧󈚨 12:29:56.995629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019󈚧󈚨 12:29:57.467089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019󈚧󈚨 12:29:57.467875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0 
2019󈚧󈚨 12:29:57.468098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N 
2019󈚧󈚨 12:29:57.468449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8665 MB memory) ‑> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2019󈚧󈚨 12:30:06.043926: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019󈚧󈚨 12:30:06.044411: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 000001F8E589DCD0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019󈚧󈚨 12:30:06.044888: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 000001F8E589DCD0: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019󈚧󈚨 12:30:06.045401: F tensorflow/stream_executor/cuda/cuda_dnn.cc:231] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.

The problem might not be connected to the convolution operation but it fails after I increase the size of this tensor. 
Can you help me solving this issue?
Thank you very much,
Gilad
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment] 2019-03-08 21:59
@lermag May be there is an issue with selection of some parameters. Could you provide a code to reproduce the bug? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-19 22:26
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-19 22:26 UTC
Labels: comp:gpu, stat:awaiting response, type:bug/performance

**Comment by wumeng2** [comment] 2019-04-25 11:20
Hello, do you solve it? I met the same error using RTX2070, thank you

**Comment by KimMeen** [comment] 2019-07-15 01:00
Same problem and could you post the solution to fix it? Thank you!!

**Comment by jvishnuvardhan** [comment] 2019-07-15 17:37
@KimMeen @wumeng2 Can you create a new issue with a standalone code and also fill issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A?
