### ISSUE TITLE
tf.linalg.expm is incompatible with vectorized_map

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#35579] opened 2020-01-04 13:36 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.2
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0-dev20191221
- Python version: 3.7

**Describe the current behavior**
Vectorizing `tf.linalg.expm` throws the error: `UnrecognizedFlagError: Unknown command line flag 'f'`

**Describe the expected behavior**
No error

**Code to reproduce the issue**
`tf.vectorized_map(lambda x: tf.linalg.expm(x), tf.reshape(tf.range(8.0),[2,2,2]))`

**Other info / logs**
This may not be related specifically to expm, as it occurs with [other functions](https://github.com/tensorflow/tensorflow/issues/34734) as well

**Comment by amahendrakar** [comment] 2020-01-06 11:41
Was able to reproduce the issue using tf-nightly 2.1.0.dev20200106. Please find the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/e695c0438fd9f99f07e13cbedd9a4cfc/35579.ipynb
) here. Thanks!

**Comment by yongtang** [comment] 2020-05-05 03:28
I tried the latest nightly and it looks like the issue has been resolved. Will close this issue for now but feel free to reopen if the issue persists.

**Closed by yongtang** 2020-05-05 03:28 UTC
Labels: TF 2.1, comp:ops, type:bug
