### ISSUE TITLE
Possible bug with map_fn in Graph mode during training, works fine with Eager execution

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#22094] opened 2018-09-05 14:32 UTC
Tensorflow 1.10 on Ubuntu 16.04

A simplified code example, see also stackoverflow: https://stackoverflow.com/questions/52187269/tensorflow-map-fn-does-not-work-in-graph-mode-during-training-in-eager-mode-it

This loss function works:
```
def discriminative_loss_working(y_true, y_pred):
    # Compute the loss for only the first image in the batch
    
    prediction = y_pred[0]
    label = y_true[0]

    # Number of clusters in ground truth
    clusters,_ = tf.unique(tf.reshape(label, [-1]))

    # Compute cluster means and variances for each cluster
    def compute_mean(c):
        mask = tf.equal(label[:,:,0], c)
        masked_pixels = tf.boolean_mask(prediction, mask)
        cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

        return cluster_mean

    cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
    return tf.reduce_mean(cluster_means)
```

However, when inserting an extra map_fn to work with batch sizes > 1 it doesnot work:
```
def discriminative_loss(y_true, y_pred):
    """Computes loss for a batch of images
    Args:
        y_true: (n, h, w) where each elements contains the ground truth instance id
        y_pred: (n, h, w, d) d-dimensional vector for each pixel for each image in the batch
    Returns:
        loss
    """
    # Compute the loss for each image in the batch
    def compute_loss(input):
        prediction = input[1]
        label = input[0]

        # Number of clusters in ground truth
        clusters,_ = tf.unique(tf.reshape(label, [-1]))

        # Compute cluster means and variances for each cluster
        def compute_mean(c):
            mask = tf.equal(label[:,:,0], c)
            masked_pixels = tf.boolean_mask(prediction, mask)
            cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

            return cluster_mean

        cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
        return tf.reduce_mean(cluster_means)
        
    # We want to know the loss for each image in the batch
    losses = tf.map_fn(compute_loss, (y_true,y_pred), dtype=(tf.float32))
    return losses
```

The error is:

> 018-09-05 16:07:24.740128: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at tensor_array_ops.cc:121 : Not found: Resource __per_step_6/_tensor_arraysloss/output_1_loss/map/while/map/TensorArray_1_3/N10tensorflow11TensorArrayE does not exist.
> Traceback (most recent call last):
>   File "instancesegmenter/test.py", line 90, in <module>
>     model.fit(train_dataset, epochs=5, steps_per_epoch=2)
>   File "/home/derk/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1363, in fit
>     validation_steps=validation_steps)
>   File "/home/derk/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 205, in fit_loop
>     outs = f(ins)
>   File "/home/derk/.local/lib/python3.5/site-packages/tensorflow/python/keras/backend.py", line 2914, in __call__
>     fetched = self._callable_fn(*array_vals)
>   File "/home/derk/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
>     run_metadata_ptr)
>   File "/home/derk/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Resource __per_step_6/_tensor_arraysloss/output_1_loss/map/while/map/TensorArray_1_3/N10tensorflow11TensorArrayE does not exist.
> 	 [[Node: training/SGD/gradients/loss/output_1_loss/map/while/map/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayGrad/TensorArrayGradV3 = TensorArrayGradV3[_class=["loc:@train...ad/truediv"], source="training/SGD/gradients", _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/SGD/gradients/loss/output_1_loss/map/while/map/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayGrad/TensorArrayGradV3/StackPopV2, training/SGD/gradients/loss/output_1_loss/map/while/map/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayGrad/TensorArrayGradV3/StackPopV2_1)]]
> 	 [[Node: training/SGD/gradients/loss/output_1_loss/map/while/map/while/Mean_grad/truediv/_161 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_608_t...ad/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_clooptraining/SGD/gradients/loss/output_1_loss/map/while/map/while/boolean_mask/Reshape/Enter_grad/Switch/_36)]]

Note that this works fine in Eager mode and also when only doing a forward pass. However the backward pass when in graph mode gives the error.

The full code example to reproduce the issue:

```
import tensorflow as tf
import numpy as np

def discriminative_loss(y_true, y_pred):
    """Computes loss for a batch of images
    Args:
        y_true: (n, h, w) where each elements contains the ground truth instance id
        y_pred: (n, h, w, d) d-dimensional vector for each pixel for each image in the batch
    Returns:
        loss
    """
    # Compute the loss for each image in the batch
    def compute_loss(input):
        prediction = input[1]
        label = input[0]

        # Number of clusters in ground truth
        clusters,_ = tf.unique(tf.reshape(label, [-1]))

        # Compute cluster means and variances for each cluster
        def compute_mean(c):
            mask = tf.equal(label[:,:,0], c)
            masked_pixels = tf.boolean_mask(prediction, mask)
            cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

            return cluster_mean

        cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
        return tf.reduce_mean(cluster_means)
        
    # We want to know the loss for each image in the batch
    losses = tf.map_fn(compute_loss, (y_true,y_pred), dtype=(tf.float32))
    return losses

def discriminative_loss_working(y_true, y_pred):
    # Compute the loss for only the first image in the batch
    
    prediction = y_pred[0]
    label = y_true[0]

    # Number of clusters in ground truth
    clusters,_ = tf.unique(tf.reshape(label, [-1]))

    # Compute cluster means and variances for each cluster
    def compute_mean(c):
        mask = tf.equal(label[:,:,0], c)
        masked_pixels = tf.boolean_mask(prediction, mask)
        cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

        return cluster_mean

    cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
    return tf.reduce_mean(cluster_means)

class MyModel(tf.keras.Model):
    def __init__(self, input_shape):
        super(MyModel, self).__init__()
        self.conv = tf.keras.layers.Conv2D(filters=4, kernel_size=(1,1))

    def call(self, input):
        return self.conv(input)

input_shape = (1,128,128,3)
def my_gen():
    while True:
        x = np.random.rand(1,input_shape[1], input_shape[2],3)
        y = np.random.randint(11000, 11015, (input_shape[1], input_shape[2],1))
        yield x,y

train_dataset = tf.data.Dataset.from_generator(my_gen, (tf.float32, tf.float32))
train_dataset = train_dataset.batch(1)
train_dataset = train_dataset.repeat()

model = MyModel(input_shape=input_shape)

# This is a fix to make loading weights possible
# x = tf.zeros((1,) + input_shape)
x = tf.zeros(input_shape)
y = model(x)

optimizer = tf.keras.optimizers.SGD(lr=0.0001)
model.compile(loss=discriminative_loss,optimizer=optimizer)
model.fit(train_dataset, epochs=5, steps_per_epoch=2)
```

**Comment by tensorflowbutler** [comment] 2018-09-06 01:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by drpngx** [comment] 2018-09-06 02:46
@skye wdyt?

**Comment by harshini-gadige** [comment] 2018-09-27 19:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-09-27 19:00 UTC
Labels: comp:eager, stat:awaiting response

**Comment by lengoanhcat** [comment] 2019-07-19 05:15
Please reopen the issue:

OS Platform and Distribution: Linux Ubuntu x86_64 - 4.15.0-52-generic (kernel)
TensorFlow installed from: conda 4.7.5
TensorFlow version: 1.13.1
Bazel version: N/A
CUDA/cuDNN version: 10.0
GPU model and memory: Tesla V100-SXM2-16GB
Exact command to reproduce: 
Mobile device: N/A

`
import tensorflow as tf
import numpy as np

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

def discriminative_loss(y_true, y_pred):
    """Computes loss for a batch of images
    Args:
        y_true: (n, h, w) where each elements contains the ground truth instance id
        y_pred: (n, h, w, d) d-dimensional vector for each pixel for each image in the batch
    Returns:
        loss
    """
    # Compute the loss for each image in the batch
    def compute_loss(input):
        prediction = input[1]
        label = input[0]

        # Number of clusters in ground truth
        clusters,_ = tf.unique(tf.reshape(label, [-1]))

        # Compute cluster means and variances for each cluster
        def compute_mean(c):
            mask = tf.equal(label[:,:,0], c)
            masked_pixels = tf.boolean_mask(prediction, mask)
            cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

            return cluster_mean

        cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
        return tf.reduce_mean(cluster_means)

    # We want to know the loss for each image in the batch
    losses = tf.map_fn(compute_loss, (y_true,y_pred), dtype=(tf.float32))
    return losses

def discriminative_loss_working(y_true, y_pred):
    # Compute the loss for only the first image in the batch

    prediction = y_pred[0]
    label = y_true[0]

    # Number of clusters in ground truth
    clusters,_ = tf.unique(tf.reshape(label, [-1]))

    # Compute cluster means and variances for each cluster
    def compute_mean(c):
        mask = tf.equal(label[:,:,0], c)
        masked_pixels = tf.boolean_mask(prediction, mask)
        cluster_mean = tf.reduce_mean(masked_pixels, axis=0)

        return cluster_mean

    cluster_means = tf.map_fn(compute_mean, clusters, dtype=(tf.float32))
    return tf.reduce_mean(cluster_means)

class MyModel(tf.keras.Model):
    def __init__(self, input_shape):
        super(MyModel, self).__init__()
        self.conv = tf.keras.layers.Conv2D(filters=4, kernel_size=(1,1))

    def call(self, input):
        return self.conv(input)

input_shape = (1,128,128,3)
def my_gen():
    while True:
        x = np.random.rand(1,input_shape[1], input_shape[2],3)
        y = np.random.randint(11000, 11015, (input_shape[1], input_shape[2],1))
        yield x,y

train_dataset = tf.data.Dataset.from_generator(
                    my_gen,
                    (tf.float32, tf.float32),
                    (tf.TensorShape([1,128,128,3]),
                     tf.TensorShape([128,128,1])))
train_dataset = train_dataset.batch(1)
train_dataset = train_dataset.repeat()

model = MyModel(input_shape=input_shape)

# This is a fix to make loading weights possible
# x = tf.zeros((1,) + input_shape)
x = tf.zeros(input_shape)
y = model(x)

with tf.Session(config=config):
    optimizer = tf.keras.optimizers.SGD(lr=0.0001)
    model.compile(loss=discriminative_loss,optimizer=optimizer)
    model.fit(train_dataset, epochs=5, steps_per_epoch=2)
`
