### ISSUE TITLE
XLA/AOT on Windows build?

### ISSUE THREAD

**Issue by neale** [tensorflow/tensorflow#8310] opened 2017-03-11 20:04 UTC
I know windows is low on the priority list (I don't blame you), but will there be support in the future for AOT compilation for Windows, or is it possible now in theory?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
There aren't a lot of questions anywhere about this yet :/

### Environment info
Operating System:
Windows 10

### Installed version of CUDA and cuDNN: 
None

### Installation 
I installed from cmake using the tutorial here and it worked fine, the stock mnist example ran and I couldn't find a fault with the installation. 

I also tried building with the windows Bazel build. I didn't have much success with this (lots of errors on configure) but if I know it can work than I can put for effort here. 

### What other attempted solutions have you tried?
I attemped the JIT example [here](https://www.tensorflow.org/versions/master/experimental/xla/jit) but I got the same output using XLA and not using XLA. Checking chrome://tracing revealed no XLA startup. This is where I assumed that the cmake build does not include tensorflow/compiler/xla, indeed I found no corresponding MSVC build files. 

Attempting to build AOT binaries with bazel didn't work because configure had not been run. I know you can build these binaries with alternate build systems (in the works?) but there's no docs on how to do that. 

I just want to know if I should even bother trying while this part of the project is so young. I should add that the JIT works very well for me on ubuntu, in places where it should work. 

If I can compile tf_library and get the tfcompile tool then I would appreciate some pointers on how to get there. I don't know how productive it is to spend time decoding bazel build files and try to construct my own alternate build the replicates it.

### Logs or other output that would be helpful
Log of JIT example output
```
$ TF_XLA_FLAGS=--xla_generate_hlo_graph=.* python mnist_softmax_xla.py
Extracting /tmp/tensorflow/mnist/input_data\train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data\t10k-labels-idx1-ubyte.gz
0.9179
```
`bazel ./configure` output
```
$ ./configure
Please specify the location of python. [Default is /c/Users//AppData/Local/Programs/Python/Python35/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] y
XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  C:\Users\\AppData\Local\Programs\Python\Python35
  C:\Users\\AppData\Local\Programs\Python\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\\AppData\Local\Programs\Python\Python35]

Using python library path: C:\Users\\AppData\Local\Programs\Python\Python35
Junction created for util\python\python_include <<===>> C:\Users\\AppData\Local\Programs\Python\Python35\include
Junction created for util\python\python_lib <<===>> C:\Users\\AppData\Local\Programs\Python\Python35
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Users\\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with CUDA support? [y/N] N
No CUDA support will be enabled for TensorFlow
Configuration finished
Warning: ignoring _JAVA_OPTIONS in environment.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:6:6: invalid character: '!'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:6:14: invalid character: '?'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:23:4: invalid character: '@'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:23:41: invalid character: '@'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:24:4: invalid character: '@'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:34:2: indentation error.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:38:6: invalid character: '!'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:38:18: invalid character: '?'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:44:2: indentation error.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:68:57: invalid character: '&'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:68:58: invalid character: '&'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:87:2: indentation error.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:92:39: invalid character: '?'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:95:44: invalid character: '?'.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:3:2: indentation error.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:7:4: indentation error.
ERROR: C:/Users//Documents/tensorflow/tensorflow/contrib/cmake/build/plottable/src/plottable/bower_components/sinon/BUILD:16:2: indentation error.
```

**Comment by prb12** [comment] 2017-03-11 20:23
@tatatodd Do you know what the status is of tf_compile on Windows?

@neale Thanks for following the issue reporting template ... I agree that the output (especially from bazel configuration) is sort of irrelevant and unrelated.

**Comment by tatatodd** [comment] 2017-03-13 16:40
@neale I don't believe anyone has tried to get `tfcompile` / `tf_library` to work on Windows.

Honestly I'm not even sure what the right approach should be; on linux we rely on the `tf_library` bazel macro to kick off `tfcompile` binary, but I'm not sure whether this will fly on Windows.  In the worst case, as long as we can get the `tfcompile` binary built, the user can invoke it themselves.  I'll self-assign and follow-up to figure out how to best do this.

**Comment by neale** [comment] 2017-03-13 17:17
Thanks!

**Comment by leandro-gracia-gil** [comment] 2017-04-17 08:35
One question. If you manage to build a native Windows version of tfcompile with bazel, would generated static libraries be compatible with MSVC? If not, is there any way to generate C/C++ source code rather than static libraries so they can built and linked across platforms and compilers?

Thanks!

**Comment by tatatodd** [comment] 2017-04-17 16:34
@leandro-gracia-gil 

Yes, if we add tfcompile support for Windows, the generated libraries would be compatible with MSVC.  Note that the only ABI requirement for the generated computation is a single C (not C++) function, which is definitely supported.  We also generate a C++ header to make it easier to call the C function, which performs some buffer management, and would just be compiled by MSVC as usual.

**Comment by neale** [comment] 2017-04-21 22:24
That would streamline so much of my development process. Deep learning on windows platforms is definitely hamstringed right now. Its more of a hack then a science.

**Comment by leandro-gracia-gil** [comment] 2017-04-26 03:53
I have managed to successfully use tfcompile to run a Tensorflow graph in MSVC. The key seems to be using the target triple "x86_64-pc-windows-msvc" from a Linux build of tfcompile to generate a .h/.lib pair. You also need to build tensorflow/compiler/aot/runtime.cc with MSVC (it needs a couple minor fixes) and link it together with everything else. Also, one more trivial fix is required in the generated headers.

Is it ok if I send a patch addressing these minor issues? If there are any instructions about sending patches that would be very helpful.

**Comment by tatatodd** [comment] 2017-04-26 04:02
@leandro-gracia-gil Yes, patches are definitely welcome!

Some info on legal stuff here:
https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

Other than that, just send the patch like a regular github pull request (PR).  Some github links on this topic:
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

Thanks!

**Comment by pawarrick** [comment] 2017-05-08 14:57
@leandro-gracia-gil do you plan to add the patch soon? It would be very helpful.  And thanks for reporting the solution.

**Comment by leandro-gracia-gil** [comment] 2017-05-08 15:59
@pawarrick I've found that depending on what you do you (your graph operations) you might actually need to build more than just the aot runtime.cc in MSVC. That leads to changes in a few more Tensorflow files, and transitively to one more trivial change in the Eigen library.

I'm currently trying to figure out a cleaner approach considering the required changes, which are small but scattered across various files. The core issue is that with the generated static library alone there are linker errors because of missing symbols (generally the memory management functions of the runtime and some XLA/JIT CPU kernel ops). This gets solved by building more and more bits of Tensorflow using MSVC, but it also makes the snowball of MSVC fixes bigger and bigger without knowing if your next graph will be missing something else.

It would be great if we could somehow include them in the generated static library itself, or perhaps have a separate static library for MSVC containing all the symbols the first one might need regardless of the graph we use.

Any suggestions on good ways to approach the problem are most welcome.

**Comment by leandro-gracia-gil** [comment] 2017-05-08 16:21
By the way, I've also noticed that there are a lot of kernels not implemented for the DEVICE_CPU_XLA_JIT device, which limits a lot what you can actually do with the AoT compiler. This seems to include multiple control flow operations (enter, whileloop and others if I remember correctly), some ops like argmin (although there's argmax), gather and scatter, some array ops and also any kernels for any quantized data types.

I've also noticed some ops implemented for DEVICE_XLA_CPU in the source, but apparently not registered for DEVICE_CPU_XLA_JIT. I wonder if this might be just a problem of incorrectly not registering some kernels? If not, are there there any plans about implementing these kernels for the AoT compiler?

If I wanted to try implementing some of these myself, is there something I should keep in mind? I've noticed that there is a parallel XlaOpKernel class but I ignore what are the main differences with the regular op kernels.

Thanks.

**Comment by leandro-gracia-gil** [comment] 2017-05-09 07:09
After looking into further detail I've crafted the list of the source files that might need to be built and linked with MSVC in order to use static libraries generated with tfcompile. Unless I'm missing something this list should be exhaustive at the moment of writing this.

Required by generated headers:
- compiler/aot/runtime.cc  (For tfcompile::runtime::MallocContiguousBuffers and FreeContiguous)
- compiler/xla/executable_run_options.cc  (For the implementation of xla::ExecutableRunOptions)

Required to provide XLA custom ops:
- compiler/tf2xla/kernels/gather_op_kernel_float_int32.cc  (for gather_float_int32_xla_impl)
- compiler/tf2xla/kernels/gather_op_kernel_float_int64.cc  (for gather_float_int64_xla_impl)
- compiler/tf2xla/kernels/index_ops_kernel_argmax_float_1d.cc  (argmax_float_1d_xla_impl)
- compiler/tf2xla/kernels/index_ops_kernel_argmax_float_2d.cc  (argmax_float_2d_xla_impl)

Required by SimpleResolver in compiler/xla/service/cpu/simple_orc_jit.cc:
- compiler/xla/service/cpu/runtime_matmul.cc  (for __xla_cpu_runtime_EigenMatMulF32)
- compiler/xla/service/cpu/runtime_single_threaded_matmul.cc  (for __xla_cpu_runtime_EigenSingleThreadedMatMulF32)
- compiler/xla/service/cpu/runtime_conv2d.cc  (for __xla_cpu_runtime_EigenConvF32)
- compiler/xla/service/cpu/runtime_single_threaded_conv2d.cc  (for __xla_cpu_runtime_EigenSingleThreadedConvF32)
- compiler/xla/service/cpu/cpu_runtime.cc  (for __xla_cpu_runtime_AcquireInfeedBufferForDequeue and __xla_cpu_runtime_ReleaseInfeedBufferAfterDequeue)
- compiler/xla/service/cpu/cpu_runtime_sse4_1.cc  (for runtime::ExpV4F32, runtime::LogV4F32 and runtime::TanhV4F32)
- compiler/xla/service/cpu/cpu_runtime_avx.cc  (for runtime::ExpV8F32, runtime::LogV8F32 and runtime::TanhV8F32)

I can also confirm that no changes in Eigen seem to be needed at the end.

The exact set of sources needed from that list depends on what the static library does and how the generated headers are used. I can confirm that I was able to successfully build all these source files in MSVC with the exception of:
- compiler/xla/service/cpu/cpu_runtime_sse4_1.cc
- compiler/xla/service/cpu/cpu_runtime_avx.cc

Which means no SSE4.1 and AVX support for the exp, log and tanh functions. The reason for these is the lack of good alternatives to __attribute__((__vector_size__(32))) and __attribute__((weak)) in MSVC, particularly the former. All other files can build with minor fixes that should not affect other platforms.

I can try preparing a pull request with the fixes that make the other sources compatible with MSVC, although we probably need some way to make sure they *keep* being compatible. Not having to gather all these by hand would be great too, but I'm not sure how that might be doable.

Any feedback or suggestions are most welcome.

**Comment by leandro-gracia-gil** [comment] 2017-05-17 03:37
Thanks for merging the fix! Here are detailed instructions on how to build and run a static library generated by tfcompile in MSVC.

1. In a Linux machine (tfcompile doesn't work on Windows yet) checkout tensorflow and build tfcompile. You will need to [install Bazel](https://bazel.build/versions/master/docs/install.html) if you haven't done so already.
> git clone https://github.com/tensorflow/tensorflow.git
> cd tensorflow
> bazel build -c opt //tensorflow/compiler/aot:tfcompile

2. Run tfcompile to generate the static library for your graph and config.
> bazel-bin/tensorflow/compiler/aot/tfcompile --target_triple="**x86_64-pc-windows-msvc**" --graph="_your_graph.pb_" --config="_your_graph_config.pbtxt_" --entry_point="_your_C_entry_point_name_" --cpp_class="_YourNamespace::YourCppClass_" --out_object="output.lib" --out_header="output.h"

You might want to add some other arguments to tfcompile, like for example:
> --xla_cpu_llvm_opt_level=3 --target_features="+avx,+avx2,+sse4.2"

3. Copy your generated .lib and .h files to the Windows machine where you run MSVC.

4. In the MSVC solution you want to use the static library, create a new empty Win32 Static Library project.

5. Checkout the Tensorflow source again in Windows (e.g., your_project\third_party\tensorflow)

6. Open tensorflow\workspace.bzl in your tensorflow checkout and look for "eigen_archive". Download one of the URLs there and extract the contents into a folder (e.g., your_project\third_party\eigen).

7. Open tensorflow\contrib\cmake\CMakeLists.txt in your tensorflow checkout and look for "add_definitions". Take a look to the preprocessor macros defined there (starting with -D) and add them manually in MSVC to your Tensorflow project properties -> C/C++ -> Preprocessor. You will need to define at least NOMINMAX, COMPILER_MSVC and TF_COMPILE_LIBRARY. Similarly, you might want to add some other compiler options from CMakeLists.txt into C/C++ -> Command Line -> Additional Options. None of these should be a strong requirement AFAIK.

8. In your Tensorflow project properties -> C/C++ -> General -> Additional Include Directories add the following entries in this order:
- If needed, the path where your generated .h file is.
- The path where you extracted eigen (e.g., your_project\third_party\eigen).
- The path where you extracted tensorflow (e.g., your_project\third_party\tensorflow).

9. In your Tensorflow project properties -> Librarian, add your generated .lib to Additional Dependencies, and the path to it in Additional Library Directories.

10. Manually add the following files to the "Source Files" section of your Tensorflow project:
- tensorflow/compiler/aot/runtime.cc
- tensorflow/compiler/xla/executable_run_options.cc
- tensorflow/compiler/tf2xla/kernels/gather_op_kernel_float_int32.cc
- tensorflow/compiler/tf2xla/kernels/gather_op_kernel_float_int64.cc
- tensorflow/compiler/tf2xla/kernels/index_ops_kernel_argmax_float_1d.cc
- tensorflow/compiler/tf2xla/kernels/index_ops_kernel_argmax_float_2d.cc
- tensorflow/compiler/xla/service/cpu/runtime_matmul.cc
- tensorflow/compiler/xla/service/cpu/runtime_single_threaded_matmul.cc
- tensorflow/compiler/xla/service/cpu/runtime_conv2d.cc
- tensorflow/compiler/xla/service/cpu/runtime_single_threaded_conv2d.cc
- tensorflow/compiler/xla/service/cpu/cpu_runtime.cc

11. Set your project dependencies in your solution so that the projects you want to use the static library in depend on your Tensorflow project. (Right-click in your project -> Build Dependencies -> Project dependencies).

12. You're ready to use the generated static library in your code. Here's an example snippet:
```
#define EIGEN_USE_THREADS
#define EIGEN_USE_CUSTOM_THREAD_POOL

#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"  // From your Tensorflow checkout.
#include "your_generated_header.h"

eigen::ThreadPool thread_pool(2);  // Number of threads in your pool. Set as you want.
eigen::ThreadPoolDevice thread_pool_device(&thread_pool, thread_pool.NumThreads());
YourNamespace::YourCppClass helper_object;

helper_object.set_thread_pool(&thread_pool_device);
helper_object.set_arg0_data(your_arg_data);
helper_object.Run();
auto your_result = helper_object.result0();
```

Keep in mind that if you enable vector instructions (by passing args like +sse4.2, +avx or +avx2 to target_features when running tfcompile) you should ensure that any pointers passed to set_arg*_data(...) have the appropriate memory alignment. Otherwise you are likely to experience crashes when calling Run().

Enjoy!

**Comment by gunan** [comment] 2017-06-16 22:26
Looks like this issue was resolved.
Closing issue.

**Closed by gunan** 2017-06-16 22:26 UTC
