### ISSUE TITLE
Setup.py on CentOS7 pywrap_tensorflow_internal Error

### ISSUE THREAD

**Issue by frankiecancino** [tensorflow/tensorflow#14948] opened 2017-11-28 16:53 UTC
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux CentOS7
TensorFlow installed from (source or binary):
Setup.py
TensorFlow version (use command below):
1.3
Python version:
2.7
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
4.8.5
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:
import tensorflow as tf
You can collect some of this information using our environment capture script:
https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

tf_env_collect.sh output:

== cat /etc/issue ===============================================
Linux rs-control1 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux rs-control1 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/init.py", line 24, in 
from tensorflow.python import *
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/init.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in 
from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

Describe the problem

Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Installing using setup.py works until trying to import tensorflow, causing an Import Error for pywrap_tensorflow_internal

Dependencies I believe are met and using setup.py because I'm building this into an rpm to deploy to different nodes and clusters.

Source code / logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Simply running setup.py and then import tensorflow as tf produces Import Error:
Traceback (most recent call last):
File "/tmp/check_tf.py", line 1, in 
import tensorflow as tf;
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/init.py", line 24, in 
from tensorflow.python import *
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/init.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/usr/local/python-tgt-201701/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in 
from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal

**Comment by aselle** [comment] 2017-11-28 18:17
Sorry, what version did you install. Did you use pip? I don't know exactly what you mean by installing with setup.py. This doesn't match our usual install instructions.

**Comment by frankiecancino** [comment] 2017-11-28 18:21
I installed TF version 1.3 with Python 2.7. Usually just running python on the setup.py file will install any python package, but for some reason running it on Tensorflow's will install it but it won't create the pywrap_internal_tensorflow file. As far as I've noticed this is the only file missing and causes an error when trying to do anything with TF.

**Comment by aselle** [comment] 2017-11-29 17:02
I'm still confused. Where did you get a setup.py? From the source code? If you download from the web site you get a .whl  which can be installed with pip. If you install from source you sually run build_pip_package which again gives you a .whl. Can you give me the exact steps to reproduce. Did you uncompress the whl with unzip or something?

**Comment by frankiecancino** [comment] 2017-11-29 17:27
Yes, I got the setup.py file from the source code. Specifically: /tensorflow/tools/pip_package/setup.py
And unfortunately the environments I'm deploying Tensorflow to are cut off from the internet due to a firewall so building it through an rpm for linux was the route I'm going. Being able to run "python setup.py" should install Tensorflow and it does except for one file, causing it to break once trying to import tensorflow in the python shell. Since it produces an import error on "import tensorflow as tf" it means it was able to install by just using Tensorflow's setup.py file. I've attempted to install by compiling from sources and using the .whl file, but neither seemed to work as well as just using setup.py.

**Comment by aselle** [comment] 2017-11-29 23:22
Well pywrap_tensorflow_internal is the entire c++ backend of TensorFlow. I.e. it's not just one file, it's the backend that runs everything. Cou'll at the very least need to run build_pip_package as
bazel run tensorflow/tools/pip_package:build_pip_package 
Before you do that edit the build_pip_package command to output to a specific directory  (i.e. replace
```
  TMPDIR=$(mktemp -d -t tmp.XXXXXXXXXX)
```
with some specific directory. Then you should have a directory with a working setup.py. Maybe this is what you are doing. But at least from there you can look if the pywrap_tensorflow_internal. However, this installation path is not officially supported, so I really have no way to test any of this on CentOS7.

**Comment by frankiecancino** [comment] 2017-12-07 19:55
I'm also getting the same error with a pip install of the tf_nightly.whl on a similar, but separate environment (CentOS7). With error 'Failed to load the native TensorFlow runtime.'

**Comment by ymodak** [comment] 2018-10-24 21:09
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again.
Feel free to report any issues you encounter with latest TensorFlow. Thanks!

**Closed by ymodak** 2018-10-24 21:09 UTC
Labels: stat:community support, type:build/install
