### ISSUE TITLE
I understand that java should be faster than Python. But not like this.

### ISSUE THREAD

**Issue by whaozl** [tensorflow/tensorflow#27999] opened 2019-04-20 05:11 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
```java
//create session, this pb come from python
        ConfigProto config=ConfigProto.newBuilder()
                .setAllowSoftPlacement(true)
                .setLogDevicePlacement(false)
                .clearLogDevicePlacement()
                //.setGpuOptions(GPUOptions.newBuilder().setAllowGrowth(true))
                //.setInterOpParallelismThreads(1)
                .build();
        sess=new Session( graph, config.toByteArray() );
```
```java
        AnjosLog log=new AnjosLog();
        log.begin();
        log.begin2Series("create data");
        float[][][] X=new float[1][this.audio_len][this.audio_feat_len];
        X[0]=data;
        log.stop2Series();
        log.begin2Series("create tensor");
        Tensor x= Tensor.create(X);
        log.stop2Series();
        log.begin2Series("use model");
        Tensor  y = sess.runner().feed(input_var, x).fetch(label_var).run().get(0);
        log.stop2Series();
        log.begin2Series("take result");
        float[][][] result = new float[ (int)y.shape()[0] ][ (int)y.shape()[1] ][ (int)y.shape()[2] ];
        y.copyTo(result);
        log.stop2Series();
        log.stop();
```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win7 CPU
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):1.8.0 java
- Python version: 3.5.6
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: none
- GPU model and memory: none

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I use python3.5 predict the same one sample speed:
```
series start　　　　　　　　　　　　　　　　 2019-04-20 13:06:18
series end　　　　　　　　　　　　　　　　 2019-04-20 13:06:18
total time　　　　　　　　　　　　　　　　 0.24s       0.00min      2019-04-20 13:06:18
````
I use java1.8 predict the same one sample speed:
```
start time　　　　　　　　　　　　　　　　2019-04-20 12:57:43 924
 series start　　　　　　　　　　　　　　　　 create data 2019-04-20 12:57:43 925
 series end　　　　　　　　　　　　　　　　         0.00s         0.00min
 series start　　　　　　　　　　　　　　　　 create tensor 2019-04-20 12:57:43 927
 series end　　　　　　　　　　　　　　　　         0.09s         0.00min
 series start　　　　　　　　　　　　　　　　 use model 2019-04-20 12:57:44 015
  series end　　　　　　　　　　　　　　　　         0.69s         0.01min
 series start　　　　　　　　　　　　　　　　 take result 2019-04-20 12:57:44 710
  series end　　　　　　　　　　　　　　　　         0.03s         0.00min
 end time　　　　　　　　　　　　　　　　 2019-04-20 12:57:44 738
 total time　　　　　　　　　　　　　　　　         0.81s         0.01min
```

**Describe the expected behavior**
**I understand that java should be faster than Python. But not like this.**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mengpengfei** [comment] 2019-04-22 05:52
i meet the same problem,have you solve it ?

**Comment by muddham** [comment] 2019-04-22 13:46
@whaozl Can you please provide the complete python snippet code to reproduce the issue

**Comment by mengpengfei** [comment] 2019-04-24 04:42
the python source code is ：
https://github.com/kerlomz/captcha_platform/blob/master/predict.py

**Comment by mengpengfei** [comment] 2019-04-24 04:45
the java source code is the example file : LabelImage

**Comment by jvishnuvardhan** [comment] 2019-04-24 18:20
@mengpengfei Could you upgrade to latest version of TF 2.0 and 1.13.1 and check whether the performance issues persists there? Thanks!

**Comment by whaozl** [comment] 2019-04-25 06:03
this tf1.13.1 need what keras version?

**Comment by mengpengfei** [comment] 2019-04-25 06:29
i have tried on the version 1.13.1,but it the same as 1.12.0：
the java code spend 300+ms，
source code：
List<Tensor<?>> tesnsors=s.runner().feed("input", image).fetch("dense_decoded").run(); 

but the python api with the same model  only spend 70+ms

**Comment by mengpengfei** [comment] 2019-04-25 06:53
even if i have use the newest java api  version, it very slowly

**Comment by mengpengfei** [comment] 2019-04-30 08:57
java api call tensorflow function with jni，but why it is so slowly than c++ or python  api

**Comment by karllessard** [comment] 2019-05-10 03:31
Hi everyone, 

Often, what slows down the Java API is the reflection operations that occurs when creating the tensors using multidimensional arrays (see [this related issue](https://github.com/tensorflow/tensorflow/issues/8244)). Serializing those arrays directly into a `FloatBuffer` and passing it through [this constructor](https://github.com/tensorflow/tensorflow/blob/c23fd17c3781b21bd3309faa13fad58472c78e93/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L185) should help in this case.

Also I have noticed that the first inference on a given graph session is way slower than the next ones (seems related to some caching operations that occur in the native library). So I don't know if you are already doing it but keeping the same `Session` instance opened for all predictions seems a good solution right now.

FYI, there is a SIG (Special interest group) for JVM support of TensorFlow into which we are currently discussing those performances issues, particularly the first one, where we are planning to develop a set of utilities to simplify read/write operations on tensor data buffers and improve their performances. If you are interested by the topic, I suggest that you join the group by registering to the [jvm@tensorflow.org](https://groups.google.com/a/tensorflow.org/forum/#!forum/jvm) mailing list.

Please keep me posted if after those changes you are still facing very slow performances, thanks!

**Comment by abhinavos7a** [comment] 2019-05-16 01:33
@mengpengfei 

Did it resolve for you. I faced similar issue where I have a simple Linear model with feature hashing and exported it using SavedModel.

When I run the inference in python it's around 0.5 msec but Java API is 50msec. Python seems to be 100 time faster.

I made sure that I didn't include first 100 inferences for both of them and my bottleneck is not creation of tensors in Java (Takes around 30 micro seconds)

**Comment by mengpengfei** [comment] 2019-05-16 02:27
it is not sloved  now,  i use jna to call c++ api

**Comment by abhinavos7a** [comment] 2019-05-18 16:56
My bad about my comment about latencies. There was a bug in my python code.  The latencies in both python and java are comparable.

Both are around 90 msec. 
The same https://github.com/VowpalWabbit/vowpal_wabbit (linear model with feature hashing) seems to be 500 times faster than tensorflow. On average it was taking 0.1 msec. 

Any insight as to why such a big difference will be helpful

**Comment by dreistheman** [comment] 2019-05-19 05:20
@mengpengfei by using jni to call c++ api, you've obtained a faster execution?

**Comment by mengpengfei** [comment] 2019-05-19 05:33
yes  i use c++ to predict  and i make a dll which contains the predict function ,,,and i use jna to call the dll

**Comment by karllessard** [comment] 2019-05-19 13:51
@mengpengfei , if you are interested in calling the TF C++ core classes directly from Java, I suggest you take a look at [TF JavaCPP bindings](https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow).

**Comment by karllessard** [comment] 2019-05-19 14:00
Now it would be interesting if you can share some comparable metrics between this approach and when using the Java client instead. When it comes to inference, performance should be pretty much comparable (like @abhinavos7a observed) as pretty much all the processing is done in the C++ core library in both cases.

Where Java could win is more in the overall performance of your service/application, or in training (I never benchmark it though), as Java code is generally executed faster than Python.

**Comment by dreistheman** [comment] 2019-05-22 06:32
@mengpengfei So you do the inference in c++ and retrieve the results (bbox data) in Java, then proceed with further processing? Can you share how to do it :( 

@karllessard I tried what you recommended that is using the same Session instance for all predictions and it improved the performance a little bit to 9 fps now (with GPU help : GTX 1070), which is still incredibly slow from the real-time goal.

**Comment by karllessard** [comment] 2019-05-22 13:17
@dreistheman I just ran a little test on my side too and like @abhinavos7a , I observe that the inference time (including the creation of initial tensors the way I suggested) is pretty much the same in both cases:

10000 iterations, CPU-only:
* Java: 32455117 msecs
* Python: 36309922 msecs

I'm very curious to see what causes this latency in your case, do you have a piece of code to share?

**Comment by dreistheman** [comment] 2019-05-24 08:49
I used as guide this repository for YOLO Tensorflow in Java: https://github.com/szaza/tensorflow-example-java. 

This is the class directly responsible for box predictions on the video image frame. I've placed corresponding comments for ease of understanding. I've done my observations and the **Session execution** inside `executeYoloGraph()` method, which itself is inside `detect()`, is the one causing the bottleneck on the performance.


```
/**
 * ObjectDetector class to detect objects using pre-trained models with TensorFlow Java API.
 */
public class ObjectDetector {
    
    private final static Logger LOGGER = LoggerFactory.getLogger(ObjectDetector.class);

    //global graph and session variables for reuse
    private byte[] GRAPH_DEF;
    private List<String> LABELS;
    Graph yoloGraph;
    Session yoloSession;
    
    public ObjectDetector() {
        //instantiate the global variables for use on all image frames.
        try {

            GRAPH_DEF = IOUtil.readAllBytesOrExit(GRAPH_FILE);
            LABELS = IOUtil.readAllLinesOrExit(LABEL_FILE);
            yoloGraph = new Graph();
            yoloGraph.importGraphDef(GRAPH_DEF); //import the graph .pb file just once 
            yoloSession = new Session(yoloGraph);
            
        } catch (ServiceException ex) {
            LOGGER.error("Download one of my graph file to run the program! \n" +
                    "You can find my graphs here: https://drive.google.com/open?id=1GfS1Yle7Xari1tRUEi2EDYedFteAOaoN");
        }

    }

    /**
     * Detect objects on the given image
     * @param Mat the image from VideoCapture
     */
     //I just use instance.detect() in my video iteration code (using OpenCV)
    public List<Recognition> detect(Mat image){
        
        MatOfByte matByte = new MatOfByte();
        Imgcodecs.imencode(".png", image, matByte); 
        byte[] imByteArray = matByte.toArray();
        
        try (Tensor<Float> normalizedImage = normalizeImage(imByteArray)) {
        //I'll provide below the link to the YOLOClassifier class from the reference repository as I've not changed it except for the anchors[] global variable
            List<Recognition> recognitions = YOLOClassifier.getInstance().classifyImage(executeYOLOGraph(normalizedImage), LABELS);
            printToConsole(recognitions);
            return recognitions;
        }
        
    }
    

    /**
     * Pre-process input. It resize the image and normalize its pixels
     * @param imageBytes Input image
     * @return Tensor<Float> with shape [1][416][416][3]
     */
    //tried observing how quick this method executes and it was ordinarily instantaneous
    private Tensor<Float> normalizeImage(final byte[] imageBytes) {
        try (Graph graph = new Graph()) {
            GraphBuilder graphBuilder = new GraphBuilder(graph);

            final Output<Float> output =
                graphBuilder.div( // Divide each pixels with the MEAN
                    graphBuilder.resizeBilinear( // Resize using bilinear interpolation
                            graphBuilder.expandDims( // Increase the output tensors dimension
                                    graphBuilder.cast( // Cast the output to Float
                                            graphBuilder.decodeJpeg(
                                                    graphBuilder.constant("input", imageBytes), 3),
                                            Float.class),
                                    graphBuilder.constant("make_batch", 0)),
                            graphBuilder.constant("size", new int[]{SIZE, SIZE})),
                    graphBuilder.constant("scale", MEAN));

            try (Session session = new Session(graph)) {
                return session.runner().fetch(output.op().name()).run().get(0).expect(Float.class);
            }
        }
    }

    /**
     * Executes graph on the given preprocessed image
     * @param image preprocessed image
     * @return output tensor returned by tensorFlow
     */

    private float[] executeYOLOGraph(final Tensor<Float> image) {

        //This is the one that takes too long to finish.
        //I'm using the global graph and session variables up top so they are not created 
        //in every iteration. It's now simplified to just the execution of the session.

        Tensor<Float> result = yoloSession.runner().feed("input", image).fetch("output").run().get(0).expect(Float.class);
        float[] outputTensor = new float[YOLOClassifier.getInstance().getOutputSizeByShape(result)];
        FloatBuffer floatBuffer = FloatBuffer.wrap(outputTensor);
        result.writeTo(floatBuffer);
        return outputTensor;
          
    }

    /**
     * Prints out the recognize objects and its confidence
     * @param recognitions list of recognitions
     */
    private void printToConsole(final List<Recognition> recognitions) {
        for (Recognition recognition : recognitions) {
            LOGGER.info("Object: {} - confidence: {}", recognition.getTitle(), recognition.getConfidence());
        }
    }
}
```
I just call the `detect()` method on my main class passing in the `Mat` image frame read by OpenCV's `VideoCapture` class. The `YoloClassifier` class used by this method that just sorts the output from the Graph execution: https://github.com/szaza/tensorflow-example-java/blob/master/src/main/java/edu/ml/tensorflow/classifier/YOLOClassifier.java. 

I'm comparing this with Darkflow's `TFNet.camera()` function that runs the predictions in 37 fps on the same video input I use on my Java Application. (`TFNet `class -> https://github.com/thtrieu/darkflow/blob/master/darkflow/net/help.py)

**Comment by saudet** [comment] 2019-05-24 09:04
@dreistheman You're going to get much better performance without copying your data multiple times:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by karllessard** [comment] 2019-05-24 13:54
Thanks @dreistheman , just quickly like that I've also noticed that you don't free up the tensor returned by `yoloSession.runner()`, I don't know how you are running your benchmark loops but you might face memory issues if you don't release it like (just declaring it as a `try` resource will do the job).

In addition, sorry if this is out-of-topic as it is not related to performances, but since TF 1.10 you don't need those custom `graphBuilder` anymore if that can simplify your life, you can simply use the `Ops` API available in the Java client to build your preprocessing graph, see [this doc](https://www.javadoc.io/doc/org.tensorflow/libtensorflow/1.13.1). For example:
```
Ops tf = Ops.create(graph);
Placeholder<UInt8> image = tf.withName(GRAPH_INPUT).placeholder(UInt8.class);
Operand<Float> normalizedImage = tf.div(
        tf.resizeBilinear(
                tf.expandDims(image, tf.constant(0)),
                tf.constant(new int[] {SIZE, SIZE}
        ),
        tf.constant(MEAN)
);
// `imageBytes` is a tensor containing bytes of an image already decoded but we could have use `tf.decodeJpeg()` as well
return session.runner().feed(image, imageBytes).fetch(normalizedImage).run().get(0).expect(Float.class);
```

**Comment by dreistheman** [comment] 2019-05-26 03:44
@karllessard I've now put the output tensor inside a try-with-resources block, performance is still the same. It's puzzling why Darkflow's implementation of YOLO (in python) is significantly quicker. My program does further post-processing after the YOLO prediction that is just lightweight as shown when I tested it with a basic thresholding for the object detection and it was very quick, even faster visibly than the normal speed/frame rate of the input video.

@saudet I'll try to place the detect method inside a `PointerScope` try resource as shown in your link.

**Comment by zychen2016** [comment] 2019-08-11 12:15
@dreistheman  Have you solved this problem？

**Comment by kobevaliant** [comment] 2019-10-12 11:06
I face the same problem. I use a dll to integrate tensorflow(2.0) through C API, then use JNA to call the dll. The performance is mush slow than that if I use exe to call the dll. Even the session creation is much slow and memory consuming more.

**Comment by abhinavos7a** [comment] 2019-10-12 16:11
> My bad about my comment about latencies. There was a bug in my python code. The latencies in both python and java are comparable.
> 
> Both are around 90 msec.
> The same https://github.com/VowpalWabbit/vowpal_wabbit (linear model with feature hashing) seems to be 500 times faster than tensorflow. On average it was taking 0.1 msec.
> 
> Any insight as to why such a big difference will be helpful
The latencies are now comparable to VW model. I was passing dense features to my Linear model than sparse features, which was resulting in high latencies.

Before:
`
category_column = tf.feature_column.categorical_column_with_hash_bucket(key, hash_size)
tf.feature_column.indicator_column(category_column)
` 
After:
`
tf.feature_column.categorical_column_with_hash_bucket(key, hash_size)
`

According to this [tf source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/feature_column/feature_column_v2.py)

Sparse features can be fed directly into linear models. They behave like an indicator column but with an efficient implementation.

**Comment by dreistheman** [comment] 2019-11-02 14:53
@zychen2016 Not yet as I went to a different project that time but just now I returned to this same detection + observation project. Have you found a way to make it execute at reasonable speed in Java?

**Comment by maziyarpanahi** [comment] 2019-11-02 23:57
>just quickly like that I've also noticed that you don't free up the tensor returned by `yoloSession.runner()`, I don't know how you are running your benchmark loops but you might face memory issues if you don't close it (just declaring it as a `try` resource will do the job).

@karllessard Cloud you please elaborate more about this statement? We have the same situation in our Scala code where we feed and fetch from a graph:
```scala
val calculated = tensorflow.getSession(configProtoBytes = configProtoBytes).runner
      .feed(tokenIdsKey, tensors.createTensor(shrink))
      .fetch(embeddingsKey)
      .run()
``` 
> getSession just checks whether the session exists or it should read/create it

We clear the `tensors` after each prediction, but I am not sure we close the session every time. This code is in Apache Spark where it's being called on each row of the DataFrame.

**Comment by karllessard** [comment] 2019-11-04 04:13
> We clear the tensors after each prediction

@maziyarpanahi: so you mean that you programatically call `calculated.forEach(Tensor::close)` or something like after reading the computed data?

For the session, I just noticed that on the first inference, at that time (I think it was on 1.13), there is some initialization going on in the C++ core library that takes very long and that reusing the same session to run all inferences was preventing this initialization to happen more than once. 

I unfortunately did not find the time yet to find out what exactly was taking so much time. Meanwhile, I can probably give some cues to anyone interested to dig into this further.

**Comment by maziyarpanahi** [comment] 2019-11-05 19:36
@karllessard Sorry for the delay.
> so you mean that you programatically call calculated.forEach(Tensor::close) or something like after reading the computed data?
Yes, we have this function which after each prediction (whether one sentence or multiple sentences) will clear the tensors:

```scala
def clearTensors(): Unit = {
    for (tensor <- tensors) {
      tensor.close()
    }

    tensors.clear()
  }
```
The prediction, session and clearing tensors happen here:
https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowBert.scala#L27

We have the same strategy for other TF graphs (NLP-NER), but this one is for Bert and it consumes a large amount of memory and it crashes in the cluster when data grows over a few millions of rows.

I followed your advice for performance and replace `Tensor.create(obj)` with `Tensor.create(Array(shape, batch), buf)`. It didn't help with the memory consumption in our Bert implementation that is why your comment about memory and session caught my eyes.

Do you have any advice for memory management when it comes to Java implementation of the TF graph involving session, tensors, etc. when it's in a distributed environment like Apache Spark and it will be called on each row?

**Comment by karllessard** [comment] 2019-11-13 02:15
Sorry @maziyarpanahi, I've just noticed your reply as well,

> Do you have any advice for memory management when it comes to Java implementation of the TF graph involving session, tensors, etc. when it's in a distributed environment like Apache Spark and it will be called on each row?

Unfortunately no. Afaik, only instances of `Tensor`, `Session` and `Graph` should be closed explicitly (or via `try-with-resources`) and could lead to memory leaks if they are left opened. I've found in the code where you take care of the tensors but didn't find how you close the session and graph... but those could remain opened for the lifetime of your application, as long as you don't create new ones every now and then. 

Now I'm suggesting to keep the session open to avoid that slow-first-inference I have noticed but maybe doing so create some leaks in the core? In the original examples, the session is always closed after running a graph. Might be interesting to see how your app react in both scenarios?

**Comment by karllessard** [comment] 2021-05-21 22:58
I don’t recall seeing this initial delay on the first inference with the new client, I’d be comfortable closing it yes. Thanks!

**Comment by tensorflowbutler** [comment] 2021-06-10 18:13
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Closed** 2021-06-17 19:23 UTC
Labels: comp:runtime, type:bug
