### ISSUE TITLE
InvalidArgumentError (traceback): BiasGrad requires tensor size <= int32 max in 3D CNN, Tensorflow

### ISSUE THREAD

**Issue by suchetasu** [tensorflow/tensorflow#8471] opened 2017-03-16 15:37 UTC
I am using 3D CNN model in tensorflow. My input image dimension is 3D i.e. (192 * 256 * 256) with one color channel image and i have used three Convolutional layers (with patches of 5 * 5 * 5) and 3 pooling layers (kernal size : 3 * 3 * 3 and stride : 2 * 2 * 2), one full-connection-layer with 128 nodes and output layer with two nodes. The number of samples are 120 for training. Batch size : 10

I am facing the below error on the cluster:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 332, in main
    sess.run(optimizer, feed_dict={train_data_node: batch_data,train_labels_node: batch_labels})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: BiasGrad requires tensor size <= int32 max
         [[Node: gradients/BiasAdd_grad/BiasAddGrad = BiasAddGrad[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Relu_grad/ReluGrad)]]

Caused by op u'gradients/BiasAdd_grad/BiasAddGrad', defined at:
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 290, in main
    optimizer = tf.train.AdamOptimizer(learning_rate=0.0).minimize(train_loss) # Adam Optimizer
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 288, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 354, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 482, in gradients
    in_grads = grad_fn(op, *out_grads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_grad.py", line 204, in _BiasAddGrad
    data_format=data_format))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 313, in bias_add_grad
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'BiasAdd', defined at:
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
[elided 0 identical lines from previous traceback]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 272, in main
    train_prediction = model(train_data_node, True)
  File "./mri_cnn.py", line 181, in model
    relu = tf.nn.relu(tf.nn.bias_add(conv, conv1_biases))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1316, in bias_add
    return gen_nn_ops._bias_add(value, bias, data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 281, in _bias_add
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): BiasGrad requires tensor size <= int32 max
         [[Node: gradients/BiasAdd_grad/BiasAddGrad = BiasAddGrad[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Relu_grad/ReluGrad)]]

Please suggest, how to fix it?

**Comment by MicaelCarvalho** [comment] 2017-03-16 17:53
Please fill the template for issue reporting (it's the standard text when you submit a new issue, you just have to fill the gaps), without those information it's very hard to find the problem.

For example: You don't provide a reproducible example, nor any information about TF version, the optimizer you're using, or the functions you're calling to construct your network. And the problem can be related to either your loss, your optimizer, or your network construction.

Also, if you don't think it's a bug in TF's code nor a feature request, but rather a question, you should post it on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) — it is the standard place for asking for help and the community over there is bigger. ;-)

**Comment by concretevitamin** [comment] 2017-03-16 23:47
Check your tensor sizes - they don't sound like to be `> kInt32Max`.

**Comment by suchetasu** [comment] 2017-03-20 10:37
@concretevitamin : My tensor size is very big as i mentioned in question. so what is the solution

**Comment by MicaelCarvalho** [comment] 2017-03-20 13:10
You're going to have a hard time finding someone willing to help you if you don't fill the template, as I suggested 4 days ago... Big error messages often aren't informative enough to solve the problem.

**Comment by skye** [comment] 2017-03-21 20:53
Hi @suchetasu , as @concretevitamin mentioned, it looks like you're exceeding the max tensor size implemented by the BiasAdd op's gradient. Unfortunately there is no simple solution, you'll either need to change your model to avoid this limitation or we'll need to find someone to modify BiasAddGrad (probably a non-trivial change).

If you share more information as suggested in the template, especially a minimal repro, that will help us find a more specific solution.

**Comment by asimshankar** [comment] 2017-04-08 07:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-08 07:12 UTC
Labels: stat:awaiting response

**Comment by chenxingqiang** [comment] 2021-04-23 04:49
please change your job on GPU
