### ISSUE TITLE
Abort when running tensorflow.python.ops.nn_ops.conv3d_transpose_v2

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61574] opened 2023-08-15 01:34 UTC
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10.0

### Custom code

Yes

### OS platform and distribution

22.04

### Python version

3.9

### CUDA/cuDNN version

nvidia-cudnn-cu11==8.6.0.163, cudatoolkit=11.8.0

### Current behavior?

Due to invalid list elements

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import nn_ops
try:
  arg_0_tensor = tf.random.uniform([2, 4, 4, 4, 3], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_tensor = tf.random.uniform([2, 2, 2, 5, 3], dtype=tf.float32)
  arg_1 = tf.identity(arg_1_tensor)
  arg_2_0 = 2
  arg_2_1 = 8
  arg_2_2 = 8
  arg_2_3 = 8
  arg_2_4 = False
  arg_2 = [arg_2_0,arg_2_1,arg_2_2,arg_2_3,arg_2_4,]
  arg_3 = 2
  out = nn_ops.conv3d_transpose_v2(arg_0,arg_1,arg_2,arg_3,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-08-14 21:33:38.109289: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-08-14 21:33:38.668776: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.686385: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.686530: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.686817: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-14 21:33:38.687712: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.687825: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.687920: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.749104: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.749246: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.749344: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-14 21:33:38.749426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3978 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-08-14 21:33:38.812494: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8600
2023-08-14 21:33:38.825580: F tensorflow/stream_executor/cuda/cuda_dnn.cc:804] Check failed: cudnnSetConvolutionGroupCount( handle_.get(), convolution_descriptor.group_count()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted

```
```

**Comment by SuryanarayanaY** [comment] 2023-08-16 06:27
Hi @dmc1778 , 

I have replicated the reported behaviour with Tf2.10v. However when I have tested the same code with Tf2.12v and tf-nightly code executed successfully. Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/ce477500dc8b53b2f48572cd3edea3c1/61574_2-12v_nightly_2-10v.ipynb).

Since the issue is already fixed with latest versions it's unlikely to cherry pick by us for Tf2.10v.

Please report the security related issues through proper channel as mentioned in [SECURITY.md](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

Please check the [instructions](https://github.com/tensorflow/tensorflow/blob/master/README.md#patching-guidelines) for patching older versions of tensorflow at individuals repo.

Thanks!

**Comment by mihaimaruseac** [comment] 2023-08-16 07:19
Please always check with the latest version.

**Closed by mihaimaruseac** 2023-08-16 07:19 UTC
Labels: stat:awaiting response, type:bug, comp:ops, TF 2.10
