### ISSUE TITLE
Model behavior changes after saving and restoring!

### ISSUE THREAD

**Issue by cocosci** [tensorflow/tensorflow#18124] opened 2018-03-30 16:48 UTC
Hi there,
My tf version is 1.2.1.
It's Okay if I feed the test data after model training, to get an accuracy of 98%.
But after I save and restore the model. The accuracy will only be around 10%. What happened...

Besides, I think the accuracy from the test data should be a constant given that weights and biases won't be updated after training, but each time the accuracy is slightly different. Say, 0.1012, 0.9982, things like that...

Any help?

**Comment by tensorflowbutler** [comment] 2018-03-31 00:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-04-14 12:31
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-29 18:30
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-14 18:59
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment] 2018-05-14 23:01
Closing this issue because the issues template was not filled out.

**Closed by reedwm** 2018-05-14 23:01 UTC
Labels: stat:awaiting response
