### ISSUE TITLE
TensorBoard: Graph Visualization failed Runtime statistics

### ISSUE THREAD

**Issue by laoreja** [tensorflow/tensorflow#10363] opened 2017-06-01 08:12 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 8 (jessie)
- **TensorFlow installed from (source or binary)**: using virtualenv, pip install
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 7.5, cuDNN 4.0
- **GPU model and memory**: GeForce GTX TITAN X 12GB
- **Exact command to reproduce**: Run this https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py scripts.

### Describe the problem
I am following the tutorials in https://www.tensorflow.org/get_started/graph_viz, downloading and running the mnist_with_summaries.py scripts.

All the Tensorboard visualization works, except the Runtime statistics. In the GRAPHS tab, the Session runs shows (0) items available. And it says 'None'.

**Comment by tazr** [comment] 2017-06-01 13:04
That is a duplicate of https://github.com/tensorflow/tensorflow/issues/10317, albeit with a different configuration.

**Comment by jart** [comment] 2017-06-02 00:19
Closing in favor of the other issue. Thanks for the report.

**Closed by jart** 2017-06-02 00:19 UTC
