### ISSUE TITLE
initialize_or_restore() executed on InitializationOnlyStatus returned by tf.train.Checkpoint.restore fails to initialize custom tf.keras.layers.Layer trainables

### ISSUE THREAD

**Issue by mmilosav** [tensorflow/tensorflow#27085] opened 2019-03-24 21:17 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, provided below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): various
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

In the self-contained test below, I am expecting `status.initialize_or_restore(session)` to initialize `my_dense/dense/kernel` and `my_dense/dense/bias`, which should be checkpointable, but it does not, as can be seen from the error message.

**Describe the expected behavior**

The test should execute normally.

**Code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

class MyDense(tf.keras.layers.Layer):
    def __init__(self, units):
        super(MyDense, self).__init__()
        self.units = units

    def build(self, input_shape):
        self.dense = tf.keras.layers.Dense(units=self.units)

    def call(self, inputs, mask=None):
        return self.dense(inputs)

inputs = tf.keras.layers.Input(shape=(1,), dtype=tf.float32)
model = tf.keras.models.Model(inputs=inputs, outputs=MyDense(units=1)(inputs))

checkpoint = tf.train.Checkpoint(model=model)
manager = tf.train.CheckpointManager(checkpoint, directory='./', max_to_keep=None)  # no checkpoint present
status = checkpoint.restore(manager.latest_checkpoint)

inputs_placeholder = tf.placeholder(dtype=tf.float32, shape=[None, 1])
called_model = model(inputs_placeholder)

with tf.Session() as session:
    status.initialize_or_restore(session)
    session.run(called_model, feed_dict={inputs_placeholder: np.array([[1.]])})
```

**Other info / logs**

WARNING:tensorflow:From /venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-24 16:09:11.964524: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable my_dense/dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/my_dense/dense/kernel/N10tensorflow3VarE does not exist.
	 [[{{node model/my_dense/dense/MatMul/ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/initialize_or_restore.py", line 27, in <module>
    session.run(called_model, feed_dict={inputs_placeholder: np.array([[1.]])})
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable my_dense/dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/my_dense/dense/kernel/N10tensorflow3VarE does not exist.
	 [[node model/my_dense/dense/MatMul/ReadVariableOp (defined at /initialize_or_restore.py:13) ]]

Caused by op 'model/my_dense/dense/MatMul/ReadVariableOp', defined at:
  File "/initialize_or_restore.py", line 23, in <module>
    called_model = model(inputs_placeholder)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 815, in call
    mask=masks)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1002, in _run_internal_graph
    output_tensors = layer.call(computed_tensor, **kwargs)
  File "/initialize_or_restore.py", line 13, in call
    return self.dense(inputs)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 975, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5333, in mat_mul
    name=name)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1222, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1177, in _dense_var_to_tensor
    return self.value()
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 644, in value
    return self._read_variable_op()
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 728, in _read_variable_op
    self._dtype)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 550, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Error while reading resource variable my_dense/dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/my_dense/dense/kernel/N10tensorflow3VarE does not exist.
	 [[node model/my_dense/dense/MatMul/ReadVariableOp (defined at /initialize_or_restore.py:13) ]]

Process finished with exit code 1

**Comment by allenlavoie** [comment] 2019-03-25 17:36
Layer only started tracking its sub-Layers like Network/Model in https://github.com/tensorflow/tensorflow/commit/e0f8b4cea2486cae671c60cc7645913bea1abf60

So the issue is that the variables aren't tracked. Can you use tf.keras.Model instead? Or try a nightly and it should work.

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:38
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!

**Closed by jvishnuvardhan** 2019-04-03 21:38 UTC
Labels: comp:keras, type:support
