### ISSUE TITLE
Android tensorflow-lite-select-tf-ops.aar generated from tflite model build and deploy error

### ISSUE THREAD

**Issue by quickgrid** [tensorflow/tensorflow#45153] opened 2020-11-24 14:37 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I am following [this](https://www.tensorflow.org/lite/guide/build_android) guide to reduce my apk size. I followed the `Set up build environment using Docker` process to generate, `tensorflow-lite.aar`, `tensorflow-lite-select-tf-ops.aar` with my tflite model. 

After running, `bash tensorflow/lite/tools/build_aar.sh --input_models=custom_model.tflite --target_archs=arm64-v8a,armeabi-v7a` I found the `aar` files in tmp folder of docker container in `/tensorflow_src/bazel-bin/tmp/tensorflow-lite.aar` and `/tensorflow_src/bazel-bin/tmp/tensorflow-lite-select-tf-ops.aar`.

I followed the part below by making `libs` folder and copying the aar files.

```
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    compile(name:'tensorflow-lite', ext:'aar')
}
```

My current code and model requires implementations below to work correctly.

```
implementation 'org.tensorflow:tensorflow-lite:2.3.0'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
```

The problem comes when the above three implementation or commenting two except `implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'` gives errors,

```
cannot find symbol class Interpreter`
cannot find symbol class NnApiDelegate
error: package org.tensorflow.lite.nnapi does not exist
``` 

This error is not show when `fat_apk` is built using command, `bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain tensorflow/lite/java:tensorflow-lite`. But using this method there is no `tensorflow-lite-select-tf-ops.aar` in `/tensorflow_src/bazel-bin/tensorflow/lite/java/` folder.

Using the previous with above fat_apk tensorflow-lite aar it crashes with error,

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK6google8protobuf7Message11GetTypeNameEv" referenced by "/data/app/com.example.myapp-PkLKD5MHuq9TB2R3mDgNcA==/base.apk!/lib/arm64-v8a/libtensorflowlite_flex_jni.so"...
```

My main goal is reduce size of `select-ft-ops` as I noticed it reduces app size by 60+mb. If there is an alternate method please suggest. Also looking for building instructions of tensorflow-lite-gpu aar.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Setup docker in Ubuntu 18.04 and download dockerfile from [here](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile). 
- Follow commands from `Set up build environment using Docker` section from [here](https://www.tensorflow.org/lite/guide/build_android#set_up_build_environment_using_docker).
- Run `./configure`.
- Use command, `bash tensorflow/lite/tools/build_aar.sh --input_models=custom_model.tflite --target_archs=arm64-v8a,armeabi-v7a`.
- Get the `aar` files from `tmp` folder as mentioned [here](https://www.tensorflow.org/lite/guide/ops_select) in section `Building the Android AAR` and paste in `libs` folder of android project.
- Paste following, 
```
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    compile(name:'tensorflow-lite', ext:'aar')
    compile(name:'tensorflow-lite-select-tf-ops', ext:'aar')
}
```
- Commenting out following,
```
//implementation 'org.tensorflow:tensorflow-lite:2.3.0'
//implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by quickgrid** [comment] 2020-11-24 17:30
Following, https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/lite/g3doc/guide/ops_select.md, I was able to get `tensorflow-lite-select-tf-ops.aar` that seems to work with `fat_apk_cpu` build of `tensorflow-lite.aar` . 

Command used to generate,
```
bazel build --cxxopt='--std=c++14' -c opt   \
  --config=android_arm64 --config=monolithic  \
  //tensorflow/lite/java:tensorflow-lite-select-tf-ops
```

Took config from here, https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/BUILD.

But, [this](https://www.tensorflow.org/lite/guide/build_android#build_and_install) part is still not working for reducing size of select-tf-ops with given tflite model.

I am confused about below as I cannot see any branch named Head in tensorflow. 

> Caution: Following feature is experimental and only available at HEAD. You can build smaller AAR files targeting only a set of models as follows:

**Comment by quickgrid** [comment] 2020-11-26 08:55
I was able to build `tensorflow-lite.aar` and `tensorflow-lite-gpu.aar` with `TF 2.3.0` for `arm64-v8a`. App works fine with newly built `aar`, but when it is included in app the size is slightly more than usual implementation for both release and debug builds. It is larger by around ~2mb. 

The `aar` were pasted into `app/libs` directory. I followed this for building aar,

https://github.com/tensorflow/tensorflow/issues/35170

Below are the working `aar` files. I used `--config=monolithic` for both of these,

[SEPARATE_TFLITE_BUILD_WITH_GPU.zip](https://github.com/tensorflow/tensorflow/files/5601544/SEPARATE_TFLITE_BUILD_WITH_GPU.zip)

App `build.gradle`,

```
ndk {
    //abiFilters 'armeabi-v7a', 'arm64-v8a'
    //abiFilters 'armeabi-v7a'
    abiFilters 'arm64-v8a'
}
```

```
dependencies {
    ...
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.3.0'
//    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
//    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'

    implementation files('libs/tensorflow-lite.aar')
    implementation files('libs/tensorflow-lite-gpu.aar')
}
```


The problem with `tensorflow-lite-select-tf-ops.aar`  still persists. I used below command to generate it,

```
bash tensorflow/lite/tools/build_aar.sh --input_models=custom_model.tflite --target_archs=arm64-v8a
```

After build finished I get two files, `tensorflow-lite-select-tf-ops.aar` of size 2.739mb and `tensorflow-lite.aar` of size 144kb. Here are the generated `aar` files,

[SELECT_TF_OPS_WITH_INPUT_MODEL.zip](https://github.com/tensorflow/tensorflow/files/5601525/SELECT_TF_OPS_WITH_INPUT_MODEL.zip)

If I put both on the project I get error with `symbol not found Interpreter` and codes like `Interpreter.Options options = (new Interpreter.Options());` does not compile. If I put my [separately built](https://github.com/tensorflow/tensorflow/issues/35170) `tensorflow-lite.aar` size of 1.01mb with `implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.3.0'` it works.


I  also tried edited the dockerfile below by replacing `FROM tensorflow/tensorflow:devel` with `FROM tensorflow/tensorflow:2.3.0`. In ubuntu 20.04 `FROM tensorflow/tensorflow:devel` works.

https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile

I was able build `tensorflow-lite-select-tf-ops.aar` successfully on ubuntu 18.04 with `FROM tensorflow/tensorflow:2.3.0`. I am not sure if this is OS version problem. Now on ubuntu 20.04 I get,

```
ubuntu@ip-172-31-14-29:~$ docker build . -t tflite-builder -f tflite-android2.Dockerfile
Sending build context to Docker daemon  2.974MB
Step 1/17 : FROM tensorflow/tensorflow:2.3.0
 ---> 539d0e818045
Step 2/17 : ENV ANDROID_DEV_HOME /android
 ---> Using cache
 ---> 4ade7614b16b
Step 3/17 : RUN mkdir -p ${ANDROID_DEV_HOME}
 ---> Using cache
 ---> b2531200046f
Step 4/17 : ENV ANDROID_SDK_FILENAME tools_r25.2.5-linux.zip
 ---> Using cache
 ---> 0ab178e71e00
Step 5/17 : ENV ANDROID_SDK_URL https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}
 ---> Using cache
 ---> 1408762ceea5
Step 6/17 : ENV ANDROID_API_LEVEL 23
 ---> Using cache
 ---> 1e20aa8d980a
Step 7/17 : ENV ANDROID_NDK_API_LEVEL 18
 ---> Using cache
 ---> 619a6e784914
Step 8/17 : ENV ANDROID_BUILD_TOOLS_VERSION 28.0.0
 ---> Using cache
 ---> 32d81af7433a
Step 9/17 : ENV ANDROID_SDK_HOME ${ANDROID_DEV_HOME}/sdk
 ---> Using cache
 ---> 8b90b07c7c63
Step 10/17 : ENV PATH ${PATH}:${ANDROID_SDK_HOME}/tools:${ANDROID_SDK_HOME}/platform-tools
 ---> Using cache
 ---> f412a21692d1
Step 11/17 : RUN cd ${ANDROID_DEV_HOME} &&     wget -q ${ANDROID_SDK_URL} &&     unzip ${ANDROID_SDK_FILENAME} -d android-sdk-linux &&     rm ${ANDROID_SDK_FILENAME} &&     bash -c "ln -s ${ANDROID_DEV_HOME}/android-sdk-* ${ANDROID_SDK_HOME}"
 ---> Running in b9cf0267b396
/bin/sh: 1: wget: not found
The command '/bin/sh -c cd ${ANDROID_DEV_HOME} &&     wget -q ${ANDROID_SDK_URL} &&     unzip ${ANDROID_SDK_FILENAME} -d android-sdk-linux &&     rm ${ANDROID_SDK_FILENAME} &&     bash -c "ln -s ${ANDROID_DEV_HOME}/android-sdk-* ${ANDROID_SDK_HOME}"' returned a non-zero code: 127
ubuntu@ip-172-31-14-29:~$ ls
tensorflow-lite-select-tf-ops.aar  tflite-android.Dockerfile
tensorflow-lite.aar                tflite-android2.Dockerfile
ubuntu@ip-172-31-14-29:~$ nano tflite-android2.Dockerfile
ubuntu@ip-172-31-14-29:~$ docker build . -t tflite-builder -f tflite-android2.Dockerfile
Sending build context to Docker daemon  2.974MB
Step 1/17 : FROM tensorflow/tensorflow:2.3.0
 ---> 539d0e818045
Step 2/17 : ENV ANDROID_DEV_HOME /android
 ---> Using cache
 ---> 4ade7614b16b
Step 3/17 : RUN mkdir -p ${ANDROID_DEV_HOME}
 ---> Using cache
 ---> b2531200046f
Step 4/17 : ENV ANDROID_SDK_FILENAME tools_r25.2.5-linux.zip
 ---> Using cache
 ---> 0ab178e71e00
Step 5/17 : ENV ANDROID_SDK_URL https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}
 ---> Using cache
 ---> 1408762ceea5
Step 6/17 : ENV ANDROID_API_LEVEL 23
 ---> Using cache
 ---> 1e20aa8d980a
Step 7/17 : ENV ANDROID_NDK_API_LEVEL 18
 ---> Using cache
 ---> 619a6e784914
Step 8/17 : ENV ANDROID_BUILD_TOOLS_VERSION 28.0.0
 ---> Using cache
 ---> 32d81af7433a
Step 9/17 : ENV ANDROID_SDK_HOME ${ANDROID_DEV_HOME}/sdk
 ---> Using cache
 ---> 8b90b07c7c63
Step 10/17 : ENV PATH ${PATH}:${ANDROID_SDK_HOME}/tools:${ANDROID_SDK_HOME}/platform-tools
 ---> Using cache
 ---> f412a21692d1
Step 11/17 : RUN cd ${ANDROID_DEV_HOME} &&     wget -q ${ANDROID_SDK_URL} &&     unzip ${ANDROID_SDK_FILENAME} -d android-sdk-linux &&     rm ${ANDROID_SDK_FILENAME} &&     bash -c "ln -s ${ANDROID_DEV_HOME}/android-sdk-* ${ANDROID_SDK_HOME}"
 ---> Running in f73c18575539
/bin/sh: 1: wget: not found
The command '/bin/sh -c cd ${ANDROID_DEV_HOME} &&     wget -q ${ANDROID_SDK_URL} &&     unzip ${ANDROID_SDK_FILENAME} -d android-sdk-linux &&     rm ${ANDROID_SDK_FILENAME} &&     bash -c "ln -s ${ANDROID_DEV_HOME}/android-sdk-* ${ANDROID_SDK_HOME}"' returned a non-zero code: 127
ubuntu@ip-172-31-14-29:~$
```

**Comment by quickgrid** [comment] 2020-11-26 14:27
Tried with command below to generate trimmed `tensorflow-lite-select-tf-ops.aar`  and `tensorflow-lite.aar` following https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/build_aar_with_docker.sh. 

With the provided `tensorflow-lite.aar` still get compilation error,

```
error: cannot find symbol
import org.tensorflow.lite.Interpreter;
                          ^
  symbol:   class Interpreter
  location: package org.tensorflow.lite
```

Get the results from `bazel-bin/tmp`. Build commands,
```
docker build . -t tflite-builder -f tflite-android.Dockerfile
docker run -it -v $PWD:/host_dir tflite-builder bash
cd tensorflow_src
wget "..." -O "custom_model.tflite"
bash tensorflow/lite/tools/build_aar_with_docker.sh --input_models=custom_model.tflite --target_archs=arm64-v8a --checkpoint=master
```

**Comment by terryheo** [comment] 2020-12-07 01:17
@thaink could you check this issue?

**Comment by thaink** [comment] 2020-12-07 05:20
Are build building it at Tensorflow v2.3.0? Or at what commit are you using?

There seems to be a divergence between compiler versions. The error related to "_ZNK6google8protobuf7Message11GetTypeNameEv" did not happen in my debian system but reported by another.
Anyway, this error should be fixed, so could you try it at v2.4.0-rc4?

**Comment by thaink** [comment] 2021-01-19 08:24
As mentioned earlier, this error was fixed before v2.4.0.

**Closed by thaink** 2021-01-19 08:24 UTC
Labels: comp:lite, type:build/install

**Comment by farmaker47** [comment] 2021-01-20 18:18
@quickgrid Is the solution to this issue to replace the first line of the Dockerfile?
Do I have to replace FROM tensorflow/tensorflow:devel to..... FROM tensorflow/tensorflow:2.4.0 to have a succesdfull build of the two final desired .aar files?
Thanks

**Comment by quickgrid** [comment] 2021-01-20 23:40
I ended up using default `org.tensorflow` implementations. Did not get a chance to try to rebuild and test with the AAR files. It is likely fixed as mentioned above. I think the build will work as is with the given Dockerfile without needing to modifying it.

**Comment by farmaker47** [comment] 2021-01-21 17:32
@quickgrid Unfortunately default implementation gives me the same errors as you have mentioned back in November and December. If you have time please check your .aar files and come back with the results. During that I will give a try with FROM tensorflow/tensorflow:2.4.0 . Procedure with a Xeon processor takes 3 hours to complete and I cannot do a lot of experiments.

**Comment by quickgrid** [comment] 2021-01-24 12:25
Did `tensorflow:2.4.0` version work? Also are you getting these errors for `implementation 'org.tensorflow:tensorflow-lite:2.4.0'` and `implementation 'org.tensorflow:tensorflow-lite-gpu:2.4.0'` or only custom built AAR's? 

I did the previous builds on aws c5 metal instance. It probably took maybe ~20 minutes per build. Other attempts failed as they took too long per build. If I remember correctly a combination of org.tensorflow and custom built aar increased apk size more than using only org.tensorflow implementations.

**Comment by thaink** [comment] 2021-01-25 08:05
@farmaker47 caching is enabled when you build so It would be reasonable if the build time is about < 30minutes after the first build. I just tried but actually cannot reproduce the issue. Is there any quick way I can reproduce your issue?

**Comment by farmaker47** [comment] 2021-01-25 08:09
@thaink Hi, thanks for looking into this. I tried another time in the weekend after you have commited changes to build_aar_with_docker.sh and unfortunately I got the same error. The only thing  we can do is give you my .tflite file and try. WDYT?

**Comment by thaink** [comment] 2021-01-27 04:31
@farmaker47 I would prefer a dummy project that explaining how you import those aar files.

**Comment by farmaker47** [comment] 2021-01-27 04:59
@thaink Ok I will clean the current and get back to you. Inside you can see the build.gradle file and the .tflite file that I used to generate the .aar ones. Thank you

**Comment by farmaker47** [comment] 2021-01-30 06:23
@thaink Hi again,
I send you the [link ](https://github.com/farmaker47/OCR_with_Keras/tree/cleaned_interpreter)of my project. Please verify that you are at cleaned_interpreter branch. I followed the instructions [here](https://www.tensorflow.org/lite/guide/build_android#add_aar_directly_to_project) and inserted inside libs folder 3 .aar files. The tensorflow-lite.aar is generated with no arguments when I executed the build_aar_with_docker.sh file. The other 2 (tensorflow-lite-main.aar, tensorflow-lite-ops.aar) where generated adding arguments specified [here](https://www.tensorflow.org/lite/guide/reduce_binary_size#build_aar_files_for_android_project_2). The .tflite file I used when executed the script (with arguments) is inside assets folder of the project (ocr_dr.tflite) and you can use it in the future to build your own custom .aar files if you want. 

Inside app's build.gradle file you can see the code for using the .aar files.

1. When using the (default) tensorflow-lite.aar file (that was generated with no arguments) and the main dependency for the special operators `implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'` (line 78 of build.gradle file) project runs flawlessly.
2. When using only the custom .aar files (tensorflow-lite-main.aar, tensorflow-lite-ops.aar) that where generated adding arguments specified [here](https://www.tensorflow.org/lite/guide/reduce_binary_size#build_aar_files_for_android_project_2), 2 errors occur. First it cannot find Interpreter class to build the project. Second if you use the default .aar file (tensorflow-lite.aar) and the  tensorflow-lite-ops.aar the project builds but app crashes at start with `_ZNK6google8protobuf7Message11GetTypeNameEv` error.

I am really interested to find out what is wrong with the set up! Thank you for looking into this!

FYI @khanhlvg

**Comment by ojj11** [comment] 2021-02-08 12:14
I found that I had to add `build --config=monolithic` to `.bazelrc` to avoid this error. It looks like by default the compilation assumes that some of the implementation is already in a system library on device.

**Comment by barrypitman** [comment] 2021-02-08 12:59
Thanks! I'm going to try that now, will update. The issue with the missing classes in the tensorflow-lite.aar is fixed in master - see https://github.com/tensorflow/tensorflow/issues/45488

**Comment by barrypitman** [comment] 2021-02-09 08:40
I've added a comment here - https://github.com/tensorflow/tensorflow/issues/46989. Your suggestion helped, thanks!

**Comment by farmaker47** [comment] 2021-02-13 17:36
I confirmed today that with the latest change at [build_aar.sh file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/build_aar.sh) where at line 125 was added `--config=monolithic` we have a working tensorflow_select_tf_ops.aar file. We have to use the tensorflow_lite.aar file that is downloaded from Maven repository though for everything to work correctly.
FYI @thaink

**Comment by thaink** [comment] 2021-02-15 02:10
@farmaker47 So what error is still remaining with tensorflow_lite.aar?

**Comment by farmaker47** [comment] 2021-02-15 17:44
@thaink My apologies for the mistake! Everything is working correctly. Tensorflow_lite.aar and tensorflow_lite_select_tf_ops.aar are generated and working correctly inside my AS project. Check [this](https://github.com/farmaker47/OCR_with_Keras/tree/with_custom_support_library) repository (the specific branch). Project from 120MB is now 38.8MB!!

Inside this project there is also a custom tensorflow_lite_support.aar file which I have generated inside Docker, based on your method. This library contains some extra functions for grayscale and buffer from one channel images. You can check out the procedure here:
https://github.com/farmaker47/Build_TensorFlow_Lite_Support_Library_With_Docker

Thank you again! I hope we collaborate again.

@khanhlvg FYI
