### ISSUE TITLE
How to use the function FusedBatchNorm() in C++?

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#22266] opened 2018-09-14 02:26 UTC
The question is that : https://stackoverflow.com/questions/52308509/tensorflow-c-how-to-convert-tensorflowoutput-to-tensor

Python has the function `covert_to_tensor()`，but C++ does not have this function. The `FusedBatchNorm()` need a `Tensor ` input, but my input type is `tensorflow::Input`. So how to solve this problem？How to convert `tensorflow::Input` to `Tensor` ？

**Comment by tensorflowbutler** [comment] 2018-09-29 18:42
Nagging Assignee @josh11b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-14 18:38
Nagging Assignee @josh11b: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-29 12:41
Nagging Assignee @josh11b: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-13 18:54
Nagging Assignee @josh11b: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-28 18:59
Nagging Assignee @josh11b: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achandraa** [comment] 2019-06-27 09:59
@EdwardVincentMa : Apologies for late response. Looks like not a bug/performance/feature request therefore question can be better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) for better and faster response. If resolved already, we shall close the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-07-04 11:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-04 11:23 UTC
Labels: comp:ops, stat:awaiting response, type:support
