### ISSUE TITLE
Unable to download the TensorFlow using pip in Windows 10

### ISSUE THREAD

**Issue by imoisharma** [tensorflow/tensorflow#37205] opened 2020-03-01 12:36 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Microsoft Windows 10 Home Single Language |  10.0.18363 N/A Build 18363 |  x64-based PC | 16GB | 4GB 1050Ti Nvidia GC
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: NA
- TensorFlow installed from (source or binary): https://www.tensorflow.org/install/pip?lang=python3
- TensorFlow version:  2.1
- Python version:  3.8.2
- Installed using virtualenv? pip? conda?: virtualenv and pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 1050Ti Nvidia 

**Describe the problem**
I have tried to both Virtualenv and pip but won't able to install. What should I do?

" ERROR: Could not find a version that satisfies the requirement TensorFlow (from versions: none)
ERROR: No matching distribution found for TensorFlow"

**Provide the exact sequence of commands/steps that you executed before running into the problem**

python3 --version   # 3.8.2
pip3 --version           # 20.0.2
virtualenv --version  #  20.0.7

pip3 install -U pip virtualenv

virtualenv --system-site-packages -p python3 ./venv
.\venv\Scripts\activate
pip install --upgrade pip

pip list  # show packages installed within the virtual environment

pip install --upgrade tensorflow

then the error is coming 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-03-02 05:09
@imoisharma,
Tensorflow is only supported till Python 3.7 as of now. For more information, please check [this](https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-571074915) comment from a similar issue. Thanks!

**Comment by amahendrakar** [comment] 2020-03-11 14:50
Any updates regarding this issue? Thanks!

**Comment by NeilClack** [comment] 2020-03-13 14:52
I understand that it is only limited to Python 3.7, however, which subversion of 3.7? Do we have a confirmed number or should it "simply be any Python 3.7"?

I'm encountering the same issues with Python 3.7.6 no matter what operating system I attempt to install on, resulting in the exact same error.

The documentation doesn't specify any specific 3.7 installation however it would be very beneficial to know if we need to be so specific in our versions. I can't imagine any breaking changes between any 3.7.x and 3.7.x+ however, clearly something has gone wrong here.

**Comment by mihaimaruseac** [comment] 2020-03-13 16:57
Any version of python 3.5, 3.6 or 3.7 should work, provided it is a 64 bits, your CPU is 64 bits and supports AVX and you have the latest MSVC redistributable installed. Oh, also, ensure `pip` is at latest version, to be able to install manylinux2010 packages

For all other cases, you will have to build from source.

**Comment by NeilClack** [comment] 2020-03-13 17:08
Python 3.7.6
Pip 20.0.2
Windows 10
Got it working by downloading the matching (version and environment) wheel from https://pypi.org/project/tensorflow/#files and installing manually from that.

In my example, I needed Tensorflow 2.1 and downloaded the tensorflow-2.1.0-cp37-cp37m-win_amd64.whl as I have cp37 (CPython 3.7), win_amd64 (Windows 64 bit)

For those who come here in the future and may not be used to installing pip wheels manually (only having ever used pip install)

Download the necessary file. Tensorflow's naming convention seems to be tensorflow-<version>-<python version>-<os & architecture>, although I'm not sure what the cp37m means here, it should not be necessary for you to find the right file.
Open a terminal and navigate to your download directory.
pip install <tensorflow whl filename>

In my case, on windows, it looked like this:

pip install C:/Users/username/Downloads/tensorflow-2.1.0-cp37-cp37m-win_amd64.whl

This did the trick for me, however I was not able to reproduce this with pipenv install, so for now, virtual environments are out of the question, albeit right now, not even necessary for me anyways.

**Comment by mihaimaruseac** [comment] 2020-03-13 18:42
`cp37m` is `cpython 3.7 manylinux` tag.

Don't know exactly why you needed to download the file and then install it like this, but good to know it works.

Closing the issue as it is resolved

**Closed by mihaimaruseac** 2020-03-13 18:42 UTC
Labels: TF 2.1, stat:awaiting response, subtype:windows, type:build/install
