### ISSUE TITLE
Mobilenet v3 keras model lack a 7x7 avgpool and cannot get reported performance

### ISSUE THREAD

**Issue by Kewenjing1020** [tensorflow/tensorflow#48226] opened 2021-04-01 05:56 UTC
Mobilenetv3 keras model is reported as converted from its ckpt model. As I observed its structure, they are inconsistent, as keras model **lacks a 'Avgpool' layer before conv_2 layer**. As a consequence, the released mobilenetv3_large_1.0 model can only achieve top1: 72.7%, 3% lower than ckpt model.

**Comment by Saduf2019** [comment] 2021-04-01 09:13
@Kewenjing1020 
Can you please share the code in support of the issue reported, also if possible share a colab gist with the issue reported.

**Comment by Kewenjing1020** [comment] 2021-04-02 03:52
Hi @Saduf2019 , I observed the model structure via netron.app.  For the evaluation code, I thought your team should have tested it before release.

**Comment by Saduf2019** [comment] 2021-04-08 06:12
@Kewenjing1020 
Please share simple stand alone code such that we can replicate the issue or a colab gist with the issue reported.

**Comment by l-bat** [comment] 2021-04-13 13:33
@Saduf2019 please look at  #48504

**Comment by Saduf2019** [comment] 2021-04-19 16:40
@i-bat 
is this a duplicate of #48504, if yes please move this to closed status as its already tracked.

**Comment by qlzh727** [comment] 2021-04-21 18:17
Thanks for reporting the issue. Please https://github.com/tensorflow/tensorflow/pull/48542#issuecomment-824258134 for more updates. #48542 should fix the issue.

**Closed** 2021-04-22 17:28 UTC
Labels: stat:awaiting response, type:performance
