### ISSUE TITLE
Feature request: Please release an official binary for Raspberry Pi

### ISSUE THREAD

**Issue by FlorinAndrei** [tensorflow/tensorflow#5729] opened 2016-11-20 06:41 UTC
The Raspberry Pi is an excellent platform for robotics and automation. The native camera also makes a great combo for portable / embedded / robotics computer vision. Having TensorFlow available on this platform would really open up a lot of options in this context.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

none

### Environment info
Operating System:

Raspbian Jessie on Raspberry Pi 3

### What other attempted solutions have you tried?

https://github.com/samjabrahams/tensorflow-on-raspberry-pi

It only provides a binary for TensorFlow 0.10. I've had lots of issues with it running DNNs trained on 0.11. I need to train on 0.11 because the only fast GPU I have is an Nvidia Pascal chip, and 0.10 doesn't work well on Pascal (due to CUDA version issues).

I've tried to compile 0.11 following the guide there, but there were a lot of errors.

**Comment by samjabrahams** [comment] 2017-04-06 02:05
To add an update to this, I have unofficial binaries through version 1.0.1 [available here](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v1.0.1).

**Comment by FlorinAndrei** [comment] 2017-06-20 18:36
@itsmeolivia Any reasons you could provide for closing this issue?

**Comment by ebrevdo** [comment] 2017-07-07 19:57
@petewarden agrees that some sort of official support would be good.  We're currently looking into options for automated testing and builds.

**Comment by ebrevdo** [comment] 2017-07-07 19:58
Additional build options for RPi:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples

and

@petewarden just added frozen Mobilenet models here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/tutorials/image_retraining.md#other-model-architectures

**Comment by previ** [comment] 2017-08-17 09:38
Hi, is there a (supported) way to compile the framework from the source for the RPi, including the Python bindings?

**Comment by samjabrahams** [comment] 2017-08-17 14:04
@previ it would appear that the answer is soon!

https://github.com/tensorflow/tensorflow/pull/11675

https://github.com/tensorflow/tensorflow/pull/12190

**Comment by mattfeury** [comment] 2017-08-19 07:07
hey all,

first off thanks for all the work here. I've been struggling to get TF setup on my Pi A+ (armv6), but with the recent work in #12190, i was able to build, install, and run TF. sweet!

i was curious what type of benchmarks others were seeing though. I am running (through Keras) a very basic predict on a somewhat small CNN, and I am seeing anywhere from 10-40s predict times (not including loading the model, imports, etc). This seems extremely high to me consider switching the Keras backend to Theano causes predictions to stick around 5s.

Is there perhaps someway to optimize the installation? I've tried overclocking and shrinking/expanding gpu memory, but everything is still 10+. As far as I know, it can't leverage the GPU but my next step is to try building the wheel with gpu support.

**Comment by ebrevdo** [comment] 2017-08-19 14:58
Have you tried running the benchmark_model binary with your model?  The
python bindings are good for prototyping but the best performance check for
inference time is benchmark_model.

On Aug 19, 2017 12:07 AM, "Matt Feury" <notifications@github.com> wrote:

hey all,

first off thanks for all the work here. I've been struggling to get TF
setup on my Pi A+ (armv6), but with the recent work in #12190
<https://github.com/tensorflow/tensorflow/pull/12190>, i was able to build,
install, and run TF. sweet!

i was curious what type of benchmarks others were seeing though. I am
running (through Keras) a very basic predict on a somewhat small CNN, and I
am seeing anywhere from 10-40s predict times (not including loading the
model, imports, etc). This seems extremely high to me consider switching
the Keras backend to Theano causes predictions to stick around 5s.

Is there perhaps someway to optimize the installation? I've tried
overclocking and shrinking/expanding gpu memory, but everything is still
10+. As far as I know, it can't leverage the GPU but my next step is to try
building the wheel with gpu support.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/5729#issuecomment-323505961>,
or mute the thread

**Comment by ebrevdo** [comment] 2017-08-19 14:59
However we should definitely look into optimizing performance as well.  I'm
assuming the pip package was built with -c opt?

**Comment by mattfeury** [comment] 2017-08-19 19:27
I will run those benchmarks later tonight and get back to you. in terms of flags i used to build, i used the `build_raspberry_pi.sh` directly, which translated into

```
bazel build -c opt --copt=-march=armv6 --copt=-mfpu=vfp \
  --copt=-funsafe-math-optimizations --copt=-ftree-vectorize \
  --copt=-fomit-frame-pointer --cpu=armeabi \
  --crosstool_top=@local_config_arm_compiler//:toolchain \
  --verbose_failures \
  //tensorflow/tools/benchmark:benchmark_model \
  //tensorflow/tools/pip_package:build_pip_package
```

**Comment by ebrevdo** [comment] 2017-08-20 14:25
It could be you should compile with neon optimizations, could be you need
to configure the number of threads by passing the config object when
creating a session.

**Comment by mattfeury** [comment] 2017-08-20 14:59
i will try neon optimizations, but it seems like those are explicitly disabled for armv6 architecture. probably for a decent reason. plan to try some new compilations today and will report back.

**Comment by ebrevdo** [comment] 2017-08-20 15:22
Indeed you may run into illegal instruction errors. Please report back.

**Comment by mattfeury** [comment] 2017-08-20 21:20
yup "illegal instruction" when running the below :(

```
  PI_COPTS='--copt=-march=armv6 --copt=-mfpu=neon-vfpv4
  --copt=-U__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1
  --copt=-U__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2
  --copt=-U__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8'

bazel build -c opt ${PI_COPTS} \
  --copt=-funsafe-math-optimizations --copt=-ftree-vectorize \
  --copt=-fomit-frame-pointer --cpu=armeabi \
  --crosstool_top=@local_config_arm_compiler//:toolchain \
  --local_resources 2048,.5,1.0 \
  --verbose_failures \
  //tensorflow/tools/benchmark:benchmark_model \
  //tensorflow/tools/pip_package:build_pip_package
```

i also tried configuring the number of threads, but to no avail (but since Pi A+ is single cpu i didn't expect much there).

is there anyway to enable the pi gpu? i don't believe it's opencl or cuda compatible, but grasping at straws looking for ways to speed this guy up. not sure what makes theano so much quicker by comparison

**Comment by previ** [comment] 2017-08-20 21:36
as a further information, I installed on a RPi 3 the framework (1.1) from the  python (2.7) wheel provided here: https://github.com/samjabrahams/tensorflow-on-raspberry-pi

and I can confirm that python bindings work, but they are about 5x or more slower compared to the "label_image" c++ example for RPi (using the same graph and image).

It also appears that the framework uses just one core, even if   config=tf.ConfigProto(intra_op_parallelism_threads=4, inter_op_parallelism_threads=4) is passed as config param in tf.Session(), the total CPU usage never exceeds 25%.

**Comment by ebrevdo** [comment] 2017-08-20 22:13
We may need to get c++ protobuf bindings compiled for rpi.  Also the single
thread use looks like it may be a bug.  Will need Pete to look at that.

**Comment by petewarden** [comment] 2017-08-20 22:37
@mattfeury - Can you email me your model and the benchmark_model command line (or however you're running it?). My email is petewarden@google.com.

I've done [some work with the Pi's GPU in the past](https://petewarden.com/2014/08/07/how-to-optimize-raspberry-pi-code-using-its-gpu/), and it's pretty old and funky. It doesn't support CUDA, OpenCL or any decent programming language, so it's not a great option unfortunately.

We do now have [automatic pip wheels being built every night](https://petewarden.com/2017/08/20/cross-compiling-tensorflow-for-the-raspberry-pi/), I'd be interested to get feedback on how well they work for everyone on this thread. For example @previ I believe the ones we create for the Pi 2/3 should be as fast as label_image, since they use NEON instructions, unlike the older versions. Let me know how you get on though.

**Comment by mattfeury** [comment] 2017-08-20 23:15
Thanks @petewarden. emailed you directly and am checking out the rest of your linked blog posts. i will update the thread here if I'm able to squeak out any performance improvements

**Comment by previ** [comment] 2017-08-28 09:56
@petewarden I installed tf from the official pip wheel on a RPi 3.
It actually works much faster than in my previous tests: I achieved about 8 fps using a retrained mobilenet model (0.25, 128, quantified) from python apis, which is very good.
I noticed that the first couple of runs of the model are quite slow (about 10 times slower) but after that, tf optimizes the run and achieves very good performance, using all of the available resources (4 cores on the RPi).

**Comment by dsiot** [comment] 2017-09-10 06:57
@samjabrahams @FlorinAndrei @petewarden I am also happy to contribute to this through my course (Data Science for IoT @Oxford uni). would you recommend a place to start so we can duplicate the existing implementation? I am also interested extending further with non image based use cases (ex sensor fusion, complex event processing etc on tensorflow with embedded devices esp on Pi). One more interest area is exploring synergies between Keras and TF embeded (most of the current course is structured on Keras with TF backend). many thanks for your help

**Comment by petewarden** [comment] 2017-09-10 07:06
The latest documentation on cross-compiling for the Pi is here, along with
links to the previous binaries:
https://petewarden.com/2017/08/20/cross-compiling-tensorflow-for-the-raspberry-pi/

We'll be updating the main TensorFlow site soon, but let me know how you
get on with these instructions. I've managed to get Keras running together
with TF on the Pi too using this approach.

**Comment by dsiot** [comment] 2017-09-10 07:09
@petewarden many thanks. This is very useful for my course as a base to start. shall share back also

**Comment by dsiot** [comment] 2017-09-10 17:37
@petewarden another thought .. as I understand it .. TF embedded/ TF mobile is designed to work with a pre trained model and extend it(a form of transfer learning). This appears to be mostly for images. My qs is .. is the idea being explored to use other models in this way ex for non image? many thanks rgds ajit

**Comment by petewarden** [comment] 2017-09-11 12:07
I am hoping to extend the simple speech recognition example here to use transfer learning:
https://www.tensorflow.org/versions/master/tutorials/audio_recognition

I have also been collaborating with Nic Lane (currently at UCL, but moving to Oxford next month) about getting some accelerometer models into TensorFlow, so I'd love to chat more about what's possible here.

**Comment by dsiot** [comment] 2017-09-11 16:54
This is great Peter, I am based in London but I teach in Oxford .. happy to sync up with Nic, Shall send more offline, thanks for your help and insights :)

**Comment by previ** [comment] 2017-10-04 12:25
@petewarden I am currently, and happily, using the pip package for rpi, both for retraining and using the model. Are there any plans on delivering a python 3 (3.4) tensorflow pip distribution? Thanks!

**Comment by petewarden** [comment] 2017-10-04 15:33
I've actually been experimenting with getting a Python3 version of the pip installation working. You can try the current version here:
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/

It's still a work in progress though, so I would expect some issues installing it, but let me know what errors you hit.

**Comment by previ** [comment] 2017-10-06 22:07
Installation went fine, but when:
```
>>> import tensorflow
```
I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dynamic module does not define init function (PyInit__pywrap_tensorflow_internal)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dynamic module does not define init function (PyInit__pywrap_tensorflow_internal)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ebrevdo** [comment] 2017-10-06 22:09
Can you try with python2?

**Comment by previ** [comment] 2017-10-06 22:10
python2 works.

**Comment by previ** [comment] 2017-10-06 22:13
To be more specific, during installation I got lots of warnings and messages like this:
```
    In file included from /usr/include/python3.4m/pyport.h:328:0,
                     from /usr/include/python3.4m/Python.h:50,
                     from numpy/core/src/umath/scalarmath.c.src:12:
    /usr/include/arm-linux-gnueabihf/bits/mathcalls.h:115:1: note: expected ‘long double *’ but argument is of type ‘npy_longdouble *’
     __MATHCALL (modf,, (_Mdouble_ __x, _Mdouble_ *__iptr)) __nonnull ((2));
     ^
    arm-linux-gnueabihf-gcc: numpy/core/src/umath/umathmodule.c
```
or
```
     int casinhl (void);
         ^
    _configtest.c:2:5: warning: conflicting types for built-in function ‘casinl’
```

**Comment by ebrevdo** [comment] 2017-10-06 22:25
I think that we just don't compile the blackberry build for python3 right
now.  We'd need to have separate builds; and probably pete warden is
looking into that now.

**Comment by petewarden** [comment] 2017-10-09 17:38
I am working on getting Python3 builds going, and you can see the latest versions here:
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero-python3/

These are still works-in-progress though.

**Comment by jaydeep95** [comment] 2017-10-11 08:43
@petewarden I read your tutorial related to GPU accelerated image processing on pi , but is there any possibilities of utilizing GPU for tensorflow classifcation? and if yes than how . Thanks for great article

**Comment by fnoop** [comment] 2017-11-01 22:23
It's been taking me about 2 days for each tensorflow raspberry build, thank you very much for this work :)

**Comment by tensorflowbutler** [comment] 2017-12-22 07:38
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:09
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:23
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2018-01-29 22:36
Closing this bug as fixed, since we now have fairly stable Raspberry Pi builds available from:

http://ci.tensorflow.org/view/Nightly/job/nightly-pi/
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero/
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero-python3/

**Closed by petewarden** 2018-01-29 22:36 UTC
Labels: type:build/install

**Comment by FlorinAndrei** [comment] 2018-02-02 20:21
@petewarden Assume you're new to TensorFlow. Look at the Install page on the main TF website https://www.tensorflow.org/install/ How would you figure out there is actually an officially supported release for RPi?

This issue was created in the hope that the RPi version would gain the same status as the other versions. This is not the case as of now. It seems to me like the definition of "fixed" is being stretched a little.

BTW, I do appreciate that binary builds are available. I'm just worried that they will eventually disappear if they are left in this second-class citizen status for too long.

**Comment by bennuttall** [comment] 2018-03-21 16:56
Hi - thanks for creating builds for Raspberry Pi - I'm from RPF and have a few questions:

- why are they tagged with the `any` platform rather than `linux_armv6l` and `linux_armv7l`?
- are you able to support the Python 3 version that ships with Raspbian, i.e. 3.5?

Also, I maintain the [piwheels](https://www.piwheels.org/) project (we build and host Armv6/7 wheels for Raspberry Pi of everything on PyPI - this) - would you be able to send new releases to me for inclusion on there? Alternatively we could build ourselves, like we do for opencv, provided the instructions are kept up-to-date.
