### ISSUE TITLE
how to apply quant to bert

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/tensorflow#30525] opened 2019-07-09 12:23 UTC
my bert is slow for prediction using cpu, can quant speed up its forward process? how to use?

**Comment by ravikyram** [comment] 2019-07-10 12:41
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by saberkun** [comment] 2019-07-12 04:21
Do you mean mobile cpu? You can try: https://www.tensorflow.org/lite/performance/post_training_quantization

For gpu, you can try to cast embedding variables to fp16 to enable full fp16 inference.

**Comment by ravikyram** [comment] 2019-07-17 05:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-17 05:44 UTC
Labels: stat:awaiting response, type:support
