### ISSUE TITLE
tflite AllocateTensors error after ResizeInputTensor

### ISSUE THREAD

**Issue by xhsoldier** [tensorflow/tensorflow#19610] opened 2018-05-29 07:57 UTC
OS Platform and Distribution: Android Native C, Android API 26
TensorFlow installed from: Compiled from the official github master branch
TensorFlow version: Master
Bazel versio: 0.13.0-homebrew
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Code below: 
```
int input = interpreter->inputs()[0];
//  TfLiteStatus status = interpreter->ResizeInputTensor(0, sizes);
  TfLiteStatus status = interpreter->ResizeInputTensor(input, sizes);

  if (interpreter->ResizeInputTensor(input, sizes) != kTfLiteOk) {
        exit(-1);
   }

  if (interpreter->AllocateTensors() != kTfLiteOk) {
      exit(-1);
  }
```
AllocateTensors errors after resize the InputTensor, any suggestions? I am using mobilenet_ssd.tflite model.

**Comment by tensorflowbutler** [comment] 2018-05-29 19:01
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xhsoldier** [comment] 2018-05-30 02:14
Re-edit the  question.

**Comment by tensorflowbutler** [comment] 2018-05-30 15:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-06-19 18:43
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-04 18:42
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-07-14 00:08
Please include the error message (see stderr or stdout). Also, you might try the nightly or master of Tensorflow lite (not 1.9), because some bugs have recently been repaired in AllocateTensors()

**Comment by tensorflowbutler** [comment] 2018-07-30 18:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by aselle** [comment] 2018-08-06 21:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2018-08-06 21:18 UTC
Labels: comp:lite, stat:awaiting response
