### ISSUE TITLE
Random slow downs during training.

### ISSUE THREAD

**Issue by chasep255** [tensorflow/tensorflow#2987] opened 2016-06-22 02:39 UTC
Usually the speed of each training batch is somewhat consistent for me when using tensorflow.  However, I am currently training an RNN.  For the first 3 epochs each batch of 128 samples took about 1 second.  Now on the third epoch my times have become inconsistent.  The batches will randomly become very slow.  I can hear the fan on my GTX Titian spin down indicating that during these slowdowns it is not using the compute resources on the GPU.  

I am timing it like this so I don't think anything else in my code could be affecting it.

```
            begin_time = time.time()
            loss, ts = sess.run([cost, train_step], feed_dict = {input_tensor: x_train, expected_output: y_train, keep_prob: 0.8})
            end_time = time.time()
```

Here is the output with timing information.

```
Epoch 3        Batch 858      Loss 172.072438250   Last Loss 206.985626221   Time 1.432 
Epoch 3        Batch 859      Loss 172.067967827   Last Loss 168.227874756   Time 1.419 
Epoch 3        Batch 860      Loss 172.057925642   Last Loss 163.421646118   Time 1.447 
Epoch 3        Batch 861      Loss 172.056937587   Last Loss 171.206222534   Time 1.339 
Epoch 3        Batch 862      Loss 172.051488565   Last Loss 167.354431152   Time 1.285 
Epoch 3        Batch 863      Loss 172.016926642   Last Loss 142.189987183   Time 1.310 
Epoch 3        Batch 864      Loss 172.011091517   Last Loss 166.969543457   Time 1.291 
Epoch 3        Batch 865      Loss 172.011779468   Last Loss 172.606857300   Time 1.317 
Epoch 3        Batch 866      Loss 172.004100742   Last Loss 165.354324341   Time 1.307 
Epoch 3        Batch 867      Loss 172.008801860   Last Loss 176.084671021   Time 1.372 
Epoch 3        Batch 868      Loss 172.032961320   Last Loss 193.003372192   Time 1.298 
Epoch 3        Batch 869      Loss 172.036121868   Last Loss 174.782638550   Time 1.310 
Epoch 3        Batch 870      Loss 172.044807513   Last Loss 179.601318359   Time 1.429 
Epoch 3        Batch 871      Loss 172.066208551   Last Loss 190.706512451   Time 1.311 
Epoch 3        Batch 872      Loss 172.052568940   Last Loss 160.158828735   Time 2.614 
Epoch 3        Batch 873      Loss 172.032694941   Last Loss 154.682693481   Time 2.208 
Epoch 3        Batch 874      Loss 172.040674805   Last Loss 179.015075684   Time 3.138 
Epoch 3        Batch 875      Loss 172.034015673   Last Loss 166.207275391   Time 1.750 
Epoch 3        Batch 876      Loss 172.029174909   Last Loss 167.788665771   Time 1.955 
Epoch 3        Batch 877      Loss 172.042762183   Last Loss 183.958801270   Time 2.576 
Epoch 3        Batch 878      Loss 172.028727179   Last Loss 159.705993652   Time 3.130 
Epoch 3        Batch 879      Loss 172.035255710   Last Loss 177.773834229   Time 2.622 
Epoch 3        Batch 880      Loss 172.043415273   Last Loss 179.223831177   Time 1.581 
Epoch 3        Batch 881      Loss 172.040243793   Last Loss 169.246170044   Time 3.093 
Epoch 3        Batch 882      Loss 172.017778805   Last Loss 152.203659058   Time 2.470 
Epoch 3        Batch 883      Loss 172.018503957   Last Loss 172.658813477   Time 2.540 
Epoch 3        Batch 884      Loss 172.054275064   Last Loss 203.675933838   Time 2.597 
Epoch 3        Batch 885      Loss 172.029123448   Last Loss 149.769943237   Time 2.915 
Epoch 3        Batch 886      Loss 172.013957027   Last Loss 158.576507568   Time 3.095 
Epoch 3        Batch 887      Loss 171.994215424   Last Loss 154.483413696   Time 2.250 
Epoch 3        Batch 888      Loss 171.998252946   Last Loss 175.583572388   Time 2.997 
Epoch 3        Batch 889      Loss 171.974352959   Last Loss 150.727264404   Time 3.417 
Epoch 3        Batch 890      Loss 171.968166587   Last Loss 166.462295532   Time 2.290 
Epoch 3        Batch 891      Loss 172.011782095   Last Loss 210.873199463   Time 1.358 
Epoch 3        Batch 892      Loss 172.013166695   Last Loss 173.248229980   Time 0.910 
Epoch 3        Batch 893      Loss 172.016952293   Last Loss 175.397491455   Time 0.893 
Epoch 3        Batch 894      Loss 172.015184030   Last Loss 170.434356689   Time 0.986 
Epoch 3        Batch 895      Loss 172.001527531   Last Loss 159.778961182   Time 1.000 
Epoch 3        Batch 896      Loss 172.008338426   Last Loss 178.110900879   Time 0.999 
Epoch 3        Batch 897      Loss 172.015577083   Last Loss 178.508651733   Time 1.699 
Epoch 3        Batch 898      Loss 172.076713689   Last Loss 226.977386475   Time 1.570 
Epoch 3        Batch 899      Loss 172.043461711   Last Loss 142.149932861   Time 1.699 
Epoch 3        Batch 900      Loss 172.069320933   Last Loss 195.342620850   Time 1.678 
Epoch 3        Batch 901      Loss 172.063626562   Last Loss 166.932998657   Time 1.685 
Epoch 3        Batch 902      Loss 172.060249506   Last Loss 169.014144897   Time 1.467 
Epoch 3        Batch 903      Loss 172.068654811   Last Loss 179.658645630   Time 3.737 
Epoch 3        Batch 904      Loss 172.061790508   Last Loss 165.856460571   Time 3.705 
Epoch 3        Batch 905      Loss 172.078748707   Last Loss 187.425918579   Time 3.376 
Epoch 3        Batch 906      Loss 172.065538518   Last Loss 160.097106934   Time 4.606 
Epoch 3        Batch 907      Loss 172.040349112   Last Loss 149.193557739   Time 4.513 
Epoch 3        Batch 908      Loss 172.078197416   Last Loss 206.444458008   Time 2.491 
Epoch 3        Batch 909      Loss 172.081030156   Last Loss 174.655990601   Time 4.244 
```

Here is what the output normally looks like most of the time when this issue is not occurring.

```
Epoch 1        Batch 213      Loss 262.820208541   Last Loss 189.761398315   Time 0.978 
Epoch 1        Batch 214      Loss 262.570083973   Last Loss 209.043426514   Time 0.984 
Epoch 1        Batch 215      Loss 262.265294534   Last Loss 196.735565186   Time 0.985 
Epoch 1        Batch 216      Loss 261.973181588   Last Loss 198.876785278   Time 0.988 
Epoch 1        Batch 217      Loss 261.685996729   Last Loss 199.366882324   Time 0.989 
Epoch 1        Batch 218      Loss 261.385472058   Last Loss 195.871093750   Time 0.981 
Epoch 1        Batch 219      Loss 261.200773135   Last Loss 220.751708984   Time 0.983 
Epoch 1        Batch 220      Loss 260.912834202   Last Loss 197.566268921   Time 0.982 
Epoch 1        Batch 221      Loss 260.757691254   Last Loss 226.471099854   Time 0.981 
Epoch 1        Batch 222      Loss 260.588221186   Last Loss 222.965866089   Time 0.984 
Epoch 1        Batch 223      Loss 260.272108146   Last Loss 189.778900146   Time 0.992 
Epoch 1        Batch 224      Loss 259.962260607   Last Loss 190.556411743   Time 0.981 
Epoch 1        Batch 225      Loss 259.509933337   Last Loss 157.736297607   Time 0.985 
Epoch 1        Batch 226      Loss 259.273305347   Last Loss 205.795379639   Time 0.982 
Epoch 1        Batch 227      Loss 259.062388972   Last Loss 211.184371948   Time 0.991 
Epoch 1        Batch 228      Loss 258.901376783   Last Loss 222.190597534   Time 0.984 
Epoch 1        Batch 229      Loss 258.643836975   Last Loss 199.667221069   Time 0.986 
Epoch 1        Batch 230      Loss 258.344224079   Last Loss 189.433258057   Time 0.979 

```

After a while it will make it through the slow phase and return to being 1s per batch.  I am using Ubuntu 16.04 with CUDNN 5 and Cuda 8.  This problem is intermittent and I have no real way to reproduce it.

**Comment by FangxiangFeng** [comment] 2016-06-23 06:06
I encountered the same problem.  
The log is as following:
2016-06-23 12:13:58.846196: step 2430, loss = 8.52 (460.8 examples/sec; 1.111 sec/batch)
2016-06-23 12:14:10.184638: step 2440, loss = 8.49 (474.2 examples/sec; 1.080 sec/batch)
2016-06-23 12:14:22.017317: step 2450, loss = 8.61 (457.5 examples/sec; 1.119 sec/batch)
2016-06-23 12:14:33.098411: step 2460, loss = 8.50 (462.9 examples/sec; 1.106 sec/batch)
2016-06-23 12:14:44.626485: step 2470, loss = 8.53 (463.6 examples/sec; 1.105 sec/batch)
2016-06-23 12:14:55.997127: step 2480, loss = 8.63 (469.0 examples/sec; 1.092 sec/batch)
2016-06-23 12:15:07.829877: step 2490, loss = 8.54 (447.0 examples/sec; 1.145 sec/batch)
2016-06-23 12:15:19.500701: step 2500, loss = 8.59 (336.6 examples/sec; 1.521 sec/batch)
2016-06-23 12:15:32.871750: step 2510, loss = 8.53 (471.3 examples/sec; 1.086 sec/batch)
2016-06-23 12:15:44.725588: step 2520, loss = 8.44 (478.0 examples/sec; 1.071 sec/batch)
2016-06-23 12:15:56.119878: step 2530, loss = 8.44 (477.7 examples/sec; 1.072 sec/batch)
2016-06-23 12:16:07.449835: step 2540, loss = 8.48 (396.2 examples/sec; 1.292 sec/batch)
2016-06-23 12:16:18.885702: step 2550, loss = 8.47 (438.6 examples/sec; 1.167 sec/batch)
2016-06-23 12:16:30.225739: step 2560, loss = 8.45 (483.1 examples/sec; 1.060 sec/batch)
2016-06-23 12:16:42.241132: step 2570, loss = 8.32 (445.8 examples/sec; 1.148 sec/batch)
2016-06-23 12:16:53.850374: step 2580, loss = 8.49 (453.8 examples/sec; 1.128 sec/batch)
2016-06-23 12:17:07.085051: step 2590, loss = 8.43 (290.5 examples/sec; 1.762 sec/batch)
2016-06-23 12:17:20.120950: step 2600, loss = 8.46 (256.8 examples/sec; 1.994 sec/batch)
2016-06-23 12:17:39.631906: step 2610, loss = 8.31 (241.3 examples/sec; 2.122 sec/batch)
2016-06-23 12:18:00.403822: step 2620, loss = 8.28 (279.3 examples/sec; 1.833 sec/batch)
2016-06-23 12:18:18.883428: step 2630, loss = 8.33 (306.9 examples/sec; 1.668 sec/batch)
2016-06-23 12:18:38.437799: step 2640, loss = 8.45 (265.5 examples/sec; 1.928 sec/batch)
2016-06-23 12:18:58.108157: step 2650, loss = 8.55 (260.9 examples/sec; 1.963 sec/batch)
2016-06-23 12:19:18.003289: step 2660, loss = 8.62 (362.8 examples/sec; 1.411 sec/batch)
2016-06-23 12:19:39.784456: step 2670, loss = 8.35 (192.5 examples/sec; 2.660 sec/batch)
2016-06-23 12:20:03.160854: step 2680, loss = 8.43 (244.8 examples/sec; 2.092 sec/batch)
2016-06-23 12:20:25.787582: step 2690, loss = 8.60 (216.9 examples/sec; 2.361 sec/batch)
2016-06-23 12:20:51.217995: step 2700, loss = 8.62 (182.7 examples/sec; 2.802 sec/batch)
2016-06-23 12:21:22.977688: step 2710, loss = 8.53 (154.7 examples/sec; 3.309 sec/batch)
2016-06-23 12:21:54.205844: step 2720, loss = 8.54 (142.1 examples/sec; 3.604 sec/batch)
2016-06-23 12:22:23.399541: step 2730, loss = 8.42 (193.0 examples/sec; 2.653 sec/batch)
2016-06-23 12:23:00.475763: step 2740, loss = 8.28 (186.7 examples/sec; 2.743 sec/batch)
2016-06-23 12:23:29.253763: step 2750, loss = 8.38 (167.2 examples/sec; 3.062 sec/batch)
2016-06-23 12:23:56.726199: step 2760, loss = 8.61 (197.4 examples/sec; 2.594 sec/batch)
2016-06-23 12:24:26.043562: step 2770, loss = 8.51 (144.0 examples/sec; 3.555 sec/batch)

Both the status of CPU and IO are normal. It can be reproduced in my machine.

**Comment by chasep255** [comment] 2016-06-23 12:11
I switched my aggregation method in my optimizer from EXPIRMENTAL_TREE to EXPERIMENTAL_ACCUMULATE_N.  I have not seen the issue since but I am not sure if I have fixed it since it is intermittent and I have not done much training since making that change.

**Comment by andydavis1** [comment] 2016-06-27 18:20
Can you please follow the steps referenced in this github issue to produce a timeline which shows the slowdown?: https://github.com/tensorflow/tensorflow/issues/3009

**Comment by FangxiangFeng** [comment] 2016-06-28 07:23
I produced the timeline which shows the same situation with #3009 . The operation "QueueDequeueMany" takes a long time and a lot of virtual memory are allocated.

**Comment by andydavis1** [comment] 2016-06-28 15:53
@chasep255 Are you also seing the slow operation as "DequeMany"? If so, I may mark this as a duplicate of #3009

**Comment by chasep255** [comment] 2016-06-28 16:21
I did not run any tests.  I have not encountered the issue again since 
positing about this problem.  I think it has to do with the 
EXPERIMENTAL_TREE aggregation method since it went away one I stopped 
using this.

**Comment by andydavis1** [comment] 2016-06-28 16:57
Ok thanks. I'll close this issue out. It looks like @FangxiangFeng's issue may be an instance of #3009.

**Closed by andydavis1** 2016-06-28 16:57 UTC
Labels: awaiting response, triaged

**Comment by rohitgirdhar** [comment] 2016-07-24 03:45
I'm facing the same problem. I'm running the inception model finetuning on my data. Here's a part of the log being printed. I'm using all TensorFlow data read operations (so no copy from numpy to TF, as I'm not using DequeueMany manually, but through shuffle_batch_join). I'll try to provide the timeline when I have a chance to re-run the training. The machine resources otherwise seem fine (CPU/memory is not choked, the prefetch queues logs show >70% full) 
```txt
2016-07-23 14:34:15.784645: step 2720, loss = 2.63 (68.5 examples/sec; 3.740 sec/batch)                                                                                                                                                                                                                                                                         [224/1046]
2016-07-23 14:34:54.449992: step 2730, loss = 2.23 (65.7 examples/sec; 3.897 sec/batch)
2016-07-23 14:35:30.115364: step 2740, loss = 2.11 (66.2 examples/sec; 3.867 sec/batch)
2016-07-23 14:36:06.048820: step 2750, loss = 2.14 (64.8 examples/sec; 3.953 sec/batch)
2016-07-23 14:36:43.302534: step 2760, loss = 2.18 (71.4 examples/sec; 3.585 sec/batch)
2016-07-23 14:37:21.960443: step 2770, loss = 2.26 (74.2 examples/sec; 3.451 sec/batch)
2016-07-23 14:37:59.039025: step 2780, loss = 2.04 (67.2 examples/sec; 3.808 sec/batch)
2016-07-23 14:38:39.144252: step 2790, loss = 2.45 (59.2 examples/sec; 4.321 sec/batch)
2016-07-23 14:39:17.613073: step 2800, loss = 2.18 (81.0 examples/sec; 3.162 sec/batch)
2016-07-23 14:39:56.705607: step 2810, loss = 2.55 (66.5 examples/sec; 3.847 sec/batch)
2016-07-23 14:40:32.612656: step 2820, loss = 2.38 (78.8 examples/sec; 3.247 sec/batch)
2016-07-23 14:41:09.194193: step 2830, loss = 2.47 (67.1 examples/sec; 3.814 sec/batch)
2016-07-23 14:41:44.523209: step 2840, loss = 2.30 (77.5 examples/sec; 3.303 sec/batch)
2016-07-23 14:42:21.437528: step 2850, loss = 2.27 (64.8 examples/sec; 3.949 sec/batch)
2016-07-23 14:42:55.936083: step 2860, loss = 2.22 (80.3 examples/sec; 3.189 sec/batch)
2016-07-23 14:43:32.151591: step 2870, loss = 2.35 (60.1 examples/sec; 4.259 sec/batch)
2016-07-23 14:44:07.513355: step 2880, loss = 2.38 (65.1 examples/sec; 3.931 sec/batch)
2016-07-23 14:44:42.496976: step 2890, loss = 1.99 (67.7 examples/sec; 3.781 sec/batch)
2016-07-23 14:45:20.375483: step 2900, loss = 2.67 (50.2 examples/sec; 5.100 sec/batch)
2016-07-23 14:46:00.563096: step 2910, loss = 2.23 (62.5 examples/sec; 4.093 sec/batch)
2016-07-23 14:46:39.610138: step 2920, loss = 2.19 (80.1 examples/sec; 3.197 sec/batch)
2016-07-23 14:47:19.147337: step 2930, loss = 2.31 (51.6 examples/sec; 4.957 sec/batch)
2016-07-23 14:48:03.449487: step 2940, loss = 2.27 (50.8 examples/sec; 5.041 sec/batch)
2016-07-23 14:48:47.893646: step 2950, loss = 2.29 (52.0 examples/sec; 4.919 sec/batch)
2016-07-23 14:49:27.023626: step 2960, loss = 2.27 (73.7 examples/sec; 3.475 sec/batch)
2016-07-23 14:50:11.125284: step 2970, loss = 2.08 (65.4 examples/sec; 3.914 sec/batch)
2016-07-23 14:50:51.295322: step 2980, loss = 2.19 (50.7 examples/sec; 5.053 sec/batch)
2016-07-23 14:51:33.655334: step 2990, loss = 2.30 (66.0 examples/sec; 3.879 sec/batch)
2016-07-23 14:52:10.323608: step 3000, loss = 2.25 (68.8 examples/sec; 3.723 sec/batch)
2016-07-23 14:52:52.609913: step 3010, loss = 2.04 (64.8 examples/sec; 3.949 sec/batch)
2016-07-23 14:53:31.631134: step 3020, loss = 2.31 (54.5 examples/sec; 4.696 sec/batch)
2016-07-23 14:54:13.547641: step 3030, loss = 2.33 (55.1 examples/sec; 4.643 sec/batch)
2016-07-23 14:55:00.528403: step 3040, loss = 2.29 (49.1 examples/sec; 5.217 sec/batch)
2016-07-23 14:55:45.258737: step 3050, loss = 2.17 (51.4 examples/sec; 4.979 sec/batch)
2016-07-23 14:56:31.159313: step 3060, loss = 2.29 (51.5 examples/sec; 4.968 sec/batch)
2016-07-23 14:57:15.148195: step 3070, loss = 2.27 (51.8 examples/sec; 4.946 sec/batch)
2016-07-23 14:57:54.451044: step 3080, loss = 2.40 (68.8 examples/sec; 3.724 sec/batch)
2016-07-23 14:58:32.325357: step 3090, loss = 1.93 (58.4 examples/sec; 4.380 sec/batch)
2016-07-23 14:59:06.746820: step 3100, loss = 2.02 (88.0 examples/sec; 2.910 sec/batch)
2016-07-23 14:59:39.746600: step 3110, loss = 2.20 (86.2 examples/sec; 2.970 sec/batch)
2016-07-23 15:00:10.409635: step 3120, loss = 2.19 (79.7 examples/sec; 3.213 sec/batch)
2016-07-23 15:00:41.756720: step 3130, loss = 2.28 (83.6 examples/sec; 3.062 sec/batch)
2016-07-23 15:01:12.757209: step 3140, loss = 2.26 (85.6 examples/sec; 2.989 sec/batch)
2016-07-23 15:01:43.993791: step 3150, loss = 2.23 (79.6 examples/sec; 3.214 sec/batch)
2016-07-23 15:02:15.348264: step 3160, loss = 2.04 (82.8 examples/sec; 3.090 sec/batch)
2016-07-23 15:02:46.752311: step 3170, loss = 2.26 (83.7 examples/sec; 3.058 sec/batch)
2016-07-23 15:03:18.581683: step 3180, loss = 1.92 (78.9 examples/sec; 3.243 sec/batch)
2016-07-23 15:03:50.599771: step 3190, loss = 2.38 (80.9 examples/sec; 3.166 sec/batch)
2016-07-23 15:04:22.723497: step 3200, loss = 2.00 (78.4 examples/sec; 3.266 sec/batch)
2016-07-23 15:05:16.565673: step 3210, loss = 1.99 (25.1 examples/sec; 10.188 sec/batch)
2016-07-23 15:06:37.336032: step 3220, loss = 2.34 (28.4 examples/sec; 9.013 sec/batch)
2016-07-23 15:08:03.531096: step 3230, loss = 2.10 (26.1 examples/sec; 9.817 sec/batch)
2016-07-23 15:09:26.177609: step 3240, loss = 2.34 (29.7 examples/sec; 8.613 sec/batch)
2016-07-23 15:10:48.697512: step 3250, loss = 2.06 (25.0 examples/sec; 10.229 sec/batch)
2016-07-23 15:12:14.720998: step 3260, loss = 2.16 (26.0 examples/sec; 9.861 sec/batch)
2016-07-23 15:13:42.700315: step 3270, loss = 2.06 (25.6 examples/sec; 10.000 sec/batch)
2016-07-23 15:15:07.717132: step 3280, loss = 2.00 (26.9 examples/sec; 9.524 sec/batch)
2016-07-23 15:16:29.206475: step 3290, loss = 2.15 (71.1 examples/sec; 3.600 sec/batch)
2016-07-23 15:17:56.483761: step 3300, loss = 2.17 (25.3 examples/sec; 10.102 sec/batch)
2016-07-23 15:19:32.355597: step 3310, loss = 2.26 (24.7 examples/sec; 10.352 sec/batch)
2016-07-23 15:20:58.064109: step 3320, loss = 2.18 (25.8 examples/sec; 9.907 sec/batch)
2016-07-23 15:22:18.608871: step 3330, loss = 2.02 (27.9 examples/sec; 9.183 sec/batch)
2016-07-23 15:23:39.227969: step 3340, loss = 2.17 (26.8 examples/sec; 9.567 sec/batch)
2016-07-23 15:25:03.643470: step 3350, loss = 2.01 (25.7 examples/sec; 9.976 sec/batch)
2016-07-23 15:26:25.196536: step 3360, loss = 2.08 (33.1 examples/sec; 7.728 sec/batch)
2016-07-23 15:27:50.458838: step 3370, loss = 2.01 (26.9 examples/sec; 9.533 sec/batch)
2016-07-23 15:29:12.861687: step 3380, loss = 2.07 (66.9 examples/sec; 3.827 sec/batch)
2016-07-23 15:30:31.386601: step 3390, loss = 1.95 (71.9 examples/sec; 3.559 sec/batch)
2016-07-23 15:31:58.734378: step 3400, loss = 2.37 (25.6 examples/sec; 10.011 sec/batch)
2016-07-23 15:33:33.894047: step 3410, loss = 2.06 (26.7 examples/sec; 9.581 sec/batch)
2016-07-23 15:34:54.087397: step 3420, loss = 1.99 (27.5 examples/sec; 9.311 sec/batch)
2016-07-23 15:36:11.707716: step 3430, loss = 2.15 (69.0 examples/sec; 3.710 sec/batch)
2016-07-23 15:37:31.881528: step 3440, loss = 2.20 (46.0 examples/sec; 5.570 sec/batch)
2016-07-23 15:38:55.509458: step 3450, loss = 2.08 (25.5 examples/sec; 10.041 sec/batch)
2016-07-23 15:40:16.870401: step 3460, loss = 2.35 (26.5 examples/sec; 9.647 sec/batch)
2016-07-23 15:41:40.889863: step 3470, loss = 2.23 (27.3 examples/sec; 9.389 sec/batch)
2016-07-23 15:43:06.156092: step 3480, loss = 2.08 (27.3 examples/sec; 9.385 sec/batch)
2016-07-23 15:44:25.849125: step 3490, loss = 2.04 (65.0 examples/sec; 3.939 sec/batch)
2016-07-23 15:45:46.423841: step 3500, loss = 2.04 (55.5 examples/sec; 4.616 sec/batch)
2016-07-23 15:47:24.597796: step 3510, loss = 2.13 (25.8 examples/sec; 9.938 sec/batch)
2016-07-23 15:48:50.303574: step 3520, loss = 1.99 (25.7 examples/sec; 9.968 sec/batch)
2016-07-23 15:50:13.826881: step 3530, loss = 2.03 (31.7 examples/sec; 8.069 sec/batch)
2016-07-23 15:51:27.094435: step 3540, loss = 1.93 (63.6 examples/sec; 4.026 sec/batch)
2016-07-23 15:52:46.522184: step 3550, loss = 2.13 (70.3 examples/sec; 3.639 sec/batch)
2016-07-23 15:54:10.492599: step 3560, loss = 2.17 (25.6 examples/sec; 10.000 sec/batch)
2016-07-23 15:55:32.567000: step 3570, loss = 1.93 (27.0 examples/sec; 9.465 sec/batch)
2016-07-23 15:56:58.073701: step 3580, loss = 2.21 (25.5 examples/sec; 10.058 sec/batch)
2016-07-23 15:58:21.894001: step 3590, loss = 2.14 (31.5 examples/sec; 8.129 sec/batch)
```

**Comment by jstaker7** [comment] 2016-09-14 23:23
Just to add my 2 cents; I'm running into a similar issue. My setup includes 4 Titan X GPUs and plenty of CPU/RAM. I'm training two models at a time (each using two GPUs). One model has been training for a long time with consistent times per step. I then start up the second model and things look good for about 1500-3000 steps and both models have consistent training times per step. After a while both models slow down considerably with sporadic training times. I then kill my second model and the first one goes back to fast, consistent time per step. Can't figure out what the problem is, and both my CPU and RAM are not fully utilized.

**Comment by yaroslavvb** [comment] 2016-09-14 23:35
There was similar sounding issue here
<https://github.com/tensorflow/tensorflow/issues/3009#issuecomment-236260459>
Can you see if enabling tcmalloc
<http://goog-perftools.sourceforge.net/doc/tcmalloc.html> solves it?

**Comment by jstaker7** [comment] 2016-09-15 19:07
Update: Tried clearing the cache and that didn't help (didn't appear to be under pressure anyway). Also, I noticed that CPU usage starts at ~8% when the second model gets started, but gradually climbs to about 50%, at which time training drastically slows down for both cases. Not sure why CPU usage would increase overtime like that with a second model running, and why there would be a slow down at only 50% load. Killing the second model brings the load back down to 8%.

**Comment by jph00** [comment] 2017-01-21 14:36
@jstaker7 I'm having the exact same problem. None of the suggestions in linked threads are helping. Did you find a solution?

**Comment by yaroslavvb** [comment] 2017-01-21 17:08
Can you try running under tf 1.0 alpha? (I believe it uses jemalloc which
can help)

**Comment by jph00** [comment] 2017-01-21 20:51
Sure I'll try that.

**Comment by adler-j** [comment] 2018-01-18 10:11
Was this ever truly resolved? I'm observing the same problem. Training slows down linearly with time to the point of it basically becoming impossible to use tensorflow.

**Comment by yaroslavvb** [comment] 2018-01-18 17:35
It was resolved. Perhaps you didn't finalize the graph
