### ISSUE TITLE
Add more information about eager/graph context for Keras layer.call()

### ISSUE THREAD

**Issue by qlzh727** [tensorflow/tensorflow#36757] opened 2020-02-14 18:31 UTC
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#call

### Clear description

This is a key function that user will implement with they custom layer. Currently it is poorly documented, especially w.r.t the execution context of eager/graph. In TF 2.0, we are advocating eager execution by default. However, the call() body in keras is executed with graph context by default unless configured otherwise. It will raise error if user try to add print/debug related to items into the call body, eg print(eager_tensor.numpy()), etc.

Some related question raised in  https://github.com/tensorflow/tensorflow/issues/27519.

### Correct links

Yes

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

Yes

### Usage example

No

### Request visuals, if applicable

No

### Submit a pull request?
No

**Comment by qlzh727** [comment] 2020-02-14 18:33
Just FYI, keras-team is working on some documents that clearly defines the API contract for all the important interfaces for Keras, and we will update the docs related very soon.

**Comment by qlzh727** [comment] 2020-03-16 15:55
I think #37574 only cover part of the functionnality for call(), and the major part for eager/graph context is not covered yet.

**Comment by adelcast** [comment] 2020-04-06 03:03
Any pointers on the proper way to enable eager execution on layer.call()? I hit this issue converting a model that uses a custom layer to tflite. The conversion fails since the custom layer call function is not being executed eagerly (tf.executing_eagerly() is returning False). I have been looking around on the documentation, and just can't find how to force my custom layer to use eager mode...

**Comment by qlzh727** [comment] 2020-04-06 16:57
@adelcast, to run the layer.call() body in eager context, you need to invoke model.compile(run_eagerly=True). Note that this will have performance slow down due to eager runtime, and should only used for debug purpose.

**Comment by bhack** [comment] 2021-04-16 13:46
@qlzh727 Do we want to close this or are we waiting for a contribution?

**Comment by jvishnuvardhan** [comment] 2021-06-12 01:31
Though the TF webpage doesn't show the recent updates, I think this was resolved in the `master` branch. The description is much more clear now. I added a PR to add description about running in eager mode as described in https://github.com/tensorflow/tensorflow/issues/36757#issuecomment-609914819. Thanks

**Comment by tensorflowbutler** [comment] 2021-12-14 23:12
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Closed** 2022-01-11 17:47 UTC
Labels: type:docs-bug, stat:awaiting tensorflower, comp:keras, TF 2.1
