### ISSUE TITLE
ValueError: Column dtype and SparseTensors dtype must be compatible. key: adt_sev_flag, column dtype: <dtype: 'int64'>, tensor dtype: <dtype: 'float32'>

### ISSUE THREAD

**Issue by WakerKQ** [tensorflow/tensorflow#35443] opened 2019-12-27 08:35 UTC
I use TF1.14 ane keras 2.2.4 , code and error is :

from future import absolute_import, division, print_function

import numpy as np
import pandas as pd
from tensorflow import feature_column
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

def df_to_dataset(dataframe, shuffle=True, batch_size=32):
dataframe = dataframe.copy()
labels = dataframe.pop('target')
ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
if shuffle:
ds = ds.shuffle(buffer_size=len(dataframe))
ds = ds.batch(batch_size)
return ds

batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

age = feature_column.numeric_column("age")
feature_columns = []
feature_layer_inputs = {}

for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
feature_columns.append(feature_column.numeric_column(header))
feature_layer_inputs[header] = tf.keras.Input(shape=(1,), name=header)

age_buckets = feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
feature_columns.append(age_buckets)

thal = feature_column.categorical_column_with_vocabulary_list(
'thal', ['fixed', 'normal', 'reversible'])
thal_one_hot = feature_column.indicator_column(thal)
feature_columns.append(thal_one_hot)
feature_layer_inputs['thal'] = tf.keras.Input(shape=(1,), name='thal', dtype=tf.string)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)
batch_size = 100 # 小批量大小用于演示
epoch = 10
steps_per_epoch =  len(train)//(batch_size*epoch)
val_steps = len(val)//batch_size
model.fit(train_ds, epochs = epoch, steps_per_epoch=steps_per_epoch, validation_data=val_ds,validation_steps=10)

output the error:

----> 2 model.fit(train_ds, epochs = epoch, steps_per_epoch=steps_per_epoch, validation_data=val_ds,validation_steps=10)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    707         steps=steps_per_epoch,
    708         validation_split=validation_split,
--> 709         shuffle=shuffle)
    710 
    711     # Prepare validation data.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2556       else:
   2557         cast_inputs = x_input
-> 2558       self._set_inputs(cast_inputs)
   2559     else:
   2560       y_input = y

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _set_inputs(self, inputs, outputs, training)
   2774       kwargs = {'training': training} if self._expects_training_arg else {}
   2775       try:
-> 2776         outputs = self(inputs, **kwargs)
   2777       except NotImplementedError:
   2778         # This Model or a submodel is dynamic and hasn't overridden

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    632                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    633                 else:
--> 634                   outputs = call_fn(inputs, *args, **kwargs)
    635 
    636             except TypeError as e:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py in call(self, inputs, training, mask)
    259         kwargs['training'] = training
    260 
--> 261       outputs = layer(inputs, **kwargs)
    262 
    263       # `outputs` will be the inputs to the next layer.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    632                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    633                 else:
--> 634                   outputs = call_fn(inputs, *args, **kwargs)
    635 
    636             except TypeError as e:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    147       except Exception as e:  # pylint:disable=broad-except
    148         if hasattr(e, 'ag_error_metadata'):
--> 149           raise e.ag_error_metadata.to_exception(type(e))
    150         else:
    151           raise

ValueError: in converted code:
    relative to /opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column:

    feature_column_v2.py:473 call *
        tensor = column.get_dense_tensor(transformation_cache,
    feature_column_v2.py:4291 get_dense_tensor
        return transformation_cache.get(self, state_manager)
    feature_column_v2.py:2562 get
        transformed = column.transform_feature(self, state_manager)
    feature_column_v2.py:4230 transform_feature
        transformation_cache, state_manager)
    feature_column_v2.py:3710 get_sparse_tensors
        transformation_cache.get(self, state_manager), None)
    feature_column_v2.py:2562 get
        transformed = column.transform_feature(self, state_manager)
    feature_column_v2.py:3688 transform_feature
        return self._transform_input_tensor(input_tensor)
    feature_column_v2.py:3664 _transform_input_tensor
        self.key, self.dtype, input_tensor.dtype))

    ValueError: Column dtype and SparseTensors dtype must be compatible. key: adt_sev_flag, column dtype: <dtype: 'int64'>, tensor dtype: <dtype: 'float32'>

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by gadagashwini** [comment] 2019-12-30 05:05
@WakerKQ, Looks like provided code is incomplete, `model is not defined`. Could you provide the complete code to reproduce the reported issue. Thanks!

**Comment by WakerKQ** [comment] 2020-01-03 03:46
> @WakerKQ, Looks like provided code is incomplete, `model is not defined`. Could you provide the complete code to reproduce the reported issue. Thanks!
thanks for replying!  model is defined as :
model = tf.keras.Sequential([
  feature_layer,
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dense(1024, activation=tf.nn.relu),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(256, activation=tf.nn.relu),
  tf.keras.layers.Dense(128, activation=tf.nn.relu),
  tf.keras.layers.Dense(64, activation=tf.nn.relu),
  tf.keras.layers.Dense(32, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.categorical_crossentropy,
              metrics=['accuracy'])

**Comment by gadagashwini** [comment] 2020-01-10 08:05
@WakerKQ, I tried with Tf 1.15 I am facing different error. Please find the [gist](https://colab.sandbox.google.com/gist/gadagashwini/18482e7e8aeb3a573eceb05cb44e1845/untitled342.ipynb) and confirm. Thanks!

**Comment by gadagashwini** [comment] 2020-01-20 13:47
@WakerKQ, Did you get a chance to look at gist. Thanks!

**Comment by gadagashwini** [comment] 2020-01-29 08:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-01-29 08:28 UTC
Labels: TF 1.14, stat:awaiting response
