### ISSUE TITLE
[TF] `tf.image.resize_with_crop_or_pad` constfolding issue with variable batch size.

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#57898] opened 2022-09-28 21:12 UTC
### TF Version
TF 2.10

## Gist of the issue

Similar problem was found with `tf.image.resize_with_crop_or_pad` as reported in https://github.com/keras-team/keras/issues/17094 and https://github.com/tensorflow/tensorflow/issues/57853.

Long story short `tf.image.resize_with_crop_or_pad` does not behave the same when batch_size is fixed (e.g. batch_size=32) and when it's variable (e.g. batch_size=None). The problem seems to reside in the way `constant_folding` is working or in the way `height` and `width` are managed.

## Google Colab for Repro

Full repro case in detail: https://colab.research.google.com/drive/1JlGYCiD-oDwXBaumxoLfZqUSj_KbXuUE?usp=sharing

### 1. Let's create the model

Picture the most basic model using `Conv2DTranspose`

```python
def create_model(batch_size=None):
  inputs = keras.layers.Input((128, 128, 3), dtype=tf.float32, batch_size=batch_size)

  net = tf.image.resize_with_crop_or_pad(inputs, 100, 100)
  net = keras.layers.Conv2D(filters=32, kernel_size=(3, 3))(net)

  model = keras.models.Model(inputs=inputs, outputs=net)
  return model
```

**Fixed BS:**
![image](https://user-images.githubusercontent.com/10923599/192889217-dde657b8-7b78-49e4-8fea-e3cdc3d2538f.png)

**Variable BS:**
![image](https://user-images.githubusercontent.com/10923599/192889268-6e12d5ae-a99a-48b8-8405-3fc2662f6418.png)

So far so good, everything looks the same ...

### 2. Freeze + ConstFold + Plot

Now let's freeze the graph and plot the resulting graphdef:

**Fixed BS:**
![image](https://user-images.githubusercontent.com/10923599/192889358-cc87a30f-bb7b-4e67-9bc8-eb274768af03.png)

**Variable BS:**
![image](https://user-images.githubusercontent.com/10923599/192889315-b9a932c3-8a1e-4c58-878f-fd517ddfd708.png)

## Conclusion

I hope the difference is fairly self explanatory, and that's a problem because that's a very different graph for inference and a lot more complicated graph to optimize by compilers (e.g. TF-TRT, XLA, TF Lite, TVM, etc).

Anything upstream of the `Slice` OP  **should** have been const folded, it's perfectly independent of input batch size. There's no reason to the best of my knowledge that the const folding behavior changes by changing the BS value. 

My guess is that the shape tensor is seen as variable because of one value being None, however the None dimension is not being used and therefore the slice of the Shape tensor is perfectly static in this case and should have been const folded.

## To go further

It should not be runtime computed when the shapes are perfectly static, we should not need to constfold this graph in the first place. This could be perfectly computed in python when all the shapes are defined. This is very expensive to compute over and over at each iteration even in training.

A very similar issue was fixed with a different layer here, we should consider a similar fix here: https://github.com/tensorflow/tensorflow/pull/31450/files

**Comment by tilakrayal** [comment] 2022-09-29 11:47
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/3cbeabdcdacba300fbbf599c31b80d68/2-8.ipynb), [v2.10](https://colab.research.google.com/gist/tilakrayal/53a0e63f1aafa5e86b1e3f969808962c/2-10.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/30c8b77b7093e008048c19f4379dacfb/2-11.ipynb). Kindly find the gist of it here.

**Comment by sachinprasadhs** [comment] 2022-12-06 20:09
@DEKHTIARJonathan , Could you please refer the comment here https://github.com/keras-team/keras/issues/17094#issuecomment-1284609390, as per the comment if you feel this needs to be addressed in XLA with additional logic, we can keep this issue open and close the Keras issue since it does not have dependency on Keras. Thanks!

**Closed** 2022-12-20 21:12 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.10
