### ISSUE TITLE
Windows 7: No module named '_pywrap_tensorflow'

### ISSUE THREAD

**Issue by Jacorr** [tensorflow/tensorflow#9167] opened 2017-04-12 14:48 UTC
My problem is with import TF module. Here is my configuration: Python 3.6.1, Windows 7 64-bit. I've MSVCP140.dll library in 'C:\Windows\System32\' and 'C:\Windows\SysWOW64\' folders. I also have instaled Update 3 for VS2015 C++.

In Windows PATH varitable I have such value related to python:
C:\Users\Jacek\AppData\Local\Programs\Python\Python36\Scripts\
C:\Users\Jacek\AppData\Local\Programs\Python\Python36\

Steps which I made:

I've installed TensorFlow by command (in power shell). It works.

`python -m pip install --upgrade tensorflow`
But when I run python environment and try import Tensor Flow

`import tensorflow as tf`
I get errors, this error raise another errors related with it, but at the beginning I want to resolve this first

> Traceback (most recent call last): File "C:\Users\Jacek\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(file)]) File "C:\Users\Jacek\AppData\Local\Programs\Python\Python36\lib\imp.py", line 296, in find_module raise ImportError(_ERR_MSG.format(name), name=name) ImportError: No module named '_pywrap_tensorflow'

**Comment by Carmezim** [comment] 2017-04-12 16:01
Python 3.6 is not supported on Windows, see #6999

**Comment by mrry** [comment] 2017-04-12 17:00
Thanks @Carmezim for being helpful as always! I'm closing this as a duplicate of #6999... feel free to chime in to the discussion there.

**Closed by mrry** 2017-04-12 17:00 UTC

**Comment by Carmezim** [comment] 2017-04-12 17:17
@mrry Always glad to help :)

**Comment by Jacorr** [comment] 2017-04-13 06:21
You are great. Now it working.

@Carmezim @mrry : I wonder if in such case there should should be message "Your Python version is not supported, please downgrade for X.X.X". Then you could avoid questions like mine.

Thank you,

**Comment by Carmezim** [comment] 2017-04-13 12:37
@Jacorr Glad it is working now :) 
This situation of the vague error messages is being addressed in #9170 and hopefully soon as you suggested more descriptive logs will be in place to provide more clarity and avoid confusion.
Thank you for opening the issue and feel free to ask further questions.

**Comment by mrry** [comment] 2017-05-31 16:30
For users who find this issue when searching for the error message, I've created a script for diagnosing common TensorFlow on Windows installation issues. Please download the script from https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c and run `python tensorflow_self_check.py`. It will print suggestions for how to fix your installation. Let me know if you are still facing problems after running the script.
