### ISSUE TITLE
error：Library objects cannot exceed 65,536，win10 + TensorFlowGPU 

### ISSUE THREAD

**Issue by EdwardVincentMa** [tensorflow/tensorflow#19743] opened 2018-06-04 09:43 UTC
**System information:**
· Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No

· OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Win10-x64

· TensorFlow installed from (source or binary): git clone https://github.com/tensorflow/tensorflow.git

· TensorFlow version (use command below):  r1.4, r1.5, r1.6  r1.7 and r1.8,  command : 
v1.8's command : git checkout -b v1.8 -f origin/r1.8
v1.7's command : git checkout -b v1.7 -f origin/r1.7
v1.6's command : git checkout -b v1.6 -f origin/r1.6
and so on include v1.4 and v1.5

· Python version:  Anaconda3 - python3.6

· Bazel version (if compiling from source):  I used CMAKE 3.11.1

· GCC/Compiler version (if compiling from source):  Visual Studio 2015( VS15' MSBuild)

· CUDA/cuDNN version:  CUDA9.0,   cudnn-9.0-win10-7.1

· GPU model and memory: GTX-860m with 2Gb Memory

Exact command to reproduce: 
"
D:\ProgramData\tensorflow\tensorflow\contrib\cmake\build> cmake .. -A x64 -DCMAKE_BUILD_TYPE=Debug -DSWIG_EXECUTABLE=D:/soft/TensorflowSoft/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE=D:/ProgramData/Anaconda3/python.exe -DPYTHON_LIBRARIES=D:/ProgramData/Anaconda3/libs/python36.lib -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="D:\soft\TensorflowSoft\cudnn" -G "Visual Studio 14 2015"

D:\ProgramData\tensorflow\tensorflow\contrib\cmake\build> set PreferredToolArchitecture=x64 

D:\ProgramData\tensorflow\tensorflow\contrib\cmake\build> MSBuild /p:Configuration=Release ALL_BUILD.vcxproj
"

**Describe the problem** : 
I build TensorFlow-CPU-r1.8 successfully (win10-x64 + Anaconda3-python3.6 + **VS2017**(not VS2015) +  tensorflow1.8 + cmake3.11.1 + SwigWin3.0.12).
 
But when I build tensorflow-**GPU** version(both tensorflow-r1.7 and r1.8), the only error has occurred: The library objects cannot exceed 65,536. (If I use VS2017, it shows error: " the compiler is not supported for CUDA 9.0" , so I switch Visual Studio version to VS2015, and CMAKE command is work successfully.)

After that, I switched to lower versions TensorFlow-r1.6 to TensorFlow-r1.5, but Link error occurred：

“libprotobufd.lib(text_format.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_8 referenced in function "void _
_cdecl std::_Reverse_unchecked1<class google::protobuf::Message const * *>(class google::protobuf::Message const * * const,class google::protobuf:
:Message const * * const,struct std::integral_constant<unsigned __int64,8>)" (??$_Reverse_unchecked1@PEAPEBVMessage@protobuf@google@@@std@@YAXQEAP
EBVMessage@protobuf@google@@0U?$integral_constant@_K$07@0@@Z) [D:\tf\tensorflowGPU\tensorflow\contrib\cmake\build\proto_text.vcxproj]
  libprotobufd.lib(wire_format.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [D:\tf\tensorflowGPU\tensorflo
w\contrib\cmake\build\proto_text.vcxproj]
  D:\tf\tensorflowGPU\tensorflow\contrib\cmake\build\Debug\proto_text.exe : fatal error LNK1120: 1 unresolved externals [D:\tf\tensorflowGPU\tenso
rflow\contrib\cmake\build\proto_text.vcxproj]”

I don't know how to solve those errors...

**Comment by tensorflowbutler** [comment] 2018-06-04 19:38
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by EdwardVincentMa** [comment] 2018-06-05 02:14
I have updated my issue, @tensorflowbutler , and thank you very much for helping me !

**Comment by mrry** [comment] 2018-06-14 23:35
Marking this as community support, because we don't support debug builds on Windows.

/CC @gunan, who was looking at the symbol limit recently, and may have some suggestions.

**Closed** 2018-09-02 14:51 UTC
Labels: stat:community support
