### ISSUE TITLE
LSTM model can not save via SavedModel

### ISSUE THREAD

**Issue by grewe** [tensorflow/tensorflow#34019] opened 2019-11-05 20:48 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Microsoft Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  
- TensorFlow version (use command below):2.0
- Python version:  3.6.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When attempt from python using tf.keras LSTM model to create a SavedModel get error  (first load model from h5 file first)
ValueError: Model <tensorflow.python.keras.engine.sequential.Sequential object at 0x000001F7676BDEF0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).

**Describe the expected behavior**
To be able to create SavedModel directory
**Code to reproduce the issue**

`# Save the entire model as a SavedModel.
BASE_DATA_PATH = 'C:\Grewe\Classes\CS663\Mat\LSTM\data'  

#load the previously saved h5 model
# try to reload the saved h5 file
# Recreate the exact same model, including its weights and the optimizer

model_file = os.path.join(BASE_DATA_PATH, 'my_model.h5')
model = tf.keras.models.load_model(model_file)
# Show the model architecture
model.summary()

#create directory to save the SavedModel

saved_model_dir = os.path.join(BASE_DATA_PATH, 'saved_model\catsdogsCNN')
!mkdir -#p saved_model_dir
model.save(saved_model_dir) 

`
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-11-06 09:31
@grewe, In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by grewe** [comment] 2019-11-06 20:39
Here is the complete code base attached
[pythonLSTMCode.txt](https://github.com/tensorflow/tensorflow/files/3816613/pythonLSTMCode.txt)

**Comment by gadagashwini** [comment] 2019-11-07 09:43
@grewe, Thanks for the code. Please provide the all the supporting files to reproduce the reported issue. Thanks!

**Comment by grewe** [comment] 2019-11-07 15:57
The data is a UCF101 data set.  I have added a zip below AND it contains results from running the part of the code that performs CNN feature extraction on the video data that can take hours to do on a normal laptop.  So each .avi file has a corresponding .npy file containing the CNN feature extraction output.  So, I would block out the part of the code that contains the feature extraction....if you unzip and change the names of the directory paths it should work.

If you want I have also provided a link to my trained model saved in h5 that you could simply run the portion of the code that loads the model runs prediction to get input layer setup and then try to save.
SEE attached for a reduced version of the code attached in previous comment --that only loads my stored h5 file, does a few predictions then tries to save to a SavedModel directory format and fails with error reported.   If you use this then it will run quickly (Note: I do not understand why h5 format does not save the input shape information and I have to do predictions to reset when reloading model ---however if using original code that trains model and does SavedModel attempt the error is exactly the same).

[LSTM_SimpleCodeVersion.py.txt](https://github.com/tensorflow/tensorflow/files/3820468/LSTM_SimpleCodeVersion.py.txt)


Training data - BOTH videos and .npy files with feature vectors from each video to feed into [LSTM](url)
[http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/UCF-101_WithTraininData_InceptionV3CNN_trainedOnImageNet_Sampled_40_per_video.zip](url)

Model file
[http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/Good17EpochModel/my_model.h5](url)

**Comment by gadagashwini** [comment] 2019-11-08 11:25
@grewe, I am unable to open the zip file that you have shared. Please help us to replicate the issue with more information. Thanks!

**Comment by grewe** [comment] 2019-11-08 20:39
Here are the URLs again for the 2 resources

MODEL
[](url)http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/Good17EpochModel/my_model.h5

Training data - BOTH videos and .npy files with feature vectors from each video to feed into
[](url) http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/UCF-101_WithTraininData_InceptionV3CNN_trainedOnImageNet_Sampled_40_per_video.zip

**Comment by grewe** [comment] 2019-11-10 21:14
Any ideas on this issue?

**Comment by gadagashwini** [comment] 2019-11-12 10:39
@grewe, I tried to open the Zip file but i am unable to open it.
Please see the screenshot.
![Screenshot from 2019-11-12 15-36-48](https://user-images.githubusercontent.com/48476109/68664696-bfbf2680-0566-11ea-8055-8788e3252c34.png)
Thanks!

**Comment by gadagashwini** [comment] 2019-11-27 10:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-11-27 10:55 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support
