### ISSUE TITLE
Error during build: no such package '@paper_radio_group//'

### ISSUE THREAD

**Issue by dimon777** [tensorflow/tensorflow#3913] opened 2016-08-19 02:33 UTC
Hi All. Building python bindings gives me error:

`
root@host# bazel build -c opt --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package
...

WARNING: /root/.cache/bazel/_bazel_root/4b98d0d2e8f34611cfd0d274c46b2eaf/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
ERROR: /data/github/google/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@paper_radio_group//': Error cloning repository: Unexpected end of file from server caused by Unexpected end of file from server caused by Unexpected end of file from server and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 1.857s
`
Is there a workaround for this problem?

**Comment by suiyuan2009** [comment] 2016-08-19 04:50
can you provide tensorflow and bazel's version ?

**Comment by dimon777** [comment] 2016-08-19 13:38
tensorflow compiled from git source:

commit d8dddca5b11212ec6e8fe372d774d60f452dab24
Merge: 858c170 1a9b107

bazel installed via apt on ubuntu and shows in basel version:

Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

**Comment by suiyuan2009** [comment] 2016-08-20 04:21
I can't reproduce. I removed bazel cache directory in ~/.cache/bazel/, and run bazel clean, then to rebuild tensorflow, everything is ok, I use the latest tensorflow and bazel 0.3.1(also the latest) on ubuntu16.04.

**Comment by aselle** [comment] 2016-08-23 00:36
Try cleaning out your caches and trying a fresh rebuild (start from scratch in a new directory). Transient failures of git fetches have been known to happen if ssl certificates temporarily get out of whack. Let us know if that doesn't fix it. (can't find the issue where I saw this before at the moment)

**Comment by tatatodd** [comment] 2016-09-06 22:55
@dimon777 , I hope the advice above helped you resolve your build issue.  Closing this out as there hasn't been any activity for a while.  Please ping this issue if the problem persists.

**Closed by tatatodd** 2016-09-06 22:55 UTC
Labels: awaiting response
