### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by dipendra009** [tensorflow/tensorflow#41838] opened 2020-07-28 20:38 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X 10.14.6
- TensorFlow installed from (source or binary): Using pip
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
python3 tensorflow/lite/python/tflite_convert.py --output_file=model-float.lite --output_format=TFLITE --inference_type=FLOAT --inference_input_type=FLOAT --input_shape="1,224,224,3" --input_array="serving_default_input_1" --output_array="StatefulPartitionedCall" --mean_value=0 --std_dev_value=1 --saved_model_dir=/Users/z004njq/Projects/save_models/mobilenetv4-exp-1004-export/ --experimental_converter=True
```

**The output from the converter invocation**

```
2020-07-28 13:29:05.763703: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-28 13:29:05.781147: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14dc421f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-28 13:29:05.781174: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-28 13:29:14.581147: I tensorflow/core/grappler/devices.cc:78] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2020-07-28 13:29:14.581230: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-07-28 13:29:14.677045: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-07-28 13:29:14.677069: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 1835 nodes (1614), 2696 edges (2475), time = 64.086ms.
2020-07-28 13:29:14.677092: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 2.02ms.
I0728 13:29:16.315555 140734995711424 lite.py:624] Using experimental converter: If you encountered a problem please file a bug. You can opt-out by setting experimental_new_converter=False
2020-07-28 13:29:16.359263: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-07-28 13:29:16.359292: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
Fatal Python error: Segmentation fault

Current thread 0x00007fff6b6d45c0 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/wrap_toco.py", line 38 in wrapped_toco_convert
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 199 in toco_convert_protos
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 574 in toco_convert_impl
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 633 in convert
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 900 in convert
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1076 in convert
  File "tensorflow/lite/python/tflite_convert.py", line 239 in _convert_tf2_model
  File "tensorflow/lite/python/tflite_convert.py", line 623 in run_main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "tensorflow/lite/python/tflite_convert.py", line 640 in main
  File "tensorflow/lite/python/tflite_convert.py", line 644 in <module>
Segmentation fault: 11
```

**Also, please include a link to the saved model or GraphDef**

[mobilenetv3-exp-1004-export.zip](https://github.com/tensorflow/tensorflow/files/4991052/mobilenetv3-exp-1004-export.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2020-07-29 00:09
Can you provide the model / a minimal reproducer please?

**Comment by dipendra009** [comment] 2020-07-29 00:14
I had included the saved model before, it's available at: https://github.com/tensorflow/tensorflow/files/4991052/mobilenetv3-exp-1004-export.zip

**Comment by mihaimaruseac** [comment] 2020-07-29 17:30
Apologies, it was not showing properly in the original message due to formatting.

**Comment by dipendra009** [comment] 2020-07-31 19:11
Thank for your correcting the formatting, I am looking forward to solving the issue and understand the underlying cause.

**Comment by jvishnuvardhan** [comment] 2020-08-03 20:41
@dipendra009 Can you please share a standalone code to reproduce the issue? I am sharing a gist that you can use and update later part of the code. [Here](https://colab.research.google.com/gist/jvishnuvardhan/f7f66a336334c3f7cd5b343278c3bc8a/untitled.ipynb) is the gist with your model. Thanks!

**Comment by dipendra009** [comment] 2020-08-05 20:08
I have already uploaded the saved model file and the code I am using is tensorflow/lite/python/tflite_convert.py from TF 2.3.0 as mentioned in the issue. The model is successfully loaded by the converter but it gives the segmentation fault while trying to convert it to tf-lite format.

**Comment by karimnosseir** [comment] 2020-09-27 23:02
Sorry for the late update. I can reproduce and working on a fix for the issue.
Thanks for reporting the issue and sorry for the delay

**Comment by karimnosseir** [comment] 2020-10-13 07:33
Sorry for the late update. This should be fixed now on the master branch.

**Closed by karimnosseir** 2020-10-13 07:33 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, type:bug
