### ISSUE TITLE
Discrepancy between keras.layers.Reshape and tf.keras.layers.Reshape

### ISSUE THREAD

**Issue by rgov** [tensorflow/tensorflow#36428] opened 2020-02-02 22:02 UTC
```
tf-version 2.1.0
keras-version 2.2.4-tf
```

In Keras, according to [the documentation](https://keras.io/layers/core/), we expect:

```python
model.add(Reshape((-1, 2, 2)))
# now: model.output_shape == (None, 3, 2, 2)
```

But in tf.Keras [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Reshape):

```python
model.add(Reshape((-1, 2, 2)))
# now: model.output_shape == (None, None, 2, 2)
```

The second dimension is now `None` instead of the computed value.

This makes tf.Keras incompatible with Keras, and makes it harder to write code that is parameterized by of the output shape of an opaque model. Is there a way to get the true output shape?

**Comment by jvishnuvardhan** [comment] 2020-02-03 22:16
I could reproduce the issue. [Here is the gist](https://colab.research.google.com/gist/jvishnuvardhan/09cfb560b120cc9c83e93b9378f1ddf6/36428_keras.ipynb) with `keras==2.3.0` and [here is the gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/531ee39cf36accf688a40b4aac667e26/36428_tf.ipynb) with `tf-nightly`. The gists are for our reference. Thanks

**Comment by rgov** [comment] 2020-02-03 22:18
To answer my question, I found I could do `model.compute_output_shape(model.input_shape)`. At the least, this should be noted in the documentation I think.

**Comment by jvishnuvardhan** [comment] 2020-02-06 21:56
@rgov Are you interested in raising PR? Thanks!

**Comment by rushabh-v** [comment] 2020-02-08 11:46
@rgov I have raised a PR. Can you please check whether the way I have used `model.compute_output_shape(model.input_shape)` is correct or not?

**Comment by tanzhenyu** [comment] 2020-03-04 11:06
This looks like an issue that needs to be resolved regardless of the keras/tf.keras merge

**Comment by tanzhenyu** [comment] 2020-04-09 18:00
This is an issue that happened in eager mode, seems the solution is:
```python
if not tf.executing_eagerly():
      # Set the static shape for the result since it might lost during array_ops
      # reshape, eg, some `None` dim in the result could be inferred.
      result.set_shape(self.compute_output_shape(inputs.shape))
    return result
```

We made a commit which was reverted. Waiting for another commit.

**Comment by oby1** [comment] 2020-06-23 17:21
@tanzhenyu Do you have an estimate of when this issue will be resolved?  Is there anything the community can do to help?

**Comment by tanzhenyu** [comment] 2020-06-23 17:32
> @tanzhenyu Do you have an estimate of when this issue will be resolved? Is there anything the community can do to help?

Can you try tf-nightly? There are quite some fix updates on this issue

**Comment by jvishnuvardhan** [comment] 2020-08-07 05:41
@rgov This is resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3dc0d61293107949485267d03ebf113c/36428_tf.ipynb) is the gist for your reference. 

I am closing this issue as this was resolved already. Please feel free to reopen if you notice any related issue. thanks!

**Closed by jvishnuvardhan** 2020-08-07 05:41 UTC
Labels: TF 2.1, comp:keras, type:docs-bug
