### ISSUE TITLE
Failure to build from source

### ISSUE THREAD

**Issue by fjanoos** [tensorflow/tensorflow#3226] opened 2016-07-07 19:56 UTC
Hello,
I'm trying to build tensorflow with GPU enabled from source using the instructions given here. https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installation-for-linux.

The build for the tutorial_example_trainer fails for me, with no error messages that I can discern. Please advise

```
215 ____Building complete.
216 Target //tensorflow/cc:tutorials_example_trainer failed to build
217 ____Elapsed time: 25.909s, Critical Path: 25.58s

```

### Environment info
Operating System:
Debian 3.16.7

Installed version of CUDA and cuDNN: 
CUDA: 7.5
cuDNN: 4.0
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
>ls -l ~/local/cuda-7.5/lib/libcud*
-rw-r--r-- 1 firdaus firdaus 185K Jul  6 15:33 /home/firdaus/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 firdaus firdaus   16 Jul  6 15:33 /home/firdaus/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5*
lrwxrwxrwx 1 firdaus firdaus   19 Jul  6 15:33 /home/firdaus/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18*
-rwxr-xr-x 1 firdaus firdaus 305K Jul  6 15:33 /home/firdaus/local/cuda-7.5/lib/libcudart.so.7.5.18*
-rw-r--r-- 1 firdaus firdaus 545K Jul  6 15:33 /home/firdaus/local/cuda-7.5/lib/libcudart_static.a
```

If installed from sources, provide the commit hash:
```commit 70de76e696c21da617fd2e6435cf7fedab220db8```

### Steps to reproduce
1.  bazel build  --verbose_failures -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer 

### What have you tried 
1. I had to patch the build file in third_party/gpus/crosstool/CROSSTOOL to point it to a non-standard gcc path.
![image](https://cloud.githubusercontent.com/assets/923438/16667600/5c4a98fc-445b-11e6-9ff7-ef84f6df971c.png)

### Logs or other output that would be helpful
Attached.
[buildlog.txt](https://github.com/tensorflow/tensorflow/files/352935/build.txt)

**Comment by aselle** [comment] 2016-07-07 20:05
Debian 3.16 is quite an old version of Linux, so it is unsurprising that you need to build custom gcc and hack the build configuration. It's unclear whether you were able to get it to work with your custom changes to the build file or not. Regardless, I would suggest upgrading to a version we support like Ubuntu 16. Unfortunately, we are unable to support older versions of Linux. I am closing for now. Please reopen if a bug is discovered.

**Comment by fjanoos** [comment] 2016-07-07 20:21
I am not able to upgrade since I don't have admin on this machine.
Therefore, I would appreciate it if you can point me to what the cause of the error / failure is ?

**Comment by aselle** [comment] 2016-07-07 21:09
I apologize that I can't tell you what the problem is, and I can't reproduce your problem since we don't have any machines with your operating system. So, if you want to get it working, you will need to go into the bazel build log you attached, search for the word error and discover that. Doing that, it looks like a "dependency is undeclared". That usually means the build file has incorrectly declared the dependencies, but since other systems work, it is more likely in this case to be that bazel is not working properly on the older version of Linux. This is probably because it, too, does not support old versions of Linux. You _may_ be able to  hack bazel or the build file to make this work, but it is assuredly going to be difficult. Trying to convince your admin to upgrade Linux is probably a better use of your time. There are not even security patches for that version of Debian, which means it is probably ill-advised to keep running it. Good Luck!

**Comment by raingo** [comment] 2016-07-08 03:16
The following error 
```
ERROR: /srv/local/1/tmp/tensorflow/tensorflow/core/kernels/BUILD:1478:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depth_space_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/spacetodepth_op_gpu.cu.cc':
  '/srv/home/tsdist/vats_deployments/hzhang-tensorflow-cd5c92d2012f19ea907a9f13a0d99ead1901e82a/ext/public/gnu/gcc/4/9/1/dist/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/include-fixed/limits.h'
```
can be solved by adding the line 
```
cxx_builtin_include_directory: "/srv/home/tsdist/vats_deployments/hzhang-tensorflow-cd5c92d2012f19ea907a9f13a0d99ead1901e82a/ext/public/gnu/gcc/4/9/1/dist/lib/gcc/x86_64-unknown-linux-gnu/4.9.1"
```
in `tensorflow/third_party/gpus/crosstool/CROSSTOOL` at around line 64.

Basically, you need to tell bazel the location of the GCC include path.

Good luck, but since you've got gcc 4.9.1 installed, it should be possible.

I've done this successfully with gcc4.8.5, also on an old system.

**Comment by fjanoos** [comment] 2016-07-08 03:54
thanks. that solved it!

**Comment by aselle** [comment] 2016-07-08 17:48
Glad it worked!

**Closed by aselle** 2016-07-08 17:48 UTC
Labels: community support
