### ISSUE TITLE
DecodeCSV outputs an unexpectedly result

### ISSUE THREAD

**Issue by uuleon** [tensorflow/tensorflow#11552] opened 2017-07-17 11:55 UTC
I recently feel confused while using `DecodeCSV` operator. The meaning of `record_defaults` is different from that described in the documentation.

Here is the description in documentation:
```
record_defaults: One tensor per column of the input record, with either a
  scalar default value for that column or empty if the column is required.
```

Problem 1 : The size of `record_defaults` limit the size of output
```python
>>> value=["a,b,c"]
>>> parts_val = parsing_ops.decode_csv(value, field_delim=",", record_defaults = [[""]])
>>> parts_val
[<tf.Tensor 'DecodeCSV_10:0' shape=(1,) dtype=string>]
```

Problem 2 : If `record_defaults` contains empty element, the type of output is always float32. In the same time, it failed to check the existence of value.
```python
>>> value=["a,b,c"]
>>> parts_val = parsing_ops.decode_csv(value, field_delim=",", record_defaults = [[""], [], []])
>>> parts_val
[<tf.Tensor 'DecodeCSV_13:0' shape=(1,) dtype=string>, <tf.Tensor 'DecodeCSV_13:1' shape=(1,) dtype=float32>, <tf.Tensor 'DecodeCSV_13:2' shape=(1,) dtype=float32>]
```

Maybe I understand it in a wrong way. Any comment is appreciated. Thanks.

**Comment by drpngx** [comment] 2017-07-18 00:05
@keveman Any idea? It doesn't look like there's bounds checking on the `records_default`, so that might be a problem.

**Comment by asimshankar** [comment] 2017-07-18 01:16
I think the documentation is correct, but any suggestions to improve it will be appreciated.

RE: Problem 1: The documentation suggests that `record_defaults` must contain `One tensor per column of the input record`. So, it needs to match with the number of columns in the input. If it doesn't the op will fail. For example:

```python
value = tf.placeholder(tf.string)
parsed = tf.decode_csv(value, record_defaults=[[""]])
run = tf.Session().make_callable(parsed, [value])

print(run("a")) # Correctly "decodes" this single column CSV into string tensor

print(run("a,b,c")) # Will throw an exception saying  "Expect 1 fields but have 2 in record 0"
```

RE: Problem 2: An "empty element" means an empty tensor, i.e., a zero-element tensor with the expected type of the value of the column. Without any additional context information, TensorFlow interprets `[]` as a float32 tensor, just like say numpy does (well numpy typically uses float64):

```python
tf.constant([]).dtype # This will be tf.float32
np.array([]).dtype    # This will be np.float64
```

To explicitly provide a zero-element tensor of the correct type, e.g., int32, you could use `tf.constant([], tf.int32)` (and similarly in numpy `np.array([], np.int32)`).

So, for your example, I'd do something like:

```python
>>> value = ["a,b,c"]
>>> empty = tf.constant([], tf.string)  # Or np.array([], np.string) 
>>> parts_val = tf.decode_csv(value, field_delim=",", record_defaults = [[""], empty])
>>> parts_val
[<tf.Tensor 'DecodeCSV:0' shape=(1,) dtype=string>,
 <tf.Tensor 'DecodeCSV:1' shape=(1,) dtype=string>]
```

Hope that helps. Since this is not a bug, I'm going to close this out. 
If you'd like to contribute suggestions to improve the documentation, we'd be more that happy to hear (or even better, feel free to send a PR editing the documentation [here](https://github.com/tensorflow/tensorflow/blob/e85d3df/tensorflow/core/ops/parsing_ops.cc#L338))

Hope that helps!

**Closed by asimshankar** 2017-07-18 01:16 UTC

**Comment by uuleon** [comment] 2017-07-18 02:52
@asimshankar Thank you for your explanation. 

Actually, i don't know the number of columns in the input at the first time. What i hope is `record_defaults` do not has to match with the number of columns in the input.

If the size of `record_defaults` is greater than the number of columns, fill in output with the defaults.

If the size of `record_defaults` is less than the number of columns, throw exception to show that column is missing and required.

Perhaps that is more reasonable, isn't it?  :)

**Comment by asimshankar** [comment] 2017-07-18 04:34
@uuleon : `tf.decode_csv` expects that the number of columns is known before being invoked, so `record_defaults` has to match exactly. I'm not sure of the genesis of this, but I suspect this is to adhere to [RFC 4180](https://tools.ietf.org/html/rfc4180) in its strict sense and discourage subtle bugs from invalid input data (e.g., differing number of columns per line or unexpectedly missing columns in the file - see Section 2 of the RFC).
