### ISSUE TITLE
tables_initializer

### ISSUE THREAD

**Issue by tianhongbao** [tensorflow/tensorflow#37867] opened 2020-03-24 13:23 UTC
`sess_id.run(graph_id.get_operation_by_name("MyGraphID/init_all_tables")) `

I did not find a way to achieve this in C ++. what should I do？

**Comment by ravikyram** [comment] 2020-03-26 09:31
@tianhongbao 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2020-04-03 11:40
I am closing the issue as this issue not related to bug/performance.Please, ask this question in StackOverflow. Thanks!

**Closed by ravikyram** 2020-04-03 11:40 UTC
Labels: stat:awaiting response, type:others
