### ISSUE TITLE
Flops calculation in tensorflow 2.x version.

### ISSUE THREAD

**Issue by weichen456** [tensorflow/tensorflow#39834] opened 2020-05-24 15:34 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
tensorflow 2.2
- Are you willing to contribute it (Yes/No):
No

**Describe the feature and the current behavior/state.**
Flops calculation in tf1.x usually use  tf.compat.v1.profiler.ProfileOptionBuilder,but it doesn't work success in tf2.x,So,anyone can show me the official example to calculate flop in tf2.x version?
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
People who care about model efficiency.
**Any Other info.**

**Comment by amahendrakar** [comment] 2020-05-26 11:07
> Flops calculation in tf1.x usually use tf.compat.v1.profiler.ProfileOptionBuilder,but it doesn't work success in tf2.x

@weichen456,
Could you please provide a minimal reproducible code regarding this so that we can look into it. 

Also, please check this [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/ProfileOptionBuilder) for ProfileOptionBuilder and let us know if it helps. Thanks!

**Comment by weichen456** [comment] 2020-05-26 13:04
> > Flops calculation in tf1.x usually use tf.compat.v1.profiler.ProfileOptionBuilder,but it doesn't work success in tf2.x
> 
> @weichen456,
> Could you please provide a minimal reproducible code regarding this so that we can look into it.
> 
> Also, please check this [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/ProfileOptionBuilder) for ProfileOptionBuilder and let us know if it helps. Thanks!

hello , 
my code is like this:
def num_params_flops(readable_format=True):
  """Return number of parameters and flops."""
  nparams = np.sum(
      [np.prod(v.get_shape().as_list()) for v in tf.trainable_variables()])
  options = tf.profiler.ProfileOptionBuilder.float_operation()
  options['output'] = 'none'
  flops = tf.profiler.profile(
      tf.get_default_graph(), options=options).total_float_ops
  # We use flops to denote multiply-adds, which is counted as 2 ops in tfprof.
  flops = flops // 2
  if readable_format:
    nparams = float(nparams) * 1e-6
    flops = float(flops) * 1e-9
  return nparams, flops


> > Flops calculation in tf1.x usually use tf.compat.v1.profiler.ProfileOptionBuilder,but it doesn't work success in tf2.x
> 
> @weichen456,
> Could you please provide a minimal reproducible code regarding this so that we can look into it.
> 
> Also, please check this [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/ProfileOptionBuilder) for ProfileOptionBuilder and let us know if it helps. Thanks!

hello, 
my code is here https://colab.research.google.com/drive/1pA_cYnMj5JXxCCsJcGISmaZjmXJ5BTf9?usp=sharing
The params is work well, but the flops is zero.
can you give me a official example in tf2.x version?

**Comment by weichen456** [comment] 2020-05-26 13:05
> > Flops calculation in tf1.x usually use tf.compat.v1.profiler.ProfileOptionBuilder,but it doesn't work success in tf2.x
> 
> @weichen456,
> Could you please provide a minimal reproducible code regarding this so that we can look into it.
> 
> Also, please check this [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/ProfileOptionBuilder) for ProfileOptionBuilder and let us know if it helps. Thanks!

hello,
my code is here https://colab.research.google.com/drive/1pA_cYnMj5JXxCCsJcGISmaZjmXJ5BTf9?usp=sharing
The params is work well, but the flops is zero.
can you give me a official example in tf2.x version?

**Comment by amahendrakar** [comment] 2020-05-27 08:28
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/c9337fcd83ce34c7a8d968b2980070c9/39763.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/cccc06e3bdd090a88ba9ccfe805c07c0/39763-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by henglicad** [comment] 2020-05-28 00:19
It will be very valuable to have the issue fixed.

**Comment by bhack** [comment] 2021-05-23 09:16
ThIs Is a duplicate of https://github.com/tensorflow/tensorflow/issues/32809

**Comment by tensorflowbutler** [comment] 2021-06-10 18:14
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment] 2021-07-16 06:12
@weichen456 this ticket is a duplicate of #32809  ,please let us know if we can close this issue ..thanks !

**Comment by weichen456** [comment] 2021-07-19 08:42
> @weichen456 this ticket is a duplicate of #32809 ,please let us know if we can close this issue ..thanks !

Ok

**Comment by sushreebarsa** [comment] 2021-07-19 08:44
@weichen456 Thank you for your response. closing this issue.

**Closed by sushreebarsa** 2021-07-19 08:44 UTC
Labels: TF 2.2, comp:ops, stat:awaiting response, stat:awaiting tensorflower, type:bug
