### ISSUE TITLE
Error messages when using Dataset.from_generator in debug mode

### ISSUE THREAD

**Issue by Xyand** [tensorflow/tensorflow#21298] opened 2018-08-01 06:53 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.3
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA (CPU)
- **GPU model and memory**: NA (CPU)
- **Exact command to reproduce**:

```python
import tensorflow as tf

def gen():
  for val in range(10):
    yield (str(val),)

dataset = tf.data.Dataset.from_generator(gen, (tf.string,))

iter = dataset.make_one_shot_iterator()
next = iter.get_next()

sess = tf.Session()

for ii in range(10):
  print(sess.run(next))
```

### Describe the problem
When using `Dataset.from_generator()` in debug mode (PyCharm) error messages () are printed to the console. The code seems to run as expected. Might be some finalization issues. When not in debug mode everything seems quiet.

### Source code / logs

Error message:
```
Exception ignored in: <generator object _yield_value at 0x181a3d7830>
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/aaa/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 100, in _yield_value
    yield value
SystemError: error return without exception set
Exception ignored in: <generator object _yield_value at 0x181a3d7830>
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/aaa/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 100, in _yield_value
    yield value
SystemError: error return without exception set
Exception ignored in: <generator object _yield_value at 0x181a3d7830>
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/aaa/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 100, in _yield_value
    yield value
.
.
.
```

**Comment by jianxucsm** [comment] 2018-08-02 02:15
I have similar problem with a bit different output error message. It only happens during the debug mode of pycharm. It does not happen during run. Though it is really annoying. Please indicate if there is any fix/bypass.

**Comment by mrry** [comment] 2018-08-02 03:43
This appears to affect other projects than TensorFlow when run under the debugger in PyCharm debugger, according to an issue on their tracker: https://youtrack.jetbrains.com/issue/PY-30036

The issue seems to involve the debugging of Python generators and a potential mishandling of the exception state.

Please follow up on that thread with your reproduction and that should help to narrow down the problem. The thread also suggests a potential workaround of setting the environment variable `PYDEVD_USE_FRAME_EVAL=NO`.

**Comment by jianxucsm** [comment] 2018-08-02 15:39
Hi Derek;

 

setting the PYDEVD_USE_FRAME_EVAL=NO stops the error output. Tks for input.

 

Regards,

 

Jian

**Comment by jianxucsm** [comment] 2018-08-03 19:54
Hi Albert;

 

Setting the environment variable works on ubuntu but not on windows. Does anyone have experience it with windows as well?

 

Regards,

 

Jian

**Comment by Xyand** [comment] 2018-08-05 05:56
Didn't try on Windows (and no plans to do so). My exact setup is actually PyCharm @ OSX but interpreter is running in Docker container Ubuntu 16.04 (tensorflow/tensorflow:1.9.0-devel-py3)

**Comment by 13steinj** [comment] 2018-08-07 18:54
@Xyand while I cannot guarantee that this specific piece of tensorflow code causes the issue on Windows, I can guarantee that the underlying problem (PyCharm debugger using evaluation frames with generators) does cause an issue on Windows (I'm using it, and I get the issue with sympy)

**Comment by mrry** [comment] 2018-08-22 19:36
I'm closing this issue because (as far as I can tell) there's no action item on the TensorFlow team's part. Please feel free to reopen if this changes.

**Closed by mrry** 2018-08-22 19:36 UTC

**Comment by danielbraun89** [comment] 2019-06-04 10:18
This problem still exists. setting PYDEVD_USE_FRAME_EVAL might be a fix on the user side, but obviously it should be fixed on the source side

**Comment by mrry** [comment] 2019-06-05 16:55
@danielbraun89 As far as we understand, the fix would need to be in PyCharm, and it's not clear that there's anything the TensorFlow team can do here. See https://youtrack.jetbrains.com/issue/PY-30036 for the PyCharm bug.
