### ISSUE TITLE
FP16 Sparse Matrix multiply returns incorrect results on ARM

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#23357] opened 2018-10-29 21:07 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **no**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux for Tegra (Ubuntu 18.04)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Jetson AGX Xavier (ARM-aarch64)**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **1.11**
- Python version: **2.7**
- Bazel version (if compiling from source): **0.15.0**
- GCC/Compiler version (if compiling from source): **Linaro 7.3.0**
- CUDA/cuDNN version: **CUDA 10 cuDNN 7.3**
- GPU model and memory: **Jetson AGX Xavier, 16GB (shared with host)**

**Describe the current behavior**

When a matrix multiply is called such that one of the input tensors is of data type fp16 and declared sparse, the function returns incorrect results.  This error causes the failure of the sparse_matmul_op_test (found at tensorflow/python/kernel_tests/sparse_matmul_op_test.py)

**Describe the expected behavior**

The matmul function should return correct results, regardless of sparsity or data type.

**Code to reproduce the issue**

Running the sparse_matmul_op_test.py script on an ARM architecture device can reproduce the failure.  This python script is a reduced reproduction:

```
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import math_ops


with tf.Session() as sess:
  x=(np.clip(
      np.random.uniform(
          low=-256.0, high=256.0, size=3 * 3), -64,
      64) / 128.0).reshape([3, 3]).astype(np.float32)
  y=(np.clip(
      np.random.uniform(
          low=-256.0, high=256.0, size=3 * 3), -64,
      64) / 128.0).reshape([3, 3]).astype(np.float32)



  #Test matmul where a is sparse fp16, and b is not sparse fp32
  tf_x = math_ops.cast(x, dtypes.bfloat16)
  tf_y = math_ops.cast(y, dtypes.float32)
  tf_ans = math_ops.matmul(
      tf_x,
      tf_y,
      a_is_sparse=True,
      b_is_sparse=False)
  out = sess.run(tf_ans)
  #Test the same matmul case as above, without sparsity
  tf_ans_nosparse = math_ops.matmul(
      tf_x,
      tf_y,
      a_is_sparse=False,
      b_is_sparse=False)
  out_nosparse = sess.run(tf_ans_nosparse)

  #Numpy result where both types are np32, since the dot operation is not supported with fp16
  np_x = sess.run(math_ops.cast(tf_x, dtypes.float32))
  np_y = sess.run(math_ops.cast(tf_y, dtypes.float32))
  np_ans = np.matrix(np_x) * np.matrix(np_y)

  print("\tNumpy answer: ")
  print(np_ans)
  print("\tNon-Sparse TF: ")
  print(out_nosparse)
  print("\tSparse fp16 a, non-sparse fp32 b")
  print(out)
```

**Other info / logs**

Here is a sample output testing different configurations for the matmul inputs’ sparsity and data types.  (This output was generating by adding additional test configurations to the provided reproduce script.)

	

> Numpy answer: 
> [[-0.24025428 -0.13065982 -0.25      ]
>  [-0.08487757 -0.36836362  0.74902344]
>  [ 0.16072105  0.00858951  0.3720703 ]]
> 	Non-Sparse TF: 
> [[-0.24025428 -0.13065982 -0.25      ]
>  [-0.08487757 -0.36836362  0.74902344]
>  [ 0.16072105  0.00858951  0.3720703 ]]
> 	Sparse TF: 
> Sparse fp16 a, non-sparse fp32 b
> [[ 0.58551383  0.6306598  -0.25      ]
>  [ 0.58551383  0.6306598  -0.25      ]
>  [-0.33927894 -0.25273013 -0.12792969]]
> Sparse fp32 a, non-sparse fp16 b
> [[-0.24023438 -0.13085938 -0.25      ]
>  [-0.08523875 -0.36806947  0.74892884]
>  [ 0.16089517  0.0092376   0.3716218 ]]
> Non-sparse fp16 a, sparse fp32 b
> [[-0.24025428 -0.13065982 -0.25      ]
>  [-0.08487757 -0.36836362  0.74902344]
>  [ 0.16072105  0.00858951  0.3720703 ]]
> Non-sparse fp32 a, sparse fp16 b
> [[-0.17285156 -0.08886719  0.25      ]
>  [-0.17211097 -0.17229089  0.24892886]
>  [ 0.08876151  0.02520579 -0.12837823]]
> Sparse fp16 a, sparse fp32 b
> [[ 0.58551383  0.6306598  -0.25      ]
>  [ 0.58551383  0.6306598  -0.25      ]
>  [-0.33927894 -0.25273013 -0.12792969]]
> Sparse fp16 a, sparse fp16 b
> [[bfloat16(0.5859375) bfloat16(0.6328125) bfloat16(-0.25)]
>  [bfloat16(0.5859375) bfloat16(0.6328125) bfloat16(-0.25)]
>  [bfloat16(-0.33984375) bfloat16(-0.25390625) bfloat16(-0.127929688)]]
> Sparse fp32 a, sparse fp32 b
> [[-0.24025428 -0.13065982 -0.25      ]
>  [-0.08481594 -0.36826903  0.74892884]
>  [ 0.16101329  0.00903805  0.3716218 ]]
>

**Comment by ymodak** [comment] 2018-11-05 23:02
I am using TF 1.11 and Python 3.5. I was not able to reproduce your output discrepancy. The python script you provided gave me identical results:
	Numpy answer: 
[[-0.29198867  0.39291728 -0.1339958 ]
 [ 0.15558213  0.357412   -0.36430225]
 [-0.3190953  -0.47049227  0.50513315]]
	Non-Sparse TF: 
[[-0.29198867  0.39291728 -0.1339958 ]
 [ 0.15558213  0.357412   -0.36430225]
 [-0.3190953  -0.47049227  0.50513315]]
	Sparse fp16 a, non-sparse fp32 b
[[-0.29198867  0.39291728 -0.1339958 ]
 [ 0.15558213  0.357412   -0.36430225]
 [-0.3190953  -0.47049227  0.50513315]]

**Comment by MattConley** [comment] 2018-11-07 18:58
Thanks for the response; what ARM device are you using?  I just tried with python 3 and am still seeing the discrepancy

**Comment by tensorflowbutler** [comment] 2018-11-22 18:50
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2019-03-22 00:07
Apologies for the delay in response. Is this still an issue for you with the latest version of TF? Thanks!

**Comment by ymodak** [comment] 2019-03-29 17:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2019-03-29 17:39 UTC
Labels: comp:lite, comp:ops, stat:awaiting response
