### ISSUE TITLE
InvalidArgumentError:  Size 1 must be non-negative, not -21

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#37153] opened 2020-02-28 05:48 UTC
https://www.kaggle.com/super13579/u-net-base-on-resnet34-transfer-learning-keras

```
fig, m_axs = plt.subplots(20, 2, figsize = (10, 40))
[c_ax.axis('off') for c_ax in m_axs.flatten()]
for (ax1, ax2), c_img_name in zip(m_axs, test_paths):
    c_path = os.path.join(test_image_dir, c_img_name)
    c_img = imread(c_path)
    #print(c_img.shape)
    first_img = np.expand_dims(c_img, 0)/255.0
    #print('a')
    first_seg = fullres_model.predict(first_img)
    #print('b')
    ax1.imshow(first_img[0])
    ax1.set_title('Image')
    ax2.imshow(first_seg[0,:, :, 0])
    ax2.set_title('Prediction')
#fig.savefig('test_predictions.png')
```

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-54-a91de316977a> in <module>
>       7     first_img = np.expand_dims(c_img, 0)/255.0
>       8     #print('a')
> ----> 9     first_seg = .predict(first_img)
>      10     #print('b')
>      11     ax1.imshow(first_img[0])
> 
> ~/venv/lib/python3.7/site-packages/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
>    1460                                             verbose=verbose,
>    1461                                             steps=steps,
> -> 1462                                             callbacks=callbacks)
>    1463 
>    1464     def train_on_batch(self, x, y,
> 
> ~/venv/lib/python3.7/site-packages/keras/engine/training_arrays.py in predict_loop(model, f, ins, batch_size, verbose, steps, callbacks)
>     322             batch_logs = {'batch': batch_index, 'size': len(batch_ids)}
>     323             callbacks._call_batch_hook('predict', 'begin', batch_index, batch_logs)
> --> 324             batch_outs = f(ins_batch)
>     325             batch_outs = to_list(batch_outs)
>     326             if batch_index == 0:
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
>    3738         value = math_ops.cast(value, tensor.dtype)
>    3739       converted_inputs.append(value)
> -> 3740     outputs = self._graph_fn(*converted_inputs)
>    3741 
>    3742     # EagerTensor.numpy() will often make a copy to ensure memory safety.
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
>    1079       TypeError: For invalid positional/keyword argument combinations.
>    1080     """
> -> 1081     return self._call_impl(args, kwargs)
>    1082 
>    1083   def _call_impl(self, args, kwargs, cancellation_manager=None):
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_impl(self, args, kwargs, cancellation_manager)
>    1119       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
>    1120           list(kwargs.keys()), list(self._arg_keywords)))
> -> 1121     return self._call_flat(args, self.captured_inputs, cancellation_manager)
>    1122 
>    1123   def _filtered_call(self, args, kwargs):
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
>    1222     if executing_eagerly:
>    1223       flat_outputs = forward_function.call(
> -> 1224           ctx, args, cancellation_manager=cancellation_manager)
>    1225     else:
>    1226       gradient_name = self._delayed_rewrite_functions.register()
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
>     509               inputs=args,
>     510               attrs=("executor_type", executor_type, "config_proto", config),
> --> 511               ctx=ctx)
>     512         else:
>     513           outputs = execute.execute_with_cancellation(
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      65     else:
>      66       message = e.message
> ---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
>      68   except TypeError as e:
>      69     keras_symbolic_tensors = [
> 
> ~/venv/lib/python3.7/site-packages/six.py in raise_from(value, from_value)
> 
> InvalidArgumentError:  Size 1 must be non-negative, not -21
> 	 [[{{node u-resnet34_1/bn_data/batchnorm/mul-1-ReshapeNHWCToNCHW-LayoutOptimizer}}]] [Op:__inference_keras_scratch_graph_62290]
> 
> Function call stack:
> keras_scratch_graph
> fullres_model

**Comment by ravikyram** [comment] 2020-02-28 08:23
@SlowMonk 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 
Request you to share a colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Please, fill issue template (https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-15 00:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-16 04:28
@SlowMonk 

Any update on this issue please. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-31 01:15
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-31 05:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-03-31 05:50 UTC
Labels: comp:keras, stat:awaiting response, type:support

**Comment by Light-Reflection** [comment] 2020-11-04 09:14
well..I had met the sam equestion, and i fixed it by changed the  input shape to match tf.nn.batch_normalization(input,mean,var,......)

**Comment by Light-Reflection** [comment] 2020-11-06 07:28
hi, i confont this problem again!
And i take 2 days to fix it...it's terribly. 

And the finally method is you should **_reshape_** all variabale about placeholder, like **tf.reshape gamma beta mean var input** ....
