### ISSUE TITLE
Inconsistency in XLA Cotionmpila with Operand Order Swap in `tf.add` with Specific Operators on GPU

### ISSUE THREAD

**Issue by GwiHwan-Go** [tensorflow/tensorflow#62549] opened 2023-12-03 15:19 UTC
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS

### Python version

3.10.0

### CUDA/cuDNN version

cuda : 12.2 / cudnn 8.9.04

### GPU model and memory

Tesla V100S-PCIE-32GB

### Current behavior?

We've identified a bug in TensorFlow where swapping the order of operands in `tf.add`, when combined with specific operators like `tf.transpose`, `tf.reverse`, and `tf.math.subtract`, results in inconsistent outputs under XLA compilation. 
This behavior is only seen on **GPU.**

### Observations and Troubleshooting:
   - Removing operations such as `tf.transpose`, `tf.reverse`, or `tf.math.subtract` from the model prevents the inconsistency, indicating that these operations are integral to the error manifestation.
   - Interestingly, swapping the order of operands in `tf.add` also resolves the inconsistency, highlighting the significance of operand order in `tf.add` under XLA compilation.

### Standalone code to reproduce the issue

```shell
from typing import Dict
import tensorflow as tf
import pickle
import os
import numpy as np
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
params = [
]
class Model1(tf.keras.Model):
    @tf.function(jit_compile=True)
    def __call__(self, inp):
        trans = tf.transpose(inp, perm=[1, 0])
        rev = tf.reverse(trans, axis=[0, 1])
        subtract = tf.math.subtract(trans, trans)
        add = tf.add(rev, subtract)
        return add,

class Model2(tf.keras.Model):
    def __call__(self, inp):
        trans = tf.transpose(inp, perm=[1, 0])
        rev = tf.reverse(trans, axis=[0, 1])
        substract = tf.math.subtract(trans, trans)
        add = tf.add(substract, rev)
        return add,  

inputs = [
tf.random.uniform(shape=[16, 16], dtype=tf.float64),
]
model1 = Model1()
model2 = Model2()
device = "gpu"
with tf.device(device):
    tf.config.run_functions_eagerly(True)
    out1 = model1(*inputs)
    out2 = model2(*inputs)
    print(f'=========eager_output(version:{tf.__version__})================')
    try :
        for i in range(min(len(out1),len(out2))):
            np.testing.assert_allclose(out1[i].numpy(), out2[i].numpy(), rtol=0.001, atol=0.001, err_msg=f'at checking {i}th')
        print("XLA_eager does not trigger assertion")
    except AssertionError as e:
        print("XLA_eager triggers assertion")
        print(e)
    tf.config.run_functions_eagerly(False)
    out1 = model1(*inputs)
    out2 = model2(*inputs)
    print(f'=========compiled_output(version:{tf.__version__})================')
    try :
        for i in range(min(len(out1),len(out2))):
            np.testing.assert_allclose(out1[i].numpy(), out2[i].numpy(), rtol=0.001, atol=0.001, err_msg=f'at checking {i}th')
        print("XLA_complie does not trigger assertion")
    except AssertionError as e:
        print("XLA_complie triggers assertion")
        print(e)
```

### Relevant log output

```shell
=========eager_output(version:2.15.0)================
XLA_eager does not trigger assertion
=========compiled_output(version:2.15.0)================
XLA_complie triggers assertion

Not equal to tolerance rtol=0.001, atol=0.001
at checking 0th
Mismatched elements: 1550 / 1550 (100%)
Max absolute difference: 196.66151428
Max relative difference: 2487.16949153
 x: array([[-44.869186, -55.12228 , -88.184502, ..., -36.286663,  86.54509 ,
        -47.566055],
       [ 56.423187,  62.918427, -16.908859, ...,  -9.663177,  -0.339844,...
 y: array([[ -6.97467 ,  26.228836,  82.672806, ..., -90.296532, -74.700211,
        -35.530495],
       [-48.684883, -46.956802,  31.971481, ...,  77.690094, -84.941338,...
```

**Comment by SuryanarayanaY** [comment] 2023-12-04 07:43
Hi @GwiHwan-Go ,

I have tested the code with Tf2.14v and this behaviour was not observed. TF2.15v CUDA package has an issue woth tensorrt and unable to install on colab. But with CPU and Tf2.15v also no such behaviour. Seems the problem is with TF2.15v with GPU.Attaching [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/01410bdcf0e31c17b91c0c4385e4599c/62549.ipynb) for reference.

Could you please confirm whether this is not an issue with TF2.14v, so that whether this can be marked as regression issue?

SInce I can't install 2.15V GPU package, I am unable to replicate the reported behaviour. It seems you have installed the CUDA packages manually right?

**Comment by SuryanarayanaY** [comment] 2023-12-06 07:13
Hi @GwiHwan-Go ,

Thanks for clarification. Seems like regression issue.

**Closed** 2023-12-19 12:18 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:gpu, comp:xla, regression issue, TF 2.15
