### ISSUE TITLE
Incorrect value in results when using tf.math.log()

### ISSUE THREAD

**Issue by yqtianust** [tensorflow/tensorflow#31619] opened 2019-08-14 14:56 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No idea
- TensorFlow installed from (source or binary): binary using pip3 install
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda9.0, cudnn 7.6
- GPU model and memory: RTX 2080Ti

When I run the following code using CPU:
`result= tf.math.log(tf.constant([280.41303540865516]*100, dtype=tf.float32)).numpy()`
I got:
`
[5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634
 5.6362634 5.6362634 5.6362634 5.6362634 5.6362634 5.636264  5.636264
 5.636264  5.636264 ]`

I found result[0] is not equal to result[-1]. the first one is 
5.636263370513916 while the latter one is equal to 5.636263847351074.

I believe it is a bug.

**Code to reproduce the issue**
`
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from random import *
tf.enable_eager_execution()
with tf.device("/cpu:0"):
    result = tf.math.log(tf.constant([ 280.41303540865516]*100, dtype=tf.float32)).numpy()
print("{} vs {}".format(result[0], result[-1]))`

Seems GPU has no such issues.

**Comment by yqtianust** [comment] 2019-08-14 15:00
Well, this issue could be related to #31408

**Comment by mihaimaruseac** [comment] 2019-08-14 16:06
I think they are related, but don't know if the fix to one will also fix the other one, so better to not mark them as duplicates

**Comment by gowthamkpr** [comment] 2019-08-14 22:44
@yqtianust I tried to reproduce the issue on [Colab](https://colab.sandbox.google.com/gist/gowthamkpr/b512cc2618fd02ca1c3b65cf5d7398e3/untitled93.ipynb) but was not able to reproduce it. Can you please provide a github gist of the issue. Thanks!

**Comment by yqtianust** [comment] 2019-08-15 03:09
@gowthamkpr I found that it is ok if using number 280.41303540865516 in Colab. However, if you change the number to 774.726039560185 and run it on colab, the issue appear again. 

See here [colab](https://colab.research.google.com/drive/1Z4KvcoYXLwNoOwSaAO4p3nVDsJyjiVZI)

**Comment by Leslie-Fang** [comment] 2019-08-28 09:43
It seems not only exists in 2.0 release.
I try 1.14 and 2.0 both have the problem.

**Comment by Leslie-Fang** [comment] 2019-08-28 13:17
@mihaimaruseac @yqtianust 
I suspect it's a bug of eigen.
With GDB to debug, I set the break point at
https://github.com/tensorflow/tensorflow/blob/aac18a3ffb2b9744f026eda4970369d2cf548980/tensorflow/core/common_runtime/eager/kernel_and_device.cc#L169-L179
And print the results in memory:
```
x/1fw 0x401e100
0x401e100:  5.63626337

x/1fw 0x401e28c
0x401e28c:  5.63626385
```

**Comment by Leslie-Fang** [comment] 2019-08-28 13:20
My understand is it's calling
https://github.com/tensorflow/tensorflow/blob/aac18a3ffb2b9744f026eda4970369d2cf548980/tensorflow/core/kernels/cwise_ops.h#L837-L838
to calculate the result.

Please correct me if I am wrong.

**Comment by Leslie-Fang** [comment] 2019-08-29 10:36
I have write a sample code to do the test of Eigen:
```
  #include <iostream>
  #include <Eigen/Core>
  #include "Eigen/src/Core/functors/UnaryFunctors.h"
  #include <iomanip>
  using namespace Eigen;
  using namespace std;
  int main()
  {
    Eigen::Matrix<float, 100, 1> tmp = Eigen::Matrix<float, 100, 1>::Constant(100, 1, 280.41303540865516);
    cout << setprecision(8) << tmp << endl << "becomes: " << endl << tmp.unaryExpr(internal::scalar_log_op<float>()) << endl;
  }
```
When I build it, I link to the Eigen lib which tensorflow use. 
However, this code didn't happens the problem.
I mean all of the output is same.

Moreover, I narrow down this issue to the code snippet:
https://github.com/tensorflow/tensorflow/blob/69b1feac62276edcc509ac88af229c6236e645fe/tensorflow/core/kernels/cwise_ops_common.h#L537-L543

**Comment by yqtianust** [comment] 2019-08-31 12:09
@Leslie-Fang Have you tried other data type? like double? I am not familiar with Eigen.
It seems this issue will not occurs when using dtype float16, but it will occur when using float32 in tensorflow.

Alos, have you tried GDB on the issue #31408?

Or it is possible the problem is due to the connection between Eigen and TensorFlow?

**Comment by Leslie-Fang** [comment] 2019-09-02 03:26
@yqtianust I suspect the problem may happen in the tensor copy process. But I don't have any clue now.

**Comment by Saduf2019** [comment] 2020-05-27 06:39
@yqtianust 
Is this still an issue.

**Comment by yqtianust** [comment] 2020-05-31 06:45
@Saduf2019 I think so. 
However, according to #31408. 

> Both numbers are correct to within 1 ulp (unit in last place). The inconsistency is due to the difference between the vectorized and scalar path in the underlying Eigen code. In short, please don't rely on exact equality of floating point numbers.

**Comment by rohan100jain** [comment] 2020-08-10 09:33
based on the last comment, closing this bug as of now. Please let me know if this is still a problem.

**Closed by rohan100jain** 2020-08-10 09:33 UTC
Labels: TF 1.14, comp:ops, type:bug
