### ISSUE TITLE
Tensorboard can't show item on windows

### ISSUE THREAD

**Issue by coming0524** [tensorflow/tensorflow#6005] opened 2016-12-01 08:32 UTC
I have install the tensorflow by pip on windows 10 64bit

tensorflow have no Problem.
but,Tensorboard can't run.

this is Log
---------------------------------------------------------------------------------------------------------
D:\Python35\Lib\site-packages\tensorflow\tensorboard>d:\Python35\python.exe tensorboard.py --logdir=D:\tensorBoard --debug
INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory D:\Python35\Lib\site-packages\tensorflow\tensorboard
INFO:tensorflow:TensorBoard path_to_run is: {'D:\\tensorBoard': 'D'}
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: D:\tensorBoard
INFO:tensorflow:Adding events from directory D:\tensorBoard
INFO:tensorflow:Constructing EventAccumulator for D:\tensorBoard
INFO:tensorflow:Done with AddRunsFromDirectory: D:\tensorBoard
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
DEBUG:tensorflow:Opening a record reader pointing at D:\tensorBoard\events.out.tfevents.1480577231.SHPC052
DEBUG:tensorflow:No more events in D:\tensorBoard\events.out.tfevents.1480577231.SHPC052
INFO:tensorflow:No path found after D:\tensorBoard\events.out.tfevents.1480577231.SHPC052
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. Load took 0.008 secs
INFO:tensorflow:TensorBoard is tag: b'39'
Starting TensorBoard b'39' on port 6006
(You can navigate to http://10.237.101.186:6006)
INFO:tensorflow:path ../external\webcomponentsjs/webcomponents-lite.min.js not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /webcomponentsjs/webcomponents-lite.min.js
INFO:tensorflow:path ../external\plottable/plottable.css not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /plottable/plottable.css
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: D:\tensorBoard
INFO:tensorflow:Adding events from directory D:\tensorBoard
INFO:tensorflow:Done with AddRunsFromDirectory: D:\tensorBoard
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
DEBUG:tensorflow:No more events in D:\tensorBoard\events.out.tfevents.1480577231.SHPC052
INFO:tensorflow:No path found after D:\tensorBoard\events.out.tfevents.1480577231.SHPC052
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. Load took 0.009 secs

---------------------------------------------------------------------------------------
this is like 404 problem.

INFO:tensorflow:path ../external\webcomponentsjs/webcomponents-lite.min.js not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /webcomponentsjs/webcomponents-lite.min.js
INFO:tensorflow:path ../external\plottable/plottable.css not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /plottable/plottable.css

Can anyone help me?
Thank you very much.

**Comment by jiuling1029** [comment] 2016-12-01 08:44
[#5844](https://github.com/tensorflow/tensorflow/pull/5844) can help for you.

**Comment by mrry** [comment] 2016-12-01 17:48
Closing this as a duplicate of #5983. We've merged #5844 and will be adding it to the final release for 0.12.

If you have any questions, please follow up on #5983!

**Closed by mrry** 2016-12-01 17:48 UTC
