### ISSUE TITLE
 error: the value of ‘j’ is not usable in a constant expression

### ISSUE THREAD

**Issue by nuliknol** [tensorflow/tensorflow#37211] opened 2020-03-01 21:35 UTC
**System information**
- OS Platform and Distribution:  
    16.04.6 LTS (GNU/Linux 4.15.0-60-generic x86_64)

- Mobile device
    not a mobile device
- TensorFlow installed from (source or binary):
    using pip command
- TensorFlow version:
    2.1.0
- Python version:
    3.5.2.
- Installed using virtualenv? pip? conda?:
  using viertualenv
- Bazel version (if compiling from source):
  no
- GCC/Compiler version (if compiling from source):
   5.4.0
- CUDA/cuDNN version:
   no cuda
- GPU model and memory:
    GeForce GT 750M

**Describe the problem**

Tensorflow doesn't compile:

```
g++ -std=c++11 -shared -fPIC -I/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include -I/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/external/nsync/public -L/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -DGOOGLE_CUDA=1 .//*.cpp .//ops/*.cpp -ltensorflow_framework -o gym_tensorflow.so
In file included from /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/Tensor:101:0,
                 from /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/tensorflow/core/framework/numeric_types.h:20,
                 from /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/tensorflow/core/framework/allocator.h:26,
                 from /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/tensorflow/core/framework/op_kernel.h:25,
                 from .//ops/indexedmatmul.cpp:8:
/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h: In static member function ‘static IndexType Eigen::internal::TensorBlockIOV2<Scalar, IndexType, NumDims, Layout>::Copy(const Eigen::internal::TensorBlockIOV2<Scalar, IndexType, NumDims, Layout>::Dst&, const Eigen::internal::TensorBlockIOV2<Scalar, IndexType, NumDims, Layout>::Src&, const DimensionsMap&)’:
/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h:998:33: error: the value of ‘j’ is not usable in a constant expression
       if (++it[j].count < it[j].size) {                                \
                                 ^
/home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h:1011:7: note: in expansion of macro ‘COPY_INNER_DIM’
       COPY_INNER_DIM(LinCopy::Linear);
       ^

```
This is because you are using some old version of Eigen:
```
(env) nickai@lap:~/evolution/deep-neuroevolution/gpu_implementation/gym_tensorflow$ ls -l /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h
-rw-rw-r-- 1 nickai nickai 48966 mar  1 15:10 /home/nickai/evolution/deep-neuroevolution/env/lib/python3.5/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h
(env) nickai@lap:~/evolution/deep-neuroevolution/gpu_implementation/gym_tensorflow$ 
```
I wonder, why is an "unsupported" tree of the Eigen source code appearing inside tensorflow build directory at all?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I installed tensorflow using this command:

    pip install --upgrade tensorflow

Then I tried to build an app that depends on Tensorflow 
https://github.com/uber-research/deep-neuroevolution/tree/master/gpu_implementation/gym_tensorflow
by exeucting 

    make

But since Tensorflow has some bad code inside its headers (i.e. using old and unsupported Eigen library) my the app I am trying to builid doesn't build.

This is possibly the same issue as reported here: https://github.com/tensorflow/tensorflow/issues/29927

I suspect that to fix this, you have to update Eigen library.

**Comment by gadagashwini** [comment] 2020-03-02 09:39
@nuliknol, Can you provide standalone code to reproduce the reported issue. Thanks

**Comment by gadagashwini** [comment] 2020-03-13 10:20
@nuliknol, Any update ?

**Comment by gadagashwini** [comment] 2020-03-26 08:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-03-26 08:01 UTC
Labels: TF 2.1, stat:awaiting response, type:build/install

**Comment by Tanxj** [comment] 2020-07-15 04:19
I've got the same error when I compile tf-1.15 into my app.
The solution is quite simple: put the tf headers at the top of other headers.

**Comment by Taka152** [comment] 2021-01-22 03:49
> I've got the same error when I compile tf-1.15 into my app.
> The solution is quite simple: put the tf headers at the top of other headers.

it works on tf 2.3.1 when building custom operator
