### ISSUE TITLE
Inconsistent behaviour of tf.range

### ISSUE THREAD

**Issue by AlessioTonioni** [tensorflow/tensorflow#22530] opened 2018-09-26 10:49 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.10.0-0-g656e7a2b34 1.10.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: V9.0.176
- **GPU model and memory**: GTX Titan X + 2xGTX Titan Black

### Describe the problem
the tensor produced by tf.range exceeds the limit with the configuration of parameters below.

### Source code / logs
```
import tensorflow as tf

with tf.Session() as sess:
	max_value=379.0
	delta=379.0/94.0

	range_tensor = tf.range(max_value,delta=delta,dtype=tf.float32)

	print(sess.run(range_tensor))
```
Result:

> [  0.          4.0319147   8.063829   12.095744   16.127659   20.159573
  24.191486   28.2234     32.255314   36.287228   40.31914    44.351055
  48.38297    52.414883   56.446796   60.47871    64.51063    68.54254
  72.574455   76.60637    80.63828    84.6702     88.70211    92.734024
  96.76594   100.79785   104.829765  108.86168   112.89359   116.92551
 120.95742   124.989334  129.02126   133.05318   137.0851    141.11702
 145.14894   149.18086   153.21278   157.2447    161.27663   165.30855
 169.34047   173.37239   177.40431   181.43623   185.46815   189.50008
 193.532     197.56392   201.59584   205.62776   209.65968   213.6916
 217.72353   221.75545   225.78737   229.81929   233.85121   237.88313
 241.91505   245.94698   249.9789    254.01082   258.04272   262.07465
 266.10657   270.1385    274.1704    278.20233   282.23425   286.26617
 290.2981    294.33002   298.36194   302.39386   306.42578   310.4577
 314.48962   318.52155   322.55347   326.5854    330.6173    334.64923
 338.68115   342.71307   346.745     350.77692   354.80884   358.84076
 362.87268   366.9046    370.93652   374.96844   379.00037  ]

379.00037 should not be there!

Equivalent numpy code
```
import numpy as np
max_value=379.0
delta=379.0/94.0
print(np.arange(0,max_value,delta))
```
Result:
> [  0.           4.03191489   8.06382979  12.09574468  16.12765957
  20.15957447  24.19148936  28.22340426  32.25531915  36.28723404
  40.31914894  44.35106383  48.38297872  52.41489362  56.44680851
  60.4787234   64.5106383   68.54255319  72.57446809  76.60638298
  80.63829787  84.67021277  88.70212766  92.73404255  96.76595745
 100.79787234 104.82978723 108.86170213 112.89361702 116.92553191
 120.95744681 124.9893617  129.0212766  133.05319149 137.08510638
 141.11702128 145.14893617 149.18085106 153.21276596 157.24468085
 161.27659574 165.30851064 169.34042553 173.37234043 177.40425532
 181.43617021 185.46808511 189.5        193.53191489 197.56382979
 201.59574468 205.62765957 209.65957447 213.69148936 217.72340426
 221.75531915 225.78723404 229.81914894 233.85106383 237.88297872
 241.91489362 245.94680851 249.9787234  254.0106383  258.04255319
 262.07446809 266.10638298 270.13829787 274.17021277 278.20212766
 282.23404255 286.26595745 290.29787234 294.32978723 298.36170213
 302.39361702 306.42553191 310.45744681 314.4893617  318.5212766
 322.55319149 326.58510638 330.61702128 334.64893617 338.68085106
 342.71276596 346.74468085 350.77659574 354.80851064 358.84042553
 362.87234043 366.90425532 370.93617021 374.96808511]

**Comment by tensorflowbutler** [comment] 2018-09-26 18:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-09-27 17:15
@AlessioTonioni That's a good catch !  I tried with couple of examples with different max_value and delta and tf.range works fine in all those scenarios. But we will definitely consider your finding and feel free to share other scenarios(if any).

**Comment by AlessioTonioni** [comment] 2018-09-29 09:36
@harshini-gadige I have only found this configuration thus far, but I think it might be something related to numerical precision during the computation.
With the same max_value and delta as in the initial post 

`range_tensor = tf.range(max_value-1E-4,delta=delta,dtype=tf.float32)`

Works as expected, i.e. the last number in the range is 374.96808511.

`range_tensor = tf.range(max_value-1E-5,delta=delta,dtype=tf.float32)`

Shows the bug, i.e. the last number in the range is 379.00037.

**Comment by harshini-gadige** [comment] 2018-10-01 16:49
@rmlarsen Is this happening due to numerical computation or this could be a bug ?

**Comment by facaiy** [comment] 2018-10-05 00:56
I guess that `max_value = 379` is converted to float32, which might lose precision.

**Comment by AlessioTonioni** [comment] 2018-10-05 09:47
> I guess that `max_value = 379` is converted to float32, which might lose precision.

I was thinking something similar at the beginning, but I tried and reported the result with `max_value=379.0` that is already a python float, the only conversion going on should be from python float to tf.float32.

**Comment by tensorflowbutler** [comment] 2018-10-21 19:04
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-05 19:00
Nagging Assignee @rmlarsen: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-05 19:01
Nagging Assignee @rmlarsen: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by JonJason** [comment] 2019-11-14 13:33
Hi, I have a similar problem with the precision in tensorflow-gpu version 2.0.0

this is the version.

    >>># note: this is tensorflow-gpu I installed
    >>>tf.__version__
    '2.0.0'

this is to reproduce the bug.

    >>>tf.range(0,5,0.1)
    <tf.Tensor: id=11, shape=(50,), dtype=float32, numpy=
    array([0.        , 0.1       , 0.2       , 0.3       , 0.4       ,
              0.5       , 0.6       , 0.70000005, 0.8000001 , 0.9000001 ,
              1.0000001 , 1.1000001 , 1.2000002 , 1.3000002 , 1.4000002 ,
              1.5000002 , 1.6000003 , 1.7000003 , 1.8000003 , 1.9000003 ,
              2.0000002 , 2.1000001 , 2.2       , 2.3       , 2.3999999 ,
              2.4999998 , 2.5999997 , 2.6999996 , 2.7999995 , 2.8999994 ,
              2.9999993 , 3.0999992 , 3.199999  , 3.299999  , 3.399999  ,
              3.4999988 , 3.5999987 , 3.6999986 , 3.7999985 , 3.8999984 ,
              3.9999983 , 4.0999985 , 4.1999984 , 4.2999983 , 4.399998  ,
              4.499998  , 4.599998  , 4.699998  , 4.799998  , 4.8999977 ],
            dtype=float32)>

**Comment by sushreebarsa** [comment] 2021-09-13 14:59
@AlessioTonioni It looks like you are using an older Version of Tensorflow (1.x) which is out of support window. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.6.0) and let us know if the issue still persists? Please refer to the [link](https://www.tensorflow.org/api_docs/python/tf/range) and let us know if it helps ?Thank you!

**Closed** 2021-09-27 16:24 UTC
Labels: stat:awaiting response, type:bug, stalled
