### ISSUE TITLE
connect trained inception model to classify_image.py file cannot find pbtxt file

### ISSUE THREAD

**Issue by DKP-90** [tensorflow/tensorflow#2513] opened 2016-05-26 16:22 UTC
I have tried the training on flowers, it generated 2 files in /tmp a output_graph.pb and output_labels.txt file, but when i tried connecting these files to classify_image.py file I found the code is reading a .pbtxt apart from .pb and .txt file. How do I use the python code without the pbtxt file. 

find the classify_image code here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/imagenet/classify_image.py

**Comment by petewarden** [comment] 2016-06-07 20:26
@wolffg has a solution for this upcoming I believe.

**Comment by zxzhijia** [comment] 2016-06-21 14:02
Same question. Waiting for a suggestion.

**Comment by zxzhijia** [comment] 2016-06-21 14:08
@DKP-90
Have you already solve this problem？

**Comment by DKP-90** [comment] 2016-06-22 05:44
No haven't found a solution yet.

**Comment by wolffg** [comment] 2016-06-22 06:03
You can look at this gist:

https://gist.github.com/wolffg/541c97a74dfc0d77c4b8fd2a946a5b41

which is referred to here:

https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#5

which shows using Python to classify with the output of tensorflow/examples/image_retraining/retrain.py.  It uses hardcoded pathnames, but you can get the idea.

Does that help?

**Comment by zxzhijia** [comment] 2016-06-22 13:06
Thank you for your help. I'll try it.

**Comment by zxzhijia** [comment] 2016-06-22 22:16
I copied the code and save it as a py file. Then I revised the path of the
pb and txt file and run it using python retrain_test.py PATHTOIMAGE. It
gives me the error below:

pi@raspberrypi:~/robotimages $ python retrain_test.py
/home/pi/robotimages/Robot1/w/1.jpg
Traceback (most recent call last):
  File "retrain_test.py", line 15, in <module>
    graph_def.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py",
line 185, in ParseFromString
    self.MergeFromString(serialized)
  File
"/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py",
line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File
"/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py",
line 1127, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File
"/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py",
line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
pi@raspberrypi:~/robotimages $

**Comment by petewarden** [comment] 2016-06-24 07:27
That error message indicates that there's something wrong with the model file you're trying to load. It's hard to tell what the problem is there though.

**Comment by suharshs** [comment] 2016-08-15 23:36
Closing this issue as it has been idle for some time. Please reopen or create new open if you get more information.

**Closed by suharshs** 2016-08-15 23:36 UTC

**Comment by ansu1234** [comment] 2017-02-18 04:28
can you tell how did you train for flower data set to generate .pb and .txt file. i tried from here https://github.com/tensorflow/models/tree/master/slim to "fine tune a model from an existing checkpoint", and its generating
1. graph.pbtxt
2. model.ckpt-1197.data-00000-of-00001
3. model.ckpt-1197.index
4. model.ckpt-1197.meta 
files. I generated .pb file and not able to generate .txt file.
