### ISSUE TITLE
Build error using bazel for r1.7 -> gen_gen_stats_ops_py_py_wrappers_cc: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E

### ISSUE THREAD

**Issue by mgyong** [tensorflow/tensorflow#18132] opened 2018-03-30 19:38 UTC
Tried to build r1.7 from source for CPU only
Build logs below
###############
INFO: From Compiling external/kafka/src/rdkafka_op.c:
external/kafka/src/rdkafka_op.c: In function 'rd_kafka_op_destroy':
external/kafka/src/rdkafka_op.c:299:35: warning: variable 'res' set but not used [-Wunused-but-set-variable]
                 rd_kafka_op_res_t res;
                                   ^~~
ERROR: /tmp/tensorflow/tensorflow/contrib/tensor_forest/BUILD:324:1: Executing genrule //tensorflow/contrib/tensor_forest:gen_stats_ops_py_pygenrule failed (Exit 127)
bazel-out/host/bin/tensorflow/contrib/tensor_forest/gen_gen_stats_ops_py_py_wrappers_cc: symbol lookup error: bazel-out/host/bin/tensorflow/contrib/tensor_forest/gen_gen_stats_ops_py_py_wrappers_cc: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
Target //tensorflow/tools/pip_package:build_pip_package failed to build

####################
Ubuntu 16.10
Bazel
Build label: 0.11.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

**Comment by tensorflowbutler** [comment] 2018-03-31 06:29
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wjcskqygj2015** [comment] 2018-04-20 13:48
I guess it is still is. Since I have encounter this problem under ubuntu16.04

**Comment by tensorflowbutler** [comment] 2018-05-05 18:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-26 18:52
It has been 36 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gunan** [comment] 2018-05-29 00:33
Closing due to the lack of full reproduction instructions. 
Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

**Closed by gunan** 2018-05-29 00:33 UTC
Labels: stat:awaiting response
