### ISSUE TITLE
AttributeError: 'ConvolutionalBoxPredictor' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by halhwadi** [tensorflow/tensorflow#48528] opened 2021-04-14 22:12 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
Colab
- Python version:3.7
_ TPU
_ Tensorflow version 2.4.1

**Describe the current behavior**

getting error below during running model_tpu_main.py:
`!python model_tpu_main.py --model_dir=model --pipeline_config_path=model/pipeline_tpu.config  --job-dir=model`

**Standalone code to reproduce the issue**
Refer to Colab [notebook](https://colab.research.google.com/drive/1XojAvhpsM4BaauXLKI1ObJw4-Sn8rfZ8?usp=sharing)

**Other info / logs** Include any logs or source code that would be helpful to
**error Msg:**
 _File "/usr/local/lib/python3.7/dist-packages/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 2947, in updates
    self._first_stage_box_predictor.inputs))
AttributeError: 'ConvolutionalBoxPredictor' object has no attribute 'inputs'_

**Comment by saikumarchalla** [comment] 2021-04-15 06:36
@halhwadi The issue is related to models repo. Could you please submit a new issue [here](https://github.com/tensorflow/models/issues/new?assignees=&labels=type%3Abug%2Cmodels%3Aresearch&template=30-research-bug-report-issue.md).Thanks!

**Comment by saikumarchalla** [comment] 2021-04-19 06:30
@halhwadi Closing this issue for now as I can see you have created a new issue on models repo. Thanks!

**Closed by saikumarchalla** 2021-04-19 06:30 UTC
Labels: TF 2.4, comp:model, stat:awaiting response, type:bug
