### ISSUE TITLE
Replacing keras by tensorflow.python.keras causes AttributeError: 'ThreadsafeIterator' object has no attribute 'shape'

### ISSUE THREAD

**Issue by bwolfus** [tensorflow/tensorflow#28183] opened 2019-04-26 13:55 UTC
System information
- OS Platform and Distribution (Windows 10 64bit):
- TensorFlow installed from (pip):
- TensorFlow version (1.13.1):
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: RTX 2060 6GB
- Keras 2.2.4

Using PyCharm.

**Describe the problem.**
When I try my model with keras and tensorflow.python.keras I found difference.
The model on keras works but when I use tensorflow.python.keras throwing errors:

`File "C:\python36_ver\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1427, in fit_generator
    initial_epoch=initial_epoch)`
`File "C:\python36_ver\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 119, in model_iteration
    shuffle=shuffle)`
`File "C:\python36_ver\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 399, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])`
`AttributeError: 'ThreadsafeIterator' object has no attribute 'shape'`

**Comment by gadagashwini** [comment] 2019-04-30 04:40
@bwolfus  In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jpsacha** [comment] 2019-05-07 21:00
I have the same issue. The `generator` passed to `model.fit_generator` is created with code

```python
@threadsafe_generator
def generator_x(image_ids, data_dir, batch_size, do_shuffle=True, name=None,
                image_subdir='images', image_suffix='.png', mask_subdir='masks', mask_suffix='.png'):

    while True:
        # Shuffle the list of images from 'train_ids'
        if do_shuffle:
            ids = shuffle(image_ids)
        else:
            ids = image_ids

        for start in range(0, len(ids), batch_size):
            x_batch = []
            y_batch = []
            end = min(start + batch_size, len(ids))
            ids_batch = ids[start:end]
            for image_id in ids_batch:
                image_path = os.path.join(data_dir, image_subdir, '%s%s' % (image_id, image_suffix))
                img = imread(image_path)
                # Convert color space, if needed
                img = from_bgr(img, color_space)

                mask_path = os.path.join(data_dir, mask_subdir, '%s%s' % (image_id, mask_suffix))
                mask = imread(mask_path, cv2.IMREAD_GRAYSCALE)
                mask = np.expand_dims(mask, axis=2)

                x_batch.append(img)
                y_batch.append(mask)

            x_batch = np.array(x_batch, np.float32) / 255
            y_batch = np.array(y_batch, np.float32) / 255
            yield x_batch, y_batch
```

That generator is passed in tf.keras code to `convert_to_generator_like` that is not able to use it (the error as above).

**Comment by ymodak** [comment] 2019-05-13 21:00
Automatically closing due to lack of recent activity from the author. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
@jpsacha Please post a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose) by filling all the information asked by the template. Thanks!

**Closed by ymodak** 2019-05-13 21:00 UTC
Labels: comp:keras, type:support

**Comment by danielbraun89** [comment] 2019-06-04 10:33
This problem still presist
