### ISSUE TITLE
NcclAllReduce Registered Multiple TImes

### ISSUE THREAD

**Issue by pmcgraw-lucidyne** [tensorflow/tensorflow#24745] opened 2019-01-07 19:20 UTC
This is likely a problem between the chair and keyboard, but bear with me. I try to simply:

`from tensorflow.contrib import nccl`

This causes code to run that registers an operation called NcclAllReduce multiple times because of various imports:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gradescan/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/__init__.py", line 30, in <module>
    from tensorflow.contrib.nccl.python.ops.nccl_ops import all_max
  File "/home/gradescan/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 52, in <module>
    @ops.RegisterGradient('NcclAllReduce')
  File "/home/gradescan/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2494, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/gradescan/.local/lib/python2.7/site-packages/tensorflow/python/framework/registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'NcclAllReduce'! (Previous registration was in <module> /home/gradescan/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py:72)"
```

Seems like one should be able to register multiple functions with the tensoflow RegsiterGradient to the same operation. Any help pointing me to documentation I can review, or general thoughts on how to resolve this issue would be appreciated.

**Comment by ymodak** [comment] 2019-01-07 21:47
Please provide following information. Thanks!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by ymodak** [comment] 2019-01-11 23:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-01-11 23:55 UTC
Labels: contrib, stat:awaiting response
