### ISSUE TITLE
How can I activate Tensorflow's XLA for the C API?

### ISSUE THREAD

**Issue by el1995** [tensorflow/tensorflow#29878] opened 2019-06-17 15:48 UTC
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: -
- GPU model and memory: - 

I have built Tensorflow from source and I am using it's C API. So far everything works good, I am also using AVX / AVX2. My Tensorflow build from source was also built with XLA support. I now would like to also activate XLA (accelerated linear algebra) as I hope that it will once again increase the performance / speed during inference.

If I start my run right now I get this message:

```
2019-06-17 16:09:06.753737: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1541] 
(One-time warning): Not using XLA:CPU for cluster because envvar 
TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that
envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass
--vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or 
set the envvar XLA_FLAGS=--xla_hlo_profile.
```

On the official XLA homepage (https://www.tensorflow.org/xla/jit) I found this information about how to turn on jit on a session level:

```
# Config to turn on JIT compilation
config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
sess = tf.Session(config=config)
```

Here (https://github.com/tensorflow/tensorflow/issues/13853) it was explained how to set the TF_SetConfig in the C API. I was able to limit to one core before using the output of this Python code:

```
config1 = tf.ConfigProto(device_count={'CPU':1})
serialized1 = config1.SerializeToString()
print(list(map(hex, serialized1)))
```

I implemented it as follows:

```
uint8_t intra_op_parallelism_threads = maxCores; // for operations that can be parallelized internally, such as matrix multiplication 
uint8_t inter_op_parallelism_threads = maxCores; // for operations that are independent in your TensorFlow graph because there is no directed path between them in the dataflow graph
uint8_t config[]={0x10,intra_op_parallelism_threads,0x28,inter_op_parallelism_threads};
TF_SetConfig(sess_opts,config,sizeof(config),status);
```

Therefore I thought this would help out for the XLA activation:
```
config= tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
output = config.SerializeToString()
print(list(map(hex, output)))
```

Implementation this time:

```
uint8_t config[]={0x52,0x4,0x1a,0x2,0x28,0x1};
TF_SetConfig(sess_opts,config,sizeof(config),status);
```

However XLA still seems to be deactivated. Can somebody help me out with this issue? Or, if you once again have a loot at the warning:

```
2019-06-17 16:09:06.753737: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1541] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
```

Does that mean I have to set XLA_FLAGS during the build?

I build Tensorflow using these configurations:

```
    Please specify the location of python. [Default is /usr/bin/python]: default
    -Please input the desired Python library path to use. Default is [/usr/local/lib/python2.7/dist-packages]: default
    Do you wish to build TensorFlow with XLA JIT support? [Y/n]: Y
    Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
    Do you wish to build TensorFlow with ROCm support? [y/N]: N
    Do you wish to build TensorFlow with CUDA support? [y/N]: N
    Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
    Do you wish to build TensorFlow with MPI support? [y/N]: y
    Please specify the MPI toolkit folder. [Default is /usr]: default
    Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: default
    Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
```

Thanks in advance!

Edit: moreover after some reading I am still not sure about when I should use XLA JIT and when I should use XLA AOT. It would be great if somebody could give me a recommendation about that!

Edit 2: I just read here (https://www.tensorflow.org/xla/jit):
```
# Config to turn on JIT compilation
config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
sess = tf.Session(config=config)
______________________________________
Note: Turning on JIT at the session level will not result in operations being compiled for the CPU. JIT compilation for CPU operations must be done via the manual method documented below.
```

So - no surprise my command did not do anything. Instead it is suggested to use the manual method:
```
    jit_scope = tf.contrib.compiler.jit.experimental_jit_scope

    x = tf.placeholder(np.float32)
    with jit_scope():
      y = tf.add(x, x)  # The "add" will be compiled with XLA.
```
However I do not know how to do this using the C API, as I do not have single operations like add, instead I just have the TF_SessionRun(...)-command.

**Comment by ymodak** [comment] 2019-06-18 21:36
@sanjoy Can you please take a look? Thanks!

**Comment by el1995** [comment] 2019-06-19 08:45
I would be especially interested on how to use AOT. For JIT, it seems like i can just include the experimental c api header and then use:

```
TF_EnableXLACompilation(sess_opts,true);
```

**Comment by jlebar** [comment] 2019-06-19 22:49
Hey there.  When filing bugs, it is helpful to include full steps to reproduce your issue.  "I'm trying to do X because Y.  (xyproblem.info, which you don't have here.)  I run this exact command, and here is the full output.  I believe this is not enabling XLA because I did xyz and I observed foo."

This bug is hard for me to help with because it does not have a listing of the complete code you're using, doesn't have the exact commands thave you have run, and doesn't have the full output of running your program.

Because I always have more things to help with than I have time for, if it's hard for me to help with this one, that means that I'm less likely to spend time on it, just out of my desire to help as many people in a day as possible.

That said, I will try to help a little.  I think these warnings are trying to tell you something:

>> 2019-06-17 16:09:06.753737: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1541] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
>
> Does that mean I have to set XLA_FLAGS during the build?

This warning is not about the build.  It is about setting an environment variable when you run your program.

```$ TF_XLA_FLAGS=--tf_xla_cpu_global_jit path/to/your/program```

I would start with that.

Note that support requests (e.g. "how do I use feature X?") are not bugs.  @ymodak in the future I think we should be strict about moving these to the correct forums.  That's important in part because whatever resolution we come to here will be useful for other people who have the same question, and they aren't necessarily going to look in the bug tracker.

**Comment by ymodak** [comment] 2019-06-19 22:51
@jlebar Thanks for the inputs. Will do now onward.

**Comment by ymodak** [comment] 2019-06-21 17:36
Closing this issue since the jlebar's comment addresses the issue. Feel free to post it on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) if further have questions related to this issue. Thanks!

**Closed by ymodak** 2019-06-21 17:36 UTC
Labels: TF 1.13, comp:xla, stat:awaiting response, type:support

**Comment by tangjie77wd** [comment] 2019-07-19 06:47
@el1995  I have tried what you said as the followings:
`
#include "c_api_experimental.h"
TF_SessionOptions* options = TF_NewSessionOptions();
TF_EnableXLACompilation(options,true);
`
but the output is **collect2: error: ld returned 1 exit status** when compiling.

**Comment by sanjoy** [comment] 2019-07-22 14:24
Have you followed all the instructions in https://www.tensorflow.org/install/lang_c (in particular, were you able to get https://www.tensorflow.org/install/lang_c#compile to run)?

If not, can you please post the entire linker error you get?

**Comment by tangjie77wd** [comment] 2019-07-23 01:21
Absolutely,i am not only able to get [https://www.tensorflow.org/install/lang_c#compile](url) to run but also [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/multibox_detector/main.cc](url) to run successfully .However, i will get the warning **(One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile** each time even i get the correct prediction result. I have tried some solutions like setting environment variable of **TF_XLA_FLAGS=--tf_xla_cpu_global_jit** or **TF_EnableXLACompilation(options,true);** but neither works.

**Comment by tangjie77wd** [comment] 2019-07-23 02:11
There are so many discussions about how to active XLA in python but very few in C++ API . I have set environment variable like this **export TF_XLA_FLAGS=--tf_xla_cpu_global_jit=/mytensorflowpath/tensorflow/compiler/xla:$TF_XLA_FLAGS=--tf_xla_cpu_global_jit** but the warning is still the same.

**Comment by sanjoy** [comment] 2019-07-23 14:31
Can you please post the entire linker error you get?

Note: you can ignore the "(One-time warning): Not using XLA:CPU for cluster because envvar ..." warning.  We had a (now fixed) bug where we'd print that warning even when it wasn't necessary.

**Comment by tangjie77wd** [comment] 2019-07-24 02:41
> Can you please post the entire linker error you get?
> 
> Note: you can ignore the "(One-time warning): Not using XLA:CPU for cluster because envvar ..." warning. We had a (now fixed) bug where we'd print that warning even when it wasn't necessary.

This is my whole warnings here (not error because i can test many examples successfully which means get correct prediction result.):
`
2019-07-16 10:33:52.057179: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-07-16 10:33:52.082548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3407965000 Hz
2019-07-16 10:33:52.082883: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x44d56d0 executing computations on platform Host. Devices:
2019-07-16 10:33:52.082903: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-16 10:33:52.557067: I tensorflow/core/common_runtime/optimization_registry.cc:35] Running all optimization passes in grouping 0. If you see this a lot, you might be extending the graph too many times (which means you modify the graph many times before execution). Try reducing graph modifications or using SavedModel to avoid any graph modification
2019-07-16 10:33:52.694202: I tensorflow/core/common_runtime/optimization_registry.cc:35] Running all optimization passes in grouping 1. If you see this a lot, you might be extending the graph too many times (which means you modify the graph many times before execution). Try reducing graph modifications or using SavedModel to avoid any graph modification
2019-07-16 10:33:53.157970: I tensorflow/core/common_runtime/optimization_registry.cc:35] Running all optimization passes in grouping 2. If you see this a lot, you might be extending the graph too many times (which means you modify the graph many times before execution). Try reducing graph modifications or using SavedModel to avoid any graph modification
2019-07-16 10:33:53.228415: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1337] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.

`
link [https://stackoverflow.com/questions/57049454/tensorflows-warningextending-the-graph-too-many-times-which-means-you-modify](url)

**Comment by el1995** [comment] 2019-07-31 08:44
Hi, I am also once again confused by XLA. I am using a CPU-only system, and although I do not get the errors mentioned about, I see the follwing:

```
 I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x44d56d0 executing computations on platform Host. Devices:
 I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): <undefined>, <undefined>
```
Moreover, the inference performance gets significantly worse every time I activate XLA. As described above, I used this command to activate XLA:
```
TF_EnableXLACompilation(sess_opts,true);
```

However, now i found out in the experimental header of the C API:
```
// When `enable` is true, set
// tensorflow.ConfigProto.OptimizerOptions.global_jit_level to ON_1, and also
// set XLA flag values to prepare for XLA compilation. Otherwise set
// global_jit_level to OFF.
```

And here (https://www.tensorflow.org/xla/jit) I see for the command mentioned (```config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1```)
"Note: Turning on JIT at the session level will not result in operations being compiled for the CPU. JIT compilation for CPU operations must be done via the manual method documented below."

Do I use XLA the way I do it now? I mean, obviously something changes, however with XLA the performance gets significantly lower. I know that this can happen with XLA and that it has an experimental status, but the note on the XLA JIT page confuses me, I am not sure any more whether I actually use XLA now or not...?

**Comment by sanjoy** [comment] 2019-07-31 14:50
> Hi, I am also once again confused by XLA. I am using a CPU-only system, and although I do not get the errors mentioned about, I see the follwing:
> 
> ```
>  I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x44d56d0 executing computations on platform Host. Devices:
>  I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): <undefined>, <undefined>
> ```

We also create a StreamExecutor for the host, that's what that line is saying.  I'm working on a CL to make that log line clearer.

> Moreover, the inference performance gets significantly worse every time I activate XLA. As described above, I used this command to activate XLA:
> 
> ```
> TF_EnableXLACompilation(sess_opts,true);
> ```
> 
> However, now i found out in the experimental header of the C API:
> 
> ```
> // When `enable` is true, set
> // tensorflow.ConfigProto.OptimizerOptions.global_jit_level to ON_1, and also
> // set XLA flag values to prepare for XLA compilation. Otherwise set
> // global_jit_level to OFF.
> ```
> 
> And here (https://www.tensorflow.org/xla/jit) I see for the command mentioned (`config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1`)
> "Note: Turning on JIT at the session level will not result in operations being compiled for the CPU. JIT compilation for CPU operations must be done via the manual method documented below."
> 
> Do I use XLA the way I do it now?

Are you also setting TF_XLA_FLAGS=--tf_xla_cpu_global_jit?  You're right that without this XLA will not kick in on CPU.

To debug this further, you can enable `--v=1` and check if you see this log line from `xla_compilation_cache.cc`: https://github.com/tensorflow/tensorflow/blob/926adde0445face2aae3d6e5822b83fa9259b988/tensorflow/compiler/jit/xla_compilation_cache.cc#L354

If that line is logging then XLA is definitely enabled and working.

> I mean, obviously something changes, however with XLA the performance gets significantly lower. I know that this can happen with XLA and that it has an experimental status, but the note on the XLA JIT page confuses me, I am not sure any more whether I actually use XLA now or not...?

**Comment by tangjie77wd** [comment] 2019-08-01 06:55
> > Can you please post the entire linker error you get?
> > Note: you can ignore the "(One-time warning): Not using XLA:CPU for cluster because envvar ..." warning. We had a (now fixed) bug where we'd print that warning even when it wasn't necessary.
> 
> This is my whole warnings here (not error because i can test many examples successfully which means get correct prediction result.)
> ` 2019-07-16 10:33:52.057179: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA`
> `2019-07-16 10:33:52.082548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3407965000 Hz`
> `2019-07-16 10:33:52.082883: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x44d56d0 executing computations on platform Host. Devices:`
> `2019-07-16 10:33:52.082903: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): <undefined>, <undefined>`
> `2019-07-16 10:33:52.557067: I tensorflow/core/common_runtime/optimization_registry.cc:35] Running all optimization passes in grouping 0. If you see this a lot, you might be extending the graph too many times (which means you modify the graph many times before execution). Try reducing graph modifications or using SavedModel to avoid any graph modification`
> `2019-07-16 10:33:53.228415: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1337] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set. If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU. To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.`
> link [https://stackoverflow.com/questions/57049454/tensorflows-warningextending-the-graph-too-many-times-which-means-you-modify](url)

Has already been solved several days !

**Comment by el1995** [comment] 2019-08-01 07:10
Hi @all,  
I now also set the environment variables and XLA should definitely be activated now. However, this leads to the termination of my simulations due to floating point exceptions, but only if I activate XLA. Is there a plausible reason for this?

**Comment by sanjoy** [comment] 2019-08-01 16:11
That sounds like an XLA bug.  Can you (yet again!) share the full log of the failure?

I'm also working on some public docs on how to file good actionable bugs against XLA, hopefully I'll have something to show next week.

**Comment by el1995** [comment] 2019-08-02 05:51
After all the "stardard" XLA messages in the beginning, I get:

```
[3] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[3] #1  Foam::sigFpe::sigHandler(int) at ??:?
[3] #2  ? in "/lib64/libc.so.6"
[3] #3  Foam::divide(Foam::Field<double>&, double const&, Foam::UList<double> const&) at ??:?
[3] #4  Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam::operator/<Foam::fvPatchField, Foam::volMesh>(Foam::dimensioned<double> const&, Foam::tmp<Foam::GeometricField<dou$
[3] #5  ? at tabulatedCombustionFoam.C:?
[3] #6  ? at ??:?
[3] #7  __libc_start_main in "/lib64/libc.so.6"
[3] #8  ? at ??:?
[node127:14007:0:14007] Caught signal 8 (Floating point exception: tkill(2) or tgkill(2))
==== backtrace ====
 0 0x0000000000036280 killpg()  ???:0
 1 0x0000000000036207 __GI_raise()  :0
 2 0x0000000000036280 killpg()  ???:0
 3 0x00000000005b824c Foam::divide()  ???:0
 4 0x00000000004759ff Foam::operator/<Foam::fvPatchField, Foam::volMesh>()  ???:0
 5 0x0000000000431d9e Foam::operator/<Foam::fvPatchField, Foam::volMesh>()  tabulatedCombustionFoam.C:0
 6 0x00000000004276cd main()  ???:0
 7 0x00000000000223d5 __libc_start_main()  ???:0
 8 0x000000000042b7d3 _start()  ???:0
===================
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 3 with PID 0 on node node127 exited on signal 8 (Floating point exception).
--------------------------------------------------------------------------
```

Please note that I linked TensorFlow to my simulation software OpenFOAM, that's why the errors do not look like TensorFlow errors. However, as mentioned before, the exactly identical simulation continues to run if I set my ```xlaJitSupport``` variable to zero. Another thing I want to point out is that only with ```TF_EnableXLACompilation(sess_opts,true);``` my simulation continues to run. If I additionally add the part with the ```TF_XLA_FLAGS```, I get the error.

**Comment by sanjoy** [comment] 2019-08-02 15:37
> Is it definitely required to additionally set the flags when already using TF_EnableXLACompilation(sess_opts,true);?

You can double check whether XLA is kicking in (or not) this way: https://github.com/tensorflow/tensorflow/issues/31199#issuecomment-517746363

**Comment by jbot19k** [comment] 2019-09-20 04:14
It work for me
On linux run in terminal: export TF_XLA_FLAGS=--tf_xla_cpu_global_jit
On Windows add on top of code: os.environ["TF_XLA_FLAGS"] = "tf_xla_cpu_global_jit"

**Comment by AbduElrahmanRezk** [comment] 2020-01-16 08:32
Does any one know how to write in c not in python using tensorflow c api 
I need the installation steps on ubuntu LTS 18.04 i cloned the TF official repository already but i stuck in this case : some  tensorflow c .h files using # include from other .h files which not in the repo 
how can i get this files so i can start use all functionalities of tensorflow on C or c++ ?
