### ISSUE TITLE
tf.nn.ctc_loss documentation does not mention that 'blank_index' must be provided when 'labels' is a SparseTensor

### ISSUE THREAD

**Issue by Ingkarat** [tensorflow/tensorflow#57964] opened 2022-10-04 07:01 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Microsoft Windows 11

### Python version

3.9

### Current Behaviour?

```shell
tf.nn.ctc_loss raises an exception when 'labels' is a SparseTensor and 'blank_index' is not provided. The documentation does not mention this.
https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss

A suggestion is to revise the docstring for either 'labels' or 'blank_index', or add a 'Raises' section to tf.nn.ctc_loss documentation.

The code below is modified from /python/kernel_tests/nn_ops/ctc_loss_op_test.py
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.ops import random_ops
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import array_ops

batch_size = 8
num_labels = 6
max_label_length = 5
num_frames = 12

labels = random_ops.random_uniform([batch_size, max_label_length], minval=1, maxval=num_labels, dtype=dtypes.int64)
logits = random_ops.random_uniform([num_frames, batch_size, num_labels])
label_length = random_ops.random_uniform([batch_size], minval=2, maxval=max_label_length, dtype=dtypes.int64)
label_mask = array_ops.sequence_mask(label_length, maxlen=max_label_length, dtype=label_length.dtype)
labels *= label_mask
logit_length = [num_frames] * batch_size

sp_labels = tf.sparse.from_dense(labels)
tf.nn.ctc_loss(sp_labels, logits, label_length, logit_length)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "...\tftesting.py", line 23, in <module>
    tf.nn.ctc_loss(sp_labels, logits, label_length, logit_length)
  File "...\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\...\tensorflow\python\ops\ctc_ops.py", line 937, in ctc_loss_v3
    raise ValueError(
ValueError: Argument `blank_index` must be provided when labels is a SparseTensor.
```
</details>

**Comment by gadagashwini** [comment] 2022-10-07 11:10
Hi @Ingkarat, This is intended behaviour.
Though its not documented on [Tensorflow.org](https://www.tensorflow.org/) but its clearly mentioned on Tensorflow repo. Please take a look at this code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/ctc_ops.py#L935-#L939). Thank you!

**Comment by Ingkarat** [comment] 2022-10-07 15:54
Thank you @gadagashwini. Would it be better to mention this in the documentation? maybe as part of `blank_index`'s description or in a Raises section at the end of the documentation.

**Comment by SuryanarayanaY** [comment] 2022-11-18 09:06
Hi @Ingkarat,

Thanks for the feedback given. Your feedback considered valuable and implemented the same in the nightly version.Please refer the attached source [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/ctc_ops.py#L968-L970).The same shall be reflected in Documentation in next release.
Could you please cross check and close the issue if satisfied.

Thankyou!

**Closed** 2022-12-02 10:16 UTC
Labels: type:docs-bug, stat:awaiting response, type:bug, stalled, comp:ops, TF 2.10
