### ISSUE TITLE
tf.train.string_input_producer breaks when num_epochs is set

### ISSUE THREAD

**Issue by bcarpenter-pub** [tensorflow/tensorflow#1045] opened 2016-02-10 21:57 UTC
I'm using a tf.train.string_input_producer to read in data from a file.  when I set num_epochs=1 instead of None it breaks and I get the following error.  My code is below as well.

Any suggestions for why this is occuring?

``` text
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 8
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 8
W tensorflow/core/common_runtime/executor.cc:1076] 0x7fdc4ba6b0f0 Compute status: Out of range: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 0)
     [[Node: shuffle_batch = QueueDequeueMany[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
W tensorflow/core/common_runtime/executor.cc:1076] 0x7fdc48da9170 Compute status: Out of range: FIFOQueue '_0_file_queue' is closed and has insufficient elements (requested 1, current size 0)
     [[Node: ReaderRead = ReaderRead[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, file_queue)]]
W tensorflow/core/common_runtime/executor.cc:1076] 0x7fdc4b8dbe20 Compute status: Aborted: Queue '_2_shuffle_batch/random_shuffle_queue' is already closed.
     [[Node: shuffle_batch/random_shuffle_queue_Close = QueueClose[cancel_pending_enqueues=false, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue)]]
Traceback (most recent call last):
  File "tensorflow_test.py", line 51, in <module>
    coord.join(threads)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 205, in join
    six.reraise(*self._exc_info_to_raise)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/queue_runner.py", line 112, in _run
    sess.run(enqueue_op)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value file_queue/limit_epochs/epochs
     [[Node: file_queue/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](file_queue/limit_epochs/epochs)]]
Caused by op u'file_queue/limit_epochs/CountUpTo', defined at:
  File "tensorflow_test.py", line 6, in <module>
    filename_queue = tf.train.string_input_producer(["datasets_top_10_50k/VALIDATION_testset/part-00000..tf"], num_epochs=2,capacity=10000, name="file_queue")
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 135, in string_input_producer
    "fraction_of_%d_full" % capacity)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 86, in _input_producer
    input_tensor = limit_epochs(input_tensor, num_epochs)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 77, in limit_epochs
    counter = epochs.count_up_to(num_epochs)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 414, in count_up_to
    return state_ops.count_up_to(self._variable, limit=limit)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 110, in count_up_to
    return _op_def_lib.apply_op("CountUpTo", ref=ref, limit=limit, name=name)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/blakec/virtual_envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()
```

Code:

``` python
import tensorflow as tf
import time

filename_queue = tf.train.string_input_producer(["datasets_top_10_50k/VALIDATION_testset/part-00000..tf"], num_epochs=2,capacity=10000, name="file_queue")
reader = tf.TFRecordReader()
_, serialized_example = reader.read(filename_queue)

data = tf.parse_single_example(
      serialized_example,
      dense_keys=["features","labels"],
      dense_types=[tf.float32, tf.float32],
      dense_shapes=[(4096),(10)])

features = data["features"]
labels = data["labels"]

batch_size=10
capacity=1000
min_after_dequeue=100
example_batch, label_batch = tf.train.shuffle_batch(
      [features, labels], 
      batch_size=batch_size, 
      capacity=capacity,
      min_after_dequeue=min_after_dequeue)
num_examples = 0
with tf.Session() as sess:
    # Start populating the filename queue.
    coord = tf.train.Coordinator()  
    threads = tf.train.start_queue_runners(coord=coord, sess=sess)

    try:
        step = 0
        while not coord.should_stop():
            start_time = time.time()
            e, l = sess.run([example_batch, label_batch])
            print "grabbing"
            e, l = sess.run([example_batch, label_batch])
            num_examples = num_examples + e.shape[0]
            print "num_examples = " + str(num_examples)
            duration = time.time() - start_time

    except tf.errors.OutOfRangeError:
        print('Done training for %d epochs, %d steps.' % (FLAGS.num_epochs, step))
    finally:
        # When done, ask the threads to stop.
        coord.request_stop()

        # Wait for threads to finish.
        coord.join(threads)
        sess.close()
```

**Comment by yaroslavvb** [comment] 2016-02-11 20:44
This doesn't seem to be a bug in TensorFlow (are you running initialize_all_variables?), this kind of question is better for StackOverflow

**Comment by jkschin** [comment] 2016-02-17 09:40
Even with init_op, I get that error too.

Error:

> W tensorflow/core/common_runtime/executor.cc:1157] 0x7fe82c00b390 Compute status: Out of range: Reached limit of 1
> 	 [[Node: input_producer/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/limit_epochs/epochs)]]
> W tensorflow/core/common_runtime/executor.cc:1157] 0x2051ef0 Compute status: Out of range: FIFOQueue '_0_input_producer' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: ReaderRead = ReaderRead[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReader, input_producer)]]

Code:
```
def run():
	with tf.Graph().as_default():
		filename_queue = tf.train.string_input_producer(["/tmp/data/sample.tfrecords"],num_epochs=1)
		images = read_and_decode(filename_queue)
		image_shape = tf.shape(images)

		init_op = tf.initialize_all_variables()
		with tf.Session() as sess:
			sess.run(init_op)
			coord = tf.train.Coordinator()
			threads = tf.train.start_queue_runners(coord=coord)
			for i in range(100):
				img = sess.run([images])
			coord.request_stop()
			coord.join(threads)

```

**Comment by ysfseu** [comment] 2016-05-19 14:16
I have the same issue

**Comment by timmeinhardt** [comment] 2016-07-06 12:40
I had the same issue. But 'tf.initialize_all_variables()' solved it. This should be mentioned in the documentation or be considered as a bug.

**Comment by MycChiu** [comment] 2016-07-08 11:51
@timmeinhardt Thank you! your comment put me on the right track. However, I think the current [master branch](https://github.com/tensorflow/tensorflow/blob/71f6bb336e5e11d6da2cedac6ba1c992ad9992bd/tensorflow/python/training/input.py#L83) put the created variables into the LOCAL_VARIABLES collection, so i had to initialize with tf.initialize_local_variables() as well.

**Comment by suiyuan2009** [comment] 2016-08-15 12:21
local_variable can't be initialized by tf.initialize_all_variables()

**Comment by jlowin** [comment] 2016-10-04 13:20
I would never have been able to solve this problem if I hadn't found this issue. If `tf.initialize_all_variables()` doesn't initialize local variables, then there's either a bug in its implementation, a documentation issue (specifically, the word "all"), or both.

**Comment by timmeinhardt** [comment] 2016-10-13 08:58
Can someone elaborate why this got closed without resolving the confusion around initializing all and/or local variables? This should definitely be changed or documented accordingly!

**Comment by yaroslavvb** [comment] 2016-10-13 17:15
Sorry, I shouldn't have closed it -- I mistakenly thought the problem was user forgetting to run `initialize_all_variables`, but the real issue is that a new class of variables was added that's not part of `all_variables`, but still needs to be initialized. I'm not sure there's an easy way to salvage the meaning of `all` in `all_variables`, @vrv may have more context on this

**Comment by vrv** [comment] 2016-10-13 17:31
There some some talk of a deprecation of "all" so that initialize_all_variables would be replaced with initialize_$something_variables, but the name was never settled on.  It's also going to be hard since nearly every program in TF uses initialize_all_variables().

Assigning to those who have thought about this more.

**Comment by timmeinhardt** [comment] 2016-10-13 17:38
From the opposite point of view there are probably only very few cases where somebody calls 'initialize_all_variables' and does not want to initialise all variables including the local variables. To ensure backwards compatibility I think 'initialize_all_variables' should be kept and do what its name suggests.

But I am curious to here what more experienced tensorflowers might have to say!

**Comment by vrv** [comment] 2016-10-13 17:42
From my limited understanding, that's not the case: there was some low level library added that decided that its variables didn't want to be part of "all" because they are local to each replica of a model, and would break a ton of models if they were initiailzed along with "all".  Hence the dilemma, and why this wasn't already done.  In other words, "local" variables are explicitly not part of "all".  Unfortunately, the name "all" was introduced well before this new use came in, so it's extremely sad and confusing.

**Comment by MycChiu** [comment] 2016-10-14 05:24
In this case, [It seems like moving epoch counter to local variables was a fix for some issues in the tf.contrib.learn library](https://github.com/tensorflow/tensorflow/commit/4c85a95925a68fec324f70cd0d7f3d4548f97a38). I think we can just add notes to the documentation on all input_producers' num_epochs parameter to remind users that they need to initialize with initialize_local_variables() if they want to limit the epochs.[Like the ones in tf.contrib.learn.read_batch_features](https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.learn.html#read_batch_features)

**Comment by jlowin** [comment] 2016-10-14 16:32
It feels very un-user-friendly to expect users to parse the documentation for a function that they may not even call directly (since it could be buried in a convenient utility function) while still having an `initialize_all_variables()` op that doesn't actually do what its name implies. 

On the other hand, I totally understand why there are times that you would want your variables to be excluded from the global `init_op` and having local variables makes sense in that context. Based on what I've learned here, I believe the problem in this case is that 1) we need to initialize `epochs` but 2) we don't want to restore `epochs` when the model is loaded because we want to be able to run the model! 

Is there a middle ground here? Maybe a way of marking a variable as not being restored? The whole issue feels to me like a very heavy-handed way of dancing around the problem.

**Comment by MycChiu** [comment] 2016-10-15 05:53
I thought one should only save the relevant model variables ,like the trainable ones and the moving moments if you use `batch_norm`, while using `tf.train.Saver`. If to avoid restoring epoch while restoring model is the only concern here, I think it would be better to just exclude `epochs` from the variables being saved.

However, I don't think this will prevent things from breaking in the distributed setting like @vrv mentioned.
 
For the time being, I think it would be really helpful to add the notes for now. (I could still feel the agony and pain from the hours I spent debugging this while violently scratching my head)

**Comment by ilblackdragon** [comment] 2016-10-28 04:03
Currently, there is still no decision on making it one way or another.
@sherrym is responsible for finalizing this.

**Comment by drpngx** [comment] 2017-01-24 01:51
@sherrym any decision on this?

**Comment by dmitry-xnor** [comment] 2017-02-15 08:14
Just got bit by this issue as well. Thank $DEITY for Google search, the error spew is impenetrable.

**Comment by jiqiujia** [comment] 2017-04-16 06:46
I still have this problem after I run 
`tf.group(tf.local_variables_initializer(), tf.global_variables_initializer())`
I use tensorflow r1.0. Anyone could help?
detailed trace back as follows:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dl/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/home/dl/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/media/dl/data2/tf_projects/NUS/eval_mscoco.py", line 138, in <module>
    coord.join(threads)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]

Caused by op u'input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo', defined at:
  File "<stdin>", line 1, in <module>
  File "/home/dl/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/home/dl/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/media/dl/data2/tf_projects/NUS/eval_mscoco.py", line 46, in <module>
    fns, labels = tf.train.slice_input_producer([fns, labels], num_epochs=1, shuffle=False)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 305, in slice_input_producer
    shared_name=shared_name)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 262, in range_input_producer
    shared_name, name, "fraction_of_%d_full" % capacity)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 156, in input_producer
    input_tensor = limit_epochs(input_tensor, num_epochs)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 96, in limit_epochs
    counter = epochs.count_up_to(num_epochs)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 628, in count_up_to
    return state_ops.count_up_to(self._variable, limit=limit)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 126, in count_up_to
    result = _op_def_lib.apply_op("CountUpTo", ref=ref, limit=limit, name=name)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/dl/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
`

**Comment by ybsave** [comment] 2017-04-24 16:51
@jiqiujia, I previously have the same problem. Later, I found that the local variables need to be initialized before calling "tf.train.start_queue_runners()"; then it will work well. Otherwise, there will be the same error as in your post. Hope it may help.

**Comment by drpngx** [comment] 2017-04-24 20:57
@jiqiujia could you start the queue runners as suggested?

It does say `input_producer`.

**Comment by gunan** [comment] 2017-06-16 21:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gunan** 2017-06-16 21:37 UTC
Labels: stat:awaiting response

**Comment by YMMS** [comment] 2017-06-30 07:26
@jiqiujia I found the same issue, when I used:
 ```
init_op =tf.group(tf.local_variables_initializer(), tf.global_variables_initializer())
sess.run(init_op)
```
but when I tried:
```
sess.run(tf.local_variables_initializer())
sess.run(tf.global_variables_initializer())
```
it works!

Is there any bugs about function 'tf.group'? @yaroslavvb

My ENV is Python 3.5.3, CPU, tf-1.1.0

**Comment by yaroslavvb** [comment] 2017-06-30 15:15
@YMMS the difference is that `tf.group` runs things in arbitrary order, so it can run global variables initializer before local variables initializer

**Comment by YMMS** [comment] 2017-07-04 02:30
@yaroslavvb , thanks for your replay.

But I have tried:

```
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess, coord)
```

It also works. I think maybe the order makes no difference.

In my opinion,

```
init_op = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer())
sess.run(init_op)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess, coord)
```

maybe failed to initialize the associated local variables of  `tf.train.string_input_producer`.

Just Guess.

**Comment by yaroslavvb** [comment] 2017-07-05 13:03
The order is random, so you may get different results upon reruns. I still think the difference is due to order, the actual ops to be executed should be the same. You can use linearize utility to guarantee that ops run in the same order -- https://github.com/yaroslavvb/stuff/tree/master/linearize

**Comment by RylanSchaeffer** [comment] 2017-08-10 23:03
I'm getting a different error as the original poster, but with the same cause - when I set num_epochs equal in `tf.contrib.slim.parallel_reader.parallel_read` to anything other than `None`, my `FIFOQueues` crash:

`OutOfRangeError (see above for traceback): FIFOQueue '_1_batch_examples_using_buckets/bucket_by_sequence_length/bucket/top_queue' is closed and has insufficient elements (requested 1, current size 0)`

Does this error have the same root cause as the `tensorflow.python.framework.errors_impl.FailedPreconditionError`? I would guess not. If so, does anyone know what might be causing this error?

**Comment by RylanSchaeffer** [comment] 2017-08-13 00:17
For anyone else with my same bug, adding `sess.run(tf.local_variables_initializer())` after `sess.run(tf.global_variables_initializer())` solved the error.

**Comment by prats226** [comment] 2018-01-31 06:03
Also for some reason, num_epochs=2 doesn't throw error.

**Comment by bharadwajdhornala** [comment] 2020-03-16 11:27
Hi @bcarpenter-pub @yaroslavvb @ysfseu @timmeinhardt @MycChiu 
I am trying to test the SketchModelling code,but stuck with error. I have tried adding 
sess.run(tf.local_variables_initializer()) 
sess.run(tf.global_variables_initializer())  but did not solve the error. Please suggest 
(SKetchModelling) C:\GenAssi\SketchModeling\Network\code\MonsterNet>python main.py --test --data_dir C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\ --train_dir C:\GenAssi\SketchModeling\Checkpoint\Chair\ --test_dir C:\GenAssi\SketchModeling\chair_results\
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
start running...
Loading testing data...
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Building network...
Testing...
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-S-0.png : The system cannot find the file specified.

W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-F-0.png : The system cannot find the file specified.

Traceback (most recent call last):
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
         [[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    tf.app.run()
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 142, in main
    monnet.test(sess, views, num_test_shapes)
  File "C:\GenAssi\SketchModeling\Network\code\MonsterNet\monnet.py", line 471, in test
    names,results,errors,images = sess.run([self.names, self.results, self.errors, self.pngs])
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
         [[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]**
