### ISSUE TITLE
ValueError: Unknown activation function:relu6

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#22976] opened 2018-10-15 02:35 UTC
tf.keras.layers.Activation(tf.nn.relu6)(x)

when i transform my model to tflite, this bug will happen

**Comment by tensorflowbutler** [comment] 2018-10-15 12:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-30 16:57
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2018-10-30 16:58
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by ymodak** 2018-10-30 16:58 UTC
Labels: comp:lite, stat:awaiting response
