### ISSUE TITLE
Inception-v3 only for specific classes

### ISSUE THREAD

**Issue by billidani7** [tensorflow/tensorflow#1103] opened 2016-02-15 10:58 UTC
Hi,

is it possible to use Inception-v3 to classify images only for dogs?The example at tensorflow/examples/label_image/ classify images into 1000 classes.

**Comment by vrv** [comment] 2016-02-15 18:25
Duplicate of https://github.com/tensorflow/tensorflow/issues/504

**Closed by vrv** 2016-02-15 18:25 UTC
