### ISSUE TITLE
TF looking for CUDA 10.1

### ISSUE THREAD

**Issue by eScribMac** [tensorflow/tensorflow#38174] opened 2020-04-02 18:37 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (Latest Update)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.2.0rc2
- Python version:  Python 3.8.2
- Installed using virtualenv? pip? conda?: venv + pip + conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA: 10.2 cuDNN: 7.6.5.32 
- GPU model and memory:  GeForce GTX 1060 6GB

**Describe the problem**

While following this tutorial: https://www.wandb.com/tutorial/build-a-neural-network and trying to run this file: https://github.com/lukas/ml-class/blob/master/videos/intro/perceptron-single.py

After following all instructions at https://www.tensorflow.org/install/gpu#software_requirements, I get the the following error: 
```
 python perceptron-single.py
Using TensorFlow backend.
2020-04-02 14:09:01.203876: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-02 14:09:01.241792: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

2020-04-02 14:09:08.194348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-02 14:09:08.236234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-04-02 14:09:08.259510: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-02 14:09:08.310824: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-02 14:09:08.345234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-02 14:09:08.373030: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-02 14:09:08.424593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-02 14:09:08.462421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-02 14:09:08.483778: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-02 14:09:08.493898: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

I have CUDA 10.2 installed but TF appears to be looking for 10.1. It proceeds to fall back to the CPU. 
How can I configure TF so that this works properly?

**Comment by ravikyram** [comment] 2020-04-03 07:20
@eScribMac 

Can you downgrade to CUDA 10.1 and check whether the issue still persists.Please, follow the guidelines from [here](https://www.tensorflow.org/install/gpu#windows_setup).Please, let us know if the problem still persists. Thanks!

**Comment by FelipeR2U** [comment] 2020-04-03 15:51
I'm having the same issue

```
2020-04-03 15:47:30.610616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-03 15:47:32.728673: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.729831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:1b.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.729940: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.731020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:00:1c.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.731105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.732204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 2 with properties: 
pciBusID: 0000:00:1d.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.732283: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.733386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 3 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.733811: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:
2020-04-03 15:47:32.735654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-03 15:47:32.737341: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-03 15:47:32.737683: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-03 15:47:32.739523: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-03 15:47:32.740580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-03 15:47:32.744448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-03 15:47:32.744474: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

The problem is that the [Profiler](https://github.com/tensorflow/profiler) needs Cuda 10.2

**Comment by FelipeR2U** [comment] 2020-04-03 15:52
I'm having the same issue

```
2020-04-03 15:47:30.610616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-03 15:47:32.728673: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.729831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:1b.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.729940: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.731020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:00:1c.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.731105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.732204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 2 with properties: 
pciBusID: 0000:00:1d.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.732283: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-03 15:47:32.733386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 3 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-04-03 15:47:32.733811: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:
2020-04-03 15:47:32.735654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-03 15:47:32.737341: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-03 15:47:32.737683: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-03 15:47:32.739523: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-03 15:47:32.740580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-03 15:47:32.744448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-03 15:47:32.744474: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

The problem is that the [Profiler](https://github.com/tensorflow/profiler) needs Cuda 10.2

**Comment by FelipeR2U** [comment] 2020-04-03 16:12
> @eScribMac
> 
> Can you downgrade to CUDA 10.1 and check whether the issue still persists.Please, follow the guidelines from [here](https://www.tensorflow.org/install/gpu#windows_setup).Please, let us know if the problem still persists. Thanks!

I downgraded to confirm my issue was solved to execute tensorflow-gpu. But the [Profiler](https://github.com/tensorflow/profiler) does not show what I need since it needs Cuda 10.2 to profile multiple GPUs

**Comment by FelipeR2U** [comment] 2020-04-06 16:27
@eScribMac, I have had some help [here](https://github.com/tensorflow/profiler/issues/3#issuecomment-608955663) if you want to try. I'm still having another issue, but tell me if you are able to solve your problem

**Comment by ravikyram** [comment] 2020-04-08 09:26
@eScribMac 

Any update on this issue please. Thanks!

**Comment by ahtik** [comment] 2020-04-14 23:01
@eScribMac for CUDA 10.2 TF has to be built with CUDA 10.2. As it's officially not supported, must be built by yourself. v2.2rc3 builds fine for both Windows and Ubuntu (used python 3.8 and cuda 10.2).

**Building tensorflow v2.2rc3 with CUDA 10.2 and python 3.8 from source**
Few notes to get it done more easily:
Adjust ~/.bazelrc to match your cpu core count for faster build
```
startup --batch_cpu_scheduling --io_nice_level 7
build --jobs 7 --ram_utilization_factor 80
test --jobs 7
```

Snippets to get the build running, adjust.
```
pip install six numpy wheel keras_applications keras_preprocessing --no-deps

SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
SET TF_NEED_CUDA=1
SET BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
SET BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
SET CUDA_TOOLKIT_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;%PATH%

# SUPER IMPORTANT TO KEEP BUILD TIME REASONABLE
SET TF_VC_VERSION=16.4

bazel clean --expunge
python configure.py

bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_cuda_10_2
```

**Using existing wheel and CUDA 10.1**
Another (easier) option is to additionally install CUDA 10.1 (while keeping CUDA 10.2 and *not* installing old drivers). CUDA 10.1 works fine with the latest drivers, CUDA installation does not do anything else than populating CUDA dir and adjusting the env variables. To allow proper libs lookup, adjust the env. Not sure anymore if all the following vars are required but feel free to experiment:
```
SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
SET CUDA_TOOLKIT_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;%PATH%
```

Validate the wheel by installing it to your env and running `python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([10000, 10000])))"`

**Comment by ravikyram** [comment] 2020-04-17 12:00
@eScribMac

Any update on this issue please. Thanks!

**Comment by mihaimaruseac** [comment] 2020-04-17 16:35
You should be able to symlink CUDA 10.2 libs to CUDA 10.1 and TF would pick them up.

Alternatively, you will have to build from source.

**Comment by eScribMac** [comment] 2020-04-17 16:38
@ravikyram thank you for the help and apologies for the delay, I've been busy with other projects. I will give that a shot this weekend. 

@mihaimaruseac what would that entail exactly? just symlinking each dll individually?

**Comment by mihaimaruseac** [comment] 2020-04-17 16:42
Yes. It has been reported in other issues that this works

**Comment by ravikyram** [comment] 2020-04-24 07:22
@eScribMac 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-04-30 07:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-30 07:54 UTC
Labels: TF 2.2, stat:awaiting response, subtype:windows, type:build/install
