### ISSUE TITLE
Add tf.repeat equivalent to np.repeat

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#8521] opened 2017-03-18 14:19 UTC
In some applications, we need to repeat Tensors, so hopefully there could be a build-in function tf.repeat which is equivalent to np.repeat. 

Example:
```
 np.repeat([1, 2, 3], 2)
>> array([1, 1, 2, 2, 3, 3])
```

**Comment by concretevitamin** [comment] 2017-03-19 17:26
I am not aware of anyone working on this.  We'd happily take a patch!  

That said, for simple cases (I understand `np.repeat` supports more general cases) like the one you cited, you could do 
```python
with tf.Session() as sess:
  print sess.run(tf.reshape(
      tf.tile(tf.expand_dims([1, 2, 3], -1),  [1, 2]), [-1]))
```
which is both CPU- and GPU-compatible.

**Comment by ZZhaoTireless** [comment] 2017-03-19 20:42
I would like to take this.

**Comment by sidjee** [comment] 2017-03-21 07:35
I am new to contributing to other projects. May i work on this issue?

**Comment by sidjee** [comment] 2017-03-25 12:21
I have been working on this issue and have written the c++ code for op.
I encountered the following error which i was unable to resolve.

1) Upon accessing the 'i'th element of object of tensor class,using
"object(i)"
following error was shown:-
**error: 'object' cannot be used as a function.**

2)Another one
```
tensorflow/core/framework/op_kernel.h: In member function ‘tensorflow::int64 tensorflow::PersistentTensor::AllocatedBytes() const’:
tensorflow/core/framework/op_kernel.h:210:49: error: ‘const class tensorflow::Tensor’ has no member named ‘AllocatedBytes’
   int64 AllocatedBytes() const { return tensor_.AllocatedBytes(); }
```

Please help.

**Comment by zycdragonball** [comment] 2017-04-04 01:09
@sidjee Are you still working on this? I have the codes ready. I think I will send a PR tomorrow.

**Comment by shoyer** [comment] 2017-04-04 02:38
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/8246. I'm closing this in favor of the other issue, which is older.

**Closed by shoyer** 2017-04-04 02:38 UTC
Labels: stat:contributions welcome, type:feature
