### ISSUE TITLE
'tf.Conv2D' op is neither a custom op nor a flex op error while converting ONNX model to TF Lite

### ISSUE THREAD

**Issue by shelkesagar29** [tensorflow/tensorflow#43963] opened 2020-10-12 21:02 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Conda binary 2.2.0
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**
My goal is to run a model trained in PyTroch on Edge TPU. I am getting this issue with a custom as well as standard Mobilenet V2 model.

Here is Colab Link

https://colab.research.google.com/drive/1giZg-g7PkLkGWb3bbMV890IFVWf_Es9f?usp=sharing

Steps
1. Get Mobilenet V2 model from torchvision
2. Convert to ONNX
    PyTorch: 1.6.0
    ONNX: 1.7.0

```
import torch
import torchvision.models as models
import torchvision.transforms as transforms

mobilenet = models.mobilenet_v2()

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

dummy_input = torch.rand((3, 224, 224))
dummy_input = normalize(dummy_input)
dummy_input = torch.unsqueeze(dummy_input, 0)
out = mobilenet(dummy_input)

torch.onnx.export(mobilenet, dummy_input, "pytorch_mnet.onnx", verbose=True, input_names=['input'], output_names=['output'])
```
3. Convert ONNX model to TF

`onnx-tf convert -i ./pytorch_mnet.onnx -o onnx_to_tf_mnet`

4. Convert to TFLite

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

quant = True
im_h = 224
im_w = 224
random_data = np.random.uniform(size=(100, im_h, im_w, 3))
random_data = random_data.astype(np.float32)

def representative_dataset_gen():
  for i in range(100):
    # Get sample input data as a numpy array in a method of your choosing.
    temp = random_data[i, :, :, :]
    temp_shape = np.shape(temp)
    temp = np.reshape(temp, (1, temp_shape[0], temp_shape[1], temp_shape[2]))
    yield [temp]

converter = tf.lite.TFLiteConverter.from_saved_model("./onnx_to_tf_mnet")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
if not quant:
    converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
    ]
else:
    converter.representative_dataset = representative_dataset_gen
    converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS_INT8
    ]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8

tflite_model = converter.convert()
open("./mnet_quant.tflite", "wb").write(tflite_model)

```
This throws error,
`<unknown>:0: error: loc(fused["convolution_7169@__inference___call___23399", "PartitionedCall/convolution_7169"]): 'tf.Conv2D' op is neither a custom op nor a flex op`

However, when I set quant=False and just get normal tflite model, it seems to work.

**Comment by amahendrakar** [comment] 2020-10-13 09:48
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/2ff55f41493495a07a91fbd10bcbb48a/43963-2-2.ipynb). Session crashes on running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/2660cd32b2a25e73f0cb26a481c7b8ea/43963.ipynb).

Whereas with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/7e9ff5cb19688a09dd41db8007a5f3d6/43963-tf-nightly.ipynb#scrollTo=fOL4A0BbklGz), the error is `RuntimeError: tensorflow/lite/kernels/conv.cc:332 input->dims->data[3] != filter->dims->data[3] (224 != 3)Node number 3 (CONV_2D) failed to prepare.`. Please find the attached gist. Thanks!

**Comment by shelkesagar29** [comment] 2020-10-13 16:23
@amahendrakar After your last comment, with TF-nightly, it looked like channel order issue between PyTorch and TensorFlow.

I made following changes,
`random_data = np.random.uniform(size=(100, 3, im_h, im_w))` (Basically used PyTorch channel order)

Now process runs but model is wrong and huge. (~12MB)

**Comment by jvishnuvardhan** [comment] 2020-10-13 21:01
@shelkesagar29 When i tried your code, the tflite model is of size 8 MB. What do you mean by `model is wrong`?

**Comment by shelkesagar29** [comment] 2020-10-14 16:26
@jvishnuvardhan 
I tried code from the gist you created and created [a new gist](https://colab.research.google.com/gist/shelkesagar29/91ac368525581738b81f2ac480ddb40a/43963-tf-nightly.ipynb#scrollTo=8Lu-m-D7ekxp) by adding some code.

What I meant previously by "model is wrong" is 
1. Model can't be compiled by edgetpu compiler
    It gives a weird error since ADD op is getting only single input.

Then I tested using tflite interpreter and inference seems to run without any issue!
```
loaded_model = tf.keras.models.load_model('/content/torch_mnet_to_tf')
t = loaded_model.gen_tensor_dict
```
Is there any way I can get all nodes of saved model using above code snippet? I think analyzing nodes will give some idea of what is going on.

**Comment by karimnosseir** [comment] 2020-11-21 01:28
The add has one input when you view it, because the second input is a constant, if you select it you can see that it is const.
As for why it doesn't compile for edgetpu compiler, i am not familiar with EdgeTPU compiler.
May be reach to the EdgeTPU compiler to check if there is a missing feature.

I am going to close the issue, since it looks like edgetpu compiler question.
Feel free to reopen if you have more questions.

Thanks

**Closed by karimnosseir** 2020-11-21 01:28 UTC
Labels: TF 2.2, TFLiteConverter, comp:lite, stat:awaiting tensorflower, type:support
