### ISSUE TITLE
TF2 Keras rms_optimizer.get_updates error

### ISSUE THREAD

**Issue by jheffez** [tensorflow/tensorflow#27568] opened 2019-04-06 10:54 UTC
Hello, trying to migrate from standalone Keras and TF 1.12 to TF2.Keras. 
I used the tf2 conversion script and, then changed import keras.xx to import **tensorflow**.keras.xx. Yet, still getting error: `TypeError: get_updates() takes 3 positional arguments but 4 were given. `

in the line:
`updates = self.rms_optimizer.get_updates(self.model.trainable_weights, [], loss)`

It works in the standalone Keras and tf 1.12. Any idea what else I need to change. or is it a bug in tf2.
using tf-nightly-2.0-preview           2.0.0.dev20190404 in windows 10/Python 3.6.6

**Comment by achandraa** [comment] 2019-04-08 12:47
Thank you for reaching out to us. Can you please provide minimum reproducible code snippet to help us proceed further and verify what is going wrong.

**Comment by achandraa** [comment] 2019-04-15 08:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-15 08:12 UTC
Labels: comp:keras, stat:awaiting response, type:support

**Comment by vbogach** [comment] 2019-05-16 13:03
I got the same problem when trying to use A3C model from https://github.com/germain-hug/Deep-RL-Keras. Basically, what's going on is this:
```python3
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import Model
from tensorflow.keras.optimizers import RMSprop
import tensorflow.keras.backend as K

# Create shared model.
shared_input = Input((10,))
layer = Dense(64, activation='relu')(shared_input)
layer = Dense(128, activation='relu')(layer)
shared_model = Model(shared_input, layer)

# Create actor model on top of shared model.
actor_layer = Dense(128, activation='relu')(shared_model.output)
actor_output = Dense(5, activation='softmax')(actor_layer)
actor_model = Model(shared_model.input, actor_output)

# Create critic model on top of shared model.
critic_layer = Dense(128, activation='relu')(shared_model.output)
critic_output = Dense(1, activation='linear')(critic_layer)
critic_model = Model(shared_model.input, critic_output)

# Create actor optimizer
action_pl = K.placeholder(shape=(None, 5))
advantages_pl = K.placeholder(shape=(None,))
weighted_actions = K.sum(action_pl * actor_model.output, axis=1)
eligibility = K.log(weighted_actions + 1e-10) * K.stop_gradient(advantages_pl)
entropy = K.sum(actor_model.output * K.log(actor_model.output + 1e-10), axis=1)
loss = 0.001 * entropy - K.sum(eligibility)
# TypeError: get_updates() takes 3 positional arguments but 4 were given.
updates = RMSprop(lr=0.0001, epsilon=0.1, rho=0.99).get_updates(actor_model.trainable_weights, [], loss)
actor_opt = K.function([actor_model.input, action_pl, advantages_pl], [], updates=updates)
```

**Comment by vbogach** [comment] 2019-05-17 11:53
I believe this is fixed by changing
```python3
get_updates(actor_model.trainable_weights, [], loss)
```
to
```python3
get_updates(params=actor_model, loss=loss)
```

**Comment by Hemanth987** [comment] 2020-08-18 13:28
no
