### ISSUE TITLE
Async prefetching queue data on GPU

### ISSUE THREAD

**Issue by nmiculinic** [tensorflow/tensorflow#5722] opened 2016-11-19 23:29 UTC
For example look at te following code:
```python
X = fifo_queue.dequeue_many(100) # Some queue
...  # some processing
f  # reslut of computation
```

```fifo_queue``` holds all its variable and data in RAM, that is on CPU since there's no GPU kernel for it (nor for any other queue that I'm aware of.

However upon running:
```python
sess.run(f)
```

There's a huge bottleneck for dequeuing and copying data from CPU to GPU which could be done async. Here is example of timeline: http://imgur.com/a/1cGHf

How can I tell tensorflow to async prefetch data on GPU (for example 3xbatch size examples or something like that) so that I avoid waiting for QueueDequeuMany and MEMCPYHtoD operations? Closest I could find for an answer is [this](http://stackoverflow.com/questions/38751736/understanding-tensorflow-queues-and-cpu-gpu-transfer) stackoverflow post, but it didn't shed enough light on the problem.

**Comment by tomrunia** [comment] 2016-11-20 11:16
Relevant: https://github.com/tensorflow/tensorflow/issues/3009

**Comment by prb12** [comment] 2016-11-21 19:23
As you say, queues are currently only implemented on CPU and cannot cross devices.

If you don't have any useful computation which can happen while the *async* transfer D2H is in progress then the only way to overlap this transfer would be to do it in a different call to session.run and store the result in some sort of variable.  However, this would rely on coordination between steps 

The only stateful ops available on GPU are Variables and TensorArrays.  

You *could* imagine manually building some sort of pipeline or double-buffering where the session.run call computed on one Variable and simultaneously transferred the input for the next step into a second Variable.

Alternatively, you could look at how the dynamic while loop speculatively executes multiple loop iterations in parallel, overlapping transfers for subsequent steps.

**Comment by ebrevdo** [comment] 2016-11-22 03:35
Four options:

1. Don't use queues; batch input yourself each iteration.
2. Run parallel training threads in parallel; while one is reading another is training
3.  Modify a queue to use GPU; not an impossible task but also not fun
4. Improve the performance of existing queues by optimizing the c++ code

TensorArrays are per step objects, thus not useful for this case

**Comment by ppwwyyxx** [comment] 2016-11-30 07:20
Would be very awesome to have this feature!
I've compared a resnet18 on two different input method:
1. Use a constant variable on GPU (not useful in practice)
2. Use a dequeued tensor, and having a Python thread running enqueue op in a loop.
In my experiment (1) is about 10% faster than (2).

btw, [convnet-benchmarks](https://github.com/soumith/convnet-benchmarks) use (1) to benchmark tensorflow.

**Comment by prb12** [comment] 2016-11-30 17:16
@mrry Do you have any ideas about how best to mask GPU transfer latency of large input tensors?

**Comment by mrry** [comment] 2016-11-30 17:29
In principle one could write a version of the `FIFOQueue` that managed GPU buffers rather than CPU buffers, and then use the existing mechanisms (like queue runners) to drive a subgraph that copies the data from CPU to GPU and enqueues it in this queue. I'm not sure what the relative latency is between these copies and the framework overhead to run a step that performs the enqueuing, but I suspect it could be profitable in some cases.

**Comment by yaroslavvb** [comment] 2016-11-30 19:35
@nmiculinic a way to provide evidence that GPU-resident queue is useful could be to implement it on the client side using a rotating buffer of GPU-pinned variables and measure the speed-up, ie https://github.com/tensorflow/tensorflow/issues/4526#issuecomment-249021613

**Comment by nmiculinic** [comment] 2016-12-01 22:16
@yaroslavvb  I've tried to implement double buffering and run some test: Full code is here: http://pastebin.com/Rcg76XPM

1) CPU only

Without buffering, that is async prefetching:
https://i.imgur.com/DWS3OKZ.png

With buffering:
https://i.imgur.com/gi4wgUu.png

As you can see there's performance improvement when queue element is already loaded in memory even for CPU... not sure why

2) GPU

With GPU this is even more pronounced due to data copying:
Without buffer:
https://i.imgur.com/v7sIKF8.png
With Buffer:
https://i.imgur.com/j6bF67e.png

I'm not sure why is only dequeue async in my code, not also data transfer. If somebody could give me some feedback I'd much appreciate it. Nevertheless speed improvement is obvious and immediate.

**Comment by TimZaman** [comment] 2016-12-11 00:56
@yaroslavvb what do you think of @mniculinic's adove code? Is that what you intended? I have tried to hunt down this copy overhead problem, and have found you have suggested this solution in half a dozen cases. Might be nice to nail it down. I'm willing and able to help.

**Comment by prb12** [comment] 2016-12-11 02:13
Two comments on the code:
1) Measuring the execution time of a step when you are tracing and retrieving a large RunMetadata proto back to Python is never a good idea - especially if you haven't installed the C++ protobuf library.  
2) I *think* there's probably a simpler way to do this:
   * Place a (non-trainable) Variable on the GPU to hold a single cached value.  
   * Each step, in parallel: 
       * Take a snapshot of the current value of the GPU variable using an Identity op
       * Dequeue from the FIFO (i.e. kick off the copy from the CPU)
   * Serialized after the read, Assign the value from the FIFO into the variable for use in the next step.
   * Compute with the snapshot value.

This may be equivalent to your code... but I admit I got a little lost.
I'm also not 100% sure whether this would play well with auto-gradient code though...

**Comment by TimZaman** [comment] 2016-12-11 18:07
OK @prb12 @yaroslavvb @nmiculinic, I implemented the rotating buffer with a size of 2. One is where the GPUs pull from, the other is where the feeder pushes to.
I took me a while to get the most optimal implementation while avoiding R/W race conditions.
I made a Gist for this: https://gist.github.com/TimZaman/639576c25693ca4890457efa5f67d103

1. init stage: `sess.run([put_in_buffer])`
2. init stage: `sess.run([move_buffer])`
3. loop: `sess.run([pull])`

Defitinion of `pull`:
```py
with tf.control_dependencies([move_buffer]):
        pull = tf.group(put_in_buffer, test_out)
```
So `pull` first refreshes the buffer, and then simultaneously puts new data in the buffer, and reads for GPU computation from the other buffer element.

I have a lot of trouble with these `control_dependencies`: the above yields accurate results, but if you read carefully i (1) push (2) move (3) loop(move, put_in_buffer, test_output). As you can see, i move 2x on the first iteration, but the value stays the same.
The Gist is setup such that i can monitor the values of the both buffers and the output. Here is an output where the first 20 buffer values are 0:1:20:
```
[BUF_IN][BUF_OUT][RESULT]:[[[1 1 1]]...][[[0 0 0]]...][0]
[BUF_IN][BUF_OUT][RESULT]:[[[2 2 2]]...][[[1 1 1]]...][0.99999082]
[BUF_IN][BUF_OUT][RESULT]:[[[3 3 3]]...][[[2 2 2]]...][1.9999816]
[BUF_IN][BUF_OUT][RESULT]:[[[4 4 4]]...][[[3 3 3]]...][3.0000162]
[BUF_IN][BUF_OUT][RESULT]:[[[5 5 5]]...][[[4 4 4]]...][3.9999633]
[BUF_IN][BUF_OUT][RESULT]:[[[6 6 6]]...][[[5 5 5]]...][5.0000668]
[BUF_IN][BUF_OUT][RESULT]:[[[7 7 7]]...][[[6 6 6]]...][6.0000324]
[BUF_IN][BUF_OUT][RESULT]:[[[8 8 8]]...][[[7 7 7]]...][6.9999766]
[BUF_IN][BUF_OUT][RESULT]:[[[9 9 9]]...][[[8 8 8]]...][7.9999266]
[BUF_IN][BUF_OUT][RESULT]:[[[10 10 10]]...][[[9 9 9]]...][8.99991]
[BUF_IN][BUF_OUT][RESULT]:[[[11 11 11]]...][[[10 10 10]]...][10.000134]
```
The above reveals that the input buffer is always +1 with respect to the output buffer, and the output buffers value is the same as the result: so it's working.
For this particular example, you can see the amazing benefit of a GPU resident queue:
![image](https://cloud.githubusercontent.com/assets/7721540/21082114/1cfdbe10-bfdd-11e6-8cb0-69bc352f6963.png)

Now, I would like to reiterate this comment https://github.com/tensorflow/tensorflow/issues/4526#issuecomment-249026120 from @mkolod:

> I think though that it would be good for this to be baked into the framework rather than shifting flow control workarounds to the user. Data prefetch is pretty much a universal need, since the input has to come from somewhere, hopefully in an efficient manner to leverage available compute cycles.

I would like to suggest opening up this issue: https://github.com/tensorflow/tensorflow/issues/4526#issuecomment-249026120
It would bring amazing benefit from operations that are heavy on data, and light on compute.

**Comment by sjperkins** [comment] 2016-12-12 13:08
I wonder if it's possible to build the prefetch into the scheduler? Consider the following diagram:

![img_20161212_134953255](https://cloud.githubusercontent.com/assets/3530212/21098743/4774b4dc-c073-11e6-9fa1-f90ecb4a213b.jpg)

We have three separate sub-graphs [(foo->bar, qux->baz, plug->thud)] that require execution on a (GPU?) device, depending on inputs [(a,b,c),(f,g,h,i,k), (l,m)] located across a device boundary and whose outputs [(d,e),(k),(n)] must be transmitted across the boundary once they are complete.

As it currently stands, tensorflow appears (to me) *to treat transfers and compute operations as the same "type" of operation, rather than as operations that can be concurrently scheduled*.  As @prb12  notes  in https://github.com/tensorflow/tensorflow/issues/2848, Recvs are scheduled immediately and Sends are scheduled once the input data is available.  So on a rough timeline the above sub-graphs seem to currently be scheduled as (see https://github.com/tensorflow/tensorflow/issues/2848 for e.g. where sends are scheduled immediately)

![img_20161212_141704007](https://cloud.githubusercontent.com/assets/3530212/21099282/05f56d00-c076-11e6-9983-4919a9cce0da.jpg)

The problem with this scheduling is that it wastes both I/O bandwidth and device compute. Given that these operations *can* be concurrently scheduled an optimal order of transfer and execution might be:

![img_20161212_135248066](https://cloud.githubusercontent.com/assets/3530212/21098800/945d2130-c073-11e6-8eef-b3d28ebeb4f9.jpg)

(a,b) must be transferred before foo can execute, (c) must be transferred before bar can and so on. The output transfers for [(d,e), (k), (n)] can be scheduled last.

The point is that scheduling the ops on the (GPU?) device necessarily imposes an ordering on how the inputs should be transferred. While my understanding of how ops are currently scheduled is limited  I would ideally expect it to be something like [a, b, foo, c, bar, f, g, h, qux, i, j, baz, l, plug, m, thud, d, e, k, n].

Running the ops *as soon* as their inputs are available should use the device optimally. If your compute beats your I/O then the device is used optimally. If not, then you've done the best you can given the algorithms in the ops.

All this information is available in the graph. I think the tricky part is estimating how many sub-graphs can be scheduled in one go -- this would involve balancing device memory vs the size of the input , temporary result and output tensors. But looking at https://github.com/tensorflow/tensorflow/issues/2848 and other issues suggests that tensorflow does this already. It just doesn't currently schedule transfers and executions optimally.

Further optimisations based on the number of copy engines on the GPU are possible.

**Comment by prb12** [comment] 2016-12-12 17:42
@sjperkins Thanks for your suggestions.  Here are some brief comments: (I don't really have time to go into this at length)

>  Recvs are scheduled immediately and Sends are scheduled once the input data is available. So on a rough timeline the above sub-graphs seem to currently be scheduled as (see #2848 for e.g. where sends are scheduled immediately)

I think you are confused about what `Send` and `Recv` *ops* actually do.   

Each transfer between devices involves two ops - the Send op on the source device is executed as soon as its input tensor is "ready". (subtlety - on GPU this means when the op which computes the Tensor has been added to the GPU compute stream.)  The 'Recv' op has no inputs, an hence is ready to be dispatched immediately, but the Send and Recv ops actually execute a _rendezvous_ and the actual copy/DMA between devices is scheduled once the rendezvous is complete.   Many Send and Recv ops can be dispatched simultaneously, and they do not (at this point) have any ordering constraints with respect to computation ops.

> The point is that scheduling the ops on the (GPU?) device necessarily imposes an ordering on how the inputs should be transferred.

I strongly encourage you to read `executor.cc`.  The above described mechanism is there purely to capture these ordering dependencies in  a way which is safe for async memory allocation and kernel execution.

> appears (to me) to treat transfers and compute operations as the same "type" of operation, rather than as operations that can be concurrently scheduled. 

This isn't really true. Transfers to and from GPU are executed on their own CUDA streams - and hence can happen in parallel with compute.  The ops dependent on Tensors which are being transferred to GPU cause the compute strream to take a dependency on the memcpy_host_to_device stream using the CUDA `RecordEvent` and `StreamWaitEvent` primitives.   There are some awkward case to deal with here and the current implementation is suboptimal in a couple of places (mainly due to there being a single compute stream), but it's a lot better than what you describe.


@TimZaman 
> It would bring amazing benefit from operations that are heavy on data, and light on compute.

This is really not a very common case in my experience... e.g. when training an inception model on a single GPU the step time is around 2ms and DMA transfers are largely in the noise.  Latency sensitive inference steps may be more of an issue.  I would be open to seeing more evidence of where this matters for non-trivial workloads.

**Comment by llhe** [comment] 2016-12-13 09:38
@prb12 
> This is really not a very common case in my experience... e.g. when training an inception model on a single GPU the step time is around 2 seconds and DMA transfers are largely in the noise. Latency sensitive inference steps may be more of an issue. I would be open to seeing more evidence of where this matters for non-trivial workloads.

What about the shallow model (such as LR, deep and wide) workloads? I think this should be one of the heavy on data case. The H2D transfer may not be the major bottleneck compared to IO, but indeed it can improve if async transfer is supported.

**Comment by TimZaman** [comment] 2016-12-13 09:49
The Inception model example and a 2 second step time doesn't sound lightweight. Another example like given by @llhe; anyone who's doing light, realtime things can't generally use models that heavy. My particular model takes steps in the order of tens of ms. A GPU queue would make perfect sense to me.

**Comment by sjperkins** [comment] 2016-12-16 13:53
@prb12 Thanks for taking the time to write your response, the information is very useful information for those coming from a CUDA background.

> Each transfer between devices involves two ops - the Send op on the source device is executed as soon as its input tensor is "ready". (subtlety - on GPU this means when the op which computes the Tensor has been added to the GPU compute stream.) The 'Recv' op has no inputs, an hence is ready to be dispatched immediately, but the Send and Recv ops actually execute a rendezvous and the actual copy/DMA between devices is scheduled once the rendezvous is complete.

I browsed through the code, but was unable to follow through all the Send/Recv/Rendezvouz/CUDA abstractions. Briefly, is this similar to the following pattern for a GPU to CPU transfer? In one thread, asynchronously issue:

```cpp
// for some kernel computing a result placed in d_result
// kernel<..., stream>(arg0, arg1, d_result);

// "Send op" starts here
cudaMemcpyAsync(s_result, d_result, stream);
cudaEvent_t done;
cudaEventRecord(done, stream);
```

and in some synchronisation thread:

```cpp
// "Recv op" starts here
cudaEventSynchronise(done);
release_to_pool(d_result);
probably_in_another_thread_use(s_result);
```

> This isn't really true. Transfers to and from GPU are executed on their own CUDA streams - and hence can happen in parallel with compute. The ops dependent on Tensors which are being transferred to GPU cause the compute strream to take a dependency on the memcpy_host_to_device stream using the CUDA RecordEvent and StreamWaitEvent primitives. There are some awkward case to deal with here and the current implementation is suboptimal in a couple of places (mainly due to there being a single compute stream), but it's a lot better than what you describe.

OK I'm familiar with this pattern. Thanks for clarifying this, but I have an example below where I'm struggling to achieve this overlap through submitting separate compute to `tf.Session.run` in multiple threads.

> In fact, what currently happens is that a, c, c, f, g, h will all get scheduled on some **non-deterministic order** on the device_to_host stream shortly after their inputs are available on the CPU device.

The non-determinism is what I want to niggle about. More below:

> As soon as the async MemcpyH2D has been enqueued for all of the inputs for foo, the compute stream will be serialized on the copy stream (using an event) and the CUDA kernel for foo will be enqueued on the compute stream. Once foo and bar have been enqueued, the device_to_host stream is made to depend on the compute stream using another event, and an async MemCopyD2H is ennqueued on the device_to_host stream. This can execute concurrently wrt quz, baz, plug, thd et al.

> Each transfer between devices involves two ops - the Send op on the source device is executed as soon as its input tensor is "ready"

OK tensorflow is scheduling ops non-deterministically because its not assuming knowledge of when inputs will become available (network transfers, multiple ops running on multiple CPU cores). Yeah I can see why this is a difficult problem. I think this is perhaps where CUDA programmers struggle. e.g. thinks like "I know all my inputs are on the CPU and can be scheduled in a specific order, why isn't tensorflow scheduling it like I know I could do?"

*BUT* this non-determinism does bite as it can result in input transfers for multiple sub-graphs being unnecessarily scheduled upfront before compute occurs (example below).  Perhaps a possible solution is to logically group inputs required by a GPU op for transfer? I don't know enough of the scheduling internals to ascertain whether this is a reasonable suggestion. A GPU queue would achieve the same effect

I've another concrete example to demonstrate. We're developing radio telescope simulator and the challenge (in terms of data transfer) is that 550MB (!) voxel cubes are used to model how the beam of an antenna affects the signal from a radio source. I've sharded feeding (3 threads), compute (3 threads) and output dequeues (1 thread). I have 6 units of compute that I want to perform. The algorithm is compute bound.

![titan_x_3_shards](https://cloud.githubusercontent.com/assets/3530212/21262989/ef9e90b6-c39c-11e6-98fd-c8e1630dd628.png)

I've attached:
-  [CUDA profile](https://github.com/tensorflow/tensorflow/files/657167/nvvp_prof.zip) on a Titan X, (merging RunMetadata objects for multiple threads produces a trace file that is too large for chrome).
- Chrome [trace](https://github.com/tensorflow/tensorflow/files/657206/timeline.json.zip) a on laptop GTX960. Single thread feeding, single thread computing.

The above profile shows the 6 units of compute sheduled into two sections of 3 units each (presumably because the 3 compute threads submit work to `Session.run` at a similar time). As the above profile and image shows, the 3 voxel cubes (1.5GB!) associated with 3 work units (or, using the terminology in my previous post, sub-graphs) scheduled for transfer upfront. Additionally the 3 transfers for the last 3 work units/sub-graphs are not overlapped with the compute of the first 3.

This is what I was describing using the toy example in the previous post:

![prev](https://cloud.githubusercontent.com/assets/3530212/21099282/05f56d00-c076-11e6-9983-4919a9cce0da.jpg)

**Comment by eraoul** [comment] 2017-01-09 23:08
+1 to built-in support for GPU-based data queues. Not all of us are running huge inception-style models with images. I definitely have a application with a smaller network but huge data sets, and got a graphics card with a large amount of RAM in order to queue up all the data in memory. I was really surprised that some people don't consider this a standard use case.

**Comment by yaroslavvb** [comment] 2017-01-13 03:01
Looks like there's `enqueue` like op with GPU support being added -- github.com/tensorflow/tensorflow/commit/85acf52a

**Comment by sjperkins** [comment] 2017-01-14 06:12
This is great news. Thanks to those who put this together. I can't wait to try it out.

**Comment by post2web** [comment] 2017-02-20 21:03
@yaroslavvb Can you suggest how to use this GPU support?

**Comment by yaroslavvb** [comment] 2017-02-20 21:29
@post2web -- @tfboyd is working on https://github.com/tensorflow/tensorflow/issues/7679 which should have an example of using these ops, once it's ready

**Comment by agupta74** [comment] 2017-03-28 22:20
I am observing the issue where "Host to Device" data tx. does not overlap with GPU execution using the rotating buffer code (published by TimZaman on Dec 11, 2016). Is this a known issue? I also tried Stage/Unstage APIs but have the same issue. It looks like that there is a plan to publish the scripts in order to perfrom "Async Host to Device transfers" (as mentioned by zheng-xq on Feb 13 in  #4526)

**Comment by yaroslavvb** [comment] 2017-03-28 22:52
@agupta74 releasing of those scripts is tracked in https://github.com/tensorflow/tensorflow/issues/7679

**Comment by skye** [comment] 2017-06-16 21:15
It appears this has been resolved. I'm gonna close, but please let me know if it should be reopened.

**Closed by skye** 2017-06-16 21:15 UTC
Labels: type:feature

**Comment by EloiZ** [comment] 2017-06-27 14:01
Do you know when the latest version of StagingQueue (i.e. with capacity and memory_limit options) will be integrated in tensorflow releases? Is it planned to add examples of how to use?

**Comment by tfboyd** [comment] 2017-06-27 15:14
@EloiZ  Examples of how to StagingQueue is in [here](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py).  Depending on your experience with TensorFlow it may or may not be hard to get working.  There is some documentation [here](https://www.tensorflow.org/performance/performance_models)but it is far from step by step.  

I cannot promise a date but in Q3 we are working on making DataSets as fast as our custom solution in the tf_cnn_benchmark, which may include suing StagingQueues.  Our goal is to use DataSets in the StagingQueues.  From my own personal testing [DataSets](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/data) is much faster than queue readers and starts to show more significant gains when pushing multiple-gpus. 

DataSets instructions / guide should be on tf.org soon, I saw a CL moving the content.  The link I provided is to github so if it moves on me I am sorry.  That link is what I used to get up to speed myself.

Finally, DataSets will move to Core likely with TF 1.4.  There are no rumors of major changes but the team wants to keep it in contrib for one more release to flush out any possible API changes before moving to core.

**Comment by agupta74** [comment] 2017-08-08 20:33
I wrote a simple script with Timeline API in order to understand if StagingQueue is infact overlapping data transfer with GPU processing but for some reason I did not see any overlap in computation and communication in the timelines shown below. Infact the gap between 2 GPU processing tasks increased on adding the StagingQueue. Any ideas on what could explain this behavior?  Is there anything wrong in my usage of StagingQueues? I am attaching a couple of Python scripts in order reproduce the behavior.

**With StagingQueue (using 1 GPU)**

python InferenceTest.py 1 1

![staging](https://user-images.githubusercontent.com/21690396/29092688-118a996a-7c3c-11e7-9337-d4b8c3aeb9f7.png)

**No StagingQueue (using 1 GPU)**
python InferenceTest.py 1 0

![nostaging](https://user-images.githubusercontent.com/21690396/29092782-59724174-7c3c-11e7-91d9-5b997a38a5da.png)

[Inference.txt](https://github.com/tensorflow/tensorflow/files/1209463/Inference.txt)
[InferenceTest.txt](https://github.com/tensorflow/tensorflow/files/1209462/InferenceTest.txt)
