### ISSUE TITLE
CUDA_ERROR_ILLEGAL_INSTRUCTION occurs while running MNIST on Cuda 3.0 device

### ISSUE THREAD

**Issue by liujunyi-sjtu** [tensorflow/tensorflow#665] opened 2016-01-01 15:55 UTC
Thanks for your working on Cuda compute capability 3.0 devices.
I've installed tensorflow from source on ubuntu14.04+Cuda Toolkit 7.0+CUDNN Toolkit 6.5 with NVIDIA driver 352.63.
The MNIST program on tutorial always goes well at first but crashes after a few seconds with CUDA_ERROR_ILLEGAL_ADDRESS or CUDA_ERROR_ILLEGAL_INSTRUCTION like below:
...
step 1300, training accuracy 0.94
step 1400, training accuracy 0.96
step 1500, training accuracy 0.98
step 1600, training accuracy 0.94
step 1700, training accuracy 0.96
step 1800, training accuracy 0.96
step 1900, training accuracy 1
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:123] Unexpected Event status: 1
Aborted (core dumped)

or
...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_INSTRUCTION
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:123] Unexpected Event status: 1
Aborted (core dumped)

Here's my dmesg information:
[  436.027718] nvidia_uvm: Loaded the UVM driver, major device number 248
[  569.125603] NVRM: GPU at PCI:0000:01:00: GPU-4e535941-7a6a-dcbe-2873-5faabb6099e7
[  569.125625] NVRM: Xid (PCI:0000:01:00): 13, Graphics SM Warp Exception on (GPC 0, TPC 0): Out Of Range Address
[  569.125640] NVRM: Xid (PCI:0000:01:00): 13, Graphics SM Global Exception on (GPC 0, TPC 0): Physical Multiple Warp Errors
[  569.125650] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x504648=0x20000e 0x504650=0x24 0x504644=0x13eff2 0x50464c=0x7f
[  569.125750] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 0020, Class 0000a0c0, Offset 00001b0c, Data 00000000

Did anyone meet the problem above?

**Comment by zheng-xq** [comment] 2016-01-07 00:56
@liujunyi-sjtu, I cannot reproduce the problem on my side. Could you provide some more information? How did you bulid and run the binary?

If we still cannot reproduce this problem, then you probably have to run cuda-memcheck on your side, and post the relevant results. Thanks.

**Comment by girving** [comment] 2016-06-08 23:43
Closing due to lack of information.  I'm happy to reopen if more information arises.

**Closed by girving** 2016-06-08 23:43 UTC
Labels: cuda

**Comment by johnfrombluff** [comment] 2016-06-11 09:34
Firstly, thanks for tensorflow!  

I am experiencing a similar issue. I installed tensorflow on Fedora 23 via **pip**.  My CUDA installation seems to be working fine, as I can use the R package **gputools** with spectacular results. However the MNIST example fails with a misaligned memory error. My graphics card info from **lspci** is:

01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)

The attached file shows the script I'm trying to run, and the results when running with **cuda-memcheck**.

And here is some output from **dmesg**. Do you need more information? And thanks again for this wonderful software!

[30573.966313] NVRM: Xid (PCI:0000:01:00): 13, Graphics SM Warp Exception on (GPC 0, TPC 4): Misaligned Address
[30573.966336] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x506648=0x3000f 0x506650=0x0 0x506644=0xd3eff2 0x50664c=0x7f
[30573.966358] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 0028, Class 0000b0c0, Offset 00001b0c, Data 00000000
[30829.981713] NVRM: Xid (PCI:0000:01:00): 43, Ch 00000028, engmask 00000101

[tensorflow-error.txt](https://github.com/tensorflow/tensorflow/files/310171/tensorflow-error.txt)

**Comment by girving** [comment] 2016-06-11 18:19
@johnfrombluff Why do you think it is a related error?  Unrelated errors should be filed as separate issues.

**Comment by johnfrombluff** [comment] 2016-06-11 21:57
What a fool I am. Sorry to waste your time.
