### ISSUE TITLE
Bug in function estimator_train when 'evaluator' included in TF_CONFIG 

### ISSUE THREAD

**Issue by mandyclustar** [tensorflow/tensorflow#34192] opened 2019-11-12 09:27 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): rc1.13
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0/7.6
- GPU model and memory: Run in GPU

**Describe the current behavior**

with the following configurations:

 `os.environ['TF_CONFIG'] = json.dumps({"cluster": {"evaluator": ["10.0.26.2:4000"], "ps": ["10.0.26.2:5000"], "worker": ["10.0.26.2:6000"]}, "rpc_layer": "grpc", "task": {"index": "0", "type": "worker"})`

Running estimator.train(), the output from the command line is

```
Traceback (most recent call last):
  ...
    model_estimator.train(input_fn=lambda: input_fn(image_ids=train_id), steps=global_step)
  File "/home/zxy/steel/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 405, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/zxy/steel/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1169, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/zxy/steel/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1227, in _train_model_distributed
    hooks)
  File "/home/zxy/steel/lib/python3.6/site-packages/tensorflow/python/distribute/estimator_training.py", line 304, in estimator_train
    if 'evaluator' in cluster_spec:
TypeError: argument of type 'ClusterSpec' is not iterable
```

**Describe the expected behavior**

When calling estimator.train with 'evaluator' included in RunConfig, a ValueError should be reported. The following is the fragment code in estimator_training.py. 
    
    if 'evaluator' in cluster_spec:
        raise ValueError("'evaluator' job is not supported if you don't use "
                         '`train_and_evaluate`')

Here the value of cluster_spec is like ClusterSpec({'evaluator': ['10.0.26.2:4000'], 'ps': ['10.0.26.2:5000'], 'worker': ['10.0.26.2:6000']})

if 'evaluator' in cluster_spec.jobs which is the way it should be.

**Comment by mandyclustar** [comment] 2019-11-12 09:52
Only r1.13 seems to have this problem

**Comment by gadagashwini** [comment] 2019-11-13 08:14
@mandyclustar, Please provide the complete code to reproduce the reported issue here. Thanks!

**Comment by gadagashwini** [comment] 2019-11-22 10:33
@mandyclustar, Any update.

**Comment by gadagashwini** [comment] 2019-12-02 11:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-12-02 11:27 UTC
Labels: TF 1.13, comp:apis, stat:awaiting response, type:support
