### ISSUE TITLE
tfconvert float to float_ref valueError 

### ISSUE THREAD

**Issue by joyicejin** [tensorflow/tensorflow#21294] opened 2018-08-01 02:08 UTC
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:NA
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:tensorflow-gpu 1.9
- **Python version**:3.5
- **Bazel version (if compiling from source)**:0.15
- **GCC/Compiler version (if compiling from source)**:5.4
- **CUDA/cuDNN version**:9.0/7.0
- **GPU model and memory**: geforce 1070/8G
- **Exact command to reproduce**:
Using the command:
 tflite_convert  --graph_def_file=./opt.pb --output_format=TFLITE   --output_file=./model.tflite --inference_type=FLOAT  --input_arrays=inputs   --output_arrays=softmax --input_shapes=1,5000,1,1
You can collect some of this information using our environment capture script:

### Describe the problem
Converting a trained CNN+RNN  model which was freezed by the freeze_graph and optimized  command gives the valueError message:
Input 0 of node save/Assign was passed float from beta1_power:0 incompatible with expected float_ref

I guess the issue was caused by the Adam optimizer 

### The parameters saved after trainning process like this
![screenshot from 2018-08-01 10-06-34](https://user-images.githubusercontent.com/32789540/43496953-a018118a-9572-11e8-8aaf-c3001378a205.png)

What can I do now?

**Comment by tensorflowbutler** [comment] 2018-08-01 12:41
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by joyicejin** [comment] 2018-08-01 15:57
Thanks for your prompt help, and sorry to lack the information in the issue template, cause I think it has little relevance in my case. I got the same issue when using tensorflow version of 0.12 and cuda8/dunddn6.
I have updated the issue information above, please help.

**Comment by karmel** [comment] 2018-08-01 17:31
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Can you provide the code you are trying to run, and the relevant error traces?

**Comment by joyicejin** [comment] 2018-08-03 06:56
Sorry, maybe I should tell you my work now, I just want to convert my own defined tensorflow model into a tflite model which works in mobile phones.

In my code I use following codes to create an adam optimizer for trainning process
 
```
#Optimizer that use different learning rates for each part of the network
            train_op, grads_and_vars_op = adam_clipping_list_lr(
                loss=train_net.loss_op,              
                list_lrs=[0.00001, 0.0001],
                list_train_vars=[train_vars1, train_vars2],
                clip_value=10.0
            )
```

First I freezed the model by the freeze_graph.py in tensorflow reposite and  and optimized the model by the optimize_for_inference.py command.
The I  use the following command to produce a tflite mobile model.
`tflite_convert --graph_def_file=./opt.pb --output_format=TFLITE --output_file=./model.tflite --inference_type=FLOAT --input_arrays=inputs --output_arrays=softmax --input_shapes=1,5000,1,1`
But I got the following message:

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
2018-08-03 14:13:55.136839: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-03 14:13:55.241106: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-03 14:13:55.241540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.873
pciBusID: 0000:07:00.0
totalMemory: 7.93GiB freeMemory: 7.27GiB
2018-08-03 14:13:55.241554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-03 14:13:55.417519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-03 14:13:55.417569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-08-03 14:13:55.417575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-08-03 14:13:55.417775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7020 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:07:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 320, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 316, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 121, in _convert_model
    output_data = converter.convert()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/lite.py", line 309, in convert
    allow_custom_ops=self.allow_custom_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 225, in toco_convert
    input_data.SerializeToString())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 107, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b'2018-08-03 14:13:58.069666: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.069846: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070054: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070240: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070338: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070471: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070627: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.070771: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.074949: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Reciprocal\n2018-08-03 14:13:58.075008: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-03 14:13:58.099706: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 322 operators, 491 arrays (0 quantized)\n2018-08-03 14:13:58.103204: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 322 operators, 491 arrays (0 quantized)\n2018-08-03 14:13:58.103368: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l1_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.104557: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l5_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.105416: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l9_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.138101: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/FW/FW/MultiRNNCell/Cell0/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.142571: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/FW/FW/MultiRNNCell/Cell1/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.164082: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/BW/BW/MultiRNNCell/Cell0/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.168823: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/BW/BW/MultiRNNCell/Cell1/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.168978: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l12_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.171340: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 277 operators, 425 arrays (0 quantized)\n2018-08-03 14:13:58.171902: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l12_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.171985: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/BW/BW/MultiRNNCell/Cell1/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.172107: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/BW/BW/MultiRNNCell/Cell0/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.172222: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/FW/FW/MultiRNNCell/Cell1/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.172334: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l11_bi_gru/BiRNN/FW/FW/MultiRNNCell/Cell0/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.172541: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l9_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.172844: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l5_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.173163: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "rssEEG/l1_dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2018-08-03 14:13:58.175469: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 277 operators, 425 arrays (0 quantized)\n2018-08-03 14:13:58.178267: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:329] Total transient array allocated size: 256128 bytes, theoretical optimal value: 256000 bytes.\n2018-08-03 14:13:58.179561: F tensorflow/contrib/lite/toco/tflite/export.cc:330] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.contrib.lite.toco_convert(). Here is a list of operators for which  you will need custom implementations: RandomUniform, Reciprocal, TensorFlowSqrt, TensorFlowSquare, TensorFlowSum, Unpack.\nAborted (core dumped)\n'
None


Then I adoped the detailed conveting process, when I use the quantize_graph command below:
`sudo bazel-bin/tensorflow/tools/quantization/quantize_graph  --input=./op.pb --output_node_names="rssEEG/l13_softmax/Add" --output=./model.pb --mode=eightbit`

I got the metioned error message:
ValueError: Input 0 of node save/Assign was passed float from beta1_power:0 incompatible with expected float_ref.

Detailed message here:
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
tf.estimator package not installed.
Traceback (most recent call last):
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node save/Assign was passed float from beta1_power:0 incompatible with expected float_ref.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1302, in <module>
    app.run()
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/tools/quantization/quantize_graph.py", line 1273, in main
    importer.import_graph_def(tf_graph, input_map={}, name="")
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/media/joyice/ssdata/tensorflow/bazel-bin/tensorflow/tools/quantization/quantize_graph.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node save/Assign was passed float from beta1_power:0 incompatible with expected float_ref.

**Comment by tensorflowbutler** [comment] 2018-08-23 19:10
Nagging Assignee @miaout17: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gargn** [comment] 2018-09-06 18:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gargn** 2018-09-06 18:37 UTC
Labels: comp:lite
