### ISSUE TITLE
TensorRT engine requires consistent batch size

### ISSUE THREAD

**Issue by chiachunfu** [tensorflow/tensorflow#19211] opened 2018-05-11 00:11 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, custom SSD model
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: nvidia gpu cloud docker container 18.04 for V100
                                                                                from source for 1080 Ti
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9 / 7
- **GPU model and memory**: V100 (16GB) 1080Ti (11GB)
- **Exact command to reproduce**: N/A 

### Source code / logs
Run TF-TRT with custom SSD and got the following message:
F tensorflow/contrib/tensorrt/shape_fn/trt_shfn.cc:52] TensorRT engine requires consistent batch size

After commenting out the line 52 in trt_shfn.cc and recompile with bazel, the model ran properly and output expected results. Suspect that this dimension check has a bug and does not cover all the cases. 

Use the code example from [here](https://developer.download.nvidia.com/devblogs/tftrt_sample.tar.xz) and modify to load custom SSD model.

**Comment by tensorflowbutler** [comment] 2018-05-11 12:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by chiachunfu** [comment] 2018-05-11 14:32
Just update the field. Thanks!

**Comment by aaroey** [comment] 2018-05-14 21:12
@samikama

**Comment by samikama** [comment] 2018-05-14 22:37
The error there seems to be a little more restrictive than it is. An engine can run a smaller batch size than it is built for, but with less efficiency than it could if it was built for that batch size. However it can not run a batch size bigger than it is built for so it is not really wrong. We are going to change these code soon for other reasons and I will update the logic there then.

**Comment by tensorflowbutler** [comment] 2018-05-30 15:08
Nagging Assignee @aaroey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by samikama** [comment] 2018-06-09 03:31
With #19871 we have less dependence on to the batch size and will be able to create a new engine on the fly at the expense of compute time.

**Comment by tensorflowbutler** [comment] 2018-06-23 18:31
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-08 18:33
Nagging Assignee @samikama: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by samikama** [comment] 2018-07-13 02:45
This should be fixed with recent updates, #20350 specifically.

**Closed by samikama** 2018-07-13 02:45 UTC
