### ISSUE TITLE
Error in post-training quantization with TFLiteConverter

### ISSUE THREAD

**Issue by NEU-Gou** [tensorflow/tensorflow#30407] opened 2019-07-04 09:28 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly (1.15.0-dev20190704)
- Python version: 3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: GTX 2080Ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
RuntimeError when convert frozen graph to TFLite with `converter.optimizations = [tf.lite.Optimize.DEFAULT]` and `converter.representative_dataset = representative_data_gen`

`RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.No calibrator found for context.Node number 0 (PAD) failed to invoke.`

I double checked the shape of the input array which is [1, 512, 512, 3] and I can convert it to a float tflite model without any dynamic-sized tensor. I'm not sure where and what raised this error... 
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
My data generator:
```
    def representative_data_gen():
        for im_info in image_list:
            path = im_info.split(' ')[0]
            img = cv2.imread(path)
            img = letterbox_transform(img)
            img = normalize_image(img)
            img = np.expand_dims(img, 0)
            yield [img.astype('float32')]
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rmothukuru** [comment] 2019-07-05 09:44
@NEU-Gou ,
Code snippet provided seems to be incomplete. In order to expedite the trouble-shooting process, please provide a minimal code snippet so that we can reproduce your error. Thanks!

**Comment by rmothukuru** [comment] 2019-07-17 09:53
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-07-17 09:53 UTC
Labels: comp:lite, stat:awaiting response
