### ISSUE TITLE
Dev request -- LSTM RNN

### ISSUE THREAD

**Issue by KendallWeihe** [tensorflow/tensorflow#3463] opened 2016-07-22 16:16 UTC
I previously [posted](https://github.com/tensorflow/tensorflow/issues/3278) about processing 3D data in an LSTM network with Tensorflow. It turns out Grid LSTM networks are what would work best. Already applied in contrib gridd_rnn.py. [This](http://arxiv.org/abs/1507.01526) paper (Grid LSTM) outlines Grid LSTM, but they also mentioned something I found to be a great idea.

I don't believe there is a way for Tensorflow to currently support this natively. 

The idea goes, in between each LSTM RNN step, instead of simply passing outputs to the next step, outputs are first passed through a single layer MLP. In other words there is a `tf.matmul` in between each step.

What do you think? It seems like a simple enough feature to implement in the `RNN` initialization.

**Comment by ebrevdo** [comment] 2016-07-22 23:45
I believe this is partially done in the LSTMCell, if you use proj_size > 0.

**Comment by KendallWeihe** [comment] 2016-07-23 00:15
I don't see a `proj_size` in the BasicLSTMCell args

**Comment by ebrevdo** [comment] 2016-07-23 03:55
It's not in BasicLSTMCell.  It's in LSTMCell.

**Comment by girving** [comment] 2016-08-08 17:41
Closing since this seems resolved.

**Closed by girving** 2016-08-08 17:41 UTC
Labels: awaiting response

**Comment by stefan-falk** [comment] 2020-07-08 14:48
@ebrevdo It seems that `proj_size` has been removed. 

If I understand this correctly, then we just apply a `Dense` layer to the RNN/LSTM output in order to project the particular output down to a desired dimension.

So doing this (note I am using `tf.compat.v1.nn.rnn_cell.LSTMCell` here):

```python
outputs = layers.RNN(
    tf.compat.v1.nn.rnn_cell.LSTMCell(
        layer_size,
        num_proj=proj_size
    ),
    return_sequences=True
)(inputs)
```

Should be similar to this:

```python
x = layers.RNN(
    layers.LSTMCell(layer_size),
    return_sequences=True
)(inputs)

outputs = layers.Dense(proj_size)(x)
```

Is this correct?

Here's a complete example:

```python
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.python.keras import Model


def get_model(inputs, layer_size, proj_size):

    x = layers.RNN(
        layers.LSTMCell(layer_size),
        return_sequences=True
    )(inputs)

    outputs = layers.Dense(proj_size)(x)

    return Model(
        inputs=[inputs],
        outputs=[outputs],
        name='model'
    )


def get_compat_model(inputs, layer_size, proj_size):

    outputs = layers.RNN(
        tf.compat.v1.nn.rnn_cell.LSTMCell(
            layer_size,
            num_proj=proj_size
        ),
        return_sequences=True
    )(inputs)

    return Model(
        inputs=[inputs],
        outputs=[outputs],
        name='compat_model'
    )


def main():
    layer_size, proj_size = 64, 32
    inputs = layers.Input(shape=(100, 50))

    model = get_model(inputs, layer_size, proj_size)
    compat_model = get_compat_model(inputs, layer_size, proj_size)

    model.summary()
    compat_model.summary()


if __name__ == '__main__':
    main()
```

*Output:*

```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 100, 50)]         0         
_________________________________________________________________
rnn (RNN)                    (None, 100, 64)           29440     
_________________________________________________________________
dense (Dense)                (None, 100, 32)           2080      
=================================================================
Total params: 31,520
Trainable params: 31,520
Non-trainable params: 0
_________________________________________________________________
Model: "compat_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 100, 50)]         0         
_________________________________________________________________
rnn_1 (RNN)                  (None, 100, 32)           23296     
=================================================================
Total params: 23,296
Trainable params: 23,296
Non-trainable params: 0
_________________________________________________________________
```

**Comment by ebrevdo** [comment] 2020-07-08 16:25
There are a couple of reasons why you may be getting different numbers of
parameters.  First of, iirc the projection layer doesn't have a bias term,
so you may need to disable bias in your Dense layer.  Second, there may be
some differences in the LSTM layer.

Another thing to consider is that the layers may have different
initializers; so you may have to add some manual initializer calls to the
keras LSTMCell constructor to ensure consistent initialization.

Finally, looks like *in your case* the set of variables created by the
LSTMCells are different:

Here's how I inspect the variables created by the cells:

```python
z = tf.keras.layers.RNN(tf.keras.layers.LSTMCell(3), return_sequences=True)
v = tf.keras.layers.RNN(tf.compat.v1.nn.rnn_cell.LSTMCell(3))
z.build((3, 4, 5))
v.build((3, 4, 5))

In [18]: [(x.name, x.shape) for x in z.variables]
Out[18]:
[('lstm_cell/kernel:0', TensorShape([5, 12])),
 ('lstm_cell/recurrent_kernel:0', TensorShape([3, 12])),
 ('lstm_cell/bias:0', TensorShape([12]))]

In [22]: [(x.name, x.shape) for x in v.variables]
Out[22]:
[('lstm_cell_1/kernel:0', TensorShape([8, 12])),
 ('lstm_cell_1/bias:0', TensorShape([12]))]
```

In my case, the sizes are the same (just split up into different shapes);
but in your case they may be different - you want to investigate that the
same way.

**Comment by stefan-falk** [comment] 2020-07-09 13:05
@ebrevdo Okay, I see. Thank you for the example.

I can see that running the following gives the same number of trainable parameters:

```python
i = tf.keras.layers.Input(shape=(4, 8))
v2 = tf.keras.layers.RNN(tf.keras.layers.LSTMCell(3), return_sequences=True)(i)
Model(inputs=[i], outputs=[v2], name='v2').summary()

i = tf.keras.layers.Input(shape=(4, 8))
v2 = tf.keras.layers.RNN(tf.compat.v1.nn.rnn_cell.LSTMCell(3), return_sequences=True)(i)
Model(inputs=[i], outputs=[v2], name='compat').summary()
```

Output:

```
Model: "v2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 4, 8)]            0         
_________________________________________________________________
rnn (RNN)                    (None, 4, 3)              144       
=================================================================
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________

Model: "compat"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, 4, 8)]            0         
_________________________________________________________________
rnn_1 (RNN)                  (None, 4, 3)              144       
=================================================================
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________
```

But what I do not understand is the `num_proj` argument in the `compat` cell. How can I reproduce (notice `num_proj`) with `tf.keras.layers.LSTMCell`?:

```python
i = tf.keras.layers.Input(shape=(4, 8))
v2 = tf.keras.layers.RNN(tf.compat.v1.nn.rnn_cell.LSTMCell(3, num_proj=2), return_sequences=True)(i)
Model(inputs=[i], outputs=[v2], name='compat').summary()
```

**Comment by ebrevdo** [comment] 2020-07-09 14:56
Looking carefully at the code, it seems like this functionality is not
supported by the keras LSTMCell.  Projection is applied
<https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/rnn_cell_impl.py#L1061>
to the h (m) state that gets passed to the next frame.  You would need to
create your own wrapper RNNCell that has this behavior, and wrap the keras
LSTMCell in it.

**Comment by stefan-falk** [comment] 2020-07-10 07:44
@ebrevdo Ah, I see. I think now it's clear why the code I posted at first was using `tf.compat.v1.nn.rnn_cell.LSTMCell` instead of the TF 2.0 version of it. Interesting that this parameter has been dropped. 

Thank you for your support 👍
