### ISSUE TITLE
compile error with CUDA8.0

### ISSUE THREAD

**Issue by aicarmark** [tensorflow/tensorflow#19344] opened 2018-05-17 04:57 UTC
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.7
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.13
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:

### Describe the problem
met compile error with:
tensorflow/core/kernels/gather_nd_op_gpu.cu.cc(45): error: calling a __host__ function("__builtin_expect") from a __global__ function("tensorflow::GatherSliceOpKernel< ::std::complex<double> , long long, (int)4> ") is not allowed

tensorflow/core/kernels/gather_nd_op_gpu.cu.cc(45): error: calling a __host__ function("__builtin_expect") from a __global__ function("tensorflow::GatherSliceOpKernel< ::std::complex<double> , long long, (int)5> ") is not allowed

tensorflow/core/kernels/gather_nd_op_gpu.cu.cc(45): error: calling a __host__ function("__builtin_expect") from a __global__ function("tensorflow::GatherSliceOpKernel< ::std::complex<double> , long long, (int)6> ") is not allowed

tensorflow/core/kernels/gather_nd_op_gpu.cu.cc(45): error: calling a __host__ function("__builtin_expect") from a __global__ function("tensorflow::GatherSliceOpKernel< ::std::complex<double> , long long, (int)7> ") is not allowed

80 errors detected in the compilation of "/tmp/tmpxft_0000502d_00000000-7_gather_nd_op_gpu.cu.cpp1.ii".
ERROR: /home/carmark/github/tensorflow/tensorflow/core/kernels/BUILD:690:1: output 'tensorflow/core/kernels/_objs/gather_nd_op_gpu/tensorflow/core/kernels/gather_nd_op_gpu.cu.pic.o' was not created
ERROR: /home/carmark/github/tensorflow/tensorflow/core/kernels/BUILD:690:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1050.472s, Critical Path: 77.58s
INFO: 4023 processes, local.
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment] 2018-05-17 12:45
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
GPU model and memory
Exact command to reproduce

**Comment by jart** [comment] 2018-05-17 17:06
Duplicate of #19203.

**Closed by jart** 2018-05-17 17:06 UTC
Labels: stat:awaiting response
