### ISSUE TITLE
While trying to run 3D Unet of mesh-tensorflow 

### ISSUE THREAD

**Issue by ved27** [tensorflow/tensorflow#41779] opened 2020-07-27 18:09 UTC
**System information**
- OS Platform : ubuntu 18.04 : x86_64 
- TensorFlow version 2.2.0:
- Python version 3.6:
- Installed using  pip:
- CUDA/cuDNN : **10.1.243** / **7.6** :
- GPU model and memory  :  pciBusID: 0000:1c:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.75GiB deviceMemoryBandwidth: 607.97GiB/s

I was trying to run 3D Unet model in the experimental/ of mesh-tensorflow on GPUs.     
 **python model_executor.py --use_tpu=False --write_summary=False --train_file_pattern=media/tfrecords64/train/*.tfrecords  --eval_file_pattern=media/tfrecords64/eval/*.tfrecords   --batch_size_train=2  --ct_resolution=64 --mesh_shape="rows:2, columns:2, cores:2" --checkpoint_dir=checkpoint_dir_8gpu &**   

I removed tensorflow.contrib etc, in the code as contrib does not belong to 2.2.0. I installed tensorflow_probability. I adjusted/removed a part of code that depends on TPU, to run the above. 

However this is in the following in the logs. I can also see that GPU memory is all being used up as shown by nvidia-smi. The training seems to be slow too.

**tensorflow/core/common_runtime/colocation_graph.cc:1017] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
/job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=-1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
AssignVariableOp: CPU XLA_CPU XLA_GPU
RandomUniform: CPU XLA_CPU XLA_GPU
VarIsInitializedOp: GPU CPU XLA_CPU XLA_GPU
Const: GPU CPU XLA_CPU XLA_GPU
Mul: CPU XLA_CPU XLA_GPU
ReadVariableOp: GPU CPU XLA_CPU XLA_GPU
Sub: CPU XLA_CPU XLA_GPU
VarHandleOp: CPU XLA_CPU XLA_GPU
Add: CPU XLA_CPU XLA_GPU**

**Comment by ravikyram** [comment] 2020-07-28 04:19
@ved27 

Request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by ved27** [comment] 2020-07-28 16:19
@ravikyram  please find the updated details Thank you!

**Comment by gowthamkpr** [comment] 2020-07-30 16:22
@ved27 Can you please try running it using a tensorflow-gpu than using mesh-tensorflow and let me know if the problem still persists
/

**Comment by ved27** [comment] 2020-07-30 16:27
Hi ,

I was using tensorflow-gpu 2.2.0 and then mesh tensorflow. Problem exists still

**Comment by gowthamkpr** [comment] 2020-08-04 11:48
@ved27 Please provide the reproducible code for us to reproduce the issue. Thanks!

**Comment by gowthamkpr** [comment] 2020-08-07 19:10
Hi @ved27 This is the duplicate of this [issue](https://github.com/tensorflow/serving/issues/1701) and as you mentioned here that its because of the datatype and as its being resolved, I am closing this issue here

**Closed by gowthamkpr** 2020-08-07 19:10 UTC
Labels: TF 2.2, comp:gpu, stat:awaiting response, type:performance
