### ISSUE TITLE
Problem with Keras sparse input

### ISSUE THREAD

**Issue by ZhangZhiPku** [tensorflow/tensorflow#27690] opened 2019-04-09 16:01 UTC
In keras.backend.GraphExecutionFunction.__call__ function, when this function receives sparse input, it will transform sparse input into coo_matrix, and extract (indices, data, shape) from it. But this function will try to invoke numpy.asarray function on value tuple: (indices, data, shape), and will cause error here.

  def __call__(self, inputs):
    inputs = nest.flatten(inputs)

    session = get_session()
    feed_arrays = []
    array_vals = []
    feed_symbols = []
    symbol_vals = []
    for tensor, value in zip(self.inputs, inputs):
      if value is None:
        continue
      if is_sparse(tensor):
        sparse_coo = value.tocoo()
        indices = np.concatenate((np.expand_dims(sparse_coo.row, 1),
                                  np.expand_dims(sparse_coo.col, 1)), 1)
        value = (indices, sparse_coo.data, sparse_coo.shape)
      if tensor_util.is_tensor(value):
        # Case: feeding symbolic tensor.
        feed_symbols.append(tensor)
        symbol_vals.append(value)
      else:
        # Case: feeding Numpy array.
        feed_arrays.append(tensor)
        # We need to do array conversion and type casting at this level, since
        # `callable_fn` only supports exact matches.
        tensor_type = dtypes_module.as_dtype(tensor.dtype)
        
        # ------------------------------------
        #  SHOULD BE THAT?
        # if is_sparse(tensor):
        #   array_vals.append(value)
        # else:
        # ------------------------------------

        array_vals.append(np.asarray(value,
                                     dtype=tensor_type.as_numpy_dtype))

**Comment by jvishnuvardhan** [comment] 2019-04-11 22:38
@ZhangZhiPku Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-25 16:43
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-25 16:43 UTC
Labels: comp:keras, stat:awaiting tensorflower, type:bug/performance
