### ISSUE TITLE
Dataset iterating different behavior in TF 2.1 and 2.2

### ISSUE THREAD

**Issue by sondracek** [tensorflow/tensorflow#39639] opened 2020-05-18 08:57 UTC
System information
- OS Platform and Distribution: Windows 10 Home
- TensorFlow versions: 
  - 2.1: v2.1.0-rc2-17-ge5bf8de410 2.1.0
  - 2.2: v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6

I was not sure how to report this issue as it might be bug or just expected behavior. There are difference in TF 2.1 and 2.2. This is a code snippet to reproduce my issue:

```python
import math
import numpy as np
import tensorflow as tf

# simple dataset with zeros
batch_size = 32
features = np.zeros((10000, 60, 2))
labels = np.zeros((10000, 1))
train_data = tf.data.Dataset.from_tensor_slices((features, labels)).batch(batch_size)
train_steps = int(math.ceil(features.shape[0] / batch_size))

# simple model with Dense layers
inputs = tf.keras.Input(shape=(features[0].shape[0], features[0].shape[1]))
x = tf.keras.layers.Dense(32, activation="relu")(inputs)
outputs = tf.keras.layers.Dense(1, activation="relu")(x)
model = tf.keras.Model(inputs, outputs, name="example_model")

# model fitting
model.compile(loss="mse", optimizer="adam", metrics=["mse"])
model.fit(train_data, epochs=100, steps_per_epoch=train_steps)
```

When I run this code in TF2.1 it will produce this error: https://pastebin.com/4M43SE44
After the first epoch, there are warnings about end of sequence, that my input ran out of data. And finally, as you can see in the pasted output, it raises `ValueError: Empty training data.`. 
When I change line with dataset creation to
<pre>
train_data = tf.data.Dataset.from_tensor_slices((features, labels)).batch(batch_size).<b>repeat()</b>
</pre>
than everything works as expected.

This is behavior I would expect. (Note `steps_per_epoch` attribute as I wan to control this by myself, of course when I do not use `repeat` and `steps_per_epoch` is set to None, it will work under TF2.1 as it will iterate whole dataset every epoch).

When I run the same code with TF2.2 (no repeat, train_steps are specified) it works without any issue. Is this behavior intentional? Why does it work in TF2.2 and not 2.1? Could anyone elaborate on this issue?

**Comment by Saduf2019** [comment] 2020-05-19 14:10
@sondracek 
I ran the code shared by you, please find the [gist for tf 2.1](https://colab.sandbox.google.com/gist/Saduf2019/91f6910ea8824e1a85bd5d9f13c107e2/untitled188.ipynb) and [tf 2.2](https://colab.sandbox.google.com/gist/Saduf2019/35c683e26a6d1b5347fab54b21a97395/untitled187.ipynb) and let us know if this confirms your issue.
If any data is missing please share all dependencies.

**Comment by sondracek** [comment] 2020-05-19 15:49
The first gist (tf 2.1) is right, it raises ValueError as I would expect.
But the second gist is not right (not sure what is the error about). When I run the same code (from your gist) for tf 2.2, it's running without any issues: [gist for tf 2.2](https://colab.research.google.com/gist/sondracek/fbfc8c39c36e146a959e60d26e328d06/untitled187.ipynb)
Thank you for your help!

**Comment by jsimsa** [comment] 2020-05-21 21:44
@tomerk could you please take a look? this looks to be rooted in Keras and not tf.data.

**Comment by tomerk** [comment] 2020-05-21 23:07
@omalleyt12 is this one of the known regressions that have fixes for 2.3 that didn't quite make it in to 2.2? Or is this something to add to the list?

**Comment by omalleyt12** [comment] 2020-05-22 00:37
@sondracek Thanks for the issue!

Yep this is something we added support for in 2.2

We can sometimes know the exact size of the `Dataset` you pass in. If we can know this size, and you pass the exact size in `steps_per_epoch`, then we will assume that you meant for us to recreate the `Iterator` each epoch.

This seems to me to be the most intuitive behavior, since what we do if you don't pass `steps_per_epoch` is we infer it to be the entire size of the `Dataset`

Closing as intended behavior, but please re-open if you think this behavior is confusing and should be changed, I don't have a strong opinion either way

**Closed by omalleyt12** 2020-05-22 00:37 UTC
Labels: TF 2.1, comp:keras, stat:awaiting tensorflower, type:others

**Comment by sondracek** [comment] 2020-05-25 07:26
Thank you for your response, I didn't find any note on this change so I was just a bit surprised that the behavior is different.

I don't have a strong opinion here as well, but it makes sense. It would be worth writing it to documentation (not sure whether it's mentioned somewhere?), however, thank you for your explanation.
