### ISSUE TITLE
[TF2.0] Histogram summary unexpected keyword 'values' in summary_v2.py

### ISSUE THREAD

**Issue by Uture** [tensorflow/tensorflow#26479] opened 2019-03-08 08:28 UTC
**System information**
- OS Platform and Distribution: Linux 18.04
- TensorFlow version 2.0-alpha
- Python 3.6.8

**Describe the current behavior**

Trying to write any tensor as histogram summary:

> /tmp/cpu-env/lib/python3.6/site-packages/tensorboard/plugins/histogram/summary_v2.py in _buckets(data, bucket_count)
     89   if bucket_count is None:
     90     bucket_count = DEFAULT_BUCKET_COUNT
---> 91   with tf.name_scope('buckets', values=[data, bucket_count]):
     92     tf.debugging.assert_scalar(bucket_count)
     93     tf.debugging.assert_type(bucket_count, tf.int32)
TypeError: __init__() got an unexpected keyword argument 'values'

**Code to reproduce the issue**
`tf.summary.histogram('SampleKernel', tf.random.normal(shape=[3,3,3,32], dtype=tf.float32))`

**Comment by jvishnuvardhan** [comment] 2019-03-12 00:08
@Uture Could you provide a code to reproduce the bug? Thanks!

**Comment by Uture** [comment] 2019-03-12 10:52
> @Uture Could you provide a code to reproduce the bug? Thanks!

It's right there in the last point of the issue. This line suffices for me to get the error (besides tensorflow import).

**Comment by nfelt** [comment] 2019-03-20 22:16
Duplicate of https://github.com/tensorflow/tensorboard/issues/1993

This is fixed in `tb-nightly`, which you can try out via `pip install --upgrade tb-nightly`.

**Closed by nfelt** 2019-03-20 22:16 UTC
Labels: 2.0, comp:tensorboard, stat:awaiting tensorflower, type:bug/performance
