### ISSUE TITLE
why options in session_config like intra_op_parallelism_threads/inter_op_parallelism_threads doesn't work in tensorflow estimator distribution mode？

### ISSUE THREAD

**Issue by guoguo11191** [tensorflow/tensorflow#22306] opened 2018-09-17 05:25 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:just tried to import it.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:CentOS Linux release 7.2
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.7 to 1.10
- **Python version**:2.7
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **CPU model and memory**:Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz,128G
- **Exact command to reproduce**:N/A

### Describe the problem
when i set intra_op_parallelism_threads/inter_op_parallelism_threads for estimator dist mode like this:
`config = tf.ConfigProto()
config.intra_op_parallelism_threads = 4
config.inter_op_parallelism_threads = 4
run_config = tf.estimator.RunConfig().replace(session_config=config)
model = tf.estimator.DNNLinearCombinedClassifier(
            model_dir=model_dir,
            linear_feature_columns=wide_columns,
            dnn_feature_columns=deep_columns,
            dnn_hidden_units=hidden_units,
            config=run_config)`
it doesn't work, i find the options isn't passed to kernals:

tensorflow/python/estimator/training.py
`if config.session_config is None:
  session_config = config_pb2.ConfigProto(log_device_placement=False)
else:
  session_config = config_pb2.ConfigProto(
	  log_device_placement=False,
	  gpu_options=config.session_config.gpu_options)`
only a few options are set, the code above indicate intra_op_parallelism_threads/inter_op_parallelism_threads have no effect，is a bug？why？

**Comment by tensorflowbutler** [comment] 2018-09-17 12:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by byronyi** [comment] 2018-09-19 02:47
@skye I suppose the user needs to switch to GraphRunner in this case?

**Comment by tensorflowbutler** [comment] 2018-10-04 19:07
Nagging Assignee @jart: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-03 12:33
Nagging Assignee @jart: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:49
Nagging Assignee @jart: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:55
Nagging Assignee @jart: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wei-v-wang** [comment] 2018-12-13 19:46
Can you please take a look at this PR and see if it helps? 
https://github.com/tensorflow/models/pull/5046/files#diff-a418c41de193111b623e6c168f552206R51 
The above PR was effective for wide and deep in github.com/tensorflow/models

**Comment by ymodak** [comment] 2019-01-08 23:59
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-01-08 23:59 UTC
