### ISSUE TITLE
Bound method <Conv.call> could not be transformed

### ISSUE THREAD

**Issue by DeveloperRachit** [tensorflow/tensorflow#34551] opened 2019-11-24 04:49 UTC
Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f2557c76048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f2557c76048>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by darsh8200** [comment] 2019-11-24 14:23
Not sure what the bug is exactly. But installing installing gast 0.2.2 version fixed it.

pip install --user gast==0.2.2

**Comment by DeveloperRachit** [comment] 2019-11-24 15:58
Pack node (map_1/while/stack) axis attribute is out of bounds: 0                               2019-11-24 21:22:04.734195: W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node map_1/while/ChangeCoordinateFrame/strided_slice_2. Error: Pack node (map_1/while/stack) axis attribute is out of bounds: 0

**Comment by DeveloperRachit** [comment] 2019-11-24 15:59
now i am getting this above error when i am evaluating this model

**Comment by ravikyram** [comment] 2019-11-25 05:17
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by DeveloperRachit** [comment] 2019-11-25 07:28
actually i am using  centos 3.10.0-693.el7.x86_64  and tensorflow version is 1.13.1 yes,

 okay and i am using CUDA 10.0 and GPU Version is Quadro P4000 with 8GB RAM

**Comment by ravikyram** [comment] 2019-11-25 10:01
Will it be possible to provide minimal standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by DeveloperRachit** [comment] 2019-11-25 10:08
actually i am using ssdssd_mobilenet_v2_oid_v4.config  arch to train model rest of i ma using eval.py to evaluate my model.
that is already available inside train

**Comment by DeveloperRachit** [comment] 2019-11-25 10:10
when evaluating my model it is producing that error?

**Comment by gowthamkpr** [comment] 2019-11-26 23:46
As mentioned in the comment [here](https://github.com/tensorflow/tensorflow/issues/29052#issuecomment-504946289), this should be fixed in Tensorflow 1.14. Can you try using Tensorflow 1.14 and see if the error still persists. Thanks!

**Comment by tensorflowbutler** [comment] 2019-12-11 12:29
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gowthamkpr** [comment] 2019-12-11 22:49
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments and we can open the issue again. Thanks!

**Closed by gowthamkpr** 2019-12-11 22:49 UTC
Labels: TF 1.13, comp:grappler, comp:model, stat:awaiting response, type:support

**Comment by Vallum** [comment] 2020-05-27 16:07
I guess that the reason of this problem is gast==0.3.3 and its mismatch with  tf 1.13 and 1.14.
```
$pip install tensorflow-gpu==1.14
...
Collecting gast>=0.2.0
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
```
This should be gast-0.2.2 for tf 1.13 and tf 1.14
gast-0.3.3 >= 0.2.0
But gast-0.3.3 is obvioursly incompatible with tf1.13 and tf1.14
* Test environment
CentOS Linux release 7.5.1804 (Core)
tensorflow_gpu-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl
tensorflow_gpu-1.14.0-cp36-cp36mu-manylinux1_x86_64.whl
virtualenv with pip
