### ISSUE TITLE
Custom op kernels compiled with C++17 are binary incompatible with tensorflow

### ISSUE THREAD

**Issue by liamuk** [tensorflow/tensorflow#23561] opened 2018-11-06 17:36 UTC
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.5 (in docker)
- TensorFlow installed from (source or binary): pip binary
- TensorFlow version (use command below): 1.11
- Python version: 3.6.4
- GCC/Compiler version (if compiling from source): 7.3.1

**current behavior**
When compiling a custom op kernel with c++17 features, compilation succeeds, but loading the generated library fails at runtime with the following error:
```
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib64/python3.6/site-packages/package-0.0.1-py3.6-linux-x86_64.egg/_package_ops.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceESt17basic_string_viewIcSt11char_traitsIcEEPSs
```
**expected behavior**
Loading the library should succeed

**Code to reproduce the issue**
Any custom op using `GetAttr` should reproduce this, e.g. the custom op in the custom op tutorial

**Other info / logs**
This symbol that is undefined is `tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*)`

the symbol that it should have linked against (which exists in libtensorflow_framework.so) is `tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, absl::string_view, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*)`

the difference is `std::basic_string<char, std::char_traits<char>` vs. `absl::string_view` for the second argument.

It appears to be this way because https://github.com/abseil/abseil-cpp/blob/master/absl/strings/string_view.h uses `std::string_view` to provide `absl::string_view` when `std::string_view` is available (i.e. when compiling using c++17 standard)

The tensorflow binary is compiled with c++11, so it has absl::string_view provided by the custom absl implementation, whereas my custom op, compiled with c++17 gets the standard library implementation, so they are binary incompatible.

**Comment by liamuk** [comment] 2018-11-06 18:21
a workaround is to do
```
#include "absl/base/config.h"
#undef ABSL_HAVE_STD_STRING_VIEW
```
before
```
#include "tensorflow/core/framework/op_kernel.h"
```

**Comment by liamuk** [comment] 2018-11-06 21:17
upstream: https://github.com/abseil/abseil-cpp/issues/211

**Comment by tensorflowbutler** [comment] 2018-12-04 18:57
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-12-04 19:12
Not just abseil, none of c++ standard promises any ABI compatibility when compilers or compiler versions are different.
For this, we have a longer term goal of providing a C API for writing kernels, and that will be the solution to this problem. Until then, unfortunately c++17 features will almost always guarantee binary incompatibility, because you will have to use a different compiler.

One solution you can use is rebuild core TF package and custom ops on the same machine with the same compiler.

**Comment by girving** [comment] 2018-12-18 17:55
@gunan Building TF and custom ops on the same machine doesn't fix the problem: I still get these errors.

**Comment by gunan** [comment] 2018-12-18 18:47
That is quite puzzling to me.
I may need to look into it. Do you have detailed reproduction instructions?

**Comment by girving** [comment] 2018-12-18 21:17
@gunan Here's a minimized test case: https://github.com/girving/custom-op-bug

**Comment by gunan** [comment] 2018-12-26 21:21
Thank you very much for sharing this!
I have not been able to look at this yet, but this is a priority for me.
Also cc @yifeif

**Comment by girving** [comment] 2019-01-11 18:38
@gunan @yifeif Let me if that test case isn't reproducible, or if more information would help for some other reason.

**Comment by gunan** [comment] 2019-01-16 07:09
I had some spare time to try out, but I ran into build issues when trying to rebuild tf with gcc 7.
So had to start going down the rabbit hole and got distracted.
I will retry on a macos.

**Comment by girving** [comment] 2019-01-17 03:05
There's a good chance this is Mac specific, since the linker is quite different on Mac vs. Linux.

**Comment by girving** [comment] 2019-01-31 20:44
@gunan Any activity on this?  It's been blocking me from running some of my unit tests for over a month.

**Comment by gunan** [comment] 2019-02-01 01:19
I just reproduced the problem, after shaving a few yaks and fixing a few more issues on macos.

Now I will try to see what happens if I build TF "--copt=-std=c++1z"

**Comment by gunan** [comment] 2019-02-01 01:58
I see that the build fails with this when I set `--cxxopt=-std=c++1z`
```
tensorflow/core/kernels/sdca_internal.cc:313:8: error: no member named 'random_shuffle' in namespace 'std'
  std::random_shuffle(sampled_index_.begin(), sampled_index_.end());
```

I think the ABI incompatibility is due to the difference in build flags. I think the workaround, until we have a C API is, we need to make TF build with `--cxxopt=-std=c++1z`

**Comment by girving** [comment] 2019-02-01 17:19
Thank you @gunan!  I'm happy to use that flag workaround for now.  Will wait until those fixes are merged and then try it out.

**Comment by gunan** [comment] 2019-02-01 17:50
Ok, both changes are merged, so you should be able to build with `--cxxopt=-std=c++1z` flag now.

Maybe we should also create a `--config=c++1z` or `--config=c++17`?

**Comment by girving** [comment] 2019-02-01 21:55
I tried it out.  It seems to fix my `custom-op-bug` repo but doesn't fix the unminimized case that I care about.  Will need to investigate more to figure out why.

**Comment by girving** [comment] 2019-02-02 17:05
Actually I'd failed to test it correctly.  It works!  Thank you @gunan!

**Closed** 2019-05-10 23:56 UTC
Labels: comp:runtime

**Comment by golden0080** [comment] 2019-08-13 04:06
I have similar issue when compiling my custom op with C++17. I did try to compile TF 1.14 with the mentioned flags: `--config=c++1z`, but got hit by compilation errors. Any ideas?

**Comment by golden0080** [comment] 2019-08-15 20:17
I think the `-config=c++1z/17` will add `-stdlib=libc++` to the params, which is only recognized by `Clang`, is there some solution to `custom_op` issue when building with GCC 7 and C++17?

**Comment by Weili17** [comment] 2023-03-03 11:07
> I think the `-config=c++1z/17` will add `-stdlib=libc++` to the params, which is only recognized by `Clang`, is there some solution to `custom_op` issue when building with GCC 7 and C++17 in Ubuntu 16.04?



> I have similar issue when compiling my custom op with C++17. I did try to compile TF 1.14 with the mentioned flags: `--config=c++1z`, but got hit by compilation errors. Any ideas?

I met the same problem, did you solve it?

**Comment by mihaimaruseac** [comment] 2023-03-03 17:29
TF should now compiler with C++17 everywhere

**Comment by Weili17** [comment] 2023-03-06 05:20
> 

could you please look at this issue，it seems somewhere is not compiled with c++17? https://github.com/tensorflow/tensorflow/issues/59887
