### ISSUE TITLE
tf.python.keras.utils.Sequence hangs fit_generator

### ISSUE THREAD

**Issue by optiluca** [tensorflow/tensorflow#25947] opened 2019-02-20 18:39 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  v1.12.0-8400-g7f0bf2ef4f 1.13.0-dev20190220
- Python version: 3.6
- CUDA/cuDNN version: 10/ 7.4.2
- GPU model and memory: 2x 980Ti

**Describe the current behavior**
- I've made a data generator that inherits from Sequence
-  calling fit_generator on it hangs if and only if use_multiprocessing=True.  It hangs in training_generator.py in`_get_next_batch `on the line `generator_output = next(generator)`
**Describe the expected behavior**
- Doesn't hang when using use_multiprocessing=True.

I haven't narrowed it down to the bare minimum code required to reproduce - if this issue isn't explainable with the information above I'll try to cut down the code to the minimum that reproduces so that I can submit it here.

**Comment by ymodak** [comment] 2019-02-26 02:11
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-03-04 23:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-04 23:23 UTC
Labels: comp:keras, stat:awaiting response
