### ISSUE TITLE
TFTRT: CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#32573] opened 2019-09-17 07:08 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:RTX2080

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Seeing the following error:
```
2019-09-16 23:41:12.835022: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:749] failed to record completion event; therefore, failed to create inter-stream dependency
2019-09-16 23:41:12.835047: I tensorflow/stream_executor/stream.cc:4813] [stream=0x5591077fbc60,impl=0x5590ffc9bd90] did not memcpy host-to-device; source: 0x7f7e8425bc80
2019-09-16 23:41:12.835058: E tensorflow/stream_executor/stream.cc:331] Error recording event in stream: error recording CUDA event on stream 0x5590ffc9b740: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2019-09-16 23:41:12.835076: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1ailed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-09-17 21:02
Since TF 1.14 prebuilt binaries support cuda 10.0, can you try by switching to cuda 10.0  instead. Thanks!

**Comment by sgambient** [comment] 2019-09-18 00:12
I see.  Using the nvcr container with TF 1.14 .  Which has Cuda 10.1.

**Comment by gadagashwini** [comment] 2019-09-18 06:28
@sgambient, Please provide the minimal standalone code to reproduce the reported issue. Thanks!

**Comment by sgambient** [comment] 2019-09-18 18:39
That is an easy ask, but very hard to do. I do not think that is the right way to handle large software.  My recommendation is to build in more detailed logs and metrics so as not to have to rely on largess of random developers.

**Comment by ymodak** [comment] 2019-10-03 17:53
Is this still an issue after switching to cuda 10.0?

**Comment by ymodak** [comment] 2019-10-21 04:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-10-21 04:22 UTC
Labels: TF 1.14, comp:gpu, stat:awaiting response, type:bug
