### ISSUE TITLE
XLA missing [ op: Unique ] for most optimizers

### ISSUE THREAD

**Issue by jannickj** [tensorflow/tensorflow#28317] opened 2019-05-01 19:19 UTC
Unable to train with anything but sgd using xla, due to a missing operation.

line 76 in https://github.com/tensorflow/tensorflow/blob/677a14872f028e9be51bd469ec2d5cc43ea9155e/tensorflow/python/training/optimizer.py
```
def _deduplicate_indexed_slices(values, indices):
  """Sums `values` associated with any non-unique `indices`.
  Args:
    values: A `Tensor` with rank >= 1.
    indices: A one-dimensional integer `Tensor`, indexing into the first
      dimension of `values` (as in an IndexedSlices object).
  Returns:
    A tuple of (`summed_values`, `unique_indices`) where `unique_indices` is a
    de-duplicated version of `indices` and `summed_values` contains the sum of
    `values` slices associated with each unique index.
  """
  unique_indices, new_index_positions = array_ops.unique(indices) <------- MISSING
  summed_values = math_ops.unsorted_segment_sum(
      values, new_index_positions,
      array_ops.shape(unique_indices)[0])
  return (summed_values, unique_indices)
```

**Comment by achandraa** [comment] 2019-05-03 12:18
Can you please help us in reproducing the issue with a minimal code. Also let us know information such as TensorFlow version, platform etc. You can refer this [link](https://github.com/tensorflow/tensorflow/issues/new/choose) to help us. Thanks!

**Comment by achandraa** [comment] 2019-05-08 06:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-08 06:44 UTC
Labels: comp:ops, stat:awaiting response
