### ISSUE TITLE
"ValueError: None values not supported."  when using bidirectional_dynamic_rnn

### ISSUE THREAD

**Issue by joostbr** [tensorflow/tensorflow#8247] opened 2017-03-09 18:25 UTC
Using bidirectional_dynamic_rnn throws the "ValueError: None values not supported" when you are not specifying the sequence lengths. The error comes from the reverse step, the operator used to reverse the input sequences requires the sequence lengths to be specified. Maybe this should be a required parameter or alternatively generate the lengths array when the default 'None' is used.

(tensorflow 1.0.0)

**Comment by prb12** [comment] 2017-03-09 19:47
@ebrevdo Can you comment on this pls?

**Comment by ebrevdo** [comment] 2017-03-09 23:43
This is a duplicate of #5588 and was fixed in
16a4bc203b90f0eff07df369d9d8fe6260c99aef.

**Comment by prb12** [comment] 2017-03-10 02:05
@ebrevdo Thanks!  (sorry I didn't spot the duplicate).
Closing.

**Closed by prb12** 2017-03-10 02:05 UTC
Labels: stat:awaiting tensorflower
