### ISSUE TITLE
The experimental lcm function gives wrong result

### ISSUE THREAD

**Issue by Ishticode** [tensorflow/tensorflow#58619] opened 2022-11-19 16:34 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Linux (Google Colab)

### Python version

3.7.15

### Current Behaviour?

```shell
Hi. The code below shows the lcm for 21 and 7 is output as 15 for TensorFlow while it should clearly be 21. NumPy and JAX give the correct result of 21. This is the case for int8 although the output value is certainly not high enough to be causing any overflows etc. The result in case of int16 or higher is accurate (21). However, if the values were 2100 and 70 the result would be inaccurate for int16 in tensorflow again as opposed to np and jax.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

at = tf.constant([21], dtype=tf.int8)
bt = tf.constant([7], dtype=tf.int8)

an = np.array([21], dtype=np.int8)
bn = np.array([7], dtype=jnp.int8)

print("tensorflow: ", tf.experimental.numpy.lcm(at, bt))
print("numpy: ", np.lcm(an,bn))
```

### Relevant log output

```shell
tensorflow:  tf.Tensor([15], shape=(1,), dtype=int8)
numpy:  [21]
```
</details>

**Comment by tiruk007** [comment] 2022-11-21 17:17
@sushreebarsa 
I was able to  reproduce the issue on Colab by using TF-nightly, TF v2.9.2 and TF v2.10.1. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/f23b2dbd292720925b0d70dc3e72c718/58619.ipynb) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment] 2022-12-16 07:24
Hi @Ishticode ,

Thanks for pointing the issue. 

At present as per documentation this [API](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/lcm) won't support dtype as argument. 

> Unsupported arguments: out, where, casting, order, dtype, subok, signature, extobj.

If you remove the dtype argument and can try with any other numbers also,you can get the same result for TF as well as Numpy.
Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/15e1b704c19605c98b4e6f3c4d095d81/58619-nightly.ipynb) here.Though in nightly mentioning correct dtype suitable for input data works fine which is also replicated in attached gist.Since this is experimental Feature we can expect consistent behaviour once its released as stable.Till then we need to follow the documentation and as per documentation it is working inline.

Please refer and confirm whether your query answered?

Thanks!

**Comment by Ishticode** [comment] 2022-12-16 12:10
Hi @SuryanarayanaY. Thank you for the reply.
I don't think this adresses the issue accurately. In the code I provided above, there is no dtype argument for `lcm` API anyways. Its the input arrays that have their dtype specified. 

As for the provided gist, the first tensor has been modified to have `int16` while my code specifies `int8`. This change is not a fix but rather a diversion from the actual issue. 

Please correct me if am missing something here or kindly take a more serious and thorough look at this. Thank you.

**Comment by SuryanarayanaY** [comment] 2022-12-16 15:17
@Ishticode ,

The API `tf.experimental.numpy.lcm` has only two arguments that are X1 & X2 which is not supporting argument  `dtype`,because TF converts them into suitable dtypes based on inputs.Providing explicit dtype not being supported currently. Hence if you won't mention any `dtype` at all it works fine.I did some exercise here and found that without explicit dtype the results are inline with numpy.Request you also do some exercise and confirm the same.

Otherway is mentioning suitable dtype same as numpy.But please note that it is my assumption that it should work with same `dtype` as numpy argument. Here i found that with `int8`  as `dtype` the results are not same for TF and Numpy which needs to be checked. But for other `dtype` like `int32` the results are same.

Please refer the attached revised [gist](https://colab.research.google.com/gist/SuryanarayanaY/1a5b184572d894c7786e3a6a7a68852e/58619-r2.ipynb).

We will definitely bring the issue to notice of Development team and also requests them to clarify about what exactly the unsupported arguments meant in this API doc.

Until then we shall assume that the `dtype` argument not supported as mentioned in Documentation and also as it is giving inconsistent results.

Thankyou!

**Comment by Ishticode** [comment] 2022-12-16 16:07
Hi @SuryanarayanaY 
lcm does not have dtype argument. That's been clear from the start and is not the point of discussion here.

Could I maybe get a look from @hawkinsp or any other senior memeber so this can be resolved comprehensively.

The result for `int32` dtypes are not same sometimes either. Check this:
Copy and run this example.
```python
import tensorflow as tf
import numpy as np
print(tf.__version__)

at = tf.constant([700000],tf.int32)
bt = tf.constant([21000000],tf.int32)

an = np.array([700000], dtype=np.int32)
bn = np.array([21000000], dtype=np.int32)

print("tensorflow: ", tf.experimental.numpy.lcm(at, bt))
print("numpy: ", np.lcm(an,bn))
```
You will see that it produces incosistent results (numpy being correct and tensorflow incorrect) as such
```
2.9.2
tensorflow:  tf.Tensor([2390], shape=(1,), dtype=int32)
numpy:  [21000000]
```

I was able to break it for int64 too. It happens for all int types where the corresponding numpy call gives correct result and tensorflow miscalculates.

**Comment by SuryanarayanaY** [comment] 2022-12-19 13:18
Hi @Ishticode ,

Yes I cross checked and agree to you.Even without dtype argument also the results are inconsistent and wrong as per [gist](https://colab.research.google.com/gist/SuryanarayanaY/e6448decb8dfdeb5b0d6196d43a843db/58619-2-12.ipynb) attached.Thanks for bring this to us.Sure the issue will be escalated to developer team.

**Comment by SuryanarayanaY** [comment] 2023-02-15 06:47
Hi @Ishticode ,

The issue is fixed now in tf-nightly. I have tested the code that failed earlier and found its working fine now with tf-nightly and please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/af548530eead31e26f891dcbebc8360f/58619_resolved.ipynb).

Could you please check and confirm whether issue resolved and can be closed? Thanks!

**Closed** 2023-03-01 08:07 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.10
