### ISSUE TITLE
Evaluating the value of a tensor from inside the model_function of a custom `tf.TPUEstimator`

### ISSUE THREAD

**Issue by vishagan1** [tensorflow/tensorflow#29036] opened 2019-05-26 03:54 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I am implementing an NLP model based on BERT, using `tf.TPUEstimator()`. I want to implement layer-wise training, where I need to select only one layer of the model to train for each epoch. In order to do this I wanted to change my model_fn and get the value of current_epoch. 

I know how to compute the value of current_epoch as a tensor using `tf.train.get_or_create_global_step()` inside the `model_fn` BUT, I need to evaluate the value of this tensor to select which layer to train and implement  return the correct `train_op` to the `tf.estimator` (**train_op pertaining to a single layer chosen accrding to the value of the current_epoch**).

I am unable to evaluate this tensor (current_epoch / global_step) from inside the model_fn. I tried the following but the training hangs at the step `my_sess.run(my_global_step.initializer`

```
global_step = tf.train.get_or_create_global_step()
graph = tf.get_default_graph()
my_sess = tf.Session(graph=graph)
current_epoch = (global_step * full_bs) // train_size

my_sess.run(my_global_step.initializer)
current_epoch = sess.run(current_epoch)

# My program hangs at the initialising step: my_sess.run(my_global_step.initializer)
```
Q) Is there currently any way to evaluate a tensor inside the `tf.estimator`
Q)Is there any way to evaluate a tensor using the tf.Estimators default session? How do I get the default session/ Graph?
Q)**Most importantly what is wrong in my code and why does the training hang when using tpu's and TPUEstimator**?

**Comment by muddham** [comment] 2019-05-27 11:26
@vishagan1 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by vishagan1** [comment] 2019-05-28 14:17
@muddham Thanks for the response. Please find below a code snippet, which creates the optimizer with different rate depending on the current_epoch and selecting a layer. Finally it returns the train_op that updates the weights.
```
def create_optimizer(loss,
                     init_lr_bert,
                     init_lr_custom,
                     num_train_steps,
                     num_warmup_steps,
                     use_tpu,
                     # fixme added new params below
                     is_layer_wise,
                     epoch_per_layer,
                     full_bs,
                     train_size,
                     steps_per_epoch,
                     steps_per_layer
                     ):

  """Creates an optimizer training op."""
  global_step = tf.train.get_or_create_global_step()

    current_epoch = (global_step * full_bs) // train_size
    eff_epoch = current_epoch // epoch_per_layer
    
  if is_layer_wise: 
     global_step = tf.train.get_or_create_global_step()
     graph = tf.get_default_graph()
     my_sess = tf.Session(graph=graph)
     current_epoch = (global_step * full_bs) // train_size
     my_sess.run(my_global_step.initializer)
     current_epoch = sess.run(current_epoch)
     
      if current_epoch == 0:
          # train just the custom layer
          lr_custom = _learning_rate_decay_and_warmup(init_lr_custom, global_step, num_train_steps,
                                                      num_warmup_steps)
          _train_op_custom = _create_train_op("[^bert]", lr_custom, loss, global_step, use_tpu=use_tpu,
                                              weight_decay_rate=0.01,
                                              beta_1=0.9,
                                              beta_2=0.999,
                                              epsilon=1e-6,
                                              exclude_from_weight_decay=["LayerNorm", "layer_norm", "bias"]
                                              )
          tf.logging.info('*******Training Custom Layer')
          train_ops.append(_train_op_custom)
      else:
          layer_to_train = 12-current_epoch
          regex_match = 'bert/encoder/' + "layer_{}".format(layer_to_train) + "/"
          tf.logging.info('*******Training: {}'.format(regex_match))
          print('*******Training: {}'.format(regex_match))
          decay = 2.6 ** (11 - layer_to_train)
          decayed_lr = init_lr_bert/decay
          tf.logging.info("Attaching learning rate of, {} to {}".format(decayed_lr, regex_match))
          lr_ = _learning_rate_decay_and_warmup(decayed_lr, global_step, num_train_steps,
                                                                              num_warmup_steps)
          _train_op = _create_train_op(regex_match, lr_, loss, global_step, use_tpu=use_tpu,
                                       weight_decay_rate=0.01,
                                       beta_1=0.9,
                                       beta_2=0.999,
                                       epsilon=1e-6,
                                       exclude_from_weight_decay=["LayerNorm", "layer_norm", "bias"]
                                       )
          train_ops.append(_train_op)
          
    new_global_step = global_step + 1
    train_op = tf.group(*train_ops, [global_step.assign(new_global_step)])
    return train_op
```

**Comment by muddham** [comment] 2019-05-31 13:04
@vishagan1 I ran the code provided in TF 1.13 TPU , its not showing any output.

**Comment by gadagashwini** [comment] 2019-06-06 11:55
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-06 11:55 UTC
Labels: TF 1.13, comp:ops, comp:tpus, stat:awaiting response
