### ISSUE TITLE
Dataset Iterator is not an iterator when using fit_generator

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#30915] opened 2019-07-22 05:28 UTC
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_generator.py#L363

below is ok.
```
    if isinstance(generator, (iterator_ops.IteratorV2, iterator_ops.Iterator)):
363        generator_output = generator.get_next()
364     else:
365        generator_output = next(generator)
```

**Comment by ymodak** [comment] 2019-07-31 19:30
Please provide following information whichever is applicable in your case.
It will help us to get some context. Thanks!
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-08-08 22:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-08-08 22:07 UTC
Labels: comp:keras, stat:awaiting response, type:bug
