### ISSUE TITLE
Error when load model with layer tensorflow.keras.layers.experimental.preprocessing.Normalization()

### ISSUE THREAD

**Issue by manuel-masiello** [tensorflow/tensorflow#46427] opened 2021-01-14 11:51 UTC
Hello,
I have an issue with tensorflow.keras.layers.experimental.preprocessing.Normalization(). 
I can't load my model when I use it. 

**System information**
- Have I custom un example script provided TensorFlow code
- Linux Ubuntu 20.04
- TensorFlow installed from binary

```
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Jan 14 12:47:29 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  On   | 00000000:08:00.0  On |                  N/A |
|  0%   49C    P8    12W / 120W |    535MiB /  5941MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1217      G   /usr/lib/xorg/Xorg                346MiB |
|    0   N/A  N/A      1943      G   /usr/bin/kwin_x11                  57MiB |
|    0   N/A  N/A      1956      G   /usr/bin/plasmashell               72MiB |
|    0   N/A  N/A      2367      G   ...gAAAAAAAAA --shared-files       10MiB |
|    0   N/A  N/A      3078      G   ...AAAAAAAA== --shared-files       41MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0.221
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-11.0/doc/man/man7/libcudart.7
/usr/local/cuda-11.0/doc/man/man7/libcudart.so.7

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.4.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/user/works/test-libs/venv/lib/python3.8/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 8, 5, 'final', 0)

== bazel version  ===============================================
```

**Describe the current behavior**
I can't load my model when I use it. 

**Describe the expected behavior**
I would like to be able to read a model with this layer. I know it's an experimental layer but it should work.  If you have no idea how to solve it, can you advise me of an alternative?

Thank you :-)

**Standalone code to reproduce the issue**
```python
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing


data = [{"a": 20.0, "b": 5.0, "c": 0.2972786923202068}, {"a": 20.0, "b": 10.0, "c": 0.10673704592967688}]
train_dataset = pd.DataFrame.from_dict(data)

train_features = train_dataset.copy()
train_labels = train_features.pop('c')

normalizer = preprocessing.Normalization()
normalizer.adapt(np.array(train_features))

dnn_model = keras.Sequential([
    normalizer,
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(1)
])

dnn_model.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))
dnn_model.save('file.h5')


# ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
new_model = tf.keras.models.load_model('file.h5')
```

**logs**
```
2021-01-14 12:27:41.950145: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-14 12:27:42.758932: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-14 12:27:42.759555: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-01-14 12:27:42.796836: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.797239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.8GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 268.26GiB/s
2021-01-14 12:27:42.797264: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-14 12:27:42.798974: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-14 12:27:42.799021: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-14 12:27:42.799743: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-01-14 12:27:42.799901: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-01-14 12:27:42.801635: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-01-14 12:27:42.802036: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-01-14 12:27:42.802131: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-14 12:27:42.802239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.802663: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.802998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-01-14 12:27:42.803643: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-14 12:27:42.803719: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.804062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.8GHz coreCount: 24 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 268.26GiB/s
2021-01-14 12:27:42.804079: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-14 12:27:42.804092: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-14 12:27:42.804101: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-01-14 12:27:42.804110: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-01-14 12:27:42.804119: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-01-14 12:27:42.804128: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-01-14 12:27:42.804136: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-01-14 12:27:42.804145: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-14 12:27:42.804191: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.804558: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:42.804884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-01-14 12:27:42.804907: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-01-14 12:27:43.183218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-14 12:27:43.183266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-01-14 12:27:43.183273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-01-14 12:27:43.183488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:43.183873: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:43.184214: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-14 12:27:43.184529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4868 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:08:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2873, in zeros
    shape = constant_op._tensor_shape_tensor_conversion_function(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 355, in _tensor_shape_tensor_conversion_function
    raise ValueError(
ValueError: Cannot convert a partially known TensorShape to a Tensor: (None,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "save.py", line 30, in <module>
    new_model = tf.keras.models.load_model('file.h5')
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 183, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 64, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 494, in from_config
    model.add(layer)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 223, in add
    output_tensor = layer(self.outputs[0])
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/preprocessing/normalization.py", line 174, in build
    self.mean = self._add_state_variable(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_preprocessing_layer.py", line 110, in _add_state_variable
    weight = self.add_weight(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 623, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 805, in _add_variable_with_custom_getter
    new_variable = getter(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 130, in make_variable
    return tf_variables.VariableV1(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 206, in _variable_v1_call
    return previous_getter(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py", line 2604, in default_variable_creator
    return resource_variable_ops.ResourceVariable(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1574, in __init__
    self._init_from_args(
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1712, in _init_from_args
    initial_value = initial_value()
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py", line 114, in __call__
    return array_ops.zeros(shape, dtype)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2877, in zeros
    shape = ops.convert_to_tensor(shape, dtype=dtypes.int32)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/user/works/test-libs/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

```

**Comment by ravikyram** [comment] 2021-01-15 16:02
I have tried in colab with TF-GPU version 2.4, nightly version(`2.5.0-dev20210114`) and I am not seeing any issue.Colab uses cuda 10.1.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f63d9dea8f90ba37ba2ea9f594e79cd5/untitled0.ipynb).Thanks!
`

**Comment by manuel-masiello** [comment] 2021-01-17 17:01
Hello,
Thank you for your reply.
Did you run the last line of the program? In your dashboard I do not see
this line ...
The problem is in the leader function.




Le ven. 15 janv. 2021 à 17:03, ravikyram <notifications@github.com> a
écrit :

**Comment by manuel-masiello** [comment] 2021-01-17 17:18
I just added it to your [colab](https://colab.research.google.com/gist/ravikyram/f63d9dea8f90ba37ba2ea9f594e79cd5/untitled0.ipynb) and the problem is the same as on my computer.

'''
new_model = tf.keras.models.load_model('file.h5')
'''

**Comment by ravikyram** [comment] 2021-01-18 05:01
I have tried in colab with TF nightly version and was able to reproduce the issue .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/37a8c56e964e09ddb33e36e74ff1ae74/untitled623.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment] 2021-01-20 00:58
@manuel-masiello Looks like there is an issue when saving in `h5` format. However, there was no issue when `tf` format is used for saving the model. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d574813ec3faf5530e6ffa2159be3858/untitled623.ipynb). Thanks!

```
#dnn_model.save('file.h5')
dnn_model.save('file',save_format='tf')

new_model = tf.keras.models.load_model('file')
```

**Comment by manuel-masiello** [comment] 2021-01-20 09:38
Hello. Thanks for finding me an alternative.  :-)
I will modify my code. 

FYI, I just tested with Json serialization and the error also exists. Please found the [gist here](https://colab.research.google.com/drive/1KXpiuHnnfOspsftzBjt5HJvD7a4_XLG8?usp=sharing).


```python
json_config = dnn_model.to_json()
new_model = keras.models.model_from_json(json_config)
```

Is there a parameter equivalent to save format = 'tf' for json?

Best regards,
Manuel

**Comment by jvishnuvardhan** [comment] 2021-02-26 03:00
@manuel-masiello There is no equivalent to `save format` = 'tf'. `save_format` has two options only ('tf' or 'h5'). Thanks!

**Comment by jvishnuvardhan** [comment] 2021-02-26 03:19
@manuel-masiello I think the issue with 'h5' is due to its limitation. There are some limitations on what can be saved as part of `h5` format. Please check this [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#keras_h5_format) to know more about it.

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-02-26 03:19 UTC
Labels: TF 2.4, comp:keras, stat:awaiting tensorflower, type:bug
