### ISSUE TITLE
Golang API to serialize data into tf.Example protos(tfrecords)

### ISSUE THREAD

**Issue by wenruij** [tensorflow/tensorflow#16347] opened 2018-01-24 02:53 UTC
The Golang api [WriteContentsTo](https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go#Tensor.WriteContentsTo) can be used to writes the serialized contents of a tensor to io.Writer, where the tensor is built from golang scalars, slices, and arrays. 

Yet there's not a Golang API to serialize data into tf.Example protos(tfrecords).

For example, when i want serialize a libsvm into tf.Example protos, i can do this by:
```
def libsvm2tfrecords(data_source, target_dir, delimiter='\t'):
    """
    a single file should not contain lines more than 1000,000, or we should use libsvm2proto_par
    :param data_source: libsvm file path
    :param target_dir: dir to storage the serialize proto file
    :param delimiter: delimiter for csv reader
    :return:
    """
    if not os.path.isfile(data_source):
        raise ValueError('data file passed do not exist or not a file')

    file_name = os.path.join(target_dir, os.path.splitext(
        os.path.basename(data_source))[0] + '.tfrecords')
    writer = tf.python_io.TFRecordWriter(file_name)
    start = datetime.now()
    line_c = 0
    with open(data_source, 'rb') as rf:
        f_reader = csv.reader(rf, delimiter=delimiter, quotechar='|')
        for row in f_reader:
            line_c += 1
            feature = dict()
            indexes = []
            values = []
            feature.update({'label': _float_feature([float(row[0])])})
            for e in row[1:]:
                index, value = e.split(':')
                indexes.append(int(index))
                values.append(float(value))
                feature.update({'index': _int64_feature(indexes)})
                feature.update({'value': _float_feature(values)})

            example = tf.train.Example(features=tf.train.Features(feature=feature))
            writer.write(example.SerializeToString())

        writer.close()
        end = datetime.now()

        print("- consumed time: %ds for %s" % ((end-start).seconds, data_source))
```
BUT Golang api does not seem to be able to achieve this.

**Comment by tensorflowbutler** [comment] 2018-01-24 19:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment] 2018-01-25 06:51
Closing this as a duplicate of a [StackOverflow query](https://stackoverflow.com/questions/48393098/how-to-convert-data-to-a-serialized-tf-exampletensorflow-tfrecords-using-golan) and #16282 

Please let me know if I'm mistaken.

**Closed by asimshankar** 2018-01-25 06:51 UTC
Labels: stat:awaiting response
