### ISSUE TITLE
Multiplication of two-dimensional and three-dimensional tensors

### ISSUE THREAD

**Issue by goljx** [tensorflow/tensorflow#28424] opened 2019-05-06 01:22 UTC
There is a two dimensional tensor a[m,n], and a three dimensional tensor b[k,n,h]. What API should I use to multiply two dimensional tensors by three dimensional tensors to get a three dimensional tensor c[k,m,h] ?
Actually I can got it by:

import tensorflow as tf
import tensorly as tl
x=tf.constant([[[1,2],[3,7],[8,9]],
[[4,5],[6,10],[11,12]]],tf.float32)
a=tf.constant([[-0.70711,0.57735],
[0.0000,0.57735],
[0.70711,0.57735]])
reshape_A = tf.reshape(x, [2,6])

re = tf.reshape( tf.matmul(a, reshape_A), [3, 3, 2])

with tf.Session() as sess:
print(sess.run(re))
re=re.eval()

But is there an easier way?

**Comment by muddham** [comment] 2019-05-07 09:06
@goljx This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-05-08 06:42
@goljx Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-08 06:42 UTC
Labels: comp:ops, stat:awaiting response, type:support
