### ISSUE TITLE
can't install tensorflow-gpu==2.0.0b1 in Google Colaboratory

### ISSUE THREAD

**Issue by abpalaciot** [tensorflow/tensorflow#37993] opened 2020-03-28 03:13 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Google Colaboratory

**Describe the problem**

ImportError                               Traceback (most recent call last)
<ipython-input-2-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/__init__.py in <module>()
     31 from tensorflow.python.keras.saving.save import load_model
     32 from tensorflow.python.keras.saving.save import save_model
---> 33 from tensorflow.python.keras.saving.saved_model import export_saved_model
     34 from tensorflow.python.keras.saving.saved_model import load_from_saved_model
     35 from tensorflow.python.keras.saving.saving_utils import trace_model_call

ImportError: cannot import name 'export_saved_model'

**Provide the exact sequence of commands / steps that you executed before running into the problem**

!pip install tensorflow-gpu==2.0.0-beta1

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

tensorflow==2.0.0b1 does work. I've also tried to uninstall any other version of tensorflow, but it doesn't solve the problem

**Comment by Rubix982** [comment] 2020-03-28 17:12
Hi @abpalaciot !

I copied `!pip install tensorflow-gpu==2.0.0-beta1` as you said to install the required version for TF's GPU builds in your `exac sequence of commands`, and it works perfectly fine for me.

![image](https://user-images.githubusercontent.com/41635766/77828967-a945f000-7140-11ea-990e-95ff9b77336f.png)

Is it possible that you can share your code or the steps that you took to reproduce them? It maybe that the problem lies in the process rather then that single line of code.

Here is a [link](https://colab.research.google.com/drive/1lzYn5PXVJaYD3i_OxMn3ojEOLyBO7ULO) ( I've set the permissions to edit it ) so you can see what settings I've set - it is the default as of now .

Hope to hear again from you soon!

**Comment by abpalaciot** [comment] 2020-03-28 20:53
Hi @Rubix982 !

![image](https://user-images.githubusercontent.com/54606640/77833528-d680a700-711c-11ea-9d01-32e71567b165.png)

The error produces when I make the import. Thankfully I was able to solve it by previously uninstalling tf.

**Comment by abpalaciot** [comment] 2020-03-28 20:57
Also when I start training produces this error/warning:

WARNING:tensorflow:Entity <function train_step at 0x7f0725bfd730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function train_step at 0x7f0725bfd730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function train_step at 0x7f0725bfd730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function train_step at 0x7f0725bfd730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method CNN_Encoder.call of <__main__.CNN_Encoder object at 0x7f0944685be0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method CNN_Encoder.call of <__main__.CNN_Encoder object at 0x7f0944685be0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method CNN_Encoder.call of <__main__.CNN_Encoder object at 0x7f0944685be0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method CNN_Encoder.call of <__main__.CNN_Encoder object at 0x7f0944685be0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7f09441fae48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7f09d56178c8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7f09d56178c8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7f09d5617b70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7f09d5617b70>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7f0944685ba8>>: AttributeError: module 'gast' has no attribute 'Num'

![image](https://user-images.githubusercontent.com/54606640/77833597-69b9dc80-711d-11ea-9f0b-2128ecda6216.png)

This is working in the Image Captioning tutorial by TF in Colaboratory using tensorflow-gpu==2.0.0b1

**Comment by Rubix982** [comment] 2020-03-29 04:41
Are you referring to https://www.tensorflow.org/tutorials/text/image_captioning this by "Image Captioning Tutorial"?

**Comment by ravikyram** [comment] 2020-03-30 06:17
@abpalaciot 

Can you please provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by abpalaciot** [comment] 2020-03-30 17:30
> Are you referring to https://www.tensorflow.org/tutorials/text/image_captioning this by "Image Captioning Tutorial"?

Yes, that's the one.

**Comment by abpalaciot** [comment] 2020-03-30 17:32
This is the Colab:
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/image_captioning.ipynb

The only modification is done before making any import, run:

!pip install tensorflow-gpu==2.0.0-beta1

**Comment by ravikyram** [comment] 2020-03-31 11:42
@abpalaciot 

Is there any specific reason you want to use 2.0.0-beta1. You can use 2.x stable versions TF 2.0, 2.1.0,'2.2.0-rc1' instead.And let us know if you face any problems with latest stable 2.x releases?

**Comment by abpalaciot** [comment] 2020-04-01 13:06
Because it's the latest version of TensorFlow that works in Google Cloud Functions. The newest versions can't be installed beacuse pip was not updated.

**Comment by ravikyram** [comment] 2020-04-01 13:39
I have tried with TF 2.0.0-beta1 version and able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1d2c869abde58415689c62a1e1cd1e75/untitled758.ipynb). Thanks!

**Comment by ymodak** [comment] 2020-04-01 23:14
There is a tracking bug for with Google Cloud Function. 
To know more https://github.com/tensorflow/tensorflow/issues/34707#issuecomment-564266913
Closing this issue since switching to latest stable TF version (2.1) solves this problem. Thanks!

**Closed by ymodak** 2020-04-01 23:14 UTC
Labels: TF 2.0.0-beta0, stat:awaiting response, type:build/install

**Comment by trushraut18** [comment] 2020-05-18 09:32
When i connect colab with hosted runtime,tensorflow installed and work successfully but when i connect it to local runtime it either shows 'no module tensorflow' or run infinitely when i enter command
!pip install tensorflow

kindly help with this
