### ISSUE TITLE
model with "tf.keras.layers.Embedding" and "trainable=False" will be loaded as "trainable=True" after saving

### ISSUE THREAD

**Issue by xqr-g** [tensorflow/tensorflow#46329] opened 2021-01-11 05:05 UTC
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 2.5.0
-   **Python version**: 3.6
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
After saving a model with tf.keras.layers.Embedding as a layer and set trainable=False and loading the model, the layer has "trainable=True" in the get_config().

### Source code / logs
```
# Code is from https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(1000, 64, input_length=10, trainable=False))

input_array = np.random.randint(1000, size=(32, 10))
model.compile('rmsprop', 'mse')

model.summary()
model.save('some_path')
new_model = tf.keras.models.load_model('some_path')
new_model.summary()
```

model has 0 trainable parameters but new_model has 6400 trainable parameters.
model summary:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding_1 (Embedding)      (None, 10, 64)            64000     
=================================================================
Total params: 64,000
Trainable params: 0
Non-trainable params: 64,000
_________________________________________________________________
```
new_model summary:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding (Embedding)        (None, 10, 64)            64000     
=================================================================
Total params: 64,000
Trainable params: 64,000
Non-trainable params: 0
_________________________________________________________________
```

**Comment by ravikyram** [comment] 2021-01-11 17:53
I have tried in colab with TF version 2.4, nightly version (`2.5.0-dev20210111`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/8d793a53aeddd21ebcd250565363ec39/untitled608.ipynb). Thanks!

**Comment by ccrusius** [comment] 2021-01-14 00:26
Duplicate of #40994

**Closed by ccrusius** 2021-01-14 00:26 UTC
Labels: TF 2.5, comp:keras, stat:awaiting tensorflower, type:bug
