### ISSUE TITLE
Invalid loop structure: Loop "Preprocessor/map/while/while_context"

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/tensorflow#33752] opened 2019-10-27 03:11 UTC
I'm trying to map the output of one graph to the input of another but I'm getting following error while trying to do so. I'm using `export_meta_graph` and `import_scoped_meta_graph` with `input_map`. Following is my code :

```
import tensorflow as tf
import numpy as np
import cv2

grid_shape = (5,5)
image_shape=(150, 150)
num_channels=3

img = cv2.imread("/Users/vedanshu/test.jpeg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

def get_frozen_graph(graph_file):
    """Read Frozen Graph file from disk."""
    with tf.gfile.GFile(graph_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    return graph_def

# Import frozen graph for level 1
pb_fname1 = "/Users/vedanshu/frozen_graph/ssd_tomato_l1_frozen_graph.pb"
trt_graph1 = get_frozen_graph(pb_fname1)
detection_graph1 = tf.Graph()
with detection_graph1.as_default():
    tf.import_graph_def(trt_graph1, name='')
    tf_sess1 = tf.Session(graph=detection_graph1)

# Import frozen graph for level 2
pb_fname2 = "/Users/vedanshu/frozen_graph/faster_rcnn_tomato_l2_frozen_graph.pb"
trt_graph2 = get_frozen_graph(pb_fname2)
detection_graph2 = tf.Graph()
with detection_graph2.as_default():
    tf.import_graph_def(trt_graph2, name='')
    tf_sess2 = tf.Session(graph=detection_graph2)

from tensorflow.python.framework import meta_graph

graph = tf.get_default_graph()
tf_sess_main = tf.Session(graph=graph)

# Importing Level 1 graph to the default graph with namespace of ved_graph1
meta_graph1 = tf.train.export_meta_graph(graph=detection_graph1)
meta_graph.import_scoped_meta_graph(meta_graph1, import_scope='ved_graph1',)

tf_input1 = graph.get_tensor_by_name('ved_graph1/image_tensor:0')
tf_scores1 = graph.get_tensor_by_name('ved_graph1/detection_scores:0')
tf_boxes1 = graph.get_tensor_by_name('ved_graph1/detection_boxes:0')
tf_classes1 = graph.get_tensor_by_name('ved_graph1/detection_classes:0')
tf_num_detections1 = graph.get_tensor_by_name('ved_graph1/num_detections:0')

boxes1 = tf_boxes1[0]  # index by 0 to remove batch dimension
scores1 = tf_scores1[0]
classes1 = tf_classes1[0]
num_detections1 = tf.dtypes.cast(tf_num_detections1[0], tf.int32)

def image_grid(input_tensor, grid_shape=(5,5), image_shape=(150, 150), num_channels=3):
    # https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/contrib/gan/python/eval/python/eval_utils_impl.py#L34
    height, width = grid_shape[0] * image_shape[0], grid_shape[1] * image_shape[1]
    input_tensor = tf.reshape(
      input_tensor, tuple(grid_shape) + tuple(image_shape) + (num_channels,))
    input_tensor = tf.transpose(input_tensor, [0, 1, 3, 2, 4])
    input_tensor = tf.reshape(
      input_tensor, [grid_shape[0], width, image_shape[0], num_channels])
    input_tensor = tf.transpose(input_tensor, [0, 2, 1, 3])
    input_tensor = tf.reshape(
      input_tensor, [height, width, num_channels])
    return input_tensor

def get_grid_roies():
    def condition1(i, boxes_pixels):
        return tf.less(i, num_detections1)
    def body1(i, boxes_pixels):
        normalizer = [tf.shape(tf_input1[0])[0], tf.shape(tf_input1[0])[1], tf.shape(tf_input1[0])[0], tf.shape(tf_input1[0])[1]]
        box = tf.multiply(boxes1[i], tf.dtypes.cast(normalizer, tf.float32))
        box = tf.dtypes.cast(tf.round(box), tf.int32)
        boxes_pixels = boxes_pixels.write(i, box)
        return [tf.add(i, 1), boxes_pixels]

    i = tf.constant(0)
    boxes_pixels = tf.TensorArray(dtype=tf.int32,size=1,dynamic_size=True,clear_after_read=False)

    _, boxes_pixels = tf.while_loop(condition1,body1,[i, boxes_pixels])
    boxes_pixels = boxes_pixels.stack()

    def condition2(j, boxes_pixels, roies):
        return tf.less(j, tf.shape(boxes_pixels)[0])
    def body2(j, boxes_pixels, roies):
        startY =  boxes_pixels[j][0]
        startX =  boxes_pixels[j][1]
        endY =  boxes_pixels[j][2]
        endX =  boxes_pixels[j][3]
        roi = tf_input1[0, startY:endY, startX:endX] # batch: 0
        roi = tf.image.resize_image_with_pad(roi,image_shape[0],image_shape[1])
        roi = tf.dtypes.cast(roi, tf.uint8)
        roies = roies.write(j, roi)
        return [tf.add(j, 1), boxes_pixels, roies]

    j = tf.constant(0)
    roies = tf.TensorArray(dtype=tf.uint8,size=1,dynamic_size=True,clear_after_read=False,
                           infer_shape=False)

    _, _, roies = tf.while_loop(condition2,body2,[j, boxes_pixels, roies])

    # Adding padding for making grid
    roies = roies.stack()
    zero_pad = tf.zeros([1,image_shape[0],image_shape[1],num_channels], tf.uint8)
    _no_pad = tf.mod(tf.shape(roies)[0], tf.constant(grid_shape[0]*grid_shape[1]))
    no_pad = tf.cond(tf.equal(_no_pad, tf.constant(0)), lambda: tf.constant(0), 
                     lambda: tf.subtract(tf.constant(grid_shape[0]*grid_shape[1]), _no_pad))
    zero_pad = tf.tile(zero_pad, [no_pad,1,1,1])
    roies = tf.concat([roies, zero_pad], axis=0)

    # Creating batch of images of size grid_shape[0]*image_shape[0]
    size = grid_shape[0]*grid_shape[1]
    n_iter = tf.dtypes.cast(tf.divide(tf.shape(roies)[0], tf.constant(size)), tf.int32)
    k = tf.constant(0)
    grid_roies = tf.TensorArray(dtype=tf.uint8,size=1,dynamic_size=True,clear_after_read=False,infer_shape=False)

    def condition3(k, grid_roies):
        return tf.less(k, n_iter)

    def body3(k, grid_roies):
        grid_roi = image_grid(roies[size*k:size*(k+1)], grid_shape, image_shape, num_channels)
        grid_roies = grid_roies.write(k, grid_roi)
        return [tf.add(k, 1), grid_roies]

    _, grid_roies = tf.while_loop(condition3, body3, [k, grid_roies])

    grid_roies = grid_roies.stack() 

    return grid_roies

def create_empty_grid():
    grid_roies = tf.zeros([1,image_shape[0]*grid_shape[0],image_shape[1]*grid_shape[1],num_channels], tf.uint8)
    return grid_roies

# Grid is filled along the column first
grid_roies = tf.cond(tf.equal(num_detections1, tf.constant(0)), create_empty_grid, get_grid_roies)

# Importing Level 1 graph to the default graph with namespace of ved_graph2
meta_graph2 = tf.train.export_meta_graph(graph=detection_graph2)
meta_graph.import_scoped_meta_graph(meta_graph2, input_map={'image_tensor': grid_roies}, import_scope='ved_graph2',)

tf_scores2 = graph.get_tensor_by_name('ved_graph2/detection_scores:0')
tf_boxes2 = graph.get_tensor_by_name('ved_graph2/detection_boxes:0')
tf_classes2 = graph.get_tensor_by_name('ved_graph2/detection_classes:0')
tf_num_detections2 = graph.get_tensor_by_name('ved_graph2/num_detections:0')

num_detections2 = tf_sess_main.run(tf_num_detections2, feed_dict={tf_input1: img[None, ...]})
```

The last line is throwing me following error:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Invalid loop structure: Loop "Preprocessor/map/while/while_context" has more than one LoopCond node: {{node ved_graph2/Preprocessor/map/while/LoopCond}} and {{node ved_graph1/Preprocessor/map/while/LoopCond}}. This is an internal bug, please file a bug report with instructions on how to reproduce the error.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-19-f4ccb146461b> in <module>
----> 1 num_detections2 = tf_sess_main.run(tf_num_detections2, feed_dict={tf_input1: img[None, ...]})

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Invalid loop structure: Loop "Preprocessor/map/while/while_context" has more than one LoopCond node: node ved_graph2/Preprocessor/map/while/LoopCond (defined at <ipython-input-16-efb8693a303c>:3)  and node ved_graph1/Preprocessor/map/while/LoopCond (defined at <ipython-input-7-ce9e14bfefad>:8) . This is an internal bug, please file a bug report with instructions on how to reproduce the error.
```

My specifications are:
OS : Mac 10.13.6
TF version: 1.13.1

**Comment by anshkumar** [comment] 2019-10-27 13:21
Thanks to the issue reported [here](https://github.com/tensorflow/tensorflow/issues/22162) and comment [here](https://github.com/tensorflow/tensorflow/issues/22162#issuecomment-428091121), I was able to fix this error. It does some renaming with the following code:

```
def rename_frame_name(graphdef, suffix):
    for n in graphdef.node:
        if "while" in n.name:
            if "frame_name" in n.attr:
                n.attr["frame_name"].s = str(n.attr["frame_name"]).replace("while_context",
                                                                           "while_context" + suffix).encode('utf-8')

```

Was this fixed in recent versions of tensorflow?

**Comment by ymodak** [comment] 2019-10-29 19:05
This is still an issue with recent TF version 1.15.0
I will close this issue since you have found a workaround and we can track this bug on the other thread you mentioned. Thanks!

**Closed by ymodak** 2019-10-29 19:05 UTC
Labels: TF 1.13, comp:ops, type:support

**Comment by pank2210** [comment] 2020-03-24 13:33
This note is for is as a help to other people who may have face similar problem but may be in different context.
I faced same error as pasted below 
"
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loop structure: Loop "s: "Preprocessor/map/while/while_contextgpu_id"
" has more than one LoopCond node: {{node 0/Preprocessor/map/while/LoopCond}} and {{node 1/Preprocessor/map/while/LoopCond}}. This is an internal bug, please file a bug report with instructions on how to reproduce the error.
"
I was using Google Object detection API faster RCNN on TF v1.13.1 with RT 5.0 and CUDANN 7.5 cuda kit 9.0.
my intention was to load inference graph on multiple GPU and i started getting this error at runtime.
I applied suggested solution of including below function
def rename_frame_name(graphdef, suffix):
    for n in graphdef.node:
        if "while" in n.name:
            if "frame_name" in n.attr:
                n.attr["frame_name"].s = str(n.attr["frame_name"]).replace("while_context",
                                                                           "while_context" + suffix).encode('utf-8')


After using this patch just after graph def was build using loading PB file code was working smoothly.

thanks for help.
