### ISSUE TITLE
Android Ndk 11

### ISSUE THREAD

**Issue by Muaazbinsaeed** [tensorflow/tensorflow#1607] opened 2016-03-23 20:36 UTC
Why Android Ndk 11 and other versions are not being supported by bazel android build?
It only supports "android-ndk-r10e".

**Comment by andrewharp** [comment] 2016-03-24 01:06
There are Bazel compatibility issues with r11 currently, so we suggest you stick with r10e for the time being. See https://github.com/tensorflow/tensorflow/issues/1468 for details and links to relevant r10e downloads.

**Comment by vrv** [comment] 2016-03-24 01:08
@andrewharp: is this a bug in bazel or a bug in TensorFlow?  If the former, have we filed a bug with them?

**Comment by andrewharp** [comment] 2016-03-24 01:18
Due to the nature of the errors people are seeing (like missing RELEASE.TXT files) I'm assuming Bazel. I'll see if I can reproduce with the latest Bazel and NDK to make sure.

**Comment by vrv** [comment] 2016-03-24 01:29
Ok thanks!  @damienmg in case he's curious :)

**Comment by damienmg** [comment] 2016-03-24 08:20
Yes this is a bazel bug (or rather an incompatibility between current Bazel and NDK r11). @ahumesky is working on it (internal reference is b/27613662 fyi)

**Comment by Muaazbinsaeed** [comment] 2016-03-24 15:38
@andrewharp why tensorflow couldn't be build by simple ndk-build and gradle ?

**Comment by andrewharp** [comment] 2016-03-24 19:43
@Muaazbinsaeed 
It would be possible to make Tensorflow build with ndk-build/Gradle, this just isn't something we can maintain right now.

If you look at https://github.com/miyosuda/TensorFlowAndroidMNIST/find/master, this is an example of linking Tensorflow into a Gradle/ndk-build environment. So you might have luck by compiling tensorflow/core:android_tensorflow_lib into a static .a library, then dropping it into your Gradle project.

**Comment by andrewharp** [comment] 2016-05-24 02:31
Closing, @ahumesky added NDK 11 support in https://github.com/bazelbuild/bazel/commit/abdaff492440b373bacd016d772ef73611a27901

**Closed by andrewharp** 2016-05-24 02:31 UTC
