### ISSUE TITLE
Tensorflow 1.13.1 import Error on Python 3.7.1

### ISSUE THREAD

**Issue by ghsama** [tensorflow/tensorflow#27035] opened 2019-03-22 11:44 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Windows 10 Pro, 64-bit
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 1.13.1
- Python version: 3.7.1
- Installed using virtualenv? pip? conda?: pip on a conda env

Firstly, I reinstalled in my old environment with python 3.5.6, and have faced the same error, then created a new one with 3.7.1 after seeing @gunan  on the #22300 issue .
I checked that i have the : _pywrap_tensorflow_internal.lib on the directory "..\Lib\site-packages\tensorflow\python"
i don't know what causes the error since tf 1.13.1 supports python 3.7

`Traceback (most recent call last):
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\EMP\Anaconda3\envs\MachineLearning\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.`

**Comment by YAOYI626** [comment] 2019-03-22 13:27
you could try `pip install --upgrade --no-deps --force-reinstall tensorflow`, it makes tensorflow 1.13.1 work on my win10

**Comment by ghsama** [comment] 2019-03-22 13:50
> you could try `pip install --upgrade --no-deps --force-reinstall tensorflow`, it makes tensorflow 1.13.1 work on my win10

I try it and still having the same error

**Comment by shaolinkhoa** [comment] 2019-03-22 14:33
I think if you don't need python version 3.7 then you should downgrade the python version to 3.6.8.
Because on the [pip guide](https://www.tensorflow.org/install/pip) said : `Requires Python 3.4, 3.5, or 3.6]`

You can use conda to create a python version 3.6 and install tensorflow:
`conda create -n py36 python=3.6 pip tensorflow`

**Comment by ghsama** [comment] 2019-03-22 14:51
> I think if you don't need python version 3.7 then you should downgrade the python version to 3.6.8.
> Because on the [pip guide](https://www.tensorflow.org/install/pip) said : `Requires Python 3.4, 3.5, or 3.6]`
> 
> You can use conda to create a python version 3.6 and install tensorflow by conda. Because Conda has supported tensorflow 1.13.1. Just run this code then conda will do the rest.
> `conda create -n py36 python=3.6 pip tensorflow`

I installed tf 1.13.1 firstly on my python 3.6 environment, then get the error checking other issues they suggested that it's due to compatibility with python 3.7. Now i face it even on tf 1.10 on python 3.6.

**Comment by shaolinkhoa** [comment] 2019-03-22 15:55
Then I think your CUDA toolkit and cuDNN are not correct.
I suggest you install tensorflow by conda intead of pip. Because currently, Anaconda has supported tensorflow 1.13.1 package and they will also install the correct CUDA toolkit and cuDNN for you.

So my solution for you:
+ Check your Nvidia GPU driver. You should install Nvidia GPU driver version >= 410.x
+ Run this command on Conda prompt. It will create a new environment which has tensorflow 1.13.1 in it. 
`conda create -n py36 python=3.6 pip tensorflow`

**Comment by ghsama** [comment] 2019-03-22 16:58
> I suggest you install tensorflow by conda intead of pip. Because currently, Anaconda has supported tensorflow 1.13.1 package.
> Run this command on Conda prompt. It will create a new environment which has tensorflow 1.13.1 in it.
> `conda create -n py36 python=3.6 pip tensorflow`

i install usinf pip and not conda, i tried it and it changed anything
the solution i found temprary is to make a python 3.5.6 and install tensorflow 1.9 waiting for a solution for the issue.

**Comment by jvishnuvardhan** [comment] 2019-03-22 17:07
@ghsama Please uninstall tensorflow and python completely and then reinstall python3.6.5 (that I have) or python3.6.6. Then, install tensorflow1.13.1 or tensorflow1.12 using the instructions provided [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Please let me know how it progresses. thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-22 17:09
@ghsama If you like conda, you could follow the instructions given by others (above) and install TF. Some time when you have many version install and uninstalled, then there will be lot of incompatibilities arises. Please start fresh by uninstalling python and tensorflow and reinstall them. Thanks!

**Comment by lyind** [comment] 2019-04-03 08:31
I am also plagued by the `ImportError: DLL load failed: ...`  issue.

**System**
KVM virtual machine with 3 cores and CPU type "host"
OS: Win64 (Windows 10)
CPU: i5-6600 (has AVX2)
no dedicated GPU

**Environment**
python 3.6.8 from anaconda
tensorflow 1.13.1 from anaconda
libmklml 2019.0.3
protobuf 3.6.1 from anaconda

I installed the debugging tools from the Windows SDK and enabled the "show loader snaps" flag for python.exe as follows:
`gflags.exe -i python.exe +sls`

I then executed a python application - which imports tensorflow - under the cdb debugger and looked at what happens when `_pywrap_tensorflow_internal.pyd` is loaded:
`cdb.exe python.exe my_app.py`
```
(1824.11bc): Integer divide-by-zero - code c0000094 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\...\app\lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd -
_pywrap_tensorflow_internal+0x2a57cd:
00007ffa`b92557cd f735b9d15105    div     eax,dword ptr [_pywrap_tensorflow_internal!tensorflow::_SequenceExample_default_instance_+0x412c (00007ffa`be77298c)] ds:00007ffa`be77298c=00000000
... (entered "g") ...
1824:29e0 @ 1267255250 - LdrpAllocateTls - INFO: TlsVector 00000234F9D5B020 Index 0 : 8 bytes copied from 00007FFAF883C83C to 00000234F9CC2220
(1824.11bc): Integer divide-by-zero - code c0000094 (!!! second chance !!!)
_pywrap_tensorflow_internal+0x2a57cd:
00007ffa`b92557cd f735b9d15105    div     eax,dword ptr [_pywrap_tensorflow_internal!tensorflow::_SequenceExample_default_instance_+0x412c (00007ffa`be77298c)] ds:00007ffa`be77298c=00000000
```

To me this looks like a **divide by zero** caused by the protobuf generated code for `SequenceExample`, but I could be wrong.

It may be helpful to have a look at the generated code for `SequenceExample`, the `default_instance` constructor in particular.

Please contact me for assistance in further analyzing this issue.

**Comment by jvishnuvardhan** [comment] 2019-04-05 21:15
@lyind Did you try uninstalling and reinstalling tensorflow and python. Some time old files affect the new installation. Thanks!

**Comment by lyind** [comment] 2019-04-09 10:39
@jvishnuvardhan I assemble an embedded python installation in a temporary directory on Windows x64 mainly using default conda (anaconda) python packages. Whenever I run my Makefiles everything is re-downloaded. The regular tensorflow installer is not used.

**Comment by jvishnuvardhan** [comment] 2019-04-10 17:34
@lyind I am not really sure what is the root-cause as we don't support anaconda. Could you also post it in anaconda repo? Thanks!

**Comment by mrevow** [comment] 2019-04-11 18:40
In case others face this here is my experience. 
I ran into this issue after upgrading my python installation from 3.6.6 I did the upgrade because of tensorboard issue https://github.com/tensorflow/tensorboard/issues/1976. I used conda to upgrade and it appears this causes corruption of many installed pyd modules (including non-tensorflow packagages). I got around all of the failures, one by one,  by reinstalling the packages as suggested above by @YAOYI626 
`pip install --force-reinstall  --upgrade <module>`

**Comment by jvishnuvardhan** [comment] 2019-04-17 20:47
@lyind Can you try @mrevow suggestion. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-30 18:25
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-30 18:25 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install

**Comment by TarrySingh** [comment] 2019-05-28 12:59
> I think if you don't need python version 3.7 then you should downgrade the python version to 3.6.8.
> Because on the [pip guide](https://www.tensorflow.org/install/pip) said : `Requires Python 3.4, 3.5, or 3.6]`
> 
> You can use conda to create a python version 3.6 and install tensorflow by conda. Because Conda has supported tensorflow 1.13.1. Just run this code then conda will do the rest.
> `conda create -n py36 python=3.6 pip tensorflow`

TF 1.13.1 supports Python3.7
