### ISSUE TITLE
Why there is no C  GPU based tensorflow for windows?

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/tensorflow#19520] opened 2018-05-24 07:25 UTC
I have seen that there are only Linux and MacOS based installations for the C language.
Kindly let me know if there is any tensorflow for the Windows in C langauage.

**Comment by asimshankar** [comment] 2018-05-25 07:17
There are no GPU binary releases for the C library for Windows yet (see https://github.com/tensorflow/tensorflow/issues/16660#issuecomment-362480779)

CPU releases are available at:
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.8.0.zip 
(Replace 1.8.0 with the version of interest).

Closing as a duplicate of #16660

**Closed by asimshankar** 2018-05-25 07:17 UTC
