### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by tiantaohuawei** [tensorflow/tensorflow#37957] opened 2020-03-27 01:18 UTC
/home/tf_mtrl# python tf_train.py
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Retrying in 1 seconds
Loading configuration... done.
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
~~~ Well done ~~~
~~~ Well done ~~~
~~~ Well done ~~~
~~~ Well done ~~~
~~~ Well done ~~~
~~~ Well done ~~~
!!! Collision !!!
~~~ Well done ~~~
~~~ Well done ~~~
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
Segmentation fault (core dumped)

**Comment by tiantaohuawei** [comment] 2020-03-27 01:44
I get callstack as below.
Fatal Python error: Segmentation fault

Thread 0x0000ffffbb0d8b20 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443 in _call_tf_sessionrun
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350 in _run_fn
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365 in _do_call
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359 in _do_run
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180 in _run
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956 in run
  File "/home/tf_mtrl_origin_1/tf_adnagent.py", line 282 in _update_network
  File "/home/tf_mtrl_origin_1/tf_adnagent.py", line 236 in train
  File "tf_train.py", line 19 in <module>
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
Segmentation fault (core dumped)

**Comment by gadagashwini** [comment] 2020-03-27 07:44
@tiantaohuawei, Please provide the complete standalone code and Tensorflow version. Thanks!

**Comment by tiantaohuawei** [comment] 2020-03-27 08:29
standalone is not available. the environment is a bit complicated。tht tf version is 1.15

**Comment by gadagashwini** [comment] 2020-03-30 06:47
@tiantaohuawei, It would be hard to find the root cause of the issue without the standalone code. Thanks!

**Comment by mihaimaruseac** [comment] 2020-03-30 16:39
Please fill in issue template (close this and reopen a new one if that is easier, tag me in it).

Also, please use ` ``` ` around code blocks to make them easier to read. We prioritize issues based on the readability of their description and the presence of a reproducer too

**Comment by gadagashwini** [comment] 2020-04-08 07:16
@tiantaohuawei, Please update the issue with standalone code. Thanks

**Comment by gadagashwini** [comment] 2020-04-16 11:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-04-16 11:36 UTC
Labels: TF 1.15, stat:awaiting response, type:bug

**Comment by gnvml** [comment] 2020-10-14 04:04
@tiantaohuawei . Hi, I also have trouble like you. And now, Have you already solved the problem ? I need help . Thank you.
My call stack is below: 
```shell
Thread 0x0000007f96fb5010 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443 in _call_tf_sessionrun
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350 in _run_fn
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365 in _do_call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359 in _do_run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180 in _run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956 in run
  File "/home/vdsmbox/VDSMART/Project/ai-eyepro-offline/face_detector.py", line 52 in __call__
```
