### ISSUE TITLE
Can't configure due to undeclared packages inside if_android/if_ios

### ISSUE THREAD

**Issue by gustavla** [tensorflow/tensorflow#4312] opened 2016-09-10 03:13 UTC
I am having trouble configuring the latest master branch (dbe7ee0dfa9e5ab26284522379f2747510fc267b). When I run `./configure`, I get:
```
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: [...]/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by [...]/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished
```
To summarize, the dependencies that are included inside the `if_android` and `if_ios` are not found. They don't exist in the repository, so that is not that surprising. What is more surprising though is that my vanilla installation is not returning empty lists when `if_android` is called. I haven't looked into how those functions work, so not sure why that is happening.

### Environment info
Setup: CentOS, Bazel 0.3.1, CUDA 7.5, CuDNN 5.1, Tensorflow master (dbe7ee0dfa9e5ab26284522379f2747510fc267b)

I run `configure` and set it up for GPU support. Actually, I don't think this is criticial, but first I had to open up `configure` and add `--output_base=...` on the two calls to `bazel`, since my setup requires a custom cache directory.

### Fix
The `if_...` lines were added in ed87884e50e1a50f7dc7b36dc7a7ff225442bee0, so a fix that I know works is to use its parent commit 7705791619f5e851687e9a63b4315087e189f8be.

**Comment by woodshop** [comment] 2016-09-10 03:49
I can confirm this issue. In my environment `configure` fails on the latest commit (7705791619f5e851687e9a63b4315087e189f8be) with the following errors:

```
ERROR: /home/sarroff/repo/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /home/sarroff/repo/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /home/sarroff/repo/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by /home/sarroff/repo/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

As suggested by @gustavla, I checked out https://github.com/tensorflow/tensorflow/commit/ed87884e50e1a50f7dc7b36dc7a7ff225442bee0 and `configure` ran without error.

**Comment by ibab** [comment] 2016-09-10 10:46
You can fix this by commenting out the `if_android` and `if_ios` calls in `contrib/session_bundle/BUILD` and the `android_tensorflow_lib_lite_no_rtti_lite_runtime` target in the core `BUILD` file.
These seem to be based on Google internal targets.

`if_android` doesn't return an empty list directly, but gives you a `select` object, which is resolved to an empty list by bazel.

**Comment by woodshop** [comment] 2016-09-10 12:39
Confirmed that if I make these changes to the following three files `configure` runs without error:

- Remove all `if_mobile` and `if_android` conditions from `tensorflow/contrib/session_bundle/BUILD`
- Remove the `ios_tensorflow_test_lib` target from `tensorflow/core/BUILD`
- Remove the `android_tensorflow_kernels_no_rtti_lite_runtime` target from `tensorflow/core/kernels/BUILD`

**Comment by kwotsin** [comment] 2016-09-10 13:16
> Remove all if_mobile and if_android conditions from tensorflow/contrib/session_bundle/BUILD

Do you mean that I comment out everything related to mobile devices,  not just if_mobile and if_android? Or are these 2 components sufficient?

```
#    "if_android",
#   "if_ios",
#    "if_mobile",
#   "if_not_mobile",
```

**Comment by ibab** [comment] 2016-09-10 13:21
You don't need to remove them from the call to `load` at the top of the file, but instead each time they are used, like this:
```python
cc_library(
    name = "session_bundle",
    srcs = ["session_bundle.cc"],
    hdrs = ["session_bundle.h"],
    copts = if_ios(["-DGOOGLE_LOGGING"]),
    visibility = ["//visibility:public"],
    deps = [
        ":signature",
    ] + if_not_mobile([
        ":manifest_proto_cc",
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:framework",
        "//tensorflow/core:lib",
        "//tensorflow/core:protos_all_cc",
    ]) #+ if_mobile([
    #    ":manifest_portable_proto",
    #    "//tensorflow/core:meta_graph_portable_proto",
    #]) + if_android([
    #    "//tensorflow/core:android_lib_lite",
    #]) + if_ios([
    #    "//tensorflow/core:ios_tensorflow_lib",
    #]),
)
```

**Comment by msevrens** [comment] 2016-09-10 21:50
Having this issue as well

**Comment by raix852** [comment] 2016-09-11 01:14
I had the same issue too. Following @ibab @woodshop suggestions solved this problem.
I think `configure` need an option to decide target environment.

**Comment by kwotsin** [comment] 2016-09-11 07:19
I fixed the issue according to @ibab and @woodshop advice as well. 

However, I also commented out `copts = if_ios(["-DGOOGLE_LOGGING"]),` and any if_ios conditions, which was seen invalid when I was configuring. Thank you!

**Comment by Eidosper** [comment] 2016-09-11 13:40
if you download tensorflow from github instead of 'git clone', you will not meet this.

**Comment by woodshop** [comment] 2016-09-11 14:01
Just to clarify @Eidosper's comment: the suggestion is to use an official TF release (e.g. tagged v0.10.0rc0). This is not a solution for anyone that needs the current state of TF development (i.e. the newest commit of the master branch).

**Comment by martinwicke** [comment] 2016-09-12 22:01
@petewarden This seems to be a sync issue maybe? Do the `is_*` macros only work on the inside and should be rewritten? 

The rules work fine in our CI, which makes it a little more confusing. What's used to determine `if_mobile` etc.?

**Comment by petewarden** [comment] 2016-09-12 22:20
This is surprising because these rules have been in for several months without causing this issue, so something must have changed recently. The is_* macros rely on config_settings in the top-level BUILD file that test against cross-tool usage, so I wouldn't expect them to return non-empty results.

The quickest way to debug this is probably to reproduce it at head, and then do a binary search on github checkins to narrow it down to a particular commit. This shouldn't be too hard since it happens very quickly, but I'm traveling for the next couple of days and won't be able to work on it until I'm done.

**Comment by ibab** [comment] 2016-09-12 22:53
@petewarden: I've narrowed the problem down to commit https://github.com/tensorflow/tensorflow/commit/ed87884e50e1a50f7dc7b36dc7a7ff225442bee0 using `git bisect`.
An easy way to reproduce it is to run `bazel fetch //tensorflow/contrib/session_bundle/...`.

**Comment by petewarden** [comment] 2016-09-12 23:06
Thanks for doing that @ibab! I've notified the author of that change, hopefully we should be able to figure out a fix.

**Comment by gustavla** [comment] 2016-09-13 00:24
@ibab I hope it didn't take you long, because I already did this and reported ed87884e50e1a50f7dc7b36dc7a7ff225442bee0 as the offending commit in my original post :smile:

Now, the question is, did that commit trigger a latent bug that was introduced at some other point in time or has it always been there. This is what I thought @petewarden was implying by saying they had been around for "several months", referring to the is_* macros. This would involve running a git bisect and in each step applying ed87884e50e1a50f7dc7b36dc7a7ff225442bee0 as a patch.

I was thinking it might be a bazel version thing, but I tried both 0.3.1 and 0.3.0 (after a quick fix: #4343), and I have the same problem.

**Comment by tmulc18** [comment] 2016-09-13 22:15
@msevrens [https://hackathonprojects.wordpress.com/2016/09/13/installing-10-series-gpus-cuda-8-0rc-and-tensorflow-on-ubuntu-14-04/](url) here is a post describing the comments if you're still having trouble

**Comment by shamak** [comment] 2016-09-14 00:13
@tmulc18 you should fix that link :)

**Comment by andrewharp** [comment] 2016-09-15 01:46
This seems to have auto-closed when I merged f66b491, but it does not seem to be completely fixed yet, does it?

**Comment by woodshop** [comment] 2016-09-15 02:20
No, it doesn't seem entirely solved. The configuration fails in my environment due to the following two targets:
  - The `ios_tensorflow_test_lib` target from `tensorflow/core/BUILD`
  - The `android_tensorflow_kernels_no_rtti_lite_runtime` target from `tensorflow/core/kernels/BUILD`

However I am now able to build the project _despite_ configuration errors, whereas I was not able to do so before commit f66b491.

Commenting out the targets enables the configuration to complete without errors.

**Comment by israelg99** [comment] 2016-09-15 06:07
I fresh cloned tensorflow for latest master commit, and I confirm I'm experiencing the same issues as @woodshop.
However, I didn't have those issues configuring a few days ago.

**Comment by suiyuan2009** [comment] 2016-09-18 06:42
meet same issue.

**Comment by jmhodges** [comment] 2016-09-19 22:33
Just got told my #4476 is a duplicate of this ticket, so coming here with: Is there anything I can do to get this fixed up? It seems to be hitting a number of external contributors and it's been 10 days since it was first reported. A time suck for all of us to be rediscovering it and working out the same patches!

**Comment by jmhodges** [comment] 2016-09-19 22:34
Just got told my #4476 is a duplicate of this ticket, so coming here with: Is there anything I can do to get this fixed up? It seems to be hitting a number of external contributors and it's been 10 days since it was first reported. A time suck for all of us to be rediscovering it and working out the same patches!

**Comment by vrv** [comment] 2016-09-19 22:44
If you remove the reference to //base and the references to the lite_no_rtti_lite_runtime and android_tensorflow_lib_lite_no_rtti_lite_runtime targets, does everything work?  If so I'll prepare a change to strip these out.

I don't know why our CI build isn't catching these obvious errors.

**Comment by jmhodges** [comment] 2016-09-19 22:45
Yeah, if you delete all mentions of "//base", "//tensorflow/core:android_proto_lib_no_rtti_lite_runtime", and "//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime" it seems to buidl okay.


I only get these errors when I build with CUDA. Could that be the deal? (I'm also on OS X.)

**Comment by andrewharp** [comment] 2016-09-19 22:46
@vrv I'm halfway done with a CL to fix the export right now

**Comment by vrv** [comment] 2016-09-19 22:48
@andrewharp woohoo, thanks! send to me :)

@jmhodges thanks for confirming.  We also have CUDA builds, so perhaps we're only building what's necessary for tests / pip installation, rather than the entire repo (e.g., we don't try to build  tensorflow/..., though maybe we should.  At least we should validate the BUILD files, which I thought we used to do).  cc @gunan

**Comment by jmhodges** [comment] 2016-09-19 22:49
Hunh, weird. It happens as soon as I run `./configure` on a fresh build!

**Comment by gunan** [comment] 2016-09-19 23:03
we do not presubmit with cuda+mac. We only have nightlies.
Those builds are broken at the moment, but at first glance, it looks like a different issue (the nightly failures and the reports here)

**Comment by andrewharp** [comment] 2016-09-21 19:39
ea0771512af531c2a3fa1f60d3e6dd2b47384e99 is commited, which should fix the remaining configure issues regarding `//base` and `android_tensorflow_lib_lite_no_rtti_lite_runtime`.

**Closed by andrewharp** 2016-09-21 19:39 UTC
Labels: bug, installation/startup
