### ISSUE TITLE
TFDS: deep_weeds down

### ISSUE THREAD

**Issue by dcpatton** [tensorflow/tensorflow#44053] opened 2020-10-15 14:06 UTC
This has been ongoing for several days:

tfds.load('deep_weeds', shuffle_files=True, as_supervised=True, try_gcs=True)

ConnectionError: HTTPSConnectionPool(host='nextcloud.qriscloud.org.au', port=443): Max retries exceeded with url: /index.php/s/a3KxPawpqkiorST/download (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff54e566470>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by ravikyram** [comment] 2020-10-16 10:32
@dcpatton 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know TF version you are using.
Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by dcpatton** [comment] 2020-10-16 12:55
https://colab.research.google.com/drive/1sibA5g9okamy4UL4rdDF_k4yg9YD7Mq7?usp=sharing

**Comment by dcpatton** [comment] 2020-10-16 12:56
TFDS version 2.1.0

**Comment by ravikyram** [comment] 2020-10-19 07:36
I have tried in colab and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0773c687f8eeca8319d47936b08f0762/untitled464.ipynb).Thanks!

**Comment by ymodak** [comment] 2020-10-20 00:24
The deep weeds dataset file hosting has been updated which is causing the issue.
commit [51e3fab](https://github.com/AlexOlsen/DeepWeeds/commit/da084f62bcd1a2b0afeb8b81f1a27be3186391a1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

**Comment by ymodak** [comment] 2020-10-27 19:25
Closing this issue since the associated PR is now merged. Feel free to comment if have further problems and we can revisit the issue if necessary. Thanks!

**Closed by ymodak** 2020-10-27 19:25 UTC
Labels: TF 2.3, comp:data, stat:awaiting response, type:bug
