### ISSUE TITLE
No improvement in performance of deeplabv3_257_mv_gpu.tflite on TFLite for GPU

### ISSUE THREAD

**Issue by WenguoLi** [tensorflow/tensorflow#27613] opened 2019-04-08 03:50 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MI 5
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

**Describe the current behavior**
I'm trying to run TFLite Model '[deeplabv3_257_mv_gpu.tflite](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/deeplabv3_257_mv_gpu.tflite)' with GPU delegate on Android  devices.  According to PR for label_image #27464,  I modified the label_image code to support the gpu delegate and removed the code from [205](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/label_image.cc#L205) to [251](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/label_image.cc#L251) lines .  

```
void RunInference(Settings* s) {
  if (!s->model_name.c_str()) {
    LOG(ERROR) << "no model file name\n";
    exit(-1);
  }

  std::unique_ptr<tflite::FlatBufferModel> model;
  std::unique_ptr<tflite::Interpreter> interpreter;
  model = tflite::FlatBufferModel::BuildFromFile(s->model_name.c_str());
  if (!model) {
    LOG(FATAL) << "\nFailed to mmap model " << s->model_name << "\n";
    exit(-1);
  }
  LOG(INFO) << "Loaded model " << s->model_name << "\n";
  model->error_reporter();
  LOG(INFO) << "resolved reporter\n";

  tflite::ops::builtin::BuiltinOpResolver resolver;

  tflite::InterpreterBuilder(*model, resolver)(&interpreter);
  if (!interpreter) {
    LOG(FATAL) << "Failed to construct interpreter\n";
    exit(-1);
  }

  interpreter->UseNNAPI(s->accel);
  interpreter->SetAllowFp16PrecisionForFp32(s->allow_fp16);

  if (s->verbose) {
    LOG(INFO) << "tensors size: " << interpreter->tensors_size() << "\n";
    LOG(INFO) << "nodes size: " << interpreter->nodes_size() << "\n";
    LOG(INFO) << "inputs: " << interpreter->inputs().size() << "\n";
    LOG(INFO) << "input(0) name: " << interpreter->GetInputName(0) << "\n";

    int t_size = interpreter->tensors_size();
    for (int i = 0; i < t_size; i++) {
      if (interpreter->tensor(i)->name)
        LOG(INFO) << i << ": " << interpreter->tensor(i)->name << ", "
                  << interpreter->tensor(i)->bytes << ", "
                  << interpreter->tensor(i)->type << ", "
                  << interpreter->tensor(i)->params.scale << ", "
                  << interpreter->tensor(i)->params.zero_point << "\n";
    }
  }

  if (s->number_of_threads != -1) {
    interpreter->SetNumThreads(s->number_of_threads);
  }

  int image_width = 224;
  int image_height = 224;
  int image_channels = 3;
  std::vector<uint8_t> in = read_bmp(s->input_bmp_name, &image_width,
                                     &image_height, &image_channels, s);

  int input = interpreter->inputs()[0];
  if (s->verbose) LOG(INFO) << "input: " << input << "\n";

  const std::vector<int> inputs = interpreter->inputs();
  const std::vector<int> outputs = interpreter->outputs();

  if (s->verbose) {
    LOG(INFO) << "number of inputs: " << inputs.size() << "\n";
    LOG(INFO) << "number of outputs: " << outputs.size() << "\n";
  }
#if defined(ANDROID) || defined(__ANDROID__)
  TfLiteGpuDelegateOptions kMyOptions = {
      .metadata = nullptr,
      .compile_options =
          {
              .precision_loss_allowed = 0,
              .preferred_gl_object_type = TFLITE_GL_OBJECT_TYPE_FASTEST,
              .dynamic_batch_enabled = 0,
          },
  };
  if (s->allow_fp16) kMyOptions.compile_options.precision_loss_allowed = 1;

  TfLiteDelegate* delegate;
  if (s->gl_backend) {
    delegate = TfLiteGpuDelegateCreate(&kMyOptions);
    if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return;
  } else {
#endif
    if (interpreter->AllocateTensors() != kTfLiteOk) {
      LOG(FATAL) << "Failed to allocate tensors!";
    }
#if defined(ANDROID) || defined(__ANDROID__)
  }
#endif

  if (s->verbose) PrintInterpreterState(interpreter.get());

  // get input dimension from the input tensor metadata
  // assuming one input only
  TfLiteIntArray* dims = interpreter->tensor(input)->dims;
  int wanted_height = dims->data[1];
  int wanted_width = dims->data[2];
  int wanted_channels = dims->data[3];

  switch (interpreter->tensor(input)->type) {
    case kTfLiteFloat32:
      s->input_floating = true;
      resize<float>(interpreter->typed_tensor<float>(input), in.data(),
                    image_height, image_width, image_channels, wanted_height,
                    wanted_width, wanted_channels, s);
      break;
    case kTfLiteUInt8:
      resize<uint8_t>(interpreter->typed_tensor<uint8_t>(input), in.data(),
                      image_height, image_width, image_channels, wanted_height,
                      wanted_width, wanted_channels, s);
      break;
    default:
      LOG(FATAL) << "cannot handle input type "
                 << interpreter->tensor(input)->type << " yet";
      exit(-1);
  }

  profiling::Profiler* profiler = new profiling::Profiler();
  interpreter->SetProfiler(profiler);

  if (s->profiling) profiler->StartProfiling();
  if (s->loop_count > 1)
    for (int i = 0; i < s->number_of_warmup_runs; i++) {
      if (interpreter->Invoke() != kTfLiteOk) {
        LOG(FATAL) << "Failed to invoke tflite!\n";
      }
    }

  struct timeval start_time, stop_time;
  gettimeofday(&start_time, nullptr);
  for (int i = 0; i < s->loop_count; i++) {
    if (interpreter->Invoke() != kTfLiteOk) {
      LOG(FATAL) << "Failed to invoke tflite!\n";
    }
  }
  gettimeofday(&stop_time, nullptr);
  LOG(INFO) << "invoked \n";
  LOG(INFO) << "average time: "
            << (get_us(stop_time) - get_us(start_time)) / (s->loop_count * 1000)
            << " ms \n";
#if 0
  if (s->profiling) {
    profiler->StopProfiling();
    auto profile_events = profiler->GetProfileEvents();
    for (int i = 0; i < profile_events.size(); i++) {
      auto op_index = profile_events[i]->event_metadata;
      const auto node_and_registration =
          interpreter->node_and_registration(op_index);
      const TfLiteRegistration registration = node_and_registration->second;
      PrintProfilingInfo(profile_events[i], op_index, registration);
    }
  }

  const float threshold = 0.001f;

  std::vector<std::pair<float, int>> top_results;

  int output = interpreter->outputs()[0];
  TfLiteIntArray* output_dims = interpreter->tensor(output)->dims;
  // assume output dims to be something like (1, 1, ... ,size)
  auto output_size = output_dims->data[output_dims->size - 1];
  switch (interpreter->tensor(output)->type) {
    case kTfLiteFloat32:
      get_top_n<float>(interpreter->typed_output_tensor<float>(0), output_size,
                       s->number_of_results, threshold, &top_results, true);
      break;
    case kTfLiteUInt8:
      get_top_n<uint8_t>(interpreter->typed_output_tensor<uint8_t>(0),
                         output_size, s->number_of_results, threshold,
                         &top_results, false);
      break;
    default:
      LOG(FATAL) << "cannot handle output type "
                 << interpreter->tensor(input)->type << " yet";
      exit(-1);
  }

  std::vector<string> labels;
  size_t label_count;

  if (ReadLabelsFile(s->labels_file_name, &labels, &label_count) != kTfLiteOk)
    exit(-1);

  for (const auto& result : top_results) {
    const float confidence = result.first;
    const int index = result.second;
    LOG(INFO) << confidence << ": " << index << " " << labels[index] << "\n";
  }
#endif  
}
```

**Describe the expected behavior**

Version with GPUDelegate is a lot slower (228.445 ms per run vs 132.303 ms) than CPU.

**Other info / logs**

GPU:
```
gemini:/data/local/tmp $ ./label_image -g 1 -m deeplabv3_257_mv_gpu.tflite
nnapi error: requires android sdk version to be at least 27
Loaded model deeplabv3_257_mv_gpu.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
invoked 
average time: 228.445 ms 
```
CPU:
```
gemini:/data/local/tmp $ ./label_image -m deeplabv3_257_mv_gpu.tflite                                   <
nnapi error: requires android sdk version to be at least 27
Loaded model deeplabv3_257_mv_gpu.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 132.303 ms
```

**Comment by SanthoshRajendiran** [comment] 2019-04-20 14:08
Watching this

**Comment by impjdi** [comment] 2019-04-20 16:23
Performance regression on Mali is still being investigated.  We spent a full week, but wasn't able to easily identify the root cause yet.  Especially with Mali showing a higher variance on performance than Adreno where numbers are more stable.  I will update as soon as we have progress.

**Comment by anneyking** [comment] 2019-04-25 07:51
@impjdi
Is there any good news about Mali now?

**Comment by holyhao** [comment] 2019-05-14 10:52
@impjdi 
Is there any good news about this?

**Comment by impjdi** [comment] 2019-05-14 18:53
@anneyking @holyhao 

Sorry, the engineers in charge don't have cycles this week to investigate.  They may start next week.

**Comment by brucechou1983** [comment] 2020-06-04 09:33
any new findings about MALI performance optmization?

**Comment by impjdi** [comment] 2020-06-04 12:29
Yeah, we have a candidate for the root cause, but are working on a more systematic approach.  We "might" see some improvement by end of year if everything goes well =/

**Comment by brucechou1983** [comment] 2020-06-05 01:47
@impjdi I'm super curious about this suspicious root cause. I found some MALI gpu phones run much faster with delegate v2, which uses opencl delegate as the default backend. I tried to tune the work groups setting of conv2d and depthwise conv2d for opengl compute shader, but just like your team I don't see any obvious improvement. It's completely counterintuitive.

You mentioned about "a more systematic approach". Is that something about the opencl-opengl interoperability?

**Comment by marko-radojcic** [comment] 2020-06-05 01:59
I would say that connection is like rendering system for gui order of
complexity.

**Comment by impjdi** [comment] 2020-06-08 19:10
@brucechou1983 no, it's something else.  for example, loop unrolling & tiling are not handled efficiently in many of the mali drivers, so we may want to do the unrolling manually.  however, doing that makes the shader code quite unreadable and difficult to debug.  so we're making things to make that sort of task easy.

**Comment by sushreebarsa** [comment] 2021-08-01 14:45
@WenguoLi  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite
