### ISSUE TITLE
Scope Reusability in tf.nn.dynamic_rnn

### ISSUE THREAD

**Issue by sunilraiyani** [tensorflow/tensorflow#3421] opened 2016-07-20 17:13 UTC
I am getting this error when I try to run the code for RNN:

ValueError: Variable RNN/MultiRNNCell/Cell0/BasicLSTMCell/Linear/Matrix does not exist, disallowed. Did you mean to set reuse=None in VarScope?

Here is a snippet of my code for RNN:

lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(self._num_hidden, forget_bias=0.0)
cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self._num_layers)
self._initial_state = cell.zero_state(batch_size, tf.float32)

inputs=[tf.reshape(data_,[batch_size,num_cat]) for data_ in tf.split(0,max_length,tf.transpose(data,[1,0,2]))]
output,_=tf.nn.dynamic_rnn(cell,inputs,initial_state=self._initial_state,sequence_length=self.length)

The error seems to be in line:
output,_=tf.nn.dynamic_rnn(cell,inputs,initial_state=self._initial_state,sequence_length=self.length)

My input is a tensor with dimensions : batch_size x max_ seq_length x feature_vector_size
I am reshaping it to a list of dimensions : batch_size x feature_vector_size

I am assuming that the reusability of scope is handled internally by tf.nn.dynamic_rnn function. Any idea why this would happen? What could be the solution?

**Comment by concretevitamin** [comment] 2016-07-20 23:51
Can you paste a complete snippet program the reliably reproduces?  Might be some outside scope that wraps the lines you pasted.

**Comment by drcrook1** [comment] 2016-07-30 17:32
I actually have this exact same issue, but with different code.  I have posted the primary question here: https://stackoverflow.com/questions/38676668/rnn-cell-naming-issue-in-tensorflow

**Comment by drcrook1** [comment] 2016-07-30 17:33
I can also provide somebody the specifics to my notebook but I need you to send me a message or something, I don't want to push my password out too widely :)

**Comment by aselle** [comment] 2016-08-08 16:24
@drcrook1, we don't want to take your password. Could you extract the code from the notebook that could be run on standalone python?
@sunilraiyani could you attach the full program that reproducies the issue? 
Without a self-contained reproducible test case, we will need to close the issue.

**Comment by aselle** [comment] 2016-08-17 16:47
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-08-17 16:47 UTC
Labels: awaiting response
