### ISSUE TITLE
Unrolled LSTM terrible performance when tf.function is used

### ISSUE THREAD

**Issue by Feri73** [tensorflow/tensorflow#34920] opened 2019-12-07 02:11 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from : binary
- TensorFlow version : 2.0
- Python version: 3.6.9
- CUDA/cuDNN version: no CUDA
- GPU model and memory: no GPU

Well I thought I knew what tf.function does, but these two pieces of code confused me:

This does not use tf.function:
```
import time
import tensorflow as tf

rnn = tf.keras.layers.LSTM(256, return_state=True, unroll=True)

def go():
    return rnn(tf.zeros((1, 300, 256)))

st = time.time()
with tf.GradientTape() as tape:
    x = go()
print(f'graph: {time.time() - st}') # --> graph: 0.20923495292663574
st = time.time()
gradient = tape.gradient(x[-1], rnn.trainable_weights) # --> gradient: 0.4629485607147217
print(f'gradient: {time.time() - st}')
```

While this does:
```
import time
import tensorflow as tf

rnn = tf.keras.layers.LSTM(256, return_state=True, unroll=True)

@tf.function
def go():
    return rnn(tf.zeros((1, 300, 256)))

st = time.time()
with tf.GradientTape() as tape:
    x = go()
print(f'graph: {time.time() - st}') # --> graph: 12.843713283538818
st = time.time()
gradient = tape.gradient(x[-1], rnn.trainable_weights) # --> gradient: 2.7147161960601807
print(f'gradient: {time.time() - st}')
```

This difference in performance only happens when unroll=True. Is this expected?

**Comment by ravikyram** [comment] 2019-12-09 06:17
I have tried on colab with TF version 2.0,2.1.0-dev20191203 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/d3b253675ac7770576cfeeaecb36646e/untitled449.ipynb). Thanks!

**Comment by qlzh727** [comment] 2020-01-07 03:56
Thanks for reporting the issue.

I think the performance dip is caused by the tf.function tracing when the function is invoked first time. During the tracing, tf.function will try to exam all the ops and variables, and create graph for execution. This process will take some time, but its a one time cost to pay, which means all the follow up invocations of the function will be very fast.

You could try time the go() with tf.function multiple times, and from the experiment I did, the follow up runs takes 0.05 sec. This aligns with our suggested usage for tf function, that user will feed different data tensor to the function, but we only need to create the graph once.

On a side note, we are spending effort to improve the eager performance, both for tracing and execution. You could expect some speedups in the 2.x releases.

I am closing this bug as working as intended, feel free to reopen it if you feel otherwise. Thanks.

**Closed by qlzh727** 2020-01-07 03:56 UTC
Labels: TF 2.0, comp:autograph, comp:keras, stat:awaiting tensorflower, type:performance
