### ISSUE TITLE
Dockerfile should assign LANG=C_ALL

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#20380] opened 2018-06-28 16:54 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:official Dockerfile
- **TensorFlow version (use command below)**:1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:from Docker
- **GCC/Compiler version (if compiling from source)**:from Docker
- **CUDA/cuDNN version**:not relevant
- **GPU model and memory**:not relevant
- **Exact command to reproduce**:see link

### Describe the problem

Python 3 has a serious issue on LANG=C environment as described in [Python Issue 19846](https://bugs.python.org/issue19846).
In fact, official python or Anaconda Dockerfile assigned LANG=C.UTF-8 like [Dockerfile](https://github.com/docker-library/python/blob/a652f35d6ce77f02ca268d67f39e7dfa24cf08c5/3.5/jessie/Dockerfile)

Can this be fixed in future releases?
Thank you so much.

**Comment by tensorflowbutler** [comment] 2018-06-29 00:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-07-18 19:05
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by angersson** [comment] 2018-08-01 21:51
Marking as contributions welcome -- this should be very easy to add.

Also, I've recently proposed a change to TensorFlow that obsoletes parameterized_docker_build.sh, which may help alleviate this issue (since the current Dockerfiles are very confusing). If anyone following this thread is interested in making TensorFlow's Dockerfile story better for everyone, [please take a look at the RFC](https://github.com/tensorflow/community/pull/8).

**Comment by tensorflowbutler** [comment] 2018-08-16 20:04
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by yongtang** [comment] 2018-08-25 19:33
Added a PR #21877 for the fix.

**Comment by tensorflowbutler** [comment] 2018-09-09 18:36
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-09-24 12:47
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-09 18:43
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-24 12:40
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Closed** 2018-10-25 00:11 UTC
Labels: stat:contributions welcome, type:feature
