### ISSUE TITLE
--config=rocm build works with bazel `0.26.1` but has link errors with `0.29.1`

### ISSUE THREAD

**Issue by deven-amd** [tensorflow/tensorflow#34082] opened 2019-11-07 21:38 UTC
We are trying to figure out why the `--config=rocm` TF build breaks (link errors) with bazel version `0.29.1`, but works fine with `0.26.1`.

How do we get a better understanding of what changed on the bazel side, to introduce the build errors, and how to fix them?

thanks

-------------------

/cc @whchung @parallelo @sunway513

**Comment by gunan** [comment] 2019-11-07 23:26
@dslomov @scentini @lazslocsomor
Who helped us move to bazel 1.0
Is there a changelog for bazel we can point people to?
I think there are some github issue labels bazel uses, but not sure how to find them.

**Comment by laszlocsomor** [comment] 2019-11-08 10:03
@gunan: See @scentini's list: https://github.com/tensorflow/tensorflow/pull/33415#issuecomment-551175252

**Comment by scentini** [comment] 2019-11-08 12:02
I think the `--config=rocm` issues come from a different incompatible change:
[`--incompatible_do_not_split_linking_cmdline`](https://github.com/bazelbuild/bazel/issues/7687)
I believe @meteorcloudy is working on fixing this.

**Comment by meteorcloudy** [comment] 2019-11-11 09:20
Yes, this issue has been resolved by https://github.com/tensorflow/tensorflow/commit/72d0facc37e377d89d8034bb825bf0e93a4f810d

**Comment by deven-amd** [comment] 2019-11-11 15:34
@meteorcloudy yes and no.

The compile issues are resolved by the commit you referenced, but the same commit also introduces a bunch of runtime failures (symbol not found errors from HIP runtime, when attempting to launch GPU kernels). I have filed a PR (https://github.com/tensorflow/tensorflow/pull/34081)  to revert that commit, so that we can get the ROCm CSB back to a known passing state.

Can I request you, to describe 
* what changed within bazel that causes the link-time failures.
* what was done in the commit (that you reference above) to fix those link-time failures.

If we have a better understanding of that, it would help us also figure out why that commit leads to the runtime errors that we see.

Thanks

deven

**Comment by meteorcloudy** [comment] 2019-11-11 16:25
@deven-amd 
Oh, sorry for that. Apparently we didn't run tests on TensorFlow CI for ROCm build, that's why the runtime failure was not caught.

The original build error was caused by https://github.com/bazelbuild/bazel/issues/7687. This incompatible change is in 0.29.1, and it caused the order of the linking flags to change. The compiler is sensitive to the flag order, which leads to the problem.

[72d0fac](https://github.com/tensorflow/tensorflow/commit/72d0facc37e377d89d8034bb825bf0e93a4f810d ) does two things:

- Removed unused toolchain definitions for Mac and Windows. The ROCm toolchain derives from the GPU toolchain, but IIUC ROCm is Linux only. This could make it easier to maintain.
- To fix the order issue, I added all missing features to the toolchain definition so that Bazel won't patch the toolchain and messes up the flag order. This was based on Bazel's unix_cc_toolchain_config.bzl. This fixed the order but probably introduced some change in the linking flags.

Can you tell me what exactly the error message looks like?

**Comment by deven-amd** [comment] 2019-11-11 18:08
here is one example of the runtime error we see

```
terminate called after throwing an instance of 'std::runtime_error'                                                                                                                                                                                                
  what():  Missing metadata for __global__ function: _ZN5Eigen8internal15EigenMetaKernelINS_15TensorEvaluatorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIfLi1ELi1EiEELi16ENS_11MakePointerEEEKNS_18TensorCwiseUnaryOpINS0_12scalar_rightIffNS0_17scalar_product\
_opIffEELb0EEEKNS4_INS5_IKfLi1ELi1EiEELi16ES7_EEEEEENS_9GpuDeviceEEEiEEvT_T0_                                                                                                                                                                                      
Fatal Python error: Aborted      
```

**Comment by deven-amd** [comment] 2019-11-11 19:26
is there a way to modify the https://github.com/tensorflow/tensorflow/commit/72d0facc37e377d89d8034bb825bf0e93a4f810d commit to not use the gold linker?

**Comment by deven-amd** [comment] 2019-11-11 19:46
think I may have found the cause...
this line ( https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/BUILD.rocm.tpl#L93) ?

My guess is that specifying the the `-Wl--gc-sections` option somehow makes the linker discard some of the information related to the gpu kernel binary blobs resulting in the runtime error.

removing this option makes one of the previously failing tests, pass. 
trying this out now on all the failing tests...will post the result here when done

**Comment by deven-amd** [comment] 2019-11-11 22:05
@meteorcloudy 

all of the runtime failures we were observing in the ROCm CSB tests go away when I remove the `-Wl,--gc-sections` from the link options. 

I will file a PR shortly to have this change upstreamed. 

We can close out this issue, if you feel this is an acceptable solution.

**Comment by deven-amd** [comment] 2019-11-11 22:16
Filed https://github.com/tensorflow/tensorflow/pull/34177

**Comment by meteorcloudy** [comment] 2019-11-12 09:30
@deven-amd That's great! Thanks for fixing this, I'll help you import #34177 and look into enabling some tests for ROCm build to prevent regression like this.

**Closed** 2019-11-12 10:05 UTC
