### ISSUE TITLE
InternalError: Blas GEMM launch failed 

### ISSUE THREAD

**Issue by paolof89** [tensorflow/tensorflow#11812] opened 2017-07-27 10:07 UTC
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
- **TensorFlow installed from (source or binary)**:
pip3 install tensorflow-gpu

- **TensorFlow version (use command below)**:
v1.2.0-5-g435cdfc 1.2.1

- **Python version**: 
3.5

- **CUDA/cuDNN version**:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

- **GPU model and memory**:
 description: 3D controller
          product: GK210GL [Tesla K80]
          vendor: NVIDIA Corporation
          physical id: 0
          bus info: pci@99ba:00:00.0
          version: a1
          width: 64 bits
          clock: 33MHz
          capabilities: bus_master cap_list
          configuration: driver=nvidia latency=0
          resources: iomemory:100-ff iomemory:140-13f irq:24 memory:21000000-21ffffff 
          memory:1000000000-13ffffffff memory:1400000000-1401ffffff

- **Code example**:
estimator = KerasRegressor(build_fn=self.create_model_function,
                                   input_dim=self.input_dim, output_dim=self.output_dim,
                                   **self.model_parameters)

param_grid = {'epochs': [5]
              ,'batch_size': [256]
              ,'neurons': [[10, 10, 10]]
              ,'dropout': [[0.0, 0.0]]}

grid = GridSearchCV(estimator=estimator, param_grid=param_grid, n_jobs=-1)

### Describe the problem
The InternalError occurred when I fit a sklearn.GridSearchCV object.
The error occurred only if I use GPU and I I use GridSearch object. It works fine on CPU and on single model fitting (using Keras wrapper).

### Error log
File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/model_selection/_search.py", line 564, in _fit
    for parameters in parameter_iterable
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 728, in __call__
    n_jobs = self._initialize_backend()
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 540, in _initialize_backend
    **self._backend_args)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 311, in configure
    self._pool = MemmapingPool(n_jobs, **backend_args)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 600, in __init__
    super(MemmapingPool, self).__init__(**poolargs)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/pool.py", line 420, in __init__
    super(PicklingPool, self).__init__(**poolargs)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 344, in __call__
    return self.func(*args, **kwargs)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/sklearn/model_selection/_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/keras/wrappers/scikit_learn.py", line 136, in fit
    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))
  File "/home/aateam/Amplifon/amplifon-adv-planning/src/libs/amplifon_objects.py", line 176, in create_test_model
    model.add(Dense(neurons[0], input_dim=input_dim, activation=last_activation))
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/keras/models.py", line 436, in add
    layer(x)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/keras/layers/core.py", line 838, in call
    output = K.dot(inputs, self.kernel)
  File "/home/aateam/.conda/envs/amplifon-dev3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 978, in dot
    out = tf.matmul(x, y)
  File "/home/aateam/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/aateam/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/aateam/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aateam/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aateam/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(256, 32), b.shape=(32, 10), m=256, n=10, k=32
         [[Node: dense_1/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_dense_1_input_0_0/_15, dense_1/kernel/read)]]
         [[Node: mul_1/_43 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_795_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by reedwm** [comment] 2017-07-27 17:22
Make sure you have no other processes using the GPU running. Run `nvidia-smi` to check this.

**Comment by paolof89** [comment] 2017-07-28 14:03
I runned the `nvidia-smi` command while just before the crash. Here the output:
`Fri Jul 28 14:01:37 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | BD8C:00:00.0     Off |                    0 |
| N/A   46C    P0    54W / 149W |  11439MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      6216    C   python                                       10888MiB |
|    0      6217    C   python                                         383MiB |
|    0      6218    C   python                                         163MiB |
+-----------------------------------------------------------------------------+
`

The GridSeachCV function creates 3 parallel jobs, is it correct?

**Comment by reedwm** [comment] 2017-07-28 16:33
If multiple TensorFlow processes are used, either [`per_process_gpu_memory_fraction`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L21) or [`allow_growth`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L40) should be passed to the TensorFlow Session in a `ConfigProto` to prevent one process from using all the GPU memory. Preferably, multiple TensorFlow processes wouldn't be used at the same time.

@fchollet I don't know Keras or sklearn, so I'm not sure how to do this with KerasRegressor. Do you know how to resolve this problem?

**Comment by fnozarian** [comment] 2017-11-06 16:52
I have the same problem when I use KerasClassifier and GridSearchCV for tuning the parameters.

**System information**

- OS: Linux 4.13.3-1-ARCH
- TensorFlow: 1.3.0
- Scikit-learn: 0.19.0
- Keras: 2.0.8
- Python: 3.6.2
- GPU: GeForce GTX 1080 Ti
- CUDA/cuDNN: release 8.0, V8.0.61

**Code example**

`model = KerasClassifier(build_fn=create_model, verbose=0, epochs=20, batch_size=1)`
`optimizer = ['SGD', 'Adagrad', 'Adam']`
`param_grid = dict(optimizer=optimizer)`
`grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)`

**Comment by fchollet** [comment] 2017-11-06 18:47
It looks like `GridSearchCV` uses `joblib`. If it attempts to pickle a Keras model (and thus a TF graph) for use in different processes, then that is potentially not going to be possible safely (@reedwm may be able to say more).

> If multiple TensorFlow processes are used, either per_process_gpu_memory_fraction or allow_growth should be passed to the TensorFlow Session in a ConfigProto to prevent one process from using all the GPU memory. Preferably, multiple TensorFlow processes wouldn't be used at the same time.

It is possible to do this in Keras by creating your own session (with `per_process_gpu_memory_fraction` configured), then setting this session as the Keras session via `keras.backend.set_session(sess)`. Do this before creating your Keras model.

**Comment by reedwm** [comment] 2017-11-06 19:23
> If it attempts to pickle a Keras model (and thus a TF graph) for use in different processes, then that is potentially not going to be possible safely (@reedwm may be able to say more).

I'm not sure what you mean here. According to [this page](https://pythonhosted.org/joblib/parallel.html), `joblib` uses `fork()`, which, according to #5448, does not work well with TensorFlow.

**Comment by reedwm** [comment] 2017-12-07 02:23
@rosecatherinek I am not sure what CodaLab is or how it works, but I doubt it's `fork()`ing the TensorFlow so this seems like a different issue. 

From the logs, I see the line
```
failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
```

This seems to indicate TensorFlow cannot initialize cuBLAS within the codalab docker container. Maybe try asking for support from the codalab authors? This is difficult to debug for us since we do not use codalab.

@zheng-xq, @yzhwang, any ideas what the issue could be?

**Comment by rosecatherinek** [comment] 2017-12-10 19:51
Thanks for pointing that out, @reedwm ! We hadn't noticed that at first. We are trying to fix that now. Thanks again!

**Comment by snjt** [comment] 2017-12-20 19:25
has anyone had any luck with this? I also get the error.
Same platform as paolof89. 
CPU works fine.

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(1, 135), b.shape=(135, 512), m=1, n=512, k=135
	 [[Node: stacked_cell_1/rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/lstm_cell/lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](stacked_cell_1/rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/lstm_cell/lstm_cell/concat, stacked_cell_1/rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/lstm_cell/lstm_cell/MatMul/Enter)]]
	 [[Node: Mean/_119 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3495_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by jidhu-mohan** [comment] 2018-01-04 07:27
Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel. 
Run the code again.. This time it should work.

**Comment by snjt** [comment] 2018-01-04 16:37
@jidhu-mohan I only have a single python process running when I get this error

**Comment by kuntoro-adi** [comment] 2018-01-12 04:24
Hi, 
I experienced the same error when executing the code in tutorial [tf.estimator](https://www.tensorflow.org/get_started/get_started)

Here's the error message

`
$ python tfestimator.py
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\<username>\AppData\Local\Temp\tmpdlwf3cjk
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Blas GEMV launch failed:  m=1, n=4
         [[Node: linear/linear_model/x/weighted_sum = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](linear/linear_model/x/Reshape, linear/linear_model/x/weights)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tfestimator.py", line 29, in <module>
    estimator.train(input_fn=input_fn, steps=1000)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 686, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMV launch failed:  m=1, n=4
         [[Node: linear/linear_model/x/weighted_sum = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](linear/linear_model/x/Reshape, linear/linear_model/x/weights)]]

Caused by op 'linear/linear_model/x/weighted_sum', defined at:
  File "tfestimator.py", line 29, in <module>
    estimator.train(input_fn=input_fn, steps=1000)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 630, in _train_model
    model_fn_lib.ModeKeys.TRAIN)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 316, in _model_fn
    config=config)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\estimator\canned\linear.py", line 89, in _linear_model_fn
    units=head.logits_dimension)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 321, in linear_model
    column, builder, units, weight_collections, trainable))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 1376, in _create_dense_column_weighted_sum
    return math_ops.matmul(tensor, weight, name='weighted_sum')
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1844, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1289, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMV launch failed:  m=1, n=4
         [[Node: linear/linear_model/x/weighted_sum = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](linear/linear_model/x/Reshape, linear/linear_model/x/weights)]]

2018-01-12 11:12:13.512132: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 11:12:13.512150: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 11:12:13.993976: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.2415
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2018-01-12 11:12:13.993992: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2018-01-12 11:12:13.993996: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2018-01-12 11:12:13.994018: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)
2018-01-12 11:12:17.243570: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_blas.cc:366] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-01-12 11:12:17.243585: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\stream.cc:1756] attempting to perform BLAS operation using StreamExecutor without BLAS support
`

My apology, should I write a new issue?
Thank you

**Comment by tensorflowbutler** [comment] 2018-01-23 23:18
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by JaneTakanashi** [comment] 2018-01-28 06:12
use nvidia-smi to see if gpu is overload, and use 'kill -9 pid' to kill the process.

**Comment by drpngx** [comment] 2018-02-03 01:32
To be clear, tensorflow will try (by default) to consume all available GPUs. It cannot be run with other programs also active. Closing. Feel free to reopen if this is actually another problem.

**Closed by drpngx** 2018-02-03 01:32 UTC

**Comment by JohnTailor** [comment] 2018-08-17 14:56
I ported from pytorch to tensorflow and had an "import torch" . No idea how that caused the crash, but it did.

**Comment by drpngx** [comment] 2018-08-17 16:17
It's possible that torch is reserving memory up front. Good to know.

**Comment by kaushal1989** [comment] 2018-12-05 07:09
In my case, removing `n_jobs=-1` worked

**Comment by vaibhavsingh007** [comment] 2018-12-10 15:51
> Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel.
> Run the code again.. This time it should work.

This worked for me. If you're using Jupyter, try shutting the kernel (server) down and restarting it.

**Comment by timoveldt** [comment] 2019-01-04 14:42
> Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel.
> Run the code again.. This time it should work.

This worked for me. I was running multiple python consoles in PyCharm and making sure there is just one seems to help.

**Comment by Crispy13** [comment] 2019-01-30 22:52
> In my case, removing `n_jobs=-1` worked.

It worked for me. Thank you!

**Comment by chouex** [comment] 2019-02-06 10:24
I got "Blas GEMM launch failed" while the virtualbox(genymotion) vm is running.

**Comment by jansenicus** [comment] 2019-03-10 08:44
> 
> 
> Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel.
> Run the code again.. This time it should work.

Closing (shutting down) all other notebooks and restarting the current notebook resolved the issue.

**Comment by chg0901** [comment] 2019-05-27 00:29
Since the GPU memory is not enough. So here is one of the solution.
```
import keras.backend.tensorflow_backend as KTF
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth=True   
sess = tf.Session(config=config)

KTF.set_session(sess)
```

**Comment by NathanBWaters** [comment] 2019-08-15 16:32
I restarted my Windows machine and it fixed the problem.

**Comment by germanjke** [comment] 2019-11-08 10:51
this is happening to me on my windovs while i'm usuing tf
so problem is really multi kernels with Jupyter
shutdown all of your JupyterNotebooks and restart the kernell

**Comment by GarryLau** [comment] 2020-01-12 08:42
> Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel.
> Run the code again.. This time it should work.

That's it! 
When I used jupyter notebook, meanwhile I used terminal to run the same code, the error above occured.

**Comment by harisushehu** [comment] 2020-02-03 22:54
Adding this on top of your code works for me in tensoflow version 2.0.0

import tensorflow as tf
import keras.backend.tensorflow_backend as KTF

os.environ["CUDA_VISIBLE_DEVICES"] = "0"
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth=True   
session = tf.compat.v1.Session(config=config)

KTF.set_session(session)

**Comment by mcawai** [comment] 2020-03-16 01:29
Working for me on tf 2.1.0 (ref: https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth)

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)

**Comment by kaibrach** [comment] 2020-04-22 17:51
This working for me:
```
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = '0' # Set to -1 if CPU should be used CPU = -1 , GPU = 0

gpus = tf.config.experimental.list_physical_devices('GPU')
cpus = tf.config.experimental.list_physical_devices('CPU')

if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
elif cpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        logical_cpus= tf.config.experimental.list_logical_devices('CPU')
        print(len(cpus), "Physical CPU,", len(logical_cpus), "Logical CPU")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
```

**Comment by crwgregory** [comment] 2020-07-12 22:25
Restarting my docker container did the trick for me:
```
docker run -d --gpus all -p 8888:8888 tensorflow/tensorflow:latest-gpu-py3-jupyter
f4f5fac66b05
docker restart f4f
```

**Comment by vikram0691** [comment] 2021-02-07 15:07
Reinstall the compatible **NVIDIA** driver.

> In the ubuntu _Software centre_ change the driver in **Additional Drivers** panel.

**Comment by wang273257881** [comment] 2024-11-14 09:16
Initially, I used tensorflow-gpu==1.14.0, which triggered this error, but it ran normally on the CPU.
I tried some methods that were mentioned before, such as **per_process_gpu_memory_fraction** , **allow_growth**  and **set_memory_growth**, but it does not works.
After that, I tried using tensorflow==2.6.0, and after making some slight changes to the code to get it running properly, TensorFlow presented a new error: 
`Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this) failed with error 'CUPTI could not be loaded or symbol could not be found.'`
After referring to [it](https://github.com/tensorflow/tensorflow/issues/50273) and resolving this new error, my code was able to run on the GPU.
