### ISSUE TITLE
tf_debug incompatibility with importlib (Python 3.6)

### ISSUE THREAD

**Issue by Sciguymjm** [tensorflow/tensorflow#18332] opened 2018-04-08 19:44 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: Python 3.6
- **Exact command to reproduce**:
- Bazel version: N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

### Describe the problem
When using tf_debug with a class that is dynamically imported using `importlib`, Tensorflow throws an exception since it is unable to determine if the dynamically imported library is either a compiled/uncompiled python file. This is due to how importlib handles imports, as a class imported using that library does not have a proper `file_path`, as seen in [this function](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/lib/source_utils.py#L42) (Line 42 of `source_utils.py`). I believe it does this because it is trying to find the lines of the file which the traceback mentions, but is unable to find them.

### Source code / logs
```
229 ops no flops stats due to incomplete shapes.
Traceback (most recent call last):
  File "C:\Users\Matt\PycharmProjects\Saltie\bot_code\models\base_model.py", line 308, in _initialize_variables
    self.sess.run(init, run_metadata=run_metadata)
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\wrappers\grpc_wrapper.py", line 225, in run
    self._sent_graph_version)
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\wrappers\grpc_wrapper.py", line 61, in publish_traceback
    send_source=True)
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\lib\source_remote.py", line 192, in send_graph_tracebacks
    graph=graph, send_source=send_source)
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\lib\source_remote.py", line 154, in _send_call_tracebacks
    call_traceback.graph_traceback.id_to_string))
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\lib\source_remote.py", line 94, in <genexpr>
    if not source_utils.guess_is_tensorflow_py_library(f) and gfile.Exists(f))
  File "C:\Users\Matt\PycharmProjects\venvs\Saltie-3.6\lib\site-packages\tensorflow\python\debug\lib\source_utils.py", line 76, in guess_is_tensorflow_py_library
    "Input file path (%s) is not a Python source file." % py_file_path)
ValueError: Input file path (<frozen importlib._bootstrap>) is not a Python source file.
```

**Comment by tensorflowbutler** [comment] 2018-04-09 06:32
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by tensorflowbutler** [comment] 2018-04-24 18:41
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Sciguymjm** [comment] 2018-04-30 17:02
Yes

**Comment by Sciguymjm** [comment] 2018-05-01 15:17
@asimshankar Will do.

**Comment by asimshankar** [comment] 2018-05-17 02:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

(@Sciguymjm : If you have a reproducible example, please do let us know by updating this thread and I'll re-open it and welcome contributions. Thanks)

**Closed by asimshankar** 2018-05-17 02:45 UTC

**Comment by johndpope** [comment] 2018-07-07 15:47
https://gist.github.com/johndpope/976c00fd6f4b70ab56368e6d32ef1eda

uncomment 
 sess = tf_debug.TensorBoardDebugWrapperSession(sess, 'localhost:6064')
to trigger error - 

pip freeze
absl-py==0.2.2
appnope==0.1.0
asn1crypto==0.24.0
astor==0.6.2
backcall==0.1.0
bleach==1.5.0
bokeh==0.13.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
cycler==0.10.0
cymem==1.31.2
Cython==0.28.3
cytoolz==0.8.2
decorator==4.3.0
dill==0.2.8.2
entrypoints==0.2.3
ftfy==4.4.3
gast==0.2.0
graphviz==0.8.4
grpcio==1.12.1
h5py==2.8.0
html5lib==0.9999999
idna==2.7
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
msgpack-numpy==0.4.1
msgpack-python==0.4.8
murmurhash==0.28.0
nbconvert==5.3.1
nbformat==4.4.0
nltk==3.3
notebook==5.5.0
numpy==1.14.5
opencv-python==3.4.1.15
packaging==17.1
pandas==0.23.1
pandocfilters==1.4.2
parso==0.2.1
pathlib==1.0.1
pexpect==4.6.0
pickleshare==0.7.4
Pillow==5.2.0
plac==0.9.6
preshed==1.0.0
prompt-toolkit==1.0.15
protobuf==3.5.2
ptyprocess==0.6.0
pyarrow==0.9.0.post1
pycparser==2.18
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
regex==2017.11.9
requests==2.19.1
scikit-learn==0.19.1
scipy==1.1.0
Send2Trash==1.5.0
simplegeneric==0.8.1
SimpleITK==1.1.0
six==1.11.0
spacy==2.0.11
tabulate==0.8.2
tensorboard==1.8.0
tensorflow==1.8.0
tensorpack==0.8.6
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
tflearn==0.3.2
thinc==6.10.2
toolz==0.9.0
tornado==5.0.2
tqdm==4.23.4
traitlets==4.3.2
ujson==1.35
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wget==3.2
widgetsnbextension==3.2.1
wrapt==1.10.11

**Comment by ea42gh** [comment] 2019-02-07 16:21
Just encountered this same issue. Any known workarounds?

**Comment by ea42gh** [comment] 2019-02-07 16:22
And how does adding a comment "unassign asimshankar"?????

**Comment by chintler** [comment] 2019-10-25 11:47
I have implemented a workaround for this issue. What happens is in the execution stack, that is found in the variable **non_tf_files** in the **_source_file_paths_outside_tensorflow_py_library** , depending on your environment, you have <frozen importlib._bootstrap>. 

This causes the **guess_is_tensorflow_py_library** method to raise a ValueError. The workaround is to edit your /dist-packages/tensorflow/python/debug/lib/source_remote.py with the following change

Replace

    non_tf_files = (id_to_string[file_id] for file_id in file_ids)

With

    non_tf_files = (id_to_string[file_id] for file_id in file_ids)
    non_tf_files = [x for x in non_tf_files if '<' not in x]

This simply removes the <frozen importlib._bootstrap> from the stacktrace that tensorflow checks for.

**Comment by jxa124** [comment] 2020-05-15 11:54
> non_tf_files = [x for x in non_tf_files if '<' not in x]

thanks, that suits for me
