### ISSUE TITLE
toco_from_protos: not found - breaking

### ISSUE THREAD

**Issue by igorhoogerwoord** [tensorflow/tensorflow#34698] opened 2019-11-29 04:16 UTC
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18 LTS
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
Python version: 3.6

**Command used to run the converter or code if you’re using the Python API**
```
    # Read the saved model from disk. Assumes it is downloaded.
    converter = tf.lite.TFLiteConverter.from_saved_model(model_out)
    lite_model = converter.convert()

    # Format model file paths to store the file in the right directory:
    lite_name = model_name + '.tflite'
    out_path = model_out + '/' + lite_name

    # Write the converted model to disk:
    open(out_path, "wb").write(lite_model)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/[]/[]/[]/v1/[]/models/main.py", line 124, in convert_lite
    lite_model = converter.convert()
  File "/home/[]/env/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 446, in convert
    **converter_kwargs)
  File "/home/[]/env/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/[]/env/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
/bin/sh: 1: toco_from_protos: not found
```

This happens, even after adding my python bin from the virtualenv to my $PATH variable.

It seems that the path to toco is hardcoded and therefore Tensorflow will never look for it anywhere else?

It's now not possible to use the converter in a Python virtualenv ( the recommended way to use Tensorflow )

Note that when activating the virtualenv from the commandline, the toco and toco_from_protos commands do work. It is only when running the Python program with Tensorflow that Tensorflow is not able to find toco_from_protos.

**Comment by haozha111** [comment] 2019-12-03 22:14
Assigning this to gargn@ who is more familiar with the context.

**Comment by gargn** [comment] 2019-12-04 16:59
If you installed using `--user` instead of `sudo pip install`, then  you do not have any console commands in your path. You probably need to do `export PATH=$PATH:~/.local/bin` before running the converter. This is a pip oddity, not really a bug of our converter.

Reassigning to @aselle who has more knowledge about this.

**Comment by igorhoogerwoord** [comment] 2019-12-05 02:14
Installed using ```python -m pip install```, without the ```--user``` flag.
All the required python packages are contained in the virtual env.

The virtual environment bin is in the ```PATH``` variable, and the toco as well as toco_from_protos packages are present in this bin directory. ( They are available when called directly from the command line ).

The recommend way to install Tensorflow is in a virtualenv, as well as specifically with Python 3.6.

**Comment by aselle** [comment] 2019-12-10 00:17
How are you adding it to your path?

**Comment by aselle** [comment] 2019-12-11 21:10
I could not reproduce this. On linux you shouldn't have to manipulate your path and virtualenv should work.
```
virtualenv -p python3 ~/py3-for-repro
source ~/py3-for-repro/bin/activate
pip install --upgrade tensorflow==2.0.0
cat > repro_test.py <<EOF;
import tensorflow as tf

@tf.function(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.float32)])
def simple(x):
  return tf.add(x,x)
converter = tf.lite.TFLiteConverter.from_concrete_functions([simple.get_concrete_function()])
converter.convert()
EOF
python repro_test.py
```
The only guesses I have without more info is you are not sourcing the virtualenv script?

**Comment by igorhoogerwoord** [comment] 2019-12-19 04:00
The ```virtualenv/bin/``` is added to the PATH variable in the row with other binary directories, in the .profile file, on the same linux user account which I also use to run the python program. 

Does this clear up how it is added to the path?

The rest of Tensorflow works successfully, it would not work if I was not sourcing my virtualenv script because Tensorflow is only installed in the virtual environment.

For added info: I use ```python -m pip install``` and not the system installed pip to prevent conflicts between system level pip and the python packages in the virtual environment.

Is there any more specific information that would help?

**Comment by cap0** [comment] 2020-01-17 09:41
I'm facing the same issue. Using TensorFlow 2.1 and virtual environments, adding the virtual env to PATH env solves the issue but this is not very handy and seems to broke then environment isolation. The toco_from_protos should be taken from the bin of the environment without the need to specify in the PATH

**Comment by jtanios** [comment] 2020-02-16 02:46
I'm having the same issue with `tensorflow-gpu==2.1.0`

**Comment by Ni-ko-laj** [comment] 2020-06-26 12:11
> I'm having the same issue with `tensorflow-gpu==2.1.0`
> 
> As a workaround, before converting to tf lite, I'm adding the virtualenv's bin path to the environment's `PATH`
> 
> ```python
>     bin_path = dirname(sys.executable)
> 
>     if 'PATH' in os.environ:
>         os.environ['PATH'] += ':' + bin_path
>     else:
>         os.environ['PATH'] = bin_path
> ```

That also didn't work for me. I'm using visual studio in combination with python 3.8.
The only thing that seemed to work was copying the file to the solutions folders.

**Comment by eRaul** [comment] 2020-07-16 08:06
I`m facing the issue. My system is macos catalina, tensorflow==1.13.1, 1.14.0 also has been tried. Add the path of toco_from_protos can solve the issue. But if pip install tensorflow will not put the bin to right path, so should the TFLiteConverter call it like this?

**Comment by sushreebarsa** [comment] 2021-08-25 08:09
@igorhoogerwoord We see that you are using older version of tensorflow .Many bug have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!

**Closed** 2021-09-08 09:42 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.0
