### ISSUE TITLE
tf.dynamic_partition may cause NaN loss when use it with multi gpus and it performs normally with single gpu

### ISSUE THREAD

**Issue by mzhaoshuai** [tensorflow/tensorflow#23918] opened 2018-11-22 07:49 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **_no_**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _**Ubuntu 16.04.5 LTS**_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**_no_**
- TensorFlow installed from (source or binary):**_binary_**
- TensorFlow version (use command below):**_1.12.0_**
- Python version: **_Python 3.5.2_**
- Bazel version (if compiling from source): _**None**_
- GCC/Compiler version (if compiling from source):  **_5.4.0_**
- CUDA/cuDNN version: **_cuda-9.0.176/cudnn-7.2.1_**
- GPU model and memory: **_2 same GTX Titan X (Pascal), 12GB_** 

I just use the offical docker image of the tensorflow, the tag is `1.12.0-devel-gpu-py3`

**Describe the problem**

**The api `tf.dynamic_partition` may cause NaN loss when use it with multi gpus and it is normal with single gpu.**

The code to reproduce the problem:
```
#coding=utf-8

import os
import time
import tensorflow as tf

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"  
os.environ["CUDA_VISIBLE_DEVICES"]="0"
num_gpus = len(os.environ["CUDA_VISIBLE_DEVICES"].split(','))

def dp_and_bm_api_test(argv=None):
	a = tf.constant([[1, 2, 3],
					[4, 5, 6],
					[7, 8, 9],
					[10, 11, 12]])
	
	mask = tf.constant([1, 0, 1, 0])
	res_01 = tf.boolean_mask(a, mask)
	res_02 = tf.dynamic_partition(a, mask, num_partitions=2)[1]

	with tf.Session() as sess:
		r_1, r_2 = sess.run([res_01, res_02])
		print("r_1\n", r_1)
		print("r_2\n", r_2)


def tower_model_fn(features, labels, api_sel=0):
	"""a test tower fn"""
	num_classes = 10
	net = tf.layers.conv2d(features, num_classes * 2, [3,3], padding="same")
	net = tf.layers.batch_normalization(net)
	net = tf.nn.relu(net)
	net = tf.layers.conv2d(net, num_classes, [3,3], padding="same")
	net = tf.layers.batch_normalization(net)
	logits = tf.nn.relu(net)

	labels = tf.squeeze(labels, axis=3)  # reduce the channel dimension.
	logits_by_num_classes = tf.reshape(logits, [-1, num_classes])
	labels_flat = tf.reshape(labels, [-1, ])
	valid_indices = tf.to_int32(labels_flat <= num_classes - 1)

	if api_sel == 0:
		valid_logits = tf.boolean_mask(logits_by_num_classes, valid_indices)
		valid_labels = tf.boolean_mask(labels_flat, valid_indices)
	else:
		valid_logits = tf.dynamic_partition(logits_by_num_classes, valid_indices, num_partitions=2)[1]
		valid_labels = tf.dynamic_partition(labels_flat, valid_indices, num_partitions=2)[1]


	cross_entropy = tf.losses.sparse_softmax_cross_entropy(logits=valid_logits, labels=valid_labels, 
							loss_collection=None)
	tf.add_to_collection(tf.GraphKeys.LOSSES, cross_entropy)
	return None

def train(api_sel=0):
	## variable strategy
	variable_strategy = 'CPU'
	input_device = '/cpu:0'
	#var_device = '/gpu:0'
	var_device = '/cpu:0'
	num_devices = num_gpus
	device_type = 'gpu'
	
	with tf.Graph().as_default() as graph:
		with tf.device(var_device):
			## some collector
			tower_ce_loss = []

			global_step = tf.train.get_or_create_global_step()	

			name_scopes = ['tower_%d' % i for i in range(num_devices)]
			for i in range(num_devices):
				with tf.variable_scope(tf.get_variable_scope(), reuse=bool(i > 0)):
					worker_device = '/{0}:{1}'.format(device_type, i)
					with tf.name_scope(name_scopes[i]) as name_scope:
						with tf.device(worker_device):	

							images = tf.ones([8, 321, 321, 3])
							labels = tf.zeros([8, 321, 321, 1], dtype=tf.int32)
							tower_model_fn(images, labels, api_sel=api_sel)
							ce_now = tf.get_collection(tf.GraphKeys.LOSSES, scope=name_scope)
							tower_ce_loss.append(tf.add_n(ce_now))

		
		with tf.device(var_device):
			update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS, name_scopes[0])	

			ce_loss = tf.add_n(tower_ce_loss)
			session_config = tf.ConfigProto(allow_soft_placement=True,
											log_device_placement=False
											)
			# Build an initialization operation to run below.
			init_op = tf.global_variables_initializer()
			max_steps = 30
			step_gap_init_time = 0.0
			with tf.Session(config=session_config) as sess:
				sess.run(init_op)
				for steps in range(1, max_steps + 1, 1):
					step_gap_init_time = time.time()
					c_l = sess.run([ce_loss])
					if steps % 10 == 0:
						gap_time = (time.time() - step_gap_init_time) / 10
						print("ce loss{0}, {1:1.4f}s per steps".format(c_l, gap_time))
	tf.keras.backend.clear_session()
	tf.reset_default_graph()

if __name__ == '__main__':
	tf.logging.set_verbosity(tf.logging.INFO)
	print("\nTest the two apis")
	dp_and_bm_api_test()
	print("The number of gpus is {0}".format(num_gpus))
	print("\nUsing tf.boolean_mask")
	train(api_sel=0)
	print("\nUsing tf.dynamic_partition")
	train(api_sel=1)
```

When I use two gpus, I set `os.environ["CUDA_VISIBLE_DEVICES"]="0, 1"`

```
2018-11-22 07:37:36.070340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2018-11-22 07:37:36.478438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-22 07:37:36.478486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1
2018-11-22 07:37:36.478498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y
2018-11-22 07:37:36.478511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N
2018-11-22 07:37:36.478930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11421 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:17:00.0, compute capability: 5.2)
2018-11-22 07:37:36.479432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11421 MB memory) -> physical GPU (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:18:00.0, compute capability: 5.2)
r_1
 [[1 2 3]
 [7 8 9]]
r_2
 [[1 2 3]
 [7 8 9]]
The number of gpus is 2

Using tf.boolean_mask

ce loss[5.088441], 0.0010s per steps
ce loss[5.088441], 0.0010s per steps
ce loss[5.088441], 0.0010s per steps


Using tf.dynamic_partition
ce loss[nan], 0.0010s per steps
ce loss[nan], 0.0011s per steps
ce loss[nan], 0.0011s per steps
```

When I use one gpus, I set `os.environ["CUDA_VISIBLE_DEVICES"]="0"`
Then I get
```

Test the two apis
2018-11-22 07:41:32.112369: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-11-22 07:41:34.385976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:17:00.0
totalMemory: 11.92GiB freeMemory: 11.80GiB
2018-11-22 07:41:34.386009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-22 07:41:34.586971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-22 07:41:34.587016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-22 07:41:34.587024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-22 07:41:34.587249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11421 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:17:00.0, compute capability: 5.2)
r_1
 [[1 2 3]
 [7 8 9]]
r_2
 [[1 2 3]
 [7 8 9]]
The number of gpus is 1


Using tf.boolean_mask

ce loss[2.3863728], 0.0009s per steps
ce loss[2.3863728], 0.0009s per steps
ce loss[2.3863728], 0.0009s per steps



Using tf.dynamic_partition
ce loss[2.1562214], 0.0010s per steps
ce loss[2.1562214], 0.0013s per steps
ce loss[2.1562214], 0.0010s per steps

```

I think the implementation of the  api `tf.dynamic_partition` is really terrible, 
I also reported that this api may cuase memory leak under certain situation
https://github.com/tensorflow/tensorflow/issues/22464

It also cost me lots of time to find that it is not suitable with mulit gpus.....
I think there may other potential issues about the  `tf.dynamic_partition`.
And I don't figure out why I still use it......

**Comment by mzhaoshuai** [comment] 2018-11-26 05:49
No anyone else meet this problem ?

**Comment by jlebar** [comment] 2018-11-26 22:20
Hi, does this have something to do with XLA?

**Comment by mzhaoshuai** [comment] 2018-11-27 03:07
@jlebar 

I am not familiar with XLA...
When I try it following https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_softmax_xla.py

I find another interesting phenomenon, the appearance of NaN loss when using `tf.dynamic_partition` is related to the magnitude of the data

Here is the code
```
#coding=utf-8

import os
import time
import tensorflow as tf
#from tensorflow.contrib.compiler import xla


os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"  
os.environ["CUDA_VISIBLE_DEVICES"]="0, 1"
num_gpus = len(os.environ["CUDA_VISIBLE_DEVICES"].split(','))


def tower_model_fn(features, labels, api_sel=1):
	"""a test tower fn"""
	num_classes = 10
	logits = tf.layers.dense(features, num_classes)

	logits_by_num_classes = tf.reshape(logits, [-1, num_classes])
	labels_flat = tf.reshape(tf.squeeze(labels), [-1, ])
	valid_indices = tf.to_int32(labels_flat <= num_classes - 1)

	if api_sel == 0:
		valid_logits = tf.boolean_mask(logits_by_num_classes, valid_indices)
		valid_labels = tf.boolean_mask(labels_flat, valid_indices)
	else:
		valid_logits = tf.dynamic_partition(logits_by_num_classes, valid_indices, num_partitions=2)[1]
		valid_labels = tf.dynamic_partition(labels_flat, valid_indices, num_partitions=2)[1]

	cross_entropy = tf.losses.sparse_softmax_cross_entropy(logits=valid_logits, labels=valid_labels, 
							loss_collection=None)
	tf.add_to_collection(tf.GraphKeys.LOSSES, cross_entropy)
	return None

def train(batch_size, api_sel=1):
	"""main"""
	## variable strategy
	variable_strategy = 'CPU'
	input_device = '/cpu:0'
	var_device = '/cpu:0'
	num_devices = num_gpus
	device_type = 'gpu'
	
	with tf.Graph().as_default() as graph:
		with tf.device(var_device):
			## some collector
			tower_ce_loss = []
			global_step = tf.train.get_or_create_global_step()	

			name_scopes = ['tower_%d' % i for i in range(num_devices)]
			for i in range(num_devices):
				with tf.variable_scope(tf.get_variable_scope(), reuse=bool(i > 0)):
					worker_device = '/{0}:{1}'.format(device_type, i)
					with tf.name_scope(name_scopes[i]) as name_scope:
						with tf.device(worker_device):	

							images = tf.ones([batch_size, 20])
							labels = tf.zeros([batch_size, 1], dtype=tf.int32)
							tower_model_fn(images, labels, api_sel=api_sel)
							ce_now = tf.get_collection(tf.GraphKeys.LOSSES, scope=name_scope)
							tower_ce_loss.append(tf.add_n(ce_now))


		with tf.device(var_device):
			update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS, name_scopes[0])	

			ce_loss = tf.add_n(tower_ce_loss)
			session_config = tf.ConfigProto(allow_soft_placement=True,
											log_device_placement=False
											)
			# Build an initialization operation to run below.
			init_op = tf.global_variables_initializer()
			max_steps = 30
			step_gap_init_time = 0.0
			with tf.Session(config=session_config) as sess:
				sess.run(init_op)
				for steps in range(1, max_steps + 1, 1):
					step_gap_init_time = time.time()
					c_l = sess.run([ce_loss])
					if steps % 10 == 0:
						gap_time = (time.time() - step_gap_init_time) / 10
						print("ce loss{0}, {1:1.4f}s per steps".format(c_l, gap_time))

if __name__ == '__main__':
	tf.logging.set_verbosity(tf.logging.INFO)
	
	for batch_size in [1000, 2000, 3000, 4000, 5000, 6000]:
		print("batch_size={0}".format(batch_size))
		print("The number of gpus is {0}".format(num_gpus))
		print("\nUsing tf.boolean_mask")
		train(batch_size, api_sel=0)
		print("\nUsing tf.dynamic_partition")
		train(batch_size, api_sel=1)
```

The output

```
batch_size=1000

The number of gpus is 2
Using tf.boolean_mask
ce loss[6.561516], 0.0003s per steps
ce loss[6.561516], 0.0005s per steps
ce loss[6.561516], 0.0004s per steps
Using tf.dynamic_partition
ce loss[8.170236], 0.0001s per steps
ce loss[8.170236], 0.0001s per steps
ce loss[8.103901], 0.0001s per steps


batch_size=2000
The number of gpus is 2
Using tf.boolean_mask
ce loss[3.8799157], 0.0003s per steps
ce loss[3.8799157], 0.0002s per steps
ce loss[3.8799157], 0.0001s per steps
Using tf.dynamic_partition
ce loss[5.843277], 0.0007s per steps
ce loss[5.843277], 0.0003s per steps
ce loss[5.843277], 0.0006s per steps

batch_size=3000
The number of gpus is 2
Using tf.boolean_mask
ce loss[5.877125], 0.0003s per steps
ce loss[5.877125], 0.0002s per steps
ce loss[5.877125], 0.0004s per steps
Using tf.dynamic_partition
ce loss[7.8206615], 0.0007s per steps
ce loss[7.82078], 0.0005s per steps
ce loss[6.755781], 0.0007s per steps

batch_size=4000
The number of gpus is 2
Using tf.boolean_mask
ce loss[7.826822], 0.0001s per steps
ce loss[7.826822], 0.0001s per steps
ce loss[7.826822], 0.0001s per steps
Using tf.dynamic_partition
ce loss[4.3592453], 0.0001s per steps
ce loss[4.3592453], 0.0001s per steps
ce loss[4.361978], 0.0001s per steps

batch_size=5000
The number of gpus is 2
Using tf.boolean_mask
ce loss[11.058659], 0.0003s per steps
ce loss[11.058659], 0.0005s per steps
ce loss[11.058659], 0.0004s per steps
Using tf.dynamic_partition
ce loss[nan], 0.0004s per steps
ce loss[nan], 0.0004s per steps
ce loss[nan], 0.0006s per steps


batch_size=6000
The number of gpus is 2
Using tf.boolean_mask
ce loss[6.5018396], 0.0001s per steps
ce loss[6.5018396], 0.0001s per steps
ce loss[6.5018396], 0.0001s per steps
Using tf.dynamic_partition
ce loss[nan], 0.0001s per steps
ce loss[nan], 0.0001s per steps
ce loss[nan], 0.0006s per steps

```

**Comment by mzhaoshuai** [comment] 2018-11-27 05:07
@jlebar 
I follow the tutorial:
https://www.tensorflow.org/xla/tutorials/xla_compile

I slightly modify the code and let the function `tower_model_fn` return the cross entropy loss
```
from tensorflow.contrib.compiler import xla

......

ce_now = xla.compile(tower_model_fn, inputs=[images, labels, api_sel])[0]
```

I try both `tf.boolean_mask` and `tf.dynamic_partition`, and I get info
```
2018-11-27 04:22:34.555284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2018-11-27 04:22:35.066707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-27 04:22:35.066779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1
2018-11-27 04:22:35.066794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y
2018-11-27 04:22:35.066805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N
2018-11-27 04:22:35.067195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4593 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:05:00.0, compute capability: 6.1)
2018-11-27 04:22:35.067573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 6512 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:06:00.0, compute capability: 6.1)
2018-11-27 04:22:35.070756: I tensorflow/compiler/jit/encapsulate_xla_computations_pass.cc:179] Subgraph fingerprint:11011464846742919204
2018-11-27 04:22:35.076199: I tensorflow/compiler/jit/encapsulate_xla_computations_pass.cc:179] Subgraph fingerprint:10675846169608442761
2018-11-27 04:22:35.185947: I tensorflow/compiler/xla/service/service.cc:149] XLA service 0x7f47800030a0 executing computations on platform CUDA. Devices:
2018-11-27 04:22:35.186050: I tensorflow/compiler/xla/service/service.cc:157]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2018-11-27 04:22:35.186072: I tensorflow/compiler/xla/service/service.cc:157]   StreamExecutor device (1): GeForce GTX 1080, Compute Capability 6.1
2018-11-27 04:22:35.280461: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:402] *** WARNING *** You are using ptxas 9.0.424, which is older than 9.2.88. ptxas 9.x before 9.2.88 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.


You do not need to update to CUDA 9.2.88; cherry-picking the ptxas binary is sufficient.
2018-11-27 04:22:02.158300: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at xla_ops.cc:295 : Invalid argument: Detected unsupported operations when trying to compile graph tower_0/cluster_12744596615876747846[] on XLA_GPU_JIT: Where (No registered 'Where' OpKernel for XLA_GPU_JIT devices compatible with node {{node tower_0/boolean_mask/Where}} = Where[T=DT_INT32, _device="/device:GPU:0"](tower_0/ToInt32)
        .  Registered:  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT8]
){{node tower_0/boolean_mask/Where}}
```

and

```

You do not need to update to CUDA 9.2.88; cherry-picking the ptxas binary is sufficient.
2018-11-27 04:22:35.507997: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at xla_ops.cc:295 : Invalid argument: Detected unsupported operations when trying to compile graph tower_0/cluster_10675846169608442761[] on XLA_GPU_JIT: DynamicPartition (No registered 'DynamicPartition' OpKernel for XLA_GPU_JIT devices compatible with node {{node tower_0/DynamicPartition_1}} = DynamicPartition[T=DT_INT32, num_partitions=2, _device="/device:GPU:0"](tower_0/Reshape_1, tower_0/ToInt32)
        .  Registered:  device='CPU'; T in [DT_VARIANT]
  device='CPU'; T in [DT_RESOURCE]
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
){{node tower_0/DynamicPartition_1}}

```

After removing the two operations, the code can run normally.

I also try https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_softmax_xla.py.

The results are same.

**Comment by jlebar** [comment] 2018-11-27 19:45
Sorry, didn't mean to ask you to try it with XLA, I was just asking if I was assigned the bug because it had something to do with XLA.  Sounds like it doesn't, so I'll unassign myself.

**Comment by xiaohu2015** [comment] 2018-11-30 07:00
> No anyone else meet this problem ?

I also meet the problem. I thought it might be some wrong with my code. But I remove the tf.dynamic_partition code, The loss don't get Nan. Hence, it is likely that the above problem.

**Comment by karmel** [comment] 2018-12-03 22:15
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by karmel** [comment] 2018-12-03 22:20
Sorry, it's not clear from the above what you are actually trying to accomplish. Can you clarify what you are trying to do?

**Comment by mzhaoshuai** [comment] 2018-12-04 05:42
@karmel 
I am training a semantic segmentation model. And there are some useless labels in the annotation images. The labels are in certain range, then I can get a boolean mask.  After I get the mask, I try to use `tf.boolean_mask` and `tf.dynamic_partition` to filter the useless labels. So they do not contribute to the final loss.

They both work normally when I use single GPU. 
When I use `tf.boolean_mask`, tf will warn me that it will cost  a lot of memory. 
So I try `tf.dynamic_partition`, and I find that it will cause NaN loss when I use multi GPUs.
But `tf.boolean_mask` works normally with multi GPUs.

The reproducible snippet code is given in my first comments.

And I also found the production of NaN loss when using `tf.dynamic_partition` is related to the magnitude of the data.
This is described in my second comments.

The key problem is that I think `tf.dynamic_partition` do not work properly when using multi GPUs.

**Comment by lcnature** [comment] 2018-12-10 16:52
Hello,
I came upon this issue after searching for the Warning message I saw `You are using ptxas 9.0.176, which is older than 9.2.88. ptxas 9.x before 9.2.88 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.` and also encountering NaN in loss function on multiple GPU training.

However, I have not explicitly used `tf.dynamica_partition`. I also find that a code which previously worked well on multiple GPU using tensorflow 1.10 now gives me NaN in loss with tensorflow 1.12. So I think this is a problem with the new version of tensorflow. On my cluster I have tried to use both cuda 9.2 and 10.0, and cudnn 7.3.1 and NaN always occur with tensorflow-gpu 1.12

I have checked the magnitudes of the data and the weights in the network. They all appear to be in reasonable range and there was no apparent change of their range before the NaN occurred (usually NaN does not appear on the first epoch of training but happens after a few hundreds of iterationd). One suspicious observation is that the norm of the gradients to the weights which are usually way below 1 suddenly changed to tens (or hundreds) of thousands in one iteration, a few iterations before NaN occurred in the loss function. But I have kept a relatively tight bound on gradient clipping in my Adam optimizier and very small learning rate (1e-5) so I would not expect one such jump in gradient to throw the network off (in fact, I observed the range of weights. They do not seem to change too much after this spike in gradient). However, as I said, the same network which worked previously with the same dataset on many hyperparameters settings now suddenly fail regardless of the hyperparameters I use. So i think it is not because of something wrong in my data.

I wonder whether the warning about XLA has something to do with this.

**Comment by jlebar** [comment] 2018-12-11 00:01
> I wonder whether the warning about XLA has something to do with this.

I'd be happy to help you debug this, but would you be willing to file a separate GitHub issue?  This issue is for a specific thing which we've established actually does not have to do with XLA.  Your issue sounds different, and combining issues makes things very confusing.

**Comment by karmel** [comment] 2019-01-08 21:18
Reassigning to @caisq for dynamic_partition on GPUs.

**Comment by kuba-ai-okinawa** [comment] 2019-06-25 17:11
Just bumping this up, as I run in exact same issue - tf.dynamic_partition often, but not always, turns some valid values into NaNs when using more than one gpu.

**Comment by jlebar** [comment] 2019-06-25 17:25
Same comment as https://github.com/tensorflow/tensorflow/issues/23918#issuecomment-446021526.

**Comment by jlebar** [comment] 2019-06-25 17:36
Oh I understand, this bug is still open, it just has nothing to do with XLA.  I will unassign myself, basically, same comment as https://github.com/tensorflow/tensorflow/issues/23918#issuecomment-442191501.

**Comment by sushreebarsa** [comment] 2021-07-07 02:59
@mzhaoshuai 
We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!

**Closed by sushreebarsa** 2021-07-07 02:59 UTC
Labels: comp:ops, type:bug
