### ISSUE TITLE
native python logging broken with TF 1.14

### ISSUE THREAD

**Issue by eldar** [tensorflow/tensorflow#29842] opened 2019-06-16 16:16 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.0 stretch
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): v1.12.1-2376-gf5ce1c00d4 1.14.0-rc0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.6
- GPU model and memory: NVIDIA Titan X (Pascal) 12Gb

**Describe the current behavior**
logging from the python's standard library stopped working in TF 1.14. Log file is not created and the output supposed to be written there is instead redirected to the stdout, which results in each logging message appear twice in the console.

**Describe the expected behavior**
When run on TF 1.12 , log.txt is created and the logging is being recorded correctly.

**Code to reproduce the issue**

```python
import logging
import tensorflow as tf


def main(_):
    FORMAT = '%(asctime)-15s %(message)s'
    logging.basicConfig(filename='log.txt', filemode='w',
                        datefmt='%Y-%m-%d %H:%M:%S',
                        level=logging.INFO, format=FORMAT)
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    logging.getLogger('').addHandler(console)

    sess = tf.Session()

    logging.info("test write")


if __name__ == '__main__':
    tf.app.run()
```

This yields the following output:

```
2019-06-16 17:54:24.047410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10711 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:04:00.0, compute capability: 6.1)
I0616 17:54:24.051054 140454010144128 test_logging.py:15] test write
test write
```

Notice that `test write` appears twice in the output. And log.txt is not created. When run with TF 1.12 this code snippets behaves as expected.

**Comment by gadagashwini** [comment] 2019-06-17 09:54
I could able to reproduce the above mentioned issue with tensorflow 1.14.0-rc0 on colab. Thanks!

**Comment by harahu** [comment] 2019-06-28 18:54
Similar problem here, @gadagashwini. Just importing tensorflow intrusively adds a logging handler to the root logger:
```python
import logging

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    logger.warning("Hi!")

(stderr)>>>
Hi!
```
vs
```python
import logging

import tensorflow as tf

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    logger.warning("Hi!")

(stderr)>>>
WARNING: Logging before flag parsing goes to stderr.
W0628 20:51:13.387141 140355075146048 test.py:9] Hi!
```

This is due to absl adding its own handler to the root logger when importing tensorflow.

**Comment by harahu** [comment] 2019-06-28 19:16
Having dug a bit more, I have found the reason for this issue. Compare the difference between `tf.app` in 1.13 and 1.14:
https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/platform/app.py
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/platform/app.py

I have traced the unwanted addition of an `ABSLHandler` down to this import in 1.14:
https://github.com/tensorflow/tensorflow/blob/f98fa7beca612279019a788d2719a3ebaaeaff85/tensorflow/python/platform/app.py#L23

**Comment by KristianHolsheimer** [comment] 2019-07-01 06:58
Just a quick ping to say that my work is also affected by this.

**Comment by lao8n** [comment] 2019-07-01 18:46
I have the same problem

**Comment by caisq** [comment] 2019-07-01 19:25
@revan has better context about this issue than I do. I'm assigning the bug to him.

**Comment by revan** [comment] 2019-07-01 20:51
Closing as duplicate of #26691.
See that bug for more, but TL;DR: upstream absl logging might be a touch too magical, but you can disable it.

**Closed by revan** 2019-07-01 20:51 UTC
Labels: comp:ops, stat:awaiting tensorflower, type:bug/performance
