### ISSUE TITLE
tf.layers.batch_normalization shape bug

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#17625] opened 2018-03-11 08:26 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04 / archlinux
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:v1.6.0-0-gd2e24b6039 1.6.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
```python
x = tf.placeholder(tf.float32, [100,100,100,100])
y = tf.layers.batch_normalization(x, axis=1, renorm=True, training=True, virtual_batch_size=2)
```
It throws:
```
ValueError: Dimension 1 in both shapes must be equal, but are 1 and 50. Shapes are [1,1,100,1,1] and [1,50,100,1,1]. for 'batch_normalization/AssignMovingAvg' (op: 'AssignSub') with input shapes:
[1,1,100,1,1], [1,50,100,1,1].
```
However, 
```python
x = tf.placeholder(tf.float32, [None,100,100,100])
y = tf.layers.batch_normalization(x, axis=1, renorm=True, training=True, virtual_batch_size=2)
```
works fine.

**Comment by cy89** [comment] 2018-03-15 22:45
There's more going on in the example that you're citing than the code that you've included. For example, something else in your code must be giving rise to the order-5 tensors that are causing the error. Can you please build us a minimal representative example? That'll help us to diagnose. 

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by ppwwyyxx** [comment] 2018-03-15 23:24
There is nothing more going on in the example code I posted. The code is self-contained and reproducible at least in my environment. I've already posted my environment information in the issue.

**Comment by tensorflowbutler** [comment] 2018-03-31 18:25
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-22 18:30
Nagging Assignee @cy89: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:50
Nagging Assignee @cy89: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ppwwyyxx** [comment] 2018-05-30 17:44
It has been >2 months. Despite how clear the bug report is, I didn't get a meaningful response from the team.
@chrisying who seems to implement virtual_batch_size originally

**Comment by chrisying** [comment] 2018-05-30 18:34
Hi @ppwwyyxx, originally `virtual_batch_size` was not intended to be used simultaneously with `renorm` (these two techniques are generally used for different use-cases) and thus not tested. However, I suppose there isn't anything stops the user from using the two together. I can see the potential use-case here where you have very small virtual_batches.

I've reproduced your error and identified the bug in the code: https://github.com/tensorflow/tensorflow/blob/2716bfff551591297a4ba6e61299e8147ac27c05/tensorflow/python/keras/layers/normalization.py#L589 this code block needs to be moved before the renorm code block above so that the means are reduced `if virtual_batch_size is not None` (`new_mean`/`new_variance` should be renamed to `mean`/`variance`).

I'll see if I can get this change in to the next TensorFlow release. In the meantime, if you need this exact functionality, please apply the change I described.

Side question: I'm curious why you need to use `renorm` and `virtual_batch_size` at the same time? Generally `renorm` is used for small batches (or non-iid batches) and `virtual_batch_size` is used for large batches. If you use both, I can imagine might be able to get by with using a larger `virtual_batch_size` and `renorm=False`.

**Comment by ppwwyyxx** [comment] 2018-05-30 18:47
Thanks a lot! 
I want to train stuff with small "normalization-batchsize" to see how bad it performs (just for research purposes), and at the same time I want to gain the GPU efficiency of larger batch for the rest of the network. That's why I want to mix the two.

**Comment by tensorflowbutler** [comment] 2018-06-14 18:49
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by chrisying** [comment] 2018-06-14 20:15
Closing this bug now that https://github.com/tensorflow/tensorflow/commit/2a484497062677f5cf0205ee3b9c28a64f03fe04 has been merged in.

Note: I haven't extensively tested if combining renorm and ghost batch norm is numerically correct. The unit tests for each pass but there aren't any tests that test both of them used together.

**Closed by chrisying** 2018-06-14 20:15 UTC
