### ISSUE TITLE
BatchNorm not working in a _FuncGraph

### ISSUE THREAD

**Issue by tongda** [tensorflow/tensorflow#14007] opened 2017-10-26 18:29 UTC
I am working on macOS 10.12.6 with TensorFlow 1.3.0, Python version: 3.6.2. CPU only.

I found that if `tf.contrib.layers.batch_norm` is called inside a `Defun`, a `TypeError` will be thrown. To clarify, the function here is a `map_func` that will be used in `Dataset.map` invoke, instead of a normal python function.

To regenerate the scenario, try this piece of code:

```
Dataset.range(27).batch(27) \
  .map(lambda x: tf.cast(tf.reshape(x, (3, 3, 3)), tf.float32) / 32.0) \
  .map(lambda img: tf.contrib.layers.batch_norm(img)) \
  .make_one_shot_iterator().get_next().eval()
```

You will get an error like this:

```
TypeError: In op 'BatchNorm/AssignMovingAvg', input types ([tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32])
```

I did some investigation. One thing that I found is that inside the `batch_norm`, we will assign a new value to the `mean` variable by calling `assign_sub`, which accept a variable with **ref** type and a value with a **basic type**. But the variable has been created some where in the `_FuncGraph` with a **basic type**, instead of a **ref** type, which make the compatibility check failed.

I will keep digging into this issue, but I think this seems a bug.

**Comment by michaelisard** [comment] 2017-10-26 22:06
@mrry if this isn't supported can you document/give a better error message do you think?

**Comment by tensorflowbutler** [comment] 2017-12-20 19:17
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by mrry** [comment] 2017-12-21 05:20
Reassigning to @akshayka, since he is currently revamping the function API.

**Comment by tensorflowbutler** [comment] 2018-01-04 19:12
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:09
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-08 19:19
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by akshayka** [comment] 2018-02-08 20:26
This somehow slipped under my radar; I'll dig into this ...

**Comment by tensorflowbutler** [comment] 2018-02-23 13:56
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:18
Nagging Assignee @akshayka: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:31
Nagging Assignee @akshayka: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:34
Nagging Assignee @akshayka: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:11
Nagging Assignee @akshayka: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:10
Nagging Assignee @akshayka: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:43
Nagging Assignee @akshayka: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:09
Nagging Assignee @akshayka: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:01
Nagging Assignee @akshayka: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:56
Nagging Assignee @akshayka: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:00
Nagging Assignee @akshayka: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:42
Nagging Assignee @akshayka: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:37
Nagging Assignee @akshayka: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by akshayka** [comment] 2018-09-13 17:17
This won't be fixed for Defun(), which is being replaced with tf.contrib.eager.defun. Once Datasets switch to using tf.contrib.eager.defun, the pasted code will work as intended.

**Closed by akshayka** 2018-09-13 17:17 UTC
Labels: type:bug/performance
