### ISSUE TITLE
having encounted an issue when i use ./configure to install tensorflow

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#4379] opened 2016-09-14 09:00 UTC
Hi, all.
i am new to tensorflow, and spent a lot of days to install tensorflow, but it didn't work. Need help

 sudo ./configure 
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 4
Please specify the location where cuDNN 4 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.5
Found stale PID file (pid=3471). Server probably died abruptly, continuing...
..
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /home/keithyin/tensorflow/tensorflow/contrib/session_bundle/BUILD:134:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by /home/keithyin/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle_lite'.
ERROR: /home/keithyin/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/keithyin/.cache/bazel/_bazel_root/9192340d7b606ddb9ea35b29a97154c1/external/jpeg_archive: Error downloading http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/keithyin/.cache/bazel/_bazel_root/9192340d7b606ddb9ea35b29a97154c1/external/jpeg_archive/jpegsrc.v9a.tar.gz: Connection timed out and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished

**Comment by MatthiasWinkelmann** [comment] 2016-09-14 14:09
To quote https://github.com/tensorflow/tensorflow/issues/4352#issuecomment-246908728:

> The errors regarding android_lib_lite and meta_graph_portable_proto should be fixed by f66b491, which was pushed today in #4360.

There may be a secondary problem you're encountering generating the download errors. I ran into this yesterday when I was struggling with the same android-reference problems. It appears that, if you run ./configure repeatedly because of a build problem, dependencies are also downloaded repeatedly and (some) servers react by blocking your requests.

Solutions include (a) waiting, (b) changing your IP address or possibly (c) changing the ```bazel clean --expunge``` at the end of /configure to just ```bazel clean```. Although the latter may create new problems if bazel isn't perfect with managing intermediate build results

**Comment by KeithYin** [comment] 2016-09-14 18:03
@MatthiasWinkelmann  i used bazel clean and did the suggestions as #4352 said , but i still got that issue
ERROR: /home/keithyin/workspace/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /home/keithyin/workspace/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.

**Comment by mxbi** [comment] 2016-09-14 18:44
Getting the exact same issue here, worked perfectly on exact same hardware a few days ago. It seems to be an issue with a recent commit.

Ubuntu 14.04, TITAN X, python2, CUDA 7.5, CuDNN 5.1

**Comment by KeithYin** [comment] 2016-09-15 02:16
@mxbi this issue occurs when i tried to build v0.9.0. Ubuntu16.04, GTX 960, python2, Cuda 8.0, cudnn 4. gcc-4.9 g++-4.9
C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 100 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by squallssck** [comment] 2016-09-17 01:17
same here when configure both on my mac and my desktop , this is what it looks like when configure on my mac

(tensorflow_anaconda/) KCs-MacBook-Pro:tensorflow kc$ ./configure 
~/tensor_versions/tensorflow ~/tensor_versions/tensorflow
Please specify the location of python. [Default is /Users/kc/anaconda2/envs/tensorflow_anaconda/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /Users/kc/anaconda2/envs/tensorflow_anaconda/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/Users/kc/anaconda2/envs/tensorflow_anaconda/lib/python2.7/site-packages]

/Users/kc/anaconda2/envs/tensorflow_anaconda/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Extracting Bazel installation...
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
INFO: Waiting for response from Bazel server (pid 70793)...
ERROR: /Users/kc/tensor_versions/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /Users/kc/tensor_versions/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /Users/kc/tensor_versions/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such package 'base': BUILD file not found on package path and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /Users/kc/tensor_versions/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such target '//tensorflow/core:android_tensorflow_lib_lite_no_rtti_lite_runtime': target 'android_tensorflow_lib_lite_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /Users/kc/tensor_versions/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /Users/kc/tensor_versions/tensorflow/tensorflow/core/kernels/BUILD:2211:1: no such target '//tensorflow/core:android_proto_lib_no_rtti_lite_runtime': target 'android_proto_lib_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /Users/kc/tensor_versions/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished

**Comment by KeithYin** [comment] 2016-09-17 01:49
@squallssck  would you like to isntall the latest version of tensorflow? if not. you can try this method:[http://wiki.jikexueyuan.com/project/tensorflow-zh/get_started/os_setup.html](url) you need just change the version 0.8.0 to 0.9.0 just like this  `sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl `. I hope it helps .

**Comment by martinwicke** [comment] 2016-10-03 23:51
Sorry, I was traveling for a bit. Is this an issue at head? There have been transient issues due to download issues, re-closing tensorflow mostly fixes those. Can you try with a fresh tensorflow?

**Comment by jart** [comment] 2016-10-15 08:51
It's likely this was a duplicate of https://github.com/tensorflow/tensorflow/issues/4312 and https://github.com/tensorflow/tensorflow/issues/4352 which should have been fixed in https://github.com/tensorflow/tensorflow/commit/f66b491a06627510c1cf751fc11db2caf5aa1f25

**Closed by jart** 2016-10-15 08:51 UTC
Labels: awaiting response
