### ISSUE TITLE
 AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute 'strategy_supports_no_merge_call'

### ISSUE THREAD

**Issue by Fer020707** [tensorflow/tensorflow#53510] opened 2021-12-21 20:21 UTC
Hello.
I am importing the following libraries while running the example that comes as the [basic text classification ](https://www.tensorflow.org/tutorials/keras/text_classification?hl=es-419) in the official Tensorflow documentation. But I get an error message. My version of tensorflow is 2.7.0

Running code for which the error occurred:
```
epochs = 10
history = model.fit( train_ds, validation_data=val_ds, epochs=epochs)
```

Libraries loads:
```
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import losses
```
Error message:
```
AttributeError: in user code:

    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\engine\training.py", line 1525, in test_function  *
        return step_function(self, iterator)
    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\engine\training.py", line 1514, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\engine\training.py", line 1507, in run_step  **
        outputs = model.test_step(data)
    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\engine\training.py", line 1474, in test_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\engine\training.py", line 961, in compute_metrics
        result = metric.result()
    File "C:\Users\Octavio\anaconda3\lib\site-packages\keras\utils\metrics_utils.py", line 124, in decorated
        tf.__internal__.distribute.strategy_supports_no_merge_call()):
```
Thank you

**Comment by mohantym** [comment] 2021-12-22 07:41
Hi @Fer020707 ! I was able to run above [example ](https://www.tensorflow.org/tutorials/keras/text_classification?hl=es-419) in Colab with 2.7 version too. Could you please share a minimal standalone code along other details through [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to reproduce this issue ?Attaching relevant [thread](https://github.com/tensorflow/tensorflow/issues/27120) for reference. Thanks!

**Comment by Fer020707** [comment] 2021-12-22 18:09
Of course. This would be the minimum code to reproduce the error. Will it be an installation aspect?

Imported libraries:
```
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import losses
```
Data upload
```
url = "https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"

dataset = tf.keras.utils.get_file("aclImdb_v1", url,
                                    untar=True, cache_dir='.',
                                    cache_subdir='')
dataset_dir = os.path.join(os.path.dirname(dataset), 'aclImdb')
train_dir = os.path.join(dataset_dir, 'train')
remove_dir = os.path.join(train_dir, 'unsup')
shutil.rmtree(remove_dir)
```
Data work
```
batch_size = 32
seed = 42
raw_train_ds = tf.keras.utils.text_dataset_from_directory(
    'aclImdb/train', 
    batch_size=batch_size, 
    validation_split=0.2, 
    subset='training', 
    seed=seed)
raw_val_ds = tf.keras.utils.text_dataset_from_directory(
    'aclImdb/train', 
    batch_size=batch_size, 
    validation_split=0.2, 
    subset='validation', 
    seed=seed)
raw_test_ds = tf.keras.utils.text_dataset_from_directory(
    'aclImdb/test', 
    batch_size=batch_size)
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')
def vectorize_text(text, label):
  text = tf.expand_dims(text, -1)
  return vectorize_layer(text), label

max_features = 10000
sequence_length = 250

vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length)
train_text = raw_train_ds.map(lambda x, y: x)
vectorize_layer.adapt(train_text)
text_batch, label_batch = next(iter(raw_train_ds))
first_review, first_label = text_batch[0], label_batch[0]
train_ds = raw_train_ds.map(vectorize_text)
val_ds = raw_val_ds.map(vectorize_text)
test_ds = raw_test_ds.map(vectorize_text)
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.cache().prefetch(buffer_size=AUTOTUNE)
embedding_dim = 16
model = tf.keras.Sequential([
  layers.Embedding(max_features + 1, embedding_dim),
  layers.Dropout(0.2),
  layers.GlobalAveragePooling1D(),
  layers.Dropout(0.2),
  layers.Dense(1)])

model.summary()
model.compile(loss=losses.BinaryCrossentropy(from_logits=True),
              optimizer='adam',
              metrics=tf.metrics.BinaryAccuracy(threshold=0.0))
epochs = 10
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=epochs)
```

**Comment by mohantym** [comment] 2021-12-23 04:25
Ok @Fer020707 !  it might be related to environment/installation perspective. Could not replicate this in Colab again. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/c033344bb53aa4929a4c6060a134dd9b/github_53510.ipynb) and relevant [thread](https://stackoverflow.com/questions/67696519/module-tensorflow-compat-v2-internal-has-no-attribute-tf2/67708260#67708260) for reference.

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues) if it does not get resolved.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks you!

**Comment by gcuder** [comment] 2021-12-23 06:19
@Fer020707 I was able to find the source of this issue. When installing `tensorflow 2.7.0`, `keras 2.8.0` was installed. I solved this issue by pinning `keras` to `2.7.0` in my `pyproject.toml`

**Comment by mohantym** [comment] 2021-12-23 08:21
Ok @Fer020707 ! Thanks for pointing out the solution . we will let the team know about it. Thank you!

**Comment by Fer020707** [comment] 2021-12-23 21:07
Thank you very much. By correcting that, it worked perfect

**Comment by mohantym** [comment] 2021-12-24 03:44
Ok @Fer020707 ! Closing this issue as it seems to be resolved from above comment . Thank you!

**Closed by mohantym** 2021-12-24 03:44 UTC
Labels: type:others, comp:keras, TF 2.7

**Comment by wrogner** [comment] 2022-02-08 08:47
Similar error on MacOS (ARM) with tensorflow-macos. After an pip -U ... I downgraded keras and tensorflow-estimator to 2.7.0.

When fitting the model, the following error occurs:

```
model.fit(x_train, y_train, epochs=5)

Epoch 1[/5]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/wolf/Development/py/5 ml/[1]() prerequisites/07 tensorflow/01_quickstart.ipynb Cell 18' in <module>
----> 1 model.fit(x_train, y_train, epochs=5)

File ~/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
         65 except Exception as e:  # pylint: disable=broad-except
         66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
         68 finally:
         69   del filtered_tb

File ~/Development/py/5 ml/venv/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:1129, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1127 except Exception as e:  # pylint:disable=broad-except
   1128   if hasattr(e, "ag_error_metadata"):
-> 1129     raise e.ag_error_metadata.to_exception(e)
   1130   else:
   1131     raise

AttributeError: in user code:

    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/engine/training.py", line 1010, in step_function  **
        - A `tf.data.Dataset`.
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/engine/training.py", line 1000, in run_step  **
        validation_data: Data on which to evaluate
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/engine/training.py", line 863, in train_step
        model._train_counter.assign_add(1)  # pylint: disable=protected-access
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 668, in apply_gradients
        grads_and_vars = self._aggregate_gradients(grads_and_vars)
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 484, in _aggregate_gradients
        return self.gradient_aggregator(grads_and_vars)
    File "/Users/wolf/Development/py/5 ml/venv/lib/python3.9/site-packages/keras/optimizer_v2/utils.py", line 33, in all_reduce_sum_gradients
        if strategy_supports_no_merge_call():

    AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute 'strategy_supports_no_merge_call'
```

This worked before the update
