### ISSUE TITLE
Documentation is becoming too undecipherable for a meaningful practical work

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#42896] opened 2020-09-02 15:28 UTC
The documentation is becoming too undecipherable for any practical applications using Tensorflow.

Look at this one, https://www.tensorflow.org/guide/data

How would anyone learn anything for a streaming data from Disk ? Not many how-tos for data that don't fit into memory. And that page.. just like a man-page for API. We end up wasting many man hours without good documentation.

**Comment by bhack** [comment] 2020-09-02 16:52
Is this a duplicate of https://github.com/tensorflow/tensorflow/issues/32938?

**Comment by mihaimaruseac** [comment] 2020-09-02 17:13
Can you send PRs to fix documentation? This is an evolving process, we try to get documentation that is as useful as possible to as many people as possible.

**Closed** 2020-09-21 11:34 UTC
Labels: comp:data, stalled, stat:awaiting response, type:docs-bug
