### ISSUE TITLE
Preferred way of installing TensorRT with Tensorflow 1.11 on Ubuntu?

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#22575] opened 2018-09-27 23:13 UTC
Back when TensorRT support was first announced back in version 1.7, for TensorRT to work it was necessary that you install TensorRT 3.0.4 for Ubuntu 14.04, regardless of your version. For 1.11, which version of TensorRT should be used when installing the tensorflow-gpu pip package?

**Comment by tensorflowbutler** [comment] 2018-09-28 06:47
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-10-12 12:50
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-10-22 16:31
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-22 16:31 UTC
Labels: stat:awaiting response

**Comment by atyshka** [comment] 2018-10-22 16:44
I know I can build from source with the tensorrt 5, to clarify I’m wondering what version the tensorflow-gpu pip package was built against
