### ISSUE TITLE
Build issue  Bazel

### ISSUE THREAD

**Issue by Mohamedtareque** [tensorflow/tensorflow#29845] opened 2019-06-16 20:44 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: MacOS Mojave 10.14.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version:2.0.0-beta1 
- Python version:3.6
- Installed using virtualenv? pip? conda?:No
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):4.2.1
- CUDA/cuDNN version:No
- GPU model and memory: 4G ram

**Describe the problem**
I face these errors so what's solution ? 
```
Kotozs-MacBook-Air-6:tensorflow kotoz$ ./configure 
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.1 installed.
Please specify the location of python. [Default is /usr/local/opt/python@2/bin/python2.7]: /usr/local/opt/python@3/bin/python3.6


Found possible Python library paths:
  /usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: N
No iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
Kotozs-MacBook-Air-6:tensorflow kotoz$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=89
INFO: Reading rc options for 'build' from /Users/kotoz/Downloads/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /Users/kotoz/Downloads/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/opt/python@3/bin/python3.6 --action_env PYTHON_LIB_PATH=/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages --python_path=/usr/local/opt/python@3/bin/python3.6 --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:opt in file /Users/kotoz/Downloads/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at /Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl:346:20):
 - /Users/kotoz/Downloads/tensorflow/tensorflow/workspace.bzl:69:5
 - /Users/kotoz/Downloads/tensorflow/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 344
		_create_local_python_repository(repository_ctx)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Call stack for the definition of repository 'jpeg' which is a third_party_http_archive (rule definition at /Users/kotoz/Downloads/tensorflow/third_party/repo.bzl:206:28):
 - /Users/kotoz/Downloads/tensorflow/third_party/jpeg/workspace.bzl:6:5
 - /Users/kotoz/Downloads/tensorflow/tensorflow/workspace.bzl:45:5
 - /Users/kotoz/Downloads/tensorflow/tensorflow/workspace.bzl:73:5
 - /Users/kotoz/Downloads/tensorflow/WORKSPACE:94:1
INFO: Call stack for the definition of repository 'pcre' which is a tf_http_archive (rule definition at /Users/kotoz/Downloads/tensorflow/third_party/repo.bzl:126:19):
 - /Users/kotoz/Downloads/tensorflow/tensorflow/workspace.bzl:449:5
 - /Users/kotoz/Downloads/tensorflow/WORKSPACE:94:1
ERROR: /Users/kotoz/Downloads/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 344
		_create_local_python_repository(repository_ctx)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 296, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 276, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/Users/kotoz/Downloads/tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 14.536s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (143 packages loaded, 3114 targets configur\
ed)
    Fetching @local_config_xcode; fetching 7s
Kotozs-MacBook-Air-6:tensorflow kotoz$ 
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rlewkowicz** [comment] 2019-06-16 23:30
Is numpy installed?

**Comment by Mohamedtareque** [comment] 2019-06-17 01:59
Yes installed

**Comment by jvishnuvardhan** [comment] 2019-06-24 20:21
@Mohamedtareque Could you downgrade Bazel to 0.26.0 as that is the max version allowed. Please check the source [here](https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/configure.py#L1394). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-08 17:47
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-07-08 17:47 UTC
Labels: stat:awaiting response, subtype:bazel, subtype:macOS, type:build/install

**Comment by manavkulshrestha** [comment] 2019-08-13 17:28
I'm using bazel 0.26.0 with numpy installed but the problem still persists

**Comment by mihaimaruseac** [comment] 2019-08-13 18:00
Just to check that all is good, please post the output of the following command:

```console
yes "" | ./configure; python -c "import numpy as np"
```

**Comment by manavkulshrestha** [comment] 2019-08-13 18:48
```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: 

Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished```

**Comment by mihaimaruseac** [comment] 2019-08-13 20:59
Thanks. That confirms that `numpy` is visible from the path you're building tensorflow. Next step in debugging would be to try

```console
python -c "import numpy as np; print(np.__path__); print(np.get_include())"
```

Please let us know what that prints

**Comment by ayushmankumar7** [comment] 2020-04-12 06:59
$ yes "" | ./configure; python -c "import numpy as np"
bash: ./configure: No such file or directory
I am getting this error. 

I also tried python3, getting the same error

**Comment by ayushmankumar7** [comment] 2020-04-12 07:12
The issue is solved.

**Comment by navneet-applify** [comment] 2020-04-14 07:03
> The issue is solved.

Can you please share the solution
i'm trying to build .pb file from terminal in Ubuntu.

And i'm facing the error 
ImportError: No module named 'numpy'

**Comment by navi63** [comment] 2020-04-14 07:09
> The issue is solved.

hi @ayushmankumar7 

I'm trying to genrate .pb file from terminal in ubuntu.

And i'm geting the same error i.e : ImportError: No module named 'numpy'

Let me know what can i do to resolve this?

**Comment by ayushmankumar7** [comment] 2020-04-14 08:33
@navi63  Sure....

See first tensorflow has considered for both Python3 and Python2 .. so make sure that you have nump installed in both the versions . This error will be solved

**Comment by navi63** [comment] 2020-04-14 10:57
@ayushmankumar7 thanks it works
may i know if you have any info regarding converting .pb file to tflite file?

**Comment by mihaimaruseac** [comment] 2020-04-14 16:27
@navi63 this issue has no relationship with your question. Please open new issues if they are issues with TensorFlow library code or please ask other questions on StackOverflow.

Locking conversation here as it has been solved already
