### ISSUE TITLE
tensorflow.exp : error lnk2001 : unresolved symbol "public: class Eigen::TensorMap<>...."

### ISSUE THREAD

**Issue by cl886699** [tensorflow/tensorflow#20802] opened 2018-07-14 15:16 UTC
windows build tensorflow-1.8  almost success,the finnal tensorflow.dll failed
anybody has ideas

**Comment by tensorflowbutler** [comment] 2018-07-15 00:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aimhabo** [comment] 2018-07-17 01:32
have you install Eigen3 and put it into your PATH?

**Comment by cl886699** [comment] 2018-07-17 13:11
i see ，maybe it is the problem of internet, when i build it agian ,no longer show that problem.

**Comment by asimshankar** [comment] 2018-07-20 19:41
Closing since it seems like the issue is resolved.

**Closed by asimshankar** 2018-07-20 19:41 UTC
