### ISSUE TITLE
NotFoundError: No registered 'ReadFile' OpKernel for GPU devices compatible with node {{node ReadFile}}

### ISSUE THREAD

**Issue by Bornlex** [tensorflow/tensorflow#31112] opened 2019-07-28 12:48 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): installed via pip
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.8
- CUDA/cuDNN version: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
- GPU model and memory: NVIDIA GeForce GTX 1060 3GB

**Describe the current behavior**

I am running the following code (it runs well on Google Colab GPU):
```python
def build_dataset(boxes_img_dataframe, data_directory, augment=True, shuffle=False):
    filenames_ds = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['image_name'].apply(lambda path: os.path.join(data_directory, path)))
    images_ds    = filenames_ds.map(
        lambda path: (tf.image.decode_jpeg(tf.io.read_file(path)) / 255) * 2 - 1
    )
    x1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_1'])
    x2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_2'])
    y1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_1'])
    y2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_2'])
    tmp_ds       = tf.data.Dataset.zip((images_ds, x1_ds, x2_ds, y1_ds, y2_ds))
    #"""
    images_ds    = tmp_ds.map(
        lambda image, x1, x2, y1, y2: tf.image.resize_images(
            tf.image.crop_to_bounding_box(
                image,
                tf.cast(x1, tf.int32),
                tf.cast(y1, tf.int32),
                tf.cast(x2 - x1, tf.int32),
                tf.cast(y2 - y1, tf.int32)
            ),
            (96, 96)
        )
    )
    if augment:
        images_color_augmented_hue = images_ds.map(
            lambda image: tf.image.random_hue(image, 0.08)
        )
        images_color_augmented_sat = images_ds.map(
            lambda image: tf.image.random_saturation(image, 0.6, 1.6)
        )
        images_color_augmented_bri = images_ds.map(
            lambda image: tf.image.random_brightness(image, 0.05)
        )
        images_color_augmented_con = images_ds.map(
            lambda image: tf.image.random_contrast(image, 0.7, 1.3)
        )
        images_augmented_flipped   = images_ds.map(
            lambda image: tf.image.flip_left_right(image)
        )
        images_augmented_rotation  = images_ds.map(
            lambda image: tf.image.rot90(image, tf.random_uniform(shape=[], minval=0, maxval=4, dtype=tf.int32))
        )
        images_ds = images_ds.concatenate(images_color_augmented_hue)
        images_ds = images_ds.concatenate(images_color_augmented_sat)
        images_ds = images_ds.concatenate(images_color_augmented_bri)
        images_ds = images_ds.concatenate(images_color_augmented_con)
        images_ds = images_ds.concatenate(images_augmented_flipped)
        images_ds = images_ds.concatenate(images_augmented_rotation)
        images_ds = images_ds.map(lambda image: tf.clip_by_value(image, -1, 1))
    ds = tf.data.Dataset.zip((images_ds, images_ds))
    ds = ds.apply(tf.data.experimental.ignore_errors())
    if shuffle:
        ds = ds.shuffle(1000)
    return ds
```

This basically builds my dataset, and I call it in the model like that:

```python
with tf.device('/gpu:0'):
        autoencoder.fit(
            dataset.batch(32),
            epochs=epochs,
            steps_per_epoch=steps,
            shuffle=True,
        )
```

So actually pretty straighforward I guess.

And when it runs, I get the following error:

```
WARNING: Logging before flag parsing goes to stderr.
W0728 11:28:51.089698 10264 deprecation_wrapper.py:119] From main.py:80: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0728 11:28:51.129585 10264 deprecation.py:506] From C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-07-28 11:28:52.388036: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-07-28 11:28:52.403659: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-07-28 11:28:52.546637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2019-07-28 11:28:52.551575: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-07-28 11:28:52.554530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-07-28 11:28:53.229349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-28 11:28:53.233344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-07-28 11:28:53.235723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-07-28 11:28:53.237899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2112 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-07-28 11:29:01.339772: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Not found: No registered 'ReadFile' OpKernel for GPU devices compatible with node {{node ReadFile}}
        .  Registered:  device='CPU'

         [[ReadFile]]
2019-07-28 11:29:01.376815: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at iterator_ops.cc:601 : Not found: No registered 'ReadFile' OpKernel for GPU devices compatible with node {{node ReadFile}}
        .  Registered:  device='CPU'

         [[ReadFile]]
Traceback (most recent call last):
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ReadFile' OpKernel for GPU devices compatible with node {{node ReadFile}}
        .  Registered:  device='CPU'

         [[ReadFile]]
         [[MakeIterator]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 140, in main
    model.train_model(latent_model, dataset, epochs, steps_per_epoch)
  File "C:\Users\Julien\Documents\Travail\NarcisseTechnologies\narcisse.latent\trainer\model.py", line 201, in train_model
    shuffle=True,
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 142, in model_iteration
    input_iterator = _get_iterator(inputs, model._distribution_strategy)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 517, in _get_iterator
    return training_utils.get_iterator(inputs)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 1315, in get_iterator
    initialize_iterator(iterator)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 1322, in initialize_iterator
    K.get_session((init_op,)).run(init_op)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\Julien\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'ReadFile' OpKernel for GPU devices compatible with node {{node ReadFile}}
        .  Registered:  device='CPU'

         [[ReadFile]]
         [[MakeIterator]]
```

It seems that the tf.io.read_file operation is running on the GPU, and my GPU does not support this kind of operation.

This is what I understand from the error.

What can I do to fix this please? Is it a bug in the driver, a compatibility problem... ?

**Comment by Bornlex** [comment] 2019-07-28 18:33
@asimshankar I saw that you answered similar questions. Maybe you can help with this one?

**Comment by ravikyram** [comment] 2019-07-29 08:15
@Bornlex 
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by Bornlex** [comment] 2019-07-29 10:12
Yes of course.

```python
class SampleLayer(Layer):
    '''
    Keras Layer to grab a random sample from a distribution (by multiplication)
    Computes "(normal)*logvar + mean" for the vae sampling operation
    (written for tf backend)

    Additionally,
        Applies regularization to the latent space representation.
        Can perform standard regularization or B-VAE regularization.

    call:
        pass in mean then logvar layers to sample from the distribution
        ex.
            sample = SampleLayer('bvae', 16)([mean, logvar])
    '''
    def __init__(self, latent_regularizer='bvae', beta=100., **kwargs):
        '''
        args:
        ------
        latent_regularizer : str
            Either 'bvae', 'vae', or 'no'
            Determines whether regularization is applied
                to the latent space representation.
        beta : float
            beta > 1, used for 'bvae' latent_regularizer,
            (Unused if 'bvae' not selected)
        ------
        ex.
            sample = SampleLayer('bvae', 16)([mean, logvar])
        '''
        if latent_regularizer.lower() in ['bvae', 'vae']:
            self.reg = latent_regularizer
        else:
            self.reg = None
    
        if self.reg == 'bvae':
            self.beta = beta
        elif self.reg == 'vae':
            self.beta = 1.

        super(SampleLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # save the shape for distribution sampling
        super(SampleLayer, self).build(input_shape) # needed for layers

    def call(self, x, training=None):
        if len(x) != 2:
            raise Exception('input layers must be a list: mean and logvar')
        if len(x[0].shape) != 2 or len(x[1].shape) != 2:
            raise Exception('input shape is not a vector [batchSize, latentSize]')

        mean = x[0]
        logvar = x[1]

        # trick to allow setting batch at train/eval time
        if mean.shape[0].value == None or  logvar.shape[0].value == None:
            return mean + 0*logvar # Keras needs the *0 so the gradinent is not None

        if self.reg is not None:
            # kl divergence:
            latent_loss = -0.5 * (1 + logvar
                                - K.square(mean)
                                - K.exp(logvar))
            latent_loss = K.sum(latent_loss, axis=-1) # sum over latent dimension
            latent_loss = K.mean(latent_loss, axis=0) # avg over batch

            # use beta to force less usage of vector space:
            latent_loss = self.beta * latent_loss
            self.add_loss(latent_loss, x)

        def reparameterization_trick():
            epsilon = K.random_normal(shape=logvar.shape,
                              mean=0., logvar=1.)
            stddev = K.exp(logvar*0.5)
            return mean + stddev * epsilon * inf

        return K.in_train_phase(reparameterization_trick, mean + 0*logvar, training=training)

    def compute_output_shape(self, input_shape):
        return input_shape[0]

class CustomAutoEncoder(object):
    def __init__(self, latent_size, beta):
        self.shape       = (96, 96, 3)
        self.latent_size = 50
        self.beta        = 1
        self.encoder = self.build_encoder()
        self.decoder = self.build_decoder()
        self.ae      = Model(self.encoder.inputs, self.decoder(self.encoder.outputs))
        self.batch   = 32
    
    def build_encoder(self):
        encoder_input = Input((self.shape))
        x = Conv2D(64, (5, 5), strides=(3, 3), padding='same', kernel_initializer='glorot_uniform')(encoder_input)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(128, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(256, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        mean   = Conv2D(self.latent_size, (1, 1), padding='same')(x)
        mean   = GlobalAveragePooling2D()(mean)
        logvar = Conv2D(self.latent_size, (1, 1), padding='same')(x)
        logvar = GlobalAveragePooling2D()(logvar)
        x = SampleLayer('bvae', self.beta)([mean, logvar])
        return Model(encoder_input, x)
    
    def build_decoder(self):
        encoder_input = Input((self.latent_size,))
        x = Reshape((1, 1, self.latent_size))(encoder_input)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(256, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(128, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(64, (5, 5), strides=(3, 3), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(3, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        
        x = Conv2D(self.shape[-1], (1, 1), 1, padding='same', activation='tanh')(x)
        return Model(encoder_input, x)

def build_model(latent_size, beta):
    bvae = CustomAutoEncoder(latent_size, beta)
    encoder = bvae.encoder
    decoder = bvae.decoder
    autoencoder = bvae.ae
    autoencoder.compile(
        optimizer=optimizers.Adam(),
        loss='mean_absolute_error'
    )
    return autoencoder

def train_model(autoencoder, dataset, epochs, steps):
    with tf.device('/gpu:0'):
        autoencoder.fit(
            dataset.batch(32),
            epochs=epochs,
            steps_per_epoch=steps,
            shuffle=True,
        )

def build_dataset(boxes_img_dataframe, data_directory, augment=True, shuffle=False):
    filenames_ds = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['image_name'].apply(lambda path: os.path.join(data_directory, path)))
    images_ds    = filenames_ds.map(
        lambda path: (tf.image.decode_jpeg(tf.io.read_file(path)) / 255) * 2 - 1
    )
    x1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_1'])
    x2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_2'])
    y1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_1'])
    y2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_2'])
    tmp_ds       = tf.data.Dataset.zip((images_ds, x1_ds, x2_ds, y1_ds, y2_ds))
    #"""
    images_ds    = tmp_ds.map(
        lambda image, x1, x2, y1, y2: tf.image.resize_images(
            tf.image.crop_to_bounding_box(
                image,
                tf.cast(x1, tf.int32),
                tf.cast(y1, tf.int32),
                tf.cast(x2 - x1, tf.int32),
                tf.cast(y2 - y1, tf.int32)
            ),
            (96, 96)
        )
    )
    if augment:
        images_color_augmented_hue = images_ds.map(
            lambda image: tf.image.random_hue(image, 0.08)
        )
        images_color_augmented_sat = images_ds.map(
            lambda image: tf.image.random_saturation(image, 0.6, 1.6)
        )
        images_color_augmented_bri = images_ds.map(
            lambda image: tf.image.random_brightness(image, 0.05)
        )
        images_color_augmented_con = images_ds.map(
            lambda image: tf.image.random_contrast(image, 0.7, 1.3)
        )
        images_augmented_flipped   = images_ds.map(
            lambda image: tf.image.flip_left_right(image)
        )
        images_augmented_rotation  = images_ds.map(
            lambda image: tf.image.rot90(image, tf.random_uniform(shape=[], minval=0, maxval=4, dtype=tf.int32))
        )
        images_ds = images_ds.concatenate(images_color_augmented_hue)
        images_ds = images_ds.concatenate(images_color_augmented_sat)
        images_ds = images_ds.concatenate(images_color_augmented_bri)
        images_ds = images_ds.concatenate(images_color_augmented_con)
        images_ds = images_ds.concatenate(images_augmented_flipped)
        images_ds = images_ds.concatenate(images_augmented_rotation)
        images_ds = images_ds.map(lambda image: tf.clip_by_value(image, -1, 1))
    ds = tf.data.Dataset.zip((images_ds, images_ds))
    ds = ds.apply(tf.data.experimental.ignore_errors())
    if shuffle:
        ds = ds.shuffle(1000)
    return ds


boxes_img = pd.read_csv(os.path.join(args.data_dir, 'list_bbox.txt'), sep='\s+', skiprows=1, dtype={
        'image_name': str,
        'x_1': np.int32,
        'x_2': np.int32,
        'y_1': np.int32,
        'y_2': np.int32,
    })

    tf.keras.callbacks.TensorBoard(log_dir=os.path.join(args.save_path, args.log_dir), histogram_freq=0, write_graph=True, write_images=True)

    epochs = args.epochs
    steps_per_epoch = args.steps_per_epoch
    dataset = build_dataset(boxes_img, args.data_dir, augment=args.augment)
    dataset = dataset.repeat(epochs)
    latent_model = build_model(args.latent_size, args.beta)
    train_model(latent_model, dataset, epochs, steps_per_epoch)
```

**Comment by Bornlex** [comment] 2019-07-30 22:27
@ravikyram is it enough?

**Comment by ravikyram** [comment] 2019-07-31 12:14
@Bornlex 
I tried to reproduce the issue .I am getting the  error `NameError: name 'args' is not defined`.
Please, help me with the reproducible code and the  list_bbox.txt file.Thanks!

**Comment by Bornlex** [comment] 2019-07-31 13:46
```python
import os
import sys
import cv2
import numpy as np
import pandas as pd
from PIL import Image
import tensorflow as tf
import matplotlib.pyplot as plt

from IPython import display

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import (
    Dense,
    Dropout,
    Flatten,
    GlobalAveragePooling2D,
    Conv2D,
    Input,
    MaxPooling2D,
    UpSampling2D,
    Reshape,
    BatchNormalization,
    LeakyReLU,
    Add,
    Conv2DTranspose,
    Activation
)
from tensorflow.keras import optimizers
from tensorflow.keras import regularizers
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.python.keras.layers import Layer
from tensorflow.python.keras import backend as K
from tensorflow.keras.callbacks import ModelCheckpoint


class SampleLayer(Layer):
    '''
    Keras Layer to grab a random sample from a distribution (by multiplication)
    Computes "(normal)*logvar + mean" for the vae sampling operation
    (written for tf backend)

    Additionally,
        Applies regularization to the latent space representation.
        Can perform standard regularization or B-VAE regularization.

    call:
        pass in mean then logvar layers to sample from the distribution
        ex.
            sample = SampleLayer('bvae', 16)([mean, logvar])
    '''
    def __init__(self, latent_regularizer='bvae', beta=100., **kwargs):
        '''
        args:
        ------
        latent_regularizer : str
            Either 'bvae', 'vae', or 'no'
            Determines whether regularization is applied
                to the latent space representation.
        beta : float
            beta > 1, used for 'bvae' latent_regularizer,
            (Unused if 'bvae' not selected)
        ------
        ex.
            sample = SampleLayer('bvae', 16)([mean, logvar])
        '''
        if latent_regularizer.lower() in ['bvae', 'vae']:
            self.reg = latent_regularizer
        else:
            self.reg = None
    
        if self.reg == 'bvae':
            self.beta = beta
        elif self.reg == 'vae':
            self.beta = 1.

        super(SampleLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # save the shape for distribution sampling
        super(SampleLayer, self).build(input_shape) # needed for layers

    def call(self, x, training=None):
        if len(x) != 2:
            raise Exception('input layers must be a list: mean and logvar')
        if len(x[0].shape) != 2 or len(x[1].shape) != 2:
            raise Exception('input shape is not a vector [batchSize, latentSize]')

        mean = x[0]
        logvar = x[1]

        # trick to allow setting batch at train/eval time
        if mean.shape[0].value == None or  logvar.shape[0].value == None:
            return mean + 0*logvar # Keras needs the *0 so the gradinent is not None

        if self.reg is not None:
            # kl divergence:
            latent_loss = -0.5 * (1 + logvar
                                - K.square(mean)
                                - K.exp(logvar))
            latent_loss = K.sum(latent_loss, axis=-1) # sum over latent dimension
            latent_loss = K.mean(latent_loss, axis=0) # avg over batch

            # use beta to force less usage of vector space:
            latent_loss = self.beta * latent_loss
            self.add_loss(latent_loss, x)

        def reparameterization_trick():
            epsilon = K.random_normal(shape=logvar.shape,
                              mean=0., logvar=1.)
            stddev = K.exp(logvar*0.5)
            return mean + stddev * epsilon * inf

        return K.in_train_phase(reparameterization_trick, mean + 0*logvar, training=training)

    def compute_output_shape(self, input_shape):
        return input_shape[0]

class CustomAutoEncoder(object):
    def __init__(self, latent_size, beta):
        self.shape       = (96, 96, 3)
        self.latent_size = 50
        self.beta        = 1
        self.encoder = self.build_encoder()
        self.decoder = self.build_decoder()
        self.ae      = Model(self.encoder.inputs, self.decoder(self.encoder.outputs))
        self.batch   = 32
    
    def build_encoder(self):
        encoder_input = Input((self.shape))
        x = Conv2D(64, (5, 5), strides=(3, 3), padding='same', kernel_initializer='glorot_uniform')(encoder_input)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(128, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(256, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2D(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        mean   = Conv2D(self.latent_size, (1, 1), padding='same')(x)
        mean   = GlobalAveragePooling2D()(mean)
        logvar = Conv2D(self.latent_size, (1, 1), padding='same')(x)
        logvar = GlobalAveragePooling2D()(logvar)
        x = SampleLayer('bvae', self.beta)([mean, logvar])
        return Model(encoder_input, x)
    
    def build_decoder(self):
        encoder_input = Input((self.latent_size,))
        x = Reshape((1, 1, self.latent_size))(encoder_input)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(512, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(256, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(128, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(64, (5, 5), strides=(3, 3), padding='same', kernel_initializer='glorot_uniform')(x)
        x = BatchNormalization(momentum=0.5)(x)
        x = Activation('relu')(x)
        
        x = Conv2DTranspose(3, (5, 5), strides=(2, 2), padding='same', kernel_initializer='glorot_uniform')(x)
        
        x = Conv2D(self.shape[-1], (1, 1), 1, padding='same', activation='tanh')(x)
        return Model(encoder_input, x)

def build_model(latent_size, beta):
    bvae = CustomAutoEncoder(latent_size, beta)
    encoder = bvae.encoder
    decoder = bvae.decoder
    autoencoder = bvae.ae
    autoencoder.compile(
        optimizer=optimizers.Adam(),
        loss='mean_absolute_error'
    )
    return autoencoder

def train_model(autoencoder, dataset, epochs, steps):
    with tf.device('/gpu:0'):
        autoencoder.fit(
            dataset.batch(32),
            epochs=epochs,
            steps_per_epoch=steps,
            shuffle=True,
        )

def build_dataset(boxes_img_dataframe, data_directory, augment=True, shuffle=False):
    filenames_ds = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['image_name'].apply(lambda path: os.path.join(data_directory, path)))
    images_ds    = filenames_ds.map(
        lambda path: (tf.image.decode_jpeg(tf.io.read_file(path)) / 255) * 2 - 1
    )
    x1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_1'])
    x2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['x_2'])
    y1_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_1'])
    y2_ds        = tf.data.Dataset.from_tensor_slices(boxes_img_dataframe['y_2'])
    tmp_ds       = tf.data.Dataset.zip((images_ds, x1_ds, x2_ds, y1_ds, y2_ds))
    #"""
    images_ds    = tmp_ds.map(
        lambda image, x1, x2, y1, y2: tf.image.resize_images(
            tf.image.crop_to_bounding_box(
                image,
                tf.cast(x1, tf.int32),
                tf.cast(y1, tf.int32),
                tf.cast(x2 - x1, tf.int32),
                tf.cast(y2 - y1, tf.int32)
            ),
            (96, 96)
        )
    )
    if augment:
        images_color_augmented_hue = images_ds.map(
            lambda image: tf.image.random_hue(image, 0.08)
        )
        images_color_augmented_sat = images_ds.map(
            lambda image: tf.image.random_saturation(image, 0.6, 1.6)
        )
        images_color_augmented_bri = images_ds.map(
            lambda image: tf.image.random_brightness(image, 0.05)
        )
        images_color_augmented_con = images_ds.map(
            lambda image: tf.image.random_contrast(image, 0.7, 1.3)
        )
        images_augmented_flipped   = images_ds.map(
            lambda image: tf.image.flip_left_right(image)
        )
        images_augmented_rotation  = images_ds.map(
            lambda image: tf.image.rot90(image, tf.random_uniform(shape=[], minval=0, maxval=4, dtype=tf.int32))
        )
        images_ds = images_ds.concatenate(images_color_augmented_hue)
        images_ds = images_ds.concatenate(images_color_augmented_sat)
        images_ds = images_ds.concatenate(images_color_augmented_bri)
        images_ds = images_ds.concatenate(images_color_augmented_con)
        images_ds = images_ds.concatenate(images_augmented_flipped)
        images_ds = images_ds.concatenate(images_augmented_rotation)
        images_ds = images_ds.map(lambda image: tf.clip_by_value(image, -1, 1))
    ds = tf.data.Dataset.zip((images_ds, images_ds))
    ds = ds.apply(tf.data.experimental.ignore_errors())
    if shuffle:
        ds = ds.shuffle(1000)
    return ds


boxes_img = pd.read_csv(os.path.join("/path/to/data", 'list_bbox.txt'), sep='\s+', skiprows=1, dtype={
        'image_name': str,
        'x_1': np.int32,
        'x_2': np.int32,
        'y_1': np.int32,
        'y_2': np.int32,
    })

    epochs = 100
    steps_per_epoch = 1000
    dataset = build_dataset(boxes_img, "/path/to/data")
    dataset = dataset.repeat(epochs)
    latent_model = build_model(100, 10)
    train_model(latent_model, dataset, epochs, steps_per_epoch)
```

The dataset I use is the DeepFashion dataset (in Img folder here, the img.zip).
The list_bbox.txt file is located in the Anno folder, same link.

https://drive.google.com/drive/folders/0B7EVK8r0v71pWGplNFhjc01NbzQ


@ravikyram sorry, I was trying to give you the minimum amount of code necessary so you have an idea of the problem.

**Comment by Bornlex** [comment] 2019-08-04 22:24
@jvishnuvardhan Hello. Do you have a rough idea of what is the cause of this?
Is it a bad installation, bad version, not compatible hardware, bad code?

**Comment by jvishnuvardhan** [comment] 2019-09-13 16:08
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-09-13 16:08 UTC
Labels: TF 1.14, comp:gpu, type:support
