### ISSUE TITLE
TF 2.3 concrete function spec issue: list index out of range

### ISSUE THREAD

**Issue by 1duo** [tensorflow/tensorflow#43436] opened 2020-09-21 22:05 UTC
In TF 2.3, if we define a model in `class`, it errors out with following error when run predict:

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _structured_signature_check_arg_types(self, args, kwargs)
   1778     arg_specs, kwarg_specs = self.structured_input_signature
   1779     for i, (arg, spec) in enumerate(zip(args, arg_specs)):
-> 1780       name = self._function_spec.arg_names[i]
   1781       self._structured_signature_check_arg_type(arg, spec, name)
   1782     for (name, arg) in kwargs.items():

IndexError: list index out of range
```

Here's a small code sample to reproduce this issue:

https://colab.research.google.com/drive/1TukOd1vtYYtO5UrCYXl3VebAhcYZNYcc#scrollTo=uerkKqrPnTBg&uniqifier=1

Note: this issue is **only in TF 2.3** if you change the TF version (first line) to `!pip install tensorflow==2.2`. This code snippet runs without any issue.

**Comment by amahendrakar** [comment] 2020-09-22 11:22
Was able to reproduce the issue. Works with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/f4499bbb57bf5c7af7507f3d1b7b9ff1/43436-2-2.ipynb).

However, running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/18e4a2cf7f935116c92c5dc67bf884bd/43436-2-3.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/fed519acd4c2cffe7d448f470088d657/43436-tf-nightly.ipynb) throws an error stating `IndexError: list index out of range`. Please find the attached gist. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-09-22 22:50
@1duo I changed arguments of the class as shown below and it works as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1927d4020185c200a65aea20fbb4561e/43436-tf-nightly.ipynb). Thanks!

```
class MyModel(tf.Module):
    @tf.function(input_signature=[tf.TensorSpec(shape=(), dtype=tf.float32), tf.TensorSpec(shape=(), dtype=tf.float32)])
    def add(self, x,y):
        return tf.math.add(x,y)
```

**Comment by 1duo** [comment] 2020-09-23 03:30
Thanks for the reply! I'm fine with the workaround but ideally * args should work, isn't it? Feel free to close it you think its not an issue.

**Comment by jvishnuvardhan** [comment] 2020-09-26 16:32
@1duo Agree with you. We have updated the code and I cannot reproduce with `tf-nightly`. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/45bfd6d184703023f6b54013317954e3/43436-tf-nightly.ipynb).

Thanks for creating this issue. I am closing this issue as this was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2020-09-26 16:32 UTC
Labels: TF 2.3, comp:core, regression issue, type:bug
