### ISSUE TITLE
Tensorflow with MKL Very Slow

### ISSUE THREAD

**Issue by zealthinker** [tensorflow/tensorflow#22212] opened 2018-09-11 13:17 UTC
I am trying to reduce the time taken by an LSTM model using MKL. I use Tensorflow 1.10.0. I have give information about configuration I am using below. It will be great, if you can help me improve the speed of my model. Please let me know what more information you need. Thanks a lot!

CPU make and model (try lscpu; if your lscpu does not list CPU flags,
try running cat /proc/cpuinfo | grep flags | sort -u)
flags	: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt ida

OS version (uname -a)
Linux ip-172-31-24-72 4.14.67-66.56.amzn1.x86_64 #1 SMP Tue Sep 4 22:03:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Compiler version (gcc --version)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

os.environ['OMP_NUM_THREADS'] = '32'
os.environ['KMP_BLOCKTIME'] = '0'
os.environ['KMP_AFFINITY'] = 'granularity=fine,verbose,compact,1,0'
K.set_image_data_format('channels_first')
config = tf.ConfigProto()
config.inter_op_parallelism_threads = 1
config.intra_op_parallelism_threads = 32
session = tf.Session(config=config)
K.set_session(session)

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
No

- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
1.10.0

- **Python version**:
2.7

- **Bazel version (if compiling from source)**:
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo

- **CUDA/cuDNN version**:
None

- **GPU model and memory**:
None

**Comment by tensorflowbutler** [comment] 2018-09-12 00:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
Exact command to reproduce

**Comment by ezhulenev** [comment] 2018-09-12 20:27
`config.inter_op_parallelism_threads = 1` doesn't seem right to me. Can you try with 16/32?

**Comment by ymodak** [comment] 2018-09-13 01:10
@drpngx Can you please take a look at this issue?. My initial investigation tells me that currently MKL-DNN supports CNN models for high performance computation whereas it requires additional effort for speeding up LSTM models which is yet to be completed. Probably you can guide me better here.

**Comment by ymodak** [comment] 2018-09-13 01:15
@zealthinker Can you please post your observations from @ezhulenev  suggestion whenever you get a chance?

> `config.inter_op_parallelism_threads = 1` doesn't seem right to me. Can you try with 16/32?

**Comment by tensorflowbutler** [comment] 2018-09-28 12:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 21:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 21:17 UTC
Labels: stat:awaiting response

**Comment by hhbyyh** [comment] 2018-10-10 21:50
Tested on Tensorflow 1.10.0 and tensorflow built with MKL is slower with LSTM. I updated 
```
config.inter_op_parallelism_threads, config.intra_op_parallelism_threads
```
with difference combination and could not see significant improvement.

**Comment by ymodak** [comment] 2018-10-10 23:35
@hhbyyh  Can you please create a new issue for this? You can mention this issue number in your new issue as well, so that we know the context as well. Thanks!

**Comment by zyndagj** [comment] 2019-06-11 15:25
I've noticed the same thing on Tensorflow v1.13.1

After discovering the `TF_DISABLE_MKL` flag, I found that disabling the Intel MKL on my LSTM model doubles the performance on both Haswell and Skylake architectures.
