### ISSUE TITLE
Convert Keras to tflite

### ISSUE THREAD

**Issue by DurgaArunkumarSmitiv** [tensorflow/tensorflow#29794] opened 2019-06-14 12:07 UTC
I tried converting my keras file to tflite file .But facing below issue 

java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 30000 bytes and a ByteBuffer with 602112 bytes.

**used below code in colab**

from tensorflow.contrib import lite
converter = lite.TFLiteConverter.from_keras_model_file( 'plano.h5')
tfmodel = converter.convert()
open ("plano_tensor_colab.tflite" , "wb") .write(tfmodel)

New to tensor flow .Please help how to convert keras to tensorflowlite.

**Comment by KabirKwatra** [comment] 2019-06-15 22:44
This Code seems to work in colabs:
```python
import tensorflow as tf
# create model
base_model = tf.keras.applications.MobileNetV2(input_shape=(160, 160, 3),
                                               include_top=False, 
                                               weights='imagenet')
# compile model
base_model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001), 
              loss='binary_crossentropy', 
              metrics=['accuracy'])
# save keras model
base_model.save('plano.h5')

# convert model
converter = tf.lite.TFLiteConverter.from_keras_model_file( 'plano.h5')
converter.allow_custom_ops=True
tfmodel = converter.convert()
open ("plano_tensor_colab.tflite" , "wb") .write(tfmodel)
```

**Comment by suharshs** [comment] 2019-06-17 06:01
@KabirKwatra 's answers seems right. 

Also the error seems to not be coming from the tflite converter?  If this is still an issue, could you provide more info on how to reproduce the error please? Thanks!

**Comment by rajat-1994** [comment] 2019-06-17 11:59
@DurgaArunkumarSmitiv I think the issue is with input/output shape. Input layer's shape of model is not equal to the input shape of the input your the passing to the model

**Comment by gadagashwini** [comment] 2019-06-24 06:04
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-24 06:04 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by akinpelu746** [comment] 2019-08-08 04:02
I want to convert my keras model into a tf lite file.
this is my code

import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.h5') # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' )
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what can I do?

**Comment by rajat-1994** [comment] 2019-08-08 06:24
You have saved your model with input shape (None, None,3), tflite wants some input shape. You have to change your Input layer of your model, say (299,299,3), then save as .h5 file and then convert that file to tflite.

**Comment by akinpelu746** [comment] 2019-08-08 06:55
I already specified the image height and width to be 299. so I expected (299,299,3) as input 
how  will I do that in the code?


def create_img_generator():
    return ImageDataGenerator(
    preprocessing_function = preprocess_input,
    rotation_range=30,
    width_shift_range = 0.2,
    height_shift_range=0.2,
    shear_range = 0.2,
    zoom_range=0.2,
    horizontal_flip=True)

Image_width,Image_height = 299,299
Training_Epochs = 5
Batch_Size = 32
Number_FC_Neurons = 1024

train_dir = r'/content/tomato/train'
validate_dir = r'/content/tomato/validate' 

num_train_samples = get_num_files(train_dir)
num_classes = get_num_subfolders(train_dir)
num_validate_samples = get_num_files(validate_dir)

num_epoch = Training_Epochs
batch_size = Batch_Size

train_image_gen = create_img_generator()
test_image_gen = create_img_generator()

train_generator = train_image_gen.flow_from_directory(
train_dir,
target_size=(Image_width,Image_height),
batch_size=batch_size,
seed=42
)

validation_generator = train_image_gen.flow_from_directory(
validate_dir,
target_size=(Image_width,Image_height),
batch_size=batch_size,
seed=42
)
x=InceptionV3_base_model.output
x= GlobalAveragePooling2D()(x)
x=Dense(Number_FC_Neurons,activation='relu')(x)
predictions = Dense(num_classes,activation='softmax')(x)

model=Model(inputs=InceptionV3_base_model.input,outputs=predictions)

history_transfer_learning = model.fit_generator(
 train_generator,
 epochs=num_epoch,
 steps_per_epoch = num_train_samples // batch_size,
 validation_data = validation_generator,
 validation_steps = num_validate_samples // batch_size,
 class_weight ='auto'
 )

**Comment by rajat-1994** [comment] 2019-08-08 07:49
InceptionV3_base_model = keras.applications.inception_v3.InceptionV3(include_top=False,weights='imagenet', input_shape=(299,299,3))

x=InceptionV3_base_model.output
x= GlobalAveragePooling2D()(x)
x=Dense(Number_FC_Neurons,activation='relu')(x)
predictions = Dense(num_classes,activation='softmax')(x)

model=Model(inputs=InceptionV3_base_model.input,outputs=predictions)
