### ISSUE TITLE
tf.matrix_inverse() is slow compared to numpy.linalg.inv

### ISSUE THREAD

**Issue by kzk2000** [tensorflow/tensorflow#221] opened 2015-11-14 17:12 UTC
Running this snippet
```
import numpy as np
import scipy as sp
from datetime import datetime
import tensorflow as tf

s = tf.Session()
dim = 3000
mat = tf.random_uniform((dim,dim))
s.run(tf.initialize_all_variables())
matinv = tf.matrix_inverse(mat)
st = datetime.now()
s.run(matinv)
print "time elapsed tensorflow:", datetime.now() - st

st = datetime.now()
x = np.random.rand(dim,dim)
sp.linalg.inv(x)
print "time elapsed scipy:     ", datetime.now() - st
```
yields this output
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:643] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
time elapsed tensorflow: 0:00:18.078232
time elapsed scipy:      0:00:01.613825
```

**1.6 sec (Scipy)  vs. ~18 sec (tensorflow), that's a huge difference.**

* Is this expected behavior?
* Why is TensorFlow so slow when inverting a matrix? I was hoping it leverages the GPU.
* Is there a way to improve the TensorFlow runtime duration?

**Comment by vrv** [comment] 2015-11-14 17:29
matrix_inverse unfortunately is not yet implemented on GPU, but some of the other operations are, so I suspect there's some amount of memory copying.  MatrixInverse on CPU is just calling Eigen::FullPivLU: https://github.com/tensorflow/tensorflow/blob/d6357a5849db980df51d00d8a9ff874cda2faeb3/tensorflow/core/kernels/matrix_inverse_op.cc#L50, so the optimizations probably have to be made at that level.

(We also don't distribute our binary package using avx/avx2 optimizations so they can run on more platforms, so it's possible things might run faster when running from source and building with more optimizations for your platform).

**Comment by kzk2000** [comment] 2015-11-14 17:42
Thanks for the quick reply. I guess I just have to wait a bit.

Is there a road map link to see which issues will be resolved / new features will added first the next weeks?

**Comment by vrv** [comment] 2015-11-14 18:04
We're still going through all of these issues and prioritizing, so we don't have a roadmap ready yet.

Once we are more able to accept external contributions, improvements like these from the community are welcome!  A quick search suggests that cublas has a matrix inversion function that might be appropriate.  Eager contributors should discuss with us here or on the discussion mailing list to figure out the best way to integrate such a change.

Renaming the title of this issue accordingly!

**Comment by girving** [comment] 2015-11-14 20:17
I'm not sure the CPU vs. GPU aspect is the only issue, since I'd be surprised if scipy used the GPU for matrix inverse.

**Comment by vrv** [comment] 2015-11-14 20:56
Indeed, even on CPU it's slow.  Should this bug just be the catch-all for now?

**Comment by delip** [comment] 2015-11-14 21:00
That (slowness on CPU) was my observation too. But I'm not sure if this a bug or an enhancement until we have some profile data.

**Comment by panmari** [comment] 2015-11-17 10:01
I guess this was fixed by 04f1932f053dd7865b191719b33860270461943a, I get now the following output to your benchmark:

time elapsed tensorflow: 0:00:04.545141
time elapsed scipy:      0:00:07.803832

**Comment by delip** [comment] 2015-11-17 18:13
This is great. I can confirm this too from my latest build.

Before:
```
time elapsed tensorflow: 0:01:13.776929
time elapsed scipy:      0:00:00.913324
```
After git pull & rebuild:
```
time elapsed tensorflow: 0:00:02.835981
time elapsed scipy:      0:00:00.844610
```

**Comment by girving** [comment] 2015-11-17 23:14
Hmm, one of the measurements says tensorflow is twice as fast, the other says it is three times as slow.  @delip: Is it still consistently 3x slower for you?

**Comment by delip** [comment] 2015-11-18 03:23
I ran this 10 times making sure no other compute heavy jobs were running. I see this consistently 3x slower than scipy, but still a dramatic improvement from the earlier slowness (>1min). My env is OSX El Capitan on iMac 5K. Running this in CPU only mode (GPU is not supported in my env). I'm pasting the timing from individual runs here:

https://gist.github.com/delip/b4b1ae1c273f2895a78a

**Comment by girving** [comment] 2015-11-18 06:47
Thanks for confirming @delip!  We should leave the bug open until the gap is better understood (and ideally closed).   Could I have your script to reproduce?

**Comment by delip** [comment] 2015-11-18 15:24
@girving, It's the same script as one used by the OP (@kzk2000) -- see first post in the issue. Is it possible that this gap exists only in OSX? Running this on other CPU-only environments (that I don't have access to at the moment), could further narrow the scope of this bug.

**Comment by vrv** [comment] 2016-02-19 07:34
@girving: are we still looking at this? worth keeping open?

**Comment by girving** [comment] 2016-02-22 18:42
I'll check this once I get tensorflow building on my Mac.

**Comment by girving** [comment] 2016-02-22 23:16
@rmlarsen: Vijay and I are getting around 40% slower than scipy with this benchmark.  Turning off the symmetry checking made no difference.  We're dramatically closer to good than we were at the beginning of this bug, but I'll leave it up to you whether we should close it or do further investigation.

**Comment by vrv** [comment] 2016-04-29 15:42
Closing this since there's been no activity on this for a while -- 40% slower on OS X for matrix_inverse isn't great, but suffices for now.  Looks like we're faster on other platforms so, there's always that.

**Closed by vrv** 2016-04-29 15:42 UTC
Labels: enhancement

**Comment by alexmonroe87** [comment] 2016-08-19 05:30
Has this op been implemented for the GPU?

**Comment by rpagliarix** [comment] 2016-09-30 11:00
Had this been implemented on GPU?

**Comment by swertz** [comment] 2017-08-03 16:12
Hello! Any news on this regarding GPU implementation?

**Comment by fxsuper** [comment] 2017-11-02 13:41
+1 for GPU implementation

**Comment by JeremyFxx** [comment] 2018-02-08 21:21
I think the tf.matrix_inverse() is already implemeted on GPU.

I run this benchmark on my laptop with 1060 Ti 6GB and get the following results:

time elapsed tf.matrix_inverse: 0:00:00.561071
time elapsed sp.linalg.inv:     0:00:02.610363

**Comment by umairbinmansoor** [comment] 2020-10-12 14:50
Hello guys,
My simple question is that why the Matlab running on my laptop (Intel, core i5, 8G ram) computes the inverse faster as compared to the Google TPU. Code attached...
Matlab code:
    A = rand(3000,3000);
    tic
    inv(A);
    t = toc;
    disp(t)
**Output:**
    **1.1297**

Python code:
import numpy as np
import scipy as sp
import timeit
import tensorflow as tf

dim = 3000
mat = tf.random.uniform(shape=(dim,dim))

st = timeit.default_timer()
tf.linalg.inv(mat)
print("time elapsed tensorflow:", timeit.default_timer() - st)

x = np.random.rand(dim,dim)
st = timeit.default_timer()
np.linalg.inv(x)
print("time elapsed scipy:     ", timeit.default_timer() - st)

**Output:**
time elapsed tensorflow: 1.3009283419999065
time elapsed scipy:      2.618305011000075
