### ISSUE TITLE
Keras predict is slow on first call when using variable input shape

### ISSUE THREAD

**Issue by ironbar** [tensorflow/tensorflow#39458] opened 2020-05-12 14:07 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Collab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla K80  11441MiB

**Describe the current behavior**

When using a variable input shape the first prediction for a new shape is slow. Following predictions for the same shape are fast. 

**Describe the expected behavior**

I would expect to see the same speed when the change in shape is small. 

**Standalone code to reproduce the issue**

This simple collab shows the problem using a ResNet50.

https://colab.research.google.com/drive/1s2-O_cRtwL_kkk2Mm-rq-xiDHdZDs5h4?usp=sharing

I notice that a warning about retracing is shown, but I don't know how to use that information to solve the problem

**Comment by ravikyram** [comment] 2020-05-13 06:11
@ironbar 

I have tried in colab with TF version 2.2 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/426f74f97a61df3e3b0b530f97fd2a1d/untitled884.ipynb)Thanks!

**Comment by ironbar** [comment] 2020-05-22 10:26
Hi @ymodak , any update on this?
Thanks

**Comment by ironbar** [comment] 2020-07-13 12:13
Hi @tomerk, any update on this?
Thanks

**Comment by tomerk** [comment] 2020-07-13 22:46
Hi @ironbar are you seeing this with the 2.3 RC?

Keras uses a `tf.function` to speed up `model.predict` calls. By default `tf.function` runs w/ experimental_relax_shapes=False:

https://www.tensorflow.org/api_docs/python/tf/function?version=nightly

This means that the tf.function will retrace every time it sees a new input shape. If experimental_relax_shapes is set to True, tf.function will attempt to make more general traces if it ends up seeing similar but slightly different shapes.

However, in 2.3 Keras should be running with `experimental_relax_shapes=True` when it wraps the internals in a tf.function.

**Comment by ironbar** [comment] 2020-07-14 08:03
Hi, 
Thanks for the hint. The problem persists but the difference is smaller.

tensorflow==2.2.0
![image](https://user-images.githubusercontent.com/8016697/87400456-1fb81200-c5b9-11ea-8e02-f224dca34207.png)

tensorflow==2.3.0rc1
![image](https://user-images.githubusercontent.com/8016697/87400416-10d15f80-c5b9-11ea-9675-4905063eea8f.png)

**Comment by kaiyu-tang** [comment] 2020-07-23 08:28
I have the same issue, If there is annoy know how to fix it?

**Comment by kaiyu-tang** [comment] 2020-07-23 08:34
model._make_predict_function()  may make sense

**Comment by tomerk** [comment] 2020-08-05 23:03
Hi @ironbar the experimental_relax_shapes lazily relaxes shapes as it sees them, so it may still take a few examples of different shapes to fully relax.

If you manually wrap your `model.call` with a `tf.function` and call your model directly instead of `predict`ing, you can directly specify the`input_signature` arg to match your data:
tensorflow.org/api_docs/python/tf/function

This will allow your tf.function to trace only once at the start, instead of lazily figuring out the input shapes from your data.

Closing this issue for now, but +@rohan100jain because this is related to some past discussions about whether tf.function should trace more generally at the start before tracing more specific shapes.

**Closed** 2020-08-05 23:04 UTC
Labels: TF 2.2, comp:keras, type:performance
