### ISSUE TITLE
tensorflow latency 2-3x worse with multiple input tensors

### ISSUE THREAD

**Issue by patelprateek** [tensorflow/tensorflow#30816] opened 2019-07-17 18:46 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12, 1.11, 1.13
- Python version: 2.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a (but 4.8)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have trained a model and then i 2 versions of frozen graph .
1) version 1 : single placeholder which takes in tfexample and rune the ParseExample operator and does inference
2)Version 2 : instead of single placeholder , i have about ~300 placeholders . one placholder per feature (i.e since the features are already parsed , i do not create tfexample , but rather feed in individual tensors i.e a feed dictionalry where for each feature column i feed in the respective tensor)

The number of ops in both graphs are approximately same (multiple placeholders being slightly less ) ~5-6k ops/nodes

Latency of version 2 is 2-3x higher then version 1 

**Describe the expected behavior**

Expected behavior is latency when i parse the feature before hand and feed in per feature tensor , there is lesser work for tensorflow to do , so it should be faster or at worse the same ? why do we observe 2-3x higher latency ?

is this due to the way feed dictionary gets copied from python to c++ ?

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment] 2019-07-18 10:26
@patelprateek ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by anush-o** [comment] 2019-07-24 09:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by anush-o** 2019-07-24 09:26 UTC
Labels: comp:ops, stat:awaiting response, type:support
