### ISSUE TITLE
www.tensorflow.org/versions/ incorrectly lists 0.12 as the most recent stable branch

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#9872] opened 2017-05-13 00:32 UTC
https://www.tensorflow.org/versions/ says that 0.12 is most recent stable branch, which is causing new users to install the older version --
https://github.com/tensorflow/tensorflow/issues/9590#issuecomment-301211285

**Comment by jubjamie** [comment] 2017-05-15 14:02
Duplicate of #8429
Was raised a while ago but no traction just yet!

**Comment by skye** [comment] 2017-05-15 15:11
Closing as duplicate.

**Closed by skye** 2017-05-15 15:11 UTC
Labels: type:docs
