### ISSUE TITLE
Bug in person_detection tf-lite example 

### ISSUE THREAD

**Issue by xieydd** [tensorflow/tensorflow#34720] opened 2019-11-30 14:42 UTC
tf==1.15
I just follow the step in [person_detection example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/examples/person_detection/training_a_model.md), after i get `vww_96_grayscale_frozen.pb`, when i want to generate `vww_96_grayscale_quantized.tflite`, I get a error `ValueError: Cannot set tensor: Dimension mismatch`, can you see it  @dansitu 

```
Traceback (most recent call last):                                                                    
  File "get_tflite.py", line 32, in <module>                                                          
    tflite_quant_model = converter.convert()                                                          
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 993, in conv
ert                                                                                                   
    inference_output_type)                                                                            
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 239, in _cal
ibrate_quantize_model                                                                                 
    inference_output_type, allow_float)                                                               
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/calibrator.py", li
ne 75, in calibrate_and_quantize                                                                      
    self._calibrator.FeedTensor(calibration_sample)                                                   
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wr
ap_calibration_wrapper.py", line 112, in FeedTensor                                                   
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value) 
ValueError: Cannot set tensor: Dimension mismatch
```

**Comment by dansitu** [comment] 2019-12-02 23:31
@MeghnaNatraj, can you take a look?

**Comment by MeghnaNatraj** [comment] 2019-12-09 16:53
I'm currently looking into this issue and I'll post an update soon.

**Comment by MeghnaNatraj** [comment] 2019-12-09 18:24
I was able to reproduce the issue. The reason that you're currently facing this issue is because of a [pending PR](https://github.com/tensorflow/models/pull/7609/commits) to merge the greyscale changes. As a result of this, the current code does not utilize the `--input_greyscale` flag and the model only accepts RGB/color images. To verify this, you can visualize the `vww_96_grayscale_frozen.pb1` file by uploading it to [netron](https://lutzroeder.github.io/netron/) to see the dimensions of the input which is: (batch=?, height=96, width=96, num_channels=3)

_Note: Netron is a useful tool for visualizing many other model formats as well, source: [https://github.com/lutzroeder/netron](https://github.com/lutzroeder/netron)_

Until the PR is merged, with a temporary fix, you can train a person_detection model that accepts color images by making two updates while converting the `vww_96_grayscale_frozen.pb` file to `vww_96_grayscale_quantized.tflite` as follows: (the 2 updates are mentioned in comments below)

```
import tensorflow as tf
import io
import PIL
import numpy as np

def representative_dataset_gen():
    record_iterator = tf.python_io.tf_record_iterator(path='coco/processed/val.record-00000-of-00010')
    count = 0
    for string_record in record_iterator:
        example = tf.train.Example()
        example.ParseFromString(string_record)
        image_stream = io.BytesIO(example.features.feature['image/encoded'].bytes_list.value[0])
        image = PIL.Image.open(image_stream)
        image = image.resize((96, 96))
        image = image.convert('RGB') # Update 1: Replace'L' with 'RGB' 
        array = np.array(image)
        # array = np.expand_dims(array, axis=2) # Update 2: Comment this line as with RGB, an extra dimension is 
                                                # already present to represent the num_channels with value=3
        array = np.expand_dims(array, axis=0)
        array = ((array / 127.5) - 1.0).astype(np.float32)
        yield([array])
        count += 1
        if count > 300:
            break

converter = tf.lite.TFLiteConverter.from_frozen_graph('vww_96_grayscale_frozen.pb',
['input'], ['MobilenetV1/Predictions/Reshape_1'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen

tflite_quant_model = converter.convert()
open("vww_96_grayscale_quantized.tflite", "wb").write(tflite_quant_model)
```

The size of this model is ~260KB and not <250KB as mentioned in the tutorial as this model accepts color images. Let us know if this works for you, and we'll post an update once we get the greyscale version checked in as well.

**Comment by xieydd** [comment] 2019-12-10 01:48
@MeghnaNatraj Thanks for your Detailed explanation， i will try after the pr merged;
Now my compromise solution is:
```
delete the line # image = image.convert('L')
and # array = np.expand_dims(array, axis=2)
```

**Comment by petewarden** [comment] 2019-12-19 20:33
Sorry for the problems! I looked into the PR, and we did merge the changes through a separate mechanism, though the flag is now called `use_grayscale` instead of `input_grayscale`:
https://github.com/tensorflow/models/blob/master/research/slim/eval_image_classifier.py#L133

Does specifying that help?

**Comment by MeghnaNatraj** [comment] 2020-02-06 16:34
Closing the issue as it is resolved.  Either a user can update the training instructions by replacing `use_grayscale` with `input_grayscale` OR the user can update the inference instructions by the solution posted earlier in this page.

**Closed by MeghnaNatraj** 2020-02-06 16:34 UTC
Labels: TF 1.15, comp:lite, comp:micro, type:bug
