### ISSUE TITLE
can not import tensorflow 

### ISSUE THREAD

**Issue by zsxgb** [tensorflow/tensorflow#8774] opened 2017-03-28 11:14 UTC
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: zsx-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libnvidia-fatbinaryloader.so.375.39: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally

**Comment by zsxgb** [comment] 2017-03-28 11:17
https://github.com/tensorflow/tensorflow/issues/6233
I have a similar problem
The last time, as if to change a setting, the problem was solved. Six months later, I found that the problem came again.
I found my question from google, carefully read every answer, I still have no way to solve this problem and disappear, is random Mody I used the good, suddenly appeared again

**Comment by gunan** [comment] 2017-03-28 18:23
You can find where your libcuda.so.1 is located, and add it to your `LD_LIBRARY_PATH` to resolve this problem. You can find where the library is using the "find" command in your terminal.

Closing the issue as it is clearly a user side setup issue, not a bug in TF.
For problems with your own setup, I recommend using StackOverflow.

**Closed by gunan** 2017-03-28 18:23 UTC

**Comment by zsxgb** [comment] 2017-03-29 02:55
I can find this file, but I did not add it to the path. The way I do this is to copy this file to LD_LIBRARY_PATH, which is a link file. Added a link to this copied file. Still being given. I try your way. May be.
