### ISSUE TITLE
2.10.0 cuBLAS error

### ISSUE THREAD

**Issue by Mollylulu** [tensorflow/tensorflow#57663] opened 2022-09-11 04:16 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 7.5.0-3ubuntu1~18.04

### Python version

3.8.0

### GCC/Compiler version

gcc 7.5.0

### CUDA/cuDNN version

NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0

### Current Behaviour?

```shell
I use `pip` to install tensorflow-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. After installation, when I import tensorflow, there is an error:
`E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered.
I noticed this is an error that occurred before and has an issue closed. But I install the latest 2.10.0 version tf and still meet this error. hope you can help me figure it out. thanks!
```

### Standalone code to reproduce the issue

```shell
pip install tensorflow-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

### Relevant log output

```shell
In [1]: import tensorflow as tf
2022-09-11 03:59:51.293241: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-11 03:59:51.436444: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-11 03:59:51.474370: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
```
```
</details>

**Comment by tilakrayal** [comment] 2022-09-12 08:11
@Mollylulu,
Could you please confirm whether you are trying to build the tensorflow from the official doc [link](https://github.com/tensorflow/tensorflow/tree/v2.10.0). Thank you!

**Comment by mazar** [comment] 2022-09-12 19:58
I see the same error with TensorFlow 2.10.0 on Ubuntu 22.04, installed using PIP. Downgrading to 2.9.2 resolves this error.
This error can be seen all over TensorFlow documentation site, e.g.: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras

<img width="960" alt="Screen Shot 2022-09-12 at 12 57 59 PM" src="https://user-images.githubusercontent.com/242569/189744480-6381d39a-4514-48ec-85b4-f48ae01aef86.png">

**Comment by claytonparnell** [comment] 2022-09-12 23:31
From AWS SageMaker, we are trying to [update sagemaker-tensorflow-extensions to support TF 2.10.0](https://github.com/aws/sagemaker-tensorflow-extensions/pull/144), but are seeing this same error and it is blocking us from releasing the update.

**Comment by mihaimaruseac** [comment] 2022-09-13 18:03
#57679 and #57671 as duplicates

**Comment by Mollylulu** [comment] 2022-09-14 10:26
> ```shell
> tensorflow-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> ```

I did not build from the repo, instead, I download the `tensorflow-2.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` from [Pypi](https://pypi.org/project/tensorflow/#files) and then use command `pip install xxx.whl` to install tf2.10.0.

**Comment by Mollylulu** [comment] 2022-09-15 03:18
> That is the same as `pip install tensorflow`, pip selects the corresponding wheel from PyPI :)

yep, since the pkg is big, I download it manually. My point is how to solve aforementioned error, though :)

**Comment by mihaimaruseac** [comment] 2022-09-15 15:49
That makes sense.

Regarding the error, it's mostly a warning to give notice about an incompatibility. If the code still works properly, I would not worry too much about it. If not, #57679 and #57671 as duplicates might also have more stuff. Maybe we could coagulate all of these in one bigger issue in that case.

**Comment by agkphysics** [comment] 2022-09-16 03:24
It seems that https://github.com/tensorflow/tensorflow/pull/56691 fixes the `Unable to register cuBLAS factory` error. I was able to successfully build TensorFlow using that patch.

**Comment by mufaddal-rohawala** [comment] 2022-09-20 20:09
The patch https://github.com/tensorflow/tensorflow/pull/56691 is not released yet for tensorflow 2.10.0, @trevor-m is there a plan for release?

**Comment by mihaimaruseac** [comment] 2022-09-20 20:17
Unless there is a cherrypick for 2.10 (and a 2.10.1 patch release), #56691 will only be included in 2.11 and later

**Comment by sachinprasadhs** [comment] 2022-09-20 23:42
@Mollylulu , Could you please refer the above comment and close this issue. Thanks!

**Comment by mihaimaruseac** [comment] 2022-09-21 00:55
Don't close this issue, this is a regression. Should be closed only when 2.11 is released with the fix

**Comment by reedwm** [comment] 2022-09-29 00:23
I can only comment on the log message

> 2022-09-28 17:14:40.865705: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

This log message is fixed by https://github.com/tensorflow/tensorflow/pull/56691, but as noted, it is not included in TF 2.10. The log message does not indicate any issues. Technically, without the PR, I think undefined behavior in C++ occurs due to ODR violations, but since all tests are passing, I doubt this is causing any issues in practice other than the log message.

@rishikasinha-tf, would it be possible to include the PR in a TF 2.10.1 release? The log message is confusing as it (incorrectly) implies that an error has occurred that would prevent TF from running correctly.

**Comment by rishikasinha-tf** [comment] 2022-09-29 18:23
Hi @reedwm thanks for the analysis, let me quickly check to see which kind of release will best address this issue. Thanks

**Comment by rishikasinha-tf** [comment] 2022-09-29 23:31
Hi @reedwm. We have decided to include this in the TF 2.11 release, whose branch cut is on Oct 13th. Let me know if you see a risk with that. Thanks!

**Comment by angelcampoverde** [comment] 2022-09-30 06:26
Hi,

> That makes sense.
> 
> Regarding the error, it's mostly a warning to give notice about an incompatibility. If the code still works properly, I would not worry too much about it. If not, #57679 and #57671 as duplicates might also have more stuff. Maybe we could coagulate all of these in one bigger issue in that case.

If it is not really a problem and can be ignored, then it should not even be an error, but a warning or just an info message. Is there a way to hide this error?

**Comment by mihaimaruseac** [comment] 2022-10-12 17:52
> @rishikasinha-tf, would it be possible to include the PR in a TF 2.10.1 release? The log message is confusing as it (incorrectly) implies that an error has occurred that would prevent TF from running correctly.

Please send a cherrypick PR for `r2.10` too to fix the error message. See [go/tf-release/cherrypick](https://goto.google.com/tf-release/cherrypick) (internal link)

**Comment by donglinz** [comment] 2022-10-24 11:56
Is cherrypick in r2.10? This error still blocks building from the source with r2.10 branch.

**Comment by donglinz** [comment] 2022-10-27 11:53
@rishikasinha-tf @mihaimaruseac Kindly ping... This issue is still present on the latest r2.10 branch. commit: 829f9ebd6bf7fa9ce4fb7e79c0142bda3cadc134

**Comment by rishikasinha-tf** [comment] 2022-10-28 20:56
Hi @donglinz. thanks for the reminder. While I look to check if it has been merged in 2.10, I recommend using the 2.11.0-rc1 for the testing.

**Comment by sachinprasadhs** [comment] 2022-12-03 22:18
Could you please refer the comment here https://github.com/tensorflow/tensorflow/issues/57679#issuecomment-1335662469 and close the issue, the issue doesn't seem to appear in tf-nightly, attached gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/08e909611e412c80940a2212474e876a/multi_worker_with_keras.ipynb) for reference. Thanks!

**Closed** 2022-12-17 23:12 UTC
Labels: stat:awaiting response, type:build/install, stalled, subtype: ubuntu/linux, TF 2.10

**Comment by mrduhart** [comment] 2023-10-10 01:41
This issue is still appearing when I install tensorflow[and-cuda] using poetry. It is installing the 2.14 version.

**Comment by Amyy** [comment] 2023-11-20 13:29
> This issue is still appearing when I install tensorflow[and-cuda] using poetry. It is installing the 2.14 version.

It is also still appearing in tensorflow 2.15 - had to downgrade to tensorflow 2.9 to get rid of that error.

**Comment by maulberto3** [comment] 2023-11-24 04:11
> > This issue is still appearing when I install tensorflow[and-cuda] using poetry. It is installing the 2.14 version.
> 
> It is also still appearing in tensorflow 2.15 - had to downgrade to tensorflow 2.9 to get rid of that error.

Same here.

**Comment by GautamSinghania** [comment] 2024-12-12 06:23
Same here
