### ISSUE TITLE
Convert savedmodel to h5 Keras format - AttributeError: 'AutoTrackable' object has no attribute 'summary'

### ISSUE THREAD

**Issue by dfvr1994** [tensorflow/tensorflow#42425] opened 2020-08-17 07:18 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.1

**Describe the current behavior**
I used Google AI-Platform to train a model for object detection. The result is a model in the savedmodel format. I wan't to convert it to h5 Keras format so I can import into Matlab. 

**Standalone code to reproduce the issue**
Here is the output folder directly from the bucket:

https://drive.google.com/file/d/1mgVGG_WNGC9gxZSgn1G2_YdQTVkJJInM/view?usp=sharing

**Other info / logs** 

I tried to do this:

`New_Model = load_model('model')`, or this `New_Model = tf.keras.models.load_model('model')` or this `New_Model = tf.saved_model.load(export_dir='model')` and lastly this `New_Model.summary()` and I always get the same error: 

`AttributeError: 'AutoTrackable' object has no attribute 'summary'`

If the model would had loaded correctly I would try to do `tf.keras.models.save_model(New_Model, 'New_Model.h5')`

Which will end up throwing this error:

`AttributeError: 'AutoTrackable' object has no attribute '_is_graph_network'`

Please help, as I said the model is saved in the savedmodel format, so I guess every piece needed is there

Complete log for summary:

```
2020-08-17 01:48:46.011995: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-17 01:48:46.016769: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-08-17 01:48:53.754437: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-08-17 01:48:53.758821: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-17 01:48:53.780897: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: EC2347417W3
2020-08-17 01:48:53.785702: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: EC2347417W3
2020-08-17 01:48:53.789520: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-17 01:48:53.820077: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x16799c381d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-17 01:48:53.832027: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/conv2d/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_variance:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/conv2d/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_variance:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/conv2d/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_variance:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/conv2d/kernel:0' shape=(7, 7, 3, 64) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/gamma:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/beta:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_mean:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'resnet50/batch_normalization/moving_variance:0' shape=(64,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
Traceback (most recent call last):
  File "savedmodel_to_h5.py", line 15, in <module>
    New_Model.summary()
AttributeError: 'AutoTrackable' object has no attribute 'summary'

```

**Comment by amahendrakar** [comment] 2020-08-17 12:41
@dfvr1994,
I am not able to access the file as I do not have the required permissions. 

Also, could you please provide the code you are running to convert the model. Thanks!

**Comment by amahendrakar** [comment] 2020-08-17 12:49
@dfvr1994,
Please take a look at [this](https://stackoverflow.com/a/58757328) similar StackOverflow issue and let us know if it helps. Thanks!

**Comment by dfvr1994** [comment] 2020-08-17 15:40
@amahendrakar I have updated permissions on the file so it can be accessed by anyone with the link. 

I'm following this steps:
https://stackoverflow.com/questions/59375679/tensorflow-pb-format-to-keras-h5

The second link you provided shows how to use the .pb model outside docker, I assume you pointed it because of what I mentioned about using the model on Matlab, which at the moment doesn't support .pb format but ONNX and h5. 

I need to transform the model into h5 format.

**Comment by amahendrakar** [comment] 2020-08-25 16:18
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/76d535b330e9047270342f58aa20fb1c/42425.ipynb#scrollTo=Jy5_OTkVVjrf). Thanks!

**Comment by DjangoPeng** [comment] 2020-08-28 12:42
Same issue could be reproduce with TF v2.2.0.

**Comment by dfvr1994** [comment] 2020-09-24 15:28
Hi, any update on this?

**Comment by DjangoPeng** [comment] 2020-09-30 07:20
I'm afraid not. @dfvr1994

**Comment by e-remington-lee** [comment] 2020-10-07 01:36
I am having the same error

**Comment by dimitraka** [comment] 2020-10-07 10:00
Did anyone manage to find a solution? Having the same issue here

**Comment by RobertJirsaraie** [comment] 2020-10-24 22:59
I am running into this issue too!

**Comment by dfvr1994** [comment] 2020-10-26 05:25
Hi @jvishnuvardhan any update on this?

**Comment by abhishekbalu** [comment] 2020-10-26 08:18
any luck on converting to h5 format

**Comment by jvishnuvardhan** [comment] 2020-10-27 01:10
@dfvr1994 I have a question. Did you save the model using `tf.saved_model.save` or 'model.save`? Thanks! If possible, please share model building code also. Thanks!

**Comment by DjangoPeng** [comment] 2020-11-03 03:13
It's not the time to close issue. 

There are many users faced the same problem crossing various versions.

**Comment by jvishnuvardhan** [comment] 2020-11-03 04:59
@DjangoPeng I removed `stalled` label, so it will not close. Thanks!

**Comment by abhishekbalu** [comment] 2020-11-03 21:07
@jvishnuvardhan I have been working on this issue for the past 2 months. I am working on Object detection models and trying to prune and compress it. This has been a major issue that I am facing in my work. I am happy to work on this problem with a little guidance. If you can help me out with understand a few concepts I will be able to pull this of.

**Comment by Ali-Parandeh** [comment] 2020-11-11 12:09
Same issue here

**Comment by k-w-w** [comment] 2020-11-13 17:57
`tf.keras.models.load_model` only works with SavedModels saved from Keras. I'm guessing that the SavedModel is saved from another source that is not Keras.

If you want to convert a SavedModel to Keras, you could try something like:

```
loaded = tf.saved_model.load(path)

class LayerFromSavedModel(tf.keras.layers.Layer):
  def __init__(self):
    super(LayerFromSavedModel, self).__init__()
    self.vars = loaded.variables
  def call(self, inputs):
    return loaded.signatures['serving_default'](inputs)

input = tf.keras.Input(...)
model = tf.keras.Model(input, LayerFromSavedModel()(input))
model.save('saved_model')
```

**Comment by DjangoPeng** [comment] 2020-11-16 01:57
@dfvr1994 Would you like to try out @k-w-w 's solution?

**Comment by dfvr1994** [comment] 2020-11-16 02:14
@DjangoPeng sure, will post results shortly

**Comment by dfvr1994** [comment] 2020-11-18 19:37
I'm getting this error: 

`Traceback (most recent call last):
  File "C:\Users\ZX776FN\Documents\out\savedmodel_to_h5.py", line 18, in <module>
    input = tf.keras.Input(...)
  File "C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\engine\input_layer.py", line 311, in Input
    input_layer = InputLayer(**input_layer_config)
  File "C:\Program Files\Python38\lib\site-packages\tensorflow\python\keras\engine\input_layer.py", line 150, in __init__
    batch_input_shape = (batch_size,) + tuple(input_shape)
TypeError: 'ellipsis' object is not iterable`

@k-w-w did you try your code with the model I uploaded at the top of the issue?

**Comment by jvishnuvardhan** [comment] 2020-11-18 20:32
@dfvr1994 What was the input for `tf.keras.Input` in your code? Can you share a standalone code to reproduce the issue? Thanks!

**Comment by dfvr1994** [comment] 2020-11-18 21:11
@jvishnuvardhan I did run this: 

```
import os
import tensorflow as tf
from tensorflow.keras.preprocessing import image

loaded = tf.saved_model.load(r"C:\Users\my_user\Documents\out\2\OUTPUT\model")

class LayerFromSavedModel(tf.keras.layers.Layer):
  def __init__(self):
    super(LayerFromSavedModel, self).__init__()
    self.vars = loaded.variables
  def call(self, inputs):
    return loaded.signatures['serving_default'](inputs)

input = tf.keras.Input(...)
model = tf.keras.Model(input, LayerFromSavedModel()(input))
model.save('saved_model')

```

Where "C:\Users\my_user\Documents\out\2\OUTPUT\model" contains: 

![image](https://user-images.githubusercontent.com/45764991/99588470-9a0a0000-29b8-11eb-9ba8-851b30866564.png)

OUTPUT contains: 

![image](https://user-images.githubusercontent.com/45764991/99588508-adb56680-29b8-11eb-84e6-cf4e83601ee5.png)

**Comment by dfvr1994** [comment] 2020-12-08 23:49
Hi, any update on this?

**Comment by yareyaredesuyo** [comment] 2020-12-19 03:47
SavedModel does not have compressed format? this is very incombinient...

**Comment by virajone** [comment] 2021-03-11 13:28
Hey, any updates on this issue ?  I've been dealing with the same problem.

**Comment by anuragtr** [comment] 2021-05-03 11:24
Same problem, unable to convert pb to h5(keras), pb file was created from an onnx file.

**Comment by rlleshi** [comment] 2021-06-16 05:25
Converting a Tensorflow model to Keras is no small feat. Some details can be found [here](https://stackoverflow.com/questions/44466066/how-can-i-convert-a-trained-tensorflow-model-to-keras).

**Comment by ats05** [comment] 2021-08-16 06:39
> `tf.keras.models.load_model`Kerasから保存されたSavedModelsでのみ機能します。SavedModelはKerasではない別のソースから保存されていると思います。
> 
> SavedModelをKerasに変換する場合は、次のような方法を試すことができます。
> 
> ```
> loaded = tf.saved_model.load(path)
> 
> class LayerFromSavedModel(tf.keras.layers.Layer):
>   def __init__(self):
>     super(LayerFromSavedModel, self).__init__()
>     self.vars = loaded.variables
>   def call(self, inputs):
>     return loaded.signatures['serving_default'](inputs)
> 
> input = tf.keras.Input(...)
> model = tf.keras.Model(input, LayerFromSavedModel()(input))
> model.save('saved_model')
> ```

In my case, this sample was worked well.

**Comment by aynesss** [comment] 2022-02-21 12:39
Same error, any solution!

**Comment by abhishekbalu** [comment] 2022-02-21 20:56
So the problem with this is due to the fact that the saved_model file is in bitstream format.  I have tried to decode it and failed multiple times. There is no known way to get layer information out of the bitstream. So if you want to recreate the model you have to use keras layers to recreate the model and then use the weights from saved_model to get the performance of the saved_model. Most common network architectures can be found in github. If you are trying to work on any specific model please let me know i can see if I can help you out.

**Comment by aynesss** [comment] 2022-02-22 08:13
@abhishekbalu  Thank you very much if you can help me!
Here is the saved_model that I use : "gs://simclr-checkpoints-tf2/simclrv1/pretrain/1x/saved_model/"
Here is a part of my code : 
```
path = "gs://simclr-checkpoints-tf2/simclrv1/pretrain/1x/saved_model/"
def create_model():
    baseModel =  tf.keras.models.load_model(path)
    baseModel.summary()   
    model_output = tf.keras.layers.Dense(3, name="head_supervised_new")(baseModel)
    model = tf.keras.Model(inputs=baseModel.input, outputs=model_output)
    model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=[tf.keras.metrics.CategoricalAccuracy()])  
    return model
model = create_model()
model.fit(train_set)
```

**Comment by dfvr1994** [comment] 2022-07-14 19:21
The model takes two inputs: encoded_image and key: 

```
loaded = tf.saved_model.load(path)
infer = loaded.signatures["serving_default"]
print(infer.structured_input_signature)
```
Which outputs: 

`((), {'encoded_image': TensorSpec(shape=(None,), dtype=tf.string, name='encoded_image'), 'key': TensorSpec(shape=(None,), dtype=tf.string, name='key')})`


I run inference by: 
```
import numpy as np
import tensorflow as tf
from skimage.io import imread

path = r"C:\Users\path\to\my\saved\model\\"
image = np.asarray(imread(r"C:\Users\path\to\my\img.png"))
loaded = tf.saved_model.load(path)

def run_inference_for_single_image(model, image):
    image = np.asarray(image)

    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image)

    # Encode the (numerical) tensor into an "encoded_image"
    encoded_image = tf.io.encode_jpeg(input_tensor)

    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    encoded_image = encoded_image[tf.newaxis,...]
    
    model_fn = model.signatures['serving_default']

    # Run inference (the SavedModel downloaded from AI platform also requires a "key" as input.)
    output_dict = model_fn(encoded_image = encoded_image, key = tf.expand_dims(tf.convert_to_tensor("test_key"), 0))
    
    print(encoded_image.shape, (tf.expand_dims(tf.convert_to_tensor("test_key"), 0)).shape)

    num_detections = int(output_dict.pop('num_detections'))
    
    print('detected objects',num_detections)
    
    return output_dict, num_detections

alo, alo_nb = run_inference_for_single_image(loaded, image)
```

I then tried: 
```
loaded = tf.saved_model.load(path)

input_tensor = tf.convert_to_tensor(tf.keras.Input(shape=(None, 3)))

# Encode the (numerical) tensor into an "encoded_image"
input_tensor =  tf.image.convert_image_dtype(input_tensor, dtype=tf.uint8)
encoded_image = tf.io.encode_jpeg(input_tensor)

model_fn = loaded.signatures['serving_default']
model = model_fn(encoded_image = tf.expand_dims(encoded_image, 0), key = tf.expand_dims(tf.convert_to_tensor("test_key"), 0))

saved_1 = tf.keras.models.save_model(model, 'success.h5')
```

Which of course fails because it is not a Keras model:

`AttributeError: 'dict' object has no attribute 'outputs'`

I then tried: 
```
class LayerFromSavedModel(tf.keras.layers.Layer):
    def __init__(self):
        super(LayerFromSavedModel, self).__init__()
        self.vars = loaded.variables
    def call(self, inputs):
        return loaded.signatures['serving_default'](inputs)

input = tf.keras.Input((None,None,))
model = tf.keras.Model(input, LayerFromSavedModel()(input))

```

Which returns: 
```
TypeError: in user code:

    File "C:\Users\dfvr1\AppData\Local\Temp\ipykernel_23372\3246415985.py", line 13, in call  *
        return loaded.signatures['serving_default'](inputs)

    TypeError: pruned(encoded_image, key) takes 0 positional arguments, got 1.
```

How can I update _LayerFromSavedModel_ now the I know the inputs for the model?

**Comment by Venkat6871** [comment] 2024-08-06 15:09
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by e-remington-lee** [comment] 2024-08-14 13:07
Yes this has been resolved, ty for reaching out!

**Comment by Venkat6871** [comment] 2024-08-26 04:23
Hi **@dfvr1994** ,
Closing this issue as the user confirmed it was resolved in the latest version. Please feel free to reopen or create a new issue if the problem persists.

**Closed** 2024-08-26 04:27 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.3
