### ISSUE TITLE
TFLite: Cannot use boolean scalar as input to TFLite model

### ISSUE THREAD

**Issue by hoavt-54** [tensorflow/tensorflow#20741] opened 2018-07-12 14:40 UTC
Edit: Adding issue template
Have I written custom code: No
OS Platform and Distribution: Ubuntu 14.04 
TensorFlow installed from: pip
TensorFlow version: r1.9
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce: tf.contrib.lite.toco_convert (More details below)

I am trying to convert the [Facenet Tensorflow](https://github.com/davidsandberg/facenet) model into `TFLITE` format which I could use for an Android app. This Facenet model takes a tensor containing image data and a boolean scalar (is_training) as input:

  `  feed_dict = { images_placeholder: images, phase_train_placeholder:False }`

I follow the [Tensorflow lite guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/mobile/tflite/devguide.md) to convert models into TFLITE format. Here is an example: 

   ```
 import tensorflow as tf
    
    img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
    val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
    out = tf.identity(val, name="out")
    
    with tf.Session() as sess:
      tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
      open("converteds_model.tflite", "wb").write(tflite_model)

```
Here is my code:

   ```
 with tf.Graph().as_default():
    
            with tf.Session() as sess:
    
                # Load the model
                facenet.load_model(args.model)
    
                # Get input and output tensors
                images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
                embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
                phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")
                #reshape as tflite does not accepts None dimension
                images_placeholder = tf.reshape(images_placeholder, [1,160,160,3])
                tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [images_placeholder, phase_train_placeholder], [embeddings])
                open("converteds_model.tflite", "wb").write(tflite_model)
```

The program gives an error saying (I guess this happens as `tflite` does not support `tf.bool` just yet):

```
    File "/.../facenet/tensorflow1.8/lib/python3.4/site-packages/tensorflow/contrib/lite/python/convert.py", line 206, in toco_convert
        input_tensor.dtype))
    ValueError: Tensors phase_train:0 not known type tf.bool

```
If I cast the `phase_train_placeholder` to the supported type `tf.int32`, just to see how it goes. Then it gives another error (I guess this happens as the convert function does not accept scalar):

 

```
File "/.../facenet/tensorflow1.8/lib/python3.4/site-packages/tensorflow/contrib/lite/python/convert.py", line 217, in toco_convert
        input_array.shape.dims.extend(map(int, input_tensor.get_shape()))
      File "/.../facenet/tensorflow1.8/lib/python3.4/site-packages/tensorflow/python/framework/tensor_shape.py", line 591, in __iter__
        raise ValueError("Cannot iterate over a shape with unknown rank.")
    ValueError: Cannot iterate over a shape with unknown rank.
```

Could you please suggest an workaround for this? I understand that TFLite is still in development but I could try to contribute this part if it is possible. Many thanks.
 
I also posted to [SO](https://stackoverflow.com/questions/51307107/tensorflow-lite-boolean-scalar-as-input-tensor); however I think this is also an issue therefore I put it here as well.

**Comment by tensorflowbutler** [comment] 2018-07-13 01:30
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jdduke** [comment] 2018-08-09 19:11
The type checking code in convert.py was relaxed in https://github.com/tensorflow/tensorflow/commit/d3931c804ce9619ac0a0c84f42b43ce70ade93a7. 

@hoavt-54 would you mind trying your conversion again? Thanks for your patience.

**Comment by tofulawrence** [comment] 2018-08-24 20:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-08-24 20:12 UTC
Labels: comp:lite, stat:awaiting response

**Comment by tensorflowbutler** [comment] 2018-08-24 21:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
