### ISSUE TITLE
[tf 1.8.0] tf.nn.swish would have issue when restoring using tf.saved_model.loader.load

### ISSUE THREAD

**Issue by pswpswpsw** [tensorflow/tensorflow#21367] opened 2018-08-03 20:54 UTC
Hi,

I found an error for tf.nn.swish for tensorflow version **1.8.0**
First, I save the model using tf.saved_model API, then I restore the model using the same API. 

It turns out to have the following error:

---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-3-a18708547b00> in <module>()
      1 sess = tf.Session(graph=tf.Graph())
----> 2 zzz = tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], 'model_saved')

/usr/local/lib/python2.7/dist-packages/tensorflow/python/saved_model/loader_impl.pyc in load(sess, tags, export_dir, **saver_kwargs)
    217 
    218     # Build a saver by importing the meta graph def to load.
--> 219     saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
    220 
    221     if saver:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1953       clear_devices=clear_devices,
   1954       import_scope=import_scope,
-> 1955       **kwargs)
   1956 
   1957   if meta_graph_def.HasField("saver_def"):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    741         name=(import_scope or scope_to_prepend_to_names),
    742         input_map=input_map,
--> 743         producer_op_list=producer_op_list)
    744 
    745     # Restores all the other collections.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.pyc in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    487         try:
    488           results = c_api.TF_GraphImportGraphDefWithResults(
--> 489               graph._c_graph, serialized, options)  # pylint: disable=protected-access
    490           results = c_api_util.ScopedTFImportGraphDefResults(results)
    491         except errors.InvalidArgumentError as e:

FailedPreconditionError: Input 0 ('swish_f32') for 'MatMul_1' was not previously added to ShapeRefiner.

# my solution

def myswish_beta(x):
    """
    Swish with beta not-traininable!
    """
    beta=tf.Variable(initial_value=1.0,trainable=False,name='swish_beta')
    return x*tf.nn.sigmoid(beta*x)
activation_fun = myswish_beta

**Comment by tensorflowbutler** [comment] 2018-08-04 06:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-08-18 18:44
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-02 18:36
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-17 18:58
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by wt-huang** [comment] 2018-09-28 21:08
@pswpswpsw Is this still an issue?

**Comment by ymodak** [comment] 2018-10-12 22:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-12 22:00 UTC
