### ISSUE TITLE
@tf.function works the first time I run the code but it fails afterwords on Spyder IDE.

### ISSUE THREAD

**Issue by spaghettix** [tensorflow/tensorflow#30290] opened 2019-07-01 21:02 UTC
PROBLEM: the first time I run my custom code (that by the way works as a charm without @tf.function on my training function) on Spyder IDE everything goes smoothly. However if I attempt a second run I get the error reported below and a huge memory leak. I thought it was important for you to know. Thanks for your amazing work and best of lucks.

TensorFlow version: 2.0.0-beta1
Eager execution: True
MacOs

**Code to reproduce the issue**

    @tf.function
    def train(self, X, Y, epochs, batch_size=None):

        iter_data = self.bake_data(X, Y, epochs, batch_size)

        for x, y in iter_data:

            with tf.GradientTape() as tape:
                Y_ = self.forward_step(x)
                loss = self.loss_fun(y_true=y, y_pred=Y_)
                cost = tf.reduce_mean(loss)

            gradients = tape.gradient(cost, self.trainable_vars)
            self.optimizer.apply_gradients(zip(gradients, self.trainable_vars))
            self.loss_history_.append(cost)

    def bake_data(self, X, Y, epochs, batch_size=None):
        data = tf.data.Dataset.from_tensor_slices((X, Y))
        if batch_size is not None:
            data = data.batch(batch_size)
        data = data.repeat(epochs)
        data = data.shuffle(buffer_size=10000)
        return iter(data)

**Other info / logs**
WARNING: Logging before flag parsing goes to stderr.
E0701 21:48:20.707326 4585448896 ag_logging.py:132] Error converting <bound method Model.train of <tensorflow.python.eager.function.TfMethodTarget object at 0x1a3a5020b8>>
Traceback (most recent call last):
  File "/Users/sm0037/anaconda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 561, in to_graph
    return conversion.convert(entity, program_ctx)
  File "/Users/sm0037/anaconda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 314, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/Users/sm0037/anaconda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 256, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/Users/sm0037/anaconda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
W0701 21:48:20.709814 4585448896 ag_logging.py:145] Entity <bound method Model.train of <tensorflow.python.eager.function.TfMethodTarget object at 0x1a3a5020b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Model.train of <tensorflow.python.eager.function.TfMethodTarget object at 0x1a3a5020b8>>: AssertionError:

**Comment by ravikyram** [comment] 2019-07-02 11:07
In order to expedite the trouble-shooting process, please provide sample datasets and full minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-07-09 05:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-09 05:25 UTC
Labels: comp:autograph, stat:awaiting response, type:support

**Comment by strongrex2001** [comment] 2020-07-18 12:44
Same problem. I have a simple reproduction here. It seems to be related with `reimport` process in the Spyder console.
```python
import tensorflow as tf


@tf.function
def mean(a):
    return tf.reduce_mean(tf.abs(a))

```
Output:
```plain
runfile('D:/SJTU/quantum/tfbug.py', wdir='D:/SJTU/quantum')

mean([1, 2])
Out[2]: <tf.Tensor: id=9, shape=(), dtype=int32, numpy=1>

mean([1, 2])
Out[3]: <tf.Tensor: id=10, shape=(), dtype=int32, numpy=1>

runfile('D:/SJTU/quantum/tfbug.py', wdir='D:/SJTU/quantum')
Reloaded modules: tmpv1iph1dn

mean([1, 2])
WARNING: Logging before flag parsing goes to stderr.
W0718 20:43:06.847428 10664 ag_logging.py:146] Entity <function mean at 0x000000001DB28B70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function mean at 0x000000001DB28B70> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
Out[5]: <tf.Tensor: id=19, shape=(), dtype=int32, numpy=1>
```

**Comment by strongrex2001** [comment] 2020-07-18 14:39
After digging for a while, I finally found that it is related with Spyder User Module Reloader (UWR).
Nowhere documents controlling the UWR from script, and I dived into Spyder source code. I come up with an automatic process like this:
```python
try:
    import os
    import sys
    from spyder_kernels.customize import spydercustomize as spc
    if spc.__umr__ is None:
        namelist = os.environ.get("SPY_UMR_NAMELIST", None)
        if namelist is not None:
            namelist = namelist.split(',')
        spc.__umr__ = spc.UserModuleReloader(namelist=namelist)
    spc.__umr__.namelist += \
        list(filter(lambda x: x.startswith("tmp"), sys.modules.keys()))
except ImportError:
    pass
```
Append this to the end of the calling script and everything goes on well. It looks quite hacky, and maybe things will change with the Spyder version.
I think it is rather a Spyder issue than a TensorFlow issue. I'm going to report it to the Spyder.
