### ISSUE TITLE
Unexpected device usage in optimizer apply_gradients(zip())

### ISSUE THREAD

**Issue by SongLingzhi** [tensorflow/tensorflow#35849] opened 2020-01-14 07:23 UTC
Hi,
I have two GPUs and test a liner model on TF 2.1.0. This is the main part of the code:

```
DEVICE = "/gpu:1"

with tf.device(DEVICE):
    grads = tf.Variable(0.0)
    opt = tf.optimizers.Adam(1e-6)

@tf.function
def train_one_batch(model,train_data,train_label):
    print("tracing batch")
    with tf.device(DEVICE):
        with tf.GradientTape() as tape:
            predicts = model(train_data)
            loss = tf.nn.l2_loss(predicts - train_label)
            grads = tape.gradient(loss, [model.W, model.b])
            opt.apply_gradients(zip(grads, [model.W, model.b])) 
```

I make sure that all other tensors/ops are on GPU:1,so this program is surposed to run on GPU:1 only without GPU:0. But check the nvidia-smi console while running:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 31%   43C    P2    54W / 250W |  10571MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 29%   40C    P2    53W / 250W |  10635MiB / 10989MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
```

According to the memory-usage of GPU:0, this GPU is already in use. When I delete the last line "opt.apply_gradients(zip(grads, [model.W, model.b])) " and run it again, nvidia-smi shows:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 31%   43C    P2    54W / 250W |    165MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 30%   40C    P2    53W / 250W |  10571MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

It shows that GPU:0 is not in use as expected.

So,this is the problem,why the line "opt.apply_gradients(zip(grads, [model.W, model.b])) "
use an unexperted device despite I have alrealy specified one. Are there any other APIs to avoid this problem.

And whats more, that line also causes another tracing behavior(retrace) in the tf.function after first trace.

Thanks

**Comment by ravikyram** [comment] 2020-01-14 15:26
@SongLingzhi 
Looks like code is incomplete. Can you help us with colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster

**Comment by SongLingzhi** [comment] 2020-01-14 15:43
Thank you for your reply, I will send the full-version code via email later, maybe tomorrow~
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ravikyram"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 晚上11:26
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;; 
抄送: "Sgt.Royce"<550247896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tensorflow/tensorflow] Unexpected device usage in optimizer apply_gradients(zip()) (#35849)




@SongLingzhi
 Looks like code is incomplete. Can you help us with colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster

**Comment by SongLingzhi** [comment] 2020-01-15 05:01
Hello, this is the full-version code, some word has been replaced by "sensitive" due to sensitive reason.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ravikyram"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 晚上11:26
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"Sgt.Royce"<550247896@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] Unexpected device usage in optimizer apply_gradients(zip()) (#35849)




@SongLingzhi
 Looks like code is incomplete. Can you help us with colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster

**Comment by ravikyram** [comment] 2020-01-17 08:18
@SongLingzhi 
Please, share the code. Thanks!

**Comment by SongLingzhi** [comment] 2020-01-19 09:19
@ravikyram 
```
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'

import tensorflow as tf
import pickle

DATA_DIR = "/sensitive_data/"
DEVICE = "/gpu:1"
RANDOM_SEED = 12345
ONEHOT_LENGTH = 1375432
DEBUG = True

if DEBUG:
    tf.debugging.set_log_device_placement(True)
    print(tf.config.experimental.list_physical_devices('GPU')) # [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]


@tf.function
def _parse_function(example_proto):
    with tf.device("/cpu:0"):
        feature_description = {
            'sensitiveA': tf.io.FixedLenFeature(shape=[], dtype=tf.string, default_value=""),
            'sensitiveB': tf.io.FixedLenFeature(shape=[], dtype=tf.float32, default_value=0.0),
            'sensitiveC': tf.io.FixedLenFeature(shape=[], dtype=tf.float32, default_value=0.0),
            'sensitiveD': tf.io.FixedLenFeature(shape=[], dtype=tf.string, default_value=""),
            'sensitiveE': tf.io.FixedLenSequenceFeature(shape=[], dtype=tf.int64, default_value=0, allow_missing=True),
        }
        return tf.io.parse_single_example(example_proto, feature_description)

# class Model(tf.Module):
class Model():
    def __init__(self):
        with tf.device(DEVICE):
            self.W = tf.Variable(tf.random.uniform(shape=[ONEHOT_LENGTH,1],minval=0,maxval=1.0/ONEHOT_LENGTH,seed=RANDOM_SEED))
            self.b = tf.Variable(170.0)

    @tf.function
    def __call__(self, _x):
        with tf.device(DEVICE):
            x = tf.dtypes.cast(_x, tf.float32)
            return tf.matmul(x, self.W) + self.b


with tf.device(DEVICE):
    grads = tf.Variable(0.0)
    opt = tf.optimizers.Adam(1e-6)

@tf.function
def train_one_batch(model,train_data,train_label):
    print("tracing batch")
    with tf.device(DEVICE):
        with tf.GradientTape() as tape:
            predicts = model(train_data)
            loss = tf.nn.l2_loss(predicts - train_label)
            grads = tape.gradient(loss, [model.W, model.b])
            opt.apply_gradients(zip(grads, [model.W, model.b]))   #fixme: causes GPU0 uasge and retrace


if __name__ == '__main__':

    sensitive_tfrecord = pickle.load(open("./sensitive.pkl","rb"))
    for i in range(len(sensitive_tfrecord)):
        sensitive_tfrecord[i] = DATA_DIR + sensitive_tfrecord[i]

    dataset = tf.data.TFRecordDataset(sensitive_tfrecord).map(_parse_function,num_parallel_calls=22)

    with tf.device(DEVICE):
        model = Model()

        for data in dataset.batch(20):
            train_one_batch(model, data["sensitiveE"], data["sensitiveB"])
```

**Comment by ymodak** [comment] 2020-01-22 23:42
Logging device placement should print devices (gpu,cpu) used to execute the operations.
See https://www.tensorflow.org/guide/gpu#manual_device_placement
What information is logged for `apply_gradients` op?

**Comment by ymodak** [comment] 2020-01-30 23:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2020-01-30 23:22 UTC
Labels: TF 2.1, comp:gpu, stat:awaiting response, type:support
