### ISSUE TITLE
make sparse_tensor (SparseTensor) serializable in meta graph

### ISSUE THREAD

**Issue by ariejdl** [tensorflow/tensorflow#8275] opened 2017-03-10 16:32 UTC
`tf.sparse_placeholder` Sparse tensors aren't serialized in meta graphs, one has to serialize tf.placeholder tensors for the indices and values individually.

At present `add_collection_def` (called by `create_meta_graph_def`, which is typically called by `export_scoped_meta_graph`, found in [/tensorflow/python/framework/meta_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/meta_graph.py), ) **fails** when a `key` resolves to a `SparseTensor` as `SparseTensor`s do not have `name` attribute: here is the specific [line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/meta_graph.py#L290).

## Suggested solutions:
- give `SparseTensor` a `name` attribute and any other methods and properties necessary

or

- Enable `SparseTensor` or `sparse_placeholder` to be added to `_proto_function_registry` so that [ops.get_to_proto_function](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/meta_graph.py#L275) works in `add_collection_def`, perhaps using the `SAVEABLE_OBJECTS` key, something like the following being found in the SparseTensor file:

```
ops.register_proto_function(
    ops.GraphKeys.SAVERS,
    proto_type=saver_pb2.SaverDef,
    to_proto=Saver.to_proto,
    from_proto=Saver.from_proto)
```

speculative, I don't know the best implementation:

Could do something similar to the [`_as_graph_def`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L2114) method of `Graph` and loop through `graph._nodes_by_id`, compare the `SparseTensor`'s `_indices` to an `op` (node) `_outputs` from `_nodes_by_id`.

## Small Test

```python

g = tf.Graph()
with g.as_default(), tf.Session(graph=g).as_default() as sess:
  st = tf.sparse_placeholder(tf.string)
  ops.add_to_collection('_sparse_test', st)
  ops.add_to_collection('_test', tf.placeholder(tf.string))
  # FORMERLY GAVE A WARNING WHEN EXCEPTION THROWN
  tf.train.export_meta_graph('tmp_model/test-model.meta', as_text=True, graph=g,
                             collection_list=['_sparse_test', '_test']) 
  # WORKS
  print(sess.run(st, feed_dict={ st: ([[i,0] for i in range(10)],
                                      list(map(str,range(10))),
                                      [10,1]) }))
    
g2 = tf.Graph()
with g2.as_default(), tf.Session(graph=g2).as_default() as sess2:
  tf.train.import_meta_graph('tmp_model/test-model.meta')
  t = tf.get_collection('_test')[0]
  # FAILS
  st = tf.get_collection('_sparse_test')[0]
  print(sess2.run(st, feed_dict={ st: ([[i,0] for i in range(10)],
                                      list(map(str,range(20,30))),
                                      [10,1]) }))


```

Sometimes I get a segfault with this

**Comment by prb12** [comment] 2017-03-10 16:41
@concretevitamin Could you please comment?

**Comment by concretevitamin** [comment] 2017-03-10 22:23
Adding @ebrevdo who knows more about SparseTensor and @sherrym who is the owner of MetaGraph.

**Comment by ebrevdo** [comment] 2017-03-11 00:32
Seems reasonable (we can always add a 4th argument with default=None);
though I wonder if we can just pull a name from the name scope of the
indices tensor.  sherry, think it's reasonable to add ser/de for
SparseTensors?

**Comment by girving** [comment] 2017-06-16 19:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 19:14 UTC
Labels: stat:awaiting tensorflower, type:feature

**Comment by manishvatsa** [comment] 2017-09-01 10:00
I am facing the same issue while creating SparseTensor() with indices dtype int32.
SparseTensor with int64 data graph is not loading in Android.
Error:
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Value for attr 'T' of int64 is not in the list of allowed values: float, int32
; NodeDef: Less_1 = Less[T=DT_INT64](ToInt64_2, ToInt64_3); Op<name=Less; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_FLOAT, DT_INT32]>
at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:439)
at org.tensorflow.contrib.android.TensorFlowInferenceInterface.(TensorFlowInferenceInterface.java:98)


If we change dtype int64 to int32 SparseTensor give the error.
File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 119, in init
indices, name="indices", dtype=dtypes.int64)
File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
as_ref=False)
File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 614, in _TensorTensorConversionFunction
% (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("x_indices:0", shape=(?, 3), dtype=int32)'

**Comment by ebrevdo** [comment] 2017-09-06 03:10
Yours is an unrelated problem. Can you create a new issue?

**Comment by xjohnxjohn** [comment] 2018-08-17 16:13
@manishvatsa your problem are solved?
