### ISSUE TITLE
Where is stop_if_no_increase_hook gone?

### ISSUE THREAD

**Issue by gui-li** [tensorflow/tensorflow#31940] opened 2019-08-23 23:52 UTC
I use tensorflow.contrib.estimator.stop_if_no_increase_hook in my code to perform an early stopping, which works smoothly before. But today it throws out an error:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:

https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
https://github.com/tensorflow/addons
https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
Traceback (most recent call last):
File ".\main.py", line 215, in 
hook = tf.contrib.estimator.stop_if_no_increase_hook(
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_increase_hook'

I noticed that estimator has been moved to tensorflow/estimator. But it doesn't support this method now. Would you tell me where to find it or other workaround to perform early stoppoing?

**Comment by WindQAQ** [comment] 2019-08-24 04:44
Should be here? `tf.estimator.experimental.stop_if_no_increase_hook`
https://www.tensorflow.org/api_docs/python/tf/estimator/experimental/stop_if_no_increase_hook

**Comment by gui-li** [comment] 2019-08-24 18:35
@WindQAQ Thank you so much！

**Comment by ravikyram** [comment] 2019-08-26 06:50
I am closing this issue since the query is been answered. Please, feel free to reopen if the issue is still persists. Thanks!

**Closed by ravikyram** 2019-08-26 06:50 UTC
Labels: 2.0, comp:apis, type:support
