### ISSUE TITLE
Target '@llvm//:support' is not visible from target '@org_tensorflow//tensorflow/compiler/xla/client:compile_only_client'.

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#14445] opened 2017-11-10 12:14 UTC
I was doing an XLA compilation that worked before TensorFlow 1.4 but now errors with

> ERROR: /home/travis/build/carl/project/cache/bazel/external/org_tensorflow/tensorflow/compiler/xla/client/BUILD:107:1: Target '@llvm//:support' is not visible from target '@org_tensorflow//tensorflow/compiler/xla/client:compile_only_client'.

This is how I get tfcompile:
```sh
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout v1.4.0 # Note: master also fails
PYTHON_BIN_PATH=$(which python) USE_DEFAULT_PYTHON_LIB_PATH=1 CC_OPT_FLAGS='-march=native'
  TF_ENABLE_XLA=0 TF_NEED_MPI=0 TF_NEED_JEMALLOC=1 TF_NEED_GCP=0 TF_NEED_HDFS=0
  TF_NEED_VERBS=0 TF_NEED_OPENCL=0 TF_NEED_CUDA=0 TF_NEED_GDR=0 TF_NEED_S3=0 TF_NEED_OPENCL_SYCL=0 ./configure
```

**Comment by angersson** [comment] 2017-11-10 21:44
Please provide details about what platform you are using  (operating system, architecture). If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by carlthome** [comment] 2017-11-13 08:38
Ubuntu Trusty on Travis with Bazel 0.7.0.

**Comment by ZihengJiang** [comment] 2017-11-13 16:20
I have the same problem on osx

**Comment by lissyx** [comment] 2017-11-14 08:28
Same on Debian Sid, Bazel v0.5.4.

**Comment by lissyx** [comment] 2017-11-14 09:15
I've been able to trigger my build after changing roughly a dozen of visibility to public in `third_party/llvm/llvm.BUILD` by trial/error ... Not sure if it's a legit solution, though.

**Comment by carlthome** [comment] 2017-11-14 13:59
I wonder how the Bazel in Jenkins differs from our configs considering the 1.4 tests passed. :confused:

**Comment by lissyx** [comment] 2017-11-14 19:17
@carlthome I took a chance and had a look at the `tensorflow/tools/ci_build/` tooling. It turns out that it seems those run without sandbox, using `--spawn_strategy=standalone --genrule_strategy=standalone`.

One can see how bazel is defined there: https://github.com/tensorflow/tensorflow/blob/1b0a9ff5e863da4349f100bead90b0032805eafc/tensorflow/tools/ci_build/builds/libtensorflow.sh#L54 and then, in the rc file we find: https://github.com/tensorflow/tensorflow/blob/1b0a9ff5e863da4349f100bead90b0032805eafc/tensorflow/tools/ci_build/install/.bazelrc#L8

**Comment by cy89** [comment] 2017-11-15 03:53
@jart this seems potentially like a build issue rather than an XLA issue. Would you PTAL?

**Comment by hawkinsp** [comment] 2017-11-15 03:59
I've pushed a fix for this to our staging tree, it will make its way to Github shortly.

If you wish to workaround this locally in your tree, just change this line:
https://github.com/tensorflow/tensorflow/blob/master/third_party/llvm/llvm.BUILD#L21
from
package(default_visibility = ["@%ws%//tensorflow/compiler/xla:internal"])
to
package(default_visibility = ["//visibility:public"])

**Comment by jart** [comment] 2017-11-15 04:02
Sounds like @hawkinsp has got this one under control. That main repo reference issue has always been somewhat problematic.

**Comment by lissyx** [comment] 2017-11-15 07:24
Thanks @hawkinsp, it's indeed a generalization of the workaround I was working with, as documented above :)

**Closed** 2017-11-16 20:34 UTC
Labels: stat:awaiting tensorflower, type:build/install

**Comment by carlthome** [comment] 2017-11-17 14:34
Works again for me now. Thanks!

**Comment by lissyx** [comment] 2017-11-17 14:47
I can confirm it also works for us. Thanks!
