### ISSUE TITLE
Tensorflow and libcuda.so.1

### ISSUE THREAD

**Issue by dominiclai** [tensorflow/tensorflow#16184] opened 2018-01-17 08:15 UTC
Tensorflow 1.4.1
OS:  CentOS 6/7  (we use customized gcc 4.9.2 build for CentOS 6)

We have a number of computational servers.  Some are with GPU but some are not.  For the ease of maintenance, we build tensorflow from source code (bazel build) and install the modules under
/usr/local/... that all computational servers mount to the same /usr/local by means of NFS.

In the past (Tensorflow 1.0.0), the module could be built without linking with libcuda.so.1.  When a computational server without GPU runs tensorflow, it could run as CPU mode without problems.  When the computational server with GPU runs tensorflow, it could detect the GPU and load up libcuda.so.1 (and libcudart.so and libcudnn.so) by using dso_loader.  This works great for supporting both GPU and non-GPU servers while sharing the same module.

But I think that since 1.2.1 (at least, still 1.4.1), it seems that linking libcuda.so.1 is mandatory.  This is bad when non-GPU server would fail loading the module (missing libcuda.so.1), unless we explicitly putting libcuda.so.1 under /usr/lib64 (but this is a non-GPU server...!).  

Wonder if it is possible to make use of the old method of dso_loader instead of linking libcuda.so.1 for bazel building.  Thanks.

**Comment by tensorflowbutler** [comment] 2018-01-17 19:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dominiclai** [comment] 2018-01-18 01:32
OS:  CentOS 6 x86_64
(we have our compiled gcc 4.9.2 installed under /usr/local, and making use of this
customized toolchain for building bazel and tensorflow)
Tensorflow version:  1.4.1, grabbed from github.
Bazel: 0.9.0
CUDA: 9.0
CUDNN: 7.0.3
GPU:  K20m, 4GB
command to build:
bazel build --config=opt --config=cuda \
        --incompatible_load_argument_is_label=false \
         //tensorflow/tools/pip_package:build_pip_package

In fact, if we compile the package under the host with CUDA installed, we could have a workable
tensorflow package.  However, this package has a dynamic link to /usr/lib64/libcuda.so.1.
(eg.  libtensorflow_framework.so).  This arrangement works under computational server with
GPU installed.  But it fails when running under a server without GPU (ie. no CUDA library) installed.

In the past (tensorflow 1.0.0), tensorflow loads up cuda libraries by means of dso_loader 
(./tensorflow/stream_executor/dso_loader.cc), but it is no longer the case under 
tensorflow 1.4.1.  As a result, in the past (1.0.0), the same binary works for servers with or without CUDA library installed (ie. both GPU and non-GPU servers).  But under 1.4.1, due to the dynamic link to libcuda.so.1, the binary does not work with non-GPU servers that are without CUDA installed.  Of course, we can install cuda under those non-GPU servers to make it run.  But hey, what is the point when installing the CUDA toolkit to a non-GPU server??!!!

**Comment by tensorflowbutler** [comment] 2018-01-23 23:01
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment] 2018-01-30 23:30
@allenlavoie do you understand the implications of this?

**Comment by allenlavoie** [comment] 2018-01-30 23:59
There are hopes of going back to dynamic loading of libcuda, where not having it would just not register the device. @gunan is leading the effort.

**Comment by tensorflowbutler** [comment] 2018-02-14 13:22
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:49
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-17 15:02
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pkit** [comment] 2018-03-23 12:03
Created a fast hack to load libcuda at runtime:
https://gist.github.com/pkit/e06c2d23046a265a4f0fea302a5ce539

**Comment by tensorflowbutler** [comment] 2018-04-07 18:26
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-22 18:32
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-09 19:00
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:56
Nagging Assignee @gunan: It has been 64 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:50
Nagging Assignee @gunan: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by r4nt** [comment] 2018-06-21 14:36
Assuming you don't want to run the cuda binaries on the non-GPU server, would it be ok for you if the build didn't require libcuda.so.1? I think this is currently the case because we don't pass -lcuda to builds that depend on .so libraries that have been built with -lcuda, in which case the linker falls back to trying to find the library via the SONAME in the original linked libcuda.so, which is libcuda.so.1.

**Comment by tensorflowbutler** [comment] 2018-07-06 18:49
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pkit** [comment] 2018-07-06 19:12
I'm not sure I understand the comment above.
Currently `tensorflow-gpu` links dynamically against proprietary Nvidia driver with a very restrictive EULA.
So, my patch solves that problem, by not requiring any Nvidia proprietary software at the load time.

**Comment by gunan** [comment] 2018-07-07 04:45
Thanks for your contribution @pkit your patch looks really useful. Would you like to upstream this into TF itself?
I think the comment above is more about the dependency of TF at build time on CUDA. @r4nt it is possible that the patch by @pkit will tackle that problem. If cuda is only loaded when needed, our build system may avoid depending on it.

**Comment by tensorflowbutler** [comment] 2018-07-23 23:00
Nagging Assignee @gunan: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-07 19:00
Nagging Assignee @gunan: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-22 19:17
Nagging Assignee @gunan: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-06 18:53
Nagging Assignee @gunan: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-21 18:59
Nagging Assignee @gunan: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-27 01:03
Looking at the change, both its author and its reviewer has left our team.
@hawkinsp do you have any memory of the change?
Who would be the best to comment about stream executor?

**Comment by gunan** [comment] 2018-09-27 01:04
Again, I would be happy to review and accept a change to resolve this.

**Comment by tensorflowbutler** [comment] 2018-10-11 18:52
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-26 12:46
Nagging Assignee @gunan: It has been 28 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-10 18:44
Nagging Assignee @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-25 18:33
Nagging Assignee @gunan: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mika-fischer** [comment] 2019-02-05 16:11
@yifeif Could you point to the commit/pull request where this was changed? Does it happen by default or do we have to alter the build process somehow? I guess this will not be in 1.13?

**Comment by pkit** [comment] 2019-02-05 17:16
@mika-fischer https://github.com/tensorflow/tensorflow/commit/e0d156b3bfef7388b31b35793a2add7b0a5fab6d

**Comment by gunan** [comment] 2019-02-05 17:50
This won't be in 1.13.

**Comment by yifeif** [comment] 2019-02-08 19:04
Thanks @pkit. As @gunan mentioned, this won't be in 1.13, but it is in the latest nightly, as well as the default if you follow the official guide building from source.

**Comment by yifeif** [comment] 2019-03-01 20:12
Closing this as the issue with TF explicitly linking to driver should be fixed at head.

**Closed by yifeif** 2019-03-01 20:12 UTC
