### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by kitty2611** [tensorflow/tensorflow#17756] opened 2018-03-16 05:04 UTC
```
Traceback (most recent call last):
  File "C:\Users\hari\Desktop\tf_object_detection_api\models\research\object_detection\object_detection_tutorial_CONVERTED.py", line 16, in <module>
    import tensorflow as tf
  File "C:\Python27\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Python27\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python27\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Python27\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named _pywrap_tensorflow


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment] 2018-03-16 16:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-04-04 23:03
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-04-05 00:12
We need more information about your system to debug this. Can you provide platform, how you built, etc?

**Comment by drpngx** [comment] 2018-04-19 20:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-04-19 20:24 UTC
Labels: stat:awaiting response, type:build/install
