### ISSUE TITLE
Same Issue with latest Tensorflow on windows when using TensorForestEstimator

### ISSUE THREAD

**Issue by kishorenayar** [tensorflow/tensorflow#7095] opened 2017-01-26 16:24 UTC
Already this [issue](https://github.com/tensorflow/tensorflow/issues/6500) was created before and it's closed, but the issue was not resolved yet.

hparams = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
        num_trees=2, max_nodes=1000, num_classes=2, num_features=9, model_dir='model/fit/')
forest_classifier = tf.contrib.learn.TensorForestEstimator(hparams)

**NotFoundError: D:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\_training_ops.so not found**

**Comment by mrry** [comment] 2017-01-26 18:14
From your comment on #6500, it sounds like you're using TensorFlow 0.12.1. Can you try again with 1.0.0 alpha or a nightly build? I think the necessary fix landed after 0.12.1 was released.

**Comment by KeyYD** [comment] 2017-01-27 00:49
I come across the similar issues, too. And I suggest that you may check the import file in the file tree `D:\Program Files\Anaconda3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops_training_ops`
I think it may be caused by version of tensorflow. And in the ReadMe.md file of contrib, you can read that "Any code in this directory is not officially supported, and may change or be removed at any time without notice". So in different versions, the files in contrib may change. Pls take care of this

**Comment by kishorenayar** [comment] 2017-01-27 05:25
I will try with Tensorflow 1.0 and will let you know soon.

**Comment by kishorenayar** [comment] 2017-01-27 06:17
Is there any way to install Tensorflow 1.0 rc1 without using bazel and cmake in windows ? Because I'm having a trouble with building from source

**Comment by mrry** [comment] 2017-01-27 16:26
It doesn't look like the release candidate is showing up in PyPI yet, but you can try installing a nightly build to see if the problem is fixed (despite the version number in the name, this package contains all of the updates for 1.0.0):

http://ci.tensorflow.org/job/tensorflow-master-win-cmake-py/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow-0.12.1-cp35-cp35m-win_amd64.whl

**Comment by kishorenayar** [comment] 2017-02-01 11:03
@mrry , From the nightly build, I have installed the and tried to execute the **TensorForestEstimator** and now it is working. Great !!! :ok_hand:

**Comment by drpngx** [comment] 2017-02-01 20:16
Happy to hear!

**Closed by drpngx** 2017-02-01 20:16 UTC
Labels: stat:awaiting response, stat:community support, type:build/install
