### ISSUE TITLE
Weird grouping of tf.layers ops in TensorBoard graph visualization

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#7302] opened 2017-02-06 19:53 UTC
This doesn't always happen, but sometimes when stacking multiple tf.layers, variables get placed in previous layers' graphical boxes. Setting variable_scope prevents this, but it's still a bit confusing as to why this is happening. It could have something to do with how tf.layers decide on a scope name automatically.

An example on TensorFlow 1.0.0-rc0 (but I think this also happens on the current PyPI release):
![image](https://cloud.githubusercontent.com/assets/1595907/22663580/686737ee-ecad-11e6-8044-5e09749378cc.png)

```python
x = tf.layers.conv2d(x, ...)
x = tf.layers.conv2d(x, ...)
x = tf.layers.conv2d(x, ...)
```

As it's hard to reproduce, I think it could be related to having multiple runs in the same TensorBoard, and some kind of namespace collision happening.

**Comment by girving** [comment] 2017-02-07 15:44
@dandelionmane Can you comment?

**Comment by dandelionmane** [comment] 2017-02-17 00:05
Reassigning to @dsmilkov and @chihuahua for graph visualizer expertise. 

@carlthome, please post a full reproduction, including code that generates a bad graph, and the .pbtxt (or event files) that will repro

**Comment by chihuahua** [comment] 2017-02-22 02:24
Indeed, a full repro would be useful. That being said, I think I might've just repro-ed this case (except with a 1D convolution lol).

In the diagram below, is what you mean that the `kernel` and `bias` Variables within the conv1d_2 box really belong to conv1d_3? And that the `kernel` and `bias` Variables within the conv1d_1 box really belong to conv1d_2?

![pbcpih3hgdx](https://cloud.githubusercontent.com/assets/4221553/23194401/bce29ff0-f862-11e6-85e9-4849bdce9713.png)

If so, this looks like a tflearn scoping-related bug. I'll do a little research on that.

**Comment by carlthome** [comment] 2017-02-22 10:01
Sorry for not being able to provide a concrete example of how to reproduce the problem. I've been unable to precisely track it down in my experiments. Good to hear you're on it, @chihuahua!

> In the diagram below, is what you mean that the kernel and bias Variables within the conv1d_2 box really belong to conv1d_3? And that the kernel and bias Variables within the conv1d_1 box really belong to conv1d_2?

Yes, exactly.

**Comment by carlthome** [comment] 2017-04-12 15:07
Giving each `tf.layers.conv2d` an explicit name makes the graph look as expected, so I guess there's something wonky with how names are generated to avoid variable reuse?

**Comment by carlthome** [comment] 2017-04-23 17:43
This is still an issue in 1.1rc2.

**Comment by jart** [comment] 2017-06-16 22:29
We really appreciate this issue report, however I'm going to close it out due to inactivity. We're still open to solving this issue, but we need a simple way to reproduce it. If anyone in the community can help us out on that end, please file an issue against our new GitHub repository. Be sure to reference this issue. https://github.com/tensorflow/tensorboard/issues/new

**Closed by jart** 2017-06-16 22:29 UTC
Labels: tensorboard

**Comment by chihuahua** [comment] 2017-06-16 22:55
Indeed, I can't reproduce the issue. It seems fixed for `tf.contrib.layers.convolution2d`.

![rcmesrk7v42](https://user-images.githubusercontent.com/4221553/27247308-2bf44440-52ac-11e7-941b-611f4a5ba744.png)
