### ISSUE TITLE
While running test cases of SVHN data using Tensor Flow I get Resource exhausted : OOM when allocating tensor with shapedim { size: 73257 } dim { size: 32 } dim { size: 32 } dim { size: 32 }

### ISSUE THREAD

**Issue by saitejagroove** [tensorflow/tensorflow#4093] opened 2016-08-29 14:01 UTC
groove@groove-VirtualBox:~/Udacity-Nanodegree-Project5-Capstone$ python Capstone-project.py
(32, 32, 3, 26032)
(26032, 1)
(32, 32, 3, 73257)
(73257, 1)
(26032, 32, 32, 3)
(73257, 32, 32, 3)
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
started at :  2016-08-29 19:06:23.180157
Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f4db351d690>> ignored
step 0, training accuracy 0.109375
step 250, training accuracy 0.328125
step 500, training accuracy 0.640625
step 750, training accuracy 0.6875
step 1000, training accuracy 0.6875
step 1250, training accuracy 0.8125
step 1500, training accuracy 0.8125
step 1750, training accuracy 0.828125
W tensorflow/core/kernels/conv_ops.cc:162] Resource exhausted: OOM when allocating tensor with shapedim { size: 73257 } dim { size: 32 } dim { size: 32 } dim { size: 32 }
W tensorflow/core/common_runtime/executor.cc:1027] 0x3399fd0 Compute status: Resource exhausted: OOM when allocating tensor with shapedim { size: 73257 } dim { size: 32 } dim { size: 32 } dim { size: 32 }
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape, Variable)]]
Traceback (most recent call last):
  File "Capstone-project.py", line 272, in <module>
    x: testDataX, y_:testDataY , keep_prob: 1.0}))
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 405, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2728, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 73257 } dim { size: 32 } dim { size: 32 } dim { size: 32 }
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape, Variable)]]
Caused by op u'Conv2D', defined at:
  File "Capstone-project.py", line 150, in <module>
    h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
  File "Capstone-project.py", line 117, in conv2d
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 207, in conv2d
    use_cudnn_on_gpu=use_cudnn_on_gpu, name=name)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/groove/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()

groove@groove-VirtualBox:~/Udacity-Nanodegree-Project5-Capstone$

**Comment by poxvoculi** [comment] 2016-08-30 23:32
You're trying to allocate a 4D tensor of 2400485376 elements.  Assuming these are float32, that's about 9GB which is quite large.  It looks like it's for a GPU Op.  How big is the memory on your GPU, and what other tensors are live at the same time?  Did you really manage to train 1750 steps with this tensor allocating at every step?

**Comment by saitejagroove** [comment] 2016-09-01 12:40
Hi, I have alloted 11GB ram and I am using CPU-only tensorflow. I made it work by reducing dimension by a scale of 6 but the accuracy is around .83 which is not so good

**Comment by poxvoculi** [comment] 2016-09-01 15:39
OK.  So it may be possible to reduce your max memory consumption a bit without down-scaling.  Unfortunately I don't know of any specific documentation on this.  We have some future improvements planned which will hopefully make it less necessary and/or easier to do.   

The fact that your program doesn't run out of memory in the first couple of steps, but runs for some thousands first, suggests that either the OOM condition is the result of an unlucky concurrent execution that exceeds memory limits, or you have variable size Op inputs somewhere, and eventually you hit a minibatch which raises the aggregate live tensor size above your limit.

You'll need to figure out exactly what your computation graph looks like, i.e. what are the types and sizes of every Op input and output, and what edges connect them together.  There may be a *.pbtxt file generated as a side effect of execution which describes this graph.  Your python program will determine which subgraphs execute by session.run() statements that specify a set of input and output nodes that induce a subgraph.  Wherever two Ops in that subgraph don't have a serial dependency, i.e. one of them does not take as input an edge which is descendant from the other, they are potentially concurrent and may overlap in execution.  When that happens, all of their inputs and outputs are allocated simultaneously.  Knowing the types and sizes, you should be able to count up fairly precisely the memory requirement to execute each Op.  Keep in mind that Vars are always live, and if you're training, some values from the forward computation phase need to live until they're used (again) in the backprop phase.  This should all be explicit in the graph.

If you have some potential parallelism in the graph that may be causing OOM with an unlucky execution overlap, you can eliminate it by introducing a control edge that prevents one of the potentially overlapping Ops from beginning execution until the other has finished.  See [control dependencies]
(https://www.tensorflow.org/versions/r0.10/api_docs/python/framework.html#control_dependencies).

If your OOM problem is due to variable sized inputs, maybe you can change your input minibatch selection somehow to stay within your limits.

**Comment by aselle** [comment] 2016-09-09 21:48
I am closing this issue, as it is more of a question appropriate for stackoverflow. If you see  behavior that is a bug, you would need to reduce it to something small that we can reproduce. It seems like this is a case of a model that is too big. Thank you.

**Closed by aselle** 2016-09-09 21:48 UTC
Labels: awaiting response
