### ISSUE TITLE
unable to pickle keras.layers.StringLookup

### ISSUE THREAD

**Issue by ophiry** [tensorflow/tensorflow#55825] opened 2022-05-02 14:32 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

colab

### Python version

3.7

### Current Behaviour?

```shell
trying to pickle a StringLookup layer causes an exception
tried in colab python 3.7 and local macos python 3.8
```

### Standalone code to reproduce the issue

```shell
import tensorflow
import pickle
print(tensorflow.__version__)
pickle.dumps(tensorflow.keras.layers.StringLookup())
```

### Relevant log output

```shell
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-caa8edb2bfc5> in <module>()
      2 import pickle
      3 print(tensorflow.__version__)
----> 4 pickle.dumps(tensorflow.keras.layers.StringLookup())

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1189       return self._numpy_internal()
   1190     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1191       raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   1192 
   1193   @property

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```
</details>

**Comment by tilakrayal** [comment] 2022-05-04 04:11
@chunduriv ,
I was able to reproduce the issue in tensorflow v2.7, v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/15f5befe0c6fd26c16becdac14c4de24/55825.ipynb).

**Comment by chunduriv** [comment] 2022-05-06 09:39
@ophiry,

Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by chunduriv** [comment] 2022-05-09 11:21
@ophiry,

Can you please close this issue, since it is tracked [here](https://github.com/keras-team/keras/issues/16503). Thank you.

**Closed** 2022-05-11 00:06 UTC
Labels: stat:awaiting response, type:bug, comp:keras, comp:ops, TF 2.8
