### ISSUE TITLE
0.5.0 wheel install on Mac OS X using Homebrew python broken

### ISSUE THREAD

**Issue by iamed2** [tensorflow/tensorflow#11] opened 2015-11-09 16:37 UTC
This is what happens:

```bash
~: pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 51kB/s
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in /usr/local/lib/python2.7/site-packages (from tensorflow==0.5.0)
Installing collected packages: six, tensorflow
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
Successfully installed six-1.10.0 tensorflow-0.5.0
~: python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by vrv** [comment] 2015-11-09 17:09
Okay, I was able to reproduce this in virtualenv by installing protobuf==2.6.1

The short answer is that we depend on protobuf 3.0.0, and having the protobuf pip library installed seems to interfere with ours.

Two solutions:

1) pip install protobuf=3.0.0a1 or higher, then pip install tensorflow
2) pip uninstall protobuf first, and then install tensorflow again -- it should bring in the dependency

I was able to do both in virtualenv and they worked -- let me know if either suffices for you.  We might add protobuf >= 3 to our whl dependencies if so.

**Comment by flyingmutant** [comment] 2015-11-09 17:51
Tensorflow does not bring dependency on protobuf:

```sh
gp@MacBook-Pro-Gregory ~> pip list
mercurial (3.5.2)
pip (7.1.2)
setuptools (18.5)
vboxapi (1.0)
wheel (0.26.0)

gp@MacBook-Pro-Gregory ~> pip install --no-cache-dir https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 13.7MB/s
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.9.2 (from tensorflow==0.5.0)
  Downloading numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 9.5MB/s
Installing collected packages: six, numpy, tensorflow
Successfully installed numpy-1.10.1 six-1.10.0 tensorflow-0.5.0

gp@MacBook-Pro-Gregory ~> pip list
mercurial (3.5.2)
numpy (1.10.1)
pip (7.1.2)
setuptools (18.5)
six (1.10.0)
tensorflow (0.5.0)
vboxapi (1.0)
wheel (0.26.0)
```

Installing protobuf3 before does not help, either:

```sh
gp@MacBook-Pro-Gregory ~> pip list
mercurial (3.5.2)
pip (7.1.2)
setuptools (18.5)
vboxapi (1.0)
wheel (0.26.0)

gp@MacBook-Pro-Gregory ~> pip install protobuf==3.0.0a1
Collecting protobuf==3.0.0a1
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from protobuf==3.0.0a1)
Installing collected packages: protobuf
Successfully installed protobuf-3.0.0a1

gp@MacBook-Pro-Gregory ~> pip install --no-cache-dir https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 65.8MB/s
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.9.2 (from tensorflow==0.5.0)
  Downloading numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 3.4MB/s
Installing collected packages: six, numpy, tensorflow
Successfully installed numpy-1.10.1 six-1.10.0 tensorflow-0.5.0

gp@MacBook-Pro-Gregory ~> python
Python 2.7.10 (default, Nov  9 2015, 20:28:23)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

Unless I am missing something, neither of the solutions work for me. Latest OS X, python2 + python3 installed from Homebrew.

**Comment by aleph7** [comment] 2015-11-09 18:24
This fixed the problem for me:
```
pip uninstall protobuf
pip uninstall tensorflow
brew uninstall protobuf
pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
```

**Comment by vrv** [comment] 2015-11-09 18:24
flyingmutant: to appease my curiosity, can you let us know what you get when you do the following in python:

```python
import google.protobuf
>>> print google.protobuf.__version__
3.0.0a4
```
(it's possible google.protobuf.__version__ doesn't exist either in one of the environments I've tested).

Basically the symptom of the problem is that python is finding the older version of the protobuf library that doesn't support the generated python proto3 we require.

**Comment by VikramTiwari** [comment] 2015-11-09 18:49
Found the same issue on my end.

```
pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Using cached https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting six>=1.10.0 (from tensorflow==0.5.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.9.2 (from tensorflow==0.5.0)
  Using cached numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: six, numpy, tensorflow
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/_f/95xpdnrx4yncxz91dt53mvfh0000gn/T/pip-ZXxpkX-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

This issue (https://github.com/pypa/pip/issues/3165) has more insight into the same. And according to this its the issue with `six` library being preinstalled in El Captain systems.

Moreover there seems to be no solution as of now except installing python locally using brew rather than using pre-installed package by Apple.

**Comment by flyingmutant** [comment] 2015-11-09 18:53
@vrv I've got `AttributeError: 'module' object has no attribute '__version__'` for both 3.0.0a1 and 3.0.0a3 (which is the latest you can install with pip).

I've found what fixes the issue for me:
```sh
$ brew uninstall protobuf
$ pip uninstall protobuf
$ pip install 'protobuf>=3.0.0a3'
$ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
```

It appears that Homebrew's protobuf package was causing the issues. Removing it, then installing protobuf3 with pip does the trick.

**Comment by dvj** [comment] 2015-11-09 18:55
For the protobuf issue above on OS X, not only should you `pip uninstall protobuf` to get rid of protobuf 2.x, but make sure you `brew uninstall protobuf` if you are using homebrew.

@VikramTiwari : that is a different issue, already addressed in the "common problems" section of the 'Get Started' page

**Comment by VikramTiwari** [comment] 2015-11-09 18:57
@dvj Yup! Got it just now. Instructions by @flyingmutant did the trick.

**Comment by vrv** [comment] 2015-11-09 19:15
Thanks for the help debugging everyone!  We'll try to update our 'common problems' section soon to include these suggestions.

**Comment by Yangqing** [comment] 2015-11-09 20:01
By the way, if you would like to use homebrew, you can install protobuf 3 via:

brew install --devel protobuf

For more details please refer to https://github.com/grpc/grpc-common/issues/162

**Comment by iamed2** [comment] 2015-11-09 20:01
I was able to solve this by doing `brew reinstall --devel protobuf`, which installs `3.0.0a1`. Feel free to close the issue whenever you update the docs.

**Comment by liuyipei** [comment] 2015-11-10 01:04
I have the same problem, but my protobuf is apparently up-to-date?

Here is the output to `pip show numpy protobuf`
```
Name: numpy
Version: 1.10.1
Location: /mnt/4tb_internal/python/tensorflow/lib/python2.7/site-packages
Requires: 

Name: protobuf
Version: 3.0.0a3
Location: /mnt/4tb_internal/python/tensorflow/lib/python2.7/site-packages
Requires: setuptools
```

Here is the output to `uname -a`. My machine runs Ubuntu 14.04 LTS.
```
Linux yi-2014 3.13.0-64-generic #104-Ubuntu SMP Wed Sep 9 12:36:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by liuyipei** [comment] 2015-11-10 01:10
My thread got closed due to being similar to this, but I am not on Mac!  I would very much appreciate it if we can leave this one open until this gets resolved!

**Comment by vrv** [comment] 2015-11-10 01:17
Woops, sorry liuyipei@!  Will re-open the original one.  It's the same issue, just on a different platform.

**Comment by vrv** [comment] 2015-11-13 22:28
We've updated our docs to what we believe can help this -- closing this bug for now but we can re-open if there are some other related issues unaddressed

**Closed by vrv** 2015-11-13 22:28 UTC
Labels: installation/startup

**Comment by brutuselvis** [comment] 2015-12-02 11:12
I have  a similar issue on my mac running the eval lua command (th eval.lua -model .. /model_id1-501-1448236541.t7 -image_folder .. /img -num_images 1) on a small folder of ten images. 


I am in the neurotalk2 folder but nonetheless I get:

'''
/Users/localadmin/torch/install/bin/luajit: ...rs/localadmin/torch/install/share/lua/5.1/trepl/init.lua:383: module 'misc.utils' not found:No LuaRocks module found for misc.utils
	no field package.preload['misc.utils']
	no file '/Users/localadmin/.luarocks/share/lua/5.1/misc/utils.lua'
	no file '/Users/localadmin/.luarocks/share/lua/5.1/misc/utils/init.lua'
	no file '/Users/localadmin/torch/install/share/lua/5.1/misc/utils.lua'
	no file '/Users/localadmin/torch/install/share/lua/5.1/misc/utils/init.lua'
	no file './misc/utils.lua'
	no file '/Users/localadmin/torch/install/share/luajit-2.1.0-beta1/misc/utils.lua'
	no file '/usr/local/share/lua/5.1/misc/utils.lua'
	no file '/usr/local/share/lua/5.1/misc/utils/init.lua'
	no file '/Users/localadmin/.luarocks/lib/lua/5.1/misc/utils.so'
	no file '/Users/localadmin/torch/install/lib/lua/5.1/misc/utils.so'
	no file './misc/utils.so'
	no file '/usr/local/lib/lua/5.1/misc/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/localadmin/.luarocks/lib/lua/5.1/misc.so'
	no file '/Users/localadmin/torch/install/lib/lua/5.1/misc.so'
	no file './misc.so'
	no file '/usr/local/lib/lua/5.1/misc.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...rs/localadmin/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	eval.lua:7: in main chunk
	[C]: in function 'dofile'
	...dmin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010f243bc0
'''
Any suggestions what I m doing wrong? 

I traced back all the steps (except pointing the library path to the cudnn - I didn not get that).

**Comment by yoni** [comment] 2015-12-11 18:37
I got the same `syntax` keyword error with both 0.5 and 0.6 versions of tensorflow.

I'm using a `virtualenv` setup. Oddly, I got the error within `ipython` sessions, but don't get the error when running `python`. My solution was to remove ipython from the system install and install it in the virtualenv environment, instead. Hope this helps folks sole their install issues.

Relevant IPython warning that pointed me to this solution:
```
$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
...
```

**Comment by kibtes** [comment] 2015-12-18 15:15
I got the same syntax error on the gpu 0.5 version installed using python 2. I'm using a  virtualenv setup. The other  i am not understanding is that when i wrote the 'pip show numpy protobuf ' command the result was as follows
---
Name: numpy
Version: 1.8.2
Location: /usr/lib/python2.7/dist-packages
Requires:
---
Name: protobuf
Version: 2.5.0
Location: /usr/lib/python2.7/dist-packages
Requires:
 where as while importing the google.protobuf and printing the google.protobuf version the result was as follows
(tensorflow)root@dmlserver:/home/rzibello/Documents# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> print google.protobuf.__version__
3.0.0-alpha-1

The OS i am using Linux Ubuntu 14.04. can sombody please let me know their difference and what i could do get rid off the syntax error as well?

**Comment by timestocome** [comment] 2016-01-25 21:40
This is how I installed tensorflow on OSX 10.11.3
- su
- python --version ( check su is using python 2.7 )
- python -m pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none.any.whl


Using sudo generated wheel errors
I also had to switch back to 2.7 from python 3.5
-------------------------------------------------------------------------------
bash-3.2$ su
Password:
sh-3.2# whoami
root
sh-3.2# python --version
Python 2.7.11 :: Anaconda 2.4.1 (x86_64)
sh-3.2# python -m pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Collecting tensorflow==0.5.0 from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 35kB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==0.5.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.9.2 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==0.5.0)
Installing collected packages: tensorflow
Successfully installed tensorflow-0.5.0

**Comment by codexpage** [comment] 2016-11-11 14:15
I have exact the same problem.
It works for me to remove the protobuf 2.6 in the brew. 
Actually there are two versions of protobuf in my system, 2.6 below brew and 3.0 blew pip. 
Just one command to uninstall the protobuf 2.6 

>brew uninstall protobuf

everything is ok now.

**Comment by KajaStene** [comment] 2017-03-31 13:19
I have updated to reinstalled with pip to  protobuf (3.2.0) and uninstalled with brew just in case (it wasn't there) but I still get the same problem from importing tensor flow

> >>> import tensorflow
> Traceback (most recent call last):
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
>   File "/Users/kaja/tensorFlow/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/Users/kaja/tensorFlow/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: dlopen(/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
>   Referenced from: /Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
>   Reason: image not found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
>   File "/Users/kaja/tensorFlow/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/Users/kaja/tensorFlow/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: dlopen(/Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
>   Referenced from: /Users/kaja/tensorFlow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
>   Reason: image not found
