### ISSUE TITLE
Build from source Java

### ISSUE THREAD

**Issue by EduardoTayupanta** [tensorflow/tensorflow#23191] opened 2018-10-23 17:06 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): r1.11
- Python version:3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.18.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: nVidia970M
- Have I written custom code: N/A
- TensorFlow version: r1.11
- Exact command to reproduce: `bazel build --config=opt --config=cuda //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni`

Error when installing tensorflow with java, generates the following error lines

```
tensorflow/java/BUILD:54:1: Building tensorflow/java/libprocessor_library-class.jar (1 source file) failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException:
        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:252)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:33)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:52)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flushIfNotAvailable(CodedOutputStream.java:2998)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeUInt32NoTag(CodedOutputStream.java:2825)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeTag(CodedOutputStream.java:2670)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2774)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1009)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:318)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:160)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:115)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:106)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:994)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:923)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:471)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:505)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:215)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:418)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/users/eduar/_bazel_eduar/gr3cukxm/bazel-workers/worker-0-Javac.log ---8<---8<---
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'CompactStrings'
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 281.132s, Critical Path: 94.67s
INFO: 602 processes: 602 local.
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment] 2018-10-24 00:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow version
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-24 03:43
I would like to encourage you to refer to these [instructions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md) if you haven't already. Also installation on Windows requires the more experimental [bazel on Windows](https://docs.bazel.build/versions/master/windows.html).

**Comment by EduardoTayupanta** [comment] 2018-10-24 13:19
yes, I have exactly followed the [instructions,](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md) up to point three where it is declared

````
./configure
bazel build --config opt \
  //tensorflow/java:tensorflow \
  //tensorflow/java:libtensorflow_jni
````
yes, I tried to create the package from the source with Cuda 10
unless you use this option

`bazel run -c opt //tensorflow/java/src/main/java/org/tensorflow/examples:label_image`

**Comment by gunan** [comment] 2018-10-24 19:10
Looks like a bazel bug to me?

**Comment by EduardoTayupanta** [comment] 2018-10-24 21:15
Okay, but what is the solution?

**Comment by tensorflowbutler** [comment] 2018-11-08 19:06
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-23 18:37
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by xiahaobo** [comment] 2018-11-27 03:38
@meteorcloudy  please help !!!

**Comment by meteorcloudy** [comment] 2018-11-27 09:09
After googling the error `Unrecognized VM option 'CompactStrings'`
Looks like it's related to https://github.com/bazelbuild/bazel/issues/5726
@cushon Is this problem already resolved?

**Comment by cushon** [comment] 2018-11-27 16:09
Is that build using `--distinct_host_configuration=false`?

The crash indicates it's using a JDK 8 `--host_javabase` with the default Java toolchain, which only supports JDK 9 or newer.

Which bazel distribution is being used here? Is it the one with an embedded JDK?

**Comment by meteorcloudy** [comment] 2018-11-27 16:18
We do add `build --distinct_host_configuration=false` into `.tf_configure.bazelrc` on Windows. You can also remove it, but the build will take much longer time. @xiahaobo Can you try removing `--distinct_host_configuration=false` from that bazelrc file?

**Comment by xiahaobo** [comment] 2018-11-29 01:35
@gunan But there are other problems, I compile under window 7, should generate tensorflow_jni.dll, but generate tensorflow_jni.so.
I run the code at MS-DOS
```
bazel build --config opt //tensorflow/tools/lib_package:libtensorflow_jni.tar.gz //tensorflow/java:libtensorflow.jar //tensorflow/java:libtensorflow-src.jar
```

**Comment by meteorcloudy** [comment] 2018-11-29 08:57
@xiahaobo You can just rename it to `tensorflow_jni.dll`, we haven't fix the extension on Windows, but the library is built as a DLL.

**Comment by jvishnuvardhan** [comment] 2019-05-17 22:01
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-05-17 22:01 UTC
Labels: type:build/install
