### ISSUE TITLE
Can't include no_op in input_map when i import graph_def

### ISSUE THREAD

**Issue by taehyunkim1527** [tensorflow/tensorflow#21943] opened 2018-08-29 08:51 UTC
### System information
- **TensorFlow version (use command below)**: current master

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

When i pass no_op  into input_map, it makes an error.
i tracebacked some codes and 
the function _PopulateTFImportGraphDefOptions() in tensorflow/tensorflow/python/framework/importer.py can't support no_op as a control dependency.

under the first loop, it registers the input map operation into `options` when the `input_src` starts with '^'.
However, `no_op` doesn't have `_as_tf_output()` and the line
`dst_op = input_dst._as_tf_output().oper` occurs an exception.
Temporarily, i add the lines
`      src_name, src_idx = _ParseTensorName(input_src[1:])`
`      src_name = compat.as_str(src_name)`
`      dst_output = c_api_util.tf_output(input_dst._c_op, -1)`
`      c_api.TF_ImportGraphDefOptionsAddInputMapping(options, src_name, -1,`
`                                                    dst_output)`
instead of the lines
`      src_name = compat.as_bytes(input_src[1:])`
`      dst_op = input_dst._as_tf_output().oper  # pylint: disable=protected-access`
`      c_api.TF_ImportGraphDefOptionsRemapControlDependency(`
`          options, src_name, dst_op)`
However, I hope this problem to be fixed in the next version.

Thank you

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:50
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-16 02:32
It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 22:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 22:01 UTC
Labels: stat:awaiting response
