### ISSUE TITLE
compile failed at grpc_remote_worker.cc error: no matching function

### ISSUE THREAD

**Issue by liuziwei** [tensorflow/tensorflow#6897] opened 2017-01-17 08:33 UTC
Hi, I am trying to build tensorflow from source. Configure is OK, but bazel build is failed.
Enviroment: Centos-6.5  gcc-4.8.0 bazel-0.42 tensorflow-0.12.1 cuda-8.0

Here is the error log:
ERROR: /root/Downloads/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:70:1: C++ compilation of rule '//tensorflow/core/distributed_runtime/rpc:grpc_remote_worker' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 134 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc: In lambda function:
tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc:215:68: error: no matching function for call to 'grpc::ClientContext::TryCancel() const'
         call_opts->SetCancelCallback([this]() { context_.TryCancel(); });
                                                                    ^
tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc:215:68: note: candidate is:
In file included from external/grpc/include/grpc++/impl/codegen/call.h:43:0,
                 from external/grpc/include/grpc++/impl/call.h:37,
                 from external/grpc/include/grpc++/channel.h:39,
                 from external/grpc/include/grpc++/grpc++.h:56,
                 from ./tensorflow/core/distributed_runtime/rpc/grpc_util.h:21,
                 from ./tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.h:21,
                 from tensorflow/core/distributed_runtime/rpc/grpc_remote_worker.cc:16:
external/grpc/include/grpc++/impl/codegen/client_context.h:296:8: note: void grpc::ClientContext::TryCancel() <near match>
   void TryCancel();
        ^
external/grpc/include/grpc++/impl/codegen/client_context.h:296:8: note:   no known conversion for implicit 'this' parameter from 'const grpc::ClientContext*' to 'grpc::ClientContext*'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.842s, Critical Path: 11.80s

**Comment by mrry** [comment] 2017-01-17 23:11
The `GrpcRemoteWorker::InitContext()` method isn't const-qualified, so I'm not sure why the captured `this->context_` is const in your version of the code. Have you made any modifications?

**Comment by liuziwei** [comment] 2017-01-18 01:12
@mrry，no.   The code is git clone from master,  and than checkout to tags/0.12.1,  never change anything.

**Comment by asimshankar** [comment] 2017-01-19 01:25
@liuziwei : Could you share the steps to reproduce? And the output of `git status` on the repository? As @mrry pointed out, the line it's pointing to shouldn't be trying to use a const-qualified method.

**Comment by liuziwei** [comment] 2017-01-19 07:22
@asimshankar :
Step 1:  git clone
Step 2: git checkout tags/0.12.1
Step 3: fix issue #6950 -- so git status will show modified:  tensorflow/workspace.bzl
Step 4: ./configure
google cloud: N
HDFS: N
OpenCL: N
CUDA:Y
Other options use default
configure is complete
Step 5:   bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

git status:
# Not currently on any branch.
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   tensorflow/workspace.bzl
#
no changes added to commit (use "git add" and/or "git commit -a")

BTW： I try pip install tensorflow-gpu,  it works!   Finally give up "build from source"

**Comment by drpngx** [comment] 2017-01-23 22:30
@liuziwei I tried on a Ubuntu system instead, with `gcc-4.8.4`, and it worked. Closing since we can't repro. Please re-open if you're really sure it's a problem with the TF code.

**Closed by drpngx** 2017-01-23 22:30 UTC
Labels: type:build/install
