### ISSUE TITLE
tf2.3 keras.models.load_model setting compile=False fails to load saved_model but tf2.0 works.

### ISSUE THREAD

**Issue by Liu-Da** [tensorflow/tensorflow#43478] opened 2020-09-23 09:53 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Use tensorflow Addons
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac (Can be reproduced on colab)
- TensorFlow installed from (source or binary):
pip
- TensorFlow version (use command below):
2.3 fails 2.0works
- Python version:
python3

**Describe the current behavior**

I use F1score from addons as the metric. After training, I  use `keras.models.load_model`  to  load the saved_model  and also set `compile=False`.  I got an error. 
```
ValueError: Unable to restore custom object of type _tf_keras_metric currently. Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`.
```
This **happens with tf2.3**, but **works with tf2.0**.

**Describe the expected behavior**

If `compile=False` is set, it shouldn't check the metrics or losses.

**Standalone code to reproduce the issue**

- CODE

```
import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa

print(tf.__version__)

_input = tf.keras.layers.Input(shape=(500), name="fbank") # B*T*F*c
out = tf.keras.layers.Dense(50, activation="tanh")(_input)
probabilities = tf.keras.layers.Dense(2, activation="softmax")(out)
model = tf.keras.Model(inputs=_input, outputs=probabilities)

model.compile(optimizer="sgd", loss=tf.keras.losses.CategoricalCrossentropy(), 
              metrics= ["accuracy", tfa.metrics.F1Score(num_classes=2, average="micro")])

model.summary()

x=np.random.rand(300,500)
y=np.random.rand(300,2)
model.fit(x,y,batch_size=100, epochs=2)

path = 'saved_model/'
model.save(path, save_format='tf')

del model
model = tf.keras.models.load_model('saved_model', compile=False)

```

- OUTPUT

```
2.3.0
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
fbank (InputLayer)           [(None, 500)]             0         
_________________________________________________________________
dense (Dense)                (None, 50)                25050     
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 102       
=================================================================
Total params: 25,152
Trainable params: 25,152
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2
3/3 [==============================] - 0s 4ms/step - loss: 0.7292 - accuracy: 0.5033 - f1_score: 0.0000e+00
Epoch 2/2
3/3 [==============================] - 0s 4ms/step - loss: 0.7192 - accuracy: 0.5200 - f1_score: 0.0000e+00
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: saved_model/assets
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-9ff0edc2f186> in <module>()
     23 
     24 del model
---> 25 model = tf.keras.models.load_model('saved_model', compile=False)

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py in revive_custom_object(identifier, metadata)
    844                      'and `from_config` when saving. In addition, please use '
    845                      'the `custom_objects` arg when calling `load_model()`.'
--> 846                      .format(identifier))
    847 
    848 

ValueError: Unable to restore custom object of type _tf_keras_metric currently. Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`.
```

**colab**

https://colab.research.google.com/drive/17DI2N1L9EKSJ8-Ua88mcSnkmRT5adna3?usp=sharing

**Comment by bhack** [comment] 2020-09-23 10:28
Please unlock the colab access permissions.

**Comment by Liu-Da** [comment] 2020-09-23 10:36
> Please unlock the colab access permissions.

https://colab.research.google.com/drive/17DI2N1L9EKSJ8-Ua88mcSnkmRT5adna3?usp=sharing

**Comment by bhack** [comment] 2020-09-23 10:45
Can you try to load with `custom_objects={"F1Score": tfa.metrics.F1Score}`?
I've used: `!pip install --upgrade tensorflow tensorflow_addons` in your colab

/cc @marload

**Comment by amahendrakar** [comment] 2020-09-23 11:34
@Liu-Da,
As suggested by @bhack, by adding the `custom_objects={"F1Score": tfa.metrics.F1Score}` argument I was able to load the model without any issues. Please check [this gist](https://colab.research.google.com/gist/amahendrakar/ae7bdd21b2917d2ec57757c648f0572a/43478.ipynb) for reference. Thanks!

**Comment by Liu-Da** [comment] 2020-09-23 12:04
> @Liu-Da,
> As suggested by @bhack, by adding the `custom_objects={"F1Score": tfa.metrics.F1Score}` argument I was able to load the model without any issues. Please check [this gist](https://colab.research.google.com/gist/amahendrakar/ae7bdd21b2917d2ec57757c648f0572a/43478.ipynb) for reference. Thanks!

Thanks @bhack and @amahendrakar. This does make the model load successfully.  

But the key to the problem is why the same code behaves differently in the tf2.0 and tf2.3.  

In addition, if I set `compile=False`,  why should we still care about the custom metric?

**Comment by Liu-Da** [comment] 2020-09-23 12:08
I also found that the model trained and saved using tf2.0 can be loaded correctly by tf2.3. (set compile=False and dont need set custom_objects)

**Comment by bhack** [comment] 2020-09-23 12:25
I don't know if tf2.0 was going to save this custom object metrics. With the current code a think that the internal load doesn't care about the `compile` argument https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saved_model/load.py#L119-L120

**Comment by Liu-Da** [comment] 2020-09-23 12:39
> I don't know if tf2.0 was going to save this custom object metrics. With the current code a think that the internal load doesn't care about the `compile` argument https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saved_model/load.py#L119-L120

As the model trained and saved using tf2.0 can be loaded correctly by tf2.3 without set any custom_objects, this situation may not be caused by tf.keras.model.load but by Model.save.

**Comment by bhack** [comment] 2020-09-23 12:41
> I don't know if tf2.0 was going to save this custom object metrics. 

So if you don't save custom object metrics you don't have problem on load or not? As you was asking about loading with `compile=False`

**Comment by bhack** [comment] 2020-09-23 12:56
E.g. If you save and load a non compiled model also with TF2.3 is ok you don't need to care about the custom_metrics:
```
import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa

print(tf.__version__)

_input = tf.keras.layers.Input(shape=(500), name="fbank") # B*T*F*c
out = tf.keras.layers.Dense(50, activation="tanh")(_input)
probabilities = tf.keras.layers.Dense(2, activation="softmax")(out)
model = tf.keras.Model(inputs=_input, outputs=probabilities)

#model.compile(optimizer="sgd", loss=tf.keras.losses.CategoricalCrossentropy(), 
#              metrics= ["accuracy", tfa.metrics.F1Score(num_classes=2, average="micro")])

model.summary()

x=np.random.rand(300,500)
y=np.random.rand(300,2)
#model.fit(x,y,batch_size=100, epochs=2)

path = 'saved_model/'
model.save(path, save_format='tf')

del model
model = tf.keras.models.load_model('saved_model', compile=False)
```

**Comment by Liu-Da** [comment] 2020-09-23 13:24
> E.g. If you save and load a non compiled model also with TF2.3 is ok you don't need to care about the custom_metrics:
> 
> ```
> import numpy as np
> import tensorflow as tf
> import tensorflow_addons as tfa
> 
> print(tf.__version__)
> 
> _input = tf.keras.layers.Input(shape=(500), name="fbank") # B*T*F*c
> out = tf.keras.layers.Dense(50, activation="tanh")(_input)
> probabilities = tf.keras.layers.Dense(2, activation="softmax")(out)
> model = tf.keras.Model(inputs=_input, outputs=probabilities)
> 
> #model.compile(optimizer="sgd", loss=tf.keras.losses.CategoricalCrossentropy(), 
> #              metrics= ["accuracy", tfa.metrics.F1Score(num_classes=2, average="micro")])
> 
> model.summary()
> 
> x=np.random.rand(300,500)
> y=np.random.rand(300,2)
> #model.fit(x,y,batch_size=100, epochs=2)
> 
> path = 'saved_model/'
> model.save(path, save_format='tf')
> 
> del model
> model = tf.keras.models.load_model('saved_model', compile=False)
> ```

This code runs perfectly. 

> > I don't know if tf2.0 was going to save this custom object metrics.
> 
> So if you don't save custom object metrics you don't have problem on load or not? As you was asking about loading with `compile=False`

Yes, this code runs perfectly.

**Comment by Liu-Da** [comment] 2020-09-23 13:38
![image](https://user-images.githubusercontent.com/24472521/94018474-3bbf0780-fde3-11ea-8ad7-1e08dbc7f464.png)

The official document says that if we use Savedmodel, we don't need to consider the issue of custom_object.

Model should been successfully loaded by `model =tf.keras.models.load_model('saved_model')`.

Even if there is a custom_object, it should not affect the loading model.

When we compile and train a model and then distribute it to others, we hope that the model can be successfully loaded without any source data sharing and inference can be performed correctly.

**Comment by bhack** [comment] 2020-09-23 15:24
I don't know if the exception is (/cc @k-w-w)
https://github.com/tensorflow/tensorflow/blob/0650101e05ef1ad56bfaadcd63ab775b25ecdd16/tensorflow/python/keras/saving/saved_model/metric_serialization.py#L44-L45

**Comment by Liu-Da** [comment] 2020-09-25 06:44
If someone only wants to load the model for prediction and inference, **without retraining**, I found a workaround solution.
Use this code before `model.save`
```
model.optimizer = None
model.compiled_loss = None
model.compiled_metrics = None
```

**Comment by Liu-Da** [comment] 2020-09-25 06:46
> I don't know if the exception is (/cc @k-w-w)
> https://github.com/tensorflow/tensorflow/blob/0650101e05ef1ad56bfaadcd63ab775b25ecdd16/tensorflow/python/keras/saving/saved_model/metric_serialization.py#L44-L45

Can anyone familiar with this part of the code provide some help?

**Comment by bhack** [comment] 2020-09-25 10:49
It is referencing an internal ticket. I've already mentioned @k-w-w

**Comment by Liu-Da** [comment] 2020-09-26 12:22
> It is referencing an internal ticket. I've already mentioned @k-w-w

**Comment by amahendrakar** [comment] 2020-09-28 08:28
Was able to reproduce the issue. 

Code works with TF v2.0, throws an error stating 
`ValueError: Unable to restore custom object of type _tf_keras_metric currently. Please make sure that the layer implements get_config and from_config when saving. In addition, please use the custom_objects arg when calling load_model().` with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/906edc47c0ce6ee03c40d8f3b8f0dc01/untitled0.ipynb#scrollTo=Hcdmx695RtxT). Thanks!

**Comment by maxvfischer** [comment] 2020-12-10 17:11
> If someone only wants to load the model for prediction and inference, **without retraining**, I found a workaround solution.
> Use this code before `model.save`
> 
> ```
> model.optimizer = None
> model.compiled_loss = None
> model.compiled_metrics = None
> ```
@Liu-Da I'm experiencing this problem as well. I'm using `from tensorflow.keras.callbacks import ModelCheckpoint` to save the model. Do you see an adjustment of your work-around when using `ModelCheckpoint`?

**Comment by lgeiger** [comment] 2020-12-10 17:20
I submitted a fix for this issue in #45278, but it is still waiting for review.
I don't think there is an easy workaround for this currently other than only saving the weights in `ModelCheckpoint` or by adapting the callback itself to only save the model without the metrics.

**Comment by maxvfischer** [comment] 2020-12-11 09:27
@lgeiger I'm thinking about using @Liu-Da workaround together with `ModelCheckpoint`:

```python
...
callbacks = [
    ModelCheckpoint(
        filepath=arguments['model_output_path'],
        monitor=arguments['early_stopping_monitor'],
        verbose=0,
        save_best_only=True,
        save_weights_only=False,
        mode='max'
    )
]
model.fit(
    x=train_generator,
    steps_per_epoch=np.ceil(num_images_train / arguments['batch_size_train']),
    epochs=arguments['epochs'],
    validation_data=val_generator,
    validation_steps=np.ceil(num_images_val / arguments['batch_size_val']),
    callbacks=callbacks
)

model.optimizer = None
model.compiled_loss = None
model.compiled_metrics = None
model.save(arguments['model_output_path'])
```
Have I understood `ModelCheckpoint` correctly, that after `model.fit()`, the variable `model` will be the best model (because `save_best_only=True` in `ModelCheckpoint`)?

**Closed** 2020-12-11 22:02 UTC
Labels: TF 2.3, comp:keras, regression issue, stat:awaiting tensorflower, type:bug

**Comment by bendykstra94** [comment] 2021-03-02 20:16
@Liu-Da Just ran in to this issue where I trained a model with a tensorflow_addon metric. In the file where I load the saved model, import both tensorflow and tensorflow_addons, then the saved model loads without issue.
