### ISSUE TITLE
No documentation for ConfigProto

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#15978] opened 2018-01-09 16:34 UTC
### System information

Not necessary in this case.

### Describe the problem

No documentation for the `ConfigProto` class in the TF website. Specifically, in neither of the following pages

- https://www.tensorflow.org/api_docs/python/tf/ConfigProto
- https://www.tensorflow.org/versions/r1.5/api_docs/python/tf/ConfigProto
- https://www.tensorflow.org/versions/master/api_docs/python/tf/ConfigProto
  
### Possible solutions

The following article https://www.tensorflow.org/tutorials/using_gpu contains info about `ConfigProto`. Either the docs for `ConfigProto` can be written based on that info or, at least, a link to that article should be added to the `ConfigProto` docs.

**Comment by cy89** [comment] 2018-01-09 20:54
@josh11b it looks like you originally wrote those lines of the tutorial. Can you take a look or assign someone more appropriate, please?

**Comment by tensorflowbutler** [comment] 2018-01-24 19:57
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:02
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:12
Nagging Assignee @wolffg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:35
Nagging Assignee @wolffg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:35
Nagging Assignee @wolffg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-24 18:40
Nagging Assignee @wolffg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wolffg** [comment] 2018-05-04 04:58
As with all protobufs on tensorflow.org, we (now) link to the definition file itself, so you can click on the provided link see the documentation where the proto is defined. Even if we were to generate a more extensive field listing, it would be generated from the proto file's comments.

If we feel strongly that the protobuf should link to this doc on tensorflow.org, it should be linked to tensorflow.org in the proto definition itself in a comment.  

I'll leave this open for now and see if that's a practical thing to do.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:54
Nagging Assignee @wolffg: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:49
Nagging Assignee @wolffg: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:13
Nagging Assignee @wolffg: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:04
Nagging Assignee @wolffg: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:59
Nagging Assignee @wolffg: It has been 82 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:02
Nagging Assignee @wolffg: It has been 97 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:38
Nagging Assignee @wolffg: It has been 127 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:45
Nagging Assignee @wolffg: It has been 142 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-09-28 21:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by RomanSteinberg** [comment] 2018-11-07 10:15
@harshini-gadige why you close it? Look at _tensorflowbutler_ lst post:

> It has been 142 days with no activity and this issue has an assignee.

So, the problem is still present and issue is inactive bacause assignee does nothing. May be you should change an assignee to fix the problem?

**Comment by tensorflowbutler** [comment] 2018-11-22 18:43
Nagging Assignee @wolffg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2019-08-07 09:55
@RomanSteinberg did you check `using_gpu` [page](https://www.tensorflow.org/guide/using_gpu) that has good number of examples on `ConfigProto`. I am closing this issue as it is stale issue. Please feel free to open the issue if there are not sufficient examples and tutorials on `ConfigProto`.  Thanks!

**Comment by nbro** [comment] 2019-08-07 10:19
@jvishnuvardhan Well, the using_gpu page is not the documentation of ConfigProto.  I think this issue should remain open.

**Comment by jvishnuvardhan** [comment] 2019-08-15 18:57
@nbro Are you interested in contributing through changing the documentation? You could raise  a Pull-Request. Thanks!

**Comment by MarkDaoust** [comment] 2019-09-25 16:53
The TF2 launch is coming soon, and TF2 does not expose ConfigProto except as `tf.compat.v1.ConfigProto`. So it might be reasonable to close this as "obsolete".

@jaingaurav, you wrote the TF2 version of "Using GPU" do you know the status of ConfigProto? is it dead? should we close this?

**Comment by jaingaurav** [comment] 2019-09-25 23:09
@MarkDaoust: ConfigProto has been replaced by many `tf.config` APIs for 2.0. Under the hood it uses ConfigProto, but that is an implementation detail. Please let me know if there is any known functionality missing from the `tf.config` APIs, as not all fields may have been exposed in the new APIs.

**Comment by MarkDaoust** [comment] 2019-09-26 17:03
Okay, so this is mentioned in the migration guide now.  Closing.

**Closed by MarkDaoust** 2019-09-26 17:03 UTC
Labels: comp:ops, type:docs
