### ISSUE TITLE
TF 2.0 'Tensor' object has no attribute 'numpy' while using .numpy() although eager execution enabled by default

### ISSUE THREAD

**Issue by Mainak431** [tensorflow/tensorflow#27519] opened 2019-04-04 18:57 UTC
Although Eager_execution is enabled by default in TF 2.0, I am getting errors while using .numpy()

Please note that i am not using the code in compatibility mode to TF 1.0.

  expt = [[[  0,   0,   0],
            [  4,  71, 141],
            [  0,   0,  0]],

           [[ 83,  25,  85],
            [ 90, 190, 143],
            [  4, 141,  49]],

           [[  0,   0,   0],
            [  4,  71,  49],
            [  0,   0,   0]]]
expt = tf.convert_to_tensor(expt)

expected_values = expt.numpy()

AttributeError: 'Tensor' object has no attribute 'numpy'

CPU TEST VERSION OF TENSORFLOW 2.0.

**Comment by jinfagang** [comment] 2019-05-06 01:53
@Mainak431  Did you solved your problem?

**Comment by Mainak431** [comment] 2019-05-06 04:44
Yes.

**Comment by aagnone3** [comment] 2019-05-07 20:30
what was your solution?

**Comment by Mainak431** [comment] 2019-05-08 07:58
.Numpy is only supported in eager mode.  If you are in graph mode,  it will not be supported.  To check,  if you are in eager mode.  Do,  tf.eagerly().  It returns true or false.  In graph mode,  you have to use eval in a session to get the value of the tensor in numpy array.

**Comment by veonua** [comment] 2019-06-26 11:09
@Mainak431 
module 'tensorflow' has no attribute 'eagerly'
module 'tensorflow.compat.v1' has no attribute 'eagerly'

**Comment by francoisruty** [comment] 2019-06-26 14:57
I'm using the package tensorflow-gpu==2.0.0-alpha0
.numpy() on one of my tensors yield 'Tensor' object has no attribute 'numpy'

tf.eagerly() gives module 'tensorflow' has no attribute 'eagerly'

**Comment by blutjens** [comment] 2019-07-24 04:53
tf.executing_eagerly() instead of tf.eagerly() worked for me to check if I'm in eager mode

**Comment by joshmyersdean** [comment] 2019-09-02 22:40
Has anyone found a solution for this?

**Comment by bionicles** [comment] 2019-09-06 16:07
same issue here ...  i invoke a keras model in eager mode and i get a Tensor, not an EagerTensor, which causes issues with OpenAI Gym

**Comment by AkashNagaraj** [comment] 2019-09-23 06:29
Run this tf.enable_eager_execution() and then when you try tf.executing_eagerly() it should give True. After this you can use something.numpy() to view the values.

**Comment by Efaq** [comment] 2019-09-26 15:01
@AkashNagaraj I just filed an issue where the code is executing eagerly (and should, since it's TF 2.0), but I'm having a problem of "missing numpy". Would you care to take a look? https://github.com/tensorflow/tensorflow/issues/32842

Thanks!

**Comment by xro7** [comment] 2019-10-02 08:22
I had the same issue. Turned out that I was trying to use .numpy() inside a @tf.function. As far as I understand tf.function is not executed eagerly for performance purposes. If I remove the @tf.function decorator .numpy() works.

**Comment by DeanLeeFumu** [comment] 2019-10-18 10:09
> I had the same issue. Turned out that I was trying to use .numpy() inside a @tf.function. As far as I understand tf.function is not executed eagerly for performance purposes. If I remove the @tf.function decorator .numpy() works.

This works for me

**Comment by malharjajoo** [comment] 2019-11-26 16:09
Why isn't there a single solution mentioned in this thread =.=

**Comment by michael-lash** [comment] 2019-12-06 04:34
My function does not have a decorator but .numpy() still fails as described by previous posters. Has anyone found an solution to this?

**Comment by michael-lash** [comment] 2019-12-06 16:50
I've found that my issue clears up after inserting tf.compat.v1.enable_eager_execution() at the top of my script (very similar to what previous posters have said, but this works for TF 2.0)...

**Comment by renatomello** [comment] 2019-12-15 16:41
I'm having the same issue and none of the aforementioned solutions worked for me. 

I'm using TF 2.0, my function does not have a decorator, tf.eagerly() returns True and I still get the same AttributeError: 'Tensor' object has no attribute 'numpy'.

**Comment by wevonosky** [comment] 2019-12-16 16:40
Same problem. 

I made sure I was executing eagerly and do not have a decorator on my loss custom loss function. I get the error: AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by renatomello** [comment] 2019-12-17 12:52
I noticed that this error only appears when I try to convert tensors to numpy during a model fit. My best guess is that it seems to be shape issue.

For example, the following tensor

<class 'tensorflow.python.framework.ops.EagerTensor'>

tf.Tensor([[1 3]  [0 4]], shape=(2, 2), dtype=int64)

is convertible using .numpy(). However, when trying to implement a custom metric for a classification problem, both y_true.numpy() and y_pred.numpy() raise

AttributeError: 'Tensor' object has no attribute 'numpy'.

Here is one example of both y's:

y_true:
print(y_true): Tensor("dense_target:0", shape=(None, None, None), dtype=float32)
print(type(y_true)): <class 'tensorflow.python.framework.ops.Tensor'>

y_pred:
print(y_pred): Tensor("dense/Identity:0", shape=(None, None, 6), dtype=float32)
print(type(pred)): <class 'tensorflow.python.framework.ops.Tensor'>

**Comment by Haakam21** [comment] 2019-12-24 20:55
@renatomello I am having the same problem as you are. I have opened a new issue: #35393.

**Comment by sid027** [comment] 2020-01-17 09:11
@renatomello the problem still persists when trying to implement a custom metric. Did you find a workaround?

**Comment by renatomello** [comment] 2020-01-17 23:12
> 
> 
> @renatomello the problem still persists when trying to implement a custom metric. Did you find a workaround?

No, I did not. I'm trying to see if there's a TF/Keras backend function that does something similar that I can work with. Otherwise, I'll just have to create one myself.

**Comment by zfang-slim** [comment] 2020-02-05 20:18
@renatomello Hello, do you solve this issue? I got the same issue when i use tf2.1 stable. For somehow, the tensor just has no numpy attibute.

**Comment by harrisonjansma** [comment] 2020-02-05 21:23
I encountered this area when using the regex functions within data preprocssing. Using python logic requires the use of `tf.py_function` as mentioned in [docs](https://www.tensorflow.org/guide/data#applying_arbitrary_python_logic) and this [StackOverflow thread](https://stackoverflow.com/questions/56122670/how-to-get-string-value-out-of-tf-tensor-which-dtype-is-string) (Note `tf.py_func()` is now `tf.py_function()`) 

Once I changed my code from 
`data = fnames.map(process_path)`
to
`data = fnames.map(lambda x: tf.py_function(process_path, [x], [tf.string]))`
the code executed correctly.

**Comment by flybotix** [comment] 2020-03-21 02:13
I ran into this issue while trying out the `TextVectorization` layer in TF2.1 with a very custom `split`. What fixed it for me was to pass in `dynamic=True` to the `TextVectorization `construction.

**Comment by hhhh12345678** [comment] 2020-03-21 16:07
> I noticed that this error only appears when I try to convert tensors to numpy during a model fit. My best guess is that it seems to be shape issue.
> 
> For example, the following tensor
> 
> <class 'tensorflow.python.framework.ops.EagerTensor'>
> 
> tf.Tensor([[1 3] [0 4]], shape=(2, 2), dtype=int64)
> 
> is convertible using .numpy(). However, when trying to implement a custom metric for a classification problem, both y_true.numpy() and y_pred.numpy() raise
> 
> AttributeError: 'Tensor' object has no attribute 'numpy'.
> 
> Here is one example of both y's:
> 
> y_true:
> print(y_true): Tensor("dense_target:0", shape=(None, None, None), dtype=float32)
> print(type(y_true)): <class 'tensorflow.python.framework.ops.Tensor'>
> 
> y_pred:
> print(y_pred): Tensor("dense/Identity:0", shape=(None, None, 6), dtype=float32)
> print(type(pred)): <class 'tensorflow.python.framework.ops.Tensor'>

Don't know the reason, but I solved such  issue  by adding 
`experimental_run_tf_function=False` 
in compile function of my model.

**Comment by renatomello** [comment] 2020-03-21 21:42
> > I noticed that this error only appears when I try to convert tensors to numpy during a model fit. My best guess is that it seems to be shape issue.
> > For example, the following tensor
> > <class 'tensorflow.python.framework.ops.EagerTensor'>
> > tf.Tensor([[1 3] [0 4]], shape=(2, 2), dtype=int64)
> > is convertible using .numpy(). However, when trying to implement a custom metric for a classification problem, both y_true.numpy() and y_pred.numpy() raise
> > AttributeError: 'Tensor' object has no attribute 'numpy'.
> > Here is one example of both y's:
> > y_true:
> > print(y_true): Tensor("dense_target:0", shape=(None, None, None), dtype=float32)
> > print(type(y_true)): <class 'tensorflow.python.framework.ops.Tensor'>
> > y_pred:
> > print(y_pred): Tensor("dense/Identity:0", shape=(None, None, 6), dtype=float32)
> > print(type(pred)): <class 'tensorflow.python.framework.ops.Tensor'>
> 
> Don't know the reason, but I solved such issue by adding
> `experimental_run_tf_function=False`
> in compile function of my model.

It does not seem to make a difference in my case

**Comment by renatomello** [comment] 2020-03-21 23:02
> I ran into this issue while trying out the `TextVectorization` layer in TF2.1 with a very custom `split`. What fixed it for me was to pass in `dynamic=True` to the `TextVectorization `construction.

How did you do that exactly?

**Comment by Aldhubri** [comment] 2020-03-22 13:41
first, you should register Session as follow:
sess=tf.Session()
then..use :
expected_values = expt.eval(session=sess)
the result should be:
print(expected_values)
Out[41]: 
array([[[  0,   0,   0],
        [  4,  71, 141],
        [  0,   0,   0]]])
thank

**Comment by flybotix** [comment] 2020-03-24 14:54
> > I ran into this issue while trying out the `TextVectorization` layer in TF2.1 with a very custom `split`. What fixed it for me was to pass in `dynamic=True` to the `TextVectorization `construction.
> 
> How did you do that exactly?

Like this. I'm still learning ML/TF in general, so this may have been the wrong thing to do. It's all black magic until it 'just works'.
```
vectorize_layer = tf.keras.layers.experimental.preprocessing.TextVectorization(
    standardize=tf_custom_standardize,
    split=tf_custom_split,
    max_tokens=len(vocab)+1,
    output_mode='int',
    dynamic=True
)
```

**Comment by tnfru** [comment] 2020-03-30 12:12
This problem still persists for me. I am not using a the @tf.function annotation and executing eagerly. The workaround I am using now is np.array(yourtensor.to_list())

**Comment by renatomello** [comment] 2020-03-30 12:30
> This problem still persists for me. I am not using a the @tf.function annotation and executing eagerly. The workaround I am using now is np.array(yourtensor.to_list())

This is what I get
 `AttributeError: 'Tensor' object has no attribute 'to_list'`

**Comment by clockzhong** [comment] 2020-04-15 06:28
According to the codes in tensorflow, when the tensor object is in eager mode tensor(tensorflow.python.framework.ops.EagerTensor), we could call tesnsorObj.numpy()
this method is implemented in tensorflow/python/framework/ops.py
But if the tensor object is a general tensor, e.g. belonging to tensorflow.python.framework.ops.Tensor, then it'll have no numpy() method, the implementation codes is also in tensorflow/python/framework/ops.py
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py

It means all tensor object running in @tf.function couldn't call tensorObj.numpy()
The eager running mode adds the flexibility to TF2.0 and also adds complexity to it.

**Comment by renatomello** [comment] 2020-04-15 10:34
> According to the codes in tensorflow, when the tensor object is in eager mode tensor(tensorflow.python.framework.ops.EagerTensor), we could call tesnsorObj.numpy()
> this method is implemented in tensorflow/python/framework/ops.py
> But if the tensor object is a general tensor, e.g. belonging to tensorflow.python.framework.ops.Tensor, then it'll have no numpy() method, the implementation codes is also in tensorflow/python/framework/ops.py
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py
> 
> It means all tensor object running in @tf.function couldn't call tensorObj.numpy()
> The eager running mode adds the flexibility to TF2.0 and also adds complexity to it.

Thanks for the detailed explanation.

However, this issue is not solved in the stable 2.1.0 version. It was pointed out to me in the #38038 that it is solved in the tf-nightly 2.2.0 version.

**Comment by ab84139** [comment] 2020-04-25 19:26
@renatomello I'm a complete newbie on TF. So, I'm not sure if the following will help to solve your issue.
I solve the error `AttributeError: 'Tensor' object has no attribute 'numpy'`, by use of [experimental_run_functions_eagerly(True)](https://www.tensorflow.org/api_docs/python/tf/config/experimental_run_functions_eagerly).
I use TF ver. 2.1 (For the detailed version information see the below console output). I allow to explain what I'm doing with this code:
```
import sys
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

counter=0

class MyDense(layers.Dense):
  def __init__(self, units, activation,input_shape):
    super().__init__(units=units, activation=activation,input_shape=input_shape)

  def call(self, inputs):
      global counter
      
      counter += 1
      print('\n{}. inputs.numpy()='.format(counter))
      if hasattr(inputs,'numpy'):
          print('{}'.format(inputs.numpy()))
      else:
          print('not available.')
          
      return super().call(inputs)

def test(run_eagerly):
    print('\n*** *** *** test(run_eagerly={})'.format(run_eagerly))
    tf.config.experimental_run_functions_eagerly(run_eagerly)
    
    dim0=256
    dim1=24
    train = np.arange(dim0*dim1).reshape(dim0,dim1)
    label = np.ones(dim0)
    
    model = tf.keras.Sequential()
    model.add(MyDense(10,activation='softmax',input_shape=(dim1,)))
    
    model.compile(optimizer=tf.keras.optimizers.SGD(),
                  loss=tf.keras.losses.SparseCategoricalCrossentropy())
    
    model.fit(train,
              label,
              batch_size=dim0,
              epochs=1)

print("Python version")
print (sys.version)
print("TensorFlow version")
print(tf.__version__)
print('\n\n')

test(False)
test(True)
```

I execute the above code in the editor Spyder’s console (Spyder Version 4.0.1). The corresponding **console output** is (just parts of the output):

```
Python version
3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
TensorFlow version
2.1.0

*** *** *** test(run_eagerly=False)

1. inputs.numpy()=
not available.
Train on 256 samples

2. inputs.numpy()=
not available.

3. inputs.numpy()=
not available.
256/256 [==============================] - 0s 899us/sample - loss: 6344.8682

*** *** *** test(run_eagerly=True)

4. inputs.numpy()=
not available.
Train on 256 samples

5. inputs.numpy()=
[[2328. 2329. 2330. ... 2349. 2350. 2351.]
 [5280. 5281. 5282. ... 5301. 5302. 5303.]
 [2208. 2209. 2210. ... 2229. 2230. 2231.]
 ...
 [5160. 5161. 5162. ... 5181. 5182. 5183.]
 [ 840.  841.  842. ...  861.  862.  863.]
 [6048. 6049. 6050. ... 6069. 6070. 6071.]]
256/256 [==============================] - 0s 132us/sample - loss: 16.1181
```
Now, see in the console output below `test(run_eagerly=False)`: All three MyDense.call() calls state, that input.numpy() is not available (Side note: When I understand it correctly, the first two MyDense.call() calls are just for building the model. So, it’s meaningful, that they don’t have input.numpy() available.). So, this is meaningful.
See in the console output below `test(run_eagerly=True)`: In the fifth MyDense.call() is input.numpy() available. So, this is also meaningful. And it solves the error.

**Comment by captify-dieter** [comment] 2020-05-19 23:01
Having the same issue with TF 2.2.0 when using tensorflow hub. `executing_eagerly` returns True, but outputs no attribute error

**Comment by livey** [comment] 2020-05-22 01:28
> I had the same issue. Turned out that I was trying to use .numpy() inside a @tf.function. As far as I understand tf.function is not executed eagerly for performance purposes. If I remove the @tf.function decorator .numpy() works.

It works for me.

**Comment by edithzeng** [comment] 2020-06-05 17:47
I've tried all solutions mentioned in this thread, and none of them worked for me. I'm on 2.2.0-rc2.

It doesn't seem to be an issue with eager execution in my case. The error comes from these lines when I called `keras.backend.get_value()`:
```
  if context.executing_eagerly() or isinstance(x, ops.EagerTensor):
    return x.numpy()
```

**Comment by kenyukobayashi** [comment] 2020-06-16 12:41
Had the same issue. It turns out that by default, eagerly execution is disabled when running the fit function on a model. To counter this, you can run : `model.run_eagerly = True` before runing model.fit.
This worked like a charm for me on Tensorflow 2.2

**Comment by bjarthur** [comment] 2020-07-21 20:44
model.compile(..., run_eagerly=True) worked for me when creating a custom metric

**Comment by FalsoMoralista** [comment] 2020-07-29 23:04
https://stackoverflow.com/questions/63062304/extracting-numpy-value-from-tensorflow-object-during-transformation/63064174?noredirect=1#comment111652837_63064174

**Comment by ShrideviReddy** [comment] 2020-07-30 04:01
I had similar problem while working with Keras. 
I don't know if this will help other , but following helped me:
I was using:
model = Sequential() before and changed that to 
model = tf.keras.Sequential() 
And it worked for me.

**Comment by talpay** [comment] 2020-08-05 12:26
@Mainak431 would you mind reopening the issue?

**Comment by talpay** [comment] 2020-08-05 12:41
To recap, what seems to work for some is to avoid using the @tf.function decorator and do:
```
tf.config.experimental_run_functions_eagerly(True)
model.compile(....., run_eagerly=True)
```
Unfortunately, this doesn't work for me. I've been debugging this issue with tf.keras.backend.eval which has the following checks:

```
  if context.executing_eagerly() or isinstance(x, ops.EagerTensor): # evaluates to False even though it is enabled above!
    return x.numpy()

  if ops.executing_eagerly_outside_functions(): # evaluates to True
    # This method of evaluating works inside the Keras FuncGraph.
    return  # fails
```
At some point `eval_in_eager_or_function(x)` calls `Tensor.numpy()` which fails because the code is expecting `TensorEager.numpy()`. This looks to me like one of the checks doesn't cover an edge case and `eval_in_eager_or_function(x)` should at the very least have an assertion about the tensor type. But it is a mystery to me how `context.executing_eagerly()` can be `False` if the model has specifically been set to run in eager mode. Since other methods like tf.print() actually work correctly (!), it reinforces the idea that the underlying issue is caused by some bug.

**Comment by Blubbaa** [comment] 2020-09-10 07:21
> I had similar problem while working with Keras.
> I don't know if this will help other , but following helped me:
> I was using:
> model = Sequential() before and changed that to
> model = tf.keras.Sequential()
> And it worked for me.

That was actually the solution for me, I reused some old code which imported directly from keras, not tensorflow.keras layers etc. changing the import statements resolved the attribute error.

**Comment by ShrideviReddy** [comment] 2020-09-11 02:44
@Blubbaa Same here. It was only thing that worked for me.

**Comment by tu1258** [comment] 2020-09-12 19:55
If I want to check the value in tensor but I have to disable eager mode because of `tf.placeholder` compatibility, how should I do? While adding `tf.enable_eager_execution` between the layer I just got this error `ValueError: tf.enable_eager_execution must be called at program startup.`

**Comment by leenabora** [comment] 2020-09-15 07:58
Following code worked:

    def parse_str(str_tensor):
        raw_string = str_tensor.numpy().decode("utf-8") 
    
        # play with raw string
        raw_string = 'AAA'+raw_string     
        return raw_string
    

Call parse function:


    def tf_pre_processing(row):
      return tf.py_function(parse_str, [row['context']], [tf.string])
    
    
    train = t.map(tf_pre_processing).batch(1).take(1)
    
    list(train)

**Comment by jvishnuvardhan** [comment] 2020-09-26 18:18
@Mainak431 The original code was working as expected. [Here](https://colab.research.google.com/gist/jvishnuvardhan/9085fdddb86208357ba785c426c1633d/untitled45.ipynb) is the gist. 

@tu1258 You don't need to disable eager execution. Just import it as `tf.compat.v1.placeholder` instead of `tf.placeholder`. If it still doesn't work, then please share a standalone code to reproduce the issue.

Please let me know if there are any more questions. Thanks!

**Comment by anugrahasinha** [comment] 2020-09-29 05:29
> I had the same issue. Turned out that I was trying to use .numpy() inside a @tf.function. As far as I understand tf.function is not executed eagerly for performance purposes. If I remove the @tf.function decorator .numpy() works.

I think following option in Tensorflow2.x can help
[tf.config.run_functions_eagerly](config.run_functions_eagerly)

The place you are calling tf.function, you can try to execute it eagerly and then disable eager execution for tf.function.

**Comment by louisnot** [comment] 2020-10-01 10:02
I'm new to tensorflow but following this tutorial (on Jupyter Notebook) https://www.tensorflow.org/tutorials/quickstart/beginner?hl=en will give you the error 

```
predictions = model(x_train[:1]).numpy()
Tensor object has no attribute 'numpy'
```

**Comment by jvishnuvardhan** [comment] 2020-10-01 18:00
@louisnot I cannot reproduce the error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/0bcf017989e93c82a94855775b4ff23e/beginner.ipynb). Thanks!

If you are facing the error, can you please share a gist? Thanks!

**Comment by louisnot** [comment] 2020-10-02 12:33
I did not face any problem using the gist.

**Comment by jvishnuvardhan** [comment] 2020-10-02 17:11
I am closing this issue as this was resolved in `tf-nightly`. Please feel free to reopen if I the issue persists. Thanks!

**Closed by jvishnuvardhan** 2020-10-02 17:11 UTC
Labels: Fixed in Nightly, TF 2.0, comp:core, stat:awaiting response, type:support

**Comment by bhupendrathore** [comment] 2020-10-20 13:56
Not sure, if it's directly connected to it but, while using the TensorFlow data pipeline (tf.Dataset.map) I'm facing a similar kind of error,
I'm using tf-nightly(Oct 20,2020).
I have an image data set, converted all the images into tensor, and serialized and saved as tfrecord

def _convert_and_serialize(value):
        value = tf.convert_to_tensor(value)
        value = tf.io.serialize_tensor(value)
Now I'm readind that tfrecords dataset  using tf.Dataset.Tfrecords , I've a decode_record function ans a preprocessing function as below ->
def _decode_record(record):
    feature_description = {
    'image': tf.io.FixedLenFeature([], tf.string, default_value='')}
    sample = {}
    parsed = tf.io.parse_single_example(record,feature_description,)
    sample['image'] = tf.io.parse_tensor(parsed['image'],out_type=tf.uint8)
return sample

def preprocesss_data(sample,jitter,min_size):
      image = sample["image"]
       image_shape = tf.cast(tf.shape(image)[:2], dtype=tf.float32)
    if jitter is not None:
        min_side = tf.random.uniform((), jitter[0], jitter[1], dtype=tf.float32)
    ratio = min_side / tf.reduce_min(image_shape)
    if ratio * tf.reduce_max(image_shape) > max_side:
        ratio = max_side / tf.reduce_max(image_shape)

....
I'm trying to reduce the function. for more details you can refer preprocess_data function at below link. https://keras.io/examples/vision/retinanet/

autotune = tf.data.experimental.AUTOTUNE
data_temp  = tf.data.TFRecordDataset('my.tfrecord')
data_temp = data_temp.map(_decode_record,num_parallel_calls=autotune)
data_temp = data_temp.map(preprocess_data,num_parallel_calls=autotune)

it  gave me an error : OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
I tried wi tf.function as well it didn't work, If i try to use tenosr.numpy() that also gave the same error no error numpy.

I also tried using tf.py_fuction but that also failed.

Sorry for the spam, let me know if it's not the right place.

Thanks

**Comment by jvishnuvardhan** [comment] 2020-10-20 17:59
@bhupendrathore Can you please open a new issue with a simple standalone code to reproduce the error? Thanks!

**Comment by liangzelang** [comment] 2020-10-22 11:51
I get the same problem,; when I fix it in your solution with `pip install tf-nightly` , the errors occurs:
```
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly
```

**Comment by jvishnuvardhan** [comment] 2020-10-22 16:55
@liangzelang i see you opened another new issue. we will resolve it there. Thanks

**Comment by xixilog** [comment] 2021-01-16 09:53
fuck tf

**Comment by OnlyBelter** [comment] 2021-02-19 12:35
Add `tf.config.run_functions_eagerly(True)` before run other code.

see: https://www.tensorflow.org/api_docs/python/tf/config/run_functions_eagerly

**Comment by kaelzhang** [comment] 2021-03-11 13:59
> Add `tf.config.run_functions_eagerly(True)` before run other code.
> 
> see: https://www.tensorflow.org/api_docs/python/tf/config/run_functions_eagerly

@OnlyBelter thanks a million! You save my day.

**Comment by billybatsaikhan** [comment] 2021-06-08 07:43
I have tried all of the above methods, but they didn't work for me.
**I solved this problem by simply restarting my Jupyter notebook.** 
It turned out that activating eager mode or trying different TensorFlow commands messed up my environment.

**Comment by GranMin** [comment] 2021-07-16 09:36
tf.config.run_functions_eagerly(True)
I fixed my problem by explicitly specify eager execution.
my tf version is 2.3.0

**Comment by Nico-ba** [comment] 2021-07-22 14:08
What fixed the problem for me was changing:

import keras
to
from tensorflow import keras

Don't know why but import keras changed tf.executing_eagerly() to false again.

**Comment by mainguyenanhvu** [comment] 2021-08-18 09:09
@renatomello I encountered it when run this command `model.tabnet.aggregate_feature_selection_mask.numpy()`. In google colab, it worked well. However, on my local, it threw this error.
I ensured that the eager model is enabled. `print(tf.executing_eagerly())` returns True. 

Please help me. Thank you a lot.
[notebook](https://colab.research.google.com/drive/1T8P5DrwBBZpx-FjWrAxXNhZNfsco8y-t?usp=sharing)

**Comment by renatomello** [comment] 2021-08-18 09:18
> @renatomello I encountered it when run this command `model.tabnet.aggregate_feature_selection_mask.numpy()`. In google colab, it worked well. However, on my local, it threw this error.
> I ensured that the eager model is enabled. `print(tf.executing_eagerly())` returns True.
> 
> Please help me. Thank you a lot.
> [notebook](https://colab.research.google.com/drive/1T8P5DrwBBZpx-FjWrAxXNhZNfsco8y-t?usp=sharing)

What worked for me at the time was updating my TF to the nightly version, where the problem was already fixed.

**Comment by mervess** [comment] 2021-09-02 12:29
What fixed it for me:
Use either `tf.config.run_functions_eagerly(True)`, or compile the model with the flag `run_eagerly=True`.
Then, add `if tf.executing_eagerly():` before calling the `.numpy()` function.

TF version: 2.5.0, I use *tensorflow.keras*.

**Comment by dpintof** [comment] 2021-09-21 08:42
If you go the tf.compat.v1.enable_eager_execution() route don't forget to restart your Kernel in Spyder.

**Comment by aghajanyan** [comment] 2021-11-17 17:16
> I have tried all of the above methods, but they didn't work for me. **I solved this problem by simply restarting my Jupyter notebook.** It turned out that activating eager mode or trying different TensorFlow commands messed up my environment.

Holy... I just can't believe!! Thank you a lot! :D

**Comment by dragen1860** [comment] 2021-11-23 09:29
simply give up tensorflow and hardly every error disappears. pytorch yes!

**Comment by CharlesScoville** [comment] 2023-08-21 06:14
~4 years later and this is still a problem; the above solutions do not resolve my issue.

I am following the TensorFlow Lite example "generative_ai" readme to the letter.

I confess, my issue may be caused by using a dated version of Python (3.8) which pulls dated versions of everything else I'm assuming. Still... I expect there to be a stable version that works for Python 3.8, and I feel I am justified in feeling that way.

Maybe IDK how it actually works in the software world, but in the real world when I'm done doing a thing I clean up my f*ing mess before I move on to something else. ¯\_(ツ)_/¯

**Comment by White-Charles** [comment] 2023-11-02 18:34
I met the same issue (TF=2.14.0, python=3.9.18, eras=2.14.0). I solved the problem in this way:
add functions which disabled some actions in TF2
```
import tensorflow as tf
tf.config.run_functions_eagerly(True)
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
if tf.executing_eagerly():
        x.numpy()
```
I referred to the [https://www.tensorflow.org/api_docs/python/tf/config/run_functions_eagerly](url)
and [https://github.com/onnx/keras-onnx/issues/651#issuecomment-872061539](url)

then the model can be run successfully! Hope this help 😄

**Comment by ben-arnao** [comment] 2023-12-09 02:55
> I had the same issue. Turned out that I was trying to use .numpy() inside a @tf.function. As far as I understand tf.function is not executed eagerly for performance purposes. If I remove the @tf.function decorator .numpy() works.

I don't have the decorator but I'd imagine this is the case for when TF does the initial tracing for custom code.
