### ISSUE TITLE
How to run tflite with float input

### ISSUE THREAD

**Issue by LeighSu** [tensorflow/tensorflow#26607] opened 2019-03-12 13:20 UTC
Hi Sir,
  I am trying to run tflite on mobile to classify sound event.
  The input of the model is mfcc features from the sound stream, which's type are float32.
  I have converted the pb model to tflite model, but I cannot feed the input data whith float32.

It will be throw exception as follow whether I setting the post_training_quantize to True or not
 **cannot convert between a tensorflowlite tensor with type float32 and a java object of type**

**Comment by jvishnuvardhan** [comment] 2019-03-14 21:52
@LeighSu Could you fill issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) and if possible, please provide a code to reproduce the bug? Thanks!

**Comment by tensorflowbutler** [comment] 2019-03-29 13:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-03-29 16:04
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-29 16:04 UTC
Labels: comp:lite, stat:awaiting response, type:bug/performance

**Comment by BIGCRYPTO001** [comment] 2019-03-29 18:36
You provide
