### ISSUE TITLE
tf.round != np.round

### ISSUE THREAD

**Issue by m-colombo** [tensorflow/tensorflow#3730] opened 2016-08-10 14:46 UTC
Looks like tensorflow and numpy use different tie-breaking rules:

```
tf.round(0.5) => 1
np.round(0.5) => 0
```

Both are sound, so actually there's no bug, however since tf and np are tightly coupled is worth considering to uniform them or at least to explictly mention it in the doc.
Especially because np is often used as ground truth for tf tests.
### Environment info
- Operating System: Mac OS X
- TensorFlow: 0.10.0rc0 
- https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl
### Steps to reproduce

```
import tensorflow as tf
import numpy as np

with tf.Session() as S:
    tf_round = S.run(tf.round(0.5))

np_round = np.round(0.5)

print "round(0.5) => tf: {:.2f}\t np:{:.2}".format(tf_round, np_round)

assert np_round == tf_round
```

**Comment by girving** [comment] 2016-08-10 16:22
@martinwicke What's the status of native round?  We currently just use `floor`.

**Comment by martinwicke** [comment] 2016-08-10 16:32
Never reinstated it. We should.

**Comment by apmanikandan** [comment] 2016-08-13 04:51
on tensorflow the function rounds the value to the nearest integer, wherein numpy specify the decimal to return the ground truth.  print np.round(0.5, decimals=1)

e.g,
>>> import tensorflow as tf
>>> import numpy as np
>>> with tf.Session() as S:
...     tf_round = S.run(tf.round(1.5))
... 
>>> np_round = np.round(1.5,1)
>>> 
>>> print "round(1.5) => tf: {:.2f}\t np:{:.2}".format(tf_round, np_round)
round(1.5) => tf: 2.00	 np:1.5

**Comment by girving** [comment] 2016-08-14 06:08
@apmanikandan The decimals monstrosity is unfortunate but unrelated to the current discussion; @m-colombo's concern is with tie breaking behavior.

**Comment by hholst80** [comment] 2016-08-15 19:44
NumPy seems to be using an unusual rounding mode by default called *Round half to even*. See https://en.wikipedia.org/wiki/Rounding#Tie-breaking 

TensorFlow uses the same standard rounding as all other scientific tools I have available (Octave, Silverfrost Fortran and Gnu Fortran) called *Round half away from zero*

**Comment by m-colombo** [comment] 2016-08-16 14:28
Even if unusual it's the default mode in IEEE754, while _Round half away from zero_ is the optional one added in IEEE754-2008. I tried R and Matlab, the first use _Round half to even_ while Matlab _Round half away from zero_ .
More over I did a brief search on low level rounding operation support and both [Cuda](http://docs.nvidia.com/cuda/parallel-thread-execution/index.html#rounding-modifiers) and [Intel architectures](http://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-manual-325462.html) (pg.104) do not natively support _Round half away from zero_ 

Wondering why so many scientific tools adopted that mode, which before 2008 wasn't even standard.

**Comment by martinwicke** [comment] 2016-08-28 06:02
If someone wants to reinstate #1288, I'd be very excited.

**Comment by Mistobaan** [comment] 2016-08-28 19:00
@martinwicke seems the rint operator was merged and then unmerged? you want a rebased PR of that PR?

**Comment by martinwicke** [comment] 2016-08-28 19:20
That would be great. Last time we had to revert because it failed some
postsubmits and I never got around to fixing it. The root cause was
someplace else and fixed I believe so this should work now.

**Comment by Mistobaan** [comment] 2016-08-29 21:44
@martinwicke I took a look at this and updated to work for float32 and float64. But seems that the `round` operation for Eigen::half is not supported on Eigen. I think is a simple declaration of the round function, but how to proceed? Wait for Eigen? commit only the float32 and float64 version?

**Comment by martinwicke** [comment] 2016-08-30 05:57
I think we should commit the float 32 and 64 version and we'll try to get the declaration into Eigen as soon as we can and then update tensorflow.

**Comment by Mistobaan** [comment] 2016-08-31 01:56
@martinwicke see #4113

**Comment by martinwicke** [comment] 2016-10-26 16:12
Andrew, assigning to you to eventually close once all the new code is in.

**Comment by rmlarsen** [comment] 2019-12-17 19:29
We have implemented fast vectorized rounding in Eigen equivalent to std::round's round-half-away from zero. I wish we could make it the default.

**Comment by martinwicke** [comment] 2019-12-17 19:50
Is there a reason we cannot make it the default?

I think this is a bug. @tensorflow/api-owners

**Comment by rmlarsen** [comment] 2019-12-17 19:57
It is a bug. I'm all for making it the default if we can agree on that.

**Comment by rmlarsen** [comment] 2019-12-17 19:58
Context: https://gitlab.com/libeigen/eigen/commit/06e99aaf409eff4693c4256e59bb58313052818d

**Comment by rmlarsen** [comment] 2019-12-17 20:07
As @aselle points out, round-to-even is used in numpy.ndrray.round, so perhaps we should keep it this way. We should provide a fast implementation of that however.

**Closed** 2019-12-17 20:20 UTC
Labels: type:bug
