### ISSUE TITLE
gpt2 int8 quantization:  op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 15 (DEQUANTIZE) failed to prepare 

### ISSUE THREAD

**Issue by gyin-ai** [tensorflow/tensorflow#46844] opened 2021-02-02 00:16 UTC
TF: 2.4.1 
Huggingface/transformers: 4.2.2
Python: 3.8

**Describe the current behavior**
The int8 quantization during the exporting has no error or problem. But it would throw an error when it is invoked. 
```
RuntimeError: tensorflow/lite/kernels/dequantize.cc:61 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 15 (DEQUANTIZE) failed to prepare.
```
Note if we only use `last_hidden_state` for tflite, this would have no problem. It seems like `tf.matmul` is a problem.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import random

import numpy as np
import tensorflow as tf
from transformers import *

rng = random.Random()

gpt2_model = TFGPT2Model.from_pretrained('distilgpt2')


def get_tf_lm_head_tensor():
    gpt2_lm_pt_model = GPT2LMHeadModel.from_pretrained('distilgpt2')
    np_tensor = gpt2_lm_pt_model.lm_head.weight.detach().numpy()
    np_tensor = np.transpose(np_tensor)
    tf_lm_head_tensor = tf.convert_to_tensor(np_tensor)
    return tf_lm_head_tensor


tf_lm_head = get_tf_lm_head_tensor()

@tf.function(input_signature=[tf.TensorSpec(shape=(1, None), dtype=tf.int32, name="input_ids")])
def serving_func(input_ids):
    outputs = gpt2_model(input_ids, training=False)
    last_hidden_state = outputs[0][0][-1:, :]
    next_token_logits = tf.matmul(last_hidden_state, tf_lm_head)
    next_token = tf.math.argmax(next_token_logits, axis=-1, output_type=tf.int32)
    log_probs = tf.math.reduce_max(tf.nn.log_softmax(next_token_logits))
    return {"decoded_ids": next_token, "log_probs": log_probs}


tensors = []
for example in range(100):
    values = [[rng.randint(0, 30000) for _ in range(8)]]
    tensors.append(np.array(values, dtype=np.int32))


def representative_dataset_gen():
    for ts in tensors:
        yield [ts]


converter = tf.lite.TFLiteConverter.from_concrete_functions([serving_func.get_concrete_function(
    tf.TensorSpec(shape=(1, None), dtype=tf.int32, name='input_ids'))])
# converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS,
                                       tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_quant_model = converter.convert()
with open("/tmp/model.tflite", 'wb') as f:
    f.write(tflite_quant_model)

# invoke the model
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="/tmp/model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

import numpy as np
# Test the TensorFlow Lite model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.int32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gyin-ai** [comment] 2021-02-02 00:18
Here might be similar PRs. https://github.com/tensorflow/tensorflow/issues/31053

**Comment by abattery** [comment] 2021-02-02 05:36
Is it possible to share your converted TFLite file to us?

**Comment by gyin-ai** [comment] 2021-02-02 09:09
> Is it possible to share your converted TFLite file to us?

Hi, here is the code snippet to generate the tflite model. 
```
import random

import numpy as np
import tensorflow as tf
from transformers import *

rng = random.Random()

gpt2_model = TFGPT2Model.from_pretrained('distilgpt2')


def get_tf_lm_head_tensor():
    gpt2_lm_pt_model = GPT2LMHeadModel.from_pretrained('distilgpt2')
    np_tensor = gpt2_lm_pt_model.lm_head.weight.detach().numpy()
    np_tensor = np.transpose(np_tensor)
    tf_lm_head_tensor = tf.convert_to_tensor(np_tensor)
    return tf_lm_head_tensor


tf_lm_head = get_tf_lm_head_tensor()

@tf.function(input_signature=[tf.TensorSpec(shape=(1, None), dtype=tf.int32, name="input_ids")])
def serving_func(input_ids):
    outputs = gpt2_model(input_ids, training=False)
    last_hidden_state = outputs[0][0][-1:, :]
    next_token_logits = tf.matmul(last_hidden_state, tf_lm_head)
    next_token = tf.math.argmax(next_token_logits, axis=-1, output_type=tf.int32)
    log_probs = tf.math.reduce_max(tf.nn.log_softmax(next_token_logits))
    return {"decoded_ids": next_token, "log_probs": log_probs}


tensors = []
for example in range(100):
    values = [[rng.randint(0, 30000) for _ in range(8)]]
    tensors.append(np.array(values, dtype=np.int32))


def representative_dataset_gen():
    for ts in tensors:
        yield [ts]


converter = tf.lite.TFLiteConverter.from_concrete_functions([serving_func.get_concrete_function(
    tf.TensorSpec(shape=(1, None), dtype=tf.int32, name='input_ids'))])
# converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS,
                                       tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_quant_model = converter.convert()
with open("/tmp/model.tflite", 'wb') as f:
    f.write(tflite_quant_model)
```

To install packages, I have used 
```
pip install tensorflow==2.4.1
pip install transformers==4.2.2
```
colab. https://colab.research.google.com/drive/1lbhB7Zl5rHUXKRncE8ZH2J5izhknyQeb?usp=sharing

**Comment by abattery** [comment] 2021-02-02 09:52
FYI, I ran your colab with `pip install tf-nightly`. It worked without any errors.

**Comment by amahendrakar** [comment] 2021-02-02 12:42
@gyin-ai,
I was able to reproduce the error with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/dc8a0d5f02b4e0af412afa0a38f55097/46844.ipynb). 

However as mentioned by @abattery, the issue seems to be resolved with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/06ec1c74ae271756db28bb2a17e37128/46844-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by gyin-ai** [comment] 2021-02-03 06:02
@abattery @amahendrakar thanks a lot for your help. After installing the new tf-nightly, it did work. However I came into the following problems when I tried to do the tf profiling. 

1. Use macOS to run the code snippet. I will get the following info. I don't see this message in CoLab. 
```
2021-02-02 21:50:33.249191: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-02-02 21:50:35.650041: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1768] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexErf
Details:
        tf.Erf {device = ""}
```

2. When I tried to run the model with tf profile, https://www.tensorflow.org/tfx/serving/tensorboard. It doesn't show the tensorflow stats as before. 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/67664443/106704766-832f7e80-65a1-11eb-9ded-d0142f55ae32.png">

assume `/tmp/distilgpt2_tflite/1/model.tflite` is where the model is. 
```
mkdir -p /Users/<user_name>/logs/inference_demo/plugins/profile/
docker run --name tftest -it --entrypoint /bin/bash --mount type=bind,source=/tmp/distilgpt2_tflite/,target=/models/gpt2/ --mount type=bind,source=/Users/<user_name>/logs/inference_demo/plugins/profile/,target=/Users/<user_name>/logs/inference_demo/plugins/profile/ -p 8501:8501 -p 8500:8500 tensorflow/serving:nightly
tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=my_model --model_base_path=/models/gpt2/1/ --prefer_tflite_model=true

# outside the container
curl -d '{"inputs": [[3, 288, 831]]}' -X POST http://localhost:8501/v1/models/my_model:predict

# then the tensorboard profile would be able to capture the information
```

**Comment by abattery** [comment] 2021-02-03 06:15
As far as I know, the TensorFlow Lite does not support the performance profiling integration with TensorBoard yet. The only Erf operator, covered by the TF kernels not TFLite kernels, is shown. Looks like it is an intended behavior. CCing @yyoon

**Comment by teijeong** [comment] 2021-02-16 08:01
Unassigning model-optimization team and assigning @yyoon temporarily.

@gyin-ai, can you close this if @abattery's answer is sufficient?

**Comment by gyin-ai** [comment] 2021-04-29 03:37
@teijeong tflite doesn't convert `log_softmax` correctly. It will output a constant value for any input.

**Comment by abattery** [comment] 2021-04-29 03:44
@gyin-ai  Could you file a separate issue to keep each issue focused?

**Closed by abattery** 2021-04-29 03:44 UTC
Labels: Fixed in Nightly, ModelOptimizationToolkit, TF 2.4, comp:lite, type:bug
