### ISSUE TITLE
AttributeError: The layer has never been called and thus has no defined input shape

### ISSUE THREAD

**Issue by dlepzelter** [tensorflow/tensorflow#30770] opened 2019-07-16 19:59 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 in Docker container
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary (pip)
- TensorFlow version (use command below): 'v2.0.0-beta0-16-g1d91213fe7', '2.0.0-beta1'
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I'm currently trying to get a PMML version of a Tensorflow 2.0 model, and seem to be getting an unrelated error.

AttributeError: The layer has never been called and thus has no defined input shape.

I've looked through the things that theoretically should cause this error, and none seem to be relevant. Here's my code:

```python
def create_and_train(x_training,y_training,n_cols_in,modelparams):
    layers = [tf.keras.layers.Dense(n_cols_in,activation="relu"),
    tf.keras.layers.Dropout(.5)]
    for param in modelparams:
        layers.extend([tf.keras.layers.Dense(param,activation="sigmoid"),tf.keras.layers.Dropout(.5)])
    layers.append(tf.keras.layers.Dense(1,activation="sigmoid"))
    model = tf.keras.models.Sequential(layers)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.AUC()])
    model.fit(x_training, y_training, epochs = epochs)
    with open("NN"+"_".join([str(m) for m in modelparams])+".pmml","w") as pmml_file:
        pmml = KerasToPmml(model)
        pmml.export(pmml_file)
```

The model gets trained, and if I tell it to give me an AUC for the training set or even a test set before the PMML export, it does so without a problem. However, PMML export requires input shape, which Tensorflow claims doesn't exist.

**Comment by ravikyram** [comment] 2019-07-17 12:37
In order to expedite the trouble-shooting process, please provide a full code snippet to reproduce the issue reported here. Thanks!

**Comment by dlepzelter** [comment] 2019-07-17 13:22
Sure, though the training data is probably not small enough for a Git message attachment and not publicly available online. For the minimal reproducible version, use the following:

```python
import tensorflow as tf
from nyoka import KerasToPmml
n_cols_in = 218
modelparams = [436,]
# get training data here; I'll toss in a CSV version.
import pandas as pd
labelcol = 'MxWillReAdmit'
trainingdata = pd.read_csv('trainingfile.csv')
x_training = np.array(trainingdata.drop(labelcol,axis='columns'))
y_training = np.array(trainingdata[labelcol])

def create_and_train(x_training,y_training,n_cols_in,modelparams,epochs=10):
    layers = [tf.keras.layers.Dense(n_cols_in,activation="relu"),
    tf.keras.layers.Dropout(.5)]
    for param in modelparams:
        layers.extend([tf.keras.layers.Dense(param,activation="sigmoid"),tf.keras.layers.Dropout(.5)])
    layers.append(tf.keras.layers.Dense(1,activation="sigmoid"))
    model = tf.keras.models.Sequential(layers)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.AUC()])
    model.fit(x_training, y_training, epochs = epochs)
    with open("NN"+"_".join([str(m) for m in modelparams])+".pmml","w") as pmml_file:
        pmml = KerasToPmml(model)
        pmml.export(pmml_file)
create_and_train(x_training,y_training,n_cols_in,modelparams)
```

How should I go about sharing the training data?

**Comment by ravikyram** [comment] 2019-07-17 13:43
Can you please share the sufficient dummy data to reproduce the issue.Thanks!

**Comment by dlepzelter** [comment] 2019-07-19 19:31
Apologies for taking so long; I wanted to ensure the sample had the same problem, and for unrelated reasons ended up having to do a pretty thorough reinstallation on my system. The same problem still comes up with the data set I'm attaching.
[trainingfile.zip](https://github.com/tensorflow/tensorflow/files/3412470/trainingfile.zip)

**Comment by ravikyram** [comment] 2019-07-23 11:56
I have tried on Jupyter notebook with TF version 2.0 beta and was able to reproduce the issue.Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-25 21:56
@dlepzelter The error trace looked more related to `nyoka` than `tensorflow. Can you create the issue without using `nyoka`. thanks!

**Comment by dlepzelter** [comment] 2019-07-26 14:03
Certainly. Replace
```python
    with open("NN"+"_".join([str(m) for m in modelparams])+".pmml","w") as pmml_file:
        pmml = KerasToPmml(model)
        pmml.export(pmml_file)
```
with
```python
    print(model.input_shape())
```
and you get the same error.

**Comment by jvishnuvardhan** [comment] 2019-08-09 17:26
@dlepzelter I can reproduce the error and the error `AttributeError: The layer has never been called and thus has no defined input shape.` clearly points out input shape was not defined. This `tf.keras.layers.Dense(n_cols_in,activation="relu")` is your first layer in the model where `input_shape` was not defined.

Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/78b70e6b720a0b2b847f649c3b5d4d15/tf_30770_inputshape.ipynb). Thanks!

**Comment by dlepzelter** [comment] 2019-08-09 17:50
That makes sense, to a point. That said, the input shape is implicitly defined by the data itself, or the model wouldn't train or run. Is it intentional that an implicit input shape definition results in this error?

**Comment by jvishnuvardhan** [comment] 2019-08-22 21:10
@dlepzelter It is always suggested to use input_shape which is the best way to tell model what is expected. Model understand the shapes and infer the shape for the following layers.  

`The model needs to know what input shape it should expect. For this reason, the first layer in a sequential model (and only the first, because following layers can do automatic shape inference) needs to receive information about its input shape.`

Without an input_shape, when you check the model.summary()

`model.summary()`

```
Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_30 (Dense)             multiple                  47742     
_________________________________________________________________
dropout_20 (Dropout)         multiple                  0         
_________________________________________________________________
dense_31 (Dense)             multiple                  95484     
_________________________________________________________________
dropout_21 (Dropout)         multiple                  0         
_________________________________________________________________
dense_32 (Dense)             multiple                  437       
=================================================================
Total params: 143,663
Trainable params: 143,663
Non-trainable params: 0
_______________________
```
Model doesn't understand the what is expected shape. So, when I provided input_shape, the model summary looks clear as below. Please notice that there is no change in `trainable params` before or after adding `input_shape`

```
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_33 (Dense)             (None, 218)               47742     
_________________________________________________________________
dropout_22 (Dropout)         (None, 218)               0         
_________________________________________________________________
dense_34 (Dense)             (None, 436)               95484     
_________________________________________________________________
dropout_23 (Dropout)         (None, 436)               0         
_________________________________________________________________
dense_35 (Dense)             (None, 1)                 437       
=================================================================
Total params: 143,663
Trainable params: 143,663
Non-trainable params: 0
```
I am closing this issue. Please feel free to open the issue if it persists. Thanks!

**Closed by jvishnuvardhan** 2019-08-22 21:10 UTC
Labels: 2.0.0-beta0, comp:keras, type:support

**Comment by fused-byte** [comment] 2020-05-19 13:33
@jvishnuvardhan, If this input_shape is such an important aspect in writing the model architecture then it should be added in the documentation. The current documentation doesn't even include this as an optional parameter. Neither does the tutorial example mentions this.

And I wrote a small piece of code to check it myself and without providing input_shape I am able to get proper output shape in model summary. Here is the code.
model = Sequential()
model.add(Dense(32, input_shape=(16,)))
# now the model will take as input arrays of shape (*, 16)
# and output arrays of shape (*, 32)

# after the first layer, you don't need to specify
# the size of the input anymore:
model.add(Dense(32))

And output

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                (None, 32)                544       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
=================================================================
Total params: 1,600
Trainable params: 1,600
Non-trainable params: 0

Now my question is how the output shape is correct even after not defining input_shape?
