### ISSUE TITLE
Wrong error message for DepthwiseConv2D

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#45703] opened 2020-12-15 16:34 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 'v1.14.0-rc1-22-gaf24dc91b5', '1.14.0'
- Python version: python 2.7

**Describe the current behavior**
There seems to be a wrong error message for the DepthwiseConv2D when different kernel dimension are specified. An InvalidArgumentError that states that the strides must be equal length is produced, even though the strides are not specified and are equal per default:"Current implementation only supports equal length strides in the row and column dimensions."
The error is e.g., produced by the following code.

It works without error when the kernel dimensions are changed from (2,3) to (3,3). Hence, a correct error message that states that unequal kernel dimensions are currently also not supported would be great. It might also be good if this is mentioned in the documentation.

**Standalone code to reproduce the issue**
```
model = keras.Sequential([keras.layers.DepthwiseConv2D(3, (2, 3), depth_multiplier=4, input_shape=(3,3,3))])
x = tf.constant([[[[8,3,5],[5,4,-2],[2,1,-1]],[[8,3,5],[5,4,-2],[2,1,-1]],[[8,3,5],[5,4,-2],[2,1,-1]]]])
print np.array2string(model.predict(x,steps=1), separator=', ')
```

**Comment by ravikyram** [comment] 2020-12-16 09:23
@rschumi0 
I tried in colab with TF version 2.3 , nightly version(`2.5.0-dev20201215`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/8d2b09537dcb336160145bd8f9538f10/untitled578.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2020-12-22 10:09
@rschumi0,
The **`Error Message`** is expected because, as per the [Documentation of DepthwiseConv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/DepthwiseConv2D#arguments), second argument is **`Strides`**, and hence the **`Error Message`** is related to **`Strides`**.

**Comment by rmothukuru** [comment] 2021-01-04 08:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2021-01-04 08:02 UTC
Labels: TF 1.14, comp:keras, stalled, stat:awaiting response, type:support
