### ISSUE TITLE
Could not find valid device for node. Node: {{node NonMaxSuppressionV4}}

### ISSUE THREAD

**Issue by Xie-Fangyuan** [tensorflow/tensorflow#33685] opened 2019-10-24 13:32 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **tensorflow 1.14.0**
- Python version: **3.7.3**

i was trying to use `tf.image.non_max_suppression_padded()`, but i got an error, maybe i write a wrong code, hope somebody can help.

test code:

```python
import tensorflow as tf
import numpy as np

np.random.seed(0)

num_objs_per_img = 10

boxes = np.sort(np.random.rand(num_objs_per_img, 4))
scores = np.random.rand(num_objs_per_img)

idx = tf.image.non_max_suppression_padded(boxes, scores, max_output_size=7, iou_threshold=0.7)
print(idx)
```

terminal log:

```text
Traceback (most recent call last):
  File "draft.py", line 11, in <module>
    idx = tf.image.non_max_suppression_padded(boxes, scores, max_output_size=7, iou_threshold=0.7)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 2646, in non_max_suppression_padded
    pad_to_max_output_size)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 2561, in non_max_suppression_v4
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Could not find valid device for node.
Node: {{node NonMaxSuppressionV4}}
All kernels registered for op NonMaxSuppressionV4 :
  device='XLA_GPU'; T in [DT_FLOAT, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_HALF]
  device='XLA_CPU'; T in [DT_FLOAT, DT_HALF]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
 [Op:NonMaxSuppressionV4]
```

**Comment by ravikyram** [comment] 2019-10-25 05:34
@Xie-Fangyuan 

I tried to execute your code with TF 1.14. However i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/7d6708be5be58ef979892901471c034b/untitled299.ipynb).Thanks!

**Comment by Xie-Fangyuan** [comment] 2019-10-25 05:51
sorry, I didn't realize that I was also using eager execution. and I use CPU to run.

here is the new test code:

```python
from tensorflow.compat.v1 import enable_eager_execution
import tensorflow as tf
import numpy as np
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
enable_eager_execution()
np.random.seed(0)

num_objs_per_img = 10

boxes = np.sort(np.random.rand(num_objs_per_img, 4))
scores = np.random.rand(num_objs_per_img)

idx = tf.image.non_max_suppression_padded(boxes, scores, max_output_size=7, iou_threshold=0.7)
print(idx)
```

it did show the error logs. should I use without eager execution when using nms?

**Comment by ravikyram** [comment] 2019-10-29 11:41
I have tried on colab with TF version 1.14,1.15.0-rc3 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/30062ca18ac915e01acfb42473d3603b/untitled314.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-30 00:37
@Xie-Fangyuan I think the error was due to `dtype` of `boxes` and `scores`. When I converted both the dtypes to `tf.float32`, there was no error. 

The two lines of code I added is here
```
boxes = np.sort(np.random.rand(num_objs_per_img, 4))
boxes = tf.dtypes.cast(boxes,tf.float32)
scores = np.random.rand(num_objs_per_img)
scores = tf.dtypes.cast(scores,tf.float32)
```

Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ef0802b70622b3294a251108bd3ee5a5/untitled314.ipynb). 

I am closing this issue as it was resolved. Please feel free to open the issue if it persists again. Thanks!

**Closed by jvishnuvardhan** 2019-10-30 00:37 UTC
Labels: TF 1.14, TF 1.15, comp:ops, type:bug

**Comment by Xie-Fangyuan** [comment] 2019-10-30 03:06
really thanks! float32 works well.

**Comment by Freen247** [comment] 2020-03-10 08:52
float32 works well.

**Comment by BDEvan5** [comment] 2020-06-11 10:19
https://medium.com/@HojjatA/could-not-find-valid-device-for-node-while-eagerly-executing-8f2ff588d1e

Great fix to the problem

**Comment by tusharkudal** [comment] 2020-07-24 14:30
I got a similar error but in my case pbtxt file for the tfrecord had a problem, try checking that also.

**Comment by samozturk** [comment] 2020-12-05 19:55
I think your value should be float as error message says. I have encountered the same problem while finding the determinant of a matrix and changed the dtype to float32 and problem solved.
