### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (up_sampling2d_5_target_2:0) to a numpy array.

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#37177] opened 2020-02-28 23:59 UTC
```
import keras.backend as K
from keras.optimizers import Adam
from keras.losses import binary_crossentropy

## intersection over union
def IoU(y_true, y_pred, eps=1e-6):
    print(y_true)
    if np.max(y_true) == 0.0:
        return IoU(1-y_true, 1-y_pred) ## empty image; calc IoU of zeros
    #if 0 == K.equal(y_true, 0):
    #    y_true = K.switch(0, 1-y_true, y_true)
    #    y_pred = K.switch(0, 1-y_pred, y_pred)
    #    return IoU(1-y_true, 1-y_pred) ## empty image; calc IoU of zeros
        
    intersection = K.sum(y_true * y_pred, axis=[1,2,3])
    union = K.sum(y_true, axis=[1,2,3]) + K.sum(y_pred, axis=[1,2,3]) - intersection
    return -K.mean( (intersection + eps) / (union + eps), axis=0)
```

> Tensor("up_sampling2d_5_target_2:0", shape=(None, None, None, None), dtype=float32)
> ---------------------------------------------------------------------------
> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-26-466b05eae4fa> in <module>
>      14 
>      15 while True:
> ---> 16     loss_history = fit()
>      17     if np.min([mh.history['val_loss'] for mh in loss_history]) < -0.2:
>      18         break
> 
> <ipython-input-26-466b05eae4fa> in fit()
>       1 def fit():
> ----> 2     seg_model.compile(optimizer=Adam(1e-3, decay=1e-6), loss=IoU, metrics=['binary_accuracy'])
>       3 
>       4     step_count = min(MAX_TRAIN_STEPS, train_df.shape[0]//BATCH_SIZE)
>       5     aug_gen = create_aug_gen(make_image_gen(train_df))
> 
> ~/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
>      73         if _SYMBOLIC_SCOPE.value:
>      74             with get_graph().as_default():
> ---> 75                 return func(*args, **kwargs)
>      76         else:
>      77             return func(*args, **kwargs)
> 
> ~/venv/lib/python3.7/site-packages/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
>     227         #                   loss_weight_2 * output_2_loss_fn(...) +
>     228         #                   layer losses.
> --> 229         self.total_loss = self._prepare_total_loss(masks)
>     230 
>     231         # Functions for train, test and predict will
> 
> ~/venv/lib/python3.7/site-packages/keras/engine/training.py in _prepare_total_loss(self, masks)
>     690 
>     691                     output_loss = loss_fn(
> --> 692                         y_true, y_pred, sample_weight=sample_weight)
>     693 
>     694                 if len(self.outputs) > 1:
> 
> ~/venv/lib/python3.7/site-packages/keras/losses.py in __call__(self, y_true, y_pred, sample_weight)
>      69         scope_name = 'lambda' if self.name == '<lambda>' else self.name
>      70         with K.name_scope(scope_name):
> ---> 71             losses = self.call(y_true, y_pred)
>      72             return losses_utils.compute_weighted_loss(
>      73                 losses, sample_weight, reduction=self.reduction)
> 
> ~/venv/lib/python3.7/site-packages/keras/losses.py in call(self, y_true, y_pred)
>     130             Loss values per sample.
>     131         """
> --> 132         return self.fn(y_true, y_pred, **self._fn_kwargs)
>     133 
>     134     def get_config(self):
> 
> <ipython-input-24-d1d9fb424ded> in IoU(y_true, y_pred, eps)
>       6 def IoU(y_true, y_pred, eps=1e-6):
>       7     print(y_true)
> ----> 8     if np.max(y_true) == 0.0:
>       9         return IoU(1-y_true, 1-y_pred) ## empty image; calc IoU of zeros
>      10     #if 0 == K.equal(y_true, 0):
> 
> <__array_function__ internals> in amax(*args, **kwargs)
> 
> ~/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial, where)
>    2619     """
>    2620     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
> -> 2621                           keepdims=keepdims, initial=initial, where=where)
>    2622 
>    2623 
> 
> ~/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
>      88                 return reduction(axis=axis, out=out, **passkwargs)
>      89 
> ---> 90     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
>      91 
>      92 
> 
> ~/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __array__(self)
>     734   def __array__(self):
>     735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
> --> 736                               " array.".format(self.name))
>     737 
>     738   def __len__(self):
> 
> NotImplementedError: Cannot convert a symbolic Tensor (up_sampling2d_5_target_2:0) to a numpy array.

**Comment by gadagashwini** [comment] 2020-03-02 06:00
@SlowMonk, thanks for reporting this issue.
Can you post the complete code to replicate the reported issue and also provide Tensorflow version that you are using. Thanks

**Comment by SlowMonk** [comment] 2020-03-02 07:07
import keras
import tensorflow as tf
print(keras.__version__)
print(tf.__version__)
2.3.1
2.0.0

**Comment by gadagashwini** [comment] 2020-03-04 09:58
@SlowMonk, I tried replicating the issue with Tf 2.0 but looks like code is incomplete to reproduce the issue. Please take a look at gist [here](https://colab.sandbox.google.com/gist/gadagashwini/be6355138fa9668e4faaf7fc25d48730/untitled415.ipynb). Thanks!

**Comment by gadagashwini** [comment] 2020-03-13 10:01
@SlowMonk, Did you check the above provided gist.

**Comment by gadagashwini** [comment] 2020-03-26 07:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-03-26 07:48 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by sujanme25** [comment] 2020-06-20 11:29
NotImplementedError                       Traceback (most recent call last)
<ipython-input-36-6d13580ffc58> in <module>
      5 
      6     # Synthetic Data Generation
----> 7     dataX_hat, loss_list = timegan(dataX, parameters)  # Returns to synthetic dataset and stored loss values
      8     losses.append(loss_list)
      9     print('Finish Synthetic Data Generation')

D:\Juypter_Sujan\CS591_TimeGAN\tgan.py in timegan(data, params)
    184     # LOSSES
    185 
--> 186     D_loss, G_loss, S_loss, E_loss, E_loss_only, G_loss_adv_sup, G_loss_V = get_losses(Y_real, Y_fake, Y_fake_sup, H, H_sup, X_tilde_fake_sup, X, X_tilde)
    187 
    188 

D:\Juypter_Sujan\CS591_TimeGAN\tgan.py in get_losses(Y_real, Y_fake, Y_fake_sup, H, H_sup, X_tilde_fake_sup, X, X_tilde)
    115       G_loss_adv = tf.losses.sigmoid_cross_entropy(tf.ones_like(Y_fake), Y_fake)
    116       #generator mean and variance difference L1 loss
--> 117       G_loss_V1 = tf.reduce_mean(np.abs(tf.sqrt(tf.nn.moments(X_tilde_fake_sup,[0])[1] + 1e-6) - tf.sqrt(tf.nn.moments(X,[0])[1] + 1e-6)))
    118       G_loss_V2 = tf.reduce_mean(np.abs((tf.nn.moments(X_tilde_fake_sup,[0])[0]) - (tf.nn.moments(X,[0])[0])))
    119       G_loss_V = G_loss_V1 + G_loss_V2

D:\Anaconda\lib\site-packages\tensorflow_core\python\framework\ops.py in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (sub:0) to a numpy array.

**Comment by sujanme25** [comment] 2020-06-20 11:30
complete code as below

def timegan(data, params):
    tf.reset_default_graph()
    data_len = len(data)
    data_dim = len(data[0][0,:])
    max_seq_len = len(data[0][:,0])
    seq_len_list = []

    for i in range(data_len):
        seq_len = len(data[i][:,0])
        seq_len_list.append(seq_len)
        if max_seq_len < seq_len:
            max_seq_len = seq_len
    
    # Get Parameters
    hidden_dim   = params['hidden_dim'] 
    num_layers   = params['num_layers']
    iterations   = params['iterations']
    batch_size   = params['batch_size']
    module_name  = params['module_name']  
    z_dim        = params['z_dim']
    gamma        = 1
    
    # input place holders
    
    X = tf.placeholder(tf.float32, [None, max_seq_len, data_dim], name = "input_x")
    Z = tf.placeholder(tf.float32, [None, max_seq_len, params['z_dim']], name = "input_z")
    T = tf.placeholder(tf.int32, [None], name = "input_t")

    
    
    H = embedder(X, T, params) # input mapped into the embedding space
    X_tilde = recovery(H, T, params, data_dim) # recovered input with recovery function
    
    # Generator
    H_fake = generator(Z, T, params) # Generated data
    H_fake_sup = supervisor(H_fake, T, params) # Supervising the fake data
    H_sup = supervisor(H, T, params) # Supervising the real data
    
    # Synthetic data
    X_tilde_fake_sup = recovery(H_fake_sup, T, params, data_dim) # Fake data recovered
    
    # Discriminator
    Y_fake_sup = discriminator(H_fake_sup, T, params)  #Supervised fake data classification outputs
    Y_real = discriminator(H, T, params) # Real data classification outputs
    Y_fake = discriminator(H_fake, T, params) #Fake data classification outputs
    
    # Variables        
    emb_vars = [v for v in tf.trainable_variables() if v.name.startswith('embedder')]
    rec_vars = [v for v in tf.trainable_variables() if v.name.startswith('recovery')]
    gen_vars = [v for v in tf.trainable_variables() if v.name.startswith('generator')]
    sup_vars = [v for v in tf.trainable_variables() if v.name.startswith('supervisor')]
    dis_vars = [v for v in tf.trainable_variables() if v.name.startswith('discriminator')]
    
    # LOSSES
   
    D_loss, G_loss, S_loss, E_loss, E_loss_only, G_loss_adv_sup, G_loss_V = get_losses(Y_real, Y_fake, Y_fake_sup, H, H_sup, X_tilde_fake_sup, X, X_tilde)
    
     
    # optimizer
    E0_opt = tf.train.AdamOptimizer().minimize(E_loss_only, var_list = emb_vars + rec_vars)
    E_opt = tf.train.AdamOptimizer().minimize(E_loss, var_list = emb_vars + rec_vars)
    D_opt = tf.train.AdamOptimizer().minimize(D_loss, var_list = dis_vars)
    G_opt = tf.train.AdamOptimizer().minimize(G_loss, var_list = gen_vars + sup_vars)      
    S_opt = tf.train.AdamOptimizer().minimize(S_loss, var_list = gen_vars + sup_vars)   
    
    
    session = tf.Session()
    session.run(tf.global_variables_initializer())
    e_loss_list = []
    s_loss_list = []
    d_loss_list = []
    g_loss_adv_list = []
    g_loss_v_list = []
    e_loss_joint_list = []
    s_loss_joint_list = []        
    #Embedder training
    
    for i in range(params['iterations']):
        
        # Batch setting
        index = np.random.permutation(data_len)
        train_index = index[:params['batch_size']]   
            
        X_mb = list(data[j] for j in train_index)
        T_mb = list(seq_len_list[j] for j in train_index)
            
        # Train embedder        
        _, step_e_loss = session.run([E0_opt, E_loss_only], feed_dict={X: X_mb, T: T_mb})
        
        if i % 10 == 0:
            print('step: '+ str(i) + ', e_loss: ' + str(np.round(np.sqrt(step_e_loss),4)) ) 
            e_loss_list.append(np.round(np.sqrt(step_e_loss),4))
    
    # Supervisor training
    
    for i in range(params['iterations']):
        
        # Batch setting
        index = np.random.permutation(data_len)
        train_index = index[:params['batch_size']]   
            
        X_mb = list(data[j] for j in train_index)
        T_mb = list(seq_len_list[j] for j in train_index)      
        
        Z_mb = random_generator(params['batch_size'], params['z_dim'], T_mb, max_seq_len)
        
        # Train generator       
        _, step_s_loss = session.run([S_opt, S_loss], feed_dict={Z: Z_mb, X: X_mb, T: T_mb})

                           
        if i % 10 == 0:
            print('step: '+ str(i) + ', s_loss: ' + str(np.round(np.sqrt(step_s_loss),4)))
            s_loss_list.append(np.round(np.sqrt(step_s_loss),4))
    #Joint Training
            
    for i in range(params['iterations']):
      
        # Generator Training
        for kk in range(2): #FIXME: Why 2 ?
          
            # Batch setting
            index = np.random.permutation(data_len)
            train_index = index[:params['batch_size']] 
            
            X_mb = list(data[j] for j in train_index)
            T_mb = list(seq_len_list[j] for j in train_index)     
            
            # Random vector generation
            Z_mb = random_generator(params['batch_size'], params['z_dim'], T_mb, max_seq_len)
            
            # Train generator
            _, step_g_loss_adv, step_s_loss, step_g_loss_v = session.run([G_opt, G_loss_adv_sup, S_loss, G_loss_V], feed_dict={Z: Z_mb, X: X_mb, T: T_mb})
            
            # Train embedder        
            _, step_e_loss_only = session.run([E_opt, E_loss_only], feed_dict={Z: Z_mb, X: X_mb, T: T_mb})   
           
        # Discriminator Training
        
        # Batch setting
        index = np.random.permutation(data_len)
        train_index = index[:params['batch_size']]  
        
        X_mb = list(data[j] for j in train_index)
        T_mb = list(seq_len_list[j] for j in train_index)  
        
        # Random vector generation
        Z_mb = random_generator(params['batch_size'], params['z_dim'], T_mb, max_seq_len)
            
        
        d_loss = session.run(D_loss, feed_dict={X: X_mb, T: T_mb, Z: Z_mb})
        
        # Train discriminator
        
        if (d_loss > 0.15):        
            _, step_d_loss = session.run([D_opt, D_loss], feed_dict={X: X_mb, T: T_mb, Z: Z_mb})
        
        # Checkpoints
        if i % 10 == 0:
            print('step: '+ str(i) + 
                  ', d_loss: ' + str(np.round(step_d_loss,4)) + 
                  ', g_loss_adv: ' + str(np.round(step_g_loss_adv,4)) + 
                  ', s_loss: ' + str(np.round(np.sqrt(step_s_loss),4)) + 
                  ', g_loss_v: ' + str(np.round(step_g_loss_v,4)) + 
                  ', e_loss_t0: ' + str(np.round(np.sqrt(step_e_loss_only),4)))
            d_loss_list.append(np.round(step_d_loss,4))
            g_loss_adv_list.append(np.round(step_g_loss_adv,4))
            g_loss_v_list.append(np.round(step_g_loss_v,4))
            s_loss_joint_list.append(np.round(np.sqrt(step_s_loss),4))
            e_loss_joint_list.append(np.round(np.sqrt(step_e_loss_only),4))
            
        
    Z_mb = random_generator(data_len, params['z_dim'], seq_len_list, max_seq_len)
    out = session.run(X_tilde_fake_sup, feed_dict={Z: Z_mb, X: data, T: seq_len_list}) 
    loss_list = [e_loss_list, s_loss_list, d_loss_list, g_loss_adv_list, g_loss_v_list, e_loss_joint_list, s_loss_joint_list ]
    output = []
    for i in range(data_len):
        temp_out = out[i,:seq_len_list[i],:]
        output.append(temp_out)   
        
    return output, loss_list
