### ISSUE TITLE
Show location of using uninitialized variable in the stacktrace

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#8162] opened 2017-03-07 09:08 UTC
It's currently hard to debug initialization of multiple variables with initial values depending on each other:

```python
a = tf.Variable(42)
b = tf.Variable(some_function(a.value()))
```

The current error message has the form `FailedPreconditionError (see above for traceback): Attempting to use uninitialized value a` and the traceback points to `sess.run(tf.global_variables_initializer())`. However, the place for fixing this problem is the declaration of `b`:

```python
a = tf.Variable(42)
b = tf.Variable(some_function(a.initialized_value()))
```

Would it be possible to add the line that defines the uninitialized access to the traceback?

**Comment by MicaelCarvalho** [comment] 2017-03-07 13:10
Have you tried initializing local variables as well? Maybe you have a local dependency in your function `some_function`.

`sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])`

If you can provide a code that reproduces the problem, it can be easier to debug. I ran the lines you provided, but they work fine here. ;-)

**Comment by asimshankar** [comment] 2017-04-04 19:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-04 19:38 UTC
Labels: stat:awaiting response
