### ISSUE TITLE
No gradient defined for operation RaggedTensorFromVariant

### ISSUE THREAD

**Issue by malsulaimi** [tensorflow/tensorflow#42189] opened 2020-08-10 14:33 UTC
hello , 

I having an issue with training a simple model with RaggedTensors and Tendorflow is throwing the below error :
`"No gradient defined for operation RaggedTensorFromVariant"`
**System information**
-Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
-OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
-Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
-TensorFlow installed from (source or binary): Binary
-TensorFlow version (use command below): '2.3.0'
-Python version: 3.7
-Bazel version (if compiling from source): NA
-GCC/Compiler version (if compiling from source): NA
-CUDA/cuDNN version: 10.1
-GPU model and memory: RTX 2080 TI
You can collect some of this information using our environment capture

**Describe the current behavior**
I'm unable to calculate the gradient of the dense values of a Ragged Tensor when RaggedTensors has been  used inside tf.map_fn.  below is the error that i get when running my code : 
`LookupError: No gradient defined for operation 'map_16/RaggedFromVariant/RaggedTensorFromVariant' (op type: RaggedTensorFromVariant)`

**Describe the expected behavior**
I believe that tensorflow should be able to handle such operations and be able to calculate the gradient especially that the values component of a raggedTensor is normal dense Tensor.  
**Standalone code to reproduce the issue**
```
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
tf.disable_v2_behavior()
import numpy as np 
myTensor = tf.ragged.placeholder(dtype=tf.float32 , ragged_rank=1)
def matmul_ragged( a) : 
    tens= a 
    con5 = tf.Variable([[0.1 , 2.11 , 11.2 ] ,[5.0 , 0.0 , 15.11 ] ])
    mat=tf.matmul(tens,con5)
    return mat
 
struct = tf.RaggedTensorSpec(shape=[None,None] , ragged_rank=0 ,dtype=tf.float32)
final_answer = tf.map_fn(matmul_ragged ,myTensor, fn_output_signature=struct)
print(final_answer)
loss = tf.reduce_mean(final_answer.values)
optimizer = tf.train.AdamOptimizer(learning_rate=.001)  # Adam Optimizer
opt_op = optimizer.minimize(loss)

with tf.Session() as sess : 
    sess.run(tf.global_variables_initializer())
    vals =tf.ragged.RaggedTensorValue(np.array([[1.0, 2.2 ]  , [4.0, 5.0]  , [6.0, 7.0] ,  [8.0, 9.0] , [10.11, 10.11]]) , np.array([0, 2, 5]))
    re    = sess.run([final_answer  ] , feed_dict={myTensor:vals} )
    print(re)
```

Below is a error stack that I get 

```
LookupError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\ops\gradients_util.py in _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients, src_graph)
    606           try:
--> 607             grad_fn = ops.get_gradient_function(op)
    608           except LookupError:

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\framework\ops.py in get_gradient_function(op)
   2654     op_type = op.type
-> 2655   return _gradient_registry.lookup(op_type)
   2656 

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\framework\registry.py in lookup(self, name)
     96       raise LookupError(
---> 97           "%s registry has no entry for: %s" % (self._name, name))

LookupError: gradient registry has no entry for: RaggedTensorFromVariant

During handling of the above exception, another exception occurred:

LookupError                               Traceback (most recent call last)
<ipython-input-17-8c10c3f6b529> in <module>
     23 loss = tf.reduce_mean(final_answer.values)
     24 optimizer = tf.train.AdamOptimizer(learning_rate=.001)  # Adam Optimizer
---> 25 opt_op = optimizer.minimize(loss)
     26 
     27 with tf.Session() as sess :

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\training\optimizer.py in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    401         aggregation_method=aggregation_method,
    402         colocate_gradients_with_ops=colocate_gradients_with_ops,
--> 403         grad_loss=grad_loss)
    404 
    405     vars_with_grad = [v for g, v in grads_and_vars if g is not None]

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\training\optimizer.py in compute_gradients(self, loss, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, grad_loss)
    510         gate_gradients=(gate_gradients == Optimizer.GATE_OP),
    511         aggregation_method=aggregation_method,
--> 512         colocate_gradients_with_ops=colocate_gradients_with_ops)
    513     if gate_gradients == Optimizer.GATE_GRAPH:
    514       grads = control_flow_ops.tuple(grads)

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\ops\gradients_impl.py in gradients(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients)
    170         ys, xs, grad_ys, name, colocate_gradients_with_ops,
    171         gate_gradients, aggregation_method, stop_gradients,
--> 172         unconnected_gradients)
    173   # pylint: enable=protected-access
    174 

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\ops\gradients_util.py in _GradientsHelper(ys, xs, grad_ys, name, colocate_gradients_with_ops, gate_gradients, aggregation_method, stop_gradients, unconnected_gradients, src_graph)
    621               raise LookupError(
    622                   "No gradient defined for operation '%s' (op type: %s)" %
--> 623                   (op.name, op.type))
    624         if loop_state:
    625           loop_state.EnterGradWhileContext(op, before=False)

LookupError: No gradient defined for operation 'map_16/RaggedFromVariant/RaggedTensorFromVariant' (op type: RaggedTensorFromVariant)`

```
I would appreciate your help to fix this bug or if possible guide me on a work around. 

Thanks

**Comment by amahendrakar** [comment] 2020-08-11 06:52
@malsulaimi,
I was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5a14e109b1f1862309ea7947a64c23d4/42189-tf-nightly.ipynb). 

Also, please take a look at [this workaround](https://groups.google.com/a/tensorflow.org/d/msg/discuss/P63KdpGGwvA/1ks-INGBAwAJ)  and let us know if it helps. Thanks!

**Comment by malsulaimi** [comment] 2020-08-11 18:23
@amahendrakar Thank you very much for the fast response . I tried to apply the work around , but I'm getting a gradient related error : 

This is my new code : 
```

@tf.RegisterGradient("RaggedTensorFromVariant")
def _RaggedTensorFromVariantGrad(op,grad,foo): 
    return [tf.cast(tf.zeros_like(foo), tf.variant)]

myTensor = tf.ragged.placeholder(dtype=tf.float32 , ragged_rank=1)
         
def matmul_ragged( a) : 
    tens= a 
    con5 = tf.Variable([[0.1 , 2.11 , 11.2 ] ,[5.0 , 0.0 , 15.11 ] ])
    mat=tf.matmul(tens,con5)
    return mat
 
def matmul_ragged2( a) : 
    tens=a
    con5 =tf.Variable([[0.1 , 2.0 , 11.0 ,0.1 ] ,[5.0 , 0.0 , 15.1 ,-10.2 ] ,[5.0 , 0.0 , 15.0 , 11.0 ]])
    mat=tf.matmul(tens,con5)
    mat=tf.transpose(mat)
    return mat    



final_answer =tf.map_fn(matmul_ragged,myTensor)

print(final_answer)
loss = tf.reduce_mean(final_answer)
optimizer = tf.train.AdamOptimizer(learning_rate=.001)  # Adam Optimizer
opt_op = optimizer.minimize(loss)

with tf.Session() as sess : 
    sess.run(tf.global_variables_initializer())
    vals =tf.ragged.RaggedTensorValue(np.array([[1.0, 2.2 ]  , [4.0, 5.0]  , [6.0, 7.0] ,  [8.0, 9.0]]) , np.array([0, 2, 4]))
    re , re1, re2    = sess.run([opt_op   ] , feed_dict={myTensor:vals} )
    print(re)
    print(re1)
    print(re2)

```


below is the error stack : 

```

tf.RaggedTensor(values=Tensor("map/RaggedFromVariant/RaggedTensorFromVariant:1", dtype=float32), row_splits=Tensor("map/RaggedFromVariant/RaggedTensorFromVariant:0", shape=(?,), dtype=int64))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-2073a7dbe0e4> in <module>
     30 loss = tf.reduce_mean(final_answer)
     31 optimizer = tf.train.AdamOptimizer(learning_rate=.001)  # Adam Optimizer
---> 32 opt_op = optimizer.minimize(loss)
     33 
     34 with tf.Session() as sess :

C:\ProgramData\Anaconda3\envs\AutoEncoder\lib\site-packages\tensorflow\python\training\optimizer.py in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    408           "No gradients provided for any variable, check your graph for ops"
    409           " that do not support gradients, between variables %s and loss %s." %
--> 410           ([str(v) for _, v in grads_and_vars], loss))
    411 
    412     return self.apply_gradients(grads_and_vars, global_step=global_step,

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'map/while/Variable:0' shape=(2, 3) dtype=float32_ref>"] and loss Tensor("RaggedReduceMean/truediv:0", shape=(), dtype=float32).
```

**Comment by kentslaney** [comment] 2020-08-13 14:58
I think this code is closer to what you want (2 arg version necessary for tf.function):
```python
from tensorflow.raw_ops import RaggedTensorToVariant

@tf.RegisterGradient("RaggedTensorFromVariant")
def _RaggedTensorFromVariantGrad(*args):
    if len(args) == 2:
        op, grad = args
        res = [RaggedTensorToVariant(rt_nested_splits=[], rt_dense_values=grad,
                                      batched_input=False)]
    else:
        op, empty, grad = args
        res = [RaggedTensorToVariant(rt_nested_splits=[op.outputs[0]], rt_dense_values=grad,
                                    batched_input=True)]
```
It seems to sort of work in eager mode (for a few hundred steps in the model I'm trying to get working), but I get the same error you do in your colab, making me think there's another op in that graph that doesn't support gradients. It breaks immediately if you put `tf.function` around it though, with this error, potentially related to the no gradients problem:
```
OP_REQUIRES failed at constant_op.cc:288 : Internal: No unary variant unary_op function found for unary variant op enum: 1 Variant type_name: tensorflow::Tensor for device type: CPU
```

**Comment by amahendrakar** [comment] 2020-08-18 10:47
@malsulaimi,
Could you please check @kentslaney's comment and let us know if it helps. Thanks!

**Comment by kentslaney** [comment] 2020-08-18 11:17
I'd be surprised if that fixed it on its own, I had to write a custom op to register the zeros unary op for a tensor type variant
```cpp
#include "tensorflow/core/util/tensor_ops_util.h"

using namespace tensorflow;

using CPUDevice = Eigen::ThreadPoolDevice;

REGISTER_UNARY_VARIANT_UNARY_OP_FUNCTION(ZEROS_LIKE_VARIANT_UNARY_OP, DEVICE_CPU, Tensor, ZerosLikeTensor<CPUDevice>);
```
```cpp
#if GOOGLE_CUDA
#define EIGEN_USE_GPU

#include "tensorflow/core/util/tensor_ops_util.h"

using namespace tensorflow;

using GPUDevice = Eigen::GpuDevice;

REGISTER_UNARY_VARIANT_UNARY_OP_FUNCTION(ZEROS_LIKE_VARIANT_UNARY_OP, DEVICE_GPU, Tensor, ZerosLikeTensor<GPUDevice>);
#endif
```
I'm now getting
```
2020-08-18 04:07:16.182610: F tensorflow/core/framework/tensor.cc:673] Check failed: 1 == NumElements() (1 vs. 4)Must have a one element tensor
```
I'll have to build from source with debugging mode later this week to get the stack trace and hopefully figure out what went wrong. I suspect it has to do with the wrapper variant that `RaggedTensorToVariant` puts around the output based on the numbers. As far as I can tell `RaggedTensor`s don't have a separate `tf.variant` class like `TensorList`s do in the unary op registry, but I'm not sure why. Let me know if you have any ideas on the error or see something wrong with my op @amahendrakar

**Comment by kentslaney** [comment] 2020-08-18 20:19
Actually, it turns out it was a separate problem, after compiling and loading the above I got it to run in static graph

**Comment by amahendrakar** [comment] 2020-08-25 14:35
> @malsulaimi,
> Could you please check @kentslaney's comment and let us know if it helps. Thanks!

@malsulaimi,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-08-25 14:35 UTC
Labels: TF 2.3, comp:ops, stat:awaiting response, type:support

**Comment by amahendrakar** [comment] 2020-08-25 14:37
> Actually, it turns out it was a separate problem, after compiling and loading the above I got it to run in static graph

@kentslaney,
If you still need help with the problem, please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
