### ISSUE TITLE
Keras model training is slow without "tf.compat.v1.disable_eager_execution()"

### ISSUE THREAD

**Issue by ducvinh-nguyen** [tensorflow/tensorflow#57645] opened 2022-09-08 16:46 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04 in WSL2

### Python version

3.8.13

### Current Behaviour?

In documentation, keras.model.fit() runs in graph mode by default, even if eager mode is by default in TF2.x. So I expect that training a simple keras model (13 parameters) should be fast. But it is very slow on my computer (~30s). However, it will be 10 times faster (~3s) if I add this line in the code: tf.compat.v1.disable_eager_execution()
It seems that keras fit function do not run in graph mode(?). Adding "run_eagerly=False" option while compiling the model do not solve the problem. Is this a bug ?
As a workaround, is there another way to disable eager mode globally in TF2 ? The command "tf.compat.v1.disable_eager_execution()" works but changes something in TF behavior behind the scences. In my case, when using this command, I cannot use predict function of my trained model which was cached in the Streamlit framework (using @st.cache(allow_output_mutation=True) or @st.experimental_singleton). The following error arises:
"InvalidArgumentError: Tensor input_1:0, specified in either feed_devices or fetch_devices was not found in the Graph" (traceback in log output)
This does not happen when disable_eager_execution() is not used.
Thank you!
```


### Standalone code to reproduce the issue

```shell
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input
from tensorflow.keras.initializers import RandomNormal
from tensorflow.keras.optimizers import Adam

from datetime import datetime

# Do not use GPU
tf.config.set_visible_devices([], "GPU")
# tf.compat.v1.disable_eager_execution()  # adding this line make keras training much faster

# Generate data
def f(x):
    return (x + 1) * np.sin(5 * x)


x_plot = np.arange(-1, 1 + 0.001, 0.001)
y_plot = f(x_plot)

x_train = np.arange(-1 + 0.05, 1, 0.2)
y_train = f(x_train)

x_val = np.arange(-1 + 0.15, 1, 0.2)
y_val = f(x_val)

# Plot the problem
plt.figure()
plt.plot(x_plot, y_plot, "-", label="Orgininal function")
plt.plot(x_train, y_train, "o", label="Training points")
plt.plot(x_val, y_val, "s", label="Validation points")
plt.xlim(-1, 1)
plt.ylim(-2, 2)
plt.xlabel("x")
plt.ylabel("f")
plt.grid()
plt.legend()
plt.show(block=False)

# Reshape
X_train = x_train.reshape(x_train.shape[0], 1)
Y_train = y_train.reshape(x_train.shape[0], 1)

X_val = x_val.reshape(x_val.shape[0], 1)
Y_val = y_val.reshape(x_val.shape[0], 1)

# Simple model
tf.keras.utils.set_random_seed(1)
model = Sequential()
model.add(Input(shape=(1,)))  # Input layer
model.add(
    Dense(
        4,
        activation="sigmoid",
        kernel_initializer=RandomNormal(mean=0.0, stddev=1.0, seed=1),
    )
)
model.add(Dense(1))

model.compile(loss="mean_squared_error", optimizer=Adam(learning_rate=3e-1))

start_time = datetime.now()
history = model.fit(
    X_train,
    Y_train,
    validation_split=0.0,
    validation_data=(X_val, Y_val),
    validation_freq=1,
    batch_size=X_train.shape[0],
    epochs=2000,
    verbose=0,
)

run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
```

### Relevant log output

```shell
InvalidArgumentError: Tensor input_1:0, specified in either feed_devices or fetch_devices was not found in the Graph
Traceback:
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/streamlit/scriptrunner/script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
File "dashboard.py", line 227, in <module>
    Y_train_pred = model.predict(X_train)
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/keras/engine/training_v1.py", line 969, in predict
    return func.predict(
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 700, in predict
    return predict_loop(
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 377, in model_iteration
    batch_outs = f(ins_batch)
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/keras/backend.py", line 4282, in __call__
    self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/keras/backend.py", line 4218, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1513, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
File "/home/vinh/miniconda3/envs/data/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1471, in __init__
    self._handle = tf_session.TF_SessionMakeCallable(
```
</details>

**Comment by tilakrayal** [comment] 2022-09-09 10:26
@ducvinh9,
I was able to execute the code with out any issue/error on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/d2b792581460db70385532458e62496c/untitled580.ipynb) and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0c33fe9588906eafd35f134f9815e234/untitled581.ipynb). Thank you!

**Comment by ducvinh9** [comment] 2022-09-09 11:28
@tilakrayal,
The notebook you provided exhibits my observation, or the issue. TF.keras take 42s to train a very simple model. Add if ou decomment the line "tf.compat.v1.disable_eager_execution()", the training takes only 3s. Can you explain this strange difference, considering the fact that keras is said to be running in graph mode internally ? This is my main issue, not that there are immediate error in the code.

The error I provided happens when reload a model(and use it to predict) which was previous cached in Streamlit; that does not happen without the line "tf.compat.v1.disable_eager_execution()" (but the traning is much slower). That why I do not want to use this command.

Thank you!

**Comment by ducvinh9** [comment] 2022-09-12 15:17
I tested the computation time in differents configurations and the results as follow:

With the eager mode disabled :
- Without validation set : 2.4s
- With validation set : 3.9s

With the eager mode enabled :
- Without validation set : 3.3s
- With validation set: 36s :slight_smile:

So if a validation set is not required, the eager mode cost only a little more compared to when it is disabled, from 2.4s to 3.3s, which is acceptable (even if it should not). The real difference comes from the evaluation of the validation set, which costs more than 30s in the eager mode when only 1.5s in the other case. Tensorflow.Keras is indeed fast without eager moder. So it is about an implementation issue of keras in TF2 , not about Tensorflow itself.

**Comment by tilakrayal** [comment] 2022-09-13 09:06
@ducvinh9,

`tf.compat.v1.disable_eager_execution()` Disables eager execution

This function is not necessary if you are using TF2. Eager execution is enabled by default. If you want to use Graph mode please consider [tf.function](https://www.tensorflow.org/api_docs/python/tf/function). Also please take a look at this official doc link which provides the required information. Thank you!

**Comment by ducvinh9** [comment] 2022-09-13 09:32
@tilakrayal,
With all due respect, you do not understand my problem yet and still ignore the issue reported. I believe my word is clear enough.
Yes, I do not want to disable eager execution either. The problem is that Keras training is very slow in TF2 with eager execution by default, despite the fact that keras told to run in graph mode (tf.function is not needed).
Is there anyone else who can actually look into the problem?

**Comment by tilakrayal** [comment] 2022-09-13 09:55
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and [nightly](https://colab.research.google.com/gist/tilakrayal/6ec9204828bcc1a63fc2a70bf16f5747/untitled594.ipynb) with and without the line `tf.compat.v1.disable_eager_execution().` Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0c33fe9588906eafd35f134f9815e234/untitled581.ipynb).

**Comment by sachinprasadhs** [comment] 2022-09-13 19:45
Could you please point me out to the documentation which you are referring for `model.fit` which mentions about graph mode.

**Comment by ducvinh9** [comment] 2022-09-15 12:28
@sachinprasadhs,

Official source (not very clear): [link](https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile) - option _run_eagerly_ defaults to False.
```
run_eagerly | Bool. Defaults to False. If True, this Model's logic will not be wrapped in a tf.function.
```
Some unofficial sources: [link1](https://stackoverflow.com/questions/61309661/run-keras-models-fit-in-graph), [link2](https://towardsdatascience.com/tensorflow-2-1-a-how-to-a3e6400d0899)

**Comment by ducvinh9** [comment] 2022-09-23 12:43
@sachinprasadhs,
Did you get a chance to look into this? Thank you!

**Comment by sachinprasadhs** [comment] 2022-09-23 18:40
Apologies for the delayed response,
`tf.compat.v1.disable_eager_execution()` would force the entire code to run in graph mode and results in faster execution as compared to Tensorflow eager mode where only model logic part is wrapped in `tf.function` and runs in graph mode when `run_eagerly` is set to `False`.

**Comment by ducvinh9** [comment] 2022-09-25 08:53
@sachinprasadhs,
Thanks for your reply. What do you mean by the model logic part? Are you implying that the method fit of the keras model is not entirely wrapped in _tf.function_? If it's true, I believe it is not the entended behavior. Why not wrap all the computation behide the method which is already well defined?

**Comment by ducvinh9** [comment] 2022-10-03 13:19
@sachinprasadhs,
Any more thought on this? The responses make me think like I am missing something really fundamental here, and not that there is a performance issue in keras. And this bothers me until today.

To sum up what I understand : TF2 use eager mode by default and new codes should not use `tf.compat.v1.disable_eager_execution()` at all. In order to benefit graph optimization, one should write new codes in eager mode for debugging, and wrap the final code in `tf.function`. Keras API help us by provide clean low-level code on feedforward, backpropagation and training loop, all already wrapped by `tf.function`. Thus, Keras users do not have to care anymore about graph optimization or notation like graph mode.

But here, I must use `tf.compat.v1.disable_eager_execution()` in order to get an "optimized" fitting computation time on a very simple model, which is counter-intuitive. All computations behind `model.fit` method should be already well defined and wrapped in `tf.function` by Keras. But obviously, as proved by my example, the loss computation part on validation set during fitting is not wrapped. Why not wrap it if debugging is not needed?

Please confirm my thought is correct or not. If my argument is correct, does Keras team acknowledges this performance issue and will trying to fix it? If I am wrong, please enlighten me. Is there a "not counter-intuitive" way to speed up the training of my model?

Thank you a lot,

**Comment by ducvinh-nguyen** [comment] 2022-11-16 08:47
@sachinprasadhs,
I hope you can find some time to look into my question, or assign someone else. For those who work mainly on "shallow" neural networks like me, the difference in computation time here makes TF/Keras much less powerful as it should be. Thank you!

**Comment by sachinprasadhs** [comment] 2022-11-17 19:21
@ducvinh-nguyen , This issue was discussed with the concerned team, we are looking into it in detail on the increase of time when the validation data is included in eager mode. Will update you on the issue. Thanks!

**Comment by sampathweb** [comment] 2022-11-17 22:39
@sachinprasadhs - Thanks for the update.
@ducvinh-nguyen - I am working on this issue and am able to reproduce it.  I will post an update by early next week.

**Comment by sampathweb** [comment] 2022-11-29 02:44
@ducvinh-nguyen - Thank you for your patience.  I took your code and ran some experiments and observed that there's no difference between TF2 and TF1 when using a TF Dataset.  
*Observation*: TF1 is much faster than TF2 when using plain Numpy Arrays as inputs
TF2 converts all data to TF Dataset, whereas TF1 has special logic for in-memory Numpy arrays that makes it fast. But most training will not be able to fit data in memory and will need to use TF Dataset and batch the inputs. Hence TF2 only works with TF Dataset and converts numpy arrays to TF dataset.  

When we ran experiments with TF Dataset as input, we see no difference between TF1 and TF2 when using TF Dataset. The Time / Epoch is reasonable and we recommend using TF2 with TF Dataset.

See the attached Colab for the experiments and results:
https://colab.research.google.com/drive/1yK50Y4QiGAuRqoQJk9OFR4akb3SezfEY?usp=sharing

**Comment by elbaro** [comment] 2022-11-29 22:41
Having the same performance issue in prediction.
Unlike `model.fit(large_dataset)`, we cannot use `model.predict(large_dataset)` as the result doesn't fit into the memory.

```
def predict_generator(dataset):
  for batch in dataset:
    for result in keras_model.predict_on_batch(batch):  # very slow
      yield result
```

@sampathweb Given TF Dataset, what do you suggest for the code like the above?

**Comment by sampathweb** [comment] 2022-11-29 23:28
@elbaro - Thanks for the follow-up question and code snippet.  Looks like `model.predict(large_dataset)` is running into OOM, because there's not memory to fit the Results of the entire computation along with the specified batch_size in dataset / predict function.  I would suggest, you could reduce the batch size for `model.predict`, so its able to fit the results and also process the inputs.

The reason for `predict_on_batch` being slow in TF2 is it creates a one shot iterator for each batch of inputs, where as, when we do `model.predict(dataset)`, it create single iterator for the whole Batch.  TF1 doesn't create this single iterator when calling with array inputs for example in `predict_on_batch` so is faster in this particular instance.  

My recommendation would be to -
1. Either reduce the batch size and call `model.predict(large_dataset)` so the results fit in Memory.
2. Create smaller datasets, for example, if you are processing 1M images and getting a large output embeddings, chunk the dataset in 200K and continue to use `model.predict`.

Either of the approaches will be faster than iterating over a large dataset and yielding results from `model.predict_on_batch`. Hope this helps.

**Comment by elbaro** [comment] 2022-11-29 23:36
Do you mean `model.predict` is preferred over `predict_on_batch` even for a single minibatch? (#1, #2 are always better than #3)?

```
model.predict(dataset_as_large_as_memory, verbose=0, batch_size=batch_size_used_in_training) # 1
model.predict(batch_as_large_as_memory, verbose=0) # 2
model.predict_on_batch(batch_as_large_as_memory) # 3
```

**Comment by sampathweb** [comment] 2022-11-29 23:41
I was not suggesting that.  I was suggesting that reduce the batch size to 1/2 of what's used in training, but keep the function as `model.predict(large_dataset, batch_size=0.5*train_batch_size)`.
Alternatively, you could chunk the dataset into smaller dataset, but still much larger than what fits in memory.  For example, if you have 1M files, create a dataset with 200K files and call `model.predict` on it.

**Comment by elbaro** [comment] 2022-11-29 23:47
Thanks, I understood. predict() still creates the overhead but has an advantage that it reduces the number of overhead calls to `1/(len(dataset)/batch_size)`.

**Comment by sachinprasadhs** [comment] 2022-11-30 22:37
@elbaro , If your issue is addressed, could you please close the issue. Thanks

**Comment by ducvinh-nguyen** [comment] 2022-12-12 09:53
@sampathweb, @sachinprasadhs,
Thank you for your response. I just find time to "relook" into the problem. Unfortunately, the way I see, the problem is still there.
As shown i the colab, of sampathweb, the different in the training time is as following:
- TF2 with numpy input : total time **80.1020 s**, with time/epoch **0.0401 s**.
- TF2 with TF dataset : total time **31.5645 s**, with time/epoch **0.0158 s**
Compared to the benmark reference in TF1 (eager disabled) :
- TF1 with numpy input : total Time: **7.7789 s**, with time/epoch **0.0039 s**

Following is the training time on my computer (1D regression, 10 training points, 10 validation points, 2000 epochs, CPU)
- TF2 with numpy input, no validation : **1.6563 s** (total time)
- TF2 with numpy input, with validation : **25.1658 s**
- TF2 with TF dataset input, no validation : **7.3768 s**
- TF2 with TF dataset input, with validation : **19.5825 s**
Compared to the benmark reference in TF1 (eager disabled):
- TF1 with numpy input : 1.3638 s

The training in TF2 is still much slower than TF1, even if both run in graph mode with Keras API. In the code of sampathweb, by using TF dataset in T2, we get more than 2x speed, but in my case, I gain only 22%. But both is still a lot slower than in TF1.
Please reconsider the problem.

Thank you,

Following is my code:
```
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input
from tensorflow.keras.initializers import RandomNormal
from tensorflow.keras.optimizers import Adam

from datetime import datetime

import streamlit as st

# Do not use GPU
tf.config.set_visible_devices([], "GPU")

# Generate data
def f(x):
    return (x + 1) * np.sin(5 * x)


x_plot = np.arange(-1, 1 + 0.001, 0.001)
y_plot = f(x_plot)

x_train = np.arange(-1 + 0.05, 1, 0.2)
y_train = f(x_train)

x_val = np.arange(-1 + 0.15, 1, 0.2)
y_val = f(x_val)

# Plot the problem
plt.figure()
plt.plot(x_plot, y_plot, "-", label="Orgininal function")
plt.plot(x_train, y_train, "o", label="Training points")
plt.plot(x_val, y_val, "s", label="Validation points")
plt.xlim(-1, 1)
plt.ylim(-2, 2)
plt.xlabel("x")
plt.ylabel("f")
plt.grid()
plt.legend()
plt.show(block=False)

# Reshape
X_train = x_train.reshape(x_train.shape[0], 1)
Y_train = y_train.reshape(x_train.shape[0], 1)

X_val = x_val.reshape(x_val.shape[0], 1)
Y_val = y_val.reshape(x_val.shape[0], 1)

# Simple model
def train(run_with_validation, use_tf_dataset):
    tf.keras.utils.set_random_seed(1)
    model = Sequential()
    model.add(Input(shape=(1,)))  # Input layer
    model.add(
        Dense(
            4,
            activation="sigmoid",
            kernel_initializer=RandomNormal(mean=0.0, stddev=1.0, seed=1),
        )
    )
    model.add(Dense(1))

    model.compile(
        loss="mean_squared_error", optimizer=Adam(learning_rate=3e-1), run_eagerly=False
    )
    
    batch_size = X_train.shape[0]
    if use_tf_dataset:
        # Convert numpy array to TF Dataset
        train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size).prefetch(tf.data.AUTOTUNE)
        val_ds = tf.data.Dataset.from_tensor_slices((x_val, y_val)).batch(batch_size).prefetch(tf.data.AUTOTUNE)
        
    if run_with_validation:
        if use_tf_dataset:
            history = model.fit(
                train_ds,
                validation_split=0.0,
                validation_data=val_ds,
                validation_freq=1,
                #batch_size=batch_size,
                epochs=2000,
                verbose=0,
            )
        else:
            history = model.fit(
                X_train,
                Y_train,
                validation_split=0.0,
                validation_data=(X_val, Y_val),
                validation_freq=1,
                batch_size=batch_size,
                epochs=2000,
                verbose=0,
            )
    else:
        if use_tf_dataset:
            history = model.fit(
                train_ds,
                validation_split=0.0,
                #batch_size=batch_size,
                epochs=2000,
                verbose=0,
            )
        else:
            history = model.fit(
                X_train,
                Y_train,
                validation_split=0.0,
                batch_size=batch_size,
                epochs=2000,
                verbose=0,
            )
    return model

# Using numpy input, no validation set
start_time = datetime.now()
model2 = train(run_with_validation=False, use_tf_dataset = False)
run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
print("Model running Eagerly?: ", model2.run_eagerly)

# Using numpy input, with validation set
start_time = datetime.now()
model2 = train(run_with_validation=True, use_tf_dataset = False)
run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
print("Model running Eagerly?: ", model2.run_eagerly)

# Using dataset input, no validation set
start_time = datetime.now()
model2 = train(run_with_validation=False, use_tf_dataset = True)
run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
print("Model running Eagerly?: ", model2.run_eagerly)

# Using dataset input, with validation set
start_time = datetime.now()
model2 = train(run_with_validation=True, use_tf_dataset = True)
run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
print("Model running Eagerly?: ", model2.run_eagerly)

# Using numpy input, with validation set in TF1 (eager disableb)
tf.compat.v1.disable_eager_execution()
start_time = datetime.now()
model2 = train(run_with_validation=True, use_tf_dataset = False)
run_time = datetime.now() - start_time
print("Training time : {:.4f} s".format(run_time.total_seconds()))
print("Model running Eagerly?: ", model2.run_eagerly)
```

**Comment by sampathweb** [comment] 2022-12-17 01:01
@ducvinh-nguyen - I will take a look and get back to you early next week.  Thanks for the additional details.

**Comment by sampathweb** [comment] 2022-12-18 19:23
@ducvinh-nguyen -I added your code into a Colab for easy reference and increased the dataset from 10 records to 2K Records, which is still a very small dataset for neural network.
https://colab.research.google.com/drive/1H6z1WRkYzF6JzeUHoPTMRqXxkAp-gEcx?usp=sharing

In the run results of the colab, you will see that when using TF Dataset, there's no meaningful difference in performance between TF1 and TF2.  TF1 is faster with Numpy arrays because it converts its to in memory tensor and uses it.  In TF2, it's converted to TF Dataset, so the interface is similar.  In practice most datasets are quite large to fit in memory and require batching and usage of TF Dataset.  If you have a really small dataset (100 observations or less), it might be better served by traditional models (Decision Trees, in particular).

**Closed** 2023-01-01 20:19 UTC
Labels: stat:awaiting response, stalled, comp:eager, comp:keras, type:performance, TF 2.9
