### ISSUE TITLE
Error in example of tensorflow lite

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [tensorflow/tensorflow#31693] opened 2019-08-16 14:11 UTC
Hello, I got an error in code while tried to run object detection. Let me know how to fix this
![Screenshot (15)](https://user-images.githubusercontent.com/39325207/63173591-d6d0a400-c05d-11e9-807b-42d1c4cc626b.png)
 code

**Comment by gadagashwini** [comment] 2019-08-19 05:16
@KanwarpartapSinghBimrah, Please provide the information asked in the [template](https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md). Thanks!

**Comment by wangtz** [comment] 2019-08-20 03:34
Yes please fill in details on how to reproduce the issue, the version you're using etc. thx

**Comment by gadagashwini** [comment] 2019-08-26 08:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-26 08:55 UTC
Labels: comp:lite, stat:awaiting response, type:support
