### ISSUE TITLE
Android demo app crashes when using quantized model obtained from graph_transform tool?

### ISSUE THREAD

**Issue by kwotsin** [tensorflow/tensorflow#9958] opened 2017-05-17 07:26 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
Only edited `ClassifierActivity.java` to suit a custom model
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Android smartphone / host machine: Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.1
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: GTX 860M

### Describe the problem
I am currently following the guide in: http://nilhcem.com/android/custom-tensorflow-classifier

to train a custom classifier. However, I am using my own frozen graph that I obtained from my own training. What I noticed was when I used the quantized graph obtained through the `graph_transform` method, the app simply crashes without even running. In the guide, it is recommended to run this command on the inference graph:

```
bazel-bin/tensorflow/python/tools/optimize_for_inference \
  --input=/tf_files/retrained_graph.pb \
  --output=/tf_files/retrained_graph_optimized.pb \
  --input_names=Mul \
  --output_names=final_result
```

While I think it may be in conflict with the quantized graph transformations, I ran this command to test, and the app did crash. Here are the observations for all 4 permutations I tested:

1. quantization + optimize_for_inference = **app crash**
2. quantization only = **app crash**
3. optimize_for_inference on frozen graph = **app works**
4. frozen_graph only = **app works**

So my conclusion is the quantization operations within the quantized graph caused the app to fail. 

Here is the quantization command I ran:

```
/home/kwotsin/tensorflow-android/tensorflow/bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=./frozen_model_mobilenet.pb \
--out_graph=./quantized_model_mobilenet.pb \
--inputs='Placeholder_only' \
--outputs='MobileNet/Predictions/Softmax' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'
```

And the java file I edited to build my APK:

```
  private static final int INPUT_SIZE = 224;
  private static final int IMAGE_MEAN = 128;
  private static final float IMAGE_STD = 128;
  private static final String INPUT_NAME = "Placeholder_only";
  private static final String OUTPUT_NAME = "MobileNet/Predictions/Softmax";

  private static final String MODEL_FILE = "file:///android_asset/quantized_model_mobilenet.pb";
  private static final String LABEL_FILE =
      "file:///android_asset/mobilenet_labels.txt";
```

Other than these edit, every other file is the same. I then imported this project in Android Studio, and ran the `build apk` option located on the top toolbar of Android Studio.

So far, existing tutorials I've seen (e.g. those from Pete Warden) use the `quantize_graph` method to run on mobile devices. Is `graph_transform` compatible for quantizing models for mobile devices yet?

**Comment by skye** [comment] 2017-05-17 16:58
@asimshankar can you comment or redirect to someone who can? Thanks!

**Comment by asimshankar** [comment] 2017-05-17 17:03
@kwotsin : Do you have any logs/stracktraces you can share from the crash? That will help in diagnosing the problem. Also, is it possible to share the graph that you are quantizing? Basically, I'm looking for detailed information on the error and/or the ability to reproduce the problem to help us diagnose.

FYI @suharshs @petewarden

**Comment by kwotsin** [comment] 2017-05-18 08:15
@asimshankar Is there a way to see the error log if an app crashes? So far the only idea I have that it's not working is just that the app crashes. Because I can't find the error log, I can't seem to find the source of the problem as well.

I have attached the PB files for both the frozen and quantized model here. https://www.dropbox.com/sh/grp7xlxu4r59qss/AADV9imhKpY9auiNAkaSsjyMa?dl=0

I have noticed another problem as well: when I tried to predict custom labels with another model trained on the flowers dataset, my app crashes even if I'm not quantizing it. Could this problem be related to why quantization fails?

**Comment by asimshankar** [comment] 2017-05-18 08:23
The errors should appear like any android app, see https://developer.android.com/studio/debug/am-logcat.html and https://developer.android.com/studio/command-line/logcat.html

**Comment by kwotsin** [comment] 2017-05-18 08:43
Unfortunately I am currently unable to get my android device mounted on my computer, and I've tried asking on StackOverflow in this link some time ago: http://stackoverflow.com/questions/43996994/android-unable-to-mount-android-phone-although-lsusb-shows-device-and-after-ins

I am currently building the APK before transferring it onto dropbox to let my android phone download the app as a workaround.

Also, I realized there's one other java file I have to change: tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java

As the labels and pb file names needs to be changed in this file as well, before building the APK. To keep things simple, I simply renamed the pb file name and the labels file name to be the same as what the demo app provided, and the frozen graph APK works fine. Once again, when I tried quantizing the graph, my app crashes. Is there a way to get the error log files without using ADB?

**Comment by asimshankar** [comment] 2017-05-18 08:55
It will be hard to debug without access to debugging information from the android logs.

I don't _think_ there is a way to get access to logs without connecting it to your computer, but maybe there is. That would be a question better suited to Android support forums.

**Comment by kwotsin** [comment] 2017-05-19 08:54
@asimshankar I have finally solved the ADB issue by doing a factory reset of the android phone and then enabling PTP instead of MTP as the file transfer method. 

From the Android Studio's android monitor, I have gotten these log when my app crashes using the quantized graph.

```
05-19 16:48:38.403 23564-23564/? I/art: Late-enabling -Xcheck:jni
05-19 16:48:38.509 23564-23564/? W/ActivityThread: Application org.tensorflow.demo can be debugged on port 8100...
05-19 16:48:38.609 23564-23564/? D/ContextHelper: convertTheme. context->name=org.tensorflow.demo themeResourceId=2131034118
05-19 16:48:38.611 23564-23564/? D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@7b0b069
05-19 16:48:38.614 23564-23564/? I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
05-19 16:48:38.617 23564-23564/? D/PhoneWindowEx: [LMJ][PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
05-19 16:48:38.617 23564-23564/? I/PhoneWindow: [setNavigationBarColor2] color=0x ff000000
05-19 16:48:38.704 23564-23564/? D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@7b0b069
05-19 16:48:38.704 23564-23564/? D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@7b0b069
05-19 16:48:38.722 23564-23597/? D/OpenGLRenderer: Render dirty regions requested: true
05-19 16:48:38.725 23564-23597/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
                                               OpenGL ES Shader Compiler Version: E031.25.03.00
                                               Build Date: 12/12/14 금
                                               Local Branch: LA.BF.1.1_RB1.05.00.00.002.031_20141212_01821442
                                               Remote Branch: 
                                               Local Patches: 
                                               Reconstruct Branch: 
05-19 16:48:38.729 23564-23597/? I/OpenGLRenderer: Initialized EGL, version 1.4
05-19 16:48:38.763 23564-23597/? D/OpenGLRenderer: Enabling debug mode 0
05-19 16:48:38.777 23564-23564/? D/Atlas: Validating map...
05-19 16:48:38.890 23564-23564/? W/ArrayUtils: Ignoring invalid value mw_continuous-picture
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value emboss
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value sketch
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value neon
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value asd
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value backlight
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value flowers
05-19 16:48:38.891 23564-23564/? W/ArrayUtils: Ignoring invalid value AR
05-19 16:48:38.907 23564-23564/? I/tensorflow: CameraConnectionFragment: Valid preview sizes: [1920x1440, 1920x1080, 1776x1080, 1440x1080, 1280x960, 1280x720, 960x720, 880x720, 864x480, 848x480, 800x480, 720x480, 768x432, 640x480, 576x432, 480x320]
05-19 16:48:38.908 23564-23564/? I/tensorflow: CameraConnectionFragment: Rejected preview sizes: [384x288, 352x288, 320x240, 240x160, 176x144, 160x120]
05-19 16:48:38.908 23564-23564/? I/tensorflow: CameraConnectionFragment: Chosen size: 480x320
05-19 16:48:38.914 23564-23564/? W/ArrayUtils: Ignoring invalid value emboss
05-19 16:48:38.914 23564-23564/? W/ArrayUtils: Ignoring invalid value sketch
05-19 16:48:38.914 23564-23564/? W/ArrayUtils: Ignoring invalid value neon
05-19 16:48:38.915 23564-23564/? W/ArrayUtils: Ignoring invalid value asd
05-19 16:48:38.915 23564-23564/? W/ArrayUtils: Ignoring invalid value backlight
05-19 16:48:38.915 23564-23564/? W/ArrayUtils: Ignoring invalid value flowers
05-19 16:48:38.915 23564-23564/? W/ArrayUtils: Ignoring invalid value AR
05-19 16:48:38.936 23564-23564/? I/TensorFlowImageClassifier: Reading labels from: imagenet_comp_graph_label_strings.txt
05-19 16:48:38.944 23564-23564/? I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
05-19 16:48:38.949 23564-23564/? E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
05-19 16:48:38.950 23564-23564/? I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
05-19 16:48:39.065 23564-23564/? I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
05-19 16:48:39.879 23564-23564/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23564 (tensorflow.demo
```

I've not done any android development before, so I would really appreciate it if you could share what this error log means. 

Also, does the image input size (299*299) that my model requires does cause any problem with the camera app activity? I'm not sure if the image will be distorted to fit into 299*299 to make it work.

**Comment by andrewharp** [comment] 2017-05-19 15:24
@kwotsin your logcat cuts off in the middle of the relevant error, can you paste the rest please?

**Comment by kwotsin** [comment] 2017-05-24 04:48
@andrewharp After several days of testing, I have managed to locate the source of the error, which is actually coming from `quantize_nodes`. As the ClassifierActivity.java file requires an input and output nodes of:

```
private static final String INPUT_NAME = "Placeholder_only";
private static final String OUTPUT_NAME = "MobileNet/Predictions/Softmax";
```
I realized the quantized file should have such an input output node as well. After confirming that the frozen model has these input and output nodes, I checked whether the quantized version has these nodes as well, and I realized it doesn't. Instead, it has these nodes after quantization:

```
(<tf.Tensor 'import/MobileNet/conv_ds_6/dw_batch_norm/batchnorm/sub/_7__cf__7_quantized_const:0' shape=(256,) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/conv_1/batch_norm/batchnorm/sub/_25__cf__25_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_6/depthwise_conv/depthwise_weights_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_1/weights_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_10/pw_batch_norm/batchnorm/sub/_29__cf__29_quantized_const:0' shape=(512,) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/conv_ds_12/pointwise_conv/biases_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_1/convolution_eightbit/Placeholder_only/reduction_dims:0' shape=(1,) dtype=int32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_3/depthwise_conv/depthwise_weights_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_9/pointwise_conv/weights_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_5/pointwise_conv/biases_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_9/dw_batch_norm/batchnorm/Rsqrt/_34__cf__34_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_2/depthwise_conv/depthwise_weights_quantized_const:0' shape=(3, 3, 32, 1) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/conv_ds_14/pointwise_conv/weights_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_2/depthwise_conv/biases_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_14/pointwise_conv/weights_quantized_const:0' shape=(1, 1, 1024, 1024) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/conv_ds_14/depthwise_conv/biases_quantized_const:0' shape=(1024,) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/fc_16/weights_quantized_min:0' shape=() dtype=float32>,)
```

After removing each graph transform one by one, I hoped to see if there is a specific transformation which after I removed, will give me the correct input node called 'Placeholder_only', which I included in the graph when I first froze the model. After checking all transformations, I found `quantize_nodes` is the transformation that removed the input_node. After removing `quantize_nodes` from the transformation, I have these nodes instead:

```
(<tf.Tensor 'import/Placeholder_only:0' shape=<unknown> dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/sub/_53__cf__53_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/sub/_53__cf__53_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/sub/_53__cf__53_quantized_const:0' shape=(512,) dtype=quint8>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/sub/_53__cf__53:0' shape=(512,) dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/Rsqrt/_52__cf__52_quantized_max:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/Rsqrt/_52__cf__52_quantized_min:0' shape=() dtype=float32>,)
(<tf.Tensor 'import/MobileNet/conv_ds_8/dw_batch_norm/batchnorm/Rsqrt/_52__cf__52_quantized_const:0' shape=(512,) dtype=quint8>,)
```

And now my quantized model works on the app. Is there a reason why `quantize_nodes` would cause the model to not work? Also, even after I've read the documentation here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#quantize_nodes 
I don't quite understand what `quantize_nodes` does and the benefits that may be gained. What are the purpose and benefits of this tool?

Also, strangely for the logcat, the error log is all I could see when I run the app and after it crashes immediately. There is nothing produced after the 'fatal signal' output. My current logcat status is at 'Verbose' - is this the correct status to use?

**Comment by Androbin** [comment] 2017-06-09 10:59
Seems to be issue #8698
This is probably a bug in `merge_duplicate_nodes` (called by `quantize_nodes`)
See #8897 for reference

**Comment by petewarden** [comment] 2017-07-12 23:26
I think the underlying issue here is that you need to specify the right input and output names when you call `transform_graph` too. In the code above, you're using the default of `Mul` and `final_result` when you invoke the tool, but they should be `input` and `MobileNet/Predictions/Softmax`, like your application code.

**Comment by kwotsin** [comment] 2017-07-13 09:10
@petewarden `Mul` and `final_result` are not the input and output names I used, but rather, the example usage given in the documentation. I included them just for the sake of illustration, but the actual command I used had the input and output node names I used in the java code as well. In fact, I think it would not be possible to run the graph transform tool successfully if the node names are invalid or do not exist within the graph. I think, at least for my use case, quantize_nodes somehow gave me the error when running.

**Comment by anandcu3** [comment] 2017-08-31 11:45
@kwotsin @petewarden  @andrewharp Were you able to solve this issue? I've hit the same error..

**Comment by kwotsin** [comment] 2017-08-31 12:47
@anandcu3 Did you try removing `quantize_nodes` from your transformation?

**Comment by anandcu3** [comment] 2017-08-31 12:51
@kwotsin But isn't `quantize_nodes ` necessary for improving performance ?

**Comment by kwotsin** [comment] 2017-08-31 13:08
YMMV but the last time I tried it, this gave me worse results instead. I think it shouldn't take too long for you 
to verify whether it gives better accuracy or not - perhaps you can try it and see if your results does improve.

**Comment by anandcu3** [comment] 2017-08-31 13:13
@kwotsin  I tried it and you are right the ` Fatal signal 11 (SIGSEGV), code 1` error is resolved, but overall there is no change in either accuracy or performance. The output is the same

**Comment by kwotsin** [comment] 2017-08-31 16:31
@anandcu3 To verify with you, 'no change in either accuracy or performance' - does it mean the accuracy is retained as your original model, or is the poor performance retained? I think `quantize_nodes` is still largely experimental now, but so far I've seen quite good results with just `quantize_weights` alone.

**Comment by anandcu3** [comment] 2017-09-01 05:23
@kwotsin Accuracy is retained and the performance is also the same as original model..

**Comment by ruppeshnalwaya1993** [comment] 2017-10-16 09:01
I fine-tuned a mobilenet model for binary classification. The problem is when I use Quantised model on Android, it produces exactly same prediction values for all images after retraining. The same mobilenet model when non-quantised produces reasonable values. 
This problem is only on Android. On iOS it works nicely for both non-quantised and quantised model. What could be reason for this and solution for Android. I tried 
1. pre-compiled .so of tensorflow inference
2. compiling .a file with selective registration.

**Comment by GodOfSmallThings** [comment] 2017-10-24 04:27
I solved this problem by updating libtensorflow_inference.so from nightly build. Leave this message just in case someone would have same problem as we had.
Try this.
https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastSuccessfulBuild/artifact/out/native/

**Comment by ruppeshnalwaya1993** [comment] 2017-10-24 06:38
https://github.com/tensorflow/tensorflow/issues/11182
I solved it by compiling the tensorflow .a lib file for android with flag `-DTENSORFLOW_DISABLE_META`

**Comment by tensorflowbutler** [comment] 2017-12-22 07:36
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:26
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2018-01-29 22:47
We're now focusing on using TF Lite for quantization, and the demo app shows how to run quantized MobileNet, so closing this one as obsolete.

**Closed by petewarden** 2018-01-29 22:47 UTC

**Comment by praveencali2017** [comment] 2018-03-23 06:05
If I use the frozen graph the app works but if I use optimize_for_inference_lib.optimize_for_inference, I get loading error in android. Is there a solution for this?

**Comment by praveencali2017** [comment] 2018-03-23 06:06
The classification is work with frozengraph, is there something I am missing?
