### ISSUE TITLE
How to change the model and label file in "assets" of Android Demo?

### ISSUE THREAD

**Issue by YoWhatever** [tensorflow/tensorflow#4266] opened 2016-09-08 03:16 UTC
When I change these files in "assets" folder , the Demo App will crash. How can I change the .txt and .pb file to change the verify model?

**Comment by andrewharp** [comment] 2016-09-08 04:27
@YoWhatever If you change the names of the asset files you need to also edit the corresponding values in TensorFlowImageListener.java.

**Comment by YoWhatever** [comment] 2016-09-08 04:35
@andrewharp Thank you！ When I replace the asset files, I also rename my model file as the former corresponding file's name. But it didn't work. So I 'm wondering if there is something else need to be changed.

**Comment by andrewharp** [comment] 2016-09-08 04:39
@YoWhatever There are a lot of possible things that could be going on; can you use adb logcat and post the exact error message that you get please?

**Comment by YoWhatever** [comment] 2016-09-08 11:45
@andrewharp Sorry I'm a novice.Is there any useful information in these pictures？
![image](https://cloud.githubusercontent.com/assets/17775886/18348161/537814ca-75fc-11e6-9a14-7380a6613020.jpeg)
![image](https://cloud.githubusercontent.com/assets/17775886/18348190/8f031e68-75fc-11e6-8488-282f880bf657.jpeg)

**Comment by andrewharp** [comment] 2016-09-08 17:54
@YoWhatever I'm guessing the root cause information comes just above the lines in the 2nd picture you provided. You can save the entire log to a text file with `adb logcat | tee log.txt`, and then just upload log.txt after you've captured an instance of it crashing.

What is odd to me is that you only have 7 nodes in your graph. Are the input and output nodes named the same? Possibly you're trying to use a node that isn't supported on mobile?

**Comment by YoWhatever** [comment] 2016-09-13 06:54
@andrewharp Sorry for late reply. I found these sentences in my logcat:

I/native (21039): tensorflow_jni.cc:299 End computing.Ran in 3ms(3ms avg over 1 runs)
F/native (21039): tensorflow_jni.cc:304 Error during inference: Not found: Feed Inputs: unable to find feed output Mul:0
F/libc (21039):Fatal signal 6 (SIGABRT), code -6 in tid 21064 (InferenceThread)
Since I change the TensorFlowImageListener.java to:

private static final int NUM_CLASSES = 10; // number of categories (0-9)
private static final int INPUT_SIZE = 299;
private static final int IMAGE_MEAN = 128;
private static final float IMAGE_STD = 128;
private static final String INPUT_NAME = "Mul:0";
private static final String OUTPUT_NAME = "final_result:0";

I think that may means something.

**Comment by andrewharp** [comment] 2016-09-13 08:40
@YoWhatevr Where did the graph you're trying to use come from? Are you trying to follow this TF for poets codelab? Otherwise do you know that the graph you're using has or should have a "Mul:0" input?

**Comment by andrewharp** [comment] 2016-09-19 18:02
Closing; please reopen with more details if the issue persists.

**Closed by andrewharp** 2016-09-19 18:02 UTC
Labels: awaiting response
