### ISSUE TITLE
experimental_new_converter / error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op

### ISSUE THREAD

**Issue by gogela** [tensorflow/tensorflow#35590] opened 2020-01-05 08:35 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): google colab, python 3 runtime
- TensorFlow installed from (source or binary): pip3 install tf-nightly
- TensorFlow version (or github SHA if from source): '2.1.0-dev20200104'

**Command used to run the converter or code if you’re using the Python API**

converter = tensorflow.lite.TFLiteConverter.from_keras_model(loaded_model)
converter.optimizations = [tensorflow.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
tflite_quant_model = converter.convert()

**The output from the converter invocation**

---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-27-934d73e7faa7> in <module>()
      3 converter.optimizations = [tensorflow.lite.Optimize.DEFAULT]
      4 converter.experimental_new_converter=True
----> 5 tflite_quant_model = converter.convert()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    213       stdout = _try_convert_to_unicode(stdout)
    214       stderr = _try_convert_to_unicode(stderr)
--> 215       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    216   finally:
    217     # Must manually cleanup files.

ConverterError: See console for info.
2020-01-05 08:26:27.512446: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:108] Ignored output_format.
2020-01-05 08:26:27.512515: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:114] Ignored drop_control_dependency.
2020-01-05 08:26:27.711202: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
loc(callsite("model_1/up_sampling2d_1/resize/ResizeNearestNeighbor"("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py":853:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py":947:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py":409:0 at callsite("<ipython-input-27-934d73e7faa7>":2:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2882:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2822:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2718:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py":533:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py":196:0 at "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py":399:0)))))))))): error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
error: failed while converting: 'main'
Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py:853:9: error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
        self._initialize(args, kwargs, add_initializers_to=initializers)
        ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py:947:5: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
    ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py:409:5: note: called from
    concrete_func = func.get_concrete_function()
    ^
<ipython-input-27-934d73e7faa7>: note: called from
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882:17: note: called from
                exec(code_obj, self.user_global_ns, self.user_ns)
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822:17: note: called from
                if self.run_code(code, result):
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718:20: note: called from
                   interactivity=interactivity, compiler=compiler, result=result)
                   ^
/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py:533:9: note: called from
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
        ^
/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py:196:13: note: called from
            res = shell.run_cell(code, store_history=store_history, silent=silent)
            ^
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py:399:41: note: called from
                                        user_expressions, allow_stdin)
                                        ^
<unknown>:0: error: failed while converting: 'main'
Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor.

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

the old toco based converter works as expected,
when testing: converter.experimental_new_converter=True
the above error appears

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-01-06 12:40
@gogela,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by gogela** [comment] 2020-01-06 14:43
The full code is below and  attached zip with model json file.
I'm unfortunately unable to share the weights h5 file.

%tensorflow_version 2.x
from tensorflow.keras.models import model_from_json
from tensorflow.keras.models import load_model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights('model.h5')

converter = tensorflow.lite.TFLiteConverter.from_keras_model(loaded_model)
converter.optimizations = [tensorflow.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
tflite_quant_model = converter.convert()


[model.zip](https://github.com/tensorflow/tensorflow/files/4026478/model.zip)

**Comment by jvishnuvardhan** [comment] 2020-01-08 19:46
@gogela Can you please try adding the following line. When I added, I don't see any error. Please check and let us know. Thanks.

```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
```

[Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/767a9270d4aaea440f715bffcca730e0/untitled736.ipynb) is the gist for your reference. Thanks!

Please close the issue if it was resolved for you. thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-13 22:13
I am closing this issue as it was resolved. Please let me know if I am mistaken. thanks!

**Closed by jvishnuvardhan** 2020-01-13 22:13 UTC
Labels: TF 2.1, comp:lite, stat:awaiting response, type:support

**Comment by gigadeplex** [comment] 2020-05-29 01:54
I'm currently faced with this issue `Exception: <unknown>:0: error: loc("Dilation2D"): 'tf.Dilation2D' op is neither a custom op nor a flex op`
When will tflite support tf.nn.dilation2d??

**Comment by gigadeplex** [comment] 2020-05-29 01:57
Also if I add `converter.allow_custom_ops = True` it works and exports a tflite file.
However, it crashes in the phone with error: 
`Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 0 (FlexIdentity) failed to prepare.`

**Comment by jvishnuvardhan** [comment] 2020-05-29 20:45
@gigadeplex Can you please open a new issue with a description (as above) and a standalone code to reproduce the issue? Thanks!

**Comment by gigadeplex** [comment] 2020-06-12 19:45
> 
> 
> @gigadeplex Can you please open a new issue with a description (as above) and a standalone code to reproduce the issue? Thanks!

Hi @jvishnuvardhan , thank you for your reply! I took your advice and just opened an issue regarding tf.Dilation2D and included a link to a saved model which is derived from pytorch through onnx #40420

**Comment by kaustubh7778** [comment] 2020-10-23 11:18
> @gogela Can you please try adding the following line. When I added, I don't see any error. Please check and let us know. Thanks.
> 
> ```
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                                        tf.lite.OpsSet.SELECT_TF_OPS]
> ```
> 
> [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/767a9270d4aaea440f715bffcca730e0/untitled736.ipynb) is the gist for your reference. Thanks!
> 
> Please close the issue if it was resolved for you. thanks!

Thank you My issue was solved because of you . I was trying for last 10 days

**Comment by vinits5** [comment] 2020-11-03 17:16
> @gogela Can you please try adding the following line. When I added, I don't see any error. Please check and let us know. Thanks.
> 
> ```
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                                        tf.lite.OpsSet.SELECT_TF_OPS]
> ```
> 
> [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/767a9270d4aaea440f715bffcca730e0/untitled736.ipynb) is the gist for your reference. Thanks!
> 
> Please close the issue if it was resolved for you. thanks!

Thank you so much. You have probably saved my several working hours.

**Comment by tucachmo2202** [comment] 2020-11-29 14:31
> I am closing this issue as it was resolved. Please let me know if I am mistaken. thanks!

Thank you so much. But I don't know why to use that line. And, do you have a tutorial about TF Lite, please tell me.

**Comment by jvishnuvardhan** [comment] 2020-12-02 22:12
@tucachmo2202 Please follow the guides [here](https://www.tensorflow.org/lite/performance/model_optimization). Thanks!
In the above example, there are two kinds of `ops` supported (`TFLITE_BUILTINS` and `SELECT_TF_OPS`].

TFLITE_BUILTINS : These are the ops builtin specifically for tflite. They are optimized for tflite. But, currently there are limited ops are supported by `TFLITE_BUILTINS`.

SELECT_TF_OPS : If you are using some `op` that is not part of  `TFLITE_BUILTINS` then the conversion code automatically selects Tensorflow Ops. These are not really optimized for TFLite, so it might need consume more memory.

Hope this helps. Thanks!

**Comment by tucachmo2202** [comment] 2020-12-14 04:29
> @tucachmo2202 Please follow the guides [here](https://www.tensorflow.org/lite/performance/model_optimization). Thanks!
> In the above example, there are two kinds of `ops` supported (`TFLITE_BUILTINS` and `SELECT_TF_OPS`].
> 
> TFLITE_BUILTINS : These are the ops builtin specifically for tflite. They are optimized for tflite. But, currently there are limited ops are supported by `TFLITE_BUILTINS`.
> 
> SELECT_TF_OPS : If you are using some `op` that is not part of `TFLITE_BUILTINS` then the conversion code automatically selects Tensorflow Ops. These are not really optimized for TFLite, so it might need consume more memory.
> 
> Hope this helps. Thanks!

Thanks. I did make sense of TF Lite, but I am getting stuck on Non maximum suppression operation, it is not support for TF Lite and I don't want to use SELECT_TF_OPS option. Do you know how to convert or re-implement the that NMS op, please tell me. Thanks very much!

**Comment by malik-anhar** [comment] 2021-04-01 07:36
Hi @tucachmo2202 have you done for implementing NMS without SELECT_TF_OPS? I'm facing the issue too. Let me know if you have the solution. Thanks in advance!
