### ISSUE TITLE
Feature Request: tf.extract_image_patches gradients operation for variable size inputs

### ISSUE THREAD

**Issue by PaddyT** [tensorflow/tensorflow#11651] opened 2017-07-20 18:40 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Scientific Linux 7.3
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.1.0-rc0-61-g1ec6ed5 1.1.0 GPU
- **Python version**: 3.6.1
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 8.0.44
- **GPU model and memory**: n/a

### Describe the problem
I'm using the `tf.extract_image_patches` operation to extract a number of overlapping frames from an image with variable size. The current gradient operation fails unless the input image dimensions are fixed.
Specifically, in my case my code fails here 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_grad.py#L690
where `rows_in`, `rows_out` and `cols_out` are all `None`.

For more background: my application is in speech processing and my "image" is a spectrogram-like array of features which has a fixed height but can vary in length with the duration of the input audio. I'm trying to split it into overlapping windows dynamically to pass to a classifier downstream.
In my case the input  has shape `(1 x None x 128 x  1)`, where the unknown dimension is typically ~15,000, my image patches are `400x128` and the result has shape `(1 x None x None x 51200)`.

I feel it should be possible to modify the gradient op to accommodate dynamic input dimensions, would this be a reasonable feature addition?
The current gradient implementation was added here: https://github.com/tensorflow/tensorflow/issues/2921
Perhaps this feature request would tie in with https://github.com/tensorflow/tensorflow/issues/6847 ?

### Source code/Logs
I think the information provided explains my problem well enough, let me know if I should provide a more detailed problem description.
An expanded code snippet can also be found here: https://github.com/PaddyT/waveform-asr/blob/master/waveasr/models/wavenet.py#L455#L495
``
extracted = tf.extract_image_patches(images=input_image,
                                                           ksizes=[1, 400, 128, 1],
                                                           strides=[1, 160, 1, 1],
                                                           rates=[1, 1, 1, 1],
                                                           padding='VALID')``

```
 File "~/diss/waveform-asr/tests/test_graphs/test_wavenet.py", line 35, in <module>
    alpha=0.5)
  File "~/diss/waveform-asr/waveasr/models/wavenet.py", line 321, in __init__
    self.train_op = self.optimizer.minimize(loss=self.objective, global_step=self.global_step)
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
    grad_loss=grad_loss)
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 368, in _MaybeCompile
    return grad_fn()  # Exit early
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "~/miniconda2/envs/diss/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 610, in _ExtractImagePatchesGrad
    rows_out = int(ceil((rows_in - ksize_r_eff + 1) / stride_r))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'```

**Comment by drpngx** [comment] 2017-07-20 19:59
@gpapan wdyt?

**Comment by sharmaannapurna** [comment] 2017-07-31 06:26
Hi, 
I am also having the same issue with the requirement of static shape of the input.

**Comment by seaotterman** [comment] 2017-08-02 23:39
+1
Can confirm this for TF v1.2.1.

**Comment by PaddyT** [comment] 2017-08-04 15:20
Good to hear!

For what it's worth in the meantime, to anyone else with this problem, I solved my requirement by replacing `extract_image_patches` with a carefully constructed sparse convolution (which i imagine is what  extract_image_patches does under the hood in any case). You can see my fix via my repo link in the original post.

**Comment by seaotterman** [comment] 2017-08-07 06:27
FWIW, [tf.space_to_batch](https://www.tensorflow.org/api_docs/python/tf/space_to_batch) is another alternative that gives gradients, though it is much less flexible.

**Comment by tensorflowbutler** [comment] 2018-01-03 07:41
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by drpngx** [comment] 2018-01-03 21:03
Is that bug still in the latest version?

**Comment by tensorflowbutler** [comment] 2018-01-24 19:58
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-01-24 23:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by chrisc36** [comment] 2018-01-25 08:22
I can confirm this still occurs in tensorflow 1.4.1, for example if I run:

```
input_image = tf.placeholder(tf.float32, (5, None, None, 5), "tmp")
extracted = tf.extract_image_patches(images=input_image,
                                         ksizes=[1, 2, 2, 1],
                                         strides=[1, 1, 1, 1],
                                         rates=[1, 1, 1, 1], padding='VALID')
grad = tf.gradients(tf.reduce_sum(extracted), input_image)
sess = tf.Session()
sess.run(grad, {input_image: np.random.normal(size=(5, 2, 2, 5))})
```

 I would still find it useful if this feature was added.

**Comment by tensorflowbutler** [comment] 2018-02-09 19:14
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-03 07:59
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-17 14:59
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-01 12:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:45
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by mkmodrzew** [comment] 2018-09-13 19:47
Could I try to fix that issue?

**Comment by lioutasb** [comment] 2019-05-28 17:12
Problem still occurs with Tensorflow 2.0

**Closed** 2019-06-20 19:29 UTC
Labels: stat:contributions welcome, type:bug/performance
