### ISSUE TITLE
Custom tf.keras.Model memory footprint drastically affects performance

### ISSUE THREAD

**Issue by schmiflo** [tensorflow/tensorflow#33527] opened 2019-10-19 08:26 UTC
**System information**
16.04.6 LTS
Python 3.5.2
GPU TITAN X (Pascal) 13GB

**Describe the current behavior**

The memory footprint of a custom tf.keras.Model object affects training performance by almost two orders of magnitude.

**Code to reproduce the issue**

The following is a stripped-down implementation of an RNN for text data loosely resembling the one in the [Effective Tensorflow 2.0 Tutorial](https://www.tensorflow.org/guide/effective_tf2)

```ruby
class DynamicRNN(tf.keras.Model): 

  def __init__(self, state_size, embedding_size, vocab_size, something):
    super(DynamicRNN, self).__init__(self)

    self.state_size = state_size
    self.embedding_size = embedding_size
    self.vocab_size = vocab_size
    self.something = something

    # The internal GRU
    self.cell = tf.keras.layers.GRUCell(state_size)
    
    # Input embedding and softmax parameters
    emb_initializer = tf.initializers.RandomUniform(-0.5, 0.5)
    self.emb = tf.Variable(emb_initializer(shape=[self.vocab_size, self.embedding_size]), name="emb")
    softmax_w_initializer = tf.initializers.GlorotUniform()
    self.softmax_w = tf.Variable(softmax_w_initializer(shape=[self.vocab_size, self.state_size]), name="softmax_w")
    self.softmax_b = tf.Variable(tf.zeros([self.vocab_size]), name="softmax_b")


  @tf.function
  def _step(self, last_state, last_symbol):
    # Embed last symbol
    last_symbol_emb = tf.nn.embedding_lookup(self.emb, last_symbol)
    
    # Compute new state
    _, state = self.cell(last_symbol_emb, [last_state], training=False)
    state = state[0]
 
    # Predict new symbol
    logits = tf.matmul(state, self.softmax_w, transpose_b=True) + self.softmax_b

    return state, logits
  

  @tf.function
  def __call__(self, inputs):
    batch_size, L = tf.shape(inputs)[0], tf.shape(inputs)[1]

    last_state = self.cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
    last_symbol = tf.fill([batch_size], 0)

    # One loss term per time-step
    total_loss = 0.0
    for i in tf.range(L):
      last_state, logits = self._step(last_state, last_symbol)
      last_symbol = inputs[:, i]
  
      batch_loss = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=inputs[:,i])
      total_loss += tf.reduce_mean(batch_loss)
      
    total_loss /= tf.cast(L, tf.float32)

    return total_loss
```

To rule out one culprit, the `TensorArray`s have been removed. Clearly, an efficient model would not perform embedding and loss computation in every step but that's not relevant here.

To perform training I use a standard tensorflow 2.0 loop (with dummy input for simplicity)

```python
# Parameters
batch_size = 64
vocab_size = 30000
seq_length = 28

# Model
something = {str(i) : i for i in range(400000)}
rnn = DynamicRNN(512, 100, vocab_size, something)
# Optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

# Dummy input
seq = tf.ones([batch_size, seq_length], dtype=tf.int32)

# Training loop
for step in tqdm.tqdm(range(100000)):
  with tf.GradientTape() as tape:
    loss = rnn(seq)
  grads = tape.gradient(loss, rnn.trainable_variables)
  optimizer.apply_gradients(zip(grads, rnn.trainable_variables))
```

The crucial part here is the `something` object which is passed to the model. Note that the object is never used inside the model, hence we can also pass `None` instead.

My point is that the training performance on GPU and CPU is significantly degraded when the relatively memory costly  `something` object is passed instead of `None`. Precisely, I get a slowdown from 0.13s/it to 7.7s/it on the GPU and 2s/it to 9s/it on the CPU. Utilization drops from ~65% to %5 on the GPU and from 800% to 300% (24 cores available) on the cpu.

The above makes me suspicious that the model is being copied in *every* training step. I found this behavior nowhere documented. Is it? Also note that such an `something` dictionary is entirely realistic if what you do is NLP and you need to carry your vocabulary around. If that object is being used internally, a more efficient alternative might be to pass it as a function argument, instead of storing it internally.

**Comment by rmothukuru** [comment] 2019-10-21 09:02
@schmiflo,
Tried reproducing your code, but it is resulting in the error, `NameError: name 'tqdm' is not defined`. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/e91992c2896e8b6338adb28409d0de8e/33527_cpu.ipynb#scrollTo=rxpoE5BiiWQn). 

Can you please help us reproduce the issue. Thanks!

**Comment by schmiflo** [comment] 2019-10-21 13:51
@rmothukuru 

Sorry, I forgot to add imports. Either add
```python 
import tensorflow as tf
import tqdm
```
if you have tqdm installed (`pip3 install --user tqdm`) or turn `tqdm.tqdm(range(100000))` into `range(100000)` but then you have to measure time per iteration in some other way.

**Comment by rmothukuru** [comment] 2019-10-22 12:43
Could reproduce the issue with TF Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/27101d39d90aa55bd05b33d140dcaac4/33527_cpu.ipynb).

**Comment by qlzh727** [comment] 2020-03-20 21:41
Thanks for reporting the issue and sorry for the very late reply. Let me explain in details.

1. In tensorflow, there is a concept for trackable item, which we use to track dependency between python objects, and we use this dependency graph to determine which part of the execution graph we need to save when we do model checkpointing and saving.

2. For keras subclass model, like the DynamicRNN class in your example, we by default track any fields that is created by user as the attribute, eg user can do:
```
self.variable1 = tf.Variable()
```
If we don't track those information, we won't be able to save the model correctly.

3. When tracking attributes, we also check the type of value, and see if it worth tracking. Eg, tensors, and variables are key concepts which we want to track. On the other hand, int, string and primitive types  that are not mutable is not in the scope. For mutable container like list, dict, since we don't know whether user will add anything to it during training, we by default track them. And this is causing the slowdown in your example.

4. To test my theory, you can do
``` 

from tensorflow.python.training.tracking import data_structures
....
    self.something = data_structures.NoDependency(something)
```

This will force tensorflow to not track the object, and bring the performance back to normal. Also you can change to `something = tuple(str(i) for i in range(400000))` and see the performance (tuple is immutable and we don't track them as long as it doesn't contain tensor or variable).

Hope this resolve your confusion. I am closing this bug for now, feel free to reopen it if u feel there is anything else need to be addressed here.

**Closed by qlzh727** 2020-03-20 21:41 UTC
Labels: TF 2.0, comp:keras, stat:awaiting tensorflower, type:performance
