### ISSUE TITLE
MLIR-based convertor fails to convert Universal Sentence Encoder model

### ISSUE THREAD

**Issue by wboleksii** [tensorflow/tensorflow#34763] opened 2019-12-02 16:12 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): tf-nightly 2.1.0.dev20191202 also tried tf-nightly-gpu 2.1.0.dev20191202

**Command used to run the converter or code if you’re using the Python API**

```
saved_model_dir = '... local path to https://tfhub.dev/google/universal-sentence-encoder-large/4 '
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.experimental_new_converter = True
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
2019-12-02 11:06:35.679573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3020 MB memory) -> physical GPU (device: 0, name: Quadro M2200, pci bus id: 0000:01:00.0, compute capability: 5.2)
2019-12-02 11:06:36.258120: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2019-12-02 11:06:36.258307: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 3003 nodes (0), 3003 edges (0), time = 149.21ms.
2019-12-02 11:06:36.258515: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 3003 nodes (0), 3003 edges (0), time = 144.701ms.
2019-12-02 11:06:36.258724: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_pruned_16231
2019-12-02 11:06:36.258972: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-12-02 11:06:36.259294: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-12-02 11:06:39.543465: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-12-02 11:06:39.544669: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-12-02 11:06:39.546506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: Quadro M2200 computeCapability: 5.2
coreClock: 1.036GHz coreCount: 8 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 82.08GiB/s
2019-12-02 11:06:39.546854: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2019-12-02 11:06:39.547033: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2019-12-02 11:06:39.547210: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2019-12-02 11:06:39.547386: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2019-12-02 11:06:39.547560: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2019-12-02 11:06:39.547739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2019-12-02 11:06:39.547922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-12-02 11:06:39.548392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2019-12-02 11:06:39.548564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-02 11:06:39.548735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2019-12-02 11:06:39.548842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2019-12-02 11:06:39.549462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3020 MB memory) -> physical GPU (device: 0, name: Quadro M2200, pci bus id: 0000:01:00.0, compute capability: 5.2)
2019-12-02 11:06:39.665521: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2019-12-02 11:06:39.665699: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 3003 nodes (0), 3003 edges (0), time = 39.697ms.
2019-12-02 11:06:39.665895: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 3003 nodes (0), 3003 edges (0), time = 35.538ms.
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/tf_models/main.py", line 70, in <module>
    tflite_model = converter.convert()
  File "C:\Users\User\anaconda3\envs\tf_models\lib\site-packages\tensorflow_core\lite\python\lite.py", line 474, in convert
    **converter_kwargs)
  File "C:\Users\User\anaconda3\envs\tf_models\lib\site-packages\tensorflow_core\lite\python\convert.py", line 475, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\User\anaconda3\envs\tf_models\lib\site-packages\tensorflow_core\lite\python\convert.py", line 215, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-12-02 11:06:42.830207: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-12-02 11:06:42.830437: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
...
...
2019-12-02 11:06:43.425042: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-12-02 11:06:43.425241: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-12-02 11:06:43.425462: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-12-02 11:06:43.426297: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: StatefulPartitionedCall
2019-12-02 11:06:43.427219: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-12-02 11:06:43.427479: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-12-02 11:06:43.427895: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-12-02 11:06:43.428165: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-12-02 11:06:43.428599: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)


```

**Also, please include a link to the saved model or GraphDef**

```
https://tfhub.dev/google/universal-sentence-encoder-large/4
```

**Comment by daverim** [comment] 2019-12-03 10:06
I believe this is a duplicate of #26626, but I'm checking on it with the v2 converter.

**Comment by wboleksii** [comment] 2019-12-03 14:36
> I believe this is a duplicate of #26626, but I'm checking on it with the v2 converter.

@daverim that issue is for the old version of converter. The error is also look different.

**Comment by daverim** [comment] 2019-12-04 01:10
The issue in 26626 was unsupported ops, which I'm seeing in your error messages as well, but yes, your path and model seem to be different so I am taking a look at it.

**Comment by wboleksii** [comment] 2019-12-23 14:49
@daverim have you had a chance to take a look?

**Comment by anurag89sharma** [comment] 2020-04-23 06:04
@daverim Did you get a chance to look at it.
I am also facing the same issue in converting the [Universal Sentence Encoder Large model](https://tfhub.dev/google/universal-sentence-encoder-large/5) and my `tensorflow` version is `2.1.0`

Here is the error I am getting

```
ConverterError: See console for info.
2020-04-23 11:06:59.248348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-23 11:07:23.991599: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-04-23 11:07:24.071588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-23 11:07:24.157016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 with Max-Q Design computeCapability: 7.5
coreClock: 1.305GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 357.69GiB/s
2020-04-23 11:07:24.157935: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-23 11:07:24.193097: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-23 11:07:24.239225: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-23 11:07:24.244705: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-23 11:07:24.280229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-23 11:07:24.296901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-23 11:07:24.359551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-23 11:07:24.362297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-23 11:07:27.678001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-23 11:07:27.678432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-04-23 11:07:27.678674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-04-23 11:07:27.682591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6304 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-04-23 11:07:30.334652: E tensorflow/lite/toco/import_tensorflow.cc:2252] tensorflow::ImportGraphDef failed with status: Invalid argument: Input 0 of node Func/StatefulPartitionedCall_1/input/_185 was passed float from Embeddings/sharded_0:0 incompatible with expected resource.
2020-04-23 11:07:32.067931: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: StatefulPartitionedCall
2020-04-23 11:07:32.068967: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

Current thread 0x0000485c (most recent call first):
  File "C:\Users\anu10961\.conda\envs\document-similarity\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56 in execute
  File "C:\Users\anu10961\.conda\envs\document-similarity\lib\site-packages\absl\app.py", line 250 in _run_main
  File "C:\Users\anu10961\.conda\envs\document-similarity\lib\site-packages\absl\app.py", line 299 in run
  File "C:\Users\anu10961\.conda\envs\document-similarity\lib\site-packages\tensorflow_core\python\platform\app.py", line 40 in run
  File "C:\Users\anu10961\.conda\envs\document-similarity\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93 in main
  File "C:\Users\anu10961\.conda\envs\document-similarity\Scripts\toco_from_protos-script.py", line 10 in <module>
```

**Comment by SkylerZheng** [comment] 2021-10-10 02:45
any solutions? I met the same problem with TF2.0

**Closed** 2022-04-14 09:23 UTC
Labels: stat:awaiting response, stalled, comp:lite, TF 2.1
