### ISSUE TITLE
Cannot open include file: 'absl/strings/string_view.h

### ISSUE THREAD

**Issue by penghao1990** [tensorflow/tensorflow#31116] opened 2019-07-29 01:23 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment] 2019-07-30 09:20
@penghao1990 ,
Can you please fill details in the above mentioned template.
Also In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by oanush** [comment] 2019-08-09 09:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-09 09:17 UTC
Labels: comp:ops, stat:awaiting response, type:support
