### ISSUE TITLE
TFlite got error output when enable hexagon delegate

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#36804] opened 2020-02-17 01:34 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** - Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): - OS Platform and Distribution (
Linux Ubuntu 16.04): - Mobile device (OPPO reno ace) if
the issue happens on mobile device: - TensorFlow installed from (source or
binary): - TensorFlow version (use command below): - Python version: - Bazel
version (if compiling from source): - GCC/Compiler version (if compiling from
source): - CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I use this model for testing: https://storage.googleapis.com/mirror.tensorflow.org/storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_0.75_quant_2018_06_29.zip
I set all input values as 1(just for tesing), then print the first 50 values of output[0], see below picture, on the left is the values when running on CPU, on the right is the values when enable hexagon delegate, 
![cpu_dsp](https://user-images.githubusercontent.com/29744812/74617424-eee9c300-5167-11ea-9061-53225444a7b7.png)

CPU and DSP got diffrent output

**Describe the expected behavior**
CPU and DSP should get the same output values

**Code to reproduce the issue** Provide a reproducible test case that is the
bare minimum necessary to generate the problem.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2020-02-17 05:11
@huanyingjun Please provide us with simple executable stand alone code[along with the tensorflow version] so we could replicate the issue in our environment.

**Comment by huanyingjun** [comment] 2020-02-17 10:37
@Saduf2019
tensorflow is at commit ID: a00bd4687adac4d5f1880595262276e656375322, Date:   Sun Feb 16 15:18:17 2020 -0800
I use tflite benchmark_model for testing, just modify a few lines:
benchmark_tflite_model.cc   PrepareInputData
line 478: modify low and high
int low = 1;//has_value_range ? low_range : 0;
int high = 1;//has_value_range ? high_range : 254;

and line 656, modify "RunImpl" as below:
`TfLiteStatus BenchmarkTfLiteModel::RunImpl() { 
	TfLiteStatus ret = interpreter_->Invoke(); 

	auto interpreter_outputs = interpreter_->outputs();
	TfLiteTensor* t = interpreter_->tensor(interpreter_outputs[0]);
	float* out_ptr = t->data.f;
	printf("==================\n");
	for (int i = 0; i < 50; i++)
	{
		if (i % 10 == 0 && i)
			printf("\n");
		printf("%f ", out_ptr[i]);
	}
	printf("\n==================\n");
	
	return ret;
}` 

then run benchmark with CPU and DSP， you can get the output value.

**Comment by huanyingjun** [comment] 2020-02-17 11:39
And I also test with mobilenet-v2 ( https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz )

Also set input values as 1 just for testing, modify below codes:
benchmark_tflite_model.cc
line 478 PrepareInputData ：
```
} else if (t->type == kTfLiteUInt8) {
int low = 1;//has_value_range ? low_range : 0;
int high = 1;//has_value_range ? high_range : 254;
```

and line 656, modify "RunImpl" as below:
```
TfLiteStatus BenchmarkTfLiteModel::RunImpl() { 
	TfLiteStatus ret = interpreter_->Invoke(); 

	auto interpreter_outputs = interpreter_->outputs();
	TfLiteTensor* t = interpreter_->tensor(interpreter_outputs[0]);
	uint8_t* out_ptr = t->data.uint8;
	printf("==================\n");
	for (int i = 0; i < 50; i++)
	{
		if (i % 10 == 0 && i)  printf("\n");
		printf("%f ", (out_ptr[i] - t->params.zero_point) * t->params.scale);
	}
	printf("\n==================\n");
	
	return ret;
}
```
CPU and DSP got different output values
![cpu_dsp_mv2](https://user-images.githubusercontent.com/29744812/74650556-f6878700-51bc-11ea-90b4-ab6645328c35.png)

**Comment by Saduf2019** [comment] 2020-02-18 06:48
@huanyingjun Can you please share the tensorflow version used, it helps us resolve th eissue

**Comment by huanyingjun** [comment] 2020-02-18 08:12
@Saduf2019
tensorflow is at commit ID: a00bd46, Date: Sun Feb 16 15:18:17 2020 -0800

**Comment by srjoglekar246** [comment] 2020-02-21 00:48
Hey @huanyingjun, the output-pointer casting in your MobileNetv2 example (where you use `t->data.uint8`) is the correct, but the SSD one is wrong - I assume you fixed it later.

It might also be good to generate random data instead of using all 1s (but then you will need to run both settings with the same). 
Minimal, equal activations (such as 1) amplify the small differences in execution on DSP & CPU - they are never the exact same.

Also, may you try our [inference_diff](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff) tool which was specifically built for this kind of testing? It runs both settings (CPU/delegate) with the same random data and returns errors between each output tensor. If these are high for you, we need to debug.

**Comment by huanyingjun** [comment] 2020-02-21 03:04
@srjoglekar246
hello, I tried inference_diff with 3 models, below is the result:
mobilenet_v1_1.0_224_quant.tflite (https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz)
```
output_errors {
      max_value: 0.0659340695
      min_value: 0.00799200777
      avg_value: 0.026453545093536378
      std_deviation: 0.0120730288
    }
```


mobilenet_v2_1.0_224_quant.tflite ( https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz )
```
output_errors {
      max_value: 5.48851156
      min_value: 5.13486528
      avg_value: 5.251767578125
      std_deviation: 0.0698218346
    }
```
detect.tflite (https://storage.googleapis.com/mirror.tensorflow.org/storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_0.75_quant_2018_06_29.zip)
```
output_errors {
      max_value: 0.433035672
      min_value: 0.255494833
      avg_value: 0.33961360931396484
      std_deviation: 0.0411406
    }
    output_errors {
      max_value: 37.4
      min_value: 7.9
      avg_value: 20.665998535156248
      std_deviation: 6.46516037
    }
    output_errors {
      max_value: 0.707812488
      min_value: 0.662890613
      avg_value: 0.68922660827636717
      std_deviation: 0.00848944299
    }
    output_errors {
      max_value: 0
      min_value: 0
      avg_value: 0
      std_deviation: 0
    }
```

seems mobilenet-v1 is correct.
but for mobilenet-v2 and  SSD, the  avg_value is high
mobilenet-v2:  (avg_value: 5.251767578125), 
SSD:  (avg_value: 20.665998535156248)

Could you please help check this ?

**Comment by prokotg** [comment] 2020-02-21 09:07
@huanyingjun Hi, I have been trying to use Hexagon Delegate with QCS605 and I'm getting the same results for SSD MobileNet but the confidence is not around 0.67 but 0.82 as described here #36927 . It now seems like a similar issue

**Comment by srjoglekar246** [comment] 2020-02-21 16:25
I can reproduce this issue. Lemme debug and send a fix :-)

**Comment by huanyingjun** [comment] 2020-02-22 10:11
@srjoglekar246
Thanks for your kindly response, I have an other question, Could you please share me how to build libhexagon_nn_skel.so for tflite?
TFLite hexagon delegate is based on hexagon nnlib, I can get nnlib source code from https://source.codeaurora.org/quic/hexagon_nn/nnlib, and I can build ibhexagon_nn_skel.so according to "README.HOW_TO_BUILD" in nnlib, but my build libhexagon_nn_skel.so can not be used for tflite, report some error. Does tflite modify the nnlib code ? how to build libhexagon_nn_skel.so using the nnlib source code ?

**Comment by srjoglekar246** [comment] 2020-02-24 17:02
Short answer is, you cannot (unless you have Qualcomm's dev board).
Only Qualcomm can build & sign a binary that runs on non-debug devices in the wild.

**Comment by srjoglekar246** [comment] 2020-02-25 20:50
The fix for this should be in by now. We were handling Convolution with an activation (RELU6) incorrectly, hence the issue with SSD MobileNet.

About the outputs from the `inference_diff` tool & your own scripting:
I see diffs for MobileNetV2 & the int vector of SSD still, but when I checked with our [classification & object detection tooling](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks), the models got correct accuracy with the ImageNet/COCO datasets.

From what I understand, randomized inputs are hard to interpret like actual data (eg images), since constant values or gaussian distributions don't entail typical model behavior. For example, the NMS post-processing that SSD does causes large deviations for random inputs, since there is sorting going on under-the-hood.

The way we typically use the diff tool is take a 'snapshot' of the output errors when we know the model is behaving correctly with the delegate, and then debug if the errors suddenly diverge. For example, the SSD model - with the fix, its avg diff for output tensor#1 is 8 with low std_deviation, while the one we saw before that is ~20 with a high std_deviation.

**Closed by srjoglekar246** 2020-02-25 20:50 UTC
Labels: TF 2.1, comp:lite, type:bug

**Comment by prokotg** [comment] 2020-02-26 18:03
@srjoglekar246 so where the bug was exactly and what should I update? Cheers!

**Comment by srjoglekar246** [comment] 2020-02-26 18:24
The bug was in the TensorFlow code, so you just need to use the latest nightly/master version. If you are using Android, the [nightly AAR](https://www.tensorflow.org/lite/performance/hexagon_delegate#step_1_edit_appbuildgradle_to_use_the_nightly_hexagon_delegate_aar_2) should work. Or if you are using the benchmark tool, BUILD from master :-)

**Comment by prokotg** [comment] 2020-02-26 18:26
@srjoglekar246 Thank you :))

**Comment by mazeltovlee** [comment] 2021-11-05 06:52
Thanks for solving this problem, can you kindly direct me to the pr/commit link where you fix this bug?

**Comment by srjoglekar246** [comment] 2021-11-08 17:11
The fix landed a while back, but everything after [this commit](https://github.com/tensorflow/tensorflow/commit/920bf272c8187ee68d810d468209400ba7f7c4c9#diff-c47a66c8e8e1fead95278a60d5aa66a287b7b44467137998f093b5d203105061) included the fix.
