### ISSUE TITLE
Tensorflow Estimator InvalidArgumentError

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#31525] opened 2019-08-12 02:52 UTC
TF 1.13.1 binary on ubuntu 18.10

the same issue with that on stackoverflow: https://stackoverflow.com/questions/54089982/tensorflow-estimator-invalidargumenterror

The issue occurs when the categorical feature size is very large and reports bug of `Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.` 

however, when reducing the size of categorical feature size, the issue disappears.

One very important detail is that I build the estimatorSpec myself, which is quite important because using the standard `DNNLinearCombinedClassifier` would not have the above error. At the same time, if I reduce the the size of categorical feature size with the `estimatorSpec` I build myself, the issue also disappears. And the above issue poster on the stackoverflow solves this problem by limiting the feature size to 17k features. Unfortunately with the feature size going larger than 17k, the same issue happens.

So is there any restrict of the categorical feature size on the `estimatorSpec ` ?

**Comment by sjtusmartboy** [comment] 2019-08-12 09:29
It seems 2GB of embedding matrix is the bottleneck

**Comment by jvishnuvardhan** [comment] 2019-08-13 19:08
@sjtusmartboy Did you try with recent version of TF (`1.14.0`, `tf-nightly`, `2.0b1`). Thanks!

**Comment by karmel** [comment] 2019-08-14 19:58
I don't fully understand what is being described here-- the linked SO post seems unrelated? Can you clarify, and provide a minimal code sample to reproduce the issue you are describing?

**Comment by gadagashwini** [comment] 2020-01-03 10:51
@sjtusmartboy, Can you provide the minimal code snippet to analyze the reported issue.Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-08 22:18
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-01-08 22:18 UTC
Labels: TF 1.13, comp:apis, stat:awaiting response, type:support
