### ISSUE TITLE
ERROR message when using tf.SyncReplicasOptimizer

### ISSUE THREAD

**Issue by mari-linhares** [tensorflow/tensorflow#11823] opened 2017-07-27 18:16 UTC
I'm running distributed tensorflow with estimators, in order to it in sync mode I'm using tf.SyncReplicasOptimizer, but casually (specially after evaluation) I see the following error on the master:
```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables/boolean_mask/Gather:0' shape=(?,) dtype=string>

['File "cifar10_main.py", line 538, in <module>\n    tf.app.run()', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run\n    _sys.exit(main(_sys.argv[:1] + flags_passthrough))', 'File "cifar10_main.py", line 518, in main\n    hooks), run_config=config)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 210, in run\n    return _execute_schedule(experiment, schedule)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 47, in _execute_schedule\n    return task()', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 501, in train_and_evaluate\n    hooks=self._eval_hooks)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 681, in _call_evaluate\n    hooks=hooks)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 292, in evaluate\n    name=name)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 638, in _evaluate_model\n    features, labels, model_fn_lib.ModeKeys.EVAL)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 545, in _call_model_fn\n    features=features, labels=labels, **kwargs)', 'File "cifar10_main.py", line 331, in _resnet_model_fn\n    gradvars, global_step=tf.train.get_global_step())', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/sync_replicas_optimizer.py", line 252, in apply_gradients\n    variables.global_variables())', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================

```
Code available at:https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10_estimator/cifar10_main.py

**Comment by reedwm** [comment] 2017-07-27 21:29
The [file](https://github.com/mari-linhares/models/blob/f24c44d5b94c516ac630110ca6f32eb8a3f023f9/tutorials/image/cifar10_estimator/cifar10_main.py) your pull request modified only appears to support single-process TensorFlow, not distributed TensorFlow.

What command(s) did you run that caused the error?

**Comment by mari-linhares** [comment] 2017-07-27 22:04
It's using experiments (tf.estimators) so it supports distributed TensorFlow. This Error happened after the master executed evaluation, and once the worker finished training. I executed this with 1 master, 1 worker and 1 ps.

**Comment by reedwm** [comment] 2017-07-27 22:28
What commands did you run to start the master, worker, and ps?

**Comment by mari-linhares** [comment] 2017-07-28 18:21
You need to have a TF_CONFIG environment variable, example for TF_CONFIG in the master:

```python
cluster = {'master': ['localhost:8000'],
           'ps': ['localhost:8888'],
           'worker': ['localhost:8009']}

TF_CONFIG = json.dumps(
  {'cluster': cluster,
   'task': {'type': master, 'index': 0},
   'model_dir': 'gs://<bucket_path>/<dir_path>',
   'environment': 'cloud'
  })
```
Then you can run the following script in all the machines.
```shell
python cifar10_main.py --run_experiment=True --num_workers=2 --train_batch_size=64 --num_gpus=1 --data_dir=<data_dir> --model_dir=gs://<bucket_path>/<dir_path>
```

**Comment by reedwm** [comment] 2017-07-28 22:35
Thanks for the info, I did not know about TF_CONFIG. I was not able to reproduce locally by running 3 processes on my local machine, but I didn't try on separate machines. How long does it usually take before the error occurs? I ran for about 30 minutes.

Also, when running with 1 master, 1 worker, and 1 ps, did you set --num_workers=1 (it's set to 2 in your example above).

@ali01 Can you look into this? I wonder if this is related to #11753.

**Comment by mari-linhares** [comment] 2017-07-30 19:33
@reedwm you should be able to reproduce it locally... I think I missed the `--sync=True` flag, make sure you have it and you should see it, sorry.

*Also, when running with 1 master, 1 worker, and 1 ps, did you set --num_workers=1 (it's set to 2 in your example above).*

Yes, the master counts as one worker as well since it also does training.

**Comment by mari-linhares** [comment] 2017-07-31 14:32
Also, you don't need to run distributed to see the error, if you run locally with `--sync=True` you should be able to see it. Thanks!

**Comment by mari-linhares** [comment] 2017-07-31 21:30
I also see this error sometimes:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 254, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 211, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
CancelledError: TakeGrad operation was cancelled
	 [[Node: sync_replicas/AccumulatorTakeGradient_15 = AccumulatorTakeGradient[_class=["loc:@sync_replicas/conditional_accumulator_15"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](sync_replicas/conditional_accumulator_15, sync_replicas/AccumulatorTakeGradient_15/num_required)]]

**Comment by reedwm** [comment] 2017-08-01 18:09
I'm able to reproduce locally with `--sync=True`, by running the three terminal commands in three different terminal windows:
```
CUDA_VISIBLE_DEVICES= TF_CONFIG='{"environment": "cloud", "cluster": {"worker": ["localhost:12347"], "ps": ["localhost:12346"], "master": ["localhost:12345"]}, "task": {"index": 0, "type": "worker"}, "model_dir": "/tmp/model"}' python cifar10_main.py --run_experiment=True --num_workers=2 --train_batch_size=64 --num_gpus=0 --data_dir ~/cifar-10-batches-bin --model_dir=/tmp/model --is_cpu_ps=True --sync=True
```
```
CUDA_VISIBLE_DEVICES= TF_CONFIG='{"environment": "cloud", "cluster": {"worker": ["localhost:12347"], "ps": ["localhost:12346"], "master": ["localhost:12345"]}, "task": {"index": 0, "type": "ps"}, "model_dir": "/tmp/model"}' python cifar10_main.py --run_experiment=True --num_workers=2 --train_batch_size=64 --num_gpus=0 --data_dir ~/cifar-10-batches-bin --model_dir=/tmp/model --is_cpu_ps=True --sync=True
```
```
CUDA_VISIBLE_DEVICES= TF_CONFIG='{"environment": "cloud", "cluster": {"worker": ["localhost:12347"], "ps": ["localhost:12346"], "master": ["localhost:12345"]}, "task": {"index": 0, "type": "master"}, "model_dir": "/tmp/model"}' python cifar10_main.py --run_experiment=True --num_workers=2 --train_batch_size=64 --num_gpus=0 --data_dir ~/cifar-10-batches-bin --model_dir=/tmp/model --is_cpu_ps=True --sync=True
```

I consistently get the "Object was never used" error on the master after the first evaluation.

The stack trace in the error message (from the [first comment](https://github.com/tensorflow/tensorflow/issues/11823#issue-246125815)) is hard to read since its printed as a Python list. The stack trace, with line breaks, is
```
File "cifar10_main.py", line 538, in <module>
    tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "cifar10_main.py", line 518, in main
    hooks), run_config=config)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 210, in run
    return _execute_schedule(experiment, schedule)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 47, in _execute_schedule
    return task()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 501, in train_and_evaluate
    hooks=self._eval_hooks)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 681, in _call_evaluate
    hooks=hooks)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 292, in evaluate
    name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 638, in _evaluate_model
    features, labels, model_fn_lib.ModeKeys.EVAL)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 545, in _call_model_fn
    features=features, labels=labels, **kwargs)
File "cifar10_main.py", line 331, in _resnet_model_fn
    gradvars, global_step=tf.train.get_global_step())
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/sync_replicas_optimizer.py", line 252, in apply_gradients
    variables.global_variables())
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning
    wrapped = TFShouldUseWarningWrapper(x)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__
    stack = [s.strip() for s in traceback.format_stack()]
```

Still waiting for @ali01 to respond.

**Comment by mari-linhares** [comment] 2017-08-01 18:17
Thank you for taking to reproduce this @reedwm! Can you train again for 1 epoch and see if you can get the other Error I mentioned on the last comment?

**Comment by reedwm** [comment] 2017-08-01 19:42
I was not able to reproduce the other error. I ran the three terminal commands above for 4000 steps, which I believe is several epochs. I did get the original "Object was never used" error after every evaluation, however.

**Comment by mari-linhares** [comment] 2017-08-01 19:48
I see thank you @reedwm.

**Comment by pickou** [comment] 2017-10-12 08:05
@mari-linhares have you ever fixed the "Object was never used" error?

**Comment by mari-linhares** [comment] 2017-10-12 13:16
@pickou not really :/

**Comment by jeffcbecker** [comment] 2017-11-02 18:30
I also encountered a similar error when attempting to use SyncReplicasOptimizer for MNIST, and was wondering if any progress has been made on this issue. Thanks.

**Comment by tensorflowbutler** [comment] 2018-01-04 19:10
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:17
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tatatodd** [comment] 2018-01-25 02:35
@reedwm looks like you reproduced the issue and have some state here.  How do you suggest we proceed?

**Comment by reedwm** [comment] 2018-01-25 17:33
I was able to reproduce but have know idea why the problem occurs. Someone needs to look at SyncReplicasOptimizer, but unfortunately most people who worked on it no longer work on TensorFlow.

/CC @ispirmustafa @panyx0718, can either of you take a look?

**Comment by tensorflowbutler** [comment] 2018-02-14 13:23
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:59
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-17 14:58
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 12:45
Nagging Assignee @aselle: It has been 99 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:12
Nagging Assignee @aselle: It has been 115 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:40
Nagging Assignee @aselle: It has been 130 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:06
Nagging Assignee @aselle: It has been 145 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 18:58
Nagging Assignee @aselle: It has been 160 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:54
Nagging Assignee @aselle: It has been 175 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 12:58
Nagging Assignee @aselle: It has been 190 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-08-09 18:05
@mari-linhares, we apologize this slipped through the cracks. Is this still an issue for you, and are you interested in the solution?

**Comment by mari-linhares** [comment] 2018-08-15 13:50
Hey @aselle, thank you for the response, I think it's a valuable fix considering that estimators are still the easiest way to run distributed tensorflow.

**Comment by reedwm** [comment] 2018-08-16 18:15
/CC @josh11b do you know who should handle issues with SyncReplicasOptimizer?

**Comment by tensorflowbutler** [comment] 2018-08-31 19:28
Nagging Assignee @reedwm: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:31
Nagging Assignee @reedwm: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:42
Nagging Assignee @reedwm: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-27 12:33
Nagging Assignees @reedwm, @josh11b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-11 18:35
Nagging Assignees @reedwm, @josh11b: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by josh11b** [comment] 2018-11-11 19:39
SyncReplicaOptimizer has been unsupported for some time and now is
officially deprecated.

Many cases can now use MirroredStrategy or CollectiveAllReduceStrategy
instead.

**Comment by azaks2** [comment] 2018-11-15 21:15
Closing, since SyncReplicaOptimizer is no longer maintained.

**Closed by azaks2** 2018-11-15 21:15 UTC

**Comment by guoshimin** [comment] 2018-12-02 07:03
Is the fact that SyncReplicasOptimizer is deprecated documented somewhere? Certainly not in the API doc https://www.tensorflow.org/api_docs/python/tf/train/SyncReplicasOptimizer.

**Comment by jw447** [comment] 2019-02-28 19:54
Can anyone suggest a workaround of this case? What would be the best replace of SyncReplicasOptimizer? I'm running inception from research repo and I'm facing the same issue when running distributed tensorflow.

**Comment by josh11b** [comment] 2019-02-28 20:02
The recommended approach is to use tf.distribute.*Strategy (such as MirroredStrategy), but I have not personally tested it with Inception.

**Comment by jw447** [comment] 2019-03-01 19:12
Thank you @josh11b. Can you suggest a distributed learning example where mirror strategy and/or parameterserver strategy is used? I would like to look at some cases before try on inception.

**Comment by jw447** [comment] 2019-03-01 20:48
@josh11b Also, is there an easier workaround if I turn it into asynchronized parameter server by discarding the SyncReplicasOptimizer?

**Comment by josh11b** [comment] 2019-03-01 21:46
Turning off SyncReplicasOptimizer should give you regular parameter server behavior. You can see our distributed training guide at https://www.tensorflow.org/guide/distribute_strategy
