### ISSUE TITLE
Cannot install tensorflow on OSX

### ISSUE THREAD

**Issue by mohitsharma0690** [tensorflow/tensorflow#5155] opened 2016-10-24 00:14 UTC
I'm having issues installing tensorflow on my mac device. I seem to be getting a protobuf version mismatch with rc0 wheel. 

> Installing collected packages: protobuf, tensorflow
>   Found existing installation: protobuf 3.0.0a2
>     Uninstalling protobuf-3.0.0a2:
>       Successfully uninstalled protobuf-3.0.0a2
>   Found existing installation: tensorflow 0.11.0rc0
>     Uninstalling tensorflow-0.11.0rc0:
>       Successfully uninstalled tensorflow-0.11.0rc0
> Successfully installed protobuf-3.0.0 tensorflow-0.11.0rc1

And then trying to import

```
python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB2\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

This thread https://github.com/tensorflow/tensorflow/issues/11 seems to mention this to be a protobuf version mismatch error but I'm not sure. 

Any workarounds or if anyone has a clue on what's wrong?

**Comment by asimshankar** [comment] 2016-10-24 08:28
@mohitsharma0690 : Thanks for the report. However, could you please add some more detail, for example, a minimal set of steps one can take to reproduce the problem? For example, I tried the following on my OS X El Capitan laptop (where I use [virtualenv](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#virtualenv-installation)) and was able to get things working:

```sh
virtualenv --system-site-packages ~/tensorflow
source ~/tensorflow/bin/activate 
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc1-py2-none-any.whl
pip install --upgrade $TF_BINARY_URL
python -c "import tensorflow; print tensorflow.__version__"
```

Let us know what steps you took that led to this problem, and we might be able to figure it out. If possible, please provide all details asked for in the [New issue template](https://github.com/tensorflow/tensorflow/issues/new).

**Comment by asimshankar** [comment] 2016-10-24 17:18
This seems similar to #5168 , which (though for Ubuntu) has more detail. Closing this bug out as a duplicate, please follow along on #5168  (and maybe use virtualenv if you can, since that isolates the pip packages and their dependencies)

**Closed by asimshankar** 2016-10-24 17:18 UTC
Labels: awaiting response

**Comment by mohitsharma0690** [comment] 2016-11-08 20:40
For anyone seeing this, my issue was with having protobuf(2.6.0 or something) installed somehow via homebrew, it worked after removing it.

**Comment by WillBrennan** [comment] 2017-01-24 10:45
Ran across this as well, upgrading protobuf also works (installed version 3.1).

**Comment by savetime1210** [comment] 2020-04-09 21:27
i think tensorflow is not supported on python 3.8. Any idea?
