### ISSUE TITLE
Mixed precision failed with OOM on A100 GPUs and Tensorflow 2.5

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#50200] opened 2021-06-10 16:15 UTC
We have a keras based code that we would like to run in mixed precision.

We enable the mixed precision computation with

```
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)
```

The code works when mixed precision policy is disabled.
The code works when mixed precision is enabled with Tensorflow 2.4 on a nvidia titan RTX cards
The code fails  with OOM error when mixed precision is enabled with Tensorflow 2.5 on A100 GPU even with a reduced batch size compared to float32 version

```
node06:632909:635501 [6] bazel-out/k8-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/alloc.h:41 NCCL WARN Cuda failure 'out of memory'
```

**Comment by saikumarchalla** [comment] 2021-06-14 03:23
Could you please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by saikumarchalla** [comment] 2021-06-24 12:46
@jrabary  Please check this [colab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/mixed_precision.ipynb#scrollTo=ADgK2L5hC_x5) for mixed precison example and it should support A100 GPU.

Could you Please check with TF 2.4 on A100 GPU and let us know whether  code is working or not. Thanks!

**Comment by saikumarchalla** [comment] 2021-06-29 03:06
@jrabary Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2021-06-29 03:07 UTC
Labels: TF 2.5, comp:gpu, stalled, stat:awaiting response, type:bug
