### ISSUE TITLE
tf.cast python float to tf.float64 or tf.complex128 leads to loss of precision

### ISSUE THREAD

**Issue by jxy** [tensorflow/tensorflow#57779] opened 2022-09-21 18:36 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.10.0-rc3-6-g359c3cdfc5f 2.10.0

### Custom Code

No

### OS Platform and Distribution

tested on Linux and macOS 

### Python version

tested with 3.9 and 3.10

### Current Behaviour?

```shell
>>> tf.cast(0.2, tf.float64)
<tf.Tensor: shape=(), dtype=float64, numpy=0.20000000298023224>
>>> tf.cast(0.2, tf.complex128)
<tf.Tensor: shape=(), dtype=complex128, numpy=(0.20000000298023224+0j)>
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.print(tf.cast(0.2, tf.float64))
tf.print(tf.math.real(tf.cast(0.2, tf.complex128)))
```

### Relevant log output

_No response_</details>

**Comment by jxy** [comment] 2022-09-21 18:39
There was an issue from 2020, #35938, which was fixed then.

**Comment by sachinprasadhs** [comment] 2022-09-23 19:56
The above PR was automatically rolled back, since the tests were failing.
I have submitted the changes again. I will update once the test results are completed.

**Comment by sachinprasadhs** [comment] 2022-09-23 20:00
Update: With the changes, tests are failing again in multiple files.

**Comment by cantonios** [comment] 2022-10-19 17:14
Unfortunately the original fix for this in #35961 changes the graph representation of a bunch of models, which breaks several use-cases - which is why it was reverted.

Your other option is to use `tf.convert_to_tensor()` directly:
```
print(tf.cast(0.2, tf.float64))
print(tf.convert_to_tensor(0.2, dtype=tf.float64))

print(tf.cast(0.2, tf.complex128))
print(tf.convert_to_tensor(0.2, dtype=tf.complex128))
```
which yields
```
tf.Tensor(0.20000000298023224, shape=(), dtype=float64)
tf.Tensor(0.2, shape=(), dtype=float64)
tf.Tensor((0.20000000298023224+0j), shape=(), dtype=complex128)
tf.Tensor((0.2+0j), shape=(), dtype=complex128)
```
There has been a long-standing desire to merge the two functions, but there exists many subtle differences (like this one) preventing that.

**Comment by jxy** [comment] 2022-10-26 19:01
It is an issue when we cast a variable the precision changes depending on whether the variable contains a python float or a TF tensor.

Can we at least leave the issue open until our "long-standing desire" gets satisfied?

**Comment by cantonios** [comment] 2022-11-09 22:03
@jxy we know the cause, and we know the proper solution is to use `tf.convert_to_tensor` rather than `tf.cast` to convert numpy arrays to tensors.  We're blocked from changing `tf.cast` to address this directly, since doing so changes the graph representation which breaks existing models and workflows.  So I think our hands are tied.  You should be using `tf.convert_to_tensor` to avoid precision loss.

**Comment by felker** [comment] 2022-11-10 03:22
> Note, this operation can lead to a loss of precision when converting non-tensor inputs such as Python `float64` data type variables to `tf.float64` or `tf.complex128` tensors, since the input is first converted to the `float32` data type and then widened. For such cases, the proper solution is to use `tf.convert_to_tensor` instead of `tf.cast`

FYI it only does this for Python floats, not `np.float64` inputs:
```
print(tf.constant(0.2).dtype)
print(tf.constant(float(0.2)).dtype)
print(tf.constant(np.float64(0.2)).dtype)
print(float(0.2) == np.float64(0.2))
print(repr(tf.cast(float(0.2), dtype=tf.float64).numpy()))
print(repr(tf.cast(np.float64(0.2), dtype=tf.float64).numpy()))

<dtype: 'float32'>
<dtype: 'float32'>
<dtype: 'float64'>
True
0.20000000298023224
0.2
````

**Comment by cantonios** [comment] 2022-11-10 16:32
Correct.  The is only happening because all non-tensor inputs get sent through a bare `tf.convert_to_tensor()` first, so calling cast on a python (or numpy) value is actually like calling
```
y = tf.cast(tf.convert_to_tensor(f), tf.float64)
```
if `f` is a numpy array with dtype `np.float64`, the `convert_to_tensor` call converts it to the equivalent tensorflow type (`tf.float64`).  If it's a python float, we default to `float32`, since for most ML applications this has sufficient accuracy, and most accelerators (GPU, TPU) do a much better handling of `float32` than `float64`.

**Comment by felker** [comment] 2022-11-10 16:51
Should I open a PR for the docs with the above suggested text?

**Comment by felker** [comment] 2022-11-10 19:20
@cantonios Could you please review #58526 ?

**Closed** 2022-11-14 19:03 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, TF 2.10
