### ISSUE TITLE
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_blas.cc:268] Check failed: s.ok() could not find cublasCreate_v2 in cuBLAS DSO; dlerror: cublasCreate_v2 not found

### ISSUE THREAD

**Issue by nevermoredanny** [tensorflow/tensorflow#7292] opened 2017-02-06 15:35 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:win10

Installed version of CUDA and cuDNN: 
cuda8.0 cudnn 5

If installed from binary pip package, provide:
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-win_amd64.whl

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by girving** [comment] 2017-02-07 15:54
@mrry Want this lovely Windows GPU issue?

**Comment by mrry** [comment] 2017-02-07 16:43
Not without much more information, e.g. including what other logs are printed. If I had to guess, I'd say the problem is an incompatible version of the cuBLAS DLL in the `%PATH%`. The logs should contain additional information about what DLL was loaded.

**Comment by aselle** [comment] 2017-03-03 23:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2017-03-03 23:43 UTC
Labels: stat:awaiting response, type:build/install
