### ISSUE TITLE
ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by AdrianTanTeckKeng** [tensorflow/tensorflow#30856] opened 2019-07-18 18:39 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOs 6.10 Linux: 2.6.32-754.2.1.el6.x86_64
- TensorFlow installed from (source or binary): Conda install
- TensorFlow version: 1.14.0
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: Conda
- GCC/Compiler version (if compiling from source): c++ 4.9.2
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Import error ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so). Indicated file is there at the path.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Import tensorflow

**Any other info / logs**
>>> import tensorflow
Traceback (most recent call last):
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 34, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by wdirons** [comment] 2019-07-19 15:41
This issue looks like a duplicate of https://github.com/tensorflow/tensorflow/issues/26826

**Comment by jvishnuvardhan** [comment] 2019-08-09 22:29
I am closing this issue as it is duplicate of https://github.com/tensorflow/tensorflow/issues/26826 and workaround for the problem is provided there. We will followup with the issue there. Thanks!

**Closed by jvishnuvardhan** 2019-08-09 22:29 UTC
Labels: stat:awaiting tensorflower, subtype:centos, type:build/install

**Comment by cache203** [comment] 2020-04-14 20:50
I find this link very useful:
http://www.programmersought.com/article/3932478100/

**Comment by kiseliu** [comment] 2020-07-24 07:45
> I find this link very useful:
> http://www.programmersought.com/article/3932478100/

this could help me, thanks.

**Comment by RenzhiDaDa** [comment] 2021-07-17 09:36
> 
> 
> I find this link very useful:
> http://www.programmersought.com/article/3932478100/

thanks,it is useful for me
