### ISSUE TITLE
Bigger Tflite micro model

### ISSUE THREAD

**Issue by ginamathew** [tensorflow/tensorflow#41400] opened 2020-07-15 05:08 UTC
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 2.2.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): 

**Describe the problem**
I downloaded tflite Inception_v4 model from https://www.tensorflow.org/lite/guide/hosted_models. The model had a size of 42.9MB. I converted to tflite micro using the xxd command and the .cc file I got after conversion had a size of 264MB. Does the model conversion to cc file increase the tflite model size by 5x times? What I understand is that, tflite micro should give a smaller sized model for execution in microcontrollers. Is my understanding correct. Can you help me in solving the problem?

**Please provide the exact sequence of commands/steps when you ran into the problem**
xxd -i inception_v4_299_quant.tflite > model.cc

**Comment by ymodak** [comment] 2020-07-15 14:04
I downloaded the `inception_v4.tflite` from https://www.tensorflow.org/lite/guide/hosted_models after extraction it is `170.7mb`
In order to obtain smallest possible model size, You may want to try performing [Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) on TF Lite Flat Buffer before converting it into C.
We should also note that inception_v4 is fairly heavy architecture so the file size can be relatively bigger.

**Comment by jdduke** [comment] 2020-07-16 16:42
What is the size of the *compiled* code? I'm not sure you can use the .cc file size as a direct measure of how it will actually impact binary size.

**Comment by ginamathew** [comment] 2020-07-24 04:41
> I downloaded the `inception_v4.tflite` from https://www.tensorflow.org/lite/guide/hosted_models after extraction it is `170.7mb`
> In order to obtain smallest possible model size, You may want to try performing [Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) on TF Lite Flat Buffer before converting it into C.
> We should also note that inception_v4 is fairly heavy architecture so the file size can be relatively bigger.

Thanks Yasir. But the size of tflite micro model more than the tflite model raised the confusion

**Comment by ginamathew** [comment] 2020-07-24 04:45
> What is the size of the _compiled_ code? I'm not sure you can use the .cc file size as a direct measure of how it will actually impact binary size.

Thanks Duke. I will check that. Meanwhile one more question. Can we use python script for the same. Or is it possible with cpp code only?

**Comment by advaitjain** [comment] 2020-07-24 18:33
Note that using xxd converts the tflite model (flatbuffer binary format) into a C array. The model is unchanged and hence the binary size will also be the same.

Here are the steps that I followed to verify what I say above:
  * Downloaded tflite Inception_v4 model from https://www.tensorflow.org/lite/guide/hosted_models
  * Confirmed the size of the tflite model is ```42855504 bytes``` with ```ls -l inception_v4_299_quant.tflite```
  * Used xxd to convert to a C array with ```xxd -i inception_v4_299_quant.tflite > inception_v4_299_quant.cc ```
  * Looked at the last line of  inception_v4_299_quant.cc and confirmed that the C array takes the same number of bytes.
```tail -n1 inception_v4_299_quant.cc``` gave me ```unsigned int inception_v4_299_quant_tflite_len = 42855504;```

I'm going to close this issue, but feel free to reopen if I missed something.

Note that in general, a 48MB model is likely not suited for TF Micro. There will always be exceptions but usual latency and power requirements mean that models <1MB are more suited for systems running TF Micro.

**Closed** 2020-07-24 18:33 UTC
Labels: TF 2.2, comp:micro, stat:awaiting response, type:support

**Comment by samkellerhals** [comment] 2021-11-24 15:10
> * tail -n1 inception_v4_299_quant.cc

Thanks for the clarification @advaitjain, much appreciated !

**Comment by Heatdh** [comment] 2023-10-26 15:21
To add on these comments and as I was myself confused you would expected the size of the c array to be the same and not the size of the c source file dumped with xxd ( the increase due to formatting). Look at the end of the file to know the actual size ( with tail or by manuel inspection) and this should be closer to the tflite model size
