### ISSUE TITLE
"WARNING:tensorflow:sample_weight ..." when training a `keras.Model` with a `Sequence` object

### ISSUE THREAD

**Issue by kieranricardo** [tensorflow/tensorflow#37500] opened 2020-03-11 04:30 UTC
**System information** 
- OS Platform and Distribution: macOS 10.14.5
- Python version: 3.6

**Describe the current behavior**

Calling `tf.keras.Model.fit(...)` with any `tf.keras.utils.Sequence` object triggers the following warning:

```
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
```

Even when not using `sample_weight`.

**Describe the expected behavior**

Training keras models without sample weights specified or correctly specified should not trigger warnings about  `sample_weight`.

**Standalone code to reproduce the issue** 
```
import tensorflow as tf
import numpy as np


class TestSequence(tf.keras.utils.Sequence):

    def __init__(self, x, y, batch_size):
        self.x, self.y = x, y
        self.batch_size = batch_size

    def __len__(self):
        return len(self.x) // self.batch_size

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) *
        self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) *
        self.batch_size]

        return batch_x, batch_y
    

seq = TestSequence(np.ones(10), np.ones(10), 2)

x_in = tf.keras.layers.Input((1,))
x_out = tf.keras.layers.Dense(1)(x_in)
model = tf.keras.Model(x_in, x_out)
model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(seq)
```

**Comment by gadagashwini** [comment] 2020-03-11 09:04
@kieranricardo, I tried with latest Tf-nightly version, i don't get any warnings. 
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/a60f8fc2e229259a8f18665de35ac97b/untitled438.ipynb). Thanks!

**Comment by kieranricardo** [comment] 2020-03-11 22:43
thanks @gadagashwini! I tested with `tf-nightly` on my machine and I'm no longer getting the warning!

**Comment by gadagashwini** [comment] 2020-03-12 05:35
@kieranricardo, Since the issue is fixed in latest TF version. Are you happy to close this issue. Thanks!

**Closed** 2020-03-12 06:16 UTC
Labels: comp:keras, stat:awaiting response, type:bug
