### ISSUE TITLE
Conversion to TFLite fails with 2.4.0-rc1

### ISSUE THREAD

**Issue by KarthikDutt** [tensorflow/tensorflow#44975] opened 2020-11-18 10:48 UTC
**System information**
- OS - Windows
- TensorFlow installed from binary
- TensorFlow version (or github SHA if from source): v2.4.0-rc1

**Command used to run the converter or code if you’re using the Python API**
Running the following set of commands to do the conversion to tf-lite
```
graph_def = tf.compat.v1.GraphDef()
graph_def.ParseFromString(open('resnet.pb', 'rb').read())
concrete_func = wrap_frozen_graph(graph_def, inputs=["input:0"], outputs=["output:0"])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
converter.optimizations = [tf.compat.v1.lite.Optimize.DEFAULT]
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
--------------------------------------------------
Frozen model layers: 
--------------------------------------------------

INFO:absl:Using new converter: If you encounter a problem please file a bug. You can opt-out by setting experimental_new_converter=False

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    212                                                  debug_info_str,
--> 213                                                  enable_mlir_converter)
    214       return model_str

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     37       debug_info_str,
---> 38       enable_mlir_converter)
     39 

Exception: C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\lift_to_graph.py:339:0: error: operand #0 does not dominate this use
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\wrap_function.py:338:0: note: called from
<ipython-input-5-1fc724505eae>:18:0: note: called from
<ipython-input-9-dd55b0fa94e3>:3:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3417:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3337:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3146:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\async_helpers.py:68:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:2922:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:2877:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\lift_to_graph.py:339:0: note: operand defined here


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
<ipython-input-9-dd55b0fa94e3> in <module>
      6 converter.optimizations = [tf.compat.v1.lite.Optimize.DEFAULT]
      7 converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
----> 8 tflite_model = converter.convert()

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\lite.py in convert(self)
   1115         Invalid quantization parameters.
   1116     """
-> 1117     return super(TFLiteConverterV2, self).convert()
   1118 
   1119 

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\lite.py in convert(self)
    941 
    942     return super(TFLiteFrozenGraphConverterV2,
--> 943                  self).convert(graph_def, input_tensors, output_tensors)
    944 
    945 

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\lite.py in convert(self, graph_def, input_tensors, output_tensors)
    626         input_tensors=input_tensors,
    627         output_tensors=output_tensors,
--> 628         **converter_kwargs)
    629 
    630     calibrate_and_quantize, flags = quant_mode.quantizer_flags()

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    611       input_data.SerializeToString(),
    612       debug_info_str=debug_info_str,
--> 613       enable_mlir_converter=enable_mlir_converter)
    614   return data
    615 

~\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    214       return model_str
    215     except Exception as e:
--> 216       raise ConverterError(str(e))
    217 
    218   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\lift_to_graph.py:339:0: error: operand #0 does not dominate this use
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\wrap_function.py:338:0: note: called from
<ipython-input-5-1fc724505eae>:18:0: note: called from
<ipython-input-9-dd55b0fa94e3>:3:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3417:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3337:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:3146:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\async_helpers.py:68:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:2922:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\IPython\core\interactiveshell.py:2877:0: note: called from
C:\Users\kar11081\Anaconda3\envs\arcgis_1_8_3_tensorflow_test\lib\site-packages\tensorflow\python\eager\lift_to_graph.py:339:0: note: operand defined here
```

**Also, please include a link to the saved model or GraphDef**

```
[Link to the model](https://drive.google.com/file/d/1RSmk7zdqmHHBjkE-KPY3BNrW5q0Txv-P/view?usp=sharing)
```

**Failure details**
The failure is observed only in the v2.4.0-rc1. The conversion works fine when I switch to nightly version tf-nightly==2.4.0.dev20200901

**Comment by Saduf2019** [comment] 2020-11-19 09:09
@KarthikDutt 
I ran the code on nightly but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ca8c330949823528cbc8200fe28c35a5/untitled463.ipynb). please share all dependencies for us to replicate the issue faced.

**Comment by KarthikDutt** [comment] 2020-11-19 13:49
Hello, I have recreated the issue here: 
https://colab.research.google.com/gist/KarthikDutt/64c0ed9d9ea09a40cd6028fb339d7fe2/untitled463.ipynb

Please note, the issue doesn't occur with the nightly  2.4.0.dev20200905 but occurs in v2.4.0-rc1

**Comment by Saduf2019** [comment] 2020-11-20 04:49
@KarthikDutt 
Please share "resnet.pb" for us to replicate the issue faced.

**Comment by KarthikDutt** [comment] 2020-11-20 04:55
@Saduf2019 - resnet.pb is available here: 
https://drive.google.com/file/d/1RSmk7zdqmHHBjkE-KPY3BNrW5q0Txv-P/view?usp=sharing

**Comment by KarthikDutt** [comment] 2020-12-01 03:28
@Saduf2019 Any update on this?

**Comment by Saduf2019** [comment] 2020-12-04 19:01
i ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/acedfe5ba2b4cb18344a15c069791d52/untitled477.ipynb).

**Comment by KarthikDutt** [comment] 2020-12-04 19:30
You are using the wrong version of the nightly. If you look at the nightly
which I used it’s a different version. Apparently the conversion was
happening fine during the nightlies built for 2.4 but the feature was
either not propagated to RC versions or purposefully left out.  You will be
able to reproduce the error with the tf nightly which I have used.

**Comment by jvishnuvardhan** [comment] 2020-12-05 01:48
@KarthikDutt Agree with you. Conversion is successful with `tf-nightly` but not successful with `TF2.4.0rcx`. I tried with most recent TF version `2.4rc4` but that was also not successful. We will look into it. in the meantime, please use `tf-nightly`. Thanks!

**Comment by karimnosseir** [comment] 2020-12-05 01:57
Is my understanding correct that the issue is fixed in the nightly already ?

**Comment by jvishnuvardhan** [comment] 2020-12-05 02:37
@karimnosseir Yes, Conversion is successful in `tf-nighty` so it is fixed in `tf-nightly`. But, those fixes didn't propagate to `2.4` branch (including 2.4rc3 which was released today). Thanks!

**Comment by KarthikDutt** [comment] 2020-12-09 10:57
@karimnosseir @jvishnuvardhan Will this be part of 2.4?

**Comment by karimnosseir** [comment] 2020-12-09 22:47
@KarthikDutt No AFAIK, they should be part of the next release though 2.5

**Comment by karimnosseir** [comment] 2020-12-09 22:48
I am not sure there is any action on the issue. So closing.

Thanks

**Closed by karimnosseir** 2020-12-09 22:48 UTC
Labels: TF 2.4, TFLiteConverter, type:bug

**Comment by KarthikDutt** [comment] 2021-01-05 12:43
@karimnosseir @jvishnuvardhan The nightly version 2.4.0.dev20200905 is no longer available. It would be great if you can provide a workaround until this is fixed in 2.5. I can build it locally if you redirect me to to the commit which solved this issue.

**Comment by karimnosseir** [comment] 2021-01-06 15:53
@KarthikDutt i don't know which commit resolved your issue. Can't you use the latest nightly instead ? does it matter which nightly you are using ?

**Comment by KarthikDutt** [comment] 2021-01-07 05:08
@karimnosseir I tried with the latest nightly and the bug is not fixed. It was fixed in 2.4.0.dev20200905. As I mentioned before, this fix was somehow not propagated to subsequent nightlies.  Is there any way I can still download and build 2.4.0.dev20200905 on my machine? Any other suggestions on how I can bring in this fix until 2.5 release would be much appreciated.

**Comment by karimnosseir** [comment] 2021-01-07 17:44
@KarthikDutt I tried latest nightly and works fine for me.
Sample of the code

```
from tensorflow.python.util import compat
from tensorflow.python.platform import gfile

graph_def = tf.compat.v1.GraphDef()
with gfile.FastGFile('/content/resnet.pb', 'rb') as f:
  data = compat.as_bytes(f.read())
  graph_def.ParseFromString(data)

concrete_func = wrap_frozen_graph(graph_def, inputs=["input:0"], outputs=["output:0"])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
converter.optimizations = [tf.compat.v1.lite.Optimize.DEFAULT]
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

**Comment by KarthikDutt** [comment] 2021-01-08 04:13
@karimnosseir - You are right. Conversion works fine with the latest nightly on a classification example I had shared before. However, it isn't fixed for a retinaNet model which I have uploaded in the link shared below. Note that the tfnightly version 2.4.0.dev20200905 fixes the issue for retinaNet as well. 
[https://drive.google.com/file/d/1HciakM1T5BIJ_ikyBPeMaGzwih9ZGE1K/view?usp=sharing](url)

To summarize, part of the issue is fixed in latest nightly but still there are elements from 2.4.0.dev20200905 which are not yet propagated to the latest nightly.  

Here's the code that I use to convert the retinanet model. 

`graph_def = tf.compat.v1.GraphDef()
graph_def.ParseFromString(open(r'retinaNet.pb', 'rb').read())
concrete_func = wrap_frozen_graph(graph_def, inputs=["input:0"], outputs=["scores:0","box:0"])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
converter.optimizations = [tf.compat.v1.lite.Optimize.DEFAULT]
#converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()`
