### ISSUE TITLE
'Function could not be transformed and will be executed as-is' while training RNN with Embedding in Keras

### ISSUE THREAD

**Issue by AlxndrMlk** [tensorflow/tensorflow#40192] opened 2020-06-05 12:28 UTC
I got the attached error saying that I should report to "AutoGraph team".

I was training a following toy-model:

```
model = keras.Sequential()

model.add(keras.layers.Embedding(vocab_size, 2, input_length = max_len))
model.add(keras.layers.Flatten())             
model.add(keras.layers.Dense(1, activation = 'sigmoid'))
```

with `tf.keras`, tensorflow version == '2.0.0'.

Operating system = Win10
Python = 3.6

```
Train on 14 samples
Epoch 1/300
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000001F5E571F620> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000001F5E571F620> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
Epoch 2/300
Epoch 3/300
Epoch 4/300
Epoch 5/300
Epoch 6/300
Epoch 7/300
Epoch 8/300
Epoch 9/300
Epoch 10/300
Epoch 11/300
Epoch 12/300
Epoch 13/300
Epoch 14/300
Epoch 15/300
Epoch 16/300
Epoch 17/300
Epoch 18/300
Epoch 19/300
Epoch 20/300
Epoch 21/300
Epoch 22/300
Epoch 23/300
Epoch 24/300
Epoch 25/300
Epoch 26/300
Epoch 27/300
Epoch 28/300
Epoch 29/300
Epoch 30/300
Epoch 31/300
Epoch 32/300
Epoch 33/300
Epoch 34/300
Epoch 35/300
Epoch 36/300
Epoch 37/300
Epoch 38/300
Epoch 39/300
Epoch 40/300
Epoch 41/300
Epoch 42/300
Epoch 43/300
Epoch 44/300
Epoch 45/300
Epoch 46/300
Epoch 47/300
Epoch 48/300
Epoch 49/300
Epoch 50/300
Epoch 51/300
Epoch 52/300
Epoch 53/300
Epoch 54/300
Epoch 55/300
Epoch 56/300
Epoch 57/300
Epoch 58/300
Epoch 59/300
Epoch 60/300
Epoch 61/300
Epoch 62/300
Epoch 63/300
Epoch 64/300
Epoch 65/300
Epoch 66/300
Epoch 67/300
Epoch 68/300
Epoch 69/300
Epoch 70/300
Epoch 71/300
Epoch 72/300
Epoch 73/300
Epoch 74/300
Epoch 75/300
Epoch 76/300
Epoch 77/300
Epoch 78/300
Epoch 79/300
Epoch 80/300
Epoch 81/300
Epoch 82/300
Epoch 83/300
Epoch 84/300
Epoch 85/300
Epoch 86/300
Epoch 87/300
Epoch 88/300
Epoch 89/300
Epoch 90/300
Epoch 91/300
Epoch 92/300
Epoch 93/300
Epoch 94/300
Epoch 95/300
Epoch 96/300
Epoch 97/300
Epoch 98/300
Epoch 99/300
Epoch 100/300
Epoch 101/300
Epoch 102/300
Epoch 103/300
Epoch 104/300
Epoch 105/300
Epoch 106/300
Epoch 107/300
Epoch 108/300
Epoch 109/300
Epoch 110/300
Epoch 111/300
Epoch 112/300
Epoch 113/300
Epoch 114/300
Epoch 115/300
Epoch 116/300
Epoch 117/300
Epoch 118/300
Epoch 119/300
Epoch 120/300
Epoch 121/300
Epoch 122/300
Epoch 123/300
Epoch 124/300
Epoch 125/300
Epoch 126/300
Epoch 127/300
Epoch 128/300
Epoch 129/300
Epoch 130/300
Epoch 131/300
Epoch 132/300
Epoch 133/300
Epoch 134/300
Epoch 135/300
Epoch 136/300
Epoch 137/300
Epoch 138/300
Epoch 139/300
Epoch 140/300
Epoch 141/300
Epoch 142/300
Epoch 143/300
Epoch 144/300
Epoch 145/300
Epoch 146/300
Epoch 147/300
Epoch 148/300
Epoch 149/300
Epoch 150/300
Epoch 151/300
Epoch 152/300
Epoch 153/300
Epoch 154/300
Epoch 155/300
Epoch 156/300
Epoch 157/300
Epoch 158/300
Epoch 159/300
Epoch 160/300
Epoch 161/300
Epoch 162/300
Epoch 163/300
Epoch 164/300
Epoch 165/300
Epoch 166/300
Epoch 167/300
Epoch 168/300
Epoch 169/300
Epoch 170/300
Epoch 171/300
Epoch 172/300
Epoch 173/300
Epoch 174/300
Epoch 175/300
Epoch 176/300
Epoch 177/300
Epoch 178/300
Epoch 179/300
Epoch 180/300
Epoch 181/300
Epoch 182/300
Epoch 183/300
Epoch 184/300
Epoch 185/300
Epoch 186/300
Epoch 187/300
Epoch 188/300
Epoch 189/300
Epoch 190/300
Epoch 191/300
Epoch 192/300
Epoch 193/300
Epoch 194/300
Epoch 195/300
Epoch 196/300
Epoch 197/300
Epoch 198/300
Epoch 199/300
Epoch 200/300
Epoch 201/300
Epoch 202/300
Epoch 203/300
Epoch 204/300
Epoch 205/300
Epoch 206/300
Epoch 207/300
Epoch 208/300
Epoch 209/300
Epoch 210/300
Epoch 211/300
Epoch 212/300
Epoch 213/300
Epoch 214/300
Epoch 215/300
Epoch 216/300
Epoch 217/300
Epoch 218/300
Epoch 219/300
Epoch 220/300
Epoch 221/300
Epoch 222/300
Epoch 223/300
Epoch 224/300
Epoch 225/300
Epoch 226/300
Epoch 227/300
Epoch 228/300
Epoch 229/300
Epoch 230/300
Epoch 231/300
Epoch 232/300
Epoch 233/300
Epoch 234/300
Epoch 235/300
Epoch 236/300
Epoch 237/300
Epoch 238/300
Epoch 239/300
Epoch 240/300
Epoch 241/300
Epoch 242/300
Epoch 243/300
Epoch 244/300
Epoch 245/300
Epoch 246/300
Epoch 247/300
Epoch 248/300
Epoch 249/300
Epoch 250/300
Epoch 251/300
Epoch 252/300
Epoch 253/300
Epoch 254/300
Epoch 255/300
Epoch 256/300
Epoch 257/300
Epoch 258/300
Epoch 259/300
Epoch 260/300
Epoch 261/300
Epoch 262/300
Epoch 263/300
Epoch 264/300
Epoch 265/300
Epoch 266/300
Epoch 267/300
Epoch 268/300
Epoch 269/300
Epoch 270/300
Epoch 271/300
Epoch 272/300
Epoch 273/300
Epoch 274/300
Epoch 275/300
Epoch 276/300
Epoch 277/300
Epoch 278/300
Epoch 279/300
Epoch 280/300
Epoch 281/300
Epoch 282/300
Epoch 283/300
Epoch 284/300
Epoch 285/300
Epoch 286/300
Epoch 287/300
Epoch 288/300
Epoch 289/300
Epoch 290/300
Epoch 291/300
Epoch 292/300
Epoch 293/300
Epoch 294/300
Epoch 295/300
Epoch 296/300
Epoch 297/300
Epoch 298/300
Epoch 299/300
Epoch 300/300

<tensorflow.python.keras.callbacks.History at 0x1f5ebf5b320>
```

**Comment by amahendrakar** [comment] 2020-06-08 04:32
@AlxndrMlk,
While running the code I'm facing an error stating `NameError: name 'vocab_size' is not defined`.
Could you please provide the complete code to reproduce the issue reported here.

Also, as per [#38691](https://github.com/tensorflow/tensorflow/issues/38691), the issue seems to be fixed in  TF-nightly. Could you please upgrade to the latest TF-nightly and let us know if it works. Thanks!

**Comment by AlxndrMlk** [comment] 2020-06-08 05:39
Sure, @amahendrakar, pasting the full code below.

```
import numpy as np
import tensorflow.keras as keras

from tensorflow.keras.preprocessing.sequence import pad_sequences

import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

# Define docs
docs = [
    'Amazing!',
    'Well done!',
    'Great job!',
    'Good job',
    'Nicely done!',
    'Amazing job!',
    'Not bad!',
    'Very poor.',
    'Not well',
    'Not very well written',
    'Purely bad',
    'It\'s not good.',
    'Very badly done',
    'Very bad'
]
    
# Define labels
labels = np.array([1] * 7 + [0] * 7)

# Tokenize the docs
vocab_size = 50

tokenizer = keras.preprocessing.text.Tokenizer(vocab_size, oov_token = '<UNK>')
tokenizer.fit_on_texts(docs)

seqs = tokenizer.texts_to_sequences(docs)

# Pad sequences
max_len = max([len(x) for x in seqs]) + 2

padded_seqs = pad_sequences(seqs, 
                            maxlen  = max_len, 
                            padding = 'post')

model = keras.Sequential()

model.add(keras.layers.Embedding(vocab_size, 32, input_length = max_len))
model.add(keras.layers.Flatten())              # We need to flatten the array before the dense layer
model.add(keras.layers.Dense(32))
model.add(keras.layers.Dropout(.2))
model.add(keras.layers.Dense(32))
model.add(keras.layers.Dropout(.2))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

# Compile the model
model.compile(optimizer = 'adam', 
              loss      = 'binary_crossentropy', 
              metrics   = ['accuracy'])

# Fit the model
model.fit(padded_seqs, labels, epochs = 150, verbose = 0)

# Note that after all the model fits the data and loss goes down as expected:
# plt.plot(model.history.history['accuracy'])
plt.plot(model.history.history['loss'])
```

**Comment by AlxndrMlk** [comment] 2020-06-08 06:04
When it comes to installing the latest nightly, I'll be able to do this later this week.

**Comment by amahendrakar** [comment] 2020-06-15 18:39
> When it comes to installing the latest nightly, I'll be able to do this later this week.

@AlxndrMlk,
Any updates regarding this issue? Thanks!

**Comment by AlxndrMlk** [comment] 2020-06-16 06:14
@amahendrakar - sorry for the delayed response. Not so far, unfortunately. 

I was not able to successfully install and run tf > 2.0 on my machine. I need more time to investigate this issue. I'll try to find a while during the weekend to check it.

**Comment by amahendrakar** [comment] 2020-06-22 19:43
> I was not able to successfully install and run tf > 2.0 on my machine. I need more time to investigate this issue. I'll try to find a while during the weekend to check it.

@AlxndrMlk,
Did you get a chance to look into this over the weekend? Thanks!

**Comment by amahendrakar** [comment] 2020-06-30 08:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-06-30 08:56 UTC
Labels: TF 2.0, comp:autograph, stalled, stat:awaiting response, type:support
