### ISSUE TITLE
custom BLAS

### ISSUE THREAD

**Issue by electricSamarth** [tensorflow/tensorflow#43177] opened 2020-09-12 15:45 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No):Yes (WOULD LOVE IT!)

**Describe the feature and the current behavior/state.**
After a good amount of profiling on some of the codes [here](https://github.com/dragen1860/TensorFlow-2.x-Tutorials). I found out that TensorFlow uses 'mkldnn_sgemm' and Tensorflow with "MKL-DNN support" (--config=mkl during build time) uses 'mkldnn::impl::cpu::avx_gemm_f32::sgemm_nocopy_driver' for **MATRIX MULTIPLICATION**. What I wanted was that somehow every time Tensorflow does matrix multiplication we make TensorFlow do these matmul operations with user defined functions. Maybe with the help of .so file?  

**Will this change the current api? How?**
NO

**Who will benefit with this feature?**
researchers and engineers who are working on TensorFlow from a systems point of view 

**Any Other info.**

**Comment by agramesh1** [comment] 2020-10-27 02:51
@electricSamarth As I mentioned in your other issue you filed, we stopped supporting this in 2.4.  For 2.3 you can still do this by modifying https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/core/kernels/mkl_matmul_op.cc#L28  and just for this file undef ENABLE_MKLDNN_V1 .  This will make TF call to cblas gemm and you can provide own cblas.

**Comment by electricSamarth** [comment] 2020-10-27 07:14
Yes I realised, the other way is to just rename my matmul function to dnnl_sgemm and pack it into a shared object and the LD_PRELOAD it, so no changes on the TF side will be required!

**Comment by electricSamarth** [comment] 2020-10-27 07:14
Thanks @agramesh1

**Comment by NeoZhangJianyu** [comment] 2020-10-28 08:02
@electricSamarth 
If the issue is fixed, could you close it?

**Comment by electricSamarth** [comment] 2020-10-28 08:31
yes, sure thing!

**Closed** 2020-10-28 08:31 UTC
Labels: comp:mkl, stat:awaiting tensorflower, type:feature
