### ISSUE TITLE
ResNet model in keras and tf.keras give different output for the same image

### ISSUE THREAD

**Issue by NagabhushanSN95** [tensorflow/tensorflow#35975] opened 2020-01-17 08:27 UTC
For a given image, I'm extracting ResNet features i.e. after all conv layers and global max pooling, which gives a 2048 length vector per image. 

Earlier, I was using `keras==2.3.1` with backend `tensorflow==1.13.1`. Now, I've shifted to `tensorflow==2.0.0` since keras has been merged with tensorflow. I replaced my code with `tf.keras` instead of `keras`.

But now the features extracted are not the same as the features extracted earlier. ResNet is a model which is independent of tensorflow/keras or even pytorch for that matter. It's functionality is predefined. Why is this difference occuring? Are there any parameters that can be tweaked to get the same functionality?\

```
    from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
    resnet_model = ResNet50(include_top=False)
```

**Comment by oanush** [comment] 2020-01-20 09:09
@NagabhushanSN95 ,
You can refer this [SO link ](https://stackoverflow.com/questions/59783361/resnet-model-in-keras-and-tf-keras-give-different-output-for-the-same-image)for the solution. Please feel free to close the issue if its resolved.Thanks!

**Comment by NagabhushanSN95** [comment] 2020-01-20 10:09
Thanks. Would it be possible to add a parameter to load original ResNet weights?

**Comment by Saduf2019** [comment] 2020-02-26 10:48
@NagabhushanSN95 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by NagabhushanSN95** [comment] 2020-02-27 22:31
No. I'm asking for a feature request.
Is it possible to provide a flag or parameter to make ResNet model use the weights from original ResNet model?

**Comment by ymodak** [comment] 2020-04-23 06:44
Is this still an issue? Can you try with latest version of tensorflow keras? Thanks!

**Closed** 2020-04-24 14:19 UTC
Labels: TF 1.13, comp:keras, stat:awaiting response, type:support
