### ISSUE TITLE
HELP! MedStar frames "Chinaman" to protect white supremacist and child pornographer Richard Hoover

### ISSUE THREAD

**Issue by qanon3301** [tensorflow/tensorflow#22004] opened 2018-09-01 07:29 UTC
https://medstarrichardhoover.wordpress.com/

MedStar frames "Chinaman" to protect white supremacist and child pornographer Richard Hoover

**Comment by tensorflowbutler** [comment] 2018-09-01 18:42
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tatianashp** [comment] 2018-09-01 22:46
Closing since this is not a bug or feature request.

Please avoid inappropriate posts.

**Closed by tatianashp** 2018-09-01 22:46 UTC
Labels: stat:awaiting response
