### ISSUE TITLE
Python import failure

### ISSUE THREAD

**Issue by IanSMoyes** [tensorflow/tensorflow#47146] opened 2021-02-14 16:50 UTC
**System information**
- OS Platform and Distribution (Linux Ubuntu 20 latest update):
- Mobile device ()Starlabs Star Lite laptop with 8Gb of RAM 113Gb of SSD space:
- TensorFlow installed from (pip install tensorflow==2.4.1):
- TensorFlow version: see above
- Python version: Python 3.8.5 (/usr/bin/python3)
- Installed using virtualenv? pip? conda?: See above
- Bazel version (if compiling from source): NA NA
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Dunno
- GPU model and memory: (description: VGA compatible controller
       product: UHD Graphics 605
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 03
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:132 memory:a0000000-a0ffffff memory:90000000-9fffffff ioport:f000(size=64) memory:c0000-dffff)

**Describe the problem**
when I import tensorflow into the Thonny shell I get:

Backend terminated or disconnected.Fatal Python error: Illegal instruction

Current thread 0x00007f30949d8740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1101 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "<pyshell>", line 1 in <module>
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1272 in _execute_prepared_user_code
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1200 in wrapper
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1213 in wrapper
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1259 in execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 814 in _execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 444 in _cmd_execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 204 in handle_command
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 146 in mainloop
  File "/usr/lib/python3/dist-packages/thonny/backend_launcher.py", line 87 in <module> Use 'Stop/Restart' to restart.Backend terminated or disconnected.Fatal Python error: Illegal instruction

Current thread 0x00007f30949d8740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1101 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "/home/ian/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 285 in _custom_import
  File "<pyshell>", line 1 in <module>
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1272 in _execute_prepared_user_code
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1200 in wrapper
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1213 in wrapper
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1259 in execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 814 in _execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 444 in _cmd_execute_source
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 204 in handle_command
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 146 in mainloop
  File "/usr/lib/python3/dist-packages/thonny/backend_launcher.py", line 87 in <module> Use 'Stop/Restart' to restart.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow==2.4.1 # into the terminal
# followed by

import tensorflow # into Thonny's shell

# the error appears in the shell

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
NA

**Comment by amahendrakar** [comment] 2021-02-15 06:24
@IanSMoyes,
Could you please share the make and model of the CPU on your machine and output of the `cat /proc/cpuinfo` command with us.

Starting with v1.6, TensorFlow binaries use AVX instructions which may not run on older CPUs. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) for installing TensorFlow. Also check similar issues [#33038](https://github.com/tensorflow/tensorflow/issues/33038#issuecomment-538470776), [#29788](https://github.com/tensorflow/tensorflow/issues/29788#issuecomment-505571104) for reference.

Thanks!

**Comment by IanSMoyes** [comment] 2021-02-15 10:43
Hello,
I'm VERY grateful for your response this time. Thank you.

Here is the output from cat /proc/cpuinfo which I included with my original
question, the one that was ignored and closed.

processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 122
model name : Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
stepping : 1
microcode : 0x32
cpu MHz : 1266.027
cache size : 4096 KB
physical id : 0
siblings : 4
core id : 0
cpu cores : 4
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 24
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb
rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe
popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch
cpuid_fault cat_l2 pti cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a
rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves
dtherm ida arat pln pts umip rdpid md_clear arch_capabilities
vmx flags : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad
ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid
unrestricted_guest vapic_reg vid ple shadow_vmcs ept_mode_based_exec
tsc_scaling
bugs : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips : 2188.80
clflush size : 64
cache_alignment : 64
address sizes : 39 bits physical, 48 bits virtual
power management:

processor : 1
vendor_id : GenuineIntel
cpu family : 6
model : 122
model name : Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
stepping : 1
microcode : 0x32
cpu MHz : 1321.060
cache size : 4096 KB
physical id : 0
siblings : 4
core id : 1
cpu cores : 4
apicid : 2
initial apicid : 2
fpu : yes
fpu_exception : yes
cpuid level : 24
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb
rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe
popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch
cpuid_fault cat_l2 pti cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a
rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves
dtherm ida arat pln pts umip rdpid md_clear arch_capabilities
vmx flags : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad
ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid
unrestricted_guest vapic_reg vid ple shadow_vmcs ept_mode_based_exec
tsc_scaling
bugs : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips : 2188.80
clflush size : 64
cache_alignment : 64
address sizes : 39 bits physical, 48 bits virtual
power management:

processor : 2
vendor_id : GenuineIntel
cpu family : 6
model : 122
model name : Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
stepping : 1
microcode : 0x32
cpu MHz : 1222.266
cache size : 4096 KB
physical id : 0
siblings : 4
core id : 2
cpu cores : 4
apicid : 4
initial apicid : 4
fpu : yes
fpu_exception : yes
cpuid level : 24
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb
rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe
popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch
cpuid_fault cat_l2 pti cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a
rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves
dtherm ida arat pln pts umip rdpid md_clear arch_capabilities
vmx flags : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad
ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid
unrestricted_guest vapic_reg vid ple shadow_vmcs ept_mode_based_exec
tsc_scaling
bugs : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips : 2188.80
clflush size : 64
cache_alignment : 64
address sizes : 39 bits physical, 48 bits virtual
power management:

processor : 3
vendor_id : GenuineIntel
cpu family : 6
model : 122
model name : Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz
stepping : 1
microcode : 0x32
cpu MHz : 1070.831
cache size : 4096 KB
physical id : 0
siblings : 4
core id : 3
cpu cores : 4
apicid : 6
initial apicid : 6
fpu : yes
fpu_exception : yes
cpuid level : 24
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb
rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology
nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor
ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe
popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch
cpuid_fault cat_l2 pti cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow
vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a
rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves
dtherm ida arat pln pts umip rdpid md_clear arch_capabilities
vmx flags : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad
ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid
unrestricted_guest vapic_reg vid ple shadow_vmcs ept_mode_based_exec
tsc_scaling
bugs : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips : 2188.80
clflush size : 64
cache_alignment : 64
address sizes : 39 bits physical, 48 bits virtual
power management:

**Comment by mihaimaruseac** [comment] 2021-02-15 18:06
Your CPU does not support AVX. You have to compile from source or use a newer machine / a VM in the cloud.

**Comment by IanSMoyes** [comment] 2021-02-18 02:07
Thank you for that helpful information. Can you please post a link to what I have to download and how to install it?

**Comment by amahendrakar** [comment] 2021-02-18 07:30
@IanSMoyes,
Please follow [this guide](https://www.tensorflow.org/install/source) to build TensorFlow from source on Linux machines.

Make sure you have all the required dependencies installed as mentioned in the [tested build configurations](https://www.tensorflow.org/install/source#linux). Thanks!

**Comment by mihaimaruseac** [comment] 2021-02-18 21:10
Closing as duplicate of  #33038, #29788 and several others

**Closed by mihaimaruseac** 2021-02-18 21:10 UTC
Labels: TF 2.4, stat:awaiting response, subtype: ubuntu/linux, type:build/install
