### ISSUE TITLE
Tflite Op missing:Stack

### ISSUE THREAD

**Issue by Archernarkiu** [tensorflow/tensorflow#24888] opened 2019-01-14 06:58 UTC
**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04):
- TensorFlow installed from ( pip ):
- TensorFlow version ( 1.10 ):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.contrib.lite.toco_convert(). Here is a list of operators for which  you will need custom implementations: Stack.

```

**Comment by Archernarkiu** [comment] 2019-01-14 08:11
As far as I know, the Op 'Stack' is closely related to Op 'Strided_slice', and both of them seems easy to be implemented. 
So I wonder why these Ops weren not supported by the standard TensorFlow Lite runtime.

**Comment by jvishnuvardhan** [comment] 2019-01-14 15:05
@Archernarkiu Could you provide an example code to reproduce the error? That will help us to find the root-cause of the issue? Thanks!

**Comment by Archernarkiu** [comment] 2019-01-15 06:41
@jvishnuvardhan Thanks for your help, and my code shows below:

>  resize_image(image, size,method=tf.image.ResizeMethod.BILINEAR,align_corners=False):
    """Resize an image and bounding boxes. """
    # Resize image.
    with tf.name_scope('resize_image'):
        height, width, channels = _ImageDimensions(image)
        image = tf.expand_dims(image, 0)
        image = tf.image.resize_images(image, size,method, align_corners)
        image = tf.reshape(**image, tf.stack([size[0], size[1], channels])**)
        return image

The bold code is an example of calling 'stack' Op explicitly. However, in most cases, when I defined my model, some Op like 'strided_slice' and 'stack' will be add into GraphDef automatically.

**Comment by Archernarkiu** [comment] 2019-01-16 09:06
@jvishnuvardhan I thought it over for a long time, and then I realized maybe this is quite an important issue. As far as I can see, the models provided officially by TFLITE , e.g. mobilenet_v1, are of linear shape and used for classification. But for other models, which have skip connections, e.g. pixellink and U-net,  Ops like 'strided_slice' or 'stack' seems inevitable. So I guess once solved this problem, TFLITE would be more widely applied.

**Comment by tofulawrence** [comment] 2019-02-08 00:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2019-02-08 00:32 UTC
Labels: comp:lite, stat:awaiting tensorflower, type:bug/performance
