### ISSUE TITLE
installing tensorflow to a local folder results in import error with realtive paths

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorflow#13126] opened 2017-09-18 13:10 UTC
this is on linux with python 3.6.2 and tf 1.3
i install tensorflow into a folder named 'site-packages' inside my project. i then add it to the path with a relative reference. works fine when path is absolute

pip install tensorflow -t site-packages
python
import sys
sys.path.insert(1,"site-packages") # will fail
#sys.path.insert(1,"/home/absolute_path/site-packages") #works
from tensorflow.contrib.framework.python.ops.checkpoint_ops import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
    from tensorflow.contrib.framework.python.ops.checkpoint_ops import *
  File "site-packages/tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_checkpoint_ops.so"))
  File "site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: site-packages/tensorflow/contrib/util/site-packages/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so: cannot open shared object file: No such file or directory

**Comment by printdhruv** [comment] 2017-09-18 20:29
@eyaler I guess you have to mention absolute_path not the other way around? By the way,I couldn't understand your concern :)

**Comment by eyaler** [comment] 2017-09-18 20:39
@printdhruv you understood correctly. this is a bug happening only with this module. see the created path: site-packages/tensorflow/contrib/util/site-packages/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so

**Comment by printdhruv** [comment] 2017-09-18 20:49
@eyaler Can you try to print `print sys.path` too see all path information?

**Comment by eyaler** [comment] 2017-09-18 20:55
@printdhruv i checked the path and its find. this contrived path name is created by tf

**Comment by printdhruv** [comment] 2017-09-18 21:02
I guess this [link](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s) will help you to understand the differences among using path in a linux.

**Comment by aselle** [comment] 2017-09-24 23:35
I believe this is working as intended. I don't see a compelling reason to add relative paths to sys.path or that it is supported by Python. If you want to make it agile to being moved around, just make a shell script to wrap python that sets up PYTHONPATH before it invokes python.

**Comment by eyaler** [comment] 2017-09-25 07:57
this breaks the principal of least surprise. if relative paths are not supported, to the very least this should be documented.

**Comment by aselle** [comment] 2017-10-07 00:57
Backtracking, it is probably possible to make this work, but it will require changing how .dso's are found to be more robust. (I.e. right now we use resource_loader.get_path_to_datafile which uses some absolute path).

**Comment by aselle** [comment] 2017-10-07 00:57
@allenlavoie, do you have any inkling to fix this problem?

**Comment by tensorflowbutler** [comment] 2017-12-20 01:07
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:14
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by allenlavoie** [comment] 2018-01-03 20:26
Not sure how I missed this. I think you nailed it @aselle. Given that this is a rather niche use, I'd say this is contributions welcome.

**Comment by mohantym** [comment] 2022-03-17 02:07
Hi @eyaler ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more.  But I executed steps mentioned in the template, and was able to  execute this command `from tensorflow import  *`.  Closing this issue as it has been resolved now in 2.8 version. Thanks!

**Closed by mohantym** 2022-03-17 02:07 UTC
Labels: stat:contributions welcome
