### ISSUE TITLE
RuntimeError: Graph is finalized and cannot be modified.

### ISSUE THREAD

**Issue by amelroua** [tensorflow/tensorflow#26171] opened 2019-02-27 12:43 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):n/a
- TensorFlow version (use command below):1.12.0
- Python version:2.7.x
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):(Ubuntu 5.4.0-6ubuntu1~16.04.11)5.4.0
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

**Describe the problem**
I use tfrecords file to train a stacked autoencoder. I want to train the encoding layer for 1000 steps. I tried to create batches from features and labels and use them to train my network.  However, when I run my code I get an error (RuntimeError: Graph is finalized and cannot be modified.) indicating that the problem comes from the following function: 

     def train_layer(output_layer, layer_loss,optimizer):
     """Train each encoding layer for 1000 steps"""
     layer_name = output_layer.name.split('/')[0]
     print('Pretraining {}'.format(layer_name))
     num_steps = 1000
      step=1
     features, labels=train_input_fn()
     input_l = tf.reshape(features, [-1, FLAGS.image_rows, FLAGS.image_cols, 1])
      while step <= num_steps:
     instance_batch, label_batch = tf.train.shuffle_batch([input_l], batch_size=5, capacity=200, min_after_dequeue=100)
    _out_layer, _layer_loss,_ = sess.run([output_layer, layer_loss, optimizer],
     feed_dict ={features:instance_batch,labels:label_batch})
     #print(_layer_loss)
     step += 1
     print('layer finished')`

**Comment by amelroua** [comment] 2019-02-27 12:49
I have a tfrecords file from which I am looking to create batches of data. I want to train the encoding layer of my model many steps while calling the batches. For this purpose I used the below code to create batches and get the next batch:


`def write_and_encode(data_list, tfrecord_filename):
    writer = tf.python_io.TFRecordWriter(tfrecord_filename)
    for label, data_matrix in data_list:
        example = tf.train.Example(features=tf.train.Features(
            feature={
                "label": tf.train.Feature(int64_list=tf.train.Int64List(value=[label])),
                "data_raw": tf.train.Feature(bytes_list=tf.train.BytesList(value=[data_matrix.tostring()]))
            }
        ))
        writer.write(example.SerializeToString())

    writer.close()


def read_and_decode(tfrecord_filename):
    reader = tf.TFRecordReader()
    filename_queue = tf.train.string_input_producer([tfrecord_filename],)
    _, serialized_example = reader.read(filename_queue)
    feature = tf.parse_single_example(serialized_example,
                                      features={
                                          "label": tf.FixedLenFeature([], tf.int64),
                                          "data_raw": tf.FixedLenFeature([], tf.string)
                                      })
    data = tf.decode_raw(feature["data_raw"], tf.float64)
    data = tf.reshape(data, [FLAGS.image_rows, FLAGS.image_cols])
    return data, feature["label"]
def train_input_fn():

    tfrecord_file = "../resources/train_tfrecord"  
    dataset = tf.data.TFRecordDataset(tfrecord_file)
    dataset = dataset.map(parser)

    train_dataset = dataset.repeat(FLAGS.num_epochs).batch(FLAGS.batch_size)
    train_iterator = train_dataset.make_one_shot_iterator()

    features, labels = train_iterator.get_next()
    return features, labels

def parser(record_line):

    features = {
        "label": tf.FixedLenFeature([], tf.int64),
        "data_raw": tf.FixedLenFeature([], tf.string)
    }
    parsed = tf.parse_single_example(record_line, features=features)
    label = tf.cast(parsed["label"], tf.int32) - 1  
    data = tf.decode_raw(parsed["data_raw"], tf.float64)
    data = tf.reshape(data, [FLAGS.image_rows, FLAGS.image_cols])
    data = tf.cast(data, tf.float32)
    return data, label`

To train the encoding layer of an autoencoder, I perfrom as follows:
`def train_layer(output_layer, layer_loss,optimizer):
    """Train each encoding layer for 1000 steps"""
    layer_name = output_layer.name.split('/')[0]
    print('Pretraining {}'.format(layer_name))
    num_steps = 1000
    step=1
    features, labels=train_input_fn()
    input_l = tf.reshape(features, [-1, FLAGS.image_rows, FLAGS.image_cols, 1])
    while step <= num_steps:

         instance_batch, label_batch = tf.train.shuffle_batch([input_l], batch_size=5, capacity=200, min_after_dequeue=100)

    _out_layer, _layer_loss,_ = sess.run([output_layer, layer_loss, optimizer],
      feed_dict ={features:instance_batch,labels:label_batch})

    #print(_layer_loss)
    step += 1
    print('layer finished')`

For the configuration of the Monitored Training Session, I implement it as follows: 

`"""Use a MonitoredTrainingSession for running the computations.  It makes running on distributed systems
possible, handles checkpoints, saving summaries, and restoring from crashes easy."""

#create hooks to pass to the session.  These can be used for adding additional calculations, loggin, etc.
#This hook simply tells the session how many steps to run
hooks=[tf.train.StopAtStepHook(last_step=10000)]

#This command collects all summary ops that have been added to the graph and prepares them to run in the next session
tf.summary.merge_all()
logs_dir = 'logs'
with tf.train.MonitoredTrainingSession(hooks=hooks, checkpoint_dir=logs_dir,save_summaries_steps=100) as sess:

    start_time = time.time()

    """First train each layer one at a time, freezing weights from previous layers.
    This was accomplished by declaring which variables to update when each layer optimizer was defined."""
    for layer_dict in model_layers:
        output_layer = layer_dict['output_layer']
        layer_loss = layer_dict['layer_loss']
        optimizer = layer_dict['optimizer']
        train_layer( output_layer, layer_loss, optimizer)

 #Now train the whole network for classification allowing all weights to change.
    while not sess.should_stop():
        _y, _cross_entropy, _net_op, _accuracy = sess.run([y, cross_entropy, net_op, accuracy], feed_dict={x:instance_batch,y_labels:label_batch})
print(_accuracy)
print('Training complete\n')`

WHen I run my code, I get an error:

> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2919, in _check_not_finalized
    raise RuntimeError("Graph is finalized and cannot be modified.")
RuntimeError: Graph is finalized and cannot be modified.

The source of the problem is the Train_layer:

> Pretraining layer_0
> Traceback (most recent call last):
>   File "aut.py", line 222, in <module>
>     train_layer( output_layer, layer_loss, optimizer)
>   File "aut.py", line 111, in train_layer
>     features, labels=train_input_fn()
>   File "aut.py", line 67, in train_input_fn
>     dataset = tf.data.TFRecordDataset(tfrecord_

file)

**Comment by jvishnuvardhan** [comment] 2019-02-28 00:42
@amelroua 
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-03-15 12:54
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-03-15 13:08
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-15 13:08 UTC
Labels: comp:data, stat:awaiting response, type:bug/performance

**Comment by sinano1107** [comment] 2021-02-04 11:40
This problem still exists.
I need some help.

Error when entering a number greater than 3 for parameter n_classes in tf.estimator.DNNClassifier

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-83-00f0f6fad3ff> in <module>
      1 tf.Graph().finalize()
      2 ## 手順3:Estimatorをインスタンス化
----> 3 dnn_classifier = tf.estimator.DNNClassifier(
      4     feature_columns=[image_feature_column],
      5     hidden_units=[32, 16],

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py in __init__(self, hidden_units, feature_columns, model_dir, n_classes, weight_column, label_vocabulary, optimizer, activation_fn, dropout, config, warm_start_from, loss_reduction, batch_norm)
    739       batch_norm: Whether to use batch normalization after each hidden layer.
    740     """
--> 741     head = head_utils.binary_or_multi_class_head(
    742         n_classes,
    743         weight_column=weight_column,

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/head_utils.py in binary_or_multi_class_head(n_classes, weight_column, label_vocabulary, loss_reduction)
     59         loss_reduction=loss_reduction)
     60   else:
---> 61     head = multi_class_head.MultiClassHead(
     62         n_classes,
     63         weight_column=weight_column,

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/multi_class_head.py in __init__(self, n_classes, weight_column, label_vocabulary, loss_reduction, loss_fn, name)
    156     if loss_fn:
    157       base_head.validate_loss_fn_args(loss_fn)
--> 158     self._n_classes = base_head.validate_n_classes(n_classes)
    159     self._weight_column = weight_column
    160     self._label_vocabulary = label_vocabulary

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/head/base_head.py in validate_n_classes(n_classes)
    696     raise ValueError('n_classes must be > 2: %s.' % n_classes)
    697 
--> 698   n_classes_as_tensor = ops.convert_to_tensor(n_classes)
    699   assert_n_classes = tf.compat.v1.debugging.assert_greater(
    700       n_classes_as_tensor, 2, message='n_classes must be greater than 2')

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py in wrapped(*args, **kwargs)
    161         with Trace(trace_name, **trace_kwargs):
    162           return func(*args, **kwargs)
--> 163       return func(*args, **kwargs)
    164 
    165     return wrapped

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1538 
   1539     if ret is None:
-> 1540       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1541 
   1542     if ret is NotImplemented:

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
     50 def _default_conversion_function(value, dtype, name, as_ref):
     51   del as_ref  # Unused.
---> 52   return constant_op.constant(value, dtype, name=name)
     53 
     54 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name)
    262     ValueError: if called on a symbolic tensor.
    263   """
--> 264   return _constant_impl(value, dtype, shape, name, verify_shape=False,
    265                         allow_broadcast=True)
    266 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    284   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    285   attrs = {"value": tensor_value, "dtype": dtype_value}
--> 286   const_tensor = g._create_op_internal(  # pylint: disable=protected-access
    287       "Const", [], [dtype_value.type], attrs=attrs, name=name).outputs[0]
    288 

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in _create_op_internal(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_device)
   3509       An `Operation` object.
   3510     """
-> 3511     self._check_not_finalized()
   3512     if name is None:
   3513       name = op_type

~/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in _check_not_finalized(self)
   3099     """
   3100     if self._finalized:
-> 3101       raise RuntimeError("Graph is finalized and cannot be modified.")
   3102 
   3103   def _add_op(self, op, op_name):

RuntimeError: Graph is finalized and cannot be modified.
```

**Comment by sinano1107** [comment] 2021-02-04 11:40
version is 2.4.1

**Comment by jvishnuvardhan** [comment] 2021-02-04 22:24
@sinano1107 Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!
