### ISSUE TITLE
Densnet169 produces memory leak in TF2.0 but works well with latest TF1

### ISSUE THREAD

**Issue by vk1996** [tensorflow/tensorflow#30443] opened 2019-07-06 04:38 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview
- Python version:3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: colab version
- GPU model and memory: colab version

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Densnet169 crashes with memory error even with datagenerator and a batchsize of 8.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2019-07-08 10:25
Can you please elaborate the issue .In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by vk1996** [comment] 2019-07-08 12:22
When using this version of tf 
$ pip install tf-nightly-gpu-2.0-preview
'''
model=tf.keras.applications.densenet.DenseNet169(include_top=True, weights='imagenet', input_tensor=None, input_shape=(224,224,3), pooling=None, classes=1000)

history = model.fit_generator(
      train_data_generator,
      steps_per_epoch=train_count/batch_size ,
      epochs=300,
      validation_data=val_data_generator,
      validation_steps=val_count/batch_size,
      verbose=1,callbacks=callbacks,initial_epoch=initial_epoch)
'''
In the above snippet, the first epoch takes a long time to start and results in memory error restarting the kernel. I use tf.keras image datagenerator with minimum batch size  of 8 and size(224,224,3) . 
RAM- 16GB
GPU- 12GB

**Comment by ravikyram** [comment] 2019-07-09 06:39
I am not able to reproduce the issue with the provided code(train_data_generator is not defined).Can you please provide full code snippet to reproduce the issue.Thanks!

**Comment by ravikyram** [comment] 2019-07-16 05:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-16 05:45 UTC
Labels: comp:keras, stat:awaiting response, type:support
