### ISSUE TITLE
Class_weight with tf.dataset as input to model.fit will throw an error

### ISSUE THREAD

**Issue by was84san** [tensorflow/tensorflow#22275] opened 2018-09-14 12:24 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No Mobile device
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.10
- **Python version**:2.7
- **Bazel version (if compiling from source)**: ---
- **GCC/Compiler version (if compiling from source)**:---
- **CUDA/cuDNN version**: cuda-8.0
- **GPU model and memory**: (Titan X and GeForce GTX 1080 )
- **Exact command to reproduce**:

### Describe the problem
I am using` tf.keras `in order to be able to feed the train_data using` tf.dataset` API through model.fit directly. It works fine whenever you didn't pass `class_weight`, but if you pass dict of class_weights, it will throw the following error :

`AxisError: axis 1 is out of bounds for array of dimension 1
`

When I debug the error , I found the error happened exactly at line 531 : 
```
> /usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_utils.py(530)standardize_weights()
    528       raise ValueError('`class_weight` not supported for '
    529                        '3+ dimensional targets.')
    530     if y.shape[1] > 1:
-->  531       y_classes = np.argmax(y, axis=1)
    532     elif y.shape[1] == 1:

```
The dimension of y is `TensorShape([Dimension(None), Dimension(8)])
`
So` y.shape[1] > 1` , but the problem y is a **tensor** now not an **numpy array,** that is why it throws the previous error.

So is there any solution to this situation? 

### **EDIT**: Adding sample code to reproduce the error.

```
import os, sys, logging
import numpy as np
import tensorflow as tf
import itertools as itt
logging.basicConfig(level=logging.INFO)


def _int64_feature(value):
  return tf.train.Feature(int64_list= tf.train.Int64List(value= [value]))

def _bytes_feature(value):
  return tf.train.Feature(bytes_list= tf.train.BytesList(value= [value]))

def _float32_feature(value):
  return tf.train.Feature(float_list= tf.train.FloatList(value= [value]))

def tf_records_creating(tfrecord_file):
    logging.info('Creating random tfrecord files for 100 sample')

    labels = np.random.uniform(0, num_classes, total_train).astype(np.int32)
    data = np.random.uniform(0, 255, total_train*224*224*3).reshape(total_train, 224, 224, 3).astype(np.int32)

    writer = tf.python_io.TFRecordWriter(tfrecord_file)

    for idx, (image, label) in enumerate(itt.izip(data, labels)):
        image = image.tostring()
        example = tf.train.Example(features=tf.train.Features(feature={
            'label': _int64_feature(int(label)),
            'image': _bytes_feature(image),
        }))
        writer.write(example.SerializeToString())
    writer.close()
    return

def decode(serialized_example):
  features = tf.parse_single_example(
      serialized_example,
      features={
          'image': tf.FixedLenFeature([], tf.string),
          'label': tf.FixedLenFeature([], tf.int64),
      })

  image = tf.decode_raw(features['image'], tf.float32)
  image.set_shape([224*224*3])

  image=tf.reshape(image, (224,224,3))

  label = tf.cast(features['label'], tf.int32)
  label_categorical = tf.one_hot(label,depth= num_classes, on_value=1,off_value=0,dtype=tf.int32,)
  label_categorical = tf.reshape(label_categorical, [num_classes])
  label_categorical.set_shape([num_classes])

  return image, label_categorical

def data_preparing(tfrecord_file):

    logging.info('Preparing the Training tf.dataset ')
    training_files = [tfrecord_file]
    dataset_train = tf.data.TFRecordDataset(training_files, num_parallel_reads=1)
    dataset_train = dataset_train.apply(tf.contrib.data.shuffle_and_repeat(buffer_size=4 * batch_size))
    dataset_train = dataset_train.map(decode, num_parallel_calls=1)  
    dataset_train = dataset_train.batch(batch_size)
    dataset_train = dataset_train.prefetch(tf.contrib.data.AUTOTUNE)
    return dataset_train

def train_model(tfrecord_file):

    base_model = tf.keras.applications.VGG16(include_top=False, weights='imagenet',
                                                 input_shape=(224, 224, 3), pooling='avg')

    for layer in base_model.layers:
        layer.trainable = False

    logging.info('Building Our Classifier')
    x = base_model.output
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(512, activation='relu')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Dense(num_classes, activation='sigmoid')(x)

    model = tf.keras.models.Model(inputs=base_model.input, outputs=x)
    model.summary()
    opt = tf.keras.optimizers.Adam(lr=0.001)
    model.compile(loss='categorical_crossentropy',
                  optimizer=opt, metrics=['accuracy'])
    dataset_train = data_preparing(tfrecord_file=tfrecord_file)

    weighted_array_train= np.array([0.01557266,0.00867447,0.04579864,0.08275284,0.18281397,
       0.30659676, 0.04686068, 0.31092999])
    class_weight_dict = dict(enumerate(weighted_array_train))

    if using_class_weight == True:
        model.fit(x=dataset_train, epochs=epochs, verbose=1,class_weight = class_weight_dict,
              steps_per_epoch=int(np.ceil(total_train / batch_size)))
    else:
        model.fit(x=dataset_train, epochs=epochs, verbose=1,
              steps_per_epoch=int(np.ceil(total_train / batch_size)))
    return

if __name__== '__main__':

    total_train = 100.
    num_classes= 8
    batch_size = 10
    epochs = 100

    #TODO (1) :Set the path to tfrecord file that we will create it.
    tfrecord_file = '~/train.tfrecords'
    tf_records_creating(tfrecord_file)                # Implement this only one time

    using_class_weight= False                         # if you set this to True, you will produce the error
    train_model(tfrecord_file)
```

**Comment by facaiy** [comment] 2018-09-15 14:08
@fchollet @mrry Would you mind taking a look?

**Comment by yongtang** [comment] 2018-09-16 16:04
@was84san I am not able to reproduce the scenario, as in case a `tf.dataset` is used, `y` is not specified in `model.fit`.

Can you provide a minimal example that trigger the error you encounter?

**Comment by was84san** [comment] 2018-09-16 17:48
I know y is not specified, but then it will be extracted trough `next element` as shown below:

`> /home/wassan/tensorflow/venv/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py(755)_standardize_user_data()
    753       try:
    754         if is_x_iterator:
--> 755           next_element = self._get_iterator_get_next_tensors(x)
    756         else:
    757           next_element = x.get_next()

ipdb> n
> /home/wassan/tensorflow/venv/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py(763)_standardize_user_data()
    761                            'required number of samples.')
    762 
--> 763       if not isinstance(next_element, (list, tuple)) or len(next_element) != 2:
    764         raise ValueError('Please provide data as a list or tuple of 2 elements '
    765                          ' - input and target pair. Received %s' % next_element)

ipdb> n
> /home/wassan/tensorflow/venv/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py(766)_standardize_user_data()
    764         raise ValueError('Please provide data as a list or tuple of 2 elements '
    765                          ' - input and target pair. Received %s' % next_element)
--> 766       x, y = next_element
    767 
    768     # First, we build/compile the model on the fly if necessary.

`

**Comment by yongtang** [comment] 2018-09-16 19:27
@was84san Any chance you could provide a sample tfrecord file and a "complete" reproducible sample code (from first line of `import tensorflow as tf` to last line of `model.fit`)?

Many parameters in your code snippet are missing.

**Comment by was84san** [comment] 2018-09-16 22:09
@yongtang I edited the code, you can run it now.

**Comment by was84san** [comment] 2018-09-17 01:30
` using_class_weight= True                        # if you set this to True, you will produce the error
`

**Comment by mrry** [comment] 2018-09-17 14:27
@pavithrasv Could you please take a look at this issue? Thanks!

**Comment by was84san** [comment] 2018-09-19 16:13
The only solution for me if this is not fixed, is to return back to use fit_generator instead and feed my data from own generator, and this one is much slower than model.fit. Like 10 times slower. I wish that can anyone just justify the condition in line 531 to make it work for both tensor and bumpy array.

**Comment by was84san** [comment] 2018-10-03 21:42
Is there any update?

**Comment by tensorflowbutler** [comment] 2018-10-18 18:57
Nagging Assignee @pavithrasv: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by was84san** [comment] 2018-10-19 04:33
anyone can reproduce the error?

**Comment by yongtang** [comment] 2018-10-19 14:52
@was84san I could reproduce the error. I also could see where the issue is. However the fix might not be so straightforward so still think the best way to address it.

**Comment by yongtang** [comment] 2018-10-30 17:35
Added a PR #23381 for the fix. Please take a look.

**Comment by was84san** [comment] 2018-11-04 21:14
It is the right fix. Thank you. When the new changes are going to be merged? Sorry, but I am not familiar about how this work , I mean when I am going to see the fix, like in the new version of tensor flow?

**Comment by yongtang** [comment] 2018-11-05 02:47
@was84san The PR #23381 is pending review. If the PR is approved it will be merged and picked up in the new version of TensorFlow.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:49
Nagging Assignee @pavithrasv: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by was84san** [comment] 2018-12-11 19:36
@yongtang Is there any possibility that this issue being reviewed soon :( . I really need to use it before my deadline.

**Closed** 2019-01-24 20:48 UTC
