### ISSUE TITLE
Can lhlo_fuse_linalg support fusion like which in XLA ?

### ISSUE THREAD

**Issue by shanshanpt** [tensorflow/tensorflow#43370] opened 2020-09-20 02:40 UTC
Hi , I found that lhlo_fuse_linalg can do some fusion at Linalg level, but it seems can not support fusion like which in XLA now.
About fusion, have a design or completely plan at Linalg level ? 
Thanks.

**Comment by shanshanpt** [comment] 2020-09-21 01:22
hi @pifon2a , maybe you can give me some details, thanks.

**Comment by Saduf2019** [comment] 2020-09-21 07:18
@shanshanpt 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by pifon2a** [comment] 2020-09-21 20:39
@shanshanpt at the moment we are still relying on XLA to fuse the ops. We are relying on Linalg & ParallelLoops fusion for the ops that we know will fuse, e.g. output of XLA with LHLO fusion ops that already contain fusable ops inside. Of course, the goal is to have fusion passes in MLIR, but I am not sure if there are any concrete plans. 

You might want to check Linalg-on-Tensors, since it supports fusion of ops bodies, not only tiling-and-fusion of surrounding loops like in Linalg-on-Buffers case. @nicolasvasilache

**Comment by shanshanpt** [comment] 2020-09-23 03:09
> @shanshanpt at the moment we are still relying on XLA to fuse the ops. We are relying on Linalg & ParallelLoops fusion for the ops that we know will fuse, e.g. output of XLA with LHLO fusion ops that already contain fusable ops inside. Of course, the goal is to have fusion passes in MLIR, but I am not sure if there are any concrete plans.
> 
> You might want to check Linalg-on-Tensors, since it supports fusion of ops bodies, not only tiling-and-fusion of surrounding loops like in Linalg-on-Buffers case. @nicolasvasilache

thanks @pifon2a

**Comment by gowthamkpr** [comment] 2020-09-28 20:18
@shanshanpt Can we close this issue as it has been resolved. Thanks!

**Closed** 2020-09-28 20:34 UTC
Labels: comp:xla, type:others
