### ISSUE TITLE
ambiguous template instantiation error with Eigen code

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#44626] opened 2020-11-05 17:10 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4-rc0
- Bazel version (if compiling from source): 3.4.1

**Describe the problem**

2.4 introduces a regression in the compilation fails on POWER systems with "ambiguous template instantiation".
The reason is that TF adds specializations for Eigen internal classes which conflict with specializations done by Eigen itself.

In this case https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_spatial_convolutions-inl.h adds `Eigen::internal::gemm_pack_rhs` specializations, e.g. at https://github.com/tensorflow/tensorflow/blob/300b62ff6a53a554bf8699f0632a0f517419b02c/tensorflow/core/kernels/eigen_spatial_convolutions-inl.h#L1044

However the updated Eigen (in particular commit https://gitlab.com/libeigen/eigen/-/commit/6fe88a3c9db27c00a3817e391cf70116451bf046) adds an own specialization for POWER architectures, see e.g. https://gitlab.com/libeigen/eigen/-/commit/6fe88a3c9db27c00a3817e391cf70116451bf046#b3394fe72fd1b6f1213ded1197953458e6851483_23_2622

This then leads to the ambiguous template instantiation of 
```
template<class Scalar, class Index, class DataMapper, int nr, bool Conjugate, bool PanelMode>
struct Eigen::internal::gemm_pack_rhs<Scalar, Index, DataMapper, nr, 0, Conjugate, PanelMode>
```
because the Eigen version specializes the `Scalar`, while TF specializes all but Scalar, Index and nr.

For reference the types that this is tried to be instantiated are (taken from the log, slightly formatted): 

```
Scalar = double;
Index = long int;
DataMapper = Eigen::internal::TensorContractionSubMapper<double, long int, 0, Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 2>, const Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const double, 4, 1, long int>, 16, Eigen::MakePointer> > >, Eigen::ThreadPoolDevice>, Eigen::array<long int, 1>, Eigen::array<long int, 1>, 2, true, true, 0, Eigen::MakePointer>;
int nr = 4;
bool Conjugate = false;
bool PanelMode = false
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Compile on POWER according to instructions

**Any other info / logs**

While this currently may only happen on POWER there is always the risk of breaking things when adding to internals of another library. So it should be checked, if that is really required.
If it is, I'd suggest to extract the 4 implementations of `gemm_pack_rhs` into 4 functions. Then specializations can be added for each datatype that Eigen also specializes for which avoids the ambiguity.

A short term solution might also be to simply remove the Eigen specializations via a patch.

**Comment by Flamefire** [comment] 2020-12-08 15:43
> A short term solution might also be to simply remove the Eigen specializations via a patch.

I tried that and found it doesn't work. Multiple tests (e.g. //tensorflow/core/kernels:eigen_spatial_convolutions_test)  will fail due to wrong results. Hence I don't have an easy way anymore to compile and use TF on POWER

**Comment by ezhulenev** [comment] 2020-12-08 21:19
Thats's strange, all these ugly specializations in `eigen_spatial_convolutions-inl.h` are supposed to be only for performance reasons, and not change how the data is packed.

**Comment by Flamefire** [comment] 2020-12-09 08:54
What I did was to remove the gemm_pack_rhs class specializations from `Eigen/src/Core/arch/AltiVec/MatrixProduct.h` and tests failed. However when I removed the whole header (there is a conditional include in `Core` which I commented) it worked, so I guess there is some dependency on the stuff TF introduces and some other things from the MatrixProduct.h which fail to meet implicit assumptions in the TF code.

As I don't want to remove the whole AltiVec code from Eigen (which is likely better optimized than the generic code from TF) I'm currently trying to remove the code TF introduces in eigen_spatial_convolutions-inl.h and eigen_cuboid_convolution.h, i.e. the gemm_pack_rhs and TensorContractionInputMapper specializations. I do that conditionally on `defined(EIGEN_VECTORIZE_ALTIVEC) || defined(EIGEN_VECTORIZE_VSX)` so if that works, it can be used upstream by TF.

Still: Adding stuff to a foreign namespace even called `internal` is risky at best.

**Comment by ezhulenev** [comment] 2020-12-09 10:34
```
Still: Adding stuff to a foreign namespace even called internal is risky at best.
```

Yes, and we had our fair share of ODRs from that :) But it brings very large improvement in practice, and too TF specific to be moved upstream. I remember it was brought up in some discussion with Eigen maintainers, and there is a desire to clean that up, so it could be upstreamed, but as far as I know, no one is working on it right now.

**Comment by Flamefire** [comment] 2020-12-09 10:48
I see. Do you recall where that was discussed?
Maybe the Eigen maintainers and especially the authors of that AltiVec code could at least make something which is compatible with TF.
And maybe someone familiar with that code could judge, which implementation is better on POWER. I'd naively expect the Eigen code is faster, as it uses vector intrinsics while (IIUC) the TF code relies on auto-vectorization. But it might as well be better to selectively remove some of the Eigen code instead. As mentioned above I wasn't able to remove just enough so the TF code works and you'd still get the vectorized code for the parts TF doesn't touch.

**Comment by ezhulenev** [comment] 2020-12-09 10:55
Eigen template specialization in TF allows to bypass all DataMappers and read data directly from the underlying tensors. Reading data through data mappers incurs HUGE overheads in stride computations for TensorImagePatch operation.

However it all worked with an assumption that packed block format is the same for all architectures. With AltiVec, TF packing specialization will produce data in format not compatible with gemm expectations. I'd say that disabling specializations on the TF side for AltiVec is the right choice here.

**Comment by jayfurmanek** [comment] 2021-02-19 15:50
Hi all, I meant to respond here earlier.
This is an unfortunate problem caused by some recent enhancements to Eigen for existing Altivec instructions as well as a new ppc matrix unit. As noticed, it breaks TensorFlow because of their usage of the internal Eigen namespace and broad unchecked assumptions on data formats.
It's unfortunate, but for now, the best way around this is to just revert the enhancements altogether.

I work on a project called [Open Cognitive Environment](http://github.com/open-ce) which supports ppc64le and we have an [Eigen fork](https://github.com/open-ce/libeigen-eigen) with the enhancements [reverted](https://github.com/open-ce/libeigen-eigen/commit/6fe88a3c9db27c00a3817e391cf70116451bf046) that works.
There is a corresponding TensorFlow [patch](https://github.com/open-ce/tensorflow-feedstock/blob/master/recipe/0303-Eigen-customized.patch) to point TensorFlow to the fork as well.

There are some folks at IBM that are looking at this. I think it would be easier to fix if the TensorFlow eigen code was upstreamed.  As mentioned it is specific to TensorFlow, but TensorFlow is a large and important consumer of Eigen and, despite steps towards a MLIR world, will continue to be for the foreseeable future.

**Comment by Flamefire** [comment] 2021-02-19 16:50
FWIW: In Easybuild we have a patch reverting the TF changes when on POWER which also resolves this:https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.0_fix-eigen-on-power.patch

**Comment by maxiwell** [comment] 2021-03-05 16:39
Hi all,

IIUC, the Flamefire's patch removes TF specialization + InputMappers, which forces both functions `CuboidConvolution` and `SpatialConvolution` to use the old/slow tensor code from Eigen (unsupported/Eigen/CXX11/src/Tensor). 

There is some benchmark available to measure the impact of this change on performance?

**Comment by ezhulenev** [comment] 2021-03-05 17:54
There are benchmarks for convolutions in `tensorflow/core/kernels/eigen_benchmark_cpu_test.cc`

**Comment by ChipKerchner** [comment] 2021-03-05 20:24
>  ... use the old/slow tensor code from Eigen (unsupported/Eigen/CXX11/src/Tensor).

Power specializes the packing routines which should be quite fast.  Other than that, I'm not sure what other code there is

**Comment by Flamefire** [comment] 2021-03-06 18:02
> There is some benchmark available to measure the impact of this change on performance?

I'd be interested in that too. However first and foremost it has to work at all so we have something to compare against.
I remember trying to remove the Eigen code additions but ending up with wrong results from the calculations. Hence I went and removed the TF code instead.

**Comment by maxiwell** [comment] 2021-03-12 17:13
@Flamefire After some tests here, your patch ended up a good fix for this issue. Can I create a pull request?

**Comment by maxiwell** [comment] 2021-03-12 18:57
https://github.com/tensorflow/tensorflow/pull/47768

**Closed** 2021-03-23 21:45 UTC
Labels: TF 2.4, comp:core, type:build/install
