### ISSUE TITLE
The batch_size argument must not be specified when using dataset as an input & Batch size: 32 is not divisible by num_workers: 3

### ISSUE THREAD

**Issue by Xie-Fangyuan** [tensorflow/tensorflow#32077] opened 2019-08-29 08:03 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14.0
- Python version :3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: TITAN Xp, 3 x 12G

---

i'm using `MirroredStrategy()` to train on 3 GPUs, and use a tf `Dataset` as the model inputs. when calling `model.fit()`, if i specify `batch_size`, it shows `The batch_size argument must not be specified when using dataset as an input.` and if i don't specify `batch_size`, it shows `Batch size: 32 is not divisible by num_workers: 3 [Op:ExperimentalRebatchDataset]`.

i know that by calling `fit()`, `batch_size` is 32 by default, but when using dataset, i did call `batch()` and i can't change `batch_size` in `fit()`.

i thought i could use 1, 2, 4, etc. GPUs that can devide 32, but why 3 GPUs is not working.

```python
strategy = MirroredStrategy()
    with strategy.scope():
        model = LSTMModel(embs=que_embs, num_ans=len(ans_vocab.word_index) + 1)
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        model(tf.zeros(shape=(config.batch_size, config.pad_max_len), dtype=tf.int32))
        model.summary()

dataset = Dataset.from_tensor_slices((inputs, labels))
dataset = dataset.shuffle(buffer_size=4).repeat(3).batch(8)
history = model.fit(dataset, epochs=config.num_epochs,
                               # batch_size=config.batch_size,
                               validation_data=(dataset_val['questions'], dataset_val['answers']),
                               callbacks=create_callbacks())
```

**Comment by lhjohn** [comment] 2019-08-29 15:15
I experience a slightly different but possibly related problem with 2.0.0-rc0. After upgrading from 2.0.0-beta1 I removed the Iterator object and passed the Dataset object to the `mode.fit()` function directly.

When I specify tf.data.Dataset.batch(...) I get the ValueError `'batch_size' or 'steps' is required for 'Tensor' or 'Numpy' input data.`

When I instead specify 'batch_size' in `mode.fit()` I get the ValueError `The 'batch_size' argument must not be specified for the given input type. Received input <BatchDataset ...`.

**Comment by gadagashwini** [comment] 2019-08-30 06:06
@Xie-Fangyuan,
In order to expedite the trouble-shooting process, please provide a minimal complete code to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-09-09 10:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-09-09 10:35 UTC
Labels: TF 1.14, comp:dist-strat, stat:awaiting response, type:support

**Comment by jtiscione** [comment] 2019-09-21 16:35
This problem is not fixed.

[mnist.ipynb.txt](https://github.com/tensorflow/tensorflow/files/3638873/mnist.ipynb.txt)

**Comment by gadagashwini** [comment] 2019-09-23 05:18
@jtiscione,
Can you please post a new issue by providing the information asked by the [template](https://github.com/tensorflow/tensorflow/issues/new/choose)?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

**Comment by Aashit-Sharma** [comment] 2019-11-29 07:53
you need to put batch_size=None
