### ISSUE TITLE
Can't load saved keras model.h5

### ISSUE THREAD

**Issue by teodor440** [tensorflow/tensorflow#38994] opened 2020-04-28 19:58 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2 & 10.1
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When loading the model with keras.models.load_model the activation functions are not recognized. This happens only when activation functions are not builtin strings

**Describe the expected behavior**
To load the model with success

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

layer = tf.keras.layers.Dense(1, activation=tf.keras.layers.PReLU(alpha_initializer='random_uniform', alpha_regularizer=None, alpha_constraint=None, shared_axes=None),\
                            name='layerX', kernel_initializer=tf.keras.initializers.he_normal())
model = tf.keras.Sequential(layer)
model.compile("adam", "binary_crossentropy", ["accuracy"])
model.fit([[1]], [1])
model.save("keras_model.h5", save_format='h5' ")
model = tf.keras.models.load_model("keras_model.h5")
```
**EDIT**: After reading the docs I saved the model with save_format h5, first time I tried without any format (the default is tf for tensorflow 2.0+)
Instead I found a workaround: I can load the model if I save it with (default) save_format='tf'

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```Traceback (most recent call last):
  File "C:\Users\Teo\OneDrive\Licenta\main.py", line 138, in <module>
    main()
  File "C:\Users\Teo\OneDrive\Licenta\main.py", line 135, in main
    model = keras.models.load_model(os.path.join(dataset_path, "keras_model.h5"))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 303, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 377, in from_config
    custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 305, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 519, in from_config
    return cls(**config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 1082, in __init__
    self.activation = activations.get(activation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\activations.py", line 450, in get
    identifier, printable_module_name='activation')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown activation: PReLU
```

**Comment by ravikyram** [comment] 2020-04-29 06:56
@teodor440 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by teodor440** [comment] 2020-04-29 14:09
> 
> 
> @teodor440
> 
> Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

https://colab.research.google.com/drive/1qZ8RuI-oNoTsD2uokHZztqeCb20RX3wR#scrollTo=_gMOL9xUPGha
I also updated the code in the issue

**Comment by ravikyram** [comment] 2020-04-30 03:55
I have tried in colab with TF 2.1.0 , 2.2-rc3 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/d18890e6d91c6fe62dcff2934500927a/untitled840.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-30 05:19
@teodor440 I was able to reproduce the issue with `save_format='h5'`. However, when I used `save_format = 'tf'` everything worked as expected. `model.predict` before saving and after loading are exactly same. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/e753ca365a61c21d77bdd70844156f68/untitled840.ipynb). Thanks!

**Comment by teodor440** [comment] 2020-05-01 21:59
I am not familiar with the implementation of tensorflow, but seems like there is a problem with how tf sees keras models
I can recall the same value error when trying to convert the model to an estimator with  keras.estimator.model_to_estimator

**Comment by teodor440** [comment] 2020-05-03 14:44
Ok so the problem was that I specified the activations in the layers as something different than a string. For some reason or another this confuses the operations made on keras models by tf

**Comment by jvishnuvardhan** [comment] 2020-05-03 15:55
@teodor440 You can use "tf" format as it is working well. But, this is still a bug with "h5" format. I will reopen the issue. Thanks!

**Comment by teodor440** [comment] 2020-05-03 16:23
You can see now at the collab link that the issue with saving h5 model doesn't persist anymore if using separate layers for dense and activation. So basically this is a workaround for the problem

**Comment by ymodak** [comment] 2021-04-23 18:10
Closing this issue since the associated PR has been merged and the issue is fixed. Thanks

**Closed by ymodak** 2021-04-23 18:10 UTC
Labels: TF 2.1, comp:keras, stat:awaiting tensorflower, type:bug
