### ISSUE TITLE
Slim VGG losses increase gradually with default training configuration

### ISSUE THREAD

**Issue by kakpple** [tensorflow/tensorflow#15939] opened 2018-01-08 09:30 UTC
Hi, when I try to train imagenet with slim vgg network with default configuration,
The loss increases gradually from ~0.1 to over 10000. 
I am not even able to debug this issue because, all tensors losses are encapsulated inside slim.
Is there any way to debug this issue?

**Comment by tensorflowbutler** [comment] 2018-01-08 19:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kakpple** [comment] 2018-01-24 04:20
I find out that there was something wrong with the imagenet tfrecord.
Actually, in tfrecord image was labeled beyond 1000, larger than 1000.
I remade the tfrecord, and mobilenet and resnet is learning.
Anyway, thank you~

**Comment by reedwm** [comment] 2018-01-29 23:13
Closing since the issue is resolved.

**Closed by reedwm** 2018-01-29 23:13 UTC
