### ISSUE TITLE
High loss of accuracy after coverting ".pb" to ".lite" on Android

### ISSUE THREAD

**Issue by seayqrain** [tensorflow/tensorflow#21048] opened 2018-07-23 08:16 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I only modified the ImageClassifier.java to make it compatible with float and quant.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04.3 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
LG G4
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.7.1
- **Python version**:2.7.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:

### Describe the problem
Hi,
I retrained a module refer to [tensorflow-for-poets](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0), and its retrain.py was replaced by [this one](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/examples/image_retraining/retrain.py).

I did two experiments:

**1. Choose the module: mobilenet_1.0_224_quant**
I retrained the module with the command below:

> python -m scripts.retrain \
  --architecture=mobilenet_1.0_224_quant \
  --bottleneck_dir=tf_files/bottlenecks \
  --how_many_training_steps=500 \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/mobilenet_1.0_224_quant \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --image_dir=tf_files/flower_photos

Then I converted ".pb" to ".lite" with this command:

> toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph_quant.lite \
  --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --input_shape="1,224,224,3" \
  --input_array=input \
  --output_array=final_result \
  --std_value=128 --mean_value=128

I tested _optimized_graph_quant.lite_ with the _TfLiteCameraDemo_ which provided by tensorflow-for-poets.
And only once inference, I found that the accuracy is very good:

> 01-01 01:12:37.942 12117 12217 D TfLiteCameraDemo: Timecost to run model inference: 354
01-01 01:12:37.946 12117 12217 D TfLiteCameraDemo: textToShow = 354ms
01-01 01:12:37.946 12117 12217 D TfLiteCameraDemo: roses: 1.00
01-01 01:12:37.946 12117 12217 D TfLiteCameraDemo: sunflowers: 0.00
01-01 01:12:37.946 12117 12217 D TfLiteCameraDemo: tulips: 0.00

**2. Choose the module: mobilenet_1.0_224**
I retrained the module with the command below:

> python -m scripts.retrain \
  --architecture=mobilenet_1.0_224 \
  --bottleneck_dir=tf_files/bottlenecks \
  --how_many_training_steps=500 \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/mobilenet_1.0_224 \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --image_dir=tf_files/flower_photos

Then I converted ".pb" to ".lite" with this command:

> toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape="1,224,224,3" \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT

I also tested optimized_graph.lite with the _TfLiteCameraDemo_ which provided by tensorflow-for-poets.
And after multiple inferences, the accuracy increased to an acceptable value :

> 01-01 01:29:23.221 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 510
01-01 01:29:23.226 13207 13224 D TfLiteCameraDemo: roses: 0.06
01-01 01:29:23.483 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 238
01-01 01:29:23.488 13207 13224 D TfLiteCameraDemo: roses: 0.18
01-01 01:29:23.741 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 221
01-01 01:29:23.746 13207 13224 D TfLiteCameraDemo: roses: 0.31
01-01 01:29:24.162 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 398
01-01 01:29:24.167 13207 13224 D TfLiteCameraDemo: roses: 0.45
01-01 01:29:24.527 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 336
01-01 01:29:24.533 13207 13224 D TfLiteCameraDemo: roses: 0.58
01-01 01:29:24.898 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 339
01-01 01:29:24.907 13207 13224 D TfLiteCameraDemo: roses: 0.68
01-01 01:29:25.274 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 326
01-01 01:29:25.280 13207 13224 D TfLiteCameraDemo: roses: 0.76
01-01 01:29:25.646 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 340
01-01 01:29:25.652 13207 13224 D TfLiteCameraDemo: roses: 0.83
01-01 01:29:26.032 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 354
01-01 01:29:26.041 13207 13224 D TfLiteCameraDemo: roses: 0.87
01-01 01:29:26.433 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 365
01-01 01:29:26.438 13207 13224 D TfLiteCameraDemo: roses: 0.91
01-01 01:29:26.831 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 365
01-01 01:29:26.838 13207 13224 D TfLiteCameraDemo: roses: 0.93
01-01 01:29:27.288 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 391
01-01 01:29:27.296 13207 13224 D TfLiteCameraDemo: roses: 0.95
01-01 01:29:27.658 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 333
01-01 01:29:27.663 13207 13224 D TfLiteCameraDemo: roses: 0.97
01-01 01:29:28.005 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 313
01-01 01:29:28.010 13207 13224 D TfLiteCameraDemo: roses: 0.97
01-01 01:29:28.381 13207 13224 D TfLiteCameraDemo: Timecost to run model inference: 341
01-01 01:29:28.385 13207 13224 D TfLiteCameraDemo: roses: 0.98

**Please help to analyze that why it needs multiple inferences to get an good accuracy here? Thanks!**

**Comment by miaout17** [comment] 2018-07-24 20:46
The demo app applies a low-pass filter to the outputs. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L134

When outputs of TFLite interpreter are changed, the displayed values are changed gradually. This prevents the case that one bad frame makes the UI jumpy (e.g. 98% -> 0% -> 99%). 

The logic isn't in TFLite interpreter. You're free to change the code to disable the logic. If you get the values from TFLite interpreter directly is should be fine. 

Closing since this is working as intended.

**Closed by miaout17** 2018-07-24 20:46 UTC
Labels: comp:lite
