### ISSUE TITLE
cmake CUDA include-path whitespaces not supported

### ISSUE THREAD

**Issue by Smoothstep** [tensorflow/tensorflow#15920] opened 2018-01-06 23:12 UTC
I'm not sure if this is intentional, but I just had some trouble with compiling tf_core_gpu_kernels due to a invalid include-dir path as command line argument given to nvcc (caused by a whitespace in the path).

In windows I was able to solve this by adding double quotes at line 277 in CMakeLists.txt:
`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};--include-path \"${PROJECT_BINARY_DIR}/$\{build_configuration\}\";--expt-relaxed-constexpr)`

Possible errors when not using double quotes:
nvcc fatal : A single input file is required for a non-link phase when an outputfile is specified

Also note that there will be problems because of CUDA not supporting some versions of msvc.
The current version for example is not yet supported.
CUDA_HOST_COMPILER path is automatically set to $(VCInstallDir)/bin, what will cause problems on some systems. For VS2015 this works fine but not for VS2017 if you are using the recent compiler.

There are also several errors when using the intel compiler, as for example the typename TType<...> declarations, which are not really required. Either remove the typename keyword or use 'auto'.
Other than that the master branch is compilable with ICC 18.

**Comment by tensorflowbutler** [comment] 2018-01-07 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-24 13:15
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-08 19:21
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-23 14:02
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-10 13:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 12:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by mrry** [comment] 2018-04-10 23:17
Marking as contributions welcome, since the CMake build is community supported.

**Comment by tilakrayal** [comment] 2022-09-24 06:46
@Smoothstep,
Could you please take a look at this official doc link and kindly update to the latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

**Closed** 2022-10-08 09:49 UTC
Labels: stat:contributions welcome, stat:awaiting response, stat:community support, stalled
