### ISSUE TITLE
Backprop through conv2d with large tensors fails

### ISSUE THREAD

**Issue by ma0ho** [tensorflow/tensorflow#11327] opened 2017-07-06 15:12 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.1.0
- **Python version**: 
3.5.2
- **Bazel version (if compiling from source)**:
0.4.5
- **CUDA/cuDNN version**:
CUDA Version 8.0.61
- **GPU model and memory**:
GeForce GTX 1080, 8GB
- **Exact command to reproduce**:
```
import tensorflow as tf

proj = tf.Variable( tf.random_normal([720,1,400,600], stddev = 2) )
kernel = tf.Variable( tf.random_normal([1, 401, 1, 1], stddev = .5), trainable = True )
proj = tf.nn.conv2d(
    input = proj,
    filter = kernel,
    strides = [ 1, 1, 1, 1 ],
    padding = 'SAME',
    data_format = 'NCHW',
    name = 'ramlak-filter'
)
grad = tf.gradients( proj, kernel, proj )

with tf.Session() as sess:
    sess.run( tf.global_variables_initializer() )
    print( sess.run( grad ) )
```

### Describe the problem
Backpropagation through `conv2d` for large tensors produces an error for me (see log below). This is true for the code above. Lowering the batch size in `proj` from 720 to 100 eliminates the error. The issue has been confirmed by another user at [stackoverflow](https://stackoverflow.com/questions/44901742/tensorflow-error-while-backpropagating-through-conv2d).

### Source code / logs
```
NotFoundError (see above for traceback): No algorithm without scratch worked!
	 [[Node: gradients/ramlak-filter_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable/read, gradients/ramlak-filter_grad/Shape_1, ramlak-filter)]]
[log.txt](https://github.com/tensorflow/tensorflow/files/1128268/log.txt)

```

Please find the full log attached.

**Comment by andydavis1** [comment] 2017-07-06 16:26
@yzhwang  can you take a look?

**Comment by ma0ho** [comment] 2017-07-06 19:09
Just updated to TF 1.2.1 (built from source), but the issue persists.

**Comment by yzhwang** [comment] 2017-07-06 20:30
@ma0ho Thanks. I will take a look later today.

**Comment by ktamiola** [comment] 2017-07-10 15:42
I can also confirm that issue in freshly compiled  `1.2.1`.

**Comment by yzhwang** [comment] 2017-07-10 23:19
Thanks @ma0ho and @ktamiola . I was able to reproduce this too. Investigating now.

**Comment by yzhwang** [comment] 2017-07-17 22:28
Hi @ma0ho 
Just to make sure I understand it correctly: are you trying to use a 1-dimensional filter with both height and width as 1, and the feature map count being 401, or are you trying to use a filter with size [1, 401] and a feature map count as 1?
tensorflow's conv2d requires filter to be of the following format:
A 4-D tensor of shape [filter_height, filter_width, in_channels, out_channels]
So if I change the filter to [1, 1, 1, 401], it actually outputs the correct OOM error:
ResourceExhaustedError: OOM when allocating tensor with shape[720,401,400,600].

**Comment by ma0ho** [comment] 2017-07-18 10:07
@yzhwang: No, exactly as given in the example I'm using a 1D filter width 401 with one in and one output channel.. I'm sure this is not an OOM problem.

**Comment by ma0ho** [comment] 2017-07-18 10:29
Maybe I should make the use case a bit more clear:

I implement a classic CT (computed tomography) reconstruction algorithm (filtered backprojection) in Tensorflow. The goal is to adjust some of the steps by training and to add additional (trainable) pre-/postprocessing steps. In such a CT setup I have many 2D projection images. One of the steps is to filter all those projection images with the same `1xM` filter kernel. The projection images are stacked in a `NxHxW` tensor, where N is the number of projection images. In order to be able to filter them all with the **same** filter kernel, I reshape this to an `Nx1xHxW` tensor, such that N is now the batch dimension (note that I'm using format NCHW, therefore input is ` [batch, channels, height, width]`). Then I convolve with a `1xMx1x1` kernel in order to filter every projection image (every batch in this case) with a `1xM` kernel.

Hope this clarification helps to understand my problem..

**Comment by ChechyLevas** [comment] 2017-07-18 11:20
@ma0ho I found that when I run it on a build targeting cpu only, the issue does not appear. Obviously this is not a solution to the problem but it might be a clue as to the cause?

**Comment by yzhwang** [comment] 2017-07-24 16:44
Hi @ma0ho 
Some updates from our side:
1) This bug is due to one cudnn function didn't pick the correct internal kernel to call for backward filter conv. We have already filed a bug to NVIDIA.
2) We are working on a workaround to improve the internal logic of conv ops to handle this case. I will let you know once the code is pushed to github repo.

**Comment by ma0ho** [comment] 2017-07-24 16:52
@yzhwang: Thanks for your investigation so far!

**Comment by ktamiola** [comment] 2017-07-24 21:34
Fantastic! Thank you @yzhwang !

**Comment by pobingwanghai** [comment] 2017-07-29 07:04
Same error to conv3d!

**Comment by pobingwanghai** [comment] 2017-07-29 07:04
Same error to conv3d when setting a dimension to 1.

**Comment by pobingwanghai** [comment] 2017-07-29 07:05
Same error to conv3d when setting one dimension of the filter to 1.

**Comment by yzhwang** [comment] 2017-07-30 22:09
@pobingwanghai Could you provide more info as @ma0ho does in the template? It would be much easier for me to debug the problem if you could offer a reproducer too. I guess the OOM error is probably an intended behavior or another issue. But it would be nice if you can offer more info first so that I can have a look. Thank you!

**Comment by yzhwang** [comment] 2017-08-03 22:47
@ma0ho I think the commit that fixes this bug has been pushed to tensorflow. https://github.com/tensorflow/tensorflow/commit/db596594b5653b43fcb558a4753b39904bb62cbd
I have tested it internally to make sure it fixes the bug. Please confirm this with the OSS version. Thank you!

**Comment by zhenhe168** [comment] 2017-08-14 23:32
@yzhwang Hi, Wang, I got a similar issue as below. I have a moderate model with dozens of thousands of weights and 128 batch size of 128x128 size images. Can you tell me how to fix this? Thx a lot! I am using tensorflow r1.3 / python 3.6.1 / CUDA/cuDNN version: CUDA Version 8.0.61, GPU model and memory: GeForce GTX 1080, 8GB. 

Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

Restarting kernel...  

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, No algorithm without scratch worked!
         [[Node: gradients/dilated_conv6/convolution_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/dilated_conv6/convolution_grad/Shape, dilated_conv6/weights/read, gradients/dilated_conv6/convolution/BatchToSpaceND_grad/SpaceToBatchND)]]
         [[Node: Adam/update/_552 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1777_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'gradients/dilated_conv6/convolution_grad/Conv2DBackpropInput', defined at:
  File "/home/zhen/anaconda2/envs/tensorflow/lib/python3.6/site-packages/spyder/utils/ipython/start_kernel.py", line 231, in <module>
......
NotFoundError (see above for traceback): No algorithm without scratch worked!
	 [[Node: gradients/dilated_conv6/convolution_grad/Conv2DBackpropInput = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/dilated_conv6/convolution_grad/Shape, dilated_conv6/weights/read, gradients/dilated_conv6/convolution/BatchToSpaceND_grad/SpaceToBatchND)]]
	 [[Node: Adam/update/_552 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1777_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by yzhwang** [comment] 2017-08-15 00:04
Hi @zhenhe168 . I don't think r1.3 branch does not contain my commit that fixed this error: https://github.com/tensorflow/tensorflow/commit/db596594b5653b43fcb558a4753b39904bb62cbd. Could you try from head of master branch? I've confirmed it contains this commit.

**Comment by zhenhe168** [comment] 2017-08-15 05:18
thx for the quick response.
I am a newbie. May I ask whether there is any other easier way to install
the latest stable version, other then building tf source codes?

**Comment by yzhwang** [comment] 2017-08-23 18:50
Fixed with https://github.com/tensorflow/tensorflow/commit/db596594b5653b43fcb558a4753b39904bb62cbd. @ma0ho if you believe this didn't solve your issue, please let us know.

**Closed by yzhwang** 2017-08-23 18:50 UTC
Labels: stat:awaiting tensorflower

**Comment by zhenhe168** [comment] 2017-08-24 06:03
Thx, Yangzhihao. will try again on this Friday. So far, I have trouble
doing docker installation of latest build on my machine. :(

**Comment by hadarpo** [comment] 2017-09-05 09:03
Hi, is this bug solved already in version 1.3?

**Comment by yzhwang** [comment] 2017-09-05 15:38
It is fixed in head so if you build from source you won't see the bug. The commit that solved this bug didn't get into r1.3, but will be included in our next release.

**Comment by hadarpo** [comment] 2017-09-06 05:45
Thanks @yzhwang, as I see the nightly build of tensorflow for windows-gpu has not succeeded for more than a month, so I'm not sure that I can build it myself. Is there any guess when will be the next release?

**Comment by yzhwang** [comment] 2017-09-06 17:16
Sorry for the trouble. Previous release dates suggest a 2 month release cycle. But I'm not sure if this will always be the case. You can also patch in https://github.com/tensorflow/tensorflow/commit/db596594b5653b43fcb558a4753b39904bb62cbd with an earlier version of tensorflow if you need them immediately.

**Comment by hadarpo** [comment] 2017-09-07 05:57
Thanks a lot @yzhwang

**Comment by zhenhe168** [comment] 2017-09-07 19:04
Works for me now. Thx for bug fixing!

Zhen sent from my iPhone

**Comment by TamizhPS** [comment] 2017-10-29 07:45
>>> import tensorflow
**Bus error (core dumped)**


Has anyone solved the above issue

**Comment by yzhwang** [comment] 2017-10-30 04:07
@TamizhPS Are you sure this is a relevant issue? If so please provide more info as the original reporter did, so that I can take a closer look. Thank you!

**Comment by AmitSharma1127** [comment] 2020-09-06 07:02
Facing the same issue.

Stacktrace:
```
Found 28709 images belonging to 7 classes.
Found 7178 images belonging to 7 classes.
Epoch 1/10

---------------------------------------------------------------------------

NotFoundError                             Traceback (most recent call last)

<ipython-input-15-87899e1fd701> in <module>()
     36   return model, test_generator
     37 
---> 38 model, test_generator = train_eval_model(model)

9 frames

<ipython-input-15-87899e1fd701> in train_eval_model(model)
     27                                 validation_data=test_generator,
     28                                 validation_steps=validation_steps,
---> 29                                 callbacks=[callbacks])
     30 
     31   print("history.history['accuracy'][-1]: ", history.history['accuracy'][-1])

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1096                 batch_size=batch_size):
   1097               callbacks.on_train_batch_begin(step)
-> 1098               tmp_logs = train_function(iterator)
   1099               if data_handler.should_sync:
   1100                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    805       # In this case we have created variables on the first call, so we run the
    806       # defunned version which is guaranteed to never create variables.
--> 807       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    808     elif self._stateful_fn is not None:
    809       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2827     with self._lock:
   2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 
   2831   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

NotFoundError:  No algorithm worked!
	 [[node sequential/conv2d/Conv2D (defined at <ipython-input-10-87899e1fd701>:29) ]] [Op:__inference_train_function_2283]

Function call stack:
train_function

```

I am working in Google Colab and the this issue came out of nowhere since I ran the same code many times before as well and it worked and trained expectedly. But now, with no significant changes in the code, it's throwing in this error.
