### ISSUE TITLE
Memory leak in eager mode when creating keras model in loop

### ISSUE THREAD

**Issue by tjume** [tensorflow/tensorflow#30324] opened 2019-07-02 19:55 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not tested
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-5259-ge703239 1.15.0-dev20190629
- Python version: 3.7.3
- Bazel version (if compiling from source): not compiled from source
- GCC/Compiler version (if compiling from source): not compiled from source
- CUDA/cuDNN version: using CPU
- GPU model and memory: using CPU

**Describe the current behavior**

In eager execution, when creating a `tf.keras.Sequential` model inside a loop and discarding it immediately, the memory increases over time. The following code shows this by printing the used memory at each iteration.

```python
import psutil
import tensorflow as tf

tf.compat.v1.enable_eager_execution()

for _ in range(100):
    tf.keras.Sequential([tf.keras.layers.Dense(3000, input_dim=3000)])
    print(psutil.virtual_memory().used / 2 ** 30)
```

Output:

```
1.0170440673828125
1.0506706237792969
1.0841865539550781
1.1179122924804688
[...]
4.285423278808594
4.318950653076172
4.35223388671875
```

The same result happens when using the Functional API or Model subclassing API. Adding `tf.keras.backend.clear_session()` in the loop solves the leak in all cases like in graph mode. To see this effect better, one should additionally use `gc.collect()` in the loop.

**Describe the expected behavior**

While adding `tf.keras.backend.clear_session()` to the loop helps, this should not be necessary because in eager execution there is no graph to clear, which according to the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session) seems to be the only thing this function does:

> Destroys the current TF graph and creates a new one.

Therefore it is also suprising that this function helps at all during eager execution. The expected behavior is that there is no memory leak even without `tf.keras.backend.clear_session()`. 

**Code to reproduce the issue**
Code is in description above.

**Other info / logs**
Nothing here.

**Comment by bionicles** [comment] 2019-07-03 01:02
Does 

`del model`

Help?

**Comment by wangyexiang** [comment] 2019-07-03 01:40
It doesn‘t work!@bionicles

**Comment by wangyexiang** [comment] 2019-07-03 02:58
> 
> 
> Does
> 
> `del model`
> 
> Help?

It doesn‘t work!@bionicles

**Comment by wangyexiang** [comment] 2019-07-03 02:59
A similar situation, if I train the model in the main thread and load the model in another thread AT THE SAME TIME. All things is in a loop. However, if I use clear_session() method in one thread, the code in another thread won't work!!! I test pytorch and mxnet , and there is no any memory leak in a loop. why??? amazing tensorflow!!! I think that clear_session shouldn't be necessary. @bionicles @tjume

**Comment by pandrey-fr** [comment] 2019-07-03 07:52
> if I use clear_session() method in one thread, the code in another thread won't work!!!
That is purely logical. Threads share memory, thus if you call `clear_session` to swipe a model out of memory in a thread, don't expect other threads to access the now-deleted memory...

Now, I do agree (after reproducing the issue, which is all the more present in TF 2.0 with Eager execution enabled by default) that the absence of implicit garbage collection inside the loop is a bit annoying. Note that if you use `clear_session` (without `gc.collect`), the garbage collector will take out the past models from memory every few seconds (which shows if you add some `time.sleep` instruction in the loop), so I guess there are two things at stake in what you raise:
* keras models created in a given scope are not swiped out when they go out of scope (causing more or less of a memory leak) - this indeed probably requires either fixing or documenting (so that users will either use `clear_session` or not need it)
* the python garbage collector can take some time before deallocating the memory taken by those models once their clearing has been ordered (which I don't think tensorflow developers can do much about)

My humble opinion, however is that it really is not an amazing effort from your end as a programmer to add a couple of memory-freeing instructions now and then in your code... This is actually pretty common, in my experience, when you are creating stuff faster than the garbage collector will take care of. But that will be up to the developers/maintainers to decide!

**Comment by wangyexiang** [comment] 2019-07-03 08:24
Maybe I didn't make it clear. I mean if I train model A in the main thread and load  model B and predict  in another thread AT THE SAME TIME. All things are in a loop. However,  if I use clear_session() method in one thread (to clear model A, e.g), BUT the model B in another thread  doesn't work(DOESN'T predict). **As you can see,  there is no any relationship between model A and model B. It seems that  clearing model A can influence model B.**why??? That isn't logical. @pandrey-fr

**Comment by pandrey-fr** [comment] 2019-07-03 10:32
> It seems that clearing model A can influence model B

Oh, I see! Thanks for clarifying the issue. From my understanding (but I might be wrong - I am just a tensorflow user, not an expert, let alone a developer), `tf.keras.backend.clear_session` clears all graphs _that have not been called yet_. So, if you declare models A and B, then `clear_session` will remove all those whose `predict` (or `evaluate`, or `fit`, etc.) method has not yet been called. On the other hand, once you have called such a method, the model cannot be deleted using `clear_session`, but can be so using `del <my_instance>`. In either cases, using `gc.collect` ensures the freed memory is effectively deallocated (otherwise it will be done once the garbage collector's routine check on it).

Examples:
```
import numpy as np
import tensorflow as tf

# Enable Eager execution, if required (i.e. using TF 1.x).
if hasattr(tf, 'enable_eager_execution'):
    tf.enable_eager_execution()

# Make some dummy input data.
inputs = np.random.normal(size=(1, 3000))

# Declare two models.
model_a = tf.keras.Sequential([tf.keras.layers.Dense(3000, input_dim=3000)])
model_b = tf.keras.Sequential([tf.keras.layers.Dense(3000, input_dim=3000)])

# This will clear BOTH models (i.e. the underlying graph will be cleared out).
tf.keras.backend.clear_session()
# Both those lines are going to fail:
model_a.predict(x)
model_b.predict(x)


# Declare two models (again).
model_a = tf.keras.Sequential([tf.keras.layers.Dense(3000, input_dim=3000)])
model_b = tf.keras.Sequential([tf.keras.layers.Dense(3000, input_dim=3000)])

# Use model B.
model_b.predict(x)
# This will discard the graph underlying model A ONLY.
tf.keras.backend.clear_session()
# This will fail.
model_a.predict(x)
# This will work.
model_b.predict(x)

# Discard model B (now that is has been called).
del model_b

# Note that using gc.collect() enforces garbage collection at wanted points.
```

**Comment by pandrey-fr** [comment] 2019-07-03 10:34
That being cleared, I now agree with you that it could be useful to dispose of a generic function to clear out a specific keras model without having to worry about its having been used or not. Let's wait for somebody from the mainteance / development team to actually pick up this issue!

**Comment by wangyexiang** [comment] 2019-07-03 11:12
OK. Thanks in advance @pandrey-fr

**Comment by brandonbell11** [comment] 2019-09-11 23:23
Why is this not fixed in all the github threads I’ve come across? Seems pretty useless to be unable to call model.predict() in a loop.

Looks like I may have to switch to pytorch

**Comment by rodrigoruiz** [comment] 2019-11-01 18:17
I'm using TensorFlow 2.0.0 and Keras 2.3.1 and still having the same issue.

**Comment by robieta** [comment] 2019-11-12 20:36
I'm going to close this since the original issue (growth from model creation) has been addressed as a known issue and now the thread is kind of drifting. We have also recently made a fix to the internals of TF that eliminates a leak when invoking model.predict many, many times. If you are still seeing issues with predict, feel free to open a new issue with a repro.. Thanks for all of the feedback.

**Closed by robieta** 2019-11-12 20:36 UTC
Labels: TF 2.0, comp:eager, type:bug
