### ISSUE TITLE
Layer test does not set weights when testing with Sequential API

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tensorflow#31476] opened 2019-08-09 12:24 UTC
**System information**
- Have I written custom code: No
- OS Platform and Distribution: macOS 10.15
- TensorFlow installed from: pip installed
- TensorFlow version: 1.14.0 (v1.14.0-rc1-22-gaf24dc91b5)
- Python version: 3.6

**Current Behaviour**
When using the `layer_test` util function in `keras.testing_utils` when testing the layer in the context of the Sequential API the weights are not set, and as a result the output of the layer will be different than expected. If expected_output is provided this will likely differ to the output from the layer and hence the test will fail.

I think that the weights on the layer should be set before calling the sequential model which can be solved with one extra line. This is done for all of the other tests already.

```python
model = keras.models.Sequential()
model.add(layer)
# add `layer.set_weights(weights)` here to fix problem
actual_output = model.predict(input_data)
...
if expected_output is not None:
  np.testing.assert_allclose(actual_output, expected_output, rtol=1e-3)
```

**Comment by jvishnuvardhan** [comment] 2019-08-12 18:28
@peteboothroyd Can you provide a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-08-22 18:47
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-08-22 18:47 UTC
Labels: TF 1.14, comp:keras, stat:awaiting response, type:bug
