### ISSUE TITLE
Centos 7, installed bazel version is 0.10 yet ./configure complain about atleast 0.4.2 version

### ISSUE THREAD

**Issue by puran157** [tensorflow/tensorflow#16823] opened 2018-02-07 06:43 UTC
I was trying to build tensorflow (branch r1.0) on centos7.
./configure exited with following error
`Current Bazel version is 0.10.0- (@non-git), expected at least 0.4.2
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package 'external': Package 'external' contains errors
Building: no action`

Steps involved in installing bazel
1. Go to bazel website
2. Download repo file and copy the same to /etc/repo.d
3. Execute `yum install bazel` 

Have I written custom code: NO
OS Platform and Distribution: Centos 7
TensorFlow installed from: source
TensorFlow version: 0.10
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: ./configure

**Comment by vvirag** [comment] 2018-02-07 18:18
Same problem here. Ubuntu 16.04. Installed bazel based on "Using Bazel custom APT repository (recommended)" (https://docs.bazel.build/versions/master/install-ubuntu.html):

```
sudo apt-get install openjdk-8-jdk
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update && sudo apt-get install oracle-java8-installer
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install bazel
```

**Comment by tensorflowbutler** [comment] 2018-02-07 19:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vvirag** [comment] 2018-02-07 20:48
Switched to tensorflow r1.6, now it works. If you wanna fix the original problem, just checkout the relevant bazel version checking function from the r1.6 in the workspace.bzl.

**Comment by AlphasCodes** [comment] 2018-02-19 10:00
I can confirm the issue with Bazel 0.10.1 and Tensorflow 1.5.

Have I written custom code: NO
OS Platform and Distribution: Ubuntu 17.10
TensorFlow installed from: Source
TensorFlow version: 1.5
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: bazel build --jobs 15 --config=opt //tensorflow/tools/pip_package:build_pip_package

steven@desktop:~/opt/git/tensorflow$ ./configure
Extracting Bazel installation...
You have bazel 0.10.1 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3


Found possible Python library paths:
  /usr/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3.6/dist-packages]
/usr/lib/python3/dist-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: Y
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: n
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: n
No Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: N
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: N
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 


Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Configuration finished


steven@desktop:~/opt/git/tensorflow$ bazel build --jobs 15 --config=opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/steven/opt/git/tensorflow/WORKSPACE:15:1: Traceback (most recent call last):
	File "/home/steven/opt/git/tensorflow/WORKSPACE", line 15
		closure_repositories()
	File "/home/steven/.cache/bazel/_bazel_steven/50a548f93783a225d8430a085c4d5aab/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
		_check_bazel_version("Closure Rules", "0.4.5")
	File "/home/steven/.cache/bazel/_bazel_steven/50a548f93783a225d8430a085c4d5aab/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
		fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.1
ERROR: Error evaluating WORKSPACE file
ERROR: /home/steven/opt/git/tensorflow/WORKSPACE:41:1: Traceback (most recent call last):
	File "/home/steven/opt/git/tensorflow/WORKSPACE", line 41
		tf_workspace()
	File "/home/steven/opt/git/tensorflow/tensorflow/workspace.bzl", line 48, in tf_workspace
		check_version("0.5.4")
	File "/home/steven/opt/git/tensorflow/tensorflow/workspace.bzl", line 38, in check_version
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.10.1, expected at least 0.5.4
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.187s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tensorflowbutler** [comment] 2018-03-06 19:17
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by puran157** [comment] 2018-03-07 10:32
Have I written custom code: NO
OS Platform and Distribution: Centos 7
TensorFlow installed from: source
TensorFlow version: 0.10
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: ./configure

**Comment by tatianashp** [comment] 2018-04-04 02:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-04-04 02:09 UTC
