### ISSUE TITLE
how to freeze graph in tensorflow 2.0

### ISSUE THREAD

**Issue by anhtu812** [tensorflow/tensorflow#27614] opened 2019-04-08 04:46 UTC
not found any related document

**Comment by muddham** [comment] 2019-04-09 06:57
@anhtu812 Request you to please go through this link https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

**Comment by anhtu812** [comment] 2019-04-10 08:14
i tried, but i get error:
```
Traceback (most recent call last):
  File "convert_h5_to_tflite.py", line 186, in <module>
    variable_names_blacklist)				
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 340, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 251, in _parse_input_graph_proto
    input_graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```
i think freeze_graph.py have not updated to compatible with tensorlow 2.0

**Comment by jvishnuvardhan** [comment] 2019-04-16 21:39
@anhtu812 Here is the correct link to 2.0 [Freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/tools/freeze_graph.py). 
The link provided by @muddham corresponds to "master" which is TF1.13.1. Thanks!

I think it was resolved. I am closing the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-16 21:39 UTC
Labels: 2.0, comp:ops, type:support

**Comment by anhtu812** [comment] 2019-04-18 03:46
what is output_node_names in this case ( saved_model.save(keras_model, 'saved_model') ).
Following code out error:
```
from tensorflow.python.tools import freeze_graph
import tensorflow.keras as keras
import tensorflow as tf



# input_data = keras.layers.Input((300,300,3), dtype=tf.float32)
# y_pred = keras.layers.Lambda(lambda x: tf.identity(x, name="out"), name='fts_output')(input_data)
# model = keras.models.Model([input_data], y_pred)
# tf.saved_model.save(model, 'saved_model')




output_graph = 'final_model.pb'
output_node_names = 'model/fts_output/out'
input_saver = ""
input_binary = True
restore_op_name = 'save/restore_all'
filename_tensor_name = 'save/Const:0'
clear_devices = True
initializer_nodes = ''
variable_names_blacklist = ''


freeze_graph.freeze_graph('', input_saver, input_binary,
			'', output_node_names,
			restore_op_name, filename_tensor_name,
			output_graph, clear_devices, initializer_nodes,
			variable_names_blacklist, input_saved_model_dir='saved_model')
```
log error:
```
Traceback (most recent call last):
  File "freeze_graph.py", line 30, in <module>
    variable_names_blacklist, input_saved_model_dir='saved_model')
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 363, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 232, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 270, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 182, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 137, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: model/fts_output/out is not in graph
```

**Comment by leimao** [comment] 2019-06-27 22:20
I doubt if TensorFlow 2.0 has officially supported frozen graph.

**Comment by KANGRuipeng** [comment] 2019-10-23 03:36
@leimao could you give more information, I can't find the API

**Comment by leimao** [comment] 2019-10-23 03:47
> @leimao could you give more information, I can't find the API

It has been confirmed that TensorFlow 2.0 deprecated the usage of frozen graph. To use frozen graph in TensorFlow 1.x, check out my blog post at https://leimao.github.io/blog/Save-Load-Inference-From-TF-Frozen-Graph/

**Comment by KANGRuipeng** [comment] 2019-10-24 01:17
> > @leimao could you give more information, I can't find the API
> 
> It has been confirmed that TensorFlow 2.0 deprecated the usage of frozen graph. To use frozen graph in TensorFlow 1.x, check out my blog post at https://leimao.github.io/blog/Save-Load-Inference-From-TF-Frozen-Graph/
thks

**Comment by nmatare** [comment] 2019-10-28 17:50
https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0

"Removed the freeze_graph command line tool; SavedModel should be used in place of frozen graphs."

**Comment by x10000year** [comment] 2019-12-12 03:04
why freeze_graph is deprecated in TF2? freeze_graph can reduce the latency of my model by 2ms in TF1.14, even with XLA enabled. @leimao  @nmatare

**Comment by leimao** [comment] 2019-12-12 03:23
> why freeze_graph is deprecated in TF2? freeze_graph can reduce the latency of my model by 2ms in TF1.14, even with XLA enabled. @leimao @nmatare

Simply because there is no tf.Session(), which is a necessary component to build frozen models, anymore in TF 2.0, and I guess Google does not want to bother to implement another protocol to freeze models without using the tf.Session() path.

**Comment by x10000year** [comment] 2019-12-12 04:23
> > why freeze_graph is deprecated in TF2? freeze_graph can reduce the latency of my model by 2ms in TF1.14, even with XLA enabled. @leimao @nmatare
> 
> Simply because there is no tf.Session(), which is a necessary component to build frozen models in TF 1.x, anymore in TF 2.0, and I guess Google does not want to bother to implement another protocol to freeze models without using the tf.Session() path.

But when we deploy the model in c++ (or other language?), we still need to use session. The latency reduced by freeze_graph is also important. Does TF2.0 clear the need to use frozen graph to reduce the model latency? In my test, at least for TF1.15 I still need to use freeze_graph to further reduce the model latency.

Another problem is model size. For mixed precision training, full-precision weights are stored in SavedModel, which are big. Freeze_graph can help to reduce the model size.

**Comment by Robin2091** [comment] 2020-01-08 04:48
@x10000year @leimao I think TF2 has this: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/convert_to_constants.py
This generates a .pb file that has the graph and weights but I am not to sure if its the same thing as freeze model

**Comment by leimao** [comment] 2020-01-08 04:50
> @x10000year @leimao I think TF2 has this:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/convert_to_constants.py
> This generates a .pb file that has the graph and weights but I am not to sure if its the same thing as freeze model

Does it generate a single .pb file without anything else?

**Comment by Robin2091** [comment] 2020-01-08 04:50
@leimao No, it just generates the pb file

**Comment by Robin2091** [comment] 2020-01-08 04:52
https://github.com/Unity-Technologies/barracuda-release/blob/release/0.3.2/Documentation~/Barracuda.md.
There is also some code right here that simplifies that whole process in that file. It is under Converting TensorFlow models to Barracuda format section.

**Comment by leimao** [comment] 2020-01-08 04:52
> @leimao No, it just generates the pb file

If it is a single `pb` file whose size is several MB (depending on the size of the model), it is likely to be a frozen model, although it remains to be verified. This is an interesting finding @Robin2091 .

**Comment by Robin2091** [comment] 2020-01-08 04:56
I have the file generated for a YOLOv3 tiny object detector. It is only 96300 kB, so I am not sure. Also when I try to convert the file into an onnx format I get an error saying failed to parse file. I used the code from tf2onnx converter.
https://github.com/onnx/tensorflow-onnx/
So I am not sure if it has the weights in it then. Although my .tf weights file is only 30000 kB so there is a chance the 96000kB file includes the weights

**Comment by leimao** [comment] 2020-01-08 05:04
> I have the file generated for a YOLOv3 tiny object detector. It is only 96300 kB, so I am not sure. Also when I try to convert the file into an onnx format I get an error saying failed to parse file. I used the code from tf2onnx converter.
> https://github.com/onnx/tensorflow-onnx/
> So I am not sure if it has the weights in it then. Although my .tf weights file is only 30000 kB so there is a chance the 96000kB file includes the weights

It is very likely that you are correct. Note that the function used for freezing model in TF1.x is called [`convert_variables_to_constants`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/graph_util/convert_variables_to_constants) which is also included in the file you provided here.
I will look into this at my convenience. Thanks @Robin2091 .
In addition, I have not used tf2onnx myself in practice. So I could probably not advise on that. However, if you are interested, you may try NVIDIA TensorRT for inference, it takes frozen model as input. But I am not sure if it can still work for the "frozen model" generated from your protocol.

**Comment by Robin2091** [comment] 2020-01-08 05:11
@leimao Ok, let me know if you find any related information to this. I will also look into TensorRT. 
Thank you.

**Comment by leimao** [comment] 2020-01-10 05:16
> @leimao Ok, let me know if you find any related information to this. I will look into TensorRT. Also, do you know if a model in TF2 can be processed by TF1.x. Since the converters(tf2onnx and others) use TF1 so that might be why my pb file cannot be read?
> Thanks for the advice.

TensorFlow 2.x does support freezing models and this frozen model should be equivalent to the frozen models used for TensorFlow 1.x. 
Please check my [blog post](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/) and [code example](https://github.com/leimao/Frozen_Graph_TensorFlow/tree/master/TensorFlow_v2).

**Comment by Robin2091** [comment] 2020-01-10 06:27
@leimao Thanks for the confirmation. I also got the conversion working so the .pb generated is equivalent.

**Comment by nuqz** [comment] 2020-04-14 20:12
@leimao First of all thanks for detailed guide and code samples.

I have a problem with following your guide using TF 2.1. It seems that `tensorflow.python.framework.convert_to_constants.convert_variables_to_constants_v2` is not available in TF 2.1 anymore.

May I ask you to point me to an analog of this function? Of course, if this method is still relevant. And if not, could you tell me how to?

Regards.

**Comment by ethanyanjiali** [comment] 2020-08-07 00:47
@leimao thank you so much. you saved my day. i hope TF team can document more for this approach, as frozen graph is still the most common format used by other libraries.

**Comment by YouSenRong** [comment] 2022-07-31 14:11
> 

Hello, if my model has many inputs, how to create a tf.function and get_concrete_function? Thanks in advance.

```python
full_model = tf.function(lambda x: model(x))
    full_model = full_model.get_concrete_function(tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
```

**Comment by YouSenRong** [comment] 2022-07-31 14:14
@leimao 

Hello, if my model has many inputs(more than 10), how to deal with in your example? Thanks in advance!

```python
full_model = tf.function(lambda x: model(x))
    full_model = full_model.get_concrete_function(tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
```
