### ISSUE TITLE
Tensorflow need a long startup time

### ISSUE THREAD

**Issue by LittleFatHero** [tensorflow/tensorflow#30256] opened 2019-06-30 10:19 UTC
when I run the example on https://www.tensorflow.org/tutorials/
It take around 5 minutes at:
Adding visible gpu devices: 0
before the tensorflow begins to compute. As far as I know a lot of people have this problem since a years age, but there seems to be no effective way to sove the problem.
the only way I know is to compile from source, that is not a good way for a beginner.

My environment is Win10, tensorflow-gpu-2.0-beta1， CUDA 10.0, cuDNN 7.6, python 3.6 and with GTX 850M

When the problem will be fixed？

**Comment by wangyexiang** [comment] 2019-07-01 01:00
Same issue. It take around 2 minutes.@LittleFatHero

**Comment by gadagashwini** [comment] 2019-07-01 05:57
@LittleFatHero Can you elaborate more about the issue and context. And also provide the tutorial link where the issue is pointing. Thanks!

**Comment by LittleFatHero** [comment] 2019-07-03 02:34
> @LittleFatHero Can you elaborate more about the issue and context. And also provide the tutorial link where the issue is pointing. Thanks!

I install tensorflow on my windows 10 laptop using conda with the following command:
```
conda create -n tf2gpu python=3.6
conda activate tf2gpu
conda install cudatoolkit=10.0
conda install cudnn
pip install tensorflow-gpu-2.0-beta1
```  
then I run the code with the following command:
```
python mnist.py
```
the code of mnist.py is copy from   https://www.tensorflow.org/tutorials/ .
then the tf 2.0 begins to run and the screen of the cmd begins to output some run infomation.
But it take a long time(about five minutes )  and stop output anything when the infomation "Adding visible gpu devices: 0" show up. after that It begin to computes.

the bug seems no need to fixed ? but it is really annoying.
more information:
 https://github.com/tensorflow/tensorflow/issues/18652

**Comment by gadagashwini** [comment] 2019-07-03 04:45
@LittleFatHero Did you get a chance to go through this [link](https://www.tensorflow.org/beta/guide/using_gpu#limiting_gpu_memory_growth). Thanks!

**Comment by LittleFatHero** [comment] 2019-07-08 02:22
> @LittleFatHero Did you get a chance to go through this [link](https://www.tensorflow.org/beta/guide/using_gpu#limiting_gpu_memory_growth). Thanks!

Thank you very much! I will take a look at it and try to figure out a solution!

**Comment by gadagashwini** [comment] 2019-07-10 09:08
@LittleFatHero Were you able to resolve this issue? Thanks!

**Comment by LittleFatHero** [comment] 2019-07-10 16:27
> @LittleFatHero Were you able to resolve this issue? Thanks!

No, I have go through that link you offer, but I can't find a way to solve this problem, Can you tell me how to fix the problem on detail? Thank you

**Comment by Jarvis-onEarth** [comment] 2019-09-19 16:28
Had the same issue. 
But it seems the delay is happening only in first tf run. Subsequent runs happens pretty quickly.
So, I would run a helloworld immediately after boot, before jumping to my core development!

**Comment by aaroey** [comment] 2019-09-19 20:43
@gunan could you help to find someone familiar with windows GPU build to help with the problem?

**Comment by gunan** [comment] 2019-09-19 22:00
@chsigg This is probably a CUDA compute  capability we have not built TF binary with.

**Comment by gunan** [comment] 2019-09-19 22:01
If you are installing using conda, we should escalate to @jjhelmus

**Comment by jjhelmus** [comment] 2019-09-20 14:59
From the install commands the Python interpreter seems to be installed using conda but the tensorflow is coming from pip.  Note that using the `cudatoolkit` and `cudnn` packages to full fill the CUDA requirements of the pip package is not recommended nor supported.

**Comment by chsigg** [comment] 2019-09-20 15:31
This is the driver compiling all of TensorFlow's CUDA kernels at startup. Your GTX 850M has CUDA compute capability 5.0. We ship TensorFlow with precompiled kernels for the following compute capabilities: 3.5,3.7,5.2,6.0,6.1,7.0

GPUs with compute capability 5.0 are low end devices which are not recommended for running TensorFlow. See https://en.wikipedia.org/wiki/CUDA

I'm closing this comment because the original question seems to be answered. Please feel free to reopen if you have further questions.

**Closed by chsigg** 2019-09-20 15:31 UTC
Labels: TF 2.0.0-beta0, comp:gpu, comp:runtime, type:bug

**Comment by eyildiz-ugoe** [comment] 2022-02-28 15:22
Same story.

Python 3
TF 2.4.1
CUDA 10.1
Cudnn 7.6.5 

It's unbelievable that this was not solved for over a year. Time to switch to Pytorch, I guess.
