### ISSUE TITLE
[lite/micro] Huge size of libtensorflow-microlite.a for arm

### ISSUE THREAD

**Issue by csukuangfj** [tensorflow/tensorflow#32345] opened 2019-09-09 10:21 UTC
The file `tensorflow/lite/experimental/micro/README.md` says 
>The core runtime fits in 16KB on a Cortex M3, and with enough operators to run a speech keyword detection model, takes up a total of 22KB.

But after compiling `libtensorflow-microlite.a`, I get

```
ls -lh
total 512
-rw-r--r--  1 xxx  xxx   254K Sep  9 18:11 libtensorflow-microlite.a
```

which is an order of magnitude larger than `22KB`.

The command I used to compile it is:

```
make -j2 -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=foo microlite
```

The configuration file `lite/experimental/micro/tools/make/targets/foo_makefile.inc` is 
```
ifeq ($(TARGET), foo)

TARGET_TOOLCHAIN_PREFIX := arm-none-eabi-

COMMON_FLAGS := \
-O2 \
-fno-unwind-tables \
-fstack-reuse=all -ffunction-sections -fdata-sections -Wl,--gc-sections -nostartfiles \
-mthumb -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 \
-mno-thumb-interwork -ffast-math  \
-Wall -Werror -Wlogical-op -Waddress -Wempty-body -Wpointer-arith \
-Wenum-compare  -fno-strict-aliasing \
-Wno-sign-compare \
-nostdlib \
-fno-exceptions \
-fno-unwind-tables \
-fno-builtin

CXXFLAGS += $(COMMON_FLAGS) -fno-rtti
CCFLAGS += $(COMMON_FLAGS)

endif
```

The compiler toolchain information is as follows:

```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.3.1 20160307 (release) [ARM/embedded-5-branch revision 234589]
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by rockyrhodes** [comment] 2019-09-09 17:09
Duplicate of #32037

Please followup on the above bug.  We would like help in testing a different proposed solution.

**Comment by rockyrhodes** [comment] 2019-09-09 17:10
Sorry.  Closed the wrong issue.

**Comment by csukuangfj** [comment] 2019-09-10 04:09
@rockyrhodes  @tensorflowbutler @ravikyram 

is there any workaround to solve this problem?

I'm porting tflite micro to a smart watch, but the resulting library is so large that it is impossible to put it into the chip.

**Comment by rockyrhodes** [comment] 2019-09-10 15:33
The size of the .a file does not represent the amount of memory used on-device.  The compiler flags used in the various target makefiles include directives like --gc-sections and -ffunction-sections that are used to eliminate unused code and data from the compiled binaries.

All of the tests and examples run successfully on the SparkFun Edge development board, for example, which has 1MB of Flash and 384KB of SRAM.

We have been recently trying to improve the memory footprint a bit more as well.  A new memory manager for allocating space for tensor memory that just landed makes a big improvement in some of the examples.

**Comment by csukuangfj** [comment] 2019-09-10 23:15
@rockyrhodes 
>The size of the .a file does not represent the amount of memory used on-device. 

yes, you are right. But the final binary is still larger than 100KB (compared against linking and without linking `libtensorflow-microlite.a` with `size`)

I added the flags `--gc-sections` and `-ffunction-sections` while compiling the library.

>All of the tests and examples run successfully on the SparkFun Edge development board, for example, which has 1MB of Flash and 384KB of SRAM.

this only demonstrates the upper bound resources needed by lite micro. In addition, for all the 
examples in the repository, lite micro is the only application running on the target system. But 
a real system cannot allocate all resources to a single application and it has to consider other applications.

A NN model for an embedded system might be 30 KB, but if the framework is much larger than
the model, it's very hard to persuade people to use the framework.

what really makes me feel excited is the following statement listed in the README.md
>The core runtime fits in 16KB on a Cortex M3, and with enough operators to run a speech keyword detection model, takes up a total of 22KB.

Could you please post the instructions for compiling to achieve this or update the figure
according to the latest version?

**Comment by rockyrhodes** [comment] 2019-09-11 00:06
I'll let Pete answer the specific question about replicating the results quoted in the README.md file.  I'm not sure exactly how we computed these numbers.

It's possible you're right that we've admitted a bit of bloat to the framework as we've expanded its capabilities, but it still looks like it's pretty reasonable.  If I compile the micro_speech_test for the apollo3evb target (an M4 processor), the text and data that are generated for loading is now close to 200k.  Most of this, however, is text for ops that aren't required for this example.  If I replace the use of the AllOpsResolver (pull all the ops into the interpreter) with a MicroMutableOpResolver, the size is reduced to ~70KB.  For this test, there is an 18KB model and 4KB of data included in the total, so this is about 48KB for the runtime with the ops for the keyword model.

We use the AllOpsResolver in the test currently just for the simplicity of the resulting code.  I've got a cl to change this as described above that we are considering.

What do you consider a reasonable amount of memory usage for a framework like this?

**Comment by csukuangfj** [comment] 2019-09-11 02:05
> What do you consider a reasonable amount of memory usage for a framework like this?

It's very hard to say. In my opinion, I think it depends on the specific application and the target platform.  One rule I believe is that: the smaller, the better; the faster, the better.

Since the architecture of the NN model for a specific application is fixed once it is trained, it is not difficult to write a program to wire them and outperform a general framework both in memory consumption and in speed.

As far as I'm concerned, one of the greatest advantage of lite micro is that it can quickly and easily test a trained tensorflow model on an embedded platform. But if the framework consumes lots of resources, we've to think whether it deserves the effort to develop our own.

**Comment by rockyrhodes** [comment] 2019-09-11 18:24
The change to using the MicroMutableOpResolver was just checked into the code base.  You should now be able to duplicate the results I cited using about 48KB of text for a runtime for the micro_speech_test.

Dan and Pete, is the runtime sizing mentioned in the README file still valid?

**Comment by csukuangfj** [comment] 2019-09-12 02:08
@rockyrhodes 

I'll try it right now.

**Comment by csukuangfj** [comment] 2019-09-16 05:30
@rockyrhodes 

`MicroMutableOpResolver` can indeed decrease the size of the final binary **significantly**.

Thank you

**Comment by rockyrhodes** [comment] 2019-09-16 16:42
Glad you're able to reproduce my results.  I'll keep the issue open for Pete and Dan to decide if the README description is still valid.

**Comment by tensorflowbutler** [comment] 2021-06-10 18:14
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Closed** 2021-06-17 19:22 UTC
Labels: comp:lite, type:bug
