### ISSUE TITLE
TensorFlow grpc tensorflow server build on CentOS 7.2

### ISSUE THREAD

**Issue by araileanu** [tensorflow/tensorflow#2406] opened 2016-05-17 15:21 UTC
### Environment info
Operating System:
Linux 3.10.0-327.13.1.el7.x86_64
CentOS Linux release 7.2.1511 (Core)

Installed version of CUDA and cuDNN: 
CUDA is 7.5 and cuDNN is 4.0.7
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 May 11 22:38 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 May 11 22:38 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 May 12 14:47 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17 May 12 14:47 /usr/local/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 61453024 Feb  8 17:12 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Feb  8 17:12 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0

If installed from sources, provide the commit hash:
Trying to build from sources the distributed version of tensorflow
### Steps to reproduce
1. git clone --recurse-submodules https://github.com/tensorflow/tensorflow
The latest commit hash is 66edcda74c0f4823c9b9e3cddd17db9dfff63ad6
2. installed bazel from binaries
 sh bazel-0.2.2b-installer-linux-x86_64.sh
3. building with bazel fails
bazel build -c opt --config=cuda --verbose_failures --spawn_strategy=standalone --genrule_strategy=standalone //tensorflow/core/distributed_runtime/rpc:grpc_tensorflow_server
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /root/tmp/tensorflow/google/protobuf/BUILD:29:1: undeclared inclusion(s) in rule '//google/protobuf:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'google/protobuf/src/google/protobuf/stubs/once.cc':
  '/include/c++/4.8.5/string'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++config.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/os_defines.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/cpu_defines.h'
  '/include/c++/4.8.5/bits/stringfwd.h'
  '/include/c++/4.8.5/bits/memoryfwd.h'
  '/include/c++/4.8.5/bits/char_traits.h'
  '/include/c++/4.8.5/bits/stl_algobase.h'
  '/include/c++/4.8.5/bits/functexcept.h'
  '/include/c++/4.8.5/bits/exception_defines.h'
  '/include/c++/4.8.5/bits/cpp_type_traits.h'
  '/include/c++/4.8.5/ext/type_traits.h'
  '/include/c++/4.8.5/ext/numeric_traits.h'
  '/include/c++/4.8.5/bits/stl_pair.h'
  '/include/c++/4.8.5/bits/move.h'
  '/include/c++/4.8.5/bits/concept_check.h'
  '/include/c++/4.8.5/type_traits'
  '/include/c++/4.8.5/bits/stl_iterator_base_types.h'
  '/include/c++/4.8.5/bits/stl_iterator_base_funcs.h'
  '/include/c++/4.8.5/debug/debug.h'
  '/include/c++/4.8.5/bits/stl_iterator.h'
  '/include/c++/4.8.5/bits/postypes.h'
  '/include/c++/4.8.5/cwchar'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/include/c++/4.8.5/cstdint'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/include/c++/4.8.5/bits/allocator.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++allocator.h'
  '/include/c++/4.8.5/ext/new_allocator.h'
  '/include/c++/4.8.5/new'
  '/include/c++/4.8.5/exception'
  '/include/c++/4.8.5/bits/atomic_lockfree_defines.h'
  '/include/c++/4.8.5/bits/exception_ptr.h'
  '/include/c++/4.8.5/bits/nested_exception.h'
  '/include/c++/4.8.5/bits/localefwd.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++locale.h'
  '/include/c++/4.8.5/clocale'
  '/include/c++/4.8.5/iosfwd'
  '/include/c++/4.8.5/cctype'
  '/include/c++/4.8.5/bits/ostream_insert.h'
  '/include/c++/4.8.5/bits/cxxabi_forced.h'
  '/include/c++/4.8.5/bits/stl_function.h'
  '/include/c++/4.8.5/backward/binders.h'
  '/include/c++/4.8.5/bits/range_access.h'
  '/include/c++/4.8.5/bits/basic_string.h'
  '/include/c++/4.8.5/ext/atomicity.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr-default.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/atomic_word.h'
  '/include/c++/4.8.5/initializer_list'
  '/include/c++/4.8.5/ext/string_conversions.h'
  '/include/c++/4.8.5/cstdlib'
  '/include/c++/4.8.5/cstdio'
  '/include/c++/4.8.5/cerrno'
  '/include/c++/4.8.5/bits/functional_hash.h'
  '/include/c++/4.8.5/bits/hash_bytes.h'
  '/include/c++/4.8.5/bits/basic_string.tcc'
  '/include/c++/4.8.5/cstddef'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/include/c++/4.8.5/utility'
  '/include/c++/4.8.5/bits/stl_relops.h'.
Target //tensorflow/core/distributed_runtime/rpc:grpc_tensorflow_server failed to build
INFO: Elapsed time: 8.212s, Critical Path: 1.98s

rpm -qa | grep gcc
gcc-c++-4.8.5-4.el7.x86_64
libgcc-4.8.5-4.el7.x86_64
gcc-4.8.5-4.el7.x86_64
rpm -qa | grep glibc
glibc-common-2.17-106.el7_2.4.x86_64
glibc-devel-2.17-106.el7_2.4.x86_64
glibc-2.17-106.el7_2.4.x86_64
glibc-headers-2.17-106.el7_2.4.x86_64

I am not sure what are the dependencies. I saw that glibc 2.17 should at least meet the minimum.

### What have you tried?
1. Nothing else yet. Trying to build bazel from source.

Any thoughts?

**Comment by mrry** [comment] 2016-05-17 18:10
This looks like a duplicate of #2109. Closing this so we can merge the discussion over there (but feel free to reopen if it looks like this is a different issue).

**Closed by mrry** 2016-05-17 18:10 UTC
