### ISSUE TITLE
Tensorboard can't work.

### ISSUE THREAD

**Issue by Channndiii** [tensorflow/tensorflow#1836] opened 2016-04-10 08:11 UTC
### Environment info
Operating System: Mac OS X 10.11.4

Didn't install CUDA.

Under anaconda.

Installed from sources, provide the commit hash:

### Steps to reproduce
1.$ git clone --recurse-submodules https://github.com/tensorflow/tensorflow
2.$ brew install bazel swig
3.$ cd tensorflow/
4.$ ./configure
Please specify the location of python. [Default is /anaconda/lib/python2.7]:
Do you wish to build TensorFlow with GPU support? [y/N] n
5.$ bazel build -c opt --define=use_fast_cpp_protos=true //tensorflow/tools/pip_package:build_pip_package
6.$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tenso
rflow_pkg
7.$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl

### Try
1.$ python tensorflow/tensorflow/tensorboard/tensorboard.py --logdir=path/to/log-directory
didn't work
2.$ tensorboard --logdir=/path/to/log-directory
didn't work 

### Logs or other output that would be helpful

WARNING:tensorflow:IOError [Errno 2] No such file or directory: '//anaconda/lib/python2.7/site-packages/tensorflow/tensorboard/TAG' on path //anaconda/lib/python2.7/site-packages/tensorflow/tensorboard/TAG
WARNING:tensorflow:Unable to read TensorBoard tag
Starting TensorBoard  on port 6006
(You can navigate to http://0.0.0.0:6006)

**Comment by danmane** [comment] 2016-04-14 20:35
"didn't work" - What do you mean? What does TensorBoard display?
I think this may be a duplicate of https://github.com/tensorflow/tensorflow/issues/1421 so I'm closing it. Please re-open it if it's not the same issue.

Also, can you try with the 0.8 release instead of 0.7 and let me know if you still have the issue?

**Closed by danmane** 2016-04-14 20:35 UTC
