### ISSUE TITLE
coord.request_stop() doesn't stop the threads

### ISSUE THREAD

**Issue by ivankreso** [tensorflow/tensorflow#2130] opened 2016-04-27 14:02 UTC
### Environment info
Operating System: Arch Linux

Installed version of CUDA and cuDNN: cuda 7.5 cuDNNv4

If installed from sources, provide the commit hash:
commit cf1659d1c233f8ddbee13fd298464d76e58bdccb

### Steps to reproduce
```
import tensorflow as tf

queue_size = 100
with tf.Graph().as_default():
  sess = tf.Session()
  queue = tf.FIFOQueue(capacity=queue_size, dtypes=tf.int32)
  enqueue_placeholder = tf.placeholder(dtype=tf.int32)
  enqueue_op = queue.enqueue(enqueue_placeholder)
  dequeue_op = queue.dequeue()
  for f in range(queue_size):
    sess.run([enqueue_op], feed_dict={enqueue_placeholder: f})
  queue.close()

  dequeue_op = tf.reshape(dequeue_op, shape=[1])
  queue_batch = tf.train.batch([dequeue_op], batch_size=1, num_threads=1, capacity=64)

  coord = tf.train.Coordinator()
  threads = tf.train.start_queue_runners(sess=sess, coord=coord)

  for i in range(queue_size):
    print(sess.run([queue_batch]))

  coord.request_stop()
  coord.join(threads, stop_grace_period_secs=5)
  sess.close()
```

### What have you tried?
https://www.tensorflow.org/versions/r0.8/how_tos/reading_data/index.html#creating-threads-to-prefetch-using-queuerunner-objects

According to documentation coord.request_stop() should stop the threads but in this case
we get a deadlock in coord.join().

### Logs or other output that would be helpful
```
...
[array([[97]], dtype=int32)]
[array([[98]], dtype=int32)]
[array([[99]], dtype=int32)]
Traceback (most recent call last):
  File "test_queue.py", line 26, in <module>
    sess.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3213, in get_controller
    yield default
  File "test_queue.py", line 25, in <module>
    coord.join(threads, stop_grace_period_secs=5)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 289, in join
    " ".join(stragglers))
RuntimeError: ('Coordinator stopped with threads still running: %s', 'Thread-1')
```

If I put sess.close() before coord.join() the threads are killed but there is still a weird warning which should not exist because I called queue.close() before.
```
...
W tensorflow/core/kernels/queue_base.cc:300] _0_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
```

**Comment by yaroslavvb** [comment] 2016-04-27 15:23
I can reproduce. Thanks for giving self-contained repro, this is super helpful. Looking

**Comment by yaroslavvb** [comment] 2016-04-27 18:18
Oh...you are calling "queue.close()", but that actually returns an op which needs to be run to do anything. You need to do `sess.run(q.close())`. Since your first queue is not closed, your "batch" queue is waiting forever for something to be added to the first queue.

Furthermore, this wait is happening in C++ mutex, so `stop_grace_period_secs` is useless -- the queue runner thread checks for "stop_requested" between session `run` calls, but because dequeue op never returns, it's stuck inside `session.run` forever.

Here's the simpler example I made for myself to reproduce this

```
def create_session():
  """Resets local session, returns new InteractiveSession"""

  config = tf.ConfigProto(log_device_placement=True)
  config.gpu_options.per_process_gpu_memory_fraction=0.3 # don't hog all vRAM
  config.operation_timeout_in_ms=5000   # terminate on long hangs
  sess = tf.InteractiveSession("", config=config)
  return sess

tf.reset_default_graph()
q = tf.FIFOQueue(4, tf.string)
enqueue_val = tf.placeholder(dtype=tf.string)
enqueue_op = q.enqueue(enqueue_val)
size_op = q.size()
dequeue_op = q.dequeue()
sess = create_session()
def enqueueit(val):
  sess.run([enqueue_op], feed_dict={enqueue_val:val})
  print "queue1 size: ", sess.run(size_op)
enqueueit("1")
enqueueit("2")
enqueueit("3")
#sess.run(q.close())

dequeue_op.set_shape([])
queue2 = tf.train.batch([dequeue_op], batch_size=1, num_threads=1, capacity=1)
threads = tf.train.start_queue_runners()

def dequeueit():
  print "queue1 size: ", sess.run(size_op)
  print "queue2 size before: ", sess.run("batch/fifo_queue_Size:0")
  print "result: ", sess.run(queue2)
  print "queue2 size after: ", sess.run("batch/fifo_queue_Size:0")

dequeueit()
dequeueit()
dequeueit()
coord.request_stop()
coord.join(threads, stop_grace_period_secs=5)
```

**Comment by yaroslavvb** [comment] 2016-04-27 18:22
So I guess the problem is that there's no way to stop a thread from Python if a thread is stuck inside of a `session.run` call. One work-around is to create session with `config.operation_timeout_in_ms` as above

**Comment by yaroslavvb** [comment] 2016-04-28 02:49
closing since it doesn't seem to be possible to fix this besides the work-around given

**Closed by yaroslavvb** 2016-04-28 02:49 UTC

**Comment by ivankreso** [comment] 2016-04-28 11:34
Thanks a lot @yaroslavvb! I somehow missed the queue.close() bug.

I fixed my training code and everything works now.
I need to handle data manualy in order to perform validation after each epoch as I have only one Titan X :)
There was one more thing I had to fix in my training code.
In all official examples the summary operation is run like this:
```
      if step % 100 == 0:
        summary_str = sess.run(summary_op)
        summary_writer.add_summary(summary_str, step)
```
This means that every 100th image is skipped in applying the training operation because ordinary summary_op includes the loss operation and subsequently the whole forward pass.
I uderstand this is not an issue when using the shuffled version of tf.train.string_input_producer but  it becomes a problem when handing queues manually because summary_op will dequeue and you need to count it as a full iteration.
I fixed it by simply running summary_op and train_op jointly:
```
      if step % 100 == 0:
        _, loss_value, summary_str = sess.run([train_op, loss, summary_op])
        summary_writer.add_summary(summary_str, global_step_val)
      else:
        _, loss_value = sess.run([train_op, loss])
```

I think it would be useful if Tensorflow documentation or source code contaned an example of how to train and validate (after each epoch) the model on single GPU. A lot of people have limiting resources and they can't reserve one GPU only for validation. If you want I can send you a simplified version of my implementation.

**Comment by yaroslavvb** [comment] 2016-04-28 16:29
You are saying we have documentation that tells people to train/validate on separate GPUs? Which one is it? Meanwhile, you could also post your implementation as a comment here, and I'll reference as it comes up in issues/stackoverflow questions, etc

**Comment by ivankreso** [comment] 2016-04-29 12:25
Documentation is great. It was a wrong impression on my side regarding code examples. There are examples on how to train and evaluate on single GPU like:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/mnist/convolutional.py

My mistake was that I was using an older version of Slim wrapper which didn't have support for variable reuse which lead me to completely forget about reuse mechanism. This was a problem because some layers behave differently in inference mode (like batch normalization) and there was no option to define two versions of the same network using different is_training flag in older Slim. In the end I wrote a code which saves, rebuilds and restores a graph from scratch each epoch which is still a good workaround as the time to do this is negligible compared to all the forward and backward passes. Now I found out that Slim supports variable reuse and I just tested it and it works.

Thanks for help!

**Comment by davidparks21** [comment] 2017-03-22 22:08
To add to this discussion, to get a clean shutdown, this was the command I needed:

`sess.run(model.queue.close(cancel_pending_enqueues=True))`

**Comment by tangqiqi123** [comment] 2017-09-23 03:15
@davidparks21 I solve the problem "RuntimeError: ('Coordinator stopped with threads still running: %s', 'Thread-1') " using your method. But I met a new error: RuntimeError: Graph is finalized and cannot be modified.Can you help me ? Thanks
