### ISSUE TITLE
Is it possible to use the autograph-compiled code on older Tensorflow versions?

### ISSUE THREAD

**Issue by phizaz** [tensorflow/tensorflow#21972] opened 2018-08-30 10:53 UTC
### Describe the problem
I have tried autograph on the nightly channel. It works and is very useful to me. I could not hope to write such code myself. However, it is not a very good idea to stay on the nightly channel for the whole time. Since autograph can generate the code, it seems natural to me to use such code and migrate back to a more stable channel. 

However, the generated code doesn't seem to be readily usable. It contains unrecognized tokens like `__ag`. I cannot get past that. Is it even possible? Can you disclose some of the plans on that?

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment] 2018-08-31 22:34
@aquariusjay @alexbw can you comment on whether working at nightly is the intended use-method for AG, or reassign to someone who can, please?

**Comment by alexbw** [comment] 2018-09-03 22:03
Hey @phizaz great to hear that AutoGraph is useful to you. If you are able, we'd love if you could share the code that you used it in!
We're still actively working on AutoGraph, so to get the most out of it (before TF 2.0 is released), staying on nightly gets you the most bug-fixes and functionality. 
However, if that's not possible, try using the 1.10 release or later.

**Comment by phizaz** [comment] 2018-09-04 06:02
@alexbw r1.10 doesn't seem to support list appending and `tf.stack`. However, I found it work on r1.11 (compiled from source).

I think I could share the code here, I simplify the code a bit:

```
@autograph.convert()
def chunkify(tensor, max_chunk_size):
    Agrs:
        tensor: the tensor to be chunked
        max_chunk_size: maximum size of a chunk
    """
    s = tf.shape(tensor)
    i = 0
    out = []
    autograph.set_element_type(out, tensor.dtype)

    while i < s[0]:
        # cut a new tensor
        t = tensor[i:i+max_chunk_size]

        ...

        out.append(t)
        i += max_chunk_size

    out = tf.stack(out)

    return out
```

**Comment by alexbw** [comment] 2018-09-04 13:39
@mdanatg

**Comment by tensorflowbutler** [comment] 2018-09-19 12:47
Nagging Assignee @aquariusjay: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-04 19:06
Nagging Assignee @aquariusjay: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-03 12:32
Nagging Assignee @aquariusjay: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:48
Nagging Assignee @aquariusjay: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:54
Nagging Assignee @aquariusjay: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mdanatg** [comment] 2019-02-14 16:43
Now that the stable release reached 1.13, I believe you will find the basic autograph functionality in the stable branch.

**Closed by mdanatg** 2019-02-14 16:43 UTC
