### ISSUE TITLE
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#21362] opened 2018-08-03 17:35 UTC
Version 1.10.0-rc1
bazel-0.15.0

**Comment by tensorflowbutler** [comment] 2018-08-04 01:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by yurivict** [comment] 2018-08-04 02:04
I got this during the FreeBSD port build ob FreeBSD 11.2. But now I think that this is a bazel bug. Please feel free to close.

FYI: The other report I posted today is actually a show-stopper: https://github.com/tensorflow/tensorflow/issues/21366

**Comment by tensorflowbutler** [comment] 2018-08-19 18:50
Nagging Assignee @tatatodd: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-03 18:39
Nagging Assignee @tatatodd: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Tahirhan** [comment] 2018-09-09 15:42
try invoking the command in your "tensorflow" directory. I was getting the same error when i was in different directory.

**Comment by tensorflowbutler** [comment] 2018-09-24 12:47
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment] 2018-10-05 21:18
Closing this issue for now.

**Closed by wt-huang** 2018-10-05 21:18 UTC

**Comment by boegel** [comment] 2018-11-13 15:16
I'm still seeing this with TensorFlow 1.12.0. Why was this closed while this problem hasn't been fixed?

**Comment by pyaf** [comment] 2019-02-28 15:47
Still facing this issue in 1.13.1

**Comment by VishvajeetRamanuj** [comment] 2019-03-21 06:11
I am facing this issue too.
when i am installing tensorflow from source https://www.tensorflow.org/install/source 
on running bellow line i get error
./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.23.0 installed.
Please downgrade your bazel installation to version 0.21.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.

Have I written custom code
OS Platform and Distribution = Ubuntu 18.04 LTS
TensorFlow installed from = source
TensorFlow version = could not able to install  because of this error
Bazel version = tried 0.21 and 0.23
CUDA/cuDNN version = NA
GPU model and memory = NA
Exact command to reproduce = NA
Mobile device = NA
