### ISSUE TITLE
File system scheme 's3' not implemented

### ISSUE THREAD

**Issue by kumaradi08** [tensorflow/tensorflow#40302] opened 2020-06-09 04:33 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented

**Describe the expected behavior**
Should be able to connect the s3 filesystem.

**Standalone code to reproduce the issue**
from tensorflow.python.lib.io import file_io
print file_io.stat('s3://bucketname/path/')

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2020-06-09 18:55
Can you try with the final 2.2 release please?

**Comment by mihaimaruseac** [comment] 2020-06-09 20:17
Oh. You are using Windows. Windows does not yet support S3 filesystems, but there is a GSoC project to enable that.

**Comment by mihaimaruseac** [comment] 2020-06-11 16:08
#39124 will be included in the upcoming 2.3 release.

Modular filesystems (tensorflow/community#101) will probably come in 2.4

**Comment by vaibhavsingh007** [comment] 2020-07-14 19:12
Hi, I'm facing the exact same error with s3a://
My tf version is: 2.1.0

Please help

**Comment by vaibhavsingh007** [comment] 2020-07-14 20:28
Also, I can read **s3a://<path>/wine-quality.csv** using Spark.

**Comment by vaibhavsingh007** [comment] 2020-07-14 20:29
Also, I can read s3**a**://path/to/wine-quality.csv using Spark.

**Comment by mihaimaruseac** [comment] 2020-07-15 23:41
@vaibhavsingh007 we only implement support for the `s3://` URI scheme. Didn't know there is a `s3a://` too. Do you know what are the differences?

**Comment by vaibhavsingh007** [comment] 2020-07-16 15:44
Yes, s3a is the latest protocol and is more performant than its predecessors s3/s3n: https://stackoverflow.com/questions/33356041/technically-what-is-the-difference-between-s3n-s3a-and-s3

Would you know if or when we may expect TF to S3 functionality become available?

**Comment by mihaimaruseac** [comment] 2020-07-16 16:16
There is funcionality for basic `s3://` scheme on Linux. Then there is work for tensorflow/community#101 to convert all these filesystem to a plugin based form so they can be used on all platforms, on demand.

Regarding `s3a` and `s3n`, can you file a new issue, feature request type, and assign it to me/mention me? just to keep this issue only for the `s3` not implemented error.

**Comment by vaibhavsingh007** [comment] 2020-07-16 16:59
Done. Seems the bot auto assigned and I can't change the assignee.

**Comment by mihaimaruseac** [comment] 2020-07-16 17:10
Thank you. Yes, the bot assigns oncall for triage.

**Comment by vaibhavsingh007** [comment] 2020-07-16 21:44
So @mihaimaruseac I wanted to draw our attention back to the original issue of not being able to write to S3 from TF using s3://.. 

I get the error _NotFoundError: Object s3://<path>/wine-quality.csv does not exist_ (from the post above).

**Comment by mihaimaruseac** [comment] 2020-07-17 02:29
Hmm, what would be the output of `tf.io.gfile.exists` on that path?

**Comment by vaibhavsingh007** [comment] 2020-07-20 16:46
o/p of above is 'False'. 
Also, I was able to get some backend logs for the stat call, in case it helps: 

![image](https://user-images.githubusercontent.com/4958034/87963548-7e303500-ca7e-11ea-88bb-10212cd34dcf.png)

**Comment by vaibhavsingh007** [comment] 2020-07-20 16:48
And I'm setting these auth vars:

```
os.environ["AWS_ACCESS_KEY_ID"]="***"
os.environ["AWS_SECRET_ACCESS_KEY"]="***"
os.environ["AWS_REGION"]="us-east-1"
```

**Comment by vaibhavsingh007** [comment] 2020-07-23 14:43
@mihaimaruseac any luck?

**Comment by mihaimaruseac** [comment] 2020-07-23 16:00
Sorry, didn't have time to look more into this. Can you manually issue the `curl` requests?

**Comment by vaibhavsingh007** [comment] 2020-07-23 17:10
Well like I said can access the said files using s3a:// via Spark. But let me try curling as well.

**Comment by vaibhavsingh007** [comment] 2020-07-23 21:17
@mihaimaruseac I couldn't set up curl, but successfully read file using aws api via boto3. Here is a snapshot: 

![image](https://user-images.githubusercontent.com/4958034/88334162-f3a63a80-ccf6-11ea-8125-ba8cb2f7c2fa.png)

**Comment by vaibhavsingh007** [comment] 2020-07-24 14:40
Would you like to share a sample code to test read from private (secured) s3 repo using TF? I hope I am using the correct auth configuration (shared before). 

> And I'm setting these auth vars:
> 
> ```
> os.environ["AWS_ACCESS_KEY_ID"]="***"
> os.environ["AWS_SECRET_ACCESS_KEY"]="***"
> os.environ["AWS_REGION"]="us-east-1"
> ```

**Comment by mihaimaruseac** [comment] 2020-07-24 18:24
Current implementation uses curl to handle the requests to the S3 API. The modular filesystem approach that is currently in the works would use awscpp.

But until then, I think we need to differentiate between TF error and curl error.

**Comment by vaibhavsingh007** [comment] 2020-07-29 15:40
Hi, I am not sure I understand what you mean by 'differentiate between TF error and curl error'. Is there something else you want me to try since we still cannot read/write to S3 using TF.

**Comment by mihaimaruseac** [comment] 2020-07-29 17:20
Can you intercept the requests TF makes during `tf.io.gfile.file_exists` on the path and then try playing them manually via `curl`? Looking at the provided logs it looks like there is a failure on the server / invalid credentials/cookies/arguments get sent.

**Comment by vaibhavsingh007** [comment] 2020-07-29 18:41
Would you be able to direct me how I can do that?

**Comment by mihaimaruseac** [comment] 2020-07-29 18:52
Hmm, I was wrong, it seems we are already using AWS library not issuing curl requests manually

https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/platform/s3/s3_file_system.cc;l=707-766;drc=791f4f2b773208b21ece71e1d37204a91720346d

You could intercept the traffic using wireshark or if you can compile from source, I'd recommend adding some debug prints in the function I linked above.

Unfortunately I currently don't have access to an S3 bucket and won't be able to look much into this issue until mid of August. Apologies for the delay

**Comment by mihaimaruseac** [comment] 2020-07-31 18:21
Question: can you compile TF from source? Or parts of TF.

We have an experimental plugin for S3 support that might be easier to use than the existing non-modular approach. But at the moment it requires manual compile.

**Comment by vaibhavsingh007** [comment] 2020-08-10 16:50
Hi @mihaimaruseac sorry for the delay. 
I'm not sure we can do that but I may try. Can you share more details about the new API?

**Comment by mihaimaruseac** [comment] 2020-08-11 16:23
Hi.

We are planning to modularize filesystems in TF and only offer the local filesystem by default in the pip package, requiring every other filesystem to be loaded at runtime from a shared library. RFC is at https://github.com/tensorflow/community/blob/master/rfcs/20190506-filesystem-plugin-modular-tensorflow.md and currently the implementation is at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/c/experimental/filesystem

I would suggest compiling the S3 plugin from the experimental filesystem and then using `tf.load_library` to load the shared object.

**Comment by andreys42** [comment] 2020-10-30 12:37
can you please describe steps to do for implementing s3 filesystem on winows platform or it still require loading shared library at runtime?

**Comment by mihaimaruseac** [comment] 2020-11-02 18:58
Compiling the plugin in https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/experimental/filesystem/plugins/s3/;drc=75a455a9416630e4a33d23b4dc27bbbdb9c75f41 gives you a shared object that you then load at runtime.

This should work on all operating systems.

**Comment by vnvo2409** [comment] 2020-12-20 11:37
The `s3` filesystem is available on windows by install `pip install tensorflow-io==0.17`. Could you give it a try ? Note that in order to avoid conflicts with current `s3` in TensorFlow, it is accessible by `s3e` uri, i.e `s3e://bucket/key`.

Example : https://github.com/tensorflow/io/blob/master/tests/test_s3_eager.py

**Comment by saikumarchalla** [comment] 2021-05-25 11:51
@kumaradi08 @vaibhavsingh007  As per the mihai latest comment, it should work on all Operating systems.  Could you please confirm and if yes, Please go ahead and close the issue if you don't have any further queries.Thanks!

**Comment by vnvo2409** [comment] 2021-05-25 11:55
@saikumarchalla @kumaradi08 @vaibhavsingh007 Actually there is one more issue https://github.com/tensorflow/tensorflow/issues/49515 which will be fixed by #49520.

**Closed** 2021-08-05 19:05 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:apis, TF 2.2

**Comment by alexcpn** [comment] 2021-08-25 09:27
This is there in 2.6 version of tensorflow

"tensorflow/tensorflow:2.6.0"

```
File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 2219, in set_model
    self._write_keras_model_summary()
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 2258, in _write_keras_model_summary
    with self._train_writer.as_default():
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 2228, in _train_writer
    self._train_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py", line 554, in create_file_writer_v2
    create_fn=create_fn, init_op_fn=init_op_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py", line 313, in __init__
    self._init_op = init_op_fn(self._resource)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_summary_ops.py", line 146, in create_summary_file_writer
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented (file: 's3://tfboard/logs/20210825-092239/train') [Op:CreateSummaryFileWriter]
```

**Comment by rbavery** [comment] 2021-09-03 21:30
I'm also getting the above error with Tensorflow 2.6

```
writer = tf.io.TFRecordWriter(tf_record_path)
```

```
Exception has occurred: UnimplementedError
File system scheme 's3' not implemented (file: 's3://ffda-poi/training_data/mauritania_by_areas/rural/od/large_tfrecords/train_mauritania_rural_od_large_training_data_001.tfrecords')
  File "/tfrecords/write_tfrecords_od.py", line 219, in write_tfrecord_file
    writer = tf.io.TFRecordWriter(tf_record_path)
  File "/tfrecords/write_tfrecords_od.py", line 280, in write_tfrecord_od
    write_tfrecord_file(train_df, tile_path, record_file_train, super_tile_size)
  File "/tfrecords/write_tfrecords_od.py", line 318, in main
    write_tfrecord_od(csv_file, output_dir, tile_path, super_tile_size, geojson_with_neg_path)
  File "/tfrecords/write_tfrecords_od.py", line 322, in <module>
    main()
```

**Comment by rbavery** [comment] 2021-09-03 21:48
I can confirm this error does not happen if I install tensorflow 2.3

**Comment by mihaimaruseac** [comment] 2021-09-14 08:10
> The `s3` filesystem is available on windows by install `pip install tensorflow-io==0.17`. Could you give it a try ? Note that in order to avoid conflicts with current `s3` in TensorFlow, it is accessible by `s3e` uri, i.e `s3e://bucket/key`.
> 
> Example : https://github.com/tensorflow/io/blob/master/tests/test_s3_eager.py

This should be the solution here. For cloud filesystems you have to also install the SIG IO wheel.
