### ISSUE TITLE
build micro_speech error

### ISSUE THREAD

**Issue by goog** [tensorflow/tensorflow#29208] opened 2019-05-31 11:28 UTC
Deep Learning VM  images/tf-2-0-cpu-experimental-20190502
```bash
googcheng@tensorflow-4-vm:~$ git clone https://github.com/tensorflow/tensorflow.git
Cloning into 'tensorflow'...
remote: Enumerating objects: 2167, done.
remote: Counting objects: 100% (2167/2167), done.
remote: Compressing objects: 100% (845/845), done.
remote: Total 598119 (delta 1392), reused 1643 (delta 1320), pack-reused 595952
Receiving objects: 100% (598119/598119), 343.85 MiB | 47.04 MiB/s, done.
Resolving deltas: 100% (483846/483846), done.
googcheng@tensorflow-4-vm:~$ ls
tensorflow
googcheng@tensorflow-4-vm:~$ cd tensorflow/
googcheng@tensorflow-4-vm:~/tensorflow$ ls
ACKNOWLEDGMENTS     AUTHORS             CODEOWNERS    CONTRIBUTING.md    LICENSE       RELEASE.md   third_party
ADOPTERS.md         BUILD               configure     ISSUES.md          models.BUILD  SECURITY.md  tools
arm_compiler.BUILD  CODE_OF_CONDUCT.md  configure.py  ISSUE_TEMPLATE.md  README.md     tensorflow   WORKSPACE
googcheng@tensorflow-4-vm:~/tensorflow$ bazel run -c opt --copt=-mavx2 --copt=-mfma \
> tensorflow/examples/speech_commands:train -- \
> --model_architecture=tiny_conv --window_stride=20 --preprocess=average \
> --wanted_words="yes,no" --silence_percentage=25 --unknown_percentage=25 --quantize=1
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=112
INFO: Reading rc options for 'run' from /home/googcheng/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
ERROR: /home/googcheng/.cache/bazel/_bazel_googcheng/c7d71bbdf8501e4441f5b58bb2db4ae1/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined (did you mean 'protos'?)
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
INFO: Elapsed time: 5.973s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
googcheng@tensorflow-4-vm:~/tensorflow$ git log
commit 94feeb1c0ade3c673a758c0794e19c82b6e868b6
Author: Tiezhen WANG <wangtz@google.com>
Date:   Fri May 31 03:18:30 2019 -0700

    nit remove unnecessary indirection in all_ops_resolver.
    
    PiperOrigin-RevId: 250856298

commit b1a535b3abc11de5e00f5b40b2a7f795b7160376
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Fri May 31 02:49:19 2019 -0700

    Test that tf.saved_model.load() does not add to the TRAINABLE_VARIABLES
    collection and add a comment why. There is no change in behavior.
```

**Comment by achandraa** [comment] 2019-06-06 12:38
Please help us to know whether you were able to import TensorFlow. Also let us know what platform (operating system etc) you are using. Thanks!

**Comment by goog** [comment] 2019-06-10 01:10
Welcome to the Google Deep Learning VM
======================================
Version: tf-cpu.1-13.m26
Based on: Debian GNU/Linux 9.9 (stretch) (GNU/Linux 4.9.0-9-amd64 x86_64\n)
Resources:
 * Google Deep Learning Platform StackOverflow: https://stackoverflow.com/questi
ons/tagged/google-dl-platform
 * Google Cloud Documentation: https://cloud.google.com/deep-learning-vm
 * Google Group: https://groups.google.com/forum/#!forum/google-dl-platform

**Comment by goog** [comment] 2019-06-10 01:13
@achandraa  the train need existed tensorflow install ?

**Comment by achandraa** [comment] 2019-06-10 08:26
@goog : Looks like this is a duplicate of issue #29206 . Can we track resolution to that issue and close on this. This would help us to track better. Thanks!

**Closed** 2019-06-10 09:16 UTC
Labels: 2.0, stat:awaiting response
