### ISSUE TITLE
undefined symbol: _ZTVN6icu_639ErrorCodeE while building v1.12.2

### ISSUE THREAD

**Issue by yrenier** [tensorflow/tensorflow#28900] opened 2019-05-21 09:44 UTC
**System information**
- Debian 10.0
- TensorFlow installed from source
- TensorFlow version: v1.12.2
- Python version: 3.5.4
- Bazel version: 0.15.2
- GCC/Compiler version (if compiling from source): gcc 7.4.0
- CUDA 9.2, cuDNN 7
- GPU model and memory: GeForce 940MX, 2Go

The build fails with : 
```
ERROR: /opt/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash failed: error executing command 
  (cd /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr \
    CUDNN_INSTALL_PATH=/usr/local/cuda/lib64 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc-7 \
    NCCL_HDR_PATH=/usr/include \
    NCCL_INSTALL_PATH=/usr/lib/x86_64-linux-gnu \
    PATH=/home/yves/anaconda3/envs/digicampipe/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/yves/anaconda3/bin:/home/yves/coin/monero/monero/build/release/bin/ \
    PYTHON_BIN_PATH=/home/yves/anaconda3/envs/digicampipe/bin/python \
    PYTHON_LIB_PATH=/home/yves/anaconda3/envs/digicampipe/lib/python3.5/site-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.0 \
    TF_CUDA_VERSION=9.2 \
    TF_CUDNN_VERSION=7 \
    TF_NCCL_VERSION=2 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1 --root_init_template=tensorflow/api_template.__init__.py --apidir=bazel-out/k8-opt/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --package=tensorflow.python --output_package=tensorflow._api.v1 bazel-out/k8-opt/genfiles/tensorflow/_api/v1/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/app/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/bitwise/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/compat/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/data/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/data/experimental/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/debugging/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/distributions/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/dtypes/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/errors/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/feature_column/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/gfile/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/graph_util/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/image/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/io/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/initializers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/activations/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/densenet/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_v3/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/nasnet/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/resnet50/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg16/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg19/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/applications/xception/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/backend/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/callbacks/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/constraints/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/boston_housing/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar10/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar100/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/imdb/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/mnist/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/datasets/reuters/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/estimator/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/initializers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/layers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/losses/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/metrics/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/models/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/optimizers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/image/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/sequence/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/text/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/regularizers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/utils/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/wrappers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/layers/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/linalg/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/logging/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/losses/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/manip/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/math/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/metrics/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/nn/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/nn/rnn_cell/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/profiler/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/python_io/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/quantization/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/random/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/resource_loader/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/strings/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/builder/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/constants/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/loader/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/main_op/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/signature_constants/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/signature_def_utils/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/tag_constants/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/saved_model/utils/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/sets/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/sparse/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/spectral/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/summary/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/sysconfig/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/test/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/train/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/train/queue_runner/__init__.py bazel-out/k8-opt/genfiles/tensorflow/_api/v1/user_ops/__init__.py')
Traceback (most recent call last):
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yves/anaconda3/envs/digicampipe/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yves/anaconda3/envs/digicampipe/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTVN6icu_639ErrorCodeE
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/yves/anaconda3/envs/digicampipe/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/yves/anaconda3/envs/digicampipe/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTVN6icu_639ErrorCodeE
 Failed to load the native TensorFlow runtime.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem** :
```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

**Any other info / logs**
```
$ldd /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
	linux-vdso.so.1 (0x00007ffe132c4000)
	libtensorflow_framework.so => /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/../../_solib_local/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow/libtensorflow_framework.so (0x00007f3a9c170000)
	libcublas.so.9.2 => /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccublas___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcublas.so.9.2 (0x00007f3a983a0000)
	libcusolver.so.9.2 => /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccusolver___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcusolver.so.9.2 (0x00007f3a90f5f000)
	libcudart.so.9.2 => /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/../../_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudart.so.9.2 (0x00007f3a90cf5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3a90cc0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3a90c9f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f3a90c6c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3a90ae9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3a90adf000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3a9095b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3a90941000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3a90780000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3aaa5db000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f3a8f625000)
	libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7 (0x00007f3a7e694000)
	libcufft.so.9.2 => /usr/lib/x86_64-linux-gnu/libcufft.so.9.2 (0x00007f3a7903a000)
	libcurand.so.9.2 => /usr/lib/x86_64-linux-gnu/libcurand.so.9.2 (0x00007f3a750fc000)
	libnvidia-fatbinaryloader.so.418.56 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.418.56 (0x00007f3a74eae000)
```

```
$nm -A /usr/lib/x86_64-linux-gnu/libicu*.a | grep _ZTVN6icu_639ErrorCodeE
/usr/lib/x86_64-linux-gnu/libicui18n.a:decimfmt.ao:                 U _ZTVN6icu_639ErrorCodeE
nm: wintzimpl.ao: no symbols
nm: windtfmt.ao: no symbols
nm: winnmfmt.ao: no symbols
/usr/lib/x86_64-linux-gnu/libicui18n.a:number_mapper.ao:                 U _ZTVN6icu_639ErrorCodeE
/usr/lib/x86_64-linux-gnu/libicuuc.a:errorcode.ao:0000000000000000 V _ZTVN6icu_639ErrorCodeE
nm: cwchar.ao: no symbols
nm: wintz.ao: no symbols
nm: icuplug.ao: no symbols
```

```
nm /home/yves/.cache/bazel/_bazel_yves/fbc06f9baef46cade6e35d9e4137e37c/execroot/org_tensorflow/bazel-out/host/bin/external/icu/libicuuc.pic.a | grep _ZTVN6icu_ | grep ErrorCode
0000000000000000 V _ZTVN6icu_629ErrorCodeE
```

**Comment by yrenier** [comment] 2019-05-21 13:51
For anyone having the same issue, I succeeded to compile Tensorflow by modifying third_party/icu/workspace.bzl in such a way that bazel would install the same version as the one already installed on the system.

Still there must be something wrong somewhere which make the building of Tensorflow using system icu while it tries to use the icu from bazel during linking.

**Comment by mihaimaruseac** [comment] 2019-05-21 14:09
Can you post the diff of the change you did to `third_party/icu/workspace.bzl`? This will ensure people hitting the same issue can find the workaround

**Comment by yrenier** [comment] 2019-05-21 18:16
Sure, here it is:
[diff.txt](https://github.com/tensorflow/tensorflow/files/3203888/diff.txt)

In order to get what to put after "sha256 =", I downloaded the release-63-2.tar.gz file and used sha256sum on it.

**Comment by mihaimaruseac** [comment] 2019-05-21 18:20
Thanks.

Looking again at the stack trace and error message I think this is caused by something escaping the conda environment.

**Comment by ymodak** [comment] 2019-05-29 22:51
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-05-29 22:51 UTC
Labels: stat:awaiting response, subtype: ubuntu/linux, subtype:bazel, type:build/install

**Comment by duanyao** [comment] 2020-01-13 07:29
Recently I encoutered this issue too on deepin linux 15.11 (like debian 9).
My workaround is removing system-wide libicu-dev package so that TF build system can't detect it:
```
sudo dpkg -r --force-depends libicu-dev
```
Note that `bazel clean --expunge` is required before continuing TF build.
After TF was built, libicu-dev may be reinstalled.
