### ISSUE TITLE
error when exit kernel

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#44192] opened 2020-10-21 04:51 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0 master
- Python version: 3.7.9
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source):  7.5.0
- CUDA/cuDNN version: 11.1 / 8.0.4
- GPU model and memory: tesla P100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
start python and import tensorflow and exit

**Describe the expected behavior**
no error messages

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-10-21 13:48:47.162423: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>>
>>> exit()
Exception ignored in: <function Buckets.__del__ at 0x7f8b017e2830>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-10-21 13:08
@alanpurple,
I did not face any errors with TF v2.3 and TF-nightly. Please find the attached screenshots for reference. 

![Screenshot 2020-10-21 at 6 21 09 PM](https://user-images.githubusercontent.com/57165142/96723593-5c6f8280-13cc-11eb-9282-63776579c13d.png)

![Screenshot 2020-10-21 at 6 23 57 PM](https://user-images.githubusercontent.com/57165142/96723610-62656380-13cc-11eb-8d3a-f23554b7f16b.png)

Looks like you are running the commands inside the Anaconda environment, could you please check if you are facing the same issue outside the Anaconda environment as well? Thanks!

**Comment by dbonner** [comment] 2020-10-21 23:13
I can confirm that this bug occurs with:
1) TensorFlow built from source (master, 2.4.0)
2) Conda environment running python 3.7.9
This is quite new.  I built from master 2.4.0 a few days ago and this error did not occur.
Cheers

**Comment by dbonner** [comment] 2020-10-22 06:11
@amahendrakar I can see you don't seem to be getting this error with python 3.8.5.  Maybe it is a problem with the tf-nightly for python 3.7.
I have also confirmed this bug occurs with:
1. tf_nightly-2.4.0.dev20201021-cp37-cp37m-manylinux2010_x86_64.whl (pip install tf-nightly)
2. Conda environment running python 3.7.9 (I also tried a conda environment running python 3.7.8 and the bug persists)
It also occurs with:
1. tf_nightly-2.4.0.dev20201021-cp37-cp37m-manylinux2010_x86_64.whl (pip install tf-nightly)
2. Virtual environment created with the standard python module venv using python 3.7.9 from pyenv (python -m venv trialvenv)
I can see that

**Comment by dbonner** [comment] 2020-10-22 15:31
The bug also occurs with:

- tf_nightly-2.4.0.dev20201022     (recently released)
- Conda environment running python 3.7.9

The bug does not occur with tf_nightly-dev20201020 and previous tf_nightly's so it is new.

**Comment by huberemanuel** [comment] 2020-10-23 18:32
The bug also occurs with tf_nightly-2.4.0-dev20201023

**Comment by kabartay** [comment] 2020-10-26 12:28
The bug still propages to next versions and appears with tf-nightly 2.5.0.dev20201026

**Comment by DEKHTIARJonathan** [comment] 2020-10-26 23:24
I confirm I can also see the issue in the docker container `docker pull tensorflow/tensorflow:nightly-gpu` built yesterday: https://hub.docker.com/layers/tensorflow/tensorflow/nightly-gpu/images/sha256-a878f2a5309a037229b8b0002ae8cd0243ca0016e2716e6ebc54192d356f7ed2?context=explore

**Comment by kabartay** [comment] 2020-10-27 08:52
Just use tensorflow==2.3.1

**Comment by mihaimaruseac** [comment] 2020-10-27 19:10
Was able to reproduce

```
mihaimaruseac@ankh:/tmp$ python3.7 -m venv venv
mihaimaruseac@ankh:/tmp$ source venv/bin/activate
(venv) mihaimaruseac@ankh:/tmp$ pip install -q tf-nightly
(venv) mihaimaruseac@ankh:/tmp$ pip list | grep tf
tf-estimator-nightly   2.4.0.dev2020102301
tf-nightly             2.5.0.dev20201027
(venv) mihaimaruseac@ankh:/tmp$ python
Python 3.7.7 (default, May 20 2020, 19:38:38) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-10-27 12:09:10.257298: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-10-27 12:09:10.257332: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> exit()
Exception ignored in: <function Buckets.__del__ at 0x7f47dfd2de60>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
(venv) mihaimaruseac@ankh:/tmp$ python -c "import tensorflow as tf"
2020-10-27 12:09:39.451204: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-10-27 12:09:39.451246: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Exception ignored in: <function Buckets.__del__ at 0x7fa003a6a560>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
```

Looking into this

**Comment by mihaimaruseac** [comment] 2020-10-27 19:42
Note though that the message is just a warning about an ignored exception. Exit code is still success

```
(venv) mihaimaruseac@ankh:/tmp$ python -c "import tensorflow as tf"
2020-10-27 12:23:51.950878: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-10-27 12:23:51.950930: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Exception ignored in: <function Buckets.__del__ at 0x7fb5abc5e560>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
(venv) mihaimaruseac@ankh:/tmp$ echo $?
0
```

**Comment by amahendrakar** [comment] 2020-10-28 16:47
@alanpurple,
Any updates regarding this? Please take a look at the above comment and let us know if this is still an issue. Thanks!

**Comment by alanpurple** [comment] 2020-10-29 01:23
@amahendrakar 
still error, but as @mihaimaruseac said, it seems like just an warning message

**Comment by alisaaalehi** [comment] 2020-10-30 01:25
Same error for me:
Tensorflow version: `2.5.0-dev20201027`
Python version: `3.6.12` |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0]

**Comment by aaronmondal** [comment] 2020-10-30 19:36
Could it be related to commit 9b5e180a69e29a6266224a6c74868295ff5631a4?

It changes `tensorflow/python/eager/pywrap_tfe_src.cc` and the commit was roughly 10 days ago.

**Comment by mihaimaruseac** [comment] 2020-10-30 22:30
Bisection points to 32f35aabce2b9c65d5244a8edf5904f367f28296 but that does not seem relevant, perhaps only surfacing an issue that exists from before.

**Comment by Whrothus** [comment] 2020-10-31 22:32
I downgraded tf-nightly works now for me

**Comment by psycho2012** [comment] 2020-11-04 09:07
Same error for me at the moment
Windows 10, Python 3.7
```

D:\python37\Scripts>pip install tf-nightly
Collecting tf-nightly
  Using cached https://files.pythonhosted.org/packages/ed/e1/3b28660594bea78e17d43ba22923bfb5299de1c324f5b521f2b089491ca8/tf_nightly-2.5.0.dev20201103-cp37-cp37m-win_amd64.whl
Collecting flatbuffers~=1.12.0 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/eb/26/712e578c5f14e26ae3314c39a1bdc4eb2ec2f4ddc89b708cf8e0a0d20423/flatbuffers-1.12-py2.py3-none-any.whl
Collecting astunparse~=1.6.3 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl
Collecting h5py~=2.10.0 (from tf-nightly)
  Downloading https://files.pythonhosted.org/packages/a1/6b/7f62017e3f0b32438dd90bdc1ff0b7b1448b6cb04a1ed84f37b6de95cd7b/h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5MB)
     |████████████████████████████████| 2.5MB 1.6MB/s
Collecting tf-estimator-nightly~=2.4.0.dev (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/89/d2/2131f5a0f0d14bae7f4d332724748b9ca6746b0d32f5c76145f0707f47d8/tf_estimator_nightly-2.4.0.dev2020102301-py2.py3-none-any.whl
Collecting termcolor~=1.1.0 (from tf-nightly)
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting grpcio~=1.32.0 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/67/5f/bf822211f7f94a2f6d0f8fd3bda3b804d7b24b6d5c84dbc6e6c9df4c74c2/grpcio-1.32.0-cp37-cp37m-win_amd64.whl
Collecting typing-extensions~=3.7.4 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting protobuf~=3.13.0 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/6b/2e/28425c709c26525998be0b7a91c4090c87c38a1a9644fd43fefaea2e16c0/protobuf-3.13.0-cp37-cp37m-win_amd64.whl
Collecting keras-preprocessing~=1.1.2 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/79/4c/7c3275a01e12ef9368a892926ab932b33bb13d55794881e3573482b378a7/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl
Collecting wrapt~=1.12.1 (from tf-nightly)
  Downloading https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4cf0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz
Collecting tb-nightly~=2.4.0.a (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/40/a1/a6eabdbe2eae2a6c745ffa473a1d9d6f8d6d1d5d2e5fd1b86c95f821bf0b/tb_nightly-2.4.0a20201103-py3-none-any.whl
Collecting google-pasta~=0.2 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl
Collecting absl-py~=0.10 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/bc/58/0aa6fb779dc69cfc811df3398fcbeaeefbf18561b6e36b185df0782781cc/absl_py-0.11.0-py3-none-any.whl
Collecting six~=1.15.0 (from tf-nightly)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting gast==0.3.3 (from tf-nightly)
  Downloading https://files.pythonhosted.org/packages/d6/84/759f5dd23fec8ba71952d97bcc7e2c9d7d63bdc582421f3cd4be845f0c98/gast-0.3.3-py2.py3-none-any.whl
Collecting wheel~=0.35 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Collecting opt-einsum~=3.3.0 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/bc/19/404708a7e54ad2798907210462fd950c3442ea51acc8790f3da48d2bee8b/opt_einsum-3.3.0-py3-none-any.whl
Collecting numpy~=1.19.2 (from tf-nightly)
  Using cached https://files.pythonhosted.org/packages/5f/a5/24db9dd5c4a8b6c8e495289f17c28e55601769798b0e2e5a5aeb2abd247b/numpy-1.19.4-cp37-cp37m-win_amd64.whl
Requirement already satisfied: setuptools in d:\python37\lib\site-packages (from protobuf~=3.13.0->tf-nightly) (41.2.0)
Collecting google-auth<2,>=1.6.3 (from tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/1d/60/81e68e70eea91ef05bb00bcdac243d67b61f826c65aaca6961de622dffd7/google_auth-1.23.0-py2.py3-none-any.whl
Collecting requests<3,>=2.21.0 (from tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61kB)
     |████████████████████████████████| 71kB 2.2MB/s
Collecting werkzeug>=0.11.15 (from tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
     |████████████████████████████████| 307kB 2.2MB/s
Collecting tensorboard-plugin-wit>=1.6.0 (from tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/b6/85/5c5ac0a8c5efdfab916e9c6bc18963f6a6996a8a1e19ec4ad8c9ac9c623c/tensorboard_plugin_wit-1.7.0-py3-none-any.whl
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/81/67/e2c34bb0628984c7ce71cce6ba6964cb29c418873847fc285f826e032e6e/google_auth_oauthlib-0.4.2-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/ac/ef/24a91ca96efa0d7802dffb83ccc7a3c677027bea19ec3c9ee80be740408e/Markdown-3.3.3-py3-none-any.whl (96kB)
     |████████████████████████████████| 102kB 3.2MB/s
Collecting rsa<5,>=3.1.4; python_version >= "3.5" (from google-auth<2,>=1.6.3->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/1c/df/c3587a667d6b308fadc90b99e8bc8774788d033efcc70f4ecaae7fad144b/rsa-4.6-py3-none-any.whl (47kB)
     |████████████████████████████████| 51kB 3.4MB/s
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/cd/5c/f3aa86b6d5482f3051b433c7616668a9b96fbe49a622210e2c9781938a5c/cachetools-4.1.1-py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl (155kB)
     |████████████████████████████████| 163kB 2.2MB/s
Collecting chardet<4,>=3.0.2 (from requests<3,>=2.21.0->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 2.2MB/s
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
     |████████████████████████████████| 163kB 2.2MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3,>=2.21.0->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl (127kB)
     |████████████████████████████████| 133kB 2.2MB/s
Collecting idna<3,>=2.5 (from requests<3,>=2.21.0->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 2.0MB/s
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from markdown>=2.6.8->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/6d/6d/f4bb28424bc677bce1210bc19f69a43efe823e294325606ead595211f93e/importlib_metadata-2.0.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4; python_version >= "3.5"->google-auth<2,>=1.6.3->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 1.3MB/s
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tb-nightly~=2.4.0.a->tf-nightly)
  Using cached https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tb-nightly~=2.4.0.a->tf-nightly)
  Downloading https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
Installing collected packages: flatbuffers, wheel, six, astunparse, numpy, h5py, tf-estimator-nightly, termcolor, grpcio, typing-extensions, protobuf, keras-preprocessing, wrapt, absl-py, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, chardet, certifi, urllib3, idna, requests, werkzeug, tensorboard-plugin-wit, oauthlib, requests-oauthlib, google-auth-oauthlib, zipp, importlib-metadata, markdown, tb-nightly, google-pasta, gast, opt-einsum, tf-nightly
  WARNING: The script wheel.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script f2py.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for termcolor ... done
  Running setup.py install for wrapt ... done
  WARNING: The scripts pyrsa-decrypt.exe, pyrsa-encrypt.exe, pyrsa-keygen.exe, pyrsa-priv2pub.exe, pyrsa-sign.exe and pyrsa-verify.exe are installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chardetect.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script google-oauthlib-tool.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tensorboard.exe is installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts estimator_ckpt_converter.exe, import_pb_to_tensorboard.exe, saved_model_cli.exe, tf_upgrade_v2.exe, tflite_convert.exe, toco.exe and toco_from_protos.exe are installed in 'd:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed absl-py-0.11.0 astunparse-1.6.3 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 flatbuffers-1.12 gast-0.3.3 google-auth-1.23.0 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 grpcio-1.32.0 h5py-2.10.0 idna-2.10 importlib-metadata-2.0.0 keras-preprocessing-1.1.2 markdown-3.3.3 numpy-1.19.4 oauthlib-3.1.0 opt-einsum-3.3.0 protobuf-3.13.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 six-1.15.0 tb-nightly-2.4.0a20201103 tensorboard-plugin-wit-1.7.0 termcolor-1.1.0 tf-estimator-nightly-2.4.0.dev2020102301 tf-nightly-2.5.0.dev20201103 typing-extensions-3.7.4.3 urllib3-1.25.11 werkzeug-1.0.1 wheel-0.35.1 wrapt-1.12.1 zipp-3.4.0
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

D:\python37\Scripts>cd ..

D:\python37>python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
2020-11-04 17:04:04.516463: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'
Exception ignored in: <function Buckets.__del__ at 0x000001B4B782AA68>
Traceback (most recent call last):
  File "D:\python37\lib\site-packages\tensorflow\python\eager\monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
```

**Comment by mihaimaruseac** [comment] 2020-11-04 16:14
Note that your error is actually `AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'`

**Comment by psycho2012** [comment] 2020-11-05 06:32
@mihaimaruseac Oh, I am sorry, but `python -c "import tensorflow as tf; print(tf.__version__)"`  also failed.

**Comment by amitport** [comment] 2020-11-05 13:22
(this also happens in windows10 with tf@2.4-rc0, can remove the subtype: ubuntu)

**Comment by mihaimaruseac** [comment] 2020-11-05 17:43
32f35aabce2b9c65d5244a8edf5904f367f28296 is indeed the culprit and fix is in progress

**Closed** 2020-11-05 21:55 UTC
Labels: type:build/install

**Comment by asimeonovMLPS** [comment] 2020-11-06 09:41
Error persist in version 2.5.0-dev20201105.

**Comment by guomingjin** [comment] 2020-11-06 10:09
It seems like a bug in the recent tf-nightly version, The bug will be gone with version 2.4.0.dev20200901.

**Comment by mihaimaruseac** [comment] 2020-11-06 18:04
tf_nightly-2.5.0.dev20201106 which was pushed recently should be ok. At least the error no longer shows up on our log.

**Comment by aaronmondal** [comment] 2020-11-06 20:26
I just built `master` and the issue did not occur anymore. Thanks for resolving :)

**Comment by JingYao0512** [comment] 2020-11-09 07:45
My solution:
This error seems to happen when python version is lower than 3.7, so I upgrade my python version to 3.8.0 and then the error did not happen.  
 
My environment
--Windows 10
--python 3.8.0
--tensorflow2.4.0rc0 

Thanks for everyone who provides great solutions for this issue!!
