### ISSUE TITLE
Problem with TF runtime when running Ape-X code

### ISSUE THREAD

**Issue by harshita-kaushal** [tensorflow/tensorflow#21978] opened 2018-08-30 18:38 UTC
I ran the following command. 
`(env) hkaushal-mac01:ape-x hkaushal$ python apex.py --env video_pinball --num-timesteps 1000000000 --logdir=/tmp/agent
`

I am trying to run through the [ape-x code ](https://github.com/uber-research/ape-x), and the above errors are generated.

Python 2.7.15 :: Anaconda, Inc. ( Python version) 
 The other issues opened regarding this didn't help my case, and there are no stack-overflow posts regarding this as well since Ape-X was released only a day ago.
I'm trying to operate under gym_tensorflow of the Ape-X code for some context. 
Thanks! 

```
raceback (most recent call last):
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apex.py", line 20, in <module>
    import tensorflow as tf
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/hkaushal/Documents/env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

`hkaushal-mac01:tools hkaushal$ bash ./tf_env_collect.sh 
`
 also gives me a similar error. ( this the command to provide the system information)

```
g++ -std=c++11 -shared -fPIC -I -I/external/nsync/public -L -D_GLIBCXX_USE_CXX11_ABI=0 -O2 -DGOOGLE_CUDA=1 -I/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/src -I/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/src/controllers -I/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/src/os_dependent -I/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/src/environment -I/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/src/external -L/Users/hkaushal/Documents/ape-x/gym_tensorflow/atari-py/atari_py/ale_interface/build -framework Cocoa .//*.cpp .//atari/*.cpp -ltensorflow_framework -lale -o gym_tensorflow.so
.//tf_env.cpp:19:10: fatal error: 'tensorflow/core/framework/op_kernel.h' file
      not found
#include "tensorflow/core/framework/op_kernel.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
.//atari/tf_atari.cpp:18:10: fatal error: 'ale_interface.hpp' file not found
#include <ale_interface.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [gym_tensorflow.so] Error 1

```

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-16 02:33
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshita-kaushal** [comment] 2018-09-19 00:07
It was an issue, but running the command which provided the system's details also generated an error, thus I could not provide more info. This has still not been resolved, no.

**Comment by tensorflowbutler** [comment] 2018-10-04 19:06
Nagging Assignee @jart: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-03 12:32
Nagging Assignee @jart: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:48
Nagging Assignee @jart: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:54
Nagging Assignee @jart: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-12-26 17:49
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-12-26 17:49 UTC
Labels: stat:awaiting response, type:build/install
