### ISSUE TITLE
--config=mkl leads to libmklml_intel.so: error: undefined reference to 'dladdr'

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#12951] opened 2017-09-10 23:50 UTC
Cloning master (702d595822e9e5f5232b8140c6296683612c33a9), running `configure` with "No" throughout, and trying to build a pip package (Bazel 0.5.4, Ubuntu 16.10) with the new `--config=mkl` flag crashes.

```sh
bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package

ERROR: /home/carl/tensorflow/tensorflow/python/BUILD:1289:1: Linking of rule '//tensorflow/python:gen_resource_variable_ops_py_wrappers_cc' failed (Exit 1)
bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so: error: undefined reference to 'dladdr'
```

```sh
ldd bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so

libiomp5.so => not found
```

**Comment by reedwm** [comment] 2017-09-11 18:14
@tfboyd do you know what the issue is?

**Comment by tfboyd** [comment] 2017-09-11 21:01
495cc8e474e608bbd0b6c5bf91d5a22962ede7cd  (Head/Master synced at 1:15 PST 11-SEP for reference)
./configure all defaults
bazel build --c opt --config=mkl //tensorflow/tools/pip_package:build_pip_package

bazel 0.5.2
python 2.7
Ubuntu 14.04 (internally customized but core is the same)

Compiled fine, maybe there was an issue at head when you synced.  Closing but feel free to comment if you have more details.  Tags are normally safer, but Gunhan was working on the build scripts for this and I am not sure everything ended up on 1.3.  If you do not mind 1.2.1, I know that Tag works and you can build with this
```bazel build --config=mkl --copt="-DEIGEN_USE_VML" -c opt //tensorflow/tools/pip_package:build_pip_package```

I do not think ```--copt="-DEIGEN_USE_VML"``` does anything those were the instructions and I what I uses so I like to stick with it.  If you want a precompiled binary [here](https://storage.googleapis.com/tf-performance/tf_binary/tensorflow-1.2.0.tag.12f033d.MKL_NOGPU-cp27-cp27mu-linux_x86_64.whl) is a link to 1.2 that I did for Python 2.7 linux.  Sharing just because I have it.

**Closed by tfboyd** 2017-09-11 21:01 UTC
Labels: type:build/install

**Comment by carlthome** [comment] 2017-09-14 14:12
Hmm, very strange. Could you share your `cat /proc/cpuinfo`? I'm running on a Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz.

```sh
git clone https://github.com/tensorflow/tensorflow

git checkout 495cc8e474e608bbd0b6c5bf91d5a22962ede7cd

cd tensorflow

PYTHON_BIN_PATH=/home/carl/anaconda3/bin/python
 USE_DEFAULT_PYTHON_LIB_PATH=1 CC_OPT_FLAGS="-march=native"
  TF_ENABLE_XLA=0 TF_NEED_MKL=0 TF_NEED_MPI=0 TF_NEED_JEMALLOC=0 TF_NEED_GCP=0 TF_NEED_HDFS=0
  TF_NEED_VERBS=0 TF_NEED_OPENCL=0 TF_NEED_CUDA=0 TF_NEED_GDR=0 ./configure

bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package
```
> error: undefined reference to 'dladdr'

Removing `--config=mkl` works fine.

**Comment by carlthome** [comment] 2017-09-14 14:52
And just to be sure it's not Anaconda related, I tried PYTHON_BIN_PATH=/usr/bin/python (Python 2.7.12+) and get the same error.

**Comment by tfboyd** [comment] 2017-09-14 16:58
All the data I can think to share:  
Python 2.7.6
I did have jemalloc as that is a default.

My CPU, which would not matter.
model name	: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz

You might want to try by just running ./configure and not using the ENV variables.  It is possible I did something weird, but I am very certain (some margin for error) that I just git cloned did ./configure (enter enter enter enter :-)) and ran the build.

I do not know this is frustrating.  I am not sure what the problem might be.

**Comment by llealgt** [comment] 2017-10-14 08:01
Hey guys, i have a different but related issue, i compiled with --config=mkl, in my case it compiles fine and creates the wheel file, i install it fine, but when i create a python session and do import tensorflow as tf, i get  libmklml_intel.so: cannot open shared object file: No such file or directory , any ideas?

**Comment by carlthome** [comment] 2017-10-16 06:55
@llealgt maybe consider opening a separate issue for this?

**Comment by SarshesJ** [comment] 2017-12-07 11:12
So, any progress? i have similar errors when compiling tensorflow v1.4.0.

`/opt/rh/devtoolset-6/root/usr/bin/gcc -o bazel-out/host/bin/tensorflow/python/gen_lookup_ops_py_wrappers_cc '-Wl,-rpath,$ORIGIN/../../_solib_k8/_U_S_Stensorflow_Spython_Cgen_Ulookup_Uops_Upy_Uwrappers_Ucc___Utensorflow' '-Wl,-rpath,$ORIGIN/../../_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib' -Lbazel-out/host/bin/_solib_k8/_U_S_Stensorflow_Spython_Cgen_Ulookup_Uops_Upy_Uwrappers_Ucc___Utensorflow -Lbazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/opt/rh/devtoolset-6/root/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/tensorflow/python/gen_lookup_ops_py_wrappers_cc-2.params)
bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so: error: undefined reference to 'dlopen'
bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so: error: undefined reference to 'dlerror'
bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so: error: undefined reference to 'dlsym'
bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so: error: undefined reference to 'dladdr'
collect2: error: ld returned 1 exit status`

`ldd bazel-out/host/bin/_solib_k8/_U_S_Sthird_Uparty_Smkl_Cintel_Ubinary_Ublob___Uexternal_Smkl_Slib/libmklml_intel.so
	linux-vdso.so.1 =>  (0x00007ffca8917000)
	libiomp5.so => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc4f8c30000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc4f892e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc4f856b000)
	/lib64/ld-linux-x86-64.so.2 (0x000055607a1eb000)`

**Comment by pavanky** [comment] 2018-02-02 02:15
@tfboyd This issue still happens when mkl is enabled on  [tensorflow 1.5.0 release](https://github.com/tensorflow/tensorflow/archive/v1.5.0.zip) for the following configuration:

- Centos 7 docker image 
- Devtoolset 6 
- Python 27
- bazel 0.8.0

Some of the things I tried:
- Passing `--linkopt=-ldl` to `bazel build`.
- Patch `mk/BUILD` to accept `linkopts = ["-ldl"]`
- Patch `tf_extension_linkopts` in `tensorflow/tensorflow.bzl` to `return ["-ldl"]`.

None of them seem to work.

**Comment by SarshesJ** [comment] 2018-02-02 02:45
We need to compile gcc 6 from source code. We shouldn't use devtoolset. :)

**Comment by patmanami** [comment] 2018-02-08 18:43
Removing the mkl option isn't a fix and that DEIGEN_USE_VML flag definitely does nothing. Getting same errors on Centos 6.5, Python 2.7, TF 1.6, Devtoolset 6. Any other viable solutions?

bazel build --linkopt='-lrt' --verbose_failures --action_env PATH="$PATH" --config=mkl --config=opt //tensorflow/tools/pip_package:build_pip_package

**Comment by tatianashp** [comment] 2018-03-22 20:50
@agramesh1  Could somebody from Intel help to figure out why this build can't find OpenMP library?

**Comment by agramesh1** [comment] 2018-03-22 23:11
This is regarding the original problem of missing  error: undefined reference to 'dladdr' and other symbols.

On some systems, esp. some Ubuntu version we have seen Tensorflow fail to build due to missing libraries when compiling with --config=mkl,  you might see errors similar to this libmklml_intel.so: error: undefined reference to 'dladdr'  The problem is not due to tensorflow or MKL, the linker is unable to find the libdl.  We tried to pass the -ldl flag to the linker through bazel build but couldn't get it to work.  There is a work around you can try.

For a work around, you need a private copy of mkl with the missing library included in. Follow the steps below
a.Download the version of MKL used by the version of tensorflow you are compiling, you can get the URL from the file tensorflow/workspace.bzl, search for mkl_repository.
b.Find the shared library libdl.so on your system ( it is usually in /usr/lib/) and copy over to the lib folder of the copy of MKL that you downloaded.
c.Set the environment variable TF_MKL_ROOT to  point to the copy of MKL from step above.
d.Modify the file third_party/mkl/BUILD as follows
i.add a line containing the following  linkopts = ["-ldl",],  after the line containing   name = "intel_binary_blob", 


ii.add a line containing "@mkl//:libdl.so",  after the line containing srcs = if_mkl([ 



e.run configure and build

**Comment by SarshesJ** [comment] 2018-03-23 02:02
Perhaps I didn't explain well about this question. What I mean is that devtoolset-6 may lead to the ldopen or libiomp5.so not found errors. 
Anybody who faces this problem can try to build a gcc-6 from source code to fix it.
build gcc-6:
```
$ tar xzf gcc-6.4.0.tar.gz
$ cd gcc-6.4.0
$ ./configure --prefix=/opt/gcc-6 --enable-languages=c,c++
$ make
$ make install
$ export PATH=/opt/gcc-6/bin:$PATH
$ export LD_LIBRARY_PATH=/opt/gcc-6/lib64:LD_LIBRARY_PATH
```
build tensorflow:
```
$ cd /path/to/tensorflow_src
$ bazel clean
$ rm .cache/bazel -rf
$ ./configure
$ bazel build --config=mkl -copt="-DEIGEN_USE_MKL_VML" -c opt //tensorflow/tools/pip_package:build_pip_package
```
It has been compiled successfully with gcc-6 on centos 7.2. But we have to take the compiled gcc library wherever we use tensorflow. 

Maybe there're some better ways to solve the problem, but this is the only way that i have found.

**Comment by agramesh1** [comment] 2018-03-23 04:08
@SarshesJ Thanks for letting us know. Glad to hear the solution worked for you.

**Comment by pavanky** [comment] 2018-03-31 06:05
@agramesh1 On centos7, the issue was libmklml_intel.so was being linked ahead of libdl.so. Your suggestions helped, but the patch required is slightly different and can be seen here: https://github.com/pavanky/tensorflow/commit/bd90d1f086a830ad7cf8edf981954af00c7ef53c

(I still followed the suggestions requiring custom MKL root as well as copying libdl)

This is based on tensorflow 1.7
