### ISSUE TITLE
Mistake in matrix multiplication(http://tensorflow.org/tutorials/mnist/beginners/index.md)

### ISSUE THREAD

**Issue by yuriShafet** [tensorflow/tensorflow#240] opened 2015-11-16 12:37 UTC
When single layer network math is described you have following:
"""If we write that out as equations, we get:"""
after that comes picture with weight multiplications, but there should be
W_1,1*x_1 + W_1,2*x_2 + W_1,3*x_3 + b_1
etc..
Instead there written:
W_1,1*x_1 + W_1,2*x_1 + W_1,3*x_1 + b_1
etc..
Please correct me if I am mistaken.

**Comment by girving** [comment] 2015-11-16 15:46
Duplicate of https://github.com/tensorflow/tensorflow/issues/185.  Already fixed in the source but not yet pushed to the website.

**Closed by girving** 2015-11-16 15:46 UTC
