### ISSUE TITLE
Pylint checks from ci_sanity.sh `--incremental`

### ISSUE THREAD

**Issue by lc0** [tensorflow/tensorflow#27903] opened 2019-04-16 21:53 UTC
Currently we kind of support `--incremental` to run incremental sanity checks. In reality, we still run it for all files:

https://github.com/tensorflow/tensorflow/blob/0e4117f67192a140466ba66513035e24bbd1a474/tensorflow/tools/ci_build/ci_sanity.sh#L137

```
# For incremental builds, we still check all Python files in cases there
# are function signature changes that affect unchanged Python files.
```

Would it make sense to just clean it up or what is the current idea? 

I started to add an incremental check for since a specific commit, so one can run checks for changes across multiple commits.

**Comment by lc0** [comment] 2019-04-17 07:48
Something along these lines https://github.com/lc0/tensorflow/pull/1 - just to visualize the idea

**Comment by gadagashwini** [comment] 2019-04-17 11:53
This question is better asked on StackOverflw.since it is not a bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by lc0** [comment] 2019-04-17 12:29
I mean, it's a feature for incremental CI checks :) and CI checks are used for people contributing to TensorFlow

**Comment by gunan** [comment] 2019-11-25 17:30
I think your suggestion makes sense.
Could you make a PR and assign it to @yifeif

**Closed** 2021-04-07 00:16 UTC
Labels: type:feature
