### ISSUE TITLE
Build "general" shared library for Android to use with Android Make 

### ISSUE THREAD

**Issue by beniroquai** [tensorflow/tensorflow#6166] opened 2016-12-07 17:43 UTC
Luckily there is a very good introduction into programming with Tensorflow on an Android device provided here:
https://github.com/miyosuda/TensorFlowAndroidDemo

The version of TF used in this project is 0.10 which doesn't work with my trained model coming from TF 0.12. I was wondering which is the best way to have a "generalized" shared library (or however this is called), built with bazel that I could use interchangeably like the one provided in the project mentioned above. 
I was able to build the TF-Android Example using Bazel. My Anrdoid-project, which uses Tensorflow, also needs OpenCV to work. Therefore I'm building my App with a make-file which worked quiet well so far. 

Maybe I'm completely wrong, as I'm not really a programmer - so far. Thank you for any advice.

**Comment by beniroquai** [comment] 2016-12-07 18:17
I think I found the answer already. Should have had stumbled over it a bit earlier:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

**Comment by andrewharp** [comment] 2016-12-07 18:17
Several generalized targets exist currently (by generalized I basically mean not tensorflow/examples/android-specific). It just depends what your requirements are and the tools you want to use.

You can build the TF library suitable for dropping into your app with the Android inference JNI bindings defined in tensorflow/contrib/android/BUILD as so:
```
bazel build //tensorflow/contrib/android:libtensorflow.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a
```

The Java src counterpart is found under tensorflow/contrib/android/java. See [TensorFlowImageClassifier.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageClassifier.java) for example using it.

Otherwise, if you want to link TF into the rest of your native code, try tensorflow/core:android_tensorflow_lib (without inference bindings), or tensorflow/contrib/android: android_tensorflow_inference_jni (with inference bindings), which should give you a .a out.

Additionally, we have a makefile-based build equivalent to android_tensorflow_inference_jni under tensorflow/contrib/makefile, and a gradle-wrapper using cmake/make that eliminates the need for bazel under tensorflow/android/cmake.

**Comment by beniroquai** [comment] 2016-12-07 18:19
A great! Will look into it! Thank you very much for this detailed answer.

**Comment by beniroquai** [comment] 2016-12-07 23:01
May I still ask question regarding this topic eventhough it's closed? 
For what ever reason, I can not build the solution above. It gives the following error:
```
User$ bazel build //tensorflow/contrib/android:libtensorflow.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cpu=armeabi-v7a
ERROR: no such target '//tensorflow/contrib/android:libtensorflow.so': target 'libtensorflow.so' not declared in package 'tensorflow/contrib/android' defined by /Users/Bene/Tensorflow/tensorflow/contrib/android/BUILD.
INFO: Elapsed time: 2,199s
```

However building the Android App using

`bazel build //tensorflow/examples/android:tensorflow_demo`

worked out quiet well I guess.

**Comment by michaelisard** [comment] 2016-12-07 23:07
It looks as if the target name has changed to //tensorflow/contrib/android:libtensorflow_inference.so @andrewharp can you confim (and update the comment above the target if so)?

**Comment by andrewharp** [comment] 2016-12-07 23:18
@michaelisard @beniroquai Correct, the comment didn't get updated when the target did. Thanks for catching that, fix sent.

**Comment by beniroquai** [comment] 2016-12-08 16:31
Thank you very much for your reply. I tested the code above and got the following error (Mac and Linux UBuntu 16.04 - all dependencies should have been met):

```
> bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo(quantized_activation_ops.o):quantized_activation_ops.cc:function Eigen::QInt32 tensorflow::FloatToQuantized<Eigen::QInt32>(float, float, float): error: undefined reference to 'round'
> bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib_lite.lo(simple_graph_execution_state.o):simple_graph_execution_state.cc:function tensorflow::SimpleGraphExecutionState::Extend(tensorflow::GraphDef const&, std::unique_ptr<tensorflow::SimpleGraphExecutionState, std::default_delete<tensorflow::SimpleGraphExecutionState> >*) const: error: undefined reference to 'ceil'
> bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib_lite.lo(unique_tensor_references.o):unique_tensor_references.cc:function tensorflow::UniqueTensorReferences::Add(tensorflow::Tensor const&): error: undefined reference to 'ceil'
> bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/tensorflow/core/libandroid_tensorflow_lib_lite.lo(logging.o):logging.cc:function tensorflow::internal::LogMessage::GenerateLogMessage(): error: undefined reference to '__android_log_write'
> collect2: error: ld returned 1 exit status
> Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 97.991s, Critical Path: 85.88s
> 
```
The Demo-App was built sucessully it says, but 

```
bazel build //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a

```
didn't work. I'm using TF 0.12.

**Comment by andrewharp** [comment] 2016-12-08 17:48
Ack, looks like `-llog` and `-lm` are missing from the linkopts. Add them and it should work; I'll send a fix.

This time I've manually run the command myself and everything seems in order :)

**Comment by beniroquai** [comment] 2016-12-08 17:53
Thanks for the quick fix :) 
Actually my programming skills are limited and I don't exactly know, what you mean by " add the linkopts. Could you give a quick hint or a page which describes that? I've seen something like that in a `makefile` as well I gues.. Sorry for that ;)

**Comment by andrewharp** [comment] 2016-12-08 17:58
You just need to find the definition of libtensorflow_inference.so in [tensorflow/contrib/android/BUILD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/BUILD) and make it look like this:

```
cc_binary(
    name = "libtensorflow_inference.so",
    srcs = [],
    copts = tf_copts(),
    linkopts = [
        "-landroid",
        "-llog",
        "-lm",
        "-z defs",
        "-s",
        "-Wl,--version-script",  # This line must be directly followed by LINKER_SCRIPT.
        LINKER_SCRIPT,
    ],
    linkshared = 1,
    linkstatic = 1,
    tags = [
        "manual",
        "notap",
    ],
    deps = [
        ":android_tensorflow_inference_jni",
        "//tensorflow/core:android_tensorflow_lib",
        LINKER_SCRIPT,
    ],
)
```

**Comment by beniroquai** [comment] 2016-12-08 18:10
Tadah! It worked! :) Let's see if I can proceed from now ^^ 

But maybe - as stated somewhere here - a short tutorial in the Readme would be super great. Like "how to integrate tensorflow libraries/binaries into a android studio project" or something.

**Comment by kevinashaw** [comment] 2016-12-16 04:52
Not sure if this is useful, but am reporting for your info.
I used the following command (as listed above):

```
bazel build //tensorflow/contrib/android:libtensorflow_inference.so \
   --crosstool_top=//external:android/crosstool \
   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
   --cpu=armeabi-v7a
```

and got the following error message (Running on MacOS with TF0.12 (Commit#412428)):

```
Kevins-MacBook-Air-2:tensorflow kevin$ bazel build //tensorflow/contrib/android:libtensorflow_inference.so \
>    --crosstool_top=//external:android/crosstool \
>    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
>    --cpu=armeabi-v7a
..........................................................
WARNING: Bazel Android NDK crosstools are based on Android NDK revision 12. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '13.1.3345770'.
INFO: Loading package: @local_config_cuda//cuda
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:avgpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:bounds_check.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops_gradients.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_activations.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_attention.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_cuboid_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_cuboid_convolution.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_patch_3d.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_pooling.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_softmax.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:fifo_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:maxpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:padding_fifo_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:queue_base.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:queue_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:typed_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_entry.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_scorer.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_search.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_decoder.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_loss_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:naming.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:naming.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kevin/tensorflow/tensorflow/core/BUILD:779:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.h' directly. You should either move the file to this package or depend on an appropriate rule there.
INFO: Found 1 target...
INFO: From Compiling external/protobuf/src/google/protobuf/util/time_util.cc [for host]:
external/protobuf/src/google/protobuf/util/time_util.cc:52:18: warning: unused variable 'kMicrosPerMillisecond' [-Wunused-const-variable]
static const int kMicrosPerMillisecond = 1000;
                 ^
external/protobuf/src/google/protobuf/util/time_util.cc:56:19: warning: unused variable 'kTimestampFormat' [-Wunused-const-variable]
static const char kTimestampFormat[] = "%E4Y-%m-%dT%H:%M:%S";
                  ^
2 warnings generated.
INFO: From ProtoCompile tensorflow/core/example/example.pb.cc:
bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/genfiles/external/protobuf/src: warning: directory does not exist.
INFO: From Compiling tensorflow/core/kernels/split_v_op.cc:
tensorflow/core/kernels/split_v_op.cc: In instantiation of 'void tensorflow::SplitVOpCPU<T, Tlen>::Compute(tensorflow::OpKernelContext*) [with T = float; Tlen = long long int]':
tensorflow/core/kernels/split_v_op.cc:400:1:   required from here
tensorflow/core/kernels/split_v_op.cc:212:63: warning: narrowing conversion of 'split_sizes_vec.std::vector<_Tp, _Alloc>::operator[]<long long int, std::allocator<long long int> >(((std::vector<long long int, std::allocator<long long int> >::size_type)i))' from '__gnu_cxx::__alloc_traits<std::allocator<long long int> >::value_type {aka long long int}' to 'int' inside { } [-Wnarrowing]
           prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                                                               ^
tensorflow/core/kernels/split_v_op.cc: In instantiation of 'void tensorflow::SplitVOpCPU<T, Tlen>::Compute(tensorflow::OpKernelContext*) [with T = int; Tlen = long long int]':
tensorflow/core/kernels/split_v_op.cc:400:1:   required from here
tensorflow/core/kernels/split_v_op.cc:212:63: warning: narrowing conversion of 'split_sizes_vec.std::vector<_Tp, _Alloc>::operator[]<long long int, std::allocator<long long int> >(((std::vector<long long int, std::allocator<long long int> >::size_type)i))' from '__gnu_cxx::__alloc_traits<std::allocator<long long int> >::value_type {aka long long int}' to 'int' inside { } [-Wnarrowing]
INFO: From Compiling tensorflow/core/kernels/split_op.cc:
tensorflow/core/kernels/split_op.cc: In instantiation of 'void tensorflow::SplitOpCPU<T>::Compute(tensorflow::OpKernelContext*) [with T = Eigen::QUInt8]':
tensorflow/core/kernels/split_op.cc:272:1:   required from here
tensorflow/core/kernels/split_op.cc:156:64: warning: narrowing conversion of '(tensorflow::int64)split_dim_output_size' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
         prefix_dim_size, split_dim_output_size, suffix_dim_size};
                                                                ^
tensorflow/core/kernels/split_op.cc: In instantiation of 'void tensorflow::SplitOpCPU<T>::Compute(tensorflow::OpKernelContext*) [with T = float]':
tensorflow/core/kernels/split_op.cc:272:1:   required from here
tensorflow/core/kernels/split_op.cc:156:64: warning: narrowing conversion of '(tensorflow::int64)split_dim_output_size' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
tensorflow/core/kernels/split_op.cc: In instantiation of 'void tensorflow::SplitOpCPU<T>::Compute(tensorflow::OpKernelContext*) [with T = int]':
tensorflow/core/kernels/split_op.cc:272:1:   required from here
tensorflow/core/kernels/split_op.cc:156:64: warning: narrowing conversion of '(tensorflow::int64)split_dim_output_size' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
INFO: From Compiling tensorflow/core/kernels/tensor_array_ops.cc:
tensorflow/core/kernels/tensor_array_ops.cc: In instantiation of 'void tensorflow::TensorArraySplitOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/tensor_array_ops.cc:1268:1:   required from here
tensorflow/core/kernels/tensor_array_ops.cc:1131:72: warning: narrowing conversion of 'previous_length' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
       Eigen::DSizes<Eigen::DenseIndex, 3> indices{0, previous_length, 0};
                                                                        ^
tensorflow/core/kernels/tensor_array_ops.cc:1133:65: warning: narrowing conversion of '(Scalar)tensor_lengths_t.Eigen::TensorMap<PlainObjectType, Options_, MakePointer_>::operator()<Eigen::Tensor<const long long int, 1, 1, int>, 16, Eigen::MakePointer>(i)' from 'Scalar {aka long long int}' to 'int' inside { } [-Wnarrowing]
                                                 elements_per_row};
                                                                 ^
tensorflow/core/kernels/tensor_array_ops.cc: In instantiation of 'void tensorflow::TensorArraySplitOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = int]':
tensorflow/core/kernels/tensor_array_ops.cc:1268:1:   required from here
tensorflow/core/kernels/tensor_array_ops.cc:1131:72: warning: narrowing conversion of 'previous_length' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
       Eigen::DSizes<Eigen::DenseIndex, 3> indices{0, previous_length, 0};
                                                                        ^
tensorflow/core/kernels/tensor_array_ops.cc:1133:65: warning: narrowing conversion of '(Scalar)tensor_lengths_t.Eigen::TensorMap<PlainObjectType, Options_, MakePointer_>::operator()<Eigen::Tensor<const long long int, 1, 1, int>, 16, Eigen::MakePointer>(i)' from 'Scalar {aka long long int}' to 'int' inside { } [-Wnarrowing]
                                                 elements_per_row};
                                                                 ^
INFO: From Compiling tensorflow/core/kernels/unpack_op.cc:
tensorflow/core/kernels/unpack_op.cc: In instantiation of 'void tensorflow::UnpackOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/unpack_op.cc:152:1:   required from here
tensorflow/core/kernels/unpack_op.cc:109:75: warning: narrowing conversion of 'before_dim' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
         Eigen::DSizes<Eigen::DenseIndex, 3> sizes{1, before_dim, after_dim};
                                                                           ^
tensorflow/core/kernels/unpack_op.cc: In instantiation of 'void tensorflow::UnpackOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = int]':
tensorflow/core/kernels/unpack_op.cc:152:1:   required from here
tensorflow/core/kernels/unpack_op.cc:109:75: warning: narrowing conversion of 'before_dim' from 'tensorflow::int64 {aka long long int}' to 'int' inside { } [-Wnarrowing]
Target //tensorflow/contrib/android:libtensorflow_inference.so up-to-date:
  bazel-bin/tensorflow/contrib/android/libtensorflow_inference.so
INFO: Elapsed time: 2481.205s, Critical Path: 2358.75s

```

**Comment by andrewharp** [comment] 2016-12-16 19:58
@kevinashaw Can you try `bazel clean`, and then build again with Android NDK 12b (found [here](https://developer.android.com/ndk/downloads/older_releases.html#ndk-12b-downloads))?

**Comment by andrewharp** [comment] 2017-01-04 22:48
Closing; as I think the original issue is resolved now.

@kevinashaw I was unable to reproduce your issue via the following steps:
```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git
cd tensorflow
gedit WORKSPACE # update ndk and sdk entries
bazel build //tensorflow/contrib/android:libtensorflow_inference.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cpu=armeabi-v7a
```
when using the 12b NDK. My guess would be that something was incorrect in your WORKSPACE file.

**Closed by andrewharp** 2017-01-04 22:48 UTC
Labels: type:build/install
