### ISSUE TITLE
Padding causing 64x increase in memory size on TPU

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#30803] opened 2019-07-17 13:24 UTC
I'm trying to train a variation of a u-net on a TPU. However, I can't seem to get it to fit into memory. I'm using tf.keras with tensorflow 1.13.2. Here's a portion of the error logs proving a list of the ops that are the greatest memory hogs. CrossReplicaSum appears to be especially bad, but so are some multiplication ops. I don't quite know how to go about debugging this as the model won't even compile so I don't know what layers these ops actually correspond to.

```
RuntimeError: Compilation failed: Compilation failure: Ran out of memory in memory space hbm. Used 27.90G of 16.00G hbm. Exceeded hbm capacity by 11.90G.

Total hbm usage >= 27.90G:
    reserved        528.00M
    program          27.38G
    arguments       unknown size

Output size unknown.

Program hbm requirement 27.38G:
    reserved          12.0K
    scoped             1.0K
    HLO temp         27.38G (5.6% utilization, 0.0% fragmentation (1.14M))

  Largest program allocations in hbm:

  1. Size: 8.00G
     Operator: op_type="CrossReplicaSum" op_name="tpu_140280287273760/CrossReplicaSum"
     Shape: f32[256,512,128,2]{3,2,1,0}
     Unpadded size: 128.00M
     Extra memory due to padding: 7.88G (64.0x expansion)
     XLA label: %cross-replica-sum = f32[256,512,128,2]{3,2,1,0} cross-replica-sum(f32[256,512,128,2]{3,2,1,0} %bitcast.1), replica_groups={{0,1,2,3,4,5,6,7}}, barrier="custom:0", to_apply=%sum.902, metadata=
{op_type="CrossReplicaSum" op_name="tpu_140280287273760/CrossRep...
     Allocation type: HLO temp
     ==========================

  2. Size: 8.00G
     Operator: op_type="Mul" op_name="tpu_140280287273760/mul_1"
     Shape: f32[8,32,512,128,2]{4,3,2,1,0}
     Unpadded size: 128.00M
     Extra memory due to padding: 7.88G (64.0x expansion)
     XLA label: %fusion.4 = (f32[8,32,512,128,2]{4,3,2,1,0}, f32[8,32,512,128,2]{4,3,2,1,0}) fusion(f32[8]{0} %fusion.1265, f32[32,512,128,2]{3,2,1,0} %reshape.319, f32[32,512,128,2]{3,2,1,0} %copy.5), kind=k
Loop, calls=%fused_computation.4, metadata={op_type="Mul" op_nam...
     Allocation type: HLO temp
     ==========================

  3. Size: 8.00G
     Operator: op_type="Mul" op_name="tpu_140280287273760/mul_1"
     Shape: f32[8,32,512,128,2]{4,3,2,1,0}
     Unpadded size: 128.00M
     Extra memory due to padding: 7.88G (64.0x expansion)
     XLA label: %fusion.4 = (f32[8,32,512,128,2]{4,3,2,1,0}, f32[8,32,512,128,2]{4,3,2,1,0}) fusion(f32[8]{0} %fusion.1265, f32[32,512,128,2]{3,2,1,0} %reshape.319, f32[32,512,128,2]{3,2,1,0} %copy.5), kind=k
Loop, calls=%fused_computation.4, metadata={op_type="Mul" op_nam...
     Allocation type: HLO temp
     ==========================

    4. Size: 1.00G
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_1/Conv2D"
     Shape: f32[32,512,128,32]{3,0,2,1}
     Unpadded size: 256.00M
     Extra memory due to padding: 768.00M (4.0x expansion)
     XLA label: %fusion.12 = f32[32,512,128,32]{3,0,2,1} fusion(f32[32]{0} %get-tuple-element.1107, f32[32,512,128,32]{3,0,2,1} %fusion.13, bf16[4,4,32,32]{3,2,1,0} %reshape.3), kind=kOutput, calls=%fused_com
putation.12, metadata={op_type="Conv2D" op_name="tpu_14028028727...
     Allocation type: HLO temp
     ==========================

  5. Size: 1.00G
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d/Conv2D"
     Shape: f32[32,512,128,32]{3,0,2,1}
     Unpadded size: 256.00M
     Extra memory due to padding: 768.00M (4.0x expansion)
     XLA label: %fusion.13 = f32[32,512,128,32]{3,0,2,1} fusion(f32[32]{0} %get-tuple-element.1105, bf16[32,512,128,2]{0,3,2,1} %copy.4, f32[4,4,2,32]{3,2,1,0} %get-tuple-element.1106), kind=kOutput, calls=%f
used_computation.13, metadata={op_type="Conv2D" op_name="tpu_140...
     Allocation type: HLO temp
     ==========================

  6. Size: 256.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_4/Conv2D"
     Shape: f32[32,256,64,64]{3,0,2,1}
     Unpadded size: 128.00M
     Extra memory due to padding: 128.00M (2.0x expansion)
     XLA label: %fusion.32 = f32[32,256,64,64]{3,0,2,1} fusion(f32[64]{0} %get-tuple-element.1165, bf16[4,4,32,64]{3,2,1,0} %reshape.6, f32[32,256,64,32]{3,0,2,1} %get-tuple-element.964), kind=kOutput, calls=
%fused_computation.32, metadata={op_type="Conv2D" op_name="tpu_1...
     Allocation type: HLO temp
     ==========================

  7. Size: 256.00M
     Operator: op_type="Conv2DBackpropInput" op_name="tpu_140280287273760/conv2d_transpose_4/conv2d_transpose"
     Shape: f32[32,256,64,32]{3,0,2,1}
     Unpadded size: 64.00M
     Extra memory due to padding: 192.00M (4.0x expansion)
     XLA label: %fusion.23 = f32[32,256,64,32]{3,0,2,1} fusion(f32[4,4,32,128]{3,2,1,0} %get-tuple-element.1186, f32[32]{0} %get-tuple-element.1185, bf16[32,128,32,64]{3,0,2,1} %get-tuple-element.965, f32[32,
128,32,64]{3,0,2,1} %fusion.48), kind=kOutput, calls=%fused_comp...
     Allocation type: HLO temp
     ==========================

  8. Size: 256.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_34/Conv2D"
     Shape: f32[32,256,64,32]{3,0,2,1}
     Unpadded size: 64.00M
     Extra memory due to padding: 192.00M (4.0x expansion)
     XLA label: %fusion.22 = f32[32,256,64,32]{3,0,2,1} fusion(f32[32]{0} %get-tuple-element.1161, f32[32,256,64,32]{3,0,2,1} %fusion.23, bf16[4,4,32,32]{3,2,1,0} %reshape.12), kind=kOutput, calls=%fused_comp
utation.22, metadata={op_type="Conv2D" op_name="tpu_140280287273...
     Allocation type: HLO temp
     ==========================

      9. Size: 128.00M
     Operator: op_type="LeakyRelu" op_name="tpu_140280287273760/leaky_re_lu/LeakyRelu"
     Shape: bf16[32,256,64,32]{3,0,2,1}
     Unpadded size: 32.00M
     Extra memory due to padding: 96.00M (4.0x expansion)
     XLA label: %fusion.38 = (bf16[32,256,64,32]{3,0,2,1}, f32[32,256,64,32]{3,0,2,1}) fusion(f32[32]{0} %get-tuple-element.1151, f32[32,512,128,32]{3,0,2,1} %fusion.14, bf16[4,4,32,32]{3,2,1,0} %reshape.5),
kind=kOutput, calls=%fused_computation.38, metadata={op_type="Le...
     Allocation type: HLO temp
     ==========================

  10. Size: 64.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_32/Conv2D"
     Shape: f32[32,128,32,64]{3,0,2,1}
     Unpadded size: 32.00M
     Extra memory due to padding: 32.00M (2.0x expansion)
     XLA label: %fusion.46 = f32[32,128,32,64]{3,0,2,1} fusion(f32[64]{0} %get-tuple-element.1157, f32[32,128,32,64]{3,0,2,1} %fusion.47, bf16[4,4,64,64]{3,2,1,0} %reshape.10), kind=kOutput, calls=%fused_comp
utation.46, metadata={op_type="Conv2D" op_name="tpu_140280287273...
     Allocation type: HLO temp
     ==========================

  11. Size: 64.00M
     Operator: op_type="Conv2DBackpropInput" op_name="tpu_140280287273760/conv2d_transpose_3/conv2d_transpose"
     Shape: f32[32,128,32,64]{3,0,2,1}
     Unpadded size: 32.00M
     Extra memory due to padding: 32.00M (2.0x expansion)
     XLA label: %fusion.47 = f32[32,128,32,64]{3,0,2,1} fusion(f32[4,4,64,256]{3,2,1,0} %get-tuple-element.1184, f32[64]{0} %get-tuple-element.1183, bf16[32,64,16,128]{3,0,2,1} %get-tuple-element.967, f32[32,
64,16,128]{3,0,2,1} %fusion.99), kind=kOutput, calls=%fused_comp...
     Allocation type: HLO temp
     ==========================

  12. Size: 64.00M
     Operator: op_type="InfeedDequeueTuple" op_name="infeed-train"
     Shape: bf16[32,512,128,2]{0,3,2,1}
     Unpadded size: 8.00M
     Extra memory due to padding: 56.00M (8.0x expansion)
     XLA label: %copy.4 = bf16[32,512,128,2]{0,3,2,1} copy(bf16[32,512,128,2]{3,2,1,0} %reshape.318), metadata={op_type="InfeedDequeueTuple" op_name="infeed-train"}
     Allocation type: HLO temp
     ==========================

  13. Size: 64.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_8/Conv2D"
     Shape: f32[32,128,32,128]{3,0,2,1}
     Unpadded size: 64.00M
     XLA label: %fusion.56 = f32[32,128,32,128]{3,0,2,1} fusion(f32[128]{0} %get-tuple-element.1173, f32[4,4,64,128]{3,2,1,0} %copy.77, f32[32,128,32,64]{3,0,2,1} %get-tuple-element.966), kind=kOutput, calls=
%fused_computation.56, metadata={op_type="Conv2D" op_name="tpu_1...
     Allocation type: HLO temp
     ==========================


     14. Size: 32.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_12/Conv2D"
     Shape: f32[32,64,16,256]{3,0,2,1}
     Unpadded size: 32.00M
     XLA label: %fusion.78 = f32[32,64,16,256]{3,0,2,1} fusion(f32[256]{0} %get-tuple-element.1113, f32[4,4,128,256]{3,2,1,0} %get-tuple-element.1114, f32[32,64,16,128]{3,0,2,1} %get-tuple-element.968), kind=
kOutput, calls=%fused_computation.78, metadata={op_type="Conv2D"...
     Allocation type: HLO temp
     ==========================

  15. Size: 32.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_13/Conv2D"
     Shape: f32[32,64,16,256]{3,0,2,1}
     Unpadded size: 32.00M
     XLA label: %fusion.77 = f32[32,64,16,256]{3,0,2,1} fusion(f32[256]{0} %get-tuple-element.1115, f32[32,64,16,256]{3,0,2,1} %fusion.78, f32[4,4,256,256]{3,2,1,0} %get-tuple-element.1116), kind=kOutput, cal
ls=%fused_computation.77, metadata={op_type="Conv2D" op_name="tp...
     Allocation type: HLO temp
     ==========================

  16. Size: 32.00M
     Operator: op_type="LeakyRelu" op_name="tpu_140280287273760/leaky_re_lu_1/LeakyRelu"
     Shape: bf16[32,128,32,64]{3,0,2,1}
     Unpadded size: 16.00M
     Extra memory due to padding: 16.00M (2.0x expansion)
     XLA label: %fusion.89 = (bf16[32,128,32,64]{3,0,2,1}, f32[32,128,32,64]{3,0,2,1}) fusion(f32[64]{0} %get-tuple-element.1171, f32[32,256,64,64]{3,0,2,1} %fusion.33, bf16[4,4,64,64]{3,2,1,0} %reshape.9), k
ind=kOutput, calls=%fused_computation.87, metadata={op_type="Lea...
     Allocation type: HLO temp
     ==========================

  17. Size: 16.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_16/Conv2D"
     Shape: f32[32,32,8,512]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %fusion.107 = f32[32,32,8,512]{3,0,2,1} fusion(f32[512]{0} %get-tuple-element.1121, f32[4,4,256,512]{3,2,1,0} %get-tuple-element.1122, f32[32,32,8,256]{3,0,2,1} %get-tuple-element.970), kind=k
Output, calls=%fused_computation.105, metadata={op_type="Conv2D"...
     Allocation type: HLO temp
     ==========================

  18. Size: 16.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_17/Conv2D"
     Shape: f32[32,32,8,512]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %fusion.106 = f32[32,32,8,512]{3,0,2,1} fusion(f32[512]{0} %get-tuple-element.1123, f32[32,32,8,512]{3,0,2,1} %fusion.107, f32[4,4,512,512]{3,2,1,0} %get-tuple-element.1124), kind=kOutput, cal
ls=%fused_computation.104, metadata={op_type="Conv2D" op_name="t...
     Allocation type: HLO temp
     ==========================

  19. Size: 16.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_30/Conv2D"
     Shape: f32[32,64,16,128]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %fusion.97 = f32[32,64,16,128]{3,0,2,1} fusion(f32[128]{0} %get-tuple-element.1153, f32[32,64,16,128]{3,0,2,1} %fusion.98, f32[4,4,128,128]{3,2,1,0} %get-tuple-element.1154), kind=kOutput, cal
ls=%fused_computation.95, metadata={op_type="Conv2D" op_name="tp...
     Allocation type: HLO temp
     ==========================

    19. Size: 16.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_30/Conv2D"
     Shape: f32[32,64,16,128]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %fusion.97 = f32[32,64,16,128]{3,0,2,1} fusion(f32[128]{0} %get-tuple-element.1153, f32[32,64,16,128]{3,0,2,1} %fusion.98, f32[4,4,128,128]{3,2,1,0} %get-tuple-element.1154), kind=kOutput, cal
ls=%fused_computation.95, metadata={op_type="Conv2D" op_name="tp...
     Allocation type: HLO temp
     ==========================

  20. Size: 16.00M
     Operator: op_type="Conv2DBackpropInput" op_name="tpu_140280287273760/conv2d_transpose_2/conv2d_transpose"
     Shape: f32[32,64,16,128]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %fusion.98 = f32[32,64,16,128]{3,0,2,1} fusion(f32[4,4,128,512]{3,2,1,0} %get-tuple-element.1182, f32[128]{0} %get-tuple-element.1181, bf16[32,32,8,256]{3,0,2,1} %get-tuple-element.969, f32[32
,32,8,256]{3,0,2,1} %fusion.179, f32[32,64,16,128]{3,0,2,1} %rng...
     Allocation type: HLO temp
     ==========================

  21. Size: 16.00M
     Operator: op_type="RandomUniform" op_name="tpu_140280287273760/dropout_5/dropout/random_uniform/RandomUniform"
     Shape: f32[32,64,16,128]{3,0,2,1}
     Unpadded size: 16.00M
     XLA label: %rng.5 = f32[32,64,16,128]{3,0,2,1} rng(f32[] %constant.2, f32[] %constant.36), distribution=rng_uniform, metadata={op_type="RandomUniform" op_name="tpu_140280287273760/dropout_5/dropout/rando
m_uniform/RandomUniform"}
     Allocation type: HLO temp
     ==========================

  22. Size: 8.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_21/Conv2D"
     Shape: f32[32,16,4,1024]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %fusion.186 = f32[32,16,4,1024]{3,0,2,1} fusion(f32[1024]{0} %get-tuple-element.1133, f32[32,16,4,1024]{3,0,2,1} %fusion.187, f32[4,4,1024,1024]{3,2,1,0} %get-tuple-element.1134), kind=kOutput
, calls=%fused_computation.180, metadata={op_type="Conv2D" op_na...
     Allocation type: HLO temp
     ==========================

  23. Size: 8.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_28/Conv2D"
     Shape: f32[32,32,8,256]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %fusion.177 = f32[32,32,8,256]{3,0,2,1} fusion(f32[256]{0} %get-tuple-element.1147, f32[32,32,8,256]{3,0,2,1} %fusion.178, f32[4,4,256,256]{3,2,1,0} %get-tuple-element.1148), kind=kOutput, cal
ls=%fused_computation.171, metadata={op_type="Conv2D" op_name="t...
     Allocation type: HLO temp
     ==========================

  24. Size: 8.00M
     Operator: op_type="Conv2DBackpropInput" op_name="tpu_140280287273760/conv2d_transpose_1/conv2d_transpose"
     Shape: f32[32,32,8,256]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %fusion.178 = f32[32,32,8,256]{3,0,2,1} fusion(f32[4,4,256,1024]{3,2,1,0} %get-tuple-element.1180, f32[256]{0} %get-tuple-element.1179, bf16[32,16,4,512]{3,0,2,1} %get-tuple-element.971, f32[3
2,16,4,512]{3,0,2,1} %fusion.229, f32[32,32,8,256]{3,0,2,1} %rng...
     Allocation type: HLO temp
     ==========================

  25. Size: 8.00M
     Operator: op_type="RandomUniform" op_name="tpu_140280287273760/dropout_4/dropout/random_uniform/RandomUniform"
     Shape: f32[32,32,8,256]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %rng.4 = f32[32,32,8,256]{3,0,2,1} rng(f32[] %constant.2, f32[] %constant.36), distribution=rng_uniform, metadata={op_type="RandomUniform" op_name="tpu_140280287273760/dropout_4/dropout/random
_uniform/RandomUniform"}
     Allocation type: HLO temp
     ==========================

  26. Size: 8.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_20/Conv2D"
     Shape: f32[32,16,4,1024]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %fusion.187 = f32[32,16,4,1024]{3,0,2,1} fusion(f32[1024]{0} %get-tuple-element.1131, f32[4,4,512,1024]{3,2,1,0} %get-tuple-element.1132, f32[32,16,4,512]{3,0,2,1} %get-tuple-element.972), kin
d=kOutput, calls=%fused_computation.181, metadata={op_type="Conv...
     Allocation type: HLO temp
     ==========================

  27. Size: 8.00M
     Operator: op_type="RandomUniform" op_name="tpu_140280287273760/dropout/dropout/random_uniform/RandomUniform"
     Shape: f32[32,32,8,256]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %rng = f32[32,32,8,256]{3,0,2,1} rng(f32[] %constant.2, f32[] %constant.36), distribution=rng_uniform, metadata={op_type="RandomUniform" op_name="tpu_140280287273760/dropout/dropout/random_uni
form/RandomUniform"}
     Allocation type: HLO temp
     ==========================

  28. Size: 8.00M
     Operator: op_type="LeakyRelu" op_name="tpu_140280287273760/leaky_re_lu_2/LeakyRelu"
     Shape: bf16[32,64,16,128]{3,0,2,1}
     Unpadded size: 8.00M
     XLA label: %fusion.219 = (bf16[32,64,16,128]{3,0,2,1}, f32[32,64,16,128]{3,0,2,1}) fusion(f32[128]{0} %get-tuple-element.1111, f32[32,128,32,128]{3,0,2,1} %fusion.57, f32[4,4,128,128]{3,2,1,0} %get-tuple
-element.1112), kind=kOutput, calls=%fused_computation.209, meta...
     Allocation type: HLO temp
     ==========================

  29. Size: 4.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_26/Conv2D"
     Shape: f32[32,16,4,512]{3,0,2,1}
     Unpadded size: 4.00M
     XLA label: %fusion.227 = f32[32,16,4,512]{3,0,2,1} fusion(f32[512]{0} %get-tuple-element.1143, f32[32,16,4,512]{3,0,2,1} %fusion.228, f32[4,4,512,512]{3,2,1,0} %get-tuple-element.1144), kind=kOutput, cal
ls=%fused_computation.217, metadata={op_type="Conv2D" op_name="t...
     Allocation type: HLO temp
     ==========================

  30. Size: 4.00M
     Operator: op_type="Conv2DBackpropInput" op_name="tpu_140280287273760/conv2d_transpose/conv2d_transpose"
     Shape: f32[32,16,4,512]{3,0,2,1}
     Unpadded size: 4.00M
     XLA label: %fusion.228 = f32[32,16,4,512]{3,0,2,1} fusion(f32[32,8,2,1024]{3,0,2,1} %fusion.339, f32[4,4,512,1024]{3,2,1,0} %get-tuple-element.1178, f32[512]{0} %get-tuple-element.1177, f32[32,16,4,512]{
3,0,2,1} %rng.3), kind=kOutput, calls=%fused_computation.218, me...
     Allocation type: HLO temp
     ==========================


  31. Size: 4.00M
     Operator: op_type="RandomUniform" op_name="tpu_140280287273760/dropout_3/dropout/random_uniform/RandomUniform"
     Shape: f32[32,16,4,512]{3,0,2,1}
     Unpadded size: 4.00M
     XLA label: %rng.3 = f32[32,16,4,512]{3,0,2,1} rng(f32[] %constant.2, f32[] %constant.36), distribution=rng_uniform, metadata={op_type="RandomUniform" op_name="tpu_140280287273760/dropout_3/dropout/random
_uniform/RandomUniform"}
     Allocation type: HLO temp
     ==========================

  32. Size: 4.00M
     Operator: op_type="RandomUniform" op_name="tpu_140280287273760/dropout_1/dropout/random_uniform/RandomUniform"
     Shape: f32[32,16,4,512]{3,0,2,1}
     Unpadded size: 4.00M
     XLA label: %rng.1 = f32[32,16,4,512]{3,0,2,1} rng(f32[] %constant.2, f32[] %constant.36), distribution=rng_uniform, metadata={op_type="RandomUniform" op_name="tpu_140280287273760/dropout_1/dropout/random
_uniform/RandomUniform"}
     Allocation type: HLO temp
     ==========================

  33. Size: 4.00M
     Operator: op_type="LeakyRelu" op_name="tpu_140280287273760/leaky_re_lu_3/LeakyRelu"
     Shape: bf16[32,32,8,256]{3,0,2,1}
     Unpadded size: 4.00M
     XLA label: %fusion.301 = (bf16[32,32,8,256]{3,0,2,1}, f32[32,32,8,256]{3,0,2,1}) fusion(f32[32,32,8,256]{3,0,2,1} %rng, f32[256]{0} %get-tuple-element.1119, f32[32,64,16,256]{3,0,2,1} %fusion.79, f32[4,4
,256,256]{3,2,1,0} %get-tuple-element.1120), kind=kOutput, calls...
     Allocation type: HLO temp
     ==========================

  34. Size: 2.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_24/Conv2D"
     Shape: f32[32,8,2,1024]{3,0,2,1}
     Unpadded size: 2.00M
     XLA label: %fusion.338 = f32[32,8,2,1024]{3,0,2,1} fusion(f32[1024]{0} %get-tuple-element.1139, f32[4,4,1024,1024]{3,2,1,0} %get-tuple-element.1140, f32[32,8,2,1024]{3,0,2,1} %fusion.421), kind=kOutput,
calls=%fused_computation.326, metadata={op_type="Conv2D" op_name...
     Allocation type: HLO temp
     ==========================

  35. Size: 2.00M
     Operator: op_type="Conv2D" op_name="tpu_140280287273760/conv2d_23/Conv2D"
     Shape: f32[32,8,2,1024]{3,0,2,1}
     Unpadded size: 2.00M
     XLA label: %fusion.421 = f32[32,8,2,1024]{3,0,2,1} fusion(f32[1024]{0} %get-tuple-element.1137, f32[32,8,2,1024]{3,0,2,1} %rng.2, f32[32,16,4,1024]{3,0,2,1} %fusion.188, f32[4,4,1024,1024]{3,2,1,0} %get-
tuple-element.1138), kind=kOutput, calls=%fused_computation.407,...
     Allocation type: HLO temp
     ==========================
```

**Comment by ravikyram** [comment] 2019-07-18 10:37
@lminer 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github ](https://github.com/tensorflow/tensorflow/issues/new/choose)new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2019-07-25 05:20
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-25 05:20 UTC
Labels: TF 1.13, comp:tpus, stat:awaiting response, type:support

**Comment by nikhilanayak** [comment] 2021-12-12 20:38
I have a similar error when running my model. I created a basic Colab notebook that reproduces this error without actually loading data.
[https://colab.research.google.com/drive/1GPR8c1Buy6bpw1PQmiqYBUjdJfjI8_Mh?usp=sharing
](https://colab.research.google.com/drive/1GPR8c1Buy6bpw1PQmiqYBUjdJfjI8_Mh?usp=sharing)
This is running on the TPU Hardware Accelerator with a Standard Runtime. Everything else is standard for Colab and should be reproducible by running the notebook.
