### ISSUE TITLE
Setup instructions link broken

### ISSUE THREAD

**Issue by priteshgudge** [tensorflow/tensorflow#8118] opened 2017-03-06 09:36 UTC
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

The above link is broken. Loading leads to a 404 error.

**Comment by adyomin** [comment] 2017-03-06 09:41
This is being addressed by #8111.

**Comment by prb12** [comment] 2017-03-06 17:29
Closing as duplicate of #8111

**Closed by prb12** 2017-03-06 17:29 UTC
