### ISSUE TITLE
[XLA] Support unknown dimension.

### ISSUE THREAD

**Issue by mcourteaux** [tensorflow/tensorflow#25068] opened 2019-01-21 11:39 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source r1.13 w/ XLA
- **TensorFlow version (use command below)**: r1.13
- **Python version**: 3.6.7
- **Bazel version (if compiling from source)**: 0.18.1
- **GCC/Compiler version (if compiling from source)**: gcc 7.3.0
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: GTX 1080Ti
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I have a graph that selects certain "records" from some Tensors, based on an optimization strategy for relevance of the records in the current context. Details don't really matter here. The essence is that the `tf.boolean_mask()` returns a Tensor with a shape containing one unknown dimension. The result is that XLA is compiling the graph for every resulting length of that unknown dimension again and again. I can see that this is the issue, as multiple invocations of this graph lead to timings of being either very fast (3 ms) or very slow (350ms). The longer you wait, the more subgraphs XLA has compiled for a specific length and the more I see the faster invocations (where it does not need to compile anything).

Is there anything available or planned to tell XLA to not fix the unknown length for every invocation, such that the compilation happens only once, for a general length in that specific dimension?
Are there other tricks I can try to circumvent this issue?

### Source code / logs
```python
center = tf.placeholder(...)
diff = tf.subtract(data, center)
mask = tf.less(tf.abs(diff), 1.0) # select near data first
near_data = tf.boolean_mask(diff, mask)
# Now, perform actual computations on near_data
# because we know we can skip doing the computations on the other data, as the result
# will be 0, due to the large distance.
# However, now, near_data has a shape like [None, 5, 5] for example
# and XLA recompiles the graph for every length of the first dimension
```

**Comment by ymodak** [comment] 2019-01-25 04:06
@jlebar

**Comment by jlebar** [comment] 2019-01-25 17:39
Hi, thank you for the bug report.

> Is there anything available or planned to tell XLA to not fix the unknown length for every invocation, such that the compilation happens only once, for a general length in that specific dimension?

Not today.  We are working on changing this, but at the moment the assumption that all shapes are known at compile time is baked very deeply into XLA.

> Are there other tricks I can try to circumvent this issue?

Could you clarify for me: Is the large number of compilations hurting overall?  Like, if you trained to convergence with XLA, would this be slower because we're compiling so many things?

If not, then I'm not sure there's a bug here.

If so I'd say this is a bug in the heuristic we use to decide when to compile with XLA ("lazy compilation").  Perhaps we should tweak the heuristic, which AIUI is very simple right now.  I'm thinking maybe we could e.g. do some sort of exponential backoff, where we're eager to compile the first few clusters we see and then less eager to do new ones.

@sanjoy @thomasjoerg wdyt?

**Comment by sanjoy** [comment] 2019-01-25 18:04
> If so I'd say this is a bug in the heuristic we use to decide when to compile with XLA ("lazy compilation").

Another option is to avoid clustering ops like `tf.where` (which is what `tf.boolean_mask` boils down to IIUC) to avoid excessive recompilation.  This may be easier than it sounds since it does not need to be 100% correct -- we only need it for profitability and not correctness.

**Comment by sanjoy** [comment] 2019-01-25 18:07
> Perhaps we should tweak the heuristic

Btw, an easy way to do this is to change (increase in this case) the `kDefaultCompilationThreshold` field: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/xla_compilation_cache.h#L190

I can change this to be a flag settable from the `TF_XLA_FLAGS` environment variable if that will help.

**Comment by jlebar** [comment] 2019-01-26 00:38
Is it as simple as not clustering `tf.where`?  ISTM we'd have to sort of poison everything whose shape "inherits from" that op.

I agree it's easier because it's not correctness-critical, but if autoclustering makes something really slow, in a sense that *is* incorrect.

> Btw, an easy way to do this is to change (increase in this case) the kDefaultCompilationThreshold field:

We can do that, I'm just not sure a fixed threshold is the right approach, because if you run the computation long enough, eventually you're going to start hitting whatever fixed threshold we set.  Which is why I reached for exponential backoff: Eagerly trigger the first few compilations, then become less eager for future ones?

It may make sense to do both of the above things.

WDYT?

**Comment by sanjoy** [comment] 2019-01-26 00:50
> Is it as simple as not clustering tf.where? ISTM we'd have to sort of poison everything whose shape "inherits from" that op.

Yes, `tf.where` and everything that depends on it, up to a point (and we can imperfect heuristics to infer where this point is; e.g. we may say that *waves hands* we know that a GEMM of a tf.where usually contracts away the variably sized dimension so anything after the GEMM is fine; in some cases we may have even stronger guarantees, like a slice of a `tf.where`).

> Eagerly trigger the first few compilations, then become less eager for future ones?

I forgot to mention something pertinent:  we have a concept of a "megamorphic" cluster, which is a cluster with highly variable shapes that we refuse to compile.  If the extra compilation time is hurting performance _overall_ (i.e. slowing down time to convergence) then maybe we should be tweaking the `IsMegamorphic` heuristic.

But megamorphism is a binary property (a cluster is either megamorphic or it isn't), so I think exponential backoff will be an improvement.

**Comment by mcourteaux** [comment] 2019-01-26 01:16
@jlebar 
> > Are there other tricks I can try to circumvent this issue?
> 
> Could you clarify for me: Is the large number of compilations hurting overall? Like, if you trained to convergence with XLA, would this be slower because we're compiling so many things?

Yes, it hurts performance tremendously for my application. The number of resulting entries after the boolean_mask can be easily anywhere between 20 and 4000. This can take up to 3980*350 milliseconds of compiling, which is 23 minutes of just compiling the same code over and over again. I obviously disabled XLA for now, but if I remember correctly, having this much compiled code in memory began causing memory and performance problems.

However, right now, I've been thinking about this for a couple days, and I believe I might get away with making sure I have, for example, multiples of 50 entries after the `boolean_mask`, by padding the Tensor to the next multiple of 50. This would reduce the number of compiled graphs by 50, if I make sure that the `boolean_mask` part is not compiled by using the `jit_scope` technique, and specifically not including that part in the `jit_scope`.

However, the padding of the Tensors is a theoretically unnecessary and hacky, annoying step, causing unnecessary overhead (both in the padding-process and the now extra entries being processed).

@sanjoy 
> Yes, `tf.where` and everything that depends on it,

I'm not exactly following 100% with the technical details of XLA internals, but please note, that in my scenario, most of the calculations happen *after* the `boolean_mask` (or equivalently `tf.where`, as I learned here). So not clustering the part after the `tf.where`, would cause the critical part of my graph to be not fused, optimised, and compiled (if I understood this XLA principle correctly).

**Comment by sanjoy** [comment] 2019-01-26 03:17
> So not clustering the part after the `tf.where`, would cause the critical part of my graph to be not fused, optimised, and compiled (if I understood this XLA principle correctly).

That's true, but as a first step we want enabling XLA to do no harm.  Once we're at a point where enabling XLA is never a *regression* we can focus on increasing the set of situations where XLA is actually a net positive.  Given this framing:

> The number of resulting entries after the boolean_mask can be easily anywhere between 20 and 4000. This can take up to 3980*350 milliseconds of compiling, which is 23 minutes of just compiling the same code over and over again.

It looks like our megamorphic cluster detection is not working as intended.  Is it possible for you to share the full model?

**Comment by mcourteaux** [comment] 2019-01-30 17:58
> Is it possible for you to share the full model?

I'm afraid not. The complete model is quite large, and the setup required to run it is quite complex. Plus, I don't know if my employer would like me to throw this on the internet just yet. But the essentials are in my short piece of code in the question. I could try to set up an [MCVE](https://stackoverflow.com/help/mcve).

Can anyone shed some light on the feasibility or the plans for implementing XLA compilation for unknown tensor sizes?

**Comment by jlebar** [comment] 2019-01-30 18:09
> Can anyone shed some light on the feasibility or the plans for implementing XLA compilation for unknown tensor sizes?

I am afraid I cannot say much more than what I wrote in https://github.com/tensorflow/tensorflow/issues/25068#issuecomment-457653556.

**Comment by ymodak** [comment] 2019-02-22 06:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-02-22 06:33 UTC
Labels: comp:xla, stat:awaiting response
