### ISSUE TITLE
windows build failed with master branch

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#35977] opened 2020-01-17 09:04 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master 2.1.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source):  Visual Studio 2019 C++ compiler
- CUDA/cuDNN version: 10.2 / 7.6.5
- GPU model and memory:

RTX2080Ti GDDR6 11GB

**Describe the problem**
bazel build failed
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build //tensorflwo/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: D:/repo/tensorflow/tensorflow/BUILD:867:1: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1)
C:\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\ALAN-W~1\AppData\Local\Temp\Bazel.runfiles_t25kvwuy\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\ALAN-W~1\AppData\Local\Temp\Bazel.runfiles_t25kvwuy\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 48, in <module>
    import numpy as np
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: D:/repo/tensorflow/tensorflow/tools/pip_package/BUILD:229:1 Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1)
```

**Comment by alanpurple** [comment] 2020-01-17 09:07
some said this should be related to numpy environment, but branch r2.1 had no problem building tensorflow, and suddenly this came out with migration to master ( which accompanies bazel 1.2.1 )

BTW, last time I had numpy 1.18.1(in conda environment)

**Comment by gadagashwini** [comment] 2020-01-17 12:49
@alanpurple, Tensorflow 2.1 supports numpy =1.17.5.
Please take a look at similar issue [#35036](https://github.com/tensorflow/tensorflow/issues/35036)

**Comment by alanpurple** [comment] 2020-01-18 05:42
@gadagashwini 

setup.py says

'numpy >= 1.16.0, < 2.0'

**Comment by gadagashwini** [comment] 2020-01-20 13:27
@alanpurple,
Just to verify, did you install multiple versions of numpy.

**Comment by alanpurple** [comment] 2020-01-20 13:43
@gadagashwini 

of course not.

I've checked several times

**Comment by alanpurple** [comment] 2020-01-22 16:08
@ymodak 

after update another error came up.
this time, short and brief

```
ERROR: D:/repo/tensorflow/tensorflow/lite/core/api/BUILD:9:1: C++ compilation of rule '//tensorflow/lite/core/api:api' failed (Exit 2)
cl : Command line error D8021 : invalid numeric argument '/Wsign-compare'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 789.391s, Critical Path: 59.28s
INFO: 1173 processes: 1173 local.
FAILED: Build did NOT complete successfully
```

**Comment by gsdaemon** [comment] 2020-01-26 13:54
@alanpurple have you found a final solution? 

> @ymodak
> 
> after update another error came up.

What exactly did you updated?

Thanks

**Comment by alanpurple** [comment] 2020-01-26 15:13
@gsdaemon 
what i meant was "git pull" in master

**Comment by alanpurple** [comment] 2020-02-03 08:47
2/2/2020

still numpy error

**Comment by alanpurple** [comment] 2020-02-29 03:22
I've reinstalled whole anaconda environment, but still same error.

simple 'import numpy' with python works fine, but emit error only with tensorflow build

**Comment by alanpurple** [comment] 2020-02-29 03:55
solved.

uninstall conda numpy and install numpy with pip fixed this issue

tensorflow build has some problem with conda environment recently ( branch 2.1 was fine )

**Comment by henrysky** [comment] 2020-03-13 02:56
I am also suffering from the same problem with compiling tf2.2.0rc0 on windows.

It seems like somehow the PATH variable is not used correctly for that build.....

Numpy works fine on my Windows but if you do `$env:PATH=""` to reset the PATH variable in your current terminal, and then call python with fullpath to start python, and then `import numpy`, you will get the exact same error

**Comment by alanpurple** [comment] 2020-04-11 04:09
is this ever gonna be fixed?(is it possible?) I'm just curious

**Comment by gunan** [comment] 2020-04-13 17:51
I cannot reproduce the issue you are seeing, that is why this is taking so long.

@jjhelmus do you know of any conda + bazel experts who may be able to help with this issue?

**Comment by alanpurple** [comment] 2020-08-12 01:08
@gunan 

still happens with fresh windows 10 2004 installation + anaconda3-2020.07

**Comment by gunan** [comment] 2020-08-12 04:46
I am guessing this is a problem where in anaconda installation numpy headers end up in a different location.
As we do not build/test with anaconda, I would have to defer to anaconda TF maintainers.

@ymodak do we have a pointer to anaconda issue tracker?

**Comment by JRF63** [comment] 2020-11-17 15:01
The `_multiarray_umath` import error is supposedly fixed by putting `Library\bin` of the Anaconda env in `PATH` according to [this](https://github.com/numpy/numpy/issues/14770). But bazel overwrites `PATH` before invoking the script so doing that won't solve this issue.

```sh
ERROR: C:/users/rafael/source/repos/open-source/tensorflow/tensorflow/BUILD:1031:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/rafael/_bazel_rafael/y6bxy5a7/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Local/CUDA/v11.1
    SET PATH=C:\Users\Rafael\AppData\Local\Programs\msys64\usr\bin;C:\Users\Rafael\AppData\Local\Programs\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0
    SET PYTHON_BIN_PATH=C:/Local/Miniconda3/envs/ml/python.exe
    SET PYTHON_LIB_PATH=C:/Local/Miniconda3/envs/ml/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_NEED_CUDA=1
  C:/Users/Rafael/AppData/Local/Programs/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/bin/tensorflow/tf_python_api_gen_v2.genrule_script.sh
```

Noticing that `msys64\bin` is nonexistent, I made such a folder and copied the contents of `Library\bin`, `Scripts` and the dll's at the root of the env there to make it build successfully (v2.4.0rc1). For some reason, `Library\bin` alone is not enough.

**Comment by mohantym** [comment] 2021-09-03 11:02
Hi @alanpurple , Could you try with tested configuration mentioned here in this [link ](https://www.tensorflow.org/install/source_windows#gpu) .

**Closed** 2021-09-17 11:55 UTC
Labels: stat:awaiting response, type:build/install, stalled, subtype:windows, TF 2.1
