### ISSUE TITLE
The package org.tensorflow.lite.nnapi  does not exist

### ISSUE THREAD

**Issue by wcq19941215** [tensorflow/tensorflow#28585] opened 2019-05-10 07:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution：Ubuntu 16.04:
- Mobile device：Pixel 2
- TensorFlow installed from：source
- TensorFlow version:1.13.1
- Python version:3.6
- Bazel version :0.24.1

**Describe the current behavior**
when i run the demo which in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo
so ,I found the bug,don't have  org.tensorflow.lite.nnapi

**Comment by wcq19941215** [comment] 2019-05-10 07:33
Excuse me, how long will this nnapi package be completed in org.tensorflow:tensorflow-lite:0.0.0-nightly?

**Comment by gadagashwini** [comment] 2019-05-13 09:30
@wcq19941215 Could you provide more details about the bug and context? Also, it would be great if you can provide any commands you followed. Please provide as many details as possible to resolve the issue faster. Thanks!

**Comment by wcq19941215** [comment] 2019-05-13 09:50
@gadagashwini .The detail about bug in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java

and the code is:
import org.tensorflow.lite.nnapi.NnApiDelegate;

but I can't find the pack in org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly or org.tensorflow:tensorflow-lite:0.1.2-nightly
so ,i used bazel ,want to get a new tensorflowlite aar , of course ,i can get a org.tensorflow.lite.nnapi.NnApiDelegate but it don't work 
the bazel command i used is:
bazel build --cxxopt='--std=c++11' -c opt             \
  --config=android_arm --config=monolithic          \
  //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops

Thanks for your help.^v^

**Comment by anilsathyan7** [comment] 2019-05-15 08:37
Facing same issue in the tflite demo app (tflite-gpu-nightly)...

**Comment by wcq19941215** [comment] 2019-05-16 08:14
@anilsathyan7 Have you solved this problem?

**Comment by jdduke** [comment] 2019-05-16 15:45
Thanks for flagging the issue, this is an issue with how sources are aggregated in the aar that gets uploaded. We'll have it fixed in the night TFLite nightly (org.tensorflow:tensorflow-lite:0.0.0-nightly).

**Closed** 2019-05-16 16:54 UTC
Labels: TF 1.13, comp:lite, stat:awaiting tensorflower, type:bug/performance

**Comment by wcq19941215** [comment] 2019-05-17 00:23
@jdduke That ‘means you will add org.tensorflow.lite.nnapi to  org.tensorflow:tensorflow-lite:0.0.0-nightly no long?Thanks for your help

**Comment by chenjiaoAngel** [comment] 2019-06-11 07:43
Facing same issue in the tflite demo app (tflite-gpu-nightly)...
error: org.tensorflow.lite.nnapi does not exist
错误: 程序包org.tensorflow.lite.nnapi不存在

**Comment by wcq19941215** [comment] 2019-06-11 07:55
@chenjiaoAngel You can try to compile a local AAR yourself. I tried it and successfully compiled lite.nnapi aar , but it can't work. It should be caused by conflict with other packages.

**Comment by chenjiaoAngel** [comment] 2019-06-11 08:07
Hi, thank you!
SO the final solution is ? And how to build the local AAR ?
Best wishes,
Jiao
--------------------------
Tel: +8618101358192
Email: chenjiao04@baidu.com<mailto:chenjiao04@baidu.com>
BaiduHi: AngelCJ
--------------------------
Baidu

SYS



发件人: wcq19941215 <notifications@github.com>
答复: tensorflow/tensorflow <reply@reply.github.com>
日期: 2019年6月11日 星期二 下午4:03
收件人: tensorflow/tensorflow <tensorflow@noreply.github.com>
抄送: "Chen,Jiao(SYS)" <chenjiao04@baidu.com>, Mention <mention@noreply.github.com>
主题: Re: [tensorflow/tensorflow] The package org.tensorflow.lite.nnapi does not exist (#28585)


@chenjiaoAngel<https://github.com/chenjiaoAngel> You can try to compile a local AAR yourself. I tried it and successfully compiled lite.nnapi aar , but it can't work. It should be caused by conflict with other packages.

**Comment by wcq19941215** [comment] 2019-06-11 08:23
@chenjiaoAngel if you want to compile a local AAR ,you will use bazel.Finally, I did not solve this problem because there are other things that have been delayed.But I think that the latest aar package should have solved this problem, just need to update it in the AS.

**Comment by jdduke** [comment] 2019-06-11 15:15
The NNAPI delegate is in the latest TFLite nightly @ org.tensorflow:tensorflow-lite:0.0.0-nightly. The GPU delegate is in a separate .aar, and should be used *in addition to* the core TFLite nightly. Add org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly to your dependencies. Note that you might need to [clear your gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) for the new class to be visible.

**Comment by wcq19941215** [comment] 2019-06-12 00:45
@jdduke Thanks,It can work<v>

**Comment by wcq19941215** [comment] 2019-06-12 00:51
Since gradle automatically caches a copy of it while downloading it, gradle actually reloads the local cache when clean project
.SO the final solution is delete the ".gradle/caches/" ,and rebuild project.
On Windows: %USER_HOME%\.gradle/caches/
On Mac/Unix: $HOME/.gradle/caches/
