### ISSUE TITLE
Getting Bus error in Ubuntu Mate 

### ISSUE THREAD

**Issue by Adilhossain227** [tensorflow/tensorflow#34877] opened 2019-12-05 17:42 UTC
WARNING:tensorflow:From /home/odroid/tensorflow1/models/research/object_detection/utils/label_map_util.py:138: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From Object_detection_image.py:64: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From Object_detection_image.py:70: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Bus error

**Getting this Bus error in Ubuntu Mate on Odroid while running the object detection webcam script  , Using Python 3.5 and tensorflow version 1.14.0
Any idea how to solve that ??

**Comment by ravikyram** [comment] 2019-12-09 10:49
@Adilhossain227 

Request you to share simple stand alone code to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2019-12-20 08:48
@Adilhossain227 

Any update on this issue please. Thanks!

**Comment by Adilhossain227** [comment] 2019-12-23 16:19
`import os
import cv2
import numpy as np
import tensorflow as tf
import sys
sys.path.append("..")

# Import utilites
from utils import label_map_util
from utils import visualization_utils as vis_util

# Name of the directory containing the object detection module we're using
MODEL_NAME = 'inference_graph'

# Grab path to current working directory
CWD_PATH = os.getcwd()

PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,'frozen_inference_graph.pb')

# Path to label map file
PATH_TO_LABELS = os.path.join(CWD_PATH,'training','labelmap.pbtxt')

# Number of classes the object detector can identify
NUM_CLASSES = 1

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

# Load the Tensorflow model into memory.
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

    sess = tf.Session(graph=detection_graph)

image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')

# Number of objects detected
num_detections = detection_graph.get_tensor_by_name('num_detections:0')

video = cv2.VideoCapture(0)
ret = video.set(3,1280)
ret = video.set(4,720)

while(True):

    ret, frame = video.read()
    frame_expanded = np.expand_dims(frame, axis=0)

    (boxes, scores, classes, num) = sess.run(
        [detection_boxes, detection_scores, detection_classes, num_detections],
        feed_dict={image_tensor: frame_expanded})

    vis_util.visualize_boxes_and_labels_on_image_array(
        frame,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=8,
        min_score_thresh=0.60)
    cv2.imshow('Object detector', frame)

    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()
`

**Comment by ravikyram** [comment] 2019-12-24 10:04
@Adilhossain227 

Looks like code is incomplete.Request you to share colab link or simple stand alone code with supporting files to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-09 12:35
It has been 16 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-01-09 14:29
@Adilhossain227 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-01-10 10:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-01-10 10:45 UTC
Labels: TF 1.14, stat:awaiting response, type:support
