### ISSUE TITLE
[Feature request] tfcompile AOT gonna support tensorflow_transform?

### ISSUE THREAD

**Issue by ranqizhu** [tensorflow/tensorflow#22744] opened 2018-10-04 19:29 UTC
Transform is out side of the graph. It could be great to have this support so that people do not have to re-implement this part in c++ while serve in c++ environment. 

The other way I can think of to solve this is: is it possible to make arbitrary feature transform a part of the tensorflow graph by modifying it afterwards using graph transform tools?

**Comment by tensorflowbutler** [comment] 2018-10-05 06:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment] 2018-10-15 19:15
@sanjoy Hi, could you please look into this issue ?

**Comment by sanjoy** [comment] 2018-10-16 05:03
I'm not familiar with tensorflow_transform but if it produces a TF graph that XLA can compile then it should be okay to use it with tfcompile.  tfcompile compiles a TF graph to machine code via XLA; so any TF graph that XLA supports is fine as input, it doesn't matter whether the TF graph was produced via tensorflow_transform or some other means.

Perhaps you could try compiling a graph produced by tensorflow_transform using tfcompile?

**Comment by harshini-gadige** [comment] 2018-10-17 21:12
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by harshini-gadige** [comment] 2018-10-29 22:34
@ranqizhu  Is this still an issue ?

**Comment by harshini-gadige** [comment] 2018-11-01 20:47
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-01 20:47 UTC
Labels: stat:awaiting response, type:feature
