### ISSUE TITLE
Wrong maximum value passed in the positional encoding for the Transformer model

### ISSUE THREAD

**Issue by s0urcer** [tensorflow/tensorflow#43674] opened 2020-09-30 14:28 UTC
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/text/transformer

## Description of issue (what needs changing):
When creating positional encoding vectors set we specify maximum_position_encoding which should be equal to the maximum possible length of the sequence fed into the model. So it must be equal to MAX_LENGTH (which is 40). In your sample it's equal to the vocabulary length (or 10000).

### Clear description
When max length is so big, the difference between neighboring elements pos encoding is very subtle and it's harder for the model to grasp it. And logically the value is incorrect.

### Correct links

Not applicable.

### Parameters defined

Not applicable.

### Returns defined

Not applicable.

### Raises listed and defined

No error. Just typo in the sample code.

### Usage example

No.

### Request visuals, if applicable

No.

### Submit a pull request?

No.

**Comment by HelioStrike** [comment] 2020-10-02 04:06
@s0urcer I think it's fixed now.

**Comment by adithyaakrishna** [comment] 2020-10-02 20:29
If the issue is open, Can I work on this?🚀

**Comment by Harsh188** [comment] 2020-10-04 03:58
@adithyaakrishna Feel free to open up a PR

**Comment by adithyaakrishna** [comment] 2020-10-04 05:56
Okay, Thanks! @Harsh188 :)

**Comment by MarkDaoust** [comment] 2022-03-04 19:29
> MAX_LENGTH (which is 40).

Yeah, that's only in the `translate` class. During training I see sequences up to 400 tokens. 
This aspect of the code could be clearer.

I'm sending a fix.

> the difference between neighboring elements pos encoding is very subtle and it's harder for the model to grasp it.

I disagree on this point. Each `(sin,cos)` pair has a fixed rotation rate. Spinning them for longer doesn't make them more or less different from time-step to time-step.

**Closed** 2022-03-05 00:18 UTC
Labels: type:docs-bug, stat:awaiting tensorflower, comp:keras
