### ISSUE TITLE
tf.split_v results in unknown shape size

### ISSUE THREAD

**Issue by Trickery94** [tensorflow/tensorflow#6186] opened 2016-12-08 09:00 UTC
### Environment info
Operating System:
Linux Mint 17.3 3.19.0-32-generic
Tensorflow Version 0.12.0-rc0 (https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0rc0-cp34-cp34m-linux_x86_64.whl)

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
`
tf.split_v(tf.placeholder(tf.float32, shape=[10, 32, 32, 3]), [3,7], 0)
`
The result is of shape (?, ?, ?, ?). 

However, when using split for equal length splits it shows the resulting shape:
`
tf.split(0, 2, tf.placeholder(tf.float32, shape=[10, 32, 32, 3]))
`

**Comment by michaelisard** [comment] 2016-12-08 17:59
The shape inference for SplitV is in [array_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc#L421) and according to the comment it assumes that the value of size_splits is not known at shape inference time, and hence returns unknown shape as you report. I suspect that you could add logic like that in e.g. [image_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc#L39) which checks to see if the input value is known at inference time, and reports the correct shape if so.

I am marking contributions welcome: please feel free to submit a PR with this change and reference this issue.

**Comment by ekelsen** [comment] 2016-12-09 20:30
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/5977.

Note that the code in question does not just _assume_ the value is not known at shape inference time, it is in fact impossible for the C++ shape inference code to inspect the contents of Tensor's during shape inference.  That the Tensor was a constant in the python code is lost by the time it gets to the shape inference.  We can hack this by setting the output shapes in the python as well.

**Comment by vrv** [comment] 2016-12-09 20:42
@ekelsen: that's actually not true anymore -- if the tensor is a constant in the graph, the shape inference code can actually ask for the values in the shape function, and output a more specific shape if it is available.

Example: https://github.com/tensorflow/tensorflow/blob/4172ca2cd7ac34be67bda2600944d284e8907b95/tensorflow/core/framework/common_shape_fns.cc#L598

**Comment by ekelsen** [comment] 2016-12-09 21:10
Well in that case we can fix it in the C++ code :) thanks for the heads up @vrv.

**Comment by AnishShah** [comment] 2016-12-10 06:40
I have opened a PR for this where I have fix this using C++ code. Should I reference #5977 in that PR too?

**Comment by ekelsen** [comment] 2016-12-10 21:50
Yes, please do.  Thanks for the contribution!

**Closed** 2016-12-15 22:48 UTC
Labels: contributions welcome
