### ISSUE TITLE
Got Segmentation fault when calling tflite::Model::UnPack() 

### ISSUE THREAD

**Issue by AssassinGQ** [tensorflow/tensorflow#43416] opened 2020-09-21 06:47 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):master
- Python version:3.7
- Bazel version (if compiling from source):2.0.0
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Pic.1:
![image](https://user-images.githubusercontent.com/36526001/93737881-e3d3a580-fc16-11ea-8c06-4fb29ea06305.png)
Pic.2:
![image](https://user-images.githubusercontent.com/36526001/93738189-bdfad080-fc17-11ea-8a54-bef065ec5ad7.png)
Pic.3:
![image](https://user-images.githubusercontent.com/36526001/93738347-25b11b80-fc18-11ea-9b6b-235368499445.png)

I'm doing benchmark on cartoongan model from tensorflow hub(https://tfhub.dev/sayakpaul/lite-model/cartoongan/int8/1). When I adding a line "ModelT *modelT = model_->GetModel()->UnPack();" to  tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc:712(Pic.1) for printing some debug info, I got a "Segmentation fault". I have found out that it happens when flatbuffers UnPacking zero_point in QuantizationParameters(Pic.2&3). 

**Describe the expected behavior**
Calling tflite::Model::UnPack() should return tflite::ModelT

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-09-21 06:53
@AssassinGQ 

Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by AssassinGQ** [comment] 2020-09-21 07:21
Just use this file to cover tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc on master and bench model in this link: https://tfhub.dev/sayakpaul/lite-model/cartoongan/int8/1

**Comment by AssassinGQ** [comment] 2020-09-21 07:38
Sorry  there are some mistake in issue describe, the version of bazel is 3.1.0.

Just using this file to cover tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc on master and benching model in this link: https://tfhub.dev/sayakpaul/lite-model/cartoongan/int8/1 will  reproduce the issue.
[benchmark_tflite_model.cc.txt](https://github.com/tensorflow/tensorflow/files/5253964/benchmark_tflite_model.cc.txt)

**Comment by AssassinGQ** [comment] 2020-10-23 02:43
@multiverse-tf 
How is it going？

**Comment by sushreebarsa** [comment] 2021-08-09 15:17
@AssassinGQ  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-23 16:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite
