### ISSUE TITLE
tf.data.iterator make_initializer multiple creates new ops instead of using old

### ISSUE THREAD

**Issue by tintinxue1** [tensorflow/tensorflow#31061] opened 2019-07-26 08:53 UTC
System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
    TensorFlow installed from (source or binary): binary
    TensorFlow version (use command below): v1.13.1
    Python version: 3.7.3
    Bazel version (if compiling from source): NA
    GCC/Compiler version (if compiling from source): NA
    CUDA/cuDNN version: 9.2 / 7.6.0
    GPU model and memory: GeForce GTX 1080 Ti

Describe the current behavior:
   I'm using tf.data.dataset.Iterator.from_structure to make an iterator. And I defined a separate function to use iterator.make_initializer(dataset) to make new initializer after a certain time interval (because I'm doing experiment for growing dataset). The dataset is created using tf.data.Dataset.from_tensor_slices((imgs,labels)). But each time this function is called, it creates new ops causing the memory to grow. 
   I know i can use placeholder, but I want to use tf.data.dataset as it's faster. 
   I've tried using with tf.name_scope('dataset'): when creating the tf.data.Dataset (also tried tf.variable_scope). 
   But it simply avoid the name clashes by creating new op so instead of  dataset\something it gives dataset_1\something etc.  

Observed behavior: new ops are created instead of reusing

Describe the expected behavior
Should reuse the variables and not create new ops.

**Comment by tintinxue1** [comment] 2019-07-26 08:56
it seems like tf.data.dataset is having the same behaviour as tf.Variable() instead of tf.get_variable(). with tf.Variable(), even with tf.name_scope() or tf.variable_scope() it avoids the name clashes instead of reusing the variables.

**Comment by rmothukuru** [comment] 2019-07-30 10:12
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2019-08-05 12:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-08-05 12:31 UTC
Labels: TF 1.13, comp:data, stat:awaiting response, type:support
