### ISSUE TITLE
Win 10 Import Error: Failed to load the native TensorFlow runtime TF-GPU(both1.13 and 2.0) 

### ISSUE THREAD

**Issue by Pure-Entropy** [tensorflow/tensorflow#26364] opened 2019-03-05 14:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow-gpu-1.13.1
- Python version: 3.6.4
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: CUDA 10.1/cuDNN7.5
- GPU model and memory: 930mx 2GB

**Describe the current behavior**  
Fails to run because of an Import Error whenever I try to import tf-GPU,
**Describe the expected behavior**  
Expected it to import so I could use it.
**Code to reproduce the issue**  
import tensorflow as tf

**Other info / logs**  
---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

c:\users\ent\appdata\local\programs\python\python36\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

c:\users\ent\appdata\local\programs\python\python36\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-602d2050546b> in <module>
----> 1 import tensorflow as tf
      2 import time
      3 import os
      4 from tensorflow.examples.tutorials.mnist import input_data
      5 

c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\ent\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\ent\appdata\local\programs\python\python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\ent\appdata\local\programs\python\python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.  
```
---------------------------------------------------------------------------

**Comment by felix-hilden** [comment] 2019-03-05 14:53
+1 with almost exactly same specs. GPU is a 1050 Ti and Python 3.7.2

**Comment by damienstanton** [comment] 2019-03-05 15:00
Same is occurring for me. Similar specs: 1050Ti, Python 3.6.8, tf-nightly-gpu, same CUDA/CuDNN versions. I can also confirm there are no path issues with the CUDA components. Downgrading CUDA is not an option for me, as the 9.0 installers break my PhysX driver and Visual Studio integrations.

**Comment by GregorKovalcik** [comment] 2019-03-05 16:50
> CUDA/cuDNN version: CUDA 10.1/cuDNN7.5

You have to use CUDA 10.0 for tensorflow-gpu-1.13.1 (don't forget to download cuDNN 7.5 for CUDA 10.0 too).

**Comment by rootkitchao** [comment] 2019-03-05 17:32
I think you should use CUDA10.0 instead of CUDA10.1.The tensorflow-gpu compiled by pip install specifies the cuda version, which needs to be accurate to the specific subversion.

**Comment by damienstanton** [comment] 2019-03-05 19:21
Confirmed to be working using CUDA 10.0 and CuDNN 7.5 for 10.0.

**Comment by Pure-Entropy** [comment] 2019-03-06 11:11
Thanks for the information. Will be downloading the cudnn and cuda toolkit today. Hopefully I can run them and close this issue.

**Comment by Pure-Entropy** [comment] 2019-03-08 09:16
> Confirmed to be working using CUDA 10.0 and CuDNN 7.5 for 10.0.

How did you get it to work? 'mine failed yesterday. It just failed with CUDA 9.0 Too. I am beginning to feel like giving up to be honest

**Comment by racinmat** [comment] 2019-03-08 17:15
@Pure-Entropy  and which version of Tensorflow did you try with CUDA 9.0? Because the 1.13 version does not work with CUDA 9.0 afaik.

**Comment by ymodak** [comment] 2019-03-08 21:14
@Pure-Entropy Please use cuda 1.0 against TF 1.13.1 and in addition to that make sure you add cuda, cudnn paths to your environment. Please take a look at similar [issue](https://github.com/tensorflow/tensorflow/issues/26059)

**Comment by Pure-Entropy** [comment] 2019-03-11 14:58
> @Pure-Entropy Please use cuda 10.0 against TF 1.13.1 and in addition to that make sure you add cuda, cudnn paths to your environment. Please take a look at similar [issue](https://github.com/tensorflow/tensorflow/issues/26059)

I honestly do not know where I am going wrong here. I just reinstalled CUDA 10.0 and cuDNN 10.0 the other day. I am just from copying the path variables EXACTLY as they are on the install page. 

the reinstalled TF13.1 still refuses to work. PyTorch manages to recognise my GPU and work without any setup whatsoever, I got it to work just as soon as I installed CUDA and cuDNN even without the path variable modifications. It is the TensorFlows that keep refusing to work. 
(This link )[https://imgur.com/a/US9LJjj] shows my environment's PATH variable. this is the system PATH.

**Comment by Pure-Entropy** [comment] 2019-03-11 15:01
> @Pure-Entropy and which version of Tensorflow did you try with CUDA 9.0? Because the 1.13 version does not work with CUDA 9.0 afaik.

it was both 1.13 and 2.0.

**Comment by racinmat** [comment] 2019-03-11 16:02
1) There is no cuDNN 10.0. The newest CuDNN version is 7.5. 
The tensorflow 1.13.1 works on Windows with GPU support, I have it myself. 

2) Maybe a bit silly question, but are you using 64bit python? Because the version (32/64bit) of DLL must match the python version. Otherwise it complains about missing DLL even when it's present.

**Comment by ymodak** [comment] 2019-03-11 17:14
You need to add sub folders: ```bin``` , ```include``` and ```lib``` to the path. I see that ```lib and include``` folder's are not added to the path. Can you please try adding them as well?

**Comment by ymodak** [comment] 2019-03-19 17:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-19 17:43 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install

**Comment by Pure-Entropy** [comment] 2019-03-24 20:20
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

No need to reopen. The issue was solved by adding `include` to the path. Thank you

**Comment by Pure-Entropy** [comment] 2019-03-24 20:36
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

I updated the docs and did a PR for the updated fork. the instructions did not tell us to add `https://github.com/tensorflow` to the PATH variable.

Please review it.

**Comment by ymodak** [comment] 2019-03-25 21:02
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by KevorkSulahian** [comment] 2019-03-30 06:05
where should i add the bin, include lib? or how should i ?

**Comment by KevorkSulahian** [comment] 2019-03-30 06:36
> where should i add the bin, include lib? or how should i ?
never mind, just had to move the Cudnn files into cuda,
here is the [link](https://medium.com/@akshaysin_86681/installing-cuda-and-cudnn-on-windows-10-f735585159f7) just in case anyone needs it in the future

thanks ymodak

**Comment by EliasHasle** [comment] 2019-05-08 09:16
> > Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
> 
> I updated the docs and did a PR for the updated fork. the instructions did not tell us to add `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include` to the PATH variable.
> 
> Please review it.

It is not necessary to add `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include` to the PATH variable. My guess is that you (and others who think that is the solution) changed something else, such as restarting your computer or opening a new PowerShell console, which will load updated environment variables.

**Comment by minhhieugma** [comment] 2019-06-01 10:04
I'd like to confirm that it works on cuda 10.0, not on 10.1.
I installed 2 things:
- cuda_10.0.130_win10_network.exe
- cudnn-10.0-windows10-x64-v7.6.0.64.zip
