### ISSUE TITLE
Open source performance benchmarks

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#2004] opened 2016-04-18 03:09 UTC
In #2001 we discussed about the performance benchmark, I suggest maybe we can have some benchmark code (in automatically tests or something else) for common NN architecture like Alex, Inception v3, ResNet  on some famous dataset like cifar10, cifar100, ImageNet.
By doing this, we can continuously trace our performance when we update our algorithms or code.
Also, we could show our benchmark test on our website or github page.

**Comment by fayeshine** [comment] 2016-04-18 03:29
Besides, if we plan to have the performance benchmark code, maybe I could help some part

**Comment by vrv** [comment] 2016-04-18 03:35
@ebrevdo has worked on benchmarking tools in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/benchmark.py

We use this internally to catch regressions because we log them to internal databases.  We'd like to have this also in the OSS world too, but we haven't figured out all the tooling yet.

**Comment by ebrevdo** [comment] 2016-06-10 18:39
The main blocker I see now is a way to write the [TestResults](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/test_log.proto) protos we generate into a BigQuery table; which means being able to automatically generate and update the table's structure when the TestResults proto is updated.

This tool could be a start, but I'm unaware of who is maintaining it and it doesn't support proto3 format (which TestReport is):

https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema

Anyone interested in getting this working?  I don't have the bandwidth...  marking as contributions welcome.

**Comment by ebrevdo** [comment] 2016-06-10 18:40
@caisq  feel free to remove self; just wanted you on the participants list so you see relevant updates here.

**Comment by tfboyd** [comment] 2017-06-16 17:26
https://www.tensorflow.org/performance/benchmarks  and we have started to updated code other teams are using for benchmarks to try and ensure best practices.

**Closed by tfboyd** 2017-06-16 17:26 UTC
Labels: stat:contributions welcome
