### ISSUE TITLE
tf.convert_to_tensor throws ValueError for tf.float64 tensor and dtype=tf.float32 instead of silently casting

### ISSUE THREAD

**Issue by gittar** [tensorflow/tensorflow#39554] opened 2020-05-14 18:55 UTC
I *think* this is a bug, at least it is inconsistent behavior.

**System information**
- custom code? no, just the minimal example to reproduce the error message
- OS Platform and Distribution: Linux Ubuntu 18.04
- PC
- TensorFlow installed from (source or binary): binary
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7.6 (default, Jan  8 2020, 19:59:22)

**Describe the current behavior**
tf.convert_to_tensor accepts numpy np.float64 arrays when dtype is tf.float32 (and returns a tf.float32 Tensor).

If the argument however is a tensor of type tf.float64, an error is thrown instead of returning a tf.float32 tensor
**Describe the expected behavior**
I would expect **tf.convert_to_tensor** to treat the float64-Tensor and the float64-ndarray the same. In my understanding it is in general use for all tensorflow operators and should accept a broad range of inputs. I see no reason to reject Tensors, but accept ndarrays.
**Standalone code to reproduce the issue**
Script:
```
import numpy as np
import tensorflow as tf
v_np = np.ones(shape=(3), dtype=np.float64)
print("A",v_np,type(v_np[0]))
v_tf = tf.constant([1.0,1,1], dtype=tf.float64)
print("B",v_tf,type(v_tf[0].numpy()))
print("C",tf.convert_to_tensor(v_np,dtype=tf.float32))
print("D",tf.convert_to_tensor(v_tf,dtype=tf.float32))
```
Output:
```
A [1. 1. 1.] <class 'numpy.float64'>
B tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64) <class 'numpy.float64'>
C tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
Traceback (most recent call last):
  File "/home/user/TENSORFLOW/myapp-tf/bug.py", line 9, in <module>
    print("D",tf.convert_to_tensor(v_tf,dtype=tf.float32))
  File "/home/user/miniconda2/envs/tf20b/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1256, in convert_to_tensor_v2
    as_ref=False)
  File "/home/user/miniconda2/envs/tf20b/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1290, in convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: <tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>
```

**Comment by Saduf2019** [comment] 2020-05-15 10:27
@gittar 
Please refer to this [link](https://stackoverflow.com/questions/54798223/tensor-conversion-requested-dtype-int32-for-tensor-with-dtype-int64-while-esti) , [link2](https://stackoverflow.com/questions/57464461/tensor-conversion-requested-dtype-float64-for-tensor-with-dtype-float32) and let us know if it helps resolve your issue.
#38225

**Comment by gittar** [comment] 2020-05-21 10:17
Yes. I can fix my program by casting the tf.float64 value to tf.float32 before invoking 
tf.convert_to_tensor(v_np,dtype=tf.float32)
Which would be a superflous call in this case.

The real context of my question is a function f() like
```
def f(X):
     mytensor = tf.convert_to_tensor(X, dtype=tf.float32)
     (rest of the function working with the tf.float32 tensor "mytensor")
```
I would like my function to accept both numpy array and tf.Tensor and both float32 and float64 and convert it all to tf.float32 tensors. Currently the tf.convert_to_tensor call  accepts numpy arrays of float64 and float32 and tf.Tensor with tf.float32, but throws an error for tf.float64. 

Why is it designed like that? If no silent conversion from 64bit to 32bit was desired it should reject also numpy arrays of float64. To get around  this in the above function I would need to do something like
```
def f(X):
     if isinstance(X,tf.Tensor) and (X.dtype == tf.float64):
          mytensor = tf.cast(X,dtype=tf.float32)
     else:
          mytensor = tf.convert_to_tensor(X, dtype=tf.float32)
     (rest of the function working with the tf.float32 tensor)
```
which is quite inelegant.

For better consistency I would propose to let tf.convert_to_tensor( X , dtype=tf.float32)  also accept values for X which are Tensors of type tf.float64 (and vice versa if conversion to tf.float64 is desired).

I understand that may be a breaking change for programs indeed relying on this (IMO) inconsistency, but I still would do it.

**Comment by saikumarchalla** [comment] 2021-05-24 03:22
Was able to reproduce the issue in TF-Nightly.Please find the attached [gist](https://colab.research.google.com/gist/saikumarchalla/f13d0fcfe0773594f96832f80f1650d8/untitled79.ipynb).Thanks!

**Comment by mihaimaruseac** [comment] 2021-11-14 17:27
Is this still an issue?

**Comment by gittar** [comment] 2021-11-21 00:18
If it has not been changed I would still see this as inconsistency as detailed in my comment from May 21, 2020. Since there exists a workaround by doing casting beforehand it will not really block anyone  but I guess tensorflow should strive for consistency to avoid users running into surprising problems.

**Comment by knkumar** [comment] 2022-03-18 00:41
any updates?

**Comment by mohantym** [comment] 2022-04-04 15:35
It is still replicating in the 2.8 version. Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/2febb530f924b49b6bab45a29829d355/git_39334.ipynb#scrollTo=ncuzgY60KGat) for reference. Thanks!

**Comment by SuryanarayanaY** [comment] 2022-12-11 14:44
Hi @gittar,

We have `tf.cast` for casting a Tensor to required Tensor type.
The main purpose of function `tf.convert_to_tensor` is:

> This function converts Python objects of various types to Tensor objects.

By using `tf.convert_to_tensor` we can convert `np.float32 to tf.float64 `or `np.float64 to tf.float32` or `np.int32 to tf.float64 ` or `np.float64 to tf.int32` etc which means the functionality here is not related to `32 Bit vs 64 Bit` instead it is `numpy to TF Tensor` conversion only.

This function raises error if you try to convert `tf.float64 to tf.float32` or ` tf.float64 to tf.float32` or to that matter any conversion that is not original Tensor itself . It only accepts conversion of a Tensor to Same type Tensor only as there is no harm in converting the Tensor to same Tensor which is extended functionality apart from converting Python objects to Tensors.The function will not accept converting to other dtype Tensors.If you observe any other conversions accepted among Tensors of different dtypes please let us know and if so then we can push to extend the functionality to all dtypes.I tried this function on different conversions among Tensors and it wont accept conversions to any other type as per attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/5971a63163804e8fdbed84e1725e5064/-39554.ipynb).

The function `tf.convert_to_tensor` if supplied with Tensor then the conversion should also be of same type Tensor.Otherwise it will raise Value Error which is intended functionality and furthermore we have `tf.cast ` for casting functionality. Clubbing the functionality of `tf.cast` with `tf.convert_to_tensor` can create confusions and both should be regarded as individual functionalities and in that way we can maintain Modulairity better. 

Thankyou!

**Comment by gittar** [comment] 2022-12-11 15:30
Your line of argumentation sounds very reasonable. No objection from my side to leave the current behavior as is. I just stumbled at that time over an apparent inconsistency which you just explained clearly as intended behavior.

**Comment by SuryanarayanaY** [comment] 2022-12-12 13:26
Hi @gittar ,

Thanks for quick response and confirmation.We value your contribution and suggestions and request you to continue doing same to make the product even better. Shall we close this issue now ?

Thankyou!

**Comment by gittar** [comment] 2022-12-12 14:43
Hi @SuryanarayanaY,the issued can be closed. Thanks for picking it up from the backlog :-)RegardsBernd (gittar)--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 12/12/2022, 14:26 SuryanarayanaY ***@***.***> wrote:

   
  Hi @gittar , 
  Thanks for quick response and confirmation.We value your contribution and suggestions and request you to continue doing same to make the product even better. Shall we close this issue now ? 
  Thankyou!

**Comment by SuryanarayanaY** [comment] 2022-12-13 10:53
Closing as completed as per user's confirmation.

Thanks!

**Closed by SuryanarayanaY** 2022-12-13 10:53 UTC
Labels: type:bug, comp:ops, TF 2.9
