### ISSUE TITLE
Why my modelcheckpoint is not saving weights based on best val_accuracy?

### ISSUE THREAD

**Issue by mobassir94** [tensorflow/tensorflow#38680] opened 2020-04-19 07:18 UTC
the code i tried in kaggle kernel for saving weights is this :

`model_path = '/kaggle/working/jigsawMultilingual.h5'
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler

checkpoint = ModelCheckpoint(model_path, monitor='val_accuracy', mode='max', save_best_only=True)
es = EarlyStopping(monitor='val_accuracy', mode='max', patience=2, 
                   restore_best_weights=True, verbose=1)
lr_callback = LearningRateScheduler(lrfn, verbose=1)

callback_list = [checkpoint, es, lr_callback]

%%time
N_STEPS = x_train.shape[0] // BATCH_SIZE
EPOCHS = 4
train_history = model.fit(
    train_dataset,
    steps_per_epoch=N_STEPS,
    validation_data=valid_dataset,
    callbacks=callback_list,
    epochs=EPOCHS
)

 # have a look at the training results : 

Train for 4414 steps, validate for 63 steps

Epoch 00001: LearningRateScheduler reducing learning rate to 1e-06.
Epoch 1/4
4414/4414 [==============================] - 2301s 521ms/step - loss: 0.3190 - auc: 0.9200 - val_loss: 0.2821 - val_auc: 0.9171

Epoch 00002: LearningRateScheduler reducing learning rate to 3.142857142857143e-06.
Epoch 2/4
4414/4414 [==============================] - 2090s 473ms/step - loss: 0.1909 - auc: 0.9718 - val_loss: 0.2581 - val_auc: 0.9249

Epoch 00003: LearningRateScheduler reducing learning rate to 5.285714285714285e-06.
Epoch 3/4
4414/4414 [==============================] - 2090s 473ms/step - loss: 0.1639 - auc: 0.9791 - val_loss: 0.2730 - val_auc: 0.9214

Epoch 00004: LearningRateScheduler reducing learning rate to 7.4285714285714275e-06.
Epoch 4/4
4414/4414 [==============================] - 2090s 473ms/step - loss: 0.1491 - auc: 0.9826 - val_loss: 0.2761 - val_auc: 0.9252
CPU times: user 9min 46s, sys: 35.5 s, total: 10min 21s
Wall time: 2h 22min 50s`

but i don't see any model in this path : model_path = '/kaggle/working/jigsawMultilingual.h5'

note that i also tried "checkpoint = ModelCheckpoint(model_path, monitor='val_acc', mode='max', save_best_only=True)" and it also didn't work

i mean jigsawMultilingual.h5 is not saving in '/kaggle/working/' directory

is it happening because validation accuracy is improving every time? but still it should save the model after 1st epoch,right?

**Comment by amahendrakar** [comment] 2020-04-20 12:07
@mobassir94,
While running the code, I'm facing an error stating `NameError: name 'lrfn' is not defined`.

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. 

Also, please add  ```  (i.e. three backticks) to your code to preserve the indentation and formatting. Thanks!

**Comment by mobassir94** [comment] 2020-04-20 19:48
Full code here : https://www.kaggle.com/mobassir/understanding-cross-lingual-models

From cell 8 till end of the jupyter notebook

**Comment by amahendrakar** [comment] 2020-04-22 08:49
@mobassir94,
Is this a duplicate of issue [#38683](https://github.com/tensorflow/tensorflow/issues/38683)?
In this case, could you please close this issue as it is already being tracked there.

**Closed** 2020-04-22 11:23 UTC
Labels: stat:awaiting response, type:support
