### ISSUE TITLE
TFLite failed to allocate tensors when changing the input size

### ISSUE THREAD

**Issue by shawn-tian** [tensorflow/tensorflow#23399] opened 2018-10-31 09:11 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 7 simulator
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): master
- Python version: 2.7
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
I convert the TF model to TFLite model by tflite_convert command with float inference_type, and input_shapes set to 1,W,H,3; when I run the model with input shape W*H, **it works well**; However, when I **change** the input shapes to different values, it would give error like "tensorflow/contrib/lite/kernels/kernel_util.cc:125 d1 == d2 || d1 == 1 || d2 == 1 was not true; Node number xx (ADD) failed to prepare" for tf.add op. Similar errors appear for other ops like CONCAT and RESHAPE. When I set breakpoints in tflite codes, it seems to always check/use the tensor shapes when converting the model, even the input shape has changed. 

Part of the codes are like this:

```
int input = interpreter->inputs()[0];
    interpreter->ResizeInputTensor(input, new_input_sizes);
    if (interpreter->AllocateTensors() != kTfLiteOk) {
        NSLog(@"Failed to allocate tensors for model.");
        exit(-1);
    }
```

**Comment by shawn-tian** [comment] 2018-10-31 09:20
#22377 similar to this issue @aselle

**Comment by aselle** [comment] 2018-10-31 17:21
@shawn-tian could you specify what shapes you have been trying?

**Comment by shawn-tian** [comment] 2018-11-01 02:14
[Here](https://drive.google.com/drive/folders/1JaVBD6Z_9H4YedZ1Oe8DgGAYzM0MGrDT?usp=sharing) are the models with corresponding tflite converted ones. The models are converted with input_shapes=1,1280,960,3. 

If i set the new_input_sizes = {1,1280,960,3}, everything works well. If I set it to any other values, it would lead to aforementioned errors. 
```
int input = interpreter->inputs()[0];
    interpreter->ResizeInputTensor(input, new_input_sizes);
    if (interpreter->AllocateTensors() != kTfLiteOk) {
        NSLog(@"Failed to allocate tensors for model.");
        exit(-1);
    }
```
Please help to take a look and let me know if any other details are required.

**Comment by shahid14** [comment] 2018-12-05 17:02
https://github.com/tensorflow/tensorflow/issues/22377#issuecomment-444550814

**Comment by jdduke** [comment] 2019-01-09 18:44
Duplicate of #24311

**Closed** 2019-01-09 18:43 UTC
Labels: comp:lite

**Comment by jdduke** [comment] 2019-01-22 21:10
>  1. So it means during inference in TFLite, it cannot accept the value computed dynamically?

It's model-dependent. Many models will allow resizing without problem. Other models have various (coupled) inputs that would all need updating if you plan on resizing the shape of a given input.

>  2. If I change conv2d_transpose to resize_bilinear op, I also have to follow your above steps, feeding another input tensor to the graph during conversion? 

Again, it depends on the model and how the resize_bilinear op is used. If it (or any downstream ops) make any assumptions about the relative sizes between the resize_bilinear op, and the input that you're resizing, then it might require a dynamic input that is passed into resize_bilinear.

**Comment by shawn-tian** [comment] 2019-01-23 02:43
@jdduke Thank you for the detailed explanation. But I think most segmentation network with resize_bilinear op will have some assumptions about the relative sizes between op and input. Is there any plan to fix this in the future?
