### ISSUE TITLE
onnx->tensorflow->tflite

### ISSUE THREAD

**Issue by lzc16** [tensorflow/tensorflow#52041] opened 2021-09-17 06:37 UTC
_Originally posted by @abattery in https://github.com/tensorflow/tensorflow/issues/46006#issuecomment-918006725_

Hi @abattery !
I have try your method

Please try out TensorFlow 2.6 or tf-nightly version with converter.experimental_enable_resource_variables = True.
And it can convert tensorflow to tflite. But when it put some warning and log error when start network forward.

Here is the warning.

```
2021-09-17 10:46:25.251638: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1844] Graph contains the following resource op(s), that use(s) resource type. Currently, the resource type is not natively supported in TFLite. Please consider not using the resource type if there are issues with either TFLite converter or TFLite runtime:
Resource ops: AssignVariableOp, ReadVariableOp, VarHandleOp
Details:
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> () : {device = ""}
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<1x1xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<768x1024xf32>) -> () : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>) -> (tensor<1024xf32>) : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>) -> (tensor<?x?xf32>) : {device = ""}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<1024xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_bias_lstm_18"}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<?x?xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_kernel_lstm_18"}
2021-09-17 10:46:25.252215: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1855] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexAssignVariableOp, FlexReadVariableOp, FlexVarHandleOp
Details:
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> () : {device = ""}
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<1x1xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<768x1024xf32>) -> () : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>) -> (tensor<1024xf32>) : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>) -> (tensor<?x?xf32>) : {device = ""}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<1024xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_bias_lstm_18"}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<?x?xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_kernel_lstm_18"}
INFO: Created TensorFlow Lite delegate for select TF ops.
2021-09-17 16:00:43.773435: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-17 16:00:43.774454: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1829] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 37 nodes with 1 partitions.

INFO: TfLiteFlexDelegate delegate: 4 nodes delegated out of 4 nodes with 1 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 4 nodes delegated out of 29 nodes with 1 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 27 nodes with 1 partitions.
Traceback (most recent call last):
  File "onnx2tflite.py", line 59, in <module>
    interpreter.invoke()
  File "/root/anaconda3/envs/tfnight/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 858, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/reshape.cc:85 num_input_elements != num_output_elements (0 != 256)Node number 25 (RESHAPE) failed to prepare.
Node number 30 (WHILE) failed to invoke.
```

It there any suggestion to solve the problem?

Thanks.

**Comment by lzc16** [comment] 2021-09-17 06:45
I find the similar problem in this issue.
https://github.com/tensorflow/tensorflow/issues/51668

**Comment by karimnosseir** [comment] 2021-09-20 17:13
Hi @lzc16 

Looks like you're trying to run with Flex and you get this failure. Can you share the original saved model and the conversion command/script you used.
Or if you have a small reproduce sample please share it

Thanks

**Comment by karimnosseir** [comment] 2021-09-22 17:30
I looked at the issue, the failure is because FullyConnected op has invalid inputs. I tried running the saved model and i am getting failure also.
Can you please verify this model works in TF (didn't work for me using the example code you sent)

Thanks

**Comment by lzc16** [comment] 2021-09-23 04:22
Hi, @karimnosseir ,

I can run the model with onnx with the code below.
'''
import numpy as np
import onnxruntime as ort
model = onnx.load("cldnn.onnx")
ort_session = ort.InferenceSession('cldnn.onnx')
test_arr = np.array(np.random.randn(150,1,5,257), dtype=np.float32)
c11 = np.zeros([1, 1, 256], dtype=np.float32)
h11 = np.zeros([1, 1, 256], dtype=np.float32)
c22 = np.zeros([1, 1, 256], dtype=np.float32)
h22 = np.zeros([1, 1, 256], dtype=np.float32)

for idx in range(150):
    outputs, snr, h11, c11, h22, c22= ort_session.run(None, {'input': test_arr[idx:idx + 1], "h1_n":h11, "c1_n":c11, "h2_n":h22, "c2_n":c22})
    if idx==0:
        stream_onnx_outputs = outputs
        stream_onnx_snroutput = snr
    else:
        stream_onnx_outputs = np.vstack((stream_onnx_outputs, outputs))
        stream_onnx_snroutput = np.vstack((stream_onnx_snroutput, snr))
'''

It seems that when I converted to TF it brought some error in LSTM, which caused model don't work in TF.
Therefore, is there any suggestion to convert to TF correctly?

Thanks.
Best regards!

**Comment by karimnosseir** [comment] 2021-09-23 07:44
It looks like it is a problem with onnx-tf not with TF/TFLite. Might be good to reach to ONNX and file issue for them.
I am closing this issue.

Thanks

**Closed by karimnosseir** 2021-09-23 07:44 UTC
Labels: stat:awaiting response, type:support, comp:lite, 2.6.0
