### ISSUE TITLE
Tensorflow Unit Test: //tensorflow/python/eager:core_test fails

### ISSUE THREAD

**Issue by snjagadale** [tensorflow/tensorflow#15131] opened 2017-12-05 14:58 UTC
Tensorflow test failing on power hardware. 

W tensorflow/core/common_runtime/device_mgr.cc:97] Unknown device: GPU:5 all devices: /device:GPU:1, GPU:0, /device:GPU:0,

We are using 2 GPUs.

Any help appreciated

**Comment by reedwm** [comment] 2017-12-05 19:00
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by snjagadale** [comment] 2017-12-06 08:20
totalMemory: 15.89GiB freeMemory: 15.60GiB
2017-12-05 14:28:56.364727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2017-12-05 14:28:56.364760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1
2017-12-05 14:28:56.364766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y N
2017-12-05 14:28:56.364771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   N Y
2017-12-05 14:28:56.364786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name:  xyz, pci bus id: 0003:01:00.0, compute capability: 6.0)
2017-12-05 14:28:56.364793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: xyz, pci bus id: 0007:01:00.0, compute capability: 6.0)
.2017-12-05 14:28:56.552693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: xyz, pci bus id: 0003:01:00.0, compute capability: 6.0)
2017-12-05 14:28:56.552707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: xyz, pci bus id: 0007:01:00.0, compute capability: 6.0)
.2017-12-05 14:28:56.554959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: xyz, pci bus id: 0003:01:00.0, compute capability: 6.0)
2017-12-05 14:28:56.554968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: xyz, pci bus id: 0007:01:00.0, compute capability: 6.0)
F2017-12-05 14:28:56.555711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: xyz, pci bus id: 0003:01:00.0, compute capability: 6.0)
2017-12-05 14:28:56.555727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: xyz, pci bus id: 0007:01:00.0, compute capability: 6.0)
.2017-12-05 14:28:56.557869: W tensorflow/core/common_runtime/device_mgr.cc:97] Unknown device: GPU:5 all devices: /device:GPU:1, GPU:0, /device:GPU:0, /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:GPU:1, /device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/cpu:0, /device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, CPU:0, /job:localhost/replica:0/task:0/gpu:1, XLA_CPU:0, XLA_GPU:0, /device:XLA_GPU:0, GPU:1, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/gpu:0, /job:localhost/replica:0/task:0/xla_gpu:0, /job:localhost/replica:0/task:0/xla_cpu:0
......................................
======================================================================
FAIL: testContextConfig (__main__.TFETest)
----------------------------------------------------------------------
Traceback (most recent call last):

**Comment by gunan** [comment] 2017-12-06 19:15
@sandipmgiri @Nayana-ibm 
As we do not have power machines, it is difficult for us to help with these issues.
Should we just redirect these issues to you? Is there a separate IBM support flow these users should follow?

**Comment by sandipmgiri** [comment] 2017-12-11 08:04
The Power h/w access can be obtained easily via http://osuosl.org/services/powerdev/request_hosting/ 
This should make it easy for this reporter as well as any other interested developers to test and analyze ppc64le specific behaviour and issues. Those can then be reported on this forum.

**Comment by wdirons** [comment] 2018-07-19 20:56
@snjagadale , I just noticed this old issue for ppc64le. I believe this test is working now in Tensorflow 1.9. Is this issue ok to close ?

**Comment by gunan** [comment] 2018-07-19 21:18
I will close this for now. But please reopen if this is still  a problem.

**Closed** 2018-07-19 21:19 UTC
Labels: stat:community support
