### ISSUE TITLE
mkl-dnn sha256sum not match since two available link has different sha256sum

### ISSUE THREAD

**Issue by tz301** [tensorflow/tensorflow#38517] opened 2020-04-14 02:59 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Utuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 5.5.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Bazel build fails since mkl-dnn sha256sum doesn't match.

In tensorflow/workspace.bzl, there are two links:

urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz",
            "https://github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz",
        ],

However the sha256sum of the two links is not the same. The sha256sum of the first url is given in workspace. Due to some connect issue in China, we don't have access to the first url and can only use the second. Then sha256sum not match is met.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-04-14 04:28
@tz301 

Request you to provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by tz301** [comment] 2020-04-14 05:44
@ravikyram

Our project using tensorflow as dependency. When we use "bazel build //project_name:module", it fails on mkl-dnn sha256sum check. We have solved this problem by adding mkl-dnn lines the same as that in tensorflow/workspace.bzl but manually change the strip-prefix and sha256sum in our workspace. 

But I think it should be a bug, since the two urls for mkl-dnn have different sha256sum, it should be the same, right? Thanks.

**Comment by mihaimaruseac** [comment] 2020-04-16 16:55
It seems that mkl-dnn redid their release and have different hash now than the one we mirrored. Unfortunately, the mirror is read-only by design, so all you can do is locally change the hash

**Comment by vpirogov** [comment] 2020-04-16 17:07
This is unintended result of repository migration from intel/mkl-dn to oneapi-src/oneDNN. The source code blob includes metadata that include repo name.

**Comment by tz301** [comment] 2020-04-17 15:40
Understood. I have done it locally. 
But I just find that the master branch also has this issue, hope it can be fixed in master branch.

**Comment by mihaimaruseac** [comment] 2020-04-17 15:44
We cannot fix until there is a new release for mkl-dnn. The things stored at `mirror.tensorflow` are read-only, we cannot rewrite them. So we have to use that hash always.

When mkl-dnn makes a new release we can mirror from the new repo and then both links will have the same hash.

**Comment by vpirogov** [comment] 2020-04-17 16:52
[oneDNN v1.4](https://github.com/oneapi-src/oneDNN/releases/tag/v1.4) is released.

**Comment by mihaimaruseac** [comment] 2020-04-19 14:39
We need a PR to update to the new version and then we're can close this. Thank you

**Comment by agramesh1** [comment] 2020-04-20 22:28
> We need a PR to update to the new version and then we're can close this. Thank you

https://github.com/tensorflow/tensorflow/pull/38671   This will fix it for the build for mkl build (config=mkl).  Compiling TF without config=mkl will still use old 0.2x release (at least for now). 
@tz301 how are you building TF?

**Comment by tz301** [comment] 2020-04-21 06:23
@agramesh1  Our project is also a bazel project, and include tensorflow's github url in workspace. Due to this issue, I have to include mkl-dnn url locally (the same version as that in tensorflow's workspace) and copy tensorflow's mkl-dnn.BUILD file. 
It's worked now in our project, though not very elegant. If there are more elegant ways to fix this in old branch, please advise, thank you.

**Comment by vpirogov** [comment] 2020-04-22 23:53
@agramesh1,
 
If this would help we can do a patch release from the branch Tensorflow uses. Just let me know which release you need.

**Comment by tz301** [comment] 2020-04-23 02:47
@vpirogov @agramesh1 
We are using tf-1.15.0, "https://github.com/tensorflow/tensorflow/archive/v1.15.0.tar.gz" is included in our workspace now. Thanks!

**Comment by mihaimaruseac** [comment] 2020-04-23 04:43
There will be a 1.15.3 patch release soon. We can cherry-pick this on the branch and release with that included too.

**Comment by vpirogov** [comment] 2020-04-23 19:12
I posted [v0.21.5](https://github.com/oneapi-src/oneDNN/releases/tag/v0.21.5). Updating branches or configurations still relying on v0.x to this version will address the problem for these as well.

**Comment by yongtang** [comment] 2020-05-21 02:15
The issue should have been fixed in PR #39725 now.

**Comment by mihaimaruseac** [comment] 2020-05-21 17:37
Closing as fixed. Please reopen if that's not the case.

**Closed by mihaimaruseac** 2020-05-21 17:37 UTC
Labels: TF 2.1, comp:mkl, subtype: ubuntu/linux, type:build/install

**Comment by tz301** [comment] 2020-05-21 17:59
@mihaimaruseac Seems fixed in master branch. Is this branch also fix as you mentioned before?  "There will be a 1.15.3 patch release soon. We can cherry-pick this on the branch and release with that included too."

**Comment by mihaimaruseac** [comment] 2020-05-21 18:31
Oh, there was no PR to cherry-pick for 1.15.3 so it didn't get included.

We should cherry-pick the #39725 PR on the `r1.15` branch in the events of there being a 1.15.4 patch release though that would not be before TF 2.3 release at least.

**Comment by mihaimaruseac** [comment] 2020-06-20 21:57
I think this is fixed now, right?
