### ISSUE TITLE
The shape of Tensors is UNKNOWN after batching in graph mode. 

### ISSUE THREAD

**Issue by konopik** [tensorflow/tensorflow#36321] opened 2020-01-29 16:40 UTC
**System information**
- Have I written custom code: YES
- OS Platform and Distribution: Google Colab
- TensorFlow installed from: Preinstalled in Colab
- TensorFlow version: v2.1.0-0-ge5bf8de410 2.1.0
- Python version: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

**Describe the current behavior**

The shape of tensors is unknown when batching dataset in the graph mode. In the eager mode, the shape is know.

See the colab: https://colab.research.google.com/drive/1jfRaXtJXCgTSav3hvvE1RqUZ4FRyZ8fb

**Describe the expected behavior**

Shape should be known in both eager and graph mode.

**Code to reproduce the issue**

https://colab.research.google.com/drive/1jfRaXtJXCgTSav3hvvE1RqUZ4FRyZ8fb

**Comment by SummerRainET2008** [comment] 2020-01-30 04:24
This is a not a bug.
In the graph mode, you have to use tf.shape(tensor) to return a shape tensor which won't be known until it really runs.

**Comment by konopik** [comment] 2020-01-30 12:02
I include additional details to show the full extend of the problem. Tensorflow layers cannot operate on Tensors with unknown shapes. For example, if I call the LSTM layer on the top of the Tensor with an unknown shape I get the error below. I have extended the Colab to include this error. The example is shown in the Colab cell named _Problems in application of Tensors with unknow shape._

    <ipython-input-32-bd24e1627452>:12 iterate  *
        for inputs in ds:
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/autograph/operators/control_flow.py:662 scan_body
        body(iterate)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/layers/recurrent.py:644 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/base_layer.py:737 __call__
        self.name)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/input_spec.py:165 assert_input_compatibility
        layer_name + ' is incompatible with the layer: '

    ValueError: Input 0 of layer lstm_27 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

**Comment by jvishnuvardhan** [comment] 2020-02-03 22:59
@konopik You need to provide `output_shapes` parameter when you use `from_generator`.  TensorFlow has no idea what the shapes will be unless output_shapes is specified as the generator is never iterated over. Check [`from_generator`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator) documentation.

I changed one line in your code from 

`ds = tf.data.Dataset.from_generator(ds_gen, output_types=tf.float3`2)

to 

`ds = tf.data.Dataset.from_generator(ds_gen, output_types=tf.float32,output_shapes=(2,5))`

Then everything worked as expected. [Here is the gist](https://colab.research.google.com/gist/jvishnuvardhan/adf0d7c32c1823a1d4d5655813b3c0bf/dataset-batching.ipynb) for your reference. 

I am closing this issue as it was resolved. Feel free to reopen if the issue persists again. Thanks for the nice colab example.

**Closed by jvishnuvardhan** 2020-02-03 22:59 UTC
Labels: TF 2.1, comp:ops, type:bug

**Comment by ismailBima** [comment] 2022-10-13 19:37
bonjours tous 
comment corriger erreur
File c:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py:749, in OwnedIterator._next_internal(self)
    746 # TODO(b/77291417): This runs in sync mode as iterators use an error status
    747 # to communicate that there is no more data to iterate over.
    748 with context.execution_mode(context.SYNC):
...

KeyError: 'class'


	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
c
