### ISSUE TITLE
tf.saved_model.save() unable to save model with sparse input.

### ISSUE THREAD

**Issue by yzhuang** [tensorflow/tensorflow#33035] opened 2019-10-04 00:02 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu (Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  fails on 1.14.0, 1.15.0rc2, 2.0.0
- Python version: python 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
See this gist for reproduction 
https://colab.research.google.com/gist/yzhuang/3d4c511b247988fdafbd083785d624c1/model-saving-fails-with-sparse-input-tensor.ipynb

If a model has sparse input, they seem to be converted to dense tensors when `saved_model.save()` is called.  This causes model saving to fail.

**Describe the expected behavior**

If a model works during model.fit(), I expect the same model to also work for `saved_model.save()`.

**Code to reproduce the issue**
Colab gist:
https://colab.research.google.com/gist/yzhuang/3d4c511b247988fdafbd083785d624c1/model-saving-fails-with-sparse-input-tensor.ipynb

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment] 2019-10-04 03:24
@yzhuang ,
Thank you for reporting the issue, error also replicating for TF version-[2.0rc2](https://colab.sandbox.google.com/gist/oanush/d8dc1f89e88530a4ab3c83cdf81adc15/model-saving-fails-with-sparse-input-tensor.ipynb).Thanks!

**Comment by rmothukuru** [comment] 2019-10-04 11:06
@yzhuang,
The error is because of the below line of code.

`sparse_tensor = tf.sparse.SparseTensor(indices=sparse_tensor.indices, values=sparse_tensor.values, dense_shape=[2, 2])` .

It works fine if you replace that line with below line:

`sparse_tensor = tf.sparse.SparseTensor(indices=tf.constant([[0,0],[1,1]], dtype=tf.int64),values=tf.constant([1.0, 1.0], dtype=tf.float32),dense_shape=[2, 2])`.

**Comment by yzhuang** [comment] 2019-10-04 18:14
Hi @rmothukuru 

I am reproducing this bug specifically: "During tf.saved_model.save(), while calling a model's call() method, all SparseTensor inputs are converted to dense tensors."  That's why the above code fails. 

While the suggested one line change fixes the crash, it no longer uses the input to the call() method, and hence no longer reproduce this bug.  Does that make sense?

**Comment by rmothukuru** [comment] 2019-10-09 06:53
Could reproduce this bug with TF Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/807a0c0d20281b818a2abeafeeae7a6b/model-saving-fails-with-sparse-input-tensor.ipynb).

**Comment by vdhelm** [comment] 2020-02-04 22:55
Is there a workaround to still save a trained model? My project absolutely needs sparse input tensors, and if I am not able to save them, that will be a major blocker. 
Thanks,

**Comment by amin-unity** [comment] 2020-02-13 11:35
Hi guys, is there any update on this?

**Comment by ymodak** [comment] 2020-03-02 21:54
This is fixed with latest tf-nightly version '2.2.0-dev20200302'. Thanks!

**Closed by ymodak** 2020-03-02 21:54 UTC
Labels: TF 2.0, comp:keras, stat:awaiting tensorflower, type:bug
