### ISSUE TITLE
In batching.map_and_batch, is map_fn for each sample build by random order?

### ISSUE THREAD

**Issue by Jar7** [tensorflow/tensorflow#32872] opened 2019-09-27 10:21 UTC
Hi, 
I meet the difficulty to reproduce the result with fixed random_seed.
tf.set_random_seed(0) is set before building a graph, for each run (rerun the script without modifying the codes), samples (after shuffle) are feed into network by the same order. But the output of `tf.image.random_flip_left_right` in `map_fn` in `batching.map_and_batch` still produce random flip image.  **In short, same input file, random flip result.**

If I set `seed=0` in `tf.image.random_flip_left_right`, the outputs are still random. So I think the order in which the graph is build is the key. The order may not be controlled by that global random seed. 
Any suggestion or reference for this problem, please? I use tf1.8 with horovod. 
Thank you.

**Comment by ravikyram** [comment] 2019-09-30 09:46
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-10-11 11:12
@Jar7 
Any update please?.Is it possible for you to try latest TF versions and let us know whether the issue persists? There were lots of performance improvements in the latest versions. Thanks!

**Comment by ravikyram** [comment] 2019-10-18 11:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-10-18 11:16 UTC
Labels: comp:ops, stat:awaiting response, type:support
