### ISSUE TITLE
[BUG] control_dependencies + sess.run(tf.global_variables_initializer())

### ISSUE THREAD

**Issue by morgangiraud** [tensorflow/tensorflow#10486] opened 2017-06-07 09:19 UTC
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04 and mac osx
- **TensorFlow installed from (source or binary)**: pip install tensorflow
- **TensorFlow version (use command below)**: v1.1.0-rc0-61-g1ec6ed5 and 1.1.0

Hi TF team, I've stumbled upon a strange behaviour that I believe is a bug:

If I try to run the code below i end up with : `FailedPreconditionError (see above for traceback): Attempting to use uninitialized value timestep
	 [[Node: AssignAdd = AssignAdd[T=DT_INT32, _class=["loc:@timestep"], use_locking=false, _device="/job:localhost/replica:0/task:0/cpu:0"](timestep, AssignAdd/value)]]`

If I remove the `tf.zeros_like(Qs_t)` statement (as in the commented line), the problem disappears.

```python
import tensorflow as tf

with tf.Graph().as_default():
    Qs_t = tf.ones([3, 2], dtype=tf.float32)
    timestep = tf.Variable(0, dtype=tf.int32, trainable=False, name="timestep")
    inc_t = tf.assign_add(timestep, 1)
    with tf.control_dependencies([inc_t]):
        Ns_t = tf.Variable(tf.zeros_like(Qs_t), dtype=tf.float32, name="N", trainable=False)
        # Ns_t = tf.Variable(0., dtype=tf.float32, name="N", trainable=False)

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
```

**Comment by michaelisard** [comment] 2017-06-08 15:51
I think the problem is that control dependencies and variable initializers are confusing. When you run the variable initializers, you only tell TensorFlow to run those initialization ops (i.e. compute zeros_like(Qs_t) and assign it to Ns_t), and it doesn't end up executing the precursors to the control dependency.

The more common use case would be something like:

```
with tf.Graph().as_default():
    Qs_t = tf.ones([3, 2], dtype=tf.float32)
    timestep = tf.Variable(0, dtype=tf.int32, trainable=False, name="timestep")
    inc_t = tf.assign_add(timestep, 1)
    with tf.control_dependencies([inc_t]):
        Ns_t = tf.Variable(0., dtype=tf.float32, name="N", trainable=False)
        tf.Assign(Ns_t, inc_t)
```
where the control dependency was intended to apply to the Assign Op. In that case you probably want to be able to call the variable initializer outside the control dependency along with any other variable initializer. You should maybe think of variable initializers more like initializers for static variables in C++: the initializers are run once "before any other code".

A judgment call was made in the TF design that more often than not, when you define the variable inside the control dependency you don't want to guard the initializer. In your case, you should just initialize based on the static shape of Qs_t, not zeros_like.

I'm closing this for now, but if you have any followup questions, please post them on stackoverflow since github issues are only for TF bugs and feature requests. Thanks!

**Closed by michaelisard** 2017-06-08 15:51 UTC
