### ISSUE TITLE
Error building PIP package on Windows

### ISSUE THREAD

**Issue by elcombato** [tensorflow/tensorflow#4799] opened 2016-10-06 11:27 UTC
Hi,

I followed the new instructions for the [CMake build on Windows](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md).
The C++ example program `tf_tutorials_example_trainer.exe` build and run successfully.
But the build of the PIP package exited with the following error:
```
ld_pip_package.vcxproj" (Standardziel) (1) ->
"C:\Users\jonas\projects\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensor flow.vcxproj" (Standardziel) (3) ->
(ClCompile Ziel) ->
C:\Users\jonas\projects\tensorflow\tensorflow\python\lib\core\py_func.cc(165): 
error C2466: cannot allocate an array of constant size 0 [C:\Users\jonas\projec ts\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj]

    2398 Warnung(en)
    1 Fehler
```

**Comment by mrry** [comment] 2016-10-06 14:20
Thanks for reporting this. As you've already noticed, this is a duplicate of #4798, so I'm going to close this as a duplicate and report there when it's fixed.

**Closed by mrry** 2016-10-06 14:20 UTC
