### ISSUE TITLE
RuntimeError: Mixing different tf.distribute.Strategy objects: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7f50aed5d160> is not <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7f5230440748>

### ISSUE THREAD

**Issue by Hukongtao** [tensorflow/tensorflow#35601] opened 2020-01-06 06:32 UTC
`def train_net():
        mirror_strategy = tf.distribute.MirroredStrategy(
                     cross_device_ops=config.cross_device_ops
          )
         with mirror_strategy.scope():

for i in range(1, config.num_step+1):
            train_net(config, stage_cfg, args.fast_mode, merge_num=i)```

**Comment by oanush** [comment] 2020-01-06 09:30
@Hukongtao ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here also error stack trace and TF version being used.Thanks!

**Comment by oanush** [comment] 2020-01-20 09:35
@Hukongtao ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2020-01-27 07:04
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2020-01-27 07:04 UTC
Labels: comp:dist-strat, stat:awaiting response, type:support
