### ISSUE TITLE
Dataset.from_generator breaks on last element

### ISSUE THREAD

**Issue by optiluca** [tensorflow/tensorflow#43016] opened 2020-09-07 12:10 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from: Docker Image
- TensorFlow version: v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.9

Running the attached gist throws InvalidArgumentError: Argument 0 is out of range. [[{{node args_0}}]].

**Describe the expected behavior**
It should run through the dataset, and once completed exit gracefully.

**Standalone code to reproduce the issue**
https://gist.github.com/optiluca/f97a34237837d19f9643b54ef17f8a76

**Other info / logs**
This issue goes away if I do any one of the following:
- If I don't batch the data ( commenting line 41)
- If I don't run _transform_after_windowing (commenting line 38)

I noticed this issue when running a similar pipeline and feeding it to a tf.keras model.predict().  It broke with the aforementioned error.

**Comment by ravikyram** [comment] 2020-09-08 06:19
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200907`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d83f0868204690814a2cc0890364b803/untitled320.ipynb). Thanks!

**Comment by Leslie-Fang** [comment] 2020-09-09 12:21
Is 1 Batch of data(8*5) if more than the items number(17)?

**Comment by optiluca** [comment] 2020-09-09 14:19
I don't think that's how the windowing works - each window steps forward only by one sample and not by an entire window width.  So my batch doesn't contain 8*5 different samples.  In any case, the issue still occurs if you replace the 17 with something large, I just set it small to make it break faster since it only breaks at the last batch!

**Comment by sachinprasadhs** [comment] 2021-05-27 15:21
The issue is fixed in Tensorflow version 2.5, your code no longer breaks, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7c30a74189bf5b5f40b9c5e51357d88f/43016.ipynb). 
Closing this issue since it is resolved, feel free to reopen. Thanks!

**Closed by sachinprasadhs** 2021-05-27 15:21 UTC
Labels: TF 2.3, comp:data, stat:awaiting tensorflower, type:bug
