### ISSUE TITLE
Tensorflow serving with transfer learning retrained inception model

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#1796] opened 2016-04-06 18:51 UTC
Hi

Trying to use a retrained inception model (as in the transfer learning tutorial) with Tensorflow serving as described by the example, [here](https://tensorflow.github.io/serving/serving_basic). However, I am unclear how to set up the exporter.

The exporter flow as shown in the tutorial looks as such:

`
 export_path = sys.argv[-1] print 'Exporting trained model to', export_path saver = tf.train.Saver(sharded=True) model_exporter = exporter.Exporter(saver) signature = exporter.classification_signature(input_tensor=x, scores_tensor=y) model_exporter.init(sess.graph.as_graph_def(), default_graph_signature=signature) model_exporter.export(export_path, tf.constant(FLAGS.export_version), sess) 
`

Since there is no "input_tensor" and "scores_tensor" as described by this tutorial within the Inception transfer learning, I am unsure of what tensors to use to get the signature. The bottleneck tensor? The ground_truth tensor?

I'd love an explanation of how to set up this retrained model with Tensorflow Serving as shown in this example!

Thanks

Oren

**Comment by fangweili** [comment] 2016-04-08 17:58
retrain.py is to take a trained inception model, reuse all layers up to bottleneck layer, and train a new top layer for new image classifications. Therefore, from an inference perspective, the input is the same as the inception model being used, and the output is the output of the new top layer.

input_tensor=jpeg_data_tensor
scores_tensor=final_tensor

**Comment by girving** [comment] 2016-06-07 00:37
Closing since this seems to be a (hopefully answered?) question rather than an issue that needs fixing.  Please ask to reopen if you think a doc-fix is warranted, or if there's a real bug here.

**Closed by girving** 2016-06-07 00:37 UTC

**Comment by evolu8** [comment] 2016-07-21 05:29
I'm struggling to server a 'fine tuned' retrained inceptions model. After retraining on just two classes I get an error when trying to export:

`  File "/home/ubuntu/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/clie
nt/session.py", line 743, in _do_call                                                                                            
    raise type(e)(node_def, op, message)                                                                                         
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1001] rhs s
hape= [3]                                                                                                                        
         [[Node: save/Assign_30 = Assign[T=DT_FLOAT, _class=["loc:@logits/logits/biases"], use_locking=true, validate_shape=true,
 _device="/job:localhost/replica:0/task:0/cpu:0"](logits/logits/biases, save/restore_slice_30)]]                                 
Caused by op u'save/Assign_30', defined at: `

**Comment by albertsylvester** [comment] 2017-09-24 16:15
```
classify_inputs_tensor_info = tf.saved_model.utils.build_tensor_info(
        jpeg_data_tensor)
classes_output_tensor_info = tf.saved_model.utils.build_tensor_info(
        **???**)
scores_output_tensor_info = tf.saved_model.utils.build_tensor_info(final_tensor)
```

What should I fill in **classes_output_tensor_info**? Thank you @fangweili
