### ISSUE TITLE
Successfully convert model through full-integer, but leave nodes with int8 instead of uint8

### ISSUE THREAD

**Issue by DLMasterCat** [tensorflow/tensorflow#36610] opened 2020-02-10 04:20 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-55-generic x86_64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: would run on Raspberry Pi4 +edge TPU or Dev-board
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.15.0-0-g590d6eef7e 1.15.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): GCC 7.3.0
- CUDA/cuDNN version: Cuda compilation tools, release 10.1, V10.1.243
- GPU model and memory: 2080Ti
**(but TensorFlow was not compiled with CUDA support)**
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I convert my model from pytorch->onnx->tensorflow->tensorflow lite. And I would run on Edge TPU, thus my tensorflow version should be 1.15.0 as suggestion. However, due to lack of "split", and incorrect of "min and max". I rebuild from source based on the two links below.

[https://github.com/tensorflow/tensorflow/commit/3c2be61e68acea533030b8f70fa0db3339b19f93](url)
[https://github.com/tensorflow/tensorflow/pull/32582/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.h&file-filters%5B%5D=No+extension#diff-71a783b5a7624430897d44e42f816444](url)

I use full-integer quantization, and all the conversion is successful. The tflite file works fine on interpreter. Input and Output datatype are tf.uint8 correctly. But almost every node in the model except input and output is tf.int8 (quantization).

**Describe the expected behavior**
I think these nodes should be tf.uint8. And I wonder that whether I could just load the tflite file via "JSON" format and change the model["subgraphs"][0]["tensors"]["type"] "INT8" to "UINT8".

This idea based on the link below.
[https://towardsdatascience.com/hacking-google-coral-edge-tpu-motion-blur-and-lanczos-resize-9b60ebfaa552](url)
Actually, it failed. I want to know the reasons.

**Code to reproduce the issue**
```

import tensorflow as tf
import torch
from PIL import Image
import numpy as np
import pathlib

#tf.compat.v1.enable_eager_execution()
#tf.logging.set_verbosity(tf.logging.DEBUG)

#import matplotlib.pyplot as plt
print(tf.__version__)
print(torch.__version__)


val = "./ILSVRC2012_img_val/"
val=pathlib.Path(val)
item=np.array([i.name for i in val.glob("*")])

image_generator = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255,data_format="channels_first")

train_data_gen = image_generator.flow_from_directory(directory=str(val),
                                                     batch_size=100,
                                                     shuffle=True,
                                                     target_size=(320,320),
                                                     classes = list(item))

image_batch, label_batch = next(train_data_gen)
image_batch=np.expand_dims(image_batch,1)

print(((image_batch).dtype))

image_batch, label_batch = next(train_data_gen)
mean=([0.485, 0.456, 0.406])
std=([0.229, 0.224, 0.225])
for i in range(3):
    image_batch[:,i,:,:]=(image_batch[:,i,:,:]-mean[i])/(std[i])
print(image_batch.shape)
image_batch=(np.expand_dims(image_batch,1))


def representative_data_gen():
    for i in range(100):
        yield [image_batch[i]]

graph_def_file = "test_320.pb"
inputs=['input.1']
outputs=['655']
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file,inputs, outputs)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
#converter.inference_type=tf.uint8
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
#converter.experimental_new_quantizer= True
#converter.experimental_enable_mlir_converter = True
tflite_model_op= converter.convert()
open("cvted_model_320_quant_op.tflite", "wb").write(tflite_model_op)


```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I tried compile with Edge TPU Compiler, and find out "unsupported data type". Then I use netron find that most of them are tf.int8.

Here is the Edge TPU compiler log, result of Netron and my model. 

```
Edge TPU Compiler version 2.0.291256449

Model compiled successfully in 45 ms.

Input model: /home/xxxxx01/39dstest/cvted_model_320_quant_op.tflite
Input size: 6.28MiB
Output model: cvted_model_320_quant_op_edgetpu.tflite
Output size: 6.03MiB
On-chip memory available for caching model parameters: 0.00B
On-chip memory used for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 7950
Operation log: cvted_model_320_quant_op_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 7950

Operator                       Count      Status

SPLIT                          36         Operation is working on an unsupported data type
QUANTIZE                       3729       Operation is otherwise supported, but not mapped due to some unspecified limitation
MUL                            74         Operation is working on an unsupported data type
MAXIMUM                        38         Operation is working on an unsupported data type
MINIMUM                        38         Operation is working on an unsupported data type
ADD                            74         Operation is working on an unsupported data type
CONCATENATION                  56         Operation is working on an unsupported data type
PAD                            37         Operation is working on an unsupported data type
CONV_2D                        38         Operation is working on an unsupported data type
DEPTHWISE_CONV_2D              3680       Operation is working on an unsupported data type
TRANSPOSE                      148        Operation is working on an unsupported data type
MEAN                           1          Operation is working on an unsupported data type
FULLY_CONNECTED                1          Operation is working on an unsupported data type

```
**Result of Netron**
![Results of Netron](https://user-images.githubusercontent.com/60849247/74120385-1be52580-4bfe-11ea-8909-7d636b97be14.PNG)

**My model**
[test_320.zip](https://github.com/tensorflow/tensorflow/files/4178930/test_320.zip)

New to Github, Thx ><

**Comment by liufengdb** [comment] 2020-02-19 22:51
So looks like the TFLite converter does the right job and you are asking for a good approach to post-processing all the nodes to uint8 for edge TPU execution? As far as I know, the current edge TPU runtime will automatically convert int8 activation to uint8, so you don't need to handle them by yourself.

**Comment by liufengdb** [comment] 2020-02-19 23:08
Can you set both the `converter.inference_input_type = tf.int8`, `converter.inference_output_type = tf.int8` and `converter.inference_type=tf.int8` and then give it another try? I noticed the extra Quatize op is converting uint8 to int8. So if you set all all the inference types to int8, the nodes of the model will be in int8 and the edge tpu converter should be able to do the right job.

**Comment by nicci1771** [comment] 2020-02-20 01:21
Hello I found the bug is hard to reproduce since it is required to rebuild tensorflow.
Can you attach the post-training quantized tflite model if possible? Thanks!

**Comment by DLMasterCat** [comment] 2020-02-21 09:22
@liufengdb @nicci1771 Thanks for your reply.
Sure, here are all the tflite model with different inference input/output type.
[https://drive.google.com/file/d/1cQ2vZ1pwyGh9__huOIXZFrxF_-_QgdMV/view](url)

Yes, you got it. All the inference on cpu was fine. However, in edge TPU failed.
"the current edge TPU runtime will automatically convert int8 activation to uint8"
Did you mean Edge TPU runtime 13? I think edgetpu compiler maybe is another problem. 
From their official website
"* **These models do not compile properly with Edge TPU Compiler version 2.0.2xx (from our September update). You can instead use the previous compiler version and run them with the latest runtime**."
 Unfortunately, I don't know where to get older version.

And, I have tried your suggestions. I set the input/output type to tf.int8, but I cannot set "converter.inference_type=tf.int8". It said that it should be float32.
Does this error relate to my representative dataset?

Thanks a lot.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:12
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:52 UTC
Labels: TF 1.15, comp:lite, type:bug
