### ISSUE TITLE
Not able to convert Keras model to tflite - TF 2.0 alpha

### ISSUE THREAD

**Issue by SanthoshRajendiran** [tensorflow/tensorflow#26672] opened 2019-03-13 14:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not yet to that phase
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7.12
- Bazel version (if compiling from source): 0.23.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA/cuDNN version: CPU
- GPU model and memory: CPU

**Current Behavior**
On conversion to tflite from keras model, fused batch norm creates a resource node issue (before fine tuning: dog_cat_classification_initial), and conv2d creates a resource node issue(after fine tuning: dog_cat_classification_final).
On conversion to tflite from a keras model using TF2.0, extra resource nodes are getting generated for each and every op that is available. So, upon conversion to tflite, all the resource nodes sum up to form the input, which does not allow the tflite to work as expected. 

**expected behavior**
Batch normalization should be supported by TFLITE. 
TFLite produced as an output of the tflite conversion process, should produce no resource nodes as it was the case in TF1.12

**Code to reproduce the issue**
This is a code to convert the mobilenet based classification model into tflite. This is developed using TF2.0 following the official dogs and cats classification published in the tensorflow page.
I have attached with this issue, the h5 file and hdf5 file extracted from the same model. I hope we can try invoking the same model and try creating the tflite file. The same code creates different issues with the same model architecture in two different situations(initial and fine tuned).

`import tensorflow as tf`
`model = tf.keras.models.load_model('dog_cat_classification_initial.hdf5')`
`@tf.function`
`def to_save(x):      return model(x)`

`from tensorflow.lite.python import lite`
`from tensorflow.lite.python.interpreter import Interpreter`
`from tensorflow.python import keras`
`from tensorflow.python.eager import def_function`
`from tensorflow.python.framework import constant_op`
`from tensorflow.python.framework import dtypes`
`from tensorflow.python.framework import tensor_spec`
`from tensorflow.python.framework import test_util`
`from tensorflow.python.ops import variables`
`from tensorflow.python.platform import test`
`from tensorflow.python.saved_model.load import load`
`from tensorflow.python.saved_model.save import save`
`from tensorflow.python.training.tracking import tracking`
`tf.keras.backend.set_learning_phase(False)`
`concrete_func = to_save.get_concrete_function(tensor_spec.TensorSpec([None, 160, 160, 3], dtypes.float32))`
`converter = lite.TFLiteConverterV2.from_concrete_function(concrete_func)`
`tflite_model = converter.convert()`
`open("new_classificaton.tflite","wb").write(tflite_model)`

Model file:

[tf2_tflite_issues.zip](https://github.com/tensorflow/tensorflow/files/2961884/tf2_tflite_issues.zip)

**Other info / logs**

**dog_cat_classification_initial.hdf5**

2019-03-13 19:52:41.281172: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594290000 Hz
2019-03-13 19:52:41.281379: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x5aee1c0 executing computations on platform Host. Devices:
2019-03-13 19:52:41.281401: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
WARNING: Logging before flag parsing goes to stderr.
W0313 19:53:20.606553 140373983291136 hdf5_format.py:261] Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
2019-03-13 19:53:21.310751: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-03-13 19:53:21.310873: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-03-13 19:53:21.344653: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:666] Optimization results for grappler item: graph_to_optimize
2019-03-13 19:53:21.344712: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   function_optimizer: Graph size after: 775 nodes (0), 960 edges (0), time = 1.54ms.
2019-03-13 19:53:21.344726: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   function_optimizer: Graph size after: 775 nodes (0), 960 edges (0), time = 1.95ms.
Traceback (most recent call last):
  File "conversion.py", line 26, in <module>
    tflite_model = converter.convert()
  File "/home/santhosh/venv_tf2/local/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 246, in convert
    self._func)
  File "/home/santhosh/venv_tf2/local/lib/python2.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 173, in convert_variables_to_constants_v2
    "data": tensor_data[input_name],
KeyError: u'sequential/mobilenetv2_1.00_160/bn_Conv1/FusedBatchNorm/ReadVariableOp/resource'

**dog_cat_classification_final.hdf5**
2019-03-13 19:52:08.602599: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594290000 Hz
2019-03-13 19:52:08.602794: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x545d360 executing computations on platform Host. Devices:
2019-03-13 19:52:08.602817: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-13 19:52:25.827825: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-03-13 19:52:25.827926: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-03-13 19:52:25.844869: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:666] Optimization results for grappler item: graph_to_optimize
2019-03-13 19:52:25.844920: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   function_optimizer: Graph size after: 775 nodes (0), 960 edges (0), time = 0.703ms.
2019-03-13 19:52:25.844930: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   function_optimizer: Graph size after: 775 nodes (0), 960 edges (0), time = 1.121ms.
Traceback (most recent call last):
  File "conversion.py", line 26, in <module>
    tflite_model = converter.convert()
  File "/home/santhosh/venv_tf2/local/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 246, in convert
    self._func)
  File "/home/santhosh/venv_tf2/local/lib/python2.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 173, in convert_variables_to_constants_v2
    "data": tensor_data[input_name],
KeyError: u'sequential/mobilenetv2_1.00_160/Conv1/Conv2D/ReadVariableOp/resource'

**Comment by gargn** [comment] 2019-03-13 17:15
This error is coming from a known issue with `convert_variables_to_constants_v2` that should be fixed in the coming weeks. The work around (in the interim while the issue is being fixed) is to save the model instead of using `@tf.function` to generate the concrete function. Here is an example of how that might look:

```
import tensorflow as tf

model = tf.keras.models.load_model('dog_cat_classification_initial.hdf5')

# Save the model.
export_dir = "/tmp/test_saved_model"
tf.saved_model.save(model, export_dir)

# Load model and get the concrete function.
model = tf.saved_model.load(export_dir)
concrete_func = model.signatures[
  tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

# Convert the model.
converter = tf.lite.TFLiteConverter.from_concrete_function(concrete_func)
tflite_model = converter.convert()
open("new_classificaton.tflite","wb").write(tflite_model)
```

However, saving and loading seems to result in the following error (from the `tf.saved_model.load(export_dir)` call):
```
AttributeError: '_UserObject' object has no attribute '_create_or_restore_slot_variable'
```

@allenlavoie Any thoughts?

**Comment by allenlavoie** [comment] 2019-03-13 17:25
Yeah we need to support Optimizers in SavedModels. Right now the imported model isn't checkpoint compatible with the exported model. There's a bug for it internally. The SavedModel will work fine for things other than `tf.saved_model.load` (saved_model_cli/tflite/etc.) in the meantime.

**Comment by allenlavoie** [comment] 2019-03-13 18:04
If you need a workaround for the optimizer issue, you should be able to `del model.optimizer` before saving. But it sounds like that's not the main issue.

**Comment by allenlavoie** [comment] 2019-03-15 17:16
https://github.com/tensorflow/tensorflow/commit/147e6777068ea569cbecbd270b8b07c648bae09b should fix the optimizer exception.

**Comment by gargn** [comment] 2019-03-27 16:33
The work around in https://github.com/tensorflow/tensorflow/issues/26672#issuecomment-472519970 works in the latest nightly.

**Closed by gargn** 2019-03-27 16:33 UTC
Labels: 2.0.0-alpha0, comp:lite

**Comment by anhtu812** [comment] 2019-04-08 03:25
tf-nightly-2.0-preview fixed KeyError: '../FusedBatchNorm/ReadVariableOp/resource'. But it don't fold  BatchNorm therefore it generate error tflife not support BatchNormalization.
"Here is a list of operators for which you will need custom implementations: BatchNormalization."

**Comment by gargn** [comment] 2019-04-11 00:28
Adding here for documentation for future users. This functionality has been changed in https://github.com/tensorflow/tensorflow/commit/312222d2a0657d4e0086ec0add4331063d0b2264. `from_concrete_function` is now `from_concrete_functions`. Additionally, `from_keras_model` and `from_saved_model` have been added.

@anhtu812 Please file a separate bug with additional information including how to reproduce the error.
