### ISSUE TITLE
Cannot load pretrained models in Android via jcenter-provided library

### ISSUE THREAD

**Issue by xumengwei** [tensorflow/tensorflow#15610] opened 2017-12-24 08:35 UTC
It's a great step to support importing Android lib via jcenter. However, I'm having trouble in loading pretrained models into `TensorFlowInferenceInterface`, which says `NodeDef mentions attr 'dilations' not in Op...`. I think it's a compatibility issue, meaning that the model graph is not consistent with the graph interpreter. The models directly downloaded from `slim` and frozen by myself. Anyone can help me?

**Comment by asimshankar** [comment] 2017-12-30 10:06
Yup, this seems like a version mismatch. Closing this as a duplicate of #15698 so that the discussion remains on a single thread. Thanks!

**Closed by asimshankar** 2017-12-30 10:06 UTC
