### ISSUE TITLE
tf.io.matching_files hangs given a certain pattern

### ISSUE THREAD

**Issue by mjkim720** [tensorflow/tensorflow#40553] opened 2020-06-17 20:31 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): No 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tf.io.matching_files` hangs and does not terminate when passing `/*` or `/?`  in the beginning of `pattern` argument.

**Describe the expected behavior**
As far as `/*` or `/?` is not placed in the beginning, the function terminates with a proper error handling. I would expect a similar behavior for my input below. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

tf.io.matching_files('/*name',name=None)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-06-18 06:33
I have tried in colab with TF version 2.2, nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1145726bc641ac37372231cf6d7866d3/untitled42.ipynb).Thanks!

**Comment by zhuzilin** [comment] 2020-06-27 05:58
The reason for this problem is the algorithm in `tf.io.matching_files` will search for all files and nested directories under `/` when `/*name` is used. I'd love to help to fix this problem.

**Comment by mihaimaruseac** [comment] 2020-12-02 17:18
This is fixed in latest nightly (probably even from before)

```
...$ python -c "import tensorflow as tf; print(tf.io.gfile.glob('/*p'))"
['/tmp']
```

**Closed by mihaimaruseac** 2020-12-02 17:18 UTC
Labels: TF 2.2, comp:ops, type:bug
