### ISSUE TITLE
Build smaller AAR files locally (tensorflow-lite.aar, tensorflow-lite-select-tf-ops.aar) fail.

### ISSUE THREAD

**Issue by farmaker47** [tensorflow/tensorflow#57840] opened 2022-09-26 05:51 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.2

### Custom Code

Yes

### Bazel version

5.3.1

### Current Behaviour?

```shell
Trying to follow the tutorial at https://www.tensorflow.org/lite/android/lite_build#build_and_install to build smaller .aar files using a .tflite model with TensorFlow ops the procedure fails with unknowk error. This happens when it tries to load the native TensorFlow runtime.
```

### Standalone code to reproduce the issue

```shell
Giving you the link to download the colab notebook and see all the output logs.
https://colab.research.google.com/drive/1D_mdWel9Pk4zVbW1Lxk9yT8P5MZdjeGg?usp=sharing
```

### Relevant log output

```shell
...........................
    Compiling tensorflow/core/common_runtime/session_state.cc; 7s local
[15,079 / 16,006] 24 actions running
    //tensorflow/core:portable_tensorflow_lib_lite; 24s local
    Compiling tensorflow/core/common_runtime/partitioning_utils.cc; 12s local
    Compiling tensorflow/core/common_runtime/ring_gatherer.cc; 10s local
    Compiling tensorflow/core/common_runtime/ring_reducer.cc; 10s local
    Compiling tensorflow/core/common_runtime/collective_util.cc; 9s local
    //tensorflow/core:portable_tensorflow_lib_lite; 8s local
    Compiling tensorflow/core/common_runtime/session_state.cc; 7s local
ERROR: /tensorflow_src/tensorflow/BUILD:1419:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
2022-09-26 04:46:44.851959: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow10checkpoint26OpenTableTensorSliceReaderERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPPNS0_17TensorSliceReader5TableE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 78, in <module>
    f'{traceback.format_exc()}'
ImportError: Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow10checkpoint26OpenTableTensorSliceReaderERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPPNS0_17TensorSliceReader5TableE


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
[15,081 / 16,006] 23 actions running
    //tensorflow/core:portable_tensorflow_lib_lite; 24s local
    Compiling tensorflow/core/common_runtime/ring_gatherer.cc; 10s local
    Compiling tensorflow/core/common_runtime/ring_reducer.cc; 10s local
    Compiling tensorflow/core/common_runtime/collective_util.cc; 9s local
    //tensorflow/core:portable_tensorflow_lib_lite; 8s local
    Compiling tensorflow/core/common_runtime/session_state.cc; 7s local
    Compiling tensorflow/core/common_runtime/lower_case_op.cc; 7s local
Target //tmp:tensorflow-lite-select-tf-ops failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tensorflow_src/tensorflow/python/tools/BUILD:281:10 Middleman _middlemen/tensorflow_Spython_Stools_Sprint_Uselective_Uregistration_Uheader-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
INFO: Elapsed time: 4769.260s, Critical Path: 564.99s
INFO: 13392 processes: 135 internal, 13257 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by farmaker47** [comment] 2022-09-26 05:54
Build of tensorflow-lite.aar is successful but fails when it tries to build tensorflow-lite-select-tf-ops.aar

**Comment by mohantym** [comment] 2022-09-26 08:43
Hi @farmaker47 !

Just making Sure things while I am replicating this issue. 

For getting a Select ops aar file , TFLite model should involve select ops syntax. [Ref](https://www.tensorflow.org/lite/guide/ops_select#:~:text=This%20will%20generate%20the%20AAR%20file%20bazel%2Dbin/tmp/tensorflow%2Dlite.aar%20for%20TensorFlow%20Lite%20built%2Din%20and%20custom%20ops%3B%20and%20generate%20the%20AAR%20file%20bazel%2Dbin/tmp/tensorflow%2Dlite%2Dselect%2Dtf%2Dops.aar%20for%20TensorFlow%20ops)
Could you use two TF lite model in Bash script (one with [Select ops ](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model)syntax and one with default optimization) . 

I also suspect you are using Python 3.6 with TF 2.8 . Could you confirm whether you are using Python 3.7/3.10.
Please check in Bazelbin folder once you completed running the script.  

Thank you!

**Comment by farmaker47** [comment] 2022-09-26 08:52
Hi @mohantym 
Yes, the model I am using has select tf ops specifically FlexDecodewav. If you see at the logcat of the first cell Python 3.7 is used.
Do you want any other detail?
Thanks

**Comment by mohantym** [comment] 2022-09-26 09:51
Hi @farmaker47 !

It is not running the bash script properly and  looks like environment issue from below line.

`from tensorflow.python._pywrap_tensorflow_internal import *

`

Quick suggestions:
1. clean the previous build - bazel clean --expunge
2. For 2.8 , You have to checkout with r2.8 branch and build with Bazel 4.2.1 (tested config) . 

```
%cd tensorflow_src
!cd tensorflow
!git checkout r2.8
```

Could you confirm the machine type too (windows/linux/macos)

Thank you!

**Comment by farmaker47** [comment] 2022-09-26 10:32
Hi @mohantym 

The environment is Linux (Colab). I am connecting the colab with a Google Cloud VM instance since this procedure needs much time and high CPU, RAM (Instance is 24 CPUs and 140GB of Ram). I always build with new VM instance so no need of bazel clean up.
I will try r2.8 branch and 4.2.1 Bazel and get back to you later.

Thanks

**Comment by farmaker47** [comment] 2022-09-26 17:03
Hi @mohantym 

Yes, the code snippet
```
%cd tensorflow_src
%cd tensorflow
!git checkout r2.8
```
did the trick! Build completed successfully! By checking out branch r2.8, this forced Baselisk to download and install Bazel version 4.2.1. 
```
# Download Latest version of Bazelisk
!wget https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64

# Make script executable
!chmod +x bazelisk-linux-amd64

# Adding to the path
!sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

# Extract bazel info
!bazel
```

Then everything finished OK! I have to verify that the 2 .aar files that were generated are OK inside the android project.

Thanks for the help. You can close the issue.

**Comment by mohantym** [comment] 2022-09-26 23:51
ok @farmaker47 !
Thanks for the confirmation. Glad you were able to resolve this issue.
Thank you!

**Comment by farmaker47** [comment] 2022-09-27 08:13
Hi @mohantym 

Unfortunately the 2 generated files do not work inside android. I am getting
"E/om.vicom.teeja: No implementation found for void org.tensorflow.lite.TensorFlowLite.nativeDoNothing() (tried Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing and Java_org_tensorflow_lite_TensorFlowLite_nativeDoNothing__)
"

Any hints?

**Comment by mohantym** [comment] 2022-09-27 10:40
@farmaker47 !
Could you confirm that you  installed the aar files to your local maven repo and declared the dependency in build.gradle file too.
```
allprojects {
    repositories {
        mavenCentral()
        maven {  // Only for snapshot artifacts
            name 'ossrh-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
        mavenLocal()
    }
}

dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.1.100'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.1.100'
}
```
[Reference.](https://www.tensorflow.org/lite/guide/ops_select#building_the_android_aar)
Thank you!

**Comment by farmaker47** [comment] 2022-09-27 12:01
Hi @mohantym 

There are various ways to add these .aar files inside an android project. I choosed [this].(https://developer.android.com/studio/projects/android-library#psd-add-aar-jar-dependency) I have done this again in the past.
What I am noticing during this build with branch 2.8 and Bazel 4.2.1 is that it processes .cpp and .cc files but it does not process .so files as it was doing with master branch and Bazel 5.3.1. Do you think this has something to do with the issue?

Thanks

**Comment by farmaker47** [comment] 2022-09-27 12:43
@mohantym Also I see that with the 2.8 branch it uses --cxxopt='--std=c++14' to build the targets inside the build_aar.sh file.
```
# Build the standard aar package of no models provided.
if [ -z ${FLAG_MODELS} ]; then
  bazel ${CACHE_DIR_FLAG} build -c opt --cxxopt='--std=c++14' \
    --config=monolithic \
    --fat_apk_cpu=${TARGET_ARCHS} \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    //tensorflow/lite/java:tensorflow-lite

  print_output bazel-bin/tensorflow/lite/java/tensorflow-lite.aar
  exit 0
fi
```
At master branch it has ' --cxxopt='--std=c++17''

**Comment by mohantym** [comment] 2022-09-27 12:44
Ok @farmaker47 !
Thanks for the update. Could you give a try once with the 2.9/2.10 version , Bazel 5.0.0 and procedure mentioned in above [comment](https://github.com/tensorflow/tensorflow/issues/57840#issuecomment-1259316243).

**Comment by mohantym** [comment] 2022-09-27 12:46
Re-opening this issue Until it is properly resolved.

**Comment by farmaker47** [comment] 2022-09-27 13:03
For other people looking at this issue and building with branch 2.8 and Bazel 4.2.1. It seems that if you navigate inside the tensorflow_src/tensorflow foder and build with
```
!bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite
```
everything compiles OK and the .aar file works OK inside android. BUT you have to add also tensorflow-lite-api.aar file as a dependency from here https://repo1.maven.org/maven2/org/tensorflow/tensorflow-lite-api/2.8.0/. 

IMPORTANT you still have to add 
```
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.9.0'
```
if you have a tflite file with TensorFlow ops.

The above in this comment does not solve the primary issue which is that I do not get working .aar files with
```
!bash tensorflow/lite/tools/build_aar.sh \
  --input_models=/converted_model.tflite \
  --target_archs=arm64-v8a,armeabi-v7a
```

**Comment by farmaker47** [comment] 2022-09-27 14:03
@mohantym It seems that with branch r2.8 and configuration
```
!bash tensorflow/lite/tools/build_aar.sh \
  --input_models=/converted_model.tflite \
  --target_archs=x86,x86_64,arm64-v8a,armeabi-v7a
```
istead of
```
!bash tensorflow/lite/tools/build_aar.sh \
  --input_models=/converted_model.tflite \
  --target_archs=arm64-v8a,armeabi-v7a
```
I have a working tensorflow-lite.aar file
Now I am waiting for the tensorflow-lite-select-tf-ops.aar to verify all together.

**Comment by mohantym** [comment] 2022-09-27 14:51
Yes @farmaker47 !
You have to skip some flags while doing a selective build . Please update after your test.
Thank you!

**Comment by farmaker47** [comment] 2022-09-27 16:56
Yes @mohantym I confirm that I have both .aar files that work fine inside my project!

To recap for future developers. I have created a procedure to build tensorflow-lite-select-tf-ops.aar with Colab as I think this is easier than building locally with or without Docker. This has the drawback that you need high power CPU colab and you have to switch to Colab Pro or connect your runtime to a Google Cloud Platform VM instance with at least 24 CPUs and 100GBs of RAM.
I had to switch to branch r2.8 and install Bazel 4.2.1 to have a successful build. Also for my phone Xiaomi Note 6 Pro I had to build for all artifacts x86,x86_64,arm64-v8a,armeabi-v7a and not only arm64-v8a,armeabi-v7a (which still is a mystery for me). The final command was
```
!bash tensorflow/lite/tools/build_aar.sh \
  --input_models=/converted_model.tflite \
  --target_archs=x86,x86_64,arm64-v8a,armeabi-v7a
```
Now the final .apk is 45MB and used to be 200MB. Also with this procedure you do not have to add the tensorflow-lite-api.aar file inside the project.

This Colab notebook will be added to my Github account after polishing it.

@mohantym Thank you for your patience.

**Comment by sachinprasadhs** [comment] 2022-09-28 18:57
@farmaker47 , If the issue is resolved, could you please close the issue. Thanks!

**Closed** 2022-09-29 03:00 UTC
Labels: stat:awaiting response, type:bug, comp:lite, TF 2.8
