### ISSUE TITLE
Do you have plan to remove –cxxopt=”-D_GLIBCXX_USE_CXX11_ABI=0 in build?

### ISSUE THREAD

**Issue by guizili0** [tensorflow/tensorflow#54295] opened 2022-02-08 01:45 UTC
Hi,

I found the latest TensorFlow release binary is build with “–cxxopt=”-D_GLIBCXX_USE_CXX11_ABI=0" for compatibility with the older ABI, do you have plain to remove this one? that mean build with --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1"

**Comment by mohantym** [comment] 2022-02-08 10:05
Hi @guizili0 ! Could you please fill the [template ](https://github.com/tensorflow/tensorflow/issues/new/choose)which would help us expedite the issue ? Thanks!

**Comment by guizili0** [comment] 2022-02-09 01:15
**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.8
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

In Tensorflow Plugin, I want to build my plugin with clang compiler but meet this ABI issue. So want to know do you team have plan to remove "–cxxopt=”-D_GLIBCXX_USE_CXX11_ABI=0" in the feature? Thanks.

**Comment by bhack** [comment] 2022-02-09 08:16
It Is a duplicate of https://github.com/tensorflow/tensorflow/issues/34946

**Comment by chunduriv** [comment] 2022-02-09 12:34
@guizili0,

As [suggested](https://github.com/tensorflow/tensorflow/issues/54295#issuecomment-1033473564), this issue is a duplicate of  https://github.com/tensorflow/tensorflow/issues/34946. Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2022-02-10 01:11 UTC
Labels: stat:awaiting response, type:build/install, subtype: ubuntu/linux, TF 2.8
