### ISSUE TITLE
Tensorboard Embedding with t-SNE Crash

### ISSUE THREAD

**Issue by smar10** [tensorflow/tensorflow#7620] opened 2017-02-17 12:28 UTC
When I run t-SNE on my datasets (on smallest or bigger one) with tensorboard embedding , the app crash all the times (after thereabout 500 iterations). I can't re-run or stop the operation to change the parameters, the iteration number freeze and the other functionalities on embedding part crash also.

Anyone have the same problem ? Other curiosity is if I run on [online tensorboard](http://projector.tensorflow.org/) embedding I have the same problem.

**Comment by aselle** [comment] 2017-02-19 06:12
Not sure you are the right person to ask, @dsmilkov, but could you  please take a look at this?
Thanks so much in advance!

**Comment by smar10** [comment] 2017-02-19 17:55
Thanks @aselle !

**Comment by dsmilkov** [comment] 2017-02-20 23:48
Hi @smar10,

Thanks for reporting. We'll need some info to help us reproduce the problem.

1. What browser and OS are you using?
2. What is the size of your dataset (number of points and dimensionality)?
3. If (some of) your datasets are public, can you share it with us?

Thanks!

**Comment by smar10** [comment] 2017-02-21 17:13
Hi @dsmilkov, 
After reading your questions and get more problems on audio tab on tensorboard, I realized what the issue might be... I was using Safari instead of Chrome. 
I make some tests with same dataset and it's all ok on Chrome.

**Comment by dsmilkov** [comment] 2017-04-14 00:53
Hi @smar10,

Can you share the size (number of points) of the dataset and the dimensionality of the embeddings, so that we have a sense of what the crash on Safari might be related to.

Thanks!

**Comment by itsmeolivia** [comment] 2017-06-16 19:31
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by itsmeolivia** 2017-06-16 19:31 UTC
Labels: type:bug/performance
