### ISSUE TITLE
Protocol messages are limited to 64MB in python

### ISSUE THREAD

**Issue by kuprel** [tensorflow/tensorflow#1100] opened 2016-02-15 06:18 UTC
The classify_image.py example isn't working because inception v3 is larger than 64MB

[libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.

**Comment by vrv** [comment] 2016-02-15 06:22
Duplicate of https://github.com/tensorflow/tensorflow/issues/582

**Closed by vrv** 2016-02-15 06:22 UTC
