### ISSUE TITLE
Keras: inconsistent behavior of "embedded" models

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#45437] opened 2020-12-07 07:46 UTC
Not sure if this a bug (I am inclined to believe so) or not, but it looks strange/inconsistent to me...
Consider the following scenario (a simple "embedded" model case):
```python
m1 = Sequential([
    Input((100,)),
    Dense(20),
    Dense(10),
])

m2 = Sequential([
    Input((100,)),
    m1,
    Dense(5),
])
```

Now, assume that I would like to extract features from an internal layer of the models.
The following example works as expected:

```python
test1 = Model(m1.input, m1.layers[1].output)
test2 = Model(m2.input, m2.layers[1].output)
```

However, this one fails, even though I would expect it to be equivalent to `test1` above:
```python
test3 = Model(m2.input, m2.layers[0].layers[1].output)
```
The error is:
```python
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_3:0", shape=(None, 100), dtype=float32) at layer "dense_3". The following previous layers were accessed without issue: []
```

It seems that the following "trick" does the job:
```python
test4 = Model(m2.layers[0].input, m2.layers[0].layers[1].output)
```

Now, there is another peculiarity, which seems rather annoying to me:
```python
m1.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_3 (Dense)              (None, 20)                2020      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                210       
=================================================================
Total params: 2,230
Trainable params: 2,230
Non-trainable params: 0
_________________________________________________________________

```
The model has two layers (no input layer), whereas this one has three layers...

```python
test4.summary()

Model: "functional_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 100)]             0         
_________________________________________________________________
dense_3 (Dense)              (None, 20)                2020      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                210       
=================================================================
Total params: 2,230
Trainable params: 2,230
Non-trainable params: 0
_________________________________________________________________
```

What is interesting `tf.keras.utils.plot_model` produces identical graphs (with input layers) for both `m1` and `test4`.

**Comment by ravikyram** [comment] 2020-12-07 10:14
@eli-osherovich 

Please, let us know which TF version you are using.You are seeing the same behavior with recent TF versions like 2.4-rc3 and nightly versions?

Thanks!

**Comment by eli-osherovich** [comment] 2020-12-07 12:41
This is TF 2.3.0

**Comment by eli-osherovich** [comment] 2020-12-08 06:26
The results are reproducible in tf-nightly
```
In [14]: tf.__version__
Out[14]: '2.5.0-dev20201207'

In [15]: tf.__git_version__
Out[15]: 'v1.12.1-47044-gfefcd5704ba'
```

**Comment by bhack** [comment] 2020-12-08 11:04
@eli-osherovich About the summary It Is ok to have this different behaviour. Input https://github.com/tensorflow/tensorflow/issues/35515#issuecomment-571266052

See also the difference between Input and InputLayer https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputLayer

**Comment by eli-osherovich** [comment] 2020-12-08 18:48
@bhack 
Why is it okay to have InputLayer in models created via functional API but not in models created with the Sequential API? 
In case one wants to access, say, third layer in the network he/she will have to check whether it is sequential or functional?

**Comment by bhack** [comment] 2020-12-08 18:56
It is in the doc link:
> It is generally recommend to use the functional layer API via Input, (which creates an InputLayer) without directly using InputLayer.
When using InputLayer with Keras Sequential model, it can be skipped by moving the input_shape parameter to the first layer after the InputLayer.


You can still access to layer by name as in https://keras.io/getting_started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer-feature-extraction

**Comment by eli-osherovich** [comment] 2020-12-08 19:24
It might be that I do not understand something... `m1` and `m2` do use `keras.Input`, however their summary (and more important `.layers` property) do not have `InputLayer`.

**Comment by bhack** [comment] 2020-12-08 19:33
Yes but as you see `m1` and `m2` are sequential and you are using `Input` not `InputLayer`

test4 is implicit functional (see the autoname of the model `Model: "functional_19"`)

> **functional layer API** via Input, (which creates an InputLayer) without directly using InputLayer.

**Comment by eli-osherovich** [comment] 2020-12-08 19:35
@bhack please see my updated response above yours. 
Isn't it reasonable to expect identical models in these two cases?

**Comment by bhack** [comment] 2020-12-08 19:43
Yes exactly, again:
> functional layer API via Input, (which creates an InputLayer) without directly using InputLayer.

And you first model in our last example `m1` is functional.

**Comment by eli-osherovich** [comment] 2020-12-08 19:50
Sorry for being "dumb". My main point is not what documentation says, but how things behave (and whether people *expect* this behavior). I would expect (and probably more people) that these three models would be identical:

```python
x = Input((128,))
y = Dense(64)(x)
m1 = Model(x, y)

m2 = Sequential([Input((128,)), Dense(64)])

m3 = Sequential([InputLayer((128,)), Dense(64)])
```

However, they are not
`m1` has *two* layers, whereas `m2` and `m3` both have only one layer.


P. S.
With that said, I do not see how the documentation part you cited explains this behavior...

**Comment by bhack** [comment] 2020-12-08 20:35
The documentation source is https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputLayer

If you want the historical motivation about Sequential summary see:
https://github.com/tensorflow/tensorflow/blob/42c2ae60913b517a5c345bf35185afe412f587ee/tensorflow/python/keras/engine/sequential.py#L148-L157

**Comment by eli-osherovich** [comment] 2020-12-08 20:45
Thanks, @bhack! 
So, there is difference between Sequential and Functional. Wouldn't it be correct to "fix" the way Sequential "hides" its input layer?

**Comment by bhack** [comment] 2020-12-08 20:51
It was accepted in 2019 for `model_to_dot` with https://github.com/tensorflow/tensorflow/pull/24637
But rejected for `summary` with https://github.com/keras-team/keras/pull/12388#issuecomment-469348981

@Wiki-fan asked about inconsistency at https://github.com/keras-team/keras/pull/12388#issuecomment-469351075 but without any reply.

/cc @fchollet If he want to add something more, by an historical point of view, about the divergence between `model_to_dot` and `summary`?

**Comment by eli-osherovich** [comment] 2020-12-09 06:02
Please note, that printing or drawing is not the biggest problem. Accessing layers' outputs may be problematic since the number of layers is different. 

Which brings me back to the original topic of this question: how one can access (the output of) an "internal" layers (from a nested model)?

**Comment by bhack** [comment] 2020-12-09 13:52
If you don't like layers names you can still access with `index` when you create the functional mode (your Model() calls examples):

`keras.Model(m2.get_layer(index=0).input, m2.get_layer(index=0).output)`

**Comment by eli-osherovich** [comment] 2020-12-09 16:51
@bhack 
I love layers names. I want the following code to work as expected:

```python
m1 = Sequential([
    Input((100,)),
    Dense(20),
    Dense(10),
])

m2 = Sequential([
    Input((100,)),
    m1,
    Dense(5),
])

test3 = Model(m2.input, m2.layers[0].layers[1].output)
```

**Comment by bhack** [comment] 2020-12-09 19:04
I don't know what do you expect but that will not work.
Please give two different names to `m1` input and `m2` input:

```
print(m2.get_layer(index=0).input.name)
print(m2.input.name)
test3 = keras.Model(m2.get_layer(index=0).input,m2.layers[0].layers[1].output)
```

**Comment by eli-osherovich** [comment] 2020-12-10 06:55
Honestly, I do not get it. This is the canonical way to extract features from an intermediate layer: one uses model's input and that layer output. It works with usual networks, but not with "embedded" ones.

**Comment by bhack** [comment] 2020-12-10 10:12
I don't understand what you want to do:

```python
from tensorflow import keras
m1 = keras.Sequential([
    keras.layers.Input((100,),name="m1_input"),
    keras.layers.Dense(20),
    keras.layers.Dense(10),
])

m2 = keras.Sequential([
    keras.layers.Input((100,),name="m2_input"),
    m1,
    keras.layers.Dense(5,name="bni"),
])
test1 = keras.Model(m1.input, m1.layers[1].output)
test2 = keras.Model(m2.get_layer(index=0).input, m2.get_layer(index=0).output)
test3 = keras.Model(m2.get_layer(index=0).input, outputs=m2.layers[0].layers[1].output)
test4 = keras.Model(m2.layers[0].input, m2.layers[0].layers[1].output)

print(m2.get_layer(index=0).input.name)
print(m2.input.name)
test3 = keras.Model(m2.get_layer(index=0).input,m2.layers[0].layers[1].output)
```

```
m1_input:0
m2_input:0
```

So with your `test3 = Model(m2.input, m2.layers[0].layers[1].output)` you are trying to connect `m1_input`

**Comment by eli-osherovich** [comment] 2020-12-10 11:27
@bhack I want to extract features from a layer in `m2`, which is inside the embedded `m1`.

**Comment by bhack** [comment] 2020-12-10 12:32
>  love layers names. I want the following code to work as expected:
....
test3 = Model(m2.input, m2.layers[0].layers[1].output)

This is exactly the same as:
`test3 = keras.Model(m2.input, m1.layers[1].output)`

And this doesn't work also for not nested models. 
As this is not a bug you need to close this and ask as a support questions to our stackoverflow space at https://stackoverflow.com/questions/tagged/tensorflow

Thanks

**Comment by eli-osherovich** [comment] 2020-12-10 14:46
@bhack  can you please explain why?

I do not agree that this is the same: both inputs and outputs belong to `m2`. Furthermore, the following code does not generate an error:
```python
test4 = Model(m2.layers[0].input, m2.layers[0].layers[1].output)
```
P. S.
Can you please show the right way to extract features from internal layers of an embedded network?

**Comment by bhack** [comment] 2020-12-10 15:06
Is the same cause If you start to give to  all the layers an unique name and you start to print the names of the layers you get you can verify yourself that `m1.layers[1].output` is exactly `m2.layers[0].layers[1].output`.

As It Is not a bug or a feature request if you need support use Stackoverflow.

**Comment by eli-osherovich** [comment] 2020-12-10 15:48
I meant this is not the same since `m1` is embedded into `m2` (unlike the case, where these two models are unrelated). Hence, there is a path from `m2.input` into `m1`.

 Can you please show the right way to extract features from internal layers of an embedded network?

**Comment by bhack** [comment] 2020-12-10 16:14
> I meant this is not the same since m1 is embedded into m2 (unlike the case, where these two models are unrelated)

This is you interpretation but it doesn't work like you are expecting and if you check you have exactly the same error as `test3 = keras.Model(m2.input, m1.layers[1].output)`.

> Can you please show the right way to extract features from internal layers of an embedded network?

This part is just a support request and you need to post that on our Stackoverflow  space.

**Comment by qlzh727** [comment] 2020-12-10 20:06
Thanks @bhack for answering the question.

To echo some of the response and providing more context here:

1. keras.layers.InputLayer is a Layer and should be used with Sequential model, which stacks layer one by one. It is mainly used to define the input shapes, which is needed by following layers to build its weights.
2. keras.Input is NOT a Layer, and should be used with functional model. The functional model provides more freedom to build the model structure, eg multiple input/output, rather than just linear structure in sequential model.
3. Historically user was passing keras.Input to sequential model, which is kind of discouraged. We still allow it to avoid breaking too many existing use case.
4. We add a dummy InputLayer to sequential model if user doesn't provide any. This is also why we don't show any InputLayer in the sequential model summary.
5. For functional model, since user has to provide input/output, we show all the input/output in the model summary, which is why you see it (and confused you with sequential model summary).

Overall, I think using Input with sequential model is not encourage, and should be replaced with InputLayer. In the meantime, please also forward any request for feature extraction to Stackoverflow to get more help from community.

**Closed by qlzh727** 2020-12-10 20:06 UTC
Labels: TF 2.3, comp:keras, stat:awaiting tensorflower, type:support

**Comment by bhack** [comment] 2020-12-10 20:16
@qlzh727 Probably, If we want to take something good from this ticket hanldlig,  maybe we could add a warning somewhere in the code for Sequential + Input what do you think?

**Comment by qlzh727** [comment] 2020-12-10 22:14
> @qlzh727 Probably, If we want to take something good from this ticket hanldlig, maybe we could add a warning somewhere in the code for Sequential + Input what do you think?

Sure, will send a change soon.

**Comment by eli-osherovich** [comment] 2020-12-11 11:57
Please update the documentation too. Today it is exactly how Sequential is demonstrated (with kearas.Input):
https://www.tensorflow.org/api_docs/python/tf/keras/Sequential
