### ISSUE TITLE
TensorFlowInferenceInterface's feed method - a performance bottleneck

### ISSUE THREAD

**Issue by theyonibomber** [tensorflow/tensorflow#15626] opened 2017-12-25 14:44 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Compiled on macos 10.13.2, Observed on Android 
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: commit ab0fcaceda on master - between release of 1.4.0 and 1.4.1 (compared to 1.0.1)
- **Python version**: N/A (java android code)
- **Bazel version (if compiling from source)**: 0.7.0-homebrew
- **GCC/Compiler version (if compiling from source)**: Apple LLVM version 9.0.0 (clang-900.0.39.2)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: Observed on a Huawei Nexus 6P
- **Exact command to reproduce**: N/A (java android code)

### Describe the problem
Following the move to Java API in commit 1a9769dc79fdd27c347633df210ff64f48de8d07, it seems that it is very ineffective to feed nodes.
I am feeding my model an input array of about 1100 floats, and when I sample CPU usage using CPU Profiler on Android Studio (Instrumented) it seems that the feed method takes ~x4 time than running the inference. If I leave everything the same but I use android libs compiled in tensorflow 1.0.1 CPU time of feed method (used to be fillNodeFloat) becomes negligible.
It seems that putting a float array into the Tensor's FloatBuffer is a very costly operation.

### Source code / logs
**TF 1.4.0:**
Relevant inference code:
```
tensorflow.feed(INPUT_NODE_NAME, input, shape);
tensorflow.run(OUTPUT_NAMES);
tensorflow.fetch(OUTPUT_NAMES[0], output);
```

Screenshot of CPU Profiler's call chart: https://www.dropbox.com/s/nx5q730l0fbd05x/TF_1.4_CallChart.png?dl=0
Screenshot of CPU Profiler's top-down breakdown of the 2 methods: https://www.dropbox.com/s/gh9vza3jmb5uzrn/TF_1.4_TopDown.png?dl=0

**TF 1.0.1:**
Relevant inference code:
```
tensorflow.fillNodeFloat(INPUT_NODE_NAME, shape, input);
tensorflow.runInference(OUTPUT_NAMES);
tensorflow.readNodeFloat(OUTPUT_NAMES[0], output);
```

Screenshot of CPU Profiler's call chart: https://www.dropbox.com/s/jrl2ggnsncx97ry/TF_1.0.x_CallChart.png?dl=0
Screenshot of CPU Profiler's bottom-up breakdown of the 2 methods: https://www.dropbox.com/s/tz5ldp4qnavhx17/TF_1.0.x_BottomUp.png?dl=0

**Comment by asimshankar** [comment] 2017-12-29 04:31
Thanks for the report. This is surprising since from a cursory look I don't think there is any added inefficiency (for example, in terms of number of copies from Java to C++). I'll dig in a bit more.

However, in the mean time, is it easy for you to test your application right before and right after the commit that moved to the Java API? (Just to rule out any other changes between TF 1.0.1 and 1.4 that may be the cause of the slowdown)?

**Comment by theyonibomber** [comment] 2017-12-31 19:19
Hi, verified. With Android Studio 3.1 (Canary) it's easier to see method runtime.
For commit 1b960c30ab (1 before move to Java): `runInference` took 6ms, `fillNodeFloat` took <1ms
For commit 1a9769dc79fdd27c347633df210ff64f48de8d07: `runInference` took 6ms, `fillNodeFloat` took 49ms.

Most of the time goes on `Tensor.create()`. Relevant line:
```
        t.buffer().asFloatBuffer().put(data);
```

**Comment by tensorflowbutler** [comment] 2018-01-17 19:13
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by saudet** [comment] 2018-01-27 05:17
FloatBuffer.put(float[]) and get(float[]) are very costly operations on Android:
https://code.google.com/archive/p/javacpp/issues/11

**Comment by tensorflowbutler** [comment] 2018-02-10 19:18
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by saudet** [comment] 2018-02-16 08:34
FYI, it's also possible to use the C++ interface directly via JavaCPP and bypass all the slow paths that way too: https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow
https://medium.com/google-cloud/how-to-invoke-a-trained-tensorflow-model-from-java-programs-27ed5f4f502d

**Comment by tensorflowbutler** [comment] 2018-03-03 15:03
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-18 16:06
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-02 12:27
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-17 12:49
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-02 18:49
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-17 18:57
Nagging Assignee @asimshankar: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-02 07:16
Nagging Assignee @asimshankar: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-17 18:33
Nagging Assignee @asimshankar: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-03 00:57
Nagging Assignee @asimshankar: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-17 19:23
Nagging Assignee @asimshankar: It has been 151 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-01 18:49
Nagging Assignee @asimshankar: It has been 166 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-16 20:01
Nagging Assignee @asimshankar: It has been 181 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 19:29
Nagging Assignee @asimshankar: It has been 196 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:33
Nagging Assignee @asimshankar: It has been 211 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:44
Nagging Assignee @asimshankar: It has been 225 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:45
Nagging Assignee @asimshankar: It has been 240 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:39
Nagging Assignee @asimshankar: It has been 255 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 18:58
Nagging Assignee @asimshankar: It has been 271 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-29 19:03
Nagging Assignee @asimshankar: It has been 286 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2019-08-06 22:12
Closing due to staleness. Please check with the latest version of TensorFlow. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-08-06 22:12 UTC
