### ISSUE TITLE
Tensorflow 1.9 for CPU, without GPU still requires cudNN - Windows

### ISSUE THREAD

**Issue by tonystark12** [tensorflow/tensorflow#21261] opened 2018-07-31 03:52 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: pip 18.0 - pip install tensorflow
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**: import tensorflow after pip install tensorflow

### Describe the problem
I am working on a Win10 machine, with python 3.6.3 and using tensorflow 1.9, pip 18.0. I did not provide an option to install tensorflow with gpu, (i.e.), according to this

https://www.tensorflow.org/install/install_windows, 

I used

        pip install tensorflow

and did not provide option for using GPU. However, when trying to import tensorflow, I am faced with the following error

        ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

After following various links,
 
https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso,
https://github.com/tensorflow/tensorflow/issues/8385,
 
I installed the **Visual studio update 3** and also used the script provided for **tensorflow self check**,  

https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c, 

and came across this following error:

        Could not load 'cudart64_80.dll'. .....
        Could not load 'nvcuda.dll' .......
        Could not load 'cudnn64_5.dll' ........

Why is my Tensorflow looking for these packages, when I installed it without GPU? MY system doesn't house a GPU at the moment. I tried uninstall and reinstalling with the **upgraded pip 18.0**, but the issue persists. How can this be rectified.?

### Source code / logs

--------------------------------------------------------------------------------------
Errors in Detail. in Jupyter notebook while trying import - 

ImportError                               Traceback (most recent call last)
c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

c:\python36\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

c:\python36\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

c:\python36\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

c:\python36\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

c:\python36\lib\importlib\_bootstrap.py in _load_unlocked(spec)

c:\python36\lib\importlib\_bootstrap.py in module_from_spec(spec)

c:\python36\lib\importlib\_bootstrap_external.py in create_module(self, spec)

c:\python36\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     16             return importlib.import_module('_pywrap_tensorflow_internal')
---> 17     _pywrap_tensorflow_internal = swig_import_helper()
     18     del swig_import_helper

c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     15         except ImportError:
---> 16             return importlib.import_module('_pywrap_tensorflow_internal')
     17     _pywrap_tensorflow_internal = swig_import_helper()

c:\python36\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-28ca7626b6fd> in <module>()
      1 get_ipython().run_line_magic('pylab', 'inline')
----> 2 from keras import regularizers, activations
      3 from keras.models import Sequential, load_model
      4 from keras.utils import np_utils,plot_model,to_categorical
      5 import pandas

c:\python36\lib\site-packages\keras\__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

c:\python36\lib\site-packages\keras\utils\__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

c:\python36\lib\site-packages\keras\utils\conv_utils.py in <module>()
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

c:\python36\lib\site-packages\keras\backend\__init__.py in <module>()
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

c:\python36\lib\site-packages\keras\backend\tensorflow_backend.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages

c:\python36\lib\site-packages\tensorflow\__init__.py in <module>()
     20 
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23 from . import app
     24 from . import bitwise

c:\python36\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

--------------------------------------------------------------------------------------
Tensorflow Self Check output

ERROR: Failed to import the TensorFlow module.

WARNING! This script is no longer maintained! 
=============================================
Since TensorFlow 1.4, the self-check has been integrated with TensorFlow itself,
and any missing DLLs will be reported when you execute the `import tensorflow`
statement. The error messages printed below refer to TensorFlow 1.3 and earlier,
and are inaccurate for later versions of TensorFlow.

- Python version is 3.6.

- TensorFlow is installed at: C:\Python36\lib\site-packages\tensorflow

- Could not load 'cudart64_80.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Download and install CUDA 8.0 from
  this URL: https://developer.nvidia.com/cuda-toolkit

- Could not load 'nvcuda.dll'. The GPU version of TensorFlow requires that
  this DLL be installed in a directory that is named in your %PATH%
  environment variable. Typically it is installed in 'C:\Windows\System32'.
  If it is not present, ensure that you have a CUDA-capable GPU with the
  correct driver installed.

- Could not load 'cudnn64_5.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Note that installing cuDNN is a
  separate step from installing CUDA, and it is often found in a
  different directory from the CUDA DLLs. You may install the
  necessary DLL by downloading cuDNN 5.1 from this URL:
  https://developer.nvidia.com/cudnn

- Could not find cuDNN.

--------------------------------------------------------------------------------------

**Comment by karmel** [comment] 2018-07-31 16:31
@gunan -- pip installation problems on Windows CPU; can you advise?

**Comment by gunan** [comment] 2018-07-31 16:36
I just confirmed that in our CI we can load the pip package without cudnn.
Is it possible you are running into https://github.com/tensorflow/tensorflow/issues/19584

**Comment by MJClarke93** [comment] 2018-08-15 03:47
I have the same problem. Windows 10 64-bit, Python 3.6.6, Pip 18.0. Attempting to import it using "import tensorflow" in the interactive console results in all of the same errors as in the OP. Testing with Tensor-Self-Check gives the same log as the OP. TensorFlow 1.8 works fine, but both 1.9 and 1.10 give the error. I used coreinfo to check if my CPU supports AVX, and it does.

**Comment by gunan** [comment] 2018-08-15 05:52
What is your CPU model?
I confirmed that it is not cudnn we are missing. But rather having a CPU without AVX can cause similar error messages.

**Comment by tonystark12** [comment] 2018-08-16 03:15
Thank you for your help and information. I installed 1.5 and it worked. As stated in the issue above, I think from version 1.6 and above, it requires AVX instruction sets. I did not check for them though.

I had also posted the question in stackoverflow, and here's the [link](https://stackoverflow.com/questions/51605105/tensorflow-1-9-for-cpu-without-gpu-still-requires-cudnn-windows/51606222?noredirect=1#comment90201596_51606222) to it.

According to the only answer there, am missing **VCOMP140.dll**, which I could not find even after installing the redistributable.

**Comment by tensorflowbutler** [comment] 2018-08-31 19:33
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:51
Nagging Assignee @gunan: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-15 19:10
Closing as duplicate of #19584

**Closed by gunan** 2018-09-15 19:10 UTC
