### ISSUE TITLE
New version 1.6 "pip install --upgrade tensorflow " installs tensorflow-gpu NOT tensorflow (cpu)....

### ISSUE THREAD

**Issue by MilkTeaD** [tensorflow/tensorflow#17520] opened 2018-03-07 22:04 UTC
1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
**BUG**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**WINDOWS 10.0**
- TensorFlow installed from (source or binary):
**pip (binary)**
- TensorFlow version (use command below):
**1.6**
- Python version: 
**tried both python 3.5.2 & 3.6.4**
- CUDA/cuDNN version: 
NO CUDA
- GPU model and memory:
**NO GPU**
- Exact command to reproduce:
**pip install --upgrade tensorflow**

### Describe the problem
import tensorflow as tf 
give the error (No module named "pywrap_tensorflow")
Issue 42011070 on stack 
There : it became clear that it is a cudannxx_x.dll , i.e. CUDA error.   
I have tensorflow-gpu running flawlesly on NVIDIA GPU
### Source code / logs
No module named _pywrap_tensorflow

**Comment by tensorflowbutler** [comment] 2018-03-08 07:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version

**Comment by gunan** [comment] 2018-03-08 08:20
There can be more root causes to your problem. I have verified that windows CPU package is indeed built for CPU.
It is possible that your CPU does not have AVX instruction set. Could you share your CPU model?

**Comment by gunan** [comment] 2018-03-08 08:22
potential duplicate of #17386

**Comment by MilkTeaD** [comment] 2018-03-08 10:15
I Tried it on processors : XEON W 3565  - Core i3 550 (both somewhat older models supposedly do not have avx) and on a Celeron 3930 : wikipedia Q1 2017 Kaby Lake supposedly having avx, no? (exactly same error _pywrap_tensorflow_internal // DLL load failed)
I tried also on a AMD FX(tm)-6300 ... and .... YES : we have a winner : it is an AVX problem - duplicate of #17386 
Celeron 3930 was a bit doubt ... but aparently has NO avx ... the AMD-FX-6300 clearly has (as stated on the webpage of the processor.  
Et voila, thank you gunan for putting me on the right track.
I have a bunch of Xeon's they gave me to play with, old ones, but still good enough to satisfy the guy in R&D with :-) .I'll use TF 1.5 or try the whl-solution mentioned in the other post
You should really document this thing, because it took me two days, just for nothing.

**Comment by gunan** [comment] 2018-03-08 23:17
Thanks for the feedback.
We did merge some updates to the installation guide, however we did not push it to the website yet.
We will look into getting it out there quickly.

**Closed by gunan** 2018-03-08 23:17 UTC

**Comment by ashiqak** [comment] 2020-03-02 16:50
how to install a specific version of tensorflow in windows @anconda distribution
