### ISSUE TITLE
I got an error with MomentumOptimizer

### ISSUE THREAD

**Issue by brantbzhang** [tensorflow/tensorflow#1914] opened 2016-04-13 12:39 UTC
I can't use MomentumOptimizer,it show that:

tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'target_embeddings/read': Could not satisfy explicit device specification '/device:GPU:0' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'

**Comment by mrry** [comment] 2016-04-13 14:20
A quick workaround for this problem is to declare your embedding matrix (`target_embeddings`) on CPU:

```python
with tf.device("/cpu:0"):
  target_embeddings = tf.Variable(..., name="target_embeddings")
```

**Comment by vrv** [comment] 2016-05-02 18:32
@mrry: what is the exact problem?

**Comment by mrry** [comment] 2016-05-02 20:09
The problem is (or seems to be) that the variable+initializer get assigned to GPU when the initializer runs, but the training op is CPU-only, leading to this error. Your upcoming placer changes should fix this, so hopefully it'll be no extra work! :)

**Closed** 2016-05-17 16:58 UTC
