### ISSUE TITLE
Question about r1.5's default ptxas GPU back-end

### ISSUE THREAD

**Issue by yangjunpro** [tensorflow/tensorflow#16098] opened 2018-01-13 09:59 UTC
From TF r1.5's release notes, it is said that "GPU back-end now uses ptxas to compile generated PTX."  I have searched through the entire git repo of r1.5 code base with only finding that ptxas will be invoked in XLA flow.
Since we are working on some XLA and GPU optimization stuffs, I just want to make sure the meaning of this sentence since I am a little bit puzzle about it and want to ensure our development flow will align with the community major direction.

Thanks

**Comment by tensorflowbutler** [comment] 2018-01-13 18:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-02-06 07:35
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-20 19:38
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:16
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 00:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-05-03 03:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-05-03 03:29 UTC
Labels: stat:awaiting response
