### ISSUE TITLE
Using tensor as parameter for tf.range and tf.slice

### ISSUE THREAD

**Issue by WhoisZihan** [tensorflow/tensorflow#23475] opened 2018-11-03 09:28 UTC
**System information**
- TensorFlow version (you are using): 1.11 cpu, Python 3.6.5
- Are you willing to contribute it (Yes/No): Yes? But contribute what?

**Describe the feature and the current behavior/state.**
I am using a model that will generate 2 intermediate values `yp1` and `yp2`( with shape [1, ] ) during training, who are supposed to be the start index and end index of another tensor `context_idxs` who has type [1, *] where the second dimension will change each input.

Now I'd like to extract `context_idxs[yp1 : yp2]` and further feed them into another LSTM cell, but since yp1 and yp2 is tensor, I could not do that directly or with `tf.slice`. I find a function called `tf.gather` that seems to be what I'm looking for, however, I need to generate a range `[yp1, yp1+1, yp1+2, ..., yp2]` to use `tf.gather`.

Then here comes the problem. `tf.range` seems  not to support using tensor as parameter. However, I can't know the value of yp1 and yp2 in the model (I know how to print them in sess.run, but I'm using them inside the model rather than from outside the graph).

I'll use a quick example
```python
self.yp1 = tf.argmax(tf.reduce_max(outer, axis=2), axis=1)
self.yp2 = tf.argmax(tf.reduce_max(outer, axis=1), axis=1)

# ??
# how do I get context_idxs[yp1 : yp2]? If context_idxs has shape [64, *], how do I get context_idxs[ : , yp1 : yp2]?
```

My questions are:
1. How can I get dynamic slice `context_idxs[yp1 : yp2]` of one tensor based on other tensors?
2. If I want to batch some values, for example, the yp1 and yp2 becomes `[64, 1]`, and context_idxs becomes [64, *], is there still any way to do so?
3. Is there any other way to show the value of variable just-in-time without having to `sess.run` each time? Something like normal python will be great.

**Will this change the current api? How?**
Maybe. I know tensorflow is based on graph but I think allowing just-in-time calculation of values will greatly make debugging easier. Normal python will make life much easier...

**Who will benefit with this feature?**
I don't know if anyone else needs it as I'm not an expert.

**Any Other info.**
Ubuntu 18.04.1
Python 3.6.5

**Comment by harshini-gadige** [comment] 2018-11-07 17:39
@drpngx  PTAL

**Comment by drpngx** [comment] 2018-11-07 18:10
For question 1, the slice operation takes in tensors, for instance:
```python
import tensorflow as tf
sess = tf.Session()
yp1 = tf.constant(1)
yp2 = tf.constant(3)
context_ids = tf.constant([0, 2, 4, 8])
sess.run(context_ids[yp1:yp2])
```
Returns `[2, 4]`.

For question 2, you'll need to clarify. If you set, for instance, in the example above,
```python
context_ids = tf.constant([[0, 10], [2, 12], [4, 14], [8, 18]])
sess.run(context_ids[yp1:yp2, :])
```
You'll get `[[2, 12], [4, 14]]`.
If you don't know the rank, you can use `...` instead of `:`.

For question 3, please look into "eager mode", which will be part of tensorflow 2.0, to be released soon.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Closed by drpngx** 2018-11-07 18:10 UTC

**Comment by WhoisZihan** [comment] 2018-11-08 01:44
Hi drpngx, thanks for your reply, I think I need to make my questions more clear.

About question 1, the yp1 and yp2 are not constant, but the output of a network(whose last layer is a linear layer), therefore yp1 and yp2 might be changing each time. When I tried to use them as indices, I got an error. I forgot to record it and I will see if I can reproduce it later.

For questions 2, suppose `context_ids = tf.constant([[0, 10], [2, 12], [4, 14], [8, 18]])`
I have yp1 and yp2 of shape (3, 2), e.g., `[[0, 1], [1, 2], [0, 2]]` and I expect to get result `[[0], [12], [8, 18]]` (it might be padded and be the input of next layer). Is it possible?

I look forward to eager mode.

Thanks!
