### ISSUE TITLE
tf.gfile.GFile issue on windows

### ISSUE THREAD

**Issue by happytian** [tensorflow/tensorflow#6880] opened 2017-01-16 15:28 UTC
When I use tf.gfile.GFile and set mode='rb' to open a file on windows, it will read as 'str' instead of 'byte'. For example,

f = tf.gfile.GFile("d2f42068.ini", mode='rb')
f.readline()
The result shows
'<KVList>\n'.
It should be 
b'<KVList>\n'

I find the gfile.py replace the 'r' to empty.
def __init__(self, name, mode='r'):
    mode = mode.replace('b', '')
    super(FastGFile, self).__init__(name=name, mode=mode)

This issue will cause some error of data reading on windows.

My OS is win10 x64. The version of tensorflow is r0.12.

**Comment by inflation** [comment] 2017-01-17 02:19
Did you use python3? See #6669.

**Comment by happytian** [comment] 2017-01-17 04:33
@inflation Yes, my python version is 3.5.2

**Comment by asimshankar** [comment] 2017-01-17 19:13
Thanks for pointing out the other bug @inflation .

@happytian : Closing this one out as a duplicate of #6669 . Let's have any further discussion/updates there.

**Closed by asimshankar** 2017-01-17 19:13 UTC
