### ISSUE TITLE
Problem compiling tensorflow for iOS on Sierra/Xcode 8

### ISSUE THREAD

**Issue by spiantino** [tensorflow/tensorflow#5333] opened 2016-11-01 18:09 UTC
with xcode-select pointed to Xcode 8:

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

I get the following compile error with build_all_ios.sh on Sierra:

```
checking whether we are cross compiling... configure: error: in `/Users/serkan/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Not sure if this is related to Xcode 8 or to code signing on Sierra

**Comment by aselle** [comment] 2016-11-01 20:47
Does your c compiler work i.e. try
```
cat >foo.c <<EOF
#include <stdio.h>
int main(){printf("hello\n");return 0;}
EOF
gcc foo.c
./a.out
```

**Comment by cowbjt** [comment] 2016-11-02 09:38
Got the same issue too.

The c compiler works.
Tested by @aselle  's test code.

P.S. my env: macOS 10.12 and XCode8.1

**Comment by aminbenarieb** [comment] 2016-11-03 14:33
Same error: macOS 10.12.1, XCode 8.1

**Comment by evogta** [comment] 2016-11-04 11:53
I’m not sure why Xcode 8.1 could not support iPhone simulator with CNN function, but Apple original CNN example does not work on simulators and could not build app. Then it’s working on real device only.

So, I wonder Tensorflow also could not run on simulators.
I modified the following sh files for disabling simulator build.

compile_ios_protobuf.sh
compile_ios_tensorflow.sh

I deleted “make” part for build and “lipo” part for archive lib file to the following directory related. 
${LIBDIR}/iossim_386/
${LIBDIR}/iossim_x86_64/

After modified I run “build_all_ios.sh” for building to  ${LIBDIR}/ libtensorflow-core.a .
That sh called two modified sh files.

The modified sh build libtensorflow-core.a without simulator libs.
But It run on the real iPhone device.
 …I run camera ios_example on iPhone 6 plus iOS 10.1.1
    used environment : macOS Sierra 10.12.1, and Xcode 8.1 with command line tools 8.1

Please try above for fixing configure issue in build phase.

**Comment by wanjianwei** [comment] 2016-11-14 11:28
I got the same error(macOS Sierra 10.12, XCode 8.1）,and don‘t know how to fix it.Does somebody have solutions?

**Comment by sahil912** [comment] 2016-11-14 11:32
follow #4640 which is similar issue as this. I fixed it removing all occurence of X86_64 bits from the build scripts compile_ios_protobuf.sh & compile_ios_tensorflow.sh and then running build_all_ios.sh
works great on device. 

Note the above fix will not run on simulator

**Comment by jart** [comment] 2017-01-16 03:01
Closing out as a duplicate of #4640.

**Closed by jart** 2017-01-16 03:01 UTC
Labels: awaiting response, type:build/install
