### ISSUE TITLE
Python package is missing ModuleSpec in tensorflow.__spec__ in tf 1.14.0

### ISSUE THREAD

**Issue by JonasAmrich** [tensorflow/tensorflow#30028] opened 2019-06-21 11:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): preinstalled in docker image
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

In TF 1.14.0 the module spec in `tensorflow.__spec__` is None:
```
>>> import tensorflow
>>> print(tensorflow.__spec__)
None
```

**Describe the expected behavior**

This is different from tf 1.13.1 where it works as expected:
```
>>> import tensorflow
>>> print(tensorflow.__spec__)
ModuleSpec(name='tensorflow', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f038cfc3cf8>, origin='/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py', submodule_search_locations=['/usr/local/lib/python3.5/dist-packages/tensorflow'])
```

Missing spec causes some problems, e.g. pkgutil now fails when trying to find tensorflow. Note that the first call to `find_loader` is successful, it only fails *after* tensorflow is imported:
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkgutil
>>> pkgutil.find_loader('tensorflow')
<_frozen_importlib_external.SourceFileLoader object at 0x7f62372c7160>
>>> import tensorflow
>>> pkgutil.find_loader('tensorflow')
Traceback (most recent call last):
  File "/usr/lib/python3.6/pkgutil.py", line 490, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/usr/lib/python3.6/importlib/util.py", line 102, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: tensorflow.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/pkgutil.py", line 496, in find_loader
    raise ImportError(msg.format(fullname, type(ex), ex)) from ex
ImportError: Error while finding loader for 'tensorflow' (<class 'ValueError'>: tensorflow.__spec__ is None)
```

**Code to reproduce the issue**
See above

**Other info / logs**

I've tested this using official tf docker image (tensorflow/tensorflow:1.14.0-py3) and also using python docker image (python:3.6) with tensorflow installed with pip.

**Comment by hhsecond** [comment] 2019-06-24 10:04
importlib throws the same error. Can't do custom imports in 1.14.
```
Traceback (most recent call last):
  File "path/test/test_model.py", line 62, in testTFGraph
    save_tensorflow(sess, path, output=['output'])
  File "path/model.py", line 55, in save_tensorflow
    if not is_installed('tensorflow'):
  File "path/_util.py", line 18, in is_installed
    if importlib.util.find_spec(p) is None:
  File "path/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: tensorflow.__spec__ is None
```

**Comment by mihaimaruseac** [comment] 2019-06-24 13:59
Another data point: this also happens in nightly

**Comment by annarev** [comment] 2019-06-27 20:48
Sorry for the breakage! This is caused by adding a module wrapper that prints deprecation messages. I will send a change to fix it.

**Comment by ymodak** [comment] 2019-07-09 20:24
Closing this issue since the associated PR has been merged. Thanks!

**Closed by ymodak** 2019-07-09 20:24 UTC
Labels: comp:apis, type:bug/performance

**Comment by SumNeuron** [comment] 2019-07-31 12:25
Is there a work around in the mean time?

**Comment by mihaimaruseac** [comment] 2019-08-05 14:07
We'll get the 1.14.1 patch release this week.

**Comment by mihaimaruseac** [comment] 2019-08-13 17:53
Update: Instead of a 1.14.1 patch release, we will get a 1.15 version in a few weeks. Sorry for the extra delay this causes.

**Comment by dean-rahman** [comment] 2022-04-07 10:51
I am getting  the error even after installing 1.15
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-013867c7255c> in <module>
----> 1 from evaluation import Trainer, DataLoader

~\Anaconda3\lib\site-packages\evaluation\__init__.py in <module>
      1 from evaluation.data import DataLoader
----> 2 from evaluation.evaluation import Trainer
      3 from evaluation.results import Results

~\Anaconda3\lib\site-packages\evaluation\evaluation.py in <module>
     33 from octis.models.LDA import LDA
     34 from octis.models.NMF import NMF
---> 35 from octis.models.CTM import CTM
     36 from octis.dataset.dataset import Dataset
     37 from octis.evaluation_metrics.diversity_metrics import TopicDiversity

~\Anaconda3\lib\site-packages\octis\models\CTM.py in <module>
      4 from octis.models.contextualized_topic_models.datasets import dataset
      5 from octis.models.contextualized_topic_models.models import ctm
----> 6 from octis.models.contextualized_topic_models.utils.data_preparation import bert_embeddings_from_list
      7 
      8 import os

~\Anaconda3\lib\site-packages\octis\models\contextualized_topic_models\utils\data_preparation.py in <module>
      1 import numpy as np
----> 2 from sentence_transformers import SentenceTransformer
      3 import scipy.sparse
      4 import warnings
      5 from octis.models.contextualized_topic_models.datasets.dataset import CTMDataset

~\Anaconda3\lib\site-packages\sentence_transformers\__init__.py in <module>
      1 __version__ = "2.2.0"
      2 __MODEL_HUB_ORGANIZATION__ = 'sentence-transformers'
----> 3 from .datasets import SentencesDataset, ParallelSentencesDataset
      4 from .LoggingHandler import LoggingHandler
      5 from .SentenceTransformer import SentenceTransformer

~\Anaconda3\lib\site-packages\sentence_transformers\datasets\__init__.py in <module>
      1 from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
      2 from .NoDuplicatesDataLoader import NoDuplicatesDataLoader
----> 3 from .ParallelSentencesDataset import ParallelSentencesDataset
      4 from .SentencesDataset import SentencesDataset
      5 from .SentenceLabelDataset import SentenceLabelDataset

~\Anaconda3\lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py in <module>
      2 import logging
      3 import gzip
----> 4 from .. import SentenceTransformer
      5 from ..readers import InputExample
      6 from typing import List

~\Anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py in <module>
      9 import numpy as np
     10 from numpy import ndarray
---> 11 import transformers
     12 from huggingface_hub import HfApi, HfFolder, Repository, hf_hub_url, cached_download
     13 import torch

~\Anaconda3\lib\site-packages\transformers\__init__.py in <module>
     28 
     29 # Check the dependencies satisfy the minimal versions required.
---> 30 from . import dependency_versions_check
     31 from .utils import (
     32     _LazyModule,

~\Anaconda3\lib\site-packages\transformers\dependency_versions_check.py in <module>
     34         if pkg == "tokenizers":
     35             # must be loaded here, or else tqdm check may fail
---> 36             from .utils import is_tokenizers_available
     37 
     38             if not is_tokenizers_available():

~\Anaconda3\lib\site-packages\transformers\utils\__init__.py in <module>
     31     replace_return_docstrings,
     32 )
---> 33 from .generic import (
     34     ContextManagers,
     35     ExplicitEnum,

~\Anaconda3\lib\site-packages\transformers\utils\generic.py in <module>
     25 import numpy as np
     26 
---> 27 from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
     28 
     29 

~\Anaconda3\lib\site-packages\transformers\utils\import_utils.py in <module>
     58 _tf_version = "N/A"
     59 if USE_TF in ENV_VARS_TRUE_AND_AUTO_VALUES and USE_TORCH not in ENV_VARS_TRUE_VALUES:
---> 60     _tf_available = importlib.util.find_spec("tensorflow") is not None
     61     if _tf_available:
     62         candidates = (

~\Anaconda3\lib\importlib\util.py in find_spec(name, package)
    112         else:
    113             if spec is None:
--> 114                 raise ValueError('{}.__spec__ is None'.format(name))
    115             return spec
    116 

ValueError: tensorflow.__spec__ is None
```
