### ISSUE TITLE
tensorflow.python.framework.errors.PermissionDeniedError: File isn't open for reading

### ISSUE THREAD

**Issue by DaveyTao** [tensorflow/tensorflow#4852] opened 2016-10-09 08:10 UTC
`
File "./encoder.py", line 103, in <module>
 tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "./encoder.py", line 99, in main
    np.savez_compressed(code_file, shape=int_codes.shape, codes=export)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 600, in savez_compressed
    _savez(file, args, kwds, True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 642, in _savez
    zipf.write(tmpfile, arcname=fname)
  File "/usr/lib/python2.7/zipfile.py", line 1146, in write
    zinfo.header_offset = self.fp.tell()    # Start of header bytes
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 139, in tell
    "File isn't open for reading")
tensorflow.python.framework.errors.PermissionDeniedError: File isn't open for reading
Exception tensorflow.python.framework.errors.PermissionDeniedError: PermissionDeniedError() in <bound method ZipFile.__del__ of <zipfile.ZipFile object at 0x7fc6f2011450>> ignored
`

**Comment by jart** [comment] 2016-10-13 02:02
Thanks for reporting this issue. In order for us to help, we need concrete steps to reproduce the bug.

**Comment by DaveyTao** [comment] 2016-10-13 07:24
@jart  I think this bug maybe caused by the numpy incompatibilities with the current TensorFlow version (r0.11). The detail refers to : https://github.com/tensorflow/models/pull/510.
When I run the code with tensorflow (r0.10), there is no error occured. 
Thank you.

**Comment by jart** [comment] 2016-10-17 03:48
@DaveyTao we encountered a PermissionDeniedError in #4913 where TensorFlow was being configured to save stuff in /tmp rather than creating a special subdirectory. It's possible this could be related to that.

Aside from that, I'm going to close this issue, because there isn't enough information here for closer examination or reproduction. I'll reopen this issue if provided new information.

**Closed by jart** 2016-10-17 03:48 UTC
