### ISSUE TITLE
tfdbg Dump root directory does not exist

### ISSUE THREAD

**Issue by XiaolongMeng** [tensorflow/tensorflow#7615] opened 2017-02-17 08:28 UTC
I run 
python -m tensorflow.python.debug.examples.debug_mnist --debug
on my laptop.which has windows 10 and gtx1070.but after I type first run,it return an exception like this:
Traceback (most recent call last):
  File "d:\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\debug\examples\debug_mnist.py", line 138, in <module>
    tf.app.run()
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\debug\examples\debug_mnist.py", line 131, in main
    acc = sess.run(accuracy, feed_dict=feed_dict(False))
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\debug\wrappers\framework.py", line 419, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\debug\wrappers\local_cli_wrapper.py", line 262, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "d:\Anaconda3\lib\site-packages\tensorflow\python\debug\debug_data.py", line 328, in __init__
    raise IOError("Dump root directory %s does not exist" % dump_root)
OSError: Dump root directory C:\Users\tony8\AppData\Local\Temp\tfdbg_cvtcdnhl does not exist

how can I fix it?Thank you

**Comment by caisq** [comment] 2017-02-19 01:16
Thanks for reporting this issue. I can reproduce it in 1.0.0 on Windows. It appears that this is because the core/debug module was not linked for the Windows cmake build (despite the fact that it is built for the Windows bazel build, but cmake is the one used in building the release binary). I'll fix it and the fix will be reflected in nightly builds and the next release. Sorry about the inconvenience it has caused.

cc @mrry, @gunan

**Comment by caisq** [comment] 2017-03-01 04:48
This is fixed by https://github.com/tensorflow/tensorflow/commit/d82e42ca3a0b06d768a439d84ff74741de7e092d

Please use our [Windows nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/) and/or wait for the next release.

**Closed by caisq** 2017-03-01 04:48 UTC
Labels: type:bug/performance

**Comment by atilaorh** [comment] 2017-03-12 09:27
I am having this issue on Ubuntu 14.04 & TF 0.12.1 (01/2017 version of Bitfusion Tensorflow AMI to be exact).

**Comment by gunan** [comment] 2017-03-12 22:23
TF debugger is only officially released with TF 1.0.
It not working with 0.12 version is expected.

**Comment by caisq** [comment] 2017-03-12 23:21
@atilaorh , can you confirm that you are experiencing this problem on Windows? The Windows-specific issue has been fixed in the master branch and the fix will be available in the next release (r1.1).

**Comment by caisq** [comment] 2017-03-12 23:42
@atilaorh , OK. Just realized that Bitfusion TensorFlow AMI is not Windows - it is Ubuntu Linux. Does the [example](https://www.tensorflow.org/programmers_guide/debugger) work for you? I'd like to rule out the possibility that the reason for the issue you are seeing is something specific to your model or the way you are suing tfdbg.

```
python -m tensorflow.python.debug.examples.debug_mnist --debug
```

**Comment by atilaorh** [comment] 2017-03-13 00:28
Sorry for the false alarm. This only happened once. Second run for the exact same script ran seamlessly. Example works as well..

**Comment by caisq** [comment] 2017-03-24 15:03
TensorFlow 1.1.0rc0 has just come out. tfdbg should be working on Windows 7 and up now. Please give it a try. 

Note: the default CLI of tfdbg on Linux and Mac uses curses. But there is no official curses support on Windows. So tfdbg CLI uses the less interactive readline on Windows, which does not have the mouse interaction and history navigation available on Linux and Mac.

**Comment by Joshuaalbert** [comment] 2017-10-10 10:22
I am getting this same issue on TF 1.3.0, Fedora 25 64-bit installed from pip.
