### ISSUE TITLE
//tensorflow/python:Sparse_split_op_test  is failing on Big Endian

### ISSUE THREAD

**Issue by jparinita** [tensorflow/tensorflow#3527] opened 2016-07-27 11:01 UTC
### Environment info

Operating System: Ubuntu/Red Hat

Installed version of CUDA and cuDNN:  Not installed 

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. **0.8.0**

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`) [ [4b7bc31](https://github.com/tensorflow/tensorflow/commit/4b7bc3174ed67b4a0eb1803537c9d00f132e9ae7)]
2. The output of `bazel version`  **0.3.0**
### Steps to reproduce
1.  Run `bazel test //tensorflow/python:Sparse_split_op_test`
### Logs or other output that would be helpful

It was observed that this particular test consists of row-wise and column-wise split of tensor.
Test is failing on execution of column wise tensor split in case of Big Endian. 
Please check attached stack-trace. 

[sparse_split_test_log.txt](https://github.com/tensorflow/tensorflow/files/385847/sparse_split_test_log.txt)

I checked the test is passing in case of  Little Endian (Ubuntu, Red Hat)

**Comment by michaelisard** [comment] 2016-07-27 20:20
@girving this looks like a bug but the code author isn't in the tf org. Would you assign appropriately?

**Comment by girving** [comment] 2016-07-27 21:57
@jparinita Is that the only test that fails?  I'm particularly curious whether any simpler tests exercising TensorShape might fail.

**Comment by jparinita** [comment] 2016-07-28 08:31
@girving  

There were many tests failing from //tensorflow/... test suite. 
Looks like  tensorflow is not supporting Big Endian as of now. 
We have made changes to source code to add big endian support ( changes for const bool kLittleEndian variable) 

With code changes, most of the tests are passing like 
```
//tensorflow/contrib/framework:ops_test 
//tensorflow/core:framework_op_kernel_test          
//tensorflow/core:util_sparse_sparse_tensor_test 
```     

However, we still couldn't figure out why Sparse_split_op_test is failing.

**Comment by girving** [comment] 2016-07-29 15:54
@jparinita That you for the fixes so far!  Would you be interested in sending them as a PR so I can see how TensorFlow is currently broken (and make it slightly less broken)?  My best guess is still that it's a bug in TensorShape, but I don't know where.

Note that TensorShape has been heavily optimized to avoid memory allocations, which involved quite a lot of case analysis.  It's possible that some of these cases are now correct in big endian and others are not.

**Comment by jparinita** [comment] 2016-08-03 09:50
@girving  

Could you please let us know the test "Sparse_split_op_test" which is failing can be ignored? Or is it used to test some complex functionality of TensorFlow?

About PR for Tensorflow,  I have built TensorFlow version 0.8.0 for big endian and also executed test cases for same version. I made few code changes related to big endian in the source code that I git cloned from tag 0.8.0.

Now, I am trying to build TensorFlow master on big endian and I am facing few build issues. 
Issues like: 
1. has a dependency on protobuf and need changes here.
2. Facing issue as 'Packet4f' does not name a type 
This one is related to EIGEN_VECTORIZE_SSE2. 

I haven't faced them on v0.8.0 before. 
I am looking into above issues. 
Once I could fix these issues and able to build master, I will create a PR .

**Comment by girving** [comment] 2016-08-03 14:38
@jparinita `sparse_split_op_test` mostly just tests that one op, but there's a good chance that the failure is in core functionality rather than that op so it's worth debugging.

**Comment by girving** [comment] 2016-08-09 23:32
Removing my assignment since I can't debug this personally.  Still happy to help with advice and code reviews.

**Comment by jparinita** [comment] 2016-08-22 13:10
@girving 

Since TensorFlow v0.9.0 was released, I have built v0.9.0 on big endian platform and currently executing tests.
`sparse_split_op_test` is failing on v0.9.0 as well.  Additionally, there are few more test failures seen such as 
```
//tensorflow/python:sparse_matmul_op_test
//tensorflow/python:string_to_hash_bucket_op_test
//tensorflow/python:conv_ops_test
//tensorflow/core/kernels:sparse_matmul_op_test_gpu
//tensorflow/python:determinant_op_test
```
I am debugging the code to find the root cause but no luck yet. 
Above mentioned tests seem to be related to ops functionality (`op_def_library.apply_op()`). 
Any suggestions would be helpful.

**Comment by girving** [comment] 2016-08-22 14:41
@jparinita I'd still suggest preparing a pull request of your changes so far.  It's hard for me to help without some idea what kind of changes need to be made.

**Comment by Nayana-ibm** [comment] 2016-09-22 12:08
@girving 
We have created a PR  #4508 for TensorFlow with big endian changes. 
Could you please have a look? 
Any suggestions would be helpful to fix failing test cases mentioned above .

**Comment by girving** [comment] 2016-09-25 01:22
Cc @aselle for triage, since I'm OOO.

**Comment by Nayana-ibm** [comment] 2016-10-03 05:30
@aselle  Could you please have a look?

**Comment by aselle** [comment] 2016-10-04 00:46
I will look at this first thing tomorrow.

**Comment by aselle** [comment] 2016-10-04 20:53
I looked at the code you changed, and it seems plausible. I also Could you post the test logs from the failing tests. I checked your code, and it looks like what you are doing is plausible. Obvious ways to check for more areas that need changing is grepping for reinterpret_cast's and uses of unions. Also, you might want to try compiling with -fno-strict-aliasing to see if a you are hitting some strict aliasing problems. 

I would like to help more, but I can't reproduce your big endian test, because I have no easy access to a   machine that is big endian. Do you know of an easy environment to build/run big endian code?

**Comment by aselle** [comment] 2016-10-04 21:03
More notes,

Also, in terms of looking at TensorShape which Geoffrey thought might be an issue. It looks like things would mostly be ok. One question is whether your architecture has alignment restrictions for uint16 for uint8 and uint32's. It looks like we aren't doing manipulations as anything but the word size and bytes, which probably is safe. You should insert  
```
static_assert(sizeof(Rep16)==12, "rep16 not 12 bytes");
static_assert(sizeof(Rep32==12), "rep32 not 12 bytes");
```
into `TensorShape` inside `tensor_shape.h`. 

If you have valgrind, you might try running that to see if any buffers are being run-off.

**Comment by Nayana-ibm** [comment] 2016-10-05 12:32
@aselle 
Thank you for your comments.
We are working on your suggestions for big endian.

Do you know of an easy environment to build/run big endian code?
==> Will it be ok if we provide our big endian vm as an extension to TensorFlow CI?

**Comment by aselle** [comment] 2016-10-05 17:51
Can you describe the endian VM? How much slower is it than a native system? Is the emulator and software open source code? I'll look into how hard it would be to put that in our testing infrastructure. @gunan and @martinwicke  can also comment.

**Comment by gunan** [comment] 2016-10-05 18:48
For now, I think it is possible to hook it up to our test infra for daily tests.
But in the near future we will transfer management of our test infra, and in that case we will be quite limited.

**Comment by Nayana-ibm** [comment] 2016-10-07 12:37
@aselle   @gunan 
Can you please provide more details on how the current CI infrastructure is ?
Also, I need below details in order to setup the CI infrastructure on z Systems (big endian):
1. How frequent the CI runs on average?
2. What is the recommended H/W and configuration requirement?
3. Special S/W requirements (if any).

**Comment by Nayana-ibm** [comment] 2016-10-17 11:56
@aselle  @gunan Could you please provide details on the current CI infrastructure ?

**Comment by Nayana-ibm** [comment] 2016-10-17 12:29
We have attached test logs for the below failing tests:
1.  //tensorflow/python:string_to_hash_bucket_op_test 
2. //tensorflow/python:sparse_split_op_test

[string_to_hash_bucket_op_test.log.txt](https://github.com/tensorflow/tensorflow/files/533415/string_to_hash_bucket_op_test.log.txt)

Could you please have a look at logs?

**Comment by gunan** [comment] 2016-10-17 15:33
About our CI:
Looking back at our future plans, we will be retiring our self maintained CI. Therefore, we ourselves would like to avoid adding more machines/setups to that to avoid making our final move more complicated.

Therefore, we decided against running a big endian machine/VM in our CI. I would be happy to help you if you wanted to setup a CI with your machines for this. And we will be happy to accept any patches you might provide.

Currently, our CI runs the scripts here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build
Which should work for you as well.

About the failure you are seeing, I would defer to someone else with more in-depth information about the ops.

**Comment by Nayana-ibm** [comment] 2016-10-18 12:59
@gunan  
We will be glad, if any kind of assistance in maintaining the zSystem VM in the CI by our team can change your decision. 
Please let us know.

**Comment by Nayana-ibm** [comment] 2016-10-18 13:01
@aselle  
We have compiled TensorFlow with -fno-strict-aliasing flag and executed tests however we have observed same failures as before.
We have also checked if our architecture has alignment restrictions for uint8,  uint16 and/or uint32's by adding static_asserts as suggested. However, we didn't find such restrictions ( sizeof Rep16 and Rep32 are 12 bytes)

**Comment by aselle** [comment] 2016-10-19 22:39
Probably the next thing  I would try is debugging further. So the next step is to look at the failing tests in more detail. You can compile in debug mode both on your architecture and a supported architecture and use a debugger to step through the statements until you find a mismatch.

**Comment by Nayana-ibm** [comment] 2016-10-24 12:21
@aselle Thanks for your comments. 
We have built TensorFlow using '-dbg' flag on s390x architecture.  
We are trying to debug the failing test-case using gdb.

Is there any documentation available which we can refer for debugging?

**Comment by Nayana-ibm** [comment] 2016-11-15 10:36
@aselle @girving  
We are currently debugging  `//tensorflow/python:string_to_hash_bucket_op_test` on s390x as well as x86 architecture.
We could see that the mismatch of values is happening in `def create_op() `from `ops.py` .
We could observe that the  op.outputs is populated after  `_add_op(self, op)` is being called:
```
ret = Operation(node_def, self, inputs=inputs, output_types=dtypes,
                    control_inputs=control_inputs, input_types=input_types,
                    original_op=self._default_original_op, op_def=op_def)
    if compute_shapes:
      set_shapes_for_outputs(ret)
-------------> **here,  ret.outputs[0].eval() gives NotFoundError**
    self._add_op(ret)
-------------> **here,  p ret.outputs[0].eval() gives array([3, 5, 7]) ( expected output is array[4,2,8])**

    self._record_op_seen_by_control_dependencies(ret)
```
We tried debugging function _`add_op()` , however couldn't find where the `op.outputs` is getting populated.
Also, we could see` self.lock` being used in this function. Is some other thread populating these values?

**Comment by girving** [comment] 2016-11-15 15:33
@Nayana-ibm I don't know offhand, and my next step at this point would just be adding print statements until I did know.  I'm not sure what you mean by `self.lock`: Python graph construction is not thread safe, and is typically single threaded.

**Comment by Nayana-ibm** [comment] 2016-11-15 17:23
@girving We are using pdb to debug test case and tried to print the op.outputs[0].eval() . The mismatch we could observe after _add_op(self, op) is being called as below:

```
ret = Operation(node_def, self, inputs=inputs, output_types=dtypes,
                    control_inputs=control_inputs, input_types=input_types,
                    original_op=self._default_original_op, op_def=op_def)
    if compute_shapes:
      set_shapes_for_outputs(ret)
-------------> **here,  ret.outputs[0].eval() gives NotFoundError**
    self._add_op(ret)
-------------> **here,  p ret.outputs[0].eval() gives array([3, 5, 7]) ( expected output is array[4,2,8])**
```

About `self.lock`, this is used in the definition of _add_op function( filename: python/framework/ops.py):
```

with self._lock:
      # pylint: disable=protected-access
      if op._id in self._nodes_by_id:
        raise ValueError("cannot add an op with id %d as it already "
                         "exists in the graph" % op._id)
      if op.name in self._nodes_by_name:
        raise ValueError("cannot add op with name %s as that name "
                         "is already used" % op.name)
      self._nodes_by_id[op._id] = op
      self._nodes_by_name[op.name] = op
self._version = max(self._version, op._id)
```
In self.lock is defined in def __init__(self) from Graph object as (filename: python/framework/ops.py):

```
self._lock = threading.Lock()
self._nodes_by_id = dict() # GUARDED_BY(self._lock)
```

**Comment by girving** [comment] 2016-11-15 17:31
Ah, maybe it is thread safe! :)  In any case, I would be surprised if the problem was at the Python level, but I don't think I'll be able to help much in debugging this remotely since I can't tinker.

**Comment by Nayana-ibm** [comment] 2016-12-01 12:26
@mrry Can you please have a look at this issue and share your views?

**Comment by mrry** [comment] 2016-12-01 15:59
@Nayana-ibm I agree with @girving: The problem almost certainly isn't in Python (unless there's an endianness bug in the Python runtime itself), but is more likely to be in either the OpKernel for the op that is failing or its C++ shape function. I'd suggest using gdb to step through these functions and see where they go wrong.

**Comment by Nayana-ibm** [comment] 2017-02-01 11:31
https://github.com/tensorflow/tensorflow/pull/6686
This test is now passing on big endian system. Fixed through PR #6686

**Comment by Nayana-ibm** [comment] 2017-02-01 11:32
@girving @gunan 
To extend my post on CI:
We would like to know that how TensorFlow CI can be extended to support z system. 
Please let us know what support will be required from IBM side. We are aware on the H/w support. 
We can provide s390x machines on which we will setup Jenkins slave node to build TensorFlow. T
he present Jenkins master will manage this node and post the s390x build results to GitHub.

Please let us know your comments.

**Comment by gunan** [comment] 2017-02-01 23:44
@Nayana-ibm As far as support goes, I cannot really promise we can fully support ourselves as we do not have big endian machines. So we cannot give first class support for this platform.

But I can help setup our jenkins to run all TF tests on your machines periodically. When there are failures, most probably we will escalate the issues to you, if they seem to be specific to your machines, and we will be available to consult resolving issues. You will retain ownership of these machines. I will help you setup all our dependencies on them, and as long as your machine is healthy and up, our jenkins master will schedule tests on your machine.

How does this sound?

**Comment by Nayana-ibm** [comment] 2017-02-03 12:32
@gunan 
This sounds good to us.

As per my understanding,  we will provide you a Jenkins slave node which will be added under your master. Correct? Also, wanted to know how the build results will be shared with us? through GitHub issue? Please let me know.

**Comment by gunan** [comment] 2017-02-07 22:56
Sorry for the delay, my inbox is going crazy these days.
Yes, you will have the machine maintained by you, and I will provide you instructions to setup the machine for tensorflow builds. The build results will be visible through ci.tensorflow.org. You will have access to all build logs through ci.tensorflow.org.
I can even set you up with access to start and stop the specific build for s390x.

**Comment by Nayana-ibm** [comment] 2017-02-09 10:45
@gunan 
Thanks for your support.
Could you please let me know what's the recommended H/W configuration required? and 
 S/W requirements (if any).

**Comment by gunan** [comment] 2017-02-14 18:44
Sorry for the delay, looks like I wrote up the response but forgot to send.
For H/W requirements, completely up to you. Obviously, the beefier the machine is, the quicker code is tested. But I wont block code submissions on this so we can tolerate some delays here. 

S/W requirements, you will need all TF dependencies on your machine installed. We usually run all our tests in a docker container, but in this case I dont think we need docker.

Our jenkins will simply execute:
```
git checkout <commit>
<set some environment variables>
yes "" | ./configure
bazel test tensorflow/...
```

**Comment by Nayana-ibm** [comment] 2017-02-17 15:02
Thank you for your inputs.
We are setting up machine with all TF dependencies.

I could see Tensorflow supports Ubuntu 14.04 ( Ref: https://www.tensorflow.org/install/install_linux)
however we are planning to build the TensorFlow on RHEL and Ubuntu on s3890x platform.

**Comment by gunan** [comment] 2017-02-22 05:43
I just verified that with bazel I can build on CentOS 7 without any issues.
I expect a similar experience with RHEL.

However, we do not have official RedHat support, so we will possibly redirect Redhat specific build issues to you in this build.

**Comment by Nayana-ibm** [comment] 2017-03-21 12:46
@gunan 
We have procured the s390x vms with Ubuntu 16.04 distribution. 
Also, installed the dependencies like bazel, python-setuptools etc. 
Please let me know the procedure to add those vm's under TensorFlow CI .

**Comment by gunan** [comment] 2017-03-21 19:22
Great!
Could you email me? my github username @ companyname is the address
We can continue the conversation there.

**Comment by Nayana-ibm** [comment] 2017-03-23 09:23
@gunan 
Will you please email me on nthorat@us.ibm.com.

**Comment by Nayana-ibm** [comment] 2017-04-25 09:13
Closing this issue as it was originally opened for test case failure.

Also, we have completed Tensorflow CI for s390x. 
@gunan Thank you for your help and support.

**Closed** 2017-04-26 04:21 UTC
Labels: stat:awaiting tensorflower, type:bug/performance
