### ISSUE TITLE
//tensorflow/python:nn_test fails with AssertionError

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#16540] opened 2018-01-29 12:50 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 s390x
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: bazel test -c opt //tensorflow/python:nn_test 

### Describe the problem
While running `nn_test`, 2 sub tests (`testOutput2DInput01`,`testOutput4DInput123`), fail on s390x with : 
```
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0.0001
None
(mismatch 100.0%)
 x: array([[ 0.00111]], dtype=float32)
 y: array([[ 0.000837]])
```

The test passes if the [tolerance](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/ops/nn_test.py#L865) is slightly increased:
```
-  def doOutputTest(self, input_shape, moments_axes, tol=1e-4,
+  def doOutputTest(self, input_shape, moments_axes, tol=4e-4,
```

Is it ok to create a PR with this change? Could you please share your thoughts on this.

### Source code / logs
======================================================================
```
FAIL: testOutput2DInput01 (__main__.MomentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py", line 911, in testOutput2DInput01
    self.doOutputTest((10, 300), (0, 1))
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py", line 896, in doOutputTest
    self.assertAllClose(variance, expected_var, rtol=tol, atol=tol)
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 972, in assertAllClose
    self._assertArrayLikeAllClose(a, b, rtol=rtol, atol=atol)
  File "/home/test/.cache/bazel/_bazel_test/774d974934abfb88e6e5d6a13042805c/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/nn_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 942, in _assertArrayLikeAllClose
    np.testing.assert_allclose(a, b, rtol=rtol, atol=atol, err_msg=msg)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0.0001
None
(mismatch 100.0%)
 x: array([[ 0.00111]], dtype=float32)
 y: array([[ 0.000837]])

```

**Comment by drpngx** [comment] 2018-01-30 02:33
@ebrevdo for context I think that s390x is the big endian system.

That seems like a large change, are you sure that this is working correctly?

**Comment by ebrevdo** [comment] 2018-01-30 02:45
The problem is either with `reduce_mean` or `squared_difference`.  Could you identify within which op you get the precision loss?  My money's on reduce_mean but who knows if there's some issue with vectorisation primitives in Eigen's scalar_square or scalar_difference implementations.

**Comment by namrata-ibm** [comment] 2018-01-30 13:10
@drpngx , @ebrevdo , Thank you for your feedback.
After doing some more analysis, found that the test fails, only for `mu` = `1e3` [here](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/ops/nn_test.py#L867) and passes for other cases.
After printing actual and expected mean and variance values, found below for failing case:
```
mean :  [[ 1000.03216553]]
expected_mean:  [[ 1000.04957838]]
variance :  [[ 0.00113162]]
expected_var :  [[ 0.0008284]]
```
So seems like some issue with variance calculation.
Further printed [squared_difference](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/ops/nn_impl.py#L621) as `print(" squared diff: ", math_ops.squared_difference(y, array_ops.stop_gradient(mean)).eval())` and found following:

```
s390x:
 squared diff:  [[  9.41790640e-05   6.66562468e-04   1.11056864e-03 ...,   2.74242461e-03
    2.63482705e-03   1.27498060e-04]
 [  2.23173201e-03   7.84847885e-04   4.25592065e-04 ...,   9.77665186e-05
    1.73807144e-04   2.11015344e-04]
 [  2.20872462e-05   2.21446529e-03   6.47787005e-04 ...,   1.97067857e-04
    7.57727772e-04   1.22044235e-04]
 ...,
 [  6.39297068e-05   3.52684036e-03   1.90446153e-03 ...,   1.26184523e-03
    1.90272927e-04   2.27228180e-03]
 [  8.02040100e-04   5.96046448e-08   4.36128676e-03 ...,   4.40835953e-04
    4.43402678e-04   2.33084336e-03]
 [  6.29279763e-04   7.04918057e-04   9.35051590e-04 ...,   4.23325598e-03
    1.49011612e-06   6.29574060e-05]]
mean :  [[ 1000.03216553]]
expected_mean:  [[ 1000.04957838]]
variance :  [[ 0.00113162]]
expected_var :  [[ 0.0008284]]

while on x86:
 squared diff:  [[  4.50760126e-05   8.83489847e-05   2.85837799e-04 ...,   1.29238144e-03
    1.21885538e-03   2.62856483e-05]
 [  9.50042158e-04   1.97434425e-03   1.37257949e-03 ...,   4.26508486e-05
    1.04643404e-05   9.57582146e-04]
 [  4.45976853e-04   9.38788056e-04   1.75310671e-03 ...,   9.27601010e-04
    1.93119049e-03   7.54371285e-04]
 ...,
 [  5.96046448e-04   1.84631348e-03   7.41019845e-04 ...,   3.64962965e-04
    9.12789255e-04   9.76562500e-04]
 [  2.00155750e-03   2.77642161e-04   2.46230140e-03 ...,   2.09547579e-05
    1.40441954e-03   1.01508200e-03]
 [  1.72257423e-03   1.02654099e-04   2.00510025e-04 ...,   2.36633793e-03
    3.11139971e-04   7.19763339e-05]]
mean :  [[ 1000.04858398]]
expected_mean:  [[ 1000.04957838]]
variance :  [[ 0.00082939]]
expected_var :  [[ 0.0008284]]

```

Do you think this variation can cause precision loss?

**Comment by namrata-ibm** [comment] 2018-01-31 12:58
@drpngx , @ebrevdo , Found the cause of failure of this test.
Looks like the precision is lost [here](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/ops/nn_test.py#L878).

When I changed the dtype from float32 to float64 as below, the test passed.
```
               inputs = constant_op.constant(
-                  input_values, shape=input_shape, dtype=dtypes.float32)
+                  input_values, shape=input_shape, dtype=dtypes.float64)
```

I also tried the same on x86, and it's still passing.

Is it OK to create a PR with this change?

**Comment by namrata-ibm** [comment] 2018-02-04 11:42
@drpngx , @ebrevdo, Could you please have a look?

**Comment by namrata-ibm** [comment] 2018-02-19 12:52
Printing few data types as below:
```
(Pdb) p input_values.dtype
dtype('float64')
```
whereas,
```
(Pdb) p inputs.dtype
tf.float32
```
This behavior is similar to earlier issues observed on s390x.
@mrry, Could you please provide your feedback?

**Comment by mrry** [comment] 2018-02-19 15:53
Can the problem be solved by setting an explicit `dtype` for `np.random.rand()` on this line?

https://github.com/tensorflow/tensorflow/blob/8ee732dae6202eac9c9ef1f14a94ba96fde677ce/tensorflow/python/ops/nn_test.py#L951

I suspect we'd like to keep test coverage for the moments-with-single-precision case, since AFAIK that's the one that currently gets more use. However, looping over `[np.float32, np.float64]` might make sense for these tests (assuming the tolerance can be set appropriately).

**Comment by namrata-ibm** [comment] 2018-02-23 09:33
@mrry, it seems like `np.random.rand()` doesn't allow setting dtype yet, as seen [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html). 

Just tried below diff for looping over dtypes and it works fine:
`//tensorflow/python:nn_test  -------                     PASSED in 22.6s`:
```
@@ -867,6 +866,7 @@ class MomentsTest(test_lib.TestCase):
     for mu in [0.0, 1.0, 1e3]:
       for sigma in [1.0, 0.1]:
         for keep_dims in [True, False]:
+         for dtype in [dtypes.float32, dtypes.float64]:
             input_values = np.random.rand(*input_shape) * sigma + mu
             expected_mean = np.mean(
                 input_values, axis=moments_axes, keepdims=keep_dims)
@@ -875,7 +875,7 @@ class MomentsTest(test_lib.TestCase):
             with ops.Graph().as_default() as g:
               with self.test_session(graph=g) as sess:
                 inputs = constant_op.constant(
-                  input_values, shape=input_shape, dtype=dtypes.float32)
+                    input_values, shape=input_shape, dtype=dtype)
                 mean, variance = nn_impl.moments(
                     inputs, moments_axes, keep_dims=keep_dims)

@@ -892,8 +892,12 @@ class MomentsTest(test_lib.TestCase):
               # Make sure that there are no NaNs
                 self.assertFalse(np.isnan(mean).any())
                 self.assertFalse(np.isnan(variance).any())
+               if dtype == 'dtypes.float64':
                  self.assertAllClose(mean, expected_mean, rtol=tol, atol=tol)
                   self.assertAllClose(variance, expected_var, rtol=tol, atol=tol)
+                else:
+                  self.assertAllClose(mean, expected_mean, rtol=4e-4, atol=4e-4)
+                  self.assertAllClose(variance, expected_var, rtol=4e-4, atol=4e-4)
```
What would be the right approach?

**Comment by tensorflowbutler** [comment] 2018-03-10 13:11
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:33
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-09 12:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-24 18:39
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:04
Nagging TensorFlower: It has been 30 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:02
Nagging TensorFlower: It has been 46 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:51
Nagging TensorFlower: It has been 61 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging TensorFlower: It has been 76 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging TensorFlower: It has been 91 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:00
Nagging TensorFlower: It has been 106 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:03
Nagging TensorFlower: It has been 121 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by drpngx** [comment] 2018-08-09 23:49
Is that still an issue with the latest code?

**Comment by duane-ibm** [comment] 2018-08-13 07:33
@drpngx the issue still exists on v1.10.0.

**Comment by drpngx** [comment] 2018-08-13 22:43
Following up on @mrry's idea, could we try maybe `np.random.rand(..).astype(np.float32)`?

**Comment by duane-ibm** [comment] 2018-08-14 09:26
I tried the below:
```
--- a/tensorflow/python/ops/nn_test.py
+++ b/tensorflow/python/ops/nn_test.py
@@ -1009,7 +1009,7 @@ class MomentsTest(test_lib.TestCase):
     for mu in [0.0, 1.0, 1e3]:
       for sigma in [1.0, 0.1]:
         for keep_dims in [True, False]:
-          input_values = np.random.rand(*input_shape) * sigma + mu
+          input_values = np.random.rand(*input_shape).astype(np.float32) * sigma + mu
           expected_mean = np.mean(
               input_values, axis=moments_axes, keepdims=keep_dims)
           expected_var = np.var(
```
The same issue still exists.

**Comment by harshini-gadige** [comment] 2018-10-24 21:13
@drpngx  @mrry  - Hi, could you please look into this issue.

@namrata-ibm  @duane-ibm  -  Hi, are you still having this issue in the latest tensorflow versions ? Feel free to close if this doesn't persist. Also, appreciate if you create a new issue with the latest details(if the issue persists). Thanks !

**Comment by mrry** [comment] 2018-10-24 21:44
@harshini-gadige I don't have access to an s390x machine to reproduce this problem, which is why this issue was marked "community support".

**Comment by kbhute-ibm** [comment] 2019-02-26 13:44
@hgadig Hi, yes we are still facing this issue for version 1.12.0 with same details.

**Comment by kbhute-ibm** [comment] 2019-06-27 10:43
This test passes in version 1.13.1. We may close this issue. Thanks for the support.

**Closed** 2019-09-10 10:22 UTC
Labels: stat:community support
