### ISSUE TITLE
Horovod fails to train Keras Preprocessing IntegerLookup Layer

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#43834] opened 2020-10-07 02:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7.6
- GPU model and memory: K80, 15 GB of RAM

**Describe the current behavior**
In TensorFlow 2.3, Keras Preprocessing Layers were released.  Some of these cause Horovod to fail.  It is not clear if this is a Horovod or TensorFlow issue.

The model that fails is:
```python3
def make_model():
  import tensorflow.keras as keras
  
  vocabulary = range(1, 11)
  return keras.Sequential([
    keras.layers.experimental.preprocessing.IntegerLookup(vocabulary=vocabulary),
    keras.layers.Embedding(len(vocabulary) + 2, 8, input_length=1),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])
```

When run, the error that is reported is:
```pycon
[1,0]<stderr>:  File "/databricks/python/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
[1,0]<stderr>:    raise e.ag_error_metadata.to_exception(e)
[1,0]<stderr>:AttributeError: in user code:
[1,0]<stderr>:
[1,0]<stderr>:    /databricks/python/lib/python3.7/site-packages/horovod/tensorflow/__init__.py:138 broadcast_group  *
[1,0]<stderr>:        var.assign(broadcast(var, root_rank))
[1,0]<stderr>:
[1,0]<stderr>:    AttributeError: 'TrackableWeightHandler' object has no attribute 'assign'
```

After fitting the same model locally, we can look at the vairables and see:
```python
for x in fitted_model.variables:
  print(type(x))
```
```pycon
<class 'tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler'>
<class 'tensorflow.python.eager.def_function.UnliftedInitializerVariable'>
<class 'tensorflow.python.eager.def_function.UnliftedInitializerVariable'>
<class 'tensorflow.python.eager.def_function.UnliftedInitializerVariable'>
```

`TrackableWeightHandler` appears to not support the interface of https://www.tensorflow.org/api_docs/python/tf/Variable - in particular, the `assign` method.

Might be similar to https://github.com/keras-team/autokeras/issues/1225 .

**Describe the expected behavior**
Horovod should be able to train with Keras Preprocessing Layers.

I also expect all objects returned from `keras.Model.variables` to be `tf.Variables`.  I don't know if that expectation is correct.  The API is vague on that part.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
import horovod.tensorflow.keras as hvd

from sparkdl import HorovodRunner

def make_dataset():
  import tensorflow as tf
  from random import randrange

  dataset = tf.data.Dataset.from_tensor_slices(
    ([randrange(1, 11) for p in range(0, 10000)], [randrange(0,2) for p in range(0, 10000)])
  )
  dataset = dataset.repeat().batch(128)
  return dataset

def train():
  import tensorflow as tf
  import tensorflow.keras as keras
  import horovod.tensorflow.keras as hvd
  
  # Initialize Horovod
  hvd.init()

  # Pin GPU to be used to process local rank (one GPU per process)
  gpus = tf.config.experimental.list_physical_devices('GPU')
  for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  if gpus:
      tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

  # Build model and dataset
  dataset = make_dataset()
  model = make_model()
  # Horovod: adjust learning rate based on number of GPUs.
  scaled_lr = 0.001 * hvd.size()
  opt = tf.optimizers.Adam(scaled_lr)

  # Horovod: add Horovod DistributedOptimizer.
  opt = hvd.DistributedOptimizer(opt)

  # Horovod: Specify `experimental_run_tf_function=False` to ensure TensorFlow
  # uses hvd.DistributedOptimizer() to compute gradients.
  model.compile(
    loss=tf.losses.BinaryCrossentropy(from_logits=True),
    optimizer=opt,
    metrics=['AUC'],
    experimental_run_tf_function=False
  )

  callbacks = [
      # Horovod: broadcast initial variable states from rank 0 to all other processes.
      # This is necessary to ensure consistent initialization of all workers when
      # training is started with random weights or restored from a checkpoint.
      hvd.callbacks.BroadcastGlobalVariablesCallback(0),
  ]

  model.fit(
    dataset,
    steps_per_epoch=500 // hvd.size(),
    callbacks=callbacks,
    epochs=2,
    verbose=1 if hvd.rank() == 0 else 0
  )
  
  return model

hr = HorovodRunner(np=-1)
fitted_model = hr.run(train)

def train_local():
  # Build model and dataset
  dataset = make_dataset()
  model = make_model()
  
  opt = tf.optimizers.Adam(0.001)
  model.compile(
    loss=tf.losses.BinaryCrossentropy(from_logits=True),
    optimizer=opt,
    metrics=['AUC'],
    experimental_run_tf_function=False
  )

  model.fit(
    dataset,
    steps_per_epoch=100,
    epochs=2,
    verbose=1
  )
  
  return model
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jeisinge** [comment] 2020-10-07 02:06
The potential Horovod defect is available at https://github.com/horovod/horovod/issues/2356 .

**Comment by Saduf2019** [comment] 2020-10-08 05:20
@jeisinge 
I ran the code shared and face dependency issues , please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f6c835f03d55d913d0df6c04a886d93d/untitled426.ipynb), if possible share a colab gist with the error reported.

**Comment by jeisinge** [comment] 2020-10-08 14:00
Thanks for attempting to reproduce.  Databricks allows for running Horovod from the notebook environment.  However, I have been unable to accomplish this in Colab.

The good news is that on the [other ticket](https://github.com/horovod/horovod/issues/2356), @tgaddair has been reproduce locally.

@tgaddair, do you have a local script/gist that can be posted?

**Comment by tgaddair** [comment] 2020-10-08 14:06
Yes, running this script with a single process was sufficient to repro for me:

```
opt = tf.keras.optimizers.Adam(lr=0.1)
        opt = hvd.DistributedOptimizer(opt)

        vocabulary = range(1, 11)
        model = keras.Sequential([
            tf.keras.layers.experimental.preprocessing.IntegerLookup(vocabulary=vocabulary),
            tf.keras.layers.Embedding(len(vocabulary) + 2, 8, input_length=1),
            tf.keras.layers.Dense(1, activation='sigmoid')
        ])

        model.compile(loss=tf.losses.BinaryCrossentropy(from_logits=True),
                      optimizer=opt,
                      metrics=['AUC'],
                      experimental_run_tf_function=False)

        dataset = tf.data.Dataset.from_tensor_slices(
            ([randrange(1, 11) for _ in range(0, 100)], [randrange(0, 2) for _ in range(0, 100)])
        )
        dataset = dataset.repeat().batch(128)

        # No assertions, we just need to verify that it doesn't hang or error
        callbacks = [hvd.callbacks.BroadcastGlobalVariablesCallback(0)]
        model.fit(dataset,
                  steps_per_epoch=10,
                  callbacks=callbacks,
                  epochs=1)
```

As I mentioned in the other ticket, the issue is pretty clear.  The `model.variables` is not returning a list of variables here. Instead, one of the variables is this `TrackableWeightHandler`, which does not adhere to the variable interface. As such, we cannot broadcast it and we cannot assign weights to it.

We need to determine if this is intended behavior from the Keras team, and if so, how we can workaround this.  But ideally, Keras would not be putting objects that do not adhere to the variable interface in variables, as special-casing is not a good long term solution for consumers of the API like Horovod.

**Comment by tanzhenyu** [comment] 2020-10-10 20:30
This is a known issue. However what are the use cases of getting `model.variables` instead of `model.trainable_variables` -- I fail to see the reason of updating non trainable variables during training runtime.

**Comment by rafaelbarreto87** [comment] 2020-10-27 05:01
Apparently this breach in the variable interface also breaks `tf.keras.callbacks.TensorBoard`: https://github.com/tensorflow/tensorflow/blob/b8f0d8c4186db00e45d9b4b9b88f6fedf4cf9d2e/tensorflow/python/keras/callbacks.py#L2397. When training a model using `StringLookup` and the `TensorBoard` callback, I get the error `AttributeError: 'TrackableWeightHandler' object has no attribute 'name'` because of the presence of `TrackableWeightHandler` in the model `.variables`.

**Comment by tgaddair** [comment] 2020-10-27 14:03
Hey @tanzhenyu, the motivation is to sync variables across multiple workers to ensure consistency during parallel training.  For example, you may have non-trainable variables initialized randomly that need to have the same values on every worker to prevent divergence.  Does that makes sense?

**Comment by jeisinge** [comment] 2021-05-21 15:38
FYI - I just tested again with TensorFlow 2.4.1.  This error is still happening.

Any update?  Any work around?

**Comment by jeisinge** [comment] 2021-05-21 22:49
FYI - same issue with TF 2.3 -> TF 2.5.  I created a gist for TF 2.5: https://colab.research.google.com/gist/jeisinge/1fe6b14ea960538ce0f14fa6a70ac09e/keraspreprocessing-horovod.ipynb

**Comment by jeisinge** [comment] 2021-06-05 14:47
Oops!  I just went back to test and I realized the gist I posted appears to be an old version.  I just recreated with https://colab.research.google.com/gist/jeisinge/80fd4e4a4af0c2287072714e7edbd43c/keras_preprocessing-horovod.ipynb for a simple test on the latest released TensorFlow.

Also, `tf.keras.layers.experimental.preprocessing.TextVectorization` fails for the same reason.

**Comment by Saduf2019** [comment] 2021-08-11 14:16
@jeisinge 
Please confirm if the issue is resolved as the pr is merged.
Also, It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version.

**Comment by jeisinge** [comment] 2021-08-11 16:48
I just tested with rc0 and rc2.  It works.

Also, I created I https://colab.research.google.com/gist/jeisinge/10629c26b078ad9f51987cb7acd3ca9a/keras_preprocessing-horovod.ipynb to test for histograms on TensorBoard that had a similar issue.  Everything appears to work!

https://github.com/tensorflow/tensorflow/issues/41244 might be fixed as well?!

**Comment by Saduf2019** [comment] 2021-08-11 17:12
@jeisinge 
Please move this to closed status as resolved.

**Closed** 2021-08-11 18:38 UTC
Labels: stat:awaiting response, type:bug, comp:keras, TF 2.3

**Comment by MrAta** [comment] 2022-08-08 17:04
Hi @Saduf2019 @jeisinge in what tf version this issue is being resolved? would you please point me to the commit that resolves this? thanks!

**Comment by jeisinge** [comment] 2022-08-08 18:33
`tensorflow==2.6.0rc2`
