### ISSUE TITLE
Problem installing tensorflow-gpu  (dll load faliure)

### ISSUE THREAD

**Issue by SunnyNagam** [tensorflow/tensorflow#23961] opened 2018-11-26 00:42 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):
- TensorFlow version: tensorflow-1.12.0 (installed via pip3)
- Python version: python 3.6.7
- CUDA/cuDNN version: CUDA==10.0.130 cuDNN==7.4.1
- GPU model and memory: NVIDIA GTX 1050 Ti with Max-Q Design

**Provide the exact sequence of commands / steps that you executed before running into the problem**
After starting python 3.6 in cmd and trying to execute `import tensorflow` I get the following stack trace:

'>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.'

I have tried installing the CUDA toolkit and cuDNN and adding to my PATH. Here is my current PATH: 

'PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;C:\cuda\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\;C:\Users\Sunny Nagam\AppData\Local\Microsoft\WindowsApps;'

I'm unsure if this infromation is helpful but my \cuda\bin contains "cudnn_64_7.dll" and my CUDA\v10.0\bin contains "cudart64_100.dll"

**Comment by epaqu** [comment] 2018-11-26 03:06
I'm experiencing the same problem.

System information
- OS Platform and Distribution: Windows 10 Pro 64bit (Build 17134)
- TensorFlow version: 1.12.0
- TensorFlow-GPU version: 1.12.0
- Python version: 3.6.7
- CUDA version: 10.0.130
- cuDNN version: 7.4.1
- GPU model and memory: GTX 1080 (16243MB)

Tried TensorFlow 1.10.0, but it didn't help.
According to https://www.tensorflow.org/install/source_windows, TensorFlow 1.12.0 should work fine with Python 3.6, Microsoft Visual C++ 2015 Update 3, cuDNN 7 and CUDA 9 on Windows 10.
I will try this configuration tonight and let you know.

**Comment by SunnyNagam** [comment] 2018-11-26 03:58
Hmm maybe I'll try downgrading to CUDA 9

**Comment by SunnyNagam** [comment] 2018-11-26 04:31
Just tried getting CUDA 9 and replacing all the CUDA 10 paths in my PATH with the corresponding CUDA 9 path. Still no luck.

My path now is: "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\CUPTI\libx64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Sunny Nagam\AppData\Local\Programs\Python\Python36\;C:\Users\Sunny Nagam\AppData\Local\Microsoft\WindowsApps;"

**Comment by ymodak** [comment] 2018-11-27 01:53
This is issue is a duplicate of #23726

**Comment by SunnyNagam** [comment] 2018-11-27 21:16
Downgrading to CUDA==10 and tensorflow-gpu==1.10 has fixed my problem. Thank you for the help!

**Closed** 2018-11-27 21:16 UTC
Labels: stat:awaiting response, type:build/install

**Comment by ymodak** [comment] 2018-11-27 23:36
You mean downgrading to CUDA 9.0 right?

**Comment by SunnyNagam** [comment] 2018-11-28 01:01
Yes i did sorry

**Comment by epaqu** [comment] 2018-11-28 07:52
Can confirm. Tensorflow-GPU 1.10 with CUDA 9.0 works for me as well.

**Comment by ymodak** [comment] 2018-12-14 23:44
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by if316030** [comment] 2019-05-25 06:11
I have same problem.
How to downgrade Tensorflow-GPU and CUDA ?
thankyou

**Comment by JuanHauara** [comment] 2019-09-03 05:34
I'm too have the same porblem.

System information:
OS Platform and Distribution: Windows 10
TensorFlow version: tensorflow-1.14.0 (installed via pip3)
Python version: python 3.7.4
CUDA/cuDNN version: CUDA==10.1.0 cuDNN==7.6
GPU model and memory: NVIDIA GTX 1050 3GB

**Comment by saga95** [comment] 2019-09-17 02:43
> Can confirm. Tensorflow-GPU 1.10 with CUDA 9.0 works for me as well.

C:\Users\Saagaa>pip install tensorflow-gpu==1.1
Collecting tensorflow-gpu==1.1
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.1 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1)
ERROR: No matching distribution found for tensorflow-gpu==1.1

what version did you use?

**Comment by arifwaqas** [comment] 2020-01-04 22:34
> > Can confirm. Tensorflow-GPU 1.10 with CUDA 9.0 works for me as well.
> 
> C:\Users\Saagaa>pip install tensorflow-gpu==1.1
> Collecting tensorflow-gpu==1.1
> ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.1 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1)
> ERROR: No matching distribution found for tensorflow-gpu==1.1
> 
> what version did you use?

The reason behind it is maybe it has been discontinued, the post is from more than 8 months older than yours
