### ISSUE TITLE
upgraded tensorflow to use GPU - she's a no worky anymore

### ISSUE THREAD

**Issue by Moldy01** [tensorflow/tensorflow#15050] opened 2017-12-01 21:53 UTC
Script was running fine (if a bit slow).  Decided it was  time to upgrade to the gpu version of tensorflow.  From what I can tell, for some reason it is looking for libcublas.so.8.0.  Since I just upgraded to the latest cuda libs, I'm running libcublas.so.9.0.176  (found in /usr/local/cuda-9.0/lib64/) and, yes, that is in my path (first item, by the way).  

Using TensorFlow backend.
```
Traceback (most recent call last):
  File "/home/mitch/MitchEng/data_Analytics/conv_radar.py", line 3, in <module>
    from keras.models import Sequential
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/mitch/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
```
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tensorflowbutler** [comment] 2017-12-02 06:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Moldy01** [comment] 2017-12-04 21:57
Sorry,  Didn't see a template.  I'll work from your list

Have I written custom code ?  Of course, But the code from above (causing the issue) is copy/paste from Keras.  Just trying to get GPU version up and running.
OS Platform and Distibution - Linux Ubuntu 1604
TensorFlow installed from - several places, most recently from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl (that's the one above)
TensorFlow version - 1.4
Cuda/cuDNN version - cuda v 9.0/cuDNN version 7.0.4
GPU model and memory - nvidia GeForce GTX 960M
Exact command to reproduce - from keras.models import Sequential

**Comment by PhilJd** [comment] 2017-12-05 08:30
Hi,
the prebuilt binaries are using cuda 8.0 and cudnn 6.0 as far as I know. That means you either need to build tensorflow from source or you try to create a symlink pointing from  libcublas.so.9.0 to  libcublas.so.8.0. However, with the latter you might run into problems later on. Another possibility is to download cuda/cudnn into some local folder and set the LD_LIBRARY_PATH to first search in this folder.

**Comment by Moldy01** [comment] 2017-12-05 23:02
Phil,

Thanks, that's pretty much what I was thinking, except I was hoping to hear that you were re-compiling the prebuilt binaries so that they would include "Anything less than ...".

I'm relatively new to Python, so I don't know whether that is even doable, unless they're actually gcc compiled libraries, in which case, it should be doable.  However, I was able to get it going by maneuvering my environment around (re-installing etc...).

FYI, pointing cudnn 6 at cudnn 7 targets didn't work.  Started to run, but tailed off to the infamous "la la land".  I haven't tried to create the old update-alternatives solution as yet.

Thanks for writing back though.  It did fortify my theories.   I may just bite the bullet and drag down the build env so I can build from source and then it will work with my system as a given.

have a GREAT day,

Mitch
________________________________

**Comment by PhilJd** [comment] 2017-12-06 08:17
Hi Moldy,
The tensorflow core is written in cpp so tf is gcc compiled. However, I'm don't quite get what you mean with re-compiling, as this is not possible from the given binar and you'd need the source code anyway.

However, you could still try the last option I mentioned, to download cuda and cudnn manually and store them locally.
That is:
1. create a folder /home/USERNAME/lib/
2. download the cuda 8 installer and install it to  /home/USERNAME/lib/cuda-8.0
3. download cudnn6 and extract the compressed file. There you'll find a folder structure that resembles the one found in /home/USERNAME/lib/cuda-8.0. Copy the files to cuda-8.0, keeping the directory structure.
4. Prepend the lib folder to your LD_LIBRARY_PATH, i.e.
` export LD_LIBRARY_PATH=/home/USERNAME/lib/cuda-8.0/lib64:$LD_LIBRARY_PATH`. Or even better, put this line into your `.bashrc` so you don't have to repeat step 4 every time you want to use tensorflow.

Cheers,
Phil

**Comment by Moldy01** [comment] 2017-12-06 16:41
Phil,

Thanks for the info.  Sometimes I wish I had the time to contribute.  As for the "re-compiling" to which you refer.  I've seen it done before, however, I'm afraid I don't remember the technique used.  It is possible for the end binary to accept "either" xxx.so.8, xxx.so.7, xxx.so.6, etc.   The reason for my preface, is that your next question would undoubtedly be to query me for the technique, which as I write this, I'm afraid is eluding my memory searches at the moment.

That being said, I have to admit that the vast majority of my software experience comes on the Windows platforms, but if you think about it, if it were NOT possible, then how do windows apps cross so many versions??

As for using the last method: I'm afraid that I work with several other "software creators" (engineers, algorithm designers, programmers, etc...).  So, in order for me to pass along a "setup" for each to install so that their contributions will work with what I check in, implies that it is somewhat more generic.  I must put together a "process" for including my efforts to their own environments, which will include the end product as well (it is an embedded application).

I can (and have done that), I was merely passing along the desire to utilize the latest available tensorflow WITH the latest available Cuda, cuDNN, etc...  We, attempt to make our embedded environment as recent as possible at the time of the first production unit.  Upgrades become difficult as the number of purchased units increases.

And, yes, I have already started the process to set up my environment to build tensorflow from scratch, but will also admit that this is doubtful to be the best answer, as it then requires us (my company - well me right now) to do my own rebuilds each time something else change.

Thanks again for you willingness to follow up and for your good suggestions,

Mitch
________________________________

**Comment by drpngx** [comment] 2017-12-09 01:40
So, reading the thread, it looks like the root cause is the wrong cublas version. I'm closing this, feel free to reopen if you think it's a bug in tensorflow.

**Closed by drpngx** 2017-12-09 01:40 UTC

**Comment by Moldy01** [comment] 2017-12-10 04:21
Phil,

I'm sorry.  I guess I was not all that clear.  I was not reporting a bug, it should have been thought of as an enhancement request.  Close if you like, I've got my work around, and am even considering setting up to build my own.  It is just nicer to be able to download an executable, and not bother.

thanks for your attentive responses and suggestions,

Mitch
________________________________
