### ISSUE TITLE
pip install tensorflow-gpu==2.1.0rc2 failed!

### ISSUE THREAD

**Issue by OoiSC** [tensorflow/tensorflow#35381] opened 2019-12-24 07:09 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0rc2
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia MX150

**Describe the problem**
The tensorflow-gpu-estimator error message occurs regardless of whether I install tensorflow-estimator first before tensorflow-gpu-2.1.0rc2 or with no installation of tensorflow-estimator.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
C:\>pip install tensorflow-estimator
Collecting tensorflow-estimator
  Using cached https://files.pythonhosted.org/packages/18/90/b77c328a1304437ab1310b463e533fa7689f4bfc41549593056d812fab8e/tensorflow_estimator-2.1.0-py2.py3-none-any.whl
Installing collected packages: tensorflow-estimator
Successfully installed tensorflow-estimator-2.1.0

C:\>pip install tensorflow-gpu==2.1.0rc2
Collecting tensorflow-gpu==2.1.0rc2
  Using cached https://files.pythonhosted.org/packages/c5/5d/4d1cb80c38b987a8d0cace1d22a366c843af8966352bcc178450530e0a4f/tensorflow_gpu-2.1.0rc2-cp37-cp37m-win_amd64.whl
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\python37-64\lib\site-packages (from tensorflow-gpu==2.1.0rc2) (1.1.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\python37-64\lib\site-packages (from tensorflow-gpu==2.1.0rc2) (1.17.2+mkl)
Requirement already satisfied: protobuf>=3.8.0 in c:\python37-64\lib\site-packages (from tensorflow-gpu==2.1.0rc2) (3.10.0)
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu-estimator<2.2.0,>=2.1.0rc0 (from tensorflow-gpu==2.1.0rc2) (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu-estimator<2.2.0,>=2.1.0rc0 (from tensorflow-gpu==2.1.0rc2)
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Following is my pip list output before I start installing tensorflow-estimator and tensorflow-gpu-2.1.0rc2.
```
C:\>pip list
Package                 Version
-----------              -----------
absl-py                 0.8.1
appdirs                 1.4.3
astor                   0.8.0
autopep8                1.4.4
cachetools              3.1.1
cairocffi               1.1.0
certifi                 2019.9.11
cffi                    1.13.1
chardet                 3.0.4
Click                   7.0
cycler                  0.10.0
decorator               4.4.1
dlib                    19.17.0
editdistance            0.5.3
entrypoints             0.3
essential-generators    0.9.2
face-recognition        1.2.3
face-recognition-models 0.3.0
flake8                  3.7.9
gast                    0.2.2
google-auth             1.7.0
google-auth-oauthlib    0.4.1
google-pasta            0.1.8
graphviz                0.13
grpcio                  1.24.3
h5py                    2.10.0
idna                    2.8
imageio                 2.6.1
imgaug                  0.3.0
imutils                 0.5.3
kaldiio                 2.14.1
Keras                   2.3.1
Keras-Applications      1.0.8
keras-ocr               0.2
Keras-Preprocessing     1.1.0
kiwisolver              1.1.0
llvmlite                0.30.0
Mako                    1.1.0
Markdown                3.1.1
MarkupSafe              1.1.1
matplotlib              3.1.1
mccabe                  0.6.1
mnist                   0.2.2
mock                    3.0.5
networkx                2.4
numba                   0.46.0
numpy                   1.17.2+mkl
oauthlib                3.1.0
opencv-contrib-python   4.1.1.26
opencv-python-headless  4.1.2.30
opt-einsum              3.1.0
Pillow                  6.1.0
pip                     19.3.1
protobuf                3.10.0
pyasn1                  0.4.7
pyasn1-modules          0.2.7
pycodestyle             2.5.0
pycparser               2.19
pycuda                  2019.1.2
pydot                   1.4.1
pyflakes                2.1.1
pyparsing               2.4.2
pypiwin32               223
pytesseract             0.3.0
python-dateutil         2.8.0
pytools                 2019.1.1
pyttsx3                 2.71
PyWavelets              1.1.1
pywin32                 224
PyYAML                  5.1.2
requests                2.22.0
requests-oauthlib       1.3.0
rsa                     4.0
scikit-cuda             0.5.3
scikit-image            0.16.2
scipy                   1.4.1
setuptools              41.4.0
Shapely                 1.6.4.post2
six                     1.12.0
termcolor               1.1.0
urllib3                 1.25.6
Werkzeug                0.16.0
wheel                   0.33.6
wrapt                   1.11.2
```

**Comment by gadagashwini** [comment] 2019-12-24 08:32
@OoiSC, Not necessary to install tensorflow-estimator first. Install tensorflow-gpu, which internally install all the dependencies like tensorflow-estimator, tensorboard. Please check the attached [gist](https://colab.sandbox.google.com/gist/gadagashwini/63a3ed96f09f56bf7f665565f239e082/untitled323.ipynb) for more. Thanks!

**Comment by OoiSC** [comment] 2019-12-24 09:06
I also tried installing tensorflow-gpu 2.1.0rc2 without first installing
tensorflow-estimator.

Failed with exactly same error message.

I ran my installation at the Windows 10 command line using pip install.

**Comment by OoiSC** [comment] 2019-12-24 09:10
The error message from my installation is

ERROR: Could not find a version that satisfies the requirement
tensorflow-gpu-estimator<2.2.0,>=2.1.0rc0 (from tensorflow-gpu==2.1.0rc2)
(from versions: none)

It is looking for tensorflow-gpu-estimator which does not exist.

**Comment by gadagashwini** [comment] 2019-12-24 09:19
@OoiSC, Could you uninstall existing tensorflow-gpu and create virtual environment and install it again.
Thanks!

**Comment by OoiSC** [comment] 2019-12-24 10:05
I have shown the list of python modules installed by pip list. You will
notice that there are no tensorflow-gpu or any tensorflow modules
installed. This means that I install tensorflow-gpu in an environment where
I had uninstalled all tensorflow modules.


I do not use virtual environments.

**Comment by mihaimaruseac** [comment] 2019-12-26 17:17
Couldn't reproduce on Linux but was able to reproduce in Windows.

It seems this comes from the way we generate the new pip packages (@yifeif, can you take a look?)

I'll create a `tensorflow-gpu-estimator` pip package to temporarily fix this.

**Comment by mihaimaruseac** [comment] 2019-12-26 17:26
I created the `tensorflow-gpu-estimator` pip package and was able to `pip install tensorflow-gpu==2.1.0rc2` on Windows. @OoiSC, can you please try this too?

**Comment by OoiSC** [comment] 2019-12-29 13:07
Thanks. I was sick during the last 2
days and I did not read my email until today.

Will try tomorrow.

**Comment by OoiSC** [comment] 2019-12-30 03:35
My windows 10 installation of tensorflow-gpu==2.1.0.rc2 is now successful
as it can now collect tensorflow-gpu=estimator.

Thanks!

**Comment by mihaimaruseac** [comment] 2019-12-30 15:48
Thank you for confirming. I'm going to close the issue then, as it seems solved.

**Comment by jgenest83** [comment] 2020-04-14 14:26
the exact same issue arise for tensorflow-gpu==2.2.0-rc2

**Comment by mihaimaruseac** [comment] 2020-04-14 16:26
Thanks for the ping. We will release estimator 2.2.0 final this week and we should fix this. Reopening this issue until then.

**Comment by mihaimaruseac** [comment] 2020-04-16 19:52
Estimator 2.2.0 has been released and it also has the gpu counterpart. When TF 2.2.0 gets released (very soon now, probably by Monday), this should be fixed.

**Comment by mihaimaruseac** [comment] 2020-06-20 21:54
Closing as all components have been released

**Closed by mihaimaruseac** 2020-06-20 21:54 UTC
Labels: TF 2.1, subtype:windows, type:build/install
