### ISSUE TITLE
Performance of TFLite custom AAR is lower than AAR release

### ISSUE THREAD

**Issue by myth01** [tensorflow/tensorflow#21864] opened 2018-08-25 01:13 UTC
When I build TFLite custom library for v1.9.0 using tip of v1.9 branch Android performance is lower by ~10-20% compared to a standard AAR release.
Build command used is bazel build --cxxopt='--std=c++11' -c opt --fat_apk_cpu=armeabi-v7a tensorflow/contrib/lite/java:tensorflow-lite

Is there anything I am missing in the build procedure?

**Comment by tensorflowbutler** [comment] 2018-08-31 07:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by jdduke** [comment] 2018-09-06 21:56
Can you sure which Android NDK and compiler you're using?

**Comment by myth01** [comment] 2018-09-08 22:55
Hi @jdduke  Thanks for your response. What is the recommended NDK version? Bazel is picking up clang.

**Comment by jdduke** [comment] 2018-09-10 15:41
Any of r14, r15 or r16 should work. Are you by chance using NDK r17? See also issue https://github.com/tensorflow/tensorflow/issues/20830 for a related report about performance degradation with NDK r17.

**Comment by myth01** [comment] 2018-09-11 01:38
I am using r15b, still I see this degradation.

**Comment by myth01** [comment] 2018-09-11 01:41
What is also not clear is the commit id used with the release. I am using the tip of r1.9 branch.

**Comment by myth01** [comment] 2018-09-20 01:51
@jdduke Do you have any updates about this? Thanks in advance!

**Comment by jdduke** [comment] 2018-09-24 15:57
Have you tried building a fat library that includes both arm/arm64 binaries? The arm64 binary (which is included in the official release) should provide improved performance on arm64 devices.

```
bazel build --cxxopt='--std=c++11' -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a ...
```

**Comment by tensorflowbutler** [comment] 2018-10-12 12:48
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tofulawrence** [comment] 2018-10-15 17:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-10-15 17:02 UTC
Labels: comp:lite, stat:awaiting response

**Comment by jazzystring1** [comment] 2018-11-18 06:22
Is the official Tensorflow Lite AAR(nightly version) release includes arm/arm64 binaries?

**Comment by jdduke** [comment] 2018-11-18 19:05
Yes, the official AAR release should include both arm and arm64 binaries.
