### ISSUE TITLE
Zero copy between CPU and GPU

### ISSUE THREAD

**Issue by faerics** [tensorflow/tensorflow#31441] opened 2019-08-08 09:51 UTC
<em>I made sure that this is a feature request. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): __tensorflow-gpu 1.13.1+nv19.5__
- Are you willing to contribute it (Yes/No): __No__, not involved in project, could try

**Describe the feature and the current behavior/state.**

I use some network which requires **a lot of CPU <-> GPU transfers**, namely NMSv2 on a hardware platform where CPU and GPU have **unified (common) memory**. Such a transfers cause a lot of copying between the same memory, while **zero-copy** technique could be used.

NVIDIA team [says](https://devtalk.nvidia.com/default/topic/1059017/jetson-agx-xavier/zero-copy-with-tensorflow/post/5369698/#5369698) that this request should be filed here.

**Will this change the current api? How?**

**Yes.** Probably requires adding some new option in config, which handles whether or not to copy between CPU & GPU. like
```python
config.gpu_options.zero_copy = True
```

Maybe some further investigation is needed.

**Who will benefit with this feature?**

- **Users** who use embedded devices with unified memory will get **performance increase** in cases with many CPU <-> GPU transfers.
- **Tensorflow itself** could use this feature to persuade developers to choose it for embedded systems.

**Any Other info.**

- A [question](https://devtalk.nvidia.com/default/topic/1059017/jetson-agx-xavier/zero-copy-with-tensorflow/) about zero copy on NVIDIA DevTalk forum
- A [post](http://arrayfire.com/zero-copy-on-tegra-k1/) about sources modification need to make zero-copy work

**Comment by aaroey** [comment] 2019-08-12 21:18
The original request seems related to Jetson platform. I'm not familiar with that. @nluehr any suggestions?

**Comment by faerics** [comment] 2019-08-19 09:05
@aaroey,
Let me clarify the thing that the request on Nvidia forum is related to Jetson indeed, but the entire freq we're discussing aims not on Jetson only.
AFAIK, tensorflow uses CUDA to allocate memory on GPU, and CUDA allows zero-coly memory allocation.

**Comment by aaroey** [comment] 2019-08-19 15:53
@faerics, hmm I don't fully understand, what did you mean by `CUDA allows zero-coly memory allocation`?

**Comment by faerics** [comment] 2019-08-22 10:04
@aaroey, soory for the delay,
I'm not a CUDA pro by myself, but according to the [post](http://arrayfire.com/zero-copy-on-tegra-k1/) I linked one needs to use different allocation functions (namely, `CudaHostAlloc` instead of `CudaMalloc` and then `cudaHostGetDevicePointer` instead of `CudaMemcpy`).

The post is from 2014, not sure that functions' names sre the same nowadays.

**Comment by faerics** [comment] 2019-09-05 08:28
Hello, commenting to bubble this up. @aaroey, let's continue the discussion!

**Comment by aaroey** [comment] 2019-10-10 22:13
@chsigg what do you think about the proposal of adding pin memory allocation support?

**Comment by chsigg** [comment] 2019-12-09 16:32
I'm fine with adding a pinned memory allocator (IIRC, we already have it for tests), if someone is willing to contribute. I don't expect it to be useful except for shared memory systems (like Jetson).

**Comment by byronyi** [comment] 2019-12-09 19:49
I think we already have a GpuHostAllocator which does allocation on pinned memory regions. It is however not necessary to allocate tensors that won’t be transferred cross device using the pinned memory, and TF currently does static analysis to determine the AllocationAttribute for each tensor. In 1.x we even have a force_gpu_compatible option which forces allocation on pinned memory regions, but this option is not exposed in 2.0.

Hope this helps.

**Comment by Soroosh129** [comment] 2020-07-29 01:00
I've implemented a zero copy allocator on Jetson AGX. The issue is that `cuMemHostAlloc` actually disables _both_ the CPU and GPU cache. Therefore, I'm getting slower training speeds compared to the default `cuMemAlloc`.

**Comment by byronyi** [comment] 2020-07-29 03:07
> I've implemented a zero copy allocator on Jetson AGX Xavier. The issue is that `cuMemHostAlloc` actually disables _both_ the CPU and GPU cache. Therefore, I'm getting slower training speeds compared to the default `cuMemAlloc`.
> 
> **Edit:** See [this](https://personal.utdallas.edu/~soroush/papers/RTAS2020.pdf) published in RTAS 2020.

Cache-coherence really hurts...

**Comment by tensorflowbutler** [comment] 2021-02-01 14:05
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:55 UTC
Labels: TF 1.13, comp:gpu, stat:contributions welcome, type:feature
