### ISSUE TITLE
android libtensorflow_inference.so run crash (signal 6 (SIGABRT))

### ISSUE THREAD

**Issue by hexujun** [tensorflow/tensorflow#9096] opened 2017-04-10 07:21 UTC
04-10 14:37:38.954   331   331 F DEBUG   : Build fingerprint: 'Xiaomi/virgo/virgo:6.0.1/MMB29M/7.3.30:user/release-keys'
04-10 14:37:38.954   331   331 F DEBUG   : Revision: '0'
04-10 14:37:38.954   331   331 F DEBUG   : ABI: 'arm'
04-10 14:37:38.954   331   331 F DEBUG   : pid: 24044, tid: 24335, name: pool-1-thread-1  >>> cmmc.com.styletransfer <<<
04-10 14:37:38.954   331   331 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-10 14:37:38.983   331   331 F DEBUG   :     r0 00000000  r1 00005f0f  r2 00000006  r3 a08bf978
04-10 14:37:38.983   331   331 F DEBUG   :     r4 a08bf980  r5 a08bf930  r6 0000000c  r7 0000010c
04-10 14:37:38.983   331   331 F DEBUG   :     r8 9d8fca90  r9 a06a7bf8  sl a08bdbd0  fp a08bdb30
04-10 14:37:38.985   331   331 F DEBUG   :     ip 00000006  sp a08bd930  lr b6ceec69  pc b6cf1058  cpsr 400f0010
04-10 14:37:39.101   331   331 F DEBUG   :
04-10 14:37:39.101   331   331 F DEBUG   : backtrace:
04-10 14:37:39.101   331   331 F DEBUG   :     #00 pc 00042058  /system/lib/libc.so (tgkill+12)
04-10 14:37:39.101   331   331 F DEBUG   :     #01 pc 0003fc65  /system/lib/libc.so (pthread_kill+32)
04-10 14:37:39.102   331   331 F DEBUG   :     #02 pc 0001c403  /system/lib/libc.so (raise+10)
04-10 14:37:39.102   331   331 F DEBUG   :     #03 pc 000195b5  /system/lib/libc.so (__libc_android_abort+34)
04-10 14:37:39.102   331   331 F DEBUG   :     #04 pc 00017508  /system/lib/libc.so (abort+4)
04-10 14:37:39.102   331   331 F DEBUG   :     #05 pc 00775457  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.103   331   331 F DEBUG   :     #06 pc 0075780d  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.103   331   331 F DEBUG   :     #07 pc 00757855  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.103   331   331 F DEBUG   :     #08 pc 0075794d  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.103   331   331 F DEBUG   :     #09 pc 00757d0f  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.105   331   331 F DEBUG   :     #15 pc 00257b13  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.105   331   331 F DEBUG   :     #16 pc 0063f655  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.105   331   331 F DEBUG   :     #17 pc 0063f8d3  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.105   331   331 F DEBUG   :     #18 pc 006342e3  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #19 pc 0063c49f  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #20 pc 0063c591  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #21 pc 0063c81d  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #22 pc 0063fc19  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #23 pc 006390c9  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.106   331   331 F DEBUG   :     #24 pc 0008c0e9  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.107   331   331 F DEBUG   :     #25 pc 0008c4eb  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so
04-10 14:37:39.107   331   331 F DEBUG   :     #26 pc 0008579f  /data/app/cmmc.com.styletransfer-2/lib/arm/libtensorflow_inference.so (Java_org_tensorflow_Session_run+650)
04-10 14:37:39.107   331   331 F DEBUG   :     #27 pc 0056e0c7  /data/app/cmmc.com.styletransfer-2/oat/arm/base.odex (offset 0x391000) (byte[] org.tensorflow.Session.run(long, byte[], long[], long[],
int[], long[], int[], long[], boolean, long[])+306)

I stylize image crashed((the image size is 576x768 or more bigger, but 384x512 not crash)
The Model based on A Neural Algorithm of Artistic Style(Stylize) paper

**Comment by asimshankar** [comment] 2017-04-10 18:12
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  **Make sure you also include the exact command if possible to produce  the output included in your test case**.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

In particular, please include the git version you've compiled from any any other information you can provide to reproduce the problem (have you written custom code, or is this just using the demo application)?

**Comment by andrewharp** [comment] 2017-04-10 18:36
@hexujun Have you made any modifications to the code? The sizes you list are invalid -- the demo by default only processes square images.

**Comment by andrewharp** [comment] 2017-05-04 20:48
Closing; please respond with additional details if issue persists.

**Closed by andrewharp** 2017-05-04 20:48 UTC
Labels: stat:awaiting response

**Comment by jakiechris** [comment] 2017-11-21 15:25
@hexujun 
pls contact me , my qq is 604173084 . we are doing the same thing and facing the same issue
