### ISSUE TITLE
[2.2rc3] Distibuted training with Keras and ThreadPoolDataset runs out of memory

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#38617] opened 2020-04-16 23:29 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0rc3 and tf-nightly
- Python version: 3.7
- CUDA/cuDNN version: 10.1 / 7.6.5.32
- GPU model and memory: 4 x NVIDIA V100 on GCP

**Describe the current behavior**

When running the code below with cached training and validations datasets in a multi-GPU environment (I am using a GCP VM with 312GB of memory and 4 NVIDIA V100s) memory increases during each validation run until the VM runs out of memory. This behaviour can be observed on 2.2.0-rc3 and on the latest nightly.

It looks like the validation dataset is not properly cached since I can still see network access during validation and the memory usage drops below the theoretical cached memory requirements after validation has finished and then increases linearly during the next validation round to a point larger than the memory usage in the previous epoch.
In the example below I intentionally use an very large validation set to make this memory increase very obvious and make training crash within the first 5 epochs. This behaviour can also be observed with other datasets, but the memory increase will be less noticible on smaller datsets.

**In which cases is the memory usage still stable?**
To narrow down the possible causes for this I found two cases where this issue doesn't exist:

1. When running on a single GPU memory usage is stable.

2. Tensorflow Datasets uses a [`_PrivateThreadPoolDataset`](https://github.com/tensorflow/tensorflow/blob/8e0eecc8e396f8c1859b1b3954a89a41da8b5b45/tensorflow/python/data/ops/dataset_ops.py#L360-L362) by setting the [`experimental_threading.private_threadpool_size=16`](https://github.com/tensorflow/datasets/blob/8277548d5bdbc264a50d84ef702adc15bee8d4ae/tensorflow_datasets/core/tfrecords_reader.py#L62) as a default option. When disabling this option the memory usage is stable again. Unfortunately this is not a valid workaround in userland since the dataset option cannot be overwritten with `experimental_threading.private_threadpool_size=None` as it expects an integer.

@yhliang2018 @tomerk @byronyi This seems to be a complicated interaction between `tf.data`, `tf.keras` and `tf.distribute`, do you have an idea what could cause this behaviour? Please let me know what additional information I could provide.
I've ran into similar issues with `experimental_threading.private_threadpool_size` on TF 2.0.0 in the past though never investigated the root cause in detail, so this might not be an entirely new regression.

**Describe the expected behavior**

Memory usage should be stable after the first epoch.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_datasets as tfds


batch_size = 1024

dataset = tfds.load(
    "imagenet2012:5.0.0",
    decoders={"image": tfds.decode.SkipDecoding()},
    split="train",
    data_dir="gs://my-cloud-bucket",
)

val_dataset = tfds.load(
    "imagenet2012:5.0.0",
    decoders={"image": tfds.decode.SkipDecoding()},
    split="validation",
    data_dir="gs://my-cloud-bucket",
)


def _decode_and_center_crop(image_bytes):
    """Crops to center of image with padding then scales image_size."""
    shape = tf.image.extract_jpeg_shape(image_bytes)
    image_height = shape[0]
    image_width = shape[1]
    image_size = 224

    padded_center_crop_size = tf.cast(
        (
            (image_size / (image_size + 32))
            * tf.cast(tf.minimum(image_height, image_width), tf.float32)
        ),
        tf.int32,
    )

    offset_height = ((image_height - padded_center_crop_size) + 1) // 2
    offset_width = ((image_width - padded_center_crop_size) + 1) // 2
    crop_window = tf.stack(
        [offset_height, offset_width, padded_center_crop_size, padded_center_crop_size]
    )
    image = tf.image.decode_and_crop_jpeg(image_bytes, crop_window, channels=3)
    return tf.image.resize(image, [image_size, image_size], method="bicubic")


def preprocessing(data):
    return tf.cast(_decode_and_center_crop(data["image"]), tf.float32), data["label"]

dataset = (
    dataset.cache()
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

val_dataset = (
    val_dataset.cache()
    .map(preprocessing, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(1)
)

with tf.distribute.MirroredStrategy().scope():
    model = tf.keras.models.Sequential(
        [
            tf.keras.layers.GlobalMaxPool2D(input_shape=(224, 224, 3)),
            tf.keras.layers.Dense(1000, activation="softmax",),
        ]
    )

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy", "sparse_top_k_categorical_accuracy"],
    )

model.fit(
    val_dataset, epochs=5, validation_data=dataset,
)
```

**Other info / logs**

To monitor memory usage over time tools like [`ytop`](https://github.com/cjbassi/ytop/) can be used.

**Comment by Conchylicultor** [comment] 2020-04-17 01:24
Yes, I think those arguments are obsolete and should be removed. Thank you for your PR

**Comment by Saduf2019** [comment] 2020-04-17 04:54
@lgeiger 
as there is a pr monitoring the issue, please let us know if we can move this to closed status

**Comment by lgeiger** [comment] 2020-04-17 08:56
>  as there is a pr monitoring the issue, please let us know if we can move this to closed status

@Saduf2019 @Conchylicultor is refering to the PR on the [TensorFlow Datasets repo](https://github.com/tensorflow/datasets/pull/1893). This doesn't solve the underlying issue in TensorFlow though, so this issue is not resolved.

**Comment by guptapriya** [comment] 2020-04-17 19:01
@lgeiger you mentioned with 1 GPU memory was stable. Was that without using any distribution strategy? or with MirroredStrategy + 1 GPU? Also, what batch size was used for the 1 GPU case? 

Also, does the issue go away if there is no validation dataset at all?

**Comment by lgeiger** [comment] 2020-04-17 19:08
> you mentioned with 1 GPU memory was stable. Was that without using any distribution strategy? or with MirroredStrategy + 1 GPU?

This was without using any distribution strategy.

> Also, what batch size was used for the 1 GPU case?

Both `MirroredStrategy` and single GPU used batch size 1024.

> Also, does the issue go away if there is no validation dataset at all?

If I recall correctly this only happens with a validation set, but I will explicitely test this later today again just to make sure.

**Comment by lgeiger** [comment] 2020-04-17 20:22
> Also, does the issue go away if there is no validation dataset at all?

@guptapriya I just double checked and memory usage is completely flat when there is on validation dataset.

**Comment by lgeiger** [comment] 2020-04-17 21:20
@goldiegadde @guptapriya @ymodak After writing down this issue yesterday I discovered another related broken behaviour in the latest RC. I wrote down my findings in #38655

**Comment by guptapriya** [comment] 2020-04-17 21:24
Thanks a lot for filing this issue @lgeiger. Your analysis has helped us narrow down on a possible root cause which we will investigate further and fix. For now this does look like a regression in 2.2rc3. 
We still don't understand why removing experimental_threading.private_threadpool_size helps though.

**Comment by guptapriya** [comment] 2020-04-17 21:46
@lgeiger to help us confirm that this is a regression, would you mind running your check against TF 2.1? both for the OOM issue, and the network usage.

**Comment by lgeiger** [comment] 2020-04-18 14:10
> @lgeiger to help us confirm that this is a regression, would you mind running your check against TF 2.1? both for the OOM issue, and the network usage.

@guptapriya This is a regression introduced between 2.1 and 2.2. I re-ran the checks with TF 2.1 and both issues are not present there (i.e. memory a network usage are completely stable).

Note that with TF 2.1 I am running into #36126 instead so I am seeing a lot of unnecessary error messages each epoch, but I don't think this is related.

**Comment by guptapriya** [comment] 2020-04-18 19:55
Thanks @lgeiger for confirming, appreciate it! We know the root cause of the memory issue, and have a fix in the works. I am surprised the network usage is also stable though, because we thought the root cause for the network issue is something else.. maybe there is some interaction still between the 2 issues that we do not understand.

**Comment by lgeiger** [comment] 2020-04-18 22:27
@guptapriya Thanks for investigating! In my journey of upgrading from 2.0 to 2.2 I discovered my hopefully last GPU memory related problem. I wrote down the findings in #38675.

**Comment by guptapriya** [comment] 2020-04-19 07:07
Thanks @lgeiger, I ll ask some folks in XLA to take a look at that one.

**Comment by lgeiger** [comment] 2020-04-21 21:56
I just retested this with the latest nightly and it seems that this has been fixed by 7ebbab819e736319ec35b48e31f4d62fbad6626b as well. I'm still not sure what the interaction with the thread pool dataset is though.

**Comment by guptapriya** [comment] 2020-04-23 17:18
Hm, are you saying that after https://github.com/tensorflow/tensorflow/commit/7ebbab819e736319ec35b48e31f4d62fbad6626b, there is no increase in memory usage? 
That seems a bit surprising because my understanding was that the fix for the memory leak and caching issues were actually different.. (and we still haven't submitted the fix for memory leak, though it is close to be submitted). 
Is memory usage completely stable after this change, or does it still increase a little bit?

**Comment by lgeiger** [comment] 2020-04-23 17:23
>  Is memory usage completely stable after this change, or does it still increase a little bit?

I can retest this more carefully tomorrow, but at least the memory increase seemed not to be as catastrophic. But I will double check, since I only briefly tested this.

**Comment by alimhanif** [comment] 2020-04-28 14:34
@lgeiger I got memory error on second epoch when evaluate val set. Then, I see on the memory usage, at the begining it only takes 35%, but it's going up time by time until I got OOM. Is it same problem with you?

I use Multi Workers Mirrored Strategy btw

**Comment by lgeiger** [comment] 2020-04-28 14:35
@alimhanif are you using the latest nightly or 2.2.0rc3?

**Comment by alimhanif** [comment] 2020-04-28 14:38
yes, i'm using that version

**Comment by lgeiger** [comment] 2020-04-28 14:40
> yes, i'm using that version

If you are using `tensorflow==2.2.0rc3`, could you give the latest version of `tf-nightly` a try and see if the issue is still there?

**Comment by alimhanif** [comment] 2020-04-28 14:48
The latest version of TF Nightly is not able to use Tensorboard Callback. So, I didn;t try it with large data. 
This is error that I get:
```
No such file or directory: 'gs://my_bucket/my_model/logs/projector_config.pbtxt
```
Could you help me please about this error? If I'm able to use TB, will try to test it with large data

TF Nightly version: `2.2.0.dev20200428`

**Comment by alimhanif** [comment] 2020-04-28 14:54
Yes, let me try it

**Comment by anj-s** [comment] 2020-04-28 18:39
@lgeiger We've checked in the [fix](dac6d6ae7c381fb93438d8553b2596bfd4828c49) for the memory leak regression. I know you mentioned that the issue was not there post the cache fix. Let us know if you are still running into issues. Thanks!

**Comment by alimhanif** [comment] 2020-04-28 21:00
@lgeiger after training for 5 hrs, TF Nightly version: `2.2.0.dev20200428` shows the flat memory utilization.

But for sure, I have another error on this version (cant use Tensorboard callback). Will make another issue

**Comment by lgeiger** [comment] 2020-04-28 21:30
@anj-s @guptapriya Thank you very much for the fix. Reliably reproducing and tracking down this issue was rather painful, so I'm very happy that it is fixed now. I double checked with todays `tf-nightly` and the memory usage is perfectly stable for many epochs 🚀 

On `tf-nightly` I now get the following warning, but I am not sure if this is related to the fix:
```
tensorflow/core/kernels/data/captured_function.cc:458]
Disabling multi-device execution for a function that uses the experimental_ints_on_device attribute.
```

**Comment by alimhanif** [comment] 2020-04-28 21:33
can we do a cherry picking this `2.2.0.dev20200428` version to the `2.2.0rc3`?

I need to train my model with Tensorboard, btw
TF 2.2 RC 3 is almost perfect, it's only have memory leak problem in my experiences


I think latest TF Nighly that I use is not able to read on gcs bucket (especially for Tensorboard CallBack)

**Comment by lgeiger** [comment] 2020-04-28 21:36
> can we do a cherry picking this 2.2.0.dev20200428 version to the 2.2.0rc3?

@alimhanif This is in progress and will probably be included in the stable release of 2.2.0. See #38996

**Comment by alimhanif** [comment] 2020-04-29 01:26
They close it and move to existing PR
https://github.com/tensorflow/tensorflow/pull/39002

**Comment by goldiegadde** [comment] 2020-04-29 01:30
@lgeiger and @alimhanif thanks for verifying that the issue is fixed with tf-nightly

**Comment by alimhanif** [comment] 2020-04-29 04:49
I'm so sorry for asking this question. So, when we are able to use this commit in the latest `2.2.0rc3`? Do you have ETA for this? 

TF nightly have a lot of bugs. Can't rely on this. :(

**Comment by anj-s** [comment] 2020-04-30 18:27
Closing this bug since the issue has been fixed. Thank you for reporting this!

**Closed by anj-s** 2020-04-30 18:27 UTC
Labels: TF 2.3, comp:dist-strat, comp:keras, type:bug

**Comment by lgeiger** [comment] 2020-05-01 18:35
Thanks, I can confirm that this doesn't show up in rc4 anymore
