### ISSUE TITLE
TensorFlow Lite conversion fails

### ISSUE THREAD

**Issue by ioavator** [tensorflow/tensorflow#24646] opened 2019-01-01 00:02 UTC
**System information**
Windows 7/64bit
- TensorFlow installed from binary:
1.12 from pip
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

Traceback (most recent call last):
  File "C:\Users\io\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\lite\python\lite.py", line 453, in
convert
    **converter_kwargs)
  File "C:\Users\io\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\lite\python\convert.py", line 342,
in toco_convert_impl
    input_data.SerializeToString())
  File "C:\Users\io\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\lite\python\convert.py", line 135,
in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b'Traceback (most recent call last):\r\n  File "C:\\Users\\io\\AppData\\Roaming\\Python\\Python36\\site-packages\\tensor
flow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, descrip
tion = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "c:\\users\\io\\anaconda3\\lib\\imp.py"
, line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'
_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (mos
t recent call last):\r\n  File "c:\\users\\io\\anaconda3\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__mai
n__", mod_spec)\r\n  File "c:\\users\\io\\anaconda3\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals
)\r\n  File "C:\\Users\\io\\Anaconda3\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "C:\\U
sers\\io\\AppData\\Roaming\\Python\\Python36\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.p
y", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "C:\\User
s\\io\\AppData\\Roaming\\Python\\Python36\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.
py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "C:\\Users\\io\\AppData\\Roaming
\\Python\\Python36\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_i
mport_helper\r\n    import _tensorflow_wrap_toco\r\nModuleNotFoundError: No module named \'_tensorflow_wrap_toco\'\r\n'
None

Github's Continuous build status says: 
Win GPU nightly failing, 
so I did not try retraining and reconverting.

**Comment by jvishnuvardhan** [comment] 2019-01-16 21:59
@ioavator Was there any issue in the installation? Could you provide any code to reproduce the error? Please provide any details that you think will help in finding the root cause of the issue. Thanks!

**Comment by ioavator** [comment] 2019-01-21 17:14
@jvishnuvardhan
>>Was there any issue in the installation? 
Nope. pip install tensorflow-gpu went smoothly.
Model training/testing with or without custom estimators works on Win7.
Apparently my problem is - toco and tensorflow lite converters are not working\supported in Windows environment.

>>Could you provide any code to reproduce the error? 
An instance of this:
https://github.com/tensorflow/tensorflow/issues/15805#issuecomment-407298717

I had to use Mac-OS to do conversion.
Mac-Os is fine. Win7 is not.

**Comment by jdduke** [comment] 2019-03-29 17:02
Does this still repro with the latest 1.13.1 TF release?

**Comment by tensorflowbutler** [comment] 2019-04-20 12:47
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-04-20 15:22
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-20 15:22 UTC
Labels: comp:lite, stat:awaiting response, type:bug/performance
