### ISSUE TITLE
[TF 2.0.0-rc0] Run model.evaluate() let  notebook crash (Chrome).

### ISSUE THREAD

**Issue by kaka-lin** [tensorflow/tensorflow#31943] opened 2019-08-24 08:29 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Mac
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): Tensorflow 2.0.0-rc0
- Python version: 3.6.5

print(tf.version.GIT_VERSION, tf.version.VERSION)
v2.0.0-beta1-5101-gc75bb66a99 2.0.0-rc0

**Describe the current behavior**
When I run `result = model.evaluate(x_train, y_train), my jupyter notebook crashed.

**Describe the expected behavior**
I will be run another cell in jupyter notebook, but I can't.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
 
I use sample code in Tensorflow 2.0.0 RC: Classify images

**Other info / logs**

**Comment by kaka-lin** [comment] 2019-08-26 05:56
I found crash only happens in Chrome browser.

In Firefox, as below:

![Screenshot from 2019-08-26 13-53-56](https://user-images.githubusercontent.com/20853096/63668267-315dc300-c809-11e9-812f-6b665c13ab47.png)

**Comment by ravikyram** [comment] 2019-08-26 10:09
@kaka-lin 

I tried in Google colab and Jupyter notebook with Google chrome and able to execute the code successfully.Can you please upgrade your google chrome version and try again and see if the problem still persists.Thanks!

**Comment by kaka-lin** [comment] 2019-08-27 02:43
Hi, @ravikyram:

I upgrade my google chrome version: Version 76.0.3809.132 (Official Build) (64-bit)
But the problem is still persistent.

I record a demo video, pls check it thanks.

TF2 - beta1:

https://drive.google.com/file/d/1g8f-IAqKU9ACYiK4BemoMpmQwxw5GlXA/view?usp=sharing

TF2 - rc0:

https://drive.google.com/file/d/1yXDPVJJ_XVCpytveEQFv9AiLlx1j3ANr/view?usp=sharing

**Comment by gino6178** [comment] 2019-08-27 02:56
I have the same problem.

**Comment by ravikyram** [comment] 2019-08-27 10:34
@kaka-lin 
As per my understanding in Google chrome with TF2 - beta1 version you are able to execute the code successfully .But with Google chrome using TF2 - rc0: you are facing the issue. Am i correct?
Thanks!

**Comment by kaka-lin** [comment] 2019-08-27 13:27
@ravikyram  

Yes!

**Comment by ravikyram** [comment] 2019-08-29 07:44
I tried reproducing the issue using Google chrome in Jupyter notebook and was able to execute the code with TF2 - beta1 but i am facing the issue with TF2 - rc0.Please, find the screenshot below.Thanks!
![error](https://user-images.githubusercontent.com/51902062/63920602-dc1aef00-ca5e-11e9-93bd-18c6dd457d30.png)

**Comment by jvishnuvardhan** [comment] 2019-11-11 19:52
@kaka-lin I think this was resolved in the recent TF versions. I checked with `TF2.0` and `tf-nightly` and I cannot reproduce the issue. 

I am closing the issue. Please feel free to reopen the issue if it persists for you. Thanks!

**Closed by jvishnuvardhan** 2019-11-11 19:52 UTC
Labels: TF 2.0-rc0, comp:keras, type:bug
