### ISSUE TITLE
Trouble installing python wheel for tensorflow on Windows 7

### ISSUE THREAD

**Issue by flightmonkey15** [tensorflow/tensorflow#7706] opened 2017-02-20 17:57 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

My problem:
http://stackoverflow.com/questions/42280894/tensorflow-wheel-install-not-supported?noredirect=1#comment71724208_42280894

Following the instructions:
https://www.tensorflow.org/install/install_windows

I had Python 3.5.2 installed, but following the instructions to install tensorflow according to the website automatically upgrades python to 3.6. The wheel is not supported.

### Environment info
Operating System:

Windows 7 

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

Not applicable yet, as I am still trying to install the software, prior to running the scripts.

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.1-cp35-cp35m-win_amd64.whl

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by Carmezim** [comment] 2017-02-21 01:15
Please see #6999, Python 3.6 is not supported on Windows yet and currently the only way is to build TensorFlow from source.  You can keep track there and this can be closed as it's a duplicate.

**Comment by poxvoculi** [comment] 2017-02-21 17:51
Closing as duplicate of #6999

**Closed by poxvoculi** 2017-02-21 17:51 UTC
