### ISSUE TITLE
Cannot compile TF 2.0.0 with MacOS 10.14.6 and XCode 11.0

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#32998] opened 2019-10-02 18:42 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs 10.14.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 2.0.0 and 1.15.0-rc2
- **Python version**: 3.7.4
- **Bazel version (if compiling from source)**: either 2.6.1, 2.6.0, 2.5.3
- **GCC/Compiler version (if compiling from source)**: Apple clang version 11.0.0 (clang-1100.0.33.8)
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: within the tensorflow 2.0.0 source directory, after standard ./configure (CPU, no GPU) or particular optimization flags besides default:

`bazel build --config=opt --config=v2 --verbose_failures //tensorflow/tools/pip_package:build_pip_package`

### Describe the problem
Compilation stops with following error:
```
ERROR: /Users/feranick/Desktop/tensorflow/tensorflow/core/debug/BUILD:43:1: ProtoCompile tensorflow/core/debug/debug_service.pb.h failed (Segmentation fault): protoc failed: error executing command 
  (cd /private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/execroot/org_tensorflow && \
  exec env - \
    PATH=/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/ \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/host/bin' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' '--grpc_out=bazel-out/host/bin' -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -I. -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src tensorflow/core/debug/debug_service.proto)
Execution platform: @bazel_tools//platforms:host_platform: protoc failed: error executing command 
  (cd /private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/execroot/org_tensorflow && \
  exec env - \
    PATH=/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/Users/feranick/Library/Python/3.7/bin/:/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/usr/local/bin/:/Users/feranick/Documents/Work/c/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/:/Users/feranick/Documents/Work/c/android-sdk/platform-tools/ \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/host/bin' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_cpp_plugin' '--grpc_out=bazel-out/host/bin' -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -I. -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -I. -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -I. -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src -Iexternal/com_google_protobuf/src -Ibazel-out/host/bin/external/com_google_protobuf/src tensorflow/core/debug/debug_service.proto)
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by feranick** [comment] 2019-10-02 18:43
I should note that compilation proceeded just fine with Xcode 10.3 and TF 2.0.0-rc2.

**Comment by ravikyram** [comment] 2019-10-03 06:37
As I understand with Xcode 10.3 and using  TF 2.0.0-rc2 the problem is resolved.Please, let us know if it is still an issue?. Thanks!

**Comment by feranick** [comment] 2019-10-03 14:29
Let's say that with XCode 10.3 and TF-2.0.0-rc2 it compiles. The problem is I cannot revert XCode to that, as the system automatically updated it to XCode 11. So I am stuck now.

**Comment by feranick** [comment] 2019-10-03 14:30
BTW, the issue is not unique to TF v2.0.0. TF1.15.0-rc1 and TF 1.15.0-rc2 do not compile either with XCode 11. I updated the bug description to reflect that.

**Comment by freedomtan** [comment] 2019-10-10 01:13
@feranick As @ravikyram suggested, Xcode 10.x  work fine for me on both macOS 10.14 and 10.15. Xcode 11 does cause problem as you reported. You can download Xcode 10.3  from [apple developer site](https://developer.apple.com/download/more/).

@ravikyram and @angerson it seems the clang come with **Xcode 11**  is problematic, with **Xcode 11** and  `bazel build --host_copt=-O0 --config opt //tensorflow/tools/pip_package:build_pip_package`, I can pass what @feranick ran into.

**Comment by feranick** [comment] 2019-10-10 03:19
So the only difference for successful compilation is to add `--host_copt=-O0`, i.e. remove any optimization?

**Comment by freedomtan** [comment] 2019-10-10 03:45
Yes, without optimization the protoc won't crash with segmentation fault. Surely `-O0` is not an answer. Just to make sure it could be a problem of the Xcode 11 toolchain.

**Comment by angerson** [comment] 2019-10-11 18:42
Thanks for the report. This looks to me like an issue with the interaction between the protoc compiler and XCode 11.0, is that right? If that's the case, this looks like an issue for https://github.com/protocolbuffers/protobuf.

**Comment by freedomtan** [comment] 2019-10-13 01:24
@angerson not exactly, this could be caused by compilation flags or other settings used by TensorFlow, because if I replace the `protoc` with one that I compiled with **cmake + Xcode 11**, `protoc` works well. Easy to reproduce @feranick's problem, run
```
bazel build --config opt tensorflow/core/profiler:profiler_analysis_proto_py_genprot -s
```
with **Xcode 11**, then you'll see something like
```
cd /private/var/tmp/_bazel_freedom/adcaa36b2ac85ab2f5a2434777d27f58/execroot/org_tensorflow && \
  exec env - \
    PATH='/Users/freedom/tfpy3/bin:/Users/freedom/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/opt/local/bin:/Users/freedom/work/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands' \
    PYTHON_BIN_PATH=/Users/freedom/tfpy3/bin/python \
    PYTHON_LIB_PATH=/Users/freedom/tfpy3/lib/python3.7/site-packages \
    TF_CONFIGURE_IOS=0 \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/darwin-opt/bin' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_python_plugin' '--grpc_out=bazel-out/darwin-opt/bin' -I. -I. -I. -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -I. -I. -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -I. -I. -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -I. -I. -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -I. -I. -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/darwin-opt/bin/external/com_google_protobuf/python tensorflow/core/profiler/profiler_analysis.proto)
ERROR: /Volumes/Seagate5T/tf-clean/tensorflow/core/profiler/BUILD:55:1: ProtoCompile tensorflow/core/profiler/profiler_analysis_pb2.py failed (Segmentation fault): protoc failed: error executing command bazel-out/host/bin/external/com_google_protobuf/protoc '--python_out=bazel-out/darwin-opt/bin' '--plugin=protoc-gen-grpc=bazel-out/host/bin/external/grpc/grpc_python_plugin' ... (remaining 33 argument(s) skipped)
```

How I compiled protoc:

1. find the version of `protobuf` used by TensorFlow from `${TF_SOURCE_ROOT}/tensorflow/workspace.bzl`. What I tried just now is:
```
    PROTOBUF_URLS = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz",
    ]
    PROTOBUF_SHA256 = "b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59"
    PROTOBUF_STRIP_PREFIX = "protobuf-310ba5ee72661c081129eb878c1bbcec936b20f0"
```
2. get the source; unpack it
3. build it with cmake

**Comment by freedomtan** [comment] 2019-10-13 02:32
I think the problem is caused by **-march=native + non-O0 optimization**. With **-march=native -O2**, the protoc binary I built with cmake also crashed. With `build:opt --host_copt=-march=native`  removed from `.tf_configure.bazelrc`,  something like
```
bazel build --config opt tensorflow/core/profiler:profiler_analysis_proto_py_genprot
```
went without problems.

**Comment by tensorflowbutler** [comment] 2019-10-27 12:21
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by feranick** [comment] 2019-10-27 14:11
It is still an issue in that I can't compile with optimization flags. Not sure if anybody is doing much about it, as it seems this is a compiler issue.

**Comment by feranick** [comment] 2020-03-26 16:02
Using MacOS 10.15.4, Xcode 11.4. I have been able to successfully compile (with optimization flags), TF v.2.1.0. I think XCode 11.4 now fixes the issues with the previous 11.3.

**Comment by mihaimaruseac** [comment] 2020-03-26 17:37
In this case, can we close this?

**Comment by feranick** [comment] 2020-03-26 17:38
I think it can be closed, previous checking if the documentation/release notes needs to be changed to reflect this.

**Comment by feranick** [comment] 2020-03-26 17:40
In particular, [this patch ](https://github.com/bazelbuild/continuous-integration/pull/878/commits/6786208c5e6a6448f7e3b47cd490b10663c9507d) should be reversed as it seems to no longer apply.

**Comment by mihaimaruseac** [comment] 2020-03-26 17:48
In our build scripts it has been reverted (see mention commits attached to the issue). If there are other places, we could accept pull requests but only against `master` branch. The release branches will only be updated when we do a new patch release.

Closing as resolved.

**Closed by mihaimaruseac** 2020-03-26 17:48 UTC
Labels: subtype:macOS, type:build/install
