### ISSUE TITLE
[TF2.0] tf.function use within tf.custom_gradient is extremly slow

### ISSUE THREAD

**Issue by n-gao** [tensorflow/tensorflow#34534] opened 2019-11-22 23:48 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I wrote a simple example similar to the provided examples
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not tested
- TensorFlow installed from (source or binary): pip 
- TensorFlow version (use command below): r2.0
- Python version: 3.7
- Bazel version (if compiling from source): does not apply
- GCC/Compiler version (if compiling from source): does not apply
- CUDA/cuDNN version: 10.2
- GPU model and memory: Nvidia GTX 1050 2048MB

**Describe the current behavior**
When calling a `tf.function` from within a `tf.custom_gradient` function a large delay occurs **before** and **after** the `tf.function` call. With more complex functions this delay before and after goes up.

**Describe the expected behavior**
There should not be any delay or at least no perceivable.

**Code to reproduce the issue**
The following code snippet reproduces this behavior. I execute the code twice to account for `tf.function`s tracing which has to be one once for `_df`.
```python
@tf.function
def _df(x):
    tf.print('Start inner')
    start = tf.timestamp()
    
    result = x@x
    
    end = tf.timestamp()
    tf.print('End inner; took: ', end-start)
    return result
    
@tf.custom_gradient
def f(x):
    def df(dy):
        tf.print('Before outer')
        start = tf.timestamp()
        
        grad = _df(x)
        
        end = tf.timestamp()
        tf.print('After outer; took: ', end-start)
        return dy*grad
    return x@x, df


for i in range(2):
    x = tf.random.normal((1000, 1000))
    t = tf.timestamp()
    with tf.GradientTape() as tape:
        tape.watch([x])
        r = f(x)
    tf.print('Forwardpass took', tf.timestamp() - t)
    t = tf.timestamp()
    tape.gradient(r, x)
    tf.print('Backwardpass took', tf.timestamp() - t)
```

Output:
```
Forwardpass took 0.00038313865661621094
Before outer
Start inner
End inner; took:  2.6941299438476563e-05
After outer; took:  0.093798160552978516
Backwardpass took 0.099112987518310547
Forwardpass took 0.0002689361572265625
Before outer
Start inner
End inner; took:  2.8848648071289063e-05
After outer; took:  0.00881505012512207
Backwardpass took 0.01347804069519043
```

**Comment by ravikyram** [comment] 2019-11-25 06:03
@n-gao 
I have tried on colab with TF version 2.0 ,2.1.0dev20191124 .Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/4108b210f3e0fb3f67090211140ab36f/untitled401.ipynb). Is this the expected behavior? Thanks!

**Comment by n-gao** [comment] 2019-11-25 16:57
Yes it is but I forgot about asynchronous execution and this is probably the intended behavior, right? The inner loop has a low execution time because all of the commands are queued to the GPU and when the `tf.function` exists tf waits for the complete execution of the function. Or did I miss something?
Thank you!

**Comment by gowthamkpr** [comment] 2019-12-20 23:41
@n-gao you are right. This is the intended behaviour.

I am closing this issue as it is not a bug/performance, build/install, feature request related issues. Please add additional comments and we can open this issue again. Thanks!

**Closed by gowthamkpr** 2019-12-20 23:41 UTC
Labels: TF 2.0, comp:autograph, comp:ops, type:support
