### ISSUE TITLE
segfault during tf.image.non_max_suppression_padded

### ISSUE THREAD

**Issue by mjkim720** [tensorflow/tensorflow#40532] opened 2020-06-17 03:20 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Segmentation fault occurs in c++ when passing a large value for `max_output_size`  and `True` for `pad_to_max_output_size`.

**Describe the expected behavior**
No segmentation fault. I would expect a proper error handling exception if necessary rather than a segfault.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

boxes = [[4.0, 6.0, 3.0, 6.0],
       [2.0, 1.0, 5.0, 4.0],
       [9.0, 0.0, 9.0, 9.0]]
scores = [5.0, 6.0, 5.0]
max_output_size = 1000000000000

tf.image.non_max_suppression_padded(
   boxes, scores, max_output_size, iou_threshold=0.5,
    score_threshold=float('-inf'), pad_to_max_output_size=True, name=None)
)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-06-17 15:25
@mjkim720,
I was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/8fa34dfa5f2649c6717708afa5ffba9d/40532.ipynb). However, the issue seems to be fixed with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/327bcc67c1e0f310feb39ca2b12b0642/40532-tf-nightly.ipynb#scrollTo=ZvE2D_WQv2Mk). 

On passing a large value, the code throws an `InvalidArgumentError` stating `InvalidArgumentError: Need k >= 0, got -727379968 [Op:TopKV2]`. Please check the linked gist. Thanks!

**Comment by mjkim720** [comment] 2020-06-17 18:03
@amahendrakar @mihaimaruseac Thank you for your feedback. It seems the segfault is gone in the nightly version, but the exception message is a bit misleading because it does not reflect the actual input. I passed a large positive value, but the exception message complains about a negative value, which is never given.  I suspect there is an overflow going on internally.

**Comment by rmothukuru** [comment] 2021-05-04 09:37
@mjkim720,
Upon running your code in the latest version of Tensorflow (2.4.1), I think proper error is being raised. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/e800797cb02ffb7b88988ec9ac5188ac/40532-tf-nightly.ipynb). Thanks!

**Closed** 2021-05-18 10:50 UTC
Labels: Fixed in Nightly, TF 2.2, comp:ops, stalled, stat:awaiting response, type:bug
