### ISSUE TITLE
map_fn removes a dimension

### ISSUE THREAD

**Issue by johnsrude** [tensorflow/tensorflow#20976] opened 2018-07-19 17:00 UTC
I am trying to remap values in an input Tensor using a defaultdict.

    class MyDataSet(object):
        def __init__(self):
            self.class_map = MyDataSet.remap_class()

        @staticmethod
        def remap_class():
            class_remap = defaultdict(lambda: 11)
            class_remap[128] = 0  
            class_remap[130] = 1  
            class_remap[132] = 2
            # ...

        def parser(self, serialized_example):
            features = tf.parse_single_example(
                serialized_example,
                features={
                    'image': tf.FixedLenFeature([], tf.string),
                    'label': tf.FixedLenFeature([], tf.string),
                })
            label = tf.decode_raw(features['label'], tf.uint8)
            label.set_shape([256 * 512])
            label = tf.cast(tf.reshape(label, [256, 512]), tf.int32)
    
            output_label = tf.map_fn(lambda x: self.class_map(x), label)

        #...
        dataset = tf.data.TFRecordDataset(filenames).repeat()
        dataset = dataset.map(self.parser, num_parallel_calls=batch_size)

The label shape is (256,512) but the output_label shape is (256,).  I can't change this shape with tf.reshape() or output_label.set_shape().

This seems to be a bug.

**Comment by tensorflowbutler** [comment] 2018-07-20 01:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment] 2018-07-23 17:55
Isn't that expected? For each sample you get the class?

**Comment by johnsrude** [comment] 2018-07-23 18:08
This are for semantic segmentation which is pixel-based, not box or column based.

**Comment by johnsrude** [comment] 2018-07-23 18:17
OS Platform and Distribution: Ubuntu 17.10

TensorFlow version: 1.8

CUDA/cuDNN version: 
Cuda compilation tools, release 9.0, V9.0.176 /
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
 
GPU model and memory: NVIDIA Titan V,  Driver Version: 387.34, 12057MiB

**Comment by drpngx** [comment] 2018-07-23 18:30
So the `class_map` takes `x, y` and returns one number? Or does it take `256 * x + y`?

**Comment by johnsrude** [comment] 2018-07-23 18:37
For each (x,y) class_map should take the value {0, 255} and translate it into another value {0, 255}

**Comment by drpngx** [comment] 2018-07-23 19:32
Could you print what comes out of `class_map` to make sure that's a 2d tensor maybe?

**Comment by johnsrude** [comment] 2018-07-23 19:43
It may be 2D but the shape is (256,).  And it won't let me reshape it.  I'm now using a workaround which is flattening the tensor to 1D, doing the mapping and then reshaping it to 2D.

**Comment by tensorflowbutler** [comment] 2018-08-07 19:05
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by drpngx** [comment] 2018-08-07 21:59
OK closing since there is a resolution. If you're unhappy about `class_map`, feel free to open another PR.

**Closed by drpngx** 2018-08-07 21:59 UTC

**Comment by KevinLucidyne** [comment] 2018-08-09 16:02
@drpngx  A question on class_map would be exactly the same question.

**Comment by drpngx** [comment] 2018-08-09 23:45
@KevinLucidyne that's fine.
