### ISSUE TITLE
"OverflowError: cannot serialize a bytes object larger than 4 GiB" when using model.fit([...], use_multiprocessing=True) on custom generator

### ISSUE THREAD

**Issue by philipp-ghtest** [tensorflow/tensorflow#39257] opened 2020-05-07 10:53 UTC
Hi,

I'm trying to train a model consisting of some GRU layers on data stored in a large numpy array (~18gb) on 2 GPUs using the MirroredStrategy.

My system:
* AMD Ryzen Threadripper 3960X 24-Core Processor 
* 64 GB RAM
* two NVIDIA GeForce RTX 2070 SUPER with 8192MiB each
* Win 10 (unfortunately, the ASrock Creator TRX40 motherboard we bought is currently incompatible with Linux, wtf...)
* TF 2.1.0 installed from binary (anaconda)
* Python 3.7.7
* CUDA Version 10.2.89

This is my code:

```python
import tensorflow as tf 
import numpy as np 

train_tokens_X = np.zeros((1066673, 61, 69), dtype=np.float32)
train_tokens_X[:] = np.eye(69)[:61,:]

train_target = np.zeros((1066673, 3943), dtype=np.float32)
train_target[:,2] = 1

valid_tokens_X= np.zeros((133366, 61, 69), dtype=np.float32)
valid_tokens_X[:] = np.eye(69)[:61,:]

valid_target= np.zeros((133366, 3943), dtype=np.float32)
valid_target[:,2] = 1

output_size = 3943
max_id = 68
batch_size = 256

class Sequencer(tf.keras.utils.Sequence):

    def __init__(self, x_set, y_set, batch_size):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size

    def __len__(self):
        return math.ceil(len(self.x) / self.batch_size)

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) *
        self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) *
        self.batch_size]

        return np.array(batch_x), np.array(batch_y)


train_generator = Sequencer(train_tokens_X, train_target, batch_size)
valid_generator = Sequencer(valid_tokens_X, valid_target, batch_size)

mirrored_strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())

with mirrored_strategy.scope():
    model = keras.models.Sequential([
        keras.layers.GRU(128, return_sequences=True, input_shape=[ None, max_id+1], use_bias=False),
        keras.layers.GRU(128, return_sequences=True, use_bias=False),
        keras.layers.GRU(128, use_bias=False),
        keras.layers.Flatten(),
        keras.layers.Dense(output_size, activation="softmax")
    ])
    model.compile(loss=[focal_loss_umbertogriffo.categorical_focal_loss(alpha=.25, gamma=2)], optimizer="adam", metrics=['accuracy'])

history = model.fit(train_generator, validation_data=valid_generator, epochs=25, callbacks = callbacks, max_queue_size=10, workers=2, use_multiprocessing=True)
```

and there it crashes with:

```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 844, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 823, in pool_fn
    initargs=(seqs, None, get_worker_id_queue()))
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\KI\anaconda3\envs\tensorflow_test\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

If trained without the `use_multiprocessing ` flag, training works seamlessly, but is very slow due to the generator overhead (I guess) with only ~10% load on each GPU and also ~10% on the CPU.

If trained without the using the generator at all (putting the data directly into model.fit), model.fit crashes due to memory issues:

`2020-05-07 12:46:43.785479: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 16823566556 exceeds 10% of system memory.`

...so I have to use a generator for memory efficiency.

I also tried to use a tf.data pipeline but the same `exceeds 10% of system memory` arises, unfortunately. 

What can I do here?

**Comment by ravikyram** [comment] 2020-05-08 05:56
@philipp-ghtest 

Will it be possible to share supporting data files to reproduce the issue in our environment.Thanks!

**Comment by philipp-ghtest** [comment] 2020-05-11 09:02
> @philipp-ghtest
> 
> Will it be possible to share supporting data files to reproduce the issue in our environment.Thanks!

My data is proprietary but I'll try to provide some fake data since training doesn't start anyways

**Comment by philipp-ghtest** [comment] 2020-05-11 10:20
> @philipp-ghtest
> 
> Will it be possible to share supporting data files to reproduce the issue in our environment.Thanks!

This code creates fake data with the same size and shape as the real data. This should do it for this purpose:

```
train_tokens_X = np.zeros((1066673, 61, 69), dtype=np.float32)
train_tokens_X[:] = np.eye(69)[:61,:]

train_target = np.zeros((1066673, 3943), dtype=np.float32)
train_target[:,2] = 1

valid_tokens_X= np.zeros((133366, 61, 69), dtype=np.float32)
valid_tokens_X[:] = np.eye(69)[:61,:]

valid_target= np.zeros((133366, 3943), dtype=np.float32)
valid_target[:,2] = 1

output_size = 3943
max_id = 68
```

**Comment by philipp-ghtest** [comment] 2020-05-14 08:38
Hey, any updates on this?

**Comment by philipp-ghtest** [comment] 2020-05-27 08:38
@ymodak @ravikyram any updates on this?

**Comment by ymodak** [comment] 2020-06-06 04:36
Apologies for the delay in response. I was able to reproduce crashing behavior using google colab. I have updated the repro code in the issue thread above. I will tag owners for this. Thanks!

**Comment by philipp-ghtest** [comment] 2020-06-17 12:44
> Apologies for the delay in response. I was able to reproduce crashing behavior using google colab. I have updated the repro code in the issue thread above.
> It fails without distribution strategy as well. I will tag owners for this.
> Thanks!

Thank you!

**Comment by tomerk** [comment] 2020-06-17 20:04
Hi @philipp-ghtest , sorry for the delay in getting to this!

So, if I'm correctly understanding this, the crux of your issue is you have a very large numpy array that you're trying to use performantly as your training/evaluation data. Using a large pre-built numpy array is generally unlikely to be the most performant way to process your data.

If you're looking to get peak performance, we suggest reading your data from disk (or generating it) directly as a tf.data dataset. Depending on how your data is stored, maybe you'll find useful utils in tensorflow.io:
github.com/tensorflow/io

You can also load csvs directly into a tf.data.dataset, and there's support for various other loading too.

---------------------

**Regarding the generator multiprocessing error:**
We recommend datasets for performance over trying to use a generator w/ multiprocessing.

I believe various objects have to be pickled/unpickled for python multiprocessing to work. because your generator holds a reference to the full numpy array, serializing/deserializing the closures means the whole numpy object has to be pickled/unpickled, so you're running into fundamental python limitations here.

-----------------

**Memory error when putting the data directly into model.fit**

The path in model.fit that handles numpy arrays directly is optimized for performantly handling *small* numpy arrays as quickly as possible, rather than minimizing memory usage. It ends up forcing a copy of your data converted to a tensor into memory, which is what's causing your crash.

Although we do recommend using tf.data instead of large numpy arrays, you're not the first person to have run into issues with this. We do have a separate path that can handle bigger arrays w/o forcing the data into memory, and I'll look into triggering that alternate path if we detect a numpy object is large.

**Comment by philipp-ghtest** [comment] 2020-06-18 14:02
Hi Tomer, 

thank you for your elaborate reply and all your helpful hints.
Since my code crashes when using tf.data on large numpy arrays (as I said, at first I get this 'exceeds 10% of system memory' and then it terminates without further notice...), I guess I have to redesign my preprocessing in order to avoid the large numpy arrays at all, but at least I have a way out now.

**Comment by saikumarchalla** [comment] 2021-05-24 01:04
@philipp-ghtest  Closing the issue as of now. Please feel free  to re-open the issue if you have any further quetions.Thanks!

**Closed by saikumarchalla** 2021-05-24 01:04 UTC
Labels: TF 2.1, comp:keras, type:bug
