### ISSUE TITLE
TPU train_on_batch stride size error

### ISSUE THREAD

**Issue by maxima120** [tensorflow/tensorflow#29839] opened 2019-06-16 12:09 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5
- GPU model and memory: TPU v3-8

**Describe the current behavior**

Code and data which **runs fine on CPU**, _throws error on TPU_. This only happens if I use train_on_batch instead of fit.

I have 2 versions of same model. One is with fit with 2 loops and with **train_on_batch** with 3 loops (epoch, day worth of data, batch within day)

train_on_batch throws error: `slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.`

0111 data is label provided in y2. and the size of 4 is correct. Why is computed input tensor is size 3 I don't understand. It looks like a bug very much.

Model
```
model = tf.keras.Sequential()
model.add(layers.LSTM(neurons, input_shape=(window_size, inputs_n), return_sequences=True)) 
model.add(layers.LSTM(neurons))
model.add(layers.Dense(outputs_n, activation='sigmoid'))

opt = tf.train.AdamOptimizer(0.001)

model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])
 
tpu_model = tf.contrib.tpu.keras_to_tpu_model(model, 
        strategy=tf.contrib.tpu.TPUDistributionStrategy(
            tf.contrib.cluster_resolver.TPUClusterResolver(tpu = [TPU_ADDRESS1])))
```
Shapes
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_input (InputLayer)      (None, 1024, 7)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 1024, 128)         69632     
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dense (Dense)                (None, 4)                 516       
=================================================================
```
Training:
```
for epoch in epochs:
    for d in days : 
        # get arrays for the day
        features = np.asarray(d[1])[:,2:9].astype(dtype = 'float32')
        labels = np.asarray(d[1])[:, 9:13].astype(dtype = 'int32')
        
        X,y = split_sequence(features, labels_buy, window_size)

        # train 
        for slide in range(window_size):
            try:
                x1, y1 = X[slide], y[slide]
                x2, y2 = x1.reshape(1,1024,7), y1.reshape(1, 4)
                H = tpu_model.train_on_batch(x2,y2)
            except Exception as e:
                print('** train exception **', e)
                continue
```
**Describe the expected behavior**

train_on_batch trains without exception

**Comment by gadagashwini** [comment] 2019-06-17 09:12
@maxima120 Please provide the complete code snippet to reproduce the issue reported here. And also include the error log. Thanks!

**Comment by maxima120** [comment] 2019-06-17 12:12
how do I send it to you? data file is big

**Comment by gadagashwini** [comment] 2019-06-18 10:21
@maxima120 Will it be possible to provide minimal code snippet with all the operations to expedite the trouble-shooting process. Thanks!

**Comment by maxima120** [comment] 2019-06-18 21:20
Yes but you need to tell me how do I send it to you. Data is a large file

**Comment by ymodak** [comment] 2019-06-21 17:38
The code snippet attached here is complete. Can you please make a GitHub gist or Google Colab with your example? Thanks!

**Comment by maxima120** [comment] 2019-06-22 15:18
https://gist.github.com/maxima120/63e1cdca833264afb4192120b72d2225

**Comment by maxima120** [comment] 2019-06-22 15:34
this reproduces the issue:
https://gist.github.com/maxima120/d1057a0e4bbf2ae2a1434dad57999a3f

**Comment by maxima120** [comment] 2019-06-27 15:54
you are awaiting for a flower? do you want me to send you a bunch of roses? ;)

**Comment by frankchn** [comment] 2019-06-28 00:43
@maxima120 I've reassigned it to folks more familiar with the code, but with TensorFlow 1.14, can you try distribution strategy instead? That is a more complete implementation: https://www.tensorflow.org/guide/distribute_strategy#using_tfdistributestrategy_with_keras

**Comment by rjpower** [comment] 2019-07-08 16:18
Sorry for the delay. It looks like `train_on_batch` hasn't been overridden properly in the `keras_to_tpu_model` code. As Frank mentions, it would great if you can try using the DistributionStrategy approach instead: that has better support as of TF 1.14.

**Comment by maxima120** [comment] 2019-07-09 11:31
Used GCP image: Debian with TF 1.14.0-rc0

Code:
```
resolver = tf.distribute.cluster_resolver.TPUClusterResolver([TPU_ADDRESS1])
tf.tpu.experimental.initialize_tpu_system(resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(resolver)

# build model
with tpu_strategy.scope():
    model = tf.keras.Sequential()
    model.add(layers.LSTM(neurons, input_shape=(window_size, inputs_n), return_sequences=True)) 
    model.add(layers.LSTM(neurons))
    model.add(layers.Dense(neurons, activation='relu'))
    model.add(layers.Dense(outputs_n, activation=activation))

    opt = tf.train.RMSPropOptimizer(learning_rate)

    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])

    X,y = split_sequence(features, labels, window_size)
    print('X shape:', X.shape, 'Y shape:', y.shape)
    for slide in range(window_size):
        x1, y1 = X[slide], y[slide]
        x2, y2 = x1.reshape(1,window_size,inputs_n), y1.reshape(1,outputs_n)
        model.train_on_batch(x2,y2)
```
got output:
```
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0709 11:29:14.795013 140573481281280 deprecation.py:506] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
X shape: (9000, 1000, 7) Y shape: (9000, 4)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-0f3e39e3b63e> in <module>
     33         x1, y1 = X[slide], y[slide]
     34         x2, y2 = x1.reshape(1,window_size,inputs_n), y1.reshape(1,outputs_n)
---> 35         model.train_on_batch(x2,y2)
     36 
     37 print(model.metrics_names)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1146     if (self._distribution_strategy and
   1147         distribution_strategy_context.in_cross_replica_context()):
-> 1148       raise NotImplementedError('`train_on_batch` is not supported for models '
   1149                                 'distributed with tf.distribute.Strategy.')
   1150     # Validate and standardize user data.

NotImplementedError: `train_on_batch` is not supported for models distributed with tf.distribute.Strategy.
```

**Comment by maxima120** [comment] 2019-07-27 19:36
@rjpower - I tried your suggestion but got similar error (_train_on_batch` is not supported.. with tf.distribute.Strategy_) - see above.. any other suggestions?

**Comment by IIIBlueberry** [comment] 2019-07-29 17:09
@rjpower @frankchn train_on_batch is broken on tensorflow 1.14.0
check this link https://stackoverflow.com/questions/56741126/using-train-on-batch-on-colab-tpu-new-tensorflow-version-1-14

**Comment by maxima120** [comment] 2019-07-29 17:19
Thank you. But this is about TF 1.13
I am not going to use 1.14 ever. I am just waiting for 2.0 being mature and TPUs are implemented..
They are moving like facebook now - move fast break things (translation to English - no quality just ticking checkboxes in managerial reports)

**Comment by rjpower** [comment] 2019-07-30 00:39
Sadly, the original Keras API you're using was always intended as an experimental stop-gap (hence being marked as `@experimental` in the API signature). DistributionStrategy is intended as it's replacement. I'm not sure at the moment if the missing support for `train_on_batch` is "we haven't gotten to it yet", or if it's "we can't get to it".

I can check on that, but I think in the meantime, the easiest thing to do (albeit a bit of a kludge)  is to try `.fit` API and give it a single batch. For more custom use cases, I believe the intended idea is a "custom training loop". It looks something like this [[code](https://github.com/tensorflow/tpu/blob/4d7f7bf76df200a6dd74b01a6dbb95d8b013ecfe/models/common/distributed_executor.py#L165)]:

```
   def train_one_step(inputs):
        inputs, labels = inputs

        with tf.GradientTape() as tape:
          logits = model(inputs, training=True)
          prediction_loss = loss_fn(labels, logits)
          logging.info('debug prediction_loss %s', prediction_loss)
          loss = tf.reduce_mean(prediction_loss)
          loss = loss / strategy.num_replicas_in_sync
          return loss

        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

      per_replica_losses = strategy.experimental_run_v2(_replicated_step, args=(next(iterator),))
      return strategy.reduce(tf.distribute.ReduceOp.MEAN, per_replica_losses, axis=None)
```

RE timelines: I'm inclined to agree -- TF 2.0 should have a more mature distribution strategy and better support for Keras TPUs. FWIW, Keras TPU support has never been a supported feature prior to TF 2.0 (though I can see good arguments for why it should have been prioritized earlier).

**Comment by maxima120** [comment] 2019-07-30 22:07
Thank you I will try it.
Re: TF 2.0 - I would gladly switch but I read 2.0 beta doesn't have tpu support whatsoever. Is it wrong?

**Comment by rjpower** [comment] 2019-08-01 19:00
I know that 2.0 final is expected to have full TPU support. That said,
development is still under way and many things aren't quite ready yet. I'd
wait until at least the first RC before trying anything TPU+2.0 related in
earnest.

(I don't work closely with the teams so take this with a grain of salt...)

**Comment by rjpower** [comment] 2020-01-10 18:00
Apologies for the long delay: TensorFlow 2.1 is now out, and now supports TPUs via DistributionStrategy. Documentation is somewhat sparse, but here's an example:

https://colab.sandbox.google.com/github/tensorflow/tpu/blob/master/tools/colab/fashion_mnist.ipynb

**Closed by rjpower** 2020-01-10 18:00 UTC
Labels: TF 1.13, comp:tpus, type:bug
