### ISSUE TITLE
TensorBoard maybe timeout when show imagenet inception-3 event

### ISSUE THREAD

**Issue by zdx3578** [tensorflow/tensorflow#716] opened 2016-01-07 09:25 UTC
when i run imagenet example ; in tensorflow/models/image/imagenet/classify_image.py i add

+    w=tf.python.training.summary_io.SummaryWriter( sess.graph_def, FLAGS.model_dir, 'graph.pbtxt')  
+    tf.train.SummaryWriter.flush(w)
+    tf.train.SummaryWriter.close(w)

output a file: events.out.tfevents.1452154974.ip-172-30-.-.
when i open tensorboard , in tab  graph ,then i check top,tensorboard use cpu 100%; but wait a while ,tensorboard cpu use is down; tensorboard log a http 200:"GET /graph?run=%2Fopt%2Fpractice%2Ftf%2Fimagenet%2Flog%2F HTTP/1.1" 200 ;

maybe event file so big cause http timeout?? 
92M Jan  7 09:01 log/events.out.tfevents.1452154974.ip-172-30

any one can help?

**Comment by zdx3578** [comment] 2016-01-07 09:32
i will check cifar-10 example for what missing?

**Comment by frankyjuang** [comment] 2016-01-15 19:47
@zdx3578 so the graph page displays nothing?

**Comment by girving** [comment] 2016-03-08 19:20
@danmane: Do you know if this is still an issue?

**Comment by danmane** [comment] 2016-03-15 00:28
This looks like a duplicate of #1287 , which is fixed as of latest master. @zdx3578 if the fix for #1287 doesn't work for you, feel free to re-open and we'll dig into it a bit more - if you do re-open it, can you please upload an events file for which you aren't able to visualize the graph? That will make it a lot easier to dig into.

**Closed by danmane** 2016-03-15 00:28 UTC
