### ISSUE TITLE
Bug in saving model in hdf5 format

### ISSUE THREAD

**Issue by sonu1-p** [tensorflow/tensorflow#33888] opened 2019-10-31 16:23 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs Mojave version 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When try to save the below model in keras format, we get the following error:
ValueError: Unable to create group (name already exists)

This happens as this model has three layers with name as below:
tf_op_layer_Pad/paddings/0
tf_op_layer_Pad/paddings
tf_op_layer_Pad

Such name causes error in keras as described here - https://github.com/keras-team/keras/issues/12195

**Describe the expected behavior**
Model saving should not fail.

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras

x = keras.Input(shape=(None,10), dtype="int32", name="input")
T = tf.shape(x)[0]
to_pad = -T % 2
y = tf.pad(x, [[0, to_pad], [0, 0], [0, 0]])
model = keras.Model(inputs=[x,], outputs=[y,])
model.save("model.h5")
```

**Other info / logs**
This fix for this has been checked into keras few days ago it seems - https://github.com/keras-team/keras/pull/13477/commits/7dee298ebec503c6b0e1727dfd49b89a3fb002d7

But it seems TF has its own copy of this hdf5 saving, so it seems this fix will also have to be made there -
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/hdf5_format.py#L624

**Comment by ymodak** [comment] 2019-11-01 19:59
Saving the model to TensorFlow format (tf) works where as hdf5 saving fails with TF nightly version '2.1.0-dev20191101'
```python
import tensorflow as tf
from tensorflow import keras

x = keras.Input(shape=(None,10), dtype="int32", name="input")
T = tf.shape(x)[0]
to_pad = -T % 2
y = tf.pad(x, [[0, to_pad], [0, 0], [0, 0]])
model = keras.Model(inputs=[x,], outputs=[y,])
model.save("models.tf")
```

**Comment by vmarkovtsev** [comment] 2019-11-04 09:37
We need to backport https://github.com/keras-team/keras/pull/13477

**Comment by vmarkovtsev** [comment] 2019-11-04 09:38
I believe this is a duplicate of https://github.com/tensorflow/tensorflow/issues/33565

**Comment by jwyyy** [comment] 2020-01-22 02:57
I have the same problem using TF 2.1.0. Calling keras from tensorflow will lead to the same error. As mentioned by @sonu1-p , TF hasn't updated its own copy of this hdf5 saving.

**Closed** 2020-01-29 00:03 UTC
Labels: TF 2.0, comp:keras, type:bug
