### ISSUE TITLE
Distributed training with SyncReplicasOptimizer may throw session close error after training 

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#21630] opened 2018-08-15 09:51 UTC
### System information

== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.14.2
protobuf                           3.5.2.post1
tensorflow                         1.8.0
tensorflow-hub                     0.1.0
tensorflow-model-analysis          0.6.0
tensorflow-serving-api             1.8.0
tensorflow-tensorboard             1.5.0
tensorflow-transform               0.6.0
tensorflowjs                       0.1.0
tensorflowonspark                  1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 106: nvidia-smi: command not found

== cuda libs  ===================================================

== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy                              1.14.2
protobuf                           3.5.2.post1
tensorflow                         1.8.0
tensorflow-hub                     0.1.0
tensorflow-model-analysis          0.6.0
tensorflow-serving-api             1.8.0
tensorflow-tensorboard             1.5.0
tensorflow-transform               0.6.0
tensorflowjs                       0.1.0
tensorflowonspark                  1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 106: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

We have used `MonitoredTrainingSession` and  `SyncReplicasOptimizer` for distributed sync training. All the master(the worker with index 0) and workers will work synchronously. But at the end of master process, it throw `CancelledError` while trying to close the session. Sometimes we re-run all the processes and the error will not be thrown.

<img width="1439" alt="screen shot 2018-08-15 at 5 37 58 pm" src="https://user-images.githubusercontent.com/2715000/44142776-dbe72ba0-a0b3-11e8-892f-dc3012fde656.png">

### Source code / logs

Above.

**Comment by tensorflowbutler** [comment] 2018-08-15 19:12
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by bignamehyp** [comment] 2018-08-30 22:45
Please provide more details and steps to reproduce.

**Comment by tensorflowbutler** [comment] 2018-09-14 12:39
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 20:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-09-28 20:37 UTC
Labels: stat:awaiting response
