### ISSUE TITLE
Interesting bug, in keras, tf.shape not compatible with tensor.get_shape()

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#35385] opened 2019-12-24 11:48 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- TensorFlow installed from (source or binary):conda binary
- TensorFlow version (use command below):2.0
- Python version:3.7
- CUDA/cuDNN version:430
- GPU model and memory:2 * 24GB Titan RTX

I found this bug is very interesting.

For example:

> a = tf.ones([1, 512, 512, 3])
> b = tf.ones([1, 256, 256, 3])
> c = tf.ones([1, 1, 1, 3])
> 
> a_size = tf.shape(a)[1:3]
> b = tf.resize(b, size = a_size)
> 
> b_size = b.get_shape()[1:3]
> c = tf.resize(c, size = b_size) # Bug line

In the last line (bug line). if the model is run eagerly, it is okay. However, if run with keras.fit (Graph mode I guess), it will give the error "**raise ValueError('\'size\' must be a 1-D int32 Tensor')**"

**Comment by gadagashwini** [comment] 2019-12-26 08:32
@edwardyehuang, Thanks for reporting the issue.
Could you post the complete code snippet to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2020-01-10 06:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-01-10 06:55 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support
