### ISSUE TITLE
Tensorflow GPU installation issues

### ISSUE THREAD

**Issue by Supergitter123** [tensorflow/tensorflow#25984] opened 2019-02-21 20:07 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Through PyCharm virtualenv
- TensorFlow version: 1.12.0
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10 / cuDNN 7.4.2
- GPU model and memory: GeForce GTX 1050 Ti

Trying to install and run tensorflow gpu version. I have installed CUDA and cuDNN and run the deviceQuery sample with what seems like good results (picture attached). I have installed tensorflow and Keras through PyCharm and when I try to run the following two lines to see if TF is installed correctly I get the following error message:

import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

Traceback (most recent call last):
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Mr.Jones/Documents/Master Thesis/Offline_models/define_models_Jonas.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mr.Jones\Documents\Master Thesis\Offline_models\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

![image](https://user-images.githubusercontent.com/17160539/53198308-626ff780-361c-11e9-80bb-5490b771776c.png)

**Comment by ymodak** [comment] 2019-02-22 03:03
I see that you have cuda 10 installed. Please switch to TensorFlow 1.13.0-rc2 as it supports cuda 10.

**Comment by Supergitter123** [comment] 2019-02-24 20:39
I installed TensorFlow 1.13.0-rc2 but still got the same error

**Comment by ymodak** [comment] 2019-02-26 00:05
Did you update the cuda, cudnn path as per the [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup)?

**Comment by Supergitter123** [comment] 2019-02-26 21:29
Yee cuda, cudnn together with the correct paths are added as described in the guide.

Can there be any problem due to me trying to run it all in PyCharm?

**Comment by ymodak** [comment] 2019-02-26 21:42
Yes its possible that PyCharm interpreter is missing those paths. Are you able to import tensorflow using your terminal?

**Comment by Supergitter123** [comment] 2019-03-03 21:40
I tried it today but ended up with the same error: 

Traceback (most recent call last):
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Test1.py", line 1, in <module>
    import tensorflow
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mr.Jones\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment] 2019-03-04 22:05
Can you attach a screenshot showing environment variables to cuda path?
This issue is a duplicate of #26059 . Please take a look. Thanks!

**Comment by ymodak** [comment] 2019-03-08 21:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-08 21:39 UTC
Labels: stat:awaiting response, subtype:cuda, subtype:windows, type:build/install

**Comment by Supergitter123** [comment] 2019-03-10 16:56
![image](https://user-images.githubusercontent.com/17160539/54088373-cb19dc80-435d-11e9-9688-352225726db0.png)
There is a screenshot of it, I tried to re-install everything today but still no luck

**Comment by Supergitter123** [comment] 2019-03-10 17:24
Additionally I've managed to install tensorflow cpu on a laptop and it works fine there. Neither cpu or gpu is working on my stationary though...

**Comment by ymodak** [comment] 2019-03-12 03:07
You need to add sub folders: ```bin``` , ```include``` and ```lib``` to the path. I see that ```lib``` and ```include``` folder's are not added to the path. Can you please try adding them as well?

**Comment by Supergitter123** [comment] 2019-03-12 06:29
These might have been removed during one of the re-installations. Both are added again but I wasn't sure if it was lib or lib\x64 so both are added:

![image](https://user-images.githubusercontent.com/17160539/54179199-6616d180-4498-11e9-8a26-1b3a410d800f.png)

However it still gives me the same error. What feels strange is that I can't even get tensorflow cpu version to run
