### ISSUE TITLE
Keras Backend ones_like with Lambda is not serializable

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#43745] opened 2020-10-02 20:58 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Databricks Runtime 7.3
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): 2.3
- Python version: 3
- CUDA/cuDNN version: 10.1
- GPU model and memory: AWS p3.xlarge

**Describe the current behavior**
Wrapping a `tf.keras.backend.ones_like` in a `tf.keras.layer.Lambda` fails serialization.

The following code creates the model that fails to serialize:
```python
x = keras.Input(shape=1, name="x")
ones_like_layer = keras.layers.Lambda(K.ones_like, name="ones_like")
ones_like_layer(x)
logits = keras.layers.Dense(1, activation="sigmoid")

model = keras.Sequential([x, ones_like_layer, logits], name="ones_like_model")
```

Errors:
```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in wrapper(*args, **kwargs)
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
TypeError: 'str' object is not callable
During handling of the above exception, another exception occurred:
TypeError                                 Traceback (most recent call last)
11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in wrapper(*args, **kwargs)
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a
    204       # TypeError, when given unexpected types.  So we need to catch both.
--> 205       result = dispatch(wrapper, args, kwargs)
    206       if result is not OpDispatcher.NOT_SUPPORTED:
    207         return result
TypeError: 'module' object is not callable
````

This happens on TF 2.3 and TF Nightly.  See https://colab.research.google.com/drive/1ih41e5b6jw_3iSm9pKSOcW_Kf5y8ktU5?usp=sharing .

**Describe the expected behavior**
The model should be serializable.

**Standalone code to reproduce the issue**
See above.

**Other info / logs** Include any logs or source code that would be helpful to
Workaround - instead of using the `Lambda`, just call `ones_like` directly.  This works but leads to the model being less interpretable.  This requires using the Functional model.

See also: https://github.com/tensorflow/tensorflow/issues/41244#issuecomment-698918718

**Comment by amahendrakar** [comment] 2020-10-05 09:19
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4cb86c00223e42eab4fbbd7d7b4a3b70/43745.ipynb). Thanks!

**Comment by jeisinge** [comment] 2020-10-12 21:18
FYI - `tf.ones_like` also suffers from this serialization issues as well.

A workaround is:
```python
class OnesLike(keras.layers.Layer):
  def call(self, x):
    return K.ones_like(x)
```

**Comment by nikitamaia** [comment] 2021-03-15 14:42
Adding the `contributions welcome` label to this issue for further investigation by the community. If you are interested in working on this issue, please leave a comment and I will assign it to you. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-04-06 23:16
@jeisinge When I update one line (Lambda layer), everything worked without any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/00813ad0f5980624a1d6d1f937fa6022/43745.ipynb)

line before 

`ones_like_layer = keras.layers.Lambda(K.ones_like, name="ones_like")`

line after updating

`ones_like_layer = keras.layers.Lambda(lambda x:K.ones_like(x), name="ones_like")`

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by jeisinge** [comment] 2021-04-08 12:56
Unfortunately, I am still seeing the error in my production on TF 2.3.1.

With that being said, I just tested on Colab.  This workaround works on 2.3.0+ just like the `OnesLike` workaround.

The original code still fails on tf-nightly.  Is it required to use a Python `lambda` in a Lambda layer?  I thought that any functions would work there?

**Comment by bhack** [comment] 2021-04-14 12:48
@nikitamaia With @tomerk commit https://github.com/tensorflow/tensorflow/commit/229cbce4caa531b9f9695e98b38909dfeed234aa on TF master/2.5.0x now we claim:
```
The `Lambda` layer exists so that arbitrary expressions can be used
  as a `Layer` when constructing `Sequential`
  and Functional API models. `Lambda` layers are best suited for simple
  operations or quick experimentation. For more advanced use cases, follow
  [this guide](https://www.tensorflow.org/guide/keras/custom_layers_and_models)
  for subclassing `tf.keras.layers.Layer`.
```
```
  WARNING: `tf.keras.layers.Lambda` layers have (de)serialization limitations!
```

So can we clarify with the team what we want to achieve here with a candidate PR?

|  jeisinge: Is it required to use a Python lambda in a Lambda layer? I thought that any functions would work there?

E.g. not all the lambda functions can be easy expressed inline (control flow etc..).

**Comment by qlzh727** [comment] 2021-04-20 21:18
@tomerk, the docstring was updated in https://github.com/tensorflow/tensorflow/commit/229cbce4caa531b9f9695e98b38909dfeed234aa. Could we make it bit explicit for what limitation it could have?

**Comment by bhack** [comment] 2021-04-20 21:22
It could be nice if we explain why we have this current limitation and if we want any contribution on this specific topic.

**Comment by ashutosh1919** [comment] 2021-05-19 16:18
After looking at the above comments, I analysed the code by going in depth function call trace.

I compared below two scenarios:
Serializability of model is affected based on previous layer.
`model = keras.Sequential([ones_like_layer, logits], name="ones_like_model")` is serializable but `model = keras.Sequential([x, ones_like_layer, logits], name="ones_like_model")` is not.

The `Lambda` layer seems serializable but when `Input` layer is passed before `Lambda` . In that case, the FullArgSpec of `ones_like` before and after are as below:
#### Before
```
FullArgSpec(args=['tensor', 'dtype', 'name', 'optimize'], varargs=None, varkw=None, defaults=(None, None, True), kwonlyargs=[], kwonlydefaults=None, annotations={})
```
#### After
```
FullArgSpec(args=[], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
```

### Observations
- `generic_utils.func_dump()` and `generic_utils.func_load()` looks good and the error can't be there.
- The closures are different in both the cases (before and after) for dumped function code. The closure before looks like `(<function ones_like at 0x7f9ea3d35290>, <function ones_like at 0x7f9ea3d35320>)` and closure after looks like `['ones_like', 'ones_like']`. This may be the problem but I am not sure yet why and how.

@bhack , @qlzh727, @jvishnuvardhan - Can you point me to the direction where error can be?

**Comment by sachinprasadhs** [comment] 2021-05-28 11:34
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210528, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/0e2d302f2507a44ca3aa74062f8f3041/43745.ipynb). Thanks!

**Comment by bhack** [comment] 2021-05-28 12:50
I think that you need to use something like:
```python
import tensorflow as tf
from tensorflow import keras
x = keras.layers.Input(shape=(1), name="input_layer")
ones_like_layer = keras.layers.Lambda(lambda x: tf.ones_like(x), name="ones_like")
ones_like_layer(x)
logits = keras.layers.Dense(1, activation="sigmoid")
model = keras.Sequential([x, ones_like_layer, logits], name="ones_like_model")
keras.models.model_from_json(model.to_json())
```

Also from the documention:
> Variables: While it is possible to use Variables with Lambda layers, this practice is discouraged as it can easily lead to bugs. For instance, consider the following layer:
python scale = tf.Variable(1.) scale_layer = tf.keras.layers.Lambda(lambda x: x * scale)
Because scale_layer does not directly track the scale variable, it will not appear in scale_layer.trainable_weights and will therefore not be trained if scale_layer is used in a Model.
A better pattern is to write a subclassed Layer:
```python 
class ScaleLayer(tf.keras.layers.Layer): def init(self): super(ScaleLayer, self).init() self.scale = tf.Variable(1.)
  def call(self, inputs):
    return inputs * self.scale
```

> In general, Lambda layers can be convenient for simple stateless computation, but anything more complex should use a subclass Layer instead.

**Comment by mohantym** [comment] 2021-11-25 11:55
Hi @jeisinge! I just made few changes according to this [thread](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Lambda#variables)  in lambda layer as below. 
`ones_like_layer = keras.layers.Lambda(lambda x:K.ones_like(x), name="ones_like")` and I was able resolve this issue in 2.7. Attaching [Gis](https://colab.research.google.com/gist/mohantym/c6adf0691b30d41ad1e6050a44838c49/43745.ipynb#scrollTo=1WYW-rQkfCuQ)t for reference .Thanks!

**Comment by jeisinge** [comment] 2021-12-07 18:48
Correct.
```python
ones_like_layer = keras.layers.Lambda(lambda x: K.ones_like(x), name="ones_like")
```
Succeeds.

However, the original issue,
```python
ones_like_layer = keras.layers.Lambda(K.ones_like, name="ones_like")
```
fails.  The workaround is fine for me.  Feel free to close out or add extra documentation!

**Comment by mohantym** [comment] 2021-12-08 16:44
Ok @jeisinge ! Thanks for confirming the same! Closing this issue as it seems to be resolved.

**Closed by mohantym** 2021-12-08 16:44 UTC
Labels: type:bug, comp:keras, TF 2.3
