### ISSUE TITLE
Cleanup Bazel Cache in Dockerfile

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4116] opened 2016-08-31 03:01 UTC
Right now I see the following in the Docker image:
```
--- /root/.cache/bazel/_bazel_root ---------------------------------------------------------------------------------------------------------------------------------------------------------
                        /..
    2.3GiB [##########] /68a62076e91007a7908bc42a32e4cff9
   84.3MiB [          ] /install
```
which leads to a very large Docker image.

**Comment by cancan101** [comment] 2016-09-06 17:57
Ping? This seems to cut down the size of the image >1GB.

**Comment by craigcitro** [comment] 2016-09-06 21:14
So we actually did this on purpose; totally worth discussing whether or not it's still a good idea. 😉 @vrv @danmane @martinwicke as some folks who may have opinions.

**Why?** The files here make it so that a freshly run container can run a `bazel build` without first having to rebuild the universe. This is explicitly trading bandwidth for computation time, which we thought was worthwhile. If someone doesn't need to fiddle with TF code, we have the non-devel builds; if they do, this saves time.

@cancan101 Just to ask, how are you using the devel builds? Does saving build time help you?

**Comment by cancan101** [comment] 2016-09-06 22:03
I am using the Docker image as the environment on a cluster. That means the first time I run a job on a new node, it has to pull the docker image.

**Comment by craigcitro** [comment] 2016-09-06 22:10
What are you doing once the machines start up in the cluster? Do they just need the TF library to be available, or are you building something from source?

If they just need TF to be available, you can switch from `gcr.io/tensorflow/tensorflow:devel` to just `gcr.io/tensorflow/tensorflow`, which is a much smaller image (even beyond dropping the bazel cache).

**Comment by cancan101** [comment] 2016-09-06 22:20
I am using the GPU image. Is there a Dockerfile that I can build myself?

**Comment by craigcitro** [comment] 2016-09-06 22:24
`gcr.io/tensorflow/tensorflow:gpu` should be the image you're looking for. All the existing dockerfiles are in [tensorflow/tools/docker](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker).

**Comment by cancan101** [comment] 2016-09-06 22:36
I would like to build myself since I am would like to build with compute capabilities 3.0 and 3.7.

**Comment by craigcitro** [comment] 2016-09-06 22:46
SGTM -- I think @caisq is the person to ask here, since he wrote [this build script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/parameterized_docker_build.sh). In particular, I think there's a correct set of params to pass there to get precisely what you want: maybe just `GPU` and `NO` for the first two?

**Comment by cancan101** [comment] 2016-09-06 22:54
I'm not sure what you are suggesting here? I am currently building the Docker image gpu-devel. It looks like the other image expects to install a prebuilt wheel. I like the ability to build from scratch and not rely on e[xternal files](https://github.com/tensorflow/tensorflow/blob/891f8f73cc1967a5c2da89057884bc3dc1f9091a/tensorflow/tools/docker/Dockerfile.gpu#L45).

I was trying to suggest a way of cutting down the size of this image. Perhaps there is a better image for what I want, but so far the ones I am seeing are just wrappers around prebuilt binaries.

**Comment by craigcitro** [comment] 2016-09-06 23:09
Ah, I think I probably left out a bit of detail.

As you mentioned, what you want is to build the equivalent of the `tensorflow:gpu` build, but with custom flags (different compute capability support), and without depending on the existing `.whl` file on `storage.googleapis.com`. 

The way the `:gpu` image is built is by
1. building the `tensorflow:devel-gpu` container, 
2. producing a new `.whl` file from that container, 
3. copying it to `storage.googleapis.com`, and 
4. building the `tensorflow:gpu` image with that newly-created file.

What you want is a variant of this, where you do (1) and (2) with custom options, but then directly go to (4) without copying the file to `storage.googleapis.com` at all. 

I believe the linked build script does precisely that, since that's what happens in the process of doing our CI builds; the only question is getting the flags right. I was thinking you could just make use of that script, since then you don't end up owning your own set of custom build scripts.

That said, you're totally welcome to write your own if that's easier for you.

**Comment by cancan101** [comment] 2016-09-06 23:16
The linked ci script might be overkill (?) for this. I would imagine this can be boiled down 
1. docker build gpu-devel
2. docker run with volume to copy out the wheel
3. docker build of the gpu image with the wheel in the build context

My initial hope was that with sufficient cleaning of the bazel cache, I could get by with just doing step 1 and having an imagine that was "small enough".

**Comment by craigcitro** [comment] 2016-09-06 23:46
Yeah, that makes sense. I'm not sure what the shortest path is, since squash support seems to be [stuck in committee](https://github.com/docker/docker/pull/22641).

It's actually not so bad to do this by flattening an existing container -- it mostly amounts to dropping some files and doing `docker export <big-container> | docker import - <flat-container>` (it's how we built containers for TF at one point long ago). I'm happy to sketch that out if you're interested, but you already be tired of my "easy solutions" from above. 😉

**Comment by jart** [comment] 2016-10-15 09:11
I'm closing this issue due to inactivity. I'll open this again if the issue is updated with new information.

One thing you'll be pleased to hear @cancan101 is that I managed to cut down the disk size used by Bazel by a few hundred megs in 65038b084059cf934df50fa86dba5b0e765f9d65 on September 21st.

**Comment by jart** [comment] 2016-10-15 09:12
Apologies, I failed to notice this was assigned. Re-opening.

**Comment by caisq** [comment] 2016-10-19 03:07
Fixed by https://github.com/tensorflow/tensorflow/commit/8a724211a9d4871338afe874276abf1d358f799b

Thank you for the suggestion, @cancan101 

Docker image size reduction is already reflected in the tensroflow/tensorflow:nightly* tags on Docker Hub, and will be reflected in tensorflow/tensorflow:latest* tags on next release.

**Closed by caisq** 2016-10-19 03:07 UTC
Labels: awaiting response
