### ISSUE TITLE
AttributeError: 'module' object has no attribute 'pack'

### ISSUE THREAD

**Issue by cdjhz** [tensorflow/tensorflow#7550] opened 2017-02-16 03:50 UTC
Training images using keras with tf backend.The error shows that tf (version==0.12.head) has no attribute "pack".
```python
Traceback (most recent call last):
  File "binary_convnets.py", line 30, in <module>
    model.add(Flatten())
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 324, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 155, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 440, in call
    return K.batch_flatten(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 862, in batch_flatten
    x = tf.reshape(x, tf.pack([-1, prod(shape(x)[1:])]))
AttributeError: 'module' object has no attribute 'pack'
```

**Comment by zhaopku** [comment] 2017-02-16 06:02
As far as I know, `tf.pack` has been renamed as `tf.stack`.

**Comment by aselle** [comment] 2017-02-18 22:48
Yes, the keras needs to be updated since this is renamed to stack in tf 1.0.
@fchollet, what's the best way to handle this?

**Comment by fido2478** [comment] 2017-02-20 19:17
I have the same issue. I've upgraded to tensorflow version 1.0 and then tried to run a python program that uses keras like this
from keras.models import Sequential
from keras.layers import Flatten, Dense

and then brought out this:

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "clone.py", line 24, in <module>
    models.add(Flatten(input_shape=(160, 320, 3)))
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/models.py", line 280, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/layers/core.py", line 409, in call
    return K.batch_flatten(x)
  File "/home/hahnsang/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 825, in batch_flatten
    x = tf.reshape(x, tf.pack([-1, prod(shape(x)[1:])]))
AttributeError: module 'tensorflow' has no attribute 'pack'

**Comment by aselle** [comment] 2017-02-21 16:58
I apologize, but I'm confused now. If the issue is resolved please close it. If not, please re-state exactly what is still wrong and what you would like fixed. Thanks so much!

**Comment by tawantinsuyu** [comment] 2017-02-23 17:51
I am having this problem as well. I pip installed tensorflow in anaconda with python3 environment. Can we revert anaconda to an earlier version of tensorflow to at least temporarily get around this?

**Comment by aselle** [comment] 2017-03-03 23:38
@tawantinsuyu, unfortunately no, we won't downgrade the default version, because that would break users who already updated. To use an older version, an easy way is to use docker. You can also find the previous .whl from our web site and install that, but we don't recommend that. Good luck. Thanks!

**Comment by aselle** [comment] 2017-03-03 23:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2017-03-03 23:38 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:bug/performance

**Comment by xiezhongzhao** [comment] 2017-06-09 09:05
I have the same problem, my version of tensorflow is 1.0.1, I changed the 'pack' into 'stack', but it did't work. I hope you can help me @zhaopku

**Comment by g07kore** [comment] 2018-07-03 18:09
I had the same issue with TensorFlow. I solved it by installing keras.

**Comment by Somayeh12** [comment] 2019-02-01 17:33
Any solution to this problem? I am having the same problem. tensorflow 1.13, python 3.6.
I replaced tf.pack with tf.stack, but the output of tf.stack is different than tf.pack.
Any solution?

**Comment by ShauryaUppal-1Mg** [comment] 2020-03-19 18:21
> Any solution to this problem? I am having the same problem. tensorflow 1.13, python 3.6.
> I replaced tf.pack with tf.stack, but the output of tf.stack is different than tf.pack.
> Any solution?

How did you solve this issue? I am facing same issue.
