### ISSUE TITLE
tf.nn.softmax_cross_entropy_with_logits and tf.keras.backend.categorical_crossentropy crash(abort)

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46908] opened 2021-02-04 03:56 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.nn.softmax_cross_entropy_with_logits` and `tf.keras.backend.categorical_crossentropy` crash(abort) when `axis` is large

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.backend.categorical_crossentropy(target=np.ones((1, 1, 1)), output=np.ones((1, 1, 1)), axis=9223372036854775807, from_logits=True)
~~~
Output
~~~python
2021-02-04 03:56:25.011064: F tensorflow/core/framework/tensor_shape.cc:345] Check failed: size >= 0 (-9223372036854775808 vs. 0)
Aborted (core dumped)
~~~

~~~python
import tensorflow as tf
import numpy as np
tf.nn.softmax_cross_entropy_with_logits(labels=1, logits=1, axis=9223372036854775807)
~~~
Output
~~~python
2021-02-04 03:55:56.843085: F tensorflow/core/framework/tensor_shape.cc:345] Check failed: size >= 0 (-9223372036854775808 vs. 0)
Aborted (core dumped)
~~~

**Comment by amahendrakar** [comment] 2021-02-04 14:10
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d016460f94fdc22c24d5fd23bc626936/46908.ipynb). Thanks!

**Comment by sushreebarsa** [comment] 2021-05-28 10:31
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/e4a58cfb82be4aded3c9617e25f06e6a/untitled35.ipynb)..Thanks !

**Comment by yongtang** [comment] 2021-08-28 16:42
The issue has been fixed with the latest tf-nightly:

```
# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-08-28 16:42:13.583357: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-28 16:42:13.583402: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> import numpy as np
>>> tf.keras.backend.categorical_crossentropy(target=np.ones((1, 1, 1)), output=np.ones((1, 1, 1)), axis=9223372036854775807, from_logits=True)
2021-08-28 16:42:14.990345: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-28 16:42:14.990388: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-28 16:42:14.990430: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-87-192): /proc/driver/nvidia/version does not exist
2021-08-28 16:42:14.990839: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-28 16:42:14.992700: W tensorflow/core/framework/op_kernel.cc:1694] OP_REQUIRES failed at sequence_ops.cc:83 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[9223372036854775807] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/backend.py", line 5006, in categorical_crossentropy
    return tf.nn.softmax_cross_entropy_with_logits(
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[9223372036854775807] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Range]
>>> 
>>> 
>>> 
>>> tf.nn.softmax_cross_entropy_with_logits(labels=1, logits=1, axis=9223372036854775807)
2021-08-28 16:42:25.317106: W tensorflow/core/framework/op_kernel.cc:1694] OP_REQUIRES failed at sequence_ops.cc:83 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[9223372036854775807] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7083, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[9223372036854775807] and type int64 on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Range]
>>> 
```

**Comment by yongtang** [comment] 2021-08-28 16:43
I will close this issue since it has been resolved. Please feel free to reopen if the issue persists.

**Closed by yongtang** 2021-08-28 16:43 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.4
