### ISSUE TITLE
Operation 'ExtractImagePatches' has no attr named '_XlaCompile'

### ISSUE THREAD

**Issue by mkravchik** [tensorflow/tensorflow#31367] opened 2019-08-06 13:42 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):b'unknown' 1.12.0
- Python version:Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0 7.0.5
- GPU model and memory: GTX 1080 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Can't take gradients, fails with InvalidArgumentError: Operation 'ExtractImagePatches' has no attr named '_XlaCompile'
**Describe the expected behavior**
Getting gradients without error
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
inputs = np.array([[[x + y * 10 for x in [1,2]] for y in range(5)]])
inputs = inputs.reshape((1,1,inputs.shape[1],inputs.shape[2]))
print("inputs:", inputs)

import tensorflow as tf
tf.reset_default_graph()
with tf.Graph().as_default() as g:
    x = tf.placeholder("float", [1, 1, None, 2])
    y = tf.extract_image_patches(images=x, ksizes=[1, 1, 3, 1], strides=[1, 1, 1, 1], rates=[1, 1, 1, 1], padding='VALID')
    gradient = tf.gradients(y, x)
    init = tf.global_variables_initializer()
    
with tf.Session(graph=g) as sess:
    sess.run(init)
    print(sess.run([y], feed_dict = {x:inputs}))

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2019-08-07 10:39
I have tried on colab with TF version 1.12 [gist](https://colab.research.google.com/drive/1a1lDY5ZsPsHI3ZRk3ePWO3lP_r-k2Y2D) ,1.13,1.14,nightly versions [gist ](https://colab.research.google.com/drive/1B-1ObJLXLNpuOA_Tx_WUtwkq15oiqTMt)and was able to reproduce the issue.However in Nightly version it is throwing different error ```
ValueError: Fetch argument <tf.Operation 'init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init"
op: "NoOp"
 is not an element of this graph.)Thanks!
```

**Comment by jvishnuvardhan** [comment] 2019-08-12 22:50
@mkravchik I cannot reproduce the error if you remove init op. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/179569689d746cc40770799bb952024f/tf_31367.ipynb). Thanks!

**Comment by mkravchik** [comment] 2019-08-15 08:25
Thanks probably because you are using the nightly build. With my version it happens regardless the init op. I think that the root cause for this is the following issue https://github.com/tensorflow/tensorflow/issues/11651 which have been fixed recently, but not released

**Comment by jvishnuvardhan** [comment] 2019-08-15 15:42
@mkravchik You could use `tf-nightly` for now and in the next couple of months new stable version will be released. I am closing the issue for now. Please feel free to open the issue if it persists with the new version. Thanks!

**Closed by jvishnuvardhan** 2019-08-15 15:42 UTC
Labels: TF 1.12, comp:ops, stat:awaiting response, type:bug
