### ISSUE TITLE
Error when saving weights in h5 format for layer with nested layers

### ISSUE THREAD

**Issue by louisgriffin** [tensorflow/tensorflow#41021] opened 2020-07-02 08:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7

**Describe the current behavior**
Given a layer with nested layers, when trying to save weights in h5 format, fails with ```RuntimeError: Unable to create link (name already exists)```

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

class NestedLayers(tf.keras.layers.Layer):
    def __init__(self):
        super(NestedLayers, self).__init__()
        self.units = [layers.Conv2D(16, (3,3), name="conv_2d_0"),
                      layers.Conv2D(16, (3,3), name="conv_2d_1"),
                      layers.Conv2D(16, (3,3), name="conv_2d_2")]

    def build(self, input_shape):
        for i in range(0,2):
            unit_input_shape = list(input_shape)
            unit_input_shape[-1] = 1
            unit = self.units[i]
            unit.build(unit_input_shape)

    def call(self, inputs):
        split_inputs = tf.split(value=inputs,
                                 num_or_size_splits=3,
                                 axis=-1,
                                 name="conv_grp_split")
        outputs = []
        for i in range(0,2):
            out = self.units[i](split_inputs[i])
            outputs.append(out)
        out = tf.keras.layers.concatenate(outputs, axis=-1, name="conv_grp_concat")
        return  out

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

model = models.Sequential()
model.add(layers.InputLayer(input_shape=(32, 32, 3)))
model.add(NestedLayers())
model.add(layers.Flatten())
model.add(layers.Dense(10, activation='softmax'))
model.summary()

import datetime
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

check_pt = tf.keras.callbacks.ModelCheckpoint(
                os.path.join(log_dir, "model.ckpt.{epoch:04d}-{val_loss:.06f}.hdf5"),
                monitor='val_loss',
                verbose=1,
                save_best_only=False,
                save_weights_only=True,
                mode='max',
                period=1)

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=2,
                    validation_data=(test_images, test_labels),
                    callbacks = [check_pt])

```

Fails with the following:
Epoch 00001: saving model to logs/fit/20200702-114230/model.ckpt.0001-1.949398.hdf5
Traceback (most recent call last):
  File "/nfs/site/home/tkrimer/work/mbe/dlo/src/internal_utils/train_cifar10_tf_2/nested_layers_save.py", line 78, in <module>
    callbacks = [tensorboard_callback, check_pt])
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1177, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1223, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1151, in save_weights
    hdf5_format.save_weights_to_hdf5_group(f, self.layers)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 639, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/h5py/_hl/group.py", line 139, in create_dataset
    self[name] = dset
  File "/localdrive/users/tkrimer/venv/tf_2.1/lib/python3.7/site-packages/h5py/_hl/group.py", line 373, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)

**Comment by Saduf2019** [comment] 2020-07-02 14:47
@louisgriffin 
I ran the code shared above on tf 2.2 and do not face any error, can you please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/bebe8742e76c3ceab03fbc86f6dc167e/untitled253.ipynb).

As per the error faced, please refer to [this link](https://www.bountysource.com/issues/45759314-python-3-string-error)  [link1](https://github.com/tensorflow/tensorflow/issues/27688) [link2](https://github.com/uber/ludwig/issues/210#issuecomment-582292921) [link3](https://stackoverflow.com/questions/59187054/runtimeerror-unable-to-create-link-name-already-exists-when-i-append-hdf5-fil)

**Comment by louisgriffin** [comment] 2020-07-06 09:16
> @louisgriffin
> I ran the code shared above on tf 2.2 and do not face any error, can you please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/bebe8742e76c3ceab03fbc86f6dc167e/untitled253.ipynb).
> 
> As per the error faced, please refer to [this link](https://www.bountysource.com/issues/45759314-python-3-string-error) [link1](https://github.com/tensorflow/tensorflow/issues/27688) [link2](https://github.com/uber/ludwig/issues/210#issuecomment-582292921) [link3](https://stackoverflow.com/questions/59187054/runtimeerror-unable-to-create-link-name-already-exists-when-i-append-hdf5-fil)

I tried the suggestions in the links, like switching to v2 optimizer - it still does not work. It does have to do with eager_execution, because once eager_execution is disabled saving at check point succeeds

**Comment by Saduf2019** [comment] 2020-07-06 09:48
@louisgriffin 
Can you please share a colab gist with the error faced.

**Comment by louisgriffin** [comment] 2020-07-06 12:06
@Saduf2019 I added `model.save_weights("nested_layers.h5")` to the [gist](https://colab.research.google.com/gist/Saduf2019/bebe8742e76c3ceab03fbc86f6dc167e/untitled253.ipynb#scrollTo=3_iqkxuDDmPN) and it fails with the same error `Unable to create link, name already exists"

**Comment by Saduf2019** [comment] 2020-07-06 16:48
@louisgriffin 
Please refer to below issues with similar error:
#27688 [link](https://github.com/uber/ludwig/issues/210#issuecomment-582292921) [link1](https://stackoverflow.com/questions/59187054/runtimeerror-unable-to-create-link-name-already-exists-when-i-append-hdf5-fil)

**Comment by louisgriffin** [comment] 2020-07-08 14:37
> @louisgriffin
> I ran the code shared above on tf 2.2 and do not face any error, can you please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/bebe8742e76c3ceab03fbc86f6dc167e/untitled253.ipynb).
> 
> As per the error faced, please refer to [this link](https://www.bountysource.com/issues/45759314-python-3-string-error) [link1](https://github.com/tensorflow/tensorflow/issues/27688) [link2](https://github.com/uber/ludwig/issues/210#issuecomment-582292921) [link3](https://stackoverflow.com/questions/59187054/runtimeerror-unable-to-create-link-name-already-exists-when-i-append-hdf5-fil)

@Saduf2019 I investigated some more, and even though you don't see the error, are the actual files of for the h5 checkpoint being created? For me they are not created

**Comment by louisgriffin** [comment] 2020-07-08 14:50
@Saduf2019 here is the a scenario where it fails even in the notebook:
```python
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

class NestedLayers(tf.keras.layers.Layer):
    def __init__(self):
        super(NestedLayers, self).__init__()
        self.units = [layers.Conv2D(16, (3,3), name="conv_2d_0"),
                      layers.Conv2D(16, (3,3), name="conv_2d_1"),
                      layers.Conv2D(16, (3,3), name="conv_2d_2")]

    def build(self, input_shape):
        for i in range(0,2):
            unit_input_shape = list(input_shape)
            unit_input_shape[-1] = 1
            unit = self.units[i]
            unit.build(unit_input_shape)

    def call(self, inputs):
        split_inputs = tf.split(value=inputs,
                                 num_or_size_splits=3,
                                 axis=-1,
                                 name="conv_grp_split")
        outputs = []
        for i in range(0,2):
            out = self.units[i](split_inputs[i])
            outputs.append(out)
        out = tf.keras.layers.concatenate(outputs, axis=-1, name="conv_grp_concat")
        return  out

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

model = models.Sequential()
model.add(layers.InputLayer(input_shape=(32, 32, 3)))
model.add(NestedLayers())
model.add(layers.Flatten())
model.add(layers.Dense(10, activation='softmax'))
model.summary()

import datetime

check_pt = tf.keras.callbacks.ModelCheckpoint(
                os.path.join(l"model.ckpt.{epoch:04d}-{val_loss:.06f}.hdf5"),
                monitor='val_loss',
                verbose=1,
                save_best_only=False,
                save_weights_only=True,
                mode='max',
                period=1)

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=2,
                    validation_data=(test_images, test_labels),
                    callbacks = [check_pt])

```

**Comment by louisgriffin** [comment] 2020-07-09 07:49
@Saduf2019 digging deeper into the issue, the main culprit is the fact that once _eager_execution_ is enabled NestedLayer's weights, that come from the nested layers within, are not named uniquely which leads to conflicts when trying to save it in h5 format.

**Comment by gowthamkpr** [comment] 2020-07-09 16:11
@louisgriffin Was able to reproduce this error in Tf 2.2 and tf-nightly. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/32c46e935e88bed1a8fd5f88b36a2427/untitled297.ipynb)

**Comment by louisgriffin** [comment] 2020-07-12 06:58
@k-w-w do you have any suggestions as per workaround?

**Comment by louisgriffin** [comment] 2020-07-30 14:04
@k-w-w I would really appreciate some guidance/workaround for the main culprit here, which is weights in the NestedLayer are not named uniquely. It is becoming a problem, not only with the h5 format, but in general.

**Comment by Zedd1558** [comment] 2020-08-04 07:13
I was facing this issue when upgraded to tf 2.3. I tried reinstalling h5py etc. none of them worked. Then, I reverted to tf 2.2 and the issue was resolved. no idea how.

**Comment by louisgriffin** [comment] 2020-08-05 10:14
I found a workaround:
Forcing the internal layers weights to be named uniquely with a name scope. Check this out:
``` 
class NestedLayers(tf.keras.layers.Layer):
    def __init__(self):
        super(NestedLayers, self).__init__()
        self.units = [layers.Conv2D(16, (3,3), name="conv_2d_0"),
                      layers.Conv2D(16, (3,3), name="conv_2d_1"),
                      layers.Conv2D(16, (3,3), name="conv_2d_2")]

    def build(self, input_shape):
        for i in range(0,2):
            unit_input_shape = list(input_shape)
            unit_input_shape[-1] = 1
            unit = self.units[i]
            with tf.name_scope("BUILD_{}".format(i)):
               unit.build(unit_input_shape)

    def call(self, inputs):
        split_inputs = tf.split(value=inputs,
                                 num_or_size_splits=3,
                                 axis=-1,
                                 name="conv_grp_split")
        outputs = []
        for i in range(0,2):
            out = self.units[i](split_inputs[i])
            outputs.append(out)
        out = tf.keras.layers.concatenate(outputs, axis=-1, name="conv_grp_concat")
        return  out
```
Also, here is a [gist](https://colab.research.google.com/drive/1DPmCmde9JAuFc0TNuBMG99CbW3Og4hJr?usp=sharing)

**Comment by sancheztavo** [comment] 2020-09-29 06:15
I also had this same issue when creating a model from an existing one the following way 
```
denoise_model_name = "./models/black/hybrid_data_model_1_00000220.h5"
    denoise_model = tf.keras.models.load_model(denoise_model_name)

    keras_input = tf.keras.Input(shape=(44, 100, 3))
    x = denoise_model(keras_input)
    x = layers.Conv2D(64, kernel_size=(3, 3),
                      activation='relu',
                      kernel_initializer='he_uniform', padding='same')(x)
```

And adding a name to the new Conv2D layer also solved it

**Comment by schniewmatz** [comment] 2020-11-18 16:42
I also experienced this issue in tf 2.3.1 when saving models repeatedly during a run, also when a model was constructed and compiled anew during an evaluation loop. This comes also with the caveat that this happened using mlflow.keras.log_model(). Nevertheless this calls tf.keras.models.save_model().

For me it helped to name all layers and also add randomized integers to the layer names whenever a model was constructed anew.

**Comment by nixingyang** [comment] 2020-12-17 09:49
Similar bug still exists in TensorFlow 2.4.0.

**Comment by shanmukh05** [comment] 2021-02-02 17:33
> Similar bug still exists in TensorFlow 2.4.0.

Did your problem get solved. I am facing the same issue.

**Comment by nixingyang** [comment] 2021-02-02 17:49
> > Similar bug still exists in TensorFlow 2.4.0.
> 
> Did your problem get solved. I am facing the same issue.

Nope. I am using TensorFlow 2.2.2 which works fine.

**Comment by shanmukh05** [comment] 2021-02-03 06:52
> I also experienced this issue in tf 2.3.1 when saving models repeatedly during a run, also when a model was constructed and compiled anew during an evaluation loop. This comes also with the caveat that this happened using mlflow.keras.log_model(). Nevertheless this calls tf.keras.models.save_model().
> 
> For me it helped to name all layers and also add randomized integers to the layer names whenever a model was constructed anew.

Can you explain this with the help of code. I tried similar but still facing the issue.

**Comment by fantauzzi** [comment] 2021-02-26 15:27
The same error can be obtained this way:
1) save an Adam optimizer in a Python variable (such that the same instance can be used again later) and use it to compile a Keras model
2) call `fit()` on the model
3) instantiate a Keras model (or load it from a .h5 file), and compile it using the same instance of Adam optimizer as before, the instance saved in a variable at point 1)
4) call `fit()` on the second model, the one instantiated at point 3)
5) save the second model as a .h5 file, you get the error **RuntimeError: Unable to create link (name already exists)**

What happens is that after step 4), the Adam optimizer instance has in its `weights` attribute a list of 9 TF variables, instead of 5. Four of the variables have been duplicated, keeping the same respective name. When trying to save the mode in .h5 format, the `tf.keras.models.save_model()` function finds two variables with duplicated name `Adam/dense/kernel/m:0`, and stops with an error.

In this case, the error can be resolved by ensuring the same instance of Adam optimizer is not used to compile more than one model.

**Comment by thusinh1969** [comment] 2021-08-02 23:37
This is annoying !!! Bugs came back after bugs. TF2 is terribly managing changes.

**Comment by sushreebarsa** [comment] 2021-12-13 16:23
@louisgriffin 
It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.7.0) and let us know if the issue still persists? Thanks!

**Closed** 2021-12-27 17:48 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:keras, TF 2.2

**Comment by TrentHouliston** [comment] 2022-09-01 01:09
This bug still exists in the latest TensorFlow (2.9.1)

**Comment by danyukezz** [comment] 2024-04-12 01:04
bug still exist tf 2.14.0

**Comment by ovds** [comment] 2024-04-15 10:55
bug exists as well when using a pretrained lstm as one of the layers
