### ISSUE TITLE
ps job in the distributed inception trainer killed by OOM killer

### ISSUE THREAD

**Issue by shendiaomo** [tensorflow/tensorflow#2384] opened 2016-05-16 07:59 UTC
Hi all:
  It seems that the distributed runtime has a memory leak problem, my tf version is the 0.8.0 wheel package from http://tensorflow.org.
  When I started the distributed inception trainer in http://github.com/tensorflow/models/ on a 64G RAM Linux server with 1 ps and 4 replicas, the footprint of the ps process increased slowly but continously, and the process was finally killed by the system oom killer after several days. 
  Anyone can reproduce this? @mrry

**Comment by mrry** [comment] 2016-05-16 19:50
Thanks for the report! It might take some time to figure this out, but we'll get to the bottom of it.

First of all, was it only the PS task that died? Do the worker replica tasks show an upward trend in memory consumption over time?

**Comment by shendiaomo** [comment] 2016-05-17 09:18
I'd tried several times, only the PS task was OOM, all the worker tasks seemed ok.

**Comment by mmuneebs** [comment] 2016-05-24 01:18
My worker task was killed in a similar setup with an upward trend in memory consumption; the ps job remained fine. I do see multiple bfc_allocator warnings indicating that more memory could give performance gains.

**Comment by girving** [comment] 2016-06-07 16:19
@mrry: Any suggestions for further debugging?  I don't think we have enough information to diagnose just yet.  If it's an actual memory leak valgrind could help, but that would be difficult to set up.

@mmuneebs: The summaries should be written to disk soon after they are generated, so I don't think that's the issue.  The allocator warnings are likely a symptom, not a cause.

**Comment by mmuneebs** [comment] 2016-06-14 22:21
I fixed this issue with the workers by commenting the `with tf.device('/cpu:0'):` spec while calling `batch_inputs` in `image_processing.py`. One reason this may have happened with my setup though not completely clear is that I use
```
with tf.device(tf.train.replica_device_setter(ps_tasks=1,
                                              worker_device="/job:worker/task:%d" % FLAGS.task_id,
                                              cluster=cluster_spec)):
```
instead of
```
# Ops are assigned to worker by default.
with tf.device('/job:worker/task:%d' % FLAGS.task_id):
    # Variables and its related init/assign ops are assigned to ps.
    with slim.scopes.arg_scope(
            [slim.variables.variable, slim.variables.global_step],
            device=slim.variables.VariableDeviceChooser(num_parameter_servers)):
```
as the outermost training scope inside which the batch processing gets called (`inception_distributed_train.py`).

Not sure why exactly this became a problem for my modified setup, but now the memory increase trend has reduced at least ten-fold, and tested to run for a 100 epochs.
Maybe the original code will work fine without this CPU device specification as well.

**Comment by mrry** [comment] 2016-06-26 00:26
Unfortunately I haven't been able to reproduce this, but we have seen a simpler apparent memory leak in #2942, which is caused by memory fragmentation. It's possible that this could be causing the problem here as well.

Our preferred workaround is to use [tcmalloc](http://goog-perftools.sourceforge.net/doc/tcmalloc.html) as the malloc implementation, which more closely reproduces the way we run the distributed runtime internally. You can install tcmalloc with many package managers, and then use it with TensorFlow by setting `LD_PRELOAD` to include the tcmalloc library.

An alternative, which might help to test the root cause, but might also cause undesirable performance issues, is to set the `MALLOC_MMAP_THRESHOLD_` environment variable to a small value (like 100000). This should reduce fragmentation, at the possible downside of increasing the cost for some allocations, since it will use `mmap()` and `munmap()` to implement `malloc()` and `free()` for more allocations.

**Comment by aselle** [comment] 2016-07-12 00:02
@shendiaomo, were you able to resolve your issue using @mrry or @mmuneebs?

**Comment by aselle** [comment] 2016-07-21 17:13
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-21 17:13 UTC
Labels: awaiting response

**Comment by lordadamson** [comment] 2018-03-22 18:23
@mrry I love you
