### ISSUE TITLE
Bus error (core dumped) when importing TensorFlow 

### ISSUE THREAD

**Issue by nikhilshinday** [tensorflow/tensorflow#6744] opened 2017-01-09 16:07 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
- [Issue 2626](https://github.com/tensorflow/tensorflow/issues/2626)
- [Issue 3366](https://github.com/tensorflow/tensorflow/issues/3366)

### Environment info
Operating System:
Ubuntu 16.04

Installed version of CUDA and cuDNN: 8.0, 5.1.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```-rw-r--r-- 1 root root   558720 Jan  8 20:20 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Jan  8 20:20 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Jan  8 20:20 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Jan  8 20:20 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Jan  8 20:20 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61062656 Jan  8 20:35 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61062656 Jan  8 20:35 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 61062656 Jan  8 20:35 /usr/local/cuda/lib64/libcudnn.so.5.1.5
```

If installed from binary pip package, provide: *did not install from pip package*

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): `ec7929b878926c39255254e9aea992f0bc65aa68`
2. The output of `bazel version`: 
```
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
Bus error (core dumped)
```

### What other attempted solutions have you tried?
I have not attempted solutions because I know of none -- it seems like there is a bus error when loading the driver, and I'm not sure how to proceed

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
Not sure if the output of the core dump is going to be useful or where to find it. Help would be appreciated.

**Comment by yaroslavvb** [comment] 2017-01-09 17:44
Can you run it under gdb and show stack trace?

it

```
cat import tensorflow > test.py
^D
gdb python
run test.py
bt
```

**Comment by yaroslavvb** [comment] 2017-01-09 17:50
Although, `bus error` looks weird, the only time I've seen it was when trying to read from NFS and network was flaky

**Comment by nikhilshinday** [comment] 2017-01-09 20:06
Hey, here is the stack trace: 

```
(gdb) run test.py
Starting program: /usr/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3b8a700 (LWP 24061)]
[New Thread 0x7ffff1389700 (LWP 24062)]
[New Thread 0x7fffeeb88700 (LWP 24063)]
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally

Thread 1 "python" received signal SIGBUS, Bus error.
memset () at ../sysdeps/x86_64/multiarch/../memset.S:78
78	../sysdeps/x86_64/multiarch/../memset.S: No such file or directory.
```

**Comment by yaroslavvb** [comment] 2017-01-09 20:11
That seems consistent with something wrong with your file-system, perhaps try copying all the CUDA .so files to another directory

**Comment by nikhilshinday** [comment] 2017-01-09 20:18
alright, I copied it into a directory as follows:
```
ubuntu@ip-172-31-44-171:~/cuda$ cp /usr/local/cuda/lib64/libcud* .
ubuntu@ip-172-31-44-171:~/cuda$ export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)"
ubuntu@ip-172-31-44-171:~/cuda$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/home/ubuntu/cuda
```
and got the same Bus error issue.

**Comment by yaroslavvb** [comment] 2017-01-09 20:20
Stack trace makes me think the problem is outside of TensorFlow. I see similar issue here

https://bugs.kde.org/show_bug.cgi?id=340824

**Comment by yaroslavvb** [comment] 2017-01-10 01:41
I'm seeing lots of potential causes for dlopen causing sigbus: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bus+error+on+dlopen

I'll close this for now, please reopen if you find that problem lies with TensorFlow rather than with system dlopen call

**Closed by yaroslavvb** 2017-01-10 01:41 UTC

**Comment by nikhilshinday** [comment] 2017-01-26 23:32
turns out that `libcublas.so.8.0` was unsuccessfully unzipped. I downloaded CUDA 8.0/CuDNN again, reinstalled drivers, and TF installed successfully.

**Comment by flyhorseli** [comment] 2018-12-20 22:46
I saw this issue in 1.9. After upgrade to 1.12, it works fine on arm32.
