### ISSUE TITLE
How to install tensorflow on the NVIDIA Jetson TK1 developer kit?

### ISSUE THREAD

**Issue by alexryan** [tensorflow/tensorflow#4070] opened 2016-08-26 23:27 UTC
We are trying to install tensorflow on the [NVIDIA Jetson TK1 developer kit](http://www.nvidia.com/object/jetson-tk1-embedded-dev-kit.html).

The platform has ..

a GPU
[Tegra-K1](http://www.nvidia.com/object/tegra-k1-processor.html)

a 64-bit ARM CPU
[NVIDIA 4-Plus-1™ Quad-Core ARM® Cortex™-A15 CPU](http://www.nvidia.com/docs/io/116757/nvidia_quad_a15_whitepaper_finalv2.pdf)

ubuntu 14
(Note: It originally came installed with a 32-bit version of ubuntu 14, but this caused problems so we installed the 64-bit version.)
64-bit version of ubuntu 14

```
ubuntu@tegra-ubuntu:~/grpc-java3/grpc-java$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

ubuntu@tegra-ubuntu:~/grpc-java3/grpc-java$ uname -a
Linux tegra-ubuntu 3.10.96-tegra #1 SMP PREEMPT Tue May 17 16:29:05 PDT 2016 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@tegra-ubuntu:~/grpc-java3/grpc-java$ lsb_release -d
Description:    Ubuntu 14.04.5 LTS
ubuntu@tegra-ubuntu:~/grpc-java3/grpc-java$ 

ubuntu@tegra-ubuntu:~/grpc-java3/grpc-java$ ldconfig -p | grep cuda
	libicudata.so.52 (libc6,AArch64) => /usr/lib/aarch64-linux-gnu/libicudata.so.52
	libcuda.so.1 (libc6,AArch64) => /usr/lib/aarch64-linux-gnu/tegra/libcuda.so.1
	libcuda.so (libc6,AArch64) => /usr/lib/aarch64-linux-gnu/libcuda.so
	libcuda.so (libc6,AArch64) => /usr/lib/aarch64-linux-gnu/tegra/libcuda.so
```

Because it is an ARM processor rather than an X86 processor, we have to build from source.

The problem we are having is 
the tensorflow build requires the protoc plugin for gRPC Java
but we are having difficulties compiling the protoc plugin for gRPC Java on this platform.
the grpc-java team does not support arm64.
[they suggested editing the gradle script ...](https://github.com/grpc/grpc-java/issues/2202)

[We’re having problems trying to do so ...](https://discuss.gradle.org/t/tool-chain-gcc-gnu-gcc-dont-know-how-to-build-for-platform-linux-aarch64/19232)

Is there something we are missing?

It would be nice if it were a little easier to install tensorflow on this nvidia GPU device.

**Comment by vrv** [comment] 2016-08-26 23:30
You might have better luck trying to use the Makefile approach in contrib/makefile, rather than bazel.  We know it works for arm devices, and it currently doesn't link in any grpc code.

**Comment by vrv** [comment] 2016-08-26 23:30
Closing since this is really a better question for StackOverflow -- it's a request for help from the community, not a bug or explicit feature request.

**Closed by vrv** 2016-08-26 23:30 UTC

**Comment by alexryan** [comment] 2016-08-26 23:31
could we make it a feature request to support arm 64?

**Comment by vrv** [comment] 2016-08-26 23:35
You should check out contrib/makefile first, and then file a concrete bug about what is not supported.

**Comment by vrv** [comment] 2016-09-29 15:53
No specific plan, if anybody who has a TX1 and is interested in getting it to work wants to send a patch, we'd be ecstatic!

**Comment by tusharsoni08** [comment] 2016-12-01 07:36
@vrv Hi I've tried with Makefile and successfully installed tensorflow on Jetson TK1 by following RPi build (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi), but I'm using tensorflow as backend for Keras, so I need python wrapping of it along with GPU support, could you please tell me how should I do that. Thank you!

**Comment by zivaliserkan** [comment] 2019-09-20 14:26
Hi every body,
Is there solve this problem ?

I have the nvidia jetson TK1 kit. I can't add tensorflow-gpu to this card. I've been looking for a lot of forms, but I couldn't find anything for 32 bits. Can you help with this?
