### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'gfile' - Version 2.0.0-alpha0

### ISSUE THREAD

**Issue by Gurubux** [tensorflow/tensorflow#31315] opened 2019-08-04 08:09 UTC
Tensorflow Version - **2.0.0-alpha0**

Error occurred while running a notebook from the Tensorflow site  - [**Build a linear model with Estimators**](https://www.tensorflow.org/tutorials/estimators/linear )
<br>
Download the dataset:
```
from official.wide_deep import census_dataset
from official.wide_deep import census_main

census_dataset.download("/tmp/census_data/")
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-9-fa1d43ace000> in <module>()
>       2 from official.wide_deep import census_main
>       3 
> ----> 4 census_dataset.download("/tmp/census_data/")
> 
> /content/models/official/wide_deep/census_dataset.py in download(data_dir)
>      76 def download(data_dir):
>      77   """Download census data if it is not already present."""
> ---> 78   **tf.gfile.MakeDirs(data_dir)**
>      79 
>      80   training_file_path = os.path.join(data_dir, TRAINING_FILE)
> 
> **AttributeError: module 'tensorflow' has no attribute 'gfile'**
<hr>

### _Should I go about making the following changes manually in the file census_dataset.py ?_
WARNING: Logging before flag parsing goes to stderr.
W0625 16:04:36.412110 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:78: The name tf.gfile.MakeDirs is deprecated. Please use **tf.io.gfile.makedirs** instead.

W0625 16:04:36.413802 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:81: The name tf.gfile.Exists is deprecated. Please use **tf.io.gfile.exists** instead.

W0625 16:04:38.253764 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:62: The name tf.gfile.Open is deprecated. Please use **tf.io.gfile.GFile** instead.

W0625 16:04:38.488776 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:73: The name tf.gfile.Remove is deprecated. Please use **tf.io.gfile.remove** instead. 
#28632 https://github.com/tensorflow/tensorflow/issues/28632
#https://github.com/google/gin-config/issues/9
#https://github.com/tobegit3hub/simple_tensorflow_serving/issues/45

**Comment by gadagashwini** [comment] 2019-08-05 08:41
@Gurubux The tutorial works for Tensorflow 1.14.0. You might want to give it a try instead. Thanks!

**Comment by mihaimaruseac** [comment] 2019-08-05 14:36
In 2.0, `tf.gfile.*` is replaced by `tf.io.gfile.*`.

If you want, you can submit a cherry-pick for `census_dataset.py`.

Thank you

**Comment by Gurubux** [comment] 2019-08-12 07:43
@mihaimaruseac The following changes in census_dataset.py i.e 
`tf.gfile.* is replaced by tf.io.gfile.*`

Results in 
`tf.io.gfile.MakeDirs(data_dir)`
> **AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'MakeDirs'**

Thanks
@gadagashwini Sure it does! Thanks

**Comment by mihaimaruseac** [comment] 2019-08-12 15:30
@Gurubux https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/gfile says it is `makedirs`

**Comment by gadagashwini** [comment] 2019-08-16 08:35
@Gurubux Did you check the @mihaimaruseac's comment. Thanks!

**Comment by gadagashwini** [comment] 2019-08-20 05:43
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-20 05:43 UTC
Labels: 2.0.0-alpha0, stat:awaiting response

**Comment by Asanka25** [comment] 2019-11-16 14:13
If you following object detection API reguard tutorial;
First check your tensorflow version by running bellow code

import tensorflow as tf
print(tf.__version__)

If it's 2 or above then
pip install tensorflow==1.14.0      will run code successfully.

**Comment by RoboEvangelist** [comment] 2020-04-27 08:59
If are having too much trouble, and don't want to downgrade, just do
`import tensorflow.compat.v1 as tf`

**Comment by mihaimaruseac** [comment] 2020-04-27 17:57
No need to downgrade, all of the gfile conversions are covered by the migration script.

**Comment by RoboEvangelist** [comment] 2020-04-27 18:01
> No need to downgrade, all of the gfile conversions are covered by the migration script.

Is there a migration script for C++?

**Comment by mihaimaruseac** [comment] 2020-04-28 00:32
The C++ API didn't change

**Comment by mitramir55** [comment] 2020-06-12 13:42
@mihaimaruseac I'm working in colab and  changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error
`AttributeError: module 'tensorflow' has no attribute 'gfile'
`

**Comment by mihaimaruseac** [comment] 2020-06-12 15:51
@mitramir55 please open a new issue, fill in issue template and provide minimal code to reproduce. It's likely you have some dependency issue / some wrong version of TF installed. `pip list` should also help in identifying the issue

**Comment by engrmz** [comment] 2020-08-19 10:40
> In 2.0, `tf.gfile.*` is replaced by `tf.io.gfile.*`.
> 
> If you want, you can submit a cherry-pick for `census_dataset.py`.
> 
> Thank you


I solved the error by replacing `tf.io.gfile.FastGFile` to `tf.io.gfile.GFile`.

**Comment by kabir-ahmed** [comment] 2020-12-17 10:46
> @Gurubux https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/io/gfile says it is `makedirs`

its working good
