### ISSUE TITLE
Segfault when running tensorflow.python.ops.gen_sparse_ops.sparse_cross

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59412] opened 2023-01-22 22:39 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_sparse_ops
try:
  indices = []
  values_0_tensor = tf.convert_to_tensor(np.ones([3], dtype=str))
  values_0 = tf.identity(values_0_tensor)
  values_1_tensor = tf.convert_to_tensor(np.ones([1], dtype=str))
  values_1 = tf.identity(values_1_tensor)
  values_2_tensor = tf.convert_to_tensor(np.ones([2], dtype=str))
  values_2 = tf.identity(values_2_tensor)
  values = [values_0,values_1,values_2,]
  shapes_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
  shapes_0 = tf.identity(shapes_0_tensor)
  shapes_1_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
  shapes_1 = tf.identity(shapes_1_tensor)
  shapes_2_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
  shapes_2 = tf.identity(shapes_2_tensor)
  shapes = [shapes_0,shapes_1,shapes_2,]
  dense_inputs = []
  hashed_output = True
  num_buckets = 1000
  hash_key = 956888297471
  out_type = tf.int64
  internal_type = tf.string
  out = gen_sparse_ops.sparse_cross(indices=indices,values=values,shapes=shapes,dense_inputs=dense_inputs,hashed_output=hashed_output,num_buckets=num_buckets,hash_key=hash_key,out_type=out_type,internal_type=internal_type,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-22 17:38:00.648068: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 17:38:00.744375: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-01-22 17:38:01.170511: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/tf-2.10/lib/
2023-01-22 17:38:01.170671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/tf-2.10/lib/
2023-01-22 17:38:01.170678: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-22 17:38:01.652854: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:01.659137: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:01.659243: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:01.659534: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 17:38:01.660386: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:01.660489: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:01.660580: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:02.013691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:02.013832: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:02.013927: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-22 17:38:02.014013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4254 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Segmentation fault

```
```
</details>

**Comment by synandi** [comment] 2023-01-24 11:24
@nimashiri This issue is not replicating in [tf-nightly](https://colab.sandbox.google.com/gist/synandi/801417c3cfaf3fa4a92f9834aac35c21/59412_nightly.ipynb) and [TF v2.11](https://colab.sandbox.google.com/gist/synandi/8066a95b6423478230aede999c87a800/untitled256.ipynb#scrollTo=EwebFEccbzpO) It is raising a different error.

```
Error:NodeDef expected inputs 'string, string, string' do not match 6 inputs specified; Op<name=SparseCross; signature=indices:N*int64, values:, shapes:N*int64, dense_inputs: -> output_indices:int64, output_values:out_type, output_shape:int64; attr=N:int,min=0; attr=hashed_output:bool; attr=num_buckets:int,min=0; attr=hash_key:int; attr=sparse_types:list(type),min=0,allowed=[DT_INT64, DT_STRING]; attr=dense_types:list(type),min=0,allowed=[DT_INT64, DT_STRING]; attr=out_type:type,allowed=[DT_INT64, DT_STRING]; attr=internal_type:type,allowed=[DT_INT64, DT_STRING]>; NodeDef: {{node SparseCross}} [Op:SparseCross]

```


Thank you!

**Comment by mihaimaruseac** [comment] 2023-02-02 01:24
Closing as duplicate of already fixed issue.

**Closed by mihaimaruseac** 2023-02-02 01:24 UTC
Labels: stat:awaiting response, type:bug, comp:ops, TF 2.10
