### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by viswanath27** [tensorflow/tensorflow#38589] opened 2020-04-16 06:01 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:not applicable
- TensorFlow installed from (source or binary):binary (pip3 install tensorflow)
- TensorFlow version: 2.2.0-dev20200409
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): na
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version: Cuda10.2/cuDNN 7.6.5
- GPU model and memory:GeForce GTX 1060/6GB

**Describe the problem**
Below is the issue with tensorflow when a specific model is executed. 

Using TensorFlow backend.
2020-04-16 10:54:20.595255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Patch extracted
Traceback (most recent call last):
  File "train_retina.py", line 38, in <module>
    model = M.BCDU_net_D3(input_size = (64,64,1))
  File "/home/sandbox/vissu/image_segmentation/BCDU-Net/Retina Blood Vessel Segmentation/models.py", line 17, in BCDU_net_D3
    conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 76, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 446, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 310, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 696, in is_keras_tensor
    if not is_tensor(x):
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 704, in is_tensor
    return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

Also referred   other open issues, but there is no solution out there. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
when running an example of BCDU-Net model. 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2020-04-16 08:20
@viswanath27, 
Provide the exact sequence of commands / standalone code to reproduce the issue.Thanks

**Comment by viswanath27** [comment] 2020-04-16 08:39
Hi Ashwini,
Please find the below code snippet for the error shown above.

from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential



TRAIN = 'data/train'
TEST = 'data/test'
JSON_FILE = './model/model.json'
HDF5_FILE = './model/model.h5'
EPOCHS = 15
BATCH_SIZE = 32
STEPS_PER_EPOCH = 130
VALIDATION_STEPS = 22
POOL_SIZE = (2, 2)
KERNEL_SIZE = (3, 3)
INPUT_SHAPE = (224, 224, 3)
TARGET_SIZE = (224, 224)

def create_model():

    # Initialise a model
    model = Sequential()

    # First conv layer
    model.add(Conv2D(64, KERNEL_SIZE, input_shape=INPUT_SHAPE,
                     activation='relu', use_bias=True, strides=1, padding='same'))

    # Second conv layer
    model.add(Conv2D(64, KERNEL_SIZE, activation='relu',
                     strides=1, use_bias=True, padding='same'))

    # First pool layer
    model.add(MaxPooling2D(pool_size=POOL_SIZE, strides=2))

    # Third conv layer
    model.add(Conv2D(128, KERNEL_SIZE, activation='relu',
                     strides=1, use_bias=True, padding='same'))

    # Fourth conv layer
    model.add(Conv2D(128, KERNEL_SIZE, activation='relu',
                     strides=1, use_bias=True, padding='same'))

    # Second pool layer
    model.add(MaxPooling2D(pool_size=POOL_SIZE, strides=2))

    # Flattening
    model.add(Flatten())

    # FC layers
    model.add(Dense(units=512, activation='relu'))
    model.add(Dense(units=4, activation='sigmoid'))

    return model



my_model = create_model()

**Comment by NMazzatenta** [comment] 2020-04-27 12:43
I had the same issue. TF 2.1 built from source + keras 2.3.1 in conda environment. Solved by modifying file "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py" at line 704.
Before:
`return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)` 
After: 
`return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)`

**Comment by Kaushy** [comment] 2020-04-28 05:24
Thank you @NMazzatenta I had the same issue and your solution fixed it.

**Comment by chrirek** [comment] 2020-04-30 10:13
Thank you @NMazzatenta, this solved my problem aswell

**Comment by ravikyram** [comment] 2020-04-30 12:16
@viswanath27 

Is this still an issue.Please, close this thread if your issue was resolved. Thanks!

**Comment by bduclaux** [comment] 2020-05-09 15:47
The issue is not resolved.

**Comment by danhnguyen12091998** [comment] 2020-05-16 09:34
> I had the same issue. TF 2.1 built from source + keras 2.3.1 in conda environment. Solved by modifying file "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py" at line 704.
> Before:
> `return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)`
> After:
> `return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)`
> 
> Don't know if it is the right thing to do, but I got things running in this way.

@NMazzatenta After change the code as you support, I still have the issue. Can you help me to look at it ? Thanks
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 703, in is_tensor
    return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TENSOR_LIKE_TYPES'

**Comment by NMazzatenta** [comment] 2020-05-16 09:51
> > I had the same issue. TF 2.1 built from source + keras 2.3.1 in conda environment. Solved by modifying file "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py" at line 704.
> > Before:
> > `return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)`
> > After:
> > `return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)`
> > Don't know if it is the right thing to do, but I got things running in this way.
> 
> @NMazzatenta After change the code as you support, I still have the issue. Can you help me to look at it ? Thanks
> File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 703, in is_tensor
> return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)
> AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TENSOR_LIKE_TYPES'

@danhnguyen12091998 You should check the module "tensorflow.python.framework.ops" for the correct name of the attribute.

I retrieved it from the file at this path "/Users/nmazzatenta/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py" at line 216:

`_TENSOR_LIKE_TYPES = tuple()

def is_dense_tensor_like(t):

  return isinstance(t, _TENSOR_LIKE_TYPES)`

**Comment by Saduf2019** [comment] 2020-05-19 05:26
@@viswanath27 
Please update on @ ravikyram comment

**Comment by Korrakas** [comment] 2020-05-19 15:47
Hello there,
I encoutered the same issue and final comment by @NMazzatenta helped with a little twist:
1) I checked in lib/python3.7/site-packages/tensorflow/python/framework/ops.py at correct line to get the right type (in my case, simply core_tf_types.Tensor)
2) I modified lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py with the correct type, which also necessitated of importing the right type just like the other file. So I added from tensorflow.python.types import core as core_tf_types.
3) It works.

I'm stunned this kind of bug is still present. Gosh, stop renaming your variables! 
I still love you, that's ok.

**Closed** 2020-06-02 18:10 UTC
Labels: stalled, stat:awaiting response, type:build/install

**Comment by lilly-chen** [comment] 2020-06-04 18:30
Hi I am getting the same error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-c998649dcbf1> in <module>
----> 1 autoencoder, encoder = autoencoder(dims, init=init)

<ipython-input-12-a5ada2e5f0c7> in autoencoder(dims, act, init)
     15     # internal layers in encoder
     16     for i in range(n_stacks-1):
---> 17         x = Dense(dims[i + 1], activation=act, kernel_initializer=init, name='encoder_%d' % i)(x)
     18 
     19     # hidden layer

~/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
     73         if _SYMBOLIC_SCOPE.value:
     74             with get_graph().as_default():
---> 75                 return func(*args, **kwargs)
     76         else:
     77             return func(*args, **kwargs)

~/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    444                 # Raise exceptions in case the input is not compatible
    445                 # with the input_spec specified in the layer constructor.
--> 446                 self.assert_input_compatibility(inputs)
    447 
    448                 # Collect input shapes to build layer.

~/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in assert_input_compatibility(self, inputs)
    308         for x in inputs:
    309             try:
--> 310                 K.is_keras_tensor(x)
    311             except ValueError:
    312                 raise ValueError('Layer ' + self.name + ' was called with '

~/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in is_keras_tensor(x)
    693     ```
    694     """
--> 695     if not is_tensor(x):
    696         raise ValueError('Unexpectedly found an instance of type `' +
    697                          str(type(x)) + '`. '

~/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in is_tensor(x)
    701 
    702 def is_tensor(x):
--> 703     return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
    704 
    705 

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
```

i try to modify the ops.py as Korrakas suggested:
I checked in lib/python3.7/site-packages/tensorflow/python/framework/ops.py it is as follow

```
 def is_dense_tensor_like(t):
   return isinstance(t, core_tf_types.Tensor)
```

i try to update it to 

```
def is_dense_tensor_like(t):
  return isinstance(t, core_tf_types._TENSOR_LIKE_TYPES)

```
but it still give me the same error.

Any suggestion to fix this! Appreciated it!!

**Comment by NMazzatenta** [comment] 2020-06-05 16:41
@lilly-chen I think you modified the wrong file. You should check in lib/python3.7/site-packages/tensorflow/python/framework/ops.py what is the correct variable name, which i assume it should be `core_tf_types.Tensor`, according to your comment.

Then, you should modify the function 'is_tensor' in  file /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in
```
def is_tensor(x):
     return isinstance(x, tf_ops.Tensor) or tf_ops.is_dense_tensor_like(x)
```

**Comment by lilly-chen** [comment] 2020-06-12 04:31
> @lilly-chen I think you modified the wrong file. You should check in lib/python3.7/site-packages/tensorflow/python/framework/ops.py which is the correct name of the variable. I assume it should be `core_tf_types.Tensor`, according to your comment.
> 
> Then, you should modify the function 'is_tensor' in file /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in
> 
> ```
> def is_tensor(x):
>      return isinstance(x, core_tf_types.Tensor) or tf_ops.is_dense_tensor_like(x)
> ```
> 
> Note, you should import core as well. So, at the top of tensorflow_backend.py you should add
> `import core as core_tf_types`
> 
> Seems like some TF versions have the attribute defined in ops.py, while others import it from core.

Hi,
Thanks for the step by step!

here is the is_dense_tensor_like in my lib/python3.7/site-packages/tensorflow/python/framework/ops.py (i reinstalled my keras in a new environment)
```
def is_dense_tensor_like(t):
  return isinstance(t, core_tf_types._TENSOR_LIKE_TYPES)
```
then i go to my  /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py
here is the original version
```
 def is_tensor(x):
     return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)

```
i tried to change to 
```
import core as core_tf_types
def is_tensor(x):
    return isinstance(x, core_tf_types._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)

```
but i am getting a new error when i try to import keras
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e787bea10ca0> in <module>
----> 1 from keras.datasets import mnist
      2 import numpy as np
      3 np.random.seed(10)

~/anaconda3/lib/python3.7/site-packages/keras/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~/anaconda3/lib/python3.7/site-packages/keras/utils/__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

~/anaconda3/lib/python3.7/site-packages/keras/utils/conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

~/anaconda3/lib/python3.7/site-packages/keras/backend/__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

~/anaconda3/lib/python3.7/site-packages/keras/backend/load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

~/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in <module>
    705 #     return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
    706 # change by lilly
--> 707 import core as core_tf_types
    708 def is_tensor(x):
    709     return isinstance(x, core_tf_types._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)

ModuleNotFoundError: No module named 'core'
```

**Comment by NMazzatenta** [comment] 2020-06-12 06:50
@lilly-chen my mistake. I updated my last comment, now it should work.

**Comment by cvas-544** [comment] 2020-06-12 10:08
Hello @lilly-chen, 

I'm still facing the issue. Unfortunately i cannot find the  `core_tf_types.Tensor` variable in the file 
 "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow_core\python\framework\ops.py". 

![Capture](https://user-images.githubusercontent.com/54102782/84491814-6c9c8600-aca5-11ea-936c-c242415dbf1d.PNG)

Currently I'm using keras 2.3.1. 

Can you please help me ?

Thanks in advance!

**Comment by lilly-chen** [comment] 2020-06-12 17:18
> @lilly-chen my mistake. I edited my last comment, now it should work.

Hi when i go to my lib/python3.7/site-packages/tensorflow/python/framework/ops.py

i find the following import
`from tensorflow.python.types import core as core_tf_types`

and i go ahead and add this line in my /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py

```
from tensorflow.python.types import core as core_tf_types
def is_tensor(x):
    return isinstance(x, core_tf_types._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)

```

but it still not able to load the kera correctly

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-e787bea10ca0> in <module>
----> 1 from keras.datasets import mnist
      2 import numpy as np
      3 np.random.seed(10)

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/utils/__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/utils/conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/backend/__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/backend/load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

~/anaconda3/envs/deeplearning/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in <module>
     15 from tensorflow.python.ops import ctc_ops as ctc
     16 
---> 17 from tensorflow.python.types import core as core_tf_types
     18 
     19 from .common import floatx, epsilon, image_data_format

ModuleNotFoundError: No module named 'tensorflow.python.types'
```

Any suggestion is appreciated!

**Comment by bjourne** [comment] 2020-06-19 11:46
I'm also seeing the exact same problem.

**Comment by BV-SS** [comment] 2020-06-22 11:44
having impport error ..tensorflow and tflearn

AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

i  am experiencing same import error in tflearn as well as tensorflow ..when i comment out import tensorflow same error is been reported as shown below ...
also thse libraries where working just fine a couple of days before ...i had imported them without showing errors .
i have just added python socketio and flask packages in virtual env
using python 3.6.10
tflearn :0.3
tensorflow :1.14
![Screenshot (65)](https://user-images.githubusercontent.com/65727171/85283770-890d9f00-b4ab-11ea-9d42-2094a54d75a7.png)
![Screenshot (64)](https://user-images.githubusercontent.com/65727171/85283781-8dd25300-b4ab-11ea-91d2-69381ab042b5.png)

**Comment by fengwang** [comment] 2020-07-29 21:11
I solved this problem by redefining `is_tensor` in file `keras/backend/tensorflow_backend.py`:

```python
from tensorflow.python.framework import tensor_util
def is_tensor(x):                                                                                                                                                      
    return tensor_util.is_tensor(x)
    #return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
```

**Comment by rasisbuldan** [comment] 2020-08-02 04:34
@fengwang Thank you! this fixes my problem, on tensorflow 2.1.0

**Comment by Uniford** [comment] 2020-08-09 09:53
I've faced the same. Have used advice of @NMazzatenta, but changed it to the following:

> return  tf_ops.is_dense_tensor_like(x) or isinstance(x, core_tf_types._TENSOR_LIKE_TYPES)

instead of

> return   isinstance(x, core_tf_types._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)   

It worked. Seems like TENSOR_LIKE_TYPES can be deleted in some cases, because it started to work without entering in there.

Thank you,  @NMazzatenta!!

**Comment by alv-alvarez** [comment] 2020-08-10 18:20
Thank you @fengwang your solution it's working

**Comment by PVinay737** [comment] 2020-08-11 14:58
@fengwang  It gives a error of `RuntimeError: Attempting to capture an EagerTensor without building a function
`

**Comment by albisbub** [comment] 2020-08-18 17:33
can someone fix this in the main branch pweeeeeze

**Comment by rmanak** [comment] 2020-08-19 00:49
same issue here

**Comment by oattao** [comment] 2020-08-20 11:04
I had the same issue. I tried upgrade Keras to the newest version and the error gone.

**Comment by OmarHory** [comment] 2020-08-28 19:44
I changed everything from keras. to tensorflow.keras and it worked for me...

**Comment by flydragon2018** [comment] 2020-09-08 08:16
keras is merged to tensorflow.   I guess that is the problem.   

using tensorflow.keras instead of keras  after tensorflow 2.3,  It works for me.

**Comment by antonio-leblanc** [comment] 2020-09-12 03:22
Same Issue,
@flydragon2018 solution worked for me
replaced `keras`  -> `tensorflow.keras` when importing

**Comment by alexandresalem** [comment] 2020-09-12 20:05
You have to either use tensorflow.keras libraries in everything, or keras libraries in everything.
If you mix them, you are going to receive that error message.

**Comment by kivechang** [comment] 2020-09-22 03:39
I solved this problem , as of keras with tensorflow 2.3.0

def is_tensor(x):                                                                                                                                                      
    return tf_ops.is_dense_tensor_like(x)

**Comment by leandron** [comment] 2020-10-30 09:34
It looks like it is fixed on `keras ==2.4.3`.
(just in case you are here from search results)

**Comment by aleczoeller** [comment] 2020-11-05 23:42
> > > I had the same issue. TF 2.1 built from source + keras 2.3.1 in conda environment. Solved by modifying file "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py" at line 704.
> > > Before:
> > > `return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)`
> > > After:
> > > `return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)`
> > > Don't know if it is the right thing to do, but I got things running in this way.
> > 
> > 
> > @NMazzatenta After change the code as you support, I still have the issue. Can you help me to look at it ? Thanks
> > File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 703, in is_tensor
> > return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)
> > AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TENSOR_LIKE_TYPES'
> 
> @danhnguyen12091998 You should check the module "tensorflow.python.framework.ops" for the correct name of the attribute.
> 
> I retrieved it from the file at this path "/Users/nmazzatenta/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py" at line 216:
> 
> ```
> _TENSOR_LIKE_TYPES = tuple()
> 
> def is_dense_tensor_like(t):
> 
>   return isinstance(t, _TENSOR_LIKE_TYPES)
> ```

Had the same issue in Tensorflow 2.3, resolved with changing _TENSOR_LIKE_TYPES to core_tf_types.Tensor from that same line in ops.py

**Comment by talhaanwarch** [comment] 2020-11-21 22:46
i got this issue when i run with cmd, but when I run with spyder, I did not get the issue

**Comment by tejaswinih** [comment] 2020-11-30 04:40
Hi 

I too faced same issue within Python 3.7 virtual environment

So i resolved the issue by running the commands in the anaconda prompt as follows



pip3 install -U  tensorflow
pip3 install -U  keras
pip3 install -U  tensorflow-gpu

Now error is resolved for me.

**Comment by GaoangLiu** [comment] 2021-01-08 01:33
I experienced the same issue when running TensorLayer Basic Example: `MNIST_simple.py`. My error msg was:
```bash
Traceback (most recent call last):
  File "tutorial_mnist_simple.py", line 24, in <module>
    network = tl.models.Model(inputs=ni, outputs=nn, name="mlp")
  File "/Users/banana/anaconda3/envs/dl/lib/python3.8/site-packages/tensorlayer/models/core.py", line 214, in __init__
    if isinstance(check_argu, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(check_argu):
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
```
Following the error message, I checked on file `.../core.py`, found the code was like:
![before](http://git.io/JLxQK)

And I checked again on the file `.../framework/ops.py`. I found no such attribute `_TensorLike` in that file. Therefore I commented out the first part of the condition expression, changing it into 
![after](http://git.io/JLxQ1)

And everything went smoothly.

**Comment by robbinc91** [comment] 2021-02-25 19:37
I had the same issue.
First I was using TensorFlow 2.0.0 and Keras 2.3.1
Then I updated to 2.4.1. and the most recent version of Keras. But I had some troubles so I got back to version 2.0.0.
Then the error started.
After a day of looking everywhere on my computer, found that the version 2.4.1 had not entirely been eliminated from my system, and it was lik overriding my version 2.0.0
Found it in this folder:
C:\Users\{username}\AppData\Roaming\Python\Python37\site-packages\
I deleted everything on that folder and now it's working ok

I hope it helps.

**Comment by sandeep22-v** [comment] 2021-04-09 06:46
> I had the same issue. TF 2.1 built from source + keras 2.3.1 in conda environment. Solved by modifying file "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py" at line 704.
> Before:
> `return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)`
> After:
> `return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)`
> 
> Don't know if it is the right thing to do, but I got things running in this way.

Not working ser!!

**Comment by HuangZhenyang** [comment] 2021-04-25 01:06
@fengwang  Thank you. This solution works fine! :D

**Comment by ShaobinChen-AH** [comment] 2022-10-25 13:59
I uninstall the old keras and tensorflow, and then install the latest keras and tensorflow. Then the problem is solved.
