### ISSUE TITLE
UniqueV2 reports incorrect output shape

### ISSUE THREAD

**Issue by lukas-w** [tensorflow/tensorflow#31361] opened 2019-08-06 09:04 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04.6 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: Tesla K40C, 11441MiB

**Describe the current behavior**
When not using eager execution, UniqueV2 always reports its first output to have rank 1.

**Describe the expected behavior**
UniqueV2 should report its first output to have the same rank as its input.

**Code to reproduce the issue**
The bug can be exposed by forcing non-eager execution through `tf.function` or `tf.compat.v1.disable_eager_execution()`. The former is demonstrated below:
```py
import tensorflow as tf
from tensorflow.python.ops import gen_array_ops

def unique_rank(x, axis):
    unique = gen_array_ops.unique_v2(x, axis)
    return tf.rank(unique[0])

# 2D input should produce a 2D output
x = tf.ones([2, 2])
print("UniqueV2 output 0 rank:", tf.function(unique_rank)(x, [0]))
print("UniqueV2 output 0 rank executing eagerly:", unique_rank(x, [0]))
```
This outputs
```
UniqueV2 output 0 rank: tf.Tensor(1, shape=(), dtype=int32)
UniqueV2 output 0 rank executing eagerly: tf.Tensor(2, shape=(), dtype=int32)
```
but should output
```
UniqueV2 output 0 rank: tf.Tensor(2, shape=(), dtype=int32)
UniqueV2 output 0 rank executing eagerly: tf.Tensor(2, shape=(), dtype=int32)
```

**Comment by ravikyram** [comment] 2019-08-07 11:45
I have tried on colab with TF version 2.0 beta1,TF 2.0.0-dev20190805 and was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1RpI4ba9Dg7Elu2yr4jjdOkyQoJVc6f67) here.Thanks!

**Comment by alextp** [comment] 2019-08-08 16:09
@yongtang I think this was broken since https://github.com/tensorflow/tensorflow/commit/7603480f3 when uniquev2 was added.

Do you have time to work on this?

**Comment by alextp** [comment] 2019-08-08 16:11
Tatiana, can you shepherd this from the TF ops side? The issue is that the shape inference function for uniquev2 ignores the fact that when axis is specified it preserves rank

**Comment by tatianashp** [comment] 2019-08-08 19:20
I think this falls into Rasmus's domain of expertise.

**Comment by yongtang** [comment] 2019-10-11 03:29
With the latest tf-nightly the result works correctly:
```python
# python v.py 
('UniqueV2 output 0 rank:', <tf.Tensor: shape=(), dtype=int32, numpy=2>)
('UniqueV2 output 0 rank executing eagerly:', <tf.Tensor: shape=(), dtype=int32, numpy=2>)
# python -c 'import tensorflow as tf; print(tf.version.VERSION)'
2.1.0-dev20191010
```

I think the issue has been resolved.

**Comment by jvishnuvardhan** [comment] 2019-10-17 00:02
As @yongtang mentioned, this was resolved in `tf-nightly`. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/04693a821f4c3e3eef2a1b38088af9e5/untitled574.ipynb) is the gist for your reference.

I am closing the issue as it was resolved in `tf-nightly`. Please feel free to open it if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-10-17 00:02 UTC
Labels: TF 2.0, comp:ops, type:bug
