### ISSUE TITLE
tensorflow problem

### ISSUE THREAD

**Issue by tbousole** [tensorflow/tensorflow#18738] opened 2018-04-20 15:46 UTC
how to solve the following error? ImportError: No module named '_pywrap_tensorflow_internal'
I have python  3.5 installed, Jupyter Notebook along with Ananconda also installed.

**Comment by cchan** [comment] 2018-04-20 17:02
Hi @tbousole, can you provide more information? At minimum, tensorflow version and a piece of code that reproduces the error would be needed.

**Comment by tbousole** [comment] 2018-04-20 21:04
import tensorflow as tf

reset_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

i am using tensorflow version 1.5

**Comment by vijaysaimutyala** [comment] 2018-04-23 00:40
@tboousele, if you're using the CPU version on Windows, can you please try installing version 1.4. This turned out to be a good workaround for a friend of mine.

**Comment by cchan** [comment] 2018-04-23 17:09
@tbousole what is `reset_graph()`? The following code works fine for me:
```
import tensorflow as tf

tf.reset_default_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x * y + y + 2
```

**Comment by cchan** [comment] 2018-04-23 17:10
Perhaps also take a look at #11571.

**Comment by angersson** [comment] 2018-04-25 18:01
This is a duplicate of #11571 (thanks for the link, @cchan). Please move discussion over there so that advice is not spread across the tracker. Thanks!

**Closed by angersson** 2018-04-25 18:01 UTC
Labels: type:build/install
