### ISSUE TITLE
TensorFlow SavedModel export fails with AttributeError

### ISSUE THREAD

**Issue by tobiaszwingmann** [tensorflow/tensorflow#34592] opened 2019-11-25 20:22 UTC
I'm following the tutorial exactly as it is here: https://www.tensorflow.org/tutorials/keras/text_classification_with_hub

Finally, if I want to export the trained model from this tutorial using model.save() I get this error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-768eb5acd4e8> in <module>()
      3 
      4 export_path = "/tmp/saved_models/{}".format(int(t))
----> 5 model.save(export_path, save_format='tf')

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
    984     """
    985     saving.save_model(self, filepath, overwrite, include_optimizer, save_format,
--> 986                       signatures, options)
    987 
    988   def save_weights(self, filepath, overwrite=True, save_format=None):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,
--> 115                           signatures, options)
    116 
    117 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save.py in save(model, filepath, overwrite, include_optimizer, signatures, options)
     72   # default learning phase placeholder.
     73   with K.learning_phase_scope(0):
---> 74     save_lib.save(model, filepath, signatures, options)
     75 
     76   if not include_optimizer:

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/save.py in save(obj, export_dir, signatures, options)
    905   # Note we run this twice since, while constructing the view the first time
    906   # there can be side effects of creating variables.
--> 907   _ = _SaveableView(checkpoint_graph_view)
    908   saveable_view = _SaveableView(checkpoint_graph_view)
    909 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/save.py in __init__(self, checkpoint_view)
    189           concrete_functions = [function]
    190         for concrete_function in concrete_functions:
--> 191           if concrete_function.name not in seen_function_names:
    192             seen_function_names.add(concrete_function.name)
    193             self.concrete_functions.append(concrete_function)

AttributeError: 'NoneType' object has no attribute 'name'
```

What's going on? Shouldn't it be possible to simply export this model to the `SavedModel` format? I'm trying with and without the `save_format='tf'` parameter.

**Comment by gowthamkpr** [comment] 2019-11-25 21:20
Can you please provide a simple reproducible case for us to look into the issue as the information provided is too vague to find the root cause. Thanks!

**Comment by tobiaszwingmann** [comment] 2019-11-25 21:40
Here you go: 

```
!pip install tensorflow==2.0 
!pip install -q tensorflow-hub
!pip install -q tensorflow-datasets

import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.experimental.list_physical_devices("GPU") else "NOT AVAILABLE")


# Split the training set into 60% and 40%, so we'll end up with 15,000 examples
# for training, 10,000 examples for validation and 25,000 examples for testing.
train_validation_split = tfds.Split.TRAIN.subsplit([6, 4])

(train_data, validation_data), test_data = tfds.load(
    name="imdb_reviews", 
    split=(train_validation_split, tfds.Split.TEST),
    as_supervised=True)

embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])


history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=2,
                    validation_data=validation_data.batch(512),
                    verbose=1)

model.save('tmp')
```

**Comment by gowthamkpr** [comment] 2019-11-25 21:44
Was able to reproduce the issue. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/e7c994341d6d4f2b6757b03cc4359fd2/copy-of-text_classification_with_hub.ipynb).

**Comment by ElliotVilhelm** [comment] 2020-01-07 21:21
I am having the same issue

**Comment by yhliang2018** [comment] 2020-01-23 23:11
This issue is fixed in latest tf-nightly. Close this for now. Feel free to reopen it if needed.

**Closed by yhliang2018** 2020-01-23 23:11 UTC
Labels: TF 2.0, comp:keras, stat:awaiting tensorflower, type:bug
