### ISSUE TITLE
UnboundLocalError: local variable 'weights_normed' referenced before assignment

### ISSUE THREAD

**Issue by gyc521zsc** [tensorflow/tensorflow#34026] opened 2019-11-06 01:56 UTC
This is my code, it can be trained normally, but when he tests, he gives an error.
![image](https://user-images.githubusercontent.com/50411057/68261608-9f313100-007b-11ea-93e8-54c497055e91.png)

**Comment by oanush** [comment] 2019-11-07 09:52
@gyc521zsc ,
Can you please assemble a minimal reproducible code snippet to reflect this issue? Also include your TensorFlow version.Thanks!

**Comment by gyc521zsc** [comment] 2019-11-07 10:55
Thank you for your reply.    tensorflow-gpu==1.1.0
![image](https://user-images.githubusercontent.com/50411057/68382740-49e64400-018f-11ea-8536-f47c5164400e.png)


I have a problem: LossTensor is inf or nan : Tensor had NaN values
![image](https://user-images.githubusercontent.com/50411057/68382860-874ad180-018f-11ea-92c1-bc00f64d259a.png)


I added a few lines of code, but it's still wrong.
![image](https://user-images.githubusercontent.com/50411057/68383127-02ac8300-0190-11ea-9c05-23b61d2c50c9.png)

looking forward to your reply!

**Comment by oanush** [comment] 2019-11-08 11:26
@gyc521zsc ,
Can you please provide the minimal reproducible code in colab gist or .ipynb file format so that we can try replicate the issue from our end. Thanks!

**Comment by oanush** [comment] 2019-11-20 08:16
@gyc521zsc ,
Any update on the issue?Thanks!

**Comment by oanush** [comment] 2019-11-25 09:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-11-25 09:41 UTC
Labels: comp:apis, type:support
