### ISSUE TITLE
Second order gradient of tf.contrib.eager.function is broken

### ISSUE THREAD

**Issue by fps7806** [tensorflow/tensorflow#29916] opened 2019-06-18 16:12 UTC
When using 2nd order gradients (i.e. Nested GradientTape) we cannot utilize @tf.defun and @tf.function.

**System information**
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 1.13.1

```
Traceback (most recent call last):
  File "test_defun.py", line 14, in <module>
    print(meta_tape.gradient(a2, a))
  File "/home/felipe.such/uber/generative_learning/env/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 946, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/felipe.such/uber/generative_learning/env/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 72, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/felipe.such/uber/generative_learning/env/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 127, in _gradient_function
    grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
  File "/home/felipe.such/uber/generative_learning/env/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 94, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: StatefulPartitionedCall
```

**Code to reproduce the issue**

```
import tensorflow as tf

tf.enable_eager_execution()

@tf.contrib.eager.function
def leaky_relu(x, alpha=0.1):
  return tf.maximum(tf.minimum(0.0, alpha * x), x)

a = tf.Variable(())
with tf.GradientTape() as meta_tape:
  with tf.GradientTape() as tape:
    x = leaky_relu(a)
  a2 = tape.gradient(x, a) + a
print(meta_tape.gradient(a2, a))
```

**Comment by achandraa** [comment] 2019-06-19 12:04
Have tried on Colab with TF 13.1 and was able to reproduce the issue.

**Comment by veqtor** [comment] 2019-06-19 13:42
Maybe related?
https://github.com/tensorflow/tensorflow/issues/29942

**Comment by jvishnuvardhan** [comment] 2019-06-28 18:11
@fps7806 I could reproduce the issue with TF1.13.1 but I don't see any error with TF.1.14.0. I created a [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/bc4e6c61ebbe156c20fab10a9de3e51c/tf_29916.ipynb). Please check it. thanks!

**Comment by tensorflowbutler** [comment] 2019-07-13 12:25
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-07-15 16:39
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-07-15 16:39 UTC
Labels: TF 1.13, comp:eager, comp:ops, stat:awaiting response, type:bug/performance
