### ISSUE TITLE
feedable iterator deal sparse feature error

### ISSUE THREAD

**Issue by guangyuyan** [tensorflow/tensorflow#29347] opened 2019-06-03 07:30 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.13
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no cuda
- GPU model and memory: no gpu

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
except error when run tf.data.Iterator.from_string_handle(handle, training_dataset.output_types, training_dataset.output_shapes)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Data type mismatch at component 0: expected int32 but got variant.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[output_shapes=[[?,?]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

print(training_dataset.output_types)
<dtype: 'int32'>

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by guangyuyan** [comment] 2019-06-03 07:31
tfrecords parser:
def parser(record):
keys_to_features = {
"feature_ids": tf.VarLenFeature(tf.int64)
# "feature_vals": tf.VarLenFeature(tf.float32),
# "label": tf.FixedLenFeature((), tf.float32)
}
parsed = tf.parse_single_example(record, keys_to_features)
# label = tf.cast(parsed["label"], tf.float64)
feature_ids = tf.cast(parsed["feature_ids"], tf.int32)
# feature_vals = tf.cast(parsed["feature_vals"], tf.float64)
return feature_ids

**Comment by guangyuyan** [comment] 2019-06-03 07:32
def parser(record):
keys_to_features = {
"feature_ids": tf.VarLenFeature(tf.int64)
}
parsed = tf.parse_single_example(record, keys_to_features)
feature_ids = tf.cast(parsed["feature_ids"], tf.int32)
return feature_ids

**Comment by guangyuyan** [comment] 2019-06-03 13:04
seems it does not support sparse feature..

**Comment by guangyuyan** [comment] 2019-06-03 13:06
when i just feed fixedlen 'label', it works, but when i feed varlen 'feature_ids' or 'feature_vals', it except above error, so seems it does not support sparse feature

**Comment by gadagashwini** [comment] 2019-06-04 06:39
@guangyuyan In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-06-11 04:17
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-11 04:17 UTC
Labels: TF 1.13, comp:data, stat:awaiting response, type:support

**Comment by guangyuyan** [comment] 2019-07-19 10:15
def tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size, shuffle_buffer_size,
				   batch_size, epochs, input_files):
	dataset = tf.data.TFRecordDataset(input_files, num_parallel_reads = parallel_reads_per_file)
	# dataset = tf.data.Dataset.from_tensor_slices(input_files)
	dataset = dataset.map(parser, num_parallel_calls = parallel_parse)
	dataset = dataset.shuffle(shuffle_buffer_size, seed=1)
	# dataset = dataset.padded_batch(batch_size, padded_shapes=[None])
	dataset = dataset.batch(batch_size)
	dataset = dataset.prefetch(buffer_size=prefetch_buffer_size)
	dataset = dataset.repeat(epochs)

	###feedable dataset iterator for train valid data switch###
	training_dataset = tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size, shuffle_buffer_size, batch_size, epochs, train_tfrecord_path)
	validation_dataset = tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size,shuffle_buffer_size, batch_size, epochs, test_tfrecord_path)

	handle = tf.placeholder(tf.string, shape=[])
	iterator = tf.data.Iterator.from_string_handle(
		handle, training_dataset.output_types, training_dataset.output_shapes)
	ids, values, label = iterator.get_next()
	# next_element = training_iterator.get_next()
	# ids, values, label = training_iterator.get_next()

	training_iterator = training_dataset.make_initializable_iterator()
	validation_iterator = validation_dataset.make_initializable_iterator()
	# validation_iterator = validation_dataset.make_initializable_iterator()
	
	with tf.Session() as sess:
		training_handle = sess.run(training_iterator.string_handle())
		validation_handle = sess.run(validation_iterator.string_handle())
		sess.run(label, feed_dict={handle: training_handle})

error:
InvalidArgumentError (see above for traceback): Data type mismatch at component 0: expected int64 but got variant.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[output_shapes=[[?,?], [?,?], [?]], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

**Comment by guangyuyan** [comment] 2019-07-19 10:17
def tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size, shuffle_buffer_size,
				   batch_size, epochs, input_files):
	dataset = tf.data.TFRecordDataset(input_files, num_parallel_reads = parallel_reads_per_file)
	# dataset = tf.data.Dataset.from_tensor_slices(input_files)
	dataset = dataset.map(parser, num_parallel_calls = parallel_parse)
	dataset = dataset.shuffle(shuffle_buffer_size, seed=1)
	dataset = dataset.batch(batch_size)
	dataset = dataset.prefetch(buffer_size=prefetch_buffer_size)
	dataset = dataset.repeat(epochs)
	return dataset


	###feedable dataset iterator for train valid data switch###
	training_dataset = tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size, shuffle_buffer_size, batch_size, epochs, train_tfrecord_path)
	validation_dataset = tfrecord_input(parallel_reads_per_file, parallel_parse, prefetch_buffer_size,shuffle_buffer_size, batch_size, epochs, test_tfrecord_path)

	handle = tf.placeholder(tf.string, shape=[])
	iterator = tf.data.Iterator.from_string_handle(
		handle, training_dataset.output_types, training_dataset.output_shapes)
	ids, values, label = iterator.get_next()

	training_iterator = training_dataset.make_initializable_iterator()
	validation_iterator = validation_dataset.make_initializable_iterator()	

	with tf.Session() as sess:
		training_handle = sess.run(training_iterator.string_handle())
		validation_handle = sess.run(validation_iterator.string_handle())
		sess.run(label, feed_dict={handle: training_handle})


error:
InvalidArgumentError (see above for traceback): Data type mismatch at component 0: expected int64 but got variant.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[output_shapes=[[?,?], [?,?], [?]], output_types=[DT_INT64, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]
