### ISSUE TITLE
Link Broken on tutorials/images/object detection API

### ISSUE THREAD

**Issue by pana1990** [tensorflow/tensorflow#40862] opened 2020-06-27 08:08 UTC
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

This link is broken https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

![image](https://user-images.githubusercontent.com/6630197/85917788-7c979680-b85d-11ea-8d93-0fae5b8d9bf2.png)

### Correct links

Is the link to the source code correct?

Yes, this one [https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb)

### Submit a pull request?

No.

**Comment by amahendrakar** [comment] 2020-06-29 13:52
@pana1990,
Looks like this is a duplicate of issue [#8698](https://github.com/tensorflow/models/issues/8698).

Can you please close this issue since it is already being tracked in the TensorFlow models repo. Thanks!

**Comment by pana1990** [comment] 2020-06-29 17:34
@amahendrakar ups, it's true, thanks a lot for your reply ;)

**Closed** 2020-06-29 17:34 UTC
Labels: stat:awaiting response, type:docs-bug
