### ISSUE TITLE
Hexagon delegate fails on a known good model

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#53423] opened 2021-12-14 17:39 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Snapdragon 855
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.7
- Python version: 3.7
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): gcc 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

When running inference with TFlite and Hexagon delegate,
initialization fails with the following message:

09-19 08:24:18.566  4958  4958 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
09-19 08:24:18.568  4958  4958 E tflite  : Calling prepare multiple times
09-19 08:24:18.568  4958  4958 E tflite  : Node number 90 (TfLiteHexagonDelegate) failed to prepare.
09-19 08:24:18.775  4958  4958 E tflite  : Restored original execution plan after delegate application failure.
09-19 08:24:18.782  4958  4958 E tflite  : Error in applying the default TensorFlow Lite delegate indexed at 0, and all previously applied delegates are reverted.

**Describe the expected behavior**

When using the same model with the same code compiled against TensorFlow 2.3, it works fine.
See attached the model in question.
[model.zip](https://github.com/tensorflow/tensorflow/files/7713641/model.zip)

**Comment by mohantym** [comment] 2021-12-15 06:37
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by yakovdan** [comment] 2021-12-19 15:24
Hi, are there any updates on this issue?

**Comment by karimnosseir** [comment] 2021-12-22 15:35
That looks like related to the new effort to enable Xnnpack by default.

@multiverse-tf Can you check it please.

**Comment by multiverse-tf** [comment] 2021-12-23 07:54
> That looks like related to the new effort to enable Xnnpack by default.
> 
> @multiverse-tf Can you check it please.
> 
> EDIT: Verified on device that disabling Xnnpack resolves the issue.

I could also verify that disabling XNNPACK resolved the issue. There are two ways to disable the XNNPACK-by-default feature, and you could choose either of them to achieve:
1. Build the Tensorflow Lite library to disable this feature. If using Bazel, you could add "--define=tflite_with_xnnpack=false" flag.
2. If you could change your code, use [BuiltinOpResolverWithoutDefaultDelegates](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.h#L39) instead of BuiltinOpResolver when creating the TFLite interpreter.

Meanwhile, we will investigate the root cause and push a fix asap. Sorry for the inconvenience.

**Comment by multiverse-tf** [comment] 2022-01-18 05:44
@yakovdan A [fix](https://github.com/tensorflow/tensorflow/commit/c8bafb818a10928b366ad9328ce6091596f0d4f2) has been pushed. Could you try your code again?

**Comment by karimnosseir** [comment] 2022-02-08 16:05
Fix was merged. Closing

**Closed by karimnosseir** 2022-02-08 16:05 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:lite, TFLiteHexagonDelegate, TF 2.7
