### ISSUE TITLE
node softmax_cross_entropy_with_logits

### ISSUE THREAD

**Issue by joyjeni** [tensorflow/tensorflow#32450] opened 2019-09-12 00:25 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab

- TensorFlow version:1.14.0
- Python version:3.6.8

**Describe the problem**

** I have created custom model for cifar 10 dataset. I m unable to use tf.nn.softmax_cross_entropy_with_logits_v2 gets   Invalid argument: logits and labels must be broadcastable: logits_size=[128,10] labels_size=[1,128]

The entire source code can be viewed at 
https://colab.research.google.com/drive/11tyipxzE9qkmlwkiPhs-A8I2OvT5Jebi

**Comment by ravikyram** [comment] 2019-09-13 08:42
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by joyjeni** [comment] 2019-09-13 09:36
I have given shared permission you can check now

**Comment by ravikyram** [comment] 2019-09-16 11:23
@joyjeni 
Can you please help me with the files. It helps us to reproduce the issue in our environment.Thanks!

**Comment by joyjeni** [comment] 2019-09-17 05:26
It's fixed from my end. It was the behavior with calculating the loss on batches

**Comment by ravikyram** [comment] 2019-09-17 05:43
I am closing this issue since it looks to be fixed. Thanks!

**Closed by ravikyram** 2019-09-17 05:43 UTC
Labels: TF 1.14, comp:apis, stat:awaiting response, type:support

**Comment by 2696120622** [comment] 2020-04-01 06:43
> It's fixed from my end. It was the behavior with calculating the loss on batches

@joyalbin 
Hello, I have encountered the same error:
"Error recorded from training_loop: logits and labels must be broadcastable: logits_size=[4000,2] labels_size=[8,2]"
How to fix this error?

**Comment by RANA-ATI** [comment] 2023-04-11 11:31
Getting the same kind of error 

Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?2a4c9f93-c76b-4453-b752-df80a172b66c)---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Cell In[31], line 3
      1 batch_size = 16
      2 epochs = 15
----> 3 history = model.fit(train_dataset, 
      4             batch_size = batch_size, 
      5             validation_data = validation_dataset, 
      6             epochs = epochs,
      7             callbacks = callbacks)

File [d:\Anaconda\envs\keras\lib\site-packages\keras\engine\training.py:1184](file:///D:/Anaconda/envs/keras/lib/site-packages/keras/engine/training.py:1184), in Model.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1177 with tf.profiler.experimental.Trace(
   1178     'train',
   1179     epoch_num=epoch,
   1180     step_num=step,
   1181     batch_size=batch_size,
   1182     _r=1):
   1183   callbacks.on_train_batch_begin(step)
-> 1184   tmp_logs = self.train_function(iterator)
   1185   if data_handler.should_sync:
   1186     context.async_wait()

File [d:\Anaconda\envs\keras\lib\site-packages\tensorflow\python\eager\def_function.py:885](file:///D:/Anaconda/envs/keras/lib/site-packages/tensorflow/python/eager/def_function.py:885), in Function.__call__(self, *args, **kwds)
    882 compiler = "xla" if self._jit_compile else "nonXla"
...
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at [C:\Users\ATI\AppData\Local\Temp\ipykernel_3960\2751684548.py:3](file:///C:/Users/ATI/AppData/Local/Temp/ipykernel_3960/2751684548.py:3)) ]] [Op:__inference_train_function_42206]

Function call stack:
train_function
