### ISSUE TITLE
keras call convert_model from theano error.

### ISSUE THREAD

**Issue by tchaton** [tensorflow/tensorflow#19047] opened 2018-05-03 08:29 UTC
convert_model(model)
  File "../utils.py", line 31, in convert_model
    ops.append (tf.assign (layer.kernel, converted_w).op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 273, in assign
    if ref.dtype._is_ref_dtype:
AttributeError: 'str' object has no attribute '_is_ref_dtype'

**Comment by tensorflowbutler** [comment] 2018-05-03 18:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-05-26 18:54
It has been 22 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-06-10 21:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-06-22 16:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-06-22 16:11 UTC
Labels: stat:awaiting response
