### ISSUE TITLE
cuda9.1 can not support tensorflow

### ISSUE THREAD

**Issue by dorothy9297** [tensorflow/tensorflow#29044] opened 2019-05-27 01:56 UTC
import tensorflow as tf
Traceback (most recent call last):
File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by dorothy9297** [comment] 2019-05-27 01:58
I resolved it by the flowing  link
- https://github.com/tensorflow/tensorflow/issues/26870
- https://blog.csdn.net/qq_36556893/article/details/79433298

**Comment by gadagashwini** [comment] 2019-05-28 05:07
@dorothy9297 Good to know the issue is resolved. Will close the issue. Thanks!

**Closed by gadagashwini** 2019-05-28 05:07 UTC
Labels: subtype:windows, type:build/install
