### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'h'

### ISSUE THREAD

**Issue by shliang0603** [tensorflow/tensorflow#28581] opened 2019-05-10 02:58 UTC
@jmhodges @ry @bmabey @djones I want to look at my own parameters in command line. I used `'python main.py -h '`  . But this error occurred 'absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'h''. I use tensorflow-gpu == 1.10.0 . Can you give me some advice ?

*Here is my code :*
```python
Flags = tf.app.flags

Flags.DEFINE_integer('rand_seed', 1 , 'random seed' )

# Directories
Flags.DEFINE_string('input_dir_LR', None, 'The directory of the input resolution input data, for inference mode')
Flags.DEFINE_string('input_dir_HR', None, 'The directory of the input resolution input data, for inference mode')
Flags.DEFINE_string('mode', 'inference', 'train, or inference')
Flags.DEFINE_string('output_dir', None, 'The output directory of the checkpoint')
Flags.DEFINE_string('output_pre', 'images', 'The output pre of the images')
Flags.DEFINE_string('output_ext', 'jpg', 'The format of the output when evaluating')
Flags.DEFINE_string('summary_dir', None, 'The dirctory to output the summary')

# Models
Flags.DEFINE_string('checkpoint', None, 'If provided, the weight will be restored from the provided checkpoint')
Flags.DEFINE_integer('num_resblock', 16, 'How many residual blocks are there in the generator')

# Machine resources
Flags.DEFINE_string('cudaID', '0', 'CUDA devices')

FLAGS = Flags.FLAGS
```

**Comment by achandraa** [comment] 2019-05-13 09:48
Please provide details about what platform you are using (operating system, architecture). 
Make sure you also include the exact command if possible to produce the output included in your test case. You can refer this [link](https://github.com/tensorflow/tensorflow/issues/new/choose) to fill in the template. Thanks!

**Comment by jmhodges** [comment] 2019-05-14 00:31
@shliang0603 hey, I'm not a tensorflow maintainer or anything so please don't include me like this. It sends me noisy notifications that I can't do anything about

**Comment by achandraa** [comment] 2019-05-20 05:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-20 05:37 UTC
Labels: stat:awaiting response, type:support

**Comment by tlranda** [comment] 2019-06-11 15:18
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution:
Linux Fedora 30
- TensorFlow version:
1.13.1
- Python version:
3.7.3

**Describe the current behavior**

Depending on how source code using tf.app.flags is written, the -h, -help, -helpshort, and -helpfull arguments may cause exceptions to be triggered as opposed to displaying flags, default values, and programmer-provided information.

**Describe the expected behavior**

When any value of -h, -help, -helpshort, -helpfull are provided as arguments to scripts using tf.app.flags, the help list should appear.

**Code to reproduce the issue**
```python
''' mwe.py: displays tensorflow --help argument issue '''
from tensorflow import app
app.flags.DEFINE_string('myflag', 'Default', 'Help output')
FLAGS = app.flags.FLAGS
global_string = "This string causes absl to begin processing the {0} flag".format(FLAGS.myflag)
def main(_):
  print("This string causes TF to race the absl parsing process, which kills the help menu using string %s" % FLAGS.myflag)
if __name__ == '__main__':
  app.run(main)
```

**Other info / logs**
Run the above code as follows to see the difference in output. The first run will trigger an exception due to Tensorflow attempting to use its implicit parsing procedure. The second run will not because the script will explicitly wait for all flags to be fully parsed before proceeding.
```bash
python mwe.py --help
sed -i 's/garbage/#garbage/g' mwe.py
python mwe.py --help
```
