### ISSUE TITLE
Cannot successfully serialize and restore model using either 'tf' or 'h5' format

### ISSUE THREAD

**Issue by fonnesbeck** [tensorflow/tensorflow#35159] opened 2019-12-16 16:51 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux on Google Cloud instance
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.1.0.rc1
- Python version: 3.7.3

**Describe the current behavior**

I've attempted to save a TF regression model in 'h5' format as follows:

    model_mean.save(HITTER_MODEL_DIR + 'hitter_model_mean.h5', save_format='h5')

however this fails:

```
ValueError                                Traceback (most recent call last)
<ipython-input-100-bf2d7187a55e> in <module>()
----> 1 model_mean.save(HITTER_MODEL_DIR + 'hitter_model_mean.h5', save_format='h5')

4 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py in create_group(self, name, track_order)
     58             name, lcpl = self._e(name, lcpl=True)
     59             gcpl = Group._gcpl_crt_order if track_order else None
---> 60             gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
     61             return Group(gid)
     62 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.create()

ValueError: Unable to create group (name already exists)
```

I then attempt to save as 'tf' format:

    model_mean.save(HITTER_MODEL_DIR + 'hitter_model_mean', save_format='tf')

which succeeds, however, attempting to load the model fails:

```
tf.keras.models.load_model(HITTER_MODEL_DIR + 'hitter_model_mean')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-99-37062ae44748> in <module>()
----> 1 tf.keras.models.load_model(HITTER_MODEL_DIR + 'hitter_model_mean')

17 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/function_deserialization.py in restored_function_body(*args, **kwargs)
    260         .format(_pretty_format_positional(args), kwargs,
    261                 len(saved_function.concrete_functions),
--> 262                 "\n\n".join(signature_descriptions)))
    263 
    264   concrete_function_objects = []

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("inputs:0", shape=(None, 2), dtype=float32)
  Keyword arguments: {}

Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (1 total):
    * [TensorSpec(shape=(None, 2), dtype=tf.float32, name='inputs/0')]
  Keyword arguments: {}
```

**Comment by fonnesbeck** [comment] 2019-12-16 17:45
I've tried giving each layer in the model unique names, but it does not affect the 'h5' saving error at all.

**Comment by fonnesbeck** [comment] 2019-12-16 18:50
Forgot to mention that the model contains a TFP layer (the last layer in the network); not sure if that's the reason I'm getting this. Otherwise the network is pretty simple. Here's the model:

```python
inputs = Input(shape=(X.shape[1],))
hidden = BatchNormalization()(inputs)
hidden = Dense(1024, activation="relu")(hidden)
hidden = Dropout(0.5)(hidden)
hidden = BatchNormalization()(hidden)
hidden = Dense(512, activation="relu")(hidden)
hidden = Dropout(0.5)(hidden)
hidden = BatchNormalization()(hidden)
hidden = Dense(256, activation="relu")(hidden)
hidden = Dropout(0.5)(hidden)
hidden = BatchNormalization()(hidden)
hidden = Dense(128, activation="relu")(hidden)
params = Dense(2)(hidden)
dist = tfp.layers.DistributionLambda(normal_sp)(params) 
 
model = Model(inputs=inputs, outputs=dist)
```

**Comment by oanush** [comment] 2019-12-18 11:02
@fonnesbeck ,
Thank you for reporting the issue, could you please provide a standalone code to reproduce the error?

**Comment by oanush** [comment] 2019-12-31 09:32
@fonnesbeck ,
Any update on the issue?Thanks!

**Comment by fonnesbeck** [comment] 2019-12-31 16:16
It still does not work, but the data is proprietary so I need to take the time to make a working example without the data.

**Comment by oanush** [comment] 2020-01-08 09:53
@fonnesbeck ,
Hello,Got a chance build a working example?Thanks!

**Comment by oanush** [comment] 2020-01-13 10:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2020-01-13 10:13 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support
