### ISSUE TITLE
Error with cude even with tf nightly

### ISSUE THREAD

**Issue by LucasColas** [tensorflow/tensorflow#47615] opened 2021-03-07 05:42 UTC
<em>Please make sure that this is a bug. As per our

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I juste wrote `from tensorflow.keras import layers
`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): W10 Family
- TensorFlow installed from (source or binary): Don't
- TensorFlow version (use command below):  tf-estimator-nightly-2.5.0.dev2021030601 
pip install tf-nightly-gpu
- Python version: 3.7
- CUDA/cuDNN version: 11.2
- GPU model and memory: GTX 1660TI 6gb

**Describe the current behavior**
I try to run script using tensorflow . But I have : 

> 2021-03-07 06:41:09.619717: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-07 06:41:09.634433: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Describe the expected behavior**
I should not have an error.

**Standalone code to reproduce the issue**
Write a script with this code : `from tensorflow.keras import layers
`
pip install tf-nightly-gpu

**Comment by amahendrakar** [comment] 2021-03-08 11:50
@LucasColas,
Every TensorFlow release is compatible with a certain CUDA/cuDNN version, for more information please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu). 

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1

In this case, can you please try installing **TensorFlow v2.4** with **CUDA 11.0** and **cuDNN 8** and check if you are facing the same error. Thanks!

**Comment by amahendrakar** [comment] 2021-03-08 11:51
Also, seems like this is a duplicate of issue [#47602](https://github.com/tensorflow/tensorflow/issues/47602). Can we close this issue as it is already being tracked there. Thanks!

**Closed** 2021-03-22 12:37 UTC
Labels: TF 2.5, comp:gpu, stalled, stat:awaiting response, type:support
