### ISSUE TITLE
i try to run a python code using tensorflow and Mask RCNN but i get that error

### ISSUE THREAD

**Issue by mhmedeng** [tensorflow/tensorflow#31645] opened 2019-08-15 13:45 UTC
check failed status == cudnn_status_success (7 vs. 0)failed to set cudnn stream

i am using 

tensorflow  1.14.0
cuda  10.0

**Comment by mcguires5** [comment] 2019-08-15 15:00
Did you download the CUDNN files and place them in the appropriate files in the CUDA folders?

**Comment by mhmedeng** [comment] 2019-08-15 19:52
> Did you download the CUDNN files and place them in the appropriate files in the CUDA folders?

tensorflow-gpu install CUDDN when i downloaded it

**Comment by gadagashwini** [comment] 2019-08-16 10:10
@mhmedeng, 
Please provide details about what platform you are using (operating system, architecture).

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mhmedeng** [comment] 2019-08-16 12:00
> @mhmedeng,
> Please provide details about what platform you are using (operating system, architecture).
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

windows 7  64 bit
nvidia quadro k1100
processor : Intel Core i7 CPU 2.8 GHz
i installed tensorflow-gpu 1.14.0 and cuda 10.0
i am trying to run demo file in samples folder of Mask_RCNN

![Capture](https://user-images.githubusercontent.com/23197541/63166261-2ac39480-c02e-11e9-9a4b-c5d41f50c17e.PNG)

**Comment by gadagashwini** [comment] 2019-08-19 08:07
@mhmedeng,
Please provide the minimal code to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-08-26 08:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-26 08:52 UTC
Labels: TF 1.14, comp:gpu, stat:awaiting response, type:support
