### ISSUE TITLE
The flag 'log_dir' is defined twice.

### ISSUE THREAD

**Issue by ljdang** [tensorflow/tensorflow#30472] opened 2019-07-08 04:36 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: Python 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: N/A

**Describe the current behavior**
DuplicateFlagError: The flag 'log_dir' is defined twice.

**Code to reproduce the issue**
import tensorflow as tf
from absl import flags
flags.DEFINE_string('log_dir', './log', 'Log directory')

**Comment by gadagashwini** [comment] 2019-07-09 12:29
I am able to reproduce the issue with Tensorflow 1.14.0 on Colab.

**Comment by mihaimaruseac** [comment] 2019-07-10 20:05
I don't think this is a TensorFlow issue as you are just redefining a flag that tensorflow knows.

It can be argued that TensorFlow should not need flags as it is a library, though.

**Comment by alextp** [comment] 2019-07-11 09:37
@mihaimaruseac do you know where do we define the log_dir flag? I can't find it in a cursory search of the TF codebase...

**Comment by mihaimaruseac** [comment] 2019-07-11 13:54
We don't, it's abseil defining it as soon as one of abseil modules is imported.

**Comment by jackwish** [comment] 2019-07-22 07:59
Encountered similar issue when using [PocketFlow]() which is running on top of TensorFlow. The message
```
wzh@docker2[✓]PocketFlow (r1.14*) $ ./scripts/run_local.sh nets/resnet_at_cifar10_run.py
Python script: nets/resnet_at_cifar10_run.py
# of GPUs: 1
extra arguments:  --model_http_url https://api.ai.tencent.com/pocketflow --data_dir_local /home/wzh/datasets/cifar/cifar-10-batches-bin
Traceback (most recent call last):
  File "utils/get_idle_gpus.py", line 38, in <module>
    gpu_smi_output = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'nvidia-smi --query-gpu=index,memory.used,memory.total --format=csv,noheader,nounits' returned non-zero exit status 9.
'nets/resnet_at_cifar10_run.py' -> 'main.py'
multi-GPU training disabled
[WARNING] TF-Plus & Horovod cannot be imported; multi-GPU training is unsupported
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    tf.app.flags.DEFINE_string('log_dir', './logs', 'logging directory')
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from main.py.  Description from first occurrence: directory t
o write logfiles into
```

When with TF 1.12, there is no such issue. With TF 1.14, the `absl.flags._exceptions.DuplicateFlagError` is raised.

**Comment by jackwish** [comment] 2019-07-22 08:20
@alextp , as @mihaimaruseac pointed out, the `log_dir` is not defined by TF itself, but defined by `absl` library which TF uses. See stack
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    import tensorflow as tf
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from absl.app import run as _run
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/app.py", line 41, in <module>
    from absl import logging
  File "/home/wzh/toolchain/venv/pocket/lib/python3.6/site-packages/absl/logging/__init__.py", line 238, in <module>
    assert False
```

The `absl` dependency is introduced by commit [`2435a1875b574f5d299b1dee431ab5ceccd6132f`](https://github.com/tensorflow/tensorflow/commit/2435a1875b574f5d299b1dee431ab5ceccd6132f). And, the interesting thing is that, the patch declares to *resolve flag conflict*.

Also ping @revan , the patch owner :)

**Comment by revan** [comment] 2019-07-22 20:21
Hi there, as Mihai said this flag is defined in absl: https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py#L234

Importing tensorflow as of 1.14 causes an import of absl logging, which itself defines certain flags like `log_dir`. The good news is the workaround is very easy -- just don't define the `log_dir` flag, and rely on the one already defined.

If for some reason you need to run on both TF 1.14 and pre-1.14, you can wrap your flag definition in a try/except.

Closing this issue, please let us know if the workaround is insufficient.

**Closed by revan** 2019-07-22 20:21 UTC
Labels: TF 1.14, comp:ops, type:bug

**Comment by jackwish** [comment] 2019-07-23 01:39
> The good news is the workaround is very easy -- just don't define the log_dir flag, and rely on the one already defined.
This breaks some apps built on top of TF, and all related tools should be rewritten, because these apps are likely to have their own default value of `log_dir` which the tools are not likely to overwrite. Now, the `log_dir` needs to be assigned.

**Comment by a7744hsc** [comment] 2019-09-19 10:43
Though this issue is easy to fix, I still believe this is a compatibility issue that should be avoided.

**Comment by eduardoLopex666** [comment] 2021-09-09 05:17
> Hi there, as Mihai said this flag is defined in absl: https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py#L234
> 
> Importing tensorflow as of 1.14 causes an import of absl logging, which itself defines certain flags like `log_dir`. The good news is the workaround is very easy -- just don't define the `log_dir` flag, and rely on the one already defined.
> 
> If for some reason you need to run on both TF 1.14 and pre-1.14, you can wrap your flag definition in a try/except.
> 
> Closing this issue, please let us know if the workaround is insufficient.

Yes, this solved my issue with this problem.
