### ISSUE TITLE
ImportError: /home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gauravssb1** [tensorflow/tensorflow#23112] opened 2018-10-19 21:23 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 0.11
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 6.3.0 20170516
- CUDA/cuDNN version: N/A
- GPU model and memory: Nvidia GTX 1050, 4 gb

**Describe the problem**
I am new learner in deep learning and do not know much about it. I was trying to install tensorflow in Raspbian following a blog [https://www.pyimagesearch.com/2016/11/14/installing-keras-with-tensorflow-backend/](url). After installing the tensorflow i got an issue while importing tensorflow, which i am not able to solve. I searched lots of blog and asked many for help but i did not get solution.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
$ mkvirtualenv keras_tf -p python3
$ workon keras_tf
$ pip install --upgrade tensorflow
$ python
>>> import tensorflow
--

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Here is the error which i am getting

>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so: cannot open shared object file: No such file or directory

**Comment by tensorflowbutler** [comment] 2018-10-21 19:00
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-01 18:58
@gauravssb1  - This could be due to the compiler version. Please use GCC 4.8.

**Comment by harshini-gadige** [comment] 2018-11-08 18:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-08 18:09 UTC
Labels: stat:awaiting response, type:build/install
