### ISSUE TITLE
`tf.keras.Model.save` does not support subclassed model when saving model as SavedModel format

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#31057] opened 2019-07-26 06:54 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190724
- Python version: 3.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.keras.Model.save`  **DOES NOT** support subclassed model when saving model as SavedModel format
**Describe the expected behavior**
`tf.keras.Model.save` **SHOULD** support subclassed model when saving model as SavedModel format
**Code to reproduce the issue**
```
import tensorflow as tf


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    @tf.function
    def call(self, x, training=True, mask=None):
        return self.d(x)


model = Model()
model(tf.random.normal((2, 3)))
# next line raises errors
model.save("save/model", save_format="tf")
```
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-07-30 06:25
I am able to reproduce the issue with TF version 2.0.0-dev20190724 on Colab. Please see the colab gist [here](https://colab.research.google.com/drive/1KQISq9_YVfIHV3S3OF5PTzk2pfdT4Uz5). 
Thanks!

**Comment by jvishnuvardhan** [comment] 2019-08-09 18:49
@zakizhou The error `ValueError: Model <__main__.Model object at 0x7f7a6bad1e48> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).` clearly mention that `input_shape` is missing.

Please follow the steps mentioned in the [TF webiste](https://www.tensorflow.org/beta/guide/keras/saving_and_serializing#saving_subclassed_models) for `Saving Subclassed Models`. It clearly mentions that  

```
First of all, a subclassed model that has never been used cannot be saved.

That's because a subclassed model needs to be called on some data in order to create its weights.

Until the model has been called, it does not know the shape and dtype of the input data it should be expecting, and thus cannot create its weight variables. You may remember that in the Functional model from the first section, the shape and dtype of the inputs was specified in advance (via keras.Input(...)) -- that's why Functional models have a state as soon as they're instantiated.
```
As you didn't run the your model, it does not know the shape and dtype of the input data it should be expecting, and thus cannot create its weight variables. 

I am closing the issue. Please feel free to open if you face any error after implementing your model following the steps outlined in TF website. There are couple of tutorials and guidelines on TF websites that will be helpful to you. Thanks!

**Closed by jvishnuvardhan** 2019-08-09 18:49 UTC
Labels: 2.0, comp:keras, type:bug

**Comment by zakizhou** [comment] 2019-08-10 01:44
hi @jvishnuvardhan ,
> As you didn't run the your model

> subclassed model needs to be called on some data in order to create its weights.

But  I indeed called my model, see 
```
model = Model()
# next line !
model(tf.random.normal((2, 3)))
```

**Comment by jvishnuvardhan** [comment] 2019-08-10 06:53
@zakizhou Please check the resource I provided in my last response. That resource has an example which is very useful. model compilation and fitting steps are missing your code. Please check the  resource for suggested way to save a subclass model. `model.save` is not correct approach. Please let me know if I am missing anything. Thanks!

**Comment by zakizhou** [comment] 2019-08-10 07:05
@jvishnuvardhan Must users call compile and fit in order to use tf.keras.Model? What if I'm writing custom training loop?

**Comment by zakizhou** [comment] 2019-08-10 07:09
@jvishnuvardhan So do you mean that model.save can not be used if I'm writing custom training loop instead of compilation + fit? I should call tf.saved_model.save(model), is it right?

**Comment by gugarosa** [comment] 2019-08-20 17:20
I am having the same problem. I have defined my subclass custom model and its custom training loop. Furthermore, I am also not using .compile() nor .fit(), and I can't try to figure which saving method I could use.

I have tested every single of them and could not find any way to solve it. Additionally, TF does not provide any documentation regarding saving a model with custom training (without using .compile() and .fit()).

**Comment by zakizhou** [comment] 2019-08-21 01:52
@gugarosa One workaround is that after finished custom training, call model.predict on some input tensors and then call model.save to save your model as SavedModel format.

**Comment by aingo03304** [comment] 2019-11-17 16:05
Same problem here too

**Comment by andreclaudino** [comment] 2019-11-21 00:22
I am having the same problem on tensorflow 2.0

**Comment by jvishnuvardhan** [comment] 2019-11-21 01:21
@andreclaudino @aingo03304 @AlexFuster Can you please open a new issue with details of your model and share a simple standalone code to reproduce the issue. Thanks!

**Comment by AlexFuster** [comment] 2019-12-02 10:32
I've been running OP's snippet and the bug is clearly reproducible. 
As @jvishnuvardhan pointed, using _set_inputs does the work. However, I think it should not be necessary if the model is called and fed an input. In other words, the call function of Model should automatically call _set_inputs with the input received

**Comment by image357** [comment] 2020-01-30 10:38
if you use model.predict(...) instead of model(...) it works.

**Comment by pinkponk** [comment] 2020-02-20 16:36
I can't save a custom model even though I successfully call model.predict(...) before the save. I get all kinds of error. My model is a seq2seq model. Why is tensorflow saying the subclassing keras.Model is the recommended low-level/flexible way when i is almost impossible to save it as a SavedModel?...

**Comment by jvishnuvardhan** [comment] 2020-02-21 23:09
@pinkponk Please create a new issue with standalone code and any other details to resolve your issue. Thanks!

**Comment by Guodonggogo** [comment] 2020-03-18 06:34
Same problem, train with a customized loop. Can save ckpy without .meta. But can not get a frozen model. Does anyone solve it?

**Comment by Liusandian** [comment] 2020-03-21 09:08
> @gugarosa One workaround is that after finished custom training, call model.predict on some input tensors and then call model.save to save your model as SavedModel format.

could you give more details about the  'call model.predict on some input tensors'  deal? such as the code text?Thanks

**Comment by pradyumnaym** [comment] 2020-04-06 16:56
@Liusandian I too was wondering how this can be done. Turns out there is a checkpoint based method to save these models. They have been used in https://www.tensorflow.org/tutorials/text/nmt_with_attention

The official docs for checkpoints can be found here:
https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint
and here:
https://www.tensorflow.org/guide/checkpoint

**Comment by anoopkatti** [comment] 2020-04-20 20:57
I followed this guide and it worked for me: https://www.tensorflow.org/guide/saved_model#exporting_custom_models

In other words, the below code should work:

````
import tensorflow as tf


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    @tf.function(input_signature=[tf.TensorSpec([2, 3], tf.float32)])
    def call(self, x, training=True, mask=None):
        return self.d(x)


model = Model()
model(tf.random.normal((2, 3)))

tf.saved_model.save(model, 'serving_path')
````

**Comment by JianweiSun007** [comment] 2021-08-29 17:23
I have the same problem here and thanks @anoopkatti I get the pb model but I still don't know why. My model as follow:
