### ISSUE TITLE
tf.linalg.triangular_solve segfaults instead of broadcasting

### ISSUE THREAD

**Issue by st--** [tensorflow/tensorflow#37584] opened 2020-03-13 22:57 UTC
**System information** 
- Have I written custom code: no
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: pip install tensorflow
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7.6

**Describe the current behavior**

`tf.linalg.triangular_solve` segfaults when the shapes don't match *and* tf.linalg.triangular_solve hasn't been run before (if it has successfully been run before, it raises an InvalidArgumentError instead).

**Describe the expected behavior**

Not to segfault. Ideally, to broadcast!

**Standalone code to reproduce the issue**

```python
import numpy as np
import tensorflow as tf

shape1 = (3, 3)
shape2 = (1, 3, 3)

# works either way around
if np.random.rand() < 0.5: shape1, shape2 = shape2, shape1

LA = tf.convert_to_tensor(np.tril(np.random.randn(*shape1)))
B = tf.convert_to_tensor(np.random.randn(*shape2))

segfault = True
if segfault:
    tf.linalg.triangular_solve(LA, B, lower=True)  # segfaults
else:
    tf.linalg.triangular_solve(tf.squeeze(LA), tf.squeeze(B), lower=True)  # works fine
    tf.linalg.triangular_solve(LA, B, lower=True)  # raises InvalidArgumentError
```

May be related to #25391

**Comment by amahendrakar** [comment] 2020-03-17 06:46
@st--,
I was able to reproduce the issue with [TF2.1](https://colab.research.google.com/gist/amahendrakar/ace0caf3affea5614171a8697624988c/37584.ipynb). However, the issues seems to be fixed in [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d09075d35701e82c6b2a0cf06b3efbc4/37584-tf-nightly.ipynb). Please check the attached gist. Thanks!

**Comment by amahendrakar** [comment] 2020-03-27 16:40
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-03 16:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-03 16:43 UTC
Labels: TF 2.1, comp:ops, stat:awaiting response, type:bug
