### ISSUE TITLE
Bug in XLA, if branches optimized by grappler/arithmetic_optimizer

### ISSUE THREAD

**Issue by LLLLKKKK** [tensorflow/tensorflow#15228] opened 2017-12-09 04:16 UTC
grappler/arithmetic_optimizer may merge different Const op with same value into one. However, if two Const ops are in different branches (tf.cond, or SwitchOp, user-defined SwitchOp things), XLA will make them into one cluster, which would cause this XlaLaunchOp can't be run forever.

One way to walk around this is to disable arithmetic_optimizer.

**Comment by tensorflowbutler** [comment] 2017-12-09 12:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jpienaar** [comment] 2017-12-10 04:34
Do you perhaps have a repro?

**Comment by tensorflowbutler** [comment] 2018-01-03 07:37
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-17 19:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-06 07:30
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-20 19:34
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 01:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by angersson** [comment] 2018-04-03 01:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by angersson** 2018-04-03 01:25 UTC
Labels: stat:awaiting response
