### ISSUE TITLE
tensorflow 

### ISSUE THREAD

**Issue by ericsungtwn** [tensorflow/tensorflow#30242] opened 2019-06-29 03:04 UTC
File "<string>", line 1, in <module>
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/ericsung/anaconda3/envs/cs231n/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib

**Comment by prat96** [comment] 2019-06-29 14:44
Hi, please edit/format your issue after reading the following issue template guide:

https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md

It becomes really difficult to solve anything without describing the problem properly.

**Comment by ravikyram** [comment] 2019-07-01 08:42
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2019-07-09 05:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-09 05:23 UTC
Labels: stat:awaiting response, type:build/install
