### ISSUE TITLE
saved_model.save bug in 2.0.0b0

### ISSUE THREAD

**Issue by jusonn** [tensorflow/tensorflow#30738] opened 2019-07-16 06:11 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): maybe binary (pip)
- TensorFlow version (use command below): 2.0.0b0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: P40/24451MB

You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I save saved model.pb using tf.saved_model.save() in 2.0.0b0.
and it gives this error.
```
W0716 04:34:59.213974 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49adb5da0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:34:59.375897 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49add7940>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:34:59.670762 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ade14a8>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:34:59.837181 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ade1fd0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.001157 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ade7b00>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.162233 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad6f668>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.321973 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad761d0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.503687 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad80198>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.669191 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad80cc0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:00.855475 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad87cc0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:01.017992 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad92828>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:01.204613 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad99828>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:01.524981 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ada1390>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:01.706990 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad28390>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:01.868694 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad28eb8>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.059983 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad30eb8>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.229396 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad35a20>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.413010 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad3da20>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.573688 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad45588>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.756634 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad4f588>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:02.916903 140620342499136 saved_model.py:722] Skipping full serialization of object <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe49ad550f0>, because an error occurred while tracing layer functions. Error message: Expected Operation, Variable, or Tensor, got None
W0716 04:35:03.265970 140620342499136 saved_model.py:722] Skipping full serialization of object <deepnormal.Model object at 0x7fe4b82cd240>, because an error occurred while tracing layer functions. Error message: in converted code:


    TypeError: tf__wrapped_call() takes 1 positional argument but 2 were given

Traceback (most recent call last):
  File "train.py", line 106, in <module>
    train(dataset, FLAGS.epochs)
  File "train.py", line 78, in train
    tf.saved_model.save(model, path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 835, in save
    meta_graph_def, saveable_view, signatures)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 531, in _fill_meta_graph_def
    object_map, resource_map, asset_info = saveable_view.map_resources()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 266, in map_resources
    tensor_util.constant_value(capture))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 455, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```
**Describe the expected behavior**
When I reinstall tensorflow with 2.0.0a0 it works and available for tf serving server.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
Maybe the model should have `batchnorm` layer
tf.saved_model.save(model, path)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment] 2019-07-18 06:14
@jusonn,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jusonn** [comment] 2019-07-19 06:22
@anush-o 
Thanks for reply.
Since this is my first issue report, I'm confusing how much code should I share.
Would you let me know how much code snippet is needed?
I think it's not the entire code.

**Comment by anush-o** [comment] 2019-07-19 08:40
@jusonn ,
Thanks for response. Please provide us the code with which we can replicate the issue.

**Comment by anush-o** [comment] 2019-07-30 11:08
Closing due to lack of recent activity.Thanks!

**Closed by anush-o** 2019-07-30 11:08 UTC
Labels: 2.0.0-beta0, comp:model, stat:awaiting response, type:support

**Comment by arielbenitah** [comment] 2019-11-21 12:51
Hi, I have the same problem in tensorflow 1.14. Any help is more than welcomed.

**Comment by Jasonnor** [comment] 2019-12-06 04:17
Any update on it? This issue is not solved yet 😕

**Comment by jusonn** [comment] 2019-12-06 09:09
For me, It was issued with tensorflow==2.0.0b0.
Now, with tensorflow==2.0.0,  `tf.saved_model.save(model, dir)` works with model above.

**Comment by MislavSag** [comment] 2020-07-09 12:24
I get the same error:
```
--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\Users\Mislav\Documents\GitHub\trademl\trademl\modeling\random_forest\train_nn.py in 
----> 293 tf.saved_model.save(model, model_path)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py in save(obj, export_dir, signatures)
    820   object_saver = util.TrackableSaver(checkpoint_graph_view)
    821   asset_info, exported_graph = _fill_meta_graph_def(
--> 822       meta_graph_def, saveable_view, signatures)
    823   saved_model.saved_model_schema_version = (
    824       constants.SAVED_MODEL_SCHEMA_VERSION)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py in _fill_meta_graph_def(meta_graph_def, saveable_view, signature_functions)
    508   resource_initializer_ops = []
    509   with exported_graph.as_default():
--> 510     object_map, resource_map, asset_info = saveable_view.map_resources()
    511     for resource_initializer_function in resource_initializer_functions:
    512       asset_dependencies = []

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py in map_resources(self)
    243             and capture not in self.captured_tensor_node_ids):
    244           copied_tensor = constant_op.constant(
--> 245               tensor_util.constant_value(capture))
    246           node_id = len(self.nodes)
    247           node = _CapturedConstant(

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
    244   """
    245   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 246                         allow_broadcast=True)
    247 
    248 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    282       tensor_util.make_tensor_proto(
    283           value, dtype=dtype, shape=shape, verify_shape=verify_shape,
--> 284           allow_broadcast=allow_broadcast))
    285   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    286   const_tensor = g.create_op(

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    452   else:
    453     if values is None:
--> 454       raise ValueError("None values not supported.")
    455     # if dtype is provided, forces numpy array to be the type
    456     # provided if possible.

ValueError: None values not supported.
```
after I tried to save a model: `tf.saved_model.save(model, model_path)`

IS there solution to this error?

**Comment by MislavSag** [comment] 2020-07-09 13:38
I have changed tf versoin, now I get different error, I will post in another issue.
