### ISSUE TITLE
Tensorflow retrain.py random distortions

### ISSUE THREAD

**Issue by danleh93** [tensorflow/tensorflow#2304] opened 2016-05-10 13:43 UTC
### Environment info
Operating System: Mac OS X with Tensorflow 0.8 installed.

I am trying to run retrain.py with my custom training set, but whenever I try passing in the argument `--random_crop 5` when running retrain.py the program errors out and says:

> tensorflow.python.framework.errors.InvalidArgumentError: assertion failed: [Need value.shape >= size, got ] [314 314 1] [299 299 3]
> 	 [[Node: random_crop/Assert = [Assert T=[DT_STRING, DT_INT32, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"(random_crop/All, random_crop/Assert/data_0, random_crop/Shape, random_crop/size)]]
> Caused by op u'random_crop/Assert'

The command I am using is:

`bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir /path/to/my/training_images --how_many_training_steps 5000 --random_crop 5`

Is this an issue with the size of the images that I am using for my training set?

**Comment by petewarden** [comment] 2016-05-12 02:07
Sorry you're hitting problems. Are you able to reproduce the same error with the standard flowers set of photos? If you can, that will help me track down what's going wrong, thanks!

**Comment by danleh93** [comment] 2016-05-12 13:50
Thanks for taking the time to respond and look into it! I was not able to reproduce the same error with the standard flowers set of photos. In fact, I was stumped for a while as I noticed all the images within the flowers set are all .jpg's, but my photos are all also .jpg's. When looking at the metadata, I noticed for all JPEGs that are EXIF standard instead of JFIF standard, Tensorflow will break when trying the distortions.  However, when removing all the photos with EXIF standard, the program runs successfully.

**Comment by petewarden** [comment] 2016-05-12 15:21
Thanks for investigating! Can you upload one of the EXIF files that's causing the error and send me a link? I'll try to reproduce the problem here.

**Comment by felixmaximilian** [comment] 2016-05-17 10:12
Hey guys, 
I ran into the same problem and have a fix ready. You seem to have problems with grayscale pictures that have one channel only.
The fix is available in this PR
https://github.com/tensorflow/tensorflow/pull/2349#issuecomment-219077419 
and you can find the fix in the marked line:
https://github.com/tensorflow/tensorflow/pull/2349/files#diff-e27def9997dcd569e1f2412fd6f3ae76R619
(I load every image as a 3 channel image)

**Comment by felixmaximilian** [comment] 2016-05-25 15:48
Hey, my pull request was accepted. Please check if your problem remains.

**Comment by petewarden** [comment] 2016-06-17 22:02
Closing this as presumed fix, since it's been a while. Please reopen or let me know if it's still an issue.

**Closed by petewarden** 2016-06-17 22:02 UTC
