### ISSUE TITLE
Xla and memory allocation

### ISSUE THREAD

**Issue by volvador** [tensorflow/tensorflow#33016] opened 2019-10-03 11:13 UTC
- TensorFlow version 1.14
- Python version: 2.7

I am defining this kind of graph:

    product_list = [(5, 6), ...] # list of pairs of integers
    data = tf.compat.v1.placeholder(dtype=tf.float64,
                                           name='input_tensor', shape=[1, 1000])
    x_i = tf.gather(data, [i[0] for i in product_list], axis=1)
    x_j = tf.gather(data, [i[1] for i in product_list], axis=1)
    res = x_i * x_j

    res = tf.concat([data, res], axis=-1)

and using `AOT` to compile an `so`.
Then calling the compiled function seems to take a lot of time.
So my question is : is there memory allocation at every call?
If yes, how can I avoid it by telling Tensorflow to pre-allocate the memory (as all the shapes are known in compile time) 
For example are there any commands that result in a new memory allocation at every call? (`tf.stack`, `tf.concat` etc..)

**Comment by gadagashwini** [comment] 2019-10-04 08:31
@volvador, If you are using GPU, can you please try using GPU memory allocation mentioned in [this link](https://www.tensorflow.org/guide/gpu#manual_device_placement) and let us know if the issue still persists. Thanks!

**Comment by volvador** [comment] 2019-10-04 08:50
@gadagashwini I am using CPU

**Comment by gadagashwini** [comment] 2019-10-04 10:24
@volvador, Please provide the complete code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2019-10-11 11:38
@volvador, Any update on the reproducible code. Thanks!

**Comment by gadagashwini** [comment] 2019-10-21 05:51
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-10-21 05:51 UTC
Labels: TF 1.14, comp:ops, stat:awaiting response, type:support
