### ISSUE TITLE
New train_op for estimator in tensorflow

### ISSUE THREAD

**Issue by bmdy** [tensorflow/tensorflow#38682] opened 2020-04-19 09:27 UTC
I would like to write a novel train_op to test a new training algorithm without using any gradient or loss, which is a little bit like a UCB algorithm in bandit. How can I define such a train_op to add it in my custom estimator? 

Thank you very much!

**Comment by Saduf2019** [comment] 2020-04-19 14:14
@bmdy 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by bmdy** [comment] 2020-04-21 11:00
> @bmdy
> This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Can you give some initial guidance?

**Comment by Saduf2019** [comment] 2020-04-21 11:12
please refer to these lonks for assistance.

[link1](https://towardsdatascience.com/an-advanced-example-of-tensorflow-estimators-part-1-3-c9ffba3bff03)

[link2](https://kite.com/python/docs/tensorflow.contrib.tpu.TPUEstimatorSpec.train_op)

[link3](https://www.tensorflow.org/api_docs/python/tf/estimator/EstimatorSpec)

[link4](https://github.com/tensorflow/tensorflow/issues/22433)

i see you have already created an issue on stackoverflow, hence moving this to closed status.

**Closed by Saduf2019** 2020-04-21 11:12 UTC
Labels: type:others

**Comment by bmdy** [comment] 2020-04-21 11:33
> please refer to these lonks for assistance.
> 
> [link1](https://towardsdatascience.com/an-advanced-example-of-tensorflow-estimators-part-1-3-c9ffba3bff03)
> 
> [link2](https://kite.com/python/docs/tensorflow.contrib.tpu.TPUEstimatorSpec.train_op)
> 
> [link3](https://www.tensorflow.org/api_docs/python/tf/estimator/EstimatorSpec)
> 
> [link4](https://github.com/tensorflow/tensorflow/issues/22433)
> 
> i see you have already created an issue on stackoverflow, hence moving this to closed status.

Thank you very much!
