### ISSUE TITLE
DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by mukesh15j** [tensorflow/tensorflow#39423] opened 2020-05-11 17:45 UTC
Traceback (most recent call last):
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import tensorflow
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Mukesh\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment] 2020-05-12 04:08
@mukesh15j 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).It helps us in localizing the issue faster.

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).

Make sure to download the[ latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?.Refer #36167 and see if it helps you.Thanks!

**Comment by jf19742016** [comment] 2020-05-13 19:36
For clarity as it isn't clear......  IF you are using GPU but your CPU doesn't support AVX then you'll get this error?  CPU is Xeon 5560 (no AVX support) GPU is 1060i and I get the above error.  C++ ok

**Comment by ravikyram** [comment] 2020-05-14 05:05
@jf19742016 

The error is due to cpu compatibility .As you mentioned Xeon 5560 has no AVX support.I have confirmed the same from product details page (https://ark.intel.com/content/www/us/en/ark/products/37109/intel-xeon-processor-x5560-8m-cache-2-80-ghz-6-40-gt-s-intel-qpi.html).

As an alternative i suggest you to use Google colab (https://colab.research.google.com).
Thanks!

**Comment by jf19742016** [comment] 2020-05-14 10:24
Sorry I know it doesn't have AVX support.  To be clear this is expected behaviour?  So i know my CPU doesn't support AVX and my GPU is a 1060i - i'll get "DLL load failed: A dynamic link library (DLL) initialization routine failed."?  A nicer error message would be better as clearly from the other threads this can happen for a lot of reasons.

**Comment by mihaimaruseac** [comment] 2020-05-15 00:34
Unfortunately the error message comes from windows and all of our attempts to fix that (checking and then presenting a better error message) resulted in failure since the code that was checking this was also compiled using AVX.

You can compile everything from source or use Google Colab Notebooks.

Can we close the issue?

**Comment by jf19742016** [comment] 2020-05-15 18:19
Really?  So a version or view back it warned you and gave some message about not being compiled for AVX, i remember you could even set a flag to turn the warning off.  You're saying that this is a Windows issue - that's hard to believe.

**Closed** 2020-05-29 19:10 UTC
Labels: stalled, stat:awaiting response, subtype:windows, type:build/install
