### ISSUE TITLE
Session initialization must not require values for tensors with dtype string

### ISSUE THREAD

**Issue by maxim5** [tensorflow/tensorflow#6315] opened 2016-12-14 17:55 UTC
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 8.0
TF 0.12.0-rc1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I create a string variable, among others, then try to initialize the session:
```
mode = tf.placeholder(tf.string, name='mode')
...

init = tf.global_variables_initializer()
session.run(init)
```

This results in
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'mode' with dtype string
	 [[Node: mode = Placeholder[dtype=DT_STRING, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: mode/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_360_mode", tensor_type=DT_STRING, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

Fix for me is to set `session.run(init, feed_dict={mode: 'foo'})`
But it looks like a regression since rc0.

**Comment by yaroslavvb** [comment] 2016-12-14 22:40
That seems like intended behavior? (assuming your graph `init` has a dependency on `mode)

**Comment by maxim5** [comment] 2016-12-15 10:29
Hi @yaroslavvb. Doesn't look like so.
Session init doesn't require other values for variables, even if there is a dependency.
It's also never mentioned in the doc: https://www.tensorflow.org/how_tos/variables/

**Comment by yaroslavvb** [comment] 2016-12-15 16:12
Can you post reproducible example?

`initialize_all_variables` is a regular tensorflow op, so it follows the regular TF semantics and all dependent nodes must be available

For instance, following two examples fail because dependent nodes are not available
```
a = tf.Variable(tf.placeholder(tf.float32))
sess.run(tf.initialize_all_variables())
```

```
a = tf.Variable(1)
b = tf.Variable(a)
sess.run(tf.initialize_all_variables())
```

**Comment by maxim5** [comment] 2016-12-15 16:34
My model is somewhat big to post it here. I have tried to make a few-lines example, but it didn't reproduce. Essentially the `mode` variable was only used in `tf.cond` op, that's all. Hope you'll be a able to find a small example.

Your examples fail indeed, but differently (on my machine):
```
>>> a = tf.Variable(tf.placeholder(tf.float32))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 215, in __init__
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 307, in _init_from_args
    self._initial_value)
ValueError: initial_value must have a shape specified: Tensor("Placeholder:0", dtype=float32)
```

In my case the graph was successfully constructed, and the error occurred only on init step.

**Comment by yaroslavvb** [comment] 2016-12-15 16:42
Sounds like maybe a documentation issue then? (to clarify that placeholders that are dependencies must be fed when running variable initialization)

**Comment by maxim5** [comment] 2016-12-15 16:51
Why isn't it required in simple cases?

```
mode = tf.placeholder(tf.string, name='mode')
layer = tf.Variable(0)
layer = tf.cond(tf.equal(mode, 'bar'), lambda: layer, lambda: 2 * layer)
init = tf.global_variables_initializer()
with tf.Session() as session:
  session.run(init)
```

**Comment by yaroslavvb** [comment] 2016-12-15 17:00
In that example `tf.placeholder` is not a dependency of init op. My guess is that in your actual model you introduce this dependency.

**Comment by andydavis1** [comment] 2016-12-15 17:50
Thanks Yaroslav. This does sound like a documentation issues. Assigning to add documentation to clarify that placeholders that are dependencies of variable init must be fed when running initialization.

**Comment by tfboyd** [comment] 2017-06-16 17:21
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Closed by tfboyd** 2017-06-16 17:21 UTC
Labels: stat:awaiting tensorflower
