### ISSUE TITLE
Docs Needed

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#23798] opened 2018-11-16 10:42 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.10+
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/estimator/export/ServingInputReceiver

**Describe the documentation issue**

It is unclear:

1. what a `serving_input_receiver_fn` is
2. why one is needed
3. how one should be written (e.g. what arguments are required in the function definition)
4. what should be returned 
5. what the difference is between the `features` argument of `tf.estimator.export.ServingInputReceiver` and the `receiver_tensors` argument is and why they are needed.

See this [S.O. post](https://stackoverflow.com/questions/52874647/tensorflow-v1-10-why-is-an-input-serving-receiver-function-needed-when-checkpoi) for an example of why it is unclear

**Comment by tensorflowbutler** [comment] 2018-12-01 18:45
Nagging Assignees @karmel, @MarkDaoust: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by shivam13juna** [comment] 2018-12-25 05:35
I wanted to start contributing here, this seems like a good place to start? so can I start?

**Comment by karmel** [comment] 2019-01-04 23:50
Thanks, @shivam13juna -- sure, please update the docs for the relevant classes/methods above as necessary, and it would be great if you also came up with an end-to-end example that could be published as a tutorial/Jupyter notebook. Thanks--

**Comment by Shashankjain12** [comment] 2019-03-04 03:16
Is this issue not assigned. Can i work on this!?

**Comment by shivam13juna** [comment] 2019-03-04 03:22
Yeah go ahead pal, I'm not working on this.

**Comment by Shashankjain12** [comment] 2019-03-04 06:36
Ok thanks @shivam13juna .. can i get assigned to this @karmel

**Comment by Shashankjain12** [comment] 2019-03-04 07:02
By the way i was looking in the docs and this particular  `tf.estimator.export.ServingInputReceiver`
is deprecated in tensorflow v2.0 do we need to work on this issue any more or this issue still open?

**Comment by dynamicwebpaige** [comment] 2019-03-04 08:32
😁 Thanks for your interest in helping improve the docs! And you're right -  `tf.estimator.export.ServingInputReceiver` will be deprecated in TF 2.0. Closing out this issue.

**Comment by karmel** [comment] 2019-03-06 23:24
ServingInputReceivers will still be in 2.0; there will be other options for exporting (see https://github.com/tensorflow/community/pull/34 ), but ServingInputReceivers will still be necessary for Estimators. If you would like to help with documentation/examples, that would be much appreciated.

**Comment by adithyaakrishna** [comment] 2020-10-02 20:31
If the issue is open, Can I work on this?🚀

**Comment by MarkDaoust** [comment] 2020-10-02 20:40
@adithyaakrishna nobody's currently working on this, If you want to contribute to these docs you're welcome to. They're generated from the docstrings in the [tensorflow/estimator repository](https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/export/export.py#L109).

**Comment by siddharth25pandey** [comment] 2021-08-22 18:25
@MarkDaoust If the issue is open, Can I work on this?

**Comment by MarkDaoust** [comment] 2021-08-23 16:48
Hi @siddharth25pandey,

While it's true that this thing is under-documented,  `ServingInputReceiver` is now only available in the legacy `tf.compat.v1` package. So any effort may be better-spent elsewhere.

If it's important to you, you can always send us a documentation update (but note that we do have a "too small to accept" threshold, we don't accept single-character PRs.).

**Closed by MarkDaoust** 2021-08-23 16:48 UTC
Labels: type:docs-bug, stat:contributions welcome, comp:apis
