### ISSUE TITLE
Importing the fast protobuf installed from pip package results in segmentation fault

### ISSUE THREAD

**Issue by fcole90** [tensorflow/tensorflow#2197] opened 2016-05-02 20:11 UTC
### Operating System:
Ubuntu 14.04 amd64

### Installed version of CUDA and cuDNN: 
no version of CUDA installed

### If installed from binary pip package, provide:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl
Version 0.8.0

### Steps to reproduce
try ```import tensorflow```, it works as expected.
Then install the suggested package for fast protobuf: https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp34-none-linux_x86_64.whl

Now trying ```import tensorflow``` results in a segmentation fault.

**Comment by zheng-xq** [comment] 2016-05-02 20:29
Adding @martinwicke. 

Could you post the log to gist?

**Comment by fcole90** [comment] 2016-05-03 17:04
Here you are: https://gist.github.com/fcole90/b5cd9bf6d972d5554173624986a359b6

**Comment by vroomzel** [comment] 2016-05-12 17:47
I have the same issue on CentOS7

**Comment by martinwicke** [comment] 2016-06-07 15:20
@keveman, do you know what could be going on?

**Comment by keveman** [comment] 2016-06-07 16:09
Hard to say, but I am guessing the binary protobuf package needs updating.

**Comment by fcole90** [comment] 2016-06-07 16:20
Is there any workaround available until this gets fixed? :smiley:

**Comment by keveman** [comment] 2016-06-07 17:46
@fcole90 Do you mind trying this wheel package for protobuf?
https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b3-cp34-cp34m-linux_x86_64.whl

(Here is the one for Python 2 : https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b3-cp27-none-linux_x86_64.whl)

**Comment by keveman** [comment] 2016-06-13 14:39
@fcole90 Gentle ping. Please let me know if the new protobuf wheel package solves this issue.

**Comment by fcole90** [comment] 2016-06-13 17:05
Sorry for my late reply. 

I just tested the just tried both and I still received a segmentation fault.

[Python2](https://gist.github.com/fcole90/0ed450312a1306c35330f5fc9d65a148)

[Python3](https://gist.github.com/fcole90/f64d8ee051a6b453a8ad8482aea61bb1)

**Comment by keveman** [comment] 2016-06-22 18:59
I am unable to reproduce this with the 0.9.0rc0 version of TensorFlow, available here https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp34-cp34m-linux_x86_64.whl. Closing this one out. Feel free to open again if you still get the segfault.

**Closed** 2016-06-22 18:59 UTC
Labels: triaged
