### ISSUE TITLE
TFLite allocate tensors fails

### ISSUE THREAD

**Issue by reorder-cv** [tensorflow/tensorflow#27279] opened 2019-03-29 10:00 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
2.0.0-dev20190327
- Python version:
3.6.8
No GPU

**Describe the current behavior**
I have been trying to convert Yolov3 from tensorflow to tflite and was facing issues due to the lack of ResizeNearestNeighbor custom operation. However with the recent nightly build I was able to convert the model and save the tflite file. When I attempt to load the tflite model, allocate tensors fails with the following error : 

`~/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
     93   def allocate_tensors(self):
     94     self._ensure_safe()
---> 95     return self._interpreter.AllocateTensors()
     96 
     97   def _safe_to_run(self):

~/anaconda3/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: tensorflow/lite/kernels/concatenation.cc:57 t0->dims->size <= 4 was not true.Node number 265 (CONCATENATION) failed to prepare.`

Code to convert tensorflow frozen graph to tflite
`import tensorflow as tf
INPUT_ARRAYS = ['Placeholder']
OUTPUT_ARRAYS = ['concat_9','mul_6']
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            'checkpoint/yolov3_cpu_nms.pb', INPUT_ARRAYS, OUTPUT_ARRAYS)
converter.allow_custom_ops=True
tflite_model = converter.convert()`

Code to load tflite model and allocate tensors:
`import tensorflow as tf
interpreter=tf.lite.Interpreter(model_path='test.tflite')

interpreter.allocate_tensors()`

**Comment by gargn** [comment] 2019-04-03 19:34
Can you provide your model or a minimal model which which reproduces your error?

**Comment by reorder-cv** [comment] 2019-04-11 06:10
> Can you provide your model or a minimal model which which reproduces your error?

How? The TFLite file or anything else?

**Comment by gargn** [comment] 2019-04-11 23:15
@reorder-cv Please provide `checkpoint/yolov3_cpu_nms.pb`.

**Comment by reorder-cv** [comment] 2019-04-12 04:02
> @reorder-cv Please provide `checkpoint/yolov3_cpu_nms.pb`.

The file is larger than 10MB so I am not able to upload it here.

**Comment by ANSHUMAN87** [comment] 2019-04-12 04:21
@reorder-cv : This issue is solved with my PR #27287, please try using latest code from TFLite, it will solve your blocking issue. If it solves, please close this issue.

**Comment by reorder-cv** [comment] 2019-04-22 06:30
> @reorder-cv : This issue is solved with my PR #27287, please try using latest code from TFLite, it will solve your blocking issue. If it solves, please close this issue.

I compiled from the latest code. I am getting a new issue "Didn't find op for builtin opcode 'CONV_2D' version '2'" when I load the tflite file.

**Comment by ANSHUMAN87** [comment] 2019-04-22 07:00
@reorder-cv : Could you please check in your workspace: [https://github.com/tensorflow/tensorflow/blob/12ee3420367f9a0f728c6b2e0493f5fb150eea47/tensorflow/lite/kernels/register.cc#L192](url)
what is min & max version?

Also please cross check [https://github.com/tensorflow/tensorflow/blob/12ee3420367f9a0f728c6b2e0493f5fb150eea47/tensorflow/lite/toco/tflite/operator.cc#L105](url)
whether it is in sync with latest code? If possible please try to post the code snippet for the api.

**Comment by ANSHUMAN87** [comment] 2019-04-22 07:07
@reorder-cv : Also for my reference would you be able to share your model Graphdef file(pbtxt)?

**Comment by reorder-cv** [comment] 2019-04-23 09:15
> @reorder-cv : Could you please check in your workspace: [https://github.com/tensorflow/tensorflow/blob/12ee3420367f9a0f728c6b2e0493f5fb150eea47/tensorflow/lite/kernels/register.cc#L192](url)
> what is min & max version?
> 
> Also please cross check [https://github.com/tensorflow/tensorflow/blob/12ee3420367f9a0f728c6b2e0493f5fb150eea47/tensorflow/lite/toco/tflite/operator.cc#L105](url)
> whether it is in sync with latest code? If possible please try to post the code snippet for the api.

Q1) Min - 1 and Max - 3 
AddBuiltin(BuiltinOperator_CONV_2D, Register_CONV_2D(),
             /* min_version */ 1,
             /* max_version */ 3)

Q2) I checked diff between the tensorflow github repository and the cloned repository I used to compile. There are zero removals and additions.

**Comment by reorder-cv** [comment] 2019-04-23 09:19
> @reorder-cv : Also for my reference would you be able to share your model Graphdef file(pbtxt)?

I do not have a pbtxt file, I have a .pb file. I converted it using the following code and the size of the file is large for me to share across github. 
`from google.protobuf import text_format
from tensorflow.python.platform import gfile
def graphdef_to_pbtxt(filename): 
    with gfile.FastGFile(filename,'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def, name='')
        tf.train.write_graph(graph_def, 'checkpoint/', 'yolov3.pbtxt', as_text=True)
    return`

**Comment by reorder-cv** [comment] 2019-04-23 10:57
> @reorder-cv : Also for my reference would you be able to share your model Graphdef file(pbtxt)?

Ok I recompiled with some changes, allocate tensors cleared. But I have a new problem now interpreter.invoke() causes core dumped and exits shell

**Comment by ANSHUMAN87** [comment] 2019-04-24 04:14
> > @reorder-cv : Also for my reference would you be able to share your model Graphdef file(pbtxt)?
> 
> Ok I recompiled with some changes, allocate tensors cleared. But I have a new problem now interpreter.invoke() causes core dumped and exits shell

@reorder-cv : Would you please share more details, so that i can debug. Also i press on sharing the changes you did to clear the allocate tensor failures, it is a learning for everyone in the community, if you share here. Thanks!

**Comment by gargn** [comment] 2019-04-24 18:21
Unfortunately, I'm unsure what is happening. Given that it's a little difficult to debug on my end without a model, can you try a few things and provide as detailed output as possible:

1. Try converting the model with the latest 2.0 nightly. There have been some fixes in the `compat.v1` pipeline so there might be a relevant one here.
2. Try converting the model without `allow_custom_ops=True`. It is possible this flag is suppressing an unrelated ops error.
3. Optionally, if possible, try running this conversion code (with and without the `allow_custom_ops=True`) against the 1.X nightly just to confirm the same errors are occurring. This will confirm it's not an issue with 2.0 specifically but an issue converting this model more generally.

Additionally, when was this model generated? There have been some changes to the code to freeze models in the last week or two to adapt to some underlying changes - so if it's a newer model can you try and freeze it again.

**Comment by ANSHUMAN87** [comment] 2019-04-30 04:32
@reorder-cv : I think 2 of your issues reported here is addressed successfully. If the thread continues it may be difficult for other community user to analyze. So i suggest you close this issue, as your original post is addressed here. And open a new issue thread with all details as asked by @gargn . Also it is true as mentioned by @gargn , it is very difficult to debug, without a model or pseudo code to reproduce the issue, unless its a pretty straight forward error. Please try to work on that as well, Thanks!
Please feel free to post your end remarks, Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-06 22:14
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Please open a new issue if there are any unresolved issues. Thanks!

**Closed by jvishnuvardhan** 2019-06-06 22:14 UTC
Labels: 2.0, comp:lite, type:bug/performance

**Comment by kartikwar** [comment] 2020-06-04 10:19
I was having the exact same issue for a keras yolo model . I changed my gradle dependency to     implementation 'org.tensorflow:tensorflow-android:1.13.1'
and I also froze the graph in tensorflow version 1.13.1 . Also keras verion was 2.3.1.

Hope these configurations work out for you as well

**Comment by BernardinD** [comment] 2020-09-16 14:40
@kartikwar which yolo version were you using? I'm having a similar issue with yolov5
