### ISSUE TITLE
TFLite: Did not get operators, tensors, or buffers in subgraph 0. Error running on Android

### ISSUE THREAD

**Issue by gcervantes8** [tensorflow/tensorflow#45313] opened 2020-12-01 22:41 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 4a 5g
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7
- CUDA/cuDNN version: Not using GPU

**Describe the current behavior**
I am able to convert a concrete function to a TensorFlow Lite model without errors.  I do get errors when trying to run the model on Android.  The error occurs when running this line on Android: tflite = new Interpreter(buffer, opt);

I don't believe this has to do with the Android code because I am able to run a TFLite model that I converted using a Keras model with this Android code.

I've been trying to convert a larger model with more operations and tensors but have gotten stuck on this error, I simplified the code to this but error remains.

**Android Error**

```
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Did not get operators, tensors, or buffers in subgraph 0.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at arl.testnmt.MainActivity.loadModel(MainActivity.java:127)
        at arl.testnmt.MainActivity$2.run(MainActivity.java:108)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Standalone code to reproduce the issue (Python TFLite conversion)**

```
import tensorflow as tf
import os


class SimpleModel:
    def infer_tflite(self, features):
        return tf.zeros(shape=(250, 1), dtype=tf.dtypes.int32)


def tf_lite_convert():
    print('TensorFlow version')
    print(tf.__version__)
    model = SimpleModel()

    single_elem = tf.zeros(shape=[1, 20], dtype=tf.dtypes.int64)
    print('Running predictions using tflite inference')
    preds = model.infer_tflite(single_elem)
    print('TFlite inference results')
    print(preds)
    print('Turning to Concrete function')
    new_infer_fn = tf.function(model.infer_tflite, input_signature=[tf.TensorSpec((1, None), dtype=tf.int64)])
    infer_concrete = new_infer_fn.get_concrete_function()

    print('Running inference with concrete function')
    preds = infer_concrete(single_elem)
    print('Concrete Output prediction')
    print(preds)

    print('Saving to Tflite')
    converter = tf.lite.TFLiteConverter.from_concrete_functions([new_infer_fn.get_concrete_function()])

    converter.target_spec.supported_ops = [
      tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
      tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
    ]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    tflite_model_path = os.path.join('', 'lite_model.tflite')

    tflite_model = converter.convert()
    with tf.io.gfile.GFile(tflite_model_path, 'wb') as f:
        f.write(tflite_model)


if __name__ == '__main__':
    tf_lite_convert()
```

**Standalone code to reproduce the issue (Android)**
```
@WorkerThread
    public synchronized void loadModel(String modelPath) {
        AssetManager assetManager = this.context.getResources().getAssets();
        ByteBuffer buffer = loadModelFile(assetManager, modelPath);
        if (buffer == null){
            return;
        }
        Interpreter.Options opt = new Interpreter.Options();
        opt.setNumThreads(NUM_LITE_THREADS);
        tflite = new Interpreter(buffer, opt);
    }
```

**Gradle Dependencies**
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.1.0-rc1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'org.apache.commons:commons-io:1.3.2'
}
```

Any help would be greatly appreciated!

**Comment by gcervantes8** [comment] 2020-12-02 15:47
I get the same error using these Android nightly builds
```
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'
```

The same error occurs when running **2.4-rc3**

```
    java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Did not get operators or tensors in subgraph 0.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:282)
        at arl.testnmt.MainActivity.loadModel(MainActivity.java:128)
        at arl.testnmt.MainActivity$2.run(MainActivity.java:109)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Using the latest nightly version: **2.5-dev20201201** I also get the same error.

**Comment by ymodak** [comment] 2020-12-03 23:20
I think the generated graph from your example is not correct. You can try uploading your `tflite` file in this [netron app](https://netron.app/) and visualize.

**Comment by gcervantes8** [comment] 2020-12-04 19:45
I looked at the output through Netron and the model looks good, I believe.

It seems I can get it running if I comment out the line:
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`

This seems like a TensorFlow bug to me, I'm not sure why that would cause an issue. (I tested this with 2.4-rc3)

**Comment by abattery** [comment] 2020-12-07 05:47
Interesting. @gcervantes8 Could you provide your tflite to us and the snapshot of the Netron app?

**Comment by gcervantes8** [comment] 2020-12-07 17:43
Hello @abattery I attached a zip with the models.
Two models; one with the optimizer (doesn't work), the other without the optimizer (works):
[lite_models.zip](https://github.com/tensorflow/tensorflow/files/5654245/lite_models.zip)

I am using version 4.6.5 of Netron

**Comment by abattery** [comment] 2020-12-07 22:23
This bug is related to the optimization toolkit. @daverim @teijeong could you take a look?

**Comment by gcervantes8** [comment] 2020-12-15 15:58
I'm still getting the bug, so I don't think the issue should be marked as stale or close.

**Comment by abattery** [comment] 2020-12-16 03:05
I can reproduce this issue. Will take a look shortly.

**Comment by abattery** [comment] 2020-12-16 03:23
@gcervantes8 The generated graph does not have any operators since the tf.zero output is constant regardless of the feature input. TFLite currently requires at least one operator and one tensor in a graph. Is this graph meaningful anyway to your case even though it just provides a constant tensor? I guess you can just use zero values in the target language. This kind of graph is very unusual.

**Comment by gcervantes8** [comment] 2020-12-17 20:04
@abattery This is not a meaningful graph.  I was debugging a model to find why I was getting an error, so I started simplifying the model.  Eventually I got this error and I thought this was the issue. but it seems when removing components of the model, I formed a graph that was invalid.
Thank you for helping me with this.

**Comment by sushreebarsa** [comment] 2021-07-21 06:58
@gcervantes8 Many bugs have been fixed in the latest version of Tensorflow. Can you please execute your code using Latest stable Version of Tensorflow 2.5 and let us know if the issue still persists?   Thanks!

**Closed** 2021-08-05 19:05 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.3

**Comment by RubensZimbres** [comment] 2024-07-17 03:15
Same error on MediaPipe with ai-edge-torch export:

Error: INVALID_ARGUMENT: Classification tflite models are assumed to have a single subgraph.; Initialize was not ok; StartGraph failed

Issue filed here:

[](https://github.com/google-ai-edge/ai-edge-torch/issues/91)
