### ISSUE TITLE
[2.0] Combining metrics places updates on the wrong graph

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#26703] opened 2019-03-14 14:40 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: `2.0.0.dev20190311`
- Python version: 3.6.6
- CUDA/cuDNN version: 10.0

**Describe the current behavior**

I wanted to define a custom metric that is the combination of 2 metrics:

```python
import tensorflow as tf

class F1(tf.metrics.Metric):

  def __init__(self, **kwargs):
    super(F1, self).__init__(**kwargs)
    self.precision = tf.metrics.Precision()
    self.recall = tf.metrics.Recall()

  @property
  def updates(self):
    return self.precision.updates + self.recall.updates

  def update_state(self, y_true, y_pred):
    self.precision.update_state(y_true, y_pred)
    self.recall.update_state(y_true, y_pred)

  def result(self):
    precision = self.precision.result()
    recall = self.recall.result()
    return (2 * precision * recall) / (recall + precision)
```

But when run in graph mode, the `updates` operations are placed on the wrong graph which raises an error in the Estimator code:

https://github.com/tensorflow/estimator/blob/v2.0.0-alpha/tensorflow_estimator/python/estimator/model_fn.py#L497

Am I missing something here? The `F1` implementation looks correct so I suspect this is a bug.

**Describe the expected behavior**

The updates should be placed on the default graph.

**Code to reproduce the issue**

```python
with tf.Graph().as_default() as graph:
  precision = tf.metrics.Precision()
  precision.update_state([0, 0, 1], [1, 0, 1])
  print(precision.updates[0].graph is graph)  # True

  f1 = F1()
  f1.update_state([0, 0, 1], [1, 0, 1])
  print(f1.updates[0].graph is graph)  # False
```

**Comment by alextp** [comment] 2019-03-25 17:41
@pavithrasv can you look at this?

**Comment by pavithrasv** [comment] 2019-03-25 18:39
Yes, I am able to repro, will look into the fix.

**Comment by pavithrasv** [comment] 2019-03-25 19:07
@guillaumekln is there a reason you have overridden `updates` property? 

We wrap metrics `update_state` API in `tf.function` internally to allow users to write simple metric updates. Since you have overridden updates, the updates you get are the updates of the inner Precision, Recall metrics which are in the `FuncGraph` scope. Your F1 metric should work as expected with both Estimator and Keras APIs without having to override updates. Thank you!

**Comment by guillaumekln** [comment] 2019-03-25 19:35
I'm not sure that's the issue because if you don't override `updates`, it will still return the updates of the inner Precision and Recall metrics.  For example, when `updates` is not overriden, the graph of some updates is still not the default one:

```python
f1 = F1()
f1.update_state([0, 0, 1], [1, 0, 1])
print(f1.updates[0].graph is graph)  # True
print(f1.updates[1].graph is graph)  # False
print(f1.updates[2].graph is graph)  # False
```

I was not sure why there are 3 updates in this case, that's why I overrided `updates`.

Note that when integrating with Estimator, the error is the same whether `updates` is overriden or not:

```text
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 180, in __new__
    eval_metric_ops = _validate_eval_metric_ops(eval_metric_ops)
  File "/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 573, in _validate_eval_metric_ops
    'eval_metric_ops', '{0}: {1}'.format(key, val.name)))
ValueError: eval_metric_ops with "precision: group_deps" must be from the default graph. Possible causes of this error include: 

1) eval_metric_ops was created outside the context of the default graph.

2) The object passed through to EstimatorSpec was not created in the most recent call to "model_fn".
```

**Comment by guillaumekln** [comment] 2019-04-10 10:15
For other users facing this, a possible workaround is to override the `__new__` method:

```python
class F1(tf.metrics.Metric):
  def __new__(cls, *args, **kwargs):
    return tf.keras.layers.Layer.__new__(cls)
```

**Comment by gadagashwini** [comment] 2019-09-13 10:10
@guillaumekln,
Looks like it is fixed in latest Tf 2.0 nightly version.
Please have a look at colab gist [here](https://colab.sandbox.google.com/gist/gadagashwini/08cfa8cffc1958a581de88b6927ed7ea/untitled148.ipynb). Thanks!

**Comment by guillaumekln** [comment] 2019-09-13 10:24
I does not seem like it. The second `print` should display True.

**Comment by Saduf2019** [comment] 2020-03-19 12:47
@guillaumekln 
Could you please check [this gist](https://colab.sandbox.google.com/gist/Saduf2019/3cd2a6de34d417b28aefcc2db2d6ad07/26703.ipynb) run on latest version of tensorflow, and let us know if it helps. Thanks!

**Comment by guillaumekln** [comment] 2020-03-19 12:54
Your gist shows that the issue is still not fixed (both `print` should output `True`). However, I'm no longer interested in this issue and it does not seem other users were impacted, so feel free to close it.

**Comment by Saduf2019** [comment] 2020-03-19 14:42
Moving the issue to closed status as confirmed.

**Closed by Saduf2019** 2020-03-19 14:42 UTC
Labels: TF 2.0-rc0, comp:ops, type:bug
