### ISSUE TITLE
large String[] create Tensor in java

### ISSUE THREAD

**Issue by gxsaccount** [tensorflow/tensorflow#19829] opened 2018-06-07 09:18 UTC
i use this way to create a tensor by a large String[] in java:    
* // Valid: Matrix of String tensors.
   * // Each element might have a different length.
   * byte[][][] matrix = new byte[2][2][];
   * matrix[0][0] = "this".getBytes("UTF-8");
   * matrix[0][1] = "is".getBytes("UTF-8");
   * matrix[1][0] = "a".getBytes("UTF-8");
   * matrix[1][1] = "matrix".getBytes("UTF-8");
   * Tensor<String> m = Tensor.create(matrix, String.class);
   * }</pre>

however,it cost too much time. my String[] length of 6000+,create the tensor will cost 20+ m. how can i deal with it? thanks.

**Comment by tensorflowbutler** [comment] 2018-06-07 18:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-06-22 18:58
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-06-22 19:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tatianashp** [comment] 2018-06-22 19:33
@gxsaccount If you still have this question please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there.

**Comment by tensorflowbutler** [comment] 2018-07-07 18:37
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-23 23:02
It has been 31 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Closed** 2018-08-07 18:57 UTC
Labels: stat:awaiting response

**Comment by tensorflowbutler** [comment] 2018-08-07 19:02
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
