### ISSUE TITLE
Issue with retrain.py, "could not convert string to float" when creating bottlenecks

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#2296] opened 2016-05-09 19:22 UTC
### Environment info
Operating System:
Ubuntu 14.04 
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 7.5, cuDNN v2 (6.5)
`lrwxrwxrwx 1 root root 19 May  9 09:11 /usr/local/cuda -> /usr/local/cuda-7.5`

Installed the Nightly pip package from April 12th, with GPU support
Tensorflow version: 0.7.1

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Running the retrain with a very large image directory (around 600k files) causes the training to fail around 3/4 the way through, during the bottleneck creation process. It always seems to fail while within the same label folder, but it does not appear that any file names within that label folder are corrupted or named incorrectly.

### What have you tried?
1. Changing the number of training steps
2. Checking to see if any files are less than 30k (theoretically, very small files are likely to be corrupted jpeg data)

### Logs or other output that would be helpful
For 610,000 files, the process can't seem to get through more than 415k. Am I simply just using too many files? Or am I missing a very, very subtle naming convention issue?

## Full stack trace:
```File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "retrain_reshape_error.py", line 695, in main
    cache_bottlenecks(sess, image_lists, FLAGS.image_dir, FLAGS.bottleneck_dir, jpeg_data_tensor, bottleneck_tensor)
  File "retrain_reshape_error.py", line 400, in cache_bottlenecks
    image_dir, category, bottleneck_dir, jpeg_data_tensor, bottleneck_tensor)
  File "retrain_reshape_error.py", line 372, in get_or_create_bottleneck
    bottleneck_values = [float(x) for x in bottleneck_string.split(',')] 
ValueErrror: could not convert string to float```

I should also note that I have been using this training process for the last few months with absolutely no failure.

Thanks!

Oren

**Comment by yaroslavvb** [comment] 2016-05-09 19:53
I don't think you are using too many files, however using large amounts of data makes it more likely to expose underlying bugs. The error indicates that "bottleneck_string" contains some non-numeric characters. Not familiar with that part of code, maybe @petewarden  has an idea how non-digits could've snuck into `bottleneck_string`?

**Comment by oweingrod** [comment] 2016-05-09 20:02
@yaroslavvb Yup, I had the same idea. Corrupted JPEG files would theoretically be missing the JPEG "tag" at beginning of file, right? I tried looking for that tag specifically but the process took prohibitively long on my machine.

**Comment by yaroslavvb** [comment] 2016-05-09 20:26
Yes, it probably could be missing. @dave-andersen had fun dealing with various forms of corruption when trying to reprocess imagenet dataset. Some ".jpg" files in the set were actually ".png" files in disguise

**Comment by oweingrod** [comment] 2016-05-09 20:29
@yaroslavvb the one issue is that I've created all of the files through an automated process, so it doesn't quite make sense that just one would be corrupted.

**Comment by oweingrod** [comment] 2016-05-09 20:52
@yaroslavvb Do you think, though, that there would be a hard-cap limit for number of images trained using this transfer learning approach? Eventually I would like to build my own CNN (or train Inception from scratch) but I'll likely have to wait for the new GTX1080 to be able to do that with any speed

**Comment by yaroslavvb** [comment] 2016-05-09 20:58
There shouldn't be a theoretical cap, but there could be practical caps. In my own experiments I saw overfitting happening when using <1M images. However, when increasing to 20M, I didn't see overfitting after hundreds of millions of steps, so I've been using it as personal rule of thumb for desired number of training images. I'm expecting GTX1080 to be 2x faster than TitanX so it's not a great panacea. It'll be faster for float16, but probably will require adjustments to training procedure.

**Comment by oweingrod** [comment] 2016-05-09 21:06
@yaroslavvb Interesting. Another question—albeit a stupid one—should the number of training steps reflect the number of images 1-1? As in, 600k images, 600k training steps?

**Comment by yaroslavvb** [comment] 2016-05-09 21:14
If you had something like 1B images, then you could train for one epoch
without fearing losing much.
But for 600k you probably will need several passes to get convergence (a
few dozen epochs at batch size 32 maybe?). I don't remember the details off
the top of my head, but ImageNet papers should talk about how many epochs
they used

**Comment by oweingrod** [comment] 2016-05-09 21:16
@yaroslavvb I'll take a look there. Thanks a lot!

**Comment by yaroslavvb** [comment] 2016-05-09 21:18
No problem, closing this for now since not sure what can be done on our side, but feel free to re-open if you are able to get more debugging info (ie, the contents of `bottleneck_string` for the failing example)

**Comment by oweingrod** [comment] 2016-05-09 21:40
Attempting to grab that data now.

**Comment by dave-andersen** [comment] 2016-05-09 23:48
I have a helper program I used to validate all of the imagenet files, but it's a little too Google-specific to be useful more broadly.  The heart of it, though, was just:

... do something to read in your JPEG into a string called image_buffer ...

  features = tf.parse_single_example(example_serialized, feature_map)
  image_buffer = features['image']
  filename = features['filename']

  image_saved = tf.Variable('')
  save_image = image_saved.assign(image_buffer)
  decode_saved_image = tf.image.decode_jpeg(image_saved)


  init = tf.initialize_all_variables()
  with tf.control_dependencies([decode_saved_image]):
    force_decode_no_copy = tf.no_op()

  with tf.Session() as sess:
    sess.run(init)
    tf.start_queue_runners()

    try:
      while True:
        key, fn, _ = sess.run([exid, filename, save_image])
        try:
          _ = sess.run(force_decode_no_copy)
        except:
          print "Error decoding ", key, fn

    except tf.errors.OutOfRangeError:
      print "OK"

You just need a wrapper mechanism to run a bunch of parallel threads for this and handle the input depending on how you're getting it all read in.

**Comment by oweingrod** [comment] 2016-05-10 17:12
@yaroslavvb new information! I tried catching the error and continuing after skipping the image file in question.

`Creating bottleneck at ~/tmp/bottleneck/832764-001/3-output00000727.jpg.txt
E tensorflow/stream_executor/cuda/cuda_driver.cc:932] failed to allocate 190.44M (199688192 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY`

So, looks like it was a memory issue causing the ValueError. How can I free up more GPU memory during the process? I have ~4GB.

**Comment by girving** [comment] 2016-06-08 00:53
@oweingrod: What's the status of this?  It seems to have fallen through the cracks.  Cc @petewarden.

**Comment by petewarden** [comment] 2016-06-22 08:18
Since there's been no update on this for a while, closing for now. Please reopen if the issue is still occurring.

**Closed by petewarden** 2016-06-22 08:18 UTC
Labels: awaiting response

**Comment by rizasif** [comment] 2017-01-29 08:18
Hello, I am having the same issue. I am using a docker container to train a dataset of almost 101000 images. Tensorflow starts creating bottlenecks of the images and after creating 15500 bottleneck files crashes with the following error:

```
15500 bottleneck files created.
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1012, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 782, in main
    jpeg_data_tensor, bottleneck_tensor)
  File "tensorflow/examples/image_retraining/retrain.py", line 440, in cache_bottlenecks
    jpeg_data_tensor, bottleneck_tensor)
  File "tensorflow/examples/image_retraining/retrain.py", line 405, in get_or_create_bottleneck
    bottleneck_values = [float(x) for x in bottleneck_string.split(',')]
ValueError: could not convert string to float:
```

I am not really sure that it is a memory issue. Even if so, how should I try and clean it? I am using Windows 10 64-bit with Docker 1.13

**Comment by rizasif** [comment] 2017-01-29 09:53
So I placed some checks in the retrain.py file and its working fine now. From What I understand this is not because of a faulty image file but a faulty bottleneck file. As soon as the error was caught by my checks, the script started creating new bottleneck files instead of checking the cached ones. 

In other words, if an incomplete bottleneck file exists in the cache then this error arises  (this file can be produced because of sudden system shutdown).

Please add some checks to the code. I'll paste my solution below:

```
#retrain.py
...
def get_or_create_bottleneck(sess, image_lists, label_name, index, image_dir,
                             category, bottleneck_dir, jpeg_data_tensor,
                             bottleneck_tensor):
...
  with open(bottleneck_path, 'r') as bottleneck_file:
    bottleneck_string = bottleneck_file.read()
  
  #avoiding non float values
    try:
      bottleneck_values = [float(x) for x in bottleneck_string.split(',')]
    except:
      print("Invalid float found, sending None instead")
      return None

  return bottleneck_values

...
def cache_bottlenecks(sess, image_lists, image_dir, bottleneck_dir,
                      jpeg_data_tensor, bottleneck_tensor):
...
      for index, unused_base_name in enumerate(category_list):
        bNeck = get_or_create_bottleneck(sess, image_lists, label_name, index,
                                 image_dir, category, bottleneck_dir,
                                 jpeg_data_tensor, bottleneck_tensor)
        if bNeck is not None:
          how_many_bottlenecks += 1
          if how_many_bottlenecks % 100 == 0:
            print(str(how_many_bottlenecks) + ' bottleneck files created.')
...
def get_random_cached_bottlenecks(sess, image_lists, how_many, category,
                                  bottleneck_dir, image_dir, jpeg_data_tensor,
                                  bottleneck_tensor):
...
  for unused_i in range(how_many):
    label_index = random.randrange(class_count)
    label_name = list(image_lists.keys())[label_index]
    image_index = random.randrange(MAX_NUM_IMAGES_PER_CLASS + 1)
    bottleneck = get_or_create_bottleneck(sess, image_lists, label_name,
                                          image_index, image_dir, category,
                                          bottleneck_dir, jpeg_data_tensor,
                                          bottleneck_tensor)
    if bottleneck is not None:
      ground_truth = np.zeros(class_count, dtype=np.float32)
      ground_truth[label_index] = 1.0
      bottlenecks.append(bottleneck)
      ground_truths.append(ground_truth)
  return bottlenecks, ground_truths

...
def get_random_distorted_bottlenecks(
    sess, image_lists, how_many, category, image_dir, input_jpeg_tensor,
    distorted_image, resized_input_tensor, bottleneck_tensor):
...
    bottleneck = run_bottleneck_on_image(sess, distorted_image_data,
                                         resized_input_tensor,
                                         bottleneck_tensor)
    if bottleneck is not None:
      ground_truth = np.zeros(class_count, dtype=np.float32)
      ground_truth[label_index] = 1.0
      bottlenecks.append(bottleneck)
      ground_truths.append(ground_truth)
  return bottlenecks, ground_truths
