### ISSUE TITLE
build Error  Tabulations are not allowed for identation. Use spaces instead.

### ISSUE THREAD

**Issue by helloworkcupid** [tensorflow/tensorflow#18924] opened 2018-04-27 12:29 UTC
ERROR: E:/demoall/demofour/tf/tensorflow/WORKSPACE:60:5: Tabulations are not allowed for identation. Use spaces instead.
ERROR: E:/demoall/demofour/tf/tensorflow/WORKSPACE:61:2: Tabulations are not allowed for identation. Use spaces instead.
ERROR: E:/demoall/demofour/tf/tensorflow/WORKSPACE:56:2: indentation error
ERROR: E:/demoall/demofour/tf/tensorflow/WORKSPACE:61:6: syntax error at 'outdent': expected expression
ERROR: error loading package 'external': Failed to parse WORKSPACE file
ERROR: error loading package 'external': Failed to parse WORKSPACE file
INFO: Elapsed time: 1.773s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tensorflowbutler** [comment] 2018-04-28 00:47
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-05-12 18:31
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-27 12:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-05-27 17:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-05-27 17:07 UTC
Labels: stat:awaiting response
