### ISSUE TITLE
Java wrapper floods temp dir with copies of extracted native library

### ISSUE THREAD

**Issue by sabi0** [tensorflow/tensorflow#18397] opened 2018-04-10 21:44 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 x64
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: None

### Describe the problem

I've been working on a Java application that uses TensorFlow. I launched it thousand times - unit tests, debugging sessions, etc. And at some point I discovered I had 8 GB of tensorflow_jni.dll copies in my Temp directory.

Apparently `deleteOnExit()` is not enough to cleanup the extracted native library ([NativeLibrary.java:150](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/NativeLibrary.java#L150)). Not on Windows at least. It appears DLL is still loaded when the deletion is attempted. So the deletion fails and the DLL is left behind.

A better approach would be to use semi-static path for library extraction rather than fully random.
In such case the library could be deleted or re-used upon the next application run.

I would suggest to use a target folder name like this:
```
File tmp = new File(System.getProperty("java.io.tmpdir"));
File dir = new File(tmp, "tensorflow-" + TF_VERSION + '-' + System.getProperty("user.name").hashCode());
```

And then check if the folder and files exist already upon startup. And either delete them and extract again (better security) or just call `System.loadLibrary()` directly.

You could still keep using `deleteOnExit()`. When it works properly the only copy of the library will not be left laying on the disk after JVM shutdown.

A similar approach is used by other native libraries handling frameworks. For example, in JNA project.
See https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java

**Comment by asimshankar** [comment] 2018-04-13 19:59
Thanks for the report.

To be extra sure, the name of the directory should probably be based on the checksum of its contents, which will be a little harder to engineer. We don't want to use a fixed directory otherwise we could run into interference between programs compiled against different versions of the library.

I don't believe this problem occurs on Linux/Mac though. I don't have enough experience with Windows - is there something about the use of `System.loadLibrary()` that causes deleting the file to fail?

Marking this as "Contributions Welcome" in case someone with a stronger understanding of the JVM on Windows can suggest a clean fix, or if someone wants to take on the fixed directory (in which case I would strongly recommend that the directory name be a function of the _contents_ of the `.jar` file being extracted and not a fixed string).

**Comment by asimshankar** [comment] 2018-04-13 20:00
(CC @saudet as well - in case he has some insights)

**Comment by sabi0** [comment] 2018-04-13 21:03
It's not about `System.loadLibrary()` but about the way files are handled in Windows.
On Linux (and I suppose Mac) opened files can be deleted (`unlink()`-ed). On Windows - not.
And when JVM processes `deleteOnExit`s DLLs are still loaded into JVM address space, i.e. the files are still open.
There is a hacky way of using a dedicated separate class loader for loading DLLs. And then calling `System.gc()` after null-ing the class loader reference. It helps ... sometimes.

I included a version of the Tensorflow into the directory name in the sample code above. Do you think it won't be enough?
Also each user should have his own folder to avoid access rights conflicts. Hence the `System.getProperty("user.name").hashCode()` part. Hash code is used to avoid problems in case user name contains national symbols or spaces.

**Comment by saudet** [comment] 2018-04-15 00:44
@asimshankar Yes, I do. That's been fixed a long time ago in JavaCPP! :)

The problem is that on Windows it's not possible to delete a DLL after it's been loaded. We need to end the process, and let some other process do the clean up. I used to have a hack for that in JavaCPP but switched to using a cache instead, because it wouldn't work with JavaFX, among other things: https://github.com/bytedeco/javacpp/issues/60

@sabi0 So, one way to work around this is by using the JavaCPP Presets for TensorFlow:
https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow
You'll get access to the C++ API from Java, but we can keep using the official Java API as well.

A build for Windows has also been released:
https://github.com/bytedeco/javacpp-presets/issues/111#issuecomment-380322141

/cc @agibsonccc

**Comment by sabi0** [comment] 2018-04-16 10:07
@saudet Thanks. I will have a look at JavaCPP.

@asimshankar It is possible to use fully random name for DLL (i.e. not bother with content checksum) as long as the folder name is predictable. Here is how it could work:
Folder name could be like this:
```
File dir = new File(tmp, "tensorflow-" + System.getProperty("user.name").hashCode());
```
Extracted file names could be fully random, e.g. `tf_jni-2387168.dll`. But when such file is extracted another "marker" file is created - `tf_jni-2387168.dll.lock`.
The latter one is immediately registered with `deleteOnExit()`. JVM will not have problems deleting it on any platform.

And then upon start the application scans the user folder and deletes any files that don't have matching `.lock` files. And then proceeds to extract the resources (under random names).
This might still left some files in Temp on Windows (when user stops using TF). But would help to avoid copies of resources piling up.

**Comment by saudet** [comment] 2018-04-16 10:38
Extracting DLLs every time a new JVM is launched is inefficient though. For
something as big as TensorFlow it takes a few seconds. Consider also that
frameworks like Hadoop or Spark tend to launch multiple JVMs during
execution. That's another reason JavaCPP uses a cache. BTW, JNA is not
performance conscious so it's not a good reference if one is interested in
efficiency.

**Comment by asimshankar** [comment] 2018-04-18 00:06
Thanks @saudet 

Caching seems very reasonable. Though, again, the caching should handle different versions/configurations correctly. So, some form of identification (like the checksum of the file contents) should be included, right? (Seems like JavaCPP uses maven coordinates for the "cache key"?)

**Comment by saudet** [comment] 2018-04-18 03:46
Yes, there needs to be some kind of system for that. JavaCPP doesn't use directly Maven coordinates because they are not available when running from an uber JAR, for example, as required by Spark, or just for a standalone application. Instead, it uses the filename of the JAR file itself plus of the path to the files inside it, which happen to contain the Maven coordinates when loaded with it.

BTW, including additional resources such as header files in the JAR file and extracting them to a cache like this also allows C++ libraries to link with it, not just Java libraries. That's what is happening with, for example, Caffe depending on OpenCV, OpenBLAS, and HDF5 here: https://github.com/bytedeco/javacpp-presets/blob/master/caffe/pom.xml#L17-L37  Though, in the case of TensorFlow, I'm assuming everything can be managed with Bazel...

**Comment by saudet** [comment] 2020-01-30 12:54
@MarkDaoust This one also could be considered "fixed" since we're now using JavaCPP for https://github.com/tensorflow/java

**Comment by MarkDaoust** [comment] 2020-01-30 14:35
Thanks.

**Closed by MarkDaoust** 2020-01-30 14:35 UTC
Labels: stat:contributions welcome, type:bug
