### ISSUE TITLE
Dataset to TFRecord

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#16926] opened 2018-02-11 00:46 UTC
The dataset API is excellent, I am even using it to perform data augmentation before training. However, I notice that when converting my dataset to tfrecord I follow a pattern that might easily be automated as a `to_records` method, in fact I think this is somewhat similar to using the `cache` method. Anyway, it would make it very straight forward for dataset users to create tfrecords.

**Comment by tensorflowbutler** [comment] 2018-02-11 13:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mrry** [comment] 2018-02-12 17:21
This is a fine suggestion, and something we have been discussing internally. I'm assigning this issue to @jsimsa, who has expressed interest in developing it.

@cgarciae There are a lot of possible designs for a feature like this. Have you had any thoughts on what your ideal API would look like for this task?

**Comment by cgarciae** [comment] 2018-02-12 18:05
@mrry Very glad you are thinking about this!

The signature could be `to_records(self, features, ...)` where:

1. It follows the same API of `tf.parse_example` so you can reuse the same concepts/structures. 
2. Only work on dict-based datasets so you can match the structure in the `features` dict to the structure of the dataset dict when creating the `tf.Example`. People who use the tuple-based datasets can just `map` to a dict beforehand.
3. Create a `tf.ImageFeature` class that indicates you want to convert the ndarray to an encoded image in bytes.

Btw: I find that tuple-based datasets are harder to maintain when you have many features/columns, the documentation should switch to dict-based approach, or you should even provide a `Row` object like pyspark so we can access the fields using `.`.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:51
Nagging Assignee @jsimsa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cgebe** [comment] 2018-03-18 00:12
I guess this functionality would simplify a lot and encourage the usage TFRecord files. Furthermore, the general documentation on creating/writing to TFRecord files is still sparse.

Was there some progress on this issue?

**Comment by tensorflowbutler** [comment] 2018-04-04 00:37
Nagging Assignee @jsimsa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mattiasarro** [comment] 2018-04-12 15:29
@cgarciae Could you post an example of how you convert a Dataset to TFRecords?

I tried this hacky approach:

```
def to_tfrecords(ds, fn):
    ds = ds.cache(fn)
    iterator = ds.make_one_shot_iterator()
    features = iterator.get_next()

    with tf.Session() as sess:
        while True:
            try:
                sess.run(features)
            except tf.errors.OutOfRangeError:
                break
```

where `ds` is a Dataset and `fn` is a file path. This creates `fn + ".data-00000-of-00001"` and `fn + ".index"` files successfully, but when I try reading it with `tf.python_io.tf_record_iterator` I get a `DataLossError: corrupted record at 0` (TF 1.7). Perhaps it's not actually a TFRecords file or is up somehow, but I haven't found much documentation about cached datasets.

**Comment by tensorflowbutler** [comment] 2018-04-27 18:42
Nagging Assignee @jsimsa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-12 18:32
Nagging Assignee @jsimsa: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by monstrim** [comment] 2018-05-19 17:20
@cgarciae thanks for that, I'm using it!

I suppose one could pass `parse_fn` as an argument:

```
def to_tfrecord(ds, parse_fn, record_path):
    with tf.Session() as sess, tf.python_io.TFRecordWriter(record_path) as writer:
        generator = dataset_generator(ds, sess)
        
        for row in generator:
            example = parse_fn(row)
            writer.write(example.SerializeToString())
```

**Comment by tensorflowbutler** [comment] 2018-06-03 18:31
Nagging Assignee @jsimsa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-18 18:45
Nagging Assignee @jsimsa: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-03 12:47
Nagging Assignee @jsimsa: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-18 19:03
Nagging Assignee @jsimsa: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-02 19:07
Nagging Assignee @jsimsa: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-17 18:57
Nagging Assignee @jsimsa: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-01 18:43
Nagging Assignee @jsimsa: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-16 12:30
Nagging Assignee @jsimsa: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-01 18:55
Nagging Assignee @jsimsa: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-16 12:47
Nagging Assignee @jsimsa: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-31 12:43
Nagging Assignee @jsimsa: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-15 18:55
Nagging Assignee @jsimsa: It has been 179 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jsimsa** [comment] 2018-11-15 19:05
On a related note that the [updated tf.Example tutorial](https://github.com/tensorflow/docs/pull/188) illustrates how to use tf.data for both reading and writing TFRecord files, which is recommended over using `tf.python_io`.

**Closed by jsimsa** 2018-11-15 19:05 UTC
Labels: stat:awaiting tensorflower, type:feature

**Comment by amxineohp** [comment] 2019-06-25 13:12
Hi,
Why this issue closed? I did not see the problem solved, if not could anyone point me to the API?
@jppgks 
Your solution is really good, write once use anywhere. It looks like your solution is only worked for eage execution.

I try hard to bypass creating tf records for cloud TPU, but failed. So looks I must do. I hope I can have a solution work well for different projects when building different models, generally speaking, when I build a model, I will create list of input features(named tuple). It work well for the TF API tf.parse_single_example, I can create the record_spec like below:      
```
for fea in self._input_features:
     record_spec[fea.name] = tf.FixedLenFeature(fea.shape, fea.dtype). 
tf.parse_single_example(tfrecord, record_spec)
```
So if the dataset have an API like tf.data.Dataset.to_tfrecords(record_spec, fpath) would be great.

Follow jppgks, I can create a function like below, but the problem is it create lots of tenors in the graph.
```
def ds2tfrecord(ds, filepath):
    with tf.python_io.TFRecordWriter(filepath) as writer:
        itr = ds.make_one_shot_iterator()
        with tf.Session() as sess:
            try:
                while True:
                    feat_dict = itr.get_next()
                    features = {}
                    for name, fea in feat_dict.items():
                        serialized_tensor = tf.serialize_tensor(fea)
                        bytes_string = sess.run(serialized_tensor)
                        bytes_list = tf.train.BytesList(value=[bytes_string])
                        features[name] = tf.train.Feature(bytes_list=bytes_list)
                    # Create a Features message using tf.train.Example.
                    example_proto = tf.train.Example(features=tf.train.Features(feature=features))
                    example_string = example_proto.SerializeToString()
                    # Write to TFRecord
                    writer.write(example_string)
            except tf.errors.OutOfRangeError:
                pass
```

**Comment by bhack** [comment] 2020-06-08 23:41
You can track https://github.com/tensorflow/tensorflow/issues/38483
