### ISSUE TITLE
keras training parameter value incorrect

### ISSUE THREAD

**Issue by w19787** [tensorflow/tensorflow#39547] opened 2020-05-14 15:28 UTC
tensorflow ver: 2.1.0

```python
import tensorflow as tf
import numpy as np

class MyModel(tf.keras.Model):

    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
        self.dropout = tf.keras.layers.Dropout(0.5)

    def call(self, inputs, training=None):
        x = self.dense1(inputs)
        if training is True:
            print("in training")
            x = self.dropout(x, training=training)
        elif training is None:
            print("training None")
        else:
            print("not in training")
            
        return self.dense2(x)

model = MyModel()

optimizer = tf.keras.optimizers.Adam(1e-4)
loss = tf.keras.losses.CategoricalCrossentropy()
model.compile(optimizer, loss)
x = tf.random.normal((5,))
y = tf.ones((5,))
model.fit(x, y, epochs=1)
```
The system report "not in training first", then "in training".
![image](https://user-images.githubusercontent.com/731496/81953648-84e39b80-963a-11ea-8c4e-ac5b49afcb9e.png)

**Comment by amahendrakar** [comment] 2020-05-15 10:09
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/6b23743610aa062475517c8b99923420/39547.ipynb). 

On running the code with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/f371dada0012444bf75b1e066629e285/39547.ipynb#scrollTo=oBTbHGrfovim) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/422599f4acaf4fa19ee7d223c0a92a80/39547-tf-nightly.ipynb), facing an error stating `    ValueError: Shapes (None, 1) and (None, 5) are incompatible`. Please find the attached gist. Thanks!

**Comment by omalleyt12** [comment] 2020-05-21 00:15
@w19787 Thanks for the issue!

I fixed the example to pass batched tensors for `x` and `y` (IIUC these were just dummy values to show the error, not the root cause of the error).

It is now passing in TF2.2 for me:

```python
import tensorflow as tf
import numpy as np

class MyModel(tf.keras.Model):

    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
        self.dropout = tf.keras.layers.Dropout(0.5)

    def call(self, inputs, training=None):
        x = self.dense1(inputs)
        if training is True:
            print("in training")
            x = self.dropout(x, training=training)
        elif training is None:
            print("training None")
        else:
            print("not in training")
            
        return self.dense2(x)

model = MyModel()

optimizer = tf.keras.optimizers.Adam(1e-4)
loss = tf.keras.losses.CategoricalCrossentropy()
model.compile(optimizer, loss)
x = tf.random.normal((1, 5))
y = tf.ones((1, 5))
model.fit(x, y, epochs=1)
```

Closing bc I can't repro, but if you are still seeing this issue with TF2.2 please reopen!

**Closed by omalleyt12** 2020-05-21 00:15 UTC
Labels: TF 2.2, comp:keras, regression issue, type:bug
