### ISSUE TITLE
tutorials/rnn/translate/translate.py Errors

### ISSUE THREAD

**Issue by alexnanchen** [tensorflow/tensorflow#8505] opened 2017-03-17 16:49 UTC
Hello,

I am trying to run the "translate.py" example from the sequence to sequence tutorial but it fails.

The tensorflow version is today nightly built (tensorflow-1.0.1-cp35-cp35m-linux_x86_64.whl). The model git containing the tutorial  is at the latest commit on the master branch.

I am using a linux OS.

The error message is:

ValueError: Shape must be rank 2 but is rank 1 for 'model_with_buckets/sequence_loss/sequence_loss_by_example/sampled_softmax_loss/MatMul_1' (op: 'MatMul') with input shapes: [?], [?,1024]

Many thanks!

Alexandre Nanchen

**Comment by concretevitamin** [comment] 2017-03-17 21:19
I can't reproduce on my end.  Can you double-check the commit hash of the `translate.py` you're using?

**Comment by alexnanchen** [comment] 2017-03-18 07:58
The model git is at HEAD: e8464d33d363c6f8e90a29c08e5af11ef01be7a1 (Update the DRAGNN (#1191)) of 17 of March 2017

The translate.py  is: c902a86785052291083682c4b833747e7ea52597 (Ability to train the translation model ...) of January 3rd 2017 from Viacheslav Kovalevskyi.

I also tried to do again a "git clone https://github.com/tensorflow/models.git"  and then run "python tutorials/rnn/translate/translate.py".

Am I using the correct file?

Many thanks for this quick help!!

Alexandre Nanchen

**Comment by concretevitamin** [comment] 2017-03-19 16:58
I see at least two potentially related fixes after Jan 3, 2017: https://github.com/tensorflow/models/commits/master/tutorials/rnn/translate/seq2seq_model.py.

Could you retry after definitely pulling in those changes?  Feel free to reopen if this doesn't work for you.

**Comment by alexnanchen** [comment] 2017-03-19 17:29
Not sure to understand.

git log -n 1 tutorials/rnn/translate/seq2seq_model.py yield 

commit 0d8916f4b84e8687eb46696883b50b84ac6aa420

It always has been to this commit which is from March 2017 and I am on the master branch.

Can you please tell me which commit of the "model git" you are working with?

Many thanks.

Alex.andre Nanchen

**Comment by concretevitamin** [comment] 2017-03-19 17:37
Hmm, previously you stated

`The translate.py is: c902a86785052291083682c4b833747e7ea52597 (Ability to train the translation model ...) of January 3rd 2017 from Viacheslav Kovalevskyi.`

which is _before_ 0d8916, one of the fixes that I supposed would fix your problems.  Now that you've confirmed you're on 0d8916, could you retry the whole thing and see if the issue persisted?

If it did, let us know and feel free to reopen (/cc @nealwu).

**Comment by alexnanchen** [comment] 2017-03-19 17:45
Ah, some confusion. It was the "translate.py" file that had this date not the "seq2seq_model.py".

I did a git log -n 1 tutorials/rnn/translate/translate.py that indicated that the file "translate.py" file did not change from January 2017.

In the debug.txt file attached in previous comment there is indeed the "legacy_seq2seq.py" file that was I think, modified in commit 0d8916f4b84e8687eb46696883b50b84ac6aa420 from March 2017.

Does this make sense.

Sorry for the confusion.

Alex.

**Comment by alexnanchen** [comment] 2017-03-20 07:39
Hello,

Based on github rules I cannot reopen an issue when closed by a collaborator.

Alex.

**Comment by alexnanchen** [comment] 2017-03-20 10:31
The issue still persist. 

The only way I got it working is installing tensorflow 0.12 and doing a git checkout of the model directory at the last commit of **translate.py**.

Alex.

**Comment by concretevitamin** [comment] 2017-03-20 15:35
Re-opening this to see if @nealwu has some insights

**Comment by nealwu** [comment] 2017-03-20 19:39
I believe you have the same issue as this: https://github.com/tensorflow/models/issues/1221. It looks like the documentation on our site and the actual code are not in sync, which has caused some confusion [here](https://github.com/tensorflow/models/pull/982) and [here](https://github.com/tensorflow/models/issues/836). I'll check on what the correct argument order should be.

**Comment by nealwu** [comment] 2017-03-20 22:24
I believe this should be fixed now via https://github.com/tensorflow/models/pull/1226. If you run into further issues let me know.

**Closed by nealwu** 2017-03-20 22:24 UTC
Labels: stat:awaiting response

**Comment by alexnanchen** [comment] 2017-03-21 07:49
There is another error related to post tensorflow/tensorflow#8191

ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.GRUCell object at 0x7f6f517906a0> with a different variable scope than its first use.  First use of cell was with scope

Already tried to fix it without success.

Alex.

**Comment by nealwu** [comment] 2017-03-21 07:51
I believe that is similar to the discussion here: https://github.com/tensorflow/models/pull/1131. If you are running the master version of TensorFlow, you may want to reinstall with TensorFlow 1.0 instead.

**Comment by alexnanchen** [comment] 2017-03-21 08:23
Yes, that solved it!

As a summary:
- use "model" git commit of 20 March 2017 f6e23e5618ef18625966c6668f1f90dca25dbc56
- use "official" release of tensorflow 1.0.1, i.e. pip install tensorflow

Many thanks!

Alex.
