### ISSUE TITLE
What replaces tf.data.get_output_shapes in TF 2?

### ISSUE THREAD

**Issue by jbgh2** [tensorflow/tensorflow#30774] opened 2019-07-16 20:53 UTC
TF 2 Datasets don't appear to have the output_shape property and there is no tf.data.get_output_shapes. 

What do we use instead?

**Comment by ppham27** [comment] 2019-07-16 21:17
`tf.data.experimental.get_structure` should have shape information.

https://www.tensorflow.org/api_docs/python/tf/data/experimental/get_structure?hl=en

**Comment by jbgh2** [comment] 2019-07-17 18:51
@ppham27 Thank you! This could be made more obvious in the docs.

**Comment by anush-o** [comment] 2019-07-18 10:07
@jbgh2 ,
Looks like issue is resolved.Can i proceed for closure.Thanks!

**Comment by anush-o** [comment] 2019-07-23 09:06
Closing since the issue is resolved.Thanks!

**Closed by anush-o** 2019-07-23 09:06 UTC
Labels: comp:data, type:docs
