### ISSUE TITLE
Virtual GPU config crashes TensorFlow after physical GPU loaded

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#16753] opened 2018-02-04 12:41 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.3
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.5.0-2132-gbdea071e68', '1.5.0')
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**:0.9.0
- **GCC/Compiler version (if compiling from source)**: (Debian 4.9.2-10) 4.9.2
- **CUDA/cuDNN version**: 9.1/7.0
- **GPU model and memory**: K40m, 11439 MB
- **Exact command to reproduce**: see the following script

### Describe the problem

Check failed when creating virtual GPU device after loading physical GPU information with `tensorflow.python.client.device_lib.list_local_devices`.

### Source code / logs

Source code:

```python
import tensorflow as tf
from tensorflow.core.protobuf import config_pb2
from tensorflow.python.client import device_lib

device_lib.list_local_devices()

virtual_device_gpu_options = config_pb2.GPUOptions(
    visible_device_list='0',
    experimental=config_pb2.GPUOptions.Experimental(virtual_devices=[
        config_pb2.GPUOptions.Experimental.VirtualDevices(
            memory_limit_mb=[200, 300])]))
config = config_pb2.ConfigProto(gpu_options=virtual_device_gpu_options)

with tf.Session(config=config) as sess:
    with tf.device('/gpu:1'):
        result = sess.run(tf.constant(42))
```

Logs:

```
2018-02-04 20:36:14.145943: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-04 20:36:23.613248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1208] Found device 0 with properties:
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:02:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-02-04 20:36:23.806370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1208] Found device 1 with properties:
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:03:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-02-04 20:36:24.019343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1208] Found device 2 with properties:
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:82:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-02-04 20:36:24.341878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1208] Found device 3 with properties:
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:83:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-02-04 20:36:24.342631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1223] Device peer to peer matrix
2018-02-04 20:36:24.342769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1229] DMA: 0 1 2 3
2018-02-04 20:36:24.342789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1239] 0:   Y Y N N
2018-02-04 20:36:24.342803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1239] 1:   Y Y N N
2018-02-04 20:36:24.342815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1239] 2:   N N Y Y
2018-02-04 20:36:24.342827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1239] 3:   N N Y Y
2018-02-04 20:36:24.342846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1308] Adding visible gpu devices: 0, 1, 2, 3
2018-02-04 20:36:25.856113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/device:GPU:0 with 10755 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:02:00.0, compute capability: 3.5)
2018-02-04 20:36:26.092252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/device:GPU:1 with 10753 MB memory) -> physical GPU (device: 1, name: Tesla K40m, pci bus id: 0000:03:00.0, compute capability: 3.5)
2018-02-04 20:36:26.329914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/device:GPU:2 with 10755 MB memory) -> physical GPU (device: 2, name: Tesla K40m, pci bus id: 0000:82:00.0, compute capability: 3.5)
2018-02-04 20:36:26.567499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/device:GPU:3 with 10753 MB memory) -> physical GPU (device: 3, name: Tesla K40m, pci bus id: 0000:83:00.0, compute capability: 3.5)
2018-02-04 20:36:26.852624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1308] Adding visible gpu devices: 0
2018-02-04 20:36:26.852709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 200 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:02:00.0, compute capability: 3.5)
2018-02-04 20:36:26.852868: F tensorflow/core/common_runtime/gpu/gpu_id_utils.cc:42] Check failed: cuda_gpu_id.value() == result.first->second (0 vs. 1)Mapping the same TfGpuId to a different CUDA GPU id. TfGpuId: 1 Existing mapped CUDA GPU id: 1 CUDA GPU id being tried to map to: 0
```

**Comment by byronyi** [comment] 2018-02-04 12:43
Ping @aaroey as appeared to be the author of the virtual GPU feature.

**Comment by byronyi** [comment] 2018-02-05 10:48
Ping @lam8da as appeared to be the author of this feature.

**Comment by aaroey** [comment] 2018-02-05 16:24
This is a known bug, it has nothing to do with the virtual gpu feature. The problem is that some options (like the ones for gpu) in session config cannot be changed once they're set. `device_lib.list_local_devices()` invokes the [DeviceFactory::AddDevices()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/device_lib.i#L32) which takes an empty SessionOptions, and later when `tf.Session(config=config)` is called the gpu options in `config` will be ignored.

I believe if you remove the `list_local_devices()` call it should work. I'm closing this one, and please refer to #8021 #8136 #9374 for more information.

**Closed by aaroey** 2018-02-05 16:24 UTC

**Comment by rundembear** [comment] 2018-05-04 09:05
No idea if commenting on a closed ticket will do any good (my case is it won't) but this feature worked just fine in Tensorflow 1.3 even with first calling list_local_devices(). It does not work in Tensorflow 1.8. I also tried 1.3 with cuda 9 and that does not have any issues.

**Comment by venuswu** [comment] 2018-06-02 12:52
This is what I met when running mpirun with hvd.

**Comment by aaroey** [comment] 2018-06-04 14:38
Hi @rundembear and @venuswu,

Sorry for the late reply, I missed the updates here. Would you please try `device_lib.list_local_devices(session_config=config)` where `config` is the `ConfigProto` that is used later to create your session? This can make sure the same config is used within the process.

Let me know if there are any other questions. Thanks.

**Comment by alsrgv** [comment] 2018-06-05 18:28
@aaroey, it's a pretty bad user experience that TF crashes with an assertion error due to this. Any fundamental reason for this restriction?

**Comment by aaroey** [comment] 2018-06-06 15:57
@alsrgv, we already fix the crash issue in master branch and it should be in r1.9. If you build from master there should not be a crash, but an error will be shown instead.

**Comment by alsrgv** [comment] 2018-06-06 16:54
@aaroey, thanks - that's better. But is there a fundamental reason for this restriction?

**Comment by aaroey** [comment] 2018-06-12 18:10
@alsrgv this is because device allocators are shared objects in the process, and GPUOptions controls how allocators are created and bind to which device, so if device mapping is changed, the allocator-device bindings will be messed up, and an error will need to be returned before any damage to the runtime.
