### ISSUE TITLE
tensorflow/contrib/lite/examples/android/BUILD/android-profile is not a directory

### ISSUE THREAD

**Issue by kate-kate** [tensorflow/tensorflow#22167] opened 2018-09-09 08:15 UTC
Hi there. I have installed the latest version of tensorflow and trained SSD quantized model following [this article](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) very precisely. After the training was successfully done, I've decided to run the android tflite example project to check how my model (frozen graph) will work with it. I've installed 14b NDK version as it was recommended and I have API level 27.

Then I run 
```
bazel build -c opt --config=android_arm{,64} --cxxopt='--std=c++11' \
//tensorflow/contrib/lite/examples/android:tflite_demo
```
And it compiled successfully without errors. But when I opened the project with Android Studio, I can't sync it with Gradle because there is an error I mentioned above (I will add the screenshot). After any attempts of re-build it says: "Sync failed. Already finished"

<img width="830" alt="2018-09-09 10 48 54" src="https://user-images.githubusercontent.com/4061805/45262560-96b27b80-b421-11e8-91c0-ac32e95d1b38.png">

What should I do?

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra 10.13.4
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: 0.15.2-homebrew
- **GPU model and memory**: Intel Iris Graphics 6100 / 1536 MB

**Comment by theoamaya** [comment] 2018-09-09 09:11
Nice

**Comment by theoamaya** [comment] 2018-09-09 09:12
Thanks

**Comment by tensorflowbutler** [comment] 2018-09-26 19:00
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Elites2017** [comment] 2018-09-29 06:54
@kate-kate Did you figure it out? I have the same problem with Android Studio (on windows 10)

**Comment by kate-kate** [comment] 2018-09-30 07:00
@Elites2017 I have just built it on remote pure server and installed files with adb as it was described in [article](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193)

**Comment by Elites2017** [comment] 2018-09-30 18:55
@kate-kate I followed the article, but i ended up with the following error:
**Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]**

in the last step using this command: adb install bazel-bin/tensorflow/contrib/lite/examples/android/tflite_demo.apk

**Comment by izdi** [comment] 2018-10-02 07:01
Having same problems with latest master branch

**Comment by Elites2017** [comment] 2018-10-03 09:57
@izdi Try launch the app on another version of the android. I think the version was maybe the cause or:

Try adding this to build.gradle under Android to create apk for each type:

splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a', 'x86_64'
            universalApk true
        }
    }

**Comment by pwallrich** [comment] 2018-10-10 01:04
I fixed the issue by renaming the `Build` file in the `Android` folder to smth other then build.

**Comment by tensorflowbutler** [comment] 2018-10-24 12:41
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nutsiepully** [comment] 2018-11-06 21:54
This is happening because `gradle` is confusing the `build` directory with the `BUILD` file. By default, gradle stores build output in the `build` directory and also creates and `android-profile` file within it. In this case it's attempting to do that with the `BUILD` file.

We need to find a way to have gradle ignore the `BUILD` file, or potentially choose a different build directory.

**Comment by nutsiepully** [comment] 2018-11-06 22:10
This can be fixed by changing the build directory for gradle using `buildDir` for those running into this. I'm making the change to fix it.

**Closed** 2018-11-07 04:06 UTC
Labels: comp:lite
