### ISSUE TITLE
adding_an_op compile fail Windows unistd.h

### ISSUE THREAD

**Issue by sr99622** [tensorflow/tensorflow#40148] opened 2020-06-04 10:30 UTC
Tensorflow r2.2 compile on Windows 10.  The example adding_an_op will fail with error message file not found unistd.h.  Error occurs on line 74 of external/eigen_archive/unsupported/Eigen/CXX11/Tensor.  

There is an #ifdef EIGEN_USE_GPU conditional #include <unistd.h> which will fail on Windows, as this is a unix file.  It is actually conditionally excluded from Windows previously in the file at line 51, so it is unclear why the include is not part of that conditional.  Commenting out the line 74 will enable successful compilation on Windows without any immediately apparent side effects.  This was not tested on *nix.

Thank you for looking at this.

**Comment by Saduf2019** [comment] 2020-06-04 12:20
@sr99622 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sr99622** [comment] 2020-06-04 12:54
This problem occurs on Windows
The command used to compile the example adding_an_op is

`bazel build tensorflow/examples/adding_an_op/... `

File not found unistd.h
Error occurs on line 74 of external/eigen_archive/unsupported/Eigen/CXX11/Tensor.

The code of interest in that file is starting at line 41

`#ifdef _WIN32
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#include <windows.h>
#else
#include <stdint.h>
#include <unistd.h>  **/*********First instance of unistd.h*********/**
#endif

#ifdef _WIN32
#include <windows.h>
#elif defined(__APPLE__)
#include <mach/mach_time.h>
#else
#include <time.h>
#endif

#if defined(EIGEN_USE_THREADS) || defined(EIGEN_USE_SYCL)
#include "ThreadPool"
#endif

#ifdef EIGEN_USE_GPU
  #include <iostream>
  #if defined(EIGEN_USE_HIP)
    #include <hip/hip_runtime.h>
  #else
    #include <cuda_runtime.h>
  #endif
  #include <atomic>
  #include <unistd.h>  **/*********Second instance of unistd.h*********/**
#endif
`

Thank you so much for your help with this

**Comment by Saduf2019** [comment] 2020-06-04 17:23
@sr99622 
Please confirm if you have referred to this [link](https://www.tensorflow.org/install/source_windows) for the installation.
Please refer to this issue and let us know if it helps.
#39829

**Comment by sr99622** [comment] 2020-06-04 19:03
This is the same issue as #39829 and the same path has been followed.  The bug is in the code as described above.  The second instance of #include <unistd.h> is not excluded from the windows build as the first one is, and this will manifest when using the GPU section.  The problem can be temporarily fixed by commenting out the second instance of the include.

I would surmise from reading the previous post that the issue has not been addressed in the official source distribution.

Your assistance is greatly appreciated.

**Comment by sushreebarsa** [comment] 2021-08-03 15:45
@sr99622 It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:runtime, TF 2.2
