### ISSUE TITLE
there is no gen_summary_ops

### ISSUE THREAD

**Issue by wqh17101** [tensorflow/tensorflow#15580] opened 2017-12-22 09:37 UTC
when i 
from tensorflow.contrib.summary import summary_ops

it raises an error
---> 29 from tensorflow.contrib.summary import gen_summary_ops
     30 from tensorflow.core.framework import graph_pb2
     31 from tensorflow.python.eager import context

ImportError: cannot import name 'gen_summary_ops'

**Comment by tensorflowbutler** [comment] 2017-12-22 19:00
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wqh17101** [comment] 2017-12-23 00:54
Thank you for your reply.
In fact , I meet this problem when I tried to run the sample of multimodel in the tensor2tensor，the official sample.And it told me that there is no module tensorflow.contrib.eager. So I checked my tensorflow lib and found there was no eager module in the directory contrib. Then I downloaded the whole directory contrib from /tensorflow/tensorflow/contrib in the github and replaced the local one.Then the problem appered.
My tensorflow version is tensorflow-gpu 1.4.1. And I find that it is the latest version on the pypi .And all the other relevant libs work well.Acturally, it works well except running the scripts from tensor2tensor.
I guessed that maybe your codes in the contrib are not up-to-date

**Comment by quaeler** [comment] 2017-12-23 04:14
@wqh17101 The "gen" part of `gen_summary_ops` is there because the code for these operations is generated during the build process. If you only take the raw code from github and don't build, you will end up with no generated classes.

**Comment by wqh17101** [comment] 2017-12-23 04:20
So,how can I get the module correctly?

**Comment by quaeler** [comment] 2017-12-23 04:30
I have no experience with the GPU version of the Python libraries - so don't close this issue as it appears from what you've reported that there is some problem with the 1.4.1 GPU release.

To address your situation now, perhaps you could build your own Python wheel: https://www.tensorflow.org/install/install_sources

**Comment by tensorflowbutler** [comment] 2018-01-06 18:55
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by wqh17101** [comment] 2018-01-07 03:28
I have tried ,but it did not work. My os is windows10 .So i hope i can solve this problem by update the tensorflow. But It does not right work .

**Comment by tensorflowbutler** [comment] 2018-01-23 22:56
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment] 2018-01-31 02:20
I think your best option is to install the prepackaged binary via Anaconda/pip as per our [doc](https://www.tensorflow.org/install/install_windows). Let us know if that worked for you.

**Comment by tensorflowbutler** [comment] 2018-02-14 13:24
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-03 08:04
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-18 16:06
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-02 12:28
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-04-02 15:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-04-02 15:07 UTC
Labels: stat:awaiting response, type:build/install
