### ISSUE TITLE
Error while importing tensorflow

### ISSUE THREAD

**Issue by p69180** [tensorflow/tensorflow#29392] opened 2019-06-04 13:19 UTC
- OS Platform and Distribution : CentOS Linux release 7.5.1804
- TensorFlow installed from (source or binary): pip
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: pip

I get the following error when I try to import tensorflow:

Traceback (most recent call last):
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/users/pjh/Python-3.7.3/Lib/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/users/pjh/Python-3.7.3/Lib/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/users/pjh/Python-3.7.3/Lib/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/users/pjh/Python-3.7.3/Lib/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/users/pjh/.local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

-----------------------------------------------

I am not the root user in the server.
I installed python in my directory by downloading 'https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz'. Next I downloaded tensorflow by 'python3 -m pip install tensorflow --user' (python3 command is linked to the one installed in my directory). Then I executed 'python3' and tried to import tensorflow.

Thank you so much.

**Comment by wdirons** [comment] 2019-06-04 15:46
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/26826
Either use python 3.6, or you'll need to build TensorFlow from source to use it with python 3.7 and CentOS.

**Comment by gadagashwini** [comment] 2019-06-12 04:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-12 04:59 UTC
Labels: stat:awaiting response, subtype:centos, type:build/install
