### ISSUE TITLE
Is it possible to train custom models for Tensorflow Android?

### ISSUE THREAD

**Issue by nijatmursali** [tensorflow/tensorflow#28642] opened 2019-05-12 13:46 UTC
Hello,

Currently, I'm working on one projects and I need to train my models. I want to train models using YoloV2 and my question is that will my custom trained models work on Android Tensorflow if I add .pb model into the assets folder?

**System information**
- TensorFlow version 1.5.0
- Are you willing to contribute it (YES)

**It will not change the API .**

**I would like to benefit from this feature.**

**Comment by SanthoshRajendiran** [comment] 2019-05-14 06:14
You can work with pb models. 
Check out [https://github.com/dailystudio/ml/tree/master/object_detection](https://github.com/dailystudio/ml/tree/master/object_detection)

For better performance in terms of computation and time, you can convert your pb files into tflite and run on mobile phones

**Comment by nijatmursali** [comment] 2019-05-14 10:29
I would like to train my own models with YoloV2 and add it to Android/assets folder with .txt file(label names). I have tried using Faster RCNN and my android didn't accept that .pb model and application stopped working.

**Comment by gadagashwini** [comment] 2019-05-16 12:16
@nijatmursali It looks This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provides support faster. Let us know. Thanks!

**Comment by gadagashwini** [comment] 2019-05-21 04:37
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-05-21 04:37 UTC
Labels: comp:lite, stat:awaiting response, type:support
