### ISSUE TITLE
API doc typo for tf.nn.avg_pool3d and tf.nn.max_pool3d

### ISSUE THREAD

**Issue by edhlee** [tensorflow/tensorflow#2702] opened 2016-06-07 06:49 UTC
In the tensorflow API doc: https://www.tensorflow.org/versions/master/api_docs/python/nn.html#max_pool3d, it states:

ksize: A list of ints that has length >= 5. 1-D tensor of length 5. The size of the window for each dimension of the input tensor. Must have ksize[0] = ksize[1] = 1.

ksize[0] = ksize[1] = 1 must be ksize[0] = ksize[4] = 1 for both average and max pooling 3d layers as detailed here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/pooling_ops_3d_test.py#L48

**Comment by girving** [comment] 2016-06-07 17:56
Duplicate of #2573.

**Closed by girving** 2016-06-07 17:56 UTC
