### ISSUE TITLE
Optimizing valid TensorFlow graph yields "graph_def is invalid" ValueError

### ISSUE THREAD

**Issue by qtdaniel** [tensorflow/tensorflow#9914] opened 2017-05-15 14:34 UTC
`tensorflow.python.tools.optimize_for_inference_lib.optimize_for_inference` is producing an invalid graph definition. So far as I can tell this is not user error; optimizing a valid graph definition should produce a valid graph definition, so this appears to be a bug.

The following code demonstrates the problem. You will need the input graph definition [model.txt.gz](https://github.com/tensorflow/tensorflow/files/1001369/model.txt.gz). Running the code loads the graph definition, verifies it is valid (by importing it and printing the number of nodes) then calls `optimize_for_inference`. We then attempt to verify the resulting graph definition but get the error

    ValueError: graph_def is invalid at node u'valid/valid_fed/model/rnn/rnn/while/multi_rnn_cell/cell_0/basic_lstm_cell/basic_lstm_cell_1/concat/axis': More inputs specified ('valid/valid_fed/model/rnn/rnn/while/Switch:1') than the op expects..

The error originates from

    tensorflow/python/framework/importer.py, line 362, in import_graph_def

The attached model definition has been manually altered to reduce the size of the (frozen) parameters but the same error occurs with the unmodified original. Attempts to reproduce this problem with a simpler graph failed. Simpler graphs can be optimized successfully. I don't know what it is about this graph that causes the failure.

    import gzip
    
    import tensorflow as tf
    from google.protobuf import text_format
    from tensorflow.python.tools import optimize_for_inference_lib
    
    
    def verify(graph_def):
        with tf.Graph().as_default():
            tf.import_graph_def(graph_def, name="")
            print(len(tf.get_default_graph().as_graph_def().node))
    
    
    def read_graph_def(path):
        graph_def = tf.GraphDef()
    
        with gzip.open(path, "rb") as input_file:
            text_format.Merge(input_file.read(), graph_def)
    
        return graph_def
    
    
    def optimize(input_graph_def):
        output_graph_def = optimize_for_inference_lib.optimize_for_inference(
            input_graph_def, ["valid/valid_fed/model/input/x"],
            ["valid/valid_fed/model/output/y"], tf.int32.as_datatype_enum)
        return output_graph_def
    
    
    def main():
        input_graph_def = read_graph_def("model.txt.gz")
        verify(input_graph_def)
        output_graph_def = optimize(input_graph_def)
        verify(output_graph_def)
    
    
    if __name__ == "__main__":
        main()

Environment details:

- Linux Ubuntu 14.04
- TensorFlow installed from source
- TensorFlow version: ('v1.1.0-0-g1ec6ed5', '1.1.0')
- Bazel version: 0.4.5
- No GPU

**Comment by concretevitamin** [comment] 2017-05-15 15:59
The team has recently released a tool called `graph_transforms`, which contains (possibly more complete?) similar functionalities that optimize for various deployment use cases: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms

Can you take a look at this newer tool to see if it works?

**Comment by qtdaniel** [comment] 2017-05-16 13:20
Thanks @concretevitamin, that worked great. The only quibble I have is that the `TransformGraph` tool is not included in the TensorFlow pip package so I had to add it to the `PYTHONPATH`. Do you know if `optimize_for_inference_lib` is to be removed from the pip package and if `TransformGraph` is to be added to the pip package?

**Comment by concretevitamin** [comment] 2017-05-16 15:19
Great to know it works!  Adding @petewarden to answer these questions.

**Comment by petewarden** [comment] 2017-06-16 20:53
I'm hoping transform_graph will be added by default to pip in #9778. Since that looks like the only remaining issue, closing as a duplicate of that one. Let me know if I've missed something!

**Closed by petewarden** 2017-06-16 20:53 UTC
