### ISSUE TITLE
einsum for SparseTensor

### ISSUE THREAD

**Issue by curiarteb** [tensorflow/tensorflow#43512] opened 2020-09-23 23:40 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Multiply two tensors that are not necessarily sparse matrices (2D tensors). For example, a 'tf.einsum' like function available for  sparse tensors. Converting sparse tensors to dense tensors must be avoided.

An example: Multiply A and B where A is a 2D dense tensor and B is a 3D sparse tensor as follows: C[i,j] = \sum_k A[i,k] B[i,k,j]
```
# Example
# inputs
A = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], tf.float32)
B = tf.sparse.SparseTensor(values=tf.constant([1,1,1,1,2,1,1,1,1,1,-1], tf.float32),indices=[[0,0,1],[0,1,2],[0,2,0],[1,0,0],[1,1,1],[1,1,2],[1,2,2],[2,0,2],[2,1,1],[2,2,1],[2,2,2]], dense_shape=[3,3,3])


# output
C = tf.constant([[3, 1, 2],
                 [4, 10, 11],
                 [9, 8, -1]], tf.float32)
```

**Will this change the current api? How?**
A 'tf.sparse.einsum(A,B,'...', a_sparse = False, b_sparse = True)' kind of function would be very useful for dealing with this kind of operations. 

**Who will benefit with this feature?**
Developers that need to deal with sparse tensor multiplications in high dimensions (grater than 2D sparse tensors)

**Any Other info.**

**Comment by Saduf2019** [comment] 2020-09-24 04:52
@curiarteb 
Please confirm if this is a duplicate of #43497, if yes please close this as it is tracked at #43497.

**Comment by curiarteb** [comment] 2020-09-24 09:02
Yes. This is a duplicate of #43497. Ok. I will close this one and maintain the #43497 issue.

**Comment by Saduf2019** [comment] 2020-09-24 09:13
Moving this to closed status with confirmation.

**Closed by Saduf2019** 2020-09-24 09:13 UTC
Labels: stat:awaiting response, type:feature
