### ISSUE TITLE
tf.variable_scope(auxiliary_name_scope=False) alters name_scope

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#18781] opened 2018-04-22 20:00 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: 1.8.0.dev20180329
- **Python version**: 3.6.5

### Describe the problem
Expected behavior for the following code is to print two lines containing:
```
(<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_1/const:0' shape=() dtype=float32>)
(<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_2/const:0' shape=() dtype=float32>)
```
What is actually printed:
```
(<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_1/const:0' shape=() dtype=float32>)
(<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_1/const_1:0' shape=() dtype=float32>)
```
Somehow the first use of `with VSO:` memorizes the `name_scope` it is in and restores it the second time it is used even though `auxiliary_name_scope=False` is set and the documentation states: 
```
auxiliary_name_scope: If True, we create an auxiliary name scope with the scope. If False, we don't touch name scope.
```

### Source code
```python
import tensorflow as tf

with tf.Graph().as_default():
  NSO = tf.name_scope('ns_outer').__enter__()

  VSO = tf.variable_scope(
        'vs_outer', auxiliary_name_scope=False, reuse=tf.AUTO_REUSE)

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_1'):
      with VSO:
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_2'):
      with VSO:
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))
```

It works when swapping the `name_scope` `with-block` with the `variable_scope` `with-block`.
```python
import tensorflow as tf

with tf.Graph().as_default():
  NSO = tf.name_scope('ns_outer').__enter__()

  VSO = tf.variable_scope(
        'vs_outer', auxiliary_name_scope=False, reuse=tf.AUTO_REUSE)

  with tf.name_scope(NSO):
    with VSO:
      with tf.name_scope('ns_inner_1'):
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))

  with tf.name_scope(NSO):
    with VSO:
      with tf.name_scope('ns_inner_2'):
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))
```

**Comment by tensorflowbutler** [comment] 2018-04-23 06:34
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by facaiy** [comment] 2018-04-24 13:54
Thank you for reporting the bug. I'm the author of `auxiliary_name_scope`. 
Could you delete `reuse=tf.AUTO_REUSE` and take a test again?  If I remember correctly, we didn't test the case of mixing `reuse` with `auxiliary_name_scope`. 
I'd like to make an investigation later.

**Comment by sleighsoft** [comment] 2018-04-24 16:16
Still the same behavior when running:
```python
with tf.Graph().as_default():
  NSO = tf.name_scope('ns_outer').__enter__()

  VSO = tf.variable_scope('vs_outer', auxiliary_name_scope=False)

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_1'):
      with VSO:
        print((tf.constant(1.0, name='const')))

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_2'):
      with VSO:
        print((tf.constant(1.0, name='const')))

```

**Comment by facaiy** [comment] 2018-04-24 22:39
@sleighsoft Thank you for feedback. Actually `auxiliary_name_scope` is introduced in #14390 to resolve the name scope conflict of `tf.layers` after reentering variable scope, I modify your codes to make it work:

```python
import tensorflow as tf

with tf.Graph().as_default():
  NSO = tf.name_scope('ns_outer').__enter__()

  with tf.variable_scope('vs_outer',
                         auxiliary_name_scope=False,
                         reuse=tf.AUTO_REUSE) as VSO:
    pass

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_1'):
      with tf.variable_scope(VSO, auxiliary_name_scope=False):
        print((tf.constant(1.0, name='const')))

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_2'):
      with tf.variable_scope(VSO, auxiliary_name_scope=False):
        print((tf.constant(1.0, name='const')))

# Tensor("ns_outer/ns_inner_1/const:0", shape=(), dtype=float32)
# Tensor("ns_outer/ns_inner_2/const:0", shape=(), dtype=float32)
```

**Comment by facaiy** [comment] 2018-04-24 22:48
Perhaps we should document that the argument is only used when reentering?

**Comment by lukaszkaiser** [comment] 2018-04-24 22:55
Better docs would be welcome, I think.

**Comment by facaiy** [comment] 2018-04-24 23:13
Sure, I'll submit a fix for document later.

**Comment by sleighsoft** [comment] 2018-04-25 08:59
Why do I have to use `with tf.variable_scope(VSO, auxiliary_name_scope=False):` again?
My point of specifying the `variable_scope` only once is to not specify all the settings again.

**Comment by facaiy** [comment] 2018-04-25 09:54
@sleighsoft Oh, my bad. Perhaps this is what you want? I wish the case could help you.

```python
import tensorflow as tf

with tf.Graph().as_default():
  NSO = tf.name_scope('ns_outer').__enter__()

  with tf.variable_scope('vs_outer',
                         auxiliary_name_scope=False,
                         reuse=tf.AUTO_REUSE) as VSO:
    pass

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_1'):
      with tf.variable_scope(VSO):
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))

  with tf.name_scope(NSO):
    with tf.name_scope('ns_inner_2'):
      with tf.variable_scope(VSO):
        print((tf.get_variable('var', [1]), tf.constant(1.0, name='const')))

# (<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_1/vs_outer/const:0' shape=() dtype=float32>)
# (<tf.Variable 'vs_outer/var:0' shape=(1,) dtype=float32_ref>, <tf.Tensor 'ns_outer/ns_inner_2/vs_outer/const:0' shape=() dtype=float32>)
```

**Comment by facaiy** [comment] 2018-04-25 10:13
@sleighsoft  As explained before, the argument is designed for re-entering case at the first: we can reenter variable_scope and its original name scope clearly:
```python
with tf.variable_scope(s, auxiliary_name_scope=False) as ss:
     with tf.name_scope(ss.original_name_scope) as n:
          # do something
```

However, I think your request sounds reasonable for me: specify the argument only once. However it might introduce complexity. 

@lukaszkaiser what do you think of the request?

**Comment by sleighsoft** [comment] 2018-04-25 15:25
Yes, that is the behavior I expected.

**Comment by lukaszkaiser** [comment] 2018-04-25 16:48
We can only judge how complex this is when someone makes a PR and we can see it. In general, we would prefer to avoid adding much complexity as the scoping code has grown a lot anyway and the issue of specifying a few times instead of once doesn't seem to be that pressing, except if I'm missing something.

**Comment by sleighsoft** [comment] 2018-04-25 16:58
I think for now it is fine to update the documentation of `auxiliary_name_scope` making the intentions clear, like @facaiy suggested. As a side note, I find all the scoping very troublesome. It is too complex and has so many side-effects. But that's just my 5cents.

**Comment by facaiy** [comment] 2018-04-25 23:12
I prefer to update document as well, because scoping codes affects a lot of people and we'd better take care not to introduce unnecessary complexity if we already have a workaround.

**Comment by cy89** [comment] 2018-05-09 18:09
I think the original issue is resolved, and #18948 is tracking the docs update. Closing.

**Closed by cy89** 2018-05-09 18:09 UTC

**Comment by amirmazaheri1990** [comment] 2019-10-29 18:35
Hi,
The document is still pretty much vague:

> auxiliary_name_scope: If True, we create an auxiliary name scope with the scope. If False, we don't create it. Note that the argument is not inherited, and it only takes effect for once when creating. You should only use it for re-entering a premade variable scope.

First of all, what is the meaning of an Auxiliary Name Scope? And what is its relation with reuse?

What does it mean that it takes effect once? like in a for loop on multiple GPUs, should it be True for the whole loop, or False?

**Comment by sleighsoft** [comment] 2019-10-29 20:04
If you can, I would suggest you move on to v2.0 and leave 1.x behind. It is sooo much easier to use.

+ I agree, that wording is "difficult"
