### ISSUE TITLE
Bug in IOU calculation of NMS for GPU

### ISSUE THREAD

**Issue by fferroni** [tensorflow/tensorflow#31541] opened 2019-08-12 13:36 UTC
**System information**
Ubuntu 18.04, Tensorflow r2.0 from pip

**Describe the current behavior**
https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/core/kernels/non_max_suppression_op.cu.cc#L96

**Describe the expected behavior**
```
const float w = fdimf(xx2, xx1);
const float h = fdimf(yy2, yy1);
const float intersection = w * h;
```

**Code to reproduce the issue**
I believe that the calculation of intersection over union in line 96 of the GPU implementation of non-max suppression is incorrect. 

```
boxes = np.array([[0.2, 0.3, 0.4, 0.5], [0.61, 0.71, 0.81, 0.91], [0.6, 0.7, 0.8, 0.9]], dtype=np.float32)
score = np.array([0.2, 0.7, 0.6], dtype=np.float32)
iou_threshold = 0.5
nms_reference_cpu = tf.image.non_max_suppression(
            boxes=boxes,
            scores=score,
            max_output_size=3,
            iou_threshold=0.5,
        )
= [1, 0]
```

it will not work for GPU, but it will work for CPU. If you remove the +1 (not sure why you would want to do that in the first place), they match.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2019-08-13 09:31
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the minimal code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ppwwyyxx** [comment] 2019-08-15 07:54
a duplicate of https://github.com/tensorflow/tensorflow/pull/28745#issuecomment-512949342

**Comment by fferroni** [comment] 2019-08-15 16:25
Thanks @ppwwyyxx you’re right, someone else also noticed. Will close.

**Closed** 2019-08-15 16:24 UTC
Labels: stat:awaiting response
