### ISSUE TITLE
Running FaceNet and MTCNN model simutaneously on 2 cameras

### ISSUE THREAD

**Issue by apoorvopen** [tensorflow/tensorflow#30980] opened 2019-07-24 08:26 UTC
Hello everyone!

I am trying to run the MTCNN and FaceNet model on 2 cameras simultaneously. So, I am not getting any error while doing this but the code don't give me any results.

It just loads both the models and doesn't give me any predictions. Can anyone help me with this? I have created 2 graphs using g=tf.Graph for MTCNN and FaceNet. 

I think this error is coming due to multi-processing with tensorflow as it might trying to load MTCNN input to Facenet graph. *this is my assumption. 

Please let me know if you have any idea about this. Thanks.

**Comment by ravikyram** [comment] 2019-07-25 09:57
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2019-07-31 05:59
Automatically closing due to lack of recent activity.Thanks!

**Closed by ravikyram** 2019-07-31 05:59 UTC
Labels: stat:awaiting response, type:support
