### ISSUE TITLE
[ distribution ] How to use multiple GPU on each replica ?

### ISSUE THREAD

**Issue by ZhuFengdaaa** [tensorflow/tensorflow#2106] opened 2016-04-26 07:22 UTC
The [Code Here](https://github.com/tensorflow/models/blob/master/inception/inception/imagenet_distributed_train.py) shows how to set each replica which has a single tower that uses one GPU. I'm wondering if there is a way changing this code a little bit to make use of multiple GPU on one machine like [that example](https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py). 

The way I currently used for using all GPU on a worker machine is starting the number of workers that equal to the number of GPUs. then the workers can communicate to each other as if they are not on one machine. That is slower than if I can start a woker that control more than one GPU.

**Comment by mrry** [comment] 2016-04-26 14:58
Closing as a duplicate of https://github.com/tensorflow/models/issues/54.

**Closed by mrry** 2016-04-26 14:58 UTC
