### ISSUE TITLE
Converting unsupported operation:Unpack Equal TensorArrayV3

### ISSUE THREAD

**Issue by zyxcambridge** [tensorflow/tensorflow#15872] opened 2018-01-05 08:58 UTC
zhangyixindeMBP:tensorflow-1.5.0-rc0 zhangyixin$ bazel run --config=opt \
>   //tensorflow/contrib/lite/toco:toco -- \
>   --input_file=/Users/zhangyixin/Desktop/ssd_mobilenet_201801051717_face/frozen_inference_graph.pb  \
>   --output_file=/Users/zhangyixin/Desktop/ssd_mobilenet_201801051717_face/frozen_inference_graph.pb-pb-lite.lite \
>   --input_format=TENSORFLOW_GRAPHDEF \
>   --output_format=TFLITE \
>   --inference_type=FLOAT \
>   --input_shape=1,300,300,3 \
>   --input_array=image_tensor \
>   --output_arrays=detection_boxes,detection_scores,detection_classes,num_detections
WARNING: Config values are not defined in any .rc file: opt
INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/toco:toco up-to-date:
  bazel-bin/tensorflow/contrib/lite/toco/toco
INFO: Elapsed time: 0.387s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tensorflow/contrib/lite/toco/toco '--input_file=/Users/zhangyixin/Desktop/ssd_mobilenet_201801051717_face/frozen_inference_graph.pb' '--output_file=/Users/zhangyixin/Desktop/ssd_mobilenet_201801051717_face/frozen_inference_graph.pb-pb-lite.lite' '--input_format=TENSORFLOW_GRAPHDEF' '--output_format=TFLITE' '--inference_type=FLOAT' '--input_shape=1,300,300,3' '--input_array=image_tensor' '--output_arrays=detection_boxes,detection_scores,detection_classes,num_detections'
2018-01-05 16:55:04.603261: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.603851: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayV3
2018-01-05 16:55:04.603888: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.603921: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayScatterV3
2018-01-05 16:55:04.603938: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayV3
2018-01-05 16:55:04.603976: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604002: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604038: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604098: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: LoopCond
2018-01-05 16:55:04.604176: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604219: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604238: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayReadV3
2018-01-05 16:55:04.604379: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Enter
2018-01-05 16:55:04.604437: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayWriteV3
2018-01-05 16:55:04.604600: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Exit
2018-01-05 16:55:04.604620: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArraySizeV3
2018-01-05 16:55:04.604668: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayGatherV3
2018-01-05 16:55:04.604778: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.604868: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.605025: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: LogicalAnd
2018-01-05 16:55:04.621652: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.627529: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.629129: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.630742: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.631634: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.631684: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.632365: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.632426: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.633228: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.633277: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.633915: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.633964: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.634590: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.634647: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.635357: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.635451: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.636153: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.636180: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Equal
2018-01-05 16:55:04.636466: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.636938: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.637261: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.637554: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.637835: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638123: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638385: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638484: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638604: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638691: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638745: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638804: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638861: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.638875: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Equal
2018-01-05 16:55:04.638953: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.639062: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Unpack
2018-01-05 16:55:04.639152: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Unpack
2018-01-05 16:55:04.639201: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Exp
2018-01-05 16:55:04.639216: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Exp
2018-01-05 16:55:04.639407: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.639464: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: StridedSlice
2018-01-05 16:55:04.640078: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayV3
2018-01-05 16:55:04.640109: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayV3
2018-01-05 16:55:04.640130: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: TensorArrayV3

**Comment by tensorflowbutler** [comment] 2018-01-05 19:04
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-24 19:57
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by gi097** [comment] 2018-02-02 10:49
Have you managed to fix this problem?

**Comment by tensorflowbutler** [comment] 2018-02-17 13:30
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-04 13:03
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-19 15:11
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:50
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-02 18:47
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatatodd** [comment] 2018-05-17 01:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatatodd** 2018-05-17 01:00 UTC
Labels: comp:lite, stat:awaiting response

**Comment by kli017** [comment] 2018-10-19 08:00
OS Platform and Distribution：Ubuntu16.04
TensorFlow installed from：pip
TensorFlow version:1.4
Bazel version:0.18.0
CUDA/cuDNN version:8
GPU model and memory: Titan V 11G

I cloned the newest tensorflow from github and run following and get the same error

bazel run -c opt tensorflow/contrib/lite/toco:toco -- \
--input_file=/home/kai/FaceRecognition/detection/model/frozen_inference_graph_face.pb \
--output_file=/home/kai/FaceRecognition/detection/model/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops \
WARNING: Processed legacy workspace file /home/kai/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/toco:toco up-to-date:
  bazel-bin/tensorflow/contrib/lite/toco/toco
INFO: Elapsed time: 0.081s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorflow/contrib/lite/toco/toco '--input_file=/home/kai/FaceRecognition/detection/model/frozen_inference_graph_face.pb' '--output_file=/home/kai/FaceRecognition/detection/model/detect.tflite' '--input_shapes=1,300,300,3' '--input_arrays=normalized_input_image_tensor' '--output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3' '--inference_type=QUANTIZED_UINT8' '--mean_values=128' '--std_values=128' '--change_concat_input_ranges=false' -INFO: Build completed successfully, 1 total action
2018-10-19 15:59:33.289229: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.292711: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.292744: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayScatterV3
2018-10-19 15:59:33.292755: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.292762: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.292767: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292773: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292780: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292786: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: LoopCond
2018-10-19 15:59:33.292796: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292800: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.292804: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292809: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayReadV3
2018-10-19 15:59:33.292824: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.292830: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.292835: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayWriteV3
2018-10-19 15:59:33.292845: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Exit
2018-10-19 15:59:33.292850: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArraySizeV3
2018-10-19 15:59:33.292863: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayGatherV3
2018-10-19 15:59:33.302558: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302588: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302595: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302601: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302606: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302611: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302631: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayScatterV3
2018-10-19 15:59:33.302653: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayScatterV3
2018-10-19 15:59:33.302673: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayScatterV3
2018-10-19 15:59:33.302682: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302688: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302693: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302698: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302702: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302707: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302712: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayV3
2018-10-19 15:59:33.302722: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302728: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302735: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302742: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302748: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302754: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302764: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302775: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: LoopCond
2018-10-19 15:59:33.302791: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302796: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302801: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302807: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayReadV3
2018-10-19 15:59:33.302826: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302833: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302838: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302844: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayReadV3
2018-10-19 15:59:33.302858: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302865: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.302870: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302875: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayReadV3
2018-10-19 15:59:33.302935: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Where
2018-10-19 15:59:33.302953: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.302980: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Where
2018-10-19 15:59:33.303004: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: NonMaxSuppression
2018-10-19 15:59:33.303027: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Where
2018-10-19 15:59:33.303061: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Where
2018-10-19 15:59:33.303084: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: NonMaxSuppression
2018-10-19 15:59:33.303111: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Size
2018-10-19 15:59:33.303336: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.303345: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.303351: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayWriteV3
2018-10-19 15:59:33.303360: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.303365: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.303370: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayWriteV3
2018-10-19 15:59:33.303378: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.303383: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.303388: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayWriteV3
2018-10-19 15:59:33.303395: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Enter
2018-10-19 15:59:33.303401: I tensorflow/contrib/lite/toco/import_tensorflow.cc:190] Unsupported data type in placeholder op: 20
2018-10-19 15:59:33.303405: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayWriteV3
2018-10-19 15:59:33.303418: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Exit
2018-10-19 15:59:33.303424: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Exit
2018-10-19 15:59:33.303428: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Exit
2018-10-19 15:59:33.303432: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: Exit
2018-10-19 15:59:33.303437: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArraySizeV3
2018-10-19 15:59:33.303449: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayGatherV3
2018-10-19 15:59:33.303457: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArraySizeV3
2018-10-19 15:59:33.303469: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayGatherV3
2018-10-19 15:59:33.303475: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArraySizeV3
2018-10-19 15:59:33.303486: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayGatherV3
2018-10-19 15:59:33.303493: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArraySizeV3
2018-10-19 15:59:33.303505: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1109] Converting unsupported operation: TensorArrayGatherV3
2018-10-19 15:59:33.314840: F tensorflow/contrib/lite/toco/tooling_util.cc:886] Check failed: GetOpWithInput(model, input_array.name()) Specified input array "normalized_input_image_tensor" is not consumed by any op in this graph. Is it a typo? To silence this message, pass this flag:  allow_nonexistent_arrays
Aborted (core dumped)
