### ISSUE TITLE
Get HTTP 404 ERROR with all the version when install？

### ISSUE THREAD

**Issue by beastlovezxc** [tensorflow/tensorflow#5134] opened 2016-10-22 09:13 UTC
Hello,when I install tensorflow with the version of OS X python3 gpu, it brings me the error as 

```
"HTTP error 404 while getting https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc1-py3-none-any.whl
  Could not install requirement tensorflow==0.11.0rc1 from https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc1-py3-none-any.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc1-py3-none-any.whl"
```

How to solve it?

**Comment by YusukeSuzuki** [comment] 2016-10-22 09:17
I have same probrem. all TF_BINARY_URL are 404 error.

**Comment by ascenator** [comment] 2016-10-22 12:47
Same problem here. Tried to install TensorFlow 0.11.0RC1 for Linux (Python 2.7) with GPU-Support:

    https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl

Throws HTTP error 404; file not available.

Same for CPU-only version.

**Comment by ascenator** [comment] 2016-10-22 12:48
Could you change the title? This issue not only applies to the OS X download links.

**Comment by asmello** [comment] 2016-10-22 13:41
As a temporary workaround, I'd suggest using the **rc0** release:

Change:

`https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc1-py3-none-any.whl`

To:

`https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py3-none-any.whl`

(same applies for other URLs)

**Comment by beastlovezxc** [comment] 2016-10-22 14:12
@asmello It works,thank you.

**Comment by ascenator** [comment] 2016-10-22 14:14
...but this only supports CUDA 7.5. I already updated to 8.0 when I saw TF supports it now.

However, one can also compile from source or use the nightly wheels from github (scroll down to "Installation":

    https://github.com/tensorflow/tensorflow

**Comment by kernelmode** [comment] 2016-10-22 15:27
I've successfully managed to install 0.11 from the master branch of documentation (see combobox at the upper left corner).
https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip-installation

**Comment by asmello** [comment] 2016-10-22 15:32
@kernelmode That actually installs **rc0**, though.

**Comment by OverFlow7** [comment] 2016-10-22 16:24
It seems the problem has been fixed

**Comment by mohitsharma0690** [comment] 2016-10-22 18:00
I'm getting a protobuf version mismatch with rc0 wheel. 

> Installing collected packages: protobuf, tensorflow
>   Found existing installation: protobuf 3.0.0a2
>     Uninstalling protobuf-3.0.0a2:
>       Successfully uninstalled protobuf-3.0.0a2
>   Found existing installation: tensorflow 0.11.0rc0
>     Uninstalling tensorflow-0.11.0rc0:
>       Successfully uninstalled tensorflow-0.11.0rc0
> Successfully installed protobuf-3.0.0 tensorflow-0.11.0rc1


And then trying to import

```
python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB2\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

This thread https://github.com/tensorflow/tensorflow/issues/11 seems to mention this to be a protobuf version mismatch error but I'm not sure. 

Any workarounds or if I did something wrong?

**Comment by asimshankar** [comment] 2016-10-22 18:29
@beastlovezxc @YusukeSuzuki @ascenator : Based on @OverFlow7 's comment, it seems that this has been resolved and you are able to download the .whl now?

I'm going to close this, but if it hasn't been resolved feel free to reopen and if possible please paste the output of `curl -v -L "${TF_BINARY_URL}" -o /dev/null` as it might help diagnose any issues with fetching (FWIW, I'm unable to reproduce this error now).

@mohitsharma0690 : Your issue seems unrelated to the HTTP 404s. If you're still having trouble, could you file a new issue and detail out the exact steps you followed (and the platform - are you doing this on OS X or Ubuntu?). Thanks.

**Closed by asimshankar** 2016-10-22 18:29 UTC

**Comment by MerDane** [comment] 2016-12-14 06:28
I got the same error here when i tried to install GPU version.
`HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0rc1-cp35-cp35m-win_amd64.whl`
Any solutions ?

**Comment by MerDane** [comment] 2016-12-14 06:38
When i tried to pip install GPU version, it gave me this:
`HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0rc1-cp35-cp35m-win_amd64.whl`
But when i tried the `0rc0` version, it worked, So what's happening
