### ISSUE TITLE
tanh on CPU exceeds range (and is inconsistent)

### ISSUE THREAD

**Issue by CamdenCU** [tensorflow/tensorflow#23054] opened 2018-10-17 21:34 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.1 LTS
- **TensorFlow installed from (source or binary)**: binary (or source)
- **TensorFlow version (use command below)**: ('v1.10.0-0-g656e7a2b34', '1.10.0')
- **Python version**: Python 2.7.15rc1
- **CUDA/cuDNN version**: N/A, CPU problem
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
```
import numpy
import tensorflow
sess = tensorflow.Session()
sess.run(tensorflow.tanh(numpy.arange(8.8,9.0,0.01,dtype=numpy.float32)))
```

### Describe the problem
tanh on float32s can return values outside of the range [-1,1] when run on a CPU, which suggests a bug in its implementation.  This occurs across multiple machines and builds (but does not seem to occur for me when running on a GPU, or when using numpy instead of tensorflow).  On the system specs given above, the commands produce two instances of 1.0000001:
```
>>> sess.run(tensorflow.tanh(numpy.arange(8.8,9.0,0.01,dtype=numpy.float32)))
array([1.        , 1.        , 0.99999994, 1.0000001 , 1.        ,
       0.99999994, 0.9999998 , 0.99999994, 0.9999998 , 1.        ,
       1.0000001 , 0.9999998 , 1.        , 0.99999994, 0.9999998 ,
       0.99999994, 1.        , 1.        , 0.9999998 , 1.        ],
      dtype=float32)
```

Of lesser concern, return values also differ on the same system when specifying overlapping ranges (here 8.8 changed to 8.9 does not match second half of above):
```
>>> sess.run(tensorflow.tanh(numpy.arange(8.9,9.0,0.01,dtype=numpy.float32)))
array([1.        , 0.99999994, 1.        , 0.99999994, 1.0000001 ,
       0.9999998 , 1.        , 1.0000001 , 1.        , 1.        ],
      dtype=float32)
```

**Comment by harshini-gadige** [comment] 2018-10-17 22:48
@drpngx Hi, could you please look into this and confirm if this is a bug ?

**Comment by drpngx** [comment] 2018-10-18 22:47
I tend to think that this is not really bug, however if you call `atanh` then it might break. @rmlarsen or @aselle WDYT?

**Comment by CamdenCU** [comment] 2018-10-19 19:46
My best guess is that the bug lies with the generic_fast_tanh_float implementation in MathFunctionsImpl.h (or something like it).  The polynomial it uses is not appropriate for single precision input.

I don't know why a result is not determined exclusively by its corresponding input.

**Comment by tensorflowbutler** [comment] 2018-11-09 18:51
Nagging Assignees @rmlarsen, @drpngx, @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-24 18:32
Nagging Assignees @rmlarsen, @drpngx, @harshini-gadige: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2021-11-30 17:27
I think this was resolved in TF2.x. I am not able to reproduce the issue with TF2.7. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a4d7ad53e6bdadb6f6683b20f5255988/untitled1118.ipynb) is a gist for reference.

Output
`tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(20,), dtype=float32)`

I am closing this issue as this was resolved. Thanks!

**Closed by jvishnuvardhan** 2021-11-30 17:27 UTC
Labels: type:bug, comp:ops
