### ISSUE TITLE
tf.summary.flush segfaults when writer is not a valid tf.summary.SummaryWriter object

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#40175] opened 2020-06-05 01:22 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0 & v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.summary.flush` doesn't have input validity check to ensure `writer` is a `tf.summary.SummaryWriter`;
give it a ndarray as `writer` would make it segfault.
**Describe the expected behavior**
The function shouldn't segfault and should have a proper input checking.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import numpy as np
tf.summary.flush(writer=np.random.rand(2,2)) # causes segfaults
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2020-06-05 08:30
I am able to replicate this issue, please find [gist here](https://colab.sandbox.google.com/gist/Saduf2019/7c8032ff3f91a11e944dfc953c68909a/untitled217.ipynb) the colab crashes when i runt he code.

**Comment by mihaimaruseac** [comment] 2020-06-15 17:37
This should be expected, after all you are calling functionality which does not exist. That is, this is not really a fault of TF.

**Comment by nfelt** [comment] 2020-06-18 22:24
The `flush()` op has legacy behavior where callers were passing in the raw handle to the resource rather than the SummaryWriter python object:

https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/ops/summary_ops_v2.py;l=964;drc=5a07c487f666d2edecea59ba7e3a215a2a03fe9d

In particular this is used by TPUEstimator here:

https://cs.opensource.google/tensorflow/estimator/+/master:tensorflow_estimator/python/estimator/tpu/tpu_estimator.py;l=522;drc=079a14eb925c3320c87baa0874ec7167e1b23242

So while I'd like to get rid of that undocumented fallback it's a bit hard to do so.  Perhaps instead there is a way we can at least restrict it to actual resource handle tensors (rather than arbitrary objects), although I'm still not sure that would completely avoid segfaults if passing in a resource handle that did not correspond to a summary writer resource.

**Comment by mihaimaruseac** [comment] 2020-06-19 15:50
Oh, then this is something that we need to fix. Didn't know this part of history.

**Comment by saikumarchalla** [comment] 2021-05-25 11:24
@leeyeetonn  I tried to reproduce the issue in TF 2.5 and Nightly, I am getting different error but colab doesnt  crashes when i executed the code. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/a847f0e86a4dd752dc9319110ff5eceb/untitled82.ipynb).Thanks!

**Comment by saikumarchalla** [comment] 2021-06-01 13:55
@leeyeetonn Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2021-06-01 13:55 UTC
Labels: TF 2.1, comp:apis, type:bug

**Comment by mihaimaruseac** [comment] 2021-06-08 20:44
The different error in colab is our fix to this issue. This is working now.

**Comment by DNXie** [comment] 2022-02-16 19:00
@saikumarchalla @mihaimaruseac  I believed the crash is gone and is replaced with an error message. Thank you!
