### ISSUE TITLE
Exit code 132 on TensorFlow import

### ISSUE THREAD

**Issue by JoeBanks13** [tensorflow/tensorflow#18147] opened 2018-03-31 16:58 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux 4.15.8
- **TensorFlow installed from (source or binary)**: Binary  wheel (`pip install tensorflow`)
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: Intel graphics, 4GB RAM
- **Exact command to reproduce**: `import tensorflow`

### Describe the problem
I've installed tensorflow v1.7.0 via PIP and I am having issues working with it. Upon entering a REPL and attempting to `import tensorflow` the REPL silently exits with an exit code of 132. I've run PDB and tried importing it and it appears it is exiting around the `from tensorflow.python import *` section of the tensorflow code. Looking at the PDB output it appears that code is exiting with error code 132 after running `importlib._bootstrap._find_and_load` which is a python internal.

### Source code / logs
PDB output from trying to import tensorflow (around the section that it exits):
```
> <frozen importlib._bootstrap>(191)_get_module_lock()->_ModuleLock('...40427194539368
(Pdb) n
> <frozen importlib._bootstrap>(149)__enter__()
(Pdb) n
--Return--
> <frozen importlib._bootstrap>(149)__enter__()->None
(Pdb) n
> <frozen importlib._bootstrap>(969)_find_and_load()
(Pdb) n
> <frozen importlib._bootstrap>(970)_find_and_load()
(Pdb) n
> <frozen importlib._bootstrap>(971)_find_and_load()
(Pdb) n

```
What I'm trying to run:
```py
$ python3.6
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
$ echo $?
132
```

**Comment by angersson** [comment] 2018-04-02 17:44
I couldn't replicate this on an Ubuntu docker container.

I also couldn't replicate this on an Arch linux docker container, with the same versions as yours:

```bash
$ docker run -it base/archlinux bash
>$ pacman -Syy                                                                                                               
>$ pacman -S python3                                                                                                                                                                                                          
>$ pacman -S python-pip
>$ pip install tensorflow                                                                                                                                                                                                    
>$ python3.6
Python 3.6.4 (default, Jan  5 2018, 02:35:40)                                                                                    
[GCC 7.2.1 20171224] on linux                                                                                                    
Type "help", "copyright", "credits" or "license" for more information.                                                           
>>> import tensorflow as tf
>>>
```

It looks like this might be local, or a GPU-specific issue. Can you replicate this in Docker (ideally nvidia-docker) for us?

**Comment by JoeBanks13** [comment] 2018-04-02 19:45
Started a docker container, ran all the same commands as you and got this as a result
```bash
[root@216b9202260e /]# python3.6
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Illegal instruction (core dumped)
[root@216b9202260e /]# echo $?
132
```

Even inside the docker container I'm receiving the 132 status code.

This was not nvidia docker as I don't have a NVIDIA graphics card (just intel integrated graphics), Not sure if that matters or not though.

**Comment by angersson** [comment] 2018-04-02 20:59
Interesting. This looks to me like either an issue with your computer, or perhaps a problem with integrated graphics (or something else that could be common to other users).

Can you also check if this still happens with different versions of TF, like a build from master HEAD and older versions of the Python package, like 1.6?

**Comment by JoeBanks13** [comment] 2018-04-02 21:10
Tested with 1.6 yesterday with same issue. I can run a build from master HEAD now.

**Comment by JoeBanks13** [comment] 2018-04-04 09:40
Sorry, got side tracked. Just finished the build from source and that seems to me working fine. Not sure why the other packages aren't.

**Comment by angersson** [comment] 2018-04-04 17:32
@gunan Any thoughts on why the pip package would be broken here?

AFAIK, the PyPi packages have some platform-specific build settings, which may mean that you'll have to build from source. Did you try an Ubuntu-targeting container, too?

**Comment by gunan** [comment] 2018-04-04 17:38
we never tested our build on arch linux. It is possible that the combination of core libraries on arch linux is different, and there is a low level conflict.

**Comment by bjmuld** [comment] 2018-04-04 19:12
Im having this issue on Ubuntu  16.04.3....  how might I track down the offending lib?

**Comment by unnir** [comment] 2018-04-11 16:04
the same issue, ubuntu...

**Comment by angersson** [comment] 2018-04-11 20:36
@bjmuld @unnir Can you provide complete replication commands for Docker?

**Comment by tensorflowbutler** [comment] 2018-04-26 18:51
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by bjmuld** [comment] 2018-04-26 22:00
Yes.  Still an issue.  
Ubuntu 16.04 on amd64.  Tensorflow 1.7.0 installed via pip inside a fresh python 3.5 virtualenv.

**Comment by gunan** [comment] 2018-04-26 22:04
Could you reproduce this in a dockerfile and share the file? Since on our systems this seems to work fine, we have no idea how to proceed.

**Comment by bjmuld** [comment] 2018-04-26 22:16
Hmm.  I'm not fluent in docker-ese.  Could perhaps read up, but not immediately.  Python crashes at 'import tensorflow'.  I should add that tensorflow==1.5 installed via pip in a virtualenv is running fine, it seems.

Here's some output from GDB:

```
Thread 1 "python3" received signal SIGILL, Illegal instruction.
0x00007fffdaa586c0 in std::pair<std::__detail::_Node_iterator<std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> >, false, true>, bool> std::_Hashtable<tensorflow::StringPiece, std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> >, std::allocator<std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> > >, std::__detail::_Select1st, std::equal_to<tensorflow::StringPiece>, tensorflow::StringPieceHasher, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_emplace<std::pair<tensorflow::StringPiece, std::function<bool (tensorflow::Variant*)> > >(std::integral_constant<bool, true>, std::pair<tensorflow::StringPiece, std::function<bool (tensorflow::Variant*)> >&&)
    () from /home/$$$$$$$$/working/testvenb/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
```

**Comment by gunan** [comment] 2018-04-26 22:31
Is it possible you are running on an old CPU?
TensorFlow prebuilt packages require your CPU to have AVX instruction set.
What is your CPU make and model?

**Comment by bjmuld** [comment] 2018-04-26 23:00
Yes, that is possible. Here's some cpuinfo (coudn't find 'avx' by grepping /proc/cpuinfo):
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz
stepping        : 5
microcode       : 0x19
```
additionally, this dockerfile produces the error for me:

```
FROM ubuntu

RUN apt update && apt install -y python3 python3-virtualenv virtualenv

RUN bash -c '\
 /usr/bin/virtualenv -p python3 testvenv && \
 source testvenv/bin/activate && \
 pip install tensorflow==1.7 && \
 echo "import tensorflow" > test.py && \
 python test.py'
```

**Comment by bjmuld** [comment] 2018-04-26 23:01
I should add that my first-cut self-compiled TF gave me the same error....

**Comment by gunan** [comment] 2018-04-27 04:14
This CPU definitely does not have AVX instruction set. So that is one issue.
Which command did you use to build TF on your machine?
Also, how did you configure?

**Comment by gunan** [comment] 2018-04-30 16:58
Yes, the CPU is missing the AVX instruction set.
The quickest recommendation I have is to build TF from sources on your machine. You can also install an older version which has more compatible binaries.

**Comment by smy20011** [comment] 2018-05-13 01:07
It also cause I cannot run tensorflow > 1.5 on Paperspace Gradient° 

Command:

paperspace jobs create --container tensorflow/tensorflow:1.8.0-gpu --machineType P4000 --command "python -c 'import tensorflow'"

**Comment by tensorflowbutler** [comment] 2018-05-27 12:36
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by unnir** [comment] 2018-05-27 12:42
@tensorflowbutler sure, just be patient.

**Comment by gunan** [comment] 2018-05-27 19:41
duplicate of #19584

**Closed by gunan** 2018-05-27 19:41 UTC
Labels: stat:awaiting response, type:build/install
