### ISSUE TITLE
Can Tensorflow restore Graph with gradient flows from checkpoint files?

### ISSUE THREAD

**Issue by backyes** [tensorflow/tensorflow#24427] opened 2018-12-18 13:38 UTC
Generally, checkpoint is used for model evaluation or inference, or fault tolerance. However, can checkpoint file be used to restore training processing, that  is, 

- Load checkpoint file, and build forward and backward graph flow based on these checkpoint files.
- We assume that we have no the model graph python code, just only checkpoint files. 

In general, we can restore forward flow immediately with inference engine, even with other  inference engine. But we wish to restore training graph with gradient flow. Does it  works? Is it big project or little   code hacking, or already APIs provided? 

Thanks a lot.

**Comment by backyes** [comment] 2018-12-19 02:06
If it's a reasonable feature request, we would like to engage this mini project. 

- Why we want this feature? 
- We want to easy user developmennt for AI model with GUI, because junior user does not want python programming.  We set several objectives for GUI design. Firstly, we want user can import python written model into graph. Secondly, user can hack imported graph with GUI or design graph from scratch with GUI. There is some research on this， https://arxiv.org/abs/1802.04626，however，we think，we need take advantage of open source community, which has lots of model resource reference design, then we want GUI tool can also take advantage of community model resource, so we need import python code model into graph. To accomplish this objective, we think, checkpoint owns graph arch, and model variables, also we can edit checkpoint graph sometimes with careful designed GUI, then that's useful if tensorflow can restore training procedure from checkpoint without using native tensorflow describe tensorflow graph. Also this feature could help mirgrating training between different training framework. In addition, this can be reachable in theory, we do not know how about code engineering .. 

Wish some comments reply, thanks.

**Comment by msymp** [comment] 2018-12-22 01:30
Hello, you have raised an excellent feature request. Since you want to restore saved checkpoint models but also be able import/integrate arbitrary Python-based model graphs, and then be able to edit them graphically, and you cite the 'Barista' paper as a reference architecture to implement this feature/GUI tool. Please go ahead and _**submit a brief 2-page design document**_ and we shall find it necessitated and get it validated by an appropriate reviewer/owner.

**Comment by backyes** [comment] 2018-12-26 10:12
Thanks for your kind reply. 

We will try to post some native design ASAP, maybe in weeks. We also want to engaged in related development to acquire more details to  implement it since we think the ability to develop tensorflow deeply will help us make the easy AI more reachable. 

This feature could help to make different DL training framework to be unified with ONNX or tensorflow checkpoint graph under the easy DL way.

**Comment by msymp** [comment] 2019-01-08 02:32
The author has confirmed the response, hence this issue is closed.

**Comment by ymodak** [comment] 2019-02-08 22:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-02-08 22:55 UTC
Labels: comp:apis, stat:awaiting response, type:feature
