### ISSUE TITLE
Keras load_model crash for custom layer using tf.gather

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#22062] opened 2018-09-04 18:51 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0-dev20180823
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: Nvidia Quadro 4000
- **Exact command to reproduce**: N/A

### Describe the problem
When having a custom layer using tf.gather, the model could be built successfully and run without problem. I can save that model successfully; however, when loading the model, the error occurs. If no tf.gather custom layer used, there is no problem. Is this a bug or a mis-use?

My codes are:

	def test_lambda_layer():
	  data_input = keras.Input(shape=(1,4,5), dtype=float)
	  mask = [0,1,1,0,1]
	  valid_out_idx = np.nonzero(mask)[0]
	  x = Lambda(lambda t: tf.gather(t, valid_out_idx, axis=-1))(data_input)
	  x = Conv2D(5, 1, use_bias=False, kernel_initializer='ones', trainable=False)(x)
	  model = keras.Model(inputs=data_input, outputs=x)
	  model.summary()

	  data = np.ones((1,1,4,5), dtype=float)
	  print(model.predict(data))

	  model.save('test.h5')

	  new_model = keras.models.load_model('test.h5')
	  new_model.summary()

	  print(new_model.predict(data))

The error message is:

	Traceback (most recent call last):
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in make_tensor_proto
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in <listcomp>
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
		(bytes_or_text,))
	TypeError: Expected binary or unicode string, got {'type': 'ndarray', 'value': [1, 2, 4]}

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "test_keras.py", line 31, in <module>
		main()
	  File "test_keras.py", line 28, in main
		test_lambda_layer()
	  File "test_keras.py", line 16, in test_lambda_layer
		new_model = keras.models.load_model('test.h5')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in load_model
		model = model_from_config(model_config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in model_from_config
		return deserialize(config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
		list(custom_objects.items())))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1302, in from_config
		process_node(layer, node_data)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1260, in process_node
		layer(input_tensors[0], **kwargs)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 770, in __call__
		outputs = self.call(inputs, *args, **kwargs)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\core.py", line 716, in call
		return self.function(inputs, **arguments)
	  File "test_keras.py", line 5, in <lambda>
		x = Lambda(lambda t: tf.gather(t, valid_out_idx, axis=-1))(data_input)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2650, in gather
		return gen_array_ops.gather_v2(params, indices, axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3804, in gather_v2
		"GatherV2", params=params, indices=indices, axis=axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
		raise err
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
		preferred_dtype=default_dtype)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1127, in internal_convert_to_tensor
		ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 228, in _constant_tensor_conversion_function
		return constant(v, dtype=dtype, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 207, in constant
		value, dtype=dtype, shape=shape, verify_shape=verify_shape))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 531, in make_tensor_proto
		"supported type." % (type(values), values))
	TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'type': 'ndarray', 'value': [1, 2, 4]}. Consider casting elements to a supported type.

**Comment by omalleyt12** [comment] 2018-09-04 22:08
Hi @ybsave, the problem is that your Lambda layer is relying on the global variable `valid_out_idx` inside its `lambda`. This is going to prevent you from loading the saved model in a different file anyway, I'd recommend hardcoding `valid_out_idx` like below or passing it in as another Input to your Model.

This works for me:

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Lambda, Conv2D

def test_lambda_layer():
  data_input = keras.Input(shape=(1,4,5), dtype=float)
  mask = [0,1,1,0,1]
  valid_out_idx = np.nonzero(mask)[0]
  # hardcode valid_out_idx
  x = Lambda(lambda t: tf.gather(t, np.nonzero([0,1,1,0,1])[0], axis=-1))(data_input)
  x = Conv2D(5, 1, use_bias=False, kernel_initializer='ones', trainable=False)(x)
  model = keras.Model(inputs=data_input, outputs=x)
  model.summary()

  data = np.ones((1,1,4,5), dtype=float)
  print(model.predict(data))

  model.save('test.h5')

  new_model = keras.models.load_model('test.h5')
  new_model.summary()

  print(new_model.predict(data))
```

**Comment by ybsave** [comment] 2018-09-04 22:33
@omalleyt12 Thank you for your response. Actually, I have many such "mask" variables in my network, which are online calculated; these cannot be known before nor passed as inputs. Could there be any way of doing this? Thank you.

**Comment by omalleyt12** [comment] 2018-09-05 17:55
@ybsave without knowing too much about your problem, my recommendation would be:

1) If it never changes, hard code it
2) If it's known when the batch starts, pass it in as an Input
3) If it's calculated during a batch run, calculate it using a Lambda layer or custom Layer

Hope that helps! Going to close this out as this is intended behavior

**Closed by omalleyt12** 2018-09-05 17:55 UTC

**Comment by allenlavoie** [comment] 2018-09-05 20:43
@ybsave I think the idea of 3 is that you could subclass `Layer` and pass the NumPy array to its constructor. You may then have to define `get_config` and `from_config`, but that's one path to getting everything serialized. The NumPy array would live with the `Layer` subclass.

We are hoping to serialize/deserialize `Model`s as TensorFlow graphs soon, which should work around function bytecode issues.

It does kinda seem like `Lambda` layers could capture in this case, but since the captured reference is to a mutable Python object getting the sematics exactly right seems super tricky.

**Comment by ybsave** [comment] 2018-09-05 22:53
@allenlavoie Thank you for your explanation. I tried to use a custom layer to perform the tf.gather; however, the load_model still crashed. My codes are

	class IndexLayer(Layer):
	  def __init__(self, valid_idx, **kwargs):
		self.valid_idx = valid_idx
		super(IndexLayer, self).__init__(trainable=False, **kwargs)

	  def build(self, input_shape):
		super(IndexLayer, self).build(input_shape)

	  def call(self, inputs):
		return tf.gather(inputs, self.valid_idx, axis=-1)

	  def get_config(self):
		base_config = super(IndexLayer, self).get_config()
		base_config['valid_idx'] = self.valid_idx

	  def from_config(cls, config):
		return cls(**config)

	def test_lambda_layer():
	  data_input = keras.Input(shape=(1,4,5), dtype=float)
	  mask = [0,1,1,0,1]
	  valid_out_idx = np.nonzero(mask)[0]
	  #x = Lambda(lambda t: tf.gather(t, np.nonzero(mask)[0], axis=-1))(data_input)
	  x = IndexLayer(valid_out_idx)(data_input)
	  x = Conv2D(5, 1, use_bias=False, kernel_initializer='ones',
				 trainable=False)(x)
	  model = keras.Model(inputs=data_input, outputs=x)
	  model.summary()

	  data = np.ones((1,1,4,5), dtype=float)
	  print(model.predict(data))

	  model.save('test.h5')

	  new_model = keras.models.load_model('test.h5')
	  new_model.summary()

	  print(new_model.predict(data))

and the error messages are

	  File "test_keras.py", line 332, in <module>
		main()
	  File "test_keras.py", line 329, in main
		test_lambda_layer()
	  File "test_keras.py", line 317, in test_lambda_layer
		new_model = keras.models.load_model('test.h5')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in load_model
		model = model_from_config(model_config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in model_from_config
		return deserialize(config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
		list(custom_objects.items())))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1292, in from_config
		process_layer(layer_data)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1278, in process_layer
		layer = deserialize_layer(layer_data, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 163, in deserialize_keras_object
		raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
	ValueError: Unknown layer: IndexLayer

Did I miss something or incorrectly implement something?

Btw: do you mean that my original codes would be supported in future Tensorflow versions? Will the numpy data be serialized/deserialized in the future? Actually, I am quite confused in @omalleyt12 's original response; I do not understand why hard coded the values is OK but using a constant like variable is not. 

Thanks.

**Comment by allenlavoie** [comment] 2018-09-06 16:18
Neat. I think you just need to set the [`custom_objects` argument to load_model](https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model).

**Comment by allenlavoie** [comment] 2018-09-06 16:27
And `from_config` [should have the `@staticmethod` decorator](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/python/keras/engine/base_layer.py#L1538). In this case you can just take it out and use the base class method.

**Comment by ybsave** [comment] 2018-09-06 16:50
@allenlavoie Thank you for your quick response. I tested several combinations, and still cannot find anyone to work. 

If I remove the definition of "from_config" function and define the custom layer as

	class IndexLayer(Layer):
	  def __init__(self, valid_idx, **kwargs):
		self.valid_idx = valid_idx
		super(IndexLayer, self).__init__(**kwargs)

	  def build(self, input_shape):
		super(IndexLayer, self).build(input_shape)

	  def call(self, inputs):
		return tf.gather(inputs, self.valid_idx, axis=-1)

	  def get_config(self):
		base_config = super(IndexLayer, self).get_config()
		base_config['valid_idx'] = self.valid_idx
		return base_config

	def test_lambda_layer():
	  data_input = keras.Input(shape=(1,4,5), dtype=float)
	  mask = [0,1,1,0,1]
	  x = IndexLayer(np.nonzero(mask)[0])(data_input)
	  x = Conv2D(5, 1, use_bias=False, kernel_initializer='ones',
				 trainable=False)(x)
	  model = keras.Model(inputs=data_input, outputs=x)
	  model.summary()

	  data = np.ones((1,1,4,5), dtype=float)
	  print(model.predict(data))

	  model.save('test.h5')
	#  model.save_weights('./weights')

	  new_model = keras.models.load_model('test.h5', custom_objects={'IndexLayer':IndexLayer})
	#  new_model = keras.Model(inputs=data_input, outputs=x)
	#  new_model.load_weights('./weights')
	  new_model.summary()

	  print(new_model.predict(data))

The error message is

	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in make_tensor_proto
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 527, in <listcomp>
		str_values = [compat.as_bytes(x) for x in proto_values]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
		(bytes_or_text,))
	TypeError: Expected binary or unicode string, got {'type': 'ndarray', 'value': [1, 2, 4]}

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "test_keras.py", line 341, in <module>
		main()
	  File "test_keras.py", line 338, in main
		test_lambda_layer()
	  File "test_keras.py", line 324, in test_lambda_layer
		custom_objects={'IndexLayer':IndexLayer})
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in load_model
		model = model_from_config(model_config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in model_from_config
		return deserialize(config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
		list(custom_objects.items())))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1302, in from_config
		process_node(layer, node_data)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1260, in process_node
		layer(input_tensors[0], **kwargs)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 770, in __call__
		outputs = self.call(inputs, *args, **kwargs)
	  File "test_keras.py", line 284, in call
		return tf.gather(inputs, self.valid_idx, axis=-1)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2650, in gather
		return gen_array_ops.gather_v2(params, indices, axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3804, in gather_v2
		"GatherV2", params=params, indices=indices, axis=axis, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
		raise err
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
		preferred_dtype=default_dtype)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1127, in internal_convert_to_tensor
		ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 228, in _constant_tensor_conversion_function
		return constant(v, dtype=dtype, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 207, in constant
		value, dtype=dtype, shape=shape, verify_shape=verify_shape))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 531, in make_tensor_proto
		"supported type." % (type(values), values))
	TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'type': 'ndarray', 'value': [1, 2, 4]}. Consider casting elements to a supported type.

If I add "@staticmethod" and defined the "from_config" function, as

    @staticmethod
    def from_config(cls, config):
      return cls(**config)

the error message is

	Traceback (most recent call last):
	  File "test_keras.py", line 343, in <module>
		main()
	  File "test_keras.py", line 340, in main
		test_lambda_layer()
	  File "test_keras.py", line 326, in test_lambda_layer
		custom_objects={'IndexLayer':IndexLayer})
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 230, in load_model
		model = model_from_config(model_config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 310, in model_from_config
		return deserialize(config, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 173, in deserialize_keras_object
		list(custom_objects.items())))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1292, in from_config
		process_layer(layer_data)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1278, in process_layer
		layer = deserialize_layer(layer_data, custom_objects=custom_objects)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 64, in deserialize
		printable_module_name='layer')
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 175, in deserialize_keras_object
		return cls.from_config(config['config'])
	TypeError: from_config() missing 1 required positional argument: 'config'

If I add "@classmethod" and defined the "from_config" function, the error would be the same as not defining "from_config". 

As shown in my codes, I also tested to use "save_weights" and "load_weights". Those would work successfully. However, the "load_model" always crashed. :(

**Comment by allenlavoie** [comment] 2018-09-11 19:58
I see, probably fixed by https://github.com/tensorflow/tensorflow/pull/21005

**Comment by ybsave** [comment] 2018-09-11 20:07
Thank you for the reference, @allenlavoie. It seems that I have to wait until they fixed the numpy array serialization.

**Comment by 7wdeepin** [comment] 2019-04-04 13:35
@ybsave I met the same problem as you, how did you solve it ?

**Comment by ybsave** [comment] 2019-04-04 17:00
@7wdeepin No solution yet. Not sure whether Google people have make tensorflow support the serialization of numpy.

**Comment by 7wdeepin** [comment] 2019-04-04 22:51
@ybsave  Thank you for the response.
