### ISSUE TITLE
Converting Tensor to Numpy array extremely slow in TF 2.0

### ISSUE THREAD

**Issue by markste-in** [tensorflow/tensorflow#27692] opened 2019-04-09 18:15 UTC
**Current Issue / Bug Report**
I tried to convert a list of tensors to a numpy array.
This was no issue in Tensorflow 1.13.x but is now orders of magnitudes slower in Tensorflow 2.0.0-dev20190405

I linked a piece of code to reproduce the issue in Colab (no HW acceleration required) and to also show the difference in execution time between 1.13.x and 2.0.0/nightly

I tested the issue with 
np.array(LIST_OF_TENSORS)
np.shape(LIST_OF_TENSORS)

**System information**
Colab w.o. HW acceleration and TF 2.0.0-dev20190405

**Code to reproduce the issue**
[Code Example](https://github.com/markste-in/colab/blob/master/bug_tensor_numpy.ipynb
)
.

**Comment by alextp** [comment] 2019-04-18 21:43
Wow, this is really bad. Thanks for bringing it up!

**Comment by alextp** [comment] 2019-04-18 21:51
The underlying issue, after running your repro through a profiler, seems to be that Tensor's array conversion is done through slicing instead of the fastpath.

**Comment by alextp** [comment] 2019-04-18 21:54
Interestingly, if you do np.array(tensor) there's no slowdown, it's only if you do np.array(list_of_tensors).

**Comment by alextp** [comment] 2019-04-18 21:56
@superbobry do you have any idea why converting a tensor to an ndarray goes through __array__ and is fast while converting a list of tensors goes through __iter__ and is slow?

**Comment by superbobry** [comment] 2019-04-20 08:24
Not sure, will have a look at [`PyArray_FromAny`](https://github.com/numpy/numpy/blob/15b092f5541e80d7c3d0108957406c6f8686aba0/numpy/core/src/multiarray/ctors.c#L1793).

Also, here's a smaller reproducer:

```python
t = tf.random.uniform([256])
%timeit np.array(t)
%timeit np.array([t])
100000 loops, best of 3: 5.21 µs per loop
10 loops, best of 3: 22.1 ms per loop
```

**Comment by superbobry** [comment] 2019-04-23 10:05
I'll see if it's easy to generalize `setArrayFromSequence` to arbitrarily nested sequence of array-like objects. 

In the meantime, I wonder if there is a way to detect `np.array([t, t, t...])` calls and error or emit or warning?

**Comment by superbobry** [comment] 2019-04-23 17:51
There seem to be two distinct issues: 

1. `PyArray_FromAny` copies its argument to a list when it does not implement `__array_interface__`, that is exactly numpy/numpy#8562 and it does affect `Tensor` which only implements `__array__`.
2. `setArrayFromSequence` ignores `__array_*__` and `__array__` and copies its argument (again!) unless it's an array (or an array subtype).

I have sketched a fix for both issues. Will post an update once I do more testing.

**Comment by rsmbyk** [comment] 2019-04-25 10:36
You can wrap each item in the list with `np.array()` first then wrap the whole list once again with `np.array()`. I know it does not looks good, but at least it is works for now.

**Comment by superbobry** [comment] 2019-05-26 20:21
The TF side of the fix has been merged. Closing the issue as the remaining part is on the NumPy side.

**Closed by superbobry** 2019-05-26 20:21 UTC
Labels: 2.0, comp:ops, type:bug/performance
