### ISSUE TITLE
How the Frozen model from tensorflow audio recognition is made and converted to tensorflow lite model?

### ISSUE THREAD

**Issue by vihari1729** [tensorflow/tensorflow#36855] opened 2020-02-18 11:31 UTC
After following the steps train.py and freeze.py from the [tutorial](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md) ,the structure of my frozen model looks like(https://imgur.com/a/JtNVkHw) which is different from the official frozen model conv_actions_frozen.pb(https://imgur.com/a/KJXExbV).

When I Converted Frozen model to Tensorflow lite using the steps:

```
import tensorflow as tf
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("./my_frozen_graph.pb", input_arrays=['decoded_sample_data', 'decoded_sample_data:1'], output_arrays=['labels_softmax'])
converter.allow_custom_ops=True
tflite_model = converter.convert()
open("output.tflite", "wb").write(tflite_model)
```

The structure of my tflite model (https://imgur.com/a/uceoHlo) is also different from the original speech commands tflite model(https://imgur.com/a/lWmxl9d). Also, When i am testing my tflite model on android studio, it is getting crashed.

I suspect something went wrong in the creation of frozen model from the [tutorial](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md). Could someone kindly help in generating the frozen model for speech commands.

Tensorflow version-2.1.0

python version - 3.7.3

**Comment by vihari1729** [comment] 2020-02-19 07:29
@petewarden Kindly go through the question once

**Comment by jvishnuvardhan** [comment] 2020-03-05 23:00
@vihari1729 Can you please provide a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-15 02:54
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-03-15 02:54 UTC
Labels: TF 2.1, comp:lite, stat:awaiting response, type:support
