### ISSUE TITLE
Keras does not verify supports_masking

### ISSUE THREAD

**Issue by asadovsky** [tensorflow/tensorflow#33260] opened 2019-10-11 18:41 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS X Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): "pip install"
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I add an Embedding layer with mask_zero=True. Then I add another layer, either Flatten or GlobalAvgPool1D or GlobalMaxPool1D.
Of these, only GlobalAvgPool1D supports masking.
But when I compile and fit the model, no error is raised. (I believe in the past, prior to TF 2.0, an error would be raised.)

**Describe the expected behavior**
An error should be raised when using a layer that doesn't support masking on top of a layer that performs masking.

**Code to reproduce the issue**
Code for repro: https://github.com/asadovsky/nn/blob/master/text_classification.py
When setting "arch" to "max_pool" or "flatten", the train_and_evaluate_model(hp) function should raise an error. But instead, no error is raised.

**Comment by oanush** [comment] 2019-10-14 06:28
Issue replicating for TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/fdff16a8b1f2ec966689f4f96d543e16/untitled13.ipynb) of colab.Thanks!

**Comment by rmothukuru** [comment] 2019-10-14 10:14
Could reproduce the issue, i.e., No error is being raised  when  `"arch" is set to "max_pool" or "flatten"`, with Tensorflow Version 2.0. However, in 1.14, the error, 
`TypeError: Layer global_max_pooling1d does not support masking, but was passed an input_mask: Tensor("embedding/NotEqual:0", shape=(?, 4), dtype=bool)`, is being raised.

Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/32656eee59860b48e185c3e550c43eca/33260.ipynb). Thanks!

**Comment by foxik** [comment] 2020-02-17 18:19
This is still true for TF 2.1 Notably the following example
```python
import numpy as np
import tensorflow as tf

m = tf.keras.Sequential([
    tf.keras.layers.Masking(.0),
    tf.keras.layers.GlobalMaxPool1D(),
])
print(m(np.array([[[0.]]], np.float32))._keras_mask)
```
produces `None` on both TF 2.0 and TF 2.1.

Therefore, the model **silently** ignores the mask! Therefore, if it would be used in training, silently the training would be performed on all elements instead of on the non-masked only.

**Comment by foxik** [comment] 2020-02-17 18:20
Also, as mentioned in #28143, TF 2.0.0-alpha0 was raising and error.

**Comment by tanzhenyu** [comment] 2020-02-20 12:32
@omalleyt12 do you remember if we implicitly swallow it?

**Comment by tanzhenyu** [comment] 2020-04-05 01:40
Reading through the code, we did make a change to implicitly mark output mask to be None when `support_masking=False`, whereas we previously errors out. The commit is [here](https://github.com/tensorflow/tensorflow/commit/8c65ee1de5ebcb85485cb0f7e5bc008134a394e7).

I'm not sure what's the reasoning behind it. Re-assigning to author of that commit.

**Comment by foxik** [comment] 2020-06-03 06:01
A gentle bump after two months of inactivity.

**Comment by Saduf2019** [comment] 2020-08-10 18:42
@asadovsky 
I ran the code on tf-nightly and do not face any error, please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/83bff2606555d9dd57c79167ba659f69/untitled355.ipynb) and please confirm if we may move this issue to closed status

**Comment by foxik** [comment] 2020-08-10 19:43
@saduf2019 Not raising an error is actually the problem -- `GlobalMaxPool1D` does not support masking, so when getting masked input it used to (I am sure it did so with TF 2.0.0-alpha0) raise an exception. With the current behaviour, you are not warned when you construct an invalid model.

So the issue is still unchanged from when it was reported.

**Comment by sushreebarsa** [comment] 2021-05-27 17:56
Was able to reproduce this issue in TF 2.6.0-dev20210527 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a360891df008f2fa0f4505cdb2f662b0/untitled20.ipynb)..Thanks !

**Comment by kumariko** [comment] 2021-08-25 09:19
I could reproduce the issue with TF 2.6 .Please, find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/ef50f08c93a93bb07a04fd56c95473f1/untitled20.ipynb#scrollTo=EzGlLQ3Y9a9V).Thanks!

**Comment by tensorflowbutler** [comment] 2021-12-14 23:25
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Closed** 2022-01-11 17:47 UTC
Labels: type:bug, comp:keras, 2.6.0
