### ISSUE TITLE
Enable use of cuDNN RNNs with optimizers other than GradientDescentOptimizer

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#9422] opened 2017-04-24 21:58 UTC
Currently cuDNN-based RNNs in TF are limited to GradientDescentOptimizer ([#6620](https://github.com/tensorflow/tensorflow/issues/6620)). This is a serious limitation given the widespread use of other optimizers. The claim that this cannot be supported in TF because cuDNN RNN don't have known shapes at static time seems overly pessimistic. Just like RNNParamsSaver provides a mechanism to convert between canonical shaped variables and the parameter buffer, a simple wrapper can be provided that does this automatically for cuDNN RNNs, so that the size of the parameter buffer is statically calculated and then used to define the variable, especially since the shape of the parameter buffer is just a 1D vector anyway.

**Comment by girving** [comment] 2017-04-24 22:29
@ebrevdo Can you comment?

**Comment by ebrevdo** [comment] 2017-04-25 18:50
This is a duplicate of #6620.  That said, #6620 is a pretty serious issue.
 zheng-xq can probably say more about whether we can add static shape
information to the parameter objects that cudnn-rnn builds.

**Comment by ebrevdo** [comment] 2017-04-25 18:54
Let's continue discussion in #6620.

**Closed by ebrevdo** 2017-04-25 18:54 UTC
Labels: stat:awaiting tensorflower, type:feature
