### ISSUE TITLE
For loop in "call" function not working with Autograph/tf.range

### ISSUE THREAD

**Issue by adgolden1** [tensorflow/tensorflow#51585] opened 2021-08-20 04:02 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code : Yes
- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.8
- CUDA/cuDNN version: N/A (testing on CPU)
- GPU model and memory: N/A (see above)

I am training a set of models in parallel as part of a more elaborate training procedure so as a result I am trying to implement a call function like the following one:

    class multi_model_test(tf.keras.Model):
        def __init__(self, num_models,width,depth):
            super(multi_model_test, self).__init__()

            self.n_traces = num_models
            self.net_list = []
            for i in range(self.n_traces):
                net = tf.keras.models.Sequential()
                net.add(tf.keras.Input(shape = (1,)))
                for i in range(depth):
                    net.add(tf.keras.layers.Dense(width,activation = 'swish'))
                net.add(tf.keras.layers.Dense(1))
                self.net_list.append(net)

        def call(self,ipts):
            outlist = []
            for i in tf.range(self.n_traces):
                outlist.append(self.net_list[i](ipts))
            out = tf.stack(outlist,-1)
            return out

When I build this as follows:
```
model = multi_model_test(10,50,10)
model.build((None,1))
```
I get the following error:

``ValueError: You cannot build your model by calling `build` if your layers do not support float type inputs. Instead, in order to instantiate and build your model, `call` your model on real tensor data (of the correct dtype).``

This appears to be a bug since the error here clearly does not affect the input, and this model can take float inputs. If I exchange the `tf.range` for simply `range` in the for loop in the call function I don't have an issue but then this doesn't work with Autograph and training takes a very long time.

**Comment by mohantym** [comment] 2021-08-20 15:33
Hi @adgolden1 @sanatmpa1 , I was able to replicate this issue in TF[ 2.2](https://colab.research.google.com/gist/mohantym/204f53b156323fd57010066f61a4ef50/github_51585_2-2.ipynb) ,[ 2.3](https://colab.research.google.com/gist/mohantym/0dedb74f823767975328fab3cf96a2e9/github_51585_2-3.ipynb) ,[2.4 ](https://colab.research.google.com/gist/mohantym/d6b8d58e5c766a45913548e1df2e71f2/github_51585_2-4.ipynb) and TF [2.6](https://colab.research.google.com/gist/mohantym/4b3c942a0c6abe2780452fcb204719d1/github_51585_2-6.ipynb) , issue does not persist when only used only range in call method instead of tf.range

**Comment by adgolden1** [comment] 2021-08-20 15:35
That's true but if only `range` is used then Autograph cannot process the model and I have found that to slow down the training substantially.

**Comment by mdanatg** [comment] 2021-09-08 18:14
@tomerk can probably tell more, but the error message seems wrong.

Looking at the code, using `tf.range` would index a Python list (`self.net_list`) using a Tensor (`i` is a Tensor when the loop is over `tf.range`), which isn't supported. The same happens for appending to outlist, which needs to be a TensorArray; Python lists are not supported in `tf.range` loops at the moment.

Still, while it should be possible to make that example work with `tf.range`, in the end it will probably not give you a speedup, because the model graphs need to be constructed anyway - so instead of having one large graph that contains every model in `self.net_list`, you'd have a while loop with a large body that contains every model in `self.net_list`.

**Comment by gowthamkpr** [comment] 2022-08-25 21:14
@adgolden1 As mentioned [above](https://github.com/tensorflow/tensorflow/issues/51585#issuecomment-915462061) this is an expected behavior. Can you please go ahead and close this issue? Thanks!

**Closed** 2022-09-08 21:50 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:keras, comp:autograph, TF 2.3
