### ISSUE TITLE
configure.gpu_options.per_process_gpu_memory_fraction = 1，case OOM

### ISSUE THREAD

**Issue by PengQi220** [tensorflow/tensorflow#22239] opened 2018-09-12 13:14 UTC
### System information

- **Have I written custom code**: N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.3.1611 (Core), but that does not matter
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.10.1-0-g4dcfddc5d1', '1.10.1')
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: N/A
- **Exact command to reproduce**: docu issue

### Describe the problem

when use the code below to config the tensorflow session, will case an `CUDA_ERROR_OUT_OF_MEMORY` error.

`configure.gpu_options.per_process_gpu_memory_fraction = 1`

```
2018-09-12 20:59:57.154299: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-12 20:59:57.409106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:84:00.0
totalMemory: 22.38GiB freeMemory: 22.21GiB
2018-09-12 20:59:57.409748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-12 20:59:59.004788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-12 20:59:59.005075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-09-12 20:59:59.005126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-09-12 20:59:59.008029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22912 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:84:00.0, compute capability: 6.1)
2018-09-12 20:59:59.015888: E tensorflow/stream_executor/cuda/cuda_driver.cc:903] failed to allocate 22.38G (24025956352 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
```

### Source code 

`cuda_driver.cc`

```
if (per_process_gpu_memory_fraction == 0) {
    allocated_memory = available_memory;
    const int64 min_system_memory = MinSystemMemory(available_memory);
    if (min_system_memory < allocated_memory) {
      allocated_memory -= min_system_memory;
    }
  } else {
    allocated_memory = total_memory * per_process_gpu_memory_fraction;
  }
  *memory_limit = allocated_memory;
```

tensorflow set memory_limit by `total_memory * per_process_gpu_memory_fraction;` , this case the OOM error, I think, may be `free_memory * per_process_gpu_memory_fraction;` is better.

**Comment by tensorflowbutler** [comment] 2018-09-13 00:50
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by PengQi220** [comment] 2018-09-15 06:02
System information has updated.

**Comment by aaroey** [comment] 2018-09-18 18:52
Yes, as @azaks2 mentioned, if you want to use all available, set per_process_gpu_memory_fraction to 0. Using `free_memory * per_process_gpu_memory_fraction` will have unexpected behavior since multiple processes will get different actual number.

**Comment by kasyoukin** [comment] 2018-09-21 12:36
@azaks2 @azaks2 
GTX 1080 has 8116 memory and I set per_process_gpu_memory_fraction=0.5, tensorflow use 4239MB,not the actual 8116/2=4058.
Why?

**Comment by aaroey** [comment] 2018-09-21 14:48
@kasyoukin we use [cuMemGetInfo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_driver.cc#L1439) to get the total memory. Since I don't have that card, would you help to check what `cuMemGetInfo()` returns?

Thanks.

**Comment by kasyoukin** [comment] 2018-09-22 15:07
@aaroey 
total 8510701568
free 7817658368

**Comment by tensorflowbutler** [comment] 2018-10-07 12:37
Nagging Assignees @aaroey, @azaks2: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aaroey** [comment] 2018-10-09 05:59
@kasyoukin may I ask where did you see the `4239MB` number? Is it from the log?

**Comment by kasyoukin** [comment] 2018-10-09 07:10
@aaroey from the nvidia-smi

**Comment by aaroey** [comment] 2018-10-09 14:44
@kasyoukin I see. The 4239MB includes the memory used to initialize CUDA runtime, which is not counted as the 50% per_process_gpu_memory_fraction. per_process_gpu_memory_fraction only includes memory that will be allocated by TF for computational purposes. So I think this is expected, and we don't know how much memory the CUDA runtime is going to take.

**Comment by aaroey** [comment] 2018-10-09 14:44
I'm going to close this issue, feel free to comment if there are any other questions.

**Closed by aaroey** 2018-10-09 14:44 UTC

**Comment by Flamefire** [comment] 2019-05-27 12:32
I run into this issue through a 3rd party lib setting `per_process_gpu_memory_fraction=1` and checked the source: Why is the heuristic determining how much system memory is required not used here? Wouldn't it be better to always reduce the total_memory by the system memory and/or warn/error on `per_process_gpu_memory_fraction>=1`?
