### ISSUE TITLE
seq2seq tutorial example not working for python 3.4

### ISSUE THREAD

**Issue by OlavHN** [tensorflow/tensorflow#1432] opened 2016-03-08 15:02 UTC
### Environment info
Operating System:
Ubuntu 14.04

1. Which pip package you installed.
sudo pip3 install --upgrade /tmp/pip/tensorflow-*.whl

2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.7.1
(Built from commit 263d00d271077 with `TF_UNOFFICIAL_SETTING=1 ./configure` )

### Steps to reproduce
1. Apply https://github.com/tensorflow/tensorflow/commit/cdd0e2b7c542a59322c054aa1a52b2753c1cf69e 
2. Run `python3 ../tensorflow/tensorflow/models/rnn/translate/translate.py --data_dir .`
3. Fail with trying to decode training data as ascii (see log at the end)

### What have you tried?
Modified https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/default/_gfile.py#L63 to `self._fp = open(name, mode, encoding="latin-1")`

This seems to fix this issue for python 3.4.

### Logs or other output that would be helpful
Creating vocabulary ./vocab40000.fr from data ./giga-fren.release2.fr
Traceback (most recent call last):
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 276, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 273, in main
    train()
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 137, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 268, in prepare_wmt_data
    create_vocabulary(fr_vocab_path, train_path + ".fr", fr_vocabulary_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 136, in create_vocabulary
    for line in f:
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_gfile.py", line 176, in __next__
    return next(self._fp)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]

**Comment by girving** [comment] 2016-03-08 17:28
Can you confirm that you're using python 3?  You say `pip3` and `python` above; is just `python` Python 3?  If so, what version?

**Comment by OlavHN** [comment] 2016-03-08 18:59
Sorry for being unclear. The command was left over from the github issue template.

`python3 --version`
Python 3.4.3
`python3 -c "import tensorflow; print(tensorflow.__version__)"`
0.7.1
`python --version`
Python 2.7.6
`python -c "import tensorflow; print(tensorflow.__version__)"`
ImportError: No module named tensorflow

**Comment by girving** [comment] 2016-03-08 19:04
Next question: what exception are you seeing?  It may just be my eyes glazing over, but it looks like the initial comment has a traceback but not the actual exception.

**Comment by OlavHN** [comment] 2016-03-08 20:50
The important line was missing, yes.

`python3 ../../../tensorflow/tensorflow/models/rnn/translate/translate.py --data_dir .`
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Preparing WMT data in .
Extracting tar file ./training-giga-fren.tar
Unpacking ./giga-fren.release2.fr.gz to ./giga-fren.release2.fr
Unpacking ./giga-fren.release2.en.gz to ./giga-fren.release2.en
Downloading http://www.statmt.org/wmt15/dev-v2.tgz to ./dev-v2.tgz
Succesfully downloaded dev-v2.tgz 21393583 bytes
Extracting tgz file ./dev-v2.tgz
Creating vocabulary ./vocab40000.fr from data ./giga-fren.release2.fr
Traceback (most recent call last):
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 276, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 273, in main
    train()
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 137, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 268, in prepare_wmt_data
    create_vocabulary(fr_vocab_path, train_path + ".fr", fr_vocabulary_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 136, in create_vocabulary
    for line in f:
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_gfile.py", line 177, in __next__
    return next(self._fp)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

**Comment by girving** [comment] 2016-03-08 20:53
Does changing `with gfile.GFile(data_path, mode="r") as f:` in `models/rnn/translate/data_utils.py` to have `mode="rb"` fix the problem?  If so, that's a better fix than teaching `gfile.py` about latin.

**Comment by OlavHN** [comment] 2016-03-08 21:12
Line 134 to `with gfile.GFile(data_path, mode="rb") as f:`

together with

Line 140 to `tokens = tokenizer(line.decode('latin1')) if tokenizer else basic_tokenizer(line.decode('latin1'))`

also seems to solve the issue for python 3.

**Comment by girving** [comment] 2016-03-08 21:18
What error do you get if you only make the line 134 change?  The reason I ask is that it should work the same way in Python 2 and Python 3, and Python 2 doesn't automatically use unicode.

**Comment by OlavHN** [comment] 2016-03-08 21:21
`python3 ../../../tensorflow/tensorflow/models/rnn/translate/translate.py --data_dir .`
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Preparing WMT data in .
Creating vocabulary ./vocab40000.fr from data ./giga-fren.release2.fr
Traceback (most recent call last):
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 276, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 273, in main
    train()
  File "../../../tensorflow/tensorflow/models/rnn/translate/translate.py", line 137, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 268, in prepare_wmt_data
    create_vocabulary(fr_vocab_path, train_path + ".fr", fr_vocabulary_size)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 140, in create_vocabulary
    tokens = tokenizer(line) if tokenizer else basic_tokenizer(line)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 109, in basic_tokenizer
    words.extend(re.split(_WORD_SPLIT, space_separated_fragment))
  File "/usr/lib/python3.4/re.py", line 200, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: can't use a string pattern on a bytes-like object

**Comment by girving** [comment] 2016-03-08 21:24
So the right fix for that is to put `b` in front of the regular expression definitions to get `bytes`-compatible regular expressions.  A few more fixes along those lines may be required.

**Comment by girving** [comment] 2016-03-08 21:25
If you want to keep trying to fix it I'm happy to keep helping, but I could also try to find someone to reproduce on our end.

**Comment by OlavHN** [comment] 2016-03-08 22:03
I've posted an initial attempt to https://github.com/tensorflow/tensorflow/pull/1436

I've not tested this on 2.7 and would also need pointers.

**Comment by girving** [comment] 2016-06-06 23:25
I believe this was fixed by #1436.

**Closed by girving** 2016-06-06 23:25 UTC
Labels: bug
