### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/conv.cc:316 input->dims->data[3] != filter->dims->data[3] (4 != 3)Node number 1 (CONV_2D) failed to prepare.

### ISSUE THREAD

**Issue by LINYOUWEI0804** [tensorflow/tensorflow#42249] opened 2020-08-12 05:03 UTC
ubuntu18.04
tf-nightly-gpu : '2.4.0-dev20200811'
numpy  :  1.18.3

I follow the official website to convert the file (https://www.tensorflow.org/lite/performance/post_training_integer_quant)
The first step is to convert .h5 files to tflite files(success!!),but When performing integer quantization This error occurred：

[RuntimeError: tensorflow/lite/kernels/conv.cc:316 input->dims->data[3] != filter->dims->data[3] (4 != 3)Node number 1 (CONV_2D) failed to prepare.]

My model:
[hdf5.zip](https://github.com/tensorflow/tensorflow/files/5060690/hdf5.zip)
[tflite.zip](https://github.com/tensorflow/tensorflow/files/5060695/tflite.zip)

One of my training materials:
[train_img.zip](https://github.com/tensorflow/tensorflow/files/5060699/train_img.zip)

**Comment by ravikyram** [comment] 2020-08-12 07:07
@LINYOUWEI0804 

Request you to share colab link or stand alone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by LINYOUWEI0804** [comment] 2020-08-12 07:24
My training program：
[train.zip](https://github.com/tensorflow/tensorflow/files/5061210/train.zip)

**Comment by jvishnuvardhan** [comment] 2020-08-13 22:23
@LINYOUWEI0804 Looks like there is a mismatch in the data shape. You can check `model.summary` that `input_shape` of image is (1, 224, 224, 3) whereas `xtrain.shape` in `representative_data_gen` is (1, 224, 224, **4**). 

Can you please update the shape of `representative_data_gen` and then convert the model. As error is clearly mentioning there is a mismatch in the shape, i think this will work for you. Thanks!

Please verify once and close the issue if this resolved the issue for you. Thanks!

**Closed** 2020-08-17 02:50 UTC
Labels: TFLiteConverter, comp:lite, stat:awaiting response, type:support

**Comment by giahi** [comment] 2020-08-27 08:39
I am totally new to this environment and faced the same problem
may I know if you could solve your problem?

**Comment by giahi** [comment] 2020-08-27 09:26
tensorflow/lite/kernels/conv.cc:313 input->dims->size != 4 (3 != 4)Node number 1 (CONV_2D) failed to prepare.

the problem is that I dont have conv2D at all

**Comment by jvishnuvardhan** [comment] 2020-08-27 12:53
@giahi Can you please create a new issue with a simple standalone code to reproduce the error? Thanks!

**Comment by LINYOUWEI0804** [comment] 2020-08-31 03:13
My problem is that 3 dimensions are created when building the model, like this 
model = tf.keras.applications.MobileNetV2(include_top=False, weights='imagenet', input_shape=(224 ,224 ,3)), but The data set I provided during the integer quantification is in png format. The 4 dimensions are different from the 3 dimensions of the model.
