### ISSUE TITLE
Feeding Batch of  Images to session.Run() in Golang

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/tensorflow#25440] opened 2019-02-01 23:26 UTC
I have tried all the methods but did not succeed to make a batch processing of images in Go Tensorflow. 

I have been following this test case for the inception model. I tried many things but did not work.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/example_inception_inference_test.go#L199

Could anyone help me? I really appreciate any help.

Error:
```
Endpoint "Placeholder:0" fed more than once.
```

**Comment by ymodak** [comment] 2019-02-04 19:48
@asimshankar  @yongtang  Can you PTAL? Thanks!

**Comment by asimshankar** [comment] 2019-02-05 09:06
@anilknayak : Having all the details asked for in the issue template (in particular, the steps to reproduce the problem) would be a good idea to add. That said, going off of just the error message, it seems that you're trying to feed the same placeholder node multiple times.

Note that a "batch" is generally just a higher dimensional tensor where elements of the batch are stacked. The model in the example you linked to accepts a batch of images, however the tiny graph constructed to normalize an input expects a single image (so given a single JPEG image, it creates a tensor with shape (1, Height, Width, 3) - representing a "batch" of 1 image.  The `ExpandDims` operation is adding the batch dimension: https://github.com/tensorflow/tensorflow/blob/783cdae78c3fdce1de859f974dfdcafdb38d4251/tensorflow/go/example_inception_inference_test.go#L210)

If you want to feed a batch of images, you'd want to construct the tensor of pixels with shape (N, Height, Width, 3) and feed that to the model - in other words, you'd need to replace https://github.com/tensorflow/tensorflow/blob/783cdae78c3fdce1de859f974dfdcafdb38d4251/tensorflow/go/example_inception_inference_test.go#L187 with something that expects a list of images.

Hope that helps.

**Comment by anilknayak** [comment] 2019-02-05 16:43
@asimshankar 
ExpandDims is not for batch size, this says which dimension it will expand the tensor.
```
input = op.Placeholder(s, tf.String) // says input place holder as string type
```

```
 tensor, err := tf.NewTensor(string(bytes)) // tensor from image byte
normalized, err := session.Run(
		map[tf.Output]*tf.Tensor{input: tensor}, // input to tensor
		[]tf.Output{output},
		nil)
	if err != nil {
		return nil, err
	}
```
however I have prepared a Map of ```map[tf.Output]*tf.Tensor{input: tensor}``` with a different scope of input placeholder still did not work and throws me an error
```Endpoint "Placeholder:0" fed more than once.```

I have tried lot of possibility, but I don't know the perfect setting for batch.

**Comment by asimshankar** [comment] 2019-02-07 18:45
> @asimshankar
> ExpandDims is not for batch size, this says which dimension it will expand the tensor.

I didn't quite understand? Why do you say that? :)
As per the [documentation of `ExpandDims`](https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go/op#ExpandDims), it adds an extra dimension to the input Tensor. In `constructGraphToNormalizeImage` it is used to convert a 3D tensor corresponding to a single image (of shape (Height, Width, NumChannels)) to a 4D tensor corresponding to a batch of images (with shape (1, Height, Width, NumChannels)).

That said though, I'm still not sure I understand the problem you're running into. In the code snippet provided above, there seems to be a single tensor being fed in the map (i.e., the feed map provided to `session.Run` has a single (key, value) pair in it). Is that the line that is throwing the error?

Ideally, if you could provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve), we could better understand the problem you're running into.

**Comment by anilknayak** [comment] 2019-02-07 19:03
Below function will prepare a small graph that will be used to convert to tensor. The second method will be used to run that graph
```
func PrepareTensor() (*tf.Session, *tf.Output, *tf.Output) {
	tfScope := op.NewScope()
	input := op.Placeholder(tfScope, tf.String)
	decodeOp := op.DecodeJpeg(tfScope, input,
		op.DecodeJpegChannels(NumColorChannels))
	castFloatOp := op.Cast(tfScope, decodeOp, tf.Float)
	batchScope := op.Const(tfScope.SubScope("make_batch"), BatchSize)
	batchOp := op.ExpandDims(tfScope, castFloatOp, batchScope)
	resizeScope := op.Const(tfScope.SubScope("resize"),
		[]int32{InputHeight, InputWidth})
	resizeOp := op.ResizeBilinear(tfScope, batchOp, resizeScope)
	divScope := op.Const(tfScope.SubScope("scale_div"), ScaleDiv)
	divOp := op.Div(tfScope, resizeOp, divScope)
	subScope := op.Const(tfScope.SubScope("scale_sub"), ScaleSub)
	subOp := op.Sub(tfScope, divOp, subScope)
	mulScope := op.Const(tfScope.SubScope("scale_mul"), ScaleMul)
	output := op.Mul(tfScope, subOp, mulScope)
	graph, err := tfScope.Finalize()
	if err != nil {
		fmt.Errorf("failed to create tensorflow graph: %v", err)
	}
	session, err := tf.NewSession(graph, nil)
	if err != nil {
		fmt.Errorf("failed to create tensorflow session: %v", err)
	}
	fmt.Println("Input tensor", input.Shape())
	fmt.Println("output tensor", output.Shape())
	return session, &input, &output
}
```
Run this method to create a tensor of shape [1,224,224,3] from image (Mat type). This method accepts tensors Image, session, input and outptu tensor prepare in the previous method and runs the model graph.
```
func ConvertImageToTensor(img gocv.Mat, session *tf.Session, input *tf.Output,
	output *tf.Output) (*tf.Tensor, error) {
	bytes, err := gocv.IMEncode(gocv.JPEGFileExt, img)
	if err != nil {
		return nil, err
	}
	// DecodeJpeg uses a scalar String-valued tensor as input.
	tensor, err := tf.NewTensor(string(bytes))
	if err != nil {
		return nil, err
	}
	tensors, err := session.Run(
		map[tf.Output]*tf.Tensor{*input: tensor},
		[]tf.Output{*output},
		nil, /*targets*/
	)
	if err != nil {
		return nil, err
	}
	return tensors[0], nil
}
```
Here after running above two methods I will get a Tensor of shape [1,224,224,3] that can be feed to the MobileNet classifier.

Below is the code to run the MobileNet classifier

```
result, err := classifier.Session.Run(
		map[tf.Output]*tf.Tensor{
			inputTensor.Output(0): tensor,  // tensor is shape [1,224,224,3] as prepared from the above code
		},
		[]tf.Output{
			outputTensor1.Output(0),
			outputTensor2.Output(0),
		},
		nil, /*targets*/
	)
```

**Comment by asimshankar** [comment] 2019-02-08 03:39
From what you've described I'm having a hard time understanding where the error is (is it when running the classifier or normalizing the image?), what this has to do with your original question of batching, what `inputTensor` is etc.

Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) as described in https://stackoverflow.com/help/mcve to make it possible to help.

From the various snippets of code provided, I don't see the obvious place where you'd get the `Endpoint "Placeholder:0" fed more than once.` error.

**Comment by anilknayak** [comment] 2019-02-08 23:32
Sorry for the log code, This would help to analyse what I am trying to do

```
package BatchProcessing

import (
	"fmt"
	"image"
	"testing"

	tf "github.com/tensorflow/tensorflow/tensorflow/go"
	"github.com/tensorflow/tensorflow/tensorflow/go/op"
	"gocv.io/x/gocv"
)

func TestBatch(t *testing.T) {
	// Starts : Graph to convert a image to [1,224,224,3] and normalizes it
	tfScope := op.NewScope()
	input := op.Placeholder(tfScope, tf.String)
	decodeOp := op.DecodeJpeg(tfScope, input, op.DecodeJpegChannels(3))
	castFloatOp := op.Cast(tfScope, decodeOp, tf.Float)
	batchScope := op.Const(tfScope.SubScope("make_batch"), int32(0))
	batchOp := op.ExpandDims(tfScope, castFloatOp, batchScope)
	resizeScope := op.Const(tfScope.SubScope("resize"),
		[]int32{224, 224})
	resizeOp := op.ResizeBilinear(tfScope, batchOp, resizeScope)
	divScope := op.Const(tfScope.SubScope("scale_div"), float32(255))
	divOp := op.Div(tfScope, resizeOp, divScope)
	subScope := op.Const(tfScope.SubScope("scale_sub"), float32(0.5))
	subOp := op.Sub(tfScope, divOp, subScope)
	mulScope := op.Const(tfScope.SubScope("scale_mul"), float32(2.0))
	output := op.Mul(tfScope, subOp, mulScope)
	graph, err := tfScope.Finalize()
	if err != nil {
		fmt.Errorf("failed to create tensorflow graph: %v", err)
	}
	session, err := tf.NewSession(graph, nil)
	if err != nil {
		fmt.Errorf("failed to create tensorflow session: %v", err)
	}
	// Ends : Graph to convert a image to [1,224,224,3] and normalizes it

	// Starts: Reading Images
	var images []gocv.Mat
	for i := 0; i < 4; i++ {
		img := gocv.IMRead("/home/anilnayak/go/src/github.com/omnify-ai/Playground/BatchProcessing/1.jpg", gocv.IMWriteJpegQuality)
		size := image.Pt(224, 224)
		gocv.Resize(img, &img, size, 0 /*fx*/, 0 /*fy*/, gocv.InterpolationCubic)
		images = append(images, img)
	}
	for _, img := range images {
		fmt.Println(img.Rows(), img.Cols())
	}
	// Ends: Reading Images

	// Starts: Converts images to tensor
	var tensor *tf.Tensor
	imgeTensorMap := make(map[tf.Output]*tf.Tensor)
	for _, img := range images {
		bytes, err := gocv.IMEncode(gocv.JPEGFileExt, img)
		if err != nil {
			fmt.Println("Error")
		}
		tensor, err = tf.NewTensor(string(bytes))
		if err != nil {
			fmt.Println("Error")
		}
		imgeTensorMap[input] = tensor
	}
	tensors, err := session.Run(
		imgeTensorMap,
		[]tf.Output{output},
		nil /*targets*/)
	// Ends: Converts images to tensor
	if err != nil {
		fmt.Println("Error")
	}
	fmt.Println(tensors[0].Shape()) // this should be [4,224,224,3] but actual [1,224,224,3]
}

```

**Comment by anilknayak** [comment] 2019-02-09 00:00
Like we feed in Python
```
with sess.as_default():
            (output,prob) = sess.run([output,prob], feed_dict={input: images })
```
Here in ```feed_dict={input: images }``` 
images is the numpy 4D array [<batch>, <height>, <width>, <channels>]
this will give output as [<batch>][output]

**Comment by asimshankar** [comment] 2019-02-09 23:25
That [full program provided above](https://github.com/tensorflow/tensorflow/issues/25440#issuecomment-461982846) helps (though, I'd say it qualifies as a "complete" example, but not "minimal" or "verifiable" :), I'd strongly suggest looking at guidelines in the the [link provided previously](https://stackoverflow.com/help/mcve). Doing so will make it easier for others to help).

With that said, I see the problem and it is the same as [mentioned in the first reply](https://github.com/tensorflow/tensorflow/issues/25440#issuecomment-460562260). Let me attempt to elaborate.

The `imageTensorMap` contains multiple entries (one per image), but all of them refer the same input tensor (`Placeholder:0`). Which you can see by inspecting the keys:

```go
for k, _ := range imageTensorMap {
  fmt.Println(k.OpName, k.Op.Index)
}
```

So, multiple `Tensor`s are being provided for the same node in the graph.

Now going back to the original comment about feeding tensors. What's happening in the [code you posted above](https://github.com/tensorflow/tensorflow/issues/25440#issuecomment-461982846) is that you're trying to feed multiple (`N = len(imageTensorMap)`) 4-D tensors, each with shape `[1, 224, 3]`, instead of a single tensor with shape `[N, 224, 224, 3]`.

The Go API isn't as comprehensive and to make things easier there are a few additions that could be made. However, given the current API, it is *possible* to construct the batched tensor using something like this:

```go
var buf bytes.Buffer
for i, img := range images {
  bytes, err := gocv.IMEncode(gocv.JPEGFileExt, img)
  if err != nil {
    fmt.Println("Error")
  }
  tensor, err = tf.NewTensor(string(bytes))
  if err != nil {
    fmt.Println("Error")
  }
  normalized, err := session.Run(
    map[tf.Output]*Tensor: { input: tensor },
    []tf.Output{output},
    nil)
  if _, err := normalized[0].WriteContentsTo(&buf); err != nil {
    // Handle error
  }
}

batchShape := []int64{len(images), 224, 224, 3}
batch, err := tf.ReadTensor(tf.Float, batchShape, &buf)
if err != nil {
  // Handle error
}

// Now feed "batch" to the model
```

Hope that helps.

**Comment by anilknayak** [comment] 2019-02-11 18:33
@asimshankar Thanks a lot for the help. buffer is working. I will work on op.Pack() in graph. Nice!

**Comment by ymodak** [comment] 2019-02-11 18:43
Closing this issue since its resolved. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-02-11 18:43 UTC
Labels: comp:apis

**Comment by fuchao01** [comment] 2019-02-12 11:05
@anilknayak How to use on op.Pack() in graph？

**Comment by anilknayak** [comment] 2019-02-12 16:25
I am working on it. as soon as I get some information I will share it. Thanks for the question.

**Comment by csenn** [comment] 2019-10-22 23:26
@anilknayak I know this was a while ago, but have you (or anyone else) figured out how to use op.Pack(). I am struggling with this API. Any quick examples or tips would be extremely appreciated!

**Comment by csenn** [comment] 2019-10-23 01:45
This is what I came up with, it seems like there could be a cleaner way, but this seems to work `func makeTensorFromImages(images []image.Image) (*tf.Tensor, error) {

	s := op.NewScope()
	inputMap := make(map[tf.Output]*tf.Tensor)
	inputs := make([]tf.Output, len(images))

	for _, image := range images {
		buf := new(bytes.Buffer)
		err := jpeg.Encode(buf, image, nil)
		if err != nil {
			log.Fatal(err)
		}

		tensor, err := tf.NewTensor(string(buf.Bytes()))
		if err != nil {
			return nil, err
		}

		input := op.Placeholder(s.SubScope("input_jpg"), tf.String)
		decoded := op.DecodeJpeg(s.SubScope("decode_jpg"), input, op.DecodeJpegChannels(3))
		inputs = append(inputs, decoded)
		inputMap[input] = tensor
	}

	output := op.Pack(s, inputs)

	graph, err := s.Finalize()
	if err != nil {
		return nil, err
	}

	// Execute that graph to decode this one image
	session, err := tf.NewSession(graph, nil)
	if err != nil {
		return nil, err
	}
	defer session.Close()

	// DecodeJpeg uses a scalar String-valued tensor as input.
	normalized, err := session.Run(
		inputMap,
		[]tf.Output{output},
		nil)
	if err != nil {
		return nil, err
	}

	return normalized[0], nil
}`

**Comment by anilknayak** [comment] 2019-10-23 12:51
```tensors``` are the images converted to tensor in other code, following is to prepare batch. 
```
var buf bytes.Buffer
	for _, tensor := range tensors {
		if _, err := tensor.WriteContentsTo(&buf); err != nil {
			fmt.Errorf("failed to write tensor to buffer: %v", err)
		}
	}
	batchShape := []int64{int64(len(tensors)), int64(InputHeight),
		int64(InputWidth), int64(NumColorChannels)}
	batch, err := tf.ReadTensor(tf.Float, batchShape, &buf)
	if err != nil {
		fmt.Errorf( "failed to read tensor from buffer: %v", err)
	}
```

**Comment by anilknayak** [comment] 2019-10-23 12:52
convert image to tensor
```
bytes, err := gocv.IMEncode(gocv.JPEGFileExt, img)
	if err != nil {
		err
	}
	// DecodeJpeg uses a scalar String-valued tensor as input.
	tensor, err := tf.NewTensor(string(bytes))
	if err != nil {
		return nil, err
	}
	tensors, err := session.Run(map[tf.Output]*tf.Tensor{*input: tensor},
		[]tf.Output{*output}, nil /*targets*/)
	if err != nil {
		err
	}
```
