### ISSUE TITLE
Keras model.fit not calling Sequence.on_epoch_end()

### ISSUE THREAD

**Issue by bfs15** [tensorflow/tensorflow#35911] opened 2020-01-15 21:07 UTC
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): binary from pip install tensorflow
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.6.7

**Describe the current behavior**
on_epoch_end() from a tf.keras.utils.Sequence is ***not*** called on epoch end while training using model.fit().

**Describe the expected behavior**
on_epoch_end() from a tf.keras.utils.Sequence should be called on epoch end while training using model.fit().

**Code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np


class ZerosFirstEpochOnesAfter(tf.keras.utils.Sequence):
    def __init__(self):
        self.is_epoch_0 = True

    def __len__(self):
        return 2

    def on_epoch_end(self):
        print('on_epoch_end')
        self.is_epoch_0 = False

    def __getitem__(self, item):
        if self.is_epoch_0:
            print("First epoch")
            return np.zeros((16, 1)), np.zeros((16,))
        else:
            return np.ones((16, 1)), np.ones((16,))


if __name__ == '__main__':
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(1, input_dim=1, activation="softmax"))

    model.compile(
        optimizer='Adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    model.fit(ZerosFirstEpochOnesAfter(), epochs=5,)
```

**Other info / logs**

Note that print('on_epoch_end') is not called anywhere and "First epoch" is printed every epoch.

Relevant api docs:
https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence?version=stable

```
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to
  ['...']
Train for 2 steps
Epoch 1/5
First epoch
First epoch
2020-01-15 17:57:31.979489: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2/2 [==============================] - 1s 260ms/step - loss: 15.2492 - accuracy: 0.0000e+00
Epoch 2/5
First epoch
First epoch
2/2 [==============================] - 0s 6ms/step - loss: 15.2492 - accuracy: 0.0000e+00
Epoch 3/5
First epoch
First epoch
2/2 [==============================] - 0s 6ms/step - loss: 15.2492 - accuracy: 0.0000e+00
Epoch 4/5
First epoch
First epoch
2/2 [==============================] - 0s 6ms/step - loss: 15.2492 - accuracy: 0.0000e+00
Epoch 5/5
First epoch
First epoch
2/2 [==============================] - 0s 6ms/step - loss: 15.2492 - accuracy: 0.0000e+00
```

**Comment by amahendrakar** [comment] 2020-01-16 13:16
@bfs15,
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/a1e87e390d7255c123bf0b28a52f70d3/35911.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-16 23:06
@bfs15 You could use `Keras.callbacks`to view on internal states and statistics of the model during training. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ddf725e66122230653747793994e3eaf/35911.ipynb) is a gist on using `callbacks` for checking a status `on_batch_end`. Thanks!

**Comment by bfs15** [comment] 2020-01-17 00:28
Well yes, while Sequence.on_epoch_end doesn't work, Callback.on_epoch_end does.
But as [the docs state Sequence.on_epoch_end should be called automatically just like Callback.on_epoch_end. ](https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence?version=stable#on_epoch_end)

The problem is that the Sequence I'm making needs to shuffle its dataset every epoch (it's actually triplet hard mining). I don't want model metrics and logs, the Sequence object needs to be alerted to shuffle the dataset for the next epoch.

I am quite sure this is a bug, this worked on tf 2.0.

But given that, the workaround I am currently using is creating a Callback whose sole purpose is to call the Sequence.on_epoch_end on its own on_epoch_end.

https://colab.research.google.com/gist/bfs15/fd18263f788a071225c60cedaf126748/35911.ipynb

**Comment by valsworthen** [comment] 2020-01-27 17:08
Just ran into the same issue on TF 2.0.0.

**Comment by w4-jungyeol** [comment] 2020-03-04 08:19
I also have encountered the same issue. Keras model.fit needs at least `steps_per_epoch * epochs` batches without calling on_epoch_end. It sounds not-conformant with the specification.

**Comment by pesapower** [comment] 2020-03-04 10:44
I have the same problem too:

- TensorFlow 2.1.0 (installed with conda)
- Python 3.7.4
- Windows 10

**Comment by omalleyt12** [comment] 2020-03-04 20:50
Thanks for the issue! This is fixed in the latest tf-nightly, please try with `pip install -U tf-nightly`

**Closed by omalleyt12** 2020-03-04 20:50 UTC
Labels: TF 2.1, comp:keras, stat:awaiting tensorflower, type:support

**Comment by travishsu** [comment] 2020-06-19 08:36
Hi,
Is this fixed if I install tensorflow by pip install tensorflow-gpu==2.1.0?
Or can someone point out which snippet of source code is corrected after this is solved?

Thx

**Comment by bfs15** [comment] 2020-06-19 14:09
From what I understand it will always be broken on 2.1.0, if they release a fix it will be on 2.1.x
If you are stuck on 2.1.0 and/or don't want to mess with tf-nightly, the notebook I posted above has a snipped to duct tape this issue using Callbacks.
The important part is the `OnEpochEnd` class and the usage on `OnEpochEnd([seq.on_epoch_end])`, which registers the Sequence on_epoch_end to be called by OnEpochEnd.on_epoch_end.
https://colab.research.google.com/gist/bfs15/fd18263f788a071225c60cedaf126748/35911.ipynb

**Comment by evans-ye** [comment] 2020-06-22 06:36
I've encountered the same issue. During my test OnEpochEnd is not called in Tensorflow 2.0.2. After upgrading to Tensorflow 2.2.0 OnEpochEnd is being called and the issue is solved.

**Comment by Abdullah-sta** [comment] 2020-11-04 11:20
I have some problem when I am trying to run the code. 
model.fit([enc_inp, dec_inp],decoder_final_output,epochs=4)
TypeError: 'NoneType' object is not callable

can anyone help me to this problem?

**Comment by amahendrakar** [comment] 2020-11-22 13:41
> can anyone help me to solve this problem?

@Abdullah-sta,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by SEAhey** [comment] 2021-06-24 08:35
good job
