### ISSUE TITLE
Keras: removing layers with model.layers.pop() doesn't work

### ISSUE THREAD

**Issue by nairouz** [tensorflow/tensorflow#22479] opened 2018-09-24 10:43 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Colab
- **TensorFlow version (use command below)**:  1.10.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: Colab
- **GCC/Compiler version (if compiling from source)**: Colab
- **CUDA/cuDNN version**: Colab
- **GPU model and memory**: Colab
- **Exact command to reproduce**:

### Describe the problem
When we delete a layer with model.layers.pop(), the deleted layer reappears. 

### Source code / logs

    import tensorflow as tf
    import tensorflow.keras as keras
    import tensorflow.keras.backend as K
    from tensorflow.keras.layers import Dense, Input, Layer
    from tensorflow.keras.models import Model
    input_tensor = Input(shape=(10,))
    hidden = Dense(100, activation='relu')(input_tensor)
    out = Dense(10, activation='relu')(hidden)
    model = Model(input_tensor, out)
    model.compile(loss="mse", optimizer=tf.train.AdamOptimizer(learning_rate=0.001))
    model.summary()
    model.layers.pop()
    model.layers.pop()
    model.summary()
    hidden = Dense(120, activation='relu')(model.layers[-1].output)
    out = Dense(5, activation='softmax')(hidden)
    model = Model(input_tensor, out)
    model.summary()

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 100)               1100      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
=================================================================
Total params: 2,110
Trainable params: 2,110
Non-trainable params: 0
```
```
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 100)               1100      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
=================================================================
Total params: 2,110
Trainable params: 2,110
Non-trainable params: 0

```

```
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense (Dense)                (None, 100)               1100      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
_________________________________________________________________
dense_2 (Dense)              (None, 120)               1320      
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 605       
=================================================================
Total params: 4,035
Trainable params: 4,035
Non-trainable params: 0
_________________________________________________________________
```

**Comment by ymodak** [comment] 2018-09-24 17:19
@nairouz  Please refer to a similar [issue](https://github.com/keras-team/keras/issues/8909)
Try assigning a new model for the reduced layers model.

**Comment by nairouz** [comment] 2018-09-24 17:56
@ymodak thank you for the response. I have created a second model as suggested in the similar thread. 
Unfortunately, it is not working. Please note that in [https://github.com/keras-team/keras/issues/8909](url), the user mentioned that `the  model.summary() shows that the layer has been removed`. For me; it is not the case.

Here is the code. Check it out.

```
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.backend as K
import numpy as np
from tensorflow.keras.layers import Dense, Input, Layer
from tensorflow.keras.models import Model

input_tensor = Input(shape=(20,), name="input")
hidden = Dense(100, activation='relu')(input_tensor)
out = Dense(10, activation='relu', name="out")(hidden)

model = Model(inputs=input_tensor, outputs=out)
model.compile(loss="mse", optimizer=tf.train.AdamOptimizer(learning_rate=0.001))

model.summary()
model.layers.pop()
model.summary()

hidden = Dense(120, activation='relu')(model.layers[-1].output)
out = Dense(5, activation='softmax')(hidden)
model2 = Model(input_tensor, out)

model2.summary()
```

**Comment by yanboliang** [comment] 2018-09-26 04:02
@nairouz 
There are two issues in your code:
* You can't use ```model.layers.pop()``` to remove the last layer in the model. In ```tf.keras```, ```model.layers``` will return a shallow copy version of the layers list, so actually you don't remove that layer, just remove the layer in the return value.
* If you want to remove the last dense layer and add your own one, you should use ```hidden = Dense(120, activation='relu')(model.layers[-2].output)```. ```model.layers[-1].output``` means the last layer's output which is the final output, so in your code, you actually didn't remove any layers.

Thanks.

**Comment by ymodak** [comment] 2018-09-26 19:18
Closing this issue since the solution provided by @yanboliang works.

**Closed by ymodak** 2018-09-26 19:18 UTC

**Comment by AthanasiosTsiaras** [comment] 2018-12-11 16:09
Faced the same issue. 
Try popping the last layer after loading the model
vgg16_model = keras.applications.vgg16.VGG16()
vgg16_model.layers.pop()
Then, if you want to create a Sequential one just iterrate over it
model = Sequential()
for layer in vgg16_model.layers:
    model.add(layer)
and then add the other layer(s) that you want
model.add(Dense(3, activation='softmax'))


That should work

**Comment by ironmanciti** [comment] 2018-12-15 08:54
The purpose of model.layers.pop() is to remove the last layer and fine-tune it reserving the already-trained weights. I resolved the problem simply as below.

vgg16_model = keras.applications.vgg16.VGG16()
model = Sequential()
for layer in vgg16_model.layers[:-1]:   # just exclude last layer from copying
    model.add(layer)
for layer in model.layers:        
    layer.trainable = False
model.add(Dense(2, activation='softmax'))

With model.summary(), you can confirm that the last layer of the model has been replaced.

**Comment by MartinThoma** [comment] 2019-01-08 19:45
@ironmanciti  @AthanasiosTsiaras  This solution gives me

```
TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x7f9869a25cc0>
```

**Comment by cmwolverton** [comment] 2019-01-26 00:43
I am pretty sure that the original poster was talking about tf.keras NOT Keras.  Some of the responses apply to Keras NOT tf.keras.  (I am just trying to get this clear for myself, don't be offended by the all caps!)  

I am trying to solve the same issue.  I want to remove the last layer from Inception_V3 in tf.keras.  Then I want to add an additional layer for regression.  I know how to do it in Keras, but not tf.keras.  

If you load Inception_V3 in Keras, it shows about 300 layers.  If you load it in tf.keras and print the layer summary you see something completely different.  
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 256, 256, 1)  0                                            
__________________________________________________________________________________________________
lambda (Lambda)                 (None, 256, 256, 1)  0           input_1[0][0]                    
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 256, 256, 1)  0           input_1[0][0]                    
__________________________________________________________________________________________________
inception_v3 (Model)            (None, 11)           21824747    lambda[0][0]                     
                                                                 lambda_1[0][0]                   
__________________________________________________________________________________________________
predictions (Concatenate)       (None, 11)           0           inception_v3[1][0]               
                                                                 inception_v3[2][0]               
==================================================================================================
Total params: 21,824,747
Trainable params: 21,790,315
Non-trainable params: 34,432

**Comment by cgebbe** [comment] 2019-03-13 14:11
I got a solution by using
`model._layers.pop(0)`
instead of
`model.layers.pop(0)`

**Comment by jamescook106** [comment] 2019-04-26 15:01
Can someone please provide an example of the best way to do this for tf.keras? All I want to do is remove the last layer of a pretrained model

**Comment by ckyleda** [comment] 2019-04-29 16:03
@jamescook106 

The best way is to create a new model that ends before the last layer of that model. Using the Keras functional model.

As far as I'm aware there is **no** method in Keras to delete a specific layer - you need to take apart the entire model and reconstruct it yourself.

**Comment by cmwolverton** [comment] 2019-04-29 18:40
Here is an example of how to remove the last layer of a pretrained model in tf.keras (NOT keras!) and add a new output layer.   This method could be used to change the number of classes for a classification problem, or to change the model to for a regression problem.  The example below changes a 10 class classification model to a 2 output regression model using InceptionV3 in tf.keras.

### Create InceptionV3 model, load pre-trained weights, find layer you want add on to 
nb_classes = 10; # number must match your pre-trained weights
base_model =InceptionV3(include_top=True, weights=weightFile, input_shape=input_shape, classes=nb_classes)
print(base_model.summary()) # find layer in the summary that you want to add new output to

base_output = base_model.layers[311].output # layer number obtained from model summary above

### attach new desired output layer to the base model to create your new model
num_regression_targets = 2 # some point (x, y)
new_output = tf.keras.layers.Dense(activation="sigmoid", units=num_regression_targets)(base_output)
new_model = tf.keras.models.Model(inputs=base_model.inputs, outputs=new_output)
print(new_model.summary())

### Now the new_model is ready to use

**Comment by cmwolverton** [comment] 2019-04-30 02:31
I re-rad my post above, and realize the explanation could be clearer.  Basically, the strategy is to create a new model starting from a base model that is a standard model included in tf.keras for which you have pre-trained weights.   You can find the standard models are included in tf.keras.keras.applications (tensorflow 1.13) here:

https://github.com/keras-team/keras-applications

You create an instance of the base model, then look for the layer which feeds into the final fully connected layer (or other desired layer) by looking at the model summary.  Then you create a new layer which takes as input the desired layer output from the base model.  Finally, you define a new model in tf.keras.model.Models() by defining the inputs and outputs.  Tensorflow will now have a graph of the base model with the new output layer.

**Comment by jamescook106** [comment] 2019-04-30 16:27
Hi, thanks for your response. This makes sense, but from your code it looks like I have to add a new layer. What I want to do is strip the last layer (the softmax layer in my model) and not add a new layer. Is there equivalent way to the old Keras pop method

**Comment by cmwolverton** [comment] 2019-05-01 17:26
Take a look at the model summary of the new model.  The softmax layer is excluded because it is not needed to produce the final output.  So if you compare the base model to the new model, you will see that you have essentially stripped the last layer.

**Comment by RubinXnibu** [comment] 2019-05-30 20:28
@cmwolverton  How does tf.keras know which layers to process?   I see in your solution we are taking the base_output and providing it as input to the new Dense() layer, but the skipped InceptionV3 layers after 311 still exist in the model object, which is where layers 0-310 we are using also exist.   So when model.fit() is running, does the unused layers [311:] still be receiving data and consuming CPU cycles?

**Comment by George1900** [comment] 2019-09-10 21:27
@jamescook106 Did anybody find why pop() does not work with tf.keras() ? I am unable to remove the last layer with .pop() method. My question basically is whether I can rely on the old .pop() method or not. Thanks. G.

**Comment by weiwenying** [comment] 2019-11-25 07:56
```python
try:
  # Colab only
  %tensorflow_version 2.x
except Exception:
    pass
import tensorflow as tf

from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tfkerassurgeon.operations import delete_layer

x = input_image = Input(shape=(224, 224, 3))
x = Conv2D(3, (3, 3), padding="same", activation="relu")(x)
x = Conv2D(3, (3, 3), padding="same", activation="relu")(x)
x = Conv2D(3, (3, 3), padding="same", activation="relu")(x)
predictions = Dense(5, activation='softmax')(x)
model = Model(inputs=input_image, outputs=predictions)

model = delete_layer(model, model.get_layer(model.layers[1].name))
```
Throw an exception：
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-c63b4938f63f> in <module>()
     31 name = model.layers[1].name
     32 name = tf.constant(name)
---> 33 model = delete_layer(model, model.get_layer(name))

5 frames
/tensorflow-2.0.0/python3.6/tensorflow_core/python/framework/ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```

**Comment by ismael-elatifi** [comment] 2020-01-14 18:07
Only thing which worked in my case was :
```python
model._layers.pop()
    new_model = tf.keras.Sequential([
        model,
        Dense(units=nb_classes, activation='softmax', name="new_layer_name")
    ])
    new_model.build((None, height, width, 3))

**Comment by SCF-byter** [comment] 2020-04-09 17:43
for me following code is a nice workaround. It builds another model without the last layer. Thus effectively being .pop()

`reduced_model = Sequential()
for layer in old_model.layers[:-1]:
  old_model.add(layer)`

**Comment by fsan** [comment] 2020-08-02 14:43
Previous replies mention iterating over base model and adding to a new model, which seems ok for VGG16.
For MobileNetV2 it seems to not be possible

when iterating over its layers it will raise an error when reaching an merge.Add layer
<tensorflow.python.keras.layers.merge.Add object at 0x000002BDB32D0F48>

```ValueError: A merge layer should be called on a list of inputs.```

I understood from previous conversation that using model.layers will bring a shallow copy from the model and using model._layers would bring the actual layers.
I observed that as @cgebbe mentioned will indeed remove the layers (at least from summary view)

> 
> I got a solution by using
> `model._layers.pop(0)`
> instead of
> `model.layers.pop(0)`

I didn't found any cons of using this method, but usually using private vars are usually not a safe thing to do if you don't know the details of the implementation. Does anybody found any problem with this method ?
Another question would be how I can properly add the mege.Add object layer to my model if I would try the iteration method.

Thanks!

**Comment by KMint1819** [comment] 2020-09-04 16:52
> Previous replies mention iterating over base model and adding to a new model, which seems ok for VGG16.
> For MobileNetV2 it seems to not be possible
> 
> when iterating over its layers it will raise an error when reaching an merge.Add layer
> <tensorflow.python.keras.layers.merge.Add object at 0x000002BDB32D0F48>
> 
> `ValueError: A merge layer should be called on a list of inputs.`
> 
> I understood from previous conversation that using model.layers will bring a shallow copy from the model and using model._layers would bring the actual layers.
> I observed that as @cgebbe mentioned will indeed remove the layers (at least from summary view)
> 
> > I got a solution by using
> > `model._layers.pop(0)`
> > instead of
> > `model.layers.pop(0)`
> 
> I didn't found any cons of using this method, but usually messing around the private vars is not a safe thing to do if you don't know the details of the implementation. Does anybody found any problem with this method ?
> Another question would be how I can properly add the mege.Add object layer to my model if I would try the iteration method.
> 
> Thanks!

I think that's because the structure of mobilenetV2 isn't "sequential". For the method that you iterate through all the layers, you assume the model structure passes data through layer by layer. This method is available for VGG since VGG is this kind of model. Yet some model structures aren't like this, such as resnet which contains shortcuts for some data. In these kind of cases, including mobilenetV2, you have to use the functional api solution provided by @cmwolverton [here](https://github.com/tensorflow/tensorflow/issues/22479#issuecomment-487695679).

**Comment by CloseChoice** [comment] 2021-11-26 07:29
pop doesn't help anything here, the correct way to do it is:

```
model2 = Model(model.input, model.layers[-2].output)
```
Tested this only for a non-sequential model.
