### ISSUE TITLE
Strange cuda error

### ISSUE THREAD

**Issue by rroderich** [tensorflow/tensorflow#27469] opened 2019-04-03 16:02 UTC
**System information**
-  Ubuntu 16.04
- TensorFlow installed from source
- TensorFlow newest version
- Python version 3.4
- Installed using virtualenv
- Bazel version 1.22.0
- CUDA/cuDNN version 10.0/7
- GPU Tesla K10.G1.8GB

I compiled TensorFlow from source because compute capatibility is only 3.0.
During training I got the strange error below. I guess it is a CUDA problem but I am not sure. Do you have any idea?

**ERROR MESSAGE:**

F tensorflow/stream_executor/cuda/cuda_driver.cc:184] Check failed: is_host_ptr == points_to_host_memory (0 vs. 1)dst pointer is not actually on GPU: 0x4304b80500
Fatal Python error: Aborted

Thread 0x00007f204affd700 (most recent call first):
  File "/usr/lib/python3.4/threading.py", line 290 in wait
  File "/usr/lib/python3.4/queue.py", line 167 in get
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f2050d9f700 (most recent call first):
  File "/usr/lib/python3.4/threading.py", line 290 in wait
  File "/usr/lib/python3.4/queue.py", line 167 in get
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f2088ac5700 (most recent call first):
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1410 in _call_tf_sessionrun
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1322 in _run_fn
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1337 in _do_call
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1331 in _do_run
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1155 in _run
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 932 in run
  File "/opt/lampp/htdocs/venv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1286 in restore
  File "/opt/l2019-04-03 17:13:00.027397: F tensorflow/stream_executor/cuda/cuda_driver.cc:184] Check failed: is_host_ptr == points_to_host_memory (0 vs. 1)dst pointer is not actually on GPU: 0x4304b81100

**Comment by achandraa** [comment] 2019-04-04 10:39
Thank you for reaching out to us. Can you please provide minimum reproducible code snippet to help us proceed further and verify what is going wrong

**Comment by rroderich** [comment] 2019-04-04 11:21
The error occurred during a training run of Google Bert (https://github.com/google-research/bert/run_squad.py). Everything went well on the CPU version of TensorFlow, but after switching to GPU the error appeared.

**Comment by ymodak** [comment] 2019-04-05 19:10
I used google colab with gpu accelerator and the code works successfully. Can you please use google colab and confirm. I am inclined to think it is cuda issue. TF requires minimum cuda compute capability of 3.5 for gpu acceleration.

**Comment by ymodak** [comment] 2019-04-11 00:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-04-11 00:59 UTC
Labels: comp:gpu, stat:awaiting response, type:support

**Comment by carlpe** [comment] 2020-06-04 17:31
Did you ever find the solution for this? 

tensorflow/stream_executor/cuda/cuda_driver.cc:182] Check failed: is_host_ptr == points_to_host_memory (0 vs. 1)dst pointer is not actually on GPU: 0

**Comment by sachinkmohan** [comment] 2021-11-18 15:52
I am having the same problem as well.
