### ISSUE TITLE
NotImplementedError in conv2 when i use in tf.distribute.experimental.CentralStorageStrategy() for multi gpus in tf2

### ISSUE THREAD

**Issue by 14asaf** [tensorflow/tensorflow#36042] opened 2020-01-19 16:57 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from conda install tensorflow.
- TensorFlow version : 2.0.0
- Python version: Python 3.7.6 
- GCC/Compiler version (if compiling from source): gcc version 7.4.0
- CUDA/cuDNN version: CUDA Version 10.1.243
- GPU model and memory: 4 gpus of Tesla V100-SXM2-16Gb

**Describe the current behavior**
I used in `tf.distribute.experimental.CentralStorageStrategy()` for use all the gpus in my computer
 I run the following code and got `NotImplementedError`

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Input

strategy = tf.distribute.experimental.CentralStorageStrategy()
with strategy.scope():
    Xi = np.zeros((2,1,1,396))
    Pi = Input(shape=(1,1,4), name = 'input_layer_preamble')
    Pd = Conv2D(int(Xi.shape[3]//Pi.shape[3]), (1, 1), padding='same', data_format='channels_first', use_bias=False)(Pi)
```
 

**Describe the current behavior**
```python
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2712, in variable_creator_scope
    yield
  File "tf2_nulty_gpus.py", line 9, in <module>
    Pd = Conv2D(int(Xi.shape[3]//Pi.shape[3]), (1, 1), padding='same', data_format='channels_first', use_bias=False)(Pi)
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 817, in __call__
    self._maybe_build(inputs)
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2311, in __setattr__
    if val.trainable:
  File "/home/ubuntu/anaconda3/envs/my_tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 477, in trainable
    raise NotImplementedError
NotImplementedError
```

**Comment by signalprime** [comment] 2020-02-22 17:51
When implementing CentralStorageStrategy, I am also encountering this error.
This is from a docker built today from tensorflow/tensorflow:latest-gpu-py3-jupyter 
```
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    746           # Build layer if applicable (if the `build` method has been
    747           # overridden).
--> 748           self._maybe_build(inputs)
    749           cast_inputs = self._maybe_cast_inputs(inputs)
    750 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2114         # operations.
   2115         with tf_utils.maybe_init_scope(self):
-> 2116           self.build(input_shapes)
   2117       # We must set self.built since user defined build functions are not
   2118       # constrained to set self.built.

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/convolutional.py in build(self, input_shape)
    156         constraint=self.kernel_constraint,
    157         trainable=True,
--> 158         dtype=self.dtype)
    159     if self.use_bias:
    160       self.bias = self.add_weight(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in __setattr__(self, name, value)
   2294       self._maybe_create_attribute('_trainable_weights', [])
   2295       self._maybe_create_attribute('_non_trainable_weights', [])
-> 2296       if val.trainable:
   2297         if any(val is w for w in self._trainable_weights):
   2298           continue

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variables.py in trainable(self)
    478   @property
    479   def trainable(self):
--> 480     raise NotImplementedError
    481 
    482   @property

NotImplementedError: 
```

**Comment by signalprime** [comment] 2020-02-22 18:16
Solution: use tf.distribute.MirroredStrategy() for multiple-GPUs

**Comment by 14asaf** [comment] 2020-02-23 21:12
This solution isn't good, when I used in MirroredStrategy I got this error:

`2020-02-23 20:57:18.371348: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 47520000000 exceeds 10% of system memory.
`

what can I do to fix this error?

**Comment by dinis-rodrigues** [comment] 2020-03-13 19:11
I have the same issue. I can easily use MirroredStrategy, but with CentralStorageStrategy I get the same error:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/dinis/msc-thesis/Code/February/VGG16/vgg16.py", line 27, in vgg16
    activation=activations[0])
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 178, in add
    layer(x)
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 817, in __call__
    self._maybe_build(inputs)
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2311, in __setattr__
    if val.trainable:
  File "/home/dinis/miniconda3/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 477, in trainable
    raise NotImplementedError
NotImplementedError
```

**Comment by nikitamaia** [comment] 2020-08-04 18:00
Hi @14asaf, this was indeed a bug that I believe has now been fixed. If you are still facing problems, please update the thread with reproducible code as I'm not seeing any problems when running the code sample you've provided in TF 2.2 with 2 GPUs.

**Comment by 14asaf** [comment] 2020-08-04 19:59
Thank you for the answer,

Now I use in TF2.2 and I I managed  with the problem of  MirroredStrategy.

I converted the data to float16 and now I have enough memory space in the Ram.

**Comment by nikitamaia** [comment] 2020-08-04 20:19
Closing this issue now since there was a fix. But feel free to reopen if you think it needs further discussion.

**Closed by nikitamaia** 2020-08-04 20:19 UTC
Labels: TF 2.0, comp:dist-strat, stat:awaiting response, type:bug
