### ISSUE TITLE
documentation request: Prebuilt binary build configuration

### ISSUE THREAD

**Issue by nbcsm** [tensorflow/tensorflow#21096] opened 2018-07-24 16:19 UTC
There are many flags/options for tensorflow build, some of them are performance related.
User may want to build a whl from source (with some modifications) , using **exactly the same** build configuration that prebuilt binary used

With previous Jenkins CI server, we can still figure out the build configuration from log of a release-xxxx build job.
But now with the new internal build system, it is not quite clear what build configuration is used for prebuilt binary anymore.
e.g. 
cuda compute capability: default value in configure.py (3.5,7.0) seems not complete.
cpu simd option: one may have to search release note to figure out whether it is still AVX.

It will be great to document the build setting somewhere, or introduce some script to produce prebuilt binary for a release.
Thanks.

**Comment by tensorflowbutler** [comment] 2018-07-25 01:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment] 2018-08-10 23:47
@gunan can you shed any light here, please?
@drpngx was also curious.

**Comment by gunan** [comment] 2018-08-10 23:52
@av8ramit Do we have these options documented?
I think at the moment, in configure you need to just pick the deafult options.
The only non-defaults we may have are CPU optimization levels, which is fixed to avx, and CUDA, which is selected and unselected depending on CPU/GPU builds.

**Comment by av8ramit** [comment] 2018-08-11 00:10
No I don't but that is a good point. I can add this information to the build from sources page if you'd like.

**Comment by tensorflowbutler** [comment] 2018-08-31 08:11
Nagging Assignees @av8ramit, @gunan: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:49
Nagging Assignees @av8ramit, @gunan: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lamberta** [comment] 2018-09-16 20:31
I'm working on an update to this page which has a section for [configuration options](https://github.com/lamberta/docs/blob/install/site/en/install/source.md#configuration-options).

We can add some more after this lands. If this list becomes unwieldy for the doc page, maybe we can just put it in a file in the tensorflow repo and link to it.

**Comment by drpngx** [comment] 2018-09-21 17:05
Thank you @lamberta ! To be precise, I think we're looking for the exact scripts that are used to generate the images, docker etc.

**Comment by nbcsm** [comment] 2018-09-28 12:49
Thanks for the update, @lamberta 

Agree with @drpngx, it would be great to share the exact script which is used to produce the pre-built binary.

E.g. from https://github.com/tensorflow/docs/blob/master/site/en/install/source.md, I still have no idea what CUDA compute capability is used for pre-built binary.

**Comment by gunan** [comment] 2018-09-28 17:20
Except for windows, we bake all supported CUDA Compute Capabilities into our binary.
The reason for windows not having this is a bug in eigen we are waiting a fix on.

Since our strategy is to include all compute capabilities, they have not been documented.

**Comment by lamberta** [comment] 2018-10-03 20:28
Sharing the script sounds like a fine idea, but then this PR is no longer a documentation request :)

**Comment by tensorflowbutler** [comment] 2018-10-18 18:56
Nagging Assignees @av8ramit, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by av8ramit** [comment] 2018-10-31 17:39
Status update: Still working on this.

**Comment by tensorflowbutler** [comment] 2018-11-15 18:57
Nagging Assignees @av8ramit, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-30 18:55
Nagging Assignees @av8ramit, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by av8ramit** [comment] 2019-06-28 21:14
Hey @angersson I'm assigning this over to you. It's possible you may make our build scripts opensource in your work this quarter. Unfortunately, I never got around to this.

We did make the [pip_new.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/pip_new.sh) the standard for building packages so maybe these are some temporary answers.

**Comment by av8ramit** [comment] 2020-01-31 18:43
So all our build scripts are now externally available. Closing this now.
[Presubmit example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/presubmit)

**Closed by av8ramit** 2020-01-31 18:43 UTC
Labels: type:build/install, type:docs
