### ISSUE TITLE
import tensorflow results in segfault.

### ISSUE THREAD

**Issue by kalleknast** [tensorflow/tensorflow#1373] opened 2016-03-03 18:12 UTC
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:
ubuntu 15.10 64-bit
Python 3.4.3+

If installed from binary pip package, provide:
1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
python3 -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.1

### Steps to reproduce
1. import gi
2. from gi.repository import Gtk
3. import tensorflow

### What have you tried?
1. Identified the necessary steps to reproduce the segfault.
2. Importing in opposite order does NOT produce any segfault.
    1. import tensorflow
    2. import gi
    3. from gi.repository import Gtk

### Logs or other output that would be helpful
Segmentation fault (core dumped)

**Comment by vrv** [comment] 2016-03-03 18:21
What version of python3 do you have installed?

**Comment by kalleknast** [comment] 2016-03-03 18:28
I used Python 3.4.3+

**Comment by viksit** [comment] 2016-03-05 22:21
Which version of CUDA are you using?

**Comment by kalleknast** [comment] 2016-03-07 13:39
Nvidia version:
`cat /proc/driver/nvidia/version`

`NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015`
`GCC version:  gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)`

CUDA complier version:
`nvcc -V`

`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2015 NVIDIA Corporation`
`Built on Mon_Feb_16_22:59:02_CST_2015`
`Cuda compilation tools, release 7.0, V7.0.27`

`./deviceQuery`

`./deviceQuery Starting...`
` CUDA Device Query (Runtime API) version (CUDART static linking)`
 `Detected 1 CUDA Capable device(s)`

`Device 0: "Quadro K2200"`
  `CUDA Driver Version / Runtime Version          7.5 / 7.0`
  `CUDA Capability Major/Minor version number:    5.0`
...
`deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.0, NumDevs = 1, Device0 = Quadro K2200`
`Result = PASS`

Gtk version:
`Gtk._version
3.0`

**Comment by viksit** [comment] 2016-04-14 09:10
This happened to me when I configured the system to use CUDA 6.x but had 7.x installed and dylib/symlinks weren't updated correctly.

My suggestion would be to clean out your CUDA/CUDNN installation, and reconfigure in a clean environment.

**Comment by chengdianxuezi** [comment] 2016-04-19 11:01
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Segmentation fault

how to solve this problem????

**Comment by pulkitag** [comment] 2016-04-20 05:42
I have the same issue. I am using python2.7. 

```python
In [1]: import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Segmentation fault (core dumped)
```

**Comment by kalleknast** [comment] 2016-04-20 05:55
It seems that chengdianxuezi and pulkitag suffer a somewhat different problem than I did. In my case, Python only crashed when I had imported Gtk before importing tensorflow. I get the impression that the two previous posters suffer from seg faults that doesn't involve Gtk.

I have not been able to test viksit's suggestion since I currently do not have access to a Nvidia graphics card.

**Comment by minghuam** [comment] 2016-04-20 06:04
Same issue here. Im using python 2.7, cudnn v4, cuda 7.5 on ubuntu 14.04.

**Comment by pulkitag** [comment] 2016-04-22 07:05
I think, I know where the problem is but don't know how to fix it. 
If you run:

```
gdb python
(gdb) run tf.py 
```

where tf.py has
```python
import tensorflow as tf
```

the trace tells that segfault is happening at:  
PyArray_API () from /usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so

So its probably some issue with numpy.

**Comment by pulkitag** [comment] 2016-04-22 18:26
It runs for me now. I basically had to uninstall `six, wheel, numpy, scipy, sckit-image, scikit-learn, protobuf` and then re-install them using `pip`

**Comment by wookayin** [comment] 2016-04-29 21:16
I also have a problem with 0.8.0 nightly (on the other hand, 0.7.1 stable works well) Following @pulkitag, I tried to uninstall the packages and then reinstall them; but segmentation fault still occurs.

When I install numpy (1.11) and tensorflow (0.8.0) only, segfault did not occur. However, just after installing `scikit-learn` (0.17.1), segfault started to occur. I am not sure why this happens, but we might need to inspect this situation as well.

**Comment by pulkitag** [comment] 2016-04-29 21:48
Did you use `pip --upgrade` while re-installing packages?

**Comment by girving** [comment] 2016-04-29 23:00
Can I close this bug as a duplicate of #2034?

**Comment by pklfz** [comment] 2016-04-30 04:43
I `pip install` tensorflow egg to **Anaconda** python instead of to system python and this bug disappears. May help someone deal with it.

**Comment by pulkitag** [comment] 2016-04-30 17:52
@girving  Yes, its the same as #2034.

**Comment by girving** [comment] 2016-04-30 18:59
Closing as duplicate of #2034.

**Closed by girving** 2016-04-30 18:59 UTC

**Comment by cruvadom** [comment] 2016-05-11 14:34
I had a similar issue, the first time I tried importing tensorflow I got:
AttributeError: NewBase is_abstract, ImportError: ...
And starting the second time I got the above mentioned error. What solved the issue for me is to update the version of 'six' as instructed in 
https://github.com/tensorflow/tensorflow/issues/1965

Cheers

**Comment by girving** [comment] 2016-05-11 14:37
@cruvadom: That sounds like an unrelated issue, since what you describe is not a segfault.  If your issue still occurs with tensorflow at master, please file a separate issue.

**Comment by prinsherbert** [comment] 2016-05-29 08:15
`sckit-image` should be `scikit-image` I assume?

**Comment by kalleknast** [comment] 2016-06-15 12:14
@viksit: Sorry for the delay. I did a fresh tensorflow installation on a new computer and the problem remains. I get a segfault if I import Gtk and tensorflow. Cuda version 6 has never been installed on the computer (only Cuda compilation tools release 7.5, V7.5.17 and CUDNN is v 4).

I want to point out that the segfault ONLY occurs when importing both Gtk (ie `import gi; from gi.repository import Gtk`) and tensorflow. I haven't encountered any segfaults related to numpy or scipy (as in #2034 ) or from tensorflow alone.
Earlier, it worked if I imported tensorflow before Gtk, but now import order also gives a segfault. However, the error is probably different, since doing this outputs some information about a difference between the installed and compiled against version of protobuf. I guess it is irrelevant to the original problem.

**Comment by girving** [comment] 2016-06-15 15:31
@kalleknast That does seem like it could be a similar problem, but please file a separate issue anyway since we're trying to keep the issue tracker organized and this one has already been fixed.  Apologies for the bureaucracy, but keeping issues focused helps us not let fall through the cracks (and not get fixed).

**Comment by kalleknast** [comment] 2016-06-15 20:26
@girving 
The back trace from core dump from the original segfault (ie importing Gtk before tensorflow):

`[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python3 /usr/local/bin/ipython'.`
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdd874a4b2b in tensorflow::kernel_factory::OpKernelRegistrar::InitInternal(tensorflow::KernelDef const*, tensorflow::StringPiece, tensorflow::OpKernel* (*)(tensorflow::OpKernelConstruction*)) () from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so
[Current thread is 1 (Thread 0x7fddb1d0b700 (LWP 13674))]
(gdb) 
(gdb) bt
#0  0x00007fdd874a4b2b in tensorflow::kernel_factory::OpKernelRegistrar::InitInternal(tensorflow::KernelDef const*, tensorflow::StringPiece, tensorflow::OpKernel* (*)(tensorflow::OpKernelConstruction*)) () from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#1  0x00007fdd8655442e in _GLOBAL__sub_I_py_func.cc ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#2  0x00007fddb1b194ea in call_init (l=<optimized out>, argc=argc@entry=2, 
    argv=argv@entry=0x7ffc8038a018, env=env@entry=0x122be60) at dl-init.c:72
#3  0x00007fddb1b195fb in call_init (env=0x122be60, argv=0x7ffc8038a018, argc=2, l=<optimized out>)
    at dl-init.c:30
#4  _dl_init (main_map=main_map@entry=0x1471390, argc=2, argv=0x7ffc8038a018, env=0x122be60)
    at dl-init.c:120
#5  0x00007fddb1b1e712 in dl_open_worker (a=a@entry=0x7ffc80384650) at dl-open.c:575
#6  0x00007fddb1b19394 in _dl_catch_error (objname=objname@entry=0x7ffc80384640, 
    errstring=errstring@entry=0x7ffc80384648, mallocedp=mallocedp@entry=0x7ffc8038463f, 
    operate=operate@entry=0x7fddb1b1e300 <dl_open_worker>, args=args@entry=0x7ffc80384650)
    at dl-error.c:187
#7  0x00007fddb1b1dbd9 in _dl_open (
    file=0x7fddac03d7c0 "/usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so", mode=-2147483390, caller_dlopen=0x62735a <_PyImport_FindSharedFuncptr+138>, nsid=-2, 
    argc=<optimized out>, argv=<optimized out>, env=0x122be60) at dl-open.c:660
#8  0x00007fddb131ff09 in dlopen_doit (a=a@entry=0x7ffc80384880) at dlopen.c:66
#9  0x00007fddb1b19394 in _dl_catch_error (objname=0xe752f0, errstring=0xe752f8, 
    mallocedp=0xe752e8, operate=0x7fddb131feb0 <dlopen_doit>, args=0x7ffc80384880) at dl-error.c:187
#10 0x00007fddb1320571 in _dlerror_run (operate=operate@entry=0x7fddb131feb0 <dlopen_doit>, 
    args=args@entry=0x7ffc80384880) at dlerror.c:163
#11 0x00007fddb131ffa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#12 0x000000000062735a in _PyImport_FindSharedFuncptr ()
#13 0x000000000060473b in _PyImport_LoadDynamicModuleWithSpec ()
#14 0x0000000000604c78 in ?? ()
#15 0x00000000004e6513 in PyCFunction_Call ()
#16 0x00000000005407ef in PyEval_EvalFrameEx ()`
...


There is no mentioning of protobuf in this core dump.

However, protobuf is mentioned in the core dump from the segfault caused by importing in the reverse order (tensorflow before Gtk). I'll file that as a separate issue.
