### ISSUE TITLE
tf.keras computes incorrect loss values with Masking

### ISSUE THREAD

**Issue by Innuendo1975** [tensorflow/tensorflow#34491] opened 2019-11-21 16:41 UTC
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip install tensorflow  /  pip install tf-nightly-2.0-preview
- TensorFlow version (use command below): 2.0  /  2.0.0-dev20191002
- Python version: 3.7.5

**Describe the current behavior**

When fitting an LSTM model with a Masking layer using Keras, if you use binary_crossentropy both as loss and metric, the values are different. In particular, the printed metric is correct, while the loss appears to be calculated without masking.

**Code to reproduce the issue**

```
import numpy as np
from numpy.random import normal, randint
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Masking, LSTM, Activation, Dense

time_steps = 20
num_seqs = 100
X = normal(size=(num_seqs, time_steps))  # create artificial data
Y = np.where(X > 0, 1, 0)  # create simple target

lens = randint(low=1, high=time_steps, size=num_seqs)  # create lengths < time_steps (padding needed)
seqs = [row[:row_len] for row, row_len in zip(X, lens)]  # artificially cut sequences
target_seqs = [row[:row_len] for row, row_len in zip(Y, lens)]  # artificially cut target sequences

padded_seqs = pad_sequences(seqs, padding='post', dtype='float32', maxlen=time_steps).reshape(num_seqs, time_steps, -1)
padded_targets = pad_sequences(target_seqs, dtype='float32', padding='post', maxlen=time_steps).reshape(num_seqs, time_steps, -1)

LSTM_SIZE = 16
model = Sequential()
model.add(Masking(mask_value=0., input_shape=(time_steps,1)))
model.add(LSTM(LSTM_SIZE, return_sequences=True))
model.add(Dense(1))
model.add(Activation("sigmoid"))
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["binary_crossentropy"])
print(model.summary())

model.fit(padded_seqs, padded_targets, batch_size=1024, epochs=10)
```

and observe that the loss and metric values are different:

```
Train on 100 samples
Epoch 1/10
100/100 [==============================] - 4s 38ms/sample - loss: 0.3365 - binary_crossentropy: 0.6434
Epoch 2/10
100/100 [==============================] - 0s 253us/sample - loss: 0.3361 - binary_crossentropy: 0.6427
Epoch 3/10
100/100 [==============================] - 0s 260us/sample - loss: 0.3357 - binary_crossentropy: 0.6419
Epoch 4/10
100/100 [==============================] - 0s 271us/sample - loss: 0.3353 - binary_crossentropy: 0.6412
Epoch 5/10
100/100 [==============================] - 0s 266us/sample - loss: 0.3349 - binary_crossentropy: 0.6404
Epoch 6/10
100/100 [==============================] - 0s 250us/sample - loss: 0.3345 - binary_crossentropy: 0.6396
Epoch 7/10
100/100 [==============================] - 0s 275us/sample - loss: 0.3341 - binary_crossentropy: 0.6389
Epoch 8/10
100/100 [==============================] - 0s 247us/sample - loss: 0.3337 - binary_crossentropy: 0.6381
Epoch 9/10
100/100 [==============================] - 0s 196us/sample - loss: 0.3333 - binary_crossentropy: 0.6373
Epoch 10/10
100/100 [==============================] - 0s 217us/sample - loss: 0.3329 - binary_crossentropy: 0.6366
```

**Other info / logs**

I already saw this closed issue: https://github.com/tensorflow/tensorflow/issues/25970 and the linked https://stackoverflow.com/questions/54802328/why-am-i-getting-different-values-between-loss-functions-and-metrics-in-tensorfl
That problem appears to be solved in my version, but my problem persists.
 
I also saw this stackoverflow post: https://stackoverflow.com/questions/53808163/same-function-in-keras-loss-and-metric-give-different-values-even-without-regula

The solution doesn't work for me. I tried changing the import statements to

```
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Masking, LSTM, Activation, Dense
```

but the problem remains.

**Comment by oanush** [comment] 2019-11-25 09:03
@Innuendo1975 ,
Issue replicating for the given code in TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/00ae89e92a84ba5d3c606a1c8b535d86/34491.ipynb) of colab.Thanks!

**Comment by qlzh727** [comment] 2020-01-07 06:28
Assigning to Parvithra who is the expert for loss and metrics.

**Comment by amahendrakar** [comment] 2020-06-04 19:16
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/9690ce05dde0b89479d59f4cc5c5356b/34491.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b46ba960d996e63f5919cc533bb46e41/34491-tf-nightly.ipynb). Please find the linked gist. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-03-23 00:23
@Innuendo1975 Is this still an issue for you. I changed `mask_value` to 1.0, then the loss and metrics are matching as expected.

`model.add(Masking(mask_value=1., input_shape=(time_steps,1)))`

[Here](https://colab.research.google.com/gist/jvishnuvardhan/9bd03b507787953cbdbd3b36dd7cbeb9/34491-tf-nightly.ipynb) is a gist for reference. Thanks!

Please close the issue if this was resolved for you. thanks!

**Comment by Innuendo1975** [comment] 2021-03-23 08:52
Hi @jvishnuvardhan, yes it is still an issue. 

Point is that 'mask_value' in the Masking layer should match the 'value' optional parameter of pad_sequences, which was left at its default 0.0 in the attached example. 
Otherwise, the Masking layer won't find any padding.

If both the 'value' parameter of pad_sequences and the 'mask_value' parameter of Masking are set at 1., the problem persists.

TensorFlow version: 2.4.1 / 2.5.0-dev20210322 (nightly)

**Comment by sushreebarsa** [comment] 2021-05-29 18:37
Was able to reproduce the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/bdba4274c9de2e40012d366840e094f1/untitled86.ipynb)..Thanks !

**Comment by seandaug** [comment] 2021-06-26 21:59
This is actually a symptom of a larger problem: the loss values are incorrect when sample weights are used because the total weighted loss is divided by the number of elements in the tensor (not divided by the total sample weight). When masking is applied, it appears that the sample weights are computed correctly according to the mask, it's just that those weights are not correctly used in the loss calculation.

For more details, see https://github.com/tensorflow/tensorflow/issues/34158#issuecomment-756813250 which includes compact examples of the issue.

**Comment by seandaug** [comment] 2021-06-27 01:54
I was able to fix this issue by overwriting some code in `losses_util.py`. This seems to work in my use case, but I have **not** fully tested it. This patch is for TF 2.5.0. I put this code in a file then import it after importing tensorflow. It edits 3 lines so that the mean's denominator is set to be the total sample weight, not the total number of samples. Lines affected: https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/utils/losses_utils.py#L253-L320

I think a more complete solution would define a new Reduction type in case people want to also use the old method. That would mimic what is done for the metrics, which has a `WEIGHTED_MEAN` option: https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/utils/metrics_utils.py#L44-L56

```
from tensorflow.python.keras.utils import losses_utils
from tensorflow.python.keras.utils.losses_utils import ReductionV2, squeeze_or_expand_dimensions, _safe_mean, _num_elements
from tensorflow.python.ops import math_ops, array_ops
from tensorflow.python.framework import ops
from tensorflow.python.keras import backend
from tensorflow.python.keras.engine import keras_tensor
from tensorflow.python.ops.ragged import ragged_tensor


def reduce_weighted_loss(weighted_losses,
                         sample_weight,  # !!!!!!!!!!!!!!!!!!!!THIS IS A CHANGE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         reduction=ReductionV2.SUM_OVER_BATCH_SIZE):
  """Reduces the individual weighted loss measurements."""
  if reduction == ReductionV2.NONE:
    loss = weighted_losses
  else:
    loss = math_ops.reduce_sum(weighted_losses)
    if reduction == ReductionV2.SUM_OVER_BATCH_SIZE:
      loss = _safe_mean(loss, math_ops.reduce_sum(sample_weight))  # !!!!!!!!!!!!!!!!!!!!THIS IS A CHANGE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  return loss


def compute_weighted_loss(losses,
                          sample_weight=None,
                          reduction=ReductionV2.SUM_OVER_BATCH_SIZE,
                          name=None):
  """Computes the weighted loss.
  Args:
    losses: `Tensor` of shape `[batch_size, d1, ... dN]`.
    sample_weight: Optional `Tensor` whose rank is either 0, or the same rank as
      `losses`, or be broadcastable to `losses`.
    reduction: (Optional) Type of `tf.keras.losses.Reduction` to apply to loss.
      Default value is `SUM_OVER_BATCH_SIZE`.
    name: Optional name for the op.
  Raises:
    ValueError: If the shape of `sample_weight` is not compatible with `losses`.
  Returns:
    Weighted loss `Tensor` of the same type as `losses`. If `reduction` is
    `NONE`, this has the same shape as `losses`; otherwise, it is scalar.
  """
  ReductionV2.validate(reduction)

  # If this function is called directly, then we just default 'AUTO' to
  # 'SUM_OVER_BATCH_SIZE'. Eg. Canned estimator use cases.
  if reduction == ReductionV2.AUTO:
    reduction = ReductionV2.SUM_OVER_BATCH_SIZE
  if sample_weight is None:
    sample_weight = 1.0
  with backend.name_scope(name or 'weighted_loss'):
    # Save the `reduction` argument for loss normalization when distributing
    # to multiple replicas. Used only for estimator + v1 optimizer flow.
    ops.get_default_graph()._last_loss_reduction = reduction  # pylint: disable=protected-access

    if not isinstance(losses,
                      (keras_tensor.KerasTensor, ragged_tensor.RaggedTensor)):
      losses = ops.convert_to_tensor_v2_with_dispatch(losses)
    input_dtype = losses.dtype

    if not isinstance(sample_weight, keras_tensor.KerasTensor):
      sample_weight = ops.convert_to_tensor_v2_with_dispatch(sample_weight)

    # TODO(psv): Handle casting here in a better way, eg. if losses is float64
    # we do not want to lose precision.
    losses = math_ops.cast(losses, 'float32')
    sample_weight = math_ops.cast(sample_weight, 'float32')
    # Update dimensions of `sample_weight` to match with `losses` if possible.
    losses, _, sample_weight = losses_utils.squeeze_or_expand_dimensions(  # pylint: disable=unbalanced-tuple-unpacking
        losses, None, sample_weight)
    weighted_losses = math_ops.multiply(losses, sample_weight)

    # Apply reduction function to the individual weighted losses.
    loss = reduce_weighted_loss(weighted_losses, sample_weight, reduction)  # !!!!!!!!!!!!!!!!!!!!THIS IS A CHANGE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # Convert the result back to the input type.
    loss = math_ops.cast(loss, input_dtype)
    return loss


losses_utils.compute_weighted_loss = compute_weighted_loss
```

**Comment by sushreebarsa** [comment] 2021-08-31 14:51
@Innuendo1975 Could you please refer to the [comment ](https://github.com/tensorflow/tensorflow/issues/34491#issuecomment-869086784) above and try to execute your code using latest TF v2.6 .Please let us know if it helps?Thanks!

**Comment by seandaug** [comment] 2021-09-07 15:01
Please do not close this. This is a very important issue to me.

**Comment by qlzh727** [comment] 2021-09-07 17:16
I have created a new issue in keras-team/keras to track this since the keras code has been moved.

**Closed by qlzh727** 2021-09-07 17:16 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:bug, stalled, comp:keras, TF 2.2

**Comment by Innuendo1975** [comment] 2021-09-08 10:58
The issue still exists and can be reproduced even with the version 2.6.
I have also tried the patch above https://github.com/tensorflow/tensorflow/issues/34491#issuecomment-869086784 with no success.

`Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 0.3452 - binary_crossentropy: 0.6601
Epoch 2/10
1/1 [==============================] - 0s 26ms/step - loss: 0.3448 - binary_crossentropy: 0.6592
Epoch 3/10
1/1 [==============================] - 0s 26ms/step - loss: 0.3443 - binary_crossentropy: 0.6584
Epoch 4/10
1/1 [==============================] - 0s 23ms/step - loss: 0.3439 - binary_crossentropy: 0.6575
Epoch 5/10
1/1 [==============================] - 0s 24ms/step - loss: 0.3434 - binary_crossentropy: 0.6566
Epoch 6/10
1/1 [==============================] - 0s 21ms/step - loss: 0.3430 - binary_crossentropy: 0.6558
Epoch 7/10
1/1 [==============================] - 0s 19ms/step - loss: 0.3425 - binary_crossentropy: 0.6549
Epoch 8/10
1/1 [==============================] - 0s 26ms/step - loss: 0.3421 - binary_crossentropy: 0.6540
Epoch 9/10
1/1 [==============================] - 0s 29ms/step - loss: 0.3416 - binary_crossentropy: 0.6532
Epoch 10/10
1/1 [==============================] - 0s 29ms/step - loss: 0.3411 - binary_crossentropy: 0.6523`

**Comment by yzhangswingman** [comment] 2022-07-20 05:40
Can someone attend to this ticket, please? Can’t attach enough importance to correct loss computation.

**Comment by tsjain** [comment] 2022-07-21 22:18
I second the importance of this. While this (hopefully) doesn't affect the model training and gradients, it affects the reported metrics.

**Comment by seandaug** [comment] 2022-12-14 14:52
@vani-or @yzhangswingman @tsjain See https://github.com/keras-team/keras/issues/15323#issuecomment-1351549740 for an updated workaround for TF 2.10 and 2.11. The codebase is under the keras-team now so any comments on the importance of this issue should be raised under issue https://github.com/keras-team/keras/issues/15323
