### ISSUE TITLE
Keras guide: input_shape needed when fitting example model using datasets (instead of numpy arrays)

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#20827] opened 2018-07-16 05:10 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux fedora 28
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

Below, I'm extracting code from the Keras guide (sequentially)

https://www.tensorflow.org/guide/keras

Here a model is being fit twice, to show you can use numpy or datasets. This works fine:

```
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu'))
# Add another:
model.add(keras.layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))

model.fit(data, labels, epochs=10, batch_size=32)
          
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset
dataset = dataset.batch(32)
dataset = dataset.repeat()
dataset
# Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
model.fit(dataset, epochs=10, steps_per_epoch=30)
```

However,  if you comment the first fit, the second will fail:

```
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu'))
# Add another:
model.add(keras.layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

#model.fit(data, labels, epochs=10, batch_size=32)
          
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset
dataset = dataset.batch(32)
dataset = dataset.repeat()
dataset
# Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
model.fit(dataset, epochs=10, steps_per_epoch=30)
```

with

```
  TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float64 of argument 'x'.
```

When I add an `input_shape` to the model, the fit using datasets works fine standalone, too.

So if `input_shape` is required with datasets, the model in the guide should probably have it, so people can copy out and directly use the code?

**Comment by Sirplentifus** [comment] 2018-07-16 13:58
I have this exact same issue.
Everything skye has said, occurs in my system. 

Strangely (for me at least) compiling and running model.fit again after this error works:
```
#Following instructions on https://www.tensorflow.org/guide/keras

import tensorflow as tf
from tensorflow import keras
import numpy as np

model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu'))
# Add another:
model.add(keras.layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])


data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))

#model.fit(data, labels, epochs=10, batch_size=32)

# Instantiates a toy dataset instance:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)
dataset = dataset.repeat()

# Don't forget to specify `steps_per_epoch` when calling `fit` on a dataset.
try:
    model.fit(dataset, epochs=10, steps_per_epoch=30)
except:
    print("Error - repeating")

    model.compile(optimizer=tf.train.AdamOptimizer(0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.fit(dataset, epochs=10, steps_per_epoch=30)
```

**Comment by pavithrasv** [comment] 2018-07-24 17:35
Thank you @skeydan and @Sirplentifus for reporting this. The issue has been fixed by https://github.com/tensorflow/tensorflow/commit/efe370fcb367efd069c8166120858492dffa9a33#diff-2afc7c6acfd68474e1e8c56718431276

This will be available in the next nightly release. Please try and let us know if it works for you.

**Comment by skeydan** [comment] 2018-07-25 20:19
thanks, with the nightly build it works for me!

**Closed** 2018-07-25 20:22 UTC

**Comment by Efaq** [comment] 2018-09-10 09:55
@pavithrasv I have just tested the issue, and I am being able to reproduce the error. That is, the code mentioned above, with two calls to fit, works well, but commenting the first fit gives error in the second. That is: "TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float64 of argument 'a'."

I am in Windows 10 enterprise, not using GPUs, tensorflow version = 1.11.0-dev20180907

Please notice that I am working with a nightly built since 1.10 was giving other issues, please see https://github.com/tensorflow/tensorflow/issues/21894
