### ISSUE TITLE
building issue with cuda 8.0RC and computing capability 6.1

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#3788] opened 2016-08-13 01:41 UTC
```
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(279): error: identifier "h2log1p" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00000170_00000000-9_depthtospace_op_gpu.cu.compute_61.cpp1.ii".
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:1529:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.o' was not created.
ERROR: /home/wenjian/pkgs/tensorflow/tensorflow/core/kernels/BUILD:1529:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 112.094s, Critical Path: 108.68s
```

so `error: identifier "h2log1p" is undefined` is the cause, there must be something new in the Eigen library

**Comment by suiyuan2009** [comment] 2016-08-13 11:09
recommend this [issue ](https://github.com/tensorflow/tensorflow/issues/2109#issuecomment-233219528)

**Comment by fayeshine** [comment] 2016-08-13 12:04
@suiyuan2009 sorry, I tried this but it cannot help this bug

**Comment by suiyuan2009** [comment] 2016-08-13 13:00
@fayeshine my GTX 1080 is not available to me now, you can try a old version of gcc or try to add more header files paths to crosstool.

**Comment by prb12** [comment] 2016-08-22 16:24
Please can you follow the template for reporting an issue.  It is impossible to triage if you do not provide software versions and adequate information to reproduce.

**Comment by Mazecreator** [comment] 2016-08-22 16:30
This appears to be a duplicate of other reports.  I had this issue and it was resolved a few days ago at the HEAD.

**Comment by vrv** [comment] 2016-08-22 16:36
Yes, I believe it was fixed already.

**Closed by vrv** 2016-08-22 16:36 UTC
Labels: awaiting response

**Comment by flx42** [comment] 2016-08-23 23:43
@vrv is the fix going to be cherry-picked in the r0.10 branch?

**Comment by vrv** [comment] 2016-08-23 23:45
Hm, it should be.

https://github.com/tensorflow/tensorflow/commit/2ddc543401efe02a521f6ce9c3a41753faa8c774 is the one, right?

**Comment by vrv** [comment] 2016-08-23 23:50
https://github.com/tensorflow/tensorflow/commit/5d3492df515b059c7b5ccfb72d3a3f3088594f52 I just cherry-picked it -- can you let me know if it works now?

**Comment by flx42** [comment] 2016-08-24 03:02
@vrv it works fine now, thanks a lot for your prompt answer!
