### ISSUE TITLE
Converting the model to TFLite format getting “Check failed: is_rnn_state_array ”

### ISSUE THREAD

**Issue by iskuhis** [tensorflow/tensorflow#21170] opened 2018-07-26 18:23 UTC
toco \--input_file=$TRAINING_DIR/retrained_graph.pb \
--input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE \
--output_file=/$TRAINING_DIR/${ARCHITECTURE}.tflite \
--inference_type=QUANTIZED_UINT8 \
--input_arrays=input \
--output_arrays=final_result \ 
--input_shapes=1,224,224,3 \inference_input_type=QUANTIZED_UNIT8 \
--mean_values=128 \
--std_values=128 \
--default_ranges_min=0 \
--quantize_weights=true \
--default_ranges_max=6

**Comment by tensorflowbutler** [comment] 2018-07-27 06:42
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by iskuhis** [comment] 2018-07-27 12:22
tensorflow - 1.7.1
macOS Sierra
Following this instructions
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/#0

**Comment by aselle** [comment] 2018-07-30 18:19
please use the binary "tflite_convert" on the nightly build and see if you are still hitting this problem.

**Comment by tofulawrence** [comment] 2018-08-23 18:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-08-23 18:32 UTC
Labels: comp:lite, stat:awaiting response

**Comment by pribadihcr** [comment] 2018-09-06 07:26
+1
