### ISSUE TITLE
Access to C++ APIs for tfprof

### ISSUE THREAD

**Issue by tvkpz** [tensorflow/tensorflow#16821] opened 2018-02-07 04:06 UTC
Hi

How can I get access to the C++ APIs for tfprof?

**Comment by tensorflowbutler** [comment] 2018-02-07 13:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-02-22 13:06
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tvkpz** [comment] 2018-02-22 19:55
Have I written custom code - Yes
OS Platform and Distribution - Linux
TensorFlow installed from - Github (built from source)
TensorFlow version - 1.4.1
Bazel version - 0.8.1
CUDA/cuDNN version - 8/6
GPU model and memory - NVidia M40 / 24GB
Exact command to reproduce - N/A

**Comment by bignamehyp** [comment] 2018-02-23 08:38
@ChrisAntaki can you please take a look?

**Comment by ChrisAntaki** [comment] 2018-02-24 18:07
Sorry, I just have experience using the Python API

**Comment by poxvoculi** [comment] 2018-04-05 20:02
@shlens: looks like this question was invited from this documentation: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tfprof

**Comment by zhangyaobit** [comment] 2018-04-05 23:59
@panyx0718 Could you comment on it?

**Comment by ydp** [comment] 2018-04-12 02:04
@tvkpz  Hi, sorry to bother, did you have solution for this?

**Comment by tensorflowbutler** [comment] 2018-04-26 18:51
Nagging Assignee @zhangyaobit: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-11 18:48
Nagging Assignee @zhangyaobit: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:04
Nagging Assignee @zhangyaobit: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:52
Nagging Assignee @zhangyaobit: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging Assignee @zhangyaobit: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:06
Nagging Assignee @zhangyaobit: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:00
Nagging Assignee @zhangyaobit: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:03
Nagging Assignee @zhangyaobit: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:45
Nagging Assignee @zhangyaobit: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:39
Nagging Assignee @zhangyaobit: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:46
Nagging Assignee @zhangyaobit: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:45
Nagging Assignee @zhangyaobit: It has been 179 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-10-15 21:30
@gunan Hi, is there any procedure for an external user to request access to C++ API for tfprof ?

**Comment by gunan** [comment] 2018-10-16 04:16
@harshini-gadige no idea.
@shlens looks like you are the only remaining owner of this component. If you have no idea about its C++ interface, I am inclined to say that C++ API for this module does not exist. Could you submit a change to remove the C++ interface from the README?

@martinwicke FYI

**Comment by martinwicke** [comment] 2018-10-16 04:58
This looks like an ownerless contrib module to me. I will close this issue. If someone wants to fix the readme, great.

**Closed by martinwicke** 2018-10-16 04:58 UTC
