### ISSUE TITLE
fatal error LNK1120: 4 unresolved externals when using bazel to build transform-graph

### ISSUE THREAD

**Issue by habom2310** [tensorflow/tensorflow#23963] opened 2018-11-26 02:18 UTC
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: source
- TensorFlow version: 1.12.0
- Python version: 3.5
- Bazel version (if compiling from source): 0.19.2
- CUDA/cuDNN version: No
- GPU model and memory: No

**Problem**
I have a build problem when using bazel to build transform-graph. The error is `fatal error LNK1120: 4 unresolved externals`

**Commands executed before running into the problem**
I've already done `set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC`
then `bazel build tensorflow/tools/graph_transforms:transform_graph --local_resources 2048,.5,1.0`

**Full error log:**
 
ERROR: C:/users/administrator/desktop/tensorflow-build/tensorflow/tensorflow/tools/graph_transforms/BUILD:219:1: Linking of rule '//tensorflow/tools/graph_transforms:transform_graph' failed (Exit 1120): link.exe failed: error executing command
  cd C:/users/administrator/_bazel_administrator/x7v2faqn/execroot/org_tensorflow
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Anaconda/envs/tensor/python.exe
    SET PYTHON_LIB_PATH=C:/Anaconda/envs/tensor/lib/site-packages
    SET TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\ADMINI~1\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/x64_windows-opt/bin/tensorflow/tools/graph_transforms/transform_graph.exe /SUBSYSTEM:CONSOLE -DEFAULTLIB:advapi32.lib /MACHINE:X64 @bazel-out/x64_windows-opt/bin/tensorflow/tools/graph_transforms/transform_graph.exe-2.params /OPT:ICF /OPT:REF
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/tools/graph_transforms/transform_graph.lib and object bazel-out/x64_windows-opt/bin/tensorflow/tools/graph_transforms/transform_graph.exp
batch_kernels.lo.lib(batch_kernels.obj) : warning LNK4217: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported in function "void __cdecl tensorflow::`dynamic initializer for 'registrar__body__0__object''(void)" (??__Eregistrar__body__0__object@tensorflow@@YAXXZ)
captured_function.lib(captured_function.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_CPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_CPU) imported
arithmetic_optimizer.lib(arithmetic_optimizer.obj) : warning LNK4217: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported in function "private: bool __cdecl tensorflow::grappler::`anonymous namespace'::ReorderCastAndTranspose::NodeIsOnCpuOrGpu(class tensorflow::NodeDef const *)const " (?NodeIsOnCpuOrGpu@ReorderCastAndTranspose@?A0x2ef8a95a@grappler@tensorflow@@AEBA_NPEBVNodeDef@4@@Z)
layout_optimizer.lib(layout_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
pin_to_host_optimizer.lib(pin_to_host_optimizer.obj) : warning LNK4049: locally defined symbol ?DEVICE_GPU@tensorflow@@3QEBDEB (char const * const tensorflow::DEVICE_GPU) imported
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl icu_62::ErrorCode::~ErrorCode(void)" (__imp_??1ErrorCode@icu_62@@UEAA@XZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: signed char __cdecl icu_62::ErrorCode::isSuccess(void)const " (__imp_?isSuccess@ErrorCode@icu_62@@QEBACXZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum UErrorCode __cdecl icu_62::ErrorCode::reset(void)" (__imp_?reset@ErrorCode@icu_62@@QEAA?AW4UErrorCode@@XZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) const icu_62::ErrorCode::`vftable'" (__imp_??_7ErrorCode@icu_62@@6B@) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
bazel-out/x64_windows-opt/bin/tensorflow/tools/graph_transforms/transform_graph.exe : fatal error LNK1120: 4 unresolved externals
Target //tensorflow/tools/graph_transforms:transform_graph failed to build
INFO: Elapsed time: 569.319s, Critical Path: 237.59s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by mrry** [comment] 2018-11-26 23:47
Assigning to Pete, since this is about the `transform_graph` tool.

**Comment by iariav** [comment] 2018-11-27 07:41
this is a similar error to what i described in #23955.
also got a link error while bazel build the transform_graph tool on a windows 10 os.

**Comment by filipvg68** [comment] 2018-12-09 11:40
Getting same error. Has any progress been made?

**Comment by habom2310** [comment] 2018-12-09 12:00
I've tried some other versions of tensorflow and bazel, but it seems to be a problem with windows 10. I've just simply changed to ubuntu and no more error.

**Comment by filipvg68** [comment] 2018-12-09 15:41
Thanks, ubuntu works indeed

**Comment by jesen8** [comment] 2019-01-15 07:08
but i only use windows 10 , how can i solve it ? thanks. @habom2310  the same error

**Comment by petewarden** [comment] 2019-02-22 23:55
Sorry for the slow response. I haven't had a chance to look at this yet, so keeping it open, but I'm not sure when we will be able to debug it, so adding contributions welcome.

**Comment by lissyx** [comment] 2019-02-28 10:06
Also hitting the same error on r1.12 branch, even after applying https://github.com/tensorflow/tensorflow/commit/7e090f6a5412fd5f22b5b75ca7ae7844c3d025e9 :[

**Comment by lissyx** [comment] 2019-02-28 10:49
@petewarden Actually, it did fix it, one should just make sure the ` #define U_STATIC_IMPLEMENTATION ` is **before** the other includes, at least on my `r1.12` branch.

**Comment by RaniemAR** [comment] 2019-03-18 15:52
Hello and Thanks all for your comments on this post 
Any update on this issue guys ?
@lissyx I tried your suggested solution but still stuck and unable to build transform_graph on windows 
Is there any pre-built binaries that we can use instead ?

Thanks and Regards

**Comment by lissyx** [comment] 2019-03-18 16:04
@RaniemAR I can't speak for TensorFlow team regarding prebuilt binaries, but make sure you place the define at the right place.
Here: https://github.com/mozilla/tensorflow/commit/ebd1a0ff1a0ed3e211ced4033a42326fd25c8661

**Comment by RaniemAR** [comment] 2019-03-18 16:55
Thanks a lot you were absolutely right, I thought I made sure I added it above the includes but when I double checked i found out that I was wrong. Fixed it and it now builds 
Thanks a million

**Comment by lissyx** [comment] 2019-03-18 17:15
@petewarden Since our backport of the upstream fix works, I've opened a PR: https://github.com/tensorflow/tensorflow/pull/26845

**Comment by petewarden** [comment] 2019-08-01 21:42
Closing as a duplicate of #23955

**Closed by petewarden** 2019-08-01 21:42 UTC
Labels: stat:contributions welcome, type:build/install
