### ISSUE TITLE
Object Detection Android App Crash

### ISSUE THREAD

**Issue by myasser63** [tensorflow/tensorflow#52194] opened 2021-09-30 05:47 UTC
I am trying to convert my custom `MobileNet Single Shot Detector (v2)`  TF 1.x to `tflite` using [Roboflow tutorial colab](https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing). After Conversion I deploy it on [Tensorflow android app demo ](https://github.com/tensorflow/examples.git). When I run the app it always crashes after lunch immediately showing the following error:
'''
E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.tensorflow.lite.examples.detection, PID: 10743
java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.
at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithByteBuffer(Native Method)
at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$100(ObjectDetector.java:86)
at org.tensorflow.lite.task.vision.detector.ObjectDetector$3.createHandle(ObjectDetector.java:211)
at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromBufferAndOptions(ObjectDetector.java:207)
at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.(TFLiteObjectDetectionAPIModel.java:87)
at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:81)
at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
at org.tensorflow.lite.examples.detection.CameraActivity$7.onPreviewSizeChosen(CameraActivity.java:446)
at org.tensorflow.lite.examples.detection.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:357)
at org.tensorflow.lite.examples.detection.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:362)
at org.tensorflow.lite.examples.detection.CameraConnectionFragment.access$300(CameraConnectionFragment.java:66)
at org.tensorflow.lite.examples.detection.CameraConnectionFragment$3.onSurfaceTextureAvailable(CameraConnectionFragment.java:171)
at android.view.TextureView.getTextureLayer(TextureView.java:415)
at android.view.TextureView.draw(TextureView.java:360)
at android.view.View.updateDisplayListIfDirty(View.java:21389)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.draw(View.java:22538)
at android.view.View.updateDisplayListIfDirty(View.java:21389)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.draw(View.java:22538)
at android.view.View.updateDisplayListIfDirty(View.java:21389)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.updateDisplayListIfDirty(View.java:21380)
at android.view.View.draw(View.java:22254)
at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
at android.view.View.draw(View.java:22538)
at com.android.internal.policy.DecorView.draw(DecorView.java:848)
at android.view.View.updateDisplayListIfDirty(View.java:21389)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4417)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
at android.view.Choreographer.doFrame(Choreographer.java:1049)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8010)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/Process: Sending signal. PID: 10743 SIG: 9
'''

**Comment by myasser63** [comment] 2021-09-30 06:12
@tilakrayal Could you assist with this problem

**Comment by tilakrayal** [comment] 2021-09-30 13:55
@myasser63 ,
Looks like this is duplicate of issue #52183.Can you please close this issue, since it is already being tracked there? Thanks!

**Comment by mirjalal** [comment] 2021-10-13 09:38
@myasser63 did you fix the problem?

**Comment by myasser63** [comment] 2021-10-13 16:57
> @myasser63 did you fix the problem?

Not yet, I have tried many times with different models and still getting the same issue

Do you have a solution?

**Comment by mirjalal** [comment] 2021-10-14 11:16
> > @myasser63 did you fix the problem?
> 
> Not yet, I have tried many times with different models and still getting the same issue
> 
> Do you have a solution?

Unfortunately no.

**Comment by tilakrayal** [comment] 2021-10-17 03:39
@myasser63 ,
We see that you are using tf version 1.x which is not actively supported, please update to v2.6 and let us know if you are using same issue.Thanks!

**Comment by tilakrayal** [comment] 2021-10-17 03:40
@myasser63 ,
Can you please let us know the tensorflow version you are using.Thanks!

**Comment by myasser63** [comment] 2021-10-17 12:06
I used tensorflow object detection with TF 1.x

**Comment by mirjalal** [comment] 2021-10-17 14:43
I used tensorflow obj detection with TF 2.x

**Comment by tilakrayal** [comment] 2021-10-18 06:08
@myasser63 ,
We see that you are using tf version 1.x which is not actively supported, please update to latest stable v2.6 and let us know if you are using same issue.

**Comment by myasser63** [comment] 2021-10-18 16:15
I tried to use TF2.X to train `ssd_mobilenet_v2_320x320_coco17_tpu-8` using [Roboflow colab](https://colab.research.google.com/drive/1sLqFKVV94wm-lglFq_0kGo2ciM0kecWD#scrollTo=QcHJuaurS_AO&uniqifier=1)  but I am getting this error when I train  the model:

During handling of the above exception, another exception occurred:

'''
Traceback (most recent call last):
  File "/content/models/research/object_detection/model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 598, in train_loop
    model_dir)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/utils/variables_helper.py", line 213, in ensure_checkpoint_supported
    variables = tf.train.list_variables(checkpoint_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 113, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 68, in load_checkpoint
    return py_checkpoint_reader.NewCheckpointReader(filename)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 100, in NewCheckpointReader
    error_translator(e)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /content/models/research/deploy/ssd_mobilenet_v2/checkpoint/ckpt-0
'''

**Comment by mirjalal** [comment] 2021-10-19 09:05
which version of tf are you used?

**Comment by myasser63** [comment] 2021-10-20 10:45
I used 2.6

**Comment by myasser63** [comment] 2021-10-21 11:15
I am trying to convert `MobilenetV2` to `Tflite `using the code below 
```
!python /content/models/research/object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path /content/models/research/deploy/ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config \
    --trained_checkpoint_dir /content/training/checkpoint \
    --output_directory /content/tflite/
```

and I always get this error:

2021-10-21 11:14:34.124780: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.135413: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.136244: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.145875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.146739: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.147505: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.632718: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.633500: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.634332: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-21 11:14:34.635050: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2021-10-21 11:14:34.635115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10819 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7
Traceback (most recent call last):
  File "/content/models/research/object_detection/export_tflite_graph_tf2.py", line 161, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/content/models/research/object_detection/export_tflite_graph_tf2.py", line 157, in main
    FLAGS.centernet_include_keypoints, FLAGS.keypoint_label_map_path)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/export_tflite_graph_lib_tf2.py", line 365, in export_tflite_model
    status.assert_existing_objects_matched()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/util.py", line 947, in assert_existing_objects_matched
    "No checkpoint specified (save_path=None); nothing is being restored.")
AssertionError: No checkpoint specified (save_path=None); nothing is being restored.

**Comment by sachinprasadhs** [comment] 2021-10-21 15:51
@myasser63 did you try with 2.5 version as @mirjalal claimed that it worked for him after downgrading the Tensorflow version, also can you try the same with tf-nightly version as well. Thank you.

**Comment by PadalaKavya** [comment] 2022-06-11 06:25
> I am getting now this error:
> 
> E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1 Process: org.tensorflow.codelabs.objectdetection, PID: 13744 java.lang.AssertionError: Error occurred when initializing ObjectDetector: Output tensor at index 0 is expected to have 3 dimensions, found 2. at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithModelFdAndOptions(Native Method) at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$000(ObjectDetector.java:86) at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:152) at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:145) at org.tensorflow.lite.task.core.TaskJniUtils$1.createHandle(TaskJniUtils.java:70) at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91) at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromFdAndOptions(TaskJniUtils.java:66) at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromFileAndOptions(ObjectDetector.java:143) at org.tensorflow.codelabs.objectdetection.MainActivity.runObjectDetection(MainActivity.kt:127) at org.tensorflow.codelabs.objectdetection.MainActivity.access$runObjectDetection(MainActivity.kt:48) at org.tensorflow.codelabs.objectdetection.MainActivity$setViewAndDetect$1.invokeSuspend(MainActivity.kt:183) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

I am having the same error. 
[https://stackoverflow.com/questions/72582191/e-androidruntime-fatal-exception-defaultdispatcher-worker-1-process-org-tenso](url)

**Comment by sachinprasadhs** [comment] 2022-06-14 22:56
@PadalaKavya , Could you please try the below suggestion using latest Tensorflow version. Thanks!

> The first issue, "java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.", was due to lack of metadata. To be more specific, floating models require metadata information of NormalizationOptions. You can add metadata using [MetadataWriter API for ObjectDetector](https://www.tensorflow.org/lite/convert/metadata_writer_tutorial#object_detectors).
> 
> The second issue, "Output tensor at index 0 is expected to have 3 dimensions, found 2." is due an update in TF 2.6 that the order of the output tensor may get changed. Model Maker and Task Library have fixed the issue in the nightly build. In the reference app, you need to depend on the nightly build of Task library, i.e. changing [this](https://github.com/tensorflow/examples/blob/f9dfe1d72d3a2e4ae9673eddf0e416c3c6ddaeaf/lite/examples/object_detection/android/lib_task_api/build.gradle#L42) to
> 
> ```
> implementation 'org.tensorflow:tensorflow-lite-task-vision:0.0.0-nightly-SNAPSHOT'
> ```
> 
> Or, you can roll back Model Maker, TF, Task Library to some old version.

**Closed** 2022-06-28 23:48 UTC
Labels: stat:awaiting response, type:bug, stalled, TF 2.5
