### ISSUE TITLE
Building Tensorflow on Windows

### ISSUE THREAD

**Issue by phueac** [tensorflow/tensorflow#18296] opened 2018-04-06 16:13 UTC
At https://www.tensorflow.org/install/install_sources, you say:

"We do not support building TensorFlow on Windows."

Why not? Are there any plans to support this in future? I know it is technically possible to build with CMake, but official support would be nice. At the moment, I am trying to use a trained model for inference as part of a C++ application. I am constrained to Windows, and getting a trained model into the app is much more difficult than it needs to be. Surely there are many people out there also using Windows?

Thanks!

**Comment by tensorflowbutler** [comment] 2018-04-07 00:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by phueac** [comment] 2018-04-07 22:39
Have I written custom code: No
OS Platform and Distribution: Windows 10 64-bit Fall Creator's Update
TensorFlow installed from: pip install tensorflow via Anaconda
TensorFlow version: 1.7
Bazel version: N/A
CUDA/cuDNN version: CUDA 9.0
GPU model and memory: Nvidia K2200 4GB
Exact command to reproduce: N/A

**Comment by mrry** [comment] 2018-05-04 17:42
Since we first released it in late 2016, we've been using CMake as a temporary build system to build TensorFlow for Windows binaries, while the necessary support in Bazel was developed. TensorFlow/Bazel/Windows support has improved greatly over that time (thanks mostly to @meteorcloudy's hard work), and we intend to switch over to Bazel builds on Windows soon. At that point, we will have standardized on a single build system, and it will be easier to support user builds on Windows as well as Linux and Mac OS X. The CMake build will likely remain, but transition to community support. (/cc @ewilderj).

Reassigning this to @martinwicke and @gunan for comment on when the switch to Bazel for Windows will be made, and what support will come with it.

**Comment by ewilderj** [comment] 2018-05-04 17:48
Please also ensure that SIG Build is informed

**Comment by gunan** [comment] 2018-05-04 17:59
@meteorcloudy to comment.
I think right now, on windows building tensorflow with bazel works great when you only would like to have CPU support.
For GPU support, we are working on a few issues, but the switch will be immediately after.
We will need to prepare a separate page because there are many details to building on windows, but I am happy to say we are very close to the switch.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:44
Nagging Assignees @martinwicke, @gunan: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment] 2018-05-28 14:32
@meteorcloudy Is there any documentations using Bazel to build tensorflow on Windows? I encountered some issues in #19583, likely related configurations. A documentation about building on Windows with Bazel will help greatly.

**Comment by tensorflowbutler** [comment] 2018-06-12 19:13
Nagging Assignees @martinwicke, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-27 18:48
Nagging Assignees @martinwicke, @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rongjiecomputer** [comment] 2018-07-04 14:56
I just notice this Github issue for Bazel/Windows stuffs. Subscribing.

> We now have release build using Bazel for the pip package with CPU support.

Official binary is still not built by Bazel on Windows I suppose?

Currently many dependencies such as zlib, jpeg and png do not use SIMD when building with Bazel on Windows (some PRs: https://github.com/tensorflow/tensorflow/pull/20538 https://github.com/tensorflow/tensorflow/pull/20537). There are also a few optimization flags added to CMake build but not yet for Bazel on Windows (will send PRs to Bazel's side).

Please let me know the rough timeline of shipping binary built by Bazel on Windows so that I can prioritize what to work on.

**Comment by meteorcloudy** [comment] 2018-07-04 16:33
@rongjiecomputer I'm working on some final issues of the Windows GPU build. I expect it will be ready in at most two weeks, so I guess the next release (1.10.0) could be built with Bazel. @gunan can confirm that.

**Comment by martinwicke** [comment] 2018-07-11 00:02
@meteorcloudy assigning you to reflect reality.

**Comment by rongjiecomputer** [comment] 2018-07-11 04:57
@meteorcloudy There used to be a public Windows bot waterfall page (https://ci.tensorflow.org/job/tf-master-win-bzl/) that allows me to check if Windows Bazel build has gone wrong from time to time without having to rebuild Tensorflow locally on my computer (Tensorflow's heavy use of C++ template is too tasking for my computer).

Is there such a page for Kokoro Windows bot that is accessible to the public?

**Comment by meteorcloudy** [comment] 2018-07-11 11:35
@rongjiecomputer Unfortunately, I don't think the Kokoro dashboard is publicly accessible. But the TF eng prod team and I are constantly monitoring the Windows build. The CPU build hasn't been broken for months, and recently the CPU build works as well. We're in the process of switching from CMake to Bazel on Windows. After that, we'll have presubmit for Windows build both internally and on github.

**Comment by tensorflowbutler** [comment] 2018-07-26 19:12
Nagging Assignees @meteorcloudy, @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by PinkySan** [comment] 2018-08-14 13:53
Providing the binaries would help with this problem (#21409 )

**Comment by tensorflowbutler** [comment] 2018-08-31 07:57
Nagging Assignees @meteorcloudy, @gunan: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:37
Nagging Assignees @meteorcloudy, @gunan: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-15 19:11
https://www.tensorflow.org/install/install_sources_windows

**Closed by gunan** 2018-09-15 19:11 UTC
Labels: type:build/install

**Comment by guikarist** [comment] 2019-01-02 07:57
See my [comment](https://github.com/tensorflow/tensorflow/issues/7258#issuecomment-450802749) which provides a way to build on Windows automatically.
