### ISSUE TITLE
use 'while_loop' leads to OOM

### ISSUE THREAD

**Issue by JiahaoYao** [tensorflow/tensorflow#29983] opened 2019-06-19 23:49 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow version (use command below): tensorflow-gpu 1.14.0
- Python version: python 3.7
- GPU model and memory: 4 x GTX2080

### My issue 
I use `while_loop` in the main graph. Every time I feed a batch size of dataset, say Mnist into the graph. Does `while_loop` lead to creating newer graph every epoch I train this model? Here is the error reported about OOM. 

```
2019-06-19 16:34:07.703179: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at batch_matmul_op_impl.h:635 : Resource exhausted: OOM when allocating tensor with shape[128,8070,8070] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,8070,8070] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node loop_body_7/MatMul/pfor/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neural_network_1.py", line 212, in <module>
    sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/yue/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[128,8070,8070] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[node loop_body_7/MatMul/pfor/MatMul (defined at neural_network_1.py:119) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

Does anyone have idea about how to solve this OOM issue?

**Comment by gadagashwini** [comment] 2019-06-20 11:28
@JiahaoYao In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-06-26 04:56
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-26 04:56 UTC
Labels: comp:ops, stat:awaiting response, type:support
