### ISSUE TITLE
tf.keras.layers.Input has undefined shape when setting sparse=True, making it impossible to use in a Model

### ISSUE THREAD

**Issue by danielegrattarola** [tensorflow/tensorflow#32737] opened 2019-09-23 20:20 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.0rc1
- Python version:3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia GeForce GTX 1050, 4GB

**Describe the current behavior**
The tensor created by `tensorflow.keras.layers.Input(specified_shape, sparse=True)` has shape `(None,) + (None, ) * len(specified_shape)` and cannot be used as input to e.g., `Dense` layers. 

**Describe the expected behavior**
The tensor created by `tensorflow.keras.layers.Input(specified_shape, sparse=True)` has shape `(None,) + specified_shape` and can be used as input to e.g., `Dense` layers. This is the default behaviour in Keras. 

**Code to reproduce the issue**
```python
from tensorflow.keras.layers import Input, Dense

i = Input(shape=(1, ), sparse=True)
o = Dense(1)(i)
```

**Other info / logs**
Stack trace: 

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    o = Dense(1)(i)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/keras/layers/core.py", line 1009, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

```

**Comment by gadagashwini** [comment] 2019-09-24 08:18
Could reproduce the issue on colab with TF 1.15.1.rc1.Please take a look at gist [here](https://colab.sandbox.google.com/gist/gadagashwini/8ed685bf1786cd6fe8f392a285fdd2c6/untitled162.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-09-24 21:38
@danielegrattarola This is due to sparse tensors. Please read [this](https://github.com/tensorflow/tensorflow/issues/23748#issuecomment-443890338) for more details on the source of the issue.

There is not an easy fix for this. A workaround is 
`i = Input(shape=(1,), sparse=True, batch_size=10)`

Thanks!

**Comment by danielegrattarola** [comment] 2019-09-24 22:04
@jvishnuvardhan I see, but why did it work in previous versions of Keras and TensorFlow then? 
Also defining a batch size is only a workaround for very simple use cases, not a stable solution at all. 

It feels like this makes using sparse tensors practically impossible in most situation.
Is there anything that I or anybody else can do to restore this functionality in Tensorflow?

**Comment by jvishnuvardhan** [comment] 2019-09-24 22:35
@danielegrattarola I think @omalleyt12 provided couple of other ideas (creating subclass layer or Lambda layer to convert your sparse inputs to dense) in response to the other [similar issue](https://github.com/tensorflow/tensorflow/issues/23748#issuecomment-443890338). Please feel free to follow that link and start contribute through PRs. Thanks!

**Comment by MarkDaoust** [comment] 2020-02-06 21:53
I've fixed this in 74195b50fb5e1f22eb95ffd1646b4b0ceca2ea9b, #23748

**Comment by jvishnuvardhan** [comment] 2020-02-26 21:29
Closing this issue as it was resolved already. Thanks!

**Closed by jvishnuvardhan** 2020-02-26 21:29 UTC
Labels: TF 1.15, comp:keras, type:bug

**Comment by zachmayer** [comment] 2021-05-05 21:27
I am on `tf.__version__` `'2.5.0-rc3'` and while `Model.predict` now works fine with sparse data, `Model.fit` does not:
```python
TypeError: 'SparseTensor' object is not subscriptable
```

If I switch my imports from tf.keras to just import from keras, Dense models work just fine.

Why does the keras package support training with sparse input, but tf.keras does not?

**Comment by MarkDaoust** [comment] 2021-05-05 22:59
@zachmayer

Shoot, when I fixed it for predict, I added tests for predict assuming that there were tests for fit __somewhere__...

I'll take a  look, it may b e too late to patch for tf2.5...

**Comment by MarkDaoust** [comment] 2021-05-05 23:00
Can you post the fill trace-back and/or the some simple code to reproduce this?

**Comment by MarkDaoust** [comment] 2021-05-05 23:23
I tried to reproduce this but did not get that error. I need more details to make any progress.

**Comment by zachmayer** [comment] 2021-05-15 02:08
Here is a reproducible example.  Some notes:
1. If you are using sparse data, you must call `x.sort_indices()` before fitting a keras model.  It sort of feels like maybe keras should do that for you?
2. My specific error was caused by calling model.fit on a pandas.Series (but the error message did not make this at all clear)!  I suggest that maybe keras either: a. raise an exception on pandas series input or b. convert the pandas series to a numpy array.  I fixed my error by converting the pandas series to a numpy array.

Here is the code:
```python
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

text = ['sdsadfasd', 'wdfsdfg', 'sDFQERG', 'ASDFASDFG']
x = TfidfVectorizer(analyzer='char').fit_transform(text)
x.sort_indices()  # This is required or the keras model fails
y = pd.Series([1, 0, 1, 0])

inputs = tf.keras.layers.Input(shape=(x.shape[1],), name='dense_inputs')
outputs = tf.keras.layers.Dense(1)(inputs)
model = tf.keras.models.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])

# Fails
model.fit(x, y)
model.predict(x)
```

And then you simply change `model.fit(x, y)` to `model.fit(x, y.values)` and the code works.

```python
# Works
model.fit({'dense_inputs': x}, y.values)
model.predict(x)
```

I am on tensorflow version `'2.5.0-rc3'`

**Comment by zachmayer** [comment] 2021-05-15 02:13
The traceback when the fit fails is below.  What's interesting is that the pandas series isn't part of the traceback.  Converting numpy to pandas somehow changes how the sparse matrix is indexed:

```python
WARNING:tensorflow:Keras is training/fitting/evaluating on array-like data. Keras may not be optimized for this format, so if your input data format is supported by TensorFlow I/O (https://github.com/tensorflow/io) we recommend using that to load a Dataset instead.
2021-05-14 22:09:35.779336: W tensorflow/core/framework/op_kernel.cc:1755] Invalid argument: TypeError: 'SparseTensor' object is not subscriptable
Traceback (most recent call last):

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 488, in py_method
    return [slice_array(inp) for inp in flat_inputs]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 488, in <listcomp>
    return [slice_array(inp) for inp in flat_inputs]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 486, in slice_array
    return training_utils.slice_arrays(data, ind.numpy(),

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in slice_arrays
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in <listcomp>
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in <listcomp>
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

TypeError: 'SparseTensor' object is not subscriptable


InvalidArgumentError:  TypeError: 'SparseTensor' object is not subscriptable
Traceback (most recent call last):

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 488, in py_method
    return [slice_array(inp) for inp in flat_inputs]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 488, in <listcomp>
    return [slice_array(inp) for inp in flat_inputs]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 486, in slice_array
    return training_utils.slice_arrays(data, ind.numpy(),

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in slice_arrays
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in <listcomp>
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

  File "/Users/zachary/Kaggle/CommonLit/python/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils.py", line 50, in <listcomp>
    entries = [[x[i:i + 1] for i in indices] for x in arrays]

TypeError: 'SparseTensor' object is not subscriptable


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_4965]

Function call stack:
train_function
```

**Comment by zachmayer** [comment] 2021-05-24 18:24
@MarkDaoust given my code snippet, are you able to reproduce?

**Comment by zachmayer** [comment] 2021-06-02 18:58
@MarkDaoust ping

**Comment by MarkDaoust** [comment] 2021-06-02 21:12
Thanks for the info (and the ping). 

I haven't worked out the details, but it looks like the difference in behavior stems from this line in the data adapter code:

https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/python/keras/engine/data_adapter.py#L988

When you pass the `pd.Series` the result is `GenericArrayLikeDataAdapter` (fails), but when you pass the values as a np.array the result is a `CompositeTensorDataAdapter` (passes).

That decision seems to be driven by the [`can_handle` method here](https://github.com/tensorflow/tensorflow/blob/15d5b930d7e6e4463e275cfcff22042105148e3f/tensorflow/python/keras/engine/data_adapter.py#L569).

Maybe that line should be checking the [`get_tensor_types`](https://github.com/tensorflow/tensorflow/blob/15d5b930d7e6e4463e275cfcff22042105148e3f/tensorflow/python/keras/engine/data_adapter.py#L569) list of classes.

But IDK.
