### ISSUE TITLE
BUG: Arithmetic computations that should be identical are not?

### ISSUE THREAD

**Issue by dbarta** [tensorflow/tensorflow#19313] opened 2018-05-16 06:56 UTC
### System information
System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.13.4
TensorFlow installed from (source or binary): Binary
TensorFlow version (use command below): v1.8.0-0-g93bc2e2072 1.8.0
Python version: 3.5.4
Bazel version (if compiling from source): 0.11.1
GCC/Compiler version (if compiling from source): 9.1.0
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

### Describe the problem

I'm running two versions of a NN which I expect to produce identical results, but they don't.

The first version contains as part of the computation:

`x = [0.0*a + 1.0*b, 1.0*a + 0.0*b]`

The second contains instead:

`x = [b, a]`

The two runs produce different results. (a and b are both matrices).

I'm using a constant seed for the random noise input, and I've verified that multiple runs of either of the two above cases produce identical results. Just changing from one case to the other produces different results. The results are not broken in either case (i.e. both cases produce reasonable output), just different. 

This seems like a bug to me.

Thanks

EDIT: 

I've also found that doing:

x = 1.0 * a
x = 1.0 * (1.0 * a)
x = tf.identity(a)

All give different results.

Looking at this: https://github.com/tensorflow/tensorflow/issues/14675
Apparently the problem is I've made a change to the computation graph. 

I still think this is a bug so I'm going to leave this here. It's very frustrating when obvious things don't work as expected.

**Comment by Negrodaumus** [comment] 2018-05-17 10:45
Your code is a logic flaw in and of itself. The values you give are x= a/and or b. having to values. 0*x+1*x, 1*x+0. Your equation gives both the same self canceling value. X is a and b. Both are worth both 1x and 0x. You cannot define one thing as having two set values. Things can have a range of values, however you must provide a mechanism for defining these within the program. As you have given x the value of both 1 and nothing, a and b, I hardly think it would work with any code anywhere. 3 functions for one self defined term with 2 simultaneous values? This isn’t a quantum computer ya know. 🤪😂😁

**Comment by dbarta** [comment] 2018-05-17 11:18
@Negrodaumus 
x is an array with 2 values. 
In one case, these two values are each linear interpolations of two tensors a & b. 
In the second case, these two values are simply b then a respectively. 
These two cases produce two separately constructed computations graphs, where one has a bunch of multiplication and addition nodes, which the second doesn't.

**Comment by reedwm** [comment] 2018-05-18 16:53
This is a duplicate of #14675, so I'm closing this issue.

/CC @asimshankar, can you take a look at #14675?

**Comment by asimshankar** [comment] 2018-05-18 17:41
I'm not quite sure it is a duplicate. #14675 is mostly around how changes to the computational graph can affect the seed used for random operations. However, IIUC, there isn't any random initialization involved here.

**Closed** 2018-05-18 17:41 UTC

**Comment by asimshankar** [comment] 2018-05-18 17:44
@dbarta : Do you see this problem only when random initialization is involved?
(Want to confirm that you don't see this issue if `a` and `b` have the same value between runs - and indeed the issue is only when you expect two calls to a random initializer with the same seed to produce the same value)
