### ISSUE TITLE
blank_index in tf.nn.ctc_loss and tf.nn.ctc_beam_search_decoder has different default value

### ISSUE THREAD

**Issue by lriuui0x0** [tensorflow/tensorflow#42140] opened 2020-08-07 21:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7

**Describe the current behavior**

Currently https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss and https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder has different default blank index.

https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss sets default blank index to be 0.

Whreas https://www.tensorflow.org/api_docs/python/tf/nn/ctc_beam_search_decoder doesn't have an API for setting blank index, and it assumes to be `num_category - 1` (see https://github.com/tensorflow/tensorflow/blob/cd7da16dd6c17df428dc9ec105c0c8f11e5fd4f5/tensorflow/core/kernels/ctc_decoder_ops.cc#L331)

**Describe the expected behavior**

This is very unexpected - I would assume they have the same default value since they both work with CTC. Or at least both should provide API to change the blank index.

**Comment by Saduf2019** [comment] 2020-08-10 11:11
@lriuui0x0 
Please provide with simple stand alone code or colab gist witht issue faced.

**Comment by lriuui0x0** [comment] 2020-08-10 21:35
@Saduf2019 There's no standalone code - it's a complain about the unintuitive and misleading API.

**Comment by cameron-martin** [comment] 2021-01-12 22:20
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/42993. An RFC is open here: https://github.com/tensorflow/community/pull/295

**Comment by rmothukuru** [comment] 2021-02-26 10:32
@lriuui0x0,
Can you please confirm if we can close this issue as as RFC has been created as mentioned in the [above comment](https://github.com/tensorflow/tensorflow/issues/42140#issuecomment-759074051)? Thanks!

**Closed** 2021-03-12 11:35 UTC
Labels: comp:core, stalled, stat:awaiting response, type:docs-bug
