### ISSUE TITLE
random output 

### ISSUE THREAD

**Issue by mohlondon** [tensorflow/tensorflow#37413] opened 2020-03-07 11:42 UTC
the chat i created it doesn't work correctly i guess it keep givin me this kind of result no matter how much time i train it 
 

> python3 ./translate.py  --en_vocab_size=40000 --fr_vocab_size=40000 --data_dir=/home/baba055h_s/ --train_dir=/home/baba055h_s/ --decode
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:463: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:464: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:466: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/baba055h_s/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:467: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
WARNING:tensorflow:From /home/baba055h_s/ten3/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py:188 in __init__.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Created model with fresh parameters.
WARNING:tensorflow:From ./translate.py:138 in create_model.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
/> hi
sample sample sample sample sample sample sample sample letter-sized letter-sized
>/> what's up
sample sample sample soil soil soil neski neski neski neski

> as you notice the result are random 10 words at least and some words are repeated  like this :"sample sample sample soil soil soil neski neski neski neski"

>>i'm using 
tensorflow 0.12.1
translate script with branch r0.11
prepare data using this script
https://github.com/b0noI/dialog_converter/tree/master
i trained it up to 4000 time and the same thing

see what is that all about is it something wrong with the data i provided
please help me

**Comment by amahendrakar** [comment] 2020-03-09 11:20
@mohlondon,
In order to expedite the trouble-shooting process, could you please provide the minimal code to reproduce the issue reported here. Thanks!

**Comment by mohlondon** [comment] 2020-03-09 12:00
What code i did mention that i used the translate.py script of this project branch: r0.11

**Comment by amahendrakar** [comment] 2020-03-16 10:56
@mohlondon,
From the link you have provided, I was able to prepare the data. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/68e56a7f958a019dd72555dfcb43ac17/37413.ipynb).

However, there is no translate script used. Could you please provide the link or the code of the  translate script you are using? Thanks!

**Comment by amahendrakar** [comment] 2020-03-27 15:18
@mohlondon,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-03 16:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-03 16:42 UTC
Labels: stat:awaiting response, type:support
