### ISSUE TITLE
External loss function raises error on incompatible types

### ISSUE THREAD

**Issue by andmax** [tensorflow/tensorflow#34528] opened 2019-11-22 18:37 UTC
On TensorFlow 2.0 (OS Ubuntu 16.04), when I've an external loss function, the tf.keras.model fit() function call raises an error of incompatible types, whereas the same code on TensorFlow 1.15 does not raise any error and works fine.  The function fit() fails with:

```
(...)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in
_apply_op_helper(self, op_type_name, name, **keywords)
    561                   "%s type %s of argument '%s'." %
    562                   (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
--> 563                    inferred_from[input_arg.type_attr]))
    564 
    565           types = [values.dtype]

TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type uint8 of
argument 'x'.
```

The minimal code to reproduce is:

```
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K

def loss_func(y_true, y_pred):
    y_true_f = K.batch_flatten(y_true)
    y_pred_f = K.batch_flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f, axis=1, keepdims=True)
    union = K.sum(y_true_f, axis=1, keepdims=True) \
            + K.sum(y_pred_f, axis=1, keepdims=True)
    return -(2. * intersection + K.epsilon()) / (union + K.epsilon())

(Xtr, Ytr), (Xva, Yva) = tf.keras.datasets.cifar10.load_data()
Xtr, Ytr, Xva, Yva, nc = Xtr[:1000], Ytr[:1000], Xva[:100], Yva[:100], 10
Xtr, Xva = Xtr.astype('float32') / 255, Xva.astype('float32') / 255
Ytr, Yva, ins = to_categorical(Ytr, nc), to_categorical(Yva, nc), Xtr.shape[1:]

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(ins))
model.add(tf.keras.layers.Conv2D(8, (3, 3)))
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Conv2D(8, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))
model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(nc, activation='softmax'))
opt = tf.keras.optimizers.RMSprop(lr=0.0001, decay=1e-6)
model.compile(loss=loss_func, optimizer=opt, metrics=[])

Ytr, Yva = Ytr.astype('uint8'), Yva.astype('uint8') # (1)

model.fit(x=Xtr, y=Ytr, batch_size=32, epochs=1, validation_data=(Xva, Yva))
```

If I remove line (1) it works on TensorFlow 2.0.

**Comment by ravikyram** [comment] 2019-11-25 06:24
I have tried on colab with TF version 1.15, 2.0, 2.1.0-dev20191124 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/a3a85b9e573c95299b5d248d662f8db7/untitled402.ipynb). Thanks!

**Comment by ravikyram** [comment] 2020-03-09 10:46
@andmax 

This was resolved in ``tf-nightly`(!pip install tf-nightly)`. Please check the gist [here](https://colab.sandbox.google.com/gist/ravikyram/cc4d485120973b17d5616b85b81a61f0/untitled715.ipynb).

You could use tf-nightly for now and in the next couple of months new stable version will be released.Can you please confirm whether we can close this issue as this was resolved. 
Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-25 01:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tanzhenyu** [comment] 2020-03-25 01:15
Looks like it has been resolved

**Closed** 2020-03-25 01:14 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:bug
