### ISSUE TITLE
DLL load failed on Windows 10 with tensorflow 1.7

### ISSUE THREAD

**Issue by sirjo66** [tensorflow/tensorflow#18530] opened 2018-04-15 11:31 UTC
Hello to all,
on my Windows 10, I installed tensorflow 1.5 and it works, but if I try to upgrade to tensorflow 1.7 it don't works, appeare the error:
**ImportError: DLL load failed
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'**

Microsoft C++ Runtime is updated

If I downgrade to the version 1.5 it works again
How can I solve it ?

Thanks
Sergio

**Comment by tensorflowbutler** [comment] 2018-04-15 18:25
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sirjo66** [comment] 2018-04-16 05:52
Many thanks for your help

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.7
- **Python version**: 
3.6.5
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
from command line: pip install --upgrade tensorflow
from python: import tensorflow

**Comment by skye** [comment] 2018-04-18 16:01
@gunan do you have ideas? Otherwise this will probably rely on community support.

**Comment by advanceddeveloper** [comment] 2018-04-18 17:07
Just for reference, I'm experiencing very similar issue: https://github.com/tensorflow/tensorflow/issues/18503
@sirjo66 posted the link for reference, but for some reason GitHub didn't detect it.

**Comment by gunan** [comment] 2018-04-23 15:04
What is your CPU model?
This is almost certainly an isue with an old CPU, that does not have AVX instruction set.

**Comment by sirjo66** [comment] 2018-04-23 19:32
I bought this PC one month ago
Intel Celeron CPU J3355 @ 2.00 Ghz
but, from specification it don't have AVX  :-(

see it: [http://www.cpu-world.com/Compare/426/Intel_Celeron_J3355_vs_Intel_Core_i5_i5-7600.html](url)

**Comment by 90s-hacker** [comment] 2018-04-23 20:05
@sirjo66 

Your link leads to wrong url.

```
Wrong:   [http://www.example.com/](url)
Correct: [url](http://www.example.com/)
```

Correct url is: [http://www.cpu-world.com/Compare/426/Intel_Celeron_J3355_vs_Intel_Core_i5_i5-7600.html](http://www.cpu-world.com/Compare/426/Intel_Celeron_J3355_vs_Intel_Core_i5_i5-7600.html)

**Comment by tensorflowbutler** [comment] 2018-05-10 01:04
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 19:01
Nagging Assignee @gunan: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-05-28 06:46
duplicate of #19584

**Closed by gunan** 2018-05-28 06:46 UTC

**Comment by mmattklaus** [comment] 2019-06-17 09:31
This may help someone. 
I am a Windows 10 user with TF v1.13
- After installing TF with pip, I experience this error.

Here is what worked for me:
- I already had Anaconda installed
- I ran `conda install tensorflow` and it updated a few packages and installed some. And everything worked fine.
