### ISSUE TITLE
CONV_2d convert to DEPTHWISE_CONV when input depth=1

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#44532] opened 2020-11-03 01:28 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- TensorFlow installed from (source or binary):pip
- TensorFlow version (or github SHA if from source):1.15.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```
tflite_convert  --output_file=centerfacembv2fix.tflite  \
                --graph_def_file=freeze.pb   \
                --inference_type=QUANTIZED_UINT8    \
                --input_arrays=input    \
                --input_shapes=1,320,320,1   \
                --std_dev_values=255 \
                --mean_values=0 \
                --output_arrays=scores,scores_1,scores_2,detector/wh_1,detector/reg_1,detector/angle_reg

**The output from the converter invocation**

```
# Copy and paste the output here.
```
![image](https://user-images.githubusercontent.com/30410113/97936501-a0905900-1db6-11eb-9bc9-33f1d0d74c09.png)

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```
![image](https://user-images.githubusercontent.com/30410113/97936536-cae21680-1db6-11eb-9b08-1c6f9e33cadd.png)
here is my pb model 
**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)
the first layer is CON2D in pb,but converted to tflite it is depthwiseConv

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-11-03 04:59
@sunzhe09 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by sunzhe09** [comment] 2020-11-03 08:01
@ravikyram I cannot paste  my code in colab ，I have problem about prepare dataset in colab；I can upload the first two layers 。which is a subgraph to，reproduce the problem；I think it‘s tflite_convert's problem,because my pb is a right layer
[Uploading testmodel.zip…]()

**Comment by karimnosseir** [comment] 2020-11-20 23:48
The Conv2D->DepthwiseConv2D shouldn't happen in the later TF versions.
Can you please try with nightly may be or 2.4

Thanks

**Comment by sunzhe09** [comment] 2020-11-21 02:24
@KabirKwatra I have tested with TF2.4 and TF-nightly,when I use this options:
tflite_convert  --enable_v1_converter \
                --experimental_new_converter=True \

**Comment by karimnosseir** [comment] 2020-11-21 02:32
Can you please share reproduce sample, so we can check it ?
Also, explain what does wrong mean here ?
wrong result during inference ? wrong visualization ? something else.. Please explain.

Thanks

**Comment by sunzhe09** [comment] 2020-11-21 03:01
I check the tflite model(tf2.4 converted) ,the output branch have many Equal layer during maxpool and select,but the output node is right.so my problem is the wrong visualization?

**Comment by karimnosseir** [comment] 2020-11-30 18:04
@sunzhe09 That might be something missing to canonicalize to avoid this duplicates ? Do you have a sample reproduce for this, so i can check the reason exactly.

Thanks

**Comment by sunzhe09** [comment] 2020-12-03 13:23
here is my command:
#!/bin/bash
tflite_convert  --enable_v1_converter \
                --experimental_new_converter=True  \
                --output_file=test.tflite  \
                --graph_def_file=freeze.pb   \
                --inference_type=QUANTIZED_UINT8    \
                --input_arrays=input    \
                --input_shapes=1,320,320,1   \
                --std_dev_values=255 \
                --mean_values=0 \
                --output_arrays=Select,Select_1,Select_2,detector/wh_1,detector/reg_1,detector/angle_reg

**Comment by karimnosseir** [comment] 2020-12-09 22:16
Thanks @sunzhe09 for providing the reproduce steps.
I have a fix. Will be merged soon.

Thanks

**Closed** 2020-12-09 22:50 UTC
Labels: TF 1.15, TFLiteConverter, comp:lite, type:support
