### ISSUE TITLE
MutableGraphView::SortTopologically error with tf.nn.conv2d in custom RNN cell

### ISSUE THREAD

**Issue by mattdutson** [tensorflow/tensorflow#38279] opened 2020-04-06 18:03 UTC
**System information**

- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04 LTS
- TensorFlow installed from: binary (`conda install tensorflow-gpu=2.1`)
- TensorFlow version: 2.1.0
- Python version: 3.7.7
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6
- GPU model and memory: GeForce GTX 1080, 8 GB

**Describe the current behavior**

Calling `predict` on a model containing a custom RNN layer whose cell calls `tf.nn.conv2d` results in the following error being printed to the console:
```
2020-04-06 12:40:50.843591: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] layout failed: Invalid argument: MutableGraphView::SortTopologically error: detected edge(s) creating cycle(s) {'Func/sequential/rnn/while/body/_1/input/_55' -> 'sequential/rnn/while/body/_1/add'}.
```
The prediction proceeds (and appears to be correct), but has poor performance.

This does not occur if the `tf.nn.conv2d` is replaced with other similar operations (`tf.nn.conv1d` for example).

**Describe the expected behavior**

The expected behavior is for no error to be produced.

**Standalone code to reproduce the issue** 

The following code produces the error:
```python
import tensorflow as tf


class CustomCell(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        self.state_size = [tf.TensorShape((16, 16, 1))]
        super(CustomCell, self).__init__(**kwargs)

    def call(self, inputs, states, **kwargs):
        output = states[0] + tf.nn.conv2d(inputs, tf.ones((3, 3, 1, 1)), (1, 1), "SAME")
        new_state = output
        return output, new_state


model = tf.keras.models.Sequential()
model.add(tf.keras.layers.RNN(CustomCell(), batch_input_shape=(1, 1, 16, 16, 1)))

# Error here
model.predict(tf.ones(model.input_shape))
```

If the `conv2d` is replaced with `conv1d`, however, no error occurs:
```python
import tensorflow as tf


class CustomCell(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        self.state_size = [tf.TensorShape((16, 1))]
        super(CustomCell, self).__init__(**kwargs)

    def call(self, inputs, states, **kwargs):
        output = states[0] + tf.nn.conv1d(inputs, tf.ones((3, 1, 1)), (1,), "SAME")
        new_state = output
        return output, new_state


model = tf.keras.models.Sequential()
model.add(tf.keras.layers.RNN(CustomCell(), batch_input_shape=(1, 1, 16, 1)))

# No error
model.predict(tf.ones(model.input_shape))
```

**Comment by amahendrakar** [comment] 2020-04-07 08:41
@mattdutson,
I was able to run the above code snippets without any error messages with both [TF v2.1](https://colab.research.google.com/gist/amahendrakar/1bfea7bbe1311e108c5864964ef07b91/38279-2-1.ipynb) and [TF v2.2.0rc2](https://colab.research.google.com/gist/amahendrakar/a5a66e6f344ce0fd75943c7d48426305/38279-2-2.ipynb). Please find the attached gist.

Could you please try running the same code in a virtual environment and let us know if it works? Thanks!

**Comment by mattdutson** [comment] 2020-04-07 16:54
@amahendrakar Thanks for the quick reply. It looks like IPython is hiding/suppressing the error message. If you upload the example code snippet to a file `test.py` in the Colab folder and then run from the command-line via `!python test.py` you can see the error message.

**Comment by ambitioncn** [comment] 2020-04-08 19:10
I have the same issue

**Comment by mattdutson** [comment] 2020-04-08 23:41
I noticed today that the error goes away if the RNN layer is constructed with `unroll=True`.

**Comment by mattdutson** [comment] 2020-04-08 23:42
Unrolling is apparently more memory-intensive, however.

**Comment by amahendrakar** [comment] 2020-04-09 07:59
Was able to reproduce the issue with TF v2.2.0rc2 and TF-nightly. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/d59dbcfeb6358851fb6f2994e49f7357/38279-2-2.ipynb#scrollTo=sxLOo03U2rnI&line=1&uniqifier=1). Thanks!

**Comment by ambitioncn** [comment] 2020-04-10 11:41
Please let me know when you have a fix, thanks!    On Thursday, April 9, 2020, 03:59:55 PM GMT+8, amahendrakar <notifications@github.com> wrote:  
 
 


Was able to reproduce the issue with TF v2.2.0rc2 and TF-nightly. Please find the gist here. Thanks!

**Comment by qlzh727** [comment] 2020-05-04 17:49
Seems to  be a grappler issue.

**Comment by rmlarsen** [comment] 2020-05-28 18:24
This appears to be fixed in the latest version at head. I cannot reproduce the error with the code snipped provided. Feel free to reopen if you see this again.

**Closed by rmlarsen** 2020-05-28 18:24 UTC
Labels: TF 2.0, comp:apis, type:bug

**Comment by mattdutson** [comment] 2020-06-01 19:36
Just tested this with `tf-nightly`. The issue does not appear to be resolved. Running the first snippet results in the following error message:
```
2020-06-01 14:34:55.279045: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:575] layout failed: Invalid argument: MutableGraphView::SortTopologically error: detected edge(s) creating cycle(s) {'sequential/rnn/while/next_iteration/_37-0-0-TransposeNCHWToNHWC-LayoutOptimizer' -> 'sequential/rnn/while/merge/_13'}.
```

**Comment by mattdutson** [comment] 2020-06-01 19:38
@rmlarsen Don't think I have the permissions required to reopen the issue. Could you reopen it?

**Comment by Noha82** [comment] 2020-11-12 04:10
I have the same issue, any advice?

**Comment by bguetarni** [comment] 2020-11-17 15:20
In my case, it seems that the error occurs when I let tensorflow do its Layout optimization.
As soon as I added:
`tf.config.optimizer.set_experimental_options({'layout_optimizer': False})`
the error disappeared. I suspect the optimization procedure to be the origin of the problem. This should be investigated.
Hope it helps !
