### ISSUE TITLE
-mavx2 or -mavx prevents eigen from compiling

### ISSUE THREAD

**Issue by mccajm** [tensorflow/tensorflow#3349] opened 2016-07-17 05:39 UTC
I'm compiling the master branch of TensorFlow as follows:
> bazel build -c opt --copt=-mavx2 --config=cuda //tensorflow/tools/pip_package:build_pip_package

and receive the error:

> ERROR: /tmp/tensorflow/tensorflow/contrib/ffmpeg/BUILD:22:1: C++ compilation of rule '//tensorflow/contrib/ffmpeg:decode_audio_op_cc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 57 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:36:0,
                 from ./tensorflow/core/framework/types.h:27,
                 from ./tensorflow/core/framework/type_traits.h:22,
                 from ./tensorflow/core/framework/allocator.h:25,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from tensorflow/contrib/ffmpeg/decode_audio_op.cc:23:
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:347:8: error: 'scalar_multiple2_op' is not a class template
 struct scalar_multiple2_op<QInt32, double> {
        ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:347:44: error: explicit specialization of non-template 'Eigen::internal::scalar_multiple2_op'
 struct scalar_multiple2_op<QInt32, double> {
                                            ^
./third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:369:23: error: 'Eigen::internal::scalar_multiple2_op' is not a template
 struct functor_traits<scalar_multiple2_op<QInt32, double>> {
                       ^
In file included from ./tensorflow/core/framework/op_kernel.h:22:0,
                 from tensorflow/contrib/ffmpeg/decode_audio_op.cc:23:
./tensorflow/core/framework/allocator.h: In member function 'virtual std::size_t tensorflow::Allocator::RequestedSize(void*)':
./tensorflow/core/framework/allocator.h:155:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
In file included from ./tensorflow/core/framework/op_kernel.h:25:0,
                 from tensorflow/contrib/ffmpeg/decode_audio_op.cc:23:
./tensorflow/core/framework/device_base.h: In member function 'virtual tensorflow::Allocator* tensorflow::DeviceBase::GetAllocator(tensorflow::AllocatorAttributes)':
./tensorflow/core/framework/device_base.h:151:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
./tensorflow/core/framework/device_base.h: In member function 'virtual const tensorflow::DeviceAttributes& tensorflow::DeviceBase::attributes() const':
./tensorflow/core/framework/device_base.h:182:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^

/proc/cpuinfo shows my CPU has avx2 support:
>processor       : 31
model name      : Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 **avx2** smep bmi2 erms invpcid cqm xsaveopt cqm_llc

**Comment by bangbangbear** [comment] 2016-07-22 07:20
I met with the same problem, and after I copied the declaration of the template scalar_multiple2_op from eigen, the problem is fixed. Here is the patch (Obviously this is not a good place to put the declaration, but let's wait for a googler to fix). 

index 356bf19..7b5ef66 100644
--- a/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h
+++ b/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h
@@ -343,6 +343,15 @@ EIGEN_STRONG_INLINE QInt8 predux_max<Packet32q8i>(const Packet32q8i& a) {
 }
 
 // Vectorized scaling of Packet32q8i by float.
+template<typename Scalar1, typename Scalar2>
+struct scalar_multiple2_op {
+  typedef typename scalar_product_traits<Scalar1,Scalar2>::ReturnType result_type;
+  EIGEN_STRONG_INLINE scalar_multiple2_op(const scalar_multiple2_op& other) : m_other(other.m_other) { }
+  EIGEN_STRONG_INLINE scalar_multiple2_op(const Scalar2& other) : m_other(other) { }
+  EIGEN_STRONG_INLINE result_type operator() (const Scalar1& a) const { return a * m_other; }
+  typename add_const_on_value_type<typename NumTraits<Scalar2>::Nested>::type m_other;
+};
+
 template<>
 struct scalar_multiple2_op<QInt32, double> {

**Comment by admcrae** [comment] 2016-07-22 14:30
I had this problem on Ubuntu 14.04, but not on 16.04; 16.04 has a newer version of Eigen (3.3), which, according to the Eigen website, adds AVX support. However, I've compiled on 14.04 with AVX in the past, so I'm not sure why this is suddenly a problem now.

**Comment by rmlarsen** [comment] 2016-07-25 17:12
My apologies for missing this. Looking...

**Comment by darrengarvey** [comment] 2016-08-15 08:54
@mccajm - Can you try this again on latest master? Should be fixed now (see #3792).

**Comment by alquraishi** [comment] 2016-08-16 15:51
I had the same problem and now it's fixed for me.

**Closed** 2016-08-16 15:52 UTC

**Comment by hholst80** [comment] 2016-09-04 12:01
Can we ge this backported to r0.10 branch? It does not compile in Ubuntu 16.04 LTS.
