### ISSUE TITLE
"Getting started" first tf.contrib.learn sample fails

### ISSUE THREAD

**Issue by avantol** [tensorflow/tensorflow#7677] opened 2017-02-19 20:30 UTC
The first tf.contrib.learn sample at
https://www.tensorflow.org/get_started/get_started
fails to run.

The  code is right under
"Basic usage
Notice how much simpler the linear regression program becomes with tf.contrib.learn:"

Output:

WARNING:tensorflow:Using temporary folder as model directory: C:\Users\John\AppData\Local\Temp\tmpahtnt89p
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
2017-02-19 11:53:57.997760: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.007657: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.008177: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.008726: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.009199: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.009591: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.010795: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-19 11:53:58.011384: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From C:\Users\John\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:521: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.

------------------
(program exited with code: 0)

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: Windows 10
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32

Installed version of CUDA and cuDNN: 
???

If installed from binary pip package, provide:

1. A link to the pip package you installed:
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl (to fix the BestSplits" error)

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
1.0.0-rc2

**Comment by headdab** [comment] 2017-02-19 21:24
I get very similar behavior under ubuntu 16.10 with v1.0.0.
As a result, many of the tutorials fail - I don't think I've gotten any that rely on contrib.learn to work.

**Comment by aselle** [comment] 2017-02-20 00:17
Are you sure it actually failed? Those all look like warnings.

**Comment by headdab** [comment] 2017-02-20 00:56
I just redid this experiment.  I copied the code from the page mentioned above, i.e.

> cat line2.py

import tensorflow as tf
# NumPy is often used to load, manipulate and preprocess data.
import numpy as np

# Declare list of features. We only have one real-valued feature. There are many
# other types of columns that are more complicated and useful.
features = [tf.contrib.layers.real_valued_column("x", dimension=1)]

# An estimator is the front end to invoke training (fitting) and evaluation
# (inference). There are many predefined types like linear regression,
# logistic regression, linear classification, logistic classification, and
# many neural network classifiers and regressors. The following code
# provides an estimator that does linear regression.
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features)

# TensorFlow provides many helper methods to read and set up data sets.
# Here we use `numpy_input_fn`. We have to tell the function how many batches
# of data (num_epochs) we want and how big each batch should be.
x = np.array([1., 2., 3., 4.])
y = np.array([0., -1., -2., -3.])
input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x}, y, batch_size=4,
                                              num_epochs=1000)

# We can invoke 1000 training steps by invoking the `fit` method and passing the
# training data set.
estimator.fit(input_fn=input_fn, steps=1000)

# Here we evaluate how well our model did. In a real example, we would want
# to use a separate validation and testing data set to avoid overfitting.
estimator.evaluate(input_fn=input_fn)

and ran it using:

> python line2.py

and got warning like above, i.e.

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpnvvddpq0
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/estes/.virtualenv/tf/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /home/estes/.virtualenv/tf/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.

On the getting started page it says:

When run, it produces

    {'global_step': 1000, 'loss': 1.9650059e-11}

That output doesn't exist anywhere within the output generated.  Thus, I assume it failed.
I just started learning TF today, so could be missing something.

I used the pip-based install for a non-GPU config with python3; in a virtual environment which has been 'activated'.  There were no complexities during the install process as described on the getting started page.

**Comment by skimmy12** [comment] 2017-02-20 05:56
It's a warning.
There's a typo in the sample code.

original
estimator.evaluate(input_fn=input_fn)

fix:
print(estimator.evaluate(input_fn=input_fn))

**Comment by microtony** [comment] 2017-02-20 06:03
Any idea where we can find this documentation md in the repo to fix it? I cannot match the structure of the tensorflow.org website and the g3doc directory here.

**Comment by Splaktar** [comment] 2017-02-25 21:39
I looked around for the markdown to update to fix this as well, but it doesn't appear to be on GitHub.

**Comment by MrTotoro** [comment] 2017-02-26 09:09
我也遇到了同样的问题， 应该怎么解决啊

**Comment by MrTotoro** [comment] 2017-02-26 09:12
I get the same problem under  win10

**Comment by bingq** [comment] 2017-02-28 21:40
get the same problem under win 10; but if executing line by line under interactive python, can get the result with the final line : 

.......
INFO:tensorflow:Starting evaluation at 2017-02-28-21:32:38
INFO:tensorflow:Restoring parameters from C:\Users\geldqb\AppData\Local\Temp\tmp772n4s7z\model.ckpt-1000
INFO:tensorflow:Finished evaluation at 2017-02-28-21:32:39
INFO:tensorflow:Saving dict for global step 1000: global_step = 1000, loss = 4.51237e-09
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
{'loss': 4.5123736e-09, 'global_step': 1000}

**Comment by chaiwa-berian** [comment] 2017-03-05 18:51
@skimmy12 Please fix this typo in the tutorial, and also the "warnings" are so confusing to newbies like me!  I couldn't even figure out the relationship between the warning and the actual fix! :) Someone to fix that as well? Thanks

**Comment by gunan** [comment] 2017-03-10 08:02
You can find the document right here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/get_started/get_started.md

**Comment by David-Petretta** [comment] 2017-04-02 09:09
To diable the warning add

tf.logging.set_verbosity(tf.logging.ERROR)

**Comment by David-Petretta** [comment] 2017-04-02 09:11
Warning can be disabled with this:

tf.logging.set_verbosity(tf.logging.ERROR)

**Comment by QQRider** [comment] 2017-04-02 13:03
I got an error when running this example code, it said CUDA_ERROR_OUT_OF_MEMORY

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpglsJ8i
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7085
pciBusID 0000:03:00.0
Total memory: 5.92GiB
Free memory: 5.67GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:03:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 5.92G (6357843968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:03:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Out of range: RandomShuffleQueue '_1_enqueue_input/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: random_shuffle_queue_DequeueUpTo = QueueDequeueUpToV2[component_types=[DT_INT64, DT_DOUBLE, DT_DOUBLE, DT_DOUBLE], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](enqueue_input/random_shuffle_queue, random_shuffle_queue_DequeueUpTo/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: RandomShuffleQueue '_1_enqueue_input/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: random_shuffle_queue_DequeueUpTo = QueueDequeueUpToV2[component_types=[DT_INT64, DT_DOUBLE, DT_DOUBLE, DT_DOUBLE], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](enqueue_input/random_shuffle_queue, random_shuffle_queue_DequeueUpTo/n)]]
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
{'loss': 4.6558966e-07, 'global_step': 1000}

**Comment by gunan** [comment] 2017-04-03 04:47
@QQRider Your error message is different.
Yours is actually a failure due to your code.
`CUDA_ERROR_OUT_OF_MEMORY` means, well, you are out of GPU memory, as it suggests.
You are allocating 5.92 GBs of GPU memory, and it fails as there is not enough memory on your GPU.
Please reach out to stackoverflow if you need more help with that.

**Comment by trd714** [comment] 2017-04-05 10:26
@gunan QQRider has the same issue as I described at https://github.com/tensorflow/tensorflow/issues/7680#issuecomment-290251024. TensorFlow tries to allocate the total GPU memory, not the free one.

**Comment by gunan** [comment] 2017-04-05 18:07
This is just a different issue. I want to keep the conversation about the initial issue, which is the CPU instruction set warnings. No errors are reported on the initial message.

Looks like initial problem reported by @avantol already has some suggestions to resolve. I will close this issue.

**Closed by gunan** 2017-04-05 18:07 UTC
Labels: stat:awaiting response, type:support

**Comment by skonto** [comment] 2017-04-06 12:30
@QQRider just add this line to the example early at the top:
config = tf.contrib.learn.RunConfig(gpu_memory_fraction=0.05)
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features, config=config)
The percentage depends on your card memory... my card had onyl a small fraction free so I used this small number and the example worked fine.

**Comment by siarez** [comment] 2017-04-12 01:25
I have the same issue on OSX. Warnings I get:
_WARNING:tensorflow:Using temporary folder as model directory: /var/folders/y6/h36z2y61059c6_9bqpb2f_9r0000gn/T/tmpfmi8rrr8
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /Users/siavash/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From /Users/siavash/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32._

**Comment by bharadwajdhornala** [comment] 2020-03-16 11:34
Hi @avantol @headdab @aselle @skimmy12 @microtony 
I am trying to test the SketchModelling code,but stuck with error. I have tried adding
sess.run(tf.local_variables_initializer())
sess.run(tf.global_variables_initializer()) but did not solve the error. Please suggest

(SKetchModelling) C:\GenAssi\SketchModeling\Network\code\MonsterNet>python main.py --test --data_dir C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\ --train_dir C:\GenAssi\SketchModeling\Checkpoint\Chair\ --test_dir C:\GenAssi\SketchModeling\chair_results
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
start running...
Loading testing data...
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Building network...
Testing...
W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-S-0.png : The system cannot find the file specified.

W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-F-0.png : The system cannot find the file specified.

Traceback (most recent call last):
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
return fn(*args)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
status, run_metadata)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\contextlib.py", line 66, in exit
next(self.gen)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
[[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main.py", line 153, in
tf.app.run()
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "main.py", line 142, in main
monnet.test(sess, views, num_test_shapes)
File "C:\GenAssi\SketchModeling\Network\code\MonsterNet\monnet.py", line 471, in test
names,results,errors,images = sess.run([self.names, self.results, self.errors, self.pngs])
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
run_metadata_ptr)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
feed_dict_string, options, run_metadata)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
target_list, options, run_metadata)
File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
[[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]**
