### ISSUE TITLE
No Rollback after "cifar10_train.py" canceled

### ISSUE THREAD

**Issue by NexYY** [tensorflow/tensorflow#363] opened 2015-11-26 17:56 UTC
Hi,

I noticed than on both Ubuntu and Mac OSX there is no handling of cancelling (rollback?) the cifar10-set download process of the cifar10_train.py via ctrl+c.

If the process was once canceled you will be incapable of running the script again. The following error will be issued:

```
Traceback (most recent call last):
  File "cifar10_train.py", line 138, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 134, in main
    train()
  File "cifar10_train.py", line 69, in train
    images, labels = cifar10.distorted_inputs()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10/cifar10.py", line 166, in distorted_inputs
    raise ValueError('Failed to find file: ' + f)
ValueError: Failed to find file: /tmp/cifar10_data/cifar-10-batches-bin/data_batch_1.bin
```

**Comment by vincentvanhoucke** [comment] 2015-11-26 20:31
Checking for integrity of all the files would be tedious. We could provide an option to always re-download, which might make DOSing the source web site a little too easy if people get used to enabling it.
The simple 'rm -rf /tmp/cifar10_data' is a natural way to deal with this, so I'd be inclined not to do anything here.

**Comment by NexYY** [comment] 2015-11-27 05:59
I think atleast a md5sum-check shouldn't be surcharged. 
But this isn't the point.
There is on neither of my systems a /tmp/cifar10_data/ directory, despite the error. Deduce from this fact "rm-rf /tmp/cifar10_train.py" hasn't worked for me.

**Comment by vrv** [comment] 2015-12-01 19:06
I'm not sure exactly what the problem is:

https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/models/image/cifar10/cifar10.py#L484 

Can you instrument that code and let us know if something is not behaving as expected?

**Comment by NexYY** [comment] 2015-12-03 13:20
I am so sorry, "rm -rf /tmp/cifar10_data" didn't work due to a miss configuration on my system.

However I still think a checksum check should me implemented. This scripts is mainly used by newbies following the tensorflow cifar tutorial. It should be beginner friendly and not require deep research and terminal working.

**Comment by tegg89** [comment] 2016-10-06 04:10
Go to /tmp, where is all the way outside of your directory. There you could find cifar10_train and cifar10_data folders. Inside cifar10_data folder, damaged cifar-10-binary.tar.gz file is located. The cifar10_train.py keep recognize this damaged file as intact one, error message keep shown. 
Therefore you should remove the cifar10_train and cifar10_data folders and re-python cifar10_train.py.

**Comment by Sunnysgw** [comment] 2017-04-19 08:06
I‘m afraid that it's too late to say something. I think that maybe the data doesn't exists in your slave nodes.

**Comment by itsmeolivia** [comment] 2017-06-16 21:26
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by itsmeolivia** 2017-06-16 21:26 UTC
Labels: stat:contributions welcome

**Comment by JerRyL2017** [comment] 2017-11-28 17:46
yeah I met the same issue as you.
And I guess this is because I download it for a while but not perfectly,that means my computer have cifar-10 but it's bad.So,i get to
/tmp/cifar10_data/
and I delect anything about cifar-10

after that I get back to cifar10_train,it worked !
