### ISSUE TITLE
ipykernel_launcher.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#52199] opened 2021-09-30 13:16 UTC
![1](https://user-images.githubusercontent.com/26819449/135461638-7520ab41-8310-4c5f-8016-2d9b4609e205.JPG)
 The error pops out ipykernel_launcher.py: error: unrecognized arguments.
Can you just tell me why I am getting this error. I can't share the code with you.
I can fix it on my own just tell me why I am getting this Error.
Thank You.

**Comment by mohantym** [comment] 2021-10-01 10:35
Hi @starboyvarun! Please check out similar issue from [here](https://stackoverflow.com/questions/48796169/how-to-fix-ipykernel-launcher-py-error-unrecognized-arguments-in-jupyter). You can post your  other support queries on [Stackoverflow](https://stackoverflow.com/) . For Tensorflow support queries , You can post in [forum ](https://discuss.tensorflow.org/)to  for Tensorflow support queries. Closing this issue as it is not a bug or feature request in  Tensorflow Repository. Thanks!

**Closed by mohantym** 2021-10-01 10:35 UTC
Labels: type:others
