### ISSUE TITLE
 about bottleneck_input = tf.placeholder_with_default ? 

### ISSUE THREAD

**Issue by Rmuli** [tensorflow/tensorflow#29568] opened 2019-06-09 04:41 UTC
In the original retrain.py:
bottleneck_input = tf.placeholder_with_default(
bottleneck_tensor, shape=[batch_size, bottleneck_tensor_size],
name='BottleneckInputPlaceholder')
Changed to:
bottleneck_input = tf.placeholder(
tf.float32, shape=[batch_size, bottleneck_tensor_size], name='BottleneckInputPlaceholder')

After training, check the parameters in retrained_graph.pb.
Utilize:
import tensorflow as tf
import os

model_name = 'retrained_graph.pb'
def create_graph():
with tf.gfile.FastGFile(os.path.join(model_name), 'rb') as f:
graph_def = tf.GraphDef()
graph_def.ParseFromString(f.read())
create_graph()

tensor_name_list = [tensor.name for tensor in tf.get_default_graph().as_graph_def().node]
for tensor_name in tensor_name_list:
print(tensor_name,'\n')

Before BOTTLENECK_TENSOR_NAME = 'pool_3/_reshape:0' was discovered, all the parameters were missing. Why?

**Comment by achandraa** [comment] 2019-06-11 10:43
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact code to reproduce the issue included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment] 2019-06-17 08:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-06-17 08:30 UTC
Labels: comp:ops, stat:awaiting response, type:support
