### ISSUE TITLE
Exception when concatenating empty flattened layer

### ISSUE THREAD

**Issue by cserpell** [tensorflow/tensorflow#42376] opened 2020-08-14 20:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, attached in colab.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab & local Ubuntu 20.04 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tried
- TensorFlow installed from (source or binary): Colab: bundled, local: using pip install
- TensorFlow version (use command below): Colab: v2.3.0-0-gb36436b087, local: 2.2.0
- Python version: local: 3.8.2

**Describe the current behavior**
Using keras bundled with tensorflow, from one input with shape (None, num > 0) and another input with shape (None, num2 > 0, 0), the second is flattened, obtaining shape (None, 0), and, when trying to concatenate both, it fails during training because it assumes the shape of the second has double number of rows. Interestingly, the summary description of the model after compiling is correct. A minimum code example is in this [colab](https://colab.research.google.com/drive/1oSFd_4MBvX0-e3-S3PEpnZeJyz_RNSAY?usp=sharing).

The exception in colab is,
```
InvalidArgumentError:  ConcatOp : Dimensions of inputs should match: shape[0] = [5,1] vs. shape[1] = [10,0]
	 [[node functional_5/concatenate_2/concat (defined at <ipython-input-3-f5c5cd6d4c13>:29) ]] [Op:__inference_train_function_1468]

Function call stack:
train_function
```
While locally, I get
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 1 must match. Input 1 has shape [256 0] and doesn't match input 0 with shape [128 10].
	 [[{{node training/Adam/gradients/gradients/concatenate_1/concat_grad/ConcatOffset}}]]
```

**Describe the expected behavior**
The flattened version of the input with a zero dimension should have the same number of rows.

**Standalone code to reproduce the issue**
[Colab example](https://colab.research.google.com/drive/1oSFd_4MBvX0-e3-S3PEpnZeJyz_RNSAY?usp=sharing).

**Other info / logs**
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1096                 batch_size=batch_size):
   1097               callbacks.on_train_batch_begin(step)
-> 1098               tmp_logs = train_function(iterator)
   1099               if data_handler.should_sync:
   1100                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    838         # Lifting succeeded, so variables are initialized and we can run the
    839         # stateless function.
--> 840         return self._stateless_fn(*args, **kwds)
    841     else:
    842       canon_args, canon_kwds = \

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2827     with self._lock:
   2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 
   2831   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  ConcatOp : Dimensions of inputs should match: shape[0] = [5,1] vs. shape[1] = [10,0]
	 [[node functional_5/concatenate_2/concat (defined at <ipython-input-3-f5c5cd6d4c13>:29) ]] [Op:__inference_train_f
```

**Comment by cserpell** [comment] 2020-08-14 20:43
I noted that changing the Flatten layer to a Reshape((x_extra_data.shape[1] * x_extra_data.shape[2],)) layers works as expected, although it is not ideal to know the shape of data in advance.

**Comment by saikumarchalla** [comment] 2020-08-17 16:23
Was able to reproduce the issue in TF 2.3 and Nightly version. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c4e0e0cb96d88078d9a1ae22b40c38bf/issue.ipynb). Thanks!

**Comment by nikitamaia** [comment] 2021-03-15 14:38
Adding the `contributions welcome` label to this issue for further investigation by the community. If you are interested in working on this issue, please leave a comment and I will assign it to you. Thanks!

**Comment by CyangXu** [comment] 2021-03-21 00:39
I am able to reproduce the issue in TF 2.5. The error message is 
`tensorflow.python.framework.errors_impl.InvalidArgumentError:  ConcatOp : Dimensions of inputs should match: shape[0] = [5,1] vs. shape[1] = [10,0]
         [[node model/concatenate/concat (defined at reproduce.py:29) ]] [Op:__inference_train_function_464]`

I am interested in this issue. Please assign to me if this issue is still available.

**Comment by bhack** [comment] 2021-04-14 12:49
@CyangXu Can you share your analysis/proposal to solve this before opening a PR?

**Comment by CyangXu** [comment] 2021-04-14 18:22
@bhack Based on my investigation, the output size inferred by Keras can be different from that calculated by C++ code. I did some work two weeks ago then got distracted by something else. I will have more things to show by end of this week.

**Comment by bhack** [comment] 2021-04-14 18:26
@CyangXu Ok thanks. Have you already compiled tensorflow in the case the change will involve C ++?

**Comment by CyangXu** [comment] 2021-04-14 18:29
Yes. I built TF from source code. I investigated the issue by printing log from the C++ side.

**Comment by bhack** [comment] 2021-04-14 18:32
Ok send us an update when you are ready.

**Comment by CyangXu** [comment] 2021-04-19 06:34
Take more time than my expectation. Hopefully I can have something to show before Friday.

**Comment by CyangXu** [comment] 2021-04-26 04:04
More progress! In the code to reproduce the issue, when calling `print(model.summary())`,  `extra_layer`'s shape is (None, 10). I believe this shape is produced from [array_ops.reshape()](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/keras/layers/core.py;l=693;drc=56f148ddeb6a571bc78f69fbf23229426ed176ba;bpv=1;bpt=0?q=layers%2Fcore.py). Then when hitting `model.fit(x=[x_data, x_extra_data], y=y_data, epochs=2)` in the reproduction code, we reshape the tensor by [ReshapeOp](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/reshape_op.h;l=104;drc=a41733ae0a093040cacf3aad010786fa6bed5f1b;bpv=1;bpt=0). The output `shape` is (10, 0). In other words, the output shape of "Flatten()" calculated by Keras is different from that calculated by C++ operation. The fixing should be straightforward: we have to unify the result from Keras and that from C++. 

I do have a question: it seems that when reshaping a tensor in Keras, we hit [here](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/ops/array_ops.py;l=61;drc=0b9ff2eb1a097602206c6b29823543768bfb34fe;bpv=1;bpt=0?q=array_ops.py). **Does anyone know where I can find the implementation for that Python function**?

**Comment by bhack** [comment] 2021-04-26 06:48
Array ops are in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc

**Comment by sushreebarsa** [comment] 2021-05-28 15:51
Was able to replicate the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/63e916ab451437a9bc2fda112ac70a94/untitled66.ipynb#scrollTo=b6akEO2SqORI)..Thanks !

**Comment by CyangXu** [comment] 2021-05-31 16:28
Very sorry that I am unable to continue working on this issue due to other things. If anyone is interested in this issue, feel free to take it. The bug's root cause is clear as demonstrated by the comment above.

**Comment by SuryanarayanaY** [comment] 2022-12-27 15:19
The issue is replicating in TF 2.11V.However to be more specific the issue exists with only Graph mode `model.compile(...,run_eagerly=False)`.If we change to eager execution `model.compile(...,run_eagerly=True)` there is no Error.Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/2c8d75fd3b19d5d7d620c913d01343e5/42376_2-11.ipynb#scrollTo=ioearmI9DnDS).

**Closed** 2023-01-12 06:39 UTC
Labels: stat:contributions welcome, stat:awaiting response, type:bug, stalled, comp:keras, TF 2.10
