### ISSUE TITLE
tensotflow website

### ISSUE THREAD

**Issue by HymEric** [tensorflow/tensorflow#31225] opened 2019-08-01 07:27 UTC
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/guide/keras

## Description of issue (what needs changing):

can't open URL

**Comment by Konstantin-Bogdanoski** [comment] 2019-08-01 07:42
This might help:
[https://www.tensorflow.org/guide/keras](https://www.tensorflow.org/guide/keras)
***
**Explanation:**
tensorflow.org/~~tutorials~~/guide/keras  =>  tensorflow.org/guide/keras

**Comment by HymEric** [comment] 2019-08-01 07:52
Tnak you. But in the www.tensorflow.org page thr URL is https://www.tensorflow.org/tutorials/guide/keras. Maybe it can be updated.

**Comment by gadagashwini** [comment] 2019-08-02 09:48
> Tnak you. But in the [www.tensorflow.org](http://www.tensorflow.org) page thr URL is https://www.tensorflow.org/tutorials/guide/keras. Maybe it can be updated.

@HymEric Can you please tell us, where exactly the link is present? Thanks!

**Comment by HymEric** [comment] 2019-08-02 10:24
![image](https://user-images.githubusercontent.com/26487821/62362185-0906df80-b54f-11e9-998e-17d4e6ffcf4d.png)

**Comment by HymEric** [comment] 2019-08-02 10:26
In Chinses language.
![image](https://user-images.githubusercontent.com/26487821/62363970-f8586880-b552-11e9-8828-7241ab7d6877.png)

**Comment by gadagashwini** [comment] 2019-08-05 05:38
@HymEric Thanks for finding the issue.

**Comment by gadagashwini** [comment] 2019-08-05 05:39
The issue is [here](https://www.tensorflow.org/tutorials/keras). Thanks!

**Comment by lamberta** [comment] 2019-08-09 17:48
Thanks. This is fixed with https://github.com/tensorflow/docs/pull/914
The site will be updated on the next Chinese translations push.
If you're interested in contributing to the community translations, see https://www.tensorflow.org/community/contribute/docs#community_translations and join the docs-zh-cn@tensorflow.org list :)

**Closed by lamberta** 2019-08-09 17:48 UTC
Labels: comp:keras, type:docs
