### ISSUE TITLE
tf.matrix_band_part uses int64 as default type for num_lower and num_upper

### ISSUE THREAD

**Issue by carltonwang** [tensorflow/tensorflow#17518] opened 2018-03-07 21:06 UTC
tf.matrix_band_part uses int64 as default type for num_lower and num_upper.
But it is weird, because most return from tf.shape() and tf.size() is int32.

**Comment by tensorflowbutler** [comment] 2018-03-08 07:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by carltonwang** [comment] 2018-03-09 07:04
leave them as N/A

**Comment by cy89** [comment] 2018-03-15 22:49
@carltonwang I don't understand the issue. Is this a bug, a feature request, or a suggestion that we change the interfaces? What do you mean by the default type? The docs suggest that tf.matrix_band_part accepts either int32 or int64 for num_lower and num_upper.

**Comment by carltonwang** [comment] 2018-03-27 21:12
It is a suggestion, because most methods accept float32 and int32 as default types, and tf.size() and tf.shape() also return int32 by default. But why tf.matrix_band_part() accept int64 by default? 
For example, if I try tf.matrix_band_part(input, 0,1), both 0 and 1 will be treated as int64
If I try tf.matrix_band_part(input, 0, tf.shape(xxx)[xxx]), there will be an err, because 0 is treated as int64, but tf.shape() returns int32.
Understand?

**Comment by carltonwang** [comment] 2018-03-31 22:21
```
a = tf.random_normal([5, 5])
b = tf.random_normal([10, 10])
c = tf.matrix_band_part(input=b, num_lower=0, num_upper=tf.shape(a)[0])

```

**Comment by tensorflowbutler** [comment] 2018-04-15 18:27
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment] 2018-05-14 00:56
The issue is because in ops registration the default value (see: `Tindex`) has been set as INT64:
https://github.com/tensorflow/tensorflow/blob/64bb1de61377f12859a719448b65b452b03047a7/tensorflow/core/ops/array_ops.cc#L853-L859

Changing the default to INT32 will address the issue and the code snippet should work fine. However, this is likely behavior-changing. Not sure if we should change it or not.

**Comment by tensorflowbutler** [comment] 2018-05-28 18:34
Nagging Assignee @hawkinsp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hawkinsp** [comment] 2018-05-29 12:45
Sorry, I didn't notice this issue was assigned to me until now. I changed the op from a hardwired `int64` to a choice of `int32` or `int64` in a previous PR. Previously, only `int64` was supported.

The error you are seeing is because:
a) tf.shape() returns an int64
b) the types of num_lower and num_upper must be the same.
c) the python `0` gets passed as an int32 by default.

There's two easy workarounds: either explicitly pass the 0 value as a numpy int64 value:
```
import numpy as np
import tensorflow as tf

a = tf.random_normal([5, 5])
b = tf.random_normal([10, 10])
c = tf.matrix_band_part(input=b, num_lower=np.int64(0), num_upper=tf.shape(a)[0])
```

or tell `tf.shape()` to return an int32 value:
```
import numpy as np
import tensorflow as tf

a = tf.random_normal([5, 5])
b = tf.random_normal([10, 10])
c = tf.matrix_band_part(input=b, num_lower=0, num_upper=tf.shape(a, out_type=tf.int32)[0])
```

As to the larger usability question of "should TensorFlow perform implicit promotions for integers", it's probably better to open a new PR for that.

**Closed by hawkinsp** 2018-05-29 12:45 UTC

**Comment by hawkinsp** [comment] 2018-05-29 12:46
(I originally had `int64` and `int32` transposed in my previous comment; corrected.)
