### ISSUE TITLE
Error when retraining a saved LSTM model

### ISSUE THREAD

**Issue by wkelongws** [tensorflow/tensorflow#34767] opened 2019-12-02 18:44 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I have a simple and functional custom code to reproduce the issue.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04

- TensorFlow installed from (source or binary):
conda install tensorflow-gpu=2.0.0

- TensorFlow version (use command below):

python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

v2.0.0-rc2-26-g64c3d38 2.0.0

- Python version:
Python 3.7.4

- CUDA/cuDNN version:
 CUDA Version: 10.1
#define CUDNN_MAJOR 7

- GPU model and memory:
nvidia Quadro GV100 - 32478MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)

output `env_info.sh` attached. 

**Describe the current behavior**

1. Train a simple LSTM model using tf.keras API
2. save the model to file as `SavedModel` format. `model.save('saved_model', save_format='tf')`
3. In a separate script (without access to the model definition), load the saved model: `model = tf.keras.models.load_model('saved_model1')`
4. continue training the reloaded model: `model.fit(data_x,data_y,batch_size=64,epochs=2)`
The following error encountered:

`LookupError: No gradient defined for operation 'while' (op type: While)`

**Describe the expected behavior**

expect the LSTM `SavedModel` can be loaded and retrained in a separated script without access to the model definition.

**Code to reproduce the issue**
Script to train and save the model:
```
import tensorflow as tf
import numpy as np

def Model_Functional_API():

    inputs = tf.keras.Input(shape=(3, 2))
    encoder = tf.keras.layers.LSTM(10,return_sequences=True)
    encoder_outputs = encoder(inputs)
    projection_layer = tf.keras.layers.Dense(2)
    preds = projection_layer(encoder_outputs)
    model = tf.keras.Model(inputs,preds)

    return model

def Model_Sequence():

    model = tf.keras.Sequential()
    model.add(tf.keras.layers.LSTM(10,return_sequences=True))
    model.add(tf.keras.layers.Dense(2))

    return model

# model = Model_Functional_API()
model = Model_Sequence()
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
            loss='mean_squared_error')

data_x = np.random.random([64,3,2])
data_y = np.random.random([64,3,2])

model.fit(data_x,data_y,batch_size=64,epochs=2)

model.save('saved_model', save_format='tf')
# model.save('saved_model.h5')
```
Script to load and retrain the model (this is where the error encountered):
```
import tensorflow as tf
import numpy as np

model = tf.keras.models.load_model('saved_model')
# model = tf.keras.models.load_model('saved_model.h5')

data_x = np.random.random([64,3,2])
data_y = np.random.random([64,3,2])

model.fit(data_x,data_y,batch_size=64,epochs=2)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`tf_env.txt` and the ouput error message are attached.
[error_log.txt](https://github.com/tensorflow/tensorflow/files/3912802/error_log.txt)
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3912803/tf_env.txt)

**Comment by oanush** [comment] 2019-12-03 05:29
@wkelongws ,
When tried running the code for `TF-gpu-2.0 `I did not face any error, kindly find the [link](https://colab.sandbox.google.com/gist/oanush/07748f478033aef83a35e5db5e1401ff/34767.ipynb) of colab gist.Thanks!

**Comment by wkelongws** [comment] 2019-12-03 18:02
@oanush 
"In a separate script (without access to the model definition)", load the saved model for retraining, then you would have the error.
In your colab link, after finishing the second cell, please restart runtime then try running JUST the third cell, that is where the aforementioned error occurred.

**Comment by oanush** [comment] 2019-12-12 08:51
@wkelongws ,
Thank you, was able to reproduce the error. I have updated the link of gist.

**Comment by ymodak** [comment] 2020-02-04 21:17
Potentially duplicate of #34211

**Comment by ujjwal-ai** [comment] 2020-02-18 19:31
Is there any update on this ??

**Comment by jvishnuvardhan** [comment] 2020-02-19 00:21
@wkelongws On GPU, I can still reproduce the issue with `tf-nightly-gpu`. However, with CPU, there is no issue. Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/762bea845c3ce926e8dc93863f1b1b3e/untitled825.ipynb) with CPU.
Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/20a72b25a5c16f98438d30b08351d1fe/34767.ipynb) with GPU.

With GPU, the error is different from the reported error. Please check below for full error trace with `tf-nightly-gpu`. Thanks!

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-9ba863f98283> in <module>()
      2 import numpy as np
      3 
----> 4 model = tf.keras.models.load_model('saved_model')
      5 # model = tf.keras.models.load_model('saved_model.h5')
      6 

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _set_input_attrs(self, inputs)
   2479         input_shape = (None,)
   2480       else:
-> 2481         input_shape = (None,) + tuple(inputs.shape[1:])
   2482       self._build_input_shape = input_shape
   2483 

AttributeError: 'list' object has no attribute 'shape' 
```

**Comment by wkelongws** [comment] 2020-02-20 00:49
@jvishnuvardhan  Thanks for the update. 
By commenting/uncommenting the corresponding lines in the GPU gist that you provided above I got below findings:

scenario 1: model = Model_Functional_API()  +  model.save('saved_model', save_format='tf')
PASS

scenario 2: model = Model_Sequence()  +  model.save('saved_model', save_format='tf')
FAIL

scenario 3: model = Model_Functional_API()  +  model.save('saved_model.h5')
PASS

scenario 4: model = Model_Sequence()  +  model.save('saved_model.h5')
PASS

(Note: In each scenario, restart runtime then run JUST the third cell. Again, this is for mimicking a situation where the inference script has no access to the model definition.)

So looks like the `tf-nightly-gpu` fixed the previous `No gradient defined for operation 'while'` error but still have some bugs remaining with aforementioned scenario 2.

**Comment by jvishnuvardhan** [comment] 2020-03-03 22:46
This issue still exists with `scenario 2` mentioned above. The trace with recently `tf-nightly` is as follows. This trace is for our reference. Thanks!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    210   try:
--> 211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:

21 frames
TypeError: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, None, 2])

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:
--> 213     raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
    214   except ValueError as e:
    215     raise ValueError("Error converting %s to a TensorShape: %s." % (arg_name,

TypeError: Error converting shape to a TensorShape: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, None, 2]).
```

**Comment by jvishnuvardhan** [comment] 2020-03-23 20:17
@wkelongws Can you please check this issue. I think this was resolved for `scenario 2`. I was not able to reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/20a72b25a5c16f98438d30b08351d1fe/34767.ipynb). Thanks!

Please close the issue if this was resolved for you. thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-02 15:23
@wkelongws Can you please confirm whether it is resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-08 00:20
Closing this issue as this was resolved in recently `tf-nightly`. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2020-04-08 00:20 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:bug

**Comment by pabloi09** [comment] 2020-04-28 16:36
Hi, I am having the same issue while trying to load a model with multiple inputs.
![model](https://user-images.githubusercontent.com/33988623/80512979-a415d400-897e-11ea-945f-0fcf4d4e7af4.png)
1.  I save the whole model with a ModelCheckpoint callback
```
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                  save_weights_only=False,
                                                  verbose=0,
                                                  save_freq=4542*10)
```
2. In a new colab session I try to load it with
```
checkpoint_dir = os.path.dirname(checkpoint_path)
model = tf.keras.models.load_model(checkpoint_dir)
```

The trace: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    210   try:
--> 211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:

22 frames
TypeError: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, 2048])

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:
--> 213     raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
    214   except ValueError as e:
    215     raise ValueError("Error converting %s to a TensorShape: %s." % (arg_name,

TypeError: Error converting shape to a TensorShape: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, 2048]).
```

**Comment by jvishnuvardhan** [comment] 2020-04-28 16:59
@pabloi09 Can you please open a new issue and provide a simple standalone code to reproduce the error. Thanks!

**Comment by pabloi09** [comment] 2020-04-29 07:38
Done ! https://github.com/tensorflow/tensorflow/issues/39013

**Comment by nikita1andreev** [comment] 2020-05-12 14:21
> @jvishnuvardhan Thanks for the update.
> By commenting/uncommenting the corresponding lines in the GPU gist that you provided above I got below findings:
> 
> scenario 1: model = Model_Functional_API() + model.save('saved_model', save_format='tf')
> PASS
> 
> scenario 2: model = Model_Sequence() + model.save('saved_model', save_format='tf')
> FAIL
> 
> scenario 3: model = Model_Functional_API() + model.save('saved_model.h5')
> PASS
> 
> scenario 4: model = Model_Sequence() + model.save('saved_model.h5')
> PASS
> 
> (Note: In each scenario, restart runtime then run JUST the third cell. Again, this is for mimicking a situation where the inference script has no access to the model definition.)
> 
> So looks like the `tf-nightly-gpu` fixed the previous `No gradient defined for operation 'while'` error but still have some bugs remaining with aforementioned scenario 2.

I installed "tf-nightly-gpu" and checked scenario 3: model = Model_Functional_API() + model.save('saved_model.h5').
It is really work, thanks!

But, fit after loading model became very slow.
When i create model like "modelC = Model(inputs=[if1,if2,if3,if4], outputs=out)", fit from cold start was about 4-5 min, on next fit it was 3 min.

Fit on loaded model show ETA about 30 min.
Recompiliing after load in has no effect.

**Comment by dimitree54** [comment] 2020-06-09 20:57
I also had issue descibed by @pabloi09  (TypeError when trying to save/load Sequential model starting with concat layer, and taking list of tensors as input). But then I noticed new warning (it seems that this warning has appeared only in tf 2.2):
`WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'list'> input: ... Consider rewriting this model with the Functional API.`
I have replaced Sequential model with Functional API Model and TypeError during model_load was solved.
