### ISSUE TITLE
train_speech_model.ipynb TUTORIAL with colab not working

### ISSUE THREAD

**Issue by nahsam** [tensorflow/tensorflow#38227] opened 2020-04-04 20:23 UTC
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
 I am trying to use this to train a set, the base tutorial will not compile the train.py section. I am copying and pasting the commands to colab to test and get a MODULE NOT FOUND ERROR.
I have used this in the past about a month or so ago and it worked fine. Something must have been changed recently to cause this issue.

Here is the output I get when trying to run the "Begin Training" section:

2020-04-04 20:08:28.890032: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "tensorflow/tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
  File "/content/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by nahsam** [comment] 2020-04-04 20:35
I found that line 35 in /content/tensorflow/tensorflow/examples/speech_commands/input_data.py is no the same using the git in the instructions of the tutorial. I changed it manually to match what is currently in the git hub and it compiles further but is still having issues finding "contrib_audio"

**Comment by llllGEM** [comment] 2020-04-05 12:09
On my side I get another error about the dependencies not found

ERROR: Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729 (from versions: 2.2.0.dev20200210, 2.2.0.dev20200211, 2.2.0.dev20200212, 2.2.0.dev20200215, 2.2.0.dev20200216, 2.2.0.dev20200217, 2.2.0.dev20200218, 2.2.0.dev20200226, 2.2.0.dev20200227, 2.2.0.dev20200228, 2.2.0.dev20200229, 2.2.0.dev20200301, 2.2.0.dev20200302, 2.2.0.dev20200303, 2.2.0.dev20200304, 2.2.0.dev20200305, 2.2.0.dev20200306, 2.2.0.dev20200307, 2.2.0.dev20200308, 2.2.0.dev20200309, 2.2.0.dev20200310, 2.2.0.dev20200311, 2.2.0.dev20200312, 2.2.0.dev20200313, 2.2.0.dev20200314, 2.2.0.dev20200315, 2.2.0.dev20200316, 2.2.0.dev20200317, 2.2.0.dev20200318, 2.2.0.dev20200319, 2.2.0.dev20200323, 2.2.0.dev20200324, 2.2.0.dev20200325, 2.2.0.dev20200327, 2.2.0.dev20200328, 2.2.0.dev20200329, 2.2.0.dev20200330, 2.2.0.dev20200331, 2.2.0.dev20200401, 2.2.0.dev20200402, 2.2.0.dev20200403, 2.2.0.dev20200404, 2.2.0.dev20200405)
ERROR: No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729

can someone provide any help on this issue ?

**Comment by saikumarchalla** [comment] 2020-04-06 12:48
@llllGEM  Currently, Tf-nightly-gpu version is 2.2.0.dev20200405, For additional information please refer this [link](https://pypi.org/project/tf-nightly-gpu/).
To install tf 1.15, try pip install tensorflow==1.15. Thanks!

**Comment by saikumarchalla** [comment] 2020-04-06 13:04
@nahsam  Could you please provide the TF version as it helps us to reproduce the issue.Thanks!

**Comment by nahsam** [comment] 2020-04-07 00:26
Using version 2.x gives those results

**Comment by saikumarchalla** [comment] 2020-04-08 06:02
Was able to reproduce the issue. Please find the Gist [here](https://colab.research.google.com/gist/saikumarchalla/37b418d191f58e32aea10803d45b206e/train-simple-audio-recognition-model.ipynb). Thanks!

**Comment by ymodak** [comment] 2020-04-09 00:54
TF nightly installs TF 2.x version and `contrib` module is no longer part of TF from 2.X. 
Also we don't save pipy packages of older tf nightly versions.
You can try using stable TF 1.x versions for using `contrib` module.
Thanks!

**Comment by nahsam** [comment] 2020-04-09 01:11
I have be able to get version 1.x to complete but the tensor board doesn't
work anymore. It makes it difficult to gauge progress. Can you try and run
it on version 1 and see if tensor board works for you?

**Comment by ymodak** [comment] 2020-04-09 09:07
If you can open a new issue and explain the tensorboard problem perhaps we can take a look and assist you. Reason being, we want to keep one issue thread specific to one topic so that it helps for users referring it in future. Thanks!

**Comment by ymodak** [comment] 2020-04-19 04:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2020-04-19 04:19 UTC
Labels: TF 2.0, comp:micro, type:bug
