### ISSUE TITLE
Check failure when running tensorflow.python.ops.gen_math_ops.dense_bincount

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59087] opened 2023-01-04 07:14 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
Check failure when running tensorflow.python.ops.gen_math_ops.dense_bincount probably because of feeding empty tensor as input.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_math_ops
try:
  input_tensor = tf.constant([], shape=[0], dtype=tf.int32,)
  input = tf.identity(input_tensor)
  weights = []
  size = 10
  binary_output = True
  out = gen_math_ops.dense_bincount(input=input,weights=weights,size=size,binary_output=binary_output,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-04 02:11:11.516596: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
Aborted

```
```
</details>

**Comment by tilakrayal** [comment] 2023-01-04 16:58
@nimashiri,
I can see the difference in behaviour on colab runtime CPU vs GPU. On the [CPU](https://colab.research.google.com/gist/tilakrayal/3c41a66ecf53db6aa3579cda8cbee760/untitled836cpu.ipynb) the code was executed without any issues/error and on [GPU](https://colab.research.google.com/gist/tilakrayal/bd78f0b2ea346e581380a28a66187001/untitled836gpu.ipynb) it is getting crashed. Kindly find the gist. Also please take a look at this [PR](https://github.com/tensorflow/tensorflow/pull/56276) which was raised for the similar issue. Thank you!

**Comment by nimashiri** [comment] 2023-01-04 23:43
> @nimashiri, I can see the difference in behaviour on colab runtime CPU vs GPU. On the [CPU](https://colab.research.google.com/gist/tilakrayal/3c41a66ecf53db6aa3579cda8cbee760/untitled836cpu.ipynb) the code was executed without any issues/error and on [GPU](https://colab.research.google.com/gist/tilakrayal/bd78f0b2ea346e581380a28a66187001/untitled836gpu.ipynb) it is getting crashed. Kindly find the gist. Also please take a look at this [PR](https://github.com/tensorflow/tensorflow/pull/56276) which was raised for the similar issue. Thank you!

Thanks for explaining.

**Comment by nimashiri** [comment] 2023-01-05 03:21
I get illegal memory access when running with another test case on TF v2.10.0
```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_math_ops
try:
  try:
    with tf.device('/CPU'):
      input_tensor = tf.constant(-90652338519106, shape=[4096], dtype=tf.int32,)
      input = tf.identity(input_tensor)
      weights = []
      size = 10
      binary_output = True
      out = gen_math_ops.dense_bincount(input=input,weights=weights,size=size,binary_output=binary_output,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      input = tf.identity(input_tensor)
      input = tf.cast(input, tf.int32)
      weights = []
      results["res_gpu"] = gen_math_ops.dense_bincount(input=input,weights=weights,size=size,binary_output=binary_output,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

The log message:

```
2023-01-04 22:18:29.497997: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-01-04 22:18:29.498018: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Aborted

```
The root cause is the negative integer tensor feed as the first argument.

**Comment by tilakrayal** [comment] 2023-01-10 10:23
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.10, [v2.11](https://colab.research.google.com/gist/tilakrayal/bd78f0b2ea346e581380a28a66187001/untitled836gpu.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7733265a23d62b042c590490b1f1e132/untitled865.ipynb).

**Comment by mihaimaruseac** [comment] 2023-02-07 19:51
@learning-to-play

**Comment by sachinprasadhs** [comment] 2023-02-16 21:24
Hi, The fix for this issue has been implemented to handle the inputs for GPU kernels in the fix here https://github.com/tensorflow/tensorflow/commit/764eae38919b45556373a320af1079ac54e70521.
This will be part of the next one/two releases. Thanks!

**Closed** 2023-02-17 16:30 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, TF 2.11
