### ISSUE TITLE
AttributeError: module 'reader' has no attribute 'ptb_producer'

### ISSUE THREAD

**Issue by jingweimo** [tensorflow/tensorflow#11025] opened 2017-06-24 00:46 UTC
I use anaconda2 python3.5 with tensorflow1.2. I want to test tensorflow on the PennTree bank (ptb) dataset. 

Referring to the ptb codes provided at https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb, I run the code
`reader_test.py`
but got the error:
ERROR: testPtbProducer (__main__.PtbReaderTest)
Traceback (most recent call last):
  File "<ipython-input-15-5eff201b8159>", line 34, in testPtbProducer
       ` x, y = reader.ptb_producer(raw_data, batch_size, num_steps)
`AttributeError: module 'reader' has no attribute 'ptb_producer'
FAIL: testPtbRawData (__main__.PtbReaderTest)
Traceback (most recent call last):
  File "<ipython-input-15-5eff201b8159>", line 28, in testPtbRawData
    self.assertEqual(len(output), 4)
AssertionError: 5 != 4
Ran 3 tests in 0.344s
FAILED (failures=1, errors=1)
An exception has occurred, use %tb to see the full traceback.
SystemExit: <sitecustomize.IPyTesProgram object at 0x000001FF9FADC630>
C:\Users\yl\Anaconda2\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

Then, running the code:
`ptb_word_lm.py`
also produces errors:
  File "C:\Users\yl\Anaconda2\envs\tensorflow-gpu\lib\argparse.py", line 1506, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --model: conflicting option string: --model

Did I do something wrong or miss some steps?

**Comment by skye** [comment] 2017-06-27 15:47
@nealwu can you comment on this or redirect to someone who can? Thanks!

**Comment by nealwu** [comment] 2017-06-28 00:00
a

**Comment by nealwu** [comment] 2017-06-28 00:30
Hi @jingweimo, could you fill out the system information form we provide at https://github.com/tensorflow/models/issues/new? I tried the test and it is working fine for me.

You may also want to try on non-Anaconda Python and also try on Python 2 to see if either of those is the cause of your issue.

**Comment by jingweimo** [comment] 2017-06-30 22:26
@nealwu: Hello! I post the problem encountered with running reader_test.py and ptb_word_lm.py at: https://stackoverflow.com/questions/44855380/tensorflow-runn-error-with-reader-test-py-in-models-tutorials-rnn
You may take a look at the error message. I am not sure if there is something wrong with anaconda environment. I follow the instructions for installing tensorflow-gpu in windows by conda installation. And the installation is free of any problem.

**Comment by nealwu** [comment] 2017-06-30 22:45
What went wrong with `reader_test.py`? It looks like it ran fine to me.

As far as `ptb_word_lm.py`, I don't really know what's going on there. Hopefully someone on StackOverflow will be familiar with the error.

**Comment by jingweimo** [comment] 2017-07-01 00:19
@nealwu : For the `reader_test.py`, it shows that the TensorFlow library wasn't complied to SSE and other instructions. I don't know if that implies some errors. For `ptb_word_lm.py`, it gives the error:
`InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(20, 400), b.shape=(400, 800), m=20, n=800, k=400
                 `

**Comment by jingweimo** [comment] 2017-07-01 00:25
@nealwu : I solved the problem by updating anaconda `(conda update --all)` and then restart my laptop

**Comment by nealwu** [comment] 2017-07-01 00:25
Yes, that means there are a few options you could compile with to boost your speed, but everything ran fine. As far as `ptb_word_lm.py`, I'm not sure unfortunately.

**Comment by nealwu** [comment] 2017-07-01 00:26
Oh, great! Looks like we can close this then.

**Closed by nealwu** 2017-07-01 00:26 UTC
