### ISSUE TITLE
Cuda error: creating context when one is currently active

### ISSUE THREAD

**Issue by SerhanGul** [tensorflow/tensorflow#3612] opened 2016-08-02 16:21 UTC
### Environment info

- Operating System: Ubuntu 14.04, 
- GPU server with 8 **Tesla K80** GPUs,
- Python 2.7 (Anaconda)

Installed version of CUDA and cuDNN: 

- Cuda 7.5, cuDNN v4

If installed from binary pip package, provide:

1. Pip package: GPU-enabled, Python 2.7
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0

### Steps to reproduce
```
import tensorflow as tf
sess = tf.Session()
```

yields the error:
**W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active;**
see the detailed logs below please:

### What have you tried?
1. I checked the output of the `nvidia-smi`. There are other processes run by other users currently. Below is the output.
2. I re-installed tensorflow again using pip, it didn't solve the problem.

```
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:05:00.0     Off |                    0 |
| N/A   33C    P0    59W / 149W |    190MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   30C    P8    30W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:09:00.0     Off |                    0 |
| N/A   25C    P8    27W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:0A:00.0     Off |                    0 |
| N/A   28C    P8    31W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 0000:84:00.0     Off |                    0 |
| N/A   24C    P8    28W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 0000:85:00.0     Off |                    0 |
| N/A   54C    P0   106W / 149W |  11461MiB / 11519MiB |     58%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 0000:88:00.0     Off |                    0 |
| N/A   49C    P0   134W / 149W |  11461MiB / 11519MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 0000:89:00.0     Off |                    0 |
| N/A   69C    P0   131W / 149W |  11462MiB / 11519MiB |     57%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    155948    C   ../../../build/tools/caffe                      82MiB |
|    0    196261    C   .build_release/test/test_all.testbin            81MiB |
|    5     19542    C   python                                       11436MiB |
|    6     18802    C   python                                       11436MiB |
|    7     85515    C   python                                       11437MiB 
```

### Logs 

```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:05:00.0
Total memory: 11.25GiB
Free memory: 11.00GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x2f85bd0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x339e320
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 2 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:09:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x37b5f60
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 3 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:0a:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x3bd1860
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 4 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:84:00.0
Total memory: 11.25GiB
Free memory: 11.16GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x3ff0cd0
Segmentation fault (core dumped)
```

**Comment by SerhanGul** [comment] 2016-08-03 13:36
Ok, by reading through the discussion in [152](https://github.com/tensorflow/tensorflow/issues/152), I figured out that Tensorflow tries to grab all the GPUs it sees from the system. The SegFault probably occurs when there is not enough memory on one or more of the GPUs since Tensorflow tries to grab it anyway.

The workaround in [152](https://github.com/tensorflow/tensorflow/issues/152) is to check nvidia-smi to see which GPUs are free and set CUDA_VISIBLE_DEVICES to these GPUs. When I do this, I do not get any SegFaults error anymore and everthing seems to work fine. I just want to know if there is any way to automate this issue by polling the GPUs beforehand to determine the available ones, or a try-catch kind of script which prevents Tensorflow from segfaulting.

**Comment by poxvoculi** [comment] 2016-08-03 16:31
Closing as duplicate of #152

**Closed by poxvoculi** 2016-08-03 16:31 UTC
Labels: duplicate
