### ISSUE TITLE
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f70dfc46840> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

### ISSUE THREAD

**Issue by aeddung** [tensorflow/tensorflow#38470] opened 2020-04-12 13:18 UTC
I have a problem while trying to do prediction by using LSTM...
Here is a error code: 
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f70dfc46840> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.
However, anyway I have a prediction even though there is error code above.
Is there any solution with this problem? I used Colab gpu for this test. Here is my code.... 
<img width="1178" alt="스크린샷 2020-04-12 오후 10 17 56" src="https://user-images.githubusercontent.com/48937254/79069726-776d8580-7d0b-11ea-8fc2-e9749755d9fc.png">
<img width="1295" alt="스크린샷 2020-04-12 오후 10 18 15" src="https://user-images.githubusercontent.com/48937254/79069733-82c0b100-7d0b-11ea-8eaf-18bd45886f37.png">

**Comment by amahendrakar** [comment] 2020-04-13 14:06
@aeddung,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment] 2020-04-21 11:04
> @aeddung,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-28 07:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-28 07:49 UTC
Labels: stalled, stat:awaiting response
