### ISSUE TITLE
tf.keras accepts incorrect CNN input shapes from tf.data.Dataset when eager execution is disabled

### ISSUE THREAD

**Issue by bfmat** [tensorflow/tensorflow#33074] opened 2019-10-06 00:19 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7
- Device: CPU

**Describe the current behavior**
I am using a `tf.data.Dataset` to train a `tf.keras` model. My CNN input layer size is (72, 96, 1). I find that if I input a tensor with size (96, 72, 1) (note the reversed dimensions), training completes successfully. However, if I enable eager execution, a `ValueError` is produced as expected.

**Describe the expected behavior**
A `ValueError` should be produced in response to the incorrect input shape, whether or not eager execution is enabled.

**Code to reproduce the issue**
NOTE: With the code below, there is no error message. However, uncomment the `tf.enable_eager_execution()` line and you will get a `ValueError`.

```
#!/usr/bin/env python3
  
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

# UNCOMMENT THIS LINE AND YOU WILL GET AN ERROR
# tf.enable_eager_execution()

def tf_dataset():

    def data_gen():
        while True:
            yield np.random.rand(72, 96, 1), np.random.rand(18)

    types = (tf.float64, tf.float64)
    shapes = (tf.TensorShape([None, None, None]), tf.TensorShape([None]))
    dataset = tf.data.Dataset.from_generator(data_gen, types, output_shapes=shapes)
    dataset = dataset.batch(16)
    return dataset

dataset = tf_dataset()

model = tf.keras.Sequential()
# Notice how the input dimensions are mismatched
model.add(layers.InputLayer((96, 72, 1)))
model.add(layers.Conv2D(filters=32, kernel_size=4, strides=4, activation='relu'))
model.add(layers.Conv2D(filters=32, kernel_size=4, strides=4, activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(18, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy')
print(model.summary())
model.fit(dataset, steps_per_epoch=1, epochs=1)
```

**Comment by gadagashwini** [comment] 2019-10-07 10:41
I could reproduce the issue with TF1.14.0 on colab. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/47a1e1726b762a876c0fc29c00e440b9/untitled182.ipynb).

**Comment by gadagashwini** [comment] 2019-10-07 10:49
@bfmat, I tried with TF 1.15.0rc1 but i didn't see ValueError with or without Eager execution. Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/ebbbb7296a5830c3ee0b852c4ec4db6e/untitled183.ipynb). Thanks!

**Comment by bfmat** [comment] 2019-10-07 13:15
@gadagashwini, I re-ran the gist with TensorFlow 2.0 as well, and no error is raised.

It is worth noting that if I change the data shape to (72, 128) instead of (72, 96), an error is raised as expected. However, if I use (72, 97), no error is raised, which is worrying, considering that the tensor size is incorrect as well as the shape.

**Comment by rmothukuru** [comment] 2019-10-09 09:30
@bfmat,
 I could execute with shape (72,128) as well, successfully. Please find the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/591ca795c780d0fcd8ddc88247b5c699/untitled183.ipynb).

**Comment by rmothukuru** [comment] 2019-10-11 07:08
@bfmat,
Can you please refer the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/591ca795c780d0fcd8ddc88247b5c699/untitled183.ipynb) and please let us know if your issue still persists. Thanks!

**Comment by bfmat** [comment] 2019-10-11 16:28
@rmothukuru The Gist exhibits the issue. What I meant is that if you leave the input layer at (96, 72), and set the data shape to (72, 128), it raises an error. However, if you set the data shape to (72, 97) while still leaving the input layer at (96, 72), no error is raised.

**Comment by rmothukuru** [comment] 2019-10-14 09:24
@bfmat,
The error, ` ValueError: Error when checking input: expected input_1 to have shape (96, 72, 1) but got array with shape (72, 97, 1)` is being triggered when `data shape to (72, 97) while still leaving the input layer at (96, 72)`.

The error disappears if the Shape of the Data and the Shape of the Input Layer is the same. For example, Shapes of Input Layer and that of Data is `(72, 128, 1)`, the Code runs without any Error, both for Eager Execution and Graph Mode execution. 

Please find the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/bd539ba720fd6d38cc48bf84cc68e075/untitled183.ipynb). 

As per my understanding, it is the intended behavior to expect same shape for Input Layer and that for the Data. Please let me know your opinion regarding the same. Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-29 12:36
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by bfmat** [comment] 2019-10-29 16:36
@rmothukuru @tensorflowbutler Apologies for the delay. Yes, it is still an issue. In the gist posted most recently, the input and data shapes are both `(72, 128, 1)`. No error is expected in this case. The problem is that, when eager execution is disabled, _no_ error is raised when, for instance, the data shape is `(128, 72, 1)` while the input shape is `(72, 128, 1)`.

**Comment by redna11** [comment] 2019-11-25 09:30
To add to this issue from keras perspective, maybe it helps finding out the error.

I have a model with input shape as:

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 1024, 1024, 3)     0   

I'm feeding this model those three inputs of different sizes :

        ri_teacher1 = self.model1([ri_larger])
        ri_teacher2 = self.model2([ri_small])
        ri_teacher3 = self.model3([ri])

print out from the inputs:

ri_larger Tensor("lambda_11/Tile:0", shape=(?, 1024, 512, 4), dtype=float32)
ri_small Tensor("lambda_10/AvgPool:0", shape=(?, 256, 256, 3), dtype=float32)
ri Tensor("conv2d_45/Relu:0", shape=(?, 512, 512, 4), dtype=float32)

None of those raise an error and training proceeds...while it is expected it should since the input shape is (?,1024,1024,3), but I am feeding it (?,1024,512,4), (?,256,256,3) and (?,512,512,4) respectively.

This is using Keras with TF backend

**Comment by tanzhenyu** [comment] 2020-04-06 19:15
I think we should error out. The fact that:
1. it doesn't put any warning in `model.fit`
2. it puts warning in `model.call`
in a little bit troubling. Here's where it swallows the error:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/network.py#L958-L964
Reassigning to author of that function.

**Comment by saikumarchalla** [comment] 2020-09-25 06:27
@bfmat   Closing this issue since we're only making critical bug fixes to graph-mode code. Please feel free to reopen the issue if necessary.Thanks!

**Closed by saikumarchalla** 2020-09-25 06:27 UTC
Labels: TF 1.14, comp:keras, type:bug
