### ISSUE TITLE
`_tanh(x)` returns different values for the same `x`

### ISSUE THREAD

**Issue by ninotoshi** [tensorflow/tensorflow#2234] opened 2016-05-05 12:21 UTC
Why is the last one (`0.99505478`) different from the first four?

```python
>>> import tensorflow as tf
>>> from tensorflow.python.ops.gen_math_ops import _tanh
>>> a = tf.ones([1, 3], tf.float32)
>>> b = tf.ones([3, 5], tf.float32)
>>> c = tf.matmul(a, b)
>>> sess = tf.Session()
>>> print(sess.run(_tanh(c)))
[[ 0.99505472  0.99505472  0.99505472  0.99505472  0.99505478]]
```

With `tf.float64`, the values are all `0.99505475`.

**Comment by yaroslavvb** [comment] 2016-05-05 14:57
Can't reproduce, tried on Z420 and Z840 machines and TF at head.

Are you using GPU?

```
import tensorflow as tf
with tf.device("/cpu:0"):
  a = tf.ones([1, 3], tf.float32)
  b = tf.ones([3, 5], tf.float32)
sess = tf.Session()
print(sess.run(tf.tanh(tf.matmul(a, b))))

[[ 0.99505478  0.99505478  0.99505478  0.99505478  0.99505478]]
```

**Comment by ninotoshi** [comment] 2016-05-05 15:23
I get the same result even with your code specifying `tf.device("/cpu:0")`.
I am using 0.8.0 in the VirtualBox image of Ubuntu (`vagrant-ubuntu-vivid-64 3.19.0-10-generic #10-Ubuntu SMP`).

**Comment by yaroslavvb** [comment] 2016-05-05 18:57
Can you try and see if it's still non-deterministic when using with less threads

```
import tensorflow as tf
with tf.device("/cpu:0"):
  a = tf.ones([1, 3], tf.float32)
  b = tf.ones([3, 5], tf.float32)
  c = tf.tanh(tf.matmul(a, b))
config = tf.ConfigProto(inter_op_parallelism_threads=1, intra_op_parallelism_threads=1)
sess = tf.Session(config=config)
print(sess.run(c))
```

**Comment by hunkim** [comment] 2016-05-05 21:30
I can reproduce it (in python 3.5.1):
![image](https://cloud.githubusercontent.com/assets/901975/15057830/71bdc75e-134b-11e6-83d2-f451ee11d611.png)

It's getting interesting when I change the input size 10:

![image](https://cloud.githubusercontent.com/assets/901975/15057856/890356b8-134b-11e6-8265-a45179fbe818.png)

with 100, the problem is gone:
![image](https://cloud.githubusercontent.com/assets/901975/15057865/9a53da64-134b-11e6-9dc6-10cfe1f38bc2.png)

**Comment by yaroslavvb** [comment] 2016-05-05 21:37
Hm, could it be numpy display issue? What if you do

import tensorflow as tf
with tf.device("/cpu:0"):
  a = tf.ones([1, 3], tf.float32)
  b = tf.ones([3, 5], tf.float32)
  c = tf.log(tf.tanh(tf.matmul(a, b))-0.99505478)/tf.log(2.)
config = tf.ConfigProto(inter_op_parallelism_threads=1, intra_op_parallelism_threads=1)
sess = tf.Session(config=config)
print(sess.run(c))

**Comment by vrv** [comment] 2016-05-05 21:40
I suspect eigen packet/vector vs non vector difference. Inputs mod 4 will
be the same, the remainder will be different because it uses a different
code path?

**Comment by vrv** [comment] 2016-05-05 21:41
@benoitsteiner @rmlarsen for comment?

**Comment by benoitsteiner** [comment] 2016-05-05 23:51
We have an optimized version of the tanh function that processes coefficients 4 by 4. In a tensor of 10 elements we call that function twice to process the 8 first element, and we process the last 2 elements one by one by calling std::tanh. std::tanh and our optimized versions don't fully agree on the final result, which is why the last 2 coefficients are slightly different from the rest.

When the input contains 100 elements, we simply call the optimized version of tanh 25 times, so all the results match.

**Comment by girving** [comment] 2016-06-07 05:38
Contributions welcome to fix this to be consistent!

**Comment by suiyuan2009** [comment] 2016-07-20 09:52
I'll work on this

**Comment by suiyuan2009** [comment] 2016-07-30 14:25
I find that SSE2 vectorization is a feature of eigen, so adding addtional code to tensorflow may be a good choice.

**Comment by suiyuan2009** [comment] 2016-08-27 03:21
one eigen's core dev pushed [some update](https://bitbucket.org/eigen/eigen/pull-requests/215/fix_tanh_inconsistent_for_tensorflow/diff) to tanh.

**Comment by aselle** [comment] 2016-10-13 01:13
I've confirmed that this is now fixed.

**Closed by aselle** 2016-10-13 01:13 UTC
Labels: contributions welcome, enhancement
