### ISSUE TITLE
TF2.0 Problem making prediction from a checkpoint if model has an embedding column

### ISSUE THREAD

**Issue by hsm207** [tensorflow/tensorflow#28929] opened 2019-05-22 13:50 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below):  v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have a keras model that has an embedding column as a  feature.

I can train and save the model's weights just fine. Making predictions immediately after training works too.

The problem is when I recreate the model and reload the weights. Making a prediction from that model gives a shape error.

**Describe the expected behavior**
Same output as making predictions immediately after training.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Please refer to this [gist](https://gist.github.com/hsm207/305d068c982edf9e1df7db77446df50c).

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment] 2019-05-23 12:18
I was able to reproduce the mentioned output on Colab with TensorFlow version 2.0.0-alpha0.

**Comment by jvishnuvardhan** [comment] 2019-09-06 20:56
@hsm207 I could not reproduce the issue as it was resolved in `tf-nightly-2.0-preview`. I can see exactly same results with model_1  (original) and model_2(restored model). Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/a6a1ca212893e68b4b2448bca31bfa05/tf2_bug_embedding_column.ipynb).

I am closing the issue as it was resolved in tf-nightly-2.0-preview. Please feel free to open it if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-09-06 20:56 UTC
Labels: TF 2.0.0-alpha0, comp:keras, stat:awaiting tensorflower, type:bug
