### ISSUE TITLE
tensorflow cpu module's speed lower on windows than linux

### ISSUE THREAD

**Issue by marykid** [tensorflow/tensorflow#19490] opened 2018-05-23 07:41 UTC
System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows7 64bit and ubuntu 16.04 64bit
- TensorFlow installed from (source or binary):build tensorflow source to shared lib
- TensorFlow version (use command below):tensorflow v1.3.0
- Python version: 3.5
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A
- Exact command to reproduce:N/A

Describe the problem
Training tensorflow module and detect faces both on windows7 and ubuntu 16.04, but it costs about twice time on windows7 than ubuntu16.04. So we want to know this issue is normal or not? And if it is normal, what's the reason?
windows7 PC environment:
CPU: Intel Core i3 2120
time: 80~160 ms

ubuntu16.04 PC environment:
CPU: Intel(R) Core(TM) i3-3220 CPU@3.30GHz
time: 40~100 ms

**Comment by tensorflowbutler** [comment] 2018-06-10 21:58
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment] 2018-06-11 17:01
There isn't any fundamental reason, I believe, why performance should be different. However, in general, it's hard to say since the same code is generated using different compilers with different options, so it's possible that some kernels behave differently based on these differences in compiler behavior.

If you could profile the code and identify potential differences that might help provide a clue.

For now, marking this as "Community Support", since hopefully someone out there will have some cycles to dig into this and identify the root cause of the difference.

**Comment by tensorflowbutler** [comment] 2018-06-26 12:45
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tilakrayal** [comment] 2022-05-24 01:53
Hi @marykid,
Could please take a look at below which helps to improve the performance.
1. Installation process of Tensorflow is easy on windows than linux.
2. It is advisable to install Visual C++ package in Windows.
3. The GPU version works best with Cuda Toolkit and cuDNN.

Also i request to please try to test the code in latest tensorflow version 2.9 from [here](https://www.tensorflow.org/install). It helps. Thank you!

**Closed** 2022-06-07 02:59 UTC
Labels: stat:awaiting response, type:build/install, type:support, stalled, 1.4.0
