### ISSUE TITLE
Allocation Tensor change output shape from [1,136] to [0,136]: Invalid tensor size on reading output tensor

### ISSUE THREAD

**Issue by vineetkushwaha** [tensorflow/tensorflow#48786] opened 2021-04-27 20:42 UTC
### 1. System information

Running on Google Colab 
TensorFlow : 2.4.1

[Model.zip](https://github.com/tensorflow/tensorflow/files/6387424/Model.zip)
Have attached the Tflite model and the Tensorflow model graph

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/drive/1N2umiVDPnTuj6-F9_V00L8GUidHP2rkB?usp=sharing): Demonstrate code to convert PyTorch to Tflite and the issue.
[](url)
### 3. Failure after conversion

- Generated model before allocation tensor show output tensor size (1,136), after allocation the tensor size becomes (0,136)
- After invoke, if try to get output tensor it show ValueError: Invalid tensor size.
- The PyTorch model is giving desired output (face landmark) before conversion to Tflite

**Comment by abattery** [comment] 2021-04-28 04:59
I could confirm that the attached TFLite model file works well with the TFLite benchmark tool.

**Comment by abattery** [comment] 2021-04-28 05:00
@vineetkushwaha Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.

**Comment by vineetkushwaha** [comment] 2021-04-28 06:58
@abattery I am inferencing the model (face landmark) in python and here is the reference code for inference (Google Colab) that will produce the error. Model.zip file contains the Tflite model and sample input image (face image).
Reference [TensorFlow Model Colab] https://colab.research.google.com/drive/1N2umiVDPnTuj6-F9_V00L8GUidHP2rkB?usp=sharing#scrollTo=6Kyyfe3O97Tr 
[Model.zip](https://github.com/tensorflow/tensorflow/files/6389646/Model.zip)

**Comment by abattery** [comment] 2021-04-28 09:58
@vineetkushwaha Thank you! I could reproduce the situation at my end. Will triage this bug report to the team.

**Comment by pjpratik** [comment] 2023-01-10 10:27
@vineetkushwaha The bug seems to be resolved in TF 2.11. Please check this [gist](https://colab.research.google.com/gist/pjpratik/e2e3c72f9a9f566af199500a512a32a8/48786.ipynb) and let us know if it helps.  Thank you.

**Closed** 2023-01-24 11:33 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.4
