### ISSUE TITLE
TF 1.10 needs CUDA 9.2 - put info in release notes

### ISSUE THREAD

**Issue by PhilipMay** [tensorflow/tensorflow#22235] opened 2018-09-12 11:02 UTC
Hi,
TF 1.10 needs CUDA 9.2 now. I am missing this info in the RELEASE.md file.
I suggest to add that. Did cost me a lot of time installing the different CUDA versions...

What do you think?

Even this documentation is "wrong" about this:
https://www.tensorflow.org/install/install_linux#tensorflow_gpu_support

Thanks
Philip

------------------------

Added informations (that do not matter) as requested:

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: newest Xubuntu but that does not matter
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: bin
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**: does not matter
- **Exact command to reproduce**: docu issue

**Comment by tensorflowbutler** [comment] 2018-09-12 18:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by PhilipMay** [comment] 2018-09-12 19:09
@tensorflowbutler done

**Comment by av8ramit** [comment] 2018-09-12 19:55
I don't believe this is true, assigning @tfboyd for further clarification.

**Comment by tfboyd** [comment] 2018-09-12 19:55
TF 1.10 will not work with CUDA 9.2, it only works with CUDA 9 if you are using the official binaries, e.g. `pip install tensorflow-gpu`.  I only test with the docker images but since I or the team did not upgrade the build servers to have CUDA 9.2.  The server also have device driver 384.111 which is not compatible with CUDA 9.2 so the unit tests would fail instantly.  I am pretty confident they do not work with CUDA 9.2 unless something really unexpected occurred.  There are also people that are not happy we/I chose to stick with CUDA 9.0.  

It would help to have seen your error.  I do not want to close this super fast on you, if you have more info that would be helpful.  TF 1.11 is also CUDA 9.0.

**Comment by tfboyd** [comment] 2018-09-12 19:57
TF 1.11 not TF 1.10 did change cuDNN versions from 7.0 to 7.2 but I suspect many people were already on 7.2.  This change is/will be in the release notes and was due to a TensorRT 4.x requirement.  

Additionally, we will move to CUDA 10.x as fast as possible once it is GA, and NVIDIA plans to have a bigger range of device driver support that should allow us to move versions faster without causing people problems.  It is a bit of a no win situation and learn as you go kind of thing.

**Comment by PhilipMay** [comment] 2018-09-12 21:32
I did use a brand new install of Xubuntu 18.04, Bionic Beaver.
Then I updated the system and installed CUDA 9.2 and cuDNN v7.2.1.
See here for a step by step guild (sorry it's just german): https://wiki.eniak.de/ml/cuda_unter_ubuntu_installieren

I installed `tensorflow-gpu` with conda via `conda install tensorflow-gpu`. That installed  tensorflow-gpu 1.10.0.

Now everything was working fine and smooth.

When I installed CUDA 9.1 or CUDA 9.0 I got this error:
CUDA driver version is insufficient for CUDA runtime Version

Maybe here is the difference: I did use conda and not pip but I do not think this is a big difference.

I am very confused and can send more details tomorrow. Just ask what you need to know...

**Comment by gunan** [comment] 2018-09-13 07:44
@PhilipMay using conda to install tensorflow does matter.
Conda TF package is built and maintained by anaconda. That is clearly stated in our documentation, in the same page you linked:
https://www.tensorflow.org/install/install_linux#InstallingAnaconda

Please reach out to anaconda for support with the conda package.
Just for good measure, I also just verified that the pip package on pypi for tensorflow runs on cuda 9.0:
```
$ pip3 install tensorflow-gpu --upgrade
$ python3
>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
....
True
>>> exit()
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Thu_Oct_19_03:08:58_CDT_2017
Cuda compilation tools, release 9.0, V9.0.222
```

Closing this issue, as it is about the community supported conda package.

**Closed by gunan** 2018-09-13 07:44 UTC

**Comment by tfboyd** [comment] 2018-09-13 13:51
@PhilipMay   

I am sorry about that.  As Gunan said we do not handle the Anaconda build.  They may have chosen to use a new CUDA which I understand and that creates confusion.  I cannot think of an easy way to make this clear.  With CUDA 10 I hope we all end up on the same version and have less divergence after that.  Thank you for the extra information, I had not even considered Anaconda might build differently but it makes sense.

Thank you again.

**Comment by PhilipMay** [comment] 2018-09-13 19:05
Thanks for clarification.
