### ISSUE TITLE
tensorflow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by rdeepc** [tensorflow/tensorflow#7558] opened 2017-02-16 06:54 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by rdeepc** [comment] 2017-02-16 06:54
1) pip uninstall tensorflow 
2) pip install tensorflow

**Comment by Carmezim** [comment] 2017-02-16 07:18
I couldn't properly understand what issue you're having, Did you receive this error when trying to install? If you're having the same problem as #7552 please keep track there as it's a duplicate issue. 
Thanks.

**Comment by aselle** [comment] 2017-02-16 21:31
Closing as this is a dupe of #7552

**Closed by aselle** 2017-02-16 21:31 UTC
