### ISSUE TITLE
Bug in embedding_ops.py Leads to Crash when importing Frozen Wide and Deep model/graph

### ISSUE THREAD

**Issue by mahmoud-abuzaina** [tensorflow/tensorflow#25443] opened 2019-02-02 00:11 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12, 1.13 and master
- Python version: 2.7
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): GCC 6.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
After successfully training and exporting the trained Wide and Deep model from here:
https://github.com/tensorflow/models/tree/master/official/wide_deep
Tried to freeze the exported model using freeze_graph.py. The frozen graph got generated without errors. However, when tried to load the frozen graph using the call tf.import_graph_def(graph_def), got the following error:
File "../python2.7/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node import/linear/linear_model/linear_model/linear_model/age_bucketized/weighted_sum/embedding_lookup_sparse/embedding_lookup was passed float from import/linear/linear_model/age_bucketized/weights/part_0:0 incompatible with expected resource.

After inspecting the frozen graph, we found that ResourceGather Op is receiving float form Const node (which used to be VarHandleOP before freezing) but ResourceGather is expecting 'resource' data type.

The issue was resolved after changing this line https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/embedding_ops.py#L693
by removing the if statement and calling convert_to_tensor() unconditionally.

**Describe the expected behavior**
The graph is expected to load and run successfully.
**Code to reproduce the issue**
https://github.com/tensorflow/models/tree/master/official/wide_deep

**Comment by martinwicke** [comment] 2019-02-05 18:38
I believe this is a bug in freeze_graph (or possibly our loading code) as freeze_graph doesn't seem to properly handle ResourceVariables. The fix in #25501 presents a regression when dealing with ResourceVariables. 

@petewarden @aselle is my hunch about freeze_graph correct?

**Comment by alextp** [comment] 2019-02-13 22:56
@gargn for freeze-resource-variables work

**Comment by yangw1234** [comment] 2019-02-27 07:46
actually there are several issues reporting similar problem #25327, #25721, https://github.com/tensorflow/hub/issues/208, https://github.com/tensorflow/tfjs/issues/947, #21889 @alextp @gargn @suharshs

**Comment by gargn** [comment] 2019-03-21 18:19
https://github.com/tensorflow/tensorflow/commit/cebce4a2b5e33a06a1c92772008082895568f10a should fix this issue. Please reopen if it's still an issue.

**Comment by veqtor** [comment] 2019-05-20 14:44
When can we expect this in nightly or master?

**Comment by CharlesKung** [comment] 2019-09-02 08:42
I could not figure out which part was the code changed.
this may due to the change of the tensorflow.
But when I change the code in current file : 747 - 752 
from
`  embedding_weights = [
      w if (isinstance(w, resource_variable_ops.ResourceVariable)
            and dtype in (None, w.dtype))
      else ops.convert_to_tensor(w, dtype=dtype)
      for w in embedding_weights
  ]`
to 
`  embedding_weights = [
      for w in embedding_weights: ops.convert_to_tensor(w,dtype=dtype)
  ]`
according to the description of the solution-- calling convert_to_tensor() unconditionally, it still did not work with the same error.

Any ideas?

**Comment by CharlesKung** [comment] 2019-09-02 09:32
Hi, I met the same problem for the wide and deep learning model. The redirect of the line 693 may have been changed, but according to the description of your, I've do the following changes:
`  embedding_weights = [
      # w if (isinstance(w, resource_variable_ops.ResourceVariable)
      #       and dtype in (None, w.dtype))
      # else ops.convert_to_tensor(w, dtype=dtype)
      # for w in embedding_weights
      ops.convert_to_tensor(w,dtype=dtype)
      for w in embedding_weights
  ]
`
where the commented part is the original code.
However it still did not work.
Did I change the wrong part? Or the bug still remains?

**Comment by gargn** [comment] 2019-09-03 18:09
@veqtor @CharlesKung Can you both provide reproducible examples with the error that you are getting?

**Comment by CharlesKung** [comment] 2019-09-04 02:12
@gargn I just changed the code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/embedding_ops.py#L693
from
embedding_weights= [ w if (isinstance(w, resource_variable_ops.ResourceVariable) and dtype in (None, w.dtype)) else ops.convert_to_tensor(w, dtype=dtype) for w in embedding_weights ]
to
embedding_weights = [ ops.convert_to_tensor(w,dtype=dtype) for w in embedding_weights ]

then freeze the model and reload it. 

`saver = tf.train.import_meta_graph(export_path+"/model.ckpt-65160.meta",clear_devices=True)

with tf.Session(graph = tf.get_default_graph()) as sess:
    input_graph_def = sess.graph.as_graph_def()
    saver.restore(sess,export_path+"/model.ckpt-65160")
    output_graph_def = tf.graph_util.convert_variables_to_constants(sess,input_graph_def,output_nodes)
    output_file = export_path+"/frozen_model.pb"
    with open(output_file,"wb") as f:
        f.write(output_graph_def.SerializeToString())

with open(output_file, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

graph = tf.Graph()
with graph.as_default():
    tf.import_graph_def(graph_def, input_map=None, return_elements=output_nodes)`

I was confused by the input of the frozen graph as the nodes left for processing were "IteratorV2" and "IteratorGetNext". I thought it was removed by the freezing parts because the previous nodes are doing data processing.
Is there any reference for the input of the frozen graph ? Like in the saved_model methods, the input should be wrapped as tf.Example and build a serving_input_receiver_fn function.
Thanks.

**Comment by gargn** [comment] 2019-09-06 20:15
@CharlesKung A few questions/comments:

1. Can you attach the input files that are being used in your code snippet so that I can run it and reproduce it locally? Additionally, can you update your code snippet to work as a stand alone. I noticed `output_nodes` is not defined.
2. Why are you changing the logic in the embedding op? In general, freeze graph works by pattern matching. If you are changing the patterns then it will no longer work.
3. Iterator ops should not be removed unless you are specifying the output nodes as nodes before the Iterator ops. However, by default nothing happens to them in freeze graph.
4. The input of your frozen graph should be the same as the original graph that you created. The only thing that changes in freeze graph is that Variable ops are converted to Const ops (and other similar transformations relating to resources). The structure of the graph and the op names stay the same. I would suggest loading the frozen graph using TensorBoard to examine what the inputs should be if you are uncertain.

**Comment by gargn** [comment] 2019-10-21 16:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gargn** 2019-10-21 16:22 UTC
Labels: comp:eager, comp:lite, type:bug
