### ISSUE TITLE
tf.TensorArray with Defun

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#30894] opened 2019-07-20 03:23 UTC
when using Defun under tf 1.x, the tf.TensorArray input will degrade to a Tensor.

```
xxxx output_tags : <dtype: 'float32'>
Tensor("output_tas:0", dtype=float32, device=/device:CPU:0)
[  FAILED  ] SpeechOpsFeatTest.test_splice
======================================================================
ERROR: test_splice (__main__.SpeechOpsFeatTest)
test_splice (__main__.SpeechOpsFeatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "speech_ops_test.py", line 202, in test_splice
    out = tffeat.splice(feat, left_context=2, right_context=2)
  File "/delta/delta/data/feat/speech_ops.py", line 376, in splice
    swap_memory=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 535, in __call__
    self.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 516, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 348, in _create_definition_if_needed                                                                                                                             
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 379, in _create_definition_if_needed_impl                                                                                                                        
    capture_resource_var_by_value=self._capture_resource_var_by_value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 915, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/delta/delta/data/feat/speech_ops.py", line 357, in _loop_body
    new_output_tas = output_tas.write(time,  new_feat)
AttributeError: 'Tensor' object has no attribute 'write'
```

without Defun decorator,  everything is ok

```
xxxx output_tags : <dtype: 'float32'>
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f2528260908>
I0720 03:20:01.964524 139798580987712 speech_ops_test.py:203] splice : Tensor("TensorArrayStack_1/TensorArrayGatherV3:0", shape=(?, ?, 1, ?), dtype=float32)
[       OK ] SpeechOpsFeatTest.test_splice
```

```
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/fields.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/parsing.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/period.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/frequencies.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/timestamps.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/resolution.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/hashtable.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/missing.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/lib.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslib.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/algos.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/interval.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/properties.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/hashing.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/ops.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/index.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/join.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/sparse.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/indexing.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/internals.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /usr/lib/python3.6/lib-dynload/mmap.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/reshape.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/kiwisolver.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/skiplist.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/groupby.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/reduction.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/parsers.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/json.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/writers.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/util/_move.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/io/msgpack/_packer.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/io/msgpack/_unpacker.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling init: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/testing.cpython-36m-x86_64-linux-gnu.so
      8583:
      8583:
      8583:     calling fini: /usr/bin/python3 [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libutil.so.1 [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libexpat.so.1 [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libz.so.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_opcode.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/x86_64-linux-gnu/libffi.so.6 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/core/_multiarray_tests.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/linalg/lapack_lite.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/linalg/_umath_linalg.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_bz2.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libbz2.so.1.0 [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_lzma.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/liblzma.so.5 [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_decimal.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/x86_64-linux-gnu/libmpdec.so.2 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/fft/fftpack_lite.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/random/mtrand.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_hashlib.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/tensorflow/python/../libtensorflow_framework.so.1 [0]
      8583:
      8583:
      8583:
      8583:
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_csv.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/termios.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/fast_tensor_util.so [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libuuid.so.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/wrapt/_wrappers.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_json.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/x86_64-linux-gnu/libssl.so.1.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/_errors.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/_conv.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5r.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/_objects.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/defs.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5t.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/utils.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5z.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5a.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5s.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5p.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5ac.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/_proxy.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5d.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5ds.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5f.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5g.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5i.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5fd.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5o.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/h5l.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/.libs/libhdf5_hl-db841637.so.100.1.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/.libs/libhdf5-5773eb11.so.103.0.0 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/.libs/./libz-a147dcb0.so.1.2.3 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/.libs/./libsz-1c7dd0cf.so.2.0.1 [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/h5py/.libs/./libaec-2147abcd.so.0.0.4 [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/librt.so.1 [0]
      8583:
      8583:
      8583:     calling fini: /lib/x86_64-linux-gnu/libdl.so.2 [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/_lib/_ccallback_c.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/_csparsetools.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/csgraph/_shortest_path.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/csgraph/_tools.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/csgraph/_traversal.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/csgraph/_min_spanning_tree.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/sparse/csgraph/_reordering.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/ndimage/_nd_image.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/ndimage/_ni_label.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/_fblas.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/_flapack.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/_flinalg.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/_solve_toeplitz.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/_decomp_update.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/cython_blas.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/scipy/linalg/cython_lapack.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/conversion.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/c_timestamp.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/nattype.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/np_datetime.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/timezones.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/tzconversion.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/timedeltas.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/offsets.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/ccalendar.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/strptime.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/fields.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/parsing.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/period.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/frequencies.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/timestamps.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslibs/resolution.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/hashtable.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/missing.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/lib.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/tslib.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/algos.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/interval.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/properties.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/hashing.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/ops.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/index.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/join.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/sparse.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/indexing.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/internals.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /usr/lib/python3.6/lib-dynload/mmap.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/reshape.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/kiwisolver.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/skiplist.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/groupby.cpython-36m-x86_64-linux-gnu.so [0]
      8583:
      8583:
      8583:     calling fini: /home/delta/.local/lib/python3.6/site-packages/pandas/_libs/reduction.cpython-36m-x86_64-linux-gnu.so [0]




































== check python ===================================================
python version: 3.6.8
python branch:
python build version: ('default', 'Jan 14 2019 11:02:34')
python compiler version: GCC 8.0.1 20180414 (experimental) [trunk revision 259383
python implementation: CPython


== check os platform ===============================================
os: Linux
os kernel version: #1 SMP Fri Sep 7 08:20:28 UTC 2018
os release version: 4.9.125-linuxkit
os platform: Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic
linux distribution: ('Ubuntu', '18.04', 'bionic')
linux os distribution: ('Ubuntu', '18.04', 'bionic')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='39917737c69c', release='4.9.125-linuxkit', version='#1 SMP Fri Sep 7 08:20:28 UTC 2018', machine='x86_64', processor='x86_64')                                                                                       
architecture: ('64bit', 'ELF')
machine: x86_64


== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== check pips ===================================================
numpy                         1.16.4   
protobuf                      3.8.0    
tensorflow                    1.14.0   
tensorflow-estimator          1.14.0   

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 1.14.0
tf.version.GIT_VERSION = v1.14.0-rc1-22-gaf24dc91b5
tf.version.COMPILER_VERSION = 4.8.5

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(2, 7, 15, 'final', 0)

== bazel version  ===============================================
```

**Comment by anush-o** [comment] 2019-07-22 11:38
@zh794390558 ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by anush-o** [comment] 2019-07-30 11:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by anush-o** 2019-07-30 11:13 UTC
Labels: TF 1.14, comp:ops, stat:awaiting response, type:support

**Comment by DelphianCalamity** [comment] 2019-10-21 10:59
I'm having this issue, too.
This is a minimal example to reproduce it:

`import tensorflow as tf
from tensorflow.python.framework import function

arr = tf.TensorArray(tf.int32, 1, dynamic_size=True)

@function.Defun(tf.int32, tf.int32, func_name="func", out_names=["ret"])
def f(i, arr):
    arr = arr.write(i, 1)
    return arr

x = f(1, arr)

sess = tf.Session()
sess.run(x)
`
