### ISSUE TITLE
./configure in interactive mode does not create working config for build

### ISSUE THREAD

**Issue by dchirikov** [tensorflow/tensorflow#7542] opened 2017-02-15 21:55 UTC
# Description
Hi,
I encounter following issue. If user runs ./configure script interactively filling blanks it is not possible to build TF with CUDA support. BUT if user exports corresponding env variables before of after ./configure, bazel can happily build binaries.

# Environment
```
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (AltArch)

$ uname -a
Linux power004.cluster 3.10.0-514.6.1.el7.ppc64le #1 SMP Thu Jan 19 14:34:54 GMT 2017 ppc64le ppc64le ppc64le GNU/Linux

$ ls -l /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcud*
-rw-r--r-- 1 root root 559800 Oct 29 10:22 /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Feb 14 23:26 /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root     19 Feb 14 23:26 /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.54
-rwxr-xr-x 1 root root 476024 Oct 29 10:22 /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcudart.so.8.0.54
-rw-r--r-- 1 root root 966166 Oct 29 10:22 /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0/lib64/libcudart_static.a

$ git rev-parse HEAD
16485a3fb5ffcbaa244e55c388e43279d2770982

$ bazel version
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
................
Build label: 0.4.4- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Feb 9 23:48:24 2017 (1486684104)
Build timestamp: 1486684104
Build timestamp as int: 1486684104
```

# Steps to reproduce
```
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ git checkout r1.0
$ export TEST_TMPDIR=/local/cvsupport
$ ./configure
```
Fill blanks
```
Please specify the location of python. [Default is /bin/python]: /usr/bin/python3.4
Please specify optimization flags to use during compilation [Default is -march=native]: -march=native
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib/python3.4/site-packages
  /usr/lib64/python3.4/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3.4/site-packages]
/usr/lib64/python3.4/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /bin/gcc]: /usr/bin/gcc
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.10
Please specify the location where cuDNN 5.1.10 library is installed. Refer to README.md for more details. [Default is /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0]: /trinity/shared/apps/cv-ppc64le/nvidia/cudnn/8.0
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.0
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
..............
INFO: All external dependencies fetched successfully.
Configuration finished
```
Attempt to build:
```
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.572s
```

# Working method
```
$ cat ../build_vars.sh 
export TEST_TMPDIR=/local/cvsupport
export PYTHON_BIN_PATH=/usr/bin/python3.4
export PYTHON_LIB_PATH=/usr/lib64/python3.4/site-packages
export TF_NEED_JEMALLOC=1
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_NEED_CUDA=1
export TF_ENABLE_XLA=0
export CC_OPT_FLAGS="-march=native"
export TF_CUDA_VERSION=8.0
export TF_CUDNN_VERSION=5.1.10
export TF_CUDA_COMPUTE_CAPABILITIES=6.0
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc
export CUDA_TOOLKIT_PATH=/trinity/shared/apps/cv-ppc64le/nvidia/cuda/${TF_CUDA_VERSION}
export CUDNN_INSTALL_PATH=/trinity/shared/apps/cv-ppc64le/nvidia/cudnn/${TF_CUDA_VERSION}

$ source ../build_vars.sh
$ ./configure
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

Experimenting with omitting different variables seems like only following vars are sufficient.
`TF_NEED_CUDA`, `TF_CUDA_VERSION`, `CUDA_TOOLKIT_PATH`, `CUDNN_INSTALL_PATH`, `GCC_HOST_COMPILER_PATH`

**Comment by aselle** [comment] 2017-02-15 23:16
@gunan, @yifeif, do we have a solution to this?

**Comment by gunan** [comment] 2017-02-16 04:39
All these work for me if I use centos nvidia-docker image, without entering anything manually.
It is possible we have a problem in the script to read the command line inputs?

**Comment by r4nt** [comment] 2017-02-16 08:45
@gunan - if anything it looks like TF_NEED_CUDA wasn't set correctly, which would be weird.

@dchirikov - can you put
echo $TF_NEED_CUDA
before the call to bazel_clean_and_fetch and post the output?

(for @damienmg, an example user experience problem bazel's configuration needs to solve better)

**Comment by dchirikov** [comment] 2017-02-16 10:27
@gunan
> without entering anything manually.

That's the issue, actually. If you need to enter it manually interactively in ./configure - it will fail. Something in this command relies on defined environment variables:
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
@r4nt 
> can you put
echo $TF_NEED_CUDA

it echoes '1', which is good
but again, those vars are not inherited in `bazel build`

**Comment by r4nt** [comment] 2017-02-16 11:16
@dchirikov - the configure script has a line saying "export TF_NEED_CUDA" - I'm really confused why that wouldn't end up in your blaze fetch.
The reliance of the blaze fetch on environment variables is by design.

**Comment by dchirikov** [comment] 2017-02-16 11:47
@r4nt 
>  that wouldn't end up in your blaze fetch.

it is accessible and defined in fetch, but not defined in `bazel build` step.

**Comment by r4nt** [comment] 2017-02-16 12:41
@dchirikov - that doesn't matter though - the way bazel works is that the whole bazel-tensorflow/external/ stuff gets configured as part of the fetch step; the environment variables affect what ends up there, but are not needed afterwards when you do bazel build.

**Comment by dchirikov** [comment] 2017-02-16 12:51
@r4nt 
If i get it right `./third_party/gpus/cuda_configure.bzl` is being executed during `basel build`, and yes, it expects some vars is user environment is being defined:
```
def _enable_cuda(repository_ctx):
  if "TF_NEED_CUDA" in repository_ctx.os.environ:
    enable_cuda = repository_ctx.os.environ["TF_NEED_CUDA"].strip()
    return enable_cuda == "1"
  return False
```

**Comment by r4nt** [comment] 2017-02-16 13:44
@dchirikov - it shouldn't (it doesn't for me, and I checked with a bazel dev that there should not be a case where it does). What makes you think it does?

**Comment by dchirikov** [comment] 2017-02-16 15:13
@r4nt
if i add print statement to cuda_configure.bzl it will be printed during build:
```
def _enable_cuda(repository_ctx):
  print("========================= test ==========================")
  if "TF_NEED_CUDA" in repository_ctx.os.environ:
    enable_cuda = repository_ctx.os.environ["TF_NEED_CUDA"].strip()
    return enable_cuda == "1"
  return False
```
```
$ bazel build -s -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
....................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.
ERROR: /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.585s
```

**Comment by r4nt** [comment] 2017-02-16 15:47
@dchirikov - this should only happen on invalidation, which is a bazel bug fixed at head.
If you now run configure again, it should work afterwards, as long as you don't sync.

**Comment by dchirikov** [comment] 2017-02-16 15:52
```
# su - cvsupport
$ cd /trinity/home/cvsupport/dmitry/tf/tensorflow; module load bazel/0.4.4; export TEST_TMPDIR=/local/cvsupport
$ bazel cleanup
$ . ../build_vars.sh
$ ./configure
WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.

$ logout
# su - cvsupport
$ cd /trinity/home/cvsupport/dmitry/tf/tensorflow; module load bazel/0.4.4; export TEST_TMPDIR=/local/cvsupport
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.
ERROR: /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
```

What I am missing?

**Comment by r4nt** [comment] 2017-02-16 16:47
Can you do
$ ls $(bazel info output_base)/external/local_config_cuda/crosstool
after ./configure?
If that already shows error_gpu_disabled, your first bazel fetch didn't work (and didn't configure cuda support)

**Comment by dchirikov** [comment] 2017-02-16 17:09
```
$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
total 16
-rwxrwxr-x 1 cvsupport cvsupport 1267 Feb 16 18:05 BUILD
drwxrwxr-x 3 cvsupport cvsupport   17 Feb 16 18:05 clang
-rwxrwxr-x 1 cvsupport cvsupport 9196 Feb 16 18:05 CROSSTOOL
```
Not sure I get you point when it where it should start to complain.

**Comment by r4nt** [comment] 2017-02-17 07:30
Ok, so between your ls (which looks correct) and your bazel builds something invalidates the repository configuration.
You can see that the file in your error message:
"external/local_config_cuda/crosstool/error_gpu_disabled.bzl"
does not even exist before.

Does your /local/cvsupport get deleted by your logout / su?
Specifically, can you run the same ls command you posted above right before you do your bazel build in the last step?

**Comment by dchirikov** [comment] 2017-02-17 10:52
Seems like something in `bazel build` invalidates the cache:
```
$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
................
total 16
-rwxrwxr-x 1 cvsupport cvsupport 1267 Feb 17 11:45 BUILD
drwxrwxr-x 3 cvsupport cvsupport   17 Feb 17 11:45 clang
-rwxrwxr-x 1 cvsupport cvsupport 8928 Feb 17 11:45 CROSSTOOL

$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.396s

$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
total 8
-rwxrwxr-x 1 cvsupport cvsupport  88 Feb 17 11:49 BUILD
-rwxrwxr-x 1 cvsupport cvsupport 497 Feb 17 11:49 error_gpu_disabled.bzl
```

**Comment by r4nt** [comment] 2017-02-17 12:47
Just talked with @damienmg, and he told me that at your bazel version if you restart the bazel server, you invalidate the repository. If your logout / su commands kill the server, the next bazel build will re-fetch, which would lead to the exact problem you describe. That hopefully will be fixed with the next bazel release.

**Comment by dchirikov** [comment] 2017-02-17 13:36
Thank you for the clarification, but origin of the issue is slightly different. Logout came to the picture later.
Initial issue was: run ./configure, fill values and run bazel build. Not sure where 'restart bazel server' is.

**Comment by r4nt** [comment] 2017-02-17 14:23
Ok, but that requires the same debugging step :) Can you do the same set of steps without any logout in between?

**Comment by dchirikov** [comment] 2017-02-17 14:36
>  but that requires the same debugging step
Agree. Just to make sure we are on the same page.

Did as you requested:
```
$ ./configure 
Please specify the location of python. [Default is /bin/python]: /usr/bin/python3.4
Please specify optimization flags to use during compilation [Default is -march=native]: -march=native
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib64/python3.4/site-packages
  /usr/lib/python3.4/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib64/python3.4/site-packages]
/usr/lib64/python3.4/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /bin/gcc]: /usr/bin/gcc
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.10
Please specify the location where cuDNN 5.1.10 library is installed. Refer to README.md for more details. [Default is /trinity/shared/apps/cv-ppc64le/nvidia/cuda/8.0]: /trinity/shared/apps/cv-ppc64le/nvidia/cudnn/8.0
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.0
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
.................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
............
WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.
INFO: All external dependencies fetched successfully.
Configuration finished

$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
..................
total 16
-rwxrwxr-x 1 cvsupport cvsupport 1267 Feb 17 15:30 BUILD
drwxrwxr-x 3 cvsupport cvsupport   17 Feb 17 15:30 clang
-rwxrwxr-x 1 cvsupport cvsupport 8928 Feb 17 15:30 CROSSTOOL

$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.
ERROR: /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.345s

$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
total 8
-rwxrwxr-x 1 cvsupport cvsupport  88 Feb 17 15:33 BUILD
-rwxrwxr-x 1 cvsupport cvsupport 497 Feb 17 15:33 error_gpu_disabled.bzl
```

**Comment by r4nt** [comment] 2017-02-21 09:30
Ok, this is really weird. Can you sprinkle ps -ef bazel in between commands so we get the PID of the bazel process (to see when it restarted)?
Other than that, I know it's a lot to ask, but can you try using bazel from head (I was told there have been a couple of fixes regarding when to rebuild the config)?

**Comment by dchirikov** [comment] 2017-02-21 13:17
Ok,another try:

```
<snip>
[Default is: "3.5,5.2"]: 6.0
1
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
....................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
...............
WARNING: /trinity/home/cvsupport/dmitry/tf/tensorflow/third_party/gpus/cuda_configure.bzl:116:3: ========================= test ==========================.
INFO: All external dependencies fetched successfully.
Configuration finished

$ ps -elf | grep bazel
0 S cvsuppo+  51964      1 99  80   0 - 505728 futex_ 14:12 ?       00:01:58 bazel(tf) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144 -Xverify:none -Djava.util.logging.config.file=/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144/javalog.properties -Djava.library.path=/local/cvsupport/_bazel_cvsupport/install/60eac8be1d9f8622135925f67ceca06d/_embedded_binaries/ -Dfile.encoding=ISO-8859-1 -jar /local/cvsupport/_bazel_cvsupport/install/60eac8be1d9f8622135925f67ceca06d/_embedded_binaries/A-server.jar --max_idle_secs=15 --connect_timeout_secs=10 --install_base=/local/cvsupport/_bazel_cvsupport/install/60eac8be1d9f8622135925f67ceca06d --install_md5=60eac8be1d9f8622135925f67ceca06d --output_base=/local/cvsupport/_bazel_cvsupport/c61d2ac558d6d30ef2694b9af72e4144 --workspace_directory=/trinity/home/cvsupport/dmitry/tf/tensorflow --deep_execroot --experimental_oom_more_eagerly_threshold=100 --nofatal_event_bus_exceptions --client_debug=false --use_custom_exit_code_on_abrupt_exit=true --product_name=Bazel --option_sources=
0 S cvsuppo+  53608  50980  0  80   0 -  1735 pipe_r 14:13 pts/0    00:00:00 grep --color=auto bazel

$ ls  -l $(bazel info output_base)/external/local_config_cuda/crosstool
INFO: $TEST_TMPDIR defined: output root default is '/local/cvsupport'.
.................
total 16
-rwxrwxr-x 1 cvsupport cvsupport 1267 Feb 21 14:12 BUILD
drwxrwxr-x 3 cvsupport cvsupport   17 Feb 21 14:12 clang
-rwxrwxr-x 1 cvsupport cvsupport 8928 Feb 21 14:12 CROSSTOOL

$ ps -elf | grep bazel
0 S cvsuppo+  54379  50980  0  80   0 -  1735 pipe_r 14:16 pts/0    00:00:00 grep --color=auto bazel
```
so `bazel info` killed bazel. I would expect that `bazel build` kills bazel server

**Comment by r4nt** [comment] 2017-02-21 15:34
That would be the case if the bazel in "bazel info" is a different bazel from the bazel that tensorflow finds in its configure script. Do you by any chance have multiple bazel versions installed?

**Comment by dchirikov** [comment] 2017-02-21 20:18
If bazel do not go with TF - no
I barely managed to build single bazel. That was another challenge to make in OpenPower :)
```
$ which bazel
/trinity/shared/apps/cv-ppc64le/bazel/0.4.4/bin/bazel
$ type -f bazel
bazel is /trinity/shared/apps/cv-ppc64le/bazel/0.4.4/bin/bazel

**Comment by damienmg** [comment] 2017-02-21 20:28
@dchirikov: what issue did you encountered in porting bazel to OpenPower? We are generally willing to accept patch to support more platform to avoid people having to maintain their own patches.

**Comment by dchirikov** [comment] 2017-02-21 20:28
Hm, actualy bazel goes offline after a minute after `./configure` by himself. One does not need even to run `bazel info`.
Last logs in `c61d2ac558d6d30ef2694b9af72e4144/java.log` (if it will help)
```
Feb 21, 2017 9:24:53 PM com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment evaluateQuery
INFO: Spent 30208 milliseconds evaluating query
Feb 21, 2017 9:24:54 PM com.google.devtools.build.lib.server.GrpcServerImpl$RunningCommand close
INFO: Finished command 62e1361d-67d3-4e47-ad0a-17183ec6adde on thread grpc-command-0
```

**Comment by dchirikov** [comment] 2017-02-21 20:31
@damienmg 
I don't remember, tbh. Just recall it took some time for me. But it could be just me not so experienced with tools. Anyway, I don't know java at all, so I did not patch it for sure.

**Comment by damienmg** [comment] 2017-02-21 20:37
Oh ok (generally patch are not in the java part, mostly in the compilation scripts).

It looks like Bazel just completed perfectly. /cc @lberki in case he has more understanding of the grpc-command message.

Anyway if the server restart, with the bug I recently fixed on Bazel and without #7575, you will do the configuration step at each build :(, we are trying to cut a Bazel release and our CI has been green today so we should be able to cut one tomorrow.

**Comment by Panaetius** [comment] 2017-02-25 14:58
I just ran into this issue, though with different circumstances

I think the cause had something to do with building tensorflow with an anaconda environment active.

I ran 'ps -elf | grep bazel' and it showed two bazel processes running, one in the conda env, and one outside of it. I don't know what exactly caused bazel to start the server twice. It looks like ./configure used one bazel instance and bazel build used the other one.

So I killed both bazel processes, ran './configure' again, verified only one bazel process was running (it was only one), and ran the bazel build command again, and the build worked. 

Posting this here for posterity if someone else runs into the same issue (since the comments on this issue are what helped me resolve it and I don't see the need to open a new issue)

**Comment by gunan** [comment] 2017-04-03 20:58
Our bazel upgrade to 0.4.5 and related configure script upgrades are done.
I just tried using nvidia dockers centos7 image, and I was able to build without problems.

I will close the issue now, but @dchirikov could you also verify by checking out the master branch, and using bazel 0.4.5?
If it still misbehaves as you described, we can reopen.

**Closed by gunan** 2017-04-03 20:58 UTC
Labels: stat:awaiting tensorflower, type:build/install
