### ISSUE TITLE
NotImplementedError when I use RMSPropOptimizer

### ISSUE THREAD

**Issue by 333caowei** [tensorflow/tensorflow#2475] opened 2016-05-23 15:18 UTC
I am try to use RMSPropOptimizer to optimize parameters and I get NotImplementedError. **But when I try AdamOptimizer, it works fine**. 

**BTW, when I try to find the problem, it seems I find the key point:**
Here is part of my code:
```
self.x = tf.placeholder(tf.int32, [None, sequence_length])  
point = tf.get_variable( [vocabulary_size])
........
........
outputs, states = rnn.rnn(lstm_cell, x_vec, initial_state=initial_state, sequence_length = self.real_length)
index     =    self.x[:, 0]
index  = tf.reshape(index, [-1,1])
index_point  =    tf.gather(point, index)
output   =  tf.mul(outputs[-1] ,   index_point)
```
The key point is last line ```output   =  tf.mul(outputs[-1] ,   index_point)```, when I change ```index_point``` to some others such as number ```1```, **the error disappear**.
And, when I try to use ```bidirectional_rnn```, **the error also can disappear**.

**Comment by mrry** [comment] 2016-05-23 16:21
Closing as duplicate of #2476.

**Closed by mrry** 2016-05-23 16:21 UTC
