### ISSUE TITLE
Branch r2.0 Failed Source Build on macOS Mojave

### ISSUE THREAD

**Issue by ilhamfp** [tensorflow/tensorflow#31247] opened 2019-08-01 20:40 UTC
**System information**
- OS Platform and Distribution: macOS Mojave, 10.14.5 (18F203), (15-inch 2018)
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r2.0
- Python version: Here's the result for `python` in terminal
```
  Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
  [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
  Type "help", "copyright", "credits" or "license" for more information.
```
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): The result for `gcc -v`
```
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.31.5)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Build failed with `bazel run //tensorflow/python/autograph/operators:py_builtins_test` command. I have tried both answering yes and no for `Do you wish to download a fresh release of clang?` question on `./configure`, everything else is the default.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Clone tensorflow from official github repo
2. Checkout to branch r2.0
3. run `./configure` and press enter (all default) except for `Do you wish to download a fresh release of clang?` where I tried both yes & no
4. `bazel run //tensorflow/python/autograph/operators:py_builtins_test`

**Any other info / logs**
Here's one of the `./configure` log: https://pastebin.com/yqsPgKeS
Here's the terminal log for `yes` on bazel run command: https://pastebin.com/cvsdbcHY
Here's the terminal log for `no` on bazel run command: https://pastebin.com/VrEVn8ig

**Comment by aaronhma** [comment] 2019-08-17 18:48
What version of C++ are you using? This is important when compiling C++ code.

**Comment by aaronhma** [comment] 2019-08-17 19:23
Aha! I have traced your issue to this file: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/gen_git_source.py

**Comment by ilhamfp** [comment] 2019-08-18 01:08
@aaronhma Hi! Here you go:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.31.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by aaronhma** [comment] 2019-08-18 01:56
@ilhamfp Please use Python 3 instead of Python 2.

**Comment by ilhamfp** [comment] 2019-08-18 02:05
@aaronhma I think I do use Python 3 though.

Here's the result for `python` in terminal
```
$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by aaronhma** [comment] 2019-08-18 04:31
# ** HOW TO FIX THE ISSUE  **
## FROM:
```bash
#!/usr/bin/env bash
set -e
set -o pipefail
if [ -z "$PYTHON_BIN_PATH" ]; then
  PYTHON_BIN_PATH=$(which python || which python3 || true)
fi
# Set all env variables
CONFIGURE_DIR=$(dirname "$0")
"$PYTHON_BIN_PATH" "${CONFIGURE_DIR}/configure.py" "$@"
echo "Configuration finished"
```

## TO
```bash
#!/usr/bin/env bash
set -e
set -o pipefail
if [ -z "$PYTHON_BIN_PATH" ]; then
  PYTHON_BIN_PATH=$(which python3 || true)
fi
# Set all env variables
CONFIGURE_DIR=$(dirname "$0")
"$PYTHON_BIN_PATH" "${CONFIGURE_DIR}/configure.py" "$@"
echo "Configuration finished"
```

This configuration worked for me. How about you?

**Comment by aaronhma** [comment] 2019-08-18 04:31
@ilhamfp Change it in the ./configure file. I will submit a PR regarding this.

**Comment by aaronhma** [comment] 2019-08-18 20:34
@ilhamfp If this worked for you, please close this issue. Thanks!

**Comment by ilhamfp** [comment] 2019-08-19 06:27
@aaronhma It still failed :(
I follow the exact same sequence of command as my first post. Here's the result:

```
>>>$ bazel run //tensorflow/python/autograph/operators:py_builtins_test
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=223
INFO: Reading rc options for 'run' from /Users/ilhamfirdausiputra/Desktop/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'run' from /Users/ilhamfirdausiputra/Desktop/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/Users/ilhamfirdausiputra/anaconda3/bin/python3 --action_env PYTHON_LIB_PATH=/Users/ilhamfirdausiputra/anaconda3/lib/python3.7/site-packages --python_path=/Users/ilhamfirdausiputra/anaconda3/bin/python3 --action_env TF_CONFIGURE_IOS=0
INFO: Analyzed target //tensorflow/python/autograph/operators:py_builtins_test (196 packages loaded, 13521 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_ilhamfirdausiputra/dcdfe0a4c6b40c8776a8245d2d35846a/sandbox
ERROR: /Users/ilhamfirdausiputra/Desktop/tensorflow/tensorflow/cc/BUILD:491:1: Creating runfiles tree bazel-out/host/bin/tensorflow/cc/ops/user_ops_gen_cc.runfiles [for host] failed: build-runfiles failed: error executing command 
  (cd /private/var/tmp/_bazel_ilhamfirdausiputra/dcdfe0a4c6b40c8776a8245d2d35846a/execroot/org_tensorflow && \
  exec env - \
    PATH=/Users/ilhamfirdausiputra/google-cloud-sdk/bin:/Users/ilhamfirdausiputra/anaconda3/bin:/Users/ilhamfirdausiputra/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/ilhamfirdausiputra/bin \
  /var/tmp/_bazel_ilhamfirdausiputra/install/37d3a264d720ec9ae63603a543c8ff7c/_embedded_binaries/build-runfiles bazel-out/host/bin/tensorflow/cc/ops/user_ops_gen_cc.runfiles_manifest bazel-out/host/bin/tensorflow/cc/ops/user_ops_gen_cc.runfiles): Process terminated by signal 15: Process terminated by signal 15
Target //tensorflow/python/autograph/operators:py_builtins_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: no such package '@local_config_download_clang//': cc_download_clang_toolchain rule //external:local_config_download_clang must create a directory
INFO: Elapsed time: 26.316s, Critical Path: 0.25s
INFO: 7 processes: 7 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by aaronhma** [comment] 2019-08-21 14:36
@ilhamfp This is a problem related with your computer. This is not TebsorFlow's problem.

**Comment by aaronhma** [comment] 2019-08-21 15:22
@gunan Anything you can do to help @ilhamfp ?

**Comment by gunan** [comment] 2019-11-12 17:52
I think the problem is that you tried to download a new clang and use that to build TF.
I do not think we have tested that feature on macos.
@r4nt I think Ilya added this feature, but I do not know if he tested this on macos.
And I do not remember his github handle :(

**Comment by mohantym** [comment] 2021-10-03 02:28
Hi @ilhamfp , Did you try with instructions in this[ link ](https://developer.apple.com/metal/tensorflow-plugin/).

**Closed** 2021-10-17 02:51 UTC
Labels: stat:awaiting response, type:build/install, stalled, TF 2.0, subtype:macOS
