### ISSUE TITLE
`tf.math.pow()` is inaccurate with some small integer values presented by tf.float32 on GPU

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#58479] opened 2022-11-08 13:32 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Colab

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

```shell
tf.math.pow() loses accuracy when computing squares of small integer values represented by tf.float32 on GPU, such as 5.0^2.0,  7.0^2.0 and 13.0^2.0. What make this strange are:

- This is not happening on CPU
- The integer values are very small
- This is not happening on tf.float64
```

### Standalone code to reproduce the issue

```shell
ints = tf.convert_to_tensor(np.arange(20, dtype=np.int32), dtype=tf.int32)
floats = tf.cast(ints, dtype=tf.float32)
doubles = tf.cast(ints, dtype=tf.float64)

with tf.device("/cpu:0"):
  print("cpu ints^2", tf.math.pow(ints, 2))
  print("cpu float32^2", tf.math.pow(floats, 2.))
  print("cpu float64^2", tf.math.pow(doubles, 2.))

with tf.device("/gpu:0"):
  print("gpu ints^2", tf.math.pow(ints, 2))
  print("INACCURATE gpu float32^2", tf.math.pow(floats, 2.))
  print("gpu float64^2", tf.math.pow(doubles, 2.))
```

### Relevant log output

```shell
cpu ints^2 tf.Tensor(
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361], shape=(20,), dtype=int32)
cpu float32^2 tf.Tensor(
[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169.
 196. 225. 256. 289. 324. 361.], shape=(20,), dtype=float32)
cpu float64^2 tf.Tensor(
[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169.
 196. 225. 256. 289. 324. 361.], shape=(20,), dtype=float64)
gpu ints^2 tf.Tensor(
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361], shape=(20,), dtype=int32)
INACCURATE gpu float32^2 tf.Tensor(
[  0.         1.         4.         9.        16.        24.999998
  36.        48.999996  64.        81.        99.99999  121.
 144.       169.       196.       225.       256.       288.99997
 324.       361.      ], shape=(20,), dtype=float32)
gpu float64^2 tf.Tensor(
[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169.
 196. 225. 256. 289. 324. 361.], shape=(20,), dtype=float64)
```
</details>

**Comment by bhack** [comment] 2022-11-08 17:07
I suppose that this is MLIR generated on GPU and it could be related to [float precision in LLVM](https://discourse.llvm.org/t/rfc-floating-point-accuracy-control/66018)?

@cantonios What do you think?

/cc @frgossen

**Comment by bhack** [comment] 2022-11-08 18:54
I am bit lost with all the things moving in `tsl`. Are we using this on CPU?

https://github.com/tensorflow/tensorflow/blob/d46cbbc6433e4e366e0bb45f8632cf84da4b1948/tensorflow/tsl/lib/math/math_util.h#L172-L180

**Comment by bhack** [comment] 2022-11-08 18:57
Also https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-use_fast_math

**Comment by hguihot** [comment] 2022-11-08 22:27
See https://github.com/tensorflow/tensorflow/issues/56998.

**Comment by reedwm** [comment] 2022-11-10 05:13
I can reproduce with this a raw CUDA program, so this is a CUDA issue:

```c++
#include <stdio.h>
#include <cuda_runtime.h>

__global__ void my_kernel(float x, float y, float* z) {
  *z = powf(x, y);
}

int main() {
  float* d_z;
  cudaMalloc(&d_z, sizeof(*d_z));
  my_kernel<<<1, 1>>>(5., 2., d_z);

  float h_z;
  cudaMemcpy(&h_z, d_z, sizeof(h_z), cudaMemcpyDeviceToHost);
  cudaDeviceSynchronize();
  printf("z: %f\n", h_z);  // prints 24.999998
}
```

@nluehr is it expected `powf` might be this inaccurate? If so I'll close this issue.

**Comment by bhack** [comment] 2022-11-10 12:54
@reedwm Is that internally is implemented in CUDA as this gist?

https://colab.research.google.com/gist/bhack/5071ca357b0e860aa99f74185cc4ff1e/untitled195.ipynb

**Comment by bhack** [comment] 2022-11-10 12:57
And the errors bounds are in this relative table:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#intrinsic-functions

**Comment by reedwm** [comment] 2022-11-10 17:53
@bhack. I'm not sure how it's internally implemented. But based on your error bound link, in Table 7 of [this section](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#mathematical-functions-appendix), `powf`'s error can be up to 10 ulps. The example in the original post has all outputs being off by only zero or one ulps, so the error is within the expected range. So I'll close this issue, since this is working as expected.

**Closed by reedwm** 2022-11-10 17:53 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, comp:gpu, TF 2.9

**Comment by bhack** [comment] 2022-11-10 17:55
> @bhack. I'm not sure how it's internally implemented

I was talking about same page:
![immagine](https://user-images.githubusercontent.com/1710528/201170646-ba4b86c3-9b75-4c28-b0c8-1ad8964b48d0.png)

In my Cuda Colab you can see it gives exactly the same result.

**Comment by reedwm** [comment] 2022-11-10 17:58
I see. I won't bother calculating the maximum ulp error based on the expression `exp2f(y * __log2f(x))`, but because the max ulp error in the original post's example is 1, this still falls within the expected ulp range.
