### ISSUE TITLE
tensorflow installation error

### ISSUE THREAD

**Issue by vinayakumarr** [tensorflow/tensorflow#12613] opened 2017-08-26 05:14 UTC
I have installed tensorflow and keras. I have used virtualenviroment given in tensorflow website. It is showing the below error when I try to import keras with tensorflow as backend

 CPU_COUNT = psutil.cpu_count()
AttributeError: 'module' object has no attribute 'cpu_count'

tensorflow version = Version: 1.3.0

keras = Version: 2.0.7

dask = Version: 0.15.0

pandas = Version: 0.20.3

For detailed error, attaching the image
![untitled](https://user-images.githubusercontent.com/18217467/29738791-2213765e-8a4b-11e7-8305-b3fa516097f1.png)

**Comment by Timeroot** [comment] 2017-08-26 07:08
First try running
`sudo pip install --upgrade psutil`
to make sure you have the latest version of psutil, as `cpu_count` was added in version 2.0. Beyond that, this issue seems to be a duplicate of https://github.com/tensorflow/tensorflow/issues/6513 .

**Comment by vinayakumarr** [comment] 2017-08-26 07:15
This worked..

**Closed** 2017-08-26 07:15 UTC
