### ISSUE TITLE
Eager mode: Accessing contents of scalars in a tf.function

### ISSUE THREAD

**Issue by jmgc** [tensorflow/tensorflow#31957] opened 2019-08-25 18:32 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Any
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I am trying to parallel download some images. I am using a `tf.data.Dataset` with the image urls as content. I want to store them in a GCS, so I am using functions from the `tf.io.gfile` package inside a `tf.function`. This function will be called through `tf.data.Dataset.map`.

When the different `tf.io.gfile` functions are called inside the `tf.function`, like `makedirs`, it raises an Error indicating that it requires a binary or unicode string as input:

```TypeError: Expected binary or unicode string, got <tf.Tensor 'StringJoin_1:0' shape=() dtype=string>```

If I try to use `.numpy()`, it is not available, as expected. The result is that I cannot download the images in the GCS.

**Describe the expected behavior**

As a tensorflow package, I would expect the `tf.io.gfile` functions to allow the use of scalar string tensors, or I would expect tensorflow to provide a solution similar to the `.numpy()` function inside `tf.function` for these cases. If not, at least it should be a warning in the documentation that these functions cannot be used inside `tf.function`.

**Code to reproduce the issue**

```python
@tf.function
def test_string(value): 
    return tf.io.gfile.exists(value)

test_string(tf.constant('test'))
```

The result in this case is:

```
TypeError: Expected binary or unicode string, got <tf.Tensor 'value:0' shape=() dtype=string>
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-08-26 08:28
Was reproduced the issue with Tensorflow 1.14.0. Please see the gist [here](https://colab.research.google.com/drive/1EKMMLXpMreIz5_w3qTWKtodnbnBDydwZ). Thanks!

**Comment by jmgc** [comment] 2019-08-26 17:58
@yongtang 

Following your advice, I have made another test using the `tf.io.write_file` function:

```python
import tensorflow as tf

tf.enable_eager_execution()

@tf.function
def test_function(name): 
    tf.io.write_file(name, tf.constant('2'))

test_function(tf.constant('hi.txt'))

print(open('hi.txt').read())
```

The result is a:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-7e9fdc2b4e62> in <module>
----> 1 print(open('hi.txt').read())

FileNotFoundError: [Errno 2] No such file or directory: 'hi.txt'
```

If I do exactly the same, but without the `@tf.function` decorator:

```python
import tensorflow as tf

tf.enable_eager_execution()

def test_function(name): 
    tf.io.write_file(name, tf.constant('2'))

test_function(tf.constant('hi.txt'))

print(open('hi.txt').read())
```

The result is the one expected:

```2```

I assume I am making something wrong, but sincerely I do not know what.

In any case, thanks for your comment.

**Comment by jmgc** [comment] 2019-08-27 06:55
@jvishnuvardhan it is correct that it works for the `tf.io.read_file` and `tf.io.write_file`. However, it does still not work with the `tf.io.gfile` functions.

**Comment by jvishnuvardhan** [comment] 2019-09-03 20:09
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-09-03 20:09 UTC
Labels: TF 1.14, comp:autograph, type:bug
