### ISSUE TITLE
All values come out as 0 while converting int32 to float16 using `tf.image.convert_image_dtype` 

### ISSUE THREAD

**Issue by msteknoadam** [tensorflow/tensorflow#35450] opened 2019-12-27 18:14 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Version 1903
- TensorFlow installed from (source or binary): Source (pip install is source I guess?)
- TensorFlow version (use command below): v1.12.1-21327-gd3457b26a0 2.1.0-dev20191226
- Python version: 3.7.3
- GPU model and memory: GeForce 1050Ti / 16GB of RAM

**Describe the current behavior**
When I convert `int32` type of data to `float16`, all values come out as 0.

**Describe the expected behavior**
The values should be like "1.0" I believe.

**Code to reproduce the issue**
```
>>> x = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=tf.int32)
>>> x
<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>
>>> tf.image.convert_image_dtype(x, dtype=tf.float16, saturate=False) 
<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float16)>
```

**Comment by msteknoadam** [comment] 2019-12-27 18:15
@mihaimaruseac Hello, I created the issue but looks like I can't assign you so I'm just tagging you here.

**Comment by Lasers67** [comment] 2019-12-28 11:21
In the code:

https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/ops/image_ops_impl.py#L1809

using scale as 1/image.dtype.max which is 1/(max Int32) and multiplying leads to very small values of order 1e-10, float16 cannot handle such large precisions, if you use dtype=float32 in convert_image_dtype the value is not 0 but the actual small value.

**Comment by msteknoadam** [comment] 2019-12-28 11:30
Hello, as your comment explains, I think that is some expected thing? But I'm not too sure about this so I'll leave decide to whether to close/not close this issue to @mihaimaruseac

**Comment by mihaimaruseac** [comment] 2019-12-28 16:12
Closing then as it is working as intended.

**Closed by mihaimaruseac** 2019-12-28 16:12 UTC
