### ISSUE TITLE
[TF 2.2] Elapsed time of ConcreteFunction becomes shorter when printing loss

### ISSUE THREAD

**Issue by ktaebum** [tensorflow/tensorflow#40659] opened 2020-06-22 08:49 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    - Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    - Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    - No
- TensorFlow installed from (source or binary):
    - Source
- TensorFlow version (use command below):
    - v2.2.0-0-g2b96f3662b (2.2.0)
- Python version:
    - 3.8.3
- Bazel version (if compiling from source):
    - 2.0.0
- GCC/Compiler version (if compiling from source):
    - 7.5.0
- CUDA/cuDNN version:
    - 10.0 / 7.6
- GPU model and memory:
    - NVIDIA Titan XP (11.9GB)

**Describe the current behavior**

I want to measure forward computation + backward computation time in `tf.function`
with a custom training loop.
Thus I wrapped `tf.function` scope to contain
- model forward
- tape.gradient

(I know that it is much more efficient if I include `apply_gradient` into `tf.function` scope,
but I didn't for my estimation).
If I print loss right after the function call, the estimated time becomes significantly different
(much shorter when w/ print loss, much longer when w/o print loss)

**Describe the expected behavior**

elapsed time should not be shorter when we print loss
(longer could be ok if `tf.function` runs asynchronously. printing loss will synchronize device execution)
(I think it runs asynchronously because if I print loss before applying gradients, throughput goes down and profiled trace shows that `ResourceApplyMomentum` operations are not overlapped with backpropagation)

**Standalone code to reproduce the issue**

Simplest version to reproduce
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import time
import numpy as np

import tensorflow as tf
from tensorflow.python import keras
from tensorflow.python.eager import def_function
from tensorflow.python.keras import applications
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import random_seed
from tensorflow.python.ops import random_ops
from tensorflow.python.ops import losses
from tensorflow.python.eager.backprop import GradientTape

def main():
  model = applications.resnet.ResNet50(True, None)
  bs = 64

  @def_function.function
  def tf_function_scope(x, y_):
    with GradientTape() as tape:
      y = model(x)
      loss = losses.losses_impl.sparse_softmax_cross_entropy(y_, logits=y)
    grads = tape.gradient(loss, model.trainable_variables)
    return loss, grads

  # Train
  optimizer = keras.optimizer_v2.gradient_descent.SGD(0.01)
  for step in range(20):
    fake_x = random_ops.random_uniform([bs, 224, 224, 3], dtype=dtypes.float32)
    fake_y = random_ops.random_uniform([bs,],
                                       minval=0,
                                       maxval=1000,
                                       dtype=dtypes.int64)
    start = time.time()

    loss, grads = tf_function_scope(fake_x, fake_y)
    tf_func_end = time.time()

    print(loss)  # on / off makes different (tf_func_end - start) result
    print((tf_func_end - start) * 1000)

    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    end = time.time()

    print('step %d, took %.3f ms (before apply_gradients: %f), throghput: %f' % \
          (step, (end-start)*1000, (tf_func_end - start)*1000, bs / (end - start)))

if __name__ == '__main__':
  os.environ['CUDA_VISIBLE_DEVICES'] = '0'
  main()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

1. Without print loss
```
2020-06-22 08:42:40.022588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-22 08:42:40.123857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:42:40.124190: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:42:40.126113: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:42:40.127874: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:42:40.128249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:42:40.130484: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:42:40.132267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:42:40.137410: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:42:40.148777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:42:40.190909: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2099905000 Hz
2020-06-22 08:42:40.197116: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b7233c1450 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:42:40.197192: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-22 08:42:40.393986: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b72342ab40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:42:40.394053: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-06-22 08:42:40.397195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:42:40.397284: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:42:40.397334: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:42:40.397374: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:42:40.397414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:42:40.397443: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:42:40.397472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:42:40.397502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:42:40.402115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:42:40.402174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:42:40.405355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:42:40.405380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:42:40.405407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:42:40.412971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11318 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
2020-06-22 08:42:46.001636: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:42:46.209792: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
tf function time: 4361.180067062378
step 0, took 4409.801 ms (before apply_gradients: 4361.180067), throghput: 14.513127
tf function time: 122.9701042175293
step 1, took 160.225 ms (before apply_gradients: 122.970104), throghput: 399.438503
tf function time: 292.9036617279053
step 2, took 329.290 ms (before apply_gradients: 292.903662), throghput: 194.357749
tf function time: 293.7884330749512
step 3, took 329.407 ms (before apply_gradients: 293.788433), throghput: 194.288679
tf function time: 296.1745262145996
step 4, took 331.075 ms (before apply_gradients: 296.174526), throghput: 193.309700
tf function time: 295.7441806793213
step 5, took 328.914 ms (before apply_gradients: 295.744181), throghput: 194.579640
tf function time: 297.3062992095947
step 6, took 328.839 ms (before apply_gradients: 297.306299), throghput: 194.624079
tf function time: 300.38952827453613
step 7, took 336.697 ms (before apply_gradients: 300.389528), throghput: 190.081826
tf function time: 295.8531379699707
step 8, took 333.771 ms (before apply_gradients: 295.853138), throghput: 191.748377
tf function time: 293.9162254333496
step 9, took 330.256 ms (before apply_gradients: 293.916225), throghput: 193.788929
tf function time: 295.107364654541
step 10, took 328.889 ms (before apply_gradients: 295.107365), throghput: 194.594592
tf function time: 296.8401908874512
step 11, took 328.850 ms (before apply_gradients: 296.840191), throghput: 194.617871
tf function time: 298.9656925201416
step 12, took 330.844 ms (before apply_gradients: 298.965693), throghput: 193.444828
tf function time: 300.534725189209
step 13, took 337.954 ms (before apply_gradients: 300.534725), throghput: 189.374994
tf function time: 295.2277660369873
step 14, took 335.415 ms (before apply_gradients: 295.227766), throghput: 190.808195
tf function time: 291.32676124572754
step 15, took 334.997 ms (before apply_gradients: 291.326761), throghput: 191.046658
tf function time: 287.0829105377197
step 16, took 333.483 ms (before apply_gradients: 287.082911), throghput: 191.914116
tf function time: 284.6190929412842
step 17, took 327.860 ms (before apply_gradients: 284.619093), throghput: 195.205059
tf function time: 288.6462211608887
step 18, took 329.876 ms (before apply_gradients: 288.646221), throghput: 194.012187
tf function time: 291.00489616394043
step 19, took 328.769 ms (before apply_gradients: 291.004896), throghput: 194.665292

```

2. with print loss

```
2020-06-22 08:43:03.438864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-22 08:43:03.560570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:43:03.561008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:43:03.563477: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:43:03.565449: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:43:03.565884: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:43:03.568719: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:43:03.570816: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:43:03.575264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:43:03.588127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:43:03.622770: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2099905000 Hz
2020-06-22 08:43:03.628790: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5632029c85b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:43:03.628829: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-22 08:43:03.814060: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563202a31ca0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:43:03.814126: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-06-22 08:43:03.822679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:43:03.822786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:43:03.822813: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:43:03.822833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:43:03.822864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:43:03.822883: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:43:03.822903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:43:03.822934: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:43:03.826928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:43:03.826991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:43:03.830583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:43:03.830633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:43:03.830665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:43:03.835490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11318 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
2020-06-22 08:43:09.605652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:43:09.814419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
loss: tf.Tensor(6.9077563, shape=(), dtype=float32)
tf function time: 4659.780740737915
step 0, took 4717.544 ms (before apply_gradients: 4659.780741), throghput: 13.566382
loss: tf.Tensor(6.907754, shape=(), dtype=float32)
tf function time: 123.58546257019043
step 1, took 376.163 ms (before apply_gradients: 123.585463), throghput: 170.138898
loss: tf.Tensor(6.9077573, shape=(), dtype=float32)
tf function time: 123.61717224121094
step 2, took 368.745 ms (before apply_gradients: 123.617172), throghput: 173.561522
loss: tf.Tensor(6.9077635, shape=(), dtype=float32)
tf function time: 123.36468696594238
step 3, took 367.381 ms (before apply_gradients: 123.364687), throghput: 174.205911
loss: tf.Tensor(6.907756, shape=(), dtype=float32)
tf function time: 122.72977828979492
step 4, took 375.007 ms (before apply_gradients: 122.729778), throghput: 170.663412
loss: tf.Tensor(6.9077506, shape=(), dtype=float32)
tf function time: 123.32725524902344
step 5, took 377.959 ms (before apply_gradients: 123.327255), throghput: 169.330637
loss: tf.Tensor(6.907758, shape=(), dtype=float32)
tf function time: 123.4426498413086
step 6, took 377.844 ms (before apply_gradients: 123.442650), throghput: 169.382137
loss: tf.Tensor(6.907757, shape=(), dtype=float32)
tf function time: 126.03235244750977
step 7, took 374.068 ms (before apply_gradients: 126.032352), throghput: 171.091986
loss: tf.Tensor(6.9077587, shape=(), dtype=float32)
tf function time: 130.0036907196045
step 8, took 373.924 ms (before apply_gradients: 130.003691), throghput: 171.157768
loss: tf.Tensor(6.907766, shape=(), dtype=float32)
tf function time: 122.81250953674316
step 9, took 367.702 ms (before apply_gradients: 122.812510), throghput: 174.053986
loss: tf.Tensor(6.907754, shape=(), dtype=float32)
tf function time: 122.46370315551758
step 10, took 367.749 ms (before apply_gradients: 122.463703), throghput: 174.031643
loss: tf.Tensor(6.9077454, shape=(), dtype=float32)
tf function time: 123.29578399658203
step 11, took 366.575 ms (before apply_gradients: 123.295784), throghput: 174.589101
loss: tf.Tensor(6.9077616, shape=(), dtype=float32)
tf function time: 123.33488464355469
step 12, took 366.533 ms (before apply_gradients: 123.334885), throghput: 174.609088
loss: tf.Tensor(6.9077625, shape=(), dtype=float32)
tf function time: 123.26574325561523
step 13, took 368.901 ms (before apply_gradients: 123.265743), throghput: 173.488161
loss: tf.Tensor(6.907754, shape=(), dtype=float32)
tf function time: 123.28004837036133
step 14, took 378.585 ms (before apply_gradients: 123.280048), throghput: 169.050499
loss: tf.Tensor(6.9077578, shape=(), dtype=float32)
tf function time: 123.01921844482422
step 15, took 367.751 ms (before apply_gradients: 123.019218), throghput: 174.030853
loss: tf.Tensor(6.907749, shape=(), dtype=float32)
tf function time: 122.85351753234863
step 16, took 370.019 ms (before apply_gradients: 122.853518), throghput: 172.964222
loss: tf.Tensor(6.9077587, shape=(), dtype=float32)
tf function time: 123.2306957244873
step 17, took 367.553 ms (before apply_gradients: 123.230696), throghput: 174.124776
loss: tf.Tensor(6.9077473, shape=(), dtype=float32)
tf function time: 122.7264404296875
step 18, took 369.329 ms (before apply_gradients: 122.726440), throghput: 173.287243
loss: tf.Tensor(6.9077606, shape=(), dtype=float32)
tf function time: 123.77810478210449
step 19, took 370.604 ms (before apply_gradients: 123.778105), throghput: 172.691160

```

3. hybrid (print loss when step >= 10)

```
2020-06-22 08:45:28.959617: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-22 08:45:29.091472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:45:29.091790: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:45:29.093565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:45:29.095172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:45:29.095532: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:45:29.097694: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:45:29.099348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:45:29.104566: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:45:29.111665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:45:29.150924: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2099905000 Hz
2020-06-22 08:45:29.157422: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559b110449d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:45:29.157478: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-22 08:45:29.406413: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559b110ae0b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:45:29.406485: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-06-22 08:45:29.413518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-06-22 08:45:29.413695: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:45:29.413772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:45:29.413815: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-06-22 08:45:29.413858: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-06-22 08:45:29.413901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-06-22 08:45:29.413944: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-06-22 08:45:29.413988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:45:29.421650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:45:29.421769: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-06-22 08:45:29.424724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:45:29.424749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:45:29.424774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:45:29.428730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11318 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:05:00.0, compute capability: 6.1)
2020-06-22 08:45:34.957824: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-06-22 08:45:35.250004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
tf function time: 4716.739177703857
step 0, took 4782.601 ms (before apply_gradients: 4716.739178), throghput: 13.381840
tf function time: 120.75352668762207
step 1, took 162.472 ms (before apply_gradients: 120.753527), throghput: 393.912849
tf function time: 288.3281707763672
step 2, took 331.619 ms (before apply_gradients: 288.328171), throghput: 192.992408
tf function time: 286.7617607116699
step 3, took 327.575 ms (before apply_gradients: 286.761761), throghput: 195.374982
tf function time: 288.7263298034668
step 4, took 332.976 ms (before apply_gradients: 288.726330), throghput: 192.206123
tf function time: 285.6485843658447
step 5, took 330.235 ms (before apply_gradients: 285.648584), throghput: 193.801241
tf function time: 285.5794429779053
step 6, took 328.592 ms (before apply_gradients: 285.579443), throghput: 194.770378
tf function time: 286.8924140930176
step 7, took 330.659 ms (before apply_gradients: 286.892414), throghput: 193.552647
tf function time: 287.52660751342773
step 8, took 333.751 ms (before apply_gradients: 287.526608), throghput: 191.759609
tf function time: 282.52458572387695
step 9, took 325.800 ms (before apply_gradients: 282.524586), throghput: 196.439568
loss: tf.Tensor(6.907755, shape=(), dtype=float32)
tf function time: 286.6995334625244
step 10, took 533.805 ms (before apply_gradients: 286.699533), throghput: 119.893993
loss: tf.Tensor(6.9077554, shape=(), dtype=float32)
tf function time: 120.00322341918945
step 11, took 362.584 ms (before apply_gradients: 120.003223), throghput: 176.510883
loss: tf.Tensor(6.907754, shape=(), dtype=float32)
tf function time: 120.20373344421387
step 12, took 364.925 ms (before apply_gradients: 120.203733), throghput: 175.378661
loss: tf.Tensor(6.90776, shape=(), dtype=float32)
tf function time: 120.89180946350098
step 13, took 367.710 ms (before apply_gradients: 120.891809), throghput: 174.050262
loss: tf.Tensor(6.907758, shape=(), dtype=float32)
tf function time: 121.07729911804199
step 14, took 375.999 ms (before apply_gradients: 121.077299), throghput: 170.213015
loss: tf.Tensor(6.907757, shape=(), dtype=float32)
tf function time: 121.16265296936035
step 15, took 371.518 ms (before apply_gradients: 121.162653), throghput: 172.266043
loss: tf.Tensor(6.907759, shape=(), dtype=float32)
tf function time: 121.36077880859375
step 16, took 371.042 ms (before apply_gradients: 121.360779), throghput: 172.487427
loss: tf.Tensor(6.9077525, shape=(), dtype=float32)
tf function time: 120.78547477722168
step 17, took 364.453 ms (before apply_gradients: 120.785475), throghput: 175.605711
loss: tf.Tensor(6.907755, shape=(), dtype=float32)
tf function time: 120.941162109375
step 18, took 375.551 ms (before apply_gradients: 120.941162), throghput: 170.416059
loss: tf.Tensor(6.9077535, shape=(), dtype=float32)
tf function time: 120.76926231384277
step 19, took 362.911 ms (before apply_gradients: 120.769262), throghput: 176.351553
```

**Comment by amahendrakar** [comment] 2020-06-22 18:54
@ktaebum,
Correct me if I'm wrong, but I did not find much difference in the `throghput` time on running the code with print loss and without printing loss. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c83da47d9449d85d41a7bc1bb644ff89/40659.ipynb#scrollTo=xr382M0ATTsf). 

Also, could you please provide the code to reproduce the `hybrid` scenario. Thanks!

**Comment by ktaebum** [comment] 2020-06-23 00:58
@amahendrakar 
Thanks for your response!
Unfortunately, my major curiosity is not `throughput` but elapsed time of `tf_function_scope` (printed as `before apply_gradients`).
In the [gist](https://colab.research.google.com/gist/amahendrakar/c83da47d9449d85d41a7bc1bb644ff89/40659.ipynb#scrollTo=xr382M0ATTsf), elapsed time of `tf_function_scope` is
- 237 ~ 238 ms when print loss before print time
- 556 ~ 558 ms when not print loss before print time

Is there any particular reason why the results are different?

For `hybrid` scenario, I just changed the code line that prints loss as
```
if step >= 10:
  print(loss)
```

**Comment by amahendrakar** [comment] 2020-06-29 11:59
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/c510e4213adf18fe63e3ae566c43388b/40659.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/46959205cd89e9211e0d95f215469d1a/40659-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by rmothukuru** [comment] 2021-06-03 09:06
Could reproduce the issue with Tensorflow Version 2.5. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/444a308c6689841258e172ec03411b0c/40659.ipynb). Thanks!

**Comment by sushreebarsa** [comment] 2023-01-03 11:24
@ktaebum We see you have used the older Tf version which is not actively supported so tried to execute this issue on colab using the latest TF version. Please refer to this [gist](https://colab.research.google.com/gist/sushreebarsa/bb5eab7ccfa4bb6e81a3a4c13abb0575/40659.ipynb#scrollTo=DSWXSiDWWT_G).
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Closed** 2023-01-17 11:55 UTC
Labels: stat:awaiting response, stalled, comp:autograph, type:performance, TF 2.5
