### ISSUE TITLE
(pandas) read_csv(compression='gzip') fails while reading compressed file with tf.gfile.GFile in Python 2

### ISSUE THREAD

**Issue by wmitsuda** [tensorflow/tensorflow#9806] opened 2017-05-10 01:42 UTC
Originally I opened an issue on pandas, apparently it maybe some bug in tensorflow side and they asked to be verified here. The original issue is pandas-dev/pandas#16241

I'm pasting bellow the same steps I used to replicate the behavior in the original issue. The last comment from pandas was about: "At a glance, it looks like gfile.GFile doesn't follow python's IO interface for seek" (please see more details on the original issue linked above)

#### Code Sample, a copy-pastable example if possible

Sample (1)
```python
import tensorflow as tf
import pandas as pd
with tf.gfile.GFile('test.csv') as f: pd.read_csv(f)
```

Sample (2)
```python
import tensorflow as tf
import pandas as pd
with tf.gfile.GFile('test.csv.gz') as f: pd.read_csv(f, compression='gzip')
```

#### Problem description

I'm converting some code to run on Google Cloud, and in the process I'm changing the way my datasets are read. I started using tf.gfile.GFile implementation from Tensorflow, as it is portable and can read both local files and files from storage buckets.

Also in the process I'm changing my code to work with Python 2 instead of Python 3.

Not sure if it is a bug in Pandas or Tensorflow code, but this issue seems similar to #14222, so I'm opening an issue here first.

To reproduce, create two files: test.csv and test.csv.gz locally. Run both samples in python 2. The sample (1) works fine, but sample (2) crashes with an error: "AttributeError: 'NoneType' object has no attribute 'Tell'"

Strangely, both samples work fine in python 3. I'm using the same library versions in python 2 and 3: pandas 0.19.2 and tensorflow 1.0.

#### Expected Output

Both samples should work in python 2.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 32.1.0
Cython: None
numpy: 1.12.0
scipy: 0.19.0
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.5.2
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 2.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.10.3
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
</details>

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: see sample code above
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macos
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.0.0
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: see above

**Comment by drpngx** [comment] 2017-05-11 17:28
I'm not sure what file interface you are expecting from panda. It is looking for `Tell`, but we have `tell`, which is the python `FileIO` interface.

```
>>> f = tf.gfile.GFile('/tmp/foo.txt')
>>> print dir(f)
['_FileIO__mode', '_FileIO__name', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_binary_mode', '_prepare_value', '_preread_check', '_prewrite_check', '_read_buf', '_read_check_passed', '_writable_file', '_write_check_passed', 'close', 'flush', 'mode', 'name', 'next', 'read', 'readline', 'readlines', 'seek', 'size', 'tell', 'write']
>>> close(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'close' is not defined
>>> f.close()
>>> ff = open('/tmp/foo.txt', 'r')
>>> print dir(ff)
['__class__', '__delattr__', '__doc__', '__enter__', '__exit__', '__format__', '__getattribute__', '__hash__', '__init__', '__iter__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'close', 'closed', 'encoding', 'errors', 'fileno', 'flush', 'isatty', 'mode', 'name', 'newlines', 'next', 'read', 'readinto', 'readline', 'readlines', 'seek', 'softspace', 'tell', 'truncate', 'write', 'writelines', 'xreadlines']
```

**Comment by TomAugspurger** [comment] 2017-05-11 19:45
With tensorflow 1.1.0, the exception is a bit different. Running

```python
import pandas as pd
import numpy as np
import tensorflow as tf

df = pd.DataFrame(np.random.randn(10, 2))
df.to_csv("foo.csv.gz", compression="gzip")

pd.read_csv("foo.csv.gz", compression="gzip")

with tf.gfile.GFile("foo.csv.gz") as gf:
    pd.read_csv(gf, compression="gzip")
```

gives,

```pytb
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    pd.read_csv(gf, compression="gzip")
  File "/Users/taugspurger/Envs/py27/lib/python2.7/site-packages/pandas/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/taugspurger/Envs/py27/lib/python2.7/site-packages/pandas/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/taugspurger/Envs/py27/lib/python2.7/site-packages/pandas/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/Users/taugspurger/Envs/py27/lib/python2.7/site-packages/pandas/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/taugspurger/Envs/py27/lib/python2.7/site-packages/pandas/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 562, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:6175)
  File "pandas/_libs/parsers.pyx", line 751, in pandas._libs.parsers.TextReader._get_header (pandas/_libs/parsers.c:9268)
  File "pandas/_libs/parsers.pyx", line 953, in pandas._libs.parsers.TextReader._tokenize_rows (pandas/_libs/parsers.c:11755)
  File "pandas/_libs/parsers.pyx", line 2173, in pandas._libs.parsers.raise_parser_error (pandas/_libs/parsers.c:28589)
TypeError: seek() takes exactly 2 arguments (3 given)
```

```
In [15]: gf.seek?
Signature: gf.seek(position)
```

**Comment by concretevitamin** [comment] 2017-05-11 23:19
I *think* this should be fixed in master.  Here's the `seek()` signature from HEAD:
```python
  def seek(self, offset=None, whence=0, position=None):
```
[Link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py#L131).  Can you retry with a nightly build?

**Comment by wmitsuda** [comment] 2017-05-12 01:21
It is working as expected with the nightly build.

**Comment by drpngx** [comment] 2017-05-12 01:54
Yay!

**Closed by drpngx** 2017-05-12 01:54 UTC
Labels: stat:awaiting response

**Comment by chrisdlangton** [comment] 2017-08-22 05:23
I'm seeing this again for python2 `pandas (0.20.1)` and would love to see zlib used instead of gzip because when i handle the files myself with zlib the issue is fixed but when pandas `pd.read_csv(filename, na_values=['nan'], keep_default_na=False, compression='gzip', error_bad_lines=False, chunksize=chunksize)` is used it fails miserably too often.
