### ISSUE TITLE
Tensorflow Micro: Build issue

### ISSUE THREAD

**Issue by aakbar5** [tensorflow/tensorflow#32309] opened 2019-09-07 10:07 UTC
`micro_vision` and `micro_speech` examples are showing following error on invoking makefile to build
```
/bin/sh: 1: [[: not found
```

My build command is:
```
make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=linux micro_vision
```
The patch to fix this issue is:
```
diff --git a/tensorflow/lite/experimental/micro/tools/make/Makefile b/tensorflow/lite/experimental/micro/tools/make/Makefile
index d2ed2e6234..2779530d02 100644
--- a/tensorflow/lite/experimental/micro/tools/make/Makefile
+++ b/tensorflow/lite/experimental/micro/tools/make/Makefile
@@ -1,3 +1,4 @@
+SHELL := /bin/bash
 
 ifneq (3.82,$(firstword $(sort $(MAKE_VERSION) 3.82)))
   $(error "Requires make version 3.82 or later (current is $(MAKE_VERSION))")
```

Tensorflow repo info:
```
commit 92fc3d02fd3cd086e17659842bfee1bbd62d1838 (HEAD -> master)
Author: Tiezhen WANG <wangtz@google.com>
Date:   Thu Sep 5 07:10:01 2019 -0700

    TFLM: Better format for debug log in `screen`
    
    Otherwise, it's showing up like
    msg1
        msg2
            msg3
    
    PiperOrigin-RevId: 267365236
```
OS Platform and Distribution: Linux Ubuntu 18.04.3 LTS
GCC/Compiler version: 7.3.1

**Comment by rockyrhodes** [comment] 2019-09-09 17:12
Duplicate of #32037 

Please followup on the above bug.  We would like help testing a different fix for this issue.

**Closed by rockyrhodes** 2019-09-09 17:12 UTC
Labels: comp:lite, stat:awaiting tensorflower, type:bug

**Comment by aakbar5** [comment] 2019-10-16 11:53
This issue is still there. I am using Tensorflow tag v2.0.0.
