### ISSUE TITLE
Does tensorflow support mfcc now?

### ISSUE THREAD

**Issue by liuzqt** [tensorflow/tensorflow#11343] opened 2017-07-07 04:38 UTC
Is mfcc support in tensorflow now? I found this https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mfcc.h

but I can't find this op in Python API in tensorflow. 

So is that not open yet? Or it's wrapped in some other Python api?

**Comment by asimshankar** [comment] 2017-07-07 06:00
Closing this as a duplicate of #11339. Let's continue discussion there.

**Closed by asimshankar** 2017-07-07 06:00 UTC
