### ISSUE TITLE
tf.read_file memory leak on python3.7

### ISSUE THREAD

**Issue by schoettner** [tensorflow/tensorflow#30281] opened 2019-07-01 15:14 UTC
Hi,
i noticed a memory leak in python3.7. When I used the dataset.map() function to load images, the process died after a few seconds with an OOM exception. After some testing, I could identify tf.read_file() as the source of this issue. Memory was never released, so all files accumulated to multiple GB of memory in seconds and the process crashes.
```python
def load_img(filename: str, label):
    image_byte = tf.read_file(filename)
    ...
    return processed_image, label

def dummy():
     ...
    load_fn = lambda f, l: load_img(f, l)
    ...
    dataset = tf.data.Dataset.from_tensor_slices(...)
                ...
                .map(load_fn, num_parallel_calls=4)
                ...
                

```
Going back to python3.6, there was no memory leak. An attempt to update to TF1.14.0 on pyhton3.7 failed so I could not verify, if the issue is fixed.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0
- GPU model and memory:

**Comment by ravikyram** [comment] 2019-07-02 12:43
In order to expedite the trouble-shooting process, please provide a full code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-07-09 05:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-09 05:56 UTC
Labels: comp:ops, stat:awaiting response, type:support
