### ISSUE TITLE
MKL inference numbers are incorrect

### ISSUE THREAD

**Issue by derekhh** [tensorflow/tensorflow#13050] opened 2017-09-14 21:51 UTC
In [Performance Guide -> Comparing Compiler Optimizations](https://www.tensorflow.org/performance/performance_guide#comparing_compiler_optimizations), the numbers shared for inference on InceptionV3 and ResNet-50 models are exactly the same.

I'm assuming this is incorrect?

**Comment by cy89** [comment] 2017-09-15 20:29
@tfboyd would you please take a look?

**Comment by tfboyd** [comment] 2017-09-15 22:03
You are correct.  In my effort to format them I must have copied and
pasted.  I will update and get someone to publish it again.  Thank you.

**Comment by tfboyd** [comment] 2017-09-15 22:10
The data you are seeing is InceptionV3 copied twice as an FYI until I get it fixed.

**Comment by derekhh** [comment] 2017-09-18 05:13
@tfboyd - Thanks for the reply. I definitely understand that everyone can and will make mistakes. :) 

I really appreciate the great documentation and work TensorFlowers like you have brought to the community.

**Comment by tfboyd** [comment] 2017-09-19 23:11
cl/169317026  (my tracking purposes)

Sorry about that and here are the updated numbers.  I also had some slightly newer numbers for inception3.  No real difference as a glance but I reran the numbers and did not update the document before I published.  Thank you for understanding.  It might take a little bit to update the site but you have the numbers here for now.  Sorry about the tables we have a slightly different Mark Down engine for the website.  

#### Inference InceptionV3

**Environment**

*   Instance Type: AWS EC2 m4.xlarge
*   CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (Broadwell)
*   Dataset: ImageNet
*   TensorFlow Version: 1.2.0 RC2
*   Test Script: [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/blob/mkl_experiment/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py)

**Batch Size: 1**

Command executed for the MKL test:

```bash
python tf_cnn_benchmarks.py --forward_only=True --device=cpu --mkl=True \
--kmp_blocktime=0 --nodistortions --model=inception3 --data_format=NCHW \
--batch_size=1 --num_inter_threads=1 --num_intra_threads=4 \
--data_dir=<path to ImageNet TFRecords>
```

| Optimization | Data Format | Images/Sec   | Intra threads | Inter Threads |
:              :             : (step time)  :               :               :
| ------------ | ----------- | ------------ | ------------- | ------------- |
| AVX2         | NHWC        | 7.0 (142ms)  | 4             | 0             |
| MKL          | NCHW        | 6.6 (152ms)  | 4             | 1             |
| AVX          | NHWC        | 5.0 (202ms)  | 4             | 0             |
| SSE3         | NHWC        | 2.8 (361ms)  | 4             | 0             |

**Batch Size: 32**

Command executed for the MKL test:

```bash
python tf_cnn_benchmarks.py --forward_only=True --device=cpu --mkl=True \
--kmp_blocktime=0 --nodistortions --model=inception3 --data_format=NCHW \
--batch_size=32 --num_inter_threads=1 --num_intra_threads=4 \
--data_dir=<path to ImageNet TFRecords>
```

| Optimization | Data Format | Images/Sec    | Intra threads | Inter Threads |
:              :             : (step time)   :               :               :
| ------------ | ----------- | ------------- | ------------- | ------------- |
| MKL          | NCHW        | 10.3          | 4             | 1             |
:              :             : (3,104ms)     :               :               :
| AVX2         | NHWC        | 7.5 (4,255ms) | 4             | 0             |
| AVX          | NHWC        | 5.1 (6,275ms) | 4             | 0             |
| SSE3         | NHWC        | 2.8 (11,428ms)| 4             | 0             |

#### Inference ResNet-50

**Environment**

*   Instance Type: AWS EC2 m4.xlarge
*   CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (Broadwell)
*   Dataset: ImageNet
*   TensorFlow Version: 1.2.0 RC2
*   Test Script: [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/blob/mkl_experiment/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py)

**Batch Size: 1**

Command executed for the MKL test:

```bash
python tf_cnn_benchmarks.py --forward_only=True --device=cpu --mkl=True \
--kmp_blocktime=0 --nodistortions --model=resnet50 --data_format=NCHW \
--batch_size=1 --num_inter_threads=1 --num_intra_threads=4 \
--data_dir=<path to ImageNet TFRecords>
```

| Optimization | Data Format | Images/Sec   | Intra threads | Inter Threads |
:              :             : (step time)  :               :               :
| ------------ | ----------- | ------------ | ------------- | ------------- |
| AVX2         | NHWC        | 8.8 (113ms)  | 4             | 0             |
| MKL          | NCHW        | 8.5 (120ms)  | 4             | 1             |
| AVX          | NHWC        | 6.4 (157ms)  | 4             | 0             |
| SSE3         | NHWC        | 3.7 (270ms)  | 4             | 0             |

**Batch Size: 32**

Command executed for the MKL test:

```bash
python tf_cnn_benchmarks.py --forward_only=True --device=cpu --mkl=True \
--kmp_blocktime=0 --nodistortions --model=resnet50 --data_format=NCHW \
--batch_size=32 --num_inter_threads=1 --num_intra_threads=4 \
--data_dir=<path to ImageNet TFRecords>
```

| Optimization | Data Format | Images/Sec    | Intra threads | Inter Threads |
:              :             : (step time)   :               :               :
| ------------ | ----------- | ------------- | ------------- | ------------- |
| MKL          | NCHW        | 12.4          | 4             | 1             |
:              :             : (2,590ms)     :               :               :
| AVX2         | NHWC        | 10.4 (3,079ms)| 4             | 0             |
| AVX          | NHWC        | 7.3 (4,4416ms)| 4             | 0             |
| SSE3         | NHWC        | 4.0 (8,054ms) | 4             | 0             |

**Comment by derekhh** [comment] 2017-09-23 20:54
Thanks @tfboyd for the update! :)

**Comment by gunan** [comment] 2017-10-15 05:53
@tfboyd is this resolved?

**Comment by tfboyd** [comment] 2017-10-15 14:42
with 1.4.  It is so hard to publish content to the website I usually give up unless it is urgent.  The easy solution is to wait for a release.  So when 1.4 becomes root the fix will show up.  So roughly 30+ days after I fixed the content.  @gunan

**Comment by yaroslavvb** [comment] 2017-10-15 16:17
There used to be an option to see "Master" version of the docs on the website, that was useful

**Comment by tfboyd** [comment] 2017-10-15 16:58
Master is still there if you go to versions.  The problem is master is not
updated by any type of job so it is really only updated when an rc
happens.  In a normal world I would have updated the content, waited MAYBE
1 week verified it and marked this issue closed.  This is not related to
Gunhan at all.

**Comment by tfboyd** [comment] 2017-11-09 18:10
Feels like a life time.  Numbers are now on the default page due to 1.4 launching.  Closing and having a personal party and a bit sip of diet cherry coke.  cheers.

**Closed by tfboyd** 2017-11-09 18:10 UTC
Labels: type:docs
