### ISSUE TITLE
I run the code in distributed mode and my code run good in asynchronous mode; but the  code run unsuccessful in synchronous mode

### ISSUE THREAD

**Issue by Crishuang95** [tensorflow/tensorflow#24448] opened 2018-12-19 13:37 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.11
- Python version:3.6
- Bazel version (if compiling from source):0.19
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:no GPU

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
292, in _do_call    return fn(*args)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
277, in _run_fn    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
367, in _call_tf_sessionrun    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef missing attr 'reduction_type'
 from Op<name=ConditionalAccumulator; signature= -> handle:Ref(string); attr=dtype:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; attr=shape:shape; attr=container:string,default=""; attr=shared_name:string,default=""; attr=reduction_type:string,default="MEAN",allowed=["MEAN", "SUM"]; is_stateful=true>; NodeDef: {{node sync_replicas/conditional_accumulator}} = ConditionalAccumulator[_class=["loc:@sync_replicas/SetGlobalStep"], container="", dtype=DT_FLOAT, shape=[3,3,3,16], shared_name="conv0/conv:0/grad_accum", _device="/job:ps/replica:0/task:0/device:CPU:0"]()
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "distributed1.py", line 318, in <module>
    main()
  File "distributed1.py", line 217, in main
    with tf.train.MonitoredTrainingSession(master=server.target, is_chief=True,hooks=[sync_replicas
_hook]) as sess:  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 504, in MonitoredTrainingSession    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 921, in __init__    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 643, in __init__    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 1107, in __init__    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 1112, in _create_session    return self._sess_creator.create_session()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session
.py", line 807, in create_session    hook.after_create_session(self.tf_sess, self.coord)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/sync_replicas_opt
imizer.py", line 494, in after_create_session    session.run(self._local_init_op)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 8
87, in run    run_metadata_ptr)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
110, in _run    feed_dict_tensor, options, run_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
286, in _do_run    run_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1
308, in _do_call    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef missing attr 'reduction_type'
 from Op<name=ConditionalAccumulator; signature= -> handle:Ref(string); attr=dtype:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; attr=shape:shape; attr=container:string,default=""; attr=shared_name:string,default=""; attr=reduction_type:string,default="MEAN",allowed=["MEAN", "SUM"]; is_stateful=true>; NodeDef: {{node sync_replicas/conditional_accumulator}} = ConditionalAccumulator[_class=["loc:@sync_replicas/SetGlobalStep"], container="", dtype=DT_FLOAT, shape=[3,3,3,16], shared_name="conv0/conv:0/grad_accum", _device="/job:ps/replica:0/task:0/device:CPU:0"]()

**Comment by ymodak** [comment] 2018-12-19 17:40
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Crishuang95** [comment] 2018-12-20 00:05
the code is here:
opt = tf.train.MomentumOptimizer(learning_rate=lr_placeholder, momentum=0.9)       opt=tf.train.SyncReplicasOptimizer(opt,replicas_to_aggregate=len(worker_hosts),replica_id=0,total_num_replicas=len(worker_hosts),use_locking=True)
train_op = opt.minimize(full_loss, global_step=global_step)
val_op = validation_op(validation_step, vali_top1_error, vali_loss)
sync_replicas_hook = opt.make_session_run_hook(True)
init=tf.global_variables_initializer()
with training.MonitoredTrainingSession(master=server.target, is_chief=True,hooks=[sync_replicas_hook]) as sess:

**Comment by Crishuang95** [comment] 2018-12-20 00:06
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
the code is here:
opt = tf.train.MomentumOptimizer(learning_rate=lr_placeholder, momentum=0.9) opt=tf.train.SyncReplicasOptimizer(opt,replicas_to_aggregate=len(worker_hosts),replica_id=0,total_num_replicas=len(worker_hosts),use_locking=True)
train_op = opt.minimize(full_loss, global_step=global_step)
val_op = validation_op(validation_step, vali_top1_error, vali_loss)
sync_replicas_hook = opt.make_session_run_hook(True)
init=tf.global_variables_initializer()
with training.MonitoredTrainingSession(master=server.target, is_chief=True,hooks=[sync_replicas_hook]) as sess:

**Comment by lxl910915** [comment] 2018-12-25 12:03
try opt.make_session_run_hook(is_chief) instead of opt.make_session_run_hook(True)

**Comment by lxl910915** [comment] 2018-12-26 02:43
@Crishuang95   
is_chief是不是应该在worker 0上是True，其他worker上是False。

**Comment by ymodak** [comment] 2019-02-08 22:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-02-08 22:52 UTC
Labels: comp:runtime, stat:awaiting response, type:support
