### ISSUE TITLE
BUILD ERROR: bazel could not find "highwayhash/sip_hash.h"

### ISSUE THREAD

**Issue by SioIkzk** [tensorflow/tensorflow#2618] opened 2016-06-02 07:17 UTC
Hi, could you tell me what I should correct?

### Environment info
Operating System: Fedora 23 Server

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): CUDA 7.5.18, cuDNN v4 (4.0.7)

### Steps to reproduce
1. prepare following to the instruction for "install from source" on web page
2. downgrade gcc to 4.9.3 and save user's local (because upper version is still in /usr/bin)
3. get bazel from GitHub
4. bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --verbose_failure

### What have you tried?
1. found the error message which seems not to find the include file of "sip_hash.cc". 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

____Loading package: tensorflow/cc
____Loading package: @bazel_tools//tools/android
WARNING: /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/protobuf/WORKSPACE:1: Workspace name in /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Loading package: @protobuf//
WARNING: /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/highwayhash/WORKSPACE:1: Workspace name in /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/re2/WORKSPACE:1: Workspace name in /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
____Loading package: @re2//
____Loading package: @jsoncpp_git//
____Loading package: tensorflow/core/util/ctc
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
____[34 / 351] Creating source manifest for //tensorflow/cc:tutorials_example_trainer
____[43 / 2,637] Creating source manifest for //tensorflow/cc:ops/array_ops_gen_cc [for host]
____[45 / 2,969] Executing genrule @boringssl_git//:err_data_c
____[46 / 2,973] Creating source manifest for //tensorflow/cc:ops/control_flow_ops_gen_cc [for host]
____[50 / 2,977] Compiling external/highwayhash/highwayhash/sip_hash.cc
____[50 / 2,977] Compiling external/jsoncpp_git/src/lib_json/json_reader.cpp
____[50 / 2,977] Executing genrule @farmhash_archive//:configure
**ERROR: /home/sio/.cache/bazel/_bazel_sio/20abde1548c7cbc7b364a6249f6601f2/external/highwayhash/BUILD:17:1: undeclared inclusion(s) in rule '@highwayhash//:sip_hash':
this rule is missing dependency declarations for the following files included by 'external/highwayhash/highwayhash/sip_hash.cc':**
  '/home/sio/usr/local/include/c++/4.9.3/cstddef'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/c++config.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/os_defines.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/cpu_defines.h'
  '/home/sio/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/stddef.h'
  '/home/sio/usr/local/include/c++/4.9.3/cstring'
  '/home/sio/usr/local/include/c++/4.9.3/memory'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_algobase.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/functexcept.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/exception_defines.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/cpp_type_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/type_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/numeric_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_pair.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/move.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/concept_check.h'
  '/home/sio/usr/local/include/c++/4.9.3/type_traits'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_iterator_base_types.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_iterator_base_funcs.h'
  '/home/sio/usr/local/include/c++/4.9.3/debug/debug.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_iterator.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/ptr_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/predefined_ops.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/allocator.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/c++allocator.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/new_allocator.h'
  '/home/sio/usr/local/include/c++/4.9.3/new'
  '/home/sio/usr/local/include/c++/4.9.3/exception'
  '/home/sio/usr/local/include/c++/4.9.3/bits/atomic_lockfree_defines.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/exception_ptr.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/nested_exception.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/memoryfwd.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_construct.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/alloc_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/alloc_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_uninitialized.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_tempbuf.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_raw_storage_iter.h'
  '/home/sio/usr/local/include/c++/4.9.3/typeinfo'
  '/home/sio/usr/local/include/c++/4.9.3/bits/hash_bytes.h'
  '/home/sio/usr/local/include/c++/4.9.3/iosfwd'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stringfwd.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/postypes.h'
  '/home/sio/usr/local/include/c++/4.9.3/cwchar'
  '/home/sio/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/stdarg.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/atomicity.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/gthr.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/gthr-default.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/atomic_word.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/concurrence.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_function.h'
  '/home/sio/usr/local/include/c++/4.9.3/backward/binders.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/uses_allocator.h'
  '/home/sio/usr/local/include/c++/4.9.3/functional'
  '/home/sio/usr/local/include/c++/4.9.3/tuple'
  '/home/sio/usr/local/include/c++/4.9.3/utility'
  '/home/sio/usr/local/include/c++/4.9.3/bits/stl_relops.h'
  '/home/sio/usr/local/include/c++/4.9.3/initializer_list'
  '/home/sio/usr/local/include/c++/4.9.3/array'
  '/home/sio/usr/local/include/c++/4.9.3/stdexcept'
  '/home/sio/usr/local/include/c++/4.9.3/string'
  '/home/sio/usr/local/include/c++/4.9.3/bits/char_traits.h'
  '/home/sio/usr/local/include/c++/4.9.3/cstdint'
  '/home/sio/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/stdint.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/localefwd.h'
  '/home/sio/usr/local/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/c++locale.h'
  '/home/sio/usr/local/include/c++/4.9.3/clocale'
  '/home/sio/usr/local/include/c++/4.9.3/cctype'
  '/home/sio/usr/local/include/c++/4.9.3/bits/ostream_insert.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/cxxabi_forced.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/range_access.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/basic_string.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/string_conversions.h'
  '/home/sio/usr/local/include/c++/4.9.3/cstdlib'
  '/home/sio/usr/local/include/c++/4.9.3/cstdio'
  '/home/sio/usr/local/include/c++/4.9.3/cerrno'
  '/home/sio/usr/local/include/c++/4.9.3/bits/functional_hash.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/basic_string.tcc'
  '/home/sio/usr/local/include/c++/4.9.3/bits/unique_ptr.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/shared_ptr.h'
  '/home/sio/usr/local/include/c++/4.9.3/bits/shared_ptr_base.h'
  '/home/sio/usr/local/include/c++/4.9.3/ext/aligned_buffer.h'
  '/home/sio/usr/local/include/c++/4.9.3/backward/auto_ptr.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
____Elapsed time: 6.120s, Critical Path: 4.43s

**Comment by SioIkzk** [comment] 2016-06-02 07:25
I saw the page of "highway hash" on GitHub, and found the message keeping "highwayhash/sip_hash.h" because of bazel configuration. Should I correct the source temporarily in this case to build it?

**Comment by aselle** [comment] 2016-06-02 16:57
This may be related to a recent change. I'll inquire about that, but it would be helpful to know if you were able to build with an older version successfully?

**Comment by SioIkzk** [comment] 2016-06-02 22:15
Thanks, aslle! I'll try to build older version while waiting the response. I will report its result again. :-)

**Comment by ysuematsu** [comment] 2016-06-03 20:04
What version of bazel are you using?

This looks familiar to 
https://github.com/tensorflow/tensorflow/issues/469

Can you try downgrade bazel?

**Comment by SioIkzk** [comment] 2016-06-04 08:40
Thanks, yasuematsu. 
Now I'm trying to remove newer bazel. I will report if I get the something progress.

**Comment by chanhkim** [comment] 2016-06-07 15:00
Hi, I have almost same problem, although some environments are different. Is threre any way to fix it ?

My environments are as follows...

- OS : Centos 6.7
- gcc : 4.8.2 (devtollset-2-gcc package)
- bazel : 0.2.3
- CUDA : 7.5.18
- cuDNN : 5
- TensorFlow : r0.9

CPU version compiling succeeded after some modification, but GPU version compiling fails with same error messages above. (Actual error messages are as follows...)


<pre>
...
ERROR: /home1/chkim/.cache/bazel/_bazel_chkim/20a7d6c35f46e64c010eb39bcbc0e998/external/highwayhash/BUILD:17:1: undeclared inclusion(s) in rule '@highwayhash//:sip_hash':
this rule is missing dependency declarations for the following files included by 'external/highwayhash/highwayhash/sip_hash.cc':
  '/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/cstddef'
  '/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h'
  '/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h'
...
</pre>


I downgraded bazel to 0.1.1 version, but it failed at initial time with another errors.
(It seems that there are many differences between 0.2.3 and 0.1.1...)

**Comment by chanhkim** [comment] 2016-06-13 12:55
I found a way to fix my problem. I'm not sure it's right way...

I added my gcc header file path to third_party/gpus/crosstool/CROSSTOOL file.

<pre>
  cxx_builtin_include_directory: "/opt/rh/devtoolset-2/root/usr/include"
  cxx_builtin_include_directory: "/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include"
</pre>

I guess that my problem was due to using another version of gcc that was not installed in system directory.
If same problem, it may works...

**Comment by ysuematsu** [comment] 2016-06-13 22:36
Yes, the problem happens when gcc is installed in other directory.

The issue to fix in configuration phase is tracked in #2413.

**Comment by SioIkzk** [comment] 2016-06-15 14:15
Thank you for all of your comments.
I had been tackled on this issue, but I could not resolve it.

Yes, I have installed the older gcc in my current directory. Maybe I should also install gcc in system directory. 

Anyway, I will try again with new version of tensorflow. Many thanks!

**Comment by noisychannel** [comment] 2016-06-17 06:29
xPost from #469 

FYI : I was able to build the GPU pip package using the changes listed in this install script : https://github.com/noisychannel/tensorflow_install/blob/master/tf_install.sh

Specifically, check the function fix_tf which makes changes in third_party/gpus/crosstool/CROSSTOOL, tensorflow/tensorflow.bzl and tensorflow/stream_executor/BUILD.

**Comment by aselle** [comment] 2016-07-18 18:17
Automatically closing this issue due to lack of recent activity.

**Closed by aselle** 2016-07-18 18:17 UTC
Labels: awaiting response, installation/startup

**Comment by sethbruder** [comment] 2016-07-29 21:49
@SioIkzk My guess is that you want to add each of the include directories referenced in the error message to `CROSSTOOL`, as described by @chanhkim , in the appropriate "toolchain" subsection.

Detail:

I had a very similar problem.
Per the original post, one might think the problem is that a header cannot be located, but this is probably **not** the case.
Looking at the bazel source (v0.3.0), this message ("undeclared inclusion(s) ... missing dependency declarations") is produced when the includes **are** found in a source file, but are in directories that are **not** declared to the build system.
In my case at least, `third_party/gpus/crosstool/CROSSTOOL` required additional `cxx_builtin_include_directory` lines to reference the include directories shown in the "undeclared inclusions" error message.
In particular, if you apply the type of changes mentioned by @noisychannel you may need to make sure you don't replace system include directories in which includes are still discovered -- instead you want to add the new `cxx_builtin_include_directory` lines before the old lines (unless you are sure you don't want to find things in the old directories).
