### ISSUE TITLE
Broken link in Doc [ api_docs/python/tf/test ]

### ISSUE THREAD

**Issue by ramithuh** [tensorflow/tensorflow#28331] opened 2019-05-02 05:12 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: TensorFlow Core 1.13
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/test

**Describe the documentation issue**
The link pointing to the testing guide is broken. 
broken link -  [https://tensorflow.org/api_guides/python/test](https://tensorflow.org/api_guides/python/test)

[A snapshot of the broken link, working as of 22nd Feb 2019](https://web.archive.org/web/20190222060703/https://tensorflow.org/api_guides/python/test)

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by jvishnuvardhan** [comment] 2019-05-02 20:58
@ramithuh Thanks for finding the link and also for providing screenshot of earlier page. Thanks!

**Comment by Saduf2019** [comment] 2020-02-19 06:56
@ramithuh please confirm if you are still facing the issue

**Comment by MarkDaoust** [comment] 2020-02-19 23:36
Thanks, it looks like this is a duplicate of: #26645 
I'll go fix that.

**Closed by MarkDaoust** 2020-02-19 23:36 UTC
Labels: TF 1.13, stat:awaiting tensorflower, type:docs

**Comment by ramithuh** [comment] 2020-02-21 03:26
Thanks!
