### ISSUE TITLE
issue numpy at Bazel build

### ISSUE THREAD

**Issue by spirinvladimir** [tensorflow/tensorflow#43562] opened 2020-09-25 11:21 UTC
In continue #29845:
>@navi63 this issue has no relationship with your question. Please open new issues if they >are issues with TensorFlow library code or please ask other questions on StackOverflow.
>
>Locking conversation here as it has been solved already
>
>_Originally posted by @mihaimaruseac in >https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-613544203_

@mihaimaruseac New contributors have a problem with build with Bazel. What is a solution you refer once you locked not resolved issue?!
Is any valid build instruction?

**Comment by spirinvladimir** [comment] 2020-09-25 11:55
I did investigation. There are a lot off open/close issues at numpy repo about error message we are getting during build with Bazel. Such closed issues was closed without code change. So problem exist. Best solution describe build process with Bazel at CI/CD here.

**Comment by amahendrakar** [comment] 2020-09-25 13:15
@spirinvladimir,
In order to expedite the trouble-shooting process, could you please provide the below details 

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and the complete error log with the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by spirinvladimir** [comment] 2020-09-25 15:16
@amahendrakar I do not have an issue. There is a problem at numpy and tensorflow by luck of using numpy.
Please use all details from not resolved issue #29845. I create this one cause not resolution was provided to locked issue  #29845.

**Comment by spirinvladimir** [comment] 2020-09-25 15:18
I as part of open-source community glad to know exactly resolution:
>Locking conversation here as it has been solved already

**Comment by mihaimaruseac** [comment] 2020-09-25 16:31
Hi, @spirinvladimir 

First, issue you link to has been resolved: https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-612574610

Next comment on the issue is an unrelated problem (building a protobuf file vs building TF): https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-613265619 That's why in my comment, which you quoted, I say the issue has been resolved; https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-613544203

The install from source page mentions that users have to install numpy before building. It's the second code block on the page, before any `blaze` command. https://www.tensorflow.org/install/source

Error also suggest installing numpy in the environment of the Python interpreter that is used during compilation:
```
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
```

Finally, same solution (make sure numpy is installed for the python you are using) is also listed in the issue you quoted: https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-613303239

So, to reiterate the solution: make sure your environment that you use to build TF has numpy installed. Best is to create a virtual environment, install numpy there and use the same python for `./configure.py`.

If this still does not work, feel free to post actual compile logs and fill in issue template.

**Comment by spirinvladimir** [comment] 2020-09-27 18:12
Hi, @mihaimaruseac 

I do understand logic and relation of links to text you write.
I think I got a point. 💡 😄 
@google I tried to help tensorflow. 👍

**Comment by mihaimaruseac** [comment] 2020-09-28 17:20
Can we close the issue now? Or are there still things left unsolved?

**Comment by spirinvladimir** [comment] 2020-09-28 17:24
Up to you.

**Closed** 2020-09-28 17:25 UTC
Labels: stat:awaiting response, type:build/install
