### ISSUE TITLE
tf.image.resize_image_with_crop_or_pad() is taking too much time to process an image or batch of images

### ISSUE THREAD

**Issue by aisuni** [tensorflow/tensorflow#16396] opened 2018-01-25 07:43 UTC
ISSUE: 
I am stuck in fine tuning imagenet data rendering speed for the reason being tf.image.resize_image_with_crop_or_pad() is taking too much time to process an image or batch of images. 
```Testing was done by preprocessing ONE image (no batching) and an observed latency was `~160msec`. ```

NOTE: I did not observe memory pressure or any possible compute bottleneck during this time. 
Description:
I have a tool to load ImageNet dataset which reads the dataset from processed TFRecords and returns an iterator object to iterate over the datasets with a shuffle and repeat.
I have been observing slow rendering of data due to some overtime by certain steps in image (batch of images) pre-preprocessing. This is really impacting in data rendering speed and hence the slow training of models(Reference here is AlexNet). 

Here is the `snip` of time taken for each operation,
<img width="1425" alt="imagenet_loader_perf_profile" src="https://user-images.githubusercontent.com/35795681/35406079-d4ec3584-01bc-11e8-9ba6-50e4dabba29e.png">

Here is a `snip`  of data preprocess methods,
```
def _parse_example_proto(dataset, height, width, depth, dtype, num_parallel_calls):
    def _input_parser(record):
        keys_to_features = {
            "image/encoded": tf.FixedLenFeature((), tf.string, default_value=""),
            "image/format": tf.FixedLenFeature((), tf.string, default_value="jpeg"),
            "image/class/label": tf.FixedLenFeature([], dtype=tf.int64, default_value=-1),
        }
        parsed = tf.parse_single_example(record, keys_to_features)
        image = tf.image.decode_jpeg(parsed["image/encoded"], channels=depth)
        image = tf.image.convert_image_dtype(image, dtype=dtype)
        label = tf.cast(parsed["image/class/label"], tf.int32)
        return image, label
    return dataset.map(_input_parser, num_parallel_calls=num_parallel_calls)

def _dataset_preprocess_fn(dataset, height, width, num_parallel_calls):
    def _preprocess_fn(image, label):
        image = tf.image.resize_image_with_crop_or_pad(image, height + 8, width + 8 )
        image = tf.random_crop(image, [height, width, 3])
        image = tf.image.random_flip_left_right(image)
        image = (ISTD * image) + MEAN  #dataset level MEAN
        return image, label
    return dataset.map(_preprocess_fn, num_parallel_calls=num_parallel_calls)
```
### System information
- **OS Platform and Distribution *:  Linux Centos 7.2
- **TensorFlow installed from (source or binary)**: 1.4.0 rc1 ( commit hash badd356)
- **TensorFlow version (use command below)**:  b'v1.3.0-rc1-4546-gef196f3' 1.4.0-rc1
- **Python version**:  3.4.5
- **Bazel version (if compiling from source)**: Build label: 0.8.1
- **CUDA/CUDAnn version**: CUDA 9 and  CUDAnn 7.0
- **GPU model and memory**: Volta 100, 16GiB

I am using Amazon Instance and here are the details,
```
GPUs - Tesla V100
GPU Memory (GB): 16
vCPUs : 8
Memory (GB):61
Network Bandwidth: Upto 10Gbps
EBS Bandwidth: 1.5 Gbps
```

**Comment by tensorflowbutler** [comment] 2018-01-25 19:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce

**Comment by aisuni** [comment] 2018-01-25 19:25
Have I written custom code: N/A
Exact command to reproduce:
```
    def input_fn( **kwargs):

        # Dataset args
        repeat = kwargs.get('repeat', True)
        shuffle = kwargs.get('shuffle', True)

        # List TFrecords
        # split args will have 'train' or 'validate'
        filenames = self._get_filenames(split)
        
        # Serialized
        dataset = tf.data.TFRecordDataset(filenames)
        # Process dataset for training only.
        if split.strip().lower() == 'train':
            if repeat:
                dataset = dataset.repeat()
            if shuffle:
                dataset = dataset.shuffle(buffer_size=len(filenames))

        # Add parallelism in input process.
        dataset = _parse_example_proto(dataset, 224, 224, 3, tf.float32, num_parallel_calls=4):
        dataset = _dataset_preprocess_fn(dataset, 224, 224, num_parallel_calls=4)
        # Process dataset for training only.
        if split.strip().lower() == 'train':
            if shuffle:
                dataset = dataset.shuffle(buffer_size=5000)
        # Combines consecutive elements of this dataset into batches
        dataset = dataset.batch(bsz)
        # Batch iterator
        iterator = dataset.make_one_shot_iterator()
        input_batch, labels_batch = iterator.get_next()
        labels_batch = tf.one_hot(labels_batch, 1000)
        return input_batch, labels_batch
def _parse_example_proto(dataset, height, width, depth, dtype, num_parallel_calls):
    def _input_parser(record):
        keys_to_features = {
            "image/encoded": tf.FixedLenFeature((), tf.string, default_value=""),
            "image/format": tf.FixedLenFeature((), tf.string, default_value="jpeg"),
            "image/class/label": tf.FixedLenFeature([], dtype=tf.int64, default_value=-1),
        }
        parsed = tf.parse_single_example(record, keys_to_features)
        image = tf.image.decode_jpeg(parsed["image/encoded"], channels=depth)
        image = tf.image.convert_image_dtype(image, dtype=dtype)
        label = tf.cast(parsed["image/class/label"], tf.int32)
        return image, label
    return dataset.map(_input_parser, num_parallel_calls=num_parallel_calls)

def _dataset_preprocess_fn(dataset, height, width, num_parallel_calls):
    def _preprocess_fn(image, label):
        image = tf.image.resize_image_with_crop_or_pad(image, height + 8, width + 8 )
        image = tf.random_crop(image, [height, width, 3])
        image = tf.image.random_flip_left_right(image)
        image = (ISTD * image) + MEAN  #dataset level MEAN
        return image, label
    return dataset.map(_preprocess_fn, num_parallel_calls=num_parallel_calls)
```

**Comment by aisuni** [comment] 2018-01-26 19:49
Hi @tensorflowbutler , Hope you have all required data from me. Thanks.

**Comment by tensorflowbutler** [comment] 2018-02-21 13:18
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-08 19:27
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zheng-xq** [comment] 2018-03-08 19:37
Assigning @raghuraman-k. This result is quite strange. It measures the graph construction time, not the actual graph execution time. So it's quite strange that tf.image.resize_image_with_crop_or_pad is taking a lot of time during graph construction.

**Comment by tensorflowbutler** [comment] 2018-03-25 00:54
Nagging Assignee @raghuraman-k: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:28
Nagging Assignee @raghuraman-k: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-23 18:40
Nagging Assignee @raghuraman-k: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:03
Nagging Assignee @raghuraman-k: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:03
Nagging Assignee @raghuraman-k: It has been 78 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:50
Nagging Assignee @raghuraman-k: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging Assignee @raghuraman-k: It has been 108 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging Assignee @raghuraman-k: It has been 123 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:00
Nagging Assignee @raghuraman-k: It has been 138 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:03
Nagging Assignee @raghuraman-k: It has been 153 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:45
Nagging Assignee @raghuraman-k: It has been 168 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:39
Nagging Assignee @raghuraman-k: It has been 183 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:45
Nagging Assignee @raghuraman-k: It has been 198 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:45
Nagging Assignee @raghuraman-k: It has been 213 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:48
Nagging Assignee @raghuraman-k: It has been 228 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-10-24 03:18
@aisuni Is this still an issue with the latest version of TensorFlow?

**Comment by ymodak** [comment] 2018-10-30 17:09
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-30 17:09 UTC
Labels: stat:awaiting response
