### ISSUE TITLE
ssd_mobilenet_v2 frozen model size much larger than ssd_mobilenet_v1

### ISSUE THREAD

**Issue by enochkid** [tensorflow/tensorflow#22233] opened 2018-09-12 09:41 UTC
Hi, comparing the pre-trained models published on tensorflow object detection model zoo, why the frozen_model/check_point/saved_model of ssd_mobilenet_v2_coco is much larger than the ones of ssd_mobilenet_v1_coco? mobilenet v2 should be more lite than mobilenet v1.

**Comment by tensorflowbutler** [comment] 2018-09-12 18:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-27 19:08
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-21 19:04
Nagging Assignee @achowdhery: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 19:11
Nagging Assignee @shashishekhar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-29 19:15
Nagging Assignee @shashishekhar: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achowdhery** [comment] 2019-01-28 23:34
Please try using ssdlite for mobilenet v2: http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz

**Comment by ymodak** [comment] 2019-08-28 21:23
Closing this issue since its resolved. Feel free to reopen if have any further problems. Thanks!

**Closed by ymodak** 2019-08-28 21:23 UTC
Labels: comp:lite
