### ISSUE TITLE
[TF2.0alpha] Eagerness/Distribute Strategies performance issues

### ISSUE THREAD

**Issue by meyerjo** [tensorflow/tensorflow#27195] opened 2019-03-27 10:23 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04/18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-dev20190327
- Python version: 3.6
- CUDA/cuDNN version: 10.0
- GPU model and memory: TITAN X 12 GB

**Describe the current behavior**

I have some code, where to the best of my knowledge not everything can be wrapped with the tf.function. Thus, in the function calling strategy.experimental_run I removed the `@tf.function` wrapper. However, this tremendously decreases the overall performance and falls way behind the 'normal' eager execution. 

For the toy example in this issue, these are the performance differences:

```
Computing for 1000-steps, no strategy: Time: 7.228003740310669 sec
Computing for 1000-steps, strategy with tf-function: Time: 2.6209354400634766
Computing for 1000-steps, strategy with no tf-function: Time: 63.60745906829834
```

**Describe the expected behavior**
I would expect that without tf.function at least the usual performance of eagerness is achieved.

**Code to reproduce the issue**

```python
import time

import tensorflow as tf


class DebugModel(tf.keras.Model):
  def __init__(self):
    super(DebugModel, self).__init__()
    self.dense = tf.keras.layers.Dense(20, activation='relu', input_shape=(5,))

  def __call__(self, input, *args, **kwargs):
    x = self.dense(input)
    return x


def train_step(input):
  with tf.GradientTape() as tape:
    out = my_model(input)
    my_loss = -tf.reduce_mean(out)
  gradients = tape.gradient(my_loss, my_model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, my_model.trainable_variables))
  return my_loss


def distributed_train():
  return strategy.experimental_run(train_step, train_iterator)

@tf.function
def distributed_train_tf_function():
  return strategy.experimental_run(train_step, train_iterator)


if __name__ == '__main__':
  dataset = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([3000, 16, 5])))
  N_steps = 1000

  # Plain computation
  my_model = DebugModel()
  optimizer = tf.keras.optimizers.Adam(1e-2)
  _s = time.time()
  i = 0
  for data in dataset:
    if i >= N_steps:
      break
    train_step(data)
    i += 1
  print('Computing for {}-steps, no strategy: Time: {} sec'.format(
      N_steps, time.time() - _s))


  # Mirrored strategy with @tf.function
  dataset = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([3000, 16, 5])))
  strategy = tf.distribute.MirroredStrategy()

  with strategy.scope():
    train_iterator = strategy.make_dataset_iterator(dataset)
    train_iterator.initialize()
    optimizer = tf.keras.optimizers.Adam(1e-2)
    my_model = DebugModel()

    _s = time.time()
    for s in range(N_steps):
      distributed_train_tf_function()
    print('Computing for {}-steps, strategy with tf-function: Time: {}'.format(
      N_steps, time.time() - _s))


  # Mirrored strategy without @tf.function decorator
  dataset = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([3000, 16, 5])))
  strategy = tf.distribute.MirroredStrategy()
  with strategy.scope():
    train_iterator = strategy.make_dataset_iterator(dataset)
    train_iterator.initialize()
    optimizer = tf.keras.optimizers.Adam(1e-2)
    my_model = DebugModel()

    _s = time.time()
    for s in range(N_steps):
      distributed_train()
    print('Computing for {}-steps, strategy with no tf-function: Time: {}'.format(
      N_steps,
      time.time() - _s))
```

**Comment by meyerjo** [comment] 2019-04-01 08:47
@goldiegadde @dynamicwebpaige Would be nice to see some progress on this issue

**Comment by mdanatg** [comment] 2019-04-01 23:52
Assigning to @alextp for triage.

I might be wrong, but at a glance it might be a caching issue. You might want to wrap `train_step` into a `tf.function`.

**Comment by shashvatshahi1998** [comment] 2019-04-08 05:09
@alextp can you please guide me, I want to work on this issue.

**Comment by alextp** [comment] 2019-04-08 16:06
@shashvatshahi1998 the first step is to try to reproduce the issue, and then try to follow @mdanatg 's advice to wrap train_step in tf.function and see whether the issue goes away.

If it doesn't, running a profiler like python's cprofiler on the code to find out what is happening and triaging that to a separate issue is the next step.

**Comment by meyerjo** [comment] 2019-04-08 16:18
Wrapping train_step in tf.function does not work. It raises the following error: ```RuntimeError: `merge_call` called while defining a new graph. [...]```.

**Comment by alextp** [comment] 2019-04-08 16:24
@guptapriya is this a known issue internally?

**Comment by guptapriya** [comment] 2019-04-08 18:57
There are couple of things mentioned here, let me clarify:
1. Performance without tf.function when using distribution strategy is terrible - this is known issue and we do not recommend doing this right now, and it is not something we are prioritizing yet either. The recommended approach is to wrap experimental_run inside a tf.function. Fixing this requires a significant amount of work inside MirroredStrategy. 

2. Wrapping just the train_step into a tf.function: The error seen there is also known, and I am working on fixing that. However, that will not address the performance issue from #1. For anyone who can wrap their train_step in a tf.function, they should be able to wrap strategy.experimental_run inside the tf.function as well - AND get the performance benefit. So there is not a great reason yet to wrap just the train_step into a tf.function but not strategy.run. So while I am working on fixing that issue, it will still not help with performance.

Hope this helps. Please let me know if there are more questions.

**Comment by meyerjo** [comment] 2019-04-08 20:03
@guptapriya Regarding 1.), this is rather confusing to me. My main problem causing this issue was my dependance on eager execution during the forward/backward pass. 
However, wrapping my experimental_run with tf.function straps me from the eager execution. The new TF policy should not be eager-execution is the default except you want to use multiple GPUs for training, should it?

**Comment by alextp** [comment] 2019-04-08 20:14
@meyerjo Ideally eager execution is available and performant for all use cases on day 1, but we have limited resources and have to prioritize what gets done first and then what gets fast first. I agree with @guptapriya's priorities outlined above as being the best to move the existing ecosystem forward, and I'm sure that once performance is good for the tf.function use cases we'll start to improve it for pure-eager multi-gpu.

**Comment by tensorflowbutler** [comment] 2019-06-20 12:36
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-07-05 12:32
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-07-25 12:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-08-09 12:37
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-08-24 12:21
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-09-08 12:23
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Closed** 2019-09-08 12:23 UTC
Labels: TF 2.0.0-alpha0, stat:awaiting response, stat:ds-triaged, type:bug
