### ISSUE TITLE
reader_ops_test failing on windows for Bazel CI

### ISSUE THREAD

**Issue by katre** [tensorflow/tensorflow#10499] opened 2017-06-07 18:53 UTC
On Bazel's CI system, TensorFlow's reader_ops_test is failing on all Windows builds, and has been since between June 1 and June 5:
http://ci.bazel.io/view/Dashboard/job/TensorFlow/863/

The logs don't show anything useful, unfortunately.:
http://ci.bazel.io/view/Dashboard/job/TensorFlow/862/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-msvc-x86_64/consoleFull
```
FAIL: //py_test_dir/tensorflow/python/kernel_tests:reader_ops_test (see C:/tmp/_bazel_system/bcthfi-n/execroot/org_tensorflow/bazel-out/msvc_x64-py3-opt/testlogs/py_test_dir/tensorflow/python/kernel_tests/reader_ops_test/test.log)
INFO: From Testing //py_test_dir/tensorflow/python/kernel_tests:reader_ops_test:
==================== Test output for //py_test_dir/tensorflow/python/kernel_tests:reader_ops_test:
..........================================================================================
```

**Comment by gunan** [comment] 2017-06-08 05:56
@meteorcloudy told us that this is actually a bug in bazel:
https://github.com/bazelbuild/bazel/issues/3134

Closing this issue as this is not a bug in TF.
Please reopen if investigation in bazel proves otherwise.

**Closed by gunan** 2017-06-08 05:56 UTC
