### ISSUE TITLE
Tensorflow distributed RNN crashed on ProtoBuf when using 3*512 rnn. 

### ISSUE THREAD

**Issue by bixiongxu** [tensorflow/tensorflow#3766] opened 2016-08-12 10:34 UTC
### Environment info
Operating System:
Linux XNLPEXP2 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Azure VM 8 cores, 56GB memory

If installed from binary pip package, provide:
pip 8.1.2 from /home/xubixiong/.local/lib/python2.7/site-packages (python 2.7)
0.10.0rc0

### Steps to reproduce
1. Create 2*PS + 2*worker, 
2. Try 3 * 512 RNN, (I changed some code in rnn/translate to make it distributed), worker0 will 100% crash on some code related to TensorBuf and run global_step, the stack is at the end of this post, same everytime
3. Smaller the RNN, make it 1*128, it works fine. 

### What have you tried?
1.  tensorflow.python.framework.errors.UnavailableError is said to not used in the document. 
2. The crashing line is TensorBuffer* buf = tensorflow::TensorCApi::Buffer(src); in tensorflow/core/client/tensor_c_api.cc:
3. I try to smaller the RNN size and layers, then there is no problem. 
4. Is it a known issue, I did find some issue relating to TensorBuf, but not the exactly same case. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
E tensorflow/core/client/tensor_c_api.cc:485]
Traceback (most recent call last):
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 346, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 343, in main
    train()
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 215, in train
    with sv.managed_session(server.target, config=sess_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 942, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 768, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 357, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 931, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 683, in prepare_or_wait_for_session
    self.start_standard_services(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 624, in start_standard_services
    current_step = training_util.global_step(sess, self._global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/training_util.py", line 50, in global_step
    return int(sess.run(global_step_tensor))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call    raise type(e)(node_def, op, message)tensorflow.python.framework.errors.UnavailableError

**Comment by girving** [comment] 2016-08-12 16:32
@josh11b What's `UnavailableError`?  I haven't seen it before.

**Comment by josh11b** [comment] 2016-08-12 16:40
"Raised when the runtime is currently unavailable."
Since I don't see any TensorFlow code creating that error, I suspect it is coming from GRPC.

**Comment by girving** [comment] 2016-08-12 16:41
@mrry Can you take a look?

**Comment by bixiongxu** [comment] 2016-08-12 16:54
Hi, guys,

Also When i used small RNN, such as 1*128, the same exception raise on worker 0 when I restore from the checkpoint, after worker run another hundreds of  steps from the ckpt. And after worker 0 is down, worker 1 can continue running until i shut down ps server manually.
Fresh running on small RNN is fine as I said in the post.

I have monitored the memory usage, it is always below 10%.

Thank you!


Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 12:43 AM +0800, "Geoffrey Irving" <notifications@github.com<mailto:notifications@github.com>> wrote:


@mrry<https://github.com/mrry> Can you take a look?

-

**Comment by bixiongxu** [comment] 2016-08-12 16:58
Sorry for word missing in last mail.
After restoring worker 0 raise unavailable error after worker 1 run hundreds of steps from ckpt. It seems like a timeout.


Also When i used small RNN, such as 1*128, the same exception raise on worker 0 when I restore from the checkpoint, after worker 1 run another hundreds of steps from the ckpt. And after worker 0 is down, worker 1 can continue running until i shut down ps server manually.
Fresh running on small RNN is fine as I said in the post.

I have monitored the memory usage, it is always below 10%.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 12:43 AM +0800, "Geoffrey Irving" <notifications@github.com<mailto:notifications@github.com>> wrote:


@mrry<https://github.com/mrry> Can you take a look?

-

**Comment by mrry** [comment] 2016-08-12 17:20
When you see an `UnavailableError`, this is most likely caused by another (remote) process crashing. Since it seems to depend on the size of your RNN, I suspect something is hitting the 2GB limit for protobuf serialization, but it's not clear what that might be. Can you capture the logs for any other crashed processes to see if there's more information in there?

**Comment by bixiongxu** [comment] 2016-08-12 17:37
Of course.
Although so far worker 0 is the only one who crashed. And small rnn worker 0 also crashes when it restores from ckpt.

But for distributed training , 2 GB shouldn't be enough. I saw some fix about the protonuf  2GB crash in github. It seems being done by add a check and return. Any other plans to make it fit for larger data?

Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 1:22 AM +0800, "Derek Murray" <notifications@github.com<mailto:notifications@github.com>> wrote:


When you see an UnavailableError, this is most likely caused by another (remote) process crashing. Since it seems to depend on the size of your RNN, I suspect something is hitting the 2GB limit for protobuf serialization, but it's not clear what that might be. Can you capture the logs for any other crashed processes to see if there's more information in there?

-

**Comment by bixiongxu** [comment] 2016-08-12 17:40
And, when i shut down ps, worker 1 will raise this exception, followed by a network error message. But I am sure when work 0 raise this exception, no other process is down.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 1:22 AM +0800, "Derek Murray" <notifications@github.com<mailto:notifications@github.com>> wrote:


When you see an UnavailableError, this is most likely caused by another (remote) process crashing. Since it seems to depend on the size of your RNN, I suspect something is hitting the 2GB limit for protobuf serialization, but it's not clear what that might be. Can you capture the logs for any other crashed processes to see if there's more information in there?

-

**Comment by mrry** [comment] 2016-08-12 17:49
The current recommend workaround to the 2GB limit is to use a [variable partitioner](https://www.tensorflow.org/versions/r0.10/api_docs/python/state_ops.html#variable-partitioners-for-sharding) that splits the variable transfer into multiple smaller transfers.

Getting an exception in a worker when you call a PS task that it's using is expected behavior. A typical distributed deployment using `tf.train.Supervisor` (e.g. on Kubernetes) will automatically restart any process when it fails.

**Comment by bixiongxu** [comment] 2016-08-12 17:53
Ok, i will try it out. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 1:51 AM +0800, "Derek Murray" <notifications@github.com<mailto:notifications@github.com>> wrote:


The current recommend workaround to the 2GB limit is to use a variable partitioner<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fwww.tensorflow.org%2fversions%2fr0.10%2fapi_docs%2fpython%2fstate_ops.html%23variable-partitioners-for-sharding&data=01%7c01%7cbix%40064d.mgd.microsoft.com%7cb294e90bda764d872a2f08d3c2d94235%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=E%2b66PmyQw8J1Lh4hgi2aqwwFNnu7biH3E8%2bi9sQHdbY%3d> that splits the variable transfer into multiple smaller transfers.

Getting an exception in a worker when you call a PS task that it's using is expected behavior. A typical distributed deployment using tf.train.Supervisor (e.g. on Kubernetes) will automatically restart any process when it fails.

-

**Comment by DjangoPeng** [comment] 2016-08-15 01:58
@bixiongxu I'm trying to change the seq2seq model to distributed model. Could I ask you some question about that? My email is pjt73651@gmail.com, look forward to your reply!

**Comment by bixiongxu** [comment] 2016-08-15 02:29
@DjangoPeng, my mail is peter@questmatic.com<mailto:peter@questmatic.com>.
Welcome to discuss.

**Comment by DjangoPeng** [comment] 2016-08-15 02:36
@bixiongxu My problem is that my workers server hanging on forever, and I don't know what happened in the `Session.run()`. Could you have a look at [issue#3762](https://github.com/tensorflow/tensorflow/issues/3762).

**Comment by bixiongxu** [comment] 2016-08-16 04:41
@mrry I have added variable partition in my code, but still got the same exception (on same line: E tensorflow/core/client/tensor_c_api.cc:485)  on Worker 0, while Worker1 can start training... 

The whole model is wrapped by a variable_scope with a partitioner, so in theory it will work to solve the problem. I will keep trying and appreciate to have some suggestions from you. 

I extracted some code as below: 

def train():
	"""Train a en->fr translation model using WMT data."""
        #   Build cluster....
         #  Start server
	print ("Create Server with Task Index %d" % FLAGS.task_index)
	if FLAGS.job_name == "ps":
		server.join()
	elif FLAGS.job_name == "worker":
                # Initialize something..........
		with tf.variable_scope("soulmate", partitioner=tf.variable_axis_size_partitioner(
				max_shard_bytes=33554432), reuse=True):
			with tf.device(tf.train.replica_device_setter(
				worker_device="/job:worker/task:%d" % FLAGS.task_index,
				cluster=cluster)) as dev:

				# Create model.
				print("Creating %d layers of %d units." % (FLAGS.num_layers, FLAGS.size))
				model = create_model_fresh(False)	
				summary_op = tf.merge_all_summaries()
				init_op = tf.initialize_all_variables()
				print(model.global_step.name)
				print(model.learning_rate.name)
				# Create a "supervisor", which oversees the training process.
				sv = tf.train.Supervisor(is_chief=(FLAGS.task_index == 0),
									 logdir=FLAGS.train_dir,
									 init_op=init_op,
									 summary_op=None,
									 saver=None,
									 global_step=None,
									 recovery_wait_secs=10)
				
				print("Global_step is placed on " + model.global_step.device + ", will be initialized on " + model.global_step.initializer.device)
				
				if FLAGS.task_index == 0:
					print("Worker %d: Initializing session..." % FLAGS.task_index)
				else:
					print("Worker %d: Waiting for session to be initialized..." % FLAGS.task_index)
				time_begin = time.time()	
				with sv.managed_session(server.target) as sess:
					print("Worker %d: Session initialization complete." % FLAGS.task_index)
					print("in %f secs." % (time.time()-time_begin))
					
					# This is the training loop.
					step_time, loss = 0.0, 0.0
					current_step = 0
					current_global_step = 0
					previous_losses = []
					while not sv.should_stop():
						# in [0, 1] and use the corresponding interval in train_buckets_scale.
						random_number_01 = np.random.random_sample()
						bucket_id = min([i for i in xrange(len(train_buckets_scale))
									   if train_buckets_scale[i] > random_number_01])

						# Get a batch and make a step.
						start_time = time.time()
						encoder_inputs, decoder_inputs, target_weights = model.get_batch(
							train_set, bucket_id)
						_, step_loss, _ = model.step(sess, encoder_inputs, decoder_inputs,
												   target_weights, bucket_id, False)

						step_time += (time.time() - start_time) / FLAGS.steps_per_checkpoint
						loss += step_loss / FLAGS.steps_per_checkpoint
						current_step += 1
						
				sv.stop()

And the stack: 

E tensorflow/core/client/tensor_c_api.cc:485]
I tensorflow/core/distributed_runtime/master_session.cc:651] DeregisterGraph error: Aborted: Graph handle is not found: . Possibly, this worker just restarted.
I tensorflow/core/distributed_runtime/master_session.cc:651] DeregisterGraph error: Aborted: Graph handle is not found: . Possibly, this worker just restarted.
Traceback (most recent call last):
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 349, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 346, in main
    train()
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/translate.py", line 239, in train
    target_weights, bucket_id, False)
  File "/home/xubixiong/soulmate/intent_trainer/rnn/translate/seq2seq_model.py", line 228, in step
    outputs = session.run(output_feed, input_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.UnavailableError

**Comment by bixiongxu** [comment] 2016-08-16 09:14
I try another partitioner:  **tf.min_max_variable_partitioner(max_partitions=50, axis=0,min_slice_size=8 << 10)** , got same crash on worker 0. 
I printed the partitioned variables, they seems to be disposed properly, as below: 
soulmate/proj_w/part_6:0
soulmate/proj_w/part_7:0
soulmate/proj_w/part_8:0
soulmate/proj_w/part_9:0
soulmate/proj_w/part_10:0
soulmate/proj_w/part_11:0
soulmate/proj_w/part_12:0
.......
(These are printed after "with sv.managed_session(server.target) as sess:", so the session is initialized successfully. )

Work 0 and Work 1 printed the params with the same name. But still only worker 1 started training and woker 0 crashed. 

According to my tryings, I doubt the root cause is not the 2G limit of protobuf, reasons: 
1. Only worker 0 crashed. If we hit 2G limit, worker1 should has the same problem. But worker 1 can run normally on big RNN while worker 0 cannot. 
2. Worker 0 always crash on the first **session.run**, if I set the saver/summary_op/global_step in the supervisor, it will crash on the **prepare_or_wait_for_session** in which session will run global_step. 
3. Smaller RNN can run fresh params with no problem, but when restoring from ckpt,  worker 0 crashes everytime with same exception, no matter big or small. 
4. Worker 0 spends 2x time to run every step ( in small RNN ). I suppose worker 0 is doing some extra job or holding a lower priority lock on the params?  
5. The interval between worker 0 starting and crashing is always about 25 minutes.... so, is there any timeout? 

So the problem might exist in the **extra job** of worker 0, not saver and summary because I have not used them. Do you have some clues?

**Comment by mrry** [comment] 2016-08-16 16:48
@bixiongxu Can you get a core dump from the crashed worker task? (The error message just suggests that the worker restarted, but gives no clue about *why* this might have happened.)

**Comment by bixiongxu** [comment] 2016-08-17 10:20
@mrry sorry I didn't explain right. It is not a crash bug just a UnavailableError crash and Exit(code: 1), so there won't be a core dump I think. 
Anyway, today I dig into the source code and location the failing position:  
in **tensorflow/core/distributed_runtime/rpc/grpc_session.cc** line 186: 
**TF_RETURN_IF_ERROR(RunProto(&call_options, &req, &resp));**
I found a timeout option in the **call_options**, and I suspect big RNN will cause a timeout. I try to set a 
**run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE, timeout_in_ms=10000000)** when I call **outputs = session.run(output_feed, input_feed, options=run_options).** and now is trying to see if it can pass through. 
Appreciate to have your suggestions...

**Comment by bixiongxu** [comment] 2016-08-17 10:38
@mrry sorry for some typo in last post and I have fixed in the post. 
And can you recommend some tool for debugging the tensorflow source? I am not so familiar with Linux coding envioronment, but I think there should be some handy tool can do breakpoint / step over / step in ....... . I did try gdb, but it cannot link to the source code, maybe I didn't build the source right?  ( I followed the [https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources], it works)

**Comment by bixiongxu** [comment] 2016-08-17 15:11
**Update**
The timeout value is passed through, but no effect :(, still raise same exception.  

Then I thought maybe too many variables for only 2 ps, I adjusted the cluster to 1 worker vs 4 ps, something new is happened. 
The worker 0 still raise the same exception, and 2 of the PS servers raise: **'unit.device' Must be non NULL** in tensorflow/core/distributed_runtime/graph_mgr.cc:55. 
Not sure if they are related.

**Comment by aselle** [comment] 2016-08-26 17:35
@mrry can you take another look?

**Comment by mrry** [comment] 2016-08-26 19:19
Without the crash dump from worker0, or some way to reproduce the bug, there's not much we can do. With `gdb` were you able to get a stack trace at least?

**Comment by bixiongxu** [comment] 2016-08-28 02:10
@mrry I think there is no dump, because it is not a crash of process. 
**in tensorflow/core/distributed_runtime/rpc/grpc_session.cc line 186: 
TF_RETURN_IF_ERROR(RunProto(&call_options, &req, &resp));**
The process failed on this point and raise a Unavailable Error then exit. 

If you want to investigate the potential problem of the grpc, I can give you the code package, which can 100% re-raise the problem, by setting up a 2 worker and 1 ps cluster, of which worker 0 will always fail if we use 3*512 or bigger size. 
The code is modified from rnn/translate, with model unmodified and some extra cluster code. 

Of course there might be some other causes, such as using VMs environment, no GPU or some codes in rnn/translate are not fit for cluster.

**Comment by aselle** [comment] 2016-09-12 17:57
Have you had any luck solving this problem on your own @bixiongxu? I would try the following..

1. Try tensorflow 0.10rc1 or the nightly build since 0.8 is now quite old.
2.  If that doesn't work try to simplify your example to the simplest test that reproduces the behavior. Include the code and exact instructions on how to reproduce it.

We cannot guarantee that we will have time to look into it, but others in the community definitely would have a chance of helping you then too. However, without a reproducible test case, we will close the issue as "cannot reproduce."

**Comment by bixiongxu** [comment] 2016-09-13 00:06
Hi Andrew

I just put it aside for now as one machine is ok for my purpose so far.  But I will definitely come back to it this month.
I will update you when I get something new. Thank you for your help.



Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by aselle** [comment] 2016-10-03 18:24
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.

**Closed by aselle** 2016-10-03 18:24 UTC
Labels: awaiting response
