### ISSUE TITLE
Calling a Dense layer fails when it is created with kernel_initializer=tf.keras.initializers.Zeros()

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24573] opened 2018-12-26 10:24 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION=1.13.0-dev20181225
GIT_VERSION=b'v1.12.0-5131-gc6f3c5dc48'
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
I get a `TypeError` exception when I call a `Dense` layer which was created with `kernel_initializer=tf.keras.initializers.Zeros()`.

**Describe the expected behavior**
I expect no error, and the kernel should be initialized to zeros, just like when I set `kernel_initializer="zeros"`.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras

inputs = tf.constant([[1., 2.], [3., 4.]])
layer_init0 = keras.layers.Dense(units=4, kernel_initializer=tf.keras.initializers.Zeros())
print(layer_init0(inputs))
print(layer_init0.get_weights())
```

If you do not set the `kernel_initializer`, or if you set it to `"zeros"`, everything works fine.

**Other info / logs**
Here is the stacktrace:

```python
>>> print(layer_init0(inputs))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 541, in __call__
    self._maybe_build(inputs)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1572, in _maybe_build
    self.build(input_shapes)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 949, in build
    trainable=True)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 355, in add_weight
    aggregation=aggregation)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 612, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2489, in default_variable_creator
    import_scope=import_scope, distribute_strategy=distribute_strategy)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 298, in __init__
    constraint=constraint)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 410, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 127, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
TypeError: __call__() got an unexpected keyword argument 'partition_info'
```

**Comment by yongtang** [comment] 2018-12-26 20:56
@ageron I tried with ubuntu but could not reproduce it:
```
# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from tensorflow import keras
>>> 
>>> tf.VERSION
'1.13.0-dev20181225'
>>> tf.GIT_VERSION
"b'v1.12.0-5131-gc6f3c5dc48'"
>>> 
>>> inputs = tf.constant([[1., 2.], [3., 4.]])
>>> layer_init0 = keras.layers.Dense(units=4, kernel_initializer=tf.keras.initializers.Zeros())
>>> print(layer_init0(inputs))
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:439: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Tensor("dense/BiasAdd:0", shape=(2, 4), dtype=float32)
>>> print(layer_init0.get_weights())
2018-12-26 20:54:44.832443: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-12-26 20:54:44.863208: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2018-12-26 20:54:44.867255: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x43bd5c0 executing computations on platform Host. Devices:
2018-12-26 20:54:44.867287: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
[array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32), array([0., 0., 0., 0.], dtype=float32)]
>>> 
```

Wondering if the issue is similar to #24577 as well?

**Comment by ageron** [comment] 2018-12-27 01:30
Hi @yongtang ,
I'm not sure we are using the same version. I installed the 2.0 preview, but it says the version is 1.13.0-dev20181225.

**Comment by yongtang** [comment] 2018-12-27 21:42
@ageron I used the following command to install tf-nightly on Ubuntu 18.04:
```
pip3 install tf-nightly==1.13.0-dev20181225
```

May I know the installation method you used?

**Comment by ageron** [comment] 2019-01-04 07:34
Thanks once more @yongtang ! 👍

**Comment by ymodak** [comment] 2019-01-18 21:46
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2019-01-18 21:46 UTC
Labels: 2.0

**Comment by JSunRae** [comment] 2020-03-31 23:19
Hi all. I have the same problem but have no idea how this solution can be implemented.
