### ISSUE TITLE
tflite mult_thread

### ISSUE THREAD

**Issue by chenjiaoAngel** [tensorflow/tensorflow#20019] opened 2018-06-14 13:09 UTC
Describe the problem
How can we use tflite code in android to test the mult_thread testing.
The set thread code doen't work.

Source code / logs
public void setNumThreads(int num_threads) {
if (tflite != null)
tflite.setNumThreads(num_threads);
}

**Comment by tensorflowbutler** [comment] 2018-06-15 01:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chenjiaoAngel** [comment] 2018-06-15 02:34
Have I written custom code: No
OS Platform and Distribution: Android studio3.0.1 ndkr14, API21-21
TensorFlow installed from: GitHub  https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite
TensorFlow version
Bazel version:0.14.0
CUDA/cuDNN version

**Comment by bignamehyp** [comment] 2018-06-20 06:48
Similar to #18658

**Comment by tensorflowbutler** [comment] 2018-07-11 03:18
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-25 19:11
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by suharshs** [comment] 2018-08-02 22:48
Seems to be similar to the other issue where we will track this. So closing this.

**Closed by suharshs** 2018-08-02 22:48 UTC
Labels: comp:lite, stat:awaiting response
