### ISSUE TITLE
tf.losses.sigmoid_cross_entropy

### ISSUE THREAD

**Issue by nooralahzadeh** [tensorflow/tensorflow#15846] opened 2018-01-04 11:46 UTC
Hi,
it seems that there is a mistake in the api doc:
logits: Float [batch_size, num_classes] logits outputs of the network. 
however it should be:
logits: Float [batch_size, num_classes] Unscaled log probabilities.
since it said it is going to "Creates a cross-entropy loss using tf.nn.sigmoid_cross_entropy_with_logits"

**Comment by tensorflowbutler** [comment] 2018-01-04 19:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-24 13:14
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-23 14:01
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-10 13:08
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 12:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by poxvoculi** [comment] 2018-04-18 21:55
@drpngx Is the 'logits' argument not actually logits?

**Comment by drpngx** [comment] 2018-04-19 20:37
I think it's fine in that case since the labels are binary. it's individual log odds ratios.

**Comment by tensorflowbutler** [comment] 2018-05-04 18:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by poxvoculi** [comment] 2018-05-04 19:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by poxvoculi** 2018-05-04 19:36 UTC
Labels: stat:awaiting response

**Comment by rjurney** [comment] 2019-07-19 07:06
This is very confusing. What does the loss function want?
