### ISSUE TITLE
Cifar-10 eval script verbose output

### ISSUE THREAD

**Issue by jaelim** [tensorflow/tensorflow#389] opened 2015-12-01 16:31 UTC
I've ran cifa10_train.py successfully. Now, I'm trying to run cifar10_eval.py, but the code's following verbose repeatedly without stopping. Any idea what this means?

I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
2015-12-01 08:17:18.602794: precision @ 1 = 0.855
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa024001740 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa03c001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa02c001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa0500018c0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa028001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa0480098d0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa020001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa030001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa038001730 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa0540098d0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa018001630 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa0400018e0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa0440098d0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa05c055a30 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa04c0098d0 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa060052d90 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
I tensorflow/core/kernels/random_shuffle_queue_op.cc:282] Skipping cancelled enqueue attempt
W tensorflow/core/common_runtime/executor.cc:1027] 0x7fa064001480 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueMany[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/RandomShuffle)]]

**Comment by shlens** [comment] 2015-12-04 04:16
Is this error produced reliably if you run cifar10_eval.py? If so, would you describe exactly how you produced this error as I am not seeing this error when I run the script? Thanks!

**Comment by shlens** [comment] 2015-12-21 19:44
I presume this error is not longer an issue so I will be marking this issue as closed but please feel free to reopen if this error persists.

**Comment by tptptptp** [comment] 2016-01-04 15:08
I get this issue - cifa10_train.py runs fine, but the above text appears when evaluating it.  I'm using a GTX960 with 2GB memory.

**Comment by jkschin** [comment] 2016-01-05 07:52
I get this error too. Anyone has a fix for it? I tried cifar10_eval.py on both CUDA enabled TensorFlow and non-CUDA enabled TensorFlow.

**Comment by liuyipei** [comment] 2016-01-08 22:00
I also encounter this error during evaluation. (I am using the pip installed gpu version). The installation was a little dated. 

After a reinstall via pip, I started getting the conv1 weights uninitialized error during training.
https://github.com/tensorflow/tensorflow/issues/642

**Comment by jkschin** [comment] 2016-01-12 05:46
I get this error too, mine however does output something first. The extra line is in bold. Subsequently, it seems identical to what is posted above.

**2016-01-12 13:38:54.616463: precision @ 1 = 0.845**
W tensorflow/core/common_runtime/executor.cc:1076] 0x7f3fb0001980 Compute status: Cancelled: Enqueue operation was cancelled
	 [[Node: shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, Div, Cast)]]
W tensorflow/core/common_runtime/executor.cc:1076] 0x7f3fcc001720 Compute status: Cancelled: Enqueue operation was cancelled

**Comment by jkschin** [comment] 2016-01-12 06:17
I get this error too. However I notice that this appears before everything else.

2016-01-12 13:38:54.616463: precision @ 1 = 0.845

Can we assume that eval_once() is successfully executed and use this result?

**Comment by habrman** [comment] 2016-01-21 07:52
Has someone found a solution to this? I'm having the same problem...

**Comment by yaroslavvb** [comment] 2016-01-23 02:48
I don't see this in behavior in the latest version (head)

**Comment by sergiosgc** [comment] 2016-02-10 15:45
I am observing this exact error in a version compiled from current HEAD today.

**Comment by atamahjoubfar** [comment] 2016-02-28 08:54
I realized that if I let the `cifar10_train.py` and `cifar10_eval.py` files keep running simultaneously, despite the `queue` errors, the `precision @ 1` is reported every 5 minutes. One can reduce this time interval by decreasing the value of `'eval_interval_secs'` in the `cifar10_eval.py` file to see more frequent updates.

**Comment by yuanpengX** [comment] 2016-04-15 01:21
Is there any solution yet? Because I have met this problem too.

**Comment by atamahjoubfar** [comment] 2016-04-15 08:49
Unfortunately, none that I am aware of.

Ata

**Comment by girving** [comment] 2016-06-06 18:19
@ebrevdo: Do you have any thoughts here?  Reassigning to you since Sherry is out.

**Comment by ebrevdo** [comment] 2016-06-10 18:51
@yuanpengX @atamahjoubfar is this still an issue?  Is it just the verbose logging that's troubling you?  when you reach the end of the input file, the queue dies and the training is restarted from the beginning.  that may explain all the warnings.

**Comment by atamahjoubfar** [comment] 2016-06-20 02:01
@ebrevdo I just tested again the CIFAR-10 code on the same machine, and the issue is resolved. Thank you.

**Comment by girving** [comment] 2016-06-20 03:25
@atamahjoubfar Thanks!  Closing for now; please comment or file another if it comes up again.

**Closed by girving** 2016-06-20 03:25 UTC
Labels: triaged

**Comment by sebastient** [comment] 2016-08-17 15:20
Issue does appear on 0.10rc0 for Mac (CPU) and Python 3 using a virtualenv installation.  First time seeing this issue, otherwise appears to be working correctly.
