### ISSUE TITLE
if you install tensorflow v1.9 through wheel，you should install tensorboard v1.9.0 but not v1.10.0

### ISSUE THREAD

**Issue by FlashSnail** [tensorflow/tensorflow#21182] opened 2018-07-27 08:16 UTC
as title i typed, is this a bug of tf1.9?

**Comment by tensorflowbutler** [comment] 2018-07-27 18:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by asimshankar** [comment] 2018-08-03 21:14
Could you elaborate on what exactly you're trying and what happened? Please provide a [minimal, verifiable, complete example](https://stackoverflow.com/help/mcve).

For example, on a clean install this is what I see:

```bash
# Validate that neither TensorFlow nor tensorboard are installed yet - the list below should be empty
pip list | grep tensor

# Install tensorflow 1.9.0
pip install tensorflow==1.9.0

# Now grep again and see that the two versions are in sync
pip list | grep tensor
```

**Comment by tensorflowbutler** [comment] 2018-08-18 18:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-02 18:35
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-09-04 19:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2018-09-04 19:57 UTC
Labels: stat:awaiting response
