### ISSUE TITLE
port::AlignedMalloc() may cause a memory leak

### ISSUE THREAD

**Issue by RockfordWei** [tensorflow/tensorflow#10997] opened 2017-06-22 21:10 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra Version 10.12.5
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0, Darwin, cpu
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
```
# NOTE: Please install Xcode 8.3 first!
$ git clone https://github.com/PerfectlySoft/Perfect-TensorFlow.git
$ cd Perfect-TensorFlow
$ ./test.sh
``` 

### Describe the problem
When developing Perfect-TensorFlow, a Swift Class Wrapper of C api [https://gihub.com/PerfectlySoft/Perfect-TensorFlow](https://gihub.com/PerfectlySoft/Perfect-TensorFlow), I found there might be a memory leak when performing such a test:
testing script: https://github.com/PerfectlySoft/Perfect-TensorFlow/blob/master/Tests/PerfectTensorFlowTests/PerfectTensorFlowTests.swift#L153-L167
currently I am using libtensorflow 1.1.0 CPU version on both macOS / Ubuntu 16.04 LTS and found the same leakage on the both systems, hope to get solution once 1.2+ released.

Using Xcode - Instruments may find the trace as screen shot below:
<p><img src='https://raw.githubusercontent.com/RockfordWei/upfiler/master/alignedmalloc.leak.png'>AlignedMalloc() leak Screenshot</img></p>

### Source code / logs

[Tensor Creation Testing Script](https://github.com/PerfectlySoft/Perfect-TensorFlow/blob/master/Tests/PerfectTensorFlowTests/PerfectTensorFlowTests.swift#L153-L167)

**Comment by mrry** [comment] 2017-06-23 00:19
If I've read the stack trace correctly, it looks like these allocations were made by the `tensorflow::ConstantOp` constructor, which allocates memory for a `tensorflow::Tensor` storing the value of each constant in the graph. That memory should be owned by a `tensorflow::DirectSession` object and freed when you delete the session. Can you confirm whether this happens?

**Comment by RockfordWei** [comment] 2017-06-23 11:29
Sorry I am not sure. Just using C API to do the TF_AllocateTensor() first then call TF_DeleteTensor() once done.

**Comment by mrry** [comment] 2017-06-23 14:04
Hmm, in that case I'm going to close this issue as "working as intended" for now. `port::AlignedMalloc()` is used at the lowest level to allocate tensor buffers, but these buffers may be shared with other parts of the system (e.g. stored in the `OpKernel` objects that implement the operations in the graph) in reference-counted `tensorflow::Tensor` objects. As such, it's possible that you could allocated a `TF_Tensor*`, pass it to one of the APIs, call `TF_DeleteTensor()` on it, and the memory would not be freed until later. Many tensors used in a session, such as constants, will only be deleted when the session is deleted.

If you find other evidence of a memory leak with this approach, please feel free to reopen the issue!

**Closed by mrry** 2017-06-23 14:04 UTC

**Comment by RockfordWei** [comment] 2017-06-23 14:30
Interesting. Actually the calling stack is `TF_NewSession()`, `run()` then `TF_DeleteSession()`, loop for 300+ times, and this chart indicates there is a growing memory usage and Xcode reported `AlignedMalloc` was the only leaky one, where you can see the a liner increase - possibly caused by an incomplete object release.
<p><img src="https://github.com/RockfordWei/upfiler/blob/master/growingleaks.png?raw=true">Suspected Memory Leak Accumulation</img></p>

**Comment by RockfordWei** [comment] 2017-06-23 16:29
Ah! You're right! After tracing the stack my self, just found some tensors that not released **AFTER** `TF_DeleteSession()`. Just fixed it. This issue can safely close now. Thank you so much!!!

**Comment by mrry** [comment] 2017-06-23 16:47
Great - thanks for confirming!
