### ISSUE TITLE
Build error for finding some generated header files

### ISSUE THREAD

**Issue by Enigma-li** [tensorflow/tensorflow#12288] opened 2017-08-15 08:16 UTC
I just build the master branch on windows based-on the CMake method, as shown in link: https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake

I first build the PIP package, as described in the above link. But there is build error says that:

C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/utils/dropout_utils.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\dropout_utils.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  sparse_column_iterable.cc
  tensor_utils.cc
  example_partitioner.cc
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/trees/decision_tree.h(19): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\common\partitioners\example_partitioner.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  bias-feature-column-handler.cc
  categorical-feature-column-handler.cc
  dense-quantized-feature-column-handler.cc
  sparse-quantized-feature-column-handler.cc
  multiple_additive_trees.cc
  decision_tree.cc
  masked_matmul_ops.cc
  wals_solver_ops.cc
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/trees/decision_tree.h(19): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\trees\decision_tree.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\sparse-quantized-feature-column-handler.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  factorization_ops.cc
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\categorical-feature-column-handler.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  generate_vocab_remapping_op.cc
  load_and_remap_matrix_op.cc
  zero_initializer_op.cc
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/models/multiple_additive_trees.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/tree_config.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\models\multiple_additive_trees.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\bias-feature-column-handler.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
C:\v-clhian\tensorflow\tensorflow/contrib/boosted_trees/lib/learner/stochastic/stats/node-stats.h(21): fatal error C1083: Cannot open include file: 'tensorflow/contrib/boosted_trees/proto/learner.pb.h': No such file or directory (compiling source file C:\v-clhian\tensorflow\tensorflow\contrib\boosted_trees\lib\learner\stochastic\handlers\dense-quantized-feature-column-handler.cc) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  checkpoint_ops.cc
  sparse_feature_cross_kernel.cc
  sparse_feature_cross_op.cc
  resampler_ops.cc
  tensor_forest_ops.cc
  reinterpret_string_to_float_op.cc
  scatter_add_ndim_op.cc
  tree_utils.cc
  hard_routing_function_op.cc
  k_feature_gradient_op.cc
  k_feature_routing_function_op.cc
  routing_function_op.cc
  routing_gradient_op.cc
  stochastic_hard_routing_function_op.cc
  stochastic_hard_routing_gradient_op.cc
  unpack_path_op.cc
  utils.cc
  skip_gram_kernels.cc
  skip_gram_ops.cc
  cross_replica_ops.cc
  infeed_ops.cc
  outfeed_ops.cc
  replication_ops.cc
  tpu_configuration_ops.cc
Done Building Project "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default targets) -- FAILED.

It cannot find the generated header files: 
learner.pb.h and tree_config.pb.h
But I find them on my disk, under folder C:\xxx\tensorflow\tensorflow\contrib\cmake\build\tensorflow\contrib\boosted_trees\proto, illustrating that it already generate the files.

So is there any configuration for this?

**Comment by reedwm** [comment] 2017-08-15 17:56
@mrry can you take a look?

**Comment by guschmue** [comment] 2017-08-16 16:09
I looked at this one and have a fix for it here (you could merge that commit to unblock):
https://github.com/guschmue/tensorflow/commit/bbbb7a7e6ee69dfb7148b7008c17f62989c8286e

The problem is that the boosted_tree kernels build in core/kernels but they do depend on the .pb.h which are generated in tf_python_protos_cc.vcxproj but core/kernels do not depend on tf_python_protos_cc.vcxproj.

The commit above moves this protoc for boosted_tree to core so they are there when core/kernels needs them. I have not send a pr for this because there are some issues with the boosted_tree unit tests that I wanted to fix at the same time ... just not found time yet.

The reason why ci.tensorflow.org does not see this: msbuild there builds 32 projects in parallel and it just happens that  tf_python_protos_cc.vcxproj is done before core/kernels needs it.

@mrry - should I send a pr for this?

**Comment by mrry** [comment] 2017-08-16 16:14
Guenther: PR #12315 seems to fix the problem (but hasn't been merged yet because some unrelated test is failing :(...).

**Comment by Enigma-li** [comment] 2017-08-16 17:02
Another error occurred when fix this one, as shown below:

.....................................
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_event.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_fft.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_gpu_executor.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_platform.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_platform_id.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_rng.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_stream.obj"
         "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.dir\Release\cuda_timer.obj"
            Creating library C:/v-clhian/tensorflow/tensorflow/contrib/cmake/build/Release/pywrap_tensorflow_internal.lib and object C:/v-clhian/tensorflow/tensorflow/contrib/cmake/build/Release/pywrap_tensorflow_internal.exp
     5>pywrap_tensorflow_internal.exp : warning LNK4070: /OUT:_pywrap_tensorflow_internal.pyd directive in .EXP differs from output filename 'C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\Release\pywrap_tensorflow_internal.dll'; ignoring directive [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
     5>zero_initializer_op.obj : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::TensorSetZero<struct Eigen::GpuDevice,struct Eigen::half>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<struct Eigen::half,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$TensorSetZero@UGpuDevice@Eigen@@Uhalf@2@@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@Uhalf@Eigen@@$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::ZeroInitializerOp<struct Eigen::GpuDevice,struct Eigen::half>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ZeroInitializerOp@UGpuDevice@Eigen@@Uhalf@2@@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
     5>zero_initializer_op.obj : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::TensorSetZero<struct Eigen::GpuDevice,float>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<float,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$TensorSetZero@UGpuDevice@Eigen@@M@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@M$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::ZeroInitializerOp<struct Eigen::GpuDevice,float>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ZeroInitializerOp@UGpuDevice@Eigen@@M@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
     5>zero_initializer_op.obj : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::TensorSetZero<struct Eigen::GpuDevice,double>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<double,1,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$TensorSetZero@UGpuDevice@Eigen@@N@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@N$00$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::ZeroInitializerOp<struct Eigen::GpuDevice,double>::Compute(class tensorflow::OpKernelContext *)" (?Compute@?$ZeroInitializerOp@UGpuDevice@Eigen@@N@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z) [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
     5>C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\Release\pywrap_tensorflow_internal.dll : fatal error LNK1120: 3 unresolved externals [C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
     5>Done Building Project "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\v-clhian\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.

Build FAILED.


May be some other Cmakelist error, could you help fix this?

**Comment by guschmue** [comment] 2017-08-16 17:03
@mrry - yes, same fix. Sorry, I dropped the ball, should have send a pr early on.

**Comment by mrry** [comment] 2017-08-16 17:47
@Enigma-li Thanks for trying that. It looks like the Windows GPU build was broken by a recent change. I think I've identified the fix, and I'll bundle it with #12315.

@guschmue Don't worry about it... we appreciate all of your contributions! :)

**Closed** 2017-08-18 00:41 UTC
Labels: stat:awaiting tensorflower
