### ISSUE TITLE
I am trying to convert yolov3 to a full uint8 tflite model after, i got this error : Quantized not yet supported for op : 'EXP'

### ISSUE THREAD

**Issue by Tieckby** [tensorflow/tensorflow#45281] opened 2020-11-30 20:32 UTC
Quantized not yet supported for op : 'EXP'
Quantized not yet supported for op : 'EXP'
Quantized not yet supported for op : 'EXP'

**Comment by ravikyram** [comment] 2020-12-01 05:54
@Tieckby 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment] 2020-12-01 16:41
@Tieckby 

Looks like duplicate #45301.Please, close this issue and we can track the issue in #45301.Thanks!

**Closed** 2020-12-07 05:51 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by Tieckby** [comment] 2020-12-07 06:22
No, it doesn't.

**Comment by abattery** [comment] 2020-12-07 06:26
@Tieckby Let's continue discussions at the #45301.

**Comment by Tieckby** [comment] 2020-12-07 06:50
Ok, Can you solve it ?
