### ISSUE TITLE
.prefetch() and .cache() not speeding up tf.data.Dataset pipeline 

### ISSUE THREAD

**Issue by Jamesswiz** [tensorflow/tensorflow#37178] opened 2020-02-29 00:01 UTC
I have a very big dataset so I am training over small chunks using keras.fit. 
For loading chunks in memory I have a generator function which generates a tuple of tensors of variable size which I pass to tf.data.Dataset to create a data pipeline.

```
def extract_XY(list_idx):
    read_files(list_idx)
    append to list X
    process, reshape and convert to tensor X (?,100,100,3)  #? means variable size
    Y = f(X)  
    return X,Y

for i in range(epochs):
    for j in range(chunks):
        x,y = extract_XY(list_idx) #list_idx changes in each loop
        data = tf.data.Dataset.from_tensor_slices((X,Y)).batch(64).cache().prefetch(tf.data.experimental.AUTOTUNE)
        model.fit(data,epochs=2,verbose=1)

```

My training with keras fit works fine but I see no speed up using .cache() or .prefetch()
Can anyone help me understand if I am using them correctly in my case.

Can I make my data-pipeline more efficient i.e., loading next chunk while model is training? any suggestions would be helpfull?
Does using multiprocessing=True in Keras.fit() will help more? or tf.data.Dataset is already taking care of I/O bottleneck.

Thanks in advance!

**Comment by amahendrakar** [comment] 2020-03-02 06:53
@Jamesswiz,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by dominthomas** [comment] 2020-03-08 13:54
Similar issue for me:

```python
def load_image(file, label):
    nifti = np.asarray(nibabel.load(file.numpy().decode('utf-8')).get_fdata()).astype(np.float32)

    xs, ys, zs = np.where(nifti != 0)
    nifti = nifti[min(xs):max(xs) + 1, min(ys):max(ys) + 1, min(zs):max(zs) + 1]
    nifti = nifti[0:100, 0:100, 0:100]
    nifti = np.reshape(nifti, (100, 100, 100, 1))
    return nifti, label


@tf.autograph.experimental.do_not_convert
def load_image_wrapper(file, label):
    return tf.py_function(load_image, [file, label], [tf.float64, tf.float64])
    # result_tensors[0].set_shape([100, 100, 100, 1])
    # result_tensors[1].set_shape([None])
    # return result_tensors


dataset = tf.data.Dataset.from_tensor_slices((train, labels))
dataset = dataset.map(load_image_wrapper, num_parallel_calls=24)
dataset = dataset.prefetch(buffer_size=12).cache()
dataset = dataset.apply(tf.data.experimental.prefetch_to_device('/device:GPU:0', 1))
dataset = dataset.batch(12, drop_remainder=True)

########################################################################################
with tf.device("/cpu:0"):
    with tf.device("/gpu:0"):
        model = tf.keras.Sequential()

        model.add(Conv3D(64,
                         input_shape=(100, 100, 100, 1),
                         data_format='channels_last',
                         kernel_size=(7, 7, 7),
                         strides=(2, 2, 2),
                         padding='valid',
                         activation='relu'))

    with tf.device("/gpu:1"):
        model.add(Conv3D(64,
                         kernel_size=(3, 3, 3),
                         padding='valid',
                         activation='relu'))

    with tf.device("/gpu:2"):
        model.add(Conv3D(128,
                         kernel_size=(3, 3, 3),
                         padding='valid',
                         activation='relu'))

        model.add(MaxPooling3D(pool_size=(2, 2, 2),
                               padding='valid'))

    with tf.device("/gpu:3"):
        model.add(Conv3D(128,
                         kernel_size=(3, 3, 3),
                         padding='valid',
                         activation='relu'))

        model.add(MaxPooling3D(pool_size=(2, 2, 2),
                               padding='valid'))

    with tf.device("/gpu:4"):
        model.add(Conv3D(128,
                         kernel_size=(3, 3, 3),
                         padding='valid',
                         activation='relu'))

        model.add(MaxPooling3D(pool_size=(2, 2, 2),
                               padding='valid'))

        model.add(Flatten())

        model.add(Dense(256, activation='relu'))
        model.add(Dropout(0.7))
        model.add(Dense(256, activation='relu'))
        model.add(Dropout(0.7))
        model.add(Dense(1, activation='sigmoid'))

loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adagrad(learning_rate=0.01)


def loss(model_param, x_param, y_param, training):
    # training=training is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    y_ = model_param(x_param, training=training)

    return loss_object(y_true=y_param, y_pred=y_)


def grad(model_param, inputs, targets):
    with tf.GradientTape() as tape:
        loss_v = loss(model_param, inputs, targets, training=True)
    return loss_v, tape.gradient(loss_v, model_param.trainable_variables)


train_loss_results = []
train_accuracy_results = []
num_epochs = 101

for epoch in range(num_epochs):
    epoch_loss_avg = tf.keras.metrics.Mean()
    epoch_accuracy = tf.keras.metrics.BinaryCrossentropy()
    iterator = iter(dataset)

    # Training loop - using batches of 12
    try:
        while True:
            x, y = iterator.get_next()
            # Optimize the model
            loss_value, grads = grad(model, x, y)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))

            # Track progress
            epoch_loss_avg(loss_value)  # Add current batch loss
            # Compare predicted label to actual label
            # training=True is needed only if there are layers with different
            # behavior during training versus inference (e.g. Dropout).
            epoch_accuracy(y, model(x, training=True))
    except tf.errors.OutOfRangeError:
        print("Epoch end...")

    # End epoch
    train_loss_results.append(epoch_loss_avg.result())
    train_accuracy_results.append(epoch_accuracy.result())

    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))
```

**Comment by dominthomas** [comment] 2020-03-08 16:22
[This](https://github.com/tensorflow/tensorflow/issues/24520#issuecomment-596213250) helped in my case.

**Comment by amahendrakar** [comment] 2020-03-11 14:47
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-03-18 05:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-03-18 05:30 UTC
Labels: stat:awaiting response, type:bug

**Comment by WillLiGitHub** [comment] 2020-12-29 07:12
same issues

**Comment by amahendrakar** [comment] 2021-01-03 17:17
@WillLiGitHub,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
