### ISSUE TITLE
Tensorflow crashed when using AdamOptimizer

### ISSUE THREAD

**Issue by chuanwen** [tensorflow/tensorflow#323] opened 2015-11-22 08:56 UTC
I tried the cnn in the tutorial for MNIST data, but initialize the parameters with stddev=1 (instead of stddev=0.1).

Error message:
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
0 0.098
W tensorflow/core/common_runtime/executor.cc:1027] 0x4472710 Compute status: Invalid argument: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: gradients/Relu_grad/Relu/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](add)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x4472710 Compute status: Invalid argument: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: gradients/Relu_1_grad/Relu_1/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](add_1)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x4472710 Compute status: Invalid argument: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: gradients/Relu_2_grad/Relu_2/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](add_2)]]
Traceback (most recent call last):
  File "2_cnn.py", line 67, in <module>
    session.run(train_step, feed_dict={X: x, Y: y, keep_prob: 0.5})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: ReluGrad input is not finite. : Tensor had NaN values
	 [[Node: gradients/Relu_grad/Relu/CheckNumerics = CheckNumerics[T=DT_FLOAT, message="ReluGrad input is not finite.", _device="/job:localhost/replica:0/task:0/cpu:0"](add)]]
Caused by op u'gradients/Relu_grad/Relu/CheckNumerics', defined at:
  File "2_cnn.py", line 55, in <module>
    train_step = tf.train.AdamOptimizer().minimize(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 165, in minimize
    gate_gradients=gate_gradients)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 205, in compute_gradients
    loss, var_list, gate_gradients=(gate_gradients == Optimizer.GATE_OP))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py", line 414, in gradients
    in_grads = _AsList(grad_fn(op_wrapper, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_grad.py", line 107, in _ReluGrad
    t = _VerifyTensor(op.inputs[0], op.name, "ReluGrad input is not finite.")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_grad.py", line 100, in _VerifyTensor
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 48, in check_numerics
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'Relu', defined at:
  File "2_cnn.py", line 32, in <module>
    h_conv1 = tf.nn.relu(conv2d(X1, w_conv1) + b_conv1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 506, in relu
    return _op_def_lib.apply_op("Relu", features=features, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()

**Comment by rafaljozefowicz** [comment] 2015-11-22 15:52
Your weights are likely diverging. Try reducing the learning rate and/or revert your initialization change.

**Comment by chuanwen** [comment] 2015-11-22 18:52
I do not think it's due to diverging, as it crashed when I did following:
- same weight initialization as the tutorial
- change full_connect to 512 units
- change batch_size to 200
Training crashed say, at step 3500 (when accuracy is near 99.2%).

**Comment by vincentvanhoucke** [comment] 2015-11-24 00:52
Consider increasing the epsilon value of the optimizer.

**Comment by jpiabrantes** [comment] 2015-11-24 11:52
I am getting the same error on my Neural Network. I am logging the weights max and min and they are between -1 and 1 so they are not diverging. I get this error when using `AdagradOptimizer`, `AdamOptimizer` and the `MomentumOptimizer` the error happens after the first epoch so the algorithm was already trained with each minibatch at least once. I have now idea of why this is happening, how can I debug it?

**Comment by vincentvanhoucke** [comment] 2015-11-24 15:06
One thing you can do is run with a tiny learning rate, or even zero learning rate. If you still have divergence then, you have a bug in your setup. If not, increase your rate slowly and see if there is a regime in which things train without diverging. It's completely possible to have weights that are in a good range, but activations or gradients going to infinity because of the shape of the loss, or too high a learning rate. It's obviously always a possibility that there is a bug in the optimizers, but in my experience, every single instance of this kind of problem could be traced back to a weirdly wired model, learning rate issues, bad randomization of the input examples, or - in the case of Adam or RMSProp - issues with the epsilon value.

**Comment by delip** [comment] 2015-11-24 16:03
OP: it might help if you can paste your entire code in a gist and report it
here.

**Comment by jpiabrantes** [comment] 2015-11-24 16:12
@vincentvanhoucke Thank you for your help. I tried to debug it following your advices:

I ran the algorithm with learning_rate = 0. Didn't raise any error.
I then tried to run the algorithm with different learning rates (lr) and obtained the following results:

![lr_results](https://dl.dropboxusercontent.com/u/15853805/learning_rates.png)

All the learning rates, but the `lr = 1E-8`, raised the error. The learning rate 1E-8 didn't learn anything.

My code is here: [gist](https://gist.github.com/jpiabrantes/321aff988eaa00dfefcb) .

If you want to run it you will also need the data that is [here](/home/joao/Dropbox/data analysis/rossman/results/results1/nn_train.dat
/home/joao/Dropbox/data analysis/rossman/results/results1/nn_val.dat) and [here](https://dl.dropboxusercontent.com/u/15853805/nn_train.dat).

**Comment by vincentvanhoucke** [comment] 2015-11-24 16:57
@jpiabrantes One thing that stands out here is that you use a square root in your loss. That's known to be very unstable numerically for very small values. Can you try 1) not taking the square root or 2) adding a small constant, e.g.: tf.sqrt(1e-4 + ...).
If that's indeed the problem, then one possible approach we can provide tooling around is to optionally cap the gradient of the sqrt function, because it's a common use case. Another possibility is to use gradient clipping in general (see: clip_by_norm(), which we should provide better examples for).
Let me know what happens.

The other avenue is to tune your learning rate decay. Gradients tend to paradoxically grow in magnitude as training progresses, and sometimes that introduces numerical issues late in training. It is still possible that we have issues with numerical precision somewhere, but my hunch is that these errors are legitimate divergence issues (for some twisted definition of 'legitimate').

**Comment by jpiabrantes** [comment] 2015-11-25 14:59
@vincentvanhoucke You were right. My problem was due to the loss function being RMS. If I use the loss functions you proposed everything works fine. Thank you for the help.

**Comment by navraj28** [comment] 2015-12-03 02:57
@vincentvanhoucke: I copied the MNIST Conv Net. Since, I have just a handful of images, each Batch is applying some random changes to the images. Code snippet below. The first iteration is successful. 2nd one gives the above error.
    
    def preprocessImages(x):
	    retValue = numpy.empty_like(x)
        for i in range(len(data)):
        image = x[i]
        image = tf.reshape(image, [388,190,1])
        image = tf.image.random_brightness(image, max_delta=63)
        # Subtract off the mean and divide by the variance of the pixels.
        float_image = tf.image.per_image_whitening(image)
        float_image_Mat = sess.run(float_image)
        retValue[i] = float_image_Mat.reshape((388*190))
    return retValue

    for i in range(500):
        feed_dict={x: preprocessImages(data), y_: labelsAsOneHotVector, keep_prob: 0.5}
        train_step.run(feed_dict)
        if i%100 == 0:
            train_accuracy = accuracy.eval(feed_dict)
            print("step %d, training accuracy %g"%(i, train_accuracy))

First iteration works fine! 
    
    step 0, training accuracy 0.680851
    W tensorflow/core/common_runtime/executor.cc:1027] 0x2a1a82e0 Compute status: Invalid     argument: ReluGrad input is not finite. : Tensor had NaN values

**Comment by vincentvanhoucke** [comment] 2015-12-03 03:47
@navraj28 diverging when you use SGD can happen for many reasons:
- your learning rate is too high. Note that the right learning rate can be data dependent.
- your input data is not well randomized, or highly redundant, which could happen if you're just feeding the same data with few distortions.
This bug is about the AdamOptimizer. I am going to close it. Feel free to reopen if you have new evidence of a bug.

**Closed by vincentvanhoucke** 2015-12-03 03:47 UTC

**Comment by lightscalar** [comment] 2015-12-17 06:41
It is likely a 0 log(0) issue. See: http://quabr.com/33712178/tensorflow-nan-bug

**Comment by nate331** [comment] 2015-12-17 16:27
@lightscalar that solved it for me. Thx.

**Comment by Muaazbinsaeed** [comment] 2015-12-18 17:52
Thanx lightscalar

**Comment by Muaazbinsaeed** [comment] 2015-12-18 17:56
cross_entropy = -tf.reduce_sum(y*tf.log(yconv+ 1e-9))

This works fine

**Comment by ZhangBanger** [comment] 2015-12-31 06:21
@lightscalar @Muaazbinsaeed Nice - I was stuck on this for awhile and convinced that my activations/weights were somehow exploding.

**Comment by washt** [comment] 2016-01-28 22:26
Thanks @lightscalar, that fixed the issue for me too!!

**Comment by Juleroy13** [comment] 2016-03-01 05:16
I had exactly the same problem and you fixed the issue for me too! Thanks @lightscalar !!

**Comment by jisus19** [comment] 2016-03-29 12:43
Thank you @lightscalar , that solved my problem, too!!

**Comment by darolt** [comment] 2016-04-19 00:28
thanks @lightscalar

**Comment by LeavesBreathe** [comment] 2016-06-03 14:04
@lightscalar big thanks

**Comment by rgvb178** [comment] 2016-12-19 06:15
I think you can have a try with this solution  :
Use `tf.nn.relu6()` to replace `tf.nn.relu() `

**Comment by edgarriba** [comment] 2017-01-16 19:57
@vincentvanhoucke Is there any improvement regarding numerical precisions for `tf.sqrt()` with last versions? Running v0.12 and still getting the mentioned issue.

**Comment by yaroslavvb** [comment] 2017-01-16 20:03
@edgarriba that's not an issue with precision of `tf.sqrt` -- square root operation in general is unstable for small values. The bigger underlying issue is that SGD-like algorithms are fundamentally unstable and can produce NaN/Infinity during normal functioning.

**Comment by edgarriba** [comment] 2017-01-16 20:39
@yanchen036 oh I see, thanks to clarify! I hope this feature comes some day since sometimes find such errors during the training is a bit painful.

**Comment by yaroslavvb** [comment] 2017-01-16 20:44
We use an optimizer that does a line-search at each step, that makes things more predictable

**Comment by edgarriba** [comment] 2017-01-16 22:09
Is it an internal code or is already part of TF?

**Comment by yaroslavvb** [comment] 2017-01-16 22:12
Sorry, by "we" I meant OpenAI, not Google, and we'll be open-sourcing our optimization code soon. However, its tailored for RL problems rather than a generic optimizer. You can use l-BFGS optimizer through the scipy optimizer interface, that one is supposed to be stable, although you incur some extra overhead in transferring data between TF and scipy

**Comment by suchetasu** [comment] 2017-03-16 15:23
My input image dimension is 3D i.e. (192*256*256) with one color channel image and i have used three Convolutional layers (with patches of 5*5*5) and 3 pooling layers (kernal size : 3*3*3 and stride : 2*2*2), one full-connection-layer with 128 nodes and output layer with two nodes. The number of samples are 120 for training. Batch size : 10

I am facing the below error on the cluster:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 332, in main
    sess.run(optimizer, feed_dict={train_data_node: batch_data,train_labels_node: batch_labels})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: BiasGrad requires tensor size <= int32 max
         [[Node: gradients/BiasAdd_grad/BiasAddGrad = BiasAddGrad[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Relu_grad/ReluGrad)]]

Caused by op u'gradients/BiasAdd_grad/BiasAddGrad', defined at:
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 290, in main
    optimizer = tf.train.AdamOptimizer(learning_rate=0.0).minimize(train_loss) # Adam Optimizer
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 288, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 354, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 482, in gradients
    in_grads = grad_fn(op, *out_grads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_grad.py", line 204, in _BiasAddGrad
    data_format=data_format))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 313, in bias_add_grad
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'BiasAdd', defined at:
  File "./mri_cnn.py", line 362, in <module>
    tf.app.run()
[elided 0 identical lines from previous traceback]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./mri_cnn.py", line 272, in main
    train_prediction = model(train_data_node, True)
  File "./mri_cnn.py", line 181, in model
    relu = tf.nn.relu(tf.nn.bias_add(conv, conv1_biases))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1316, in bias_add
    return gen_nn_ops._bias_add(value, bias, data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 281, in _bias_add
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): BiasGrad requires tensor size <= int32 max
         [[Node: gradients/BiasAdd_grad/BiasAddGrad = BiasAddGrad[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Relu_grad/ReluGrad)]]

Please suggest, how to fix it?

**Comment by yzcjtr** [comment] 2017-10-18 09:03
I've come across a similar bug during calculating the L2 norm along a certain dimension of a feature map. The gradients no longer explode after I added small values(1e-10) elementwise to that feature map. Hope this could help someone.
