### ISSUE TITLE
Error popping up

### ISSUE THREAD

**Issue by pushkarkishore** [tensorflow/tensorflow#40452] opened 2020-06-14 16:49 UTC
Pl. pin-point the line in the code from which the error is coming?

class ReconstructingRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.flatten1 = keras.layers.Flatten(input_shape=[109,109])
        self.hidden = [keras.layers.Dense(30, activation="relu",
                                          kernel_initializer="lecun_normal")
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim,activation="softmax")

    def build(self, batch_input_shape):
       
        n_inputs = batch_input_shape[-1]
        print(n_inputs)
        self.reconstruct = keras.layers.Dense(n_inputs)
        super().build(batch_input_shape)

    def call(self, inputs, training=None):
        Z=self.flatten1(inputs)
        
        for layer in self.hidden:
            Z = layer(Z)
         
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        #if training:
        #    result = self.reconstruction_mean(recon_loss)
        #    self.add_metric(result)
        return self.out(Z)
model = ReconstructingRegressor(10)
model.compile(loss="sparse_categorical_crossentropy", optimizer=keras.optimizers.SGD(), metrics=["accuracy"])
history = model.fit(avast, housing_labels, epochs=100,validation_split=0.1) 

Error- InaccessibleTensorError: The tensor 'Tensor("mul:0", shape=(), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=build_graph, id=1629497199368); accessed from: FuncGraph(name=train_function, id=1629516591688).

**Comment by amahendrakar** [comment] 2020-06-15 13:05
@pushkarkishore,
On running the code I am facing an error stating `NameError: name 'avast' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f7e3c20519d747ab1a773f8def3c1206/40452.ipynb). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by ratansingh98** [comment] 2020-06-16 01:51
> Pl. pin-point the line in the code from which the error is coming?
> 
> class ReconstructingRegressor(keras.models.Model):
> def **init**(self, output_dim, **kwargs):
> super().**init**(**kwargs)
> self.flatten1 = keras.layers.Flatten(input_shape=[109,109])
> self.hidden = [keras.layers.Dense(30, activation="relu",
> kernel_initializer="lecun_normal")
> for _ in range(5)]
> self.out = keras.layers.Dense(output_dim,activation="softmax")
> 
> ```
> def build(self, batch_input_shape):
>    
>     n_inputs = batch_input_shape[-1]
>     print(n_inputs)
>     self.reconstruct = keras.layers.Dense(n_inputs)
>     super().build(batch_input_shape)
> 
> def call(self, inputs, training=None):
>     Z=self.flatten1(inputs)
>     
>     for layer in self.hidden:
>         Z = layer(Z)
>      
>     reconstruction = self.reconstruct(Z)
>     recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
>     self.add_loss(0.05 * recon_loss)
>     #if training:
>     #    result = self.reconstruction_mean(recon_loss)
>     #    self.add_metric(result)
>     return self.out(Z)
> ```
> 
> model = ReconstructingRegressor(10)
> model.compile(loss="sparse_categorical_crossentropy", optimizer=keras.optimizers.SGD(), metrics=["accuracy"])
> history = model.fit(avast, housing_labels, epochs=100,validation_split=0.1)
> 
> Error- InaccessibleTensorError: The tensor 'Tensor("mul:0", shape=(), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=build_graph, id=1629497199368); accessed from: FuncGraph(name=train_function, id=1629516591688).

Unfortunately, the methods of a nested class cannot directly access the instance attributes of the outer class. Here you are getting an error because of tf.reduce_mean and tf.square functions are out of scope.

**Closed** 2020-06-30 02:26 UTC
Labels: stalled, stat:awaiting response, type:support
