### ISSUE TITLE
Doc keras/Model for "predict" function the list of argument is not display properly (fullblock instead of list)

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#27583] opened 2019-04-06 19:02 UTC
**System information**
- TensorFlow version: 2.0
- Doc Link:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/Model

**Describe the documentation issue**

In the documentation keras/Model for "predict" function the list of argument is not display properly (fullblock instead of list) on both Chrome and Firefox

<img width="910" alt="Screenshot 2019-04-06 at 20 59 00" src="https://user-images.githubusercontent.com/12021701/55674016-0cdf6980-58af-11e9-995f-fc569131a741.png">

**Comment by yongtang** [comment] 2019-04-07 02:34
I think the issue is that the first line `x: Input samples.` should be prefixed with 4 spaces (not 5). Created a PR #27596 for the fix.

**Comment by tarrade** [comment] 2019-04-24 06:29
@dynamicwebpaige  @margaretmz  Since you are experts, any idea why this PR didn't pass test ? It was just to fix some display issue of the Keras doc. I didn't do the PR but I see it didn't pass the test and it is not clear why. Thanks

**Comment by tarrade** [comment] 2019-05-04 14:20
I don't know if it normally take 2 days to deploy the new version of the doc, but I still see the same issue in the doc:
![image](https://user-images.githubusercontent.com/12021701/57180374-4c867a80-6e88-11e9-97ee-1da60b9932bf.png)
Thanks

**Comment by tarrade** [comment] 2019-05-09 15:56
The issue was not fixed with the PR, please reopen the ticket. Thanks

**Comment by yongtang** [comment] 2019-05-09 16:14
@tarrade The page is pointing to 2.0.0alpha so it still use the docstring in 2.0.0 python. The PR #27596 fixes the issue in the master branch, it will show up in the next release of 2.0.0 (alpha or beta), then the web page will be re-rendered to capture the change.

I will re-open the issue for now, though I think once the next release of 2.0.0 (alpha or beta) is out the page will be updated and corrected automatically.

**Comment by tarrade** [comment] 2019-05-09 16:55
@yongtang ah ok got it. Since this was independend of a Tensorflow version (the format), I was think it will be probagated to the main branch and I could see the update on the main page. I am fine to have the ticket closed since the issue is really fixed.

**Comment by jvishnuvardhan** [comment] 2019-05-09 17:11
I am closing the issue as it was resolved. I have checked that the PR was merged already. It will reflect on the website soon. Thanks!

**Closed by jvishnuvardhan** 2019-05-09 17:11 UTC
Labels: 2.0, comp:keras, type:docs
