### ISSUE TITLE
sparse_placeholder no longer accepts python ints in shape argument

### ISSUE THREAD

**Issue by shawnjhenry** [tensorflow/tensorflow#6749] opened 2017-01-09 22:13 UTC
Hi,

After recently updating tensorflow, sparse_placeholder stopped working correctly.  It appears that the shape argument must now be int64 in order for tensorflow to convert the shape to a tensor, so the following fails:
```
ph = tf.sparse_placeholder(dtype=tf.float32, shape=(50, 10000))
```
with error message:
```
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("Const:0", shape=(2,), dtype=int32)'
```
This is inconsistent with the behavior of tf.placeholder, for which: 
```
ph = tf.placeholder(dtype=tf.float32, shape=(50, 10000))
```
succeeds. 

Thanks,
Shawn

**Comment by jart** [comment] 2017-01-11 03:06
Maybe @mrry can comment on what might be an issue with the `tf.sparse_placeholder` shape API.

**Comment by mrry** [comment] 2017-01-11 17:30
Looks like the problem is in `array_ops._normalize_sparse_shape()`. It converts its argument to a tensor, which for a list of Python `int` values will result in a `tf.int32` tensor. I suspect the correct answer is to add a `dtype=dtypes.int64` to the `ops.convert_to_tensor()` call, but since there doesn't appear to be any unit test for this I'll defer to @ilblackdragon, who originally added that function.

**Comment by kilsen512** [comment] 2017-01-13 08:12
simple workaround:
`
shape = [1, 3]
shape = np.array(shape, dtype=np.int64)
tf.sparse_placeholder(tf.int32, shape=shape)
`

**Comment by michaelosthege** [comment] 2017-03-15 03:41
Any update on this issue? @ilblackdragon

**Comment by rolfe** [comment] 2017-04-19 00:00
I also seem to be having the same problem.  Has there been any progress on this issue?

**Comment by meereeum** [comment] 2017-04-28 02:36
The workaround is all well and good

```
>> foo = tf.sparse_placeholder(tf.float32, shape=np.array([10, 47], dtype=np.int64))
>> foo.get_shape()
TensorShape([Dimension(10), Dimension(47)])
```

.... until you want a variable dimension

```
>> bar = tf.sparse_placeholder(tf.float32, shape=[None, 47])
>> bar.get_shape()
TensorShape(None)
>> bar2 = tf.sparse_placeholder(tf.float32, shape=np.array([None, 47], dtype=np.int64))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by skye** [comment] 2017-06-16 21:37
Marking this as contributions welcome. @ilblackdragon please let me know if you plan to fix this.

**Comment by yongtang** [comment] 2017-06-29 22:36
Added a PR #11153 with test cases.

**Closed** 2017-07-11 04:14 UTC
Labels: stat:contributions welcome, type:bug/performance
