### ISSUE TITLE
Cardinality returns unknown for a dataset with (string, float), but also for dataset with float variable alone

### ISSUE THREAD

**Issue by lynochka** [tensorflow/tensorflow#43047] opened 2020-09-08 14:01 UTC
Cardinality returns unknown from a dataset with (string, float) but also for dataset with float variable alone. 

I created data stored in a csv files without header representing text and a float number corresponding to this text (NALU like dataset). 

I susptect that it is not possible to find the size of the data since the first column is a string it gives me an UNKNOWN cardinality (-2) back.

Dataset creation: 
```py
import tensorflow_datasets as tfds
import tensorflow as tf

with open("file.csv", "w") as f:
    for text, number in [("one", 1.0), ("two", 2.0)]:
        f.write(f"{text:s}, {number:.1f}\n")

ds = tf.data.experimental.CsvDataset(
    filenames="file.csv", record_defaults=[tf.string, tf.float32], header=False)

tf.data.experimental.cardinality(ds)
```

One would expect that when creating a dataset with the float column only, or mapping the dataset to the target only, the cardinality would be returned properly, but the next mapping stil has UNKNOWN cardinality.

```py
# check first method:
with open("file1.csv", "w") as f:
    for number in [1.0, 2.0]:
        f.write(f"{number:.1f}\n")

ds1 = tf.data.experimental.CsvDataset(
    filenames="file1.csv", record_defaults=[tf.float32], header=False)

tf.data.experimental.cardinality(ds1)
#returns -2

# check second method
def get_target_pyfn(text, target):
    target = tf.py_function(lambda text, target: target, inp=[text, target], Tout=tf.float32)
    target.set_shape([])
    return target

tf.data.experimental.cardinality( ds.map(get_target_pyfn))
#returns -2
```

**System information**
tensorflow version = 2.3.0
Python virtual environment is setup with pyproject.toml in https://github.com/lynochka/parser/blob/bf2a006bee210b62552618dceb181101655753ff/pyproject.toml

**Comment by Saduf2019** [comment] 2020-09-08 14:06
@lynochka 
Please fill in issue template for us to help. tf version, simple stand alone code to replicate the issue faced or share a colab gist with issue reported with error logs.

**Comment by bhack** [comment] 2020-09-08 14:13
Check https://github.com/tensorflow/tensorflow/issues/30529#issuecomment-510814608

**Comment by lynochka** [comment] 2020-09-08 14:15
Update the issue with tensorflow = 2.3.0, the code is standalone now that the imports are added

**Comment by lynochka** [comment] 2020-09-08 14:17
From link you gave, looks like it is less of a bug and more of a feature request ?

**Comment by bhack** [comment] 2020-09-08 14:18
>tf.data.experimental.UNKNOWN_CARDINALITY if the analysis fails to determine the number of elements in dataset (e.g. when the dataset source is a file).

**Comment by bhack** [comment] 2020-09-08 14:30
If you see I've just quoted the official documention.
It Is by design.

**Comment by bhack** [comment] 2020-09-08 16:08
@jsimsa Can we close this?

**Comment by jsimsa** [comment] 2020-09-08 16:33
Correct, this is working as intended. If you wish to compute the cardinality of a dataset whose cardinality is not known statically (and thus requires iterating over the entire dataset), you can do so via:

```
num_elements = 0
for _ in dataset:
  num_elements = num_elements + 1
```

**Closed by jsimsa** 2020-09-08 16:33 UTC
Labels: stat:awaiting response, type:bug
