### ISSUE TITLE
TF dataset padded_batch: support for batching non-padable component

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tensorflow#19762] opened 2018-06-05 03:58 UTC
Current` tf.data.dataset `class only support `padded_batch` method which would pad every component into same shape, but there are cases that some component may not be padable, e.g., in object detection input pipeline, the ground truth calsses and bounding boxes are different for different image, so they can not be padded to the same shape as images, so how to batch these data in this case?

**Comment by tensorflowbutler** [comment] 2018-06-05 12:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment] 2018-06-05 21:43
Seems like this is a duplicate of #19710, so closing this. Feel free to reopen if I'm mistaken.

**Comment by MrWanter** [comment] 2018-06-06 07:10
Hi! it is not a duplicate, internal TF dataset API do not have a good support for batching things for object detection model, e.g., different image can be resized/padded into same shape, but may have different number of groundtruth boxes, in object detection API, they batch padded groundtruth boxes tensors, and manually recover them latter, so the question is better implementation in the batching stage with tf.data.dataset may bring more efficiency.

**Comment by asimshankar** [comment] 2018-06-06 10:02
Indeed, sorry, I only made a cursory read.
That said though, could you elaborate on what you'd like the behavior to be? Are you suggesting that the "batches" contain tensors of irregular shapes?

**Comment by MrWanter** [comment] 2018-06-06 11:54
Yes, I that may be a bit irregular for tensors and not implementable, but can we add feature to batch tensors into list of different length tensors, so the job can be down, without post recovering of the shapes

**Comment by asimshankar** [comment] 2018-06-18 18:30
Can you use [`group_by_window`](https://www.tensorflow.org/api_docs/python/tf/contrib/data/group_by_window) to bin the different length tensors?

**Comment by tensorflowbutler** [comment] 2018-07-03 12:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by MrWanter** [comment] 2018-07-06 04:56
no, group_by_window can be used to batch similar shaped tensors, like similar aspect ratio tensors, but the question is in object detection, we may first use group_by_window to group similar aspect ratio images, then we have to deal with batching ground truth boxes and cls labels, which has to be padded to same shape within the whole batch to form a tensor. Then we have to recover the actual shape of ground truth boxes and cls labels, so the question is in bathing stage, can we add this support instead of force pad to same shape.

**Comment by asimshankar** [comment] 2018-07-06 19:28
@jsimsa @mrry may have some guidance here, such as suggestions on if and how someone could contribute to this feature.

**Closed** 2018-07-06 20:48 UTC

**Comment by Fanshia** [comment] 2019-07-04 19:31
Hi? I have the same question.  Is there any answer to this issue?

**Comment by world4jason** [comment] 2019-12-10 01:24
same question here

**Comment by jsimsa** [comment] 2019-12-10 01:30
See https://github.com/tensorflow/community/pull/5/files?short_path=df3302a#diff-df3302ad45d4c94d919eefaefa059780.
