### ISSUE TITLE
Unable to run native XLA AOT tests

### ISSUE THREAD

**Issue by willxujun** [tensorflow/tensorflow#28787] opened 2019-05-17 02:04 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.12
- Python version: python 3.6.3
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.1 (clang-1001.0.46.4)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
There is a set of native tests in tensorflow/compiler/aot/tests. I am not able to run them using bazel because of a linking error while building the rule `tfcompile_test` in .../tests/BUILD. Specifically, `tfcompile_test` depends upon `test_graph_tfmatmulandadd_with_profiling` and `test_graph_tfmatmulandadd` which fail to link.

**Code to reproduce the issue**
In an untouched Tensorflow repo with r1.12 checkout and bazel 0.18.1 installed, run
`bazel build //tensorflow/compiler/aot/tests:tfcompile_test`

**Describe the current behavior**
Error message is as follows:
`/Users/willxujun/code/tensorflow/tensorflow/compiler/aot/tests/BUILD:225:1: Linking of rule '//tensorflow/compiler/aot/tests:tfcompile_test' failed (Exit 1)
Undefined symbols for architecture x86_64:
 "___tfcompile_MatMulAndAddCompWithProfiling_HloProfilePrinterData_protobuf_array_contents", referenced from:
      MatMulAndAddCompWithProfiling::StaticData()::'lambda'()::operator()() const in tfcompile_test.o
  "___tfcompile_MatMulAndAddComp_ProgramShape_protobuf_array_contents", referenced from:
      MatMulAndAddComp::StaticData()::'lambda'()::operator()() const in tfcompile_test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/compiler/aot/tests:tfcompile_test failed to build`

The problem seems to stem from constructing MatMulAndAddCompWithProfiling or MatMulAndAddComp objects in `tfcompile_test.cc`. These two classes are graphs compiled by XLA. 
Disabling the relevant tests in `tfcompile_test.cc` makes the issue go away.
Alternatively, in .../aot/tests/BUILD, removing tfcompile_flags from test_graph_tfmatmulandadd, and setting enable_xla_hlo_profiling to False in test_graph_tfmatmulandadd_with_profiling makes the issue go away.
This problem seems to happen to only macOS. I could run the same command without issues in Ubuntu 16.04.
This problem seems to be related to the linking of dependencies. I could successfully run the individual `tf_library`s and get the compiled graph classes in bazel_genfiles/, and both undefined symbols are "extern C" variables found in the graphs' header files, and it seems the root definition is not found somehow. As a result, the graph objects cannot be constructed.

**Describe the expected behavior**
In Ubuntu 16.04, build succeeds with the following:
`INFO: Build completed successfully, 3560 total actions`
Then a tfcompile_test executable would be produced in bazel_bin/tensorflow/compiler/aot/tests, which can be run successfully.

**Other info / logs**
N/A

**Comment by muddham** [comment] 2019-05-27 08:53
@willxujun Request you to please follow the [link](https://www.tensorflow.org/install/source#tested_build_configurations), as per the reference the bazel version for 1.12 is 0.15.0

**Comment by willxujun** [comment] 2019-05-31 07:30
Re-run using Bazel 0.15.0 exhibits identical behaviour

**Comment by jlebar** [comment] 2019-06-11 00:14
> TensorFlow version: r1.12

Does this reproduce at git head?

**Comment by ymodak** [comment] 2019-08-29 22:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-08-29 22:39 UTC
Labels: TF 1.12, comp:xla, subtype:macOS, type:build/install
