### ISSUE TITLE
Standardizing the saved format and/or converting to big-endian on read

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#16364] opened 2018-01-24 13:52 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 s390x
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: bazel test -c opt //tensorflow/python:framework_meta_graph_test which invokes meta_graph.import_scoped_meta_graph.

### Describe the problem
The testdata for //tensorflow/python:framework_meta_graph_test is not platform independent and causes test to fail on Big Endian systems.

As per discussion in #16003 , correct approach would be standardizing the stored format and/or conversion on load based on endianness. Can someone have a look?

**Comment by asimshankar** [comment] 2018-01-25 06:48
For context, this has come up before (see https://github.com/tensorflow/tensorflow/issues/11290#issuecomment-321380067 for example).

**Comment by frreiss** [comment] 2019-05-07 01:21
As discussed on the mailing list (https://groups.google.com/a/tensorflow.org/d/msg/developers/GOzGNx8GnHg/oxBFij5ACAAJ), I have implemented a fix for this issue that involves inspecting the `endianness` field of the bundle header on read and byte-swapping tensor values as needed. I should have a PR shortly.

**Comment by Nayana-ibm** [comment] 2019-07-19 06:10
Looks liked fixed by https://github.com/tensorflow/tensorflow/issues/16540.
This issue can be closed

**Closed** 2019-09-10 10:21 UTC
Labels: stat:contributions welcome

**Comment by Masquerade0097** [comment] 2020-07-23 08:41
I'm facing errors while trying to load model graphs on s390x from protobuf file. I think this issue is related to it - #41652

**Comment by Masquerade0097** [comment] 2020-07-29 16:24
@namrata-ibm @Nayana-ibm @frreiss @asimshankar  I tried loading the model graph on s390x from a protobuf file of the model but it failed. I think the issue is similar to this, can you please look into it. I've described the details here - #41652
