### ISSUE TITLE
kears.layers.concatenate Does Not Work when Saving a Model

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#35441] opened 2019-12-27 07:48 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): A custom model
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.0.0
- Python version:  3.75
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.1
- GPU model and memory: Quadro K620M

**Describe the current behavior**

I built a custom model as follows

```
	class C3BR(tf.keras.Model):
		''' 3D Convolution + Batch Normalisation + Relu '''
		def __init__(self, filterNum, kSize, strSize, padMode):
			super(C3BR, self).__init__()
			self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
			self.BN = layers.BatchNormalization(axis=1)
		
		def call(self, inputs, ifTrain=True):
			x = self.conv(inputs)
			if ifTrain == True:
				x= self.BN(x)
			return activations.relu(x)

		def build_model(self, input_shape):
			''' A work-around to define dimensions of signals through the NN'''
			self.build(input_shape)
			inputs = tf.keras.Input(shape=input_shape[1:])
			_ = self.call(inputs) 

	class SimpleUNet1(tf.keras.Model):
		"""
		Serialise basic units so as to build up a double-layered encoder-decoder U-Net
		Input:
			inDim: (for initialisation) [modaility/channel, tensor dimensions]
			classNum: background included
			name: name for the net
			inputs: 5D tf tensor of [mbSize, modaility/channel, tensor dimensions]. Inputs must be organised into channel first order
			input_shape: a 1X5 tuple [mbSize, modaility/channel, tensor dimensions]
			ifTrain: True for training, and False for validation and testing
		Returns:
			outputs: 5D tf tensor of [mbSize, classNum, tensor dimensions]
		"""
		def __init__(self, inDim, classNum, name='SimpleUNet', **kwarg):
			super(SimpleUNet1, self).__init__(name=name, **kwarg)
			self.inDim = inDim
			self.classNum = classNum
			dimEnSt1End = np.array(inDim)[2:]-2-2
			dimEnSt2Ed = dimEnSt1End/2-2-2
			dimBridgeEnd = (dimEnSt2Ed/2-2-2)*2
			dimDEStd1End = (dimBridgeEnd-2-2)*2
			self.outDim = dimDEStd1End-2-2-2
			temp = ((dimEnSt2Ed - dimBridgeEnd)/2).astype('int32')
			crop3d1 = tuple(np.tile(temp, (2, 1)).T)
			temp = ((dimEnSt1End - dimDEStd1End)/2).astype('int32')
			crop3d2 = tuple(np.tile(temp, (2, 1)).T)

			self.en_st1_cbr1 = C3BR(32, 3, 1, 'valid')
			self.en_st1_cbr2 = C3BR(64, 3, 1, 'valid')
			self.en_st2_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
			self.en_st2_cbr1 = C3BR(64, 3, 1, 'valid')
			self.en_st2_cbr2 = C3BR(128, 3, 1, 'valid')
			self.bridge_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
			self.bridge_cbr1 = C3BR(128, 3, 1, 'valid')
			self.bridge_cbr2 = C3BR(256, 3, 1, 'valid')    
			self.bridge_tconv1 = layers.Conv3DTranspose(256, 2, strides=2, padding='valid', data_format='channels_first')
			self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
			self.de_st1_concat = layers.Concatenate(axis=1)
			self.de_st1_cbr1 = C3BR(256, 3, 1, 'valid')
			self.de_st1_cbr2 = C3BR(128, 3, 1, 'valid')    
			self.de_st1_tconv1 = layers.Conv3DTranspose(128, 2, strides=2, padding='valid', data_format='channels_first')
			self.de_3dcrop2 = layers.Cropping3D(crop3d2, data_format='channels_first')
			self.de_st2_concat = layers.Concatenate(axis=1)
			self.de_st2_cbr1 = C3BR(64, 3, 1, 'valid')
			self.de_st2_cbr2 = C3BR(64, 3, 1, 'valid') 
			self.final_conv3D = layers.Conv3D(filters=self.classNum, kernel_size=3, strides=1, padding='valid', data_format='channels_first')
					
		#@tf.function
		def call(self, inputs, ifTrain=True):
			x0 = self.en_st1_cbr1(inputs, ifTrain)
			xEnSt1End = self.en_st1_cbr2(x0, ifTrain)
			x1 = self.en_st2_mp(xEnSt1End)
			x2 = self.en_st2_cbr1(x1, ifTrain)
			xEnSt2Ed = self.en_st2_cbr2(x2, ifTrain)
			x3 = self.bridge_mp(xEnSt2Ed)  
			x4 = self.bridge_cbr1(x3, ifTrain)
			x5 = self.bridge_cbr2(x4, ifTrain)    
			xBridgeEnd = self.bridge_tconv1(x5)
			xCrop1 = self.de_3dcrop1(xEnSt2Ed)
			print(xBridgeEnd.shape)
			print(xCrop1.shape)
			x6 = self.de_st1_concat([xBridgeEnd, xCrop1])
			print(x6.shape)
			x7 = self.de_st1_cbr1(x6, ifTrain)
			x8 = self.de_st1_cbr2(x7, ifTrain)
			xDeSt1End = self.de_st1_tconv1(x8)
			xCrop2 = self.de_3dcrop2(xEnSt1End)
			x9 = self.de_st2_concat([xDeSt1End, xCrop2])
			x10 = self.de_st2_cbr1(x9, ifTrain)
			x11 = self.de_st2_cbr2(x10, ifTrain)
			x12 = self.final_conv3D(x11)
			outputs = activations.softmax(x12, axis=1)
			
			return outputs
			
		def build_model(self, input_shape):
			''' A work-around to define dimensions of signals through the NN'''
			self.build(input_shape)
			inputs = tf.keras.Input(shape=input_shape[1:])

			_ = self.call(inputs)
			
		def compute_output_shape(self):
			# Override this function if one expects to use the subclassed model in Kera's fit() method; Otherwise, it is optional.
			return tf.TensorShape(np.append(self.classNum, self.outDim))    

```

Please pay attention to the following two definitions. If I use concatenate layer in this way (the C is a capitalised one), when I try and save the model, it works
```
	self.de_st1_concat = layers.Concatenate(axis=1)
	self.de_st2_concat = layers.Concatenate(axis=1)
```
For instance,
```
	modelInDim = (4, 64, 64, 64)
	classNum = 2
	mbSize = 2
	TUNet = SimpleUNet1(modelInDim, classNum)
	TUNet.build_model(input_shape=(mbSize,)+modelInDim)
	x=tf.random.uniform((mbSize, 4, 64, 64, 64))
	y=TUNet(x)
	TUNet.summary()
	TUNet._set_inputs(x)
	TUNet.save(r'...\TTweight', save_format='tf') 
```

But if, as per [this page](https://www.tensorflow.org/api_docs/python/tf/keras/layers/concatenate?hl=en&version=stable) I use layers.concatenate (small 'c') to generate signals x6 and x9, respectively, that is
```
	x6 = layers.concatenate([xBridgeEnd, xCrop1], axis=1)
	x9 = layers.concatenate([xDeSt1End, xCrop2], axis=1)
```
Then save the model in the same way above, it raised an error
```
	  ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 256, None, None, None), (None, 128, 18, 18, 18)]
```
The detailed log is [here](https://github.com/tensorflow/tensorflow/issues/19241)

It takes me almost an entire day to figure out the root cause. In conclusion, I think the second one may have to be deprecated; otherwise users like me will be confused and misguided.

**Comment by yourtheron** [comment] 2020-01-02 07:57
@gadagashwini @gowthamkpr 
I encountered a further issue when trying to save the model under the mixed precision version. It quite confusing. I followed instructions at [here](https://www.tensorflow.org/guide/keras/mixed_precision#training_the_model_with_a_custom_training_loop)
So I did the following
```
from tensorflow.keras.mixed_precision import experimental as mixed_precision
curOpt = tf.keras.optimizers.Adam(learning_rate=lr)
curOpt = mixed_precision.LossScaleOptimizer(curOpt, loss_scale='dynamic')
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)
# query if it has been well set
print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
from MedNN import SimpleUNet
TUNet = SimpleUNet(modelInDim, classNum)
TUNet.build_model(input_shape=(mbSize,)+modelInDim)
```
Then if I use a test signal x0 of tf.float32 to do the following:
```
x0 =tf.random.uniform((mbSize, 4, 64, 64, 64), dtype=tf.float32)
y=TUNet(x0, True)
TUNet.summary()
TUNet._set_inputs(x0, True)
# Method #1
tf.saved_model.save(TUNet, r'...\TUNet_Test')
# Method #2
TUNet.save(r'...\TUNet_Test', save_format='tf') 
```
Whether I ran method #1 or 2, an error was raised. It seems the dtype does not match
```
ValueError: Python inputs incompatible with input_signature: inputs ((<tf.Tensor 'conv3d/Cast:0' shape=(None, 4, 64, 64, 64) dtype=float16>,)), input_signature ((TensorSpec(shape=(None, 4, None, None, None), dtype=tf.float32, name=None),))
```
Even if I cast x0 into tf.float16, the same error occurs.

So my questions are:
1. Is it a bug about tf's functionality of saving custom model or mixed precision?
2. Can I use mixed precision for custom models safely?
3. If it is neither, how can I fix the problem?
I am aware that multiple issues are involved here, and I might need to report them in different issues, Yet they are tightly coupled as presented above, hence could they be scrutinised here in this issue altogether? Many thanks, indeed!

**Comment by yourtheron** [comment] 2020-01-02 08:10
At the same time, I would like to say that I surmise that loads of people tend to use custom layers, custom loops, custom models, and custom training, but tf's doc seems not quite to keep apace well. For example, in the mixed precision guide (the link above), it uses the toy example of digit recognition, then states the following:
![捕获](https://user-images.githubusercontent.com/51472988/71657145-9e7bea80-2d0c-11ea-8a97-4c907a9d8fe2.JPG)

1. Why can't the doc use a more explicit or articulating example to state such a delicate and important case?
2. The underlined sentence is quite confusing. Will the model do it automatically, or shall the user do it, for example in the call() function of a custom model?

**Comment by yourtheron** [comment] 2020-01-02 10:03
Another issue about loading custom models:
After saving it in tf format as I mentioned in the first post, I load it by
```
newModel= tf.keras.models.load_model(...path)
```
The path contains the following
![image](https://user-images.githubusercontent.com/51472988/71661707-105c3000-2d1d-11ea-8d66-37722cd4e8a5.png)

Yet tf prompts

**Comment by reedwm** [comment] 2020-01-22 01:02
When I try to run the code in the original post, I get the error:

```
Traceback (most recent call last):
  File "issue35441.py", line 118, in <module>
    TUNet = SimpleUNet1(modelInDim, classNum)
  File "issue35441.py", line 63, in __init__
    self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
  File "/usr/local/google/home/reedwm/venvs/tf2_0/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 2565, in __init__
    'Found: ' + str(cropping))
ValueError: `cropping` should have 3 elements. Found: (array([4, 4], dtype=int32), array([4, 4], dtype=int32))
```

I am unfamiliar with UNet so I'm not sure what's wrong. Also, it would help if you post a single self-contained example to reproduce the issue. In your original post, you split the code over several code blocks, and you don't have the import statements like `import tensorflow as tf`.

Can you post a self-contained example to reproduce the original issue?

As for your mixed-precision related questions:

> 1. Is it a bug about tf's functionality of saving custom model or mixed precision?

It's probably a bug with the combination of the two features. But this may have been fixed by cd6184047e9e497955c473b88387b54818ff23a0 so try again with the latest nightly build. You can install a nightly build with `pip install tf-nightly`.

> 2. Can I use mixed precision for custom models safely?

Yes, this should work.

> Why can't the doc use a more explicit or articulating example to state such a delicate and important case?

Agreed this point is not emphasized much. I did try to make this clear, as earlier in the doc, there is a sentence stating the same thing: "They cast their inputs to float16 in order to do float16 computations, which causes their outputs to be float16 as a result." After that sentence, there is an example showing the output is float16.

It was tough to balance having a lot of explanation on details like that, and having the doc be too long. I will see if I can make this more clear but I also don't want to add another paragraph as the doc is already very long.

> The underlined sentence is quite confusing. Will the model do it automatically, or shall the user do it, for example in the call() function of a custom model?

The model will automatically do it. I'll also see if I can add a sentence stating this to the doc. This is useful information, but it's tough to find a good place to mention this.

**Comment by yourtheron** [comment] 2020-01-22 07:25
@reedwm Sorry for the confusion, here is the complete code, which I have tested via Colab.
```
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, activations

class C3BR(tf.keras.Model):
		''' 3D Convolution + Batch Normalisation + Relu '''
		def __init__(self, filterNum, kSize, strSize, padMode):
			super(C3BR, self).__init__()
			self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
			self.BN = layers.BatchNormalization(axis=1)
		
		def call(self, inputs, ifTrain=True):
			x = self.conv(inputs)
			if ifTrain == True:
				x= self.BN(x)
			return activations.relu(x)

		def build_model(self, input_shape):
			''' A work-around to define dimensions of signals through the NN'''
			self.build(input_shape)
			inputs = tf.keras.Input(shape=input_shape[1:])
			_ = self.call(inputs) 

class SimpleUNet1(tf.keras.Model):
	"""
	Serialise basic units so as to build up a double-layered encoder-decoder U-Net
	Input:
		inDim: (for initialisation) [modaility/channel, tensor dimensions]
		classNum: background included
		name: name for the net
		inputs: 5D tf tensor of [mbSize, modaility/channel, tensor dimensions]. Inputs must be organised into channel first order
		input_shape: a 1X5 tuple [mbSize, modaility/channel, tensor dimensions]
		ifTrain: True for training, and False for validation and testing
	Returns:
		outputs: 5D tf tensor of [mbSize, classNum, tensor dimensions]
	"""
	def __init__(self, inDim, classNum, name='SimpleUNet', **kwarg):
		super(SimpleUNet1, self).__init__(name=name, **kwarg)
		self.inDim = inDim
		self.classNum = classNum
		dimEnSt1End = np.array(inDim)[1:]-2-2
		dimEnSt2Ed = dimEnSt1End/2-2-2
		dimBridgeEnd = (dimEnSt2Ed/2-2-2)*2
		dimDEStd1End = (dimBridgeEnd-2-2)*2
		self.outDim = dimDEStd1End-2-2-2
		temp = ((dimEnSt2Ed - dimBridgeEnd)/2).astype('int32')
		crop3d1 = tuple(np.tile(temp, (2, 1)).T)
		temp = ((dimEnSt1End - dimDEStd1End)/2).astype('int32')
		crop3d2 = tuple(np.tile(temp, (2, 1)).T)

		self.en_st1_cbr1 = C3BR(32, 3, 1, 'valid')
		self.en_st1_cbr2 = C3BR(64, 3, 1, 'valid')
		self.en_st2_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
		self.en_st2_cbr1 = C3BR(64, 3, 1, 'valid')
		self.en_st2_cbr2 = C3BR(128, 3, 1, 'valid')
		self.bridge_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
		self.bridge_cbr1 = C3BR(128, 3, 1, 'valid')
		self.bridge_cbr2 = C3BR(256, 3, 1, 'valid')    
		self.bridge_tconv1 = layers.Conv3DTranspose(256, 2, strides=2, padding='valid', data_format='channels_first')
		self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
		self.de_st1_concat = layers.Concatenate(axis=1)
		self.de_st1_cbr1 = C3BR(256, 3, 1, 'valid')
		self.de_st1_cbr2 = C3BR(128, 3, 1, 'valid')    
		self.de_st1_tconv1 = layers.Conv3DTranspose(128, 2, strides=2, padding='valid', data_format='channels_first')
		self.de_3dcrop2 = layers.Cropping3D(crop3d2, data_format='channels_first')
		self.de_st2_concat = layers.Concatenate(axis=1)
		self.de_st2_cbr1 = C3BR(64, 3, 1, 'valid')
		self.de_st2_cbr2 = C3BR(64, 3, 1, 'valid') 
		self.final_conv3D = layers.Conv3D(filters=self.classNum, kernel_size=3, strides=1, padding='valid', data_format='channels_first')
				
	#@tf.function
	def call(self, inputs, ifTrain=True):
		x0 = self.en_st1_cbr1(inputs, ifTrain)
		xEnSt1End = self.en_st1_cbr2(x0, ifTrain)
		x1 = self.en_st2_mp(xEnSt1End)
		x2 = self.en_st2_cbr1(x1, ifTrain)
		xEnSt2Ed = self.en_st2_cbr2(x2, ifTrain)
		x3 = self.bridge_mp(xEnSt2Ed)  
		x4 = self.bridge_cbr1(x3, ifTrain)
		x5 = self.bridge_cbr2(x4, ifTrain)    
		xBridgeEnd = self.bridge_tconv1(x5)
		xCrop1 = self.de_3dcrop1(xEnSt2Ed)
		print(xBridgeEnd.shape)
		print(xCrop1.shape)
		x6 = self.de_st1_concat([xBridgeEnd, xCrop1])
		print(x6.shape)
		x7 = self.de_st1_cbr1(x6, ifTrain)
		x8 = self.de_st1_cbr2(x7, ifTrain)
		xDeSt1End = self.de_st1_tconv1(x8)
		xCrop2 = self.de_3dcrop2(xEnSt1End)
		x9 = self.de_st2_concat([xDeSt1End, xCrop2])
		x10 = self.de_st2_cbr1(x9, ifTrain)
		x11 = self.de_st2_cbr2(x10, ifTrain)
		x12 = self.final_conv3D(x11)
		outputs = activations.softmax(x12, axis=1)
		
		return outputs
		
	def build_model(self, input_shape):
		''' A work-around to define dimensions of signals through the NN'''
		self.build(input_shape)
		inputs = tf.keras.Input(shape=input_shape[1:])

		_ = self.call(inputs)
		
	def compute_output_shape(self):
		# Override this function if one expects to use the subclassed model in Kera's fit() method; Otherwise, it is optional.
		return tf.TensorShape(np.append(self.classNum, self.outDim))    

modelInDim = (4, 64, 64, 64)
classNum = 2
mbSize = 2
TUNet = SimpleUNet1(modelInDim, classNum)
TUNet.build_model(input_shape=(mbSize,)+modelInDim)
TUNet.summary()
TUNet.save(r'e:\TTweight', save_format='tf') 
```
The above works in saving the moel
If we change the code above into
```
x6 = layers.concatenate([xBridgeEnd, xCrop1], axis=1)
x9 = layers.concatenate([xDeSt1End, xCrop2], axis=1)
```
An error was raised as stated before.

Has the solution for saving models under mixed precision been submitted to Tf2.1 as well?

By the way, at present I am saving neither model nor weight. I simply save everything to a checkpoint, and it can be loaded back. It is fine as long as I work in Python environment and have full access to original code for building up the model, but not export model to C++ etc.

Finally, I would say as I proceed in the doc (basically I read all of the guide and tutorial except the RNN part that is not my field), I have got a strong feeling that the writing style in different parts differ a lot. Sometimes semi-formal, sometimes informal, even colloquial. I, being a non-native English speaker, am afraid to say there are even some grammatical mistakes and pdigin English, which do not hinder engineers from understanding the stuff though, are flaws. Hope Google will pay some attentions to it.

**Comment by reedwm** [comment] 2020-01-22 20:43
Thanks for the example to reproduce! However, when I try running the new example (without changing the x6 and x9 lines to the version), I get the error:

```
ValueError: Model <__main__.SimpleUNet1 object at 0x7f7ea76ec690> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).
```

Can you double check the example? I got that above error in TF 2.0, TF 2.1, and the nightly TF.

> Has the solution for saving models under mixed precision been submitted to Tf2.1 as well?

Unfortunately no. The fix will only be in TF 2.2 and above.

> Finally, I would say as I proceed in the doc (basically I read all of the guide, the tutorial, as well as 2.0.0 API except the RNN and reinforcement learning part that are not my field), I have got a strong feeling that the writing style in different parts differ a lot. Sometimes semi-formal, sometimes informal, even colloquial. I, being a non-native English speaker, am afraid to say there are even some grammatical mistakes and pdigin English, which do not hinder engineers from understanding the stuff though, are flaws. Hope Google will pay some attentions to it.

Thanks for the feedback. Ideally all documentation should conform to the [Google documentation style guide](https://developers.google.com/style). Feel free to point out different docs where you think the writing style differs a lot, or where there are grammatical mistakes. You can also file a new issue for this. The docs are written by different people so style may differ, but we try to keep the style consistent.

**Comment by yourtheron** [comment] 2020-01-23 08:46
@reedwm I see. Well, for some reason I do not know, we have run a dummy signal through the net as follows before saving the model
```
x=tf.random.uniform((mbSize, 4, 64, 64, 64))
y=TUNet(x)
# use your directory in lieu of r'...\TTweight'
TUNet.save(r'...\TTweight', save_format='tf') 
```
or
```
x=tf.random.uniform((mbSize, 4, 64, 64, 64))
TUNet._set_inputs(x)
TUNet.save(r'...\TTweight', save_format='tf') 
```

**Comment by reedwm** [comment] 2020-01-23 20:31
With your second code sample, with `TUNet._set_inputs(x)`, I was able to get the example to work. Once I replace `x6` and `x9` though, I get a different error on the `TUNet.summary()` line. If I comment the summary line out, I can reproduce your original error in TF 2.0 ("A `Concatenate` layer requires inputs with matching shapes..."). However, I cannot reproduce in TF 2.1. Therefore, I'm assuming the original issue is fixed so I'm closing it.

However, there still may be a bug, as the summary doesn't work. Feel free to file another bug about that if you think that is an issue, with a self-contained example to reproduce. If you do file such a bug, consider CCing me (add the line "/CC @reedwm") as I have some context and can therefore more easily triage to someone else.

For reference, here is the code sample I ran that works in TF 2.0 but not TF 2.1. It is the same as the code sample you provided, except i called `_set_inputs` as you suggested, I commented out `TUNet.summary()`, and I replaced `x6` and `x9` as you suggested.

```
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, activations

class C3BR(tf.keras.Model):
  ''' 3D Convolution + Batch Normalisation + Relu '''
  def __init__(self, filterNum, kSize, strSize, padMode):
    super(C3BR, self).__init__()
    self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
    self.BN = layers.BatchNormalization(axis=1)

  def call(self, inputs, ifTrain=True):
    x = self.conv(inputs)
    if ifTrain == True:
      x= self.BN(x)
    return activations.relu(x)

  def build_model(self, input_shape):
    ''' A work-around to define dimensions of signals through the NN'''
    self.build(input_shape)
    inputs = tf.keras.Input(shape=input_shape[1:])
    _ = self.call(inputs)

class SimpleUNet1(tf.keras.Model):
  """
  Serialise basic units so as to build up a double-layered encoder-decoder U-Net
  Input:
    inDim: (for initialisation) [modaility/channel, tensor dimensions]
    classNum: background included
    name: name for the net
    inputs: 5D tf tensor of [mbSize, modaility/channel, tensor dimensions]. Inputs must be organised into channel first order
    input_shape: a 1X5 tuple [mbSize, modaility/channel, tensor dimensions]
    ifTrain: True for training, and False for validation and testing
  Returns:
    outputs: 5D tf tensor of [mbSize, classNum, tensor dimensions]
  """
  def __init__(self, inDim, classNum, name='SimpleUNet', **kwarg):
    super(SimpleUNet1, self).__init__(name=name, **kwarg)
    self.inDim = inDim
    self.classNum = classNum
    dimEnSt1End = np.array(inDim)[1:]-2-2
    dimEnSt2Ed = dimEnSt1End/2-2-2
    dimBridgeEnd = (dimEnSt2Ed/2-2-2)*2
    dimDEStd1End = (dimBridgeEnd-2-2)*2
    self.outDim = dimDEStd1End-2-2-2
    temp = ((dimEnSt2Ed - dimBridgeEnd)/2).astype('int32')
    crop3d1 = tuple(np.tile(temp, (2, 1)).T)
    temp = ((dimEnSt1End - dimDEStd1End)/2).astype('int32')
    crop3d2 = tuple(np.tile(temp, (2, 1)).T)

    self.en_st1_cbr1 = C3BR(32, 3, 1, 'valid')
    self.en_st1_cbr2 = C3BR(64, 3, 1, 'valid')
    self.en_st2_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
    self.en_st2_cbr1 = C3BR(64, 3, 1, 'valid')
    self.en_st2_cbr2 = C3BR(128, 3, 1, 'valid')
    self.bridge_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
    self.bridge_cbr1 = C3BR(128, 3, 1, 'valid')
    self.bridge_cbr2 = C3BR(256, 3, 1, 'valid')
    self.bridge_tconv1 = layers.Conv3DTranspose(256, 2, strides=2, padding='valid', data_format='channels_first')
    self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
    self.de_st1_concat = layers.Concatenate(axis=1)
    self.de_st1_cbr1 = C3BR(256, 3, 1, 'valid')
    self.de_st1_cbr2 = C3BR(128, 3, 1, 'valid')
    self.de_st1_tconv1 = layers.Conv3DTranspose(128, 2, strides=2, padding='valid', data_format='channels_first')
    self.de_3dcrop2 = layers.Cropping3D(crop3d2, data_format='channels_first')
    self.de_st2_concat = layers.Concatenate(axis=1)
    self.de_st2_cbr1 = C3BR(64, 3, 1, 'valid')
    self.de_st2_cbr2 = C3BR(64, 3, 1, 'valid')
    self.final_conv3D = layers.Conv3D(filters=self.classNum, kernel_size=3, strides=1, padding='valid', data_format='channels_first')

  #@tf.function
  def call(self, inputs, ifTrain=True):
    x0 = self.en_st1_cbr1(inputs, ifTrain)
    xEnSt1End = self.en_st1_cbr2(x0, ifTrain)
    x1 = self.en_st2_mp(xEnSt1End)
    x2 = self.en_st2_cbr1(x1, ifTrain)
    xEnSt2Ed = self.en_st2_cbr2(x2, ifTrain)
    x3 = self.bridge_mp(xEnSt2Ed)
    x4 = self.bridge_cbr1(x3, ifTrain)
    x5 = self.bridge_cbr2(x4, ifTrain)
    xBridgeEnd = self.bridge_tconv1(x5)
    xCrop1 = self.de_3dcrop1(xEnSt2Ed)
    print(xBridgeEnd.shape)
    print(xCrop1.shape)
    x6 = layers.concatenate([xBridgeEnd, xCrop1], axis=1)
    print(x6.shape)
    x7 = self.de_st1_cbr1(x6, ifTrain)
    x8 = self.de_st1_cbr2(x7, ifTrain)
    xDeSt1End = self.de_st1_tconv1(x8)
    xCrop2 = self.de_3dcrop2(xEnSt1End)
    x9 = layers.concatenate([xDeSt1End, xCrop2], axis=1)
    x10 = self.de_st2_cbr1(x9, ifTrain)
    x11 = self.de_st2_cbr2(x10, ifTrain)
    x12 = self.final_conv3D(x11)
    outputs = activations.softmax(x12, axis=1)

    return outputs

  def build_model(self, input_shape):
    ''' A work-around to define dimensions of signals through the NN'''
    self.build(input_shape)
    inputs = tf.keras.Input(shape=input_shape[1:])

    _ = self.call(inputs)

  def compute_output_shape(self):
    # Override this function if one expects to use the subclassed model in Kera's fit() method; Otherwise, it is optional.
    return tf.TensorShape(np.append(self.classNum, self.outDim))

modelInDim = (4, 64, 64, 64)
classNum = 2
mbSize = 2
TUNet = SimpleUNet1(modelInDim, classNum)
TUNet.build_model(input_shape=(mbSize,)+modelInDim)
# TUNet.summary()

x=tf.random.uniform((mbSize, 4, 64, 64, 64))
TUNet._set_inputs(x)
# use your directory in lieu of r'...\TTweight'
TUNet.save(r'TTweight', save_format='tf')
```

**Closed by reedwm** 2020-01-23 20:31 UTC
Labels: TF 2.0, comp:keras, type:bug
