### ISSUE TITLE
TF 2.0 create model-- 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by ixNeo** [tensorflow/tensorflow#43521] opened 2020-09-24 05:42 UTC
tf version is 2.0,
below is my import packages:
```
import numpy as np
import keras.backend as K
import keras
from keras.engine.topology import Layer
from keras.layers import Input, Reshape,Dense, Activation, Flatten,Dropout,TimeDistributed,dot,concatenate,multiply,Permute,Add
from keras.layers.core import Lambda, Activation
from keras.models import Model
```
below is my code:
```
	inp = Input(shape=(TIME_STEPS, INPUT_DIM,))
	inp_time = Input(shape=(1,))
	print(inp_time.numpy())
```

below is my log
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/coolinear/Desktop/tjk_full_atte/demo_tjk_full_atte/model_full_atte.py", line 71, in <module>
    transformer_model(1251)
  File "/Users/coolinear/Desktop/tjk_full_atte/demo_tjk_full_atte/model_full_atte.py", line 32, in transformer_model
    print(inp_time.numpy())
AttributeError: 'Tensor' object has no attribute 'numpy'
```

what can i do, to transform a tensor(there is variable "inp_time") to a int?

**Comment by ravikyram** [comment] 2020-09-24 08:00
@ixNeo 

This is duplicate of #43516. Can we close here and track the issue in#43516.

Please, see similar issue #27519 and [SO link](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy) and see if it helps you.

Can you try with tf.compat.v1.disable_eager_execution() ans see if the issue still persists. Thanks!

**Comment by bhack** [comment] 2020-09-24 09:43
You cannot use `numpy()` cause it produces a symbolic tensor. 
It is documented at https://www.tensorflow.org/api_docs/python/tf/keras/Input:
> Note that even if eager execution is enabled, Input produces a symbolic tensor (i.e. a placeholder). This symbolic tensor can be used with other TensorFlow ops

**Closed** 2020-09-25 00:22 UTC
Labels: stat:awaiting response, type:bug
