### ISSUE TITLE
googletest.h used in open source project

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#26671] opened 2019-03-13 14:36 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-  OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit 6583b83dc9393118c60a9c11f15453c650fab89f
- Python version: 2.7.15rc1
- Installed using virtualenv? pip? conda?: sources
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
During compilation I get an error:
```
ERROR: /local/people/kamil_herba/tensorflow-x86/tensorflow/lite/testing/kernel_test/BUILD:81:1: Couldn't build file tensorflow/lite/testing/kernel_test/_objs/input_generator_test/input_generator_test.o: C++ comp
ilation of rule '//tensorflow/lite/testing/kernel_test:input_generator_test' failed (Exit 1)
tensorflow/lite/testing/kernel_test/input_generator_test.cc:21:44: fatal error: testing/base/public/googletest.h: No such file or directory
compilation terminated.
```
I guess that ```googletest.h``` is some internal Google header file which shouldn't be use in open source projects.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test tensorflow/lite/testing/kernel_test:input_generator_test

**Any other info / logs**
@liyunlu0618 could you take a look on that?

Other similar problems from the same commit
- tensorflow/lite/testing/kernel_test/generate_diff_report.cc:
```
tensorflow/lite/testing/kernel_test/generate_diff_report.cc:22:3: error: 'string' was not declared in this scope
   string base, test, output;
```
- tensorflow/lite/testing/kernel_test/util_test.cc
```
testing/base/public/googletest.h: No such file or directory
```
- tensorflow/lite/testing/kernel_test/diff_analyzer_test.cc:
```googletest.h``` is not used but ```FLAGS_test_tmpdir``` which probably comes from this header is used so it should be removed as well.

**Comment by feihugis** [comment] 2019-10-04 22:36
I have met the same problem when running the test for `tensorflow/lite/testing/kernel_test/util_test.cc`.

**Comment by mihaimaruseac** [comment] 2019-10-07 15:45
Google Test is a [publicly released open source library](https://github.com/google/googletest) that can be used by any other open source project. I see it is included as depenency in the `util_test.cc` target: https://github.com/tensorflow/tensorflow/blob/656e7a55387fac2df1b786013adbde79cdc95fd5/tensorflow/lite/testing/kernel_test/BUILD#L33-L49

Can you recompile from scratch and attach the log? Most likely the download of googletest archive didn't succeed and you missed that in the rest of the compilation log.

**Comment by feihugis** [comment] 2019-10-07 22:01
@mihaimaruseac I think the error is caused by [#include "testing/base/public/googletest.h"](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/testing/kernel_test/util_test.cc#L21). The error message is as below:
```
ERROR: /home/abc/tensorflow/tensorflow/lite/testing/kernel_test/BUILD:33:1: C++ compilation of rule '//tensorflow/lite/testing/kernel_test:util_test' failed (Exit 1)
tensorflow/lite/testing/kernel_test/util_test.cc:21:10: fatal error: testing/base/public/googletest.h: No such file or directory
 #include "testing/base/public/googletest.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/lite/testing/kernel_test:util_test failed to build
```
This PR #33123 is submitted to fix it. Could you please take a look?

**Comment by mihaimaruseac** [comment] 2019-10-07 22:25
Confirmed that I cannot compile `tensorflow/lite/testing/kernel_test:input_generator_test` although I can compile other targets using Google test. Assigning to lite/ code owners for review.

**Comment by gadagashwini** [comment] 2022-06-02 06:46
Hi @herbakamil, Looks like this issue has been fixed. 

Triage Note*
As this issue has been fixed by @nairb774 via (https://github.com/tensorflow/tensorflow/commit/1c88fff548acb048f2fe64fd2564e885759def12, https://github.com/tensorflow/tensorflow/commit/c9c0e70d0b1d6d4fd618c5ebdebd859dbe59848f, https://github.com/tensorflow/tensorflow/commit/db5816707ab0fc4ae6d3959a313d67dd871a8d9d)

Please take a look at this [comment](https://github.com/tensorflow/tensorflow/pull/33123#issuecomment-542983578). Kindly move this to closed status, if you think its resolved. Thanks!

**Closed** 2022-06-02 10:34 UTC
Labels: stat:awaiting response
