### ISSUE TITLE
Register.h not found

### ISSUE THREAD

**Issue by michael-stram** [tensorflow/tensorflow#23806] opened 2018-11-16 17:29 UTC
For the Xcode iOS project, I follow the steps, however during the build for device process, Xcode gives me an error stating that it cannot find the register.h file.

**System information**
- OS Platform and Distribution: macOS Mojave 10.14.2 and High Sierra 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): clones repo, followed instructions on website
- TensorFlow version: 1.12
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by michael-stram** [comment] 2018-11-16 17:31
Steps ( sorry for not posting in first post ):

Follow steps exactly as stated on TensorFlow website for the iOS demo project. Also in terminal, checked to make sure python was installed, brew, automate and lib tool, cocoa pods.

**Comment by JayThomason** [comment] 2018-11-16 19:57
I suspect this may be caused by commit 61c6c84964b4aec80aeace187aab8cb2c3e55a72.

**Comment by JayThomason** [comment] 2018-11-16 22:03
@michael-stram I can confirm that it works if you checkout 61c6c84964b4aec80aeace187aab8cb2c3e55a72~ and move into tensorflow/contrib/lite/examples/ios/camera

**Comment by michael-stram** [comment] 2018-11-16 22:14
Thank you Jay!!! umm, I'm about to ask something stupid..what do you mean by check out. Do I change the file path in Xcode  of the register.h file? Thanks!!

**Comment by JayThomason** [comment] 2018-11-16 22:57
@michael-stram Try this: close xcode, do `git checkout  61c6c84~` in terminal, and then follow the original instructions from the guide using `tensorflow/contrib/lite/examples/ios/camera` instead of `tensorflow/lite/examples/ios/camera`.

**Comment by michael-stram** [comment] 2018-11-16 23:01
Ohhhh...Thank you!

**Comment by michael-stram** [comment] 2018-11-17 16:52
I am trying to do the check out but I am getting an error saying its not a repository ?

**Comment by michael-stram** [comment] 2018-11-19 00:11
Hey Jay there's always two Xcode projects in that folder, do I remove one of them for the pod install?

Thanks!

**Comment by JayThomason** [comment] 2018-11-19 01:13
What I’ve been doing is either editing the pod file to specify the
Xcodeproj or just removing the second project.

**Comment by gerchicov-bp** [comment] 2018-11-19 13:29
I have the same issue. And it is independent from a concrete device:

- OS Platform and Distribution: OSX High Sierra 10.13.6
- Mobile device: iPhone 7, iOS 12.x
- TensorFlow installed from (source or binary):
https://www.tensorflow.org/lite/demo_ios
- TensorFlow version: 1.12.0
Other options have no influence because the project is not even compiled due to incorrect paths to files.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:59
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by shashishekhar** [comment] 2019-01-29 20:14
@gerchicov-bp: Does following instructions https://github.com/tensorflow/tensorflow/issues/23806#issuecomment-439554347 not help.

**Comment by karimnosseir** [comment] 2019-02-08 00:13
Can you please follow the updated instructions here 
https://www.tensorflow.org/lite/demo_ios
and let me know if it is not working.

Thanks

**Comment by McWare** [comment] 2019-02-16 19:28
Sorry folks it is still not working.. somethings seams to be wrong with the paths to the framework.
![screen shot 2019-02-16 at 20 27 59](https://user-images.githubusercontent.com/16985927/52904227-5e616580-3229-11e9-8ea7-50090afc8d3f.png)

**Comment by karimnosseir** [comment] 2019-02-17 06:12
We are sorry for the breakage.
Will be sending a fix. You can fix it manually by removing the prefix  "third_party/".

Thanks and sorry for the breakage.

**Comment by McWare** [comment] 2019-02-17 16:53
Thx! I found out meanwhile🤗

Von meinem iPhone gesendet

**Comment by karimnosseir** [comment] 2019-03-01 17:52
Fix submitted already. closing the bug.
Please file new /reopen if you have any problems/questions.

Thanks

**Closed by karimnosseir** 2019-03-01 17:52 UTC
Labels: comp:lite
