### ISSUE TITLE
Error when using the class_weight parameter in the fit function in tensorflow.python.keras

### ISSUE THREAD

**Issue by imarkiew** [tensorflow/tensorflow#26714] opened 2019-03-14 21:12 UTC
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow version: 1.13.1
- Python version: 3.6

I wanted to test my network on a small set of records with two imbalanced classes (0 and 1). I was going to use the _class_weight_ parameter in the _fit_ function to improve the balance, but unfortunately there were problems probably associated with tensor support. Without the _class_weight_ parameter, the fit function works correctly. I also tried to use tensorflow.python.keras.layers.Input as an input to the Xception model, but with the same effect.

```
import tensorflow as tf
from tensorflow.python.keras.layers import Dense, Dropout
from tensorflow.python.keras.applications.xception import Xception, preprocess_input
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.optimizers import Adam

# parsing images and labels from TFRecords
def parse_function(proto):
    example = {'image_raw': tf.FixedLenFeature([], tf.string), 'label': tf.FixedLenFeature([], tf.int64)}
    parsed_example = tf.parse_single_example(proto, example)
    image = tf.decode_raw(parsed_example['image_raw'], tf.uint8)
    image = tf.reshape(image, [HEIGHT, WIDTH, DEPTH])
    image = preprocess_input(tf.cast(image, tf.float32))
    return image, parsed_example['label']

def get_data(filepath, schuffle_size=32, batch_size=8, prefetch=1, repeat=None, num_parallel_calls=1):
    dataset = tf.data.TFRecordDataset(filepath)
    if schuffle_size != 0:
        dataset = dataset.shuffle(schuffle_size)
    dataset = dataset.repeat(repeat)
    dataset = dataset.map(parse_function, num_parallel_calls=num_parallel_calls)
    dataset = dataset.batch(batch_size)
    dataset = dataset.prefetch(prefetch)
    iterator = dataset.make_one_shot_iterator()
    return iterator

def build_model(number_of_neurons_in_dense_layer, dropout, learning_rate):
    base_model = Xception(weights='imagenet', include_top=False, pooling='avg', input_shape=(HEIGHT, WIDTH, 3))
    for layer in base_model.layers:
        layer.trainable = True
    x = base_model.output
    x = Dropout(dropout)(x)
    x = Dense(number_of_neurons_in_dense_layer, activation='relu')(x)
    x = Dropout(dropout)(x)
    logits = Dense(NUMBER_OF_CLASSES, activation='softmax')(x)
    model = Model(inputs=base_model.input, outputs=logits)
    model.compile(optimizer=Adam(lr=learning_rate), loss='sparse_categorical_crossentropy', metrics=['categorical_accuracy'])
    return model

global NUMBER_OF_CLASSES, HEIGHT, WIDTH, DEPTH
NUMBER_OF_CLASSES = 2
...
CLASS_WEIGHTS = {
        0: 1,
        1: 7
       }
model = build_model(64, 0.4, 0.001)
train = get_data(..., 8, 2, num_parallel_calls=8)
val = get_data(...., 0, 4, num_parallel_calls=8)
model.fit(train, validation_data=val, epochs=3,steps_per_epoch=8//2,
           validation_steps=8//4, shuffle=False, 
           class_weight=CLASS_WEIGHTS)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'Tensor' object has no attribute 'reshape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./model.py", line 137, in main
    model.fit(train, validation_data=val, epochs=3, steps_per_epoch=8 // 2, validation_steps=8 // 4, shuffle=False, class_weight=CLASS_WEIGHTS)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 776, in fit
    shuffle=shuffle)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2432, in _standardize_user_data
    feed_sample_weight_modes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2431, in <listcomp>
    for (ref, sw, cw, mode) in zip(y, sample_weights, class_weights,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_utils.py", line 758, in standardize_weights
    y_classes = np.reshape(y, y.shape[0])
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 41, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: __index__ returned non-int (type NoneType)
```

**Comment by dd1923** [comment] 2019-05-10 19:57
@jvishnuvardhan any updates?

**Comment by dd1923** [comment] 2019-05-10 22:31
@imarkiew This looks like due to the fact that code in training_utils.py of tf.keras is still wrongly assuming input data to be numpy arrays. Try enabling eager execution. It goes away for me if I do that but then it also uncovers other bugs.

**Comment by imarkiew** [comment] 2019-05-11 10:04
@dd1923 Honestly, I changed my approach some time ago and completely switched to Kerasa (so I don't use TFRecords and Datset API). But I also think that there is something broken underneath between the Tensors and numpy arrays.

**Comment by jvishnuvardhan** [comment] 2019-10-29 16:08
@imarkiew @dd1923 There were lots of improvements over the last two releases. Can you please check with `TF2.0` or `tf-nightly` and let us know whether the issue persists in the newer TF versions. Please provide a standalone code reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-11-08 16:34
@imarkiew Is this still an issue? If it not, please close the issue. Thanks!

**Comment by imarkiew** [comment] 2019-11-09 15:32
@jvishnuvardhan I tested this for `2.0.0b1` version and it still seems that the problem exists (but with another error). Unfortunately, due to some problems I wasn't able to test `tf-nightly`.

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2326, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'dropout_1/cond' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 344, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2330, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'dropout_1/cond' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'dropout_shape_dense_identity' expects to be colocated with unknown node 'dropout_1/cond'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model.fit(train, validation_data=val, epochs=3, steps_per_epoch=8//2, validation_steps=8//4, class_weight=CLASS_WEIGHTS, shuffle=False)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 694, in fit
    steps_name='steps_per_epoch')
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 917, in train_on_batch
    self._make_train_function()
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1974, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 476, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 91, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3568, in gradients
    loss, variables, colocate_gradients_with_ops=True)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 677, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 349, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 677, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2.py", line 100, in _IfGrad
    true_graph, false_graph = _get_func_graphs(if_op)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2.py", line 268, in _get_func_graphs
    return (_get_func_graph_for_branch(op.get_attr("then_branch")),
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2.py", line 258, in _get_func_graph_for_branch
    fdef, input_shapes)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 62, in function_def_to_graph
    importer.import_graph_def(graph_def, name="")
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/PycharmProjects/TfRecordsTestV2/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Node 'dropout_shape_dense_identity' expects to be colocated with unknown node 'dropout_1/cond'
```

**Comment by jvishnuvardhan** [comment] 2019-11-11 17:04
@imarkiew Can you please try `TF2.0` or create a simple standalone code to reproduce the issue. Thanks!

**Comment by imarkiew** [comment] 2019-11-12 15:53
@jvishnuvardhan It seems that the change form `2.0.0b1` to `2.0.0` has helped. I don't see this issue anymore.

**Comment by jvishnuvardhan** [comment] 2019-11-12 18:23
@imarkiew Thanks for the confirmation. We will close this issue as it was resolved. Thanks!

**Closed by jvishnuvardhan** 2019-11-12 18:23 UTC
Labels: TF 1.13, comp:keras, stat:awaiting response, type:bug
