### ISSUE TITLE
Unable to execute example: models/image/mnist/convolutional.py on MacOS

### ISSUE THREAD

**Issue by bbnstsai** [tensorflow/tensorflow#1319] opened 2016-02-27 20:47 UTC
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System: Mac OS (El Capitan / Python 2.7)

If installed from binary pip package, provide:

1. Which pip package you installed.
Virtualenv
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.7.1

If installed from sources, provide the commit hash:

### Steps to reproduce
1. python /Users/foo/tensorflow/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py

### Logs or other output that would be helpful
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "/Users/yuntatsai/tensorflow/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 316, in <module>
    tf.app.run()
  File "/Users/yuntatsai/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/yuntatsai/tensorflow/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 128, in main
    train_data = extract_data(train_data_filename, 60000)
  File "/Users/yuntatsai/tensorflow/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 75, in extract_data
    buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x381c74b0 != 0x805e6c18L

**Comment by kristoffernolgren** [comment] 2016-02-28 07:40
I also get this error trying to run 

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

from the tutorial.

**Comment by waterofphysics** [comment] 2016-03-16 13:25
At first, I have met the same error, after 
```
$ rm -r models/image/mnist/data
```
and execute `convolutional.py` again, everything works well.

**Comment by Xiaoming-Zhao** [comment] 2016-06-05 09:20
Hi, I met the same problem as you. 

I found that the error might be caused by the dataset downloading. After changing the line 37 `WORK_DIRECTORY` in `tensorflow/tensorflow/models/image/mnist/convolutional.py` to my own directory, everything worked fine when re-running the `convolutional.py` code.

I hope this will help you.

**Comment by girving** [comment] 2016-06-06 21:39
@ebrevdo: Could you take a look or reassign?  I'm not sure if there's a problem we can fix here or not.

**Comment by ebrevdo** [comment] 2016-06-08 06:03
Sounds like a bad download. We can auto retry the download, or catch the error and ask the user to delete the gzipped files before rerunning. Not sure who wrote the original mnist fetching code.

**Comment by girving** [comment] 2016-06-08 15:50
@ebrevdo: I don't think we should do too much work if the issue is a server outside of our control.  PRs welcome if someone wants to make this more robust: if so please comment and I can reopen the issue.

**Closed by girving** 2016-06-08 15:50 UTC
Labels: triaged

**Comment by shamitlal** [comment] 2017-01-24 17:56
@kristoffernolgren I got the same error too. Everything worked well when I mentioned the complete directory in read_data_sets command.
