### ISSUE TITLE
how to do prediction after quantizing model

### ISSUE THREAD

**Issue by smartcatdog** [tensorflow/tensorflow#31255] opened 2019-08-02 02:39 UTC
while i transformer ckpt to pb model by freeze and quantize model to compression_pb_model,  and then serve the compression_pb_model occuring the errors like this:

ValueError: NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]>; NodeDef: {{node bert/embeddings/GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, batch_dims=0](bert/embeddings/word_embeddings/read, bert/embeddings/Reshape, zeros/Const). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

however, i run the code in the same meachine,,,thx,,,

**Comment by gadagashwini** [comment] 2019-08-06 06:48
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-08-16 08:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-16 08:24 UTC
Labels: comp:model, stat:awaiting response, type:support

**Comment by smartcatdog** [comment] 2019-09-19 14:52
> while i transformer ckpt to pb model by freeze and quantize model to compression_pb_model, and then serve the compression_pb_model occuring the errors like this:
> 
> ValueError: NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]>; NodeDef: {{node bert/embeddings/GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, batch_dims=0](bert/embeddings/word_embeddings/read, bert/embeddings/Reshape, zeros/Const). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 
> however, i run the code in the same meachine,,,thx,,,

i find why the errors, sorry for reply delaying.
i compile tensorflow from the source code, however, i compress model on the server which tensorflow version is 1.14 while i serve compressed_model on 1.13....

**Comment by smartcatdog** [comment] 2019-09-19 14:53
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

i find why the errors, sorry for reply delaying.
i compile tensorflow from the source code, however, i compress model on the server which tensorflow version is 1.14 while i serve compressed_model on 1.13....
