### ISSUE TITLE
Handling output labels of mobilenet model tf lite version in android.

### ISSUE THREAD

**Issue by prateekswamy** [tensorflow/tensorflow#28262] opened 2019-04-29 13:11 UTC
can we handle the predicted label of Mobilenet model on android side to improve accuracy ?

if an image does not contain an object in the label list i.e 1000 classes, then can we show a null output so that user will not be getting wrong labels?

**Comment by muddham** [comment] 2019-04-30 11:36
@prateekswamy This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-05-08 06:30
@prateekswamy Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-08 06:30 UTC
Labels: comp:lite, comp:model, stat:awaiting response, type:support
