### ISSUE TITLE
Error in Android Example

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [tensorflow/tensorflow#31521] opened 2019-08-11 15:55 UTC
Hello,

I want to tell that I am using source code which I got from tensorflow.com/lite website. Now I am frustrated to solve this error. Please see screenshot and let me know. how to fix it and use this. When I start the app then it takes seconds to take to crash my app.

![Screenshot (10)](https://user-images.githubusercontent.com/39325207/62836209-78cb4780-bc7e-11e9-9a8d-2bd625c9dd41.png)
![Screenshot (11)](https://user-images.githubusercontent.com/39325207/62836210-7963de00-bc7e-11e9-94d6-8fa373f1fcb0.png)
![Screenshot (12)](https://user-images.githubusercontent.com/39325207/62836211-7963de00-bc7e-11e9-9502-74f18d87622c.png)

**Comment by oanush** [comment] 2019-08-13 07:15
@KanwarpartapSinghBimrah ,

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here in accessible format. Thanks

**Comment by KanwarpartapSinghBimrah** [comment] 2019-08-13 10:20
@oanush Now it's working fine and I fix all the errors. if in future I need help I let you know.

**Comment by oanush** [comment] 2019-08-13 10:30
Thank you for the feedback.Closing since the issue is resolved.

**Closed by oanush** 2019-08-13 10:30 UTC
Labels: comp:lite, type:support
