### ISSUE TITLE
Reducing the binary size of tflite library for android

### ISSUE THREAD

**Issue by holyhao** [tensorflow/tensorflow#25278] opened 2019-01-29 08:57 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: all
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.10
- Python version:.3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):1.15
- GCC/Compiler version (if compiling from source):5.4
- CUDA/cuDNN version:8.0
- GPU model and memory:16GB

I build the libtensorflowLite.so following the https://github.com/tensorflow/tensorflow/issues/19642#issuecomment-422697028, and i can use it in the android project . But the .so of the  libtensorflowLite.so is about 3.7M. From the document ,it should be hundreds of KB.
Here is my build commit:
```
bazel build -c opt //tensorflow/contrib/lite:libtensorflowLite.so 
 --crosstool_top=//external:android/crosstool 
 --cpu=arm64-v8a
 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
 --cxxopt="-std=c++11" 
 --verbose_failures

```
So, could someone helps me, how can I reduce the size of tflite library?

**Comment by ANSHUMAN87** [comment] 2019-02-01 05:16
libtensorflowLite.so memory size significantly contributed by the Kernels for various operators, the simplest way to reduce the size is to remove unnecessary ops kernels from compiling into the lib, which are not required for your model. So you can just compile libtensorflowLite.so with the required OPs for your model only.

Also suggest if it is not mandatory, try to use latest tensorflow version, in that way you can get benefit of recent tools/customization added into it.

**Comment by holyhao** [comment] 2019-02-01 07:38
@ANSHUMAN87 Tanks for reply. I just want keep all the ops as a platform . May the configuration and compile setting can help reduce the size.? I think 3.7M is too big even with all the ops. Do you have some ideas. Looking forward to your reply.

**Comment by jdduke** [comment] 2019-02-04 21:04
Hi @holyhao, I'm landing a change which adds a proper C++ shared library target for TensorFlow Lite (tensorflow/lite:libtensorflowlite.so). The (Android) binary size for arm should be ~1MB, and arm64 ~1.5MB (this includes the full set of builtin ops). You likely won't be able to get much smaller than that unless you use selective op registration as noted by @ANSHUMAN87.

**Comment by jdduke** [comment] 2019-02-04 21:06
The main reason you're seeing a much larger binary size is that the suggested build target you referenced includes *all* symbols in the shared library, not just the symbols that are part of the public C/C++ API. Please follow issue #20905 for further updates.

**Comment by jdduke** [comment] 2019-02-04 21:07
Duplicate of #20905

**Closed by jdduke** 2019-02-04 21:07 UTC
Labels: comp:lite

**Comment by lenaevans** [comment] 2019-05-30 00:40
@ANSHUMAN87 Is there documentation on how to do the selective registration? The tflite documentation points to a script that says it has been deprecated.

**Comment by ANSHUMAN87** [comment] 2019-05-30 07:50
@lenaevans : You can follow steps mentioned in #20905. Now the size has reduced much.

**Comment by laohur** [comment] 2019-09-09 14:16
>



> 
> 
> Hi @holyhao, I'm landing a change which adds a proper C++ shared library target for TensorFlow Lite (tensorflow/lite:libtensorflowlite.so). The (Android) binary size for arm should be ~1MB, and arm64 ~1.5MB (this includes the full set of builtin ops). You likely won't be able to get much smaller than that unless you use selective op registration as noted by @ANSHUMAN87.

build cmd

>   bazel build --config monolithic --config=android_arm64 --cxxopt=-std=c++11 -c opt  \
  --crosstool_top=//external:android/crosstool \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
 --cpu=arm64-v8a --verbose_failures \
  //tensorflow/lite/examples/l17:libProphet.so

get ~3.6m , 2.8m after strip ops。
 what‘s wrong with me ?

**Comment by jdduke** [comment] 2019-09-09 15:24
What other dependencies/code do you have in `libProphet.so`?

**Comment by laohur** [comment] 2019-09-10 02:44
> 
> 
> What other dependencies/code do you have in `libProphet.so`?

> cc_binary(
    name = "libProphet.so",
    srcs = [
        "Prophet.cc",
        "Prophet.h",
    ],
    copts = tflite_copts(),
    defines = [
        "TFLITE_CUSTOM_OPS_HEADER",
        "TFLITE_WITH_RUY",
    ],
    linkopts = tflite_linkopts() + select({
        "//tensorflow:android": [
            "-pie",  # Android 5.0 and later supports only PIE
            "-lm",  # some builtin ops, e.g., tanh, need -lm
        ],
        #        "//conditions:default": [],
    }),
    linkshared = True,
    deps = [
        #        ":custom_ops",
        "//tensorflow/lite:framework",
        #        "//tensorflow/lite/c:c_api_internal",
        "//tensorflow/lite/kernels:builtin_ops",
        #        "//tensorflow/lite/kernels:builtin_op_kernels",
        #        "//tensorflow/lite:builtin_op_data",
        #        "//tensorflow/lite/schema:schema_fbs",
        #        "//tensorflow/lite:util",
    ],
)

**Comment by jdduke** [comment] 2019-09-13 18:15
Which NDK version are you using?
