### ISSUE TITLE
Choosing the right Bazel version to build TF is confusing

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#24101] opened 2018-12-02 01:39 UTC
This bug was closed while the problem still exists: https://github.com/tensorflow/tensorflow/issues/21362

**Comment by ker2x** [comment] 2018-12-19 15:42
i have the problem while following this : https://www.tensorflow.org/install/source#docker_linux_builds to build the docker image

**Comment by Surmeh** [comment] 2018-12-21 13:46
I still get the issue with version 1.12 with tensorflow/configure.py

**Comment by VishvajeetRamanuj** [comment] 2018-12-25 02:46
I have same issue too. exact error shown in pc is 
root@0d56190c7f6e:/tensorflow# ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0 installed.
Please upgrade your bazel installation to version 0.19.0 or higher to build TensorFlow!

even if i have latest bazel  version 0.21.0

**Comment by abditag2** [comment] 2019-01-18 21:16
I have the same exact error. The official build guide shows 1.15 as the tested version though. 
https://www.tensorflow.org/install/source

**Comment by Anton-Velikodnyy** [comment] 2019-01-29 19:54
The reason I installed 0.15 bazel is because of the above comment.

**Comment by xingjinglu** [comment] 2019-03-14 14:26
@dveselov It does work with tf 1.12.0 when upgrade bazel to 0.21.0

**Comment by abe1ge** [comment] 2019-03-15 15:48
I get the following error, can anyone help me, I believe that it is related to this issue. When configuring bazel I get the following error.

```
root@636420111df0:/tensorflow# ./configure
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.23.2 installed.
Please downgrade your bazel installation to version 0.21.0 or lower to build TensorFlow!
```

Using tf 1.13 with bazel 0.23.2. 

Am I better off down grading tf or bazel, I can't seem to find any instructions to install a different version of bazel

**Comment by yurivict** [comment] 2019-03-15 16:22
```cmake``` does't seem to have such problems. Why not just use cmake instead?

**Comment by angersson** [comment] 2019-03-15 21:14
@lamberta "What version of Bazel do I install to build TF" seems to be a common problem, and a static doc may be unreliable because the recommended version is likely to change as changes are made to master. Our best reference for any branch is always the [configure script](https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1624). Do you think it would be best to link straight to that from the build docs, or something like that?

Unfortunately, it looks like this issue has migrated from its original intent (to ask about the `--batch` warning). Since that's just a warning and the issue has changed topic, I'll adjust the title. If anyone still experiences issues with `--batch` mode, please create another issue.

**Comment by the7threvival** [comment] 2019-05-31 13:30
So, there is not solution to this?

**Comment by mihaimaruseac** [comment] 2019-05-31 14:59
If the issue is that `bazel ...` prints
```
WARNING: --batch-mode is deprecated...
```

that's something caused by Bazel, not TensorFlow (also, it's just a warning, nothing breaks, can be safely ignored).

---

If the issue is that every version of TensorFlow can only build with some specific Bazel versions, then running `./configure` before doing any compile will check if you have a Bazel that is supported. Afaik, there is no bug in the logic there, but if there's an issue, please open one and tag me.

---

Upgrading/downgrading `bazel` is just a matter of running the following commands

```bash
$ BAZEL_VERSION="0.26.0"     # insert your desired version here, for example 0.26.0
$ wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh   # if not on x86_64, change that too
$ chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh   # or the file you just downloaded
$ ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
$ bazel version   # this should now print the same as BAZEL_VERSION
```

I think this issue diverged too much, so I propose we close it and open new issues for individual components, if needed.

**Comment by the7threvival** [comment] 2019-05-31 15:29
My issue was that the TF guide was telling me to use bazel 0.23.0 or lower but Bazel was telling me to upgrade to 0.24.1 to use it. In the end, I just upgraded and it worked.

**Closed** 2019-05-31 22:36 UTC
Labels: type:build/install, type:docs

**Comment by fisakhan** [comment] 2020-08-18 11:50
Please downgrade your bazel installation to version x.x.x or lower to build TensorFlow! Even if you follow the version compatibility at https://www.tensorflow.org/install/source#cpu-only_2

Please downgrade your bazel installation to version 0.0.0 and still it doesn't work.
