### ISSUE TITLE
Tensorflow 2.1.0 2.1.0-rc0 2.1.0-rc2 causes SIGSEGV when is used with textgenrnn

### ISSUE THREAD

**Issue by sjurajpuchky** [tensorflow/tensorflow#36937] opened 2020-02-20 18:10 UTC
Hi All,

I have a problem when I build TensorFlow 2.1.0 2.1.0-rc0 2.1.0-rc2 from sources on CentOS 7
build is successfully compiled without any problems but when trying to learn from a text file with textgenrnn package
it causes SIGSEGV error, you can see the log from gdb same on mentioned versions

```
Missing separate debuginfos, use: debuginfo-install python3-3.6.8-10.el7.x86_64
(gdb) run ./train-sources.py -k půjčky-limited
Starting program: /usr/bin/python3 ./train-sources.py -k půjčky-limited
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffecf3f700 (LWP 27545)]
[New Thread 0x7fffec73e700 (LWP 27546)]
[New Thread 0x7fffe9f3d700 (LWP 27547)]
warning: File "/usr/lib64/libstdc++.so.6.0.27-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib64/libstdc++.so.6.0.27-gdb.py
line to your configuration file "/home/jpuchky/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/jpuchky/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
[Thread 0x7fffec73e700 (LWP 27546) exited]
[Thread 0x7fffe9f3d700 (LWP 27547) exited]
[Thread 0x7fffecf3f700 (LWP 27545) exited]
Detaching after fork from child process 27777.
Detaching after fork from child process 27779.
[New Thread 0x7fffe9f3d700 (LWP 27893)]
[New Thread 0x7fffec73e700 (LWP 27894)]
[New Thread 0x7fffecf3f700 (LWP 27895)]
[New Thread 0x7fffb95aa700 (LWP 27896)]
[New Thread 0x7fffb8da9700 (LWP 27897)]
[New Thread 0x7fffa3fff700 (LWP 27898)]
[New Thread 0x7fffa37fe700 (LWP 27899)]
[New Thread 0x7fffa2ffd700 (LWP 27900)]
2020-02-20 19:06:27.583250: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594220000 Hz
[Thread 0x7fffa37fe700 (LWP 27899) exited]
[New Thread 0x7fffa37fe700 (LWP 27901)]
[New Thread 0x7fffa27fc700 (LWP 27902)]
[New Thread 0x7fffa1ffb700 (LWP 27903)]
[New Thread 0x7fffa17fa700 (LWP 27904)]
2020-02-20 19:06:27.588578: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x34fe630 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-20 19:06:27.588620: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[New Thread 0x7fffa0ff9700 (LWP 27905)]
[New Thread 0x7fff83fff700 (LWP 27906)]
[New Thread 0x7fff837fe700 (LWP 27907)]
[New Thread 0x7fff82ffd700 (LWP 27908)]
[New Thread 0x7fff827fc700 (LWP 27909)]

Program received signal SIGSEGV, Segmentation fault.
---Type <return> to continue, or q <return> to quit---
[Switching to Thread 0x7fffb8da9700 (LWP 27897)]
0x00007fffd8967b20 in Eigen::internal::TensorBlockIOV2<unsigned int, long, 2, 1>::Copy(Eigen::internal::TensorBlockIOV2<unsigned int, long, 2, 1>::Dst const&, Eigen::internal::TensorBlockIOV2<unsigned int, long, 2, 1>::Src const&, Eigen::DSizes<int, 2> const&) ()
   from /usr/local/lib64/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
(gdb) 
```

**Comment by amahendrakar** [comment] 2020-02-24 08:47
@sjurajpuchky,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by sjurajpuchky** [comment] 2020-02-24 09:00
@amahendrakar 
`#!/usr/bin/python3

from textgenrnn import textgenrnn
import sys
import getopt
import os


def usage():
    print('train-sources.py -k <keyword>')


# noinspection SpellCheckingInspection
def main(argv):
    keyword = ''
    epochs = 10
    try:
        opts, args = getopt.getopt(argv, "hk:e:", ["keyword=", "epochs="])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            usage()
            sys.exit()
        elif opt in ("-k", "--keyword"):
            keyword = arg
        elif opt in ("-e", "--epochs"):
            epochs = arg

    srcfile = os.path.dirname(os.path.realpath(__file__)) + '/sources/' + keyword + '.txt'
    wfile = os.path.dirname(os.path.realpath(__file__)) + '/weights/' + keyword + '.hdf5'
    textgen = textgenrnn(weights_path=wfile)
    textgen.train_from_file(srcfile, new_model=True, num_epochs=int(epochs))
    textgen.save()


if __name__ == "__main__":
    main(sys.argv[1:])
`
srcfile is plain text file

**Comment by sjurajpuchky** [comment] 2020-02-24 09:01
`absl-py (0.9.0)
astor (0.8.1)
cached-property (1.5.1)
cachetools (4.0.0)
certifi (2019.11.28)
chardet (3.0.4)
cycler (0.10.0)
docker (2.6.1)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
docopt (0.6.2)
future (0.18.2)
gast (0.2.2)
google-auth (1.11.2)
google-auth-oauthlib (0.4.1)
google-pasta (0.1.8)
grpcio (1.27.2)
h5py (2.10.0)
idna (2.9)
joblib (0.14.1)
jsonschema (2.5.1)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
kiwisolver (1.1.0)
Markdown (3.2.1)
matplotlib (3.1.3)
mock (4.0.1)
numpy (1.18.1)
oauthlib (3.1.0)
opt-einsum (3.1.0)
pip (9.0.3)
protobuf (3.11.3)
pyasn1 (0.4.8)
pyasn1-modules (0.2.8)
pyparsing (2.4.6)
pypi-install (0.0.5)
PySocks (1.6.8)
python-dateutil (2.8.1)
PyYAML (3.11)
requests (2.23.0)
requests-oauthlib (1.3.0)
rsa (4.0)
scikit-learn (0.22.1)
scipy (1.4.1)
setuptools (45.2.0)
six (1.14.0)
tensorboard (2.0.2)
tensorflow (2.1.0rc0)
tensorflow-estimator (2.0.1)
termcolor (1.1.0)
textgenrnn (2.0.0)
texttable (1.4.0)
tqdm (4.42.1)
urllib3 (1.25.8)
websocket-client (0.47.0)
Werkzeug (1.0.0)
wheel (0.34.2)
wrapt (1.12.0)
youtube-dl (2019.9.28)
`

Thanks a lot

**Comment by sjurajpuchky** [comment] 2020-02-24 09:03
System
`Linux localhost.localdomain 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
CentOS 7

**Comment by amahendrakar** [comment] 2020-02-29 09:45
@sjurajpuchky,
I was unable to reproduce the issue due to the missing .hdf5 file. You can take a look at the gist [here](https://colab.sandbox.google.com/gist/amahendrakar/0fe49e16e5bbd1de283b7cd98cb9cf3c/36937.ipynb). Could you please provide all the supporting files needed to run your code.

Also, please add ``` before and after your code to preserve the indentation of the code. Thanks!

**Comment by sjurajpuchky** [comment] 2020-02-29 21:41
You have to install which contains all required files
I do not have hdf5 file I train network from text file
also have to mention that my version of tensorflow is 2.1.0-rc2 builded from source on centos 7.1
what i suggest is common problem 

see attached WHL file which is my build

[](https://www.baba.bj/tensorflow-2.1.0rc2-cp36-cp36m-linux_x86_64.whl)

`#!/usr/bin/python3

from textgenrnn import textgenrnn
import sys
import getopt
import os


def usage():
    print('train-sources.py -k <keyword>')


# noinspection SpellCheckingInspection
def main(argv):
    keyword = ''
    epochs = 10
    try:
        opts, args = getopt.getopt(argv, "hk:e:", ["keyword=", "epochs="])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            usage()
            sys.exit()
        elif opt in ("-k", "--keyword"):
            keyword = arg
        elif opt in ("-e", "--epochs"):
            epochs = arg

    srcfile = os.path.dirname(os.path.realpath(__file__)) + '/sources/' + keyword + '.txt'
    wfile = os.path.dirname(os.path.realpath(__file__)) + '/weights/' + keyword + '.hdf5'
    textgen = textgenrnn(weights_path=wfile)
    textgen.train_from_file(srcfile, new_model=True, num_epochs=int(epochs))
    textgen.save()


if __name__ == "__main__":
    main(sys.argv[1:])
`
`
Name: textgenrnn
Version: 2.0.0
Summary: Easily train your own text-generating neural network of any size and complexity
Home-page: https://github.com/minimaxir/textgenrnn
Author: Max Woolf
Author-email: max@minimaxir.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages/textgenrnn-2.0.0-py3.6.egg
Requires: h5py, scikit-learn, tqdm, tensorflow
Metadata-Version: 2.1
Installer: 
Classifiers:
Entry-points:
`

**Comment by mihaimaruseac** [comment] 2020-03-02 16:51
@sjurajpuchky Please add ` ``` ` before and after your code blocks. Otherwise, the things you post are unreadable and if you don't invest some time into the issue to make it easier to understand other contributors will just move over the issue and look at other ones.

**Comment by sjurajpuchky** [comment] 2020-03-04 16:23
@mihaimaruseac I have fixed it but it's not working properly

**Comment by mihaimaruseac** [comment] 2020-03-05 16:53
It's 3 backticks, not two

**Comment by mihaimaruseac** [comment] 2020-03-05 16:55
Can you check if the two packages (TF and textgenrnn) are built using the same toolchains?

**Comment by amahendrakar** [comment] 2020-03-06 12:43
@sjurajpuchky,
I was able to run the above code without any issues using TF-nightly. Please find the output attached to this message.
![36937 output](https://user-images.githubusercontent.com/57165142/76084435-e56cb180-5fd5-11ea-8817-b515f7b4fb88.png)


I had used the sample `hacker_news.hdf5` and `hacker_news_2000.txt` files given in the [documentation](https://github.com/minimaxir/textgenrnn) of textgenrnn as the input. Thanks!

[36937 full_output.txt](https://github.com/tensorflow/tensorflow/files/4298364/36937.full_output.txt)

**Comment by sjurajpuchky** [comment] 2020-03-06 20:32
Thanks a lot i will try tommorow

**Comment by sjurajpuchky** [comment] 2020-03-09 20:15
Its working with version r2.2 build on CentOS 7 Python 3.6
Thanks a lot

**Comment by amahendrakar** [comment] 2020-03-11 14:37
Happy to help @sjurajpuchky. Closing this issue as resolved.

**Closed by amahendrakar** 2020-03-11 14:37 UTC
Labels: TF 2.1, type:support
