### ISSUE TITLE
Android Demo DetectorActivity landscape orientation problem

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#9412] opened 2017-04-24 10:27 UTC
I'm trying to change the orientation to landscape:

`private static final Size DESIRED_PREVIEW_SIZE = new Size(1280, 720);`
`private static final boolean USE_YOLO = true`

```
        <activity android:name="org.tensorflow.demo.DetectorActivity"
                  android:screenOrientation="landscape"
                  android:label="@string/activity_name_detection">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

But it draws detected rects wrongly.
How to fix it?

**Comment by jubjamie** [comment] 2017-04-24 13:29
By any chance are you referring to the fact that it draws them correctly in the debug preview but off to the side and squished in the main view?

**Comment by anonym24** [comment] 2017-04-24 14:24
Actually in debug there also nothing.
And in the main view we can see false (train) detected object

portrait 
![portrait](https://cloud.githubusercontent.com/assets/8851301/25341785/add555bc-2912-11e7-8f06-5a508ca782ff.png)

landscape
![landscape](https://cloud.githubusercontent.com/assets/8851301/25341789/b13bdf0a-2912-11e7-988a-c4503406d60a.png)

**Comment by jubjamie** [comment] 2017-04-24 14:31
If you look at the preview screen bottom right you will see that your input is coming through on it's side. That debug preview screen is what goes through the model. As it is on it's side the model will not preform as expected. That's why in landscape you're getting nonsense predictions. Almost all image recognition problems are **NOT** rotation invariant.

On another note, you'll notice that the blue train box is being drawn on a part of the image that isn't in the preview that goes through the model. That's because the rectangle drawing functions don't work correctly when the app is changed to landscape. I am also struggling with this issue and hope @andrewharp is able to comment on that particular issue. (Probably not a bug but rather me being too rubbish at understanding the source code),

**Comment by anonym24** [comment] 2017-04-24 17:00
I tried this:

```
public class DetectorActivity extends CameraActivity implements OnImageAvailableListener {
 
 ...
 
 @Override
  public void onPreviewSizeChosen(final Size size, final int rotation) {
    
	...
	
    sensorOrientation = screenOrientation;
    //sensorOrientation = rotation + screenOrientation;
```

So debug preview looks fine now 

So now it's only main view.
I'm not sure where to look, but I guess it mb here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java#L205

**Comment by jubjamie** [comment] 2017-04-24 17:04
Yes that is the way to force the rotation. I also found problems with the rotation. I guess this is kind of linked with #9416 that @andrewharp has been assisting with.

Regarding the boxes on the main view, it is on my todo list to try and figure out but will be a few weeks away if anyone else has any ideas?

**Comment by anonym24** [comment] 2017-04-29 21:17
I tried to force rotation in the different part of code.
Rects on the main view looks better now (I guess it shows normal width/height now of every detected car),
but they are still at the wrong position..

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L297
```
rgbFrameBitmap.setPixels(rgbBytes, 0, previewWidth, 0, 0, previewWidth, previewHeight);
    final Canvas canvas = new Canvas(croppedBitmap);
    canvas.drawBitmap(rgbFrameBitmap, frameToCropTransform, null);
    croppedBitmap = rotateBitmap(croppedBitmap, -90); // here forced rotation
```

```
public static Bitmap rotateBitmap(Bitmap source, float angle) {
    Matrix matrix = new Matrix();
    matrix.postRotate(angle);
    return Bitmap.createBitmap(source, 0, 0, source.getWidth(), source.getHeight(), matrix, true);
  }
```
![screenshot_2017-04-30-00-01-16-782_org tensorflow demo](https://cloud.githubusercontent.com/assets/8851301/25558969/4dc2dfec-2d3a-11e7-8f00-2349713fefa0.png)

**Comment by solix** [comment] 2017-07-27 21:16
I am also struggling with landscape mode for drawing correct rectangles around images. Debug looks totally valid only preview side is remaining. any progress on this?

**Comment by bobeo** [comment] 2017-09-29 08:27
I have the same issue. Any luck till recently?

**Comment by nanamare** [comment] 2017-11-02 05:27
I solved this problem.

**Comment by bobeo** [comment] 2017-11-02 05:34
@nanamare can you tell us how you solved the issue?

**Comment by andrewharp** [comment] 2017-11-02 05:38
@nanamare We'd love to have this as a contribution, if you'd be up for submitting a pull request!

**Comment by anonym24** [comment] 2017-11-02 17:37
@nanamare great, if the problem was related to `List<Recognition> recognizeImage(final Bitmap bitmap)` method (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java#L134)

then maybe you understand code pretty well and could also help with Yolo detector in Java for Windows/Ubuntu

I already made a project in IntelliJ IDEA, I posted a result and full java classes from the project in my question https://stackoverflow.com/questions/47077983/yolo-detector-in-java
I got some negative votes, but I don't care:)

I'm just doing this for fun, it's just cool that we can run Tensorflow just everywhere and using different programming frameworks, languages, devices
and Java is powerful - works on Windows/Ubuntu/Mac

**Comment by andrewharp** [comment] 2017-11-02 23:35
I've made a fix for this internally, should show up in the next push. You'll still have to manually change the orientation of the Activity in AndroidManifest, but everything else should just work afterwards.

**Closed** 2017-11-04 02:39 UTC
Labels: stat:contributions welcome

**Comment by bobeo** [comment] 2017-11-04 07:21
@gunan @andrewharp will this work with screenOrientation="sensor" or screenOrientation="fullSensor"?

Thanks.

**Comment by anonym24** [comment] 2017-12-04 12:15
I downloaded latest android example and set `android:screenOrientation="landscape"`

debug is ok, but still something wrong with main window and it's position:

![1](https://user-images.githubusercontent.com/8851301/33552419-7cb0f784-d8fd-11e7-99d3-fd1d8e7a5cc5.png)


p.s. I fixed java project (windows/ubuntu) for tensorflow yolo2/tiny yolo detector:  https://stackoverflow.com/a/47632412/7767664

**Comment by mfp305629415** [comment] 2018-01-09 09:45
Have you solved it, please?

**Comment by annaisabel93** [comment] 2018-03-16 11:18
@andrewharp I changed the orientation but it stays just as @anonym24 described... Any idea on how to fix this?

**Comment by prasanna532** [comment] 2018-08-14 09:29
I am having some issue camera is opening only 70% to the screen Remaining 30% of the screen is black. Any suggestion or solution how to fix that?

**Comment by Shruti-Mahajan** [comment] 2018-11-15 13:13
Hi 

I have integrated tensor flow with YOLO in android. and I want to detect the objects in landscape and I also want camera preview in full screen.  
If I change the camera preview size. Object detection not working. Please help me. 

I have changed to support in landscape mode by changing 
 sensorOrientation = screenOrientation;

Change the camera preview size by adding 
private static Size DESIRED_PREVIEW_SIZE = new Size(1280, 720);
and I have commented that method  chooseOptimalSize() to show camera in full screen.


Please help me to show the preview of a camera in full screen and also support for a landscape to detect the objects

Thanks 
Shruti

**Comment by prasanna532** [comment] 2018-11-16 05:36
@Shruti-Mahajan 
change your mobile setting to auto rotate they it will detect the objects in any mode.

**Comment by Shruti-Mahajan** [comment] 2018-11-21 07:37
Ok, Thanks

**Comment by Shruti-Mahajan** [comment] 2018-11-21 07:41
Hi 

I want to get the distance of detected objects. Please guide me how to get the distance of detected objects. Actually, I already searched on the internet and I didn't get any idea.
Please help me.

Thanks

Thanks

**Comment by anonym24** [comment] 2018-11-21 07:44
@Shruti-Mahajan you should not ask such questions here, it's not even about TensorFlow at all.

**Comment by MICHAEL-ZENGZF** [comment] 2019-02-19 07:42
Just pulled the latest demo, still cannott change to landscape mode by simply changing the screenOrientation in manifest.xml, and change to auto rotate didn`t work for me @prasanna532 

Here`s my work around:

In DetectorActivity:
`sensorOrientation = 0 - getScreenOrientation();//here change rotation to 0`

In MultiBoxTracker:

    final boolean rotated = sensorOrientation % 180 != 90;//here change == to !=

    frameToCanvasMatrix =
    ImageUtils.getTransformationMatrix(
            frameWidth,
            frameHeight,
            (int) (multiplier * (rotated ? frameHeight : frameWidth)),
            (int) (multiplier * (rotated ? frameWidth : frameHeight)),
            sensorOrientation+90,//here add 90 to degree
            false);


    borderedText.drawText(canvas, trackedPos.left + cornerSize, trackedPos.top, labelString,90);//here draw from top, and modify the drawText function in env/BorderedText

In env/BorderedText:

    //Add a new drawText function
    public void drawText(final Canvas canvas, final float posX, final float posY, final String text, float angle) 
    {
        if(angle != 0){
            canvas.rotate(angle, posX, posY);
        }
        canvas.drawText(text, posX, posY, exteriorPaint);
        canvas.drawText(text, posX, posY, interiorPaint);
        if(angle != 0){
            canvas.rotate(-angle, posX, posY);
        }
        
    }

**Comment by saras-verihelp** [comment] 2019-06-19 12:10
I commented out the portion in set fragment, which is calling the legacy connection fragment. Then landscape mode seems to work without any changes(except in the manifest file) - camera2api being used. (Incase, we want to retain the if..else block and want the legacy fragment to be called, then need to make changes in legacyconnectionfragment.java file corresponding to landscape mode.)

**Comment by erpsindhu** [comment] 2019-06-19 12:18
I commented out the portion in set fragment, which is calling the legacy connection fragment. Then landscape mode seems to work without any changes(except in the manifest file) - camera2api being used. (Incase, we want to retain the if..else block and want the legacy fragment to be called, then need to make changes in legacyconnectionfragment.java file corresponding to landscape mode.)

**Comment by raymondsutjiadi** [comment] 2019-07-10 02:48
I have the same problem with newest example file. Please guide me how to change the screen orientation to landscape.

**Comment by mrprimle** [comment] 2020-12-29 11:17
> I am having some issue camera is opening only 70% to the screen Remaining 30% of the screen is black. Any suggestion or solution on how to fix that?

I've solved the landscape orientation problem thanks to @MICHAEL-ZENZ. However, the issue of 30% black rectangle @prasanna532 at the bottom stayed in both landscape and vertical orientations. Please, need help.

![Screenshot_2020-12-29-13-13-37-219_org tensorflow lite examples detection](https://user-images.githubusercontent.com/30389608/103279965-d9743500-49d7-11eb-8169-fb66b2e2bd6d.png)
