### ISSUE TITLE
Expected dimension in the range [-1, 1), but got 1 [[Node: accuracy_5/ArgMax_1 = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_y_label_0_1, accuracy_5/ArgMax/dimension)]]

### ISSUE THREAD

**Issue by HunarAA** [tensorflow/tensorflow#22148] opened 2018-09-07 16:33 UTC
I am working on luna16 dataset, I use tensorflow CNN code to classify images (cancer/not-cancer [0 or 1]), the code has no problem and runs without any error, but in session when I want to add summary `_, c, summary = sess.run([accuracy, cost, merged_summary], feed_dict={x_img: X, y_label: Y})` I get this error: InvalidArgumentError (see above for traceback): `Expected dimension in the range [-1, 1), but got 1 [[Node: accuracy_5/ArgMax_1 = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_y_label_0_1, accuracy_5/ArgMax/dimension)]]`
if I remove the merged_summary the code is works fine?

**Comment by tensorflowbutler** [comment] 2018-09-08 01:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by HunarAA** [comment] 2018-09-08 05:39
sorry, but where are these fields?

**Comment by apischan** [comment] 2018-09-08 22:36
@HunarAA when you created this issue there was the policy (in the field where you described your issue) where devs asks to specify that information. To ensure you can click "New issue" again and read it.
Also as I see your issue can be not issue at all. In the same policy as I mentioned above the most first sentence is about your case. Such questions you should ask on [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow).
Good luck!

**Comment by skye** [comment] 2018-09-10 14:16
@apischan is right on both counts. Closing this since it's not a bug or feature request.

**Closed by skye** 2018-09-10 14:16 UTC
