### ISSUE TITLE
SSL certificate for tensorflow.org expired

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/tensorflow#12496] opened 2017-08-22 15:25 UTC
The SSL certificate for https://tensorflow.org (*not* https://www.tensorflow.org) expired on June 29.

**Comment by ali01** [comment] 2017-08-28 04:08
@martinwicke, we should fix this. Could you please reassign appropriately? Thanks!

**Comment by martinwicke** [comment] 2017-08-28 04:36
@wolffg I suppose we were wrong about that cert being unused. Are we ready to move or should we renew what we have?

**Comment by tensorflowbutler** [comment] 2017-12-20 01:21
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:10
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:12
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment] 2018-01-19 22:23
@gunan, I think you got a new one, no?

**Comment by gunan** [comment] 2018-01-20 00:18
Not for tensorflow.org, I got a new one for www.tensorflow.org.
We may need to discuss what exactly needs to be done here.

**Comment by quaeler** [comment] 2018-01-20 01:16
Perhaps use [Let's Encrypt](https://letsencrypt.org/)? Free and wildcarded.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:20
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment] 2018-02-07 13:49
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-02-07 21:23
SSL certificate is updated.

**Closed** 2018-02-07 21:23 UTC
Labels: type:docs

**Comment by brokenairplane** [comment] 2018-02-14 20:33
Could this certificate be applied to *.tensorflow.org as well? https://playground.tensorflow.org/ provides a certificate error.

**Comment by martinwicke** [comment] 2018-02-15 01:35
Playground is served from github pages, which doesn't support cname forwards combined with SSL (a common problem). @dsmilkov I think it's worth finding an alternative for this (GAE?) Come July the pure http will be [effectively inaccessible in Chrome](https://www.theregister.co.uk/2018/02/08/google_chrome_http_shame/).

**Comment by dsmilkov** [comment] 2018-02-15 01:58
Makes sense. Migrating playground to https is long overdue. We are going to use GAE on another project very soon, so I'll do it then.

**Comment by liao-b** [comment] 2018-02-26 05:54
Still not working until Feb 28 2018 on Chrome:

Your connection is not private
Attackers might be trying to steal your information from www.tensorflow.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
Subject: tensorflow.org

Issuer: Google Internet Authority G2

Expires on: Jun 29, 2017

Current date: Feb 25, 2018

**Comment by yunjiangster** [comment] 2018-07-21 13:57
I recently went to China and was using tensorflow.google.cn back there to circumvent the GFW. Upon coming back to the US, I am no longer able to open tensorflow.org on either safari or chrome, but tensorflow.google.cn continues to work. 

On safari, I simply get "too many redirects occurred trying to open ..." message
On chrome, I get a "Your connection is not private" message, but if I proceed anyway to the unsafe address, I would get "This page isn’t working
www.tensorflow.org redirected you too many times.", similar to safari.

I have double checked that my datetime is set correctly to PDT (automatically synced). I have tried clearing all cache, browser history, cookies, etc to no effect. Help is greatly appreciated!

**Comment by yunjiangster** [comment] 2018-07-21 13:59
Here is the certificate warning statement:

This server could not prove that it is www.tensorflow.org; its security certificate expired 387 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Saturday, July 21, 2018. Does that look right? If not, you should correct your system's clock and then refresh this page.
