### ISSUE TITLE
`AttributeError due to '_TensorLike'

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#40251] opened 2020-06-07 21:54 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary):Binary
- TensorFlow version (use command below): tf-nightly-gpu latest
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: gtx 1060

I'm getting the following error,

`AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
`
and this error points to the following line,

`    x = Conv2D(32, (3,3), strides=(1,1), padding='same', name='conv_1', use_bias=False)(input_image)
`

**Comment by Saduf2019** [comment] 2020-06-08 04:47
@Zumbalamambo  
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-06-11 21:58
@Zumbalamambo  When error description include '_TensorLike', then mostly the error is due to mixing of functions from `keras` and `tf.keras` in the code. Can you please share a standalone code that is throwing an error. Thanks!

Please close the issue if this was already resolved for you. Thanks!

**Comment by Zumbalamambo** [comment] 2020-06-19 06:56
+1

**Comment by jvishnuvardhan** [comment] 2020-06-19 12:50
@Zumbalamambo Please let us know whether issue was resolved for you. 

Please close the issue if the issue was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-07-02 03:56
I am closing this issue as i think it was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2020-07-02 03:56 UTC
Labels: TF 2.2, comp:keras, stat:awaiting response, type:support
