### ISSUE TITLE
Batch matrix-matrix product slower than Pytorch

### ISSUE THREAD

**Issue by lioutasb** [tensorflow/tensorflow#28679] opened 2019-05-13 20:59 UTC
I'm doing a batch matrix multiplication using matmul but it seems to be slower than using [bmm](https://pytorch.org/docs/stable/torch.html#torch.bmm) function from Pytorch. Specifically,

```
sentence = tf.constant(tf.random.normal([10240, 32, 3]))
w = tf.constant(tf.random.normal([10240, 3, 1]))

%timeit tf.matmul(sentence, w)
725 µs ± 9.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

compared to 

```
sentence = torch.randn(10240, 32, 3).to(device)
w = torch.randn(10240, 3, 1).to(device)

%timeit torch.bmm(sentence, w)
78.5 µs ± 14 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Is there anyway to speed up the batch matrix-matrix product computation?

Also, normal matrix multiplication seems to be slightly slower than Pytorch

```
sentence = tf.constant(tf.random.normal([10240, 32]))
w = tf.constant(tf.random.normal([32, 1]))

%timeit tf.matmul(sentence, w)
42.6 µs ± 807 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

```

compared to

```
sentence = torch.randn(10240, 32).to(device)
w = torch.randn(32, 1).to(device)

%timeit torch.mm(sentence, w)
19.2 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
but I guess that's between the acceptable limits.

Tested with eager mode both on 1.13 and 2.0-alpha.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): Both 1.13 and 2.0-alpha
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0/CuDNN 7.3.1
- GPU model and memory: NVidia Titan V

**Comment by ppwwyyxx** [comment] 2019-05-14 00:15
When a statement `torch.bmm` returns, it does not mean the computation has finished. The computation on GPU tensors is asynchronous. 
So you cannot use %timeit to time it.

Also, most cuda functions are slower in the first few iterations, which are often excluded from timing.

**Comment by muddham** [comment] 2019-05-15 09:37
@lioutasb Please provide simple reproducible code to investigate it further.

**Comment by muddham** [comment] 2019-05-21 06:05
@lioutasb Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-21 06:05 UTC
Labels: comp:runtime, type:support
