### ISSUE TITLE
bug about tensorflow can not call opencv imread properly

### ISSUE THREAD

**Issue by BKZero** [tensorflow/tensorflow#14826] opened 2017-11-23 08:16 UTC
------------------------

### System information
**- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7(but actually i am talking about c++ code)
- **Bazel version (if compiling from source)**: 0.5.4/0.7.0 all tried
- **GCC/Compiler version (if compiling from source)**:  4.8.4
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: CPU mode
- **Exact command to reproduce**: bazel run -c opt //tensorflow/cc/face:face**

### Describe the problem
i add opencv as a third party lib to tensorflow, and modify the workspace and BUILD file to include it to the project. it works well when i use tensorflow 1.2.1 or version before it. recently i update my tensorflow to the newest version, it recommand i must update my bazel at least 0.5.4(i use 0.5.2 with jdk7 before).
and when i update bazel, and move my own code to the new project, compiling seems ok. but when i run the binary, it seems not right. i can not load a jpeg file when i use cv::imread, it doesn't crash, but return a cv::Mat with size 0. in the new project, i can load a bmp file properly, so i guess it is because the project does not link the libjpeg.
but i never need to link the libjpeg manually, because it is included in the opencv library. so i guess there is a bug in the new version of tensorflow.
i have tried the linkopt with -ljpeg, but it does not work.

### Source code / logs
WORKSPACE File:
new_local_repository(
  name = "opencv",
  path = "/usr/local",
  build_file = "opencv.BUILD",
)
BUILD file of opencv:
cc_library(
    name = "opencv",
    srcs = glob(["lib/*.so*"]),
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"], 
    linkstatic = 1,
)
BUILD file of my code
tf_cc_binary(
    name = "face",
    srcs = ["face.cc"],
    includes = ["."],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",
        "@opencv//:opencv",
    ],
    copts = ["-fopenmp"],
    linkopts = ["-lgomp", "-ljpeg"],
)
my code:
        cv::Mat img = cv::imread("pic.jpg");
        std::cout<<line<<" "<<img.channels()<<" "<<img.cols<<" "<<img.rows<<endl;
the log will be: pic.jpg 1 0 0
but if i read a bmp file:
        cv::Mat img = cv::imread("pic.bmp");
        std::cout<<line<<" "<<img.channels()<<" "<<img.cols<<" "<<img.rows<<endl;
the log will be: pic.bmp 3 500 355

**Comment by aselle** [comment] 2017-11-28 16:57
can you do an ldd on the openmp library and the tensorflow dso libraries? Does it work if you don't link tensorflow and only link opencv?

**Comment by martinwicke** [comment] 2017-11-29 00:56
Both TF (via bazel) and OpenCV include libjpeg and build it from source as part of their build. It is conceivable that, if they use different versions, or even if they don't, that there might be global state that is confused between the two. 

I also don't know what OpenCV does if the jpeg decoder is not available, do you have to configure OpenCV to use jpeg manually, i.e. define some compiler defines? The test @aselle suggested should clear that up.

**Comment by kxhit** [comment] 2017-12-15 06:34
Hi! I meet the same problem.
I'm using opencv3.1 tensorflow1.4 in ubuntu14.04. When I included tensorflow headers like #include <tensorflow/core/public/session.h> or #include "tensorflow/cc/ops/standard_ops.h", cv::imread can not read images encoded by JPEG, but can read other encoding images like Uncompressed 8-bit RGB. When I commented TF headers, I can read any images by cv::imread. Is there any solution? Thanks a lot!!! @martinwicke @aselle

**Comment by YaoQ** [comment] 2017-12-27 07:34
I got same issue when I compile the[ mtcnn face detector with OpenCV](https://github.com/cyberfire/tensorflow-mtcnn/tree/master/cpp/tf_embedded).
I just use OpenCV3.3 and tensorflow 1.4.0.

**Comment by tensorflowbutler** [comment] 2018-01-10 18:56
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by kxhit** [comment] 2018-01-11 06:34
I rebuild libtensorflow_cc.so using command bazel build --config=monolithic :libtensorflow_cc.so , and can read any images successfully. 
see  #14267[](https://github.com/tensorflow/tensorflow/issues/14267#issuecomment-351914635)

**Comment by martinwicke** [comment] 2018-01-11 22:18
That means that most likely the cause is a version mismatch of some dependent library (most likely libjpg): TF builds against the version pointed to by its bazel workspace, but links dynamically against what's installed. If those don't match, bad things happen. If you build --config=monolithic, you link statically and everything is fine. 

The other fix for this is to change the bazel workspace dependency to use the same version that is used by opencv (which I think *also* distributes a version in their sources). 

I'll close this issue as I don't see how we can fix this, but a viable workaround exists.

**Closed by martinwicke** 2018-01-11 22:18 UTC
Labels: stat:awaiting response, type:build/install
