### ISSUE TITLE
AUCROC > 80% with sensitivity 1.0 and specificity 0.0?

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/tensorflow#36373] opened 2020-01-31 13:05 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: Python 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla K80 11441MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
True negatives and false negatives are 0, sensitivity computes to 1.0 and specificity to 0.0, but the AUCROC is giving 80%.

**Describe the expected behavior**
Isn't AUCROC used a single number to represent performance across the entire confusion matrix of true positives, true negatives, false positives and false negatives?

**Code to reproduce the issue**
This code was used to parse the TensorBoard data into Pandas: https://gist.github.com/ptschandl/ef67bbaa93ec67aba2cab0a7af47700b

With the basic formula for both:
```
'sensitivity': np.divide(tp, np.add(tp, fn)),
'specificity': np.divide(tn, np.add(tn, fp)),
```

**Other info / logs**
Metrics included AUCROC, and all 4 metrics of the confusion matrix taken at threshold 50.
<img width="918" alt="Screen Shot 2020-01-29 at 9 26 16 pm" src="https://user-images.githubusercontent.com/807580/73541346-4c9ebf80-4486-11ea-8e03-aba7c2209f9b.png">

**Comment by amahendrakar** [comment] 2020-02-03 13:13
@SamuelMarks,
I was unable to reproduce the issue from the link given above. Please find the Gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/faeada87cf68c37d640bac07ac5539da/36373.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment] 2020-02-10 13:15
Any updates regarding the complete reproducible code? Thanks!

**Comment by amahendrakar** [comment] 2020-02-19 06:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-19 06:17 UTC
Labels: stat:awaiting response
