### ISSUE TITLE
Keras saves invalid JSON files containing NaN

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#37196] opened 2020-02-29 19:35 UTC
**Describe the current behavior**

JSON saved by Keras contains `NaN` which is invalid according to [RFC 7159](https://tools.ietf.org/html/rfc7159):

> "Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted."

**Describe the expected behavior**

Keras saves correct JSON format.

**Standalone code to reproduce the issue** 

```
import tensorflow as tf
i = tf.keras.layers.Input((600,600,3))
o = tf.keras.layers.Conv2D(16, (3, 3), padding='same', name='conv0',
       kernel_regularizer=tf.keras.regularizers.l2(1e-2),
       bias_regularizer=tf.keras.regularizers.l2(None),
       kernel_initializer=tf.keras.initializers.RandomNormal(stddev=0.01),
       bias_initializer=tf.keras.initializers.constant(0.0))(i)
model = tf.keras.models.Model(i, o)
with open('repro.json', 'w') as json_file:
    json_file.write(model.to_json())
```

```
~ node
> JSON.parse(require('fs').readFileSync('repro.json', 'utf-8'))
Uncaught SyntaxError: Unexpected token N in JSON at position 861 
```

[repro.zip](https://github.com/tensorflow/tensorflow/files/4270871/repro.zip)

lutzroeder/netron#435

**Comment by gadagashwini** [comment] 2020-03-04 09:00
I was able to replicate the issue Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/d029a1da140e81b7b510335a0acf23db/untitled.ipynb). Thanks!

**Comment by howl-anderson** [comment] 2020-03-13 02:34
@lutzroeder @gadagashwini I am willing to take a closer look, fix it and send a PR.

**Comment by howl-anderson** [comment] 2020-03-16 06:57
@lutzroeder @gadagashwini 

This bug is caused by `tf.keras.regularizers.l2` which will convert `None` to JSON string when `model.to_json` is called. 
`None` will convert to NumPy float first, it will be a `np.nan`. 
Then `np.nan` will be converted to Python float, it will be `float('nan')`. 
Finally, `float('nan')` will be converted to a JSON string, python's built-in JSON library allow dump `float('nan')` to string as `NaN` (https://docs.python.org/3.6/library/json.html#infinite-and-nan-number-values).  

I will submit a PR later to make sure `tf.keras.regularizers.l2` will only accept float value.

**Comment by clkruse** [comment] 2020-04-19 05:50
Does this same issue apply to `tf.keras.layers.BatchNormalization()`?
I'm using the Pix2Pix example code and having a similar problem with NaN values in my one set of weights and in my model.json when created with tfjs.

**Comment by howl-anderson** [comment] 2020-04-19 07:45
Hi @clkruse, If your arguments contain None which not supposed to be. It's likely to be the same issue.

**Comment by howl-anderson** [comment] 2020-06-02 07:57
@clkruse Can you submit an issue for your problem, so I can check and fix it.

**Comment by clkruse** [comment] 2020-06-03 05:34
@howl-anderson I have an issue out for my version of the problem in #38698. 

Note: the error only seems to occur when batchnorm is used with a batch size of 1.

**Comment by howl-anderson** [comment] 2020-06-03 05:48
@clkruse I will take a close look to see if I can fix it.

**Comment by goldiegadde** [comment] 2020-07-13 20:50
@lutzroeder can you confirm if your issue is fixed with the above commit by @howl-anderson , if so please close the issue.

**Closed** 2020-07-13 23:04 UTC
Labels: TF 2.1, comp:keras, stat:awaiting tensorflower, type:bug
