### ISSUE TITLE
Providing a Prebuilt Binary for TFLite Benchmark

### ISSUE THREAD

**Issue by fzyzcjy** [tensorflow/tensorflow#26499] opened 2019-03-09 02:29 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): latest
- Are you willing to contribute it (Yes/No): Y

**Describe the feature and the current behavior/state.**
There are many people benchmarking their tflite models using the https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark . However, it seems that this does not provide a pre-built binary, so we have to build it by ourselves. Since there are many people needing to benchmark, I think the pre-built binary can benefit a lot of people and save their time. I would appreciate it if it could be done.

**Will this change the current api? How?**
N

**Who will benefit with this feature?**
Everyone who uses tflite benchmark

**Any Other info.**
N/A

**Comment by fzyzcjy** [comment] 2019-03-09 02:55
In addition, it does not support windows compile 😢 so what should I do

**Comment by jdduke** [comment] 2019-03-22 17:41
Thanks for the suggestion.

The problem is one of hosting and deployment. We don't store binaries in the actual GitHub repo, so what would be the distribution model for the binary? We could potentially bundle it in the TensorFlow pip, but then you're getting *host* performance, not on-device performance.

**Comment by fzyzcjy** [comment] 2019-03-23 02:22
Sorry, I do not quite get your point... I think, if the binaries are bundles in pip, everything will be fine and I can get on-device performance!

Looking at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark , we see these steps:

(0) ndk install
(1) Build for your specific platform
(2) Connect your phone. Push the binary to your phone with adb push (make the directory if required):
(3) Make the binary executable.
(4) Push the compute graph that you need to test.
(5) Run the benchmark. For example:

The step (1) is the only step which requires building from source. If the binary is bundled and given in pip, then I think I can get **on-device** performace, because: In step (2)-(5), I push _my own model(compute graph)_, and I execute the binary on _my own mobile phone_. Thus I think it is _on device_, not _hosted_.

Please correct me if I am wrong, and thank you very much for your reply!!

**Comment by jdduke** [comment] 2019-03-25 15:43
>  If the binary is bundled and given in pip

For better or worse, we cannot bundle *Android* binaries in a pip compiled for a desktop PC.

What we can do is provide a single shell script which automates steps (1)-(5). Would that help?

**Comment by fzyzcjy** [comment] 2019-03-26 08:53
> For better or worse, we cannot bundle _Android_ binaries in a pip compiled for a desktop PC.

Oh it does not matter in _pip for PC_. It would be excellent if the binary can be put **somewhere**!

**Comment by jdduke** [comment] 2021-08-30 15:56
@multiverse-tf can you link to the prebuilts?

**Comment by ymodak** [comment] 2021-08-30 16:54
For benchmark binary - https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

**Comment by fzyzcjy** [comment] 2021-08-31 00:25
Nice to see it is now there! (Though 2.5 yr has passed and I am no longer doing tflite...)

**Comment by ymodak** [comment] 2021-08-31 17:31
Closing this issue now since the feature is added. Thanks!

**Closed by ymodak** 2021-08-31 17:31 UTC
Labels: stat:awaiting response, type:feature, comp:lite
