### ISSUE TITLE
Can't allocate memory for the interpreter in tflite

### ISSUE THREAD

**Issue by shiftsayan** [tensorflow/tensorflow#19982] opened 2018-06-13 09:19 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Nope, using tensorflow-for-poets
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.1
- **Python version**: Python 2.7.10
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: I added a custom tflite model (converted .pb using TOCO) and replaced graph.lite with the new custom model and built the app, but it crashes on runtime.

### Detailed Description
I created a custom TensorFlow model and converted it to TOCO (as described in the tensorflow-for-poets tutorial) and I replaced the old graph.lite file with my custom model and changed nothing else in the code. When I run the app, I get the following runtime error:

```
Process: android.example.com.tflitecamerademo, PID: 29160
    java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Can not allocate memory for the interpreter
```

### Fixes Already Tried
- Ensuring that Android Studio/Gradle pick up on tensorflow-lite:0.1.7 changes (#19051). Currently, my build.gradle file says `compile 'org.tensorflow:tensorflow-lite:+'`, but changing it to `compile 'org.tensorflow:tensorflow-lite:0.1.7'` doesn't resolve the issue either.
- Running TOCO with the `--change_concat_input_ranges=false` flag.

**Comment by alanchiao** [comment] 2018-06-14 22:07
Hey Sayan, thanks for following up on this. 

Could you possibly update the build.gradle file to 'org.tensorflow:tensorflow-lite:0.0.0-nightly' and see if it fixes your issue? It contains the most recent version of the TFLite library.

**Comment by shiftsayan** [comment] 2018-06-15 06:09
Hey Alan, thanks for taking up the issue!
When I make the change you suggested, I get the following error message: `Multiple dex files define Lorg/tensorflow/lite/NativeInterpreterWrapper;`, but I am not sure if this has something to do with the fact that I am running the nightly build.

**Comment by shiftsayan** [comment] 2018-06-18 06:41
I tried compiling and running the app again today with the nightly build and I get the following error message now:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:191 input->dims->size != 4 (0 != 4)`

**Comment by alanchiao** [comment] 2018-06-19 20:22
Hey Sayan! There seems to have been a problem in the model conversion process (ex: TOCO) as opposed to the demo app.

As the error message indicates, one of your conv operators is provided with an input tensor with no dimensions.

**Some Background for Debugging**
For ops with dynamic inputs, we call the Prepare function (that your error appeared in) right before calling its Eval function. Suppose op A feeds its output into op B through tensor C. The Prepare call in dynamic op A will resize tensor C.

No we can suppose in your model, the conv op that's failing is op B. For some reason, op A has not resized tensor C and the conv op is seeing an input tensor with no dims. 

Unfortunately, I don't currently have cycles to help debug a model-specific issue. If it's ok for you to share your frozen graph file, that'd be great for when someone gets cycles to look into it.

**Comment by tensorflowbutler** [comment] 2018-07-04 18:43
Nagging Assignee @alanchiao: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Whiteseeker** [comment] 2018-07-09 08:13
I'm also having the issue

**Comment by tensorflowbutler** [comment] 2018-07-24 12:58
Nagging Assignee @alanchiao: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karlzheng** [comment] 2018-07-26 10:48
with the same problem.

**Comment by bayan100** [comment] 2018-07-31 10:19
I had the same issue (Nr. 3). Its probably because you retrained you modell with a modified retrain.py script. To complete the tutorial I had to give a variable called input_layer another value (to solve a different issue).
When converting your model with toco you have to make sure to use the same value as parameter for input_array.
Solved the problem for me.

**Comment by alanchiao** [comment] 2018-08-01 17:42
Thank you @bayan100 for sharing how you resolved Nr. 3!

Closing this issue since the original reporter hasn't responded for a while. @Whiteseeker and @karlzheng, feel free to create a separate issue and link to this one for context. If what Bayan said is true (you'd modified retrain.py), it'd be great if you mentioned it here so others know that that's the cause.

**Closed by alanchiao** 2018-08-01 17:42 UTC
Labels: comp:lite

**Comment by luolugithub** [comment] 2018-08-02 09:24
java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:191 input->dims->size != 4 (1 != 4)Node 0 failed to prepare.

how to solve?

**Comment by alanchiao** [comment] 2018-08-02 20:06
@luolugithub : there isn't sufficient information from just that error. Does bayan100's comment apply to you?

We'd need the .tflite model file at a minimum (or something the reproduces the error), and if it's generated from a working model (e.g. via retraining via retrain.py), it'd be useful to see both the original model and the generation code. Thanks!

**Comment by nakulbharuka** [comment] 2018-08-04 13:31
I have the same problem 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.example.com.tflitecamerademo, PID: 29651
    java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:191 input->dims->size != 4 (0 != 4)Node 0 failed to prepare.

Please help me

**Comment by CartierPierre** [comment] 2018-11-06 13:53
Having the same issue when trying to run on Android.
`Internal error: Unexpected failure when preparing tensor allocations: tensorflow/contrib/lite/kernels/conv.cc:225 input->dims->size != 4 (0 != 4)Node number 0 (CONV_2D) failed to prepare.`
I used the last retrain.py from https://www.tensorflow.org/hub/tutorials/image_retraining with my own dataset.
Then converting using TOCO `./toco --input_file="$HOME/tensorflow-master/output_graph.pb" --output_file="$HOME/output_graph.tflite" --input_arrays=Placeholder --output_arrays=final_result`
Then putted in the android lite demo next to mobilenet_quant.tflite.
And i don't understand what @bayan100 said with the input_layer

**Comment by CartierPierre** [comment] 2018-11-09 14:58
The .pb model looks good because still have 4 dimension with Placeholder but when i try to open .tflite converted mode, it doesn't find any input array. Still working on it, may be a problem with toco

**Comment by damhurmuller** [comment] 2018-11-15 09:56
Same error here but only when Im trying to use the post-training quantization.

`converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file('models/mobilenet_tune.h5')`
`converter.post_training_quantize = True --> Without this line is Ok`
`tflite_model = converter.convert()`
`open("mobilenet_quantize_model.tflite", "wb").write(tflite_model)`

**Comment by SreehariRamMohan** [comment] 2018-11-27 05:37
@damhurmuller I'm doing the same thing as you and running into issues. Did you manage to find a solution?

**Comment by damhurmuller** [comment] 2018-11-27 05:57
@SreehariRamMohan I was using an old version 1.10.* I guess. Now I'm using the nightly version and is ok.

**Comment by SreehariRamMohan** [comment] 2018-11-27 06:01
@damhurmuller I switched to compiling the tf nightly version but I still get the following error:

`Caused by: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhg.zza(Unknown Source)
W/System.err: 	... 5 more
W/System.err: Caused by: java.lang.NullPointerException: Can not allocate memory for the interpreter
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
W/System.err:     at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:90)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzif.zzfm(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhr.zzfp(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhr.call(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhg.zza(Unknown Source)
W/System.err: 	... 5 more`

**Comment by aselle** [comment] 2018-11-27 16:57
@alanchiao, what version of TFLite is required to use post_training_quant?

**Comment by alanchiao** [comment] 2018-12-12 18:30
@mstc-xqp : please create a separate issue. While the error message is the same, the underlying cause is different.

@damhurmuller : that makes sense. I don't think the post_training_quantize was ready for use until the 1.11 release

**Comment by MATTYGILO** [comment] 2018-12-14 18:51
I am having the same problem. Has anyone worked out a solution to this problem.

**Comment by alanchiao** [comment] 2018-12-14 19:16
@MATTYGILO : could you please create a separate issue (and CC mstc-xqp if the error is exactly the same).

Note that for mstc's case, the error is for the concatenation.cc , whereas for Pierre, it's for the conv.cc. These are all model-specific and op-specific issues

**Comment by GustavZ** [comment] 2019-02-15 08:25
same problem here

**Comment by fcakir** [comment] 2020-04-24 00:20
I encountered a similar problem when trying to convert pb to tflite using the toco converter (via bazel). I managed to get rid of the problem by passing in the `input_shape `argument in the command line, e.g., `--input_shape=1,224,224,3.` Just adding here as a reference.

**Comment by joonb14** [comment] 2021-03-04 14:47
> I tried compiling and running the app again today with the nightly build and I get the following error message now:
> `java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/conv.cc:191 input->dims->size != 4 (0 != 4)`

In my case, I used multiple inputs. I solved the similar problem with
![image](https://user-images.githubusercontent.com/30307587/109981154-fadcfe80-7d43-11eb-86d6-def6fd797196.png)
