### ISSUE TITLE
TensorRT loses defined shapes 

### ISSUE THREAD

**Issue by joeyearsley** [tensorflow/tensorflow#21125] opened 2018-07-25 10:45 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **Bazel version**: N/A
- **GPU model and memory**: Titan 12Gb
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10rc0
- **Python version**: 3.5
- **CUDA/cuDNN version**: 9 / 7.0.15

### Describe the problem
When `tf.contrib.tensorrt` compiles a graph which can be fully compiled it loses shape information.

For example if you compile a graph which has no activations, for example a model which ends in an average pool so that you can get [N, C] then the shape information is lost.

If you load up that optimised model and try to add an operation on the end which required a shape definition, for example a `tf.unstack` it will fail out stating there isn't any shape information.

This seems like the output shape should be kept.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:50
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-08-09 13:14
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-08-24 21:54
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by joeyearsley** [comment] 2018-09-07 09:11
N/A
Titan 12Gb
N/A
None

**Comment by tensorflowbutler** [comment] 2018-09-24 12:47
Nagging Assignee @rohan100jain: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-09 18:43
Nagging Assignee @rohan100jain: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment] 2018-10-11 00:32
Could you provide some piece / snippet of code that can reproduce the problem? That can help us debug.

**Comment by tensorflowbutler** [comment] 2018-10-25 12:40
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by wt-huang** [comment] 2018-10-26 21:09
Closing due to low activity

**Closed by wt-huang** 2018-10-26 21:09 UTC
Labels: stat:awaiting response, type:bug/performance
