### ISSUE TITLE
tf.keras throws AlreadyExistsError for LSTM training whereas keras stand-alone throws no error.

### ISSUE THREAD

**Issue by yakaboskic** [tensorflow/tensorflow#29413] opened 2019-06-04 20:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13.1 (keras version 2.2.4)
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: None
- GPU model and memory: None (CPU Training)

**Describe the current behavior**
When using tf.keras models and layers to build a simple LSTM and train on the Penn Treebank Dataset a long list of errors are thrown of the form:

W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE

However, when just importing keras and building the same LSTM, no errors occur. 

**Describe the expected behavior**
It would be expected that both keras's should be operational. I am also not mixing and matching keras and tf.keras layers.

**Code to reproduce the issue**
Attached is a test case that reproduces the problem. It is required that the Penn Treebank Dataset is downloaded/available (Directions in source). Code was modified from:

https://github.com/adventuresinML/adventures-in-ml-code/blob/master/keras_lstm.py

Run option 1 to use keras with no errors and use option 2 to run with tf.keras and see all the errors.

**Other info / logs**

2019-06-04 15:27:39.644788: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.647428: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.664264: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.666201: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.671178: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.676772: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.680910: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.685541: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.689694: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.693689: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.702369: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.703234: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.713664: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.725751: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.727035: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.731410: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.734116: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.745524: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.749895: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.750059: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.754578: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.757058: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.764737: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.769848: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.779327: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.779501: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.787285: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-04 15:27:39.793182: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/
Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "keras_lstm_issueFile.py", line 152, in <module>
    validation_steps=len(valid_data)//(batch_size*num_steps))
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 191, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1191, in train_on_batch
    outputs = self._fit_function(ins)  # pylint: disable=not-callable
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/cyakaboski/python/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_5/training/Adam/gradients/lstm/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19Tem
poraryVariableOp6TmpVarE
         [[{{node training/Adam/gradients/lstm/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]

[keras_lstm_issueFile.zip](https://github.com/tensorflow/tensorflow/files/3254289/keras_lstm_issueFile.zip)

**Comment by gadagashwini** [comment] 2019-06-05 08:23
@yakaboskic I tried reproducing the issue of option 1 and option 2 separately but I am not able to reproduce the it, Could you please provide minimal code snippet to reproduce issue. Thanks!

**Comment by Drezil** [comment] 2019-06-05 08:36
I have the same issue, but also complicated/long code - thus no minimal example.
When learning with a lear-rate of 0 the error vanishes, but the network is not learning ;)
A bit of googling hinted at some weights degenerating and yielding similar errors.

Also the net trained ~1.8 Epochs yesterday (around 800 iterations) and then encountered this error. When fiddling with the learning-rate i can make it crash after 1 iteration (with a lr of 1) or not at all (with a lr of 0).

Hope this information help a bit.

System is debian stretch with python 3.5.3 (GCC 6.3.0) and a GTX1080 for training. Also current tensorflow from pip.

**Comment by Drezil** [comment] 2019-06-05 09:23
reverted back to 1.12. That version works without problems.

**Comment by gadagashwini** [comment] 2019-06-13 04:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-13 04:52 UTC
Labels: TF 1.13, comp:keras, stat:awaiting response, type:support

**Comment by indestinee** [comment] 2019-07-12 12:32
@Drezil Thanks a lot! It works! :)
I tried in 1.14.0 and 1.13.1, error occurs. 
but with 1.12.0, it's perfect!

**Comment by gavinlive** [comment] 2020-02-22 20:54
Is this issue still present in TF 2.0 in graph mode (with tf.function decorator?)

**Comment by gadagashwini** [comment] 2020-02-24 06:58
@gavinlive, 
Can you please post a new issue by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!
