### ISSUE TITLE
stats_calculator.cc:185:13: error: no member named 'emplace' 

### ISSUE THREAD

**Issue by Antpachon** [tensorflow/tensorflow#19875] opened 2018-06-09 10:38 UTC
### System information
Darwin newbmac753702.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.3

   ANDROID_BUILD_TOOLS_VERSION=27.0.3 \
    ANDROID_NDK_API_LEVEL=15 \
    ANDROID_SDK_API_LEVEL=27 \
    PYTHON_BIN_PATH=/Users/aruiz/miniconda3/bin/python \
    PYTHON_LIB_PATH=/Users/aruiz/miniconda3/lib/python3.6/site-packages \

Hi. I am trying to build an .apk following the steps in the android samples readme
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md however when running
bazel build -c opt //tensorflow/examples/android:tensorflow_demo 
the following errors are thrown.

### Source code / logs
tensorflow/core/util/stats_calculator.cc:142:24: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& det : details_) {
                       ^
tensorflow/core/util/stats_calculator.cc:181:72: error: a space is required between consecutive right angle brackets (use '> >')
  std::priority_queue<std::pair<int64_t, std::pair<std::string, int64_t>>>
                                                                       ^~
                                                                       > > 
tensorflow/core/util/stats_calculator.cc:183:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (const auto& node_type : node_type_map_time) {
             ^
tensorflow/core/util/stats_calculator.cc:183:30: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (const auto& node_type : node_type_map_time) {
                             ^
tensorflow/core/util/stats_calculator.cc:185:13: error: no member named 'emplace' in 'std::priority_queue<std::pair<long long, std::pair<std::basic_string<char>, long long> >, std::vector<std::pair<long long, std::pair<std::basic_string<char>, long long> >, std::allocator<std::pair<long long, std::pair<std::basic_string<char>, long long> > > >, std::less<std::pair<long long, std::pair<std::basic_string<char>, long long> > > >'
    timings.emplace(node_type.second,
    ~~~~~~~ ^
tensorflow/core/util/stats_calculator.cc:200:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto entry = timings.top();
    ^

I am able to solve the issue with the  > > spaces but not the emplace not found. Any ideas?

Thanks a lot

**Comment by tensorflowbutler** [comment] 2018-06-09 18:32
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment] 2018-06-22 16:10
It looks like you have an old compiler that doesn't support cxx11 properly.

**Comment by drpngx** [comment] 2018-06-22 16:10
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-06-22 16:10 UTC
Labels: stat:awaiting response
