### ISSUE TITLE
UnimplementedError:  Fused conv implementation does not support grouped convolutions for now. 	

### ISSUE THREAD

**Issue by abhishekkuber** [tensorflow/tensorflow#44929] opened 2020-11-17 07:19 UTC
I am using the FERN 2013 dataset from kaggle for the emojify project. The dataset consists of 48X48 grayscale images. 
When I go to train the model, I get an error as shown below. I am using tensorflow version 2.3.0

UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
	 [[node sequential_3/conv2d_6/Relu (defined at <ipython-input-16-994f59dc933f>:1) ]] [Op:__inference_train_function_3421]

Function call stack:
train_function

My code is as follows : 

import numpy as np
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(horizontal_flip=True)
training_set = train_datagen.flow_from_directory('train/', batch_size=32, class_mode='categorical')

test_datagen = ImageDataGenerator(horizontal_flip=True)
test_set = test_datagen.flow_from_directory('test/', batch_size=32, class_mode='categorical')

cnn = tf.keras.models.Sequential()

cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(48, 48, 1)))

cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(48, 48, 1)))

cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

cnn.add(tf.keras.layers.Flatten())

cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

cnn.fit(x=training_set, validation_data=test_set, epochs=25)

**Comment by Saduf2019** [comment] 2020-11-17 08:06
@abhishekkuber 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by bhack** [comment] 2020-11-17 12:54
Please check if it isn't a duplicate of https://github.com/tensorflow/tensorflow/issues/41107

**Closed** 2020-12-02 05:51 UTC
Labels: stalled, stat:awaiting response, type:bug
