### ISSUE TITLE
InvalidArgumentError if np.ndarray is registered as Sequence type

### ISSUE THREAD

**Issue by kyao** [tensorflow/tensorflow#35650] opened 2020-01-07 22:25 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: CPU

**Describe the current behavior**

For reference, numpy is planning to register numpy ndarray as a Sequence:
https://github.com/numpy/numpy/issues/2776

The sample ResNet50 code from https://keras.io/applications/ runs fine. But, if ndarray is registered as a sequence, then TF2 throws an InvalidArgumentError.

**Code to reproduce the issue**

```
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np
import typing
typing.Sequence.register(np.ndarray)

model = ResNet50(weights='imagenet')

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])
# Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]
```

Two extra lines added to the sample ResNet50 code are:

```
import typing
typing.Sequence.register(np.ndarray)
```

The error is:

```
2020-01-07 13:48:16.421816: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: The first dimension of padding\s must be the rank of inputs[4,2] []
         [[{{node conv1_pad/Pad}}]]
Traceback (most recent call last):
  File "test_d3m_imports.py", line 16, in <module>
    preds = model.predict(x)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  The first dimension of paddings must be the rank of inputs[4,2] []
         [[node conv1_pad/Pad (defined at /data/dsbox/kyao/miniconda3/envs/dsbox-eval-2019-winter/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [O\p:__inference_keras_scratch_graph_10370]

Function call stack:
keras_scratch_graph

```

**Comment by vidursatija** [comment] 2020-01-08 13:27
Hi,
There's a chance that TF2 doesn't support `Sequence` yet. I think we'll have to wait for the community to add such support

**Comment by amahendrakar** [comment] 2020-01-08 14:50
@kyao,
Tried to reproduce the issue using keras and tensorflow.keras, but I am facing an error different from yours.
Please find the attached Gist for keras [here](https://colab.sandbox.google.com/gist/amahendrakar/75fd7c47f61a12133313d0f6b9ba0d11/35650_keras.ipynb) and tensorflow.keras [here](https://colab.sandbox.google.com/gist/amahendrakar/f5b3b3ca9979e6ceeb8a247436e811ef/35650_tf-keras.ipynb). Could you please provide a minimal reproducible code for the issue? Thanks!

**Comment by kyao** [comment] 2020-01-08 19:40
@amahendrakar ,
The correct expected behaviors are for keras [here ](https://colab.research.google.com/drive/11yS9C5Gi8zoL7JwxALvbZXKX-zwMh7hQ) and tensorflow.keras  [here](https://colab.research.google.com/drive/1VkDeuL1zY9VJecD6ApGANthGMH74NMuK).

With the Sequence.register statement added the unexpected behaviors  are for keras [here](https://colab.research.google.com/drive/1sSnoFdQjgZcNlFnNlpi_UeUfMtlo1UlH) and for tensorflow.keras [here](https://colab.research.google.com/drive/1bc7fSgeCpKQvO8wxImzeL-Opopa1qy1i#scrollTo=5KxvZjBXkJig). For tensorflow.keras I did get the same error as you.

**Comment by amahendrakar** [comment] 2020-01-09 12:04
@kyao,
I do not have the permission to view the files. Please try saving the Gist using the following method
'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!

**Comment by kyao** [comment] 2020-01-11 23:11
@amahendrakar ,
Here they are on Github Gist

The correct expected behaviors are for keras [here ](https://colab.research.google.com/gist/kyao/408f31e638a39371a35a8e8492619904/35650_keras-expected.ipynb)and tensorflow.keras [here](https://colab.research.google.com/gist/kyao/43e472c6b712935b956b8b6d5f4879df/35650_tf-keras-expected.ipynb).

With the Sequence.register statement added the unexpected behaviors are for keras [here ](https://colab.research.google.com/gist/kyao/42ced4cd80bc592e80829365ea6ab3f0/35650_keras_2.ipynb)and for tensorflow.keras [here](https://colab.research.google.com/gist/kyao/5626f3d7d8d326cd62147f3cb8cef448/35650_tf-keras_2.ipynb). For tensorflow.keras I did get the same error as you.

**Comment by amahendrakar** [comment] 2020-01-13 10:04
Was able to replicate the issue from the given Gist.

**Comment by karmel** [comment] 2020-01-23 19:40
@kyao -- Keras supports ndarray, but we have to check and handle a variety of types. It's likely that the Sequence registration is throwing off some of these checks. @tomerk will take a look, but it may be that you are best using the raw ndarray.

**Comment by sachinprasadhs** [comment] 2021-05-24 10:20
@kyao, The issue is now fixed in TF Nightly version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/43d5e0b89b76db855d57fb9fc1a81e6f/35650.ipynb).

**Closed by sachinprasadhs** 2021-05-24 10:20 UTC
Labels: TF 2.1, comp:keras, type:bug
