### ISSUE TITLE
Train Keras model with GPU Google Colab very slow when compared with my personal cpu

### ISSUE THREAD

**Issue by quancq** [tensorflow/tensorflow#26375] opened 2019-03-06 04:22 UTC
**Information environment when I run [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)**

== cat /etc/issue ===============================================
Linux dc5aaefaf4e1 4.14.79+ #1 SMP Wed Dec 19 21:19:13 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux dc5aaefaf4e1 4.14.79+ #1 SMP Wed Dec 19 21:19:13 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
mesh-tensorflow          0.0.5                
msgpack-numpy            0.4.3.2              
numpy                    1.14.6               
protobuf                 3.6.1                
tensorflow               1.13.1               
tensorflow-estimator     1.13.0               
tensorflow-hub           0.3.0                
tensorflow-metadata      0.12.1               
tensorflow-probability   0.6.0                

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.13.1
tf.GIT_VERSION = b'v1.13.1-2-g09e3b09e69'
tf.COMPILER_VERSION = b'v1.13.1-2-g09e3b09e69'
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/lib64-nvidia
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Wed Mar  6 04:31:12 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    71W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/lib/python3.6/dist-packages/torch/lib/libcudart-1581fefa.so.10.0
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudart-1581fefa.so.10.0
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.7

**Describe the current behavior**
Train time of each epoch on google colab gpu: ~60s
Train time of each epoch on my personal pc cpu: ~10s

**Code to reproduce the issue**
I train crf model use keras, keras_contrib library
Code:
```python
    input = Input(shape=(config["input_dim"],))
    model = Embedding(input_dim=config["vocab_size"] + 1, output_dim=config["embedding_dim"],
                      input_length=config["input_dim"], mask_zero=True)(input)
    model = Bidirectional(LSTM(units=config["lstm_dim"],
                               return_sequences=True, recurrent_dropout=config["recurrent_dropout"]))(model)
    model = TimeDistributed(Dense(config["dense_dim"], activation="relu"))(model)
    crf = CRF(config["num_tags"])  # CRF layer
    output = crf(model)  # output

    model = Model(input, output)
    model.compile(optimizer=config["optimizer"], loss=crf_loss, metrics=[crf_accuracy])
    model.summary()

```

**Logs**
2019-03-06 04:13:53.402787: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-03-06 04:13:53.403069: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x23c8dc0 executing computations on platform Host. Devices:
2019-03-06 04:13:53.403105: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-06 04:13:53.491058: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-06 04:13:53.491582: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55374a0 executing computations on platform CUDA. Devices:
2019-03-06 04:13:53.491616: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-03-06 04:13:53.492038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-03-06 04:13:53.492071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-06 04:13:53.863400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-06 04:13:53.863478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-06 04:13:53.863513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-03-06 04:13:53.863768: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-03-06 04:13:53.863821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10754 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2019-03-06 04:13:55.629273: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally

**Comment by jvishnuvardhan** [comment] 2019-03-10 15:40
@quancq  Can you provide a code to run and reproduce the bug? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-20 21:15
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-20 21:15 UTC
Labels: comp:keras, comp:runtime, type:support

**Comment by appleyuchi** [comment] 2019-09-22 04:53
@jvishnuvardhan 
Hi it seems that it's duet to the bug from Colab.
Because the GPU of Colab will make almost every package to run slower than that under CPU.
It's very strange

**Comment by jvishnuvardhan** [comment] 2019-09-23 04:52
@appleyuchi Please create a new issue and provide a small standalone code to reproduce the issue. Thanks!

**Comment by nalron** [comment] 2020-02-23 17:45
Hi !
I've the same thing with my Colab.....
And I don't get solution, if someone can help me!????

**Comment by ArefAz** [comment] 2020-04-16 10:15
I have the same problem here.

My laptop has a 960m gpu but it runs tensorflow object detection model training faster than google colab. Am I missing something or is it just normal of free google colab?

**Comment by jvishnuvardhan** [comment] 2020-04-16 13:43
@ArefAz Can you please create an issue with `colab` repository [here](https://github.com/googlecolab/colabtools/issues). thanks!
