### ISSUE TITLE
Tried to read from index 3 but array size is: 3

### ISSUE THREAD

**Issue by PanXiebit** [tensorflow/tensorflow#22408] opened 2018-09-20 11:00 UTC
### System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
OS Platform and Distribution : Linux Ubuntu 16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): N/A
TensorFlow version (use command below): N/A
Python version: 3.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: 8.0
GPU model and memory: N/A
Exact command to reproduce: N/A

### Describe the problem：

Hi, 
when I am using the tf.data.dataset api, I meet the error, and i am confused. 

the error is :
`InvalidArgumentError (see above for traceback): Tried to read from index 3 but array size is: 3`

and my related code is:

```python
def train_input(sess, vocab, rcmodel, train_or_valid=True):
    train_dataset = get_dataset(vocab.word2idx, FLAGS.train_tfrecord_file, FLAGS.train_batch_size,
                                repeat_num=FLAGS.num_epochs, shuffle_bufer=500, prefetch=-1)
    valid_dataset = get_dataset(vocab.word2idx, FLAGS.valid_tfrecord_file, FLAGS.valid_batch_size,
                                repeat_num=-1, shuffle_bufer=500)
    train_iterator = train_dataset.make_initializable_iterator()
    valid_iterator = valid_dataset.make_initializable_iterator()
    if train_or_valid:
        data_handle = sess.run(train_iterator.string_handle())
        sess.run(train_iterator.initializer)
    else:
        data_handle = sess.run(valid_iterator.string_handle())
        sess.run(valid_iterator.initializer)
        
    data_iter = tf.data.Iterator.from_string_handle(string_handle=data_handle,
                                                    output_types=train_dataset.output_types,
                                                    output_shapes=train_dataset.output_shapes)

    batch_data = data_iter.get_next()
    feed_data = {rcmodel.passage: batch_data["passage"].eval(),
                 rcmodel.passage_len: batch_data["passage_len"].eval(),
                 rcmodel.query: batch_data["query"].eval(),
                 rcmodel.query_len: batch_data["query_len"].eval(),
                 # rcmodel.query_id: batch_data["query_id"],
                 rcmodel.answer: batch_data['answer'].eval(),
                 rcmodel.answer_len: batch_data["answer_len"].eval(),
                 rcmodel.alter0: batch_data["alter0"].eval(),
                 rcmodel.alter1: batch_data["alter1"].eval(),
                 rcmodel.alter2: batch_data["alter2"].eval()}
    return feed_data
```

```python
train_feed = train_input(sess, vocab, rcmodel, True)
train_feed[rcmodel.dropout_keep_prob] = FLAGS.dropout_keep_prob
train_summary, _, train_loss, train_ppl_loss, train_acc, step, predict, logits, answer, embedding = sess.run(
                   [merged, rcmodel.train_op, rcmodel.total_loss, rcmodel.ppl_loss,
                    rcmodel.accuracy, rcmodel.global_step, rcmodel.predict, rcmodel.logits,
                    rcmodel.answer, rcmodel.word_embedding],
                   feed_dict=train_feed)
```

I know the error is caused by that: when I try to use 
```sess.run(fetches, feed_dict={passage:data_iter["passage}, query:data_iter['passage_len'])```

```passage:data_iter["passage"]``` consumed a batch, and ```query:data_iter["passage_len"]``` consumed an other batch. So the data pasage and passage_len is not match.

So the reason is that when I sess.run one of the content of batch_iter, it will consume one batch. And I know using the string_handle can solve this problem. 

But when I need to do this:
```python
self.passage = tf.placeholder(tf.int32, [None, None], name="passage")
self.query = tf.placeholder(tf.int32, [None, None], name="query")
self.answer = tf.placeholder(tf.int32, [None, None], name="answer")
self.passage_len = tf.placeholder(tf.int32, [None], name="passage_len")
self.query_len = tf.placeholder(tf.int32, [None], name="query_len")
self.query_id = tf.placeholder(tf.int32, [None], name="query_id")
self.answer_len = tf.placeholder(tf.int32, [None], name="answer_len")
self.alter0 = tf.placeholder(tf.int32, [None, None], name="alter0")
self.alter1 = tf.placeholder(tf.int32, [None, None], name="alter1")
self.alter2 = tf.placeholder(tf.int32, [None, None], name="alter2")
```

What can I do to feed this?

**Comment by tensorflowbutler** [comment] 2018-09-20 19:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wt-huang** [comment] 2018-09-21 00:45
@PanXiebit This question is best asked at StackOverflow as this is not a bug nor feature request. You would need to provide more code snippets if seeking help here.

**Comment by wt-huang** [comment] 2018-09-24 18:15
@PanXiebit test_dataset.types should be the same as train_dataset.shape, You can use tf.reshape()

**Comment by wt-huang** [comment] 2018-09-29 03:00
Closing this for now, feel free to open a new one if running into any issues.

**Closed by wt-huang** 2018-09-29 03:00 UTC
Labels: stat:awaiting response
