### ISSUE TITLE
Tensorflow to CoreML with tf-coreml: `Retval[26]` error

### ISSUE THREAD

**Issue by danvargg** [tensorflow/tensorflow#32959] opened 2019-10-01 17:37 UTC
**System information**
- Have I written custom code: a mix of both
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): `pip install tensorflow-gpu`
- TensorFlow version: 1.14.0
- Python version: 3.6.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA-SMI 418.87.00 / Driver Version: 418.87.00

**Describe the current behavior**
I have a multi-input network that uses a `tf.bool` `tf.placeholder` to manage how batch normalization is executed in training and validation / testing.
I’ve been trying to convert this trained model to `CoreML` via `tf-coreml` library with no success, with below error:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[26] does not have value`
I've also encountered: `NotImplementedError: Unsupported Ops of type: Switch,Merg`

I understand that this error states that there is a certain node that’s missing a value so the converter can execute the model. I also understand this error is connected to control flow operations (linked to the batch normalization method creating operations like `Switch` and `Merge`). The [source code](https://github.com/tensorflow/tensorflow/blob/1c7993f7c597745e3639b9918c3b3ae2165d4af2/tensorflow/python/kernel_tests/control_flow_ops_py_test.py#L244) shows this:

```def testSwitchDeadBranch(self):
    with self.cached_session():
      data = constant_op.constant([1, 2, 3, 4, 5, 6], name="data")
      ports = ops.convert_to_tensor(True, name="ports")
      switch_op = control_flow_ops.switch(data, ports)
      dead_branch = array_ops.identity(switch_op[0])

      with self.assertRaisesWithPredicateMatch(
          errors_impl.InvalidArgumentError,
          lambda e: "Retval[0] does not have value" in str(e)):
        self.evaluate(dead_branch)
```
Note that my error is `Retval[26]` (I’ve gotten [24], etc.), not `Retval[0]`. I’m assuming it tests the `Switch` “dead branch”, which should be the non-used branch for inference. The code also does the same with `Merge` “dead branch”.

Is there any detail I’m missing that may be causing this error (not the first error I’ve faced during conversion, of course)? The way the inference is done? The way batch normalization is implemented? The way the model is saved? 

What I’ve done so far:
- I know `tf.layers.batch_normalization` creates operations `Switch` and `Merge`, which are not CoreML compatible
- I’ve tried converting to `Tensorflow Lite` with similar issues
- I’ve follow `Facenet` (this model uses the same `tf.bool` logic for training, validation, testing) conversion process with no success
- I’ve tried the [`GraphTransforms`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) library
- I’ve tried scripts to remove / modify the control flow 
- I’ve created separate graphs to avoid the extra ops with no success

_Note: I’ve abstracted big part of the code and network to post this issue._

**Code to reproduce the issue**

This is how batch normalization is implemented (within a convolution block):

```
training = tf.placeholder(tf.bool, shape = (), name = 'training')

def conv_layer(input, kernelSize, nFilters, poolSize, stride, input_channels = 1, name = 'conv'):
        with tf.name_scope(name):
        shape = [kernelSize, kernelSize, input_channels, nFilters]
        weights = new_weights(shape = shape)        biases = new_biases(length = nFilters)
        conv = tf.nn.conv2d(input, weights, strides = [1, 2, 2, 1], padding = 'SAME', name = 'convL')
        conv += biases
        pool = tf.reduce_max(conv, reduction_indices=[3], keep_dims=True, name = 'pool') 
       pool = tf.nn.max_pool(conv, ksize = [1, poolSize, poolSize, 1], strides = shape, padding = 'SAME')
        bnorm = tf.layers.batch_normalization(pool, training = training, center = True, scale = True, fused = False, reuse= False)
        act = tf.nn.relu(bnorm)
        return act
```

Below is the code to train and save the model.

```
saver = tf.train.Saver()

    with tf.Session(config = config) as sess:
        sess.run(tf.global_variables_initializer())
        sess.run(tf.local_variables_initializer())
        sess.run(init_train_op)

        for epoch in range(MAX_EPOCHS):
            
            for step in range(10):
                
                l, _, se = sess.run(
                    [loss, train_op, mean_squared_error],
                     feed_dict = {training: True})

            print('\nRunning validation operation...')

            sess.run(init_val_op)
            for _ in range(10):
                val_out, val_l, val_se = sess.run(
                    [out, val_loss, val_mean_squared_error],
                    feed_dict = {training: False})
         
            sess.run(init_train_op) # switch back to training set

        #Save model
        print('Saving Model...\n')
        saver.save(sess, join(saveDir, './model_saver_validation'.format(modelIndex)), write_meta_graph = True)
```

Below is the code to load, update inputs, perform inference, and freeze the model.

```
# Dummy data for inference
b = np.zeros((1, 80, 160, 1), np.float32)
ill = np.ones((1,3), np.float32)
is_train = False

def freeze():
    with tf.Graph().as_default():
        with tf.Session() as sess:
            bIn = tf.placeholder(dtype=tf.float32, shape=[
                             1, 80, 160, 1], name='bIn')
            illumIn = tf.placeholder(dtype=tf.float32, shape=[
                                     1, 3], name='illumIn')
            training = tf.placeholder(tf.bool, shape=(), name = 'training')

            # Load the model metagraph and checkpoint
            meta_file = meta_graph #.meta file from saver.save()
            ckpt_file = checkpoint_file #checkpoint file

            # Load graph to redirect inputs from iterator to expected inputs
            saver = tf.train.import_meta_graph(meta_file, input_map={
                'IteratorGetNext:0': bIn,
                'IteratorGetNext:3': illumIn,
                'training:0': training},  clear_devices = True)
            
            tf.get_default_session().run(tf.global_variables_initializer())
            tf.get_default_session().run(tf.local_variables_initializer())
            saver.restore(tf.get_default_session(), ckpt_file)
            
            pred = tf.get_default_graph().get_tensor_by_name('Out:0')
            
            tf.get_default_session().run(pred, feed_dict={'bIn:0': b, 'poseIn:0': po, 'training:0': is_train})

            # Retrieve the protobuf graph definition and fix the batch norm nodes
            input_graph_def = sess.graph.as_graph_def()

            # Freeze the graph def
            output_graph_def = freeze_graph_def(
                sess, input_graph_def, output_node_names)

        # Serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(frozen_graph, 'wb') as f:
            f.write(output_graph_def.SerializeToString())

freeze()
```

Below is the code to convert to CoreML.

```
tfcoreml.convert(
    tf_model_path=frozen_graph,
    mlmodel_path='./coreml_model.mlmodel',
    output_feature_names=['Out:0'],
    input_name_shape_dict={
        'bIn:0': [1, 80, 160, 1],
        'illumIn:0': [1, 3], 
        'training:0': []})
```

**Other info / logs**
Below is the error thrown by `tf-coreml`.
```
Loading the TF graph...
Graph Loaded.
Collecting all the 'Const' ops from the graph, by running it....

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[26] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf2opencv.py", line 392, in <module>
    'illumIn:0': [1, 3], 'poseIn:0': [1, 16], 'training:0': []})
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 243, in _convert_pb_to_mlmodel
    tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[26] does not have value
```

**Comment by ravikyram** [comment] 2019-10-03 11:21
@danvargg 

Can you please help us with the simple stand alone code to reproduce the issue in our environment.Thanks!

**Comment by danvargg** [comment] 2019-10-03 17:22
@ravikyram thanks for the response, I'll post a code between tomorrow and Monday.

**Comment by danvargg** [comment] 2019-10-07 15:04
Hi, 

Here's a minimal stand alone code.

https://gist.github.com/danvargg/d5258167e27744d071f7bbb00b329e24

**Comment by ravikyram** [comment] 2019-10-10 12:37
@danvargg 

Looks like this is not related to tensorflow issue.Can you please confirm.Thanks!

**Comment by danvargg** [comment] 2019-10-10 13:12
Hi,

Yes, sorry for not updating earlier. I am handling the issue in [`tf-coreml`](https://github.com/tf-coreml/tf-coreml/issues/342).

Thanks!

**Comment by ravikyram** [comment] 2019-10-10 13:24
@danvargg 
Can we close this issue here and track the issue in [tf-coreml](https://github.com/tf-coreml/tf-coreml/issues/342) as this issue is more related to tf-coreml. Please confirm.Thanks!

**Comment by danvargg** [comment] 2019-10-10 13:40
Yes, confirmed! Please close this issue.

**Closed** 2019-10-10 13:57 UTC
Labels: TF 1.14, stat:awaiting response, type:support
