### ISSUE TITLE
Cannot return string from tf.data map function

### ISSUE THREAD

**Issue by laurimi** [tensorflow/tensorflow#18355] opened 2018-04-09 19:46 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: see below

### Describe the problem
The map method of tf.data does not allow returning a string because no implicit conversion to a tensor is made. Instead, an error `AttributeError: 'str' object has no attribute 'get_shape'` is raised.

According to @mrry this is a bug introduced in TF 1.5. For a reference, see the comments at: https://stackoverflow.com/questions/49668252/returning-strings-in-tf-data-dataset-map-method this is also the Q&A that originally noted this problem.

### Source code / logs
To reproduce:
```
import tensorflow as tf

def map_fn(x):
    return x*2, 'foo'

dataset = tf.data.Dataset.range(5)
dataset = dataset.map(map_fn)
```

Error trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 790, in map
    return MapDataset(self, map_func)
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1597, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/username/tensorflow-remote/local/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1585, in tf_map_func
    ret, [t.get_shape() for t in nest.flatten(ret)])
AttributeError: 'str' object has no attribute 'get_shape'
```

**Comment by mrry** [comment] 2018-04-09 19:53
@jsimsa I think this regression crept in at 82fa1e1ae5b2f8af642979fafb1cab455db1882f, which added SparseTensor support, because the new logic assumes that all return values from a map function are either `tf.Tensor` or `tf.SparseTensor`, whereas the old logic had a conversion pass. Perhaps some variant of `convert_to_tensor_or_sparse_tensor()` is needed here?

**Comment by tensorflowbutler** [comment] 2018-04-24 18:41
Nagging Assignee @jsimsa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jsimsa** [comment] 2018-04-24 19:15
This has been fixed in https://github.com/tensorflow/tensorflow/commit/5a53c9b54d8781032ebf2cf26f93da3b2a33d1e4

**Closed by jsimsa** 2018-04-24 19:15 UTC
Labels: type:bug/performance
