### ISSUE TITLE
Tensorflow.summary.histogram produces wrong output

### ISSUE THREAD

**Issue by paloha** [tensorflow/tensorflow#36128] opened 2020-01-22 12:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
**Tested on my machine with Linux Ubuntu 16.04 and in Google Colab**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): 
**Installed with pip on my machine or using the one preinstalled in Colab**
- TensorFlow version (use command below): 
**v2.0.0-rc2-26-g64c3d38 2.0.0 on my machine or v2.1.0-rc1-0-g064e1535a7 2.1.0-rc1 in Colab**
- Python version: 
**3.5.2 on my machine or 3.6.9 in Colab**
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 
**run on CPU on my machine or run on CPU in Colab or run on GPU in 10.0, V10.0.130 in Colab (there seems to be no problem when running on GPU)**
- GPU model and memory: 
**no GPU on my machine or Colab GPU Tesla P100-PCIE-16GB**

**Describe the current behavior**
;tldr
`tensorboard.plugins.histogram.summary_v2._buckets` produces wrong result when run with CPU on arrays with more than approx. `7e7` elements.

Longer description:
I wanted to add a histogram of my model outputs (not only weights) to tensorboard using `tf.summary.histogram()` in a custom keras callback. All works, histogram is shown, but the values displayed are not correct. After I have inspected further, I found out that the function `tensorboard.plugins.histogram.summary_v2._buckets`, which is internally used in the `tf.summary.histogram()` produces wrong results for larger inputs. Namely it returns incorrect counts for some of the buckets. It is very simple to check this, because the size of the data should equal the sum of counts, which are stored in the first column of the `_buckets` output. For larger arrays, this is not true.

Wierdly, the discrepancy seems to occur only when the code is run on CPU. On the GPU, the histogram is correct (up to some tiny difference - missing one or two elements). But I can not check larger arrays than `100e6`, because running in Colab on GPU gives an error when calling `_buckets()`: 
`InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:GPU:0 to /job:localhost/replica:0/task:0/device:CPU:0 in order to run LinSpace: GPU sync failed [Op:LinSpace]`

Description of each step is in Gist along with the code.

**Describe the expected behavior**
Expected behavior of `tensorboard.plugins.histogram.summary_v2._buckets` would be to produce the correct counts of elements in a specific bucket for all sizes of data.

**Code to reproduce the issue**

Simplified code:
```python
import numpy as np
from tensorboard.plugins.histogram.summary_v2 import _buckets
# Create random data
data = np.random.standard_normal(int(100e6)).astype(np.float16)
# Compute the histogram with tf
tfhist = _buckets(data, bucket_count=20)
counts_tf = tfhist[:,2] # Counts are in the last column
edges_tf = tfhist[:,0] # Edges are in the first column
np.equal(np.sum(counts_tf), data.size)  # If false, there is a bug
```

Full example in Gist (can be run in Colab): https://gist.github.com/paloha/d079aa9afb832b996657fb97a2763a47#file-tensorflow-produces-wrong-histogram-ipynb

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I think that the error I get when running the gist on GPU in Colab (mentioned above) should be addressed as well.

**Comment by sushreebarsa** [comment] 2021-05-30 16:18
Was able to reproduce the issue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/91f7f61b529333de15400cc86a38f6ea/untitled125.ipynb#scrollTo=hkhqnkaBBnJm)..Thanks !

**Comment by nfelt** [comment] 2021-09-02 22:57
Thank you very much for filing this issue with such a detailed and comprehensive reproduction!  I apologize for the long delay in actually investigating this further.

I've done more of a deep dive in this colab of my own: https://gist.github.com/nfelt/0ae51ba3eb901b3438d9eab9a7ca4d16

To summarize my conclusions:

- A) The main problem you identified, with a large number of entirely missing counts, is due to bin counts effectively being truncated at 2^24 (= 16,777,216).  This is due to the way the bin counts are constructed as a sum of 1's, where the summation inadvertently was using float32, and simple accumulation in float32 results in numerical instability because integer values past 2^24 are not exactly representable: https://github.com/tensorflow/tensorflow/issues/51419
    - The reason you would only have seen this for larger arrays is because they needed to be large enough to have over 2^24 values falling into a single bin in order to manifest the effect.
    - My operating assumption is that the GPU kernel for summation doesn't have the same numerical instability issues due to a different implementation, and thus didn't result in truncation (or perhaps only did so at much higher counts)
    
- As part of digging into this, I also noticed:
   - B) some much smaller correctness issues around the handling of bin edge boundaries when floating point values in the input are very close to the bin edge. This shouldn't affect the overall count, but could mean individual bin counts are still not entirely correct in certain relatively rare cases.
   - C) The actual bin edges computed by TF are different than Numpy for float16 data because of different linspace computations (TF uses float64 arithmetic, Numpy uses float64 and then rounds back to float16).  I don't think this is really a correctness issue since either choice is defensible, but it's easy to conflate with the issue in B so worth noting for that reason.

We should be able to fix at least issue (A) relatively easily.  Unfortunately until we do that fix, there is no particularly good workaround other than avoiding generating bin counts that exceed 2^24 (e.g. perhaps use more bins to keep the count in each bin smaller).

**Comment by paloha** [comment] 2021-09-20 11:11
Thank you @nfelt for getting back to this issue, I was wondering if somebody picks it up eventually. Good job in the [gist](https://gist.github.com/nfelt/0ae51ba3eb901b3438d9eab9a7ca4d16) and thx for the conclusions. :clap:

**Comment by yatbear** [comment] 2021-10-01 13:35
Hi @paloha, the fix for this (`A` in Nick's [comment](https://github.com/tensorflow/tensorflow/issues/36128#issuecomment-912115542) above)  (https://github.com/tensorflow/tensorboard/pull/5337) is merged and now in tb-nightly.

**Comment by sushreebarsa** [comment] 2021-10-04 10:31
@paloha, Could you please let us know if we can close the issue as the [PR](https://github.com/tensorflow/tensorboard/pull/5348) is merged ? Thanks!

**Comment by tilakrayal** [comment] 2023-04-27 06:51
@paloha,
The respective PR's for the mentioned issue was merged https://github.com/tensorflow/tensorboard/pull/5337 and https://github.com/tensorflow/tensorboard/pull/5348. Also I tried to execute the code on tf-nightly 2.13.0 dev-20230417 with the expected output **TRUE**. 
<img width="564" alt="image (8)" src="https://user-images.githubusercontent.com/81610181/234782371-b424daf3-f8a2-4a5d-8efe-df79a5dece6f.png">

Thank you!

**Comment by paloha** [comment] 2023-05-02 09:15
@tilakrayal
Thanks for fixing the issue and testing it. In my opinion @nfelt should decide whether to close this issue or not as he has deeper understanding of what is going on and what needs to be fixed and where.

**Comment by tilakrayal** [comment] 2023-05-17 12:05
@nfelt,
The related PR #https://github.com/tensorflow/tensorboard/pull/5337 was merged and also as mentioned here the output was also as expected. Could you please confirm whether the issue still persists? Attached  the screen shot for the reference. 
https://github.com/tensorflow/tensorflow/issues/36128#issuecomment-1524887895
Thank you!

**Comment by yatbear** [comment] 2023-05-17 12:58
Hi @tilakrayal,

nfelt is out of office right now. I also worked on the histogram changes and I can confirm that this issue can be closed. Thank you!

**Closed** 2023-05-17 12:58 UTC
Labels: comp:tensorboard, stat:awaiting response, stat:awaiting tensorflower, type:bug, TF 2.1
