### ISSUE TITLE
Want to save this training weight by epoch

### ISSUE THREAD

**Issue by BeccaHuang** [tensorflow/tensorflow#49938] opened 2021-06-01 05:54 UTC
https://github.com/lancerane/Adversarial-domain-adaptation/blob/master/Domain%20adaptation,%20TF2.0.ipynb

Thanks Oscar Bennett provide this code, but i don't know how to save this weight then test another data.
And if can train supervise val loss  to learn avoid overfitting.
Because this model DANN have three part and i can't use keras save weight, Can u give me some direction?
---------------
EPOCHS = 100

alpha = 1
for epoch in range(EPOCHS):
  reset_metrics()
  
  for domain_data, label_data in zip(domain_train_ds, train_ds):
    
    try:
      train_step(label_data[0], label_data[1], domain_data[0], domain_data[1], alpha=alpha)
     
    #End of the smaller dataset
    except ValueError: 
      pass
    
  for test_data, m_test_data in zip(test_ds,mnist_m_test_ds):
    test_step(test_data[0], test_data[1], m_test_data[0], m_test_data[1])
  
  template = 'Epoch {}, Train Accuracy: {}, Domain Accuracy: {}, Source Test Accuracy: {}, Target Test Accuracy: {}'
  print (template.format(epoch+1,
                         train_accuracy.result()*100,
                         conf_train_accuracy.result()*100,
                         test_accuracy.result()*100,
                         m_test_accuracy.result()*100,))
-----------------------------

**Comment by BeccaHuang** [comment] 2021-06-01 13:34
https://core.ac.uk/download/pdf/228291159.pdf P41
have a way but is keras save weight,
i don't know how to do save weight  tensorflow.

**Comment by tilakrayal** [comment] 2021-06-02 04:30
@BeccaHuang ,

Please take a look at this links for information on keras.[Link1](https://stackoverflow.com/questions/47266383/save-and-load-weights-in-keras),[Link2](https://stackoverflow.com/questions/57152978/keras-how-to-save-models-or-weights),[Link3](https://www.tensorflow.org/guide/keras/save_and_serialize).

Thanks!

**Comment by tilakrayal** [comment] 2021-06-02 04:31
@BeccaHuang ,

Please post this question in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by BeccaHuang** [comment] 2021-06-02 05:18
Thank you, give me direction ,I already post this quenstion  in StackOverflow.
Best regards

**Comment by luozhouyang** [comment] 2021-06-02 08:57
You can use `tf.train.Checkpoint` to save model's weights. If you use `keras`, you can add a `ModelCheckpoint` callback.

**Comment by tilakrayal** [comment] 2021-06-02 09:10
@BeccaHuang ,

Please look at @luozhouyang  comment, provided links and let us know if the issue got resolved.

Please feel free to close this issue and track in StackOverflow as this is not bug or feature request.Thanks!

**Comment by zyberg2091** [comment] 2021-06-02 16:19
In keras you can use `ModelCheckpoint` :

for example-
```
checkpoint_path='weights.{epoch:02d}-{loss:0.2f}.h5'

checkpoint= tf.keras.callbacks.ModelCheckpoint(
    checkpoint_path,
    monitor="val_loss",
    verbose=0,
    save_best_only=False,
    save_weights_only=True,
    mode="auto",
    save_freq="epoch",
    options=None,)
```

Here you can monitor your metrics and you can resume your training at any time from your previous checkpoint.

for example-

Loading checkpoint:
```
if checkpoint_path is not None :
 model.load_weights('weights.03-0.66.h5')   #Here 3 is the epoch number and 0.66 is the loss of the last checkpoint saved
 Finding the epoch index from which we are resuming
 initial_epoch = 3
else:
 initial_epoch = 0
```


While doing custom training you can use `tf.train.Checkpoint` as mentioned by @luozhouyang  which tracks the latest weights and you can save it in each iteration easily.

**Comment by BeccaHuang** [comment] 2021-06-07 08:16
Hi luozhouyang and shubhamkr,

Thank your replay,
I try these advise many days, but i still confuse because my try model is combite three part,
Can't use history= model.fit(...)   then i don't know how to use checkpoint in each epoch.

Often need to definition model , but if three part how can i  definition combite one model?

Try code dann↘   Domain confusion and Adversarial loss
https://github.com/lancerane/Adversarial-domain-adaptation/blob/master/Domain%20adaptation,%20TF2.0.ipynb

The expression may not be clear, hope you can understand! ><"

**Comment by luozhouyang** [comment] 2021-06-07 11:05
Here is an official tutorial [tf.train.Checkpoint](https://www.tensorflow.org/guide/checkpoint)

**Comment by BeccaHuang** [comment] 2021-06-07 11:18
Thanks @luozhouyang,
The official tutorial model is  a simple linear model   "net = Net()"  [just one part]
but my model have three part build a model,
i don't know how to use this by dann  model.

**Comment by luozhouyang** [comment] 2021-06-07 11:40
```python
ckpt = tf.train.Checkpoint(model_a=a, model_b=model_b, model_c=model_c, ...)
```

**Comment by BeccaHuang** [comment] 2021-06-10 09:05
Thanks @luozhouyang,
you give me direction, i try for tf.train.Checkpoint, get this error [ `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`)]

I already change  [tf.compat.v2.keras.optimizers.Adam] result same get error.
I don't know where get wrong

![image](https://user-images.githubusercontent.com/67473475/121496702-4c64eb80-ca0d-11eb-9972-b054a2ddb1e1.png)

**Comment by jvishnuvardhan** [comment] 2021-06-24 16:59
@BeccaHuang We generally not support debugging long codes. GitHub is mainly for bugs and performance related issues. If you think you find a bug, can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by BeccaHuang** [comment] 2021-06-24 17:23
Thanks jvishnuvardhan , i am sorry, because  i don't know how clear expression about my problem, I tried to re-expression.

In tensorflow2.0 how save and load weight ,about build adversarial neural network  model have two different optimizer, by epoch training, It's not model = tf.keras.Model(...) framework and can't model.fit,  can't tf.saved_model.save(model),how can i do?


 I use this to do train step→ [with tf.GradientTape(persistent=True) as tape], but i don't know how can i save weight?

**Comment by BeccaHuang** [comment] 2021-06-24 17:38
I try but i don't know how to use simple code to show.
Model Framework i try use @ofbennett DANN model code
about [with tf.GradientTape(persistent=True) as tape] train step
how can to save weight?

https://github.com/lancerane/Adversarial-domain-adaptation/blob/master/Domain%20adaptation,%20TF2.0.ipynb

**Closed** 2021-07-10 01:47 UTC
Labels: comp:keras, stalled, stat:awaiting response, type:support
