### ISSUE TITLE
tf.nn.embedding_lookup return NaN, i think it is not correct!

### ISSUE THREAD

**Issue by gitdavida** [tensorflow/tensorflow#24712] opened 2019-01-05 03:32 UTC
here is my test case code:
-----------------------------------start
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()
a = np.zeros([2,4,2],dtype=float)
out = tf.nn.embedding_lookup(a,[0],'div',None,-1)
-------------------------------------end
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12.0
- Python version:3.5
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
it returns :
[[[nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]]
**Describe the expected behavior**
when i study the source code in 
tensorflow/python/ops/embedding_ops.py
tensorflow/tensorflow/python/ops/clip_ops.py:line148-152
i think it should returns 
[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by hanayashiki** [comment] 2019-01-05 19:40
```
import tensorflow as tf
import numpy as np

config = tf.ConfigProto(
        device_count = {'GPU': 0}
    )
tf.enable_eager_execution(config=config)
a = np.zeros([2,4,2],dtype=float)
out = tf.nn.embedding_lookup(a,[0],'div',None,-1)

print(tf.__version__)
print(out)
```
```
1.11.0
tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(1, 4, 2), dtype=float64)
```
Guess I cannot reproduce.

**Comment by gitdavida** [comment] 2019-01-08 00:45
@hanayashiki   please try again with tensorflow version=1.12.0

**Comment by ymodak** [comment] 2019-01-08 06:14
@gitdavida I was able execute your code snippet successfully in TF 1.12.
1.12.0
tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(1, 4, 2), dtype=float64)

Can you please confirm it by running your code usinf google colab? Thanks!

**Comment by ymodak** [comment] 2019-01-11 23:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-01-11 23:56 UTC
Labels: comp:apis, stat:awaiting response

**Comment by loginaway** [comment] 2019-10-28 07:02
I came up with the same problem. Still have no idea about it. My environment is tensorflow-gpu 1.13, cuda 10.0, ubuntu 16.04
