### ISSUE TITLE
PYYAML not found

### ISSUE THREAD

**Issue by vipulroxx** [tensorflow/tensorflow#30110] opened 2019-06-25 06:57 UTC
Running ```yaml_string = model.to_yaml()``` on mac is giving me this error :
```
Traceback (most recent call last):
  File "check-keras.py", line 197, in <module>
    yaml_string = model.to_yaml()
  File "/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/network.py", line 1560, in to_yaml
    'Requires yaml module installed (`pip install pyyaml`).')
ImportError: Requires yaml module installed (`pip install pyyaml`)
```
When I run pip install, it says that the package already exists.
```
Vipuls-MacBook-Air:Keras vipulsharma$ pip install pyyaml
Requirement already satisfied: pyyaml in /Users/vipulsharma/Library/Python/2.7/lib/python/site-packages (5.1.1)
```

So I figured in the above terminal output
``` File "/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/network.py", line 1560,``` 

This version of Python is different than the version here :
```Requirement already satisfied: pyyaml in /Users/vipulsharma/Library/Python/2.7/lib/python/site-packages (5.1.1)```

So I tried installing yaml in 
```/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/```

 by doing a 
```pip install --target=/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/ pyyaml```

 It installed yaml in  ```/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/```  successfully, but when I run my Python file it gives me the same error.

How am I supposed to convert it to Yaml?

**Comment by wdirons** [comment] 2019-06-26 13:31
This question on the install of pyyaml is better asked in stackoverflow then here.

**Comment by ravikyram** [comment] 2019-06-28 05:09
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ravikyram** [comment] 2019-07-03 05:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-03 05:27 UTC
Labels: stat:awaiting response, type:support
