### ISSUE TITLE
Models having locally connected layers with implementation = 2 or 3 cannot be saved in SavedModel format.

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorflow#48584] opened 2021-04-17 07:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab, so binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7

**Describe the current behavior**
This issue is a continuation of #47689 . Whenever the user opts for `implementation=2` or `implementation=3`, the model cannot be saved as a SavedModel format.  

**Describe the expected behavior**
One should be able to save it as SavedModel format.

**Standalone code to reproduce the issue**
Please see the gist [here](https://colab.research.google.com/gist/AdityaKane2001/c74692d463f14517d84ee9be9443941d/tfpr_maker.ipynb).

**Other info**
I have played around a bit with the source code in the colab environment. I have inserted many `logging_ops.print_v2(...)` statements to make it easier to debug. Also, I have cloned my fork (it's a clean fork, no personal commits) and ran the `local_test.py` file. I have added `model_2.save('model2')` line, too check for the issue.

**Some observations:**
1. The `local.py`  file has no errors (none that I found). But many function calls can be updated as they are deprecated.
2. The `K.reshape` or `array_ops.reshape` calls are the ones that are causing the issue. There's some bug in  `tensorflow/python/framework/op_def_library.py  : _apply_op_helper(op_type_name, name=None, **keywords)` function. 
3. Note that `local.py: 790` calls `reshape`, which calls `gen_array_ops.reshape`, which calls `op_def_library._apply_op_helper`. But the arguments that go to the latter **were not recorded in `**keywords` argument.**  I checked that by printing the keywords dict in the error message. 

Please take a look at the error log under local_test.py execution cell in the colab notebook.
Thanks.

**Comment by bhack** [comment] 2021-04-17 15:59
> Note that local.py: 790 calls reshape, which calls gen_array_ops.reshape, which calls op_def_library._apply_op_helper. But the arguments that go to the latter were not recorded in **keywords argument. I checked that by printing the keywords dict in the error message.

It is that in_dims and out_dims have shape `shape=(3,)` so then in_size/out_size is shape=(). 

```
  in_size = math_ops.reduce_prod(in_dims)
  out_size = math_ops.reduce_prod(out_dims)
```

**Comment by AdityaKane2001** [comment] 2021-04-17 16:02
@bhack 
Can you please elaborate on that?

**Comment by bhack** [comment] 2021-04-17 16:04
In `local.py` add a print yourself:

```
  in_size = math_ops.reduce_prod(in_dims)
  out_size = math_ops.reduce_prod(out_dims)
  print("== Shape in ==" + str(in_size))
  print("== Shape out ==" + str(out_dims))
  return array_ops.reshape(tensor, (in_size, out_size))
```

**Comment by AdityaKane2001** [comment] 2021-04-17 16:07
Got it, will look into it

**Comment by bhack** [comment] 2021-04-17 16:07
P.s. I fixed a type

**Comment by AdityaKane2001** [comment] 2021-04-17 16:44
@bhack 
I understood that in `make_2d` function we are facing empty arrays. But then why in the test error logs we see that the error is on some other line, and not that one?

**Comment by bhack** [comment] 2021-04-17 17:30
> Note that local.py: 790 calls reshape, which calls gen_array_ops.reshape, which calls op_def_library._apply_op_helper. But the arguments that go to the latter were not recorded in **keywords argument. I checked that by printing the keywords dict in the error message.

I was just commenting your point 3. Isn't that line?

**Comment by AdityaKane2001** [comment] 2021-04-17 17:32
Yes, that's the one. 
My question is, how do we pinpoint where the bug is? Where are we calling the `reshape` that has argument `shape` which has `None` in it?

**Comment by bhack** [comment] 2021-04-17 19:56
The problem is that on save the layer `def call(self, inputs):` called with `inputs.shape` `(None, None, None, 1)` instead of `(None, 28, 28, 1)`. As in `implementation == 2` and `3` we have always `self.compute_output_shape(inputs.shape)` we will get the error for `(None, None, None, 1)`.

**Comment by bhack** [comment] 2021-04-28 00:41
@AdityaKane2001 is this a duplicate of https://github.com/tensorflow/tensorflow/issues/47689 or there is something new?

**Comment by AdityaKane2001** [comment] 2021-04-28 04:33
@bhack 
Yes, this is a duplicate, but I had added some observations.

**Comment by AdityaKane2001** [comment] 2021-05-05 09:24
@bhack 
Frankly, I don't have any idea how to proceed from here. I had read the related code and tried to understand it, but I couldn't identify what changes were required. How can we proceed from here?

**Comment by ashutosh1919** [comment] 2021-05-17 12:49
@bhack , @AdityaKane2001 - Please consider looking at the detailed description in the PR #49230 and provide your feedback.

**Closed** 2021-05-25 19:43 UTC
Labels: TF 2.4, comp:keras, stat:awaiting tensorflower, type:bug
