### ISSUE TITLE
Support python3.6 Linux

### ISSUE THREAD

**Issue by BL4CKvGHOST** [tensorflow/tensorflow#15311] opened 2017-12-12 13:02 UTC
Python3.6 support Linux

**Comment by facaiy** [comment] 2017-12-12 13:26
https://www.tensorflow.org/install/install_linux#python_36 ?

**Comment by angersson** [comment] 2017-12-12 23:09
Dupe of #6533 (which was closed after Python 3.6 support was added)

**Closed by angersson** 2017-12-12 23:09 UTC
