### ISSUE TITLE
Unable to register cuDNN factory, cuFFT factory, and cuBLAS factory

### ISSUE THREAD

**Issue by MohannadAbuIssa** [tensorflow/tensorflow#70947] opened 2024-07-06 17:05 UTC
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TensorFlow Version: 2.15.0

### Custom code

No

### OS platform and distribution

OS Version: #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC

### GPU model and memory

RTX4000

### Current behavior?

Cannot utilize my GPU to run TF

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

```shell
2024-07-06 15:47:43.180939: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-06 15:47:43.181095: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-06 15:47:43.345276: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-06 15:47:43.613629: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-06 15:47:45.645686: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
```

**Comment by sushreebarsa** [comment] 2024-07-08 07:17
@MohannadAbuIssa Could you ensure that the correct versions of CUDA and cuDNN compatible with your TensorFlow version are installed? Also Please make sure that your NVIDIA drivers are up to date.
Thank you!

**Comment by vladbelit** [comment] 2024-07-09 18:52
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/62075

**Comment by anilbey** [comment] 2024-07-28 11:32
This issue is better not closed because it still exists

**Comment by belitskiy** [comment] 2024-07-29 14:44
Closing as it's a duplicate of https://github.com/tensorflow/tensorflow/issues/62075

**Closed by belitskiy** 2024-07-29 14:44 UTC
Labels: type:build/install, subtype: ubuntu/linux, TF 2.15
