### ISSUE TITLE
cmake compile error C2678: binary '*': no operator found sparse_column_iterable.cc

### ISSUE THREAD

**Issue by vldbnc** [tensorflow/tensorflow#15925] opened 2018-01-07 12:22 UTC
`cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/ProgramData/chocolatey/bin/swig.exe -DPYTHON_EXECUTABLE=C:/Python36/python.exe -DPYTHON_LIBRARIES=C:/Python36/libs/python36.lib -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2 `

```
c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const tensorflow::boosted_trees::utils::`anonymous-namespace'::IndicesRowIterator' (or there is no acceptable conversion) (compiling source file D:\_working_dir\_ml\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc) [D:\_working_dir\_ml\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
  c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\algorithm(2417): error C2100: illegal indirection (compiling source file D:\_working_dir\_ml\tensorflow\tensorflow\contrib\boosted_trees\lib\utils\sparse_column_iterable.cc) [D:\_working_dir\_ml\tensorflow\tensorflow\con
trib\cmake\build\tf_core_kernels.vcxproj]
```
Windows 8.1 x64
cmake 3.10.1
swig 3.0.9
Visual Studio 2017 Community

the same problem asked
https://stackoverflow.com/questions/48058113/compiling-tensorflow-1-4-on-windows-10

**Comment by tensorflowbutler** [comment] 2018-01-08 00:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vksbhandary** [comment] 2018-01-08 16:07
@vldbnc I encountered same error while trying to build arch:AVX pip file. I couldn't say for sure but re-installing Visual Studio 2017 might help.

I was able to build arch:AVX version of pip file only after cleaning all [Visual studio](https://github.com/Microsoft/VisualStudioUninstaller) components and reinstalling [MSVC 2015 update 3](https://www.tensorflow.org/install/install_sources). MSVC 2015 update 3 setup cant compile arch:AVX2 pip because of header file [issue](https://github.com/tensorflow/tensorflow/issues/10199). 

But you can try it as @aluo-x  has build it successfully using VS2017 15.4
Here is [link](https://github.com/aluo-x/tensorflow_windows/blob/master/working/tensorflow-1.4.0-cp36-cp36m-win_amd64.whl) to .whl file which you are trying to build.  
(I am using this file and its working fine.)

Maybe @aluo-x can in this error.

**Comment by CarltonSemple** [comment] 2018-01-08 22:22
I'm running into the same issue.
Windows 10 x64, using the 64-bit MSBuild (not the default for some reason)
cmake 3.9.2
swig 3.0.12
Visual Studio 2017 community.

I'll try @vksbhandary 's suggestion and update

**Comment by vldbnc** [comment] 2018-01-09 09:56
@vksbhandary I'm using @aluo-x whl file and it's working.
Missing support of AVX2 instruction set in MSCV2015 and some compiling error made me install MSCV2017 based on discussion [10199](https://github.com/tensorflow/tensorflow/issues/10199) but I ran into this issue. Thanks for suggestion, I will try to re-install and build again with VS2017 15.4 toolset.

**Comment by Michael-4** [comment] 2018-01-09 12:54
The problem is that in Visual Studio 2017 the std::lower_bound() function internally creates a const object of the iterator for which it then calls operator*(). However, IndicesRowIterator does not define this for const objects, which results in the error the compiler is giving you.
You could fix this by adding const to

`reference operator*() { return iter_->ix()(row_idx_, 0); }, `

i.e.

`reference operator*() const { return iter_->ix()(row_idx_, 0); }`

As the ix() function is defined as const this should be no problem.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:05
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by vksbhandary** [comment] 2018-01-24 07:20
@Michael-4 's [comment](#issuecomment-356275963) provides the fix for building pip file on Windows using VS 2017. I was able to built tensorflow 1.5rc with AVX2 as SMID option. So this issue can be closed.

**Comment by reedwm** [comment] 2018-01-30 19:59
Closing since it looks like this is fixed on the master branch.

**Closed by reedwm** 2018-01-30 19:59 UTC

**Comment by dtarakanov1** [comment] 2019-06-06 16:29
Could you please reopen the issue?

This is _not_ fixed in the master branch: https://github.com/tensorflow/tensorflow/blob/054cf11347dc19a1bd2ec2b09ac4c71dc0f8ee8f/tensorflow/core/framework/op_kernel.h#L455

And the mentioned above fix works.
