### ISSUE TITLE
Tensorflow matmul of float64's behaves like numpy float32 matmul

### ISSUE THREAD

**Issue by PCerles** [tensorflow/tensorflow#28811] opened 2019-05-17 21:06 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: Titan Xp

**Describe the current behavior**
Multiplying two tf.float64s together is giving me a substantial error over multiplying two np.float64s together. 

**Describe the expected behavior**
np.matmul(a, b) should be very close to tf.matmul(a, b) when a, b are both float64s. This issue is compounding over a spectrogram preprocessing pipeline making tensorflow unusable for pushing my signal preprocessing from numpy into tensorflow. 

**Code to reproduce the issue**
```
a = tf.placeholder(tf.float64, [None, None])
b = tf.placeholder(tf.float64, [None, None])

res_tf = tf.matmul(a, b)

in1 = np.random.uniform(size=(998, 257))
in2 = np.random.uniform(size=(257, 80))

print(in1.dtype)
print(in2.dtype)

numpy_result_f64 = np.matmul(in1, in2)
numpy_result_f32 = np.matmul(in1.astype(np.float32), in2.astype(np.float32))

with tf.Session() as sess:
    tensorflow_result = sess.run(res_tf, feed_dict={a: in1, b: in2})
    
print(((numpy_result_f64 - tensorflow_result) / numpy_result_f64).max())
print(((numpy_result_f32 - tensorflow_result) / numpy_result_f32).max())
```
Out:
```
float64
float64
0.16405904009391822
9.08087494225598e-07
```
This has the same issue whether the code is run on GPU or CPU. 

This issue does not appear on tf 1.12.

**Comment by muddham** [comment] 2019-05-20 08:15
@PCerles Able to reproduce the issue with the code provided here

float64
float64
2.1063637390863436e-15
9.67467215661267e-07

**Comment by jvishnuvardhan** [comment] 2019-05-28 22:23
@PCerles My output is different from yours. My output shows that tensorflow `matmul` of float64 behaves like numpy's float64 matmul than numpy's float32 matmul.

Please take a look at the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/819210b965e4007df38b405e416079dd/untitled201.ipynb). This gist has your code and my output. I have tried gpu and cpu, both produce results as expected. Thanks!

Output is as follows
```
1.966516285169991e-15
9.296283790026668e-07
```

**Comment by jvishnuvardhan** [comment] 2019-06-06 21:07
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-06-06 21:07 UTC
Labels: TF 1.13, comp:ops, stat:awaiting response, type:bug/performance
