### ISSUE TITLE
Strange behavior of tensorflow.python.ops.gen_data_flow_ops.dynamic_stitch when running from different environments

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59085] opened 2023-01-04 07:06 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
A very strange behavior when running .python.ops.gen_data_flow_ops.dynamic_stitch. I get different output when running from different environments. Log message from different environments:

When running from linux terminal:

```
Segmentation fault
```

When running from colab:

```
Error:{{function_node __wrapped__DynamicStitch_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] is out of range [Op:DynamicStitch]
```
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_data_flow_ops

try:
    arg_0_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
    arg_0_0 = tf.identity(arg_0_0_tensor)
    arg_0_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
    arg_0_1 = tf.identity(arg_0_1_tensor)
    arg_0 = [
        arg_0_0,
        arg_0_1,
    ]
    arg_1_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
    arg_1_0 = tf.identity(arg_1_0_tensor)
    arg_1_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
    arg_1_1 = tf.identity(arg_1_1_tensor)
    arg_1 = [
        arg_1_0,
        arg_1_1,
    ]
    out = gen_data_flow_ops.dynamic_stitch(
        arg_0,
        arg_1,
    )
except Exception as e:
    print("Error:" + str(e))

```

```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_data_flow_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_0_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
      arg_0_0 = tf.identity(arg_0_0_tensor)
      arg_0_1_tensor = tf.random.uniform([1], minval=-256, maxval=257, dtype=tf.int32)
      arg_0_1 = tf.identity(arg_0_1_tensor)
      arg_0 = [arg_0_0,arg_0_1,]
      arg_1_0_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
      arg_1_0 = tf.identity(arg_1_0_tensor)
      arg_1_1_tensor = tf.random.uniform([1], minval=-256, maxval=257, dtype=tf.int32)
      arg_1_1 = tf.identity(arg_1_1_tensor)
      arg_1 = [arg_1_0,arg_1_1,]
      out = gen_data_flow_ops.dynamic_stitch(arg_0,arg_1,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0_0 = tf.identity(arg_0_0_tensor)
      arg_0_0 = tf.cast(arg_0_0, tf.int32)
      arg_0_1 = tf.identity(arg_0_1_tensor)
      arg_0_1 = tf.cast(arg_0_1, tf.int32)
      arg_0 = [arg_0_0,arg_0_1,]
      arg_1_0 = tf.identity(arg_1_0_tensor)
      arg_1_0 = tf.cast(arg_1_0, tf.int32)
      arg_1_1 = tf.identity(arg_1_1_tensor)
      arg_1_1 = tf.cast(arg_1_1, tf.int32)
      arg_1 = [arg_1_0,arg_1_1,]
      gen_data_flow_ops.dynamic_stitch(arg_0,arg_1,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment] 2023-01-04 15:07
Hi @nimashiri ,
The difference in behaviour is due to colab runtime CPU vs GPU.

 I tested the code in colab with CPU runtime and found the error: `Error:{{function_node _wrapped__DynamicStitch_N_2_device/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] is out of range [Op:DynamicStitch]` as mentioned by you. Please refer attached [cpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/865f5c076a5205ee07fcd8e775c45a76/59085-cpu.ipynb#scrollTo=CCIqZI2TJW0Q)

But with GPU runtime the colab session crashed with Warning log below:
`2023-01-04 14:54:07.475973: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0`.
Please refer [gpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/6815063ff3e112ffe3c814495b141453/59085_gpu.ipynb).

I tested the same from Ubuntu terminal and it gives `segmentation fault (core dumped)` as attached below.
<img width="1502" alt="Screenshot 2023-01-04 at 8 19 38 PM" src="https://user-images.githubusercontent.com/116063290/210584909-8ce8c11a-2462-411b-bb56-3d16c3e23814.png">

**Comment by nimashiri** [comment] 2023-01-04 23:13
> Hi @nimashiri , The difference in behaviour is due to colab runtime CPU vs GPU.
> 
> I tested the code in colab with CPU runtime and found the error: `Error:{{function_node _wrapped__DynamicStitch_N_2_device/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] is out of range [Op:DynamicStitch]` as mentioned by you. Please refer attached [cpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/865f5c076a5205ee07fcd8e775c45a76/59085-cpu.ipynb#scrollTo=CCIqZI2TJW0Q)
> 
> But with GPU runtime the colab session crashed with Warning log below: `2023-01-04 14:54:07.475973: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0`. Please refer [gpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/6815063ff3e112ffe3c814495b141453/59085_gpu.ipynb).
> 
> I tested the same from Ubuntu terminal and it gives `segmentation fault (core dumped)` as attached below. <img alt="Screenshot 2023-01-04 at 8 19 38 PM" width="1502" src="https://user-images.githubusercontent.com/116063290/210584909-8ce8c11a-2462-411b-bb56-3d16c3e23814.png">

Ok thanks. Same behavior here.

**Comment by nimashiri** [comment] 2023-01-22 16:18
> Hi @nimashiri , The difference in behaviour is due to colab runtime CPU vs GPU.
> 
> I tested the code in colab with CPU runtime and found the error: `Error:{{function_node _wrapped__DynamicStitch_N_2_device/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] is out of range [Op:DynamicStitch]` as mentioned by you. Please refer attached [cpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/865f5c076a5205ee07fcd8e775c45a76/59085-cpu.ipynb#scrollTo=CCIqZI2TJW0Q)
> 
> But with GPU runtime the colab session crashed with Warning log below: `2023-01-04 14:54:07.475973: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0`. Please refer [gpu-gist](https://colab.research.google.com/gist/SuryanarayanaY/6815063ff3e112ffe3c814495b141453/59085_gpu.ipynb).
> 
> I tested the same from Ubuntu terminal and it gives `segmentation fault (core dumped)` as attached below. <img alt="Screenshot 2023-01-04 at 8 19 38 PM" width="1502" src="https://user-images.githubusercontent.com/116063290/210584909-8ce8c11a-2462-411b-bb56-3d16c3e23814.png">

Also this one:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_data_flow_ops
try:
  arg_0_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
  arg_0_0 = tf.identity(arg_0_0_tensor)
  arg_0_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_0_1 = tf.identity(arg_0_1_tensor)
  arg_0 = [arg_0_0,arg_0_1,]
  arg_1_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
  arg_1_0 = tf.identity(arg_1_0_tensor)
  arg_1_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_1_1 = tf.identity(arg_1_1_tensor)
  arg_1 = [arg_1_0,arg_1_1,]
  out = gen_data_flow_ops.dynamic_stitch(arg_0,arg_1,)
except Exception as e:
  print("Error:"+str(e))
```

**Comment by nimashiri** [comment] 2023-01-22 22:49
This test case also caused segfault:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_data_flow_ops
try:
  arg_0_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
  arg_0_0 = tf.identity(arg_0_0_tensor)
  arg_0_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_0_1 = tf.identity(arg_0_1_tensor)
  arg_0 = [arg_0_0,arg_0_1,]
  arg_1_0_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
  arg_1_0 = tf.identity(arg_1_0_tensor)
  arg_1_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_1_1 = tf.identity(arg_1_1_tensor)
  arg_1 = [arg_1_0,arg_1_1,]
  out = gen_data_flow_ops.dynamic_stitch(arg_0,arg_1,)
except Exception as e:
  print("Error:"+str(e))
```

**Comment by sachinprasadhs** [comment] 2023-01-24 18:59
Hi, We are looking to fix these types of issues in a generic way than fixing it in a OP/API specific.
This issue is happening due to the GPU kernel launch when the input Tensors are empty, which we are trying to address. Thanks for creating the issue.

**Comment by mihaimaruseac** [comment] 2023-02-07 19:51
@learning-to-play

**Comment by sachinprasadhs** [comment] 2023-02-16 21:09
Hi, The error which you are seeing in the colab is working as intended, the fix for this has been implemented in the PR here https://github.com/tensorflow/tensorflow/commit/ee004b18b976eeb5a758020af8880236cd707d05.
Thanks!

**Closed** 2023-02-17 16:31 UTC
Labels: stat:awaiting response, type:bug, comp:ops, TF 2.11
