### ISSUE TITLE
ppc64le: //tensorflow/python/kernel_tests:matrix_exponential_op_test fails

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#21960] opened 2018-08-29 21:18 UTC
Please assign this issue to me

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  Master branch from 8/29 (065f9b833ffbb3b2f03d63febb186275674ba133)
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: 4 V100 GPUs with 16 GB of memory each
- **Exact command to reproduce**: 
bazel test --config=cuda --test_tag_filters=-no_oss,-oss_serial,-no_gpu,-benchmark-test --test_timeout 300,450,1200,3600 --local_test_jobs=4 --test_output=errors --build_tests_only //tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/python/kernel_tests:matrix_exponential_op_test

### Describe the problem
testL1Norms_complex128_3_2500 in matrix_exponential_op_test fails with a slight difference:
not close lhs =  [14.19404]
not close rhs =  [14.191119]

### Source code / logs
```
======================================================================
FAIL: testL1Norms_complex128_3_2500 (__main__.ExponentialOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/matrix_exponential_op_test.py", line 234, in Test
    self._verifyExponentialReal(scale * matrix)
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/matrix_exponential_op_test.py", line 68, in _verifyExponentialReal
    self._verifyExponential(x, np_type)
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/matrix_exponential_op_test.py", line 64, in _verifyExponential
    self.assertAllClose(np_ans, out, rtol=1e-4, atol=1e-3)
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1443, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1413, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/home/wdirons/upstream/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python                      /kernel_tests/matrix_exponential_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1348, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg=msg, equal_nan=True)
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.5/dist-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0.001
Mismatched value: a is different from b.
(mismatch 5.555555555555557%)
 x: array([[[  4.719045,   3.237183,  -1.798661],
        [  5.548645,   3.793037,  -2.115632],
        [ -5.977193,  -4.089234,   2.273146]],...
 y: array([[[  4.719063,   3.237082,  -1.798567],
        [  5.548592,   3.793213,  -2.115799],
        [ -5.977084,  -4.089204,   2.273036]],...

----------------------------------------------------------------------
Ran 5 tests in 5.153s

FAILED (failures=1)
<class 'numpy.complex128'> (2, 3, 3) 25.0 [[[-0.25091976+0.j  0.90142861+0.j  0.46398788+0.j]
  [ 0.19731697+0.j -0.68796272+0.j -0.68801096+0.j]
  [-0.88383278+0.j  0.73235229+0.j  0.20223002+0.j]]

 [[ 0.41614516+0.j -0.95883101+0.j  0.9398197 +0.j]
  [ 0.66488528+0.j -0.57532178+0.j -0.63635007+0.j]
  [-0.63319098+0.j -0.39151551+0.j  0.04951286+0.j]]]
not close where =  (array([1]), array([2]), array([2]))
not close lhs =  [14.19404]
not close rhs =  [14.191119]
not close dif =  [0.0029211]
not close tol =  [0.00241911]
dtype = float32, shape = (2, 3, 3)
<class 'numpy.complex64'> (2, 3, 3) 5.0 [[[-0.25091976+0.j  0.90142864+0.j  0.4639879 +0.j]
  [ 0.19731697+0.j -0.6879627 +0.j -0.68801093+0.j]
  [-0.88383275+0.j  0.7323523 +0.j  0.20223002+0.j]]

 [[ 0.41614515+0.j -0.958831  +0.j  0.9398197 +0.j]
  [ 0.6648853 +0.j -0.5753218 +0.j -0.6363501 +0.j]
  [-0.633191  +0.j -0.39151552+0.j  0.04951286+0.j]]]
<class 'numpy.float64'> (2, 3, 3) 6.0 [[[-0.25091976  0.90142861  0.46398788]
  [ 0.19731697 -0.68796272 -0.68801096]
  [-0.88383278  0.73235229  0.20223002]]

 [[ 0.41614516 -0.95883101  0.9398197 ]
  [ 0.66488528 -0.57532178 -0.63635007]
  [-0.63319098 -0.39151551  0.04951286]]]
================================================================================

FAILED: //tensorflow/python/kernel_tests:matrix_exponential_op_test (Summary)
```

**Comment by tensorflowbutler** [comment] 2018-09-13 12:43
Nagging Assignee @wdirons: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-26 23:42
@wdirons I just tried this now, with cuda 9.1, but I cannot reproduce the problem.
Running this command got an all passing result for me:
bazel test --config=cuda tensorflow/python/kernel_tests:matrix_exponential_op_test --local_test_jobs=1 --runs_per_test=100

I will close this issue now, please reopen if you are still seeing it.

**Closed by gunan** 2018-09-26 23:42 UTC

**Comment by wdirons** [comment] 2018-09-27 22:39
This is still failing on ppc64le. I'll try more variations to see if I can isolate the problem.
