### ISSUE TITLE
UnicodeDecodeError: "utf-8" codec can't decode byte in position : invalid start byte

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#37950] opened 2020-03-26 18:45 UTC
**System information** 

- OS Platform and Distribution : ubuntu 18.04
the issue happens on mobile device: 
- TensorFlowinstalled with pip3  : v1.14.0

I generate my own dataset .tfrecord with that modify code:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import hashlib
import io
import logging
import os

from lxml import etree
import PIL.Image
import tensorflow as tf

from object_detection.utils import dataset_util
from object_detection.utils import label_map_util


flags = tf.app.flags
flags.DEFINE_string('data_dir', '', 'Root directory to raw PASCAL VOC dataset.')
flags.DEFINE_string('set', 'train', 'Convert training set, validation set or '
                    'merged set.')
flags.DEFINE_string('annotations_dir', 'Annotations',
                    '(Relative) path to annotations directory.')
flags.DEFINE_string('year', 'VOC2007', 'Desired challenge year.')
flags.DEFINE_string('output_path', '', 'Path to output TFRecord')
flags.DEFINE_string('label_map_path', 'data/pascal_label_map.pbtxt',
                    'Path to label map proto')
flags.DEFINE_boolean('ignore_difficult_instances', False, 'Whether to ignore '
                     'difficult instances')
FLAGS = flags.FLAGS

SETS = ['train', 'val', 'trainval', 'test']
YEARS = ['VOC2007', 'VOC2012', 'merged']


def dict_to_tf_example(data,
                       dataset_directory,
                       label_map_dict,
                       ignore_difficult_instances=False,
                       image_subdirectory='JPEGImages'):
  """Convert XML derived dict to tf.Example proto.

  Notice that this function normalizes the bounding box coordinates provided
  by the raw data.

  Args:
    data: dict holding PASCAL XML fields for a single image (obtained by
      running dataset_util.recursive_parse_xml_to_dict)
    dataset_directory: Path to root directory holding PASCAL dataset
    label_map_dict: A map from string label names to integers ids.
    ignore_difficult_instances: Whether to skip difficult instances in the
      dataset  (default: False).
    image_subdirectory: String specifying subdirectory within the
      PASCAL dataset directory holding the actual image data.

  Returns:
    example: The converted tf.Example.

  Raises:
    ValueError: if the image pointed to by data['filename'] is not a valid JPEG
  """
  print(" ---- {0} \n {1} \n {2}".format(data['folder'], image_subdirectory, data['filename']))
  img_path = os.path.join(data['folder'], image_subdirectory, data['filename'])
  full_path = os.path.join(dataset_directory, img_path)
  with tf.gfile.GFile(full_path, 'rb') as fid:
    encoded_jpg = fid.read()
  encoded_jpg_io = io.BytesIO(encoded_jpg)
  image = PIL.Image.open(encoded_jpg_io)
  if image.format != 'JPEG':
    raise ValueError('Image format not JPEG')
  key = hashlib.sha256(encoded_jpg).hexdigest()

  width = int(data['size']['width'])
  height = int(data['size']['height'])

  xmin = []
  ymin = []
  xmax = []
  ymax = []
  classes = []
  classes_text = []
  truncated = []
  poses = []
  difficult_obj = []
  if 'object' in data:
    for obj in data['object']:
      difficult = bool(int(obj['difficult']))
      if ignore_difficult_instances and difficult:
        continue

      difficult_obj.append(int(difficult))

      xmin.append(float(obj['bndbox']['xmin']) / width)
      ymin.append(float(obj['bndbox']['ymin']) / height)
      xmax.append(float(obj['bndbox']['xmax']) / width)
      ymax.append(float(obj['bndbox']['ymax']) / height)
      classes_text.append(obj['name'].encode('utf8'))
      classes.append(label_map_dict[obj['name']])
      truncated.append(int(obj['truncated']))
      poses.append(obj['pose'].encode('utf8'))

  example = tf.train.Example(features=tf.train.Features(feature={
      'image/height': dataset_util.int64_feature(height),
      'image/width': dataset_util.int64_feature(width),
      'image/filename': dataset_util.bytes_feature(
          data['filename'].encode('utf8')),
      'image/source_id': dataset_util.bytes_feature(
          data['filename'].encode('utf8')),
      'image/key/sha256': dataset_util.bytes_feature(key.encode('utf8')),
      'image/encoded': dataset_util.bytes_feature(encoded_jpg),
      'image/format': dataset_util.bytes_feature('jpeg'.encode('utf8')),
      'image/object/bbox/xmin': dataset_util.float_list_feature(xmin),
      'image/object/bbox/xmax': dataset_util.float_list_feature(xmax),
      'image/object/bbox/ymin': dataset_util.float_list_feature(ymin),
      'image/object/bbox/ymax': dataset_util.float_list_feature(ymax),
      'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
      'image/object/class/label': dataset_util.int64_list_feature(classes),
      'image/object/difficult': dataset_util.int64_list_feature(difficult_obj),
      'image/object/truncated': dataset_util.int64_list_feature(truncated),
      'image/object/view': dataset_util.bytes_list_feature(poses),
  }))
  return example


def main(_):
  if FLAGS.set not in SETS:
    raise ValueError('set must be in : {}'.format(SETS))
  if FLAGS.year not in YEARS:
    raise ValueError('year must be in : {}'.format(YEARS))

  data_dir = FLAGS.data_dir
  years = ['VOC2007', 'VOC2012']
  if FLAGS.year != 'merged':
    years = [FLAGS.year]

  writer = tf.python_io.TFRecordWriter(FLAGS.output_path)

  label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)

  for year in years:
    logging.info('Reading from PASCAL %s dataset.', year)
    examples_path = os.path.join(data_dir, 'ImageSets', 'Main',
                                 'default.txt')
    annotations_dir = os.path.join(data_dir, FLAGS.annotations_dir)
    examples_list = dataset_util.read_examples_list(examples_path)
    for idx, example in enumerate(examples_list):
      if idx % 100 == 0:
        logging.info('On image %d of %d', idx, len(examples_list))
      path = os.path.join(annotations_dir, example + '.xml')
      if not os.path.exists(path) : 
        continue
      with tf.gfile.GFile(path, 'r') as fid:
        xml_str = fid.read()
      xml = etree.fromstring(xml_str)
      data = dataset_util.recursive_parse_xml_to_dict(xml)['annotation']

      tf_example = dict_to_tf_example(data, FLAGS.data_dir, label_map_dict,
                                      FLAGS.ignore_difficult_instances)
      writer.write(tf_example.SerializeToString())

  writer.close()


if __name__ == '__main__':
  tf.app.run()`

```

I use that command to train my model:
```
`
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
PIPELINE_CONFIG_PATH=/data/ssd_mobilenet_v1_coco_2018_01_28/ssd_mobilenet_v1_coco_2018_01_28/pipeline.config
MODEL_DIR=/data/training
NUM_TRAIN_STEPS=1500
SAMPLE_1_OF_N_EVAL_EXAMPLES=1
python3 object_detection/model_main.py \
    --pipeline_config_path=${PIPELINE_CONFIG_PATH} \
    --model_dir=${MODEL_DIR} \
    --num_train_steps=${NUM_TRAIN_STEPS} \
    --sample_1_of_n_eval_examples=$SAMPLE_1_OF_N_EVAL_EXAMPLES \
    --alsologtostderr
`
```

After few iterations I get that error:

```
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 519, in after_save
    self._evaluate(global_step_value)  # updates self.eval_result
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 539, in _evaluate
    self._evaluator.evaluate_and_export())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 920, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 477, in evaluate
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 519, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 501, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1501, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1534, in _call_model_fn_eval
    input_fn, ModeKeys.EVAL)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1022, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1113, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/label/models/research/object_detection/inputs.py", line 625, in _eval_input_fn
    params=params)
  File "/home/label/models/research/object_detection/inputs.py", line 725, in eval_input
    transform_input_data_fn=transform_and_pad_input_data_fn)
  File "/home/label/models/research/object_detection/builders/dataset_builder.py", line 130, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "/home/label/models/research/object_detection/data_decoders/tf_example_decoder.py", line 319, in __init__
    default_value=''),
  File "/home/label/models/research/object_detection/data_decoders/tf_example_decoder.py", line 64, in __init__
    label_map_proto_file, use_display_name=False)
  File "/home/label/models/research/object_detection/utils/label_map_util.py", line 172, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "/home/label/models/research/object_detection/utils/label_map_util.py", line 139, in load_labelmap
    label_map_string = fid.read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/compat.py", line 117, in as_str_any
    return as_str(value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/compat.py", line 87, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 10: invalid start byte
`
```

My tfrecord seems to be corrupted.

**Comment by xav12358** [comment] 2020-03-27 08:11
I modidy /models/research/object_detection/data_decoders/tf_example_decoder.py and put in constructor dct_method='INTEGER_FAST' ensure TF version 1.6 compatibility

**Comment by amahendrakar** [comment] 2020-03-27 15:11
@xav12358,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/11312#issuecomment-313444730) comment form a similar issue and let us know if it helps? Thanks!

**Comment by amahendrakar** [comment] 2020-04-03 16:52
> @xav12358,
> Could you please check [this](https://github.com/tensorflow/tensorflow/issues/11312#issuecomment-313444730) comment form a similar issue and let us know if it helps? Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-10 13:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by linux-cj** [comment] 2020-04-16 07:26
i hava same problem,i start object_dection\utils\config_util.py:
when i start this command : python train.py --logtostderr --train_dir=train_dir/ --pipeline_config_path=ssd_mobilenet_v1_coco.config
error:
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 91, in main
    FLAGS.pipeline_config_path)
  File "G:\python练习\Deep_learn\objectDetec\TrainMyModel\object_detection\utils\config_util.py", line 42, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\compat.py", line 117, in as_str_any
    return as_str(value)
  File "E:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\compat.py", line 87, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 365: invalid start byte

someone can help me?

**Comment by mihaimaruseac** [comment] 2020-04-16 16:02
Please fill in issue template

**Comment by amahendrakar** [comment] 2020-04-24 07:03
> someone can help me?

@linux-cj,
Could you please provide the complete code to reproduce the issue reported here along with the TensorFlow version you are using? Thanks!

**Closed** 2020-05-08 07:08 UTC
Labels: TF 1.14, comp:ops, stalled, stat:awaiting response, type:support

**Comment by mihaimaruseac** [comment] 2020-11-19 00:38
Unicode errors should be fixed now. If you encounter new errors, please open a new issue, filling in the template.

**Comment by qufdl0357** [comment] 2020-11-20 09:22
Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 58, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "object_detection/train.py", line 120, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 231, in build
    config.input_path[:], input_reader_config, filename_shard_fn=shard_fn)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 150, in read_dataset
    filename_shard_fn)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\dataset_builder.py", line 76, in _read_dataset_internal
    filenames = tf.gfile.Glob(input_files)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 350, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 415, in get_matching_files_v2
    for single_filename in pattern
  File "C:\Users\info\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 417, in <listcomp>
    compat.as_bytes(single_filename))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 50: invalid start byte
[ERROR|main.py:37] 2020-11-20 18:18:04,392 > Transfer leaarning Error


Help me

**Comment by smartinez1** [comment] 2020-11-27 06:40
I'm going through this tutorial (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) and when I try to train the model I get this error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

this is the whole log:

Traceback (most recent call last):
  File "d:\WIndowsRepositories\TensorFlow\workspace\training_demo\model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "d:\WIndowsRepositories\TensorFlow\workspace\training_demo\model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\object_detection\model_lib_v2.py", line 467, in train_loop
    pipeline_config_path, config_override=config_override)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 121, in read
    return self._prepare_value(self._read_buf.read(length))
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 93, in _prepare_value
    return compat.as_str_any(val)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 139, in as_str_any
    return as_str(value)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 118, in as_str
    return as_text(bytes_or_text, encoding)
  File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 109, in as_text
    return bytes_or_text.decode(encoding)


Any help is really apreciated, thank you!

**Comment by mihaimaruseac** [comment] 2020-11-30 17:02
Please open a new issue and fill in issue template

**Comment by AphroMad** [comment] 2020-12-11 22:24
I'm not the last person but I got a similar problem that I post [here ](https://github.com/tensorflow/tensorflow/issues/45617) (I filled the issue template)
Thanks in advance !

**Comment by BeyzaYayla** [comment] 2021-02-14 12:02
> I'm going through this tutorial (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) and when I try to train the model I get this error:
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
> 
> this is the whole log:
> 
> Traceback (most recent call last):
> File "d:\WIndowsRepositories\TensorFlow\workspace\training_demo\model_main_tf2.py", line 113, in
> tf.compat.v1.app.run()
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
> _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\absl\app.py", line 303, in run
> _run_main(main, args)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\absl\app.py", line 251, in _run_main
> sys.exit(main(argv))
> File "d:\WIndowsRepositories\TensorFlow\workspace\training_demo\model_main_tf2.py", line 110, in main
> record_summaries=FLAGS.record_summaries)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\object_detection\model_lib_v2.py", line 467, in train_loop
> pipeline_config_path, config_override=config_override)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file
> proto_str = f.read()
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 121, in read
> return self._prepare_value(self._read_buf.read(length))
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 93, in _prepare_value
> return compat.as_str_any(val)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 139, in as_str_any
> return as_str(value)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 118, in as_str
> return as_text(bytes_or_text, encoding)
> File "D:\ProgrammingWindows\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\compat.py", line 109, in as_text
> return bytes_or_text.decode(encoding)
> 
> Any help is really apreciated, thank you!

Did you find solution? Im getting the exact same error.
