### ISSUE TITLE
Quantized graph not running with commit:bb88ec7ecc4dc7ba72548a5115fb86e20b14de5b

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#12011] opened 2017-08-03 17:00 UTC
OS: Ubuntu 16.04 64bits
 Android Version: 7.1 (Nougat)
 NDK Version: android-ndk-r12b

commit bb88ec7ecc4dc7ba72548a5115fb86e20b14de5b
Author: Alan Yee <alyee@ucsd.edu>
Date:   Mon Jul 24 22:46:38 2017 -0700

LOG:

```
native : benchmark_model.cc:405 Input layers: [Variable]
native : benchmark_model.cc:406 Input shapes: [1,227,227,3]
native : benchmark_model.cc:407 Input types: [float]
native : benchmark_model.cc:408 Output layers: [prob]
native : benchmark_model.cc:409 Num runs: [50]
native : benchmark_model.cc:410 Inter-run delay (seconds): [-1.0]
native : benchmark_model.cc:411 Num threads: [16]
native : benchmark_model.cc:412 Benchmark name: []
native : benchmark_model.cc:413 Output prefix: []
native : benchmark_model.cc:414 Show sizes: [0]
native : benchmark_model.cc:415 Warmup runs: [2]
native : benchmark_model.cc:54 Loading TensorFlow.
native : benchmark_model.cc:61 Got config, 0 devices
can't determine number of CPU cores: assuming 4
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT16 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT8 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT16 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseAnd" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseAnd
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT16 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT8 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT16 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseXor" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseXor
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT16 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT8 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT16 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "Invert" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: Invert
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT16 } } }') for unknown op: BitwiseOr
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_UINT8 } } }') for unknown op: BitwiseOr
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT64 } } }') for unknown op: BitwiseOr
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }') for unknown op: BitwiseOr
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT16 } } }') for unknown op: BitwiseOr
native : op_kernel.cc:1142 OpKernel ('op: "BitwiseOr" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT8 } } }') for unknown op: BitwiseOr
native : benchmark_model.cc:74 Could not create TensorFlow Session: Not found: Op type not registered 'RoundToSteps' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process.

```

Earlier this error was not getting reported.

Thanks

**Comment by poxvoculi** [comment] 2017-08-04 00:03
Did you confirm this works just before the commit, and fails just after?

**Comment by kzos** [comment] 2017-08-05 08:22
I was using 1.2 version. later I pulled to that commit id, I am not sure from which commit id  this error is happening.
thanks

**Comment by poxvoculi** [comment] 2017-08-05 16:57
Can you post a small reproducible case?

**Comment by kzos** [comment] 2017-08-05 19:05
Quantize the inception v3/alexnet and try running benchmark app.

**Comment by poxvoculi** [comment] 2017-08-07 18:16
@cwhipkey Can you see what's going on with the RoundToSteps Op?

**Comment by petewarden** [comment] 2017-08-07 20:43
This is an old bug in the quantize_graph.py script. We used to have a RoundToSteps op, but it was removed but the script still inserts it. The quantize_graph.py script is now obsolete though, since it's been replaced by the Graph Transform Tool's quantize_nodes rule:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms/#quantize_nodes

It is confusing though, and I need to officially deprecate quantize_graph.py, and add a logging message point people to the right tool to use.

**Comment by kzos** [comment] 2017-08-14 08:30
@petewarden 
any quick fix to get rid of this error?

**Comment by tensorflowbutler** [comment] 2017-12-20 01:17
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:13
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:15
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2018-01-30 00:05
Since the recommended fix is to use the more up to date script, closing this one for now. I'm also hoping we'll have some improved documentation on quantization soon.

**Closed by petewarden** 2018-01-30 00:05 UTC
Labels: type:bug/performance
