### ISSUE TITLE
Quantized graphs produce unusable output on Android

### ISSUE THREAD

**Issue by eaigner** [tensorflow/tensorflow#17034] opened 2018-02-15 09:34 UTC
When running a quantized graph on linux/ios/android the first 2 are correct, android though produces only garbage output. Does only occur with newer trained graphs (TF 1.4/5 i suppose), never had this issue before.

`softfp` problem?

**Comment by tensorflowbutler** [comment] 2018-02-15 19:35
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-03-03 07:53
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-17 14:55
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by joelteply** [comment] 2018-03-23 04:47
I am seeing this in iOS

**Comment by tensorflowbutler** [comment] 2018-04-17 12:39
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment] 2018-04-17 18:06
Closing because the template is not filled out.

@joelteply if you still have this issue, please file a new issue with the issue template filled out.

**Closed by reedwm** 2018-04-17 18:06 UTC
Labels: stat:awaiting response
