### ISSUE TITLE
Tensorflow 2.0 BatchNorm not working

### ISSUE THREAD

**Issue by SinghKislay** [tensorflow/tensorflow#27349] opened 2019-03-31 17:19 UTC
**System information**
- I written custom code
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: pip
- TensorFlow version: 2.0
- Python version: 3.6
- CUDA/cuDNN version: 10.0/ 7.5
- GPU model and memory: GTX 1070/ 8 gig

 So I wrote a simple model using tf.keras and I was using batchnorm, It was working just fine then sudddenly it stopped working.

**logs**
Traceback (most recent call last):
  File "/home/kislay/Documents/DeepQ/DQmodel.py", line 30, in <module>
    print(dqn.callback(np.random.rand(4,210,160,1),random_action(4)))
  File "/home/kislay/Documents/DeepQ/DQmodel.py", line 18, in callback
    frame_stack = self.BatchNorm(frame_stack)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 589, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 465, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 56, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 462, in _fused_batch_norm_inference
    data_format=self._data_format)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 1206, in fused_batch_norm
    name=name)
  File "/home/kislay/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3931, in _fused_batch_norm
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Could not find valid device for node.
Node: {{node FusedBatchNorm}}
All kernels registered for op FusedBatchNorm :
  device='XLA_CPU'; T in [DT_FLOAT]
  device='XLA_GPU'; T in [DT_FLOAT]
  device='XLA_CPU_JIT'; T in [DT_FLOAT]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_FLOAT]
  device='XLA_GPU_JIT

**Comment by SinghKislay** [comment] 2019-03-31 17:21
Also I comment out the tf.keras.layers.BatchNormalization()(input) line it starts working.

**Comment by muddham** [comment] 2019-04-01 09:29
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by tensorflowbutler** [comment] 2019-04-18 12:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-04-18 16:59
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-18 16:59 UTC
Labels: 2.0, comp:ops, stat:awaiting response, type:bug/performance
