### ISSUE TITLE
[Windows] Speech commands tutorial does not work

### ISSUE THREAD

**Issue by tomzx** [tensorflow/tensorflow#14004] opened 2017-10-26 17:38 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, I'm running `python tensorflow/examples/speech_commands/train.py`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 x64
- **TensorFlow installed from (source or binary)**: `pip install tf-nightly`  (tf_nightly-1.5.0.dev20171026-cp35-cp35m-win_amd64.whl)
- **TensorFlow version (use command below)**: b'unknown' 1.5.0-dev20171026
- **Python version**: Python 3.5.4
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 6.1 x64
- **GPU model and memory**: 2x Nvidia GTX 670 2GB
- **Exact command to reproduce**: `python tensorflow/examples/speech_commands/train.py`

### Describe the problem
It appears that the currently nightlies (or 1.4.0rc1) do not contain the gen_audio_ops module. However the documentation for r1.4 or master (https://www.tensorflow.org/versions/r1.4/tutorials/audio_recognition or https://www.tensorflow.org/versions/master/tutorials/audio_recognition) appears to indicate that the speech_commands demo should work.

Related: #13031

### Source code / logs
```
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
  File "E:\Tom\Documents\GIT\tensorflow\tensorflow\examples\speech_commands\input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\audio_ops.py", line 31, in <module>
    from tensorflow.python.ops.gen_audio_ops import *
ImportError: No module named 'tensorflow.python.ops.gen_audio_ops'
```

**Comment by mrry** [comment] 2017-10-26 23:40
@petewarden Are there any platform dependencies holding these ops back from being available on Windows?

**Comment by mrry** [comment] 2017-10-27 00:03
(Actually, this might be a very easy fix, so I'm sending you a CL that might just fix it.)

**Comment by tomzx** [comment] 2017-11-03 14:37
Based on the logs available @ http://ci.tensorflow.org/view/tf-nightly/job/tf-nightly-windows/M=windows-gpu,PY=35/90/consoleText (the tf-nightly-windows build for python 3.5 of November 3rd, 2017), it appears that gen_audio_ops.py is still not generated.

```
[...]
// should be here (~line 9056)
  Generating tf_python/tensorflow/python/ops/gen_array_ops.py
  Generating tf_python/tensorflow/python/ops/gen_bitwise_ops.py
[...]
// should be here (~line 66164)
  copying tensorflow\python\ops\gen_array_ops.py -> build\lib\tensorflow\python\ops
  copying tensorflow\python\ops\gen_bitwise_ops.py -> build\lib\tensorflow\python\ops
```

**Comment by mrry** [comment] 2017-11-03 14:48
Thanks for letting us know. Looks like I missed a line in the CMake build... will send a PR shortly.

**Comment by NearLinHere** [comment] 2017-11-06 10:34
I have the same problem. The code is pull 5 hours ago.

**System information**
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No, I'm running python tensorflow/examples/speech_commands/train.py
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows 10 x64
**TensorFlow installed from (source or binary):** pip install tf-nightly (tf_nightly-1.5.0.dev20171026-cp35-cp35m-win_amd64.whl)
**TensorFlow version (use command below):** b'unknown' 1.5.0-dev20171104
**Python version:** Python 3.6.3
**Bazel version (if compiling from source):** N/A
**CUDA/cuDNN version:** CUDA 8.0, cuDNN 6.0
**GPU model and memory:** Nvidia GTX 960M , 8GB
**Exact command to reproduce:** python tensorflow/examples/speech_commands/train.py

**Comment by mrry** [comment] 2017-11-06 15:41
@NearLinHere The  Wheel filename includes `20171026`, which suggests that it's the nightly build from October 26th 2017. Can you try against with the latest nightly build?

**Comment by KevlarTheGreat** [comment] 2017-11-07 05:25
This is the error I get:
`c:\Users\Brian\Anaconda3\Lib\site-packages\tensorflow\examples\speech_commands>python train.py
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    import input_data
  File "c:\Users\Brian\Anaconda3\Lib\site-packages\tensorflow\examples\speech_commands\input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
  File "C:\Users\Brian\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\audio_ops.py", line 31, in <module>
    from tensorflow.python.ops.gen_audio_ops import *
ModuleNotFoundError: No module named 'tensorflow.python.ops.gen_audio_ops'

c:\Users\Brian\Anaconda3\Lib\site-packages\tensorflow\examples\speech_commands>`

Can someone tell me how to update my TensorFlow install to get the missing libraries once this problem is fixed?

**Comment by mrry** [comment] 2017-11-07 18:46
@KevlarTheGreat Which version of TensorFlow have you installed? The fix is only available in the `tf-nightly` package, and will be part of TF 1.5.

**Comment by NearLinHere** [comment] 2017-11-08 02:10
@mrry it's fixed. thank you 👍

**Comment by przemoo9621** [comment] 2017-11-11 13:23
I have the same problem.

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, I'm running python tensorflow/examples/speech_commands/train.py
    OS Platform and Distribution: Windows 10 x64
    TensorFlow installed from (source or binary): pip3 install --upgrade tensorflow
    TensorFlow version (use command below): tensorflow-1.4.0-cp36-cp36m-win_amd64.whl
    Python version: Python 3.6
    Exact command to reproduce: python tensorflow/examples/speech_commands/train.py

Speech Commands example was downloaded yesterday from github:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands

**Comment by mrry** [comment] 2017-11-11 23:12
@przemoo9621 See my comment [above](https://github.com/tensorflow/tensorflow/issues/14004#issuecomment-342582086). You'll need to upgrade to a newer version (`tf-nightly` or wait for the 1.5 release).

**Comment by przemoo9621** [comment] 2017-11-13 07:36
@mrry thanks for your reply. I changed my tensor flow version to a newer version tf_nightly. This solve my problem, but now I have another one.

PS C:\Python36\lib\site-packages> python tensorflow\examples\speech_commands\train.py
2017-11-11 16:59:17.282443: I C:\tf_jenkins\home\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\platform\cpu
_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "tensorflow\examples\speech_commands\train.py", line 429, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 133, in run
    _sys.exit(main(argv))
  File "tensorflow\examples\speech_commands\train.py", line 106, in main
    FLAGS.testing_percentage, model_settings)
  File "C:\Python36\lib\site-packages\tensorflow\examples\speech_commands\input_data.py", line 161, in __init__
    testing_percentage)
  File "C:\Python36\lib\site-packages\tensorflow\examples\speech_commands\input_data.py", line 243, in prepare_data_index
    word = re.search('.*/([^/]+)/.*.wav', wav_path).group(1).lower()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by mrry** [comment] 2017-11-13 15:45
@petewarden If I'm reading that line of code correctly, it's trying to extract a path component using a regular expression with `'/'` as the path separator.

**Comment by mrry** [comment] 2017-11-13 15:46
Thanks for letting us know. It looks like that code is relying on `'/'` being the path separator. I've just sent PR #14519 that should fix this.

**Comment by przemoo9621** [comment] 2017-11-14 07:02
@mrry Thanks for your help, everything works fine now.

**Comment by NearLinHere** [comment] 2017-11-15 01:36
@mrry thank you for your kindly help
I met another problem when I try to let model recognize more words. Here is my command: 

`python tensorflow/tensorflow/examples/speech_commands/train.py --data_dir=speech_commands_data --model_architecture=low_latency_conv --wanted_words=yes,no,up,down,left,right,on,off,stop,go,happy,house,cat,dog,bird,three,tree`

and after 400 steps. The following error message is shown:
`Traceback (most recent call last):
  File "tensorflow/tensorflow/examples/speech_commands/train.py", line 429, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\[TS040]\201711 audio recognition\py36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/tensorflow/examples/speech_commands/train.py", line 248, in main
    total_conf_matrix += conf_matrix
ValueError: operands could not be broadcast together with shapes (19,19) (18,18) (19,19)`

**Comment by tenapril** [comment] 2017-11-15 06:33
so i changed it to 
```
_, word = os.path.split(os.path.dirname(wav_path))
word = word.lower()

```
in line 243 on train.py and it works!

i was wondering if we can run this on GPU instead of CPU? What code should i add?
Thanks in advance for the developers! Cheers

**Comment by mrry** [comment] 2017-11-16 00:18
@tenapril Thanks for confirming that it works!

@NearLinHere I'm not sure what the problem is there... I don't think it's platform related... but hopefully @petewarden can shed some light.

**Comment by mrry** [comment] 2017-11-16 00:22
@NearLinHere A quick update: I think PR #14600 should fix it. Thanks for letting us know the problem!

**Comment by NearLinHere** [comment] 2017-11-17 02:56
@mrry I follow the indirection  #14600  and it fixed. Thank you very much.

**Closed** 2017-11-17 19:29 UTC
Labels: stat:awaiting tensorflower

**Comment by cheahheng** [comment] 2017-12-19 01:00
Hi all the nightly build 1.5 fixed the training but I met with another problem when freezing the model. Here's the error...
2017-12-19 08:52:25.336229: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-12-19 08:52:26.539263: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-12-19 08:52:27.734690: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-12-19 08:52:28.926234: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-12-19 08:52:30.113852: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-12-19 08:52:31.136618: W C:\tf_jenkins\workspace\tf-nightly-windows\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
Traceback (most recent call last):

**Comment by Ann1874** [comment] 2019-02-20 18:24
help please
C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\Lib\site-packages>python tensorflow/examples/speech_commands/train.py
Traceback (most recent call last):
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1641, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1617, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1480, in __init__
    self.firstmember = self.next()
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 2295, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1090, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<h')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 452, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tensorflow/examples/speech_commands/train.py", line 106, in main
    FLAGS.testing_percentage, model_settings, FLAGS.summaries_dir)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\Lib\site-packages\tensorflow\examples\speech_commands\input_data.py", line 186, in __init__
    self.maybe_download_and_extract_dataset(data_url, data_dir)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\Lib\site-packages\tensorflow\examples\speech_commands\input_data.py", line 232, in maybe_download_and_extract_dataset
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1587, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\Users\Ana Flavia\AppData\Local\Programs\Python\Python36\lib\tarfile.py", line 1645, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
