### ISSUE TITLE
[TF 2.0 alpha] Tutorial "Using TFRecords and tf.Example" can't run on tensorflow2.0 α0 gpu

### ISSUE THREAD

**Issue by Windaway** [tensorflow/tensorflow#28823] opened 2019-05-18 10:12 UTC
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

TensorFlow version: Tensorflow 2.0 alpha
Doc Link: Using TFRecords and tf.Example https://www.tensorflow.org/alpha/tutorials/load_data/tf_records
Windows 10 LTSC x64 Python3.6 Cuda 10.0 Cudnn 7.5

## Description of issue (what needs changing):

If I run the example code, I will have an error in the cell:
tf_serialize_example(f0,f1,f2,f3)

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

`UnknownError           Traceback (most recent call last)
<ipython-input-21-406ee79a7f52> in <module>
----> 1 tf_serialize_example(f0,f1,f2,f3)

<ipython-input-20-3f3d0d83f6b2> in tf_serialize_example(f0, f1, f2, f3)
      3     serialize_example,
      4     (f0,f1,f2,f3),  # pass these args to the above function.
----> 5     tf.string)      # the return type is `tf.string`.
      6   return tf.reshape(tf_string, ()) # The result is a scalar

F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\ops\script_ops.py in eager_py_func(func, inp, Tout, name)
    387     if `func` returns None.
    388   """
--> 389   return _internal_py_func(func=func, inp=inp, Tout=Tout, eager=True, name=name)
    390 
    391 

F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\ops\script_ops.py in _internal_py_func(func, inp, Tout, stateful, eager, is_grad_func, name)
    276   if eager:
    277     result = gen_script_ops.eager_py_func(
--> 278         input=inp, token=token, Tout=Tout, name=name)
    279   else:
    280     if stateful:

F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\ops\gen_script_ops.py in eager_py_func(input, token, Tout, name)
     64       else:
     65         message = e.message
---> 66       _six.raise_from(_core._status_to_exception(e.code, message), None)
     67   # Add nodes to the TensorFlow graph.
     68   token = _execute.make_str(token, "token")

F:\Anaconda3\envs\TF2\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError: RuntimeError: Error copying tensor to device: CPU:0. Can't copy 35 bytes of a tensor into another with 32 bytes buffer.
Traceback (most recent call last):

  File "F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\ops\script_ops.py", line 205, in __call__
    return func(device, token, args)

  File "F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\ops\script_ops.py", line 107, in __call__
    ret = self._func(*args)

  File "<ipython-input-5-a40a581f0687>", line 10, in serialize_example
    'feature2': _bytes_feature(feature2),

  File "<ipython-input-1-0ab605f55efd>", line 8, in _bytes_feature
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.

  File "F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\framework\ops.py", line 732, in numpy
    return self._cpu_nograd()._numpy()  # pylint: disable=protected-access

  File "F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\framework\ops.py", line 899, in _cpu_nograd
    return self._copy_nograd(context.context(), "CPU:0")

  File "F:\Anaconda3\envs\TF2\lib\site-packages\tensorflow\python\framework\ops.py", line 847, in _copy_nograd
    new_tensor = self._copy_to_device(context=ctx._handle, device=device_name)

RuntimeError: Error copying tensor to device: CPU:0. Can't copy 35 bytes of a tensor into another with 32 bytes buffer.

 [Op:EagerPyFunc]
`

**Comment by Windaway** [comment] 2019-05-18 10:15
If I write import numpy before def _bytes_feature(value): Problem solved.

**Comment by gadagashwini** [comment] 2019-05-22 07:41
@Windaway I tried reproducing the issue through colab link provided but the code executed without any error. Can you try once again and let us know if that still gives error. Thanks!

**Comment by gadagashwini** [comment] 2019-05-27 05:08
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-05-27 05:08 UTC
Labels: stat:awaiting response, type:docs
