### ISSUE TITLE
tf_version_script giving syntaxerror

### ISSUE THREAD

**Issue by machomachopadre** [tensorflow/tensorflow#3059] opened 2016-06-27 13:16 UTC
Hi everyone,
I ran the command `ld tf_version_script.lds` and it gave this error-
`ld:/home/me/tensorflow/tensorflow/tf_version_script.lds:1: syntax error`
I had the directory mounted. Why is this happening?
Thanks!

**Comment by andydavis1** [comment] 2016-06-27 20:05
Can you please fill out all of fields from the template? Environment, steps to reproduce, etc...

**Comment by machomachopadre** [comment] 2016-06-28 11:12
@andydavis1 which template do you mean? It's quite simple. I am using the default configs for tensorflow. And the only steps I took was, mounting the tensorflow directory and running `ld tf_version_script.lds`. Is there some step I am missing?

**Comment by andydavis1** [comment] 2016-06-28 15:39
There is a template when you click the "New Issue" button. I've copied it below:

GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by aselle** [comment] 2016-07-09 03:48
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-09 03:48 UTC
Labels: awaiting response, triaged
