### ISSUE TITLE
TF 2.0 create model-- 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by ixNeo** [tensorflow/tensorflow#43516] opened 2020-09-24 02:35 UTC
```
1 source code
-------------------
inp = Input(shape=(TIME_STEPS, INPUT_DIM,))
inp_time = Input(shape=(1,))
print(tf.executing_eagerly())  # return True

print(inp_time.numpy()) # error
# inp_time=inp_time.eval()/ K.get_value()/ x.numpy()/ K.eval()
x = ConvAtteShare(inp_time=inp_time.numpy(),kernel=(32,32),stride=(16,16),filter_num=3)(inp)
x = Dense(kind_num,activation='softmax')(x)
m = Model(inputs=[inp,inp_time], outputs=[x], name='convatte-test')
print(m.summary())

2 error
----------------------------
print(inp_time.numpy())
AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by Saduf2019** [comment] 2020-09-24 05:06
@ixNeo 
Code shared is incomplete, please provide with simple stand alone code to replicate the issue or is possible share a colab gist with issue faced along with tf version and error log. [When error description include '_TensorLike', then mostly it is due to using mixing of functions from keras and tf.keras in the code.]


With respect to error reported, please refer to : [link](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy), [link1](https://github.com/tensorflow/tensorflow/issues/27519#issuecomment-490388556), #40569
Thanks!

**Comment by ixNeo** [comment] 2020-09-24 05:38
> @ixNeo
> Code shared is incomplete, please provide with simple stand alone code to replicate the issue or is possible share a colab gist with issue faced along with tf version and error log. [When error description include '_TensorLike', then mostly it is due to using mixing of functions from keras and tf.keras in the code.]
> 
> With respect to error reported, please refer to : [link](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy), [link1](https://github.com/tensorflow/tensorflow/issues/27519#issuecomment-490388556), #40569
> Thanks!

tf version is 2.0, 
below is my import packages:
```
import numpy as np
# import tensorflow.keras.backend as K
import keras.backend as K

import keras
from keras.engine.topology import Layer
from keras.layers import Input, Reshape,Dense, Activation, Flatten,Dropout,TimeDistributed,dot,concatenate,multiply,Permute,Add
from keras.layers.core import Lambda, Activation
from keras.models import Model
```

below is my log:
```
	inp = Input(shape=(TIME_STEPS, INPUT_DIM,))
	inp_time = Input(shape=(1,))
	print(inp_time.numpy())

Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/coolinear/Desktop/tjk_full_atte/demo_tjk_full_atte/model_full_atte.py", line 71, in <module>
    transformer_model(1251)
  File "/Users/coolinear/Desktop/tjk_full_atte/demo_tjk_full_atte/model_full_atte.py", line 32, in transformer_model
    print(inp_time.numpy())
AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by Saduf2019** [comment] 2020-09-24 08:39
@ixNeo 
Please provide your issue in a colab gist along with error in it, have you referred and tried the solutions shared, please share the output after you have applied then to your code.

**Comment by bhack** [comment] 2020-09-24 09:44
You cannot use `numpy()` cause it produces a symbolic tensor. 
It is documented at https://www.tensorflow.org/api_docs/python/tf/keras/Input:
> Note that even if eager execution is enabled, Input produces a symbolic tensor (i.e. a placeholder). This symbolic tensor can be used with other TensorFlow ops

**Comment by ixNeo** [comment] 2020-09-24 13:23
> You cannot use `numpy()` cause it produces a symbolic tensor.
> It is documented at https://www.tensorflow.org/api_docs/python/tf/keras/Input:
> 
> > Note that even if eager execution is enabled, Input produces a symbolic tensor (i.e. a placeholder). This symbolic tensor can be used with other TensorFlow ops

it means i cannot get input's value ?

**Comment by bhack** [comment] 2020-09-24 18:06
@ixNeo It is not a bug I think you can close this. For support questions please post on https://stackoverflow.com/questions/tagged/tensorflow

**Closed** 2020-09-25 00:23 UTC
Labels: TF 2.0, stat:awaiting response, type:support
