### ISSUE TITLE
Tensors erroneously zero when an existing session is running on the same device

### ISSUE THREAD

**Issue by crizCraig** [tensorflow/tensorflow#14254] opened 2017-11-05 04:03 UTC
UPDATE: Restarting my machine fixed the issue.

To reproduce, run two processes with
```python
import tensorflow as tf
import time
z = tf.constant([1.8, 2.2], dtype=tf.float32)
z = tf.cast(z, tf.int32)
with tf.Session() as sess:
    while True:
        print('z is', sess.run(z), 'but should be [1, 2]')
        time.sleep(1)
```
Second process output
```
z is [0 0] but should be [1, 2]
z is [0 0] but should be [1, 2]
...
```
Stopping the first process will fix the problem immediately without needing to restart the second process!

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: 3.5.2
- **CUDA/cuDNN version**: CUDA 8 cuDNN 5.1.10
- **GPU model and memory**: GeForce GTX 980 4GB

**Comment by bignamehyp** [comment] 2017-11-06 23:40
I can't reproduce it on my local machine either. Thanks for the update. I will close this issue.

**Closed by bignamehyp** 2017-11-06 23:40 UTC
