### ISSUE TITLE
Keras fit method not working with dataset iterator

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/tensorflow#20022] opened 2018-06-14 14:27 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.9-rc0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: `model.fit(get_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)`
and
`model.fit(get_iterator,get_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)`

### Describe the problem
When I pass one dataset iterator to `fit` method, I get:
 

> Please provide data as a list or tuple of 2 elements  - input and target pair. Received Tensor("IteratorGetNext_4:0", shape=(2, ?), dtype=float32)

When I pass two iterators I get the error:

> ValueError: You passed a dataset or dataset iterator (<tensorflow.python.data.ops.iterator_ops.Iterator object at 0x000001FEABE88748>) as input `x` to your model. In that case, you should not specify a target (`y`) argument, since the dataset or dataset iterator generates both input data and target data. Received: <tensorflow.python.data.ops.iterator_ops.Iterator object at 0x000001FEABE88748>

When I create a new dataset after zipping the original x and y data set and pass that to `fit `I get the error described in https://github.com/tensorflow/tensorflow/issues/19912

According to 1.9-rc0 method release notes iterators should be usable with keras training methods. Please provide a solution or provide clarification in the documentation.

### Source code / logs
```
dataset= tf.contrib.data.make_csv_dataset(file_name,48,select_columns= ['Load_residential_multi_0','Load_residential_multi_1'],shuffle=False)
dataset = dataset.map(lambda x: tf.stack(list(x.values())))
get_iterator = dataset.make_one_shot_iterator()
get_batch = get_iterator.get_next()

#Building and training a single layer model using Keras (Available within TensorFlow)
model = Sequential() 
#Input Layer
model.add(InputLayer(input_shape=(48,),name='InputLayer'))#,input_tensor =dataset
#model.add(BatchNormalization(axis=1))  #Normalizing values
#Layer1 
model.add(Dense(units=5,activation='relu',name='FeedForward1'))  #Add a feed forward layer
#Layer2 
model.add(Dense(units=5,activation='relu',name='FeedForward2'))  #Add a feed forward layer
#Output layer 
model.add(Dense(units=48,name='OutputLayer'))

#Specify los function and optimizer
model.compile(loss='mse',optimizer='adam',metrics=['mae'])

#Summarize model
model.summary()
#Train the model
model.fit(get_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)
#model.fit(get_iterator,get_iterator,steps_per_epoch=2,batch_size=2,epochs=2,shuffle =True,verbose=1)
```

**Comment by sibyjackgrove** [comment] 2018-06-14 20:58
@sebamlu Can you please share the code snippet that you used to make it work?

**Comment by sebamlu** [comment] 2018-06-14 21:15
Sure, I'm using TFRecordDataset instead of tf.contrib.data.make_csv_dataset, but should make no difference.


```
with tf.variable_scope('feeding_data'):
        train_set = tf.data.TFRecordDataset(glob(DATA_DIR + '/*train*.tfrecord'))
        train_set = train_set.repeat(epochs)
        train_set = train_set.shuffle(1000)
        train_set = train_set.map(decode_data, num_parallel_calls=num_map_threads)
        train_set = train_set.batch(batch_size)

        test_set = tf.data.TFRecordDataset(glob(DATA_DIR + '/*test*.tfrecord'))
        test_set = test_set.shuffle(buffer_size=1000)  # Enables stochastic batch validation
        test_set = test_set.map(decode_data, num_parallel_calls=num_map_threads)
        test_set = test_set.batch(batch_size)

        training_iterator = train_set.make_one_shot_iterator()
        validation_iterator = test_set.make_initializable_iterator()  

    model = BaseCnnModel(num_classes=n_classes)
    model.compile(
        optimizer=tf.train.MomentumOptimizer(learning_rate=learning_rate, momentum=0.9),
        loss='categorical_crossentropy',
        metrics=['accuracy'],
    )

    model.fit(
        x=training_iterator,
        validation_data=validation_iterator,
        steps_per_epoch=40,
        epochs=epochs,
        validation_steps=2,
    )

```

and the model

> class BaseCnnModel(keras.Model):
> 
>     def __init__(self, num_classes, dropout_rate=0.5):
>         super(BaseCnnModel, self).__init__(name='bcnn')
> 
>         self.cnn1 = keras.layers.Conv2D(12, 3, activation=tf.nn.relu)
>         self.maxp1 = keras.layers.MaxPooling2D((2, 2))
>         self.cnn2 = keras.layers.Conv2D(16, 3, activation=tf.nn.relu)
>         self.maxpl2 = keras.layers.MaxPooling2D((2, 2))
>         self.cnn3 = keras.layers.Conv2D(16, 3, activation=tf.nn.relu)
>         self.maxpl3 = keras.layers.MaxPooling2D((2, 2))
>         self.flat = keras.layers.Flatten()
>         self.dense1 = keras.layers.Dense(512, activation=tf.nn.relu)
>         self.drop1 = keras.layers.Dropout(dropout_rate)
>         self.dense2 = keras.layers.Dense(num_classes, activation=None)
> 
>     def call(self, inputs):
>         x = self.cnn1(inputs)
>         x = self.maxp1(x)
>         x = self.cnn2(x)
>         x = self.maxpl2(x)
>         x = self.cnn3(x)
>         x = self.maxpl3(x)
>         x = self.flat(x)
>         x = self.dense1(x)
>         x = self.drop1(x) # I assume that keras makes this work properly on evaluation..
>         return self.dense2(x)
> 


As you can see i never defined an input shape for the model

**Comment by sibyjackgrove** [comment] 2018-06-14 22:08
@sebamlu thanks for sharing. So you are saying this doesn't work when you defined the Keras model without using the class?
Anyway I will try putting my model inside a class and if it works with the `tf.contrib.data.make_csv`

**Comment by sebamlu** [comment] 2018-06-14 22:29
@sibyjackgrove From [https://github.com/keras-team/keras/blob/master/examples/mnist_tfrecord.py](url)

```
Input Tensors also have important disadvantages. In
particular, Input Tensors are fixed at model construction
because rewiring networks is not yet supported.
For this reason, changing the data input source means
model weights must be saved and the model rebuilt
from scratch to connect the new input data.
validation cannot currently be performed as training
progresses, and must be performed after training completes.
....

```
I don't see this working with two iterators if you define an InputTensor

**Comment by sibyjackgrove** [comment] 2018-06-15 14:32
I created the model as you suggested, 
```
class BaseModel(Model):
    def __init__(self, num_features):
        super(BaseModel, self).__init__(name='bcnn')

        self.dense1 = Dense(12, activation=tf.nn.relu)
        self.dense2 = Dense(12, activation=tf.nn.relu)
        self.dense3 = Dense(num_features, activation=None)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)
```
But I am getting the same error as before.

**Comment by sebamlu** [comment] 2018-06-15 15:33
`Please provide data as a list or tuple of 2 elements - input and target pair. Received Tensor("IteratorGetNext_4:0", shape=(2, ?), dtype=float32)`

I read your error and I think that the problem is with your map function, tf.stack returns a tensor and you need to return a tuple or list like: (features_tensor, target_label_tensor),  hope this helps.

**Comment by sibyjackgrove** [comment] 2018-06-15 16:56
I need the tf.stack to flatten the columns from the CSV file. Anyway I removed the `tf.stack` as shown below: 
```
dataset= tf.contrib.data.make_csv_dataset(file_name,48,select_columns=['Load_residential_multi_0','Load_residential_multi_1'],shuffle=False)
dataset = dataset.batch(2)
get_iterator = dataset.make_one_shot_iterator()
get_batch = get_iterator.get_next()
```
But I get pretty much the same error except that the  `tf.contrib.data.make_csv_dataset` is now returning an ordered dictionary.

> ValueError: Please provide data as a list or tuple of 2 elements  - input and target pair. Received OrderedDict([('Load_residential_multi_0', <tf.Tensor 'IteratorGetNext_8:0' shape=(?, ?) dtype=float32>), ('Load_residential_multi_1', <tf.Tensor 'IteratorGetNext_8:1' shape=(?, ?) dtype=float32>)])

Maybe the tf.contrib.data.make_csv_dataset just can't work with Keras model. I wish they would clarify.

**Comment by pavithrasv** [comment] 2018-06-21 18:08
Duplicate of #19912

**Closed by pavithrasv** 2018-06-21 18:08 UTC
