### ISSUE TITLE
why my coco_output.txt (output of evaluation coco object detection with tflite models)is empty!!!!!! 

### ISSUE THREAD

**Issue by Davari393** [tensorflow/tensorflow#33081] opened 2019-10-06 07:41 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:samsung s8 pluse
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.15
- Python version:3.6
- Bazel version (if compiling from source):0.26.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:NO CUDA
- GPU model and memory:NO GPU

**Comment by rmothukuru** [comment] 2019-10-07 11:36
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2019-10-21 12:53
@Davari393,
 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2019-10-25 09:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-10-25 09:36 UTC
Labels: TF 1.15, comp:lite, stat:awaiting response
