### ISSUE TITLE
Keras fit with mixed dataset/ndarray data results in batch_size arg error

### ISSUE THREAD

**Issue by ahoereth** [tensorflow/tensorflow#29865] opened 2019-06-17 08:56 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 & macOS 10.14.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc0-55-g1b365ca304 1.14.0-rc1
- Python version: 3.6.8 & 3.7.2
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the current behavior**

Combining tf.data.Dataset with tf.keras.Model fails since 1.14.0rc0 when using a dataset for training but a numpy array for validation data. Logs with errors for both 1.14 and 1.13 below.

**Describe the expected behavior**

Being able to use a dataset only for training but a numpy array for validation data.

**Code to reproduce the issue**

```Python
import tensorflow as tf
import numpy as np

data = np.random.randn(1000, 10)
targets = np.random.randn(1000, 1)
ds = tf.data.Dataset.from_tensor_slices(data).batch(32)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=10))
model.add(tf.keras.layers.Dense(32))
model.add(tf.keras.layers.Dense(1))

model.compile(optimizer="rmsprop", loss="mse")
model.fit(ds, steps_per_epoch=10, validation_data=(data, targets), batch_size=32)
```

**Other info / logs**

**Behaviour using 1.14.0rc1:**

Without `batch_size=32` set:

```Bash
% python bug.py
[...]
1/10 [==>...........................] - ETA: 1s - loss: 2.3122
Traceback (most recent call last):
  File "tensorflow_bug.py", line 14, in <module>
    model.fit(ds, steps_per_epoch=10, validation_data=(data, targets))
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 409, in model_iteration
    steps_name='validation_steps')
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 335, in model_iteration
    batches = make_batches(num_samples_or_steps, batch_size)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 493, in make_batches
    num_batches = int(np.ceil(size / float(batch_size)))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

With `batch_size=32` set:

```Bash
% python tensorflow_bug.py
[...]
Traceback (most recent call last):
  File "tensorflow_bug.py", line 14, in <module>
    model.fit(ds, steps_per_epoch=10, validation_data=(data, targets), batch_size=32)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 652, in fit
    batch_size, steps_per_epoch, x)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1873, in _validate_or_infer_batch_size
    raise ValueError('The `batch_size` argument must not be specified when'
ValueError: The `batch_size` argument must not be specified when using dataset as an input.
```

**Behaviour using 1.13.1:**

Without `batch_size=32` set:

```Bash
% python bug.py
[...]
1/10 [==>...........................] - ETA: 2s - loss: 3.0703
Traceback (most recent call last):
  File "tensorflow_bug.py", line 14, in <module>
    model.fit(ds, steps_per_epoch=10, validation_data=(data, targets))
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 364, in model_iteration
    validation_in_fit=True)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 301, in model_iteration
    batches = make_batches(num_samples_or_steps, batch_size)
  File "/Users/ahoereth/repos/AutoECG/.venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 488, in make_batches
    num_batches = int(np.ceil(size / float(batch_size)))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

With `batch_size=32` set:

```Bash
% python bug.py
[...]
10/10 [==============================] - 0s 21ms/step - loss: 1.0369 - val_loss: 1.1500
```

**Comment by achandraa** [comment] 2019-06-18 08:29
I have tried on Colab with TF versions 1.14.0-rc1 and 1.13.1 and was able to reproduce the issue  on 1.14rc1 but not in 1.13.1 as mentioned in the description. Thanks!

**Comment by ahoereth** [comment] 2019-07-05 11:13
Any news on this issue? I think this is an undocumented breaking change?

**Comment by jvishnuvardhan** [comment] 2019-09-05 22:15
@ahoereth I modified your code little bit by making validation data as a dataset instead of `numpy.ndarray`. In this case, you don't need to provide `batch_size=32` as an input to `model.fit` function. Please take a look at the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/176d60213967b951f724769b0cc34f47/tf_29865.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-09-11 17:59
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-09-11 17:59 UTC
Labels: TF 1.14, comp:keras, type:bug
