### ISSUE TITLE
Having problem to use the Reshape in Keras

### ISSUE THREAD

**Issue by Ray322417** [tensorflow/tensorflow#29818] opened 2019-06-15 06:38 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 750 Ti

**Describe the current behavior**
When using Reshape layer of Keras and -1 is used to infer the shape, the output shape is incorrect.

**Describe the expected behavior**

**Code to reproduce the issue**
`from tensorflow.python.keras.layers import Input, Lambda, Conv2D, Reshape, TimeDistributed`
`from tensorflow.python.keras.models import *`
`import tensorflow.keras as keras`

`a = Input(shape=(12,), dtype = 'int32')`
`# a.shape == (None, 12)`
`d = Reshape((-1, 2, 2))(a)`
`# actual result： d.shape == (None, None, 2, 2)`
`# expected result： d.shape == (None, 3, 2, 2)`

**Comment by veqtor** [comment] 2019-06-15 20:59
You don't need to specify the batch dimension in Keras

**Comment by gadagashwini** [comment] 2019-06-17 10:26
I am able to reproduce the reported issue on Colab with Tensorflow 2.0.0.beta0. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-19 02:17
@Ray322417 I am closing this as this is a duplicate of this issue https://github.com/keras-team/keras/issues/12964. Thanks!

**Closed by jvishnuvardhan** 2019-06-19 02:17 UTC
Labels: 2.0.0-beta0, comp:keras, type:bug/performance
