### ISSUE TITLE
layers.LocallyConnected2D throws error when saving a model in tf, saving in .h5 works

### ISSUE THREAD

**Issue by hojin89** [tensorflow/tensorflow#47689] opened 2021-03-10 07:49 UTC
Hi, tensorflow community

I'm playing around with LocallyConnected2D and found some weird error when I tried to save a model (model.save).

When I gave the layer implementation=1, the model was saved without any errors.
But, if I set implementation=2, it gave me this error.

Traceback (most recent call last):
  File "/home/tonglab/Documents/Project/PycharmProjects/LCN/LCN_Keras/LocalConn2d_Keras.py", line 84, in <module>
    model.save('keras1')
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    signatures, options, save_traces)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 89, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1133, in _build_meta_graph_impl
    checkpoint_graph_view)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 151, in list_functions
    self._serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2613, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3087, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 94, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 57, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 155, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 274, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 193, in wrap_layer_functions
    fn.get_concrete_function()
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 549, in get_concrete_function
    self.call_collection.add_trace(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 423, in add_trace
    fn.get_concrete_function(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 550, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 527, in wrapper
    ret = method(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 570, in call_and_return_conditional_losses
    call_output = layer_call(inputs, *args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/layers/local.py", line 615, in call
    self.compute_output_shape(inputs.shape))
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/layers/local.py", line 782, in local_conv_matmul
    [K.shape(output_flat)[0],] + output_shape.as_list()[1:])
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3020, in reshape
    return array_ops.reshape(x, shape)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8378, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/tonglab/anaconda3/envs/tf_2_4_1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 540, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

My tensorflow version is 2.4.1.

Any advice will be appreciated.
Thank you.

**Comment by AdityaKane2001** [comment] 2021-03-10 08:38
@hojin89 
It would be great if you shared the source code of this error. 
Also, from the log, I speculate that the layer and its weights are initialized with a placeholder (dummy Tensor), and thus it says that the shape is not defined. Other cause may be that the shapes of some Tensors may not be defined before runtime, as layers are executed in graph mode.

**Comment by amahendrakar** [comment] 2021-03-10 13:57
@hojin89,
As mentioned by @AdityaKane2001, could you please provide the complete code and the TensorFlow version you are using so that we can reproduce the issue on our end. Thanks!

**Comment by hojin89** [comment] 2021-03-10 15:25
Thanks for the replies.

Here is the complete code:

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers

# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Scale images to the [0, 1] range
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
print("x_train shape:", x_train.shape)
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

#### train
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():

    model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.LocallyConnected2D(16, kernel_size=(9, 9), activation="relu", implementation=2),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

    model.summary()

    batch_size = 128
    epochs = 1

    opt = keras.optimizers.Adam(learning_rate=0.001)
    model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
    model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

    score = model.evaluate(x_test, y_test, verbose=0)
    print("Test loss:", score[0])
    print("Test accuracy:", score[1])

    model.save('keras1')

As mentioned earlier, my tensorflow version is 2.4.1.
If I use "implementation=1", the code works well without any errors.

It seems like the error occurs when it calls "self.compute_output_shape(inputs.shape))" in local.py.
inputs.shape should be (None, 28, 28, 1), but for some reason, it shows me (None, None, None, 1) at some point.

I'm still trying to figure this out. 
If you could give any advice, that'll be appreciated.

**Comment by AdityaKane2001** [comment] 2021-03-11 04:39
`model.save('keras1.h5')` works as expected. Saving model in a directory results in the aforementioned error. Gist [here](https://colab.research.google.com/gist/AdityaKane2001/c2072f8433a13975b815dbdfa3819d7c/47689.ipynb).

**Comment by amahendrakar** [comment] 2021-03-17 17:38
@ymodak,
I was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/cfbf7c9942e89e7b286509fe7776cdf5/47689.ipynb). Thanks!

**Comment by nikitamaia** [comment] 2021-04-06 17:08
Adding the contributions welcome label to this issue for further investigation by the community. If you are interested in working on this issue, please leave a comment and I will assign it to you. Thanks!

**Comment by Suraj1199** [comment] 2021-04-15 05:34
@AdityaKane2001 @hojin89  
One can observe in this [file](tensorflow/python/keras/layers/local.py) that LocallyConnected2D layer uses deprecated version of keras and a bunch of deprecated ops. According to its documention, implementation=2, stores weights of each layer in a dense (but sparsely-populated) 2D matrix and implements the forward pass as a single matrix-multiply. So while saving as TF SavedModel, compute_output_shape() is not able to convert the shape and raises the error you mention. However it gets saved as .h5 keras model.

**Comment by AdityaKane2001** [comment] 2021-04-15 05:36
@Suraj1199 
The link is broken..

**Comment by Suraj1199** [comment] 2021-04-15 05:40
@AdityaKane2001  It should be working now.

**Comment by AdityaKane2001** [comment] 2021-04-15 05:41
@Suraj1199
Thanks

**Comment by Suraj1199** [comment] 2021-04-15 05:46
> `model.save('keras1.h5')` works as expected. Saving model in a directory results in the aforementioned error. Gist [here](https://colab.research.google.com/gist/AdityaKane2001/c2072f8433a13975b815dbdfa3819d7c/47689.ipynb).

To save the model in TF SavedModel format in a directory ('keras1' in this case) use Conv2D layer intead of LocallyConnected2D.

**Comment by AdityaKane2001** [comment] 2021-04-16 05:53
Side note, this is true for `implementation=3` as well

**Comment by Kareem-negm** [comment] 2021-04-30 02:25
@hojin89 
you can Save the entire model to a HDF5 file.
 The '.h5' extension indicates that the model should be saved to HDF5.
```model.save('my_model.h5')```

**Comment by ashutosh1919** [comment] 2021-05-17 12:48
@nikitamaia , please assign this issue to me since I am working on it as part of PR #49230 .

**Closed** 2021-05-25 19:43 UTC
Labels: TF 2.4, comp:keras, stat:contributions welcome, type:bug
