### ISSUE TITLE
MNIST dataset usage issue

### ISSUE THREAD

**Issue by aartikas** [tensorflow/tensorflow#8159] opened 2017-03-07 07:18 UTC
Hi,
I am working with tensorflow to build a network using mnist data set but it is showing connection refused error.

 File "neuralnw1.py", line 4, in <module>
    mnist = input_data.read_data_sets('MNIST_data', one_hot=True)  # one-hot -> '2' = (0,0,1,0,0,0,0,0,0)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 189, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 157, in maybe_download
    urllib.request.urlretrieve(source_url, temp_file_name)
  File "/usr/lib/python3.4/urllib/request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by MicaelCarvalho** [comment] 2017-03-07 13:01
LeCun's website seems to be down at the moment, and the dataset is hosted over there. This probably explains the problem, although the error message doesn't say timeout.

Anyway, in future issues you should post a minimal code to reproduce the problem, not only the stack trace — it would help us find what is wrong and you would get an answer faster. ;)

**Comment by prb12** [comment] 2017-03-07 18:44
Closed as duplicate of #8126

**Closed by prb12** 2017-03-07 18:44 UTC
