### ISSUE TITLE
Reading tfrecord reaches deadock or crushes in one computer and works just fine on another.

### ISSUE THREAD

**Issue by tnikolla** [tensorflow/tensorflow#13039] opened 2017-09-14 12:42 UTC
### Laptop -System information
- Linux Ubuntu 16.04
- TensorFlow installed with pip:
- TensorFlow 1.3.0
- Python 2.7.12
- Spyder 2.3.8

### Workstation -System information
- Linux Ubuntu 16.04
- TensorFlow installed with pip:
- TensorFlow-gpu 1.0.0
- Python 2.7.13

### Problem description
I want to create and read a tfrecord file with [build_cgd_dataset.py](https://github.com/tnikolla/grasp-detection/blob/master/build_cgd_dataset.py) as the writer and [reader_iter.py](https://github.com/tnikolla/grasp-detection/blob/master/reader_iter.py) as the reader. Everything works smooth in the workstation but it reaches a deadlock or gets stuck in the laptop. The dataset are from [Cornell grasping dataset](http://pr.cs.cornell.edu/grasping/rect_data/data.php).

I narrowed down the error in this special cases where it doesn't show any problem, for example:
  - if it reads a int64_list with one value, so a list with one elemnet
  - if it reads a float_list with one element

If the lists have more than one element the program freezes.

**Comment by reedwm** [comment] 2017-09-14 22:43
I could not reproduce on my workstation, after changing the paths in the programs to point to directories on my local workstation. To clarify, you are waiting for build_cgd_dataset.py to finish before starting reader_iter.py, right?

Try to reproduce the problem in a very simple case. Before, you were limiting the the number of elements in the lists, but instead try limiting the number of `tf.train.Example`s. Also try creating the tfrecords on your workstation and read them on the laptop, or vice versa. And try using the same TensorFlow versions on both, to see if the issue is caused by a certain TensorFlow version.

**Comment by tnikolla** [comment] 2017-09-15 16:46
So, I write the tfrecord with build_cgd_dataset.py. This works always. The problem lies in reading them.

I've done some more careful tests today. I'm writing here the programs:

**writer.py**

    import tensorflow as tf

    def _int64_feature(v):
        return tf.train.Feature(int64_list=tf.train.Int64List(value=v))

    def _floats_feature(v):
        return tf.train.Feature(float_list=tf.train.FloatList(value=v))
    
    def convert_to_example():
        return tf.train.Example(features=tf.train.Features(feature={
                'a': _floats_feature(a)}))
    
    #a = [1, 2, 3]
    a = [1., 2., 3.]
    def main():
        writer = tf.python_io.TFRecordWriter('tfrecord_float')
        example = convert_to_example()
        writer.write(example.SerializeToString())
        writer.close()

    if __name__ == '__main__':
        main()

**reader.py**

    import tensorflow as tf

    filename = '/home/tomi/issue/tfrecord_float'
    record_iter = tf.python_io.tf_record_iterator(path=filename)
    example = tf.train.Example()
    l = []
    for record in record_iter:
        example.ParseFromString(record)
        a = example.features.feature['a'].float_list.value[:]
        print(a)

**Running the reader from the terminal** (and not Spyder 2.3.8) everything works as should. Running the reader from Spyder reading a list of floats crushes Spyder. With a list of integers, more often than not, the reader works fine. Maybe the issue should be closed.

**Comment by reedwm** [comment] 2017-09-15 21:54
I also could not reproduce running from the terminal. You should verify that Spyder is using the same versions of Python and Tensorflow as when you run from the terminal.

Marking as contributions welcome if someone can reproduce in Spyder.

**Comment by sushreebarsa** [comment] 2024-05-23 06:41
Hi,
Could you verify that you're using the same TensorFlow version on both computers. Different versions might have variations in how they handle TFRecords.
Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the release notes to stay up to date with the latest developments which are happening in the Tensorflow space.
Thank you!

**Closed** 2024-05-24 08:20 UTC
Labels: stat:contribution welcome, stat:awaiting response
