### ISSUE TITLE
undefined reference to `google::protobuf::internal::fixed_address_empty_string'

### ISSUE THREAD

**Issue by fangyan93** [tensorflow/tensorflow#7266] opened 2017-02-05 01:14 UTC
![error_2_4](https://cloud.githubusercontent.com/assets/14129554/22622882/bd9c80a0-eb15-11e6-9ee1-3269efd7e0bd.png)

Hello,
I am tring to do install core of tensorflow on Raspberry PI 3, on Ubuntu 16.04 LTS using python 3.5.2, exactly following the instruction on https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile, but got error messages at last step "make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8". 

Note that I tried the method shared on  https://github.com/samjabrahams/tensorflow-on-raspberry-pi, but there are also error occured. 

I am wondering is it due to some update of tensorflow? Looking forward to your reply. Thank you!

**Comment by yaroslavvb** [comment] 2017-02-06 00:53
cc @samjabrahams who made TF work on PI

**Comment by samjabrahams** [comment] 2017-02-06 01:03
Thanks @yaroslavb - I haven't seen the "undefined reference to ...protobuf..." error before. Generally, the error code 1 messages I've seen were due to an out of memory error, though that doesn't seem likely to be the case here. Currently at a super bowl party, but I'll try to take a closer look soon.

**Comment by samjabrahams** [comment] 2017-02-06 08:14
This appears to be a duplicate of #5684. @fangyan93 - it may be good to move the discussion over there.

As an aside, you mentioned that you experienced a bug following the instructions on my repo. If you have the time, would you mind opening up an issue over there with a few details so I can investigate that problem separately?

**Comment by girving** [comment] 2017-02-06 16:27
Closing as a duplicate per @samjabrahams's comment.

**Closed by girving** 2017-02-06 16:27 UTC
