### ISSUE TITLE
tensorflow/tensorflow/models/rnn/ptb/ptb_word_lm.py TypeError

### ISSUE THREAD

**Issue by yuriShafet** [tensorflow/tensorflow#293] opened 2015-11-19 11:16 UTC
when running ptb_word_lm.py:

File "ptb_word_lm.py", line 259, in main
    config = get_config()
  File "ptb_word_lm.py", line 122, in __init__
    self._cost = cost = tf.reduce_sum(loss) / batch_size
TypeError: unsupported operand type(s) for /: 'Tensor' and 'int'

I replaced
 self._cost = cost = tf.reduce_sum(loss) / batch_size
to
self._cost = cost = tf.div(tf.reduce_sum(loss), batch_size)
and it seems to work fine.

**Comment by girving** [comment] 2015-11-19 17:41
Do you have `from __future__ import division` at the top, and are you running against tensorflow installed via pip?  As part of #1 we added __truediv__ support to tensorflow but made the mistake of using it in the tutorials.  It should work if you remove that import, and I'll fix it so that the HEAD tutorials are compatible with the 0.5.0 release.

**Comment by girving** [comment] 2015-11-19 17:44
Oh, actually that isn't a tutorial.  I think we won't try to keep stuff in `models` at HEAD backwards compatible to older versions of tensorflow.  You can fix it locally by either removing that  import line or using the version of `ptb_word_lm.py` from the `0.5.0` tag.  In general, running part of tensorflow at `HEAD` against an older release is not guaranteed to work.

**Comment by girving** [comment] 2015-11-19 17:44
Reopening until the diagnosis is confirmed.

**Comment by girving** [comment] 2015-11-30 18:02
Closing for now, since I believe this is fixed.

**Closed by girving** 2015-11-30 18:02 UTC
Labels: installation/startup

**Comment by darolt** [comment] 2015-12-28 10:12
girving: I had the same issue. Commenting the division import line made it work.

**Comment by girving** [comment] 2015-12-28 16:50
@darolt: This shouldn't be an issue now at 0.6.0 is out.  In general, there's no guarantee that git versions of tensorflow models will work against old releases.
