### ISSUE TITLE
Data cardinality

### ISSUE THREAD

**Issue by mohammadalimehdizadeh** [tensorflow/tensorflow#38702] opened 2020-04-20 07:33 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): preinstalled
- TensorFlow version (use command below): v2.2.0-rc3-0-gaad398b5e9, 2.2.0-rc3
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I build a model with to independent sequential sub-models like:
![image](https://user-images.githubusercontent.com/44928904/79725338-5229da00-82fe-11ea-943b-58c2af493e8b.png)
 but number of samples for two sub-models are different and i am seeing this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-a01d55a188be> in <module>()
----> 5 model.fit({'input1':x1.to_numpy(), 'input2':x2.to_numpy()}, {'output1':y1.to_numpy(), 'output2':y2.to_numpy()}, epochs=10)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, sample_weight_modes, batch_size, epochs, steps, shuffle, **kwargs)
    280             label, ", ".join(str(i.shape[0]) for i in nest.flatten(data)))
    281       msg += "Please provide data which shares the same first dimension."
--> 282       raise ValueError(msg)
    283     num_samples = num_samples.pop()
    284 

ValueError: Data cardinality is ambiguous:
  x sizes: 2408, 2371
  y sizes: 2408, 2371
Please provide data which shares the same first dimension.
**Describe the expected behavior**
because the number of batches are the same, so i think it must work...

**Comment by amahendrakar** [comment] 2020-04-20 15:34
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

You can also share your Colab notebook. Select 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!

**Comment by mohammadalimehdizadeh** [comment] 2020-04-20 15:49
It's a very simple model, like:

# Input layer
input1 = Input((310,), name='input1')
input2 = Input((310,), name='input2')

# Layer 1
l1 = Dense(64, activation='relu')(input1)
l1 = Dense(1, activation='sigmoid', name='output1')(l1)

# Layer 2
l2 = Dense(64, activation='relu')(input2)
l2 = Dense(1, activation='sigmoid', name='output2')(l2)

# Build model
model = keras.Model(inputs=[input1, input2], outputs=[l1, l2])
# keras.utils.plot_model(model, 'multi_input_and_output_model.png', show_shapes=True)
model.compile(optimizer='adam', loss={'output1':keras.losses.MeanSquaredError(),'output2':keras.losses.MeanSquaredError()})
model.summary()

and you can check it by som dummy x1 and x2 but with different first dimension, for example:
x1.shape = (1000,310)
y1.shape = (1000,)
x2.shape = (2000,310)
y2.shape = (2000,)
model.fit({'input1':x1, 'input2':x2}, {'output1':y1, 'output2':y2}, epochs=10)

**Comment by amahendrakar** [comment] 2020-04-22 05:51
@mohammadalimehdizadeh,
On running the above code, I am facing a different error stating `ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(1000, 310), (2000, 310)]`. 

On changing the dimensions, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/829637c2c12963876c294a7930b5fe0f/38702.ipynb#scrollTo=8oU1vMyzaEEJ). Thanks

**Comment by mohammadalimehdizadeh** [comment] 2020-04-22 19:15
I solve it by using tf.GradientTape and optimizater.apply_gradients instead of fit method it work nice!!!

But why is fit method design in this manner?

**Comment by mohammadalimehdizadeh** [comment] 2020-04-23 07:11
it is the feature of problem, i have two input with different number of samples. it's the nature of  problem.
 when i use tf.GradientTape and optimizer.apply_gradient instead of model.fit method it works nice without any error.

**Comment by amahendrakar** [comment] 2020-04-24 10:21
@mohammadalimehdizadeh,
As the error message states, all input arrays should be of the same size. In your case the shape of `x1` and `x2` was different. Any mismatch in the input data raises a ValueError. You can read more about the fit method [here](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit).

Is this still and issue? Please feel free to close the issue if resolved. Thanks!

**Closed** 2020-04-25 17:26 UTC
Labels: TF 2.2, comp:keras, stat:awaiting response, type:support

**Comment by Luckilyeee** [comment] 2020-10-19 21:40
> @amahendrakar thanks for your response.
> I solve it by using tf.GradientTape and optimizater.apply_gradients instead of fit method it work nice!!!
> 
> But why is fit method design in this manner?

how did you use the tf.GradientTape and optimizater.apply_gradients  to deal with that problem, can you share the details? I have been stuck for a long time. Thanks!

**Comment by MaxHeuillet** [comment] 2020-10-22 17:15
Same issue for me, 

I designed a custom tensorflow model with multiple inputs and one binary output
And when I use the .fit method, even though the batch size is correct they throw an error because the inner dimensions do not match

**Comment by amahendrakar** [comment] 2020-10-27 15:56
@Luckilyeee, @MaxHeuillet,
Could y'all please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by KaterinaBao** [comment] 2021-04-02 03:02
> > @amahendrakar thanks for your response.
> > I solve it by using tf.GradientTape and optimizater.apply_gradients instead of fit method it work nice!!!
> > But why is fit method design in this manner?
> 
> how did you use the tf.GradientTape and optimizater.apply_gradients to deal with that problem, can you share the details? I have been stuck for a long time. Thanks!

Hi, have you know how to use the tf.GradientTape and optimizater.apply_gradients to solve the problem? Thanks! I am facing the same problem and would you like to share the information with me?
