### ISSUE TITLE
Saver: Don't fail on restoring variables not present in a checkpoint.

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#17257] opened 2018-02-25 12:12 UTC
This is a feature request.

Let's consider a scenario where one trains multiple models and uses them in combination (like it is done in GANs).

To simplify the process of saving and restoring variables that are partly shared across the models (Pretraining Model, Training Model, Evaluation Model, Infer Model) one could instantiate the whole graph, containing all operations and variables, and save it.

Then in order to do pre-training only the subset of graph elements that is required for pretraining is used.

This results in the overhead of having to build the whole model (which might consist of multiple sub models) the first time the model is run even though only a smaller part (e.g. Pretraining Model) is required.

Another issue arises when using different optimizers in different training stages (e.g. SGD first then Adam). As Adam creates additional variables Adam has to be instantiated during the first training stage so restoring from a checkpoint does not fail when restoring with Adam instead of SGD.

This restriction of having to build everything despite parts not being required results in more complicated code. If it would be possible to silently fail when a variable is not found in a checkpoint, so it can be initialized with `tf.global_variables_initializer()` instead, would allow better structuring of code.

I have looked through all current issues regarding this problem and I have found a couple that face a similar problem and where a `QuietlyFailRestoringSaver` could solve this problem:
https://github.com/tensorflow/tensorflow/issues/12032
https://github.com/tensorflow/tensorflow/issues/16781

I might consider building this if there is enough support for it. I am open for feedback.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-03-17 14:56
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by sleighsoft** [comment] 2018-03-21 11:06
Yes it is

**Comment by angersson** [comment] 2018-04-03 17:14
@allenlavoie Do you have any thoughts on this?

**Comment by allenlavoie** [comment] 2018-04-03 17:38
Interesting. It's not exactly a drop-in replacement for `tf.train.Saver`, but we've been developing an object-based save/restore API in part for compatibility with eager execution, [tfe.Checkpoint](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/Checkpoint).

It more or less accidentally has the lazy error checking you're interested in. When executing eagerly the `restore` request may come before some variables have been created, so it won't complain unless you manually run one of its assertions (`restore` returns a status object).

The caveat is that it doesn't use global variable names like `tf.train.Saver`, and requires that the objects you use come from [`Checkpointable`](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/Checkpointable) classes. This is almost all of TensorFlow's objects at this point (`Layer`s, `Optimizer`s, `tf.keras.Model`, `make_template`, most RNN cells, etc.), but may require some refactoring to use. The [eager examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples) have been converted; those run with eager execution enabled, but everything will work fine with graph building if you add a `checkpoint.restore(...).run_restore_ops()` call to run the restore ops in a `Session`.

So that's the direction I'd like checkpointing to be headed in. The APIs are not in core yet, but should get there in another release or two. Happy to take feature requests / bug reports.

**Comment by sleighsoft** [comment] 2018-04-03 21:40
Looks interesting. So how exactly would I transfer my code over to this new approach (I do not use any high-level APIs). I currently don't see the locality of variables to be a disadvantage. I am going to use multiple savers in my GAN anyways to swap out different trained generator and discriminator stages.

**Comment by allenlavoie** [comment] 2018-04-03 22:08
Inheriting from `tf.keras.Model` is a nice way to manage `Layer`s ([example](https://github.com/tensorflow/tensorflow/blob/5d33c1e49178aedbb459da7ce58eca710102c06b/tensorflow/contrib/eager/python/examples/gan/mnist.py#L95)) and you get Checkpointability for free. But if you want something lower level, you can inherit from `tfe.Checkpointable` directly. In either case the `__setattr__` override takes your attribute names and builds up a graph of objects with named edges; the trick is just making sure there's a path from the object you're saving to your variables.

**Comment by allenlavoie** [comment] 2018-04-04 16:19
That sounds right. I'll close this for now, but feel free to comment or open something else if object-based checkpointing is missing something you need (or if you decide it's awful and want the original name-based request open again :).

**Closed by allenlavoie** 2018-04-04 16:19 UTC
Labels: stat:contributions welcome, type:feature

**Comment by sleighsoft** [comment] 2018-05-09 20:46
@allenlavoie What happens internally when I assign the same variable multiple times to `self`? E.g.:
```({'model/embedding/.ATTRIBUTES/VARIABLE_VALUE': <tf.Variable 'embedding:0' shape=(1, 1) dtype=float32_ref>}, nodes {
  children {
    node_id: 1
    local_name: "model"
  }
}
nodes {
  children {
    node_id: 2
    local_name: "embedding"
  }
  children {
    node_id: 2
    local_name: "test"
  }
}
nodes {
  attributes {
    name: "VARIABLE_VALUE"
    full_name: "embedding"
    checkpoint_key: "model/embedding/.ATTRIBUTES/VARIABLE_VALUE"
  }
}
)
```

**Comment by allenlavoie** [comment] 2018-05-09 21:01
It should just overwrite the dependency. I've considered making that a warning (or queuing up the warning for save/restore time?). A restore() after the second assignment should restore the second object, but otherwise it will (only) restore the first: self.test = foo, restore(), self.test = bar will only restore foo.

Is that not what's happening?

**Comment by sleighsoft** [comment] 2018-05-10 18:58
Thank you for your reply. My question wasn't about assigning two different objects to the same `self.<key>` but rather assign the same variable multiple times to self with different keys. I was confused if that would somehow duplicate the variable or would cause multiple restores for the same variable.
I found the internal documentation for `_track_checkpointable`. That already explains the assignment part but I am still unsure if I would cause multiple restores for the same variable.

**Comment by sleighsoft** [comment] 2018-05-10 19:01
Is it correct, that restoring works based on the `self.<key>` and not based on the global variable name?

**Comment by allenlavoie** [comment] 2018-05-10 19:35
Oh, yes, multiple dependencies on the same object are fine/expected. It will only restore once.

Restoring does work on dependency names rather than global variable names. If you want to inspect dependencies manually, I'd use [dot_graph_from_checkpoint](https://github.com/tensorflow/tensorflow/blob/c8731009708d4694fc553562a267d75064fc5ab4/tensorflow/contrib/checkpoint/python/visualize.py#L25). Or programatically you can inspect checkpoints with [tf.contrib.checkpoint.object_metadata](https://github.com/tensorflow/tensorflow/blob/c8731009708d4694fc553562a267d75064fc5ab4/tensorflow/python/training/checkpointable_utils.py#L162).

I haven't added a tf.contrib.checkpoint API for listing variables yet. Do you have a use-case in mind?

**Comment by sleighsoft** [comment] 2018-05-10 20:00
Currently I would only use it for debugging purposes.
Maybe for visualization outside of tensorboard it would be useful as well, but I haven't spent much thought about it.

**Comment by sleighsoft** [comment] 2018-05-10 21:19
@allenlavoie Is there a way to get all uninitialized variables for a Checkpoint or Checkpointable? All those that did not get initialized by a restore.

**Comment by allenlavoie** [comment] 2018-05-10 21:37
`initialize_or_restore()` on the status object returned by `restore()` will initialize anything that wasn't restored (assuming it's in the dependency graph). Does that work for you?

Example usage: https://github.com/tensorflow/tensorflow/blob/2b42a0620f45cc40c3cc96552c565271bfed0c82/tensorflow/python/training/checkpointable_utils.py#L954

`initialize_or_restore` documentation: https://github.com/tensorflow/tensorflow/blob/2b42a0620f45cc40c3cc96552c565271bfed0c82/tensorflow/python/training/checkpointable_utils.py#L531

**Comment by sleighsoft** [comment] 2018-05-11 08:18
I cannot paste you my whole code right now but that does not seem to work for me when using Adam. It somehow does not restore one of the variables Adam creates for variables.
I'll see if I can reproduce it in a smaller example.

**Comment by sleighsoft** [comment] 2018-05-11 09:28
Small example:
```python
import tensorflow as tf
import tensorflow.contrib.eager as tfe
from tensorflow.python.training import checkpointable
from tensorflow.contrib.eager.python import checkpointable_utils


class MyModel(checkpointable.Checkpointable):

  def __init__(self):
    self.optimizer = tf.train.GradientDescentOptimizer(0.1)
    self.var = tf.get_variable('var', [])

  def optimizer_to_adam(self):
    self.optimizer = tf.train.AdamOptimizer()


checkpoint_path = 'modeldir/test/'

with tf.Graph().as_default():
  model = MyModel()
  checkpoint = tfe.Checkpoint(model=model)
  train_op = model.optimizer.minimize(model.var * model.var)
  print(checkpointable_utils._serialize_object_graph(checkpoint))
  session = tf.Session()
  session.run(tf.global_variables_initializer())
  checkpoint.save(checkpoint_path, session)
  session.run(train_op)
  print('Finished Model with SGD')

with tf.Graph().as_default():
  model = MyModel()
  model.optimizer_to_adam()
  latest = tf.train.latest_checkpoint(checkpoint_path)
  train_op = model.optimizer.minimize(model.var * model.var)
  checkpoint = tfe.Checkpoint(model=model)
  print(checkpointable_utils._serialize_object_graph(checkpoint))
  session = tf.Session()
  checkpoint.restore(latest).initialize_or_restore(session)
  session.run(train_op)
  print('Finished Model with Adam')
```

I would expect that the second graph (`Finished Model with Adam`) works.
But it throws `Attempting to use uninitialized value beta2_power`.
I expected the `.initialize_or_restore` to initialize the `Adam` variables but that does not happen.

**Comment by allenlavoie** [comment] 2018-05-11 16:36
I think just a version issue? The initialization changes I mentioned are relatively recent. Your awesome repro snippet works for me with `v1.8.0-1386-g2dc7575123` (from `python3.5 -c "import tensorflow as tf; print(tf.__git_version__)"`).

The change is https://github.com/tensorflow/tensorflow/commit/eb31cf8a62739d4df4c84b8edeccbe756b70616d so anything built with that should work (theoretically any nightly, although some of those have been stretching "nightly").

**Comment by sleighsoft** [comment] 2018-05-13 17:53
Good to know :)
Sadly there are no windows nightly builds right now, for whatever reason, so I'll have to wait until they get fixed.

**Comment by sleighsoft** [comment] 2018-05-13 18:29
@allenlavoie Do Checkpoints only support lower case names?
When I do `tfe.Checkpoint(**{'TEST': MyModel()'})` it silently consumes it but it is not attached to the checkpoint afterwards.

**Comment by allenlavoie** [comment] 2018-05-14 16:28
I know of at least one user of mixed-case names.

Your example works for me assuming I build/use `checkpoint.TEST`. Your `tfe.Checkpoint` line is adding a new `MyModel` instance; are you just using a different instance?

**Comment by sleighsoft** [comment] 2018-05-16 11:37
So you do?
```
ckpt = tfe.Checkpoint()
ckpt.TEST = MyModel()
```

Do you have any idea why this error could occur?
```
File "/home/mp2017/cmdseqgan/CMDSeqGAN-2/network/architecture/base_gan.py", line 50, in initialize_or_restore
    load_status.initialize_or_restore(self.session)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/training/checkpointable_utils.py", line 619, in initialize_or_restore
    session.run(initializers)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 245, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 352, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 352, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 253, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/mp2017/miniconda3/envs/cmdseqgan-cpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 289, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument <tf.Operation 'ConditionedGradientConv2dDiscriminator/CONDITIONED_GRADIENT_CONV2D/global_step/Assign' type=Assign> cannot be interpreted as a Tensor. (Operation name: "ConditionedGradientConv2dDiscriminator/CONDITIONED_GRADIENT_CONV2D/global_step/Assign"
op: "Assign"
```

**Comment by allenlavoie** [comment] 2018-05-16 16:03
Usually I'd do something like https://github.com/tensorflow/models/blob/0344c5503ee55e24f0de7f37336a6e08f10976fd/official/mnist/mnist_eager.py#L146 (or https://github.com/tensorflow/tensorflow/blob/d2297c8571ea485898851420de9f8368f0c869fd/tensorflow/contrib/eager/python/examples/gan/mnist.py#L275 for a dictionary example)

So the model object gets constructed and used, and `tf.train.Checkpoint` just gets a reference to it. But to be clear, there's nothing wrong with `Checkpoint(**{'TEST': MyModel()})` as long as you use the instance of `MyModel` created on that line. In order to do that you'd need to do something like:

```
checkpoint = tf.train.Checkpoint(**{'TEST': MyModel()})
output = checkpoint.TEST(tf.constant([[1.]]))
```

or 

```
checkpoint = tf.train.Checkpoint(**{'TEST': MyModel()})
model = checkpoint.TEST
output = model(tf.constant([[1.]]))
```

**Comment by sleighsoft** [comment] 2018-05-16 21:54
Oh, maybe that got fixed in some commit. I was on an older 1.8 nightly

**Comment by dhingratul** [comment] 2018-08-14 17:26
initialize_or_restore doesn't work for me, I am at v1.8.0-0-g93bc2e2072

**Comment by allenlavoie** [comment] 2018-08-14 17:35
@dhingratul are you looking for the behavior in https://github.com/tensorflow/tensorflow/commit/eb31cf8a62739d4df4c84b8edeccbe756b70616d#diff-dbbfcd46840cb910643decf863dc00a6 ?

Looks like that first appeared in 1.9. Could you try upgrading and see if the new behavior works for you?

**Comment by sleighsoft** [comment] 2018-08-22 08:27
@dhingratul What exactly does not work? Doesn't it restore the variables or are they not initialized?

**Comment by dhingratul** [comment] 2018-08-22 16:04
I was at 1.8, so it doesn't recognize it. I will check with 1.9
