### ISSUE TITLE
tf.estimator package not installed

### ISSUE THREAD

**Issue by greyowl** [tensorflow/tensorflow#23007] opened 2018-10-16 05:03 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6.6
- **Bazel version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Mobile device**: N/A
- **Exact command to reproduce**: 
`pip install --upgrade tensorflow`
`import tensorflow as tf` 

### Describe the problem
I installed tensorflow via pip in a conda environment. Trying to `import tensorflow` results in a `tf.estimator package not installed.` error. I had a look a #22342 and checked my pandas version to be 0.23.4. 

```python
>>> import tensorflow as tf
tf.estimator package not installed.
```

Interestingly enough if I import pandas before importing tensorflow there is no error
```python
>>> import pandas as pd 
>>> import tensorflow as tf 
# No Error
```

On an added note I can't import pandas after I import tensorflow 
```python
>>> import tensorflow as tf
tf.estimator package not installed.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/home1/irteam/anaconda3/envs/umap/lib/python3.6/site-packages/pandas/core/series.py", line 67, in <module>
    import pandas.core.ops as ops
AttributeError: module 'pandas' has no attribute 'core'
```

**Comment by tensorflowbutler** [comment] 2018-10-16 07:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Mobile device

**Comment by wt-huang** [comment] 2018-10-23 14:38
@greyowl This is likely anaconda related. Make sure to install pandas, numpy, matplotlib and matplotlib at minimum if not entire scipy during anaconda setup. 

Also, check whether GLIB version is up-to-date with Centos.

**Comment by manugarri** [comment] 2018-10-24 18:34
same here

**Comment by daxinnan** [comment] 2018-10-26 08:01
```julia> using PyCall

julia> pyimport("tensorflow")
tf.estimator package not installed.
PyObject <module 'tensorflow' from '/xxx/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py'>
```

**Comment by HubberDev** [comment] 2018-11-07 02:31
I hit the exact same issue. Here are the steps I followed:
1. Installed Anaconda3-5.3.0-Windws-x86_64 on Windows 10 PC.
2. Downgrade python to 3.6.7 since python 3.7 is not supported yet.
3. pip install tensorflow

4. when do "import tensorflow as tf" in jupyter notebook, it complains 
tf.estimator package not installed.
tf.estimator package not installed.

5. when do "import pandas as pd", it complains the following. Even after I uninstalled tensorflow, it still has the same issue.
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7dd3504c366f> in <module>
----> 1 import pandas as pd

C:\Anaconda3\lib\site-packages\pandas\__init__.py in <module>
     40 import pandas.core.config_init
     41 
---> 42 from pandas.core.api import *
     43 from pandas.core.sparse.api import *
     44 from pandas.tseries.api import *

C:\Anaconda3\lib\site-packages\pandas\core\api.py in <module>
      8 from pandas.core.dtypes.missing import isna, isnull, notna, notnull
      9 from pandas.core.arrays import Categorical
---> 10 from pandas.core.groupby.groupby import Grouper
     11 from pandas.io.formats.format import set_eng_float_format
     12 from pandas.core.index import (Index, CategoricalIndex, Int64Index,

C:\Anaconda3\lib\site-packages\pandas\core\groupby\__init__.py in <module>
      1 # flake8: noqa
----> 2 from pandas.core.groupby.groupby import (
      3     Grouper, GroupBy, SeriesGroupBy, DataFrameGroupBy
      4 )

C:\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py in <module>
     47                                CategoricalIndex, _ensure_index)
     48 from pandas.core.arrays import ExtensionArray, Categorical
---> 49 from pandas.core.frame import DataFrame
     50 from pandas.core.generic import NDFrame, _shared_docs
     51 from pandas.core.internals import BlockManager, make_block

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in <module>
     72                                    create_block_manager_from_arrays,
     73                                    create_block_manager_from_blocks)
---> 74 from pandas.core.series import Series
     75 from pandas.core.arrays import Categorical, ExtensionArray
     76 import pandas.core.algorithms as algorithms

C:\Anaconda3\lib\site-packages\pandas\core\series.py in <module>
     65 from pandas.compat.numpy import function as nv
     66 
---> 67 import pandas.core.ops as ops
     68 import pandas.core.algorithms as algorithms
     69 

AttributeError: module 'pandas' has no attribute 'core'

**Comment by HubberDev** [comment] 2018-11-07 02:48
Amazingly, the problem seemed have gone away after I did the following:
- downgrade pandas from 0.23.4 to 0.23.0
- upgrade matplotlib to 3.0.0

**Comment by wt-huang** [comment] 2018-11-18 00:52
Closing as this is resolved, free to reopen if problem persists.

**Closed by wt-huang** 2018-11-18 00:52 UTC
Labels: stat:awaiting response

**Comment by asafasban** [comment] 2018-11-19 18:46
Hi, i've done :
downgrade pandas from 0.23.4 to 0.23.0
upgrade matplotlib to 3.0.0

issue still exist, exactly the same as "HubberDev" described X(

**Comment by asafasban** [comment] 2018-11-19 18:51
Hey, Solved .
just update matplotlib 👍 
matplotlib: 3.0.0-py36hd159220_0 --> 3.0.1-py36hc8f65d3_0 = fixed
(panda remained 0.23.0)

**Comment by agilebean** [comment] 2018-12-03 10:09
> Hey, Solved .
> just update matplotlib 👍
> matplotlib: 3.0.0-py36hd159220_0 --> 3.0.1-py36hc8f65d3_0 = fixed
> (panda remained 0.23.0)

I can confirm this. You still have the problem with matplotlib 3.0.0 but not 3.0.1

**Comment by upuil** [comment] 2018-12-19 13:54
same problem 
     import tensorflow as tf
     tf.estimator package not installed.
     tf.estimator package not installed.

**Comment by ThomasColthurst** [comment] 2019-01-04 21:35
I'm also seeing this with TensorFlow 1.11.  I'm building TensorFlow from source following the instructions at https://www.tensorflow.org/install/source

**Comment by ziyuwzf** [comment] 2019-03-08 01:58
my is tensorflow-gpu==1.12，tensorflow-estimator==1.13，i change  tensorflow-estimator==1.10.12

**Comment by Phynixknight** [comment] 2019-03-13 07:11
> Hey, Solved .
just update matplotlib 👍
matplotlib: 3.0.0-py36hd159220_0 --> 3.0.1-py36hc8f65d3_0 = fixed
(panda remained 0.23.0)

I solve this problem the same way.

**Comment by PeterMitrano** [comment] 2019-03-21 16:16
For me this had nothing to do with pandas or matplotlib. The issue was that I had installed a newer version of TF then downgraded. Uninstalling `tensorflow-estimator` and `tensorflow-gpu`, then reinstalling `tensorflow-gpu` fixed it.

**Comment by yayaQAQ** [comment] 2019-04-18 12:33
I fixed it by uninstalling `tensorflow-estimator`

**Comment by Fashiar** [comment] 2019-05-02 22:06
_**pip uninstall tensorflow-estimator**_ worked for me

**Comment by kennedyCzar** [comment] 2019-06-11 14:00
**SOLUTION**
```
pip install tensorflow==1.13.1
pip install tensorflow-estimator-1.13.0
```

Ensure no previous version of tensorflow-estimator is available apart from the above..To check use
```
conda list
pip uninstall tensorflow-estimator-x.xx.x
```

**Comment by doolingdavid** [comment] 2019-06-20 15:13
kennedyCzar's solution above worked for me.

**Comment by lwmonster** [comment] 2020-07-27 07:50
> _**pip uninstall tensorflow-estimator**_ worked for me

It works for me too ...
