### ISSUE TITLE
tf.debugging.assert_shapes

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#37228] opened 2020-03-02 11:10 UTC
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/debugging/assert_shapes

## Description of issue (what needs changing):
The documentation for the `shapes` argument states that is expects a dict, but in fact in many circumstances it is not possible to assemble such a dict because eager tensors are unhashable.
So while it is possible to submit a dict here in GraphMode, Eager expects a list of (key, value) pairs.

It should also state whether `tf.Variable`s can be used as keys.

### Usage example
The usage example seems to confuse the two concepts, and provides a mixup of both in invalid python syntax:
```
tf.assert_shapes([
  (x: ('N', 'Q')),
  (y: ('N', 'D')),
  (param: ('Q',)),
  (scalar: ()),
])
```
*This seems to be fixed already in master*

Further, `tf.assert_shapes` should probably be changed to `tf.debugging.assert_shapes`

### Submit a pull request?
Yes

**Comment by ngc92** [comment] 2020-03-02 15:15
Looking at the code in master, this seems to have been partially fixed (the usage example). However, now there are `assert_shapes` and `assert_shapes_v2` functions which slightly different documentation, even though the latter does nothing but call the former.

**Comment by amahendrakar** [comment] 2020-03-03 09:47
@ngc92,
Could you please check the nightly version of the docs from this [link](https://www.tensorflow.org/api_docs/python/tf/debugging/assert_shapes?version=nightly). 
I was able to reproduce the error with the example given on the stable version. However, the example given in nightly docs works without any issues. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/b63bf1fd7194fa28fa1a198f17c5baab/37228.ipynb). Thanks!

**Comment by ngc92** [comment] 2020-03-03 15:55
yes, the example from the nightly docs works. The point about the `shapes` argument documented as being a dict still stands, though.

**Comment by ymodak** [comment] 2020-03-23 20:03
Closing this issue since the associated PR has been merged. Thanks!

**Closed by ymodak** 2020-03-23 20:03 UTC
Labels: TF 2.1, comp:tfdbg, type:docs
