### ISSUE TITLE
Batched matrix multiplication is incorrect for large batches

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#29374] opened 2019-06-03 21:57 UTC
This bug seems to exist in all versions of TensorFlow from (at least) `1.13` to the current `2.0` nightly under multiple configurations (host os, gpu, python versions...) with CUDA 10.0.

It can be reproduced fairly easily:

```python
with tf.device('gpu:0'):
  v = tf.ones((2**17, 1, 1), dtype=tf.float32)
  print(tf.reduce_sum(tf.matmul(v, v)))
```

This prints `65535.0` instead of `131072.0` (stemming from the output values at indices `>= 2**16` being `0`)

Colab: https://colab.research.google.com/drive/1CZiKKWkI96SAVRJ5kMkT5kmMunipJhdx

Some observations:

- This occurs for batch dimensions greater than or equal to 2<sup>16</sup>.
- This only occurs on the GPU. The CPU version seems fine.
- This only occurs for FP32. FP64 seems fine.
- In TensorFlow 2.0, the bug only manifests on the first run (as shown in the colab example). Subsequent runs produce the correct result.

**Comment by gadagashwini** [comment] 2019-06-04 08:21
I could reproduce the reported issue on colab. Thanks!

**Comment by aaroey** [comment] 2019-06-04 21:51
I can only reproduce with 2.0, not with 1.13.

@smit-hinsu could you help to take a look? Thanks.

**Comment by ethereon** [comment] 2019-06-04 23:57
@aaroey: This reproduces it on v1.13: https://colab.research.google.com/drive/1ycxH0LP2TPJxBKci5XqsgguhHdGCow1I

The underlying issue seems to be reading out of bounds memory for elements `>= 2**16`. In the example above, that out-of-bounds region is zeros. However, you can just as easily get other results.

**Comment by smit-hinsu** [comment] 2019-06-08 02:33
Duplicate of #26969

**Closed by smit-hinsu** 2019-06-08 02:33 UTC
Labels: comp:gpu, type:bug/performance
