### ISSUE TITLE
Colab TPU cannot use dataset from GCS

### ISSUE THREAD

**Issue by kurnianggoro** [tensorflow/tensorflow#33427] opened 2019-10-16 12:46 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: - 

**Describe the current behavior**
upload credential to TPU is failed. Therefore, cannot train on TPU using dataset from google cloud service. I also tried to downgrade to tf 1.14 but still not working.

**Describe the expected behavior**
Same code was working few days ago, also the example codes in seedbank are using same code and they were working fine. Now all are not working.

**Code to reproduce the issue**
```python
import os
import tensorflow as tf

import json
bucket = 'kurnianggoro ' #@param {type:"string"}

assert bucket, 'Must specify an existing GCS bucket name'
print('Using bucket: {}'.format(bucket))


from google.colab import auth
auth.authenticate_user()

TF_MASTER = 'grpc://{}'.format(os.environ['COLAB_TPU_ADDR'])

# Upload credentials to TPU.
with tf.Session(TF_MASTER) as sess:    
    with open('/content/adc.json', 'r') as f:
        auth_info = json.load(f)
    tf.contrib.cloud.configure_gcs(sess, credentials=auth_info)
```

similar code in the official examples of google colab also not working
https://colab.research.google.com/github/GoogleCloudPlatform/cloudml-samples/blob/master/tpu/templates/tpu_estimator/trainer.ipynb

**Other info / logs**
```

InternalError                             Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

9 frames

InternalError: From /job:tpu_worker/replica:0/task:0:
The filesystem registered under the 'gs://' scheme was not a tensorflow::RetryingGcsFileSystem*.
	 [[{{node GcsConfigureCredentials}}]]


During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InternalError: From /job:tpu_worker/replica:0/task:0:
The filesystem registered under the 'gs://' scheme was not a tensorflow::RetryingGcsFileSystem*.
	 [[node GcsConfigureCredentials (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

**Comment by FrederikWA** [comment] 2019-10-16 13:57
Duplicate of #33426

**Closed** 2019-10-17 01:30 UTC
