### ISSUE TITLE
undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)

### ISSUE THREAD

**Issue by gp1322719830** [tensorflow/tensorflow#53096] opened 2021-11-17 13:33 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.3.0
- Python version:python3.6
- Bazel version (if compiling from source):bazel3.1
- GCC/Compiler version (if compiling from source):7.5
- CUDA/cuDNN version:cuda10.2、cudnn8
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2021-11-17 17:05
Does this occur on newer versions of TF?

Afaik, TF 2.3 does not really contain all the changes to prevent code using invalid shapres from crashing the interpreter via `CHECK`-failures. Plus, TF 2.3 is no longer supported

**Comment by gp1322719830** [comment] 2021-11-18 03:40
Tf2.1, there is no such problem

**Comment by sushreebarsa** [comment] 2021-11-18 06:30
@gp1322719830 
It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Can you please execute your code using latest Version (2.7.0) and let us know if the issue still persists? Thanks!

**Comment by gp1322719830** [comment] 2021-11-18 09:02
I need use 2.3.0

**Comment by sushreebarsa** [comment] 2021-11-18 09:06
@gp1322719830 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gp1322719830** [comment] 2021-11-18 12:28
tensorflow::Tensor input_tensor(tensorflow::DT_FLOAT, tensorflow::TensorShape({1,299,2399,3}));

**Comment by gp1322719830** [comment] 2021-11-18 12:31
Is there any other way to set the input size？Avoid tensorflow:: tensorshape construction.

**Comment by gp1322719830** [comment] 2021-11-18 12:51
tf2.3.0 code error ----> tensor.cc：645: Tensor::Tensor(DataType type) : shape_(type), buf_(nullptr) {}

**Comment by gp1322719830** [comment] 2021-11-18 15:50
Tensorflow::TensorShape shape;
shape.AddDim(1);
shape.AddDim(299);
shape.AddDim(299);
shape.AddDim(3);
tensorflow::Tensor input_tensor(tensorflow::DT_FLOAT, shape);
success！

**Comment by mihaimaruseac** [comment] 2021-11-18 15:55
Closing since you have a workaround and since this is only affecting TF 2.3 which is no longer supported.

**Closed by mihaimaruseac** 2021-11-18 15:55 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:apis, TF 2.3
