### ISSUE TITLE
C++ Online Documentation codeblocks not formatting

### ISSUE THREAD

**Issue by oxinabox** [tensorflow/tensorflow#10241] opened 2017-05-27 06:03 UTC
There are some codeblocks in C++ documentation , written with github-style fenced markdown, 
that are not rendering as `<code>`.

Eg: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/depth-to-space

![screenshot of a page with docs not formatted as code](https://cloud.githubusercontent.com/assets/5127634/26518496/5c312d9e-42e4-11e7-856a-972268bcf757.png)

It looks like something is going wrong with the site generation,
that when translating markdown, it does not pickup these blocks.

In the pages I quickly checked it seems to occur in the Summary sections, eg in:

- https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/depth-to-space
- https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space
- https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space-n-d

**Comment by jart** [comment] 2017-05-28 01:01
This is happening in the [1.2 docs](https://www.tensorflow.org/versions/r1.2/api_docs/cc/class/tensorflow/ops/depth-to-space) too.

@markdaoust Any idea why we're not rendering the code blocks in our C++ ops documentation?

**Comment by shitian-ni** [comment] 2017-05-28 13:40
Maybe triple ``` should be single ` ?

**Comment by MarkDaoust** [comment] 2017-05-28 15:05
@shitian-ni: These are rendering correctly in the python docs (singles are for inline, triples are for blocks).

https://www.tensorflow.org/versions/r1.2/api_docs/python/tf/depth_to_space

@jart: I'm not very familiar with that section of the docs pipeline, I'll find the right person.

**Comment by joshua-xia** [comment] 2017-06-23 06:12
The document is in tensorflow\core\ops\array_ops.cc, I am willing to fix this, should we remove all  ```  as python API: https://www.tensorflow.org/api_docs/python/tf/depth_to_space ?

Thanks

**Comment by dr4b** [comment] 2017-06-23 18:15
If you remove the ``` you need to indent 4 spaces so we parse it as Markdown regardless, otherwise it will still render poorly.

I think we have an internal bug open to do some processing to the C++ docs regardless, however.

**Comment by joshua-xia** [comment] 2017-06-24 01:58
so this issue will be fixed after the internal bug fixed, right?

**Comment by tensorflowbutler** [comment] 2017-12-20 19:13
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-04 19:15
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by dr4b** [comment] 2018-01-06 00:23
I'm trying to figure out the state of this, but I think Mark's still working on the backticks bug?  It still looks like the issue is happening in our C++ docs.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:26
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wolffg** [comment] 2018-02-07 23:52
This is a preprocessing bug.  Tracking this as internal bug #62161343.

**Comment by tensorflowbutler** [comment] 2018-02-22 13:10
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-09 13:39
Nagging Assignees @MarkDaoust, @dr4b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 03:48
Nagging Assignees @MarkDaoust, @dr4b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MarkDaoust** [comment] 2018-04-03 23:15
Fixed.

**Closed by MarkDaoust** 2018-04-03 23:15 UTC
Labels: type:docs
