### ISSUE TITLE
EfficientNet models from TensorFlow.Keras not being reproducible on GPU

### ISSUE THREAD

**Issue by mhaghighat** [tensorflow/tensorflow#47174] opened 2021-02-16 02:07 UTC
After downloading an EfficientNet model from [tensorflow.keras.applications.efficientnet][1], and retraining it on our own data, I've noticed that the results are not reproducible. The results are reproducible for other architectures like *VGG16*, *ResNet101*, *InceptionV3*, and *InceptionResNetV2*, but not for any of the *EfficientNetBx* models.

Please note that I've set all the following seeds, and even have tensorflow-determinism:

    random.seed(1)
    np.random.seed(1)
    tf.random.set_seed(1)
    os.environ['TF_CUDNN_DETERMINISTIC'] = TRUE
    os.environ['TF_DETERMINISTIC_OPS'] = TRUE

TensorFlow Version:  tensorflow-gpu==2.3

  [1]: https://www.tensorflow.org/api_docs/python/tf/keras/applications/efficientnet

**Comment by Saduf2019** [comment] 2021-02-16 08:05
@mhaghighat 
Please share simple indented stand alone code with all dependencies to replicate the issue or if possible share a colab gist with the error reported.

**Comment by mhaghighat** [comment] 2021-02-16 16:47
```
import os
import numpy as np
import tensorflow as tf

np.random.seed(1)
tf.random.set_seed(2)
os.environ['TF_CUDNN_DETERMINISTIC'] = 'true'
os.environ['TF_DETERMINISTIC_OPS'] = 'true'

tf.config.threading.set_inter_op_parallelism_threads(1)
tf.config.threading.set_intra_op_parallelism_threads(1)

from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from keras.utils import np_utils
from keras.optimizers import SGD
from keras.callbacks import CSVLogger

csv_logger = CSVLogger('log.csv', append=True, separator=';')

batch_size = 32 # 32 examples in a mini-batch, smaller batch size means more updates in one epoch
num_classes = 10#
epochs = 3# repeat 200 times
data_augmentation = True


## Model 
input_shape = (32,32,3)
base_model  = tf.keras.applications.efficientnet.EfficientNetB0(include_top=False, weights="imagenet", input_shape=input_shape)
#base_model = tf.keras.applications.VGG16(include_top=False, weights="imagenet", input_shape=input_shape)
#base_model = tf.keras.applications.ResNet101(include_top=False, weights="imagenet", input_shape=input_shape)
#base_model = tf.keras.applications.MobileNetV2(include_top=False, weights="imagenet", input_shape=input_shape)
#base_model = tf.keras.applications.MobileNet(include_top=False, weights="imagenet", input_shape=input_shape)

initializer = tf.keras.initializers.GlorotUniform(seed=1)
regularizer = tf.keras.regularizers.l2(0.0001) # 0.0001
global_average_layer = layers.GlobalAveragePooling2D()
flatten_layer = layers.Flatten()
dense_layer = layers.Dense(10, use_bias=False, kernel_initializer=initializer, bias_initializer='zeros', name='Bottleneck', activation='softmax')

Model  = tf.keras.Sequential([base_model, global_average_layer, flatten_layer, dense_layer])


## Training Data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
class_names = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
y_train = np_utils.to_categorical(y_train, num_classes)
y_test = np_utils.to_categorical(y_test, num_classes)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train  /= 255
x_test /= 255


## Training
sgd = SGD(lr=0.01, momentum=0.9, decay=1e-6, nesterov=False)
Model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
cnn = Model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test,y_test), shuffle=False,callbacks=[csv_logger])

```

**Comment by Saduf2019** [comment] 2021-02-17 11:00
@mhaghighat 
I ran the code on tf 2.3 ,2.4 and nightly with gpu and it did reproduce output, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/67ce5f207dccd8b28d5593532bb569fc/untitled541.ipynb).

**Comment by mhaghighat** [comment] 2021-02-17 16:50
@Saduf2019 
Looking at your experiments, I can see that it is NOT reproducible for you either. The losses are different for each run. For example, the loss after the first epoch is 2.2377,  2.1338, and 1.9896 for the first, second, and third runs, respectively.

**Comment by jvishnuvardhan** [comment] 2021-02-19 02:53
@mhaghighat I ran your code two times restarting the kernel when I ran second time. I see the results are reproducible. Please check the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/4c12e097430d9ef78ea1bd19d63bac39/untitled541.ipynb).

I got these results (first time)
```
# First time these are the results. After these results I ran one more time and the results are above
Epoch 1/3
1563/1563 [==============================] - 511s 323ms/step - loss: 2.1790 - accuracy: 0.2155 - val_loss: 3.5879 - val_accuracy: 0.1000
Epoch 2/3
1563/1563 [==============================] - 495s 317ms/step - loss: 1.6280 - accuracy: 0.4084 - val_loss: 5.4849 - val_accuracy: 0.1000
Epoch 3/3
1563/1563 [==============================] - 496s 318ms/step - loss: 1.4605 - accuracy: 0.4793 - val_loss: 4.0663 - val_accuracy: 0.1000
```

Restarted kernel and ran again (second time) and noticed these results are reproducible. Please let me know if I am missing anything. Thanks!
```
Epoch 1/3
1563/1563 [==============================] - 544s 344ms/step - loss: 2.1790 - accuracy: 0.2155 - val_loss: 3.5879 - val_accuracy: 0.1000
Epoch 2/3
1563/1563 [==============================] - 506s 324ms/step - loss: 1.6280 - accuracy: 0.4084 - val_loss: 5.4849 - val_accuracy: 0.1000
Epoch 3/3
1563/1563 [==============================] - 514s 329ms/step - loss: 1.4605 - accuracy: 0.4793 - val_loss: 4.0663 - val_accuracy: 0.1000
```

**Comment by mhaghighat** [comment] 2021-02-19 21:50
@jvishnuvardhan : The reason you are getting reproducible results is that you have installed the `tf-nightly` version, which runs on CPU. Using the GPU version (updated [your gist](https://colab.research.google.com/gist/jvishnuvardhan/4c12e097430d9ef78ea1bd19d63bac39/untitled541.ipynb#scrollTo=CgYNUohtr9Kf)), I am getting different results for each run.
I got these results (first time):
```
Epoch 1/3
1563/1563 [==============================] - 43s 27ms/step - loss: 1.8422 - accuracy: 0.3357 - val_loss: 2.4678 - val_accuracy: 0.1021
Epoch 2/3
1563/1563 [==============================] - 42s 27ms/step - loss: 1.3999 - accuracy: 0.5037 - val_loss: 2.6971 - val_accuracy: 0.0991
Epoch 3/3
1563/1563 [==============================] - 41s 26ms/step - loss: 1.1729 - accuracy: 0.5852 - val_loss: 2.3490 - val_accuracy: 0.1156
```
And the second time:
```
Epoch 1/3
1563/1563 [==============================] - 42s 27ms/step - loss: 1.9248 - accuracy: 0.3008 - val_loss: 2.4087 - val_accuracy: 0.0989
Epoch 2/3
1563/1563 [==============================] - 42s 27ms/step - loss: 1.5121 - accuracy: 0.4559 - val_loss: 3.2401 - val_accuracy: 0.1014
Epoch 3/3
1563/1563 [==============================] - 42s 27ms/step - loss: 1.2872 - accuracy: 0.5445 - val_loss: 2.9831 - val_accuracy: 0.1000
```

**Comment by jvishnuvardhan** [comment] 2021-02-20 00:23
@mhaghighat Can you please try with `tf-nightly-gpu`? I tried with ` tf-nightly-gpu` and I see same reproducible results as I had shown earlier. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/92d00558c2e8a4a22d06505eb49bf8d0/untitled541.ipynb).  Thanks!

Also, I noticed that this is an issue with `TF2.3`. I think this was resolved in recent `tf-nightly`. Please check the [gist](https://colab.research.google.com/gist/jvishnuvardhan/4480849ce2b9852f37a2858521b1e619/untitled541.ipynb) with `TF2.3`. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-02-20 01:15
I can also see reproducibility with `TF2.4-gpu`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1edb2d0c2e0468984184c2ae93823f70/untitled541.ipynb). Thanks!

**Comment by mhaghighat** [comment] 2021-02-20 02:27
@jvishnuvardhan : I noticed that your run-times are around 500s for each epoch. For some reason, your kernel is still running the tf-cpu. Using the GPU, each epoch takes around 42s. To make sure you are running the tf-gpu, please add this check after your tensorflow import:

```
if tf.test.gpu_device_name():
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
else:
    print("Please install GPU version of TF!")
```

**Comment by mhaghighat** [comment] 2021-03-16 22:33
@ymodak @jvishnuvardhan Any updates on this issue?

**Comment by nasirml** [comment] 2021-03-22 20:29
I am also having the same issue to reproduce the results of EfficientNet models. Just wondering if anyone has updates on this?

**Comment by hpshah459** [comment] 2021-03-23 18:45
I am facing similar issue with the EfficientNet models. Not able to reproduce to result when using `tf-gpu`.

**Comment by saqibns** [comment] 2021-03-31 10:24
Facing the same problem. Any updates on this yet?

**Comment by reedwm** [comment] 2021-04-06 19:14
I think this is caused by https://github.com/tensorflow/tensorflow/issues/38185, so closing as a duplicate.

@duncanriach is working on making `tf.nn.softmax_cross_entropy_with_logits` deterministic.

**Comment by mhaghighat** [comment] 2021-04-09 17:26
I don't think this issue is related to the GPU-deterministic backprop. I already have the [tensorflow-determinism](https://github.com/NVIDIA/framework-determinism) installed and the results are reproducible for other architectures like _VGG16_, _ResNet101_, _InceptionV3_, and _InceptionResNetV2_, which use the same backprop. This issue is unique to the EfficientNet models.

**Comment by reedwm** [comment] 2021-04-09 19:04
`tf.nn.softmax_cross_entropy_with_logits` is being called, which is nondeterministic. But if I replace it with a softmax followed by a cross-entropy, which is nondeterministic, the model still has nondeterminism. So there's another determinism issue, so I'll reopen.

@duncanriach is adding errors to all currently known nondeterministic ops when `TF_DETERMINISTIC_OPS` is used (@duncanriach, let me know if you want help with this). Once that is done, it will be easy to identify the source of the nondeterminisim.

**Comment by duncanriach** [comment] 2021-04-13 01:08
[Disclosure: I have not (yet) run this code and debugged the source of nondeterminism. The following is just from looking at the models.]

1. The above code implements the currently recommended [workaround](https://github.com/NVIDIA/framework-determinism/blob/master/tensorflow_status.md#softmax-xent) for fused softmax/cross-entropy nondeterminism by configuring the final `dense_layer` to have a `'softmax'` activation. This explains why the other four architectures operate deterministically even though they use that loss function.
2. Several of these model architectures use `tf.keras.layers.BatchNormalization` which, [when used for fine-tuning](https://github.com/NVIDIA/framework-determinism/blob/master/tensorflow_status.md#fused-batch-norm), will introduce nondeterminism in the backprop. This is something that @reedwm discovered recently. However, all of these models are being trained using `model.fit()` and I don't think that the `is_training` parameter of the underlying op is ever getting to set to `True` while gradients are being generated. The batch-norms are being used in inference mode, during the evaluation step, but in those cases the gradients are not being used. So, I don't think that batch-norm is the issue here.
3. No other significant differences currently stand-out to me between these model architectures (e.g. more than one of them uses dropout, so I'm assuming that it's being initialized correctly even in the troublesome model architecture).
4.  I'm wondering if there is one or more fields missing in the loaded initialization state for EfficientNet. Whenever attempting to achieve reproducibility, it's always good to start by confirming that the initial state is reproducible. After calling `Model.compile`, please will you (@mhaghighat) confirm that the trainable variables are reproducible by calling the following function.

```
def summarize_keras_trainable_variables(model, message):
  s = sum(map(lambda x: x.sum(), model.get_weights()))
  print(“summary of trainable variables %s” % message)
  return s
```

**Comment by mhaghighat** [comment] 2021-04-14 22:43
Thank you, @duncandean. Using your suggested function, I checked the model state after the compilation, and it is the same for multiple runs. So, the initial state is reproducible. 
My guess is that the problem is related to the `DepthwiseConv2D` layers. They only exist in EfficientNet and MobileNet architectures, and neither of them are reproducible.

**Comment by duncanriach** [comment] 2021-04-15 02:23
@mhaghighat, well spotted. I missed that. I had also assumed that all the commented-out model architectures were operating deterministically. Now I see that the list in the code does not match the list in your original comment.

`tf.keras.layers.DepthwiseConv2D` and `tf.nn.depthwise_conv2d`, upon which it is built, are suspect, as you probably saw [here](https://github.com/NVIDIA/framework-determinism#other-possible-gpu-specific-sources-of-non-determinism). This op has shown up in other model architectures that I'm aware of as being a probable source of truly random noise. However, I have not yet gotten around to creating a reproducer for it. I will task myself with that and prioritize it. I'll return here with findings.

The first-order work-around I can think of is to force the underlying op to run on the CPU, which will slow training down a bit, but not as much as running the whole model on the CPU.

Try running the following code near the beginning of your program (before training). I have not run this code, and I'm not sure that the generic all-arg-passing will work. You might need to pass the args explicitly. There might be other bugs. Please let me know how it goes.

```
from tensorflow.python.ops import nn
x = nn.depthwise_conv2d

def cpu_op(*args, **kwargs):
  tf.device('/cpu:0'):
    x(args, kwargs)

nn.depthwise_conv2d = cpu_op
```

**Comment by mhaghighat** [comment] 2021-04-15 19:40
@duncanriach: I couldn't separate that op run on the CPU. I tried different ways to pass the arguments but no success so far. 
Would you mind taking a look at it in this [notebook](https://colab.research.google.com/gist/mhaghighat/5d6d33b78531ccf9664501dc166508d4/untitled541.ipynb).
Thanks!

**Comment by duncanriach** [comment] 2021-04-15 22:52
@mhaghighat, thanks for making this really easy for me to help.

The call to `x` needed to look like this: `x(*args, **kwargs)` to unpack the `args` and `kwargs`. I have changed the code above to be the working version, including returning the result the call to `x`, which you discovered was necessary.

The model now train. Step time increased from 27ms (all on GPU) to 100ms (DepthwiseConv2D on CPU), but it's not as slow as 320ms (everything on CPU).

However, this does not seem to have resolved the nondeterminism.

**Comment by duncanriach** [comment] 2021-04-16 00:46
In this [notebook](https://colab.research.google.com/gist/duncanriach/7d783b073cb9615320d4ae0ba1680a9a/untitled541.ipynb), I have simplified things so that the model will run twice in a few seconds. I have also included some code and instructions for hiding the GPU. I spent a while trying to identify what the remaining source of nondeterminism might be. Since the model trains reproducibly on CPU, it's almost certainly a nondeterministic op. My next step would be to clone the model code and use the debug tool that I have to isolate the source. I have to go do some other urgent things and I'll come back to this.

**Comment by nasirml** [comment] 2021-04-19 08:15
@duncanriach 
It's probably not the BatchNormalization. As a point of reference, InceptionResNetV2 model, which is reproducible in GPU, has BatchNormalization layer (and so does ResNet101). 

In case it is helpful, following layers are unique to the EfficientNetB0 in comparison to the InceptionResNetV2: 
`Rescaling`
`Normalization`
`ZeroPadding2D`
`DepthwiseConv2D`
`GlobalAveragePooling2D`
`Reshape`
`Multiply`
`Dropout` and
`Add`

My initial guess was the `Dropout` layer that is causing the reproducibility issue, as dropout has an inherent randomness to it. I did try to freeze the randomness in the dropout layers by setting `layer.seed = 1` and `layer.dropout_rate = 0.0`. But it did not solve the reproducibility issue either.

According to the discussion so far, and, as you suggest, it can be Normalization that is causing the issue. Although, MobileNet architectures do not have Normalization layer and yet they are not reproducible. 

May be we are missing something else?

**Comment by duncanriach** [comment] 2021-04-20 23:40
Thanks for digging deeper, @nasirml; that's very helpful.

It is possible the the model architectures are using BatchNormalization differently. If BatchNormalization is configured for [fine-tuning](https://github.com/NVIDIA/framework-determinism/blob/master/tensorflow_status.md#fused-batch-norm), then it would introduce nondeterminism. I have yet to clarify (and document) the configuration mapping with respect to this between `tf.compat.v1.nn.fused_batch_norm` and `tf.keras.layers.BatchNormalization`.

**Comment by duncanriach** [comment] 2021-04-28 04:05
I'm returning here with findings on a repro for `tf.keras.layers.DepthwiseConv2D` nondeterminism, as promised in [this previous comment](https://github.com/tensorflow/tensorflow/issues/47174#issuecomment-820009465).

Please see [this gist](https://gist.github.com/duncanriach/4c18cb07a73510c5fcb2deb52adbffaa) for a complete repro, forward and backward, CPU and GPU. I'll copy/paste the findings here:

This repro demonstrates that:

1. `tf.nn.depthwise_conv2d` operates deterministically* in the forward direction when running on both CPU and GPU;
2. when running on CPU, `tf.nn.depthwise_conv2d` operates deterministically* in backprop to both input and filter;
3. when running on GPU and when op-determinism is expected, `tf.nn.depthwise_conv2d` operates deterministically* in backprop to input;
4. when running on GPU and when op-determinism is expected, `tf.nn.depthwise_conv2d` operates determinsitically* in backprop to filter when it is using cuDNN convolution (more info below);
5. when running on GPU and when op-determinism is expected, `tf.nn.depthwise_conv2d` operates nondeterminstically* in backprop to filter when it is not using cuDNN convolution (more info below); and
6. when running on GPU and when op-determinism is not expected, operation* is as would be expected given that cuDNN backprop algorithms to both input and filter operate nondeterministically* by default and the specialized algorithms for depthwise conv operate deterministically* in backprop to input and nondeterministically* in backprop to filter.

*: for the tested parameters

"when op-determinism is expected" currently means when `TF_DETERMINISTIC_OPS` is set to `"true"` or `"1"`

"when op-determinism is not expected" currently means when `TF_DETERMINISTIC_OPS` either has not been set or has been set to `"false"` or `"0"`.

cuDNN convolution is selected when there is only one input channel and cuDNN supports the desired filter dimensions and number of output channels.

`tf.keras.layers.DepthwiseConv2D` uses `tf.nn.depthwise_conv2d` simply and direcly. Therefore, any assertions about the latter apply equally to the former.

The findings above are summarised in the following table, where `D` stands for deterministic and `ND` stands for nondeterministic:

```
    | col                     |  1  |  2  |  3  |  4  |  5
    | device                  | CPU | GPU | GPU | GPU | GPU
    | op-determinism expected |     |  Y  |  Y  |  N  |  N
row | cuDNN used              |     |  Y  |  N  |  Y  |  N
====o=========================o=====o=====o=====o=====o====
 1  | forward                 |  D  |  D  |  D  |  D  |  D
 2  | backprop to input       |  D  |  D  |  D  |  ND |  D
 3  | backprop to filter      |  D  |  D  |  ND |  ND |  ND
```

Note that the only problematic case here is the cell at row 3, col 3 (GPU, op-determinism expected, cuDNN not used) because we expect op-determinism and we're not getting it. On the other hand, we clearly don't care about nondeterminism when op-determinism is not expected (i.e. col 4 and col 5).

For GPU functionality, these findings are consistent with looking at the code, in which the CUDA kernel for the depthwise backprop to filter uses CUDA atomicAdd and the CUDA kernel for the depthwise backprop to input does not. For CPU functionality, some of the implementation code uses multi-threaded sharding, but that doesn't appear to result in nondeterminism, which is not unusual.

So far in this discussion, cuDNN auto-tuning has not been considered. cuDNN auto-tuning would not (and should not) be disabled in col 4 of the table above (GPU, op-determinism not expected, cuDNN used). Therefore, the `D` at col 4, row 1 is not actually correct: auto-tuning could (and ultimately would) introduce nondeterminism.

Finally, while looking at the code-paths via which `tf.nn.depthwise_conv2d` uses cuDNN convolution (e.g. in `conv_grad_filter_ops.cc`), it seems that there might be other (perhaps partial) implementations of cuDNN auto-tuning, independent from those used for the regular convolution ops (e.g. `tf.nn.conv2d`). Because it's very difficult (or perhaps impossible) to test that auto-tuning determinism is not present, a careful code-level inspection and understanding of the cuDNN auto-tuning mechanism for this op should be performed as part of addressing nondeterminism in this op.

**Comment by duncanriach** [comment] 2021-09-17 22:51
Update: MR [51920](https://github.com/tensorflow/tensorflow/pull/51920) adds determinism-unimplemented exception-throwing to `tf.nn.depthwise_conv2d`. This will be included in the TF 2.7 release. Meanwhile, you can try the latest determinism functionality in top-of-tree by using the `tensorflow/tensorflow:nifgtly-gpu` Docker container image.

**Comment by mhaghighat** [comment] 2021-10-01 18:21
For some reason, when I install the `tf-nightly-gpu`, it doesn't see the GPU. It acts as the CPU version, and it returns null for `tf.test.gpu_device_name()`. I don't have this problem with r2.6 on the same device. We thought maybe it is CUDA incompatibility and tried other versions of CUDA, but it didn't help. I hope r2.7 releases soon and it won't have this issue.

**Comment by mhaghighat** [comment] 2021-11-08 22:42
I installed the released tensorflow-gpu==2.7. This version throws an error when the determinism flag is on (`os.environ['TF_DETERMINISTIC_OPS'] = '1'`): 
```
  File "/home/mo/anaconda3/envs/tf27/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/mo/anaconda3/envs/tf27/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError:  A deterministic GPU implementation of DepthwiseConvBackpropFilter is not currently available.
	 [[node gradient_tape/efficientnet-lite0/efficientnet-lite0/model/blocks_15/depthwise_conv2d/depthwise_0/depthwise/DepthwiseConv2dNativeBackpropFilter
 (defined at /home/mo/whr/tmp/food2vec/magnet_loss/train.py:151)
]] [Op:__inference_train_step_19847]
```
And if I comment out the line regarding TF_DETERMINISTIC_OPS, the results are still not reproducible.

**Comment by duncanriach** [comment] 2021-11-11 04:47
Thank you for letting us know, @mhaghighat. This is expected and correct behavior. This confirms that the model is attempting to use `tf.nn.depthwise_conv2d` (as we suspected), which does not currently (or yet) have a deterministic GPU implementation. I'm going to make a note of this with the intention that this use-case can be taken into consideration as part of prioritizing a deterministic GPU implementation. It may be possible to implement an acceptable, though perhaps non-optimal, solution using the cuDNN-based non-depthwise convolution ops, which _can_ operate nondeterministically.

@reedwm, this is just something for us to consider: if this exception could be easily disabled, then it would be possible to run further into the model and thereby discover if there are other ops for which there is not yet a deterministic implementation. I'm wondering if it makes sense to have a per-op switch that selects [A] exception (default), [B] skip exception and run on default device (e.g. GPU), and [C] skip exception and run on "slower" device (e.g. CPU).

**Comment by reedwm** [comment] 2021-11-11 20:13
In principle I think adding such a per-op switch is sensible, but it is difficult to justify adding an API to do this because eventually we hope to make all ops deterministic. For now, I think we should try fixing such ops or unconditionally implementing [C] when determinism is enabled.

Unfortunately, [C] is surprisingly difficult to implement. For Scatter ops, I added some code to do this, but it required writing a [fairly long function](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/scatter_nd_op.cc) which manually copies tensors to the CPU, runs the CPU version of the op, then copying outputs back to the GPU. 

Instead, we could register a GPU kernel that runs on the CPU, by marking all inputs/outputs on host memory and using the CPU implementation, but there's currently no way to get such kernels to run if and only if determinism is enabled. Perhaps we should add a way, but it would be difficult since normally the set of kernels that can be run can is determined once per graph, but determinism can be enabled after a graph is already run. In any case, it's probably a bad idea to run depthwise conv ops on the CPU since I think these ops often make up a significant portion of a model and running them on the CPU might slow it down significantly.

For depthwise conv2d specifically, I wonder if it's possible to always use cuDNN when determinism is enabled. I can't find any reference in the cudnn documentation that states depthwise convolutions are only supported for certain shapes

**Comment by duncanriach** [comment] 2021-11-23 05:31
Thank you for describing all of that, @reedwm.

**Exception Throwing**

I agree that the exception-throwing is intended to be temporary and it's also a mechanism for flagging important ops that we want to provide deterministic GPU implementations for, a user-accessible nondeterminism debugging tool to help us prioritize effort. In a model with more than one op without a deterministic GPU implementation, it would be preferable to be able to hit all the exceptions (or confirm that there are no others).

I'm wondering if a good middle-ground would be to add an environment-variable-based exception-disable switch to ops on a case-by-case bass. One of these [was added](https://github.com/tensorflow/tensorflow/pull/47925/files#diff-28078d1a90c8ab6eece5f8b54883114f6e8a4e20f87fd5ccf44627fa1e0c11c1R66-R75) for `tf.nn.softmax_cross_entropy_with_logits` before it ran deterministically on the GPU, so that it could be used for a higher-level determinism work-around. A similar disable switch could be added for tf.nn.depthwise_conv2d (without testing) very easily and then be available in the nightly build. Then @mhaghighat could confirm that `tf.nn.depthwise_conv2d` is the only remaining op preventing this model from operating deterministically.

**Depthwise Convolution using cuDNN**

Are you suggesting using cuDNN grouped convolutions to implement depthwise convolution? On the surface, that seems to be possible. Regarding restrictions on shapes, I remember there being shape restrictions on when cuDNN is used in the existing algorithm for the single-input-channel cases, in which depthwise convolution and regular convolution are the same thing. I find it hard to believe that cuDNN doesn't support all the required shapes.

Another possibility might be to implement diagonalwise refactorization as described in [this 2018 paper](https://arxiv.org/pdf/1803.09926.pdf). This is the kind of thing I was beginning to think about in [this earlier comment](https://github.com/tensorflow/tensorflow/issues/47174#issuecomment-965986440) and I'm so happy to find that it's already fleshed out. But I wonder if this would actually be equivalent to using grouped convolution in terms of how the underlying computation gets done, and so therefore have similar performance.

Either way, shouldn't it be possible to delegate to the regular conv2d op, which should handle any shapes that might be needed? But does the regular conv2d op take a groupCount parameter at the API level from which we would be calling it?

**Comment by duncanriach** [comment] 2022-02-03 00:27
@mhaghighat, PR [54119](https://github.com/tensorflow/tensorflow/pull/54119) added a disable switch for the exception. Please will you run again using the `tensorflow/tensorflow:latest-gpu` docker image (I think that will have the change in it). Enable determinism using [`tf.config.experimental.enable_op_determinism`](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism) rather than `TF_DETERMINISTIC_OPS`. Also, disable the `tf.nn.depthwise_conv2d` exception by setting `TF_DISABLE_DEPTHWISE_CONV_DETERMINISM_EXCEPTIONS` to `"true"` or `"1"`.

I want to see if another determinism-unimplemented exception is thrown, or if `tf.nn.depthwise_conv2d` is the only op that is now preventing this model from operating deterministically.

**Comment by jvishnuvardhan** [comment] 2022-02-04 05:57
@mhaghighat Can you please check @duncanriach suggestions and respond with your findings? Thanks

**Comment by duncanriach** [comment] 2022-02-16 23:56
Let's not close this. I intend to execute the experiment I asked for [above](https://github.com/tensorflow/tensorflow/issues/47174#issuecomment-1028486016). I will return here with the result from that.

**Comment by duncanriach** [comment] 2022-02-19 03:50
By disabling the exception on `tf.nn.depwise_conv2d`, I have confirmed that it is the only remaining nondeterministic op standing in the way of the EfficientNet models operating fully reproducibly on GPU. @reedwm, I intend to start work on making this op function deterministically on GPU.

**Comment by edwardyehuang** [comment] 2022-03-12 13:55
> By disabling the exception on `tf.nn.depwise_conv2d`, I have confirmed that it is the only remaining nondeterministic op standing in the way of the EfficientNet models operating fully reproducibly on GPU. @reedwm, I intend to start work on making this op function deterministically on GPU.

Why my EfficientNet model can be reproduced in 2.8? I also did not use the TF_DISABLE_DEPTHWISE_CONV_DETERMINISM_EXCEPTIONS ? @duncanriach ?

Let me confirm again, tonight

**Comment by duncanriach** [comment] 2022-03-14 21:39
@edwardyehuang, to trigger the determinism-unimplemented exception in `tf.nn.depthwise_conv2d` (in TensorFlow version 2.8) your model must use the back-prop paths through the GPU implementation of the op. It's possible to run GPU inference only or train on CPU using the op without the exception being thrown. Please confirm that you're definitely _training_ your models on _GPU_.

**Comment by edwardyehuang** [comment] 2022-03-15 02:06
> @edwardyehuang, to trigger the determinism-unimplemented exception in `tf.nn.depthwise_conv2d` (in TensorFlow version 2.8) your model must use the back-prop paths through the GPU implementation of the op. It's possible to run GPU inference only or train on CPU using the op without the exception being thrown. Please confirm that you're definitely _training_ your models on _GPU_.

I am using keras.mode.fit and tf.distribute.MirroredStrategy on 8 GPUs

**Comment by duncanriach** [comment] 2022-03-17 00:08
@edwardyehuang, the original repro program for this issue uses `tf.keras.applications.efficientnet.EfficientNetB0`, not B5 or B7, but I just ran the repro program with B0, B5, and B7 on TF version 2.9.0-dev20220316 and again reproduced the issue on all three versions of the program, confirming that the nondeterministic path is certainly being traversed by the repro program (as evidenced by both the exception and by nondeterminism when the exception is disabled).

Your program(s) appears to not be traversing the nondeterministic GPU backprop-to-filter path of `tf.nn.depthwise_conv2d`. If it was, the exception would be getting thrown. There are several possible reasons for that path to not get traversed, such as the cases where the operation is delegated to cuDNN. If your program is not traversing that path, but is operating correctly, then I wouldn't worry too much about it; it's fortunate.

If you're concerned that your program is not doing what you intend it to be doing, I recommend taking a look at the `tf.keras.layers.DepthwiseConv2D` filter weights for each instance in your model and checking that they're different between before and after training and that the weights are not all the same value after training. You could also stub-out, or change the parameters of, the depthwise convolution layers to at least confirm that they are contributing roughly as expected to the overall performance of your model.

Do you have any concerns specifically with regard to this current issue?

**Comment by edwardyehuang** [comment] 2022-03-17 02:32
> 

I don't have concerns anymore. However, can you explain " the cases where the operation is delegated to cuDNN" for me? Or provide me some link/topic to read. In my weak knowledge, I used to think the GPU operation in TensorFlow only has a single implementation.

**Comment by duncanriach** [comment] 2022-03-17 23:01
@edwardyehuang, the CUDA GPU functionality of any given op in TensorFlow is implemented using one or more (usually several) different CUDA kernels; for some ops, different CUDA kernels are used for different sections of the op parameter space. Some ops use functionality provided via the cuDNN library, which, in turn, often uses different underlying CUDA kernels (also referred to as algorithms in the cuDNN documentation) for different sections of the op parameter space. This particular op (`tf.nn.depthwize_conv2d`) depends on several custom CUDA kernels, but delegates to the convolution machinery in TensorFlow that is based on cuDNN when possible. [This earlier comment](https://github.com/tensorflow/tensorflow/issues/47174#issuecomment-828126821) from me in this current issue documents the partitioning between the functionality that is based on cuDNN versus the functionality that is not.

**Comment by duncanriach** [comment] 2022-04-30 00:49
Using docker image `tensorflow/tensorflow:2.10.0-dev20220427` I have confirmed that PR [55657](https://github.com/tensorflow/tensorflow/pull/55657) allows EfficientNetB0, B5, and B7 to operate deterministically on GPU (when op-determinism is enabled via [`tf.config.experimental.enable_op_determinism`](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism)).

This issue can now be closed.

**Closed** 2022-05-03 19:07 UTC
Labels: type:bug, comp:keras, comp:gpu, TF 2.3, TF 2.4
