### ISSUE TITLE
Feature request: Return true labels from `estimator.predict(...)`

### ISSUE THREAD

**Issue by lhlmgr** [tensorflow/tensorflow#17824] opened 2018-03-19 13:48 UTC
Hello everyone,

As mentioned in the [Getting started with Tensorflow / Custom Estimators](https://www.tensorflow.org/get_started/custom_estimators#implement_training_evaluation_and_prediction) one has to know the expected label for the data, since the labels will be discarded during the `predict()` function.

```python
# Generate predictions from the model
expected = ['Setosa', 'Versicolor', 'Virginica']
predict_x = {
    'SepalLength': [5.1, 5.9, 6.9],
    'SepalWidth': [3.3, 3.0, 3.1],
    'PetalLength': [1.7, 4.2, 5.4],
    'PetalWidth': [0.5, 1.5, 2.1],
}

predictions = classifier.predict(
    input_fn=lambda:iris_data.eval_input_fn(predict_x,
                                            batch_size=args.batch_size))
```

which can be seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L486)

```python
     features, input_hooks = self._get_features_from_input_fn(
        input_fn, model_fn_lib.ModeKeys.PREDICT)
    estimator_spec = self._call_model_fn(
        features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
```

I totally agree to discard the labels, and don't pass them to the `model_fn` function. However, it would be much easier to return them also from the `input_fn`-function, if they are provided. A simplified solution, without the case distinction of given/not given labels, could be:

```python
  def predict(self,
              input_fn,
              predict_keys=None,
              hooks=None,
              checkpoint_path=None):
    """Yields predictions for given features.

    Args:
      input_fn: A function that constructs the features. Prediction continues
        until `input_fn` raises an end-of-input exception (`OutOfRangeError` or
        `StopIteration`).
        See @{$get_started/premade_estimators#create_input_functions} for more
        information. The function should construct and return one of
        the following:

          * A 'tf.data.Dataset' object: Outputs of `Dataset` object must have
            same constraints as below.
          * features: A `Tensor` or a dictionary of string feature name to
            `Tensor`. features are consumed by `model_fn`. They should satisfy
            the expectation of `model_fn` from inputs.
          * A tuple, in which case the first item is extracted as features.

      predict_keys: list of `str`, name of the keys to predict. It is used if
        the `EstimatorSpec.predictions` is a `dict`. If `predict_keys` is used
        then rest of the predictions will be filtered from the dictionary. If
        `None`, returns all.
      hooks: List of `SessionRunHook` subclass instances. Used for callbacks
        inside the prediction call.
      checkpoint_path: Path of a specific checkpoint to predict. If `None`, the
        latest checkpoint in `model_dir` is used.

    Yields:
      Evaluated values of `predictions` tensors.

    Raises:
      ValueError: Could not find a trained model in model_dir.
      ValueError: if batch length of predictions are not same.
      ValueError: If there is a conflict between `predict_keys` and
        `predictions`. For example if `predict_keys` is not `None` but
        `EstimatorSpec.predictions` is not a `dict`.
    """
    hooks = _check_hooks_type(hooks)
    # Check that model has been trained.
    if not checkpoint_path:
      checkpoint_path = saver.latest_checkpoint(self._model_dir)
    if not checkpoint_path:
      raise ValueError('Could not find trained model in model_dir: {}.'.format(
          self._model_dir))

    with ops.Graph().as_default() as g:
      random_seed.set_random_seed(self._config.tf_random_seed)
      self._create_and_assert_global_step(g)
      features, labels, input_hooks = self._get_features_and_labels_from_input_fn(
          input_fn, model_fn_lib.ModeKeys.PREDICT)
      estimator_spec = self._call_model_fn(
          features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
      predictions = self._extract_keys(estimator_spec.predictions, predict_keys)
      all_hooks = list(input_hooks)
      all_hooks.extend(hooks)
      all_hooks.extend(list(estimator_spec.prediction_hooks or []))
      with training.MonitoredSession(
          session_creator=training.ChiefSessionCreator(
              checkpoint_filename_with_path=checkpoint_path,
              master=self._config.master,
              scaffold=estimator_spec.scaffold,
              config=self._session_config),
          hooks=all_hooks) as mon_sess:
        while not mon_sess.should_stop():
          preds_evaluated, gt_labels = mon_sess.run([predictions, labels])
          if not isinstance(predictions, dict):
            for pred, true_label in zip(preds_evaluated, gt_labels):
              yield pred, true_label
          else:
            for i in range(self._extract_batch_length(preds_evaluated)):
              yield {
                  key: value[i]
                  for key, value in six.iteritems(preds_evaluated)
              }, gt_labels[i]
```

OS Platform and Distribution
> Ubuntu 16.04.3 LTS

TensorFlow installed from
> pip

TensorFlow version
>  tensorflow-gpu '1.6.0'

Bazel version
> N/A

CUDA/cuDNN version
> N/A

GPU model and memory
> N/A

Exact command to reproduce
> N/A

**Comment by tensorflowbutler** [comment] 2018-03-20 01:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tatianashp** [comment] 2018-03-22 01:31
@martinwicke Could you please comment on this suggestion?

**Comment by ispirmustafa** [comment] 2018-04-02 16:59
Hi @lhlmgr 
I think this should be handled as part of evaluation but not prediction. Do you have any suggestion if about how can we do it as evaluation?
thanks

**Comment by lhlmgr** [comment] 2018-04-17 13:00
Hi @ispirmustafa,
Sorry, I guess I don't understand exactly what you mean by "should be handled as part of evaluation". 

The case I have in mind is the following: I want to predict e.g. a class `y_hat` for sample `x`, or I want to retrieve the generated image `x_hat` (in case of an auto-encoder). And to compare it with the true class / image I want access to the true labels without extracting `TFRecord`-Files. For this case, it seems, the evaluation method is the wrong method, or am I mistaken?

Cheers, and thanks!

**Comment by ispirmustafa** [comment] 2018-04-17 21:35
I mean if you're comparing predictions with the labels, which seems evaluation. Having said that what do you think about following solution: add label in to features dict. make it as one of the prediction if it exist in the features dictionary.

**Comment by ChuangLee** [comment] 2018-04-27 11:26
Hi @ispirmustafa 
Here is a case:
 When using Siamese network ,  the loss only make sense when training,  So evaluation won't work because only  losses returned,  we want Euclidean distance or something like to actually evaluate on test data.
I think a sample solution is just passing true labels to "model_fn“.
In estimator.py  line 492~495, if labels is not None, just pass to "model_fn“.

**Comment by ispirmustafa** [comment] 2018-04-27 23:16
Hi @ChuangLee 
we use predict mode for exporting serving graph. providing labels to the `model_fn` in predict mode seems breaking the assumptions.
You can still have `labels` in your network by adding them to `features` dictionary. Does that work?

**Comment by tensorflowbutler** [comment] 2018-05-12 18:32
Nagging Assignee @ispirmustafa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 12:36
Nagging Assignee @ispirmustafa: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by basque21** [comment] 2018-06-08 08:09
hi @ispirmustafa, adding labels in features dictionary doesn't work, it receives labels as None values, and it raises `ValueError: None values not supported.` I'm also interested in getting the labels in prediction mode.

**Comment by ispirmustafa** [comment] 2018-06-08 16:33
@basque21 could you please provide a simple repo of this error?

**Comment by zo7** [comment] 2018-06-11 22:08
It appears that the `labels` arg in `model_fn` is always `None` during prediction even if they are provided by `input_fn`. @ispirmustafa's suggestion doesn't work here because `estimator.predict()` is tossing out labels regardless.

I've run into similar situations where I'd like to get the input and ground truth labels if available alongside predictions to do further analysis (like view failure cases). This is easily done by calling `model_fn` and reading from `input_fn` manually, but it feels hacky to me. It would be nice if there was a high-level way to do this like there is with training and evaluation.

**Comment by lhlmgr** [comment] 2018-06-11 22:57
What @ispirmustafa proposes is that you could pass the `labels` as additional `feature` in your `features`-`dict`.
Something along this lines:

```python
# Generate predictions from the model
def parse_input(x, y):
   features = dict(
      x=x,
      labels=y
   )
   
   return features, y
```

It should definitely work (not tested), but I would also prefer another way.

**Comment by zo7** [comment] 2018-06-12 00:07
Oh! Yeah that would work, but that definitely feels like a hack.

**Comment by tensorflowbutler** [comment] 2018-06-26 12:43
Nagging Assignee @ispirmustafa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-11 12:49
Nagging Assignee @ispirmustafa: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ispirmustafa** [comment] 2018-07-11 13:23
Closing this since there is a workaround.

**Closed by ispirmustafa** 2018-07-11 13:23 UTC
Labels: type:feature

**Comment by areeh** [comment] 2018-08-28 11:32
@ispirmustafa  I consider this very basic functionality for a machine learning library so I am surprised the issue is closed because a workaround exists.

**Comment by lorenzoriano** [comment] 2018-10-13 00:57
I agree, the solution is a very hacky workaround. A better solution would be e.g. to pass a parameter to predict so that it would get the labels when requested.

**Comment by physicsrob** [comment] 2019-02-08 01:08
I'm running into this exact issue, and also agree that this is an important limitation of the estimator API.

**Comment by cag51** [comment] 2019-03-19 23:30
Agree, can't believe it has been a year and we're still waiting on this basic request.

**Comment by prouast** [comment] 2019-03-21 00:39
Bump, I would also like to see this done properly.

**Comment by wenbotse** [comment] 2019-05-10 07:48
Maybe you can take a look at 'bert' code, when define the EstimatorSpec, you can feed the relative values,
      output_spec = tf.contrib.tpu.TPUEstimatorSpec(
          mode=mode,
          predictions={"probabilities": probabilities,
                       "label": label},
          scaffold_fn=scaffold_fn)
get the label after prediction:

result = estimator.predict(input_fn=my_predict_input_fn)
for (i, prediction) in enumerate(result):
        probabilities = prediction["probabilities"]
        label = prediction["label"]
