### ISSUE TITLE
TFlite Converter Error: from tensorflow.lite.toco.python.toco_from_protos import main ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by rambowding** [tensorflow/tensorflow#40121] opened 2020-06-03 12:52 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source): tensorflow 2.2.0 
- Python 3.7.6

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
open("model/train/converted_model.tflite", "wb").write(tflite_quant_model)
print('tflite convert finish')
```

**The output from the converter invocation**

```
Total params: 3,084,997
Trainable params: 3,084,997
Non-trainable params: 0
__________________________________________________________________________________________________
Epoch 1/10
25/25 [==============================] - 2s 79ms/step - loss: 0.6899 - accuracy: 0.6162
Epoch 2/10
25/25 [==============================] - 2s 77ms/step - loss: 0.5860 - accuracy: 0.6862
Epoch 3/10
25/25 [==============================] - 2s 75ms/step - loss: 0.4454 - accuracy: 0.8050
Epoch 4/10
25/25 [==============================] - 2s 76ms/step - loss: 0.2366 - accuracy: 0.9038
Epoch 5/10
25/25 [==============================] - 2s 76ms/step - loss: 0.1573 - accuracy: 0.9400
Epoch 6/10
25/25 [==============================] - 2s 76ms/step - loss: 0.0459 - accuracy: 0.9875
Epoch 7/10
25/25 [==============================] - 2s 76ms/step - loss: 0.0103 - accuracy: 0.9975
Epoch 8/10
25/25 [==============================] - 2s 75ms/step - loss: 0.0634 - accuracy: 0.9725
Epoch 9/10
25/25 [==============================] - 2s 76ms/step - loss: 0.0796 - accuracy: 0.9712
Epoch 10/10
25/25 [==============================] - 2s 75ms/step - loss: 0.0063 - accuracy: 0.9975
Saved trained model at ./model/train/sts_rmsprop_binary_crossentropy_epochs_10.h5 
2020-06-03 20:42:32.237929: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-06-03 20:42:32.238000: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-03 20:42:32.249905: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-03 20:42:32.249928: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.005ms.
2020-06-03 20:42:32.249932: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-03 20:42:32.472526: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-06-03 20:42:32.472630: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-03 20:42:32.594738: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-03 20:42:32.594761: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 66 nodes (-14), 66 edges (-16), time = 79.678ms.
2020-06-03 20:42:32.594766: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 66 nodes (0), 66 edges (0), time = 12.165ms.
Traceback (most recent call last):
  File "sts_v2.py", line 117, in <module>
    tflite_quant_model = converter.convert()
  File "/Users/dingxirong/venv/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 518, in convert
    **converter_kwargs)
  File "/Users/dingxirong/venv/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 496, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/dingxirong/venv/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
Traceback (most recent call last):
  File "/Users/dingxirong/venv/bin/toco_from_protos", line 5, in <module>
    from tensorflow.lite.toco.python.toco_from_protos import main
ModuleNotFoundError: No module named 'tensorflow'

```

**Comment by amahendrakar** [comment] 2020-06-03 13:45
@rambowding,
In order to expedite the trouble-shooting process, could you please provide the complete code and the model you are using, to reproduce the issue reported here. Thanks!

**Comment by rambowding** [comment] 2020-06-04 02:52
> @rambowding,
> In order to expedite the trouble-shooting process, could you please provide the complete code and the model you are using, to reproduce the issue reported here. Thanks!

```
# python 3.7.6, Tensorflow 2.2.0
import tensorflow as tf
import numpy as np
import data_preprocess

# 超参数
MAX_NB_WORDS = 200000
MAX_SEQUENCE_LENGTH = 200
VALIDATION_SPLIT = 0.2
EMBEDDING_DIM = 300

EPOCHS = 10
OPT = 'rmsprop'
LOSS = 'binary_crossentropy'
MODEL_DIR = './model/train/'
MODEL_FORMAT = '.h5'
filename_str = "{}sts_{}_{}_epochs_{}{}"
# 模型文件
MODEL_FILE = filename_str.format(MODEL_DIR, OPT, LOSS,  str(EPOCHS), MODEL_FORMAT)

print('Indexing word vectors.')
embeddings_index = data_preprocess.build_word_embedding()

train_data_file = 'data/train.txt'
s1, s2, score = data_preprocess.read_train_data(train_data_file)
# print('s1=', s1[0])
left, right, texts = data_preprocess.change_for_tokenizer(s1, s2)
# print('left=', left[0])
# print('texts=', texts[:2])
print('Found %s left.' % len(left))
print('Found %s right.' % len(right))
print('Found %s labels.' % len(score))

tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(texts)

seq_left = tokenizer.texts_to_sequences(left)
# print(seq_left)
seq_right = tokenizer.texts_to_sequences(right)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

data_left = tf.keras.preprocessing.sequence.pad_sequences(seq_left, maxlen=MAX_SEQUENCE_LENGTH, truncating='post')
data_right = tf.keras.preprocessing.sequence.pad_sequences(seq_right, maxlen=MAX_SEQUENCE_LENGTH, truncating='post')
score = np.array(score)
# print(data_left)

indices = np.arange(data_left.shape[0])
np.random.shuffle(indices)
data_left = data_left[indices]
data_right = data_right[indices]
score = score[indices]

val_index = int(VALIDATION_SPLIT * data_left.shape[0])
input_train_left = data_left[:-val_index]
input_train_right = data_right[:-val_index]
val_left = data_left[-val_index:]
val_right = data_right[-val_index:]
train_score = score[:-val_index]
val_score = score[-val_index:]

print('Preparing embedding matrix.')
nb_words = min(MAX_NB_WORDS, len(word_index))
embedding_matrix = np.zeros((nb_words + 1, EMBEDDING_DIM))
for word, i in word_index.items():
    if i > MAX_NB_WORDS:
        continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

print('Training model.')
tweet_a = tf.keras.Input(shape=(MAX_SEQUENCE_LENGTH,))
tweet_b = tf.keras.Input(shape=(MAX_SEQUENCE_LENGTH,))
tweet_input = tf.keras.Input(shape=(MAX_SEQUENCE_LENGTH,))

embedding_layer = tf.keras.layers.Embedding(nb_words + 1,
                                            EMBEDDING_DIM,
                                            input_length=MAX_SEQUENCE_LENGTH,
                                            weights=[embedding_matrix],
                                            trainable=True)(tweet_input)
conv1 = tf.keras.layers.Conv1D(128, 3, activation='tanh')(embedding_layer)
drop1 = tf.keras.layers.Dropout(0.2)(conv1)
max1 = tf.keras.layers.MaxPooling1D(3)(drop1)
# conv2 = tf.keras.layers.Conv1D(128, 3, activation='tanh')(max1)
# drop2 = tf.keras.layers.Dropout(0.2)(conv2)
# max2 = tf.keras.layers.MaxPooling1D(3)(drop2)
out = tf.keras.layers.Flatten()(max1)

model_encode = tf.keras.models.Model(tweet_input, out)
encoded_a = model_encode(tweet_a)
encoded_b = model_encode(tweet_b)
merged = tf.keras.layers.concatenate([encoded_a, encoded_b])
dense1 = tf.keras.layers.Dense(128, activation='relu')(merged)
dense2 = tf.keras.layers.Dense(128, activation='relu')(dense1)
dense3 = tf.keras.layers.Dense(128, activation='relu')(dense2)
prediction = tf.keras.layers.Dense(1, activation='sigmoid')(dense3)
model = tf.keras.Model(inputs=[tweet_a, tweet_b], outputs=prediction)
model.summary()
model.compile(optimizer=OPT,
              loss=LOSS,
              metrics=['accuracy'])
# 训练模型
model.fit([input_train_left, input_train_right], train_score, epochs=EPOCHS)

# 保存模型
if not tf.io.gfile.exists(MODEL_DIR):
    tf.io.gfile.makedirs(MODEL_DIR)

model.save(MODEL_FILE)
print('Saved trained model at %s ' % MODEL_FILE)

# 模型转换
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
# converter.experimental_new_converter = True
tflite_quant_model = converter.convert()
open("model/train/converted_model.tflite", "wb").write(tflite_quant_model)
print('tflite convert finish')

# 预测测试集
loss_and_accuracy = model.evaluate([val_left, val_right], val_score)
print("Test Loss: {}".format(loss_and_accuracy[0]))
print("Test Accuracy: {}%".format(loss_and_accuracy[1]*100))

```

**Comment by rambowding** [comment] 2020-06-11 08:44
@amahendrakar 
the 'data_preprocess.py' file is shown in below, other modules are from 'pip install'
```
# 数据预处理
import word2vec
import pandas as pd
import numpy as np
import jieba

# 词向量文件路径
word_vector_file_path = 'data/sgns.weibo.word.txt'


def build_word_embedding():
    embeddings_index = {}
    f = open(word_vector_file_path)
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = vector
    f.close()
    print('Found %s word vectors.' % len(embeddings_index))  # embeddings_index type=dict
    return embeddings_index


def build_word_vectors():
    wv = word2vec.load(word_vector_file_path)
    vocab = wv.vocab
    vectors = wv.vectors
    print('build_word_dic fun vocab len=', len(vocab))
    # print(vocab)
    # print(word_embedding)
    return vocab, vectors


def read_train_data(train_file):
    df_train = pd.read_csv(train_file, sep='\t', usecols=[0, 1, 2], names=['s1', 's2', 'score'],
                           dtype={'s1': object, 's2': object, 'score': object})
    s1 = df_train.s1.values
    s2 = df_train.s2.values
    score = np.asarray(df_train.score.values, dtype=np.float32)
    print('train data len=', len(score))
    return s1, s2, score


def change_for_tokenizer(s1, s2):
    size = len(s1)
    texts = []
    left = []
    right = []
    for i in range(size):
        seg_left = jieba.lcut(s1[i])
        seg_right = jieba.lcut(s2[i])
        text_left = (' '.join(seg_left))  # .encode('utf-8', 'ignore').strip()
        text_right = (' '.join(seg_right))  # .encode('utf-8', 'ignore').strip()

        texts.append(text_left)
        texts.append(text_right)

        left.append(text_left)
        right.append(text_right)
    return left, right, texts

```

**Comment by amahendrakar** [comment] 2020-06-12 18:30
@rambowding,
Could you please share `train.txt`, `sgns.weibo.word.txt` and any other supporting files you are using in your code. Thanks!

**Comment by rambowding** [comment] 2020-06-15 08:56
> @rambowding,
> Could you please share `train.txt`, `sgns.weibo.word.txt` and any other supporting files you are using in your code. Thanks!

I hope that my data files are not public on github or web，could I send the file's download url to you via email?

**Comment by amahendrakar** [comment] 2020-06-17 17:47
> I hope that my data files are not public on github or web，could I send the file's download url to you via email?

@rambowding,
Please send the supporting files to amahendrakar@google.com. Thanks!

**Comment by rambowding** [comment] 2020-06-18 09:45
> @rambowding,
> Please send the supporting files to [amahendrakar@google.com](mailto:amahendrakar@google.com). Thanks!

@amahendrakar 
done!

**Comment by amahendrakar** [comment] 2020-06-20 19:27
@rambowding,
Due to network restrictions I am unable to access the link you have sent. Could you please try to send the files in another way.  Thanks!

**Comment by rambowding** [comment] 2020-06-22 05:51
> @rambowding,
> Due to network restrictions I am unable to access the link you have sent. Could you please try to send the files in another way. Thanks!

shared with you via Google Drive

**Comment by amahendrakar** [comment] 2020-06-22 19:48
@rambowding,
I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/81358916b6a1c56eda894a25aa9888a4/40121.ipynb).

Could you please run the code in a virtual environment and check if you are facing the same issue. Thanks!

**Comment by rambowding** [comment] 2020-06-23 13:20
@amahendrakar 
It also works in my jupyter environment,  it is way that I convert tf model to tflite model temporarily. The issue happens in venv environment, I am sorry for not pointing it out definitely.

**Comment by amahendrakar** [comment] 2020-06-23 17:35
>The issue happens in venv environment

@rambowding,
Could you please check the TensorFlow version in the virtual environment? Make sure that you are using TensorFlow v2.2 in the virtual environment too. Thanks!

**Comment by rambowding** [comment] 2020-06-24 11:57
@amahendrakar 
python 3.7.6, Tensorflow 2.2.0
![image](https://user-images.githubusercontent.com/7675778/85551732-dd07b780-b654-11ea-8c5d-ccb91fdab717.png)

**Comment by ymodak** [comment] 2020-09-16 22:47
Closing this issue since it is not reproducible. Please try using latest tensorflow version and try again. Thanks!

**Closed by ymodak** 2020-09-16 22:47 UTC
Labels: TF 2.2, TFLiteConverter, comp:lite, type:support
