### ISSUE TITLE
Inputs mismatch in model.predict does not raise Error

### ISSUE THREAD

**Issue by LucaMantani** [tensorflow/tensorflow#39226] opened 2020-05-06 14:11 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.4
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.5

**Describe the current behavior**
I wrote a simple model that takes 1 input array and outputs another. I produce then 2 input arrays, one with the right dimension and the other with wrong dimensions. If you feed to model.predict the 2 input arrays, the correct one first, the model simply takes the first array and the run goes fine. The second input is completely ignored.

**Describe the expected behavior**
I would expect an error like "You are giving two input arrays to a model that expects one"

**Standalone code to reproduce the issue**

```
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import numpy as np


def generator(input_dim, output_dim):
        # Input
        g_input = Input(input_dim, name='noise_input')

        # Dense block
        x = Dense(32)(g_input)

        # Final layer
        g_output = Dense(output_dim)(x)

        G = Model(g_input, g_output, name='Generator')
        return G


input_dim = 6
output_dim = 2

gen = generator(input_dim, output_dim)

sample_size = 5

noise_data_1 = np.random.normal(0, 1, size=(sample_size, input_dim))
noise_data_2 = np.random.normal(0, 1, size=(sample_size, 1))


out = gen.predict([noise_data_1, noise_data_2])

print(out)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-05-07 10:33
Was able to reproduce the issue with [TF v2.2.0rc4](https://colab.research.google.com/gist/amahendrakar/c2833385469c38ee05ad804f217f9159/39226.ipynb). Please find the gist of it here. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-05-07 14:12
@LucaMantani This is intended behavior of the `model.predict(x)` which is defined [here](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#predict). 

If you look at the input `x`, it should be an array or or a list of arrays (in case the model has multiple inputs). 

```
Arguments:
x: Input samples. It could be:
A Numpy array (or array-like), or a list of arrays (in case the model has multiple inputs).
A TensorFlow tensor, or a list of tensors (in case the model has multiple inputs).
A tf.data dataset.
A generator or keras.utils.Sequence instance. A more detailed description of unpacking behavior for iterator types (Dataset, generator, Sequence) is given in the Unpacking behavior for iterator-like inputs section of Model.fit.
```
In your case, you have a model that takes single input so when you pass a list of arrays ([noise_data_1, noise_data_2]), it is taking  array[0] only as it was designed for single input. 

If you try the following line, it will throw mismatch error that you are expecting.
```
# It will throw size mismatch error
out2 = gen.predict([noise_data_2])
print(out2)  # throw InvalidArgumentError:  Matrix size-incompatible: In[0]: [5,1], In[1]: [6,32]
```

In another case where given input is longer that what is expected, it will throw an error as shown below

```
gen2 = generator(input_dim, output_dim)
noise_data_3 = np.random.normal(0, 1, size=(sample_size, input_dim+5))
noise_data_4 = np.random.normal(0, 1, size=(sample_size, 1))
out2 = gen2.predict([noise_data_3, noise_data_4]) # this will throw an error as follows
#     ValueError: Input 0 of layer dense_4 is incompatible with the layer: expected axis -1 of input shape to have value 6 but received input with shape [None, 11]
```
Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5bc15e5deb21f7654b274eb57b7ca28a/39226.ipynb). 

Please verify once and close the issue. Thanks!

**Comment by LucaMantani** [comment] 2020-05-07 15:13
Yes, I understand what is happening. But in particular

> you have a model that takes single input so when you pass a list of arrays ([noise_data_1, noise_data_2]), it is taking array[0] only as it was designed for single input.

shouldn't be better to raise an error? This "feature" that if you feed multiple inputs to a single input NN it just takes the first in the list could very well make it difficult to spot bugs in codes.

**Comment by ramonpeter** [comment] 2020-05-07 17:09
Just to jump on that. Even if you don't use model.predict but just use this generator as model within the functional API in the following way


    from tensorflow.keras.models import Model
    from tensorflow.keras.layers import Input, Dense
    import numpy as np


    def generator(input_dim, output_dim):
        # Input
        g_input = Input(input_dim, name='noise_input')

        # Dense block
        x = Dense(32)(g_input)

        # Final layer
        g_output = Dense(output_dim)(x)

        G = Model(g_input, g_output, name='Generator')
        return G


    input_dim = 6
    output_dim = 2

    gen = generator(input_dim, output_dim)


    noise_data_1 = Input((input_dim))
    noise_data_2 = Input(1)


    out_tensor = gen([noise_data_1, noise_data_2])

    print(out_tensor)

Even then it doesn't give an error. This potentially dangerous isn't it?

**Comment by jvishnuvardhan** [comment] 2021-05-10 22:27
@LucaMantani Looks like this was resolved. I checked your code with `tf-nightly` and it throws an shape mismatch error as shown below. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3449cb4058fcc994da8164c3722d23ea/untitled.ipynb).

Here is the error

`    ValueError: Layer Generator expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 6) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 1) dtype=float32>]`

Please verify once and close the issue if this was resolved for you. thanks!

**Closed** 2021-05-24 23:48 UTC
Labels: TF 2.1, TF 2.2, comp:keras, stalled, stat:awaiting response, type:support
