### ISSUE TITLE
Error importing tensorflow, tensorflow library was compiled to use AVX instructions, but these aren;t in your machine

### ISSUE THREAD

**Issue by OsamaNaeem1995** [tensorflow/tensorflow#27198] opened 2019-03-27 14:00 UTC
**System information**
-  Linux Ubuntu 16.04
- 
- TensorFlow installed from binary (pip install)
- TensorFlow version:
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip and virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Problem described** 

i was following the tutorial for using intel neural stick 2 for object detection https://towardsdatascience.com/speed-up-predictions-on-low-power-devices-using-neural-compute-stick-and-openvino-98f3ae9dcf41
in the  example i install the prerequisites using the command 
`sudo ./opt/intel/computer_vision_sdk/deployment_tools/model_optimizer/install_prerequisites/install_prerequisites.sh`

tensorflow was installed with the prerequisites , i also installed tensorflow using pip install , but when i run the next command 

`mo_tf.py \
    --input_model ~/Downloads/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.pb \
    --tensorflow_use_custom_operations_config     /opt/intel/computer_vision_sdk/deployment_tools/model_optimizer/extensions/front/tf/ssd_support.json \
    --tensorflow_object_detection_api_pipeline_config ~/Downloads/ssd_mobilenet_v1_coco_2018_01_28/pipeline.config \
    --data_type FP16`

i get the following error 
`F tensorflow/core/platform/cpu_feature_guard.cc:37] 
The tensorflow library was compiled to use AVX instructions, but these aren't available in your machine 
Aborted (core dumped) ` 

i am getting the same error when try and **import tensorflow** 

what should i do to solve this error ?

**Comment by muddham** [comment] 2019-03-29 13:22
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue like CUDA and cuDNN versions. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by OsamaNaeem1995** [comment] 2019-03-29 13:28
Hi. Found somewhere that I needed to install tensorflow 1.5 and the issue
would be resolved. And that's what happened. I had tensorflow 1.13 which
isn't compatible

**Comment by jvishnuvardhan** [comment] 2019-04-04 21:38
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-04-04 21:38 UTC
Labels: comp:runtime, subtype: ubuntu/linux, type:build/install

**Comment by foobar167** [comment] 2019-04-16 14:39
Try Anaconda. It has new TensorFlow distribution for old CPUs.

**Comment by r-barnes** [comment] 2019-11-19 04:18
@foobar167 : I didn't see such a distribution. Perhaps you could link to it?

**Comment by foobar167** [comment] 2019-11-23 12:32
@r-barnes : There is [Anaconda Python](https://www.anaconda.com/distribution/) distribution which is more flexible sometimes, than Python distribution. For example, I installed TensorFlow on the old CPU using **Anaconda Python**. Meanwhile Python refused to work (old CPU, CUDA not installed, wrong version of cuDNN, etc.).

Anaconda Python has better automatic software package installer and versions tracker. So in my opinion, it is a little bit easier for beginner to deploy a **virtual environment**, install some packages like TensorFlow.

If you're beginner try the following software:
   * Anaconda Python instead of Python
   * PyCharm Community edition as an integrated development environment (IDE)
   * try Jupyter Notebook for your software templates
   * [Google Colab](https://colab.research.google.com/) or [Kaggle Kernels](https://www.kaggle.com/kernels) or some other [Cloud Jupyter Notebooks](https://www.dataschool.io/cloud-services-for-jupyter-notebook/), especially if you have an old CPU and old GPU
   * Review my links on Machine Learning [here](https://github.com/foobar167/articles/blob/master/Machine_Learning/courses_on_machine_learning.md) and [here](https://github.com/foobar167/articles/blob/master/Ubuntu/13_Keras_and_TensorFlow_how-tos.md).

**Comment by foobar167** [comment] 2019-11-26 06:36
Hi,
@r-barnes <https://github.com/r-barnes> : There is Anaconda Python
<https://www.anaconda.com/distribution/> distribution which is more
flexible sometimes, than Python distribution. For example, I installed
TensorFlow on the old CPU using *Anaconda Python*. Meanwhile, Python
refused to work (old CPU, CUDA not installed, the wrong version of cuDNN,
etc.).

Anaconda Python has a better automatic software package installer and
versions tracker. So in my opinion, it is a little bit easier for beginner
to deploy a *virtual environment*, install some packages like TensorFlow.

If you're beginner try the following software:

   - Anaconda Python instead of Python
   - PyCharm Community edition as an integrated development environment
   (IDE)
   - try Jupyter Notebook for your software templates
   - Google Colab <https://colab.research.google.com/> or Kaggle Kernels
   <https://www.kaggle.com/kernels> or some other Cloud Jupyter Notebooks
   <https://www.dataschool.io/cloud-services-for-jupyter-notebook/>,
   especially if you have an old CPU and old GPU
   - Review my links on Machine Learning here
   <https://github.com/foobar167/articles/blob/master/Machine_Learning/courses_on_machine_learning.md>
   and here
   <https://github.com/foobar167/articles/blob/master/Ubuntu/13_Keras_and_TensorFlow_how-tos.md>
   .


Kind regards,
Foo Bar 167

**Comment by mbalalzade** [comment] 2024-01-30 07:08
hello . i have same problem to use tensorflow on my gpu but system told me error of AVX cpu. now i have question: my program that make with python run on my ubuntu system after collection dataset of my work in online mode of my app i am need to train a dense model i was trying to use my gpu but i got mentioned error that told u now i want know is there any api or any thing that i can train my model and give back answer of predicts of my model that trained to my app on my system?
