### ISSUE TITLE
Under MirroredStrategy and ParameterStrategy tf.trainable_variables() doesn't return the correct wrapped variables

### ISSUE THREAD

**Issue by oldshuren** [tensorflow/tensorflow#27927] opened 2019-04-17 16:34 UTC
Under MirroredStrategy and ParameterStrategy tf.trainable_variables() returns the normal unwrapped variables.

But according to the comments in mirrored_strategy.py and parameter_server_strategy.py, tf.trainable_variables() should return the wrapped variables.

Here tf 1.13.1 mirrored_strategy.py code segment,
```
 if not context.executing_eagerly():
    g = ops.get_default_graph()
    # If "trainable" is True, next_creator() will add the member variables                                                                                                                    
    # to the TRAINABLE_VARIABLES collection, so we manually remove                                                                                                                            
    # them and replace with the MirroredVariable. We can't set                                                                                                                                
    # "trainable" to False for next_creator() since that causes functions                                                                                                                     
    # like implicit_gradients to skip those variables.                                                                                                                                        
    if kwargs.get("trainable", True) or kwargs.get("trainable", True) is None:
      collections.append(ops.GraphKeys.TRAINABLE_VARIABLES)
      l = g.get_collection_ref(ops.GraphKeys.TRAINABLE_VARIABLES)
      for v in index.values():
        if v in l:
          l.remove(v)
    g.add_to_collections(collections, result)
```
The problem is that in kwargs past from up stream API, "trainable" is set but the value is None, so just ckeck

    if kwargs.get("trainable", True): 

is not enough, it should be

    if kwargs.get("trainable", True) or  kwargs.get("trainable", True) is None:

This bug exists in all version of tensorflow. For tf 1.13.1, here is the fix for mirred_strategy.py
```
diff -u mirrored_strategy.py-org mirrored_strategy.py
--- mirrored_strategy.py-org    2019-03-15 08:56:17.677027702 -0400
+++ mirrored_strategy.py        2019-04-17 12:21:06.339507273 -0400
@@ -256,7 +256,7 @@
     # them and replace with the MirroredVariable. We can't set
     # "trainable" to False for next_creator() since that causes functions
     # like implicit_gradients to skip those variables.
-    if kwargs.get("trainable", True):
+    if kwargs.get("trainable", True) or kwargs.get("trainable", True) is None:
       collections.append(ops.GraphKeys.TRAINABLE_VARIABLES)
       l = g.get_collection_ref(ops.GraphKeys.TRAINABLE_VARIABLES)
       for v in index.values():
```

**Comment by achandraa** [comment] 2019-04-26 11:57
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-05-02 04:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-02 04:54 UTC
Labels: comp:dist-strat, stat:awaiting response, type:bug/performance
