### ISSUE TITLE
Bazel unable to build on Jetson TX1 with --config=cuda option?

### ISSUE THREAD

**Issue by kwotsin** [tensorflow/tensorflow#9755] opened 2017-05-08 10:43 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.1 (latest master)
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: Tegra X1
- **Exact command to reproduce**:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 

### Describe the problem
Using the bazel build command above, I am unable to find a valid toolchain to support the aarch64 architecture in the Jetson TX1. However, by removing the `--config=cuda` option, the error is gone, although I am still unable to finish building the pip file (probably due to the fact that I configured TF for GPU using `./configure`). 

Note: I changed the bazel files as seen in this guide: http://zhiyisun.github.io/2017/02/15/Running-Google-Machine-Learning-Library-Tensorflow-On-ARM-64-bit-Platform.html , in order to get bazel to build for aarch64.

Is there anything more that I have to change? using the suggested command of `bazel build -c opt --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --verbose_failures tensorflow/tools/pip_package:build_pip_package` I get the same error too.

I saw this issue over here: https://github.com/bazelbuild/bazel/issues/1855
and it says it has something related to the cuda crosstool. Is there a way to fix this to configure TensorFlow-GPU on the Jetson TX1?

Thank you for your help. :D

### Source code / logs

Here is the error I got:

```
ubuntu@tegra-ubuntu:~/tensorflow$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: No toolchain found for cpu 'aarch64'. Valid cpus are: [
  k8,
  piii,
  arm,
  darwin,
  ppc,
].
INFO: Elapsed time: 1.589s

```

**Comment by girving** [comment] 2017-05-09 16:12
@jart Do you know what to do here?

**Comment by kwotsin** [comment] 2017-05-11 04:40
Do you think if I compile tensorflow for the Jetson on my laptop, this will work? Meaning to say is this just a build issue, or will TF not run properly even when successfully built because of the architecture issue?

If cross-compiling on a laptop will work, is there a guide on how to do this? I have tried the instructions in https://developer.ubuntu.com/en/snappy/guides/cross-build/ but I can't seem to run the commands to completion. Further, the architecture is ARM64 and not aarch64, so there might be a difference.

**Comment by girving** [comment] 2017-05-11 14:27
@petewarden Are we likely to be Jetson compatible?

**Comment by jart** [comment] 2017-05-11 20:03
This appears to be a duplicate of #9788. The solution appears to be upgrading Bazel.

**Closed by jart** 2017-05-11 20:03 UTC
Labels: type:build/install

**Comment by jart** [comment] 2017-05-11 20:06
Or more correctly, the other issue is a duplicate of this one, since your issue was filed first.

**Comment by xav12358** [comment] 2018-02-06 09:22
Do you have any solution for that error?

`ERROR: No default_toolchain found for cpu 'arm64-v8a'. Valid cpus are: [
  k8,
  armeabi-v7a,
  x64_windows,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]
INFO: Elapsed time: 1.323s
`

I can't find solution to build it properly for arm64-v8a
