### ISSUE TITLE
Val loss behaves strange while using custom training loop in tensorflow 2.0

### ISSUE THREAD

**Issue by SuperCrystal** [tensorflow/tensorflow#33771] opened 2019-10-28 04:38 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, I defined my own training and validation loop and also my own keras model.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No.

- TensorFlow installed from (source or binary):
From source.

- TensorFlow version (use command below):
Tensorflow 2.0.0 (gpu version)

- Python version:
Python 3.6.2

**Describe the current behavior**
I'm using a VGG16 model written in tf2.0 to train on my own datasets. Some BatchNormalization layers were included in the model and the "training" argument were set to True during training time and False during validation time as described in many tutorials. The train_loss decreased to a certain level during training as expected.
However, the val_loss behaves really strange. I checked out the output of the model after training and found out that, if I set the training argument to True, the output is quite correct, but if I set it to False, the result is incorrect at all. According to the tutorials in tensorflow website, when training is set to False , the model will normalize its inputs using the mean and variance of its moving statistics learned during training but it doesn't seem so. Am I missing something?

**Describe the expected behavior**
I think in the validation step if I set ```training``` to ```False``` the model should use the learned moving mean and variance as expected but it doesnt seem so.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import matplotlib.pyplot as plt
from PIL import Image
from tensorflow.keras.preprocessing import image
import glob
from tensorflow.keras.layers import BatchNormalization, Conv2D, ReLU, Conv2DTranspose, add, concatenate
from scipy.io import loadmat
import numpy as np
# from mobilev3 import MobileNetV3Large
from vgg_pr import VGG_PR
from tensorflow.keras.callbacks import TensorBoard
import logging
import cv2

# parameters
img_size = (299,299)
batch_size = 8
num_label = 20
initial_lr = 0.001
total_epoch = 100
repeat_times = 5
# case number
case_num = 9

os.chdir(os.getcwd())

train_img_list = sorted(glob.glob('../dataset/train/intensity/*.mat'))
train_label_list = sorted(glob.glob('../dataset/train/phase/*.txt'))
val_img_list = sorted(glob.glob('../dataset/validate/intensity/*.mat'))
val_label_list = sorted(glob.glob('../dataset/validate/phase/*.txt'))
ckpt_path = '../checkpoints/VGG-{epoch}.ckpt'
log_path = '../log/{}/'
if not os.path.exists(log_path.format(case_num)):
    os.mkdir(log_path.format(case_num))

# read data
def read_img(filename):
    image_dict = loadmat(filename.decode('utf-8'))
    exp_thresh = 1e4
    image_decoded = image_dict['Iz']
    image_decoded = cv2.resize(image_decoded, img_size, interpolation=cv2.INTER_AREA)
    image_decoded[image_decoded>exp_thresh] = exp_thresh
    image_decoded /= exp_thresh
    image_resized = np.float32(np.expand_dims(image_decoded, axis=-1))
    return image_resized

def read_label(filename):
    label = open(filename).read()
    label = label.strip().split(' ')
    label = [np.float32(i) for i in label if i!='']
    label = np.reshape(label, [1,1,-1])
    label = np.array(label) + 0.5  
    return label
def parse_function(image_filename, label_filename):
    img = tf.numpy_function(read_img, [image_filename], tf.float32)
    label = tf.numpy_function(read_label, [label_filename], tf.float32)
    return img, label
def train():
    logging.basicConfig(level=logging.INFO)
    tdataset = tf.data.Dataset.from_tensor_slices((train_img_list[:200], train_label_list[:200]))
    tdataset = tdataset.map(parse_function, 3).shuffle(buffer_size=200).batch(batch_size).repeat(repeat_times)
    vdataset = tf.data.Dataset.from_tensor_slices((val_img_list[:100], val_label_list[:100]))
    vdataset = vdataset.map(parse_function, 3).batch(batch_size)

    ### Vgg model
    model = VGG_PR(num_classes=num_label)

    logging.info('Model loaded')

    start_epoch = 0
    latest_ckpt = tf.train.latest_checkpoint(os.path.dirname(ckpt_path))
    if latest_ckpt:
        start_epoch = int(latest_ckpt.split('-')[1].split('.')[0])
        model.load_weights(latest_ckpt)
        logging.info('model resumed from: {}, start at epoch: {}'.format(latest_ckpt, start_epoch))
    else:
        logging.info('training from scratch since weights no there')

    ######## training loop ########
    loss_object = tf.keras.losses.MeanSquaredError()
    val_loss_object = tf.keras.losses.MeanSquaredError()
    optimizer = tf.keras.optimizers.Adam(learning_rate=initial_lr)
    train_loss = tf.metrics.Mean(name='train_loss') 
    val_loss = tf.metrics.Mean(name='val_loss')
    writer = tf.summary.create_file_writer(log_path.format(case_num))

    with writer.as_default():
        for epoch in range(start_epoch, total_epoch):
            print('start training')
            try:
                for batch, data in enumerate(tdataset):
                    images, labels = data
                    with tf.GradientTape() as tape:
                        pred = model(images, training=True)
                        if len(pred.shape) == 2:
                            pred = tf.reshape(pred,[-1, 1, 1, num_label])
                        loss = loss_object(pred, labels)
                    gradients = tape.gradient(loss, model.trainable_variables)
                    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
                    if batch % 20 ==0:
                        logging.info('Epoch: {}, iter: {}, loss:{}'.format(epoch, batch, loss.numpy()))
                    tf.summary.scalar('train_loss', loss.numpy(), step=epoch*1250*repeat_times+batch)      # the tdataset has been repeated 5 times..
                    tf.summary.text('Zernike_coe_pred', tf.as_string(tf.squeeze(pred)), step=epoch*1250*repeat_times+batch)
                    tf.summary.text('Zernike_coe_gt', tf.as_string(tf.squeeze(labels)), step=epoch*1250*repeat_times+batch)

                    writer.flush()
                    train_loss(loss)
                model.save_weights(ckpt_path.format(epoch=epoch))
            except KeyboardInterrupt:
                logging.info('interrupted.')
                model.save_weights(ckpt_path.format(epoch=epoch))
                logging.info('model saved into {}'.format(ckpt_path.format(epoch=epoch)))
                exit(0)
            # validation step
            for batch, data in enumerate(vdataset):
                images, labels = data
                val_pred = model(images, training=False)
                if len(val_pred.shape) == 2:
                    val_pred = tf.reshape(val_pred,[-1, 1, 1, num_label])
                v_loss = val_loss_object(val_pred, labels)
                val_loss(v_loss)
            logging.info('Epoch: {}, average train_loss:{}, val_loss: {}'.format(epoch, train_loss.result(), val_loss.result()))
            tf.summary.scalar('val_loss', val_loss.result(), step = epoch)
            writer.flush()
            train_loss.reset_states()
            val_loss.reset_states()
        model.save_weights(ckpt_path.format(epoch=epoch))
```
And here is my vgg_pr model:
```python
import tensorflow as tf

# ------------------------------- Layers part -------------------------------
class BatchNormalization(tf.keras.layers.Layer):
    """All our convolutional layers use batch-normalization
    layers with average decay of 0.99.
    """

    def __init__(self):
        super().__init__(name="BatchNormalization")
        self.bn = tf.keras.layers.BatchNormalization(
            momentum=0.99,
            name="BatchNorm")

    def call(self, input, training):
        return self.bn(input, training)

class ConvBnAct(tf.keras.layers.Layer):
    def __init__(
            self,
            filters=64,
            kernel_size=(3,3),
            activation='relu',
            padding='same',
            name='conv'):
        super().__init__(name="ConvBnAct")

        self.conv = tf.keras.layers.Conv2D(
            filters=filters,
            kernel_size=kernel_size,
            activation=activation,
            padding=padding,
            name=name)
        # self.norm = BatchNormalization()
        self.norm = tf.keras.layers.BatchNormalization(name='BatchNorm')

    def call(self, input, training):
        x = self.conv(input)
        x = self.norm(x,training=training)
        return x

class Block_1(tf.keras.layers.Layer):
    def __init__(
            self):
        super().__init__(name="Block_1")
        self.conv1 = ConvBnAct(64,name='block1_conv1')
        self.conv2 = ConvBnAct(64,name='block1_conv2')
        self.pool = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2), name='block1_pool')

    def call(self, input,training=False):
        x = self.conv1(input,training)
        x = self.conv2(x,training)
        x = self.pool(x)
        return x

class Block_2(tf.keras.layers.Layer):
    def __init__(
            self):
        super().__init__(name="Block_2")
        self.conv1 = ConvBnAct(128,name='block2_conv1')
        self.conv2 = ConvBnAct(128,name='block2_conv2')
        self.pool = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2), name='block2_pool')

    def call(self, input,training=False):
        x = self.conv1(input,training)
        x = self.conv2(x,training)
        x = self.pool(x)
        return x

class Block_3(tf.keras.layers.Layer):
    def __init__(
            self):
        super().__init__(name="Block_3")
        self.conv1 = ConvBnAct(256,name='block3_conv1')
        self.conv2 = ConvBnAct(256,name='block3_conv2')
        self.conv3 = ConvBnAct(256,name='block3_conv3')
        self.pool = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2), name='block3_pool')

    def call(self, input ,training=False):
        x = self.conv1(input,training)
        x = self.conv2(x,training)
        x = self.conv3(x,training)
        x = self.pool(x)
        return x

class Block_4(tf.keras.layers.Layer):
    def __init__(
            self):
        super().__init__(name="Block_4")
        self.conv1 = ConvBnAct(512,name='block4_conv1')
        self.conv2 = ConvBnAct(512,name='block4_conv2')
        self.conv3 = ConvBnAct(512,name='block4_conv3')
        self.pool = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2), name='block4_pool')

    def call(self, input,training=False):
        x = self.conv1(input,training)
        x = self.conv2(x,training)
        x = self.conv3(x,training)
        x = self.pool(x)
        return x

class Block_5(tf.keras.layers.Layer):
    def __init__(
            self):
        super().__init__(name="Block_5")
        self.conv1 = ConvBnAct(512,name='block5_conv1')
        self.conv2 = ConvBnAct(512,name='block5_conv2')
        self.conv3 = ConvBnAct(512,name='block5_conv3')
        self.pool = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2), name='block5_pool')

    def call(self, input,training=False):
        x = self.conv1(input,training)
        x = self.conv2(x,training)
        x = self.conv3(x,training)
        x = self.pool(x)
        return x

class VGG_PR(tf.keras.Model):
    def __init__(self,num_classes):
        super(VGG_PR, self).__init__()
        self.block1 = Block_1()
        self.block2 = Block_2()
        self.block3 = Block_3()
        self.block4 = Block_4()
        self.block5 = Block_5()
        self.avg = tf.keras.layers.GlobalAveragePooling2D()
        self.fc1 = tf.keras.layers.Dense(256, activation='relu', name='fc1')
        self.fc2 = tf.keras.layers.Dense(128, activation='relu', name='fc2')
        self.fc3 = tf.keras.layers.Dense(num_classes,activation='linear',name='predictions')

    def call(self, input, training=False):
        x = self.block1(input,training)
        x = self.block2(x,training)
        x = self.block3(x,training)
        x = self.block4(x,training)
        x = self.block5(x,training)
        x = self.avg(x)
        # print("output1:{}".format(x))
        x = self.fc1(x)
        # print("output2:{}".format(x))
        x = self.fc2(x)
        x = self.fc3(x)
        return x

```

**Comment by SuperCrystal** [comment] 2019-10-28 04:41
I thought it's because of some problems with ```tf.keras.layers.BatchNormalization()``` but I didn't find the way to solve it.

**Comment by ravikyram** [comment] 2019-10-29 08:55
@SuperCrystal 

Looks like code is incomplete. Please, help us with simple standalone code to reproduce the issue in our environment. It helps us to localize the issue faster. Thanks!

**Comment by SuperCrystal** [comment] 2019-10-30 02:18
@ravikyram Hello! I've added the complete code. Is there any suggestions on how to solve this problem? Thx!

**Comment by ravikyram** [comment] 2019-10-30 10:15
@SuperCrystal 
I tried reproducing the issue and i am seeing the below error.`ModuleNotFoundError: No module named 'mobilev3'`.Also, please share supporting files to reproduce the issue. Thanks!

**Comment by SuperCrystal** [comment] 2019-10-31 04:24
@ravikyram Sorry for that! I have corrected it. See whether you can reproduce the issue this time? Thanks a lot!

**Comment by SuperCrystal** [comment] 2019-11-04 03:02
@ymodak Sorry but is there any possible solution or am I missing sth? Thx a lot :)

**Comment by JadTawil-theonly** [comment] 2019-12-20 03:00
I believe i am experiencing something similar.
Setting training=False worked for getting validation results that made sense, and were much more accurate. I made sure i took dropout out of my network to isolate the problem, which seems to be the batch normalization (for batches of size 1 and greater).
After investigating the source code, it has something to do with the moving mean and moving variance.
When i rerouted the code such that the mean and variance of the current batch are used for the batch normalization operation in BOTH the training and validation modes, the network validated fine.
Another curious thing i noticed when printing the value of moving mean during validation is that it was still changing... and i could not find where in the code it was being assigned. Not only was it changing, but it was generally a order or two orders of magnitude below the batch mean, causing a drastic change in network output. Why would it be changing, i have no idea, since i am under the impression that during inference it is used as it was determined during the training.

**Comment by lminer** [comment] 2020-01-05 17:15
I'm also having an issue with val loss behaving strangely. Although in my case, I'm using `tf.keras `for the training loop and it goes away if I disable v2 behavior `tf.compat.v1.disable_v2_behavior()`

**Comment by ymodak** [comment] 2020-01-08 00:08
@JadTawil-theonly @lminer  Can you please post a new issue and provide a minimal reproducible code snippet? Thanks!

**Comment by JadTawil-theonly** [comment] 2020-01-08 13:44
BatchNormalization behaves differently during training and validation. This MAY be your issue, idk you let me know.

During training, the statistics of the current batch are used to normalize the features. The computed mean and variance are used to update a running mean and running variance.
During validation, the running mean and running variance are used, and nothing is updated.
You may get very different results during validation because of this.
Over time, the running mean and running variance will have values that are closer to the batch mean and variance. You can control this with the momentum term.
Another solution would be to normalize your data around zero, by subtracting the mean and dividing by std of each input channel (assuming image type data). Doing this, you don't have to adjust the momentum.

**Comment by ymodak** [comment] 2020-01-15 22:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2020-01-15 22:28 UTC
Labels: TF 2.0, comp:keras, type:support

**Comment by anshkapil** [comment] 2020-04-03 18:58
@SuperCrystal Were you able to find a solution to this problem? I am not using model subclassing, but still have the same problem at hand. Thanks!
