### ISSUE TITLE
RaggedTensor Hierarchical Model Issue

### ISSUE THREAD

**Issue by nectario** [tensorflow/tensorflow#35067] opened 2019-12-12 22:51 UTC
I have the following model:

```
   import numpy as np

   def example():

        # Encode each timestep
        in_sentence = Input(shape=(None,),  dtype='int64', name="Input1")
        embedded_sentence = Embedding(1000, 300, trainable=False)(in_sentence)
        lstm_sentence = LSTM(300)(embedded_sentence)
        encoded_model = Model(in_sentence, lstm_sentence)

        section_input = Input(shape=(None, None), dtype='int64', name="Input2")
        section_encoded = TimeDistributed(encoded_model)(section_input)
        section_encoded = LSTM(300)(section_encoded)
        section_model = Model(section_input, section_encoded)

        document_input = Input(shape=(None, None, None), dtype='int64', name="Input3")
        document_encoded = TimeDistributed(section_model)(document_input)
        document_encoded = LSTM(300, return_sequences=True)(document_encoded)
        document_encoded = Dense(1)(document_encoded)
        document_model = Model(document_input, document_encoded)
        document_model.compile(loss='categorical_crossentropy',
                      optimizer='rmsprop',
                      metrics=['accuracy'])

        print(section_model.summary())
        print(document_model.summary())
        return document_model
```
And I call it:

```

y = []
for doc in documents:
    tocs = []
    for token in doc:
        tocs.append(np.random.random_integers(0, high=1))
        y.append(tocs)

output = tf.ragged.constant(y)

input = tf.ragged.constant([[[[4, 5, 2, 6]], [[10, 12, 9], [26, 20, 21, 22], [35, 34, 31]]]])

example().fit(input, output, use_multiprocessing=True, epochs=10, batch_size=1)
```
I get the following error:

Traceback (most recent call last):
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\util\nest.py", line 318, in assert_same_structure
    expand_composites)
ValueError: The two structures don't have the same nested structure.

First structure: type=RaggedTensorSpec str=RaggedTensorSpec(TensorShape([5, None, None, None]), tf.int32, 3, tf.int64)

Second structure: type=Tensor str=Tensor("Input3:0", shape=(None, None, None, None), dtype=int64)

More specifically: Substructure "type=RaggedTensorSpec str=RaggedTensorSpec(TensorShape([5, None, None, None]), tf.int32, 3, tf.int64)" is a sequence, while substructure "type=Tensor str=Tensor("Input3:0", shape=(None, None, None, None), dtype=int64)" is not

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 392, in <module>
    qa_model.fit(input=documents, output=output)
  File "D:/Development/competitions/Kaggle/Tensorflow 2.0 - Q_a_A/tensorflow_2.0/QuestionAnswerContextAttention.py", line 163, in fit
    self.example().fit(input, output, use_multiprocessing=True, epochs=10, batch_size=1)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 224, in fit
    distribution_strategy=strategy)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 547, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 594, in _process_inputs
    steps=steps)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2497, in _standardize_user_data
    nest.assert_same_structure(a, b, expand_composites=True)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\util\nest.py", line 325, in assert_same_structure
    % (str(e), str1, str2))
ValueError: The two structures don't have the same nested structure.

First structure: type=RaggedTensorSpec str=RaggedTensorSpec(TensorShape([5, None, None, None]), tf.int32, 3, tf.int64)

Second structure: type=Tensor str=Tensor("Input3:0", shape=(None, None, None, None), dtype=int64)

More specifically: Substructure "type=RaggedTensorSpec str=RaggedTensorSpec(TensorShape([5, None, None, None]), tf.int32, 3, tf.int64)" is a sequence, while substructure "type=Tensor str=Tensor("Input3:0", shape=(None, None, None, None), dtype=int64)" is not
Entire first structure:
.
Entire second structure:
.

Process finished with exit code 1

<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-12-16 05:28
@nectario, Please provide the Tensorflow version and complete standalone code to reproduce the reported issue. Thanks!

**Comment by nectario** [comment] 2019-12-16 18:08
Hi @gadagashwini , 

I have attached a zip file that contains the code and data that recreates the problem. Just unzip the file and type:

python RaggedProblem.py

[ragged_problem.zip](https://github.com/tensorflow/tensorflow/files/3969504/ragged_problem.zip)

Thanks!

Nektarios

**Comment by gadagashwini** [comment] 2019-12-19 10:40
I could replicate the issue with Tf 1.15.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/3bcb5544395d4609e3ce596ecb473d8e/untitled317.ipynb). Thanks!

**Comment by nectario** [comment] 2019-12-19 12:16
Thank you! For me this happened with TensorFlow 2.0 also.

**Comment by gowthamkpr** [comment] 2019-12-21 00:15
@nectario Can you please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/27170) and let me know if it helps. Thanks!

**Comment by nectario** [comment] 2019-12-21 00:43
I tried specifiy ragged = True on all Input layers, but now I get a different issue:

TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=Tensor("Input1/flat_values:0", shape=(None,), dtype=int64), row_splits=Tensor("Input1/row_splits_0:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.

**Comment by gowthamkpr** [comment] 2020-01-09 22:11
@nectario This is very similar to the issue #27170. Lets track the issue there and close it here. Please let me know if you think otherwise. Thanks!

**Closed** 2020-01-16 22:29 UTC
Labels: TF 1.15, comp:keras, stat:awaiting response, type:bug

**Comment by Jordy-VL** [comment] 2020-06-30 09:27
@nectario did you manage to resolve the issue after all? 
I am having exactly the same problem...
Ragged tensor support still seems to be lacking... 
I do not want to have to clip and pad my sentences/words to represent documents.

**Comment by nectario** [comment] 2020-06-30 14:09
> @nectario did you manage to resolve the issue after all?
> I am having exactly the same problem...
> Ragged tensor support still seems to be lacking...
> I do not want to have to clip and pad my sentences/words to represent documents.
@Jordy-VL Never resolved this issued. I actually gave up on ragged tensors and padded my inputs. I am hoping for better support for ragged tensors in Keras.

**Comment by Jordy-VL** [comment] 2020-06-30 14:27
Thanks for the heads-up @nectario 
Quite sad to still wait for this support as the concept behind ragged tensors is beautiful. 
It deserves to be embedded deeper in the Tensorflow toolbox.

For anyone wanting to pad and clip ragged tensors I have a handy helper function:

```
def hierarchical_tensorize(variable_length_sequences, max_sentences=None, max_document_len=None):
    '''
    since support for ragged tensors is still incipient; we need to convert ragged to full tensors 
    Args:
        variable_length_sequences (list): 2D variable length "sentences x words" elements
        max_sentences (int, optional): 
        max_document_len (int, optional): IS abused for max words per sentence

        -> .to_tensor()[:,:max_sentences,:max_document_len]
    if using ragged tensor -> can only use batch without padding

    Returns:
        3D tensor
    '''
    docs = tf.ragged.constant(variable_length_sequences)
    docs = docs.to_tensor()
    if max_sentences:
        docs = docs[:, :max_sentences, :]
    if max_document_len:
        docs = docs[:, :, :max_document_len]
    return docs
```
