### ISSUE TITLE
Can tensorflow use multiple ps servers to store an embedding variable? 

### ISSUE THREAD

**Issue by Ljl-Jdsk** [tensorflow/tensorflow#36816] opened 2020-02-17 09:54 UTC
Thank you for reading. 
Can tensorflow use multiple parameter servers to store an embedding variable? 
My embedding is too big, the bandwidth of a server is not enough. 
Which module should I use?

Looking forward to your reply！
Thanks！

**Comment by gadagashwini** [comment] 2020-02-17 11:52
@Ljl-Jdsk, Tensorflow supports distribution strategy please take a look at [guide](https://www.tensorflow.org/guide/distributed_training#parameterserverstrategy) for parameter server strategy. Thanks!

**Comment by Ljl-Jdsk** [comment] 2020-02-18 02:31
Yes, the following code can distribute v1, v2 and v3 to two different parameter servers. But now I want to separate the v1 and store it on two servers. Sorry, can you tell me the specific function? I ’m abroad and I can’t open the guide.

cluster_spec = {
    "ps": ["ps0:2222", "ps1:2222"],
    "worker": ["worker0:2222", "worker1:2222", "worker2:2222"]}
with tf.device(tf.train.replica_device_setter(cluster=cluster_spec)):
  v1 = tf.Variable(...)  # assigned to /job:ps/task:0
  v2 = tf.Variable(...)  # assigned to /job:ps/task:1
  v3 = tf.Variable(...)  # assigned to /job:ps/task:0

**Comment by gadagashwini** [comment] 2020-02-20 10:03
@Ljl-Jdsk, Please find the example for Parameter server strategy
```
strategy = tf.distribute.experimental.ParameterServerStrategy()
run_config = tf.estimator.RunConfig(
    experimental_distribute.train_distribute=strategy)
estimator = tf.estimator.Estimator(config=run_config)
tf.estimator.train_and_evaluate(estimator,...)
```
For more read [here](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy). Thanks

**Comment by gadagashwini** [comment] 2020-02-28 11:31
@Ljl-Jdsk, Did you get a chance to look at the above given link. Thanks!

**Comment by gadagashwini** [comment] 2020-03-06 06:20
Closing this issue since the title of the issue is resolved. Thanks!

**Closed by gadagashwini** 2020-03-06 06:20 UTC
Labels: comp:dist-strat, stat:awaiting response, type:support
