### ISSUE TITLE
How to build with RDMA in new version

### ISSUE THREAD

**Issue by hellofinch** [tensorflow/tensorflow#58520] opened 2022-11-10 12:33 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master

### Custom Code

No

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.7

### Bazel version

0.26.1

### Current Behaviour?

```shell
Tensorflow supports gRPC+verbs and gRPC+MPI for distributed settings. I want to know how RDMA works in Tensorflow. So I build TensorFlow from the source.
But I can't find any documentation which shows how to do it. And I find a [repo](https://github.com/tensorflow/networking) which is relative to RDMA(verbs). I try to figure out how I can combine it with TensorFlow and the README confused me.
Then I review the git log in Tensorflow's repo and find the commit `7520b33` which supports verbs. In that commit, I can find how to configure the verbs support in `.bzaelc`. I try to find the same config in `master`'s `.bazelc` but I failed.
How can I build Tensorflow with verbs? Or may Tensorflow not support the verbs?
```

### Standalone code to reproduce the issue

```shell
./configure
```

### Relevant log output

_No response_</details>

**Comment by Twbent** [comment] 2022-11-10 14:07
Sorry

**Comment by SuryanarayanaY** [comment] 2022-11-16 10:44
Hi @hellofinch ,
Yes Tensorflow v2.0 supports `--config==verbs` but in latest versions it is not configured with `--config==verbs`.
Please refer similar issues [55528](https://github.com/tensorflow/tensorflow/issues/55528) & [55524](https://github.com/tensorflow/tensorflow/issues/55524) . Please go through the attached issues and also issue #55528 is still open we can expect a response from there. If you feel this issue is duplicate of #55528 please do close this or let us confirm so that we can close on behalf of you.

**Comment by hellofinch** [comment] 2022-11-16 11:48
@SuryanarayanaY Yeah, I have seen those issues. But none of them can satisfy me, and I don't see anyone who can handle it. It's OK for me to close the issue.
Does that mean Tensorflow does not long support the verbs? Or are there some way else can do?
One last question, I see a [repo](https://github.com/tensorflow/networking) containing verbs, MPI, and some thing else. Is that solution?

**Comment by SuryanarayanaY** [comment] 2022-11-17 09:16
@hellofinch ,

You can try building tensorflow from source using Bazel with `--config==verbs` by referring the steps mentioned [here](https://www.tensorflow.org/install/source).If you succeed in above step next you might be needed this [API](https://www.tensorflow.org/api_docs/python/tf/distribute/Server) with protocol ="grpc+verbs" to turn on RDMA.
Please try your luck with this and let us know if it helps.

Thankyou!

**Comment by hellofinch** [comment] 2022-11-18 02:25
@SuryanarayanaY the option `--config=verbs` maybe work with TensorFlow 2.0. As the issue [55524](https://github.com/tensorflow/tensorflow/issues/55524) says, this option is gone in the new version. In 2.0, this option is [here](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L279). But as you can see, there is nothing about networking. Not only verbs but also mpi are missing too.

I want to know how Tensorflow handles different tensor transmission protocols. verbs or MPI works will sound good to me.

by the way, On the web page you mentioned, I see Tensorflow still supports verbs. Does that mean Tensorflow has contained the old package?

**Comment by sachinprasadhs** [comment] 2022-12-01 00:11
@hellofinch , You can find the bazel files in the directory here https://github.com/tensorflow/tensorflow/tree/master/tensorflow , it should be part of one of these files , `workspace0.bzl` `workspace2.bzl`, `workspace3.bzl`

**Comment by SuryanarayanaY** [comment] 2022-12-01 06:55
@hellofinch ,

To add more I have tried to bazel build using option `--config=verbs` it throws out immediate error stating `"Config value 'verbs' is not defined in any .rc file"` and please refer to the [gist1](https://colab.research.google.com/gist/SuryanarayanaY/7b641ca479f7cc5d9dcaa484c09fe658/bazel-install-58520-masterrepo.ipynb) for same.

Then i have added the line `build:verbs --define=with_verbs_support=true` which is there in 1.x .bazelrc file to the 2.x .bazelrc file and it starts compiling.Please refer attached [gist2.](http://gist2.as/) As compilation in colab taking more time there i stopped it forcefully. Could you please try to add the line mentioned and lets know if it compiles and works for your case.

Thankyou!

**Closed** 2022-12-15 08:07 UTC
Labels: stat:awaiting response, type:build/install, stalled, subtype: ubuntu/linux, subtype:bazel
