### ISSUE TITLE
 Does tensorflow  support Xeon E5645 CPU ?

### ISSUE THREAD

**Issue by Leepengfei** [tensorflow/tensorflow#21341] opened 2018-08-02 13:10 UTC
Hi,

Does tensorflow version r1.9 support Intel Xeon E5645 CPU?

Thanks !
Alan

**Comment by gunan** [comment] 2018-08-02 16:11
https://ark.intel.com/products/48768/Intel-Xeon-Processor-E5645-12M-Cache-2_40-GHz-5_86-GTs-Intel-QPI
Your CPU does not have AVX instruction set.
If you install from certain community maintained packages, or build from sources, yes.
If you install from official binaries, no

Closing as a duplicate of https://github.com/tensorflow/tensorflow/issues/19584

**Closed by gunan** 2018-08-02 16:11 UTC
