### ISSUE TITLE
Trying to create frozen graph with freeze_graph: IndexError: list index out of range

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#30555] opened 2019-07-10 08:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Docker image
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15+
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2080 Ti

I am trying to freeze a custom keras model (simple XOR) with the help of the freeze_graph script for later usage with the Coral TPU Stick. After a week of testing or so, I still can't get it to work because I am running into an error, caused by freeze_graph.

I think I am following the instructions correctly on creating a graph, so the script should work and produce a frozen graph. I am using the official `tensorflow:tensorflow:gpu-latest` docker image.

**Code**

With the following script, I create the graph in keras and save the quantized training graph.

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "uint8")
target_data = np.array([[0],[1],[1],[0]], "uint8")

model = Sequential()
model.add(Dense(16, input_dim=2, use_bias=False, activation='relu'))
model.add(Dense(1, use_bias=False, activation='sigmoid'))

session = tf.keras.backend.get_session()
tf.contrib.quantize.create_training_graph(session.graph)
session.run(tf.global_variables_initializer())

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, nb_epoch=1000, verbose=2)
print(model.predict(training_data).round())
model.summary()

saver = tf.train.Saver()
saver.save(keras.backend.get_session(), 'xor-keras.ckpt')

```

Then I load the graph and convert it into an eval graph with a second script:

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(16, input_dim=2, use_bias=False, activation='relu'))
model.add(Dense(1, use_bias=False, activation='sigmoid')) 


 #<Load the model into a new session>

session = tf.keras.backend.get_session()

saver = tf.train.Saver()
saver.restore(session, 'xor-keras.ckpt')

tf.contrib.quantize.create_eval_graph(session.graph)

tf.io.write_graph(session.graph, '.', 'xor-keras-eval.pb', as_text=False)
```

In my opinion, this should be valid input for the script, which I execute with the command:

`freeze_graph --input_graph='xor-keras-eval.pb' --input_checkpoint='xor-keras.ckpt' --output_graph='xor-keras-frozen.pb' --output_node_name='dense_1/Sigmoid' --input_binary=True`

This throws an error. Here the complete error traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/freeze_graph", line 10, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 487, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 486, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 378, in main
    flags.saved_model_tags, checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 361, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 190, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 482, in _build_internal
    names_to_saveables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 342, in validate_and_slice_inputs
    for converted_saveable_object in saveable_objects_for_op(op, name):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 205, in saveable_objects_for_op
    variable, "", name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 82, in __init__
    self.handle_op = var.op.inputs[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2410, in __getitem__
    return self._inputs[i]
IndexError: list index out of range
```

I have tried executing my scripts with a custom docker image with tensorflow 1.13.1 and Python 3.6.8, but with the same result. I also found other threads with similar/the same issue #20886 and #24591, but none of the proposed solutions worked. I am quite confident that this is a bug, and want you to verify that I am doing it correctly.

**Comment by rmothukuru** [comment] 2019-07-11 10:03
@DocDriven ,
I have tried executing the second script and I am getting the error, 

```
NotFoundError: Key dense_2/kernel not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]
```.

Can you please provide correct reproducible code snippet. Thanks.

**Comment by DocDriven** [comment] 2019-07-11 14:15
@rmothukuru : I have double checked my posted code and tested it with both docker images/Python versions, but I can't reproduce your error. I could share my images with you, if this helps.

**Comment by smartcatdog** [comment] 2019-08-02 02:47
ckpt model can be transferred to GraphDef(pb)model by freeze_graph.py in tensorflow,
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py](url)
or you can do like this depend by your code:
1) load your ckpt model and generate graph
2) use tf.saver to save your model [however, this generate model is made up of saved_model.pb and variables folder]

**Comment by ymodak** [comment] 2019-08-15 20:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-08-15 20:45 UTC
Labels: TF 1.14, comp:grappler, type:support
