### ISSUE TITLE
Pyinstaller with Tensorflow takes incorrect path for _checkpoint_ops.so file

### ISSUE THREAD

**Issue by piyushshri** [tensorflow/tensorflow#13060] opened 2017-09-15 09:29 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04, Pyinstaller
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7.6
- **CUDA/cuDNN version**: CUDA 8.0 cuDNN 6.0
- **GPU model and memory**: 3x nVidia GEForce 1080

### Describe the problem
As Tensorflow's `load_op_library` finds paths according to the OS it is being run on, I believe this is a problem with Tensorflow in Pyinstaller environment. 

I am trying to make an executable of my Python code which uses Tensorflow . The executable gets generated correctly but when I try to run it, I get the following error:
```

Traceback (most recent call last):
  File "detection_init.py", line 14, in <module>
    import lib.tensorboxDetector as tensorboxDetector
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib/tensorboxDetector.py", line 26, in <module>
    from lib.train import build_forward
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib/train.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/__init__.py", line 22, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/python/ops/csiszar_divergence.py", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/python/ops/csiszar_divergence_impl.py", line 42, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/__init__.py", line 89, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 32, in <module>
  File "tensorflow/contrib/util/loader.py", line 55, in load_op_library
  File "tensorflow/python/framework/load_library.py", line 64, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so: cannot open shared object file: No such file or directory
[11241] Failed to execute script detection_init
```
If we look carefully, Pyinstaller is expecting the file `_checkpoint_ops.so` in directory `tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/` but there's no directory like this. `_checkpoint_ops.so` is located at `tensorflow/contrib/framework/python/ops/`. How can this be fixed?

**Comment by cy89** [comment] 2017-09-15 20:34
@sherrym do you have any suggestions, please?

**Comment by eyaler** [comment] 2017-09-17 21:42
i am seeing a similar issue when and only when doing:
pip install tensorflow -t project_folder
and then importing from the project_folder

**Comment by bw4sz** [comment] 2017-09-27 17:18
I think I am having a related issue. Has anyone been able to package tensorflow with pyinstaller?

I opened a SO

https://stackoverflow.com/questions/46369902/how-to-package-tensorflow-with-pyinstaller-on-macosx-what-is-tensorflow-interna

**Comment by eyaler** [comment] 2017-09-28 12:51
https://github.com/tensorflow/tensorflow/issues/13126

**Comment by bw4sz** [comment] 2017-09-28 20:43
@eyaler are you suggesting that packaging tensorflow may be effected by the relative paths? I can open a separate issue if my example wasn't a good fit here, but I think the pyinstaller challenge is larger than a PATH issue. Still trying to debug today, I will report back if adding to PYTHONPATH makes a difference in distributing as .exe

**Comment by bw4sz** [comment] 2017-09-28 21:43
Again, I can open a new issue, but my gut feeling is that this is the same underlying issue in tensorflow for distributing as an app as reported by other user above.

https://github.com/pyinstaller/pyinstaller/issues/2883

Hi, opening a new question with a reproducible example. Given growing importance of tensorflow, hopefully this is a known issue.  

Here is our program. Let's just load tensorflow and have it print out some path info.

```
tf_check.py

    import tensorflow
    print(tensorflow.__file__)
```

Run with pyinstaller.

```
    Bens-MacBook-Pro:tests ben$ pyinstaller tf_check.py 
    66 INFO: PyInstaller: 3.3
    66 INFO: Python: 2.7.10
    78 INFO: Platform: Darwin-16.7.0-x86_64-i386-64bit
    79 INFO: wrote /Users/ben/Documents/DeepMeerkat/tests/tf_check.spec
    87 INFO: UPX is not available.
```

Builds without a problem. Trying to run the tf_check under dist/tf_check/

yields
```
    Last login: Thu Sep 28 12:54:34 on ttys000
    Bens-MacBook-Pro:~ ben$ /Users/ben/Documents/DeepMeerkat/tests/dist/tf_check/tf_check ; exit;
    Traceback (most recent call last):
      File "tf_check.py", line 1, in <module>
      File "/Library/Python/2.7/site-packages/PyInstaller-3.3-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
        exec(bytecode, module.__dict__)
      File "tensorflow/__init__.py", line 24, in <module>
      File "/Library/Python/2.7/site-packages/PyInstaller-3.3-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
        exec(bytecode, module.__dict__)
      File "tensorflow/python/__init__.py", line 107, in <module>
      File "/Library/Python/2.7/site-packages/PyInstaller-3.3-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
        exec(bytecode, module.__dict__)
      File "tensorflow/python/platform/test.py", line 60, in <module>
      File "/Library/Python/2.7/site-packages/PyInstaller-3.3-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
        exec(bytecode, module.__dict__)
      File "mock/__init__.py", line 2, in <module>
      File "/Library/Python/2.7/site-packages/PyInstaller-3.3-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
        exec(bytecode, module.__dict__)
      File "mock/mock.py", line 71, in <module>
      File "pbr/version.py", line 461, in semantic_version
      File "pbr/version.py", line 448, in _get_version_from_pkg_resources
      File "pbr/packaging.py", line 755, in get_version
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mock was given, but was not able to be found.
    [1916] Failed to execute script tf_check
    logout
    Saving session...
    ...copying shared history...
    ...saving history...truncating history files...
    ...completed.
    Deleting expired sessions...9 completed.
    
    [Process completed]
```

Some system information

```
    Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tensorflow
    >>> tensorflow.__version__
    '1.3.0'
```

The same code works on Windows without a problem. Again, only when distributing with pyinstaller. 

Can anyone show an example of packaging tensorflow on OSX?

**Comment by goodloop** [comment] 2017-11-06 06:45
can we get any point here ? is this a problem of pyinstaller or tensorflow ?

**Comment by tensorflowbutler** [comment] 2017-12-20 01:06
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:14
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:15
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by drpngx** [comment] 2018-02-03 01:16
Is that still happening in the latest version? I haven't heard anything recently on that front.

**Comment by tensorflowbutler** [comment] 2018-02-17 13:31
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-04 13:04
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-19 15:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment] 2018-03-20 18:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-03-20 18:48 UTC
Labels: stat:awaiting response

**Comment by shuntos** [comment] 2018-06-29 07:51
tensorflow.python.framework.errors_impl.NotFoundError: /home/bitberry/darkflow/dist/detect_from_image/tensorflow/contrib/coder/python/ops/_coder_ops.so: cannot open shared object file: No such file or directory
[11102] Failed to execute script detect_from_image

**Comment by drpngx** [comment] 2018-06-29 17:37
Is the file present? Can you try ldd on it?
