### ISSUE TITLE
tensorflow-gpu 2.0 pip package outdated/missing/name wrong

### ISSUE THREAD

**Issue by rjurney** [tensorflow/tensorflow#32751] opened 2019-09-24 00:41 UTC
## URL(s) with the issue:

https://www.tensorflow.org/install/pip

## Description of issue (what needs changing):

The current pip package that exists on PyPi is `tensorflow-gpu==2.0.0rc2`. The documentation says `tensorflow-gpu==2.0.0-rc1`, which is 2 typos.

The command to install it is `pip install tensorflow-gpu==2.0.0rc2`.

The documents say `pip install tensorflow-gpu==2.0.0-rc1`, which is two typos.

This bug has existed for all release candidates.

```python
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==dont_exist (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2)
```

**Comment by kwonnaseong** [comment] 2019-09-24 01:31
I will do it.

**Comment by Saptarshi-Ghosh-98** [comment] 2019-09-24 13:06
Btw, both `tensorflow-gpu==2.0.0-rc2` and `tensorflow-gpu==2.0.0rc2` works.

**Comment by rjurney** [comment] 2019-09-24 16:31
In my tests `-rc2` did not work. Nor did previous release candidates. With the dash has never worked, there hasn’t been an asset with a dash on pypi. I lasted the available packages above, there is no dash.

**Comment by mihaimaruseac** [comment] 2019-09-24 20:13
This is most likely an issue with the pip version.

On my system I am able to install both with dash and without dash

```console
(dash) mihaimaruseac@ankh:/tmp/32751/dash$ pip install -q tensorflow-gpu==2.0.0-rc2
(dash) mihaimaruseac@ankh:/tmp/32751/dash$ echo $?
0
(dash) mihaimaruseac@ankh:/tmp/32751/dash$ python -c "import tensorflow as tf; print(tf.__path__)"
['/tmp/32751/dash/lib/python3.6/site-packages/tensorflow']

# change environment

(nodash) mihaimaruseac@ankh:/tmp/32751/nodash$ pip install -q tensorflow-gpu==2.0.0rc2
(nodash) mihaimaruseac@ankh:/tmp/32751/nodash$ echo $?
0
(nodash) mihaimaruseac@ankh:/tmp/32751/nodash$ python -c "import tensorflow as tf; print(tf.__path__)"
['/tmp/32751/nodash/lib/python3.6/site-packages/tensorflow']
```

I am using pip 19.2.3 which seems to be the latest (`pip install --upgrade pip` doesn't bring anything new).

As such, closing the issue.

**Closed by mihaimaruseac** 2019-09-24 20:13 UTC
Labels: type:docs

**Comment by rjurney** [comment] 2019-09-24 20:39
@mihaimaruseac I have the same pip version as you. That you can’t reproduce it doesn’t mean it doesn’t exist - look at the versions available on the pypi page for tensorflow-gpu and you’ll see the one with the dashes is missing. This seems to be proof of the problem?

**Comment by mihaimaruseac** [comment] 2019-09-24 21:00
See https://github.com/pypa/pip/issues/5021

**Comment by rjurney** [comment] 2019-09-24 21:56
@mihaimaruseac I have the latest version of pip and this is happening. Given that you know this is a bug, why have you closed this ticket?

**Comment by mihaimaruseac** [comment] 2019-09-24 22:45
I closed the bug because this is not an issue that tensorflow devs need to handle. Leaving it open will just drown out other issues that we should be working on. Afaik, it is standard to deduplicate issues and close those that are caused from upstream, favoring the upstream issue.

**Comment by rjurney** [comment] 2019-09-24 23:00
@mihaimaruseac Just so I understand you correctly, the reason pypi lists no package with a dash is because of this bug? And pip removes the dash automatically?

**Comment by mihaimaruseac** [comment] 2019-09-24 23:19
See [the corresponding section in PEP 440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers) and [examples in same PEP](https://www.python.org/dev/peps/pep-0440/#pre-releases): there is no dash in the canonical name. 

Regarding the PyPi website: the redirect that is being done is legit, rather than display the same content at two URLs one returns a 301 and redirects to the canonical URL.

Regarding the `pip` expected behavior: see [normalization section in same PEP](https://www.python.org/dev/peps/pep-0440/#normalization). It explains why `pip install TensorFlow==2.0.0-----c00002` should do the same as `pip install tensorflow==2.0.0rc2`. If it doesn't, see the bug I linked above on PyPa.

**Comment by rjurney** [comment] 2019-09-24 23:48
Ok, thank you. I get it.
