### ISSUE TITLE
relaxing numpy requirement

### ISSUE THREAD

**Issue by casassg** [tensorflow/tensorflow#43679] opened 2020-09-30 18:07 UTC
Numpy is fixed to `<1.19` in current main branch. Justification in [code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L64) is that it was waiting for https://github.com/numpy/numpy/pull/15355 to be merged. But it seems to be merged and deployed. Is there any reason to maintain the current fixed version of numpy?

**Comment by mihaimaruseac** [comment] 2020-09-30 18:45
The main issue is that the numpy PR breaks TF compilation. So we introduced the numpy bound.

**Comment by casassg** [comment] 2020-09-30 19:11
Is there any plans to fix it from either Tensorflow or Numpy side?

**Comment by mihaimaruseac** [comment] 2020-10-02 16:53
Yes, See #40728 for example.

**Comment by pavanky** [comment] 2020-10-08 20:01
@mihaimaruseac Are there commits in a new branch that we can merge? This is blocking our internal stack and we want to rebuild tensorflow 2.3 with the right patches applied.

**Comment by mihaimaruseac** [comment] 2020-10-08 20:45
#40728 is the only public branch at this time, unfortunately.

**Comment by pavanky** [comment] 2020-10-08 22:25
@mihaimaruseac according to https://github.com/tensorflow/tensorflow/pull/40728#issuecomment-698217353 the issue seems to be fixed in 2 commits already ? Looking at the dates they should have made it into 2.3.

Am I missing something ?

**Comment by mihaimaruseac** [comment] 2020-10-09 17:54
Neither of those two commits has been made on the `r2.3` branch (that is, they have not been made before branch was cut, nor have they been cherry-picked to the branch). They are included in nightly builds and will be included in TF 2.4.

**Comment by pavanky** [comment] 2020-10-09 18:11
@mihaimaruseac Do they fix the numpy issue or are they unrelated ? because the setup.py in master branch still forces numpy < 1.19 (I am assuming nightlies also have this limitation).

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py

**Comment by mihaimaruseac** [comment] 2020-10-09 18:14
I think we need a different PR to relax `setup.py`.

**Comment by pavanky** [comment] 2020-10-09 18:17
Thanks for the info! This helps us in building a custom wheel to use internally.

**Comment by mihaimaruseac** [comment] 2020-10-09 18:20
Note that `setup.py` is only used to determine which `numpy` wheel gets installed on your system. The API breakage is caused by the Numpy C++ API and only affects compiling TF. If you don't need to compile TF but only use a newer numpy, you can just ignore the bound in `setup.py`.

**Comment by mihaimaruseac** [comment] 2020-10-16 20:39
Fixed by aafe25d

**Closed by mihaimaruseac** 2020-10-16 20:39 UTC
Labels: type:others

**Comment by casassg** [comment] 2020-10-16 23:19
is there any plans to add a release any time soon to include this?

**Comment by mihaimaruseac** [comment] 2020-10-16 23:21
There is going to be the 2.4 release

**Comment by casassg** [comment] 2020-10-16 23:23
is there any approximate date for the 2.4 release? Mostly wondering as we currently had to build our own wheel to unlock upgrading wheel and it would be nice to have it synced w OSS.

**Comment by mihaimaruseac** [comment] 2020-10-16 23:47
Yes, [branch cut is next week](https://groups.google.com/a/tensorflow.org/g/developers/c/jEaxXK6-C5k) and then we start the release process which can take 2 weeks if all goes well
