### ISSUE TITLE
Kernel dies on interpreter.invoke()

### ISSUE THREAD

**Issue by asimsultan** [tensorflow/tensorflow#50002] opened 2021-06-02 23:56 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version 2.5

**So here is the attached code in which I am loading a tflite model and I want to perform inference on that, for 1 input it works fine but when I changed the input_tensor to 1000, it kills the kernel. Any solution for this? Thanks!**

```
from transformers import MobileBertModel, MobileBertConfig, MobileBertTokenizer, MobileBertForSequenceClassification, MobileBertTokenizerFast, TFMobileBertModel
import numpy as np
import tensorflow as tf
import pandas as pd
path = 'mobilequantmodel.tflite'

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=path)
interpreter.allocate_tensors()

# model_name = 'bert-base-uncased'
model_name = "google/mobilebert-uncased"
print(model_name)

# Max length of tokens
max_length = 100

config = MobileBertConfig.from_pretrained(model_name)
config.output_hidden_states = False

# Load BERT tokenizer
tokenizer = MobileBertTokenizerFast.from_pretrained(pretrained_model_name_or_path = model_name, config = config)
df = pd.read_csv('file_sentences.csv')

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_shape = input_details[0]['shape']

ddf = df[(df['useful'] == 1) & (df['language']=='en')]

x_test = tokenizer(
  text= ddf['paragraph'].to_list(),
  add_special_tokens=True,
  max_length=max_length,
  truncation=True,
  return_tensors='tf',
  padding='max_length', 
  return_token_type_ids = False,
  return_attention_mask = False,
  verbose = True)

input_text = x_test['input_ids']

interpreter.resize_tensor_input(input_details[0]['index'], [1000, 100])
interpreter.allocate_tensors()

ipp = input_text[:1000]
interpreter.get_input_details()

interpreter.set_tensor(input_details[0]['index'], ipp)

interpreter.invoke()
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by abattery** [comment] 2021-06-03 02:03
It is really hard to reproduce your issue at our end. Please consider providing a minimal, reproducible step as a gist or provide the model file if possible.

**Comment by asimsultan** [comment] 2021-06-03 02:39
Sure, let me create a reproducible complete code snippet with the model.

**Comment by asimsultan** [comment] 2021-06-03 20:15
So I am going to explained my model working from scratch along with that, I am going to share my tflite model files so that be easy for you to interpret the error.

I have a dataset of sentiment analysis and I am using BertModel for its classification. I developed the bert model and I named it as SentimentBertModel.h5 and then using tflite, I changed the model to a tflite model to make it small in size and to do quick inference on that. The model gets converted and I named it as TheFinalQuantizedModel.tflite. Now when I perform the inference on that, on interpreter.invoke(), either the kernel dies or I get the following error which I am going to mentione now.


Code for the model development, conversion to tflite(quantization) and inference are all present in the given link along with the dataset used and the tflite model developed too. 

Link to all the files: https://drive.google.com/file/d/1cqq0OKVr3rKlH6yt-CLVskcnms7z6bte/view?usp=sharing

The error I get is this one.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-df579c7368bc> in <module>
----> 1 interpreter.invoke()
      2 output_data = interpreter.get_tensor(output_details[0]['index'])
      3 print(output_data)

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in invoke(self)
    538     """
    539     self._ensure_safe()
--> 540     self._interpreter.Invoke()
    541 
    542   def reset_all_variables(self):

RuntimeError: Encountered unresolved custom op: Erf.Node number 97 (Erf) failed to prepare.


NOTE: I am new to Quantization and if there is something that I am not doing right, kindly let me know from the scratch so I could just fix it soon.

**Comment by sachinprasadhs** [comment] 2022-10-06 21:05
This issue seems to be fixed in the previous version, related PR https://github.com/tensorflow/tensorflow/commit/3a6a6465c45797bd573c118a535405da43ab03fa, could you please try gain in the latest version and let us know the outcome. Thanks!

**Closed** 2022-10-20 22:18 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.5
