### ISSUE TITLE
How about we stop deprecating everything every other release....

### ISSUE THREAD

**Issue by acidtonic** [tensorflow/tensorflow#43303] opened 2020-09-17 16:18 UTC
I can't believe how terrible the experience is using these tools.

It seems the whole process is playing jigsaw puzzle games trying to line up all the versions so that something, anything works.

We are sorry but your original working tensorflow code for training is being moved to generic tf.slim for generic training.
We are sorry but your changed code using generic tf.slim was not specific enough, make these changes.
We are sorry but after having you do all this, tf.slim is moving to contrib.
Okay, now contrib is going away and here is a basic script that will just tell you cannot change anything for you, code it all again yourself. All 3rd party guides are now worthless.
(Roughly after about a year of this, I realized what a waste of time and left tensorflow)

Now I'm back only to try to get other frameworks (which work) models converted to tflite since it's the only decent solution for performance on mobile.
Of course the tools to convert to tf-lite require a bunch of tensorflow things to be installed again.
Oops, I'm using Cuda 10.1, watch pip packages try opening libcudart-9.
Install tensorflow 2.x from source for cuda 10.1, whoops it wants newer python now.
Install tensorflow addons, BOOM it doesn't support tensorflow 2.4.0.
Backdate to tensorflow 2.1, rebuild everything.
Install tensorflow addons, BOOM it doesn't support tensorflow <2.2.0.

I know this will just get closed and someone will mention that I'm wrong for being a Gentoo user who expects to build from source and not limp off of a packaging system to fix a project that cannot properly figure out how to handle backwards compatibility. Nor will I use some "docker" container....

Do you need some help coding? Is this intentional lock-in related movement to keep everyone rewriting things? Can you stop deprecating things long enough for someone to actually build something longer than a year and have it work when they are done? Thanks.

**Comment by acidtonic** [comment] 2020-09-17 16:18
Comment previously posted on Tensorflow/addons, but I deprecated it to get it over here ;)

**Comment by bhack** [comment] 2020-09-17 21:36
I think it is a duplicate of https://github.com/tensorflow/tensorflow/issues/43302

**Comment by acidtonic** [comment] 2020-09-28 15:40
Here's some more...

Converting a yolov3 model to TFLITE to run on a phone.

Tried 4 different projects.

1st: All code worked until needing slim from tf.contrib. Didn't want to rewrite their code.
2nd: needed onnx and tensorflow_addons but it doesn't work with tensorflow 1.x. Older pip package for tensorflow_addons with 1.x support is now removed so it cannot be done.
3rd: Go all the way through, it spit out tflite files that I then mapped into my android project. java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.

You'd think that means it would be the right format.... nope TFLITE has various "metadata" and looks like mine is missing it.

java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.

Stuck again. My tflite in a binary editor looks similar but has "TOCO Converted" where the example tflite for android shows "TFLITE_METADATA".

Just documenting the various ways I get stuck here, since I need a big collection to get enough ammo to make the case to management  for using something else.

**Comment by ymodak** [comment] 2020-10-05 22:29
@acidtonic Thank you for your feedback and apologies for the inconvenience.
`tf.contrib` module was a collection of modules contributed by external users as well as internal resources and it was a big challenge to maintain all of it along with TF 2 upgrades.

So we wanted to apply a divide and conquer approach where part of it is consumed in TF Core, another part where we have designated owners and some portions deprecated which were less popular and no one claimed ownership.
As a result we have TF Addons (works with TF 2.X) where we have revived popular modules of tf.contrib and also provides a place where users can request to add new functionality as well.
When using TF Addons it can be a good idea to familiarize yourself with python op compatibility with various TF versions. See https://github.com/tensorflow/addons#python-op-compatility

Lot of our developers prefer having support for the latest CUDA versions and sadly, CUDA is not backward compatible so some of the moves are breaking. As you can imagine it would create too many branches/forks to support several versions at once, which can be very resource intensive.

We appreciate your feedback and are committed to enhance TensorFlow significantly and provide a better user experience.

**Closed** 2020-10-14 19:40 UTC
Labels: stalled, stat:awaiting response, type:support
