### ISSUE TITLE
Tensorflow Random Function Always return 0

### ISSUE THREAD

**Issue by Strideradu** [tensorflow/tensorflow#6033] opened 2016-12-02 06:14 UTC
So import tensorflow showing following
```
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA li
l locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA li
locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA li
 locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA li
ally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA li
l locally
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with
name: GeForce GTX 760
major: 3 minor: 0 memoryClockRate (GHz) 1.15
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.35GiB
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow
(device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0)
E c:\tensorflow\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:586] Could not identify
calhost/replica:0/task:0/gpu:0, defaulting to 0.  Your kernel may not have been built with NUMA supp
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\direct_session.cc:255] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0
```
And generate random matrix

```
>>> a = tf.random_normal((100,100))
>>> sess.run(a)
random_normal/RandomStandardNormal: (RandomStandardNormal): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal/RandomStandardNormal: (Ran
domStandardNormal)/job:localhost/replica:0/task:0/gpu:0
random_normal/mul: (Mul): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal/mul: (Mul)/job:localhost/r
eplica:0/task:0/gpu:0
random_normal: (Add): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal: (Add)/job:localhost/repli
ca:0/task:0/gpu:0
random_normal/stddev: (Const): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal/stddev: (Const)/job:localh
ost/replica:0/task:0/gpu:0
random_normal/mean: (Const): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal/mean: (Const)/job:localhos
t/replica:0/task:0/gpu:0
random_normal/shape: (Const): /job:localhost/replica:0/task:0/gpu:0
I c:\tensorflow\tensorflow\tensorflow\core\common_runtime\simple_placer.cc:827] random_normal/shape: (Const)/job:localho
st/replica:0/task:0/gpu:0
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)
```

The basic matrix operation still works fine

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/1734 seems has similar problems
### Environment info
Operating System:
Windows 10
GeForce GTX 760 GPU
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 8.0
cuDNN 5.1

I follow the CMake instruction build from source (tf 0.12)

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by poxvoculi** [comment] 2016-12-02 17:20
I can't reproduce your problem.
1. Does it also occur if you place the operation on CPU, or is it GPU only?
2. Can you include more information about your environment, as requested by the new issue template?  e.g. OS, CUDA version, etc.

**Comment by Strideradu** [comment] 2016-12-02 17:43
I already provide the environment information in my post~ If you need more just let me know. And I will try your suggestion to try CPU this evening

**Comment by Strideradu** [comment] 2016-12-03 01:25
I change CUDA_VISIBLE_DEVICES to "", and rerun the random function and get the right results

```
>>> import tensorflow as tf
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dl
l locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll
locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll
 locally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll loc
ally
I c:\tensorflow\tensorflow\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dl
l locally
>>> sess = tf.Session()
E c:\tensorflow\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVI
CE
I c:\tensorflow\tensorflow\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:158] retrieving CUDA diagnostic informati
on for host: zsx988-Golden
I c:\tensorflow\tensorflow\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:165] hostname: zsx988-Golden
>>> a = tf.random_normal((100,100))
>>> sess.run(a)
array([[ -1.60603717e-01,  -9.76819277e-01,  -5.30430973e-01, ...,
          3.82902361e-02,   4.57652728e-04,   7.37040758e-01],
       [  3.86225969e-01,   2.95245004e+00,  -5.66983461e-01, ...,
         -1.39389920e+00,   1.87824667e+00,   3.45089823e-01],
       [  1.35846555e+00,   1.45867085e+00,   5.65616488e-02, ...,
         -1.53614789e-01,   7.22914577e-01,  -2.70827681e-01],
       ...,
       [  2.13479862e-01,  -1.67380559e+00,   4.74632114e-01, ...,
          3.85872096e-01,   1.64577377e+00,   2.13960743e+00],
       [ -7.64496267e-01,  -6.11636817e-01,  -3.17500472e-01, ...,
         -2.53556418e+00,  -1.09151840e+00,   4.00447100e-01],
       [ -4.60968226e-01,   8.84875000e-01,  -8.24124396e-01, ...,
         -6.42477036e-01,   5.90658069e-01,  -1.41880393e+00]], dtype=float32)
```

**Comment by poxvoculi** [comment] 2016-12-04 02:20
@zheng-xq looks like a CUDA random problem

**Comment by guschmue** [comment] 2016-12-06 03:22
Last time I have seen this was when the -gencode was not correct for the requested cuda compute
ability. A gtx 760 has cuda compute ability 3.0 but the default build enables only 3.5 and 5.1. 
Tensorflow should refuse to use this card unless CMakefile was changed and 3.0 was added to TF_EXTRA_CUDA_CAPABILITIES without adding 3.0 to -gencode.
OR there is some bug in that area.
I can take a look.

**Comment by guschmue** [comment] 2016-12-07 03:11
tested this on master (@mrry has enabled cuda 3.0 capability) and it works fine on a gtx 740 (which is 3.0). tf.random_normal((100,100))  works too. 
I think the only thing we need to try is that a cuda 3.0 card is not taken by a tensorflow build before cuda 3.0 was enabled.

**Comment by Strideradu** [comment] 2016-12-07 04:37
I followed the instruction given by https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake to build tensorflow which I supposed to support 3.0 as I modify on [this line](https://github.com/tensorflow/tensorflow/blob/a7b4f636d50b6fcb9cd1f7f138cc50b720fc86dd/tensorflow/contrib/cmake/CMakeLists.txt#L156) and[ this line](https://github.com/tensorflow/tensorflow/blob/a7b4f636d50b6fcb9cd1f7f138cc50b720fc86dd/tensorflow/contrib/cmake/CMakeLists.txt#L166). Did I miss something?

**Comment by guschmue** [comment] 2016-12-07 05:04
ah, need to fix that comment: the -gencode need to change too so nvcc generates the 3.0 code.  That explains why tensorflow took the card but returned zeros. The correct change is here:
https://github.com/tensorflow/tensorflow/commit/669b2cc9fa02527c87e9f82bd4ac7d76e715d2a8#diff-1d799fa350437420218e5e5aa680c481

**Comment by tfboyd** [comment] 2017-06-16 16:46
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Closed by tfboyd** 2017-06-16 16:46 UTC
Labels: stat:awaiting tensorflower
