### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'is_jpeg'

### ISSUE THREAD

**Issue by Aliennandy** [tensorflow/tensorflow#26606] opened 2019-03-12 13:15 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10 Pro 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.6
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.0
- GPU model and memory: Nvidia Quadro P4000 - 8GB

While running the train.py - it fails with the attribute error

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
PS D:\Nanda\DeepLabs\models-master\research\deeplab> python train.py --logtostderr --train_split="train" --model_variant="xcep
tion_65" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --decoder_output_stride=4 --train_crop_size=5
13 --train_crop_size=513 --train_batch_size=4 --training_number_of_steps=100 --fine_tune_batch_norm=true --tf_initial_checkpoi
nt="D:/Nanda/DeepLabs/models-master/research/deeplab/datasets/Datathon/exp/train_on_trainval_set/init_models/deeplabv3_pascal_
train_aug/model.ckpt" --train_logdir="D:/Nanda/DeepLabs/models-master/research/deeplab/datasets/Datathon/exp/train_on_trainval
_set/train/" --dataset_dir="D:/Nanda/DeepLabs/models-master/research/deeplab/datasets/Datathon/tfrecord"
INFO:tensorflow:Training on train set
Traceback (most recent call last):
  File "train.py", line 499, in <module>
    tf.app.run()
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 451, in main
    dataset.get_one_shot_iterator(), dataset.num_of_classes,
  File "D:\Nanda\DeepLabs\models-master\research\deeplab\datasets\data_generator.py", line 335, in get_one_shot_iterator
    .map(self._parse_function)
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 790, in map
    return MapDataset(self, map_func)
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1597, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "C:\Users\nvenugop\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1562, in tf_map_func
    ret = map_func(nested_args)
  File "D:\Nanda\DeepLabs\models-master\research\deeplab\datasets\data_generator.py", line 246, in _parse_function
    image = _decode_image(parsed_features['image/encoded'], channels=3)
  File "D:\Nanda\DeepLabs\models-master\research\deeplab\datasets\data_generator.py", line 223, in _decode_image
    tf.image.is_jpeg(content),
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'is_jpeg'

**Comment by jvishnuvardhan** [comment] 2019-03-14 18:25
@Aliennandy Could you check this with latest version of TF and let us know whether the bug persists with latest TF. Could you share a code to reproduce the bug? Thanks!

**Comment by tensorflowbutler** [comment] 2019-03-29 13:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-03-29 16:05
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-29 16:05 UTC
Labels: comp:model, stat:awaiting response, type:support

**Comment by i-amgeek** [comment] 2021-08-15 20:50
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'sobel_edges' using tensorflow=1.7
