### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by Harvey13** [tensorflow/tensorflow#39817] opened 2020-05-23 17:32 UTC
I use tensorflow with Google Colaboratory
I have TensorFlow 2.x selected.

I wrote a small error metrics but could not succeed to transform the result to numpy array.
I got AttributeError: 'Tensor' object has no attribute 'numpy'

I thought I could transform my tensor to numpy array with a .numpy() call

```
def custom__error(y_true, y_pred):
  # ---- y_pred
  yp = tf.nn.softmax( y_pred)
  bp = tf.argsort(yp,axis=-1,direction='DESCENDING',stable=False,name=None)
  #cp = bp.numpy()
  xcp = bp[None,:10]
  # ---- y_true
  yt = tf.nn.softmax( y_true )
  bt = tf.argsort(yt,axis=-1,direction='DESCENDING',stable=False,name=None)
  #ct = bt.numpy()
  xct = bt[None,:10]
  # ---- common
  count =  tf.sets.intersection(xcp,xct)
  dcount = tf.sparse.to_dense(count)
  return dcount.numpy()
```
```
<ipython-input-46-10646c4f8b46> in custom__error(y_true, y_pred)
     15   count =  tf.sets.intersection(xcp,xct)
     16   dcount = tf.sparse.to_dense(count)
---> 17   return dcount.numpy()
     18 
     19 

AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by abhipn** [comment] 2020-05-24 17:36
> I use tensorflow with Google Colaboratory
> I have TensorFlow 2.x selected.
> 
> I wrote a small error metrics but could not succeed to transform the result to numpy array.
> I got AttributeError: 'Tensor' object has no attribute 'numpy'
> 
> I thought I could transform my tensor to numpy array with a .numpy() call
> 
> ```
> def custom__error(y_true, y_pred):
>   # ---- y_pred
>   yp = tf.nn.softmax( y_pred)
>   bp = tf.argsort(yp,axis=-1,direction='DESCENDING',stable=False,name=None)
>   #cp = bp.numpy()
>   xcp = bp[None,:10]
>   # ---- y_true
>   yt = tf.nn.softmax( y_true )
>   bt = tf.argsort(yt,axis=-1,direction='DESCENDING',stable=False,name=None)
>   #ct = bt.numpy()
>   xct = bt[None,:10]
>   # ---- common
>   count =  tf.sets.intersection(xcp,xct)
>   dcount = tf.sparse.to_dense(count)
>   return dcount.numpy()
> ```
> 
> ```
> <ipython-input-46-10646c4f8b46> in custom__error(y_true, y_pred)
>      15   count =  tf.sets.intersection(xcp,xct)
>      16   dcount = tf.sparse.to_dense(count)
> ---> 17   return dcount.numpy()
>      18 
>      19 
> 
> AttributeError: 'Tensor' object has no attribute 'numpy'
> ```

It works fine for me. This usually happens in older version of tensorflow where you have to enable eager execution. Are you sure that tensorflow version is >= 2.x?

**Comment by Harvey13** [comment] 2020-05-24 19:31
Hello abhipn
I wrote
%tensorflow_version 2.x
And got
```
`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.

TensorFlow is already loaded. Please restart the runtime to change versions.
```
If you want to check
[https://colab.research.google.com/drive/14TC0Hgf_aKtSTwlZvUKMlVYZUdvUuVJv?usp=sharing](url)

**Comment by abhipn** [comment] 2020-05-24 21:32
@Harvey13 Can you provide minimal reproducible notebook so I can execute the code and get the error you are facing?

**Comment by ravikyram** [comment] 2020-05-25 10:36
@Harvey13 

Request you to provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Harvey13** [comment] 2020-05-25 11:22
[https://colab.research.google.com/drive/12fkayzNa0uOIRkKJYsZ0J7VjwS0P-BXd?usp=sharing](url)

**Comment by Harvey13** [comment] 2020-05-25 11:31
My problem is only inside a callback function (tf backend)
[https://colab.research.google.com/drive/1wFKDQjlPuB0ax0g-ZSU8ge1ukzBBn3TR?usp=sharing](url)

**Comment by Harvey13** [comment] 2020-05-25 12:55
Access for everyone with the link

**Comment by abhipn** [comment] 2020-05-25 18:18
@Harvey13 I was able to replicate the issue and I believe it is not possible to extract numpy arrays in Keras loss functions (or) metrics. You have to operate on tensors using either keras backend functions or tensorflow functions but not using numpy to calculate the loss.

**Comment by ravikyram** [comment] 2020-05-26 11:00
@Harvey13 

Can you please provide correct colab link to understand the issue better.Thanks!

**Comment by Harvey13** [comment] 2020-05-26 11:15
@ravikyram 
[https://colab.research.google.com/drive/1wFKDQjlPuB0ax0g-ZSU8ge1ukzBBn3TR?usp=sharing](url)

**Comment by ravikyram** [comment] 2020-05-26 11:29
I have tried in colab with TF 2.2 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d8858bca32d165a6091d4558d269597a/untitled43.ipynb).Thanks!

**Comment by ravikyram** [comment] 2020-05-26 11:37
I have tried in TF nightly version`(2.3.0-dev20200526`) and i am seeing below error message`.AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/597eacdc5051d3368b7ce7740b50dfb8/untitled43.ipynb#scrollTo=umFa7Ez8wr46)Thanks!

**Comment by jvishnuvardhan** [comment] 2020-06-06 07:40
@Harvey13 Looks like this was resolved. I am not able to reproduce the issue. Can you please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/eb63a5055c5c04903f0c672fae789dec/untitled43.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by Harvey13** [comment] 2020-06-07 14:57
@jvishnuvardhan The gist works fine, even with original custom__error function.
Unfortunatly my own project, no more works, even without numpy() call inside backend function : it's a new bug because it was working fine former the nightlty installed

I tried differents old projects they all have the same error with tf-nightly :
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-2a71bdab68f1> in <module>()
----> 1 model = make_model()
      2 print(str(training_data_width) + "=>" + str(target_data_width))
      3 model.compile(loss=custom__loss, optimizer='adam', metrics=['binary_accuracy','accuracy',custom__error])

5 frames
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in is_tensor(x)
    701 
    702 def is_tensor(x):
--> 703     return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
    704 
    705 

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'
```

**Comment by Harvey13** [comment] 2020-06-09 10:52
> Message du 06/06/20 09:40> De : "Vishnuvardhan Janapati" > A : "tensorflow/tensorflow" > Copie à : "Harvey13" , "Mention" > Objet : Re: [tensorflow/tensorflow] AttributeError: 'Tensor' object has no attribute 'numpy' (#39817)> >
>
> @Harvey13 Looks like this was resolved. I am not able to reproduce the issue. Can you please check the gist here. Thanks!
> Please verify once and close the issue if this was resolved for you. Thanks!
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/tensorflow/tensorflow/issues/39817#issuecomment-640005373", "url": "https://github.com/tensorflow/tensorflow/issues/39817#issuecomment-640005373", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by jvishnuvardhan** [comment] 2020-06-09 20:46
@Harvey13 When error description include `'_TensorLike'`, then mostly it is due to using mixing functions from `keras` and `tf.keras` in the code. Can you please share a standalone code that is throwing an error. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-06-11 21:41
@Harvey13 I am closing this issue as you confirmed that the issue was resolved. Thanks!

**Closed by jvishnuvardhan** 2020-06-11 21:41 UTC
Labels: TF 2.2, comp:keras, stat:awaiting response, type:bug
