### ISSUE TITLE
tfp.JointDistributionSequential._build() -> line 236, in _build     if not isinstance(model, collections.Sequence): AttributeError: module 'collections' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by eipiisneg1** [tensorflow/tensorflow#58708] opened 2022-11-28 05:34 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Mac OS 13.0.1 (22A400)

### Python version

3.10

### Current Behaviour?

```shell
A bug happened!

I expected the code in the tfp guide to run as written. 

I did...
import collections.abc as collections

According to python doc:

isinstance(object, classinfo), 
Return True if the object argument is an instance of the classinfo argument

However, the classinfo argument in Pycharm is 
{ABCMeta} <class 'collections.abc.Sequence'>

and tfp code is

"if not isinstance(model, collections.Sequence)"

My guess is tfp code should be:

"if not isinstance(model, collections.abc.Sequence)"
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/probability/blob/main/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb


Code to reproduce:

dfhogg = pd.DataFrame(np.array([[1,201,592,61,9,-0.84],
                                [2,244,401,25,4,0.31],
                                [3,47,583,38,11,0.64],
                                [4,287,402,15,7,-0.27],
                                [5,203,495,21,5,-0.33],
                                [6,58,173,15,9,0.67],
                                [7,210,479,27,4,-0.02],
                                [8,202,504,14,4,-0.05],
                                [9,198,510,30,11,-0.84],
                                [10,158,416,16,7,-0.69],
                                [11,165,393,14,5,0.30],
                                [12,201,442,25,5,-0.46],
                                [13,157,317,52,5,-0.03],
                                [14,131,311,16,6,0.50],
                                [15,166,400,34,6,0.73],
                                [16,160,337,31,5,-0.52],
                                [17,186,423,42,9,0.90],
                                [18,125,334,26,8,0.40],
                                [19,218,533,16,6,-0.78],
                                [20,146,344,22,5,-0.56]]),
                      columns=['id','x','y','sigma_y','sigma_x','rho_xy'])

## for convenience zero-base the 'id' and use as index
dfhogg['id'] = dfhogg['id'] - 1
dfhogg.set_index('id',inplace=True)

## standardize (mean center and divide by 1 sd)
dfhoggs = (dfhogg[['x','y']] - dfhogg[['x','y']].mean(0)) / dfhogg[['x','y']].std(0)
dfhoggs['sigma_y'] = dfhogg['sigma_y'] / dfhogg['y'].std(0)
dfhoggs['sigma_x'] = dfhogg['sigma_x'] / dfhogg['x'].std(0)

X_np = dfhogg['x'].values
sigma_y_np = dfhogg['y'].values
Y_np = dfhogg['y'].values

mdl_ols = tfd.JointDistributionSequential([
    # b0 ~ Normal(0, 1)
    tfd.Normal(loc=tf.cast(0, dtype), scale=1.),
    # b1 ~ Normal(0, 1)
    tfd.Normal(loc=tf.cast(0, dtype), scale=1.),
    # x ~ Normal(b0+b1*X, 1)
    lambda b1, b0: tfd.Normal(
      # Parameter transformation
      loc=b0 + b1*X_np,
      scale=sigma_y_np)
])
```

### Relevant log output

```shell
line 236, in _build
    if not isinstance(model, collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'
```
</details>

**Comment by mohantym** [comment] 2022-11-28 12:50
Hi @eipiisneg1 !
Could you post the same code as Colab gist as I was getting different error.
I think It would be better addressed in [Tensorflow/probablity](https://github.com/tensorflow/probability/issues) repo.

Thank you!

**Comment by eipiisneg1** [comment] 2022-12-05 15:31
No one has replied to me?On Dec 5, 2022, at 08:16, google-ml-butler[bot] ***@***.***> wrote:﻿
This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.

**Comment by eipiisneg1** [comment] 2022-12-07 14:18
Thank you for responding. I do not use colab as to write code. The code ran fine in colab. I run Code in pycharm and returned an error when I ran the code. Fortunately, pycharm’s traceback is a hyperlink and allows me to open this executable stored on my machine.That how I found it. I fixed it by simply changing it to collections.abc…Is it possible this issue is found only in code installed via conda environments? Thanks for responding. ScottOn Dec 7, 2022, at 07:02, SuryanarayanaY ***@***.***> wrote:﻿
Hi @eipiisneg1 ,
Could you please pin point the exact tfp guide which you are referring to?
I did checked the attached link of yours which is mentioned below. https://github.com/tensorflow/probability/blob/main/tensorflow_probability/examples/jupyter_notebooks/Modeling_with_JointDistribution.ipynb
But i am unable to find any code like if not isinstance(model, collections.Sequence) or if not isinstance(model, collections.abc.Sequence).Please check whether the attached link is what you wants to refer to ?
Also the code you attached for replicating the issue does not raising any error.Please refer to attached gist.
Thankyou!

**Comment by SuryanarayanaY** [comment] 2022-12-08 13:30
Hi @eipiisneg1 ,

I checked with 2.8.* versions on the colab and there iam getting the below error.Earlier gist was with default colab import versions which is 2.9.2.Please find the attached [gist of 2.8 V](https://colab.sandbox.google.com/gist/SuryanarayanaY/9fc1e0cff872fa38fcd546f9b476bb24/58708-2-8v.ipynb#scrollTo=-9xf_QgBeuNw) with different behaviour.

> ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.9; Detected an installation of version 2.8.4. Please upgrade TensorFlow to proceed.

It seems the issue is due to version mismatch where in pycharm does felicitated to debug the issue for your code.I expect that with 2.9.2 and higher even in pycharm you might not get any error.Could you please try with updated version and confirm ?

Thankyou.

**Comment by eipiisneg1** [comment] 2022-12-08 19:55
Thank you so much. On Dec 8, 2022, at 08:30, SuryanarayanaY ***@***.***> wrote:﻿
Hi @eipiisneg1 ,
I checked with 2.8.* versions on the colab and there iam getting the below error.Earlier gist was with default colab import versions which is 2.9.2.Please find the attached gist of 2.8 V with different behaviour.

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.9; Detected an installation of version 2.8.4. Please upgrade TensorFlow to proceed.

It seems the issue is due to version mismatch where in pycharm does felicitated to debug the issue for your code.I expect that with 2.9.2 and higher even in pycharm you might not get any error.Could you please try with updated version and confirm ?
Thankyou.

**Comment by SuryanarayanaY** [comment] 2022-12-12 13:29
Hi @eipiisneg1 ,
Could you please confirm whether the issue got resolved and if so request you to close the issue.

**Comment by eipiisneg1** [comment] 2022-12-12 14:33
Thank you. You can close the issue. On Dec 12, 2022, at 08:29, SuryanarayanaY ***@***.***> wrote:﻿
Hi @eipiisneg1 ,
Could you please confirm whether the issue got resolved and if so request you to close the issue.

**Comment by SuryanarayanaY** [comment] 2022-12-13 14:06
Thanks @eipiisneg1 for confirmation.Closing it as resolved.

Thankyou!

**Closed by SuryanarayanaY** 2022-12-13 14:06 UTC
Labels: type:bug, comp:apis, TF 2.8
