### ISSUE TITLE
Using tf.constant in the model causes saving to fail

### ISSUE THREAD

**Issue by Gilthans** [tensorflow/tensorflow#38117] opened 2020-04-01 13:04 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): **binary**
- TensorFlow version (use command below): v2.2.0-rc1-34-ge6e5d6df2a 2.2.0-rc2
- Python version: 3.7
 - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 970, 4GB memory

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Whenever I try to save a model which has a tf.constant as input, it fails with "IndexError: list index out of range" from inside Keras.
If instead of tf.constant I use a keras Input and pass the same value, everything seems fine.
Note that the model trains and infers successfully, so this is probably an export issue.

**Describe the expected behavior**
Save should succeed.

**Standalone code to reproduce the issue** 

        import numpy as np
        import tensorflow as tf
        from tensorflow.keras.layers import Input, Dense, Concatenate, TimeDistributed, Bidirectional, LSTM
        from tensorflow.keras.models import Model
        from pathlib import Path

        batch_size = 32
        max_sentence_len = 80
        recurrent_size = 96
        embedding_dim = 1024

        encoder_inputs = Input(batch_shape=(batch_size, max_sentence_len, embedding_dim), dtype='float32')
        encoder_lstm = Bidirectional(
            LSTM(recurrent_size, return_sequences=True, return_state=True))
        (encoder_out, encoder_fwd_hstate, encoder_fwd_cstate, encoder_back_hstate, encoder_back_cstate) = encoder_lstm(
            encoder_inputs)

        decoder_lstm = LSTM(recurrent_size * 2, return_sequences=True, return_state=True)

        **inp = tf.constant(np.zeros((batch_size, 2, 2)), dtype='float32')**
        decoder_out, decoder_hstate, decoder_cstate = decoder_lstm(
            inp, initial_state=[Concatenate(axis=-1)([encoder_fwd_hstate, encoder_back_hstate]),
                                Concatenate(axis=-1)([encoder_fwd_cstate, encoder_back_cstate])]
        )

        dense = Dense(2, activation='softmax')
        dense_time = TimeDistributed(dense)
        decoder_pred = dense_time(decoder_out)

        full_model = Model(inputs=encoder_inputs, outputs=decoder_pred)
        full_model.compile(optimizer='adam', loss='binary_crossentropy')

        save_dir = Path('D:\\tmp\\train_logs\\saved_model\\')
        save_dir.mkdir(parents=True, exist_ok=True)

        full_model.save(str(save_dir))

**Other info / logs** 
2020-04-01 16:01:14.975117: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-04-01 16:01:17.343365: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-01 16:01:17.533497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 208.91GiB/s
2020-04-01 16:01:17.533758: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-01 16:01:17.537501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-01 16:01:17.541404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-01 16:01:17.542637: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-01 16:01:17.546712: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-01 16:01:17.549502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-01 16:01:17.558631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-01 16:01:17.559629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-04-01 16:01:17.559985: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-01 16:01:17.568641: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x28f8bd6e360 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-01 16:01:17.568829: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-01 16:01:17.569437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 208.91GiB/s
2020-04-01 16:01:17.569701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-04-01 16:01:17.569832: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-04-01 16:01:17.570177: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-04-01 16:01:17.570366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-04-01 16:01:17.570541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-04-01 16:01:17.570676: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-04-01 16:01:17.570798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-01 16:01:17.571827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-04-01 16:01:18.141216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-01 16:01:18.141366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-04-01 16:01:18.141448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-04-01 16:01:18.142398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2991 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:04:00.0, compute capability: 5.2)
2020-04-01 16:01:18.145329: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x28fa934abb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-01 16:01:18.145500: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 970, Compute Capability 5.2
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU
C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\layers\recurrent.py:820: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if (isinstance(inputs, collections.Sequence)
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU

Error
Traceback (most recent call last):
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\unittest\case.py", line 628, in run
    testMethod()
  File "D:\Work\Stuff\brain\doctor\models\texttoimprovement\model_test.py", line 48, in test_reproduce
    full_model.save(str(save_dir))
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1047, in save
    signatures, options)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\save.py", line 138, in save_model
    signatures, options)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\saved_model\save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\saved_model\save.py", line 1008, in _build_meta_graph
    checkpoint_graph_view)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\saved_model\signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\saved_model\save.py", line 143, in list_functions
    self._serialization_cache)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1593, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 2439, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 77, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\model_serialization.py", line 47, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saved_model\save_impl.py", line 203, in default_save_signature
    fn.get_concrete_function()
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\def_function.py", line 506, in _initialize
    *args, **kwds))
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\eager\def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 132, in _wrapped_model
    outputs = model(inputs, training=False)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\network.py", line 714, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\network.py", line 883, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2830, in call
    return self._make_op(inputs)
  File "C:\Users\Gilthans\anaconda3\envs\brain\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2843, in _make_op
    graph = inputs[0].graph
IndexError: list index out of range

**Comment by amahendrakar** [comment] 2020-04-02 10:35
@Gilthans,
I was able to run the given code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/65ae786b4d058caba56fa9f4e8a88972/38117.ipynb).

Could you please try running the code in a virtual environment and check if you are able to reproduce the error? Thanks!

**Comment by amahendrakar** [comment] 2020-04-09 17:06
Any updates regarding this issue? Thanks

**Comment by amahendrakar** [comment] 2020-04-16 17:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-16 17:27 UTC
Labels: TF 2.0, comp:keras, type:support

**Comment by Madhurananda** [comment] 2020-06-24 21:10
Hi there, I am getting this warning too: 
tensorflow:Layer lstm_1 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU

Also, it isn't taking all my samples while running. I have over two million samples but there is only 80286 samples have been taken by LSTM TensorFlow. 

Successfully opened dynamic library libcublas.so.10
 9865/80286 [==>...........................] - ETA: 25:56 - loss: 23.0515 - accuracy: 0.6120

**Comment by amahendrakar** [comment] 2020-06-25 09:46
@Madhurananda,
Please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ll01** [comment] 2020-06-27 23:03
> 
> 
> @Gilthans,
> I was able to run the given code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/65ae786b4d058caba56fa9f4e8a88972/38117.ipynb).
> 
> Could you please try running the code in a virtual environment and check if you are able to reproduce the error? Thanks!

https://colab.research.google.com/gist/ll01/7e2d7dda7cbd22ca0e547f439e82e012/38117.ipynb
