### ISSUE TITLE
How to test a saved model trained with tf.train.batch?

### ISSUE THREAD

**Issue by guoguoguilai** [tensorflow/tensorflow#29110] opened 2019-05-29 06:31 UTC
By calling graph.get_tensor_by_name("output:0")，I found that it returns a tensor shaped [batch_size,num]，How to test a saved model trained with tf.train.batch?

**Comment by gadagashwini** [comment] 2019-05-30 06:34
@guoguoguilai Please have look on this [link](https://www.tensorflow.org/guide/saved_model#loading_a_savedmodel_in_python) to load saved model. Thanks!

**Comment by gadagashwini** [comment] 2019-05-30 06:37
It looks, This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think it is a bug. Let us know. Thanks!

**Comment by gadagashwini** [comment] 2019-06-04 11:34
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-04 11:34 UTC
Labels: comp:ops, stat:awaiting response, type:support
