### ISSUE TITLE
a bizarre mistake-----InvalidArgumentError: slice index -1 of dimension 0 out of bounds.（）

### ISSUE THREAD

**Issue by ouy160** [tensorflow/tensorflow#32908] opened 2019-09-29 14:53 UTC
My computer is installed with win10, tf-nightly-2.0-preview==2.0.0dev20190926，python3.7&python3.6.8

Tensorflow standard template: https://tensorflow.google.cn/tutorials/load_data/images#setup

When I run the tensorflow standard template, I get an error in

    for image, label in labeled_ds.take(1):
        print("Image shape: ", image.numpy().shape)
        print("Label: ", label.numpy())

 the error message :
InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
[[{{node strided_slice}}]]
Encountered when executing an operation using EagerExecutor. 
This error cancels all future operations and poisons their output tensors.

However, in google colab I installed tf-nightly-2.0-preview==2.0.0dev20190926, python==3.6,
Running the code but it runs fine without errors

If I want to run this standard template code on my computer, how should I modify it?

**Comment by Leslie-Fang** [comment] 2019-09-30 00:12
It seems the only difference between google colab system and yours is the Python version?

**Comment by ouy160** [comment] 2019-09-30 04:08
> 看来Google colab系统与您的系统之间唯一的区别是Python版本？

I used the same python3.6.8 as colab and got the same error.

**Comment by ravikyram** [comment] 2019-09-30 05:37
I tried executing the standard template code in colab and on my computer successfully.Thanks!

**Comment by ouy160** [comment] 2019-10-01 00:00
But I can't successfully execute the code.
here is my pip list

Will there be any errors in my pip list?
Package                            Version
---------------------------------- -------------------
absl-py                            0.8.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.3
asn1crypto                         0.24.0
astor                              0.8.0
astroid                            2.2.5
astropy                            3.2.1
atomicwrites                       1.3.0
attrs                              19.1.0
Babel                              2.7.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.8.0
bitarray                           1.0.1
bkcharts                           0.2
bleach                             3.1.0
bokeh                              1.3.4
boto                               2.49.0
Bottleneck                         1.2.1
certifi                            2019.9.11
cffi                               1.12.3
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.2.2
clyent                             1.2.2
colorama                           0.4.1
comtypes                           1.1.7
conda-package-handling             1.6.0
conda-verify                       3.1.1
contextlib2                        0.6.0
cryptography                       2.7
cycler                             0.10.0
Cython                             0.29.13
cytoolz                            0.10.0
dask                               2.4.0
decorator                          4.4.0
defusedxml                         0.6.0
distributed                        2.4.0
docutils                           0.15.2
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
Flask                              1.1.1
fsspec                             0.5.1
future                             0.17.1
gast                               0.2.2
gevent                             1.4.0
glob2                              0.7
google-pasta                       0.1.7
greenlet                           0.4.15
grpcio                             1.24.0
h5py                               2.9.0
HeapDict                           1.0.1
html5lib                           1.0.1
idna                               2.8
imageio                            2.5.0
imagesize                          1.1.0
importlib-metadata                 0.23
ipykernel                          5.1.2
ipython                            7.8.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.15.1
Jinja2                             2.10.1
joblib                             0.13.2
json5                              0.8.5
jsonschema                         3.0.2
jupyter                            1.0.0
jupyter-client                     5.3.3
jupyter-console                    6.0.0
jupyter-core                       4.5.0
jupyterlab                         1.1.4
jupyterlab-server                  1.0.6
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.0
keyring                            18.0.0
kiwisolver                         1.1.0
lazy-object-proxy                  1.4.2
libarchive-c                       2.8
llvmlite                           0.28.0
locket                             0.2.0
lxml                               4.4.1
Markdown                           3.1.1
MarkupSafe                         1.1.1
matplotlib                         3.1.1
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.0.14
mkl-random                         1.1.0
mkl-service                        2.3.0
mock                               3.0.5
more-itertools                     7.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.0
nbformat                           4.4.0
networkx                           2.3
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.1
numba                              0.43.1
numexpr                            2.7.0
numpy                              1.16.5
numpydoc                           0.9.1
olefile                            0.46
openpyxl                           2.6.3
opt-einsum                         3.0.1
packaging                          19.2
pandas                             0.25.1
pandocfilters                      1.4.2
parso                              0.5.1
partd                              1.0.0
path.py                            12.0.1
pathlib2                           2.3.4
patsy                              0.5.1
pep8                               1.7.1
pickleshare                        0.7.5
Pillow                             6.1.0
pip                                19.2.3
pkginfo                            1.5.0.1
pluggy                             0.13.0
ply                                3.11
prometheus-client                  0.7.1
prompt-toolkit                     2.0.9
protobuf                           3.9.2
psutil                             5.6.3
py                                 1.8.0
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.3
pyflakes                           2.1.1
Pygments                           2.4.2
pylint                             2.3.1
pyodbc                             4.0.27
pyOpenSSL                          19.0.0
pyparsing                          2.4.2
pyreadline                         2.1
pyrsistent                         0.15.4
PySocks                            1.7.1
pytest                             5.1.2
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.4.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.0
pytz                               2019.2
PyWavelets                         1.0.3
pywin32                            223
pywinpty                           0.5.5
PyYAML                             5.1.2
pyzmq                              18.1.0
QtAwesome                          0.6.0
qtconsole                          4.5.5
QtPy                               1.9.0
requests                           2.22.0
rope                               0.14.0
ruamel-yaml                        0.15.46
scikit-image                       0.15.0
scikit-learn                       0.21.3
scipy                              1.3.1
seaborn                            0.9.0
Send2Trash                         1.5.0
setuptools                         41.2.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
snowballstemmer                    1.9.1
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.3
Sphinx                             2.2.0
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.1.2
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.8
statsmodels                        0.10.1
style                              1.1.0
sympy                              1.4
tables                             3.5.2
tb-nightly                         2.1.0a20190927
tblib                              1.4.0
tensorflow-estimator-2.0-preview   2.0.0
termcolor                          1.1.0
terminado                          0.8.2
testpath                           0.4.2
tf-estimator-nightly               2.0.0.dev2019092611
tf-nightly-2.0-preview             2.0.0.dev20190926
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.36.1
traitlets                          4.3.2
unicodecsv                         0.14.1
update                             0.0.1
urllib3                            1.24.2
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.16.0
wheel                              0.33.6
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.2.1
xlwings                            0.15.10
xlwt                               1.3.0
zict                               1.0.0
zipp                               0.6.0

**Comment by ouy160** [comment] 2019-10-01 00:10
> I tried executing the standard template code in colab and on my computer successfully.Thanks!
Then here is my detailed error message.


















InvalidArgumentError                      Traceback (most recent call last)
F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\context.py in execution_mode(mode)
   1733     ctx.executor = executor_new
-> 1734     yield
   1735   finally:

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2360     except _core._NotOkStatusException as e:
-> 2361       _ops.raise_from_not_ok_status(e, name)
   2362   # Add nodes to the TensorFlow graph.

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6612   # pylint: disable=protected-access
-> 6613   six.raise_from(core._status_to_exception(e.code, message), None)
   6614   # pylint: enable=protected-access

F:\path\python\anaconda\envs\py37\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]]
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors. [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-23-f421ee3a3c47> in <module>
----> 1 for image, label in labeled_ds.take(1):
      2   print("Image shape: ", image.numpy().shape)
      3   print("Label: ", label.numpy())

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    655         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    656       except AttributeError:
--> 657         return structure.from_compatible_tensor_list(self._element_spec, ret)
    658 
    659   @property

F:\path\python\anaconda\envs\py37\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\context.py in execution_mode(mode)
   1735   finally:
   1736     ctx.executor = executor_old
-> 1737     executor_new.wait()
   1738 
   1739 

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]]
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.

**Comment by ouy160** [comment] 2019-10-01 00:14
> I tried executing the standard template code in colab and on my computer successfully.Thanks!

Then this is my detailed error message.


InvalidArgumentError                      Traceback (most recent call last)
F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\context.py in execution_mode(mode)
   1733     ctx.executor = executor_new
-> 1734     yield
   1735   finally:

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2360     except _core._NotOkStatusException as e:
-> 2361       _ops.raise_from_not_ok_status(e, name)
   2362   # Add nodes to the TensorFlow graph.

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6612   # pylint: disable=protected-access
-> 6613   six.raise_from(core._status_to_exception(e.code, message), None)
   6614   # pylint: enable=protected-access

F:\path\python\anaconda\envs\py37\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]]
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors. [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-23-f421ee3a3c47> in <module>
----> 1 for image, label in labeled_ds.take(1):
      2   print("Image shape: ", image.numpy().shape)
      3   print("Label: ", label.numpy())

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py in _next_internal(self)
    655         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    656       except AttributeError:
--> 657         return structure.from_compatible_tensor_list(self._element_spec, ret)
    658 
    659   @property

F:\path\python\anaconda\envs\py37\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\context.py in execution_mode(mode)
   1735   finally:
   1736     ctx.executor = executor_old
-> 1737     executor_new.wait()
   1738 
   1739 

F:\path\python\anaconda\envs\py37\lib\site-packages\tensorflow_core\python\eager\executor.py in wait(self)
     65   def wait(self):
     66     """Waits for ops dispatched in this executor to finish."""
---> 67     pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     68 
     69   def clear_error(self):

InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]]
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.

**Comment by ouy160** [comment] 2019-10-01 01:19
> 我尝试在colab和我的计算机上成功执行标准模板代码。谢谢！

Running this code with python 3.6.8 also gets the same error

**Comment by ymodak** [comment] 2019-10-01 20:49
I tried to reproduce the error reported however I was unsuccessful. In the due process I compared the pip versions from your session and my colab runtime sessions.
I see that colab is using ```pathlib==1.0.1``` whereas you are on ```pathlib2``` module.
Here's a [gist](https://colab.sandbox.google.com/gist/ymodak/4dfbf118f49f7ad101ad25cf80d39b60/images.ipynb#scrollTo=mgeiPZkM8_4g) of my colab attempt using which I was able to execute the script successfully.

**Comment by ouy160** [comment] 2019-10-02 04:28
> 我试图重现所报告的错误，但未成功。在适当的过程中，我比较了您的会话和colab运行时会话中的pip版本。
> 我看到colab正在使用，`pathlib==1.0.1`而您正在使用`pathlib2`模块。
> 我还升级了Pillow以使其适合您的版本（6.1.0）。
> 这是我colab尝试的[要点](https://colab.sandbox.google.com/gist/ymodak/4dfbf118f49f7ad101ad25cf80d39b60/images.ipynb#scrollTo=mgeiPZkM8_4g)，通过该尝试我能够成功执行脚本。


> I tried to reproduce the error reported however I was unsuccessful. In the due process I compared the pip versions from your session and my colab runtime sessions.
> I see that colab is using `pathlib==1.0.1` whereas you are on `pathlib2` module.
> I have also upgraded Pillow to match your version (6.1.0)
> Here's a [gist](https://colab.sandbox.google.com/gist/ymodak/4dfbf118f49f7ad101ad25cf80d39b60/images.ipynb#scrollTo=mgeiPZkM8_4g) of my colab attempt using which I was able to execute the script successfully.

I am sorry, your code failed to run on my computer.And got the same error message.
Colab uses the linux version of python and successfully runs this code.
And I am using the win10 version of python, running this code and getting the same error.

**Comment by gowthamkpr** [comment] 2019-10-17 17:05
Please switch to 2.0.0 final release as there were bug fixes between the rc and the final release.

**Comment by ouy160** [comment] 2019-10-21 05:00
> Please switch to 2.0.0 final release as there were bug fixes between the rc and the final release.

It still returns the same error message.

InvalidArgumentError: {{function_node __inference_Dataset_map_process_path_117}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync]

**Comment by arielkempf** [comment] 2019-10-23 19:34
I am having the same problem running the tutorial on Win10, Python 3.6.5, tensorflow==2.0.0, tensorflow-estimator==2.0.1, tensorflow-gpu==2.0.0, tensorboard==2.0.0.
I don't have pathlib installed.

**Comment by gowthamkpr** [comment] 2019-10-23 19:50
@ouy160 @arielkempf Will try to reproduce the issue in windows and will get back to you

**Comment by pjo74** [comment] 2019-10-24 12:12
I was facing the same issue and after pulling my hairs out I FOUND THE ANSWER.
The tf tutorials sometimes use some code that only works with Unix-like paths (using /)

A quick windows fix, replace in the tuturial code
`parts = tf.strings.split(file_path, '/')
`
with
`parts = tf.strings.split(file_path, '\\')
`
And it works.

And the below fix should work **on both** unix and windows:
`import os`
`...`
`parts = tf.strings.split(file_path, os.path.sep)`



The original slice index error message was coming afterwards from the`parts[-2]` that fails because of the split results that was only of dim 0 (no / separator was found).

I recommend tf to fix the tutorial so they work on both unix and windows, perhaps the way I suggested.

**Comment by pjo74** [comment] 2019-10-24 12:43
I am preparing a pull request to fixt it

**Comment by ouy160** [comment] 2019-11-03 13:01
> I have submitted a pull request to fix the tutorial.
> In the meantime you can go ahead by applying the above change in your local code.
> Please note this is not a bug of the tensorflow library, but an issue with the tutorial itself.

wow,thank you so much. O(∩_∩)O

**Comment by marireeves** [comment] 2019-11-04 23:24
For the record, I tried both of these in Win 10, and only the windows specific solution worked. 
So, this worked: 
A quick windows fix, replace in the tutorial code
parts = tf.strings.split(file_path, '/')
with
parts = tf.strings.split(file_path, '\\')



BUT this did not...
And the below fix should work on both unix and windows:
import os
...
parts = tf.strings.split(file_path, os.path.sep)

**Comment by pjo74** [comment] 2019-11-05 00:16
This is quite strange, I suspect an error on your local code.
Try this dummy python code: it should really work on windows!
(I also have windows 10)
```

import os
import tensorflow as tf

print('Is it Backslash?', '\\' == os.path.sep)  # should be True on Windows
file_path = r'C:\some\dummmy\path\parent_folder\file.txt'
parts = tf.strings.split(file_path, os.path.sep)
print(parts)
print(parts[-1]) # the file
print(parts[-2]) # the parent folder
```
And that should print on Windows as

> Is it Backslash? True
> tf.Tensor([b'C:' b'some' b'dummmy' b'path' b'parent_folder' b'file.txt'], shape=(6,), dtype=string)
> tf.Tensor(b'file.txt', shape=(), dtype=string)
> tf.Tensor(b'parent_folder', shape=(), dtype=string)

**Comment by marireeves** [comment] 2019-11-06 20:15
You're right, the dummy code runs with the following output. I'll take another look at that tutorial code:

Is it Backslash? True
tf.Tensor([b'C:' b'some' b'dummmy' b'path' b'parent_folder' b'file.txt'], shape=(6,), dtype=string)
tf.Tensor(b'file.txt', shape=(), dtype=string)
tf.Tensor(b'parent_folder', shape=(), dtype=string)

**Comment by marireeves** [comment] 2019-11-06 21:32
It works both ways if you don't leave out the import os statement... thanks!

**Comment by jaingaurav** [comment] 2019-11-13 17:49
@ouy160: With the fixed tutorial is there any further action needed for this issue or should we close it?

**Closed** 2019-11-22 09:25 UTC
Labels: TF 2.0, comp:ops, stat:awaiting response, type:bug
