### ISSUE TITLE
Model cannot be saved because the input shapes have not been set.

### ISSUE THREAD

**Issue by menon92** [tensorflow/tensorflow#39906] opened 2020-05-27 14:14 UTC
Hello, I'm following [save_and_serialize subclass model](https://www.tensorflow.org/guide/keras/save_and_serialize#whole-model_saving_loading) . When I run the following code,
```python
class CustomModel(tf.keras.Model):
    def __init__(self, hidden_units):
        super(CustomModel, self).__init__()
        self.dense_layers = [
            tf.keras.layers.Dense(u) for u in hidden_units]
    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

model = CustomModel([16, 16, 10])
# Build the model by calling it
input_arr = tf.random.uniform((1, 5))
outputs=model(input_arr)
model.save('my_custom_model')
```
I get the this error, `ValueError: Model <__main__.CustomModel object at 0x7f96797a2c10> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs).`

But when I change code as following, 
```python
model = CustomModel([16, 16, 10])
input_arr = tf.random.uniform((1, 5))
outputs = model(input_arr)
model._set_inputs(input_arr) # add this line
model.save('my_custom_model')
```
It runs without any error. What could be the possible cause. Do I need to add `model._set_inputs(input_arr) ` explicitly ?

I'm using, 
`Ubuntu 20.04 LTS`
`conda environment`
`TensorFlow 2.1.1 `

Thanks

**Comment by Saduf2019** [comment] 2020-05-27 14:38
@menon92 
I ran the code shared by you and do not face any errors, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/7ea93b577b7c605b3656251f739bc09b/untitled200.ipynb)

**Comment by menon92** [comment] 2020-05-30 12:23
@Saduf2019 I try the same code in `pip` version of tensorflow and it works without any issue. 
I think there is an issue in `conda` version of tensorflow

**Comment by gowthamkpr** [comment] 2020-06-03 19:27
@menon92 Are you sure there is an issue with conda version of tensorflow . I am not running into any error. Thanks!

**Comment by menon92** [comment] 2020-06-04 13:43
```bash
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import tensorflow as tf                                                                                   

In [2]: tf.__version__                                                                                            
Out[2]: '2.1.0'

In [3]: class CustomModel(tf.keras.Model): 
   ...:     def __init__(self, hidden_units): 
   ...:         super(CustomModel, self).__init__() 
   ...:         self.dense_layers = [ 
   ...:             tf.keras.layers.Dense(u) for u in hidden_units] 
   ...:     def call(self, inputs): 
   ...:         x = inputs 
   ...:         for layer in self.dense_layers: 
   ...:             x = layer(x) 
   ...:         return x 
   ...:  
   ...: model = CustomModel([16, 16, 10]) 
   ...: # Build the model by calling it 
   ...: input_arr = tf.random.uniform((1, 5)) 
   ...: outputs=model(input_arr) 
   ...: model.save('my_custom_model')                                                                             
2020-06-04 19:38:19.299584: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2020-06-04 19:38:19.590094: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294900000 Hz
2020-06-04 19:38:19.601769: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5579ab0470d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-04 19:38:19.601891: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-04 19:38:19.647392: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:Skipping full serialization of Keras model <__main__.CustomModel object at 0x7f911b73cc10>, because its inputs are not defined.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ae79cf94cb11> in <module>
     14 input_arr = tf.random.uniform((1, 5))
     15 outputs=model(input_arr)
---> 16 model.save('my_custom_model')

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1006     """
   1007     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1008                     signatures, options)
   1009 
   1010   def save_weights(self, filepath, overwrite=True, save_format=None):

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,
--> 115                           signatures, options)
    116 
    117 

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py in save(model, filepath, overwrite, include_optimizer, signatures, options)
     63 
     64   if save_impl.should_skip_serialization(model):
---> 65     saving_utils.raise_model_input_error(model)
     66 
     67   if not include_optimizer:

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saving_utils.py in raise_model_input_error(model)
    111       'set. Usually, input shapes are automatically determined from calling'
    112       ' .fit() or .predict(). To manually set the shapes, call '
--> 113       'model._set_inputs(inputs).'.format(model))
    114 
    115 

ValueError: Model <__main__.CustomModel object at 0x7f911b73cc10> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call model._set_inputs(inputs)
```

**Comment by gowthamkpr** [comment] 2020-06-08 10:18
@menon92 Yes this bug exists in 2.1.0 but has been fixed in tensorflow 2.2.0. 
![image](https://user-images.githubusercontent.com/47574994/84019847-b6e4d680-a936-11ea-9a8e-e7946635f967.png)

**Closed by gowthamkpr** 2020-06-08 10:18 UTC
Labels: TF 2.1, comp:keras, type:bug

**Comment by cmichelenstrofer** [comment] 2020-09-23 16:19
Bug seems to be back in 2.3

**Comment by sschaffer92** [comment] 2020-09-24 12:38
I am facing the same problem in 2.3.

**Comment by cmichelenstrofer** [comment] 2020-09-24 14:21
My bad, the problem is not with 2.3, it is when trying to save a subclassed model.

**Comment by iyerkrithika21** [comment] 2020-10-09 23:43
I am also facing the same problem in 2.3.

**Comment by boogalooYison** [comment] 2020-12-24 10:38
I am also facing the same problem in 2.3. And I used "model.compute_output_shape(input_shape=(None, 1080,1920,3))",can also solve this problem when saving  a subclassed model. But why does it work?

**Comment by lmielke** [comment] 2021-02-16 12:24
I am facing the same issue in 2.4.0, with jupyter lab python 3.8. 
For testing i downloaded the notebook from https://www.tensorflow.org/tutorials/generative/cvae
Both, tf.keras.models.save_model(model, path) and model.save(path) return the same ValueError
Is there any workarround?

**Comment by shixm-cloud** [comment] 2021-03-11 01:10
I ran into the same issue as @lmielke. If I used a different VAE example, I could save the model. However, using the example from https://www.tensorflow.org/tutorials/generative/cvae just does not work. The code there is really nice. 

It would be very nice if an updated version of TensorFlow can solve the issue.

**Comment by kennysong** [comment] 2021-06-08 13:01
@lmielke @shixm-cloud Did you find a workaround to save the CVAE model?

**Comment by menon92** [comment] 2021-06-08 16:51
@kennysong, I try this
```python
(base) menon@menon:~$ ipython
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help

In [18]: import tensorflow as tf

In [19]: tf.__version__
Out[19]: '2.4.1'

In [20]: class CustomModel(tf.keras.Model):
    ...:     def __init__(self, hidden_units):
    ...:         super(CustomModel, self).__init__()
    ...:         self.dense_layers = [
    ...:             tf.keras.layers.Dense(u) for u in hidden_units]
    ...:     def call(self, inputs):
    ...:         x = inputs
    ...:         for layer in self.dense_layers:
    ...:             x = layer(x)
    ...:         return x
    ...: 

In [21]: model = CustomModel([16, 16, 10])
    ...: # Build the model by calling it
    ...: input_arr = tf.random.uniform((1, 5))
    ...: outputs = model(input_arr)
    ...: model.save('my_custom_model')
INFO:tensorflow:Assets written to: my_custom_model/assets

In [22]: ls my_custom_model
assets/  saved_model.pb  variables/

In [23]:
```
And it runs without  any issue

**Comment by kennysong** [comment] 2021-06-09 06:32
@menon92 Thanks! That works for basic examples, but not for [the CVAE model in the TF documentation](https://www.tensorflow.org/tutorials/generative/cvae).

I figured out how to save the CVAE by replacing this line:
```python
eps = tf.random.normal(shape=mean.shape)
```
with:
```python
eps = tf.random.normal(shape=tf.shape(mean))
```

And adding the `@tf.function` decorator to all of CVAE's methods so they are reconstructed when loading from disk.

**Comment by fperezgamonal** [comment] 2021-09-08 10:24
Hi all!
Thanks @boogalooYison , your solution worked with TensorFlow 2.6.0 👍  . About the reason why it works, I can only say that the input shape is set in the call to `model.compute_output_shape(input_shape)`, as it is required to compute the actual output shape.

In my opinion, this is a cleaner and more elegant solution than having to call the network with dummy input data.

Cheers!

**Comment by yunruili** [comment] 2021-12-22 05:21
> Are you satisfied with the resolution of your issue? [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/39906) [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/39906)

no

**Comment by MINDLAB1** [comment] 2022-02-28 19:01
Hi all, couldn`t save model after training this model, any help please

`
import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras import Model

from ssim2dmodule import similarityattention2d
from attention_module import SSCblockaddall, SSCblocksam1dlast, SSCblocksamlast, SSCblockcamlast, SSCblockparallel, SSCblockRandom



#act_fn3 = tf.keras.activations.tanh() #tf.ReLU()

class encode_block(tf.keras.layers.Layer):
    def __init__(self, filter_num, BatchNorm2d=True):
        super(encode_block, self).__init__()
        
        self.init = tf.keras.initializers.RandomNormal(stddev=0.02)
        self.act_fn =tf.keras.layers.LeakyReLU(0.2)
       

        self.conv = tf.keras.layers.Conv2D(filter_num, kernel_size=4, 
                                    strides=2, padding='same', kernel_initializer=self.init)
        
        self.BatchNorm2d =None
        if BatchNorm2d:
            self.BatchNorm2d = tf.keras.layers.BatchNormalization()
        
        
    def call(self,x):
        x = self.conv(x)
        
        if self.BatchNorm2d != None:
            x = self.BatchNorm2d(x, training=True)
            
        x = self.act_fn(x)
        
        return x
       
class decode_block(tf.keras.layers.Layer):
    def __init__(self, filter_num, dropout2d=True):
        super(decode_block, self).__init__()
        
        self.init = tf.keras.initializers.RandomNormal(stddev=0.02)
        self.act_fn =tf.keras.layers.ReLU(0.2)
        self.concat = tf.keras.layers.Concatenate()
        self.BatchNorm2d = tf.keras.layers.BatchNormalization()
       

        self.conv = tf.keras.layers.Conv2DTranspose(filter_num, kernel_size=4, 
                                    strides=2, padding='same', kernel_initializer=self.init)
        
        self.dropout2d = None
        if dropout2d:
            self.dropout2d = tf.keras.layers.Dropout(0.5)
        
        
    def call(self,x,concat_in):
        x = self.concat([x, concat_in])
        x = self.conv(x)
        x = self.BatchNorm2d(x, training=True)
        
        if self.dropout2d != None:
            x = self.dropout2d(x, training=True)
        
        x = self.act_fn(x)
        
        return x
    

class bottleneck(tf.keras.layers.Layer):
    def __init__(self, filter_num):
        super(bottleneck, self).__init__()
        
        self.init = tf.keras.initializers.RandomNormal(stddev=0.02)
        self.act_fn =tf.keras.layers.ReLU(0.2)
       
        self.conv = tf.keras.layers.Conv2D(filter_num, kernel_size=4, 
                                    strides=2, padding='same', kernel_initializer=self.init)
        
        self.dconv = tf.keras.layers.Conv2DTranspose(filter_num, kernel_size=4, 
                                    strides=2, padding='same', kernel_initializer=self.init)

        
        
    def call(self,x):
        x = self.conv(x)
            
        x = self.act_fn(x)
        
        x = self.dconv(x)
        
        x = self.act_fn(x)
        
        return x
    

class final_layer(tf.keras.layers.Layer):
    def __init__(self):
        super(final_layer, self).__init__()
        
        self.init = tf.keras.initializers.RandomNormal(stddev=0.02)
        self.concat = tf.keras.layers.Concatenate()
        self.conv = tf.keras.layers.Conv2DTranspose(3, kernel_size=4, 
                                    strides=2, padding='same', kernel_initializer=self.init)
        
        
    def call(self,x, concat_in):
        x = self.concat([x, concat_in])
        x = self.conv(x)
        
        x = tf.keras.activations.tanh(x)
        
        return x
        


class MixedFusion_Block0(tf.keras.layers.Layer):
    
    def __init__(self, inputs1, inputs2, filter_num):
        super(MixedFusion_Block0, self).__init__()

        self.input1 = inputs1
        self.input2 = inputs2
        self.filter_num  = filter_num

        self.ssim2d = similarityattention2d(inputs1, inputs2)
        self.encode = encode_block(filter_num, BatchNorm2d=False)

    def call(self, x1, x2):
        
        # multi-style fusion
        ssim2d_out = self.ssim2d(x1,x2)
        encode_out =  self.encode(ssim2d_out)
        print(encode_out.shape)
        if not encode_out.get_shape()[1:] == (self.filter_num*2, self.filter_num*2, self.filter_num):
            encode_out = tf.keras.layers.Reshape((self.filter_num*2, self.filter_num*2, self.filter_num))(encode_out) #(tf.squeeze(encode_out, axis=[0]))
        
        return encode_out

class MixedFusion_Block1(tf.keras.layers.Layer):
    
    def __init__(self, x, filter_num): #SSCblockaddall, SSCblocksam1dlast, SSCblocksamlast, SSCblockcamlast, SSCblockparallel, SSCblockRandom
        super(MixedFusion_Block1, self).__init__()

        self.filter_num  = filter_num
        self.block_name = SSCblockaddall()
        self.encode = encode_block(filter_num)
        

    def call(self, x1, x2, x3):
        
        y1 = self.block_name(x1) 
        y2 = self.block_name(x2)
        y = tf.concat([y1, y2, x3], 3)
        
        
        encode_out = self.encode(y)
        print(encode_out.shape)

        return encode_out



class generator(Model):

    def __init__(self, input_nc, layer_out, filter_num):
        super(generator,self).__init__()
        
        self.filters = filter_num
        self.in_dim = input_nc
        self.layer_out = layer_out

            # ~~~ Encoding Paths ~~~~~~ #
        # Encoder (Modality 1)
        
        #######################################################################
        # Encoder **Modality 1
        #######################################################################

        self.encode_1_0 = encode_block(self.filters*1, BatchNorm2d=False)

        self.encode_2_0 = encode_block(self.filters*2)

        self.encode_3_0 = encode_block(self.filters*4)

        self.encode_4_0 = encode_block(self.filters*8)

        self.encode_5_0 = encode_block(self.filters*8)

        self.encode_6_0 = encode_block(self.filters*8)

        self.encode_7_0 = encode_block(self.filters*8)
        
        #self.encode_8_0 = encode_block(self.filters*8)
        
        #######################################################################
        # Encoder **Modality 2
        #######################################################################

        self.encode_1_1 = encode_block(self.filters, BatchNorm2d=False)

        self.encode_2_1 = encode_block(self.filters*2)

        self.encode_3_1 = encode_block(self.filters*4)

        self.encode_4_1 = encode_block(self.filters*8)

        self.encode_5_1 = encode_block(self.filters*8)

        self.encode_6_1 = encode_block(self.filters*8)

        self.encode_7_1 = encode_block(self.filters*8)
        
        #self.encode_8_1 = encode_block(self.filters*8)
         
        #######################################################################
        # fusion block
        #######################################################################
        # --- fusion encoder
        self.fu_encoder_1 = MixedFusion_Block0(self.in_dim, self.in_dim, self.filters)
          
        self.fu_encoder_2 = MixedFusion_Block1(self.layer_out, self.filters*2)
        
        self.fu_encoder_3 = MixedFusion_Block1(self.layer_out*2, self.filters*4)

        self.fu_encoder_4 = MixedFusion_Block1(self.layer_out*4, self.filters*8)

        self.fu_encoder_5 = MixedFusion_Block1(self.layer_out*8, self.filters*8)

        self.fu_encoder_6 = MixedFusion_Block1(self.layer_out*8, self.filters*8)

        self.fu_encoder_7 = MixedFusion_Block1(self.layer_out*8, self.filters*8)
        
        #self.fu_encoder_8 = MixedFusion_Block1(self.layer_out*8, self.filters*8)
        
        # bottleneck layer
        self.bottleneck = bottleneck(self.filters*8)
     
        # ~~~ Decoding Path ~~~~~~ #
     
        self.decod_1_0 = decode_block(self.filters*8)
        self.decod_2_0 = decode_block(self.filters*8)
        self.decod_3_0 = decode_block(self.filters*8)
        self.decod_4_0 = decode_block(self.filters*4, dropout2d=False)  
        self.decod_5_0 = decode_block(self.filters*2, dropout2d=False)
        self.decod_6_0 = decode_block(self.filters*1, dropout2d=False)
        
        
        self.out        = final_layer()

    
                
    def call(self,x,y):

        # ##############################
        image_shape=(256,256,3)
        x = tf.keras.Input(image_shape)
        y = tf.keras.Input(image_shape)
        z = (x*y)
        
        # -----  First Level -------- 
        encoder_1_0 = self.encode_1_0(x) #(256, 256, input_size[-1])
        encoder_1_1 = self.encode_1_1(y) 


        # -----  Second Level --------
        
        encoder_2_0 = self.encode_2_0(encoder_1_0) # (128, 128, 64)
        encoder_2_1 = self.encode_2_1(encoder_1_1)
        
        
        # -----  Third Level --------
                
        encoder_3_0 = self.encode_3_0(encoder_2_0) # (64, 64, 128)
        encoder_3_1 = self.encode_3_1(encoder_2_1)

         # -----  Fourth Level --------
                
        encoder_4_0 = self.encode_4_0(encoder_3_0) # (32, 32, 256)
        encoder_4_1 = self.encode_4_1(encoder_3_1)

         # -----  Five Level --------
                
        encoder_5_0 = self.encode_5_0(encoder_4_0) # (16, 16, 512)
        encoder_5_1 = self.encode_5_1(encoder_4_1)

        # -----  sixth Level --------
                
        encoder_6_0 = self.encode_6_0(encoder_5_0) # (8, 8, 512)
        encoder_6_1 = self.encode_6_1(encoder_5_1)

        # -----  seventh Level --------
                
        encoder_7_0 = self.encode_7_0(encoder_6_0) # (4, 4, 512)
        encoder_7_1 = self.encode_7_1(encoder_6_1)
        
         
        # ----------------------------------------
        # fusion block -- f_block
        f_block_1   = self.encode_1_0(z) #self.fu_encoder_1(x,y) 
        
        f_block_2  = self.fu_encoder_2(encoder_1_0, encoder_1_1, f_block_1)
        
        f_block_3   = self.fu_encoder_3(encoder_2_0, encoder_2_1, f_block_2) 

        f_block_4  = self.fu_encoder_4(encoder_3_0, encoder_3_1, f_block_3)

        f_block_5  = self.fu_encoder_5(encoder_4_0, encoder_4_1, f_block_4)

        f_block_6  = self.fu_encoder_6(encoder_5_0, encoder_5_1, f_block_5)

        f_block_7  = self.fu_encoder_7(encoder_6_0, encoder_6_1, f_block_6)

        #f_block_8  = self.fu_encoder_8(encoder_7_0, encoder_7_1, f_block_7)
        
        #f_block_9  = self.fu_encoder_9(encoder_8_0, encoder_8_1, f_block_8)
        


        ####################################################################### 
        # ~~~~~~ Bottleneck
        btlnck = self.bottleneck(f_block_7)     # (1 x 1 x 512) and # (2 x 2 x 512)
        print(btlnck.shape)

        #######################################################################                                                                                                
        # ~~~~~~ Decoding 
        decoder_1_0 =  self.decod_1_0 (btlnck,f_block_7)  # (4, 4, 512)
        decoder_2_0 = self.decod_2_0(decoder_1_0,f_block_6)  # (8, 8, 512)
        decoder_3_0 = self.decod_3_0(decoder_2_0,f_block_5)  # (16, 16, 512)
        decoder_4_0 = self.decod_4_0(decoder_3_0,f_block_4)  # (32, 32, 256)
        decoder_5_0 = self.decod_5_0(decoder_4_0,f_block_3)  # (64, 64, 128)
        decoder_6_0 = self.decod_6_0(decoder_5_0,f_block_2)   # (128, 128, 64)
        
        
        decod_out     = self.out(decoder_6_0, f_block_1) # (256, 256, output_channels)
        
       
        # get three channels
        
        
                        
        return decod_out

class adversary(Model):

    def __init__(self,filter_num):
        super(adversary,self).__init__()
        
        self.filters = filter_num
        
        self.init = tf.keras.initializers.RandomNormal(stddev=0.02)
        self.last = tf.keras.layers.Conv2D(1, (4,4), padding='same', kernel_initializer = self.init, 
                                            activation=tf.keras.activations.sigmoid)

        self.conv_1 = encode_block(self.filters*1)

        self.conv_2 = encode_block(self.filters*2)

        self.conv_3 = encode_block(self.filters*4)

        self.conv_4 = encode_block(self.filters*8)

        self.conv_5 = encode_block(self.filters*8)

        self.conv_6 = encode_block(self.filters*8)


    def call(self,x,y):

        x = tf.keras.Input(x.shape[1:])
        y = tf.keras.Input(y.shape[1:])

        adv_1 = tf.keras.layers.concatenate([x, y]) # (256, 256, real_channels+fake_channels)

        adv_2 = self.conv_1(adv_1)                  # (128, 128,  64)
        
        adv_3 = self.conv_2(adv_2)                  # (64,  64, 128)
        
        adv_4 = self.conv_3(adv_3)                  # (32,  32, 256)
        
        adv_5 = self.conv_4(adv_4)                  # (16, 16, 512)
        
        adv_6 = self.conv_5(adv_5)                  #(8, 8, 512)
        
        adv_7 = self.conv_6(adv_6)                  #(4, 4, 512)
        
        adv_8 = self.last(adv_7)                    #(4, 4, 1)
        
        return adv_8
`

**Comment by Thijsvandepoll** [comment] 2022-03-22 20:32
Hi all,

I recently came across a similar problem where I had 2 models. One text encoder, and one classification head. I needed to implement some custom logic inside the `train_step`. The subclassed model looked as follows:

```
class TestModel(keras.Model):
    
    def __init__(self, first, second, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.first = first
        self.second = second
        
    def call(self, inputs):
        return self.second(self.first(inputs))
        
    def train_step(self, data):
        # Here some custom logic requiring both first and second model
        pass
```


When calling `model.save()` on the instance, it cannot save the model because of the `ValueError` described above. One can only save the model if you have made a forward pass on the model. I was using `KerasTuner` for hyperparameter tuning and noticed that it does not return a correctly built model. So one solution was to pass some data through the model to make it save. That worked but I didn't like it. Then I came across the following solution:


```
class TestModel(keras.Model):
    
    def __init__(self, first, second, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.first = first
        self.second = second
        
        self._set_inputs(inputs=self.first.inputs, outputs=self(self.first.inputs))
        
    def call(self, inputs):
        return self.second(self.first(inputs))

    def train_step(self, data):
        # Here some custom logic requiring both first and second model
        pass
```

This basically allows you to lazily specify the `inputs` and `outputs` as normal. So far it works properly. I hope this might help others out as well.

**Comment by florianwirth** [comment] 2022-10-19 09:31
Hi, I am building a GNN with several inputs of variable size and here, neither @Thijsvandepoll 's nor @boogalooYison 's proposal worked for me. 

My solution is specifying TensorSpecs in the `@tf.function` decorator according to [this paragraph of the tf docu](https://www.tensorflow.org/guide/saved_model#saving_a_custom_model):

```
import keras.layers
import tensorflow as tf
import unittest

class TestModel(keras.Model):
    def __init__(self):
        super(TestModel, self).__init__()
        self.w = tf.Variable(initial_value=tf.initializers.he_normal()(shape=[10, 10]))

    @tf.function(input_signature=[tf.TensorSpec([10, None], tf.float32), tf.TensorSpec([10, None], tf.float32)])  # This line defines the inputs' sizes of the network call
    def __call__(self, x, y):
        return tf.matmul(self.w, x) + tf.matmul(self.w, y)

class SaveAndLoadTest(unittest.TestCase):
    def __init__(self):
        super(SaveAndLoadTest, self).__init__()

        x = tf.ones([10, 5])
        y = tf.ones([10, 5])

        model = TestModel()
        z = model(x, y)

        tf.saved_model.save(model, "/tmp/test_model/")  # saving a this way works
        with self.assertRaises(ValueError):
            model.save("/tmp/test_model/")  # saving a model this way fails, regardless of assigning TensorSpecs to tf.function

        model_loaded = tf.saved_model.load("/tmp/test_model/")
        z_loaded = model_loaded(x, y)

        self.assertTrue((z_loaded.numpy() == z.numpy()).all())  # making sure the outputs are the same

if __name__ == "__main__":
    SaveAndLoadTest()
    print("Success.")
```

**Comment by CassSarge** [comment] 2023-09-07 06:39
I came across this issue using version 2.11 when using someone else's model that I didn't fully understand. For anyone else in the same boat, you may not need to save the model and can avoid the issue entirely by using `save_weights_only=True` in your keras callbacks, e.g.:
```
callbacks = [
        keras.callbacks.ModelCheckpoint(
            './logs/model/weights', monitor='sparse_categorical_accuracy', save_best_only=True, save_weights_only=True)
    ]
```
and then later
```
model.fit(
        dataset_train,
        validation_data=dataset_val,
        callbacks=callbacks,
        epochs=100,
    )
```
Just consider if you need to save the model or the weights!
