### ISSUE TITLE
Adam optimizer - ValueError: tf.function-decorated function tried to create variables on non-first call

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/tensorflow#42183] opened 2020-08-10 09:21 UTC
I am using tensorflow 2.3

The code below 

    import  tensorflow as tf
    
    y_N= tf.Variable([1., 2., 3.],name="dd")
    
    @tf.function
    def loss():
        return -tf.reduce_mean(input_tensor=tf.reduce_sum(input_tensor=tf.math.log(y_N), axis=0))
    
    @tf.function
    def run():
        tf.keras.optimizers.Adam(0.5).minimize(loss, var_list=[y_N])
    
    run()

gives exception

    ValueError: tf.function-decorated function tried to create variables on non-first call.

Problem looks like `tf.keras.optimizers.Adam(0.5).minimize(loss, var_list=[y_N])` creates new variable on > first call, while using `@tf.function`. If I must wrap adam_optimizer under `@tf.function`, is it possible? looks like a bug?

**Comment by ravikyram** [comment] 2020-08-10 09:38
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200810`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b8abbdd5f974a0f189fe36cb6c34a421/untitled234.ipynb).Thanks!

**Comment by tianhuat** [comment] 2020-08-10 13:08
I found out that  after calling `minimize` function, it will create an `iter` variable, by calling `self.iterations` once. 
(This happens in `tensorflow/python/keras/optimizer_v2/optimizer_v2.py`)

Subsequent call of the `self.iterations` will not create new variable - 
as `iter` has already been created.

Therefore, by calling it earlier outside the tf.function solve the issue, here's the code that works:

    import  tensorflow as tf
    
    y_N= tf.Variable([1., 2., 3.],name="dd")
    
    @tf.function
    def loss():
        return -tf.reduce_mean(input_tensor=tf.reduce_sum(input_tensor=tf.math.log(y_N), axis=0))
    
    @tf.function
    def run(adam):
        adam.minimize(loss, var_list=[y_N])
    
    
    adam=tf.keras.optimizers.Adam(0.5)
    adam.iterations
    run(adam)

Though I think the `minimize` of Adam function could be improved so that we don't need this hack.

**Comment by nikitamaia** [comment] 2020-08-10 18:42
Hi @tianhuat, you've run into a fairly common scenario due to some slightly confusing behavior with Keras and tf.function. The [Variables section of the tf.function guide](https://www.tensorflow.org/guide/function#variables) explains the error message you've seen as guarding against behavior divergence on repeated calls. In eager mode, a function creates a new variable with each call, but with graph mode a new variable may not be created due to trace reuse. This is essentially what you've noted in your above comment, and the official suggestion is to pass in the optimizer. And for reference, you'll likely run into a similar error message if you try to create the model inside your tf.function, instead of passing it in.

I'll close this issue now as you've found a solution, and there is also an open issue around this error message (with a lot of comments if you're interested in reading more on the details) #27120

**Closed by nikitamaia** 2020-08-10 18:42 UTC
Labels: TF 2.3, comp:autograph, comp:keras, type:bug
