### ISSUE TITLE
ERROR: tensorflow

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/tensorflow#44932] opened 2020-11-17 08:54 UTC
**System information**
tf version =2.3.0-rc
System- colab-gpu

Reproduce error
`y=tf.TensorArray(tf.float32,size=1,dynamic_size=True)`
```
y.write(0,[[20,1,10]])
y.write(1,[[22,1,10]])
y.write(2,[[23,1,10]])
y.write(3,[[24,1,10]])
```

ERROR
```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f6e013e9d68>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-38-cf79ca55289e>", line 1, in <module>
    y.write(0,[[20,1,10]])  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 249, in wrapped
    error_in_function=error_in_function)
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f6e013e9d68>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-38-cf79ca55289e>", line 2, in <module>
    y.write(1,[[22,1,10]])  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 249, in wrapped
    error_in_function=error_in_function)
==================================
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
<tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f6e013e9d68>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-38-cf79ca55289e>", line 3, in <module>
    y.write(2,[[23,1,10]])  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py", line 249, in wrapped
    error_in_function=error_in_function)
==================================
<tensorflow.python.ops.tensor_array_ops.TensorArray at 0x7f6e011c99e8>
```

**Comment by ravikyram** [comment] 2020-11-17 09:34
I have tried in colab with TF version 2.2, 2.3 and nightly version(`2.5.0-dev20201116`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1d473053fe135af066190e050a90b658/untitled521.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2020-11-22 08:33
@maxkaustav,
As per the [Example of TensorArray](https://www.tensorflow.org/api_docs/python/tf/TensorArray#used-in-the-notebooks_1), it should be 

`y = y.write(0,[[20,1,10]])` instead of `y.write(0,[[20,1,10]])`

because it will not modify the Tensor in Place.

Please find the [Gist of Working Code](https://colab.research.google.com/gist/rmothukuru/f3761d531c0aa73f38b15e94959967ad/untitled521.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2020-11-28 09:47
@maxkaustav,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment] 2020-12-04 10:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mihaimaruseac** [comment] 2021-11-14 17:39
Reopening as there's a comment that this still reproduces

**Comment by mohantym** [comment] 2021-12-01 10:26
Hi @Arregator @maxkaustav ! I could not replicate this issue in 2.7 version though .Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/7272e8316d3fc5cd251487789890e340/untitled521.ipynb#scrollTo=iO67RlSsh5Pd) for reference . Thanks!

**Comment by gadagashwini** [comment] 2022-04-19 11:01
@maxkaustav,
Given code works with Tf v 2.8.0. Please take a look at [gist](https://colab.research.google.com/drive/1ZTrFDPRwmwAulu3eQfWKTYD8pon0yy95?usp=sharing). 
```
import tensorflow as tf
import numpy as np
print(tf.__version__)
images = np.array([[122_222]])
images_array = tf.TensorArray(tf.uint16, size=0, dynamic_size=True, clear_after_read=False)
images_array = images_array.write(0, images)
```

**Comment by gadagashwini** [comment] 2022-04-21 07:43
@maxkaustav,
Closing this issue, since its resolved .
Please feel free to reopen if issue still persists. Thanks!

**Closed by gadagashwini** 2022-04-21 07:43 UTC
Labels: stat:awaiting response, type:support, comp:ops, TF 2.3, TF 2.7
