### ISSUE TITLE
Fail to build tensorflow pip - "...external" failed: No such file or directory 

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#2751] opened 2016-06-09 06:11 UTC
I'm using bazel 0.2.3 as well, Ubuntu 16.04 + GCC 5.3.1, Cuda 7.5 + cudnn 5.0.5 .
I strictly followed https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#installation-for-linux, but run into the same error 

> $ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
> Wed Jun 8 17:48:44 PDT 2016 : === Using tmpdir: /tmp/tmp.67PiK9GeAe
> rsync: change_dir "/home/jiapei/Downloads/machinelearning/deeplearning/tensorflow//bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external" failed: No such file or directory (2)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

I noticed that I do **NOT** have the subfolder **external**, but only a folder **org_tensorflow**. In addition, I do **NOT** have a folder __main__ .

> .../pip_package/build_pip_package.runfiles$ ls 
> d3                             iron_collapse               iron_range_behavior        paper_dropdown_menu  paper_styles
> dagre                          iron_dropdown               iron_resizable_behavior    paper_header_panel   paper_tabs
> eigen_archive                  iron_fit_behavior           iron_selector              paper_icon_button    paper_toggle_button
> es6_promise                    iron_flex_layout            iron_validatable_behavior  paper_input          paper_toolbar
> font_roboto                    iron_form_element_behavior  lodash                     paper_item           plottable
> graphlib                       iron_icon                   MANIFEST                   paper_material       polymer
> __init__.py                    iron_icons                  neon_animation             paper_menu           promise_polyfill
> iron_a11y_announcer            iron_iconset_svg            org_tensorflow             paper_menu_button    protobuf
> iron_a11y_keys_behavior        iron_input                  paper_behaviors            paper_progress       six_archive
> iron_ajax                      iron_list                   paper_button               paper_radio_button   web_animations_js
> iron_autogrow_textarea         iron_menu_behavior          paper_checkbox             paper_radio_group    webcomponentsjs
> iron_behaviors                 iron_meta                   paper_dialog               paper_ripple
> iron_checked_element_behavior  iron_overlay_behavior       paper_dialog_behavior      paper_slider

Can anybody help please?

Cheers
Pei

**Comment by girving** [comment] 2016-06-09 16:26
@martinwicke This seems like a Bazel issue.  Have you seen it before?

**Comment by vrv** [comment] 2016-06-10 06:12
also pinging @damienmg and @kchodorow  (did something change in bazel 0.2.3?)

**Comment by damienmg** [comment] 2016-06-10 07:44
It should have an external folder. This is not 0.2.3, what does `bazel version` says? By the way this should be fixed @HEAD also (an in 0.3.0rc2)

**Comment by jiapei100** [comment] 2016-06-10 07:49
@damienmg 

I installed a bazel-0.2.3 release, and then rebuild bazel-git, and overwrite the installed bazel with my output/bazel.

```
jiapei@jiapei-GT72-6QE:~$ bazel version
Build label: 0.2.3-2016-06-08 (@caa000a)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 8 23:20:40 2016 (1465428040)
Build timestamp: 1465428040
Build timestamp as int: 1465428040
```

So, do you mean, if I checkout 0.3.0rc2 now, bazel will successfully build through tensorflow?


cheers

**Comment by damienmg** [comment] 2016-06-10 08:08
Yes either check out 0.2.3 tag or pull the new head (or the 0.3.0-release branch).

We rolled back a change that introduced since 0.2.3 for 0.3.0 because of those kind of symptoms.

**Comment by jiapei100** [comment] 2016-06-10 08:11
@damienmg 
What if the current bazel-git? Will that work as well???
You don't have a 0.3.0 release here yet ~ [https://github.com/bazelbuild/bazel/releases]

**Comment by damienmg** [comment] 2016-06-10 08:16
Yes it will work as well, we did the rollback yesterday.

Our release candidates are on GCS:  https://storage.googleapis.com/bazel/0.3.0/rc2/index.html

**Comment by jiapei100** [comment] 2016-06-10 08:26
@damienmg 

I just have bazel-git built, and it seems only one single file is produced:
`Build successful! Binary is here: ... /bazel/output/bazel`

However, if I install bazel from the release [https://github.com/bazelbuild/bazel/releases](url)
I will get three files under  /usr/local/lib/bazel/bin
```
jiapei@jiapei-GT72-6QE:/usr/local/lib/bazel/bin$ ls
bazel  bazel-complete.bash  bazel-real
```

So, I guess bazel-complete.bash and bazel-real don't matter at all ?? I can just copy the built-from-source .../output/bazel under /usr/local/lib/bazel/bin directly?
That's it???? That's all???

**Comment by damienmg** [comment] 2016-06-10 08:41
output/bazel to /usr/local/lib/bazel/bin/bazel-real (you can replace bazel too won't matter much, but the actual binary is bazel-real).

**Comment by jiapei100** [comment] 2016-06-10 09:17
@damienmg 
Great... It builds... Thank you ...

**Comment by damienmg** [comment] 2016-06-10 09:22
@girving: is there a bazel test we could run to test those regression on ci.bazel.io?

I am adding building the build_pip_package script but that might not be enough since it failed at run time.

**Comment by samfux84** [comment] 2016-06-10 13:49
Is it possible to build the tensorflow pip wheel with the following version of bazel ?

[sfux@develop01 ~]$ bazel version
..
Build label: 0.2.3- (@non-git)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 6 08:27:55 2016 (1465201675)
Build timestamp: 1465201675
Build timestamp as int: 1465201675
[sfux@develop01 ~]$

**Comment by samfux84** [comment] 2016-06-10 13:50
I have this version and encountered the problem with the missing "external" directory.

**Comment by martinwicke** [comment] 2016-06-10 15:17
@damienmg could we have a sh_test that simply runs build_pip_package? That
should have caught this one at least, right?

**Comment by damienmg** [comment] 2016-06-10 15:32
Yes this is possible,

By the way, `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles` is a bit weird, we generally use `$PYTHON_RUNFILES` if it exisrts or `$0.runfiles` instead. Every other file should be included as inputs of the target. Seeing the build_pip_package.sh script I actually wonder why it is not a build step for bazel?

**Comment by martinwicke** [comment] 2016-06-10 15:57
Good question. What's the easiest way to do that?

**Comment by damienmg** [comment] 2016-06-10 16:07
Having a genrule that call the build_pip_package script should be enough. Some adaptation will be needed from the pip package. Actually let me try to do it.

**Comment by damienmg** [comment] 2016-06-10 16:35
(sorry I have to leave, my fast test show it should not be too hard, I'll try to send a PR for doing so on monday).

**Comment by martinwicke** [comment] 2016-06-11 02:29
Awesome! That would be a great improvement of our installation process.

**Comment by damienmg** [comment] 2016-06-13 10:56
So I made it work but it's hacky:
  1. the name of the package encode the version of tensorflow (not a problem), the version of python and the system (not a problem). The version of python might be an issue. A workaround is to wrap the package in another zip but that's not really nice.
  2. pip is non deterministic, it stores the timestamp of the zip file. It's ok overall to mark the genrule as time stamped as this is for building a release binary.

So overall my only trouble is the name of the package. I also figured out it might be good to have a skylark rules to do it that does not depends on bash, this would help the windows port too.

**Comment by damienmg** [comment] 2016-06-13 11:03
Ok the name can be resolve with apropriate auto-configuration I think. I think I'll take today to do it for python :)

**Comment by samfux84** [comment] 2016-06-20 12:45
Hi,

any news about the problem with the missing 'external' directory ?

I could still not install tensorflow.

Python 3 is only recognized if I check out the release 0.9 from github (a check out of the current master branch still does not recognize Python 3 installed in a non-standard location, even when specifying the path to the installation in the configure script). But with r 0.9, I still hit the problem with the external folder:

```
[sfux@e3001 tensorflow]$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Mon Jun 20 14:16:57 CEST 2016 : === Using tmpdir: /scratch/21391859.tmpdir/tmp.HQP10lzxmo
rsync: change_dir "/scratch/21391859.tmpdir/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/external" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
[sfux@e3001 tensorflow]$ 
```
I am trying now since end of may to make a central installation of tensorflow on the HPC cluster of ETH to provide it to our more than 2000 users. We can not install the precompiled binaries, because of GLIBC being too old. There are one or two users, which compiled a newer version of GLIBC in order to be able to install the precompiled binaries of tensorflow in their home directories, but this is not an option for a central installation of tensorflow on our cluster.

Can you please provide some help, or update the description on

https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#create-the-pip-package-and-install

because it does apparently not work, if one follows the steps described there.

Please find below the steps that I used in my attempts to install tensorflow:

1.) bsub -Is -n 24 -W 4:00 bash
(start a bash interactive job to get a 24-core compute node for compiling tensorflow)

2.) module load new gcc/4.8.2 java/1.8.0_91 bazel/0.2.3 swig/3.0.5 python/3.3.3
(load all required modules, to make sure that PATH, LD_LIBRARY_PATH etc. contain all paths to the executables and libraries)

3.) cd $TMPDIR
(go to $TMPDIR to compile on local scratch of the compute node)

4.) git clone -b r0.9 https://github.com/tensorflow/tensorflow

5.) cd tensorflow

6.) git submodule update --init --recursive

7.) export http_proxy=http://proxy.ethz.ch:3128
8.) export https_proxy=http://proxy.ethz.ch:3128
(set proxy server variables)

9.) ./configure
(t automatically finds our Python 3 installation and suggests already the correct path)

10.) vi tools/bazel.rc
(add build --host_force_python=py3)

11.) bazel build --verbose_failures -c opt //tensorflow/tools/pip_package:build_pip_package

12.) bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

And then I am stuck with the error message mentioned above.

Best regards

Sam

**Comment by martinwicke** [comment] 2016-06-20 15:45
Can you check your bazel version just to be sure nothing is getting picked up by accident?

**Comment by samfux84** [comment] 2016-06-21 05:05
[sfux@euler04 ~]$ module load new gcc/4.8.2 java/1.8.0_91 bazel/0.2.3 swig/3.0.5 python/3.3.3
Autoloading openblas/0.2.8_seq
[sfux@euler04 ~]$ bazel version
Warning: ignoring _JAVA_OPTIONS in environment.
WARNING: Output base '/cluster/home/sfux/.cache/bazel/_bazel_sfux/0973bb30a23240a9299c1053c5a39bb3' is on NFS. This may lead to surprising failures and undetermined behavior.
Extracting Bazel installation...
...
Build label: 0.2.3- (@non-git)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 6 08:27:55 2016 (1465201675)
Build timestamp: 1465201675
Build timestamp as int: 1465201675
[sfux@euler04 ~]$

**Comment by damienmg** [comment] 2016-06-21 05:34
Can you upgrade to bazel 0.3.0?

**Comment by martinwicke** [comment] 2016-06-21 06:34
@damienmg do we effectively require bazel 0.3 at this point?

**Comment by damienmg** [comment] 2016-06-21 07:52
No but in the 0.2.3 baseline there was a change that have been rolled back
in 0.3 that cause the missing external directory. 0.2.3 itself does not
contains the culprit change but if the repository was not cloned from the
tag then there might be the culprit.

**Comment by samfux84** [comment] 2016-06-21 08:46
Thank you very much for your help. With bazel 0.3.0 creating the wheel worked:

```
[sfux@e2319 tensorflow]$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Tue Jun 21 10:11:31 CEST 2016 : === Using tmpdir: /scratch/21408461.tmpdir/tmp.uoFXuaUHI5
/scratch/21408461.tmpdir/tmp.uoFXuaUHI5 /scratch/21408461.tmpdir/tensorflow
Tue Jun 21 10:11:31 CEST 2016 : === Building wheel
/scratch/21408461.tmpdir/tensorflow
Tue Jun 21 10:11:40 CEST 2016 : === Output wheel file is in: /tmp/tensorflow_pkg
[sfux@e2319 tensorflow]$ pip
pip         pip3        pip3.3      pipeclient  
[sfux@e2319 tensorflow]$
```
Now pip is going ballistic and tries to delete parts of my numpy etc. installations (I would rather prefer to install a newer version of numpy in user space and to involve it through PYTHONPATH instead of pip trying to delete stuff and reinstalling a newer version, which does most likely not automatically link against OpenBLAS), but this problem is not related to tensorflow.

```
[sfux@e2319 tensorflow]$ pip install /tmp/tensorflow_pkg/tensorflow-0.9.0-py3-none-any.whl 
Processing /tmp/tensorflow_pkg/tensorflow-0.9.0-py3-none-any.whl
Collecting numpy>=1.8.2 (from tensorflow==0.9.0)
  Downloading numpy-1.11.0.tar.gz (4.2MB)
    100% |████████████████████████████████| 4.2MB 144kB/s 
Collecting six>=1.10.0 (from tensorflow==0.9.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b2 (from tensorflow==0.9.0)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB)
    100% |████████████████████████████████| 327kB 1.2MB/s 
Requirement already satisfied (use --upgrade to upgrade): wheel>=0.26 in /cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/wheel-0.29.0-py3.3.egg (from tensorflow==0.9.0)
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.9.0)
  Downloading setuptools-23.0.0-py2.py3-none-any.whl (435kB)
    100% |████████████████████████████████| 438kB 1.1MB/s 
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy
  Stored in directory: /cluster/home/sfux/.cache/pip/wheels/d9/cc/5c/f60303cc48ac18e6bd359aa88e4fa50e8bd88fc7e9f001cfd8
Successfully built numpy
Installing collected packages: numpy, six, setuptools, protobuf, tensorflow
  Found existing installation: numpy 1.8.0
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0:
      Successfully uninstalled numpy-1.8.0
  Rolling back uninstall of numpy
Exception:
Traceback (most recent call last):
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/pip-7.1.2-py3.3.egg/pip/wheel.py", line 317, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/shutil.py", line 110, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/cluster/apps/python/3.3.3/x86_64/lib64/python3.3/site-packages/numpy/_import_tools.py'
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[sfux@e2319 tensorflow]$
```

Thank you again for your help. It would be very nice if you could add a note to

https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#requirements

which explains that you need to have a particular version of bazel (I am refering to the last reply from daminegm about how to correctly checkout 0.2.3 such that you get the proper version of bazel, because from the bazel webpage it is not very clear, what to download). Due to the dependency on bazel, one also need to have Java 1.8.0, SWIG > 3.0.0. It would also be great if you would mention the dependencies of tensorflow with respect to other Python packages (numpy>=1.8.2, six>=1.10.0, protobus 3.0.0b2, setuptools 23.0.0, wheel>=0.26), because on a larger clusters, one does not just run pip as root and hope that everything goes well. I usually check the list of dependencies, install all of them from source in user space and then try on install the main package in user space before installing anything centrally.

Best regards

**Comment by damienmg** [comment] 2016-06-21 09:05
Yes adding a note to checkout a tagged version of bazel and not the master branch would be better for people building from head. Maybe pointing to the Bazel release page?

**Comment by samfux84** [comment] 2016-06-21 12:03
I was very happy to finally be able to build tensorflow from source, but when running it for the first time, I was hitting issue #121. "ImportError: undefined symbol: clock_gettime #121".

This seems to be a never ending story.

First I had a problem with "ulimit -u" for installing bazel, which is required for building tensorflow. On many systems it is set to 256 by default, which is not enough to build bazel.

Then I hit a problem with specifying a proxy server, such that tensorflow can download some dependencies (tensorflow fails to use a proxy server, when the hostname ends with a "/". The solution is to remove the slash)

Then I had the problem with tensorflow not recognizing Python in a non-standard location, which was solved by checking out release 0.9 from github.

Then I hit the problem with the non-existing "external" directory, solved by downloading release 0.3.0 of bazel

Then I had to fight with pip that it does not destroy my Python 3.3.3 installation.

And finally I get runtime errors.

It be nice if the "troubleshooting" paragraph at the bottom of the instructions for building tensorflow from source could be extended, such that other users do not need experience the above-mentioned problems themselves, especially since some of them are known issues.

**Comment by martinwicke** [comment] 2016-06-21 16:03
We should point people to the bazel releases page for sure. 

The troubleshooting paragraph could be extended, but it cannot grow to contain all of the issue tracker. But we can certainly add a note that searching on the issue tracker is a sensible thing to do.

**Closed by martinwicke** 2016-06-21 16:03 UTC

**Comment by martinwicke** [comment] 2016-06-21 16:09
In fact, we do point to bazel's releases page.
