### ISSUE TITLE
Installation broken - Tensorflow 2.1 Cuda 10.1 Ubuntu 18.04

### ISSUE THREAD

**Issue by igorhoogerwoord** [tensorflow/tensorflow#36121] opened 2020-01-22 09:14 UTC
Having followed the installation guide for GPU support multiple times, each time starting from a blank Ubuntu 18.04 LTS instance it breaks when installing cuda 10-1 after installing the driver and rebooting.

See guide for Ubuntu 18.04 + Cuda 10.1: https://www.tensorflow.org/install/gpu
Cuda 10.1 is the version with which Tensorflow 2.1 is compiled and therefore Cuda 10.1 needs to be installed.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- TensorFlow installed from (source or binary): Tensorflow 2.1 binary
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: virtualenv
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla T4

Having restarted the machine and confirmed that the driver recognises the GPU:
The installation guide for GPU support breaks at this section:
```
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1
```
Which results in:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
             Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Having searched stackoverflow, github and the Tensorflow website, it seems that the dependencies list can not be installed. 

Again, I have rerun this installation multiple times on a *blank* machine, without running *anything else* before trying to run this installation.

**Comment by mihaimaruseac** [comment] 2020-01-24 18:59
Can you try installing the 2 deps in `Depends:`?

**Comment by igorhoogerwoord** [comment] 2020-01-25 12:26
Yes tried that, but it gets stuck at installing cuda-**** something. Attempted to run this multiple times but for some reason it doesn't find one of the packages.

Need to try this again to see which specific package it wouldn't install..

**Comment by igorhoogerwoord** [comment] 2020-01-27 13:10
Report on installing dependencies:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
             Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
 Installing cuda-runtime-10-1 results in:
```
sudo apt-get install cuda-runtime-10-1
...
The following packages have unmet dependencies:
 cuda-runtime-10-1 : Depends: cuda-drivers (>= 418.87) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Installing cuda-drivers results in:
```
sudo apt-get install cuda-drivers
...
The following packages have unmet dependencies:
 cuda-drivers : Depends: libnvidia-fbc1-440 (>= 440.33.01) but it is not going to be installed
                Depends: nvidia-compute-utils-440 (>= 440.33.01) but it is not going to be installed
                Depends: nvidia-driver-440 (>= 440.33.01) but it is not going to be installed
                Depends: xserver-xorg-video-nvidia-440 (>= 440.33.01) but it is not going to be installed
```

Installing ```libnvidia-fbc1-440``` is successful and then also lets me install ```cuda-drivers```.
cuda-drivers installation is successful and now it appears I can run this part from the guide without problems:
```
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1
```

However, when testing to see if Tensorflow GPU works, this is the result:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-01-27 13:08:06.076513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-01-27 13:08:06.078594: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
>>> tf.config.list_physical_devices('GPU')
2020-01-27 13:08:13.950792: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-27 13:08:13.952790: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2020-01-27 13:08:13.952841: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: adaptive-3
2020-01-27 13:08:13.952857: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: adaptive-3
2020-01-27 13:08:13.952948: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.33.1
2020-01-27 13:08:13.952988: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.50.0
2020-01-27 13:08:13.953003: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 430.50.0 does not match DSO version 440.33.1 -- cannot find working devices in this configuration
[]
```

What installation steps for the cuda dependencies that work for Tensorflow 2.1 GPU on Linux Ubuntu?

**Comment by igorhoogerwoord** [comment] 2020-01-27 13:17
Update 2:

When trying to reinstall ```sudo apt-get install --no-install-recommends nvidia-driver-418``` from the guide:
```
The following packages have unmet dependencies:
 nvidia-driver-418 : Depends: nvidia-driver-430 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

It appears that Nvidia driver 418 depends on 430. When trying to install nvidia-driver 430 I ran into the same problem of many broken packages which would not be installed.

After successfully installing nvidia-driver-430 by going down the rabit hole of broken packages and installing each individiually, nvidia-smi output:
```
nvidia-smi
Mon Jan 27 13:14:10 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    28W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

After this testing Tensorflow 2.1 with list devices does seem to work:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-01-27 13:15:54.758171: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-01-27 13:15:54.760036: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
>>> tf.config.list_physical_devices('GPU')
2020-01-27 13:16:08.210038: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-27 13:16:08.908023: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-27 13:16:08.908709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2020-01-27 13:16:08.908758: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-27 13:16:08.908799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-27 13:16:08.911539: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-27 13:16:08.912234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-27 13:16:08.914737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-27 13:16:08.916157: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-27 13:16:08.916220: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-27 13:16:08.916306: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-27 13:16:08.916993: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-27 13:16:08.917573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Does Tensorflow 2.1 require nvidia-driver-430 instead of 418 and should the documentation be updated?

**Comment by mihaimaruseac** [comment] 2020-01-27 16:50
2.1 uses CUDA 10.1

**Comment by igorhoogerwoord** [comment] 2020-01-28 03:15
Hi @mihaimaruseac 

10.1 is indeed the CUDA version that I am installing, because the current documentation does refer to that version for Tensorflow 2.1: https://www.tensorflow.org/install/gpu

It turns out the Nvidia *driver* needs to be 430 instead of 418 to make it work on Linux Ubuntu 18.04. 

I think the documentation needs to be updated to reflect the new driver version right?
Or do you mean to say something else with your comment?

**Comment by mihaimaruseac** [comment] 2020-01-28 17:02
You are right, I misunderstood.

**Comment by ymodak** [comment] 2020-02-03 22:31
@igorhoogerwoord Thanks for sharing your findings.
On the TF website currently we say `CUDA 10.1 requires 418.x or higher.`
https://www.tensorflow.org/install/gpu#software_requirements

**Comment by igorhoogerwoord** [comment] 2020-02-04 03:26
Is that helpful for people installing Tensorflow though?
As it appears Nvidia only makes 430 available for Ubuntu?

-> The installation errors with the Nvidia cuda code took long to figure out because the driver version in the install script from the document says driver version 418 while this version can not actually be installed on Linux Ubuntu 18.04.

**Comment by lamberta** [comment] 2020-02-07 18:52
Thanks. Can you send a PR for that page in the tensorflow/docs repo: https://github.com/tensorflow/docs/blob/master/site/en/install/gpu.md

But verifying will take longer

**Comment by igorhoogerwoord** [comment] 2020-02-08 02:34
Can someone else commit this?: https://github.com/tensorflow/docs/pull/1450

**Comment by HardRockDude** [comment] 2020-02-10 01:36
A few comments from my side, as I've been struggling with a similar problem with a slightly different root cause.

0. Starting from a CLEAN MACHINE (delete your ./cache/pip/ if you have to).
1. Created and activated conda environment with `python=3.6`
2. `pip install tf-nightly` (installs 2.2.0 at this time of writing)
3. Then followed the entire block in the manual with no problems:
```
# Add NVIDIA package repositories
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo apt-get update
```
4. Next block:
```
# Install NVIDIA driver
sudo apt-get install --no-install-recommends nvidia-driver-418
# Reboot. Check that GPUs are visible using the command: nvidia-smi
```
This worked well for me as opposed to for @igorhoogerwoord as the 418 driver is automatically fetched as 430.50. For anyone who's interested: After a reboot, open the Ubuntu "software update" settings, go to the tab "additional drivers", and see whether the correct version is selected (430 should be selected). In a terminal, `nvidia-smi` should say:
`| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |`
Verification comes from this fact:
```
$ sudo apt-get install nvidia-driver-418
nvidia-driver-418 is already the newest version (430.50-0ubuntu0.18.04.2).
```
5. But then, next step from the manual:
```
# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends cuda-10-1
cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
            Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Trying to install the depends just lead to hair loss.
6. I left it at that and continued with the rest of the manual:
```
sudo apt-get install --no-install-recommends libcudnn7=7.6.4.38-1+cuda10.1
sudo apt-get install --no-install-recommends libcudnn7-dev=7.6.4.38-1+cuda10.1

# Install TensorRT. Requires that libcudnn7 is installed above.
sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1
sudo apt-get install -y --no-install-recommends libnvinfer-dev=6.0.1-1+cuda10.1
sudo apt-get install -y --no-install-recommends libnvinfer-plugin6=6.0.1-1+cuda10.1
```
All of these went well. Notice I did them all in clear separate steps.

7. But how to install CUDA? After hours of cursing I decided to solve it dirtily:
`conda install cudatoolkit=10.1.243`

Following this, my tensorflow programs run just fine!


ADDENDUM:
You might notice that installating the packages in step 6 actually installs some CUDA 10.2 related things, particularly `libcublas`. You can check this typing:
```
dpkg -l | grep libcublas
libcublas-dev       10.2.2.89-1       amd64    CUBLAS native dev links, headers
libcublas10         10.2.2.89-1       amd64    CUBLAS native runtime libraries
```
This is for CUDA 10.2. I had problems with this version mix before, so I decided to clean this up for once and for all:
```
sudo apt-get install libcublas-dev=10.2.1.243-1
sudo apt-get install libcublas10=10.2.1.243-1
```
The version numbers are a mess, 10.2.2 is CUDA 10.2 and 10.2.1 is CUDA 10.1.
Downgrading libcublas will also trigger the cuda-license-10-2 package to become obsolete.

**Comment by jchwenger** [comment] 2020-05-03 10:47
Hi,

I'm also struggling with this. I followed the instructions for Ubuntu 18.04 twice on two different machines, worked like a charm, and now I get stuck as described above when trying to install `cuda-10-1` (the rest seems fine, `nvidia-smi` shows the gpus, although with cuda version 10.2, like on the other machines that still run ok with 10.1 set up following the manual instructions):
```
$ sudo apt-get install cuda-10-1
The following packages have unmet dependencies:
 cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
             Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
When trying to install deps:
```
$ sudo apt-get install cuda-runtime-10-1
The following packages have unmet dependencies:
 cuda-runtime-10-1 : Depends: cuda-drivers (>= 418.87) but 410.0-0~dummy18.04 is to be installed
E: Unable to correct problems, you have held broken packages.
```
```
$ sudo apt-get install cuda-drivers
cuda-drivers is already the newest version (410.0-0~dummy18.04).
```

**Comment by ymodak** [comment] 2020-05-31 04:47
Closing this issue since the associated PR has been merged. Feel free to reopen if necessary.
Thanks!

**Closed by ymodak** 2020-05-31 04:47 UTC
Labels: TF 2.1, subtype: ubuntu/linux, type:build/install

**Comment by MVPavan** [comment] 2020-09-01 19:58
If anyone is still looking for a solution, try the following.
Note: It was tried on Cuda 10.2, nvidia-450:

After following the [installation guide for GPU](https://www.tensorflow.org/install/gpu#install_cuda_with_apt) till "Install nvidia driver"

`
sudo apt-get install nvidia-settings

sudo apt-get install cuda-drivers-450

sudo apt-get install cuda-runtime-10-2

sudo apt-get install cuda-demo-suite-10-2

sudo apt-get install  \
    cuda-10-2 \
    libcudnn7=7.6.5.32-1+cuda10.2  \
    libcudnn7-dev=7.6.5.32-1+cuda10.2

export PATH=/usr/local/cuda/bin:$PATH  
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

source ~/.bashrc
`
