### ISSUE TITLE
Optimization flags are ignored in builds

### ISSUE THREAD

**Issue by samikama** [tensorflow/tensorflow#21528] opened 2018-08-09 21:28 UTC
user defined optimization flags, i.e. bazel build -copt="xxx", regardless whether passed from command-line or are not propagated to compilation steps. This creates a problem especially in cuda builds and same for both clang and nvcc based builds. Here is an example

Bazel command-line
```shell
bazel build -s -c opt --copt="-march=sandybridge" --copt="-mtune=broadwell" --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" tensorflow/tools/pip_package:build_pip_package
```

one of the compilation commands
```
external/local_config_cuda/crosstool/extra_tools/bin/clang -MD -MF bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_JEMALLOC -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DLLVM_BUILD_GLOBAL_ISEL -iquote . -iquote bazel-out/host/genfiles -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote external/jemalloc -iquote bazel-out/host/genfiles/external/jemalloc -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/host/genfiles/external/local_config_cuda -iquote external/llvm -iquote bazel-out/host/genfiles/external/llvm -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/jemalloc/include -isystem bazel-out/host/genfiles/external/jemalloc/include -isystem bazel-out/host/bin/external/jemalloc/include -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem bazel-out/host/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda -isystem bazel-out/host/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/crt -isystem external/llvm/lib/IR -isystem bazel-out/host/genfiles/external/llvm/lib/IR -isystem bazel-out/host/bin/external/llvm/lib/IR -isystem external/llvm/include/llvm/IR -isystem bazel-out/host/genfiles/external/llvm/include/llvm/IR -isystem bazel-out/host/bin/external/llvm/include/llvm/IR -isystem external/llvm/include -isystem bazel-out/host/genfiles/external/llvm/include -isystem bazel-out/host/bin/external/llvm/include '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wno-invalid-partial-specialization -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 -g0 -c tensorflow/compiler/xla/service/gpu/tuple_thunk.cc -o bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.o
```

**Comment by jlebar** [comment] 2018-08-09 21:30
Hi, I don't work on the TF build system.  Perhaps you mean to assign to someone on the TF build team?

**Comment by jlebar** [comment] 2018-08-09 21:33
cc @gunan @ilya-biryukov

**Comment by gunan** [comment] 2018-08-09 21:38
I think you configured for GPU and to build with clang in the configure script.
`--config=cuda` gets added in bazelrc when you choose to build for GPU in our configure script.

@ilya-biryukov set this option up for us, so Ill let him look.

**Comment by samikama** [comment] 2018-08-09 21:42
@jlebar current cuda toolchain file filters out any parameters it doesn't understand instead of passing them as compiler parameters to nvcc
it looks like similar issue is happening with clang compilation., --config=cuda is in bazelrc file

**Comment by samikama** [comment] 2018-08-09 22:02
Actually one should *not* add --config=cuda to command-line anymore since if you select cuda with clang, it creates a conflicting rule for building the pip package and won't build.

**Comment by samikama** [comment] 2018-08-10 00:45
Two more updates. I instrumented crosstool_wrapper_driver_is_not_gcc to printout compiler flags it get, used for cpu compilation and gpu compilation and did a build with -s option, generating around 140k line log file. Some early observations
- For some reason only part of the files get --copt options
- If these options are passed to cuda compilation, they are ignored, as was expected from the code.
Tinkering more.

**Comment by gunan** [comment] 2018-08-11 06:51
Maybe these are excluded in our crosstool intentionally?
Is it possible that the following was  the cause to make such a decision?
https://devtalk.nvidia.com/default/topic/780902/nvcc-with-avx-support-cannot-find-gcc-builtin-intrinsics/
Does the above still apply?

**Comment by samikama** [comment] 2018-08-15 01:07
@gunan,
I believe issue there is different. Reporter there is trying to use gcc avx intrinsics in .cu files. passing -Xcompiler "-mavx" should be perfectly fine. Besides, the wrapper actually would pass -mavx (or any -mxxx) flag to compiler but would not pass -march=sandybridge which would also enable same flags.

**Comment by tensorflowbutler** [comment] 2018-08-31 15:03
Nagging Assignee @tatatodd: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-16 02:29
Nagging Assignee @tatatodd: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-16 19:51
@meteorcloudy could you loop in someone who can help out with our gpu crosstool?

**Comment by meteorcloudy** [comment] 2018-09-17 08:50
From the command line
```
external/local_config_cuda/crosstool/extra_tools/bin/clang -MD -MF bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.d '-frandom-seed=bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_JEMALLOC -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DLLVM_BUILD_GLOBAL_ISEL -iquote . -iquote bazel-out/host/genfiles -iquote external/nsync -iquote bazel-out/host/genfiles/external/nsync -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/host/genfiles/external/com_google_absl -iquote external/jemalloc -iquote bazel-out/host/genfiles/external/jemalloc -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/host/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/host/genfiles/external/local_config_cuda -iquote external/llvm -iquote bazel-out/host/genfiles/external/llvm -isystem external/nsync/public -isystem bazel-out/host/genfiles/external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/jemalloc/include -isystem bazel-out/host/genfiles/external/jemalloc/include -isystem bazel-out/host/bin/external/jemalloc/include -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/host/genfiles/external/protobuf_archive/src -isystem bazel-out/host/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda -isystem bazel-out/host/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include -isystem external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/genfiles/external/local_config_cuda/cuda/cuda/include/crt -isystem bazel-out/host/bin/external/local_config_cuda/cuda/cuda/include/crt -isystem external/llvm/lib/IR -isystem bazel-out/host/genfiles/external/llvm/lib/IR -isystem bazel-out/host/bin/external/llvm/lib/IR -isystem external/llvm/include/llvm/IR -isystem bazel-out/host/genfiles/external/llvm/include/llvm/IR -isystem bazel-out/host/bin/external/llvm/include/llvm/IR -isystem external/llvm/include -isystem bazel-out/host/genfiles/external/llvm/include -isystem bazel-out/host/bin/external/llvm/include '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wno-invalid-partial-specialization -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 -g0 -c tensorflow/compiler/xla/service/gpu/tuple_thunk.cc -o bazel-out/host/bin/tensorflow/compiler/xla/service/gpu/_objs/gpu_executable/tensorflow/compiler/xla/service/gpu/tuple_thunk.pic.o
```

Looks like Bazel is compiling for host configuration. You need to use `--host_copt` and `--host_cxxopt` if you want to pass options for those compilations. 
Also /cc @mhlopko the C++ expert.

**Comment by perfinion** [comment] 2018-09-18 03:36
@samikama try this: https://github.com/gentoo/gentoo/blob/0d7adf51d80763d2ca8c3e5ffac4dd9b3edbe388/sci-libs/tensorflow/tensorflow-1.11.0_rc0.ebuild#L125-L141
im pretty sure that snippet gets all flags properly. (at least for one machine, I havent worked on cross-compiling yet)

**Comment by samikama** [comment] 2018-09-21 21:06
@perfinion, Sorry I can't see how this helps with cuda compilation.

**Comment by tensorflowbutler** [comment] 2018-10-06 18:42
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mhlopko** [comment] 2018-10-16 12:15
Is there anything that needs to be done on the Bazel side? What Yun said in https://github.com/tensorflow/tensorflow/issues/21528#issuecomment-421932118 should fix the issue.

**Comment by tensorflowbutler** [comment] 2018-10-31 12:46
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-15 18:58
Nagging Assignee @gunan: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-30 18:56
Nagging Assignee @gunan: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2019-05-17 20:59
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-05-17 20:59 UTC
Labels: stat:awaiting tensorflower, type:build/install
