### ISSUE TITLE
TF 1.14 build failed on Ubuntu 18.04: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_

### ISSUE THREAD

**Issue by 1zoom** [tensorflow/tensorflow#35584] opened 2020-01-04 17:10 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version:1.14
- Python version:3.6.9
- Installed using virtualenv? pip? conda?: Virtualenv
- Bazel version (if compiling from source):1.1.0
- GCC/Compiler version (if compiling from source):gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: Cuda=10.2/cuDNN=7.6.5
- GPU model and memory:Geforce GTX 1070/8G/Driver Version: 440.33.01    

**Describe the problem**
Undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_

Build fails with error: ERROR: /data/vkurien/tensorflow-build/tensorflow/tensorflow/python/keras/api/BUILD:115:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 772, in main
    lazy_loading, args.use_relative_imports)
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 629, in create_api_files
    compat_api_versions, lazy_loading, use_relative_imports)
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 503, in get_api_init_text
    _, attr = tf_decorator.unwrap(attr)
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 219, in unwrap
    elif _has_tf_decorator_attr(cur):
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 124, in _has_tf_decorator_attr
    hasattr(obj, '_tf_decorator') and
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/vkurien/.virtualenvs/tensorflow-build-1.14/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 28, in <module>
    _wrap_py_utils = swig_import_helper()
  File "/home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrap_py_utils', fp, pathname, description)
  File "/home/vkurien/.virtualenvs/tensorflow-build-1.14/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/vkurien/.virtualenvs/tensorflow-build-1.14/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/vkurien/.cache/bazel/_bazel_vkurien/229479d4bc4ba13038e7d45343e2dcc2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /data/vkurien/tensorflow-build/tensorflow/tensorflow/python/tools/BUILD:98:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
INFO: Elapsed time: 6732.030s, Critical Path: 456.19s
INFO: 4238 processes: 4238 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Ran ./configure and accepted CUDA and TensorRT option. 
Then ran: bazel-1.1.0 build --config=opt --config=v1 --verbose_failures //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by 1zoom** [comment] 2020-01-04 19:41
This is probably a repeat of issue [build failure for TF2](https://github.com/tensorflow/tensorflow/issues/35115)

**Comment by freedomtan** [comment] 2020-01-05 01:56
@1zoom yes, I believe it's the same problem. Simple solution is to use bazel 0.2x instead of 1.1.0.

**Comment by sujoyrc** [comment] 2020-01-05 04:54
When I try downgrading by the following command

`sudo apt install bazel-0.29.0`

I get the following error

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bazel-0.29.0
E: Couldn't find any package by glob 'bazel-0.29.0'
E: Couldn't find any package by regex 'bazel-0.29.0'


How do I install bazel-0.2x

**Comment by sujoyrc** [comment] 2020-01-05 09:00
I installed from source and got the error that I do need bazel 1.0.0 or higher.

> (base) antpc@ant-pc: /home/antpc/tensorflow$ which bazel
/home/antpc/bin/bazel
(base) antpc@ant-pc:/home/antpc/tensorflow$ bazel --version
bazel 0.29.1
(base) antpc@ant-pc:/home/antpc/tensorflow$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please upgrade your bazel installation to version 1.0.0 or higher to build TensorFlow!

**Comment by 1zoom** [comment] 2020-01-05 15:04
@sujoyrc, @freedomtan ,

1. I confirmed that using bazel 0.26.1  does work successfully.
2. In terms of the specific above, you have to change the following files to make the build work with bazel-0.26.1:
3. configure.py: 
-_TF_MIN_BAZEL_VERSION = '1.0.0'
-_TF_MAX_BAZEL_VERSION = '1.1.0'
+_TF_MIN_BAZEL_VERSION = '0.26.0'
+_TF_MAX_BAZEL_VERSION = '0.26.1'
4) WORKSPACE:
-check_bazel_version_at_least("1.0.0")
+check_bazel_version_at_least("0.26.0")

5) .bazelrc:  # Enable using platform specific build settings
-build --enable_platform_specific_config
+build --config=linux <-- If you are using windows then change this. 

That made it all work

**Comment by sujoyrc** [comment] 2020-01-05 19:48
Thanks it worked

**Comment by oanush** [comment] 2020-01-06 03:59
@1zoom ,
Please close the issue if the issue is resolved, thanks!

**Comment by 1zoom** [comment] 2020-01-06 21:55
Workaround found, but no solution - closing for now

**Closed** 2020-01-06 21:55 UTC
Labels: TF 1.14, stat:awaiting response, type:build/install

**Comment by cswiger** [comment] 2020-01-18 21:38
This bazel 0.26.1 solution worked for me also - Ubuntu16, python 3.5.2, TF2.1 cuda gpu, gcc 5.4.0, cuda 10.1, cudnn7, GeForce GTX 1060 6GB

**Comment by jamesturner246** [comment] 2020-01-19 07:29
Also works for me. Any chance of backporting this fix to the r2.1 branch?

**Comment by jiapei100** [comment] 2020-01-31 01:54
> @sujoyrc, @freedomtan ,
> 
> 1. I confirmed that using bazel 0.26.1  does work successfully.
> 2. In terms of the specific above, you have to change the following files to make the build work with bazel-0.26.1:
> 3. configure.py:
>    -_TF_MIN_BAZEL_VERSION = '1.0.0'
>    -_TF_MAX_BAZEL_VERSION = '1.1.0'
>    +_TF_MIN_BAZEL_VERSION = '0.26.0'
>    +_TF_MAX_BAZEL_VERSION = '0.26.1'
> 
> 1. WORKSPACE:
>    -check_bazel_version_at_least("1.0.0")
>    +check_bazel_version_at_least("0.26.0")
> 2. .bazelrc:  # Enable using platform specific build settings
>    -build --enable_platform_specific_config
>    +build --config=linux <-- If you are using windows then change this.
> 
> That made it all work


Still buggy from my side...

```console
INFO: From ProtoCompile tensorflow/python/framework/cpp_shape_inference.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: ....../tensorflow/core/util/BUILD:338:1: Executing genrule //tensorflow/core/util:version_info_gen failed (Profiling timer expired): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
/bin/bash: line 1: 11745 Profiling timer expired bazel-out/host/bin/tensorflow/tools/git/gen_git_source --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/k8-opt/bin/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 78.994s, Critical Path: 13.68s
INFO: 231 processes: 231 local.
FAILED: Build did NOT complete successfully
```

**Comment by vk1z** [comment] 2020-01-31 12:45
@jiapei100 What were your build flags? Mine were the standard cuda and opt flags, nothing else. I'm wondering why protobuf directories don't exist. To make sure that everything starts from a clean state, without pollution from prior builds, I tend to rm -fr .cache/bazel first.

**Comment by MattConley** [comment] 2020-02-19 23:50
In case it helps, adding the bazel flag `--noincompatible_do_not_split_linking_cmdline` when using bazel 0.27.1 and python3 allowed my build to complete successfully.
