### ISSUE TITLE
cifar10 example running slower with Windows 10

### ISSUE THREAD

**Issue by oranshayer** [tensorflow/tensorflow#10066] opened 2017-05-20 21:52 UTC
### System information 1
- **Have I written custom code**: No
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 0.12.1
- **CUDA/cuDNN version**: 8.0.44 / 5.1
- **GPU model and memory**: GTX 1080 8gb
- **Exact command to reproduce**: 'python3 cifar10_train.py'

### System information 2
- **Have I written custom code**: No
- **OS Platform and Distribution**: Windows 10 Pro
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 0.12.1
- **CUDA/cuDNN version**: 8.0.44 / 5.1
- **GPU model and memory**: GTX 1080 8gb
- **Exact command to reproduce**: 'python cifar10_train.py'

### System information 3
- **Have I written custom code**: No
- **OS Platform and Distribution**: Windows 7 Pro
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 0.12.1
- **CUDA/cuDNN version**: 8.0.44 / 5.1
- **GPU model and memory**: Titan X maxwell 12gb
- **Exact command to reproduce**: 'python cifar10_train.py'

### Describe the problem
When running the cifar 10 CNN example code (https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10/), I get very different performance on several OS while having same installations of CUDA, CuDNN & TF, and the same code of course.
With _System 1_ (described above): running at ~2600 images/sec, Python CPU usage at ~50%
With _System 2_ (described above): running at ~600 images/sec, Python CPU usage at **100%** (!)
With _System 3_ (described above): running at ~2600 images/sec, Python CPU usage at ~50%

I'm experiencing the same problems with TF r1.0.1.
Seems like something in this code (pherhaps the queue threading?) doesn't go well with win10? CPU usage reaches 100% with win10, and significantly slower, that's very weird.

Thanks.

**Comment by StefanoD** [comment] 2017-05-21 08:31
Why don't you use the latest TF version? Maybe it's fixed there.

**Comment by oranshayer** [comment] 2017-05-22 13:29
Tried with the latest release. Same issue still exists.

**Comment by aselle** [comment] 2017-05-29 21:05
@mrry, any ideas. Could you take a look?

**Comment by gunan** [comment] 2017-05-30 23:25
What are the CPUs and memory you are using on these machines, are they all the same?

**Comment by oranshayer** [comment] 2017-06-04 13:13
intel i7-7700
CORSAIR Vengeance LPX 32GB (2 x 16GB) DDR4

It's all the same hardware for all OS - it's a dual boot machine with windows 10 and ubuntu 16.04

**Comment by dtung2008** [comment] 2017-06-08 22:37
I suspect I have similar issue with TF v.1.1.0. So I search internet and find this link.

I have a ubuntu 16.04 run on virtualbox assigned with 2 cores of i7 (somewhat older generation), when running the cifar10 example, it processes about 60 images/second. (2 cores are 100% utilized). 

Then I find a windows 10 with full power (4 cores) of i7 latest generation, running the cifar10 again, it still process about 60 images/second. (4 cores, 8 threads are all 100% utilized, strange !!)

**Comment by oranshayer** [comment] 2017-06-10 17:18
Anything new on this?

**Comment by tensorflowbutler** [comment] 2017-12-22 07:36
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2017-12-22 18:56
@reedwm Any ideas why this may be happening?

**Comment by reedwm** [comment] 2017-12-22 19:11
I'm not sure, sorry. I don't have a Windows machine to reproduce this on. @oranshayer can you try again on Tensorflow 1.4?

/CC @mrry again, any ideas why TensorFlow on windows could be slower than on Ubuntu?

**Comment by mrry** [comment] 2017-12-22 19:22
No idea, but the two variables seem to be that the configuration (Windows 10 Pro, GTX 1080 8gb) is slower than (Windows 7 Pro, Titan X maxwell 12gb), and the latter version is as fast as Ubuntu.

This makes me suspect that something in the configuration of your Windows 10 system is causing the problem, rather than TensorFlow. Driver version perhaps?

**Comment by tensorflowbutler** [comment] 2018-01-06 18:57
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mrry** [comment] 2018-01-06 23:00
I'm closing this due to lack of recent activity. Since TensorFlow 1.5.0rc0 with CUDA 9 support is now available, I expect much has changed since TensorFlow 0.12.1, which is over a year old now. If the problem reproduces with the latest version of TensorFlow, please feel free to reopen the issue.

**Closed by mrry** 2018-01-06 23:00 UTC
Labels: stat:awaiting response, type:bug/performance
