### ISSUE TITLE
Problem with softmax on Windows OS

### ISSUE THREAD

**Issue by Windaway** [tensorflow/tensorflow#21337] opened 2018-08-02 09:36 UTC
------------------------
### System information
Windows 10 x64 pro 17314.365, i5 6600k, Z170(clevo), GTX1070(notebook), 16G DDR4 2400 Dual Channel .
Tensorflow 1.9.0 with AVX2 simd, CUDA9.2.148, Cudnn7.1.4, py3.6.6 , VS2017 15.7(with cmake), CP/SM6.1
Tensorflow 1.9.0 offical, CUDA9.0, Cudnn7.05, py3.6.6

### Describe the problem
softmax_cross_entropy_with_logits or softmax_cross_entropy_with_logits_v2 can not be computed on GPU, but sparse_softmax_cross_entropy_with_logits can be computed on GPU. I could add with device cpu to solve the problem. But it seems simlar to https://github.com/tensorflow/models/issues/2803.
The problem may be with softmax kernel, and allow_soft_placement will also solve? 

### Source code / logs
https://github.com/golbin/TensorFlow-Multi-GPUs/blob/master/many-GPUs-MNIST.py
`import datetime

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.client import device_lib

def check_available_gpus():
    local_devices = device_lib.list_local_devices()
    gpu_names = [x.name for x in local_devices if x.device_type == 'GPU']
    gpu_num = len(gpu_names)

    print('{0} GPUs are detected : {1}'.format(gpu_num, gpu_names))

    return gpu_num

def model(X, reuse=False):
    with tf.variable_scope('L1', reuse=reuse):
        L1 = tf.layers.conv2d(X, 64, [3, 3], reuse=reuse)
        L1 = tf.layers.max_pooling2d(L1, [2, 2], [2, 2])
        L1 = tf.layers.dropout(L1, 0.7, True)

    with tf.variable_scope('L2', reuse=reuse):
        L2 = tf.layers.conv2d(L1, 128, [3, 3], reuse=reuse)
        L2 = tf.layers.max_pooling2d(L2, [2, 2], [2, 2])
        L2 = tf.layers.dropout(L2, 0.7, True)

    with tf.variable_scope('L2-1', reuse=reuse):
        L2_1 = tf.layers.conv2d(L2, 128, [3, 3], reuse=reuse)
        L2_1 = tf.layers.max_pooling2d(L2_1, [2, 2], [2, 2])
        L2_1 = tf.layers.dropout(L2_1, 0.7, True)

    with tf.variable_scope('L3', reuse=reuse):
        L3 = tf.contrib.layers.flatten(L2_1)
        L3 = tf.layers.dense(L3, 1024, activation=tf.nn.relu)
        L3 = tf.layers.dropout(L3, 0.5, True)

    with tf.variable_scope('L4', reuse=reuse):
        L4 = tf.layers.dense(L3, 256, activation=tf.nn.relu)

    with tf.variable_scope('LF', reuse=reuse):
        LF = tf.layers.dense(L4, 10, activation=None)

    return LF

if __name__ == '__main__':
    # need to change learning rates and batch size by number of GPU
    batch_size = 10000
    learning_rate = 0.001
    total_epoch = 10

    gpu_num = check_available_gpus()

    X = tf.placeholder(tf.float32, [None, 28, 28, 1])
    Y = tf.placeholder(tf.float32, [None, 10])

    losses = []
    X_A = tf.split(X, int(gpu_num))
    Y_A = tf.split(Y, int(gpu_num))

    '''
    Multi GPUs Usage
    Results on P40
     * Single GPU computation time: 0:00:22.252533
     * 2 GPU computation time: 0:00:12.632623
     * 4 GPU computation time: 0:00:11.083071
     * 8 GPU computation time: 0:00:11.990167
     
    Need to change batch size and learning rates
         for training more efficiently
    
    Reference: https://research.fb.com/wp-content/uploads/2017/06/imagenet1kin1h5.pdf
    '''
    for gpu_id in range(int(gpu_num)):
        with tf.device(tf.DeviceSpec(device_type="GPU", device_index=gpu_id)):
            with tf.variable_scope(tf.get_variable_scope(), reuse=(gpu_id > 0)):
                cost = tf.nn.softmax_cross_entropy_with_logits(
                                logits=model(X_A[gpu_id], gpu_id > 0),
                                labels=Y_A[gpu_id])
                losses.append(cost)

    loss = tf.reduce_mean(tf.concat(losses, axis=0))

    optimizer = tf.train.AdamOptimizer(learning_rate).minimize(
        loss, colocate_gradients_with_ops=True)  # Important!

    init = tf.global_variables_initializer()
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=False))
    sess.run(init)

    mnist = input_data.read_data_sets('/tmp/tensorflow/mnist/input_data', one_hot=True)
    total_batch = int(mnist.train.num_examples/batch_size)
    print("total: %s, %s, %s" % (mnist.train.num_examples, total_batch, batch_size))

    start_time = datetime.datetime.now()

    for epoch in range(total_epoch):
        total_cost = 0

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            batch_xs = batch_xs.reshape(-1, 28, 28, 1)
            _, cost_val = sess.run([optimizer, loss],
                                   feed_dict={X: batch_xs,
                                              Y: batch_ys})
            total_cost += cost_val

        print("total cost : %s" % total_cost)

    print("--- Training time : {0} seconds /w {1} GPUs ---".format(
        datetime.datetime.now() - start_time, gpu_num))`

Logs:

`F:\Anaconda3\envs\tf\python.exe F:/ODT/Leaf/leafmg.py
1.9.0
2018-08-02 17:25:58.253241: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.62GiB
2018-08-02 17:25:58.253526: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-02 17:26:43.721732: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-02 17:26:43.721924: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 
2018-08-02 17:26:43.722057: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N 
2018-08-02 17:26:43.722281: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/device:GPU:0 with 6394 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
1 GPUs are detected : ['/device:GPU:0']
WARNING:tensorflow:From F:/ODT/Leaf/leafmg.py:81: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

2018-08-02 17:26:44.358873: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-02 17:26:44.359084: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-02 17:26:44.359266: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 
2018-08-02 17:26:44.359392: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N 
2018-08-02 17:26:44.359563: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6394 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1305, in _run_fn
    self._extend_graph()
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'softmax_cross_entropy_with_logits_sg': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
SoftmaxCrossEntropyWithLogits: GPU CPU 
Identity: GPU CPU 
ZerosLike: CPU 
Const: GPU CPU 
ExpandDims: GPU CPU 
Neg: GPU CPU 
Mul: GPU CPU 
LogSoftmax: CPU 

Colocation members and user-requested devices:
  softmax_cross_entropy_with_logits_sg (SoftmaxCrossEntropyWithLogits) /device:GPU:0
  gradients/zeros_like (ZerosLike) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/LogSoftmax (LogSoftmax) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/Neg (Neg) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1 (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul_1 (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency (Identity) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency_1 (Identity) /device:GPU:0

Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]

	 [[Node: softmax_cross_entropy_with_logits_sg = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape, softmax_cross_entropy_with_logits_sg/Reshape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/ODT/Leaf/leafmg.py", line 91, in <module>
    sess.run(init)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'softmax_cross_entropy_with_logits_sg': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
SoftmaxCrossEntropyWithLogits: GPU CPU 
Identity: GPU CPU 
ZerosLike: CPU 
Const: GPU CPU 
ExpandDims: GPU CPU 
Neg: GPU CPU 
Mul: GPU CPU 
LogSoftmax: CPU 

Colocation members and user-requested devices:
  softmax_cross_entropy_with_logits_sg (SoftmaxCrossEntropyWithLogits) /device:GPU:0
  gradients/zeros_like (ZerosLike) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/LogSoftmax (LogSoftmax) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/Neg (Neg) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1 (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul_1 (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency (Identity) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency_1 (Identity) /device:GPU:0

Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]

	 [[Node: softmax_cross_entropy_with_logits_sg = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape, softmax_cross_entropy_with_logits_sg/Reshape_1)]]

Caused by op 'softmax_cross_entropy_with_logits_sg', defined at:
  File "F:/ODT/Leaf/leafmg.py", line 81, in <module>
    labels=Y_A[gpu_id])
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1968, in softmax_cross_entropy_with_logits
    labels=labels, logits=logits, dim=dim, name=name)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1879, in softmax_cross_entropy_with_logits_v2
    precise_logits, labels, name=name)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 7738, in softmax_cross_entropy_with_logits
    name=name)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "F:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'softmax_cross_entropy_with_logits_sg': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and devices: 
SoftmaxCrossEntropyWithLogits: GPU CPU 
Identity: GPU CPU 
ZerosLike: CPU 
Const: GPU CPU 
ExpandDims: GPU CPU 
Neg: GPU CPU 
Mul: GPU CPU 
LogSoftmax: CPU 

Colocation members and user-requested devices:
  softmax_cross_entropy_with_logits_sg (SoftmaxCrossEntropyWithLogits) /device:GPU:0
  gradients/zeros_like (ZerosLike) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/LogSoftmax (LogSoftmax) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/Neg (Neg) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1/dim (Const) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/ExpandDims_1 (ExpandDims) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/mul_1 (Mul) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency (Identity) /device:GPU:0
  gradients/softmax_cross_entropy_with_logits_sg_grad/tuple/control_dependency_1 (Identity) /device:GPU:0

Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]

	 [[Node: softmax_cross_entropy_with_logits_sg = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/device:GPU:0"](softmax_cross_entropy_with_logits_sg/Reshape, softmax_cross_entropy_with_logits_sg/Reshape_1)]]

Process finished with exit code 1
`

**Comment by tensorflowbutler** [comment] 2018-08-02 19:06
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Windaway** [comment] 2018-08-04 02:17
Have I written custom code
Yes
OS Platform and Distribution
Windows 10 x64 pro 17314.365, i5 6600k, Z170(clevo), 
Tensorflow 1.9.0 with AVX2 simd, CUDA9.2.148, Cudnn7.1.4, py3.6.6 , VS2017 15.7(with cmake), CP/SM6.1
Tensorflow 1.9.0 offical, CUDA9.0, Cudnn7.05, py3.6.6
TensorFlow installed from
Offical and from source
TensorFlow version
1.9.0
Bazel version
Null(with cmake)
CUDA/cuDNN version
Tensorflow 1.9.0 with AVX2 simd, CUDA9.2.148, Cudnn7.1.4, py3.6.6 , VS2017 15.7(with cmake), CP/SM6.1
Tensorflow 1.9.0 offical, CUDA9.0, Cudnn7.05, py3.6.6
GPU model and memory
GTX1070(notebook) 16G DDR4 2400 Dual Channel

**Comment by tensorflowbutler** [comment] 2018-09-06 18:57
Nagging Assignee @asimshankar: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-21 19:03
Nagging Assignee @asimshankar: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-06 18:41
Nagging Assignee @asimshankar: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-05 18:58
Nagging Assignee @asimshankar: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-05 18:59
Nagging Assignee @asimshankar: It has been 123 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sushreebarsa** [comment] 2021-09-13 17:04
@Windaway It looks like you are using an older Version of Tensorflow which is out of support window. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.6.0) and let us know if the issue still persists? Thanks!

**Closed** 2021-10-03 07:59 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:gpu, subtype:windows
