### ISSUE TITLE
cmake: No session factory registered for the given session options 

### ISSUE THREAD

**Issue by hemecha** [tensorflow/tensorflow#13177] opened 2017-09-20 09:15 UTC
Hi everyone,

I have built the static library for tensorflow with cmake in Windows and I have the error "No session factory registered for the given session options ". This issue is fixed with the flag /Wholearchive, however it seems there is not equivalent flag for Qt creator. So, my question is if someone knows if the static library built with bazel has the same issue (add the flag /wholearchive) in windows? I have read that someone people didin´t have this issue with bazel in Linux, but it would be great if someone can confirm it for Windows.

Thanks for your help.

**Comment by yaroslavvb** [comment] 2017-09-21 16:14
looks this was fixed in other issue, feel free to close if it was addressed

**Comment by shivaniag** [comment] 2017-09-21 18:54
This is a duplicate of #13180. Please see that issue for more information.

**Closed by shivaniag** 2017-09-21 18:54 UTC
Labels: type:build/install

**Comment by Ruvinator** [comment] 2018-04-11 03:44
@hemecha  I am currently having the same issue. I was able to build TensorFlow using CMake and use it in Visual Studio with the /WHOLEARCHIVE flag, but I'm having trouble finding an alternative in Qt. Would you be able to shed some light regarding how you generated libprotobuf.lib and tensorflow.lib and then linked them in Qt?

Thanks in advance!

**Comment by Ruvinator** [comment] 2018-04-11 14:56
Just following up on my previous comment - I ended up getting TensorFlow to work on Qt using your recommendation in #13180.

For reference: I built TensorFlow using CMake as per the instructions in [this post](https://medium.com/@shiweili/building-tensorflow-c-shared-library-on-windows-e79c90e23e6e). Once built, I was able to run the C++ API code from [this post](https://joe-antognini.github.io/machine-learning/windows-tf-project) in Qt by adding the corresponding Include Directories and linking only libprotobuf.lib and tensorflow.lib (both of which should be in the CMake build directory) rather than the libraries listed in the post.
