### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_file'

### ISSUE THREAD

**Issue by YibaYan** [tensorflow/tensorflow#25877] opened 2019-02-19 08:21 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy]
when i run densenet, i got stuck into this bug.
`  File "D:/Documents/GitHub/DenseNet-master/imagenet_inference.py", line 26, in <module>
    print('Predicted:', decode_predictions(preds))
  File "D:\Applications\Anaconda3\envs\keras\lib\site-packages\keras_applications\imagenet_utils.py", line 224, in decode_predictions
    fpath = keras_utils.get_file(
AttributeError: 'NoneType' object has no attribute 'get_file'
`
**System information**
- Win10
- Python version:3.6

**Comment by jvishnuvardhan** [comment] 2019-02-20 23:35
@YibaYan Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-01 23:32
I think it was resolved. Closing due to lack of recent activity. Please open new ticket if you see similar issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-01 23:32 UTC
Labels: subtype:windows, type:build/install
