### ISSUE TITLE
Tensorflow Feature Column V2 test cases failing due to Out of Memory for CUDA

### ISSUE THREAD

**Issue by amitisgr8** [tensorflow/tensorflow#24703] opened 2019-01-04 12:07 UTC
I am trying to run feature_column_v2_test script using  the bazel test command :
bazel test tensorflow/python/feature_column:feature_column_v2_test
I get an error of i.e out of memory for CUDA
---------------------------------------------------------------------------------------------------
```
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
E.2019-01-04 11:57:48.246499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1464] Ignoring visible gpu device 0 whose executor is in invalid state: Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 6373572608
2019-01-04 11:57:48.248421: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 6373572608
```
-----------------------------------------------------------------------------------------------
**My System information**
- Build Tensorflow via Bazel no change from the original repository:
- OS is Ubuntu 18.04
-  Dell G7 15 GTX 1060 Nvidia Cuda 9.0:
- TensorFlow installed from (source or binary):
- 1.18 Tensorflow version:
- Python version is 3.6.7:
- Bazel version  0.19.2
- CUDA/cuDNN version: 9/7
- GPU model and memory: GTX 1060 6GB

Pls help

Regards
Amit

**Comment by msymp** [comment] 2019-01-08 23:13
Hello @amitisgr8 , Please mention the correct TensorFlow version you are building from.
[New Issue Template](https://github.com/tensorflow/tensorflow/issues/new)
Also if you are using the current version 1.12.0, please step back to bazel 0.15.0, and build again.

**Comment by amitsrivastava78** [comment] 2019-01-09 05:03
Thanks for the reply @msymp , yes you are right my tensorflow version is 1.12.0 , but tensorflow does not allow to downgrade the bazel version below 0.19, I tried to by pass some checks to make it compile but in the end they are too many checks and i am not sure if this is the cause of the problem, i tried the same configuration on my server with 12GB GPU RAM instead of 6GB in my machine and to my surprise the same configuration worked on server, so this has to be tensorflow problem.
I find it very strange that tensorflow basic test cases which uses GPU cannot be run on my laptop with the above configurations, any help in this regards is highly appreciated.

Regards
Amit

**Comment by tensorflowbutler** [comment] 2019-01-23 18:48
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by msymp** [comment] 2019-01-23 23:20
@amitisgr8 , as the error says please use the new FeatureColumn APIs in your code and try again:
https://www.tensorflow.org/guide/feature_columns
https://stackoverflow.com/questions/51965094/whats-the-difference-between-tf-feature-column-input-layer-and-tf-layers-input

**Comment by amitsrivastava78** [comment] 2019-01-24 03:30
@msymp , this is just a warning, also i have not modified anything in the Testcases, the least you can expect is the test case to run without modification, Any help in this regard will be highly appriciated.

**Comment by ymodak** [comment] 2019-02-07 19:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-02-07 19:32 UTC
Labels: comp:apis, stat:awaiting response
