### ISSUE TITLE
SavedModel of Keras Model does not save the trainable status

### ISSUE THREAD

**Issue by HedgehogCode** [tensorflow/tensorflow#40994] opened 2020-07-01 16:00 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Google Colab
- TensorFlow installed from: binary
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0
- Python version: 3.6.9
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

Set `trainable` for some layers of a Keras model to `False` and save the model via `model.save(..., save_format='tf')`. Loading the model again with `tf.keras.load_model(...)` does not restore the value of `trainable` but sets the value to `True`.

**Describe the expected behavior**

I would expect the `trainable` flag to saved and loaded correctly.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1tYvRK8mxfvU3_SVV9P97dKUV6W9Hue_S?usp=sharing

**Comment by ravikyram** [comment] 2020-07-02 05:17
I have tried in colab with TF versions 2.2, nightly versions(`2.4.0-dev20200701`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/431be3bc71ee1d13668ee6baa9d2988e/untitled69.ipynb).Thanks!

**Comment by xqr-g** [comment] 2021-01-14 01:45
May I ask is there any update on this bug?

**Comment by saikumarchalla** [comment] 2021-03-05 11:01
@HedgehogCode @xqr-g  Closing the issue since the bug was fixed already [here](https://critique-ng.corp.google.com/cl/359853088). Please feel free to re open the issue if the isse still persists.Thanks!

**Closed by saikumarchalla** 2021-03-05 11:01 UTC
Labels: TF 2.2, comp:keras, stat:awaiting tensorflower, type:bug
