### ISSUE TITLE
op_resolver documentation update

### ISSUE THREAD

**Issue by juanluislm** [tensorflow/tensorflow#21862] opened 2018-08-24 21:22 UTC
Hello,

I am having problems converting my frozen graphs to tflite models. I could do it without problems with v1.8.0-rc0, but the latest version adds an extra input to the FindOp function of the MutableOpResolver (see lines 34 and 31 of op_resolver.h). Here is what they look like

  virtual const TfLiteRegistration* FindOp(tflite::BuiltinOperator op,
                                           int version) const = 0;
  // Finds the op registration of a custom operator by op name.
  virtual const TfLiteRegistration* FindOp(const char* op,
                                           int version) const = 0;

What should be the value of 'version'? How can I figure that out? The documentation does not mention that variable or how to do any sort of mapping.

Thanks,
Juan

**Comment by tensorflowbutler** [comment] 2018-08-31 07:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-16 02:31
It has been 21 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 21:10
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 21:10 UTC
Labels: stat:awaiting response
