### ISSUE TITLE
Cannot import tensorflow in python 

### ISSUE THREAD

**Issue by ananthnagaraj** [tensorflow/tensorflow#8780] opened 2017-03-28 18:13 UTC
I get the following error when I try to import tensorflow in  python 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow

Python Version:-
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

Tensor Flow Version :- 
Name: tensorflow
Version: 1.0.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: wheel, protobuf, numpy, six, mock

Protobuf
Name: protobuf
Version: 3.2.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /usr/local/lib/python2.7/site-packages
Requires: setuptools, six

Numpy 
Name: numpy
Version: 1.12.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /usr/local/lib/python2.7/site-packages
Requires: 

working on MAC sierra . Please let me know what could be the issue.

**Comment by gunan** [comment] 2017-03-28 18:18
Some common issues are mentioned at the end of our installation guide:
https://www.tensorflow.org/install/install_mac#common_installation_problems

I am pretty certain that this is not a bug in TF, it is an issue in your setup.
Therefore, I recommend asking in StackOverflow if the installation guide does not help resolving your problem.

**Comment by asimshankar** [comment] 2017-04-08 07:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-08 07:11 UTC
Labels: stat:awaiting response
