### ISSUE TITLE
Windows Installation permission denied. Why it required Admin?

### ISSUE THREAD

**Issue by mohamedmansour** [tensorflow/tensorflow#10058] opened 2017-05-20 04:43 UTC
Hello, first time install Windows Tensorflow, and I am running Python3.5.2 and following example, I got "Permission Denied". I don't believe it requires admin, or does it?

```
d:\Experiments>conda create -n tensorflow
Fetching package metadata ...........
Solving package specifications:
Package plan for installation in environment C:\Users\mmansour\AppData\Local\conda\conda\envs\tensorflow:

Proceed ([y]/n)? Y

#
# To activate this environment, use:
# > activate tensorflow
#
# To deactivate this environment, use:
# > deactivate tensorflow
#
# * for power-users using bash, you must source
#


d:\Experiments>activate tensorflow

(tensorflow) d:\Experiments>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.1.0-cp35-cp35m-win_amd64.whl
Collecting tensorflow-gpu==1.1.0 from https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.1.0-cp35-cp35m-win_amd64.whl
  Using cached https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.1.0-cp35-cp35m-win_amd64.whl
Collecting six>=1.10.0 (from tensorflow-gpu==1.1.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.2.0 (from tensorflow-gpu==1.1.0)
Collecting wheel>=0.26 (from tensorflow-gpu==1.1.0)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting werkzeug>=0.11.10 (from tensorflow-gpu==1.1.0)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow-gpu==1.1.0)
  Using cached numpy-1.12.1-cp35-none-win_amd64.whl
Collecting setuptools (from protobuf>=3.2.0->tensorflow-gpu==1.1.0)
  Using cached setuptools-35.0.2-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools->protobuf>=3.2.0->tensorflow-gpu==1.1.0)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools->protobuf>=3.2.0->tensorflow-gpu==1.1.0)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools->protobuf>=3.2.0->tensorflow-gpu==1.1.0)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: six, pyparsing, packaging, appdirs, setuptools, protobuf, wheel, werkzeug, numpy, tensorflow-gpu
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\six-1.10.0.dist-info\\DESCRIPTION.rst'

(tensorflow) d:\Experiments>
```

**Comment by snnn** [comment] 2017-05-20 13:03
Non-admin shouldn't have write access to ProgramData and "Program Files". They are system wide files.

**Comment by Wendy0601** [comment] 2017-05-21 20:26
use the cmd as administrator and then install it.
 
![capture](https://cloud.githubusercontent.com/assets/15058478/26287104/3000a872-3e42-11e7-9236-99aefd565ac6.PNG)

**Comment by gunan** [comment] 2017-05-22 20:07
This is related to how anaconda manages its environments, and where it places all environment files.
The issue is unrelated to TF itself. The comments by @snnn and @Wendy0601 explain the root cause, and provide a good workaround.
I am closing this issue.

**Closed by gunan** 2017-05-22 20:07 UTC

**Comment by manideepdv** [comment] 2019-07-03 05:37
I got this error

Requirement already satisfied: setuptools in c:\users\deepu\anaconda3\lib\site-packages (from protobuf>=3.6.1->tensorflow-gpu==1.12.0)
Installing collected packages: tensorflow-gpu
  Found existing installation: tensorflow-gpu 1.14.0
    Uninstalling tensorflow-gpu-1.14.0:
      Successfully uninstalled tensorflow-gpu-1.14.0
  Rolling back uninstall of tensorflow-gpu
Exception:
Traceback (most recent call last):
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "C:\Users\Deepu\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\Deepu\Anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Deepu\\Anaconda3\\Lib\\site-packages\\tensorflow\\python\\_pywrap_tensorflow_internal.pyd'

**Comment by gunan** [comment] 2019-07-03 16:44
@manideepdv if you use the admin account to install tensorflow once, the files created will be owned by the administrator, and your user wont be able to remove them.
This is purely due to your system and the files on them, and has nothing to do with tensorflow.

**Comment by SundarML** [comment] 2020-08-16 08:29
python 3.8 does not support tensorflow 2.2 but 3.6.
