### ISSUE TITLE
Tensorflow Tutorial websites are full of "Math Processing Error" messages

### ISSUE THREAD

**Issue by perrohunter** [tensorflow/tensorflow#1382] opened 2016-03-04 07:39 UTC
Hi,

I just wanted to bring this up, many of the tutorial pages in the current website are showing an error as follows:

[Math Processing Error]

This is showing instead of the formulas and make the learning processed a little bit more complicated.

Example affected page:

https://www.tensorflow.org/versions/r0.7/tutorials/word2vec/index.html#vector-representations-of-words

**Comment by vrv** [comment] 2016-03-04 07:47
Closing as duplicate of #1377 -- thanks for the report!

**Closed by vrv** 2016-03-04 07:47 UTC
