### ISSUE TITLE
"IndexError: list index out of range" when load EfficientDet SavedModel with tf.keras

### ISSUE THREAD

**Issue by NguyenHongSon1103** [tensorflow/tensorflow#43527] opened 2020-09-24 08:00 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

 I try to load SavedModel efficientDetD0 with load_model of keras:

`model = tf.keras.models.load_model("saved_model")'
'model.summary()`

And following error occur: 

Traceback (most recent call last):
  File "E:/Detection/test_infer_model.py", line 129, in <module>
    model = tf.keras.models.load_model("saved_model")
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 121, in load
    path, options=options, loader_cls=KerasObjectLoader)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\saved_model\load.py", line 633, in load_internal
    ckpt_options)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\saved_model\load.py", line 130, in __init__
    self._load_all()
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 221, in _load_all
    self._finalize_objects()
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 526, in _finalize_objects
    _finalize_saved_model_layers(layers_revived_from_saved_model)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 706, in _finalize_saved_model_layers
    inputs = infer_inputs_from_restored_call_function(call_fn)
  File "C:\Users\Luxury\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 982, in infer_inputs_from_restored_call_function
    spec = fn.concrete_functions[0].structured_input_signature[0][0]
IndexError: list index out of range
**Standalone code to reproduce the issue **
link colab: https://colab.research.google.com/drive/1fR8nu3INEWVUJJhex3Dline10296vxri?usp=sharing
and model: https://drive.google.com/file/d/18D8NQp9zP4UW06jeG_75YQWyB531CWUj/view?usp=sharing
I lost 2 days for searching on internet, stackoverflow even this repo's issue but no result, please help !

**Comment by bhack** [comment] 2020-09-24 09:20
The ticket template requires:
> Standalone code to reproduce the issue
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Comment by NguyenHongSon1103** [comment] 2020-09-25 02:18
> The ticket template requires:
> 
> > Standalone code to reproduce the issue
> > Provide a reproducible test case that is the bare minimum necessary to generate
> > the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Sorry, I updated

**Comment by amahendrakar** [comment] 2020-09-30 17:52
@NguyenHongSon1103,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/b31e51328902aea167d3287d67b62a40/43527.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3b0f693fb11f924a27c019d3f4d86106/43527-tf-nightly.ipynb#scrollTo=gpcvSq0y8iV9). Please find the attached gist.

In order to expedite the trouble-shooting process, could you please share the code to generate the `saved_model` files as well? Thanks!

**Comment by NguyenHongSon1103** [comment] 2020-10-04 16:46
@amahendrakar 
I followed here https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html and used file "exporter_main_v2.py" from tensorflow repository

**Comment by hlloydt** [comment] 2020-10-13 15:24
I am also getting the same error with models:
* SSD with Resnet 50 v1 FPN feature extractor, shared box predictor and focal loss (a.k.a Retinanet).
* SSD with EfficientNet-b4 + BiFPN feature extractor, shared box predictor and focal loss (a.k.a EfficientDet-d4)

The config files are the same the ones in: models/research/object_detection/configs/tf2/

I first train with: models/research/object_detection/model_main_tf2.py

And then I export with: models/research/object_detection/exporter_main_v2.py

But then when I try to load the exported model I get the error:

```
Traceback (most recent call last):
  File "/Users/harrythomas/projects/xrfiber_effdet/pb_to_coreml.py", line 82, in <module>
    main()
  File "/Users/harrythomas/projects/xrfiber_effdet/pb_to_coreml.py", line 22, in main
    model = tf.keras.models.load_model(PATH_TO_MODEL, compile=False)
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 120, in load
    model = tf_load.load_internal(
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 632, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 221, in _load_all
    self._finalize_objects()
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 526, in _finalize_objects
    _finalize_saved_model_layers(layers_revived_from_saved_model)
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 706, in _finalize_saved_model_layers
    inputs = infer_inputs_from_restored_call_function(call_fn)
  File "/Users/harrythomas/opt/anaconda3/envs/effdetvenv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 982, in infer_inputs_from_restored_call_function
    spec = fn.concrete_functions[0].structured_input_signature[0][0]
IndexError: list index out of range
```


System Information:
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
* Mobile device name if the issue happens on a mobile device:
* TensorFlow installed from (source or binary): pip
* TensorFlow version (use command below): 2.3.1
* Python version: 3.8.3
* Bazel version (if compiling from source):
* GCC/Compiler version (if compiling from source):
* CUDA/cuDNN version: CUDA 10.1.243, cuDNN 7.6.4 
* GPU model and memory: 2x 1080 Ti 10Gb

Code:
```
Import tensorflow as tf
import object_detection.models.keras_models.resnet_v1
import object_detection.models.feature_map_generators
PATH_TO_MODEL = ‘./saved_model/‘
model = tf.keras.models.load_model(PATH_TO_MODEL)
```

I can load and make predictions with
```
model = tf.saved_model.load(PATH_TO_MODEL)
tf_out = model(inputs)
```
However I wish to load the saved model so that I can edit it and then export it with coreML.

**Comment by bhack** [comment] 2020-10-13 15:44
Check also https://github.com/tensorflow/models/issues/8990#issuecomment-665672274

**Comment by rfourdinier** [comment] 2020-10-14 11:58
I have the exact same problem @hlloydt

I can load my saved model with tf and predict with it but i cannot load it with keras in order to save it in .h5

**Comment by redienP** [comment] 2020-10-26 07:54
> I have the exact same problem @hlloydt
> 
> I can load my saved model with tf and predict with it but i cannot load it with keras in order to save it in .h5

Same here

**Comment by tibbe** [comment] 2020-12-11 20:37
Also fails with another model:

```
import os
import tensorflow as tf
path = os.path.join('.', 'models', 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8', 'saved_model')
base_model = tf.keras.models.load_model(path)
```

**Comment by duffjay** [comment] 2020-12-26 17:19
I have same problems.   Is there some other way to convert a saved_graph.pb to a frozen inference graph in TF 2.4?

**Comment by duffjay** [comment] 2021-01-05 20:41
so what is the workaround to using Keras?   go through the colab tutorials:  
tensorflow/models/research/object_detection/colab_tutorials/

Specifically, go through: inference_from_saved_model_tf2_colab.ipynb
With minor edits, this will run locally - you don't have to run on colab.    This works well and it will show you the pattern for utilizing your model without the Keras problems.

**Comment by Saduf2019** [comment] 2021-01-15 09:51
@NguyenHongSon1103 
Is this still an issue.

**Comment by gytdau** [comment] 2021-01-16 22:09
Does reverting to an older version of tensorflow fix this issue as a workaround?

**Comment by Yonma** [comment] 2021-01-20 08:32
There's a workaround works for me: 

**My model setting:**
**Model_type: keras subclassed model**
**Save_way: used model.save() to save**
**Load_way: used tf.keras.models.load_model() to load.**

**MY Error raised in:** tensorflow\python\keras\saving\saved_model\load.py line_1067 (or around)

**I changed the original code:**

```
  spec = fn.concrete_functions[0].structured_input_signature[0][0]
  for concrete in fn.concrete_functions[1:]:
    spec2 = concrete.structured_input_signature[0][0]
    spec = nest.map_structure(common_spec, spec, spec2)
  return spec
```

to:

```
  spec = None
  if len(fn.concrete_functions) > 0:
    spec = fn.concrete_functions[0].structured_input_signature[0][0]
  for concrete in fn.concrete_functions[1:]:
    spec2 = concrete.structured_input_signature[0][0]
    spec = nest.map_structure(common_spec, spec, spec2)
  return spec
```

What I met was a error induced by the **fn.concrete_functions** which lets **the code run twice**, I haven't dig into python and tensorflow so I don't know how could it be like this, but **the first time the above part has a length of 4 (in my case), while at the second time it has a length of 0. So here maybe where the question is.**

I used
```
print(len(fn.concrete_functions))
print(type(fn.concrete_functions))
```
for test, it turns out to:

4, list, 0, list

roughly, but just like this. (If anyone know what's this is, I'd appreciate it if you tell me sth about it **: )**

Wish I could help you guys to sovle your problem.

**Comment by ValerianGonnot** [comment] 2021-02-11 10:04
The workaround doesn't work anymore in tf 2.4.1 as the error is not in the same location / block of code

**Comment by KA0335** [comment] 2021-02-14 22:28
So can anyone please share the final code as to how we can convert our .pb file to .tflite or CoreML...I have trained the model and now just need to convert the .pb file

**Comment by JanderHungrige** [comment] 2021-02-22 16:38
same problem here with ssd_mobilenetV2 and TF2.4
I tried to convert with 
`converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model('./exported-models/my_model_f32/saved_model')`
and 
`converter = tf.lite.TFLiteConverter.from_saved_model('./exported-models/my_model_f32/saved_model')`
which both failed.

**Comment by lefumathannah** [comment] 2021-03-02 13:26
Exact same error here with ssd_mobilenet_v2_fpnlite_320x320 trained with tensorflow object detection api. Tensorflow= 2.4.1.
Might not solve everyone's problem but you can load it with tf:
`model = tf.saved_model.load(path)`

**Comment by monicadsong** [comment] 2021-03-08 16:53
I confirmed that the gist `model = tf.keras.models.load_model('/content/saved_model')` which @amahendrakar provided works with tf.nightly: https://colab.research.google.com/gist/amahendrakar/3b0f693fb11f924a27c019d3f4d86106/43527-tf-nightly.ipynb.

I am closing this issue now, as I believe it is now fixed.

**Closed by monicadsong** 2021-03-08 16:53 UTC
Labels: TF 2.3, comp:keras, stat:awaiting tensorflower, type:bug

**Comment by abrarum** [comment] 2021-03-20 18:23
The issue still persists.

**Comment by monicadsong** [comment] 2021-03-22 15:56
Hi @abrarum --

(1) Is the index error still present in TF-nightly? I wasn't clear earlier, but the issue would still be in `2.4.1.`, so you will have to use TF-nightly until TF 2.5 is released to overcome this bug.

(2) For your new error, can you file a new issue please? Thanks!

**Comment by danishansari** [comment] 2021-11-08 06:29
I am getting a similar error in TF2.6, cuda-10.2 has anyone been able to fix it.
2021-11-04 16:06:55.345573: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.349826: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.350105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.350528: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-04 16:06:55.350809: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.351071: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.351302: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.766650: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.766916: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.767136: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-04 16:06:55.767349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2440 MB memory: → device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
Traceback (most recent call last):
File “scripts/convert_saved_model_trt_engine.py”, line 20, in
converter.convert()
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py”, line 1096, in convert
self._saved_model = load.load(self._input_saved_model_dir,
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py”, line 864, in load
result = load_internal(export_dir, tags, options)[“root”]
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py”, line 902, in load_internal
loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py”, line 162, in init
self._load_all()
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py”, line 259, in _load_all
self._load_nodes()
File “/home/hexa/miniconda3/envs/TRT/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py”, line 448, in _load_nodes
slot_variable = optimizer_object.add_slot(
AttributeError: ‘_UserObject’ object has no attribute ‘add_slot’
