### ISSUE TITLE
How to add "TFLite_Detection_Postprocess" op in Keras model when using tf2.x

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/tensorflow#34857] opened 2019-12-05 08:33 UTC
In tf1.x, I used `export_tflite_ssd_graph.py` function in the `object_detection` module to convert model adding`TFLite_Detection_Postprocess` op, but now, I write model use Keras in tf2.x, and there are no documents to tell how to do the conversion.

**Comment by jvishnuvardhan** [comment] 2019-12-06 21:11
@JoelTsui Do you have any model that you want to convert? There is a [`new expeimental_new_converter`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/experimental_new_converter) that you could try.

Please let us know more details and a standalone code to reproduce the issue. Thanks!

**Comment by JoelTsui** [comment] 2019-12-08 12:13
The problem is not about "convert", but about adding `TFLite_Detection_Postprocess` op when converting

**Comment by jvishnuvardhan** [comment] 2019-12-09 20:14
@JoelTsui Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-12-16 19:16
@JoelTsui Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-12-18 22:59
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-12-18 22:59 UTC
Labels: TF 2.0, comp:lite, stat:awaiting response, type:support
