### ISSUE TITLE
Placeholder shape checking inside tf.cond not properly enforced

### ISSUE THREAD

**Issue by Novak3** [tensorflow/tensorflow#18708] opened 2018-04-19 23:00 UTC
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Tensorflow 1.7 Docker under CentOS 7.3
- **TensorFlow installed from (source or binary)**: Tensorflow 1.7 Docker
- **TensorFlow version (use command below)**:  1.7
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:  N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Quadro M4000
- **Exact command to reproduce**:

### Describe the problem
When a placeholder is defined in a tf.cond statement, shape checking is not enforced until the merge, and ends up being only rank checking.

### Source code / logs
 Consider the following toy graph/session, developed in the pursuit of a larger issue.  I suspect this entire approach of trying to have differently shaped placeholders is doomed to failure.  But, the graph produced clearly shows placeholders of appropriate shape inside the conditional; shows appropriately sized tensors flowing into the merge, but shows the merge itself as shape (?,?) and that is where the shape checking happens.  As a result, you can put just about any rank two tensor in and set the boolean to anything you like and tensorflow doesn't care. 

Heck, you can make another op completely outside the conditional to compute matmul (a, matrix_inverse(a)) and it'll chug merrily along. 

Is this the desired behavior?  

```
with graph.as_default():
    pred   = tf.placeholder(tf.bool, shape=[])

    def fnTrue():
        a      = tf.placeholder(tf.float32, shape=[5, 1], name="column")
        return a

    def fnFalse():
        a      = tf.placeholder(tf.float32, shape=[1, 5], name="row")
        return a

    a = tf.cond(pred, fnTrue, fnFalse, name="my_conditional")
graphWriter = tf.summary.FileWriter(logdir='logdir', graph=graph)
graphWriter.flush()

with tf.Session(graph=graph) as session:
    writer_graph         = tf.summary.FileWriter(LogPath , session.graph)
    writer_graph.flush()
    writer_graph.close()
    plTrue       = np.ones((15, 2)) * 2     # column
    plFalse      = np.ones((12, 15)) * 3     # row
    feed_dict = {
        a            : plTrue,
        pred         : False
    }

    d = session.run( a , feed_dict = feed_dict)
    print(d)
    print(d.shape)
```

**Comment by michaelisard** [comment] 2018-04-24 23:40
Sorry, but I'm not completely sure what you are asking. I think it is the intended behavior that the two branches of a conditional may return differently-shaped tensors. This is in general supported in TF control flow, for example loop-carried state may be of a different shape every time around a loop, e.g., a loop may add a row to a tensor each time around.

I think the shape inference is working as expected, in that given the two placeholders, the 'merge' of their shapes constraints is the constraint that the output is rank 2.

If you build a conditional with branches outputting different shapes, then shape checking becomes a dynamic property that the TensorFlow interpreter will enforce, not something that is checked before the graph is run.

Does that make sense? What are you hoping for here?

**Comment by Novak3** [comment] 2018-04-25 00:08
Agreed, conditionals returning different possible shapes is desirable.  That's what I was trying to do. 

But surely a placeholder of shape [1,5] should not accept a tensor of shape [12,15], inside a conditional or no.

**Comment by michaelisard** [comment] 2018-04-25 03:53
Sorry that I hadn't looked carefully enough at your example.

The reason for the counterintuitive behavior is that you aren't feeding either of the placeholders in your example. You are feeding 'a' in the outer scope, which is returned by the tf.cond and is I guess a Merge node (you can verify this by printing its name and looking at the graph to find it).

You could feed the placeholders e.g., by capturing them while the lambdas execute, something like:

```
      p_list = []

      def fnTrue():
        a      = tf.placeholder(tf.float32, shape=[5, 1], name="column")
        p_list.append(a)
        return a

    def fnFalse():
        a      = tf.placeholder(tf.float32, shape=[1, 5], name="row")
        p_list.append(a)
        return a
 ...

    feed_dict = {
        p_list[0]    : plTrue,
        p_list[1]    : plFalse,
        pred         : False
    }
```

I think if you do that you should get the shape error from the placeholders.

Instead you are feeding the Merge, which (as you observe) is only constrained to have rank 2. The most precise shape constraint on the Merge is "either [5,1] or [1,5]" which our shape inference system is not rich enough to encode, and I don't think it's realistic to make it encode arbitrary expressions like that, so it's probably going to stay at this level of imprecision.

I wonder from your example if you think that feeding False to p should constrain the Merge to have shape [1,5]. Unfortunately it doesn't, because of the way that graph pruning works in TensorFlow. The algorithm is to look at all the fetches (in this case a) and work backwards from them only as far as necessary to evaluate them given the supplied feeds (in this case a and p). Since a can be computed given a, the pruned graph that is evaluated by the session.run() call is just the singleton node a, and the value of p is ignored. You should also know that the pruning algorithm is based on the identity of the feed and fetch nodes, not the values sent to the feeds, so in the case I gave where I fed the placeholders it would be necessary to feed both placeholders in every run: the set of feeds required to evaluate the graph is determined before the value of p is known, so it has to include both branches.

There is no doubt that the algorithm for determining which nodes are evaluated given a set of feeds and fetches has confused a lot of people. At this point, however, it's probably not going to change given the amount of code that has been built, so I hope that you can solve your problem based on this explanation of the graph pruning process.

**Comment by tensorflowbutler** [comment] 2018-05-10 12:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by michaelisard** [comment] 2018-05-17 21:59
Closing for now but please reopen if there's a bug that needs to be looked at.

**Closed by michaelisard** 2018-05-17 21:59 UTC
Labels: stat:awaiting response
