### ISSUE TITLE
tf dataset cache behave differently with filter for TF 1.x

### ISSUE THREAD

**Issue by hardianlawi** [tensorflow/tensorflow#37963] opened 2020-03-27 05:04 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: NA
- TensorFlow installed from (source or
binary): binary (pip)
- TensorFlow version (use command below): v1.15.0-rc3-22-g590d6eef7e 1.15.0
- Python version: - Bazel
version (if compiling from source): NA
- GCC/Compiler version (if compiling from
source): NA
- CUDA/cuDNN version: - GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When applying filter before cache on `tf.data.Dataset`, the outputs when caching to file compared to caching to memory are different.

**Describe the expected behavior**

They should be the same.

TF 2x is working as expected.

**Standalone code to reproduce the issue** 

Cache to memory
```python
import tensorflow as tf

tf.enable_eager_execution()

data = tf.data.Dataset.from_tensor_slices(list(range(50)))
data = data.filter(lambda x: tf.random.uniform([]) < 0.5)
data = data.cache()

outputs = [x for x in data]
outputs_1 = [x for x in data]

assert len(outputs) == len(outputs_1)

for x, y in zip(outputs, outputs_1):
    assert x.numpy() == y.numpy()
```

Cache to file
```python
import tensorflow as tf

tf.enable_eager_execution()

data = tf.data.Dataset.from_tensor_slices(list(range(50)))
data = data.filter(lambda x: tf.random.uniform([]) < 0.5)
data = data.cache('/tmp/dummy_data')

outputs = [x for x in data]
outputs_1 = [x for x in data]

assert len(outputs) == len(outputs_1)

for x, y in zip(outputs, outputs_1):
    assert x.numpy() == y.numpy()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-03-27 10:40
Was able to reproduce the issue with TF 1.15.2. Please find the Gist [here](https://colab.research.google.com/gist/amahendrakar/7714f97c7adc37db9f361bdc40fe9f5a/37963.ipynb). Thanks!

**Comment by thisisandreeeee** [comment] 2020-03-31 07:09
Hi, I am facing a similar issue and I've managed to replicate the problem too. Is there a fix for this?

**Comment by jsimsa** [comment] 2020-03-31 18:01
In TF 1, `cache` does not work with eager iteration (i.e. `from elem in dataset`). You should either use TF 2 or append `repeat` to the end of your dataset consume multiple epochs.

**Closed by jsimsa** 2020-03-31 18:01 UTC
Labels: TF 1.15, comp:data, type:bug

**Comment by hardianlawi** [comment] 2020-04-01 15:02
Hi @jsimsa, thank you for your reply. I tried replicating it in non-eager and still experienced the same issue.

Why are you saying that `cache` does not work with eager mode in TF 1? By "does not work", do you mean it will not behave properly?

**Comment by jsimsa** [comment] 2020-04-01 16:25
In TF 1, memory-based `cache` only support reuse through subsequent `repeat`. This is because the implementation uses an in-memory cache that is owned by the iterator and thus different iterators will have different caches. This is not an issue for file-based caches because different iterators can access the same file-based cache.

This is fixed in TF 2 where a single in-memory `cache` is shared among all iterators created for a dataset.
