### ISSUE TITLE
memory leak in tf.keras.Model.predict

### ISSUE THREAD

**Issue by plooney** [tensorflow/tensorflow#44711] opened 2020-11-09 21:36 UTC
https://stackoverflow.com/questions/64199384/tf-keras-model-predict-results-in-memory-leak

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by plooney** [comment] 2020-11-09 21:37
https://stackoverflow.com/questions/64199384/tf-keras-model-predict-results-in-memory-leak

Seems to be an issue with tf.keras.Model.predict

**Comment by ravikyram** [comment] 2020-11-10 01:23
I have tried in TF GPU with version [2.3 gist](https://colab.research.google.com/gist/ravikyram/c9430bc7667e6299feaeab3b905418f7/untitled501.ipynb) ,nightly version(`2.5.0-dev20201109`) [gist](https://colab.research.google.com/gist/ravikyram/bf1336b625d9c416c9838280e162247c/untitled502.ipynb) and was able to reproduce the issue.Thanks!

**Comment by jvishnuvardhan** [comment] 2020-11-10 04:17
@plooney `model.predict` is a high-level API which is designed for batch-predicting outside of any loops. It automatically wraps your model into a tf.function and maintains graph based execution. Which means, if there is any change in input signature (`shape` and `dtype`) to that function (here model.predict), then it traces multiple models instead of a single model as you are expecting.

In your case, `inImm` is a numpy input which is considered as different signature each time you provide it in a for loop to a function wrapped by tf.function. However, providing `inImm` as a tensor will result in same input signature and hence there is a single graph to which these inputs are fed and results are obtained. In the numpy case, there are 60 static graphs (which is not what you want). As there are many static graphs, the memory is increasing with each for loop iteration.

When I added one line in your code, the code is not crashing. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/36ebe9b17279c12ac26cc6f171eb125b/untitled502.ipynb). Thanks!


`inImm=tf.convert_to_tensor(inImm)`


Please read [1](https://github.com/tensorflow/tensorflow/issues/40261), [2](https://www.tensorflow.org/guide/function], and [3](https://github.com/tensorflow/tensorflow/issues/40708#issuecomment-653823716). These resources will help you more. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by bhack** [comment] 2020-11-12 19:51
@jvishnuvardhan Predict in a loop it is a quite recurrent issue, I remember some weeks ago I've just triaged two of this tickets. 
How we could better expose this in the docs? /cc @lamberta @MarkDaoust

**Comment by jvishnuvardhan** [comment] 2020-11-12 20:00
@bhack Good point. I think updating one of the docs (tutorial/guides) would help resolving this kind of issues. Thanks!

**Comment by bhack** [comment] 2020-11-12 20:02
@jvishnuvardhan Yes we need to find a quite popular entry point in the Docs if any internal team member has some stats about Docs page views.

**Comment by bhack** [comment] 2020-11-12 20:04
Also some more specific "entry level" warning (instead of the generic function retracing) could be very useful for newcomers.

**Comment by MarkDaoust** [comment] 2020-11-13 19:46
@jvishnuvardhan thanks for the clear explanation. If this were calling a `tf.function` in a loop that would be 100% the correct answer. But `Model.predict` manages some of this to avoid this problem (in general keras fit/evaluate/predict never require that the user convert inputs to tensors). It looks like something more complicated is happening.

The first two clues that suggest it are:

1. It's not printing the frequent retracing warning.
2. You're creating a single numpy array and passing that multiple times and it still goes OOM. Except for constants the caching logic is based on object identity, re-using the object should reuse the same function trace.

Investigating a little farther you can find the `model.predict_function` is the `@tf.function` that runs in here.
Inspecting that, both it's `._list_all_concrete_functions()` and `.pretty_printed_concrete_signatures()` show that there is only one graph, and predict is handling the conversion of the numpy array to a Tensor.

So I agree that this is leaking memory somewhere. But I've confirmed that it's not the `tf.function` cache causing it.

@tomerk, you're pretty familiar with this code, do you have any ideas?

**Comment by bhack** [comment] 2020-11-13 20:40
I've just modified the original stackoverflow mentioned code for Colab:
```
pip install --upgrade memory_profiler
```

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Input,Conv2D, Activation

%load_ext memory_profiler

matrixSide = 512 #define a big enough matrix to give memory issues

inputL = Input([matrixSide,matrixSide,12]) #create a toy model
l1 = Conv2D(32,3,activation='relu',padding='same') (inputL) #120
l1 = Conv2D(64,1,activation='relu',padding='same')(l1)
l1 = Conv2D(64,3,activation='relu',padding='same')(l1)
l1 = Conv2D(1,1,padding='same')(l1)
l1 = Activation('linear')(l1)
model = tf.keras.Model(inputs= inputL,outputs = l1)


#run predictions
inImm = np.zeros((64,matrixSide,matrixSide,12))
for i in range (60):
  print(i)
  %memit outImm = model.predict(inImm)
```

**Comment by bhack** [comment] 2020-11-13 20:55
```
peak memory: 5729.88 MiB, increment: 3190.20 MiB
1
peak memory: 6498.93 MiB, increment: 769.06 MiB
2
peak memory: 6499.14 MiB, increment: 0.21 MiB
3
peak memory: 6499.14 MiB, increment: 0.00 MiB
4
peak memory: 6499.14 MiB, increment: 0.00 MiB
5
peak memory: 6499.15 MiB, increment: 0.00 MiB
6
peak memory: 6499.17 MiB, increment: 0.02 MiB
7
peak memory: 6499.17 MiB, increment: 0.00 MiB
8
peak memory: 6499.17 MiB, increment: 0.00 MiB
9
peak memory: 6499.17 MiB, increment: 0.00 MiB
10
peak memory: 6499.17 MiB, increment: 0.00 MiB
11
peak memory: 6499.17 MiB, increment: 0.00 MiB
12
peak memory: 6499.18 MiB, increment: 0.01 MiB
13
peak memory: 6499.18 MiB, increment: 0.00 MiB
14
peak memory: 6499.19 MiB, increment: 0.00 MiB
15
peak memory: 6499.19 MiB, increment: 0.00 MiB
16
peak memory: 6499.19 MiB, increment: 0.00 MiB
17
peak memory: 6499.19 MiB, increment: 0.00 MiB
18
peak memory: 6499.19 MiB, increment: 0.00 MiB
19
peak memory: 6499.19 MiB, increment: 0.00 MiB
20
peak memory: 6499.19 MiB, increment: 0.00 MiB
21
peak memory: 6499.19 MiB, increment: 0.00 MiB
22
peak memory: 6499.19 MiB, increment: 0.00 MiB
23
peak memory: 6499.19 MiB, increment: 0.00 MiB
24
peak memory: 6499.19 MiB, increment: 0.00 MiB
25
peak memory: 6499.19 MiB, increment: 0.00 MiB
26
peak memory: 6499.19 MiB, increment: 0.00 MiB
27
peak memory: 6499.19 MiB, increment: 0.00 MiB
28
peak memory: 6499.19 MiB, increment: 0.00 MiB
29
peak memory: 6499.19 MiB, increment: 0.00 MiB
30
peak memory: 6499.19 MiB, increment: 0.00 MiB
31
peak memory: 6499.19 MiB, increment: 0.00 MiB
32
peak memory: 6499.19 MiB, increment: 0.00 MiB
33
peak memory: 6499.19 MiB, increment: 0.00 MiB
34
peak memory: 6499.19 MiB, increment: 0.00 MiB
35
peak memory: 6499.19 MiB, increment: 0.00 MiB
36
peak memory: 6499.19 MiB, increment: 0.00 MiB
37
peak memory: 6499.19 MiB, increment: 0.00 MiB
38
peak memory: 6499.19 MiB, increment: 0.00 MiB
39
peak memory: 6499.19 MiB, increment: 0.00 MiB
40
peak memory: 6499.19 MiB, increment: 0.00 MiB
41
peak memory: 6499.19 MiB, increment: 0.00 MiB
42
peak memory: 6499.19 MiB, increment: 0.00 MiB
43
peak memory: 6499.19 MiB, increment: 0.00 MiB
44
peak memory: 6499.19 MiB, increment: 0.00 MiB
45
peak memory: 6499.19 MiB, increment: 0.00 MiB
46
peak memory: 6499.19 MiB, increment: 0.00 MiB
47
peak memory: 6499.19 MiB, increment: 0.00 MiB
48
peak memory: 6499.19 MiB, increment: 0.00 MiB
49
peak memory: 6499.20 MiB, increment: 0.00 MiB
50
peak memory: 6499.20 MiB, increment: 0.00 MiB
51
peak memory: 6499.20 MiB, increment: 0.00 MiB
52
peak memory: 6499.20 MiB, increment: 0.00 MiB
53
peak memory: 6499.20 MiB, increment: 0.00 MiB
54
peak memory: 6499.20 MiB, increment: 0.00 MiB
55
peak memory: 6499.20 MiB, increment: 0.00 MiB
56
peak memory: 6499.20 MiB, increment: 0.00 MiB
57
peak memory: 6499.20 MiB, increment: 0.00 MiB
58
peak memory: 6499.20 MiB, increment: 0.00 MiB
59
peak memory: 6499.20 MiB, increment: 0.00 MiB
```

**Comment by MarkDaoust** [comment] 2020-11-13 21:45
It doesn't OOM with memory_profiler running because `%meit` calls `gc.collect`: 

https://github.com/pythonprofilers/memory_profiler/blob/bd6da910f791cef725640fa207fb4ee433c93586/memory_profiler.py#L1060

If you add a `gc.collect` there it continues as well. It you monkey-patch out `gc.collect` then you get the explosive memory growth.

So that points this towards an issue with cyclical-garbage not getting cleaned up fast enough.

**Comment by bhack** [comment] 2020-11-13 22:06
> So that points this towards an issue with cyclical-garbage not getting cleaned up fast enough.

Yes It was one of the suspects

**Comment by bhack** [comment] 2020-11-13 23:22
Also at step `0`
`outImm = model(inImm)`

```
ResourceExhaustedError: OOM when allocating tensor with shape[64,512,512,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BiasAdd]
```

**Comment by tomerk** [comment] 2020-12-01 03:05
So, random thoughts (I re-opened just to leave these)

1. as mentioned above, `predict` shouldn't be used in a loop. Sad things happen if you do. Ideally use model call w/ training=False directly (manually wrapping your model call in a tf.function if needed for performance reasons)

2. Numpy inputs to predict/fit/evaluate get converted to tf.data datasets then iterated over. The specific conversion implementation in place currently ends up copying the data and is poorly suited for large input sizes (it is prone to ooms for large inputs). There's a number of other github issues related to this floating around, but we have so far been unable to prioritize this in core Tensorflow. If you need performant numpy input to keras fit/evaluate/predict my current recommendation is using Tensorflow-io's numpy inputs: https://www.tensorflow.org/io/api_docs/python/tfio/experimental/IODataset#from_numpy because it should be more performant and avoid excess memory copies.

3. The fact that gc.collect fixes this makes me think something about the numpy conversion is also creating cyclical references that the python gc doesn't trigger for (the memory is consumed by the gpu which isn't tracked by the python gc, so the python gc fails to trigger because it thinks there's still plenty of memory). We've seen cyclical issues like this cause issues elsewhere (e.g. when creating multiple models), but due to the two aforementioned points we don't have the bandwidth right now to prioritize tracking down & fixing this specific one.

**Closed by tomerk** 2020-12-01 03:05 UTC
Labels: TF 2.3, comp:keras, stalled, stat:awaiting response, type:performance

**Comment by yichenj** [comment] 2021-03-16 08:15
> Also at step `0`
> `outImm = model(inImm)`
> 
> ```
> ResourceExhaustedError: OOM when allocating tensor with shape[64,512,512,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BiasAdd]
> ```

Hi, I am wondering what this mean? Cannot solve the OOM issue even if using model.__call__ directly ?
What is the workaround for this problem?

**Comment by MarkDaoust** [comment] 2021-03-16 17:28
>> 64*64*512*512*4/2**30
4.0

That 1 tensor is 4GB. Have you tried a smaller batch size?

**Comment by yichenj** [comment] 2021-03-17 05:28
So? I understand the OOM of GPU is because the GPU memory is too small. It means it is not the same issue with the leakage problem. The bug i met is that after 7 hours of running model.predict() in a loop, there is a GPU OOM.

**Comment by lukeconibear** [comment] 2023-01-06 12:04
In case this helps:

If the dataset can fit in memory, then the following functions can replace the call to `model.predict`:

```python
def generate_batches(
    x: np.ndarray | tf.Tensor, batch_size: int = 32
) -> np.ndarray | tf.Tensor:
    """Generate batches of test data for inference.

    Args:
        x (np.ndarray | tf.Tensor):
            Full test data set.
        batch_size (int, default=32):
            Batch size.

    Yields:
        np.ndarray | tf.Tensor:
            Yielded batches of test data.
    """
    for index in range(0, x.shape[0], batch_size):
        yield x[index : index + batch_size]


def predict(
    model: tf.keras.Model,
    x: np.ndarray | tf.Tensor,
    batch_size: int = 32,
) -> np.ndarray:
    """Predict using generated batched of test data.

    - Used instead of model.predict() due to memory leaks.
    - https://github.com/tensorflow/tensorflow/issues/44711

    Args:
        model (tf.keras.Model):
            The model to use for prediction.
        x (np.ndarray | tf.Tensor):
            Full test data set.
        batch_size (int, default=32):
            Batch size.

    Returns:
        np.ndarray:
            Predictions on the test data.
    """
    y_batches = []
    for x_batch in generate_batches(x=x, batch_size=batch_size):
        y_batch = model(x_batch, training=False).numpy()
        y_batches.append(y_batch)

    return np.concatenate(y_batches)


# instead of
# y_pred = model.predict(x_test)

# use
y_pred = predict(model=model, x=x_test, batch_size=32)
```

Else, if the dataset does not fit in memory, then consider using [`tf.data`](https://www.tensorflow.org/guide/data):
```python
def create_tf_dataset(
    data_split: str,
    x: np.ndarray,
    y: np.ndarray,
    batch_size: int,
    use_mixed_precision: bool,
) -> tf.data.Dataset:
    """Create a TensorFlow dataset.

    - Cache train data before shuffling for performance (consider full dataset size).
    - Shuffle train data to increase accuracy (not needed for test data).
    - Batch train data after shuffling for unique batches at each epoch.
    - Cache test data after batching as batches can be the same between epochs.
    - End pipeline with prefetching for performance.
    
    Args:
        data_split (str):
            The data split to create the dataset for.
            Supported are "train", "validation", and "test".
        x (np.ndarray):
            The feature data.
        y (np.ndarray):
            The target data.
        batch_size (int):
            The batch size.
        use_mixed_precision (bool):
            Whether to use mixed precision.

    Raises:
        ValueError: If the data split is not supported.

    Returns:
        tf.data.Dataset:
            The TensorFlow dataset.
    """
    if data_split not in {"train", "validation", "test"}:
        raise ValueError(f"Invalid data split: {data_split}")

    if use_mixed_precision:
        tf.keras.mixed_precision.set_global_policy("mixed_float16")
        x = x.astype(np.float16)
        y = y.astype(np.float16)

    ds = tf.data.Dataset.from_tensor_slices((x, y))

    if data_split in {"train", "validation"}:
        ds = ds.cache()
        set_random_seed(seed=RANDOM_SEED)
        ds = ds.shuffle(number_of_samples, seed=RANDOM_SEED)
        ds = ds.batch(batch_size)
    else:
        ds = ds.batch(batch_size)
        ds = ds.cache()

    ds = ds.prefetch(AUTOTUNE)

    return ds


ds_test = create_tf_dataset(
    data_split="test",
    x=x_test,
    y=y_test,
    batch_size=32,
    use_mixed_precision=True,
)
y_pred = model.predict(ds_test)
```

**Comment by CryptoSurff** [comment] 2023-04-14 01:17
@lukeconibear worked for me thank you!

**Comment by MichaelBreslavskyNintex** [comment] 2023-07-03 10:51
I had the same issue with '.predict', running on about 50,000 inputs over several hours, seen a leak of around 0.35 GB. Traced the leak back to the '.predict' method. Tried replacing it with the '__call__' method, which solved the memory leak but was slower by about 50%.
