### ISSUE TITLE
Decoding JPEGs much slower on Windows

### ISSUE THREAD

**Issue by LucasSloan** [tensorflow/tensorflow#34113] opened 2019-11-09 00:43 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15.0 GPU
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0/7.6.5
- GPU model and memory: 2080 Ti

My input pipeline is much slower on Windows than Linux.  On Linux, I'm using 10% of my CPU (Threadripper 2950x), to parse 1000 640x480 images per second.  On Windows, I'm using 85% of my CPU to parse 300 640x480 images per second.  I found [this TODO](https://github.com/tensorflow/tensorflow/blob/4b628e8a154c4fbd74ed13d3284fb887a5103e41/tensorflow/core/lib/jpeg/jpeg_mem.cc#L438), which suggests that the issue is that the windows builds of Tensorflow don't use libjpeg-turbo.  I dug a little and found [this issue](https://github.com/tensorflow/tensorflow/issues/4807) and [this PR](https://github.com/tensorflow/tensorflow/pull/5547), which covers the discussion of using libjpeg-turbo, but neither mention any issues with Windows.

Is it possible to use libjpeg-turbo on Windows?

**Comment by jvishnuvardhan** [comment] 2019-11-13 19:21
@LucasSloan Can you please share a simple standalone code to reproduce the issue? Also, did you notice any similar  issue with GPU? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-11-20 21:53
@LucasSloan Did you had any time to prepare simple standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-11-26 18:23
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-11-26 18:23 UTC
Labels: TF 1.15, comp:ops, stat:awaiting response, type:performance
