### ISSUE TITLE
ValueError: '-_Loss/Const' is not a valid node name

### ISSUE THREAD

**Issue by elfadly** [tensorflow/tensorflow#8105] opened 2017-03-05 21:34 UTC
I am trying to build a network using tflearn library and tensorflow v.1, and I got this error 

**error**
Scipy not supported!
[+] Building CNN
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 169, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1220, in __init__
    raise ValueError("'%s' is not a valid node name" % node_def.name)
ValueError: '-_Loss/tags' is not a valid node name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emotion_recognition.py", line 101, in <module>
    import poc
  File "C:\Users\Mohamed\Desktop\Capstone Project\emotion-recognition-neural-networks-master\poc.py", line 46, in <module>
    network.build_network()
  File "C:\Users\Mohamed\Desktop\Capstone Project\emotion-recognition-neural-networks-master\emotion_recognition.py", line 42, in build_network
    tensorboard_verbose = 2
  File "C:\Program Files\Python35\lib\site-packages\tflearn\models\dnn.py", line 57, in __init__
    session=session)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 111, in __init__
    clip_gradients)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 561, in initialize_training_ops
    ema_num_updates=self.training_steps)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\summaries.py", line 243, in add_loss_summaries
    summaries_collection_key)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\summaries.py", line 46, in get_summary
    summ = tf.summary.scalar(tag, value)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\summary\summary.py", line 120, in scalar
    tags=scope.rstrip('/'), values=tensor, name=scope)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 281, in _scalar_summary
    name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 504, in apply_op
    values, as_ref=input_arg.is_ref).dtype.name
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 169, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1220, in __init__
    raise ValueError("'%s' is not a valid node name" % node_def.name)
ValueError: '-_Loss/Const' is not a valid node name

**Comment by prb12** [comment] 2017-03-06 17:47
Please provide details about what platform you are using  (operating system, architecture). Also include details of how you installed TensorFlow and the command lines necessary to reproduce your problem. We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by elfadly** [comment] 2017-03-06 23:20
OS: windows 10 64 bit
installed tensorflow using pip
I think the code I am trying to run is incomplete.

**Comment by prb12** [comment] 2017-03-07 19:25
> I think the code I am trying to run is incomplete.

Could you please explain this comment?

**Comment by asimshankar** [comment] 2017-04-04 07:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-04 07:59 UTC
Labels: stat:awaiting response
