### ISSUE TITLE
Support for LSTM and GRU

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#46389] opened 2021-01-13 06:46 UTC
Hello,

I wonder if there is support for LSTM and GRU within TensorFlow Lite for Microcontrollers (audio NN models) or any plan to have these operations? 

Thank you.

Best regards,
Peter

**Comment by amahendrakar** [comment] 2021-01-13 14:44
@peter197321,
Closing this issue as it is a duplicate of [#46390](https://github.com/tensorflow/tensorflow/issues/46390). Please feel free to re-open if mistaken. Thanks!

**Closed by amahendrakar** 2021-01-13 14:44 UTC
Labels: comp:micro
