### ISSUE TITLE
subclass of tf.keras.Model throws "NotImplementedError" when fit() with custom data

### ISSUE THREAD

**Issue by poedator** [tensorflow/tensorflow#43173] opened 2020-09-12 09:06 UTC
TF 2.3.0 tested on Windows and in Colab.

There is an error that comes out only when certain type of model (subclass of tf.keras.Model) is combined with certain custom dataloaders (Python generator and subclass of tf.keras.utils.Sequence). Yet same loaders work OK with simple Functional Keras model. 

the error is "**NotImplementedError: When subclassing the `Model` class, you should implement a `call` method**"

See Colab reproduction [here.](https://colab.research.google.com/drive/19hbGTk-RAjdHiUfM-cgDPMNTyu5FRIQf?usp=sharing)

**Comment by ravikyram** [comment] 2020-09-12 11:26
I have tried in colab with TF version 2.3, nightly versions(`2.4.0-dev20200912`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/578ba17757a9a9afc21e8659b65e2440/untitled338.ipynb#scrollTo=ucG1nfsXCABQ). Thanks!

**Comment by bhack** [comment] 2020-09-12 13:11
It is not a bug. You need to implement the `call` method in your class when sublcassing. (e.g. in your `class AE1` etc.):
See https://keras.io/guides/making_new_layers_and_models_via_subclassing/

**Comment by poedator** [comment] 2020-09-13 10:28
@bhack, thank you for the suggestion. I added `call()` to my test model and it works OK.  [Gist with working model here](https://colab.research.google.com/gist/poedator/21bb68a5b18b4766b9e45ebdc6f02781/tf_loader_issues.ipynb).

What I find confusing is:
1) some combinations of models and loaders work OK in my original example. Even without `call()` in my example the subclassed `Model` worked fine with `tf.data.Dataset.from_tensor_slices`
2) some examples at TF/Keras site do not use call() when subclassing models.
 Example: [VAE tutorial ](https://keras.io/examples/generative/vae/) by respectable @fchollet - he just feeds data directly to `Model.fit()` without loaders and everything works fine without `call()`. 

There are quite a few confused people out there trying to replicate Keras examples and struggling with this inconsistency (see [one](https://stackoverflow.com/questions/63832318/keras-using-a-generator-for-the-data-vae), [two](https://stackoverflow.com/questions/63822281/issue-with-modifying-a-keras-class-to-include-call-function)).
Perhaps some warnings should be made in the examples / documentations, promoting consistent use of `call()`, also see if any code changes are needed to ensure consistent enforcement of `call()` use.

**Comment by bhack** [comment] 2020-09-13 10:43
@poedator Cause It Is requested/checked for the `build` case.
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L320:L328

if you want to better notify developers about this please open a documentation PR on this doc string and also on https://github.com/keras-team/keras-io/blob/master/guides/making_new_layers_and_models_via_subclassing.py

Thanks

**Comment by poedator** [comment] 2020-09-23 10:38
[updated gist with issues demonstration](https://colab.research.google.com/gist/poedator/06e66814d0d914cfe65a70bd9595c98d/tf_loader_issues_without_call.ipynb)
opened [pull request](https://github.com/keras-team/keras-io/pull/258)

**Comment by MarkDaoust** [comment] 2020-09-23 13:41
I agree with the initial assessment, that this is more like a bug than a documentation issue.

1. If `call` were **required** it would be an abstract method, instead of just not-implemented.
2. Changing the data-source shouldn't cause this change in requirements.

Looking into it a little more I see that it's this line in `data_adaptor.GeneratorDataAdaptor` causing the inconsistency:

https://github.com/tensorflow/tensorflow/blob/5d5534edf7d0b73cb23f7069135d674e1d27250b/tensorflow/python/keras/engine/data_adapter.py#L787

@omalleyt12, WDYT? What's the right way to fix this?

**Comment by bhack** [comment] 2020-09-23 13:53
@MarkDaoust 
For 1. Do you mean that you want to decorate `@six.add_metaclass(abc.ABCMeta)` at :

https://github.com/tensorflow/tensorflow/blob/d0cc5dfc14765d4c1e00c65bcf47d81390e64332/tensorflow/python/keras/engine/training.py#L420

**Comment by MarkDaoust** [comment] 2020-09-23 14:14
> you want to decorate @six.add_metaclass(abc.ABCMeta) at: ...

I don't *want* it. I'm just pointing out that it isn't currently there, and it's not clear why fitting with a generator should require `call` (I see it's being used to `build` the model, but maybe there's a way around that).

**Comment by bhack** [comment] 2020-09-23 14:56
I don't know the full story of this but it seems to me that there is "you should" in the raised string and in other documentations entries.
So the logic it seems to me more related to the case when the user "voluntary"  invoke call. 

In the case of the generator instead this "direct" user control doesn't seems to me so explicit as it is a little bit hidden/internal.

**Comment by IoanTurturea** [comment] 2020-12-28 05:28
Thank you all for figuring out this problem. But what if the discussed problem comes out, when a class in not used? See this:

x_train, y_train = train_import()
train_dataset = tf.data.Dataset.zip((x_train, y_train))

input = Input((64,), name='input')
hidden = Dense(64, activation='relu', name='hidden_1')(input)
dropout = Dropout(0.2, name='dropout_1')(hidden)
hidden = Dense(32, activation='relu', name='hidden_2')(dropout)
dropout = Dropout(0.2, name='dropout_2')(hidden)
output = Dense(7, activation='softmax', name='output')(dropout)
model = Model(inputs=input, outputs=output)
model = Model()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# ERROR WHEN RUNNING THIS LINE:
accuracy = model.fit(train_dataset, batch_size=64, epochs=2048)
# "NotImplementedError: When subclassing the Model class, you should implement a call method"

**Comment by MarkDaoust** [comment] 2021-10-15 23:59
Francois fixed this here:

https://github.com/keras-team/keras/commit/d9abcd788e5419560c4d8bd47b22ec387fe5c9c2

It will be in TensorFlow 2.7 which will be released shortly.

**Closed by MarkDaoust** 2021-10-15 23:59 UTC
Labels: type:bug, comp:keras, TF 2.3

**Comment by RxstydnR** [comment] 2022-02-03 05:44
I solved this error by adding the following `call` method.
```python
 def call(self, data, training=False): 
        # You don't need this method for training.
        # So just pass.
        pass
```
