### ISSUE TITLE
convert to tflite failed using tf.lite.TFLiteConverter.from_saved_model and validate failed

### ISSUE THREAD

**Issue by glevenc** [tensorflow/tensorflow#35008] opened 2019-12-11 01:17 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
when i convert saved lstm tensorflow model to the tflite file and meets the error.
this is piece of code :
def create_LSTM_model(inputs):
    W = {
        
        'hidden': tf.Variable(tf.keras.backend.random_normal([N_FEATURES, N_HIDDEN_UNITS])),
        'output': tf.Variable(tf.keras.backend.random_normal([N_HIDDEN_UNITS, N_CLASSES]))
        'output': tf.Variable(init_w_output)
    }
    biases = {
        'hidden': tf.Variable(tf.keras.backend.random_normal([N_HIDDEN_UNITS], mean=1.0))
        'output': tf.Variable(tf.keras.backend.random_normal([N_CLASSES]))
    }

    X = tf.transpose(inputs, [1, 0, 2])
    X = tf.reshape(X, [-1, N_FEATURES])
    hidden = tf.nn.relu(tf.matmul(X, W['hidden']) + biases['hidden'])
    hidden = tf.split(hidden, N_TIME_STEPS, 0)

    def get_a_cell(lstm_size, keep_prob):
        lstm = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(lstm_size)
        drop = tf.compat.v1.nn.rnn_cell.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop

    # lstm_layers = [tf.compat.v1.nn.rnn_cell.BasicLSTMCell(N_HIDDEN_UNITS, forget_bias=1.0) for _ in range(2)]
    lstm_size = N_HIDDEN_UNITS
    keep_prob = 0.9
    num_layers = 2
    # lstm_layers = tf.compat.v1.nn.rnn_cell.MultiRNNCell([get_a_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    lstm_layers = tf.compat.v1.nn.rnn_cell.MultiRNNCell([get_a_cell(lstm_size, keep_prob) for _ in range(num_layers)])

    outputs, _ = tf.compat.v1.nn.static_rnn(lstm_layers, hidden, dtype=tf.float32)
    # keras.layers.RNN  outputs, _ = tf.keras.layers.RNN(lstm_layers, hidden, dtype=tf.float32)

    # Get output for the last time step
    lstm_last_output = outputs[-1]

    return tf.matmul(lstm_last_output, W['output']) + biases['output']

tf.compat.v1.reset_default_graph()

X = tf.compat.v1.placeholder(tf.float32, [None, N_TIME_STEPS, N_FEATURES], name="input_X")
Y = tf.compat.v1.placeholder(tf.float32, [None, N_CLASSES], name='input_Y')

pred_Y = create_LSTM_model(X)
tf.identity(pred_Y, name="pred_Y")

pred_softmax = tf.nn.softmax(pred_Y, name="pred_softmax")

train_count = len(X_train)
L2_LOSS = 0.0015

l2 = L2_LOSS * \
     sum(tf.nn.l2_loss(tf_var) for tf_var in tf.compat.v1.trainable_variables())

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred_Y, labels=Y)) + l2
# loss=tf.reduce_mean(tf.square(tf.reshape(pred,[-1,2])-tf.reshape(Y, [-1,2])))
tf.identity(loss, name="saved_loss")

global_step = tf.Variable(0, trainable=False, name='global_step')

learning_rate = tf.compat.v1.train.exponential_decay(
    LEARNING_RATE_BASE,
    global_step,
    train_count / BATCH_SIZE, LEARNING_RATE_DECAY)

tf.identity(learning_rate, name="learning_rate")

optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss, global_step=global_step)
tf.identity(loss, name="saved_optimizer")

correct_pred = tf.equal(tf.argmax(pred_softmax, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, dtype=tf.float32), name='output_accuracy')

history = dict(train_loss=[],
               train_acc=[],
               test_loss=[],
               test_acc=[])

sess = tf.compat.v1.InteractiveSession()
sess.run(tf.compat.v1.global_variables_initializer())

export_simple_path = 'model_simple/'
if os.path.exists(export_simple_path):
    shutil.rmtree(export_simple_path)

tf.compat.v1.saved_model.simple_save(sess,
            export_simple_path,
            inputs={"input_X": X},
            outputs={"pred_softmax": pred_softmax})
use this to save the model
and then i convert the .pb model to tflite with python API

import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
but got the error:
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, FULLY_CONNECTED, GREATER_EQUAL, LOGISTIC, MUL, SOFTMAX, SPLIT, TANH. Here is a list of operators for which you will need custom implementations: RandomUniform.
Traceback (most recent call last):
  File "c:\users\d\.conda\envs\ai\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\d\.conda\envs\ai\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\d\.conda\envs\ai\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\d\.conda\envs\ai\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\d\.conda\envs\ai\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, FULLY_CONNECTED, GREATER_EQUAL, LOGISTIC, MUL, SOFTMAX, SPLIT, TANH. Here is a list of operators for which you will need custom implementations: RandomUniform.

and then i add the
converter.allow_custom_ops=True

then i can convert to tflite (lstm.tflite) successfully
but then i use below command to validate my model then i got the errors:

interpreter = tf.lite.Interpreter(model_path="lstm.tflite")

interpreter.allocate_tensors()

>>> interpreter = tf.lite.Interpreter(model_path="D:\Feature\model_simple_1207\lstm_har_1207.tflite")
INFO: Initialized TensorFlow Lite runtime.
>>> interpreter.allocate_tensors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\d\.conda\envs\ai\lib\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
**R**untimeError: Encountered unresolved custom op: RandomUniform.Node number 14 (RandomUniform) failed to prepare.****

could anyone  hlep with the issue?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**

**Comment by jvishnuvardhan** [comment] 2019-12-12 20:56
@glevenc Can you please format your code and share a simple standalone code to reproduce the issue? You could use colab gist for sharing the standalone code. Thanks!

**Comment by glevenc** [comment] 2019-12-13 01:54
> 
> 
> @glevenc Can you please format your code and share a simple standalone code to reproduce the issue? You could use colab gist for sharing the standalone code. Thanks!

@jvishnuvardhan 
if i remove the dropoutwrapper opratation then the convert will be successfuly 
drop = tf.compat.v1.nn.rnn_cell.DropoutWrapper(lstm, output_keep_prob=keep_prob)
maybe this opration is not supported yet?

hope this can help you to give you some clue

thx

**Comment by glevenc** [comment] 2019-12-13 03:39
@jvishnuvardhan  the result is repoduced here:
https://colab.research.google.com/drive/1vRsTiKk8CAClShGjwyLmRP7VAqXxAIeq#scrollTo=xNQwn_eZVB4n

**Comment by jvishnuvardhan** [comment] 2019-12-13 16:58
@glevenc I cannot access your colab (permission issue). Can you please open the gist  --> go to `File` --> press `Save a copy as a GitHub gist`---> another page opens up with the shareable gist --> copy the link and share with me. Thanks!

**Comment by glevenc** [comment] 2019-12-14 02:24
@jvishnuvardhan 
sorry for that and the link :
https://colab.research.google.com/gist/glevenc/20ecb878b520653257f4d290dd79fec0/test.ipynb

**Comment by jvishnuvardhan** [comment] 2019-12-16 18:37
@glevenc I am not able to reproduce the exact error you are getting with your colab. When I ran your colab, i see the following error

```
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
Tensor.name is meaningless when eager execution is enabled.
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-15-79344999a2d5> in <module>()
      2 converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
      3 converter.allow_custom_ops=True
----> 4 tflite_model = converter.convert()
      5 open("lstm.tflite", "wb").write(tflite_model)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in numpy(self)
    585       return self.read_value().numpy()
    586     raise NotImplementedError(
--> 587         "numpy() is only available when eager execution is enabled.")
    588 
    589   @deprecated(None, "Prefer Dataset.range instead.")

NotImplementedError: numpy() is only available when eager execution is enabled.
```

Are you using `TF1.15` or `TF2.0`? Can you please check the error one more time. Thanks!

**Comment by glevenc** [comment] 2019-12-17 02:33
@jvishnuvardhan 
hi, i print the version in the colab
and it  shows 1.15.0
Also , in my own pc env. the version is TF2.0
both version have the same issues as list belows:
i just re-run the colab as i shared above link: it can always be reproduced;

RuntimeError                              Traceback (most recent call last)

<ipython-input-16-c0f7628eb24c> in <module>()
      1 interpreter = tf.lite.Interpreter(model_path="lstm.tflite")
----> 2 interpreter.allocate_tensors()
      3 
      4 # Get input and output tensors.
      5 input_details = interpreter.get_input_details()

1 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Encountered unresolved custom op: RandomUniform.Node number 13 (RandomUniform) failed to prepare.

**Comment by haozha111** [comment] 2020-02-01 00:17
we are adding `RandomUniform` as a built-in op for TF Lite. Assigning this issue to Jaeyoo  for investigation now. thanks.

**Comment by ashwinmurthy** [comment] 2020-05-07 05:48
@glevenc We recently announced a new feature in dogfood to convert TF 2.0 Keras LSTM to TFLite fused LSTM (which can then be also quantized if needed). You can see the announcement here:
https://groups.google.com/a/tensorflow.org/g/tflite/c/Ub4apUvblN8

Would you be interested in trying this out?

**Comment by jaeyoo** [comment] 2020-07-07 21:44
Hi @glevenc,

Please use this at the front of your colab
```
!pip install tf-nightly
```
then it succeeds without any errors.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:12
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:53 UTC
Labels: TF 1.15, comp:lite, type:support
