### ISSUE TITLE
tf.linalg.triangular_solve adjoint option description is wrong

### ISSUE THREAD

**Issue by vicaws** [tensorflow/tensorflow#46757] opened 2021-01-28 10:24 UTC
Link:
https://www.tensorflow.org/api_docs/python/tf/linalg/triangular_solve

The following description about "adjoint" looks the other way around to me:
"If adjoint is True then the innermost matrices in output satisfy matrix equations sum_k matrix[..., i, k] * output[..., k, j] = rhs[..., i, j]. If adjoint is False then the innermost matrices in output satisfy matrix equations sum_k adjoint(matrix[..., i, k]) * output[..., k, j] = rhs[..., i, j]."

**Comment by rmothukuru** [comment] 2021-02-02 11:35
@vicaws,
Can you please elaborate your point with a code example? Thanks!

**Comment by vicaws** [comment] 2021-02-02 12:24
> @vicaws,
> Can you please elaborate your point with a code example? Thanks!

Hey,

It is probably a documentation issue only. I'm using tf.linalg.solve and tf.linalg.triangular_solve, while both functions have an argument "adjoint". However, the descriptions of the use of adjoint are inconsistent for these two functions.

**tf.linalg.solve:**
https://www.tensorflow.org/api_docs/python/tf/linalg/solve
"If adjoint is **False** then each output matrix satisfies matrix[..., :, :] * output[..., :, :] = rhs[..., :, :]. If adjoint is **True** then each output matrix satisfies adjoint(matrix[..., :, :]) * output[..., :, :] = rhs[..., :, :]."

**tf.linalg.triangular_solve:**
https://www.tensorflow.org/api_docs/python/tf/linalg/triangular_solve
"If adjoint is **True** then the innermost matrices in output satisfy matrix equations sum_k matrix[..., i, k] * output[..., k, j] = rhs[..., i, j]. If adjoint is **False** then the innermost matrices in output satisfy matrix equations sum_k adjoint(matrix[..., i, k]) * output[..., k, j] = rhs[..., i, j]."

I'm just wondering if this inconsistency is intended, and if both descriptions are correct - i.e. aligned with what the codes really do.

**Comment by Cheril311** [comment] 2022-01-20 05:30
Hey @vicaws  the description seems correct, can you please elaborate what the discrepancy you think is?

**Comment by st--** [comment] 2022-05-21 15:48
@Cheril311 @random-forests I've tried fixing the same issue in #55697 but I've got issues with the CLA system refusing to accept my username. But maybe it'll help you figure out what the issue is & you can re-do the docfix on your own.

**Comment by mohantym** [comment] 2022-09-16 03:57
Hi @vicaws !
This doc bug has been fixed in 2.10 version. Could we mark this as resolved now. Attached [solve](https://www.tensorflow.org/api_docs/python/tf/linalg/solve#:~:text=%2C%20K%5D.-,adjoint,-An%20optional%20bool) and [triangular solve ](https://www.tensorflow.org/api_docs/python/tf/linalg/triangular_solve#:~:text=or%20upper%20triangular.-,adjoint,-An%20optional%20bool)documentation for reference.
Thank you!

**Comment by mohantym** [comment] 2022-09-16 04:42
Ok @vicaws !
Thanks for the nod. Marking this as resolved then.
Thank you!

**Comment by mohantym** [comment] 2022-09-16 04:42
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Closed by mohantym** 2022-09-16 04:42 UTC
Labels: type:docs-bug, stat:awaiting response, comp:ops
