### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by gesman** [tensorflow/tensorflow#7457] opened 2017-02-13 05:13 UTC
The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:

 python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
0.12.1

**Here's the error**:

Epoch 2/2
19125/19125 [==============================] - 78s - loss: 0.4568 - acc: 0.8681 - val_loss: 2.1682 - val_acc: 0.4104
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f747161e160>>
Traceback (most recent call last):
  File "/home/p3/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment

**Comment by yaroslavvb** [comment] 2017-02-14 22:27
This should've been fixed in https://github.com/tensorflow/tensorflow/pull/7386 , can you see if error persists in latest nightly version?

**Comment by aselle** [comment] 2017-03-03 23:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by kentrino** [comment] 2017-04-18 09:38
I've got this in tensorflow (1.0.1).

**Comment by laimonassutkus** [comment] 2017-05-11 07:23
Still persists.

**Comment by frankcarey** [comment] 2017-05-14 23:06
Happens intermittently with `tensorflow/tensorflow:1.0.1-gpu-py3` docker image and keras.

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f3a69e8c470>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 582, in __del__
UnboundLocalError: local variable 'status' referenced before assignment

```

**Comment by nateGeorge** [comment] 2017-05-23 22:39
Also happened for me upon saving a model in keras:
```python
>>> tf.__version__
'1.0.1'
>>> keras.__version__
'2.0.4'
```

**Comment by hank-der-hafenarbeiter** [comment] 2017-07-25 07:53
Happend to me too today on our GPU-Cluster:
```
uname -a
Linux [...] 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
On a GeForce GTX 980 Ti.

```
python --version
Python 3.5.3 :: Continuum Analytics, Inc.

```
```

>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> tensorflow.__version__
'1.0.1'
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.0.3'
```

**Comment by aselle** [comment] 2017-07-25 17:08
@zheng-xq , could you take a look?

**Comment by zheng-xq** [comment] 2017-07-25 17:28
The exception comes from session.py. Passing to Derek fro now.

**Comment by mrry** [comment] 2017-08-08 03:38
I'm pretty sure this has been fixed since the 1.1 release. I'm closing this issue for now, but feel free to reopen it if you can reproduce with a newer version of TensorFlow.

**Closed by mrry** 2017-08-08 03:38 UTC
Labels: stat:awaiting tensorflower, type:bug/performance

**Comment by kkarnatak** [comment] 2018-03-07 22:24
I got this error today while training my network on keras.

Epoch 10/10
19308/19286 [==============================] - 62s - loss: 0.0220 - acc: 0.1795 - val_loss: 0.0231 - val_acc: 0.1846
dict_keys(['val_acc', 'val_loss', 'acc', 'loss'])
Acc
[0.1782905629139073, 0.1796146675076869, 0.18056705298013245, 0.17775015535748767, 0.18656870860927152, 0.17137973897756442, 0.17694536423841059, 0.18142738762061394, 0.17860099337748345, 0.17951108349797049]
Loss
[0.032948918208874613, 0.029692213859633675, 0.028213497242020654, 0.027055541726004047, 0.025659046015572666, 0.025640698771453779, 0.024098622677416005, 0.023113698205617934, 0.02143701246557202, 0.02202132222925083]
Validation Loss
[0.027665206672329651, 0.026977688277141799, 0.026762272280297782, 0.025648139429476319, 0.024419905385002494, 0.024124456143497338, 0.024165717970677895, 0.022718481179619013, 0.021766701916234244, 0.023056170290434046]
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fc9535b4a90>>
Traceback (most recent call last):
  File "/home/carnd/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment

**Comment by shreyapandit** [comment] 2018-03-19 06:56
I also get this error, version 1.5

`
2018-03-19 02:51:05.913 EDT
The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 167, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run _sys.exit(main(argv)) File "/root/.local/lib/python2.7/site-packages/object_detection/train.py", line 163, in main worker_job_name, is_chief, FLAGS.train_dir) File "/root/.local/lib/python2.7/site-packages/object_detection/trainer.py", line 366, in train saver=saver) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 790, in train return total_loss UnboundLocalError: local variable 'total_loss' referenced before assignment To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=301256752837&resource=ml_job%2Fjob_id%2Fshreya_object_detection_1521441960&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22shreya_object_detection_1521441960%22
`

**Comment by canivel** [comment] 2018-03-23 13:53
i also get this error, version 1.6

`Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/research/object_detection/trainer.py", line 360, in train
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 791, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment
`

**Comment by dsimmo** [comment] 2018-03-29 13:45
I also get a similar error when attempting to train using the object detection API (identical to the comment above)

Traceback (most recent call last):
  File "object_detection/train.py", line 167, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/dave/tensorflow-master/models/research/object_detection/trainer.py", line 370, in train
    saver=saver)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 791, in train
    return total_loss
UnboundLocalError: local variable 'total_loss' referenced before assignment
