### ISSUE TITLE
Error : Check failed: IsConstantParameterArray

### ISSUE THREAD

**Issue by Jeong-Heon** [tensorflow/tensorflow#23187] opened 2018-10-23 11:13 UTC
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04.5 LTS 
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.13.0-dev20181023
Python version: 
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: 9.0.176 / 9
GPU model and memory: GeForce GTX 1080ti / 11175MiB

**Describe the current behavior**

I want to convert a custom graph from TF to TFLite using 'TFLiteconverter'
but I faced below error:

> tensorflow.contrib.lite.python.convert.ConverterError: TOCO failed. See console for info.
> 2018-10-23 10:13:26.786330: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 784 operators, 1332 arrays (0 quantized)
> 2018-10-23 10:13:26.797260: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 511 operators, 912 arrays (0 quantized)
> 2018-10-23 10:13:26.806327: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 511 operators, 912 arrays (0 quantized)
> 2018-10-23 10:13:26.806920: F tensorflow/contrib/lite/toco/graph_transformations/resolve_batch_normalization.cc:45] Check failed: IsConstantParameterArray(*model, bn_op->inputs[1]) && IsConstantParameterArray(*model, bn_op->inputs[2]) && IsConstantParameterArray(*model, bn_op->inputs[3]) Batch normalization resolution requires that mean, multiplier and offset arrays be constant.
> Aborted (core dumped)
> 

How can I fix it?

**Code to reproduce the issue**

```
import tensorflow as tf

graph_def_file = "/path/graph.pb"
input_arrays = ["Placeholder"]
output_arrays = ["final"]

converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays)
converter.inference_type = tf.contrib.lite.constants.FLOAT
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by tensorflowbutler** [comment] 2018-10-23 19:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-23 20:33
Please provide the information requested by the @tensorflowbutler.
Can you please try using tf-nightly version if haven't already?

**Comment by Jeong-Heon** [comment] 2018-10-24 04:56
> Please provide the information requested by the @tensorflowbutler.
> Can you please try using tf-nightly version if haven't already?

I modified my System Information
also I already use tf-nightly version using docker.

commend below:
`docker run --name tensorflow-nightly-gpu --runtime=nvidia -it -p 6006:6006 tensorflow/tensorflow:nightly-gpu bash`

**Comment by brucechou1983** [comment] 2018-10-29 15:34
Same issue here. @Jeong-Heon did you solve the problem?

**Comment by tensorflowbutler** [comment] 2018-11-13 18:55
Nagging Assignee @liyunlu0618: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-28 19:00
Nagging Assignee @liyunlu0618: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by liyunlu0618** [comment] 2018-12-08 01:40
You are converting a training graph. Please create a eval graph, freeze it and then run tflite_convert.

**Comment by tofulawrence** [comment] 2019-02-07 23:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2019-02-07 23:28 UTC
Labels: comp:lite

**Comment by JitenderMaurya** [comment] 2019-03-14 06:54
> You are converting a training graph. Please create a eval graph, freeze it and then run tflit

Please explain.
