### ISSUE TITLE
Seemingly unavailable datatypes for Ops.

### ISSUE THREAD

**Issue by mcourteaux** [tensorflow/tensorflow#34098] opened 2019-11-08 12:56 UTC
In [`training_ops.cc:640`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc#L640) I see many registrations for Ops, which have datatypes only supported for non-Windows.

For example:
```cpp
#define REGISTER_KERNELS(D, T)                                                \
  REGISTER_KERNEL_BUILDER(                                                    \
      Name("ApplyGradientDescent").Device(DEVICE_##D).TypeConstraint<T>("T"), \
      ApplyGradientDescentOp<D##Device, T>);                                  \
  REGISTER_KERNEL_BUILDER(Name("ResourceApplyGradientDescent")                \
                              .Device(DEVICE_##D)                             \
                              .HostMemory("var")                              \
                              .TypeConstraint<T>("T"),                        \
                          ApplyGradientDescentOp<D##Device, T>);
#define REGISTER_CPU_KERNELS(T) REGISTER_KERNELS(CPU, T);

TF_CALL_half(REGISTER_CPU_KERNELS);
TF_CALL_bfloat16(REGISTER_CPU_KERNELS);
TF_CALL_float(REGISTER_CPU_KERNELS);
TF_CALL_double(REGISTER_CPU_KERNELS);
#ifndef PLATFORM_WINDOWS
TF_CALL_complex64(REGISTER_CPU_KERNELS);
TF_CALL_complex128(REGISTER_CPU_KERNELS);
#endif
```
Seeing this, we quickly switched and ran our code on a Linux build, hoping the Op would be available for complex128, but it turns out also on Linux, it's not, as indicated by following error:
```
NotFoundError: No registered 'ResourceApplyGradientDescent' OpKernel for 'GPU' devices compatible with node {{node ResourceApplyGradientDescent}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_COMPLEX64, use_locking=true
	.  Registered:  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
 [Op:ResourceApplyGradientDescent]
```
This TensorFlow 2.0 version was installed with `pip install tensorflow-gpu`, minutes ago. Let's say I'm currently interested in having access to the `ApplyGradientDescent` with complex128 for CPU.

Currently compiling TensorFlow myself, to test this. However, the actual questions are:
 - Why are these not supported on Windows?
 - Why are these seemingly not available on a pip-installed TensorFlow version on Linux? Is this an issue with the build process of the pip-release of TensorFlow for Linux?
 - Any recommendations on how to proceed? (I'm currently compiling TensorFlow from source on Linux, hoping for the Op to be available).

**Comment by jaingaurav** [comment] 2019-11-08 16:09
@Davidvdrm: Unfortunately compiler support for many complex operations was suboptimal. We need to provide the necessary complex overrides in order to provide wider support. Did you try compiling with nvcc of the clang CUDA compiler? Clang should give you access to those kernels.

**Comment by Davidvdrm** [comment] 2019-11-08 16:20
I have not yet, but i will try ASAP. The issue is clear now. Thank you for the clarification.

**Comment by jaingaurav** [comment] 2019-11-11 12:47
@Davidvdrm: Were you able to verify if the problem was resolved with the clang CUDA compiler?

**Comment by Davidvdrm** [comment] 2019-11-11 13:37
Not yet, a different issue came up and i will het to the compiler tommorow.
I will post an update as soon as i have results

Op ma 11 nov. 2019 13:54 schreef Gaurav Jain <notifications@github.com>:

**Comment by Davidvdrm** [comment] 2019-11-14 08:54
@jaingaurav I compiled from source using the experimental download clang option in the configuration and this resulted in the same error. In order to test even further i will also try compiling CUDA with clang and then compiling tensorflow with this. I am quite new to linux and compiler (thanks physics education) so it might take me a while to get through everything. If you have any pointers or a short guide this would be very much appreciated.

**Comment by jaingaurav** [comment] 2019-11-14 09:17
@Davidvdrm: The main option needed to be set is the "Do you want to use clang as CUDA compiler?" to be set when running `./configure`. See https://www.tensorflow.org/install/source#sample_session for an example session. Note in the example it is using nvcc instead of clang for the CUDA compiler, which is NOT what you want.

**Comment by Davidvdrm** [comment] 2019-11-14 10:58
I do not reveive this option on windows. I'll try on a linux boot, but as mentioned before getting cudnn and cuda to work on linux is slightly beyond me. The following terminal entry is from the windows bazel build configuration.

```
C:\Users\David\tmp\tensorflow>configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.0 installed.
Please specify the location of python. [Default is C:\Users\David\Anaconda3\python.exe]:


Found possible Python library paths:
  C:\Users\David\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\David\Anaconda3\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include
Found cuDNN 7 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 6.1


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

C:\Users\David\tmp\tensorflow>
```

**Comment by jaingaurav** [comment] 2019-11-15 16:25
@Davidvdrm: As you can see from the code snippet you posted, these complex ops are not supported on windows due to compiler incompatibilities. I think we'll have better luck when we upgrade to MSVC 2019. For now these ops are available only on linux with clang as the CUDA compiler.

**Comment by Davidvdrm** [comment] 2019-11-15 17:11
I was able to get the compilation started on linux with clang, but am currently running into a last issue which i don't understand at all. From some research it seems to be a problem with the compiler not having a back-end for the host. 
```
1 warning generated.
ERROR: /home/david/tmp/tensorflow/tensorflow/core/kernels/BUILD:1976:1: C++ compilation of rule '//tensorflow/core/kernels:gather_functor_gpu' failed (Exit 1)
error: unable to create target: 'No available targets are compatible with triple "nvptx64-nvidia-cuda"'
1 error generated when compiling for sm_35.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/david/tmp/tensorflow/tensorflow/python/tools/BUILD:98:1 C++ compilation of rule '//tensorflow/core/kernels:gather_functor_gpu' failed (Exit 1)
INFO: Elapsed time: 455.025s, Critical Path: 68.46s
INFO: 1675 processes: 1675 local.
FAILED: Build did NOT complete successfully

```

**Comment by Davidvdrm** [comment] 2019-11-15 20:47
An extension on the previously posted error

The full error:
```
ERROR: /home/david/.cache/bazel/_bazel_david/34d22352ac396fe0091b65c723a68a75/external/nccl_archive/BUILD.bazel:53:1: C++ compilation of rule '@nccl_archive//:device_lib' failed (Exit 1)
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:431:
In file included from /usr/include/strings.h:144:
/usr/include/x86_64-linux-gnu/bits/strings_fortified.h:23:8: error: exception specification in declaration does not match previous declaration
__NTH (bcopy (const void *__src, void *__dest, size_t __len))
       ^
/usr/include/strings.h:38:13: note: previous declaration is here
extern void bcopy (const void *__src, void *__dest, size_t __n)
            ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:431:
In file included from /usr/include/strings.h:144:
/usr/include/x86_64-linux-gnu/bits/strings_fortified.h:29:8: error: exception specification in declaration does not match previous declaration
__NTH (bzero (void *__dest, size_t __len))
       ^
/usr/include/strings.h:42:13: note: previous declaration is here
extern void bzero (void *__s, size_t __n) __THROW __nonnull ((1));
            ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:31:8: error: exception specification in declaration does not match previous declaration
__NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
       ^
/usr/include/string.h:42:14: note: previous declaration is here
extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:38:8: error: exception specification in declaration does not match previous declaration
__NTH (memmove (void *__dest, const void *__src, size_t __len))
       ^
/usr/include/string.h:46:14: note: previous declaration is here
extern void *memmove (void *__dest, const void *__src, size_t __n)
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:45:8: error: exception specification in declaration does not match previous declaration
__NTH (mempcpy (void *__restrict __dest, const void *__restrict __src,
       ^
/usr/include/string.h:377:14: note: previous declaration is here
extern void *mempcpy (void *__restrict __dest,
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:8: error: exception specification in declaration does not match previous declaration
__NTH (memset (void *__dest, int __ch, size_t __len))
       ^
/usr/include/string.h:60:14: note: previous declaration is here
extern void *memset (void *__s, int __c, size_t __n) __THROW __nonnull ((1));
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:81:8: error: exception specification in declaration does not match previous declaration
__NTH (explicit_bzero (void *__dest, size_t __len))
       ^
/usr/include/string.h:435:13: note: previous declaration is here
extern void explicit_bzero (void *__s, size_t __n) __THROW __nonnull ((1));
            ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:88:8: error: exception specification in declaration does not match previous declaration
__NTH (strcpy (char *__restrict __dest, const char *__restrict __src))
       ^
/usr/include/string.h:121:14: note: previous declaration is here
extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:8: error: exception specification in declaration does not match previous declaration
__NTH (stpcpy (char *__restrict __dest, const char *__restrict __src))
       ^
/usr/include/string.h:451:14: note: previous declaration is here
extern char *stpcpy (char *__restrict __dest, const char *__restrict __src)
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:103:8: error: exception specification in declaration does not match previous declaration
__NTH (strncpy (char *__restrict __dest, const char *__restrict __src,
       ^
/usr/include/string.h:124:14: note: previous declaration is here
extern char *strncpy (char *__restrict __dest,
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:116:8: error: exception specification in declaration does not match previous declaration
__NTH (stpncpy (char *__dest, const char *__src, size_t __n))
       ^
/usr/include/string.h:459:14: note: previous declaration is here
extern char *stpncpy (char *__restrict __dest,
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:126:8: error: exception specification in declaration does not match previous declaration
__NTH (strcat (char *__restrict __dest, const char *__restrict __src))
       ^
/usr/include/string.h:129:14: note: previous declaration is here
extern char *strcat (char *__restrict __dest, const char *__restrict __src)
             ^
In file included from <built-in>:1:
In file included from external/local_config_cuda/crosstool/extra_tools/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:133:8: error: exception specification in declaration does not match previous declaration
__NTH (strncat (char *__restrict __dest, const char *__restrict __src,
       ^
/usr/include/string.h:132:14: note: previous declaration is here
extern char *strncat (char *__restrict __dest, const char *__restrict __src,
             ^
In file included from bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:10:
In file included from bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:8:
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:243:7: warning: field 'comm' will be initialized after field 'tid' [-Wreorder-ctor]
    : comm(comm), tid(tid), nthreads(nthreads), stepSize(stepSize), opCount(opCount) {
      ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:30:5: note: in instantiation of member function 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::ncclPrimitives' requested here
    prims(tid, nthreads, &ring->prev, &ring->next, NULL, stepSize, channel, comm, args->opCount);
    ^
bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:14:1: note: in instantiation of function template specialization 'ncclReduceScatterRingKernel<4, FuncMax<double>, double>' requested here
IMPL_COLL_R(ncclReduceScatter, ncclCollReduceScatter);
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:145:3: note: expanded from macro 'IMPL_COLL_R'
  IMPL_COLL2(collf, max,  FuncMax,  colln, ncclMax);
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:130:3: note: expanded from macro 'IMPL_COLL2'
  IMPL_COLL3(coll, op, ncclFunc, f64, double,   ncclColl, ncclOp, ncclFloat64)
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:101:3: note: expanded from macro 'IMPL_COLL3'
  IMPL_COLL4(coll##Ring, op, ncclFunc, dtype, ctype, ncclColl, ncclOp, ncclType, 0) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:96:3: note: expanded from macro 'IMPL_COLL4'
  IMPL_COLL_FUNC(coll, op, ncclFunc, dtype, ctype) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:48:3: note: expanded from macro 'IMPL_COLL_FUNC'
  coll##Kernel<COLL_UNROLL, ncclFunc<ctype>, ctype>(args); \
  ^
<scratch space>:121:1: note: expanded from here
ncclReduceScatterRingKernel
^
In file included from bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:10:
In file included from bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:8:
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:143:16: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
      if (SRC) srcs[1] = recvPtr(0);
               ^    ~
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:253:5: note: in instantiation of function template specialization 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::GenericOp<0, 0, 0, 1, 1, 0>' requested here
    GenericOp<0, 0, 0, 1, 1, 0>(src, NULL, nelem, 0);
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:46:11: note: in instantiation of member function 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::send' requested here
    prims.send(thisInput+offset, nelem);
          ^
bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:14:1: note: in instantiation of function template specialization 'ncclReduceScatterRingKernel<4, FuncMax<double>, double>' requested here
IMPL_COLL_R(ncclReduceScatter, ncclCollReduceScatter);
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:145:3: note: expanded from macro 'IMPL_COLL_R'
  IMPL_COLL2(collf, max,  FuncMax,  colln, ncclMax);
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:130:3: note: expanded from macro 'IMPL_COLL2'
  IMPL_COLL3(coll, op, ncclFunc, f64, double,   ncclColl, ncclOp, ncclFloat64)
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:101:3: note: expanded from macro 'IMPL_COLL3'
  IMPL_COLL4(coll##Ring, op, ncclFunc, dtype, ctype, ncclColl, ncclOp, ncclType, 0) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:96:3: note: expanded from macro 'IMPL_COLL4'
  IMPL_COLL_FUNC(coll, op, ncclFunc, dtype, ctype) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:48:3: note: expanded from macro 'IMPL_COLL_FUNC'
  coll##Kernel<COLL_UNROLL, ncclFunc<ctype>, ctype>(args); \
  ^
<scratch space>:121:1: note: expanded from here
ncclReduceScatterRingKernel
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:140:5: note: array 'srcs' declared here
    const T* srcs[RECV*NRECV+SRC];
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:150:16: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
      if (DST) dsts[1] = directSendPtr<DIRECTSEND>(0, directOffset);
               ^    ~
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:147:5: note: array 'dsts' declared here
    T* dsts[SEND*NSEND+DST];
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:150:16: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
      if (DST) dsts[1] = directSendPtr<DIRECTSEND>(0, directOffset);
               ^    ~
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:294:5: note: in instantiation of function template specialization 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::GenericOp<0, 0, 1, 1, 1, 0>' requested here
    GenericOp<0, 0, 1, 1, 1, 0>(src, NULL, nelem, 0);
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:53:13: note: in instantiation of member function 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::recvReduceSend' requested here
      prims.recvReduceSend(thisInput+offset, nelem);
            ^
bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:14:1: note: in instantiation of function template specialization 'ncclReduceScatterRingKernel<4, FuncMax<double>, double>' requested here
IMPL_COLL_R(ncclReduceScatter, ncclCollReduceScatter);
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:145:3: note: expanded from macro 'IMPL_COLL_R'
  IMPL_COLL2(collf, max,  FuncMax,  colln, ncclMax);
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:130:3: note: expanded from macro 'IMPL_COLL2'
  IMPL_COLL3(coll, op, ncclFunc, f64, double,   ncclColl, ncclOp, ncclFloat64)
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:101:3: note: expanded from macro 'IMPL_COLL3'
  IMPL_COLL4(coll##Ring, op, ncclFunc, dtype, ctype, ncclColl, ncclOp, ncclType, 0) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:96:3: note: expanded from macro 'IMPL_COLL4'
  IMPL_COLL_FUNC(coll, op, ncclFunc, dtype, ctype) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:48:3: note: expanded from macro 'IMPL_COLL_FUNC'
  coll##Kernel<COLL_UNROLL, ncclFunc<ctype>, ctype>(args); \
  ^
<scratch space>:121:1: note: expanded from here
ncclReduceScatterRingKernel
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:147:5: note: array 'dsts' declared here
    T* dsts[SEND*NSEND+DST];
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:150:16: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
      if (DST) dsts[1] = directSendPtr<DIRECTSEND>(0, directOffset);
               ^    ~
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:289:5: note: in instantiation of function template specialization 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::GenericOp<0, 0, 1, 0, 1, 1>' requested here
    GenericOp<0, 0, 1, 0, 1, 1>(src, dst, nelem, 0);
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:60:11: note: in instantiation of member function 'ncclPrimitives<4, 2, 2, double, 1, 1, FuncMax<double> >::recvReduceCopy' requested here
    prims.recvReduceCopy(thisInput+offset, thisOutput+chunkOffset, nelem);
          ^
bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:14:1: note: in instantiation of function template specialization 'ncclReduceScatterRingKernel<4, FuncMax<double>, double>' requested here
IMPL_COLL_R(ncclReduceScatter, ncclCollReduceScatter);
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:145:3: note: expanded from macro 'IMPL_COLL_R'
  IMPL_COLL2(collf, max,  FuncMax,  colln, ncclMax);
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:130:3: note: expanded from macro 'IMPL_COLL2'
  IMPL_COLL3(coll, op, ncclFunc, f64, double,   ncclColl, ncclOp, ncclFloat64)
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:101:3: note: expanded from macro 'IMPL_COLL3'
  IMPL_COLL4(coll##Ring, op, ncclFunc, dtype, ctype, ncclColl, ncclOp, ncclType, 0) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:96:3: note: expanded from macro 'IMPL_COLL4'
  IMPL_COLL_FUNC(coll, op, ncclFunc, dtype, ctype) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:48:3: note: expanded from macro 'IMPL_COLL_FUNC'
  coll##Kernel<COLL_UNROLL, ncclFunc<ctype>, ctype>(args); \
  ^
<scratch space>:121:1: note: expanded from here
ncclReduceScatterRingKernel
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:147:5: note: array 'dsts' declared here
    T* dsts[SEND*NSEND+DST];
    ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/primitives.h:529:7: warning: field 'comm' will be initialized after field 'tid' [-Wreorder-ctor]
    : comm(comm), tid(tid), nthreads(nthreads), opCount(opCount) {
      ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/reduce_scatter.h:76:35: note: in instantiation of member function 'ncclLLPrimitives<double, FuncMax<double>, 1, 1>::ncclLLPrimitives' requested here
  ncclLLPrimitives<T, FUNC, 1, 1> LLprims(tid, nthreads, &ring->prev, &ring->next, channel, comm, args->opCount);
                                  ^
bazel-out/host/bin/external/nccl_archive/src/collectives/device/max_f64_reduce_scatter.cu.cc:14:1: note: in instantiation of function template specialization 'ncclReduceScatterRingLLKernel<4, FuncMax<double>, double>' requested here
IMPL_COLL_R(ncclReduceScatter, ncclCollReduceScatter);
^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:145:3: note: expanded from macro 'IMPL_COLL_R'
  IMPL_COLL2(collf, max,  FuncMax,  colln, ncclMax);
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:130:3: note: expanded from macro 'IMPL_COLL2'
  IMPL_COLL3(coll, op, ncclFunc, f64, double,   ncclColl, ncclOp, ncclFloat64)
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:101:3: note: expanded from macro 'IMPL_COLL3'
  IMPL_COLL4(coll##Ring, op, ncclFunc, dtype, ctype, ncclColl, ncclOp, ncclType, 0) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:97:3: note: expanded from macro 'IMPL_COLL4'
  IMPL_COLL_FUNC(coll##LL, op, ncclFunc, dtype, ctype) \
  ^
bazel-out/host/bin/external/nccl_archive/_virtual_includes/device_hdrs/common.h:48:3: note: expanded from macro 'IMPL_COLL_FUNC'
  coll##Kernel<COLL_UNROLL, ncclFunc<ctype>, ctype>(args); \
  ^
<scratch space>:127:1: note: expanded from here
ncclReduceScatterRingLLKernel
^
6 warnings and 13 errors generated when compiling for sm_35.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/david/tmp/tensorflow/tensorflow/tools/pip_package/BUILD:223:1 C++ compilation of rule '@nccl_archive//:device_lib' failed (Exit 1)
INFO: Elapsed time: 523.828s, Critical Path: 170.66s
INFO: 2425 processes: 2425 local.
FAILED: Build did NOT complete successfully
```

**Closed** 2020-02-02 07:43 UTC
Labels: TF 2.0, comp:ops, stat:awaiting tensorflower, type:support
