### ISSUE TITLE
model.fit() with TensorFlow callback set to log each batch causes error on the second model.fit() call

### ISSUE THREAD

**Issue by daniel-kukiela** [tensorflow/tensorflow#49246] opened 2021-05-18 01:26 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1 (edit: confirmed also with TF 2.5.0)
- Python version: 3.8.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 11.0/8.0.4.30
- GPU model and memory: GTX 1080 Ti 11 GB

**Describe the current behavior**
While training a model with TensorBoard callback set to log each batch, another `model.fit()` call fails with error:
```
2021-05-18 03:23:42.686008: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at summary_kernels.cc:210 : Not found: Resource localhost/_AnonymousVar6/class tensorflow::SummaryWriterInterface does not exist.
Traceback (most recent call last):
  File "error.py", line 11, in <module>
    model.fit([1, 2, 3, 4, 5])
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\danie\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  Resource localhost/_AnonymousVar6/class tensorflow::SummaryWriterInterface does not exist.
         [[{{node cond/then/_0/batch_loss}}]]
  (1) Not found:  Resource localhost/_AnonymousVar6/class tensorflow::SummaryWriterInterface does not exist.
         [[{{node cond/then/_0/batch_loss}}]]
         [[GroupCrossDeviceControlEdges_0/Identity_1/_15]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_208]

Function call stack:
train_function -> train_function
```

**Describe the expected behavior**
The second `model.fit()` call should not yield this error

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): no (I do not know the cause currently to think about a fix)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```py
import tensorflow.keras as keras

model = keras.Sequential()
model.add(keras.layers.Input(shape=(1,)))

model.compile()
model.summary()

model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq='batch')])
model.fit([1, 2, 3, 4, 5])
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Error message included above

**Comment by daniel-kukiela** [comment] 2021-05-18 02:26
After further investigation, what triggers this issue is either:
```py
        self._pop_writer()
```
in the `on_train_end()` method of the `TensorBoard` callback, or:
```py
        self._close_writers()
```
in the same method.

What possibly helps here is to call:
```py
model._reset_compile_cache()
```
between first and second `model.fit()` call, like:
```py
import tensorflow.keras as keras

model = keras.Sequential()
model.add(keras.layers.Input(shape=(1,)))

model.compile()
model.summary()

model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq='batch')])
model._reset_compile_cache()
model.fit([1, 2, 3, 4, 5])
```

**Comment by saikumarchalla** [comment] 2021-05-18 12:44
@daniel-kukiela  I can able to reproduce the issue when calling model.fit twice() and after adding model._reset_compile_cache(),  I am not facing any issues as you mentioned above. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/f14ae4401b461238e9edee727dba2c07/untitled.ipynb).

Looks like the issue is resolved already.  Please let us know if you have  any further questions?

**Comment by daniel-kukiela** [comment] 2021-05-18 12:56
For me, what I found is a workaround for a bug, not a solution. I would not call it a solution. `_reset_compile_cache` is not documented method and I doubt that it is meant/designed to be used outside of the class (because of leading `_` in its name) and that this way is or will be a supported way of dealing with this issue.

**Comment by bhack** [comment] 2021-05-18 13:10
You need to recompile your model if you want to run on the same model again but without callbacks:
```python
import tensorflow.keras as keras

model = keras.Sequential()
model.add(keras.layers.Input(shape=(1,)))

model.compile()
model.summary()

model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq='batch')])
model.compile()
model.fit([1, 2, 3, 4, 5])
```

**Comment by daniel-kukiela** [comment] 2021-05-18 13:21
It does not matter if we do this with or without callbalcks. This:
```py
import tensorflow.keras as keras

model = keras.Sequential()
model.add(keras.layers.Input(shape=(1,)))

model.compile()
model.summary()

model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq='batch')])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq='batch')])
```
yields the same error.

Is `.compile()` really necessary or is it yet another way of workaround? I specifically tracked it further to find out that some sort of cache causes this issue and it does not seem to be necessary to compile the model again. Additionally we'll have to keep an optimizer's instance aside to be able to use it with subsequent `.fit()` calls. Does compile affect anything else?
Additionally, if we remove `update_freq='batch'` from the TensorBoard callback, everything works without model re-compilation (no matter if I change a list of callbacks or anything else).

Taking all of the above into account, I still think that this is some sort of bug, possibly introduced while batch-level logging was moved from the TensorBoard class to the Model class (for some sort of speed improvement of small models).

**Comment by bhack** [comment] 2021-05-18 14:54
In this 2nd case it will work cause I don't think they are executed.
I don't know if it need to works with different callbacks without re-compile.

It seems that without recompile it is going to have some conflict on execution

This is broken
```
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard()])
```

This is not cause it is not executed:
```
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=2)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard()])
```

**Comment by daniel-kukiela** [comment] 2021-05-18 15:37
I'm using other callbacks as well and everything works perfectly fine without re-compilation with another `.fit()` call - all of the callbacks like checkpoints or custom preview callback).

I'm almost sure that (from your examples) this:
```py
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard()])
```
is exactly the same what I originally posted (`update_freq=1` and `update_freq='batch'` are exactly same setting) and this:
```py
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=2)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard()])
```
This actually writes 2 log files but in both cases, there is only one batch executed with `.fit()` (maybe this is what makes it different).

**Comment by bhack** [comment] 2021-05-18 15:55
What I suppose with the TensorBoard callback is that if you change the freq with the second call then when it is executed the first one something it is not ready anymore (e.g. the summary writer node?).

```python
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=2)])
```

```python
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=2)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
```

**Comment by daniel-kukiela** [comment] 2021-05-18 16:08
Well, it is the same even if you do not change the frequency:
```py
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
```

As far as I tested by subclassing TB class, it's related to writer objects or references which are probably cached with the first `.fit()` call, but as writers are then removed at the training end, whatever is cached is no longer valid.

Also, I do not see a reason to call `.compile()` in this case, as this is a TesorBoard callback only which is problematic and not even training itself. Training works ok without `compile()` between `.fit()` calls as well as other callbacks. Re-assigning everything like an optimizer, loss, etc feels like makes no sense just for a TensorBoard callback, and adds complexity and a need to make sure that, for example, we are not using a fresh optimizer instance with a second `.fit(0` call.

What seems to be helping here is `model._reset_compile_cache()` (which is also called when you invoke `model.compile()`, that's why it helps the same way here) which suggests that something is being kept cached incorrectly or redundantly.

**Comment by bhack** [comment] 2021-05-18 16:24
Is that the training_function is not recreated:

https://github.com/tensorflow/tensorflow/blob/66852f05e5fec32ea8f3f7c2346f86c7e3e4fcf5/tensorflow/python/keras/engine/training.py#L836-L837

If you bypass this if

```python
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
model.train_function=None
model.fit([1, 2, 3, 4, 5], callbacks=[keras.callbacks.TensorBoard(update_freq=1)])
```

**Comment by daniel-kukiela** [comment] 2021-05-18 16:39
It's over my knowledge to know if it needs to be re-created. Things seem to work correctly if we invalidate the cache only, so maybe `model._reset_compile_cache()` should be called in `.fit()` instead of (or additionally to) `.compile()` since some things that require it are invoked in `.fit()` (callbacks).

Are we both on the same page speaking of classifying it as a bug? It looks like we have multiple workarounds already, so possibly it can have low priority, but this is something that should be, IMO, fixed in the future. I can make a PR if I know if my way of thinking is correct here.

**Comment by bhack** [comment] 2021-05-18 16:59
It is the same as `_reset_compile_cache` (that it is a `private` API) as the name could suggest it is called by `compile` (compile is a public API).

I think in this specific case `model.train_function=None` (and it is what it is done in `_reset_compile_cache) it is probably enough.

I don't know if this is the only case that requires to recreate the `train_function` but you can try to submit a new PR covering to cover this test case.

**Comment by saikumarchalla** [comment] 2021-06-09 12:29
@daniel-kukiela  Please go ahead and close the issue if you don't have any further queries.

**Comment by bhack** [comment] 2021-06-09 12:33
@MarkDaoust Could you evaluate if we need to add something to the docs?

**Comment by daniel-kukiela** [comment] 2021-06-09 15:20
@saikumarchalla I'm still considering it a bug, this hasn't changed. I've been looking around to post a PR. I've been trying to search through the code if other places need a similar patch. Just haven't done that yet.

**Comment by MarkDaoust** [comment] 2021-06-10 13:07
The discussion shows that it's only the TensorBoard callback that triggers this error. So I think this should be considered a bug not a docs issue. 

Notes:

`.compile(run_eagerly=True) ` also avoids the issue. 

Looking at `make_train_function` the only reference to summaries I see are [here](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/python/keras/engine/training.py#L848) and  [here](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/python/keras/engine/training.py#L1188) 

It could be something like that callback being set as the default summary writer, and then something holding a reference to it.
I'm more suspicious of the first link, since that is in the train train_function. Anyone want to try with that line commented out?

**Closed** 2021-07-03 02:13 UTC
Labels: TF 2.4, comp:keras, stalled, stat:awaiting response, type:bug
