### ISSUE TITLE
tf.debugging is not compatible with symbolic Keras tensors

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#41627] opened 2020-07-22 13:30 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.2.0
- Python version: 3.6.9

**Describe the current behavior**

Functions from `tf.debugging` (such as `tf.debugging.assert_equal`) raise an exception when passing a Keras tensor as argument.

It appears that the functions run the eager code path even when one of the input is a symbolic tensor.

**Describe the expected behavior**

`tf.debugging` functions should work with Keras tensors.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
x = tf.keras.Input(shape=[5], batch_size=2)
batch_size = tf.shape(x)[0]
tf.debugging.assert_equal(batch_size, 2)
```

**Other info / logs**

```text
Traceback (most recent call last):
  File "assert.py", line 4, in <module>
    tf.debugging.assert_equal(batch_size, 2)
  File "/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 648, in assert_equal_v2
    return assert_equal(x=x, y=y, summarize=summarize, message=message, name=name)
  File "/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 659, in assert_equal
    data, summarize, message, name)
  File "/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 334, in _binary_assert
    if condition:
  File "/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 778, in __bool__
    self._disallow_bool_casting()
  File "/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 548, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 537, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by Saduf2019** [comment] 2020-07-22 16:00
@guillaumekln 
Please refer to these [links](https://stackoverflow.com/questions/59308263/using-a-tf-tensor-as-a-python-bool-is-not-allowed-in-graph-execution-use-ea) with same error and let us know if it helps
#40916 #37393 #36848 [link](https://github.com/matterport/Mask_RCNN/issues/1911#issuecomment-653752919)

**Comment by guillaumekln** [comment] 2020-07-22 16:06
Unless the usage above is incorrect, I think the issue is inside TensorFlow:

https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/check_ops.py#L334

`if condition` is invalid when `condition` is a symbolic tensor.

**Comment by jvishnuvardhan** [comment] 2020-07-23 22:37
@guillaumekln I think we need to use static shape (`x.shape[0]`) during graph definition instead of dynamic shape (`tf.shape(x)[0]`). I changed one line in your code and everything worked as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f07cf4aa74722a7ba556e5ed7ed4cd38/untitled957.ipynb#scrollTo=dYSub6fKnbpq).

```
#batch_size = tf.shape(x)[0]
batch_size = x.shape[0]

```
There are couple of stackoverflow and other resources explaining difference between `static` and `dynamic` shape. [Here](https://pgaleone.eu/tensorflow/2018/07/28/understanding-tensorflow-tensors-shape-static-dynamic/) one resource that is good. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by guillaumekln** [comment] 2020-07-24 08:18
`tf.shape` is required when the dimension is dynamic and not known at graph building time. Consider the following example:

```python
import tensorflow as tf
x = tf.keras.Input(shape=[5])
assert x.shape[0] is None
batch_size = tf.shape(x)[0]
tf.debugging.assert_equal(batch_size, 2)
```

**Comment by tomerk** [comment] 2020-07-30 19:59
Hi @guillaumekln,

By design you can only use tf APIs as layers in Keras Functional models when the APIs take tensors as input and output tensors. The various `tf.debugging` APIs return None (or an op that needs to be used as a control dependency), so they do not support Keras inputs.

If you're just looking to do a static shape check here you can statically get the shape instead of getting a symbolic tensor representing the shape by doing:
```
batch_size = int(x.shape[0])
tf.debugging.assert_equal(batch_size, 2)
```

On the other hand, if you want to encode a `tf.debugging.assert` as part of your actual model you can:
1. put it in a `tf.keras.Lambda` layer that returns the inputs (w/ the debugging assert as a side effect run in the lambda),
 or 2. Put the `tf.debugging` call in a custom layer / custom model.

**Closed** 2020-07-30 20:00 UTC
Labels: TF 2.2, comp:keras, stat:awaiting tensorflower, type:bug
