### ISSUE TITLE
Tensorflow2.0 Training OOM when tf.function retraces excessively

### ISSUE THREAD

**Issue by akanyaani** [tensorflow/tensorflow#31842] opened 2019-08-21 14:09 UTC
<em>When I am training my model using **tf.function** CPU memory is leaking and after some steps of training it is getting killed.</em>

**System information**
- OS Platform: - Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0-beta
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.01
- GPU model and memory: p100, 16GB

```
@tf.function
def train_step(self, x, step, grad_clip=True, clip_value=1.0):
    with tf.name_scope("input_data"):
        inputs = x[:, :-1]
        targets = x[:, 1:]

     with tf.GradientTape() as tape:
          predictions, _ = model(inputs, training=True)
          loss = self.get_loss(targets, predictions)

      with tf.name_scope("gradients"):
          gradients = tape.gradient(loss, self.trainable_variables)
          if grad_clip:
              gradients = [(tf.clip_by_value(grad, -clip_value, clip_value))
                             for grad in gradients]
          self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))

        accuracy = self.get_padded_accuracy(targets, predictions)
        assert self.train_writer is not None
        with tf.name_scope("summary_writer"):
            with self.train_writer.as_default():
                tf.summary.scalar("loss", loss, step=step)
                tf.summary.scalar("accuracy", accuracy, step=step)
       return loss, accuracy

**Stats of CPU memory
After 100 steps - 5.08 GB
After 500 steps -  14.8 GB
After 1000 steps - 27 GB**
```
        

**When is graph mode of training using tf.function CPU memory gets leaked and after some steps, it gets killed but when I train my model using eager mode it works fine, I am using above code for graph mode training as recommended by TensorFlow 2.0 community.**

**Comment by WindQAQ** [comment] 2019-08-21 18:04
Hi @akanyaani, is the shape of `x` varies between each batch?

**Comment by akanyaani** [comment] 2019-08-21 18:08
Yes, the shape of x varies between each batch.

**Comment by akanyaani** [comment] 2019-08-21 18:09
> Hi @akanyaani, is the shape of `x` varies between each batch?

**Comment by akanyaani** [comment] 2019-08-21 18:11
Yes, The shape of x varies between each batch.

**Comment by WindQAQ** [comment] 2019-08-21 18:25
That's the reason why! Because `tf.function` will re-trace the graph due to the variable sequence lengths or variable batch sizes, the number of cached graphs will increase over time if it do not see this shape before., and this OOM occurred. To avoid re-tracing, you might want to specify the `input_signature`. For detailed explanation, please refer to
https://www.tensorflow.org/beta/tutorials/eager/tf_function
https://www.tensorflow.org/beta/tutorials/text/transformer (search `tf.function`)

**Comment by akanyaani** [comment] 2019-08-21 18:31
Thanks for your prompt response.
But for that I was calling this method for prevent tensorflow to create new graph tf.compat.v1.get_default_graph().finalize() 

But let me try with the input signature

**Comment by akanyaani** [comment] 2019-08-21 19:42
It tried with `@tf.function(input_signature=[tf.TensorSpec(shape=(None, None), dtype=tf.int32)])` with variable sequence length but still, it is happening, but **when I run with a fix sequence length it works fine** but it will cost extra computation.

**Comment by oanush** [comment] 2019-08-22 06:15
@akanyaani ,
Can you please provide a code snippet to reproduce the issue reported here.Thanks!

**Comment by errord** [comment] 2019-08-23 06:32
focus on

**Comment by akanyaani** [comment] 2019-08-23 06:55
Hi,

My model has transformer-based encoder-decoder as explained here.
[https://www.tensorflow.org/beta/tutorials/text/transformer](url)

**Comment by akanyaani** [comment] 2019-08-27 17:35
Hi, @kkimdev please look at Gpt model written in this repo.
https://github.com/akanyaani/gpt-2-tensorflow2.0

**Comment by mdanatg** [comment] 2019-09-26 15:21
@akanyaani, it looks like the general suspicion is that subsequent calls to `train_step` cause the function to be re-traced (a slow process that should only happen once or twice), likely due to the parameter configuration. For example, it could be because the shape of `x` varies, but it could also depend on the value of `step`.

I'm not sure I can completely follow your instructions for reproducing it, but here is a way to diagnose this issue: add a `print` call to train_step, like so:

```
def train_step(self, x, step, grad_clip=True, clip_value=1.0):
    print('tracing', x, step, grad_clip, clip_value)
    with tf.name_scope("input_data"):
      ...
```

Since the pure Python functions like `print` are only called during tracing, it's an effective way to tell whether the function is re-traced too much. If it does, it also helps explain why.

We've just updated the API docs as well with a bit more relevant information, it's worth checking out here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/def_function.py#L989

**Comment by akanyaani** [comment] 2019-10-10 10:00
Hi @mdanatg, Sorry for my late response, Actually I tried with one parameter also but the same thing was happening. So I found that the sequence length of x was the culprit. It was working fine with fix sequence length. And I have noticed that if you restart training with different batch size same problem happens. 
```
def train_step(self, x):
    with tf.name_scope("input_data"):
```

**Comment by mdanatg** [comment] 2019-10-10 13:42
Thanks! Just to double-check, you are still seeing the leak if you try:

```
@tf.function(input_signature=[tf.TensorSpec(shape=(None, None), dtype=tf.int32)])
def train_step(self, x):
    print('tracing')
    with tf.name_scope("input_data"):
```

And you see just one "tracing" message at the console?

**Comment by zxk19981227** [comment] 2019-11-21 05:29
I met the same problem. Did you solve the same problem?

**Comment by akanyaani** [comment] 2019-11-21 07:53
Hi @zxk19981227,

Can you give me some idea about your model architecture, then I will be able to give you the answer.

Thanks

**Comment by andiconda** [comment] 2020-03-08 10:30
@mdanatg I have use “print” in train_step(), it shows that each epoch has a "print" work. and my code killed because of OOM.

are there some solutions for it?

thank you in advance.

**Comment by zxk19981227** [comment] 2020-03-09 01:48
I'm sorry  to hear that. But I solved my problems by turning off auto
trace. Maybe your problem is not the 'print' but the auto trace. You can
try this.
I hope it helps

anna <notifications@github.com> 于2020年3月8日周日 下午6:30写道：

**Comment by Saduf2019** [comment] 2020-03-19 14:14
@akanyaani ,
Could you please update on the above comment, let us know if the issue still exist.

**Comment by Saduf2019** [comment] 2020-03-29 07:32
@akanyaani ,
Could you please update on the above comment

**Comment by Saduf2019** [comment] 2020-04-06 10:50
@akanyaani ,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by Saduf2019** 2020-04-06 10:50 UTC
Labels: TF 2.0-rc0, comp:core, stat:awaiting response, type:bug

**Comment by GoingMyWay** [comment] 2020-05-24 10:01
> That's the reason why! Because `tf.function` will re-trace the graph due to the variable sequence lengths or variable batch sizes, the number of cached graphs will increase over time if it do not see this shape before. Thus OOM occurred. To avoid re-tracing, you might want to specify the `input_signature`. For detailed explanation, please refer to
> https://www.tensorflow.org/beta/tutorials/eager/tf_function
> https://www.tensorflow.org/beta/tutorials/text/transformer (search `tf.function`)

Great, it helps. Could you please add a warning in this function to alert users?
