### ISSUE TITLE
TensorFlow cublas code is not honoring NVIDIA_TF32_OVERRIDE=0 

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#53742] opened 2022-01-12 19:00 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6
- Python version: 3.8.12
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4
- GPU model and memory: A100

**Describe the current behavior**

Irrespective of NVIDIA_TF32_OVERRIDE=0/1 setting, the following is observed coming from cublas. 

> I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

By using CUBLASLT_LOG_LEVEL=5 , only see the following kernels with both NVIDIA_TF32_OVERRIDE=0/1

[cublasLtCreate]
[cublasLtCtxInit]
[cublasLtSSSMatmulAlgoGetHeuristic]
[cublasLtSSSMatmul]

Both seem to use the following

2022-01-12 03:29:14][cublasLt][1420][Api][cublasLtSSSMatmulAlgoGetHeuristic] Adesc=[type=R_32F rows=200 cols=200 ld=200] Bdesc=[type=R_32F rows=200 cols=128 ld=200] Cdesc=[type=R_32F rows=200 cols=128 ld=200] preference=[maxWavesCount=0.0 gaussianModeMask=3M_MODE_DISALLOWED pointerModeMask=0 maxWorkspaceSizeinBytes=4194304 minBytesAlignmentA=16 minBytesAlignmentB=16 minBytesAlignmentC=16 minBytesAlignmentD=16 smCountTarget=108] computeDesc=[computeType=COMPUTE_32F_FAST_TF32 scaleType=R_32F]

**Describe the expected behavior**

Should use FP32 instead of TF32.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

Any kernel that uses cublas gemm. 

**Other info / logs** Include any logs or source code that would be helpful to
Irrespective of NVIDIA_TF32_OVERRIDE=0/1 setting, the following is observed coming from cublas. 

> I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

**Comment by tilakrayal** [comment] 2022-01-13 07:37
@whatdhack ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by whatdhack** [comment] 2022-01-20 08:54
@tilakrayal ,  it is very easy to create that -  just as I mentioned do a matmul .

**Comment by tilakrayal** [comment] 2022-01-21 12:26
@whatdhack ,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet  you are using

**Comment by whatdhack** [comment] 2022-01-26 00:31
@tilakrayal , an example follows.

```
> NVIDIA_TF32_OVERRIDE=0 python
>>>  import tensorflow as tf
>>> a = tf.constant(0.2, shape=[1000, 1000])
>>> b = tf.constant(0.2, shape=[1000, 1000])
>>> c = tf.matmul(a, b)
2022-01-26 00:29:04.187721: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
>>>
```

**Comment by tilakrayal** [comment] 2022-01-27 10:04
@whatdhack ,
While trying to execute the provided code i haven't faced any issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/c428751ec19835d5844d68708fd6835b/untitled199.ipynb) and let us know if anything is missing.Thanks

**Comment by whatdhack** [comment] 2022-01-27 18:56
Still see it  in TF 2.6  Do not have TF 2.7 yet.  Will try again after upgrade. 

```
>>> b = tf.constant(0.2, shape=[1000, 1000])
>>> c = tf.matmul(a, b)
2022-01-27 18:40:10.497687: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
>>> tf.__version__
'2.6.0'
>>> c = tf.matmul(a, b)
>>>
```

However, that part of the code does not look like have changed in TF source ( https://github.com/tensorflow/tensorflow/blob/c242bc0901c3fa5966a16e41a8d3da33e4e4b690/tensorflow/stream_executor/cuda/cuda_blas.cc#L1774  ).    
Also, the log is  displayed only once, the first time cublas is called.  Do not know how colab works - could it have  been already been run  previously ? 


This question came up because I am trying to run in only FP32, do not want pollution from TF32  inadvertently.  Is there another way to ascertain that ? Changing model code is not an option however.

**Comment by whatdhack** [comment] 2022-02-03 00:21
Tried with TF 2.8 .  Same output.  So, looks like either it is not possible to disable TF32 or that message is erroneous.  If the former, which I think it is , then performance results for fp32 will  be misleading, 
```
Python 3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> NVIDIA_TF32_OVERRIDE=0
>>> import tensorflow as tf
>>> tf.__version__
'2.8.0'
>>> a = tf.constant(0.2, shape=[1000, 1000])
2022-02-03 00:14:02.629882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:02.643073: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:02.644380: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:02.645940: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-03 00:14:02.649275: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:02.650593: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:02.651803: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:03.016682: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:03.017961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:03.019177: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-03 00:14:03.020402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38420 MB memory:  -> device: 0, name: NVIDIA A100-PCIE-40GB, pci bus id: 0000:43:00.0, compute capability: 8.0
>>> b = tf.constant(0.2, shape=[1000, 1000])
>>> c = tf.matmul(a, b)
2022-02-03 00:14:19.247907: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
>>>
```

**Comment by jurahul** [comment] 2022-02-11 00:51
Note that the API to enable or disable TF32 support in Tensorflow is: https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_tensor_float_32_execution

Using NVIDIA_TF32_OVERRIDE will not work because TF explicitly tells cublas to use TF32. Can you try using the enable_tensor_float_32_execution API?

**Comment by whatdhack** [comment] 2022-02-11 02:10
@jurahul , thanks for the pointer.

**Comment by sachinprasadhs** [comment] 2022-09-21 18:23
@whatdhack , If your issue is resolved with the `tf.config.experimental.enable_tensor_float_32_execution`, could you please close the issue. Thanks!

**Closed** 2022-10-05 18:49 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:gpu, 2.6.0
