### ISSUE TITLE
RuntimeError: Quantization not yet supported for op: %

### ISSUE THREAD

**Issue by ehazrati** [tensorflow/tensorflow#43207] opened 2020-09-14 13:59 UTC
**System information**
- OS Platform and Distribution (Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): TF 2.3.0

**Command used to run the converter or code if you’re using the Python API**
```
def representative_data_gen():
    dataset_list = os.listdir(data_dir)
    num_calibration_images = 100
    norm_factor = 255.0
    for i in range(num_calibration_images):
        image_name = next(iter(dataset_list))
 
        image = cv2.imread(os.path.join(data_dir, image_name), 1)
        image = image.astype(np.float32)
        image = image/norm_factor

        image = tf.expand_dims(image, 0)
        yield [image]


converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]

# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

converter.allow_custom_ops = True
tflite_model = converter.convert()
```

** Model definition:
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def conv2d_block_3layers(input_tensor, n_filters, kernel_size=3, dropout=0.2, 
                         batchnorm=True, activation=True):
    # first layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(input_tensor)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    x = layers.Dropout(dropout)(x)
    # second layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    x = layers.Dropout(dropout)(x)
    # third layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    return x

def UNET_v2(nClasses=25, input_height=288, input_width=224, n_filters=64, dropout=0.2, 
            batchnorm=True, activation=True):
  
    img_input = layers.Input(shape=(input_height, input_width, 3))  

    c1 = conv2d_block_3layers(img_input, n_filters * 1, kernel_size=3, batchnorm = batchnorm, activation=activation)
    p1 = layers.MaxPooling2D((2, 2))(c1) 

    c2 = conv2d_block_3layers(p1, n_filters * 2, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p2 = layers.MaxPooling2D((2, 2))(c2) 

    c3 = conv2d_block_3layers(p2, n_filters * 4, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p3 = layers.MaxPooling2D((2, 2))(c3) 

    c4 = conv2d_block_3layers(p3, n_filters * 4, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p4 = layers.MaxPooling2D((2, 2))(c4) 

    c5 = conv2d_block_3layers(p4, n_filters = n_filters * 8, kernel_size=3, batchnorm = batchnorm, activation=activation)
    p5 = layers.Dropout(dropout)(c5) 

    up6  = layers.Conv2DTranspose(n_filters * 4, kernel_size=(3,3), strides=(2,2), padding="same")(p5)
    # up6  = layers.UpSampling2D()(p5) 
    m6 = layers.Concatenate(axis=3)([up6, c4])
    c6 = conv2d_block_3layers(m6, n_filters * 4, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up7 = layers.Conv2DTranspose(n_filters * 4, kernel_size=(3,3), strides=(2,2), padding="same")(c6)
    # up7  = layers.UpSampling2D()(c6) 
    m7 = layers.Concatenate(axis=3)([up7, c3])
    c7 = conv2d_block_3layers(m7, n_filters * 4, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up8 = layers.Conv2DTranspose(n_filters * 2, kernel_size=(3,3), strides=(2,2), padding="same")(c7)
    # up8  = layers.UpSampling2D()(c7) 
    m8  = layers.Concatenate(axis=3)([up8, c2])
    c8 = conv2d_block_3layers(m8, n_filters * 2, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up9 = layers.Conv2DTranspose(n_filters * 1, kernel_size=(3,3), strides=(2,2), padding="same")(c8)
    # up9  = layers.UpSampling2D()(c8) 
    m9 = layers.Concatenate(axis=3)([up9, c1])
    c9 = conv2d_block_3layers(m9, n_filters * 1, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    outputlayer = tf.keras.layers.Conv2D(filters=nClasses, kernel_size=1, activation="softmax")(c9)
    
    model = tf.keras.Model(inputs=img_input, outputs=outputlayer)
    model.summary(line_length=124)
    return model
```
 
**The output from the converter invocation**
```
Traceback (most recent call last):
  File "keras_to_tflite.py", line 105, in <module>
    tflite_model = converter.convert()
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 831, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 452, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 98, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op: %

```

The model architecture uses Conv2D, batchnormalization, dropout, MaxPooling2D, Conv2DTranspose, Concatenate layers. Is the operation % used in any of the mentioned layers? The % operation is not used at all.

**Comment by bhack** [comment] 2020-09-14 14:18
Can you please attach your model/ share google colab code to debug further? Thanks!

**Comment by ehazrati** [comment] 2020-09-14 14:28
[test_model.zip](https://github.com/tensorflow/tensorflow/files/5219078/test_model.zip)
Here is the Keras *.hdf5 model file.

**Comment by bhack** [comment] 2020-09-14 14:38
I think you need to update your example also with the missing source of `converter.representative_dataset = representative_data_gen`

**Comment by amahendrakar** [comment] 2020-09-14 15:57
@ehazrati,
On running the code I am facing an error stating `NameError: name 'data_dir' is not defined`.

In order to expedite the trouble-shooting process, could you please provide the dataset you are using as well. Thanks!

**Comment by ehazrati** [comment] 2020-09-15 07:31
[dataset.tar.gz](https://github.com/tensorflow/tensorflow/files/5223152/dataset.tar.gz)
Here is the example data set. Thanks.

**Comment by bhack** [comment] 2020-09-15 11:16
You are using what in Doc is described as [Integer only quantizzation](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization):
> To quantize the input and output tensors, and make the converter throw an error if it encounters an operation it cannot quantize, convert the model again with some additional parameters.

You have some operation that it cannot quantize.

You can check these running your example with `pip install tf-nightly`:

```
RuntimeError: Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'DIV'.
```

**Comment by ehazrati** [comment] 2020-09-15 14:13
The problem is I want to be able to perform the inference on a Coral USB accelerator which has an edge TPU and it is an "integer-only" hardware. Therefore, I have to convert using integer-only quantization. For that to work, all operations in the model should have a quantized implementation, otherwise I won't get an end-to-end integer-only model and I cannot run it on an edge TPU. 
As mentioned in the previous comments, the model uses the following layers:
- layers.Conv2D 
- layers.BatchNormalization
- layers.Dropout
- layers.MaxPooling2D 
- layers.Concatenate
- layers.Activation('relu')
- layers.Conv2DTranspose  or layers.UpSampling2D
- layers.Activation('softmax')

According to the guides, the above layers all have a quantized implementation, except for the  layers.Conv2DTranspose layer which I am not sure. For that reason I created two models one with layers.Conv2DTranspose and another one with layers.UpSampling2D.
Trying both, I got the sane Error you mentioned in your comment: 
```
Traceback (most recent call last):
  File "keras_to_tflite.py", line 108, in <module>
    tflite_model = converter.convert()
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 847, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 648, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 476, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/home/ths/anaconda3/envs/py37_tf23/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 98, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'DIV'.
```
I suspect that the error could be related to Softmax, as it is the one uses EXP and DIV operations. But, then I am able to perform all the steps mentioned in this tutorial: convert, compile, and run the model on DPU, without any problem (using tensorflow2.3): 
https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb#scrollTo=19IQ2gqneqmS
The model above uses Softmax as well.

Any idea what is happening? Is there a way to check where exactly the operations 'EXP'  and 'DIV' are performed in the model?    
Thanks.

**Comment by bhack** [comment] 2020-09-15 14:26
Can you edit/complete you example with your dummy model definition and saving instead of the saved file? 
So that we have a minimal but complete example to run.

Thanks

**Comment by ehazrati** [comment] 2020-09-16 08:19
** model definition
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def conv2d_block_3layers(input_tensor, n_filters, kernel_size=3, dropout=0.2, 
                         batchnorm=True, activation=True):
    # first layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(input_tensor)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    x = layers.Dropout(dropout)(x)
    # second layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    x = layers.Dropout(dropout)(x)
    # third layer
    x = layers.Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),
                      padding = 'same')(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    if activation:
        x = layers.Activation('relu')(x)
    return x

def UNET_v2(nClasses=25, input_height=288, input_width=224, n_filters=64, dropout=0.2, 
            batchnorm=True, activation=True):
  
    img_input = layers.Input(shape=(input_height, input_width, 3))  

    c1 = conv2d_block_3layers(img_input, n_filters * 1, kernel_size=3, batchnorm = batchnorm, activation=activation)
    p1 = layers.MaxPooling2D((2, 2))(c1) 

    c2 = conv2d_block_3layers(p1, n_filters * 2, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p2 = layers.MaxPooling2D((2, 2))(c2) 

    c3 = conv2d_block_3layers(p2, n_filters * 4, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p3 = layers.MaxPooling2D((2, 2))(c3) 

    c4 = conv2d_block_3layers(p3, n_filters * 4, kernel_size=3, batchnorm = batchnorm,  activation=activation)
    p4 = layers.MaxPooling2D((2, 2))(c4) 

    c5 = conv2d_block_3layers(p4, n_filters = n_filters * 8, kernel_size=3, batchnorm = batchnorm, activation=activation)
    p5 = layers.Dropout(dropout)(c5) 

    up6  = layers.Conv2DTranspose(n_filters * 4, kernel_size=(3,3), strides=(2,2), padding="same")(p5)
    # up6  = layers.UpSampling2D()(p5) 
    m6 = layers.Concatenate(axis=3)([up6, c4])
    c6 = conv2d_block_3layers(m6, n_filters * 4, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up7 = layers.Conv2DTranspose(n_filters * 4, kernel_size=(3,3), strides=(2,2), padding="same")(c6)
    # up7  = layers.UpSampling2D()(c6) 
    m7 = layers.Concatenate(axis=3)([up7, c3])
    c7 = conv2d_block_3layers(m7, n_filters * 4, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up8 = layers.Conv2DTranspose(n_filters * 2, kernel_size=(3,3), strides=(2,2), padding="same")(c7)
    # up8  = layers.UpSampling2D()(c7) 
    m8  = layers.Concatenate(axis=3)([up8, c2])
    c8 = conv2d_block_3layers(m8, n_filters * 2, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    up9 = layers.Conv2DTranspose(n_filters * 1, kernel_size=(3,3), strides=(2,2), padding="same")(c8)
    # up9  = layers.UpSampling2D()(c8) 
    m9 = layers.Concatenate(axis=3)([up9, c1])
    c9 = conv2d_block_3layers(m9, n_filters * 1, kernel_size = 3, batchnorm = batchnorm, activation=activation)

    outputlayer = tf.keras.layers.Conv2D(filters=nClasses, kernel_size=1, activation="softmax")(c9)
    
    model = tf.keras.Model(inputs=img_input, outputs=outputlayer)
    model.summary(line_length=124)
    return model
```

**Comment by amahendrakar** [comment] 2020-09-21 16:10
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/3043b00079794220298cb59fb238ba75/43207.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/806ca7fbab4575784d6459cab4ee5fff/43207-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by bhack** [comment] 2020-09-21 17:42
@ehazrati I saw you model and I think that what is missing is that you are using the `softmax` activation in your conv. This is different from the official colab that you have mentioned in this ticket cause there the `softmax` activation is in a Dense layer:

` outputlayer = tf.keras.layers.Conv2D(filters=nClasses, kernel_size=1, activation="softmax")(c9)`

**Comment by ehazrati** [comment] 2020-09-22 09:13
Clear, thanks for the support and clarification.

**Comment by teijeong** [comment] 2020-09-25 05:43
Hi @njeffrie,

Seems the problem is almost resolved, but the initial error message seems weird. Can you take a look?
`RuntimeError: Quantization not yet supported for op: %`

**Comment by bhack** [comment] 2020-09-25 10:39
@teijeong Just a note, the original message was on TF 2.3 only. 
I don't know If you want to improve the nightly error message.

**Comment by teijeong** [comment] 2020-09-28 01:48
Ah I see, thanks!

Hi @ehazrati, could you close this issue if it's resolved?

**Closed** 2020-09-28 08:09 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, type:bug

**Comment by littleTitan** [comment] 2022-03-05 16:48
I resolved this error by using TOCO:
converter.experimental_new_converter = False
