### ISSUE TITLE
Kernel Restarting The kernel appears to have died. It will restart automatically. importing tensorflow

### ISSUE THREAD

**Issue by yoasaine** [tensorflow/tensorflow#21554] opened 2018-08-12 06:49 UTC
hey comrades. am a new ubuntu user, i read most articles on how to install tensorflow in anaconda so that i can run it in the notebook.
i am however facing this challenge which is disturbing having thought i've succeeded. and it's nagging me.
the moment i do "import tensorflow as tf", and upon running, i receive the following;
_**Kernel Restarting
The kernel appears to have died. It will restart automatically.**_
i am totally beaten. what should i do? any help is highly regarded.
Note that my kernel works fine with other import of numpy, pandas,... etc. Issues are only available with import of tensorflow.
thank you.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-08-31 15:04
It has been 18 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by NoreenMekky** [comment] 2018-09-15 11:12
I got the same problem after installation, so I just updated my packages and it's now working.
If you are using anaconda you can simply do `conda update anaconda --yes`
Hope it helps.

**Comment by ymodak** [comment] 2018-09-28 20:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 20:44 UTC
Labels: stat:awaiting response

**Comment by shekbruce** [comment] 2019-03-19 02:41
I resolved this issue by upgrading numpy and importing numpy before tensorflow.  my numpy version was 1.15.4. Upgraded it  to  1.16.2.
