### ISSUE TITLE
Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array.

### ISSUE THREAD

**Issue by jnphilipp** [tensorflow/tensorflow#47242] opened 2021-02-18 11:44 UTC
**System information**
- OS Platform and Distribution: Arch Linux
- TensorFlow installed from package: python-tensorflow
- TensorFlow version: unknown 2.4.1
- Python version: 3.9.1
- CUDA/cuDNN version: No GPU

**Standalone code to reproduce the issue**
```python
from tensorflow.keras.layers import Embedding, Input, GRU

x = Input(shape=(None,))
x = Embedding(input_dim=50, output_dim=16, mask_zero=True)(x)
x = GRU(units=256)(x)
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/jnphilipp/Nextcloud/Code/jnphilipp/deep_learning/test3.py", line 5, in <module>
    x = GRU(units=256)(x)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 660, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 439, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 859, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 642, in get_initial_state
    init_state = get_initial_state_fn(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1948, in get_initial_state
    return _generate_zero_filled_state_for_cell(self, inputs, batch_size, dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2987, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3005, in _generate_zero_filled_state
    return create_zeros(state_size)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 3000, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Comment by alik604** [comment] 2021-02-19 06:13
+1! I'm getting the same issue.

**Comment by Saduf2019** [comment] 2021-02-19 07:41
@jnphilipp 
I ran the code shared above it seems incomplete, please find the [gist here ](https://colab.research.google.com/gist/Saduf2019/883a41f4a5a9737bfb85138d5b476d09/untitled545.ipynb)[there is no error or output]
menwhile can you please refer to these resolved issues and let us know: [link](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy), [link2](https://github.com/tensorflow/tensorflow/issues/36792)

**Comment by jnphilipp** [comment] 2021-02-19 12:27
@Saduf2019  I know the code looks incomplete, but it is the minimum that I need to get the error message above.
As to the issues: I don't even import numpy.

**Comment by ghylander** [comment] 2021-02-19 13:55
i too am having this issue just now
i have been running the same scripts for months, and i just atrted having this isseu today when i re-reun them. Last time they worked was 7 days ago (i even have the git commit uploading the then freshly executed script)

the only thing that changed in between was an updated version of numpy

**Comment by ZeroOut** [comment] 2021-02-24 12:05
Me too, after the last update.

**Comment by jvishnuvardhan** [comment] 2021-02-24 16:33
@jnphilipp I ran your code in `TF2.4.1` and I don't see any error as you described. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/9259875409e4f892b4db22fe11e12322/untitled545.ipynb). Am i missing something here?

@ZeroOut @ghylander Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by ghylander** [comment] 2021-02-25 07:26
@jvishnuvardhan 
yes
'numpy.__version__'
'1.19.3'
this problem arises with numpy version 1.20 and 1.21

**Comment by nickion** [comment] 2021-02-25 16:33
> @jvishnuvardhan
> yes
> `numpy.__version__`
> `1.19.3`
> this problem arises with numpy version 1.20 and 1.21

Thanks! The same issue just started happening on my setup, and downgrading to 1.19.4 solved.

**Comment by jnphilipp** [comment] 2021-02-25 17:01
@jvishnuvardhan no, you're not missing anything in the gist.

**Comment by jvishnuvardhan** [comment] 2021-02-25 23:28
> .

So, the issue was resolved for you.? Thanks!

**Comment by jvishnuvardhan** [comment] 2021-02-25 23:29
> @jvishnuvardhan no, you're not missing anything in the gist.

So, the issue was resolved for you.? Thanks!

**Comment by jvishnuvardhan** [comment] 2021-02-25 23:35
@ZeroOut @ghylander As mentioned by you, looks like this was related to numpy version. I just checked that TF was built with `'numpy ~= 1.19.2'` . Please check [here](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/tools/pip_package/setup.py#L84) to know all the packages and their versions that were used when building TF `pip` package`2.4`. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-02-26 02:55
Similar issues that are due to numpy version 1.20.

https://github.com/tensorflow/tensorflow/issues/47263
https://github.com/tensorflow/tensorflow/issues/47311

**Comment by cuikunyu** [comment] 2021-03-01 08:22
I met a similar problem when I run the BERT model (repo: https://github.com/google-research/bert).
I have downgrade Numpy from 1.20 to 1.19.2 and the problem solved.
Thanks!

**Comment by jvishnuvardhan** [comment] 2021-03-01 19:56
I am closing this issue as this is more related to numpy version as mentioned above and not related core Tensorflow. Loading correct numpy version resolves the issue. Thanks!

**Closed by jvishnuvardhan** 2021-03-01 19:56 UTC
Labels: TF 2.4, comp:keras, type:bug

**Comment by jvishnuvardhan** [comment] 2021-03-17 06:22
Moved to #47691

**Comment by dh7hong** [comment] 2021-08-15 18:43
Try making a new python environment and install tensorflow==2.4.0

**Comment by Rayjrz** [comment] 2021-12-08 18:53
> @jvishnuvardhan yes `numpy.__version__` `1.19.3` this problem arises with numpy version 1.20 and 1.21

Saved my day! Thanks!

**Comment by JafirDon** [comment] 2022-02-24 10:33
### [Solved]
I have the same error when training the data, even also try to downgrade the NumPy version, but it not be fixed.
**Finally, I solved that issue**. Try the below command:

`!pip install numpy==1.17.4`
`!pip install pycocotools==2.0.0`
