### ISSUE TITLE
tf.keras.estimator.model_to_estimator ignores layer reuse for Sequential models

### ISSUE THREAD

**Issue by artkorenev** [tensorflow/tensorflow#21778] opened 2018-08-21 23:58 UTC
### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Mobile device**: N/A
- **TensorFlow installed from**: binary
- **TensorFlow version**: 1.10.0
- **Python version**: 3.6
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: `python my_custom_script.py`

**Overview:**

If a model is created using `tf.keras.models.Sequential` with reuse of some layers (including those that are parameterless) then the estimator created from `tf.keras.estimator.model_to_estimator` may contain a different model from the original Keras model.

This also may produce an error of shape mismatch in case that the `tf.keras.estimator.model_to_estimator` is called after fitting the Sequential model. 

**Simple example:**
```
import tensorflow as tf
import numpy as np

max_pool = tf.keras.layers.MaxPooling2D(2)
model = tf.keras.Sequential([
    max_pool,
    max_pool,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy')

X, y = np.zeros((32, 8, 8, 1)), np.ones((32,))
model.fit(X, y)

tf.keras.estimator.model_to_estimator(keras_model=model)
```
**The error produced:**
```
...
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 847, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (16, 1) and (4, 1) are incompatible
```

**Explanation:**

The mismatch happens because `tf.keras.estimator.model_to_estimator` traverses `model.layers` which has a single entry of max pooling. Therefore, instead of making 2 max pooling operations it performs a single one which results in **16** outputs after `tf.keras.layers.Flatten()` instead of **4** that was intended initially.

If `model.fit` is not called then `tf.keras.estimator.model_to_estimator` does not produce any errors which is actually more concerning since it may be not obvious that the new model is different from the initial Sequential model.

**Comment by tensorflowbutler** [comment] 2018-08-22 06:41
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by artkorenev** [comment] 2018-08-22 08:45
Done

**Comment by asimshankar** [comment] 2018-08-23 05:01
@fchollet @pavithrasv @anj-s @tanzhenyu  - mind taking a look?

**Comment by pavithrasv** [comment] 2018-08-23 20:36
@artkorenev Can you try this with the latest tf-nightly? This should have been fixed with the following change: https://github.com/tensorflow/tensorflow/commit/42b61fbd380a7b6c3912e5a91ff09738ace7073c#diff-2afc7c6acfd68474e1e8c56718431276

Thank you,
Pavithra

**Comment by artkorenev** [comment] 2018-08-24 10:10
I used the build `1.11.0-dev20180824` and now creating the estimator doesn't produce any errors.
However, if I run `estimator.train` (or `estimator.predict`) then the underlying `model_fn` function fails.

**The exception:** 
```
Traceback (most recent call last):
  File "~/my_custom_script.py", line 26, in <module>
    print(estimator.train(input_fn=input_fn, steps=1))
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1183, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1213, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1171, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py", line 213, in model_fn
    labels)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py", line 188, in _clone_and_build_model
    in_place_reset=(not keras_model._is_graph_network))
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 441, in clone_and_build_model
    _in_place_subclassed_model_reset(clone)
  File "~/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 316, in _in_place_subclassed_model_reset
    name = layers_to_names[layer]
KeyError: <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x7fae4b685c88>
```

**The slightly updated code example to reproduce the bug:**
```
import tensorflow as tf
import numpy as np

max_pool = tf.keras.layers.MaxPooling2D(2)
model = tf.keras.Sequential([
    max_pool,
    max_pool,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer=tf.train.AdamOptimizer(), loss='binary_crossentropy')

X, y = np.zeros((32, 8, 8, 1)), np.ones((32, 1))
model.fit(X, y)

estimator = tf.keras.estimator.model_to_estimator(keras_model=model)

input_fn = tf.estimator.inputs.numpy_input_fn(
    x=X,
    y=y,
    batch_size=32,
    num_epochs=1,
    shuffle=False
)

estimator.train(input_fn=input_fn, steps=1)
```

I also tried this on a model created from Functional API and it works fine without any errors

**Comment by tensorflowbutler** [comment] 2018-09-08 18:47
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:52
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:50
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:52
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:13
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:48
Nagging Assignees @fchollet, @pavithrasv, @tanzhenyu: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by duongludien** [comment] 2019-03-03 02:02
I had the same error. So, I try to add `input_shape` argument into the first layer of my model, the problem was resolved.

```
model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(
            input_shape=(IMAGE_SIZE, IMAGE_SIZE, IMAGE_DEPTH),
            filters=96, kernel_size=11, strides=4, padding='valid'),
        tf.keras.layers.MaxPooling2D(pool_size=3, strides=2, padding='valid'),
        tf.keras.layers.Conv2D(filters=256, kernel_size=5, strides=1, padding='same'),
        tf.keras.layers.MaxPooling2D(pool_size=3, strides=2, padding='valid'),
        tf.keras.layers.Conv2D(filters=384, kernel_size=3, strides=1, padding='same'),
        tf.keras.layers.Conv2D(filters=384, kernel_size=3, strides=1, padding='same'),
        tf.keras.layers.Conv2D(filters=256, kernel_size=3, strides=1, padding='same'),
        tf.keras.layers.MaxPooling2D(pool_size=3, strides=2, padding='valid'),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(units=4096),
        tf.keras.layers.Dense(units=4096),
        tf.keras.layers.Dense(units=num_classes),
    ])
```

**Comment by tanzhenyu** [comment] 2019-04-26 17:33
Looks like there is an alternative solution to this. Closing it.

**Closed by tanzhenyu** 2019-04-26 17:33 UTC
