### ISSUE TITLE
XLA throws an error when beta1 = 0 in Adam optimizer

### ISSUE THREAD

**Issue by fengyang0317** [tensorflow/tensorflow#40832] opened 2020-06-26 14:17 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- CUDA/cuDNN version: 7.6
- GPU model and memory: GTX 1070

**Describe the current behavior**
Throws an error when beta1 = 0.

**Describe the expected behavior**
No errors.

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/fengyang0317/26486c2740955cff9c88f7d02e9832a0/use-xla-with-tf-function.ipynb

**Comment by Saduf2019** [comment] 2020-06-29 16:35
@fengyang0317 
I ran the code shared and do not face any errors, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f477d02e1888d8d4a9d12ea2dcbe5a71/untitled247.ipynb)

**Comment by jvishnuvardhan** [comment] 2020-09-12 20:40
@fengyang0317 I think this was resolved in recent `tf-nightly`. I cannot reproduce the issue with `tf-nightly`.

Can you please verify once and close the issue. Thanks!

**Closed** 2020-09-13 00:04 UTC
Labels: TF 2.2, comp:keras, stat:awaiting response, type:bug
