### ISSUE TITLE
TensorFlow 2.2.0 doesn't detect GPU with CUDA version 10.2

### ISSUE THREAD

**Issue by gauravmunjal13** [tensorflow/tensorflow#41374] opened 2020-07-14 11:34 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: Tesla K40m

**Describe the current behavior**
Keras (version 2.4.3) with tensorflow as backend doesn't detect the GPU. This is verified by running:
`tf.config.experimental.list_physical_devices('GPU')`
returns emplty list [].

Also, checked as:
`from tensorflow.python.client import device_lib`
`print(device_lib.list_local_devices())`

returns: 
_[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11064916497553704899
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 5592130336569042773
physical_device_desc: "device: XLA_CPU device"
]_

**Describe the expected behavior**
It should detect the GPU as detected by PyTorch as:
`torch.cuda.is_available()`
Outputs: True

`torch.cuda.current_device()`
Outputs: 0

`torch.cuda.get_device_name(0)`
Outputs: 'Tesla K40m'

**Standalone code to reproduce the issue**
Not required in this case as it seems to be some version mismatch issue.

**Other info / logs** 
Attaching the tf_env.txt output file for the environment settings.
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/4918521/tf_env.txt)

Thanks!

**Comment by gauravmunjal13** [comment] 2020-07-14 12:49
Here's the update:
It works when I install separately tensorflow with GPU support:
`conda install tensorflow-gpu`

Thus,
`tf.test.is_gpu_available()`
returns: True

`K.tensorflow_backend._get_available_gpus()`
returns:
['/job:localhost/replica:0/task:0/device:GPU:0']

And, `device_lib.list_local_devices()`
returns:
_[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15279102792666353313
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 8743602476137325517
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 11315983156
locality {
  bus_id: 2
  numa_node: 1
  links {
  }
}
incarnation: 5952156843105137928
physical_device_desc: "device: 0, name: Tesla K40m, pci bus id: 0000:84:00.0, compute capability: 3.5"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 17355483587532015042
physical_device_desc: "device: XLA_GPU device"
]_

I am wondering, isn't this possible with TensorFlow 2?

Thanks!

**Comment by amahendrakar** [comment] 2020-07-15 11:12
@gauravmunjal13,
The `cuda libs` section from the environment settings you've provided is blank. The output should be similar to

```
== cuda libs  ===================================================
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudart-1b201d85.so.10.1
/usr/local/lib/python3.6/dist-packages/torch/lib/libcudart-1b201d85.so.10.1
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.1/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.1/doc/man/man7/libcudart.7
```
Attached [gist](https://colab.research.google.com/gist/amahendrakar/a3d9832cb510347cadde7ac37d5f7d37/41374.ipynb) for reference. 


Please take a look at the [tested build configuration](https://www.tensorflow.org/install/source#gpu) and check if you are running the compatible CUDA and cuDNN versions. Thanks!

**Comment by gauravmunjal13** [comment] 2020-07-15 16:32
@amahendrakar 
Thanks for your response!

Based on shared tested build configuration link, it does mention that TF 2.2.0 matches with CUDA 10.1. However, as stated in my query I am using Tesla K40m with Driver Version: 440.31 and CUDA Version: 10.2.

However, now I am using TF 1.14.0 which can successfully detect this GPU. 

Regarding the cuda libs, I tried again but sadly the cuda libs are not captured again via that script. I am working on a high performing computing cluster, thus it requires submitting job to access GPU. But I could see that via running:
`tf.test.is_gpu_available()`
_2020-07-15 21:56:52.773131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:84:00.0
2020-07-15 21:56:52.773189: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-07-15 21:56:52.773206: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-07-15 21:56:52.773221: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-07-15 21:56:52.773234: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-07-15 21:56:52.773248: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-07-15 21:56:52.773261: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-07-15 21:56:52.773275: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-07-15 21:56:52.774936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-07-15 21:56:52.774990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-15 21:56:52.775016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2020-07-15 21:56:52.775028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2020-07-15 21:56:52.776741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 10791 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:84:00.0, compute capability: 3.5)
True_

**Note** These results are with TF 1.14.0. 

Thanks!

**Comment by amahendrakar** [comment] 2020-07-16 18:19
> However, now I am using TF 1.14.0 which can successfully detect this GPU.

@gauravmunjal13,
Thank you for the update. Do you want to close this issue or find out the cause of the GPU inconsistency?

**Comment by gauravmunjal13** [comment] 2020-07-17 05:20
@amahendrakar 
I have moved on with TF 1.14.0 due to project urgency. However, if it's possible to work with TF 2.2.0 on CUDA 10.2, I would like to know what shall I do to make it work.
Thanks for your help!

**Comment by amahendrakar** [comment] 2020-07-21 15:36
@gauravmunjal13,
Please check [this comment](https://github.com/tensorflow/tensorflow/issues/38194#issuecomment-657233766) from a similar issue and let us know if it helps. Thanks!

**Closed** 2020-08-04 17:23 UTC
Labels: TF 2.2, comp:gpu, stalled, stat:awaiting response, type:bug

**Comment by kaustubholpadkar** [comment] 2020-08-11 00:41
I am also facing the same issue with Tensorflow2.2 and Cuda-10.1. PyTorch is able to detect and utilize GPU, but tensorflow is not.

**Comment by amahendrakar** [comment] 2020-08-11 15:58
@kaustubholpadkar,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by nguyenhoa93** [comment] 2020-10-07 09:03
> I am also facing the same issue with Tensorflow2.2 and Cuda-10.1. PyTorch is able to detect and utilize GPU, but tensorflow is not.

I also faced this problem when installing TF2.2 via `conda`, I uninstalled and reinstalled with `pip` and it worked.
