### ISSUE TITLE
Pycharm 3.9 not supporting Tensorflow

### ISSUE THREAD

**Issue by sbarbosa0714** [tensorflow/tensorflow#44400] opened 2020-10-28 20:39 UTC
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
Hi!, i'm someone thats completley new to coding, now i was instructed to download tensorflow thru pycharm (i prefer to have things stored physically on my device rather than online) as i tried all of the guides i realized that for most platforms i was getting the exact same answer, i was searching breifly and saw that there wasnt another thread about this topic, so thank you to anyone that interacts with this!
![image](https://user-images.githubusercontent.com/73615107/97494015-c7bcd580-1933-11eb-86b9-6fd88744b189.png)

**Comment by ravikyram** [comment] 2020-10-29 12:51
@sbarbosa0714 

TensorFlow pip packages are compatible with Python 3.5–3.8.

From the below link we can see that the whl files are available upto Python v3.8.
https://pypi.org/project/tf-nightly/2.4.0.dev20201023/#files

Python3.9 is not yet supported. Thanks!

**Comment by mihaimaruseac** [comment] 2020-11-05 18:51
Duplicate of #44485 (assuming you meant/use Python 3.9)

Not that pycharm still downloads stuff locally.

**Closed by mihaimaruseac** 2020-11-05 18:51 UTC
Labels: stalled, stat:awaiting response
