### ISSUE TITLE
Error reported to Coordinator: /dbfs/FileStore/tables/TFOS/trainData/checkpoint.tmpb97208e81436466b80430829067e21d8; Input/output error

### ISSUE THREAD

**Issue by vishal-kr-yadav** [tensorflow/tensorflow#20090] opened 2018-06-18 05:06 UTC
018-06-12 14:59:28,653 INFO (MainThread-2183) global step 75: loss = 1.4016 (7.176 sec/step)
2018-06-12 14:59:35,636 INFO (MainThread-2183) global step 76: loss = 1.3862 (6.978 sec/step)
2018-06-12 14:59:43,038 INFO (MainThread-2183) global step 77: loss = 3.2210 (7.398 sec/step)
2018-06-12 14:59:50,353 INFO (MainThread-2183) global step 78: loss = 1.3114 (7.311 sec/step)
2018-06-12 14:59:57,775 INFO (MainThread-2183) global step 79: loss = 1.3847 (7.417 sec/step)
2018-06-12 15:00:05,181 INFO (MainThread-2183) global step 80: loss = 1.3856 (7.402 sec/step)
2018-06-12 15:00:12,513 INFO (MainThread-2183) global step 81: loss = 1.2985 (7.327 sec/step)
2018-06-12 15:00:20,160 INFO (MainThread-2183) global step 82: loss = 1.2625 (7.643 sec/step)
2018-06-12 15:00:27,564 INFO (MainThread-2183) global step 83: loss = 1.2674 (7.400 sec/step)
2018-06-12 15:00:32,553 INFO (Thread-4-2183) Error reported to Coordinator: /dbfs/FileStore/tables/TFOS/trainData/checkpoint.tmpb97208e81436466b80430829067e21d8; Input/output error
Traceback (most recent call last):
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 495, in run
    self.run_loop()
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 1104, in run_loop
    global_step=self._sv.global_step)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1686, in save
    save_relative_paths=self._save_relative_paths)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1041, in _update_checkpoint_state
    text_format.MessageToString(ckpt))
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 431, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 410, in rename
    compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: /dbfs/FileStore/tables/TFOS/trainData/checkpoint.tmpb97208e81436466b80430829067e21d8; Input/output error
2018-06-12 15:00:34,910 INFO (MainThread-2183) global step 84: loss = 2.6778 (7.342 sec/step)
2018-06-12 15:00:34,913 INFO (MainThread-2183) Finished training! Saving model to disk.
18/06/12 15:02:02 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 990, in managed_session
    yield sess
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 780, in train
    sv.saver.save(sess, sv.save_path, global_step=sv.global_step)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1686, in save
    save_relative_paths=self._save_relative_paths)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1041, in _update_checkpoint_state
    text_format.MessageToString(ckpt))
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 431, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 410, in rename
    compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
  File "/databricks/python/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: /dbfs/FileStore/tables/TFOS/trainData/checkpoint.tmp51f40c3652e54c3b93209b402acfc49a; Input/output error

**Comment by tensorflowbutler** [comment] 2018-06-18 12:33
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vishal-kr-yadav** [comment] 2018-06-18 12:58
**Have I written custom code --> No just clone it from git (tensorflow/models repository)
TensorFlow installed from --> using azure dataBricks clusters (tensorflow pre-installed with latest version)
TensorFlow version->1-.8
CUDA/cuDNN version -->pre-installed in azure dataBricks clusters
GPU model and memory ->
Exact command to reproduce**  ->train.py (and passing all the necessary argument)

-->We are storing all the checkpoint in **dbfs** .
Q) is tensorflow is having any issues while saving its checkpoint in dbfs?

Some pointers  i)when we ran for only 50 steps of training, it ran successfully and finished the training without any error 
ii)After testing with 50 odd steps when we increase the number of steps from 50 to 20k it get errored out between 80 to 90 steps (error is mentioned above)

**Comment by asimshankar** [comment] 2018-06-18 19:12
I don't know much about `dbfs`, but from the error message and stacktrace it seems like the program is having trouble writing the checkpoint. Is it possible that a quota or file limit is being hit? If you delete the older checkpoints, can you make more progress>

**Comment by vishal-kr-yadav** [comment] 2018-06-19 06:13
I have tried deleting the older checkpoints but did't work.

**Comment by tensorflowbutler** [comment] 2018-07-03 12:49
Nagging Assignee @michaelisard: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by michaelisard** [comment] 2018-07-11 22:21
Sorry for the delay in responding to this. It's pretty hard to see what the problem could be without more information. Your rename is failing with an i/o error. Probably that's because e.g. there is a name clash, or as @asimshankar mentioned maybe you don't have space/quota, or...

@ispirmustafa do you know anything about dbfs?

**Comment by ispirmustafa** [comment] 2018-07-12 10:05
unfortunately i don't know.

**Comment by tensorflowbutler** [comment] 2018-07-27 18:54
Nagging Assignee @ispirmustafa: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:58
Nagging Assignee @ispirmustafa: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 08:05
Nagging Assignee @ispirmustafa: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:44
Nagging Assignee @ispirmustafa: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ispirmustafa** [comment] 2018-09-18 00:13
Un-assigning myself so that it will be triaged.

**Comment by wt-huang** [comment] 2018-09-18 18:00
@vishal-kr-yadav could you check if transport endpoint is not connected? Probably start with test run on checkpoint to make sure all nodes are alive.

**Comment by vishal-kr-yadav** [comment] 2018-09-19 03:30
@wt-huang yes i checked with this one also, it seems that the issue is not on the tensorflow side. As we are writing the checkpoints to dbfs, its throwing the error. We checked with other storage system and it worked fine.
If anyone of you could simply run a tensorflow object detection model and check whether you are able to write the checkpoints in dbfs or not.

**Comment by tensorflowbutler** [comment] 2018-10-03 18:54
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment] 2018-10-04 19:29
@vishal-kr-yadav Good to know that the issue is not related to TensorFlow. Is this issue still blocking you? I was able to write the checkpoints in dbfs.

**Comment by sophia-wright-blue** [comment] 2018-10-04 21:51
I tried saving checkpoints on dbfs about a month ago, and I wasn't able to, its interesting that you're able to do this @wt-huang , do you know if there is a public example of this somewhere?

**Comment by dnwarnock** [comment] 2018-10-16 16:10
@wt-huang Is it possible for us to view the notebook you used to write checkpoints to dbfs?

**Comment by wt-huang** [comment] 2018-10-16 20:39
@dnwarnock As mentioned above, this issue is not TensorFlow related. There were tweaks and fiddling I had to go through to get it to work which may not be optimal. FWIW the notebook I used is one of the image detection examples.

**Comment by wt-huang** [comment] 2018-10-26 13:15
Closing, feel free to reopen if any additional questions.

**Closed by wt-huang** 2018-10-26 13:15 UTC
Labels: type:support
