### ISSUE TITLE
Problem building label_image

### ISSUE THREAD

**Issue by informatica92** [tensorflow/tensorflow#1333] opened 2016-02-29 16:44 UTC
Hi all, 
I tried to build the label_image example (I have tensor flow version 0.7 and I installed bazel) but when I build the example with
`../../bin/bazel build tensorflow/examples/label_image/...`
I get:
`INFO: Found 2 targets...
ERROR: /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
/home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow/external/png_archive/libpng-1.2.53 /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow
/tmp/tmp.dPQmFTp3hh /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow/external/png_archive/libpng-1.2.53 /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow`

At the end of this, in bazel-bin/tensorflow/examples/label_image I have no executable file, only a manifest and a param file.
What's wrong?

**Comment by vrv** [comment] 2016-02-29 18:55
Can you try building with --verbose_failures and repaste your logs?

**Comment by informatica92** [comment] 2016-03-01 09:36
Thanks for reply vrv!
New output is this:
`INFO: Found 2 targets...

ERROR: /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/external/png_archive/BUILD:23:1: Executing genrule @png_archive//:configure failed: bash failed: error executing command (cd /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow && \  exec env - \
    PATH=/home/informatica/tensorflow/bin:/home/informatica/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/png_archive/libpng-1.2.53; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $workdir/config.h bazel-out/local_linux-fastbuild/genfiles/external/png_archive/libpng-1.2.53; rm -rf $workdir;'): bash failed: error executing command 
  (cd /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow && \ exec env - \
    PATH=/home/informatica/tensorflow/bin:/home/informatica/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; pushd external/png_archive/libpng-1.2.53; workdir=$(mktemp -d -t tmp.XXXXXXXXXX); cp -a * $workdir; pushd $workdir; ./configure --enable-shared=no --with-pic=no; popd; popd; cp $workdir/config.h bazel-out/local_linux-fastbuild/genfiles/external/png_archive/libpng-1.2.53; rm -rf $workdir;').
/home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow/external/png_archive/libpng-1.2.53 /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow
/tmp/tmp.k02Q7lIQJp /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow/external/png_archive/libpng-1.2.53 /home/informatica/.cache/bazel/_bazel_informatica/91a9bba81c77fb078ff5ab9ac13df451/tensorflow
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking how to run the C preprocessor... gcc -E
checking for sed... /bin/sed
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for ANSI C header files... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working strtod... yes
checking for memset... yes
checking for pow... no
checking for pow in -lm... yes
checking for zlibVersion in -lz... no
configure: error: zlib not installed
INFO: Elapsed time: 47.026s, Critical Path: 14.45s
`

I hope it's useful

**Comment by dgolden1** [comment] 2016-03-11 00:35
Try installing zlib.

```
sudo apt-get install zlib1g-dev -y
```

**Comment by liumilan** [comment] 2016-05-05 16:15
I have also the same issue,
can't be found in zlib
But I have install zlib in my machine
[@sjs_88_31 tensorflow]# sudo yum install zlib1g-dev -y
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: mirrors.neusoft.edu.cn
No package zlib1g-dev available.
Error: Nothing to do
[@sjs_88_31 tensorflow]# yum install zlib
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: mirrors.neusoft.edu.cn
Package zlib-1.2.7-13.el7.x86_64 already installed and latest version
Nothing to do

**Comment by girving** [comment] 2016-06-06 21:29
Closing since it looks like the problem is not having installed zlib.

**Closed by girving** 2016-06-06 21:29 UTC
