### ISSUE TITLE
InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match:

### ISSUE THREAD

**Issue by Lihengwannafly** [tensorflow/tensorflow#26967] opened 2019-03-21 03:23 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When I am trianging my model with tf.estimator and tf.data, this issue occurs:
`InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [128,64] vs. shape[1] = [127,16]`
the batch of data is 128, so the first feature' s is correct, the second wrong. 
Does anyone else have the same problem? Thanks in advance.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-03-21 21:22
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-03-25 17:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-25 17:24 UTC
Labels: comp:apis, stat:awaiting response, type:support
