### ISSUE TITLE
RHEL pip install 2.0-rc issues, No module named tensorflow_core.keras

### ISSUE THREAD

**Issue by fjallraven** [tensorflow/tensorflow#32768] opened 2019-09-24 08:20 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0-rc2, 2.0-rc1
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Running pip installs the package without issues but fails to import keras when using.
I have tried both gpu and cpu packages with same result.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
python3 -m pip install tensorflow-gpu==2.0.0-rc2
from tensorflow import keras
inputs = keras.Input(shape=(784,))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyinstalls/python3.6/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/pyinstalls/python3.6/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/pyinstalls/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named tensorflow_core.keras

import tensorflow.python.keras
ModuleNotFoundError: No module named tensorflow_core.python
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2019-09-24 20:18
By any chance, do you have `keras_applications` and `keras_preprocessing` installed?

I cannot reproduce but knowing the relevant import area these two seem like might be related.

**Comment by fjallraven** [comment] 2019-09-25 13:42
I do have those packages yes:
```
Python 3.6.5 (default, Jan 12 2018, 18:10:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'
>>> import keras_applications
>>> keras_applications.__version__
'1.0.8'
>>> import keras_preprocessing
>>> keras_preprocessing.__version__
'1.1.0'
```

**Comment by mihaimaruseac** [comment] 2019-09-25 20:33
It's strange that not even `tf.__version__` works for you.

Can you create a fresh environment and install tensorflow in it? Please attach all logs.

`(mkdir new; virtualenv new -ppython3.6; cd new; source bin/activate; pip install tensorflow; python -c "import tensorflow as tf; print(tf.__version__)") > logs`

**Comment by fjallraven** [comment] 2019-09-30 12:53
I was missing CUDA/cudnn on my PATH, adding those then rerunning pip install fixed the issue.

**Comment by gadagashwini** [comment] 2019-10-01 08:14
@fjallraven,
Glad its fixed. Are you happy to close this issue. Thanks!

**Closed** 2019-10-02 11:06 UTC
Labels: TF 2.0-rc0, stat:awaiting response, subtype:centos, type:build/install
