### ISSUE TITLE
sparsemax implementation is not infinite-safe

### ISSUE THREAD

**Issue by gcampax** [tensorflow/tensorflow#15564] opened 2017-12-21 21:31 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, but I have a simple reproducer below

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 27
- **TensorFlow installed from (source or binary)**: pip3 install --user tensorflow
- **TensorFlow version (use command below)**:  1.4.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no (x86_64 CPU)
- **Exact command to reproduce**:

### Describe the problem
tf.contrib.sparsemax.sparsemax does not produce the correctly expected results when infinities are present in the input.

Mathematically, a negative infinity should be treated the same as a very large negative number, and produce a 0 in the output.

This is a real-world problem when sparsemax is combined with contrib.seq2seq.LuongAttention (as suggested in its documentation, and also as suggested in the sparsemax paper), because entries past the input length in the batch will have a score of -inf by default.

### Source code / logs

Reproducer (assume tensorflow as tf)
```
>>> tf.contrib.sparsemax.sparsemax([[1., -1e+5]]).eval(session=sess)
array([[ 1.,  0.]], dtype=float32)
>>> tf.contrib.sparsemax.sparsemax([[1., float('-inf')]]).eval(session=sess)
2017-12-21 22:13:55.697302: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
2017-12-21 22:13:55.697997: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
2017-12-21 22:13:55.699634: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
2017-12-21 22:13:55.699980: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
	 [[Node: sparsemax_7/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sparsemax_7/sub, sparsemax_7/stack)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 570, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4455, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
	 [[Node: sparsemax_7/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sparsemax_7/sub, sparsemax_7/stack)]]

Caused by op 'sparsemax_7/GatherNd', defined at:
  File "<stdin>", line 1, in <module>
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/contrib/sparsemax/python/ops/sparsemax.py", line 69, in sparsemax
    tau_sum = array_ops.gather_nd(z_cumsum, indices)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1971, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/redacted/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[0, :] = [0, -1] does not index into param (shape: [1,2]).
	 [[Node: sparsemax_7/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sparsemax_7/sub, sparsemax_7/stack)]]
```

**Comment by michaelisard** [comment] 2017-12-22 01:18
@AndreasMadsen am I right that you contributed this? Any thoughts?

**Comment by facaiy** [comment] 2017-12-22 03:26
According to the [paper](https://arxiv.org/pdf/1602.02068.pdf):
<img width="439" alt="image" src="https://user-images.githubusercontent.com/1112263/34284021-fc2b3a64-e709-11e7-9469-984e7c632a29.png">

I agree that `-inf` should return 0 in common, however we need take care of all elements are `-inf`. In that case, both `-inf + 1 > -inf` and `-inf / -inf` are undefined if I understand it correctly.

**Comment by AndreasMadsen** [comment] 2017-12-22 07:45
@michaelisard you are correct.

I would say if all values are `-inf` they should be assigned an equal probability.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:07
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by gcampax** [comment] 2018-01-05 20:17
Yes, this is still an issue (not sure what "awaiting response" is for, is it like needinfo in bugzilla? if so, not sure what response you expect...)
Additionally, I observed that large positive or negative numbers also gives invalid results, because adding 1 has no effect.
In turn, this results in a sparsemax value outside of [0, 1], which breaks the math of the attention function later on.

**Comment by tensorflowbutler** [comment] 2018-01-23 22:56
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment] 2018-01-31 02:17
So @AndreasMadsen what do you think of @facaiy comment? That it's undefined? If so, then we can either 1) not promise any value, so it's not a bug, or 2) define an expected behavior. In the latter case, then we either set to the value that @gcampax suggested, or leave it as is, but specify it in the documentation.

**Comment by AndreasMadsen** [comment] 2018-01-31 08:42
@drpngx I think the behavior should be the same as with softmax. Although, I don't remember what that is.

Softmax and Sparsemax share many properties and the use case it the same.

**Comment by drpngx** [comment] 2018-01-31 18:33
Right. Can you send a PR?

**Comment by drpngx** [comment] 2018-01-31 18:34
Also, it's always a good idea to check what numpy does. We don't have to be compatible but we should clearly indicate when we are

**Comment by AndreasMadsen** [comment] 2018-02-09 13:29
Right now I'm a bit busy, but I should be able to work on this from Febuary 19th as I will be moved to our Open Source Data Science Team.

**Comment by clarken92** [comment] 2018-06-19 05:15
Dear guys,

My name is Kien. Would you mind telling me whether the infinite-safe problem with sparsemax has been resolved or not? I am using TF 1.3 and still encounter this problem. Thank you.

**Comment by AndreasMadsen** [comment] 2018-06-19 08:35
@clarken92 It hasn't been solved, as far as I know. I would really like to solve this, but I'm having a hard time allocating the time and I'm on vacation right now.

**Comment by clarken92** [comment] 2018-06-19 14:36
@AndreasMadsen Thank you for replying. I have checked the code from tensorflow, it not difficult to understand. I think based on the detailed algorithm from the paper, I could fix this and will report within 1 or 2 days.
I have to say that I really love this paper. Moving from softmax to sparsemax change a lot of concepts: soft => hard, nonlinear => linear. I hope that in the future, it can be combined with relational deep learning and stochastic discrete model like REBAR and RELAX to enable reasoning over discrete structures.

**Comment by clarken92** [comment] 2018-06-20 12:46
Hi guys,

I think I have solved the problem of sparsemax. The main problem is that the code for normalizing the logits in sparsemax() function substracts the **mean** instead of **max**. mean is very sensitive to noise (very positive or very negative numbers) since it includes all elements. For example, if we have 3 elements, one of them is -1e30 while the others 2 are 0.1 and 0.2, subtracting the mean will result in all three values around 1e29, causing a precision problem and other problem like division of a very large number by a very large number. Therefore, I replaced 
`z = logits - math_ops.reduce_mean(logits, axis=1)[:, array_ops.newaxis]`
with 
`z = logits - tf.reduce_max(logits, axis=1, keep_dims=True)` 
and the code works well. This is similar to the trick for robust computation in softmax.

Another problem I discovered is that the maximum range that we can detect small change is about [-1e6, 1e6]. So if you have 2 values like 1e7 and 1e7 + 0.5, they will be treated equally. I show this phenomenon in my unit test. To prevent this, it added in the code of sparsemax() a control_dependency that checks whether there is at least one value within this range or not. If not, we should not compute sparsemax since it will cause a precision error later.

I attatch here my code and my unit tests. Could you please check whether it is OK or not. Thank you.
[my_sparsemax.zip](https://github.com/tensorflow/tensorflow/files/2119313/my_sparsemax.zip)

**Comment by clarken92** [comment] 2018-06-20 12:51
One more thing I forget to say, I also add the option for computing sparsemax in case of 2 classes where only one logit value is available. This behavior is similar to sigmoid function. In this case, I assume that the logit for class 0 is 0 and the logit for class 1 is the logit itself.

**Comment by AndreasMadsen** [comment] 2018-07-26 14:00
@clarken92 I don't get how `max` makes things better. Yes, you avoid the issue of `mean` becoming `-inf`. But you still have an issue with `inf` and `nan`.

Regarding, the stability of `mean` I don't think your solution fixes that much as it will still cause issues if a value is `1e30`. When comparing with `softmax` you should be aware that the numerical stability comes from very different places. In `sparsemax` the numerical instability comes from the `cumsum` in `softmax` it comes from `exp`. Hence the solution to prevent this should be different.

In the end, I don't see how this addresses the issue of `inf` and `nan`. To me, your solution just addresses possible issues regarding numerical stability.

--- 

I finally got time to make a fix for this, for now it is here: https://github.com/AndreasMadsen/tensorflow/commit/7e25025409e7921f2e7816dbc8ba7fe3a532428b. I will open a PR as soon as I have tested it properly.

**Comment by AndreasMadsen** [comment] 2018-07-27 09:09
PR with a nan an inf safety fix: https://github.com/tensorflow/tensorflow/pull/21183

**Closed** 2018-10-05 23:17 UTC
Labels: stat:contributions welcome
