### ISSUE TITLE
Load image tutorials 

### ISSUE THREAD

**Issue by fardindadashi** [tensorflow/tensorflow#30163] opened 2019-06-26 06:25 UTC
You didn't use keras_ds or feature_map_batch in model.fit

**Comment by gadagashwini** [comment] 2019-06-27 07:47
@fardindadashi Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the reproducible code snippet. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by fardindadashi** [comment] 2019-06-27 08:05
I'm just saying the tutorials in https://www.tensorflow.org/tutorials/load_data/images the  keras_ds or feature_map_batch have not been used in model.fit function. Is that OK?

**Comment by gadagashwini** [comment] 2019-06-28 08:41
@fardindadashi In the mentioned tutorial, the model.fit uses the dataset of image_paths and image_labels that is ds. Thanks!

**Comment by gadagashwini** [comment] 2019-07-04 06:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-04 06:27 UTC
Labels: comp:data, comp:keras, stat:awaiting response, type:support
