### ISSUE TITLE
EarlyStopping with baseline doesn't set weights

### ISSUE THREAD

**Issue by danipozo** [tensorflow/tensorflow#45187] opened 2020-11-25 16:55 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Manjaro latest
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.6

**Describe the current behavior**

When passing an `EarlyStopping` callback to `model.fit()` with `baseline` parameter set and `restore_best_weights=True`, if the monitored quantity doesn't reach the baseline, best weights are never set and an exception is thrown when trying to restore them.

**Describe the expected behavior**

Something a bit more sensible like not trying to restore best weights if those are `None`, or throwing an exception that explicitly indicates the problem.

**Standalone code to reproduce the issue**
```python
from tensorflow.keras.optimizers import SGD
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Dense, Softmax

from tensorflow.keras.callbacks import EarlyStopping

x_train = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])
y_train = np.array([0, 1, 1, 0])

x_val = np.array([[0, 0], [0, 1]])
y_val = np.array([1, 0])

model = keras.Sequential([
    Dense(20),
    Dense(1),
    Softmax()
])

model.compile(optimizer=SGD(), loss='mse')
model.fit(x_train, y_train,
          validation_data=(x_val, y_val),
          epochs=5,
          callbacks=[
              EarlyStopping(monitor='val_loss',
                            baseline=0.5,
                            patience=3,
                            restore_best_weights=True)
          ])
```

**Other info / logs**
Traceback:
``` File "early_stopping.py", line 24, in <module>
    model.fit(x_train, y_train,
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1677, in on_epoch_end
    self.model.set_weights(self.best_weights)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1805, in set_weights
    if expected_num_weights != len(weights):
TypeError: object of type 'NoneType' has no len()
```

**Comment by ravikyram** [comment] 2020-11-26 06:01
I have tried in colan with TF version 2.2, 2.3, nightly version(`2.5.0-dev20201125`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ab13806714eba31316a64845fac90669/untitled539.ipynb). Thanks!

**Comment by fchollet** [comment] 2020-12-03 18:12
Thanks for the report, looks like a bug.

**Comment by jvishnuvardhan** [comment] 2021-04-08 20:48
@danipozo Looks like this was resolve in recent `tf-nightly`. I couldn't reproduce the error with `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/4fca1ef51b17c570d8d34da0d5faae44/untitled539.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by danipozo** [comment] 2021-04-14 19:09
I can see that this has been fixed, I guess in these [two](https://github.com/tensorflow/tensorflow/commit/c5f8604fedb0f82c6966a1d692b76eb5d7ce6d0e) [commits](https://github.com/tensorflow/tensorflow/commit/abcabe12666d064da4710d965c36a59c937eab12).

However, I wonder if this a good design, since as far as I can tell, the `baseline` argument is ignored with respect to deciding which weights to return if `restore_best_weights=True` is passed. This way, weights that underperform the specified baseline  can be returned without warning.

Although the docs don't specify that the returned weights should outperform the baseline, I see this as confusing and think a warning could help, specially given that past behavior tried to enforce this by not restoring weights when they didn't meet the baseline.

**Closed** 2021-04-28 20:35 UTC
Labels: TF 2.3, comp:keras, stalled, stat:awaiting response, type:bug
