### ISSUE TITLE
Windows 10: Failed to load native runtime.

### ISSUE THREAD

**Issue by MohammadDabbas** [tensorflow/tensorflow#23751] opened 2018-11-14 21:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution Windows 10 64 bit
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 1.12.0
- Python version:3.6.5
- GPU model and memory: Geforce 150mx 4gb

**Describe the problem**
I'm unable to import keras using _"Tensorflow backend"_
when I try to import _"from keras.models import Sequential"_  I get the error shown bellow

**These are the steps that I did when I installed the libraries**
1- conda create -n tensorflow python=3.5 anaconda.

2- activate tensorflow.

3- conda install theano.

4- conda install mingw libpython.

5-pip install tensorflow.

6- pip install keras.

7- conda update --all

8-  pip install tensorflow-gpu

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Error shown:

`from keras.models import Sequential
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-5-9c5e0a19b646>", line 1, in <module>
    from keras.models import Sequential

  File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *

  File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\MHD\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\MHD\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by ymodak** [comment] 2018-11-14 23:32
Duplicate of #23755

**Closed by ymodak** 2018-11-14 23:32 UTC
