### ISSUE TITLE
libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program

### ISSUE THREAD

**Issue by forhonourlx** [tensorflow/tensorflow#4267] opened 2016-09-08 04:56 UTC
i am trying to install tensorflow on my laptop LenovoY700, so that Ubuntu16.04 is more suitable with laptop.
I installed cuda7.5+cudnn4 with GTX960M and nvidia-version is 367.

When I was running 'convolutional.py', something goes wrong.

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/cuda-7.5/lib64:
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: Y700
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.44  Wed Aug 17 22:24:07 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.44.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1077] LD_LIBRARY_PATH: /usr/local/cuda-7.5/lib64:
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1078] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

Could somebody give me a hand?
Thanks for your help.
Simon

**Comment by tatatodd** [comment] 2016-09-08 06:53
@forhonourlx please provide the following details:
```
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
```

In general it looks like libcuda.so couldn't be found on LD_LIBRARY_PATH, so that's the direction you want to investigate.  For more details, see this related issue:
https://github.com/tensorflow/tensorflow/issues/4078#issuecomment-243065693

**Comment by forhonourlx** [comment] 2016-09-08 23:51
Hi Todd,
Thank you for your help, I installed tensorflow from pip of this link:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

simon@Y700:~$ ls -l /usr/local/cuda/lib/libcud*
-rw-r--r-- 1 root root 189170 Sep  4 00:48 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Sep  4 00:48 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Sep  4 00:48 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Sep  4 00:48 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Sep  4 00:48 /usr/local/cuda/lib/libcudart_static.a

simon@Y700:~$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/cuda/lib64:
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: Y700
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.44  Wed Aug 17 22:24:07 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.44.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1077] LD_LIBRARY_PATH: /usr/local/cuda/lib64:
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1078] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0rc0

simon@Y700:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:

**Comment by aselle** [comment] 2016-09-09 18:10
simon@Y700:~$ ls -l /usr/local/cuda/lib/libcud*
so...
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib

**Comment by GodloveD** [comment] 2016-09-21 15:53
I encountered a similar problem when trying to use cuda in a [singularity](http://singularity.lbl.gov/) container.  It turns out that the cuda .run installer did not set up a few symbolic links in the appropriate directories.  Easy fix. 
```
$ export NVID_VER=367.44 # or whatever version you have
$ cd /path/to/libcuda.so.$NVID_VER
$ ln -s libcuda.so.$NVID_VER libcuda.so
$ ln -s libcuda.so.$NVID_VER libcuda.so.1
```

**Comment by aselle** [comment] 2016-09-21 20:00
Automatically closing due to lack of recent activity by submitter. If the suggestions do not solve the problem, please provide information when available, and we can reopen.

**Closed by aselle** 2016-09-21 20:00 UTC
Labels: awaiting response

**Comment by linkoffate** [comment] 2016-09-23 17:44
I'm also having this problem, and its actually very strange.
Same as @forhonourlx, once I tried importing tensorflow, it said it can't open CUDA library libcuda.so and libcuda.so.1.

So I found the libraries within the machine as the following.
Under /usr/lib, /usr/lib64, the symbolic links are set up like this:
```
libcuda.so -> libcuda.so.1
libcuda.so.1 -> libcuda.so.352.93
libcuda.so.352.93
```
which is pretty much the way it is expected to be.

It will be natural to export LD_LIBRARY_PATH with /usr/lib and /usr/lib64 added, but when I import tensorflow for testing, it still somehow isn't able to find it.

Can anyone give a hint in what's going wrong?
By the way, the machine is CentOS 6 (I hate it)

Here is the full error log with some censoring (not critical)
```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: $HOME/.local/lib:$HOME/.local2/lib:/usr/lib:/usr/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib:$HOME/.local/lib:/usr/local/cuda/lib64:/usr/local/cuda/lib:
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: (_______)
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.93  Tue Apr  5 18:18:24 PDT 2016
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.93.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1077] LD_LIBRARY_PATH: $HOME/.local/lib:$HOME/.local2/lib:/usr/lib:/usr/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib:$HOME/.local/lib:/usr/local/cuda/lib64:/usr/local/cuda/lib:
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1078] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot enable executable stack as shared object requires: Operation not permitted
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
```

**Comment by damvantai** [comment] 2016-10-25 13:07
i think you install package libcuda1-370 or libcuda1-xxx


![image](https://cloud.githubusercontent.com/assets/9005755/19687168/9e9a5a64-9aee-11e6-86d1-132d19de57a6.png)

**Comment by sunsided** [comment] 2016-12-07 15:33
For some reason an nvidia driver update on Ubuntu 16.10 uninstalled the virtual `libcuda-XXX` package for me. Fixed it by manually installing it, then the error went away.

**Comment by benwu232** [comment] 2016-12-09 10:31
@sunsided 
Thank you very much!
Got this problem when installing tensorflow on cuda8.0 in a Ubuntu16.04. After installing libcuda367, now, it can run on gpu.

**Comment by mesuvash** [comment] 2017-01-30 08:15
@sunsided : I am having the same problem with Ubuntu 16.10. Could you please tell me how you install it manually?

**Comment by botev** [comment] 2017-03-05 06:00
The issue is definitely not resolved. I'm encountering it now as well on CentOS with the latest r1.0 release of tensorflow. For reference, this can not be a CUDA issue because both Theano and Pytorch worked out of the box. 
One suspicion I have (which I'm not sure) is that Tensorflow is picking the default GCC (4.4) rather than the local one (4.9) which could be causeing the problem, but I can not confirm this.

**Comment by zhihongzeng** [comment] 2017-03-16 20:26
I has been struggling for this problem for a whole day with docker. 
Finally I found a decent solution which is to use nvidia-docker: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker.

**Comment by wangg12** [comment] 2017-05-24 16:30
@damvantai thanks. Your answer solved my problem.

**Comment by Natural-Desire** [comment] 2017-07-09 02:02
Hello, 
I have asme problem

 python -c "import tensorflow; print(tensorflow.__version__)"


I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcuda.1.dylib. LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: RamakriidassMBP
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got ""
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1092] LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1093] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.1.dylib; dlerror: dlopen(libcuda.1.dylib, 6): image not found
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.dylib locally
0.12.1

**Comment by bzamecnik** [comment] 2017-09-21 08:51
@damvantai Yeah, this helped! Thanks. I don't know why it wasn't installed along with package`cuda` or `nvidia-384`.

```
sudo apt install libcuda1-384
```

Just for completeness the file should be located at `/usr/lib/x86_64-linux-gnu/libcuda.so.1`.

**Comment by zhangwewenwen** [comment] 2018-07-27 13:39
Duplicate of #21186

**Comment by zhangwewenwen** [comment] 2018-07-27 13:40
@GodloveD I meet this also, and I can't find the file you referred to ,how can I solve this problem??

**Comment by GodloveD** [comment] 2018-07-27 14:09
Heya @zhangwewenwen.  Are you running into this problem in a Singularity container?  Did you run your container with the `--nv` option?  

`--nv` will find the appropriate nvidia libraries on the host system (including `libcudo.so*`) and bind mount them into your container at runtime.  This will give you access to the host system GPU.

This is very similar to how nvidia-docker works afaik.

**Comment by markroxor** [comment] 2018-08-23 13:56
On following `sudo apt install libcuda1-390`

```python3
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcuda1-390 : Depends: nvidia-compute-390 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Getting this beautiful error on Ubuntu 18.04, nvidia drivers - 390.77.

Suggestions?
