### ISSUE TITLE
Warning: TensorFlow library wasn't compiled to use SSE instructions

### ISSUE THREAD

**Issue by jhburkhard** [tensorflow/tensorflow#8853] opened 2017-03-30 22:28 UTC
Installed nightly build using 
>pip3 install tensorflow-1.1.0rc0-cp35-cp35m-win_amd64.whl 
on Windows 7 Professional x64.  Simple run gives warning that the libs were not compiled to use SSE, SSE2, SSE3, SSE4.1, SSE4.2 and AVX instructions even though available. 

c:\python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print( tf.__version__)
1.1.0-rc0
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2017-03-30 15:20:06.126686: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_
tions, but these are available on your machine and could speed up CPU computations.
<<lines ommitted>
>>> print(sess.run(hello))
b'Hello, TensorFlow!'

**Comment by Carmezim** [comment] 2017-03-31 06:35
Duplicate of #7778

**Comment by aselle** [comment] 2017-04-01 21:08
This is not a bug.

**Closed** 2017-04-01 21:08 UTC

**Comment by rajaramcomputers** [comment] 2017-08-09 08:59
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf

This will work fine without warning
