### ISSUE TITLE
Pass Input to tensorflow lite model in Android

### ISSUE THREAD

**Issue by ihd2911** [tensorflow/tensorflow#30749] opened 2019-07-16 11:04 UTC
I have created a neural network that take numerical data as input and saved it as tensorflow lite model using python. I am trying to pass input to the model in Android. Shape of ndarray is 1*3

Sample of the input in python is as follows

`np.array([[-0.276786765 ,8.41897583008  ,-0.0222015380859]])`

But i do not know to create the same input in java to pass it to model.

I tried using nd4j library. But still not able to write the proper code to create the input which is required by the model.

**Comment by ravikyram** [comment] 2019-07-17 10:49
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2019-07-24 06:22
Automatically closing due to lack of recent activity. Thanks!

**Closed by ravikyram** 2019-07-24 06:22 UTC
Labels: comp:lite, stat:awaiting response, type:support
