### ISSUE TITLE
`import tensorflow.contrib.layers` takes very long time

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#12401] opened 2017-08-18 19:16 UTC
I've used Cprofile to test my code, and I find that `import tensorflow.contrib.layers` takes very long time. Here is the quick screenshot of the result:

```
14495011 function calls (14451561 primitive calls) in 6.324 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1023/1    0.058    0.000    6.328    6.328 {built-in method builtins.exec}
        1    0.000    0.000    6.328    6.328 test_import.py:10(<module>)
   1066/1    0.006    0.000    6.328    6.328 <frozen importlib._bootstrap>:966(_find_and_load)
   1066/1    0.005    0.000    6.328    6.328 <frozen importlib._bootstrap>:939(_find_and_load_unlocked)
   1360/1    0.001    0.000    6.328    6.328 <frozen importlib._bootstrap>:214(_call_with_frames_removed)
    759/1    0.002    0.000    6.328    6.328 {built-in method builtins.__import__}
    881/2    0.004    0.000    6.328    3.164 <frozen importlib._bootstrap>:659(_load_unlocked)
    833/2    0.003    0.000    6.328    3.164 <frozen importlib._bootstrap_external>:667(exec_module)
 6575/625    0.005    0.000    6.102    0.010 <frozen importlib._bootstrap>:996(_handle_fromlist)
... 
```
As seen above, it took more than 6 secs to just do `import tensorflow.contrib.layers`, and I wonder if this is expected. Also, I am pretty interested in why it takes so long time to do importing there.

**P.S** The profiling test runs on MacOS Sierra 10.12.5 with Tensorflow v1.2 and Python 3.5.

**Comment by reedwm** [comment] 2017-08-18 19:28
@jart, any plans to improve this?

**Comment by JettJones** [comment] 2017-09-21 16:51
This looks like a duplicate of #11829 - which was patched on September 18th. 🎉

**Closed** 2017-09-26 14:17 UTC
Labels: stat:awaiting tensorflower
