### ISSUE TITLE
Receiving InvalidArgument error when feeding inputs of uneven length

### ISSUE THREAD

**Issue by drunkinlove** [tensorflow/tensorflow#28903] opened 2019-05-21 15:50 UTC
**System information**
- I have written custom, albeit straightforward code using keras.Sequential.
- Platform: Google Colab, CPU runtime, Python 3
- TensorFlow installed using _pip install -q tensorflow==2.0.0-alpha0_

**Current behavior**
InvalidArgument error occurs.

**Expected behavior**
I should be able to train the network using inputs of uneven length.

**Code to reproduce the issue**
```
!pip install tensorflow==2.0.0-alpha0 

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
import numpy as np
import pickle

model = keras.Sequential([
    layers.Embedding(input_dim=48191, output_dim=300),
    layers.LSTM(300),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy', 
    optimizer=Adam(), 
    metrics=['accuracy']
    )

dataset = pickle.load(open("dataset.pkl", "rb"))
data_generator = ((np.asarray([x]), np.asarray([y])) for x, y in dataset)
model.fit_generator(data_generator, steps_per_epoch=len(dataset))
```
**Error message**
```
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Tried to stack elements of an empty list with non-fully-defined element_shape: [?,300]
	 [[{{node unified_lstm_2/TensorArrayV2Stack/TensorListStack}}]] [Op:__inference_keras_scratch_graph_6215]
```

[The dataset is required to reproduce the issue.](https://github.com/tensorflow/tensorflow/files/3203395/dataset.zip)

**Comment by gadagashwini** [comment] 2019-05-22 05:26
I could reproduce the issue reported here.

**Comment by jvishnuvardhan** [comment] 2019-06-13 00:44
@drunkinlove The `dataset` has an empty list at index=63. 
Index=63, dataset=([], 1.0)
index=62 , dataset=([16564,
  12869,
  48036,
  23694,
  41333,
  18458,
  9110,
  41136,
  15388,
  44860,
  18979,
  8556,
  16411,
  10861,
  13137,
  46889,
  19663,
  8556,
  46100,
  25021,
  16411,
  7388,
  12736,
  6535,
  7394,
  19571,
  3623,
  20091,
  44915,
  24392,
  9080,
  41136,
  6535,
  44136,
  23273,
  32950],
 1.0). 

Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-20 01:31
I think it was resolved. Closing due to lack of recent activity. Please open new ticket if you see similar issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-20 01:31 UTC
Labels: 2.0.0-alpha0, comp:keras, type:bug/performance
