### ISSUE TITLE
Failed to use vectorizing mapping for tf.data

### ISSUE THREAD

**Issue by hgffly** [tensorflow/tensorflow#38559] opened 2020-04-15 04:29 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  ubuntu18.04
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  pip, tf2.1.0
- CUDA/cuDNN version: - GPU model and memory: cuda10.1, cudnn7.6.5

**Describe the current behavior**
Failed to apply vectorizing mapping for tf.data

**Describe the expected behavior**
Apply vectorizing mapping for tf.data and speed up as described in https://www.tensorflow.org/guide/data_performance#vectorizing_mapping

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

    import tensorflow as tf

    data = tf.data.TFRecordDataset(['images.tfrecord'])

    image_feature_description = {
        'height': tf.io.FixedLenFeature([], tf.int64),
        'width': tf.io.FixedLenFeature([], tf.int64),
        'depth': tf.io.FixedLenFeature([], tf.int64),
        'bboxes': tf.io.VarLenFeature(tf.int64),
        'image_raw': tf.io.FixedLenFeature([], tf.string),
    }

    def parse_example(example):
        data = tf.io.parse_single_example(example, image_feature_description)
        
        img = tf.io.decode_jpeg(data['image_raw'])
        
        img = tf.image.resize(img, (416, 416))

        bboxes = data['bboxes']
        bboxes = tf.sparse.to_dense(bboxes)
        bboxes = tf.reshape(bboxes, [-1, 5])

        return img, bboxes

    #data = data.map(parse_example).batch(1)  # this works
    data = data.batch(1).map(parse_example)  # I tried to apply vectorizing mapping but errors raised

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

    Traceback (most recent call last):
    File "test_tfrecord.py", line 28, in <module>
        data = data.batch(1).map(parse_example)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1588, in map
        return MapDataset(self, map_func, preserve_cardinality=True)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3888, in __init__
        use_legacy_function=use_legacy_function)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3147, in __init__
        self._function = wrapper_fn._get_concrete_function_internal()
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2395, in _get_concrete_function_internal
        *args, **kwargs)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
        graph_function, _, _ = self._maybe_define_function(args, kwargs)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
        capture_by_value=self._capture_by_value),
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3140, in wrapper_fn
        ret = _wrapper_helper(*args)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
        ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
    File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    ValueError: in converted code:

        test_tfrecord.py:14 parse_example  *
            data = tf.io.parse_single_example(example, image_feature_description)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/parsing_ops.py:472 parse_single_example_v2_unoptimized
            serialized = _assert_scalar(serialized, "serialized")
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/parsing_ops.py:1319 _assert_scalar
            raise ValueError("Input %s must be a scalar" % name)

        ValueError: Input serialized must be a scalar

How should I fix it, thanks

**Comment by Saduf2019** [comment] 2020-04-15 05:40
i am able to replicate this, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/30416fd71b2065ef43b6069de4223370/38559.ipynb)

**Comment by ngc92** [comment] 2020-04-15 08:29
you are using `parse_single_example`, but passing in a batch of examples. This does not seem to be a bug but the intended behaviour of the function.

From the documentation:
```
One might see performance advantages by batching Example protos with parse_example instead of using this function directly.
```
https://www.tensorflow.org/api_docs/python/tf/io/parse_example

**Comment by hgffly** [comment] 2020-04-16 06:47
I have replaced parse_single_example with parse_example, but it raised another error

    import tensorflow as tf

    data = tf.data.TFRecordDataset(['images.tfrecord'])

    image_feature_description = {
        'height': tf.io.FixedLenFeature([], tf.int64),
        'width': tf.io.FixedLenFeature([], tf.int64),
        'depth': tf.io.FixedLenFeature([], tf.int64),
        'bboxes': tf.io.VarLenFeature(tf.int64),
        'image_raw': tf.io.FixedLenFeature([], tf.string),
    }

    def parse_example(example):
        data = tf.io.parse_example(example, image_feature_description)

        img = tf.io.decode_jpeg(data['image_raw'])
        
        img = tf.image.resize(img, (416, 416))

        bboxes = data['bboxes']
        bboxes = tf.sparse.to_dense(bboxes)
        bboxes = tf.reshape(bboxes, [-1, 5])

        return img, bboxes

    data = data.batch(1).map(parse_example)

errors:

    Traceback (most recent call last):
      File "test_tfrecord.py", line 28, in <module>
        data = data.batch(1).map(parse_example)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1588, in map
        return MapDataset(self, map_func, preserve_cardinality=True)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3888, in __init__
        use_legacy_function=use_legacy_function)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3147, in __init__
        self._function = wrapper_fn._get_concrete_function_internal()
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2395, in _get_concrete_function_internal
        *args, **kwargs)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
        graph_function, _, _ = self._maybe_define_function(args, kwargs)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
        capture_by_value=self._capture_by_value),
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3140, in wrapper_fn
        ret = _wrapper_helper(*args)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
        ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
      File "/home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    ValueError: in converted code:

        test_tfrecord.py:16 parse_example  *
            img = tf.io.decode_jpeg(data['image_raw'])
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_image_ops.py:1092 decode_jpeg
            dct_method=dct_method, name=name)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py:742 _apply_op_helper
            attrs=attr_protos, op_def=op_def)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:595 _create_op_internal
            compute_device)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:3322 _create_op_internal
            op_def=op_def)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1786 __init__
            control_input_ops)
        /home/wilson/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1622 _create_c_op
            raise ValueError(str(e))

        ValueError: Shape must be rank 0 but is rank 1 for 'DecodeJpeg' (op: 'DecodeJpeg') with input shapes: [?].


How should I fix it, thanks

**Comment by gowthamkpr** [comment] 2020-06-03 20:15
@hgffly Are you still facing the issue?

**Comment by hgffly** [comment] 2020-06-04 04:46
> @hgffly Are you still facing the issue?

No, I have switched to PyTorch, thanks

**Comment by gowthamkpr** [comment] 2020-06-08 08:57
@hgffly I am sorry to hear this. But the issue here is that you have to convert `data['image_raw']` from  rank 1 to rank 0 i.e., scalar as `tf.io.decode_jpeg()` only expects scalar as input. So you can use this to reshape it into a scalar
`img = tf.io.decode_jpeg(tf.reshape(data['image_raw'],[]))` and everything should work as normal.

Anyways, I am closing this issue now. If you face anymore issues, please reopen it. Thanks!

**Closed by gowthamkpr** 2020-06-08 08:57 UTC
Labels: TF 2.1, comp:data, type:bug

**Comment by FalsoMoralista** [comment] 2021-06-20 16:15
https://stackoverflow.com/questions/61245158/failed-to-apply-vectorizing-mapping-for-tf-data-in-tensorflow-2-1-0
