### ISSUE TITLE
Invalid Output shape to Invalid input

### ISSUE THREAD

**Issue by soumyadeepabhaumik** [tensorflow/tensorflow#38075] opened 2020-03-31 15:23 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: No
- TensorFlow installed from (source or
binary): - TensorFlow 2.1 (source) 
- Python version: - 3.7
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When`kenerl_size=0` the size of image increases
**Describe the expected behavior**
Value error
**Standalone code to reproduce the issue** 
`import tensorflow as tf`
`inputs=tf.keras.layers.Input(shape=(32, 32, 3))`
`x=tf.keras.layers.Conv2D(64,kernel_size=0)(inputs)`
`x=tf.keras.layers.Flatten()(x)`
`outputs=tf.keras.layers.Dense(64)(x)`
`model=tf.keras.Model(inputs,outputs)`
`model.summary()`

Output:
![issue1](https://user-images.githubusercontent.com/62893143/78043941-98d88400-7391-11ea-99b0-37d10eb84e46.PNG)

**Comment by soumyadeepabhaumik** [comment] 2020-03-31 15:25
Please make the changes in 2.1 version ,being an instructor i am unable to show to people about tensorflow's tiny mistakes

**Comment by amahendrakar** [comment] 2020-04-01 07:49
@soumyadeepabhaumik,
I was able to reproduce the issue with [TF v2.2.0rc2](https://colab.research.google.com/gist/amahendrakar/0d207dfe652f6cb0b0b6291db2bbb7a1/38075-2-2.ipynb). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/67bfd7bb5ebe4eb7513650dfa4847bd0/38075.ipynb) i.e. TF v2.2.0-dev20200331. Please find the attached gist. Thanks!

**Comment by amahendrakar** [comment] 2020-04-08 15:22
@soumyadeepabhaumik,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-16 17:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-16 17:22 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug
