### ISSUE TITLE
STOP UPDATING

### ISSUE THREAD

**Issue by creatist** [tensorflow/tensorflow#39998] opened 2020-05-29 16:10 UTC
More updations, more pains!!!

**Comment by ravikyram** [comment] 2020-05-31 11:45
@creatist 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github [new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by ravikyram** [comment] 2020-06-08 06:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-08 06:18 UTC
Labels: stalled, stat:awaiting response, type:others
