### ISSUE TITLE
Checkpoints continue to grow after the first restore

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#16025] opened 2018-01-11 00:25 UTC
### System information
- No

- **OS Platform and Distribution**: Mac OS X, v 10.13.2
- **TensorFlow installed from**: binary
- **TensorFlow version**: v1.3.0-rc1-5211-gab0fcac 1.5.0-dev20171126
- **Python version**: Python 3.5.0
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: Intel Iris Pro 1536 MB
- **Exact command to reproduce**: N/A
- **Have I written custom code**: N/A

### Describe the problem

The parameter `max_to_keep` of the `Saver` class does not seem to have effect once a model and its training variables are restored. In other words, the first time I train my model, the saver is keeping only `max_to_keep` checkpoints. Then I interrupt the training. Later, when I resume it, the number of checkpoints keeps going without any apparent limit.

### Related issues

- https://github.com/tensorflow/tensorflow/issues/5929
- https://github.com/tensorflow/tensorflow/issues/6326

**Comment by tensorflowbutler** [comment] 2018-01-11 12:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by nbro** [comment] 2018-01-11 14:05
@tensorflowbutler Ok, I have added it.

**Comment by nbro** [comment] 2018-01-12 00:49
I've just noticed that the file `checkpoint`, which keeps track of the names of the last checkpoints, only contains the last `max_to_keep` filenames.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:01
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by reedwm** [comment] 2018-01-29 23:04
I can reproduce with

```python
import tensorflow as tf

gs = tf.Variable(0, name='global_step')
inc_gs = gs.assign_add(1)
saver = tf.train.Saver([gs], max_to_keep=2)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for _ in range(3):
    saver.save(sess, '/tmp/ckpts/model.ckpt', gs)
    sess.run(inc_gs)

saver = tf.train.Saver([gs], max_to_keep=2)
with tf.Session() as sess:
  saver.restore(sess, tf.train.latest_checkpoint('/tmp/ckpts'))
  for _ in range(3):
    saver.save(sess, '/tmp/ckpts/model.ckpt', gs)
    sess.run(inc_gs)
```

@panyx0718, do you know if this is intended?

**Comment by tensorflowbutler** [comment] 2018-02-13 14:24
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 08:02
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-18 16:02
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-10 12:33
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-25 19:02
Nagging Assignee @bignamehyp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 12:48
Nagging Assignee @bignamehyp: It has been 100 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:56
Nagging Assignee @bignamehyp: It has been 116 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:49
Nagging Assignee @bignamehyp: It has been 131 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment] 2018-06-20 06:57
Is it still an issue for the latest TF?

**Comment by tensorflowbutler** [comment] 2018-07-04 18:38
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-20 01:16
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by bignamehyp** [comment] 2018-08-02 17:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by bignamehyp** 2018-08-02 17:25 UTC
Labels: stat:awaiting response

**Comment by nbro** [comment] 2018-08-02 21:37
@bignamehyp 

> Please update the issue when new information becomes available, and we will reopen the issue

Update the issue? Why should I need to update the issue? TF developers have to solve this issue. There's nothing to update.
