### ISSUE TITLE
TF 2.0 strange issue with code upgraded from TF 1.x.

### ISSUE THREAD

**Issue by SetoKaiba** [tensorflow/tensorflow#27669] opened 2019-04-09 05:16 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0-alpha0
- Python version:3.6

**Describe the current behavior**
The session return an ndarray [[value_estimate]] instead of value_estimate.

**Describe the expected behavior**
The session should return a scalar float. Just value_estimate. It should not be in an ndarray.
Workaround: get the actual scalar float in the ndarray if it is not a float
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L199-L200
```python
if not isinstance(value_estimate, float):
            value_estimate = value_estimate[0][0]
```

**Code to reproduce the issue**
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L199-L200
The problem can be reproduced without the two lines workaround.

**Other info / logs**
The value_estimate is calculated by the session and model.value. Code is lines below.
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L198
```python
value_estimate = self.sess.run(self.model.value, feed_dict)
```
self.model.value is defined like this. The previous layer is dense layer with one units.
And the tf.identity should just return a scalar float.
The code is running correctly in TF 1.x. 
But it's working incorrectly in TF 2.0.
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/models.py#L298-L299
```python
        value = tf.layers.dense(hidden_value, 1, activation=None)
        self.value = tf.identity(value, name="value_estimate")
```

**Comment by achandraa** [comment] 2019-04-12 13:05
Seems like it is a duplicate of issue #27425 . Can you please confirm?

**Comment by SetoKaiba** [comment] 2019-04-12 13:14
@achandraa Yes. It' duplicated. I created this because I think maybe the official didn't aware of it. Because tons of issues everyday. I just created this and closed that #27425. But then I received that #27425 is assigned. So I reopen it. Just to keep one would be ok.

**Comment by tranhungnghiep** [comment] 2019-04-13 14:08
I looked at this, seems this is the intended behavior. `tf.layers.dense()` takes a tensor of shape `(batch, input_dim)` as input and return a tensor of shape `(batch, num_units)`. Here the output is a tensor, which is returned as a 2-d numpy array, not a scalar.

**Comment by SetoKaiba** [comment] 2019-04-13 14:20
@tranhungnghiep The num_units is 1. Shouldn't it be a scalar?
And also the problem doesn't occur in tf1. And also it doesn't occur in the early training as well. It occurs after about 8000 steps.

Here's the branch I migrated to tf2. I can only by adding L199-200 to make it work in tf2.
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L198

Here's the branch of original tf1.
https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/ppo/policy.py#L198

**Comment by tranhungnghiep** [comment] 2019-04-13 16:30
I tested on tf2.compat.v1 with disable_v2_behavior(). So it seems to be a bigger problem that was overlooked. Because the behavior of v1 was not replicated. 

I think the behavior changed due to it uses keras layers under the hood, and keras hides the batch size in the shape. Keras always makes some abstractions that are very confusing for expert users. 

I see this immediately, so maybe the delay in your case is not related.

**Comment by SetoKaiba** [comment] 2019-04-14 04:53
@tranhungnghiep Thank you for your reply. Do you need an Unity env to reproduce the bug?
I can upload one for you.

**Comment by SetoKaiba** [comment] 2019-04-14 05:14
Here's the Unity env for Win and Linux. I didn't test the Linux build. Because I'm using it on Win. Maybe it's not working.
https://www37.zippyshare.com/v/LPFvEKiZ/file.html
Check out the repo for tf2 branch. https://github.com/SetoKaiba/ml-agents
Remove the two lines workaround below.
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L199-L200
You can just use the lines below to reproduce the bug.
```
pip install -e ml-agents-envs
pip install -e ml-agents
```
For Windows, replace the env for your path
```
mlagents-learn config\trainer_config.yaml --env="E:\Seto\GitHub\Unity-Technologies\ml-agents\UnitySDK\Build\Win\Unity Environment" --train
```
For Linux, replace the env for your path
```
mlagents-learn config/trainer_config.yaml --env="3DBall" --train
```

**Comment by ebrevdo** [comment] 2019-07-12 18:17
`tf.layers` is deprecated in TF2 in favor of tf.keras.layers; specifically here you'd use `tf.keras.layers.Dense`.  There is no `tf.layers` in TF2.

If you pass a scalar to `tf.keras.layers.Dense(1)` you'll get the explicit error:

```python
z = tf.keras.layers.Dense(1)(1)    
>>> ValueError: Input 0 of layer dense_3 is incompatible with the layer: : expected min_ndim=2, found ndim=0. Full shape received: []
```

Keras Dense layers accept at least matrices and emit at least matrices, so the behavior is consistent in TF1 and TF2.

In your case, if you passed a 1x1 matrix to Dense(1) you'd get a 1x1 matrix back:

```python
tf.keras.layers.Dense(1)(tf.constant([[1.0]]))
>>> <tf.Tensor 'dense_8/BiasAdd:0' shape=(1, 1) dtype=float32>
```

**Closed by ebrevdo** 2019-07-12 18:17 UTC
Labels: 2.0.0-alpha0, comp:ops, stat:awaiting tensorflower, type:support
