### ISSUE TITLE
Map-function Jacobian gives error

### ISSUE THREAD

**Issue by jjough** [tensorflow/tensorflow#10514] opened 2017-06-08 00:52 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OS X 10.11.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.1.0-rc0-61-g1ec6ed5 1.1.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CPU
- **GPU model and memory**: CPU

### Describe the problem
Calculating the Jacobian with a map function gives an InvalidArgumentError.

### Source code / logs
```python
import tensorflow as tf

a = tf.constant([5., 3., 2.])
b = tf.square(a)

fn = lambda x: tf.gradients(x, a)[0]
out = tf.map_fn(fn, b)

with tf.Session() as sess:
    out_eval = sess.run(out)
    print(out_eval)
```
`InvalidArgumentError (see above for traceback): TensorArray map/TensorArray_1@map/while/gradients: Could not read index 0 twice because it was cleared after a previous read (perhaps try setting clear_after_read = false?).`

**Comment by michaelisard** [comment] 2017-06-08 17:06
Closing as duplicate of #10476, see discussion in #675.

**Closed by michaelisard** 2017-06-08 17:06 UTC
