### ISSUE TITLE
fft wrong results with non-power of 2 input sizes

### ISSUE THREAD

**Issue by BinhBob** [tensorflow/tensorflow#17825] opened 2018-03-19 14:21 UTC
I have encounter problems with the tensorflow fft implementation when the input is not a power of two. If the input is real, the first entry of the output is the sum of the input and should therefore also be real. 
But tf.fft output a non-zero imaginary part. An example is given below:

```
import tensorflow as tf
import numpy as np

data = np.random.random(100)
sess = tf.Session()
fft_tf = sess.run(tf.fft(data))
print(fft_tf[0])
np.sum(data.astype(np.float32))
```

works as intended for inputs as power of two's including smaller errors:

```
data = np.random.random(128)
sess = tf.Session()
fft_tf = sess.run(tf.fft(data))
print(fft_tf[0])
np.sum(data.astype(np.float32))
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Windows 10
- **TensorFlow installed from (source or binary)**:
    Installed from Source
- **TensorFlow version (use command below)**:
    Version 1.4
- **Python version**: 
    Python 3.6.2
- **Bazel version (if compiling from source)**:
    N/A
- **GCC/Compiler version (if compiling from source)**:
    N/A
- **CUDA/cuDNN version**:
    CUDA Version 8.0, cuDNN64_6
- **GPU model and memory**:
    nvidia GTX 1050 mobile
- **Exact command to reproduce**:
    See above.

**Comment by tensorflowbutler** [comment] 2018-03-20 01:40
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by BinhBob** [comment] 2018-03-20 08:52
Sorry, I updated my post above!

**Comment by rryan** [comment] 2018-04-01 18:01
Thanks @BinhBob and sorry for the trouble. This was a bug in Eigen and should be fixed in https://github.com/tensorflow/tensorflow/commit/67ff23036e093343a7ea02e17f36f2b02eaae740, which is included in TensorFlow 1.6.

**Comment by rryan** [comment] 2018-04-01 18:28
Running your example on TensorFlow 1.6:
```
data = np.random.random(128)
sess = tf.Session()
fft_tf = sess.run(tf.fft(data))
print(fft_tf[0])
np.sum(data.astype(np.float32))
> (59.306988+0j)
> 59.30699
```

**Comment by BinhBob** [comment] 2018-04-03 09:18
Sorry, I forgot to post my results for TF 1.6 but as you can see the imaginary part of the first entry is still non-zero in TF 1.6. In general the error using power of two inputs are smaller than non power of two's. If thats an issue in the cuFFT implementation one should mention it in the tf.fft() function description?

**Comment by tensorflowbutler** [comment] 2018-04-18 12:34
Nagging Assignee @rryan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-03 18:44
Nagging Assignee @rryan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:49
Nagging Assignee @rryan: It has been 53 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:56
Nagging Assignee @rryan: It has been 68 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rryan** [comment] 2018-06-11 17:41
I'm learning that a lot of RFFT implementations simply zero the imaginary component of the first frequency bin instead of computing them. 

For example, numpy.fft.rfft (FFTPack) does this:
https://github.com/numpy/numpy/blob/master/numpy/fft/fftpack_litemodule.c#L193-L200

Due to floating point error I think it's unlikely we'll reach true zero, so maybe we should follow suit.

**Comment by tensorflowbutler** [comment] 2018-06-26 12:43
Nagging Assignee @rryan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-11 12:49
Nagging Assignee @rryan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Closed** 2018-07-11 13:08 UTC
