### ISSUE TITLE
building tensorflow r1.4  RelWithDebInfo on Window 10 Fails

### ISSUE THREAD

**Issue by ben11355** [tensorflow/tensorflow#19354] opened 2018-05-17 13:50 UTC
Hi Guys,

I was able to build Tensorflow r1.4 in Release on Windows 10 with the following successfully.
Python 3.5
Cuda 8.0, Cudnn 6.0
Visual Studio 2015

However, I clone the Tensorflow repository, checked out r1.4 and try to build RelWithDebInfo with the following commands:

cmake .. -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSWIG_EXECUTABLE="C:\\swigwin-3.0.12\\swig.exe" -DPYTHON_EXECUTABLE="C:\\Python35\\python.exe" -DPYTHON_LIBRARIES="C:\\Python35\\libs\\python35.lib" -DPYTHON_INCLUDE_DIR="C:\\Python35\\include" -DNUMPY_INCLUDE_DIR="C:\\Python35\\Lib\\site-packages\\numpy\\core\\include" -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\\cudnn_80_60"

MSBuild /p:Configuration=RelWithDebInfo tf_tutorials_example_trainer.vcxproj

Cmake was able to generate the visual studio files.

However, I ended up with the following compilation error:
"C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj" (default target) (1) ->
"C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default target) (114) ->
(ClCompile target) ->
  C:\tensorflow_1_4\tensorflow\tensorflow\core\kernels\training_ops.cc(3248): error C2471: cannot update program database 'C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\b
uild\tf_core_kernels.dir\RelWithDebInfo\tf_core_kernels.pdb' [C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]

Can I please get some help on this?  Thank you very much in advance!

**Comment by ben11355** [comment] 2018-05-21 21:06
Hi,
OS Platform and Distribution: Windows 10
TensorFlow installed from: N/A
TensorFlow version: 1.4
Bazel version: N/A (used cmake and VS2015)
CUDA/cuDNN version: Cuda 8, cuDNN 6.0
GPU model and memory: GPU model Titan Xp, memory 64GB

Exact Commands:
cmake .. -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSWIG_EXECUTABLE="C:\swigwin-3.0.12\swig.exe" -DPYTHON_EXECUTABLE="C:\Python35\python.exe" -DPYTHON_LIBRARIES="C:\Python35\libs\python35.lib" -DPYTHON_INCLUDE_DIR="C:\Python35\include" -DNUMPY_INCLUDE_DIR="C:\Python35\Lib\site-packages\numpy\core\include" -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\cudnn_80_60"

This was fine,  however, the build command failed:
MSBuild /p:Configuration=RelWithDebInfo tf_tutorials_example_trainer.vcxproj

Please see below for the error message:
"C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj" (default target) (1) ->
"C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default target) (114) ->
(ClCompile target) ->
C:\tensorflow_1_4\tensorflow\tensorflow\core\kernels\training_ops.cc(3248): error C2471: cannot update program database 'C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\b
uild\tf_core_kernels.dir\RelWithDebInfo\tf_core_kernels.pdb' [C:\tensorflow_1_4\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]


Thank you very much for your help!

**Comment by jrs-synth** [comment] 2018-05-23 11:19
I have the same issue with 1.7.1...

OS Platform and Distribution: Windows 10
TensorFlow installed from: N/A
TensorFlow version: 1.7.1
Bazel version: N/A (used cmake and VS2017)
CUDA/cuDNN version: Cuda 9, cuDNN 7.1.3
GPU model and memory: 1070 MaxQ

Commands...
cmake .. -A x64 -G "Visual Studio 15 2017" -T host=x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
-Dtensorflow_ENABLE_GPU=ON -Dtensorflow_BUILD_PYTHON_BINDINGS=ON -Dtensorflow_BUILD_SHARED_LIB=ON ^
-Dtensorflow_CUDA_VERSION=9.0 -Dtensorflow_CUDNN_VERSION=7 -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2 ^
-DCMAKE_INSTALL_PREFIX="D:\TensorFlow\tensorflow-1.7.1\tensorflow\contrib\cmake\build\install" ^
-DSWIG_EXECUTABLE="C:\Program Files\swigwin-3.0.12\swig.exe" ^
-DPYTHON_EXECUTABLE="C:\Python36\python.exe" ^
-DPYTHON_LIBRARIES="C:\Python36\libs\python36.lib" ^
-DPYTHON_INCLUDE_DIR="C:\Python36\include" ^
-DNUMPY_INCLUDE_DIR="C:\Python36\Lib\site-packages\numpy\core\include" ^
-DCUDA_HOST_COMPILER="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe"

MSBuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m:6 INSTALL.vcxproj /p:PreferredToolArchitecture=x64

The RelWithDebInfo build fails with the error:
“training_ops.cc(3508): error C2471: cannot update program database … tf_core_kernels.pdb”

(I tried adding CXXFLAGS=/FS but this didn't appear to solve the problem)

Release builds fine. Any help with debug support would be much appreciated!

**Comment by ben11355** [comment] 2018-05-25 19:34
This is broken for Tensorflow 1.5 as well.

Have I written custom code: No
OS Platform and Distribution: Windows 10
TensorFlow installed from: N/A
TensorFlow version: 1.5
Bazel version: N/A
CUDA/cuDNN version: CUDA 9.0, cuDNN 7.12
GPU model and memory:  GPU model Titan Xp, memory 64GB
Exact command to reproduce:

Cmake:
cmake .. -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSWIG_EXECUTABLE="C:\\swigwin-3.0.12\\swig.exe" -DPYTHON_EXECUTABLE="C:\\Python35\\python.exe" -DPYTHON_LIBRARIES="C:\\Python35\\libs\\python35.lib" -DPYTHON_INCLUDE_DIR="C:\\Python35\\include" -DNUMPY_INCLUDE_DIR="C:\\Python35\\Lib\\site-packages\\numpy\\core\\include" -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:\\cudnn_90_712"

Build:
MSBuild /p:Configuration=RelWithDebInfo tf_tutorials_example_trainer.vcxproj

Build fails with the following error:
"C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj" (default target) (1) ->
"C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\tf_stream_executor.vcxproj" (default target) (120) ->
  C:\tensorflow_1_5\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc(137): warning C4068: unknown pragma [C:\tensorflow_1_5\tensorflow\tensorflow\co
ntrib\cmake\build\tf_stream_executor.vcxproj]
  C:\tensorflow_1_5\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc(138): warning C4068: unknown pragma [C:\tensorflow_1_5\tensorflow\tensorflow\co
ntrib\cmake\build\tf_stream_executor.vcxproj]
  C:\tensorflow_1_5\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc(224): warning C4068: unknown pragma [C:\tensorflow_1_5\tensorflow\tensorflow\co
ntrib\cmake\build\tf_stream_executor.vcxproj]
  C:\tensorflow_1_5\tensorflow\tensorflow/stream_executor/lib/statusor.h(191): warning C4180: qualifier applied to function type has no meaning; ignored (com
piling source file C:\tensorflow_1_5\tensorflow\tensorflow\stream_executor\plugin_registry.cc) [C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\t
f_stream_executor.vcxproj]


"C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\tf_tutorials_example_trainer.vcxproj" (default target) (1) ->
"C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj" (default target) (118) ->
(ClCompile target) ->
  C:\tensorflow_1_5\tensorflow\tensorflow\core\kernels\training_ops.cc(3500): error C2471: cannot update program database 'C:\tensorflow_1_5\tensorflow\tenso
rflow\contrib\cmake\build\tf_core_kernels.dir\RelWithDebInfo\tf_core_kernels.pdb' [C:\tensorflow_1_5\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernel
s.vcxproj]

    20057 Warning(s)
    1 Error(s)


Thank you very much for your help!

**Comment by shivaniag** [comment] 2018-05-25 20:18
@gunan could you take a look into this.

**Comment by gunan** [comment] 2018-05-25 20:41
As far as I know, this has never worked.
@mrry @guschmue may be able to explain why.

**Comment by guschmue** [comment] 2018-05-30 16:33
RelWithDebInfo used to work fine, it was the most practical way for debugging.
Looks it doesn't work anymore because multiple builds of tf_core_kernels try to update the same pdb.
Something wrong with the dependencies I assume.
I can see if I can find some time to look at it.

**Comment by jrs-synth** [comment] 2018-06-14 18:14
Hi, gentle prompt... is there a work around that can be used in the build? Many thanks.

**Comment by tensorflowbutler** [comment] 2018-06-14 18:51
Nagging Assignees @gunan, @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-29 18:57
Nagging Assignees @gunan, @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kingofthebongo2008** [comment] 2018-07-06 21:18
if i set all cc files to produce different pdb the error does not happen. also if /mp option is disabled everything is fine, the build time is slower

**Comment by kingofthebongo2008** [comment] 2018-07-07 11:38
I have disabled the /MP flag which was a clue, got the error again. Seems to me that the pdb generated is just too big, because it is around 2GB
tf_core_kernels fails, did not check other libraries

**Comment by kingofthebongo2008** [comment] 2018-07-07 11:40
Seems to me that splitting the kernels library will be good solution, also looks to me that on windows we are in a desperate need for precompiled headers, building on 8 core machine takes too much time also.

**Comment by kingofthebongo2008** [comment] 2018-07-08 06:49
So i have split tf_core_kernels in two, the errors are gone. Other tools now fail like transform_graph. But the problem is obvious. Tensorflow in this shape is a monster. Need to be split in several dlls to reduce these issues. Will see more these days, but the transform graph pdb is 3gb on my machine

**Comment by kingofthebongo2008** [comment] 2018-07-08 06:50
actually i wanted to compile it and debug one simple inference example and now i got this two week effort to build a pdb :).

**Comment by kingofthebongo2008** [comment] 2018-07-08 17:21
so i have split tf_core_kernels  into 6 libraries, they compile fine, but after that tensorflow.pdb cannot be generated, because it gets above 3GB. So removing the pdb for now will work. I have discovered also that there is one script for version_info.cc, which is executed on every build and should be executed only once from a build machine. putting it in make,sh or something similar will be better.

**Comment by jrs-synth** [comment] 2018-07-14 18:33
@vincentlabonte sadly not for me,  I still get subsequent errors
e.g ...\range_coder.cc(375): error C2471: cannot update program database ....\tf_core_kernels.pdb

What build options did you use? thanks!

**Comment by vincentlabonte** [comment] 2018-07-19 20:16
@jrs-synth You are right my work around only works with -Dtensorflow_ENABLE_GPU=OFF...

**Comment by kingofthebongo2008** [comment] 2018-07-20 05:55
I am working in a branch to split some tensorflow in parts in dlls.

So far the kernels are registered in a GlobalRegistry which is a multimap.
This can go in a dll. If it goes there, then every kernel can be made as a
dll and will have own pdb and the problem will disappear.

For this to happen.

1. proto files must be in a different dll like tf_proto.dll
2. tf_kernel_registry.dll must be made
3. tf_core_kernels must be split.

**Comment by gunan** [comment] 2018-07-20 07:01
Actually we are also planning to do that.
Please see the design here:
https://github.com/tensorflow/community/pull/2

**Comment by kingofthebongo2008** [comment] 2018-07-20 12:05
This is quite, good. Hope will come soon, In the mean time i will fix it
locally.

**Comment by guschmue** [comment] 2018-07-20 16:29
I think splitting into multiple dlls is the only way to handle the large pdbs. 
One issue that might come with this is the symbol exports from the dll done by https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tools/create_def_file.py ... it is good enough to handle kernels in _lstm_ops.dll  but I'm not sure if it exports enough symbols to keep all kernels happy. In case additional symbols need to be exported, there is a 64k limit on the number of symbols and for gpu builds 59k are used today ... not much room to grow.
In case you need a workaround to just debug a specific issue: I used to have the issue with the pdb size during the port of the cuda to windows and could get around it by generating symbols selective in cmake for the modules I needed. Or alternatively you can delete the pdb's you don't care about and re-link with  /p:BuildProjectReferences=false ... total hack of course.

**Comment by tensorflowbutler** [comment] 2018-08-04 18:39
Nagging Assignees @gunan, @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pvn25** [comment] 2018-08-07 21:10
@kingofthebongo2008 I believe you mean in the tf_core_kernels project,  "Configuration Properties > Linker > Debugging> Generate Debug Info" set to No.  However, I do not see the Linker tab in the "tf_core_kernels" project. Am I missing something?

**Comment by tensorflowbutler** [comment] 2018-08-22 19:18
Nagging Assignees @gunan, @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-06 18:54
Nagging Assignees @gunan, @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-21 19:00
Nagging Assignees @gunan, @shivaniag: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-24 07:11
Sorry for not being able to resolve this.
CMake files we had were becoming too confusing to maintain.
They have been deprecated in favor of bazel on windows.
I am sorry to close this issue as obsolete.

**Closed by gunan** 2018-09-24 07:11 UTC
Labels: type:build/install
