### ISSUE TITLE
TypeError: save() got an unexpected keyword argument 'save_format'

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#37847] opened 2020-03-24 00:42 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): I followed a tutorial of Adrian Rosebrock ( Pyimagesearch )
- OS Platform and Distribution : Windows 10 x64
- TensorFlow installed from (
binary): - TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: - GPU model and memory:9/7

**Standalone code to reproduce the issue** 
I'm trying to train a dataset of COVID-19 virus to detect the normal person and the no normal person ( he have not the virus) .
when I execute the script `train_covid19.py` that I have got from ( https://www.pyimagesearch.com/2020/03/16/detecting-covid-19-in-x-ray-images-with-keras-tensorflow-and-deep-learning/?fbclid=IwAR2P7bkAaIf9F_I1dk2xyLRpQB2mfAtc3ov3fpsls8B-wNEeCVPT3cizCWY), I got an error after I have completed the 25 epochs of training.
>[INFO] saving COVID-19 detector model...
Traceback (most recent call last):
  File "train_covid19.py", line 164, in <module>
    model.save(args["model"], save_format="h5")
TypeError: save() got an unexpected keyword argument 'save_format'

I'm sure that the problem is a bug in the version of the tensorflow or some changes ( because Adrain is used Tensorflow 2.0 and the version that I used is 1.13.1)
So I need to know how can I change this line to make the complete code works?
Thanks :)

**Comment by gadagashwini** [comment] 2020-03-24 06:57
@abdou31, In the given link, Tensorflow version used is 2.0, Try to execute the `train_covid19.py` with Tf2.0.
Thanks

**Comment by abdou31** [comment] 2020-03-28 19:06
I know that the problem with the version, but I solved the problem by changing some lines using the version 1.13.1.

**Comment by gadagashwini** [comment] 2020-03-30 06:36
@abdou31, Can you provide the modified code snippet to find the root cause. Thanks

**Comment by gadagashwini** [comment] 2020-04-08 07:14
@abdou31, Any update

**Comment by abdou31** [comment] 2020-04-09 13:59
Hello @gadagashwini , I have just made an update in the last line of the code:

#model.save(args["model"], save_format="h5") the new version Tensorflow 2.0
model.save(args["model"]) # the version that I've used Tensorflow 1.13.1

**Comment by gadagashwini** [comment] 2020-04-13 04:22
@abdou31, Could you provide the complete modified code. Thanks

**Comment by Saduf2019** [comment] 2020-04-19 17:03
@abdou31,
please update on the above comment

**Comment by Saduf2019** [comment] 2020-04-27 05:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by Saduf2019** 2020-04-27 05:36 UTC
Labels: TF 1.13, stalled, stat:awaiting response, type:bug

**Comment by engrazr** [comment] 2020-06-17 09:46
save the 'model_name{}'.format(model_format) for example:
model_format='.h5'
model.save('model_name{}'.format(model_format))
