### ISSUE TITLE
OP_REQUIRES failed at sparse_tensor_dense_matmul_op.cc:146 : Invalid argument: k (784) from index[4352,1] out of bounds (>=784)

### ISSUE THREAD

**Issue by sachinkmohan** [tensorflow/tensorflow#43842] opened 2020-10-07 11:00 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): [Referred code repository](https://github.com/WojciechMormul/deep-compression) 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Installed using conda 
- TensorFlow version (use command below): 1.15
- Python version: 3.6.12
- CUDA/cuDNN version: 11.1 
- GPU model and memory:

**Conda list of packages installed**
`# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.10.0           py36h9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py36h7b6447c_1    anaconda
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
async_generator           1.10             py36h28b3542_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
bleach                    3.2.1                      py_0    anaconda
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.7.22                     0    anaconda
certifi                   2020.6.20                py36_0    anaconda
cffi                      1.14.3           py36he30daa8_0    anaconda
dbus                      1.13.12              h746ee38_0    anaconda
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
entrypoints               0.3                      py36_0    anaconda
expat                     2.2.9                he6710b0_2    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.10.2               h5ab3b9f_0    anaconda
gast                      0.2.2                      py_0    conda-forge
glib                      2.56.2               hd408876_0    anaconda
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.31.0           py36h769ab6c_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.10.0          nompi_py36hecadee3_104    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
icu                       58.2                 he6710b0_3    anaconda
importlib-metadata        2.0.0            py36h9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py36h5ca1d4c_0    anaconda
ipython                   7.16.1           py36h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py36_0    anaconda
ipywidgets                7.5.1                      py_0    anaconda
jedi                      0.17.2                   py36_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.0.2                    py36_0    anaconda
jupyter                   1.0.0                    py36_7    anaconda
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py36_0    anaconda
jupyterlab_pygments       0.1.1                      py_0    anaconda
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.13.0               h8b12597_0    conda-forge
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               he19cac6_1    anaconda
markdown                  3.2.2                      py_0    conda-forge
markupsafe                1.1.1            py36h7b6447c_0    anaconda
mistune                   0.8.4            py36h7b6447c_0    anaconda
nbclient                  0.5.0                      py_0    anaconda
nbconvert                 6.0.6                    py36_0    anaconda
nbformat                  5.0.7                      py_0    anaconda
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.0                      py_1    anaconda
notebook                  6.1.1                    py36_0    anaconda
numpy                     1.19.1           py36h3849536_2    conda-forge
openssl                   1.1.1h               h7b6447c_0    anaconda
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.4                       py_0    anaconda
pandoc                    2.10.1                        0    anaconda
pandocfilters             1.4.2                    py36_1    anaconda
parso                     0.7.0                      py_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py36_0    anaconda
pickleshare               0.7.5                    py36_0    anaconda
pip                       20.2.2                   py36_0  
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.7                      py_0    anaconda
prompt_toolkit            3.0.7                         0    anaconda
protobuf                  3.13.0           py36h831f99a_0    conda-forge
ptyprocess                0.6.0                    py36_0    anaconda
pycparser                 2.20                       py_2    anaconda
pygments                  2.7.1                      py_0    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py36h22d08a2_1    anaconda
pyrsistent                0.17.3           py36h7b6447c_0    anaconda
python                    3.6.12               hcff3b4d_2  
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.6                     1_cp36m    conda-forge
pyzmq                     19.0.2           py36he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.0                  h7b6447c_0  
scipy                     1.5.2            py36h3a855aa_0    conda-forge
send2trash                1.5.0                    py36_0    anaconda
setuptools                49.6.0                   py36_1  
sip                       4.19.24          py36he6710b0_0    anaconda
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0  
tensorboard               1.15.0                   py36_0    conda-forge
tensorflow                1.15.0          mkl_py36h4920b83_0  
tensorflow-base           1.15.0          mkl_py36he1670d9_0  
tensorflow-estimator      1.15.1             pyh2649769_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3                    py36_0    anaconda
testpath                  0.4.4                      py_0    anaconda
tk                        8.6.10               hbc83047_0  
tornado                   6.0.4            py36h7b6447c_1    anaconda
traitlets                 4.3.3                    py36_0    anaconda
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py36_1    anaconda
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py36_0    anaconda
wrapt                     1.12.1           py36h8c4c3a4_1    conda-forge
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.2                he6710b0_3    anaconda
zipp                      3.2.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3`

**Describe the current behavior**
I am working on neural network pruning and the problem occurs when finding accuracy from the pruned weights. 

The code fails when it runs the `batch_acc = sess.run(accuracy,feed_dict={x_PH: batch_x, labels: batch_y})` in the deploy code. 

The training goes fine on the MNIST dataset. As I use deploy to find the accuracy from the pruned weights, I get an error on the multiplication between Sparse Tensor and Tensor. 

There are already issues on this. Found a stackoverflow thread on the same. 
https://stackoverflow.com/questions/34030140/is-sparse-tensor-multiplication-implemented-in-tensorflow

The error occurs at `tf.sparse.sparse_dense_matmul(w,x)` line.

`	def forward_matmul(self, x):
		
		if self.dense == False:
			w = tf.sparse.transpose(self.w_matrix, (1, 0))
			x = tf.transpose(x, (1, 0))
			x = tf.sparse.sparse_dense_matmul(w, x) # only left matrix can be sparse hence transpositions ### Changing tf.sparse.matmul() to tf.sparse.sparse_dense_matmul()
			x = tf.transpose(x, (1, 0))
		else:
			x = tf.matmul(x, self.w_matrix)
		
		return x`

**Describe the expected behavior**
The code should be able to predict the accuracy from the newly trained weights 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Please use the modified repository, which was initially failing because of the type conversion in the default code.
https://github.com/sachinkm308/deep-compression_v3/tree/v1.0 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

`(mlp8) mohan:~/mlp/git/deep-compression_v3$ python deploy.py 
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
layer: conv1
	valid matrix weights: 800
	total tensor weights: 800
	total matrix weights: 4917248
Tensor("Reshape:0", shape=(?, 784), dtype=float32)
x -  Tensor("Shape:0", shape=(2,), dtype=int32)
Tensor("transpose_1:0", shape=(784, ?), dtype=float32)
layer: conv2
	valid matrix weights: 51200
	total tensor weights: 51200
	total matrix weights: 19668992
x -  Tensor("Shape_1:0", shape=(2,), dtype=int32)
Tensor("transpose_5:0", shape=(6272, ?), dtype=float32)
layer: fc1
	valid matrix weights: 3211264.0
	total matrix weights: 3211264
WARNING:tensorflow:From /home/mohan/mlp/git/deep-compression_v3/layers.py:223: The name tf.sparse.matmul is deprecated. Please use tf.sparse.sparse_dense_matmul instead.

layer: fc2
	valid matrix weights: 10240.0
	total matrix weights: 10240
WARNING:tensorflow:From deploy.py:50: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
2020-10-07 12:58:33.749107: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-07 12:58:33.770019: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3999980000 Hz
2020-10-07 12:58:33.770318: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55891ca32840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-07 12:58:33.770345: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 2 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 1 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 2 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 
OMP: Info #250: KMP_AFFINITY: pid 2931 tid 2931 thread 0 bound to OS proc set 0
2020-10-07 12:58:33.779852: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
OMP: Info #250: KMP_AFFINITY: pid 2931 tid 3127 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 2931 tid 3147 thread 2 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 2931 tid 3148 thread 3 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 2931 tid 3149 thread 4 bound to OS proc set 4
2020-10-07 12:58:39.482282: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at sparse_tensor_dense_matmul_op.cc:146 : Invalid argument: k (784) from index[4352,1] out of bounds (>=784)
Traceback (most recent call last):
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: k (784) from index[4352,1] out of bounds (>=784)
	 [[{{node SparseTensorDenseMatMul/SparseTensorDenseMatMul}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy.py", line 62, in <module>
    batch_acc = sess.run(accuracy,feed_dict={x_PH: batch_x, labels: batch_y})
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: k (784) from index[4352,1] out of bounds (>=784)
	 [[node SparseTensorDenseMatMul/SparseTensorDenseMatMul (defined at /home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'SparseTensorDenseMatMul/SparseTensorDenseMatMul':
  File "deploy.py", line 25, in <module>
    x = tf.nn.relu(L1.forward_matmul(x))
  File "/home/mohan/mlp/git/deep-compression_v3/layers.py", line 353, in forward_matmul
    x = tf.sparse.sparse_dense_matmul(w, x, adjoint_a=False, adjoint_b=False, name=None) # only left matrix can be sparse hence transpositions ### Changing tf.sparse.matmul() to tf.sparse.sparse_dense_matmul()
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/ops/sparse_ops.py", line 2405, in sparse_tensor_dense_matmul
    adjoint_b=adjoint_b)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_sparse_ops.py", line 3063, in sparse_tensor_dense_mat_mul
    adjoint_b=adjoint_b, name=name)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/mohan/anaconda2/envs/mlp8/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by ravikyram** [comment] 2020-10-08 06:35
@sachinkm308 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by sachinkm308** [comment] 2020-10-08 09:35
I have created a tag for this repository which is failing.
https://github.com/sachinkm308/deep-compression_v3/tree/v1.0

Please let me know if you need anything else.

**Comment by ravikyram** [comment] 2020-10-08 11:35
I have tried in colab with TF version 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/161080835014dcdfb3197ab8a7a30398/untitled436.ipynb).Thanks!

**Comment by sachinkm308** [comment] 2020-10-09 10:36
Hey Team, 

I fixed this issue. 

`	def tensor_to_matrix(self, tensor, prune_mask, H_in, W_in, stride):
				
		# assume padding type 'SAME' and padding value 0 

		H_out = int(int(H_in +1)/stride) # padding 'SAME'
		W_out = int(int(W_in +1)/stride) # padding 'SAME'
		H_in = int(H_in)
		W_in = int(W_in)
					
		kH, kW, D_in, D_out = tensor.shape 
		
		self.D_out = D_out
		self.H_out = H_out
		self.W_out = W_out
 
		if self.dense == False:
			indices, values, dense_shape = [], [], [H_in * W_in * D_in, H_out* W_out * D_out] # sparse matrix
		else:
			matrix = np.zeros((H_in * W_in * D_in, H_out* W_out * D_out), dtype=np.float32) # dense matrix		
		
		for d_in in range(D_in):
			for d_out in range(D_out):
		
				# tf.nn.conv2d implementation doesn't go from top-left spatial location but from bottom-right
				for i_in_center in np.arange(H_in-1, -1, -stride): # kernel input center for first axis
					for j_in_center in np.arange(W_in-1, -1, -stride): # kernel input center for second axis
								
						i_out = int(i_in_center / stride)
						j_out = int(j_in_center / stride)

						for i in range(kH):
							
							i_in = int(i_in_center + i - kH/2)  #Changed to int as the indices were generating float values
								
							if i_in < 0 or i_in >= H_in: # padding value 0 
								continue 
													
							for j in range(kW):
								
								j_in = int(j_in_center + j -kW/2) #Changed to int as the indices were generating float values
								
								if j_in < 0 or j_in >= W_in: # padding value 0 
									continue
								
								# pruning mask: ones - valid weights, zero - pruned weights
								if prune_mask[i][j][d_in][d_out] == 0.0:
									continue		
								
								pos_in = self.get_linear_pos(i_in, j_in, W_in) + d_in * H_in * W_in
								pos_out = self.get_linear_pos(i_out, j_out, W_out) + d_out * H_out * W_out
								
								if self.dense == False:
									indices.append([pos_in, pos_out])
									values.append(tensor[i][j][d_in][d_out])
								else:
									matrix[pos_in][pos_out] = tensor[i][j][d_in][d_out]

		if self.dense == False:
			return indices, values, dense_shape  #Removing np.round as they don't need to be rounded anymore as i_in and j_in are changed to int
		else:
			return matrix`

Previously while returning `indices`, I changed to `np.round(indices)` because the default indices pair was returning me a list of float values. But indices and dense_shape of a SparseTensor is always int and only values can be float.

So in this code snipped above, I type casted `i_in` and  `j_in` values to int and removed `np.round(indices)` as mentioned above.

Thanks for all the help! Atleast I learned to work on google colab in a better way and to solve this bug ;)  

You may please close this issue by adding any additional comments if you have from your side.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:15
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:45 UTC
Labels: TF 1.15, comp:ops, stat:awaiting tensorflower, type:bug
