### ISSUE TITLE
Saving large graphs to S3 fails with InternalError: : Unable to connect to endpoint

### ISSUE THREAD

**Issue by smurching** [tensorflow/tensorflow#13844] opened 2017-10-20 01:24 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes; modified Tensorflow [save/load example code](https://www.tensorflow.org/programmers_guide/saved_model) to save a few large tensors to S3
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version**:
Git version: `v1.3.0-rc1-3504-g27767d8`
Tensorflow version: `1.4.0-rc1`
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: Nvidia Tesla K80 (12 GiB RAM)
- **Exact command to reproduce**: Run the code in [this gist](https://gist.github.com/smurching/8766a9d91c148ef7d89292b6dd4da5b8) in a Python shell. You'll need access to an S3 bucket for which you have write permissions.

### Describe the problem
I'm trying to save a large (~380 MB) graph to S3, but my call to `tf.Saver.save()` crashes after ~1 min with what appears to be an AWS SDK error (`InternalError: : Unable to connect to endpoint`).

If the error is indeed AWS related, it'd be helpful to wrap it in something to indicate that the error isn't coming from tensorflow. Here's the stacktrace:

```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<command-5036518> in <module>()
----> 1 test_save(num_tensors=10, tensor_size=10000000, save_path="s3://<redacted_s3_bucket_name>/model.ckpt")

<command-5036204> in test_save(num_tensors, tensor_size, save_path)
     18     sess.run(init_op)
     19     # Save the variables to disk.
---> 20     save_path = saver.save(sess, save_path)
     21     print("Model saved in file: %s" % save_path)

/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in save(self, sess, save_path, global_step, latest_filename, meta_graph_suffix, write_meta_graph, write_state)
   1571           model_checkpoint_path = sess.run(
   1572               self.saver_def.save_tensor_name,
-> 1573               {self.saver_def.filename_tensor_name: checkpoint_file})
   1574         else:
   1575           self._build_eager(

/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1119       results = self._do_run(handle, final_targets, final_fetches,
-> 1120                              feed_dict_tensor, options, run_metadata)
   1121     else:
   1122       results = []

/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1315     if handle is None:
   1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1317                            options, run_metadata)
   1318     else:
   1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1334         except KeyError:
   1335           pass
-> 1336       raise type(e)(node_def, op, message)
   1337 
   1338   def _extend_graph(self):

InternalError: : Unable to connect to endpoint
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, v0/_1, v1/_3, v2/_5, v3/_7, v4/_9, v5/_11, v6/_13, v7/_15, v8/_17, v9/_19)]]

Caused by op u'save/SaveV2', defined at:
  File "/tmp/1509404428358-0/PythonShell.py", line 990, in <module>
    launch_process()
  File "/tmp/1509404428358-0/PythonShell.py", line 986, in launch_process
    shell.executor.run()
  File "/tmp/1509404428358-0/PythonShell.py", line 263, in run
    self.shell.shell.run_cell(command_id, cmd, store_history=True)
  File "/tmp/1509404428358-0/PythonShell.py", line 572, in run_cell
    super(IPythonShell, self).run_cell(raw_cell, store_history, silent, shell_futures)
  File "/databricks/python/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2741, in run_cell
    interactivity=interactivity, compiler=compiler)
  File "/databricks/python/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes
    if self.run_code(code):
  File "/databricks/python/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<command-5036518>", line 1, in <module>
    test_save(num_tensors=10, tensor_size=10000000, save_path="s3://databricks-mllib/tmp/s3-save-failure/model.ckpt")
  File "<command-5036204>", line 13, in test_save
    saver = tf.train.Saver()
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 748, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 296, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 239, in save_op
    tensors)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1163, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/databricks/python/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): : Unable to connect to endpoint
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, v0/_1, v1/_3, v2/_5, v3/_7, v4/_9, v5/_11, v6/_13, v7/_15, v8/_17, v9/_19)]]
```

If I run the same code but checkpoint to my local filesystem the save op runs without error.
The error also only seems to occur for large graphs (running the [linked gist](https://gist.github.com/smurching/8766a9d91c148ef7d89292b6dd4da5b8) with smaller/fewer tensors works)

**Comment by andydavis1** [comment] 2017-10-20 19:45
@asimshankar Can you comment on this one?

**Comment by smurching** [comment] 2017-10-30 23:16
@asimshankar I was able to reproduce this error locally with tensorflow 1.4rc1, I'll update the issue description!

**Comment by quaeler** [comment] 2017-10-31 03:12
@smurching If you could reproduce it locally, could you remove the "If I run the same code but checkpoint to my local filesystem the save op runs without error." from your initial description?

Is the stack trace the same for the local error as well?

Lastly, are you running this on a relatively memory constrained device?

**Comment by smurching** [comment] 2017-10-31 04:15
My mistake, by "locally" I meant to say on a single machine -- I'm still trying to checkpoint to S3, with the stacktrace appearing as shown above. I'm running on a p2.xlarge AWS EC2 instance, which AFAIK has 61 GB RAM.

**Comment by sebaschaal** [comment] 2017-12-29 22:21
I am facing the same issue!
Trying to train a Faster RCNN Nasnet and put the checkpoints into an S3 bucket.
Would very much appreciate any feedback

**Comment by timonbimon** [comment] 2018-01-03 12:52
The same issue came up for me too.
When running a toy example and using a Saver to save a small graph to an S3 bucket it works, but when trying to write a Faster R-CNN (through the export_inference_graph.py from the Object Detection API) to S3, I get the following error (I used the latest nightly build with @yongtang's AWS logging):

```
2018-01-03 12:24:08.336668: I tensorflow/core/platform/s3/aws_logging.cc:53] Creating HttpClient with max connections2 and scheme http
2018-01-03 12:24:08.336680: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 2
2018-01-03 12:24:08.336688: I tensorflow/core/platform/s3/aws_logging.cc:53] Creating Instance with default EC2MetadataClient and refresh rate 900000
2018-01-03 12:24:08.336738: I tensorflow/core/platform/s3/aws_logging.cc:53] Successfully reloaded configuration.
2018-01-03 12:24:08.336763: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 25
2018-01-03 12:24:08.336906: I tensorflow/core/platform/s3/aws_logging.cc:53] Pool grown by 2
2018-01-03 12:24:08.336924: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-03 12:24:08.458925: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-03 12:24:11.461615: E tensorflow/core/platform/s3/aws_logging.cc:59] Curl returned error code 28
2018-01-03 12:24:11.461669: W tensorflow/core/platform/s3/aws_logging.cc:56] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-01-03 12:24:11.461681: W tensorflow/core/platform/s3/aws_logging.cc:56] Request failed, now waiting 0 ms before attempting again.
2018-01-03 12:24:11.461953: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-03 12:24:14.474854: E tensorflow/core/platform/s3/aws_logging.cc:59] Curl returned error code 28
2018-01-03 12:24:14.474919: W tensorflow/core/platform/s3/aws_logging.cc:56] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-01-03 12:24:14.474932: W tensorflow/core/platform/s3/aws_logging.cc:56] Request failed, now waiting 50 ms before attempting again.
2018-01-03 12:24:14.525228: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
...
2018-01-03 12:24:51.335497: W tensorflow/core/platform/s3/aws_logging.cc:56] Request failed, now waiting 12800 ms before attempting again.
2018-01-03 12:25:04.135817: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-03 12:25:07.149093: E tensorflow/core/platform/s3/aws_logging.cc:59] Curl returned error code 28
2018-01-03 12:25:07.149164: W tensorflow/core/platform/s3/aws_logging.cc:56] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-01-03 12:25:07.149200: I tensorflow/core/platform/s3/aws_logging.cc:53] Cleaning up CurlHandleContainer.
2018-01-03 12:25:07.149214: I tensorflow/core/platform/s3/aws_logging.cc:53] Cleaning up CurlHandleContainer.
2018-01-03 12:25:07.149567: W tensorflow/core/framework/op_kernel.cc:1198] Internal: : Unable to connect to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: : Unable to connect to endpoint

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "/home/ubuntu/train_and_serve/object_detection/exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/ubuntu/train_and_serve/object_detection/exporter.py", line 375, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/ubuntu/train_and_serve/object_detection/exporter.py", line 321, in _write_graph_and_checkpoint
    saver.save(sess, model_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1593, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: : Unable to connect to endpoint
```

**Comment by tensorflowbutler** [comment] 2018-01-18 19:07
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by jkinkead** [comment] 2018-01-24 01:05
This is probably an issue with the default timeout the S3 client uses. Try setting `S3_REQUEST_TIMEOUT_MSEC` to a large value (say, `600000`).

**Comment by tensorflowbutler** [comment] 2018-02-07 13:44
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-22 13:05
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by yongtang** [comment] 2018-02-26 19:42
@smurching As @jkinkead mentioned, adjusting `S3_REQUEST_TIMEOUT_MSEC` could help addressing the timeout issue when the graph is too large. I will close this issue for now, but feel free to reopen and continue the discussion if the issue persists.

**Closed by yongtang** 2018-02-26 19:42 UTC
Labels: stat:awaiting tensorflower

**Comment by jasstionzyf** [comment] 2018-09-14 02:00
@yongtang   where to set S3_REQUEST_TIMEOUT_MSEC ?

**Comment by quaeler** [comment] 2018-09-14 02:36
@jasstionzyf via environment variables - see https://github.com/tensorflow/tensorflow/pull/15899/files

**Comment by RKAtrishee** [comment] 2020-06-08 08:38
#Training the model
print(f'Beginning Training!')
current_time = datetime.now()
estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
print("Training took time ", datetime.now() - current_time)

Beginning Training!
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Create CheckpointSaverHook.
---------------------------------------------------------------------------
AbortedError                              Traceback (most recent call last)
<ipython-input-23-c162613f017e> in <module>
      2 print(f'Beginning Training!')
      3 current_time = datetime.now()
----> 4 estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
      5 print("Training took time ", datetime.now() - current_time)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/util/smdebug.py in run(*args, **kwargs)
     55     if pre_hook:
     56       args, kwargs = pre_hook(function, *args, **kwargs)
---> 57     return_value = function(*args, **kwargs)
     58     if post_hook:
     59       post_hook(function, return_value, *args, **kwargs)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    368 
    369       saving_listeners = _check_listeners_type(saving_listeners)
--> 370       loss = self._train_model(input_fn, hooks, saving_listeners)
    371       logging.info('Loss for final step: %s.', loss)
    372       return self

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1159       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1160     else:
-> 1161       return self._train_model_default(input_fn, hooks, saving_listeners)
   1162 
   1163   def _train_model_default(self, input_fn, hooks, saving_listeners):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1193       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
   1194                                              hooks, global_step_tensor,
-> 1195                                              saving_listeners)
   1196 
   1197   def _train_model_distributed(self, input_fn, hooks, saving_listeners):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1488         config=self._session_config,
   1489         max_wait_secs=self._config.session_creation_timeout_secs,
-> 1490         log_step_count_steps=log_step_count_steps) as mon_sess:
   1491       loss = None
   1492       any_step_done = False

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py in MonitoredTrainingSession(master, is_chief, checkpoint_dir, scaffold, hooks, chief_only_hooks, save_checkpoint_secs, save_summaries_steps, save_summaries_secs, config, stop_grace_period_secs, log_step_count_steps, max_wait_secs, save_checkpoint_steps, summary_dir)
    582       session_creator=session_creator,
    583       hooks=all_hooks,
--> 584       stop_grace_period_secs=stop_grace_period_secs)
    585 
    586 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py in __init__(self, session_creator, hooks, stop_grace_period_secs)
   1018         hooks,
   1019         should_recover=True,
-> 1020         stop_grace_period_secs=stop_grace_period_secs)
   1021 
   1022 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py in __init__(self, session_creator, hooks, should_recover, stop_grace_period_secs)
    717 
    718     for h in self._hooks:
--> 719       h.begin()
    720 
    721     worker_context = distribute_coordinator_context.get_current_worker_context()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py in begin(self)
    555 
    556   def begin(self):
--> 557     self._summary_writer = SummaryWriterCache.get(self._checkpoint_dir)
    558     self._global_step_tensor = training_util._get_or_create_global_step_read()  # pylint: disable=protected-access
    559     if self._global_step_tensor is None:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/summary/writer/writer_cache.py in get(logdir)
     61       if logdir not in FileWriterCache._cache:
     62         FileWriterCache._cache[logdir] = FileWriter(
---> 63             logdir, graph=ops.get_default_graph())
     64       return FileWriterCache._cache[logdir]

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/summary/writer/writer.py in __init__(self, logdir, graph, max_queue, flush_secs, graph_def, filename_suffix, session)
    365     else:
    366       event_writer = EventFileWriter(logdir, max_queue, flush_secs,
--> 367                                      filename_suffix)
    368 
    369     self._closed = False

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/summary/writer/event_file_writer.py in __init__(self, logdir, max_queue, flush_secs, filename_suffix)
     65     self._logdir = str(logdir)
     66     if not gfile.IsDirectory(self._logdir):
---> 67       gfile.MakeDirs(self._logdir)
     68     self._event_queue = six.moves.queue.Queue(max_queue)
     69     self._ev_writer = pywrap_tensorflow.EventsWriter(

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py in recursive_create_dir(dirname)
    436     errors.OpError: If the operation fails.
    437   """
--> 438   recursive_create_dir_v2(dirname)
    439 
    440 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py in recursive_create_dir_v2(path)
    451     errors.OpError: If the operation fails.
    452   """
--> 453   pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
    454 
    455 

AbortedError: All 10 retry attempts failed. The last failure: Unknown: : No response body.

**Comment by RKAtrishee** [comment] 2020-06-08 08:40
I am running the above script on sagemaker and getting the error. Please help me out.

**Comment by ConverJens** [comment] 2021-02-02 12:11
I'm using TFX on KubeFlow with Minio as S3 backend and I'm also encountering this issue. Any update?

**Comment by ConverJens** [comment] 2021-02-08 13:07
For us, this had to do with not running Minio in erasure mode: https://github.com/minio/minio/issues/11481.
