### ISSUE TITLE
cuda 10.2 issue

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#39778] opened 2020-05-22 05:51 UTC
Can tensorflow provide alternative CUDA prebuilt version as pytorch does?

this is really behind pytorch official site say supports cuda 10.1 only:

![image](https://user-images.githubusercontent.com/21303438/82635669-44d07a00-9c33-11ea-9bad-d407999f4331.png)

You can see pytorch is so user-friendly it provides every CUDA version prebuilt binarys.... I mean every not literally every but at least the decent on of CUDA 10.2.. (since cuda 11 out, 10.2 is not the newest)

But 10.2 is really common used in pytorch now...

**Comment by mihaimaruseac** [comment] 2020-05-22 16:50
Duplicate of #39247 

Meanwhile, you can symlink CUDA 10.2 to CUDA 10.1 and TF will work without any issues.

**Closed by mihaimaruseac** 2020-05-22 16:50 UTC
Labels: type:build/install, type:feature
