### ISSUE TITLE
Running rename_protobuf.sh causes sed: can't read s%#include \([<"]\)google/protobuf/%#include \1google/protobuf3/%: No such file or directory

### ISSUE THREAD

**Issue by StephenRostanti** [tensorflow/tensorflow#23099] opened 2018-10-19 07:10 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: https://github.com/tensorflow/tensorflow/commit/93bc2e2072e0daccbcff7a90d397b704a9e8f778/
- Python version: python3
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 10.0 / 7.1.4
- GPU model and memory: 

**Describe the problem**
https://stackoverflow.com/questions/52886112/running-rename-protobuf-sh

**Provide the exact sequence of commands / steps that you executed before running into the problem**
sudo bash tensorflow/contrib/makefile/download_dependencies.sh
sudo bash tensorflow/contrib/makefile/rename_protobuf.sh

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The error message:
sed: can't read s%#include \([<"]\)google/protobuf/%#include \1google/protobuf3/%: No such file or directory

**Comment by tensorflowbutler** [comment] 2018-10-19 19:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-11-07 19:15
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:50
Nagging Assignee @ymodak: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2019-02-05 00:12
@benoitsteiner Can you PTAL?

**Comment by ymodak** [comment] 2019-03-29 21:05
Closing this issue due to staleness. Please switch to latest version of TF and try again. Thanks!

**Closed by ymodak** 2019-03-29 21:05 UTC
Labels: contrib, type:build/install

**Comment by YixuanBan** [comment] 2020-06-05 07:16
The same issue too. Why there are so many "No such file or directory" here?
