### ISSUE TITLE
`tf.Module` saves in an invalid state when `tf.function` references a variable defined in another scope

### ISSUE THREAD

**Issue by joshhansen** [tensorflow/tensorflow#39780] opened 2020-05-22 06:08 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Fedora 32 x86_64
- TensorFlow installed from (source or binary): `pip install tensorflow`, 
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.2
- CUDA/cuDNN version: 10.2.89 / 7.6.5.32
- GPU model and memory: NVIDIA GeForce GTX 960M

**Describe the current behavior**
I am wrapping a Keras model within a `tf.Module` which has a `tf.function` that runs a training step. As part of that I calculate a loss. If the loss function references a variable defined in a different scope, the model seems to serialize successfully, but `saved_model_cli show --dir $DIR --all` crashes with a `KeyError` related to the `tf.function` when run on the model that was saved. This suggests that the model saved was in some way invalid---something that should have been caught prior to saving.

```
josh@achebe:~/Projects/Umpire$ ./venv/bin/saved_model_cli show --dir ai/umpire_regressor --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 
WARNING:tensorflow:From /home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py:1813: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "./venv/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/tools/saved_model_cli.py", line 1153, in main
    args.func(args)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/tools/saved_model_cli.py", line 714, in show
    _show_all(args.dir)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/tools/saved_model_cli.py", line 306, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/tools/saved_model_cli.py", line 186, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 602, in load_internal
    loader = loader_cls(object_graph_proto,
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 123, in __init__
    self._load_all()
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 134, in _load_all
    self._load_nodes()
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 264, in _load_nodes
    node, setter = self._recreate(proto, node_id)
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 370, in _recreate
    return factory[kind]()
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 359, in <lambda>
    "function": lambda: self._recreate_function(proto.function),
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 397, in _recreate_function
    return function_deserialization.recreate_function(
  File "/home/josh/Projects/Umpire/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 265, in recreate_function
    concrete_function_objects.append(concrete_functions[concrete_function_name])
KeyError: '__inference_fit_action_1159'
```

**Describe the expected behavior**
When I try to serialize a model, it should either serialize in a form that can be read by `saved_model_cli` or an error should be emitted.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense

fX = tf.float32

class TrainableAI(tf.Module):
    def __init__(self, keras_model, *args, **kwargs):
        self.model = keras_model
        super().__init__(*args, **kwargs)

    @tf.function(input_signature=[
        tf.TensorSpec(shape=(1,14,), dtype=fX),#1d_features
        tf.TensorSpec(shape=(1,19,), dtype=fX),# true_action_values
    ])
    def fit_action(self, _1d_features, true_action_values):
        estimated_action_values = self.model(_1d_features)
        mse = tf.keras.losses.MeanSquaredError()
        loss = mse(estimated_action_values, true_action_value)


input = Input(shape=(14,), name='1d_features', dtype=fX)
dense = Dense(64, activation='relu', name="dense0")(input)
action_value_estimate = Dense(1, activation='linear', name='estimate')(dense)
true_action_value = Input([1], dtype=fX, name='true_action_values')

model = Model(inputs=input, outputs=action_value_estimate, name='umpire_regressor')
trainable_ai = TrainableAI(model)

tf.saved_model.save(trainable_ai, 'umpire_regressor')
```

Then `saved_model_cli show --dir umpire_regressor --all`

Note that there is a typo where `action_value_estimate` is referenced instead of `action_value_estimates`. `action_value_estimate` without the trailing `s` is defined in the `if __name__=="__main__"` block. Resolving this typo resolves the error; however, the bug is that this was saved in an invalid state instead of an exception being thrown.

I tried running this in a Kaggle container running TF 2.1.0 and it caught the problem, so this may be a regression post-2.1.0.

**Comment by amahendrakar** [comment] 2020-05-22 14:52
Was able to reproduce the error with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/3fd00db62d096e0f5a9322d26b7f2931/39780-2-1.ipynb#scrollTo=vNy2Pmpl1F2_), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/70be824d707de6f0925fe71b3f9e0a96/39780-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/e95ee8d4da90a02f03d760aba6fecff4/39780-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by joshhansen** [comment] 2020-05-22 23:51
Yep, looks like it. By contrast, the Kaggle container running 2.1.0 gives `
ValueError: Attempted to save a function b'__inference_fit_action_95' which references a symbolic Tensor Tensor("true_action_values:0", shape=(None, 1), dtype=float32) that is not a simple constant. This is not supported.`

**Comment by jvishnuvardhan** [comment] 2020-08-07 00:50
@joshhansen I think this was resolved in recent `tf-nightly`. I am not able to reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1a2069fa920e8ffd6567288de9207915/39780-tf-nightly.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2020-08-15 03:10 UTC
Labels: TF 2.2, comp:autograph, stalled, stat:awaiting response, type:bug
