### ISSUE TITLE
Why are the Adam implementations in tensorflow.python.keras.optimizers and tensorflow.keras.optimizers different in tensorflow2.0stable? 

### ISSUE THREAD

**Issue by jiawei6636** [tensorflow/tensorflow#32980] opened 2019-10-02 05:34 UTC
Why are the Adam implementations in tensorflow.python.keras.optimizers and tensorflow.keras.optimizers different?

**Comment by jvishnuvardhan** [comment] 2019-10-03 22:20
@jiawei6636 Can you create a standalone code to reproduce the issue? I tried running a model with both the optimizers you mentioned. `optimizer=tf.keras.optimizers.Adam()` works as expected. But, `optimizer=tf.python.keras.optimizers.Adam()` throws an error as follows. Thanks!

```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-680887cceef6> in <module>()
     12 ])
     13 
---> 14 optimizer=tf.python.keras.optimizers.Adam()
     15 model.compile(optimizer='adam',
     16               loss='sparse_categorical_crossentropy',

AttributeError: module 'tensorflow' has no attribute 'python'
```

**Comment by jiawei6636** [comment] 2019-10-05 14:11
> @jiawei6636 Can you create a standalone code to reproduce the issue? I tried running a model with both the optimizers you mentioned. `optimizer=tf.keras.optimizers.Adam()` works as expected. But, `optimizer=tf.python.keras.optimizers.Adam()` throws an error as follows. [gist is here](https://colab.sandbox.google.com/gist/jvishnuvardhan/779336aedee841bbebdbd06521033076/untitled533.ipynb) for your reference. Thanks!
> 
> ```
> Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
> 11493376/11490434 [==============================] - 0s 0us/step
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-680887cceef6> in <module>()
>      12 ])
>      13 
> ---> 14 optimizer=tf.python.keras.optimizers.Adam()
>      15 model.compile(optimizer='adam',
>      16               loss='sparse_categorical_crossentropy',
> 
> AttributeError: module 'tensorflow' has no attribute 'python'
> ```

`from tensorflow.python.keras.optimizers import Adam `

**Comment by jvishnuvardhan** [comment] 2019-10-15 17:50
@jiawei6636 Anything under `tf.python.*` is private, intended for development only, rather than public use. Importing from tensorflow.python or any other modules (including import tensorflow_core...) is not supported, and can break unannounced. For full response on similar issue, you can check [here](https://github.com/tensorflow/tensorflow/issues/33075#issuecomment-539070546).

I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-10-15 17:50 UTC
Labels: TF 2.0, comp:keras, type:support
