### ISSUE TITLE
Loading a saved multi-input model

### ISSUE THREAD

**Issue by pabloi09** [tensorflow/tensorflow#39013] opened 2020-04-29 07:36 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I have written a simple standalone code to reproduce the error
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab
- TensorFlow version (use command below):
v2.2.0-rc3-0-gaad398b5e9 2.2.0-rc3
- Python version:
Python 3.6.9
- CUDA/cuDNN version:
CUDA Version 10.1.243

**Describe the current behavior**
1. I save the whole model with a ModelCheckpoint callback
2. I try to load the model from de checkpoint files
3. ```TypeError: Error converting shape to a TensorShape: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, 16]).```

**Describe the expected behavior**
The model should be loaded and ready to continue training or to be used for evaluation
**Standalone code to reproduce the issue**
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1CWRU1k2d0xtlww6hCavWHbKYb5aRrjw9)

**Other info / logs** 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    210   try:
--> 211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:

21 frames
TypeError: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, 16])

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in make_shape(v, arg_name)
    211     shape = tensor_shape.as_shape(v)
    212   except TypeError as e:
--> 213     raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
    214   except ValueError as e:
    215     raise ValueError("Error converting %s to a TensorShape: %s." % (arg_name,

TypeError: Error converting shape to a TensorShape: Dimension value must be integer or None or have an __index__ method, got TensorShape([None, 16]).
```

**Comment by amahendrakar** [comment] 2020-04-29 15:24
Was able to reproduce the issue with TF v2.1, [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/87dee37fd31153716c292d1ab4df899a/39013.ipynb#scrollTo=n49ArHDEeON1) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8d190e12a923604a08113f41a19c3338/39013-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by SachitNayak** [comment] 2020-05-21 07:50
I seem to face the same issue, although it's not during the loading of a saved model.
It occurs during model building/compilation itself.

**Comment by saikumarchalla** [comment] 2021-05-24 00:35
Was able to reproduce the issue using TF version 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/2cd7779cafef3cc4a7d3aee0bd98c347/untitled79.ipynb).

**Comment by songcaidao** [comment] 2021-09-01 08:52
Hitting the same error

**Comment by jvishnuvardhan** [comment] 2021-09-03 00:44
@pabloi09 Looks like this may be due to providing multi-input to a keras Sequential model. Please note that Sequential models only works with single-input and single-output. For multi input/outputs, please use Functional model. 

The warning also clearly mentions about multi-outputs provided to the model.

I tried to remove one branch in your multi-input Sequential model. With those modification, i didn't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/6ff409f85a1aee9b8950f2e2d785c116/untitled79.ipynb). Thanks!

**Comment by songcaidao** [comment] 2021-09-03 07:18
Thanks to @jvishnuvardhan 's reply, I was reminded  to check my code and then I found I was using **tf.keras.layers.Input**, when I tried to use **tf.keras.Input**, the error just gone. Maybe the previous is a type of keras Sequential model?

**Comment by songcaidao** [comment] 2021-09-03 08:31
Thanks to @jvishnuvardhan 's reply, I clear the error by remove Sequential model and just use Functional style code.

**Comment by jvishnuvardhan** [comment] 2021-09-10 16:30
Closing this issue as this was resolved. Thanks!

**Closed by jvishnuvardhan** 2021-09-10 16:30 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:apis, TF 2.2
