### ISSUE TITLE
Problem running build_all_ios.sh 

### ISSUE THREAD

**Issue by mweber7** [tensorflow/tensorflow#3065] opened 2016-06-27 21:00 UTC
Mac OS X: El Capitan (10.11.4)

I am trying to build Tensorflow for iOS and am following the "Building all at once" instructions found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/README.md).  When running the build_all_ios.sh file, I am getting the following errors:

In file included from /Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-802d984ade26/unsupported/Eigen/CXX11/../../../Eigen/Core:355:
/Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-802d984ade26/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/Complex.h:18:35: error: 
      statement expression not allowed at file scope
static uint32x4_t p4ui_CONJ_XOR = vld1q_u32( conj_XOR_DATA );
                                  
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/arm_neon.h:7609:39: note: 
      expanded from macro 'vld1q_u32'
#define vld1q_u32(__p0) __extension__ ({ \
                                      
In file included from tensorflow/core/kernels/xent_op.cc:20:
In file included from ./tensorflow/core/kernels/xent_op.h:20:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from /Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-802d984ade26/unsupported/Eigen/CXX11/Tensor:14:
In file included from /Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-802d984ade26/unsupported/Eigen/CXX11/../../../Eigen/Core:355:
/Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/downloads/eigen-eigen-802d984ade26/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/Complex.h:19:35: error: 
      statement expression not allowed at file scope
static uint32x2_t p2ui_CONJ_XOR = vld1_u32( conj_XOR_DATA );
                                  
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/arm_neon.h:7759:38: note: 
      expanded from macro 'vld1_u32'
#define vld1_u32(__p0) __extension__ ({ \
                                     
2 errors generated.
make: *** [/Users/mw/Tensorflow_gitclone/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/xent_op.o] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1
MW:makefile mw$ ./build_all_ios.sh

I have been able to overcome many issues up to this one but am now stuck.  Any suggestions?

**Comment by fcyy** [comment] 2016-06-28 01:49
I encountered exactly the same problem.   As a temporary measure just to get it to build the lib, I removed the assignment to the static vars mentioned above.    But in Xcode building the Camera sample, I got stuck on the same error described in #3004.   I set flags in Clang to ignore reference errors (bad idea, but I wanted to see how far I could take it), and managed to deploy the app to a physical iPad.  But it crashes on launch due to those missing refs.   It would be nice if this gets fixed in the next couple of hours as I'm planning to demo the app at a company meeting.   So you'll have a very motivated tester here if you have a fix.

**Closed** 2016-06-28 13:38 UTC
Labels: triaged

**Comment by petewarden** [comment] 2016-06-28 13:40
Sorry about the recent issues with iOS building. I've put in a temporary patch for the Eigen problem until we get around the underlying problem, along with a build process fix in #3075. Can you give this a try and let me know if you're still having issues?

**Comment by fcyy** [comment] 2016-06-28 14:45
Thanks, Pete.   That fixed the problem!   I can confirm that the sample iOS app 'CameraExample' is now running happily on my iPad Air.

**Comment by petewarden** [comment] 2016-06-28 14:46
That's awesome to hear, thanks for the update!

**Comment by mweber7** [comment] 2016-06-29 01:01
This worked for me as well.  Thanks!
