### ISSUE TITLE
bad juju in docker vm url

### ISSUE THREAD

**Issue by jnorthrup** [tensorflow/tensorflow#31226] opened 2019-08-01 07:43 UTC
goal as user: 
would like to click the url produced referring to localhost tokens. using docker as recceomended by tensorflow project  is the fastest and most repeatable way to get gpu+tensorflow+ jupyter
  
console output:

```
________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

[I 07:28:24.895 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
[I 07:28:25.795 NotebookApp] Serving notebooks from local directory: /tf
[I 07:28:25.795 NotebookApp] The Jupyter Notebook is running at:
[I 07:28:25.795 NotebookApp] http://(2950c268081b or 127.0.0.1):8888/?token=9c954171d97b7cf33d46c63611fe4c4f04558871aaf5eb06
[I 07:28:25.795 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:28:25.798 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-1-open.html
    Or copy and paste one of these URLs:
        http://(2950c268081b or 127.0.0.1):8888/?token=9c954171d97b7cf33d46c63611fe4c4f04558871aaf5eb06
```  

problem:

` http://(2950c268081b or 127.0.0.1):8888 ` is not a legal url in most browsers.  in even fewer browsers, this will result in useful copy and paste

**Comment by ravikyram** [comment] 2019-08-02 10:21
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by jnorthrup** [comment] 2019-08-06 12:22
@ravikyram this is bone stock ubuntu 18.04 following the tensorflow web page to pursue the docker prescription with the above mentioned instance tags

**Comment by angersson** [comment] 2019-08-06 17:25
I'm afraid I don't have the time to work on this, but please feel free to submit a PR!

**Comment by jnorthrup** [comment] 2019-08-07 06:19
well, what produces the string "(2950c268081b or 127.0.0.1)" ?

and what code uses that string?

coming from the 5 minute docker instructions, my familiarity with the internals is quite low.

**Comment by jnorthrup** [comment] 2019-08-07 06:22
i think the best PR to solve the bug would be to comment out the docker instructions from the website and leave the jupyter code alone.

**Comment by mihaimaruseac** [comment] 2019-08-13 17:56
Those error messages seem to come from Jupyter, not Tensorflow code. See for example https://github.com/jupyter/notebook/issues/3947

I think we can close this issue in this case.

**Closed by mihaimaruseac** 2019-08-13 17:56 UTC
Labels: stat:contributions welcome, type:build/install
