### ISSUE TITLE
Is there something wrong with AttentionWrapper when use BahdanauAttention or LuongAttention? 

### ISSUE THREAD

**Issue by qzfnihao** [tensorflow/tensorflow#23064] opened 2018-10-18 07:10 UTC
When using attention model, we need to get a AttentionWrapper object,  which defined in tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py. When focused on the func call, i find something wrong. 

tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py: In class AttentionWrapper:
  def call(self, inputs, state):
    """Perform a step of attention-wrapped RNN.
    - Step 1: Mix the `inputs` and previous step's `attention` output via
      `cell_input_fn`.
    - Step 2: Call the wrapped `cell` with this input and its previous state.
    - Step 3: Score the cell's output with `attention_mechanism`.
    - Step 4: Calculate the alignments by passing the score through the
      `normalizer`.
    - Step 5: Calculate the context vector as the inner product between the
      alignments and the attention_mechanism's values (memory).
    - Step 6: Calculate the attention output by concatenating the cell output
      and context through the attention layer (a linear layer with
      `attention_layer_size` outputs).
....
    # Step 1: Calculate the true inputs to the cell based on the
    # previous attention value.
    cell_inputs = self._cell_input_fn(inputs, state.attention)
    cell_state = state.cell_state
    cell_output, next_cell_state = self._cell(cell_inputs, cell_state)
.....
    for i, attention_mechanism in enumerate(self._attention_mechanisms):
      attention, alignments, next_attention_state = _compute_attention(
          attention_mechanism, cell_output, previous_attention_state[i],
          self._attention_layers[i] if self._attention_layers else None)
      alignment_history = previous_alignment_history[i].write(
          state.time, alignments) if self._alignment_history else ()

      all_attention_states.append(next_attention_state)
      all_alignments.append(alignments)
      all_attentions.append(attention)
      maybe_all_histories.append(alignment_history)
.....

The code is just copyed.  In _compute_attention(...),  we get alignment and attention, but here the second parameter  we used is  cell_ouput , which was calculted from self._cell(cell_inputs, cell_state). 

But In paper: neuaral machine translation by  jonintly learning to align and trainslate(https://arxiv.org/pdf/1409.0473.pdf), the BahdanauAttention, which should be calculated by cell_state,  not cell_output.

In paper: effective Approaches to Attention-based Neural Machine Translation(https://arxiv.org/pdf/1508.04025.pdf), i cannot  find the LuongAttention used to calculate current cell state and output, so, how should step 1 occured? The default self._cell_input_fn(inputs, state.attention) just cancat input and stattion.

Is there someting wrong?

**Comment by tensorflowbutler** [comment] 2018-10-18 18:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment] 2018-10-30 22:44
@qzfnihao  -  Hi, could you please provide the information asked by the tensorflowbutler. Thanks !

**Comment by harshini-gadige** [comment] 2018-11-01 20:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-01 20:49 UTC
Labels: comp:apis, stat:awaiting response, type:bug/performance
