### ISSUE TITLE
[CMAKE] Unresolved external symbol rdft

### ISSUE THREAD

**Issue by mrlzla** [tensorflow/tensorflow#9961] opened 2017-05-17 08:55 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 (Visual studio 2015)
- **TensorFlow installed from (source or binary)**: via cmake and includes into c++ project as static lib.(tensorflor_static.lib file).

### Describe the problem
After successful building Release version I tried to add tensorflow_static.lib and dependencies into c++ project. Then linker threw an error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2001	unresolved external symbol rdft	MyLib	C:\path\to\release\tensorflow_static.lib(spectrogram.obj)	1

**Comment by ali01** [comment] 2017-05-17 23:48
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by mrlzla** [comment] 2017-05-18 10:04
I build tensorflow from sources and use the latest version of master branch.
 Windows 10 (Visual studio 2015). Build in Release, x64.

**Comment by ali01** [comment] 2017-05-20 01:10
Hi @mrlzla, thank you for reaching out. Could you please provide any additional information that might help us reproduce this problem? Exact command lines or precise sequences of steps would be very helpful. Thanks!

**Comment by mrlzla** [comment] 2017-05-23 11:02
That's how I compile tensorflow:

```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=%CONFIGIRATION% -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX -DPYTHON_EXECUTABLE=%PYTHONPATH% -Dtensorflow_BUILD_SHARED_LIB=ON -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF
MSBuild /p:Configuration=%CONFIGIRATION% tensorflow_static.vcxproj
```

**Comment by michaelisard** [comment] 2017-06-05 16:56
@mrry could you reassign to whomever supports Windows configuration?

**Comment by mrry** [comment] 2017-06-05 17:08
AFAICT, @petewarden added the spectrogram code, which appears to be causing the failure, in 7c9d2a458ee6cb925a0b3d23793d0e356a6eac12.

**Comment by petewarden** [comment] 2017-06-16 21:24
What's the best way to reproduce this, since I believe the standard Windows cmake builds are working? Is there a script I can run to kick off a test that shows this error?

**Comment by mrry** [comment] 2017-06-20 16:42
I'd guess the issue is `-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX`, which AFAIK isn't part of the standard build. Probably easiest to run the build on a GCE VM (@gunan or @yifeif might have a canonical configuration script) using the following script:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/cpu/cmake/run_build.bat

...although you'll need to modify the CMake invocation with the additional AVX flag.

**Comment by gunan** [comment] 2017-06-21 17:42
Correct, windows build uses that script.
We do not currently build on windows using AVX on CI, because not all machines seem to have AVX, but we can revisit this.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:35
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:04
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:26
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2018-01-29 22:53
We haven't had a chance to work on this one for the last few months, and I'm not sure when we will get to it, so closing it as infeasible. Contributions are very welcome, and please reopen if this is still an issue for you.

**Closed by petewarden** 2018-01-29 22:53 UTC
Labels: type:build/install
