### ISSUE TITLE
Unexpected failure when preparing tensor allocations

### ISSUE THREAD

**Issue by Meghraj1998** [tensorflow/tensorflow#32110] opened 2019-08-30 10:59 UTC
Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/conv.cc:235 input->dims->size != 4 (1 != 4)Node number 0 (CONV_2D) failed to prepare.

**Comment by Meghraj1998** [comment] 2019-08-30 11:00
byte[] i=imgData.array();






            ByteBuffer buffer = ByteBuffer.wrap(i);
            FloatBuffer fb = buffer.asFloatBuffer();

            float[] floatArray = new float[fb.limit()];
            fb.get(floatArray);


            tflite.run(floatArray, labelProbArray);

**Comment by gadagashwini** [comment] 2019-09-03 06:30
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment] 2019-09-09 06:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-09-09 06:36 UTC
Labels: comp:lite, stat:awaiting response, type:support
