### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#33203] opened 2019-10-10 11:10 UTC
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0.0
- Python version:3.7
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: 1060 6GB

Tell me how to run the code on TF 2.0?
The problem arises only in the second era, as if the memory of the GPU is not cleared.
The first version helps
`tf.keras.backend.get_session().run(tf.global_variables_initializer())`
Code
https://github.com/sgenza/keras_crnn

**Comment by gadagashwini** [comment] 2019-10-11 06:43
@sonfiree, Please provide the minimal standalone code to reproduce the issue reported here. Indeed, it will help us to investigate the root cause. Thanks!

**Comment by sonfiree** [comment] 2019-10-11 08:08
> @sonfiree, Please provide the minimal standalone code to reproduce the issue reported here. Indeed, it will help us to investigate the root cause. Thanks!

https://github.com/sgenza/keras_crnn

**Comment by sonfiree** [comment] 2019-10-13 08:44
https://github.com/tensorflow/tensorflow/issues/33178

**Comment by gadagashwini** [comment] 2019-10-15 10:54
@sonfiree, Please provide more information on reproducing the issue. I cloned your repo but there is no description for how to use the repo. Thanks!

**Comment by mihaimaruseac** [comment] 2019-10-15 16:06
Duplicate of #33178 (in lack of reproducer being provided here, OP pointed to duplicate)

**Closed by mihaimaruseac** 2019-10-15 16:06 UTC
Labels: TF 2.0, stat:awaiting response
