### ISSUE TITLE
Dataset passed to group_by_window's reduce_func is a DatasetV2 instead of DatasetV1

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#29024] opened 2019-05-25 09:23 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: 1.14.0rc0
- Python version: 3.6.6

**Describe the current behavior**

In 1.14.0rc0, the dataset passed to the `reduce_func` function of `tf.data.experimental.group_by_window` is a `DatasetV2` instance instead of `DatasetV1`.

**Describe the expected behavior**

In TF V1, the dataset instance should inherit from `DatasetV1`, not `DatasetV2`.

**Code to reproduce the issue**

The following code raises an assertion error:

```python
import tensorflow as tf

def _reduce_func(key, dataset):
    assert isinstance(dataset, tf.data.Dataset)
    return dataset.batch(5)

dataset = tf.data.Dataset.range(100)
dataset = dataset.apply(tf.data.experimental.group_by_window(
    lambda x: x % 2, _reduce_func, window_size=5))
```

**Other info / logs**

This specifically breaks codes that use the V1 properties `output_*` within the `reduce_func` function.

**Comment by muddham** [comment] 2019-05-27 12:51
@guillaumekln Can you please try the code in 2.0.0-alpha0 and let us know it progresses. Thanks!

**Comment by guillaumekln** [comment] 2019-05-27 13:22
Of course it works in 2.0 but this issue is about the next V1 release and a code that used to work in previous versions.

**Comment by jsimsa** [comment] 2019-05-29 22:46
Thank you for reporting the problem @guillaumekln.

The `tf.data.Dataset.output_*` API is deprecated (see [documentation](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/data/Dataset)) and you can use `tf.data.get_output_*` instead (see [here](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/data/get_output_shapes)).

To be clear, I understand that the change in tf.data behavior breaks code that worked in TF 1.13 and I apologize for that. FWIW, the API that results in the breakage is marked as deprecated and the deprecation warning includes information about the replacement API.

I was able to identify the root cause but the fix is non-trivial. Given the existence of replacement API and severity of the issue, my assessment is that we will not attempt to fix this.

**Closed by jsimsa** 2019-05-29 22:46 UTC
Labels: comp:data, stat:awaiting tensorflower, type:bug/performance
