### ISSUE TITLE
Cmake nightly builds for Windows are broken for more than a month!

### ISSUE THREAD

**Issue by zyavrik** [tensorflow/tensorflow#12977] opened 2017-09-11 19:42 UTC
Cmake nightly builds for Windows are broken for more than a month!
Will tensorflow ever support Windows again?

**Comment by zyavrik** [comment] 2017-09-11 21:56
The head revision fails with the error (compiling with GPU support):

`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.ta‌​rgets(171,5): error MSB6006: "cmd.exe" e xited with code 1. [C:\tensorflow\tensorflow\contrib\cmake\build\cub.vcxproj]
`
The revision on the moment of the last successful nightly build fails as well (why?) with the error:
`
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.ta‌​rgets(171,5): error MSB6006: "cmd.exe" e xited with code 1. [C:\tensorflow-cmake\tensorflow\contrib\cmake\build\gemmlowp‌​.vcxproj]`

**Comment by fmannan** [comment] 2017-09-12 21:32
I'd the same problem due to hash mismatch (see below). I'd to change the hash in `cmake\external\gemmlowp.cmake` to get over this problem.

```
  -- verifying file...
         file='D:/devel/tensorflow/tensorflow/contrib/cmake/build/downloads/010bb3e71a26ca1d0884a167081d092b43563996.tar.gz'
  -- SHA256 hash of
      D:/devel/tensorflow/tensorflow/contrib/cmake/build/downloads/010bb3e71a26ca1d0884a167081d092b43563996.tar.gz
    does not match expected value
      expected: '0d7a44327e26b622ee08faaea10f8d10b439bcfda622f9c98be1c036bc645cad'
        actual: '861cc6d9d902861f54fd77e1ab79286477dcc559b2a283e75b9c22d37b61f6ae'
  -- Hash mismatch, removing...
  CMake Error at gemmlowp-stamp/download-gemmlowp.cmake:157 (message):
    Each download failed!
  
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\devel\tensorflow\tensorflow\contrib\cmake\build\gemmlowp.vcxproj]
Done Building Project "D:\devel\tensorflow\tensorflow\contrib\cmake\build\gemmlowp.vcxproj" (default targets) -- FAILED.
```

**Comment by yaroslavvb** [comment] 2017-09-13 19:22
btw, AVX optimized Windows binary wheel is the most requested wheel on https://github.com/yaroslavvb/tensorflow-community-wheels/issues

**Comment by mrry** [comment] 2017-09-13 20:24
@ekelsen Erich: The current build failure (see e.g. [here](http://ci.tensorflow.org/job/tf-master-win-gpu-cmake/979/console)) looks like it might be caused by the GPU reduction code you added in 42fcbb196052823c4393a4d5d8682ca425253f6a. It looks like MSVC can't infer the template arguments for `BlockReduce()` and `WarpReduce()`... can you please take a look?

**Comment by ekelsen** [comment] 2017-09-13 20:42
I have a fix internally, going in today.

**Comment by zyavrik** [comment] 2017-09-14 20:49
@ekelsen, did you fix it? Nightly builds are still broken...

**Comment by ekelsen** [comment] 2017-09-14 21:16
well, I did fix one problem, but it looks like there's another one.  These tests don't run internally, so it can be hard to tell sometimes...  There is a PR with a fix for this issue here: https://github.com/tensorflow/tensorflow/pull/12920/files

I'll accelerate getting that part of that CL that solves this issue submitted.

**Closed** 2017-09-15 02:28 UTC
Labels: stat:awaiting tensorflower, type:build/install

**Comment by zyavrik** [comment] 2017-09-19 03:35
Why have you closed it? The problem is still not resolved!
