### ISSUE TITLE
tf lite model error

### ISSUE THREAD

**Issue by prakHr** [tensorflow/tensorflow#36491] opened 2020-02-05 15:11 UTC
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED. Here is a list of operators for which you will need custom implementations: IdentityN.

**Comment by LexusH** [comment] 2020-02-05 19:42
Hey @prakHr 

I'm attempting to triage issues in order to speed up the debugging process. Can you please give an example of the operators you tried to run to see if this is a bug or an intentional exclusion? If this is not a bug it might be best labeled as type:feature and comp:lite just to get the right eyes on this project!

**Comment by gadagashwini** [comment] 2020-02-06 06:11
@prakHr,
If you are using the [Python converter](https://www.tensorflow.org/lite/convert/python_api), with the latest version of TF/TFLite (nightly maybe?) could you try adding the following line pre-conversion:

`converter.experimental_new_converter = True`

If that doesn't work, it looks like we don't support the op yet :-(. You could try using [Select TF ops](https://www.tensorflow.org/lite/guide/ops_select) if you are using our C++/Java APIs. Thanks!

**Comment by gadagashwini** [comment] 2020-02-17 10:15
@prakHr, Is this still as issue ?

**Comment by gadagashwini** [comment] 2020-03-03 10:51
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-03-03 10:51 UTC
Labels: comp:lite, stat:awaiting response, type:support
