### ISSUE TITLE
Print Version of cuDNN Being Used

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4003] opened 2016-08-24 04:08 UTC
Right now what you get is device info for example:

```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
```

Theano prints:

```
Using gpu device 0: GRID K520 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)
```

giving you device info but also info on the version of cuDNN.

**Comment by prb12** [comment] 2016-08-24 16:44
There should also be a log message with the cuDDN shared library version from [here] ?(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L108)

**Comment by cancan101** [comment] 2016-08-24 16:48
No version though:
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
```

**Comment by cancan101** [comment] 2016-08-24 17:41
When there is a mismatch, might also be cool to print what compute capabilities TF was built with next to the compute capabilities of the device.

**Comment by prb12** [comment] 2016-08-24 18:10
OK - I'm pretty sure I see versions on the .so files when I run internally.  
I agree that having the fill path would be useful to triage library version issues.

**Comment by prb12** [comment] 2016-08-24 18:12
@zheng-xq  These sort of diagnostics might be useful - is there an obvious place to add some extra log info?

**Comment by zheng-xq** [comment] 2016-08-24 18:15
Stream-executor has both the build time and compile time information of Cudnn. Adding Jason, the owner of stream-executor here.

**Comment by vrv** [comment] 2016-08-24 18:23
Yes, it's just embedded in cuda_dnn.cc.  Might be worth somehow surfacing that when we load the DSO.   People already don't like the fact that we log this to output though, so I'm worried about adding a separate LOG statement :)

**Comment by Mistobaan** [comment] 2016-08-25 01:24
Also notice that Description has already a `ToMap()` that could be consumed to output all the key/values.  I agree that is unexpected to see all dump of information and at the beginning looks like the library is not working. 
Maybe add a verbosity env parameter to control when to output the device description ?

**Comment by vrv** [comment] 2016-08-25 01:46
The problem is that, most of the time, this information shows up in logs that people use to report to us and is actually useful.  It would make our life harder to help people if we turned that off by default. :(   Maybe one day when GPUs are just easier to use, we could turn it off by default.

**Comment by akors** [comment] 2016-09-01 08:29
I think this is related to #4090 .

Would it be possible to not only dump the CUDA, cuDNN version and Compute capabilities into the log, but also make them available as python variables in the TensorFlow module?

**Comment by tensorflowbutler** [comment] 2017-12-22 07:43
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:11
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:21
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by gunan** [comment] 2018-02-07 23:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

deduoing against https://github.com/tensorflow/tensorflow/issues/10827

**Closed by gunan** 2018-02-07 23:40 UTC
Labels: stat:contributions welcome, type:feature
