### ISSUE TITLE
Run model on ios

### ISSUE THREAD

**Issue by Onotoko** [tensorflow/tensorflow#20682] opened 2018-07-11 02:51 UTC
Hi friends,
when I run a model on ios, I got an error:
Running model failed:Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv2d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_x_0, conv2d/kernel/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
I using tensorflow 1.8.0 to trainning (but when I using tensorflow 1.5.0 I still got same error when run model on ios)
Please kindly give me an advice for this. Thanks

**Comment by tensorflowbutler** [comment] 2018-07-11 12:47
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Onotoko** [comment] 2018-07-12 03:04
Thank you for your response, I fixed it. The reason is tensorflow for mobile using lower level than tensorflow for PC. I hope tensorflow team can update the version for tensorflow for mobile.
Thanks!

**Comment by tensorflowbutler** [comment] 2018-07-27 18:55
Nagging Assignee @angersson: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by angersson** [comment] 2018-08-01 21:15
It looks like this issue has been resolved, so I'm closing it. Thanks!

**Closed by angersson** 2018-08-01 21:15 UTC
