### ISSUE TITLE
cpu tensorflow win: 7, DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by nouranik** [tensorflow/tensorflow#26451] opened 2019-03-07 16:08 UTC
Please make sure that this is a build/installation issue. As per our GitHub Policy, we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 7
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
TensorFlow installed from (source or binary): https://www.tensorflow.org/install/pip
TensorFlow version: 1.12
Python version: 3.6.8
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source):-
GCC/Compiler version (if compiling from source):-
CUDA/cuDNN version: CUDA 9.2, cuDNN64_7
GPU model and memory: NVIDIA quadro 2000 graphic card, Intel Xeon.
Describe the problem

Traceback (most recent call last):
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal
.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal
.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_init_.py", line 24, in <module

from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python_init_.py", line 49, in

from tensorflow.python import pywrap_tensorflow
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 74, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal
.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal
.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

Any other info / logs

I have problem with CPU model!!!!!!!!!!!!!!!!!!

I have problem with cpu version. only 1.5 workes for me and faced error for installing CUDA 9.0. therefore I installed CUDA 9.2! what is the source of error? I tried different version of tensorflow and cuda!!!!!!

thanks.

**Comment by Ayush517** [comment] 2019-03-07 16:36
@nouranik Can you please tell the template. Please provide details about what platform you are using (operating system, architecture), your TensorFlow version, did you compile from source or install a binary. Make sure you also include the exact command if possible to produce the output included in your test case.
It is really difficult to help without this information. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-07 22:40
Thanks @Ayush517 
@nouranik Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by nouranik** [comment] 2019-03-08 08:20
> @nouranik Can you please tell the template. Please provide details about what platform you are using (operating system, architecture), your TensorFlow version, did you compile from source or install a binary. Make sure you also include the exact command if possible to produce the output included in your test case.
> It is really difficult to help without this information. Thanks!

thanks, done!

**Comment by jvishnuvardhan** [comment] 2019-03-08 21:19
@nouranik Could you check tested build [configuration](https://www.tensorflow.org/install/source_windows#cpu). [Here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12/blob/master/README.md) are the instructions I created that could you help you installing TF1.12. I think there is a similar resolved [issue](https://github.com/tensorflow/tensorflow/issues/26227#issuecomment-471068552) on Win7 that could help you. Please let me know how it progresses. Thanks!

**Comment by nouranik** [comment] 2019-03-11 08:20
thnak you for your helps. I already used the instructions. I can not install CUDA 9.0 it has error.
I installed 9.2 but still does not work. why I face with tensorflow CPU error?

**Comment by jvishnuvardhan** [comment] 2019-03-11 13:51
@nouranik Did you uninstall python and tensorflow before installing then by following the instructions I provided. Thank you. It worked for many users. Some time when you have installed different versions of python and tensorflow, there will be some modules that could affect reinstalling of TF. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-11 14:02
@could you check this [resource](https://github.com/tensorflow/tensorflow/issues/12748) that might help you. Do you have python 32 bit or 64 bit? For some reason, if you cannot install CUDA9.0, and can only install CUDA9.2, you need to make sure that the paths are correctly referencing cuda and cuDNN folders. Thanks!

**Comment by GIT3513** [comment] 2019-04-03 02:03
> > @nouranik Can you please tell the template. Please provide details about what platform you are using (operating system, architecture), your TensorFlow version, did you compile from source or install a binary. Make sure you also include the exact command if possible to produce the output included in your test case.
> > It is really difficult to help without this information. Thanks!
> 
> thanks, done!
> it is about two weeks that I am facing with this issue!

How did you solve it? I got the same problem.THANKS

**Comment by malidoost** [comment] 2019-04-06 18:21
Hi @nouranik ,

I am a new PhD student in bioengineering. I am going to do vessel segmentation. I actually saw your message in the issues of "https://github.com/ellisdg/3DUnetCNN". I am also new to python and want to use 3D UNet from the mentioned github page. I was wondering if you could help me to use it. I was not able to find your email; therefore, I am contacting you heare! my email address is maalidoost@ucla.edu.

Thanks for your time and consideration and look forward to hearing from you.

Best, Mohammad

**Comment by jvishnuvardhan** [comment] 2019-04-08 17:11
> I installed 9.2 but still does not work. why I face with tensorflow CPU error?

There could be some dependencies that weren't removed completely. Check Environmental file and remove any CUDA or cuDNN related paths as you want to use TF-cpu. Thanks!

**Comment by mrry** [comment] 2020-01-03 17:55
Closing due to lack of recent activity.

**Closed by mrry** 2020-01-03 17:55 UTC
Labels: subtype:windows, type:build/install
