### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'matrix_band_part'

### ISSUE THREAD

**Issue by JiaxiangBU** [tensorflow/tensorflow#33737] opened 2019-10-26 04:24 UTC
There is a past issue #30297, but no updates. The reproducible example is here.

https://github.com/bojone/bert4keras/blob/eb4dcffd72b9ba08a7ccfb11aee8cdfaeed2d1df/bert4keras/bert.py#L292-L300

I get this error `AttributeError: module 'tensorflow' has no attribute 'matrix_band_part'`, when I run sorta code in Jupyter notebook.
Surely, I install 2.0.0 Tensorflow on Windows 7.  Here is my session information.

<details>
<summary>Session Info</summary>

```bash
# packages in environment at D:\install\miniconda:
#
# Name                    Version                   Build  Channel
absl-py                   0.8.1                    pypi_0    pypi
asn1crypto                0.24.0                   py37_0  
astor                     0.8.0                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   py37_1  
backcall                  0.1.0                    py37_0  
bert-tensorflow           1.0.1                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    3.1.0                    py37_0  
blis                      0.4.1                    pypi_0    pypi
boto                      2.49.0                   pypi_0    pypi
boto3                     1.9.252                  pypi_0    pypi
botocore                  1.12.252                 pypi_0    pypi
bzip2                     1.0.8                he774522_0  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_1  
cffi                      1.12.3           py37h7a1dbc1_0  
chardet                   3.0.4                    py37_1  
colorama                  0.4.1                    py37_0  
conda                     4.7.10                   py37_0  
conda-package-handling    1.3.11                   py37_0  
console_shortcut          0.1.1                         3  
cryptography              2.7              py37h7a1dbc1_0  
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.2                    pypi_0    pypi
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      py37_0  
fastprogress              0.1.21                   pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
funcy                     1.13                     pypi_0    pypi
future                    0.18.1                   pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
gensim                    3.8.1                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.24.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
idna                      2.8                      py37_0  
importlib-metadata        0.23                     pypi_0    pypi
intel-openmp              2019.4                      245  
ipykernel                 5.1.1            py37h39e3cac_0  
ipython                   7.7.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.0                      py_0  
jedi                      0.13.3                   py37_0  
jieba                     0.39                     pypi_0    pypi
jinja2                    2.10.1                   py37_0  
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.14.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.1                      py_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.5.0                      py_0  
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-bert                0.80.0                   pypi_0    pypi
keras-embed-sim           0.7.0                    pypi_0    pypi
keras-layer-normalization 0.13.0                   pypi_0    pypi
keras-multi-head          0.22.0                   pypi_0    pypi
keras-pos-embd            0.11.0                   pypi_0    pypi
keras-position-wise-feed-forward 0.6.0                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
keras-rectified-adam      0.17.0                   pypi_0    pypi
keras-self-attention      0.41.0                   pypi_0    pypi
keras-transformer         0.31.0                   pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libarchive                3.3.3                h0643e63_5  
libiconv                  1.15                 h1df5818_7  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.16               h9d3ae62_0  
libtiff                   4.0.10               hb898794_2  
libxml2                   2.9.9                h464c3ec_0  
lightgbm                  2.3.0                    pypi_0    pypi
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 h6df0209_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37he774522_0  
matplotlib                3.1.1                    pypi_0    pypi
menuinst                  1.4.16           py37he774522_0  
mistune                   0.8.4            py37he774522_0  
mkl                       2019.4                      245  
mkl_fft                   1.0.12           py37h14836fe_0  
mkl_random                1.0.2            py37h343c172_0  
more-itertools            7.2.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1  
murmurhash                1.0.2                    pypi_0    pypi
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
notebook                  6.0.0                    py37_0  
numexpr                   2.7.0                    pypi_0    pypi
numpy                     1.16.4           py37h19fb1c0_0  
numpy-base                1.16.4           py37hc3f5095_0  
olefile                   0.46                     py37_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openssl                   1.1.1c               he774522_1  
opt-einsum                3.1.0                    pypi_0    pypi
packaging                 19.2                     pypi_0    pypi
pandas                    0.25.0           py37ha925a31_0  
pandoc                    1.19.2.1                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pandocfilters             1.4.2                    py37_1  
parso                     0.5.0                      py_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.1.0            py37hdc69c19_0  
pip                       19.1.1                   py37_0  
plac                      0.9.6                    pypi_0    pypi
pluggy                    0.13.0                   pypi_0    pypi
powershell_shortcut       0.0.1                         2  
preshed                   3.0.2                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.9                    py37_0  
protobuf                  3.10.0                   pypi_0    pypi
py                        1.8.0                    pypi_0    pypi
pycosat                   0.6.3            py37hfa6e2cd_0  
pycparser                 2.19                     py37_0  
pygments                  2.4.2                      py_0  
pyks                      1.1.3                    pypi_0    pypi
pyldavis                  2.1.2                    pypi_0    pypi
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.2                    pypi_0    pypi
pyqt                      5.9.2            py37h6538335_2  
pyrsistent                0.14.11          py37he774522_0  
pysocks                   1.7.0                    py37_0  
pytest                    5.2.1                    pypi_0    pypi
python                    3.7.3                h8c8aaf0_1  
python-dateutil           2.8.0                    py37_0  
python-libarchive-c       2.8                     py37_11  
pytorch-cpu               1.1.0               py3.7_cpu_1    pytorch
pytz                      2019.1                     py_0  
pywin32                   223              py37hfa6e2cd_1  
pywinpty                  0.5.5                 py37_1000  
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     18.0.0           py37ha925a31_0  
qt                        5.9.7            vc14h73c81de_0  
qtconsole                 4.5.2                      py_0  
requests                  2.22.0                   py37_0  
ruamel_yaml               0.15.46          py37hfa6e2cd_0  
s3transfer                0.2.1                    pypi_0    pypi
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
seaborn                   0.9.0                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
sip                       4.19.8           py37h6538335_0  
six                       1.12.0                   py37_0  
smart-open                1.8.4                    pypi_0    pypi
spacy                     2.2.1                    pypi_0    pypi
sqlite                    3.29.0               he774522_0  
srsly                     0.1.0                    pypi_0    pypi
tensorboard               2.0.0                    pypi_0    pypi
tensorflow                2.0.0                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
tensorflow-hub            0.6.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
thinc                     7.1.1                    pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0  
torchvision-cpu           0.3.0             py37_cuNone_1    pytorch
tornado                   6.0.3            py37he774522_0  
tqdm                      4.32.1                     py_0  
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.2                   py37_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
wasabi                    0.2.2                    pypi_0    pypi
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
widgetsnbextension        3.5.0                    py37_0  
win_inet_pton             1.1.0                    py37_0  
wincertstore              0.2                      py37_0  
winpty                    0.4.3                         4  
wrapt                     1.11.1                   pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zeromq                    4.3.1                h33f27b4_3  
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  
```

</details>

**Comment by ravikyram** [comment] 2019-10-29 10:22
@JiaxiangBU 
Please, provide simple standalone code to reproduce the issue in our environment, then it is easy for localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2019-11-07 11:16
@JiaxiangBU 
Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2019-11-15 09:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-11-15 09:52 UTC
Labels: TF 2.0, stat:awaiting response, type:support
