### ISSUE TITLE
tensorflow build error in Illegal ambiguous match on configurable attribute "copts" in //tensorflow/python:gen_math_ops_py_wrappers_cc:

### ISSUE THREAD

**Issue by linyia01** [tensorflow/tensorflow#11807] opened 2017-07-27 09:23 UTC
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
ERROR: /root/tools/tensorflow-master/tensorflow/python/BUILD:1166:1: Illegal ambiguous match on configurable attribute "copts" in //tensorflow/python:gen_math_ops_py_wrappers_cc:
@local_config_cuda//cuda:using_clang
@local_config_cuda//cuda:using_nvcc
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 0.190s

**Comment by reedwm** [comment] 2017-07-27 17:30
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by eddytrex** [comment] 2017-08-06 18:21
Hi, I have a similar error

```bash
/home/nvidia/tensorflow/tensorflow/python/BUILD:1131:1: Illegal ambiguous match on configurable attribute "copts" in //tensorflow/python:gen_io_ops_py_wrappers_cc:
@local_config_cuda//cuda:using_clang
@local_config_cuda//cuda:using_nvcc
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 1.099s
```
My environment is:
Hardware: Jetson TX1
Tensorflow: v1.3.0-rc2
```bash
Linux tegra-ubuntu 4.4.38 #1 SMP PREEMPT Sun Aug 6 15:54:28 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

Thanks for your help

**Comment by linyia01** [comment] 2017-08-07 00:51
i have Solve it   by use python3.6  ，but python2.7  is error

**Comment by reedwm** [comment] 2017-08-07 22:39
@martinwicke can you take a look?

**Comment by martinwicke** [comment] 2017-08-08 00:27
@av8ramit This appears to be on 1.3RC2. Is it one of the know bazel issues with 0.5.3?

@eddytrex what version of bazel is this?

**Comment by av8ramit** [comment] 2017-08-08 00:44
It is not one of the known issues, but I'm curious to see if this is a regression in rc2 or a new issue with 0.5.3

@eddytrex or @linyia01 please reply with the bazel versions.

**Comment by linyia01** [comment] 2017-08-08 02:32
bazel  0.5.2

**Comment by linyia01** [comment] 2017-08-08 02:33
bazel 0.5.2 @av8ramit

**Comment by eddytrex** [comment] 2017-08-08 03:30
Build label: 0.5.0- (@non-git)

**Comment by eugenechae** [comment] 2017-08-08 15:51
I am seeing the same behavior with bazel 0.5.3

Ubuntu 16.04
Python 3.5.2

**Comment by av8ramit** [comment] 2017-08-08 20:52
I'm unfortunately unable to reproduce this with rc2 and 0.5.2 Still investigating.

**Comment by linyia01** [comment] 2017-08-09 03:03
python3.6 @av8ramit

**Comment by jwpowell055** [comment] 2017-08-12 20:41
The guilty lines are in tensorflow.bzl:

def _cuda_copts():
  """Gets the appropriate set of copts for (maybe) CUDA compilation.

    If we're doing CUDA compilation, returns copts for our particular CUDA
    compiler.  If we're not doing CUDA compilation, returns an empty list.

    """
  return cuda_default_copts() + select({
      "//conditions:default": [],
      "@local_config_cuda//cuda:using_nvcc": ([
          "-nvcc_options=relaxed-constexpr",
          "-nvcc_options=ftz=true",
      ]),
      "@local_config_cuda//cuda:using_clang": ([
          "-fcuda-flush-denormals-to-zero",
      ]),
  })

The reproduce the behavior it seems like you'd need to build CUDA support using Clang.

**Comment by jwpowell055** [comment] 2017-08-12 20:53
[This answer](https://stackoverflow.com/a/45644766/825785) at StackOverflow would seem to support that this interference in the configuration between using CUDA and using Clang is the problem.

**Comment by traviscross** [comment] 2017-10-19 22:35
The issue here, which remains a problem on `master` as of commit 89f15928293f62b63404ffbdabbb6a3b07274ff8, is that when you:

```
export TF_CUDA_CLANG=1
./configure
```

...then we create broken bazel `select` blocks like this:

```
def _cuda_copts():
  """Gets the appropriate set of copts for (maybe) CUDA compilation.

    If we're doing CUDA compilation, returns copts for our particular CUDA
    compiler.  If we're not doing CUDA compilation, returns an empty list.

    """
  return cuda_default_copts() + select({
      "//conditions:default": [],
      "@local_config_cuda//cuda:using_nvcc": ([
          "-nvcc_options=relaxed-constexpr",
          "-nvcc_options=ftz=true",
      ]),
      "@local_config_cuda//cuda:using_clang": ([
          "-fcuda-flush-denormals-to-zero",
      ]),
  })
```

A build with this configuration reliably fails as documented above.  We can prove to ourselves this must be the issue by "correcting" the configuration and hard-coding the result we want for each `select`:

```
diff --git a/tensorflow/core/platform/default/build_config/BUILD b/tensorflow/core/platform/default/build_config/BUILD
index f746b15fe..6e9da1179 100644
--- a/tensorflow/core/platform/default/build_config/BUILD
+++ b/tensorflow/core/platform/default/build_config/BUILD
@@ -34,11 +34,7 @@ tf_cuda_library(
     deps = [
         "//tensorflow/stream_executor",
     ] + select({
-        "//tensorflow:using_cuda_clang": ["//tensorflow/stream_executor:cuda_platform"],
-        "//tensorflow:using_cuda_nvcc": ["//tensorflow/stream_executor:cuda_platform"],
-        "//tensorflow:using_cuda_clang_with_dynamic_build": [],
-        "//tensorflow:using_cuda_nvcc_with_dynamic_build": [],
-        "//conditions:default": [],
+        "//conditions:default": ["//tensorflow/stream_executor:cuda_platform"],
     }) + select({
         "@local_config_cuda//cuda:darwin": ["IOKit"],
         "//conditions:default": [],
diff --git a/tensorflow/tensorflow.bzl b/tensorflow/tensorflow.bzl
index 3001a3747..2398abd34 100644
--- a/tensorflow/tensorflow.bzl
+++ b/tensorflow/tensorflow.bzl
@@ -725,12 +725,7 @@ def _cuda_copts():
 
     """
   return cuda_default_copts() + select({
-      "//conditions:default": [],
-      "@local_config_cuda//cuda:using_nvcc": ([
-          "-nvcc_options=relaxed-constexpr",
-          "-nvcc_options=ftz=true",
-      ]),
-      "@local_config_cuda//cuda:using_clang": ([
+      "//conditions:default": ([
           "-fcuda-flush-denormals-to-zero",
       ]),
   })
diff --git a/third_party/gpus/cuda/build_defs.bzl.tpl b/third_party/gpus/cuda/build_defs.bzl.tpl
index ca8bbc1ee..6d9ad452d 100644
--- a/third_party/gpus/cuda/build_defs.bzl.tpl
+++ b/third_party/gpus/cuda/build_defs.bzl.tpl
@@ -7,9 +7,7 @@ def if_cuda(if_true, if_false = []):
 
     """
     return select({
-        "@local_config_cuda//cuda:using_nvcc": if_true,
-        "@local_config_cuda//cuda:using_clang": if_true,
-        "//conditions:default": if_false
+        "//conditions:default": if_true
     })
 
 
diff --git a/third_party/toolchains/gpus/cuda/build_defs.bzl b/third_party/toolchains/gpus/cuda/build_defs.bzl
index badaf4301..1b7aac066 100644
--- a/third_party/toolchains/gpus/cuda/build_defs.bzl
+++ b/third_party/toolchains/gpus/cuda/build_defs.bzl
@@ -10,9 +10,7 @@ def if_cuda(if_true, if_false = []):
 
     """
     return select({
-        "@local_config_cuda//cuda:using_nvcc": if_true,
-        "@local_config_cuda//cuda:using_clang": if_true,
-        "//conditions:default": if_false
+        "//conditions:default": if_true
     })
```

That's a workaround, and clearly not the right way to fix it, but it does allow the build to get past this issue (and then, in my testing with `TF_CUDA_CLANG=1`, to fail in myriad other places for unrelated reasons).

**Comment by Choxmi** [comment] 2017-11-30 12:39
I faced a same type of issue in windows. I was able to solve it by changing the cpu  to `x64_windows_msys`. Hope would help somebody. :)

**Comment by tensorflowbutler** [comment] 2017-12-20 19:21
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by JavaMan7** [comment] 2017-12-31 05:43
I tried to build with opencl support and got this error 

` Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/kernels:compare_and_bitpack_op:
@local_config_sycl//sycl:using_sycl_ccpp
@local_config_sycl//sycl:using_sycl_trisycl
Multiple matches are not allowed unless one is unambiguously more specialized.INFO: Elapsed time: 1.099s, Critical Path: 0.00s
INFO: Elapsed time: 1.099s, Critical Path: 0.00s
`
what is needed to fix this

**Comment by tensorflowbutler** [comment] 2018-01-14 18:55
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment] 2018-01-21 00:58
@av8ramit, could you take a look again. The @traviscross  comment seems to indicate that we need to handle the USE_CLANG case differently to make things work.

**Comment by xshow-xs** [comment] 2018-02-06 05:58
I am seeing the same error with bazel 0.5.4
python 2.7
centos7.3
tensorflow:v1.3
cuda8.0
cudnn6.0
GTX1080

**Comment by letatanu** [comment] 2018-03-04 01:33
When you do config, just say NO to use Clang as CUDA compiler. That solved my problem.

**Comment by tycho** [comment] 2018-03-15 21:43
So I just figured out that doing `--config=cuda_clang` works, but setting environment `TF_CUDA_CLANG=1` with `--config=cuda` does not. Seems like the solution is to make the latter case work and then the 0/1 for `TF_CUDA_CLANG` could toggle using nvcc/clang.

**Comment by anilmaddala** [comment] 2018-03-27 21:41
I resolved this by not selecting clang in the nofigure step.
Just setup using default when asked for, 

> Do you want to use clang as CUDA compiler? [y/N]:

the configure script should automatically pick nvcc

**Comment by tensorflowbutler** [comment] 2018-04-11 12:37
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-26 18:52
Nagging Assignee @shivaniag: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:13
Nagging Assignee @shivaniag: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:40
Nagging Assignee @shivaniag: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:06
Nagging Assignee @shivaniag: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 18:58
Nagging Assignee @shivaniag: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:54
Nagging Assignee @shivaniag: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 12:58
Nagging Assignee @shivaniag: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:40
Nagging Assignee @shivaniag: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:35
Nagging Assignee @shivaniag: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:42
Nagging Assignee @shivaniag: It has been 179 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:43
Nagging Assignee @shivaniag: It has been 194 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-10-12 21:40
@linyia01 Hi, does issue still exist ? If so, can you please try the workaround suggested by @anilmaddala

**Comment by tensorflowbutler** [comment] 2018-10-27 12:33
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-10-31 18:11
Closing this issue due to staleness. Please use the latest version of TensorFlow and build again. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2018-10-31 18:11 UTC
Labels: type:build/install

**Comment by brentsony** [comment] 2019-03-06 20:51
What worked for me is specifying --config=cuda_clang (instead of --config=cuda).

Compiling GPU code with clang can succeed in some instances where using nvcc does not.

**Comment by aenjon** [comment] 2019-03-10 02:20
--config=cuda_clang ,sure,I have to check it out
