### ISSUE TITLE
Keras loading a saved model - ValueError: Could not find matching function to call loaded from the SavedModel

### ISSUE THREAD

**Issue by hepbc** [tensorflow/tensorflow#37973] opened 2020-03-27 14:00 UTC
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have written custom code: Yes
- OS Platform and Distribution: Windows 10 
- Mobile device: No 
- TensorFlow installed from: conda install tensorflow
- TensorFlow version: 2.1.0 (CPU only)
- Python version: 3

**Describe the current behavior**
I train a TF Keras model (summary below) and use it for slot classification and it works fine.
I then save it using: `tf.saved_model.save(joint_model, 'BERT2.tf')`
I then load the model: bertmodel = `tf.keras.models.load_model('BERT2.tf', compile=False)`
It is compiled using the same arguments as saved model.
And then try predictions using the same function as before but I getting the following error: ValueError: Could not find matching function to call loaded from the SavedModel

**Describe the expected behavior**
I run prediction using the same function but the loaded model gives the error.
I tried installing the nightly tensorflow build but was not successful.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("inputs:0", shape=(1, 8), dtype=int32)
  Keyword arguments: {'training': False}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/input_ids')}
  Keyword arguments: {'training': False}

Option 2:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='input_ids')}
  Keyword arguments: {'training': False}

Option 3:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/input_ids')}
  Keyword arguments: {'training': True}

Option 4:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='input_ids')}
  Keyword arguments: {'training': True}

```
```

**Comment by khimraj** [comment] 2020-03-28 11:57
@hepbc, please can you share full code or link of colab file to reproduce and analyse issue as above given code is not sufficient to reproduce issue.

**Comment by hepbc** [comment] 2020-03-28 13:19
Reproducing complete code here as I am not familiar with Google Colab:

```
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dropout, Dense
from transformers import BertTokenizer
# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.metrics import SparseCategoricalAccuracy
from transformers import TFBertModel
lines = pd.read_csv(r"C:\BC personal\coding\Bert example tags expanded.csv", header=0)
lines = lines.sample(frac=1)
lines
txt = lines["Text"].tolist()
text = []
for line in txt:
    text.append(line.lower())
text
tags = []
slot_map = {}
slot_names = ["[PAD]"]
slot_map["[PAD]"] = 0 
for i in range(len(lines)):
    k = ""
    for j in range(11):
#        print(i,j)
        slot = lines.iloc[i,j+1]
#        print(slot)
        if pd.isna(slot):
            break
        else:
            if slot not in slot_names:
                slot_names.append(slot)
                slot_map[slot] = len(slot_map)
            k = k + " " + str(slot)
    tags.append(k)
print(slot_names)
print(slot_map)
def encode_token_labels(text_sequences, slot_names, tokenizer, slot_map,
                        max_length):
    encoded = np.zeros(shape=(len(text_sequences), max_length), dtype=np.int32)
    for i, (text_sequence, word_labels) in enumerate(
            zip(text_sequences, slot_names)):
        encoded_labels = []
        for word, word_label in zip(text_sequence.split(), word_labels.split()):
            #print(word, word_label)
            tokens = tokenizer.tokenize(word)
            #print(tokens)
            encoded_labels.append(slot_map[word_label])
            #print(encoded_labels)
            expand_label = word_label.replace("B-", "I-")
            if not expand_label in slot_map:
                expand_label = word_label
            encoded_labels.extend([slot_map[expand_label]] * (len(tokens) - 1))
        encoded[i, 1:len(encoded_labels) + 1] = encoded_labels
        print(tokenizer.tokenize(text_sequence))
        print(encoded_labels)
    return encoded
#slot_train = encode_token_labels(text, tags, tokenizer, slot_map, 25)
slot_train = encode_token_labels(text[:75], tags, tokenizer, slot_map, 25)
slot_test = encode_token_labels(text[75:], tags, tokenizer, slot_map, 25)
def encode_dataset(tokenizer, text_sequences, max_length):
    token_ids = np.zeros(shape=(len(text_sequences), max_length),
                         dtype=np.int32)
    for i, text_sequence in enumerate(text_sequences):
        print(text_sequence)
        encoded = tokenizer.encode(text_sequence)
        #print(len(encoded))
        token_ids[i, 0:len(encoded)] = encoded
    attention_masks = (token_ids != 0).astype(np.int32)
    return {"input_ids": token_ids, "attention_masks": attention_masks}
encoded_train = encode_dataset(tokenizer, text[:75], 25)
encoded_test = encode_dataset(tokenizer, text[75:], 25)
class JointIntentAndSlotFillingModel(tf.keras.Model):
    def __init__(self, slot_num_labels=None, model_name="bert-base-uncased", dropout_prob=0.1):
        print("started init")
        super().__init__(name="joint_intent_slot")
        print(model_name)
        self.bert = TFBertModel.from_pretrained(model_name)
        print("bert")
        self.dropout = Dropout(dropout_prob)
        print("dropout")
        #self.intent_classifier = Dense(intent_num_labels,
         #                              name="intent_classifier")
        self.slot_classifier = Dense(slot_num_labels, name="slot_classifier")
        #print("init over")
    
    #@tf.function(input_signature=[None])
    def call(self, inputs, **kwargs):
        print("started call")
        sequence_output, pooled_output = self.bert(inputs, **kwargs)
        #sequence_output = self.bert(inputs, **kwargs)
        # The first output of the main 
        # and gives a "pooled" representation for the full sequence from the
        # hidden state that corresponds tBERT layer has shape:
        # (batch_size, max_length, output_dim)
        sequence_output = self.dropout(sequence_output, training=kwargs.get("training", False))
        slot_logits = self.slot_classifier(sequence_output)

        # The second output of the main BERT layer has shape:
        # (batch_size, output_dim)o the "[CLS]" token.
        pooled_output = self.dropout(pooled_output, training=kwargs.get("training", False))
        ##intent_logits = self.intent_classifier(pooled_output)

        #return slot_logits, intent_logits
        return slot_logits
print(len(slot_map))
joint_model = JointIntentAndSlotFillingModel(slot_num_labels=len(slot_map))
print("Done")
opt = Adam(learning_rate=3e-5, epsilon=1e-08)
print("Done")
losses = [SparseCategoricalCrossentropy(from_logits=True)]#, SparseCategoricalCrossentropy(from_logits=True)]
print("Done")
metrics = [SparseCategoricalAccuracy('accuracy')]
print("Done")
joint_model.compile(optimizer=opt, loss=losses, metrics=metrics)
print("Done")
history = joint_model.fit(encoded_train, slot_train, epochs=15, batch_size=32)
history = joint_model.evaluate(encoded_test, slot_test)
print(history)

```
**Output:**
```
started call
22/22 [==============================] - 34s 2s/sample - loss: 0.6699 - accuracy: 0.8800
[0.6698841452598572, 0.88]
```

joint_model.summary()

**Output:**
```
Model: "joint_intent_slot"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
tf_bert_model (TFBertModel)  multiple                  109482240 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
slot_classifier (Dense)      multiple                  19225     
=================================================================
Total params: 109,501,465
Trainable params: 109,501,465
Non-trainable params: 0
_________________________________________________________________
```

```
def show_predictions(text, tokenizer, model, slot_names):
    inputs = tf.constant(tokenizer.encode(text))[None, :]  # batch_size = 1
    print(inputs)
    outputs = model(inputs)
    slot_logits = outputs
    slot_ids = slot_logits.numpy().argmax(axis=-1)[0, 1:-1]
    print(slot_ids)
    #intent_id = intent_logits.numpy().argmax(axis=-1)[0]
    #print("## Intent:", intent_names[intent_id])
    print("## Slots:")
    for token, slot_id in zip(tokenizer.tokenize(text), slot_ids):
        print(f"{token:>10} : {slot_names[slot_id]}")
usertxt = ""
while usertxt != "Exit":
    usertxt = input()
    show_predictions(usertxt, tokenizer, joint_model, slot_names)

```
**Output - as expected:**
```
Ebitda for cement cos
tf.Tensor([[  101  1041 16313  2850  2005 11297  2522  2015   102]], shape=(1, 9), dtype=int32)
started call
[5 8 8 4 7 4 4]
## Slots:
         e : B-funda
     ##bit : I-funda
      ##da : I-funda
       for : O
    cement : B-sector
        co : O
       ##s : O
```

Works fine till here. 
**Loading and Saving:**
```
tf.saved_model.save(joint_model, 'BERT2.tf')
bertmodel = tf.keras.models.load_model('BERT2.tf', compile=False)
bertmodel.compile(loss = losses, optimizer = opt, metrics = metrics)
bertmodel.summary()
```

**Output: - same as saved model**
```
Model: "joint_intent_slot"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
tf_bert_model (TFBertModel)  multiple                  109482240 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
slot_classifier (Dense)      multiple                  19225     
=================================================================
Total params: 109,501,465
Trainable params: 109,501,465
Non-trainable params: 0
_________________________________________________________________
```
**Testing code:**
```
text = "PB vs ROE for banks"
inputs = tf.constant(tokenizer.encode(text))[None, :]  # batch_size = 1
outputs = bertmodel(inputs)
slot_logits = outputs
slot_ids = slot_logits.numpy().argmax(axis=-1)[0, 1:-1]
for token, slot_id in zip(tokenizer.tokenize(text), slot_ids):
    print(f"{token:>10} : {slot_names[slot_id]}")
```

**Output:**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-4b0bfdfc5f80> in <module>
      5 #outputs = bertmodel.predict(inputs)
      6 #print(outputs)
----> 7 outputs = bertmodel(inputs)
      8 slot_logits = outputs
      9 slot_ids = slot_logits.numpy().argmax(axis=-1)[0, 1:-1]

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py in return_outputs_and_add_losses(*args, **kwargs)
     57     inputs = args[inputs_arg_index]
     58     args = args[inputs_arg_index + 1:]
---> 59     outputs, losses = fn(inputs, *args, **kwargs)
     60     layer.add_loss(losses, inputs)
     61     return outputs

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py in wrap_with_training_arg(*args, **kwargs)
    111         training,
    112         lambda: replace_training_and_call(True),
--> 113         lambda: replace_training_and_call(False))
    114 
    115   # Create arg spec for decorated function. If 'training' is not defined in the

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py in smart_cond(pred, true_fn, false_fn, name)
     57         pred, true_fn=true_fn, false_fn=false_fn, name=name)
     58   return smart_module.smart_cond(
---> 59       pred, true_fn=true_fn, false_fn=false_fn, name=name)
     60 
     61 

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     54       return true_fn()
     55     else:
---> 56       return false_fn()
     57   else:
     58     return control_flow_ops.cond(pred, true_fn=true_fn, false_fn=false_fn,

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py in <lambda>()
    111         training,
    112         lambda: replace_training_and_call(True),
--> 113         lambda: replace_training_and_call(False))
    114 
    115   # Create arg spec for decorated function. If 'training' is not defined in the

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py in replace_training_and_call(training)
    106     def replace_training_and_call(training):
    107       set_training_arg(training, training_arg_index, args, kwargs)
--> 108       return wrapped_call(*args, **kwargs)
    109 
    110     return tf_utils.smart_cond(

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    604       # In this case we have not created variables on the first call. So we can
    605       # run the first trace but we should fail if variables are created.
--> 606       results = self._stateful_fn(*args, **kwds)
    607       if self._created_variables:
    608         raise ValueError("Creating variables on a non-first call to a function"

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2360     """Calls a graph function specialized to the inputs."""
   2361     with self._lock:
-> 2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   2701 
   2702       self._function_cache.missed.add(call_context_key)
-> 2703       graph_function = self._create_graph_function(args, kwargs)
   2704       self._function_cache.primary[cache_key] = graph_function
   2705       return graph_function, args, kwargs

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2591             arg_names=arg_names,
   2592             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2593             capture_by_value=self._capture_by_value),
   2594         self._function_attributes,
   2595         # Tell the ConcreteFunction to clean up its graph once it goes out of

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    976                                           converted_func)
    977 
--> 978       func_outputs = python_func(*func_args, **func_kwargs)
    979 
    980       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    437         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    438         # the function a weak reference to itself to avoid a reference cycle.
--> 439         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    440     weak_wrapped_fn = weakref.ref(wrapped_fn)
    441 

~\Anaconda3\lib\site-packages\tensorflow_core\python\saved_model\function_deserialization.py in restored_function_body(*args, **kwargs)
    260         .format(_pretty_format_positional(args), kwargs,
    261                 len(saved_function.concrete_functions),
--> 262                 "\n\n".join(signature_descriptions)))
    263 
    264   concrete_function_objects = []

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("inputs:0", shape=(1, 8), dtype=int32)
  Keyword arguments: {'training': False}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/input_ids')}
  Keyword arguments: {'training': False}

Option 2:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='input_ids')}
  Keyword arguments: {'training': False}

Option 3:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='inputs/input_ids')}
  Keyword arguments: {'training': True}

Option 4:
  Positional arguments (1 total):
    * {'attention_masks': TensorSpec(shape=(None, 25), dtype=tf.int32, name='attention_masks'), 'input_ids': TensorSpec(shape=(None, 25), dtype=tf.int32, name='input_ids')}
  Keyword arguments: {'training': True}

```

**Comment by khimraj** [comment] 2020-03-28 13:39
@hepbc, I have not required csv file for data. Although I suggest you to do not use `model.save()` for custom subclass keras model and use `save_weights()` and `load_weights()` instead.

**Comment by Rubix982** [comment] 2020-03-28 18:05
Hello, @hepbc !
I'm trying to recreate your code in a jupyter notebook on Google Colab - the link to that is [here](https://colab.research.google.com/drive/1oxL0S446ctgkY6UPOKZGt9U5siSYs0G3) .
Your code failed for me because it was importing a CSV file from your local computer's storage, and I don't have that. 
Can you provide any dummy data so that it will be easier to understand and help you? Thank you!

Love to hear back from you soon.

**Comment by hepbc** [comment] 2020-03-29 03:05
@khimraj Your solution works, many thanks!

@Rubix982 Thanks for all the help Saif. I changed the way I was saving and loading the model as suggested by Khimraj. Instead of model.save(), I saved the weights and then loaded the model as per guidelines in Part II-Approach 1 here: https://www.tensorflow.org/guide/keras/save_and_serialize. Seems to be working now.

**Comment by Rubix982** [comment] 2020-03-29 04:37
Fantastic! 
I haven't touched those guide before, so I didn't exactly know where the error could come. good to see it's resolved now.

**Comment by amahendrakar** [comment] 2020-03-30 12:10
>Seems to be working now.

@hepbc,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Closed** 2020-03-31 14:13 UTC
Labels: TF 2.1, comp:apis, stat:awaiting response, type:support

**Comment by meg261995** [comment] 2022-01-20 06:51
> @hepbc, I have not required csv file for data. Although I suggest you to do not use `model.save()` for custom subclass keras model and use `save_weights()` and `load_weights()` instead.

I got the same error with model.save(). Hence I used save_weights() and load_weights(). But here again there is another issue. The prediction done where the model is trained and the prediction done where the model is loaded for the same input is different. How to solve this?

**Comment by sliang11** [comment] 2022-12-09 14:06
> 

Same here. I find even without further training, the original model weights and the loaded model weights can have slight differences, and such differences can be enlarged as the training goes on. It seems to me that this has to do with type conversion. I wonder how to eliminate this effect?
