### ISSUE TITLE
Many Keras.applications (e.g. ResNet-101, ResNeXt) missing from default TensorFlow-gpu installation of 1.10 (through 1.14)

### ISSUE THREAD

**Issue by EmielBoss** [tensorflow/tensorflow#30024] opened 2019-06-21 10:28 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.10
- Python version: 3.5
- CUDA/cuDNN version: V8.0.61
- GPU model and memory: Tesla P100-PCIE, 12193MiB

A lot of the listed [Keras applications](https://keras.io/applications/) are missing from TensorFlow-gpu installations of 1.10 through 1.14. This might as well be a feature request to include those.

I installed TensorFlow 1.10 through 1.14, and all installations are missing some [Keras applications](https://keras.io/applications/), like ResNet-101, ResNext, etc. I copied the files from the [Keras applications GitHub repository](https://github.com/keras-team/keras-applications/tree/master/keras_applications), and simply pasted them in `site-packages/tensorflow/python/keras/applications/`. However, this results in the following error:

```
Traceback (most recent call last):
  File "myscript.py", line 2, in <module>
    import tensorflow as tf
  File "tensorflow/__init__.py", line 53, in <module>
    from tensorflow import keras
  File "tensorflow/keras/__init__.py", line 13, in <module>
    from tensorflow.keras import applications
  File "tensorflow/keras/applications/__init__.py", line 8, in <module>
    from tensorflow.keras.applications import densenet
  File "tensorflow/keras/applications/densenet/__init__.py", line 14, in <module>
    from tensorflow.python.keras.applications import DenseNet121
ImportError: cannot import name 'DenseNet121'
```

This led me to discover another Keras applications folder: `site-packages/tensorflow/keras/applications/`. What is the difference between the two applications folders? Why does not TensorFlow install all applications out-of-the-box? How can I use those applications anyways (preferably without installing Keras separately)?

**Comment by TomHeaven** [comment] 2019-07-17 06:18
I meet a similar error running old TF code. I'm using tensorflow 1.14.0.
```
Traceback (most recent call last):
  File "/Users/tomheaven/NutstoreFiles/我的坚果云/PycharmProjects/noise_estimation_and_denoise_pytorch/test_drne_and_dn.py", line 5, in <module>
    from tensorflow.contrib.layers import conv2d, avg_pool2d
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 35, in <module>
    from tensorflow._api.v1 import compat
  File "/Library/Python/2.7/site-packages/tensorflow/_api/v1/compat/__init__.py", line 21, in <module>
    from tensorflow._api.v1.compat import v1
  File "/Library/Python/2.7/site-packages/tensorflow/_api/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v1.compat.v1 import layers
  File "/Library/Python/2.7/site-packages/tensorflow/_api/v1/compat/v1/layers/__init__.py", line 9, in <module>
    from tensorflow.python.keras.api._v1.keras.layers import InputSpec
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/__init__.py", line 8, in <module>
    from tensorflow.python.keras.api import keras
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/keras/__init__.py", line 17, in <module>
    from tensorflow.python.keras.api.keras import applications
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/keras/applications/__init__.py", line 8, in <module>
    from tensorflow.python.keras.api._v1.keras.applications import DenseNet121
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/_v1/__init__.py", line 8, in <module>
    from tensorflow.python.keras.api._v1 import keras
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/_v1/keras/__init__.py", line 17, in <module>
    from tensorflow.python.keras.api._v1.keras import applications
  File "/Library/Python/2.7/site-packages/tensorflow/python/keras/api/_v1/keras/applications/__init__.py", line 8, in <module>
    from tensorflow.python.keras.api._v1.keras.applications import DenseNet121
ImportError: cannot import name DenseNet121

Process finished with exit code 1
```

**Comment by Saduf2019** [comment] 2020-02-06 11:27
@EmielBoss Could you please confirm if the issue is resolved.

**Comment by Saduf2019** [comment] 2020-06-30 14:05
@EmielBoss 
Could you update as per above comment.

**Comment by gowthamkpr** [comment] 2020-07-12 14:59
As this issue has already been addressed [here](https://stackoverflow.com/questions/56714015/tensorflow-keras-how-to-get-missing-models-resnet101-resnext-etc-from-kera), I am going ahead and closing this issue. Thanks!

**Closed by gowthamkpr** 2020-07-12 14:59 UTC
Labels: comp:keras, stalled, stat:awaiting response, type:support
