### ISSUE TITLE
GO Tests Fail for Tensorflow 1.4.0 but example code works on amd64 and arm64

### ISSUE THREAD

**Issue by meldron** [tensorflow/tensorflow#15306] opened 2017-12-12 10:41 UTC
### System information
- ~**Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**~:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04 on amd64 and arm64
- **TensorFlow installed from (source or binary)**: amd64: binary (https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.4.0.tar.gz); arch64: source (d752244f) `//tensorflow:libtensorflow.so`
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: python3.5
- **Bazel version (if compiling from source)**:  arm64: 0.7.0
- **GCC/Compiler version (if compiling from source)**: arm64: 5.4.0-6ubuntu1~16.04.5
- **CUDA/cuDNN version**: amd64: cuda-8.0 | libcudnn.so.6
- **GPU model and memory**: amd64: GeForce GTX 1060 6071MiB
- **Exact command to reproduce**: `go test github.com/tensorflow/tensorflow/tensorflow/go`

### Describe the problem
Test fail but [example code](https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go#example-package) work on both platforms. 

### Source code / logs
amd64:
```
2017-12-12 11:37:29.916413: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2017-12-12 11:37:29.918709: F tensorflow/core/framework/tensor.cc:822] Unexpected type: 23
SIGABRT: abort
PC=0x7f9b403b4428 m=4 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 29 [syscall, locked to thread]:
runtime.cgocall(0x657730, 0xc4200479d0, 0xc4200479f8)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200479a0 sp=0xc420047960 pc=0x405574
github.com/tensorflow/tensorflow/tensorflow/go._Cfunc_TF_SetAttrTensor(0x7f9b0800c380, 0x7f9b0800e190, 0x7f9b0800c840, 0x7f9b0800dc80)
	github.com/tensorflow/tensorflow/tensorflow/go/_test/_obj_test/_cgo_gotypes.go:919 +0x45 fp=0xc4200479d0 sp=0xc4200479a0 pc=0x52d725
github.com/tensorflow/tensorflow/tensorflow/go.setAttr.func18(0x7f9b0800c380, 0x7f9b0800e190, 0x7f9b0800c840, 0x7f9b0800dc80)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:306 +0xec fp=0xc420047a08 sp=0xc4200479d0 pc=0x539cdc
github.com/tensorflow/tensorflow/tensorflow/go.setAttr(0x7f9b0800c380, 0xc42000e0c0, 0x6f01be, 0x5, 0x6b70c0, 0xc4200ec4c0, 0x0, 0x0)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:306 +0x10f1 fp=0xc420047c00 sp=0xc420047a08 pc=0x530481
github.com/tensorflow/tensorflow/tensorflow/go.(*Graph).AddOperation(0xc42000e080, 0x6f0024, 0x5, 0xc42050a3b8, 0x6, 0x0, 0x0, 0x0, 0xc420080f00, 0x4b393b, ...)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:209 +0x4a0 fp=0xc420047d60 sp=0xc420047c00 pc=0x52f190
github.com/tensorflow/tensorflow/tensorflow/go.Const(0xc42000e080, 0xc42050a3b8, 0x6, 0x683760, 0xc4200ec300, 0xc42050a3b8, 0x6, 0x4d499d, 0x7abe18)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/util_test.go:38 +0x221 fp=0xc420047e38 sp=0xc420047d60 pc=0x52a781
github.com/tensorflow/tensorflow/tensorflow/go.TestOutputDataTypeAndShape.func1(0xc420102780)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/operation_test.go:137 +0x11e fp=0xc420047fa8 sp=0xc420047e38 pc=0x53708e
testing.tRunner(0xc420102780, 0xc4200ec480)
	/usr/local/go/src/testing/testing.go:746 +0xd0 fp=0xc420047fd0 sp=0xc420047fa8 pc=0x4d4a40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420047fd8 sp=0xc420047fd0 pc=0x45fa31
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420102000, 0x6f62b2, 0x1a, 0x703770, 0x47b401)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc420102000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc420102000, 0xc420057de0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4200ec220, 0xa423e0, 0x11, 0x11, 0xc420057e78)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420057f18, 0xc420057f70)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/tensorflow/tensorflow/tensorflow/go/_test/_testmain.go:84 +0xdb

goroutine 25 [chan receive]:
testing.(*T).Run(0xc4201023c0, 0xc4200145a0, 0x13, 0xc4200ec480, 0x2)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
github.com/tensorflow/tensorflow/tensorflow/go.TestOutputDataTypeAndShape(0xc4201023c0)
	/home/meldron/go/src/github.com/tensorflow/tensorflow/tensorflow/go/operation_test.go:136 +0x56e
testing.tRunner(0xc4201023c0, 0x703770)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

rax    0x0
rbx    0x7f9b1fbfca30
rcx    0x7f9b403b4428
rdx    0x6
rdi    0x20a0
rsi    0x20a3
rbp    0x7f9b1fbfca20
rsp    0x7f9b1fbfc8e8
r8     0x7f9b0800eb80
r9     0x0
r10    0x8
r11    0x206
r12    0x7f9b1fbfcc50
r13    0x17
r14    0x5
r15    0x7f9b1fbfcc50
rip    0x7f9b403b4428
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
FAIL	github.com/tensorflow/tensorflow/tensorflow/go	0.059s
```

arm64:
```
2017-12-12 11:40:20.357262: F tensorflow/core/framework/tensor.cc:822] Unexpected type: 23
SIGABRT: abort
PC=0x7f7a686528 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 56 [syscall, locked to thread]:
runtime.cgocall(0x5e9a48, 0x442003d9d8, 0x29)
	/usr/local/go/src/runtime/cgocall.go:132 +0xa0 fp=0x442003d9a0 sp=0x442003d960 pc=0x405280
github.com/tensorflow/tensorflow/tensorflow/go._Cfunc_TF_SetAttrTensor(0xa2bac10, 0xa24bfa0, 0x9fcbb50, 0xa289620)
	github.com/tensorflow/tensorflow/tensorflow/go/_test/_obj_test/_cgo_gotypes.go:919 +0x38 fp=0x442003d9d0 sp=0x442003d9a0 pc=0x508468
github.com/tensorflow/tensorflow/tensorflow/go.setAttr.func18(0xa2bac10, 0xa24bfa0, 0x9fcbb50, 0xa289620)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:306 +0xa4 fp=0x442003da00 sp=0x442003d9d0 pc=0x511e04
github.com/tensorflow/tensorflow/tensorflow/go.setAttr(0xa2bac10, 0x442008a0c0, 0x6809f9, 0x5, 0x648200, 0x4420106480, 0x0, 0x0)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:306 +0xd7c fp=0x442003dc00 sp=0x442003da00 pc=0x50aa3c
github.com/tensorflow/tensorflow/tensorflow/go.(*Graph).AddOperation(0x442008a088, 0x680864, 0x5, 0x4420086728, 0x6, 0x0, 0x0, 0x0, 0x442007ef00, 0x4a1f7c, ...)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/graph.go:209 +0x3b8 fp=0x442003dd60 sp=0x442003dc00 pc=0x509b38
github.com/tensorflow/tensorflow/tensorflow/go.Const(0x442008a088, 0x4420086728, 0x6, 0x615100, 0x44201062c0, 0x4420086728, 0x6, 0x445a01, 0x80)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/util_test.go:38 +0x190 fp=0x442003de30 sp=0x442003dd60 pc=0x505a90
github.com/tensorflow/tensorflow/tensorflow/go.TestOutputDataTypeAndShape.func1(0x442011e780)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/operation_test.go:137 +0xc4 fp=0x442003dfa0 sp=0x442003de30 pc=0x50fd44
testing.tRunner(0x442011e780, 0x4420106440)
	/usr/local/go/src/testing/testing.go:746 +0xb0 fp=0x442003dfc0 sp=0x442003dfa0 pc=0x4bd240
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:931 +0x4 fp=0x442003dfc0 sp=0x442003dfc0 pc=0x456a44
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x244

goroutine 1 [chan receive]:
testing.(*T).Run(0x442011e000, 0x686c26, 0x1a, 0x694188, 0x5a2fb201)
	/usr/local/go/src/testing/testing.go:790 +0x258
testing.runTests.func1(0x442011e000)
	/usr/local/go/src/testing/testing.go:1004 +0x54
testing.tRunner(0x442011e000, 0x4420051dd0)
	/usr/local/go/src/testing/testing.go:746 +0xb0
testing.runTests(0x44201061c0, 0x7d8300, 0x11, 0x11, 0x3e7)
	/usr/local/go/src/testing/testing.go:1002 +0x280
testing.(*M).Run(0x4420051f18, 0x42d01c)
	/usr/local/go/src/testing/testing.go:921 +0xf0
main.main()
	github.com/tensorflow/tensorflow/tensorflow/go/_test/_testmain.go:84 +0xd0

goroutine 52 [chan receive]:
testing.(*T).Run(0x442011e3c0, 0x44200c02c0, 0x13, 0x4420106440, 0x2)
	/usr/local/go/src/testing/testing.go:790 +0x258
github.com/tensorflow/tensorflow/tensorflow/go.TestOutputDataTypeAndShape(0x442011e3c0)
	/home/rock64/go/src/github.com/tensorflow/tensorflow/tensorflow/go/operation_test.go:136 +0x540
testing.tRunner(0x442011e3c0, 0x694188)
	/usr/local/go/src/testing/testing.go:746 +0xb0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x244

r0      0x0
r1      0x363f
r2      0x6
r3      0x7f7c729000
r4      0x363f
r5      0x7f7c7296f0
r6      0x0
r7      0x0
r8      0x83
r9      0x9fa59e0
r10     0x7fdb6f6760
r11     0x7fdb6f6760
r12     0xa3d70a3d70a3d70b
r13     0x7fdb6f6706
r14     0x0
r15     0x1db
r16     0x7f7a639120
r17     0x7f7a687830
r18     0x14
r19     0x7f7a797000
r20     0x7f7c729000
r21     0x7f7a7979d8
r22     0xa322700
r23     0x5
r24     0xa2bac10
r25     0x0
r26     0x6941e0
r27     0x10
r28     0x80b700
r29     0x7fdb6f66e0
lr      0x7f7a6879e0
sp      0x7fdb6f66e0
pc      0x7f7a686528
fault   0x0
FAIL	github.com/tensorflow/tensorflow/tensorflow/go	0.261s
```

**Comment by asimshankar** [comment] 2017-12-13 01:58
@meldron : Apologies for the error. The root cause of the error is that the Go code at head is not compatible with the release version of the C library (version 1.4.0) that you're using.

Possible fixes:

- Use the 1.4 version of the Go code, as suggested in https://github.com/tensorflow/tensorflow/issues/14546#issuecomment-347433966
- Build the C library from source
- Use the "nightly" build of the C library from: http://ci.tensorflow.org/view/Nightly/job/nightly-libtensorflow/TYPE=gpu-linux/lastSuccessfulBuild/artifact/lib_package/libtensorflow-gpu-linux-x86_64.tar.gz

Let us know if any of these work for you.

(Apologies for the trouble, we updated the Go tests in a way that they depend on new C API behavior before the official release containing those changes was made)

**Comment by tensorflowbutler** [comment] 2018-01-03 07:40
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by asimshankar** [comment] 2018-01-03 08:12
(Closing as there are suggested workarounds and the 1.5.0 release should be coming up soon too. Please feel free to reopen if the closing is unsatisfactory)

**Closed by asimshankar** 2018-01-03 08:12 UTC
Labels: stat:awaiting response
