### ISSUE TITLE
AudioSpectrogram not support batch_size mode and no fbank op 

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#22615] opened 2018-09-29 12:30 UTC
AudioSpectrogram not support audios with `batch_size` dim.

```
ValueError: Shape must be rank 2 but is rank 3 for 'AudioSpectrogram' (op: 'AudioSpectrogram') with input shapes: [32,?,1].
```

There have `Mfcc` and `Spectrogram` api but no `Fbank` api export .

**Comment by tensorflowbutler** [comment] 2018-09-30 00:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by zh794390558** [comment] 2018-09-30 02:17
OS Platform and Distribution
centos 7

TensorFlow installed from
source

TensorFlow version
tf.VERSION = 1.9.0
tf.GIT_VERSION = v1.9.0-0-g25c197e023
tf.COMPILER_VERSION = v1.9.0-0-g25c197e023

Bazel version

CUDA/cuDNN version
cuda 9.0
GPU model and memory
N/A
Exact command to reproduce
N/A
Mobile device
N/A

**Comment by gunan** [comment] 2018-10-16 17:41
Looks like @petewarden added this OP.

**Comment by zh794390558** [comment] 2018-10-17 09:04
@gunan  Does not find `melfbank_op` in `core/kernels`.  And there is also no introduction about audio_ops in c++ API.

**Comment by tensorflowbutler** [comment] 2018-11-01 12:47
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:55
Nagging Assignee @petewarden: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2019-02-23 00:06
Since this is a feature request that we aren't likely to get to soon, closing for now.

**Closed by petewarden** 2019-02-23 00:06 UTC
Labels: stat:awaiting tensorflower
