### ISSUE TITLE
Features: train.saver  namescoped-restoring

### ISSUE THREAD

**Issue by Jylomaki** [tensorflow/tensorflow#21402] opened 2018-08-06 10:01 UTC
Hello:

Scenario of need:
Joe the ML-engineer wants a model that predict multiple thing out of a single img (lets say object detection & some environment values: hour of day, type of surroundings: inside/outside/forest/stadium/etc).
So Joe train a model to get its object detected.
Then Joe train a model to get its environment data.
And now, Joe want a model that does both in a single prediction.
But Joe may want to have a clean **modulated model** (for scalable/maintainable purposes)

Scenario of usage:
Joe create its model of object detection using the same function he used for first creating it, but in a name scope.
Joe then use the `saver` to restore his checkpoint, adding the name scope as parameter to indicate that his variables are now contained in a name_scope thus their name has changed.
Then the same for the environment model.

This feature need was inspired by this issue: 
[make-predictions-with-an-old-model-without-losing-the-current-model](https://stackoverflow.com/questions/51654259/make-predictions-with-an-old-model-without-losing-the-current-model/51654678?noredirect=1#comment90301946_51654678)

Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Mobile device: N/A

**Comment by tensorflowbutler** [comment] 2018-08-06 18:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Jylomaki** [comment] 2018-08-09 09:45
filled the field even though it's not technically and issue, and more of a feature request/proposition

**Comment by tensorflowbutler** [comment] 2018-08-24 21:54
Nagging Assignee @bignamehyp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:46
Nagging Assignee @bignamehyp: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:51
Nagging Assignee @bignamehyp: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-09-28 22:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-09-28 22:17 UTC
