### ISSUE TITLE
LSTMStateTuple without get_shape() method

### ISSUE THREAD

**Issue by kangxin** [tensorflow/tensorflow#3056] opened 2016-06-27 01:17 UTC
I have a problem when building seq2seq model with attention based on the LSTM cell, using TensorFlow r0.9 on OS X.

I find that the LSTMCell generates a LSTMStateTuple state if the state_is_tuple parameter is set to True (the rnn_cell.py code seems to encourage this setting). But when I feed the output to an attention_decoder as the initial_state, the attention() function in seq2seq.py calls the _linear() function in rnn_cell.py, and _linear() calls the get_shape() function of the initial_state variable, and the program reports "AttributeError: 'LSTMStateTuple' object has no attribute 'get_shape'". 

Could you please help me find if I am missing some important steps in building seq2seq with attention based on the LSTM cell, or should LSTMStateTuple support the get_shape() function?

(The error does not appear when I set state_is_tuple=False.)

Thank you!

**Comment by ebrevdo** [comment] 2016-06-27 04:40
@lukaszkaiser any plans to update seq2seq to support state tuples?

**Comment by lukaszkaiser** [comment] 2016-07-12 21:46
This has been resolved in a CL a few days ago.

**Comment by kangxin** [comment] 2016-08-02 01:25
@lukaszkaiser Thank you very much for resolving the problem. However, my program still reports the same error when I set state_is_tuple=True. 

I have pip-installed the latest tensorflow-0.10.0rc0 with GPU on a linux system.

I do not know the meaning of "CL" in your post. Maybe I am missing some important factor here.

**Comment by lukaszkaiser** [comment] 2016-08-02 02:13
Sorry, by CL I meant PR. It should be fixed in 0.10, so if it's not working for you, let's take a look. Could you write a small example model that shows the problem and paste it here, so I can confirm? That would be great, thanks!

**Comment by kangxin** [comment] 2016-08-02 04:23
@lukaszkaiser Thank you for quick response. Please find the code in attachment. 
The program does not report error until I set `state_is_tuple=True`.
[lstm_state_is_tuple.py.zip](https://github.com/tensorflow/tensorflow/files/395233/lstm_state_is_tuple.py.zip)

**Comment by lukaszkaiser** [comment] 2016-08-02 18:39
I can replicate the problem now, working on a fix. Thanks!

**Closed** 2016-08-05 05:19 UTC

**Comment by lukaszkaiser** [comment] 2016-08-05 21:41
Hope the above PR fixed it. Let me know if any problems are still there, of course!

**Comment by zzjin13** [comment] 2016-09-08 03:25
I have the same problem and I'm using the latest tensorflow-0.10.0. Anyone has some ideas about how to solve it?

**Comment by lukaszkaiser** [comment] 2016-09-08 16:51
I'm not sure the PR that fixed it made into 0.10.0. Could you try with the head TF from github?

**Comment by ebrevdo** [comment] 2016-09-09 00:03
Yes- likely to be at head.

**Comment by zzjin13** [comment] 2016-09-09 08:56
This problem is solved now. But another error ocurrs: "tensorflow.python.framework.errors.InternalError: Dst tensor is not initialized."

I assume this problem may be related to running out of memory, so I set the batch size to 1. The problem still exist.

**Comment by lukaszkaiser** [comment] 2016-09-09 16:11
It's important to know how large is your model and how long you're unfolding it. Does it work with a smaller model (say 32 units in a cell)? How much GPU memory do you have? That'd make it clear if it's about memory. Unluckily the seq2seq library does static unrolling -- dynamic_rnn and while_loop do dynamic unrolling and can use CPU memory, so they're much better in terms of practical memory use. But we'll need to write a new seq2seq library to use them.

**Comment by zzjin13** [comment] 2016-09-10 02:31
In fact, I run the embedding_rnn_seq2seq model with the same hyper-parameters before. It works well with my GPU. However, when I switch to embedding_attention_seq2seq model, it cannot work even if I set the batch size to 1 (128 before) and RNN hidden state dimension to 1 (256 before). So I think this is not a issue related with memory. Any other factors may cause this problem?

**Comment by lukaszkaiser** [comment] 2016-09-10 03:39
Looks like a bug -- please, let us know when you dig some more information. The seq2seq code didn't change much with state_is_tuple, so it's very strange what you're seeing.

**Comment by ebrevdo** [comment] 2016-09-10 05:36
This does indeed sound like a bug, perhaps with the while_loop.  Can you
provide a minimal failing example?

**Comment by zzjin13** [comment] 2016-09-13 03:17
@lukaszkaiser @ebrevdo  Thanks for your response. The code is in the attachment. 
 When I call the train_batch function, it returns a error.

[test.txt](https://github.com/tensorflow/tensorflow/files/468799/test.txt)

**Comment by chiragjn** [comment] 2017-01-17 11:29
```# Running with tensorflow (0.12.1)
import tensorflow as tf
from tensorflow.python.ops import rnn
from tensorflow.python.ops import rnn_cell

batch_size = 100
size = 20
num_encoder_symbols = 30
embedding_size = 64
state_is_tuple = True
num_layers = 3
encoder_inputs = [tf.zeros([32],dtype=tf.int32) for _ in range(batch_size)]
single_cell = tf.nn.rnn_cell.BasicLSTMCell(size, state_is_tuple=state_is_tuple) # Or GRU
cell = tf.nn.rnn_cell.MultiRNNCell([single_cell] * num_layers)
encoder_cell = rnn_cell.EmbeddingWrapper(cell, embedding_classes=num_encoder_symbols, embedding_size=embedding_size)
_, encoder_state = rnn.rnn(encoder_cell, encoder_inputs, dtype=tf.float32)
encoder_state[0].get_shape()
```

`encoder_state` is a tuple of `LSTMStateTuple` of size `num_layers`

Calling `encoder_state[0].get_shape()` fails with ` 'LSTMStateTuple' object has no attribute 'get_shape'`

For now `encoder_state[0].c.get_shape()` , `encoder_state[0].h.get_shape()` is the only way I know to work around this

**Comment by ebrevdo** [comment] 2017-01-17 16:02
That's right, a tuple may contain multiple tensors, each of which may have
different shapes.  Thus you must call .get_shape() on whichever tensor you
care about.  You can use encoder_state[0][0].get_shape() which is
equivalent to encoder_state[0].c.get_shape().

We may add a get_shape() or shape property to LSTMStateTuple, feel free to
open a new issue for that.

**Comment by louisway** [comment] 2018-01-30 12:13
Hey, guys, any update for the shape property?
