### ISSUE TITLE
Why `tf.reshape` function tries to evaluate the `shape` argument?

### ISSUE THREAD

**Issue by Arsenal591** [tensorflow/tensorflow#28341] opened 2019-05-02 17:22 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem
When feeding images to a deep network, normally I resize all images to a fixed size (512*512 for example). So
there might be a tensor `input:0` of shape `(32, 512, 512, 3)`. Afterwards, I resize the tensor to shape `(N*H,W,C)`, i.e., `(32*512, 512, 3)`. To do this, I should write something like
```
shape = tf.shape(inputs)
reshaped = tf.reshape(inputs, (shape[0]*shape[1], shape[2], shape[3])) # Now the tensor has a known shape: (32*512, 512, 3)
```

Now, suppose the network is trained and I would like to make predictions. But note that during test time, the shape of data we want to feed into `input:0` might not be `(32, 512, 512, 3)`, since the batch size might vary(if we test images one by one, the batch size is 1) or the height/width might vary(if we do not want to resize images). So if I use `tf.import_graph_def()` to restore the graph and feed a image of a different size, the shape will be mismatched.

The main reason here might be invoking `tf.reshape` function, it will try to evaluate the `shape` argument, and since tensor `input:0` is of a fixed shape, the `shape` argument is easily evaluated, so the `reshaped` tensor is also of a fixed shape. If the function does not try to evaluate the `shape`, the target shape will be determined after the image is fed into the network, so everything will work fine.

So I would like to know why `tf.reshape` function tries to evaluate the `shape` argument. Is it a feature or not? If it is a feature, what should I do to fix the shape mismatch problem? Of course I can use the `input_map` argument in `tf.import_graph_def()` to change the shape of `input:0`, but it will not affect the shape of `reshape:0`.

**Comment by achandraa** [comment] 2019-05-07 08:32
Will it possible for you to give us some more info on the issue as for example a minimal reproducible code snippet that can depict the case. Thanks!

**Comment by achandraa** [comment] 2019-05-08 06:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-08 06:50 UTC
Labels: comp:ops, stat:awaiting response, type:support
