### ISSUE TITLE
image_retraining example is extremely slow when cropping/rotating

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#2669] opened 2016-06-05 12:16 UTC
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN 4
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

$ ls -l /usr/local/cuda/lib64/
total 987720
-rw-r--r-- 1 root root  28585480 Aug 15  2015 libcublas_device.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcublas.so -> libcublas.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcublas.so.7.5 -> libcublas.so.7.5.18
-rwxr-xr-x 1 root root  23938736 Aug 15  2015 libcublas.so.7.5.18
-rw-r--r-- 1 root root  28220076 Aug 15  2015 libcublas_static.a
-rw-r--r-- 1 root root    322936 Aug 15  2015 libcudadevrt.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root    383336 Aug 15  2015 libcudart.so.7.5.18
-rw-r--r-- 1 root root    720192 Aug 15  2015 libcudart_static.a
-rwxr-xr-x 1 root root  61453024 Jun  3 17:11 libcudnn.so
-rwxr-xr-x 1 root root  61453024 Jun  3 17:11 libcudnn.so.4
-rwxr-xr-x 1 root root  61453024 Jun  3 17:11 libcudnn.so.4.0.7
-rw-r--r-- 1 root root  62025862 Jun  3 17:11 libcudnn_static.a
lrwxrwxrwx 1 root root        15 Aug 15  2015 libcufft.so -> libcufft.so.7.5
lrwxrwxrwx 1 root root        18 Aug 15  2015 libcufft.so.7.5 -> libcufft.so.7.5.18
-rwxr-xr-x 1 root root 111231960 Aug 15  2015 libcufft.so.7.5.18
-rw-r--r-- 1 root root 115104400 Aug 15  2015 libcufft_static.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcufftw.so -> libcufftw.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcufftw.so.7.5 -> libcufftw.so.7.5.18
-rwxr-xr-x 1 root root    447664 Aug 15  2015 libcufftw.so.7.5.18
-rw-r--r-- 1 root root     42206 Aug 15  2015 libcufftw_static.a
lrwxrwxrwx 1 root root        17 Aug 15  2015 libcuinj64.so -> libcuinj64.so.7.5
lrwxrwxrwx 1 root root        20 Aug 15  2015 libcuinj64.so.7.5 -> libcuinj64.so.7.5.18
-rwxr-xr-x 1 root root   5751400 Aug 15  2015 libcuinj64.so.7.5.18
-rw-r--r-- 1 root root   1649726 Aug 15  2015 libculibos.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libcurand.so -> libcurand.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 libcurand.so.7.5 -> libcurand.so.7.5.18
-rwxr-xr-x 1 root root  51765952 Aug 15  2015 libcurand.so.7.5.18
-rw-r--r-- 1 root root  51992564 Aug 15  2015 libcurand_static.a
lrwxrwxrwx 1 root root        18 Aug 15  2015 libcusolver.so -> libcusolver.so.7.5
lrwxrwxrwx 1 root root        21 Aug 15  2015 libcusolver.so.7.5 -> libcusolver.so.7.5.18
-rwxr-xr-x 1 root root  37034328 Aug 15  2015 libcusolver.so.7.5.18
-rw-r--r-- 1 root root  16613348 Aug 15  2015 libcusolver_static.a
lrwxrwxrwx 1 root root        18 Aug 15  2015 libcusparse.so -> libcusparse.so.7.5
lrwxrwxrwx 1 root root        21 Aug 15  2015 libcusparse.so.7.5 -> libcusparse.so.7.5.18
-rwxr-xr-x 1 root root  36816424 Aug 15  2015 libcusparse.so.7.5.18
-rw-r--r-- 1 root root  44445334 Aug 15  2015 libcusparse_static.a
lrwxrwxrwx 1 root root        14 Aug 15  2015 libnppc.so -> libnppc.so.7.5
lrwxrwxrwx 1 root root        17 Aug 15  2015 libnppc.so.7.5 -> libnppc.so.7.5.18
-rwxr-xr-x 1 root root    427168 Aug 15  2015 libnppc.so.7.5.18
-rw-r--r-- 1 root root     20664 Aug 15  2015 libnppc_static.a
lrwxrwxrwx 1 root root        14 Aug 15  2015 libnppi.so -> libnppi.so.7.5
lrwxrwxrwx 1 root root        17 Aug 15  2015 libnppi.so.7.5 -> libnppi.so.7.5.18
-rwxr-xr-x 1 root root  63516808 Aug 15  2015 libnppi.so.7.5.18
-rw-r--r-- 1 root root  90106200 Aug 15  2015 libnppi_static.a
lrwxrwxrwx 1 root root        14 Aug 15  2015 libnpps.so -> libnpps.so.7.5
lrwxrwxrwx 1 root root        17 Aug 15  2015 libnpps.so.7.5 -> libnpps.so.7.5.18
-rwxr-xr-x 1 root root   6047400 Aug 15  2015 libnpps.so.7.5.18
-rw-r--r-- 1 root root   8647292 Aug 15  2015 libnpps_static.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 libnvblas.so -> libnvblas.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 libnvblas.so.7.5 -> libnvblas.so.7.5.18
-rwxr-xr-x 1 root root    456112 Aug 15  2015 libnvblas.so.7.5.18
lrwxrwxrwx 1 root root        24 Aug 15  2015 libnvrtc-builtins.so -> libnvrtc-builtins.so.7.5
lrwxrwxrwx 1 root root        27 Aug 15  2015 libnvrtc-builtins.so.7.5 -> libnvrtc-builtins.so.7.5.18
-rwxr-xr-x 1 root root  22408512 Aug 15  2015 libnvrtc-builtins.so.7.5.18
lrwxrwxrwx 1 root root        15 Aug 15  2015 libnvrtc.so -> libnvrtc.so.7.5
lrwxrwxrwx 1 root root        18 Aug 15  2015 libnvrtc.so.7.5 -> libnvrtc.so.7.5.17
-rwxr-xr-x 1 root root  18199288 Aug 15  2015 libnvrtc.so.7.5.17
lrwxrwxrwx 1 root root        18 Aug 15  2015 libnvToolsExt.so -> libnvToolsExt.so.1
lrwxrwxrwx 1 root root        22 Aug 15  2015 libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
-rwxr-xr-x 1 root root     37936 Aug 15  2015 libnvToolsExt.so.1.0.0
-rw-r--r-- 1 root root     25840 Aug 15  2015 libOpenCL.so
drwxr-xr-x 2 root root      4096 Jun  3 13:47 stubs

If installed from binary pip package, provide:

1. Which pip package you installed. Linux x64 w/ GPU support
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

0.8.0

### Steps to reproduce

I've been running the image_retrain example from Jupyter like so:

FLAGS._parse_flags()
FLAGS.image_dir = '/data/corpus'
FLAGS.output_graph = '/data/output_graph4.pb'
FLAGS.output_labels = '/data/output_labels4.txt'
FLAGS.bottleneck_dir = '/data/bottleneck/'
FLAGS.model_dir = '/data/imagenet/'
#FLAGS.flip_left_right = True
FLAGS.random_crop = 5
FLAGS.random_scale = 5
FLAGS.random_brightness = 5

main('')

When I run it without any of the crop/scale options, it runs pretty quickly on my AWS instance; creating the bottlneck images takes under an hour and the training takes minutes for 4k steps.

When I specify those flags, it took on the order of 13 hours to complete when I had ~9k images.

Obviously it has to do more work, but needing to do more than 13x the work to transform 15% of my images seems wrong.

**Comment by girving** [comment] 2016-06-07 18:18
@petewarden: Can you take a look at this?

**Comment by petewarden** [comment] 2016-06-07 21:22
Unfortunately this is expected behavior. All of the images are being transformed, the percentage values are for the amount of cropping, etc, not how many images are being affected. This means the original images can't be cached at the bottleneck stage as they are without transformations applied, so running each training step is a lot more expensive. I recommend switching to GPUs once you have heavier duty training needs like this.

Closing since this is working as intended.

**Closed by petewarden** 2016-06-07 21:22 UTC
Labels: triaged

**Comment by trinity77** [comment] 2016-09-10 05:38
Trigger update_date
