### ISSUE TITLE
Symlink loop FATAL error

### ISSUE THREAD

**Issue by evangello** [tensorflow/tensorflow#6878] opened 2017-01-16 14:13 UTC
Hello all,
I started teaching myself some tensor flow, and i faced a problem when trying to retrain an existing image classification model with a new class following that tutorial:
https://www.tensorflow.org/how_tos/image_retraining/

Since i installed tensorflow through pip and after reading a few issues, i had to download and install tensorflow from the source. when i got to configuring the install (calling ./configure) it gave me the following error:

```
____Loading package: tensorflow/contrib/lookup
____Loading package: tensorflow/java/src/main/native
____Loading package: tensorflow/tools/quantization
____Loading package: tensorflow/compiler/aot
____Loading package: tensorflow/core
____Loading package: tensorflow/contrib/quantization
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 1,508,324 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,342,484 bytes
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages/tensorflow/util/python/python_lib
[end of symlink chain]
```

Is there any particular way i can resolve this? I would really appreciate any input on the matter.

Thanks!

**Comment by asimshankar** [comment] 2017-01-16 17:30
@evangello : Could you elaborate on your setup (ideally all the information asked for in the new issue template including OS, OS version, steps to reproduce etc.)? Without that, it is a bit a hard to figure out the problem since it isn't common in other setups.

**Comment by evangello** [comment] 2017-01-17 09:33
Hello @asimshankar, thanks for your reply. Im working on a mac El Capitan. I am running "./configure" in the main tensorflow directory and putting "n" to all the prompts except for when it prompts me about the location of the python bin.

**Comment by asimshankar** [comment] 2017-01-17 17:48
This seems like an issue with the location of the custom Python bin you are providing, possibly some issue with how Python is installed with homebrew.

Since this seems like a custom setup, I'm going to close the issue here and suggest that you try [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) for support as we try to keep the github issues focused on bugs and feature requests.

If I misunderstood (and this is a bug on our end) please feel free to reopen or file a new issue

**Closed by asimshankar** 2017-01-17 17:48 UTC
