### ISSUE TITLE
How to limit the cpu core number in Tensorflow 2.0

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#34415] opened 2019-11-19 12:21 UTC
I am using tf.keras to train a model with cpu and I want to limit the cpu usage of this program. I found this article(https://www.kaggle.com/c/porto-seguro-safe-driver-prediction/discussion/43383):

```
from keras import backend as K
import tensorflow as tf

config = tf.ConfigProto(intra_op_parallelism_threads=args.jobs, \ 
                        inter_op_parallelism_threads=args.jobs, \
                        allow_soft_placement=True, \
                        device_count = {'CPU': args.jobs})
session = tf.Session(config=config)
K.set_session(session)
```

But in Tensorflow 2.0, ConfigProto is deprecated and Session is gone. What's the correct method to limit cpu usage?

**Comment by Leslie-Fang** [comment] 2019-11-19 13:49
```
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(112)
```
Have a try of this setting @fancyerii ?

**Comment by gadagashwini** [comment] 2019-11-20 06:01
@fancyerii, Please take a look at this [link](https://www.tensorflow.org/api_docs/python/tf/config/threading). Thanks!

**Comment by benni93** [comment] 2019-11-30 13:44
I tried 
```
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)
```
using `tensorflow.keras`. It doesn't work on Windows 10, Windows 10 WSL and Ubuntu. On Ubuntu and WSL it uses all CPUs, no matter the number I set. On Windows 10 it seems to regulate something, but not exactly the number of CPUs. And what is the difference between intra and inter op?

**Comment by gadagashwini** [comment] 2019-12-02 11:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by benni93** [comment] 2019-12-03 11:18
#29968

**Comment by benni93** [comment] 2019-12-03 11:19
It's apparently a bug discussed in #29968

**Comment by mayou36** [comment] 2020-01-05 09:24
@benni93 on the difference between intra and inter op, may have a look at this [StackOverflow answer](https://stackoverflow.com/a/41233901/4360557).

**Comment by yuviabhi** [comment] 2020-01-09 10:40
This issue still persists. Please **Re-Open** this issue.

https://github.com/tensorflow/tensorflow/issues/29968#issuecomment-572492815

**Comment by mr-haseeb** [comment] 2020-03-28 18:01
# Tensorflow 2.0 :headphones: :1st_place_medal:  
```from tensorflow.compat.v1.keras import backend as K
config = tf.compat.v1.ConfigProto(device_count={"CPU": 2})
K.set_session(tf.compat.v1.Session(config=config))

**Comment by sushreebarsa** [comment] 2021-05-29 18:27
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c20f28f27cfe7e5624d55f9c8bef16a8/untitled84.ipynb)..Thanks !

**Comment by sushreebarsa** [comment] 2021-06-14 18:29
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/74cd676f801692042889258380ba8c54/untitled247.ipynb) ..Thanks!

**Comment by tonkolviktor** [comment] 2021-08-09 15:50
hello all,

for me it seems to work with: 
```
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)
```
using CentOs and tensorflow 2.5.0 and python 3.6.

I think one crucial factor is finding a commonly agreed way of testing this. I was using: `htop -p <pid>` and I was validating that without the settings I've got >100% CPU usage and with the settings <=100%, which was my goal, albeit I agree that this test might not be the most sophisticated one :)

In https://github.com/tensorflow/tensorflow/issues/29968, it's discussed that there are many threads and context switches. Which I can confirm, however for my use-case was not relevant and from the CPU utilization point of view - I think - is irrelevant. 
If there are 100 threads but only one is running or ~1core can serve all active threads, I'm fine.

@sushreebarsa both of your notebooks have syntax error which is independent of tensorflow. At the same time it does not really matter, because what you try to do is anyhow not supported in tensorflow 2, session is not really supported anymore: https://www.tensorflow.org/guide/effective_tf2#functions_not_sessions

**Comment by olifre** [comment] 2021-08-16 16:55
> In #29968, it's discussed that there are many threads and context switches. Which I can confirm, however for my use-case was not relevant and from the CPU utilization point of view - I think - is irrelevant.

Many threads and context switches cause cache trashing and inefficiencies, i.e. 100 % CPU load does not translate into 100 % efficient CPU use. You can analyze this further with performance analysis tools such as `perf` to estimate how much actual CPU cycles are used and how many are lost due to the threading overhead.

**Comment by mbalsells** [comment] 2021-08-31 12:43
I had the same problem. Make sure the first lines in your code are:

```
import os
os.environ["OMP_NUM_THREADS"] = "1"
```

And then import everything else. If you import tensorflow or even numpy before that, it won't work. Hope that solves the issue!

**Comment by kumariko** [comment] 2021-10-04 07:14
@fancyerii please refer to the above comment https://github.com/tensorflow/tensorflow/issues/34415#issuecomment-909201783 and let us know if you still need any help here. If it is resolved then please feel free to move this issue to close status ? Thanks!

**Closed** 2021-10-18 07:51 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:runtime, TF 2.5

**Comment by alexpyattaev** [comment] 2021-11-05 13:03
Seems TF2 still does not respect these options for simple linear algebra tasks. For example, 
```
inputA = tf.random.uniform([batch_size, problem_size, problem_size])
output = tf.linalg.inv(
            inputA, adjoint=False, name=None
        )
output = tf.reduce_sum(output)
```
would still use all cores it can find no matter what is set in config.
It seems the only thing that actually works as intended is 
```
os.environ["OMP_NUM_THREADS"] = f"{N}"
os.environ['TF_NUM_INTEROP_THREADS'] = f"{N}"
os.environ['TF_NUM_INTRAOP_THREADS'] = f"{N}"
```

Maybe would be nice if programmatic change would work too, starting new processes not always convenient.

**Comment by gangcai** [comment] 2022-01-19 09:31
Tried above solutions, still all cores were used by Tensorflow.

**Comment by kartoffelbaerig** [comment] 2023-07-12 13:05
This is still an issue in 2023. Neither the os.environ setting nor the Tensorflow config settings work.
