### ISSUE TITLE
gpu_options doesn't work

### ISSUE THREAD

**Issue by eustomaqua** [tensorflow/tensorflow#32814] opened 2019-09-25 14:22 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 16.04, Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **pip install way**
- TensorFlow version (use command below): 
        **pip install tensorflow-gpu==1.12.\* and 
        pip install tensorflow-gpu==1.14.\***
- Python version: **python 3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **tf1.12 with cuda9, tf1.14 with cuda10**
- GPU model and memory: **ubuntu 16.04 with 12G, ubuntu 18.04 with 24G**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I used the codes in AdaNet like
```python
GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
sess = tf.Session(config = CONFIG)
```
But it still occupied the whole gpu memory when I run the AdaNet. For example: 
(1) If there is only 4G memory left, it will occupied the remaining 6G memory
(2) If there is no other process occupying the GPU memory (i.e., there is 10G memory left), it will occupied the whole 10G memory when I run the AdaNet. 
So I think it doesn't need 10G to run but it takes that much any way.

**Describe the expected behavior**
I expect it only takes the memory it needs, instead of taking all of them. Therefore, I could make use of the 10G GPU memory better. 
But now, I have no idea how to fix this issue. Could anybody please give me some suggestions? Thanks a lot.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
I used the codes there [AdaNet](https://github.com/tensorflow/adanet) and change all "tf.Session()" to "tf.Session(config=CONFIG)" with codes as I mentioned before.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-09-26 17:25
You need to put the gpu configuration on top of your code.
```python
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
# Your model
  . . .
  . . .
```
Can you please confirm if this was the case? Thanks!

**Comment by eustomaqua** [comment] 2019-09-27 01:04
> You need to put the gpu configuration on top of your code.
> 
> ```python
> import tensorflow as tf
> config = tf.ConfigProto()
> config.gpu_options.allow_growth=True
> sess = tf.Session(config=config)
> # Your model
>   . . .
>   . . .
> ```
> 
> Can you please confirm if this was the case? Also can you please point me to example you tried?Thanks!

Yes, that's exactly what I did. Didn't work

**Comment by eustomaqua** [comment] 2019-09-27 01:22
The codes I used is here [AdaNet](https://github.com/tensorflow/adanet), to be specific, the codes I got by "pip install adanet==0.5.0". Since AdaNet has been updated, AdaNet 0.5.0 will have some differences, compared with [AdaNet](https://github.com/tensorflow/adanet). 

Besides, I changed all the original "sess = tf.Session()" inside to "config, ... , sess=tf.Session()". The files involving "tf.Session()" are "core/ensemble.py", "core/estimator.py", and "subnetwork/generator.py". 

I put codes as follows in the beginning of each file, like:
```python 
from __future__ import ...
import ...

GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)

def ....
class ...

    with tf.Session(config=CONFIG) as sess:
        # codes
```

Another way is 
```python
from __future__ import ...
import ...

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

...
with tf.Session(config=config) as sess:
    ...
```

I tried both and none of them worked. If there is still ambiguity, please tell me to be specific. Thank you so much for help!

**Comment by eustomaqua** [comment] 2019-09-27 01:37
As for the examples I tried, it refers to [A Simple Example using AdaNet](https://github.com/tensorflow/adanet/blob/master/adanet/examples/tutorials/customizing_adanet.ipynb)  

Please modify some of them as follows:
```python
from core_estimator import Estimator as MyEstimator  # I did some modification based on AdaNet
from core_evaluator import Evaluator as MyEvaluator   # I did some modification based on AdaNet
...
ADANET_ITERATIONS = 7  ##@param {type: "integer"}
max_iteration_steps = TRAIN_STEPS // ADANET_ITERATIONS

estimator = MyEstimator(
            head=head, 
            subnetwork_generator=my_simple_dnn.Generator(
                feature_columns=feature_columns, 
                optimizer=tf.train.RMSPropOptimizer(learning_rate=LEARNING_RATE), 
                seed=RANDOM_SEED), 
            max_iteration_steps=temp_stp, 
            evaluator=adanet.Evaluator(input_fn=eval_input_fn, steps=None), 
            config=make_config(this_experiment))

```

**Comment by zhangqinghao0811** [comment] 2019-09-30 09:15
It doesn't work for me either, have you found the solution?

**Comment by eustomaqua** [comment] 2019-10-07 16:07
> It doesn't work for me either, have you found the solution?

Nope. If I did, I wouldn't open this issue

**Comment by aaroey** [comment] 2019-10-08 04:32
I cannot reproduce this issue with 1.15.0rc2. Here is what I did:
```
$ pip install tensorflow-gpu==1.15.0rc2
$ python
>>> import tensorflow as tf
>>> GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
>>> CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
>>> sess = tf.Session(config = CONFIG)
```

I'm using a Titan-V GPU. After running the above command, only 319MiB out of 12066MiB is used based on nvidia-smi.

Could you try with the above commands?

**Comment by eustomaqua** [comment] 2019-10-08 05:25
**Did you use the AdaNet codes that I mentioned before? This issue happens when I use AdaNet models**, involving some modifications of course, but I think all you need to modify is those related to "sess = tf.Session()", by replacing them with "sess = tf.Session(config=config)". I will explain that in detail in the following. 

To be clear, I get the AdaNet codes by "**pip install adanet==0.5.0**". Then I **changed all the original "sess = tf.Session()" inside to "config, ..., sess=tf.Session()"**. The files **involving "tf.Session()"** are **"core/ensemble.py", "core/estimator.py", and "subnetwork/generator.py"**.   
I put codes as follows at the beginning of each file, like:
```python
from __future__ import ...
import ...

# the first method
GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
# the second method
# config = tf.ConfigProto()
# config.gpu_options.allow_growth = True

def ....
class ...

    with tf.Session(config=CONFIG) as sess:
        # codes
```

For your convenience, after modifying those "sess = tf.Session(config=config)", **this issue could be reproduced by using examples, which could refer to** [A Simple Example using AdaNet](https://github.com/tensorflow/adanet/blob/master/adanet/examples/tutorials/customizing_adanet.ipynb). **Please note that the "MyEstimator, MyEvaluator" should be imported from the codes that you just modified**, instead of 
```python
from adanet import Estimator
from adanet import Evaluator
```
. Please modify some of them as follows:
```python
# Please import MyEstimator, MyEvaluator from the codes you just modified
# It may differ from the following three lines that I wrote
from core_estimator import Estimator as MyEstimator  # I did some modifications based on AdaNet
from core_evaluator import Evaluator as MyEvaluator   # I did some modifications based on AdaNet
import examples_simple_dnn as mine_simple_dnn     # I did some modifications based on AdaNet
...
ADANET_ITERATIONS = 7  ##@param {type: "integer"}
max_iteration_steps = TRAIN_STEPS // ADANET_ITERATIONS

estimator = MyEstimator(
            head=head, 
            subnetwork_generator=my_simple_dnn.Generator(
                feature_columns=feature_columns, 
                optimizer=tf.train.RMSPropOptimizer(learning_rate=LEARNING_RATE), 
                seed=RANDOM_SEED), 
            max_iteration_steps=temp_stp, 
            evaluator=MyEvaluator(input_fn=eval_input_fn, steps=None), 
            config=make_config(this_experiment))
```

Besides, I'm using a TITAN RTX on Ubuntu 18.04 and a GTX 1080 Ti on Ubuntu 16.04. Other details could refer to the beginning of this issue. Therefore, I don't think "TITAN RTX / GTX 1080 Ti / Titan-V GPU" is the problem.

Thanks for helping me.

**Comment by zhangqinghao0811** [comment] 2019-10-08 06:45
It's strange,  I found that only the "allow_growth" option doesn't work, others work well.
If I add use this config in my code:

`tf_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))
tf_config.gpu_options.allow_growth = True
tf_config.gpu_options.per_process_gpu_memory_fraction = 0.05`

The program will only use 5% gpu memory, and report this message:
`Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.04GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`

And the program couldn't run if I allocate less memory.
So the program can't automatic allocate memory as the option "allow_growth" doesn't work.

**Comment by aaroey** [comment] 2019-10-08 20:35
I'm not familiar with adanet, but as another quick test, can you try running these
```
import tensorflow as tf
GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
sess = tf.Session(config = CONFIG)
# <-- sleep and measure the mem usage here
```
before importing anything from adanet?

**Comment by eustomaqua** [comment] 2019-10-10 02:57
> I'm not familiar with adanet, but as another quick test, can you try running these
> 
> ```
> import tensorflow as tf
> GPU_OPTIONS = tf.GPUOptions(allow_growth=True)
> CONFIG = tf.ConfigProto(gpu_options=GPU_OPTIONS)
> sess = tf.Session(config = CONFIG)
> # <-- sleep and measure the mem usage here
> ```
> 
> before importing anything from adanet?

I already did that. Please refer to my previous comments

**Comment by eustomaqua** [comment] 2019-10-14 17:27
Well, it seems like this issue goes away even though I'm not sure whether that I'm guessing is the right reason.  
Previously, in the middle of models, I initialize some variables manually instead of using tf.global_variables_initializer. 
Now, I only initialize those variables that are not initialized at the very time, and suddenly, it works, now the model wouldn't take the whole GPU memory, at least it works for now.

**Comment by ravikyram** [comment] 2019-10-15 13:44
Glad to know that it worked.Closing the issue since its resolved. Thanks!

**Closed by ravikyram** 2019-10-15 13:44 UTC
Labels: TF 1.12, TF 1.14, comp:gpu, type:performance

**Comment by BryanBo-Cao** [comment] 2021-05-17 19:55
I had the same code and had debugged for hours but still it did not work -- it just used all the GPU memory it had.

In the end, **setting GPU before loading Keras** solved my problem of limiting GPU memory usage!

https://github.com/keras-team/keras/issues/1538#issuecomment-342034737
