### ISSUE TITLE
TF 1.15.0  savedModel running in  TF 2.1.0

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#38768] opened 2020-04-21 21:34 UTC
OS Platform and Distribution : macOS Catalina 10.15.3

TensorFlow installed from : binary

TensorFlow version : 1.15.0

Python version: 3.7.3

Hi All,

I have general question (so no code is provided) . Are below 2 questions possible :

1. Can we run TF 1.15.0 savedModel (which has feature transformation ported as part of savedModel) in TF 2.1.0 directly ? 

2. Is there any way to convert TF 1.15.0 savedModel (which has feature transformation ported as part of savedModel) directly to TF 2.1.0 ?

**Comment by ravikyram** [comment] 2020-04-22 06:15
@17patelumang 

Please, refer this [link](https://www.tensorflow.org/guide/migrate#saved_models_compatibility) and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by 17patelumang** [comment] 2020-04-22 18:18
we can close this thank you

**Comment by ravikyram** [comment] 2020-04-23 07:29
@17patelumang 

Thanks for the confirmation. I am closing this issue

**Closed by ravikyram** 2020-04-23 07:29 UTC
Labels: TF 2.1, comp:apis, type:support
