### ISSUE TITLE
tf.decode_csv works with \n but not with \r\n for new lines

### ISSUE THREAD

**Issue by ToraxXx** [tensorflow/tensorflow#633] opened 2015-12-28 02:20 UTC
I copied the example for reading CSV files from [here](https://www.tensorflow.org/versions/master/how_tos/reading_data/index.html#reading-from-files) and used it with csv files that I generated (5 columns, comma seperated) which used **\r\n** as line breaks which resulted in the following error:

> W tensorflow/core/common_runtime/executor.cc:1076] 0x1659ea0 Compute status: Invalid argument: Unquoted fields cannot have quotes/CRLFs inside

Using only **\n** worked as expected. According to the [standard](https://tools.ietf.org/html/rfc4180#section-2) using **\r\n** is also valid.

I'm using docker for windows and used the latest docker image, I haven't tried it on other machines.

**Comment by mrry** [comment] 2015-12-28 16:18
Looks like the issue is in `TextLineReader`, which only recognizes `'\n'` when splitting a text file into lines. I'll prepare a patch.

**Comment by mrry** [comment] 2016-01-06 00:14
Should be fixed at HEAD now.

**Closed by mrry** 2016-01-06 00:14 UTC
