### ISSUE TITLE
kernel dying, after import.

### ISSUE THREAD

**Issue by adshnaik** [tensorflow/tensorflow#22434] opened 2018-09-21 04:56 UTC
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)

**Comment by adshnaik** [comment] 2018-09-21 12:47
pytorch  works well, why not tensorflow.

**Comment by harshini-gadige** [comment] 2018-09-21 16:14
Duplicate of #22440.

**Closed by harshini-gadige** 2018-09-21 16:14 UTC
