### ISSUE TITLE
I get cultural errors when I import the Tensorflow library. Can you help me?

### ISSUE THREAD

**Issue by BgMuhendis** [tensorflow/tensorflow#37981] opened 2020-03-27 16:58 UTC
Traceback (most recent call last):
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Muhammet/PycharmProjects/Tez/Sentiment_Analysis.py", line 3, in <module>
    from tensorflow.python.keras.models import Sequential
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Muhammet\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
###

**Comment by khimraj** [comment] 2020-03-28 06:26
@BgMuhendis, This looks like a similiar of [#11571](https://github.com/tensorflow/tensorflow/issues/11571).

**Comment by gadagashwini** [comment] 2020-03-30 05:15
@BgMuhendis, Can you fill the issue template by providing Tensorflow version, python version and other stuff to understand the root cause of this issue. Thanks!

**Comment by gadagashwini** [comment] 2020-04-08 07:18
@BgMuhendis, Provide more information to replicate the issue. Thanks

**Comment by BgMuhendis** [comment] 2020-04-08 12:09
@gadagashwini  
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10 -64-bit

Python version:
3.7.4

CUDA/cuDNN version:
CUDA 10.0, cudnn64_7.dll (Windows file description is: NVIDIA CUDA CUDNN Library. Version 10.0)

GPU model and memory:
GPU NVidia Geforce 1050TI

TensorFlow version (use command below):
2.1.0 (command does not work, it includes the failed command)

**Comment by BgMuhendis** [comment] 2020-04-08 14:06
@gadagashwini  
Python 3.6 version is also installed on my computer and tensorflow is installed there
Thanks

**Comment by av8ramit** [comment] 2020-04-13 23:08
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by av8ramit** [comment] 2020-04-13 23:10
Sorry accidentally closed. Have you tried installing the MSVC 2019 redistributable?

**Comment by Saduf2019** [comment] 2020-04-19 17:03
@BgMuhendis 
please update on the above comment

**Comment by Saduf2019** [comment] 2020-04-27 10:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by Saduf2019** 2020-04-27 10:50 UTC
Labels: stalled, subtype:windows, type:build/install
