### ISSUE TITLE
why would I got "tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file" when I use pretrain model download from https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models

### ISSUE THREAD

**Issue by WuShaoXuan5** [tensorflow/tensorflow#27980] opened 2019-04-19 09:22 UTC
Hi,
I download resnet_v2_2017_04_14 from https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models,
and rename it as "resnet_v2_2017_04_14.ckpt".
But when I "tf.train.init_from_checkpoint " to initialize it ,I got "tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file"
why would I got "tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file" ?
This also happened when I use slim.assign_from_checkpoint_fn()
### Source code / logs
#Here is the code
def get_init_fn(checkpoint_exclude_scopes=None):
    checkpoint_path =  './ini_checkpoints/resnet_v1_101.ckpt'
    if checkpoint_path is None:
        return None

    # Warn the user if a checkpoint exists in the train_dir. Then we'll be
    # ignoring the checkpoint anyway.
    if tf.train.latest_checkpoint('./training'):
        tf.logging.info(
            'Ignoring --checkpoint_path because a checkpoint already exists ' +
            'in ./training')
        return None

    exclusions = []
    if checkpoint_exclude_scopes:
        exclusions = [scope.strip() for scope in
                      checkpoint_exclude_scopes.split(',')]
    variables_to_restore = []
    for var in slim.get_model_variables():
        excluded = False
        for exclusion in exclusions:
            if var.op.name.startswith(exclusion):
                excluded = True
        if not excluded:
            variables_to_restore.append(var)

    if tf.gfile.IsDirectory(checkpoint_path):
        checkpoint_path = tf.train.latest_checkpoint(checkpoint_path)
    else:
        checkpoint_path = checkpoint_path

    tf.logging.info('Fine-tuning from %s' % checkpoint_path)

    return slim.assign_from_checkpoint_fn(
        checkpoint_path,
        variables_to_restore,
        ignore_missing_vars=True)

init_fn = get_init_fn()

**Comment by allenlavoie** [comment] 2019-04-19 16:31
Oh interesting, those are still using the proto-based checkpoint format which hasn't been the default save format for years. `tf.train.Saver` (or in v2 `tf.compat.v1.Saver`) can still read them, although newer checkpoint tools probably won't. So you could load them with `tf.train.Saver` and re-save and then they should work with `assign_from_checkpoint`.

**Comment by WuShaoXuan5** [comment] 2019-04-20 14:16
> Oh interesting, those are still using the proto-based checkpoint format which hasn't been the default save format for years. tf.train.Saver (or in v2 tf.compat.v1.train.Saver) can still read them, although newer checkpoint tools probably won't. So you could load them with tf.train.Saver and re-save and then they should work with assign_from_checkpoint.
But it only happened when I use resnet_v2_101_2017_04_14，but not happend to some other pretained models like resnet_2016_08_18.
I wonder is the pretrained model publish in 2017 defferent from pretrain model pubilsh in 2016?
Or would it happened because I hadn't use Inception preprocessing for Resnet V2?

**Comment by WuShaoXuan5** [comment] 2019-04-20 14:25
@allenlavoie Think you for your answer!
But it happened only when I use resnet_v2_2017_04_14,but not happened to other pretrained models like resnet_v1_101_2016_08_18.
I wonder would it because  the pretrained models published in 2017 defferent from pretrained models published in 2016?
Or would it heppened because I hadn't use Inception preprocessing to processing resnet_v2_101_2017_04_14before I initialize it.

**Comment by muddham** [comment] 2019-04-24 12:17
@WuShaoXuan5 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-05-06 14:16
@WuShaoXuan5 Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-06 14:16 UTC
Labels: comp:model, stat:awaiting response, type:support

**Comment by FCinHFUT** [comment] 2019-06-11 08:26
I also met the same same same  question !!!  Have you resolved the problem?

**Comment by WuShaoXuan5** [comment] 2019-06-11 08:41
> I also met the same same same  question !!!  Have you resolved the problem?
I later downloaded resnet_v1_101 and us it as a replacement of resnet_v2_101.
Resnet_v1_101 can be used normally.

**Comment by FCinHFUT** [comment] 2019-06-11 13:14
you mean just use resnet_v1_101 to replace resnet_v2_101, I want to make implementation of deeplab V3+,  I tried but still find another failure...  you chinese? I'm CHINESE student, can I add your wechat or QQ? so sorry...




------------------ 原始邮件 ------------------
发件人: "WuShaoXuan5"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 下午4:48
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com>;
抄送: "冯超"<502553602@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tensorflow/tensorflow] why would I got"tensorflow.python.framework.errors_impl.DataLossError: Unable to open tablefile" when I use pretrain model download fromhttps://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models(#27980)



 
I also met the same same same  question !!!  Have you resolved the problem?
 I later downloaded resnet_v1_101 and us it as a replacement of resnet_v2_101.
 Resnet_v1_101 can be used normally.

**Comment by WuShaoXuan5** [comment] 2019-06-12 03:00
> you mean just use resnet_v1_101 to replace resnet_v2_101, I want to make implementation of deeplab V3+,  I tried but still find another failure...  you chinese? I'm CHINESE student, can I add your wechat or QQ? so sorry...
> …
> ------------------ 原始邮件 ------------------
> 发件人: "WuShaoXuan5"<notifications@github.com>;
> 发送时间: 2019年6月11日(星期二) 下午4:48
> 收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com>;
> 抄送: "冯超"<502553602@qq.com>;"Comment"<comment@noreply.github.com>;
> 主题: Re: [tensorflow/tensorflow] why would I got"tensorflow.python.framework.errors_impl.DataLossError: Unable to open tablefile" when I use pretrain model download fromhttps://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models(#27980)
> 
> 
> 
> 
> I also met the same same same  question !!!  Have you resolved the problem?
>  I later downloaded resnet_v1_101 and us it as a replacement of resnet_v2_101.
>  Resnet_v1_101 can be used normally.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

You need to change the corresponding Settings in the code for resnet_v2_101 to resnet_v1_101

**Comment by WuShaoXuan5** [comment] 2019-11-15 06:21
We should not rename resnet_v2_2017_04_14  as "resnet_v2_2017_04_14.ckpt", which is in resnet_v2_2017_04_14.tar ,but instead rename it as 'resnet_v2_2017_04_14.tar'.And then open it as RAR, then we will get three files in it:eval.graph, resnet_v2_101.ckpt, train.graph
