### ISSUE TITLE
does pip wheels support hdfs on default?

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensorflow#30981] opened 2019-07-24 09:35 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary?
- TensorFlow version: 1.12
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**
Uncertain if pip tensorflow_gpu 1.12 for python 3.5 supports hdfs by default

**Any other info / logs**
util.NativeCodeLoader: Unable to load native-hadoop library for your platform
info retry.RetryInvocationHandler org.apache.hadoop.net.ConnectTimeoutException: Call From ... failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 20000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=...] while invoking ClientNameNodeProtocolTranslatorPB.getFileinfo over ... after 1 failover attempts. Trying to failover after sleeping for 781ms

**Comment by sharkdtu** [comment] 2019-07-24 12:11
Yes. you should set hadoop env in advance:
```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${JAVA_HOME}/jre/lib/amd64/server:${HADOOP_HDFS_HOME}/lib/native
export CLASSPATH=$(${HADOOP_HOME}/bin/hadoop classpath --glob)
python your_script.py
```

**Comment by colmantse** [comment] 2019-07-24 12:18
much thanks!

**Comment by colmantse** [comment] 2019-07-29 07:15
I am running it on a paas, therefore instead of shell export, i did instead
""" os.environ["LD_LIBRARY_PATH"]+=":"+os.environ["JAVA_HOME"]+"/jre/lib/amd64/server:"+os.environ["HADOOP_HDFS_HOME"]+"/lib/native"
  f = os.popen("/opt/hadoop/bin/hadoop classpath --glob")
  classpath=f.read()
  os.environ["CLASSPATH"]=classpath.strip('\n') 
"""
the unable to load error goes away but the socket timeout exception persists and the program is unable to run.

**Comment by anush-o** [comment] 2019-07-30 11:44
@colmantse ,
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by colmantse** [comment] 2019-07-30 13:26
@anush-o sorry for the ambiguity , I have narrowed down it to this function:

data_files = sorted(tf.contrib.slim.parallel_reader.get_data_files(
        data_filepattern))
where datafilepattern is the hdfs://path/pattern

**Comment by anush-o** [comment] 2019-07-31 10:44
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): binary?
> * TensorFlow version: 1.12
> * Python version: 3.5
> * Installed using virtualenv? pip? conda?: pip
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version:
> * GPU model and memory:
> 
> **Describe the problem**
> Uncertain if pip tensorflow_gpu 1.12 for python 3.5 supports hdfs by default
> 
> **Any other info / logs**
> util.NativeCodeLoader: Unable to load native-hadoop library for your platform
> info retry.RetryInvocationHandler org.apache.hadoop.net.ConnectTimeoutException: Call From ... failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 20000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=...] while invoking ClientNameNodeProtocolTranslatorPB.getFileinfo over ... after 1 failover attempts. Trying to failover after sleeping for 781ms

@colmantse ,
Looks like the issue is from hadoop,can you confirm?Thanks!

**Comment by colmantse** [comment] 2019-07-31 10:53
um.... yeah Hadoop error is raised. I am just not sure if it is caused because some of the function in tf 1.12 and Hadoop is incompatible.

**Comment by gunan** [comment] 2019-08-01 17:31
@jhseu do you know who know about the hdfs support in TF?

**Comment by colmantse** [comment] 2019-08-02 07:30
update, apart from tf.contrib.slim.parallel_reader.get_data_files, 

tf.python_io.tf_record_iterator does not support hdfs as well

**Comment by jhseu** [comment] 2019-08-02 23:26
@colmantse Is your Hadoop cluster running in secure mode? You may also need to pass the Kerberos ticket cache env var:
https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md

**Comment by colmantse** [comment] 2019-08-03 02:54
hi, I would double check and come back after the weekend. thanks.

**Comment by colmantse** [comment] 2019-08-05 09:55
@jhseu hi, the cluster is not running in secure mode.

**Comment by colmantse** [comment] 2019-08-08 11:52
@jhseu hi, the cluster is not running in secure mode.
My current status is that i have located the function below as the cause of the error,
data_files = sorted(tf.contrib.slim.parallel_reader.get_data_files(
data_filepattern))
where datafilepattern is the hdfs://path/pattern
and i work it around by
data_filepattern = nfs_data_filepattern
data_files = sorted(tf.contrib.slim.parallel_reader.get_data_files(
data_filepattern))
data_files = [x.replace(nfs_path,hdfs_path) for x in data_files]
after that the below log happened
graph was finalized.
restoring parameters from nfs/data
saving check point.
warn retry.retryinvovationhandler: a failover has occured since the start of call #2 clientnamenodeprotocaltranslatorPB.getBlocklocations over /30.12.2.128.9000
info retry.RetryInvocationHandler org.apache.hadoop.net.ConnectTimeoutException: Call From ... failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 20000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=...] while invoking ClientNameNodeProtocolTranslatorPB.getFileinfo over ... after 1 failover attempts. Trying to failover after sleeping for 781ms

**Comment by bhack** [comment] 2021-05-13 17:39
Can we close this?

**Comment by mohantym** [comment] 2021-08-31 10:20
Hi @colmantse !
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Closed** 2021-09-07 18:02 UTC
Labels: stat:awaiting response, type:build/install, stalled, TF 1.12, subtype: ubuntu/linux
