### ISSUE TITLE
 Tensorflow2.1.compat.v1 distributed training occasionally goes wrong

### ISSUE THREAD

**Issue by zkx741481546** [tensorflow/tensorflow#37407] opened 2020-03-07 02:34 UTC
`TaskIndex: 4 | Episode: 1995/100000  | Episode Reward: 52.2229  | Running Time: 7.6459 | EnvStep Time: 0.7538 | Render Time: 0.0000
TaskIndex: 1 | Episode: 1984/100000  | Episode Reward: 2.9837  | Running Time: 7.6459 | EnvStep Time: 1.4454 | Render Time: 0.0000
TaskIndex: 6 | Episode: 1992/100000  | Episode Reward: 8.1637  | Running Time: 7.6850 | EnvStep Time: 1.0630 | Render Time: 0.0000
TaskIndex: 0 | Episode: 2004/100000  | Episode Reward: -60.5018  | Running Time: 5.3829 | EnvStep Time: 2.2781 | Render Time: 0.9659
2020-03-07 09:55:22.138197: I tensorflow/core/202distri0b-03uted-07 09_runtime/worker:55:22..138233: Ic c:t2enso04]rfl Caowncell/coaretion /dreqistriuebuted_rsted untifor meRun/worker.cc:2Grap04]h.
 Cancellation requested for RunGraph.
2020-03-07 09:55:22.138365: I tensorflow/core/distributed_runtime/worker.cc:204] Can202cella0-tio03-07n  09:55:22re.13850que8: Ested  tensorflfor owRu/conGrre/aphdistribu.
ted_runtime/master_session.cc:1911] Cleanup partition error: Unavailable: Stream removed
Additional GRPC error information:
{"created":"@1583546122.138000000","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Stream removed","grpc_status":2}
2020-03-07 09:55:22.1382029208220-03-: 02020-03-07 09:55:22.139043: I tensorflow20/2c0-03-07 09:55o:20-Ir2e/d tensorflow/core/distributed_runtime/worker.cc:204] Cancellation reques2020ted- fo0r3- 07 09R7u 0n9::55250205.:122.1:39014:2G2 r.I1a 3ptensorfh9l.2o
08: I tensorflow/core/distributed_runtime/worker.cc:204] Cancellation requested for RunGraph.
03-07 09:55:22.w/core/distributed_runtime/worker.cc:204] Cancellation reistrq-03-07 0u138993eis39089: I tensorflow/core/distributed_runtime/worker.cc:204] Cancellation reqt: eb9u:Idu e5 fosted for RunGraph.
5te:tnesod2r_2f.lo1rw3u/9nctoirmee//2wdistributed_runtime/worker.cc:204] Can7ocrkelelr6a:.tion  Ir ctensorflow/core/distributed_ruce:q2un0et4si]tmee d/C wafoornrkc eeRru.nGclcrl:ar Rph.2a
04] Cancellation requested for RunGraph.
tion requested for RunGraph.
unGraph.
2020-03-07 09:55:22.588608: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-07 09:55:22.588719: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\zkx74\Anaconda3\envs\RL\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning:

pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.`

It can train normally for aobut hundreds episode, and the throw this error message.
I used 1ps and 8 worker on 1CPU+1GPU

**Comment by ravikyram** [comment] 2020-03-09 08:47
@zkx741481546 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Request you to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Please, fill [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by zkx741481546** [comment] 2020-03-09 10:21
> @zkx741481546
> 
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Request you to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Please, fill [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

Win10 1903 
anaconda 
python3.7
tensorflow2.1 avx2 
tebsorflow2.1-gpu avx2

It turns out to be a bug of pycharm, after this error, python program launched by pycharm can't find  cuda lib, but it works normally with powershell.
After I restart pycharm, the problem never occored.

**Comment by ravikyram** [comment] 2020-03-12 09:17
@zkx741481546 

looks like issue got resolved. Please close this thread if it solves your question. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-28 01:10
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-30 07:12
Closing the issue since its resolved. Thanks!

**Closed by ravikyram** 2020-03-30 07:12 UTC
Labels: TF 2.1, stat:awaiting response, type:others
