### ISSUE TITLE
the error message of "OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781            INFO:tensorflow:Error reported to Coordinator: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781    "

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/tensorflow#18905] opened 2018-04-26 18:48 UTC
When running the deeplab model (train.py) included in tensorflow, it keeps generating the log message such as following. I don't know what does it mean.
```

2018-04-26 13:37:54.472896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0                                                        
2018-04-26 13:37:54.472907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N                                                        
INFO:tensorflow:Restoring parameters from /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt-0                  
INFO:tensorflow:Running local_init_op.                                                                                                            
INFO:tensorflow:Done running local_init_op.                                                                                                       
INFO:tensorflow:Starting Session.                                                                                                                 
INFO:tensorflow:Saving checkpoint to path /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt                    
INFO:tensorflow:Starting Queues.                                                                                                                  
2018-04-26 13:38:17.513798: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781           
INFO:tensorflow:Error reported to Coordinator: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                             
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

Caused by op 'concat', defined at:
  File "train.py", line 386, in <module>
    tf.app.run()                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))                                                                                                        
  File "train.py", line 278, in main                                                                                             
    clones = model_deploy.create_clones(config, model_fn, args=model_args)                                                       
  File "/tmp/test/models/research/slim/deployment/model_deploy.py", line 193, in create_clones                                   
    outputs = model_fn(*args, **kwargs)                                                                                          
  File "train.py", line 207, in _build_deeplab                                                                                   
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)                                                                             
  File "/tmp/test/models/research/deeplab/model.py", line 296, in multi_scale_logits                                             
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 461, in _get_logits                                                    
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 424, in _extract_features                                              
    concat_logits = tf.concat(branch_logits, 3)                                                                                  
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)                                                               
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)                                                                                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper                                                                                                                                          
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op         
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__          
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access                                                            

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                                    
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              
Traceback (most recent call last):                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call         
    return fn(*args)                                                                                                                              
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn          
    options, feed_dict, fetch_list, target_list, run_metadata)                                                                                    
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun                                                                                                                                                
    status, run_metadata)                                                                                                                         
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__   
    c_api.TF_GetCode(self.status.status))                                                                                                         
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                      
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception                                                                                                                                             
    yield                                                                                                                                         
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 495, in run         
    self.run_loop()                                                                                                                               
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1030, in run_loop    
    self._sv.global_step])                                                                                                                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run               
    run_metadata_ptr)                                                                                                                             
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run             
    feed_dict_tensor, options, run_metadata)                                                                                                      
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run          
    run_metadata)                                                                                                                                 
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call         
    raise type(e)(node_def, op, message)                                                                                                          
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                      
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

Caused by op 'concat', defined at:
  File "train.py", line 386, in <module>
    tf.app.run()                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))                                                                                                        
  File "train.py", line 278, in main                                                                                             
    clones = model_deploy.create_clones(config, model_fn, args=model_args)                                                       
  File "/tmp/test/models/research/slim/deployment/model_deploy.py", line 193, in create_clones                                   
    outputs = model_fn(*args, **kwargs)                                                                                          
  File "train.py", line 207, in _build_deeplab                                                                                   
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)                                                                             
  File "/tmp/test/models/research/deeplab/model.py", line 296, in multi_scale_logits                                             
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 461, in _get_logits                                                    
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 424, in _extract_features                                              
    concat_logits = tf.concat(branch_logits, 3)                                                                                  
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)                                                               
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)                                                                                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper                                                                                                                                          
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op         
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__          
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access                                                            

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                                    
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

2018-04-26 13:38:18.049156: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781           
INFO:tensorflow:Retrying training!                                                                                                                
2018-04-26 13:38:18.592880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1394] Ignoring visible gpu device (device: 0, name: Quadro 5000, pci bus id: 0000:05:00.0, compute capability: 2.0) with Cuda compute capability 2.0. The minimum required Cuda capability is 3.0.                   
2018-04-26 13:38:18.592940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:                                                                                                                                                 
2018-04-26 13:38:18.592950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0                                                        
2018-04-26 13:38:18.592958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N                                                        
INFO:tensorflow:Restoring parameters from /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt-0                  
INFO:tensorflow:Running local_init_op.                                                                                                            
INFO:tensorflow:Done running local_init_op.                                                                                                       
INFO:tensorflow:Starting Session.                                                                                                                 
INFO:tensorflow:Saving checkpoint to path /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt                    
INFO:tensorflow:Starting Queues.                                                                                                                  
2018-04-26 13:38:42.322907: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781           
INFO:tensorflow:Error reported to Coordinator: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                             
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

Caused by op 'concat', defined at:
  File "train.py", line 386, in <module>
    tf.app.run()                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))                                                                                                        
  File "train.py", line 278, in main                                                                                             
    clones = model_deploy.create_clones(config, model_fn, args=model_args)                                                       
  File "/tmp/test/models/research/slim/deployment/model_deploy.py", line 193, in create_clones                                   
    outputs = model_fn(*args, **kwargs)                                                                                          
  File "train.py", line 207, in _build_deeplab                                                                                   
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)                                                                             
  File "/tmp/test/models/research/deeplab/model.py", line 296, in multi_scale_logits                                             
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 461, in _get_logits                                                    
    fine_tune_batch_norm=fine_tune_batch_norm)                                                                                   
  File "/tmp/test/models/research/deeplab/model.py", line 424, in _extract_features                                              
    concat_logits = tf.concat(branch_logits, 3)                                                                                  
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)                                                               
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)                                                                                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper                                                                                                                                          
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op         
    op_def=op_def)                                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__          
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access                                                            

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                                    
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              
Traceback (most recent call last):                                                                                                                
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call         
    return fn(*args)                                                                                                                              
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn          
    options, feed_dict, fetch_list, target_list, run_metadata)                                                                                    
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun                                                                                                                                                
    status, run_metadata)                                                                                                                         
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__   
    c_api.TF_GetCode(self.status.status))                                                                                                         
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                      
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]                                                                              

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception                                                                                                                                             
    yield                                                                                                                                         
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 495, in run         
    self.run_loop()                                                                                                                               
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1030, in run_loop    
    self._sv.global_step])                                                                                                                        
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run               
    run_metadata_ptr)                                                                                                                             
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run             
    feed_dict_tensor, options, run_metadata)                                                                                                      
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run          
    run_metadata)                                                                                                                                 
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call         
    raise type(e)(node_def, op, message)                                                                                                          
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781                                                                                      
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]

Caused by op 'concat', defined at:
  File "train.py", line 386, in <module>
    tf.app.run()
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 278, in main
    clones = model_deploy.create_clones(config, model_fn, args=model_args)
  File "/tmp/test/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train.py", line 207, in _build_deeplab
    fine_tune_batch_norm=FLAGS.fine_tune_batch_norm)
  File "/tmp/test/models/research/deeplab/model.py", line 296, in multi_scale_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/tmp/test/models/research/deeplab/model.py", line 461, in _get_logits
    fine_tune_batch_norm=fine_tune_batch_norm)
  File "/tmp/test/models/research/deeplab/model.py", line 424, in _extract_features
    concat_logits = tf.concat(branch_logits, 3)
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1181, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 949, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/user/virtualE/deeplab/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781
         [[Node: concat = _MklConcatV2[N=5, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear_1, aspp0/Relu, aspp1_pointwise/Relu, aspp2_pointwise/Relu, aspp3_pointwise/Relu, concat/axis, DMT/_313, aspp0/Relu:1, aspp1_pointwise/Relu:1, aspp2_pointwise/Relu:1, aspp3_pointwise/Relu:1, DMT/_314)]]

2018-04-26 13:38:42.846252: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at mkl_concat_op.cc:784 : Aborted: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:781
INFO:tensorflow:Retrying training!
2018-04-26 13:38:43.479830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1394] Ignoring visible gpu device (device: 0, name: Quadro 5000, pci bus id: 0000:05:00.0, compute capability: 2.0) with Cuda compute capability 2.0. The minimum required Cuda capability is 3.0.
2018-04-26 13:38:43.479882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-26 13:38:43.479896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0
2018-04-26 13:38:43.479906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N
INFO:tensorflow:Restoring parameters from /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /user/DL-Phase3/DeepLab/ADE20K/train_on_train_set/train/model.ckpt
INFO:tensorflow:Starting Queues.


```

**Comment by tensorflowbutler** [comment] 2018-04-27 06:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by s-ravichandran** [comment] 2018-04-27 09:11
You will have to rollback to TF1.6 to get this resolved.

Refer this issue for more details https://github.com/tensorflow/tensorflow/issues/17494

**Comment by wenouyang** [comment] 2018-04-29 02:51
Hi s-ravichandran, I rollbacked to TF1.6, and got the same problem. The python is 3.5

**Comment by wei-v-wang** [comment] 2018-04-30 23:37
Related to https://github.com/tensorflow/tensorflow/issues/17494 as @wenouyang also noticed.

**Comment by tensorflowbutler** [comment] 2018-05-15 18:42
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-01 23:59
Nagging Assignee @bignamehyp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment] 2018-06-14 23:57
Please follow @17494 and close this bug.

**Comment by tensorflowbutler** [comment] 2018-06-29 18:56
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-14 18:40
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-29 18:34
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Closed** 2018-08-15 02:48 UTC
Labels: stat:awaiting response

**Comment by tensorflowbutler** [comment] 2018-08-15 02:55
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by BlackHandguy** [comment] 2019-08-31 07:35
I also have this error.I need help
