### ISSUE TITLE
ValueError: as_list() is not defined on an unknown TensorShape.

### ISSUE THREAD

**Issue by cjjjy** [tensorflow/tensorflow#24824] opened 2019-01-10 08:06 UTC
I want to test some example with my training model ,but it occur error during test ,console tell me the wrong in my code is focus on line 119:

line112: cell_fw = LSTMCell(self.hidden_dim,forget_bias=0.4)
line113: cell_bw = LSTMCell(self.hidden_dim,forget_bias=0.4)
line114: (output_fw_seq, output_bw_seq), _ = 
            tf.nn.bidirectional_dynamic_rnn(
line115:    cell_fw=cell_fw,
line116:    cell_bw=cell_bw,
line117:    inputs=self.word_embeddings,
line118:    sequence_length=self.sequence_lengths,
line119     dtype=tf.float32)
The console error as follows:

 File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py", line 416, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py", line 632, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn.py", line 697, in _dynamic_rnn_loop
    const_time_steps, const_batch_size = inputs_got_shape[0].as_list()[:2]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 812, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

**Comment by ymodak** [comment] 2019-01-11 21:30
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-01-18 00:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-01-18 00:37 UTC
Labels: comp:apis, stat:awaiting response, type:support
