### ISSUE TITLE
Securing models before sending it to client for inference

### ISSUE THREAD

**Issue by aayusharora** [tensorflow/tensorflow#36858] opened 2020-02-18 13:49 UTC
We have Tensorflow Saved model format (.pb file  )that we want to ship in an offline application. 
Is there a way to secure the model such that, it is not exposed to the client?

We understand that any logic that is running on the client-side is exposed by definition but wondering whether there are best practices to mitigate this risk?

**Comment by dtsmith2001** [comment] 2020-02-18 13:56
Please do some searches, there are a variety of ways to accomplish this goal with varying degrees of risk.

**Comment by aayusharora** [comment] 2020-02-18 14:26
@dtsmith2001 
I have done my research by didn't find anything convincing.
Can you please share some resources?
Any help would be appreciated.

**Comment by dtsmith2001** [comment] 2020-02-18 15:39
I don't think this is a question for tensorflow.

Are you using Python or some other language in the remote app?

**Comment by aayusharora** [comment] 2020-02-18 17:54
Yes @dtsmith2001 , we are using python in the app.

**Comment by ravikyram** [comment] 2020-02-20 06:49
@aayusharora 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2020-03-03 11:13
@aayusharora 

As this issue not related to bug or feature request I am closing this issue.Please, ask this question in Stackoverflow. Thanks!

**Closed by ravikyram** 2020-03-03 11:13 UTC
Labels: stat:awaiting response, type:support

**Comment by mihaimaruseac** [comment] 2020-03-05 19:47
Please consult the [security guidelines](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md)
