### ISSUE TITLE
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: size of values 0 does not match size of permutation 4.

### ISSUE THREAD

**Issue by wkdgnsgo** [tensorflow/tensorflow#34499] opened 2019-11-21 22:55 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below):  2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: RTX 2080Ti 11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Originally, I built this model in tensorflow 1.1x and I transferred the model to TF 2.0 manually to use tf.keras. It is working but it shows me this error message  (E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: size of values 0 does not match size of permutation 4.) and its performance is worse than tf 1.1x. 

I suspect that this error interrupts to train somehow. 

I didn't put any permutation layer in my model. It is hard to find it. 

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jjqtony** [comment] 2019-11-24 12:34
same issue for me.

**Comment by gadagashwini** [comment] 2019-11-25 06:07
@wkdgnsgo, Please paste the standalone code to reproduce the issue.
Follow the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/guide/migrate) site to migrate from TF1 to TF2. Thanks!

**Comment by miguelalba96** [comment] 2019-11-25 19:23
I have the exact same issue training a cycleGAN, my operations are built in `tf.Module` and I’m using `tf.optimizers.Adam`

**Comment by MadsAdrian** [comment] 2019-11-28 12:08
I get the same error message(/warning?). `Python 3.6.8 [GCC 8.3.0]`, tf.version `v2.0.0-rc2-26-g64c3d38 2.0.0` in the official tf docker image. 

Quite a large I2I translation project, so it's hard to make minimal reproducing code. An issue that _might_ be related is a shape error that is produced if the `train` function is decorated with `@tf.function`, which works in EE mode. 

A par of subclassed `tf.keras.Model`s `f_x, f_y` is used with the train step pattern
```python 
self.loss_object = tf.keras.losses.MeanSquaredError()
self.optimizer = tf.keras.optimizers.Adam(tf.keras.optimizers.schedules.ExponentialDecay(...))

def train_step(x,y,cross_loss_weight)
    with tf.GradientTape as tape: 
        y_hat, x_hat = f_x(x), f_y(y)
        x_tilde, y_tilde = f_y(y_hat), f_x(x_hat)
        fx_loss = {
                "cross": self.loss_object(y, y_hat, clw),
                "cycle": self.loss_object(x, x_tilde),
                "reg": sum(self._fx.losses),  # regularization from submodel
        }
        fx_loss = {key: self.lambdas[key] * value for key, value in fx_loss.items()}
        fx_total_loss = sum(fx_loss.values())
        ... same for f_y...
    gradient_targets = self._fx.trainable_variables + self._fy.trainable_variables
    gradients = tape.gradient(loss_value, gradient_targets)
    self.optimizer.apply_gradients(zip(gradients, gradient_targets))
``` 

So it seems the use is similar to @miguelalba96 with a cyclic loss term, but no adversarial term in my case. The model is hardly a DAG, but rather two DAGs trained in conjunction. Can the issue be related to this?

**Comment by AntoinePlumerault** [comment] 2019-12-03 10:48
I am training a VAE and I encountered the same issue and managed to remove the error but I do not understand what caused the issue. When I run this code I get the error: 
`@tf.function
    def forward(x_real):
        eps = tf.random.normal([FLAGS.batch_size, FLAGS.latent_dim])
        z_mu, z_log_sigma = E(x_real, training=True)
        z = z_mu + tf.exp(z_log_sigma) * eps
        x_real_mu = D(z, training=True)

        kl_loss = tf.reduce_mean(
            kl_divergence(z_mu, z_log_sigma))
        ll_loss = tf.reduce_mean(
            negative_log_likelyhood(x_real, x_real_mu))
        return x_real_mu, ll_loss, kl_loss
`
but the error vanish if I run this one:
`@tf.function
    def forward(x_real):
        eps = tf.random.normal([FLAGS.batch_size, FLAGS.latent_dim])
        z_mu, z_log_sigma = E(x_real, training=True)
        z = z_mu + tf.exp(z_log_sigma) * eps
        x_real_mu = D(z, training=True)

        kl_loss = tf.reduce_mean(
            kl_divergence(z_mu, z_log_sigma))
        ll_loss = tf.reduce_mean(
            negative_log_likelyhood(x_real+0.0, x_real_mu)) # <-- change here
        return x_real_mu, ll_loss, kl_loss
`
I wonder why the first version raise the error...

**Comment by gadagashwini** [comment] 2019-12-05 06:02
@AntoinePlumerault, Could provide the complete code snippet to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2019-12-12 06:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-12-12 06:37 UTC
Labels: TF 2.0, comp:grappler, comp:ops, stat:awaiting response, type:bug

**Comment by ktatar** [comment] 2019-12-18 21:25
I confirm the same issue. I am working with python 3.7 and tensorflow-gpu 2.0 release installed from pip. 
Here is the code to reproduce the issue. You would need a folder of images with the same size to run this code:

`# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import os
import time
import numpy as np
import glob
import matplotlib.pyplot as plt
import PIL
import imageio
import random
import pdb
from IPython import display

AUTOTUNE = tf.data.experimental.AUTOTUNE
print("GPU is available:", tf.test.is_gpu_available())
#data_root_train = '/home/tatar/.keras/datasets/flower_photos/daisy'
#data_root_test = '/home/tatar/.keras/datasets/flower_photos/tulips'z

data = "YOUR-DATA-FOLDER"
image_h = 320
image_w = 180
epochs = 200

all_image_paths = [os.path.join(data, file) for file in os.listdir(data)]
random.shuffle(all_image_paths)

#all_image_paths = all_image_paths[:int(0.5*len(all_image_paths))]

all_train_image_paths = all_image_paths[:int(0.9*len(all_image_paths))]
all_test_image_paths = all_image_paths[int(0.9*len(all_image_paths)):]

BATCH_SIZE = 8
TRAIN_BUF = len(all_train_image_paths)
TEST_BUF = len(all_test_image_paths)

def decode_img(img):
  # convert the compressed string to a 3D uint8 tensor
  img = tf.image.decode_jpeg(img, channels=3)
  # Use `convert_image_dtype` to convert to floats in the [0,1] range.
  img = tf.image.convert_image_dtype(img, tf.float32)
  # resize the image to the desired size.
  #img = tf.image.resize(img, [image_w, image_h])
  return img 

def process_path(file_path):
  # load the raw data from the file as a string
  img = tf.io.read_file(file_path)
  img = decode_img(img)
  return img

def preprocess_image(image):
  image = tf.image.decode_jpeg(image, channels=3)
  #image = tf.image.resize(image, [image_w, image_h])
  image = tf.image.convert_image_dtype(image, tf.float32)  # normalize to [0,1] range
  return image

def load_and_preprocess_image(path):
  image = tf.io.read_file(path)
  return preprocess_image(image)

path_train_ds = tf.data.Dataset.from_tensor_slices(all_train_image_paths)
path_test_ds = tf.data.Dataset.from_tensor_slices(all_test_image_paths)

train_dataset = path_train_ds.map(load_and_preprocess_image, num_parallel_calls=AUTOTUNE).shuffle(TRAIN_BUF).batch(BATCH_SIZE).prefetch(AUTOTUNE)
test_dataset = path_test_ds.map(load_and_preprocess_image, num_parallel_calls=AUTOTUNE).shuffle(TEST_BUF).batch(BATCH_SIZE).prefetch(AUTOTUNE)

"""## Wire up the generative and inference network with *tf.keras.Sequential*

In our VAE example, we use two small ConvNets for the generative and infercence network. Since these neural nets are small, we use `tf.keras.Sequential` to simplify our code. Let $x$ and $z$ denote the observation and latent variable respectively in the following descriptions.

### Generative Network
This defines the generative model which takes a latent encoding as input, and outputs the parameters for a conditional distribution of the observation, i.e. $p(x|z)$. Additionally, we use a unit Gaussian prior $p(z)$ for the latent variable.

### Inference Network
This defines an approximate posterior distribution $q(z|x)$, which takes as input an observation and outputs a set of parameters for the conditional distribution of the latent representation. In this example, we simply model this distribution as a diagonal Gaussian. In this case, the inference network outputs the mean and log-variance parameters of a factorized Gaussian (log-variance instead of the variance directly is for numerical stability).

### Reparameterization Trick
During optimization, we can sample from $q(z|x)$ by first sampling from a unit Gaussian, and then multiplying by the standard deviation and adding the mean. This ensures the gradients could pass through the sample to the inference network parameters.

### Network architecture
For the inference network, we use two convolutional layers followed by a fully-connected layer. In the generative network, we mirror this architecture by using a fully-connected layer followed by three convolution transpose layers (a.k.a. deconvolutional layers in some contexts). Note, it's common practice to avoid using batch normalization when training VAEs, since the additional stochasticity due to using mini-batches may aggravate instability on top of the stochasticity from sampling.
"""

class CVAE(tf.keras.Model):
  def __init__(self, latent_dim):
    super(CVAE, self).__init__()
    self.latent_dim = latent_dim
    self.inference_net = tf.keras.Sequential(
      [
          tf.keras.layers.InputLayer(input_shape=(image_w, image_h, 3)),
          tf.keras.layers.Conv2D(
              filters=32, kernel_size=3, strides=(2, 2), activation='relu'),
          tf.keras.layers.Conv2D(
              filters=64, kernel_size=3, strides=(2, 2), activation='relu'),
          tf.keras.layers.Flatten(),
          # No activation
          tf.keras.layers.Dense(latent_dim + latent_dim),
      ]
    )

    self.generative_net = tf.keras.Sequential(
        [
          tf.keras.layers.InputLayer(input_shape=(latent_dim,)),
          tf.keras.layers.Dense(units=int(image_w/4)*int(image_h/4)*32, activation=tf.nn.relu),
          tf.keras.layers.Reshape(target_shape=(int(image_w/4), int(image_h/4), 32)),
          tf.keras.layers.Conv2DTranspose(
              filters=64,
              kernel_size=3,
              strides=(2, 2),
              padding="SAME",
              activation='relu'),
          tf.keras.layers.Conv2DTranspose(
              filters=32,
              kernel_size=3,
              strides=(2, 2),
              padding="SAME",
              activation='relu'),
          # No activation
          tf.keras.layers.Conv2DTranspose(
              filters=3, kernel_size=3, strides=(1, 1), padding="SAME"),
        ]
    )

  @tf.function
  def sample(self, eps=None):
    if eps is None:
      eps = tf.random.normal(shape=(100, self.latent_dim))
    return self.decode(eps, apply_sigmoid=True)

  def encode(self, x):
    mean, logvar = tf.split(self.inference_net(x), num_or_size_splits=2, axis=1)
    return mean, logvar

  def reparameterize(self, mean, logvar):
    eps = tf.random.normal(shape=mean.shape)
    return eps * tf.exp(logvar * .5) + mean

  def decode(self, z, apply_sigmoid=False):
    logits = self.generative_net(z)
    if apply_sigmoid:
      probs = tf.sigmoid(logits)
      return probs

    return logits

"""## Define the loss function and the optimizer

VAEs train by maximizing the evidence lower bound (ELBO) on the marginal log-likelihood:

$$\log p(x) \ge \text{ELBO} = \mathbb{E}_{q(z|x)}\left[\log \frac{p(x, z)}{q(z|x)}\right].$$

In practice, we optimize the single sample Monte Carlo estimate of this expectation:

$$\log p(x| z) + \log p(z) - \log q(z|x),$$
where $z$ is sampled from $q(z|x)$.

**Note**: we could also analytically compute the KL term, but here we incorporate all three terms in the Monte Carlo estimator for simplicity.
"""

optimizer = tf.keras.optimizers.Adam(1e-4)

def log_normal_pdf(sample, mean, logvar, raxis=1):
  log2pi = tf.math.log(2. * np.pi)
  return tf.reduce_sum(
      -.5 * ((sample - mean) ** 2. * tf.exp(-logvar) + logvar + log2pi),
      axis=raxis)

@tf.function
def compute_loss(model, x):
  mean, logvar = model.encode(x)
  z = model.reparameterize(mean, logvar)
  x_logit = model.decode(z)

  cross_ent = tf.nn.sigmoid_cross_entropy_with_logits(logits=x_logit, labels=x)
  logpx_z = -tf.reduce_sum(cross_ent, axis=[1, 2, 3])
  logpz = log_normal_pdf(z, 0., 0.)
  logqz_x = log_normal_pdf(z, mean, logvar)
  return -tf.reduce_mean(logpx_z + logpz - logqz_x)

@tf.function
def compute_apply_gradients(model, x, optimizer):
  with tf.GradientTape() as tape:
    loss = compute_loss(model, x)
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

"""## Training

* We start by iterating over the dataset
* During each iteration, we pass the image to the encoder to obtain a set of mean and log-variance parameters of the approximate posterior $q(z|x)$
* We then apply the *reparameterization trick* to sample from $q(z|x)$
* Finally, we pass the reparameterized samples to the decoder to obtain the logits of the generative distribution $p(x|z)$
* **Note:** Since we use the dataset loaded by keras with 60k datapoints in the training set and 10k datapoints in the test set, our resulting ELBO on the test set is slightly higher than reported results in the literature which uses dynamic binarization of Larochelle's MNIST.
"""

latent_dim = 16
num_examples_to_generate = 1

model = CVAE(latent_dim)

ckpt = tf.train.Checkpoint(step=tf.Variable(1), optimizer=optimizer, net=model)
manager = tf.train.CheckpointManager(ckpt, './tf_ckpts', max_to_keep=4)
ckpt.restore(manager.latest_checkpoint)
if manager.latest_checkpoint:
  print("Restored from {}".format(manager.latest_checkpoint))
else:
  print("Initializing from scratch.")

for epoch in range(1, epochs + 1):
  start_time = time.time()
  for train_x in train_dataset:
    compute_apply_gradients(model, train_x, optimizer)
  end_time = time.time()

  if epoch % 1 == 0:
    loss = tf.keras.metrics.Mean()
    for test_x in test_dataset:
      loss(compute_loss(model, test_x))
    elbo = -loss.result()
    display.clear_output(wait=False)
    print('Epoch: {}, Test set ELBO: {}, '
          'time elapse for current epoch {}'.format(epoch,
                                                    elbo,
                                                    end_time - start_time))

  ckpt.step.assign_add(1)
  if int(ckpt.step) % 10 == 0:
      save_path = manager.save()
      print("Saved checkpoint for step {}: {}".format(int(ckpt.step), save_path))


save_path = manager.save()
print("Saved checkpoint befor exit")`

As @AntoinePlumerault mentioned, I could solve the issue by changing this line,
`  cross_ent = tf.nn.sigmoid_cross_entropy_with_logits(logits=x_logit, labels=x)`

to this line,

`  cross_ent = tf.nn.sigmoid_cross_entropy_with_logits(logits=x_logit, labels=x+0.0)`

**Comment by kshitij-ingale** [comment] 2020-03-02 03:00
I'm facing similar issue, with tensorflow-gpu 2.0 release (installled inside docker). While training VAE with `tf.distribute.MirroredStrategy()` over 4 GPUs, I encounter this warning and the loss value shoots up to `inf` Following is the stdout (with logs showing training loss)
```
2020-03-02 02:53:44,396 INFO    : Batch 33, Training set loss: 332.27264404296875, batch size: 32
2020-03-02 02:53:50.188897: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: Size of values 0 does not match size of permutation 4.
2020-03-02 02:53:52,400 INFO    : Batch 34, Training set loss: inf, batch size: 30
```

**Comment by naturomics** [comment] 2020-07-01 09:49
Similar issue. Here is my solution. In my case the error was caused by the following code:
```
def _ndtr(self, x):
  # x is a tensor with shape [bs, height, width, channels]
  half_sqrt_2 = 0.5 * np.sqrt(2.)
  w = x * half_sqrt_2
  z = tf.abs(w)
  y = tf.where(z < half_sqrt_2, 1. + tf.math.erf(w), tf.where(w > 0., 2. - tf.math.erfc(z), tf.math.erfc(z)))
  return 0.5 * y
```
Which gives `layout failed: Invalid argument: Size of values 0 does not match size of permutation 4 @ fanin shape ingradient_tape/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer`.  

Looks like in the layout optimization stage tensors are transposed from NHWC to NCHW for performance, but some are failed.
So transposing it manually will solve:
```
def _ndtr(self, x):
  # x is a tensor with shape [bs, height, width, channels]
  x = tf.transpose(x, [0, 3, 1, 2])
  half_sqrt_2 = 0.5 * np.sqrt(2.)
  w = x * half_sqrt_2
  z = tf.abs(w)
  y = tf.where(z < half_sqrt_2, 1. + tf.math.erf(w), tf.where(w > 0., 2. - tf.math.erfc(z), tf.math.erfc(z)))
  y = tf.transpose(y, [0, 2, 3, 1])
  return 0.5 * y
```
The best solution is writing your model in NCHW format, so you can skip the layout optimization stage. [Here](https://web.stanford.edu/class/cs245/slides/TFGraphOptimizationsStanford.pdf) a tutorial on what tf does in graph optimization stage.

**Comment by YanSteph** [comment] 2023-08-04 14:26
This problem seems to come back on the latest TF versions.

**Comment by edumotya** [comment] 2023-08-28 11:10
Another workaround is to disable the `layout_optimizer` for the problematic layers. Following https://www.tensorflow.org/guide/graph_optimization, wrapping the problematic code block with `with options({"layout_optimizer": False}):` does the trick.

**Comment by stanlee321** [comment] 2024-03-01 03:43
I solve it using this workaround  in colab


```py
file_path = '/content/models/research/object_detection/model_main_tf2.py'

# Read the content of the file
with open(file_path, 'r') as file:
    content = file.readlines()



# Find the index of the import tensorflow line
import_line_index = next(i for i, line in enumerate(content) if 'import tensorflow' in line)

# Define the fix command to insert
fix_command = "tf.config.optimizer.set_experimental_options({'layout_optimizer': False})\n"

# Insert the fix command after the TensorFlow import
content.insert(import_line_index + 1, fix_command)


# Write the modified content back to the file
with open(file_path, 'w') as file:
    file.writelines(content)


```
