### ISSUE TITLE
@mihaimaruseac I'm working in colab and  changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error

### ISSUE THREAD

**Issue by 161019733305** [tensorflow/tensorflow#52936] opened 2021-11-04 09:59 UTC
@mihaimaruseac I'm working in colab and  changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error
`AttributeError: module 'tensorflow' has no attribute 'gfile'
`

_Originally posted by @mitramir55 in https://github.com/tensorflow/tensorflow/issues/31315#issuecomment-643277101_

**Comment by 161019733305** [comment] 2021-11-04 10:00
> @mihaimaruseac I'm working in colab and changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error `AttributeError: module 'tensorflow' has no attribute 'gfile' `
> 
> _Originally posted by @mitramir55 in [#31315 (comment)](https://github.com/tensorflow/tensorflow/issues/31315#issuecomment-643277101)_

I'm also getting the same ..how to figure it out?

**Comment by Saduf2019** [comment] 2021-11-04 11:33
@161019733305 
I tried https://www.tensorflow.org/io/tutorials/avro tutorial which shows tf.io.gfile.GFile usage example. I didn't see AttributeError raised. [also please fill in the issue template and share the tf version and verify the system requirements for compatibility issues]

schema = tf.io.gfile.GFile('train.avsc').read()

Perhaps you can confirm at your end. [please find the [gist](https://colab.research.google.com/gist/Saduf2019/343a29e9fa6b969520d959cb61ea7ea2/untitled.ipynb) for your reference]Thanks!

**Comment by mihaimaruseac** [comment] 2021-11-04 17:52
Duplicate of #31315 which is already resolved.

Please make sure you environment only uses packages that are build for TF 2.x

**Comment by mihaimaruseac** [comment] 2021-11-04 17:53
Sorry, misread. But please fill in issue template and provide a minimal reproducer

**Closed** 2021-11-23 07:46 UTC
Labels: stat:awaiting response, stalled
