### ISSUE TITLE
"Iterator::Model::Prefetch::Batch::Shuffle::ParallelInterleaveV2" returned OutOfRange without setting *end_of_sequence

### ISSUE THREAD

**Issue by devstein** [tensorflow/tensorflow#30141] opened 2019-06-25 17:24 UTC
See https://github.com/tensorflow/tensorflow/issues/29060#issuecomment-505539468 for more details 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX and Linux
- TensorFlow installed from (source or binary): `pipenv install --pre tensorflow==2.0.0-beta1`
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6.8

**Describe the current behavior**
I'm running into this issue when caching before `interleave`

```python
    filenames_dataset = filenames_dataset.cache("./some_path")

    return filenames_dataset.interleave(
        lambda f: map_file_to_xy_dataset(f, predict_task_fn, params),
        cycle_length=params[CYCLE_LENGTH_KEY],
        block_length=params[BLOCK_LENGTH_KEY],
        num_parallel_calls=tf.data.experimental.AUTOTUNE)
```

```
Iterator "Iterator::Model::Prefetch::Batch::Shuffle::ParallelInterleaveV2" returned OutOfRange without setting `*end_of_sequence`. This indicates that an error may have occurred. Original message: Attempting to call get_next after iteration should have finished. [Op:IteratorGetNextSync]
```

**Describe the expected behavior**

Able to cache the `filenames_dataset`

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

See above

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by aaudiber** [comment] 2019-06-25 20:59
Thank you for reporting this @devstein. I am able to reproduce the problem with the below code:

```python
  import tensorflow as tf

  tf.enable_v2_behavior()

  ds = tf.data.Dataset.range(5)
  ds = ds.cache('/tmp/cache_dir' )
  ds = ds.interleave(
      lambda f: tf.data.Dataset.range(f),
      cycle_length=2, num_parallel_calls=1)
  ds = ds.repeat(2)

  for e in ds:
    tf.print(e)
```

I'm looking into the root cause and will message back when I have a fix.

**Comment by aaudiber** [comment] 2019-06-25 21:44
The issue is related to using parallel interleave. As a temporary workaround, try leaving `num_parallel_calls` unset.

**Comment by devstein** [comment] 2019-06-25 22:18
@aaudiber Appreciate the quick response, I'll try that workaround for now.

**Comment by aaudiber** [comment] 2019-06-28 15:38
The fix is merged to master in https://github.com/tensorflow/tensorflow/commit/3398e887f5daa1e22c59eaa1c6f5ca731698ad2f

**Closed** 2019-06-28 15:40 UTC

**Comment by devstein** [comment] 2019-06-28 21:41
@aaudiber Thanks!
