### ISSUE TITLE
Cannot load saved model with tf.keras.models.load_model

### ISSUE THREAD

**Issue by bdzyubak** [tensorflow/tensorflow#31853] opened 2019-08-21 18:29 UTC
**System information**
- Wrote custom code for simple model
- Ubuntu 16.04.6 LTS
- Tensorflow 2.0.0-beta1 installed from binary using pip
- Python 3.7, no CUDA or GPU

Loading a saved model results in error: 
__init__() got an unexpected keyword argument 'reduction'

**Code to reproduce the issue**

```
model = tf.keras.Model(inputs=[input_x], outputs=[logits])
loss = tf.keras.losses.MeanSquaredError()
model.compile(optimizer=tf.keras.optimizers.Adam(),  # Optimizer
              # Loss function to minimize; Emphasize not getting false positives with pos_weight
              loss=loss, # tf.nn.weighted_cross_entropy_with_logits(logits,labels,pos_weight=1) # tf.keras.losses.MeanSquaredError()
              # tf.keras.losses.mean_squared_error
              # List of metrics to monitor
              metrics=[tf.keras.losses.MeanSquaredError()])
checkpointer = tf.keras.callbacks.ModelCheckpoint(session_name + '_backup.h5', save_best_only=True, monitor = 'acc', verbose = 0)
early_stopper = tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=3, verbose=1,min_delta=0.005)
history = model.fit(data_train, roi_zoom_train,
                    batch_size=batch_size,
                    epochs = 1,
                    # We pass some validation for
                    # monitoring validation loss and metrics
                    # at the end of each epoch
                    validation_data=(data_val, roi_zoom_val),callbacks=[checkpointer,early_stopper]) #
model.save(session_name + '.h5')
model = tf.keras.models.load_model(session_name + '.h5')
```

**Other info / logs**
Traceback (most recent call last):
  File "/home/m047659/Programs/pycharm/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 137, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    training_config, custom_objects))
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 458, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 320, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1735, in _cache_output_metric_attributes
    metrics, self.output_names, output_shapes, self.loss_functions)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 755, in collect_per_output_metric_info
    metric_name = get_metric_name(metric, is_weighted)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 929, in get_metric_name
    metric = metrics_module.get(metric)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 2833, in get
    return deserialize(identifier)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 2827, in deserialize
    printable_module_name='metric function')
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 451, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'reduction'

**Comment by ravikyram** [comment] 2019-08-22 11:18
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks!

**Comment by ravikyram** [comment] 2019-08-29 08:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-29 08:02 UTC
Labels: TF 2.0.0-beta0, comp:keras, stat:awaiting response, type:support
