### ISSUE TITLE
Jupyter notebook from `tensorflow/tensorflow:nightly-py3-jupyter` won't authenticate its own token

### ISSUE THREAD

**Issue by rakshitraj** [tensorflow/tensorflow#33062] opened 2019-10-05 03:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- TensorFlow installed from (source or binary): ` docker pull tensorflow/tensorflow:nightly-py3-jupyter`
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:n/a
- GPU model and memory: n/a

* Tensorflow 1.14 installed on system via `conda install tensorflow`; using docker container because needed a higher version without disturbing the system installation*

**Describe the current behavior**
![Screenshot from 2019-10-05 08-08-27](https://user-images.githubusercontent.com/31768189/66248857-65ea6600-e749-11e9-8d75-22dca6cf6129.png)

The jupyter notebook that comes bundled with `tensorflow/tensorflow:nightly-py3-jupyter` docker image won't authenticate its own token

**Describe the expected behavior**

Jupyter notebook should authenticate its own token.

**Code to reproduce the issue**

``` bash
$ docker pull tensorflow/tensorflow:nightly-py3-jupyter
$ docker run -u $(id -u):$(id -u) -it -p 10001:10001 tensorflow/tensorflow:nightly-py3-jupyter
```

**Other info / logs**

```
________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


You are running this container as user with ID 1000 and group 1000,
which should map to the ID and group for your user on the Docker host. Great!

[I 02:35:18.648 NotebookApp] Writing notebook server cookie secret to /.local/share/jupyter/runtime/notebook_cookie_secret
/usr/local/lib/python3.6/dist-packages/IPython/paths.py:68: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
[I 02:35:18.817 NotebookApp] Serving notebooks from local directory: /tf
[I 02:35:18.818 NotebookApp] The Jupyter Notebook is running at:
[I 02:35:18.818 NotebookApp] http://82fe909436a2:8888/?token=508ff9f2b673ebcc134e67f6c21f539659cc74b659fceeb1
[I 02:35:18.818 NotebookApp]  or http://127.0.0.1:8888/?token=508ff9f2b673ebcc134e67f6c21f539659cc74b659fceeb1
[I 02:35:18.818 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:35:18.822 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///.local/share/jupyter/runtime/nbserver-1-open.html
    Or copy and paste one of these URLs:
        http://82fe909436a2:8888/?token=508ff9f2b673ebcc134e67f6c21f539659cc74b659fceeb1
     or http://127.0.0.1:8888/?token=508ff9f2b673ebcc134e67f6c21f539659cc74b659fceeb1
```

**Comment by rakshitraj** [comment] 2019-10-07 10:52
Initially I got this

```bash
raxit@mBox:~$ docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-py3-jupyter

docker: Error response from daemon: driver failed programming external connectivity on endpoint confident_keller (4f284434a00f2fbdf9d7fec344acf2b33f333c2f41e5e097f254b81c4560f32b): Error starting userland proxy: listen tcp 0.0.0.0:8888: bind: address already in use.

```
Then I went ahead and tried this

```bash
sudo kill `sudo lsof -t -i:8888`  # to free up the port
```
and viola
![Screenshot from 2019-10-07 16-20-10](https://user-images.githubusercontent.com/31768189/66306069-5ec88100-e91e-11e9-9f48-fd909174abbb.png)
It works!

BTW could you tell me why it didn't work the first time. I was using it on a free port, I made sure of that using `netstat -an`

Thanks a lot!

**Comment by mbenezra** [comment] 2019-10-07 11:02
I have exactly the same issue.

**Comment by gadagashwini** [comment] 2019-10-07 11:41
@rakshitraj,
Glad it worked.
Initial error might be because your jupyter notebook is already in use or you tried to connect jupyter notebook on different terminal. You can restart the system or kill the existing port to free the port. Thanks!

**Comment by gadagashwini** [comment] 2019-10-07 11:43
@mbenezra, Can you please post a new issue by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

**Comment by gadagashwini** [comment] 2019-10-07 11:44
Closing this issue since its resolved. Thanks!

**Closed by gadagashwini** 2019-10-07 11:44 UTC
Labels: TF 1.14, stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by mbenezra** [comment] 2019-10-07 11:58
> @mbenezra, Can you please post a new issue by providing the information asked by the template?
> The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-py3-jupyter works for me now.
