### ISSUE TITLE
ValueError: Variable <tf.Variable 'basic_nstepTD_1/noisy_dense/bias:0' shape=(3,) dtype=float32> has `None` for gradient.

### ISSUE THREAD

**Issue by Huixxi** [tensorflow/tensorflow#32729] opened 2019-09-23 14:15 UTC
I am trying to implement a self-defined noisy-layer, when I put the `add` operator in the `build` function
```python 
self.kernel = self.weight_mu + self.weight_sigma * self.weights_eps
self.bias = self.bias_mu + self.bias_sigma * self.bias_eps
```
, it will raise the error that  ` ValueError: Variable <tf.Variable 'basic_nstepTD_1/noisy_dense/bias:0' shape=(3,) dtype=float32> has 'None' for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.`  But when I put that two-line code into the `call` function, the error is disappeared.  
My code:
```python
class NoisyDense(kl.Layer):
    def __init__(self, units, std_init=0.5):
        super().__init__()
        self.units = units
        self.std_init = std_init

    def build(self, input_shape):
        self.reset_noise(input_shape[-1])
        mu_range = 1 / np.sqrt(input_shape[-1])
        mu_initializer = tf.random_uniform_initializer(-mu_range, mu_range)
        sigma_initializer = tf.constant_initializer(self.std_init / np.sqrt(self.units))

        self.weight_mu = tf.Variable(initial_value=mu_initializer(shape=(input_shape[-1], self.units), dtype='float32'),
                                     trainable=True)

        self.weight_sigma = tf.Variable(initial_value=sigma_initializer(shape=(input_shape[-1], self.units), dtype='float32'),
                                        trainable=True)

        self.bias_mu = tf.Variable(initial_value=mu_initializer(shape=(self.units,), dtype='float32'),
                                     trainable=True)

        self.bias_sigma = tf.Variable(initial_value=sigma_initializer(shape=(self.units,), dtype='float32'),
                                        trainable=True)

        self.kernel = self.weight_mu + self.weight_sigma * self.weights_eps
        self.bias = self.bias_mu + self.bias_sigma * self.bias_eps

    def call(self, inputs):
        # output = tf.tensordot(inputs, self.kernel, 1)
        # tf.nn.bias_add(output, self.bias)
        # return output
        # self.kernel = self.weight_mu + self.weight_sigma * self.weights_eps
        # self.bias = self.bias_mu + self.bias_sigma * self.bias_eps
        return tf.matmul(inputs, self.kernel) + self.bias

    def _scale_noise(self, dim):
        noise = tf.random.normal([dim])
        return tf.sign(noise) * tf.sqrt(tf.abs(noise))

    def reset_noise(self, input_shape):
        eps_in = self._scale_noise(input_shape)
        eps_out = self._scale_noise(self.units)
        self.weights_eps = tf.multiply(tf.expand_dims(eps_in, 1), eps_out)
        self.bias_eps = eps_out
```

**Comment by Huixxi** [comment] 2019-09-23 14:16
So, how can I define mu own `initializer` in tensorflow 2.0?

**Comment by ravikyram** [comment] 2019-09-24 08:07
@Huixxi 
Looks like code is incomplete. In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-09 12:42
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2019-10-10 11:33
@Huixxi 
Can you help us with minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by Huixxi** [comment] 2019-10-13 11:30
> @Huixxi
> Looks like code is incomplete. In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

Sorry for late reply, It still an issue, I've the reason but I don't know. The details are updated in the mainbody of that issue.

**Comment by ravikyram** [comment] 2019-10-17 04:05
@Huixxi 
I tried to reproduce the issue in colab using TF 2.0 .But i feel code is incomplete. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/a1a3199a71c49429923e563b5452eada/untitled277.ipynb). Please, help us in reproducing the issue, then it is easy for localizing the issue faster. Thanks again.!

**Comment by Huixxi** [comment] 2019-10-18 02:58
I've update the code, here
<https://colab.research.google.com/gist/Huixxi/5dc9af1e4d3d4f4253de9e6312ee194d/untitled277.ipynb>

**Comment by rmothukuru** [comment] 2019-10-18 12:01
@Huixxi,
You have commented saying, 

> But when I put that two-line code into the call function, the error is disappeared. 

But in the [Gist](https://colab.sandbox.google.com/gist/Huixxi/5dc9af1e4d3d4f4253de9e6312ee194d/untitled277.ipynb#scrollTo=nJIgyw1Tt3Xy) which you have provided, there is no error even when the `Two Line Code` is commented in the `Call` function. 

Can you please help us reproduce the error. Thanks!

**Comment by Huixxi** [comment] 2019-10-20 08:44
Sorry, maybe I made a mistake in my former statement, it's not *Error*, it
is *Warning*, which means the is no gradient pass through my *weights*, so
that I can not train or update the weight parameters, and that is what I
understand, when you put the two line in the build function, you can see
that right? It will raise abundant of Warnings, you will see the output
just run the code in the Gist I provided, *However*, the error will appear.
when I remove the two-line code in the *build function, *line 47, 48, and
add them to* call function*, those warnings will disappear.
Thanks. Regards

**Comment by gowthamkpr** [comment] 2019-10-24 21:30
@Huixxi 
 
The build method is called when the model containing the layer is built. This is where you set up the weights of the layer. The input_shape is accepted as an argument to the function.

The call method defines the computations performed on the input. The function accepts the input tensor as its argument and returns the output tensor after applying the required operations.

So, this is the reason why there are no gradients passing through the weights.

For more indepth expanation please read the following [doc](https://www.saama.com/blog/deep-learning-diaries-building-custom-layers-in-keras/)

**Comment by gowthamkpr** [comment] 2019-10-28 21:00
@Huixxi Closing this issue as it has been answered. Please add additional comments and we can open this issue again. Thanks!

**Closed by gowthamkpr** 2019-10-28 21:00 UTC
Labels: TF 2.0, comp:ops, stat:awaiting response, type:support
