### ISSUE TITLE
WARNING: Entity <method-wrapper '__call__' of weakref object...

### ISSUE THREAD

**Issue by sergii-bond** [tensorflow/tensorflow#27004] opened 2019-03-21 20:40 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): one line modification to official [colab checkpoints.ipynb](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/guide/checkpoints.ipynb)
- Tensorflow version: 2.0.0-alpha0

**Describe the current behavior**
After the model has been loaded from a checkpoint, the following messages appear:
```
W0321 20:29:37.423420 139748586436480 tf_logging.py:161] Entity <method-wrapper '__call__' of weakref object at 0x7f197ec58278> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Object conversion is not yet supported. If you are trying to convert code that uses an existing object, try including the creation of that object in the conversion. For example, instead of converting the method of a class, try converting the entire class instead. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/README.md#using-the-functional-api for more information.
W0321 20:29:37.434415 139748586436480 tf_logging.py:161] Entity <method-wrapper '__call__' of weakref object at 0x7f197ebfad68> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Object conversion is not yet supported. If you are trying to convert code that uses an existing object, try including the creation of that object in the conversion. For example, instead of converting the method of a class, try converting the entire class instead. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/README.md#using-the-functional-api for more information.
WARNING: Entity <method-wrapper '__call__' of weakref object at 0x7f197ec58278> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Object conversion is not yet supported. If you are trying to convert code that uses an existing object, try including the creation of that object in the conversion. For example, instead of converting the method of a class, try converting the entire class instead. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/README.md#using-the-functional-api for more information.
WARNING: Entity <method-wrapper '__call__' of weakref object at 0x7f197ebfad68> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Object conversion is not yet supported. If you are trying to convert code that uses an existing object, try including the creation of that object in the conversion. For example, instead of converting the method of a class, try converting the entire class instead. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/README.md#using-the-functional-api for more information.
```

**Describe the expected behavior**
No warning messages.

**Code to reproduce the issue**
Decorate `def call` with `@tf.function` in the second cell of the notebook:
```
class Net(tf.keras.Model):
  """A simple linear model."""

  def __init__(self):
    super(Net, self).__init__()
    self.l1 = tf.keras.layers.Dense(5)

  @tf.function
  def call(self, x):
    return self.l1(x)
```

**Comment by blaueck** [comment] 2019-03-22 16:28
I met the same problem with the following code running second time. It can be fixed by uncomment the line "fc(x)". So I think is related to the restoration of Checkpoint.
```python
import tensorflow as tf
from tensorflow.python import keras

@tf.function
def forward(net, x):
    return net(x)

x = tf.random.normal([10, 10])
fc = keras.layers.Dense(100)

cp = tf.train.Checkpoint(fc=fc)
cp.restore(tf.train.latest_checkpoint('log/test_cp'))

# fc(x)
y = forward(fc, x)

cp.save('log/test_cp/haha')
```

**Comment by mdanatg** [comment] 2019-03-22 21:41
Yes, it happens when restoring from check points, although the root cause is unrelated.

The issue should be fixed in the nightly build by #1003.

**Closed by mdanatg** 2019-03-22 21:41 UTC
Labels: 2.0.0-alpha0, comp:autograph, stat:awaiting tensorflower, type:bug/performance

**Comment by xiaohu2015** [comment] 2019-05-15 11:18
I have meet the same trouble, why? @mdanatg

**Comment by mdanatg** [comment] 2019-05-15 11:35
@xiaohu2015 The alpha preview is fairly outdated. Are you seeing the issue even if you `pip install tf-nightly-2.0-preview`?

**Comment by xiaohu2015** [comment] 2019-05-15 12:25
> @xiaohu2015 The alpha preview is fairly outdated. Are you seeing the issue even if you `pip install tf-nightly-2.0-preview`?

I built tensorflow-2.0 from source, maybe I need try the new.

**Comment by mdanatg** [comment] 2019-05-15 12:46
It's worth checking the git revision of your repo. If the source you are building from is at head, then this might be a regression.
