### ISSUE TITLE
'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'ravel'

### ISSUE THREAD

**Issue by indexraja** [tensorflow/tensorflow#35933] opened 2020-01-16 11:29 UTC
I am using tensorflow 2.1

    `def`` generate_sequence(epoch_num, initial_index, seq_length):
    with open(os.path.join(data_directory, charIndex_json)) as f:
        char_to_index = json.load(f)
    index_to_char = {i:ch for ch, i in char_to_index.items()}
    unique_chars = len(index_to_char)
    
    model = make_model(unique_chars)
    model.load_weights(model_weights_directory + "Weights_{}.h5".format(epoch_num))
     
    sequence_index = [initial_index]
    
    for _ in range(seq_length):
        batch = np.zeros((1, 1))
        batch[0, 0] = sequence_index[-1]
        
        predicted_probs = model.predict_on_batch(batch).ravel()
        sample = np.random.choice(range(unique_chars), size = 1, p = predicted_probs)
        
        sequence_index.append(sample[0])
    
    seq = ''.join(index_to_char[c] for c in sequence_index)
    
    cnt = 0
    for i in seq:
        cnt += 1
        if i == "\n":
            break
    seq1 = seq[cnt:]
    #above code is for ignoring the starting string of a generated sequence. This is because we are passing any arbitrary 
    #character to the model for generating music. Now, the model start generating sequence from that character itself which we 
    #have passed, so first few characters before "\n" contains meaningless word. Model start generating the music rhythm from
    #next line onwards. The correct sequence it start generating from next line onwards which we are considering.
    
    cnt = 0
    for i in seq1:
        cnt += 1
        if i == "\n" and seq1[cnt] == "\n":
            break
    seq2 = seq1[:cnt]
    #Now our data contains three newline characters after every tune. So, the model has leart that too. So, above code is used for
    #ignoring all the characters that model has generated after three new line characters. So, here we are considering only one
    #tune of music at a time and finally we are returning it..
    
    return seq2

error :

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-1c976bcea2e8> in <module>
      3 ln = int(input("\n3. Enter the length of music sequence you want to generate. Typical number is between 300-600. Too small number will generate hardly generate any sequence: "))
      4 
----> 5 music = generate_sequence(ep, ar, ln)
      6 
      7 print("\nMUSIC SEQUENCE GENERATED: \n")

<ipython-input-47-a1565ba804d1> in generate_sequence(epoch_num, initial_index, seq_length)
     14         batch[0, 0] = sequence_index[-1]
     15 
---> 16         predicted_probs = model.predict_on_batch(batch).ravel()
     17         sample = np.random.choice(range(unique_chars), size = 1, p = predicted_probs)
     18 

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'ravel'

**Comment by ravikyram** [comment] 2020-01-17 08:39
@indexraja 

I have tried on colab with TF version 2.1.0-rc2 . I am seeing the below error.
`NameError: name 'make_model' is not defined`
Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-01-30 10:10
@indexraja 

Any update on this issue please. Thanks!

**Comment by tufnica** [comment] 2020-02-06 22:59
try this: 
np.squeeze(model.predict_on_batch(batch))

btw. model.predict_on_batch should return numpy -> ravel should work . 
but if input mismatch or model  arch is wrong he will raise error

**Comment by ravikyram** [comment] 2020-02-20 10:45
@indexraja

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-02-28 11:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-28 11:46 UTC
Labels: TF 2.1, stat:awaiting response, type:support
