### ISSUE TITLE
TensorFlow 1.8 Issues with GPU availability always returns false

### ISSUE THREAD

**Issue by rajkpammi** [tensorflow/tensorflow#37058] opened 2020-02-25 18:55 UTC
Hi,

I have been facing issues lately with getting tensorflow to use GPU, I have setup a jupyterhub application on AWS cloud with a P3 type Instance which has cuda and drivers installed also tensorflow python packages, but whenever i check the gpu availability tensorflow returns False

Here is the version information  below:

Nvidia Driver Version: 396.26
CUDA Version 9.2.88
CUDNN_VERSION 7.1.4
Tensorflow : 1.8.0
Tensorflow_gpu : 1.8.0

Here is the compatibility list from Tensorflow website which doesn't point out the cuda and cudnn minor versions only major version https://www.tensorflow.org/install/source#linux

Can someone please help me with this issue, Thanks in advance!

**Comment by ravikyram** [comment] 2020-02-26 09:56
@rajkpammi 
Can you try with this command to know Tensorflow-GPU availability
tf.config.list_physical_devices('GPU').Looks like duplicate of #37059. Thanks!

**Comment by ravikyram** [comment] 2020-03-06 10:33
@rajkpammi 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-03-20 10:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-03-20 10:29 UTC
Labels: comp:gpu, stat:awaiting response, type:support
