### ISSUE TITLE
Bug: issue initializing iterator

### ISSUE THREAD

**Issue by eilifsolberg** [tensorflow/tensorflow#23334] opened 2018-10-28 21:14 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
 Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
Version: v1.11.0-0-gc19e29306c 1.11.0
 **Python version**:
3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
See source code below

### Describe the problem
There seems to be an issue initializing an iterator created with `tf.data.Iterator.form_structure` a second time in the _same_ session where the dataset contains `Function` instances.

### Source code / logs
To produce problem
```python
import tensorflow as tf

def g():
  for i in range(10):
    yield i

iterator = tf.data.Iterator.from_structure(tf.int64, tf.TensorShape([]))
x = iterator.get_next()
sess = tf.Session()

dataset_1 = tf.data.Dataset.from_generator(g, output_types=tf.int64)
sess.run(iterator.make_initializer(dataset_1))
sess.run(x)

dataset_2 = tf.data.Dataset.from_generator(g, output_types=tf.int64)
sess.run(iterator.make_initializer(dataset_2))
sess.run(x)
```
Executing the above leads to the following error
```
NotFoundError (see above for traceback): Function tf_data_structured_function_wrapper_uv0gphzJzQY is not defined.
```

**Comment by ahatamiz** [comment] 2018-10-28 22:01
It seems fine when I run your code. Can you try again and provide more information?

**Comment by eilifsolberg** [comment] 2018-10-29 20:30
See updated version. The previous example worked for me when I used e.g. version 1.10. The updated example fails for me for both version 1.10 and 1.11.

**Comment by mrry** [comment] 2018-11-11 23:38
This does appear to be a bug in the latest version. One workaround is to ensure that all calls to `make_initializer()` have been made before creating the `tf.Session`. For example, the following program should work as intended:

```python
import tensorflow as tf

def g():
  for i in range(10):
    yield i

iterator = tf.data.Iterator.from_structure(tf.int64, tf.TensorShape([]))
x = iterator.get_next()

dataset_1 = tf.data.Dataset.from_generator(g, output_types=tf.int64)
dataset_2 = tf.data.Dataset.from_generator(g, output_types=tf.int64)

init_1 = iterator.make_initializer(dataset_1)
init_2 = iterator.make_initializer(dataset_2)

with tf.Session() as sess:
  sess.run(init_1)
  print sess.run(x)

  sess.run(init_2)
  print sess.run(x)
```

**Comment by mrry** [comment] 2018-11-13 15:20
Update: we have a fix for this case, and it's currently pending review.

**Comment by eilifsolberg** [comment] 2018-11-13 20:48
Ok, thanks!

**Closed** 2018-11-14 20:05 UTC
Labels: comp:data, stat:awaiting tensorflower, type:bug/performance
