### ISSUE TITLE
tf.data.Dataset data remain as tensor even after sess.run()?

### ISSUE THREAD

**Issue by dragon28** [tensorflow/tensorflow#21619] opened 2018-08-15 02:14 UTC
Hello Professional Tensorflow Developers,

I apologize if I am making a noob mistake over here. But my finding about the data that remain in the tf.data.Dataset remain as tensor even after sess.run(). Below are the source code:

```

import matplotlib.pyplot as plt
from scipy import misc
import numpy as np
from skimage import exposure
from math import ceil
import tensorflow as tf
import math
import glob
import collections
import re
from pathlib import Path
from PIL import Image
from skimage import data, img_as_float, io, img_as_uint
from skimage._shared._warnings import expected_warnings
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OneHotEncoder
print("Tensorflow version " + tf.__version__)

import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

tf.set_random_seed(0)



int_list = [0,1,2,3,4,5,6,7,8,9]

lb = LabelBinarizer()



def parse_function(data_list):

	print("data_list: ", data_list,"\n")

	print("tf.print: ", tf.Print(data_list, [data_list]),"\n")

	graph1 = tf.Graph()
	
	with graph1.as_default():
		x = tf.placeholder(tf.int32)
		y = x * 1
		#z = tf.Variable(data_list)

	print("x: ", x, "\n")
	#print("z: ", z, "\n")	

	#sess = tf.InteractiveSession()

	#with sess.as_default():
	with tf.Session() as sess:
		sess.run(tf.global_variables_initializer())
		#sess.run(tf.local_variables_initializer())
		#tf.global_variables_initializer().run()
		#tf.local_variables_initializer().run()
		#tf.tables_initializer().run()
		
		#feed = {x: sess.run(tf.data_list)}
		#feed = {x: data_list}
		
		#data = sess.run(data_list)
		
		#print("data: ", data,"\n")
		#print("feed: ", feed, "\n")

		print("tf.print: ", tf.Print(data_list, [data_list]),"\n")
	        
                print("sess.run(data_list): ", sess.run(data_list), "\n")

		#label_eval = sess.run(y, feed_dict=feed)
		#label_eval = sess.run(z)
		#label_eval = sess.run(data_list)

		#print("x: ", x, "\n")

		#label_eval = x.eval()
		#print("label_eval: ", label_eval,"\n")
		#one_hot_label = tf.one_hot(label, 10) #no issue
		#one_hot_label = lb.fit_transform(label_eval)
		#print("one_hot_label: ", one_hot_label, "\n")

	sess.close()

	#return one_hot_label

int_list = tf.convert_to_tensor(int_list, dtype=tf.float32)

int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))

int_dataset = int_dataset.batch(100)

int_iterator = int_dataset.make_initializable_iterator()

int_iterator = train_iterator.get_next()
```

The error output:

```
Tensorflow version 1.8.0
2018-08-15 10:09:18.992919: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
data_list:  Tensor("arg0:0", shape=(), dtype=float32) 

tf.print:  Tensor("Print:0", shape=(), dtype=float32) 

x:  Tensor("Placeholder:0", dtype=int32) 

tf.print:  Tensor("Print_1:0", shape=(), dtype=float32) 

Traceback (most recent call last):
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 282, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3669, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("arg0:0", shape=(), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tf_dataset.py", line 93, in <module>
    int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1804, in tf_map_func
    ret = map_func(nested_args)
  File "./tf_dataset.py", line 93, in <lambda>
    int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))
  File "./tf_dataset.py", line 72, in parse_function
    print("sess.run(data_list): ", sess.run(data_list), "\n")
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 253, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 289, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'arg0:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("arg0:0", shape=(), dtype=float32) is not an element of this graph.)
```

pip list:
```
pip3 list
Package                       Version               
----------------------------- ----------------------
absl-py                       0.2.2                 
aiohttp                       2.2.5                 
aniso8601                     1.3.0                 
apturl                        0.5.2                 
asn1crypto                    0.23.0                
astor                         0.6.2                 
async-timeout                 2.0.0                 
attrs                         17.3.0                
Automat                       0.6.0                 
base58                        0.2.5                 
beautifulsoup4                4.6.0                 
behave                        1.2.5                 
BigchainDB                    1.2.0.dev0            
bigchaindb-driver             0.4.0                 
bleach                        1.5.0                 
blinker                       1.3                   
Brlapi                        0.6.4                 
cached-property               1.3.0                 
certifi                       2017.7.27.1           
cffi                          1.11.2                
chardet                       3.0.4                 
checkbox-support              0.22                  
click                         6.7                   
cloudpickle                   0.5.3                 
command-not-found             0.3                   
constantly                    15.1.0                
cryptoconditions              0.6.0.dev1            
cryptography                  2.1.3                 
cssselect                     1.0.1                 
cycler                        0.10.0                
dask                          0.18.1                
decorator                     4.1.2                 
defer                         1.0.6                 
docker                        2.5.1                 
docker-compose                1.16.1                
docker-pycreds                0.2.1                 
dockerpty                     0.4.1                 
docopt                        0.6.2                 
dpkt                          1.9.1                 
enum34                        1.1.6                 
feedparser                    5.1.3                 
Flask                         0.12.2                
Flask-Cors                    3.0.3                 
Flask-RESTful                 0.3.6                 
gast                          0.2.0                 
grpcio                        1.13.0                
guacamole                     0.9.2                 
gunicorn                      19.7.1                
h5py                          2.8.0                 
html5lib                      0.9999999             
httplib2                      0.9.1                 
hyperlink                     17.3.1                
hypothesis                    3.18.5                
hypothesis-regex              0.2                   
idna                          2.6                   
incremental                   17.5.0                
itsdangerous                  0.24                  
Jinja2                        2.9.6                 
jsonschema                    2.5.1                 
Keras                         2.2.0                 
Keras-Applications            1.0.2                 
Keras-Preprocessing           1.0.1                 
language-selector             0.1                   
logstats                      0.2.1                 
louis                         2.6.4                 
lxml                          4.1.1                 
Mako                          1.0.3                 
Markdown                      2.6.11                
MarkupSafe                    1.0                   
matplotlib                    2.0.2                 
multidict                     3.3.0                 
multipipes                    0.1.0                 
networkx                      1.11                  
nose                          1.3.7                 
numpy                         1.14.0                
oauthlib                      1.0.3                 
olefile                       0.44                  
onboard                       1.2.0                 
padme                         1.1.1                 
parse                         1.8.2                 
parse-type                    0.3.4                 
parsel                        1.2.0                 
pexpect                       4.0.1                 
Pillow                        5.2.0                 
pip                           10.0.1                
plainbox                      0.25                  
protobuf                      3.5.1                 
psutil                        5.3.0                 
ptyprocess                    0.5                   
py                            1.4.34                
pyasn1                        0.4.2                 
pyasn1-modules                0.2.1                 
pycparser                     2.18                  
pycups                        1.9.73                
pycurl                        7.43.0                
PyDispatcher                  2.0.5                 
Pygments                      2.2.0                 
pygobject                     3.20.0                
PyJWT                         1.3.0                 
pymongo                       3.5.1                 
PyNaCl                        1.1.2                 
pyOpenSSL                     17.4.0                
pyparsing                     2.2.0                 
pysha3                        1.0.2                 
pytest                        3.2.3                 
pytest-mock                   1.6.3                 
python-apt                    1.1.0b1+ubuntu0.16.4.2
python-dateutil               2.6.1                 
python-debian                 0.1.27                
python-rapidjson              0.0.11                
python-rapidjson-schema       0.1.1                 
python-systemd                231                   
pytz                          2017.2                
PyWavelets                    0.5.2                 
pyxdg                         0.25                  
PyYAML                        3.12                  
queuelib                      1.4.2                 
reportlab                     3.3.0                 
requests                      2.18.4                
rethinkdb                     2.3.0.post6           
scikit-image                  0.14.0                
scikit-learn                  0.19.0                
scipy                         0.19.1                
Scrapy                        1.4.0                 
selenium                      3.7.0                 
service-identity              17.0.0                
sessioninstaller              0.0.0                 
setuptools                    38.4.0                
six                           1.11.0                
statsd                        3.2.1                 
system-service                0.3                   
tensorboard                   1.8.0                 
tensorflow                    1.8.0                 
tensorflow-tensorboard        0.4.0                 
termcolor                     1.1.0                 
texttable                     0.9.1                 
toolz                         0.9.0                 
tornado                       4.5.2                 
Twisted                       17.9.0                
ubuntu-drivers-common         0.0.0                 
ufw                           0.35                  
unattended-upgrades           0.1                   
unity-scope-calculator        0.1                   
unity-scope-chromiumbookmarks 0.1                   
unity-scope-colourlovers      0.1                   
unity-scope-devhelp           0.1                   
unity-scope-firefoxbookmarks  0.1                   
unity-scope-gdrive            0.7                   
unity-scope-manpages          0.1                   
unity-scope-openclipart       0.1                   
unity-scope-texdoc            0.1                   
unity-scope-tomboy            0.1                   
unity-scope-virtualbox        0.1                   
unity-scope-yelp              0.1                   
unity-scope-zotero            0.1                   
urllib3                       1.22                  
usb-creator                   0.3.0                 
w3lib                         1.18.0                
websocket-client              0.44.0                
Werkzeug                      0.14.1                
wheel                         0.30.0                
xdiagnose                     3.8.4.1               
xkit                          0.0.0                 
XlsxWriter                    0.7.3                 
yarl                          0.13.0                
zope.interface                4.4.3 
```          

I am using Ubuntu 16.04 64 Bits, Python 3.5.2 and tensorflow 1.8.0

Additional information:

Have I written custom code

No

OS Platform and Distribution

Linux OS Ubuntu 16.04 x64 

TensorFlow installed from

Tensorflow 1.8.0 CPU only version install from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0rc1-cp35-cp35m-linux_x86_64.whl

Bazel version

n/a

CUDA/cuDNN version

n/a

GPU model and memory

n/a due to I am using CPU only version

Exact command to reproduce

Please execute my source code which mentioned above

Mobile device

n/a due to I am using PC not mobile device

Thanks

**Comment by tensorflowbutler** [comment] 2018-08-15 13:03
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by dragon28** [comment] 2018-08-15 14:37
I have updated the original post

**Comment by dragon28** [comment] 2018-08-16 04:42
Ok, I updated the source code to:

```
import matplotlib.pyplot as plt
from scipy import misc
import numpy as np
from skimage import exposure
from math import ceil
import tensorflow as tf
import math
import glob
import collections
import re
from pathlib import Path
from PIL import Image
from skimage import data, img_as_float, io, img_as_uint
from skimage._shared._warnings import expected_warnings
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OneHotEncoder
print("Tensorflow version " + tf.__version__)

import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

tf.set_random_seed(0)



int_list = [0,1,2,3,4,5,6,7,8,9]

lb = LabelBinarizer()


print("int_list: ", int_list, "\n")

def parse_function(data_list):

	print("data_list: ", data_list,"\n")

	print("tf.print: ", tf.Print(data_list, [data_list]),"\n")

	print("x: ", x, "\n")
	
	with tf.Session() as sess:
		
		sess.run(tf.global_variables_initializer())
		sess.run(tf.local_variables_initializer())

		print("tf.print: ", tf.Print(data_list, [data_list]),"\n")

		print("sess.run(data_list): ", sess.run(data_list), "\n")


	sess.close()

	#return one_hot_label

int_list = tf.convert_to_tensor(int_list, dtype=tf.float32)

int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))

int_dataset = int_dataset.batch(100)

int_iterator = int_dataset.make_initializable_iterator()

int_iterator = train_iterator.get_next()
```
Output:

```
Tensorflow version 1.8.0
int_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

2018-08-16 12:36:46.385121: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
data_list:  Tensor("arg0:0", shape=(), dtype=float32) 

tf.print:  Tensor("Print:0", shape=(), dtype=float32) 

x:  Tensor("Placeholder:0", dtype=float32) 

tf.print:  Tensor("Print_1:0", shape=(), dtype=float32) 

Traceback (most recent call last):
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'arg0' with dtype float
	 [[Node: arg0 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tf_dataset.py", line 103, in <module>
    int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1804, in tf_map_func
    ret = map_func(nested_args)
  File "./tf_dataset.py", line 103, in <lambda>
    int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))
  File "./tf_dataset.py", line 83, in parse_function
    print("sess.run(data_list): ", sess.run(data_list), "\n")
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'arg0' with dtype float
	 [[Node: arg0 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'arg0', defined at:
  File "./tf_dataset.py", line 103, in <module>
    int_dataset = tf.data.Dataset.from_tensor_slices(int_list).map(lambda z: parse_function(z))
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 332, in _create_definition_if_needed_impl
    argholder = array_ops.placeholder(argtype, name=argname)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4848, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 686, in create_op
    **kwargs)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/dragon/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'arg0' with dtype float
	 [[Node: arg0 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
I still gave me an error but was a different type of error.

I am not sure what happen at the tf.data.Dataset.from_tensor_slices(int_list) whereby it turned the int_list into tensor object or tensor tensor? I still puzzled that I am unable to convert the tensor inside the tf.data.Dataset into numpy array by using both tf.session.run() or tensor.eval(session=tf.session()).

Thanks

**Comment by rachellim** [comment] 2018-08-16 17:07
In eager mode (which you turned on with `tf.enable_eager_execution`), variables are initialized as soon as they are created, so you don't need `global_variables_initializer` and `local_variables_initializer`, and you should not create a `Session` at all.

You also need not explicitly create an iterator for datasets in eager mode. In eager, you can iterate over datasets as follows: 

```
for x in int_dataset:
  print(x)
```

Check out the [eager execution guide](https://www.tensorflow.org/guide/eager) on the tensorflow website for more information.

(Note that even in non-eager mode, you should never create a `Session` in a tf.data map function!). 

Our error message here in tf.data could have been more helpful, and I'll look into how we can improve it.

**Comment by alextp** [comment] 2018-08-16 17:08
I don't think the code you pasted gave the error you pasted because the last iteration of the code has no placeholders.

In general you are not supposed to create a tensorflow session inside a python function which is supposed to be building a graph (and functions passed to Dataset.map are supposed to build graphs).

It might be easier for you to take a step back and describe what you're trying to achieve here (specially because your parse_function isn't actually doing any parsing).

Answering your question, tf.data.Dataset.from_tensor_slices returns a Dataset, not a tensor. A Dataset is an object from which you can build iterators and other datasets (using tools like map and friends). The iterators you build from a dataset have an op which you can run to get a tensor.

Please refer to the documentation in [tf.data](https://www.tensorflow.org/guide/datasets) or [one of Derek's talks on the subject](https://www.youtube.com/watch?v=uIcqeP7MFH0).

For now I'm closing this issue since I do not think it's a bug in tf.

**Closed by alextp** 2018-08-16 17:08 UTC
Labels: stat:awaiting response
