### ISSUE TITLE
Deterministic GPU implementation of unsorted segment reduction op not available on Windows

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#54276] opened 2022-02-04 19:29 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 21H2
- TensorFlow installed from (source or binary): from PyPI
- TensorFlow version (use command below): v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: 3.10.2
- CUDA/cuDNN version: 11.2, 8.1.1
- GPU model and memory: GeForce RTX 2060

**Describe the current behavior**
The code below works on Linux, but not on Windows where I am seeing

> tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:
> Detected at node 'UnsortedSegmentSum_1' defined at (most recent call last):
> Node: 'UnsortedSegmentSum_1'
> Deterministic GPU implementation of unsorted segment reduction op not available.
>          [[{{node UnsortedSegmentSum_1}}]] [Op:__inference_train_function_517]

**Describe the expected behavior**
It works on both OSs.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
tf.random.set_seed(0)
tf.config.experimental.enable_op_determinism()
data = tf.ones((1, 1))
layer = tf.keras.layers.Input(shape=[1])
model = tf.keras.models.Model(inputs=layer, outputs=layer)
model.compile(loss="categorical_crossentropy", metrics="AUC")
model.fit(x=data, y=data)
```

This is due to the `AUC` metric as discussed in https://github.com/tensorflow/tensorflow/issues/51978. It was resolved for Linux, but not Windows in https://github.com/tensorflow/tensorflow/pull/51861. A workaround is given by `set TF_DISABLE_SEGMENT_REDUCTION_OP_DETERMINISM_EXCEPTIONS=True`. I am posting a new issue here as recommended in https://github.com/tensorflow/tensorflow/issues/39751#issuecomment-982919265.

**Comment by reedwm** [comment] 2022-02-05 01:41
@benbarsdell, do you know why the kernels had to be disabled on Windows, and how hard it would be to enable them for Windows?

/CC @duncanriach

**Comment by mohantym** [comment] 2022-02-07 04:28
Hi @bersbersbers ! Did not get any error either in [Colab ](https://colab.sandbox.google.com/gist/mohantym/1989e72f47d012c552fc953e0912c019/github_54276.ipynb#scrollTo=koYvPob1U-i9) or windows 20H2. Could you try again with following code in Windows 21H2 and let us know?  Thanks!
```
import tensorflow as tf
tf.keras.utils.set_random_seed(1)
tf.config.experimental.enable_op_determinism()
data = tf.ones((1, 1))
layer = tf.keras.layers.Input(shape=[1])
model = tf.keras.models.Model(inputs=layer, outputs=layer)
model.compile(loss="CategoricalCrossentropy", metrics="AUC")
model.fit(x=data, y=data)
```

**Comment by bersbersbers** [comment] 2022-02-07 05:10
Colab is running on Linux, I guess, it which case it won't reproduce there because it doesn't reproduce on Linux.

When you try to reproduce on Windows, are you sure you are using GPU acceleration? Because it doesn't reproduce on a CPU.

**Comment by benbarsdell** [comment] 2022-02-07 05:25
The issue we ran into is described here:
https://github.com/tensorflow/tensorflow/blob/92b294f/tensorflow/core/kernels/segment_reduction_ops_gpu_0.cu.cc#L97-L103

**Comment by reedwm** [comment] 2022-02-07 23:40
I can reproduce on a Windows VM, where I can edit and quickly get a build error. The error is:

```
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(4558): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(5323): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(5428): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(5525): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(5530): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
C:\Users\kbuilder\AppData\Local\Temp\nvcc_inter_files_tmp_dir\tmpmapuno6t\segment_reduction_ops_gpu_0.cu.cudafe1.stub.c(5567): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
```

Opening the file on the first file, the specified line, 4558, is:

```
__cudaLaunch(((char *)((void ( *)(_ZN10tensorflow12CastIteratorINS_13AlignedVectorIdLi16EEES2_idE10IteratorTyE,  _ZN10tensorflow13AlignedVectorIdLi16EEE *, const int *, const int *, int,  _ZN10tensorflow7functor3SumE, _ZN3cub2IfILb0EN10tensorflow13AlignedVectorIdLi16EEES3_E4TypeE))cub::DeviceSegmentedReduceKernel< ::cub::DeviceReducePolicy< ::tensorflow::AlignedVector<double, (int)16> ,  ::tensorflow::AlignedVector<double, (int)16> , int,  ::tensorflow::functor::Sum> ::Policy600,  ::cub::TransformInputIterator< ::tensorflow::AlignedVector<double, (int)16> ,  ::tensorflow::LookupAndScaleAndCastInputsFunctor< ::tensorflow::AlignedVector<double, (int)16> ,  ::tensorflow::AlignedVector<double, (int)16> , int, double> ,  ::cub::CountingInputIterator<int, long long> , long long> ,  ::tensorflow::AlignedVector<double, (int)16>  *, const int *, int,  ::tensorflow::functor::Sum,  ::tensorflow::AlignedVector<double, (int)16> > )));
```

Looks like your comment is correct: the line above references both AlignedVector and cub. Any advice on how to fix? I don't have time to spend very long on this unfortunately, so we may have to leave this unfixed.

**Comment by reedwm** [comment] 2022-02-08 03:50
So I was able to fix the error by changing [this line](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/util/gpu_kernel_helper.h;l=329;drc=0d53fe6214d99fc8ab85cfc45bb02b8d1fbf3411) to not instantiate `Functor<16>`, giving a max value of 8 on Windows. But I got several other errors, such as:

```
.\tensorflow/core/util/gpu_kernel_helper.h(259): error: more than one operator "*=" matches these operands:
            function "Eigen::complex_operator_detail::operator*=(std::complex<float> &, const std::complex<float> &)"
            function "std::complex<float>::operator*=(const std::complex<float> &)"
            operand types are: tensorflow::complex64 *= const tensorflow::complex64
          detected during:
            instantiation of "tensorflow::AlignedVector<T, N> &tensorflow::AlignedVector<T, N>::operator*=(const tensorflow::AlignedVector<T, N> &) [with T=tensorflow::complex64, N=8]"
.\tensorflow/core/kernels/segment_reduction_ops_gpu.cu.h(460): here
```

and

```
.\tensorflow/core/util/gpu_kernel_helper.h(288): error: no instance of overloaded function "tensorflow::max" matches the argument list
            argument types are: (const int, const int)
          detected during instantiation of class "tensorflow::AlignedVector<T, N> [with T=int, N=8]"
```

The first seems like a legitimate error: I don't why why eigen is redefining `operator*=` on complex numbers. I'm confused by the second, as I cannot find any `tensorflow::max` function at all, so I'm not sure why it's not simply using the CUDA max function.

Unfortunately, I don't have more time to work on this.

**Comment by wangpengmit** [comment] 2022-03-08 02:48
@reedwm @benbarsdell I don't have context for this problem.

Is `SparseSegmentReductionFunctor` only used after `tf.config.experimental.enable_op_determinism()` is called?

**Comment by gadagashwini** [comment] 2022-08-30 07:09
Hi @benbarsdell, Can we move this issue to closed state, If it was  resolved. Thank you!

**Comment by andreped** [comment] 2022-09-24 19:14
> Hi @benbarsdell, Can we move this issue to closed state, If it was resolved. Thank you!

@gadagashwini I don't think it was resolved. I am experiencing the same issue on Windows with TensorFlow 2.10.0. Works fine on CPU though, but same issue on GPU as described above. Any simple fix for this?

**Closed** 2022-09-29 02:45 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:core, TF 2.8
