### ISSUE TITLE
Python3.11 support please

### ISSUE THREAD

**Issue by blackPantherOS** [tensorflow/tensorflow#57805] opened 2022-09-22 18:30 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

blackPanther OS

### Python version

3.11

### Bazel version

5.3.1

### GCC/Compiler version

11.2.1

### Current Behaviour?

```shell
A bug happened!
Build fail with Python 3.11
```

### Standalone code to reproduce the issue

```shell
Standalone code from git
```

### Relevant log output

```shell
/tensorflow/python/BUILD:398:27: Compiling tensorflow/python/lite/toco_python_api_wrapper.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 47 arguments skipped)
In file included from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/cast.h:16,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/attr.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h:13,
                 from tensorflow/python/lite/toco_python_api_wrapper.cc:19:
bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/detail/type_caster_base.h: In function 'std::string pybind11::detail::error_string()':
bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type 'PyFrameObject' {aka 'struct _frame'}
  482 |             frame = frame->f_back;
      |                          ^~
In file included from bazel-out/k8-opt/bin/external/local_config_python/python_include/Python.h:42,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/detail/common.h:186,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pytypes.h:12,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/cast.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/attr.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h:13,
                 from tensorflow/python/lite/toco_python_api_wrapper.cc:19:
bazel-out/k8-opt/bin/external/local_config_python/python_include/pytypedefs.h:22:16: note: forward declaration of 'PyFrameObject' {aka 'struct _frame'}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
In file included from bazel-out/k8-opt/bin/external/local_config_python/python_include/tupleobject.h:39,
                 from bazel-out/k8-opt/bin/external/local_config_python/python_include/Python.h:59,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/detail/common.h:186,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pytypes.h:12,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/cast.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/attr.h:13,
                 from bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h:13,
                 from tensorflow/python/lite/toco_python_api_wrapper.cc:19:
bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h: In function 'pybind11::function pybind11::detail::get_type_override(const void*, const pybind11::detail::type_info*, const char*)':
bazel-out/k8-opt/bin/external/pybind11/_virtual_includes/pybind11/pybind11/pybind11.h:2348:54: error: 'PyCodeObject' {aka 'struct PyCodeObject'} has no member named 'co_varnames'; did you mean 'co_names'?
 2348 |                     locals, PyTuple_GET_ITEM(f_code->co_varnames, 0)
      |                                                      ^~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.900s, Critical Path: 6.54s
INFO: 111 processes: 11 internal, 100 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by tilakrayal** [comment] 2022-09-23 06:44
@blackPantherOS,
Every TensorFlow release is compatible with a certain version. The latest stable tensorflow **v2.10** was compatible with python **v3.7-3.10**. Could you please have a look at the [compatible](https://www.tensorflow.org/install/source_windows#tested_build_configurations) tested build configurations as well. Thank you!

**Comment by mihaimaruseac** [comment] 2022-10-17 16:56
Closing as duplicate of #58032 (later issue, but with more content and fewer bots)

**Closed by mihaimaruseac** 2022-10-17 16:56 UTC
Labels: type:build/install, type:support, TF 2.10

**Comment by kaique-ryan-santos-chagas** [comment] 2022-12-30 20:03
I have the same problem when i try to install the tensorflow on Python 3.11 project. 

![image](https://user-images.githubusercontent.com/59677362/210108006-6e8a740f-1d98-425a-a90e-9ea596385c50.png)

**Comment by mihaimaruseac** [comment] 2022-12-30 21:56
@kaique-ryan-santos-chagas please see discussion at #58032.
