### ISSUE TITLE
using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

### ISSUE THREAD

**Issue by happpyosu** [tensorflow/tensorflow#35403] opened 2019-12-25 07:25 UTC
something is wrong when I use model.get_layer(),
I was confused what's wrong with my code, and I have never used a `tf.Tensor` as a Python `bool` in my code

Here are my code:
------------------------------------
```python
import tensorflow as tf
from tensorflow.keras import layers

def seq(k):
    result = tf.keras.Sequential(name='seq'+str(k))
    result.add(tf.keras.layers.Conv2D(64, (3, 3), strides=2, padding='same', use_bias=False))
    result.add(tf.keras.layers.BatchNormalization(name='bn_'+str(k)))
    result.add(tf.keras.layers.GaussianNoise(stddev=1, name='noise_'+str(k)))
    result.add(tf.keras.layers.ReLU())

    return result


def testModel():
    input_layer = layers.Input(shape=(256, 256, 3))
    l0 = seq(0)(input_layer)
    l1 = seq(1)(l0)
    l2 = seq(2)(l1)
    model = tf.keras.Model(input_layer, l2)
    return model


if __name__ == '__main__':
    model = testModel()
    model.summary()
    seq0 = model.get_layer('seq_0')
    bn0 = seq0.get_layer('bn_0').output
    noise0 = seq0.get_layer('noise_0').output

    sub0 = tf.keras.layers.Subtract()([noise0, bn0])

    new_model = tf.keras.Model(model.input, [sub0, model.output])

    test_tensor = tf.ones(shape=(1, 256, 256, 3))

    (out, z) = new_model(test_tensor)
```
----------------------------------------------------------------
2019-12-25 15:15:54.403715: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Traceback (most recent call last):
  File "/home/chenhao-gpu/PycharmProjects/GAN/test.py", line 36, in <module>
    (out, z) = new_model(test_tensor)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 517, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1201, in cond
    if pred:
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 765, in __bool__
    self._disallow_bool_casting()
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 534, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Comment by ravikyram** [comment] 2019-12-26 05:42
@happpyosu 

Which version of TensorFlow you are using?.Can you please provide colab link or reproducible code with proper indentation. It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment] 2020-01-10 10:59
@happpyosu 

Any update on this issue please. Thanks!

**Comment by happpyosu** [comment] 2020-01-11 03:36
@ravikyram 
Sorry for the late reply. I am using Tensorflow-gpu==2.0.0. 
I was building a model with tf.keras API and met the problem. First of all, I define a  Sequential model as:
```python
import tensorflow as tf
from tensorflow.keras import layers

def seq_model(k):
    model = tf.keras.Sequential(name='seq_'+str(k))
    model.add(layers.Conv2D(64, (3, 3), strides=2, padding='same', use_bias=False))
    model.add(layers.BatchNormalization(name='bn_'+str(k)))
    model.add(layers.GaussianNoise(stddev=1, name='noise_'+str(k)))
    model.add(layers.ReLU())

    return model
```
Then I made another model by using the seq_model:
```python
def mymodel():
    input = tf.keras.Input(shape=(224, 224, 3))

    s0 = seq_model(k=0)(input)
    s1 = seq_model(k=1)(s0)
    s2 = seq_model(k=2)(s1)

    return tf.keras.Model(input, s2)
```
Then I try to use the API model.get_layer() to get the output of the layer named "noise_0" and "bn_0"
```python
model = mymodel()
noise_0 = model.get_layer('seq_0').get_layer('noise_0').output
bn_0 = model.get_layer('seq_0').get_layer('bn_0').output
```
Since I want to get the noise value added by "noise_0" layer, I build a new Subtract layer, and put the output of the Substrat layer into a new model:

```python
sub_0 = layers.Subtract()([noise_0, bn_0])
new_model = tf.keras.Model(model.input, [model.output, sub_0])
```
It is still no problem until here, however, if I call the new_model, an exception raised:
```python
test_tensor = tf.zeros(shape=(1, 224, 224, 3))
out_of_new_model = new_model(test_tensor, training=True)
```
The terminal output:
```python
Traceback (most recent call last):
  File "/home/chenhao-gpu/PycharmProjects/GAN/test.py", line 35, in <module>
    out_of_new_model = new_model(test_tensor, training=True)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 517, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1201, in cond
    if pred:
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 765, in __bool__
    self._disallow_bool_casting()
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 534, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/home/chenhao-gpu/anaconda3/envs/tf2s/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

Process finished with exit code 1
```
I am confused whether I correctly used the API model.get_layers().

**Comment by ravikyram** [comment] 2020-01-17 10:38
@happpyosu 
Can you please try with `!pip install tensorflow-gpu==2.1-rc2`and see if the error still persists. I am not seeing any issue with TF 2.1.Thanks!

**Comment by ravikyram** [comment] 2020-01-30 09:51
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by ravikyram** 2020-01-30 09:51 UTC
Labels: TF 2.0, comp:keras, comp:ops, stat:awaiting response, type:support

**Comment by happpyosu** [comment] 2020-02-03 15:11
Thanks, it works after updating to tf2.1

**Comment by mtdot** [comment] 2020-07-09 06:27
Hello, I met this issue with the code bellow (my tensorflow version is 2.2.0), any suggestion?

```
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

import os

os.chdir(r"F:\My\ML\eat_tensorflow2_in_30_days-master\eat")

BATCH_SIZE = 100


def load_image(img_path, size=(32, 32)):
    label = tf.constant(1, tf.int8) if tf.strings.regex_full_match(img_path, ".*automobile.*") \
        else tf.constant(0, tf.int8)
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img)  # In jpeg format
    img = tf.image.resize(img, size) / 255.0
    return img, label


# Parallel pre-processing using num_parallel_calls and caching data with prefetch function to improve the performance
ds_train = tf.data.Dataset.list_files("../data/cifar2/train/*/*.jpg") \
    .map(load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE) \
    .shuffle(buffer_size=1000).batch(BATCH_SIZE) \
    .prefetch(tf.data.experimental.AUTOTUNE)

ds_test = tf.data.Dataset.list_files("../data/cifar2/test/*/*.jpg") \
    .map(load_image) \
    .batch(BATCH_SIZE) \
    .prefetch(tf.data.experimental.AUTOTUNE)

```
