### ISSUE TITLE
Offer TensorFlow Docker Images Based on 18.04

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#19363] opened 2018-05-17 23:10 UTC
Nvidia is now shipping docker images based on ubuntu 18.04 ([see](https://github.com/NVIDIA/nvidia-docker/issues/666#issuecomment-390039509)), it would be great if TensorFlow started offering builds against these.

Ubuntu 18.04 has added Python 3.6.
```
Have I written custom code N/A
OS Platform and Distribution Docker
TensorFlow installed from Docker
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A
```

**Comment by tensorflowbutler** [comment] 2018-05-18 06:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment] 2018-05-21 18:14
@gunan Thoughts on this?

@cancan101 Please feel free to submit a PR for this.

**Comment by gunan** [comment] 2018-05-21 23:17
For CPU, I do not see a reason why we cannot.
For GPU, we are strictly required to build on top of nvidia cuda docker images.
So If nvidia/cuda has ubuntu 18.04, it is certainly possible for us, too.

**Comment by cancan101** [comment] 2018-05-22 19:13
I started: https://github.com/tensorflow/tensorflow/pull/19474

**Comment by tensorflowbutler** [comment] 2018-06-06 18:52
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-06-21 18:56
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by angersson** [comment] 2018-08-01 21:58
I've recently proposed a change to TensorFlow that obsoletes parameterized_docker_build.sh, which may help alleviate this issue. If anyone following this thread is interested in making TensorFlow's Dockerfile story better for everyone, [please take a look at the RFC](https://github.com/tensorflow/community/pull/8).

**Comment by tarmath** [comment] 2020-05-06 17:32
looks like current images are based on ubuntu 18.04:

    $ docker run --rm -it 
    docker.apple.com/tensorflow/tensorflow:2.1.0-gpu-py3 bash

    root@7468b22afb64:/# cat /etc/issue
    Ubuntu 18.04.3 LTS \n \l

seems like this issue can be closed...

**Comment by yongtang** [comment] 2020-05-06 17:41
Close this issue as it has been solved.

**Closed by yongtang** 2020-05-06 17:41 UTC
Labels: stat:contributions welcome, type:build/install
