### ISSUE TITLE
Go TensorFlow 1.15.0: DataType 20 is not supported

### ISSUE THREAD

**Issue by hamdimuzakkiy** [tensorflow/tensorflow#35352] opened 2019-12-23 08:17 UTC
**System information**

- OS Platform and Distribution : mcOS HighSierra Version 10.13.2
- TensorFlow version: 1.15.0

Tried to load model from python (TF 2) on my go (TF 1.15.0) and i got error when accessing the value of the result. The error message I got was:

`panic: BUG: Please report at https://github.com/tensorflow/tensorflow/issues with the note: Go TensorFlow 1.15.0: DataType 20 is not supported (see https://www.tensorflow.org/code/tensorflow/core/framework/types.proto)`

is there any solution for this?

**Comment by ravikyram** [comment] 2019-12-24 05:58
@hamdimuzakkiy 
Request you to provide simple standalone code to reproduce the issue in our environment. It helps in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-07 12:34
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-01-08 04:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-01-08 04:55 UTC
Labels: TF 1.15, comp:apis, stat:awaiting response, type:support
