### ISSUE TITLE
Can't install on ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by anjishnu** [tensorflow/tensorflow#53] opened 2015-11-10 00:26 UTC
I am running into an error while trying to install tensor flow on Ubuntu.

> $  sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

> Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (10.9Mb): 10.9Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-nulCWJ-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

>  File "<string>", line 14, in <module>

>IOError: [Errno 2] No such file or directory: '/tmp/pip-nulCWJ-build/setup.py'

> ----------------------------------------
> Command python setup.py egg_info failed with error code 1

**Comment by anjishnu** [comment] 2015-11-10 07:50
The issue was solved by updating to the latest version of pip - however I'm getting a new error.

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17 not found

**Comment by jendap** [comment] 2015-11-10 09:48
Yes, latest pip solves the first part. But the libc.so is bigger problem. It is non trivial hacks to give the one app newer glibc than the system one.

You may try recompile it on your system. But it may take some effort just to compile bazel, you will not have java8, nor newer versions of numpy nor anything else... Is upgrading to at least 14.04 LTS realy not an option for you?

**Comment by ninjin** [comment] 2015-11-10 12:27
I am sadly also in a similar situation trying to deploy on a nation-wide GPU cluster which is really the only access to GPUs that my research group has.  We have a module system that can give us access to plenty of modern tooling, but I only have access to glibc 2.12.  Installing binary bazel releases fail since they depend on glibc 2.14 and I have also been unable to build bazel 0.1.0/0.1.1/HEAD from scratch due to compilation errors.  For now I have given up on making TensorFlow work on the cluster [pending the issue I filed with bazel](https://github.com/bazelbuild/bazel/issues/583).

**Comment by evanthebouncy** [comment] 2015-11-10 15:46
welp... time for 14.04 I guess

**Comment by jendap** [comment] 2015-11-10 18:31
Upgrading ubuntu is definitely the best way to go. But if not...

I would not upgrade the system libc.so on the shared cluster. It should be backward compatible but there are regression here and there. You can still make it work if you want to. If you grep libc from newer package [http://packages.ubuntu.com/trusty/libc6] (click on amd64). You can extract that deb. Then you can use LD_PRELOAD the files from content directory. See something like [https://rafalcieslak.wordpress.com/2013/04/02/dynamic-linker-tricks-using-ld_preload-to-cheat-inject-features-and-investigate-programs/] or [http://stackoverflow.com/questions/5223971/question-about-overriding-c-standard-library-functions-and-how-to-link-everythin].

Libc has pretty much no dependencies but kernel. I believe tensorflow does not need anything fancy new there. Newer libc in custom directory and LD_PRELOAD trick should allow you to run the bazel binaries from download as well as the tensorflow pip (you may not need to recompile anymore). Good for shared cluster with old system.

BTW: Google / bazel philosophy is to rebuild everything from sources (that's why bazel download so many git repos). That also means there are very little external dependencies. But yes, it depends on libc.

**Comment by vinodrajendran001** [comment] 2015-11-12 19:04
I don't have sudo permission, so updating or installing GLIBC is not possible. I tried extracting libc6 from debian package and set the path in LD_PRELOAD but it's not using that instead it always point to **/lib64/libc.so.6**(ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found) but my LD_PRELOAD is defined as **/home/hpc/pr63so/ga93yih2/lib/libc.so.6**

**Comment by initproc** [comment] 2015-11-13 08:46
Does anyone who solve this?
I use cent os 6.x and it's glibc version is under the 2.12.

```
(tensorflow)[dev-srv /home/user/tensorflow]# yum info glibc
Loaded plugins: fastestmirror, security
Determining fastest mirrors
Installed Packages
Name        : glibc
Arch        : i686
Version     : 2.12
```

I download glibc-2.17-78.el7.x86_64.rpm in the Internet and uncompress rpm to /opt/tensorflow/glibc diretory.
```
(tensorflow)[dev-srv /home/user/tensorflow]# ls /opt/tensorflow/glibc/lib64/
ld-2.17.so               libanl-2.17.so   libcidn.so.1      libm-2.17.so           libnss_compat.so.2  libnss_files-2.17.so   libnss_nis.so.2         libresolv-2.17.so    libthread_db.so.1
ld-linux-x86-64.so.2     libanl.so.1      libcrypt-2.17.so  libm.so.6              libnss_db-2.17.so   libnss_files.so.2      libnss_nisplus-2.17.so  libresolv.so.2       libutil-2.17.so
libBrokenLocale-2.17.so  libc-2.17.so     libcrypt.so.1     libnsl-2.17.so         libnss_db.so.2      libnss_hesiod-2.17.so  libnss_nisplus.so.2     librt-2.17.so        libutil.so.1
libBrokenLocale.so.1     libc.so.6        libdl-2.17.so     libnsl.so.1            libnss_dns-2.17.so  libnss_hesiod.so.2     libpthread-2.17.so      librt.so.1           rtkaio
libSegFault.so           libcidn-2.17.so  libdl.so.2        libnss_compat-2.17.so  libnss_dns.so.2     libnss_nis-2.17.so     libpthread.so.0         libthread_db-1.0.so
```

Finally, I ran convolutional.py with LD_PRELOAD or LD_LIBRARY_PATH option and those neither helpful. Here is an error message.
```
(tensorflow)[dev-srv /home/irteam/tensorflow]# LD_PRELOAD=/opt/tensorflow/glibc/lib64/libc.so.6 python ./lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
python: relocation error: /opt/tensorflow/glibc/lib64/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

(tensorflow)[dev-srv /home/user/tensorflow]# LD_LIBRARY_PATH=/opt/tensorflow/glibc/lib64 python ./lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
python: relocation error: /opt/tensorflow/glibc/lib64/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

Does anyone who really solve this issue?

**Comment by vinodrajendran001** [comment] 2015-11-13 08:59
I am also eagerly waiting for a solution

**Comment by blacknes** [comment] 2015-11-13 09:11
I use OS X to install tensorflow, it's succeed,but when I use python to write first program,I find some error, who can help me?
there is error message:
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Library/Python/2.7/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py", line 59, in <module>
    import six.moves.copyreg as copyreg
ImportError: No module named copyreg

**Comment by initproc** [comment] 2015-11-13 09:33
In addition, even loading both libc.so.6 and ld-linux-x86-64.so.2 doesn't work.
```
(tensorflow)[dev-srv /home/user/tensorflow]# LD_PRELOAD="/opt/tensorflow/glibc/lib64/libc.so.6 /opt/tensorflow/glibc/lib64/ld-linux-x86-64.so.2" python ./lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
Segmentation fault
```

**Comment by vrv** [comment] 2015-11-13 22:25
I think we do require glibc >2.17 at the moment. Closing for now but if someone has a solution for earlier versions, would be great to have it here.  Thanks!

**Closed by vrv** 2015-11-13 22:25 UTC

**Comment by vinodrajendran001** [comment] 2015-12-07 16:16
Anyone able to find a solution for it ?

**Comment by anjishnu** [comment] 2015-12-12 03:38
Managed to get it to build from source. 

Overview of how to do it.
Install Bazel - (but not the latest version, because it apparently fails to compile tensorflow according to a ticket I saw there)
I used Build label: 0.1.1

Update pip, install wheels and setuptools
Check out tensorflow's latest version, modify tensorflow/tensorflow.bzl file

 def tf_extension_linkopts():
-  return []  # No extension link opts
+  return ["-lrt"]  # No extension link opts

Then build according to the instructions on the source build page:
Also, on the instructions page (http://tensorflow.org/get_started/os_setup.md#installing_from_sources) you will see these three commands, but you have to add —config=cuda, like so:

Create the pip package and install
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
# The name of the .whl file will depend on your platform.
$ pip install /tmp/tensorflow_pkg/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

**Comment by vinodrajendran001** [comment] 2015-12-14 13:30
My problem lies with old GLIBC version(2.11.3), and I tried installing bazel for which it requires a GLIBC version 2.14 or greater.

Any other solution?
Note: I can't update GLIBC version, because I am using a cluster system and naturally am not given a admin privileges.

**Comment by MrXiaoWan** [comment] 2015-12-27 16:31
I have this problem just now！Here maybe help you ！！ My system is ubuntu 12.04
Reference Linking：http://stackoverflow.com/questions/33655731/error-while-importing-tensorflow-in-python2-7-in-ubuntu-12-04-glibc-2-17-not-f

$ sudo pip install --upgrade virtualenv
$ virtualenv --system-site-packages ~/tensorflow
$ cd ~/tensorflow
$ source bin/activate
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
$ cd /tmp
$ wget http://launchpadlibrarian.net/137699828/libc6_2.17-0ubuntu5_amd64.deb
$ wget http://launchpadlibrarian.net/137699829/libc6-dev_2.17-0ubuntu5_amd64.deb
$ mkdir libc6_2.17
$ cd libc6_2.17
$ ar p libc6_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
$ ar p libc6-dev_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
$ cd -
$ LD_LIBRARY_PATH=/tmp/libc6_2.17/lib/x86_64-linux-gnu/ /tmp/libc6_2.17/lib/x86_64-linux-gnu/ld-2.17.so bin/python local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py

**Comment by vinodrajendran001** [comment] 2015-12-27 16:46
This may work for local pc but not for clusters or for those who don't have admin privileges.

**Comment by vodp** [comment] 2016-01-04 13:35
You can install virtualenv locally:
`pip install virtualenv --user`. My problem is that the installation of tensorflow in virtualenv encounters `maximum recursion depth exceeded`:
```
        self.finalize_options()
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 825, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 837, in obtain
        return installer(requirement)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 272, in fetch_build_egg
        dist = self.__class__({'script_args':['easy_install']})
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 579, in resolve
        env = Environment(self.entries)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 748, in __init__
        self.scan(search_path)
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 777, in scan
        for dist in find_distributions(item):
      File "/home/phong/.local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 1702, in find_distributions
        importer = get_importer(path_item)
      File "/usr/lib/python2.7/pkgutil.py", line 394, in get_importer
        importer = ImpImporter(path_item)
    RuntimeError: maximum recursion depth exceeded
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-E19HDw/numpy
```

**Comment by ttrouill** [comment] 2016-01-20 13:49
I managed to have it running on a CentOS 6.7 without being admin, two solutions : http://stackoverflow.com/a/34897674/1990516 
http://stackoverflow.com/a/34900471/1990516
:)

**Comment by i3v** [comment] 2016-12-07 12:54
I [was able](https://github.com/tensorflow/tensorflow/issues/110#issuecomment-265431453) to build bazel-0.4.1 and tensorflow-0.12.0rc0 from source, on CentOS 6.5, without having root privileges. And it seem to work OK with glibc 2.12, without any LD_LIBRARY_PATH or LD_PRELOAD tricks. [Editing](https://github.com/tensorflow/tensorflow/issues/53#issuecomment-164105922) `tensorflow/tensorflow.bzl` is one of the options (but it might be not the only thing to do), but, personally, for me it was simpler to do the same thing in "[gpu/CROSSTOOL.tpl#L59](https://github.com/leelabcnbc/DevOps/blob/master/Docker/tensorflow/0.10.0/centos6/py35/gpu/CROSSTOOL.tpl#L59)".

**Comment by chandu8542** [comment] 2017-03-17 11:18
For those facing glib problem, switch keras config file to use Theano instead of Tensorflow. I did that and it solved my problem.

**Comment by wilderfield** [comment] 2017-04-04 21:50
I am facing similar problems. I am trying to run TensorFlow at work, on my RHEL 6.8 box. IT will not let us use package managers, and we cannot upgrade the bundled python, or gcc.
I tried to get around this by installing Python 2.7, TensorFlow, and latest GCC locally on the box in /scratch
I update LD_LIBRARY_PATH to point to my own copy of GCC shared libraries. It seems that tensorflow does not care about LD_LIBRARY_PATH, and it is searching in /lib64/libc.so.6 for GLIBC_2.16

**Comment by chandu8542** [comment] 2017-04-05 01:57
You need to update glibc or update Ubuntu to 14.04. It will work like charm.

**Comment by empty16** [comment] 2017-11-26 01:11
Hey, guys. Here are the solutions.
`mkdir ~/glibc
cd ~/glibc 

wget http://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
tar zxvf glibc-2.23.tar.gz
cd glibc-2.23
mkdir build
cd build

../configure --prefix=/opt/glibc-2.23
make -j4
sudo make install

export LD_LIBRARY_PATH=/opt/glibc-2.23/lib`
https://github.com/mind/wheels/issues/7

**Comment by cdancette** [comment] 2018-02-13 11:31
`conda install tensorflow` works for me

**Comment by concinntyTurtle** [comment] 2018-03-29 14:04
`conda install tensorflow` works for me too

**Comment by qiaofeiw** [comment] 2018-04-06 04:04
conda install tensorflow work for me too!!!

**Comment by TheMoakMan** [comment] 2019-03-01 19:06
> `conda install tensorflow` and life is easy

I've tried conda install tensorflow and I'm still getting the same issue. GLIBC 2.17 not found.
