### ISSUE TITLE
estimator saving eval metrics to /eval_0 not /eval

### ISSUE THREAD

**Issue by amm385** [tensorflow/tensorflow#25272] opened 2019-01-29 03:12 UTC
I decided to give early stopping a shot with [stop_if_no_decrease_hook](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/stop_if_no_decrease_hook) but after tweaking the params and making sure the hook was actually being triggered, discovered an oddity with my estimator. 

The hook reads eval data from the directory[ specified by estimator.eval_dir()](https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/early_stopping.py#L391) which in this case pops out "trained_models/rcnn_inception_v2/eval". This looks all good until I check my actual directory structure and find that /eval doesn't exist. Instead, I have eval_0/ (containing the proper logs) with no other directories in the rcnn_inception_v2/ folder.

I'm curious why eval_0/ is being created instead of eval/ when I've done nothing special to specify this directory. And importantly on top of that, why does estimator.eval_dir() return the wrong directory?

**Comment by jvishnuvardhan** [comment] 2019-01-30 00:02
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Github is mainly for addressing bugs in installation and performance. Thanks!

**Comment by amm385** [comment] 2019-01-30 00:22
ok will do, I thought this might be a bug with estimator.eval_dir, so thought it might be of interest here as well. go ahead and close out if you think that's appropriate

**Comment by jvishnuvardhan** [comment] 2019-01-30 17:00
@amm385 Could you post a code to reproduce the bug? Also, could you fill the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-02-06 23:24
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-02-06 23:24 UTC
Labels: type:support
