### ISSUE TITLE
Different results from scipy imread and tensorflow decode_jpeg

### ISSUE THREAD

**Issue by HaaPut** [tensorflow/tensorflow#11623] opened 2017-07-19 20:45 UTC
### Problem Description
Image decoded using decode_jpeg from tensor flow is visually similar, but numerically different from one returned by scipy imread.

**Minimal Example**:
```
import numpy as np
import scipy
import tensorflow as tf
def minimal_example():
    #image_source = 'https://upload.wikimedia.org/wikipedia/commons/8/88/Astronaut-EVA.jpg'
    image_path = 'astronaut.jpg'
    image_file = open(image_path,'rb')
    image_raw = image_file.read()
    image_scipy = scipy.misc.imread(image_path)
    image_tf = tf.image.decode_jpeg(image_raw).eval(session=tf.Session())
    print('Error: ', np.sum(np.abs(image_tf - image_scipy)))
    #Error:  3420883624
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.2.0-rc2-21-g12f033d 1.2.0
- **Python version**: 3.5

**Comment by bill363yang** [comment] 2017-07-19 22:43
I can reproduce the result with exactly the same error using the same image and code.
Can this be caused by decoders' differences? Since `scipy.misc.imread` uses `pillow`, `tf.image.decode_jpeg` still functions without `pillow`.


## system information 

- OS: Fedora 26
- Python version: 3.5.3
- Python related management tool: Anaconda 3
- Tensorflow(installed via `conda install`) version: 1.1.0,  np112py35_0

### printed a small portion of the results
````
[1:10,:,2] scipy image
 [[0 0 0 ..., 0 2 1]
 [0 0 0 ..., 0 5 4]
 [0 0 0 ..., 0 5 4]
 ..., 
 [0 0 2 ..., 0 5 5]
 [0 0 0 ..., 0 3 0]
 [0 0 0 ..., 3 3 0]]
[1:10,:,2] tf image
 [[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 3 4]
 [0 0 0 ..., 0 3 4]
 ..., 
 [0 0 0 ..., 0 3 3]
 [0 0 0 ..., 0 2 0]
 [0 0 0 ..., 0 2 0]]
````

**Comment by drpngx** [comment] 2017-07-19 22:46
We use libjpeg. I am not sure what your application is. If you really need this, I would recommend writing your own op on top of pillow.

I am going to close this, since I don't think it warrants changing the TF core.

**Closed by drpngx** 2017-07-19 22:46 UTC

**Comment by HaaPut** [comment] 2017-07-20 16:54
I think the reason for this difference is that Tensorflow used fast integer DCT as a default decode jpeg image 
https://github.com/tensorflow/tensorflow/blob/e073322452e41e76754314aa75d543d071003fc5/tensorflow/core/kernels/decode_image_op.cc#L109

**Comment by drpngx** [comment] 2017-07-20 16:59
Oh yes, I remember some discussion about that. I think we change the default but the other version is available through options.
