### ISSUE TITLE
How to run .pb model with tensorflow( or tensorflowLite)  using DSP in android

### ISSUE THREAD

**Issue by suyali** [tensorflow/tensorflow#38026] opened 2020-03-30 01:44 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-03-30 05:22
@suyali 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the code snippet to reproduce the issue.Please, fill the issue template.

Also, refer [link1](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#1) and [link2](https://www.tensorflow.org/lite) and see if it helps you. Thanks!

**Comment by ravikyram** [comment] 2020-04-07 13:02
@suyali 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-04-13 14:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-13 14:42 UTC
Labels: comp:lite, stat:awaiting response, type:build/install
