### ISSUE TITLE
java/sbt. Cannot register 2 metrics with the same name on cross tests

### ISSUE THREAD

**Issue by ravwojdyla** [tensorflow/tensorflow#19298] opened 2018-05-15 17:24 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: osx 10.11.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: NA
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: https://github.com/ravwojdyla/minimal-repo-tf-crashing

### Describe the problem
We have an issue open in scio (https://github.com/spotify/scio/issues/1137) which depends on java TF artifacts, please read full description in the link above. A TLDR: in cross test TF crushes with:

```
Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count
```

This problem started to manifest itself from version 1.4.0 (previous versions were not affected), and continues to be a problem. The minimal reproduction repo is here: https://github.com/ravwojdyla/minimal-repo-tf-crashing and to reproduce you run `sbt +test`.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by reedwm** [comment] 2018-05-16 17:50
/CC @asimshankar, can you take a look?

**Comment by asimshankar** [comment] 2018-05-16 19:28
Thanks for the report. I'm not familiar with Scala or sbt enough, so I apologize for any ignorance demonstrated below.

If I'm reading https://github.com/spotify/scio/issues/1137#issuecomment-387801270 right, it seems that the problem is that when the test is running in the same JVM as `sbt` (i.e., when `fork := true` is not set), then `org.tensorflow.NativeLibrary` is unable to correctly determine whether or not the shared library has already been loaded and ends up extracting the shared library to another location and loading it again, leading to the initialization conflict.

Resolving  #18397 would help with that, but it seems the underlying issue in this particular case is that `org.tensorflow.NativeLibrary.isLoaded()` isn't able to handle however `sbt` is managing class loading. 

I'll try to look into it, but any suggestions for a better implementation of [`isLoaded`](https://github.com/tensorflow/tensorflow/blob/3176ba990070cdde62b7cdf81747d70107d2e032/tensorflow/java/src/main/java/org/tensorflow/NativeLibrary.java#L119) will be greatly appreciated.

**Comment by asimshankar** [comment] 2018-05-16 19:30
(Would maintaining state about the extracted library, e.g., a monitor-protected static bool be sufficient?)

**Comment by jto** [comment] 2018-05-17 11:48
I *think* sbt creates a different classloader to run each test class.

Maybe `isLoaded` could list the currently loaded libraries and look for the presence of `libtensorflow` ?

Something along the line of:

```scala
def isInClasspath: Boolean = {
  import scala.collection.JavaConverters._
  val libs = classOf[ClassLoader].getDeclaredField("loadedLibraryNames")
  libs.setAccessible(true)
  val loadedLibs = 
      libs.get(ClassLoader.getSystemClassLoader())
        .asInstanceOf[java.util.Vector[String]]
        .asScala
  loadedLibs.exists(_.contains("libtensorflow"))
}
```

**Comment by saudet** [comment] 2018-05-18 02:01
JavaCPP keeps track of libraries already loaded from its cache, so using the [JavaCPP Presets for TensorFlow](https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow) is one way to work around this. The official Java API is also bundled these days:
https://github.com/bytedeco/javacpp-presets/tree/1.4.1/tensorflow#documentation

However, if sbt uses multiple class loaders, the classes of TensorFlow should be loaded by the system class loader. That's a limitation of Java and JNI.

**Comment by jto** [comment] 2018-05-21 09:01
I think I found the cause of the issue and I managed to workaround the bug for scio. See my comments on https://github.com/spotify/scio/issues/1137 and this PR: https://github.com/spotify/scio/pull/1168.

The problem is not SBT specific and anyone using a classloader hierarchy may experience it.

**Comment by asimshankar** [comment] 2018-05-21 17:46
Thanks for the update @jto 
I'm still not 100% sure about what the appropriate fix would be.

@saudet : How does JavaCPP keep track of libraries already loaded from its cache across class loaders (as in, how does it ensure that the class that keeps track of these libraries is managed by the system classloader?)

**Comment by saudet** [comment] 2018-05-21 23:00
It doesn't, class loaders isolate multiple versions of the same class from each other. We could do it through the file system I guess, but loading isn't the issue. The issue is that the life of the JNI library is associated with the class loader that loaded it, and it might get unloaded once that class loader is garbage collected. So the only real "fix" is to load any class that need JNI with the system class loader.

In a way though something like JavaCPP but standardized would make it easy to get all those details right in one place for as many libraries as we need, and then not worry about them at least. I wish the Panama team would understand the need for something like this, sigh...

**Comment by tensorflowbutler** [comment] 2018-06-20 18:39
Nagging Assignee @asimshankar: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-05 18:43
Nagging Assignee @asimshankar: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-20 12:48
Nagging Assignee @asimshankar: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kamei86i** [comment] 2018-07-31 10:30
I'm facing the **Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count** problem both in JUnit tests and in the context of application servers where different applications (i.e., different classloaders) try to load a tensorflow model.
I'm trying to reproduce the issue programmatically, and what I experimented is:
When I load a TF model in Java in a simple main class with SavedModelBundle.load() (as in the following code snippet) all is working, and in _/tmp_ only one _tensorflow_jni_ directory is created.

```
public static void main(String[] args) throws InterruptedException {
	SavedModelBundle b = SavedModelBundle.load(mymodel_path, "serve");
	Thread.sleep(10000);	
}
```
When using classloaders, i experience the Fatal error that is causing the JVM to crash, and in _/tmp_ i can find two different _tensorflow_jni_ directories.

This is the code:

```
public class MyClassLoader extends ClassLoader {

	public MyClassLoader() {
	}

	@Override
	public Class<?> findClass(String name) {
		byte[] bt = loadClassData(name);
		return defineClass(name, bt, 0, bt.length);
	}

	private byte[] loadClassData(String className) {
		// read class
		InputStream is = getClass().getClassLoader().getResourceAsStream(className.replace(".", "/") + ".class");
		ByteArrayOutputStream byteSt = new ByteArrayOutputStream();
		// write into byte
		int len = 0;
		try {
			while ((len = is.read()) != -1) {
				byteSt.write(len);
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		// convert into byte array
		return byteSt.toByteArray();
	}
}
```

and the main:

```
public class MultipleClassLoaderTest {
	public static void main(String[] args) throws NoSuchMethodException, SecurityException, IllegalArgumentException,
			InvocationTargetException, IllegalAccessException {
		MyClassLoader l1 = new MyClassLoader();
		
		String[] classesToLoad = new  String[] { "org.tensorflow.NativeLibrary", "org.tensorflow.TensorFlow" };
		for (String cl : classesToLoad) {
			l1.findClass(cl);			
		}

		Class<?> smb = l1.findClass("org.tensorflow.SavedModelBundle");
		Method loadModelMethod = smb.getMethod("load", new Class<?>[] { String.class, String[].class });
		Object loadedModel = loadModelMethod.invoke(null, new Object[] { "mymodel_path", new String[] {"serve"}});

		System.out.println("Done.");
	}

}
```

The strange thing is that in this last example I was expecting the fatal error when instantiating two MyClassLoader instances. Instead, the error is going to appear with only one instance of MyClassLoader. Is the "system" class loader also trying to load the library?
Has anyone addressed this issue in the context of application servers?

**Comment by saudet** [comment] 2018-07-31 10:42
The system class loader won't load it unless you tell it to. There isn't any good solutions other than loading it as a shared JAR or something as per the instructions of the framework you're using...

**Comment by tensorflowbutler** [comment] 2018-08-15 13:05
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment] 2018-08-18 17:28
Marking as "Contributions Welcome" just so that we can keep this issue open for tracking, but as https://github.com/deeplearning4j/deeplearning4j/issues/6166 suggests it seems that a fix would require some JDK changes?

In the mean time, any contributions to update the documentation (updating https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_java.md) will be appreciated.

**Comment by saudet** [comment] 2018-08-25 06:52
On Linux and Mac, when we have one large JNI-only binary with no symbols or resources shared globally across the process, it's also possible to rename the library before loading it with another class loader: https://github.com/netty/netty/issues/7272

**Comment by saudet** [comment] 2018-08-27 13:48
Actually, we just need to rename the JNI library containing the wrappers, not TensorFlow itself. I think I've successfully worked around this limitation in JavaCPP with commit https://github.com/bytedeco/javacpp/commit/dd57c2cca04c937de8031f5dfc896f1c45b59379 and TensorFlow seems to work well when loaded from multiple class loaders with the JavaCPP Presets for TensorFlow, which comes bundled with the official Java API, but also maps the more complete C/C++ APIs: https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow
I've tested this a bit on Tomcat and it seems to work fine!

This might not work as well when TensorFlow is linked statically to the JNI wrappers, as is the case with the official binaries that are deployed by Google, because TensorFlow would get loaded multiple times in the same process, but maybe it's fine. @asimshankar Is this something supported by TensorFlow?

**Comment by Aliece** [comment] 2019-05-21 08:18
> I'm facing the **Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count** problem both in JUnit tests and in the context of application servers where different applications (i.e., different classloaders) try to load a tensorflow model (tf version 1.6.0).
> I'm trying to reproduce the issue programmatically, and what I experimented is:
> When I load a TF model in Java in a simple main class with SavedModelBundle.load() (as in the following code snippet) all is working, and in _/tmp_ only one _tensorflow_jni_ directory is created.
> 
> ```
> public static void main(String[] args) throws InterruptedException {
> 	SavedModelBundle b = SavedModelBundle.load(mymodel_path, "serve");
> 	Thread.sleep(10000);	
> }
> ```
> 
> When using classloaders, i experience the Fatal error that is causing the JVM to crash, and in _/tmp_ i can find two different _tensorflow_jni_ directories.
> 
> This is the code:
> 
> ```
> public class MyClassLoader extends ClassLoader {
> 
> 	public MyClassLoader() {
> 	}
> 
> 	@Override
> 	public Class<?> findClass(String name) {
> 		byte[] bt = loadClassData(name);
> 		return defineClass(name, bt, 0, bt.length);
> 	}
> 
> 	private byte[] loadClassData(String className) {
> 		// read class
> 		InputStream is = getClass().getClassLoader().getResourceAsStream(className.replace(".", "/") + ".class");
> 		ByteArrayOutputStream byteSt = new ByteArrayOutputStream();
> 		// write into byte
> 		int len = 0;
> 		try {
> 			while ((len = is.read()) != -1) {
> 				byteSt.write(len);
> 			}
> 		} catch (IOException e) {
> 			e.printStackTrace();
> 		}
> 		// convert into byte array
> 		return byteSt.toByteArray();
> 	}
> }
> ```
> 
> and the main:
> 
> ```
> public class MultipleClassLoaderTest {
> 	public static void main(String[] args) throws NoSuchMethodException, SecurityException, IllegalArgumentException,
> 			InvocationTargetException, IllegalAccessException {
> 		MyClassLoader l1 = new MyClassLoader();
> 		
> 		String[] classesToLoad = new  String[] { "org.tensorflow.NativeLibrary", "org.tensorflow.TensorFlow" };
> 		for (String cl : classesToLoad) {
> 			l1.findClass(cl);			
> 		}
> 
> 		Class<?> smb = l1.findClass("org.tensorflow.SavedModelBundle");
> 		Method loadModelMethod = smb.getMethod("load", new Class<?>[] { String.class, String[].class });
> 		Object loadedModel = loadModelMethod.invoke(null, new Object[] { "mymodel_path", new String[] {"serve"}});
> 
> 		System.out.println("Done.");
> 	}
> 
> }
> ```
> 
> The strange thing is that in this last example I was expecting the fatal error when instantiating two MyClassLoader instances. Instead, the error is going to appear with only one instance of MyClassLoader. Is the "system" class loader also trying to load the library?
> Has anyone addressed this issue in the context of application servers?

Imeet this issue now same as yours， have you solve this issue？

**Comment by MarkDaoust** [comment] 2020-01-24 21:34
What's the status of this? You might have more luck with SIG-JVM, which is taking over tensorflow's Java functionality.

github.com/tensorflow/java

**Closed by MarkDaoust** 2020-01-24 21:34 UTC
Labels: stat:contributions welcome, type:docs

**Comment by saudet** [comment] 2020-01-25 01:08
We're using JavaCPP there now, so this can be considered "fixed".
