### ISSUE TITLE
Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary

### ISSUE THREAD

**Issue by cdmajie** [tensorflow/tensorflow#4592] opened 2016-09-27 02:09 UTC
when i  change 'max_step' from 1000 to 10000 in mnist_with_summaries.py ,after 8550 iters occur these error:
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Nan in summary histogram for: layer1/biases/summaries/HistogramSummary
	 [[Node: layer1/biases/summaries/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](layer1/biases/summaries/HistogramSummary/tag, layer1/biases/Variable/read/_21)]]
Traceback (most recent call last):

**Comment by concretevitamin** [comment] 2016-09-28 22:43
I did not confirm this myself, but could it be that this model is basically fully trained within 1000 steps?  If this is the case, continue training may or may not lead to NaNs.  Please confirm.

**Comment by vrv** [comment] 2016-09-28 22:50
I think mnist_with_summaries prior to r0.11 had bugs.  If you are using mnist_with_summaries.py at HEAD, they might be fixed.  I wouldn't use mnist_with_summaries.py for anything real -- the point was to demonstrate how to attach summaries to a model.

**Comment by aselle** [comment] 2016-10-11 00:11
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!

**Closed by aselle** 2016-10-11 00:11 UTC
Labels: awaiting response

**Comment by issxjl2015** [comment] 2017-06-13 09:36
but my tensorflow version is 1.0.1, so I don't know why have a error? the error is "Invalid argument: Nan in summary histogram for: train/boxes_delta_y
	 [[Node: train/boxes_delta_y = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](train/boxes_delta_y/tag, strided_slice_45/_99)]]"

I need help, help, help!!! Please!!!

**Comment by sswarnakar** [comment] 2017-06-14 14:58
InvalidArgumentError: Nan in summary histogram for: dnn/dnn/logits_activation
	 [[Node: dnn/dnn/logits_activation = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](dnn/dnn/logits_activation/tag, dnn/logits/BiasAdd)]]

I am having the same error too.....have been trying to figure out what's wrong but not being able to do it....someone please help me on this

**Comment by aselle** [comment] 2017-06-14 16:54
@issxjl2015, @sswarnakar, you may have the same error but for different reasons. Please post detailed issues with **reproducible test cases** as new issues if you would like help. Assuming the causes of the error being the same is easy to do, but often not true. Thank you.
