### ISSUE TITLE
tf.contrib.learn yields error message “module has no attribute 'learn' ”

### ISSUE THREAD

**Issue by bullwinkle2059** [tensorflow/tensorflow#6607] opened 2017-01-02 23:12 UTC
Here is a snippet of my code taken directly from the tf.contrib.learn tutorial 

`# Load Data Sets
training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
    filename = IRIS_TRAINING,
    target_dtype = np.int,
    features_dtype = `np.float32)`

Here is the error message:

`AttributeError                            Traceback (most recent call last)
<ipython-input-14-7122d1244c55> in <module>()
     11 
     12 # Load Data Sets
---> 13 training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
     14     filename = IRIS_TRAINING,
     15     target_dtype = np.int,

AttributeError: 'module' object has no attribute 'learn'`

Clearly the module has the attribute learn since tensorflow has a section on learning tf.contrib.learn. What am I doing wrong? All guidance is appreciated.

**Comment by gunan** [comment] 2017-01-03 23:24
Please make sure to fill out all of the template when filing bugs.
Which operating system are you running on?
Which version of tensorflow are you using?

In our setups we cannot reproduce this problem. We need much more information than you provided if we are to help you with this problem.

**Comment by aselle** [comment] 2017-01-17 19:20
Closing due to lack of recent activity. We will reopen when additional information becomes available. Thanks!

**Closed by aselle** 2017-01-17 19:20 UTC
Labels: awaiting response
