### ISSUE TITLE
Greater(nextafter(x), x) returns False

### ISSUE THREAD

**Issue by Poiu19** [tensorflow/tensorflow#56710] opened 2022-07-08 07:27 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Current Behaviour?

```shell
Greater(nextafter(x), x) returns False
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

input = tf.constant([0.0, 0.25, np.finfo(tf.float32.as_numpy_dtype).tiny], dtype=tf.float32)
nextafter = tf.math.nextafter(input, tf.dtypes.as_dtype(tf.float32).max)
greater = tf.math.greater(nextafter, input)

print("input", input)
print("nextafter", nextafter)
print("greater", greater)

assert all(greater)
```

### Relevant log output

```shell
input tf.Tensor([0.0000000e+00 2.5000000e-01 1.1754944e-38], shape=(3,), dtype=float32)
nextafter tf.Tensor([1.4012985e-45 2.5000003e-01 1.1754945e-38], shape=(3,), dtype=float32)
greater tf.Tensor([False  True  True], shape=(3,), dtype=bool)
collected 0 items / 1 errors                                                                                                                                                                                                 

=========================================================================================================== ERRORS ===========================================================================================================
_______________________________________________________________________________________________________ ERROR repro.py _______________________________________________________________________________________________________
repro.py:12: in <module>
    assert all(greater)
E   assert False
E    +  where False = all(<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True,  True])>)
================================================================================================== short test summary info ===================================================================================================
ERROR repro.py - assert False
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================== 1 error in 5.84 seconds ===================================================================================================
```
</details>

**Comment by sushreebarsa** [comment] 2022-07-10 06:47
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/acbf429424e6957e2d8c7f4958cd0d2e/56710.ipynb). Thank you!

**Comment by sachinprasadhs** [comment] 2022-07-20 22:34
`assert all` to return true, all the values in the list must be True. In your case values are `[False  True  True]`. It is working as expected, correct me if I'm missing anything.

**Comment by Poiu19** [comment] 2022-07-21 08:12
@sachinprasadhs Yes, `assert all` expects all values to be `True`. The problem is that `Greater` returns `[False True True]` instead of `[True True True]`

**Comment by sachinprasadhs** [comment] 2022-07-21 18:44
In the output provided by you, I see value difference in the first value of `Input` and `nextafter` which are `0.0000000e+00 `and `1.4012985e-45`, are the values generated here is not as you expected, if so, could you please let us know what was the expected outcome in your case. Thanks!

**Comment by lapinskm** [comment] 2022-07-27 07:37
Poiu19 is on vacation so we are filling in for him.

The values generated by nextafter are different than the original ones, which is as expected.
The problem is, that nextafter(x) > x should return True for every x (except for corner-cases).

In short, we would expect the result to be [True True True]

However, in this case 1.4012985e-45 > 0 returns False.
It is possible that operator Greater does not work correctly on denormals.

**Comment by lapinskm** [comment] 2022-08-03 08:35
Bumping issue to prevent closing.

**Comment by Poiu19** [comment] 2022-08-08 08:55
bump

**Comment by cantonios** [comment] 2022-08-31 16:54
We flush denormals in hardware within TensorFlow for performance purposes ([links](https://github.com/tensorflow/tensorflow/search?q=ScopedFlushDenormal)).  So that is comparing 0 to 0, which are equal.  This is working as intended.

**Closed by cantonios** 2022-08-31 16:54 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, TF 2.9
