### ISSUE TITLE
Inconsistence output with resize_images() using different method 

### ISSUE THREAD

**Issue by 24hours** [tensorflow/tensorflow#2228] opened 2016-05-05 01:37 UTC
Extended from [Stackoverflow question](http://stackoverflow.com/questions/37032251/tensorflow-image-resize-mess-up-image-on-unknown-image-size)

### Environment info
Operating System: Ubuntu 14.04 / OS X Yosemite

Installed version of CUDA and cuDNN: 
CUDA Version : 7.5
cuDnn: 4

Tensorflow version: 0.8.0

When resizing image with variable dimension (output from `decode_jpeg`), image tend to get messed up. However, if `reshape()` is applied prior to `resize()`, image will get resized properly. This issue does not affect `ResizeMethod.Nearest_Neighbour`. 

### Steps to reproduce
```

import tensorflow as tf
import matplotlib.pyplot as plt

file_contents = tf.read_file('./2008_000002.jpg')
im = tf.image.decode_jpeg(file_contents)
im_bi = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BILINEAR)
im_nn = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
im_bic = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BICUBIC)
im_ar = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.AREA)

# im = tf.reshape(im, shape=[256, 256, 3])

sess = tf.Session()
sess.run(tf.initialize_all_variables())

img_bi, img_nn, img_bic, img_ar = sess.run([im_bi, im_nn, im_bic, im_ar])

plt.imshow(img_bi)
plt.title("BILINEAR")
plt.figure()

plt.imshow(img_nn)
plt.title("NEAREST_NEIGHBOR")
plt.figure()

plt.imshow(img_bic)
plt.title("BICUBIC")
plt.figure()

plt.imshow(img_ar)
plt.title('AREA')
plt.show()
```

[Original image](http://imgur.com/MskVWIV)

Result
![nearest Neighbour](https://cloud.githubusercontent.com/assets/650407/15034074/7b973208-12a4-11e6-943e-ea04e1389c01.png)
![bilinear](https://cloud.githubusercontent.com/assets/650407/15034080/88bfbc84-12a4-11e6-81be-b0fa632d7997.png)
![bicubic](https://cloud.githubusercontent.com/assets/650407/15034081/88c2a41c-12a4-11e6-9681-f008ec36ff0f.png)
![area](https://cloud.githubusercontent.com/assets/650407/15034079/88bb4604-12a4-11e6-9ff9-1a53c49a5ab3.png)

**Comment by yaroslavvb** [comment] 2016-05-05 02:47
Can reproduce at head with
- from tensorflow.python.ops import image_ops

im_bi = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BILINEAR)
im_nn = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
im_bic = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BICUBIC)
im_ar = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.AREA)

**Comment by yaroslavvb** [comment] 2016-05-05 02:48
![bad-sun](https://cloud.githubusercontent.com/assets/23068/15034991/3019a0e0-1231-11e6-9697-7f26bfd28253.jpg)

**Comment by girving** [comment] 2016-06-07 05:42
Closing as duplicate of #1029.

**Closed by girving** 2016-06-07 05:42 UTC

**Comment by yuezhizizhang** [comment] 2017-04-04 05:37
Any conclusion on how to fix this problem? I meet the same issue with Tensorflow 1.0.

**Comment by peigolee** [comment] 2017-04-09 14:58
change your image type, and it will be showed properly. 
resize image by  bilinear, bicubic and area will change image data type(from uint8 to float32)
im_bi = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BILINEAR)
im_nn = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
im_bic = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.BICUBIC)
im_ar = tf.image.resize_images(im, 256, 256, method=tf.image.ResizeMethod.AREA)

im_bi = tf.cast(im_bi, tf.uint8)
im_bic = tf.cast(im_bic, tf.uint8)
im_ar = tf.cast(im_ar, tf.uint8)

**Comment by shawnyuen** [comment] 2017-07-08 11:29
@peigolee 
Exactly.
''
import numpy as np
plt.imshow(np.uint8(img_bi))
''
Resized images are showed properly.
