### ISSUE TITLE
tf.compat.v2.summary.scalar  has no attribute 'experimental'

### ISSUE THREAD

**Issue by tasnimul92** [tensorflow/tensorflow#30989] opened 2019-07-24 12:42 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 2.7 
- Bazel version (if compiling from source): Build label: 0.24.1
- GPU model and memory:  CPU 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)

**Describe the current behavior**
```
import tensorflow.compat.v2.summary as b
b.scalar
```
<function scalar at 0x7fbe6ed09050>
```
b.experimental
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'experimental'

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` 
train_log_dir = "logs/scalars/"
self._train_summary_writer = tf.compat.v2.summary.create_file_writer(train_log_dir)
 def get_metrics(self,step):
    self._step= step
    loss=self.metrics.get("loss", None)
    accuracy = self.metrics.get("accuracy", None)
    with self._train_summary_writer.as_default():
      tf.compat.v2.summary.scalar('loss', loss,step=self._step)
      tf.compat.v2.summary.scalar('loss', accuracy,step=self._step )
      self._train_summary_writer.flush()
    return self.metrics
```
**Other info / logs**
Traceback (most recent call last):
  File "/home/sendate/Desktop/TeamTrung/Bintu/Tensor/Agent.py", line 152, in <module>
    print('history dict:', agent.get_metrics(episode))
  File "/home/sendate/Desktop/TeamTrung/Bintu/Tensor/Agent.py", line 83, in get_metrics
    tf.compat.v2.summary.scalar('loss', loss,step=self._step)
  File "/home/sendate/Desktop/TeamTrung/Bintu/Tensor/venv/local/lib/python2.7/site-packages/tensorboard/plugins/scalar/summary_v2.py", line 57, in scalar
    getattr(tf.summary.experimental, 'summary_scope', None) or
  File "/home/sendate/Desktop/TeamTrung/Bintu/Tensor/venv/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 104, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: 'module' object has no attribute 'experimental'

**Comment by ravikyram** [comment] 2019-07-25 09:30
I am able to execute the code without any issues in 2.0.0-beta1. Please, find the screenshot.
![experimental](https://user-images.githubusercontent.com/51902062/61863096-995c7900-aeec-11e9-8517-9f73fc71696d.png)
If that was not the expected output ,please share the full code snippet to reproduce the issue.
Thanks!

**Comment by ravikyram** [comment] 2019-08-01 05:24
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by ravikyram** 2019-08-01 05:24 UTC
Labels: 2.0.0-beta0, comp:tensorboard, stat:awaiting response
