### ISSUE TITLE
[TF2.0] Can't use tf.data.Dataset::cache with distribution strategy

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#28782] opened 2019-05-16 22:59 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip tf-nightly-gpu-2.0-preview
- TensorFlow version (use command below): 2.0.0.dev20190514
- Python version: 3.7.3
- CUDA/cuDNN version: 10 / 7.4.2.24
- GPU model and memory: V100

**Describe the current behavior**
Using `tf.data.Dataset::cache` and `tf.distribute.MirroredStrategy()` will fail with `Cache should only be read after it has been completed. [Op:MultiDeviceIteratorInit]` in TF 2.0 nightly.

**Describe the expected behavior**
Using `tf-nightly-gpu==1.14.1.dev20190514` graph mode `tf.data` caching works using distribution strategy and doesn't throw an error.

**Code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_train, mnist_test = tfds.load(name='mnist', split=[tfds.Split.TRAIN, tfds.Split.TEST], as_supervised=True, data_dir="gs://plumerai/data")

strategy = tf.distribute.MirroredStrategy()

def scale(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255

  return image, label

train_dataset = mnist_train.cache().repeat().map(scale).shuffle(1000).batch(256)
test_dataset = mnist_test.cache().repeat().map(scale).batch(256)

with strategy.scope():
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10, activation='softmax')
  ])

  model.compile(loss='sparse_categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

model.fit(train_dataset, validation_data=test_dataset, steps_per_epoch=100, validation_steps=10, epochs=10)
```

**Other info / logs**
```python
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 646, in fit validation_freq=validation_freq)
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 143, in fit_distributed steps_name='steps_per_epoch')
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 194, in model_iteration val_iterator = _get_iterator(val_inputs, model._distribution_strategy)
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 512, in _get_iterator inputs, distribution_strategy)
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/distribute/distributed_training_utils.py", line 529, in get_iterator initialize_iterator(iterator, distribution_strategy)
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/distribute/distributed_training_utils.py", line 535, in initialize_iterator init_op = control_flow_ops.group(iterator.initialize())
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 274, in initialize return super(DistributedIteratorV1, self)._initializer
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 259, in _initializer init_ops.extend(it.initialize())
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 660, in initialize self._iterator._eager_reset() # pylint: disable=protected-access
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 333, in _eager_reset max_buffer_size=self._max_buffer_size)
File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3118, in multi_device_iterator_init _six.raise_from(_core._status_to_exception(e.code, message), None)
File "<string>", line 3, in raise_from tensorflow.python.framework.errors_impl.InternalError: Cache should only be read after it has been completed. [Op:MultiDeviceIteratorInit]
```

**Comment by achandraa** [comment] 2019-05-17 07:34
Will it be possible to provide full minimal code snippet that can reproduce the issue on version 2.0.0.dev20190514. That would really help us to debug faster. Thanks!

**Comment by lgeiger** [comment] 2019-05-17 10:10
@achandraa Sorry for the incomplete code sample. This was the result of some late night debugging ;)

I added a complete code sample above.

**Comment by lytkarinskiy** [comment] 2019-07-23 23:40
Hi! Any update in this?

**Comment by darcula1993** [comment] 2019-10-12 08:04
I meet the same problem today with newest released tf2.0.

**Comment by rani-pinchuk** [comment] 2019-10-16 19:18
Same problem with me. If I cache on the validation data I get the same error. What do we do wrong?

**Comment by darcula1993** [comment] 2019-10-18 02:28
> Same problem with me. If I cache on the validation data and use the `validation_step` in the `fit()` call, I always get the same error.
> 
> However, if I do not include the `validation_step`, and remove the `repeat()` from the validation dataset, it works nicely, as the validation runs until the validation_data dataset is exhausted (see the documentation of `fit()`. As it is not necessary to shuffle the validation data, the repeat is not really necessary here. So this way the problem is _solved_.
> 
> So I guess I did not use the correct `validation_steps` value after all, but it is not really needed.

I just found my problem come from that I accidently used same tf dataset for both train and valid stage. In the same time, the number of steps I set do not exhausted all data in the cache.

After I use different tf.data.dataset and set a larger number of steps, the problem solved.

**Comment by sbl1996** [comment] 2019-10-23 02:05
Thanks for @darcula1993 . Using `cache()` after `take()` or `skip()` solved my problem.

**Comment by MikeOfZen** [comment] 2019-11-05 02:10
I'm experiencing the same issue.
both suggestions by darcula1993 and sbl1996 dont help
A minimal reproduction code:

```

%tensorflow_version 2.x
#must use tf 1.x to use TPU properly
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import tensorflow_datasets as tfds
import os

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

#constants
IMG_HEIGHT=IMG_WIDTH=200
BATCH_SIZE=128

def create_model():
  model = tf.keras.models.Sequential()
  model.add(tf.keras.layers.BatchNormalization(input_shape=(IMG_HEIGHT,IMG_WIDTH,1)))
  model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(64, (5, 5), activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(128, (3, 3),  activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(256, (3, 3),  activation='elu'))
  #model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.BatchNormalization())
  model.add(tf.keras.layers.Conv2D(512, (3, 3),  activation='elu'))
  model.add(tf.keras.layers.MaxPooling2D(2))
  model.add(tf.keras.layers.Dropout(0.25))

  model.add(tf.keras.layers.Flatten())
  model.add(tf.keras.layers.Dense(256))
  model.add(tf.keras.layers.Activation('elu'))
  model.add(tf.keras.layers.Dropout(0.5))
  model.add(tf.keras.layers.Dense(10))
  model.add(tf.keras.layers.Activation('softmax'))
  return model

@tf.function
def convert(image,label):
  return (tf.image.convert_image_dtype(image, tf.float32),tf.expand_dims(tf.cast(label,tf.float32),0))
@tf.function
def resize(image,label):
  return (tf.image.resize(image,(IMG_HEIGHT,IMG_WIDTH)),label)

test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 10, 80])
train_ds = (tfds.load("mnist", split=train_split, as_supervised=True, try_gcs=True) 
  .map(convert)
  .map(resize)
  .batch(BATCH_SIZE).take(144).cache().repeat().prefetch(50))
#this requires a google cloud bucket for the data dir path, but the same problem happens in MNIST as well

with strategy.scope():
  model=create_model()
  model.compile(
        optimizer=tf.keras.optimizers.Adam(),
        loss="sparse_categorical_crossentropy",
        metrics=["sparse_categorical_accuracy"])

model.fit(train_ds,epochs=15,steps_per_epoch=200)
```
Produces this error
```
InternalError: Cache should only be read after it has been completed.
Additional GRPC error information:
{"created":"@1572919336.377239490","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Cache should only be read after it has been completed.","grpc_status":13} [Op:MultiDeviceIteratorInit]
```

The environment is a Colab notebook with python 3.6 and TPU accelerator.
The problem disappears if the code is switched to TF 1.x and training runs well.

**Comment by darcula1993** [comment] 2019-11-08 02:05
> I'm experiencing the same issue.
> both suggestions by darcula1993 and sbl1996 dont help
> A minimal reproduction code:
> 
> ```
> 
> %tensorflow_version 2.x
> #must use tf 1.x to use TPU properly
> import tensorflow as tf
> import numpy as np
> import matplotlib.pyplot as plt
> import tensorflow_datasets as tfds
> import os
> 
> resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
> tf.config.experimental_connect_to_cluster(resolver)
> tf.tpu.experimental.initialize_tpu_system(resolver)
> strategy = tf.distribute.experimental.TPUStrategy(resolver)
> 
> #constants
> IMG_HEIGHT=IMG_WIDTH=200
> BATCH_SIZE=128
> 
> def create_model():
>   model = tf.keras.models.Sequential()
>   model.add(tf.keras.layers.BatchNormalization(input_shape=(IMG_HEIGHT,IMG_WIDTH,1)))
>   model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
>   model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.BatchNormalization())
>   model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='elu'))
>   model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.BatchNormalization())
>   model.add(tf.keras.layers.Conv2D(64, (5, 5), activation='elu'))
>   model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.BatchNormalization())
>   model.add(tf.keras.layers.Conv2D(128, (3, 3),  activation='elu'))
>   model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.BatchNormalization())
>   model.add(tf.keras.layers.Conv2D(256, (3, 3),  activation='elu'))
>   #model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.BatchNormalization())
>   model.add(tf.keras.layers.Conv2D(512, (3, 3),  activation='elu'))
>   model.add(tf.keras.layers.MaxPooling2D(2))
>   model.add(tf.keras.layers.Dropout(0.25))
> 
>   model.add(tf.keras.layers.Flatten())
>   model.add(tf.keras.layers.Dense(256))
>   model.add(tf.keras.layers.Activation('elu'))
>   model.add(tf.keras.layers.Dropout(0.5))
>   model.add(tf.keras.layers.Dense(10))
>   model.add(tf.keras.layers.Activation('softmax'))
>   return model
> 
> @tf.function
> def convert(image,label):
>   return (tf.image.convert_image_dtype(image, tf.float32),tf.expand_dims(tf.cast(label,tf.float32),0))
> @tf.function
> def resize(image,label):
>   return (tf.image.resize(image,(IMG_HEIGHT,IMG_WIDTH)),label)
> 
> test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 10, 80])
> train_ds = (tfds.load("mnist", split=train_split, as_supervised=True, try_gcs=True) 
>   .map(convert)
>   .map(resize)
>   .batch(BATCH_SIZE).take(144).cache().repeat().prefetch(50))
> #if the .cache() is removed the issue disappears
> 
> with strategy.scope():
>   model=create_model()
>   model.compile(
>         optimizer=tf.keras.optimizers.Adam(),
>         loss="sparse_categorical_crossentropy",
>         metrics=["sparse_categorical_accuracy"])
> 
> model.fit(train_ds,epochs=15,steps_per_epoch=200)
> ```
> 
> Produces this error
> 
> ```
> InternalError: Cache should only be read after it has been completed.
> Additional GRPC error information:
> {"created":"@1572919336.377239490","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Cache should only be read after it has been completed.","grpc_status":13} [Op:MultiDeviceIteratorInit]
> ```
> 
> The environment is a Colab notebook with python 3.6 and TPU accelerator.
> TF version:v2.0.0-rc2-26-g64c3d38 2.0.0
> The problem disappears if the code is switched to TF 1.x and training runs well.

try catche first then map?

**Comment by jsimsa** [comment] 2020-01-13 21:20
Can you try with TF 2.1? I believe this issue should have been fixed by https://github.com/tensorflow/tensorflow/commit/08f41c6216d177933ba8eb48cd171a1e004e6ca2

**Comment by ymodak** [comment] 2020-04-02 19:50
Closing this issue since it's resolved. Feel free to reopen if still have problems. Thanks!

**Closed by ymodak** 2020-04-02 19:50 UTC
Labels: TF 2.0, comp:dist-strat, stat:ds-triaged, type:bug
