### ISSUE TITLE
Deallocation not happening when running on GPU in iOS swift

### ISSUE THREAD

**Issue by jestingeorgejacob1** [tensorflow/tensorflow#47674] opened 2021-03-09 10:05 UTC
System information

    OS Platform - iOS, swift
    Mobile device : iPhone, iPad
    TensorFlow installed from (source or binary): Pod.
    TensorFlow version (use command below): 2.3.0

**Execution**
Initialised interpreter once with below code
var delegate = MetalDelegate()
self.interpreter = try Interpreter(modelPath: modelPath, options: nil, delegates: [delegate])
self.interpreter?.allocateTensors()

Then executed the below code each time on running the inference
var inputTensor = try interpreter?.copy(input, toInputAt:0)
try interpreter?.invoke()
var outputTensor = try interpreter?.output(at: 0)

**Issue**
On running the .invoke() in GPU (using MetalDelegate) the memory consumption is increasing and not decreasing. How do i deallocate the unused memory? This is working fine in CPU.

**Comment by amahendrakar** [comment] 2021-03-09 13:16
@jestingeorgejacob1,
Seems like this is a duplicate of issue [#47640](https://github.com/tensorflow/tensorflow/issues/47640). I'm closing this issue as it is already being tracked there. 

Please feel free to re-open if I'm mistaken. Thanks!

**Closed by amahendrakar** 2021-03-09 13:16 UTC
Labels: type:bug
