### ISSUE TITLE
No Speedup or Size Savings After FP16 / INT8 with TensorRT

### ISSUE THREAD

**Issue by nseidl** [tensorflow/tensorflow#30717] opened 2019-07-15 17:57 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): [nvidia-docker `tensor:19.02-py3` (Ubuntu 16.04)](https://docs.nvidia.com/deeplearning/sdk/tensorrt-container-release-notes/rel_19-02.html#rel_19-02)
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: Python 3.5.2
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0.130 / 7.4.2
- GPU model and memory: Tesla V100 32GB

**Describe the current behavior**
I am trying to optimize (decrease) the inference time and model size of my Tiny Yolov3 model. I currently have it as a frozen graph. When I run the timing and evaluation script from [here](https://github.com/tensorflow/models/blob/master/research/tensorrt/tensorrt.py), fps actually decreases as the optimizations are tried, and file sizes stay constant.

**Describe the expected behavior**
I expect file sizes and inference time to decrease.

**Code to reproduce the issue**
I used [this](https://docs.nvidia.com/deeplearning/sdk/tensorrt-container-release-notes/rel_19-02.html#rel_19-02) nvidia-docker image.

[This](https://github.com/tensorflow/models/blob/master/research/tensorrt/tensorrt.py) script with a small preprocessing change:

```
def resize_image(image, target_height, target_width):
    image = image.resize((target_width, target_height), Image.BICUBIC).convert('RGB')
    return np.array(image)

def preprocess_image(file_name, output_height=416, output_width=416,
                     num_channels=3):
    return resize_image(Image.open(file_name), output_height, output_width).astype('float32')
```

I also removed the printing of predictions, as the script is built for a classifier rather than a detector.

**Other info / logs**
Command executed (image file is attached; model is [here](https://drive.google.com/file/d/1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v/view)):
```
python timed.py --frozen_graph=tiny-yolov3_frozen.pb \
--image_file=11075842.jpg \
--native --fp32 --fp16 --int8 \
--output_dir=/workspace \
--input_node=inputs --output_node=output_boxes
```
```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 256, steps 100
  fps   median: 993.1,  mean: 959.8,    uncertainty: 8.9,       jitter: 7.7
  latency       median: 0.25778,        mean: 0.26986,  99th_p: 0.43523,        99th_uncertainty: 0.05783

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 256, steps 100
  fps   median: 912.7,  mean: 896.3,    uncertainty: 8.2,       jitter: 4.6
  latency       median: 0.28048,        mean: 0.29338,  99th_p: 0.42830,        99th_uncertainty: 0.43877

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 256, steps 100
  fps   median: 823.5,  mean: 831.9,    uncertainty: 8.4,       jitter: 96.2
  latency       median: 0.31087,        mean: 0.31129,  99th_p: 0.43070,        99th_uncertainty: 0.07565

==========================
network: tftrt_int8_tiny-yolov3_frozen.pb,       batchsize 256, steps 100
  fps   median: 803.3,  mean: 820.6,    uncertainty: 9.9,       jitter: 19.9
  latency       median: 0.31867,        mean: 0.31814,  99th_p: 0.60985,        99th_uncertainty: 0.01011
```

**Comment by aaroey** [comment] 2019-07-19 17:58
Hi @nseidl, is it possible for you to provide the `tiny-yolov3` model mentioned above for further investigation?

**Comment by nseidl** [comment] 2019-07-19 18:15
> **Other info / logs**
> Command executed (image file is attached; model is [here](https://drive.google.com/file/d/1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v/view)):

You can download the `tiny-volov3` model, as the frozen graph `tiny-yolov3_frozen.pb`.

**Comment by aaroey** [comment] 2019-07-22 16:29
Thanks @nseidl, I think the problem is with 1.14 and we're investigating. Also @bananabowl.

Meanwhile, if you try with tf-nightly-gpu it should work, please let me know if it doesn't.

**Comment by nseidl** [comment] 2019-07-22 19:58
@aaroey I just tried with:

- `NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0`
- the same [nvidia-docker `tensor:19.02-py3` (Ubuntu 16.04)](https://docs.nvidia.com/deeplearning/sdk/tensorrt-container-release-notes/rel_19-02.html#rel_19-02)
- `tf-nightly-gpu`

I've attached the `do.py` script that I execute with the following command:
```
python do.py --frozen_graph=tiny-yolov3_frozen.pb \
--image_file=</path/to/any/image/here> \
--native --fp32 --fp16 \
--output_dir=/workspace \
--input_node=inputs --output_node=output_boxes
```

I ran this twice to get two different `log.txt`:

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 815.2,  mean: 808.7,    uncertainty: 4.9,       jitter: 9.6
  latency       median: 0.15702,        mean: 0.15896,  99th_p: 0.21183,        99th_uncertainty: 0.03145

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 659.8,  mean: 660.3,    uncertainty: 5.0,       jitter: 38.6
  latency       median: 0.19398,        mean: 0.19549,  99th_p: 0.27653,        99th_uncertainty: 0.06498

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 874.4,  mean: 896.2,    uncertainty: 6.2,       jitter: 5.6
  latency       median: 0.14639,        mean: 0.14350,  99th_p: 0.17826,        99th_uncertainty: 0.01251
```

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 816.2,  mean: 809.3,    uncertainty: 3.2,       jitter: 2.9
  latency       median: 0.15683,        mean: 0.15846,  99th_p: 0.20266,        99th_uncertainty: 0.02407

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 659.8,  mean: 656.4,    uncertainty: 2.3,       jitter: 1.8
  latency       median: 0.19399,        mean: 0.19531,  99th_p: 0.24172,        99th_uncertainty: 0.06146

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 912.5,  mean: 911.9,    uncertainty: 0.4,       jitter: 2.8
  latency       median: 0.14028,        mean: 0.14037,  99th_p: 0.14132,        99th_uncertainty: 0.00180
```

As you can see, there's a slow down going from native -> tftrt_fp32, but the fastest is (as expected) tftrt_fp16. 

**1. Why is there a slowdown from native -> tftrt_fp32?**

Additionally, the original `tiny-yolov3_frozen.pb` is ~35MB in size. `tftrt_fp16_tiny-yolov3_frozen.pb` is ~45MB in size, and `tftrt_fp32_tiny-yolov3_frozen.pb` is ~69MB in size.

**2. Are the increased graph file sizes for both the tftrt_fp32 and tftrt_fp16 expected?**

**Comment by aaroey** [comment] 2019-07-22 20:19
For the slowdown from native->trt_fp32, @pooyadavoodi 

For the increased graph size, that is expected. The problem is currently the converted graph has two copies of the weights, but we're fixing it in #30789.

**Comment by nseidl** [comment] 2019-07-22 20:21
Just tried `int8` and there is an error:
```
python do.py --frozen_graph=tiny-yolov3_frozen.pb --image_file=/path/to/image --int8 --output_dir=/workspace --input_node=inputs --output_node=output_boxes
```

```
...
2019-07-22 20:14:47.521952: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor DataType is determined at build time for tensors not marked as input or output.
2019-07-22 20:14:47.622752: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:740] Starting calibration thread on device 0, Calibration Resource @ 0x7f7738007050
2019-07-22 20:14:47.623222: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor DataType is determined at build time for tensors not marked as input or output.
2019-07-22 20:14:47.658028: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:740] Starting calibration thread on device 0, Calibration Resource @ 0x7f77380154f0
2019-07-22 20:14:47.658515: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor DataType is determined at build time for tensors not marked as input or output.
2019-07-22 20:18:39.690851: I tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc:27] Destroying Calibration Resource 
 Calibrator = 0
 Builder    = 0
 Engine     = 0
 Logger     = 0x7f773000bc38
 Thread     = 0x7f7730018ad0

2019-07-22 20:18:46.833018: I tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc:27] Destroying Calibration Resource 
 Calibrator = 0
 Builder    = 0
 Engine     = 0
 Logger     = 0x7f773011ec58
 Thread     = 0x7f7730071b80

2019-07-22 20:18:50.594933: I tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc:27] Destroying Calibration Resource 
 Calibrator = 0
 Builder    = 0
 Engine     = 0
 Logger     = 0x7f77302819c8
 Thread     = 0x7f77302b2520

2019-07-22 20:18:59.329510: I tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc:27] Destroying Calibration Resource 
 Calibrator = 0
 Builder    = 0
 Engine     = 0
 Logger     = 0x7f7730cb5d28
 Thread     = 0x7f77302bd5f0

2019-07-22 20:19:00.279089: I tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc:27] Destroying Calibration Resource 
 Calibrator = 0
 Builder    = 0
 Engine     = 0
 Logger     = 0x7f7738015568
 Thread     = 0x7f77380153f0

pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

**Comment by pooyadavoodi** [comment] 2019-08-01 23:19
@nseidl Could you post the full log you get from TF-TRT (FP16 and INT8)?
Please try it with verbose logging as explained here: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#verbose 

Could you also try nvidia container 19.07 which has 1.14 in it.
There might be regressions in the nightly builds.

**Comment by nseidl** [comment] 2019-08-02 01:10
> @nseidl Could you post the full log you get from TF-TRT (FP16 and INT8)?
> Please try it with verbose logging as explained here: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#verbose
> 
> Please try it with nvidia container 19.07 which has 1.14 in it.
> There might be regressions in the nightly builds.

Nvidia container 19.07 has cuda 10.1, which as far as I know is incompatible with TF 1.14.0.

But, I tried a clean 19.02 container with `tensorflow-gpu==1.14.0`, and observe no speedup at all on either model.  I think this is because no TRTEngineOps are getting created.

```
Running INT8 graph
I0802 00:53:22.479997 140615879628544 trt_convert.py:575] Linked TensorRT version: (0, 0, 0)
I0802 00:53:22.480141 140615879628544 trt_convert.py:576] Loaded TensorRT version: (0, 0, 0)
I0802 00:53:22.480309 140615879628544 trt_convert.py:597] Running against TensorRT version 0.0.0
2019-08-02 00:53:23.598903: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-02 00:53:23.599366: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-08-02 00:53:23.600403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-08-02 00:53:23.600485: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 00:53:23.600497: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-02 00:53:23.600509: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-02 00:53:23.600521: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-02 00:53:23.600531: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-02 00:53:23.600542: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-02 00:53:23.600553: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-02 00:53:23.601804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-02 00:53:23.601836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-02 00:53:23.601843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-02 00:53:23.601849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-02 00:53:23.603427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 16240 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capa
bility: 7.0)
2019-08-02 00:53:26.795786: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-08-02 00:53:26.795820: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 848 nodes (-483), 963 edges (-485), time = 1410.06201ms.
2019-08-02 00:53:26.795908: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 865 nodes (17), 979 edges (16), time = 350.479ms.
2019-08-02 00:53:26.795921: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 858 nodes (-7), 979 edges (0), time = 859.111ms.
2019-08-02 00:53:32.132584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-08-02 00:53:32.132682: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 00:53:32.132713: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-02 00:53:32.132727: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-02 00:53:32.132739: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-02 00:53:32.132750: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-02 00:53:32.132761: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-02 00:53:32.132774: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-02 00:53:32.134133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-02 00:53:32.134175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-02 00:53:32.134183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-02 00:53:32.134189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-02 00:53:32.135805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 16240 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute cap$bility: 7.0)
2019-08-02 00:53:36.359543: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: The graph is already optimized by layout optimizer.
I0802 00:53:46.876585 140615879628544 do.py:122] Starting execution
2019-08-02 00:53:51.250421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-08-02 00:53:51.250522: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 00:53:51.250535: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-02 00:53:51.250548: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-02 00:53:51.250560: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-02 00:53:51.250569: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-02 00:53:51.250582: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-02 00:53:51.250594: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-02 00:53:51.252089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-02 00:53:51.252127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-02 00:53:51.252135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-02 00:53:51.252142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-02 00:53:51.253800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 16240 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute cap$bility: 7.0)
I0802 00:53:51.253948 140615879628544 do.py:141] Starting Warmup cycle
2019-08-02 00:53:55.477931: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: The graph is already optimized by layout optimizer.
I0802 00:54:07.796527 140615879628544 do.py:146] Starting timing.
I0802 00:55:26.767084 140615879628544 do.py:153] Timing loop done!
```

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 820.8,  mean: 802.9,    uncertainty: 5.2,       jitter: 2.6
  latency       median: 0.15594,        mean: 0.16036,  99th_p: 0.23999,        99th_uncertainty: 0.06786

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 823.7,  mean: 813.5,    uncertainty: 5.9,       jitter: 1.9
  latency       median: 0.15539,        mean: 0.15867,  99th_p: 0.27463,        99th_uncertainty: 0.09189

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 822.3,  mean: 805.1,    uncertainty: 4.7,       jitter: 4.9
  latency       median: 0.15567,        mean: 0.15982,  99th_p: 0.22045,        99th_uncertainty: 0.09074

==========================
network: tftrt_int8_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 824.2,  mean: 824.0,    uncertainty: 0.2,       jitter: 1.1
  latency       median: 0.15530,        mean: 0.15534,  99th_p: 0.15649,        99th_uncertainty: 0.00074

==========================
network: native_big-yolov3_frozen.pb,    batchsize 128, steps 100
  fps   median: 162.8,  mean: 160.8,    uncertainty: 0.6,       jitter: 3.7
  latency       median: 0.78606,        mean: 0.79734,  99th_p: 0.97108,        99th_uncertainty: 0.11392

==========================
network: tftrt_fp32_big-yolov3_frozen.pb,        batchsize 128, steps 100
  fps   median: 164.9,  mean: 163.7,    uncertainty: 0.4,       jitter: 1.0
  latency       median: 0.77605,        mean: 0.78252,  99th_p: 0.89290,        99th_uncertainty: 0.09504

==========================
network: tftrt_fp16_big-yolov3_frozen.pb,        batchsize 128, steps 100
  fps   median: 165.1,  mean: 164.0,    uncertainty: 0.3,       jitter: 0.8
  latency       median: 0.77537,        mean: 0.78063,  99th_p: 0.83099,        99th_uncertainty: 0.07721

==========================
network: tftrt_int8_big-yolov3_frozen.pb,        batchsize 128, steps 100
  fps   median: 165.4,  mean: 163.3,    uncertainty: 1.0,       jitter: 0.2
  latency       median: 0.77405,        mean: 0.78970,  99th_p: 0.98406,        99th_uncertainty: 0.51370

```

**Comment by pooyadavoodi** [comment] 2019-08-02 22:26
NVIDIA container 19.07 is compatible with TF 1.14.

**Comment by nseidl** [comment] 2019-08-05 14:21
> NVIDIA container 19.07 is compatible with TF 1.14.
> You wouldn't need to install anything like TensorRT or CUDNN.

@pooyadavoodi `tensorflow-gpu==1.14.0` expects CUDA 10.0.x, whereas the container comes with CUDA 10.1.168 

```
2019-08-05 14:20:24.954346: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-08-05 14:20:24.954436: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-08-05 14:20:24.954501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-08-05 14:20:24.954564: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-08-05 14:20:24.954627: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-08-05 14:20:24.954690: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

**Comment by pooyadavoodi** [comment] 2019-08-06 17:39
> > NVIDIA container 19.07 is compatible with TF 1.14.
> > You wouldn't need to install anything like TensorRT or CUDNN.
> 
> @pooyadavoodi `tensorflow-gpu==1.14.0` expects CUDA 10.0.x, whereas the container comes with CUDA 10.1.168
> 
> ```
> 2019-08-05 14:20:24.954346: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> 2019-08-05 14:20:24.954436: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> 2019-08-05 14:20:24.954501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> 2019-08-05 14:20:24.954564: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> 2019-08-05 14:20:24.954627: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> 2019-08-05 14:20:24.954690: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> ```

You don't need to install tensorflow inside the container. We have already built and installed tensorflow for you inside that container. It's ready to use.

**Comment by nseidl** [comment] 2019-08-06 18:01
> You don't need to install tensorflow inside the container. We have already built and installed tensorflow for you inside that container. It's ready to use.

Yep, I was incorrect. I installed the python dependencies by running `/opt/tensorrt/python/python_setup.sh` (as directed by the container, upon booting up), and it seems to install `tensorflow==1.14.0` from locally. However, how would I install `tensorflow-gpu==1.14.0` from locally?

**Comment by pooyadavoodi** [comment] 2019-09-16 17:17
> I installed the python dependencies by running `/opt/tensorrt/python/python_setup.sh` (as directed by the container, upon booting up), and it seems to install `tensorflow==1.14.0` from locally. However, how would I install `tensorflow-gpu==1.14.0` from locally?

Could you post the log of this?
I just tried this I didn't see that the container boot telling to run `python_setup.sh`.

You don't need to run  `/opt/tensorrt/python/python_setup.sh`.

**Comment by pooyadavoodi** [comment] 2019-09-16 17:18
Closing as a duplicate of https://github.com/tensorflow/tensorflow/issues/31039

**Closed by pooyadavoodi** 2019-09-16 17:18 UTC
Labels: comp:gpu, type:support

**Comment by Kaede93** [comment] 2020-09-26 15:52
> Closing as a duplicate of #31039

@pooyadavoodi 

Hi, I have same problem with TF-TRT. Is that means that using TF-TRT based on TensorRT 4 or 5 will get model with twice of size, and slower speed of inference? Is that using higher version of TensorRT is the only option for this situation?

I tried TF-TRT base on TF1.12+TRT4 and TF1.15+TRT5, they got same results (larger .pb model and slower speed).

I also tried TensorRT4 only (using import tensorrt as trt), and the results seem reasonable (small model in .plan format and faster speed).

Where can I download the TF1.14 with TF-TRT module? I know the pip install tensorflow-gpu==1.14 will get a TF without TF-TRT module, and I don't want to download a whole container from Nvidia-GPU-Cloud.

One more thing, I noticed that the TF1.14 needs less memory while doing inference than other version of TF. For example, only 29MB memory for MobileNetV1 with TF1.14 (pb file was provided by TF official github repository), and ~1.4GB with TF1.12/1.13/1.15/1.8/1.9 (even I set gpu_options.allow_growth = True). Can you tell me why?
