### ISSUE TITLE
resize_image_with_pad output dimensions must be positive

### ISSUE THREAD

**Issue by KuenstlicheIntelligenz** [tensorflow/tensorflow#28919] opened 2019-05-22 06:06 UTC
**System information**
- Custom code
- OS Platform and Distribution Windows 10:
- TensorFlow installed using pip
- TensorFlow versions: tested 1.12, 1.13:
- Python version: 3.6
- CUDA/cuDNN version: 9
- GPU model and memory:  GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:02:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB

**Describe the current behavior**
I have a custom estimator which i trained and i use predictor.from_saved_model(model_dir) to load an exported model. At the preprocessing stage i resize the image with tf.image.resize_image_with_pad with the bilinear method to keep the aspectratio. This works well for a seemingly arbitrary amount of images but sometimes the program crashes with this error:

InvalidArgumentError (see above for traceback): output dimensions must be positive

I read the file with PIL and convert it to a numpy array. Afterwards i check
1. If the image has 3 dimensions
2. Has at least 5 rows and cols 
3. Has 3 channels
4. The image is not all zeros
5. The image values lie between 0 and 255
So i guess it should be a valid input array.

I do provide correct input parameters for the resize fn, and try to resize the images to 128x128.

**Other info / logs**
Traceback (most recent call last):
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: output dimensions must be positive
	 [[{{node map/while/resize_image_with_pad/resize_images/ResizeBilinear}} = ResizeBilinear[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/resize_image_with_pad/control_dependency, map/while/resize_image_with_pad/resize_images/size)]]
	 [[{{node add_19/_165}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_561_add_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/bab/projects/vat_image_classification/run_inference.py", line 31, in <module>
    main(sys.argv)
  File "C:/bab/projects/vat_image_classification/run_inference.py", line 27, in main
    inf.inference_multi(model_dir, config)
  File "C:\bab\projects\vat_image_classification\inference\multi_predict_from_sql_roi.py", line 163, in inference_multi
    predict_to_sql(result, predict_fn, config, engine)
  File "C:\bab\projects\vat_image_classification\inference\multi_predict_from_sql_roi.py", line 122, in predict_to_sql
    prediction.append(predict_fn({'images_ul': [image]})['probabilities'][0][1])
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\contrib\predictor\predictor.py", line 77, in __call__
    return self._session.run(fetches=self.fetch_tensors, feed_dict=feed_dict)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: output dimensions must be positive
	 [[node map/while/resize_image_with_pad/resize_images/ResizeBilinear (defined at C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\contrib\predictor\saved_model_predictor.py:153)  = ResizeBilinear[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/resize_image_with_pad/control_dependency, map/while/resize_image_with_pad/resize_images/size)]]
	 [[{{node add_19/_165}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_561_add_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'map/while/resize_image_with_pad/resize_images/ResizeBilinear', defined at:
  File "C:/bab/projects/vat_image_classification/run_inference.py", line 31, in <module>
    main(sys.argv)
  File "C:/bab/projects/vat_image_classification/run_inference.py", line 27, in main
    inf.inference_multi(model_dir, config)
  File "C:\bab\projects\vat_image_classification\inference\multi_predict_from_sql_roi.py", line 136, in inference_multi
    predict_fn = predictor.from_saved_model(model_dir)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\contrib\predictor\predictor_factories.py", line 153, in from_saved_model
    config=config)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\contrib\predictor\saved_model_predictor.py", line 153, in __init__
    loader.load(self._session, tags.split(','), export_dir)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 197, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 350, in load
    **saver_kwargs)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 278, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\training\saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): output dimensions must be positive
	 [[node map/while/resize_image_with_pad/resize_images/ResizeBilinear (defined at C:\Users\r.beckmann\AppData\Local\conda\conda\envs\babenv\lib\site-packages\tensorflow\contrib\predictor\saved_model_predictor.py:153)  = ResizeBilinear[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/resize_image_with_pad/control_dependency, map/while/resize_image_with_pad/resize_images/size)]]
	 [[{{node add_19/_165}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_561_add_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by achandraa** [comment] 2019-05-23 11:53
Can you please help us to get the minimal code snippet to reproduce the issue. Thanks!

**Comment by achandraa** [comment] 2019-05-28 05:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-28 05:00 UTC
Labels: TF 1.13, stat:awaiting response

**Comment by sakusss** [comment] 2019-10-20 09:38
Do you solve the problem ? cause I met the same error .
