### ISSUE TITLE
"import tensorflow" configures Python logging if tensorboard is not installed

### ISSUE THREAD

**Issue by mdickinson** [tensorflow/tensorflow#47474] opened 2021-03-01 11:37 UTC
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7, Python 3.8 from MacPorts, Python venv
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary wheel `tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl` from PyPI (using `python -m pip install tensorflow`) 
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: Radeon Pro 560X 4 GB, Intel UHD Graphics 630 1536 MB

**Describe the current behavior**

After uninstalling `tensorboard` from the Python virtual environment with `pip uninstall tensorboard`, executing `import tensorflow` at the prompt causes logging to be configured: in particular, a `StreamHandler` handler is added to the root logger.

As a result, in a large Python GUI (PyQt5) application, an `import tensorflow` at application startup time resulted in many log messages unrelated to tensorflow being printed to the console; without importing tensorflow, those log messages weren't visible. (Note that the application had set the level of the root logger to `logging.DEBUG`, and added its own root-level loggers, under the assumption that it would be the only part of the Python environment working with the configuration for the root-level logger.)

**Describe the expected behavior**

Following usual logging best practices (libraries should only emit log messages but not configure logging; log configuration should be left to the application using the library), `import tensorflow` does not affect the root logger.

**Standalone code to reproduce the issue**

Here's an interpreter session demonstrating the issue

```python
Python 3.8.8 (default, Feb 22 2021, 09:21:28) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> root_logger = logging.root
>>> root_logger.handlers
[]
>>> import tensorflow
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
>>> root_logger.handlers  # expected an empty list
[<StreamHandler <stderr> (NOTSET)>]
```

**Additional information**

This looks like a shallow bug and an easy fix. Here's the troublesome code: https://github.com/tensorflow/tensorflow/blob/c023a829167aa4a233a36479cd338ef9784b6990/tensorflow/compat_template.__init__.py#L43

Diagnosis: because the Python logging system hadn't already been configured at the point of the `import tensorflow` execution, and because `tensorboard` wasn't available,`_logging.warning` was then called as above: that then implicitly configured logging by calling `logging.basicConfig`.

A simple solution would be to set up a logger in the normal way (`logger = logging.getLogger(__name__)`) and use `logger.warning` instead of `logging.warning`; that way, implicit configuration of the logging machinery is avoided.

We were able to work around this problem in our application by making sure that we configured logging (adding a null handler to the root logger) _before_ importing `tensorflow`, so that `logging.basicConfig` was no longer invoked.

Another workaround was to ensure that `tensorboard` was installed, but since we don't generally need the functionality provided by `tensorboard`, our packaging system leaves `tensorboard` out as a explicit dependency of `tensorflow`. If the recommendation is that `tensorboard` should be treated as a required dependency of `tensorflow`, that would be good to know.

**Comment by amahendrakar** [comment] 2021-03-02 08:48
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/fb1db566517e29553062515d8262aeff/47474.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2021-03-02 20:34
@mdickinson I cannot reproduce the issue with `TF2.4.1` and `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/6dd00b069523a678946a89468eb93049/47474.ipynb) is a gist with `tf-nightly` and [here](https://colab.research.google.com/gist/jvishnuvardhan/3d2fbe4df01dea9c1e36ed8cf55406a6/47474.ipynb) is a gist with `TF2.4.1`. Thanks!

Can you please verify my gist and let me know why I am not seeing that warning? Thanks!

**Comment by mihaimaruseac** [comment] 2021-03-02 20:45
Can you send a PR please?

**Comment by mdickinson** [comment] 2021-03-04 19:34
@mihaimaruseac: I can definitely create a PR with just the fix. Would this need a regression test, too?

@jvishnuvardhan: I'm not really sure how I could go about finding out why you're not seeing that warning: I can't reproduce your non-reproduction here, and I don't know anything about your system or Python environment. One suggestion would be to try this at a plain old Python prompt: it looks as though you're using IPython, and that brings in a whole lot of extra variables. (E.g., I don't know exactly what log configuration IPython does, under what circumstances.)

**Comment by mdickinson** [comment] 2021-03-04 19:38
@jvishnuvardhan: Ah, looking harder at your gist, you've already imported `tensorflow` to get the version, right at the top. That means that your later import will be using the existing cached import. You need to import tensorflow for the first time _after_ uninstalling tensorboard.

**Comment by mihaimaruseac** [comment] 2021-03-06 01:11
Would be good to also get a regression test.

**Comment by mdickinson** [comment] 2021-03-07 11:18
Sorry, I'm not going to be able to provide a PR with test any time soon; I've already used up most of the time I had available trying to get bazel installed on my machine (and still haven't succeeded).

**Comment by sushreebarsa** [comment] 2021-05-31 09:13
Was able to reproduce the issue in TF v2.5 and didn't face any error,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7fcb43019480cc32719b0fefd449869b/untitled140.ipynb)..Thanks !

**Comment by mdickinson** [comment] 2021-05-31 11:51
@sushreebarsa The issue is still present with Tensorflow 2.5. Below is the output from an example shell session demonstrating the issue. Note that (a) this is not using IPython, and (b) Python caches imports, so it matters that `tensorboard` is uninstalled *before* starting the Python process and importing `tensorflow`.

```
lovelace:~ mdickinson$ python3.8 --version
Python 3.8.9
lovelace:~ mdickinson$ python3.8 -m venv --clear ~/.venvs/tensorflow47474/
lovelace:~ mdickinson$ source ~/.venvs/tensorflow47474/bin/activate
(tensorflow47474) lovelace:~ mdickinson$ pip install -q tensorflow
WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/mdickinson/.venvs/tensorflow47474/bin/python3.8 -m pip install --upgrade pip' command.
(tensorflow47474) lovelace:~ mdickinson$ pip uninstall -q tensorboard
Proceed (y/n)? y
(tensorflow47474) lovelace:~ mdickinson$ pip list
Package                 Version
----------------------- -------------------
absl-py                 0.12.0
astunparse              1.6.3
cachetools              4.2.2
certifi                 2021.5.30
chardet                 4.0.0
flatbuffers             1.12
gast                    0.4.0
google-auth             1.30.1
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
grpcio                  1.34.1
h5py                    3.1.0
idna                    2.10
keras-nightly           2.5.0.dev2021032900
Keras-Preprocessing     1.1.2
Markdown                3.3.4
numpy                   1.19.5
oauthlib                3.1.0
opt-einsum              3.3.0
pip                     20.2.3
protobuf                3.17.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
setuptools              49.2.1
six                     1.15.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.5.0
tensorflow-estimator    2.5.0
termcolor               1.1.0
typing-extensions       3.7.4.3
urllib3                 1.26.5
Werkzeug                2.0.1
wheel                   0.36.2
wrapt                   1.12.1
WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/mdickinson/.venvs/tensorflow47474/bin/python3.8 -m pip install --upgrade pip' command.
(tensorflow47474) lovelace:~ mdickinson$ python
Python 3.8.9 (default, Apr  3 2021, 05:57:58) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> root_logger = logging.root
>>> root_logger.handlers
[]
>>> import tensorflow
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
>>> root_logger.handlers
[<StreamHandler <stderr> (NOTSET)>]
```

**Comment by mihaimaruseac** [comment] 2021-06-08 20:50
Note though that `tensorboard` is listed as a dependency in TF's `setup.py`. Whenever you `pip install tensorflow` you should also get TB.

**Comment by SuryanarayanaY** [comment] 2022-12-15 16:06
Hi @mdickinson ,
At first step itself i have used command `pip uninstall tensorboard` and then installed TF 2.10V and found that Tensorboard 2.10 also getting installed.The i have uninstalled tensorboard again and then got confirmation that 
```
Successfully uninstalled tensorboard-2.10.1
WARNING: Skipping tensorboard as it is not installed.
```
where we are getting uninstallation message as well as Warning.

 I have tested the issue with latest version 2.11 V and found that tensorboard-2.11 installed along with TF.Upon `pip uninstall tensorboard` i got confirmation message as below.

`Successfully uninstalled tensorboard-2.11.0`

Again on trying `pip uninstall tensorboard` i got the warning as below.

`WARNING: Skipping tensorboard as it is not installed.`

Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/e458ef676bf2291607da8fe70c6ddf4a/47474-nightly.ipynb).The problem resolved in latest version 2.11V.

Please go through and confirm whether we can close this issue now.

**Comment by mdickinson** [comment] 2022-12-15 19:58
@SuryanarayanaY The issue I originally reported is still present with the latest tensorflow. Example reproducer on Python 3.10 / macOS / latest tensorflow from PyPI follows:

<details>

```
mdickinson@lovelace ~ % python -m venv ~/.venvs/testing && source ~/.venvs/testing/bin/activate
(testing) mdickinson@lovelace ~ % pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-2.11.0-cp310-cp310-macosx_10_14_x86_64.whl (244.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 MB 8.9 MB/s eta 0:00:00
Collecting numpy>=1.20
  Downloading numpy-1.23.5-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 14.7 MB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting libclang>=13.0.0
  Downloading libclang-14.0.6-py2.py3-none-macosx_10_9_x86_64.whl (13.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 15.6 MB/s eta 0:00:00
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting tensorboard<2.12,>=2.11
  Downloading tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 15.2 MB/s eta 0:00:00
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.51.1-cp310-cp310-macosx_12_0_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 16.4 MB/s eta 0:00:00
Collecting h5py>=2.9.0
  Downloading h5py-3.7.0-cp310-cp310-macosx_10_9_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 14.9 MB/s eta 0:00:00
Collecting absl-py>=1.0.0
  Downloading absl_py-1.3.0-py3-none-any.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./.venvs/testing/lib/python3.10/site-packages (from tensorflow) (63.2.0)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting tensorflow-estimator<2.12,>=2.11.0
  Downloading tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 8.0 MB/s eta 0:00:00
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.28.0-cp310-cp310-macosx_10_14_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 13.4 MB/s eta 0:00:00
Collecting protobuf<3.20,>=3.9.2
  Downloading protobuf-3.19.6-py2.py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 4.7 MB/s eta 0:00:00
Collecting typing-extensions>=3.6.6
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting wrapt>=1.11.0
  Downloading wrapt-1.14.1-cp310-cp310-macosx_10_9_x86_64.whl (35 kB)
Collecting six>=1.12.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting keras<2.12,>=2.11.0
  Downloading keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 13.3 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-22.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.3 MB/s eta 0:00:00
Collecting termcolor>=1.1.0
  Downloading termcolor-2.1.1-py3-none-any.whl (6.2 kB)
Collecting flatbuffers>=2.0
  Downloading flatbuffers-22.12.6-py2.py3-none-any.whl (26 kB)
Collecting wheel<1.0,>=0.23.0
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-macosx_10_9_x86_64.whl (3.5 MB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 3.3 MB/s eta 0:00:00
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.15.0-py2.py3-none-any.whl (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.0/177.0 kB 5.8 MB/s eta 0:00:00
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 11.2 MB/s eta 0:00:00
Collecting werkzeug>=1.0.1
  Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.7/232.7 kB 6.3 MB/s eta 0:00:00
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.0 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 2.7 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 5.1 MB/s eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_x86_64.whl (13 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 4.7 MB/s eta 0:00:00
Installing collected packages: tensorboard-plugin-wit, pyasn1, libclang, flatbuffers, wrapt, wheel, urllib3, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, rsa, pyasn1-modules, protobuf, packaging, oauthlib, numpy, MarkupSafe, markdown, keras, idna, grpcio, gast, charset-normalizer, certifi, cachetools, absl-py, werkzeug, requests, opt-einsum, h5py, google-pasta, google-auth, astunparse, requests-oauthlib, google-auth-oauthlib, tensorboard, tensorflow
Successfully installed MarkupSafe-2.1.1 absl-py-1.3.0 astunparse-1.6.3 cachetools-5.2.0 certifi-2022.12.7 charset-normalizer-2.1.1 flatbuffers-22.12.6 gast-0.4.0 google-auth-2.15.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.51.1 h5py-3.7.0 idna-3.4 keras-2.11.0 libclang-14.0.6 markdown-3.4.1 numpy-1.23.5 oauthlib-3.2.2 opt-einsum-3.3.0 packaging-22.0 protobuf-3.19.6 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.28.1 requests-oauthlib-1.3.1 rsa-4.9 six-1.16.0 tensorboard-2.11.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.11.0 tensorflow-estimator-2.11.0 tensorflow-io-gcs-filesystem-0.28.0 termcolor-2.1.1 typing-extensions-4.4.0 urllib3-1.26.13 werkzeug-2.2.2 wheel-0.38.4 wrapt-1.14.1

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
(testing) mdickinson@lovelace ~ % pip uninstall tensorboard
Found existing installation: tensorboard 2.11.0
Uninstalling tensorboard-2.11.0:
  Would remove:
    /Users/mdickinson/.venvs/testing/bin/tensorboard
    /Users/mdickinson/.venvs/testing/lib/python3.10/site-packages/tensorboard-2.11.0.dist-info/*
    /Users/mdickinson/.venvs/testing/lib/python3.10/site-packages/tensorboard/*
Proceed (Y/n)? y
  Successfully uninstalled tensorboard-2.11.0
(testing) mdickinson@lovelace ~ % python
Python 3.10.7 (main, Sep 10 2022, 07:37:51) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> root_logger = logging.root
>>> root_logger.handlers
[]
>>> import tensorflow
2022-12-15 19:54:39.834932: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
>>> root_logger.handlers
[<StreamHandler <stderr> (NOTSET)>]
```

</details>

> confirm whether we can close this issue now.

Of course, it's up to the tensorflow developers to decide what issues to fix and which issues aren't worth fixing. The issue is not fixed. It's a relatively minor issue, but also a very easy fix.

**Comment by SuryanarayanaY** [comment] 2022-12-19 08:13
Hi @mdickinson ,

Sorry that I misunderstood this [comment](https://github.com/tensorflow/tensorflow/issues/47474#issuecomment-857129968) by the developer. 

I tried to replicate the issue and confirming the same behaviour as you reported with `pip uninstall tensorboard` at first step. Please refer [gist1](https://colab.research.google.com/gist/SuryanarayanaY/bd98772cffdc7c11c449c6cf13d359a1/47474_r3.ipynb) here. But I observed that root_logger.handlers list not empty even before `import tensorflow`. Hence i tried another way without  `pip uninstall tensorboard` and  explicit `root_logger.handlers=[]` and then tried `import tensorflow` after this import itself i got `[<StreamHandler stderr (NOTSET)>]` for `root_logger.handlers`.Please note i haven't uninstalled tensorboard yet here.After uninstalling tensorboard and then again emptying the list `root_logger.handlers` explicitly and thereafter trying `import tensorflow` is not creating the logging list `[<StreamHandler stderr (NOTSET)>]` again.Please refer [gist2](https://colab.research.google.com/gist/SuryanarayanaY/1f4e71ae1ca54e52911c7363425f5320/47474_r4.ipynb).

As per my observation the logging `[<StreamHandler stderr (NOTSET)>]` is being configured irrespective of tensorboard presence in the recent versions. Am I missing anything here ? Please cross check and let me know if something missing from my side or if there is change in behaviour.

The warning log arising from importing tensorflow after tensorboard uninstallation shall be due to Tensorboard integration with Tensorflow as both are included in the same package.

Thankyou!

**Comment by mdickinson** [comment] 2022-12-20 10:36
> thereafter trying `import tensorflow` is not creating the logging list `[<StreamHandler stderr (NOTSET)>]` again

Yes, that's correct: Python caches imports (as [mentioned earlier](https://github.com/tensorflow/tensorflow/issues/47474#issuecomment-851436858)), so if `import tensorflow` has already occurred, then a second `import tensorflow` will not incur the same side-effects that the first did.

**Comment by mdickinson** [comment] 2022-12-20 10:50
@SuryanarayanaY I'm going to unfollow this issue. We've long since worked around the issue in our own code; my motivation in reporting it was to help others who might encounter the same problem. (I don't know for sure, but I'd guess that we're not the only people unbundling `tensorboard`.)

I'm a little bit baffled by the process and the discussion here, and especially by all the attempts to reproduce in a notebook instead of at a console - the notebook is quite a different (and much more complicated) environment. We seem to be going in circles trying to reproduce. The issue exists and is trivially easy to reproduce at a console (or in a script); it's also an easy fix. The decision to be made should simply be whether it's worth fixing it or not. I can certainly see arguments either way there, and it's up to the tensorflow developers to decide.

**Comment by soxofaan** [comment] 2023-02-15 15:46
> I'm a little bit baffled by the process and the discussion here, and especially by all the attempts to reproduce in a notebook instead of at a console - the notebook is quite a different (and much more complicated) environment. We seem to be going in circles trying to reproduce. The issue exists and is trivially easy to reproduce at a console (or in a script); it's also an easy fix.

:point_up: this

I'd also like to point out that it is rather bad style to use the root logger for these things, which makes it harder to track down where these logs are coming from and impractical to filter them out with a logging config.

**Comment by soxofaan** [comment] 2023-02-15 15:57
Coincidentally, last month I tackled a similar issue in Apache Spark: https://github.com/apache/spark/pull/39516 which was resolved in less than 24 hours. 
FYI: note that the maintainers preferred to switch to `warnings.warn` instead of fixing `logging` usage, which has the added benefit that duplicate warning logs (illustrated in examples above) are avoided.

**Comment by tilakrayal** [comment] 2024-09-16 13:56
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by mdickinson** [comment] 2024-09-16 14:53
@tilakrayal Thank you for your comment. I've just verified that the issue appears to no longer exist with Python 3.12.6 and Tensorflow 2.16.2. Here's the transcript (using the same commands as [earlier](https://github.com/tensorflow/tensorflow/issues/47474#issuecomment-851436858) ). I believe this issue can be closed.

```console
~/Desktop/temp % python -m venv --clear tensorflow47474venv && source tensorflow47474venv/bin/activate
(tensorflow47474venv) ~/Desktop/temp % pip install -q tensorflow && pip uninstall -q -y tensorboard
(tensorflow47474venv) ~/Desktop/temp % python
Python 3.12.6 (main, Sep  7 2024, 05:15:33) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.root.handlers
[]
>>> import tensorflow
2024-09-16 15:50:45.083922: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> logging.root.handlers  # expected [], got []
[]
```

**Closed** 2024-09-16 14:59 UTC
Labels: type:bug, comp:apis, TF 2.4, TF 2.5
