### ISSUE TITLE
  java.lang.IllegalArgumentException: Invalid output Tensor index: 1

### ISSUE THREAD

**Issue by NidamanuriChenchaiah** [tensorflow/tensorflow#33976] opened 2019-11-04 14:28 UTC
I've trained my own model for object detection with TensorFlow and I got it working with Tensorflow mobile for android. Now since Tensorflow Lite is released and is going to replace mobile in the future I wanted to start working with it. The Tensorflow team provided a demo for TFLite for object detection. So I tried to get it working with my model but I got the error in the title. Here's the logcat :

    java.lang.IllegalArgumentException: Invalid output Tensor index: 1
        at org.tensorflow.lite.NativeInterpreterWrapper.getOutputTensor(NativeInterpreterWrapper.java:308)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:164)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:194)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)

**Comment by Auburgo** [comment] 2019-11-21 12:10
Are there any updates on this issue?

**Comment by NidamanuriChenchaiah** [comment] 2019-11-21 12:21
No

**Comment by MeghnaNatraj** [comment] 2019-11-21 20:52
@NidamanuriChenchaiah Some values in the android example are hard coded for that particular use case, so this might not work as is for a new tflite model. I suggest you try the following: 

1. Refer to a similar issue ([31788](https://github.com/tensorflow/tensorflow/issues/31788)) and try resolving it using their suggestions:
  a) Match input and output shape array, modifying NUM_DETECTIONS, etc.
  b) Use tools like our [.tflite visualizer](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) to better understand your graph inputs/outputs, or the excellent [Netron](https://electronjs.org/apps/netron) model visualizer (that handles .tflite models as well as other model formats) to ensure input/output tensors have the same shape.

2. If nothing works: upload the model, share a github link to your project or a google colab link where we can reproduce the issue.

**Comment by MeghnaNatraj** [comment] 2019-12-18 23:13
Closing the issue due to inactivity. If you can provide more information, feel free to re-open the issue.

**Closed by MeghnaNatraj** 2019-12-18 23:13 UTC
Labels: comp:lite, type:bug

**Comment by Anasel23** [comment] 2020-05-04 13:42
how did you solve this exception please
 java.lang.IllegalArgumentException: Invalid output Tensor index: 1 i converted a yolov3-tiny model
i changed the NUM_DETECTION into 2535 (NUM_DETECTION=2535) because the input shape is (1,416,416,6) and the output shape is (1,2535,6)
