### ISSUE TITLE
Server finished RPC without an explicit exit code -bash: Server: command not found when use bazel build tensorflow

### ISSUE THREAD

**Issue by anddelu** [tensorflow/tensorflow#6572] opened 2016-12-30 05:56 UTC
### Environment info
Operating System:
centos 6.5 x86_64
ldd (GNU libc) 2.12
gcc (GCC) 4.8.2

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
 [****tensorflow]# git rev-parse HEAD
ac28ae043df4bc6f112f964f6df22845b8a05390
2. The output of `bazel version`
bazel  0.4.3
I build bazel and install successfully

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package                                               

### What other attempted solutions have you tried?
1: rebuild and still have errors

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
INFO: From Compiling tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc:
tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc: In function 'const char* tensorflow::GrpcWorkerMethodName(tensorflow::GrpcWorkerMethod)':
tensorflow/core/distributed_runtime/rpc/grpc_worker_service_impl.cc:50:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling tensorflow/core/debug/debug_io_utils.cc:
tensorflow/core/debug/debug_io_utils.cc:212:15: warning: 'tensorflow::Status tensorflow::CloseDebugURL(const string&)' defined but not used [-Wunused-function]
 static Status CloseDebugURL(const string& debug_url) { return Status::OK(); }
               ^
Server finished RPC without an explicit exit code

**Comment by sugartom** [comment] 2017-01-06 00:50
@anddelu Hi, have you solved the issue? I saw a similar error message "Server finished RPC without an explicit exit code" when installing tensorflow from source. Details [here](https://github.com/tensorflow/tensorflow/issues/6678). Please let me know if you have any suggestions. Thanks in advance! :-)

**Comment by anddelu** [comment] 2017-01-06 02:30
@sugartom I have tried to rebuild the source, but I added some parameters "--local_resources 2048,.5,1.0" when I used bazel. You can fix 2048 to 8096 or else based on your environment. I once tried 2048, it take long time to do. I suggest you can set bigger if you want to fast. Good luck!

**Comment by yliu120** [comment] 2017-02-16 21:17
This problem may be caused by the rpc timeout. Bazel has such a problem with some type of Java Runtime. It maps all processes it spawned to a single core of your machine. So all threads will run slow and at some point, the bazel server will experience a RPC timeout and shutdown.

To fix this problem:
1) Use --batch mode instead of server/client mode of Bazel. add --batch --batch_cpu_scheduling as startup options. Like, bazel --batch --batch_cpu_scheduling build -c opt...
2) Increase rpc timeout using other startup options.

**Comment by martinwicke** [comment] 2017-03-16 15:52
I will close this issue. I don't see how we can do anything about this on the TensorFlow side. The workarounds should work.

**Closed by martinwicke** 2017-03-16 15:52 UTC

**Comment by thavidu** [comment] 2017-06-08 17:02
Switching to batch mode seems to get the process Killed (I'm guessing memory?) so i'm looking at the other option- You mentioned you can increase the 'rpc timeout' , how do you do this? I can't seem to find documentation on doing so.
