### ISSUE TITLE
BUILD Failed: missing input file '@mkl//:LICENSE'.

### ISSUE THREAD

**Issue by athulase** [tensorflow/tensorflow#11678] opened 2017-07-21 23:19 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: latest
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:0.4.5
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: bazel build --config=mkl  -c opt //tensorflow/tools/pip_package:build_pip_package

I was trying to build Tensorflow. and hitting this error missing input file '@mkl//:LICENSE'.
i did it a week back, no problem faced. everything worked fine with same command line

**Comment by kevin-coder** [comment] 2017-07-22 06:19
Meet the same issue, too.

**Comment by Ishi-Apps** [comment] 2017-07-22 20:39
getting following error message during build in Ubuntu,
"missing input file '@androidsdk//:build-tools/25.0.2/aapt'.
Target //tensorflow/examples/android:tensorflow_demo failed to build"

**Comment by gunan** [comment] 2017-07-22 20:46
Sorry for the inconvenience, this is probably due to my change to MKL build.

I have an internal change which should fix MKL build once pushed externally.
Monday or Tuesday we should have a push, which should fix the problem.

**Comment by gunan** [comment] 2017-07-22 20:47
@Ishi-Apps your issue is quite different, I recommend filing a new issue by filling out the full template.

**Comment by agramesh1** [comment] 2017-07-24 19:22
@gunan we are seeing the MKL issue.

**Comment by gunan** [comment] 2017-07-25 07:01
https://github.com/tensorflow/tensorflow/commit/5442825dfd774a1d1f55d4d0e9d2821abb551caf is now pushed out.
@agramesh1 could you sync past that commit and try again to see if the issue is resolved?

**Comment by agramesh1** [comment] 2017-07-25 22:56
@gunan The issues is resolved in the commit. Thanks.

**Closed** 2017-07-26 11:09 UTC
