### ISSUE TITLE
nvcc error: string_view.h: constexpr function return is non-constant

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#22766] opened 2018-10-05 13:50 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: This is what the bug is about, see below.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.11.0-0-gc19e29306c 1.11.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: none
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 8.0, 9.0, 9.1
- **GPU model and memory**: doesn't matter
- **Exact command to reproduce**: See below.

### Describe the problem

Compiling some custom native op with `nvcc` fails, with basically this error:

    absl/strings/string_view.h(501): error: constexpr function return is non-constant

Compiling the same code with `g++` does not have this issue. This seems specifically related to the CUDA frontent `cudafe`.

### Source code / logs

Example code `test.cpp`:

```
// For Eigen::GpuDevice.
#define EIGEN_USE_GPU 1

// For Eigen::ThreadPoolDevice.
#define EIGEN_USE_THREADS 1

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/common_runtime/device.h"

#include <cuda.h>
#include <cuda_runtime.h>
#include <cublas_v2.h>
#include <math_constants.h>

#include "tensorflow/core/platform/stream_executor.h"
```

Compile command:
`/usr/local/cuda-8.0/bin/nvcc -shared -O2 -std=c++11 -I /u/zeyer/py-envs/py36-tf111/lib/python3.6/site-packages/tensorflow/include -I /u/zeyer/py-envs/py36-tf111/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -I /usr/local/cuda-8.0/include -L /usr/local/cuda-8.0/lib64 -x cu -DGOOGLE_CUDA=1 -Xcompiler -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -g test.cpp -o test.so -lblas -lf77blas -L/u/zeyer/py-envs/py36-tf111/lib/python3.6/site-packages/numpy/.libs -lopenblasp-r0-8dca6697.3.0.dev -L/u/zeyer/py-envs/py36-tf111/lib/python3.6/site-packages/tensorflow -ltensorflow_framework -v -Xcompiler -v`

The full compile output (including some more warnings) can be seen [here in the StackOverflow question](https://stackoverflow.com/questions/52665441/nvcc-error-string-view-h-constexpr-function-return-is-non-constant).

**Comment by ppwwyyxx** [comment] 2018-10-05 17:45
A workaround is to add the flag `-DNDEBUG` .

**Comment by albertz** [comment] 2018-10-05 21:19
Hm, yea, although I would want that my `assert`s will fail.
Maybe `-Dconstexpr=` would be another option (did not try), although not sure if that has other drawbacks.

**Comment by Iamanorange** [comment] 2018-10-09 08:20
Same error compiling a custom op.

Environment:
Ubuntu 16.04
GCC 5.5.0
CUDA 9.0 9.2 / cuDNN 7.1
Python 2.7.12
Tensorflow 1.11.0

Fixed by adding the flag `-DNDEBUG`.

**Comment by ymodak** [comment] 2018-10-09 17:32
@albertz Did the workaround help to solve your issue?

> A workaround is to add the flag `-DNDEBUG` .

**Comment by albertz** [comment] 2018-10-09 17:40
@ymodak As I said:

I want that my asserts will fail, so `-DNDEBUG` is not an option for me (and anyway, this is an ugly workaround, and doesn't really solve the problem itself).

Maybe -Dconstexpr= would be another option (did not try; not sure if *less* ugly), although not sure if that has other drawbacks.

**Comment by pavelgolik** [comment] 2018-10-09 17:49
I second @albertz: the problem can be masked as suggested by @ppwwyyxx, but it's not addressing the source of the issue. 

In my environment, I can get past this error by replacing the call to `ABSL_ASSERT()` in `tensorflow/include/absl/strings/string_view.h:501` by `0` (but it is arguably just as ugly as `-DNDEBUG`).

**Comment by tensorflowbutler** [comment] 2018-11-01 12:47
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Wehrdo** [comment] 2018-11-24 01:50
Also seeing this on Ubuntu 18.04, GCC 7.3, Python 3.5, CUDA 9.2.

I worked around by just commenting out the offending line in `tensorflow/include/absl/strings/string_view.h:501`.

**Comment by gh2k** [comment] 2019-05-04 22:22
Another hack is to remove the `ABSL_ASSERT` from the offending line. wfm, ymmv.

**Comment by danganea** [comment] 2019-07-13 12:08
I'm also affected by this issue and similar problems when attempting to compile in debug mode (normal compilation works fine). #27744

It seems to me like the TF community has found some workarounds like defining NDEBUG and commenting out a string_view line and making it work.

But what is the root cause of this issue? #28091 seems to suggest to just quit CUDA debugging altogether. Looking at this thread and related issues  it looks like there's a large amount of people still affected by this.

**Comment by ArthurG** [comment] 2019-12-25 18:22
I am also affected by this issue cuda 10.2 and the -DNDEBUG flag workaround seems to work for me .

**Comment by BruceDai003** [comment] 2020-08-12 02:41
> Another hack is to remove the `ABSL_ASSERT` from the offending line. wfm, ymmv.

Hello, I'm compiling cuda code using NVCC command, and also met this issue, simply add `-DNDEBUG` doesn't slove all related errors(I've 5 errors related). Just curious when is the `ABSL_ASSERT`? Can you explicitly tell me?

**Comment by albertz** [comment] 2020-08-12 08:30
> > Another hack is to remove the `ABSL_ASSERT` from the offending line. wfm, ymmv.
> 
> Hello, I'm compiling cuda code using NVCC command, and also met this issue, simply add `-DNDEBUG` doesn't slove all related errors(I've 5 errors related). Just curious when is the `ABSL_ASSERT`? Can you explicitly tell me?

Look at the error:

    absl/strings/string_view.h(501): error: constexpr function return is non-constant

It says, in file `absl/strings/string_view.h`, in line 501, there is some error.
When you look into that file, in this line, you will find `ABSL_ASSERT`. The suggestion was to just remove that.

But as you say, `-DNDEBUG` doesn't work for you, I suspect that you actually have some different error. You should write what error you get exactly (and what CUDA version, what TF version).

**Comment by BruceDai003** [comment] 2020-08-25 09:13
> > > Another hack is to remove the `ABSL_ASSERT` from the offending line. wfm, ymmv.
> > 
> > 
> > Hello, I'm compiling cuda code using NVCC command, and also met this issue, simply add `-DNDEBUG` doesn't slove all related errors(I've 5 errors related). Just curious when is the `ABSL_ASSERT`? Can you explicitly tell me?
> 
> Look at the error:
> 
> ```
> absl/strings/string_view.h(501): error: constexpr function return is non-constant
> ```
> 
> It says, in file `absl/strings/string_view.h`, in line 501, there is some error.
> When you look into that file, in this line, you will find `ABSL_ASSERT`. The suggestion was to just remove that.
> 
> But as you say, `-DNDEBUG` doesn't work for you, I suspect that you actually have some different error. You should write what error you get exactly (and what CUDA version, what TF version).

Thank you. Well, my CUDA=8.0, TF=1.15.0, 
one of my error says:
`site-packages/tensorflow_core/include/absl/strings/string_view.h(495): error: constexpr function return is non-constant`,
So I checked it out.
```
static constexpr size_type CheckLengthInternal(size_type len) {
    return ABSL_ASSERT(len <= kMaxSize), len;
  }
```
So, should I change this block of code to:
```
static constexpr size_type CheckLengthInternal(size_type len) {
    return 0, len;
  }
```
? 0 or 1?

**Comment by BruceDai003** [comment] 2020-08-25 09:16
> > > Another hack is to remove the `ABSL_ASSERT` from the offending line. wfm, ymmv.
> > 
> > 
> > Hello, I'm compiling cuda code using NVCC command, and also met this issue, simply add `-DNDEBUG` doesn't slove all related errors(I've 5 errors related). Just curious when is the `ABSL_ASSERT`? Can you explicitly tell me?
> 
> Look at the error:
> 
> ```
> absl/strings/string_view.h(501): error: constexpr function return is non-constant
> ```
> 
> It says, in file `absl/strings/string_view.h`, in line 501, there is some error.
> When you look into that file, in this line, you will find `ABSL_ASSERT`. The suggestion was to just remove that.
> 
> But as you say, `-DNDEBUG` doesn't work for you, I suspect that you actually have some different error. You should write what error you get exactly (and what CUDA version, what TF version).

Another error which appears twice is:

```
/include/absl/strings/str_cat.h(269): error: expression must have a constant value
```
I go to that file, and found that it's an template, how to comment this out, I have no idea, can you help me to check it out?
Here is the 269 line:
```
// Normal enums are already handled by the integer formatters.
  // This overload matches only scoped enums.
  template <typename T,
            typename = typename std::enable_if<
                std::is_enum<T>{} && !std::is_convertible<T, int>{}>::type>
  AlphaNum(T e)  // NOLINT(runtime/explicit)
      : AlphaNum(static_cast<typename std::underlying_type<T>::type>(e)) {}
```

**Comment by pavelgolik** [comment] 2020-08-25 09:18
`return len;` should do the trick, no zero or one needed.


As for your second question, you could try to remove the `enable_if`:

`template <typename T> AlphaNum ...`

**Comment by kumariko** [comment] 2021-09-21 11:04
@albertz We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. please check https://github.com/tensorflow/tensorflow/issues/22766#issuecomment-679909377  Thanks!

**Comment by albertz** [comment] 2021-09-21 13:46
I just tried with GCC 9.3.0, CUDA 11.0 and TF 2.3.1 and I don't see the problem anymore.

I'm not exactly sure since what (TF?) version that problem is gone.

**Comment by kumariko** [comment] 2021-09-21 13:55
@albertz  if it is resolved then please feel free to move this issue to close status ? Thanks!

**Closed** 2021-09-21 13:55 UTC
Labels: stat:awaiting response, type:build/install
