### ISSUE TITLE
DLL load failed for tensorflow

### ISSUE THREAD

**Issue by vinit13792** [tensorflow/tensorflow#23065] opened 2018-10-18 08:24 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.10
- Python version: 3.6
- Installed using virtualenv: Canopy pip: 1.18 
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the problem**

```
ImportError                               Traceback (most recent call last)
C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-7-6b0f4483b0d5> in <module>()
----> 1 import tensorflow as tf
      2 
      3 a = tf.Variable(1, name="a")
      4 b = tf.Variable(2, name="b")
      5 f = a + b

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\__init__.py in <module>()
     20 
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23 
     24 try:

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dell\AppData\Local\Enthought\Canopy\edm\envs\User\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```python
import tensorflow as tf

a = tf.Variable(1, name="a")
b = tf.Variable(2, name="b")
f = a + b

init = tf.global_variables_initializer()
with tf.Session() as s:
    init.run()
    print( f.eval() )
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
``

**Comment by harshini-gadige** [comment] 2018-10-18 17:58
@vinit13792 Hi, can you confirm if you installed msvc redistributable library ?

**Comment by vinit13792** [comment] 2018-10-26 06:36
> @vinit13792 Hi, this could be due to missing msvc redistributable library. Can you confirm if you installed this?
> Also please refer this issue #19584 and see if the suggestions provided there helps. Thank you !

Hi, i haven't installed msvc redistributable library, let me check by installing that.

**Comment by vinit13792** [comment] 2018-10-26 06:38
> @vinit13792 Hi, this could be due to missing msvc redistributable library. Can you confirm if you installed this?
> Also please refer this issue #19584 and see if the suggestions provided there helps. Thank you !

**Comment by vinit13792** [comment] 2018-10-26 06:38
> @vinit13792 Hi, this could be due to missing msvc redistributable library. Can you confirm if you installed this?
> Also please refer this issue #19584 and see if the suggestions provided there helps. Thank you !

yeah i have msvc redist lib and still i'm getting the same error.

**Comment by AlvaroSJM** [comment] 2018-11-07 16:29
Hi, I have the exact same error, any clue on how to solve it?
Many thanks!!

**Comment by AlvaroSJM** [comment] 2018-11-08 18:42
Hello vinit13792; I have followed this steps and I have finally managed to execute on jupyter notebook:
import tensorflow as tf

a = tf.Variable(1, name="a")
b = tf.Variable(2, name="b")
f = a + b

init = tf.global_variables_initializer()
with tf.Session() as s:
    init.run()
    print( f.eval() )

Step 1: install canopy (version 2.1.6)
Step 2: on the editor (NOT the command editor type and execute:     !pip install pydotplus
Step 3: on the command editor I typed and executed:      pip install tensorflow==1.10.0
   however with this I got a very strange error of Permissions
Step 4: back on the Canopy editor type and execute: !pip install tensorflow
and also; !pip install keras

And with this I managed to finally get results!!

Hope it helps

**Comment by vinit13792** [comment] 2018-11-09 06:59
> Hello vinit13792; I have followed this steps and I have finally managed to execute on jupyter notebook:
> import tensorflow as tf
> 
> a = tf.Variable(1, name="a")
> b = tf.Variable(2, name="b")
> f = a + b
> 
> init = tf.global_variables_initializer()
> with tf.Session() as s:
> init.run()
> print( f.eval() )
> 
> Step 1: install canopy (version 2.1.6)
> Step 2: on the editor (NOT the command editor type and execute: !pip install pydotplus
> Step 3: on the command editor I typed and executed: pip install tensorflow==1.10.0
> however with this I got a very strange error of Permissions
> Step 4: back on the Canopy editor type and execute: !pip install tensorflow
> and also; !pip install keras
> 
> And with this I managed to finally get results!!
> 
> Hope it helps

Hi AlvaroSSM, i tried the exact same steps which you mentioned above, and i still ended up having the same error. Any pointers as to what to do next?

**Comment by tensorflowbutler** [comment] 2018-11-23 18:36
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lyind** [comment] 2019-04-03 08:32
I tried to debug this or a related issue a little more: https://github.com/tensorflow/tensorflow/issues/27035#issuecomment-479392652

**Comment by ymodak** [comment] 2019-10-24 08:38
Apologies for the delay in response.
*TensorFlow release binaries (CPU/GPU) version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements

**Comment by gunan** [comment] 2019-11-08 19:07
Closing as duplicate of https://github.com/tensorflow/tensorflow/issues/19584

**Closed** 2019-11-08 19:09 UTC
Labels: type:build/install
