### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.optimizers'

### ISSUE THREAD

**Issue by zhaoyingjun** [tensorflow/tensorflow#27310] opened 2019-03-30 07:23 UTC
my tensorflow version is tf-nightly-2.0-preview-2.0.0.dev20190329

but when i try 'import tensorflow.optimizers.Adam',it raise ModuleNotFoundError: No module named 'tensorflow.optimizers'.

**Comment by shashvatshahi1998** [comment] 2019-03-30 16:01
Reinstall upgraded version of everything.

**Comment by jvishnuvardhan** [comment] 2019-04-02 22:07
@zhaoyingjun 
1. Were you able to run "import tensorflow as tf"
2. Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by armando-fandango** [comment] 2019-04-08 05:11
Just tried in Google Colab, tf version 2.0.0-dev20190405
`from tensorflow.optimizers import Adam`
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-24-40e5ae37d9cb> in <module>()
----> 1 from tensorflow.optimizers import Adam

ModuleNotFoundError: No module named 'tensorflow.optimizers'
```

same error with `import tensorflow.keras.optimizers.Adam` and `from tensorflow.optimizers import Adam`

However this works: `from tensorflow.keras.optimizers import Adam`

Seems like some mixed up imports in __init__ ?

**Comment by tensorflowbutler** [comment] 2019-04-22 12:59
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-04-22 16:44
@zhaoyingjun In TF2.0, keras is going to play a major role. Most of the functions (layers, optimizer...etc) are moved under keras. So you can do what @armando-fandango suggested or something like below
```
import tensorflow as tf
from tensorflow import keras
from keras.optimizers import Adam
```
I am closing this as it was resolved. Please let me know if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-04-22 16:44 UTC
Labels: 2.0, stat:awaiting response, type:build/install

**Comment by sassan72** [comment] 2020-06-21 02:52
actually, I have the same problem but your idea doesn't work.

**Comment by jvishnuvardhan** [comment] 2020-06-22 17:59
@sassan72 Please create a new issue with a simple standalone code to reproduce the issue. Thanks!
