### ISSUE TITLE
tf.math.segment_min abortion when segment_ids contains large value

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46696] opened 2021-01-26 15:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.math.segment_min` abortion when `segment_ids` contains large value
**Describe the expected behavior**
expect an exception message if the input is not expected, instead of crash.

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.math.segment_min(data=np.ones((1,2,1,1,1), dtype=np.uint16), segment_ids=[5053997376933981534])
~~~

output:
~~~python
2021-01-26 15:49:10.870684: F tensorflow/core/framework/tensor_shape.cc:405] Check failed: 0 <= new_num_elements (0 vs. -8338749319841588546)
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment] 2021-01-27 04:58
I ran the code on tf 2.4 and nightly colab crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7b803fee1ccf099305e738c5cb124824/untitled505.ipynb).

**Comment by rmothukuru** [comment] 2021-02-05 08:12
@DNXie,
Can you please confirm if we can close this issue as this case has been covered in #46888? Thanks!

**Comment by DNXie** [comment] 2021-02-08 03:20
@rmothukuru Yes it should be covered by #46888

**Comment by rmothukuru** [comment] 2021-02-08 06:29
Closing the issue as it is the duplicate of #46888. Thanks!

**Closed** 2021-02-08 06:30 UTC
Labels: TF 2.1, comp:ops, stat:awaiting response, type:bug
