### ISSUE TITLE
TFLite model gives random outputs when running on Android

### ISSUE THREAD

**Issue by ryanaleksander** [tensorflow/tensorflow#43071] opened 2020-09-09 10:33 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10E
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
On desktop, my saved_model works perfectly fine. I converted it to TFLite format, tested it using Python API, and it also worked perfectly fine. However, when I deployed it to an Android phone, it would give very bizarre and often very random outputs. To be more specific, the output is supposed to be a 1x256x256x1 tensor with each value normally falling in the range of 0.05 ~ 1. However, on android, the values often drop below 1e-27 or reach above 1e25, seemingly at random. Sometimes the first run would give the correct values, but the subsequent runs would output smaller and smaller values. 

**Describe the expected behavior**
The TFLite model running on android should return outputs with values similar to that when running on desktop.

**Standalone code to reproduce the issue**
Android code
```
    private var options = Interpreter.Options()
    private val modelFile = File(assetFilePath(context, segmentationModulePath))
    private var interpreter: Interpreter
    private var imageProcessor: ImageProcessor

    init {
        options.addDelegate(GpuDelegate())
        options.setNumThreads(4)
        interpreter = Interpreter(modelFile, options)
        imageProcessor = ImageProcessor.Builder()
            .add(ResizeOp(IMAGE_WIDTH, IMAGE_HEIGHT, ResizeOp.ResizeMethod.BILINEAR))
            .add(NormalizeOp(IMAGE_MEAN, IMAGE_STD))
            .build()
    }

    fun loadImage(bitmap: Bitmap): TensorImage {
        val image = TensorImage(DataType.FLOAT32)
        image.load(bitmap)
        return imageProcessor.process(image)
    }
// The main executing function
    fun infer(bmp: Bitmap): Bitmap {
        val input = loadImage(bmp)
        val output = TensorBuffer.createFixedSize(intArrayOf(1, 256, 256, 1), DataType.FLOAT32)
        val start = System.nanoTime()
        interpreter.run(input.buffer, output.buffer)
// Omitted 
    }
    companion object {
        private const val IMAGE_WIDTH = 256
        private const val IMAGE_HEIGHT = 256
        private const val IMAGE_MEAN = 127.5f
        private const val IMAGE_STD = 127.5f
    }
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
The model is attached.
[shm.zip](https://github.com/tensorflow/tensorflow/files/5194486/shm.zip)

**Comment by lu-wang-g** [comment] 2020-09-10 21:29
Not sure how you could invoke "input.buffer", since TensorImage does not have the field "buffer". Please try using getBuffer() instead. You image is passed in as a Bitmap, calling getBuffer() will convert the Bitmap instance into a TensorBuffer instance, and then return the ByteBuffer representation of the underlying image.

**Comment by ryanaleksander** [comment] 2020-09-11 01:42
@lu-wang-g The code is in Kotlin, `input.buffer` is equivalent to `input.getBuffer()` in Java

**Comment by lu-wang-g** [comment] 2020-09-11 02:46
Could you please verify if input.buffer changes when invoking loadImage(bmp) multiple times?

**Comment by ryanaleksander** [comment] 2020-09-21 02:41
Sorry for the late reply, input.buffer remains the same when invoked multiple times

**Comment by lu-wang-g** [comment] 2020-09-21 22:33
No worries. Just want to confirm the issue, do you mean that when invoking the following code for multiple times: 
   interpreter.run(input.buffer, output.buffer),
output.buffer may vary even if feeding the same input.buffer?

**Comment by ryanaleksander** [comment] 2020-09-22 04:54
Yes

**Comment by lu-wang-g** [comment] 2020-09-23 02:11
OK, one more question, do you use multithreading in your code, not the multithreading of the interpreter through setNumThreads() (that is fine), but the multithreading of your entire inference? Could it be possible that input.buffer is changed during interpreter.run()? Note that the interpreter API is not thread safe.

**Comment by ryanaleksander** [comment] 2020-09-25 07:23
No, I use no multithreading in my code

**Comment by lu-wang-g** [comment] 2020-09-25 19:43
I'll need to dig into the issue and see what happened exactly. Your model's input and output look very similar as our [style transfer models](https://www.tensorflow.org/lite/models/style_transfer/overview#performance_benchmarks). Could you please verify if the issue exist with our style transfer models? And then I can use that model to reproduce the issue.

**Comment by sushreebarsa** [comment] 2021-08-09 14:26
@ryanaleksander  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-23 15:52 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.1
