### ISSUE TITLE
Error if input size (of test set) not divisible by TPU core count. "InvalidArgumentError: slice index 0 of dimension 0 out of bounds." or "AssertionError: batch_size must be divisible by the number of TPU cores in use (7 vs 8)"

### ISSUE THREAD

**Issue by AaronSpieler** [tensorflow/tensorflow#27313] opened 2019-03-30 09:35 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary):  Google Colab
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: release 10.0, V10.0.130
- GPU model and memory: Google Colab TPU

**Describe the current behavior**

The following error occurs:

```

Train on 10000 samples, validate on 1153031 samples
Epoch 1/25
INFO:tensorflow:New input shapes; (re-)compiling: mode=train (# of cores 8), [TensorSpec(shape=(128,), dtype=tf.int32, name='core_id0'), TensorSpec(shape=(128, 650), dtype=tf.float32, name='input_10'), TensorSpec(shape=(128, 1), dtype=tf.float32, name='activation_7_target_10')]
INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Remapping placeholder for input_1
INFO:tensorflow:Started compiling
INFO:tensorflow:Finished compiling. Time elapsed: 7.617780447006226 secs
INFO:tensorflow:Setting weights on TPU model.
 8192/10000 [=======================>......] - ETA: 4s - loss: 1.5425 - mean_squared_error: 1.5425INFO:tensorflow:New input shapes; (re-)compiling: mode=train (# of cores 8), [TensorSpec(shape=(98,), dtype=tf.int32, name='core_id0'), TensorSpec(shape=(98, 650), dtype=tf.float32, name='input_10'), TensorSpec(shape=(98, 1), dtype=tf.float32, name='activation_7_target_10')]
INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Remapping placeholder for input_1
INFO:tensorflow:Started compiling
INFO:tensorflow:Finished compiling. Time elapsed: 6.491861820220947 secs
 9216/10000 [==========================>...] - ETA: 2s - loss: 1.4734 - mean_squared_error: 1.4734INFO:tensorflow:New input shapes; (re-)compiling: mode=eval (# of cores 8), [TensorSpec(shape=(128,), dtype=tf.int32, name='core_id_10'), TensorSpec(shape=(128, 650), dtype=tf.float32, name='input_10'), TensorSpec(shape=(128, 1), dtype=tf.float32, name='activation_7_target_10')]
INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Remapping placeholder for input_1
INFO:tensorflow:Started compiling
INFO:tensorflow:Finished compiling. Time elapsed: 5.56870174407959 secs
INFO:tensorflow:New input shapes; (re-)compiling: mode=eval (# of cores 8), [TensorSpec(shape=(0,), dtype=tf.int32, name='core_id_10'), TensorSpec(shape=(0, 650), dtype=tf.float32, name='input_10'), TensorSpec(shape=(0, 1), dtype=tf.float32, name='activation_7_target_10')]

---------------------------------------------------------------------------

InvalidArgumentError                      Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1658   try:
-> 1659     c_op = c_api.TF_FinishOperation(op_desc)
   1660   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 0 of dimension 0 out of bounds. for 'strided_slice_3' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.

During handling of the above exception, another exception occurred:
```
So basically the input shapes gets remapped to something nonesensical:  (0,)

**Describe the expected behavior**

Input shapes get remapped to something that makes sense.

**Code to reproduce the issue**

```
def train_on_TPU_regression(model,model_save_loc, X_train, y_train, X_test, y_test, batch_size=1024, epochs=25, save_best_only=True, period=1, train_patience=5, mse=True):
 
  #Identify TPU worker
  TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
  tf.logging.set_verbosity(tf.logging.INFO)
  
  #Useful to avoid clutter from old models / layers.
  tf.keras.backend.clear_session()

  #Convert model to TPU model
  tpu_model = tf.contrib.tpu.keras_to_tpu_model(model,strategy=tf.contrib.tpu.TPUDistributionStrategy(tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))
  
  print("\n")

  if mse:
    #Compile the model
    tpu_model.compile(
      optimizer=tf.train.AdamOptimizer(), 
      loss=tf.keras.losses.mean_squared_error,
      metrics=['mse']
    )
  else:
    #Compile the model
    tpu_model.compile(
      optimizer=tf.train.AdamOptimizer(), 
      loss=tf.keras.losses.mean_absolute_error,
      metrics=['mae']
    )
  
  #Configure how to save model and early stopping
  callbacks_list = [
      tf.keras.callbacks.ModelCheckpoint(
          filepath=model_save_loc,
          save_weights_only=True,
          monitor='val_loss', 
          save_best_only=save_best_only,
          mode='auto',
          period=period),
      tf.keras.callbacks.EarlyStopping(monitor='val_loss', 
                                       patience=train_patience,
                                       mode='auto')
  ]
  
  history = tpu_model.fit(X_train,
                          y_train,
                          validation_data=(X_test,y_test),
                          epochs=epochs,
                          batch_size=batch_size,
                          callbacks=callbacks_list,
                          verbose=1)

  return tpu_model, history
```
```
print(X_train.shape)
print(y_train_scaled.shape)
print(X_test.shape)
print(y_test_scaled.shape)

(6533755, 650)
(6533755,)
(1153031, 650)
(1153031,)
```

```
inputs = tf.keras.layers.Input(shape=(SEQUENCE_LEN,))

x = tf.keras.layers.Embedding(CLASSES, 8, input_length=SEQUENCE_LEN)(inputs) 
x = tf.keras.layers.Conv1D(128, 7)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.Conv1D(128, 3)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.Conv1D(128, 3)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)

x = tf.keras.layers.MaxPooling1D(3)(x)
x = tf.keras.layers.Conv1D(256, 3)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.Conv1D(256, 3)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.Conv1D(256, 3)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)

x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(256)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.Dense(1)(x)
x = tf.keras.layers.Activation("linear")(x)

model = tf.keras.Model(inputs=inputs, outputs=x)
model.summary()
```

```
tpu_model, history = train_on_TPU_regression(model,model_saves_folder_location+"model_#01_08.hdf5", X_train[:10000], y_train_scaled[:10000], X_test, y_test_scaled, train_patience=10, batch_size=1024)
```

**How it can be prevented apparently**

```
tpu_model, history = train_on_TPU_regression(model,model_saves_folder_location+"model_#01_08.hdf5", X_train[:10000], y_train_scaled[:10000], X_test[:-7], y_test_scaled[:-7], train_patience=10, batch_size=1024)
```
By changing the size of the training data this error can be prevented? In this case I made the number of training examples divisible by 1024, however, it worked too by just using 10000: `X_test[:10000], y_test_scaled[:10000]`, which is how i noticed this in the first place.

**Question:**
It this really a bug or am I missing something?

**UPDATE**

When trying to predict, I get the following error:

```
TPU worker setup:
INFO:tensorflow:Querying Tensorflow master (grpc://10.14.138.218:8470) for TPU system metadata.
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 13438656196918098020)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 12429978056820721148)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 3813600547282296097)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 18120823110831817385)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 429246965946293269)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 5942823189813875074)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 1996329778228354684)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 15775279347369926923)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 6250325552725876457)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 17570123092856457982)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184, 3640626136020975642)
WARNING:tensorflow:tpu_model (from tensorflow.contrib.tpu.python.tpu.keras_support) is experimental and may change or be removed at any time, and without warning.


Calculating predictions:
INFO:tensorflow:New input shapes; (re-)compiling: mode=infer (# of cores 8), [TensorSpec(shape=(4, 650), dtype=tf.float32, name='input_10')]
INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Remapping placeholder for input_1
INFO:tensorflow:Started compiling
INFO:tensorflow:Finished compiling. Time elapsed: 2.8085508346557617 secs
INFO:tensorflow:Setting weights on TPU model.
1152832/1153031 [============================>.] - ETA: 0s

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-36-aa8045e6a687> in <module>()
----> 1 y_preds, rmse_err, mae_err = calc_reg_pred(model, weights_location, X_test, y_test, mse=True, scaler=y_train_scaled)

<ipython-input-35-fc3b6ce0949b> in calc_reg_pred(model, weight_loc, X_test, y_test, batch_size, mse, scaler)
     32 
     33   print("Calculating predictions:")
---> 34   y_pred = cpu_model.predict(X_test, verbose=1)
     35 
     36   if not(scaler is None):

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in predict(self, x, batch_size, verbose, steps, max_queue_size, workers, use_multiprocessing)
   1982           max_queue_size=max_queue_size,
   1983           workers=workers,
-> 1984           use_multiprocessing=use_multiprocessing)
   1985 
   1986   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, max_queue_size, workers, use_multiprocessing)
   1111     else:
   1112       return training_arrays.predict_loop(
-> 1113           self, x, batch_size=batch_size, verbose=verbose, steps=steps)
   1114 
   1115   def reset_metrics(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, mode, validation_in_fit, **kwargs)
    327 
    328         # Get outputs.
--> 329         batch_outs = f(ins_batch)
    330         if not isinstance(batch_outs, list):
    331           batch_outs = [batch_outs]

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in __call__(self, inputs)
   1254     infeed_manager = self._lookup_infeed_manager(inputs)
   1255     input_tensors, inputs = self._construct_input_tensors_and_inputs(inputs)
-> 1256     infeed_instance = infeed_manager.make_infeed_instance(inputs)
   1257     del inputs  # To avoid accident usage.
   1258     input_specs = infeed_instance.make_input_specs(input_tensors)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in make_infeed_instance(self, inputs)
    663 
    664   def make_infeed_instance(self, inputs):
--> 665     sharded_inputs = self._split_tensors(inputs)
    666     return self.NumpyInfeedInstance(sharded_inputs)
    667 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _split_tensors(self, inputs)
    652     assert batch_size % self._tpu_assignment.num_towers == 0, (
    653         'batch_size must be divisible by the number of TPU cores in use (%s '
--> 654         'vs %s)' % (batch_size, self._tpu_assignment.num_towers))
    655     shard_size = batch_size // self._tpu_assignment.num_towers
    656     input_list = []

AssertionError: batch_size must be divisible by the number of TPU cores in use (7 vs 8)
```

I get the error, even though my batch size was 128 and later 1024. Then I again applied `X_test[:-7], y_test[:-7]` and the error is gone. 
*So I would conclude that the TPU currently cant handle imput sizes not divisible by muber of TPUs for prediction.*

**Comment by vmehera123** [comment] 2019-05-20 05:06
i have got the same issue, but the error occurs when trying "fit_generator" method on TPU model (the same one with "fit" works fine)

**Comment by ChouWeizhong** [comment] 2019-07-12 17:29
Hi, I have the same problem when training the model on colab with TPU.
1.Using Tensorflow 1.13.1 (Other lib are colab's Default)
2.Using tf.Keras and using `tf.contrib.tpu.keras_to_tpu_model`
3.Using fit_generator(Because my data is too big)

**Problem is at beginning the training will run for a while.**
At begining I think there's some data error.
But then I training the same data and code with GPU and success.
So during training of TPU some error happend.

looks like reason from the data generator.
I build a data generator by 'class DataGenerator(tf.keras.utils.Sequence):'
And because reading data is slow(big image data),
I use use_multiprocessing , workers and max_queue_size .
'
model.fit_generator(train_data,
                    steps_per_epoch = steps_per_epoch,
                    epochs = 30,
                    callbacks=callbacks,
                    validation_data = validation_data,
                    validation_steps = validation_steps,
                    use_multiprocessing = True,
                    workers = 8,
                    max_queue_size = 24
                   )
'

Here is my log when training.
'
y_pred shape (?, 32, 80, 80, 2)
y_true shape (?, ?, ?, ?, ?)
INFO:tensorflow:Querying Tensorflow master (grpc://10.79.62.194:8470) for TPU system metadata.
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 4592675977746479807)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 3835905418955304939)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 9973634016239195625)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 7412254046126854739)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 1251060567783699712)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 159592003167631933)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 3555001218257168182)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 497511677534294237)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 3996482485963028891)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 14345708154009247026)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 13869207026421776388)
WARNING:tensorflow:tpu_model (from tensorflow.contrib.tpu.python.tpu.keras_support) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Cloning Adam {'lr': 0.0010000000474974513, 'beta_1': 0.8999999761581421, 'beta_2': 0.9990000128746033, 'decay': 0.0, 'epsilon': 1e-07, 'amsgrad': False}
INFO:tensorflow:Cloning Adam {'lr': 0.0010000000474974513, 'beta_1': 0.8999999761581421, 'beta_2': 0.9990000128746033, 'decay': 0.0, 'epsilon': 1e-07, 'amsgrad': False}

Epoch 1/30
INFO:tensorflow:New input shapes; (re-)compiling: mode=train (# of cores 8), [TensorSpec(shape=(1,), dtype=tf.int32, name='core_id0'), TensorSpec(shape=(1, 32, 80, 80, 1), dtype=tf.float32, name='input_10'), TensorSpec(shape=(1, 32, 80, 80, 2), dtype=tf.float32, name='segmentation_2classes_target_30')]

INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Cloning Adam {'lr': 0.0010000000474974513, 'beta_1': 0.8999999761581421, 'beta_2': 0.9990000128746033, 'decay': 0.0, 'epsilon': 1e-07, 'amsgrad': False}
INFO:tensorflow:Remapping placeholder for input
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py:302: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:KerasCrossShard: <tensorflow.python.keras.optimizers.Adam object at 0x7ff0efe11d30> []
y_pred shape (8, 32, 80, 80, 2)
y_true shape (8, 32, 80, 80, 2)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
INFO:tensorflow:Started compiling
INFO:tensorflow:Finished compiling. Time elapsed: 67.50986790657043 secs
INFO:tensorflow:Setting weights on TPU model.
INFO:tensorflow:CPU -> TPU lr: 0.0010000000474974513 {0.001}
INFO:tensorflow:CPU -> TPU beta_1: 0.8999999761581421 {0.9}
INFO:tensorflow:CPU -> TPU beta_2: 0.9990000128746033 {0.999}
INFO:tensorflow:CPU -> TPU decay: 0.0 {0.0}
WARNING:tensorflow:Cannot update non-variable config: epsilon
WARNING:tensorflow:Cannot update non-variable config: amsgrad
233/363 [==================>...........] - ETA: 7:52 - loss: 0.4663 - dice: 0.4089INFO:tensorflow:New input shapes; (re-)compiling: mode=train (# of cores 8), [TensorSpec(shape=(0,), dtype=tf.int32, name='core_id0'), TensorSpec(shape=(0, 32, 80, 80, 1), dtype=tf.float32, name='input_10'), TensorSpec(shape=(0, 32, 80, 80, 2), dtype=tf.float32, name='segmentation_2classes_target_30')]
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1658   try:
-> 1659     c_op = c_api.TF_FinishOperation(op_desc)
   1660   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 0 of dimension 0 out of bounds. for 'strided_slice_1' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.

During handling of the above exception, another exception occurred:
.......
'

**Comment by ChouWeizhong** [comment] 2019-07-12 19:59
I find the reason!
The error said new input size.
So there must be something wrong with input data.
I finally checked out my batch generator didn't worked well.
When using fit_generator with  Class 'DataGenerator(tf.keras.utils.Sequence):'
,steps_per_epoch  didn't work.
Example I set steps_per_epoch  362 but still in training is 363.
'''
233/363 [==================>...........] - ETA: 7:52 - loss: 0.4663 - dice: 0.4089INFO:tensorflow:New input shapes; (re-)compiling: mode=train (# of cores 8), [TensorSpec(shape=(0,), dtype=tf.int32, name='core_id0'), TensorSpec(shape=(0, 32, 80, 80, 1), dtype=tf.float32, name='input_10'), TensorSpec(shape=(0, 32, 80, 80, 2), dtype=tf.float32, name='segmentation_2classes_target_30')]
'''

**Comment by gadagashwini** [comment] 2019-08-02 06:13
@AaronSpieler Is this still an issue? Can you please provide the complete code to reproduce the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-08-17 12:21
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jmgc** [comment] 2019-08-17 21:56
I have a similar issue. In my case I have a Dataset with shape (None, 5, 128, 128, 1). If I try to train a Sequence keras Model with fit, I get the error:

InvalidArgumentError: First dim of input shape: 5 is not divisible by num_workers: 8

I use the TPU colaboratory environment in eager mode and with a TPUStrategy.

**Comment by jmgc** [comment] 2019-08-18 06:10
After some tests, I have found that the issue in my case is related with the batch size. Calling the method Dataset.batch with a multiple of 8 number has solved the problem.

**Comment by gadagashwini** [comment] 2019-08-19 05:50
@jmgc, 
Can you please post a new issue by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

**Comment by gadagashwini** [comment] 2019-08-19 05:51
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-19 05:51 UTC
Labels: comp:tpus, stat:awaiting response, type:support
