### ISSUE TITLE
In tensorflow, why does a 6B GPU show with memory limit than 5GB of VRAM?

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#27065] opened 2019-03-23 19:09 UTC
I have a 6GB 1060 GPU. Running:

```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```
gives

```
name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 4951913267
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 15506209764385210283
 physical_device_desc: "device: 0, name: GeForce GTX 1060 6GB, 
pci bus id: 0000:02:00.0, compute capability: 6.1"
```
Notice it is showing memory_limit of 4951913267, which is 1.1GB short of 6GB.  Where did my 1.1GB go?

**Comment by gshashank84** [comment] 2019-03-24 08:35
I think there is a limit(set by system) to what extent you can utilize your virtual memory of GPU, therefore the default size is set to 5GB. However it can be clocked further upto the actual size.

**Comment by ymodak** [comment] 2019-03-26 20:14
> I think there is a limit(set by system) to what extent you can utilize your virtual memory of GPU, therefore the default size is set to 5GB. However it can be clocked further upto the actual size.

The above explanation is correct. Closing this issue since the issue is not at TensorFlow end. Thanks!

**Closed by ymodak** 2019-03-26 20:14 UTC
Labels: comp:gpu, type:support
