### ISSUE TITLE
Why i have same value in confusion matrix always 12% even after 17000 lerning rate?

### ISSUE THREAD

**Issue by konradqweleg** [tensorflow/tensorflow#36867] opened 2020-02-18 20:14 UTC
Model after train don,t work and Confusion matrix have one column value other column 0

**Comment by amahendrakar** [comment] 2020-02-19 06:57
@konradqweleg,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by konradqweleg** [comment] 2020-02-19 15:52
I used the default train.py

**Comment by amahendrakar** [comment] 2020-02-29 07:03
@konradqweleg,
Could you please send a link of the project or share the notebook of your python code? Thanks!

**Comment by konradqweleg** [comment] 2020-02-29 10:13
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands

**Comment by amahendrakar** [comment] 2020-03-04 14:11
@konradqweleg,
This was the final output on running the above code. I have attached the complete log as a file.
```
INFO:tensorflow:Step 18000: Validation accuracy = 88.3% (N=4445)
I0303 22:32:58.230043 139990098704192 train.py:289] Step 18000: Validation accuracy = 88.3% (N=4445)
INFO:tensorflow:Saving to "/tmp/speech_commands_train/conv.ckpt-18000"
I0303 22:32:58.230095 139990098704192 train.py:297] Saving to "/tmp/speech_commands_train/conv.ckpt-18000"
INFO:tensorflow:set_size=4890
I0303 22:32:58.251442 139990098704192 train.py:301] set_size=4890
WARNING:tensorflow:Confusion Matrix:
 [[407   0   0   0   0   0   0   0   0   0   1   0]
 [  3 272   7   7  16  16  25  21  13   6   9  13]
 [  1   6 396   4   0   0   9   0   0   0   2   1]
 [  0   8   8 345   1  12   8   1   0   0   1  21]
 [  2   4   0   1 392   1   3   0   5   6   9   2]
 [  1  10   7  27   2 341   4   0   2   0   0  12]
 [  2   2  15   0   4   0 384   3   0   0   2   0]
 [  3  16   1   1   0   0  11 362   1   1   0   0]
 [  1   9   0   0   9   8   1   1 348  17   2   0]
 [  2   8   0   0  38   1   4   1  10 332   3   3]
 [  2   1   1   0  12   2   1   0   0   2 388   2]
 [  4  13   1  54   8  10   5   4   0   2   1 300]]
W0303 22:33:23.295454 139990098704192 train.py:320] Confusion Matrix:
 [[407   0   0   0   0   0   0   0   0   0   1   0]
 [  3 272   7   7  16  16  25  21  13   6   9  13]
 [  1   6 396   4   0   0   9   0   0   0   2   1]
 [  0   8   8 345   1  12   8   1   0   0   1  21]
 [  2   4   0   1 392   1   3   0   5   6   9   2]
 [  1  10   7  27   2 341   4   0   2   0   0  12]
 [  2   2  15   0   4   0 384   3   0   0   2   0]
 [  3  16   1   1   0   0  11 362   1   1   0   0]
 [  1   9   0   0   9   8   1   1 348  17   2   0]
 [  2   8   0   0  38   1   4   1  10 332   3   3]
 [  2   1   1   0  12   2   1   0   0   2 388   2]
 [  4  13   1  54   8  10   5   4   0   2   1 300]]
WARNING:tensorflow:Final test accuracy = 87.3% (N=4890)
```
[output.txt](https://github.com/tensorflow/tensorflow/files/4287692/output.txt)

Could you please compare this output with yours and if the issue persists, send us the reproducible code with the output. Thanks!

**Comment by amahendrakar** [comment] 2020-03-11 14:35
Any updates regarding this issue? Thanks!

**Comment by konradqweleg** [comment] 2020-03-11 16:29
So My final output is  same to
 [[407   0   0   0   0   0   0   0   0   0  0   0]
 [  272  0  0  0  0  0  0   0   0  0   0   0]
everywhere 
I will give the results tomorrow

**Comment by amahendrakar** [comment] 2020-03-18 05:29
@konradqweleg,
Any updates regarding the results? Thanks!

**Comment by amahendrakar** [comment] 2020-03-27 04:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-03-27 04:27 UTC
Labels: TF 2.1, comp:lite, stat:awaiting response, type:support
