### ISSUE TITLE
python mnist_softmax_xla.py run failure

### ISSUE THREAD

**Issue by zhangdingfei** [tensorflow/tensorflow#10982] opened 2017-06-22 12:09 UTC
Hi,
I run python mnist_softmax_xla.py and got below failure:

linux-swfm:~/workarea/test> python3 mnist_softmax_xla.py   
...
2017-06-22 20:02:52.685534: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (1): Tesla K40m, Compute Capability 3.5
2017-06-22 20:02:57.741927: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user->operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7f30cc012550 vs. 0x7f30cc021490)
Aborted

my tensorflow version is tensorflow-1.1.0
cuda sdk: 7.5

**Comment by rohan100jain** [comment] 2017-06-23 23:13
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by zhangdingfei** [comment] 2017-06-24 02:34
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: SUSE Linux Enterprise Server 11 SP3  (x86_64)
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: tensorflow-1.1.0
- **Bazel version (if compiling from source)**: bazel release 0.5.0- (@non-git)
- **CUDA/cuDNN version**: CUDA 7.5/cuDNN 5.1
- **GPU model and memory**: Tesla K40m
- **Exact command to reproduce**: python3 mnist_softmax_xla.py

### Describe the problem
when run python3 mnist_softmax_xla.py, I met a assertion failure.

my build command is :
bazel build --c dbg --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Source code / logs

linux-swfm:~/workarea> python3 mnist_softmax_xla.py
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
2017-06-24 10:28:06.834688: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-24 10:28:06.834747: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-24 10:28:06.834762: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-24 10:28:06.834787: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-24 10:28:06.834809: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-24 10:28:07.156861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:04:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
2017-06-24 10:28:07.157144: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x7ff0ac098f10
2017-06-24 10:28:07.460466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 1 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:83:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
2017-06-24 10:28:07.460571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 0 and 1
2017-06-24 10:28:07.460613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:779] Peer access not supported between device ordinals 1 and 0
2017-06-24 10:28:07.460672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 1 
2017-06-24 10:28:07.460692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y N 
2017-06-24 10:28:07.460712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 1:   N Y 
2017-06-24 10:28:07.460751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:04:00.0)
2017-06-24 10:28:07.460770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K40m, pci bus id: 0000:83:00.0)
2017-06-24 10:28:07.838088: I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 2 visible devices
2017-06-24 10:28:07.838941: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 72 visible devices
2017-06-24 10:28:07.852362: I tensorflow/compiler/xla/service/service.cc:183] XLA service 0x7ff0acde4930 executing computations on platform Host. Devices:
2017-06-24 10:28:07.852407: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (0): <undefined>, <undefined>
2017-06-24 10:28:07.852819: I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 2 visible devices
2017-06-24 10:28:07.853650: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 72 visible devices
2017-06-24 10:28:07.866012: I tensorflow/compiler/xla/service/service.cc:183] XLA service 0x7ff0ad069f30 executing computations on platform CUDA. Devices:
2017-06-24 10:28:07.866043: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2017-06-24 10:28:07.866056: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (1): Tesla K40m, Compute Capability 3.5
2017-06-24 10:28:12.890410: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user->operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7ff0b4033ba0 vs. 0x7ff0b404d3e0)
Aborted

**Comment by ali01** [comment] 2017-06-30 17:22
This may be due to lack of python3 support. @tfboyd, care to take a look?

**Comment by tfboyd** [comment] 2017-06-30 18:12
I will take a look.  I have doubts python3 matters.

**Comment by tfboyd** [comment] 2017-07-05 16:51
Ping myself.  My test will be weak.  I am going to give this a try locally today with python2 and head just to make sure nothing is wrong.

**Comment by tfboyd** [comment] 2017-07-05 19:31
I know this is not super helpful although I had an idea at the end.  I just ran the following setup and the example worked.  I double checked the timeline to ensure XLA was 100% running:

- CUDA 8
- cuDNN 5.1
- TF (head past 1.2):  3a64879a86e46908ad90a387efe56ad32be61e94
- GTX 1080, which should not matter
- Python2.7, I doubt python is the issue as the error is coming from the `op` but it would not be the first time I was really wrong.  
- The AVX,SSE stuff also doesn't matter and we are working on a simpler warning.

Completely random thought.  I see you have two GPUs.  The code is not setup for multi-GPU, the example is also really basic but still I wonder if that is creating a problem.  You could try with one GPU and run something like this to try it out.  I have never tried the example on multi-GPU.      

```bash
CUDA_VISIBLE_DEVICES=0 python mnist_softmax_xla.py
```

**Comment by zhangdingfei** [comment] 2017-07-06 02:16
I tried with one GPU, but got the same failure.

linux-swfm:~/workarea> CUDA_VISIBLE_DEVICES=0 python3  mnist_softmax_xla.py
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
2017-07-06 10:07:08.126795: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 10:07:08.126848: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 10:07:08.126862: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 10:07:08.126872: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 10:07:08.126886: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 10:07:12.868401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:04:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
2017-07-06 10:07:12.868480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-07-06 10:07:12.868498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-07-06 10:07:12.868534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:04:00.0)
2017-07-06 10:07:13.073789: I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 1 visible devices
2017-07-06 10:07:13.074631: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 72 visible devices
2017-07-06 10:07:13.086519: I tensorflow/compiler/xla/service/service.cc:183] XLA service 0x7f96e89c4d40 executing computations on platform Host. Devices:
2017-07-06 10:07:13.086559: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (0): <undefined>, <undefined>
2017-07-06 10:07:13.086943: I tensorflow/compiler/xla/service/platform_util.cc:58] platform CUDA present with 1 visible devices
2017-07-06 10:07:13.087747: I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 72 visible devices
2017-07-06 10:07:13.099575: I tensorflow/compiler/xla/service/service.cc:183] XLA service 0x7f96e8c4a370 executing computations on platform CUDA. Devices:
2017-07-06 10:07:13.099606: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2017-07-06 10:07:17.919040: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user->operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7f96e8c6dc70 vs. 0x7f96e8c9f6b0)
Aborted

**Comment by tfboyd** [comment] 2017-07-06 16:46
My final thought is to compile the latest version from head, which is where I started.  It is entirely possible there was an XLA issue in the 1.1 branch.  I would also use CUDA 8.  With XLA being experimental I try to stick with the most common settings and the most recent code.

I know this can be frustrating and is why it is still marked as experimental.  If I think of anything else I will update this issue.

**Comment by tensorflowbutler** [comment] 2017-12-20 19:07
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-04 19:23
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:23
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tfboyd** [comment] 2018-01-24 19:41
Adding @hpucha incase there is interest in fixing or enhancing the tutorial or close.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:11
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:15
Nagging Assignee @hpucha: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:37
Nagging Assignee @hpucha: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hpucha** [comment] 2018-04-04 19:33
I retried the tutorial again locally (with TitanX, CUDA 8 and the latest Tensorflow version) and it worked. 

I'm going to close this because I couldn't reproduce this issue in the latest version. But please don't hesitate to reopen this if it's still not working for you. 

Thank you!

**Closed by hpucha** 2018-04-04 19:33 UTC
Labels: type:build/install
