### ISSUE TITLE
A bug in TF2.0 that prevents tf.int32 tensor to be placed on GPU (but tf.int16/64 or tf.float32 is fine)

### ISSUE THREAD

**Issue by gtg162y** [tensorflow/tensorflow#33835] opened 2019-10-30 00:45 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 'v2.0.0-rc2-26-g64c3d38' and '2.0.0' (GPU version)
- Python version: 3.x
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Colab GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Cannot put an int32 tensor on a GPU. But can put an int16/int64/float32 on a GPU.

**Describe the expected behavior**
Should be able to place an int32 tensor on a GPU.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

#####################################
with tf.device('GPU:0'):
&nbsp;&nbsp;&nbsp;&nbsp; var = tf.constant([1,2,3], dtype=tf.int32) #doesn't work
&nbsp;&nbsp;&nbsp;&nbsp; print(var.device) #wrongly puts on CPU
&nbsp;&nbsp;&nbsp;&nbsp; var = tf.constant([1,2,3], dtype=tf.int16) #works fine
&nbsp;&nbsp;&nbsp;&nbsp; print(var.device) #correctly puts on GPU

prints the following:
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0
#####################################
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ppham27** [comment] 2019-10-30 18:36
Yes, there's a reason for that. I'm afraid it might be intended behavior.

https://github.com/tensorflow/tensorflow/blob/4eb3e36d1b0cd511e1677e740bd093f42365cf9f/tensorflow/python/eager/pywrap_tensor.cc#L352-L354

**Comment by oanush** [comment] 2019-10-31 09:16
@gtg162y ,
Can you please check the feedback from @ppham27 ?Thanks!

**Comment by gtg162y** [comment] 2019-11-01 04:25
I was not aware that most int32 kernels are placed in host memory. I understand it now, but it's just that it is restrictive to the developer who wants to put an int32 tensor on a GPU. It'd be nice if there is any way around it.

**Comment by ppham27** [comment] 2019-11-08 03:54
@gtg162y I agree that this behavior is not ideal. You avoid that codepath in the eager runtime by using `tf.function`. It's a bit hacky but maybe this workaround is acceptable.

```
import tensorflow as tf
tf.compat.v1.enable_v2_behavior()

@tf.function(autograph=False)
def f():
  with tf.device('/device:GPU:0'):
    return tf.constant([1, 2], tf.int32)

y = f()
y.dtype, y.device  # Returns (tf.int32, '/job:localhost/replica:0/task:0/device:GPU:0')
```

https://colab.research.google.com/drive/1HhNCQs5UureoQ5Iql3VvhzUMgnkzCwRR

**Comment by ymodak** [comment] 2019-11-23 00:25
Closing this issue since its resolved. Feel free to reopen if have further questions. thanks!

**Closed by ymodak** 2019-11-23 00:25 UTC
Labels: TF 2.0, comp:eager, type:support
