### ISSUE TITLE
Error installing from source

### ISSUE THREAD

**Issue by qlqqkq** [tensorflow/tensorflow#5149] opened 2016-10-23 11:44 UTC
In the procedure of installing from source, 
when I try to do "bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg"

then an error occurs and the message is like this:
"error: can't copy 'tensorflow/models/embedding/gen_word2vec.py': doesn't exist or not a regular file"

In the directory of '_tensorflow/models/embedding/_', there does not exist named "gen_word2vec.py", only "word2vec.py" is in there.
(Changing the file name "word2vec.py" as "gen_word2vec.py", but it does not make it.)

OS : OS X El Capitan(10.11.6)
TensorFlow : r0.11(Same problem occurs r0.10)

In #4234, recommended method is installing the TF's branch r0.10, but it does not work for me.
How can I solve it?

<img width="656" alt="2016-10-23 8 05 16" src="https://cloud.githubusercontent.com/assets/22737703/19625753/111ae2aa-995c-11e6-93c0-464fb1443589.png">

**Comment by asimshankar** [comment] 2016-10-24 04:01
@qlqqkq : `gen_word2vec.py` is a generated file that will be created when you run `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` and ends up in `bazel-genfiles/tensorflow/models/embedding/gen_word2vec.py`. The `build_pip_package` tool should be able to pick it up from there.

I was unable to reproduce your issue.
Could you please provide some more details, like

- Which version of bazel are you using? (`bazel version`). If less than 0.3.2, then could you upgrade to 0.3.2?
- Which git commit are you synced to when building from sources (`git rev-parse HEAD && git branch`)?
- What would be the exact sequence of steps to reproduce the problem? Were you following the instructions from [the website](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources) verbatim, or were there some commands inserted in the middle? (That might have caused the generated file to be cleaned up)

Let us know and we can try to figure this out.

**Comment by qlqqkq** [comment] 2016-10-24 04:36
a. Currently, I use bazel ver. 0.3.2
b. I use git branch(_git clone -b r.0.11 ..._ I use) to build from source.
c. describe below.

I followed instruction on the "https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources"

pre-installed : xcode - 7.2, Nvidia webdriver : 346.03.15f02

1. install pip
2. git clone -b r.0.11 https://github.com/tensorflow/tensorflow
3. install java
4. install bazel and swig
5. install python dependencies(like wheel, numpy, six)
6. install coreutils & cuda(ver. 8.0.46)
7. Add Env to bash_profile
8. about cudnn
9. configuration
10. bazel build -c opt --config=cuda ...
11. bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
and made an error in 11.
(There is no other command inserted between the procedures above.)

Thank you for your help and tell me what you want to know more about my installation procedures and details.

**Comment by asimshankar** [comment] 2016-10-24 05:22
@qlqqkq : Could you run the following set of commands and provide all the output?

```sh
ls bazel-genfiles/tensorflow/models/embedding/
bazel query --config=cuda 'somepath(//tensorflow/tools/pip_package:build_pip_package, //tensorflow/models/embedding:gen_word2vec)'
bazel build -c opt --config=cuda //tensorflow/tools/pip_backage:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
ls bazel-genfiles/tensorflow/models/embedding/
```

**Comment by qlqqkq** [comment] 2016-10-24 06:57
@asimshankar :

1st command
`ls bazel-genfiles/tensorflow/models/embedding/`
output is
`ls: bazel-genfiles/tensorflow/models/embedding/: No such file or directory`

2nd line
`bazel query --config=cuda 'somepath(//tensorflow/tools/pip_package:build_pip_package, //tensorflow/models/embedding:gen_word2vec)'`
output is
`WARNING: Config values are not defined in any .rc file: cuda`
`WARNING: /private/var/tmp/_bazel_Kusu/e92c2cbd4935130908d79abb3c6104b0/external/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of string "host" and "data correspondingly.`
`WARNING: /private/var/tmp/_bazel_Kusu/e92c2cbd4935130908d79abb3c6104b0/external/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of string "host" and "data correspondingly`
`//tensorflow/tools/pip_package:build_pip_package`
`//tensorflow/models/embedding:package`
`//tensorflow/models/embedding:gen_word2vec`

3rd line
`bazel build -c opt --config=cuda //tensorflow/tools/pip_backage:build_pip_package`
output is
`ERROR: /Users/Kusu/tensorflow/tensorflow/python/BUILD:612:1: Executing genrule //tensorflow/python:nn_ops_pygenrule failed: bash failed: error executing command /bin/bach-c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 5.`
`dyld: Library not loaded: @rpath/libcudart.8.0.dylib`
`   Referenced from: /private/var/tmp/_bazel_Kusu/e92c2cbd4935130908d79abb3c6104b0/execroot/tensorflow/bazel-out/hos/bin/tensorflow/python/gen_nn_ops_py_wrappers_cc`
`   Reason: image not found`
`/bin/bach: line 1: 15171 Trace/BPT trap:5        bazel-out/host/bin/tensorflow/python/gen_nn_ops_py_wrappers_cc @tensorflow/python/ops/hidden_ops.txt 1 > bazel-out/local_darwin-opt/genfiles/tensorflow/python/ops/gen_nn_ops.py`
`Target //tensorflow/tools/pip_package:build_pip_package failed to build`
`Use --verbose_failures to see the command lines of failed build steps`

4th line made an error I asked first.

These are all I've done.
Thank you for your help.

**Comment by asimshankar** [comment] 2016-10-24 07:37
@qlqqkq : From the commands you've described above, it seems step 3 failed (it prints out a bunch of errors). So, the `build_pip_package` binary you end up with in `bazel-bin/` is not ready to use.

Step 3 seems to be failing because of `dyld: Library not loaded: @rpath/libcudart.8.0.dylib`, which suggests that the build process is unable to find the CUDA shared libraries to link against.

Did you follow the instructions from: https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#prepare-environment-for-mac-os-x
in particular, is the `DYLD_LIBRARY_PATH` environment variable set?

**Comment by qlqqkq** [comment] 2016-10-24 07:57
@asimshankar :

I thought I correctly followed instruction on
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#prepare-environment-for-mac-os-x

After the `$ brew cask install cuda`
I added Env to my bash_profile like this

<img width="629" alt="2016-10-24 4 44 41" src="https://cloud.githubusercontent.com/assets/22737703/19637377/bacaebda-9a09-11e6-91bd-557b8a135e57.png">

I don't know what the problem is. Trying to re-install tensorflow is my only solution I can use?
Thank you for your help.

**Comment by asimshankar** [comment] 2016-10-24 08:06
What does `echo $DYLD_LIBRARY_PATH` say?

**Comment by qlqqkq** [comment] 2016-10-24 08:08
@asimshankar :

`echo $DYLD_LIBRARY_PATH`
says
`:/usr/local/cuda/lib`

**Comment by asimshankar** [comment] 2016-10-24 09:09
Hmm...this seems like #5141 where `DYLD_LIBRARY_PATH` is being ignored. Marking this as a duplicate.

We will look into a robust solution, in the mean time I don't suppose you can get by your immediate needs without using the GPU?

**Closed by asimshankar** 2016-10-24 09:09 UTC
Labels: awaiting response

**Comment by qlqqkq** [comment] 2016-10-24 10:00
I remember one of my friend installed with v0.10.0rc0(He installed it on Os X). He said tensorflow is successfully installed and imported. I don't know for sure actually work by using GPU.
Anyway, I really appreciate your help.
Thanks.
