### ISSUE TITLE
Compiling TF for Ubuntu: Failed

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#21269] opened 2018-07-31 10:39 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
No

- **TensorFlow installed from (source or binary)**:
Checked out tag origin/r1.9

- **TensorFlow version (use command below)**:
r1.9.0

- **Python version**:
3.6

- **Bazel version (if compiling from source)**:
Build label: 0.15.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 17 12:22:40 2018 (1531830160)
Build timestamp: 1531830160
Build timestamp as int: 1531830160

- **GCC/Compiler version (if compiling from source)**:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 

- **CUDA/cuDNN version**:
n/a; compiling for non-GPU machine

- **GPU model and memory**:
n/a

- **Exact command to reproduce**:
`bazel build --config opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni`

You can collect some of this information using our environment capture script:

```
(tensorflow_p36) ubuntu:/efs/tensorflow/tools$ bash tf_env_collect.sh 
Collecting system information...
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
2018-07-31 10:32:11.836897: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-31 10:32:12.013176: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-31 10:32:12.013518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-07-31 10:32:12.013553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.

cat tf_env.txt
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Here is the error message.  It doesnt say much:
```
external/curl/lib/vtls/openssl.c: At top level:
cc1: warning: unrecognized command line option "-Wno-string-plus-int" [enabled by default]
INFO: Elapsed time: 450.149s, Critical Path: 21.18s
INFO: 1372 processes: 1372 local.
FAILED: Build did NOT complete successfully
```
Here are the 100 lines that precede it:
```
In file included from external/curl/lib/vtls/openssl.c:72:0:
/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/../lib/gcc/../../include/openssl/ocsp.h:567:34: error: unknown type name 'OCSP_RESPONSE'
 int OCSP_RESPONSE_print(BIO *bp, OCSP_RESPONSE *o, unsigned long flags);
                                  ^
external/curl/lib/vtls/openssl.c: In function 'verifystatus':
external/curl/lib/vtls/openssl.c:1262:3: error: unknown type name 'OCSP_RESPONSE'
   OCSP_RESPONSE *rsp = NULL;
   ^
external/curl/lib/vtls/openssl.c:1267:3: warning: implicit declaration of function 'SSL_get_tlsext_status_ocsp_resp' [-Wimplicit-function-declaration]
   long len = SSL_get_tlsext_status_ocsp_resp(connssl->handle, &p);
   ^
external/curl/lib/vtls/openssl.c:1275:3: warning: implicit declaration of function 'd2i_OCSP_RESPONSE' [-Wimplicit-function-declaration]
   rsp = d2i_OCSP_RESPONSE(NULL, &p, len);
   ^
external/curl/lib/vtls/openssl.c:1275:7: warning: assignment makes pointer from integer without a cast [enabled by default]
   rsp = d2i_OCSP_RESPONSE(NULL, &p, len);
       ^
external/curl/lib/vtls/openssl.c:1282:3: warning: implicit declaration of function 'OCSP_response_status' [-Wimplicit-function-declaration]
   ocsp_status = OCSP_response_status(rsp);
   ^
external/curl/lib/vtls/openssl.c:1290:3: warning: implicit declaration of function 'OCSP_response_get1_basic' [-Wimplicit-function-declaration]
   br = OCSP_response_get1_basic(rsp);
   ^
external/curl/lib/vtls/openssl.c:1290:6: warning: assignment makes pointer from integer without a cast [enabled by default]
   br = OCSP_response_get1_basic(rsp);
      ^
external/curl/lib/vtls/openssl.c:1374:3: warning: implicit declaration of function 'OCSP_RESPONSE_free' [-Wimplicit-function-declaration]
   OCSP_RESPONSE_free(rsp);
   ^
external/curl/lib/vtls/openssl.c: In function 'ossl_connect_step1':
external/curl/lib/vtls/openssl.c:2061:5: warning: implicit declaration of function 'SSL_set_tlsext_status_type' [-Wimplicit-function-declaration]
     SSL_set_tlsext_status_type(connssl->handle, TLSEXT_STATUSTYPE_ocsp);
     ^
external/curl/lib/vtls/openssl.c: In function 'get_cert_chain':
external/curl/lib/vtls/openssl.c:2390:9: warning: passing argument 1 of 'X509_get0_signature' from incompatible pointer type [enabled by default]
         X509_get0_signature(&psig, &palg, x);
         ^
In file included from external/boringssl/src/include/openssl/pem.h:66:0,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/x509.h:761:21: note: expected 'const struct ASN1_BIT_STRING **' but argument is of type 'struct ASN1_BIT_STRING **'
 OPENSSL_EXPORT void X509_get0_signature(const ASN1_BIT_STRING **psig,
                     ^
external/curl/lib/vtls/openssl.c:2390:9: warning: passing argument 2 of 'X509_get0_signature' from incompatible pointer type [enabled by default]
         X509_get0_signature(&psig, &palg, x);
         ^
In file included from external/boringssl/src/include/openssl/pem.h:66:0,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/x509.h:761:21: note: expected 'const struct X509_ALGOR **' but argument is of type 'struct X509_ALGOR **'
 OPENSSL_EXPORT void X509_get0_signature(const ASN1_BIT_STRING **psig,
                     ^
external/curl/lib/vtls/openssl.c:2455:11: warning: passing argument 2 of 'RSA_get0_key' from incompatible pointer type [enabled by default]
           RSA_get0_key(rsa, &n, &e, &d);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:95:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_key(const RSA *rsa, const BIGNUM **out_n,
                     ^
external/curl/lib/vtls/openssl.c:2455:11: warning: passing argument 3 of 'RSA_get0_key' from incompatible pointer type [enabled by default]
           RSA_get0_key(rsa, &n, &e, &d);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:95:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_key(const RSA *rsa, const BIGNUM **out_n,
                     ^
external/curl/lib/vtls/openssl.c:2455:11: warning: passing argument 4 of 'RSA_get0_key' from incompatible pointer type [enabled by default]
           RSA_get0_key(rsa, &n, &e, &d);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:95:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_key(const RSA *rsa, const BIGNUM **out_n,
                     ^
external/curl/lib/vtls/openssl.c:2456:11: warning: passing argument 2 of 'RSA_get0_factors' from incompatible pointer type [enabled by default]
           RSA_get0_factors(rsa, &p, &q);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:100:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_factors(const RSA *rsa, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2456:11: warning: passing argument 3 of 'RSA_get0_factors' from incompatible pointer type [enabled by default]
           RSA_get0_factors(rsa, &p, &q);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:100:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_factors(const RSA *rsa, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2457:11: warning: passing argument 2 of 'RSA_get0_crt_params' from incompatible pointer type [enabled by default]
           RSA_get0_crt_params(rsa, &dmp1, &dmq1, &iqmp);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:107:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_crt_params(const RSA *rsa, const BIGNUM **out_dmp1,
                     ^
external/curl/lib/vtls/openssl.c:2457:11: warning: passing argument 3 of 'RSA_get0_crt_params' from incompatible pointer type [enabled by default]
           RSA_get0_crt_params(rsa, &dmp1, &dmq1, &iqmp);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:107:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_crt_params(const RSA *rsa, const BIGNUM **out_dmp1,
                     ^
external/curl/lib/vtls/openssl.c:2457:11: warning: passing argument 4 of 'RSA_get0_crt_params' from incompatible pointer type [enabled by default]
           RSA_get0_crt_params(rsa, &dmp1, &dmq1, &iqmp);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:82:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/rsa.h:107:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void RSA_get0_crt_params(const RSA *rsa, const BIGNUM **out_dmp1,
                     ^
external/curl/lib/vtls/openssl.c:2500:11: warning: passing argument 2 of 'DSA_get0_pqg' from incompatible pointer type [enabled by default]
           DSA_get0_pqg(dsa, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:74:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dsa.h:101:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DSA_get0_pqg(const DSA *dsa, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2500:11: warning: passing argument 3 of 'DSA_get0_pqg' from incompatible pointer type [enabled by default]
           DSA_get0_pqg(dsa, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:74:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dsa.h:101:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DSA_get0_pqg(const DSA *dsa, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2500:11: warning: passing argument 4 of 'DSA_get0_pqg' from incompatible pointer type [enabled by default]
           DSA_get0_pqg(dsa, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:74:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dsa.h:101:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DSA_get0_pqg(const DSA *dsa, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2501:11: warning: passing argument 2 of 'DSA_get0_key' from incompatible pointer type [enabled by default]
           DSA_get0_key(dsa, &pub_key, &priv_key);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:74:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dsa.h:96:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DSA_get0_key(const DSA *dsa, const BIGNUM **out_pub_key,
                     ^
external/curl/lib/vtls/openssl.c:2501:11: warning: passing argument 3 of 'DSA_get0_key' from incompatible pointer type [enabled by default]
           DSA_get0_key(dsa, &pub_key, &priv_key);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:74:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dsa.h:96:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DSA_get0_key(const DSA *dsa, const BIGNUM **out_pub_key,
                     ^
external/curl/lib/vtls/openssl.c:2533:11: warning: passing argument 2 of 'DH_get0_pqg' from incompatible pointer type [enabled by default]
           DH_get0_pqg(dh, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:73:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dh.h:102:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DH_get0_pqg(const DH *dh, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2533:11: warning: passing argument 3 of 'DH_get0_pqg' from incompatible pointer type [enabled by default]
           DH_get0_pqg(dh, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:73:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dh.h:102:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DH_get0_pqg(const DH *dh, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2533:11: warning: passing argument 4 of 'DH_get0_pqg' from incompatible pointer type [enabled by default]
           DH_get0_pqg(dh, &p, &q, &g);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:73:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dh.h:102:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DH_get0_pqg(const DH *dh, const BIGNUM **out_p,
                     ^
external/curl/lib/vtls/openssl.c:2534:11: warning: passing argument 2 of 'DH_get0_key' from incompatible pointer type [enabled by default]
           DH_get0_key(dh, &pub_key, &priv_key);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:73:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dh.h:92:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DH_get0_key(const DH *dh, const BIGNUM **out_pub_key,
                     ^
external/curl/lib/vtls/openssl.c:2534:11: warning: passing argument 3 of 'DH_get0_key' from incompatible pointer type [enabled by default]
           DH_get0_key(dh, &pub_key, &priv_key);
           ^
In file included from external/boringssl/src/include/openssl/x509.h:73:0,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/curl/lib/urldata.h:86,
                 from external/curl/lib/vtls/openssl.c:41:
external/boringssl/src/include/openssl/dh.h:92:21: note: expected 'const struct BIGNUM **' but argument is of type 'struct BIGNUM **'
 OPENSSL_EXPORT void DH_get0_key(const DH *dh, const BIGNUM **out_pub_key,
                     ^
external/curl/lib/vtls/openssl.c: At top level:
cc1: warning: unrecognized command line option "-Wno-string-plus-int" [enabled by default]
INFO: Elapsed time: 450.149s, Critical Path: 21.18s
INFO: 1372 processes: 1372 local.
FAILED: Build did NOT complete successfully
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tensorflowbutler** [comment] 2018-08-15 13:07
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:51
Nagging Assignee @shivaniag: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:57
Nagging Assignee @shivaniag: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:57
Nagging Assignee @shivaniag: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:51
Nagging Assignee @shivaniag: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 19:08
Nagging Assignee @shivaniag: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2019-05-10 23:47
```
include/openssl/ocsp.h:567:34: error: unknown type name 'OCSP_RESPONSE'
```
This is a duplicate of this issue:
https://github.com/tensorflow/serving/issues/626

It is related to anaconda's openssl. Please see the workaround on the other issue.

**Closed by gunan** 2019-05-10 23:47 UTC
Labels: stat:awaiting tensorflower, type:build/install
