### ISSUE TITLE
CUDA broken on docker image tensorflow/tensorflow:devel-gpu

### ISSUE THREAD

**Issue by lezh** [tensorflow/tensorflow#36974] opened 2020-02-22 02:20 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker Hub
- TensorFlow version: [tensorflow/tensorflow:latest-devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/latest-devel-gpu/images/sha256-607098dc1fe31c990b2c54c37bd5c81099cad165232cb0489c35e51689de27c7?context=explore)
- Python version: python3
- Installed using virtualenv? pip? conda?: docker 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

CUDA is broken on [tensorflow/tensorflow:devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/latest-devel-gpu/images/sha256-607098dc1fe31c990b2c54c37bd5c81099cad165232cb0489c35e51689de27c7?context=explore) image. TensorFlow could not recognize the GPUs.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

### Host Server (Debian GNU/Linux 9)

On the host server, CUDA is on 10.1. Tensorflow can detect 8 GPUs.

Run `nvidia-smi` and it shows 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```

Verify that TensorFlow can see the 8 GPUs.
```
$ pip install tensorflow 
$ python -c 'import tensorflow as tf; print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices("GPU")))'

('Num GPUs Available: ', 8)
```

### Inside Container (tensorflow/tensorflow:devel-gpu)

Then, start the container.
```
$ docker run --gpus=all -it tensorflow/tensorflow:latest-devel-gpu-py3
```

In the container, run
```
root@5f3ceeb2248b:/# nvidia-smi
Sat Feb 22 02:06:17 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
```
Notice that the CUDA version was **ERR!**. It may indicate that the CUDA version is broken. 
Run 
```
$ pip install tensorflow 
$ python -c 'import tensorflow as tf; print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices("GPU")))'

2020-02-22 02:11:29.788170: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2020-02-22 02:11:29.788245: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.87.1
Num GPUs Available:  0
```

TensorFlow could not see the GPUs.

**Any other info / logs**

**Comment by angerson** [comment] 2020-02-25 00:22
Thanks for your report. I investigated this and replicated part of it. You should be able to use CUDA correctly by removing the "stubs" entry from LD_LIBRARY_PATH. See [here for details](https://github.com/Kaggle/docker-python/issues/361#issuecomment-448093930) (follow the link chain starting from "should not" to see why our dockerfiles have this. I'm not sure if this is still necessary).

However, on my machine, `nvidia-smi` still finds my graphics card, even though CUDA reports ERR. Can you try nvidia-smi with the `tensorflow/tensorflow:latest` and `nvidia/cuda:10.1-runtime-ubuntu16.04` images?

**Comment by lezh** [comment] 2020-02-25 02:11
@angerson Thanks for the investigation! 

Yes. Once I take away the `stubs` from LD_LIBRARY_PATH, the problem is gone. 
```
root@f1a39ae5bce1:/# echo $LD_LIBRARY_PATH
/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
root@f1a39ae5bce1:/# export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
root@f1a39ae5bce1:/# nvidia-smi
Tue Feb 25 02:07:07 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
```

Both nvidia-smi and TF work properly on images you mentioned:
- `tensorflow/tensorflow:latest-gpu`
- `nvidia/cuda:10.1-runtime-ubuntu16.04`

I tried to find the exact command that produces this ERR result. It turns out to be [this command](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile#L95) in the [devel-gpu.Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile). I don't understand how it works. But, if it's no longer necessary, removing it should fix our problem.

**Comment by duncanriach** [comment] 2020-03-07 05:09
I was about to open a new issue, and then GitHub figured out exactly what I was looking for and brought me to this issue. I seem to be dealing with a slightly different flavor of the same problem, with the same root cause. Here is my issue description:

**Title**: TensorFlow will not run on GPU in devel-gpu container (because of CUDA stubs)

**Reproduction Instructions**

```
$ docker run -it -w /tensorflow_src tensorflow/tensorflow:devel-gpu
# bazel test --config=cuda -c opt --test_output=all --verbose_failures -- //tensorflow/python/kernel_tests:bias_op_deterministic_test
```

**Other Information**

The source of the problem is that `LD_LIBRARY_PATH` includes `/usr/local/cuda/lib64/stubs`:

```
# echo $LD_LIBRARY_PATH
/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

Removing this resolves the problem:

```
# LD_LIBRARY_PATH="${LD_LIBRARY_PATH//\/usr\/local\/cuda\/lib64\/stubs:}"
# echo $LD_LIBRARY_PATH
/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
# bazel test --config=cuda -c opt --test_output=all --verbose_failures -- //tensorflow/python/kernel_tests:bias_op_deterministic_test
```

I understand that `/usr/local/cuda/lib64/stubs` is used to enable the TensorFlow wheel to be built in the absence of a real CUDA driver, and I assume that the `devel-gpu` container is used for this purpose. However, this makes it harder and more confusing to use the `devel-gpu` container for development.

Apparently, there are preferable ways to allow the build to successfully complete in the absence of a real CUDA driver, and these ways do not require the presence of `/usr/local/cuda/lib64/stubs` in `LD_LIBRARY_PATH`. Four different approaches are discussed [here](https://github.com/NVIDIA/nvidia-docker/issues/775#issuecomment-400178344).

My intentions in filing this issue are,
1. to provide thorough documentation to help other struggling with it,
2. to organize a discussion about how to resolve this (apparently recurring) issue, and
3. to drive resolution.

**Comment by nouiz** [comment] 2020-11-10 15:00
I hit that problem today. I made a PR that move the stub to the end. This fix this problem: https://github.com/tensorflow/tensorflow/pull/44732

**Comment by tensorflowbutler** [comment] 2021-09-22 17:14
This has been fixed in this PR https://github.com/tensorflow/tensorflow/pull/46190/files , so closing this issue. Thank you

**Comment by rthadur** [comment] 2021-09-22 17:15
This has been fixed here https://github.com/tensorflow/tensorflow/pull/46190 , will be closing this request. Thank you

**Closed by rthadur** 2021-09-22 17:15 UTC
Labels: type:build/install, subtype: ubuntu/linux, TF 2.1
