### ISSUE TITLE
reduce_max on empty int32 array returns -2147483648

### ISSUE THREAD

**Issue by kelvinguu** [tensorflow/tensorflow#31325] opened 2019-08-04 21:13 UTC
**System information**
- Have I written custom code: **no**
- OS Platform and Distribution: **Linux**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: **1.14.0**
- Python version: **2.7**

**Describe the current behavior**
```python
# Call reduce_max on an empty Tensor.
x = tf.reduce_max(tf.zeros([0], tf.int32))
with tf.Session() as sess:
  print x.eval()
# prints -2147483648
```
**Describe the expected behavior**
Would be better if `reduce_max` threw an error when fed an empty Tensor.

**Comment by ravikyram** [comment] 2019-08-05 08:26
I have tried on colab with TF version 1.14 and nightly versions was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1695UiZG2M9q8oKvEN0WGdwLjY1NXy6wm) here.Thanks!

**Comment by Leslie-Fang** [comment] 2019-08-26 13:49
The test run into this snippet of code
https://github.com/tensorflow/tensorflow/blob/0b180e77223a1819758945a9d09c6960c553a1f3/tensorflow/core/kernels/reduction_ops_common.h#L189-L194

**Comment by Leslie-Fang** [comment] 2019-08-28 22:43
@jvishnuvardhan
I believe we can close this issue now. Since the behavior is as expected.

**Comment by jvishnuvardhan** [comment] 2019-08-28 23:20
I am closing this issue as it is intended behavior. Thanks!

**Closed by jvishnuvardhan** 2019-08-28 23:20 UTC
Labels: TF 1.14, comp:ops, stat:awaiting tensorflower, type:bug
