### ISSUE TITLE
PIP installation error due to libcuda.so.1 not found

### ISSUE THREAD

**Issue by peterzcc** [tensorflow/tensorflow#3674] opened 2016-08-06 01:15 UTC
I encountered a strange error after installing tensorflow through pip: the tensorflow says it cannot find libcuda.so.1, which should not exist. Does anyone know how to fix it? Thanks for help!
### Environment info

Operating System:
CentOS 6
Installed version of CUDA and cuDNN: 
Cuda 7.5 and cudnnv4

If installed from binary pip package, provide:
1. Which pip package you installed.
   https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp34-cp34m-linux_x86_64.whl
### Logs or other output that would be helpful

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/GNU/gcc-4.9.2/lib64:/usr/local/cuda-7.5/lib64:/csproject/dygroup2/czeng/venv/lib:/usr/lib64/:/csproject/dygroup2/czeng/venv/cudnnv4/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: client108
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.93  Tue Apr  5 18:18:24 PDT 2016
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.93.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1077] LD_LIBRARY_PATH: /usr/local/GNU/gcc-4.9.2/lib64:/usr/local/cuda-7.5/lib64:/csproject/dygroup2/czeng/venv/lib:/usr/lib64/:/csproject/dygroup2/czeng/venv/cudnnv4/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1078] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot enable executable stack as shared object requires: Operation not permitted
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: client108
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: client108
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.93  Tue Apr  5 18:18:24 PDT 2016
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 352.93.0

**Comment by girving** [comment] 2016-08-08 17:09
When you say `libcuda.so.1` should not exist, does it exist?  Usually this kind of error is caused by a bad path or bad cuda installation.

**Comment by girving** [comment] 2016-08-08 17:14
Also: CentOS isn't a fully supported platform, which may mean that our pip wheels don't work with it.

**Comment by aselle** [comment] 2016-08-17 16:46
Marking as community support since CentOS is not officially supported. There are definitely people monitoring the issues list who are experienced with CentOS that can better help you. Good luck!

**Comment by gunan** [comment] 2016-12-21 09:09
Is this still a problem?

When you install CUDA, libcuda.so.1 should exist in your system.
what do you see when you run 
```
sudo find / -name libcuda.so.1
```

**Comment by gunan** [comment] 2017-01-04 06:07
Closing issue due to inactivity.

**Closed by gunan** 2017-01-04 06:07 UTC
Labels: community support
