### ISSUE TITLE
Fails when atrous rate is higher than ~280.

### ISSUE THREAD

**Issue by israelg99** [tensorflow/tensorflow#7914] opened 2017-02-27 08:43 UTC
When `tf.nn.atrous_conv2d` is called with a rate higher than ~280, tensorflow fails with the following message: `F tensorflow/stream_executor/cuda/cuda_dnn.cc:2742] failed to enqueue convolution on stream: CUDNN_STATUS_NOT_SUPPORTED`  
Further invistigation leads to when [tensorflow calls cudnn convolution backward filters operation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_dnn.cc#L2681).

Tested with multiple machines with TITAN X's and all pip packages and CUDA/CUDNN upgraded to latest.

**Comment by tatatodd** [comment] 2017-03-01 01:49
@israelg99 can you provide the full log before the failure?

Perhaps the root problem is we're running out of memory, as in #5688 ?

**Comment by israelg99** [comment] 2017-03-02 15:38
My logs are identical to #5688 and I don't think it is running out of memory, I tried running it on many configurations, it fails even on a small network with batch size 1.

The same error occurs both when I run it on TF or Keras with TF backend.

 It should be easily reproducible by running a simple graph with `tf.nn.atrous.conv2d` with a rate higher than ~280.

**Comment by yaroslavvb** [comment] 2017-03-06 19:55
@israelg99 it might be useful to give a self-contained example someone could just copy-paste to reproduce your problem

**Comment by asimshankar** [comment] 2017-04-04 07:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-04 07:59 UTC
Labels: stat:awaiting response
