### ISSUE TITLE
tensorflow howto for sharing variable is confusing

### ISSUE THREAD

**Issue by evanthebouncy** [tensorflow/tensorflow#213] opened 2015-11-14 00:56 UTC
at here:
http://tensorflow.org/how_tos/variable_scope/index.md

The tutorial talk about using "two sets of variables" and talk about their duplication, however the network itself uses 2 layers of convolution. So there's 2 different things that can be the quantity of 2. 
1) The number of layers is 2, being conv1 and conv2, these 2 should be distinct
2) The number of image filters, applied once to each image, these 2 should be identical

I was having a hard time understanding at first and thought we're attempting to use the same weights for both of the conv layers. It didn't help that the definition for "variables_dict" only explicitly states the existence for the weights for the first conv layer, leading me to believe that the weights of the 2 layers are actually shared as well.

I think a simple fix is to make the network have say 5 conv layers instead of 2, this way you get to demonstrate variable_scope as well in the later section

Just my 2 cents, I starred at this for much longer than I should have because of this confusion.

**Comment by vrv** [comment] 2015-11-14 17:33
Thanks, we'll take a look to see if we can reduce the confusion!

**Comment by girving** [comment] 2016-06-06 17:25
@vrv: Did this ever happen?

**Comment by vrv** [comment] 2016-06-06 17:47
I doubt it -- assigning to Lukasz

**Comment by lukaszkaiser** [comment] 2016-06-16 22:48
Improved the tutorial to clarify which sets of variables are meant in a recent CL, is now live on master.

**Closed by lukaszkaiser** 2016-06-16 22:48 UTC
Labels: docs, triaged

**Comment by amirmazaheri1990** [comment] 2017-05-31 23:07
Hi,

My question may be a little bit different than what is already asked.
If I define a class like below:

```

class Dense:
    def __init__(self,Dsize,OSize):
        self.variables_dict = {
            "FirstLayer": tf.Variable(tf.random_normal(Dsize),  name="weights"),
            "FirstLayer_b": tf.Variable(tf.zeros(OSize), name="biases")
        }
    def apply(self, input, equation = 'ijk,kd->ijd'):
        output = tf.einsum(equation, input, self.variables_dict['FirstLayer']) + self.variables_dict['FirstLayer_b']
        return output
```


And get **one** instance of this class in my code and use it multiple times by using its `apply` function. Does it mean that I have shared the same weight matrix (they have equal values in them) in different parts of my graph? Or it will make different matrices and update the variables differently?

I am not using the `reuse = True` option.

I would appreciate if someone helps me with this issue. It will help me a lot to understand the logic behind generating a graph in Tensorflow and also writing a clean and readable code.

**Comment by lukaszkaiser** [comment] 2017-05-31 23:16
Please use tf.get_variable. Reuse will *not* work with tf.Variable and you should basically *never* use it, always go for tf.get_variable instead.

**Comment by amirmazaheri1990** [comment] 2017-05-31 23:25
@lukaszkaiser  Thanks a lot for your prompt response and the good tip.

Actually, my main concern is about using object oriented style programming in TF. 

If I implement a costume layer as a class (Dense layer in my toy example above), can I do weight sharing by just getting one instance of that class and use it multiple times? Or the TF engine will internally make different ones and update them completely different and that layer won't have same weights with other ones?

Thanks

**Comment by lukaszkaiser** [comment] 2017-05-31 23:52
It is a little tricky to do the OO-style right, but we're working to provide a convenient way to do it as follows.

First of all, let your class be a sub-class of Layer from tensorflow/python/layers/base.py: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/base.py

This will handle everything related to scopes. It will open new scope if you provide a name for your layer, it will reuse if you're referring to the same object, but create new variables when you create a new object. If you subclass from Layer, the only thing you need to implement are the "build" and "call" functions, similar to Keras. You can see how we do it for the core Dense layer here:
  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/core.py#L106

I think the easiest way to do OO is to do the same, you can even use our OO layers already. They are not part of the public API yet because we want to test them properly and let them mature, but I think they're far enough to give them a try. If you want to have a look, the expected behaviors in terms of interaction with reuse have their unit tests here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/core_test.py

Hope that helps, we want to make a great OO interface too, so let us know if you try the core OO stuff and have troubles.
