### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by lxz1104** [tensorflow/tensorflow#34547] opened 2019-11-23 13:46 UTC
**System information**
- OS Platform and Distribution :Linux Ubuntu 18.0.4
- TensorFlow installed from (source or binary): anaconda3
- TensorFlow version (use command below):2.0.0
- Python version:3.6.9
- CUDA/cuDNN version:10.1
- GPU model and memory:GTX2070 8GB

**Code to reproduce the issue**
``` python
from net.baseline import Baseline
from tensorflow import keras
import tensorflow as tf
from data.dataset import MSRA

train_data = tf.data.Dataset.from_tensor_slices((images, labels))
train_data = train_data.apply(tf.data.experimental.shuffle_and_repeat(buffer_size=len(images)))
train_data = train_data.map(dataset.load_and_preprocess_data)
train_data = train_data.batch(BATCH_SIZE)
```

**info / logs**
```
Traceback (most recent call last):
  File "/home/lxz/PycharmProjects/PoseREN_tf2/src/train_baseline.py", line 26, in <module>
    train_data = tf.data.Dataset.from_tensor_slices((images, labels))
AttributeError: module 'tensorflow' has no attribute 'data'
```

**Comment by oanush** [comment] 2019-11-25 05:49
@lxz1104 ,
Hi, in the given code `from data.dataset import MSRA` its not a tensorflow dataset import. Can you please check the line. Rest of the code when tried executing worked fine without any issues.
`from tensorflow import data `can be used.
Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/dd1b6136a323001d662a593f0cdb5783/untitled269.ipynb) of colab.
For more information on the syntax of tf.data, kindly refer the [link](https://github.com/tensorflow/tensorflow/issues/33654#issuecomment-546414347).

**Comment by lxz1104** [comment] 2019-11-26 12:13
I have fixed this problem by change `import` to this:
``` python
import tensorflow as tf
from net.baseline import Baseline
from tensorflow import keras
from data.dataset import MSRA
from tensorflow_core.python.keras.callbacks import EarlyStopping
```

**Comment by oanush** [comment] 2019-11-27 03:39
Closing since the issue is resolved,Thanks!

**Closed by oanush** 2019-11-27 03:39 UTC
Labels: TF 2.0, comp:data, type:support
