### ISSUE TITLE
tensorflow keras SavedModel for LSTM fails

### ISSUE THREAD

**Issue by grewe** [tensorflow/tensorflow#34028] opened 2019-11-06 03:04 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):  2.0
- Python version: 3.6.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Attempting to save LSTM based tf.keras model to a SavedModel it fails with error:

`ValueError: Attempted to save a function b'__inference_lstm_layer_call_fn_5041' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(None, 2048), dtype=float32) that is not a simple constant. This is not supported.`
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

`BASE_DATA_PATH = 'C:\Grewe\Classes\CS663\Mat\LSTM\data' `
`model_file = os.path.join(BASE_DATA_PATH, 'my_model.h5')`
`model = tf.keras.models.load_model(model_file)`
`model.summary()`

`print('\n# Generate predictions ')`
`predictions = model.predict(valid_dataset, verbose=1 )`
`print('predictions shape:', predictions.shape)`
`print(predictions)`
`print(len(predictions))`

`saved_model_dir = os.path.join(BASE_DATA_PATH, 'saved_model\catsdogsCNN')`
`!mkdir -#p saved_model_dir`
`model.save(saved_model_dir) `

[pythonLSTMCode.txt](https://github.com/tensorflow/tensorflow/files/3812314/pythonLSTMCode.txt)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

See attached python file that contains the original training code for the sequential LSTM model defined as:
`model = tf.keras.Sequential([
    tf.keras.layers.Masking(mask_value=0.),
    tf.keras.layers.LSTM(512, dropout=0.5, recurrent_dropout=0.5),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(LABELS), activation='softmax')
])`

**Comment by ravikyram** [comment] 2019-11-07 08:03
@grewe 

Can you please share all the supporting files (`UCF-101, .txt files`) for reproducing the issue. Thanks!

**Comment by grewe** [comment] 2019-11-07 16:02
The data is a UCF101 data set.  I have added a zip below AND it contains results from running the part of the code that performs CNN feature extraction on the video data that can take hours to do on a normal laptop.  So each .avi file has a corresponding .npy file containing the CNN feature extraction output.  So, I would block out the part of the code that contains the feature extraction....if you unzip and change the names of the directory paths it should work.

If you want I have also provided a link to my trained model saved in h5 that you could simply run the portion of the code that loads the model runs prediction to get input layer setup and then try to save.
SEE attached for a reduced version of the code attached in previous comment --that only loads my stored h5 file, does a few predictions then tries to save to a SavedModel directory format and fails with error reported.   If you use this then it will run quickly 

IMPORTANT:  following the suggestion of the error, after loading my h5 file I do some predictions and get a different error when attempt SavedModel.   I do not understand why h5 format does not save the input shape information and I have to do predictions to reset when reloading model ---however if using original code that trains model and does SavedModel attempt the error is exactly the same.

[LSTM_SimpleCodeVersion.py.txt](https://github.com/tensorflow/tensorflow/files/3820468/LSTM_SimpleCodeVersion.py.txt)


Training data - BOTH videos and .npy files with feature vectors from each video to feed into [LSTM](url)
[http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/UCF-101_WithTraininData_InceptionV3CNN_trainedOnImageNet_Sampled_40_per_video.zip](url)

Model file
[http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/Good17EpochModel/my_model.h5](url)

**Comment by grewe** [comment] 2019-11-08 20:39
Here are the URLs again for the 2 resources

MODEL
[](url)http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/Good17EpochModel/my_model.h5

Training data - BOTH videos and .npy files with feature vectors from each video to feed into
[](url) http://borg.csueastbay.edu/~grewe/CS663/Mat/LSTM/data/UCF-101_WithTraininData_InceptionV3CNN_trainedOnImageNet_Sampled_40_per_video.zip

**Comment by grewe** [comment] 2019-11-10 21:14
Any ideas on this issue?

**Comment by ravikyram** [comment] 2019-11-11 11:29
@grewe, I am unable to open the zip file that you have shared. Please help us to replicate the issue with more information. Thanks!

**Comment by ravikyram** [comment] 2019-11-19 11:43
@grewe 
Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2019-11-29 10:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-11-29 10:01 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by NLP-ZY** [comment] 2020-01-02 06:04
same error. I use parameter dropout & recurrent_dropout in GRU Layer, when I complete my train, use tf.saved_model.save(model, "path/save/model/1"), raise an error "ValueError: Attempted to save a function b'__inference_gru_layer_call_fn_60270' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(None, 200), dtype=float32) that is not a simple constant. This is not supported."

**Comment by NLP-ZY** [comment] 2020-01-02 06:07
### Network
```
class SiameseRNN(tfk.Model):
    def __init__(self, embeddings):
        super(SiameseRNN, self).__init__()
        self.embedding_layer = tfk.layers.Embedding(embeddings.shape[0], embeddings.shape[1], trainable=False,
                                                    embeddings_initializer=tf.initializers.Constant(embeddings))
        self.gru_layer = tfk.layers.GRU(FLAGS.gru_units, dropout=FLAGS.rnn_dropout,
                                        recurrent_dropout=FLAGS.rnn_recurrent_dropout)
        self.batchnorm_layer1 = tfk.layers.BatchNormalization()
        self.dropout_layer = tfk.layers.Dropout(FLAGS.dropout_rate)
        self.dense_layer1 = tfk.layers.Dense(FLAGS.dense_units, activation=FLAGS.dense1_activation)
        self.batchnorm_layer2 = tfk.layers.BatchNormalization()
        self.dense_layer2 = tfk.layers.Dense(1, FLAGS.dense2_activation)

    def call(self, inputs, training=False):
        x1 = inputs[0]
        x2 = inputs[1]
        x1_mask = inputs[2]
        x2_mask = inputs[3]
        x1_embed = self.embedding_layer(x1)
        x2_embed = self.embedding_layer(x2)
        x1_encoding = self.gru_layer(x1_embed, mask=x1_mask, training=training)
        x2_encoding = self.gru_layer(x2_embed, mask=x2_mask, training=training)
        x1_x2_encoding_concat = tf.concat([x1_encoding, x2_encoding], axis=-1)
        x1_x2_encoding_concat = self.batchnorm_layer1(x1_x2_encoding_concat, training=training)
        x1_x2_encoding_concat = self.dropout_layer(x1_x2_encoding_concat, training=training)
        hidden = self.dense_layer1(x1_x2_encoding_concat)
        hidden = self.batchnorm_layer2(hidden, training=training)
        y_pred = self.dense_layer2(hidden)
        return y_pred
```
### Train & save
```
model.compile(optimizer=optimizer, loss=tf.losses.binary_crossentropy, metrics=["acc"])
        model.fit(x=[x1, x2, x1_mask, x2_mask], y=y, batch_size=FLAGS.batch_size, epochs=FLAGS.epochs,
                  validation_data=([val_x1, val_x2, val_x1_mask, val_x2_mask], val_y))
        model.summary()
        tf.saved_model.save(model, FLAGS.save_path)
```
### Error
```
ValueError: Attempted to save a function b'__inference_gru_layer_call_fn_60270' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(None, 200), dtype=float32) that is not a simple constant. This is not supported.
```
If don't use parameter dropout & recurrent_dropout, tf.saved_mode.save can save the model successfully

**Comment by pourmatin** [comment] 2020-05-14 23:28
I get the same error with /opt/anaconda3/bin/python. but it works fine with my /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

**Comment by prabhatkgupta** [comment] 2024-01-03 19:35
I am still getting this issue, Tensorflow team please resolve this

ValueError: Attempted to save a function b'__inference_forward_gru_layer_call_fn_42239' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(?, 256), dtype=float32) that is not a simple constant. This is not supported.

cc: @ravikyram @grewe
