### ISSUE TITLE
GPU text classification notebook produces CUDNN error

### ISSUE THREAD

**Issue by radiantone** [tensorflow/tensorflow#29034] opened 2019-05-26 01:26 UTC
**Error Message**
UnknownError: Fail to find the dnn implementation.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pop!_OS 19.04
- TensorFlow installed from (source or binary): jupyter
- TensorFlow version (use command below): !pip install tensorflow-gpu
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0, cudnn 7.4.5.1
- GPU model and memory: See below RTX 2070 Max-q

[I 21:20:12.056 LabApp] Saving file at /Downloads/text_classification_rnn.ipynb
[W 21:20:12.057 LabApp] Notebook Downloads/text_classification_rnn.ipynb is not trusted
[I 21:21:07.912 LabApp] Kernel interrupted: fe30308a-41da-4a83-8fa9-93bf6c87fb6c
[I 21:22:12.102 LabApp] Saving file at /Downloads/text_classification_rnn.ipynb
[W 21:22:12.103 LabApp] Notebook Downloads/text_classification_rnn.ipynb is not trusted
2019-05-25 21:22:15.359388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-05-25 21:22:15.359425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-25 21:22:15.359432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-05-25 21:22:15.359436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-05-25 21:22:15.359592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/device:GPU:0 with 6704 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-05-25 21:22:19.514494: W ./tensorflow/core/framework/model.h:202] Encountered a stop event that was not preceded by a start event.
2019-05-25 21:22:20.872486: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-05-25 21:22:20.872526: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at cudnn_rnn_ops.cc:1280 : Unknown: Fail to find the dnn implementation.
2019-05-25 21:22:20.872567: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Unknown: Fail to find the dnn implementation.
	 [[{{node bidirectional_2/CudnnRNN}}]]
	 [[loss_2/dense_5_loss/binary_crossentropy/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_47/has_invalid_dims_0/_52]]
2019-05-25 21:22:20.872626: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Unknown: Fail to find the dnn implementation.
	 [[{{node bidirectional_2/CudnnRNN}}]]
2019-05-25 21:22:20.872655: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Unknown: Fail to find the dnn implementation.
	 [[{{node bidirectional_2/CudnnRNN}}]]
	 [[loss_2/dense_5_loss/binary_crossentropy/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_47/has_invalid_dims_0/_52]]
2019-05-25 21:22:20.875125: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-05-25 21:22:20.875145: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at cudnn_rnn_ops.cc:1280 : Unknown: Fail to find the dnn implementation.
2019-05-25 21:22:20.875197: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Unknown: Fail to find the dnn implementation.
	 [[{{node bidirectional_2/CudnnRNN}}]]

**Comment by radiantone** [comment] 2019-05-26 01:43
I think the issue here *might be* that my card is on compute cudnn version 7.5 yet cuda toolkit 10.0 does for my OS does not pull cudnn 7.5. If I install cuda toolkit 10.1, then tensorflow looks for 10.0 shared libraries only.

**Comment by radiantone** [comment] 2019-05-26 01:51
I also tried with
!pip install tensorflow-gpu==2.0.0-alpha0

same error.

UnknownError: Fail to find the dnn implementation.
	 [[{{node bidirectional/CudnnRNN}}]]
	 [[loss/dense_1_loss/binary_crossentropy/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_47/has_invalid_dims/concat/_48]] [Op:__inference_keras_scratch_graph_2449]

**Comment by achandraa** [comment] 2019-05-28 07:49
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by radiantone** [comment] 2019-05-28 13:17
It comes from this notebook from tensorflow team
https://www.tensorflow.org/alpha/tutorials/text/text_classification_rnn

And the segment throwing the exception is the "Train the Model" cell.

history = model.fit(train_dataset, epochs=10,
                    validation_data=test_dataset)

**Comment by radiantone** [comment] 2019-05-28 13:26
This is likely a duplicate of this issue https://github.com/tensorflow/tensorflow/issues/24496

**Comment by achandraa** [comment] 2019-05-29 06:01
Please have a look on the issue mentioned by you and let us know if that helps. Looks like this [comment](https://github.com/tensorflow/tensorflow/issues/24496#issuecomment-464909727) might give you a fix. Thanks!

**Comment by radiantone** [comment] 2019-05-29 12:37
Hi,
  Thank you for responding. I don't think that solution will work here as the example notebook is using Keras and the solution in the other ticket is not. Is there a way to enable that solution when using tensorflow through keras? If so, that might work.

**Comment by chsigg** [comment] 2019-06-03 11:42
It might well be related to the memory allocation: TF grabs all the GPU memory and cuDNN can't initialize because there is nothing left. You could try to reduce the preallocated TF memory (I have to admit I don't know how to do that through Keras).

You are suspecting that you need to update cuDNN and CUDA because it doesn't support your model yet. Older CUDA software is generally compatible with newer hardware (because the driver API is the same).

The best shot at debugging this is running with cuDNN logging on: https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#api-logging

**Comment by jvishnuvardhan** [comment] 2019-10-01 20:14
@radiantone Is this still an issue? If not, please close the issue.
If it is still an issue, 
1) can you try recently release TF2.0 and check whether the issue is resolved or not?
2) Can you try to run small TF model and see whether you have the same issue?
3) I noticed that you are using Anaconda. Is there any limit set on GPU memory?

Please let us know what you think? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-09 15:39
@radiantone Can you please provide the info I requested in the last response? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-16 18:11
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-10-16 18:11 UTC
Labels: TF 2.0, comp:gpu, stat:awaiting response, type:support

**Comment by wuzhixin1010** [comment] 2019-11-23 09:12
@radiantone  did you finally solve the problem?
I get the same problem right now.
Also in my how hardware2070s.And problem occour in the text classification example of tensorflow.
[https://www.tensorflow.org/alpha/tutorials/text/text_classification_rnn](url)

`CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Reshape_11/_38}}]] [Op:__inference_distributed_function_6315]

Function call stack:
distributed_function`

` W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]`

if the problem has solved,please give me some solutions.
Thank you!
