### ISSUE TITLE
Cannot confine TensorFlow C API to use not more than 1 threads in total

### ISSUE THREAD

**Issue by fisakhan** [tensorflow/tensorflow#42510] opened 2020-08-20 11:15 UTC
<em>TensorFlow C API is generating at least one thread on each of the available CPUs. The available instructions/guidlines do not take effect to confine TensorFlow C API to only one CPU. I have 8 CPUs and want TensorFlow C API to use only 1, thus generating one and only one thread. How can I confine TensorFlow to use only one CPU (and only one thread) out of available CPUs?</em>
Processor (lscpu command on Ubuntu):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 142
Model name:            Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Stepping:              10
CPU MHz:               1122.143
CPU max MHz:           3400.0000
CPU min MHz:           400.0000
BogoMIPS:              3600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
The following code can reduce the number of threads to 1 per core and the top command cou

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.6.1810
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): https://www.tensorflow.org/install/lang_c
- TensorFlow version (use command below): TensorFlow C API 1.15.0
- Python version:3.6
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
- CUDA/cuDNN version:NO
- GPU model and memory:No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TensorFlow C API is generating multiple threads, at least one thread on each of the available CPUs. 

**Describe the expected behavior**
One and only one thread for tensorflow, no matter how many cpus, cores or sockets.

**Standalone code to reproduce the issue**
Graph = TF_NewGraph();
Status = TF_NewStatus();
SessionOpts = TF_NewSessionOptions();  
  
  // limit number of threads  
  uint8_t intra_op_parallelism_threads = 1;
  uint8_t inter_op_parallelism_threads = 1;
  uint8_t device_count = 1;  
  uint8_t config[15] = {0xa, 0x7, 0xa, 0x3, 0x43, 0x50, 0x55, 0x10, device_count, 0x10, intra_op_parallelism_threads, 0x28, intra_op_parallelism_threads,0x40, 0x1};
  TF_SetConfig(SessionOpts, (void*)config, 13, Status);

  if (TF_GetCode(Status)!= TF_OK)
    std::cout << "\nERROR: " << TF_Message(Status);
  RunOpts = NULL;

  // load model
  Session = TF_LoadSessionFromSavedModel(SessionOpts, RunOpts, saved_model_dir, &tags, ntags, Graph, NULL, Status);
  if( TF_GetCode(Status) != TF_OK ) {
    std::cout << "\nERROR: Failed to load SavedModel." << TF_Message(Status);
    return -1;  }
  assert( TF_GetCode(Status) == TF_OK);

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by annarev** [comment] 2020-08-27 01:36
@penpornk do you know if there is away to use just one thread? Feel free to reassign if you are not the right owner for this issue.

**Comment by fisakhan** [comment] 2020-09-09 17:52
As soon as I create a graph or load a .pb model, thread count reaches the number of cores.

The following is my code to load a savedmodel (.pb) and it increases the number of threads from 1 to 8 (using "top -H -b -n1 | grep example | wc -l" command on linux).

Status LoadGraph(string graph_file_name, std::unique_ptr<tensorflow::Session>* session) {
  tensorflow::GraphDef graph_def;
  Status load_graph_status =
      ReadBinaryProto(tensorflow::Env::Default(), graph_file_name, &graph_def);
  if (!load_graph_status.ok()) {
    return tensorflow::errors::NotFound("Failed to load compute graph at '",
                                        graph_file_name, "'");
  }
  
  // initialize the number of worker threads
    tensorflow::SessionOptions options;
    tensorflow::ConfigProto & config = options.config;
    config.set_inter_op_parallelism_threads(1);
    config.set_intra_op_parallelism_threads(1);
    config.set_use_per_session_threads(false); 

  session->reset(tensorflow::NewSession(options));
  Status session_create_status = (*session)->Create(graph_def);
  if (!session_create_status.ok()) {
    return session_create_status;
  }

  //std::cout << "RunOption...\n";
  //RunOptions run_options;
  //run_options.mutable_experimental()->set_use_run_handler_pool(true);
  //RunMetadata run_metadata;
  //Status status = session->Run(run_options, input, output_node_names, {}, &output, &run_metadata);

  return Status::OK();
}

**Comment by Zantares** [comment] 2020-09-10 05:31
Hi @fisakhan , below is my CC case which met similar issue before, I used the flag `set_use_run_handler_pool` to solve this issue as I mentioned:
```c++
bool Predict(Session* session, vector<int>& in, vector<vector<float>>& out) {
    ...
    // run
    RunOptions run_options;
    run_options.mutable_experimental()->set_use_run_handler_pool(true);
    RunMetadata run_metadata;
    Status status = session->Run(run_options, input, output_node_names, {}, &output, &run_metadata);
    if (!status.ok()) {
        cout << "[Predict] failed! " << status.ToString() << endl;
        return false;
    }
    const Tensor& output_tensor = output[0];
    auto out_map = output_tensor.tensor<float, 3>();
    col = 20;
    int row = output_tensor.NumElements()/ col;

    for(size_t i=0; i<row; i++){
        vector<float> row_out;
        for(size_t k=0; k<col; k++)
            row_out.push_back(out_map(0, i, k));
        out.push_back(row_out);
    }
    return true;
}
```
Because you can't use it in C case, I think you may change this condition(https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/core/common_runtime/direct_session.cc#L600-L601) to `true`  and source build TF to see whether it works

**Comment by fisakhan** [comment] 2020-09-11 18:43
@Zantares I implemented your suggestion/recommendation in the following example (from tensorflow) using tensorflow C++ Api  and it is not working. You can just copy-paste-execute the following code without errors and will notice that it is generating multiple threads.
```
#include <fstream>
#include <utility>
#include <vector>
#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/image_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/str_util.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"

using tensorflow::Flag;
using tensorflow::int32;
using tensorflow::Status;
using tensorflow::string;
using tensorflow::Tensor;
using tensorflow::tstring;

Status ReadLabelsFile(const string& file_name, std::vector<string>* result,
                      size_t* found_label_count) {
  std::ifstream file(file_name);
  if (!file) {
    return tensorflow::errors::NotFound("Labels file ", file_name,
                                        " not found.");
  }
  result->clear();
  string line;
  while (std::getline(file, line)) {
    result->push_back(line);
  }
  *found_label_count = result->size();
  const int padding = 16;
  while (result->size() % padding) {
    result->emplace_back();
  }
  return Status::OK();
}

static Status ReadEntireFile(tensorflow::Env* env, const string& filename,
                             Tensor* output) {
  tensorflow::uint64 file_size = 0;
  TF_RETURN_IF_ERROR(env->GetFileSize(filename, &file_size));

  string contents;
  contents.resize(file_size);

  std::unique_ptr<tensorflow::RandomAccessFile> file;
  TF_RETURN_IF_ERROR(env->NewRandomAccessFile(filename, &file));

  tensorflow::StringPiece data;
  TF_RETURN_IF_ERROR(file->Read(0, file_size, &data, &(contents)[0]));
  if (data.size() != file_size) {
    return tensorflow::errors::DataLoss("Truncated read of '", filename,
                                        "' expected ", file_size, " got ",
                                        data.size());
  }
  output->scalar<tstring>()() = tstring(data);
  return Status::OK();
}

Status ReadTensorFromImageFile(const string& file_name, const int input_height,
                               const int input_width, const float input_mean,
                               const float input_std,
                               std::vector<Tensor>* out_tensors) {
  auto root = tensorflow::Scope::NewRootScope();
  using namespace ::tensorflow::ops;  // NOLINT(build/namespaces)

  string input_name = "file_reader";
  string output_name = "normalized";

  // read file_name into a tensor named input
  Tensor input(tensorflow::DT_STRING, tensorflow::TensorShape());
  TF_RETURN_IF_ERROR(
      ReadEntireFile(tensorflow::Env::Default(), file_name, &input));

  // use a placeholder to read input data
  auto file_reader =
      Placeholder(root.WithOpName("input"), tensorflow::DataType::DT_STRING);

  std::vector<std::pair<string, tensorflow::Tensor>> inputs = {
      {"input", input},
  };

  // Now try to figure out what kind of file it is and decode it.
  const int wanted_channels = 3;
  tensorflow::Output image_reader;
  if (tensorflow::str_util::EndsWith(file_name, ".png")) {
    image_reader = DecodePng(root.WithOpName("png_reader"), file_reader,
                             DecodePng::Channels(wanted_channels));
  } else if (tensorflow::str_util::EndsWith(file_name, ".gif")) {
    // gif decoder returns 4-D tensor, remove the first dim
    image_reader =
        Squeeze(root.WithOpName("squeeze_first_dim"),
                DecodeGif(root.WithOpName("gif_reader"), file_reader));
  } else if (tensorflow::str_util::EndsWith(file_name, ".bmp")) {
    image_reader = DecodeBmp(root.WithOpName("bmp_reader"), file_reader);
  } else {
    // Assume if it's neither a PNG nor a GIF then it must be a JPEG.
    image_reader = DecodeJpeg(root.WithOpName("jpeg_reader"), file_reader,
                              DecodeJpeg::Channels(wanted_channels));
  }
  // Now cast the image data to float so we can do normal math on it.
  auto float_caster =
      Cast(root.WithOpName("float_caster"), image_reader, tensorflow::DT_FLOAT);
  auto dims_expander = ExpandDims(root, float_caster, 0);
  // Bilinearly resize the image to fit the required dimensions.
  auto resized = ResizeBilinear(
      root, dims_expander,
      Const(root.WithOpName("size"), {input_height, input_width}));
  // Subtract the mean and divide by the scale.
  Div(root.WithOpName(output_name), Sub(root, resized, {input_mean}),
      {input_std});

  tensorflow::GraphDef graph;
  TF_RETURN_IF_ERROR(root.ToGraphDef(&graph));

  std::unique_ptr<tensorflow::Session> session(
      tensorflow::NewSession(tensorflow::SessionOptions()));
  TF_RETURN_IF_ERROR(session->Create(graph));
  TF_RETURN_IF_ERROR(session->Run({inputs}, {output_name}, {}, out_tensors));
  return Status::OK();
}

Status LoadGraph(const string& graph_file_name,
                 std::unique_ptr<tensorflow::Session>* session) {
  std::cout << "Thread count: " << system("top -H -b -n1 | grep example | wc -l") << "\n";

  tensorflow::GraphDef graph_def;
  Status load_graph_status =
      ReadBinaryProto(tensorflow::Env::Default(), graph_file_name, &graph_def);
  if (!load_graph_status.ok()) {
    return tensorflow::errors::NotFound("Failed to load compute graph at '",
                                        graph_file_name, "'");
  }
  
  **std::cout << "Thread count: " << system("top -H -b -n1 | grep example | wc -l") << "\n";**
  **// initialize the number of worker threads
  tensorflow::SessionOptions options;
  tensorflow::ConfigProto & config = options.config;
  config.set_inter_op_parallelism_threads(1);
  config.set_intra_op_parallelism_threads(1);**

  session->reset(tensorflow::NewSession(options));
  Status session_create_status = (*session)->Create(graph_def);
  if (!session_create_status.ok()) {
    return session_create_status;
  }
  **std::cout << "Thread count: " << system("top -H -b -n1 | grep example | wc -l") << "\n";**

  return Status::OK();
}

Status GetTopLabels(const std::vector<Tensor>& outputs, int how_many_labels,
                    Tensor* indices, Tensor* scores) {
  auto root = tensorflow::Scope::NewRootScope();
  using namespace ::tensorflow::ops;  // NOLINT(build/namespaces)

  string output_name = "top_k";
  TopK(root.WithOpName(output_name), outputs[0], how_many_labels);
  tensorflow::GraphDef graph;
  TF_RETURN_IF_ERROR(root.ToGraphDef(&graph));

  std::unique_ptr<tensorflow::Session> session(
      tensorflow::NewSession(tensorflow::SessionOptions()));
  TF_RETURN_IF_ERROR(session->Create(graph));
  std::vector<Tensor> out_tensors;
  TF_RETURN_IF_ERROR(session->Run({}, {output_name + ":0", output_name + ":1"},
                                  {}, &out_tensors));
  *scores = out_tensors[0];
  *indices = out_tensors[1];
  return Status::OK();
}

Status PrintTopLabels(const std::vector<Tensor>& outputs,
                      const string& labels_file_name) {
  std::vector<string> labels;
  size_t label_count;
  Status read_labels_status =
      ReadLabelsFile(labels_file_name, &labels, &label_count);
  if (!read_labels_status.ok()) {
    LOG(ERROR) << read_labels_status;
    return read_labels_status;
  }
  const int how_many_labels = std::min(5, static_cast<int>(label_count));
  Tensor indices;
  Tensor scores;
  TF_RETURN_IF_ERROR(GetTopLabels(outputs, how_many_labels, &indices, &scores));
  tensorflow::TTypes<float>::Flat scores_flat = scores.flat<float>();
  tensorflow::TTypes<int32>::Flat indices_flat = indices.flat<int32>();
  for (int pos = 0; pos < how_many_labels; ++pos) {
    const int label_index = indices_flat(pos);
    const float score = scores_flat(pos);
    LOG(INFO) << labels[label_index] << " (" << label_index << "): " << score;
  }
  return Status::OK();
}

Status CheckTopLabel(const std::vector<Tensor>& outputs, int expected,
                     bool* is_expected) {
  *is_expected = false;
  Tensor indices;
  Tensor scores;
  const int how_many_labels = 1;
  TF_RETURN_IF_ERROR(GetTopLabels(outputs, how_many_labels, &indices, &scores));
  tensorflow::TTypes<int32>::Flat indices_flat = indices.flat<int32>();
  if (indices_flat(0) != expected) {
    LOG(ERROR) << "Expected label #" << expected << " but got #"
               << indices_flat(0);
    *is_expected = false;
  } else {
    *is_expected = true;
  }
  return Status::OK();
}

int main(int argc, char* argv[]) {
  string image = "/home/twentyface/Projects/C++/tf_threads/images/grace_hopper.jpg";
  string graph = "/home/twentyface/Projects/C++/tf_threads/examples/example3/data/inception_v3_2016_08_28_frozen.pb";
  string labels = "/home/twentyface/Projects/C++/tf_threads/examples/example3/data/imagenet_slim_labels.txt";
  int32 input_width = 299;
  int32 input_height = 299;
  float input_mean = 0;
  float input_std = 255;
  string input_layer = "input";
  string output_layer = "InceptionV3/Predictions/Reshape_1";
  bool self_test = false;
  string root_dir = "";
  std::vector<Flag> flag_list = {
      Flag("image", &image, "image to be processed"),
      Flag("graph", &graph, "graph to be executed"),
      Flag("labels", &labels, "name of file containing labels"),
      Flag("input_width", &input_width, "resize image to this width in pixels"),
      Flag("input_height", &input_height,
           "resize image to this height in pixels"),
      Flag("input_mean", &input_mean, "scale pixel values to this mean"),
      Flag("input_std", &input_std, "scale pixel values to this std deviation"),
      Flag("input_layer", &input_layer, "name of input layer"),
      Flag("output_layer", &output_layer, "name of output layer"),
      Flag("self_test", &self_test, "run a self test"),
      Flag("root_dir", &root_dir,
           "interpret image and graph file names relative to this directory"),
  };
  string usage = tensorflow::Flags::Usage(argv[0], flag_list);
  const bool parse_result = tensorflow::Flags::Parse(&argc, argv, flag_list);
  if (!parse_result) {
    LOG(ERROR) << usage;
    return -1;
  }

  // We need to call this to set up global state for TensorFlow.
  tensorflow::port::InitMain(argv[0], &argc, &argv);
  if (argc > 1) {
    LOG(ERROR) << "Unknown argument " << argv[1] << "\n" << usage;
    return -1;
  }

  std::cout << "Loading model...\n\n";
  // First we load and initialize the model.
  std::unique_ptr<tensorflow::Session> session;
  string graph_path = tensorflow::io::JoinPath(root_dir, graph);
  Status load_graph_status = LoadGraph(graph_path, &session);
  if (!load_graph_status.ok()) {
    LOG(ERROR) << load_graph_status;
    return -1;
  }

  std::cout << "Preparing input tensors...\n\n";
  // Get the image from disk as a float array of numbers, resized and normalized
  // to the specifications the main graph expects.
  std::vector<Tensor> resized_tensors;
  string image_path = tensorflow::io::JoinPath(root_dir, image);
  Status read_tensor_status =
      ReadTensorFromImageFile(image_path, input_height, input_width, input_mean,
                              input_std, &resized_tensors);
  if (!read_tensor_status.ok()) {
    LOG(ERROR) << read_tensor_status;
    return -1;
  }
  const Tensor& resized_tensor = resized_tensors[0];

  std::cout << "Running the image through the model...\n\n";
  **std::cout << "Thread count: " << system("top -H -b -n1 | grep example | wc -l") << "\n";
  // Actually run the image through the model.
  tensorflow::RunOptions run_options;
  run_options.mutable_experimental()->set_use_run_handler_pool(true);
  tensorflow::RunMetadata run_metadata;

  std::vector<Tensor> outputs;
  //Status run_status = session->Run({{input_layer, resized_tensor}}, {output_layer}, {}, &outputs);
  Status run_status = session->Run(run_options, {{input_layer, resized_tensor}}, {output_layer}, {}, &outputs, &run_metadata);**
  if (!run_status.ok()) {
    LOG(ERROR) << "Running model failed: " << run_status;
    return -1;
  }
  **std::cout << "Thread count: " << system("top -H -b -n1 | grep example | wc -l") << "\n";**

  std::cout << "Automated testing...\n\n";
  if (self_test) {
    bool expected_matches;
    Status check_status = CheckTopLabel(outputs, 653, &expected_matches);
    if (!check_status.ok()) {
      LOG(ERROR) << "Running check failed: " << check_status;
      return -1;
    }
    if (!expected_matches) {
      LOG(ERROR) << "Self-test failed!";
      return -1;
    }
  }

  // Do something interesting with the results we've generated.
  Status print_status = PrintTopLabels(outputs, labels);
  if (!print_status.ok()) {
    LOG(ERROR) << "Running print failed: " << print_status;
    return -1;
  }

  return 0;
}
```

**Comment by roywei** [comment] 2020-09-17 18:10
Hi, it seems TF changed the environment variable name to : `TF_NUM_INTEROP_THREADS` and `TF_NUM_INTRAOP_THREADS` you can set both to 1 works for me.

```
export TF_NUM_INTEROP_THREADS=1
export TF_NUM_INTRAOP_THREADS=1
```

**Comment by fisakhan** [comment] 2020-09-20 16:08
@roywei how did you count the threads? Did you use "top -H -b -n1 | grep example | wc -l"? The environement variables that you use are equivalent to ```
config.set_inter_op_parallelism_threads(1);
  config.set_intra_op_parallelism_threads(1);
``` in TensorFlow C++ API.

**Comment by fisakhan** [comment] 2020-09-22 13:37
What source code of TensorFlow 2.3 C++ API to change if I want to build TF from source for keeping it to single-threaded?

**Comment by fisakhan** [comment] 2020-09-30 11:34
@Zantares @roywei Do you agree with the reason given at the following link? It explains that TensorFlow cannot be a single threaded. https://stackoverflow.com/questions/48696900/why-tensorflow-creates-so-many-cpu-threads

**Comment by Zantares** [comment] 2020-10-12 08:29
> @Zantares @roywei Do you agree with the reason given at the following link? It explains that TensorFlow cannot be a single threaded. https://stackoverflow.com/questions/48696900/why-tensorflow-creates-so-many-cpu-threads

Not exactly, this answer said that GPU has CUDA runtime and GRPC engine to generate multi-threads, but as I said CPU can be executed as "single thread" mode.

You can use "single thread" mode on CPU with python API definitely. but it may become complex with C API. Because I didn't have your dataset and can't run your case directly, I don't know what the issue is in your case. You can roughly modified TF source code to set all thread number to 1 if have no other good solution.

**Comment by fisakhan** [comment] 2020-10-12 14:15
@Zantares How to use "single thread" mode on CPU wiht Python API?

**Comment by Zantares** [comment] 2020-10-13 00:29
@fisakhan you can start from a python model, and:
1. if you are using TF 1.x, you need to set inter/intra config in session like [this](https://github.com/google-research/bert/pull/876/files#diff-51759dcea7f50f6314e4b971c159bf19846d38e5705567b36d09b42dfb61410dR833). But this configuration will be ignored sometimes due to TF internal issue of TF, so it's not the best way to use.
2. if you are using TF .2x, you can set the environment var(TF_NUM_INTEROP_THREADS/TF_NUM_INTRAOP_THREADS) directly.

Because TF uses a multilayer structure, you can see 3 threads at least even you set all thread configuration to 1: one is python thread, one is inter thread and one is intra thread.

The reason why these configuration doesn't work for C API is that you may lack some default configuration when run C API directly and it may change the behavior of thread pool. Currently I know  that `set_use_run_handler_pool` is an issue.

**Comment by Zantares** [comment] 2020-10-13 17:04
Maybe some implicit behavior created more threads than expected:
I got **22** threads in my below case when set inter/intra to 1, and it will increase to **40** if I set each of them to 10. These 2 options are working well to control work thread number, but TF has created other threads and showed confusing information in **top**.


My cmd
```shell
numactl -C 0-7 -l python conv.py
```
And I got
```
Total number of threads: 
22
```
After increasing inter/intra to 10, I got
```
Total number of threads: 
40
```

My case **conv.py**:
```python
import tensorflow as tf
import os

# reduce number of threads
os.environ['TF_NUM_INTEROP_THREADS'] = '1' 
os.environ['TF_NUM_INTRAOP_THREADS'] = '1' 

print('\n\nTotal number of threads: ')
os.system( "top -H -b -n1 | grep python | wc -l")

def my_model():
  layer_input = tf.random.uniform((1, 2, 3, 3), minval=0, maxval=100, dtype=tf.float32)
  weights = tf.random.uniform((1, 2, 3, 3), minval=0, maxval=100, dtype=tf.float32)

  with tf.compat.v1.variable_scope("output_1"):
    outputs_1 = tf.nn.conv2d(
        input=layer_input, filters=weights, strides=1,
        # padding=[[0, 0], [1, 1], [1, 1], [0, 0]])
        padding='SAME')
    outputs_1 = tf.nn.bias_add(outputs_1, tf.constant([1, 1, 1], dtype=tf.float32))

  return outputs_1

with tf.compat.v1.Session() as sess:
  loss = my_model()
  print('\n\nTotal number of threads: ')
  os.system( "top -H -b -n1 | grep python | wc -l")
  init = tf.compat.v1.initialize_all_variables()
  sess.run(init)
  sess.run((loss))
  print('\n\nTotal number of threads: ')
  os.system( "top -H -b -n1 | grep python | wc -l")
```

**Comment by fisakhan** [comment] 2020-10-14 11:08
In PyTorch it is as simple as "torch.set_num_threads(1)". It works and generates 3 threads in total (including 1 for python).

**Comment by fisakhan** [comment] 2020-10-27 09:17
If I build TensorFlow from source then what code should I change to disable threading by TensorFlow?

**Comment by Zantares** [comment] 2020-10-27 09:24
> If I build TensorFlow from source then what code should I change to disable threading by TensorFlow?

[Here](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/common_runtime/process_util.cc#L100) to set inter and [here ](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/common_runtime/local_device.cc#L73)to set intra. It works for python API but not sure work for C/C++ API or not.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:15
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:45 UTC
Labels: TF 1.15, comp:runtime, type:bug
