### ISSUE TITLE
Tensorflow 2.0 overwrites logging config

### ISSUE THREAD

**Issue by jankislinger** [tensorflow/tensorflow#28147] opened 2019-04-25 09:29 UTC
**System information**

- Linux Ubuntu 16.04
- Python 3.6.7
- packages: logging 0.5.1.2, tensorflow 2.0.0-alpha0

When importing `tensorflow` any logging user-defined config is ignored and tf config is used instead. Here is an example where logging format and level is changed. Note that the `info` isn't printed at all.

Code:
```
import logging

import tensorflow

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)
logger.info("Some info")
logger.error("Some error")
```

Output:
```
WARNING: Logging before flag parsing goes to stderr.
E0425 11:22:27.150884 140450657982208 temp.py:9] Some error
```

Expected output (as if you delete `import tensorflow` or with older version of `tf`):
```
INFO Some info
ERROR Some error
```

**Comment by jvishnuvardhan** [comment] 2019-04-26 03:37
@jankislinger Thanks for finding the issue. I could reproduce the issue with TF2.0.0-alpha0 and tf-nightly. However, with TF1.13.1, the above code outputs expected output. Thanks!

**Comment by jre21** [comment] 2019-06-24 19:20
I was able to reproduce this bug in tensorflow 1.14.0, which means it is now present in released code.

**Comment by harahu** [comment] 2019-06-28 18:57
Posten this in the issue you mentioned @jre21, but posting it here as well, as it is relevant:

Just importing tensorflow intrusively adds a logging handler to the root logger:
```python
import logging

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    logger.warning("Hi!")

(stderr)>>>
Hi!
```
vs
```python
import logging

import tensorflow as tf

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    logger.warning("Hi!")

(stderr)>>>
WARNING: Logging before flag parsing goes to stderr.
W0628 20:51:13.387141 140355075146048 test.py:9] Hi!
```

This is due to absl adding its own handler to the root logger when importing tensorflow.

**Comment by harahu** [comment] 2019-06-28 19:20
As for tf 1.14, the problem seems to stem for how absl is used in tf 2.0:
https://github.com/tensorflow/tensorflow/blob/8e423e3d56390671f0d954c90f4fd163ab02a9c1/tensorflow/python/platform/app.py#L23
This results in an undesirable `ABSLHandler` being installed on the root logger.

**Comment by harahu** [comment] 2019-07-02 12:26
@revan I think this is a duplicate of your assigned issue #26691.

**Closed** 2019-07-02 12:52 UTC
Labels: 2.0.0-alpha0, comp:ops, regression issue, stat:awaiting tensorflower, type:bug/performance
