### ISSUE TITLE
The current session will be closed and a new session will be created. Error: Stream IDs exhausted

### ISSUE THREAD

**Issue by zhangwj0101** [tensorflow/tensorflow#31787] opened 2019-08-20 09:05 UTC
**System information**
TensorFlow:
- OS Platform and Distribution (e.g., centos7):
- TensorFlow installed from ( binary):
- TensorFlow version (1.8):

in Distrubuted TensorFlow, train 38 days, we get the error " **INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Stream IDs exhausted** " , 
any better to solve this quesution?

**Comment by ravikyram** [comment] 2019-08-21 09:56
In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-08-29 08:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-29 08:09 UTC
Labels: comp:dist-strat, stat:awaiting response, type:support

**Comment by zhangwj0101** [comment] 2019-09-11 08:24
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

> In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

no other exception info, we just get the information from tensorflow log "INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Stream IDs exhausted"

**Comment by zhangwj0101** [comment] 2019-09-11 08:27
> In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

@ravikyram only get error info "The current session will be closed and a new session will be created. Error: Stream IDs exhausted"

**Comment by ravikyram** [comment] 2019-09-11 09:29
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here.It helps us to debug your issue faster. Thanks!
