### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by cossio** [tensorflow/tensorflow#35920] opened 2020-01-15 23:48 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): from pip (binary?)
- TensorFlow version (use command below): 2.1
- Python version: 3.7
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the current behavior and code to reproduce**

I am running this code:

https://gist.github.com/cossio/dc761b2731b1428267b65333dbd3f321

to train an RBM by contrastive divergence. Briefly I am using the Keras sub-classing API and I view the multiple Monte Carlo samples as layers.

However it produces the following error:

```
TypeError: object of type 'NoneType' has no len()
```

Please find the full error message and stack-trace as a comment on the above gist link.

**Comment by jmanly56** [comment] 2020-01-16 03:20
If I am reading your code correctly, you have: 

```
class CD(keras.Model):
    def __init__(self, rbm, mcsteps = 5, **kwargs):
        super().__init__(self, **kwargs)
```

Whereas the super() call should be formatted like so:
`super(CD, self).__init__()`

You can of course add kwargs, if you wanted to.

As an example, see [this](https://www.tensorflow.org/tutorials/generative/cvae#network_architecture) Tensorflow tutorial.

**Comment by cossio** [comment] 2020-01-16 12:21
@gadagashwini So you think this is a Tensorflow bug and not something wrong in my code? If you have suggestions for a workaround please let me know.

**Comment by jvishnuvardhan** [comment] 2020-03-18 22:39
@cossio I ran your code with `tf-nightly` and everything worked well. I can see the deprecation warning as you mentioned. Other than deprecation warning, I cannot reproduce the error you mentioned. May be the error might have been resolved with recent `tf-nightly`.

```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
Epoch 1/10
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:4291: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().
6000/6000 [==============================] - 10s 2ms/step - loss: -13.3863
Epoch 2/10
6000/6000 [==============================] - 10s 2ms/step - loss: -8.2681
Epoch 3/10
6000/6000 [==============================] - 10s 2ms/step - loss: -5.7110
Epoch 4/10
6000/6000 [==============================] - 10s 2ms/step - loss: -4.1468
Epoch 5/10
6000/6000 [==============================] - 10s 2ms/step - loss: -3.1042
Epoch 6/10
6000/6000 [==============================] - 10s 2ms/step - loss: -2.4848
Epoch 7/10
6000/6000 [==============================] - 10s 2ms/step - loss: -1.8877
Epoch 8/10
6000/6000 [==============================] - 10s 2ms/step - loss: -1.5715
Epoch 9/10
6000/6000 [==============================] - 11s 2ms/step - loss: -1.2992
Epoch 10/10
6000/6000 [==============================] - 10s 2ms/step - loss: -1.0544
<tensorflow.python.keras.callbacks.History at 0x7f9baa2238d0>
```

Please close the issue if this was resolved for you. Thanks!

**Comment by cossio** [comment] 2020-03-19 13:44
Great! Will this be available in the next minor version of tensorflow? When is it planned to be released? @jvishnuvardhan

**Comment by jvishnuvardhan** [comment] 2020-03-19 17:04
@cossio This will be available in near future in `TF2.2` stable version. Currently TF team released `TF2.2.rc1` and in near future they may release `TF2.2` stable version. 

Please close the issue if this was resolved for you. Thanks!

**Comment by cossio** [comment] 2020-03-19 17:37
@jvishnuvardhan Well I cannot test for now because I only use TF stable. I will test when 2.2 is released. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-29 22:35
I am closing this as this was resolved in `tf-nightly` and will be available in stable `TF2.2` which will be release in near future (currently TF2.2rc3 released more than a week ago). 

Please feel free to reopen if this persists in `TF2.2` stable. Thanks!

**Closed by jvishnuvardhan** 2020-04-29 22:35 UTC
Labels: TF 2.1, comp:keras, type:bug
