### ISSUE TITLE
keras.callbacks.ModelCheckPoint has a problem when filepath of working directory is long

### ISSUE THREAD

**Issue by princyok** [tensorflow/tensorflow#40642] opened 2020-06-21 01:10 UTC
**System information**
- 
- OS Platform and Distribution: Windows 10
- TensorFlow version: 2.1.0
- Python version: 3.7.4

**Issue**
If the filepath to the current working directory is long, then keras.callbacks.ModelCheckPoint fails when creating a checkpoint. It raises a `NotFoundError`.

Two forms of the messages that I've encountered are:

> NotFoundError: Failed to create a directory: issues_with_mixed_slashes\too_damn_buggy\checkpoint_1/variables; No such file or directory

OR

> NotFoundError: Failed to create a NewWriteableFile: issues_with_mixed_slashes\too_damn_buggy\checkpoint_1\variables\variables_temp_af3a37dbc2fc491b87d8afc1eab1ef3a/part-00000-of-00001.data-00000-of-00001.tempstate5339521814986627484 : The system cannot find the path specified.
> ; No such process [Op:SaveV2]

Some working directories produce the first kind and some others produce the second kind.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import os
import numpy as np

n=10
x = np.random.random((n,1))
y = np.random.random((n,1))

# set `new_cwdir` to a really long path for the two commented out lines below.
# os.mkdir(new_cwdir)
# os.chdir(new_cwdir)

all_callbacks=[]
checkpoint_filepath = "issues_with_mixed_slashes\\too_damn_buggy\\checkpoint_{epoch}"
all_callbacks.append(
    tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_filepath, monitor='loss', verbose=1))

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=x.shape[-1:]))
model.add(tf.keras.layers.Dense(1))

epochs = 2
model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.MeanAbsoluteError())
history = model.fit(x=x, y=y, epochs=epochs, callbacks=all_callbacks)
```
If you set the working directory to something closer to the root directory, the problem will not occur.

**More info** 
I suspect that the mixing of `/` and `\`  when TensorFlow tries to create a new directory is (or is part of) the cause.

**Comment by ravikyram** [comment] 2020-06-22 06:51
@princyok 

I have tried in colab with TF versions 2.1,2.2 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ecffe407c4f1e17fb91f9090f466104a/untitled53.ipynb).Thanks!

**Comment by princyok** [comment] 2020-06-23 00:16
I verified and I'm not seeing any issue in colab as well. I also tried with another machine and it didn't occur. But it still occurs in a different machine. Both Windows 10, 64-bit. I'm not sure why.

**Comment by ravikyram** [comment] 2020-06-30 07:55
@princyok 

This is not a bug in Tensorflow and something specific to your machine. Please, close this thread as this issue is not related to Tensorflow.Thanks!

**Closed** 2020-07-12 01:50 UTC
Labels: TF 2.1, comp:keras, stalled, stat:awaiting response, type:bug

**Comment by princyok** [comment] 2020-07-28 03:56
Found a workaround to this problem from [issue #32505](https://github.com/tensorflow/tensorflow/issues/32505). Use `os.path.join` to create the filepath.  

I initially thought it shouldn't make a meaningful difference, but I stopped getting the errors when I used `os.path.join`. It's worked out so far. I still feel there is an underlying issue with how TensorFlow creates new directories on Windows when saving models, but this workaround worked so far.

So in the standalone code above, it will be: 
`checkpoint_filepath = os.path.join("issues_with_mixed_slashes", "too_damn_buggy", "checkpoint_{epoch}")`

**Comment by princyok** [comment] 2021-02-04 20:38
The earlier post was a temporary solution, arguably not a solution (I still don't see why it should've made any difference, but it temporarily did, and that was almost certainly a fluke). 

PERMANENT SOLUTION: Remove the limit that Windows has on the maximum length of path (which is 260 characters). Set the LongPathsEnabled key in Registry to 1.

**Comment by princyok** [comment] 2021-02-04 20:40
The earlier post was a temporary solution, arguably not a solution (I still don't see why it should've made any difference, but it temporarily did, and that was almost certainly a fluke). 

PERMANENT SOLUTION: Remove the limit that Windows has on the maximum length of path (which is 260 characters). Set the LongPathsEnabled key in Registry to 1.
