### ISSUE TITLE
tf.distriubte.strategy() doesn't support multiple input, multiple input will report an error:TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by lijinze9456yy000** [tensorflow/tensorflow#34086] opened 2019-11-08 02:02 UTC
Hi,I find a bug.I have found that the workaround those not work if the model has multiple inputs. The following code fails:

import numpy as np
import tensorflow as tf
#strategy = tf.distribute.MirroredStrategy()
strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

def generator():
    while True:
        yield [np.ones([10, 10], np.float32), np.ones([10, 10], np.float32)], np.ones([10, 1], np.float32)
with strategy.scope():
    inputA = tf.keras.layers.Input(shape=(10,))
    inputB = tf.keras.layers.Input(shape=(10,))
    output = tf.keras.layers.Concatenate()([inputA, inputB])
    output = tf.keras.layers.Dense(1, input_shape=(10,), activation="relu")(output)
    model = tf.keras.models.Model(inputs=[inputA, inputB], outputs=output)
    model.compile('Adam', 'mae')
    model.fit(generator(), steps_per_epoch=1000, epochs=10)

The error is as follows：
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
How can I solve this problem?

**Comment by ravikyram** [comment] 2019-11-11 09:52
@lijinze9456yy000 

Can you please let us know which version of TensorFlow you are using?. Thanks!

**Comment by ravikyram** [comment] 2019-11-19 11:42
@lijinze9456yy000 

Any update on this issue please.Thanks!

**Comment by ravikyram** [comment] 2019-11-29 10:04
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-11-29 10:04 UTC
Labels: comp:dist-strat, stat:awaiting response, type:support

**Comment by Dr-Gandalf** [comment] 2020-01-03 15:17
I am using TF2.0 with this docker  "tensorflow/tensorflow:latest-gpu-py3-jupyter", and have a similar problem, my model has two images and a vector input and it has 14 categorical outputs each with 3 clases. 
this line works but terrible slow
```python
T_history = classification_model.fit_generator(trainGenerator, steps_per_epoch=100,
                                              validation_data=validation_generator,
                                              validation_steps=validation_steps, 
                                              callbacks=callbacks_list,
                                              epochs=6,
                                              use_multiprocessing=True,
                                              workers=8,
                                              max_queue_size=50)
```
and this one gives the error reported here:
```python
T_history = classification_model.fit(trainGenerator, steps_per_epoch=100,
                                              validation_data=validation_generator,
                                              validation_steps=validation_steps, 
                                              callbacks=callbacks_list,
                                              epochs=6,
                                              use_multiprocessing=True,
                                              workers=8,
                                              max_queue_size=50,
                                              shuffle=False)
```

**Comment by vinhtknguyen** [comment] 2020-02-07 16:05
I confirmed that I encounter a similar issue.

**Comment by grwche** [comment] 2020-05-06 08:47
use a tuple, not a list, in the return statement of the generator:

return ((x1, x2, ...), y)

not:

return [x1, x2, ...], y

+ shuffle=False in the call to fit

**Comment by thf24** [comment] 2020-11-10 17:49
I had the same issue and it is indeed solved by the generator not yielding a list but a tuple for the FEATURES. I feel like this is a bit inconsistent, as the features are supposed to be a list when you call model.fit without a generator (and multiple inputs of course)
