### ISSUE TITLE
Eager code with tf.function decoration is >2x slower than without it.

### ISSUE THREAD

**Issue by HansiZeng** [tensorflow/tensorflow#35840] opened 2020-01-14 02:18 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow version: 
    TF 2.0.0
- Python version:
   Python 3.7.6
- CUDA/cuDNN version:
   10.0.130
- GPU model and memory:
   GTX2080

**Describe the current behavior**
I walk through the ```@tf.function``` usage examples from [Tensorflow Tutorial](https://www.tensorflow.org/guide/function). There is a example shows that the eager code version of  ```conv_layer``` with ```@tf.function``` decorator could run faster than without it. However, when I imitate it and write eager code version  of ```embedding_layer```, the decorator one is >2x slower than the not decorator one. See the code below

**Code to reproduce the issue**
```
# check time it for embedding layer
from tensorflow.keras.initializers import RandomUniform
import numpy as np
import tensorflow as tf

input_dim = 1000
output_dim = 300
emb_layer = tf.keras.layers.Embedding(input_dim, output_dim, RandomUniform(-1,1))

@tf.function
def emb_fn(indices):
    return emb_layer(indices)


indices = np.random.randint(0, input_dim-1, size=64)
indices = tf.constant(indices)
# warm up
emb_layer(indices); emb_fn(indices)

print("Eager embed: ", timeit.timeit(lambda: emb_layer(indices), number=10000))
print("Function embed: ", timeit.timeit(lambda: emb_fn(indices), number=10000))
```
**The result**
Eager embed:  1.895560858771205
Function embed:  4.15901411511004

**Comment by amahendrakar** [comment] 2020-01-14 13:41
@HansiZeng,
I tried to reproduce the issue but could not find much difference in the execution time. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/63ea6bcef523087f47a14ef0eb8401a5/35840.ipynb).

**Comment by HansiZeng** [comment] 2020-01-15 02:15
@amahendrakar, 
I found TF: 2.1.0 actually fixed the issue as you code shown, but in TF: 2.0.0 the running time difference exists. To reproduce the result, you can convert your TF version to 2.0.0.

**Comment by amahendrakar** [comment] 2020-01-17 13:24
Was able to reproduce the issue with TF 2.0. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/d4b1ca4e863f070c923a4ce9d36ee58a/35840_copy.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-17 21:24
@HansiZeng There were couple of important performance improvements after releasing `TF2.0`. So please use latest stable version for better performance. Another reason for the small difference in performance is due to overhead of the @tf.function. 

Best and more detailed answer for a similar question was provided [here](https://github.com/tensorflow/tensorflow/issues/35720#issuecomment-574188882) by @mdanatg as follows

> Unfortunately, tf.function is not always faster for small computations. The reason is quite simple: calling an empty tf.function is more expensive than calling an empty Python function. This is especially true when the computations involve scalars, when the speed gained inside the function is too small to recover the cost of calling it.
> 
> This can sometimes be avoided by one of the following:
> 
> vectorizing the computation (e.g. instead of operating on one example at a time, operate on an entire batch); here is such an example
> adding experimental_compile=True, which can greatly speed up complex scalar computations when XLA support is available
> you may also speed things up by moving more computation inside the tf.function iself
> This is something that we're addressing, as there are a few inefficiencies in the current implementation.

I am closing this issue. Please let me know if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2020-01-17 21:24 UTC
Labels: TF 2.0, comp:autograph, type:performance
