### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Can not get size for:

### ISSUE THREAD

**Issue by Nassimbelmecheri** [tensorflow/tensorflow#15314] opened 2017-12-12 13:43 UTC
D:\Python\Python35\models-master\research\object_detection>D:\Python\Python35\python train.py --logtostderr --train_dir=training\ --pipline_config_path=training\ssd_mobilenet_v1_pets.config
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "C:\Users\USER\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 106, in main
    overwrite=True)
  File "C:\Users\USER\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\lib\io\file_io.py", line 384, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "D:\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\USER\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Can not get size for:  : path d\udc92acc\udce8s sp\udce9cifi\udce9 not found

**Comment by andydavis1** [comment] 2017-12-13 01:26
Please fill out the template and include code for a reproducible test case.

**Comment by tensorflowbutler** [comment] 2017-12-13 01:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Nassimbelmecheri** [comment] 2017-12-13 02:23
OS Platform : windows
TensorFlow version ; latest
Bazel version: ?
CUDA/cuDNN version : latest
GPU model and memory : Nvidia 980 m 2g
Exact command to reproduce :
python train.py --logtostderr --train_dir=training\ --pipline_config_path=training\ssd_mobilenet_v1_pets.config

**Comment by tensorflowbutler** [comment] 2018-01-03 07:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-17 19:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by Nassimbelmecheri** [comment] 2018-01-17 20:18
Yes

**Comment by tensorflowbutler** [comment] 2018-01-23 22:54
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment] 2018-01-31 19:35
This seems to be a duplicate. Closing.

**Closed by drpngx** 2018-01-31 19:35 UTC

**Comment by zhangyinsheng** [comment] 2018-02-09 03:03
I've encountered the same problem. In my case, this is actually caused by a silly mispelling mistake: 

It SHOULD BE:
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

BUT I USED:
python train.py --logtostderr --train_dir=training/ --pipelie_config_path=training/ssd_mobilenet_v1_pets.config

This makes "train.py" unable to parse the "FLAGS.pipeline_config_path", and activates the "else" branch: 

  if FLAGS.pipeline_config_path:
    configs = config_util.get_configs_from_pipeline_file(
        FLAGS.pipeline_config_path)
    if FLAGS.task == 0:
      tf.gfile.Copy(FLAGS.pipeline_config_path,
                    os.path.join(FLAGS.train_dir, 'pipeline.config'),
                    overwrite=True)
  else:
    configs = config_util.get_configs_from_multiple_files(
        model_config_path=FLAGS.model_config_path,
        train_config_path=FLAGS.train_config_path,
        train_input_config_path=FLAGS.input_config_path)
    if FLAGS.task == 0:
      for name, config in [('model.config', FLAGS.model_config_path),
                           ('train.config', FLAGS.train_config_path),
                           ('input.config', FLAGS.input_config_path)]:
        tf.gfile.Copy(config, os.path.join(FLAGS.train_dir, name),
                      overwrite=True)
