### ISSUE TITLE
Old python version

### ISSUE THREAD

**Issue by daninja7** [tensorflow/tensorflow#9248] opened 2017-04-16 12:56 UTC
I have python 3.6.0 but tensorflow only supports 3.5

**Comment by asimshankar** [comment] 2017-04-16 16:56
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

(Closing this issue out due to lack of information and I suspect that this is a duplicate of #6999. If that is not the case, please feel free to file a new issue with all requested details)

**Closed by asimshankar** 2017-04-16 16:56 UTC
