### ISSUE TITLE
Instance of 'CheckpointState' has no 'model_checkpoint_path' member

### ISSUE THREAD

**Issue by TheBlackPlague** [tensorflow/tensorflow#23732] opened 2018-11-14 11:07 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Package based PIP installation
- TensorFlow version (use command below): 1.12.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
So I am trying to get checkpoint path, but I am unable to. Error:
Instance of 'CheckpointState' has no 'model_checkpoint_path' member

**Describe the expected behavior**
No error and able to get checkpoint path.

**Code to reproduce the issue**
```
def restore(s, save_instance):
    checkpoint = tensorflow.train.get_checkpoint_state(os.path.dirname(configuration.CHECKPOINT_PATH + "/checkpoint"))
    if checkpoint and checkpoint.model_checkpoint_path:
        print("Loading...")
        save_instance.restore(s, checkpoint.model_checkpoint_path)
    else:
        print("New Instance being created...")
```

**Comment by TheBlackPlague** [comment] 2018-11-16 19:08
Is there going to be a follow-up?

**Comment by allenlavoie** [comment] 2018-11-19 20:49
I can't reproduce. Could you put an end-to-end example together?

Here's what works for me:

import tensorflow as tf

```
def restore(save_path):
    checkpoint = tf.train.get_checkpoint_state(save_path)
    if checkpoint and checkpoint.model_checkpoint_path:
        print("Loading... {}".format(checkpoint.model_checkpoint_path))
    else:
        print("New Instance being created...")

tf.train.update_checkpoint_state("/tmp/", model_checkpoint_path="blah")
restore("/tmp/")
```

Prints:

> Loading... /tmp/blah

**Comment by allenlavoie** [comment] 2018-11-26 17:18
I removed `/tmp/checkpoint` and re-ran. I'm using Python 3.6; I don't have 3.7 installed. I'm also on Linux, but we have similar unit tests which run on Windows. 

Does it work for you on Python 3.6? Presumably not using `"/tmp/"` since that isn't meaningful on Windows.

**Comment by ZYB19960829** [comment] 2019-03-25 09:40
？

**Comment by allenlavoie** [comment] 2019-03-25 16:14
Closing as not reproducible, but please do follow up if it's still an issue.

**Closed by allenlavoie** 2019-03-25 16:14 UTC
