### ISSUE TITLE
OP_REQUIRES failed : Not found: No algorithm worked!

### ISSUE THREAD

**Issue by Ambistic** [tensorflow/tensorflow#43223] opened 2020-09-14 19:46 UTC
**System information**
- OS Platform and Distribution:  Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip install)
- TensorFlow version (use command below): v1.12.1-41444-g9396e98574 2.4.0-dev20200913
- Python version: 3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 and 8.0
- GPU model and memory: GTX 2060

**Describe the current behavior**
The script crashes at prediction.

**Describe the expected behavior**
The script shall compute prediction

**Standalone code to reproduce the issue**
```
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
import numpy as np

model = Sequential([
    ResNet50(include_top=False, weights="imagenet", input_shape=(224, 224, 3), pooling="avg"),
    Dropout(0.5),
    Dense(64, activation='relu'),
])

X = np.zeros((1, 224, 224, 3))
print(model.predict(X))
```

Note that if adding the line `tf.config.set_visible_devices([], 'GPU')`, this problem disappear

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
2020-09-14 21:29:32.163353: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-14 21:29:32.931061: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-09-14 21:29:32.931534: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-14 21:29:32.953860: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.954284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.68GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2020-09-14 21:29:32.954301: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-14 21:29:32.956135: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-09-14 21:29:32.957003: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-14 21:29:32.957172: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-14 21:29:32.959170: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-14 21:29:32.959632: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-09-14 21:29:32.959728: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-09-14 21:29:32.959814: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.960277: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.960669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-14 21:29:32.960919: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-14 21:29:32.961335: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-09-14 21:29:32.961418: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.961827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.68GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2020-09-14 21:29:32.961841: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-14 21:29:32.961854: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-09-14 21:29:32.961864: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-14 21:29:32.961873: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-14 21:29:32.961882: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-14 21:29:32.961892: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-09-14 21:29:32.961900: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-09-14 21:29:32.961949: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.962375: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:32.962759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-14 21:29:32.962779: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-14 21:29:33.321292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-14 21:29:33.321321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-14 21:29:33.321325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-14 21:29:33.321485: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:33.321815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:33.322113: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-14 21:29:33.322399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5352 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:09:00.0, compute capability: 7.5)
2020-09-14 21:29:34.367791: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 1)
2020-09-14 21:29:34.384838: I tensorflow/core/platform/profile_utils/cpu_utils.cc:108] CPU Frequency: 3593095000 Hz
2020-09-14 21:29:34.803301: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-09-14 21:29:35.075322: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-09-14 21:29:35.505290: W tensorflow/core/framework/op_kernel.cc:1774] OP_REQUIRES failed at conv_ops.cc:1114 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "report_bug.py", line 13, in <module>
    print(model.predict(X))
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 102, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1584, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 787, in __call__
    result = self._call(*args, **kwds)
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 853, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 556, in call
    outputs = execute.execute(
  File "/opt/jupyterhub/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
         [[node sequential/resnet50/conv1_conv/Conv2D (defined at report_bug.py:13) ]] [Op:__inference_predict_function_6649]

Function call stack:
predict_function
```

**Comment by bhack** [comment] 2020-09-14 21:06
What is the output of:
```
import tensorflow as tf
print(tf.config.list_physical_devices())
```

**Comment by ravikyram** [comment] 2020-09-15 06:30
@Ambistic 

I have tried in colab with TF nightly version and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3f34c393bb1371f297bcc9cea6f0ca4f/untitled351.ipynb).

It looks like cuda problem.Can you try with tested build configurations from [here](https://www.tensorflow.org/install/source#gpu) and see if the problem still persists. Thanks!

**Comment by bhack** [comment] 2020-09-15 08:55
@ravikyram  You cannot test tf-nightly with GPU only ISSUES on colab currently cause It has only CPU visibile devices.

**Comment by bhack** [comment] 2020-09-15 08:56
@ravikyram check https://github.com/tensorflow/tensorflow/issues/42957

**Comment by Ambistic** [comment] 2020-09-15 09:55
> What is the output of:
> 
> ```
> import tensorflow as tf
> print(tf.config.list_physical_devices())
> ```

The output is :
```
2020-09-15 11:52:23.068529: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-09-15 11:52:23.069203: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-15 11:52:23.094984: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-15 11:52:23.095310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:09:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.68GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2020-09-15 11:52:23.095332: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-09-15 11:52:23.097519: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-09-15 11:52:23.098514: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-15 11:52:23.098681: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-15 11:52:23.100594: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-15 11:52:23.101058: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-09-15 11:52:23.101151: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-09-15 11:52:23.101234: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-15 11:52:23.101552: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-15 11:52:23.101800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

@ravikyram I actually need features from tensorflow 2.3.0 and I couldn't find it in the tested build configurations

**Comment by bhack** [comment] 2020-09-15 10:16
Can you print `tf.config.get_visible_devices()`?

**Comment by Ambistic** [comment] 2020-09-15 10:33
> Can you print `tf.config.get_visible_devices()`?

`[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

Just as previous output

**Comment by bhack** [comment] 2020-09-15 10:42
And do you still require `tf.config.set_visible_devices([], 'GPU')`?
Have you tried with the last `tf-nightly`?

**Comment by Ambistic** [comment] 2020-09-15 14:28
Yes I still require that line and it's the same with `tf-nightly-2.4.0.dev20200915`

Interestingly, this error appear when creating a model with a submodel from tensorflow.keras.applications and a layers (such as Dense), but the problem dissappear if using only the application or only the keras layers. 
It's also working if using a model from applications and only Dropout, not Dense

**Comment by bhack** [comment] 2020-09-15 14:47
So the problem is only on GPU. 
I need to wait for https://github.com/googlecolab/colabtools/issues/1574 to check if it is reproducible on tf-nightly.

**Comment by jaentrouble** [comment] 2020-09-30 02:08
Have you tried setting set_memory_growth to True?

**Comment by Ambistic** [comment] 2020-10-01 18:45
Actually it seems to work, thank you very much !

**Comment by Ambistic** [comment] 2020-10-01 18:46
This is the code to add
```python
physical_devices = tf.config.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
    pass
```

**Comment by vikalpjain91** [comment] 2020-10-02 02:57
if that is not the case probably we have to restart the environment to make things working!

**Comment by ravikyram** [comment] 2020-10-09 12:56
@Ambistic 

Please, close this thread if your issue was resolved. Thanks!

**Closed** 2020-10-09 16:28 UTC
Labels: stat:awaiting response, type:bug

**Comment by Ambistic** [comment] 2020-10-09 19:34
I add that using Model() instead of Sequential() seems also to correct the problem

**Comment by skaldek** [comment] 2020-11-20 07:42
Same issue using r2.4 sources on arch.

**Comment by ShuttleDDD** [comment] 2021-03-29 18:51
same issue when using TF2.4.1 on RTX3060, compiled by myself, weird

**Comment by SaifeddineBarkia** [comment] 2021-09-17 14:49
> same issue when using TF2.4.1 on RTX3060, compiled by myself, weird

Did u find the solution?
