### ISSUE TITLE
Query result not show aliased functions

### ISSUE THREAD

**Issue by zchrissirhcz** [tensorflow/tensorflow#40976] opened 2020-07-01 09:28 UTC
If we search `tf.argmax` in [tensorflow r1.15 documentation](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/math/argmax), no result get for tf 1.x

However, if search "tf.math.argmax", you will get it.

But they're both annations:
```Python
# pylint: disable=redefined-builtin
@tf_export(v1=["math.argmax", "argmax"])         # !!!! This line
@deprecation.deprecated_args(None, "Use the `axis` argument instead",
                             "dimension")
@_set_doc(
    gen_math_ops.arg_max.__doc__.replace("dimensions", "axes").replace(
        "dimension", "axis"))
def argmax(input,
           axis=None,
           name=None,
           dimension=None,
           output_type=dtypes.int64):
  axis = deprecation.deprecated_argument_lookup(
      "axis", axis, "dimension", dimension)
  return argmax_v2(input, axis, output_type, name)
```

Why only show the first aliased annotation in documentation?

**Comment by aavishkarmishra** [comment] 2020-07-08 19:35
### I would like to work of this issue.
Can anyone explain me why is this happening ? 
@jvishnuvardhan

**Comment by aavishkarmishra** [comment] 2020-07-19 16:08
@MarkDaoust can you help me whit my doubt ?

**Comment by MarkDaoust** [comment] 2020-07-20 20:58
Hi @aavishkarmishra,

Thanks for your interest. There's no easy fix for this. 

It would be a big rewrite to the code that generates the _toc.yaml file here. 

I agree that we should to it, but its a simple fix.

**Comment by aavishkarmishra** [comment] 2020-07-24 08:03
Then can you tell where I can find the code generates the _toc.yaml file here, this can help me understanding more about how this stuff actually works.

**Comment by zchrissirhcz** [comment] 2020-07-24 08:25
@MarkDaoust Yes, please provide some hints for where these docs are generated.

**Comment by MarkDaoust** [comment] 2020-07-24 12:38
Sorry, in my earlier comment I was missing a **not** on the last line.

The code that does this is here: https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/generate_lib.py#L539-L541

But the problem is that it currently doesn't have access to an organized view of those aliases, I'd need to change the lower levels to pass up the tree structure being generated here:

https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/doc_generator_visitor.py#L76

**Comment by aavishkarmishra** [comment] 2020-07-25 19:38
@MarkDaoust How can I start with this, as I cannot see that how can we provide access to an organised view of those classes.

Actually I don't exactly got the idea that where those aliases are being used.

**Closed** 2022-03-16 14:08 UTC
Labels: type:docs-bug, comp:ops
