### ISSUE TITLE
Error using TensorBoard callback with histogram_freq > 0

### ISSUE THREAD

**Issue by agchitu** [tensorflow/tensorflow#33210] opened 2019-10-10 14:27 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): installed with pip 
- TensorFlow version (use command below): 1.14.0
- Python version: Python 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda_10.1.243_426.00_win10, cudnn-10.1-windows10-x64-v7.6.3.30
- GPU model and memory: GeForce GTX 1060, 6GB dedicated

**Describe the current behavior**
The code in the section bellow results in an error on this line:
https://github.com/tensorflow/tensorflow/blob/025365a736ed10185c1a68c2c896cf5c54b9f69f/tensorflow/python/keras/callbacks_v1.py#L385

The test_function does not have fetch_callbacks defined. The error I get is:
```Python
tensorflow_gpu\lib\site-packages\tensorflow\python\keras\callbacks_v1.py", line 386, in on_epoch_begin
    self.merged] = self._fetch_callback
AttributeError: 'Function' object has no attribute 'fetch_callbacks'
```
**Describe the expected behavior**
There should be no error. The code works only when ```histogram_freq=0```
**Code to reproduce the issue**
```python 
import numpy as np
import tensorflow as tf
from keras.layers import Input, Dense
from keras.models import Model

from keras.optimizers import SGD

num_features = 100
train_x = np.random.rand(40, num_features)
train_y = np.random.randint(2, size=40)

# The input layer
input_layer = Input(shape=(num_features,), name="Input")
output = Dense(10, activation='sigmoid', name="Hidden_1")(input_layer)
output = Dense(1, activation='sigmoid', name="Output")(output)
model = Model(inputs=input_layer, outputs=output)

sgd = SGD(lr=0.01, decay=1e-4, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy',
                     optimizer=sgd,
                      metrics=['accuracy'])

tensorboard_callback = tf.keras.callbacks.TensorBoard(
            log_dir=os.path.join("out_dir", datetime.now().strftime("%Y%m%d-%H%M%S")),
            histogram_freq=2, write_graph=True, write_images=True)
my_callbacks = [tensorboard_callback]

model.fit(x=train_x, y=train_y,
                  validation_split=.2,
                  epochs=5,
                  callbacks=my_callbacks)
```
**Other info / logs**
model summary 
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
Input (InputLayer)           (None, 100)               0         
_________________________________________________________________
Hidden_1 (Dense)             (None, 10)                1010      
_________________________________________________________________
Output (Dense)               (None, 1)                 11        
=================================================================
Total params: 1,021
Trainable params: 1,021
Non-trainable params: 0
_________________________________________________________________
```

**Comment by ravikyram** [comment] 2019-10-11 06:35
Looks like code is incomplete.In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by agchitu** [comment] 2019-10-11 11:32
> 
> 
> Looks like code is incomplete.In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

I have added a small toy code that replicates the error on my system. Thanks for looking into this.

**Comment by ravikyram** [comment] 2019-10-14 11:39
I have tried on colab with TF version 2.0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/265376b981cca3cbf9a56bfb0e9cbd72/untitled267.ipynb).Thanks!

**Comment by goldiegadde** [comment] 2020-03-31 04:32
@agchitu I do not see this issue with 2.2.0-rc2. here is a [colab gist](https://colab.research.google.com/gist/goldiegadde/b7d420eac7eb255b0867dc01ef242710/github-issue-33210.ipynb) of the same, can you please take a look and close if this is resolved ?

**Comment by jvishnuvardhan** [comment] 2020-04-16 16:32
@agchitu This was also resolved in `TF1.15.2`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/9e5b51ae2ce340597321dedb4e8913e0/untitled95.ipynb). 

Please verify once and close the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-05-21 04:22
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-05-21 04:22 UTC
Labels: TF 1.14, TF 1.15, comp:keras, type:bug
