### ISSUE TITLE
Tensorflowlite build error for Raspberry pi

### ISSUE THREAD

**Issue by Kishwar** [tensorflow/tensorflow#28174] opened 2019-04-26 08:38 UTC
I am trying to build Tensorflow Lite using instructions https://www.tensorflow.org/lite/guide/build_rpi but getting following error.

**Describe the problem**
**benchmark_tflite_model.cc:(.text+0x53a0): undefined reference to `tflite::evaluation::CreateGPUDelegate(tflite::FlatBufferModel*)'
benchmark_tflite_model.cc:(.text+0x551e): undefined reference to `tflite::evaluation::CreateNNAPIDelegate()'**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker image **tensorflow/tensorflow:nightly-devel**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Building for Raspberry Pi using Docker
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.0/Latest
- Python version: Python 2.7.15rc1
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): bazel release 0.15.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version:
- GPU model and memory:

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Commands defined on https://www.tensorflow.org/lite/guide/build_rpi

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by petewarden** [comment] 2019-08-02 00:08
Passing over to @aselle as a TF Lite RPi issue.

**Comment by aselle** [comment] 2019-08-07 17:46
I verified that this now works after #26336. It worked for me in the docker container cross compiling approach. I then tested on a raspberry pi 4 and no loader error (undefined reference) occurred.

**Comment by amahendrakar** [comment] 2020-05-06 18:08
@Kishwar,
As per @aselle's comment looks like the issue is fixed. Please feel free to close the issue if resolved. Thanks!

**Closed** 2020-05-20 19:26 UTC
Labels: TF 2.0, comp:lite, stalled, stat:awaiting response, subtype: raspberry pi, type:build/install
