### ISSUE TITLE
slim.conv2d_transpose()

### ISSUE THREAD

**Issue by SophieChang66** [tensorflow/tensorflow#33875] opened 2019-10-31 11:42 UTC
**System information**
- OS Platform and Distribution: arm aarch64 cortex A A54:
- TensorFlow installed from (source or binary):  1.12.0 cross-compiled from source
- TensorFlow version (or github SHA if from source): tensorflow-lite/benchmark_model

**Provide the text output from tflite_convert**
using command 'TOCO' converted model sucessfully, but occur segment fault when run benchmark_model --graph=*.tflite(* is my model name)
```
# Copy and paste here
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by SophieChang66** [comment] 2019-10-31 11:43
sorry, type error, my plantform is cortex A53

**Comment by oanush** [comment] 2019-11-04 09:58
@SophieChang66 ,
Can you please provide a standalone code to reproduce the issue ?Thanks!

**Comment by tensorflowbutler** [comment] 2019-11-19 12:32
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by oanush** [comment] 2019-11-20 08:15
@SophieChang66 ,
Any update on the issue?Thanks!

**Comment by oanush** [comment] 2019-11-25 09:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-11-25 09:37 UTC
Labels: TF 1.12, comp:lite, stat:awaiting response, type:support
