### ISSUE TITLE
pip Install Error: don't could find version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by veniciuss** [tensorflow/tensorflow#47198] opened 2021-02-16 22:37 UTC
------------------------

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Python version**: 3.9.1 64x

I tried to 

```bash
pip install https://github.com/tensorflow/tensorflow/archive/v2.4.1.tar.gz
```
or
```bash
pip install tensorflow
```
on VirtualEnv created via VSCode and I am getting the following errors:

```bash
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
```
or

```bash
Collecting https://github.com/tensorflow/tensorflow/archive/v2.4.1.tar.gz
  Using cached https://github.com/tensorflow/tensorflow/archive/v2.4.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\venic\onedrive\kaggle\fashion_ai\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\venic\\AppData\\Local\\Temp\\pip-req-build-72uc4pr3\\setup.py'"'"'; __file__='"'"'C:\\Users\\venic\\AppData\\Local\\Temp\\pip-req-build-72uc4pr3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\venic\AppData\Local\Temp\pip-pip-egg-info-z0d8x7xg'
    Complete output (5 lines):
      File "C:\Users\venic\AppData\Local\Programs\Python\Python39\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\venic\\AppData\\Local\\Temp\\pip-req-build-72uc4pr3\\setup.py'
    ----------------------------------------
```

Pip version = 21.0.1

**Comment by WindQAQ** [comment] 2021-02-17 00:50
@veniciuss TensorFlow has not supported Python3.9 yet.  See https://github.com/tensorflow/tensorflow/issues/44485. As a workaround, can you try to install Python3.8 or lower version?

**Comment by mihaimaruseac** [comment] 2021-02-17 17:02
Closing as duplicate of #44485

**Closed by mihaimaruseac** 2021-02-17 17:02 UTC
