### ISSUE TITLE
URLError: <urlopen error [Errno 110] Connection timed out> 

### ISSUE THREAD

**Issue by dowhat1995** [tensorflow/tensorflow#8167] opened 2017-03-07 13:19 UTC
When I run program about Deep MINIST for Experts on Jupyter notebook,I met this question.How do I solve it?

**Comment by MicaelCarvalho** [comment] 2017-03-07 14:18
Yann LeCun's website is down, and the dataset is hosted over there. For now, you can only wait for it to come back up, or look for a mirror online.

**Comment by prb12** [comment] 2017-03-07 17:50
Closing as duplicate of #8126

**Closed by prb12** 2017-03-07 17:50 UTC
