### ISSUE TITLE
Can a tensorflow-lite model accept a variable-shaped input?

### ISSUE THREAD

**Issue by datavisornicolacorradi** [tensorflow/tensorflow#33124] opened 2019-10-07 22:18 UTC
When converting a saved frozen graph to tensorflow lite I received the following error: `ValueError: None is only supported in the 1st dimension. Tensor 'input' has invalid shape '[1, None, None]'.`

I'm expecting a variable-sized input that can range from e.g. 10x7 to 100x100, but this seems to be actively prevented in the conversion to tensorflow lite.

It seems to be possible to fix the input size and reshape the graph to accommodate the input (e.g. https://stackoverflow.com/a/55732431) but if I had to do it for every call the overhead would probably kill any gain made by switching to tensorfow lite.

Is there a way around that, or as now this functionality is missing from tf-lite?

I'm using tensorflow 1.14 - I'd be happy to switch to tensorflow 2.0 but at least by looking at the source code it seems to have the same problem.

**Comment by gowthamkpr** [comment] 2019-10-08 19:49
Can you please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/20798) and let me know if it helps. Thanks!

**Comment by datavisornicolacorradi** [comment] 2019-10-08 20:22
If I understand it correctly, the workaround advocates specifying a static input size. 
As the shape of my inputs is variable this would break the network.

[the content of the arrays is categorical, so I wouldn't be able to resize it as if they were images]

**Comment by datavisornicolacorradi** [comment] 2019-10-08 22:20
According to this issue this feature is being developed. 
https://github.com/tensorflow/tensorflow/issues/29590

Is this still the case? [the issue is few months old]
If so we could merge the two threads.

**Comment by gowthamkpr** [comment] 2019-10-17 17:58
Yes. It is being tracked there. And the developers are actively working on it. 

I am going to close this issue as we already have a thread open for this issue and Having multiple threads doesn't help the cause. Thanks!

**Closed by gowthamkpr** 2019-10-17 17:58 UTC
Labels: TF 1.14, comp:lite, type:feature
