### ISSUE TITLE
tf.raw_ops.ImageProjectiveTransformV3 interpolates pixels that are outside image boundary (instead of using `fill_value`)

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#46637] opened 2021-01-24 13:04 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian testing
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
`tf.raw_ops.ImageProjectiveTransformV3` interpolates pixels that are outside image boundary (instead of using fill_value)
In the example below, the corner pixels are mapped from coordinates that lie outside the image. Hence, they must be set to fill_value (like, for example, scipy.ndimage.affine_transform and skimage.transform.AffineTransform). However, they are interpolated instead

**Describe the expected behavior**
Pixels outside image boundaries should be set to `fill_value`. Namely, the corner pixels, in the example below must be zeros.

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa

# Rotate 45 degrees
transform = tfa.image.angles_to_projective_transforms(np.pi/4, 3, 3)

x = tf.ones((1, 3, 3, 1))
res = tf.raw_ops.ImageProjectiveTransformV3(images=x,
                                            transforms=transform,
                                            output_shape=(3,3),
                                            interpolation="BILINEAR",
                                            fill_value=0)
np.squeeze(res)

array([[0.58578646, 1.        , 0.58578634],
       [1.        , 1.        , 1.        ],
       [0.58578646, 1.        , 0.58578634]], dtype=float32)
```

**Comment by amahendrakar** [comment] 2021-01-25 15:11
Running the code with TF v2.3 throws an error stating `AttributeError: module 'tensorflow._api.v2.raw_ops' has no attribute 'ImageProjectiveTransformV3'`

However, I was able to reproduce the issue with TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4be3af55b34eeecf51bfd8f426d4cfcb/46637.ipynb). Thanks!

**Comment by eli-osherovich** [comment] 2021-01-27 09:24
Tensorflow 2.3 and 2.4 have `ImageProjectiveTransformV2` which also must set pixels outside the image to zeros. The bug is present there as well

**Comment by eli-osherovich** [comment] 2021-01-28 07:40
Submitted a PR that fixes it: #46752

**Comment by saikumarchalla** [comment] 2021-05-29 03:46
@eli-osherovich  The PR you have submitted  was closed already. Please check PR for detailed information and seems the changes cannot be implemented due to several reasons as mentioned in PR. 

Please go ahead and close the issue if you don't have any concern.Thanks!

**Closed** 2021-05-30 15:41 UTC
Labels: TF 2.4, comp:ops, stat:awaiting response, stat:awaiting tensorflower, type:bug

**Comment by sauravsolanki** [comment] 2021-10-05 08:39
Warning says it all.
```
>>> import tensorflow_addons as tfa
The versions of TensorFlow you are currently using is 2.3.1 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 

```
