### ISSUE TITLE
unable to build tensorflow for GPU

### ISSUE THREAD

**Issue by abidmalik1967** [tensorflow/tensorflow#4926] opened 2016-10-12 22:11 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
..
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/ammalik/TensorFlow/tensorflow/util/python/BUILD:11:16: in includes attribute of cc_library rule //util/python:python_headers: 'python_include' resolves to 'util/python/python_include' not in 'third_party'. This will be an error in the future.
INFO: Found 1 target...
ERROR: /home/ammalik/.cache/bazel/_bazel_ammalik/27908a9a0ff0347c2aebe63a8fa99002/external/zlib_archive/BUILD:7:1: undeclared inclusion(s) in rule '@zlib_archive//:zlib':
this rule is missing dependency declarations for the following files included by 'external/zlib_archive/zlib-1.2.8/compress.c':
  '/opt/local/gcc/6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include-fixed/limits.h'
  '/opt/local/gcc/6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include-fixed/syslimits.h'
  '/opt/local/gcc/6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stddef.h'
  '/opt/local/gcc/6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stdarg.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 962.954s, Critical Path: 0.69s

**Comment by MatthiasWinkelmann** [comment] 2016-10-12 22:39
You'll get more sympathy if you actual use the template instead of just quoting it, but I believe your problem is related to/helped by https://github.com/tensorflow/tensorflow/issues/3431#issuecomment-234131699. 

It that doesn't work: your gcc is a custom install, right? You'll probably have it easier using your distributions standard builchain.

**Comment by jart** [comment] 2016-10-13 01:37
Are you using CUDA 8.0? Right now we only support 7.0 - 7.5. But we're actively working on supporting 8.0. See #2559. 

@davidzchen is it possible setting the CUDA toolchain is what caused the "undeclared inclusion" error with zlib? Possible duplicate of #2109.

**Comment by gunan** [comment] 2016-10-13 03:48
When building natively, I can build using cuda8 without any problems.
But this issue report is missing too much information.

Is it possible reporter is missing either the prerequisites:
$ sudo apt-get install python-numpy swig python-dev python-wheel

Or forgot running ./configure before building?

**Comment by asimshankar** [comment] 2016-10-24 04:42
Closing due to inactivity. Feel free to reopen if this is still an issue (and please add more information as requested in the comments above).

**Closed by asimshankar** 2016-10-24 04:42 UTC
Labels: awaiting googler, awaiting response
