### ISSUE TITLE
Colab notebook crashes due to RAM overuse on "Explore overfitting and underfitting" tutorial

### ISSUE THREAD

**Issue by iboates** [tensorflow/tensorflow#30261] opened 2019-06-30 19:03 UTC
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/overfit_and_underfit.ipynb#scrollTo=LqG3MXF5xSjR

## Description of issue (what needs changing):

Notebook crashes on the code block training the baseline model, reporting that all RAM has been consumed.

### Clear description

Users should be able to complete the entire notebook without hitting resource limits

Maybe the model is not defined correctly? This is the summary:

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                (None, 16)                160016    
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
=================================================================
Total params: 160,305
Trainable params: 160,305
Non-trainable params: 0
```

**Comment by lamberta** [comment] 2019-07-01 17:52
Confirmed.

Log:
```
Jul 1, 2019, 10:50:28 AM | WARNING | WARNING:root:kernel 69b47c82-98ca-47b8-b06e-c237cf4a1dfd restarted
Jul 1, 2019, 10:50:28 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jul 1, 2019, 10:50:18 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x1f896c000 @ 0x7f2229ef7887 0x7f22287edbf9 0x7f22287eeacb 0x7f22287eeb84 0x7f22287eef6c 0x7f21fa8c9d79 0x7f21fa9591be 0x7f21fa8f16f7 0x7f21fa8f228c 0x7f21fa8b0ffa 0x7f21fa8b117a 0x7f21fd6d1dce 0x7f21fd4a46e2 0x4f858d 0x4f98c7 0x4f7a28 0x4f876d 0x4f98c7 0x4f6128 0x4f426e 0x5a1481 0x512a60 0x53ee21 0x57ec0c 0x4f88ba 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128
Jul 1, 2019, 10:50:17 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x109a16000 @ 0x7f2229ef51e7 0x5a1c5c 0x7f2208dba650 0x4f8925 0x4f98c7 0x4f7a28 0x4f876d 0x4f98c7 0x4f6128 0x4f426e 0x5a1481 0x512a60 0x53ee21 0x57ec0c 0x4f88ba 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x56ff4c 0x57c2fe 0x4facb1 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d
Jul 1, 2019, 10:50:16 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x181612000 @ 0x7f2229ef7887 0x7f22287edbf9 0x7f22287edd17 0x7f22287ef775 0x7f2208dba181 0x7f2208dbaeca 0x7f2208dbc9e6 0x7f2208dbcc2a 0x53b410 0x53bb7b 0x4f9dc1 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0
Jul 1, 2019, 10:50:14 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x109a16000 @ 0x7f2229ef51e7 0x5a1c5c 0x7f2222013df7 0x4f8925 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60
Jul 1, 2019, 10:50:12 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x926bc000 @ 0x7f2229ef7001 0x7f2221f1fde5 0x7f2221f846f1 0x7f2221f867cf 0x7f222201f158 0x4f8925 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x517a9a 0x4f858d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f426e 0x5a1481 0x57c2fe 0x4facb1 0x4f6128 0x4f7d60 0x4f876d
Jul 1, 2019, 10:50:10 AM | WARNING | tcmalloc: large alloc 2000003072 bytes == 0x1b362000 @ 0x7f2229ef7001 0x7f2221f1fde5 0x7f2221f846f1 0x7f2221f867cf 0x7f222201f158 0x4f8925 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x517a9a 0x4f858d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4fa6c0 0x4f6128 0x4f426e 0x5a1481 0x57c2fe 0x4facb1 0x4f6128 0x4f7d60 0x4f876d
Jul 1, 2019, 10:49:41 AM | INFO | Adapting to protocol v5.1 for kernel 69b47c82-98ca-47b8-b06e-c237cf4a1dfd
Jul 1, 2019, 10:49:40 AM | INFO | Kernel started: 69b47c82-98ca-47b8-b06e-c237cf4a1dfd
```

**Comment by lamberta** [comment] 2019-07-01 17:55
cc: @craigcitro

**Comment by craigcitro** [comment] 2019-07-01 19:38
+cc @colaboratory-team for visibility

The logs in https://github.com/tensorflow/tensorflow/issues/30261#issuecomment-507362714 do seem to confirm that the notebook is requesting more RAM than the VM has available; I don't think there's anything we can do from the colab side unless it doesn't use that much RAM outside of colab.

**Comment by lamberta** [comment] 2019-07-01 20:12
Oookaay ...
Turns out this notebook is set to install `tf-nightly`,  switching to stable (1.14) resolves this issue.
But this may have caught a bug in nightly.

**Comment by lamberta** [comment] 2019-07-02 00:20
Fixed by switching back from nightly to stable in https://github.com/tensorflow/docs/pull/730
cc @fchollet

**Closed by lamberta** 2019-07-02 00:20 UTC
Labels: comp:keras, type:docs

**Comment by martinwicke** [comment] 2019-07-02 03:01
We do need to look into what broke it in nightly.
