### ISSUE TITLE
Can't install Tensorflow 1.14.0 

### ISSUE THREAD

**Issue by ZH-Lee** [tensorflow/tensorflow#28785] opened 2019-05-17 01:23 UTC
When i import tensorflow_model_optimization as tfmot like document, i got error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lees/Library/Python/3.6/lib/python/site-packages/tensorflow_model_optimization/__init__.py", line 69, in <module>
    _ensure_tf_install()
  File "/Users/lees/Library/Python/3.6/lib/python/site-packages/tensorflow_model_optimization/__init__.py", line 66, in _ensure_tf_install
    required=required_tensorflow_version, present=tf.__version__))
ImportError: This version of TensorFlow Model Optimization requires TensorFlow version >= 1.14.0; Detected an installation of version 1.13.1. Please upgrade TensorFlow to proceed.`

But I can't upgrade tensorflow to 1.14.0, even cannot find Tensorflow 1.14.0 by pip3 install --upgrade tensorflow==1.14.0.
So, is it a bug?

**Comment by fsx950223** [comment] 2019-05-17 01:57
You should install tensorflow nightly

**Comment by ZH-Lee** [comment] 2019-05-17 03:48
> tensorflow nightly

Thanks. But when training the network, i got lots of warnings, some syntax are different from tensorflow 1.13. Should i change that or ignore the warnings?

**Comment by muddham** [comment] 2019-05-20 08:53
@ZH-Lee Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by muddham** [comment] 2019-05-27 08:50
@ZH-Lee Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-27 08:50 UTC
Labels: type:build/install

**Comment by Roshanson** [comment] 2019-06-25 09:55
you can degrade the  TensorFlow Probability .   
In my case , set the version of TensorFlow Probability  from 0.7.0 to 0.6.0

tensor2tensor            1.13.4  
tensorboard              1.13.1  
tensorflow-datasets      1.0.2   
tensorflow-estimator     1.13.0  
tensorflow-gpu           1.13.1  
tensorflow-metadata      0.13.0  
tensorflow-probability   ~~0.7.0~~ 0.6.0

**Comment by Rubix982** [comment] 2020-04-10 06:54
Date April 10th, 2020, at commit 05ad339414ba7c95260bc71ecf79734a2c5e9d84 , issue is still unresolved. Can be reproduced by
`pip install tensorflow==1.14.0`

Either,
- Include tensorflow_model_optimization in tensorflow 1.13.1
- Or change and edit the documentation for the 
```
File "/Users/lees/Library/Python/3.6/lib/python/site-packages/tensorflow_model_optimization/__init__.py", line 66, in _ensure_tf_install required=required_tensorflow_version, present=tf.__version__)
```
