### ISSUE TITLE
Error building tensorflow.dll (Windows 10)

### ISSUE THREAD

**Issue by Lotte1990** [tensorflow/tensorflow#42730] opened 2020-08-28 09:53 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version: 2.3.0
- Bazel version (if compiling from source): 3.1.0

**Describe the problem**
Error building tensorflow.dll
```
ERROR: C:/users/lotte/downloads/tensorflow-2.3.0/tensorflow/BUILD:663:1: Linking of rule '//tensorflow:tensorflow_framework.dll' failed (Exit 1127): link.exe failed: error executing command
  cd C:/users/lotte/_bazel_lotte/6a53jthk/execroot/org_tensorflow
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/lotte/AppData/Local/Programs/Python/Python38/python.exe
    SET PYTHON_LIB_PATH=C:/Users/lotte/AppData/Local/Programs/Python/Python38/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\lotte\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TF_ENABLE_XLA=1
    SET TMP=C:\Users\lotte\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/HostX64/x64/link.exe @bazel-out/x64_windows-opt/bin/tensorflow/tensorflow_framework.dll-2.params
Execution platform: @local_execution_config_platform//:platform
external\mkl_windows\lib\libiomp5md.lib : fatal error LNK1127: library is corrupt
Target //tensorflow/tools/lib_package:libtensorflow failed to build
INFO: Elapsed time: 9542.848s, Critical Path: 619.14s
INFO: 8184 processes: 8184 local.
FAILED: Build did NOT complete successfully
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
python configure.py
    empty
    empty
    n
    n
    empty
    y
    n

bazel build -c opt --config=mkl //tensorflow/tools/lib_package:libtensorflow
```

**Edit: Possibly related to #42703 (Error building tensorflow_cc.dll)**

**Comment by Saduf2019** [comment] 2020-08-28 10:09
@Lotte1990 
This issue reported is duplicate of #42703 and it is tracked there, please move this to closed status as its tracked already.

**Comment by Lotte1990** [comment] 2020-08-28 10:12
This is not a duplicate issue. This issue concerns tensorflow.dll (C API) and #42703 concerns tensorflow_cc.dll (C++ API). Please keep both issues open until resolved. Thanks!

**Comment by gunan** [comment] 2020-08-28 17:15
Definitely the same issue as #42703 it is the exact same library (mkl) failing to link.
Possibly mkl build is not configured to run on windows. Closing as duplicate.

**Closed by gunan** 2020-08-28 17:15 UTC
Labels: TF 2.3, stat:awaiting tensorflower, subtype:windows, type:build/install
