### ISSUE TITLE
tf.gather's gradient fails on GPU in eager mode

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#18477] opened 2018-04-13 00:26 UTC
Tested with TensorFlow v1.7.0 on Ubuntu 16.06.

Consider the following contrived example:
```python
import tensorflow as tf
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

with tf.device('/gpu:0'):
    with tfe.GradientTape() as tape:
        params = tfe.Variable(tf.zeros((1024,)))
        indices = tf.constant(range(5))
        output = tf.reduce_sum(tf.gather(params, indices))
    print(tape.gradient(output, [params]))
```

When executed, it fails with:

```
Tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensors on conflicting devices: cannot compute Cast as input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0) Tensors can be copied explicitly using .gpu() or .cpu(), or transparently copied by using tfe.enable_eager_execution(tfe.DEVICE_PLACEMENT_SILENT). Copying tensors between devices may slow down your model [Op:Cast] name: ToInt32
```

This does not occur on the CPU.

The issue can be fixed by removing the `to_int32` call and just changing the `out_types` to `int32` here in [array_grad.py](https://github.com/tensorflow/tensorflow/blob/v1.7.0/tensorflow/python/ops/array_grad.py#L398-L399) as follows:
```python
params_shape = array_ops.shape(params, out_type=ops.dtypes.int32) # int64 -> int32
# params_shape = math_ops.to_int32(params_shape) [remove this line]
```

**Comment by tensorflowbutler** [comment] 2018-04-13 12:32
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment] 2018-04-13 23:54
The root cause of this is that as of TensorFlow 1.7, by default we do not silently copy tensors between devices and since most operations on int32 tensors require the tensor to be placed on CPU, you get the error.

As the error message suggests, in TensorFlow 1.7 you can work around this by using:

```python
tf.enable_eager_execution(device_policy=tf.contrib.eager.DEVICE_PLACEMENT_SILENT)
```

With TensorFlow 1.8 we've done a bit more to make behavior in eager and graph more aligned - so you won't need the `with tf.device('/gpu:0')` block since GPUs will be used where available and tensors silently copied if needed by default. 

Thus, for 1.7, try a different `device_policy` when enabling eager execution and with 1.8 the issue you described will go away.

Hope that helps.

Some additional details for the record:
- This silent copying could become a bottleneck in model performance, so you can revert to `tf.contrib.eager.DEVICE_PLACEMENT_EXPLICIT` to help identify the points at which copying happens.
- The behavior between graph and eager when it comes to placement of operations won't always be _exactly_ the same as with graph execution the runtime has the benefit of seeing the complete computation to make more informed placement decisions, while with eager execution placement decisions have to be made greedily.

Closing this out since the behavior is intentional, there is a workaround for 1.7, and this problem won't occur in 1.8. Please re-open if I've misunderstood. Thanks.

**Closed by asimshankar** 2018-04-13 23:54 UTC
Labels: stat:awaiting response

**Comment by ethereon** [comment] 2018-04-14 00:49
It seems undesirable that this gradient operation will incur a cross device copy overhead when it seems avoidable (at least on non-Windows targets, based on my understanding of the comment above the cast to int32)

**Comment by asimshankar** [comment] 2018-04-14 01:44
Yes, it certainly is. 

The Windows specific-ness of that is questionable See https://github.com/tensorflow/tensorflow/pull/9780#issuecomment-323547672.

Though in practice this hasn't been a concern that has shown up much over the past year and hence resolving that hasn't been bumped up the priority list. If you do have some reason to believe that the int32 casting and the resulting copies is indeed causing trouble, please do file a bug with the details.

(Keeping this particular one closed since this concern about int32 casting and copies isn't specific to the original description of the issue)

Hope that makes sense. Thanks.
