### ISSUE TITLE
Tflite.tensorflow  Cannot convert a Tensor of dtype resource to a NumPy array. after multi mirrored strategy training

### ISSUE THREAD

**Issue by uidchet** [tensorflow/tensorflow#39918] opened 2020-05-27 18:20 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): Tnsorflow 2.2-gpu docker
- TensorFlow version (or github SHA if from source): tensorflow/tensorflow:2.2.0-gpu

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
https://github.com/uidchet/tflite-issue

```

**The output from the converter invocation**

  ```
  File "tflite.py", line 22, in convert_model
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 459, in convert
    self._funcs[0], lower_control_flow=False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 706, in convert_variables_to_constants_v2_as_graph
    func, lower_control_flow, aggressive_inlining)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 457, in _convert_variables_to_constants_v2_impl
    tensor_data = _get_tensor_data(func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 217, in _get_tensor_data
    data = val_tensor.numpy()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 961, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 929, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.

```

**Also, please include a link to the saved model or GraphDef**

```
https://github.com/uidchet/tflite-issue/blob/master/sav_model.zip
```

**Comment by amahendrakar** [comment] 2020-05-28 11:13
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/3cc83d1f8f00b85b6d707ab67e41e038/39918.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/eca8e32076002fb5c907e6cededf0de9/39918-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by ethanyanjiali** [comment] 2020-06-13 19:30
Seeing a same error, i doubt it's about type mismatch because when I load the SavedModel into TFServing, it worked well. So it should be something specific to TFLiteConverter

**Comment by ethanyanjiali** [comment] 2020-06-13 19:32
@jvishnuvardhan i think @uidchet has already provided a SaveModel for you, most likely you just need to run the converter over it.

**Comment by haozha111** [comment] 2020-06-15 21:46
Assigning to @karimnosseir since this is related with tflite converter.

**Comment by uidchet** [comment] 2020-06-26 05:28
Any work around for this?

**Comment by uidchet** [comment] 2020-06-26 19:52
well reloading the saved model and the saving it again works...

**Comment by jvishnuvardhan** [comment] 2020-08-03 07:16
@uidchet Is this still an issue? I ran the gist @amahendrakar  without any issue. May be this was resolved in recent `tf-nightly`. Please verify the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/7d0dd3e7a2b5f5a4bd5d89d03f75fc46/39918-tf-nightly.ipynb). Thanks!

**Closed** 2020-08-17 07:27 UTC
Labels: TF 2.2, TFLiteConverter, comp:lite, stalled, stat:awaiting response, type:support
