### ISSUE TITLE
Tensorflow 1.14 GPU hanging when running models

### ISSUE THREAD

**Issue by MayhemGang** [tensorflow/tensorflow#34333] opened 2019-11-16 05:29 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: yes, I have coded an AEGAN that used to work but no longer.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Conda install tensorflow-gpu==1.14.0
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:Installed by Anaconda, unknown
- GPU model and memory: Geforce GTX 1070 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

N/A, issue is described exactly by this stackoverflow question:
https://stackoverflow.com/questions/47272869/tensorflow-stops-training-and-hanged-on-gpu-randomly/58887825#58887825

**Comment by MayhemGang** [comment] 2019-11-16 05:44
Note: I made sure the select feature of the command prompt isn't it, and this is definitely a bios/other issue. Any ideas?

**Comment by oanush** [comment] 2019-11-18 08:26
@MayhemGang ,
Thanks for reporting the issue, Can you share a standalone code to reproduce the error reported here?Thanks!

**Comment by oanush** [comment] 2019-11-29 06:04
@MayhemGang ,
Any update on the issue?thanks!

**Comment by oanush** [comment] 2019-12-06 08:48
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-12-06 08:48 UTC
Labels: TF 1.14, comp:gpu, type:support
