### ISSUE TITLE
[TF 2.0] TPU Estimator cannot function without steps or max_steps

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/tensorflow#30148] opened 2019-06-25 19:42 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): No
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): tensorflow==2.0.0b0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
- TPU: v2.8, TF Nightly.
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TPU Estimator Cannot function without steps or max_steps.
When provided, Any value of `max_steps` raises an `IteratorGetNext: End of Sequence Error`. However this error gets handled, and TPU Session Remains active even when there's no more code to execute.
**Describe the expected behavior**
TPU Estimator should run without `steps` or `max_steps` as mentioned in the documentation. It should stop the training process as soon as `tf.errors.OutOfRangeError` Rises.
**More Information (along with Code to Reproduce)**
Related Issue: https://github.com/captain-pool/GSOC/issues/12
Code: https://github.com/captain-pool/GSOC/blob/e7145c8d6c43545c4bcbde3cdd47f7cc53b1490c/E1_TPU_Sample/image_retraining_tpu.py

CC: @vbardiovskyg @srjoglekar246

**Comment by gadagashwini** [comment] 2019-06-26 10:31
@captain-pool I am unable to reproduce the issue on colab with Tensorflow 2.0.0.beta0. Please help us to reproduce the issue. When i ran it throws ```
FATAL Flags parsing error: Unknown command line flag 'f'
Pass --helpshort or --helpfull to see help on flags.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
``` Thanks!

**Comment by captain-pool** [comment] 2019-06-26 11:04
> @captain-pool I am unable to reproduce the issue on colab with Tensorflow 2.0.0.beta0. Please help us to reproduce the issue. When i ran it throws ```
> FATAL Flags parsing error: Unknown command line flag 'f'
> Pass --helpshort or --helpfull to see help on flags.
> An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit: 1

Hey @gadagashwini There's no `f` flag defined anywhere in the code I gave. Try copy/pasting this and try out.
```python3 image_retraining_tpu.py --tpu [TPU_NAME] \
--use_tpu --use_compat --data_dir gs://[BUCKET_NAME]/data_dir \
--model_dir gs://[BUCKET_NAME]/model_dir --batch_size=32 \
--iterations=8 --max_steps=8
```
I'm not sure about colab, I've been trying this on gcloud. So, it would be better if you can try out on a VM instance.

**Comment by jvishnuvardhan** [comment] 2019-10-02 22:38
@captain-pool Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-17 00:10
@captain-pool Is this still an issue? If not, please close this issue. Thanks!

**Closed** 2019-10-19 12:45 UTC
Labels: TF 2.0, comp:tpus, stat:awaiting response, type:bug
