### ISSUE TITLE
Object detection ppn tflite works wrong on mobile

### ISSUE THREAD

**Issue by holyhao** [tensorflow/tensorflow#25746] opened 2019-02-14 07:10 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: HUAWEI MATE20
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.10
- Python version:3.6
- Bazel version (if compiling from source):1.15
- GCC/Compiler version (if compiling from source):1.9
- CUDA/cuDNN version:8.0
- GPU model and memory:16GB

I used  object detection API, the ssd_mobilenetV2 is working well including the train, eval ,inference on pc ,and .tflite on phone.
Recently, i try ppn_mobilenetv1, the train and eval is well. The frozen_inference_graph.pb also work well on pc and the results are right. When i convert it to tflite_graph.pb, then convert it to detect.tflite. No errors occur. But when it runs on the mobile, it shows totally wrong results. I can not find anything wrong here. Could anyone please help me find it out?

**Comment by jvishnuvardhan** [comment] 2019-02-14 21:40
@holyhao Could you provide any code to reproduce the bug? or could you provide more detailed steps/commands you followed? Thanks!

**Comment by holyhao** [comment] 2019-02-15 01:35
@jvishnuvardhan hi，thanks for your reply, to reproduce the bug：
1.Download the ppn_mobilnetV1 http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03.tar.gz
2.Conver it to tflite, no errors occur
`CONFIG_PATH=../pipeline.config
CHECKPOINT_PATH=../model.ckpt
OUTPUT_DIR=../results/	
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path $CONFIG_PATH \
--trained_checkpoint_prefix $CHECKPOINT_PATH \
--output_directory $OUTPUT_DIR \
--add_postprocessing_op=true
bazel-bin/tensorflow/contrib/lite/toco/toco \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=FLOAT \
--allow_custom_ops`
3. Run it on mobile, i use the tensorflow-lite from tensoflow 1.10

As I mentioned above, ssd_mobilenetV2 works well from the framework. The frozen_inference_graph.pb of ppn_mobilenetv1 works well on pc. But when the ppn_mobilenetv1  runs on the mobile, it shows totally wrong results. Looking forward to your help.

**Comment by jdduke** [comment] 2019-07-12 19:24
Hi @holyhao, are you still experiencing a problem with the model? Thanks.

**Comment by tensorflowbutler** [comment] 2019-07-27 12:23
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-07-29 13:54
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-07-29 13:54 UTC
Labels: comp:lite, stat:awaiting response, type:bug
