### ISSUE TITLE
how to get  “tf. fake_quant_with_min_max_args”  by  API  "tf.keras"

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#22880] opened 2018-10-11 02:32 UTC
I want to quantize a h5 model, but i can't find “tf. fake_quant_with_min_max_args”  by   API tf.keras

**Comment by tensorflowbutler** [comment] 2018-10-11 12:35
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-12 00:09
Duplicate of #22881

**Closed by ymodak** 2018-10-12 00:09 UTC
Labels: stat:awaiting response
