### ISSUE TITLE
Combining multiple SavedModels into one SavedModel

### ISSUE THREAD

**Issue by yaswitag1** [tensorflow/tensorflow#40535] opened 2020-06-17 07:32 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I was able to combine multiple tf estimator savedmodels (linear classifiers) into one and then serve that final model instead of serving multiple models. But when it comes to boosted trees, i am experiencing an the following error :

NotFoundError:  Resource localhost/boosted_trees/QuantileAccumulator/_load_2153_load_11463/N10tensorflow34BoostedTreesQuantileStreamResourceE does not exist.
	 [[node import/boosted_trees/BoostedTreesQuantileStreamResourceGetBucketBoundaries_1 (defined at <ipython-input-136-92a81f76cf4e>:2) ]] [Op:__inference_pruned_12525]

Function call stack:
pruned
**Will this change the current api? How?**

**Who will benefit with this feature?**
Serving on port gives enables easier maintenance 
**Any Other info.**

**Comment by amahendrakar** [comment] 2020-06-17 15:35
@yaswitag1,
Looks like this is a duplicate of [#40536](https://github.com/tensorflow/tensorflow/issues/40536). Can you please close this issue since it is already being tracked there. Thanks!

**Closed** 2020-06-18 03:54 UTC
Labels: comp:apis, stat:awaiting response, type:feature
