### ISSUE TITLE
arm-none-eabi-g++: error: tensorflow/lite/experimental/micro/tools/make/downloads/gcc_embedded//lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard/crtbegin.o: No such file or directory tensorflow/lite/experimental/micro/examples/micro_speech/Makefile.inc:372: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech' failed make: *** [tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech] Error 1

### ISSUE THREAD

**Issue by saptechengineer** [tensorflow/tensorflow#30060] opened 2019-06-23 18:27 UTC
arm-none-eabi-g++: error: tensorflow/lite/experimental/micro/tools/make/downloads/gcc_embedded//lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard/crtbegin.o: No such file or directory
tensorflow/lite/experimental/micro/examples/micro_speech/Makefile.inc:372: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech] Error 1

**Comment by saptechengineer** [comment] 2019-06-23 18:28
arm-none-eabi-g++: error: tensorflow/lite/experimental/micro/tools/make/downloads/gcc_embedded//lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard/crtbegin.o: No such file or directory
tensorflow/lite/experimental/micro/examples/micro_speech/Makefile.inc:372: recipe for target 'tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech' failed
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech] Error 1

**Comment by achandraa** [comment] 2019-06-24 07:51
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by wangtz** [comment] 2019-06-26 08:36
Hi Saptech,

Could you provide a list of steps int order to reproduce this issue? It looks like the download didn't compete. Could you delete tensorflow/lite/experimental/micro/tools/make/downloads folder and try again?

Thanks,

**Comment by gadagashwini** [comment] 2019-07-04 11:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-04 11:13 UTC
Labels: comp:lite, stat:awaiting response, type:support
