### ISSUE TITLE
Problem with callbacks and LSTM : is failing

### ISSUE THREAD

**Issue by u650080** [tensorflow/tensorflow#20531] opened 2018-07-03 20:10 UTC
I try to use callbacks and it is failing with following example, if I use GRU with callbacks is ok but with LSTM is failing:

This is system info :

== cat /etc/issue ===============================================
Linux gpuMachine 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.4 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux strategy.ca.alcatel-lucent.com 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                             1.14.5   
protobuf                          3.6.0    
tensorflow                        1.8.0    
tensorflow-gpu                    1.8.0    

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-9.0/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Jul  3 16:05:54 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:02:00.0  On |                  N/A |
|  0%   43C    P2    41W / 180W |   1141MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     28189      C   ...user1/.conda/envs/tensorflow/bin/python  1007MiB |
|    0     28294      G   /usr/lib/xorg/Xorg                           122MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.0/lib64/libcudart_static.a
/usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
/usr/local/cuda-9.0/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7

with this example I have problem:
```
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from keras.callbacks import TensorBoard
import numpy as np
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.1
session = tf.Session(config=config)
path_checkpoint = 'test.keras'
SEQUENCES = 5
TIME_STEPS = 10

model = Sequential()
model.add(Embedding(100, 4))
model.add(LSTM(32))
model.add(Dense(1))
model.compile(optimizer='rmsprop', loss='mse')

tensor_board = TensorBoard(log_dir='log', batch_size=2, write_graph=False,
write_grads=True, histogram_freq=4)
callback_early_stopping = EarlyStopping(monitor='val_loss',
patience=2, verbose=2)
callback_checkpoint = ModelCheckpoint(filepath=path_checkpoint,
monitor='val_loss',
verbose=2,
save_weights_only=True,
save_best_only=True)
callback_reduce_lr = ReduceLROnPlateau(monitor='val_loss',
factor=0.1,
min_lr=1e-4,
patience=0,
verbose=2)
x_train = np.random.randint(100, size=(SEQUENCES, TIME_STEPS), dtype='int8')

y_train = np.random.rand(SEQUENCES)

model.fit(x_train, y_train, batch_size=2, epochs=4, shuffle=True, callbacks=[callback_reduce_lr,tensor_board,callback_early_stopping,callback_checkpoint])
```
and I got this :+1: 
Error +1
Epoch 1/4

FailedPreconditionError Traceback (most recent call last)
in ()
36 y_train = np.random.rand(SEQUENCES)
37
---> 38 model.fit(x_train, y_train, batch_size=2, epochs=4, shuffle=True, callbacks=[callback_reduce_lr,tensor_board,callback_early_stopping,callback_checkpoint])

~/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
1040 initial_epoch=initial_epoch,
1041 steps_per_epoch=steps_per_epoch,
-> 1042 validation_steps=validation_steps)
1043
1044 def evaluate(self, x=None, y=None,

~/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
197 ins_batch[i] = ins_batch[i].toarray()
198
--> 199 outs = f(ins_batch)
200 if not isinstance(outs, list):
201 outs = [outs]

~/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in call(self, inputs)
2659 return self._legacy_call(inputs)
2660
-> 2661 return self._call(inputs)
2662 else:
2663 if py_any(is_tensor(x) for x in inputs):

~/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
2629 symbol_vals,
2630 session)
-> 2631 fetched = self._callable_fn(*array_vals)
2632 return fetched[:len(self.outputs)]
2633

~/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py in call(self, *args)
1452 else:
1453 return tf_session.TF_DeprecatedSessionRunCallable(
-> 1454 self._session._session, self._handle, args, status, None)
1455
1456 def del(self):

~/.conda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in exit(self, type_arg, value_arg, traceback_arg)
517 None, None,
518 compat.as_text(c_api.TF_Message(self.status.status)),
--> 519 c_api.TF_GetCode(self.status.status))
520 # Delete the underlying status object from memory otherwise it stays alive
521 # as there is a reference to status from this from the traceback due to

FailedPreconditionError: Attempting to use uninitialized value RMSprop_16/lr
[[Node: RMSprop_16/lr/read = IdentityT=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]
[[Node: loss_16/mul/_621 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1571_loss_16/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

**Comment by tensorflowbutler** [comment] 2018-07-04 06:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by u650080** [comment] 2018-07-04 13:14
I put output from tools which was in template:
Have I written custom code : none
OS Platform Ubuntu: "16.04.4 LTS (Xenial Xerus)"
Tensorflow : 1.8.0 GIT VERSION = v1.8.0-0-g93bc2e2072
TensorFlow installed from : anaconda3
Bazel version: none
CUDA/cuDNN version : cuda_9.0.176_384.81 and cuDNN : 7.1.4.18+cuda9.0
GPU model and memory: GPU
Exact command to reproduce:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from keras.callbacks import TensorBoard
import numpy as np
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.1
session = tf.Session(config=config)
path_checkpoint = 'test.keras'
SEQUENCES = 5
TIME_STEPS = 10

model = Sequential()
model.add(Embedding(100, 4))
model.add(LSTM(32))
model.add(Dense(1))
model.compile(optimizer='rmsprop', loss='mse')

tensor_board = TensorBoard(log_dir='log', batch_size=2, write_graph=False,
write_grads=True, histogram_freq=4)
callback_early_stopping = EarlyStopping(monitor='val_loss',
patience=2, verbose=2)
callback_checkpoint = ModelCheckpoint(filepath=path_checkpoint,
monitor='val_loss',
verbose=2,
save_weights_only=True,
save_best_only=True)
callback_reduce_lr = ReduceLROnPlateau(monitor='val_loss',
factor=0.1,
min_lr=1e-4,
patience=0,
verbose=2)
x_train = np.random.randint(100, size=(SEQUENCES, TIME_STEPS), dtype='int8')

y_train = np.random.rand(SEQUENCES)

model.fit(x_train, y_train, batch_size=2, epochs=4, shuffle=True, callbacks=[callback_reduce_lr,tensor_board,callback_early_stopping,callback_checkpoint])

**Comment by reedwm** [comment] 2018-07-09 18:11
Can you create a minimal example that reproduces the problem? I see you have four callbacks, but can you reproduce with only one callback, or even zero callbacks? It's easier to debug issues if the examples are as small and simple as possible.

Also, it's easier to read the post if you put source code in [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/). I edited your original post to use a code block.

**Comment by u650080** [comment] 2018-07-23 17:20
there is no problem with no callbacks : even with one callback:
 ```
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from keras.callbacks import TensorBoard
import numpy as np
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.1
session = tf.Session(config=config)
path_checkpoint = 'test.keras'
SEQUENCES = 5
TIME_STEPS = 10

model = Sequential()
model.add(Embedding(100, 4))
model.add(LSTM(32))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')


callback_reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                                       factor=0.1,
                                       min_lr=1e-4,
                                       patience=0,
                                       verbose=2)
x_train = np.random.randint(100, size=(SEQUENCES, TIME_STEPS), dtype='int8')

y_train = np.random.rand(SEQUENCES)

model.fit(x_train, y_train, batch_size=2, epochs=4, shuffle=True, callbacks=[callback_reduce_lr])

 ```

**Comment by reedwm** [comment] 2018-07-24 22:21
This works if you either use just `tensorflow.python.keras` or `keras` in your imports, but in your current code, you mix them. Try changing 
```
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
``` 
to

```
from keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
```
/CC @fchollet, is mixing `tf.keras` and `keras` supposed to work? If not, perhaps we should detect that case and throw an error.

**Comment by u650080** [comment] 2018-07-25 13:10
thanks a lot .

**Comment by reedwm** [comment] 2018-08-08 17:41
Closing this since the original issue has been solved.

**Closed by reedwm** 2018-08-08 17:41 UTC
