### ISSUE TITLE
tensorflow lite tests on x86

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#26092] opened 2019-02-25 14:41 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit a2bb5db1bf7931b0dc2cd08e53b8798489568198
- Python version: 2.7.15rc1
- Installed using virtualenv? pip? conda?: sources
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Tensorflow lite tests seem to require android sdk even though we wanted to test them on x86.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test --local_resources 40000,23,2 -- //tensorflow/lite/...
**Any other info / logs**
ERROR: /home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/external/bazel_tools/tools/android/BUILD:391:1: Executing genrule @bazel_tools//tools/android:no_android_sdk_repository_error faile
d (Exit 1)                                                                                      
This build requires an Android SDK. Please add the android_sdk_repository rule to your WORKSPACE.

**Comment by jdduke** [comment] 2019-03-06 17:08
We probably need to mark a few targets with the "manual" tag to allow this kind of glob-based testing for x86.

**Comment by herbakamil** [comment] 2019-03-14 12:08
@jdduke do you have some suggestions what quick fix I can do so that I have working CI which can run tf lite tests? I've came to the command below which disables tests in tflite which don't work on the standard non-google environment (so that all tests pass) but bazel still fails because of the error mentioned above

bazel test --test_tag_filters=-no_oss,-gpu,-benchmark-test --test_lang_filters=cc,java -k \
    --jobs=${N_JOBS} --test_timeout 300,450,1200,3600 --config=opt \
    --test_output=errors --test_size_filters=small,medium -- \
    //tensorflow/lite/... \
    -//tensorflow/lite/kernels/internal/... \
    -//tensorflow/lite/kernels:resize_bilinear_test \
    -//tensorflow/lite/kernels:resize_nearest_neighbor_test \
    -//tensorflow/lite/testing/...

**Comment by jdduke** [comment] 2019-03-14 19:46
Does excluding //tensorflow/lite/java/... work?

**Comment by herbakamil** [comment] 2019-03-15 10:24
@jdduke It works. Thank you very much for your help :)

It's good that [documentation](https://www.tensorflow.org/install/source) has been updated because even quite recently it was claiming that tests should work properly without any exclusions.

Anyway it's a bit annoying that the big open-source project doesn't have all tests running in the official docker image and when somebody wants to develop something there and wants to have CI running he needs to figure out which tests don't work (because in some cases fixing them would be very time consuming).

**Comment by jdduke** [comment] 2019-03-15 22:23
Yeah, apologies for the pain. Part of the problem is that internally we use another set of files to provide build hints for certain directories, but these hints are only used in our internal, automated builds.

**Comment by ymodak** [comment] 2021-06-18 22:39
Closing this issue since it's resolved. Thanks!

**Closed by ymodak** 2021-06-18 22:39 UTC
Labels: comp:lite, type:bug
