### ISSUE TITLE
tensorflow problems

### ISSUE THREAD

**Issue by Alankriti44** [tensorflow/tensorflow#38468] opened 2020-04-12 09:20 UTC
System Information:
- Windows 7
- TensorFlow installed via pip
- Python version: 3.8.2

Code:
from keras.models import Sequential

Error: 
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\chatbot\train_chatbot.py", line 8, in <module>
    from keras.models import Sequential
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\platform\self_check.py", line 53, in preload_check
    raise ImportError(
ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

**Comment by khimraj** [comment] 2020-04-12 11:50
@Alankriti44, It is due to installation problem. Install the DLL as in the error message.

**Comment by Saduf2019** [comment] 2020-04-12 17:36
@Alankriti44 
please follow [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) and below mentioned issues to resolve.

#35749 #38262 ##37906

**Comment by mihaimaruseac** [comment] 2020-04-16 16:58
Closing as the issue is that %PATH% is not updated to contain the needed libraries, thus not a TF issue

**Closed by mihaimaruseac** 2020-04-16 16:58 UTC
Labels: subtype:windows, type:build/install
