### ISSUE TITLE
[TFlite]: Failed to instantiate the interpreter with a StyleGAN2 generator model

### ISSUE THREAD

**Issue by ntreepoint** [tensorflow/tensorflow#42190] opened 2020-08-10 14:35 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel4, Samsung Galaxy S9+
- TensorFlow installed from (source or binary): binary
- TensorFlow version on desktop (use command below): tensorflow 2.2.0 + tensorflow-gpu 2.2.0
- TensorFlow lite version on mobile: tensorflow-lite:0.0.0-nightly + tensorflow-lite-gpu:0.0.0-nightly
- Python version: 3.6.10
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: V10.2.89
- GPU model and memory: 4* TITAN RTX 24GB

**Describe the current behavior**
I used `tf.compat.v1.lite.TFLiteConverter.from_session` to convert StyleGAN2 generator in Tensorflow lite format. the conversion  gives no error and no warning.
The option used for the conversion are as follow:
`converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]`
On phone, the interpreter instanciation fails when running on CPU: `tflite = new Interpreter(tfliteModel, tfliteOptions);` gives the following error:
`Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/pad.cc:111 op_context.dims <= reference_ops::PadKernelMaxDimensionCount() was not true.
    Node number 239 (PAD) failed to prepare.`
When trying to use GPU or NNAPI delegates, i have the same kind of error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.helloworld/org.pytorch.helloworld.MainActivity}: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: tensorflow/lite/kernels/pad.cc:111 op_context.dims <= reference_ops::PadKernelMaxDimensionCount() was not true.
    Node number 239 (PAD) failed to prepare.`

**Describe the expected behavior**
I expect the model to be able to execute whatever target (CPU/GPU/NNAPI) is used, but most likely on NNAPI or GPU to get the best performances.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs**
I tried several things to cope with this issue. When using the following option:
`converter.target_ops=SELECT_TF_OPS`
It is working on CPU, but fails with another error on GPU: 
`ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`
I guess this is because these target ops are not compatible with GPU and NNAPI delegates.

I also tried to use converter v2 using the following method:
`converter =  tf.lite.TFLiteConverter.from_concrete_functions([func])`
But the model size is very huge (624MB instead of 110MB for converter.v1) and i faced the same error when running on mobile: 
` Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/pad.cc:111 op_context.dims <= reference_ops::PadKernelMaxDimensionCount() was not true.
    Node number 221 (PAD) failed to prepare.`

**Comment by denieboy** [comment] 2020-08-11 07:36
Same thing happaned to me. During converting Pytorch model 'ir_csn_152' pretrained on 'ig_ft_kinetics_32frms' to Onnx, then to TF pb frozen graph, that is loaded and converted by TFLiteConverter sucessfully. But running  'interpreter.allocate_tensors()' gives 'RuntimeError: tensorflow/lite/kernels/pad.cc:111 op_context.dims <= reference_ops::PadKernelMaxDimensionCount() was not true.Node number 0 (PAD) failed to prepare.' error.

**Comment by srjoglekar246** [comment] 2020-08-25 20:03
@ntreepoint @denieboy Looks like some tensors in the graph have >4 dimensions, which isn't well-supported by TFLite yet. Can you share the tflite file? Even untrained works fine, as long as I can inspect the converter output file.

**Comment by ntreepoint** [comment] 2020-08-26 09:49
Hi @srjoglekar246 I can't share the model because of company restrictions. Anyway i have checked the model and i confirm that i have tensors which have more than 4 dimensions (up to 6). Do you know when this will be available in TFLite?

**Comment by srjoglekar246** [comment] 2020-08-26 15:42
Can you provide the ops you need >4 dim support for, apart from PAD?
You can use the [visualization tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py) on the TFLite graph for this.

**Comment by abattery** [comment] 2020-08-26 20:20
Could you try TF 2.3 or the latest version for the conversion? We've added a lot of sanity checks in the conversion in the TF 2.3 version. The converter is able to assign the TF ops to appropriate op set, TFLite builtin op or Flex op based on the input restriction unless the shape is undecided.

**Comment by ntreepoint** [comment] 2020-08-27 10:21
@srjoglekar246 , here is the list of ops that need dim >4:
```
MUL
STRIDED_SLICE
SQUARE
SUM
RESHAPE
TRANSPOSE
PAD
```

**Comment by ntreepoint** [comment] 2020-08-27 13:45
@abattery , i have tried using TF 2.3
The conversion fails. It generates a huge trace file (2.6G), it looks like you are dumping big data at the end such as model weight, perhaps you could reconsider the level of traces.
I don't have any error related to tensor dimensions. The error i got is the following:
`error: 'tf.Pad' op is neither a custom op nor a flex op`
I didn't get such error on 2.2. Where could it come from?

**Comment by abattery** [comment] 2020-08-27 20:15
Since your graph does operators, that are not supported in TFLite builtin operators. The conversion failure is an intended behavior. I would suggest conversion with Select TF ops in order to cover unsupported TF operator via Flex delegate.

https://www.tensorflow.org/lite/guide/ops_select
See also https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by ntreepoint** [comment] 2020-08-31 09:33
@abattery i confirm that this is working on CPU using TF operators. But this is not working on neither GPU nor NNAPI. I have the following warning message:
`Ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`
When inspecting the model i don't see any dynamic size.Here is the model details from visualize tool:
[generator.zip](https://github.com/tensorflow/tensorflow/files/5149531/generator.zip)
Can you pinpoint where this error come from? Does it mean that model using TF operators are not compatible with GPU and NNAPI?

**Comment by srjoglekar246** [comment] 2020-08-31 15:54
@ntreepoint That is indeed the case. Also, looks like *all* ops in your graph are turning out to be TF operators (hence the name 'CUSTOM' in the op names.) That isn't compatible with TFLite, so NNAPI/GPU delegation won't work.

**Comment by ntreepoint** [comment] 2020-09-10 13:03
@abattery ,
Coming back to the conversion issue i have using TF 2.3:
`note: see current operation: %579 = "tf.Pad"(%578, %cst_72) {device = ""} : (tensor<3x16x1x16x1x1xf32>, tensor<6x2xi32>) -> tensor<3x16x2x16x2x1xf32> error: 'tf.Pad' op is neither a custom op nor a flex op`
The error message is confusing. It states that the operator is not supported whereas i think it is supported by Tensorflow Lite. Does this message can be more likely triggered by the issue we raised before, which is that the input/output tensors dimensions are too big?
If so do you have a rough estimation on when it could be supported for the following ops i already mentioned:
```
MUL
STRIDED_SLICE
SQUARE
SUM
RESHAPE
TRANSPOSE
PAD
```

**Comment by abattery** [comment] 2020-09-22 21:59
FYI, Flex + GPU combination is now working at tf-nightly version if the graph has only static shapes.

**Comment by sailor002** [comment] 2020-12-31 16:03
Hi,

I have been doing the same as @ntreepoint to create a tflite model. I can successfully create the model with the -allow_custom_ops = True option. There are 2 custom ops in StyleGan2 which are “fused_bias_act” and “upfirdn_2d”. And it’s all ok when converting the model as these ops are already present. However, when I try to run inference on the same machine (python API) or run the tflite model on an iOS device I get the error “Encountered unresolved custom op: FusedBiasAct.Node number 352 (FusedBiasAct) failed to prepare”. I have tried a few methods but no luck so far.  What would be the best way to run the model on mobile with these custom ops. I appreciate your help…

**Comment by sailor002** [comment] 2021-01-04 06:56
Thanks for the information @abattery. I confirm that Flex + GPU is working with the Python interpreter. However, I'm trying to run the same StyleGAN2 model on iOS and I run into this error: TensorFlow Lite Error: "tensorflow/lite/kernels/strided_slice.cc new_axis_mask is not implemented yet. TensorFlow Lite Error: Node number 76 (STRIDED_SLICE) failed to prepare".  I tried different TF versions but it did not help. By the way, this error occurs when I convert the model with "TFLITE_BUILTINS" option. I know that I can use "SELECT_TF_OPS" but since iOS does not support a selective TF_OPS conversion, I have memory issues on iOS devices as it loads all of the TF ops and the model is very large. So TFLITE_BUILTINS seems to be the only option for me. Also, I have implemented a custom OP for RandomStandardNormal as it's not supported by TFLITE. Here is the link to the tflite model: https://bucket-mert.s3.us-east-2.amazonaws.com/StyleGAN2+Tflite/synthesis_tflite_build.tflite

Thanks for your help,
Regards

**Comment by abattery** [comment] 2021-01-04 22:52
@thaink could you take a look at this? It looks like the strided slice operator has an issue with the new_axis_mask attribute.

**Comment by abattery** [comment] 2021-01-04 22:55
@sailor002 could you make sure that the TensorFlow Lite conversion is done with the recent TensorFlow version? You can use the different TensorFlow versions for training a model and exporting the model to the corresponding TensorFlow Lite model. For example, you can export the saved model from TensorFlow 2.2 and convert the saved model in TensorFlow 2.4 or beyonds.

**Comment by thaink** [comment] 2021-01-05 00:53
> @thaink could you take a look at this? It looks like the strided slice operator has an issue with the new_axis_mask attribute.

New axis mask and ellipsis_mask are not yet supported in our strided_slice kernel.

**Comment by sailor002** [comment] 2021-01-05 07:11
Thanks for the quick reply. @abattery I also tried to convert the model with the latest nightly version but this time I get "Encountered unresolved custom op: Pad." on the device. Pad seems to be another custom op that needs to be implemented but I think that even if I find a way to implement it, I'll still get the new_axis_mask error afterward. @thaink are there any plans for new_axis_mask and ellipsis_mask to be supported in the near future. If not, is there an easy way that I can find a workaround or manually support it with a bazel-built custom library on the device? Thanks...

**Comment by abattery** [comment] 2021-01-05 08:32
@sailor002 could you convert your model with the select TF op option instead of using custom ops? I would confirm that the new_axis_mask error can be resolved by the Flex delegate in the recent version?

**Comment by sailor002** [comment] 2021-01-05 11:57
@abattery I've converted the model with TF op. It works with the python API (on a GPU cloud instance, with approx 10-seconds inference time). However, when I run the model on an iOS device (iPad 5th gen), I get a memory error: "* malloc: can't allocate region
:*** mach_vm_map(size=2437758976, flags: 100) failed (error code=3)
TfLite Test(5619,0x10d18b880) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc"

I googled it and tried out an answer saying that increasing the thread number could help, but unfortunately the error persists. By the way, I converted the model with the "tf.lite.Optimize.DEFAULT" optimization option. Any ideas what else could be done?

**Comment by sailor002** [comment] 2021-01-05 15:02
I managed to get the 256x256 version of the model (the original is 1024x1024) working on iPhone 11. On the iPad however, the issue still persists. So now it's all about memory. I think it's a handicap right now not being able to run the model without TF op (because of the new_axis_mask error). If we could, then we would definitely save a lot of memory. Plus, I am not able to use the Metal GPU and CoreML delegates as they are not supported by TF op. This seems to prolong prediction times which are around 3 secs on iPhone 11.

**Comment by abattery** [comment] 2021-01-05 22:22
I am not sure that the memory issue is coming from the TF library for the iOS platform or the heavy model itself. You can build your own slim TF library based on https://www.tensorflow.org/lite/guide/reduce_binary_size

@yyoon @thaink could you take a look?

**Comment by yyoon** [comment] 2021-01-06 05:33
@sailor002 How big is the model in megabytes, and on which exact iPad model are you seeing that error?

IIUC, TFLite reads the `.tflite` file as a memory-mapped file, so the entire model will be in read into memory.
I've never seen that particular memory allocation error before, but if the model file itself is too big to be read into memory, it could fail at the interpreter initialization step. (@srjoglekar246 @abattery please correct me if I'm wrong here.)

Would be good to try some memory profiling with the iPhone 11 on which you managed to run the model. Then you'd get a better idea of how much memory is used at runtime and if it's a reasonable amount of memory to be used in other devices.

**Comment by sailor002** [comment] 2021-01-06 06:48
@yyoon Here are the profiling results with iPad 5th Gen with [this](https://drive.google.com/file/d/1dbJQ1q-16J7kxdQBWqtdfjBxb1C0Bcf7/view?usp=sharing) model. The model is a tflite conversion of StyleGAN2 (applied Post-training float16 quantization). Normally, StyleGAN is trained to produce 1024x1024 images but I have downgraded it to be 128x128 for this model (because of the memory issue). As you see, RAM usage after the tensor allocation is around 20 MB which is quite normal. However, when I invoke the first inference, it rises up to 700 MB. After the 2nd inference, it rises up to about 800 MB and remains stable for every following inference.

The issue is that 128x128 is a low resolution for this project. I at least hope for 256x256 or more preferably 512x512 which causes an immediate memory crash when the inference is invoked. I don't know, maybe StyleGAN is not so suitable for mobile but I'm pushing the limits.

@abattery I considered using a custom slim library, but as far as I understand, it's not supported on iOS. The doc says "Selective Build for C API and iOS version is not supported currently". Correct me if I'm wrong.

And, one more interesting issue :) I managed to convert the model with "Post-training float16 quantization" obtaining a half-sized model which is expected. But when I used the OPTIMIZE_FOR_SIZE option (Post-training dynamic range quantization), the model size is almost unchanged compared to the original one, which is contrary to the expected quarter-sized binary. I also tried with "Post-training integer quantization", but again the model size is almost unchanged. Maybe if I could manage to convert the model to quarter size with these options, the memory issue may be resolved.

![1_after_tensor_alloc](https://user-images.githubusercontent.com/32747250/103737871-1e195500-5004-11eb-96bc-60ed0ae384ad.jpg)
![2_after_first_inference](https://user-images.githubusercontent.com/32747250/103737876-1fe31880-5004-11eb-9ddc-10160c5e981d.jpg)
![3_after_n_inference_stable](https://user-images.githubusercontent.com/32747250/103737879-207baf00-5004-11eb-9396-60f2cd949925.jpg)

**Comment by srjoglekar246** [comment] 2021-01-06 17:11
@sailor002 GAN models are usually tricky to get working well on mobile, I am afraid. One of our previous projects involved ESRGAN, and we had to distill it to a smaller model for efficient on-device performance (See [this repo](https://github.com/captain-pool/GSOC/tree/master/E3_Distill_ESRGAN)). Using a distilled model will probably reduce your model-size (by simplifying hidden layers) while still retaining a high input size.

In this case, there is only so much we can do on the inference side :-). On that note, have you tried 8-bit quantization-aware training for this? Might help reduce the memory overhead.

**Comment by sailor002** [comment] 2021-01-06 18:52
@srjoglekar246 thanks for the hints. I'll give the distillation method a try. I actually have not tried 8-bit quantization-aware training because I did not try to retrain the model (official weights are quite good). But maybe when I retrain the model for smaller sizes, I use 8-bit quantization-aware training in the process. But it's interesting that "Post-training dynamic range quantization" and "Post-training integer quantization" did not reduce the size at all. I remember the console logs saying something like "skipping quantization of {foo} because it has fewer than 1024 elements". Maybe this is the cause. Any ideas on that?

**Comment by srjoglekar246** [comment] 2021-01-06 19:06
That is strange. Most models contains weights etc that should be quantizable. Can you share your quantized conversion code?

Also, for the inference stats above, did you run on CPU or GPU?

**Comment by sailor002** [comment] 2021-01-11 10:20
@srjoglekar246  [Here](https://drive.google.com/file/d/1P87Nv0zxdxTm0ddtRlazRYrY2AUG8oik/view?usp=sharing) is the dynamic quantization model. And [here](https://drive.google.com/file/d/1CRdDzNBdVZqir57cPyFBrm7SVFLdEWcT/view?usp=sharing) is the integer quantization model.

I run on CPU because when I run on GPU, I get several other errors:
"
2021-01-05 13:55:14.157800+0300 TfLite Test[5624:2088575] TfLiteFlexDelegate delegate: 33 nodes delegated out of 700 nodes with 9 partitions.
TensorFlow Lite Error: Following operations are not supported by GPU delegate:
BROADCAST_TO: Operation is not supported.
DELEGATE TfLiteFlexDelegate: Operation is not supported.
STRIDED_SLICE: STRIDED_SLICE supports for 3 or 4 dimensional tensors only.
STRIDED_SLICE: Slice does not support shrink_axis_mask parameter. 
129 operations will run on the GPU, and the remaining 547 operations will run on the CPU.
TensorFlow Lite Error: TfLiteMetalDelegate Prepare: Tensor "model/Synthesis_network/4x4/Conv1/Mul_3" has bad input dims size: 5.
TensorFlow Lite Error: Node number 709 (TfLiteMetalDelegate) failed to prepare.
TensorFlow Lite Error: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
TensorFlow Lite Error: Node number 0 (FlexRandomStandardNormal) failed to prepare.
"

By the way, I'm working on the distillation method. I try to retrain a student model (both the same depth and a simplified version of the original model) but I guess there is something wrong because the model is not learning at all. Then I tried to use a standard DCGAN as the student model. This time it creates some face silhouettes but no more than that. It's strange that the original model performs worse than the standard DCGAN architecture. I've also studied the repo you've mentioned and it really helped. Do you have some best practices on this topic from your past experience like which student model architectures work best?. Thanks..

**Comment by srjoglekar246** [comment] 2021-01-11 17:09
@sailor002 Looks like you are trying to use 5-dim tensors, which are not well-supported on the GPU delegate. You will probably need to use different ops or reshape or something like that. Also, your model contains [TF Select ops](https://www.tensorflow.org/lite/guide/ops_select) for which you need to add some BUILD dependencies. See the linked docs for details.

Usually, simple Convolutional architectures (like the MobileNets) work best for on-device inference. Looks like your original model contains a lot of tricky architecture that won't perform the best on device. So distillation will certainly help. Most of the best-practices we learnt in that project are encoded in the repo I linked you too, so going over the code should help :-).

> It's strange that the original model performs worse than the standard DCGAN architecture. 

Do you mean the teacher performs *worse* than the student (the simpler model)?

**Comment by sailor002** [comment] 2021-01-14 10:26
@srjoglekar246 thanks for the tips. I appreciate your help. No, I mean I'm comparing a shallow version of StyleGAN2 (as the student) and a regular DCGAN architecture (also as the student). DCGAN student can produce face silhouettes wheres the shallow StyleGAN2 student can not produce anything. Maybe this is related to using a wrong training process on my side because StyleGAN2 training is also somewhat complex due to Progressively Growing architecture and some other details. But of course, this is out of the scope of this thread. Anyway, thanks for the support. I hope I can find a way to create a mobile-friendly tflite model :)

**Comment by srjoglekar246** [comment] 2021-01-14 16:30
@sailor002 You should be able to gauge on-device performance without training the model. Simply try converting & running an untrained model (just benchmark for latency using [our tool](https://www.tensorflow.org/lite/performance/measurement)). This will save wasted time on training student models.

**Comment by sailor002** [comment] 2021-01-15 05:47
Thanks, I'll definitely use it.

**Comment by sushreebarsa** [comment] 2021-08-03 18:01
@ntreepoint It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.2
