### ISSUE TITLE
No bounding box detection when using GPU

### ISSUE THREAD

**Issue by edwinjosegeorge** [tensorflow/tensorflow#55929] opened 2022-05-05 02:48 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.8.0-rc1-32-g3f878cff5b6 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9.7

### CUDA/cuDNN version

CUDA V10.1.243  cuDNN 8400

### Current Behaviour?

```shell
I have a custom yolov4 .weights that is converted to .tf model. When run on GPU, the model only gives detection for first 2 frames. However, when the model is run on CPU, all detection are properly made.

I have tried out the same at my local machine, a workstation, and at Google Colab, all results the same.
```

### Standalone code to reproduce the issue

```shell
The code used was imported from https://github.com/theAIGuysCode/yolov4-deepsort.git 
We used a custom yolov4 model trained on darknet. To run our detection, we first compile .weights into .tf using *save_model.py* and then changed the path for *weights* to point to our model and updated the core/config.py *coco.names* to our custom *label.names*
```

### Relevant log output

```shell
Output when running on GPU

OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Frame #:  1
Objects being tracked: 3
FPS: 0.38
Frame #:  2
Objects being tracked: 0
FPS: 17.86
Frame #:  3
Objects being tracked: 0
FPS: 16.62
Frame #:  4
Objects being tracked: 0
FPS: 16.76
Frame #:  5
Objects being tracked: 0
FPS: 16.45
Frame #:  6
Objects being tracked: 0
FPS: 16.78
Frame #:  7
Objects being tracked: 0
FPS: 16.47
Frame #:  8
Objects being tracked: 0
FPS: 15.85
Frame #:  9
Objects being tracked: 0
.....................


Output when running on CPU

OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Frame #:  1
Objects being tracked: 3
FPS: 1.00
Frame #:  2
Objects being tracked: 3
FPS: 5.62
Frame #:  3
Objects being tracked: 3
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (235, 455, 522, 620)
Tracker ID: 3, Class: bus,  BBox Coords (xmin, ymin, xmax, ymax): (0, 435, 44, 482)
FPS: 5.97
Frame #:  4
Objects being tracked: 3
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (220, 441, 549, 631)
Tracker ID: 3, Class: bus,  BBox Coords (xmin, ymin, xmax, ymax): (0, 435, 44, 482)
FPS: 5.60
Frame #:  5
Objects being tracked: 3
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (68, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (253, 451, 545, 618)
Tracker ID: 3, Class: bus,  BBox Coords (xmin, ymin, xmax, ymax): (0, 435, 44, 482)
FPS: 5.82
Frame #:  6
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (277, 453, 555, 610)
Tracker ID: 3, Class: bus,  BBox Coords (xmin, ymin, xmax, ymax): (0, 435, 44, 482)
FPS: 6.07
Frame #:  7
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (277, 446, 578, 615)
FPS: 6.21
Frame #:  8
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (297, 439, 588, 603)
FPS: 6.04
Frame #:  9
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (315, 438, 593, 593)
FPS: 6.12
Frame #:  10
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 467, 146, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (332, 441, 596, 586)
FPS: 6.27
Frame #:  11
Objects being tracked: 2
Tracker ID: 1, Class: car,  BBox Coords (xmin, ymin, xmax, ymax): (67, 466, 147, 508)
Tracker ID: 2, Class: van,  BBox Coords (xmin, ymin, xmax, ymax): (317, 428, 627, 599)
.....................................
```
</details>

**Comment by sushreebarsa** [comment] 2022-05-05 08:51
@edwinjosegeorge 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by edwinjosegeorge** [comment] 2022-05-05 17:04
## Code snippet
This is the code snippet that was ran on google colab. I downloaded yolov4.weights from [here](https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights) and saved into .tf using [this file](https://github.com/theAIGuysCode/yolov4-deepsort/blob/master/save_model.py)

```
import cv2
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.python.saved_model import tag_constants

saved_model_loaded = tf.saved_model.load("/content/ProjectAI/checkpoints/yolov4-416", tags=[tag_constants.SERVING])
infer = saved_model_loaded.signatures['serving_default']

vid = cv2.VideoCapture("/content/video.mp4")

frame_num = 0
input_size = 416

while True:
    return_value, frame = vid.read()
    if return_value:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(frame)
    else:
        print('Video has ended or failed, try a different video format!')
        break
    
    
    frame_num +=1
    
    frame_size = frame.shape[:2]
    image_data = cv2.resize(frame, (input_size, input_size))
    image_data = image_data / 255
    image_data = image_data[np.newaxis, ...].astype(np.float32)
    
    batch_data = tf.constant(image_data)
    pred_bbox = infer(batch_data)
    
    for key, value in pred_bbox.items():
        boxes = value[:, :, 0:4]
        pred_conf = value[:, :, 4:]
    
    
    
    boxes, scores, classes, valid_detections = tf.image.combined_non_max_suppression(
                boxes=tf.reshape(boxes, (tf.shape(boxes)[0], -1, 1, 4)),
                scores=tf.reshape(pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])),
                max_output_size_per_class=50,
                max_total_size=50,
                iou_threshold=0.5,
                score_threshold=0.5
            )
    
    # convert data to numpy arrays and slice out unused elements
    num_objects = valid_detections.numpy()[0]
    bboxes = boxes.numpy()[0]
    bboxes = bboxes[0:int(num_objects)]
    scores = scores.numpy()[0]
    scores = scores[0:int(num_objects)]
    classes = classes.numpy()[0]
    classes = classes[0:int(num_objects)]
    
    print(f"Frame {frame_num} -> detections: {len(classes)}")
```

## Output of Google Colab when ran on CPU only
```
Frame 1 -> detections: 3
Frame 2 -> detections: 3
Frame 3 -> detections: 3
Frame 4 -> detections: 3
Frame 5 -> detections: 2
Frame 6 -> detections: 2
Frame 7 -> detections: 2
Frame 8 -> detections: 2
Frame 9 -> detections: 2
Frame 10 -> detections: 2
Frame 11 -> detections: 2
Frame 12 -> detections: 2
Frame 13 -> detections: 2
Frame 14 -> detections: 2
Frame 15 -> detections: 2
Frame 16 -> detections: 2
Frame 17 -> detections: 2
Frame 18 -> detections: 2
Frame 19 -> detections: 2
Frame 20 -> detections: 2
```

## Output of Google Colab when ran on GPU support
```
Frame 1 -> detections: 3
Frame 2 -> detections: 0
Frame 3 -> detections: 0
Frame 4 -> detections: 0
Frame 5 -> detections: 0
Frame 6 -> detections: 0
Frame 7 -> detections: 0
Frame 8 -> detections: 0
Frame 9 -> detections: 0
Frame 10 -> detections: 0
Frame 11 -> detections: 0
Frame 12 -> detections: 0
Frame 13 -> detections: 0
Frame 14 -> detections: 0
Frame 15 -> detections: 0
Frame 16 -> detections: 0
Frame 17 -> detections: 0
Frame 18 -> detections: 0
Frame 19 -> detections: 0
Frame 20 -> detections: 0
```

**Comment by sushreebarsa** [comment] 2022-05-10 06:45
@edwinjosegeorge I tried to replicate this issue on colab and faced a different error.Could you share a sample video file to reproduce this issue?
Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7715d24f49b3132c041291e67954a4f9/gist55929.ipynb) and confirm the same?
Thank you!

**Comment by edwinjosegeorge** [comment] 2022-05-11 04:54
I read the gist and found few initial configs missing. Here is the new gist [file](https://colab.research.google.com/gist/edwinjosegeorge/e5828958aae45e22552039d624136250/gist55929.ipynb) that completely repoduces the error. 

We get detection only when it is executed on CPU alone. When it  runs on GPU acceleration, no detection are made.

**Comment by sushreebarsa** [comment] 2022-05-12 05:02
@edwinjosegeorge I was able to reproduce this issue on colab , could you find the attached gist in [cpu](https://colab.research.google.com/gist/sushreebarsa/dd56bd7d0945d4e60e7ddf69a483c115/untitled373.ipynb) and [gpu](https://colab.research.google.com/gist/sushreebarsa/ea4043624751989a686b69af941d1979/untitled374.ipynb) runtime?
Please confirm the same .
Thank you!

**Comment by edwinjosegeorge** [comment] 2022-05-13 04:37
Yes this is the issue we are facing when the same model is run on CPU and GPU

**Comment by gowthamkpr** [comment] 2022-06-02 21:42
@edwinjosegeorge As mentioned [here](https://stackoverflow.com/questions/69791192/theres-no-bounding-box-when-i-tested-darknet-pre-trained-model-no-detection-re), can you please try without opencv and check if it works on gpu. Thanks!

**Comment by edwinjosegeorge** [comment] 2022-06-03 03:08
I am using the saved weights from darknet into python. openCv is used to get the frame from video. I have my code build entire on python. The result of partitioning the CV component before running the detection is shown [here](https://gist.github.com/edwinjosegeorge/0403e3100cba9789bc21e230f889406f#file-gist55929-ipynb)

I found a work around by using the [yolov4 from pip](https://pypi.org/project/yolov4/) to process the frame, which works fine. The output have be seen in the same [file](https://gist.github.com/edwinjosegeorge/0403e3100cba9789bc21e230f889406f#file-gist55929-ipynb). It works as expected.

**Comment by edwinjosegeorge** [comment] 2022-06-08 16:29
Its a work around I found, using yolov4 from pip. Yes that does my job now...

However I did not find the root cause for the issue. The same code works on CPU but not on GPU really puzzled me. Still I do not know the reason behind it. I cross checked the saved weights and the file works fine in other parts. I think the line ` batch_data = tf.constant(image_data)` might be the culprit here. I has something to do with setting the values in GPU memory. I am not sure about it. I do not have understanding of how Graphs work in tensorflow.

**Comment by gowthamkpr** [comment] 2022-06-13 23:16
@edwinjosegeorge To get a clear understanding of graphs, you can go through this [documentation](https://www.tensorflow.org/guide/intro_to_graphs). I suspect the same too. Since you found the solution, can you please close this issue. Thanks!

**Closed** 2022-06-13 23:19 UTC
Labels: stat:awaiting response, type:bug, comp:gpu, TF 2.8
