### ISSUE TITLE
Error occurred when finalizing GeneratorDataset iterator

### ISSUE THREAD

**Issue by olk** [tensorflow/tensorflow#35100] opened 2019-12-13 22:06 UTC
**System information**
- OS Platform and Distribution: Arch Linux, 5.4.2-arch1-1-ARCH
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0rc0-1
- Keras version: 2.2.4-tf
- Python version: 3.8
- GPU model and memory: 2x GTX 1080 Ti 11GB"`

**Describe the current behavior**
executing Tensorflow's MNIST handwriting example produces error:
the error dissapears if the code doesn't use OneDeviceStrategy or MirroredStrategy

> W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

**Code to reproduce the issue**

 ```
 import tensorflow as tf
  import tensorflow_datasets as tfds
  import time
  
  from tensorflow.keras.optimizers import Adam
  
  def build_model():
      filters = 48
      units = 24
      kernel_size = 7
      learning_rate = 1e-4
      model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(filters=filters, kernel_size=(kernel_size, kernel_size), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(units, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
      ])
      model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate), metrics=['accuracy'])
      return model
  
  datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
  mnist_train, mnist_test = datasets['train'], datasets['test']
  
  num_train_examples = info.splits['train'].num_examples
  num_test_examples = info.splits['test'].num_examples
  
  strategy = tf.distribute.OneDeviceStrategy(device='/gpu:0')
  
  BUFFER_SIZE = 10000
  BATCH_SIZE = 32
  
  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label
  
  train_dataset = mnist_train.map(scale).shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
  eval_dataset = mnist_test.map(scale).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
  
  with strategy.scope():
    model = build_model()
  
  epochs=5
  start = time.perf_counter()
  model.fit(
          train_dataset,
          validation_data=eval_dataset,
          steps_per_epoch=num_train_examples/epochs,
          validation_steps=num_test_examples/epochs,
          epochs=epochs)
  elapsed = time.perf_counter() - start
  print('elapsed: {:0.3f}'.format(elapsed))
```

**Comment by gadagashwini** [comment] 2019-12-16 08:20
@olk, I tried reproducing the reported issue but it worked as expected. Please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/b4e63824872465031af99fccde00ebe1/untitled306.ipynb). Thanks!

**Comment by olk** [comment] 2019-12-16 22:04
upgraded to TensorFlow version: 2.1.0-rc1 - still get errors
please note that I execute the example at real hardware (not colab)

**Comment by olk** [comment] 2019-12-17 14:33
I guess this issue is related to using Tensorflow with Python-3.8.

**Comment by olk** [comment] 2019-12-17 18:30
I've downgraded my system:
- Python 3.7.4
- Tensorflow-2.1.0-rc1

Still facing the error:

> Train for 30000.0 steps, validate for 5000.0 steps
> Epoch 1/2
> 2019-12-17 19:21:54.361240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2019-12-17 19:21:55.824790: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2019-12-17 19:21:56.980785: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
> Relying on driver to perform ptx compilation. This message will be only logged once.
> 30000/30000 [==============================] - 115s 4ms/step - loss: 0.0856 - accuracy: 0.9761 - val_loss: 0.0376 - val_accuracy: 0.9879
> Epoch 2/2
> 29990/30000 [============================>.] - ETA: 0s - loss: 0.0152 - accuracy: 0.99582019-12-17 19:25:28.372294: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
> 30000/30000 [==============================] - 111s 4ms/step - loss: 0.0152 - accuracy: 0.9958 - val_loss: 0.0375 - val_accuracy: 0.9889
> 2019-12-17 19:25:40.010887: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
> 2019-12-17 19:25:40.031138: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
> elapsed: 226.391

seams to be related to tensorflow-2.1.0-rc1

**Comment by GeoMarky** [comment] 2019-12-17 23:18
I have the same issue.  Originally I was using:

tensorflow/tensorflow:nightly-gpu-py3

which has:

Then I tried upgrading tensorflow in the container with:

https://files.pythonhosted.org/packages/a9/fa/8ac34cf1369deb4f523a80eeb86ec0be3dd44139bfb42c45dd3829d6aff5/tf_nightly_gpu-2.1.0.dev20191217-cp36-cp36m-manylinux2010_x86_64.whl

I still have the same issue.

**Comment by jsimsa** [comment] 2019-12-18 00:12
@guptapriya @qlzh727 this seems to be an issue related to tf.distribute + tf.keras. In particular, as far as I can tell, the user code does not use `tf.data.Dataset.from_generator` but the error indicates that GeneratorDataset is used. Could you please triage? Thanks.

**Comment by guptapriya** [comment] 2019-12-18 00:36
The error log suggests that the training completed fine, but something at the end caused this error. Neither the training or validation dataset are using generators, so it does seem weird that there is a generator related error. Also it seems like it's just a warning - since the user's print statement at the end "elapsed.." did get printed as well. 

@jsimsa is tf.data.Dataset.from_generator the only time generator_dataset_op is used? Or could there be something else that could trigger it? 

@rchao could it be something related to any of the fault tolerance callbacks?

**Comment by andrew-bydlon** [comment] 2019-12-18 15:18
I can verify this error with python 3.8 and python-tensorflow-opt-cuda 2.1.0rc1-2 on arch linux.

**Comment by jsimsa** [comment] 2019-12-19 01:16
@guptapriya I realized that generator dataset is used in multi-device iterator. This seems related to newly added support for cancellation in tf.data.

The good news is that, as you pointed out, the warning is superfluous. The bad news is that, as far as I can tell, this warning will be present for all tf.distribute jobs in TF 2.1 (given how tf.data cancellation is implemented). I will look into having a fix for this cherrypicked into TF 2.1.

**Comment by guptapriya** [comment] 2019-12-19 01:21
Ah, great, thanks @jsimsa.

**Closed** 2019-12-20 00:22 UTC
Labels: TF 2.1, comp:data, type:bug

**Comment by spate141** [comment] 2020-02-12 02:54
@jsimsa Any update on this? I'm getting this exact message and it looks like my model.fit is not doing it's thing on validation dataset during training.

**Comment by Ely-S** [comment] 2020-02-13 22:40
I'm also experiencing this on the official Google Cloud Platform tf2-gpu.2-1.m42 image with Python 3.53.

**Comment by jsimsa** [comment] 2020-02-13 22:42
This warning is spurious and should be removed by https://github.com/tensorflow/tensorflow/commit/b6edd34c5858ab0ab4380da774e7e2fd81a92da0

**Comment by Mauhing** [comment] 2020-02-20 07:54
I think the error is not spurious. It indicates the memory leak for each epoch. Try to train for extremely large epochs. You will use up all memory.

**Comment by spate141** [comment] 2020-02-20 15:07
> Try to train for extremely large epochs. You will use up all memory.

@Mauhing Yup, it looks like! Tried to train a model with `batch_size=512` on couple millions samples on `g3s.xlarge` instance with 8GB GPU memory and 30GB RAM. It ran out of memory at one point after 2 epochs and I had to shut down the instance because it stopped responding! I hope @jsimsa, @guptapriya will look into this.

**Comment by dogacbasaran** [comment] 2020-02-21 07:42
@spate141 , @jsimsa , I have the same error and the memory leak as well. My configuration is TF 2.1.0, Ubuntu 18.04, Python 3.6.10. I'm using fit_generator with generators for train and validation. When I try to train a model, it directly starts filling up the cache memory until it crashes. I observed that the issue might be related to the validation part because it generates way more number of batches than it supposed to. This is error is not spurious.

**Comment by Mauhing** [comment] 2020-02-21 08:34
@spate141, @dogacbasaran  Yes, I have uploaded a small demo to demonstrate the problem it #36919. 

@dogacbasaran  I guess it depends which one is using the generator. is It the train set? or is It validation set? 

@spate141 Try to use a small batch_size, and extremly large epoch. The problem will still be there.

**Comment by dogacbasaran** [comment] 2020-02-21 09:46
@Mauhing when I first observed this issue, I wrote two separate generators doing exactly the same operations, one for training, one for validation. I printed the batch number in validation generator during training. At each epoch, validation generator supposed to generate 10 batches so after 280 epochs it should be around 2800 batches. But it generated more than 6600 batches and the cache memory was filled with 60GB in the process.

**Comment by spate141** [comment] 2020-02-21 21:05
@Mauhing Thanks for the scripts demo; I hope the team looked into it. And yes, I tried the small batch_size and it seems to be working fine as of now. Luckily, my model is reaching to a good validation accuracy point in relatively small number of epochs.. so there is that! 🤷🏻‍♂️

**Comment by Ely-S** [comment] 2020-03-05 00:47
It might help to point out that this is being printed out once per active GPU.

**Comment by Tuxius** [comment] 2020-03-08 18:58
**Problem description**

I am using TensorFlow 2.1.0 for image classification under Centos Linux. As my image training data set is growing, I have to start using a Generator as I do not have enough RAM to hold all pictures. I have coded the Generator based on this [tutorial](https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly).

It seems to work fine, until my program all the sudden gets killed without an error message:

```
Epoch 6/30
2020-03-08 13:28:11.361785: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
43/43 [==============================] - 54s 1s/step - loss: 5.6839 - accuracy: 0.4669
Epoch 7/30
2020-03-08 13:29:05.511813: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
 7/43 [===>..........................] - ETA: 1:04 - loss: 4.3953 - accuracy: 0.5268Killed
```

Looking at the growing memory consumption with linux's top, I suspect a memory leak?

**What I have tried**

- The above suggestion to switch to TF nightly build version. For me it did not help, also downgrading to TF2.0.1 did not help

- There is a [discussion ](https://stackoverflow.com/questions/60000573/error-occurred-when-finalizing-generatordataset-iterator-cancelled-operation-w) suggesting that it is important, that 'steps_per_epoch' and 'batch size' correspond (whatever this exactly means) - I played with it without finding any improvement.

- Trying to narrow down by looking at the size development of all variables in my Generator

**Relevant code snippets**

```
class DataGenerator(tf.keras.utils.Sequence):
    'Generates data for Keras'
    def __init__(self, list_IDs, labels, dir, n_classes):
        'Initialization'
        config = configparser.ConfigParser()
        config.sections()
        config.read('config.ini')

        self.dim = (int(config['Basics']['PicHeight']),int(config['Basics']['PicWidth']))
        self.batch_size = int(config['HyperParameter']['batchsize'])
        self.labels = labels
        self.list_IDs = list_IDs
        self.dir = dir
        self.n_channels = 3
        self.n_classes = n_classes
        self.on_epoch_end()        


    def __len__(self):
        'Denotes the number of batches per epoch'
        return math.floor(len(self.list_IDs) / self.batch_size)

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]

        # Find list of IDs
        list_IDs_temp = [self.list_IDs[k] for k in indexes]

        # Generate data
        X, y = self.__data_generation(list_IDs_temp)

        return X, y, [None]
```

being called by

```
        training_generator = datagenerator.DataGenerator(train_files, labels, dir, len(self.class_names))
        self.model.fit(x=training_generator,
                    use_multiprocessing=False,
                    workers=6, 
                    epochs=self._Epochs, 
                    steps_per_epoch = len(training_generator),
                    callbacks=[LoggingCallback(self.logger.debug)])
```

Any ideas highly welcome, I am stuck!

**Comment by PhilipMay** [comment] 2020-03-09 21:03
@Tuxius I have the same Issue. Should be reopen this? Why is it closed anyway?

**Comment by 4doge** [comment] 2020-03-10 12:35
@Tuxius @PhilipMay the same problem here

**Comment by Tuxius** [comment] 2020-03-11 20:33
Since more and more people (@PhilipMay, @jsimsa, @drsantos89, @4doge, @Tuxius, ...) report to also still have the same issue I have reopened it [#37515](https://github.com/tensorflow/tensorflow/issues/37515)

**Comment by ds21194** [comment] 2020-03-17 21:38
I have the same problem (using fit_generator)
I'm using windows 10, python 3.6 and tensorflow 2.1 (cuda 10.1, cudnn 7.6.5)

**Comment by aliutkus** [comment] 2020-03-24 07:57
same issue here, with CPU, tf 2.1 and python 3.7

**Comment by ybagdasa** [comment] 2020-03-24 18:10
same issue here, scales with validation_freq (occurs on those epochs for which validation is performed.) 
I'm using the tensorflow image tensorflow/tensorflow:2.1.0-gpu-py3 from docker hub: https://hub.docker.com/r/tensorflow/tensorflow/tags/?page=1

Within the image, the system is 18.04.3 LTS, cuda 10.1.243, python Python 3.6.9

**Comment by ysyyork** [comment] 2020-03-25 15:03
I'm using keras Sequence and saw this issue too. However it's weird if I only use one worker, it works well. I didn't use multiprocessing tho. 2 worker thread will leave the training hang and data show this error

**Comment by jsimsa** [comment] 2020-03-25 15:55
There was a bug for Keras sequence multi-processing implementation that was fixed in https://github.com/tensorflow/tensorflow/commit/e918c6e6fab5d0005fcde83d57e92b70343d3553. This will be available in TF 2.2 and should be already available in TF nightly.

**Comment by ybagdasa** [comment] 2020-03-26 03:35
@jsimsa thanks for the heads up! I updated to tf-nightly-gpu and the error: 
`W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled` went away.

**Comment by jsimsa** [comment] 2020-03-26 15:38
Good to know. Note that the warning and the memory leak are unrelated.

**Comment by flydragon2018** [comment] 2020-03-28 19:01
> @jsimsa thanks for the heads up! I updated to tf-nightly-gpu and the error:
> `W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled` went away.

I updated today. I confirm that.

**Comment by flydragon2018** [comment] 2020-03-28 19:04
but the training result   seems not stable.   train/val  loss/accuracy up and downs too much.

**Comment by ybagdasa** [comment] 2020-03-28 23:53
For me the results aren't reproducible from run to run either, even with
tf.random.set_seed(), but I suspect it has to do with multiple workers for
my image augmentation generator.

**Comment by vuducnghia** [comment] 2020-05-02 08:00
I have the same issue. I fixed it by:
pip install tf-nightly-gpu and down batchsize

**Comment by Serhiy-Shekhovtsov** [comment] 2020-06-12 15:55
Had the same problem. Memory leak and crash after some number of epochs. Looks like the `ModelCheckpoint` callback is a culprit. Removing it solved the issue.

**Comment by mikechen66** [comment] 2020-07-28 16:21
> I guess this issue is related to using Tensorflow with Python-3.8.

It is not related to Python 3.8. I have the same problem with Python 3.7.4

**Comment by leszekmp** [comment] 2020-08-01 17:15
I found a reason for the problem on my computer - YMMV. I was using the ModelCheckpoint callback to save the best model, and if there was a model with that name already in the folder, I got the error. Removing or renaming the model with that name fixed the issue. Windows 10 system, Python 3.7.4.

**Comment by a-arbabian** [comment] 2020-08-10 18:06
Adding this code snippet fixes this issue for me when using RTX GPUs:
```
devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(devices[0], True)
```
This is something I have to do in my training scripts as well. Might help someone :+1:

**Comment by ccl-private** [comment] 2020-09-07 01:48
https://github.com/610265158/face_landmark/issues/34#issuecomment-615152235

**Comment by Gare-Ng** [comment] 2020-10-03 09:02
Ideas from stackoverflow.  I just directly copy the code from deeplearning.ai in colab. A part of it goes like this:
`train_generator = train_datagen.flow_from_directory(
        'horse-or-human/',  # This is the source directory for training images
        target_size=(300, 300),  # All images will be resized to 300x300
        batch_size=128,
        # Since we use binary_crossentropy loss, we need binary labels
        class_mode='binary')
        
history = model.fit(
      train_generator,
      steps_per_epoch=8,  
      epochs=15,
      verbose=1)`
and there are 1027 images. 128*8=1024, less than 1027.
So, for me the **problem arises when there is wrong correspondence on the batch size and steps(iterations)**.
At least this is one of the cases for the error.
Here is the original answer [https://stackoverflow.com/questions/60000573/error-occurred-when-finalizing-generatordataset-iterator-cancelled-operation-w](url)

**Comment by rcx986635** [comment] 2021-03-26 07:02
I have the same problem (using model.fit() ,and one numpy generator but keras.sequence)
I'm using linux redhat, python 3.6 and tensorflow 2.4.1.
then I got the error 
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 190, in __init__
    if value < 0:
RecursionError: maximum recursion depth exceeded in comparison
2021-03-26 14:50:45.148650: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

**Comment by rcx986635** [comment] 2021-03-26 07:05
devices = tf.config.experimental.list_physical_devices('GPU')  tf.config.experimental.set_memory_growth(devices[0], True)    
not work for me

**Comment by rcx986635** [comment] 2021-03-26 07:38
It might be helpful ,
Epoch 00001: loss improved from inf to 93.23533, saving model to model/best_model.h5
Traceback (most recent call last):
  File "train_v2.py", line 1070, in train
    callbacks=callbacks_list)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1344, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1396, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2002, in save
    signatures, options, save_traces)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 154, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 115, in save_model_to_hdf5
    model_metadata = saving_utils.model_metadata(model, include_optimizer)
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 155, in model_metadata
    model_config['config'] = model.get_config()
  File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 650, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

**Comment by prajwaljpj** [comment] 2021-04-16 12:17
> I have the same problem (using model.fit() ,and one numpy generator but keras.sequence)
> I'm using linux redhat, python 3.6 and tensorflow 2.4.1.
> then I got the error
> File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 215, in _deepcopy_list
> append(deepcopy(a, memo))
> File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
> y = _reconstruct(x, memo, *rv)
> File "/root/python_env/anaconda3/lib/python3.6/copy.py", line 274, in _reconstruct
> y = func(*args)
> File "/root/python_env/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 190, in **init**
> if value < 0:
> RecursionError: maximum recursion depth exceeded in comparison
> 2021-03-26 14:50:45.148650: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
> [[{{node PyFunc}}]]

Running into the same error...

Here is some information about my configuration:
Distribution: 
```shell
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

GPU Driver:
```shell
Fri Apr 16 12:13:45 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   34C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

CUDA version:
```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

```
Python version:
```shell
Python 3.8.0
```

Tensorflow version:
```shell
# Tensorflow-2.4.1 compiled from source with gcc and no TensorRT
tensorflow @ file:///home/ubuntu/projects/tensorflow/mywhl/tensorflow-2.4.1-cp38-cp38-linux_x86_64.whl
tensorflow-addons==0.12.1
tensorflow-estimator==2.4.0
```

Any thoughts?

**Comment by Amokstakov** [comment] 2021-06-14 03:47
The following solved the issue for me:

```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession


def fix_gpu():
    config = ConfigProto()
    config.gpu_options.allow_growth = True
    session = InteractiveSession(config=config)


fix_gpu()
```

Call this function at the start of your script

**Comment by magicianofriga** [comment] 2021-07-05 08:40
Hi, 
I seem to be facing the same issue with Leela Chess Zero training. 

message.txt
I have tried various fixes to this problem (changing the parser, changing CUDA version, changing Python version, changing TF version etc). But it continues to persist. Please help me rectify this issue.

My current PC configuration:
8 GB RAM
Intel i7-4790K
NVIDIA RTX 2070 SUPER
1TB SSD

My current requirement setup:
CUDA 11.3
CUDNN 8.2.1
Python 3.9.5
TF-Nightly GPU (2.7.0 dev)

As you can see from the attachment, the training progresses fine. But when it reaches a checkpoint an Assertion Error is thrown. I have tried this fix:

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession


def fix_gpu():
    config = ConfigProto()
    config.gpu_options.allow_growth = True
    session = InteractiveSession(config=config)

fix_gpu()

But it doesn't seem to work. Please help.

**Comment by Nafees-060** [comment] 2022-03-12 17:25
Getting same error;  
 ```
 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_6832]
2022-03-13 01:17:08.463663: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

```

Tried every possible way to fix it. However, could not successful. Honestly, don't know why this error occurring? I would request please reopen this issue?

**Comment by mrk1992** [comment] 2022-04-03 14:50
I suppose a file named 'train.py' to run  (this is an example)

When run .py files in terminal
```console
$ CUDA_VISIBLE_DEVICES=0 python train.py  # Uses GPU 0.
$ CUDA_VISIBLE_DEVICES=1 python train.py  # Uses GPU 1.
$ CUDA_VISIBLE_DEVICES=2,3 python train.py  # Uses GPUs 2 and 3.
```


2. Add 3 lines in train.py file
~~~python
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   
os.environ["CUDA_VISIBLE_DEVICES"]="0"
~~~

**Comment by raymondconfidence** [comment] 2022-10-28 18:37
> The following solved the issue for me:
> 
> ```
> from tensorflow.compat.v1 import ConfigProto
> from tensorflow.compat.v1 import InteractiveSession
> 
> 
> def fix_gpu():
>     config = ConfigProto()
>     config.gpu_options.allow_growth = True
>     session = InteractiveSession(config=config)
> 
> 
> fix_gpu()
> ```
> 
> Call this function at the start of your script

Worked for me.
Thanks for sharing

**Comment by pangyuteng** [comment] 2023-04-09 15:37
for what its (not) worth, with the below,
```
gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
logical_gpus = tf.config.list_logical_devices('GPU')
print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
```

I am still getting this same error, oddly after 55 epochs (step*batch size == total test n). I am not using tf.data but subclassing `tensorflow.keras.utils.Sequence` for the data generator.

"W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated."

tf version: tensorflow/tensorflow:2.10.0-gpu-jupyter

**Comment by pangyuteng** [comment] 2023-04-09 16:17
for what its worth (or not)...

I saw this same "error" (which is a actually warning) in the one of my training log file `W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]`

But the exit code of the train script is `0`, and turns out training stopped due to `tf.keras.callbacks.EarlyStopping` kicked in, and i did not set `verbose=1` in the earlystopping callback.

--

Also I was not able to replicate this error with the code provided in the original post 
https://github.com/tensorflow/tensorflow/issues/35100#issue-537798504

versions used:
```
container: tensorflow/tensorflow:2.10.0-gpu-jupyter
tensorflow_datasets==4.9.0
```
