### ISSUE TITLE
Raspberry pi - Go Tensorflow - OOM allocating tensor issue

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/tensorflow#25948] opened 2019-02-20 19:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
1. Code in Golang
2. Used GO Tensorflow
3. MobileNet model 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Raspberry Pi (1.4GHz, 1024 RAM, 4 Cores)
- TensorFlow version (use command below):
v1.12.0

**Describe the current behavior**
I have written a Face Classification code which uses MobileNet (depth 80) model. But When I ran the model after 8-10 min, tensorflow is throwing OOM allocation error.
**Describe the expected behavior**
Because raspberry pi has limited memory. But as the model is very small it has to run perfectly.
**Code to reproduce the issue**
1. Run MobileNet model classification in Golang Env
2. Input tensor shape [5,224,224,3], tried other batch sizes as well 1 and 3 but no luck.
**Other info / logs**
```
2019-02-20 10:52:26.403200: W tensorflow/core/framework/op_kernel.cc:1412] OP_REQUIRES failed at fused_batch_norm_op.cc:573 : Resource exhausted: OOM when allocating tensor with shape[5,112,112,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
2019-02-20 10:52:26.478760: W tensorflow/core/framework/op_kernel.cc:1412] OP_REQUIRES failed at pad_op.cc:137 : Resource exhausted: OOM when allocating tensor with shape[5,113,113,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
E0220 10:52:26.483588    3282 classifier.go:203] Failed to classify face: OOM when allocating tensor with shape[5,112,112,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node mobilenet_1.00_224/conv_pw_1_bn/FusedBatchNorm}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

**Comment by ymodak** [comment] 2019-02-21 21:10
@asimshankar Can you PTAL? Thanks!

**Comment by anilknayak** [comment] 2019-03-21 22:24
Can anybody help me here?

**Comment by anilknayak** [comment] 2019-03-22 19:22
latest log
```
E0321 17:42:11.720840     471 classifier.go:204] Failed to classify face: OOM when allocating tensor with shape[2,113,113,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node mobilenet_1.00_224/conv_pad_2/Pad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
E0321 17:42:16.627385     471 classifier.go:204] Failed to classify face: OOM when allocating tensor with shape[2,113,113,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node mobilenet_1.00_224/conv_pad_2/Pad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
E0321 17:42:27.929953     471 classifier.go:204] Failed to classify face: OOM when allocating tensor with shape[2,113,113,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node mobilenet_1.00_224/conv_pad_2/Pad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

Is this because of floating and shape [2,113,113,64]? I am trying out the quantization of model?
I will update on this.

**Comment by petewarden** [comment] 2019-08-01 21:46
From the description, it looks like this is a duplicate of #25554 ? Closing for now, but please reopen with more information if I'm misunderstanding.

**Closed by petewarden** 2019-08-01 21:46 UTC
Labels: comp:apis, stat:awaiting tensorflower
