### ISSUE TITLE
Can I use the same record file for tf_record_input_reader (Object Detection)?

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#28035] opened 2019-04-22 07:59 UTC
I have one image dataset with some classes and needed annotations.
So I made a record file (`train.record`) for training an object detection model.
I set it in `train_input_reader`

But what should I set for `eval_input_reader`? Can I use the same record file? 

"Eval" is used for verifying the quality of training as I understand

    train_input_reader: {
      tf_record_input_reader {
        input_path: "object_detection/train.record"
      }
      label_map_path: "object_detection/training/labelmap.pbtxt"
    }
    
    ...
    
    eval_input_reader: {
      tf_record_input_reader {
        input_path: "???"
      }
      label_map_path: "object_detection/training/labelmap.pbtxt"
      shuffle: false
      num_readers: 1
    }

**Comment by muddham** [comment] 2019-04-23 13:16
@anonym24 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-08 21:30
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-08 21:30 UTC
Labels: comp:model, type:support
