### ISSUE TITLE
Bad download link for Windows GPU only binaries zip file

### ISSUE THREAD

**Issue by krsummersBA** [tensorflow/tensorflow#58933] opened 2022-12-18 04:14 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

x86_64-2.11.0

### Custom Code

No

### OS Platform and Distribution

Windows x86 GPU only

### Current Behaviour?

```shell
storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip

The zip file does not exist.  "No such object"
```

### Standalone code to reproduce the issue

```shell
"No such object"  when clicking on the download link
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment] 2022-12-18 11:34
Hi @krsummersBA !
I can confirm your observations on GPU wheels from pip installation document . ( Can downloads CPU wheels as expected and see 404 error)

Could you point the location of this "storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip " file too. 


@SuryanarayanaY !
Could you look at this issue. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/8976ab15e663d5e5e9e16838861874fa/git_58933.ipynb#scrollTo=dQ6xAn6nAQc9) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment] 2022-12-19 14:52
All the Windows GPU links mentioned in [Documentation](https://www.tensorflow.org/install/pip#package_location) are empty.This might be due to recent development with Windows or due to some broken links during recent updation in Documentation. 

@krsummersBA , Thanks for reporting this and we will have a look into it and Meanwhile if you want you can refer [here](https://www.tensorflow.org/install/pip#step-by-step_instructions) for instructions on how to install Tensorflow with GPU support for Windows.

Thankyou!

**Comment by krsummersBA** [comment] 2022-12-21 02:18
Can you provide an alternate / temporary link for the  GPU .zip file?   I don't want to build/install this from scratch, but just need the valid zip file so I can reference some of the included DLL files.

**Comment by MDSchechtman** [comment] 2022-12-21 18:15
> Can you provide an alternate / temporary link for the GPU .zip file? I don't want to build/install this from scratch, but just need the valid zip file so I can reference some of the included DLL files.

Note sure about how to get the latest version, but the previous can be downloaded by changing the url: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.10.0.zip

**Comment by ADITYADAS1999** [comment] 2023-01-01 02:26
> All the Windows GPU links mentioned in [Documentation](https://www.tensorflow.org/install/pip#package_location) are empty.This might be due to recent development with Windows or due to some broken links during recent updation in Documentation.
> 
> @krsummersBA , Thanks for reporting this and we will have a look into it and Meanwhile if you want you can refer [here](https://www.tensorflow.org/install/pip#step-by-step_instructions) for instructions on how to install Tensorflow with GPU support for Windows.
> 
> Thankyou!

hey [SuryanarayanaY](https://github.com/SuryanarayanaY) this issue is still open ?

**Comment by SuryanarayanaY** [comment] 2023-01-04 09:48
Hi @krsummersBA @ADITYADAS1999 ,

Since from Tensorflow 2.11, For windows native GPU support disabled and instructions to use GPU are different and it is mentioned in the document [here](https://www.tensorflow.org/install/pip#step-by-step_instructions).A [PR](https://github.com/tensorflow/docs/pull/2172) has been moved for removal of those broken/non existing GPU wheels for windows.

Thank you!

**Comment by SuryanarayanaY** [comment] 2023-01-23 17:02
@krsummersBA ,
The mentioned PR has been merged.Could you please check and confirm? Thanks!

**Closed** 2023-01-23 20:05 UTC
Labels: type:docs-bug, stat:awaiting response, type:build/install, ready to pull, subtype:windows, TF 2.11
