### ISSUE TITLE
Tensorflow tutorial "How to Retrain": error when saving the model

### ISSUE THREAD

**Issue by mostafachatillon** [tensorflow/tensorflow#1389] opened 2016-03-05 06:29 UTC
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

hello,
I am trying to run the tutorial 'How to Retrain Inception's Final Layer for New Categories'
available here: https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html

### Environment info
Operating System: Ubuntu 14.04

If installed from binary pip package, provide:

1. Which pip package you installed: I use the following AWS community AMI: 
Axel TensorFlow machine - ami-a41147ce   in Northern Virginia region.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)":

I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
0.5.0

If installed from sources, provide the commit hash:

### Steps to reproduce
step 1. download and unpack images: curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz

step 2. run:    python retrain.py --image_dir ~/flower_photos

### What have you tried?
1. nothing: I do not know what to do

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

the only difference with the tutorial is that I do not use Bazel, I just do: 

python retrain.py --image_dir ~/flower_photos

Everything runs smoothly, until I get this error:

Final test accuracy = 91.6%
Traceback (most recent call last):
File "retrain.py", line 829, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
sys.exit(main(sys.argv))
File "retrain.py", line 820, in main
output_graph_def = graph_util.convert_variables_to_constants(
AttributeError: 'module' object has no attribute 'convert_variables_to_constants'

The problematic portion of the code is:

  # Write out the trained graph and labels with the weights stored as constants.
  output_graph_def = graph_util.convert_variables_to_constants(
      sess, graph.as_graph_def(), [FLAGS.final_tensor_name])
  with gfile.FastGFile(FLAGS.output_graph, 'wb') as f:
    f.write(output_graph_def.SerializeToString())
  with gfile.FastGFile(FLAGS.output_labels, 'w') as f:
    f.write('\n'.join(image_lists.keys()) + '\n')

What should I do?

**Comment by petewarden** [comment] 2016-03-07 23:07
The Bazel build process helps set up the dependency paths for things like graph_util, so that's the supported path for this. Looking at your error, I'm guessing you have an older pip-installed version of TensorFlow, where the graph_util namespace didn't include that function, which was introduced after 0.7.1.
https://github.com/tensorflow/tensorflow/commit/2179890199c3561ff3a1297c5e9c073471473a77#diff-33f2d39e607bc1b6234f0972973159cb
I hope this explanation helps. I'm closing this since I believe it's working as intended.

**Closed by petewarden** 2016-03-07 23:07 UTC

**Comment by mostafachatillon** [comment] 2016-03-16 08:38
yes, you were right, with the version 0.7.1, it worked
