### ISSUE TITLE
tf.keras.callbacks.ProgbarLogger(count_mode='samples') does not work

### ISSUE THREAD

**Issue by dfangs** [tensorflow/tensorflow#38765] opened 2020-04-21 19:57 UTC
**System information**
(I'm sorry, this is my first time writing an issue.)
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3.6

**Describe the current behavior**
I noticed from [this commit](https://github.com/tensorflow/tensorflow/commit/10666c59dd4858645d1b03ce01f4450da80710ec) that the default behavior of `ProgbarLogger` has been changed to always show the number of `'steps'` instead of `'samples'`. I was curious and tried to manually use a `ProgbarLogger` callback argument to `Model.fit()` with `count_mode='samples'` instead, but then an error showed up.

**Describe the expected behavior**
 I expected it to work normally as with the older version of TensorFlow?

**Standalone code to reproduce the issue**
```python
# Assuming we use mnist data set
model = Sequential([
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10)
])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

model.fit(x_train, y_train, callbacks=[tf.keras.callbacks.ProgbarLogger('steps')])
```

**Other info / logs**
On my local machine (TF 2.1), this is the default behavior:
```
Epoch 1/5
16500/16500 [==============================] - 3s 207us/sample - loss: 0.4841 - accuracy: 0.8584
Epoch 2/5
16500/16500 [==============================] - 2s 95us/sample - loss: 0.2430 - accuracy: 0.9276
Epoch 3/5
...
```

On Google Colab (TF 2.2), I got this when I tried my code:
```
0/Unknown - 1s 0s/sample - loss: 0.3902 - accuracy: 0.8912

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py:595: RuntimeWarning: divide by zero encountered in log10
  numdigits = int(np.log10(self.target)) + 1

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-51-834d420b09ab> in <module>()
      8 model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
      9 
---> 10 model.fit(x_train, y_train, callbacks=[tf.keras.callbacks.ProgbarLogger('samples')])

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    877           epoch_logs.update(val_logs)
    878 
--> 879         callbacks.on_epoch_end(epoch, epoch_logs)
    880         if self.stop_training:
    881           break

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    363     logs = self._process_logs(logs)
    364     for callback in self.callbacks:
--> 365       callback.on_epoch_end(epoch, logs)
    366 
    367   def on_train_batch_begin(self, batch, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    892 
    893   def on_epoch_end(self, epoch, logs=None):
--> 894     self._finalize_progbar(logs)
    895 
    896   def on_test_end(self, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in _finalize_progbar(self, logs)
    933       self.progbar.target = self.seen
    934     logs = logs or {}
--> 935     self.progbar.update(self.seen, list(logs.items()), finalize=True)
    936 
    937 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in update(self, current, values, finalize)
    593 
    594       if self.target is not None:
--> 595         numdigits = int(np.log10(self.target)) + 1
    596         bar = ('%' + str(numdigits) + 'd/%d [') % (current, self.target)
    597         prog = float(current) / self.target

OverflowError: cannot convert float infinity to integer
```

**Comment by ravikyram** [comment] 2020-04-22 10:37
@dfangs 

Looks like code is incomplete. Request you to provide colab link or simple standalone code to reproduce the issue reported here.It helps us in localizing the issue faster.Thanks!

**Comment by dfangs** [comment] 2020-04-22 12:14
@ravikyram 

Here is the link to a simple [colab](https://colab.research.google.com/drive/19gsTsz94MpW5r03NwgWD3Kl1iPgWFFdT) that I made, thank you.

**Comment by goldiegadde** [comment] 2020-04-22 18:18
@dfangs as noted [here](https://github.com/tensorflow/tensorflow/issues/38618#issuecomment-617907735) can you add verbose to model.fit() call. this should work.

**Comment by dfangs** [comment] 2020-04-22 18:28
@goldiegadde But that would default to `count_mode='steps'`. The thing is I would like the progress bar to display the number of samples (instead of steps), which is not the default behavior per the [commit](https://github.com/tensorflow/tensorflow/commit/10666c59dd4858645d1b03ce01f4450da80710ec) I mentioned above. Since apparently there is no way to configure that, I tried to manually insert `tf.keras.callbacks.ProgbarLogger(count_mode='samples')` into the `callbacks` parameter. I wish there was an option to configure that.

I looked at the link you gave me but it seems that the problem wasn't resolved. Hopefully this makes it clear.

**Comment by ravikyram** [comment] 2020-09-17 07:27
@dfangs 

I tried in colab with TF nightly version(`2.4.0-dev20200916`) and i am not seeing any issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/4acd5f63414cf559763431c971d3e6f2/untitled82.ipynb).Please, verify once and close the issue. Thanks!

**Closed** 2020-10-02 21:14 UTC
Labels: TF 2.2, comp:keras, regression issue, stalled, stat:awaiting response, type:bug
