### ISSUE TITLE
tensorflow.keras.layer.add() causes exception in to_json()

### ISSUE THREAD

**Issue by EdmundButler** [tensorflow/tensorflow#40608] opened 2020-06-19 11:34 UTC
**System information**
- custom code (below)
- OS: Windows 10
- Tensorflow installed from binary
- Tensorflow version v2.2.0-rc4-8-g2b96f3662b 2.2.0. 
- Keras version 2.3.0-tf
- Python version 3.6
- Run from CPU

**Describe the current behavior**
to_json() causes exception in nest.pack_sequence_as()

**Describe the expected behavior**
to_json() should work!

**Standalone code to reproduce the issue**
"""
        Keras/Tensorflow bug.
  Exception in to_json()/.../nest.pack_sequence_as().
  Change "KL.add" to "tf.add_n" and there is no problem

  Using Tensorflow 2.2.0
        Keras 2.3.0-tf
""" 
import tensorflow.keras.layers as KL
import tensorflow.keras.models as KM
import tensorflow as tf

Input=KL.Input(batch_shape=[2,2])
sk=[]
o1=KL.Dense(17,name='d1')(Input)
sk.append(o1)
o2=KL.Dense(17,name='d2')(o1)
sk.append(o2)
x1 = KL.add(sk,name='a1')
o3=KL.Dense(17,name='d3')(o2)
sk.append(o3)
x2 = KL.add(sk,name='a2')

m=KM.Model(inputs=[Input],outputs=[x1,x2])
m.summary()
junk = m.to_json()

**Comment by amahendrakar** [comment] 2020-06-19 15:46
@EdmundButler,
I was able to reproduce the error with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/11aa0e9bb6c11a86ed142395461dff56/40608.ipynb). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b88a2dafe177ef01458303e8659c1045/40608-tf-nightly.ipynb). Please check the linked gist. Thanks!

**Closed** 2020-07-03 17:19 UTC
Labels: Fixed in Nightly, TF 2.2, comp:keras, stalled, stat:awaiting response, type:bug
