### ISSUE TITLE
Dynamic Input support for TFLite models

### ISSUE THREAD

**Issue by neso613** [tensorflow/tensorflow#48915] opened 2021-05-05 12:40 UTC
Hello Tensors
I have a TF model with (None,None,100) input dims and its converted into TFLite too.
But when I do inference, it gives error-
RuntimeError: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)Node number 72 (RESHAPE) failed to prepare.

**System information**
- TensorFlow version (you are using): 2.4.1.

**Describe the feature and the current behavior/state.**
Currently, 0th index can be dynamic(None or -1).

**Will this change the current api? How?**
Other indexs of model input can be dynamic(None or -1)

**Who will benefit with this feature?**
Generally, Vision models have 0th index dynamic but NLP models have other dimensions as dynamic.

**Comment by neso613** [comment] 2021-05-05 12:41
@ichuang

**Comment by abattery** [comment] 2021-05-05 12:50
@neso613 Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.

FYI, both TF and TFLite supports multiple dimensions but the Reshape operator does not only allow two dynamic dimensions in the shape argument.

**Comment by neso613** [comment] 2021-05-05 12:57
> @neso613 Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.
> 
> FYI, both TF and TFLite supports multiple dimensions but the Reshape operator does not only allow two dynamic dimensions in the shape argument.

Thats the Question.
TFLite supports dynamic input shape.
`[{'name': 'input_1', 'index': 0, 'shape': array([ 1,  1, 40], dtype=int32), 'shape_signature': array([-1, -1, 40], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

When I do inference, my input can be of any shape, so I have to resize using
`interpreter.resize_tensor_input(input_details[0]['index'],data_test.shape)`

**Comment by abattery** [comment] 2021-05-05 13:01
That is an intended behavior since the input tensors should be fixed through the resize_tensor_input method when the given model has dynamic inpiuts. You can resize input tensors again when the model should handle the different size in the following tasks.

**Comment by neso613** [comment] 2021-05-05 13:32
> That is an intended behavior since the input tensors should be fixed through the resize_tensor_input method when the given model has dynamic inpiuts. You can resize input tensors again when the model should handle a different size in the following tasks.

This is the code, I am using
`interpreter.resize_tensor_input(input_details[0]['index'],data_test.shape)
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]['index'], data_test)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])`

**Comment by abattery** [comment] 2021-05-05 13:48
@neso613 Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist. It is really impossible to reproduce your problem at our end and please consider the latest TF version from the conversion stage to the inference stage.

**Comment by gcervantes8** [comment] 2021-05-05 19:37
I have gotten a very similar error when converting models with TFLite and running with TensorFlow 2.4.  TensorFlow versions 2.3 and 2.5 pre-release work for me, I'd recommend trying these versions.

**Comment by neso613** [comment] 2021-05-11 12:47
I have tried TFv2.3 and TFnightly versions. None of them works for me.

**Comment by abattery** [comment] 2021-05-11 20:38
@neso613 Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist. It is really impossible to reproduce your problem at our end

**Comment by neso613** [comment] 2021-05-17 12:43
It is running now, but with Flex dependecny. Any solution for this flex issue?

**Comment by abattery** [comment] 2021-05-17 20:50
Please file a feature request for the Select TF ops by adding a new issue. Thanks.

**Closed by abattery** 2021-05-17 20:50 UTC
Labels: TF 2.4, comp:lite, stat:awaiting response, type:support
