### ISSUE TITLE
EMA's support for DistributionStrategy introduces worse performance

### ISSUE THREAD

**Issue by fanshiqing** [tensorflow/tensorflow#23291] opened 2018-10-26 09:19 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Cent OS 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: master
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.15
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 7.0
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

**Describe the current behavior**
This [PR](https://github.com/benjamintanweihao/tensorflow/commit/70af5e7ddcef853adb8af6355341bb8a97dcf736) add DistributionStrategy support to moving average APIs. However, **in MirroredStrategy**, this patch's implementation will introduce expensive MEMCPYPtoP cost, as `strategy.reduce(MEAN, value, v)` will eventually call strategy.broadcast(reduced, devices), and this get even worse when there are more devices used. Is this as expected as this implementation is just prepared for GENERAL distribution strategy? Thanks in advance.

**Comment by byronyi** [comment] 2018-10-26 10:41
I saw 

``TensorFlow version (use command below): 1.4``

in your checklist. I am not aware of publicly available TF-1.4 package that provides DistributionStrategy. Is this a mistake?

**Comment by fanshiqing** [comment] 2018-10-26 10:54
@byronyi Sorry for that typo, I have corrected it.

**Comment by byronyi** [comment] 2018-10-26 11:10
Better to give a git hash for easier reproducing.

**Comment by mrry** [comment] 2018-10-31 20:21
Reassigning this to Josh, since it's a distribution strategy issue.

**Comment by josh11b** [comment] 2018-10-31 23:44
Cross device communication does have some overhead, but is necessary for correctness when running distributed. What is the magnitude of the performance degradation?

**Comment by fanshiqing** [comment] 2018-11-01 12:15
@josh11b Let's take a translation model with was trained offline on one machine with four 1080Ti cards as an example, the consumption time of EMA related is about **20%** and this gets worse when there are more devices, which is really a huge overhead. 
More specifically, there overhead include addN, AssignSubVariableOp, MEMCPYPtoP which introduced by broadcast etc. And these are where we wish to do some job to optimize.

![image](https://user-images.githubusercontent.com/3927162/47850863-b6f32b00-de11-11e8-860b-cc69b5751175.png)

**Comment by yuefengz** [comment] 2018-11-01 22:58
@fanshiqing which broadcast are you looking at?

**Comment by fanshiqing** [comment] 2018-11-02 15:10
Yes, @yuefengz PR(#23396) fix the case when MirroredVariable comes and no reduce-mean-broadcast is performed, it's exactly fix the timeline as shown above.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:51
Nagging Assignee @yuefengz: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:57
Nagging Assignee @yuefengz: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Closed** 2018-12-09 06:00 UTC
Labels: comp:dist-strat
