### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.summary_op_util' has no attribute 'skip_summary'

### ISSUE THREAD

**Issue by skyzombie89** [tensorflow/tensorflow#30974] opened 2019-07-24 04:01 UTC
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
device:
- TensorFlow installed from (source or binary): i use pip
- TensorFlow version (use command below): 1.14
- Python version: i tried 3.7.3 and 3.6
- Bazel version (if compiling from source):  i dont know
- GCC/Compiler version (if compiling from source): i dont know
- CUDA/cuDNN version: 10.0
- GPU model and memory: 1070ti

i try to use TecoGAN (https://github.com/thunil/TecoGAN)

Traceback (most recent call last):
File "main.py", line 284, in 
Net = TecoGAN( rdata.s_inputs, rdata.s_targets, FLAGS )
File "/home/ksjin/바탕화면/TecoGAN-master/lib/Teco.py", line 500, in TecoGAN
gif_sum = [ gif_summary('LR', r_inputs, max_outputs=max_outputs, fps=3),
File "/home/ksjin/바탕화면/TecoGAN-master/lib/ops.py", line 507, in gif_summary
if summary_op_util.skip_summary():
AttributeError: module 'tensorflow.python.ops.summary_op_util' has no attribute 'skip_summary'

but i got this error  how can i fix it

**Comment by ravikyram** [comment] 2019-07-25 10:34
@skyzombie89 
In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-08-01 05:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-01 05:36 UTC
Labels: stat:awaiting response, type:support
