### ISSUE TITLE
Model Maker Object Detection Tutorial Bug

### ISSUE THREAD

**Issue by stist1111** [tensorflow/tensorflow#52255] opened 2021-10-05 07:39 UTC
I ran the Model Maker Object Detection Tutorial via Colab.
(https://colab.research.google.com/drive/1DhxMGuQ9ep9mrfDBrFBx47zmOeEOn9_W#scrollTo=qhl8lqVamEty)

However, a problem occurred in
 `model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)`.

```
Epoch 1/50
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-5-187f39c1697e> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
	 [[Func/cond/then/_3378/input/_6828/_56]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_96849]

Function call stack:
train_function -> train_function
```

Please solve this problem.

**Comment by mohantym** [comment] 2021-10-05 10:14
Hi @stist1111! 
Could you please the issue template ? it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by tykwon97** [comment] 2021-10-05 13:38
Thanks for the reply @mohanty


The issue template is as follows.

`https://colab.research.google.com/drive/1DhxMGuQ9ep9mrfDBrFBx47zmOeEOn9_W#scrollTo=qhl8lqVamEty`

We inadvertently did not allow access.
Since access is allowed, you can check the error by entering the link.

------------------------------------------------------------------------------------------------------------------------------------------
a problem occurred in

`model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data).`

```Epoch 1/50
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-5-187f39c1697e> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
	 [[Func/cond/then/_3378/input/_6828/_56]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_96849]

Function call stack:
train_function -> train_function```

**Comment by tykwon97** [comment] 2021-10-06 07:27
Hi @mohantym 
there's something I haven't said
An error occurs when running on gpu in colab, but no error occurs when running the same code through cpu

**Comment by mohantym** [comment] 2021-10-06 08:07
Ok @stist1111! Thanks for confirming that. Could you please look at  these similar issues .[ Link1](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in) .Could you please confirm the Tensorflow version,Cuda and Cudnn version too as It seems to be a Cuda mismatch issue while running  in GPU? Tested configurations can be found from [here](https://www.tensorflow.org/install/source#gpu). Thanks!

**Comment by mohantym** [comment] 2021-10-07 10:11
Could you please confirm  Tensorflow version ,Cuda and CuDNN version too?

**Comment by tykwon97** [comment] 2021-10-07 10:38
Thank you for answer. @mohantym
I use colab.
Is it possible to change the cuda and cudnn versions within colab?
I did a Google search and couldn't find it.


tf version : 2.5.0

Results using !nvidia-smi

```
Thu Oct  7 10:27:23 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Results using  !nvcc --version

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

**Comment by mohantym** [comment] 2021-10-08 02:31
Hi @stist1111 , I replicated this issue in [TF 2.5](https://colab.research.google.com/gist/mohantym/80f2d61ed8da3807d11942edf47ce527/model-maker-object-detection-tutorial.ipynb#scrollTo=CtdZ-JDwMimd) and resolved in [TF 2.6](https://colab.research.google.com/gist/mohantym/ea4213967e99463b798da29d65342b52/model-maker-object-detection-tutorial.ipynb#scrollTo=-BzCHLWJ6h7q) . 
Reference - https://www.tensorflow.org/lite/tutorials/model_maker_image_classification  ,Thanks!

**Comment by noxhsxrk** [comment] 2021-10-08 03:15
Thank you for answer. @mohantym
Using TF 2.6 can train without any errors 
But when the training is complete and export model by this code 

```
model.export(export_dir='.', export_format=[ExportFormat.TFLITE, ExportFormat.LABEL])
```
and run 

```
model.evaluate_tflite('model.tflite', test_data)
```
it caused an exception
```
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: required broadcastable shapes [Op:Mul]
```

**Comment by EdjeElectronics** [comment] 2021-10-16 18:14
I had the same problem, and @noxhsxrk's solution fixed it. Thanks!

**Comment by jeong-ah313** [comment] 2021-12-01 15:12
Please find the problem with my code! It runs when it is set to CPU.

https://colab.research.google.com/drive/1CIGbbRqEyPEJYGnXY2TLBuj4etWLgN6Z#scrollTo=xZKG8lRxPp2z&uniqifier=2

**Comment by jeong-ah313** [comment] 2021-12-01 15:40
@mohantym @noxhsxrk Please find the problem with my code! It runs when it is set to CPU...

https://colab.research.google.com/drive/1CIGbbRqEyPEJYGnXY2TLBuj4etWLgN6Z?usp=sharing

**Closed** 2021-12-15 07:37 UTC
Labels: type:bug, comp:lite, TF 2.5
