### ISSUE TITLE
AttributeError: module 'dataset_utils' has no attribute 'int64_list_feature'

### ISSUE THREAD

**Issue by Brayden1000** [tensorflow/tensorflow#36172] opened 2020-01-24 03:25 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no, it is code pulled off a website
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 x64
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command 2.1.0
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: 960m 4gb

**Describe the current behavior**
I am running this script that is below and I get this error, anyone have any help??

**Describe the expected behavior**
The script to run

**Code to reproduce the issue**
I run python then that location of the script

**Other info / logs**
2020-01-23 22:14:41.289298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Users\minec\Desktop\Robotics_stuff\TFconvert.py", line 90, in <module>
    xml_to_tf(PATH_TEST, PATH_RECORD_TEST)
  File "C:\Users\minec\Desktop\Robotics_stuff\TFconvert.py", line 82, in xml_to_tf
    'image/object/class/label': dataset_util.int64_list_feature(classes),
AttributeError: module 'dataset_utils' has no attribute 'int64_list_feature'

___________________________________________________________________________________________________________
# Importing all necessary libraries
import os
import sys
import xml.etree.ElementTree as ET
import tensorflow as tf
sys.path.append(r"C:\Python37\models\models-master\research\slim\datasets"); 
import dataset_utils as dataset_util

# This are the path to the datasets and to the output files.
# NEED TO BE UPDATED IN CASE THE DATASET CHANGES
PATH_TEST = "C:/Users/minec/Desktop/Robotics_stuff/FIRSTballDatabase/test/"
PATH_RECORD_TEST = "test2.record"
PATH_TRAIN = "C:/Users/minec/Desktop/Robotics_stuff/FIRSTballDatabase/train/"
PATH_RECORD_TRAIN = "train2.record"

IMAGE_EXT = ".jpg"
IMAGE_FORMAT = b'jpg'

# This function defines the different classes the dataset has and return a different number per each.
# NEED TO BE UPDATED IN CASE THE DATASET CHANGES
def class_text_to_int(row_label):
    if row_label == 'FIRSTball':
        return 1
    else:
        return 0

# Reads the xml and the images, and create the tf records files. 
def xml_to_tf(path_input, path_output):
    xml_list = []
    column_name = ['filename', 'width', 'height', 'class', 'xmin', 'ymin', 'xmax', 'ymax']

    writer = tf.io.TFRecordWriter(path_output)

    files = os.listdir(path_input)
    for file in files:
        if file.endswith(".xml"):
            xmlFile = path_input + file

            tree = ET.parse(xmlFile)
            root = tree.getroot()
            
            filename = root[1].text + IMAGE_EXT
            width = int(root[4][0].text)
            height = int(root[4][1].text)

            xmins = []
            xmaxs = []
            ymins = []
            ymaxs = []
            classes_text = []
            classes = []
            

            for member in root.findall('object'):
                beer = member[0].text
                xmin = int(member[4][0].text)
                ymin = int(member[4][1].text)
                xmax = int(member[4][2].text)
                ymax = int(member[4][3].text)
                
                xmins.append(xmin/width)
                xmaxs.append(xmax/width)
                ymins.append(ymin/height)
                ymaxs.append(ymax/height)
                classes_text.append(beer.encode('utf8'))
                classes.append(class_text_to_int(beer))

            with tf.io.gfile.GFile(os.path.join(path_input, '{}'.format(filename)), 'rb') as fid:
                encoded_jpg = fid.read()
            tf_example = tf.train.Example(features=tf.train.Features(feature={
                'image/height': dataset_util.int64_feature(height),
                'image/width': dataset_util.int64_feature(width),
                'image/filename': dataset_util.bytes_feature(filename.encode('utf8')),
                'image/source_id': dataset_util.bytes_feature(filename.encode('utf8')),
                'image/encoded': dataset_util.bytes_feature(encoded_jpg),
                'image/format': dataset_util.bytes_feature(IMAGE_FORMAT),
                'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
                'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
                'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
                'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
                'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
                'image/object/class/label': dataset_util.int64_list_feature(classes),
            }))
            
            writer.write(tf_example.SerializeToString())
    writer.close()             
    output_path = os.path.join(os.getcwd(), path_output)
    print('Successfully created the TFRecords: {}'.format(output_path))

xml_to_tf(PATH_TEST, PATH_RECORD_TEST)
xml_to_tf(PATH_TRAIN, PATH_RECORD_TRAIN)
___________________________________________________________________________________________________________
If anyone is able to help thanks!!

**Comment by ravikyram** [comment] 2020-01-24 13:34
@Brayden1000 
Can you please share colab link or simple standalone code along with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-02-10 11:57
@Brayden1000 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-02-20 10:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-20 10:43 UTC
Labels: TF 2.1, comp:data, stat:awaiting response, type:support
