### ISSUE TITLE
TF1 tf.image.resize_image does not work with unbatched variable size image anymore since 1.12

### ISSUE THREAD

**Issue by jejay** [tensorflow/tensorflow#38694] opened 2020-04-20 00:47 UTC
(Sorry for not adhering to the template, I can point to the problematic commit)

I use tf.image.resize_images to resize variable sized images in an unbatched manner, like so:

    tf.image.resize_images(
                tf.reshape(x, [-1, 100, 3]),
                size,
                method=tf.image.ResizeMethod.BILINEAR
            )

I.e. some images are 100x100, some 110x100 etc. Upon updating tensorflow I received the following error:

```
Traceback (most recent call last):
[...]
  File "data_preprocess_amass.py", line 32, in __init__
    method=tf.image.ResizeMethod.BILINEAR
  File "/mnt/HDD1/julian/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1187, in resize_images
    skip_resize_if_same=True)
  File "/mnt/HDD1/julian/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/image_ops_impl.py", line 1053, in _resize_images_common
    new_height_const = size_const_as_shape.dims[0].value
TypeError: 'NoneType' object is not subscriptable
```
I investigated it and it seems that the commit f43d458a318d4d97298710654f1692f6e8364f82 is the culprit, introducing the following lines to image_ops_impl.py:

    new_height_const = size_const_as_shape.dims[0].value
    new_width_const = size_const_as_shape.dims[1].value

blame: https://github.com/tensorflow/tensorflow/blame/r1.15/tensorflow/python/ops/image_ops_impl.py#L1053

It is included since 1.12.1. Downgrading to 1.11 solved it for me. Might be a very special use case on a already deprecated function but I thought its worth reporting.

**Comment by ravikyram** [comment] 2020-04-20 06:37
@jejay 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by jejay** [comment] 2020-04-27 10:27
No wait I'll do it, just give me some time I have a deadline end of the month.

**Comment by ravikyram** [comment] 2020-05-05 06:32
@jejay 

Any update on this issue please. Thanks!

**Comment by jejay** [comment] 2020-05-07 10:04
So its basically just the code I already presented:


```
import numpy as np
import tensorflow as tf

x = tf.placeholder(tf.float32)
size = tf.placeholder(tf.int32)

result = tf.image.resize_images(
    tf.reshape(x, [-1, 100, 3]),
    size,
    method=tf.image.ResizeMethod.BILINEAR)


session = tf.Session()
r = session.run(result, {
    x: np.random.normal(size=(100, 100, 3)),
    size: [20, 20]
})
```

works on pre 1.12 and fails afterwards with:
```
Traceback (most recent call last):
  File "py.py", line 10, in <module>
    method=tf.image.ResizeMethod.BILINEAR)
  File "[...]/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py", line 960, in resize_images
    name=None)
  File "[...]/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1041, in resize_images_v2
    new_height_const = size_const_as_shape.dims[0].value
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ravikyram** [comment] 2020-05-07 10:26
I have tried in colab and i am not seeing any issue with TF version <= 1.12 and i could reproduce the issue with TF version >1.12.Please,find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f3b22183898179523f0837b637d5ce47/untitled864.ipynb).Thanks!

**Comment by hyeygit** [comment] 2020-05-16 00:26
The issue was that the line with the error was not v1/v2 TensorShape backwards compatible. It should be fixed at head now. I’ve [verified](https://colab.research.google.com/drive/1C9_VBU-dSXnkabBLSUZWveylVQTzcfZK?usp=sharing#scrollTo=8r0M6AQoqXPK) it with tf-nightly version 2.3.0-dev20200515.

On older branches, we unfortunately need to wait until the next patch release to cherrypick it in (note: supported versions are 1.5, 2.0, 2.1, 2.2). If you need to work with TF versions >= 1.13 and <= 2.2, one interim possibility would be to build tf from source with the [two liner fix](https://github.com/UofT-EcoSystem/tensorflow/commit/24c75ce5016efb4ab107f27b96aac07549d8617b).

**Comment by saikumarchalla** [comment] 2020-10-18 15:01
@jejay  Closing this issue since it was resolved already. Please feel  free to reopen the issue in case of any concern. Thanks!

**Closed by saikumarchalla** 2020-10-18 15:01 UTC
Labels: comp:ops, stat:awaiting tensorflower, type:bug
