### ISSUE TITLE
Tensorflow installation from local drive

### ISSUE THREAD

**Issue by Sukhjitghuman** [tensorflow/tensorflow#556] opened 2015-12-19 09:18 UTC
Hi,
I am trying to install Tensorflow in windows machine using docker. It's a corporate connection and I am not able to connect to daemon for installation. If there any way where I can download tensorflow in my local drive and execute it from docker?

$ docker run -it b.gcr.io/tensorflow.tensorflow
Unable to find image 'b.gcr.io/tensorflow.tensorflow:latest' locally
Error response from daemon: unable to ping registry endpoint https://b.gcr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 74.125.68.
82:443: connection refused

Please help.

**Comment by pari125** [comment] 2015-12-22 14:50
Does your network has proxy?

**Comment by dixudx** [comment] 2016-02-15 05:43
refer to [docker issue 868](https://github.com/docker/distribution/issues/868)

**Comment by mrry** [comment] 2016-03-18 17:47
Closing this, since it seems related to proxy settings that we can't reproduce. Let us know if you have any more problems.

**Closed by mrry** 2016-03-18 17:47 UTC

**Comment by aaronyoung6** [comment] 2022-09-13 07:19
TensorFlow is a deep learning framework that provides an easy interface to a variety of functionalities, required to perform state of the art deep learning tasks such as image recognition, text classification and so on. [It](https://paintsvision.com/) is a machine learning framework developed by Google and is used for designing, building, and training of deep learning models such as the neural networks. 
When installing TensorFlow, you can choose either the CPU-only or GPU-supported version. I'd recommend to install the CPU version if you need to design and train simple machine learning models, or if you're just starting out. However, the CPU version can be slower while performing complex tasks, especially those involving image processing. If you need to use TensorFlow to process a huge amount of data, especially cases in which the data involves images, I'd recommend installing the GPU-supported version.

GPU supported TensorFlow requires you to install a number of libraries and drivers. It supports NVIDIA GPU card, with support for CUDA Compute 3.5 or higher.

You must install the following software in order to run the GPU version of TensorFlow:

    NVIDIA GPU drivers
    CUDA Toolkit: CUDA 9.0.
    NCCL 2.2 (optional)
    cuDNN SDK (7.2 or higher)
    TensorRT for improved latency and throughput.
