### ISSUE TITLE
CUDA 9.1 Support

### ISSUE THREAD

**Issue by StevenGann** [tensorflow/tensorflow#18961] opened 2018-04-29 08:56 UTC
I am using NVIDIA GeForce GTX 1050 and installed NVIDIA 388.19. I installed cuDNN 7.0.5 and CUDA 9.1. As of my understanding, I know that, tensorflow is not supported in CUDA 9.1. My question is when I can expect the next build/release of TF to support CUDA 9.1. For the time being, shall I make a link from CUDA 9.0 to CUDA 9.1 and expect to work? Or is there any better way to solve the problem?

**Comment by tensorflowbutler** [comment] 2018-04-29 18:29
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ntenenz** [comment] 2018-04-29 18:49
@StevenGann, this is addressed in #15140. The tentative plan, AFAIK, is to move to 9.2 w/TF 1.9. See #18906 for the latest.

**Comment by tensorflowbutler** [comment] 2018-05-14 18:59
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jhmenke** [comment] 2018-06-06 12:28
still does not work on 1.8.0 Windows

**Closed** 2018-06-21 18:55 UTC
Labels: stat:awaiting response

**Comment by tensorflowbutler** [comment] 2018-06-21 18:56
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by fenix7** [comment] 2018-07-23 16:12
for me its also an issue the problem should stay open  because the is not easy solution

**Comment by jotes35** [comment] 2018-10-22 12:16
Hi.
I installed tensorflow gpu on an HPC server, I have installed the dependencies cudnn and cuda 9.1. But when i import tensorflow it get an error. I read that tensorflow-gpu installed via pip does not support cuda 9.1. Could that be the issue here? The error message is below

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by benn94** [comment] 2018-10-25 02:42
Same here. I have multiple version of cuda 7.5, 8.0, 9.1 They are working fine for various projects. 
I have tried installing 9.0 without installing driver and the geforce experience. It's still failed. It would be nice if someone could help me.

**Comment by jotes35** [comment] 2018-10-27 18:48
I solved my issue. I just installed CUDA 9.0 to a different directory. 

And before i import tensorflow i make sure to set my PATH to add cuda 9.0. After doing that i get no error when i run tensorflow gpu
