### ISSUE TITLE
Tensorflow lite version 0.1.7 is too slow

### ISSUE THREAD

**Issue by Dabin22** [tensorflow/tensorflow#18915] opened 2018-04-27 05:09 UTC
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: android
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: no
- **Python version**: no
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: no

I used the Tensor Flowlight library on my device. Until then, the operation speed was 300ms. However, it took more than a second after using the 0.1.7 version of the Tensor Flow Lite version released this week. If i use the current 0.0.0-nightly version, it takes 300ms again. The question is whether or not you have removed the option that the 0.1.7 version of the library uses neon.

Ask https://bintray.com/google/tensorflow/tensorflow-lite to post your question here and upload it here. Even if it does not fit the form, please understand and ask for confirmation.

**Comment by andrehentz** [comment] 2018-04-27 14:32
We are investigating. There were no changes to remove neon support. Do you have custom inference code or are you running benchmark_model?

**Comment by shashishekhar** [comment] 2018-04-27 20:44
There was a bug in the schema where the default values of dilation width and height factors were set to 0 instead of 1. This incorrect value will cause the slow kernel to be selected for execution.
This got fixed with recent update to [schema](https://github.com/tensorflow/tensorflow/commit/e41e70ed9827b81a07c42f68def80f3f61b70375#diff-16ca4f2738c3598cf9b1d79b45eed593), that is the reason you saw the regression in 0.1.7 version.

**Closed by shashishekhar** 2018-04-27 20:44 UTC
