### ISSUE TITLE
[feature] sparse_multiply

### ISSUE THREAD

**Issue by asiakaczmar** [tensorflow/tensorflow#10003] opened 2017-05-18 12:08 UTC
Hi guys,

We'd like to ask if it's possible to add sparse_multiply and sparse_multiply_sparse as a sparse equivalent to existing tf.multiply but for SparseTensor arguments and both Tensor and SparseTensor result.

Thank you,

Joanna

**Comment by ali01** [comment] 2017-05-20 01:05
Thanks for the suggestion @asiakaczmar! Marking this as "Contributions Welcome" for now.

**Comment by cfperez** [comment] 2017-05-30 22:21
Is the request for the equivalent of
```
from functools import partial
sparse_multiply = partial(tf.multiply, a_is_sparse)
```
and similarly for `sparse_multiply_sparse`?

**Comment by asiakaczmar** [comment] 2017-06-01 08:51
Thank you for replying! As far as we know tf.multiply requires both a and b to be Tensors and we would like it to accept SparseTensor (possibly as one or both arguments, we could work with either). We couldn't find a_is_sparse flag in tf.multiply documentation (nor source, but it could be hidden somewhere). Also sparse_multiply would return Tensor as result, but sparse_multiply_sparse would return SparseTensor (similarly to existing tf.sparse_reduce_sum and tf.sparse_reduce_sum_sparse).

**Comment by shawnjhenry** [comment] 2017-06-01 17:55
I would like to have this feature as well, with the caveat that sparse multiplied element-wise with dense is always sparse, and so should be returned as such.  This can make a huge difference in some use cases, for example if you wanted to multiply every row in a huge sparse matrix by the same dense vector element-wise.  If that operation returned a dense tensor there could easily be memory issues.  Scipy recently switched the result of sparse x dense element-wise to return sparse by default because a lot of people complained about this.

**Comment by tjingrant** [comment] 2017-07-07 18:09
Hi, so by reading up the code, I've found out that as @asiakaczmar pointed out, there is no `a_is_sparse` option in the implementation of multiply as in [link](https://github.com/tensorflow/tensorflow/blob/cf18c6d384a96a53b448bd51a90c117af0ed7c96/tensorflow/python/ops/math_ops.py#L304). However, there is indeed the option of specifying `a_is_sparse` option in the implementation of `matmul` as in [link](https://github.com/tensorflow/tensorflow/blob/cf18c6d384a96a53b448bd51a90c117af0ed7c96/tensorflow/python/ops/math_ops.py#L1686). I might be missing something, @cfperez can you make sure if `matmul` is what you mean instead of `multiply` in your comment?

As I read through relevant sections of code related to sparse tensor multiplication, I see quite a bit of confusion surrounding what the word `sparse` actually mean both in the code and in people's comments. A comment by @concretevitamin in #3246 suggests that `a_is_sparse` or `b_is_sparse` does not specify that the input tensor is a SparseTensor; rather, it provides algorithmic hints suggesting that the input dense tensor contains large portion of zeros. Moreoever, the `sparse_matmul` function seems to follow suite on this line of thinking and in [here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/ops/math_ops.py#L1821), the implementation suggests that it essentially performs the same operation as `multiply` do with sparse hints turned on. That is to say, the behavior described in #3246 is expected in order to remain consistent about what the word `sparse` means in the context of tensorflow. 

However, the problem is that what `sparse` means somehow fluctuates depending on which function you are in. For instance, the documentation indicates that `sparse_transpose` and `sparse_reduce_sum` take SparseTensor as inputs, which seems to contradicts the definition of `sparse` as seen in `multiply` or `sparse_matmul`. So, in light of the splitting definition of `sparse`, I would like to ask for opinions on how would sparse-sparse matrix multiplication fit into the picture. 

The most logical thing to do, in my opinion, is to implement in `math_ops.py` another function called `sparse_tensor_sparse_tensor_matmul` (the naming follows from `sparse_tensor_dense_matmul`).

**Closed** 2017-08-14 23:52 UTC
Labels: stat:contributions welcome, type:feature
