### ISSUE TITLE
Timeseries example is not working with latest 2.4 code

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#42016] opened 2020-08-04 02:53 UTC
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/time_series.ipynb

When it comes to Convolution model, this errors out.
===code===
history = compile_and_fit(conv_model, conv_window)

IPython.display.clear_output()
val_performance['Conv'] = conv_model.evaluate(conv_window.val)
performance['Conv'] = conv_model.evaluate(conv_window.test, verbose=0)
==============
===error====
NotFoundError:  No algorithm worked!
	 [[node sequential_3/conv1d/conv1d (defined at <ipython-input-41-716049f06cb3>:12) ]] [Op:__inference_train_function_127129]

Function call stack:
train_function

**Comment by Saduf2019** [comment] 2020-08-04 10:19
Closing this as duplicate of #41987

**Closed by Saduf2019** 2020-08-04 10:19 UTC
