### ISSUE TITLE
python3.4 doesn't works well?

### ISSUE THREAD

**Issue by andyyuan78** [tensorflow/tensorflow#1474] opened 2016-03-12 10:09 UTC
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

ubuntu 14.04

envy@ub1404:~/os_pri/github/tensorflow$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux

If installed from sources, provide the commit hash:
envy@ub1404:~/os_pri/github/tensorflow$ git log
commit 639d48f1f225e5dba865a5eeef513dbe88d6470e
Merge: aea1bf5 993c77d
Author: Manjunath Kudlur <keveman@gmail.com>
Date:   Mon Feb 22 21:28:30 2016 -0800

    Merge pull request #1207 from dongjoon-hyun/avoid_copying_invalid_large_constant_data.

### Steps to reproduce
1.
import tensorflow

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
envy@ub1404:~/os_pri/github/tensorflow-deepq$ PYTHONPATH=~/os_pri/github/tensorflow-deepq:$PYTHONPATH python3 
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow import contrib
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/contrib/__init__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/contrib/layers/__init__.py", line 67, in <module>
    from tensorflow.contrib.layers.python.framework.tensor_util import *
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/contrib/layers/python/framework/tensor_util.py", line 21, in <module>
    from tensorflow.python.framework.ops import Tensor
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.framework import versions
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/framework/versions.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /home/envy/os_pri/github/tensorflow/_python3_build/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyClass_Type
>>>

**Comment by mrry** [comment] 2016-03-14 15:19
This problem doesn't seem to be happening with the [nightly build for Python 3](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=cpu-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py3-none-any.whl), and it looks like you're using an old snapshot of the tree from February 22nd. Can you try again with the latest HEAD?

**Comment by mrry** [comment] 2016-03-18 17:44
I'm going to close this for now, since we can't reproduce. Let us know if you still have a problem with the up-to-date code.

**Closed by mrry** 2016-03-18 17:44 UTC
Labels: installation/startup
