### ISSUE TITLE
FutureWarning in TensorFlow 1.14 after NumPy update.

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#32553] opened 2019-09-16 12:00 UTC
System information:
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
    TensorFlow installed from (source or binary): binaries from pip
    TensorFlow version (use command below):1.14
    Python version: 3.6.1
    CUDA/cuDNN version: 10.0 with any 7.5.0
    GPU model and memory: Geforce RTX 2060

After updating the NumPy to the latest version (1.17.2+mkl),
I receive the following warnings in TensorFlow 1.14:

```
2019-09-16T13:46:07.976+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:07.976+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:07.977+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:07.977+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:07.977+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:07.977+0200	WARNING	C:\python\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.194+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.194+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.195+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.195+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.195+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
	py.warnings:99
```
```
2019-09-16T13:46:09.195+0200	WARNING	C:\python\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
	py.warnings:99
```

**Comment by gadagashwini** [comment] 2019-09-17 06:41
@kiflowb777, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by alanhdu** [comment] 2019-09-19 20:26
I believe this is closed by 3402d711846

**Comment by gadagashwini** [comment] 2019-10-03 09:55
@kiflowb777, Associated PR has been merged. Let us know if the problem still persists. Thanks!

**Comment by gadagashwini** [comment] 2019-10-14 10:38
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!

**Closed by gadagashwini** 2019-10-14 10:38 UTC
Labels: TF 1.14, stat:awaiting response, type:bug
