### ISSUE TITLE
TensorFlowLiteSwift nightly build running 40 times slower than stable release build (on iPhone)

### ISSUE THREAD

**Issue by unarmedman** [tensorflow/tensorflow#40521] opened 2020-06-16 20:37 UTC
**System information**
   - Using TensorFlowLiteSwift iOS ObjectDetection example project
   - OS Platform and Distribution: iOS 13.5.1
   - Mobile device: iPhone 11 and other older iPhones
   - TensorFlow installed from binary
   - TensorFlow version: TensorFlowLiteSwift 0.0.1-nightly20200611

**Describe the current behavior**
   - With nightly build, we see 3330ms inference times

**Describe the expected behavior**
   - With stable release build, we see 80ms inference times

**Steps to reproduce the issue**
   1. Clone the TensorFlow Lite ObjectDetection iOS example repo
   2. Run and see inferences averaging 80ms on iPhone 11 (up to 250ms on older iPhones)
   3. Edit podfile, changing:
         pod 'TensorFlowLiteSwift'
      to
         pod 'TensorFlowLiteSwift', '-> 0.0.1-nightly'
   4. pod update
   5. Run and see inferences averaging 3330ms on iPhone 11 (up to 9000ms on older iPhones)

**Comment by yyoon** [comment] 2020-06-22 06:15
@unarmedman Thanks for reporting. I can see that happening on the exact version you mentioned (`0.0.1-nightly.20200611`), but when I tried a more recent nightly build (`0.0.1-nightly.20200621`) the it seems to be fixed.

Can you try `pod update --repo-update` and see if it resolves the issue?

**Comment by yyoon** [comment] 2020-06-23 11:32
I can confirm that there was a performance regression issue exactly on 6/11, which got fixed the next day, so let me close this issue. If you are still seeing the issue after `pod update`, feel free to reopen.

**Closed by yyoon** 2020-06-23 11:32 UTC
Labels: comp:lite, stat:awaiting response, type:performance

**Comment by unarmedman** [comment] 2020-06-24 06:36
thx yyoon.  I guess I was just unlucky trying it that day.  works now :)
