### ISSUE TITLE
run this:python freeze_graph.py \ --input_graph C:/Users/Administrator.DESKTOP-5V6G6NA/tensorflowfiles/bird\data2/slim/tmp/inception_v3_inf_graph.pb \ --input_checkpoint .tmp/train_logs/model.ckpt-721 \ --input_binary true \ --output_node_names InceptionV3/Predictions/Reshape_1 \ --output_graph .tmp/frozen_graph.pb

### ISSUE THREAD

**Issue by lucyLLLL** [tensorflow/tensorflow#40090] opened 2020-06-02 15:38 UTC
WARNING:tensorflow:From freeze_graph.py:124: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0602 23:33:08.629297 12556 deprecation.py:323] From freeze_graph.py:124: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Fatal Python error: Segmentation fault

Current thread 0x0000310c (most recent call first):
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 384 in get_matching_files_v2
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 363 in get_matching_files
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 372 in checkpoint_exists
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 324 in new_func
  File "freeze_graph.py", line 124 in freeze_graph_with_def_protos
  File "freeze_graph.py", line 357 in freeze_graph
  File "freeze_graph.py", line 374 in main
  File "freeze_graph.py", line 482 in <lambda>
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250 in _run_main
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299 in run
  File "D:\91UserData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "freeze_graph.py", line 483 in run_main
  File "freeze_graph.py", line 487 in <module>

get this error;
tf=1.14.0 cpu

**Comment by ravikyram** [comment] 2020-06-02 16:21
@lucyLLLL 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by lucyLLLL** [comment] 2020-06-02 16:40
windows10，tensorflow=1.14.0，cpu，
dataset is flowers
use slim Module
i learn from this [https://blog.csdn.net/stesha_chen/article/details/81976415?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.nonecase&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.nonecase]

because  inception_v3_inf_graph.pb only saves the network structure of Inception V3, and does not contain the model parameters obtained by training. You need to save the model parameters in checkpoint. so  i  use freeze_graph.py the error is appear

**Comment by ravikyram** [comment] 2020-06-02 16:53
@lucyLLLL 

I believe you are using https://github.com/tensorflow/models/tree/master/research/slim models.

This issue is more suitable for TensorFlow Models repo. Please post it on Models repo from [here.](https://github.com/tensorflow/models/issues) Thanks!

**Comment by lucyLLLL** [comment] 2020-06-03 02:21
the code is [https://github.com/lucyLLLL/slim-flowers.git],thank you for your help @ravikyram

**Comment by ravikyram** [comment] 2020-06-03 06:36
@lucyLLLL 

Can we close this issue here and can be tracked in Models repo?.Thanks!

**Comment by ravikyram** [comment] 2020-06-16 05:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-16 05:50 UTC
Labels: TF 1.14, comp:model, type:bug
