### ISSUE TITLE
TF 1.8-gpu runs on only one Ubuntu 18.04 account

### ISSUE THREAD

**Issue by bwllc** [tensorflow/tensorflow#21029] opened 2018-07-22 10:19 UTC
About six months ago I succeeded in installing TF 1.4.0-gpu on top of Ubuntu 17.10.  I have multiple user accounts on the system, and I needed all accounts to have TF access.  TF needed to be accessible whether the Python script was launched from a terminal or from a GUI.  The procedure that worked for me was documented [here](https://ubuntuforums.org/showthread.php?t=2386704).

I decided to upgrade to Ubuntu 18.04 and TF 1.8.0-gpu.  The installation procedure I followed was essentially the same as shown above.  My primary account has full access to TF, and is functioning normally.  However, the secondary account (which has admin privileges) is unable to load TF.  I get this:

> Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> ˃˃˃ import tensorflow as tf
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/usr/lib/python3.6/imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/usr/lib/python3.6/imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

I searched for libcublas.so* files on my system.  The screenshot of the search result is attached.  I don't have 8.0 files.  I do have 9.0 and 9.1 files, I'm not sure how I ended up with both.  I have what appear to be manual pages with a version 7 suffix.

My main account is not looking for libcublas.so.8.0.  My secondary account is.  Any thoughts as to why?  I reviewed my .bashrc and .profile in each account for discrepancies.  I have none.  The modifications that I make to /etc/profile and ldconfig should be shared between all accounts on the system.

**Comment by tensorflowbutler** [comment] 2018-07-23 21:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by bwllc** [comment] 2018-07-24 05:34
The "TensorFlow Butler" prompt made me check the issue template.  I tried a `pip3 list` in both my active accounts.  The working account showed TF 1.8.0.  The non-working account showed TF 1.4.0, which must have been a hold-over from my Ubuntu 17.10 configuration.  Uninstalling TF 1.4 and then executing `sudo pip3 install tensorflow-gpu==1.8` from the secondary account got me working again.

Perhaps this is an issue with `pip`, and not with TensorFlow itself?  I thought using `sudo` with `pip3` would install a package for all users.  Perhaps it does not.  Feel free to close this issue if you think there's nothing more to discuss.

**Comment by gunan** [comment] 2018-07-29 21:38
This looks to be an issue with pip.
Did you try "sudo pip...." That lets you change system libraries, rather than only your own.
Moreover, it looks like you need to set LD_LIBRARY_PATH for all accounts on your system.
You can try looking at this:
https://www.google.com/search?q=LD_LIBRARY_PATH+ubuntu+system&oq=LD_LIBRARY_PATH+ubuntu+system&aqs=chrome..69i64j0l2j69i57.6390j0j7&sourceid=chrome&ie=UTF-8

Closing, as this is a pip and CUDA installation issue.

**Closed by gunan** 2018-07-29 21:38 UTC
