### ISSUE TITLE
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

### ISSUE THREAD

**Issue by GodsDusk** [tensorflow/tensorflow#34350] opened 2019-11-17 06:56 UTC
when I convert pre-trained mobilenet model to tflite, there is a error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/project/pyenv/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 400, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

my code is

```python 
import tensorflow as tf
from tensorflow.keras.applications.mobilenet import MobileNet
model = MobileNet(weights='imagenet')
saved_model_path = "./saved_models/{}".format(int(time.time()))
tf.keras.experimental.export_saved_model(model, saved_model_path)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
```

my os is 
Ubuntu 16.04.6 LTS

**Comment by gargn** [comment] 2019-11-19 01:32
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by GodsDusk** [comment] 2019-11-19 02:25
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

I use both Ubuntu 16.04.6 LTS x_86 and macOS Mojave x_64, there is same error.
and I use python virtualenv and pip command to install tensorflow2.0

**Comment by gargn** [comment] 2019-11-19 02:33
Can you use `tf.keras.models.save_model` instead. `tf.keras.experimental.export_saved_model` has been [deprecated](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model). I was able to get the following code working on `tf-nightly` (version: `2.1.0.dev20191118`).

```
import tensorflow as tf
from tensorflow.keras.applications.mobilenet import MobileNet
model = MobileNet(weights='imagenet')
saved_model_path = "/tmp/saved_models/"
tf.keras.models.save_model(model, saved_model_path)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
tflite_model = converter.convert()
```

**Comment by GodsDusk** [comment] 2019-11-19 03:00
> Can you use `tf.keras.models.save_model` instead. `tf.keras.experimental.export_saved_model` has been [deprecated](https://www.tensorflow.org/api_docs/python/tf/keras/experimental/export_saved_model). I was able to get the following code working on `tf-nightly` (version: `2.1.0.dev20191118`).
> 
> ```
> import tensorflow as tf
> from tensorflow.keras.applications.mobilenet import MobileNet
> model = MobileNet(weights='imagenet')
> saved_model_path = "/tmp/saved_models/"
> tf.keras.models.save_model(model, saved_model_path)
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
> tflite_model = converter.convert()
> ```

it works, thanks

**Comment by skulhare** [comment] 2019-11-21 21:17
Hi, I am getting the same error : 
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 421
in convert
raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

I am trying to convert SSD_ResNet50_fpn architecture with tf-nighty version. 

Thanks in advance.

**Comment by titanbender** [comment] 2019-11-22 13:15
I'm having the same issue as @skulhare

**Comment by mlinxiang** [comment] 2019-12-04 15:19
the same issue when convert deeplab mobilenetv2 version.

**Comment by alexanderfrey** [comment] 2020-01-03 09:14
having the same issue when trying to convert efficientnet_edge

**Comment by trayanmomkov** [comment] 2020-01-18 19:24
The same problem when trying to convert saved **DNNClassifier estimator** model.
(Sorry for the formatting)

TensorFlow version:  2.0.0

def construct_feature_columns():
    return set([tf.feature_column.numeric_column('pixels', shape=NUMBER_OF_PIXELS)])
...

my_optimizer = partial(tf.optimizers.Adam, learning_rate=learning_rate, clipnorm=5.0)
classifier = tf.estimator.DNNClassifier(
    feature_columns=construct_feature_columns(),
    n_classes=NUMBER_OF_CLASSES,
    hidden_units=hidden_units,
    optimizer=my_optimizer,
    config=tf.estimator.RunConfig(keep_checkpoint_max=1),
    model_dir=MODEL_DIR
)
...

for period in range(0, periods):
    classifier.train(
        input_fn=training_input_fn,
        steps=steps_per_period
    )
...

serving_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
            tf.feature_column.make_parse_example_spec(construct_feature_columns()))
saved_model_path = classifier.export_saved_model(MAIN_DIR + 'saved_models/', serving_input_fn)
...

converter = tf.lite.TFLiteConverter.from_saved_model(MAIN_DIR + 'saved_models/1579340040')
tflite_model = converter.convert()

===============================
WARNING:tensorflow:From /home/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/home/venv/tf_lite_converter.py", line 5, in <module>
    tflite_model = converter.convert()
  File "/home/venv/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 400, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

**Comment by gargn** [comment] 2020-01-21 17:19
There is documentation on concrete functions [here](https://www.tensorflow.org/guide/concrete_function). You will need to use `TFLiteConverter.from_concrete_function` directly. There is an example of how to do that [here](https://github.com/tensorflow/tensorflow/issues/35736#issuecomment-573814435).

**Comment by trayanmomkov** [comment] 2020-01-21 22:32
@gargn thank you for your answer!
I've read concrete_function documentation and tried the code from your comment:
```python
# Load the SavedModel.
saved_model_obj = tf.saved_model.load(export_dir=saved_model_dir)

# Load the specific concrete function from the SavedModel.
concrete_func = saved_model_obj.signatures['serving_default']

# Set the shape of the input in the concrete function.
concrete_func.inputs[0].set_shape([])

# Convert the model to a TFLite model.
converter =  tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.optimizations =  [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```
It returns:
```
ValueError: Shapes must be equal rank, but are 1 and 0
```
If I try with `concrete_func.inputs[0].set_shape([1024])` for example it says:
```
2020-01-22 00:16:54.071217: F tensorflow/lite/toco/import_tensorflow.cc:2690] Check failed: status.ok() Input_content string_val doesn't have the right dimensions for this string tensor
```
As far as I understand you save only one concrete_function with the following code:
```python
# Generate concrete function.
root = Pow(3)
concrete_func = root.__call__.get_concrete_function(tf.constant(2.))
# Save the generated concrete function as a SavedModel.
saved_model_dir = '/tmp/pow'
tf.saved_model.save(root, saved_model_dir, signatures=concrete_func)
```
But how to get a concrete_function, to save, from a DNNClasiffier estimator?
```python
def construct_feature_columns():
return set([tf.feature_column.numeric_column('pixels', shape=NUMBER_OF_PIXELS)])

classifier = tf.estimator.DNNClassifier(...)

serving_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
tf.feature_column.make_parse_example_spec(construct_feature_columns()))

saved_model_path = classifier.export_saved_model(MAIN_DIR + 'saved_models/', serving_input_fn)
```

**Comment by gargn** [comment] 2020-01-21 22:42
For the first code snippet, try removing the `concrete_func.inputs[0].set_shape([])` line. That was only necessary because the user in the previous example wanted to set the shape of their input. For your conversion, let's assume it is correct. If that still leads to an error, then can you add `converter.experimental_new_converter = True` since that converter supports more use cases.

For the last code snippet, try printing out `saved_model_obj.signatures.keys()` (the `saved_model_obj` is from the first snippet). Each of the keys is a signature that maps to a concrete function. Usually you want to use the one with `serve` in it.

**Comment by trayanmomkov** [comment] 2020-01-22 09:36
If I remove `concrete_func.inputs[0].set_shape([])` the error is:
```
2020-01-22 10:21:41.306469: F tensorflow/lite/toco/import_tensorflow.cc:2690] Check failed: status.ok() Input_content string_val doesn't have the right dimensions for this string tensor
	 (while processing node 'head/AsString')
Fatal Python error: Aborted
```
When add `converter.experimental_new_converter = True` the error is:
```
error: failed while converting: 'main'
Ops that need custom implementation (enabled via setting the -emit-custom-ops flag): ParseExampleV2
tensorflow_core/python/saved_model/load.py:559:7: error: 'tf.ParseExampleV2' op is neither a custom op nor a flex op
      root = load_v1_in_v2.load(export_dir, tags)
```
Here are the signatures (I need "predict" I guess?):
```python
print(saved_model_obj.signatures.keys())
KeysView(_SignatureMap({
'serving_default': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x7f2ea00c6a20>,
'predict': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x7f2ea00ebda0>,
'classification': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x7f2ea00989b0>,
'regression': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x7f2ea003fd30>}))
```

Maybe the model is not correctly saved?
Here is how I create DNNClassifier estimator and save the model:
```python
classifier = tf.estimator.DNNClassifier(
    feature_columns=[tf.feature_column.numeric_column('pixels', shape=1024)],
    n_classes=2,
    hidden_units=[1024, 1024, 1024],
    optimizer=partial(tf.optimizers.Adam, learning_rate=0.000001, clipnorm=5.0),
    config=tf.estimator.RunConfig(keep_checkpoint_max=1),
    model_dir=MODEL_DIR

# Training
for period in range(0, periods):
    classifier.train(
        input_fn=create_training_input_fn(training_examples,
                                          training_targets,
                                          batch_size),
        steps=steps_per_period
    )

    # Take a break and compute probabilities.
    training_predictions = list(classifier.predict(
        input_fn=create_predict_input_fn(training_examples,
                                         training_targets,
                                         batch_size)))
    ...


# Saving the model
serving_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
    tf.feature_column.make_parse_example_spec(
        [tf.feature_column.numeric_column('pixels', shape=1024)]))

classifier.export_saved_model(MAIN_DIR + 'saved_models/', serving_input_fn)


def create_training_input_fn(features, labels, batch_size):
    def _input_fn(num_epochs=None, shuffle=True):
        rand = np.random.RandomState(28)
        idx = rand.permutation(features.index)
        raw_features = {"pixels": features.reindex(idx)}
        raw_targets = np.array(labels[idx])

        ds = Dataset.from_tensor_slices((raw_features, raw_targets))
        ds = ds.batch(batch_size).repeat(num_epochs)

        if shuffle:
            ds = ds.shuffle(buffer_size=NUMBER_OF_IMAGES, seed=28)

        # Return the next batch of data.
        feature_batch, label_batch = ds.make_one_shot_iterator().get_next()
        return feature_batch, label_batch

    return _input_fn


def create_predict_input_fn(features, labels, batch_size):
    def _input_fn():
        raw_features = {"pixels": features.values}
        raw_targets = np.array(labels)

        ds = Dataset.from_tensor_slices((raw_features, raw_targets))
        ds = ds.batch(batch_size)

        # Return the next batch of data.
        feature_batch, label_batch = ds.make_one_shot_iterator().get_next()
        return feature_batch, label_batch

    return _input_fn
```

**Comment by gargn** [comment] 2020-01-28 00:48
First off, I recommend using `experimental_new_converter` given that the older converter seems to be resulting in additional errors. With the new converter, it becomes clear that your example uses an unsupported operation - `tf.ParseExampleV2`.

Given that `tf.ParseExampleV2` is not supported as a built-in op in TFLite your options are to:
1. Remove `tf.ParseExampleV2` from your graph.
2. Implement `tf.ParseExampleV2` as a custom operation.
3. [Recommended] Use TF Select ops. If you download tomorrow's `tf-nightly` (released on 01-28 PST), I have added `ParseExampleV2` to the [TF Select ops](https://www.tensorflow.org/lite/guide/ops_select).

Assuming you choose option #3 (which will the easiest but will lead to a binary size increase), you should use the following flags during conversion:
```
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
```

If the suggestion does not fix your issue, can you provide a fully reproducible example with the imports and the conversion code. The example you provided had some errors, so I was not able to run it in order to debug the code.

**Comment by trayanmomkov** [comment] 2020-01-29 12:56
Thank you @gargn!
I've added the 'supported_ops' and conversion passed without errors. Here is the final code.
```Python
        # TensorFlow version:  2.2.0-dev20200128
        # Load the SavedModel.
        saved_model_obj = tf.saved_model.load(export_dir=saved_model_dir)
        print(saved_model_obj.signatures.keys())

        # Load the specific concrete function from the SavedModel.
        concrete_func = saved_model_obj.signatures['serving_default']

        # Set the shape of the input in the concrete function.
        # concrete_func.inputs[0].set_shape([])

        # Convert the model to a TFLite model.
        converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.experimental_new_converter = True
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
        tflite_model = converter.convert()

        open("converted.tflite", "wb").write(tflite_model)
```
Now there is a problem when try to infer: **"Node number 0 (FlexParseExampleV2) failed to prepare"**
```Python
    dataframe = pd.read_csv('file:////training_data_sample.csv', sep=",", header=None)
    features = dataframe.loc[0, 1:]
    features = features / 255

    # Load TFLite model and allocate tensors.
    interpreter = tf.lite.Interpreter(model_path="/converted.tflite")
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Test model.
    input_shape = input_details[0]['shape']
    input_data = np.array(features, dtype=np.float32)
    input_data = np.reshape(input_data, input_shape)
    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke()

    output_data = interpreter.get_tensor(output_details[0]['index'])
    results = np.squeeze(output_data)
    print(results)
```
```
TensorFlow version:  2.2.0-dev20200128
Traceback (most recent call last):
  File "/home/PycharmProjects/ML/test_tflite_file.py", line 15, in <module>
    interpreter.allocate_tensors()
  File "/home/PycharmProjects/ML/venv/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/PycharmProjects/ML/venv/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 0 (FlexParseExampleV2) failed to prepare.

Process finished with exit code 1
```
I should apply "Flex delegate" somehow, I guess?

**Comment by gargn** [comment] 2020-01-31 15:38
Unfortunately, models converted with TensorFlow select ops cannot be run in Python interpreters. There is more information on running your model available [here](https://www.tensorflow.org/lite/guide/ops_select#running_the_model).

**Comment by trayanmomkov** [comment] 2020-02-04 19:13
Thank you @gargn! You helped a lot!
Maybe we can close the issue now?
My fight to run the model on an Android device continue! \m/

**Closed** 2020-02-04 19:14 UTC

**Comment by raghavgurbaxani** [comment] 2020-05-01 01:46
@gargn @trayanmomkov 
I am getting the same error and I tried the code snippet provided above, however my KeysView(_SignatureMap({})) is empty and I get `KeyError: 'serving_default¸`.

How do I get around this ? 

I am trying to quantize my .pb file obtained from my checkpoints using this script 
https://blog.csdn.net/zmlovelx/article/details/100511406

**Comment by manmay-nakhashi** [comment] 2020-06-05 08:43
> @gargn @trayanmomkov
> I am getting the same error and I tried the code snippet provided above, however my KeysView(_SignatureMap({})) is empty and I get `KeyError: 'serving_default¸`.
> 
> How do I get around this ?
> 
> I am trying to quantize my .pb file obtained from my checkpoints using this script
> https://blog.csdn.net/zmlovelx/article/details/100511406

me too
