### ISSUE TITLE
Big bug, tf.keras is slower then keras.

### ISSUE THREAD

**Issue by tsing-cv** [tensorflow/tensorflow#29049] opened 2019-05-27 09:02 UTC
I just change all keras api to tf.keras. But training become too slower, gpu is usable

**Comment by achandraa** [comment] 2019-05-28 10:26
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact minimal code snippet to reproduce the issue reported. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tsing-cv** [comment] 2019-05-28 14:19
`https://github.com/tsing-cv/tf.keras_Mask_rcnn`
I didnt change anything, but instead of all keras api. 
The performance drops down, and training is very very slow.
@achandraa

**Comment by achandraa** [comment] 2019-05-29 06:39
Can we have the details about the platform you are using (operating system, architecture). Also let us know which TensorFlow version you are using, whether you compiled it using source or installed using binary and your CUDA/cuDNN, GPU information. This will help us to dig further and proceed easily. Thanks!

**Comment by tsing-cv** [comment] 2019-05-29 07:23
···
ubuntu18.04
TITAN RTX 24G
cuda 10.0
cudnn 7.3.1
INVIDIA driver 418.43
tensorflow 1.12 or 1.13.1
keras 2.2.4
···

**Comment by ymodak** [comment] 2019-05-29 23:15
Can you please use profiling tool and help us figure out what operations consume most time in computing? Thanks!

**Comment by tsing-cv** [comment] 2019-06-03 02:55
OK, I will take a few hours to use this tool, to address the wasting time ops.

**Comment by ymodak** [comment] 2019-06-07 21:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-06-07 21:24 UTC
Labels: comp:keras, type:support

**Comment by tsing-cv** [comment] 2019-06-23 12:51
Speed has nothing to do with multi_preprocess and data io.
When executing python coco.py evaluate, tf.keras is slower than keras.

**Comment by ariannacvf** [comment] 2019-06-29 19:56
i have same problem. tf.keras is 4 times slower than keras itself. Did you solve anything?
