### ISSUE TITLE
mAP increase but classification loss increase

### ISSUE THREAD

**Issue by hongym7** [tensorflow/tensorflow#28353] opened 2019-05-03 01:58 UTC
mAP increase, but classification loss increase in object detection training. (by tensorflow object detection API)
Train data : 1500, Val data : 150
Class : 1 (drone)
I don't know what happen

![image](https://user-images.githubusercontent.com/3411873/57116734-11a21b00-6d92-11e9-867b-d10a7e16e52d.png)

**Comment by rootkitchao** [comment] 2019-05-04 23:40
It seems that you are using a two-stage detector such as [faster r-cnn](https://arxiv.org/pdf/1506.01497.pdf).It seems that the decline in RPN loss has a greater impact on detection performance.

**Comment by achandraa** [comment] 2019-05-06 09:14
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version and if possible provide us the code snippet to reproduce the issue at hand. If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by achandraa** [comment] 2019-05-10 04:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-10 04:07 UTC
Labels: stat:awaiting response
