### ISSUE TITLE
Get error when build tensorflow-lite-hexagon.aar

### ISSUE THREAD

**Issue by thinksmert** [tensorflow/tensorflow#35377] opened 2019-12-24 06:09 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version:2.0
- Python version:2.7.15
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):1.1.0
- GCC/Compiler version (if compiling from source):8.3.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I try to build a tensorflow-lite-hexagon.aar with the instructions as follows:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/hexagon_delegate.md
It used the command :
bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon
to build.But I get the error like this:
ERROR: /prj/F3060803/Project/Tensorflow/tensorflow-master/tensorflow/lite/c/BUILD:130:1: C++ compilation of rule '//tensorflow/lite/c:common' failed (Exit 1)
Target //tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon failed to build
I wonder how should I do?Thanks

**Comment by thinksmert** [comment] 2019-12-27 05:47
Hi,
  I try to build tensorflow-lite-hexagon.aar with the lasted code from github,but it always could not be successful and gave the different errors each times.When google can provide the stable release?Thanks

**Comment by karimnosseir** [comment] 2019-12-30 20:55
Hi,
Sorry for late reply as i was out of office.
I just tried building it and it is working. Can you try again ?

We will be providing a hosted version on JCenter to use soon.

Thanks

**Comment by thinksmert** [comment] 2019-12-31 02:56
Hi,
Thank you for your reply.Can you tell me which version on the git you tried?I have tried the lasted code downloaded from github,but still got the error:
ERROR: /home/foxconn/.cache/bazel/_bazel_foxconn/dd512d2a00295bff465168b5ce1aeaf7/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-gnu-libstdcpp: cc_toolchain_suite '@androidndk//:toolchain-gnu-libstdcpp' does not contain a toolchain for cpu 'k8'
The tf version is 2.0 and python version is 2.7.15.Can you provide me the version you sucessed?Thanks

**Comment by karimnosseir** [comment] 2019-12-31 08:51
Steps:
1) git clone https://github.com/tensorflow/tensorflow.git
2) cd tensorflow
3) run ./configure
** don't forget to configure the android workspace - Answer Y when asked 
"Would you like to interactively configure ./WORKSPACE for Android builds?"
4)  bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon


If you followed the above steps and still have a problem, then please send details on bazel version you're using and what is the environment setup you configured for android (point #3 above)

Thanks

**Comment by thinksmert** [comment] 2019-12-31 15:11
Hi,
I have tried again and still get the error.Here is the details:
ERROR: /prj/F3060803/Project/Tensorflow/tensorflow-lastest/tensorflow-master/tensorflow/lite/experimental/delegates/hexagon/builders/BUILD:8:1: C++ compilation of rule '//tensorflow/lite/experimental/delegates/hexagon/builders:op_builder' failed (Exit 1)
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:31:36: error: no member named 'numeric_limits' in namespace 'std'
                              std::numeric_limits<uint8_t>::min(),
                              ~~~~~^
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:31:51: error: unexpected type name 'uint8_t': expected expression
                              std::numeric_limits<uint8_t>::min(),
                                                  ^
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:31:61: error: no member named 'min' in the global namespace
                              std::numeric_limits<uint8_t>::min(),
                                                          ~~^
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:32:36: error: no member named 'numeric_limits' in namespace 'std'
                              std::numeric_limits<uint8_t>::max());
                              ~~~~~^
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:32:51: error: unexpected type name 'uint8_t': expected expression
                              std::numeric_limits<uint8_t>::max());
                                                  ^
tensorflow/lite/experimental/delegates/hexagon/builders/neg_op_builder.cc:32:61: error: no member named 'max' in the global namespace
                              std::numeric_limits<uint8_t>::max());
                                                          ~~^
6 errors generated.

The bazel version is 1.1.0 and android configuration I set is:
min android-ndk api level: 21
android api level: 28
android build tools: 28.0.3

Please help to check.Thanks

**Comment by karimnosseir** [comment] 2020-01-02 17:50
Which NDK are you using.
Can you try with ndk r17c ?

**Comment by thinksmert** [comment] 2020-01-03 02:00
I use r16 now and I will try r17c later.

**Comment by thinksmert** [comment] 2020-01-03 06:34
Hi,
I used r17c to built and it was successful.But the size of .aar is only 2.2kB and when I excute the code:hexagonDelegate = new HexagonDelegate(activity);
I got the error:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.lite.examples.detection-z7pYJM-s1UhmIszRu4C0Qg==/base.apk"],nativeLibraryDirectories=[/data/app/org.tensorflow.lite.examples.detection-z7pYJM-s1UhmIszRu4C0Qg==/lib/arm64, /data/app/org.tensorflow.lite.examples.detection-z7pYJM-s1UhmIszRu4C0Qg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libtensorflowlite_hexagon_jni.so"
where can I find the libtensorflowlite_hexagon_jni.so?Thanks

**Comment by thinksmert** [comment] 2020-01-06 14:34
Hi,karimnosseir
  Do you have any suggestions?

**Comment by thinksmert** [comment] 2020-01-06 14:34
Hi,karimnosseir
  Do you have any suggestions?

**Comment by karimnosseir** [comment] 2020-01-06 20:43
Hi @thinksmert 

The AAR is now available on bintray, can you download it and try it
https://bintray.com/google/tensorflow/tensorflow-lite-hexagon/

Note: It might take up to 24 Hrs before Gradle dependency works, so if you got failure for resolving the dependency then try downloading and adding to your app

**Comment by thinksmert** [comment] 2020-01-07 01:42
Hi,karimnosseir
 Thank you for your reply and I will try the aar later.But I still want to know where can I find libtensorflowlite_hexagon_jni.so.I guess it should be built from hexagon delegate source code because I found some build rule about the .so in tensorflow\lite\experimental\delegates\hexagon\java\BUILD file.But I don't know why it does not be built.

**Comment by karimnosseir** [comment] 2020-01-07 23:27
Hi @thinksmert,
It should be built by the rule defined in 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/java/BUILD

But looks like you have some configuration issue which results in something wrong.

Can you please try the AAR

Thanks

**Comment by karimnosseir** [comment] 2020-01-07 23:28
I mean the Jcenter hosted one

Thanks

**Comment by thinksmert** [comment] 2020-01-08 01:25
Hi,karimnosseir
Which issue should be corrected?I don't change the built rule and it is just the one downloaded from git.
Otherwise, I have tried the AAR and it works.But it sames can only use quantized model?I use quantized model and the accuracy is bad than float model with gpu.Do you have any suggestion that can improve the accuracy?
Thanks

**Comment by karimnosseir** [comment] 2020-01-08 02:09
By issue i meant configuration issue for the environment (for example NDK).
Anyways, you can use the one provided on JCenter - glad it is working.
For quantized, yes it works for quantized models only.
Refer to https://www.tensorflow.org/lite/performance/best_practices#quantization
for some pointers if you're quantizing your model.
It is expected that you will lose some accuracy, but how much you're losing depends on what you're doing.

Thanks

**Comment by karimnosseir** [comment] 2020-01-08 02:10
Closing the bug, since the issue is fixed with switching to using the AAR provided on JCenter.

Thanks

**Closed by karimnosseir** 2020-01-08 02:10 UTC
Labels: TF 2.0, comp:lite, type:support
