### ISSUE TITLE
not support MatrixBandPart in tflite

### ISSUE THREAD

**Issue by anhtu812** [tensorflow/tensorflow#27618] opened 2019-04-08 08:06 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version : 2.0alpha

**Provide the text output from tflite_convert**

```
Here is a list of operators for which you will need custom implementations: MatrixBandPart.
```

**Comment by anhtu812** [comment] 2019-04-08 08:37
I replaced tf.linalg.band_part by mask e.g:
	# mask = tf.linalg.band_part(mask, 0, -1)
	a = tf.range(tf.shape(mask)[0])
	mask1 = a[:,None]<=a[None,:]# true in upper_triangular
	mask = tf.logical_and(mask, mask1)

**Comment by muddham** [comment] 2019-04-09 08:43
@anhtu812 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-16 21:27
@anhtu812 Could you provide the issue and its context with more details? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-25 21:35
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-25 21:35 UTC
Labels: 2.0.0-alpha0, comp:ops, type:bug/performance
