### ISSUE TITLE
 Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph.

### ISSUE THREAD

**Issue by Dasinator21** [tensorflow/tensorflow#41829] opened 2020-07-28 16:38 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version (or github SHA if from source): 1.15

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```
tflite_convert --graph_def_file=C:/tensorflow4/models/research/object_detection/TFLite_model/tflite_graph.pb --output_file=tflite/detect.tflite --output_format=TFLITE --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=127 --change_concat_input_ranges=false --allow_custom_ops
**The output from the converter invocation**

```
# Copy and paste the output here.
```
2020-07-28 18:33:11.363228: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TFLite_Detection_PostProcess
2020-07-28 18:33:11.531507: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Fatal Python error: Aborted

Current thread 0x000023ec (most recent call first):
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 52 in execute
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 250 in _run_main
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 299 in run
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\platform\app.py", line 40 in run
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 89 in main
  File "C:\Users\Sreed\Anaconda3\envs\tensorflow2\Scripts\toco_from_protos.exe\__main__.py", line 7 in <module>
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\runpy.py", line 85 in _run_code
  File "c:\users\sreed\anaconda3\envs\tensorflow2\lib\runpy.py", line 193 in _run_module_as_main

**Also, please include a link to the saved model or GraphDef**
 https://github.com/Dasinator21/Replicate-Error
```
# Put link here or attach to the issue.
```https://github.com/Dasinator21/Replicate-Error

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)


**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment] 2020-07-29 08:41
@Dasinator21 
Could you please try removing quotes as below and let us know if it helps:
instead of using
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' Use:
--output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3

as per issues with similar error:
#34143 [link](https://stackoverflow.com/questions/58282082/error-when-covert-pb-to-tflite-ssd-mobilenet-v2-windows-10)

**Comment by Dasinator21** [comment] 2020-07-29 09:58
> @Dasinator21
> Could you please try removing quotes as below and let us know if it helps:
> instead of using
> --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' Use:
> --output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3
> 
> as per issues with similar error:
> #34143 [link](https://stackoverflow.com/questions/58282082/error-when-covert-pb-to-tflite-ssd-mobilenet-v2-windows-10)

It seems to work, I will see I can run a code to run an inference with the tflite model. (Sorry for any misuse of terminology)

**Comment by Dasinator21** [comment] 2020-07-29 10:04
It works thank you!

**Comment by Saduf2019** [comment] 2020-07-29 15:38
@Dasinator21 
Happy to help, moving this to closed status as the issue is resolved.

**Closed by Saduf2019** 2020-07-29 15:38 UTC
Labels: TF 1.15, TFLiteConverter, stat:awaiting response
