### ISSUE TITLE
importing tensorflow

### ISSUE THREAD

**Issue by HotepRato** [tensorflow/tensorflow#18554] opened 2018-04-16 12:28 UTC
Hello, 
I tried to install tensorflow using conda, but whenever I try to import it, I get this error:

```
ImportError                               Traceback (most recent call last)
C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

C:\Anaconda\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\Anaconda\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Anaconda\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Anaconda\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Anaconda\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Anaconda\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\Anaconda\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\Anaconda\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     20             return importlib.import_module('_pywrap_tensorflow_internal')
---> 21     _pywrap_tensorflow_internal = swig_import_helper()
     22     del swig_import_helper

C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow_internal')
     21     _pywrap_tensorflow_internal = swig_import_helper()

C:\Anaconda\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-90de3482487c> in <module>()
      1 
      2 
----> 3 import tensorflow as tf
      4 from skimage import transform
      5 from skimage import data

C:\Anaconda\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

C:\Anaconda\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Anaconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Anaconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems


```

Whenever I search for a solution, everyone recommend installing VCREDIST 2015, except I already have it.

Thank you for your time

**Comment by jhemp01** [comment] 2018-04-16 15:10
Got the same issue, installed with anaconda, double-checked all my pathes, nothing helps!
![2018-04-15_215717](https://user-images.githubusercontent.com/16338045/38817523-d83088b4-4198-11e8-847f-4ac77a50ca77.jpg)

**Comment by jhemp01** [comment] 2018-04-16 20:55
Ok, I was able to solve the problem, at least on my Windows 10:
Assuming that only users with the tensorflow-gpu version are concerned:

If you have CUDA 9.0 and cudnn 7.0.5 installed, like suggested from a lot of tutorials, you MUST install Tensorflow 1.5.0, no other version. The command pip install --ignore-installed --upgrade tensorflow-gpu gives you the latest tensorflow 1.7.0, which doesn't seem to work with CUDA 9.0.
You'll need to download the appropriate file from https://pypi.org/project/tensorflow-gpu/1.5.0/#files, cd to the download directory, install the file with pip install tensorflow...xxx.whl

Hope this helps!

**Comment by HotepRato** [comment] 2018-04-17 18:28
I'm not trying to install the GPU version, but the CPU version. 
Thank you anyway !

**Comment by vijaysaimutyala** [comment] 2018-04-17 20:12
There was a stackoverflow post that says that TensorFlow 1.7 uses AVX for the CPU version which is causing the above issue on Windows(Same behaviour observed for 1.6 as well). The above case occurs even when the Visual C++ build tools are installed. Verified this on two desktops running Windows 10(They run the same processor). Also to add, Intel Virtualization is already enable in the BIOS.

Versions <=1.5 works well without any issues.

Happy to provide more detials.

**Comment by angersson** [comment] 2018-04-25 18:18
This is a duplicate of https://github.com/tensorflow/tensorflow/issues/17386. Please look there for discussion + assistance.

**Closed by angersson** 2018-04-25 18:18 UTC

**Comment by clement2019** [comment] 2020-07-31 15:45
Hi guys solved the above  importing tensor flow error  suing the CPU after i downloaded and install
Microsoft Visual C++ 2015-2019 Redistributable (x64) 
VC_redist.x64 version on my laptop.. hope this help someone out there
i had initially installed Anaconda 3.7 python version, then i now using the conda command prompt
 installed the tensor flow successfully from Anaconda and it worked. But on importing tensorflow i ran into the above issues.
i even installed msv140dll still did not work until i downloaded and run
VC_redist.x64 version  everything worked after then 
cheers
