### ISSUE TITLE
Update docker images and documentation to not use nvidia-docker by default.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tensorflow/tensorflow#14943] opened 2017-11-28 14:21 UTC
`nvidia-docker` is not used anymore by the [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) project.  Rather `nvidia-docker2` should be used:

```
$ docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

**Comment by aselle** [comment] 2017-11-28 23:07
@caisq, could you please look into updating our examples?

**Comment by flx42** [comment] 2017-11-29 00:56
dupe of #14714

**Comment by tensorflowbutler** [comment] 2017-12-20 01:26
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:05
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-06 07:33
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-07 13:21
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 01:03
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:35
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:57
Nagging Assignee @caisq: It has been 178 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:46
Nagging Assignee @caisq: It has been 193 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:10
Nagging Assignee @caisq: It has been 208 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:02
Nagging Assignee @caisq: It has been 223 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:57
Nagging Assignee @caisq: It has been 238 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:01
Nagging Assignee @caisq: It has been 253 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:43
Nagging Assignee @caisq: It has been 268 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:37
Nagging Assignee @caisq: It has been 283 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:44
Nagging Assignee @caisq: It has been 298 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dksb** [comment] 2018-09-28 21:28
This issue has been fixed.

**Closed by dksb** 2018-09-28 21:28 UTC
