### ISSUE TITLE
[TF2.0] Checkpoint doesn't store non-TF objects

### ISSUE THREAD

**Issue by awav** [tensorflow/tensorflow#32242] opened 2019-09-05 15:35 UTC
Hello all,

I found that `tf.train.Checkpoint` doesn't save non-TF objects and tf.Tensors. The MWE below shows the case:

```python
import tensorflow as tf

class A(tf.Module):
    def __init__(self):
        super().__init__()
        self.scalar = 1.
        self.variable = tf.Variable(1.)
        self.tensor = tf.convert_to_tensor(1.)
        self.list = [tf.convert_to_tensor(10.0), 20.0, tf.Variable(0.0)]

    def __str__(self):
        return f"scalar={self.scalar}, variable={self.variable.numpy()}, tensor={self.tensor}, list={self.list}"


a_module = A()
checkpoint = tf.train.Checkpoint(a=a_module)
manager = tf.train.CheckpointManager(checkpoint, '/tmp/example', max_to_keep=3)
manager.save()

print(f"1. {a_module}")

#### modify

a_module.scalar = -100.
a_module.variable.assign(123.)
a_module.tensor = tf.convert_to_tensor(-12.)
a_module.list = [3., 3.]

print(f"2. {a_module}")

#### restore
checkpoint.restore(manager.latest_checkpoint)

print(f"3. {a_module}")
```

Output:
```python
1. scalar=1.0, variable=1.0, tensor=1.0, list=ListWrapper([<tf.Tensor: id=9, shape=(), dtype=float32, numpy=10.0>, 20.0, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>])
2. scalar=-100.0, variable=123.0, tensor=-12.0, list=ListWrapper([3.0, 3.0])
3. scalar=-100.0, variable=1.0, tensor=-12.0, list=ListWrapper([3.0, 3.0])
```

In the output you can see that the checkpointer restores only the variable and completely ignores other fields of the A object.

I expected that at least pythonic objects, numpy and TF tensors should be stored by the checkpointer on the disk. Is that a normal behavior?

If the answer is **yes**: I think that this feature should be implemented, otherwise it is very confusing and not straightforward why the checkpoint saves some objects and others not.
**no**: this is a bug, must be fixed.

**System information**
- OS Platform and Distribution: `macOS 10.14.6`
- TensorFlow version: `v1.12.1-10419-g5138353309 2.0.0-dev20190905`
- Python version: `3.6.8`

**Comment by ravikyram** [comment] 2019-09-06 10:34
I have tried on colab with TF version 2.0.0-dev20190903, 2.0.0-rc0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e4d3e264f71cd7372f17020f0db42c76/untitled160.ipynb).Thanks!

**Comment by awav** [comment] 2019-09-21 16:23
Hello @ravikyram , @jvishnuvardhan , @rchao! Any updates on the topic?

**Comment by awav** [comment] 2019-09-30 15:34
Hello @ravikyram , @jvishnuvardhan , @rchao again! Does anyone have looked at this issue?

**Comment by jvishnuvardhan** [comment] 2019-09-30 15:56
@rchao could you PTAL?

**Comment by rchao** [comment] 2019-09-30 19:50
Reassigning to @k-w-w to take a look or triage. Thanks.

**Comment by k-w-w** [comment] 2019-09-30 19:57
Hi @awav,

This is intended. Tensorflow checkpoints only save and restore the variables/other TensorFlow objects with state. Constants tensors and python objects won't be included in the Checkpoint, and this is expected because some constants (e.g. lookup tables) can get exceedingly large. 

There is an experimental API that lets you save arbitrary python values to the Checkpoint. Check it out here: https://www.tensorflow.org/api_docs/python/tf/train/experimental/PythonState

Feel free to submit a PR with clarifications to docstring of [tf.train.Checkpoint](https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint).

**Comment by awav** [comment] 2019-10-01 15:15
Hello @k-w-w ,

Okay, what's about this line: `self.list = [tf.convert_to_tensor(10.0), 20.0, tf.Variable(0.0)]`, the list has variable, but it is not stored in the checkpoint.

> Constants tensors and python objects won't be included in the Checkpoint, and this is expected because some constants (e.g. lookup tables) can get exceedingly large.
Variables can be exceedingly large as well. The literals can and should be stored in a checkpoint. Writing a serializer for `int`, `float` and `str` every time when I need to store them is a bit weird.

Can we keep an issue open?

**Comment by k-w-w** [comment] 2019-10-01 21:20
When the values were restored, the list no longer contained any variables. Checkpoint.restore only restores the values of existing objects, but will not modify the objects themselves. In other words, it will not rewrite the elements in the list.

What would be the use case for storing python ints/floats/strings?

**Comment by amahendrakar** [comment] 2020-10-22 04:17
@awav,
Any updates regarding this? Please take a look at @k-w-w's comment above and let us know if this is still an issue. Thanks!

**Closed** 2020-11-05 05:34 UTC
Labels: TF 2.0, comp:apis, stalled, stat:awaiting response, type:bug
