### ISSUE TITLE
Download of test data not working

### ISSUE THREAD

**Issue by CmasterG** [tensorflow/tensorflow#8134] opened 2017-03-06 17:04 UTC
The get started part has a section MNIST for ML Beginners. In this tutorial you should download the test data via:

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Unfortunately that's not working because of an connection error.

**Comment by prb12** [comment] 2017-03-06 17:10
The MNIST example downloads its dataset from `http://yann.lecun.com/exdb/mnist`.
If this site is temporarily down or unreachable then the download will fail. 

Please can you try accessing the URL directly in a web browser?  (it is currently unreachable for me) 
Once the page is accessible in a browser, then please try the tutorial again.

**Comment by CmasterG** [comment] 2017-03-06 17:13
Hi!
Thanks for the fast reply. No, it is not reachable in the browser. Is there an alternative way to get the relevant data?

**Comment by prb12** [comment] 2017-03-06 17:26
Duplicate of #8126

**Closed by prb12** 2017-03-06 17:26 UTC

**Comment by amita-kapoor** [comment] 2018-06-11 13:45
I am getting " HTTP Error 403: Forbidden" while trying to download MNIST dataset using ```input_data.read_data_sets("MNIST_data/", one_hot=True)``` comand, though the data is downloadable from Yann LeCun website. 

Tensorflow version 1.4
