### ISSUE TITLE
python(2711,0x7fffcc8553c0) malloc: *** error for object 0x120b0fff0: pointer being freed was not allocated

### ISSUE THREAD

**Issue by zyxcambridge** [tensorflow/tensorflow#15360] opened 2017-12-14 09:27 UTC
cambridgedeMBP:tensorflow-master cambridge$ bazel-bin/tensorflow/python/tools/freeze_graph \
> --input_graph=/Users/cambridge/Desktop/naset/models-master/research/slim/flowers_5/inception_v4_inf_graph.pb \
> --input_checkpoint=/Users/cambridge/Desktop/naset/models-master/research/slim/flowers_5/my_train_10/model.ckpt \
> --input_binary=true \
> --output_graph=/Users/cambridge/Desktop/naset/models-master/research/slim/flowers_5/frozen_inception_v4.pb \
> --output_node_names=InceptionV4/Predictions/Reshape_1
python(2711,0x7fffcc8553c0) malloc: *** error for object 0x120b0fff0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by tensorflowbutler** [comment] 2017-12-14 19:01
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MistLiao** [comment] 2017-12-19 06:26
It looks like caused by incorrect python version. Do you run .configure before build freeze_graph?

**Comment by rish321** [comment] 2017-12-23 07:13
Have I written custom code: No
OS Platform and Distribution: macOS High Sierra
TensorFlow installed from - virtualenv
TensorFlow version - 1.4.1
Bazel version - 0.9.0
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce - bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/dir

**Comment by tensorflowbutler** [comment] 2018-01-06 18:55
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by chriszeng87** [comment] 2018-01-11 08:05
Yes, I got the same problem on Mac, CPU version

**Comment by jared-mess** [comment] 2018-01-13 06:13
This appears to be a Bazel issue. For tensorflow 1.4.1, I downgraded to Bazel 0.6.1 (not 0.9.0) and that fixed the `malloc pointer being freed was not allocated` error. 
My specs are:
- macOS Sierra,
- Tensorflow r1.4
- Bazel 0.6.1
- No GPU/Cuda

**Comment by chriszeng87** [comment] 2018-01-14 15:16
Tried Bazel 0.6.1 but still got the same error message:
python(10450,0x7fff943f8340) malloc: *** error for object 0x1c16f928c8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by tensorflowbutler** [comment] 2018-02-06 07:31
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-20 19:31
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:09
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by thmufl** [comment] 2018-03-08 20:53
Same error with:

- TensorFlow 1.6
- Bazel 0.11.1-homebrew
- MacOS High Sierra

Any updates?

**Comment by tensorflowbutler** [comment] 2018-03-25 00:49
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by rtvanals** [comment] 2018-03-25 04:12
Same error with:

- Tensorflow 1.5
- Bazel 0.9.0
- MacOS High Sierra

**Comment by lifeiteng** [comment] 2018-03-28 06:56
error with:
- TF 1.7.0 rc1 `CPU`
- Bazel 0.11.1
- MacOS Sierra

**Comment by thmufl** [comment] 2018-04-17 13:34
From my point of view, you can close the issue. I tested it with Tensorflow 1.7. It ran without problem. Thanks a lot!

**Comment by skye** [comment] 2018-04-17 17:13
Thank you for reporting back!

**Closed by skye** 2018-04-17 17:13 UTC
Labels: stat:awaiting response

**Comment by lifeiteng** [comment] 2018-11-03 08:02
solved by:
```
diff --git a/tensorflow/tensorflow/tf_version_script.lds b/tensorflow/tensorflow/tf_version_script.lds
index 6b28943f01..39d258c3b7 100644
--- a/tensorflow/tensorflow/tf_version_script.lds
+++ b/tensorflow/tensorflow/tf_version_script.lds
@@ -6,6 +6,7 @@ tensorflow {
     *TFE_*;
     *nsync_*;
     *pywrap_xla*;
+    *stream_executor*;
   local:
     *;
 };
```
