### ISSUE TITLE
How to test a saved model trained with tf.train.batch?

### ISSUE THREAD

**Issue by guoguoguilai** [tensorflow/tensorflow#29152] opened 2019-05-30 01:45 UTC
By calling

graph.get_tensor_by_name("output:0")
I found that it returns a tensor shaped [batch_size,num]，How to test a saved model trained with tf.train.batch ?

**Comment by gadagashwini** [comment] 2019-05-31 05:06
@guoguoguilai Closing since its a duplicate of  [#29110](https://github.com/tensorflow/tensorflow/issues/29110). Feel free to reopen if the solution provided on that thread doesn't work Distributed for you. Thanks!

**Closed by gadagashwini** 2019-05-31 05:06 UTC
Labels: comp:ops, type:support
