### ISSUE TITLE
error: can't copy 'tensorflow/models/embedding/gen_word2vec.py': doesn't exist

### ISSUE THREAD

**Issue by EderSantana** [tensorflow/tensorflow#3680] opened 2016-08-06 20:16 UTC
I was installing TF from source like I always did but I'm having the following issue this time when running `bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg` I got

```bash
~/python/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Sat Aug 6 16:07:12 EDT 2016 : === Using tmpdir: /tmp/tmp.TNJr7rCgpe
/tmp/tmp.TNJr7rCgpe ~/python/tensorflow
Sat Aug 6 16:07:12 EDT 2016 : === Building wheel
error: can't copy 'tensorflow/models/embedding/gen_word2vec.py': doesn't exist or not a regular file
```

plus, I can't find that file anywhere... did anything change or am I missing something?

**Comment by girving** [comment] 2016-08-08 16:48
@martinwicke Do we have a pip czar?  We don't have one listed in the spreadsheet.

**Comment by martinwicke** [comment] 2016-08-11 22:35
That looks like a build dependency is missing: pip_package should depend on that gen_word2vec.py file, but doesn't. PRs welcome.

**Comment by martinwicke** [comment] 2016-08-11 22:36
Yuefeng, assigning to you, build system fun.

**Comment by YuefengZhou** [comment] 2016-08-12 19:07
@EderSantana Hi Eder, it worked in my Mac with OSX 10.11.6. What is your environment? Did you successfully run the "bazel run"? Which version of bazel are you using?

**Comment by EderSantana** [comment] 2016-08-12 20:26
@YuefengZhou 
I'm using ubuntu 14.04 I ran `./configure` and 
`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
with success

the problem was on that very last step

**Comment by EderSantana** [comment] 2016-08-12 20:29
Actually, I just tried to run everything and noticed that I got the following message when running `bazel build`:
```bash
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by YuefengZhou** [comment] 2016-08-12 22:12
@EderSantana Your problems looks very similar to another issue, you probably can try the workaround there: https://github.com/tensorflow/tensorflow/issues/1157#issuecomment-192552759

**Comment by YuefengZhou** [comment] 2016-08-15 17:22
I have reproduced the problem in my Ubuntu 14.04 desktop and fixed it with this workaround. So I am closing this issue.

**Closed by YuefengZhou** 2016-08-15 17:22 UTC
Labels: bug, installation/startup

**Comment by EderSantana** [comment] 2016-08-15 21:47
You mean this, right:

>
Adding
cxx_builtin_include_directory: "/usr/local/cuda/targets/x86_64-linux/include"
to file tensorflow/third_party/gpus/crosstool/CROSSTOOL
seem to be a workaround.

**Comment by JoelDan192** [comment] 2016-12-08 19:39
Hi,
if someone can help me. I have a similar problem on Windows 10 (a friend has the same issue for Windows aswell) with tensorflow 0.12.0-rc0:
ImportError: No module named 'tensorflow.models'.
And the file gen_word2vec.py doesn't exist in tensorflow/models/embedding so I cannot even import it manually (from cloned GitHub).
I did the installation via pip for CPU, but even the folder /tensorflow/models is missing in that case.

**Comment by martinwicke** [comment] 2016-12-08 20:39
We are moving model/ out of this repo altogether and moving it to github.com/tensorflow/models. This is probably accidental, but it's a sign of the things to come.
