### ISSUE TITLE
Assign requires shapes of both tensors to match

### ISSUE THREAD

**Issue by vclteam** [tensorflow/tensorflow#13581] opened 2017-10-09 12:58 UTC
im trying to run the voice recognition example

for some reason specifying a clip_duration_ms diffren from 1000 generate an error while freezing the model.

so running
python tensorflow/examples/speech_commands/freeze.py 
--wanted_words=yes 
--clip_duration_ms=2800 --sample_rate=16000 --window_size_ms=20 
--start_checkpoint=/notebooks/yesmodel/conv.ckpt-10 
--output_file=/notebooks/yesmodel/conv_frozen.pb

generate the following message
Error: Assign requires shapes of both tensors to match. lhs shape= [320000,3] rhs shape= [62720,3]

any idea what im doing wrong?

**Comment by reedwm** [comment] 2017-10-09 16:36
This appears to be a duplicate of #13487

**Closed by reedwm** 2017-10-09 16:36 UTC
