### ISSUE TITLE
Attension Layer Tensorflow TypeError: Cannot iterate over a tensor with unknown first dimension

### ISSUE THREAD

**Issue by abdoelsayed2016** [tensorflow/tensorflow#39235] opened 2020-05-06 18:54 UTC
I am trying to apply attention Layer to CRNN Econder and Decoder
but there is an error cant understand what it means?

Use distribution to create a linear combination of value with shape batch_size, Tq, dim]: return tf.matmul(distribution, value).
    cnn = MaxPooling2D(pool_size=(1,2), strides=(1,2), padding="valid")(cnn)
    shape = cnn.get_shape()
    nb_units = shape[2] * shape[3]

    gru = Reshape((shape[1], nb_units))(cnn)
    gru, forward_h, forward_c, backward_h, backward_c = Bidirectional \
    (LSTM
     (nb_units,
      dropout=0.2,
      return_sequences=True,
      return_state=True,
      recurrent_activation='relu',
      recurrent_initializer='glorot_uniform'))(gru)

    state_h = tf.keras.layers.Concatenate()([forward_h, backward_h])
    state_c = tf.keras.layers.Concatenate()([forward_c, backward_c])
    gru, attention_weights = Attention(32)([gru, state_h])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-1b228a635105> in <module>()
      4 # note: `learning_rate=None` will get architecture default value
      5 model = HTRModel(architecture=arch, input_size=input_size, vocab_size=dtgen.tokenizer.vocab_size)
----> 6 model.compile(learning_rate=0.001)
      7 
      8 # save network summary

C:\Users\a.abdallah\Desktop\handwritten-text-recognition\src\network\model.py in compile(self, learning_rate)
    134 
    135         # define inputs, outputs and optimizer of the chosen architecture
--> 136         outs = self.architecture(self.input_size, self.vocab_size + 1, learning_rate)
    137         inputs, outputs, optimizer = outs
    138 

C:\Users\a.abdallah\Desktop\handwritten-text-recognition\src\network\model.py in abdo(input_size, d_model, learning_rate)
    571 
    572     
--> 573     gru, attention_weights = Attention(32)([gru, state_h])
    574 
    575     

c:\users\a.abdallah\anaconda3\envs\handwritten\lib\site-packages\tensorflow_core\python\framework\ops.py in __iter__(self)
    546     if shape[0] is None:
    547       raise TypeError(
--> 548           "Cannot iterate over a tensor with unknown first dimension.")
    549     for i in xrange(shape[0]):
    550       yield self[i]

TypeError: Cannot iterate over a tensor with unknown first dimension.

**Comment by ravikyram** [comment] 2020-05-07 06:42
@abdoelsayed2016 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version?
Request you to provide colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by abdoelsayed2016** [comment] 2020-05-07 16:49
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow 2.1.0 GPU
- Python version: 3.6.10:: Anaconda, Inc.
- CUDA/cuDNN version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105


You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
2020-05-07 22:47:55.783521: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
v2.1.0-rc2-17-ge5bf8de410 2.1.0

**Comment by ravikyram** [comment] 2020-05-08 08:11
@abdoelsayed2016 

Request you to provide colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment] 2020-06-05 07:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-05 07:25 UTC
Labels: TF 2.1, comp:keras, type:support

**Comment by Shridharpawar77** [comment] 2020-07-16 15:55
Hello @ravikyram, Did you solved the problem. if yes, please help me with the same. 
I am trying to add attention layer in seq2seq model
