### ISSUE TITLE
tflite invoke function crash

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#29864] opened 2019-06-17 08:24 UTC
I came cross a strange issues only occurred on HuaWei Phone. 
For phone infomation with this image.
![image](https://user-images.githubusercontent.com/17869361/59587579-26572a00-9118-11e9-8b20-67a14a5c8f08.png)

At first time run inference no crash, It is always crash at second time. below is crash info.
![image](https://user-images.githubusercontent.com/17869361/59587879-e3498680-9118-11e9-8fe6-bf97e2e2301b.png)

Below is processed crash info with ndk-stack, but unable to locate in tensorflow source as build tflite from source with no debug symbols and i do not know how to build with debug symbol
![image](https://user-images.githubusercontent.com/17869361/59588620-9a92cd00-911a-11e9-9fb9-ba68baa06f52.png)

I have tried many methods for building tflite with debug symbol but not successed
For example
1、 bazel build -c dbg --strip=never --compilation_mode=dbg --per_file_copt=//tensorflow/lite/.*\.cc@-g,-O0  //tensorflow/lite:libtensorflowLite.so --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"
with -c dbg --strip=never  --compilation_mode=dbg

![image](https://user-images.githubusercontent.com/17869361/59588889-345a7a00-911b-11e9-9424-c3cfcdd87d99.png)
Crash occurred at 62 line
It crashed at second time only on HuaWei Phone. Other phones and ios has no crash.

ps:This issue finally crashed at 277 line with below image
![image](https://user-images.githubusercontent.com/17869361/59751454-217aad80-92b3-11e9-8a98-155da7e58c92.png)

I guess the bias_data address is unavaible
![image](https://user-images.githubusercontent.com/17869361/59751423-10ca3780-92b3-11e9-971c-99ec5e074624.png)

**Comment by ravikyram** [comment] 2019-06-21 12:27
Can we close this issue. It looks this is the duplicate of #29739.Please, let us know.Thanks.

**Comment by weinixuehao** [comment] 2019-06-24 01:39
@ravikyram Two are both submitted by me but no answer.

**Comment by ravikyram** [comment] 2019-06-24 06:00
@weinixuehao It will be better to track with a single issue #29739 for faster resolution .Can we close this issue? Thanks.

**Comment by weinixuehao** [comment] 2019-06-24 07:02
OK 
The other one has included two issues 
One is for ios building with gpu support and one is for this issue

**Comment by ravikyram** [comment] 2019-06-25 04:51
@weinixuehao I am closing this issue & we can track the resolution for this issue in #29739.Thanks.

**Closed by ravikyram** 2019-06-25 04:51 UTC
Labels: comp:lite, type:bug/performance
