### ISSUE TITLE
Issue with running Tensorflow with OpenCL - Ubuntu 14.04.3 (Trusty) - AMD R5 Radeon M335 GPU

### ISSUE THREAD

**Issue by rahasayantan** [tensorflow/tensorflow#9445] opened 2017-04-25 18:35 UTC
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):14.04.3-->Trusty

TensorFlow installed from (source or binary):Source

TensorFlow version (use command below):1.0 (Steps-> Downloaded tensorflow from https://github.com/benoitsteiner/tensorflow-opencl, ./configure - to configure project)

Bazel version (if compiling from source):0.4.5

CUDA/cuDNN version:NA

OPENCL Version:
Number of platforms:	1
Platform Profile:	FULL_PROFILE
Platform Version:	OpenCL 2.0 AMD-APP (1800.11)
Platform Name:	AMD Accelerated Parallel Processing
Platform Vendor:	Advanced Micro Devices, Inc.
Platform Extensions:	cl_khr_icd cl_amd_event_callback cl_amd_offline_devices

GPU model and memory:
Platform Name:	AMD Accelerated Parallel Processing
Number of devices:	2
Device Type:	CL_DEVICE_TYPE_GPU
Board name:	AMD Radeon (TM) R5 M335
Memory:	4096M

Exact command to reproduce:
run the python script -- ipython keras_code.py

** G++/GCC version**:
g++-4.9 (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4

I have compiled CPP programs, they work fine.

ComputeCPP: 0.1.4
-- ** Python**: I am using Anaconda distribution Python for 2.7.2. (Anaconda - 2.4.3)

Describe the problem

I have compile tensorflow, and deployed the same -> No issues here. when I try to run the code I run into the following error:

2017-04-23 14:01:15.180795: W ./tensorflow/core/common_runtime/sycl/sycl_util.h:44] No OpenCL GPU found that is supported by ComputeCpp, trying OpenCL CPU
2017-04-23 14:01:15.180843: F ./tensorflow/core/common_runtime/sycl/sycl_util.h:53] No OpenCL GPU nor CPU found that is supported by ComputeCpp
Aborted (core dumped)

I have attached the code file. Please note this is a simplified version of the file. The logic is:

Read data from files,
Pass it through a NN
I am using Keras as the Functional programming API on top of Tensorflow.

More details: Output of Computecpp_info:
********************************************************************************

ComputeCpp Info (CE 0.1.4)

********************************************************************************

Toolchain information:

GLIBCXX: 20150426
This version of libstdc++ is supported.

********************************************************************************

Device Info:

Discovered 2 devices matching:
  platform    : <any>
  device type : <any>

--------------------------------------------------------------------------------
Device 0:

  Device is supported                     : UNTESTED - Device not tested on this OS
  CL_DEVICE_NAME                          : Hainan
  CL_DEVICE_VENDOR                        : Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION                       : 1800.11 (VM)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU 
--------------------------------------------------------------------------------
Device 1:

  Device is supported                     : UNTESTED - Device running untested driver
  CL_DEVICE_NAME                          : Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  CL_DEVICE_VENDOR                        : GenuineIntel
  CL_DRIVER_VERSION                       : 1800.11 (sse2,avx)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_CPU 

If you encounter problems when using any of these OpenCL devices, please consult
this website for known issues:
https://computecpp.codeplay.com/releases/v0.1.4/platform-support-notes

********************************************************************************
Please let me know if there are any fixes or if I can do something to get round this issue.
Thanks and regards
Sayantan
[tensorflow-code-throwing-error.txt](https://github.com/tensorflow/tensorflow/files/956152/tensorflow-code-throwing-error.txt)

**Comment by drpngx** [comment] 2017-04-25 18:49
We are in the middle of a merge (https://github.com/tensorflow/tensorflow/pull/9117). It might be a good idea to patch up your code and start from there.

**Comment by rahasayantan** [comment] 2017-04-25 18:59
Thanks, I will wait for the merge to complete and restart from that point.

Regards
Sayantan

**Comment by gunan** [comment] 2017-05-19 17:35
OpenCL support in TF still is not finalized.
I recommend reaching out to CodePlay (authors of ComputeCPP) for more help on this, as the compiler is still in beta, and it may be a compiler or a runtime issue.

Also, from what I can see in Platform Support Notes in CodePlay website, they do not have support for any AMD GPUs under ubuntu 16.04
Therefore, I will close this issue.

**Closed by gunan** 2017-05-19 17:35 UTC
Labels: stat:community support, type:build/install

**Comment by rahasayantan** [comment] 2017-08-31 08:43
I am using Ubuntu 14 (Trusty) as I had mentioned earlier. Anyway, I will be eagerly waiting for TF to roll out support for AMD. Guess it was anyway a bad decision to buy AMD..

**Comment by mirh** [comment] 2017-12-10 03:10
> Also, from what I can see in Platform Support Notes in CodePlay website, they do not have support for any AMD GPUs under ubuntu 16.04

For some reason they dropped the note _description_ itself after [0.3.2](https://developer.codeplay.com/computecppce/v0.3.2/supported-platforms) docs. 
Though, it doesn't make sense. Even a year ago [cl_khr_spir](https://community.amd.com/thread/207051#2756287) was already supported in amd 'latest' closed driver. 

@DuncanMcBain do you know perhaps who wrote that part of the readme? And/or why the note "*note*" is still there, even though people are starting to report successes even on dismembered drivers over unofficial OSs?

@rahasayantan you could or could not be interested to supposed forward-port of [fglrx for 16.04](https://launchpad.net/~dokomix/+archive/ubuntu/fglrx-xenial) (god knows why it seems just so harder on ubuntu, compared to fedora or arch)

**Comment by DuncanMcBain** [comment] 2017-12-10 14:39
Hi!
The readme is written by us. To some extent, you have answered your own question there in the way you described people getting stuff working - we tend to say that any compliant, SPIR-supporting platform *should* work, but we will only describe something as supported if we know we have tested that combination of driver and hardware internally, because we can then actually reproduce failures, write new tests, get a fix implemented and so on.

That section might be due an overhaul anyway, but ultimately my advice is (and always has been): OpenCL 1.2 platforms supporting SPIR (and now SPIR-V!) should work. However, if we don't have that combination of hardware and software in our internal testing, it's unlikely we can genuinely say we support it with fixes.

(As an aside, I am sure that there was at least one release of AMD's drivers that claimed cl_khr_spir support, but when I tried it I just got crashes. Additionally, AMD employees publicly stated on Github that they were dropping SPIR support due to a lack of use, so at the time we stuck with the driver version we knew worked and we already had internally.)

**Comment by mirh** [comment] 2017-12-10 22:44
I was reading AMD itself [knows](https://community.amd.com/thread/221158#2832345) their latest proprietary driver (at least on linux) is shit with SPIR. 

Then, it's legit that you just claim as "supported" (even though maybe a better word could be tested or certified) platforms you tested.. But I think it's pretty blatant that "_somehow_ broken support" is different than no support at all. 

p.s. I'm not sure why in the world they'd drop SPIR, considering SPIR-V is part of core CL 2.1, vulkan, and soon even vulkanCL or whatever they are gonna call it. 
p.p.s hope you are gonna fix those docs 🙃 :
* bring back that amd-4 note description
* recheck your results in light of everything people said in #22 (TL;DR amdgpu-pro is supposedly working)
* idk about ubuntu (as I linked above), but reliable patches to get fglrx to work even on 4.15 are available for both [fedora](https://github.com/imageguy/fglrx-for-Fedora) and [arch](https://aur.archlinux.org/packages/catalyst-total/) - and for as much certainly unofficial, a slim hint could really make the day for _many_ people/newcomers

**Comment by DuncanMcBain** [comment] 2017-12-13 12:48
I believe the computecpp_info tool will describe platforms we test internally as supported, most other platforms as "untested" and those we know won't work as "unsupported". The documentation could be clearer on that point.

SPIR 1.2 and SPIR-V are very distinct formats. It might well be easier for them not to have to support 1.2 in favour of developing other IR formats, like SPIR-V.

Which AMD note 4 is that exactly? When I look at the historical docs, it looks like that is the one saying that we can't do AMD on 16.04, no? I can try to find a spare machine to test the GPUPRO driver but I don't actually have compatible hardware myself, so this might not happen. We could also add some notes about the Fedora and Arch patches though that seems more flaky than I'd be comfortable suggesting.

What I will say as a final thought is that we are planning to continue updating the compiler to tip Clang, which will increase the number of IR formats that we can support (for example, recently we enabled PTX output from compute++, and while it's early days we can run some basic samples on nvidia hardware).

**Comment by mirh** [comment] 2017-12-13 14:32
> I believe the computecpp_info tool will describe platforms we test internally as supported, most other platforms as "untested" and those we know won't work as "unsupported". The documentation could be clearer on that point.

Cool, that would really be neat. 

> SPIR 1.2 and SPIR-V are very distinct formats. It might well be easier for them not to have to support 1.2 in favour of developing other IR formats, like SPIR-V.

Well, then in turn you'd be dumping OpenCL 1.2 support altogether. 
Which to be really honest, at least atm is the biggest selling point of all the affair. 

> Which AMD note 4 is that exactly? When I look at the historical docs, it looks like that is the one saying that we can't do AMD on 16.04, no?

Yes, and notice how it's still there, mentioned in the table notes.. Yet no description is currently available. 
p.s. I just noticed it kind of moved inside AMD-2 now. 

> I can try to find a spare machine to test the GPUPRO driver but I don't actually have compatible hardware myself, so this might not happen.

FTR folks over at #22 are calling it a day. 
I wouldn't know if it was something fixed on theirs or yours part though. 

> We could also add some notes about the Fedora and Arch patches though that seems more flaky than I'd be comfortable suggesting.

I can totally see it. 
Maybe just simply a something between brackets at the end of current note could do it too?
With or without even links, if you don't feel at ease. 

> What I will say as a final thought is that we are planning to continue updating the compiler to tip Clang, which will increase the number of IR formats that we can support (for example, recently we enabled PTX output from compute++, and while it's early days we can run some basic samples on nvidia hardware).

Absolutely, keep going. 
With that, AFAIK you are the most (possibly only) cross-vendor library/path out there for accelerating ML/DNN.

**Comment by DuncanMcBain** [comment] 2017-12-15 22:16
>Well, then in turn you'd be dumping OpenCL 1.2 support altogether.
>Which to be really honest, at least atm is the biggest selling point of all the affair.

I'm not sure I follow you here - SPIR is optional, not core, so there is nothing to say they have to support SPIR 1.2 over anything else. I believe the SYCL specification rather deliberately doesn't demand a particular IR format either. Or am I misunderstanding you?
>Yes, and notice how it's still there, mentioned in the table notes.. Yet no description is currently available.
>p.s. I just noticed it kind of moved inside AMD-2 now.

@rodburns could we maybe get this updated with the next release? These are all useful hints for our documentation.
> With that, AFAIK you are the most (possibly only) cross-vendor library/path out there for accelerating ML/DNN.

I've always felt that we should be proud of how compatible ComputeCpp is. We'd also not have managed this without the open standards work driving this either!

**Comment by mirh** [comment] 2017-12-15 22:36
> Or am I misunderstanding you?

If you OCL 1.2 support relies on the mandatory support of SPIR 1.2, I assumed dropping this latter also inversely entailed dropping opencl 1.2 compatibility. 

> @rodburns could we maybe get this updated with the next release? These are all useful hints for our documentation.

I'm also in the process of *\*finally\** getting to test said arch fglrx platform (on kernel 4.14 nonetheless) on a humble AMD E-350 [that for as much a low power apu, still has a fully fledged gpu (*yes I'm looking at you intel*)]
Might you be interested to results?
