### ISSUE TITLE
Unexpected log output in Tensorboard

### ISSUE THREAD

**Issue by qwesdfok** [tensorflow/tensorflow#27034] opened 2019-03-22 10:44 UTC
Env:
Tensorflow-GPU 1.13.1
Tensorboard 1.13.1
TensorboardX 1.6
Installed time: 2019/03/22
Installed from PIP
OS: Windows 10
Python version: 3.7
CUDA: 10

Problem:
I use command "tensorboard --logdir ... --host 127.0.0.1" to run the program, and there are many log output in the command. And not add "-v" parameter..

TensorBoard 1.13.1 at http://127.0.0.1:6006 (Press CTRL+C to quit)
I0322 17:56:22.683215 10068 _internal.py:97] 127.0.0.1 - - [22/Mar/2019 17:56:22] "GET / HTTP/1.1" 200 -
I0322 17:56:23.341972 12492 _internal.py:97] 127.0.0.1 - - [22/Mar/2019 17:56:23] "GET /font-roboto/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 HTTP/1.1" 200 -
I0322 17:56:24.188966 10068 _internal.py:97] 127.0.0.1 - - [22/Mar/2019 17:56:24] "GET /tf-interactive-inference-dashboard/editedexample.png HTTP/1.1" 200 -
...

This does not appare in the previous version. I not sure whether it is a bug or a new feature.

**Comment by jvishnuvardhan** [comment] 2019-03-22 17:12
@qwesdfok Could you provide a small code to reproduce your bug? Thanks!

**Comment by qwesdfok** [comment] 2019-03-23 03:11
@jvishnuvardhan 
For example,

from tensorboardX import SummaryWriter
import numpy as np
import time
writer = SummaryWriter("tb_log")
step = 0
while True:
    writer.add_scalar("loss", np.random.rand(), step)
    time.sleep(1.0)
    step += 1

And run tensorboard. Open 127.0.0.1:6006 in Chrome browser. The following output will appare in the command line.

tensorboard --logdir E:\PersonalData\Project\PyProject\Inpainting-Conv\tb_log --host 127.0.0.1
TensorBoard 1.13.1 at http://127.0.0.1:6006 (Press CTRL+C to quit)
I0323 11:05:51.970985  9496 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:51] "[37mGET / HTTP/1.1[0m" 200 -
I0323 11:05:52.261211 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /font-roboto/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 HTTP/1.1[0m" 200 -
I0323 11:05:52.833691  9496 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /tf-interactive-inference-dashboard/editedexample.png HTTP/1.1[0m" 200 -
I0323 11:05:52.834676 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /tf-interactive-inference-dashboard/distance.png HTTP/1.1[0m" 200 -
I0323 11:05:52.836671 18396 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /tf-interactive-inference-dashboard/explorecounterfactuals.png HTTP/1.1[0m" 200 -
I0323 11:05:52.839663  8384 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /tf-interactive-inference-dashboard/pdplots.png HTTP/1.1[0m" 200 -
I0323 11:05:52.905486 18396 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/runs HTTP/1.1[0m" 200 -
I0323 11:05:52.905486 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/environment HTTP/1.1[0m" 200 -
I0323 11:05:52.906484  9496 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/experiments HTTP/1.1[0m" 200 -
I0323 11:05:52.909475  8384 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/plugins_listing HTTP/1.1[0m" 200 -
I0323 11:05:52.939399  8384 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /font-roboto/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2 HTTP/1.1[0m" 200 -
I0323 11:05:52.945382 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/runs HTTP/1.1[0m" 200 -
I0323 11:05:52.947374  8384 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/environment HTTP/1.1[0m" 200 -
I0323 11:05:52.947374  9496 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/plugins_listing HTTP/1.1[0m" 200 -
I0323 11:05:52.949370 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:52] "[37mGET /data/experiments HTTP/1.1[0m" 200 -
I0323 11:05:53.057084 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:53] "[37mGET /data/plugin/scalars/tags HTTP/1.1[0m" 200 -
I0323 11:05:53.080021 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:53] "[37mGET /data/plugin/scalars/tags HTTP/1.1[0m" 200 -
I0323 11:05:53.091987 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:53] "[37mGET /font-roboto/d-6IYplOFocCacKzxwXSOJBw1xU1rKptJj_0jans920.woff2 HTTP/1.1[0m" 200 -
I0323 11:05:53.139859 11452 _internal.py:97] 127.0.0.1 - - [23/Mar/2019 11:05:53] "[37mGET /data/plugin/scalars/scalars?tag=loss&run=.&experiment= HTTP/1.1[0m" 200 -

**Comment by stephanwlee** [comment] 2019-03-25 22:47
Hi @qwesdfok, thanks for raising the issue. I was able to reproduce this and it looks like it is related to https://github.com/tensorflow/tensorboard/issues/2028. `pip freeze` should reveal that you have werkzeug of `0.15.1`. We will address it soon. Thanks!

**Comment by nfelt** [comment] 2019-03-25 23:01
Duplicate of https://github.com/tensorflow/tensorboard/issues/2028

**Comment by qwesdfok** [comment] 2019-03-26 01:28
Yes, I checked the version of werkzeug and it is 0.15.1. I will downgrade werkzeug, if it is needed. Thanks!

**Comment by nfelt** [comment] 2019-06-21 23:35
Closing since this is a dupe, please follow https://github.com/tensorflow/tensorboard/issues/2028

**Closed by nfelt** 2019-06-21 23:35 UTC
Labels: TF 1.13, comp:tensorboard, type:bug/performance

**Comment by StenkinVlad** [comment] 2019-11-19 12:39
Had the same problem with TensorBoard 
after fitting logs created but when used in terminal
`tensorboard --logdir logs/fit`
got bad link that did not work in Google Chrome
`TensorBoard 1.14.0 at http://DESKTOP-CC81AQ5:6006/ (Press CTRL+C to quit)`
and in IE was nothing with this  python response
`I1119 15:12:22.167826  3004 _internal.py:122] ....... - - [19/Nov/2019 15:12:22] "?[37mGET / HTTP/1.1?[0m" 200 -`

Fix this really easy - just **update tensorboard from 1.14 to 2.0** 
and left tf version 1.14 (still have problem with tf 2.0 and CUDA 10.0)
and now goog python response
`TensorBoard 2.0.0 at http://localhost:6006/ (Press CTRL+C to quit)`
