### ISSUE TITLE
TimeDistributed wrapper works with "standalone" Keras, but not with "built-in" Keras

### ISSUE THREAD

**Issue by adamjones1** [tensorflow/tensorflow#17200] opened 2018-02-22 19:34 UTC
The following lines worked with Keras (2.0.8) and Tensorflow (pre 1.4).

`input_tensor = Input((input_epochs_per_output_epoch, samples_per_epoch, features_per_epoch))`

`inner_intermediate = TimeDistributed(BatchNormalization(axis = -1), name="bn_input")(input_tensor)`

`many lines...`

`inner_out = TimeDistributed(Bidirectional(GRU(intermediate_features, return_sequences=False, recurrent_dropout=recurrent_dropout, dropout=normal_dropout, kernel_initializer=kernel_initializer, kernel_regularizer=l2(l2_lambda), implementation=lstm_implementation), merge_mode='concat'), name="inner_out")(inner_intermediate)`

However, with Tensorflow 1.5.0, using the Keras within Tensorflow, the final line fails with:
> ValueError: as_list() is not defined on an unknown TensorShape.

Because there are a lot of lines between 2 and 3, which have various layers wrapped by TimeDistributed, I've figured out that it is only GRU and LSTM layers that cause this error. I've tried specifying the input_shape for both the the wrappers and/or the layers themselves, to no avail.

**Comment by tensorflowbutler** [comment] 2018-02-23 07:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by adamjones1** [comment] 2018-02-23 15:20
I didn't realize that those questions were necessary. Answers below.
Have I written custom code: No, using standard keras Functional API
OS Platform and Distribution: macOS 10.13 & Ubuntu 16.04
TensorFlow installed from: macOS: pip & Ubuntu: conda
TensorFlow version: 1.5.0
Bazel version: N/A (was not compiled)
CUDA/cuDNN version: Ubuntu: CUDA 9
GPU model and memory: Ubuntu: GeForce 1080 Ti
Exact command to reproduce: written in initial post

**Comment by adamjones1** [comment] 2018-02-28 15:44
**new finding**
The above lines work perfectly if I use the keras package (2.1.4) directly, instead of keras included in Tensorflow.

**Comment by tensorflowbutler** [comment] 2018-04-21 18:26
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-06 18:29
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:00
Nagging Assignee @fchollet: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:53
Nagging Assignee @fchollet: It has been 64 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:16
Nagging Assignee @fchollet: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:07
Nagging Assignee @fchollet: It has been 94 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lgeiger** [comment] 2018-07-17 15:13
@adamjones1 It looks like this has been fixed in the latest tensorflow nightly.

**Comment by tensorflowbutler** [comment] 2018-08-01 18:50
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-16 20:02
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 19:29
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:34
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:45
Nagging Assignee @fchollet: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:46
Nagging Assignee @fchollet: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:41
Nagging Assignee @fchollet: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment] 2018-11-09 22:15
Closing as this is resolved

**Closed by wt-huang** 2018-11-09 22:15 UTC
Labels: stat:awaiting tensorflower
