### ISSUE TITLE
`tf.experimental.numpy.remainder` outputs nan for 0/inf on GPU

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#58369] opened 2022-10-29 20:53 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0, 2.12.0-dev20221029

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

`tf.experimental.numpy.remainder` outputs `nan` for `0/inf` on GPU. In contrast, it outputs the correct result `0` on CPU.

remainder(0, np.inf):

- GPU: nan
- CPU: 0.0
- numpy: 0.0

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

with tf.device('/device:CPU:0'):
    print(tf.experimental.numpy.remainder(0, np.inf)) # 0.0
with tf.device('/device:GPU:0'):
    print(tf.experimental.numpy.remainder(0, np.inf)) # nan

print(np.remainder(0, np.inf)) # 0.0
```

### Relevant log output

```shell
tf.Tensor(0.0, shape=(), dtype=float64)
tf.Tensor(nan, shape=(), dtype=float64)
0.0
```
</details>

**Comment by bhack** [comment] 2022-10-30 14:24
We don't have explicit tests for `mod` with non int/unit input types:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/math_ops/cwise_ops_binary_test.py#L335

**Comment by bhack** [comment] 2022-10-30 14:26
```python
import numpy as np
import tensorflow as tf
x = np.arange(1, 13, 2).reshape(1, 3, 2).astype(np.int32)    
y = np.arange(1, 7, 1).reshape(1, 3, 2).astype(np.int32)
with tf.device("CPU"):
  res = tf.math.mod(x,tf.cast(np.inf,dtype=tf.float32))
  print(res)
with tf.device("GPU"):
  res = tf.math.mod(x,tf.cast(np.inf,dtype=tf.float32))
  print(res)
```

```python
tf.Tensor(
[[[ 1.  3.]
  [ 5.  7.]
  [ 9. 11.]]], shape=(1, 3, 2), dtype=float32)
tf.Tensor(
[[[nan nan]
  [nan nan]
  [nan nan]]], shape=(1, 3, 2), dtype=float32)
```

**Comment by tilakrayal** [comment] 2022-10-31 13:49
@fuzzyswan,
I tried to execute the mentioned code and was able to get the desired output. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/973d2ccfed819bf0f2bab2a219c0a35f/untitled719.ipynb) and confirm if anything is missing in this case. Thank you!

**Comment by bhack** [comment] 2022-10-31 14:05
> and was able to get the desired output.

What do you mean?

**Comment by fuzzyswan** [comment] 2022-11-01 15:32
@tilakrayal 
I think the output is not desired as the GPU outputs nan.

**Comment by tilakrayal** [comment] 2022-11-07 14:19
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/fdd25a38ee8d7d7feb02ff23978bf8e1/untitled733.ipynb).

**Comment by sherhut** [comment] 2023-01-06 09:30
This was caused by a bug in LLVM, which was fixed in https://github.com/llvm/llvm-project/commit/2c3f82b7759691f3b67f7e5940e95ac3434b1a9c.

**Closed** 2023-01-06 16:23 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, comp:gpu, TF 2.10
