### ISSUE TITLE
Segmentation fault when GPUs are already used

### ISSUE THREAD

**Issue by nouiz** [tensorflow/tensorflow#152] opened 2015-11-11 21:50 UTC
When I set the nvidia driver in exclusive mode and one of the GPU is already used by another process, I get a segmentation fault:

```
$ python -c "import tensorflow as tf;tf.InteractiveSession()"
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 12
Segmentation fault (core dumped)
```

If I limit the visible GPUs to only GPUs that have nothing running on them, it don't segfault:

```
$CUDA_VISIBLE_DEVICES=1 python -c "import tensorflow as tf;tf.InteractiveSession()"
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 12
I tensorflow/core/common_runtime/gpu/gpu_init.cc:88] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:09:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:112] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:122] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:643] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0)
I tensorflow/core/common_runtime/gpu/gpu_region_allocator.cc:47] Setting region size to 12105628263
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 12
```

Here is my output of nvidia-smi:

```
$ nvidia-smi 
Wed Nov 11 16:48:27 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750     Off  | 0000:05:00.0      On |                  N/A |
| N/A   48C    P8     0W /  38W |     25MiB /  2047MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:06:00.0     Off |                  N/A |
| 42%   82C    P2   127W / 250W |    262MiB / 12287MiB |     39%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 22%   46C    P8    17W / 250W |     23MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:0A:00.0     Off |                  N/A |
| 22%   37C    P8    15W / 250W |    361MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1171    G   /usr/bin/X                                      17MiB |
|    1     32740    C   python                                         209MiB |
|    3      9429    C   python                                         336MiB |
+-----------------------------------------------------------------------------+

```

I suppose that in the code that check the available GPUs, it don't handle correctly a case when one of the GPUs can't be used.

**Comment by zheng-xq** [comment] 2015-11-11 23:49
@nouiz, you are correct in your analysis. TensorFlow tries to grab all the GPU it sees from the system that passes its criteria. CUDA_VISIBLE_DEVICES is the solution I would suggest. Please let us know if that is not enough.

**Comment by skearnes** [comment] 2015-11-12 16:03
@zheng-xq +1 on CUDA_VISIBLE_DEVICES; this fixes the issue for me.

**Comment by vrv** [comment] 2015-11-13 22:20
Re-open if CUDA_VISIBLE_DEVICES isn't good enough

**Comment by noisychannel** [comment] 2015-12-11 00:05
@vrv This is still a problem when there are multiple GPUs (in exclusive mode) on the machine and some of them have processes running on them. Setting CUDA_VISIBLE_DEVICES is not ideal if you do not actually know which GPU is available. nvidia-smi will only show the current state of the GPUs and there's no way of ensuring that while you spawn your process, no other process occupied the GPU you set for use. Is there a way of polling GPUs and assigning the process to the first available, compatible GPU on the machine instead of having to manually specify the GPU id?

PS: I cannot reopen this issue.

**Comment by vrv** [comment] 2015-12-11 00:08
@zheng-xq: is it possible to query the status of the exclusive mode bit?

**Comment by zheng-xq** [comment] 2015-12-11 04:57
@noisychannel, even if we can query which GPU is available, and by the time we actually try to assign the GPU, it could be taken by other processes. This is not very different from having a script query GPU status through nvidia-smi, and set the GPU id accordingly. 

The only way I can think of that makes your case easier is actually to create the context, and if it fails, ignore that failure and move on to the next. However, this is undesirable for many more common cases, where such context creation errors are signs of bigger problems.

**Comment by noisychannel** [comment] 2015-12-11 18:17
The established way to do this seems to be: 

1. Set the GPUs to operate in exclusive mode.
2. Do not call ``cudaSetDevice()``.
3. When you run your program, it will try and create the context on the first GPU and fail if the GPU is busy.  Assuming you're using CUDART, it should *silently* try and create the context on the next GPUs and fail if all GPUs are busy. 

As for exception handling while creating the context, it seems like the this scenario can be handled with the exceptions returned by ``cuCtxCreate()``. 

A solution like this is optimal when you delegate the scheduling of your jobs to something like SGE and cannot trust the script based querying approach which I think is common for large clusters.

**Comment by zheng-xq** [comment] 2015-12-11 19:15
This would work fine if the framework only wants to use a single GPU. TensorFlow is designed to use multiple GPU seamlessly at the same time. So at the initialization stage, it grabs all the visible devices that are compatible, since the client program might use all of them. The actual device used is only known at the graph construction/execution time, which is at a much later stage.

For most of our existing users, the GPUs that are available to a particular job is known when it starts. So it is okay for TensorFlow to take all of them. A few options to think about: 

1. Is it possible for the job scheduler to reserve the GPUs in your clusters? That would work best with TensorFlow. 
2. If you only know the list of candidate GPUs, and the number of GPUs to use, we can add a special mode where we try to create context in the candidate list, and stops if desired number of GPUs are taken. This requires more plumbing to both TensorFlow and the underlying Stream-Executor that actually manages GPUs. We would much prefer #1 if that is possible for you.

**Comment by noisychannel** [comment] 2015-12-11 19:29
For 1: AFAIK, the only responsibility of most job schedulers is to ensure that you will have access to the number of GPUs you have asked for on the machine which has been assigned to you. It leaves the actual CPU/GPU scheduling of the processes on that machine to the OS/Cuda driver. Also, hypothetically, if the scheduler was to attempt something of this sort, it would not be able to block the GPU without creating something like a context. 

For 2 : I understand that this is probably painful. However, it does add a more general set of features. The case where I want ``k`` out of ``n`` GPUs on the machine is most prominent. Eg,, it would be able to handle the case where the candidate list is the set of all GPUs on the machine and I want only 2 available and compatible GPUs from that list. Having the ability to specify how many GPUs you want to use will be a great addition and this will tie in perfectly with most job schedulers. So to tensorflow, I specify, I want to run this thing on 2 GPUs and I tell the job scheduler that I need 2 GPUs.

**Comment by skearnes** [comment] 2015-12-11 19:34
Drive-by comment: the sysadmin for my local SGE cluster was able to have an environment variable set that tells me which GPUs my jobs have been assigned. I then use this variable to set CUDA_VISIBLE_DEVICES. I would guess that most common schedulers have similar capabilities, although they may require root-level tweaking.

**Comment by noisychannel** [comment] 2015-12-11 21:45
This is useful to know. However, something like this would require all jobs on the cluster to respect that environment variable when using GPUs. And it takes away some of the scheduling responsibility that should ideally belong to the CUDA driver, adding another layer of complexity. In fact, most other toolkits that are GPU capable will not require something like this and as long as the GPUs are set in exclusive mode, they work just fine.

**Comment by jtrmal** [comment] 2015-12-11 21:56
Another drive-by comment: when the allocation fails, the app actually segfaults on our machines. That does not provide any possibility for the user to recover from it at the python level. 
A good-enough solution would be
a) throw an exception so that user can it catch and try (for example) another device
b) ideally, adding /gpu:auto which would just iterate through the devices and allocate the one that is available.

**Comment by zheng-xq** [comment] 2015-12-14 19:00
@noisychannel, please see if you can work around this issue at the moment. Meanwhile, I will investigate if we can officially support the soft-try-and-device-limit approach in TensorFlow.

**Comment by noisychannel** [comment] 2015-12-14 22:04
Okay. Thanks. Keep me posted.

**Comment by girving** [comment] 2016-03-08 19:15
@zheng-xq: Is this still an issue?

**Comment by noisychannel** [comment] 2016-03-09 00:02
I'm not aware of a "soft-try-and-assign-device" implementation in Tensorflow.

**Comment by aselle** [comment] 2016-08-15 22:50
Closing this automatically due to lack of recent activity. Please reopen when new information becomes available. @zheng-xq, please re-open if you plan to be still working on this.

**Comment by AndreasMadsen** [comment] 2016-10-21 16:11
@aselle I'm on a shared multi GPU machine and this doesn't appear to have been fixed.

**Comment by aselle** [comment] 2016-10-21 16:19
@AndreasMadsen, what is your exact hardware/software configuration and steps to reproduce (see the new issue template).

**Comment by AndreasMadsen** [comment] 2016-10-22 14:10
The steps are the same @nouiz describe. `python -c "import tensorflow as tf;tf.InteractiveSession()"` fails with a Segmentation fault. Adding `CUDA_VISIBLE_DEVICES=1` fixes it.

I have a hunch that it might be related to mixing GPUs with diffrent CUDA capabilities. But I have no way to test that.

```
Sat Oct 22 16:07:37 2016
+------------------------------------------------------+
| NVIDIA-SMI 352.39     Driver Version: 352.39         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40c          On   | 0000:02:00.0     Off |                    0 |
| 23%   23C    P8    18W / 235W |     22MiB / 11519MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20c          On   | 0000:03:00.0     Off |                    0 |
| 30%   20C    P8    16W / 225W |     13MiB /  4799MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K20c          On   | 0000:83:00.0     Off |                    0 |
| 30%   22C    P8    16W / 225W |     13MiB /  4799MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  On   | 0000:84:00.0     Off |                  N/A |
| 22%   31C    P8    29W / 250W |    161MiB / 12287MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

```

**Comment by yaroslavvb** [comment] 2016-10-25 18:32
A backtrace can be useful here. Either run under pdb directly, or examine
core file under pdb (ie, set ulimit -c unlimited, get core file, open core
file with pdb and using pywraptensorflow.so as binary)

**Comment by casiciaco** [comment] 2017-01-13 13:00
Hi,
I am still observing problems w/ GPU reservation in a 16 GPU node. For some GPUs, when reserving the GPU with CUDA_VISIBLE_DEVICES, it fails to reserver the node. In TF 0.10 it generated a coredump. In TF 0.12 it complains about not being able to start the tf.Session.

The node status is this:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     46690    C   /usr/bin/python2.7                            2326MiB |
|    2     13781    C   python                                        3456MiB |
|    3     26767    C   python                                         282MiB |
|    4     53525    C   /usr/bin/python2.7                             740MiB |
|    5     13782    C   python                                        3456MiB |
|    6      9427    C   /usr/bin/python2.7                            3455MiB |
|    9     53527    C   /usr/bin/python2.7                             740MiB |
|   10     53222    C   /usr/bin/python2.7                             740MiB |
|   11     53526    C   /usr/bin/python2.7                             740MiB |
|   12     54930    C   /usr/bin/python2.7                            1085MiB |
|   13     54926    C   /usr/bin/python2.7                             785MiB |
|   14     54927    C   /usr/bin/python2.7                             785MiB |
+-----------------------------------------------------------------------------+
```
And when I use CUDA_VISIBLE_DEVICES=1 , which is free:
```
Before reservation the free GPUs  [1, 7, 8, 15]
Setting CUDA_VISIBLE_DEVICES=1
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
Traceback (most recent call last):
...
 File "PATH/run.py", line 138, in reserveGPUs
    with  tf.Session() as session:
  File "PATH/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1186, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "PATH/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 551, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "PATH/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/amr/tools/tensorflow/0.12-cuda7.5/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

**Comment by casiciaco** [comment] 2017-01-13 13:19
Actually, this also fails in the above example:
```
 CUDA_VISIBLE_DEVICES=1 python2.7 -c "import tensorflow as tf;tf.InteractiveSession()"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.7.5 locally
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
...
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```
but
```
CUDA_VISIBLE_DEVICES=8 python2.7 -c "import tensorflow as tf;tf.InteractiveSession()"
```
and
```
CUDA_VISIBLE_DEVICES=15 python2.7 -c "import tensorflow as tf;tf.InteractiveSession()"
```
work.

Note that the same happens with the new ConfigProto options: https://github.com/tensorflow/tensorflow/issues/1888
```
python2.7 -c "import tensorflow as tf; config_proto = tf.ConfigProto(); config_proto.gpu_options.visible_device_list=\"1\"; tf.Session(config=config_proto)"
```
doesn't work but
```
python2.7 -c "import tensorflow as tf; config_proto = tf.ConfigProto(); config_proto.gpu_options.visible_device_list=\"8\"; tf.Session(config=config_proto)"
``` 
works.

**Comment by cbquillen** [comment] 2017-01-18 16:01
One problem that I ran into with using both CUDA_VISIBLE_DEVICES and gpu_options.visible_device_list is that GPU numbering can be different between Nvidia NVML (and nvidia-smi for example) and between what you get from cuda if you do cuDeviceGet().  On some systems, NVML and nvidia-smi apparently order the card numbers by sorting the PCI id.  <b>Cuda doesn't necessarily use the same order.</b>  This can happen on a machine where all the GPU cards are identical.

The result is a crash when CUDA_VISIBILE_DEVICES is used to select a GPU.  With gpu_options.visible_device_list you get a failure opening the session for a mismatched GPU that isn't actually available.

Here's the mapping I get on a particular system at work:
NVML id 0 maps to Cuda index 4
NVML id 1 maps to Cuda index 5
NVML id 2 maps to Cuda index 6
NVML id 3 maps to Cuda index 7
NVML id 4 maps to Cuda index 0
NVML id 5 maps to Cuda index 1
NVML id 6 maps to Cuda index 2
NVML id 7 maps to Cuda index 3
NVML id 8 maps to Cuda index 8
NVML id 9 maps to Cuda index 9
NVML id 10 maps to Cuda index 10
NVML id 11 maps to Cuda index 11
NVML id 12 maps to Cuda index 12
NVML id 13 maps to Cuda index 13
NVML id 14 maps to Cuda index 14
NVML id 15 maps to Cuda index 15

Here is the python that generated this:

```
#!/usr/bin/env python

import pynvml
import os
import ctypes

cuda = ctypes.CDLL('libcuda.so')
cuda_device = ctypes.c_int32(0)
cuda_pci_bus = ctypes.c_int32(0)
cuda_pci_slot = ctypes.c_int32(0)

if cuda.cuInit(ctypes.c_int32(0)) != 0:
    raise Exception("Cuda failure")
total_gpus = ctypes.c_int32(0)
if cuda.cuDeviceGetCount(ctypes.byref(total_gpus)) != 0:
    raise Exception("Cuda failure")

pci_map = {}
for gpu in range(total_gpus.value):
    if cuda.cuDeviceGet(ctypes.byref(cuda_device), ctypes.c_int32(gpu)) != 0:
        raise Exception("Cuda failure")
    if cuda.cuDeviceGetAttribute(ctypes.byref(cuda_pci_bus), ctypes.c_int32(33), cuda_device) != 0:
        raise Exception("Cuda failure")
    if cuda.cuDeviceGetAttribute(ctypes.byref(cuda_pci_slot), ctypes.c_int32(34), cuda_device) !=0:
        raise Exception("Cuda failure")
    # The below is correct on my system but...
    pci_string = "0000:%02X:%02X.0" % (cuda_pci_bus.value, cuda_pci_slot.value)
    pci_map[pci_string] = gpu

pynvml.nvmlInit()
assert pynvml.nvmlDeviceGetCount() == total_gpus.value

for gpu in xrange(total_gpus.value):
    h = pynvml.nvmlDeviceGetHandleByIndex(gpu)
    bus_id = pynvml.nvmlDeviceGetPciInfo(h).busId
    print "NVML id {} maps to Cuda index {}".format(gpu, pci_map[bus_id])

```

**Comment by yaroslavvb** [comment] 2017-01-18 17:05
@cbquillen do I understand it correctly that the problem arises only when you use `CUDA_VISIBLE_DEVICES` mechanism to select the GPU device used by TensorFlow, and some other mechanism (which?) to select GPU device used by another program?

**Comment by vrv** [comment] 2017-01-18 17:16
Indeed, visible_device_list deals with what is provided at runtime via the cuGetDevice API -- how external drivers and processes remap the physical ID to the 'visible id' is out of TensorFlow's control, and it sounds like you agree, that visible_device_list must use f(N), not N, since f is not something TF controls.

I believe our documentation is pretty clear on this point: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L48 . -- let us know if there's any further documentation that might help?

**Comment by cbquillen** [comment] 2017-01-18 17:17
@yaroslavvb 

I am running into this in the case where exclusive GPU access is turned on and there are other processes using some GPUs on the machine.  If I find a free GPU subset using nvidia-smi (or the NVML library) and try to limit Tensorflow to using this subset via CUDA_VISIBLE_DEVICES or gpu_options.visible_device_list in the Tensorflow config_proto, the result is a request for busy GPUs unless I use the mapping derived by looking at PCI-ids.

**Comment by yaroslavvb** [comment] 2017-01-18 17:25
Hm, that's kind of annoying actually, I've also been parsing `nvidia-smi` generate `CUDA_VISIBLE_DEVICES` on shared computers (along the lines of [setup_one_gpu](http://stackoverflow.com/a/41638727/419116). Haven't run into problems yet, but it would be nice to have a work-around that works reliably.

**Comment by cbquillen** [comment] 2017-01-18 17:29
@vrv 

The problem is that users will see the ordering provided by nvidia-smi (sorted by PCI-Id) and try to use it, not realizing it actually has nothing to do with what CUDA_VISIBLE_DEVICES actually selects.  Now a lot of people think this is an NVidia bug, and it's possible that they agree and fix it in newer drivers.  However it might be worth adding a prominent warning in the documentation to the effect that this problem exists.  Otherwise you will continue to get queries about it.

**Comment by vrv** [comment] 2017-01-18 17:34
I agree that this is a problem.  I'm not sure if NVidia would prefer people to not use the cuGetDevice API in favor of whatever nvidia-smi is using.  Perhaps @benbarsdell or @cliffwoolley might know?

In lieu of that, would you like to add the warning to the documentation somewhere?  You probably know best where others like you would go looking for it :)

**Comment by cbquillen** [comment] 2017-01-18 17:50
@vrv
A short warning in tensorflow.Session about using CUDA_VISIBLE_DEVICES with a link would probably help.  The visible_device_list doc config.proto would be a place where the a complete  problem is described and where you would link to.

stracing nvidia-smi reveals that it loads libnvidia-ml.so.  So it is using NVML and so could Tensorflow.

**Comment by vrv** [comment] 2017-01-18 17:53
I was thinking documentation rather than source code might be better: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/using_gpu/index.md#using-gpus as a possible area to write a short section on it?

cc @zheng-xq: I know he had reservations about adding visible_device_list for this exact reason of confusion -- perhaps he can weigh in if he wants.

**Comment by noisychannel** [comment] 2017-01-18 18:17
This may be helpful to some users who are on a cluster. Often, you don't have information about which GPU has been allocated to you or which one to occupy if free, with CUDA_VISIBLE_DEVICES. 

I use this script to (https://gist.github.com/noisychannel/cdf57e2f177e98ae653230323a093d1e) to return the first free GPU and then use something like : 
```
CUDA_VISIBLE_DEVICES=`scripts/free-gpu` python 
```

**Comment by cbquillen** [comment] 2017-01-19 02:18
@yaroslavvb
Looking at the NVIDIA [docs](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars) more, I think you can get your setup_one_gpu script to work reliably if you set the CUDA_DEVICE_ORDER environment variable to PCI_BUS_ID.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:48
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by zheng-xq** [comment] 2017-12-22 17:40
If someone is interested in adding CUDA_DEVICE_ORDER='PCI_BUS_ID' support in TensorFlow, a contribution is welcome. But note that we can only override it if it is not already set. And it has to been before any potential Cuda calls are made.

**Comment by cbquillen** [comment] 2017-12-22 18:07
You can certainly set environment variables within an application before the first call to tf.Session().

**Comment by cliffwoolley** [comment] 2017-12-22 18:26
Of course it's _possible_.  Just as in C you'd use setenv().  I was just saying that for those particular environment variables, the choice is a bit specific to the combination of application and machine the application is run on.  So usually the user (or script) invoking the application would set those env vars rather than having the application set them unilaterally.  I'd argue for example that it's unwise for TF itself to set CUDA_DEVICE_ORDER, because it would undo the CUDA feature that this variable sits on top of, which is to, by default, have the "best" device be device 0; this is handy when you don't know much about the system you're running on and are just trying things out.  More sophisticated users just pick a GPU or, if really fancy, pick one based on NVML output as we're discussing here.  But we shouldn't, IMO, assume all users are so sophisticated.

**Comment by yzhuoning** [comment] 2018-04-12 18:07
`export CUDA_VISIBLE_DEVICES=0 ` solves my issue!

**Comment by wt-huang** [comment] 2018-11-10 03:14
Closing as this is resolved, free to reopen if problem persists.

**Closed by wt-huang** 2018-11-10 03:14 UTC
Labels: stat:contributions welcome

**Comment by saikrishnadas** [comment] 2020-04-04 06:22
Python 3.6.9
Tensorflow 2.1.0 gpu supported 
Cuda 10.0
TensorRT 6.0
GPU - 1
Is still get the error even after export `CUDA_VISIBLE_DEVICES=0`  or export `CUDA_VISIBLE_DEVICES=1 `

**Error log :**
```
Can't identify the cuda device. Running on device 0
Segmentation fault (core dumped)

```
