### ISSUE TITLE
Embedding layer ~10x slower in tf.function

### ISSUE THREAD

**Issue by mdanatg** [tensorflow/tensorflow#38287] opened 2020-04-06 22:26 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Standard colab environment
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): tf-nightly pip
- Python version: - Bazel
version (if compiling from source): N/A
- GCC/Compiler version (if compiling from
source): N/A
- CUDA/cuDNN version: - GPU model and memory: N/A

This is a follow-up to https://github.com/tensorflow/tensorflow/issues/29075#issuecomment-608976001, to capture a separate issue identified by @szc11121.

**Describe the current behavior**

```
import time
import tensorflow as tf
tf.__version__

class Toymodel(tf.keras.Model):
    def __init__(self, use_embedding):
        super(Toymodel, self).__init__()
        if use_embedding:
          self.emb = tf.keras.layers.Embedding(100000, 512)
        self.use_embedding = use_embedding
        self.fc = tf.keras.layers.Dense(1)

    def call(self, constant_input):
        if self.use_embedding:
          constant_input_emb = self.emb(constant_input)
        else:
          constant_input_emb = tf.expand_dims(constant_input, -1)
        logit = self.fc(constant_input_emb)
        output = tf.keras.activations.sigmoid(logit)
        return logit, output

def run_step(model, optimizer, constant_input, y):
    with tf.GradientTape() as tape:
        logit, output = model(constant_input)
        loss = tf.reduce_mean(
                        tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                                labels=tf.cast(y, dtype=tf.float32)))
    gradient = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradient, model.trainable_weights))
    return loss, output

def run_loop(in_graph, use_embedding):
  model = Toymodel(use_embedding)
  opt = tf.keras.optimizers.SGD(learning_rate=0.1, momentum=0.0)

  if in_graph:
    f = tf.function(run_step)
  else:
    f = run_step

  for _ in range(20):
      start = time.time()
      loss, output  = f(model, opt, tf.random.uniform([100], minval=0, maxval=100000), tf.random.uniform([100, 1]))
      end = time.time()
      print(end - start)

print('Eager, no embedding')
run_loop(False, False)
print('Graph, no embedding')
run_loop(True, False)
print('Eager, embedding')
run_loop(False, True)
print('Graph, embedding')
run_loop(True, True)
```

**Describe the expected behavior**

The graph versions sound be in faster in both cases (ignoring initial calls). However, the case which includes an embedding layer shows a 10x performance drop compared to the same model running eagerly:

Eager, no embedding
0.010893821716308594
0.0032660961151123047
...
Graph, no embedding
0.34873294830322266
0.0013270378112792969
...
Eager, embedding
0.4676947593688965
0.006254434585571289
...
Graph, embedding
0.5206460952758789
0.07123064994812012
...

**Comment by amahendrakar** [comment] 2020-04-07 06:36
Was able to reproduce the issue with [TF v2.2.0rc2](https://colab.research.google.com/gist/amahendrakar/6b3d4d3899eff968778f67463ae03da7/38287-tf2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/5e0e28711de26d660cfe72d6da17d9d9/38287.ipynb). Please find the attached gist. Thanks!

**Comment by szc11121** [comment] 2020-04-20 01:17
any update?

**Comment by mdanatg** [comment] 2020-04-20 11:37
@omalleyt12 @fchollet

**Comment by dathudeptrai** [comment] 2020-08-19 08:15
hi, please update and try to fix this issue. There is some people report this bugs recently. See (https://github.com/tensorflow/tensorflow/issues/42475). This bug cause slow training on language, signal model, please fix that. @mdanatg @omalleyt12 @fchollet

**Comment by jvishnuvardhan** [comment] 2021-04-02 00:01
Looks like this was resolved. Please check the performance of the four cases below. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/ea9832ac0b481990a849790f547ed40f/38287.ipynb). Thanks!

```
> Eager, no embedding
> 0.13755321502685547
> 0.005505561828613281
> ------
> 
> Graph, no embedding
> 0.30103421211242676
> 0.0021209716796875
> ------
> Eager, embedding
> 0.5504169464111328
> 0.006941795349121094
> ---
> Graph, embedding
> 0.5892281532287598
> 0.002460002899169922
> ---
```
Performance of graph mode is better than eager model as shown above. Thanks!

**Comment by szc11121** [comment] 2021-04-09 03:57
> Looks like this was resolved. Please check the performance of the four cases below. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/ea9832ac0b481990a849790f547ed40f/38287.ipynb). Thanks!
> 
> ```
> > Eager, no embedding
> > 0.13755321502685547
> > 0.005505561828613281
> > ------
> > 
> > Graph, no embedding
> > 0.30103421211242676
> > 0.0021209716796875
> > ------
> > Eager, embedding
> > 0.5504169464111328
> > 0.006941795349121094
> > ---
> > Graph, embedding
> > 0.5892281532287598
> > 0.002460002899169922
> > ---
> ```
> 
> Performance of graph mode is better than eager model as shown above. Thanks!

when will this fix release? since its tf2.4.1 now and tf2.6 seems still has a long way to go

**Comment by jvishnuvardhan** [comment] 2021-04-09 16:30
@szc11121 The following are the results with `TF2.5rc0`. May be there is a `2.5rc1` and `2.5rc2` then stable `TF2.5` (near future). If you want to use stable version, then in near future `TF2.5` will be released. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/9b2f28fc264efd38bdb1cc323d61e84c/38287.ipynb). Thanks!
```
> Eager, no embedding
> 0.12328195571899414
> 0.0040400028228759766
> 0.0034770965576171875

> Graph, no embedding
> 0.283444881439209
> 0.0018429756164550781
> 0.0014486312866210938

> Eager, embedding
> 0.5126852989196777
> 0.00421595573425293
> 0.004243135452270508

> Graph, embedding
> 0.5634112358093262
> 0.005776643753051758
> 0.0012359619140625
```

**Closed** 2021-04-16 17:21 UTC
Labels: TF 2.0, comp:keras, comp:ops, stalled, stat:awaiting response, type:performance
