### ISSUE TITLE
Tensors have values set to 0 if code is run on GPU.

### ISSUE THREAD

**Issue by berlogb** [tensorflow/tensorflow#4229] opened 2016-09-06 15:50 UTC
Hello team, 
I have a strange issue, which very well might be my own fault, but appreciate if somebody could comment on it.
TF 0.10 with CUDA 8
Running code like this on GPU (GeForce GTX Titan X) :

`import tensorflow as tf
import numpy as np
with tf.device("/gpu:0"):
    a = tf.placeholder(tf.float32, shape=[2,2])
    b = tf.placeholder(tf.float32, shape=[2,2])
    r = tf.squared_difference(a, b)
   
t1 = np.asarray([[1,1],[1,-5]])
t2 = np.asarray([[2,3],[4,5]])

feed_dict = {a:t1, b:t2}

with tf.Session() as sess:
     t1, t2, sd = sess.run([a,b,r], feed_dict=feed_dict)
    print("a = {}\n b = {}\n sqared diff = {}".format(t1, t2, sd))`

Prints result like this 

`a = [[ 1.  1.]
 [ 1. -5.]]
 b = [[ 2.  3.]
 [ 4.  5.]]
 sqared diff = [[ 0.  0.]
 [ 0.  0.]]`

While if I run the same code on CPU , the result is correct 
`a = [[ 1.  1.]
 [ 1. -5.]]
 b = [[ 2.  3.]
 [ 4.  5.]]
 sqared diff = [[   1.    4.]
 [   9.  100.]]`

I'd expect squared_difference to be a perfect operation for GPU and as I tensors "a" and "b" are populated properly, it doesn't look like TF has issues getting those values into GPU

Appreciate any comments on this.

Operating System: 4.4.0-34-generic #53-Ubuntu

` python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.8.0 locally
0.10.0rc0`.

**Comment by tatatodd** [comment] 2016-09-07 07:32
A couple of shots in the dark:

1. Try installing version 0.10 rather than 0.10.0rc0.  We haven't officially released 0.10 yet, but there have definitely been fixes applied since the rc "release candidate".  See the following for details on installation of 0.10; the instructions are different from "master" since 0.10 isn't officially released yet.
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation

2. I know of some other issues being tracked wrt cuda 8 in #2559 that you might want to look at.

Let me know how that goes; just ping if you're still stuck.

**Comment by berlogb** [comment] 2016-09-07 09:38
Hi
Thank you, discovered yesterday an interesting thing. It actually started working magically after some time and it seems that at the time when it wasn't working correctly, the colleague of mine was running something on the same GPU which occupied almost all memory. When that task was stopped , my example worked as expected.
So, it seems to be related to memory usage of GPU. Though, it's a bit strange that TF/GPU interaction in this situation doesn't produce some error (like when GPU runs out of memory) but instead stops calculating floats properly.

**Comment by tatatodd** [comment] 2016-09-07 16:36
I see, I think #4196 is also related, wrt concurrent usage of the same GPU.

@zheng-xq can you comment on the failures modes we're likely to see when the same GPU is used concurrently?  And also whether we can prevent these problems, or at least provide better errors?  Empirically in this case we seem to silently get bad results, while in #4196 we seem to either get bad results or strange errors.  Thanks!

**Comment by zheng-xq** [comment] 2016-09-07 17:56
TensorFlow should definitely report error in this case. It will try to grab all the memory it can get from the system, and if that fails, that should be fatal. 

Are you using a recent Cuda driver? We've had several incidents with older Cuda drivers. One remote possibility is that the Cuda driver gives the same memory to multiple running processes, and they all thought they own the memory.

**Comment by berlogb** [comment] 2016-09-07 19:52
Might be, I'm running 361.77 nvidia driver which seems to be a bit old.

```
nvidia-smi 
Wed Sep  7 21:48:02 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 361.77                 Driver Version: 361.77                    |
|-------------------------------+----------------------+----------------------+

```

**Comment by tatatodd** [comment] 2016-09-09 23:00
@berlogb have you attempted using newer drivers, to see we at least report a reasonable error when the gpu is used concurrently, rather than silently giving bad results?

**Comment by aselle** [comment] 2016-09-23 18:12
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by berlogb** [comment] 2016-10-05 13:31
@tatatodd  Sorry, work caught up with me. 
So, repeated test on old driver simply copy pasting the same code as above into 3 different python processes on the same machine, using the same CPU.

Unfortunately, doesn't seem that situation changes much. On old 361 driver I've got :
`a = [[ 1.  1.]
 [ 1. -5.]]
 b = [[ 2.  3.]
 [ 4.  5.]]
 sqared diff = [[ nan  nan]
 [ nan  nan]]`

and after upgrading 

`nvidia-smi 
Wed Oct  5 15:28:26 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.44                 Driver Version: 367.44                    |`

`sqared diff = [[ -1.70120404e+38  -1.70141163e+38]
 [             nan              nan]]
`

(When it works fine , it should look like this:
` sqared diff = [[   1.    4.]
 [   9.  100.]]`
)
Interestingly, it seems that if I open another python , I finally get error I was looking for :

`W tensorflow/core/common_runtime/gpu/gpu_init.cc:163] Not initializing the GPU, could not create GPU MachineManager. Error: Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuCtxCreate: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615`

So, looks like we do get that error, but somewhere in between, there is a situation when we fail to calculate stuff properly, but still don't through that error.

**Comment by tatatodd** [comment] 2016-10-06 20:03
@berlogb thanks for the info.  

Can you try the tensorflow 0.11 release?  I don't know of anything specific in that release that should help, but it'd be good to get on the latest version so we can narrow in on the possibilities.
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

**Comment by yaroslavvb** [comment] 2016-10-06 20:06
@berlogb TensorFlow grabs all GPU memory by default, so if you open up another process you will get `CUDA_ERROR_OUT_OF_MEMORY`

**Comment by tatatodd** [comment] 2016-10-06 20:29
@yaroslavvb I think the issue is that he's not getting `CUDA_ERROR_OUT_OF_MEMORY` under certain circumstances with multiple concurrent processes; instead he just gets arbitrary output with no errors.

**Comment by yaroslavvb** [comment] 2016-10-06 20:33
I see. I've gotten random/incorrect results from GPU when I compiled with the wrong Compute Capability. The description says it's for CUDA 8.0, but there are were no official releases for CUDA 8.0 in September. So maybe there's been a user mistake in ./configure step. A way to rule that out is to reproduce with the official wheel

**Comment by berlogb** [comment] 2016-10-06 20:43
Hi Yaroslav
Thanks, good point. It wasn't me who upgrade setup to 8.0, but looks like official release was in the end of September. I'll try to reinstall with official package and see how it goes.
Thanks.

**Comment by aselle** [comment] 2016-10-14 20:19
Did you get this to work? If so, please close the issue @berlogb.

**Comment by aselle** [comment] 2016-10-25 22:01
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.

**Closed by aselle** 2016-10-25 22:01 UTC
Labels: awaiting response

**Comment by mandarup** [comment] 2017-02-12 01:01
getting  ```CUDA_ERROR_OUT_OF_MEMORY```  when trying to run  ``convolutional.py`` from tensorflow ``models`` repo

```
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744071515537408
Traceback (most recent call last):
  File "convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "convolutional.py", line 284, in main
    with tf.Session() as sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1186, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 551, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

**Comment by yaroslavvb** [comment] 2017-02-12 02:18
@mandar that indicates your GPU doesn't have enough memory for this network

**Comment by mandarup** [comment] 2017-02-12 02:23
thanks @yaroslavvb ! jupyter notebook locked in full memory even when it was idle!

**Comment by yaroslavvb** [comment] 2017-02-12 02:25
Yes TF is greedy, it takes all GPU memory by default

**Comment by mandarup** [comment] 2017-02-12 03:13
@yaroslavvb  so TF wouldn't release GPU memory once TF session exits?
