### ISSUE TITLE
tensorflow/compiler/xla/service/allocation_tracker.cc:178:54: error: non-constant-expression cannot be narrowed from type 'std::vector<se::DeviceMemoryBase>::size_type' (aka 'unsigned long') to 'long long' in initializer list [-Wc++11-narrowing]

### ISSUE THREAD

**Issue by dbl001** [tensorflow/tensorflow#8283] opened 2017-03-10 18:12 UTC
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/8238

### Environment info
OS X 10.11.6
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Installed version of CUDA and cuDNN: 
drwxrwxrwx  15 root  wheel  510 May  3  2015 CUDA-7.0
David-Laxers-MacBook-Pro:tensorflow davidlaxer$ ls -l /Developer/NVIDIA/CUDA-7.0/lib/libcud*
-rw-r--r--  1 davidlaxer  staff  292184 Mar  6  2015 /Developer/NVIDIA/CUDA-7.0/lib/libcudadevrt.a
-rwxr-xr-x  1 davidlaxer  staff  274176 Mar  6  2015 /Developer/NVIDIA/CUDA-7.0/lib/libcudart.7.0.dylib
lrwxr-xr-x  1 davidlaxer  staff      19 Mar  6  2015 /Developer/NVIDIA/CUDA-7.0/lib/libcudart.dylib -> libcudart.7.0.dylib
-rw-r--r--  1 davidlaxer  staff  562856 Mar  6  2015 /Developer/NVIDIA/CUDA-7.0/lib/libcudart_static.a
If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

print(tensorflow.__version__)
1.0.1
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)

99e30bc6b22b259ddc6a2cfc6aec1d9ebc635da4

2. The output of `bazel version`

Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 15:54:21 2016 (1481126061)
Build timestamp: 1481126061
Build timestamp as int: 1481126061

**Comment by prb12** [comment] 2017-03-10 19:42
Closing as duplicate of #8238 
@dbl001 Not sure why you opened a new issue given you reference the identical problem?

**Closed by prb12** 2017-03-10 19:42 UTC
