### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#17981] opened 2018-03-25 07:40 UTC
Using https://github.com/hizhangp/yolo_tensorflow I get the following error. How should I fix it?
```
[jalal@goku yolo_tensorflow]$ /scratch/sjn/anaconda/bin/python train.py 
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    main()
  File "train.py", line 151, in main
    yolo = YOLONet()
  File "/scratch2/body_pose/yolo_tensorflow/yolo/yolo_net.py", line 41, in __init__
    is_training=is_training)
  File "/scratch2/body_pose/yolo_tensorflow/yolo/yolo_net.py", line 69, in build_network
    net, 64, 7, 2, padding='VALID', scope='conv_2')
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1039, in convolution
    outputs = activation_fn(outputs)
  File "/scratch2/body_pose/yolo_tensorflow/yolo/yolo_net.py", line 244, in op
    return tf.nn.leaky_relu(inputs, alpha=alpha, name='leaky_relu')
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'


```

**Comment by tensorflowbutler** [comment] 2018-03-25 19:12
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-04-10 12:34
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-25 18:59
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jart** [comment] 2018-04-26 15:50
Automatically closing due to lack of recent activity. Please file an issue with the upstream project, which might need to upgrade to TF's latest APIs.

**Closed by jart** 2018-04-26 15:50 UTC
Labels: stat:awaiting response

**Comment by inksci** [comment] 2019-07-02 11:53
TensorFlow version: '1.3.0'

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

**Comment by inksci** [comment] 2019-07-02 12:10
it seems like that we can use leaky_relu in tensorflow with version of 1.2.1, so why such a function can not be support by tensorflow with version of 1.3.0?
