### ISSUE TITLE
Error reading filenames with special characters on Windows

### ISSUE THREAD

**Issue by Arvinds-ds** [tensorflow/tensorflow#11494] opened 2017-07-14 05:03 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.6

### Describe the problem
My tensorflow script on Ubuntu 16.04 works with the following code.

```
file=tf.gfile.GFile('../../data/Gutenberg/txt/Anthony Trollope___La Vendée.txt')
text = file.read()
```

However on Windows 10
```
file=tf.gfile.GFile('../../data/Gutenberg/txt/Anthony Trollope___La Vendée.txt')
text = file.read()
```
gives the following error.  This happens when the filenames have special characters in them

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-22-669eb528a808> in <module>()
----> 1 text = file.read()

C:\Users\xxx\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    116       string if in string (regular) mode.
    117     """
--> 118     self._preread_check()
    119     with errors.raise_exception_on_not_ok_status() as status:
    120       if n == -1:

C:\Users\xxx\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     76       with errors.raise_exception_on_not_ok_status() as status:
     77         self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 78             compat.as_bytes(self.__name), 1024 * 512, status)
     79 
     80   def _prewrite_check(self):

C:\Users\xxx\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
     87         if type is None:
     88             try:
---> 89                 next(self.gen)
     90             except StopIteration:
     91                 return

C:\Users\xxx\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    464           None, None,
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:
    468     pywrap_tensorflow.TF_DeleteStatus(status)

NotFoundError: NewRandomAccessFile failed to Create/Open: ../../data/Gutenberg/txt/Anthony Trollope___La Vendée.txt : The system cannot find the file specified.
```
Note: pythons open()/read() works well on both platforms.  This error occurs for other file names  with special characters on windows too. I moved my data readers from python to tf api and data readers, the pipeline works on ubuntu but breaks in windows.

**Comment by michaelisard** [comment] 2017-07-14 16:50
@mrry do you know who owns this code?

**Comment by mrry** [comment] 2017-07-14 17:00
This looks like a duplicate of #9481, so let's close this and follow along on that thread. It's "contributions welcome" (and I think it might be on @guschmue's radar).

**Closed by mrry** 2017-07-14 17:00 UTC
Labels: stat:awaiting tensorflower
