### ISSUE TITLE
pip install tensorflow could not find a version

### ISSUE THREAD

**Issue by alexcreature** [tensorflow/tensorflow#37457] opened 2020-03-09 23:31 UTC
**System information**
- macOS Catalina version 10.15.3
- pip install tensorflow
- GPU model and memory: Intel Iris Plus Graphics 645 1536 MB

**The problem**
Both `pip install tensorflow` and `pip install tf-nightly` lead to the following error messages:

> ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)

> ERROR: No matching distribution found for tensorflow

**Comment by ymodak** [comment] 2020-03-09 23:42
Did you try updating your pip version?

**Comment by amahendrakar** [comment] 2020-03-11 06:01
@alexcreature.

As per the [documentation](https://www.tensorflow.org/install) TensorFlow 2 packages require a pip version >19.0.

Could you please try the following commands and let us know if it works.
`python3 -m pip install --upgrade pip` or `pip install --upgrade pip` and then try 

`pip install tensorflow`

Thanks!

**Comment by NeilClack** [comment] 2020-03-13 03:32
I've encountered this same error as well.
Source built Python 3.7.6 and Pip 20.0.2 running on Ubuntu. I've tried this both inside and out of a pipenv shell with no change to the results.

I should be able to provide any other information that will help solve this, as it's really hurting me trying to get this running for 4 days straight now with different configurations within Ubuntu (and windows, I think, unsure as I do not remember)

Error Message: 

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by dA505819** [comment] 2020-03-17 16:31
@alexcreature Try updating pip version by:
``` 
pip install --upgrade pip
```
and the you can again install tensorflow by:
```
pip install tensorflow
```
or you can specify version which you want to install.

**Comment by NeilClack** [comment] 2020-03-17 17:49
This seems to be the same as an issue I had previously with both Windows 10 and Ubuntu 18 and Ubuntu 16, no matter the operating system.
The previous issue ( #37205 ) was closed because I proposed a WORK AROUND of downloading the .whl and installing Tensorflow through the downloaded wheel, which worked just fine for me.

Something is broken in the pypi pipeline of installation and needs to be taken care of...

**Comment by mihaimaruseac** [comment] 2020-03-17 18:10
Yes, the issue is that systems use old `pip` / `setuptools` by default and these don't know how to install packages with manylinux2010 tags. That's why you need to upload `pip` and `setuptools` first (and always install in a virtualenv, not globally)

**Comment by amahendrakar** [comment] 2020-03-18 09:27
@alexcreature,
Any updates regarding this issue? Thanks!

**Comment by NeilClack** [comment] 2020-03-18 14:21
> Yes, the issue is that systems use old `pip` / `setuptools` by default and these don't know how to install packages with manylinux2010 tags. That's why you need to upload `pip` and `setuptools` first (and always install in a virtualenv, not globally)

Okay so here are ALL of the things I have tried in my attempts to simply install tensorflow via pip install:

pip 20.0.2
Python 3.7.6
Win10, globally
Ubuntu 18.04, globally (source built python 3.7.6 and alias setup to avoid breaking apt)
Ubuntu 16.xx, globally, same as above
Win10 pipenv environment (most recent version of pipenv)
Ubuntu 16, 18 pipenv environment (most recent version of pipenv)

I have tried and tested everything I can possibly come up with to make things different but nothing seems to install Tensorflow 2.1 for Python 3.7 for me, in any way shape or form. I have tried pip install tensorflow I have tried pip install tensorflow==2.1 and the absolute only thing I can do is install by downloading the wheel and installing that wheel directly.

Is there something we can do with pip or python source to get this back to working properly? I don't have ANY issues with any other packages I use across the board, except for Black, but even then sometimes that will install without a hitch and other times I get the same error, though it's been a long time since I tried and that is not relevant to Tensorflow...

**Comment by mihaimaruseac** [comment] 2020-03-18 17:06
I think the best way forward now would be to open an issue on PyPI https://github.com/pypa/pip

If you do, please link against this issue and/or tag me too to follow up

**Comment by amahendrakar** [comment] 2020-03-27 15:23
> @alexcreature,
> Any updates regarding this issue? Thanks!

Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-03-27 15:23 UTC
Labels: TF 2.1, stat:awaiting response, subtype:macOS, type:build/install

**Comment by dstkibbrom** [comment] 2020-07-19 12:43
upgrading my pip worked for me. 

pip install --upgrade pip
