### ISSUE TITLE
categorical feature columns usage together with DenseFeatures layers in Keras fails with 1.14

### ISSUE THREAD

**Issue by dfalbel** [tensorflow/tensorflow#30307] opened 2019-07-02 11:32 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **MacOS** and **Ubuntu**
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  1.14 and nightly. **This code works with 2.0.0b1**

**Describe the current behavior**

`feature_column.categorical_column_with_vocabulary_list` does not correctly works with TF 1.14 and nightly when using it together with `tf.keras.layers.DenseFeatures`.

We get the error: 

```Table not initialized.
FailedPreconditionError: Table not initialized.
	 [[{{node sequential/dense_features/x_embedding/hash_table_Lookup/LookupTableFindV2}}]]```
```

**Describe the expected behavior**

Expected to fit the model without errors.

**Code to reproduce the issue**

```
import tensorflow as tf
import numpy as np
tf.__version__

x = np.random.choice(3, 1000)
x = np.reshape(x, newshape=[1000,1])

y = np.random.normal(size = 1000)

fc = tf.feature_column.categorical_column_with_vocabulary_list("x",vocabulary_list=[0,1,2,3])
em = tf.feature_column.embedding_column(fc, dimension = 10)

model = tf.keras.Sequential([
  tf.keras.layers.DenseFeatures(feature_columns=[em]),
  tf.keras.layers.Dense(units = 1)
])

model.compile(loss = "mse", optimizer = "adam")

model.fit(x = {'x': x}, y = y)
```

fails with log:

```
2019-07-02 13:27:03.558149: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-02 13:27:03.575154: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8bb54f5f00 executing computations on platform Host. Devices:
2019-07-02 13:27:03.575169: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-02 13:27:03.615659: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1558] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-07-02 13:27:03.763974: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at lookup_table_op.cc:809 : Failed precondition: Table not initialized.
FailedPreconditionError: Table not initialized.
	 [[{{node sequential/dense_features/x_embedding/hash_table_Lookup/LookupTableFindV2}}]]
```

**Comment by gadagashwini** [comment] 2019-07-03 08:27
@dfalbel I could able to reproduce the issue with Tensorflow 1.14.0 on Colab. And it is working as expected with Tensorflow 2.0.0.beta1.  Thanks!

**Comment by karmel** [comment] 2019-07-08 23:01
In TF v1, you will need to initialize all tables (this is no longer required in v2).

See https://www.tensorflow.org/api_docs/python/tf/initialize_all_tables

**Comment by ymodak** [comment] 2019-07-12 22:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-07-12 22:01 UTC
Labels: comp:apis, comp:keras, stat:awaiting response, type:bug/performance
