### ISSUE TITLE
Checksum error with GCC download

### ISSUE THREAD

**Issue by henriwoodcock** [tensorflow/tensorflow#46393] opened 2021-01-13 08:53 UTC
@tensorflow/micro

**Short description**

```
tensorflow/lite/micro/tools/make/targets/apollo3evb_makefile.inc:14: *** Something went wrong with the GCC download: Bad checksum. Expected: bc8ae26d7c429f30d583a605a4bcf9bc, Got: e588d21be5a0cc9caa60938d2422b058.  Stop.
```

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina
- TensorFlow installed from (source or binary): n/a
- Tensorflow version (commit SHA if source): latest from git clone b860885da901ed641015bc75b9ac06fc4a1c5a57
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): SparkFun_edge

**Reproduction instructions**

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge hello_world_bin
```

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by ymodak** [comment] 2021-01-15 06:31
Potential duplicate of https://github.com/tensorflow/tensorflow/issues/45033

**Comment by henriwoodcock** [comment] 2021-01-15 10:20
This works fine when I use docker running ubuntu 18.04, just on macOS.

**Comment by advaitjain** [comment] 2021-01-15 18:22
This is very likely an incorrect checksum as part of https://github.com/tensorflow/tensorflow/pull/46287.

We do not have appropriate CI for MacOS and many contributors (including myself) only test on Linux.

If you could send a PR with an updated checksum that is tested on MacOS, that would be very useful.

**Closed** 2021-01-19 18:10 UTC
Labels: comp:micro, type:support
