### ISSUE TITLE
clip_by_value clips NaN to clip_value_max

### ISSUE THREAD

**Issue by garibarba** [tensorflow/tensorflow#7014] opened 2017-01-23 10:58 UTC
Running 
`sess.run(tf.clip_by_value(float('nan'), 0.0, 100.0))`
returns `100.0`

I'm not sure if this is expected behavior or convenient for clipping gradients, but I believe it should return `nan` (as `np.clip()` does) or be documented.

### Environment info
Windows 7
Only CPU
Python 3.5.2 from Anaconda
Tensorflow 0.12.0-rc1 installed from binary pip package

**Comment by drpngx** [comment] 2017-01-23 20:50
@aselle for numpy compat.

**Comment by drpngx** [comment] 2017-01-24 05:43
In general, I think it's probably a good idea to follow `np.clip()`. We might be using `isfinite()` instead of `isnan()`. If you submit a PR we could discuss the issues there.

@rmlarsen FYI

**Comment by aselle** [comment] 2017-01-24 19:16
This is generally the case... Also tf.clip_by_value should be consistent with the implementation of
tf.minimum and tf.maximum s.t.
clip_by_value(v,a,b) is equivalent to  tf.minimum(tf.maximum(a, v), b)

**Comment by aselle** [comment] 2017-01-24 19:34
I cannot reproduce this on 0.9, 0.10, 0.11, 0.12 or the last nightly build from master.  I get nan.  What version and platform are you using? The issue template we ask people to complete asks what version and platform you are using, so we can help you on these types of issues better. Please use it in the future. Thank you.

**Comment by garibarba** [comment] 2017-01-24 22:06
I have filled in the information. I will do so in the future too. Sorry.
I will confirm the precise tensorflow version and test with a newer version as soon as I am able.

**Comment by garibarba** [comment] 2017-01-26 09:24
Same results on tensorflow 0.12.1. And I also get the float instead of the `nan` if I call `tf.minimum(float('nan'), 0.0)` or `tf.maximum(float('nan'), 0.0)`

**Comment by drpngx** [comment] 2017-01-26 18:17
Just to be clear, @garibarba you're running:

```
import tensorflow as tf
print tf.Session().run(tf.minimum(float('nan'), 0.0))
```
?

**Comment by garibarba** [comment] 2017-01-26 19:00
Precisely:
`python -c "import tensorflow as tf; print(tf.Session().run(tf.minimum(float('nan'), 0.0))"`
`python -c "import tensorflow as tf; print(tf.Session().run(tf.maximum(float('nan'), 0.0))"`
`python -c "import tensorflow as tf; print(tf.Session().run(tf.clip_by_value(float('nan'), 0.0, 100.0))"`

**Comment by drpngx** [comment] 2017-01-26 19:05
OK, it gives `nan` for me on Linux and `master`. @mrry / @gunan do you happen to have a windows build available where you could repro?

**Comment by gunan** [comment] 2017-01-27 00:46
Trying now.

**Comment by gunan** [comment] 2017-01-27 00:56
Reproduced the issue on windows, both on master and 0.12.1

**Comment by drpngx** [comment] 2017-01-27 01:09
Thank you @gunan ! We should definitely add a test for that once fixed.

Assigning to @aselle . I might take a look later

**Comment by gunan** [comment] 2017-01-27 01:14
It looks like the problem is caused by maximum and minimum.
And the implementations of those seem to just use eigen, if I am not mistaken.

**Comment by drpngx** [comment] 2017-01-27 02:29
Hopefully it's not a problem with NaN on SIMD.

**Comment by rmlarsen** [comment] 2017-02-06 21:33
I "fixed" the underlying NaN problem for SIMD max/min Eigen in 

https://bitbucket.org/eigen/eigen/commits/738d7c6becf04a2a8f400d5edd2c13ea44f28428

(plus a few followup). Please notice that it is a bit subtle since max and min are defined to match the (elementwise) behavior of std::max / std::min. See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1373 for a discussion.

Unfortunately we have not been able to update TensorFlow to use a recent version of Eigen containing this fix, due to build breakage in Eigen. I'll try to give this another try.

**Comment by drpngx** [comment] 2017-02-06 22:24
Nice!

**Comment by girving** [comment] 2017-06-16 17:09
@rmlarsen I'm unable to clone the Eigen repo because bitbucket's https clone doesn't work.  Has this been fixed yet?

**Comment by girving** [comment] 2017-06-16 17:12
Fixed a while ago, apparently.

**Closed by girving** 2017-06-16 17:12 UTC
Labels: stat:awaiting tensorflower, type:bug/performance
