### ISSUE TITLE
TensorBoard command unable to handle the path properly in Windows

### ISSUE THREAD

**Issue by AndreaFar** [tensorflow/tensorflow#6355] opened 2016-12-16 07:20 UTC
If you try to save the graph in a specific path eg `C:\documents`
`writer = tf.train.SummaryWriter('C:/documents/my_graph', sess.graph)`

and try to show the graph with TensorBoard

`tensorboard --logdir="C:/documents/my_graph"`

TensorBoard will not find any graph because is unable to load the path and looks always for the graph files in the default user path` C:\Users\andrew\mygraph\` if I run console as user or `C:\Windows\System32` if I run console as administrator. This is a bug and should be fixed.

Tensorflow version 0.12.0rc1 pip installation
OS: Windows 10 x64

Related Stackoverflow question
http://stackoverflow.com/questions/41157645/tensorflow-tensorboard-on-windows-shows-a-blank-page?noredirect=1#comment69557752_41157645

**Comment by vit-stepanovs** [comment] 2016-12-16 16:00
@AndreaFar Have you tried enabling more debug output by passing --debug switch to tensorboard command? This may help in investigations :)

**Comment by SMH17** [comment] 2016-12-20 17:48
The problem has been fixed in the latest final release. Upgrade your rc (release candidate) version to final 0.12.0

**Comment by aselle** [comment] 2016-12-20 22:14
@AndreaFar  please confirm that @SMH17's suggestion to upgrade resolves your issues. Thanks!

**Comment by AndreaFar** [comment] 2017-01-09 22:02
this issue has been fixed now I have another issue

**Comment by jart** [comment] 2017-01-14 00:08
We're glad to hear the issue is resolved. As for the other issue, that appears to be resolved in https://github.com/tensorflow/tensorflow/issues/6748.

**Closed by jart** 2017-01-14 00:08 UTC
Labels: tensorboard, type:bug/performance
