### ISSUE TITLE
[TF 2.0] non-tensor argument to target of tf.function logging slows down training

### ISSUE THREAD

**Issue by 4OH4** [tensorflow/tensorflow#32157] opened 2019-09-02 14:41 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Modified the stock DCGAN TensorFlow example**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Google Colab and Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.0.0-rc0**
- Python version: **3.7**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **Colab: unknown, Windows 10: CUDA=10.0, cuDNN=7.4.2**
- GPU model and memory: **Colab: unknown, Windows 10: 1080 Ti 11 GB**

**Describe the current behavior**
Logging summary scalars (for review in TensorBoard) leads to significantly increased training times. 

**Code to reproduce the issue**
Using the DCGAN tutorial (https://www.tensorflow.org/beta/tutorials/generative/dcgan), and modifying it to include a summary_writer :

```
# Load the TensorBoard notebook extension
%load_ext tensorboard
logs_base_dir = "./logs"
os.makedirs(logs_base_dir, exist_ok=True)

summary_writer = tf.summary.create_file_writer(logs_base_dir)

%tensorboard --logdir {logs_base_dir}
```

and adding scalar logging to the training step function:

```
@tf.function
def train_step(images, step):
    noise = tf.random.normal([BATCH_SIZE, noise_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)

        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output)
        disc_real_loss, disc_fake_loss = discriminator_loss(real_output, fake_output)
        disc_loss = disc_real_loss + disc_fake_loss
    
    # new code here only:
    tf.summary.scalar('gen_loss', gen_loss, step=step)
    tf.summary.scalar('disc_loss', disc_loss, step=step) 
    tf.summary.scalar('total_loss', gen_loss+disc_loss, step=step)
    summary_writer.flush()

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))
```

The average time per epoch [running on Google Colab, and on a Windows 10 PC with 1080 Ti] is a lot longer when logging:

Original configuration:  **24.6 secs** (Colab),  **8.5 secs** (Windows)
With logging summary scalars:  **220 secs** (Colab),  **44.7 secs** (Windows)

**Describe the expected behavior**
I would have expected logging to place a minimal overhead cost on training performance. Perhaps related to the `tf.function` compilation?

**Comment by oanush** [comment] 2019-09-03 06:21
@4OH4 ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks

**Comment by nfelt** [comment] 2019-09-03 22:26
@4OH4 - thanks for raising the issue.

I'm having trouble reproducing the slowness when trying the DCGAN tutorial on Colab with TF 2.0.0-rc0, as you described.  I've made the following insertion to the body of `train_step()`:

```python
    # new code here only:
    with summary_writer.as_default():
      tf.summary.scalar('gen_loss', gen_loss, step=0)
      tf.summary.scalar('disc_loss', disc_loss, step=0) 
      tf.summary.scalar('total_loss', gen_loss+disc_loss, step=0)
    summary_writer.flush()
```

Note that this differs from your modification in that:
* I'm using `summary_writer.as_default()` to activate summary writing; without this the `tf.summary.scalar` lines should be no-ops
* I'm passing `step=0` to avoid modification to the signature of `train_step()` as in your example, which I assume involved other modifications to the callsite

With this change, running `train(train_dataset, 3)` (aka 3 epochs) takes the same amount of time as without the change for me, about 11 seconds per epoch.

If you're still seeing this issue, can you provide the precise code that you ran (ideally as a full `.ipynb`), including any changes to set the summary writer as the default and to propagate the step value, and what exactly you ran to check the average time per epoch?

**Comment by 4OH4** [comment] 2019-09-03 23:08
I think that, actually, i was mistaken and it is not `tf.summary` that is causing the slow down, but that `step` is not a tensor.

I created a variable `step=0` in `train()`, and then incremented it each image batch using `step+=1`. This caused the training slow-down, from 11 secs/epoch to ~168 secs/epoch, as printed by `train()`.

Changing this to `step=tf.Variable(0)` and `step.assign_add(1)` fixes the problem.

Similarly, removing the line `step+=1` in `train()` also fixes the problem - it seems to occur only if `step` is non-zero?

Here is a gist that demonstrates the effect:
https://gist.github.com/4OH4/036062cd76ecd0a9dc83b787ee75e2dd#file-dcgan-ipynb

Perhaps its obvious to many that all the arguments going into the `tf.function` target should be tensors - I overlooked that at the time. It is confusing though that the code still runs, just much more slowly.

**Comment by kkimdev** [comment] 2019-09-04 16:22
I'm sorry for the confusion, here is the relevant doc https://www.tensorflow.org/beta/tutorials/eager/tf_function#python_or_tensor_args

Many users are hitting this and we definitely want to address this.  I will be adding a "too-many-retrace" warning very soon, likely this week.  And we are discussing what we should we do more on the top of that.

Closing this issue as it's not a bug (although it's confusing).

**Closed by kkimdev** 2019-09-04 16:22 UTC
Labels: TF 2.0-rc0, comp:core, type:performance
