### ISSUE TITLE
Error: Data loss: file is too short to be an sstable

### ISSUE THREAD

**Issue by Lldenaurois** [tensorflow/tensorflow#6644] opened 2017-01-04 21:21 UTC
Hi there,

I'm training the Language Model code available here: https://github.com/rafaljozefowicz/lm

I am getting a "Data loss" error, see below for a traceback call. I was able to find the file where the error is raised, but I am having some trouble understanding exactly what is going wrong. It seems like this is related to a checkpoint file need to populate tensorboard, however I would greatly appreciate it if someone could point me in the right direction, so I may resolve this issue.

Currently, when I look at TensorBoard, I see a global_step of 0 for the entire training duration, and I'm worried that the model is not running. All of my GPUs are fully utilized, and I have no other issues. 

```
W tensorflow/core/framework/op_kernel.cc:975] Data loss: file is too short to be an sstable
Traceback (most recent call last):
  File "single_lm_train.py", line 38, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "single_lm_train.py", line 34, in main
    run_eval(dataset, hps, FLAGS.logdir, FLAGS.mode, FLAGS.eval_steps)
  File "/shareddata/s5kbjt/NLM_RNN/lm/run_utils.py", line 111, in run_eval
    while ckpt_loader.load_checkpoint():
  File "/shareddata/s5kbjt/NLM_RNN/lm/common.py", line 45, in load_checkpoint
    if load_from_checkpoint(self.saver, self.logdir):
  File "/shareddata/s5kbjt/NLM_RNN/lm/common.py", line 27, in load_from_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)

tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable
         [[Node: save/RestoreV2_15 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_15/tensor_names, save/RestoreV2_15/shape_and_slices)]]
Caused by op u'save/RestoreV2_15', defined at:  File "single_lm_train.py", line 38, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "single_lm_train.py", line 34, in main
    run_eval(dataset, hps, FLAGS.logdir, FLAGS.mode, FLAGS.eval_steps)
  File "/shareddata/s5kbjt/NLM_RNN/lm/run_utils.py", line 98, in run_eval
    saver = tf.train.Saver(model.avg_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): file is too short to be an sstable
         [[Node: save/RestoreV2_15 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/repl
ica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_15/tensor_names, save/RestoreV2_15/sha
pe_and_slices)]]

```

**Comment by Lldenaurois** [comment] 2017-01-04 21:50
Right before this error occurs, I get the following output. It seems like the checkpoint file is never created, and at some point a DataLossError is thrown. Any help is greatly appreciated!
```
No checkpoint file found. Waiting...
No checkpoint file found. Waiting...
No checkpoint file found. Waiting...
Waiting for a new checkpoint...
```

**Comment by michaelisard** [comment] 2017-01-06 17:57
Would you fill in the issue template with your OS/setup, etc.? Thanks.

**Comment by Lldenaurois** [comment] 2017-01-09 12:58
Hi Michael,

Yes, here is the information

Operating System: Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64)

Setup:
  tensorflow installed via "pip install tensorflow-gpu"
  CUDA 8.0 & cuDNN 3.5
  4 Tesla K80 (2 GPUs per card) @ 24GB per card

**Comment by jart** [comment] 2017-01-13 23:42
That error message appears to mean one of your checkpoint files is <48 bytes in size. Is it possible that your training script failed or files got corrupted or truncated afterwards? If you regenerate the data, does the same error still happen?

**Comment by Lldenaurois** [comment] 2017-01-14 13:34
Hi Jart,

Thanks so much for your response.

Yes, the error is persistent. It seems like the Checkpoint file is being created through a deprecated class, and I can't figure out how to fix it.

I'm now trying to simply rebuild the entire model from scratch and using the newest API documentation for version 0.12

Do you think I could contact you directly via eMail or Google Hangout with questions? Just one time, not a repitive thing. My email is Lldenaurois@gmail.com just in case.

Also, I noticed that some of the documentation, e.g. Tutorials and How-Tos still refer to the older API, some of which is deprecated. I would like to contribute by updating the documentation. How would I go about that?

**Comment by Lldenaurois** [comment] 2017-01-14 13:39
Sorry, to your questio : The training script does not fail, but the eval script does. I think the checkpoint file is truncated because its calling a deprecated API call, which leads to the truncated checkpoint file.

Like I said, I'm rebuding the entire model from scratch. Maybe once its done, we could add the source to the model zoo. I saw that lm_1b is in there, but only the eval script, not the training script.

I contacted rafal about updating his repo, but he never answered. Is this something you guys think would be interesting?

**Comment by jart** [comment] 2017-01-15 22:12
The repository you linked in the original comment appears to be doing a lot of checkpoint loading logic by hand. Please understand that TensorFlow is community supported and we also can't provide support for other people's projects.

Right now I'm trying to determine if a TensorFlow API is responsible for writing corrupt data. If that's the case, then it's a bug, and we want to fix it. Anything you can do to help us better understand what the bug is, will be helpful. Possibly by providing a minimal reproducible example.

Also does [testLegacyInitOp()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/saved_model_test.py#L456) demonstrate what you're trying to do?

**Comment by jart** [comment] 2017-01-16 00:49
Also would tf.train.NewCheckpointReader serve your needs?

**Comment by Lldenaurois** [comment] 2017-01-16 14:43
Hi Justine,

Thanks for the info. I'll try those out and get back to you with a minimum reprodubcible example (if there is a bug).

Thanks for the help!

**Comment by aselle** [comment] 2017-02-13 17:44
Closing due to lack of recent activity. Please update the issue if it persists and we will reopen.

**Closed by aselle** 2017-02-13 17:44 UTC
Labels: stat:awaiting response

**Comment by FarisHijazi** [comment] 2020-12-17 12:34
if you're getting this from a tf.data dataloader, then try deleting the cache file. This worked for me
