### ISSUE TITLE
AttributeError: 'OneDeviceStrategy' object has no attribute 'call_for_each_tower'

### ISSUE THREAD

**Issue by WeiyiLi** [tensorflow/tensorflow#24136] opened 2018-12-04 03:00 UTC
I downloaded the up-to-date source code from this page and build from source. Then I tried to train mnist using the code in https://github.com/tensorflow/models/tree/master/official/mnist
But I got the following error message:
```

I1203 18:58:06.548315 140153645283136 run_config.py:530] Initializing RunConfig with distribution strategies.
I1203 18:58:06.548501 140153645283136 estimator_training.py:166] Not using Distribute Coordinator.
I1203 18:58:06.548817 140153645283136 estimator.py:197] Using config: {'_model_dir': '/tmp/mnist_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.one_device_strategy.OneDeviceStrategy object at 0x7f77577a59e8>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f77577a5ac8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
W1203 18:58:06.572286 140153645283136 deprecation.py:317] From /home/kathy/workspace/test/models/official/mnist/dataset.py:100: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
W1203 18:58:06.609055 140153645283136 deprecation.py:317] From /home/kathy/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:175: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "mnist.py", line 236, in <module>
    absl_app.run(main)
  File "/home/kathy/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/kathy/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "mnist.py", line 230, in main
    run_mnist(flags.FLAGS)
  File "mnist.py", line 211, in run_mnist
    mnist_classifier.train(input_fn=train_input_fn, hooks=train_hooks)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/kathy/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1287, in _train_model_distributed
    grouped_estimator_spec = self._train_distribution.call_for_each_tower(
AttributeError: 'OneDeviceStrategy' object has no attribute 'call_for_each_tower'

```

But if I install from tf-nightly from binary, it can be trained. Please help out!Thanks.

**Comment by Zantares** [comment] 2018-12-11 07:41
I got the same issue when run NCF in [tensorflow-models](https://github.com/tensorflow/models/tree/master/official/recommendation), and I has already know that is caused by mismatching API between tensorflow and tensorflow-estimator.

TF deleted this API **call_for_each_tower** and used **call_for_each_replica** instead, but the release package of [tensorflow-estimator](https://pypi.org/project/tensorflow-estimator/#history) is too old(release on Sep, 12, 2018) that still used the old API. 
Tensorflow-estimator has already changed this API in their master, but they didn't release any new package and I didn't find somewhere to submit the issue, so I just answered this issue and hope someone can help to release a new estimator.

**Comment by karmel** [comment] 2019-01-10 20:48
Note that master of the Official Models should run against the nightly releases, so using tensorflow-nightly in this case (or tensorflow-estimator-nightly if you want to install estimator independently) is the expected behavior. We are currently not cutting releases for the Official Models, but may do so again in the future (CC @lintian06 ) 

I will close this as the mismatched build seems to be the problem; please reopen as necessary.

**Closed by karmel** 2019-01-10 20:48 UTC
Labels: comp:apis, stat:awaiting tensorflower, type:bug/performance

**Comment by RicciWoo** [comment] 2019-02-11 02:24
I got the same error when going through TensorFlow Keras guide to the last snippet on colab.
