### ISSUE TITLE
TensorFlow version 1.0.0-rc2 on Windows: “OpKernel ('op: ”BestSplits“ device_type: ”CPU“') for unknown op: BestSplits” with test code

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [tensorflow/tensorflow#7500] opened 2017-02-14 14:41 UTC
I installed TensorFlow version 1.0.0-rc2 on Windows 7 SP1 x64 Ultimate (Python 3.5.2 |Anaconda custom (64-bit)) using:

    pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl

When I try running the test script from https://web.archive.org/web/20170214034751/https://www.tensorflow.org/get_started/os_setup#test_the_tensorflow_installation in Eclipse 4.5 or in the console:

    import tensorflow as tf
    print('TensorFlow version: {0}'.format(tf.__version__))
    hello = tf.constant('Hello, TensorFlow!')
    sess = tf.Session()
    print(sess.run(hello))

I obtain some error message:

    TensorFlow version: 1.0.0-rc2
    'Hello, TensorFlow!'
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflob
    w\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
    E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots

Why?

I didn't have such issues with TensorFlow 0.12.1 (installed with `pip install tensorflow==0.12.1`):

    TensorFlow version: 0.12.1
    b'Hello, TensorFlow!'

Stack Exchange thread: [TensorFlow version 1.0.0-rc2 on Windows: "OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits" with test code](http://stackoverflow.com/q/42217532/395857)

@drpngx

**Comment by drpngx** [comment] 2017-02-14 23:03
@mrry might have a clue.

**Comment by mrry** [comment] 2017-02-14 23:07
As far as I can tell this is fixed at HEAD, but didn't make it into the release candidate. Fortunately you can ignore this message (unless you want to use `tf.contrib.tensor_forest.*`), but upgrading to the latest nightly should fix it.

**Comment by aselle** [comment] 2017-02-15 01:32
Could you verify that this works @Franck-Dernoncourt and close it if so?

**Comment by JerryKurata** [comment] 2017-02-15 21:02
I just ran into this error on the 1.0 release linked to on the new install guide.  Also, none of my solutions work due to similar errors.

**Comment by Carmezim** [comment] 2017-02-15 22:16
I can confirm [today's build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/) worked. I received SSE warnings though.

```
c:\tensorflow-mnist-tutorial>pip install c:\tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl
Processing c:\tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl
Requirement already satisfied: six>=1.10.0 in 
c:\python35\lib\site-packages (from tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: protobuf>=3.2.0 in 
c:\python35\lib\site-packages (from tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: wheel>=0.26 in 
c:\python35\lib\site-packages (from tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: numpy>=1.11.0 in 
c:\python35\lib\site-packages (from tensorflow-gpu==1.0.0rc2)
Collecting werkzeug>=0.11.10 (from tensorflow-gpu==1.0.0rc2)
  Downloading Werkzeug-0.11.15-py2.py3-none-any.whl (307kB)
    100% |################################| 317kB 203kB/s
Requirement already satisfied: setuptools in 
c:\python35\lib\site-packages (from protobuf>=3.2.0->tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: packaging>=16.8 in 
c:\python35\lib\site-packages (from setuptools->protobuf>=3.2.0->tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: appdirs>=1.4.0 in 
c:\python35\lib\site-packages (from setuptools->protobuf>=3.2.0->tensorflow-gpu==1.0.0rc2)
Requirement already satisfied: pyparsing in 
c:\python35\lib\site-packages (from packaging>=16.8->setuptools->protobuf>=3.2.0->tensorflow-gpu==1.0.0rc2)
Installing collected packages: werkzeug, tensorflow-gpu
Successfully installed tensorflow-gpu-1.0.0rc2 werkzeug-0.11.15

c:\tensorflow-mnist-tutorial>python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2017-02-15 23:08:35.514775: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.542579: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.545107: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.548359: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.550845: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.557935: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.568638: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:35.570199: W c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 23:08:37.210331: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce 840M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:0a:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-02-15 23:08:37.210611: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
2017-02-15 23:08:37.216269: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
2017-02-15 23:08:37.217272: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 840M, pci bus id: 0000:0a:00.0)
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
```

**Comment by sajjo79** [comment] 2017-02-15 22:43
Hi, I am also facing similar type of issue. I am running tensorflow 1.0 on windows 10. When I run the following program 
"

**import numpy as np
import tensorflow as tf

#one real values column
features = [tf.contrib.layers.real_valued_column("", dimension=1)]

estimator = tf.contrib.learn.LinearRegressor(feature_columns=features)

dataSet = tf.contrib.learn.datasets.base.Dataset(
												data=np.array([[1],[2],[3],[4]]),
												target=np.array([[0],[-1],[-2],[-3]])
												)

estimator.fit(x=dataSet.data, y=dataSet.target, steps=1000)

estimator.evaluate(x=dataSet.data, y=dataSet.target)**

I get the following error messages. 

WARNING:tensorflow:Using temporary folder as model directory: C:\Users\CRCV\AppData\Local\Temp\tmp2rbt5gl8
C:\Users\CRCV\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\deprecation.py:247: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  equality = a == b
WARNING:tensorflow:From C:\Users\CRCV\documents\visual studio 2015\Projects\HelloTF\HelloTF\tf_contrib_basic.py:14: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\CRCV\documents\visual studio 2015\Projects\HelloTF\HelloTF\tf_contrib_basic.py:14: calling BaseEstimator.fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
WARNING:tensorflow:From C:\Users\CRCV\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From C:\Users\CRCV\documents\visual studio 2015\Projects\HelloTF\HelloTF\tf_contrib_basic.py:16: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\CRCV\documents\visual studio 2015\Projects\HelloTF\HelloTF\tf_contrib_basic.py:16: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From C:\Users\CRCV\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
Press any key to continue . . .

any solution??


"

**Comment by maxamante** [comment] 2017-02-15 23:47
Seeing the same issue as @sajjo79 using tf 1.0.0 on Windows 10/Python 3.5.2/CUDA 8.0/cuDNN 5.1

Going to try installing the nightly

**Comment by JerryKurata** [comment] 2017-02-15 23:57
@sajjo79 It looks like most of the issues in your post are due to 2 things.  First is the display issues that opkernal.cc is outputting.  The second is deprecated features being used.  For the deprecated features the the warning message shows the code changes you will need to make.  And as @mrry mentions upgrading to nightly should fixed the opkernel issues until the update gets pushed to the main.

**Comment by maxamante** [comment] 2017-02-16 00:04
@JerryKurata I agree with you on the possible fixes. This is tutorial code though. It's strange it doesn't "just work"

**Comment by streamtree** [comment] 2017-02-16 00:18
Seeing the exact same issue as @Franck-Dernoncourt with the Windows installation test code using the 1.0 release on Windows 10 Anniversary Edition.

**Comment by JerryKurata** [comment] 2017-02-16 00:18
@maxamante Any time your write a tutorial it is the best your can do at the time.  But, over time things change and there is only so much time to keep up the documentation. 

FWIW, does anyone know if the TensorFlow team is looking for help with the documentation, tutorials, etc on tensorflow.org?

**Comment by Carmezim** [comment] 2017-02-16 00:32
For everybody replying saying they are having this same issue the fix was already given. You just need to download and install the most recent nightly build [0] if you want to get it going right now. Otherwise wait for the nightly build be released. 
If you are having a different problem, please open a new issue.

[0] http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/

**Comment by maxamante** [comment] 2017-02-16 00:43
@Carmezim I was commenting on @sajjo79's issue with the tutorial code not executing to completion. Sorry for the derail. Nightly build does solve the OpKernel for me

**Comment by Carmezim** [comment] 2017-02-16 00:48
@maxamante This got a little confusing here. I think this issue could be closed when @Franck-Dernoncourt gives heads up of his side and folks having other problems could open new issues.

**Comment by Franck-Dernoncourt** [comment] 2017-02-16 01:00
Installing [today's nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/) (CPU version) fixed the issue (no more  `“OpKernel ('op: ”BestSplits“ device_type: ”CPU“') for unknown op: BestSplits”` etc.).

But as @Carmezim remarked there are now some SSE warnings:

```
TensorFlow version: 1.0.0-rc2
b'Hello, TensorFlow!'
2017-02-15 19:56:22.688266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 19:56:22.688266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 19:56:22.689266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 19:56:22.689266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 19:56:22.689266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-15 19:56:22.689266: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.


```

**Comment by drpngx** [comment] 2017-02-16 04:43
@gunan fyi

**Comment by TrisDing** [comment] 2017-02-16 22:22
I see the same issue using the raw win32 interpreter. However, it's working for me in python IDLE (Shell)

**Comment by Carmezim** [comment] 2017-02-16 22:52
@TrisDing TensorFlow on Windows is only compatible with 64-bit OS and Python distribution.

**Comment by butu5** [comment] 2017-02-17 07:34
I too faced the same issue. After installing nightly build, error gone. Now getting below warnings:-

C:\WINDOWS\system32>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello Tensorflow')
>>> sess = tf.Session()
2017-02-17 13:01:59.790943: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791138: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791318: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791498: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791609: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791783: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.791905: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-17 13:01:59.792043: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(sess.run(hello))
b'Hello Tensorflow'
>>>

**Comment by jameslem** [comment] 2017-02-17 12:26
# Validate tf installation

## Windows CMD

C:\Windows\system32>python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>>
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2017-02-17 20:00:30.151037: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE instructions, but these are available on your m
achine and could speed up CPU computations.
2017-02-17 20:00:30.151421: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-02-17 20:00:30.151958: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE3 instructions, but these are available on your
machine and could speed up CPU computations.
2017-02-17 20:00:30.152531: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.1 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-02-17 20:00:30.153561: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.2 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-02-17 20:00:30.154072: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX instructions, but these are available on your m
achine and could speed up CPU computations.
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
>>>


## Python 3.5.3 Shell

>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
>>>

**Comment by Carmezim** [comment] 2017-02-17 16:40
As the issue is solved it could be closed and a new one opened to track this other problems folks are having.

**Comment by mrry** [comment] 2017-02-17 22:10
Thanks @Carmezim :), and @Franck-Dernoncourt for confirming that this is fixed in the nightlies.

I'm going to close this issue because the original problem has already been solved, and lock it for new discussion. Please open a new issue if you still have problems!

**Closed by mrry** 2017-02-17 22:10 UTC
Labels: type:bug/performance
