### ISSUE TITLE
How to get a flowchart for fireworks cnn optimization algorithm.

### ISSUE THREAD

**Issue by sree941** [tensorflow/tensorflow#37923] opened 2020-03-26 05:06 UTC
def fire_incept(x, fire=16, intercept=64):
    x = Conv2D(fire, (5,5), strides=(2,2))(x)
    x = LeakyReLU(alpha=0.15)(x)
    
    left = Conv2D(intercept, (3,3), padding='same')(x)
    left = LeakyReLU(alpha=0.15)(left)
    
    right = Conv2D(intercept, (5,5), padding='same')(x)
    right = LeakyReLU(alpha=0.15)(right)
    
    x = concatenate([left, right], axis=3)
    return x

def fire_squeeze(x, fire=16, intercept=64):
    x = Conv2D(fire, (1,1))(x)
    x = LeakyReLU(alpha=0.15)(x)
    
    left = Conv2D(intercept, (1,1))(x)
    left = LeakyReLU(alpha=0.15)(left)
    
    right = Conv2D(intercept, (3,3), padding='same')(x)
    right = LeakyReLU(alpha=0.15)(right)
    
    x = concatenate([left, right], axis=3)
    return x

image_input=Input(shape=input_shape)

x = fire_incept((image_input), fire=16, intercept=16)

x = fire_incept(x, fire=32, intercept=32)
x = fire_squeeze(x, fire=32, intercept=32)

x = fire_incept(x, fire=64, intercept=64)
x = fire_squeeze(x, fire=64, intercept=64)

x = fire_incept(x, fire=64, intercept=64)
x = fire_squeeze(x, fire=64, intercept=64)

x = Conv2D(64, (3,3))(x)
x = LeakyReLU(alpha=0.1)(x)

x = Flatten()(x)

x = Dense(512)(x)
x = LeakyReLU(alpha=0.1)(x)
x = Dropout(0.1)(x)

out = Dense(len(SPECIES), activation='softmax')(x)

model_new = Model(image_input, out)
model_new.summary()

**Comment by khimraj** [comment] 2020-03-26 05:30
@sree941, please share full code or link of google colab to reproduce issue.

**Comment by sree941** [comment] 2020-03-26 05:33
> @sree941, please share full code or link of google colab to reproduce issue.

Actually there is no issue with this code. I want a flowchart that describes this code. So I'm asking whether there is a code in python that produces the algorithm for this particular model. Or else can you just explain me this code please.

**Comment by ravikyram** [comment] 2020-03-26 05:36
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by khimraj** [comment] 2020-03-26 05:42
@sree941, You can try with `tf.keras.utils.plot_model`.

**Comment by sree941** [comment] 2020-03-26 05:47
> tf.keras.utils.plot_mode

I tried and is getting an error like this:
AttributeError: module 'tensorflow.python.keras.api._v1.keras.utils' has no attribute 'plot_model_new'

**Comment by khimraj** [comment] 2020-03-26 05:51
@sree941, you need to pass model name in `plot_model` method.
`tf.keras.utils.plot_model( model_new, to_file='model.png')`

**Comment by sree941** [comment] 2020-03-26 06:27
> `tf.keras.utils.plot_model( model_new, to_file='model.png')`

yeah it's working thank you

**Comment by ravikyram** [comment] 2020-03-27 11:26
Closing the issue since its resolved. Thanks!

**Closed by ravikyram** 2020-03-27 11:26 UTC
Labels: comp:keras, type:support
