### ISSUE TITLE
Gradient computation erroneously returns None

### ISSUE THREAD

**Issue by joshburkart** [tensorflow/tensorflow#783] opened 2016-01-15 10:05 UTC
```python
In [5]: tf.gradients(tf.constant(5), tf.Variable(0))
Out[5]: [None]
```
The derivative of 5 with respect to x should be 0.

**Comment by girving** [comment] 2016-01-20 23:18
I'm not sure this isn't the desired behavior.  Returning `None` makes it explicit that there is no graph connection between the two.

**Comment by joshburkart** [comment] 2016-01-20 23:39
If it's called "gradients" then I expect it to compute gradients... The gradient of e.g. 5 with respect to some vector v is most certainly the zero vector.

Also just from a practicality standpoint, you should be able to compute gradients and then perform mathematical operations with them without having to worry about something unexpectedly becoming a non-`Tensor` and causing an exception to be raised. In some TF code I wrote recently I had to make the following function to avoid this bug:
```python
def _compute_gradients(tensor, var_list):
  grads = tf.gradients(tensor, var_list)
  return [grad if grad is not None else tf.zeros_like(var)
          for var, grad in zip(var_list, grads)]
```

**Comment by girving** [comment] 2016-01-20 23:47
Yep, I agree that this is a bug; my comment was poorly worded.  @mrry: Do we use the `None` feature anywhere that changing this would break?  It could certainly cause some code to get slower, which is a potential concern.

**Comment by mrry** [comment] 2016-01-26 02:15
I'm pretty sure this is intended behavior. [`Optimizer.apply_gradients()`](https://github.com/tensorflow/tensorflow/blob/b159e211860e26e3dbae26989163b9da55e3f430/tensorflow/python/training/optimizer.py#L239) uses the fact that individual gradients may be `None` to remove assignment ops. While this would be an easy case for a graph rewriter, it's not something we currently do, so I'd be a little worried about regressions if various variables suddenly started being updated every time.

Since `tf.gradients()` is mostly hidden behind the optimizers, and the behavior isn't currently documented, we could consider a breaking change to the API, but I think we'd want to retain the existing functionality. Perhaps it could be controlled by an optional arg?

**Comment by joshburkart** [comment] 2016-01-26 17:16
Hmm, I get the efficiency argument. I agree that a keyword arg could be a suitable workaround. E.g.
```python
tf.gradients(tf.constant(5), tf.Variable(0), return_zeros=True)
```

**Comment by girving** [comment] 2016-01-26 17:48
It looks like there are hundreds of direct uses of `tf.gradients` within Google, so I don't think a silent performance breaking change is okay.  If we're going to change the default behavior, I think the only way would be to make the special `Zeros` class and give it suitable arithmetic overloads.  That way, anyone who doesn't realize and treats it as a normal tensor in a way that doesn't take advantage of zeros will throw an exception.

For now, how about a `return_zeros` argument that defaults to `False`?

**Comment by joshburkart** [comment] 2016-01-27 18:24
SGTM, and going for a keyword arg would allow for easy deprecation once/if the `Zeros` class gets implemented.

**Comment by girving** [comment] 2016-01-27 19:39
Writing this now.

**Comment by girving** [comment] 2016-01-27 19:56
Actually, there's a wrinkle: `None` is used to indicate a variety of different things:

1. There is no connection from input to output.
2. There is a connection, but it's through a discrete variable with meaningless gradients.
3. There is a connection, but it's through an op that doesn't have an implemented gradient.

(3) in particular would be very bad to replace with zeros.

**Comment by joshburkart** [comment] 2016-01-28 17:02
Ahh yeah I would think only (1) is a bug. Do you think it would be better to raise separate exceptions instead of returning `None` for both (2) and (3)? Allow the user to handle them separately?

One thing I could imagine is adding a `return_none` flag instead of a `return_zeros` flag, with a default value of `True`. When set to false, it raises `GradientOfDiscreteVariableError` for (2) and `NoImplementedGradientError` for (3), and returns an appropriately shaped zero Tensor for (1). When set to `True` it maintains the status quo and returns `None` in all cases. And then eventually plan to deprecate the `return_none=True` path.

What do you think? Obviously I'd be happy to help out.

**Comment by girving** [comment] 2016-01-28 17:27
That's sounds reasonable, but unfortunately it would require adjusting the gradient functions, since individual gradient functions also use `None` for both (1) and (2).

@mrry: What do the think about the `Zeros` solution?

**Comment by qingzew** [comment] 2016-05-28 07:52
I have the same problem, I do not kwon core implementation about tf and theano, but I think that the param disconnected_inputs in  theano.gradient.grad() would be good

**Comment by girving** [comment] 2016-08-09 23:39
I'm going to close this for now.  It's a marginal benefit with an unfortunately large amount of work, since introducing `Zeros` or similar will break a lot of downstream code.

**Closed by girving** 2016-08-09 23:39 UTC
Labels: enhancement

**Comment by yaroslavvb** [comment] 2016-08-10 00:34
I've been using this work-around

def replace_none_with_zero(l):
  return [0 if i==None else i for i in l]

grads = replace_none_with_zero(tf.gradients([grads[0]], [x, y]))

**Comment by TEHEK** [comment] 2018-05-14 19:07
I think I've just ran into this:

```
with tf.Graph().as_default():
  with tf.Session() as sess:
    x = tf.constant([1.0])
    x_double = 2*x
    print sess.run(tf.hessians(x_double, x))

# ValueError: None values not supported.
```

=\

**Comment by scofield7419** [comment] 2019-01-19 01:58
> Actually, there's a wrinkle: `None` is used to indicate a variety of different things:
> 
> 1. There is no connection from input to output.
> 2. There is a connection, but it's through a discrete variable with meaningless gradients.
> 3. There is a connection, but it's through an op that doesn't have an implemented gradient.
> 
> (3) in particular would be very bad to replace with zeros.

@girving, excuse me Sir,  May I ask: There are two session run in my certain project, and the first run outputs the middle-results that is inputed into the second run, and this two step-run are respectively the first part and the next part of a complete whole network. After the second run, I get the result of loss and I try to compute all the parameters in both two parts of the network above, by **_tf.gradients_**, and then **_optimizer.apply_gradients_**. But, as you declared, lt's not possible to achieve this, cause there is no direct graph connection between this two session run. And now I'm in the dilemma cause by this problem. So if there is any suggestion that you can give to me? Thank u so much. You can make some further detail about my problem if necessary.

**Comment by girving** [comment] 2019-01-22 04:45
@scofield7419 Your question is unrelated to the current issue.  Please use stackoverflow for questions like this instead.

**Comment by ShnitzelKiller** [comment] 2019-02-28 22:49
Then I take it the official documentation of tf.gradients() is erroneous?

> `unconnected_gradients` determines the value returned for each x in xs if it is unconnected in the graph to ys. By default this is None to safeguard against errors. MAthematically these gradients are zero which can be requested using the 'zero' option. tf.UnconnectedGradients provides the following options and behaviors:
> ```
> a = tf.ones([1, 2])
> b = tf.ones([3, 1])
> g1 = tf.gradients([b], [a], unnconnected_gradients='none')
> sess.run(g1)  # [None]
> 
> g2 = tf.gradients([b], [a], unconnected_gradients='zero')
> sess.run(g2)  # [array([[0., 0.]], dtype=float32)]
> ```

There doesn't seem to be such a keyword argument though.

**Comment by chutongz** [comment] 2019-06-14 08:08
I met this problem when using BN layer(tf.layers.batch_normalization)
When I calculate the gradients using opt.compute_gradients(), and it shows the None gradient comes from `((None, <tf.Variable 'VLAD/cluster_bn/gamma:0' shape=(512,) dtype=float32_ref>),)`

However, the gradients of a BN layer is supposed to be:
```
((<tf.Tensor 'gradients/VLAD/vlad_bn0/batchnorm/mul_grad/tuple/control_dependency_1:0' shape=(64,) dtype=float32>, <tf.Variable 'VLAD/vlad_bn0/gamma:0' shape=(64,) dtype=float32_ref>),)

((<tf.Tensor 'gradients/VLAD/vlad_bn0/batchnorm/sub_grad/tuple/control_dependency:0' shape=(64,) dtype=float32>, <tf.Variable 'VLAD/vlad_bn0/beta:0' shape=(64,) dtype=float32_ref>),)

```
and the traceback is as follow:

Traceback (most recent call last):

>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
>     preferred_dtype=default_dtype)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 424, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
>     values, as_ref=input_arg.is_ref).dtype.name
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 424, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 192, in <module>
>     main()
>   File "train.py", line 188, in main
>     Trainer.train()
>   File "train.py", line 136, in train
>     grads = self.average_gradients(tower_grads)
>   File "train.py", line 61, in average_gradients
>     expanded_g = tf.expand_dims(g, 0)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 136, in expand_dims
>     return gen_array_ops.expand_dims(input, axis, name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2020, in expand_dims
>     "ExpandDims", input=input, dim=axis, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
>     (input_name, err))
> ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.

**Comment by ksrath0re** [comment] 2020-02-25 08:51
> If it's called "gradients" then I expect it to compute gradients... The gradient of e.g. 5 with respect to some vector v is most certainly the zero vector.
> 
> Also just from a practicality standpoint, you should be able to compute gradients and then perform mathematical operations with them without having to worry about something unexpectedly becoming a non-`Tensor` and causing an exception to be raised. In some TF code I wrote recently I had to make the following function to avoid this bug:
> 
> ```python
> def _compute_gradients(tensor, var_list):
>   grads = tf.gradients(tensor, var_list)
>   return [grad if grad is not None else tf.zeros_like(var)
>           for var, grad in zip(var_list, grads)]
> ```

How does this affect the computation since we are just setting them to Zero?
