### ISSUE TITLE
transpose op is deleted when i use tf.lite.TFLiteConverter.from_keras_model to convert tflite model.

### ISSUE THREAD

**Issue by fhahaha** [tensorflow/tensorflow#48206] opened 2021-03-31 02:30 UTC
### 1. System information

- OS Platform and Distribution (Linux Ubuntu 16.04):
- TensorFlow installation (pip package):
- TensorFlow library (2.0.0-rc0):

### 2. Code
...
    output = tf.transpose(output, [0, 3, 1, 2])
    output_shape = output.shape
    output = Reshape([output_shape[1] * output_shape[3], output_shape[2]])(tf.transpose(output, [0, 1, 3, 2]))
    output = tf.transpose(output, [0, 2, 1]) **# if output shape is [1, 64, 1], the transpose op is deleted, when i convert keras to tflite. If the output shape is [1, 64, 2], the transpose op is reserved.**
    bn_w = state_dict[bn_name+'.weight'].numpy()
    bn_b = state_dict[bn_name+'.bias'].numpy()
    bn_mean = state_dict[bn_name+'.running_mean'].numpy()
    bn_var = state_dict[bn_name+'.running_var'].numpy()
    output = tf.add(tf.multiply(
        tf.divide(tf.subtract(output, bn_mean), tf.sqrt(bn_var+1e-05)), bn_w), bn_b)
    output = tf.transpose(output, [0, 2, 1])
    output = tf.transpose(Reshape([output_shape[1], output_shape[3],  output_shape[2]])(output), [0, 1, 3, 2])

...
converter = tf.lite.TFLiteConverter.from_keras_model(model)

### 3. Failure after conversion
The conversion is successful, but the generated model is wrong:
- transpose op is deleted in tflite model, which leads to the dimension mismatch after the transpose.

**Comment by abattery** [comment] 2021-03-31 02:35
@fhahaha could you provide minimal, reproducible steps as a format of gist to reproduce your problem at our end?

**Comment by abattery** [comment] 2021-03-31 02:51
Could you try your conversion with the recent TF version? There is possibility that the issue has been fixed in the recent TF version already.

**Comment by fhahaha** [comment] 2021-03-31 03:22
@abattery Thanks, the issue has been fixed in recent TF version 2.4.1.

**Comment by abattery** [comment] 2021-03-31 03:25
Thanks @fhahaha for the confirmation. Closed this issue since the recent TF version can resolve this issue.

**Closed** 2021-03-31 03:24 UTC
Labels: TF 2.0, TFLiteConverter, comp:lite, stat:awaiting response, type:bug
