### ISSUE TITLE
`tf.train.NanTensorHook` does not prevent `tf.train.NanLossDuringTrainingError` when using custom Estimator.

### ISSUE THREAD

**Issue by Noahyt** [tensorflow/tensorflow#27523] opened 2019-04-04 22:18 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.14.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): BINARY
- TensorFlow version (use command below): 1.13
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I am trying to use `tf.train.NanTensorHook` to prevent my training script from halting with an Error. (Specifically this is to do Hyperparameter optimization on cloudml, but I observe this bug on my local machine as well). My instantiation looks like:

```
def model_fn():
  loss = ...
  train_op = ...

  training_hooks=[]
  # Report training failed if loss becomes `Nan`.
  training_hooks.append(tf.train.NanTensorHook(loss, fail_on_nan_loss=False))

  return tf.estimator.EstimatorSpec(
    mode=mode,
    loss=loss,
    train_op=train_op,
    predictions=predict_output,
    eval_metric_ops=eval_metric_ops,
    training_hooks=training_hooks,
  )
```

**Describe the expected behavior**

I expect that this should log a warning and halt training.

**Code to reproduce the issue**
Will update when I have written a minimal example.

**Other info / logs**
Error thrown:

> ERROR:tensorflow:Model diverged with loss = NaN.
> Traceback (most recent call last):
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/noah/Documents/CHU/super_resolution/super_resolution/trainer/train_basic_model.py", line 140, in <module>
>     main()
>   File "/Users/noah/Documents/CHU/super_resolution/super_resolution/trainer/train_basic_model.py", line 132, in main
>     eval_parse_fns=parse_fns,
>   File "/Users/noah/Documents/CHU/super_resolution/super_resolution/trainer/train.py", line 166, in run_train_and_evaluate
>     log_step_count=args.log_step_count,
>   File "/Users/noah/Documents/CHU/super_resolution/super_resolution/trainer/train.py", line 81, in train_and_evaluate
>     tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
>     return executor.run()
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
>     return self.run_local()
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
>     saving_listeners=saving_listeners)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
>     saving_listeners)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
>     _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
>     run_metadata=run_metadata)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
>     run_metadata=run_metadata)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
>     raise six.reraise(*original_exc_info)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
>     return self._sess.run(*args, **kwargs)
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
>     run_metadata=run_metadata))
>   File "/Users/noah/Documents/CHU/super_resolution/conda_env/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 753, in after_run
>     raise NanLossDuringTrainingError

**Comment by achandraa** [comment] 2019-04-05 09:10
Thank you for reaching out to us. Can you please provide minimum reproducible code snippet to help us proceed further and verify what is going wrong

**Comment by achandraa** [comment] 2019-04-12 13:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-12 13:11 UTC
Labels: comp:apis, stat:awaiting response, type:support
