### ISSUE TITLE
Error arising when import tensorflow 

### ISSUE THREAD

**Issue by Luxios** [tensorflow/tensorflow#10247] opened 2017-05-27 11:18 UTC
alpine 3.5 python 2.7
Installing tensorflow using pip succesfully, but after `import` tensorflow` I got this

> ImportError: Error relocating /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal
.so: __sprintf_chk: symbol not found

**Comment by jart** [comment] 2017-05-28 00:00
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Luxios** [comment] 2017-05-28 08:35
# OS
Host: Windows 10 Professional  64bit
Docker container :  Alpine
`/ # cat /etc/issue`
Welcome to Alpine Linux 3.6
Kernel \r on an \m (\l)

`/ # uname -a`
Linux 3b851449cb60 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 Linux

# Installation
- Part of my dockerfile

`FROM frolvlad/alpine-glibc`
`RUN apk update && apk add --no-cache \
        wget ca-certificates unzip vim git \
        gcc g++ python python-dev py-numpy-dev && \
    apk add --no-cache --virtual=build-dependencies \
        libffi-dev libressl-dev zlib-dev jpeg-dev freetype-dev libpng-dev `

`RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && rm get-pip.py && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip --no-cache-dir install requests[security] ipykernel jupyter matplotlib scipy scikit-learn pandas seaborn \
    https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.0rc1-cp27-none-linux_x86_64.whl && \
    python -m ipykernel.kernelspec `

The dockerfile was built successfully. But when `import tensorflow` in a container , the following happened

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: Error relocating /usr/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: __sprintf_chk: symbol
 not found
Failed to load the native TensorFlow runtime.

**Comment by Luxios** [comment] 2017-05-30 09:27
????

**Comment by asimshankar** [comment] 2017-05-30 18:04
Closing this out as a duplicate of #10283

**Closed by asimshankar** 2017-05-30 18:04 UTC
