### ISSUE TITLE
tensorflow-1.11.0-rc1 fails to build

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#22437] opened 2018-09-21 06:36 UTC
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04.5 LTS

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: 
No

- **TensorFlow installed from (source or binary)**:
source

- **TensorFlow version (use command below)**:
1.11.0-rc1

- **Python version**:
3.5

- **Bazel version (if compiling from source)**:
0.17.1

- **GCC/Compiler version (if compiling from source)**:cc 
5.4.0

- **CUDA/cuDNN version**:
CUDA10.0 
cuDNN 7.2

- **GPU model and memory**:
GTX1070

Tried to build tensorflow-1.11.0-rc1 but it failed with

> ERROR: /home/bernard/opt/cuda_test/cuda10/tensorflow-1.11.0-rc1/tensorflow/contrib/verbs/BUILD:90:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_rendezvous_mgr' failed (Exit 1)

To be sure that it is not  because cuda is too new I tried also build tensorflow-1.10.1 and it built without problem

I tried googling and dug up this old bug https://github.com/tensorflow/tensorflow/issues/9752

**Comment by tensorflowbutler** [comment] 2018-09-21 18:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by beew** [comment] 2018-09-22 02:39
Someone just reported exactly the same error
https://github.com/tensorflow/tensorflow/issues/22455

**Comment by gunan** [comment] 2018-09-24 06:32
The other issue articulates the problem better.
TF 1.11 builds fine, the problem is verbs support.
I will close this issue and continue on the other one.

**Closed by gunan** 2018-09-24 06:32 UTC
