### ISSUE TITLE
Problem with mean OpenGL since 2.5 version

### ISSUE THREAD

**Issue by UnickSoft** [tensorflow/tensorflow#51429] opened 2021-08-11 12:35 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 11 oct 5 2020
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2 XL
- TensorFlow installed from (source or binary): Java modules. Also try to compile from sources and run using C++ API.
- TensorFlow version (use command below): 2.5
- GPU model and memory: Adreno 540 / 4GB RAM

**Describe the current behavior**

I have model, which makes something like chroma key. It returns 1 for pixel, where is person on image and 0 for other pixels. Starting with version 2.5, when I started recording to file, I have wrong output of model for some frames with OpenGL delegate. It looks like flashing. I attached video. I double check inputs, they are correct. Also for version 2.4 or 2.3 it works correct.

**Describe the expected behavior**

TFL 2.5 works the same as 2.4, without wrong output for my model.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

On my device TFL uses OpenGL. I compared code version 2.5 and 2.3 and I found, what the reason of my problem is mean (/tensorflow/lite/delegates/gpu/gl/kernels/mean.cc). For version 2.5 mean uses GenerateTiledMean function for calculation, if I forced call GenerateTrivialMean instead of GenerateTiledMean, all works correct for me.
Also I have this problem only if I record output to file. For preview (without recording to file) it works perfect. I think there is problem with synchronisation or data race. I tryed to fix shader of GenerateTiledMean, but I didn't succeed.
As solution I can sugguest can disable GenerateTiledMean for Adreno, because many of other phones with Adreno use OpenCL.

`   } else if (UseTiledImpl(ctx) && !ctx.gpu_info->IsAdreno()) {`

I forgot one thing. If I force use SSBO instead of texture it fix my problem. But with SSBOs work slower, I think it is a reason, why TFL use texture for Adreno. 

**Other info / logs**

I don't have any tfl errors in log.

https://user-images.githubusercontent.com/9623833/129029414-0ca2adf7-25b4-43c4-983d-771d1754c3c2.mov

**Comment by sylajarlind** [comment] 2021-08-17 08:48
Do you think it is the same issue here? #51276

**Comment by UnickSoft** [comment] 2021-08-17 09:51
Maybe it is the same, but I am no sure. You may try to forced call GenerateTrivialMean for mean(/tensorflow/lite/delegates/gpu/gl/kernels/mean.cc), maybe it will help you.

**Comment by sylajarlind** [comment] 2021-08-17 12:49
It is already calling on GenerateTrivialMean

**Comment by UnickSoft** [comment] 2021-08-18 12:08
> It is already calling on GenerateTrivialMean

I think, you have another problem, because force calling GenerateTrivialMean fix my issue.

**Comment by xunkai55** [comment] 2021-08-28 10:28
@srjoglekar246 Hi Sachin, since it's related with GPU, could you help take a look or triage to proper engineers? Thanks!

**Comment by srjoglekar246** [comment] 2021-08-30 17:27
@impjdi Can you take a look?

**Comment by impjdi** [comment] 2021-08-30 20:20
@UnickSoft It would be helpful if you can attach a tflite model that can reproduce this.

**Comment by UnickSoft** [comment] 2021-09-21 10:41
@impjdi Sorry I cannot provide tflite model. I tried to find open models with mean but I can't. If you provide me model with mean, I am able to test it.

**Comment by mizabrik** [comment] 2022-04-26 15:06
We faced an issue with tiled mean too; unfortunately, I can not provide a model either :(

**Comment by impjdi** [comment] 2022-04-26 15:45
@mizabrik I'm not familiar with TF, i.e. I don't know how TF's tiled mean gets mapped to TFLite.  I don't recall having tiled mean implementation separately (in the GPU code).

**Comment by mizabrik** [comment] 2022-07-19 13:24
@impjdi with a bit of a delay, but i have a clarification :) I was speaking about tiled [implementation](https://github.com/tensorflow/tensorflow/blob/v2.7.1/tensorflow/lite/delegates/gpu/gl/kernels/mean.cc#L186) for a regular mean node. My colleague did some intense debugging of one model and found that disabling this implementation fixed incorrect outputs.

**Comment by mohantym** [comment] 2022-11-22 07:52
Hi @UnickSoft !
We are checking to see whether you still need help in this issue . Have you checked above[ suggestion](https://github.com/tensorflow/tensorflow/issues/51429#issuecomment-1189714834) yet.
Thank you!

**Closed** 2022-12-06 08:16 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.5
