### ISSUE TITLE
tfl.cast cannot convert tensor to uint8 while tfv1 works without problems

### ISSUE THREAD

**Issue by Keyang** [tensorflow/tensorflow#42357] opened 2020-08-14 08:42 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Conda
- TensorFlow version (or github SHA if from source): 2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/16zUebMOvR4vvF3GxlxTWXUy8iMzsAQbO?usp=sharing
```python
# Copy and paste here the exact command
import tensorflow.keras as keras 
import tensorflow as tf
ipt=keras.Input(shape=(256,256,3),dtype="float32")
tmp=tf.cast(ipt,"uint8")
model=keras.Model(inputs=ipt,outputs=tmp)
converter=tf.lite.TFLiteConverter.from_keras_model(model)
converter.inference_output_type = tf.uint8
tflite_model=converter.convert()
```

**The output from the converter invocation**

```
# Copy and paste the output here.
ConverterError: See console for info.
2020-08-14 08:31:08.628838: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-08-14 08:31:08.628892: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-08-14 08:31:08.636532: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-14 08:31:08.641744: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200145000 Hz
2020-08-14 08:31:08.642003: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2719480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-14 08:31:08.642043: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-14 08:31:08.644263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-14 08:31:08.647089: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-08-14 08:31:08.647135: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e497356b9cd3): /proc/driver/nvidia/version does not exist
loc(callsite("model_5/tf_op_layer_Cast_5/Cast_5"("/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py":865:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py":959:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py":435:0 at callsite("<ipython-input-7-93af565c8972>":6:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2882:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2822:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2718:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py":537:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py":208:0 at "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py":399:0)))))))))): error: 'tfl.cast' op result #0 must be tensor of 32-bit float or 1-bit integer or 32-bit integer or 64-bit integer or complex type with 32-bit float elements values, but got 'tensor<1x256x256x3x!tf.uint8>'
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:865:9: error: 'tfl.cast' op result #0 must be tensor of 32-bit float or 1-bit integer or 32-bit integer or 64-bit integer or complex type with 32-bit float elements values, but got 'tensor<1x256x256x3x!tf.uint8>'
        self._initialize(args, kwargs, add_initializers_to=initializers)
        ^
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:959:5: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
    ^
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:435:5: note: called from
    concrete_func = func.get_concrete_function()
    ^
<ipython-input-7-93af565c8972>: note: called from
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882:17: note: called from
                exec(code_obj, self.user_global_ns, self.user_ns)
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822:17: note: called from
                if self.run_code(code, result):
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718:20: note: called from
                   interactivity=interactivity, compiler=compiler, result=result)
                   ^
/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py:537:9: note: called from
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
        ^
/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py:208:13: note: called from
            res = shell.run_cell(code, store_history=store_history, silent=silent)
            ^
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py:399:41: note: called from
                                        user_expressions, allow_stdin)
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
# See embedded model definition
```

**Comment by amahendrakar** [comment] 2020-08-14 15:56
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/58348a479a8f7cbbbb754db66345182d/42357-2-3.ipynb#scrollTo=bOKPIXgDEPsb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/813ac1c8dd80c245c800c0dcfdbee5d9/42357-tf-nightly.ipynb). 

Converting with TF 2.x fails, but using `tf.compat.v1.lite.TFLiteConverter` works. Please find the attached gist. Thanks!

**Comment by karimnosseir** [comment] 2020-08-27 19:32
Everything looks working as expected from the gists @amahendrakar  shared.
1) @amahendrakar The failure showing in the gists,  is because you're trying to set inference_output_type to uint8 without any quantization, we disallow setting the flag to int8/uint8 unless you have quantized options set.

2) The model generated looks correct, float input and cast then output is already uint8.

Closing, please reopen or file new one if you have any issues.

Thanks

**Closed by karimnosseir** 2020-08-27 19:32 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, type:bug
