### ISSUE TITLE
Error while converting to tflite model

### ISSUE THREAD

**Issue by AdirthaBorgohain** [tensorflow/tensorflow#44326] opened 2020-10-26 11:30 UTC
I am trying to convert a trained keras model to tflite. However, I am facing the error shown below. Is this likely because of the Albert layer in the model?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_keras_model(text_classifier_model)
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    195     try:
--> 196       model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
    197                                                  toco_flags_str, input_data_str,

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     31   """Wraps TocoConvert with lazy loader."""
---> 32   return _pywrap_toco_api.TocoConvert(
     33       model_flags_str,

Exception: fail to open input file

During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
<ipython-input-5-c548bab089a8> in <module>
----> 1 tflite_model = converter.convert()

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py in convert(self)
    785         Invalid quantization parameters.
    786     """
--> 787     saved_model_convert_result = self._convert_as_saved_model()
    788     if saved_model_convert_result:
    789       return saved_model_convert_result

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py in _convert_as_saved_model(self)
    767         self._trackable_obj = _load(self.saved_model_dir,
    768                                     self._saved_model_tags)
--> 769         return super(TFLiteKerasModelConverterV2,
    770                      self).convert(meta_graph.graph_def, input_tensors,
    771                                    output_tensors)

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/lite.py in convert(self, graph_def, input_tensors, output_tensors)
    627 
    628     # Converts model.
--> 629     result = _toco_convert_impl(
    630         input_data=graph_def,
    631         input_tensors=input_tensors,

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    567       input_tensors, output_tensors, *args, **kwargs)
    568   debug_info_str = debug_info.SerializeToString() if debug_info else None
--> 569   data = toco_convert_protos(
    570       model_flags.SerializeToString(),
    571       toco_flags.SerializeToString(),

~/anaconda3/lib/python3.8/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    200       return model_str
    201     except Exception as e:
--> 202       raise ConverterError(str(e))
    203 
    204   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: fail to open input file```

**Also, please include a link to the saved model or GraphDef**

```
# Architecture of text_classifier_model
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_title_word_ids (InputLaye [(None, 35)]         0                                            
__________________________________________________________________________________________________
input_title_mask (InputLayer)   [(None, 35)]         0                                            
__________________________________________________________________________________________________
segment_title_ids (InputLayer)  [(None, 35)]         0                                            
__________________________________________________________________________________________________
input_text_word_ids (InputLayer [(None, 250)]        0                                            
__________________________________________________________________________________________________
input_text_mask (InputLayer)    [(None, 250)]        0                                            
__________________________________________________________________________________________________
segment_text_ids (InputLayer)   [(None, 250)]        0                                            
__________________________________________________________________________________________________
albert_layer (KerasLayer)       [(None, 768), (None, 11683584    input_title_word_ids[0][0]       
                                                                 input_title_mask[0][0]           
                                                                 segment_title_ids[0][0]          
                                                                 input_text_word_ids[0][0]        
                                                                 input_text_mask[0][0]            
                                                                 segment_text_ids[0][0]           
__________________________________________________________________________________________________
title_repeat_vector (RepeatVect (None, 1, 768)       0           albert_layer[0][0]               
__________________________________________________________________________________________________
text_repeat_vector (RepeatVecto (None, 1, 768)       0           albert_layer[1][0]               
__________________________________________________________________________________________________
global_average_pooling1d (Globa (None, 768)          0           title_repeat_vector[0][0]        
__________________________________________________________________________________________________
global_average_pooling1d_1 (Glo (None, 768)          0           text_repeat_vector[0][0]         
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 1536)         0           global_average_pooling1d[0][0]   
                                                                 global_average_pooling1d_1[0][0] 
__________________________________________________________________________________________________
repeat_vector (RepeatVector)    (None, 1, 1536)      0           concatenate[0][0]                
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 150)          725850      repeat_vector[0][0]              
__________________________________________________________________________________________________
dense (Dense)                   (None, 64)           9664        bidirectional[0][0]              
__________________________________________________________________________________________________
dropout (Dropout)               (None, 64)           0           dense[0][0]                      
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1)            65          dropout[0][0]     

```
# Standalone code to reproduce issues

[Colab Notebook](https://colab.research.google.com/drive/11Jwz2YV1h1EniI4vVwaxyf3jXRNUSNys?usp=sharing)

**Comment by jvishnuvardhan** [comment] 2020-10-27 01:57
@AdirthaBorgohain Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by AdirthaBorgohain** [comment] 2020-10-27 04:54
> @AdirthaBorgohain Can you please share a standalone code to reproduce the issue? Thanks!

I have added in a colab noteboook to my initial post.

**Comment by Arman-IMRSV** [comment] 2020-11-02 16:00
Any update?

**Comment by abattery** [comment] 2020-11-08 08:27
Could you try conversion with tf-nightly version?

**Comment by jvishnuvardhan** [comment] 2020-11-13 23:08
@abattery I ran the code in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/4e14888100e5e35ede1a1b5bc37f98b0/tflite.ipynb) is the gist for your reference.
One of the main error looks like `tf.Einsum`. Please check part of the error trace below.

> 'tf.Einsum' op is neither a custom op nor a flex op


```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:2342: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1395: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '
WARNING:absl:Found untraced functions such as forward_gru_layer_call_fn, forward_gru_layer_call_and_return_conditional_losses, backward_gru_layer_call_fn, backward_gru_layer_call_and_return_conditional_losses, gru_cell_1_layer_call_fn while saving (showing 5 of 145). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmp9n8xjicj/assets
INFO:tensorflow:Assets written to: /tmp/tmp9n8xjicj/assets
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    212                                                  debug_info_str,
--> 213                                                  enable_mlir_converter)
    214       return model_str

6 frames
Exception: <unknown>:0: error: loc(callsite(callsite(callsite(callsite(callsite(callsite("embedding_projection/einsum/Einsum@__inference_albert_transformer_encoder_layer_call_and_return_conditional_losses_11038" at "albert_transformer_encoder/StatefulPartitionedCall@__inference_model_layer_call_and_return_conditional_losses_11140") at "StatefulPartitionedCall@__inference_model_layer_call_fn_11174") at "StatefulPartitionedCall@__inference_restored_function_body_13318") at "model/albert_layer/StatefulPartitionedCall@__inference__wrapped_model_14265") at "StatefulPartitionedCall@__inference_signature_wrapper_17324") at "StatefulPartitionedCall")): 'tf.Einsum' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
```

**Comment by abattery** [comment] 2020-11-13 23:11
@jvishnuvardhan this error can be resolved via enabling SELECT TF op option.

**Comment by jvishnuvardhan** [comment] 2020-11-14 01:18
Thanks @abattery. Forgot to enable it.

When I enable `tf.lite.OpsSet.SELECT_TF_OPS`, there is no error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/674a74838edfd8dfb292e30a02684803/tflite.ipynb).

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2020-11-14 01:18 UTC
Labels: TFLiteConverter, comp:lite, type:support
