### ISSUE TITLE
Saving custom graph collections in graph_def

### ISSUE THREAD

**Issue by meereeum** [tensorflow/tensorflow#1798] opened 2016-04-06 19:02 UTC
Would be useful to facilitate, e.g., restoring desired subset of nodes when re-loading model with graph_def if custom graph collections were persisted.

**Comment by yaroslavvb** [comment] 2016-04-06 19:42
You can use import_meta_graph and export_meta_graph.

**Comment by meereeum** [comment] 2016-04-07 01:50
@yaroslavvb Thanks for the tip.

Seems that```import_meta_graph``` requires instantiating ```tf.train.Saver```, which fails with ```ValueError: No variables to save``` - possibly because I am essentially freezing variables via assign ops once trained. Is there no way to divorce the Saver protocol from restoring a graph and corresponding collections ?

**Comment by yaroslavvb** [comment] 2016-04-07 01:52
oooh, that's no bueno, @sherrym may know a workaround

**Comment by sherrym** [comment] 2016-04-07 19:10
You should be to do this:

  ```Python
  with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('my-save-dir/my-model-10000.meta')
    new_saver.restore(sess, 'my-save-dir/my-model-10000')
    # tf.get_collection() returns a list. In this example we only want the
    # first one.
    train_op = tf.get_collection('train_op')[0]
    for step in xrange(1000000):
      sess.run(train_op)
```

**Comment by sherrym** [comment] 2016-04-18 18:10
@meereeum Any updates?

**Comment by meereeum** [comment] 2016-04-20 18:53
Hi @sherrym , no luck so far with ```meta_graphs```.

meta_graph is saved successfully (or, at least, no errors thrown) via:
```
tf.train.export_meta_graph(filename=outfiles['meta'], collection_list=[self.restore_key],
                           graph_def = sesh.graph_def, saver_def = tf.train.SaverDef())
```

Trying to restore via:
```
tf.train.import_meta_graph(outfiles['meta'])
```

Throws: ```IOError: Cannot parse file ./model.meta: 2:1 : Expected identifier..```

Not sure if this is the problem, but I have not found any documentation of what the ```meta_info_def``` kwarg (of ```export_meta_graph```) expects.

**Comment by sherrym** [comment] 2016-05-13 20:58
What did you set to outfiles['meta'] to? Could you pass in an absolute path to your meta file, something like this:

tf.train.import_meta_graph("/tmp/model.meta")

if your model.meta file is indeed in /tmp?

Sherry

**Comment by sherrym** [comment] 2016-05-13 21:00
The instructions and examples for using meta_graph can be found here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/meta_graph/index.md

**Comment by girving** [comment] 2016-06-07 00:32
@meereeum: Closing for now since it seems like it might have been caused by a malformed use of `import_meta_graph`.  I'm happy to reopen if it's a persistent issue.

**Closed by girving** 2016-06-07 00:32 UTC
