### ISSUE TITLE
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer`

### ISSUE THREAD

**Issue by UltraSpecialException** [tensorflow/tensorflow#29371] opened 2019-06-03 20:59 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip3 install tensorflow`
- TensorFlow version: 1.13.1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I am currently building a few custom Keras layers. However, when I try to return a tf.keras.Model with outputs that is the output of the last layer, I get the error:
`ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("layer_normalization_1/batchnorm/add_1:0", shape=(?, ?, 10), dtype=float32)`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
import tensorflow as tf
inps = tf.keras.Input(shape=(None, 256), name="inps")
mask = tf.keras.Input(shape=(1, 1, None), name="mask")
m1 = tf.random.uniform(shape=(8, 20))
m2 = tf.random.uniform(shape=(8, 20))
outputs = tf.keras.layers.Dense(units=512)(m1 + m2)
model = tf.keras.Model(inputs=[inps, mask], outputs=outputs, name="test")
```
-- These are toy commands that are similar to my actual code. I was confused as to why the 
outputted values from a Dense layer aren't considered outputs from a Tensorflow Layer.

**Comment by gadagashwini** [comment] 2019-06-04 08:11
I am able to reproduce the issue on colab with Tensorflow 1.13.1. Thanks!

**Comment by UltraSpecialException** [comment] 2019-06-04 14:15
Thanks! It's sort of a blocker for me at the moment, do you think there's anything I could try?

**Comment by omalleyt12** [comment] 2019-07-23 19:00
@UltraSpecialException The inputs to your dense layer are constant-valued. They need to come from keras.Input in order for the Model to be connected

**Comment by jvishnuvardhan** [comment] 2019-08-06 00:31
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-08-06 00:31 UTC
Labels: comp:keras, type:bug

**Comment by marvinxu-free** [comment] 2019-12-04 12:11
anyone found the answer?

**Comment by GoingMyWay** [comment] 2020-04-15 03:22
Did anyone found the answer? As far as I know, tf.keras is not compatible with tf in tf 1.x. In tf 2.x they work fine.

**Comment by robertlugg** [comment] 2021-01-15 21:58
From what I can see there is no reliable way to put constants in a TF 1.x Keras graph.  You can add them as an Input() or as a lambda function (https://stackoverflow.com/a/50716411/2184122).  The first is messy as you need to transmit your constant using some other mechanism.  The second is messy because you have python "stuff" embedded in you model, so also need to transmit that code along with your model.

TensorFlow 2.x seems to have taken care of this missing functionality.
