### ISSUE TITLE
Increasing predict time every iteration of loop

### ISSUE THREAD

**Issue by Dabuk** [tensorflow/tensorflow#35060] opened 2019-12-12 17:05 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 12.04
- TensorFlow version (use command below): conda install tensorflow-gpu=1.14.0 
- Python version: 3.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla k80

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
model predict time increases for every tensor. 

Using a resnet 32 layer model. No modifications except for input shape.

Call initializer instance with the dtype argument instead of passing it to the constructor
--- 2.172 seconds ---
1
--- 0.3469 seconds ---
1
--- 0.3441 seconds ---
1
--- 0.3465 seconds ---
1
--- 0.3543 seconds ---
1
--- 0.3583 seconds ---
1
--- 0.3638 seconds ---
1
--- 0.3676 seconds ---
1
--- 0.3727 seconds ---
1
--- 0.3779 seconds ---
1
--- 0.3838 seconds ---
1
--- 0.3918 seconds ---
0
--- 0.3958 seconds ---
0
--- 0.4069 seconds ---
0
--- 0.4084 seconds ---
0
--- 0.4144 seconds ---
0
--- 0.4143 seconds ---
0
--- 0.4173 seconds ---
0
--- 0.4180 seconds ---
0
--- 0.4244 seconds ---
0
--- 0.4355 seconds ---
0
--- 0.4313 seconds ---
0
--- 0.4429 seconds ---
0
--- 0.4446 seconds ---
0
--- 0.4435 seconds ---
0
--- 0.4547 seconds ---
0
--- 0.4513 seconds ---
0
--- 0.4641 seconds ---
0
--- 0.4697 seconds ---
0
--- 0.4717 seconds ---
0
--- 0.4737 seconds ---
0
--- 0.4794 seconds ---
0
--- 0.4816 seconds ---
0
--- 0.4845 seconds ---
0
--- 0.4906 seconds ---
0
--- 0.4923 seconds ---
0
--- 0.5027 seconds ---
0
--- 0.5028 seconds ---
0
--- 0.5088 seconds ---
0
--- 0.5185 seconds ---
0
--- 0.5173 seconds ---
0
--- 0.5223 seconds ---
0
--- 0.5292 seconds ---
0
--- 0.5280 seconds ---
0
--- 0.5391 seconds ---
0
--- 0.5429 seconds ---
0
--- 0.5413 seconds ---
0
--- 0.5503 seconds ---
0
--- 0.5559 seconds ---
1
--- 0.5666 seconds ---
1
--- 0.5622 seconds ---
1
--- 0.5678 seconds ---
0
--- 0.5780 seconds ---
0
--- 0.5866 seconds ---
1
--- 0.5863 seconds ---

**Describe the expected behavior**
constant predict times

** code **
```
class PredictPerFeat(object):
   def __init__(self, model, params):

        self.model = tf.keras.models.load_model(model, compile=False)

   def predict(feats):
        start_time = time.time()
        out = self.model.predict_on_batch(feats)
        
        print("--- %s seconds ---" % (time.time() - start_time))
        out = int(out > 0.5) # outputs label

        return out

def main(args):
      predperfeat = PredictPerFeat(args.model_path)
      feats = loadfeats(args.feat_path)   

      for i in range(len(feats)):
         # each feature of shape 1, 25, 40, 1
         # also tested for random input 
         # f = tf.convert_to_tensor(np.random.rand(1,25,40,1))
         f = feats[i]
         pred = predperfeat.predict(feats[i])
         print(prediction)
```

**Comment by amahendrakar** [comment] 2019-12-16 11:50
Could you please provide a complete standalone code. Looks like model_path and feat_path are not defined. 

Tried to reproduce this code but didn't get any output. Please find the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/a0969c270e6d2d0fe6eeccc5c0a8695f/35060.ipynb) here. Thanks!

**Comment by amahendrakar** [comment] 2019-12-23 06:40
Any updates regarding this issue? Thanks!

**Comment by Dabuk** [comment] 2019-12-23 21:57
Apologies,

Will get you a reproducible code by tomorrow / day after.
I found a temporary work around.
Will update soon.

**Comment by amahendrakar** [comment] 2019-12-31 11:23
@Dabuk,
Any updates regarding the reproducible code? Thanks!

**Comment by amahendrakar** [comment] 2020-01-08 08:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-01-08 08:46 UTC
Labels: TF 1.14, stat:awaiting response
