### ISSUE TITLE
Runtime error when using ExponentialMovingAverage with MirroredStrategy (TF 1.13.1)

### ISSUE THREAD

**Issue by apls777** [tensorflow/tensorflow#27392] opened 2019-04-01 22:37 UTC
I'm trying to use ExponentialMovingAverage with MirroredStrategy training the model on several GPUs, but getting an error:
```
RuntimeError: Tried to create variable dense/kernel/replica_1/ExponentialMovingAverage/ with mismatching name on device 1
```

This error can also be reproduced on a CPU machine by specifying the number of GPUs in the "tf.contrib.distribute.MirroredStrategy" more or equal to 2.

The model works fine if I'm training it on a single GPU (by specifying the number of GPUs to 1).

I'm using TF v1.13.1. Here is a simplified code:
```python
import tensorflow as tf


def input_fn():
    features = tf.data.Dataset.from_tensors([1., 2., 3.])
    labels = tf.data.Dataset.from_tensors(1.)
    dataset = tf.data.Dataset.zip((features, labels)).repeat(10).batch(1)
    return dataset


def model_fn(features, labels, mode, params):
    logits = tf.layers.dense(features, 1, activation=tf.nn.relu)
    logits = tf.reshape(logits, (-1,))
    loss = tf.losses.mean_squared_error(logits, labels)

    ema = tf.train.ExponentialMovingAverage(0.999)

    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
        train_op = optimizer.minimize(loss=loss, global_step=tf.train.get_global_step())

        # apply moving averages
        with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
            ema_update_op = ema.apply(tf.trainable_variables())

        with tf.control_dependencies([train_op]):
            train_op = tf.group(ema_update_op)

        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

    raise NotImplementedError


def train(model_dir):
    distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=2)

    estimator = tf.estimator.Estimator(
        model_fn=model_fn,
        config=tf.estimator.RunConfig(
            train_distribute=distribution,
            model_dir=model_dir,
            log_step_count_steps=1,
        ),
    )

    estimator.train(input_fn=input_fn)


if __name__ == '__main__':
    tf.logging.set_verbosity(tf.logging.INFO)
    train('training/test1')
```

**Comment by rootkitchao** [comment] 2019-04-12 22:29
I have a similar problem.
`RuntimeError: Tried to create variable mnasnet-a1/mnas_net_model/mnasnet/mnas_blocks_4/se/conv2d_11/kernel/replica_1/ExponentialMovingAverage/ with mismatching name on device 1`
I don't understand why replica_1 appears in the middle of the variable name.

**Comment by rootkitchao** [comment] 2019-04-13 02:00
This seems to be a problem caused by using both `tf.contrib.distribute.MirroredStrategy` and `tf.train.ExponentialMovingAverage`.When ema.apply(tf.trainable_variables()) is executed, the replica variable has been generated.Finally generated a variable name like kernel/replica_1/ExponentialMovingAverage.
Maybe this is not a bug, but it needs a way to solve this problem.Can someone help solve this problem?

**Comment by apls777** [comment] 2019-04-13 09:42
@rootkitchao For now, I solved this problem by using a deprecated functionality: [tf.contrib.estimator.replicate_model_fn](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/replicate_model_fn) with [tf.contrib.estimator.TowerOptimizer](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/TowerOptimizer). Check out [this article](https://joe-antognini.github.io/machine-learning/multi-gpu-tf) to see how to use them together.

**Comment by rootkitchao** [comment] 2019-04-13 21:27
> @rootkitchao For now, I solved this problem by using a deprecated functionality: tf.contrib.estimator.replicate_model_fn with tf.contrib.estimator.TowerOptimizer. Check out this article to see how to use them together.

Thanks for your reply.I solved this problem temporarily by modifying shared_variable_creator:
```python
  def reuse_variable(next_creator, *args, **kwargs):
    """Re-use existing variable from store with same name (in order)."""
    del next_creator, args
    name = kwargs.get("name")
    canonical_name = _canonicalize_variable_name(name)
    replica_index = canonical_name.find('replica/')
    if replica_index != -1:
      canonical_name = canonical_name[replica_index+8:]
    try:
      variable_index = variable_scope_access_index.get(canonical_name, 0)
      v = shared_variable_store[canonical_name][variable_index]
      # TODO(priyag): Make this variable re-use more robust by adding checks
      # that the requested shape and dtype match the existing variable.
      variable_scope_access_index[canonical_name] = variable_index + 1
      return v
    except (KeyError, IndexError):
      raise RuntimeError(
          "Tried to create variable {} with mismatching name on device {}".
          format(name, device_id))

  if device_id == 0:
    return create_new_variable
  else:
    return reuse_variable
```
I found that MirroredStrategy always generates some wrong variable names on GPU1.Removing 'replica/' from the variable name can temporarily solve this problem.But I think there is a conflict when MirroredStrategy and ExponentialMovingAverage are used together.Ema.apply(tf.trainable_variables()) adds variables from each GPU to the list.Need a way to just manipulate variables on the current GPU.

**Comment by rootkitchao** [comment] 2019-04-24 10:51
@guptapriya Will this issue be fixed? Thank you.

**Comment by guptapriya** [comment] 2019-04-26 08:43
@rootkitchao we will definitely look into the bug, but I don't have an ETA yet unfortunately. Thanks.

**Comment by LegendaryDan** [comment] 2019-05-07 09:47
@guptapriya hi, any updates on this issue?

**Comment by preritj** [comment] 2019-05-24 00:14
any updates?

**Comment by guptapriya** [comment] 2019-05-24 06:56
Hi, sorry we don't have any updates yet. I will open this up for contributions as well.

**Comment by DavidWiesner** [comment] 2019-06-06 13:09
I have found an ugly workaround. Just define your `ExponentialMovingAverage` **outside** of the training function and set the `num_updates` **inside** the training function. Here is an working example:

```python
def input_fn():
  features = tf.data.Dataset.from_tensors([[1.]]).repeat(100)
  labels = tf.data.Dataset.from_tensors(1.).repeat(100)
  return tf.data.Dataset.zip((features, labels)).repeat()

ema = tf.train.ExponentialMovingAverage(decay=0.9999)

def model_fn(features, labels, mode):
  regularizer = tf.contrib.layers.l2_regularizer(0.001)
  layer = tf.compat.v1.layers.Dense(1, kernel_regularizer=regularizer)
  logits = layer(features)

  loss = tf.compat.v1.losses.mean_squared_error(labels, tf.reshape(logits, []))

  global_step = tf.compat.v1.train.get_or_create_global_step()

  # NOTE Here we set the global step for the ema
  ema._num_updates = global_step

  train_op = tf.compat.v1.train.GradientDescentOptimizer(0.2).minimize(loss, global_step=global_step)

  ema_vars = tf.compat.v1.trainable_variables()

  with tf.control_dependencies([train_op]):
    train_op = ema.apply(ema_vars)

  return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)

distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=2)
config = tf.estimator.RunConfig(log_step_count_steps=10, train_distribute=distribution)
classifier = tf.estimator.Estimator(model_fn=model_fn, config=config)
classifier.train(input_fn=input_fn)

```

**Comment by leekyungmoon** [comment] 2020-03-11 14:16
Any updates?

**Comment by guptapriya** [comment] 2020-04-06 05:50
This was fixed in https://github.com/tensorflow/tensorflow/commit/3a22ef3c8a466123d60c1a5d10d62e4d2d0f92d2#diff-4617aef7d483dc28665b640fbe23c18d.

**Closed by guptapriya** 2020-04-06 05:50 UTC
Labels: comp:dist-strat, stat:contributions welcome, stat:ds-triaged, type:bug
