### ISSUE TITLE
unify keras.optimizer and tf.train.Optimizer behavior

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#28064] opened 2019-04-23 03:32 UTC
when I using tf.train.Adam to replace kearas.optimizer.Adam the fit method rasize error about global_step not exits.

**Comment by muddham** [comment] 2019-04-24 12:21
@zh794390558 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by muddham** [comment] 2019-05-03 06:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by muddham** 2019-05-03 06:31 UTC
Labels: comp:apis, stat:awaiting response, type:support
