### ISSUE TITLE
[Feature Request] retrieving exact node names from multiple outputs (`tf.nn.top_k`)

### ISSUE THREAD

**Issue by joshsuihn** [tensorflow/tensorflow#22128] opened 2018-09-07 00:18 UTC
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow version (use command below)**: '1.9.0-rc1'  I also believe it happens r1.10
- **Python version**: 2.7 
- **CUDA/cuDNN version**: 7.1
- **Bazel version**: 0.16.1
- **GPU model and memory** : TitanV 12 G
- **Exact command to reproduce**: I added python sample code 
- **Mobile device**:  n/a

### Describe the problem
When a tensor op returns multiple outputs such as  `tf.nn.top_k`, 
it would be great to retrieve exact individual input nodes of its output recursively. 

As addressed here, https://www.tensorflow.org/api_docs/python/tf/nn/top_k, 
`tf.nn.top_k` returns 
- values: The k largest elements along each last dimensional slice.
- indices: The indices of values within the last dimension of input.

With below sample code, 
'Namespace/TopKV2' returns two outputs: 'Namespace/probabilities', 'Namespace/indices'
(From the two output nodes, )
'Namespace/probabilities' takes 'Namespace/TopKV2' **values** as input, 
'Namespace/indices' takes  'Namespace/TopKV2' **indices** as input. 

However, only 'Namespace/TopKV2' can be retrieved from the two output nodes. 
I also checked graph structure on tensorboard; it seems that same tensor/node (i.e., 'Namespace/TopKV2') goes to 'Namespace/probabilities' and  'Namespace/indices', both, however, one is values and, the other indices. 

If differentiable names for multiple outputs are used, that would be great. 
Or, if there is workaround, please advise me. 
This issue also causes key error in TensorRT graphsurgeon module. 

```
def _map_nodes(nodes):
    return {node.name: node for node in nodes}

def main():
   # simple network 
    with tf.variable_scope("Namespace"):
        inputs = tf.placeholder(tf.float32, [1, 3, 16, 16], name="input")
        convolved = tf.layers.conv2d(inputs, 4, [1, 1], data_format='channels_first')
        reshaped = tf.reshape(convolved, [1, 256, 4])
        best_probabilities, best_indices = tf.nn.top_k(reshaped, k=1)
        output1 = tf.reshape(best_probabilities, [256], name='probabilities')
        output2 = tf.reshape(best_indices, [256], name='indices')

    graph = tf.get_default_graph()
    graphdef = tf.get_default_graph().as_graph_def()

    # Freeze the graph.
    output_node_names = ['Namespace/probabilities', 'Namespace/indices']
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            sess, graphdef, output_node_names
        )
        # Remove training nodes.
        infer_graph = tf.graph_util.remove_training_nodes(frozen_graph)
        graph_io.write_graph(infer_graph, "./", "test.pb", as_text=False)
        node_map = _map_nodes(infer_graph.node)
        for node in infer_graph.node:
            for input_name in node.input:
                # Recursively check against all of this node's inputs
                input_node = node_map[input_name]

if __name__ == '__main__':
    main()

```
I also attached TF board events file. 
https://drive.google.com/file/d/1HdV_eqMloqXgLenZSZHmKwME_oSnJbFb/view?usp=sharing

**Comment by tensorflowbutler** [comment] 2018-09-07 12:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow installed from
Bazel version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-09-28 22:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 22:09 UTC
Labels: stat:awaiting response
