### ISSUE TITLE
Feature request: Mask R-CNN support on TensorFlow Lite

### ISSUE THREAD

**Issue by JaviBonilla** [tensorflow/tensorflow#19293] opened 2018-05-15 14:22 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux openSUSE Leap 42.3
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
This is a feature request about supporting Mask R-CNN on TensorFlow Lite. Thanks.

### Source code / logs
Currently, the following operators are not supported by TensorFlow Lite: `ResizeNearestNeighbor`, `Stack`, and `TensorFlowShape`.

`Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: ResizeNearestNeighbor, Stack, TensorFlowShape.`

**Comment by tensorflowbutler** [comment] 2018-06-02 00:00
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-27 18:50
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-12 19:08
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anitha-v** [comment] 2018-07-26 23:02
The Stack op is now supported in nightly and we are looking into adding more op support however RNNs introduce other challenges and we are hoping to provide examples to make this easier.

**Comment by achowdhery** [comment] 2018-07-26 23:10
@anitha-v This is a CNN..It will work if we have the operations in Tensorflow Lite

**Comment by achowdhery** [comment] 2018-08-01 20:02
@JaviBonilla Stack and Shape are supported in Tensorflow Lite now. We are looking in to ResizeNearestNeighbor

**Comment by JaviBonilla** [comment] 2018-08-02 07:42
@achowdhery Great! Thanks for letting me know, I’ll stay tuned for the remaining operator

**Comment by tensorflowbutler** [comment] 2018-08-17 18:58
Nagging Assignees @rohan100jain, @achowdhery: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment] 2018-08-30 16:12
Still working on prioritizing the ResizeNearestNeighbor op, though it might be a number of weeks until it's ready.

**Comment by tensorflowbutler** [comment] 2018-09-14 12:38
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-29 18:40
Nagging Assignee @achowdhery: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-14 18:37
Nagging Assignee @achowdhery: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-29 12:40
Nagging Assignee @achowdhery: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by beniroquai** [comment] 2018-11-13 08:52
Is there any update on the ResizeNearestNeighbor op? Thanks!

**Comment by jdduke** [comment] 2018-11-13 16:47
Yes! This op was added in https://github.com/tensorflow/tensorflow/commit/86a7867840d290f6d80b20765b4635c217700bd4. It's available either by building from head or in the next TensorFlow release (though there's no ETA for the latter yet).

**Comment by tensorflowbutler** [comment] 2018-11-28 18:57
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achowdhery** [comment] 2018-12-20 22:12
@JaviBonilla Please let us know if you are successfully able to convert the model to Tensorflow Lite now.

**Comment by JaviBonilla** [comment] 2018-12-23 08:16
@achowdhery I will check in the next week and let you know how it goes :-), thanks a lot!

**Comment by JaviBonilla** [comment] 2019-01-09 10:22
I am trying to generate the **tflite** from [faster rcnn inception v2](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz)  with the following command,

`bazel run -c opt tensorflow/lite/toco:toco -- \
--input_file=frozen_inference_graph.pb \
--output_file=mask_rcnn_inception.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=image_tensor \
--output_arrays='num_detections','detection_classes','detection_scores','detection_boxes','detection_masks' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops \
--experimental_local_memory_estimate`

but I am getting this error, am I missing any previous step?

`F tensorflow/lite/toco/graph_transformations/resolve_constant_slice.cc:59] Check failed: dim_size >= 1 (0 vs. 1)`

**Comment by JaviBonilla** [comment] 2019-01-09 10:43
I think this issue is related to #24407. I will have a look at the info over there.

**Comment by noah003** [comment] 2019-01-29 06:33
> I am trying to generate the **tflite** file from [mask rcnn inception v2](http://download.tensorflow.org/models/object_detection/mask_rcnn_inception_v2_coco_2018_01_28.tar.gz) with the following command,
> 
> ```
> bazel run -c opt tensorflow/lite/toco:toco -- \ 
> --input_file=frozen_inference_graph.pb \  
> --output_file=mask_rcnn_inception.tflite \
> --input_shapes=1,300,300,3 \
> --input_arrays=image_tensor \ 
> --output_arrays='num_detections','detection_classes','detection_scores','detection_boxes','detection_masks' \
> --inference_type=QUANTIZED_UINT8 \
> --mean_values=128 \
> --std_values=128 \
> --change_concat_input_ranges=false \
> --allow_custom_ops \
> --experimental_local_memory_estimate
> ```
> but I am getting this error, am I missing any previous step?
> 
> ```
> .......
> I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: CropAndResize
> I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 7262 operators, 13617 arrays (0 quantized)
> I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 7208 operators, 13526 arrays (0 quantized)
> I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 7208 operators, 13526 arrays (0 quantized)
> F tensorflow/lite/toco/graph_transformations/resolve_constant_slice.cc:59] Check failed: dim_size >= 1 (0 vs. 1)
> ```

@JaviBonilla hi, have you solved this problem?

**Comment by JaviBonilla** [comment] 2019-01-29 09:13
Hi @noah003,

Not yet, I didn't have much time to investigate it though, I'll let you know if I find something.

**Comment by achowdhery** [comment] 2019-01-29 13:43
The generic commands will not work. You will need to inspect the graph to find the correct input/output nodes.
For segmentation, you may be able to leverage the GPU version of the model released here:
https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7

**Comment by noah003** [comment] 2019-01-30 05:40
> Hi @noah003,
> 
> Not yet, I didn't have much time to investigate it though, I'll let you know if I find something.

@JaviBonilla Thanks!

**Comment by noah003** [comment] 2019-01-31 09:09
@achowdhery I'm use the output_node_names form research/object_detection/exporter.py, but still cannot work...

**Comment by fzyzcjy** [comment] 2019-03-06 03:20
Hi it seems that `ResizeNearestNeighbor` still not work? thanks!

**Comment by jdduke** [comment] 2019-03-06 15:32
> Hi it seems that ResizeNearestNeighbor still not work? thanks!

What version of TensorFlow(Lite) are you using? You'll need to be on the latest nightly to use this TensorFlow Lite op.

**Comment by fzyzcjy** [comment] 2019-03-06 22:44
> > Hi it seems that ResizeNearestNeighbor still not work? thanks!
> 
> What version of TensorFlow(Lite) are you using? You'll need to be on the latest nightly to use this TensorFlow Lite op.

I am on 1.12.0. So shall I use 1.13.0, 1.14.0 or 2.0? Thanks!

**Comment by jdduke** [comment] 2019-03-07 02:56
I would give 1.14.0 a try and let me know how it goes, thanks.

**Comment by fzyzcjy** [comment] 2019-03-07 03:36
> I would give 1.14.0 a try and let me know how it goes, thanks.

OK I will try that, thanks! (btw, yesterday I use another workaround, change nearest neighbor to bilinear upsampling and it works)

**Comment by mAximlIano** [comment] 2019-03-29 01:14
does anyone already know how to make it work?

**Comment by JaviBonilla** [comment] 2019-04-05 14:08
Hi @jdduke 

It is not working for me with `tf-nightly 1.14.1.dev20190405`.

`tflite_convert \
  --graph_def_file=./mask_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb \
  --output_file=./mask_rcnn_inception.tflite \
  --input_arrays=image_tensor \
  --input_shapes=1,224,224,3 \
  --output_arrays=detection_masks,detection_classes,detection_boxes,detection_scores,num_detections \
  --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS`

Error message:

`
...........
2019-04-05 16:05:57.074330: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-04-05 16:05:58.130320: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 6566 operators, 12219 arrays (0 quantized)
2019-04-05 16:05:59.072672: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 6529 operators, 12161 arrays (0 quantized)
2019-04-05 16:06:00.249379: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 6529 operators, 12161 arrays (0 quantized)
2019-04-05 16:06:01.669340: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 6100 operators, 11326 arrays (0 quantized)
2019-04-05 16:06:03.167713: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 6099 operators, 11325 arrays (0 quantized)
2019-04-05 16:06:04.447879: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 6098 operators, 11323 arrays (0 quantized)
2019-04-05 16:06:05.733437: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 6098 operators, 11323 arrays (0 quantized)
2019-04-05 16:06:06.712519: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 6098 operators, 11323 arrays (0 quantized)
2019-04-05 16:06:07.448395: F tensorflow/lite/toco/tooling_util.cc:641] Check failed: dim >= 1 (0 vs. 1)
Fatal Python error: Aborted`

**Comment by jdduke** [comment] 2019-04-05 17:13
See https://www.tensorflow.org/lite/models/segmentation/overview for a more detailed overview of using the DeepLab segmentation, for which we have a .tflite model available. We'll take a look at the MaskRCNN conversion failure.

**Comment by JaviBonilla** [comment] 2019-04-05 17:28
Oh, that’s great! Thanks for the info @jdduke, I am going to check it 😊

**Comment by zhouxcal** [comment] 2019-04-15 08:26
@JaviBonilla @jdduke 
Hi Guys, just checking back any updates on this thread?
Million thanks!

**Comment by jdduke** [comment] 2019-04-15 16:35
No updates, we're still investigating.

**Comment by juanilarregui** [comment] 2019-05-21 14:16
Hi @JaviBonilla @jdduke , any updates? Thanks!

**Comment by JaviBonilla** [comment] 2019-06-14 09:47
Hi @jdduke,

I've tested with `tf-nightly 1.14.1.dev20190612`

```
tflite_convert \
  --graph_def_file=./mask_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb \
  --output_file=./mask_rcnn_inception.tflite \
  --input_arrays=image_tensor \
  --input_shapes=1,224,224,3 \
  --output_arrays=detection_masks,detection_classes,detection_boxes,detection_scores,num_detections \
  --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS
```

and I get a different error.

```
..........
2019-06-14 11:43:28.172266: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: NonMaxSuppressionV2
2019-06-14 11:43:28.172790: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-06-14 11:43:28.173179: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-06-14 11:43:28.173452: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-06-14 11:43:28.173469: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-06-14 11:43:28.173483: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-06-14 11:43:29.230199: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 6800 operators, 13059 arrays (0 quantized)
2019-06-14 11:43:30.278421: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 6750 operators, 12970 arrays (0 quantized)
2019-06-14 11:43:32.153509: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 6750 operators, 12970 arrays (0 quantized)
2019-06-14 11:43:32.539125: F tensorflow/lite/toco/graph_transformations/resolve_tensorflow_switch.cc:98] Check failed: other_op->type == OperatorType::kMerge Found Sub as non-selected output from Switch, but only Merge supported.
Fatal Python error: Aborted
```
I am reporting in case this helps.

**Comment by mali30** [comment] 2019-06-14 20:01
Any updates yet? Currently working on a project and I need to convert or find a way to run on my TPU.

**Comment by NicholaiStaalung** [comment] 2019-06-26 17:27
@mali30 did u solve it. I tried freezing the graph and converting to .pb to convert into .tflite. Didnt work. Im also trying to deploy on edge tpu.

**Comment by mali30** [comment] 2019-06-26 19:40
no I could not get it to work. I am sorry my friend @NicholaiStaalung

**Comment by NicholaiStaalung** [comment] 2019-06-26 20:02
@mali30 ok, thx for letting me know! Good luck

**Comment by JaviBonilla** [comment] 2019-08-29 10:16
@mali30 sorry, somehow I missed your comment. I didn’t have luck yet, I will inform here if I make any progress.

**Comment by elazdins** [comment] 2019-11-09 08:59
Hi all,

Just wanted to check if any progress has been made here since August? Just tried locally converting a Mask RCNN network to TFLite format and unfortunately, no luck.

Thank you,

Edgars

**Comment by srjoglekar246** [comment] 2019-11-21 17:15
While it is possible to convert a MaskRCNN model to TFLite using our new converter, there are some major drawbacks:
1. It requires using the [Select TF ops in TFLite](https://www.tensorflow.org/lite/guide/ops_select) feature, as not all ops in MaskRCNN are supported on TFLite (Size, CropandResize, LinSpace). This adds binary size & latency.
2. The latency is *very* high (read: >8s), mainly because MaskRCNN uses heavy convolutions and the pre-trained models available on our model zoo have large inputs (1365*800). Since the graph has dynamic tensors, acceleration on NNAPI/GPU isn't currently supported. If I modify the inference parameters in `pipeline.config` to make inference faster, it degrades the high accuracies of MaskRCNN.

So to keep things feasible, I would like to understand the requirements here - is it bounding boxes (in that case, our SSD/SSDLite models are much better) or is it segmentation (we have some decent models for that). Otherwise, we could also try to convert research-y (not supported by the object detection team) models like [these](https://github.com/gustavz/Mobile_Mask_RCNN), but the mAP/latency tradeoff doesn't seem that good, considering we might get comparable accuracy with the SSD floating point models.

**Comment by JaviBonilla** [comment] 2019-11-22 00:38
Hi @srjoglekar246,

Thanks for the effort and the information. It is great that it is already working. For our use case, a latency of seconds is probably enough.

We are doing research in solar tracking for concentrating solar power, so basically we have a Raspberry Pi and a camera on each mirror (called heliostat) to automatically track the Sun and detect a receiver (at the top of a tower) to reflect and concentrate the solar irradiance onto the receiver, where high temperature is reached to produce high-pressure steam, move a turbine and produce electricity.

We have a mobile app to do manual tests in the solar field, a 3D-printed mockup for preliminary tests and a prototype for testing in the real plant. Some pictures are in these articles.

https://aip.scitation.org/doi/pdf/10.1063/1.5117524?class=pdf (Figure 6, mobile app example, Figure 5 real plant example).

https://arxiv.org/pdf/1809.07048.pdf (Figure 6, prototype at the real plant).

https://lanochedelosinvestigadores.fundaciondescubre.es/actividades/heliostato-inteligente/ (Pictures of the 3D-printed mockup, we are using here the Coral USB accelerator to have a really fast response).

We are already testing with retrained SSD models, but we would also like to test if Mask R-CNN can better frame the objects and achieve a higher accuracy. A latency of seconds is probably ok because the heliostats commonly move in minutes to cope with the apparent Sun trajectory in the sky.

Do you think it is a good idea to test Mask R-CNN? Are there other models that would be better for this use case? Thanks!

**Comment by srjoglekar246** [comment] 2019-11-22 17:23
@JaviBonilla If better bounding-box based tracking is your goal, you could try `ssd_resnet_50_fpn_coco` from our [detection page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). It gives a COCO mAP value of 35 at a relatively lower latency (while still being pretty good with the TFLite infra) - the latency is ~14s on a Pixel 2, to give some context.

To squeeze the maximum accuracy from the model, use 'regular' NMS (which does one round of NMS per class instead of combining all classes into one NMS round) by using `--use_regular_nms=true` with the [`export_tflite_ssd_graph`](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) script. This should yield a good TF graphdef suitable for TFLite.

Then proceed to convert as per the instructions for floating-point models [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md).
*If* latency is too high, you could go without regular NMS :-).

Let me know how it goes!

**Comment by JaviBonilla** [comment] 2019-11-23 11:37
@srjoglekar246 thanks a lot for the info! We will do some experiments in our solar field with the model you mentioned and Mask RCNN to compare and evaluate accuracy and latency.

I keep you inform about the results :-).

**Comment by basedrhys** [comment] 2020-02-23 21:18
@srjoglekar246 another thanks for the info! I'm also trying to squeeze as much performance out of a model that can be compiled to tflite, which FasterRCNN and the like are not supported for. Your tips should be pretty useful for us so cheers!

**Comment by Yu-Hang** [comment] 2021-03-04 16:24
@srjoglekar246 Is there any updates on this issue? I'm also exploring the possibility of using MaskRCNN on Android with TFLite. I checked [Running TF2 Detection API Models on mobile](models/research/object_detection/g3doc/running_on_mobile_tf2.md) and [Running on mobile with TensorFlow Lite](models/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md). Both docs still says TF Lite only support SSD models.

**Comment by srjoglekar246** [comment] 2021-03-04 17:13
@Yu-Hang Are you interested in the masks output from MaskRCNN? If its bounding boxes, is it on your own dataset?

**Comment by Yu-Hang** [comment] 2021-03-04 20:20
@srjoglekar246 Yes, I'm interested in the object masks. Right now I just want to convert a pre-trained model, and run inference on Android and see the performance. We have a trained MaskRCNN model with our own dataset. The goal is to run inference with this model on Android.

**Comment by Yu-Hang** [comment] 2021-03-04 21:00
@srjoglekar246 Our app does not process images in real-time. The accuracy of MaskRCNN is appealing to us even though it is computationally expensive compared to SSD.

**Comment by srjoglekar246** [comment] 2021-03-04 21:13
Did you train the MaskRCNN from the [detection zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)? Or did you use some other code?
In any case, you can probably try converting the model with [Select TF ops](https://www.tensorflow.org/lite/guide/ops_select) to check whether it converts, and report back errors?

**Comment by Yu-Hang** [comment] 2021-03-04 21:42
@srjoglekar246 No, we trained using the [matterport](https://github.com/matterport/Mask_RCNN) code base. Does this make a difference since that codebase is using TF1? Do you suggest we retrain using the one from the TF2 model zoo?

Okay, I will try converting the MaskRCNN model from TF2 model zoo using Select TF ops.

**Comment by srjoglekar246** [comment] 2021-03-04 22:00
TF1 support can be messy, if it contains control flow etc (MaskRCNN most probably does, but you can check)

Trying the one from the detection zoo makes more sense, we can debug the errors if they arise :-)

**Comment by Yu-Hang** [comment] 2021-03-05 22:30
@srjoglekar246 I tried to convert the model, but failed at generating the intermediate SavedModel.

code:
`tensorflow@3e9a683ad236:~/models/research$ python object_detection/export_tflite_graph_tf2.py --pipeline_config_path ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/pipeline.config --trained_checkpoint_dir ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/checkpoint --output_directory ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/output`

Error message:
`Traceback (most recent call last):
  File "object_detection/export_tflite_graph_tf2.py", line 161, in <module>
    app.run(main)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_graph_tf2.py", line 149, in main
    text_format.Parse(f.read(), pipeline_config)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 699, in Parse
    allow_unknown_field=allow_unknown_field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 771, in ParseLines
    return parser.ParseLines(lines, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 824, in ParseLines
    self._ParseOrMerge(lines, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 852, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 949, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 153:40 : Message type "object_detection.protos.TFRecordInputReader" has no field named "s".`

**Comment by srjoglekar246** [comment] 2021-03-05 22:39
Oh yeah.. the TFLite tools don't work on MaskRCNN, you need to use [export_inference_graph](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py) instead.

**Comment by Yu-Hang** [comment] 2021-03-05 23:49
@srjoglekar246 I changed command to:
`python object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/pipeline.config --trained_checkpoint_prefix ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/checkpoint --output_directory ~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/output/`

Seems like the same error:
`Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 206, in <module>
    tf.app.run()
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 170, in main
    text_format.Merge(f.read(), pipeline_config)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 737, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 805, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 830, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 852, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 949, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 153:40 : Message type "object_detection.protos.TFRecordInputReader" has no field named "s".`

Not sure if I have setup checkpoint path correctly. The example for export_inference_graph.py has the following for checkpoint path:
"--trained_checkpoint_prefix path/to/model.ckpt ". However, the checkpoint files for TF 2 models look a bit different. Please explain on how to set checkpoint path here.

<img width="780" alt="Screen Shot 2021-03-05 at 6 45 45 PM" src="https://user-images.githubusercontent.com/5137261/110186451-4db9c300-7de3-11eb-8416-4e46984b8bd7.png">

**Comment by srjoglekar246** [comment] 2021-03-05 23:58
It should be `~/data/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/checkpoint/ckpt`, I believe.

**Comment by Yu-Hang** [comment] 2021-03-06 00:37
@srjoglekar246 hmmm...looks like checkpoint path is not the cause of the error. I still have the same error: 

`google.protobuf.text_format.ParseError: 153:40 : Message type "object_detection.protos.TFRecordInputReader" has no field named "s".`

**Comment by Yu-Hang** [comment] 2021-03-06 22:19
@JaviBonilla @noah003 @mali30 Hi fellas, did any of you had any luck getting this to work?

**Comment by Yu-Hang** [comment] 2021-03-08 17:46
@srjoglekar246 @tombstone I found out from this [issue](https://github.com/tensorflow/models/issues/9546) that the above error is because 

> In the pipeline.config file of the Mask R-CNN Inception ResNet V2 1024x1024 there is an extra 's' placed

**Comment by Yu-Hang** [comment] 2021-03-23 20:24
@srjoglekar246 Can you convert models that are not from the the model hub? I tried convert my own MaskRCNN model, but the output tensors of the model seems to be wrong. It would be nice if you can take a look my issuehttps://github.com/tensorflow/tensorflow/issues/48025#issue-839067869

**Comment by mohantym** [comment] 2022-05-24 11:45
Hi @JaviBonilla ! Have you checked this[ thread ](https://colab.sandbox.google.com/gist/mohantym/a473483a7673f0db9eef66936f5e8a34/mask-rcnn-tflite-with-test.ipynb)on M-RCNN to TFlite yet? Thank you!

**Comment by JaviBonilla** [comment] 2022-05-24 18:57
@mohantym Thanks for the link! I think this issue can be closed.

**Comment by mohantym** [comment] 2022-05-25 04:02
Ok @JaviBonilla ! Thanks for confirmation. Moving this issue to closed status then. Thank you!

**Closed by mohantym** 2022-05-25 04:02 UTC
Labels: stat:awaiting response, type:feature, comp:lite
