### ISSUE TITLE
build android demo error

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorflow/tensorflow#16762] opened 2018-02-05 03:07 UTC
ERROR: missing input file '@local_jdk//:jre/lib/resources.jar'
ERROR: /home/wangmeng/.cache/bazel/_bazel_wangmeng/b0a6578298b02ab8f9d039326e51a46f/external/bazel_tools/tools/android/BUILD:104:1: @bazel_tools//tools/android:gen_java_lang_extras_jar: missing input file '@local_jdk//:jre/lib/resources.jar'
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/wangmeng/.cache/bazel/_bazel_wangmeng/b0a6578298b02ab8f9d039326e51a46f/external/bazel_tools/tools/android/BUILD:104:1 1 input file(s) do not exist
INFO: Elapsed time: 22.408s, Critical Path: 0.03s
FAILED: Build did NOT complete successfully

**Comment by asimshankar** [comment] 2018-02-05 20:09
@wm901115nwpu : Could you please provide all information asked for in the issue template?
From the little snippet provided, it seems the issue is that bazel is unable to find some files it expects from the JDK, so perhaps your JDK installation is broken?

Full instructions to reproduce will be helpful.

**Comment by wm901115nwpu** [comment] 2018-02-06 06:17
I run bazel build -c opt //tensorflow/examples/android:tensorflow_demo
java version:java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
bazel version: bazel release 0.10.0

**Comment by asimshankar** [comment] 2018-02-16 19:23
Closing this as this appears to be a bazel issue.

See https://github.com/tensorflow/tensorflow/issues/16723#issuecomment-363985153
and follow progress on https://github.com/bazelbuild/bazel/issues/3988

Thanks!

**Closed by asimshankar** 2018-02-16 19:23 UTC
Labels: type:support
