### ISSUE TITLE
Issue with training of object detection api (ssd_mobilenet_v2_coco.config)

### ISSUE THREAD

**Issue by Invisible1** [tensorflow/tensorflow#24895] opened 2019-01-14 10:32 UTC
Command Used:
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_coco.config

Please guide me if i am doing something wrong.

Error Trace:
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 91, in main
    FLAGS.pipeline_config_path)
  File "/home/tayyab/Desktop/models/object_detection/utils/config_util.py", line 43, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tayyab/Desktop/tensor_android/local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 86:7 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "use_depthwise".

**Comment by jvishnuvardhan** [comment] 2019-01-15 17:24
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you provide a small code to reproduce the error. Thanks.

**Comment by jvishnuvardhan** [comment] 2019-01-29 00:34
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-01-29 00:34 UTC
Labels: comp:apis, stat:awaiting response, type:build/install
