### ISSUE TITLE
Error in cifar10_eval.py

### ISSUE THREAD

**Issue by manucarbonell** [tensorflow/tensorflow#803] opened 2016-01-18 14:10 UTC
Hi,
i'm trying to run the cifar10 network and getting problems when evaluating the trained variables. I've runned the cifar_10 train with a maximum steps of 100 and then it should theoretically be able to be evaluated, but i get this error:
.../tensorflow/models/image/cifar10/cifar10_eval.py", line 138, in evaluate
    variables_to_restore = variable_averages.variables_to_restore()
AttributeError: 'ExponentialMovingAverage' object has no attribute 'variables_to_restore'
Can someone help me?
Thanks

**Comment by vincentvanhoucke** [comment] 2016-01-18 16:18
Dupe of https://github.com/tensorflow/tensorflow/issues/802

**Closed by vincentvanhoucke** 2016-01-18 16:18 UTC
