### ISSUE TITLE
tensorflow master window build fail

### ISSUE THREAD

**Issue by yinxungong** [tensorflow/tensorflow#35655] opened 2020-01-08 02:04 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:master
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):1.1.0
- GCC/Compiler version (if compiling from source):vs 2015
- CUDA/cuDNN version:no cuda 
- GPU model and memory:no

**Describe the problem**

use below compile command:
python ./configure.py
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

build fail

**Any other info / logs**

master window compile fail，ERROR: E:/work/work/gitlab/github/tensorflow/tensorflow/core/framework/BUILD:450:1: C++ compilation of rule '//tensorflow/core/framework:allocator_registry_impl' failed (Exit 2)
c:\users\yinxungong\_bazel_yinxungong\4pfkvgbi\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(950): error C2061: 语法错误: 标识符“Kind”
c:\users\yinxungong\_bazel_yinxungong\4pfkvgbi\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1056): note: 参见对正在编译的类 模板 实例化“Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>”的引用
c:\users\yinxungong\_bazel_yinxungong\4pfkvgbi\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(959): error C2061: 语法错误: 标识符“Kind”

**Comment by mihaimaruseac** [comment] 2020-01-08 18:29
I think you need MSVC2019. Can you try from a fresh clone of the repo? And if the issue still reproduces please ensure the following:

* the error logs use ` ``` ` before and after so that they are readable
* the error logs use English throughout the names
* the commit hash you cloned at is also included in the report

**Comment by ravikyram** [comment] 2020-01-17 09:48
@yinxungong 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-01-24 13:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-01-24 13:11 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install
