### ISSUE TITLE
Bad example in Sparse_Categorical_CrossEntropy

### ISSUE THREAD

**Issue by wzzhu** [tensorflow/tensorflow#34927] opened 2019-12-07 13:36 UTC
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/losses.py#L493

## Description of issue (what needs changing):

The example will cause errors:

cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce(
  [0, 1, 2],
  [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
print('Loss: ', loss.numpy())  # Loss: 0.3239

Need to change to

cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce(
  [0, 1, 2],
  tf.constant([[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]]))
print('Loss: ', loss.numpy())  # Loss: 0.3239

In addition [.5, .89, .6] should be [0.05, 0.89, 0.06] to be consistent with similar example (
https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy?hl=en). Thus Loss should be updated to 0.0945

**Comment by yongtang** [comment] 2019-12-08 17:02
@wzzhu I am not able to observe the error with the latest tf-nightly. Can you show the version of the tf you are using?

**Comment by wzzhu** [comment] 2019-12-09 01:14
!pip install tf-nightly-2.0-preview

import tensorflow as tf
cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce([0, 1, 2], [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
print('Loss: ', loss.numpy())  # Loss: 0.3239

I first found the problem in Tensorflow 2.0 stable version. When I tried running with nightly, it still had errors:

!pip install tf-nightly-2.0-preview

import tensorflow as tf
cce = tf.keras.losses.SparseCategoricalCrossentropy()
loss = cce([0, 1, 2], [[.9, .05, .05], [.5, .89, .6], [.05, .01, .94]])
print('Loss: ', loss.numpy())  # Loss: 0.3239

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in sparse_categorical_crossentropy(target, output, from_logits, axis)
   4523   if not from_logits:
   4524     if (isinstance(output, (ops.EagerTensor, variables_module.Variable)) or
-> 4525         output.op.type != 'Softmax'):
   4526       epsilon_ = _constant_to_tensor(epsilon(), output.dtype.base_dtype)
   4527       output = clip_ops.clip_by_value(output, epsilon_, 1 - epsilon_)

AttributeError: 'list' object has no attribute 'op'

**Comment by yongtang** [comment] 2019-12-09 01:58
@wzzhu tf-nightly-2.0-preview has not been updated even before 2.0 released as it has been switched to tf-nightly. The last version of tf-nightly-2.0-preview was released in 10/02:
https://pypi.org/project/tf-nightly-2.0-preview/#history

Please use tf-nightly instead.

**Comment by wzzhu** [comment] 2019-12-09 02:27
Right, it was TensorFlow Ver:  2.0.0-dev20191002.
I tried tf-nightly and it works. Thanks.
But the numbers still need updating to as [.5, 0.89, .6] is logits instead of a prob distribution as in categorical crossentropy example which is [.05, .89, .06]

**Comment by amahendrakar** [comment] 2019-12-09 11:04
Could reproduce the issue with TF version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/amahendrakar/6019a161a256e9a461093b9ea53279fd/34927.ipynb). Thanks!

**Comment by yongtang** [comment] 2019-12-09 16:27
@wzzhu Looks like the docstring has been fixed in  commit c7061962262c8cacc4017b352f32d2134216ca4a

**Comment by ymodak** [comment] 2019-12-10 00:11
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2019-12-10 00:11 UTC
Labels: TF 2.0, comp:keras, type:docs
