### ISSUE TITLE
Why model.Summary() shows all layers in sub model.

### ISSUE THREAD

**Issue by HLSS-Hen** [tensorflow/tensorflow#34634] opened 2019-11-27 05:40 UTC
In old version(I forget which one). Sub model just shows model's name but not all layers.
But now,it shows all layers.

My versoin: TF2.0(GPU)

demo code:
```
class Swish(keras.layers.Layer):
    def __init__(self):
        super(Swish, self).__init__()
        self.weight = self.add_weight(initializer='uniform',trainable=True)

    def __call__(self, inputs):
        return inputs+tf.sigmoid(self.weight*inputs)
```

**Comment by HLSS-Hen** [comment] 2019-11-27 07:19
the full code :[https://github.com/tensorflow/tensorflow/issues/34637](url)

**Comment by gadagashwini** [comment] 2019-11-28 06:07
@HLSS-Hen, Tried replicating the issue but got error at `from Models import MCN`. Looks like file or class method is missing. Please provide us more information to reproduce the issue. Thanks!

**Comment by HLSS-Hen** [comment] 2019-11-28 06:10
> @ HLSS-Hen，尝试复制该问题，但在遇到错误`from Models import MCN`。看起来缺少文件或类方法。请提供更多信息以重现该问题。谢谢！
No, there is. 
MCN.py is the file you miss.

**Comment by gadagashwini** [comment] 2019-11-28 09:09
@HLSS-Hen, MCN.py file doesn't have Models class method.

**Comment by HLSS-Hen** [comment] 2019-11-28 09:57
@gadagashwini Models is just a file.

**Comment by gadagashwini** [comment] 2019-12-05 06:07
@HLSS-Hen, Just to verify, MCN.py and Models are they same file or different.

**Comment by HLSS-Hen** [comment] 2019-12-05 06:13
@gadagashwini 
you can use following code(use any database with shape [?,256,256,3]):
```
import os
os.environ['TF_AUTO_MIXED_PRECISION_GRAPH_REWRITE_IGNORE_PERFORMANCE'] = '1'
import math
import tensorflow as tf
from tensorflow import keras

class Swish(keras.layers.Layer):
    def __init__(self):
        super(Swish, self).__init__()
        self.weight = self.add_weight(initializer='uniform',trainable=True)

    def __call__(self, inputs):
        return inputs+tf.sigmoid(self.weight*inputs)


class Conv(keras.Model):
    def __init__(self,filters,kernel_size=1,strides=1,padding='valid'):
        super(Conv, self).__init__()
        self.conv = keras.layers.Conv2D(filters,kernel_size,strides,padding)
        self.bn = keras.layers.BatchNormalization()
        self.ac = Swish()

    def __call__(self,inputs):
        return self.ac(self.bn(self.conv(inputs)))


class SEBlock(keras.Model):
    def __init__(self, filters):
        super(SEBlock, self).__init__()
        self.conv0 = keras.layers.Conv2D(filters//4,1,1)
        self.drop = keras.layers.Dropout(0.25)
        self.conv1 = keras.layers.Conv2D(filters,1,1)
        self.bn = keras.layers.BatchNormalization()
        self.ac = Swish()

    def __call__(self,inputs):
        x = self.conv1(self.drop(self.conv0(tf.reduce_mean(inputs,[1,2],keepdims=True))))
        return self.ac(self.bn(tf.sigmoid(x)*inputs))


class ResBlock(keras.Model):
    def __init__(self, filters):
        super(ResBlock, self).__init__()
        self.conv0 = keras.layers.Conv2D(filters//4,1,1)
        self.drop = keras.layers.Dropout(0.25)
        self.conv1 = keras.layers.Conv2D(filters,3,1,'same')
        self.bn = keras.layers.BatchNormalization()
        self.ac = Swish()

    def __call__(self,inputs):
        x = self.conv1(self.drop(self.conv0(inputs)))
        return self.ac(self.bn(inputs+x))

def mcn_520(width, growth,input_shape=[256,256,3]):
    fs = int(width*growth)
    inputs=keras.layers.Input(input_shape)
    x=keras.layers.Conv2D(fs,8,2)(inputs)
    x=keras.layers.MaxPool2D(2)(x)
    x1=Conv(fs//width)(SEBlock(fs)(x))
    x2=Conv(fs//width)(ResBlock(fs)(x))
    for i, depth in enumerate([2, 3, 5, 4]):
        for _ in range(int(6*depth)):
            fs+=int(math.sqrt(fs*width))
            t=keras.layers.Concatenate()([x,x1,x2])
            t=keras.layers.Dropout(0.25)(t)
            t=Conv(fs//width, 1, 1)(t)
            t=keras.layers.Dropout(0.25)(t)
            x1=SEBlock(fs//width)(t)
            x2=ResBlock(fs//width)(t)
            t=keras.layers.Concatenate()([t,x1,x2])
            t=keras.layers.Dropout(0.25)(t)
            t=Conv(growth,1,1)(t)
            x=keras.layers.Concatenate()([x,t])
        if i != 3:
            fs //= 2
            x=keras.layers.MaxPool2D(2)(Conv(fs)(x))
            x1=keras.layers.MaxPool2D(2)(Conv(fs//width)(x1))
            x2=keras.layers.MaxPool2D(2)(Conv(fs//width)(x2))
    x=keras.layers.GlobalMaxPool2D()(x)
    x=keras.layers.Dropout(0.25)(x)
    outputs=keras.layers.Dense(1000,activation='softmax')(x)
    return keras.Model(inputs=inputs,outputs=outputs,name='MCN520')

for gpu in tf.config.experimental.list_physical_devices('GPU'):
    tf.config.experimental.set_memory_growth(gpu, True)
logical_gpus = tf.config.experimental.list_logical_devices('GPU')

starategy=tf.distribute.MirroredStrategy()
with starategy.scope():
    model=MCN.mcn_520(2,24)
    model.summary()
    model.compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(),
        optimizer=tf.keras.optimizers.SGD(),
        metrics=[tf.keras.metrics.TopKCategoricalAccuracy(1,'top1'),tf.keras.metrics.TopKCategoricalAccuracy(5,'top5')]
        )
    fit_ds,val_ds=ds(BATCH_SIZE)
    model.fit(
        fit_ds, # please use your database
        epochs=1000000,
        steps_per_epoch=BATCHS_PER_APLY_GRADIENTS*200,
    )
```

**Comment by gadagashwini** [comment] 2019-12-12 10:39
@HLSS-Hen, Please find the attached the [gist](https://colab.sandbox.google.com/gist/gadagashwini/68712f12f85f31da6a6fce73cde257e4/untitled295.ipynb) and help us in reproducing the issue. Thanks!

**Comment by HLSS-Hen** [comment] 2019-12-16 07:58
@gadagashwini  , sorry I took some time to  visit the page. And my google account have some wrong.
Please change `    model=MCN.mcn_520(2,24)` to `    model=mcn_520(2,24)` .
If you don't set in your dataset. please remove `model.fit` to the end.

**Comment by gadagashwini** [comment] 2019-12-17 07:40
I could replicate the issue with Tf 2.0.
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/955ccf74deb3065fb10a17cd08a0939d/untitled295.ipynb#scrollTo=chYTIWSIrgzX). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-12-20 23:52
@HLSS-Hen [This](https://github.com/tensorflow/tensorflow/issues/29472#issue-452812370) model is related to your issue but check the approach ('base_model') used to show pretrained model as one layer. Thanks.

**Comment by jvishnuvardhan** [comment] 2020-01-02 18:21
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-01-02 18:21 UTC
Labels: TF 2.0, comp:keras, type:bug
