### ISSUE TITLE
I'm working in colab and  changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error

### ISSUE THREAD

**Issue by ishkabir1401** [tensorflow/tensorflow#50809] opened 2021-07-16 20:04 UTC
@mihaimaruseac I'm working in colab and  changed `tf.gfile.GFile` to `tf.io.gfile.GFile` but still get this error
`AttributeError: module 'tensorflow' has no attribute 'gfile'
`

_Originally posted by @mitramir55 in https://github.com/tensorflow/tensorflow/issues/31315#issuecomment-643277101_

**Comment by ishkabir1401** [comment] 2021-07-16 20:05
I tried the way mentioned but still it is not working

**Comment by ymodak** [comment] 2021-07-16 21:33
I tried https://www.tensorflow.org/io/tutorials/avro tutorial which shows [tf.io.gfile.GFile](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile) usage example. I didn't see AttributeError raised.
Perhaps you can confirm at your end. Thanks!

**Comment by mihaimaruseac** [comment] 2021-07-18 21:29
Please fill in issue template. Please make sure you are using TF 2.x. Please post full error and code sample.

Without a reproducer we cannot do anything here.

**Comment by saikumarchalla** [comment] 2021-07-19 04:57
@ishkabir1401  If you are using TF 1.x, change import tensorflow as tf to import tensorflow.compat.v1 as tf and it works.
 
As suggested by @mihaimaruseac, Please fill the issue template. Thanks!

**Comment by saikumarchalla** [comment] 2021-07-28 16:28
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2021-07-28 16:28 UTC
Labels: comp:ops, stalled, stat:awaiting response, type:support
