### ISSUE TITLE
Which version of Protobuf do I need to compile the TensorFlow2.0 source code ？

### ISSUE THREAD

**Issue by tensorflowt** [tensorflow/tensorflow#45083] opened 2020-11-23 00:32 UTC
Which version of Protobuf do I need to compile the TensorFlow2.0 source code ？

**Comment by ravikyram** [comment] 2020-11-23 05:06
@tensorflowt 
Protobuf = 3.6.0 will be good to go.

You can install by below commands  and then import tensorflow.

```
pip uninstall protobuf
pip install protobuf==3.6.0
```
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by tensorflowt** [comment] 2020-11-23 10:16
HI！If I compile c++ source code is also this version ？

**Comment by mihaimaruseac** [comment] 2020-12-07 22:15
C++ code has versions specified in `workspace.bzl` file and automatically pulled for you when you do `bazel build`.

**Comment by ymodak** [comment] 2020-12-14 22:25
Closing this issue since its answered. Feel free to reopen if necessary. Thanks!

**Closed by ymodak** 2020-12-14 22:25 UTC
Labels: TF 2.0, type:build/install
