### ISSUE TITLE
tf.split T value inconsistency

### ISSUE THREAD

**Issue by alperyyildiz** [tensorflow/tensorflow#37210] opened 2020-03-01 17:51 UTC
tf.split raise ValueError when it is used before tf.identity to copy splitted tensors. Error seems related to split num parameter when it is set to None and occurs when split operation outputs more then 2 tensors. 

Code for the model:
        inp = tf.keras.layers.Input(shape=(102,df.shape[1]),dtype = 'float32')
        x0, x1, x2 = tf.split(inp,[66,22,14],axis=1,num=3)
        x00 = tf.identity(x0)
        x11 = tf.identity(x1)
        x22 = tf.identity(x2)

handled by the code:

        inp = tf.keras.layers.Input(shape=(102,df.shape[1]),dtype = 'float64')
        inp_ = tf.identity(inp)
        x0, x1, x2 = tf.split(inp,[66,22,14],axis=1,num=3) 
        x00, x11, x22 = tf.split(inp_,[66,22,14],axis=1,num=3)

Error raised:

ValueError: Inconsistent values for attr 'T' DT_DOUBLE vs. DT_FLOAT while building NodeDef 'split' using Op<name=SplitV; signature=value:T, size_splits:Tlen, split_dim:int32 -> output:num_split*T; attr=num_split:int,min=1; attr=T:type; attr=Tlen:type,default=DT_INT64,allowed=[DT_INT32, DT_INT64]>

**Comment by ravikyram** [comment] 2020-03-02 06:29
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Looks like code is incomplete. Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-17 01:15
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-17 03:56
@alperyyildiz 

Any update on this issue please. Thanks!

**Comment by tensorflowbutler** [comment] 2020-04-01 01:17
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-04-01 06:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-01 06:06 UTC
Labels: comp:ops, stat:awaiting response, type:support
