### ISSUE TITLE
tf.distributions.Gamma quantile not implemented, yet exists in documentation

### ISSUE THREAD

**Issue by MarkGreeny** [tensorflow/tensorflow#20208] opened 2018-06-22 01:29 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.6

Atempting to run

`tf.distributions.Gamma(concentration=10.,rate=0.2).quantile(0)`
we see that

> NotImplementedError: quantile is not implemented

But in the [documentation](https://www.tensorflow.org/api_docs/python/tf/distributions/Gamma) there is no indication of this function not being implemented, as the function is documented as all others are.

Is there something missing from my installation and the function should be present, or is it wrongly documented as existing?

**Comment by facaiy** [comment] 2018-06-22 09:24
I think gamma is not a monotone function, hence its `quantile` is implemented. 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Gamma_plot.svg/650px-Gamma_plot.svg.png)

**Comment by MarkGreeny** [comment] 2018-06-22 11:56
@facaiy Sorry, did you mean to say 

> hence its `quantile` is **not** implemented

Of that is so, I think we could remove it from the documentation. Same goes for exponential distribution and a few others. Current documentation is written as if these functions are implemented.

**Comment by facaiy** [comment] 2018-06-22 14:45
@MarkGreeny I afraid that `quantile` of gamma doesn't exist, and that's why we leave it NotImplementedError. I agree that we'd better document it.

**Comment by tensorflowbutler** [comment] 2018-07-07 18:37
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by srvasude** [comment] 2018-07-15 19:41
Hi,
  This is documented incorrectly. The quantile function can exist but would require some implementation of something like this: http://reference.wolfram.com/language/ref/InverseGammaRegularized.html.

The issue here is that all these public methods exist on distributions (which call private methods), and hence docstrings always exist (even though the private methods might not be implemented).

**Comment by cy89** [comment] 2018-07-21 00:48
@srvasude so can or should we mark this "docs"? Is there a way to override the docstring for tf.distributions.Gamma?

**Comment by tensorflowbutler** [comment] 2018-08-04 18:41
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-19 18:49
Nagging Assignee @cy89: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-03 18:39
Nagging Assignee @cy89: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pwaller** [comment] 2018-09-11 15:41
The same problem exists for Beta - this is very confusing. Is it not implemented for beta?

**Comment by guyko81** [comment] 2018-10-11 10:30
hi, what about cheating and using scipy? Is it legit?

###################
## EXAMPLE CODE ##
###################

import tensorflow as tf

concentration=3.
rate=1.5
quantile = 0.000001

def my_func(x):
    return np.float32(stats.gamma(a=concentration, loc=0., scale=1/rate).ppf(x))

quantile = tf.py_func(my_func, [quantile], tf.float32)

with tf.Session() as sess:
    print(quantile.eval())

**Comment by tensorflowbutler** [comment] 2018-10-26 12:47
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-10 18:45
Nagging Assignee @cy89: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-25 18:34
Nagging Assignee @cy89: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by EliasHasle** [comment] 2019-06-07 05:58
Same problem goes for Mixture. Very disappointing to see after all my struggles getting to the point were I was going to use the quantiles for a plot.

@facaiy If I am not wrong, a quantile can be derived from the CDF (if available), which should always be monotonically increasing. Besides, the Gamma distribution is not the same as the Gamma function.

**Comment by CarloGraziani** [comment] 2019-08-06 20:25
I just ran into this too, and it's a major problem for me -- I need the gamma quantile.

EliasHasle is correct -- the quantile exists, and is simply the inverse of the CDF, which is monotonic.  

Note also that scipy has an implementation -- see scipy.special.gammaincinv(). I assume it shares code with scipy.stats.gamma.ppf().

**Comment by CarloGraziani** [comment] 2019-08-09 21:05
I've come up with a work-around, based on Newton-Raphson root finding and the tf.while_loop() construct.  The following code computes the inverse of the regularized lower incomplete gamma function (as implemented by tf.igamma()), which is equivalent to the gamma distribution quantile method:

```
#!/usr/bin/python3

import numpy as np
import tensorflow as tf
from scipy.special import gammaln, gammainc
from scipy.stats import gamma

nsamp=10 # Dimension of vector of cdfs to be inverted
ndim = 40 # 'a' (shape) parameter of gamma distribution
eps = 1.0E-04 # Termination accuracy
maxiter = 20 # Maximum number of iterations

Ndim = tf.constant(ndim, dtype=tf.float32)
lnorm = gammaln(ndim)


def body(tgt, currx, currf, currdf, iter):
    iter = iter + 1
    nextx = currx - (currf - tgt)/ currdf
    nextf = tf.igamma(Ndim, nextx)
    nextdf = tf.exp(-nextx + tf.log(nextx)*(Ndim-1) - lnorm)
    return tgt, nextx, nextf, nextdf, iter

def cond(tgt, currx, currf, currdf, iter):
    disc = tf.abs((tgt - currf)/tgt)
    not_converged = tf.logical_and( tf.reduce_any(disc > eps) , iter < maxiter )
    return not_converged

x = gamma.rvs(ndim, size=nsamp) # true x values to be located
u = gammainc(ndim, x) # true target function values
U = tf.constant(u, dtype=tf.float32)
F = tf.constant(np.zeros(nsamp), dtype=tf.float32)
dF = tf.constant(np.ones(nsamp), dtype=tf.float32)
X = tf.constant(np.ones(nsamp)*(ndim-1), dtype=tf.float32) # inital guesses
Iter = tf.constant(0)

loop_vars = [U, X, F, dF, Iter]

res = tf.while_loop(cond, body, loop_vars)

with tf.Session() as sess:
    tgt, currx, currf, currdf, iter = sess.run(res)

    print("Target x:\n", x)
    print("Target funcvals:\n", tgt)
    print("Solved x:\n", currx)
    print("Solved funcvals:\n", currf)
    print("Iterations: %d" % iter)

```

I've done some restricted testing, and it seems to work for a good range of ndim values. In the range 2-40 convergence occurs in 5-8 iterations at for eps=1.0E-04.

**Comment by CarloGraziani** [comment] 2019-08-13 13:48
This is not an ideal workaround, because it is inefficient from the standpoint of autodiff. The graph of the forward-rlowed function will consist of those 5-8 iterations that havr to be differentiated through. The derivatives of this function are known in closed for, and a sane implementation would use those expressions.

Which is to say, an effort commitment by a tensorflower to fix this problem would be welcome.

**Comment by SoapClancy** [comment] 2020-07-03 12:17
A similar issues is found for tfp.distributions.TruncatedNormal.

NotImplementedError: quantile is not implemented: TruncatedNormal, yet it exists in the [documentation ](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TruncatedNormal#quantile)

**Comment by Demetrio92** [comment] 2020-07-20 12:02
This thread is sad. We're not talking about the Gamma function, but the gamma distribution. Where you use `gamma(alpha)` as a **constant**. 

For a workaround implementation, which also works with the mixture of gamma distributions see https://github.com/tensorflow/probability/issues/659

**Comment by CarloGraziani** [comment] 2020-07-22 19:41
@Demetrio92 , what you are suggesting in no way addresses the issue discussed here.  The gamma distribution inverse  (and yes, we already knew it was a distribution, and you would be aware of it had you read the thread in full) has known specific approximations and algorithms, as do its derivatives.  A generic quadrature or iterative approach is at best a work-around.  What is required here is for known working code from scipy.special (for example) to be tensorflow-ified by a tensorflower. It is not helpful to suggest that the issue is addressed by your work-around (or by mine, above, for that matter).

**Comment by srvasude** [comment] 2021-02-13 13:09
Closing this as the Gamma distribution and related friends have quantiles now.

**Closed by srvasude** 2021-02-13 13:09 UTC
Labels: stat:awaiting tensorflower
