### ISSUE TITLE
Spurious tf.function retracing warnings, when developing Keras layer in colab

### ISSUE THREAD

**Issue by janpfeifer** [tensorflow/tensorflow#43555] opened 2020-09-25 07:15 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Developing in colab with TF/Keras I always get these random seemingly unrelated warnings. 

**Describe the expected behavior**
No warnings.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/18XwRl5d8qY1L1qKPMm-A9NT_m4qB0UxZ?usp=sharing

Code that generate issue:

```
import tensorflow as tf
for ii in range(10):
  # Notice class definition *inside the loop*.
  class MyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
      super(MyLayer, self).__init__(**kwargs)

    def call(self, inputs, training=None):
      return 2*inputs

  i1 = tf.keras.Input((1,))
  logits = MyLayer()(i1)
  model = tf.keras.Model(inputs=i1, outputs=logits)
  model.predict(x=[[0.0], [1.0], [3.0]], batch_size=1)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-09-25 10:46
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/1a6760a344736f1c30dfb1265f6db4d7/43555.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3328ac18feba642ee515c71e38f469f4/43555-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by bhack** [comment] 2020-09-25 14:56
@amahendrakar I think is a dup of https://github.com/tensorflow/tensorflow/issues/38561

**Comment by bhack** [comment] 2020-09-25 15:02
@janpfeifer #38561 is solved in nightly but in you specific example it is an expected behavoiur. 
See: https://github.com/tensorflow/tensorflow/issues/42441#issuecomment-675654182

**Comment by nikitamaia** [comment] 2020-09-25 21:02
@bhack @janpfeifer After a closer look this warning is confusing and should probably be removed. Until then, if you want to manage the tf.function yourself you can use `predict_step()` as suggested in #42441, which will not result in the warning.

**Comment by janpfeifer** [comment] 2020-09-29 09:35
Thanks, yes, this seems a dup. 

And thanks for the fix suggestion. I think i'll live with with the warning eyesore ... I dislike having these hacks (with potential unintended consequences) that need to be undone later.

**Comment by nikitamaia** [comment] 2021-05-17 17:05
Some work has been done to reduce retracing warnings, and testing with nightly results in only two warnings in this case.
[Gist here.](https://colab.research.google.com/gist/nikitamaia/0cc6732434b5b32782a4ab0d3d5b254a/43555.ipynb)

**Comment by bhack** [comment] 2021-05-17 18:24
@nikitamaia Have you tried in your colab:
```python
import tensorflow as tf
for ii in range(10):
  # Notice class definition *inside the loop*.
  class MyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
      super(MyLayer, self).__init__(**kwargs)

    def call(self, inputs, training=None):
      return 2*inputs

  i1 = tf.keras.Input((1,))
  logits = MyLayer()(i1)
  model = tf.keras.Model(inputs=i1, outputs=logits)
  model.build(input_shape=(1,))
  model.predict(x=[[0.0], [1.0], [3.0]], batch_size=1)
```

**Comment by janpfeifer** [comment] 2021-05-18 05:09
@bhack I just updated the colab to force install of the new TF 2.5.0 (by default it comes with 2.4.1) and verified that the retrace was only called twice:

https://colab.research.google.com/drive/18XwRl5d8qY1L1qKPMm-A9NT_m4qB0UxZ?usp=sharing

I feel the issue is fixed. I mean better yet if there were no retracing ... :)

**Comment by bhack** [comment] 2021-05-18 08:32
Have you tried with my example?

**Comment by janpfeifer** [comment] 2021-05-18 09:03
Interesting, I just did, I [added it to the colab](https://colab.research.google.com/drive/18XwRl5d8qY1L1qKPMm-A9NT_m4qB0UxZ#scrollTo=B26kne4tr_ck).

This time around there were no warnings at all, neither on yours or mine.

Btw, I believe you don't need to call `model.build(...)`, since the input is specified (by `tf.kerars.Input(...)`). 

At least according to [tf.keras.Sequential doc page](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential)

**Comment by bhack** [comment] 2021-05-18 09:07
Yes but I think It Is similar to https://github.com/tensorflow/tensorflow/issues/48851#issuecomment-830858393

**Comment by bhack** [comment] 2021-05-18 09:54
P.s. Just to summarize `tf.keras.Input` is going to create a placeholder internally if you don't pass your tensor with the `tensor` arg (it is in the documentation).

E.g. You can try yourself, this will not retrace as with `build`:

```
import tensorflow as tf
for ii in range(10):
  # Notice class definition *inside the loop*.
  class MyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
      super(MyLayer, self).__init__(**kwargs)

    def call(self, inputs, training=None):
      return inputs

  b = tf.constant([5])
  i1 = tf.keras.Input(shape=(1,), tensor=b)
  logits = MyLayer()(i1)
  model = tf.keras.Model(inputs=i1, outputs=logits)
  #model.build(input_shape=(1,))
  print(model.predict(x=[[0.0], [1.0], [3.0]], batch_size=1))
```

**Comment by janpfeifer** [comment] 2021-05-18 13:12
Sorry I'm not sure I'm following.

`tf.Keras.Input` is a placeholder exactly! And it can have a variable size (let's say the batch dimension).

Searching the docs a bit, `build()` seems to be [a method of `keras.Layer`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#build), not of [`keras.Model`](https://keras.io/api/models/model/). Since Keras models can be a Layer, I believe that's why they have also the `build()` method. I don't think it needs calling in your case (it will be called automatically for the layers in your Model once you "call" it).

**Comment by bhack** [comment] 2021-05-18 13:36
The difference is that it will be re-trigger tracing cause what you do in fit is executed in grap mode.

> And it can have a variable size (let's say the batch dimension).

As fit is running in `graph_mode` and in your examples  you cannot explicitly control `@tf.function(experimental_relax_shapes=True)` it will going to trigger retrace.

**Comment by nikitamaia** [comment] 2021-05-24 22:19
Closing issue since the number of warnings has been decreased.

**Closed by nikitamaia** 2021-05-24 22:19 UTC
Labels: TF 2.3, comp:tf.function, type:bug

**Comment by timhdesilva** [comment] 2022-03-01 00:54
Update: I'm having the same problem described above with ``.predict()``, but am able to use the ``.predict_step()`` workaround.

**Comment by jvishnuvardhan** [comment] 2022-03-01 20:45
@timhdesilva As this issue closed long timme back, please open a new issue with a simple standalone code to reproduce the issue. Thanks!
