### ISSUE TITLE
Cannot run mobilenet_0.25_128_quantized image retrain

### ISSUE THREAD

**Issue by rish321** [tensorflow/tensorflow#15701] opened 2017-12-28 18:23 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: python tensorflow/examples/image_retraining/retrain.py --image_dir /path/to/image/dir/  --architecture mobilenet_0.25_128_quantized

### Describe the problem
while trying to create a mobilenet model, getting this error. The url being created in the retrain.py file, is not accessible via browser either.

### Source code / logs
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/imagenet/mobilenet_v1_0.25_128_quantized_frozen/quantized_frozen_graph.pb; No such file or directory

**Comment by bignamehyp** [comment] 2017-12-28 19:56
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by litenjacob** [comment] 2018-01-16 19:32
It is actually a bug, if only in the hosting, since the file [http://download.tensorflow.org/models/mobilenet_v1_0.25_128_quantized_frozen.tgz](http://download.tensorflow.org/models/mobilenet_v1_0.25_128_quantized_frozen.tgz) is not reachable, whereas eg. [http://download.tensorflow.org/models/mobilenet_v1_1.0_224_quantized_frozen.tgz](http://download.tensorflow.org/models/mobilenet_v1_1.0_224_quantized_frozen.tgz) is.

**Comment by rishflip** [comment] 2018-01-16 19:37
+1

**Comment by tensorflowbutler** [comment] 2018-02-06 07:38
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by litenjacob** [comment] 2018-02-09 12:58
Yes, this is still an issue: [http://download.tensorflow.org/models/mobilenet_v1_0.25_128_quantized_frozen.tgz](http://download.tensorflow.org/models/mobilenet_v1_0.25_128_quantized_frozen.tgz) and many of the other smaller models aren't reachable.

**Comment by tushuhei** [comment] 2018-02-14 09:11
+1

**Comment by tushuhei** [comment] 2018-02-14 13:53
Duplicate of #15009

**Comment by suharshs** [comment] 2018-02-27 05:28
We have published new models here: https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

I have pushed changes to the retrain script to support these, once the next sync happens.

Commands like
```
python tensorflow/examples/image_retraining/retrain.py \
    --image_dir ~/flower_photos/   --architecture mobilenet_1.0_224_quant
```
should work for all depth multipliers and image sizes.

Please create a new issue if things don't work once github pulls in the changes to retrain.py

**Closed by suharshs** 2018-02-27 05:28 UTC
Labels: stat:awaiting response
