### ISSUE TITLE
Unable to run "bazel build tensorflow/examples/image_retraining:retrain"

### ISSUE THREAD

**Issue by atwj** [tensorflow/tensorflow#4701] opened 2016-10-01 04:10 UTC
Hi! I was going through the re-trainer tutorial but i keep encountering the following error.

<code>Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
error: Could not expand include path '~/.gitcinclude'
fatal: bad config file line 49 in /usr/local/git/etc/gitconfig
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 254, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 207, in generate
    write_version_info(dest_file, git_version)
  File "tensorflow/tools/git/gen_git_source.py", line 160, in write_version_info
    if b"\"" in git_version or b"\" in git_version:
TypeError: 'in <string>' requires string as left operand, not bytes
Target //tensorflow/examples/image_retraining:retrain failed to build
Use --verbose_failures to see the command lines of failed build steps. </code>

Am i doing something incorrectly?

**Comment by olivermg** [comment] 2016-10-01 08:24
This happens when using Python 3, as that code in gen_git_source.py ('b"\"" in ...' etc.) works only for Python 2.

As a workaround, I've patched my gen_git_source.py locally by removing these 'b' characters (thus passing a string into the "in" operation instead of a byte). However, this is probably just a workaround, as this change may make it incompatible with Python 2 and only work with Python 3.

**Comment by ceocookie** [comment] 2016-10-01 17:40
Hi @olivermg Could you advise how do you run tensorflow using Python 2? After installing with tensorflow using conda (anaconda2-4.1.1) , I proceed to clone the tensorflow repo, run /.configure before attempting to execute "bazel build tensorflow/examples/image_retraining:retrain". However I still get the following issues:

<code>
ERROR: /Users/AMOS/Documents/PROJECTS/iot-tensorflow-py2/tensorflow/tensorflow/core/BUILD:1030:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
error: Could not expand include path '~/.gitcinclude'
fatal: bad config file line 49 in /usr/local/git/etc/gitconfig
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 254, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 207, in generate
    write_version_info(dest_file, git_version)
  File "tensorflow/tools/git/gen_git_source.py", line 160, in write_version_info
    if b"\"" in git_version or b"\\" in git_version:
TypeError: 'in <string>' requires string as left operand, not bytes
Target //tensorflow/examples/image_retraining:retrain failed to build
</code>

Thanks!

**Comment by ceocookie** [comment] 2016-10-01 18:05
I followed your post here ( https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/discuss/lOEFA0PHguA/46Za6_ouAwAJ ) and tried to set up Python 2 using conda. But i encounter similar issues.

<code>
tensorflow/tensorflow/core/BUILD:1030:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command
  (cd /private/var/tmp/_bazel_AMOS/ad612b9cca884ed29e9c8b7eb90ae243/execroot/tensorflow && \
  exec env - \
    PATH='/usr/local/sbin:/Users/AMOS/.rbenv/shims:/Users/AMOS/.jenv/shims:/Users/AMOS/.jenv/bin:/usr/local/Cellar/pyenv-virtualenv/1.0.0/shims:/Users/AMOS/.pyenv/shims:/Users/AMOS/.nvm/versions/node/v6.2.2/bin:/Users/AMOS/.node/bin:export /usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/TeX/texbin' \
    TMPDIR=/var/folders/d6/7pkzyf4j25b21nqs_05n_ch80000gn/T/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate tensorflow/tools/git/gen/spec.json tensorflow/tools/git/gen/head tensorflow/tools/git/gen/branch_ref "bazel-out/local-opt/genfiles/tensorflow/core/util/version_info.cc"'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
error: Could not expand include path '~/.gitcinclude'
fatal: bad config file line 49 in /usr/local/git/etc/gitconfig
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 254, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 207, in generate
    write_version_info(dest_file, git_version)
  File "tensorflow/tools/git/gen_git_source.py", line 160, in write_version_info
    if b"\"" in git_version or b"\\" in git_version:
TypeError: 'in <string>' requires string as left operand, not bytes
Target //tensorflow/examples/image_retraining:retrain failed to build
</code>

**Comment by olivermg** [comment] 2016-10-01 18:34
As far as I understand the whole process, the necessary steps to have bazel run with Python2, you have to follow these steps (assuming Anaconda):

1. Create the Anaconda virtual env via `conda create -n tensorflow python=2.7` . A thing to note here: Don't run this command from within your cloned working copy of Tensorflow Serving, as the conda command seems to get confused when a directory "tensorflow" exists in the current working directory. I think it'll try to install the virtual env into that folder then, which is not what you want. Ergo: Run that conda command from within a directory in which NO directory named "tensorflow" (or whatever name you choose) exists.

2. Make sure that no bazel processes exist from previous calls to it, as that may result in bazel "remembering" parts of the environment you had previously. So to be on the safe side, kill all potentially running bazel processes. I was actually wondering why bazel wasn't using Python2 although I was in a corresponding Anaconda environment. As I've figured out after a while, it was because bazel was obviously picking up a bazel process created earlier when I was still trying Python3.

3. Activate the Anaconda environment you created in step 1 via `source activate tensorflow`.

4. You should now have Python2 being the default. You can check via e.g. `pip --version` or `python --version`.

5. (Make sure that you install the necessary pip dependencies into this virtual env, like numpy & mock, via `pip install numpy mock`.)

This should allow you to run bazel using Python2 as far as my brief knowledge is concerned ;) .

**Comment by aselle** [comment] 2016-10-11 18:36
gen_git_source.py should work in Python 3 and Python 2. It used to not have the b"  prefixes on the string literals, but @mrry added them for Windows compatibility. Looking, but the easiest work around is to just edit gen_git_source.py to remove the b" in the string literals.

**Comment by aselle** [comment] 2017-06-14 01:40
Automatically closing due to lack of recent activity. Please file a new issue referring to this issue, if the issue is still relevant and important. If this is documenting some kind of bug, be sure to use the latest version of TensorFlow. Thank you so much.

**Closed by aselle** 2017-06-14 01:40 UTC
