### ISSUE TITLE
builld tf 1.10.0, but version shows rc1

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#21427] opened 2018-08-07 02:50 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04 x64
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6.6 x64
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.2/7.1.5
- **GPU model and memory**: GTX1080Ti GDDR5X 11GB  X 6
- **Exact command to reproduce**: 

pip generated as 1.10
install complete and shows 1.10

import tensorflow as tf
print(tf.__verison__)

1.10.0-rc1

**Comment by gragundier** [comment] 2018-08-07 07:02
https://github.com/tensorflow/tensorflow/releases
1.10 is still prerelease
You used pip3 install tensorflow-gpu?  That's weird and definitely a bug if you did.

**Comment by alanpurple** [comment] 2018-08-07 07:07
@gragundier  no i build from r1.10 source as I wrote above.....what ru sayin....

**Comment by alanpurple** [comment] 2018-08-07 07:29
@gragundier 
you're really not helping

https://github.com/tensorflow/tensorflow/commit/d2af5d50b6255c4bc76b9e9fc516a0aa027efe6d

**Comment by gragundier** [comment] 2018-08-07 08:05
I'm just cranky because ci.tensorflow.org is down. 😞

**Comment by av8ramit** [comment] 2018-08-07 16:30
ci.tensorflow.org is not down. We have deprecated it. Any nightly builds you need can be found at the tf-nightly or tf-nightly-gpu.

Additionally I've just merged the [latest version change](https://github.com/tensorflow/tensorflow/commit/d2af5d50b6255c4bc76b9e9fc516a0aa027efe6d). Can you try again with the latest r1.10 branch?

**Comment by gunan** [comment] 2018-08-07 16:39
@alanpurple could you also share the output of `tf.__git_version__` ?
@gragundier ci.tensorflow.org is deprecated, and is finally taken down for good. So the site being down is working as intended.

**Comment by gragundier** [comment] 2018-08-07 23:38
@av8ramit Then, I've got a question.  Recently, the regular raspberry pi tf binary's tflite interpreter didn't work because of an armv7 optimization bug.  Turns out, I could pull the latest pi-zero binary compilation and use that instead.  I understand this isn't a problem with other hardware: "Broken tf-nightly version? Roll it back to a stable release." But with Raspberry Pi's I can use either the Pi-Zero or Pi3 specific binaries.  How would I choose which of those binaries I pip install?

**Comment by alanpurple** [comment] 2018-08-07 23:54
@gunan 
b'v1.10.0-rc1-12-gbae6aeffc0'

**Comment by gragundier** [comment] 2018-08-08 04:53
@av8ramit it has absolutely nothing to do do with the topic and I don't see a DM feature.  Let me open a new issue and we can stop pestering alanpurple.  And yes, you're right on the money.

**Comment by gunan** [comment] 2018-08-08 06:09
@alanpurple I suspect this is due to 1.10 official still not being out, and the tag not being generated in our repo.
May I ask, why do you need the package with 1.10 label before we release the official 1.10?

**Comment by alanpurple** [comment] 2018-08-08 06:56
@gunan 

That's not what "I need"
I just report this because your repo says " 1.10 " and actually is not

https://github.com/tensorflow/tensorflow/commit/d2af5d50b6255c4bc76b9e9fc516a0aa027efe6d
this is just a report, not my problem

**Comment by gunan** [comment] 2018-08-08 19:52
Thanks for the report. The version string generation mechanism is actually more than just what is at the repo. Once all the git tags are created, and release is finalized, this will be pointing to 1.10.

I will close this issue for now.

**Closed by gunan** 2018-08-08 19:52 UTC
