### ISSUE TITLE
Using Tensorflow 2.0 loss functions that require inputs gives "`tf.Tensor` as a Python `bool` is not allowed"  error

### ISSUE THREAD

**Issue by bdzyubak** [tensorflow/tensorflow#31850] opened 2019-08-21 17:48 UTC
** System information **

- Wrote custom code for simple model
- Ubuntu 16.04.6 LTS
- Tensorflow 2.0.0-beta1 installed from binary using pip
- Python 3.7, no CUDA or GPU
- Loading a saved model results in error:
init() got an unexpected keyword argument 'reduction'

** Code to reproduce the issue **

Relevant architecture: 

```
labels = tf.keras.Input(batch_shape=(batch_size, xsze, ysze), name='labels')
logits = tf.keras.layers.Conv2D(1, [1, 1], activation='linear', name='output_x')(drop11)
model = tf.keras.Model(inputs=[input_x], outputs=[logits]
model.compile(optimizer=tf.keras.optimizers.Adam(),  
              loss=loss, 
              metrics=[tf.keras.losses.MeanSquaredError()])
```

If I use a keras loss class that doesn't require explicit input arguments, it works fine: 
`loss = tf.keras.losses.MeanSquaredError() `

But I get the error with any loss that requires inputs: 
`loss = tf.keras.losses.sparse_categorical_crossentropy(labels,logits)`

Including custom functions which don't seem to be mixing numpy and tensor operations, nor do they check for if not None: 

```
def dice_loss_per_image(labels, logits):
     smooth = tf.constant(1e-17,dtype=float)

    numerator = tf.constant(2, dtype=float) * tf.reduce_sum(labels * logits, axis=(1, 2))
    denominator = tf.reduce_sum(labels + logits, axis=(1, 2))

    loss = tf.constant(1.0,dtype=float) - (numerator + smooth)/(denominator + smooth)
    return loss
```

** Error traceback ** 

Traceback (most recent call last):
  File "/home/m047659/Programs/pycharm/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 137, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    training_config, custom_objects))
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 458, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 320, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1735, in _cache_output_metric_attributes
    metrics, self.output_names, output_shapes, self.loss_functions)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 755, in collect_per_output_metric_info
    metric_name = get_metric_name(metric, is_weighted)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 929, in get_metric_name
    metric = metrics_module.get(metric)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 2833, in get
    return deserialize(identifier)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 2827, in deserialize
    printable_module_name='metric function')
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/m047659/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 451, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'reduction' 

Any way to fix this? 
Thank you.

**Comment by ravikyram** [comment] 2019-08-22 11:12
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks!

**Comment by ravikyram** [comment] 2019-08-30 04:04
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-30 04:04 UTC
Labels: TF 2.0.0-beta0, comp:keras, stat:awaiting response, type:support

**Comment by ghunkins** [comment] 2020-01-27 01:38
For anyone running into this, particularly when looking to run inference on a pre-trained `tf.keras.Model` object, simply load the model with the flag `compile=False`.

```python
model = tf.keras.models.load_model('model_file.hdf5', compile=False)
```

You will still be able to run inference using the `predict` functionality.

**Comment by ravikyram** [comment] 2020-01-27 04:28
@ghunkins 

Request you to open the new issue by filling the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by ghunkins** [comment] 2020-01-27 04:30
@ravikyram No issue, just adding a solution for any other lonely wanderers who have the same question / issue.

**Comment by Yashgh7076** [comment] 2020-02-29 18:08
@ghunkins Thanks a lot! Your suggestion works. Any intuition behind what is actually going on? This issue only seems to affect saved models. That is a model which is created and tested immediately after training does not have this issue.

**Comment by pamudu123** [comment] 2023-02-19 11:01
I want to train from what I have stopped by loading the model.Then what is the solution

**Comment by ABMHub** [comment] 2023-04-12 21:54
> I want to train from what I have stopped by loading the model.Then what is the solution

Keras is trying to pass `reduction` as a keyword variable to your class constructor, so just adding a `**kwargs` to my constructor header solved the problem for me.
