### ISSUE TITLE
Low GPU usage while executing CNN with keras (tf backend)

### ISSUE THREAD

**Issue by ChetanRajput** [tensorflow/tensorflow#36175] opened 2020-01-24 07:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): tensorflow 2.0.0
- Python version: Python 3.7.6
- CUDA/cuDNN version: cuda10.0_0 / cudnn 7.6.5
- GPU model and memory: RTX 2060 - 6GB

**Describe the current behavior**
While executing my conv neural net  I am getting GPU usage of 1%.

**Describe the expected behavior**
As no other application is using my resource I should be able to use my GPU at least at 80-85 % 

**Code to reproduce the issue**
```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)

    except RuntimeError as e:
        print(e)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Convolution2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense

classifier = Sequential()

classifier.add(Convolution2D(32, 3, 3, input_shape = (64, 64, 3), activation = 'relu'))

classifier.add(MaxPooling2D(pool_size = (2, 2)))

classifier.add(Convolution2D(32, 3, 3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

classifier.add(Flatten())

classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 1, activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 4,
                                                 class_mode = 'binary')

test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 4,
                                            class_mode = 'binary')

classifier.fit_generator(training_set,
                         steps_per_epoch = 8000,
                         epochs = 25,
                         validation_data = test_set,
                         validation_steps = 2000)
Got error after execution of last section :

classifier.fit_generator(training_set,
                             steps_per_epoch = 8000,
                             epochs = 25,
                             validation_data = test_set,
                             validation_steps = 2000)

```

**Comment by turfday** [comment] 2020-01-25 20:42
This has always been a problem since Tensorflow 2.0 was released.

**Comment by amahendrakar** [comment] 2020-01-27 12:29
@ChetanRajput,
Could you please provide the supporting files you are using. Tried to reproduce the error but was unable to do so, please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/e15d127d27ab2cfea9bedd1b67e8c34d/36175.ipynb). Thanks!

**Comment by amahendrakar** [comment] 2020-02-04 12:36
@ChetanRajput,
Any updates regarding the supporting files required to reproduce this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-02-11 06:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2020-02-11 06:30 UTC
Labels: stat:awaiting response
