### ISSUE TITLE
why some OPs are not shown on timeline

### ISSUE THREAD

**Issue by lxl910915** [tensorflow/tensorflow#32203] opened 2019-09-04 10:07 UTC
why some OPs are not shown on timeline, such as FlatMapDataset, PrefetchDataset and ParallelMapDataset.

**Comment by gadagashwini** [comment] 2019-09-05 06:39
@lxl910915,
Could you elaborate the issue with context. Thanks!

**Comment by lxl910915** [comment] 2019-09-05 07:52
> @lxl910915,
> Could you elaborate the issue with context. Thanks!

We use tf.data.Dataset to read dataset file, and we also used map,batch,shuffle,prefetch OPs and so on. While on timeline, we can not find those OPs.

Code as follows:
```
dataset = tf.data.Dataset.list_files(data_dir, shuffle=False)
            dataset = dataset.interleave(
                lambda x: tf.data.TextLineDataset(x), cycle_length=4,
                block_length=batch_size)
            dataset = dataset.repeat(epochs)
            dataset = dataset.prefetch(batch_size * 10)
            dataset = dataset.shuffle(batch_size * 10)
            dataset = dataset.batch(batch_size)
            def parse(line):
                ...
                return label, feature
            dataset = dataset.map(parse)
            dataset = dataset.prefetch(1)
            label, feature = dataset.make_one_shot_iterator().get_next()
```

**Comment by gadagashwini** [comment] 2019-09-05 11:26
@lxl910915, Will it be possible to provide minimal standalone code reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2019-09-17 06:28
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-09-17 06:28 UTC
Labels: comp:data, comp:ops, stat:awaiting response, type:support
