### ISSUE TITLE
Cannot convert a Tensor of dtype resource to a NumPy array

### ISSUE THREAD

**Issue by evyasonov** [tensorflow/tensorflow#42673] opened 2020-08-26 09:10 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
Colab is here: https://colab.research.google.com/drive/1X0MhpbPbguscxwY-UDyp9d0OsL5hANR2?usp=sharing
```
tfliteModel = tf.lite.TFLiteConverter.from_keras_model(model).convert()
```

**The output from the converter invocation**
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-11-ef48ab45d342> in <module>()
----> 1 tfliteModel = tf.lite.TFLiteConverter.from_keras_model(model).convert()
      2 
      3 with tf.io.gfile.GFile('my_model.tflite', 'wb') as f:
      4     f.write(tfliteModel)

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    807     frozen_func, graph_def = (
    808         _convert_to_constants.convert_variables_to_constants_v2_as_graph(
--> 809             self._funcs[0], lower_control_flow=False))
    810 
    811     input_tensors = [

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2_as_graph(func, lower_control_flow, aggressive_inlining)
   1101       func=func,
   1102       lower_control_flow=lower_control_flow,
-> 1103       aggressive_inlining=aggressive_inlining)
   1104 
   1105   output_graph_def, converted_input_indices = _replace_variables_by_constants(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in __init__(self, func, lower_control_flow, aggressive_inlining, variable_names_whitelist, variable_names_blacklist)
    802         variable_names_whitelist=variable_names_whitelist,
    803         variable_names_blacklist=variable_names_blacklist)
--> 804     self._build_tensor_data()
    805 
    806   def _build_tensor_data(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in _build_tensor_data(self)
    821         data = map_index_to_variable[idx].numpy()
    822       else:
--> 823         data = val_tensor.numpy()
    824       self._tensor_data[tensor_name] = _TensorData(
    825           numpy=data,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in numpy(self)
   1061     """
   1062     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1063     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1064     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1065 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1029       return self._numpy_internal()
   1030     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1031       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1032 
   1033   @property

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Also, please include a link to the saved model or GraphDef**
```
https://drive.google.com/file/d/1iXmNGjMTPoqzBRpeNmTjarGGEIBK8Jdr/view?usp=sharing
```

**Any other info / logs**
I can't convert a model which contains tf.keras.layers.experimental.preprocessing.TextVectorization to tf.lite.
I've got this error:
```InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.```

- I saw this issue ( https://github.com/tensorflow/tensorflow/issues/32693 ) and tried to use `converter.experimental_new_converter = True` -- it did not help
- I saw this answer ( https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array ) and tried to use a custom layer -- it did not help

Please see this colab:
https://colab.research.google.com/drive/1X0MhpbPbguscxwY-UDyp9d0OsL5hANR2?usp=sharing

Can you please help me

**Comment by Saduf2019** [comment] 2020-08-26 15:32
@evyasonov 
Please update the issue template with the tf version.
With respect to the error shared, please refer to:
[link](https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array) #39918 #32693 #42113 #38305 #37441

**Comment by evyasonov** [comment] 2020-08-28 11:17
> @evyasonov
> Please update the issue template with the tf version.
> With respect to the error shared, please refer to:
> [link](https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array) #39918 #32693 #42113 #38305 #37441

I updated the issue

**Comment by Saduf2019** [comment] 2020-08-28 15:15
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/133680d5d43aa31cf2f1f81d49fa2191/untitled398.ipynb)

**Comment by jvishnuvardhan** [comment] 2020-08-28 16:53
@evyasonov Can you please check this issue that is very similar to you and let us know whether it resolved your issue or not. Thanks!

**Comment by evyasonov** [comment] 2020-08-29 08:21
@jvishnuvardhan 
As you can see, first I added my comment to the issue you mentioned and only then I created this one. I tried to create a custom layed, but had no success. Maybe I did it wrong, but the resolution that woked in the issue you mention did not work for me.

**Comment by abattery** [comment] 2020-09-01 02:24
Could you try the conversion with from_saved_model within tf-nightly version? You can avoid the above error through the from_saved_model with tf-nightly version.

**Comment by evyasonov** [comment] 2020-09-01 12:05
@abattery 
I've installed tf-nightly, but now I can not import tensorflow_text:
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-cefb365966a1> in <module>()
      1 import tensorflow          as tf
----> 2 import tensorflow_text     as tft
      3 import sys

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     56     RuntimeError: when unable to load the library or get the python wrappers.
     57   """
---> 58   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     59   try:
     60     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

See this colab:
https://colab.research.google.com/drive/1X0MhpbPbguscxwY-UDyp9d0OsL5hANR2?usp=sharing

**Comment by abattery** [comment] 2020-09-01 23:29
@evyasonov For your problem, I think you can refer to the following issue:

https://github.com/tensorflow/text/issues/160

**Comment by evyasonov** [comment] 2020-09-02 19:28
@abattery 
I added a comment into the issue you refered. But I found no solution of the issue. What should I do?

**Comment by abattery** [comment] 2020-09-02 21:07
@evyasonov please check out the comment in the above thread. :-) https://github.com/tensorflow/text/issues/160#issuecomment-685967575

**Comment by kafji** [comment] 2020-09-05 05:16
Hi. I'm facing the same issue.

I tried using the from_saved_model with tf-nightly as @abattery suggested but I got error:
`'tf.MutableHashTableV2' op is neither a custom op nor a flex op`.

Here is the link to the Colab: https://colab.research.google.com/drive/1IU6dLDkxxOzMHKKqi5_WQgShDL3K-_69

**Comment by Liu-Da** [comment] 2020-09-21 02:47
> Could you try the conversion with from_saved_model within tf-nightly version? You can avoid the above error through the from_saved_model with tf-nightly version.

This worked for me. Thanks.
Hope the new official version can be released soon.

**Comment by evyasonov** [comment] 2020-10-12 08:01
> Could you try the conversion with from_saved_model within tf-nightly version? You can avoid the above error through the from_saved_model with tf-nightly version.

@abattery 
I've finally built and installed tf-nightly and tf-text on my laptop and I've succeed to import both nightly and text.
And I've saved model and loaded it via `tf.lite.TFLiteConverter.from_saved_model(...)`.
BUT when I called `.convert()`, I've got this error:
```
WARNING:tensorflow:8 out of the last 8 calls to <function recreate_function.<locals>.restored_function_body at 0x7f04a85a3ae8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 9 calls to <function recreate_function.<locals>.restored_function_body at 0x7f04a85571e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/.virtualenvs/python3Tf/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    211                                                  debug_info_str,
--> 212                                                  enable_mlir_converter)
    213       return model_str

~/.virtualenvs/python3Tf/lib/python3.6/site-packages/tensorflow/lite/python/wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     37       debug_info_str,
---> 38       enable_mlir_converter)
     39 

Exception: <unknown>:0: error: loc("string_lookup_index_table"): 'tf.MutableHashTableV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringLower@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringLower' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StaticRegexReplace@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StaticRegexReplace' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/StringSplitV2@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringSplitV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/RaggedFromValueRowIds/RowPartitionFromValueRowIds/bincount/Bincount@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Bincount' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/RaggedFromValueRowIds/RowPartitionFromValueRowIds/Cumsum@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Cumsum' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringNGrams/StringNGrams@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringNGrams' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/category_encoding/RaggedReduceSum/RaggedSplitsToSegmentIds/range@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Range' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/string_lookup/string_lookup_index_table_lookup_table_find/LookupTableFindV2@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.LookupTableFindV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/category_encoding/RaggedReduceSum/UnsortedSegmentSum@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.UnsortedSegmentSum' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Bincount {T = i64, device = ""}
	tf.Cumsum {device = "", exclusive = false, reverse = false}
	tf.Range {device = ""}
	tf.StaticRegexReplace {device = "", pattern = "[!\22#$%&()\\*\\+,-\\./:;<=>?@\\[\\\\\\]^_`{|}~\\']", replace_global = true, rewrite = ""}
	tf.StringLower {device = "", encoding = ""}
	tf.StringSplitV2 {device = "", maxsplit = -1 : i64}
	tf.UnsortedSegmentSum {device = ""}Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.LookupTableFindV2 {device = "/job:localhost/replica:0/task:0/device:CPU:0"}
	tf.MutableHashTableV2 {container = "", device = "", key_dtype = !tf.string, shared_name = "table_72", use_node_name_sharing = false, value_dtype = i64}
	tf.StringNGrams {Tsplits = i64, device = "", left_pad = "", ngram_widths = [1, 2], pad_width = 0 : i64, preserve_short_sequences = false, right_pad = "", separator = " "}


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
<ipython-input-12-be72feb906f0> in <module>
      1 converter   = tf.lite.TFLiteConverter.from_saved_model('cannot_convert_model')
      2 
----> 3 tfliteModel = converter.convert()

~/.virtualenvs/python3Tf/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self)
    756     converter_kwargs.update(quant_mode.converter_flags())
    757 
--> 758     result = _convert_saved_model(**converter_kwargs)
    759     calibrate_and_quantize, flags = quant_mode.quantizer_flags(
    760         self.inference_input_type, self.inference_output_type)

~/.virtualenvs/python3Tf/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in convert_saved_model(saved_model_dir, saved_model_version, saved_model_tags, saved_model_exported_names, **kwargs)
    634       None,  # input_data, unused
    635       None,  # debug_info_str, unused
--> 636       enable_mlir_converter=True)
    637   return data
    638 

~/.virtualenvs/python3Tf/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    213       return model_str
    214     except Exception as e:
--> 215       raise ConverterError(str(e))
    216 
    217   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("string_lookup_index_table"): 'tf.MutableHashTableV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringLower@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringLower' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StaticRegexReplace@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StaticRegexReplace' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/StringSplitV2@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringSplitV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/RaggedFromValueRowIds/RowPartitionFromValueRowIds/bincount/Bincount@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Bincount' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringSplit/RaggedFromValueRowIds/RowPartitionFromValueRowIds/Cumsum@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Cumsum' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/StringNGrams/StringNGrams@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.StringNGrams' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/category_encoding/RaggedReduceSum/RaggedSplitsToSegmentIds/range@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.Range' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/string_lookup/string_lookup_index_table_lookup_table_find/LookupTableFindV2@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.LookupTableFindV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/text_vectorization/category_encoding/RaggedReduceSum/UnsortedSegmentSum@__inference__wrapped_model_6417" at "StatefulPartitionedCall@__inference_signature_wrapper_7583") at "StatefulPartitionedCall")): 'tf.UnsortedSegmentSum' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Bincount {T = i64, device = ""}
	tf.Cumsum {device = "", exclusive = false, reverse = false}
	tf.Range {device = ""}
	tf.StaticRegexReplace {device = "", pattern = "[!\22#$%&()\\*\\+,-\\./:;<=>?@\\[\\\\\\]^_`{|}~\\']", replace_global = true, rewrite = ""}
	tf.StringLower {device = "", encoding = ""}
	tf.StringSplitV2 {device = "", maxsplit = -1 : i64}
	tf.UnsortedSegmentSum {device = ""}Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.LookupTableFindV2 {device = "/job:localhost/replica:0/task:0/device:CPU:0"}
	tf.MutableHashTableV2 {container = "", device = "", key_dtype = !tf.string, shared_name = "table_72", use_node_name_sharing = false, value_dtype = i64}
	tf.StringNGrams {Tsplits = i64, device = "", left_pad = "", ngram_widths = [1, 2], pad_width = 0 : i64, preserve_short_sequences = false, right_pad = "", separator = " "}
```

So `from_saved_model` don't work for this case.
I uploaded my notebook to this colab: https://colab.research.google.com/drive/16650qRDj2_I1RRAd5nCHfEcWjuzNPOYs?usp=sharing

Can you please help me to save my model to tflite format
What I should do?

**Comment by evyasonov** [comment] 2020-10-19 13:08
@abattery @jvishnuvardhan 
Any update?

**Comment by karimnosseir** [comment] 2020-10-23 00:23
@evyasonov The last failure is because the model have operations that TFLite doesn't support natively.
For Hashtable support, we are working on supporting this. Generally for other operations you can use SELECT mode which fallbacks to TF during the runtime with some cost.
See https://www.tensorflow.org/lite/guide/ops_select

**Comment by abattery** [comment] 2020-10-23 02:41
Sorry for experiencing this. TFLite currently can not support the TextVectorization keras layer right now. We are working with TensorFlow keras team to fix this.

**Comment by evyasonov** [comment] 2020-10-23 08:41
@karimnosseir @abattery 
Got it! Thank you for the answers!
Do you have any estimation of when TextVectorization will be supported by TFLite?

**Comment by brlambert7818** [comment] 2020-11-06 20:11
@evyasonov TextVectorization still doesn't seem to be working yet with TFLite. Have you received any updates on when it will be supported?

**Comment by NLPpupil** [comment] 2020-11-11 09:07
> Sorry for experiencing this. TFLite currently can not support the TextVectorization keras layer right now. We are working with TensorFlow keras team to fix this.

So TFLite can not support tensorflow_text.BertTokenizer either?

**Comment by abattery** [comment] 2020-11-11 12:29
tensorflow_text.BertTokenizer is not using a mutable hash table but a combination of static hash table and wordpiece tokenizer. This layer can be supported in TFLite soon with hash table support feature and Select TF ops with the tensorflow_text op.

(1) You can add hash table custom ops (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/kernels/hashtable) and
(2) you can link interpreter and convert with tensorflow_text project for adding wordpiece tokenizer support.

@thaink can you help this on using wordpiece tokenizer?

**Comment by thaink** [comment] 2020-11-13 02:48
To use WordPiece tokenizer, you can do one of following things:
1. Add the //tensorflow/lite/delegate/flex:delegate dependency to your target and then add @org_tensorflow_text//tensorflow_text:ops_lib dependency.
2. Build a custom flex delegate with @org_tensorflow_text//tensorflow_text:ops_lib in additional_deps field. Following the rule here:
https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/custom_ops/BUILD#L10
I would recommend to take a look at above tflite-support example. It is a good start.

**Comment by zhaohb** [comment] 2021-01-11 09:53
@abattery now I have the same problem, II tested my code with TF 2.2 and TF-nightly 2.5, but encountered the same problem.

 
`frozen_func = convert_variables_to_constants_v2(full_model)
 frozen_func.graph.as_graph_def()`

Can you give me some advice， thank you very much！

**Comment by abattery** [comment] 2021-01-11 10:00
We do not have a plan to support resource type freezing through the `convert_variables_to_constants_v2` method. If you are converting the given model to TFLite, please use `TFLiteConverter.from_saved_model` in TF v2.

**Comment by zhaohb** [comment] 2021-01-11 10:08
But if I want to use resource type freezing , I want to implement it myself, can I have some suggestions?

**Comment by digital-thinking** [comment] 2021-04-28 12:05
I have the same Problem, when using a simple custom layer in keras, using convert_variables_to_constants_v2 in combination with tf.lookup.StaticHashTable. tf2.4 (worked in 2.2)....

**Comment by abattery** [comment] 2021-04-28 12:11
@digital-thinking could you file a new issue with the reproducible steps? It is hard to track multiple stuffs at a single thread.

**Comment by abattery** [comment] 2021-04-28 12:13
Closing this issue since we have a solution with the TF v2 saved model converter API.

**Closed by abattery** 2021-04-28 12:13 UTC
Labels: TF 2.3, TFLiteConverter, type:feature

**Comment by abattery** [comment] 2021-04-28 12:26
FYI, TextVectorization keras layer does work with TFLite converter if you can export it to the TF v1 saved model with the hash table initializer.

```
  # Disable eager execution to export v1 saved model.
  tf.compat.v1.disable_eager_execution()

  text_dataset = tf.data.Dataset.from_tensor_slices(["foo", "bar", "baz"])
  max_features = 5000  # Maximum vocab size.
  max_len = 4  # Sequence length to pad the outputs to.
  embedding_dims = 2

  # Create the layer.
  vectorize_layer = tf.keras.layers.experimental.preprocessing.TextVectorization(
      max_tokens=max_features,
      output_mode="int",
      output_sequence_length=max_len,
      vocabulary=["foo", "bar", "baz"])

  # Create the model that uses the vectorize text layer
  model = tf.keras.models.Sequential()

  # Start by creating an explicit input layer. It needs to have a shape of
  # (1,) (because we need to guarantee that there is exactly one string
  # input per batch), and the dtype needs to be 'string'.
  model.add(tf.keras.Input(shape=(1,), dtype=tf.string))

  # The first layer in our model is the vectorization layer. After this
  # layer, we have a tensor of shape (batch_size, max_len) containing vocab
  # indices.
  model.add(vectorize_layer)

  # Now, the model can map strings to integers, and you can add an embedding
  # layer to map these integers to learned embeddings.
  input_data = [["foo qux bar"], ["qux baz"]]
  model.predict(input_data)

  x = tf.compat.v1.placeholder(tf.string, shape=([None, None]), name="input")
  y = model.call(x)

  tensor_info_x = tf.compat.v1.saved_model.utils.build_tensor_info(x)
  tensor_info_y = tf.compat.v1.saved_model.utils.build_tensor_info(y)

  signature_def_map, init_op, assets_collection = {
      "serving_default":
          (tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
              inputs={"x": tensor_info_x},
              outputs={"y": tensor_info_y},
              method_name="some_function"))
  }, tf.compat.v1.tables_initializer(), None

  lookup = vectorize_layer._index_lookup_layer._table_handler.table._resource_handle

  import tensorflow.pythons.ops import lookup_ops
  init_op = tf.group(
      lookup_ops.lookup_table_insert_v2(lookup, ["foo", "bar", "baz"],
                                        tf.constant([0, 1, 2], dtype=tf.int64)))
 
  saved_model_dir = "/tmp/textvec"

  sess = tf.compat.v1.Session()
  sess.run(tf.compat.v1.initializers.global_variables())
  builder = tf.compat.v1.saved_model.builder.SavedModelBuilder(saved_model_dir)
  builder.add_meta_graph_and_variables(
      sess, [tf.compat.v1.saved_model.tag_constants.SERVING],
      signature_def_map,
      main_op=init_op,
      legacy_init_op=init_op,
      assets_collection=assets_collection,
      strip_default_attrs=True)
  builder.save()
```

And then, it needs to re-enable the eager execution (simply, you can just have another Python script for conversion only) and converts the generated saved model with the TF v2 saved model converter:

```
  saved_model_dir = "/tmp/textvec"
  converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
  converter.target_spec.supported_ops.add(tf.lite.OpsSet.SELECT_TF_OPS)
  tflite_model = converter.convert()
```

**Comment by hanzigs** [comment] 2021-06-01 06:32
Hi,
I am getting same issue in AutoKeras convertion to onnx, Is there any help https://github.com/onnx/keras-onnx/issues/647
Thanks

**Comment by abattery** [comment] 2021-06-01 06:42
@hanzigs please upload a new post for your issue. Fyi, resource types are supported through only saved model converter since TF 2.5.

**Comment by hanzigs** [comment] 2021-06-01 06:43
@abattery Sure Thanks

**Comment by shuangpe** [comment] 2022-08-17 05:37
[https://github.com/tensorflow/tensorflow/issues/42673#issuecomment-828412232](url)

@abattery, the code that converts keras model to tf v1 saved model format reports error on TF2.9.1.
could you provide an updated version of the conversion code? Thx!
