### ISSUE TITLE
TPU issue using Colab - NotFoundError: 'AnonymousSeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-c0cd0e2d-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:TakeDataset]

### ISSUE THREAD

**Issue by dipoojo55** [tensorflow/tensorflow#39550] opened 2020-05-14 17:30 UTC
**System information**
Pip installed TensorFlow 
TensorFlow version (use command below): tf-nightly/ 2.2.0-dev20200502
Python version: 3.6.9

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to run my model I get a NotFoundError when getting my dataset. The code works with a GPU but does not work with TPU.  I was previously getting a NotFoundError that had to do with PyFunc.

**Describe the expected behavior**
Epochs should run and give a result.

**Standalone code to reproduce the issue**
```
import requests
import os
url = 'http://' + os.environ['COLAB_TPU_ADDR'].split(':')[0] + ':8475/requestversion/2.2.0-dev20200312'
resp = requests.post(url)
print(resp)
%pip install tf-nightly==2.2.0-dev20200505
```

```
import tensorflow as tf
from tensorflow.keras import backend as K
import os
import PIL
import csv
import shutil
import numpy as np
import sys
from PIL import Image
from tensorflow.keras import backend as K
import gc

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers
from tensorflow.keras import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3
# from tensorflow.keras.applications.inception_resnet_v2 import InceptionResNetV2

from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

#*********************** tried this first ***************************************
# resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
# tf.config.experimental_connect_to_cluster(resolver)
# # This is the TPU initialization code that has to be at the beginning.
# tf.tpu.experimental.initialize_tpu_system(resolver)
# strategy = tf.distribute.experimental.TPUStrategy(resolver)
#********************************************************************************

tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
strategy = tf.distribute.experimental.TPUStrategy(tpu)

print("REPLICAS: ", strategy.num_replicas_in_sync)


from PIL import Image
print(Image.__file__)

# import Image
print(Image.__file__)
```

#clone and mount drives as needed

```
def make_generator():

    train_datagen = ImageDataGenerator(rescale=1/255, horizontal_flip=True, rotation_range=90)
    
    train_generator = train_datagen.flow_from_directory(
        '/content/plant-path/tfdir/train/',  # This is the source directory for training images
        target_size=(400, 400),  # All images will be resized to 150x150
        batch_size=1, 
        
        class_mode='sparse')
    

    return train_generator

def create_model():
         pre_trained_model = InceptionV3(input_shape = (400, 400,3), include_top = False, weights = 'imagenet')

# pre_trained_model = InceptionResNetV2(include_top=False, weights='imagenet', input_tensor=None, input_shape=(1024, 1024,3))

         for layer in pre_trained_model.layers:
                    if layer.name == 'mixed1':
                                    break
# #     print(layer.name)
                    layer.trainable = False

                    last_layer = pre_trained_model.get_layer('mixed7')
                    last_output = last_layer.output

         from tensorflow.keras.optimizers import RMSprop
         from tensorflow.keras import regularizers
 

         x = Flatten()(last_output)
         x = layers.Dense(1024,  activation= 'relu')(x)
         x = layers.Dropout(.2)(x)
         x = layers.Dense(4, activation= 'softmax')(x)
         modelin = Model(pre_trained_model.input, x)
         return modelin



def get_callbacks(name_weights, patience_lr):
    mcp_save = ModelCheckpoint(name_weights, save_best_only=True, monitor='val_acc', mode='max')
#     reduce_lr_loss = ReduceLROnPlateau(monitor='loss', factor=0.1, patience=patience_lr, verbose=1, epsilon=1e-4, mode='min')
    return [mcp_save] #, reduce_lr_loss]


batch_size = 456
def scale(image, label):
    image = tf.squeeze(image)
    return image, label  

def get_dataset(i, batchsize = batch_size):
  dataset = tf.data.Dataset.from_generator(make_generator, (tf.float32, tf.float32),
     (tf.TensorShape([400, 400, 3]), tf.TensorShape([None])))
  dataset = dataset.shuffle(buffer_size = 2280)  
  dataset = dataset.cache()
  val = dataset.skip(i*456).take(456).batch(batch_size, drop_remainder=True).prefetch(4)
  
  train = dataset.skip(i*456+456).take(1824).concatenate(dataset.take(456*i)).batch(batch_size, drop_remainder=True).prefetch(15)
  return train, val
```

#K-fold algo

```
for i in range(5):
  
  #********* this was created to trouble shoot but did not resolve issue
  # dataset = tf.data.Dataset.from_generator(make_generator, (tf.float32, tf.float32),
  #    (tf.TensorShape([1, 400, 400, 3]), tf.TensorShape([None])))
  # dataset = dataset.shuffle(buffer_size = 2280)
    
    # val = dataset.skip(i*456).take(456).batch(batch_size, drop_remainder=True).prefetch(4)
  
    # train = dataset.skip(i*456+456).take(1824).concatenate(dataset.take(456*i)).batch(batch_size, drop_remainder=True).prefetch(15)  

  #******************************************************  
    
    train, val = get_dataset(i) 
    
    name_weights = "/content/drive/My Drive/Plant/final_model_fold_D512_I400_mix_1_7_" + str(i) + ".{epoch:02d}-{val_acc:.2f}.h5"
    callbacks = get_callbacks(name_weights = name_weights, patience_lr=10)

    
    with strategy.scope():
       modelinc = create_model()
       modelinc.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['acc'])

    modelinc.fit(
                dataset,
                # batch_size = batch_size,
                # steps_per_epoch=1824/batch_size,
                epochs=25,
                # shuffle=True,
                # verbose=1,
                # validation_data = val
                 ) #,
                #  callbacks = callbacks)
    
    print(modelinc.evaluate(val)) 
    K.clear_session()
    
    del name_weights
    del callbacks

    gc.collect()
```

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-7-4b2615ce6f75> in <module>()
     15   #******************************************************
     16 
---> 17     train, val = get_dataset(i)
     18 
     19     name_weights = "/content/drive/My Drive/Plant/final_model_fold_D512_I400_mix_1_7_" + str(i) + ".{epoch:02d}-{val_acc:.2f}.h5"

5 frames
<ipython-input-6-c4546546e618> in get_dataset(i, batchsize)
     56   dataset = dataset.shuffle(buffer_size = 2280)
     57   dataset = dataset.cache()
---> 58   val = dataset.skip(i*456).take(456).batch(batch_size, drop_remainder=True).prefetch(4)
     59 
     60   train = dataset.skip(i*456+456).take(1824).concatenate(dataset.take(456*i)).batch(batch_size, drop_remainder=True).prefetch(15)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py in take(self, count)
   1271       Dataset: A `Dataset`.
   1272     """
-> 1273     return TakeDataset(self, count)
   1274 
   1275   def skip(self, count):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py in __init__(self, input_dataset, count)
   3727         input_dataset._variant_tensor,  # pylint: disable=protected-access
   3728         count=self._count,
-> 3729         **self._flat_structure)
   3730     super(TakeDataset, self).__init__(input_dataset, variant_tensor)
   3731 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py in take_dataset(input_dataset, count, output_types, output_shapes, name)
   6474       return _result
   6475     except _core._NotOkStatusException as e:
-> 6476       _ops.raise_from_not_ok_status(e, name)
   6477     except _core._FallbackException:
   6478       pass

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6810   message = e.message + (" name: " + name if name is not None else "")
   6811   # pylint: disable=protected-access
-> 6812   six.raise_from(core._status_to_exception(e.code, message), None)
   6813   # pylint: enable=protected-access
   6814 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

NotFoundError: 'AnonymousSeedGenerator' is neither a type of a primitive operation nor a name of a function registered in binary running on n-c0cd0e2d-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:TakeDataset]

**Comment by dipoojo55** [comment] 2020-05-14 18:06
At modelinc.fit please change dataset to train 
thanks!

**Comment by Saduf2019** [comment] 2020-05-15 10:22
@dipoojo55 
I ran the code shared and i am able to replicate the issue faced please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/da63b63985f128aeb1c984581ff5c257/untitled181.ipynb)

**Comment by sayakpaul** [comment] 2021-02-03 02:56
Any update on this issue? Facing it in an AI Platform Notebook plugged to Cloud TPU v3-8.

**Comment by rxsang** [comment] 2021-03-26 18:43
This is due to the coordinator and TPU worker version don't match. Make sure they both use the same TF version or nightly instance.

**Comment by jvishnuvardhan** [comment] 2021-04-12 16:10
@sayakpaul Can you please check whether the issue is persisting even after matching TF versions as suggested by @rxsang . 

Please close the issue if this was already resolved after matching the versions. Thanks!

**Comment by sayakpaul** [comment] 2021-04-12 16:12
@jvishnuvardhan at least check who has opened the issue and then post your suggestions :D

How can a non-member close an issue that they haven't created?

**Comment by jvishnuvardhan** [comment] 2021-04-12 16:34
@sayakpaul Sorry for the last comment. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-04-12 17:20
@dipoojo55 Is this still an issue for you? I tried running your code but facing different error (could be due to data that I cannot access). [Here is a gist](https://colab.research.google.com/gist/jvishnuvardhan/f568d9ce7a6f1d9cc70bbb09a7be9fe9/untitled181.ipynb) for reference.  

Can you please run the code yourself or share a standalone code and data to reproduce the issue. Thanks!

**Comment by dails08** [comment] 2021-04-21 16:28
I'm having a similar NotFoundError issue with the ComputeBatchSize op.  @rxsang , can you elaborate on how to make sure the coordinator and worker have the same tf version?

**Comment by rxsang** [comment] 2021-04-23 16:06
Yes, you are right. Thanks for the confirmation @dails08

**Closed by rxsang** 2021-04-23 16:06 UTC
Labels: TF 2.2, comp:tpus, stalled, stat:awaiting response, type:bug
