### ISSUE TITLE
outputs indifferent to input when applying `merge_duplicate_nodes`

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#8897] opened 2017-04-01 17:19 UTC
I think I might have located the root of #8698
It seems that `merge_duplicate_nodes` is the reason that `quantize_nodes` malfunctions.
Whatever I do, whenever I apply a `merge_duplicate_nodes` somewhere during a graph transformation, the output becomes completely indifferent to the input.

(Unfortunately) I don't get any error messages concerning this...

**Comment by aselle** [comment] 2017-04-01 22:18
@petewarden , could you please take a look. Thanks so much.

**Comment by Androbin** [comment] 2017-04-02 13:35
Variants of this problem include zero values at intermediate layers.
So the input won't make it past there, which results in other constant output.

**Comment by Androbin** [comment] 2017-04-08 18:45
I should probably mention that it makes inference a lot faster ...
Unfortunately, faster doesn't always mean better ...
How could `merge_duplicate_nodes` possibly eliminate all of these computations?

**Comment by andrehentz** [comment] 2017-04-18 22:35
@Androbin, could you confirm that replacing `deduped_graph_def` with `merged_graph_def` in 
[quantize_nodes.cc line 942](https://github.com/tensorflow/tensorflow/blob/a667a52ee909975389e48ffe30fb4ff9570635da/tensorflow/tools/graph_transforms/quantize_nodes.cc#L942) causes the problem to go away?

**Comment by Androbin** [comment] 2017-04-18 22:38
@andrehentz I will triple-check that and post the results here!

**Comment by Androbin** [comment] 2017-04-18 23:34
As mentioned, this bug does also step in place when `merge_duplicate_nodes` is used without `quantize_nodes`.

**Comment by Androbin** [comment] 2017-04-19 15:32
And I should probably mention that I am doing the inference on Android.
Unfortunately, I am currently unable to test this on Ubuntu because the original graph, from which the quantized version is derivated, is currently broken due to another issue.

**Comment by andrehentz** [comment] 2017-04-19 21:50
@Androbin 
I found an issue with dequantization on Android and I'm wondering if building with 
   `-DTENSORFLOW_DISABLE_META` 
works for you. I'd appreciate if you would try it out. Thanks in advance!

**Comment by Androbin** [comment] 2017-04-19 23:50
@andrehentz 
Thanks for the hint!
So, is this issue bounded to the `transform_graph` tool?
Or do I have to recompile the whole library?

**Comment by Androbin** [comment] 2017-04-20 10:54
Wait, do you want me to build with the `-DTENSORFLOW_DISABLE_META` flag AND the previous fix or should I revert it?

**Comment by Androbin** [comment] 2017-04-20 12:51
This was my first attempt to do the Android build myself.
Either I have done something (???) wrong,
or there is an issue with the flag @andrehentz provided.

```
ERROR: /home/androbin/.cache/bazel/_bazel_androbin/0614ddb178f91f25438b47fee5f001b7/external/protobuf/BUILD:73:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: false failed: error executing command /bin/false -MD -MF bazel-out/stub_armeabi-v7a-py3-opt/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/io/coded_stream.pic.d ... (remaining 26 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

```
ERROR: /home/androbin/.cache/bazel/_bazel_androbin/0614ddb178f91f25438b47fee5f001b7/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: false failed: error executing command 
  (cd /home/androbin/.cache/bazel/_bazel_androbin/0614ddb178f91f25438b47fee5f001b7/execroot/tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=5.0 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  /bin/false -MD -MF bazel-out/stub_armeabi-v7a-py3-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/io/zero_copy_stream_impl.pic.d '-frandom-seed=bazel-out/stub_armeabi-v7a-py3-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/io/zero_copy_stream_impl.pic.o' -fPIC -iquote external/protobuf -iquote bazel-out/stub_armeabi-v7a-py3-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/stub_armeabi-v7a-py3-opt/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/stub_armeabi-v7a-py3-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -c external/protobuf/src/google/protobuf/io/zero_copy_stream_impl.cc -o bazel-out/stub_armeabi-v7a-py3-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/io/zero_copy_stream_impl.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
```

I can provide further logs as necessary.

**Comment by andrehentz** [comment] 2017-04-20 16:14
The following should work:
`bazel build -c opt --copt="-DTENSORFLOW_DISABLE_META" //tensorflow/contrib/android:libtensorflow_inference.so --config=android_arm`

But if you are OK waiting, we should have a fix for quantization in the nightly by the end of next week. I'm not sure it will fix this particular problem you are experiencing, though.

Meanwhile, could you perhaps provide steps for reproducing the failures you are seeing with `merge_duplicate_nodes`? Did you retrain an inception model?

**Comment by Androbin** [comment] 2017-04-20 16:24
@andrehentz 
Thanks, this should work now.
Happy to hear about a fix in sight.

In my particular case, I didn't use a prepared model but a custom one in the scope of a research project.
I can provide the structure of the graph, if this was helpful.
Anyway, currently any graph transform containing a `merge_duplicate_nodes` e.g. `quantize_nodes` causes this issue with my model.

**Comment by andrehentz** [comment] 2017-04-20 17:45
I'd be curious to know which nodes are removed when you run transform_graph with 
  `--transforms='merge_duplicate_nodes'`
from reading the code I understand only nodes that have the same op, inputs and attributes (by the way of a hash function) are removed.

**Comment by Androbin** [comment] 2017-04-20 17:49
@andrehentz 
I will inspect this and list anything unusual here!

**Comment by Androbin** [comment] 2017-04-20 18:42
@andrehentz 
Meanwhile, which ABI does `--config=android_arm` resolve to?

**Comment by andrehentz** [comment] 2017-04-20 18:47
armeabi-v7a (but I think any of the ones you mentioned should be fine)

**Comment by Androbin** [comment] 2017-06-08 21:10
I tried recompiling and running computing a diff but since the output of `transform_graph` is binary, I wasn't able to extract, exactly which nodes are removed.

**Comment by kwotsin** [comment] 2017-07-03 07:09
@Androbin Did the new bazel build for `libtensorflow_inference.so` work for you?

**Comment by Androbin** [comment] 2017-07-05 12:16
@kwotsin I will recompile, retrain and requantize and comment the results as soon as I have them.

**Comment by Androbin** [comment] 2017-07-05 19:11
I might need some time though, there are currently some issues with building the inference library.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:46
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:12
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:13
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Closed** 2018-01-24 14:57 UTC
Labels: type:bug/performance
