### ISSUE TITLE
AttributeError: module 'tensorflow.python.training.training' has no attribute 'SummaryWriter'

### ISSUE THREAD

**Issue by FeiWard** [tensorflow/tensorflow#8164] opened 2017-03-07 09:40 UTC
When I use tensorboard，return this error。
AttributeError: module 'tensorflow.python.training.training' has no attribute 'SummaryWriter'

**Comment by MicaelCarvalho** [comment] 2017-03-07 13:12
SummaryWriter has changed in TensorFlow 1.0. You can use `tf.summary.FileWriter`

**Comment by Kamatio** [comment] 2017-03-09 05:19
Hello, I have got the related error while training the NN with Tensorflow, any help? Thanks!

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-10bb478fe634> in <module>()
      loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(yPredbyNN, Y))
---->optimizer = tf.train.AdamOptimiizer().minimize(loss)
      CorrectPred = tf.equal(tf.argmax(yPredbyNN,1), tf.argmax(Y,1))
AttributeError: module 'tensorflow.python.training.training' has no attribute 'AdamOptimiizer'

**Comment by MicaelCarvalho** [comment] 2017-03-09 13:07
@Kamatio I don't see how the problem is related. But are you correctly importing TensorFlow with `import tensorflow as tf`? Furthermore, check which version you're using; it's possible you have something very old installed.

**Comment by asimshankar** [comment] 2017-04-05 01:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-05 01:37 UTC
Labels: stat:awaiting response

**Comment by anjanakumar** [comment] 2017-04-26 03:20
I have the same issue when I try to run my code with tensorflow
AttributeError: module 'tensorflow.python.training.training' has no attribute 'AdagradDAOptimizer'

**Comment by saria85** [comment] 2017-04-29 22:11
hi,,
I am getting this error :
train_writer = tf.train.summary.FileWriter(summaries_dir + '/train')
AttributeError: module 'tensorflow.python.training.training' has no attribute 'summary'

my code is this
train_writer = tf.train.summary.FileWriter(summaries_dir + '/train')

whats the problem, 
It was at first summarywriter but I changed that to summary.filewriter still getting this error

**Comment by MicaelCarvalho** [comment] 2017-04-30 08:31
@saria85 the correct name is `tf.summary.FileWriter`. All problems reported in this thread seem to be solvable with a simple google search.

**Comment by rahuliamsarkar** [comment] 2018-03-09 07:03
@Techlucy  please verify the spelling it might cause the issue 
thanks

**Comment by matiji66** [comment] 2018-04-01 09:51
yes， `writer = tf.summary.FileWriter(log_dir, sess.graph) ` solve my problem.

**Comment by KirosG** [comment] 2018-06-08 15:42
AttributeError                            Traceback (most recent call last)
<ipython-input-24-a8333a92c1ae> in <module>()
----> 1 saver=tf.train.saver()

AttributeError: module 'tensorflow.tools.api.generator.api.train' has no attribute 'saver'

**Comment by MicaelCarvalho** [comment] 2018-06-08 15:49
@KirosG, it's a class, so you have to correctly use the casing. Saver, with an uppercase S: `saver=tf.train.Saver()`
