### ISSUE TITLE
Compatibility with Python 3.12.0

### ISSUE THREAD

**Issue by gitteral** [tensorflow/tensorflow#62049] opened 2023-10-04 14:32 UTC
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tensorflow 2.14.0

### Custom code

No

### OS platform and distribution

Mac OS

### Python version

3.12.0

### Current behavior?

Python 3.12.0 is now available. I tried to pip install TensorFlow 2.14.0. The attempt failed as TF is only compatible with Python 3.11 at most at the moment.

When will a version of TensorFlow be available for the latest Python?  

Thanks.

### Standalone code to reproduce the issue

```shell
Terminal output:

(venv) ## my user ## % pip install tensorflow==2.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.14.0 (from versions: none)
```

**Comment by mihaimaruseac** [comment] 2023-10-04 18:06
Duplicate of #62003

**Closed by mihaimaruseac** 2023-10-04 18:06 UTC
Labels: type:build/install
