### ISSUE TITLE
libcusolver.so.10? 

### ISSUE THREAD

**Issue by SchrodingerZhu** [tensorflow/tensorflow#45263] opened 2020-11-30 09:40 UTC
```
coreClock: 1.755GHz coreCount: 68 deviceMemorySize: 10.74GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-30 17:36:59.367782: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-11-30 17:36:59.369653: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-11-30 17:36:59.369702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-11-30 17:36:59.370388: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-11-30 17:36:59.370548: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-11-30 17:36:59.370610: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-11-30 17:36:59.371080: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-11-30 17:36:59.371185: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-11-30 17:36:59.371200: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-11-30 17:36:59.475119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-30 17:36:59.475153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]      0 
2020-11-30 17:36:59.475162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1286] 0:   N 
```

but we should have
```
libcusolverMg.so.11 (libc6,x86-64) => /opt/cuda/lib64/libcusolverMg.so.11
libcusolverMg.so (libc6,x86-64) => /opt/cuda/lib64/libcusolverMg.so
libcusolver.so.11 (libc6,x86-64) => /opt/cuda/lib64/libcusolver.so.11
libcusolver.so (libc6,x86-64) => /opt/cuda/lib64/libcusolver.so
```

**Comment by Saduf2019** [comment] 2020-11-30 10:18
@SchrodingerZhu 
You will need to add cuda, cudnn, cupti to the environment path.
See https://www.tensorflow.org/install/gpu#linux_setup

**Comment by SchrodingerZhu** [comment] 2020-12-01 06:01
But this should already in my ld conf.
```
🕙[ 13:55:52 ] λ cat /etc/ld.so.conf.d/*.conf
/opt/cuda/lib64
/opt/cuda/nvvm/lib64
/opt/cuda/extras/CUPTI/lib64
/usr/lib/libfakeroot
/opt/intel/mkl/lib/intel64
/opt/intel/mkl/lib/intel64_lin
/opt/intel/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin
/usr/lib32
/usr/lib/octave/5.2.0
/usr/lib/openmpi
```
Moreover,
```
🕙[ 13:57:31 ] λ env LD_LIBRARY_PATH=/opt/cuda/lib64/ python3
Python 3.8.6 (default, Nov 28 2020, 13:43:41) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-12-01 13:58:03.056049: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> tf.test.
tf.test.Benchmark(                  tf.test.create_local_cluster(       tf.test.is_built_with_xla(
tf.test.TestCase(                   tf.test.gpu_device_name(            tf.test.is_gpu_available(
tf.test.assert_equal_graph_def(     tf.test.is_built_with_cuda(         tf.test.main(
tf.test.benchmark_config(           tf.test.is_built_with_gpu_support(  
tf.test.compute_gradient(           tf.test.is_built_with_rocm(         
>>> tf.test.gpu_device_name()
2020-12-01 13:58:15.539168: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-01 13:58:15.541897: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-01 13:58:15.557986: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-01 13:58:15.638215: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 13:58:15.638675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1727] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.755GHz coreCount: 68 deviceMemorySize: 10.74GiB deviceMemoryBandwidth: 573.69GiB/s
2020-12-01 13:58:15.638691: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-01 13:58:15.673486: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-12-01 13:58:15.673575: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-12-01 13:58:15.683915: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-12-01 13:58:15.707195: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-12-01 13:58:15.707289: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/cuda/lib64/
2020-12-01 13:58:15.723204: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-12-01 13:58:15.723901: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-12-01 13:58:15.723916: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1764] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-12-01 13:58:15.797186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-01 13:58:15.797211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1273]      0 
2020-12-01 13:58:15.797218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1286] 0:   N 
''"
```

--------
Some new findings:

I am using Arch Linux. I found that the official package delivered in arch's repo (version `2.3.0`) is compatible with `CUDA 11` and `Python 3.9` and using that the device name is detected correctly.

However, in my `pipenv`, I used `Python 3.8` and `tf-nightly(-gpu)` installed from `pypi` but it just failed with the above output.

**Comment by SchrodingerZhu** [comment] 2020-12-01 06:03
In my global env with the versions delivered in Arch Official:
```
Python 3.9.0 (default, Oct  7 2020, 23:09:01) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-12-01 14:02:30.312027: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> tf.test.gpu_device_name()
2020-12-01 14:02:34.584965: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-01 14:02:34.603043: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 4000199999 Hz
2020-12-01 14:02:34.604630: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564b2fe03990 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-01 14:02:34.604659: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-01 14:02:34.606204: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-01 14:02:34.693722: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:34.694203: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564b2fd48890 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-01 14:02:34.694214: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-12-01 14:02:34.703648: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:34.704054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:0a:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.755GHz coreCount: 68 deviceMemorySize: 10.74GiB deviceMemoryBandwidth: 573.69GiB/s
2020-12-01 14:02:34.704083: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-01 14:02:34.705639: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-12-01 14:02:34.706268: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-12-01 14:02:34.706423: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-12-01 14:02:34.740611: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2020-12-01 14:02:34.741244: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-12-01 14:02:34.741347: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-12-01 14:02:34.741437: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:34.741892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:34.742279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-01 14:02:34.742299: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-12-01 14:02:36.464604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-01 14:02:36.464638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-01 14:02:36.464644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-12-01 14:02:36.464835: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:36.465293: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-01 14:02:36.465795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 9728 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:0a:00.0, compute capability: 7.5)
'/device:GPU:0'
```

**Comment by jvishnuvardhan** [comment] 2020-12-06 06:44
@SchrodingerZhu Looks like there is mix of `CUDA8.0`, `CUDA10.0` and `CUDA11.0`.

```
Successfully opened dynamic library libcudart.so.11.0
2020....  Successfully opened dynamic library libcublas.so.11
2020..... Successfully opened dynamic library libcufft.so.10
2020..... Successfully opened dynamic library libcurand.so.10
2020..... Successfully opened dynamic library libcusolver.so.11
2020..... Successfully opened dynamic library libcusparse.so.11
2020.... Successfully opened dynamic library libcudnn.so.8
```

**Comment by SchrodingerZhu** [comment] 2020-12-06 07:33
ops. that maybe the problem. but I am completely rely on the Arch Repo:
```
community/cuda 11.1.1-1 [installed]
community/cudnn 8.0.5.39-1 [installed]
```
Sure enough, there is some libraries ends with `.10`:
```
/opt/cuda/nsight_systems/target-linux-armv8/libcupti-sbsa.so.10.2
/opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.0
/opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.1
/opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.2
/opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.0
/opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.1
/opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.2
/opt/cuda/targets/x86_64-linux/lib/libcufft.so.10
/opt/cuda/targets/x86_64-linux/lib/libcufft.so.10.3.0.105
/opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10
/opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10.3.0.105
/opt/cuda/targets/x86_64-linux/lib/libcurand.so.10
/opt/cuda/targets/x86_64-linux/lib/libcurand.so.10.2.2.105
```
Maybe it is the OS problem?

**Comment by jvishnuvardhan** [comment] 2020-12-09 02:58
@SchrodingerZhu Can you please try to uninstall, restart the system, reinstall and check whether the issue was resolved or not. thanks!

**Comment by appleparan** [comment] 2020-12-14 21:09
It looks like similar to #44312. Even I removed all CUDA 10.1 and 10.2 packages and installs 11.1, I got same error.

I fix this issue by installing `libcusolver10` by `apt` in Ubuntu 20.04, but not sure this is right solution

**Comment by barskern** [comment] 2020-12-17 16:23
I'm also facing this issue, however I doubt I have much to bring to the discussion as I also run ArchLinux and hence the same environment as @SchrodingerZhu. Just "bumping" to show interest.

**Comment by barskern** [comment] 2020-12-17 16:31
> ops. that maybe the problem. but I am completely rely on the Arch Repo:
> 
> ```
> community/cuda 11.1.1-1 [installed]
> community/cudnn 8.0.5.39-1 [installed]
> ```
> 
> Sure enough, there is some libraries ends with `.10`:
> 
> ```
> /opt/cuda/nsight_systems/target-linux-armv8/libcupti-sbsa.so.10.2
> /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.0
> /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.1
> /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.2
> /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.0
> /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.1
> /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.2
> /opt/cuda/targets/x86_64-linux/lib/libcufft.so.10
> /opt/cuda/targets/x86_64-linux/lib/libcufft.so.10.3.0.105
> /opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10
> /opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10.3.0.105
> /opt/cuda/targets/x86_64-linux/lib/libcurand.so.10
> /opt/cuda/targets/x86_64-linux/lib/libcurand.so.10.2.2.105
> ```
> 
> Maybe it is the OS problem?

Just as a FYI, those files are a part of the current `cuda` package, hence they are at least not 'leftover' files from a previous installation (however it might be wrong to include them anyways?).

```
>>> pacman -Ql cuda | rg '\.so\.10'
cuda /opt/cuda/nsight_systems/target-linux-armv8/libcupti-sbsa.so.10.2
cuda /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.0
cuda /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.1
cuda /opt/cuda/nsight_systems/target-linux-armv8/libcupti-tegra.so.10.2
cuda /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.0
cuda /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.1
cuda /opt/cuda/nsight_systems/target-linux-x64/libcupti.so.10.2
cuda /opt/cuda/targets/x86_64-linux/lib/libcufft.so.10
cuda /opt/cuda/targets/x86_64-linux/lib/libcufft.so.10.4.0.72
cuda /opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10
cuda /opt/cuda/targets/x86_64-linux/lib/libcufftw.so.10.4.0.72
cuda /opt/cuda/targets/x86_64-linux/lib/libcurand.so.10
cuda /opt/cuda/targets/x86_64-linux/lib/libcurand.so.10.2.3.68
```

**Comment by xidchen** [comment] 2020-12-21 09:17
I can write confidently to solve this issue.
The issue has two focuses, with the first one being **CUDA components versions**, and the second being **libcusolver.so.10 error**.

**CUDA components versions**
The is some asynchronous relationship between CUDA versions and their components versions.
If you use TensorFlow 2.4, you probably use CUDA 11.0. Check the CUDA 11.0 release document. You can find the following list.

> This release of the toolkit includes the following updates:
> 
> CUDA Math libraries toolchain uses C++11 features, and a C++11-compatible standard library is required on the host.
> cuBLAS 11.0.0
> cuFFT 10.1.3
> cuRAND 10.2.0
> cuSPARSE 11.0.0
> cuSOLVER 10.4.0
> NPP 11.0.0
> nvJPEG 11.0.0

The above list concludes that CUDA 11.0 does contain some components with version 10.
BTW, from CUDA 11.1, you will find cusolver.so version above 11.

**libcusolver.so.10 error**
This is an error caused by the environment variable **LD_LIBRARY_PATH**.
If you use a terminal, you have probably already set the LD_LIBRARY_PATH, with /usr/local/cuda-11.0/lib64 in it.
If you use PyCharm or other IDEs, you need to check environment variables as well.
With environment variables being just the default one: PYTHONUNBUFFERED=1, you will get:
`W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory`
With environment variables being **LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:/usr/local/lib**, you will get:
`I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10`

**Comment by sanjoy** [comment] 2020-12-28 23:54
@xidchen 's assessment is correct.

**Comment by elliotops** [comment] 2020-12-29 00:58
@xidchen is indeed correct.

**Comment by appleparan** [comment] 2020-12-29 03:28
So, this issue can be closed. #44312 also.

**Comment by SchrodingerZhu** [comment] 2020-12-30 08:40
sorry for the delay. I just returned and tested. I think the current discussion is already enough for solving the issue.

**Comment by mihaimaruseac** [comment] 2020-12-30 17:02
Closing as [requested](https://github.com/tensorflow/tensorflow/issues/45263#issuecomment-751933452) Please reopen if it's a mistake

**Closed by mihaimaruseac** 2020-12-30 17:02 UTC
Labels: TF 2.5, comp:gpu, stat:awaiting tensorflower, subtype: ubuntu/linux, type:bug, type:build/install

**Comment by RonDen** [comment] 2021-01-06 16:02
> It looks like similar to #44312. Even I removed all CUDA 10.1 and 10.2 packages and install 11.1, I got same error.
> 
> I fix this issue by installing `libcusolver10` using `apt` in Ubuntu 20.04, but not sure this is right solution

I cannot install libcusolver10 through apt, any idea?

**Comment by rayryeng** [comment] 2021-04-09 02:46
For me, I actually had `libcusolver.so.11` available because I am using CUDA 11.1.  For TensorFlow 2.4.1 (as of this date), still refers to `libcusolver.so.10`.  I solved this by making a symbolic link in my `/usr/local/cuda-11.1/lib64` directory so that version 10 points to version 11:

```
sudo ln -s /usr/local/cuda-11.1/lib64/libcusolver.so.11 /usr/local/cuda-11.1/lib64/libcusolver.so.10
```

**Comment by alealv** [comment] 2021-04-15 18:07
> For me, I actually had `libcusolver.so.11` available because I am using CUDA 11.1. For TensorFlow 2.4.1 (as of this date), it still refers to `libcusolver.so.10`. I solved this by making a symbolic link in my `/usr/local/cuda-11.1/lib64` directory so that version 10 points to version 11:
> 
> ```
> sudo ln -s /usr/local/cuda-11.1/lib64/libcusolver.so.11 /usr/local/cuda-11.1/lib64/libcusolver.so.10
> ```

I also have the same issue with CUDA v11.1. I tried TensorFlow v2.5,0-rc1 and it's working just fine. 
I believe that the problem is that TensorFlow v2.4.1 links only to CUDA 11.0

**Comment by rayryeng** [comment] 2021-04-16 03:08
@alealv that's good to know!

**Comment by brendano257** [comment] 2021-04-30 22:17
I also had a similar experience to @alealv 

After figuring out nvidia driver issues between Arch and Manjaro's preferred nvidia drivers, explicitly upgrading to 2.5.0 rc2 worked for me after making sure to uninstall any previous tensorflow or tensorflow-gpu installations.
