### ISSUE TITLE
resize_image_with_crop_or_pad() on variable image sizes

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#1412] opened 2016-03-07 04:33 UTC
I'm setting up what (I think) should be a straightforward image loading pipeline:

```python
decoded_image = tf.image.decode_jpeg(value)
resized_image = tf.image.resize_image_with_crop_or_pad(decoded_image, width, height)
```

However, I get an error `'image' must be fully defined.` - the image not being fully defined because the size of the JPEG is variable. When using the `tf.image.resize_images()` function, it seems that this constraint is not enforced. Is it necessary to have fixed image dimensions to use the `resize_image_with_crop_or_pad()` function? That would seem to somewhat defeat the point of an auto-crop/resizing function, no?

**Comment by girving** [comment] 2016-03-07 17:11
@shlens: `resize_image_with_crop_or_pad` calls `Check3DImage` with `required_static=True`?  Is there a reason for that?  Fixing it would require changing a few routines to compute height and width via `tf.shape` at runtime rather that at graph construction time.

**Comment by girving** [comment] 2016-03-07 17:13
@shlens: Feel free to remove your name and put contributions welcome if you want.

@zplizzi: I think the only reason for this limitation is that all the existing uses appear as part of a larger image pipeline where the size is known.

**Comment by mrry** [comment] 2016-03-08 15:46
This looks like a duplicate of #521.

**Comment by girving** [comment] 2016-03-08 16:29
Yep, closing.

**Closed by girving** 2016-03-08 16:29 UTC
Labels: enhancement
