### ISSUE TITLE
 SavedModel restored in Graph mode under MirroredStrategy crashes global_variables_initializer

### ISSUE THREAD

**Issue by arnoegw** [tensorflow/tensorflow#47086] opened 2021-02-11 12:28 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux: colab.research.google.com and others
- TensorFlow installed from (source or binary): pre-installed on colab
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9

**Describe the current behavior**

1) `tf.compat.v1.global_variables_initializer()` crashes with `TypeError: Expected tf.group() expected Tensor arguments not 'None'` after restoring a SavedModel in Graph mode under MirroredStrategy as in the code below.

2) Estimator does this kind of initialization automatically when used with `RunConfig(..., train_distribute=MirroredStrategy())`, so just fixing the example below won't help. See https://github.com/tensorflow/hub/issues/704 for user-level impact.

**Describe the expected behavior**

1) `tf.compat.v1.global_variables_initializer()` succeeds in this situation.

2) An Estimator `model_fn` can use `tf.saved_model.load()` without this crash when used with `RunConfig(..., train_distribute=MirroredStrategy())`.

**Standalone code to reproduce the issue**

[Also shared with Alphabet at https://colab.research.google.com/drive/1piVum7WJb_WlYhHbW6tYO7gWSzJeT7oO ]

```python
import tensorflow as tf

class Twice(tf.train.Checkpoint):
  def __init__(self):
    self._two = tf.Variable(2.0, name="two")

  @tf.function(input_signature=[tf.TensorSpec((None, None), tf.float32)])
  def __call__(self, x):
    return tf.multiply(x, self._two)

export_dir = "/tmp/twice"
tf.saved_model.save(Twice(), export_dir)

strategy = tf.distribute.MirroredStrategy()
with tf.Graph().as_default() as g:
  with strategy.scope():
    obj = tf.saved_model.load(export_dir)

  for v in tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.GLOBAL_VARIABLES):
    prefix = "NO INIT" if v.initializer is None else "ok init"
    print(prefix, v)

  init_op = tf.compat.v1.global_variables_initializer()
```

```
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
NO INIT <tf.Variable 'two:0' shape=() dtype=float32>
ok init MirroredVariable:{
  0: <tf.Variable 'two:0' shape=() dtype=float32>
}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7fd461f5dad0> in <module>()
      8     print(prefix, v)
      9 
---> 10   init_op = tf.compat.v1.global_variables_initializer()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in group(*inputs, **kwargs)
   2921       if not hasattr(inp, "device"):
   2922         raise TypeError("Expected tf.group() expected Tensor arguments not "
-> 2923                         "'%s' with type '%s'" % (inp, type(inp)))
   2924       dev = inp.device
   2925       if dev in ops_on_device:

TypeError: Expected tf.group() expected Tensor arguments not 'None' with type '<class 'NoneType'>'
```

**Comment by Saduf2019** [comment] 2021-02-15 05:19
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [git here](https://colab.research.google.com/gist/Saduf2019/94db1593f4993a582109e30cc5ad4b65/untitled532.ipynb)

**Comment by ckkuang** [comment] 2021-03-02 02:06
The issue is fixed in tf-nightly.

**Closed by ckkuang** 2021-03-02 02:06 UTC
Labels: TF 2.4, comp:dist-strat, stat:awaiting tensorflower, type:bug

**Comment by tanmaysachan** [comment] 2022-05-26 12:57
@ckkuang Can the commit fixing this issue be mentioned? Currently stuck with tf 2.4, and need to figure out a workaround for this issue.
