### ISSUE TITLE
Restoring tf.py_funcs used inside of a tf.data.Dataset for use at inference time

### ISSUE THREAD

**Issue by Alaska47** [tensorflow/tensorflow#30966] opened 2019-07-23 21:22 UTC
**tensorflow gpu version:** 1.13.1

I'm currently trying to use the Datasets API at inference time but I am having trouble restoring the model and the iterator/py_func ops. I'm setting up the dataset while training like this and I'm using two py_funcs in my input pipeline:
```python
padding_const_str = tf.constant("<PAD>")
padding_const_int = tf.constant(0, dtype=tf.int64)
dataset_type = tf.placeholder(tf.string, shape=[])
dataset = tf.data.TextLineDataset(dataset_type)
dataset = dataset.map(lambda map_el: tuple(tf.py_func(preprocess, [map_el], [tf.string, tf.string, tf.string, tf.string, tf.int64, tf.int64], name="preprocess_py_func")), num_parallel_calls=16)
dataset = dataset.padded_batch(batch_size=FLAGS.batch_size, padded_shapes=([None],[None],[None],[None],[None],[None]), padding_values=(padding_const_str, padding_const_str, padding_const_str, padding_const_str, padding_const_int, padding_const_int))
dataset = dataset.map(lambda labels, tokens, shapes, chars, seq_lens, tok_len : str_to_id((labels, tokens, shapes, chars, seq_lens, tok_len), labels_str_id_lookup, vocab_str_id_lookup, shape_str_id_lookup, char_str_id_lookup),  num_parallel_calls=16)
dataset = dataset.map(lambda labels, tokens, shapes, padded_chars, seq_len_batch, tok_len : tuple(tf.py_func(postprocess, [labels, tokens, shapes, padded_chars, seq_len_batch, tok_len], [labels.dtype, tokens.dtype, shapes.dtype, padded_chars.dtype, seq_len_batch.dtype, tok_len.dtype, tf.float32, tf.int64, tf.int64, tf.int64], name="postprocess_py_func")), num_parallel_calls=16)
dataset = dataset.prefetch(3)
iterator = tf.data.Iterator.from_structure(dataset.output_types, dataset.output_shapes)
dataset_init_op = iterator.make_initializer(dataset, name='dataset_init')
```

I am trying to load the model and iterator at inference time by doing this, however I'm running into an issue. 
```python
with tf.Graph().as_default():

    saver = tf.train.import_meta_graph(FLAGS.load_dir + '/dilated-cnn.tf.meta')
    ckpt = tf.train.get_checkpoint_state(os.path.dirname(FLAGS.load_dir + '/checkpoint'))
    
    with tf.Session() as sess:
        saver.restore(sess, ckpt.model_checkpoint_path)

        graph = tf.get_default_graph()
        dataset_init_op = graph.get_operation_by_name('dataset_init')
        dataset_type = graph.get_tensor_by_name('Placeholder:0')
        predictions = graph.get_tensor_by_name('predictions/ArgMax:0')

        sess.run(dataset_init_op, feed_dict={dataset_type : "sample_text.txt"})
        print(sess.run(predictions))
```

I keep getting an error saying: 
```
ValueError: callback pyfunc_0 is not found
	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext}}]]
	 [[{{node IteratorGetNext}}]]
```

I understand this is happening because py_funcs are inherently not stored on the computation graph as they are simply pure Python functions. However, even after looking at this [post](https://stackoverflow.com/questions/43644506/setting-up-py-func-op-after-importing-graphdef-in-tensorflow) and creating two py_func skeleton functions, I'm still getting a similar error. 

My question is, does Tensorflow support using the Datasets API at inference time (without using feed dict i.e feeding in the tensors directly into the model without also recreating the model). I'm trying to do it using iterators and a modular dataset but I can't get around this py_func issue. Is there a way to properly restore an iterator that uses py_funcs at inference time or should I focus on converting all my preprocessing to native TF ops (which seems to be taking longer than the py_func version weirdly)?

**Comment by anush-o** [comment] 2019-07-24 06:34
@Alaska47 ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by Alaska47** [comment] 2019-07-24 13:42
Like I said, it occurs when I'm trying to get the value of my output tensor. Specifically with this code: 
```python

def preprocess(map_el):
    # this function takes in a list of strings
    lines = re.findall(r"((?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)|(?=[^\(\"\`{\[:;&\#\*@\)}\]\-,])\S+?(?=\s|$|(?:[?!)\";}\]\*:@\'\({\[])|(?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)|(?=$|\s|(?:[?!)\";}\]\*:@\'\({\[])|(?:\-{2,}|\.{2,}|(?:\.\s){2,}\.)))|\S)", map_el[0].decode("utf-8"))
    sent_len = len(lines)
    max_word_len = max(map(len, [word for word in lines]))
    max_len_with_pad = 2 + sent_len

    tokens = np.empty(max_len_with_pad, dtype="S" + str(max_word_len))
    shapes = np.empty(max_len_with_pad, dtype="S5")
    chars = np.empty(max_len_with_pad*max_word_len, dtype="S5")
    sent_lens = np.empty(1, dtype=np.int64)
    tok_lens = np.empty(max_len_with_pad, dtype=np.int64)
    sent_lens[0] = sent_len

    pad_width = 1

    tokens[:pad_width] = "<PAD>"
    shapes[:pad_width] = "<PAD>"
    chars[:pad_width] = "<PAD>"
    tok_lens[:pad_width] = 1

    char_start = pad_width
    idx = pad_width

    def shape(string):
        if all(c.isupper() for c in string):
            return "AA"
        if string[0].isupper():
            return "Aa"
        if any(c for c in string if c.isupper()):
            return "aAa"
        else:
            return "a"

    for token_str in lines:
        token_shape = shape(token_str)
        token_str_normalized = re.sub("\d", "0", token_str)

        tok_lens[idx] = len(token_str)
        tokens[idx] = token_str_normalized
        shapes[idx] = token_shape

        chars[char_start:char_start+tok_lens[idx]] = [char for char in token_str]

        char_start += tok_lens[idx]
        idx += 1

    tokens[idx:idx + pad_width] = "<PAD>"
    shapes[idx:idx + pad_width] = "<PAD>"
    chars[char_start:char_start + pad_width] = "<PAD>"
    char_start += pad_width
    tok_lens[idx:idx + pad_width] = 1
    idx += pad_width

    padded_len = 1*(len(sent_lens)+1)*pad_width+sum(sent_lens)
    tokens = tokens[:padded_len]
    shapes = shapes[:padded_len]
    chars = chars[:sum(tok_lens)]

    labels = None
    if(len(map_el) == 1):
        labels = np.array(["O"] * sent_len)
    else:
        labels = np.array(("<PAD> " + map_el[1].decode('utf-8') + " <PAD>").split(" "))
    return labels, tokens, shapes, chars, sent_lens, tok_lens

def postprocess(labels, tokens, shapes, chars, seq_lens, tok_len):
    # this function takes in input vectors and returns more input vectors
    batch_size, batch_seq_len = tokens.shape
    mask_batch = np.zeros((batch_size, batch_seq_len), dtype=np.float32)
    actual_seq_lens = np.add(np.sum(seq_lens, axis=1), 2)

    for i, seq_len in enumerate(actual_seq_lens):
        mask_batch[i, :seq_len] = 1

    char_lens = np.sum(tok_len, axis=1)
    max_char_len = np.max(tok_len)
    padded_chars = np.zeros((batch_size, max_char_len * batch_seq_len), dtype=np.int64)
    for b in range(batch_size):
        char_indices = [item for sublist in [range(i * max_char_len, i * max_char_len + d) for i, d in
                                             enumerate(tok_len[b])] for item in sublist]
        padded_chars[b, char_indices] = chars[b][:char_lens[b]]

    # tf.int64, tf.int64, tf.int64, tf.int64, tf.int64, tf.int64, tf.int64, tf.int32, tf.int32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32
    return labels, tokens, shapes, padded_chars, seq_lens, tok_len, mask_batch, batch_size, batch_seq_len, max_char_len

with tf.Graph().as_default():

    saver = tf.train.import_meta_graph(FLAGS.load_dir + '/dilated-cnn.tf.meta')
    ckpt = tf.train.get_checkpoint_state(os.path.dirname(FLAGS.load_dir + '/checkpoint'))
    
    # Even with the py_funcs redefined, I still get the same error
    # py_func1 = lambda map_el: tuple(tf.py_func(preprocess, [map_el], [tf.string, tf.string, tf.string, tf.string, tf.int64, tf.int64], name="preprocess_py_func"))
    # py_func2 = lambda labels, tokens, shapes, padded_chars, seq_len_batch, tok_len : tuple(tf.py_func(postprocess, [labels, tokens, shapes, padded_chars, seq_len_batch, tok_len], [labels.dtype, tokens.dtype, shapes.dtype, padded_chars.dtype, seq_len_batch.dtype, tok_len.dtype, tf.float32, tf.int64, tf.int64, tf.int64], name="postprocess_py_func"))

    with tf.Session() as sess:
        saver.restore(sess, ckpt.model_checkpoint_path)

        graph = tf.get_default_graph()
        dataset_init_op = graph.get_operation_by_name('dataset_init')
        dataset_type = graph.get_tensor_by_name('Placeholder:0')
        predictions = graph.get_tensor_by_name('predictions/ArgMax:0')

        sess.run(dataset_init_op, feed_dict={dataset_type : "sample_text.txt"})

         # ERROR OCCURS HERE
        print(sess.run(predictions))
```

**Comment by anush-o** [comment] 2019-07-31 08:17
@Alaska47 ,
When tried executing the code given `NameError: name 'FLAGS' is not defined` was faced.Can you provide minimal required executable code?Thanks!

**Comment by anush-o** [comment] 2019-08-07 06:53
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by anush-o** 2019-08-07 06:53 UTC
Labels: TF 1.13, comp:ops, stat:awaiting response, type:support
