### ISSUE TITLE
Missing device_attributes.pb.h when make tensorflow to .a file

### ISSUE THREAD

**Issue by SefaZeng** [tensorflow/tensorflow#27508] opened 2019-04-04 13:49 UTC
I want make tensorflow to a static link file so I can use it to run the pretrained model with the cpp API.After I run the **build_all_linux.sh**, I move the **tensorflow** and **third_party** file and the **libtensorflow-core.a** and **libprotobuf.a** and **libnsync.a** to a work path.
And when I compile the cpp code, it returns an error which said 

> fatal error: tensorflow/core/framework/device_attributes.pb.h: No such file or directory

And it occurs in the session.h. I find there is only device_attributes.proto in the path,but I dont know why because I just followed the ways of many blogs online.Is there any thing that I missed?

Any help is appreciate!Thx!

**Comment by achandraa** [comment] 2019-04-05 11:29
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by SefaZeng** [comment] 2019-04-08 02:56
Now,I found all the xxx.pb.h file in this path 

> tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/framework

But why? As the example said, you need to `#include "tensorflow/core/public/session.h"` and the session.h file `include "tensorflow/core/framework/device_attributes.pb.h"`. So,the generate file from protoc should be in the path which is right to the session.h,right?

Need I check all the files in the gen?

**Comment by ymodak** [comment] 2019-05-01 22:09
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by ymodak** 2019-05-01 22:09 UTC
Labels: comp:runtime, type:support

**Comment by banbishan** [comment] 2019-07-08 08:40
hi, @SefaZeng , I got the same error, have you solved the problem?

**Comment by SefaZeng** [comment] 2019-07-08 10:04
> hi, @SefaZeng , I got the same error, have you solved the problem?

你好像是个中国人我就打中文了.. 我其实记不太清这里是咋回事 好像是proto生成的一些文件在我写的那个路径下面 在cmakelist里面把这些路径加进去好像就可以
