### ISSUE TITLE
Infinite recursion in TFModuleWrapper.__getattr__

### ISSUE THREAD

**Issue by chrishmorris** [tensorflow/tensorflow#36710] opened 2020-02-12 19:56 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker container gcr.io/deeplearning-platform-release/tf-cpu.1-15
- **TensorFlow version (use command below)**: v1.15
- **Python version**: Python 3.5.6 :: Anaconda, Inc.
- **Exact command to reproduce**:

### Describe the problem
When running a complex Apache Beam job using Tensorflow to create TFRecords, the jobs fails with 
....
  File "/usr/local/lib/python3.5/site-packages/tensorflow_core/python/util/module_wrapper.py", line 192, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow_core/python/util/module_wrapper.py", line 192, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow_core/python/util/module_wrapper.py", line 192, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow_core/python/util/module_wrapper.py", line 160, in __getattribute__
    attr_map = object.__getattribute__(self, '_tfmw_attr_map')
RecursionError: maximum recursion depth exceeded while calling a Python object

Sorry, I have been unable to isolate a test case. However, TFModuleWrapper.__getattr__ does look vulberable to recursion errors. See https://nedbatchelder.com/blog/201010/surprising_getattr_recursion.html for a discussion of a similar problem.

I am not using kivy, so this is probably different than: https://github.com/tensorflow/tensorflow/issues/27312

**Comment by gadagashwini** [comment] 2020-02-13 06:33
@chrishmorris, Can you provide the sample code to reproduce the reported issue. Thanks!

**Comment by chrishmorris** [comment] 2020-02-13 08:48
Appears to be related to https://github.com/uqfoundation/dill/issues/300. I had a DoFn with a custom init method and a super call, and used save_main_session. So my beam job would have failed, for reasons unconnected with Tensorflow. However, the behaviour of TFModuleWrapper.getattr generated an especially obscure message for the error.

**Comment by gowthamkpr** [comment] 2020-02-26 23:50
Yes this looks like it is being related to dill. Thanks for reporting.

**Comment by yifeif** [comment] 2020-02-27 22:13
Thanks for reporting the issue @chrishmorris. Do you see the same issue with newer version of TF?

**Comment by yifeif** [comment] 2020-04-10 23:18
Closing this. @chrishmorris feel free to re-open if you are still having issue with this.

**Closed by yifeif** 2020-04-10 23:18 UTC
Labels: TF 1.15, comp:ops, type:support

**Comment by narsapuramvijaykumar** [comment] 2024-07-10 08:56
I get same error with tensorflow 2.11 , unable to resolve the same with listed solutions. Any help is highly appreciated

python3.9 -c 'import tensorflow as tf; print(tf.__version__)'
2024-07-10 08:38:28.422239: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/__init__.py", line 470, in <module>
    _keras._load()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import keras
  File "/home/ubuntu/.local/lib/python3.9/site-packages/keras/api/keras/__init__.py", line 13, in <module>
    from keras.api.keras import __internal__
  File "/home/ubuntu/.local/lib/python3.9/site-packages/keras/api/keras/__internal__/__init__.py", line 8, in <module>
    from keras.api.keras.__internal__ import layers
  File "/home/ubuntu/.local/lib/python3.9/site-packages/keras/api/keras/__internal__/layers/__init__.py", line 13, in <module>
    _sys.modules[__name__] = _module_wrapper.TFModuleWrapper(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/module_wrapper.py", line 106, in __init__
    self.__dict__.update(wrapped.__dict__)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/module_wrapper.py", line 213, in _getattribute
    if not (self._tfmw_print_deprecation_warnings and
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/module_wrapper.py", line 213, in _getattribute
    if not (self._tfmw_print_deprecation_warnings and
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/module_wrapper.py", line 213, in _getattribute
    if not (self._tfmw_print_deprecation_warnings and
  [Previous line repeated 938 more times]
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tensorflow/python/util/module_wrapper.py", line 189, in _getattribute
    func__fastdict_insert = object.__getattribute__(self, '_fastdict_insert')
RecursionError: maximum recursion depth exceeded while calling a Python object
