### ISSUE TITLE
Can't save individual models from Tensorflow 1.x Session Checkpoint

### ISSUE THREAD

**Issue by VILLAIN511** [tensorflow/tensorflow#36966] opened 2020-02-21 18:41 UTC
I have a folder containing 3 files
**model.ckpt.data-00000-of-00001
model.ckpt.index
model.ckpt.meta**

It actually contains 3 models (you can check them on tensorboard)
**InceptionV3
TransformNet
VGG16**

If you want to check it out
https://storage.googleapis.com/download.magenta.tensorflow.org/models/arbitrary_style_transfer.tar.gz

I want to separate each model to **individual .pb frozen models** and want to use them in web after conversion using tensorflowjs-converter

I am using below snippet to get InceptionV3(the last node of Iv3 is Conv/BiasAdd)

```
FileWriter("__tb", sess.graph)

  
  frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        ['Conv/BiasAdd']) #Output_nodes

    # Save the frozen graph
  with open('/content/model/IV3.pb', 'wb') as f:
    f.write(frozen_graph_def.SerializeToString())
```

But i don't know how to get **transformer model** after **Conv/BiasAdd** node to the output node.

**Comment by VILLAIN511** [comment] 2020-02-21 19:25
![tb](https://user-images.githubusercontent.com/58945222/75064984-f0234300-550d-11ea-87e9-08e6136b0bc8.PNG)

**Comment by gadagashwini** [comment] 2020-02-24 11:59
@VILLAIN511, Please take a look at this [doc](https://www.tensorflow.org/tutorials/keras/save_and_load#save_checkpoints_during_training) for saving checkpoints in Tensorflow. Thanks

**Comment by gadagashwini** [comment] 2020-03-06 08:41
@VILLAIN511, Did you get a chance to look at document provided above.

**Comment by gadagashwini** [comment] 2020-03-13 09:49
Closing this issue since the tittle of the issue is resolved. 
Please feel free to open if issue still persists. Thanks!

**Closed by gadagashwini** 2020-03-13 09:49 UTC
Labels: TF 1.15, comp:apis, stat:awaiting response, type:support
