### ISSUE TITLE
tf.data.experimental.prefetch_to_device("/gpu:0") moves tensors back to CPU

### ISSUE THREAD

**Issue by OutSorcerer** [tensorflow/tensorflow#30929] opened 2019-07-22 14:42 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: Python 3.6.8
- CUDA/cuDNN version: CUDA Version: 10.0 / cuDNN 7.6.0
- GPU model and memory: Tesla T4  15079MiB

**Describe the current behavior**
`tf.data.experimental.prefetch_to_device("/gpu:0")` moves tensors back to CPU.

**Describe the expected behavior**
`tf.data.experimental.prefetch_to_device("/gpu:0")` should leave tensors on GPU.

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

data = np.array([[1, 2],[3, 4]])

dataset = tf.data.Dataset.from_tensor_slices(data)
dataset = dataset.apply(tf.data.experimental.prefetch_to_device("/gpu:0"))

#dataset = dataset.apply(tf.data.experimental.copy_to_device("/gpu:0"))
#
#Uncommenting the line above line will print:
#
#Tensor [1 2] is on device /job:localhost/replica:0/task:0/device:GPU:0
#Tensor [3 4] is on device /job:localhost/replica:0/task:0/device:GPU:0

for datum in dataset:
  print(f'Tensor {datum} is on device {datum.device}')
  #Prints
  #Tensor [1 2] is on device /job:localhost/replica:0/task:0/device:CPU:0
  #Tensor [3 4] is on device /job:localhost/replica:0/task:0/device:CPU:0
```

It is convinient to reproduce it as [a notebook in Google Colaboratory](https://colab.research.google.com/drive/1LpOX04L6l8SW3krQvzFdQVvXE-LK3ehH).

**Comment by ravikyram** [comment] 2019-07-23 09:10
I have tried on colab with TF version 2.0.0-beta1 and was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1UB-vuD2MNChCJBAsf1aWM5pIw17AAtWm) here.Thanks!

**Comment by gadagashwini** [comment] 2020-03-13 08:48
Reproduce this issue with Tf 2.1 and Tf-nightly==2.2.0.dev20200312
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/56ac5217e9ee6d137bc43f62f9bfc965/untitled454.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-15 02:48
@OutSorcerer This is intended behaviour only. Please check the comment on similar issue [here](https://github.com/tensorflow/tensorflow/issues/28610#issuecomment-494171724). Thanks!

**Comment by jsimsa** [comment] 2020-03-15 15:46
It is not intended behavior and there is an outstanding PR to fix this bug: https://github.com/tensorflow/tensorflow/pull/37277

**Comment by jvishnuvardhan** [comment] 2020-03-15 19:12
@jsimsa Sorry, I was wrong. Thanks for the correction.

**Comment by Saduf2019** [comment] 2020-04-19 16:40
@OutSorcerer 
as there is a pr to monitor this issue [there is an outstanding PR to fix this bug: #37277], please confirm if we may move this to closed status

**Comment by OutSorcerer** [comment] 2020-04-20 08:19
@Saduf2019, thanks for the answer, it is great that fixing this is work in progress!

I hope #37277 will be merged, but if it would not be merged and this issue would be closed now there would be no open issues/PRs on the topic, so I suggest to link this issue to the PR instead, so that [when it is merged the issue is closed automatically](https://github.blog/2013-05-14-closing-issues-via-pull-requests/).

**Comment by Saduf2019** [comment] 2020-06-05 05:09
@OutSorcerer
As the Pr is merged, please confirm if we may move this issue to closed status.

**Comment by drasmuss** [comment] 2020-06-05 12:45
The PR has not been merged, as mentioned in this comment it was rolled back https://github.com/tensorflow/tensorflow/pull/37277#issuecomment-620202464

**Comment by jsimsa** [comment] 2020-06-05 16:23
This issue should be fixed by https://github.com/tensorflow/tensorflow/commit/8be4d61574f29568c8699708d88945b441bfd317

**Closed** 2020-06-19 17:52 UTC
Labels: TF 2.0, TF 2.1, comp:data, stalled, stat:awaiting response, type:bug
