### ISSUE TITLE
TypeError: convolution() got multiple values for argument 'weights_regularizer'

### ISSUE THREAD

**Issue by chouqin3** [tensorflow/tensorflow#21749] opened 2018-08-21 03:30 UTC
I got error like this, how do I fix it, please help me
Traceback (most recent call last):
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 398, in <module>
    ret = run(arg.vid_file, t, arg.clip_dur, pr, gpus[0], mask = arg.mask, arg = arg, net = net)
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 294, in run
    net.init()
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 42, in init
    pr, reuse = False, train = False)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\sourcesep.py", line 953, in make_net
    vid_net_full = shift_net.make_net(ims, sfs, pr, None, reuse, train)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\shift_net.py", line 419, in make_net
    sf_net = slim.conv2d(sf_net,num_outputs= 64, kernel_size= [65, 1], scope = 'sf/conv1_1', stride = [4, 1], padding='SAME', reuse = reuse) 
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: convolution() got multiple values for argument 'weights_regularizer'

**Comment by tensorflowbutler** [comment] 2018-08-21 12:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-05 18:51
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-20 12:44
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment] 2018-09-24 22:42
Closing this issue since the issues template was not filled out.

**Closed by reedwm** 2018-09-24 22:42 UTC
Labels: stat:awaiting response
