### ISSUE TITLE
Allow sessions to be started in cpu-only mode.

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#754] opened 2016-01-12 19:26 UTC
I would find it convenient to be able to start a session in cpu only mode (e. g. because you have another session running already that hogs all the VRAM). My workaround for now is to use

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.01)
    with tf.Session(config=tf.ConfigProto(log_device_placement=True, gpu_options=gpu_options)) as sess:

And then wrap `with tf.device('/cpu:0'):` around the model construction.

**Comment by nryant** [comment] 2016-01-13 14:19
Setting CUDA_VISIBLE_DEVICES to the empty string will accomplish the desired result.

**Comment by panmari** [comment] 2016-01-15 09:03
Doesn't that need to be set before running python? Or is it enough to export it before launching a TF session?

**Comment by nryant** [comment] 2016-01-15 21:36
As long as you set it before creating any session it will work.

**Comment by vrv** [comment] 2016-01-15 21:51
(I have a potentially better but bigger change that should help with this, but no guarantee that I'll get it in in the next week).

**Comment by LeavesBreathe** [comment] 2016-01-26 19:58
@vrv have you implemented your solution to this yet? Would be nice to have some sort of simple command to not call upon the gpu if you already have another session going on.

**Comment by vrv** [comment] 2016-01-26 20:03
In https://github.com/tensorflow/tensorflow/commit/8421f177ced940374e06a9daf9b4ee638e207f10 I made it so that if you never use the GPU device, you never allocate any memory for it.

Longer term I want to make the memory allocator grow as needed, but my test change showed a 5% reduction in memory capacity due to the additional fragmentation created.

We're working on a bigger change to the memory allocation strategy in general, but hopefully the commit above will help.

**Comment by LeavesBreathe** [comment] 2016-01-27 00:57
>We're working on a bigger change to the memory allocation strategy in general, but hopefully the commit above will help.

Thanks! Allowing RNN's to take less memory would be such a game changer. I know you have heard that from several individuals already, so don't want to be overbearing.

**Comment by vrv** [comment] 2016-02-06 22:14
Closing since this is probably addressed for the time being.

**Closed by vrv** 2016-02-06 22:14 UTC

**Comment by Steviey** [comment] 2017-05-02 15:37
CUDA_VISIBLE_DEVICES does not work anymore.

**Comment by vrv** [comment] 2017-05-02 16:49
```
(tf)$ CUDA_VISIBLE_DEVICES='' python
<snip>
>>> import tensorflow as tf
>>> s = tf.Session()
<snip>
2017-05-02 09:48:02.014954: E tensorflow/stream_executor/cuda/cuda_driver.cc:405] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-05-02 09:48:02.014996: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: vijay-linux.mtv.corp.google.com
2017-05-02 09:48:02.015006: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: vijay-linux.mtv.corp.google.com
2017-05-02 09:48:02.015045: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 370.28.0
2017-05-02 09:48:02.015259: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  370.28  Thu Sep  1 19:45:04 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
2017-05-02 09:48:02.015285: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 370.28.0
2017-05-02 09:48:02.015293: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 370.28.0
```

In another process:
```
$ nvidia-smi

<snip>
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     96368    G   /usr/lib/xorg/Xorg                             451MiB |
|    0     96949    G   cinnamon                                       114MiB |
+-----------------------------------------------------------------------------+
```

@Steviey we need more evidence, reproduction steps, etc.

**Comment by ahundt** [comment] 2017-09-01 00:51
I also seem to encounter this:

```
± CUDA_VISIBLE_DEVICES="" python grasp_dataset.py --grasp_download 102
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Using TensorFlow backend.
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4664:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2209:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4185:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4664:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2209:(snd_pcm_open_noupdate) Unknown PCM default
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
NVIDIA: no NVIDIA devices found
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (login-node03): /proc/driver/nvidia/version does not exist
```

**Comment by pronot** [comment] 2018-03-12 10:27
I also get the same errors. Any progress or fix on this issue?

**Comment by ahundt** [comment] 2018-03-15 19:38
Improved example command:
```
export CUDA_VISIBLE_DEVICES="" && python my_script.py
```
