### ISSUE TITLE
Use of tf.custom_gradient prevents garbage collection of Graph

### ISSUE THREAD

**Issue by matthen** [tensorflow/tensorflow#27492] opened 2019-04-04 06:10 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): pip install tensorflow==1.13.1
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.4
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

Using an op decorated with `tf.custom_gradient` prevents the `tf.Graph` it was created in from being garbage collected later. So if a script creates multiple such graphs in a row, it will use more and more memory unnecessarily.
I believe it's due to the `Graph` being held as an indirect reference to the custom gradient registry.

**Describe the expected behavior**

Ideally such a `Graph` would not be referenced forever, allowing it to be garbage-collected.

**Code to reproduce the issue**

```python
import gc
import objgraph
import tensorflow as tf


@tf.custom_gradient
def op(x):
    def grad(dy):
        return dy * 10.0
    return x, grad


def run(use_custom_gradient):
    with tf.Session(graph=tf.Graph()) as sess:
        x = tf.constant([1, 2, 3])
        if use_custom_gradient:
            print("(Using custom_gradient)")
            x = op(x)
        sess.run(x)


def log():
    gc.collect()
    print(
        "number of uncollected graphs:",
        len(objgraph.by_type('Graph')))


for use_custom_gradient in [False, True, True, False, False, True]:
    run(use_custom_gradient)
    log()
```

outputs:

```
number of uncollected graphs: 0
(Using custom_gradient)
number of uncollected graphs: 1
(Using custom_gradient)
number of uncollected graphs: 2
number of uncollected graphs: 2
number of uncollected graphs: 2
(Using custom_gradient)
number of uncollected graphs: 3
```

(ideally it should always say `number of uncollected graphs: 0`)

**Other info / logs**
n/a

**Comment by alextp** [comment] 2019-04-11 16:57
Yes, this can be a problem. Marking as contributions welcome as I won't have time to dig into this soon, and someone interested in finding the backreferences to those graphs might have a better luck.

**Comment by QuRyu** [comment] 2019-04-30 00:23
(Disclaimer: I am new to tensorflow but would love to help fix issues)
It seems the problem is caused by the line `x = op(x)`. While trying to figure out what `op()` does, I failed to find the documentation for `op`. I threaded through the code and found that `tf.constant()` creates a 'Tensor' object, as verified by `type(x) is tf.Tensor`. But the `op` function defined in `Tensor` calls `_op, which I can't find. 
May I ask what transformation `x` has gone through with the `op` function and what materials should I look into to understand it?

**Comment by astropeak** [comment] 2019-05-15 08:01
Hey, I'd like to take a crack at this!

**Comment by alextp** [comment] 2019-05-15 16:00
@astropeak Great! Have you looked at python's GC module and how it lets you find out all references to a living object? That's where I'd start

**Comment by danyjacob45** [comment] 2019-05-16 06:53
great blog detailing (with links) about GC 
https://rushter.com/blog/python-garbage-collector/

**Comment by astropeak** [comment] 2019-05-17 09:35
It turns out that the graph object is finally referenced by the global variable '_gradient_registry', which is in 'tensorflow/python/framework/ops.py'.

This is how (for the above example):
Notation: 'A -> B' means A is referenced by B

graph ->
x ->
result object in custom_gradients.py at line 183 ->
flat_result  in custom_gradients.py ->
closure tape_grad_fn  in custom_gradients.py ->
closure internal_grad_fn  in custom_gradients.py ->
_gradient_registry

I found the reference relationship between 'closure tape_grad_fn' and 'flat_result' could be broken, since 'closure tape_grad_fn' only uses 'len(flat_result)'. After that reference is broken, the problem disappears. So this could be a solution. Do you have any opinions? If this solution looks good, I will create a pull request soon.

**Comment by alextp** [comment] 2019-05-17 16:23
That sounds like the correct fix. Would love a pull request!

**Comment by charmasaur** [comment] 2021-03-12 07:09
I guess this is a pretty old issue now, but I just came across a similar incarnation, which I don't think is fixed by #28826.

Using the example from `custom_gradient`, which is:
```
@tf.custom_gradient
def log1pexp(x):
  e = tf.exp(x)
  def grad(dy):
    return dy * (1 - 1 / (1 + e))
  return tf.math.log(1 + e), grad
```
notice that the `grad` function holds a reference to the `e` tensor (which references its containing graph) via its closure. Breaking the reference from `tape_grad_fn` to that `grad` function doesn't really seem possible. Fundamentally, it seems to me that the issue is that the gradient registry is global rather than scoped to a graph...

FWIW I don't see this issue when using `@tf.function` instead of `tf.Graph()`s, seemingly because with `@tf.function` the `e` tensor doesn't hold a reference to any graph. I don't know enough about `@tf.function`s to say whether that's by design or by accident though.

**Comment by charmasaur** [comment] 2021-03-15 23:57
Came up with a workaround, in case anybody else needs it. Trick is to only let the custom gradient machinery get access to a weak reference to your actual gradient function (and any subsequent objects captured in its closure). Note that to avoid the gradient function then getting GC'd too *early* we also need to keep a strong reference around for the lifetime of the graph, which we can do with a graph collection:
```
def custom_custom_gradient(f):
    def _f(*x):
        y, grad = f(*x)

        if tf.compat.v1.executing_eagerly():
            new_grad = grad
        else:
            tf.compat.v1.get_default_graph().add_to_collection(
                "custom_gradient_functions", grad
            )

            grad_weak = weakref.ref(grad)

            def new_grad(*grad_ys):
                return grad_weak()(*grad_ys)

        return y, new_grad

    return tf.custom_gradient(_f)
```

**Comment by rmothukuru** [comment] 2021-04-26 10:12
@matthen,
Your code could be run without any error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/bb2e518503624af19cd09c857644dbdb/gh_27492.ipynb) of the working code. Please let us know if we can close this issue? Thanks!

**Closed** 2021-05-10 10:59 UTC
Labels: comp:ops, stalled, stat:awaiting response, stat:contributions welcome, type:bug
