### ISSUE TITLE
TFLite: allocate_tensors() fails for 2 dense layers with quantization

### ISSUE THREAD

**Issue by julian-urban** [tensorflow/tensorflow#36705] opened 2020-02-12 18:54 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15.0

I'm trying to convert a model built with keras to tflite in order to run it on an Edge TPU. If I use more than one dense layer, allocate_tensors() throws an error. It only happens for full integer quantization with a representative dataset. Here is a minimal example which reproduces this error:

```
import keras
import tensorflow as tf
import tflite_runtime.interpreter as tflite
import numpy as np


n = 16

dense_1 = keras.layers.Dense(n)
dense_2 = keras.layers.Dense(n)

x = keras.layers.Input(shape=(n,))

y = dense_1(x)
y = dense_2(y)

model = keras.models.Model(inputs=[x], outputs=[y])

model.compile(optimizer='rmsprop', loss='mean_squared_error')
model.save('example.h5')

input_shapes = {}
input_shapes['input_1'] = (1, n)
converter = tf.lite.TFLiteConverter.from_keras_model_file('example.h5', input_shapes=input_shapes)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

def rep_data_gen():
	for _ in range(100):
		yield [np.random.rand(1, n).astype(np.float32)]

converter.representative_dataset = rep_data_gen

tflite_model = converter.convert()
open("example.tflite", "wb").write(tflite_model)

interpreter = tflite.Interpreter("example.tflite",
								 experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')])

interpreter.allocate_tensors()
```

The error:

```
Traceback (most recent call last):
  File "example.py", line 43, in <module>
    interpreter.allocate_tensors()
  File "/home/julian/anaconda3/envs/keras/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/julian/anaconda3/envs/keras/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/kernel_util.cc:106 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.Node number 2 (FULLY_CONNECTED) failed to prepare.
```

Note that the error doesn't occur when I drop ```y = dense_2(y)```. I feel like I am missing something simple, but what is it? This is the simplest two-layer model I can imagine, so it should really work.

**Comment by terryheo** [comment] 2020-02-13 07:34
@daverim allocation works without quantization. Any idea?

**Comment by AlmogDavid** [comment] 2020-02-16 14:46
I'm having the exact same issue, someone knows what is the problem?

**Comment by Namburger** [comment] 2020-02-19 19:10
@julian-urban 
Unrelated, but make sure you [compile the model](https://coral.ai/docs/edgetpu/compiler/) after converting it to a tflite model, otherwise model will still be executed on CPU. Also don't forget this:
```
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```

Also, your input shape is dynamic, which isn't supported:
```
x = keras.layers.Input(shape=(n,))
```
Can you try fixing that?

**Comment by julian-urban** [comment] 2020-02-19 22:00
@Namburger 
Thanks for your answer. I set the input and output type to tf.uint8 and fixed the input shape to (1, n). I tried to compile the model, but unfortunately it throws the same error:

```
$ edgetpu_compiler example.tflite 
Edge TPU Compiler version 2.0.291256449
ERROR: :129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
ERROR: Node number 2 (FULLY_CONNECTED) failed to prepare.


Model compiled successfully in 1 ms.

Input model: example.tflite
Input size: 2.02KiB
Output model: example_edgetpu.tflite
Output size: 1.85KiB
On-chip memory available for caching model parameters: 0.00B
On-chip memory used for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 0
Operation log: example_edgetpu.log
See the operation log file for individual operation details.
$
```

Any ideas? Thanks for bringing the dummy example to my attention, I will check it out and see if it helps my issue.

**Comment by Namburger** [comment] 2020-02-19 22:12
@julian-urban 
Humn, so I'm still seeing this:
```
ERROR: :129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
ERROR: Node number 2 (FULLY_CONNECTED) failed to prepare.
```
Possibly due to undefined weight, can you show me your current code for producing model by any chance?

**Comment by julian-urban** [comment] 2020-02-19 22:23
@Namburger 

The dummy example with Conv2D worked (also with more than one layer). I adapted the code to have two Dense layers:

```
import tensorflow as tf
if not str(tf.__version__).startswith('1.15'):
    print('please use tensorflow 1.15')
    exit()
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, Dense

tf.enable_eager_execution()

n = 64

# image_shape = (n,n,3)
image_shape = (n,)

# Creating a dummy keras model here
x = Input(shape=image_shape)

# y = Conv2D(3, (3, 3), padding='same')(x)
# y = Conv2D(3, (3, 3), padding='same')(y)

y = Dense(n)(x)
y = Dense(n)(y)

model = Model(inputs=x, outputs=y)
model.summary()
model.save('keras_model.h5', include_optimizer=False)

def representative_dataset_gen():
    for i in range(100):
        # creating fake images
        image = tf.random.normal([1] + list(image_shape))
        yield [image]

# actual conversion
converter = tf.lite.TFLiteConverter.from_keras_model_file('keras_model.h5')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8] # For EdgeTPU, no float ops allowed
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# save model
tflite_model = converter.convert()
open('dummy.tflite', 'wb').write(tflite_model)
```

The same error appears when I try to compile it. Note that I still have (n,) as the input shape, I tried fixed ones as well but to no avail. I don't think the problem is related to this. Do I need to initialize the weights manually? If I remember correctly, I tried that and it didn't help. Maybe it's a keras issue? Is there a dummy example that just uses tensorflow?

**Comment by Namburger** [comment] 2020-02-19 23:11
@julian-urban Right now this looks like a tflite convertion issue to me as @terryheo mentioned that it [works without quantization](https://github.com/tensorflow/tensorflow/issues/36705#issuecomment-585591604). Maybe @daverim will have more insight?

I do have a dummy example for converting a .pb file, it downloads a mobile net model and converts it to tflite. Although not sure if it'd help you in this case: https://github.com/tensorflow/tensorflow/issues/36705#issuecomment-585591604

On another note, just wanted to make you aware that `Dense` is not a [supported operation](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) by the compiler at this time. So once this is fixed, chances are the model still won't pass the compiler. 

I still think it's still worth investigating why you are not able to allocate_tensors() after conversion though.

**Comment by julian-urban** [comment] 2020-02-20 00:06
@Namburger 

> On another note, just wanted to make you aware that Dense is not a supported operation by the compiler at this time. So once this is fixed, chances are the model still won't pass the compiler (plus the dynamic input size).

That explains a lot, however, I do see 'FullyConnected' on the list. How do I implement the operation in keras or tensorflow? Should I just use matrix-vector multiplication syntax?

**Comment by Namburger** [comment] 2020-02-21 19:18
I'm not a hundred percent sure on this, but maybe [this](https://stats.stackexchange.com/a/383797) will help?

**Comment by shariq-audiofocus** [comment] 2020-04-09 18:41
Running into this issue as well. I tried converting the graph to a .pb file (freezing the graph) as @Namburger  suggested and then using TFLiteConverter.from_frozen_graph() but that also failed with the same error. 

Looking at the MobileNet architecture[1] it seems like there is only one FC layer so perhaps that is why this bug was not caught seen before. It seems surprising that no model with 2 FC layers has been compiled for the Edge TPU yet. Does anyone know one so I can try to replicate it?

[1] Table 1 of https://arxiv.org/pdf/1704.04861.pdf

**Comment by shariq-audiofocus** [comment] 2020-04-09 20:51
Workaround: Make the layers have different sizes. @julian-urban 

Strangely, if the layer sizes are different the issue does not manifest. Got the idea from https://github.com/tensorflow/tensorflow/issues/30173 with I believe is a duplicate of this. I wrote some code to demonstrate my claim:

```
# How to Reproduce issue:
# 1) Install TensorFlow 1.15 ('1.15.0') and edgetpu_compiler
# 2) python simple_example.py (this file)
# 3) edgetpu_compiler issue_36705_dummy.tflite
#    - Will fail with ERROR: :129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
# 4) Set 'will_work = True' below:
# 5) Repeat steps 2 & 3 and it will compile successfully.

import tensorflow as tf
import numpy as np
import pdb 


def main():
  tflite_filepath = "issue_36705_dummy.tflite"
  will_work = True  # Switch to trigger bug/fix
  
  # Hyperparameters
  tflite_batch_size = 1 
  input_size = 64

  num_layers = 2 
  default_layer_size = 1024
  if will_work:
    # Make the layers different sizes to avoid the issue.
    layer_sizes = [default_layer_size - i for i in range(num_layers)]
  else:
    layer_sizes = [default_layer_size] * num_layers
  
  # Build Graph
  input_shape = (tflite_batch_size, input_size)
  x = tf.compat.v1.placeholder(tf.float32, shape=input_shape)

  output = x 
  for i in range(num_layers):
    # Can use tf.matmul or tf.keras.layers.Dense here too:
    output = tf.contrib.layers.fully_connected(output, layer_sizes[i])

  # Build TFLite
  with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())

    converter = tf.compat.v1.lite.TFLiteConverter.from_session(sess, 
        [x], [output])

    def representative_dataset_gen():
      for i in range(100):
        yield [np.ones(input_shape).astype(np.float32)]

    # UINT8 + Edge TPU Constraints.
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.representative_dataset = representative_dataset_gen
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8

    # Build and write binary.
    tflite_binary = converter.convert()
    open(tflite_filepath, "wb").write(tflite_binary)


if __name__ == "__main__":
  main()
```

**Comment by julian-urban** [comment] 2020-04-16 13:11
@shariq-audiofocus Thanks for the workaround, I'll try it out. I guess you can train your network as desired and then embed the learned weights into layers of varying size. It's a shame though that such a simple model requires this amount of hacking to get it to run. I'm not a particular fan of the documentation either, the available information is really sparse and scattered. I suppose the Edge TPU was rushed to production and now we have to deal with the resulting shortcomings, I'm just speculating though... don't get me wrong, it's still a great platform/project. However, encountering issues like this one when you just want to try some super elementary, straightforward stuff simply doesn't leave a great impression, is all I'm saying.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:12
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:52 UTC
Labels: TF 1.15, comp:lite, stat:awaiting tensorflower, type:bug
