### ISSUE TITLE
can't import tensorflow.keras properly

### ISSUE THREAD

**Issue by DequanZhu** [tensorflow/tensorflow#26813] opened 2019-03-18 01:39 UTC
I,m writing my code in vscode edit with tensorflow=1.13.1 version and anaconda virtual environment. But when I write 'from tensorflow.keras import layers',it give me a warning:
"unresolved import 'tensorflow.keras'(unresolved import)". 
The code can run as I expected,no errors. But because tensorflow.keras can't be imported properly,the auto-completion and intelligent hint function can't work,I need to search the function's usage everytime. I have thought it's the problem of vscode, but the problem came as well when I use pycharm IDE. Have anyone has the same problem? Is there anyone can help me?

**Comment by mr-ubik** [comment] 2019-03-18 08:17
The problem is present also in 2.0. Apparently, Jedi (or Pyls) cannot resolve Keras import.

**Comment by AlexMetsai** [comment] 2019-03-18 10:28
Works fine for me, with both ways of importing
"from tensorflow.python.keras import layers"
and
"from tensorflow.keras import layers"

Can you give us a little more info about your configuration?

**Comment by mr-ubik** [comment] 2019-03-18 11:11
In my case I am using the 2.0 Nightly, the issue is related to autocomplete either using Jedi or Pyls (Python Language Server) with either Vim/Neovim/Pycharm or VS Code.
The issue is present also if linting with pylint as it cannot see Keras marking it as an erroneous import. The problem is common to all 4 machines we use in our lab. The only peculiar thing is that we run Arch Linux but Tensorflow is installed in a separate virtualenv. Every other module seems to work fine, Keras is the only problematic one.

**Comment by DequanZhu** [comment] 2019-03-18 11:22
> Works fine for me, with both ways of importing
> "from tensorflow.python.keras import layers"
> and
> "from tensorflow.keras import layers"
> 
> Can you give us a little more info about your configuration?

I works on windows10 platform, and I use the python plugin for vscode. It seems that just tensorflow's keras module can't be imported properly, i.e. vscode's automatic completion function didn't work but other modules works fine.

**Comment by AlexMetsai** [comment] 2019-03-18 12:14
If the issue is related to autocomplete related to your IDEs, then maybe this isn't a tensorflow issue.
Can you import from a python interpreter that does NOT use any autocomplete method? If you already tried that, does the problem persist?

**Comment by mr-ubik** [comment] 2019-03-26 12:23
Importing keras in an interpreter works but all linters and autocomplete providers cannot resolve it. Unless it's something shared by all of them I would guess it's TF

**Comment by tensorflowbutler** [comment] 2019-04-10 13:07
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by iLeW** [comment] 2019-04-10 14:22
The automatic completion never worked for me either. I'm using PyCharm (professional edition).

**Comment by darophi** [comment] 2019-04-17 09:36
You can use the v1 api like so:
```python

from tensorflow._api.v1.keras import Sequential
from tensorflow._api.v1.keras.layers import Dense
```
or the tensorflow.python api like so:

```python
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Dense
```

**Comment by ymodak** [comment] 2019-04-19 23:09
Closing this issue since it is IDE related. Feel free to reopen if have any questions. Thanks!

**Closed by ymodak** 2019-04-19 23:09 UTC
Labels: comp:keras, stat:awaiting response, type:support

**Comment by DequanZhu** [comment] 2019-04-20 02:32
It solved my problem, thank you!

At 2019-04-17 18:00:06, "Raphael Neumann" <notifications@github.com> wrote:


You can use the v1 api like so:

from tensorflow._api.v1.keras import Sequential
from tensorflow._api.v1.keras.layers import Dense

or the tensorflow.python api like so:

from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Dense

**Comment by kong13661** [comment] 2019-05-03 09:16
It seems because auto-complete won't scan the whole code of a library. I open `__init__.py` file whose path is `/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py` in my computer, and add one line `from tensorflow.python import keras`. It works for me. And you can find the path of the file by using finding definition of your IDE. I think it's a temporary way.

**Comment by astier** [comment] 2019-10-26 17:11
@kong13661 so it is a tf issue.

**Comment by yurnery** [comment] 2019-11-15 10:59
this is still a problem for me, it cann't auto-complete the code.

**Comment by ajmssc** [comment] 2020-01-18 23:10
this is reproducible outside of IDEs using pylint
```
python -m pylint --disable=all --enable=E0401 model.py
```

**Comment by astier** [comment] 2020-01-19 00:43
Please reopen. This is a real issue.

**Comment by dantengdekaoya** [comment] 2020-01-23 12:57
Please reopen. This is a real issue.

**Comment by janosh** [comment] 2020-01-30 19:56
I third @astier. Getting `unresolved import 'tensorflow.keras.layers'` with

```py
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPool2D
```

Importing from `tensorflow.python.keras.layers` makes no difference. This is in TF r2.1.

**Comment by pjsjongsung** [comment] 2020-02-01 23:00
Using tensorflow 2.1.0 in VScode.
I'm having the same issue.

**Comment by Adilkhan510** [comment] 2020-02-12 05:23
Having the same issue. Please reopen this

**Comment by ximalayashanjiao** [comment] 2020-02-13 14:24
Having the same issue. Please reopen this

**Comment by marewi** [comment] 2020-02-19 17:03
same issue with VScode 1.42.1 & tensorflow 2.0.1

**Comment by soheilazangeneh** [comment] 2020-02-20 01:24
Same issue TensorFlow 2.0 in PyCharm.

**Comment by dantengdekaoya** [comment] 2020-02-20 02:55
If you upgrade pycharm to 2019.3 version, this issue may can be solved.

Soheila Zangeneh <notifications@github.com>于2020年2月20日 周四上午10:25写道：

**Comment by adriangb** [comment] 2020-02-22 17:17
Same issue here. All other packages work fine.

**Comment by soheilazangeneh** [comment] 2020-02-22 17:36
> If you upgrade pycharm to 2019.3 version, this issue may can be solved. Soheila Zangeneh <notifications@github.com>于2020年2月20日 周四上午10:25写道：
> […](#)

Worked for me! Thanks!

**Comment by ShreyasRP** [comment] 2020-02-26 15:30
Try removing the prefix "tensorflow".
Eg: from keras import layers

**Comment by dskkato** [comment] 2020-03-06 01:54
When I switched to use flake8 instead of pylint, all error message related to importing keras has gone. If you try, open VScode setting page and serach `Linting Enabled`, and

1. Uncheck `Python › Linting: Pylint Enabled`
2. Check `Python › Linting: Flake8 Enabled`

**Comment by raspstephan** [comment] 2020-03-16 17:53
I opened an issue for this on the vscode-python page: https://github.com/microsoft/vscode-python/issues/10598

**Comment by sunn1melon** [comment] 2020-05-09 07:18
> 
> 
> When I switched to use flake8 instead of pylint, all error message related to importing keras has gone. If you try, open VScode setting page and serach `Linting Enabled`, and
> 
>     1. Uncheck `Python › Linting: Pylint Enabled`
> 
>     2. Check `Python › Linting: Flake8 Enabled`
> 
> 
> Other solution?
> 
> [#15736 (comment)](https://github.com/tensorflow/tensorflow/issues/15736#issuecomment-354642939)

That finally worked for me! Thanks a lot for that hint!

**Comment by mayankgupta1905** [comment] 2020-05-10 10:09
Working with the 2.1.0. The problem persists only with the TensorFlow modules.

**Comment by Mrmachiner** [comment] 2020-05-11 15:38
uninstall extension Visual Studio IntelliCode works fine for me

**Comment by mihaimaruseac** [comment] 2020-05-15 00:08
Locking conversation to drive people encountering new issues with newer code to open new issue reports (filling in template) and to help people encountering the same issue find the solution here
