### ISSUE TITLE
ptr bug tensorflow

### ISSUE THREAD

**Issue by allendred** [tensorflow/tensorflow#27913] opened 2019-04-17 10:44 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>
wrong ptr 
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.13
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:7.0/9.0
- GPU model and memory: 1080ti

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
project deeplab v3 +.When I open the memory, the network input is a pointer to mat, not a pointer to the raw file I opened, so the input is wrong. And remove the pointer input of mat, although the input pointer is correct,  the content read by tensor is wrong, resulting in the final output map is all 2 (label).This may be related to defining the location of the tensor.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`    Mat img=imread(image_path);
    cvtColor(img, img, CV_BGR2RGB);
    unsigned char * q=img.data;
         FILE *out; 
         out = fopen("./a011.raw", "rb");
    unsigned char *buf_tempx;
    Tensor resized_tensor(DT_UINT8, TensorShape({1,input_height,input_width,3}));
    buf_tempx = (unsigned char *)malloc(input_width*input_height*3);
        fread(buf_tempx, 1, input_width*input_height*3, out);
        fclose(out);
    Point_to_Tensor(buf_tempx,&resized_tensor,input_height,input_width);
    struct  timeval start;
    struct  timeval end;
    unsigned  long diff;
    gettimeofday(&start,NULL);
    cout<<endl<<"<-------------Running the model with test_image--------------->"<<endl;
    vector<tensorflow::Tensor> outputs;
    string output_node = output_tensor_name;
    Status status_run = session->Run({{input_tensor_name, resized_tensor}}, {output_node}, {}, &outputs);
`

**Comment by jvishnuvardhan** [comment] 2019-05-06 21:04
@allendred Could you create a reproducible code or a GitHub gist to reproduce the issue? It will help us to resolve the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-14 22:07
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-14 22:07 UTC
Labels: comp:model, stat:awaiting response, type:bug/performance
