### ISSUE TITLE
Object_detection_api : Le fichier sp\udce9cifi\udce9 est introuvable.

### ISSUE THREAD

**Issue by ABNeqrouz** [tensorflow/tensorflow#19939] opened 2018-06-12 12:16 UTC
Thisissue appear when i want to generate TFRecord file.

models\research\object_detection\images\train\image1 : Le fichier sp\udce9cifi\udce9 est introuvable. ; No such file or directory

`def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf-8')
    image_format = b'png'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf-8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example`
this is the stack-trace : File "generate_tfrecord.py", line 46, in create_tf_example encoded_jpg = fid.read()

**Comment by tensorflowbutler** [comment] 2018-06-13 01:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by anouaradyel2** [comment] 2018-06-13 06:42
Hello,

I am having exactly the same problem. with the same error message.
Is that due to my non use of GPU? (my programmes run only on my CPU because i work on simple objects and few data)

**Comment by tensorflowbutler** [comment] 2018-06-27 18:52
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-12 19:09
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by achowdhery** [comment] 2018-07-20 20:06
Please consider following steps in this tutorial:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by achowdhery** [comment] 2018-08-01 19:55
Is this still an open issue?

**Comment by tensorflowbutler** [comment] 2018-08-16 20:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-08-31 19:31
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-15 18:43
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 20:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 20:52 UTC
Labels: stat:awaiting response
