### ISSUE TITLE
TensorRT Slowdown Native->FP32 and FP16->INT8; File Size Increase

### ISSUE THREAD

**Issue by nseidl** [tensorflow/tensorflow#31039] opened 2019-07-25 17:13 UTC
## **System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04, [nvcr.io/nvidia/tensorrt:19.02-py3](https://docs.nvidia.com/deeplearning/sdk/tensorrt-container-release-notes/rel_19-02.html#rel_19-02)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-7024-g24b3e6cf73 1.15.0-dev20190725
- Python version: 3.5.2
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0.130 / 7.4.2 as per the above linked container
- GPU model and memory: Tesla V100 32GB

Relevant output from `pip freeze`:
```
tf-estimator-nightly==1.14.0.dev2019072201
tf-nightly-gpu==1.15.0.dev20190725
```

## **Describe the current behavior**

**Inference Speed (frames per second)**

| Model | Native | FP32 | FP16 | INT8 | 
| - | - | - | - | - |
| tiny-yolo | 348 | 333 | 402 | 415 |
| big-yolo | 125 | 140 | 243 | 208 |

**1. Why is there a slowdown for tiny native->FP32?** (@pooyadavoodi same as [here](https://github.com/tensorflow/tensorflow/issues/30717#issuecomment-513938562))
**2. Why is this slowdown not consistent for big?**
**3. Why is there a slowdown for big FP16->INT8?**

**Model Size (megabytes)**

| Model | Native | FP32 | FP16 | INT8 | 
| - | - | - | - | - |
| tiny-yolo | 35 | 67 | 44 | 51 |
| big-yolo | 238 | 439 | 288 | 332 |

I understand that there is currently an issue where new graph weights are saved twice to the .pb file (#30717, #30789). Once the weights in the table are adjusted for this double weight saving, the resulting sizes for fp32 and fp16 seem reasonable.

**1. Why is there an increase in size for fp16->int8?**

## **Describe the expected behavior**

I am trying to quantize two different YOLO models (one tiny, one normal) with TensorRT. The goals of this quantization are:

1. speed up inference
2. decrease model size

As quantization and conversion proceeds from native->fp32->fp16->int8, I expect inference time to decrease (FPS to increase), and model size to decrease.

## **Code to reproduce the issue**

I am using [this](https://github.com/tensorflow/models/blob/master/research/tensorrt/tensorrt.py) script and a few helper functions from [here](https://github.com/tensorflow/tensorrt/blob/master/tftrt/examples/object_detection/graph_utils.py). The two exact scripts that I use are [do.py](https://github.com/tensorflow/tensorflow/files/3432597/do.py.txt) and [utilities.py](https://github.com/tensorflow/tensorflow/files/3432598/utilities.py.txt). Here are the [tiny model](https://drive.google.com/open?id=1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v) and the [big model](https://drive.google.com/open?id=19BzNDCHpDnxj9wU26BsGM4ewS9bKNmpO).

My command for running the experiments:
```bash
python do.py \
--frozen_graph=big-yolov3_frozen.pb \ # or tiny-yolov3_frozen.pb
--native --fp32 --fp16 --int8 \
--batch_size=32 \ # or 128 for tiny
--output_dir=/workspace \
--input_node=inputs --output_node=output_boxes
```

## **Other info / logs**

I ran a couple of experiments just to make sure that the results were consistent.

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 350.2,  mean: 348.0,    uncertainty: 1.4,       jitter: 5.1
  latency       median: 0.36551,        mean: 0.36846,  99th_p: 0.42946,        99th_uncertainty: 0.01453

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 340.9,  mean: 333.4,    uncertainty: 1.5,       jitter: 4.4
  latency       median: 0.37546,        mean: 0.38470,  99th_p: 0.47469,        99th_uncertainty: 0.06110

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 403.3,  mean: 402.3,    uncertainty: 0.6,       jitter: 3.6
  latency       median: 0.31740,        mean: 0.31824,  99th_p: 0.34266,        99th_uncertainty: 0.00263

==========================
network: tftrt_int8_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 417.7,  mean: 414.9,    uncertainty: 1.1,       jitter: 4.4
  latency       median: 0.30641,        mean: 0.30873,  99th_p: 0.35451,        99th_uncertainty: 0.01511

==========================
network: native_big-yolov3_frozen.pb,    batchsize 32, steps 100
  fps   median: 125.2,  mean: 124.7,    uncertainty: 0.3,       jitter: 1.4
  latency       median: 0.25553,        mean: 0.25677,  99th_p: 0.28257,        99th_uncertainty: 0.00308

==========================
network: tftrt_fp32_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 140.3,  mean: 140.2,    uncertainty: 0.4,       jitter: 1.9
  latency       median: 0.22802,        mean: 0.22839,  99th_p: 0.25419,        99th_uncertainty: 0.00890

==========================
network: tftrt_fp16_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 237.6,  mean: 242.5,    uncertainty: 1.4,       jitter: 5.4
  latency       median: 0.13469,        mean: 0.13245,  99th_p: 0.17733,        99th_uncertainty: 0.04387

==========================
network: tftrt_int8_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 210.1,  mean: 207.5,    uncertainty: 1.5,       jitter: 2.7
  latency       median: 0.15231,        mean: 0.15657,  99th_p: 0.16928,        99th_uncertainty: 0.16613
```

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 357.4,  mean: 354.3,    uncertainty: 1.7,       jitter: 14.5
  latency       median: 0.35814,        mean: 0.36215,  99th_p: 0.44575,        99th_uncertainty: 0.00629

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 324.9,  mean: 319.4,    uncertainty: 1.4,       jitter: 2.5
  latency       median: 0.39401,        mean: 0.40173,  99th_p: 0.49218,        99th_uncertainty: 0.06484

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 376.1,  mean: 372.8,    uncertainty: 1.1,       jitter: 1.7
  latency       median: 0.34036,        mean: 0.34363,  99th_p: 0.38601,        99th_uncertainty: 0.02051

==========================
network: tftrt_int8_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 392.1,  mean: 391.3,    uncertainty: 0.5,       jitter: 1.8
  latency       median: 0.32645,        mean: 0.32717,  99th_p: 0.33765,        99th_uncertainty: 0.01967

==========================
network: native_big-yolov3_frozen.pb,    batchsize 32, steps 100
  fps   median: 124.3,  mean: 124.0,    uncertainty: 0.4,       jitter: 1.7
  latency       median: 0.25737,        mean: 0.25842,  99th_p: 0.31292,        99th_uncertainty: 0.00355

==========================
network: tftrt_fp32_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 141.0,  mean: 140.7,    uncertainty: 0.3,       jitter: 0.3
  latency       median: 0.22690,        mean: 0.22761,  99th_p: 0.24239,        99th_uncertainty: 0.00581

==========================
network: tftrt_fp16_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 247.4,  mean: 245.9,    uncertainty: 1.0,       jitter: 4.4
  latency       median: 0.12934,        mean: 0.13044,  99th_p: 0.16018,        99th_uncertainty: 0.02011

==========================
network: tftrt_int8_big-yolov3_frozen.pb,        batchsize 32, steps 100
  fps   median: 206.0,  mean: 204.5,    uncertainty: 1.4,       jitter: 1.0
  latency       median: 0.15536,        mean: 0.15885,  99th_p: 0.16454,        99th_uncertainty: 0.17423
```

**Comment by aaroey** [comment] 2019-07-31 20:42
Hi @pooyadavoodi, would you help to take a look at this?

**Comment by pooyadavoodi** [comment] 2019-08-01 23:22
@nseidl Is this a duplicate of https://github.com/tensorflow/tensorflow/issues/30717 ?

**Comment by nseidl** [comment] 2019-08-02 00:50
> @nseidl Is this a duplicate of #30717 ?

Yes. Would you prefer to continue the thread in this issue or in #30717? I'd prefer to use this one (#31039)

**Comment by nseidl** [comment] 2019-08-02 04:38
From the default nvidia19.02 container, I had to install the cuDNN v7.6.0 because `tf-nightly-gpu==1.15.0.dev20190801` complained about the default installed cuDNN v7.4.2 not being new enough, to match the v7.6.0 that the `tf-nightly-gpu` was built with.

CUDA 10.0, cuDNN 7.6.0, Nvidia Driver 410.104, Python 3.5.2

```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.12.1-7676-g4157717 1.15.0-dev20190801
```

Proceeding with `tf-nightly-gpu==1.15.0.dev20190801`, I found there to be negligible fps increase.

```
python do.py --frozen_graph=tiny-yolov3_frozen.pb --native --fp32 --fp16 --output_dir=/workspace --input_node=inputs --output_node=output_boxes

python do.py --frozen_graph=big-yolov3_frozen.pb --native --fp32 --fp16 --output_dir=/workspace --input_node=inputs --output_node=output_boxes
```

```
==========================
network: native_tiny-yolov3_frozen.pb,   batchsize 128, steps 100
  fps   median: 862.1,  mean: 841.4,    uncertainty: 6.7,       jitter: 91.7
  latency       median: 0.14848,        mean: 0.15314,  99th_p: 0.19557,        99th_uncertainty: 0.00155

==========================
network: tftrt_fp32_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 888.7,  mean: 865.6,    uncertainty: 7.8,       jitter: 55.0
  latency       median: 0.14408,        mean: 0.14938,  99th_p: 0.19656,        99th_uncertainty: 0.02804

==========================
network: tftrt_fp16_tiny-yolov3_frozen.pb,       batchsize 128, steps 100
  fps   median: 864.9,  mean: 845.8,    uncertainty: 4.5,       jitter: 7.2
  latency       median: 0.14799,        mean: 0.15179,  99th_p: 0.17967,        99th_uncertainty: 0.01009

==========================
network: native_big-yolov3_frozen.pb,    batchsize 128, steps 100
  fps   median: 161.4,  mean: 160.2,    uncertainty: 0.4,       jitter: 0.2
  latency       median: 0.79308,        mean: 0.79935,  99th_p: 0.85455,        99th_uncertainty: 0.07410

==========================
network: tftrt_fp32_big-yolov3_frozen.pb,        batchsize 128, steps 100
  fps   median: 163.7,  mean: 162.7,    uncertainty: 0.4,       jitter: 0.3
  latency       median: 0.78213,        mean: 0.78730,  99th_p: 0.89013,        99th_uncertainty: 0.08374

==========================
network: tftrt_fp16_big-yolov3_frozen.pb,        batchsize 128, steps 100
  fps   median: 166.3,  mean: 166.2,    uncertainty: 0.1,       jitter: 0.2
  latency       median: 0.76969,        mean: 0.77026,  99th_p: 0.79509,        99th_uncertainty: 0.00254
```

So, I then ran just FP16 and recorded the output. It looks like there's a problem converting `LeakyRelu`, and this causes some TensorRT nodes to not be created. This would explain the negligible FPS increase, I think.

```
WARNING: Logging before flag parsing goes to stderr.
W0802 04:02:24.227455 140013164369664 module_wrapper.py:136] From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0802 04:02:25.165457 140013164369664 deprecation.py:323] From do.py:67: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
W0802 04:02:25.165779 140013164369664 module_wrapper.py:136] From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

2019-08-02 04:02:25.273736: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.5
I0802 04:02:25.273825 140013164369664 trt_convert.py:195] Linked TensorRT version: (5, 1, 5)
I0802 04:02:25.273978 140013164369664 trt_convert.py:196] Loaded TensorRT version: (5, 0, 2)
W0802 04:02:25.274046 140013164369664 trt_convert.py:212] TensorRT mismatch. Compiled against version 5.1.5, but loaded 5.0.2. Things may not work
2019-08-02 04:02:25.527247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-08-02 04:02:26.502815: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-02 04:02:26.502918: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-02 04:02:26.503307: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-08-02 04:02:26.517468: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2019-08-02 04:02:26.521001: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5df5f50 executing computations on platform Host. Devices:
2019-08-02 04:02:26.521030: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-08-02 04:02:26.911246: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5e59340 executing computations on platform CUDA. Devices:
2019-08-02 04:02:26.911319: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2019-08-02 04:02:26.912403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-08-02 04:02:26.912458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 04:02:26.912480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-02 04:02:26.913735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-02 04:02:26.913986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-02 04:02:26.915425: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-02 04:02:26.916453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-02 04:02:26.916493: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-02 04:02:26.917990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-02 04:02:26.918019: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 04:02:27.083314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-02 04:02:27.083374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-02 04:02:27.083383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-02 04:02:27.085486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30420 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2019-08-02 04:02:27.434240: I tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:213] Specified max_batch_size=128 is larger than maximum batch dimension of inputs (1). This can result in poor performance.
2019-08-02 04:02:27.524490: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:460] There are 9 ops of 6 different types in the graph that are not converted to TensorRT: ResizeNearestNeighbor, ConcatV2, SplitV, Conv2D, NoOp, Placeholder, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
2019-08-02 04:02:27.528748: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:633] Number of TensorRT candidate segments: 6
2019-08-02 04:02:27.587194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.5
2019-08-02 04:02:27.611198: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.5
2019-08-02 04:02:27.611805: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/Network.cpp::addActivation::89, condition: int(type) >= 0 && int(type) < EnumMax<ActivationType>()
2019-08-02 04:02:27.611849: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:737] TensorRT node TRTEngineOp_0 added for segment 0 consisting of 82 nodes failed: Internal: TFTRT::ConvertLeakyRelu:2886 failed to add TRT layer, at: detector/tiny-yolo/Conv/LeakyRelu. Fallback to TF...
2019-08-02 04:02:29.753906: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_1 added for segment 1 consisting of 4 nodes succeeded.
2019-08-02 04:02:29.881641: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node TRTEngineOp_2 added for segment 2 consisting of 4 nodes succeeded.
2019-08-02 04:02:29.886954: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/Network.cpp::addActivation::89, condition: int(type) >= 0 && int(type) < EnumMax<ActivationType>()
2019-08-02 04:02:29.887002: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:737] TensorRT node detector/tiny-yolo/TRTEngineOp_3 added for segment 3 consisting of 54 nodes failed: Internal: TFTRT::ConvertLeakyRelu:2886 failed to add TRT layer, at: detector/tiny-yolo/Conv_6/LeakyRelu. Fallback to TF...
2019-08-02 04:02:29.894176: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/Network.cpp::addActivation::89, condition: int(type) >= 0 && int(type) < EnumMax<ActivationType>()
2019-08-02 04:02:29.894212: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:737] TensorRT node detector/tiny-yolo/TRTEngineOp_4 added for segment 4 consisting of 25 nodes failed: Internal: TFTRT::ConvertLeakyRelu:2886 failed to add TRT layer, at: detector/tiny-yolo/Conv_11/LeakyRelu. Fallback to TF...
2019-08-02 04:02:30.350996: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node detector/tiny-yolo/TRTEngineOp_5 added for segment 5 consisting of 29 nodes succeeded.
2019-08-02 04:02:30.508788: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2019-08-02 04:02:30.524988: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2019-08-02 04:02:30.540291: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2019-08-02 04:02:30.552068: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-08-02 04:02:30.552096: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 171 nodes (-129), 186 edges (-130), time = 142.977ms.
2019-08-02 04:02:30.552103: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 223 nodes (52), 238 edges (52), time = 53.212ms.
2019-08-02 04:02:30.552121: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 223 nodes (0), 238 edges (0), time = 40.421ms.
2019-08-02 04:02:30.552131: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 189 nodes (-34), 198 edges (-40), time = 2938.43091ms.
2019-08-02 04:02:30.552138: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 181 nodes (-8), 194 edges (-4), time = 113.943ms.
2019-08-02 04:02:30.552175: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: detector/tiny-yolo/TRTEngineOp_5_native_segment
2019-08-02 04:02:30.552182: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 38 nodes (0), 37 edges (0), time = 2.783ms.
2019-08-02 04:02:30.552188: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 38 nodes (0), 37 edges (0), time = 0.842ms.
2019-08-02 04:02:30.552194: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 38 nodes (0), 37 edges (0), time = 2.768ms.
2019-08-02 04:02:30.552200: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 38 nodes (0), 37 edges (0), time = 0.126ms.
2019-08-02 04:02:30.552206: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 38 nodes (0), 37 edges (0), time = 2.669ms.
2019-08-02 04:02:30.552212: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: TRTEngineOp_2_native_segment
2019-08-02 04:02:30.552218: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.021ms.
2019-08-02 04:02:30.552224: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 8 nodes (0), 8 edges (0), time = 0.199ms.
2019-08-02 04:02:30.552229: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.1ms.
2019-08-02 04:02:30.552235: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 8 nodes (0), 8 edges (0), time = 0.058ms.
2019-08-02 04:02:30.552241: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.213ms.
2019-08-02 04:02:30.552247: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: TRTEngineOp_1_native_segment
2019-08-02 04:02:30.552253: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.031ms.
2019-08-02 04:02:30.552259: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 8 nodes (0), 8 edges (0), time = 0.189ms.
2019-08-02 04:02:30.552265: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.102ms.
2019-08-02 04:02:30.552271: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 8 nodes (0), 8 edges (0), time = 0.05ms.
2019-08-02 04:02:30.552293: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 8 nodes (0), 8 edges (0), time = 2.086ms.
W0802 04:02:30.686552 140013164369664 module_wrapper.py:136] From /usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

I0802 04:02:30.790657 140013164369664 do.py:122] Starting execution
W0802 04:02:31.761751 140013164369664 deprecation.py:323] From do.py:118: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
2019-08-02 04:02:35.895788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-08-02 04:02:35.895893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-02 04:02:35.895905: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-02 04:02:35.895919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-02 04:02:35.895929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-02 04:02:35.895939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-02 04:02:35.895948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-02 04:02:35.895957: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-02 04:02:35.896887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-02 04:02:35.896929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-02 04:02:35.896937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-02 04:02:35.896943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-02 04:02:35.897987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30420 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
I0802 04:02:35.900057 140013164369664 do.py:141] Starting Warmup cycle
2019-08-02 04:06:27.600120: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
I0802 04:06:29.636768 140013164369664 do.py:146] Starting timing.
I0802 04:06:45.426122 140013164369664 do.py:153] Timing loop done!
Running FP16 graph
```

**Comment by pooyadavoodi** [comment] 2019-09-16 17:31
This is the error with LeakyRelu:
`2019-08-02 04:02:27.611805: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Parameter check failed at: ../builder/Network.cpp::addActivation::89, condition: int(type) >= 0 && int(type) < EnumMax<ActivationType>()
2019-08-02 04:02:27.611849: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:737] TensorRT node TRTEngineOp_0 added for segment 0 consisting of 82 nodes failed: Internal: TFTRT::ConvertLeakyRelu:2886 failed to add TRT layer, at: detector/tiny-yolo/Conv/LeakyRelu. Fallback to TF...
`
I think this is happening because the version of loaded TensorRT is different from the version used in TF compilation according to the log:
```
I0802 04:02:25.273825 140013164369664 trt_convert.py:195] Linked TensorRT version: (5, 1, 5)
I0802 04:02:25.273978 140013164369664 trt_convert.py:196] Loaded TensorRT version: (5, 0, 2)
W0802 04:02:25.274046 140013164369664 trt_convert.py:212] TensorRT mismatch. Compiled against version 5.1.5, but loaded 5.0.2. Things may not work
```

TensorRT 5.1 added a bunch of new activation types:
- TensorRT 5.0: https://docs.nvidia.com/deeplearning/sdk/tensorrt-archived/tensorrt-502/tensorrt-api/c_api/namespacenvinfer1.html#acbd177748000d30ae0277ee980757eb6
- TensorRT 5.1 https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/namespacenvinfer1.html#acbd177748000d30ae0277ee980757eb6


This kind of version mismatch will be prevented in the future: https://github.com/tensorflow/tensorflow/commit/03b6d1c6986aa62993e46114be56d9ec3276e3aa

@nseidl Please use the same version of TensorRT in compilation and loading.

**Comment by reactivetype** [comment] 2019-11-19 23:00
@pooyadavoodi Has this issue been fixed? Or is still a problem? How about TF2.0 models or models compiled with TensorRT 6.0?

**Comment by yuanzhedong** [comment] 2020-02-22 04:42
Hi @reactivetype did you try TensorRT 6.0.1 through the docker from nvcr or?

**Comment by tensorflowbutler** [comment] 2021-06-10 18:13
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Closed** 2021-06-17 19:22 UTC
Labels: comp:gpu, comp:gpu:tensorrt, type:bug
