### ISSUE TITLE
GPU implementation for RangeSampler and related samplers

### ISSUE THREAD

**Issue by siddharth-agrawal** [tensorflow/tensorflow#3345] opened 2016-07-16 17:21 UTC
The implementation for `RangeSampler` currently works only for the CPU, even though the sampling is done using `SimplePhilox` in most cases (which has GPU support). This issue is for tracking all changes to enable GPU support for the samplers.

This issue came into picture while digging for #1140, and affects it directly. Once GPU implementations are written for the samplers related to `RangeSampler`, float64 can easily be enabled for the `*Sampler` ops mentioned [here](https://github.com/tensorflow/tensorflow/issues/1140#issuecomment-227012645).  Some more context can be found in [this comment](https://github.com/tensorflow/tensorflow/issues/1140#issuecomment-232891827).

**Comment by aselle** [comment] 2017-06-14 01:37
Automatically closing due to lack of recent activity. Please file a new issue referring to this issue, if the issue is still relevant and important. If this is documenting some kind of bug, be sure to use the latest version of TensorFlow. Thank you so much.

**Closed by aselle** 2017-06-14 01:37 UTC
Labels: stat:contributions welcome
