### ISSUE TITLE
Importing Tensorflow - DLL load failed: the specified procedure could not be found

### ISSUE THREAD

**Issue by sandrodelrivo** [tensorflow/tensorflow#22845] opened 2018-10-09 17:57 UTC
I'm creating a basic project in PyCharm 2018.2.4, importing tensor flow (version 1.10.0 installed using pip) , and I get this error:

`Traceback (most recent call last):
  File "C:/Users/sandr/Desktop/TensorProj/testing.py", line 1, in <module>
    import tensorflow
  File "C:\Users\sandr\.virtualenvs\TensorProj-uBuGaj5e\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\sandr\.virtualenvs\TensorProj-uBuGaj5e\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\sandr\.virtualenvs\TensorProj-uBuGaj5e\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\sandr\.virtualenvs\TensorProj-uBuGaj5e\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.`

Tried a whole bunch of different versions, but nothing is working. Could anyone help me out?

**Comment by tensorflowbutler** [comment] 2018-10-10 01:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-10 23:39
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sandrodelrivo** [comment] 2018-10-12 17:56
The tensorflow version was 1.10.0. I installed from the command 'pip install --uprade tensorflow' in the PyCharm terminal.

I am running Windows 10 (Version 10.0.17134 Build 17134). My CPU is an Intel Core i5-5200 CPU, integrated GPU.

**Comment by ymodak** [comment] 2018-10-12 18:18
What is the python version using?

**Comment by sandrodelrivo** [comment] 2018-10-12 18:41
Python version 3.6.0. pip3 install tensorflow for version 1.10 gave me the same error.

**Comment by ymodak** [comment] 2018-10-15 17:10
Please refer to a similar [issue](https://github.com/protocolbuffers/protobuf/issues/5062). Can you please try updating your python version to 3.6.1 and check if the issue still persists?

**Comment by ymodak** [comment] 2018-10-22 16:32
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-22 16:32 UTC
Labels: stat:awaiting response, type:build/install
