### ISSUE TITLE
1.13.1 wheels for Python 3.7 do not work on RHEL/CentOS7

### ISSUE THREAD

**Issue by dverstap** [tensorflow/tensorflow#26826] opened 2019-03-18 10:13 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RedHat Enterprise Linux 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: 2.7.2
- Installed using virtualenv? pip? conda?: virtualenv+pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

We noticed that TensorFlow 1.13.1 now comes with wheels for Python 3.7 as well:

tensorflow-1.13.1-cp37-cp37m-manylinux1_x86_64.whl

We first upgraded to 1.13.1 on our existing Python 3.6, which worked
fine. Then we tried upgrading to Python 3.7, but even importing
tensorflow fails there, because the shared libraries need a newer
libstdc++:

E   ImportError: Traceback (most recent call last):
E     File "/home/anon/git/sensors/venv3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "/home/anon/git/sensors/venv3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "/home/anon/git/sensors/venv3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "/opt/anon/python-3.7.2-master-201903180831/lib/python3.7/imp.py", line 242, in load_module
E       return load_dynamic(name, filename, file)
E     File "/opt/anon/python-3.7.2-master-201903180831/lib/python3.7/imp.py", line 342, in load_dynamic
E       return _load(spec)
E   ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/anon/git/sensors/venv3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
E   
E   
E   Failed to load the native TensorFlow runtime.
E   
E   See https://www.tensorflow.org/install/errors
E   
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.

This is error is logical, because RHEL/CentOS 7 only has support for 1.3.7 and earlier:

(venv3) [anon@vdesk sensors]$ uname -a 
Linux vdesk.localdomain 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
(venv3) [anon@vdesk sensors]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
(venv3) [anon@vdesk sensors]$ strings /lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
(venv3) [anon@vdesk sensors]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

If you unzip the 3.6 and 3.7 wheels for TF 1.13.1, you can see that the 3.6 wheel is compiled on Ubuntu 14.04 with GCC 4.8:

[anon@vdesk python]$ strings python36/tensorflow-1.13.1.data/purelib/tensorflow/libtensorflow_framework.so | grep -i ubuntu
GCC: (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5

and the 3.7 wheel is compiled on Ubuntu 16.04 with GCC 5.4:

[anon@vdesk python]$ strings python37/tensorflow-1.13.1.data/purelib/tensorflow/libtensorflow_framework.so | grep -i ubuntu
GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

RHEL/CentOS 7 also has GCC 4.8.x, so that's why the Python 3.6 wheels work.

Is there any chance you could build the Python 3.7 wheels on Ubuntu 14.04 as well?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Just importing tensorflow; works fine with the Python3.6 wheels.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by chwang85** [comment] 2019-03-18 15:37
I also got this issue (TF 1.13, CentOS 7, CUDA 10, python 3.7), which is caused by a old glibc version. 
Are you sure it works on python 3.6?

**Comment by dverstap** [comment] 2019-03-18 17:38
Yes, it works with python 3.6, because those binaries are built on Ubuntu 14.04 with same version of GCC. I use the CPU version of TF though, so perhaps it's different for the GPU version ...

**Comment by chwang85** [comment] 2019-03-18 21:46
It seems that TF for Python 3.7 are built on Ubuntu 16, and TF for Python 3.6 and lower are built on Ubuntu 14. 
Ubuntu 16's glibc is higher than Ubuntu 14, which is the same as CentOS 7.

**Comment by gunan** [comment] 2019-03-20 04:29
Correct, we had to build our python 3.7 binaries on ubuntu 16, because we were not able to setup python 3.7 fully on ubuntu 14. We had to disable ssl, which caused our builds to fail.
We are exploring builds on CentOS, but I cannot offer an immediate solution for prebuilt binaries.
You should be able to build TF from sources on CentOS for a quick solution.

**Comment by jvishnuvardhan** [comment] 2019-08-09 22:33
@dverstap Is this still an issue? Did you try the workaround suggested by @gunan. Please close the issue, if it was already resolved. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-08-16 20:32
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-08-16 20:32 UTC
Labels: subtype:centos, type:build/install
