### ISSUE TITLE
FLOP calculation by tf.profiler might be wrong

### ISSUE THREAD

**Issue by benmyara** [tensorflow/tensorflow#19746] opened 2018-06-04 12:59 UTC
Have I written custom code: Yes
OS Platform and Distribution: macOS 10.11.13
TensorFlow installed from: pip 
TensorFlow version: 1.6.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: see code below

```
import tensorflow as tf
g = tf.Graph()
with g.as_default():
    m, p, q = 25, 16, 9
    A = tf.Variable(tf.zeros([m, p]))
    B = tf.Variable(tf.zeros([p, q]))
    C = tf.matmul(A,B)

    flops = tf.profiler.profile(g, options = tf.profiler.ProfileOptionBuilder.float_operation())
    if flops is not None:
        print('FLOP should be', m * q * (2 * p - 1))
        print('Calculated FLOP', flops.total_float_ops)
```

Given two matrices `A` of shape `(m, p)` and `B` of shape `(p, q)`, the number of floating point operations (FLOP) should be `mq(2p-1)`.

Calculating the number of FLOP using tensorflow's profiler gives `2mqp` instead of `mq(2p-1)`.

**Comment by tensorflowbutler** [comment] 2018-06-05 00:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karmel** [comment] 2018-06-05 17:28
Have you read the caveats on [floating point profiling](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/g3doc/profile_model_architecture.md#profile-model-float-operations)? It looks like some of these may apply to your case?

**Comment by karmel** [comment] 2018-06-05 18:39
As the docs note, contributions here would be welcome. Are you interested in looking into this issue?

**Comment by benmyara** [comment] 2018-06-05 20:38
I'll try to find some time and update this issue accordingly.

**Comment by ppwwyyxx** [comment] 2018-06-05 20:48
https://github.com/tensorflow/tensorflow/blob/397f04acb1faeff451691d7fdc0f754eeb547cc1/tensorflow/python/ops/math_ops.py#L2023-L2036

**Comment by tensorflowbutler** [comment] 2018-06-20 18:40
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-05 18:44
Nagging Assignee @karmel: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-20 12:49
Nagging Assignee @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-04 18:40
Nagging Assignee @karmel: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-19 18:48
Nagging Assignee @karmel: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-03 18:38
Nagging Assignee @karmel: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-18 19:03
Nagging Assignee @karmel: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-09 18:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-24 12:40
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-10-26 21:09
Closing due to staleness. Please use the latest version for TensorFlow and test again. Feel free to open a new issue if it still persists. Thanks!

**Closed by ymodak** 2018-10-26 21:09 UTC
Labels: stat:awaiting response

**Comment by moboehle** [comment] 2018-10-27 11:50
@benmyara I came across the same issue and I think the issue is related to the fact that you need to store the results somewhere, at least this is the explanation that I came up with. 
You initialize a result matrix filled with zeros and then you add to each entry the result of the row x column multiplication. This way, one entry of the result matrix requires p multiplications, which are summed using p-1 summations. By adding it to the result matrix, you obtain one additional flop, yielding
 ```
flops per entry = p + p - 1 + 1 = 2 p
```
Given the shape of the result matrix, you obtain a total of 2mpq flops.
