### ISSUE TITLE
Why this simple code causes RAM memory leak? tf.shuffle seems not release memory.

### ISSUE THREAD

**Issue by kindernerd** [tensorflow/tensorflow#35132] opened 2019-12-15 11:33 UTC
**System information**
- OS Platform and Distribution Linux Ubuntu 16.04
- Python: 2.7.17 / 3.7.5
- Tensorflow: 1.12.0 / 1.15.0
- Numpy: 1.16.5
- GPU: GeForce RTX 2080 Ti
- CUDA: 9.2

**Describe the current behavior**
CPU memory gradually increase after each epoch until the program restarts, i suspect that dataset.shuffle doesn't release the buffer memory. Tested with tf 1.15, same situation.

**Code to reproduce the issue**
```
import gc
import numpy as np
import tensorflow as tf
def datagenerator():
    for i in range(250):
        for j in range(100):
            yield 'a','b',np.random.randn(300,120)
def f(s1,s2,feat):
    return s1,s2,feat
dataset = tf.data.Dataset.from_generator(datagenerator, (tf.string,tf.string,tf.float32))
dataset = dataset.shuffle(20000)
dataset = dataset.batch(200, drop_remainder=True)
dataset = dataset.map(f)
test_iter = dataset.make_initializable_iterator()
test_next = test_iter.get_next()   

run_config = tf.ConfigProto()
run_config.gpu_options.allow_growth = True
with tf.Session(config=run_config) as sess:

    for i in range(100):

        sess.run(test_iter.initializer)
        
        while True:
            try:
                loss_list = sess.run([test_next])
                print(len(loss_list[0]))
            except tf.errors.OutOfRangeError:
                print("train epoch %d finish" % (i+1))
                break
        gc.collect()
```

**Comment by gadagashwini** [comment] 2019-12-16 08:53
@kindernerd, Is this similar [#34942](https://github.com/tensorflow/tensorflow/issues/34942) issue.

**Comment by gadagashwini** [comment] 2019-12-27 10:01
@kindernerd, Can you please let us know if you are happy to close if its duplicate of [#34942](https://github.com/tensorflow/tensorflow/issues/34942) issue.

**Comment by kindernerd** [comment] 2019-12-27 10:59
> @kindernerd, Can you please let us know if you are happy to close if its duplicate of [#34942](https://github.com/tensorflow/tensorflow/issues/34942) issue.

ok, sorry for the  duplication

**Closed** 2019-12-27 11:00 UTC
Labels: TF 1.15, comp:data, stat:awaiting response, type:performance
