### ISSUE TITLE
Error building custom op

### ISSUE THREAD

**Issue by zendevil** [tensorflow/tensorflow#42523] opened 2020-08-20 18:40 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): tensorflow/tensorflow docker image on macOS Catalina
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.0
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
```
# g++ -I /usr/local/lib/python3.6/dist-packages/tensorflow/include disparity_prop.cc

/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccyNizdq.o: In function `__static_initialization_and_destruction_0(int, int)':
disparity_prop.cc:(.text+0x5a7): undefined reference to `tensorflow::register_op::OpDefBuilderReceiver::OpDefBuilderReceiver(tensorflow::register_op::OpDefBuilderWrapper<true> const&)'
/tmp/ccyNizdq.o: In function `tensorflow::OpRegistrationData::~OpRegistrationData()':
disparity_prop.cc:(.text._ZN10tensorflow18OpRegistrationDataD2Ev[_ZN10tensorflow18OpRegistrationDataD5Ev]+0x26): undefined reference to `tensorflow::OpDef::~OpDef()'
/tmp/ccyNizdq.o: In function `tensorflow::register_op::OpDefBuilderWrapper<true>::OpDefBuilderWrapper(char const*)':
disparity_prop.cc:(.text._ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EEC2EPKc[_ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EEC5EPKc]+0x52): undefined reference to `tensorflow::OpDefBuilder::OpDefBuilder(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccyNizdq.o: In function `tensorflow::register_op::OpDefBuilderWrapper<true>::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
disparity_prop.cc:(.text._ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x4d): undefined reference to `tensorflow::OpDefBuilder::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccyNizdq.o: In function `tensorflow::register_op::OpDefBuilderWrapper<true>::Output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
disparity_prop.cc:(.text._ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x4d): undefined reference to `tensorflow::OpDefBuilder::Output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccyNizdq.o: In function `tensorflow::register_op::OpDefBuilderWrapper<true>::SetShapeFn(std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)>)':
disparity_prop.cc:(.text._ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE10SetShapeFnESt8functionIFNS_6StatusEPNS_15shape_inference16InferenceContextEEE[_ZN10tensorflow11register_op19OpDefBuilderWrapperILb1EE10SetShapeFnESt8functionIFNS_6StatusEPNS_15shape_inference16InferenceContextEEE]+0x4d): undefined reference to `tensorflow::OpDefBuilder::SetShapeFn(std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)>)'
/tmp/ccyNizdq.o: In function `tensorflow::core::RefCounted::~RefCounted()':
disparity_prop.cc:(.text._ZN10tensorflow4core10RefCountedD2Ev[_ZN10tensorflow4core10RefCountedD5Ev]+0xf4): undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
disparity_prop.cc:(.text._ZN10tensorflow4core10RefCountedD2Ev[_ZN10tensorflow4core10RefCountedD5Ev]+0x11c): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccyNizdq.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
disparity_prop.cc:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x33): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
disparity_prop.cc:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x5d): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::ForVar2()'
disparity_prop.cc:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x7b): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
disparity_prop.cc:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x8a): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
disparity_prop.cc:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0xad): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
collect2: error: ld returned 1 exit status
```
**Describe the expected behavior**
The .cc source should compile successfully. 

**Standalone code to reproduce the issue**
```
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"

using namespace tensorflow;


class DisparityPropOp : public OpKernel {
public:
  explicit DisparityPropOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);

    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));
  }
};

//REGISTER_KERNEL_BUILDER(Name("DisparityProp").Device(DEVICE_CPU), DisparityPropOp);

// Disparity propagation
REGISTER_OP("DisparityProp")
.Input("to_disparity_prop: float32")
.Output("disparity_proped: float32")
.SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
              c->set_output(0, c->input(0));
              return Status::OK();
            });
```

**Comment by ravikyram** [comment] 2020-08-21 05:18
@zendevil 

Looks like duplicate of #42524. Can we close the issue here and can track the issue in #42524 
Thanks!

**Closed** 2020-09-04 05:22 UTC
Labels: TF 2.3, stalled, stat:awaiting response, type:bug
