### ISSUE TITLE
CMake Build Error for Computing Capability 2.1

### ISSUE THREAD

**Issue by jithurjacob** [tensorflow/tensorflow#6262] opened 2016-12-12 06:46 UTC
Thanks a lot guys for giving support to windows 💯 

But since I'm having an old GPU(Nvidia 610M) with computing capabilty 2.1 I'm unable to use GPU. Is it possible to run Tensorflow on this GPU???

For trying my luck, I followed instructions from this [comment](https://github.com/tensorflow/tensorflow/issues/6001#issuecomment-264263354) and this cmake [instruction](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) but I'm running into build errors.

Environment : Windows 10 Pro 1607 64 Bit & Nvidia 610M with Python 3.5, Visual Studio 2015, CUDA 8

I got build error on both MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj and MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj  

Please help me in compiling for this GPU or it would be great if someone could share the whl.
Thank you
![image](https://cloud.githubusercontent.com/assets/7101452/21090262/7b50fe1e-c064-11e6-86f0-0337ae526768.png)

**Comment by Carmezim** [comment] 2016-12-12 15:18
1. TensorFlow supports CUDA 8.0 and cuDNN 5.1 on Windows. If your GPU is compatible with those requirements there should be no problem regarding the GPU. 
2. Two weeks ago TensorFlow released 0.12 version already providing a pip package. [Visit here and follow the instructions to install TensorFlow with pip](https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation-on-windows).

**Comment by mrry** [comment] 2016-12-12 20:09
Compute capability 2.1 isn't supported by our pre-built binaries: the 0.12.0rc0 supports 3.5 and 5.2, and future binaries (and nightly builds) support 3.0, 

Can you share the entire logs from `MSBuild` (e.g. as a gist)? It appears from the errors at the bottom that one of the code generators failed to build, but the error itself was lost.

**Comment by jithurjacob** [comment] 2016-12-13 06:35
Please find the gist [here](https://gist.github.com/jithurjacob/630c99c0d6033fff1cdda886e2ddb044)

**Comment by mrry** [comment] 2016-12-13 06:41
Looking at the error, it seems like `gen_git_source.py` is failing on [this line](https://github.com/tensorflow/tensorflow/blob/6dc7f989f10ceb4cc6b19e627ab742e02a0787b7/tensorflow/tools/git/gen_git_source.py#L150), where it tries to run `git`. Is it possible that `git` isn't in a directory in your `%PATH%` environment variable?

**Comment by jithurjacob** [comment] 2016-12-13 07:17
Thanks a lot for your help it was the reason. Here is an updated [gist](https://gist.github.com/jithurjacob/a9dc4b3b5001a21f3b1992f74cde577b)

**Comment by mrry** [comment] 2016-12-13 15:42
It looks like the error is caused by the use of `__shfl_down()`, support for which was [added in Compute Capability 3.x devices](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#warp-shuffle-functions). Since we don't officially support these older devices, I doubt that we will add a workaround for your GPU, although it may be possible to get TensorFlow to build by disabling kernels that use this feature.

@benoitsteiner Do you happen to know which Eigen-based kernels make use of Compute Capability 3.x features? Or are there any `#define`s that could make the build work for @jithurjacob's older CC 2.1 GPU?

**Comment by benoitsteiner** [comment] 2016-12-15 21:15
We use `__shfl_down()` for contractions. It's not clear why this code is instantiated when compiling reductions on Windows: this doesn't happen on Linux for example.

**Comment by tfboyd** [comment] 2017-06-16 17:17
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Closed by tfboyd** 2017-06-16 17:17 UTC
Labels: stat:community support
