### ISSUE TITLE
Strange behavior and verbosity in Tensorboard for RNN

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#602] opened 2015-12-23 18:31 UTC
I only have one encoder, but it lists 50+ encoder variables in the side bar (see attached). This also happens for my decoder. I presume that it is duplicating the variables for each time step? Notice that it says 500+ inputs!

Also, the graph becomes unwieldy and barely loaded in Safari (crashed in Chrome, wouldn't load in Firefox), and is displayed with a <i>very</i> long list of variable names (see attached).

![tf1](https://cloud.githubusercontent.com/assets/1364252/11982491/e9e57346-a968-11e5-9d05-1c6e6faded1e.jpg)
![tf2](https://cloud.githubusercontent.com/assets/1364252/11982496/eceb63ca-a968-11e5-9c59-3960f635f653.jpg)

**Comment by MarkDaoust** [comment] 2015-12-30 00:57
Does the graph tab ever render in Firefox? See issue #650.

**Comment by girving** [comment] 2016-03-08 21:08
Looks like this fell through the cracks.  @danmane: Any thoughts?

**Comment by danmane** [comment] 2016-03-15 00:25
@dsmilkov and @jameswex are point people on graph visualizer issues - I know we've fixed a few issues of this general form, but automatic grouping for repeated nodes isn't perfect yet. Can one of you comment if we should close this issue? Also, would grouping all of these ops under a shared namespace help, or just kick the problem down into a new unmanagably massive namespace?

**Comment by jameswex** [comment] 2016-03-15 00:44
What is the code that creates all of the encoder[num] ops? The graph visualizer will automatically group together nodes that are of the form [name]_[num], but these don't have an underscore between name and num.

When using tensorflow to create an op a number of times with the same name for the op each time, tensorflow will automatically add _[num] to each of the created ops after the first one.

**Comment by jstaker7** [comment] 2016-03-15 19:40
If I remember correctly I generated these graphs using the initial 0.5 release and I added monitoring to variables in the Seq2Seq example. So I believe the encoder[num] ops were generated simply from the RNN cells (LSTM as part of a MultiRNN object, I think) that were part of that example.

**Comment by jameswex** [comment] 2016-03-15 19:46
Do you happen to have this graph created with a more-recent release? If so, does the problem exist? Do you have the code you added to the example that I could take a look at?

**Comment by jstaker7** [comment] 2016-03-23 21:54
Unfortunately, I didn't keep the code or model that I used to generate the images. I'm working on a small script that can hopefully reproduce the problem, but just a simple RNN so far has the clean output you had suggested. Maybe this happens when generating a sequence using an RNN with an output projection layer (like in the seq2seq translate tutorial), or when when using an embedding (multi-dimensional output sequences). Sorry I haven't been able to provide much help on diagnosising the root cause. I'll do a few more tests to see if I can reproduce the problem and get back to you.

**Comment by danmane** [comment] 2016-04-15 21:53
I'm going to close this for now since we don't have a repro and we don't know if it is still reproducing. @jstaker7 please re-open if you find a repro.

**Closed by danmane** 2016-04-15 21:53 UTC
