### ISSUE TITLE
Maybe bug in quantize_graph.py

### ISSUE THREAD

**Issue by orshi** [tensorflow/tensorflow#16390] opened 2018-01-25 04:23 UTC
In line 489 of quantize_graph.py
```python
def quantize_nodes_recursively(self, current_node):
    """The entry point for quantizing nodes to eight bit and back."""
    if self.already_visited[current_node.name]:
      return
```
The initial value of dic *self.already_visited* is empty ,so the statement
```python
if self.already_visited[current_node.name]:
```
may raise exception.
So I think it would be better to update to ：
```python
if self.already_visited.has_key(current_node.name):
``` 
Same issue also in ：
```python
def round_nodes_recursively(self, current_node)
```
Please take a look, thanks!

**Comment by tensorflowbutler** [comment] 2018-01-25 09:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qmick** [comment] 2018-01-25 11:29
Yes, I can produce the error. It's quite strange that we do not have a test case of `GraphRewriter` with `mode=quantize`.
`round_nodes_recursively` do not have this issue since it test whether keys are in dict firstly.

**Comment by qmick** [comment] 2018-01-25 13:59
Found some discussion here #8999. It seems this python script is dprecated and the new [Graph Transform Tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms/#eight-bit-calculations) is recommended. Maybe we can close this issue now.

**Comment by tensorflowbutler** [comment] 2018-02-09 19:13
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-03 07:51
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-17 15:01
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-01 12:33
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:48
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Closed** 2018-04-18 19:47 UTC
Labels: stat:awaiting response
