### ISSUE TITLE
InaccessibleTensorError in graph mode with for loop itteration (different sized tensors) ( tf.image.resize)

### ISSUE THREAD

**Issue by bela127** [tensorflow/tensorflow#37444] opened 2020-03-09 13:15 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): custom Layer, using tf.image.resize
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Linux Mint 19.3 Cinnamon (Ubuntu based)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: No
- TensorFlow installed from (source or
binary): pip install
 - TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.6.9

Problem:
Not sure if its a bug, or i misused something
but i expected autograph to do a loop unrolling once, and later work with the tensors created in the unrolled loop.

**Describe the current behavior**
in graph mode (tf.function) InaccessibleTensorError is thrown if tf.image.resize is used in loop

**Describe the expected behavior**
should work as in eager mode

**Standalone code to reproduce the issue** 
```
import tensorflow as tf 

def main():
    execute_eager = False
    test_nr = 2
    tf.config.experimental_run_functions_eagerly(execute_eager)
    
    images = tf.constant(100.,shape=[1,10,10,20])
    if execute_eager or test_nr == 1:
        scale = Scaler1()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 2:
        scale = Scaler2()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 3:
        scale = Scaler2()
        out = scale(images)
        print(out)

class Scaler1(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
                   
        for i in range(int(self.count)):
            scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
            sized_image = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
            self.sized_images.append(sized_image)
        
        return self.sized_images

class Scaler2(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
                   
        for i in tf.range(self.count):
            scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
            sized_image = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
            self.sized_images.append(sized_image)
        
        return self.sized_images
    
class Scaler3(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
             
        self.sized_images = [tf.image.resize(images, tf.cast(image_size * (1 + i) + 0.5, dtype = tf.int32)) for i in tf.range(self.count)]     
        
        return self.sized_images
    

if __name__ == '__main__':
    main()
```
Traceback:

```
Traceback (most recent call last):
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/test_scaling_tensor.py", line 83, in <module>
    main()
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/test_scaling_tensor.py", line 72, in main
    out = scale(images)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 967, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 579, in __call__
    result = self._call(*args, **kwds)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 626, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    expand_composites=True)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 945, in convert
    x = deps_ctx.mark_as_return(x)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/auto_control_deps.py", line 217, in mark_as_return
    tensor = array_ops.identity(tensor)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 282, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3901, in identity
    "Identity", input=input, name=name)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 591, in _create_op_internal
    inp = self.capture(inp)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 641, in capture
    % (tensor, tensor.graph, self))
tensorflow.python.framework.errors_impl.InaccessibleTensorError: The tensor 'Tensor("resize/ResizeBilinear:0", shape=(1, None, None, 20), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=while_body_32, id=139898298208720); accessed from: FuncGraph(name=call, id=139898299444136).
```

**Comment by bela127** [comment] 2020-03-09 17:55
I found a workaround, which is a bit wired because logicically does the same as the original code, but it splits the work in to loops.
So a lot overhead in typing code, and not very intuitive.

The workaround (Test 6) shoes that tensorflow is basically able to perform the required computation.
It has nothing to do with tf.image.resize but with autograph loop handling
So i guess the solution should be a:
-  autograph bug
- or autograph feature request

So i here by reformulate the bug report:

* Describe the current behaviour:
Works in eager mode
Throws different Errors in graph mode (tf.function)
Problem: autograph has problems with converting for loops

Tests: 1 to 5 fail in graph mode
Test: 6 works like expected :)
Can be used for implementing the expected behaviour

Test 5 and Test 6 are very similar (no obvious clue why 6 works but 5 does not)
Test 1,2 are also very similar and should be solvable

Test 3 uses Generator (which is probably hard to implement in autograph)

Test 4 is a manually unrolled loop, which does not work (probably autograph is try s to be "to smart" and try s implementing the conditions in the graph, and fails because of different length output)
the conditions don't depend on tf.function input so a conversion only of path at construction time would be preferable 

* Describe the expected behaviour:
should work like in eager mode
or like Test 6

```
import tensorflow as tf 

def main():
    execute_eager = False
    test_nr = 6
    tf.config.experimental_run_functions_eagerly(execute_eager)
    
    images = tf.constant(100.,shape=[1,10,10,20])
    if execute_eager or test_nr == 1:
        scale = Scaler1()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 2:
        scale = Scaler2()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 3:
        scale = Scaler3()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 4:
        scale = Scaler4()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 5:
        scale = Scaler5()
        out = scale(images)
        print(out)
    if execute_eager or test_nr == 6:
        scale = Scaler6()
        out = scale(images)
        print(out)

class Scaler1(tf.keras.layers.Layer):
    
    def __init__(self, count = 4, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
                   
        for i in range(int(self.count)):
            scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
            sized_image = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
            self.sized_images.append(sized_image)
        
        return self.sized_images

class Scaler2(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
                   
        for i in tf.range(self.count):
            scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
            sized_image = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
            self.sized_images.append(sized_image)
        
        return self.sized_images
    
class Scaler4(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
        
        i = 1
        scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
        sized_image1 = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
        if i == self.count:
            return [sized_image1]
        else:
            i = 2
            scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
            sized_image2 = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
            if i == self.count:
                return [sized_image1,sized_image2]
            else:
                i = 3
                scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
                sized_image3 = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
                if i == self.count:
                    return [sized_image1,sized_image2,sized_image3]
                else:
                    i = 4
                    scale = image_size * (1 + tf.cast(i, dtype=tf.float32))
                    sized_image4 = tf.image.resize(images, tf.cast(scale + 0.5, dtype = tf.int32))
                if i == self.count:
                    return [sized_image1,sized_image2,sized_image3,sized_image4]
                else:
                    return [sized_image1,sized_image2,sized_image3,sized_image4]
    
class Scaler3(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
        self.sized_images=[]
         
    @tf.function
    def call(self, inputs):
        images = inputs
        
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
             
        self.sized_images = [tf.image.resize(images, tf.cast(image_size * (1 + i) + 0.5, dtype = tf.int32)) for i in tf.range(self.count)]     
        
        return self.sized_images
    
class Scaler5(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)
         
 
    @tf.function
    def call(self, inputs):
        images = inputs
                
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
        
        sized_images = []
        for i in tf.range(self.count):
            scale = image_size * (1 + i)
            sized_images.append(tf.image.resize(images,tf.cast(scale + 0.5, dtype = tf.int32)))
        
        return sized_images
    
class Scaler6(tf.keras.layers.Layer):
    
    def __init__(self, count = 5, name = "Scaler", **kwargs):
        self.count = tf.cast(count, dtype = tf.float32)
        super().__init__(name = name, **kwargs)

    @tf.function
    def call(self, inputs):
        images = inputs
                
        image_size = tf.cast(tf.shape(images)[1:3], dtype=tf.float32)
        
        scales_arr = tf.TensorArray(dtype =tf.float32, size=tf.cast(self.count, dtype=tf.int32),dynamic_size=False)
        for i in tf.range(self.count):
            scale = image_size * (1 + i)
            scales_arr = scales_arr.write(tf.cast(i, dtype=tf.int32), scale)
        scales = scales_arr.stack()
        
        scales_list = tf.unstack(scales)
        sized_images = []
        for scale in scales_list:
            sized_images.append(tf.image.resize(images,tf.cast(scale + 0.5, dtype = tf.int32)))

        return sized_images
    

if __name__ == '__main__':
    main()

```

**Comment by amahendrakar** [comment] 2020-03-11 08:41
Was able to reproduce the issue, code works only when `test_nr = 6`, fails in all other cases. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/8708c578c99d40f7eab22c18b2e3874d/37444.ipynb). Thanks!

**Comment by cmarlin** [comment] 2020-05-07 10:44
Hello,
I had the same issue, with a simpler code sample:

```import tensorflow as tf

class Connect4Environment(object):
  def __init__(self, batch_size:int=1):
    self.board = tf.zeros((batch_size,6,7), dtype=tf.int8)

  def step(self, board, action_mask):
    #tf.debugging.Assert(action_mask.ndim == board.ndim) # Fails with "'Tensor' object has no attribute 'ndim'" in graph mode
    self.board = board * action_mask
  
@tf.function
def play_game():

  batch_size = 4
  history = tf.zeros([batch_size,1], dtype=tf.int32)
  o = Connect4Environment(batch_size)

  for current_index in tf.range(0, 0): # seems XLA doesn't drop the loop
    action_mask = tf.expand_dims(tf.one_hot(history[:,current_index], 7, dtype=tf.int8), 1)
    o.step(o.board, action_mask)
    #o.board = o.board * action_mask # using this way avoid the crash

  current_observation = tf.stack([o.board>0, o.board<0], -1) # pass if this line is commented
  return tf.constant(0) # current_observation is not returned

if __name__ == "__main__":
  #tf.config.experimental_run_functions_eagerly(True) # disable graph / stop crash
  print(play_game())
````

The error seems to be related to tensor update/write in `step` function, inside of the loop. Moving the write outside, or skipping the function avoid the issue.

**Comment by bela127** [comment] 2020-05-07 18:23
@cmarlin 
Your Error is signifikantly different and is not an issue with Tensorflow but a Case of wrong Implementation.

Tensors can never be reassined once created. For that you have to use variables.

In your case in your Loop you create a new constant every time. So your Loop cant execute in Graph mode, nur is unrolled for each Loop itteration and leads to e verry big Graph.

**Comment by cmarlin** [comment] 2020-05-08 12:19
Thanks for the advice, I'll try to rewrite code using Variables

**Comment by mdanatg** [comment] 2020-05-23 19:47
Yes, list manipulation with uneven tensors is not well supported at the moment. We're looking into fixing this. For now, the easiest way to make `Scalar1` work, which I think is the most idiomatic version, is to avoid turning `self.count` into a `Tensor`.

Note that if `self.count` ever becomes a truly dynamic tensor, then you won't be able to use a Python list for `self.sized_images` - Python lists can't change length in TensorFlow.

An alternative to using lists or TensorArray is to use tf.RaggedTensor, which can hold elements of uneven size, and will work with a dynamic self.count as well.

**Comment by bela127** [comment] 2020-05-23 22:20
Thanks for your reply.

I already tryed the solution with RagedTensors, but the current Implementation for them is only useable for one dimentional Data. The scaled Images have two variing Dimentsons, so a RagedTensors is not working.

A RagedTensors Implementation which allowed simple multible ragged dimensions would be nice.

Currently one would have to Splitt the Image in its singel rows and colums, by doing so a folowing compuation is not posible any more.

So using a Python List ist the only posible solution.

That the list cant change size is clear, in Graph mode it ther is no list in the graph.

Can you explain for clearaty what differens it makes whether count is a tensor or a Python scalar? The Loop did a explicit conversion to python int so i guest it should not be translated by autograph.

Im looking Forward to the fix of list itteration.

Thanks for your Help.

**Comment by mdanatg** [comment] 2020-05-24 02:20
I see. Although sometimes you can downcast a Tensor to a Python int (see `tf.get_static_value`), that only works for simple values like constants, and won't work for outputs of more complicated ops. In our case, `int(tensor)` is just a type cast, that is `tf.cast(tensor, tf.int32)` - perhaps that was the source of the confusion, and the reason why I suggested avoiding to wrap self.count into a `tf.constant` in the first place.

**Comment by bela127** [comment] 2020-05-24 18:03
thanks, indeed it was not clear to me that a explicit python cast is also converted by autograph to tf.cast(tensor, tf.int32).
It is very confusing because python ints don't need to be int32.

**Comment by mdanatg** [comment] 2020-05-25 13:08
Agreed, perhaps raising an error would be less confusing instead. The choice for int32 is because int32 and float32 are the default data types in TF (used e.g. when creating tf.constant).

**Comment by sachinprasadhs** [comment] 2021-05-25 10:00
@bela127, from the above comments if your issue is resolved can we go ahead and close this issue? Thanks.

**Comment by bela127** [comment] 2021-05-25 10:32
I'm not sure it is resolved?

I used a "work around" to make it work, but it is not pretty.

In the conversation are multiple solutions mentioned (throwing an error, or a warning, better ragged tensors, better autograph translator to make all examples behave the same -> they should do the same) that would resolve this issue

But i think non of them is currently implement in tensor flow. So the issue still exists.

**Comment by mohantym** [comment] 2021-11-23 09:47
Hi @bela127! This issues seems to be getting resolved in TF 2.7 .Attaching [Gist ](https://colab.research.google.com/gist/mohantym/2c30b2a6856d1a4be20eac59ce1f4049/github_37444.ipynb#scrollTo=JFwkJ5fEKDUT)for reference. Thanks!

**Comment by bela127** [comment] 2021-11-30 11:39
Sorry for my late reply,

so i run all the tests in the gist, and added one new.
the new [gist](https://colab.research.google.com/gist/bela127/d4b8bb3779e113202df2ebdb1ac9f206/github_37444.ipynb#scrollTo=OvGGjSOUJ_84).

The most phythonic test 0 now works! Perfect!

But there is still a big gap between eager and tf.function (this can be expected, as autographing is a difficult job).

The bigger issue is that the Exceptions do not point to the correct problems, or give confusing error messages.
E.g. compare test 0 and 1, the error points to a totally different location than the actual difference in code.

Maybe there are some ideas how to make it better?

I'm happy to see development goes on :+1:

**Comment by mdanatg** [comment] 2021-11-30 18:58
Glad to hear! Sorry I forgot to mark the bug when the fix was submitted.

For the remaining gaps (especially wrong location information in error messages), there should be some improvements in tf-nightly, and we definitely expect the error to point to the correct line - if you come across examples when that's not true, we'd appreciate filing new issues!

**Comment by mohantym** [comment] 2022-12-17 11:58
Hi  @bela127 !
We are checking to see whether you still need help in this issue . 
I am able to get results now in [2.9](https://colab.sandbox.google.com/gist/mohantym/5a321d003dbeaf4069a96e3aecee7d62/git_37444.ipynb), [2.10](https://colab.sandbox.google.com/gist/mohantym/be4362a30f9297933daccf5d2bc264cf/git_37444.ipynb#scrollTo=C79T-XGt6_Ix) and [2.11](https://colab.sandbox.google.com/gist/mohantym/49fde4d4bfb554759fdc1b188579ff65/git_37444.ipynb) .

Thank you!

**Closed** 2022-12-31 13:19 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:autograph, TF 2.7
