### ISSUE TITLE
Can't install form pip on MacOS Mojave and build from source failed

### ISSUE THREAD

**Issue by wildcard** [tensorflow/tensorflow#22945] opened 2018-10-12 18:27 UTC
@tesorflowbutler asked nicely so I added this section :)

Have I written custom code: N/A
OS Platform and Distribution:
MacOS Mojave
TensorFlow installed from: 
- source, tag v1.11.0
- source, branch master 
- pip, 1.11
TensorFlow version: latest or 1.11.0
Bazel version: 
0.17.2 via brew
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: I’ve tried a couple of things, listed below.
Mobile device: N/A

—-

When I tried `pip3 install --user --upgrade tensorflow`
it didn't worked see

```
pip3 install --user --upgrade tensorflow

Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```

when trying `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

it fails for

```
9 warnings generated.
ERROR: /private/var/tmp/_bazel_kobi.kadosh/2314413b591ef152edf49d9023c8bc65/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 1)
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:172:13: error: assigning to 'char *' from incompatible type 'const char *'
        if (PyString_AsStringAndSize(key, &name, &name_size) < 0) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:69:22: note: expanded from macro 'PyString_AsStringAndSize'
       ((*(charpp) = PyUnicode_AsUTF8AndSize(ob, (sizep))) == NULL? -1: 0): \
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:189:13: error: assigning to 'char *' from incompatible type 'const char *'
        if (PyString_AsStringAndSize(key, &camelcase_name, &name_size) < 0) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc:69:22: note: expanded from macro 'PyString_AsStringAndSize'
       ((*(charpp) = PyUnicode_AsUTF8AndSize(ob, (sizep))) == NULL? -1: 0): \
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 218.358s, Critical Path: 49.61s
INFO: 1348 processes: 1348 local.
FAILED: Build did NOT complete successfully
```

the only thing allowed me to get it installed was: 

`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.11.0-py3-none-any.whl`

which I saw here
https://qiita.com/nahshi/items/fcf4898f7c45f11a5c63

running this

`python3 -c "import tensorflow as tf; print(tf.__version__)"`

output that it didn't match.. I guess that my only option is to compile.. but I can't get it to work..

```
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
1.11.0
```

Any help here would be greatly appreciated ^_^

**Comment by tensorflowbutler** [comment] 2018-10-13 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by lamhoangtung** [comment] 2018-10-15 15:51
I'm having the same issue

**Comment by ymodak** [comment] 2018-10-15 17:45
Can you please update your pip3 version to 9.0.1 (typically requires 8.1 or later) and install tensorflow again?

**Comment by ymodak** [comment] 2018-10-16 17:06
@CraigOpie You are correct about Python 3.7 compatibility. TensorFlow 1.11 is tested against Python 3.6 so should work. Please post here your observations.

**Comment by CraigOpie** [comment] 2018-10-16 18:46
@wildcard @ymodak: Just confirmed, I had the same issues as you did with Python 3.7.  You need to install Python 3.6.6 or lower in your virtualenv to use tensorflow.  Just use google if you don't know how to install a different version of Python in your virtualenv.  If you still have questions after that, contact me.

**Comment by bennix** [comment] 2018-10-20 03:03
MacOS users do not upgrade to MacOS Mojave if you want to use tensorflow.
 I use it on MacOS 10.13.6. with Xcode 9.2  CUDA 9.2

Build with newest source code from github.

I use anaconda so the ".bash_profile" file is below:

# added by Anaconda3 5.2.0 installer
export PATH="/Users/username/anaconda3/bin:$PATH"

export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib:/Developer/NVIDIA/CUDA-9.2/lib
export PATH=$DYLD_LIBRARY_PATH:$PATH:/Developer/NVIDIA/CUDA-9.2/bin

[ Download NCCL v2.3.5, for CUDA 9.2, Sept 25, 2018 ]
https://developer.nvidia.com/nccl/nccl-download
NCCL 2.3.5 O/S agnostic and CUDA 9.2
tar xvf nccl_2.3.5-2+cuda9.2_x86_64.txz (cd ~/Downloads)
cd nccl_2.3.5-2+cuda9.2_x86_64/lib
sudo mv * /Developer/NVIDIA/CUDA-9.2/lib/
cd nccl_2.3.5-2+cuda9.2_x86_64/include
sudo mv nccl.h /Developer/NVIDIA/CUDA-9.2/include/
cd tensorflow/third_party/nccl/
ln -s /Developer/NVIDIA/CUDA-9.2/include/nccl.h

And Download CUDNN  and install to related path.

Before building, just modify some files:

Delete all  __align__(sizeof(T)) or  __align__(8)  in following three files:
tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc
tensorflow/core/kernels/split_lib_gpu.cu.cc
tensorflow/core/kernels/concat_lib_gpu_impl.cu.cc


Disable linkopts = [“-lgomp”] in file:
tensorflow/third_party/gpus/cuda/BUILD.tpl

Delete "constexpr" in "constexpr Variant() noexcept = default; " in file:
tensorflow/core/framework/variant.h

Because NCCL will not work on Mac computer, we need delete each item contained nccl in 
tensorflow/contrib/BUILD
tensorflow/contrib/distribute/python/BUILD
tensorflow/contrib/all_reduce/BUILD

especially in tensorflow/contrib/BUILD , modified like following:

""//tensorflow/contrib/text:all_kernels",
    ] + if_mpi(["//tensorflow/contrib/mpi_collectives:mpi_collectives_py"]) + select({
        "//tensorflow:android": [],
"
These operation will disable nccl related function in tensorflow running on Mac.

Then use 
1. ./configure
2. bazel build --config=cuda --config=opt --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package
3. ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

4. cd /tmp/tensorflow_pkg
5. pip install tensorflow-1.12.0rc0-cp36-cp36m-macosx_10_7_x86_64.whl

Then try to run it. It will be OK!

**Comment by ymodak** [comment] 2018-10-30 17:05
Closing this issue since downgrading Python version to 3.6 solves the issue. Please feel free to reopen if it still persists with additional information. Thanks!

**Closed by ymodak** 2018-10-30 17:05 UTC
Labels: stat:awaiting response, type:build/install
