### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: TensorRT is not enabled!

### ISSUE THREAD

**Issue by li829** [tensorflow/tensorflow#32313] opened 2019-09-07 13:13 UTC
I am trying to use tensorflow-1.10 to optimize my pb model.
trt_graph = trt.create_inference_graph(
   input_graph_def = graph_def,
   outputs = outputs,
   max_batch_size=1,
   max_workspace_size_bytes=workspace_size,
   precision_mode='INT8',
   minimum_segment_size=3)

**Comment by gadagashwini** [comment] 2019-09-09 08:04
@li829, Please elaborate the issue with context. And also, provide the code snippet to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-09-16 09:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-09-16 09:00 UTC
Labels: comp:gpu, stat:awaiting response, type:support
