### ISSUE TITLE
TF2: tf.distribute.MirroredStrategy() running sequentially on GPUs

### ISSUE THREAD

**Issue by dsgupta** [tensorflow/tensorflow#30855] opened 2019-07-18 18:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux AMI release 2018.03
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0 beta
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Tesla K80

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have built a custom subclassed Keras model and am using MirroredStrategy for multi-GPU training. I am using custom training loops exactly as described in the official guide here:
https://www.tensorflow.org/beta/tutorials/distribute/training_loops

However, I am running it in `eager-mode` without using `@tf.function`

I am also using `TFRecordDataset` as part of the input pipeline and when I run it separately, it iterates over the dataset very fast, so that is not a bottleneck. 

When I use `nvidia-smi` to monitor the GPU usage during training, I can see that each GPU gets used in a sequential manner. I am not sure why this behavior is arising. 

**Describe the expected behavior**
The model should be running parallel on all GPUs at the same time. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

When using the basic MirroredStrategy, I keep getting a warning that Efficient Allreduce does not support IndexedSlices. What does that mean? 

I have also changed to `tf.distribute.ReductionToOneDevice()` which removes the warning but the sequential behavior still persists.

**Comment by ppham27** [comment] 2019-07-18 21:30
I'm pretty sure this is the expected behavior since the default execution mode is `SYNC`. You can try changing it to `ASYNC`, https://github.com/tensorflow/tensorflow/blob/3794c88add3f4d5dec3d3e4147940ef76e21f030/tensorflow/python/eager/context.py#L62.

I've run into all types of strange errors when I do. Maybe there should be warning about using MirroredStrategy outside a `tf.function` context.

**Comment by dsgupta** [comment] 2019-07-19 17:31
@ppham27 How/Where do I set this mode?

**Comment by dsgupta** [comment] 2019-07-19 17:34
Further updates: I recreated the model, omitting a custom-layer using the Tensorflow Functional API. When I run that model, I can see that it parallelizes across the GPUs (to a certain extent, even though the execution % is quite imbalanced). However, with the exact same layers with my subclassed Keras model, I only ever get sequential execution. 

Does the functional API have graph mode execution enabled by default even in Tensorflow 2.0?

**Comment by christopherbate** [comment] 2019-07-22 20:32
I am also struggling with this issue. When I try to add the "@tf.function" decorator to my function which executes the distribute step, my performance goes from ~2 seconds per batch to over 10 seconds across 4 GPUs. When I try to profile, I mostly just see empty space in the profiler in Tensorboard, where there's some sporadic activity on my CPU seemingly due to the only layers in my model where I subclassed "keras.layer". I will check if switching to functional API fixes the problem.

**Comment by dsgupta** [comment] 2019-07-22 22:17
@christopherbate If it's not a problem, could you please share the steps involved to profile using `tensorboard` or maybe point me to documentation/tutorial you followed? Even I am getting extremely weird behavior when I try to use `@tf.function`

**Comment by ppham27** [comment] 2019-07-22 22:31
@dsgupta 

See https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_synchronous_execution?hl=en.

You can try `tf.config.experimental.set_synchronous_execution(False)`. I'm not that optimistic that this will fix your issue, though.

**Comment by dsgupta** [comment] 2019-07-22 23:42
I tried that but the execution is still sequential. If I try to use `@tf.function` decorator for `dist_train_step` and `dist_test_step`, I am getting the following error: 

`ValueError: No gradients provided for any variable:`

But it is working perfectly in `eager` mode.

**Comment by christopherbate** [comment] 2019-07-23 03:36
@dsgupta 
Put: 
`with self.writer.as_default():
         tf.summary.trace_on(graph=False, profiler=True)`

Right before you want to start profiling, then:
` with self.writer.as_default():
         tf.summary.trace_export(step=step, name="model_profile", profiler_outdir="./test_profile")`

To stop profiling. Generally I try to capture 2-3 batches to see what things look like.

Can you provide your code for reproducing the issue? My code base is large, so paring it down to isolate the cause is difficult, although it sounds like it might be a common cause.

**Comment by dsgupta** [comment] 2019-07-23 16:50
@christopherbate Sorry, I am not able to share the code. However, I am using the Keras Functional API with Bidirectional LSTM, and basic Dense and Embedding layers. 
My training script is exactly like the one in the tutorial here, only swapping out the model with mine, and the input dataset is something else using TFRecordDataset: https://www.tensorflow.org/beta/tutorials/distribute/training_loops

It works in `eager` mode, but when I decorate the distributed train and val steps with `@tf.function` as given in the tutorial, I get all kinds of weird errors. 

@ppham27 Would you mind sharing your email so I can privately share the model structure with you? 

In any case, when I swap out my custom Pooling layer with `AveragePool1D` and try to use `@tf.function` decorator, I get the following error: 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Cannot place the graph because a reference or resource edge connects colocation groups with incompatible assigned devices: /job:localhost/replica:0/task:0/device:GPU:0 vs /job:localhost/replica:0/task:0/device:CPU:0. The edge src node is while_20/exit/_95 , and the dst node is while_1_RetVal
         [[node model/bi_rnn/StatefulPartitionedCall_1 (defined at /SageMaker/efs/Damayanti/ChargeBackModel_TF2/src/trainer.py:68) ]]
  (1) Invalid argument:  Cannot place the graph because a reference or resource edge connects colocation groups with incompatible assigned devices: /job:localhost/replica:0/task:0/device:GPU:0 vs /job:localhost/replica:0/task:0/device:CPU:0. Theedge src node is while_20/exit/_95 , and the dst node is while_1_RetVal
```

**Comment by dsgupta** [comment] 2019-07-23 17:25
My custom layer is a dynamic one as it has operations using the shape of its inputs, which is the output of `padded_batch`, so it's `None`. Hence, if I remove `dynamic=True`, it throws an error. And if I keep in the `dynamic=True` and try `Autograph`, it can't find the gradients for any of the trainable variables. I assume this is expected behavior.

**Comment by dsgupta** [comment] 2019-07-23 17:28
@ppham27 Sorry for spamming your notifs, but I just wanted to confirm. So there's no way to ensure asynchronous execution in a multi-GPU setting outside of graph mode, right? 

Is there a way to do distributed training without using MirroredStrategy or any way to train in parallel in eager mode? Otherwise, there's no point in doing multi-GPU training...

**Comment by ppham27** [comment] 2019-07-23 23:40
Hi @dsgupta,

If you want, you can send me code to ppham27-github@google.com. Yes, it doesn't seem that the ASYNC execution mode is fully working, so you probably have to be using graph mode.

The last easy fix that I can think of to improve performance with `tf.function` is trying:

```
from tensorflow.python.eager import context

context.context().mirroring_policy = context.MIRRORING_ALL
```

I doubt that this will work, too, though.

**Comment by dsgupta** [comment] 2019-07-29 21:10
Hi @ppham27, 

When I try using @tf.function, my execution just hangs without progressing (no activity on GPU) but with lots of activity on CPU. Can you please help me debug the issue? There are no errors being shown.

**Comment by ppham27** [comment] 2019-08-03 08:17
Are using using the `tf.function` in the right part?

Ideally use use `tf.function` *only* in the outermost region:

```
@tf.function
def train_with_strategy(strategy, model, optimizer, dataset):
  def train_step(x, y):
    return _train_step(model, optimizer, x, y)

  def update_state(state, x_and_y):
    per_replica_loss = strategy.experimental_run_v2(train_step, x_and_y)
    state['loss'] = strategy.reduce(
        tf.distribute.ReduceOp.SUM, per_replica_loss, axis=None)       
    state['step'] += 1
    return state

  initial_state = {'loss': np.nan, 'step': 0}
  return dataset.reduce(initial_state, update_state)
```

Where dataset comes from `strategy.experimental_distribute_dataset`. Also, run `tf.debugging.set_log_device_placement(True)` to help debug where ops are being placed.

**Comment by dsgupta** [comment] 2019-08-05 16:17
Hi @ppham27 , thanks for that example. Please also see issue: #31210 where I solved the decorator problem, but am now facing issues iterating over the dataset. 
The colab gist is: [here](https://colab.research.google.com/gist/dsgupta/7114aa6e13b4f33264ccf3758d169bab/test.ipynb)

I also had a doubt regarding the code above. What exactly is `state` and why should we use `dataset.reduce`? I followed the tutorial here: [](https://www.tensorflow.org/beta/tutorials/distribute/training_loops) and then changed it to send the dataset directly to the function decorated by `@tf.function` as mentioned in issue #29911 

Is the above snippet part of a bigger code that I can refer for efficient iteration and logging of metrics for multi-GPU training?

**Comment by ppham27** [comment] 2019-08-11 08:08
What error am I suppose to be seeing?

I made some small modifications to your Colab and everything seems fine: https://colab.sandbox.google.com/gist/ppham27/fb8b9eb2e46a05b3ad796d38a7174a6c/test.ipynb.

The dataset reduce and state stuff is what a for loop compiles down into after applying the tf.function and Autograph. Sometimes it's better to write it that way if you're experiencing problems with Autograph.

**Comment by ymodak** [comment] 2019-09-07 04:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-09-07 04:00 UTC
Labels: comp:dist-strat, type:support

**Comment by naturomics** [comment] 2019-11-14 09:50
Same issue, look like the mirrored strategy only works on multi-GPUs when the `fn` in strategy.experimental_run_v2(fn) is wrapped with tf.function, eager mode or only wrap with tf.function inside `fn`   will fail. Finally I got the meaning of this warning:

> Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `experimental_run_v2` inside a tf.function to get the best performance.

1. Is there any work on the eager mode support ? If not, we should issue a feature require.
2. Is this behavior also apply to TPU or any other strategy? I can not find any doc on this problem

**Comment by naturomics** [comment] 2019-11-15 13:53
For ppl struggling with this problem, [horovod](https://github.com/horovod) is a good workaround at this time, if you have to run in eager mode or tf.function only decorated in sub-block of model.  Here is my code for creating a distributed optimizer, other things follow the example of horovod.

```
def create_distributed_optimizer(optimizer, name=None, device_dense='', device_sparse='',
                         compression=hvd.Compression.none, sparse_as_dense=False):
    class _DistributedOptimizer(tf.keras.optimizers.Optimizer):
        def __init__(self, name, device_dense, device_sparse, compression, sparse_as_dense, config):
            if name is None:
                name = "Distributed%s" % self.__class__.__base__.__name__
            self._name = name
            self._device_dense = device_dense
            self._device_sparse = device_sparse
            self._compression = compression
            self._sparse_as_dense = sparse_as_dense
            self._get_gradients_used = False
            super(self.__class__, self).__init__(**config)

        def apply_gradients(self, grads_and_vars, *args, **kwargs):
            if not self._get_gradients_used and hvd.size() > 1:
                averaged_grads, params = [], []
                with tf.name_scope(self._name + "_Allreduce"):
                    for grad, param in grads_and_vars:
                        if grad is not None:
                            if self._sparse_as_dense and isinstance(grad, tf.IndexedSlices):
                                grad = tf.convert_to_tensor(grad)
                            avg_grad = hvd.allreduce(grad,
                                                     device_dense=self._device_dense,
                                                     device_sparse=self._device_sparse,
                                                     compression=self._compression)
                            averaged_grads.append(avg_grad)
                        else:
                            averaged_grads.append(None)
                        params.append(param)
                grads_and_vars = zip(averaged_grads, params)
            self._get_gradients_used = True
            return super(self.__class__, self).apply_gradients(grads_and_vars, *args, **kwargs)

        @classmethod
        def from_config(cls, cfg):
            return cls(name, device_dense, device_sparse, compression, sparse_as_dense, cfg)

    cls = type(optimizer.__class__.__name__, (optimizer.__class__,), dict(_DistributedOptimizer.__dict__))
    return cls(name, device_dense, device_sparse, compression, sparse_as_dense, optimizer.get_config())
```

E.g.,

```
hvd.init()
opt = tf.keres.optimizers.Adam()
opt = create_distributed_optimizer(opt)

dataset = tf.data.Dataset instance
mode = Model()

first_batch = True
for input in dataset:
    results = model(input)
    if first_batch:
        hvd.broadcast_variables(model.variables, root_rank=0)
        hvd.broadcast_variables(opt.variables(), root_rank=0)
        first_batch = False
     results = hvd.allreduce(results)
```

**Comment by sufengniu** [comment] 2020-07-28 23:09
I observe the same issue here, that GPU run in sequential way for eager execution when I use MirroredStrategy, I'd like to confirm, the best way to address this issue is to use horovod? it is surprise that until now tf2.x still haven't resolved this problems
