### ISSUE TITLE
Ubuntu installation instruction is too obsolete!

### ISSUE THREAD

**Issue by zyavrik** [tensorflow/tensorflow#13015] opened 2017-09-13 13:07 UTC
For successful build on Ubuntu it's required to do much more than stated on the installation instructions!

My system:
```
CUDA support: YES
Bazel: 0.5.4
gcc (Ubuntu 5.4.1-8ubuntu1) 5.4.1 20170304
Linux Desktop 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
CPU i7-7820x (with AVX512 support)
```

It's required change the build command:

`bazel build --config=opt --config=cuda --cxxopt="-fabi-version=0" //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

And it's still not enough :( I still can't make successful build...

**Comment by drpngx** [comment] 2017-09-13 18:07
Are you missing the configure step?

**Comment by zyavrik** [comment] 2017-09-13 19:27
No, of course.

**Comment by zyavrik** [comment] 2017-09-13 20:11
If I remove libeigen3-dev then I get the same error like before install:

```
ERROR: /home/dmitry/Private/Kaggle/tensorflow/tensorflow/core/kernels/BUILD:1369:1: C++ compilation of rule '//tensorflow/core/kernels:range_sampler' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/dmitry/.cache/bazel/_bazel_dmitry/45cfecd68ef4f076728c861b104b36a6/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=6 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++11' '-march=native' '-fabi-version=0' '-D_GLIBCXX_USE_CXX11_ABI=0' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/range_sampler/tensorflow/core/kernels/range_sampler.pic.d '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/range_sampler/tensorflow/core/kernels/range_sampler.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -DSNAPPY -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/nsync -iquote bazel-out/local_linux-opt/genfiles/external/nsync -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/jemalloc -iquote bazel-out/local_linux-opt/genfiles/external/jemalloc -iquote external/protobuf_archive -iquote bazel-out/local_linux-opt/genfiles/external/protobuf_archive -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-opt/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/local_linux-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/local_linux-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-opt/genfiles/external/zlib_archive -iquote external/snappy -iquote bazel-out/local_linux-opt/genfiles/external/snappy -isystem external/nsync/public -isystem bazel-out/local_linux-opt/genfiles/external/nsync/public -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/jemalloc/include -isystem bazel-out/local_linux-opt/genfiles/external/jemalloc/include -isystem external/protobuf_archive/src -isystem bazel-out/local_linux-opt/genfiles/external/protobuf_archive/src -isystem external/eigen_archive -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-opt/genfiles/external/zlib_archive -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/kernels/range_sampler.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/kernels/_objs/range_sampler/tensorflow/core/kernels/range_sampler.pic.o)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:378:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/lib/random/random_distributions.h:27,
                 from ./tensorflow/core/lib/random/simple_philox.h:24,
                 from ./tensorflow/core/lib/random/distribution_sampler.h:38,
                 from ./tensorflow/core/kernels/range_sampler.h:23,
                 from tensorflow/core/kernels/range_sampler.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h: In function 'Packet Eigen::internal::ploaddup(const typename Eigen::internal::unpacket_traits<Packet>::type*) [with Packet = __vector(16) float; typename Eigen::internal::unpacket_traits<Packet>::type = float]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h:469:77: error: '_mm512_castsi512_ps' was not declared in this scope
   __m512 even_elements = _mm512_castsi512_ps(_mm512_cvtepu32_epi64(low_half));
                                                                             ^
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h: In function 'Packet Eigen::internal::ploaddup(const typename Eigen::internal::unpacket_traits<Packet>::type*) [with Packet = __vector(8) double; typename Eigen::internal::unpacket_traits<Packet>::type = double]':
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/AVX512/PacketMath.h:478:56: error: '_mm512_insertf64x2' was not declared in this scope
   x = _mm512_insertf64x2(x, _mm_loaddup_pd(&from[0]), 0);
                                                        ^
In file included from ./tensorflow/core/platform/default/logging.h:24:0,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:25,
                 from ./tensorflow/core/kernels/range_sampler.h:21,
                 from tensorflow/core/kernels/range_sampler.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::string* tensorflow::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = long long int; std::string = std::basic_string<char>]':
tensorflow/core/kernels/range_sampler.cc:86:5:   required from here
./tensorflow/core/platform/default/logging.h:230:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <= )
                                   ^
./tensorflow/core/platform/macros.h:79:29: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (x)
                             ^
./tensorflow/core/platform/default/logging.h:230:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LE, <= )
 ^
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::string* tensorflow::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = long long int; T2 = long unsigned int; std::string = std::basic_string<char>]':
tensorflow/core/kernels/range_sampler.cc:244:3:   required from here
./tensorflow/core/platform/default/logging.h:228:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         == )  // Compilation error with CHECK_EQ(NULL, x)?
                         ^
./tensorflow/core/platform/macros.h:79:29: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) (x)
                             ^
./tensorflow/core/platform/default/logging.h:227:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.974s, Critical Path: 1.31s
FAILED: Build did NOT complete successfully

```

**Comment by drpngx** [comment] 2017-09-13 20:26
@rmlarsen any idea what the problem is with `_mm512_insertf64x2`?

**Comment by zyavrik** [comment] 2017-09-13 21:51
It looks like problem is with `_mm512_insertf64x2` is caused by gcc 4 - it doesn't support avx512. Of course, compilation must be successful anyway. But even gcc 5 doesn't work with another error :( Nothing work at all.

It's so disappointing. I can't build tensorflow for a week on macOS, Windows and Ubuntu using hundreds of different compilation options (but always with GPU support).

**Comment by zyavrik** [comment] 2017-09-14 00:29
Now I get another error with gcc 5 (I don't understand why the error is different from described above). It's reported here: #10220

**Comment by zyavrik** [comment] 2017-09-14 01:50
More information about errors that I get both with gcc-4.9 and gcc-5: https://github.com/tensorflow/tensorflow/issues/13014

**Comment by zyavrik** [comment] 2017-09-14 04:02
Only gcc-4.8 works fine on new CPUs. Please update installation instructions.

**Comment by salviustryphon** [comment] 2017-09-14 08:51
Hi, no matter for me with this command line : "bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --config=cuda -k //tensorflow/tools/pip_package:build_pip_package"

**Comment by aselle** [comment] 2017-09-25 20:58
@wolffg, could you update the docs:?

**Comment by tensorflowbutler** [comment] 2017-12-20 01:09
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by wolffg** [comment] 2017-12-20 07:22
These installation instructions have been updated several times since this bug was opened.  I'm closing this; if you are still having issues compiling from source, please file a new issue and fill out the template so we can get more information on your issues.

Thanks!

**Closed by wolffg** 2017-12-20 07:22 UTC
Labels: stat:awaiting tensorflower, type:docs

**Comment by aselle** [comment] 2017-12-20 19:24
Thanks @wolffg
