### ISSUE TITLE
tflite ssbo buffer dump

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#38188] opened 2020-04-03 08:01 UTC
I`m using tflite gpu ssbo way to inference but the output is not the same as without ssbo
I have referenced this example
https://github.com/gnsmrky/tensorflow-lite-ssbo.git
So I want to inpect the input with ssbo is or not same as the input without ssbo but have no idea how to get ssbo content to evaluate ?

The way to get input without ssbo
![image](https://user-images.githubusercontent.com/17869361/78337233-3f579b80-75c3-11ea-910a-29e67cd7dcdf.png)

Bellow is ssbo way by using compute shader in opengl es 3.1
I have tried to use glMapBufferRange to map the buf to cpu for evaluting but all result is zero.
I am new to opengles 3.1 and googled but not found a solution  
![image](https://user-images.githubusercontent.com/17869361/78337436-89d91800-75c3-11ea-91cc-ae4a8a35fcf2.png)

**Comment by Saduf2019** [comment] 2020-04-03 13:08
@weinixuehao 
please let us know the tensorflow version on which issue is faced.

**Comment by weinixuehao** [comment] 2020-04-04 07:28
tensorflow 2.0.1

**Comment by weinixuehao** [comment] 2020-04-10 03:27
@Saduf2019 
It`s inference result is wrong with ssbo

**Comment by impjdi** [comment] 2020-04-19 08:09
I think this is a duplicate of https://github.com/tensorflow/tensorflow/issues/26297

**Closed by impjdi** 2020-04-19 08:09 UTC
Labels: TF 2.0, comp:lite, type:support

**Comment by weinixuehao** [comment] 2020-04-20 01:23
@impjdi you can close it
