### ISSUE TITLE
Unable to change validation dataset for "model.fit()" function after it raises an exception

### ISSUE THREAD

**Issue by yashwanth98** [tensorflow/tensorflow#62104] opened 2023-10-13 03:30 UTC
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Google Colab

### Python version

3.10.12

### Current behavior?

When using model.fit() in TensorFlow, the validation data provided as an input parameter is initially used for model evaluation. However, if the initial evaluation fails, subsequent runs of model.fit() still use the previously provided validation data, even if new data is provided.

### Standalone code to reproduce the issue

```shell
The error is quite easy to reproduce. Check the "compile and train section" in the below provided colab.

https://colab.research.google.com/drive/1Es8mQd0FOoWea4SrJ2TDz4NRSx0ZxwEt#scrollTo=08WJXiheNxK7

I modified a tensorflow tutorial colab on CNNs to reproduce this error. In the section i first run the model with correct parameters, then with incorrect and then again with correct parameters but this time it fails.
```

**Comment by sushreebarsa** [comment] 2023-10-13 06:49
@SuryanarayanaY I was able to replicate this issue. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/fc4de78e81b2267dd16fd133c349190a/copy-of-cnn.ipynb#scrollTo=vNVwAMsaNlIV) here. Thank you!

**Comment by yashwanth98** [comment] 2023-10-13 09:02
I have been digging into the code and I think I found out what the problem is. It appears that the model.fit function caches the validation data as a data handler before executing the model.evaluate function. Normally, this cache is cleared after the evaluate function call. However, when the model.evaluate call encounters an exception, the cache is not cleared, leading to the continued use of the same data for subsequent model.fit calls.

I can work on this issue. Can you please assign it to me?

**Comment by dokutoshi** [comment] 2023-10-16 23:37
I believe there is a major issue with the Keras `model.fit` module, as I've been experiencing several OOM crashes while using it with the validation parameter on versions 2.13, 2.13.1, and 2.14. Specifically, I've noticed a significant memory growth per epoch in a Linux environment, which can be monitored by running the `free -gh` command in the terminal. 

Moreover, there seems to be an interaction problem between the gradientTape and model.fit with validation data that causes free memory to decline very quickly on consecutive epochs. To recreate this issue, one can use a dataset with one million samples and 1000 classes similar to ImageNet. 

In Pytorch, there is a zero.grad() method to manage memory, but Keras manages it automatically. Therefore, the Keras `fit` method should resolve the data handler memory management, but it doesn't seem to be doing so effectively. 

@yashwanth98 recommend this page: https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch
@SuryanarayanaY

**Comment by dokutoshi** [comment] 2023-10-17 00:42
Related and open cases to the above.

`Memory leak when using tf.Model and tf.Model.fit() in a loop. clear_session() does not help`
https://github.com/tensorflow/tensorflow/issues/61791 

`Higher Memory Usage with model.predict in Recent TF Versions (TF 2.10, 2.11 etc)`
https://github.com/tensorflow/tensorflow/issues/58676

@yashwanth98 @SuryanarayanaY

**Comment by SuryanarayanaY** [comment] 2023-10-17 18:14
> I have been digging into the code and I think I found out what the problem is. It appears that the model.fit function caches the validation data as a data handler before executing the model.evaluate function. Normally, this cache is cleared after the evaluate function call. However, when the model.evaluate call encounters an exception, the cache is not cleared, leading to the continued use of the same data for subsequent model.fit calls.
> 
> I can work on this issue. Can you please assign it to me?

Hi @yashwanth98 , Yes model.fit creates a cache of data handler for validation data which will be cleared after completion of all epochs of training. In a case where training not completed due to any reason or exception like reproduced by you the validation data handler object not getting deleted and during next call to `model.fit `as it was already exists there is no new validation data handler object generated and using older object only.This is causing the Graph execution error(due to shape  mismatch).

**Comment by SuryanarayanaY** [comment] 2023-10-17 18:29
@yashwanth98 ,

The issue exists in keras_core(multi backend) and needs to be reported on keras repo. Could you please submit an issue with [keras-team/keras](https://github.com/keras-team/keras/issues) repo ?

**Comment by SuryanarayanaY** [comment] 2023-10-26 09:44
@yashwanth98 ,

It was resolved in keras-nightly(3.0.dev version) as per Keras repo PR#[18659](https://github.com/keras-team/keras/pull/18659). Thanks for reporting this. 

Shall we mark it as closed now? Please verify and close from your end.

**Comment by dokutoshi** [comment] 2023-10-28 02:08
@SuryanarayanaY @yashwanth98 - i want to investigate

**Comment by SuryanarayanaY** [comment] 2023-10-30 04:21
@dokutoshi,

Since Keras (available as ` Keras-nightly(3.0.Dev)` ) now transformed to Multi backend that can support Pytorch,Tensorflow,Jax as well any issues related to tensorflow backend i.e tf.keras module can be handled in tf-keras repo if not related to Keras3. 

Anyways the reported issue fixed in keras-nightly with the PR mentioned in above [comment](https://github.com/tensorflow/tensorflow/issues/62104#issuecomment-1780773667).

@yashwanth98 ,

Could you please verify and close the issue and let us know if have any problems still needs a look. Thanks!

**Comment by dokutoshi** [comment] 2023-11-01 15:59
I will look into the solution from Keras.

**Comment by yashwanth98** [comment] 2023-11-01 16:07
Hi, I verified the fix and it seems to be working fine now.

**Closed** 2023-11-01 16:07 UTC
Labels: type:bug, comp:apis, comp:keras, TF 2.13
