### ISSUE TITLE
Precision change of tf.variable while doing some ops

### ISSUE THREAD

**Issue by sumitpai** [tensorflow/tensorflow#30814] opened 2019-07-17 18:14 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed : via conda
- TensorFlow version (use command below): 1.14.0-rc1
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0.130/7.6 (driver 410.78)
- GPU model and memory: Tesla V100 16GB

**Describe the current behavior**
The output difference is non zero
**Describe the expected behavior**
It should be zero
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import numpy as np
import tensorflow as tf

tf.reset_default_graph()
with tf.device('/cpu:0'):    
    inp = tf.Variable(np.random.normal(size=(10,5)), dtype=tf.float64)
"""
with tf.device('/gpu:0'):    
    inp = tf.Variable(np.random.normal(size=(10,5)), dtype=tf.float64)       
"""
var_test = tf.Variable(np.zeros((3,5), dtype=np.float64), dtype=tf.float64)
plh = tf.placeholder(shape=(3,), dtype=tf.int32)
   
op = var_test.assign(tf.gather(inp, plh))
with tf.control_dependencies([op]):
    out_var = var_test + tf.constant(np.float64(0.07))
    out_var = out_var - tf.constant(np.float64(0.07))
    update_op = tf.scatter_update(inp, plh, out_var)

idx = np.arange(10)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out_ip_before = sess.run(inp)
    print(out_ip_before)
    print('sum of all params (before):', np.sum(out_ip_before))
    for i in range(10):
        idx_batch = np.random.permutation(idx)[:3]
        out = sess.run(update_op, feed_dict={plh:idx_batch})
        
    out_ip_after = sess.run(inp)
    print('sum of all params (after):', np.sum(out_ip_after))
    print(out_ip_after)
    diff_after_before = out_ip_before - out_ip_after
    print('before-after:', np.sum(diff_after_before))
    print(diff_after_before)
```
**Other info / logs**
Could have come up with a better issue title :)

**Comment by gadagashwini** [comment] 2019-07-18 10:15
I am able to reproduce the issue on Colab with Tenosrflow 1.14.0. Please find the [gist here](https://colab.research.google.com/drive/1f3m2HkQMO2MczoLjBchlFYyU791rIBP8). Thanks!

**Comment by alextp** [comment] 2019-07-31 18:39
I don't understand. In @gadagashwini's reproduction the precision difference is 1e-16, which seems to be in line of what you'd expect from double precision addition / subtraction at this difference in order of magnitude.

Is this something you don't see in numpy but see in tf?

**Comment by sumitpai** [comment] 2019-08-02 10:17
My bad.. I had not verified the numpy equivalent. I was expecting it to be much lower in magnitude (like 1e-30 or so for float 32 but it is of the order of 1e-7 for float 32 in both tf and np).

**Comment by gadagashwini** [comment] 2019-08-02 11:50
@sumitpai Closing the issue since it is answered. Thanks!

**Closed by gadagashwini** 2019-08-02 11:50 UTC
Labels: TF 1.14, comp:ops, type:support
