### ISSUE TITLE
Cannot compile tensorflow with CUDA 10.0 and cuDNN 7.2

### ISSUE THREAD

**Issue by Tvde1** [tensorflow/tensorflow#22664] opened 2018-10-02 08:57 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
Trying to build from source.
- **TensorFlow version (use command below)**:
1.11.0
- **Python version**:
3.6.7rc1
- **Bazel version (if compiling from source)**:
0.16.1 (I tried with latest 1.17.2 but that also didn't build).
- **GCC/Compiler version (if compiling from source)**:
I don't know
- **CUDA/cuDNN version**:
CUDA 9.0 and cuDNN 7.3.1
- **GPU model and memory**:
GTX 1080 8gb
- **Exact command to reproduce**:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
I'm trying to build tensorflow from source. This is the error:
```
ERROR: D:/temp/tensorflow/tensorflow/contrib/rnn/BUILD:217:1: C++ compilation of rule '//tensorflow/contrib/rnn:python/ops/_lstm_ops_gpu' failed (Exit 1): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/tim/_bazel_tim/lj4hacgi/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Tim/AppData/Local/Programs/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Tim/AppData/Local/Programs/Python/Python37/lib/site-packages
    SET TEMP=C:\Users\Tim\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TMP=C:\Users\Tim\AppData\Local\Temp
```

**Comment by Tvde1** [comment] 2018-10-02 09:19
v1.10 also doesn't build for me.

**Comment by adampl** [comment] 2018-10-02 10:36
TensorFlow requires CUDA 9.0 according to: https://www.tensorflow.org/install/gpu

**Comment by Tvde1** [comment] 2018-10-02 10:39
I've talked to and seen people having it built with CUDA 10.0 :\ I guess I'll try

**Comment by Tvde1** [comment] 2018-10-02 11:47
I'm trying with CUDA 9.0 and cuDNN 7.3.1 (for CUDA 9.0) and it still fails.

```
RROR: D:/temp/tensorflow/tensorflow/contrib/image/BUILD:22:1: C++ compilation of rule '//tensorflow/contrib/image:python/ops/_image_ops_gpu' failed (Exit 1): msvc_wrapper_for_nvcc.bat failed: error executing command
```

**Comment by blaueck** [comment] 2018-10-03 04:55
I've sucessfully  built tensorflow with CUDA 10 and cuDNN 7.3.1 on windows 10. Maybe the problem is caused by the compiler? I used vs 2017.

**Comment by Tvde1** [comment] 2018-10-03 07:58
I used vs 2017 professional, fresh install from yesterday.

**Comment by alanpurple** [comment] 2018-10-04 00:32
there is no cudnn 7.2 for cuda 10

**Comment by joseortiz3** [comment] 2018-10-04 02:45
I get this same issue with cudnn 7.3, Cuda 10, on Windows 10.

```
ERROR: C:/users/joey/_bazel_joey/juz2ghmw/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/joey/_bazel_joey/juz2ghmw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Joey/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Joey/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\Joey\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\Joey\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/local_config_python /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python /Ibazel-out/x64_windows-opt/bin/external/local_config_python /Iexternal/protobuf_archive/python /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/python /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/python /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/local_config_python/python_include /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python/python_include /Ibazel-out/x64_windows-opt/bin/external/local_config_python/python_include /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /DHAVE_PTHREAD /wd4018 /wd4514 -DGOOGLE_PROTOBUF_HAS_ONEOF=1 -DPROTOBUF_PYTHON_ALLOW_OVERSIZE_PROTOS=1 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/python/google/protobuf/pyext/_message.so/descriptor_containers.o /c external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(172): error C2440: '=': cannot convert from 'const char *' to 'char *'
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(172): note: Conversion loses qualifiers
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(189): error C2440: '=': cannot convert from 'const char *' to 'char *'
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(189): note: Conversion loses qualifiers
[2,999 / 6,086] Compiling external/protobuf_archive/src/google/protobuf/generated_message_util.cc; 1s local ... (39 actions running)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: C:/users/joey/downloads/tensorflow/tensorflow/contrib/lite/python/BUILD:42:1 C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/joey/_bazel_joey/juz2ghmw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Joey/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Joey/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\Joey\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\Joey\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/local_config_python /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python /Ibazel-out/x64_windows-opt/bin/external/local_config_python /Iexternal/protobuf_archive/python /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/python /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/python /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/local_config_python/python_include /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python/python_include /Ibazel-out/x64_windows-opt/bin/external/local_config_python/python_include /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /DHAVE_PTHREAD /wd4018 /wd4514 -DGOOGLE_PROTOBUF_HAS_ONEOF=1 -DPROTOBUF_PYTHON_ALLOW_OVERSIZE_PROTOS=1 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/python/google/protobuf/pyext/_message.so/descriptor_containers.o /c external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc
```

**Comment by blaueck** [comment] 2018-10-04 07:02
@joseortiz3 @Tvde1 , I noticed that you use the v140 toolset with vs 2017 maybe by setting BAZEL_VC="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"? I use the v141 toolset with CUDA 10 by setting BAZEL_VS="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"(I use community edition).

**Comment by joseortiz3** [comment] 2018-10-04 07:39
@blaueck @Tvde1  , Yeah, I was using msvc 14.0 but I set my bazel environment variables like you said: `BAZEL_VS` and `BAZEL_VC` (then restarted some things in a random way until the right compiler showed up during compilation).

However now I'm getting similar " 'const char *' to 'char *'" errors under the msvc 15.0 compiler.
```
ERROR: C:/users/joey/_bazel_joey/juz2ghmw/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 2): msvc_wrapper_for_nvcc.bat failed: error executing command
  cd C:/users/joey/_bazel_joey/juz2ghmw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Joey/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Joey/Anaconda3/lib/site-packages
    SET TEMP=C:\Users\Joey\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\Joey\AppData\Local\Temp
  external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/bazel_tools /Ibazel-out/x64_windows-opt/genfiles/external/bazel_tools /Ibazel-out/x64_windows-opt/bin/external/bazel_tools /Iexternal/local_config_python /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python /Ibazel-out/x64_windows-opt/bin/external/local_config_python /Iexternal/protobuf_archive/python /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/python /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/python /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/local_config_python/python_include /Ibazel-out/x64_windows-opt/genfiles/external/local_config_python/python_include /Ibazel-out/x64_windows-opt/bin/external/local_config_python/python_include /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /DHAVE_PTHREAD /wd4018 /wd4514 -DGOOGLE_PROTOBUF_HAS_ONEOF=1 -DPROTOBUF_PYTHON_ALLOW_OVERSIZE_PROTOS=1 /Fobazel-out/x64_windows-opt/bin/external/protobuf_archive/_objs/python/google/protobuf/pyext/_message.so/descriptor_containers.o /c external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(172): error C2440: '=': cannot convert from 'const char *' to 'char *'
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(172): note: Conversion loses qualifiers
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(189): error C2440: '=': cannot convert from 'const char *' to 'char *'
external/protobuf_archive/python/google/protobuf/pyext/descriptor_containers.cc(189): note: Conversion loses qualifiers
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 14.784s, Critical Path: 8.98s
INFO: 43 processes: 43 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by blaueck** [comment] 2018-10-04 08:00
@joseortiz3 , Have you try to run "bazel clean" after switch to compiler 14.15.26726?

**Comment by joseortiz3** [comment] 2018-10-04 20:36
@blaueck Yeah tried that, `bazel clean` and `bazel clean --expunge`, closing shell, etc. Needed to do that when I changed my environment variables.

No matter what I do I always get `protobuf` compile errors. I think its a problem with Python 3.7 somehow being incompatible with protobuf; that seems to pop up a lot googling this error.

Always get 2-10 C2440 errors in ` descriptor_containers.cc`... going to try python 3.6

**Comment by joseortiz3** [comment] 2018-10-05 02:03
@blaueck Tried Python 3.6.6, but now I get the error below:

```
c:\users\joey\_bazel_joey\juz2ghmw\execroot\org_tensorflow\external\eigen_archive\eigen\src/Core/arch/CUDA/Half.h(212): error: more than one instance of overloaded function "__hadd" matches the argument list:
            function "__hadd(int, int)"
            function "__hadd(__half, __half)"
            argument types are: (const Eigen::half, const Eigen::half)
```

Related to https://github.com/tensorflow/tensorflow/issues/19198

What compute capability are you specifying I wonder?

**Comment by blaueck** [comment] 2018-10-05 03:48
I specify 5.0. My card can't support compute capability greater than 5.0.

**Comment by joseortiz3** [comment] 2018-10-05 04:54
Ok, I figured it out. See https://github.com/tensorflow/tensorflow/issues/22715 if interested. Compute >= 5.3 requires patching right now. Followed [this guide to patch it](https://medium.com/@amsokol.com/update-1-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-and-c2e86fec9ef2). I also did `checkout` v1.11 as per that guide, not sure if that's required.

**Comment by ymodak** [comment] 2018-10-05 20:11
@Tvde1  Can you please post your observations after trying installation guide given in the comment below.

> Ok, I figured it out. See #22715 if interested. Compute >= 5.3 requires patching right now. Followed [this guide to patch it](https://medium.com/@amsokol.com/update-1-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-and-c2e86fec9ef2). I also did `checkout` v1.11 as per that guide, not sure if that's required.

**Comment by RainyRen** [comment] 2018-10-07 15:12
@joseortiz3 I have the same problem with you. I refer https://medium.com/@amsokol.com/update-1-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-and-c2e86fec9ef2, do the same progress work for me. I think the key is "There is a BUG in eigen third-party library" as mentioned in the article. My environment: Windows 10, RTX 2080, cuda 10.0, cudnn 7.3, VS2017

**Comment by joseortiz3** [comment] 2018-10-07 21:10
@RainyRen Yep, that's what I found too, said it in my last comment. Hope the problems with the `eigen` compute stuff and `protobuf`-`python3.7` compatibility get fixed soon.

**Comment by ymodak** [comment] 2018-10-12 00:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-12 00:03 UTC
Labels: stat:awaiting response
