### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /home/selena/pcn-master/pc_distance/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow15OpKernelContext10CtxFailureEPKciRKNS_6StatusE

### ISSUE THREAD

**Issue by HappySelena** [tensorflow/tensorflow#22432] opened 2018-09-21 03:32 UTC
Error Message:
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    model_module = importlib.import_module('.%s' % args.model_type, 'models')
  File "/home/selena/miniconda2/envs/tensorflow/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/selena/pcn-master/models/pcn_cd.py", line 2, in <module>
    from tf_util import mlp, mlp_conv, chamfer, add_train_summary, add_valid_summary
  File "/home/selena/pcn-master/tf_util.py", line 2, in <module>
    from pc_distance import tf_nndistance, tf_approxmatch
  File "/home/selena/pcn-master/pc_distance/tf_nndistance.py", line 5, in <module>
    nn_distance_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_nndistance_so.so'))
  File "/home/selena/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/selena/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/selena/pcn-master/pc_distance/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow15OpKernelContext10CtxFailureEPKciRKNS_6StatusE

MakeFile:
 cuda_inc = /usr/local/cuda-9.0/include/
cuda_lib = /usr/local/cuda-9.0/lib64/
nsync = /home/selena/miniconda2/envs/tensorflow/lib/python3.5/site-packages/external/nsync/public
nvcc = /usr/local/cuda-9.0/bin/nvcc
tf_inc = /home/selena/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/include
tf_lib = /home/selena/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow

all: tf_nndistance_so.so tf_approxmatch_so.so

tf_nndistance.cu.o: tf_nndistance.cu
	$(nvcc) tf_nndistance.cu -o tf_nndistance.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

tf_nndistance_so.so: tf_nndistance.cpp tf_nndistance.cu.o
	g++ tf_nndistance.cpp tf_nndistance.cu.o -o tf_nndistance_so.so \
	-I $(cuda_inc) -I $(tf_inc) -I $(nsync) \
	-L $(cuda_lib) -lcudart -L $(tf_lib) -ltensorflow_framework \
    -shared -std=c++11 -fPIC -O2

tf_approxmatch.cu.o: tf_approxmatch.cu
	$(nvcc) tf_approxmatch.cu -o tf_approxmatch.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

tf_approxmatch_so.so: tf_approxmatch.cpp tf_approxmatch.cu.o
	g++ -shared $(CPPFLAGS) tf_approxmatch.cpp tf_approxmatch.cu.o -o tf_approxmatch_so.so \
	-I $(cuda_inc) -I $(tf_inc) -I $(nsync) \
	-L $(cuda_lib) -lcudart -L $(tf_lib) -ltensorflow_framework \
    -shared -std=c++11 -fPIC -O2

clean:
	rm -rf *.o *.so

Cuda:9.0
TensorFlow: 1.5.0

**Comment by tensorflowbutler** [comment] 2018-09-21 18:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment] 2018-09-28 18:04
@HappySelena Hi, could you please describe the issue clearly.

**Comment by harshini-gadige** [comment] 2018-10-05 17:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-10-05 17:06 UTC
Labels: stat:awaiting response
