### ISSUE TITLE
Tensorboard conda envs not working

### ISSUE THREAD

**Issue by BBeuker** [tensorflow/tensorflow#8440] opened 2017-03-15 17:30 UTC
Hi guys,

I am having a rather weird problem, which I hope someone here can solve. I am currently using the newest version of anaconda to create a python 3.5 environment with Tensorflow r1.0 installed. Inside my script I am perfectly able to create event files that should contain my Tensorflow graph, the script opens a writer that uses the tf.session graph as the graph and I create namescopes for the layers, weights and biases (Neural Network).

Upon running an event file gets generated that also can be used to open up tensorboard from my command prompt. This generates an localhost:6006 which can be opened perfectly fine but there is no graph where it should be. Additionally when I use the tensorboard inspect logdir command it tells me the event file is found. Now I have no idea if it is a tensorboard problem, an installation problem or a script problem. 

Does this perhaps sound familiar to anyone? Or is anyone perhaps able to open my event file? Would love to figure this out.

[events.out.tfevents.1489598042.EH39G4DC.zip](https://github.com/tensorflow/tensorflow/files/845479/events.out.tfevents.1489598042.EH39G4DC.zip)

If needed i can upload my script! Thanks alot!

**Comment by aselle** [comment] 2017-03-21 22:04
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. In addition, include a simple reproducible test case. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by asimshankar** [comment] 2017-04-08 07:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-04-08 07:13 UTC
Labels: stat:awaiting response, type:support

**Comment by TugbaAtici** [comment] 2017-05-10 12:58
I have the exact same problem! Does anyone know how to fix this problem?
