### ISSUE TITLE
eigh fails with 26x26 zero matrix on GPU with eager execution

### ISSUE THREAD

**Issue by charmasaur** [tensorflow/tensorflow#47661] opened 2021-03-09 01:53 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.7.6
- CUDA/cuDNN version: 11.0
- GPU model and memory: Tesla T4 16GB

**Describe the current behavior**
`tf.linalg.eigh` fails with `InternalError: tensorflow/core/util/cuda_solvers.cc:648: cuSolverDN call failed with status =7 [Op:SelfAdjointEigV2]` on a 26x26 (and larger) zero matrix when used with both GPU and eager execution. It works with other combinations of eager/graph execution and CPU/GPU.

**Describe the expected behavior**
Eigendecomposition should be successfully calculated.

**Standalone code to reproduce the issue**
```
# Needs to have GPU
import tensorflow as tf
tf.linalg.eigh(tf.zeros((26, 26), dtype=tf.float64))
```
Also see gist: https://colab.research.google.com/drive/1x5sfDIGJdDNOgqpaH7OBrnENfgE14ZQ0?usp=sharing

**Comment by sanjoy** [comment] 2021-05-20 04:28
Works fine on TF nightly now.  Can you please cross check?

**Comment by rmothukuru** [comment] 2021-05-20 04:47
@charmasaur,
As per [sanjoy's comment](https://github.com/tensorflow/tensorflow/issues/47661#issuecomment-844677445), the issue is fixed in the TF Nightly. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/0dd6b435709d08c0f20883e349fdce9e/47661.ipynb) of the working code. Thanks!

**Comment by charmasaur** [comment] 2021-05-20 05:00
@rmothukuru unfortunately I don't think that test is accurate: notice that `print(device_lib.list_local_devices())` only detects a CPU, which suggests that the op isn't actually running on GPU.

**Comment by charmasaur** [comment] 2021-05-27 05:57
This still seems to be broken.

**Comment by charmasaur** [comment] 2021-09-29 06:10
Seems to have been fixed upstream: https://docs.nvidia.com/cuda/archive/11.0/cuda-toolkit-release-notes/index.html#cusolver-resolved-issues

I'm pretty confused by CUDA/cuSOLVER versions though. [NVIDIA says](https://docs.nvidia.com/cuda/archive/11.0/cuda-toolkit-release-notes/index.html#cuda-major-component-versions) that the bug got fixed in CUDA 11.0 / cuSOLVER 10.6.0.245, but TF 2.4 (which is broken) is [meant to](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0) be using CUDA 11 (and messing around on Colab, if I install TF 2.4 then running `!ls /usr/local/cuda-11.0/lib64/libcusolver*` suggests that `10.6.0.245` is indeed present).

Maybe an older version is getting statically compiled in?

In any case, I guess this is now fixed.

**Comment by sushreebarsa** [comment] 2022-05-19 09:30
@charmasaur Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/1d537606b5b00733488f421af1805b60/untitled358.ipynb) and confirm if it has been fixed in latest TF version.
Thank you!

**Comment by charmasaur** [comment] 2022-05-20 05:11
LGTM, thanks!

**Comment by sushreebarsa** [comment] 2022-05-20 05:14
Hi @charmasaur! Thank you for the update.
Could you move this issue to closed status if it is resolved?
Thank you!

**Closed** 2022-05-20 05:28 UTC
Labels: stat:awaiting response, type:bug, comp:gpu, TF 2.3
