### ISSUE TITLE
FusedBatchNorm does not support 3D Filters

### ISSUE THREAD

**Issue by tomrunia** [tensorflow/tensorflow#5694] opened 2016-11-18 16:37 UTC
The current implementation of `tf.contrib.layers.batch_norm` is quite slow with the default parameters. Recent builds of TF support `fused=True` which forces the use of the faster `nn.fused_batch_norm`. However this method does not support 3D filters for computing the mean and variance. The normal (slower) variant with `fused=False` does not have this problem.

**FusedBatchNorm**:
```python
# Following error is raised when trying to batch normalize 3D filters
elif original_rank not in [2, 4]:
      raise ValueError('Inputs %s has unsupported rank. \
          Expected 2 or 4 but got %d' % (inputs.name, original_rank))
```

And the default implementation without the fused version uses these axis to compute the `tf.nn.moments`:

```python
axis = list(range(inputs_rank - 1))
```

This also works for 3D filters of course. See code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L483

**Comment by zhangyaobit** [comment] 2016-11-22 05:42
@tomrunia, thanks for filing the issue! 

I believe 3D filters including both NCW and NWC could be supported in a similar way to that of convolution: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L766

I'll label this as contribution welcome for now.

**Comment by tomrunia** [comment] 2016-11-30 17:56
As a work-around I now use `tf.reshape` to merge the WxH so the 5D tensor becomes 4D. Then I am able to use `tf.nn.fused_batch_norm()`. After the batch normalization I reshape the tensor again to get the 5D tensor back. This speeds up training time with 20% compared to using the non-fused version of batch normalization.

**Comment by siddharth-agrawal** [comment] 2016-12-19 13:51
@zhangyaobit I'm working on this issue.

**Comment by siddharth-agrawal** [comment] 2016-12-19 14:57
@zhangyaobit I investigated into the issue. The C++ implementation of `FusedBatchNorm` depends on [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/stream.cc#L280) in `stream.cc` which uses the underlying cuDNN implementation from what I can see. Thus, the solution you suggested can work for 1D filters but not for 3D. But as @tomrunia suggested we can have a workaround. Let me know if I should make changes only for 1D filters or write a special case for 3D filters as well.

**Comment by zhangyaobit** [comment] 2016-12-22 01:12
@siddharth-agrawal Please note that how the code currently handles the case when the input is 2D (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L233): the input is reshaped to a 4D shape [-1, 1, 1, channels].

I believe this is essentially the same as the workaround by @tomrunia, where the 5D input is reshaped to 4D. For the 3D case, say NWC, you can do the same to reshape from [N, W, C] to [-1, 1, W, C]. 

I think you can add both the 5D and 3D case inside _fused_batch_norm (while @tomrunia is doing it outside _fused_batch_norm), in addition to the 2d case, which is currently already supported.

Please let me know if this works.

**Comment by raphtown** [comment] 2017-02-22 02:03
Hello,


Has there been any progress on getting fused_batch_norm working on 3D data?

Up until now I was using tf.contrib.layers.batch_norm, but due to tf.nn.moments returning negative values for variance (as reported [here](https://github.com/tensorflow/tensorflow/issues/3290)),  I am forced to switch to fused_batch_norm.  I suspect many people dealing with 3D data will be running into similar problems.

Thanks.

**Comment by zhangyaobit** [comment] 2017-02-26 23:44
Could you use the workaround suggested by @tomrunia to reshape the data to 3D?

**Comment by raphtown** [comment] 2017-02-27 18:31
Yes, that does seem to work for now.  Thank you.

**Comment by zhangyaobit** [comment] 2017-02-28 06:34
This is currently marked as contributions welcome! 

Essentially, to do the same "reshaping business", but inside the fused_batch_norm function.

**Comment by raphtown** [comment] 2017-02-28 08:19
Ah, I see that now!  If I have the time I will give it a try :)

**Comment by girving** [comment] 2017-06-16 18:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 18:36 UTC
Labels: stat:contributions welcome

**Comment by happyharrycn** [comment] 2017-07-05 03:37
I do not think the issue is fully resolved. And the lack of fused batch norm can be a critical performance issue for networks with 3D convolutions. I have done the modification in _fused_batch_norm as suggested by @zhangyaobit. Yet, I do see the [to-do comment](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/normalization.py#L144) in normalization.py, which is more fundamental. I am willing to send a PR if that to-do action will not be implemented any time soon.

**Comment by ziyuang** [comment] 2018-03-06 17:09
@tomrunia how did you merge WxH? I tried

```
# net is the output of conv3d
orig_shape = tf.shape(net)
workaround_shape = (orig_shape[0], orig_shape[1], orig_shape[2]*orig_shape[3], orig_shape[4])
net = tf.reshape(net, workaround_shape)
net = tf.layers.batch_normalization(net, training=True)
net = tf.reshape(net, orig_shape)
```
But TensorFlow will complain at the `batch_normalization` line:
```
File "~/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 253, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(None)]))
```

**Comment by appyfizzA** [comment] 2018-06-12 11:08
@happyharrycn 
I'm working with 5D tensors and 3D convolutions with TF 1.7.0
Has this issue been resolved?

**Comment by appyfizzA** [comment] 2018-06-13 06:05
@happyharrycn Also, if nn.moments were not returning negative variance, we could give axes as [0,1,2,3] for 5D tensors and 3D convolutions, right? Because nn.batch_normalization takes tensors of any size.
