### ISSUE TITLE
dnn_linear_combined.py is not compatible with Python 3

### ISSUE THREAD

**Issue by eyewy** [tensorflow/tensorflow#3200] opened 2016-07-06 05:01 UTC
in Python 3.x, line 215 of dnn_linear_combined.py (master version) results in an error.

**line 215 is:**
return sorted(set(self._dnn_feature_columns)) if self._dnn_feature_columns else None

**the error is:**
builtins.TypeError: unorderable types: _SparseColumnHashed() < str()

**to reproduce this error:**
in wide_n_deep_tutorial.py, change the following line:
feature_cols = dict(continuous_cols.items() + categorical_cols.items())
to
feature_cols = {_**continuous_cols , *_*categorical_cols}
this change makes wide_n_deep_tutorial.py compatible with Python 3.x.
Now simply run it like:
python3.5 wide_n_deep_tutorial.py --model_type=wide_n_deep

**Comment by aselle** [comment] 2016-07-07 18:11
That only works on 3.5 or higher, so it would make it incompatible with python 2.x  so maybe we should do
feature_cols = dict(continuous_cols)
feature_cols.update(categorical_cols)

**Comment by aselle** [comment] 2016-07-07 18:15
@hengtze could you take a look at the fix and integrate it if possible?

**Comment by eyewy** [comment] 2016-07-09 01:36
But the error in line 215 of dnn_linear_combined.py still persists.

**Comment by wtusm** [comment] 2016-07-09 03:15
yes

**Comment by wtusm** [comment] 2016-07-09 03:16
under the python3.5, the newest wide_n_deep_tutorial.py still encounter the  problem of "TypeError: unorderable types: _SparseColumnHashed() < str()"

**Comment by skywildworld** [comment] 2016-07-09 18:35
This works fine for me(python 3.4).
Change function _get_dnn_feature_columns in learn/python/learn/estimators/dnn_linear_combined.py as:

def _get_dnn_feature_columns(self):
    return sorted(
        set(self._dnn_feature_columns),
        key=lambda x: x.key) if self._dnn_feature_columns else None

**Comment by eyewy** [comment] 2016-07-09 22:12
Thanks, checked with 3.5, and your solution solves the issue.

**Comment by Vitiell0** [comment] 2016-07-10 05:45
I had the same _SparseColumnHashed() < str() error on wide_n_deep_tutorial.py 

The change skywildworld suggested fixed it for me as well on 3.5

**Comment by jmchen-g** [comment] 2016-07-11 18:37
@hengtze could you take a look at this please?

**Comment by hengtze** [comment] 2016-07-11 20:44
No problem. I'll take a look again. Thanks for reporting the issue!

**Comment by hengtze** [comment] 2016-07-13 22:57
I'm not sure how the change that @skywildworld suggested would fix the problem.

If you look at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py#L236

def _get_dnn_feature_columns(self):
    if not self._dnn_feature_columns:
      return None
    feature_column_ops.check_feature_columns(self._dnn_feature_columns)
    return sorted(set(self._dnn_feature_columns), key=lambda x: x.key)

It's doing the same operations (except the line feature_column_ops.check_feature_columns). Since  @eyewy mentioned "line 215" of dnn_linear_combined.py, I wonder if some people are running older versions of the code. Can someone confirm that this issue occurs with the latest version of the code, and that skywildworld's solution fixes the issue?

**Comment by JulianNorton** [comment] 2016-07-20 01:29
@hengtze 
I can confirm this issue is present in the most recent version of code. I was trying to do the tutorial here: https://www.tensorflow.org/versions/r0.9/tutorials/wide/index.html using [this code](https://github.com/JulianNorton/trump-weather/blob/87062b07e037e1c3dedb06bd45c95d222e175f85/tensor-flow.py).

Python 3.5.1
Tensorflow 0.9.0


### Problem
```
def _get_dnn_feature_columns(self):
      return sorted(
        set(self._dnn_feature_columns),
        key=lambda x: x.key) if self._dnn_feature_columns else None
```
in dnn_linear_combined.py was causing the issue as @skywildworld mentioned.

```
  File "/usr/local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 216, in _get_dnn_feature_columns
    self._dnn_feature_columns)) if self._dnn_feature_columns else None
TypeError: unorderable types: _SparseColumnKeys() < str()
```

### solution
Change line 214 in `dnn_linear_combined.py`

```
def _get_dnn_feature_columns(self):
      return sorted(
        set(self._dnn_feature_columns),
        key=lambda x: x.key) if self._dnn_feature_columns else None
``` 

and now the program works with this output

```
accuracy: 0.820588
eval_auc: 0.8732
loss: 1.13403
```

**Comment by gunan** [comment] 2017-01-04 06:04
I see that the suggested changes have been made to the file.
https://github.com/tensorflow/tensorflow/commit/ab30c2d368ecd7fc691de15a1a8b242ad59bc2af seems to have resolved this. Closing issue.

**Closed by gunan** 2017-01-04 06:04 UTC
Labels: bug
