### ISSUE TITLE
Possibly serious bug in cuDNN RNNParamsSaveable

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#9370] opened 2017-04-21 17:19 UTC
`RNNParamsSaveable` appears to only save half of the weights when the RNN is bidirectional. See below.

When the RNN is unidirectional, `model.params_size()` matches the total size of weights + biases returned by `model.params_to_canonical(params)`

```
model = cudnn_rnn_ops.CudnnLSTM(num_layers=1, num_units=100, input_size=20, direction='unidirectional')
params = tf.get_variable('cudnn_rnn_params', initializer=tf.random_uniform([model.params_size()]), validate_shape=False)
model.params_size().eval(session=sess) # returns 48800
sum([wts.eval(session=sess).shape[0] for wtss in model.params_to_canonical(params) for wts in wtss]) # returns 48800
```

On the other hand, when the RNN is bidirectional, `model.params_size()` returns twice the size of the unidirectional case, which makes sense, but the size of `model.params_to_canonical(params)` is unchanged.

```
model = cudnn_rnn_ops.CudnnLSTM(num_layers=1, num_units=100, input_size=20, direction='bidirectional')
params = tf.get_variable('cudnn_rnn_params', initializer=tf.random_uniform([model.params_size()]), validate_shape=False)
model.params_size().eval(session=sess) # returns 97600
sum([wts.eval(session=sess).shape[0] for wtss in model.params_to_canonical(params) for wts in wtss]) # returns 48800
```

I believe this may have been missed by tests because, as this [TODO](https://github.com/tensorflow/tensorflow/blob/f0f7a1ef63c47075e3eb7eaeeb3588d057f3171d/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py#L37) suggests, both the canonical and non-canonical versions are being saved and restored, and so even if only half the weights are being restored from the canonical version, the non-canonical weights can compensate and hide the problem.

Am I missing something?

**Comment by drpngx** [comment] 2017-04-22 17:06
@ebrevdo any comment on this? Is this a documentation or usage issue?

**Comment by alquraishi** [comment] 2017-05-05 11:46
And updates on this?

**Comment by zhangyaobit** [comment] 2017-05-06 21:43
@alquraishi, thanks for reporting the issue. This does look like a bug/feature request. @boche also reported a related (potentially the same) issue here: https://github.com/tensorflow/tensorflow/issues/6072

I looked into the code and currently the code only stores params for forward direction, as you have observed. So I don't think checkpointing for the bidirectional the case is currently working/supported.

The unknown param order (in the bidirectional case) problem @boche raised is a valid question. I looked in the cuDNN documentation. The order (in the bidirectional case) is not documented for function cudnnGetRNNLinLayerMatrixParams and  cudnnGetRNNLinLayerBiasParams. Another possibility is that the backward params are accessed by the "layer" parameter in these two functions. However, it is also not clear if this is the case in the cuDNN documentation.

I marked this as contribution welcome for interested people to take a deeper look from here and possibly propose and work on a fix.

**Comment by ebrevdo** [comment] 2017-05-06 21:45
We should consider also contacting nvidia for clarification in their
documentation.

**Comment by zhangyaobit** [comment] 2017-05-06 21:57
Good point. Assigning @zheng-xq

**Comment by alquraishi** [comment] 2017-05-07 01:51
May I suggest that this gets documented very clearly as a limitation, perhaps even preventing the user from accidentally using RNNParamsSaver with a bidirectional RNN? I understand the temptation to mark this as contributions welcome and set it aside, but I really do think it's a very serious bug. What makes it particularly problematic is that it's completely silent, so a user may suddenly see their model behaving inexplicably without any idea why. The only reason I stumbled onto this is because I noticed the size difference by accident, otherwise I would've merrily used it without realizing there's a hidden bug, and I routinely checkpoint models on one GPU type and resume on another, so it's not an unlikely scenario. Just my two cents. Of course ideally the problem would get solved.

**Comment by alquraishi** [comment] 2017-05-17 20:48
Any updates on this?

**Comment by zhangyaobit** [comment] 2017-05-18 06:27
@alquraishi, we haven't had time to look into this. We provided this checkpointing feature for cuDNN and I'm glad you find it useful and seem to be a heavy user of it. If you think you benefit from this feature, please consider registering as a contributor and contributing back to improve it. We could together make TensorFlow better. I like your idea of better documentation. And if you could help dive deeper (from my previous suggestions) into the bidirectional RNN issue you found, that would be even better. Please consider registering as NVIDIA developer as well to ask them about the bidirectional RNN layout. 

We just haven't found a time to look into this, ebrevdo@ and zheng-xq@ will follow up when they get a chance.

**Comment by albertz** [comment] 2017-07-05 08:42
This is not a bug in the checkpointing nor in `RNNParamsSaveable`.

This is a bug in the `CudnnRNNParamsToCanonical` op or in `CudnnSupport::createRnnDescriptor` or even in cuDNN itself.

Note that the test also seems to be not correct. You are only summing `shape[0]`. But you should sum `prod(shape)`. I wonder why that worked for you in the unidirectional case. It does not for me.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:31
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-06 18:57
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by protoget** [comment] 2018-01-06 19:50
This class is deprecated. The new CudnnRNN layers manages vars and saveables for users.

**Closed by protoget** 2018-01-06 19:50 UTC
Labels: stat:awaiting tensorflower, stat:contributions welcome, type:bug/performance
