### ISSUE TITLE
HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tuomassiren** [tensorflow/tensorflow#36141] opened 2020-01-22 20:24 UTC
**System information**
- Linux tutkain 4.19.93-v7l+ #1290 SMP Fri Jan 10 16:45:11 GMT 2020 armv7l GNU/Linux
- Debian 10.2 on Raspberry PI 4+ 4GB

**Describe the problem**
(venv) tas@tutkain:~ $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2020-01-22 20:21:52.312444: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Tensor("Sum:0", shape=(), dtype=float32)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Installation exactly as described https://www.tensorflow.org/install/pip

**Any other info / logs**
(venv) tas@tutkain:~ $ pip list
Package              Version
-------------------- ---------
absl-py              0.9.0
asn1crypto           0.24.0
astor                0.8.1
cachetools           4.0.0
certifi              2018.8.24
chardet              3.0.4
cryptography         2.6.1
distro-info          0.21
entrypoints          0.3
gast                 0.2.2
google-auth          1.10.2
google-auth-oauthlib 0.4.1
google-pasta         0.1.8
grpcio               1.26.0
h5py                 2.8.0
idna                 2.6
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
keyring              17.1.1
keyrings.alt         3.1.1
Markdown             3.1.1
numpy                1.16.2
oauthlib             3.1.0
opt-einsum           3.1.0
pip                  20.0.1
protobuf             3.11.2
pyasn1               0.4.8
pyasn1-modules       0.2.8
pycrypto             2.6.1
pycurl               7.43.0.2
PyGObject            3.30.4
python-apt           1.8.4
pyxdg                0.25
requests             2.21.0
requests-oauthlib    1.3.0
rsa                  4.0
SecretStorage        2.3.1
setuptools           45.1.0
six                  1.12.0
ssh-import-id        5.7
tensorboard          2.0.2
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
unattended-upgrades  0.1
urllib3              1.24.1
virtualenv           16.7.9
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2

**Comment by mihaimaruseac** [comment] 2020-01-22 21:13
Do you have `libhdf.so` in a searchable location? Is it at the right version?

**Comment by tuomassiren** [comment] 2020-01-22 22:21
> Do you have `libhdf.so` in a searchable location? Is it at the right version?

I do not think so. If that would be the case, it would work as expected, obviously.

The point being, installation instructions at https://www.tensorflow.org/install/pip **do not mention anything** about `libhdf.so`. 

Problem with the package, should work out-of-the box without manually installing a missing dependency. Before this is fixed, a **validated** workaround is appreciated. 

There's a duplicate issue #35462 which was closed without resolution.

**Comment by mihaimaruseac** [comment] 2020-01-22 23:23
Hadoop file system requires additional setup on your system, which can be found on [Hadoop project's page](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html)

We cannot document how to install all third party libraries in all operating systems and all environments in the world. The world is not just a "install this one thing and everything must work now" type of thing.

You only need `libhdf.so` if you use the Hadoop file system and if you want to use that you have to install it properly.

I am closing the issue but please reopen if you still get an error in TF after installing Hadoop and confirming that Hadoop works outside of TF.

**Comment by mihaimaruseac** [comment] 2020-01-22 23:24
Reopening, as it seems your error is related to #32885, not to wanting to use the Hadoop filesystem

**Comment by tuomassiren** [comment] 2020-01-23 07:19
> We cannot document how to install all third party libraries in all operating systems and all environments in the world.
> The world is not just a "install this one thing and everything must work now" type of thing.

Straw man. It's **your** application that requires the 3rd party library by default, out-of-the-box. Not **my** code, system nor environment.

And hell yeah. The world is full of crappy second class open source software with incorrect documentation, non-working sample code and tons of open critical issues.
Resume the tradition, keep up the good work. 
 
> You only need `libhdf.so` if you use the Hadoop file system and if you want to use that you have to install it properly.

Finally we're getting _somewhere_. Not using Hadoop file system. 
Obviously you didn't read the [installation instructions](https://www.tensorflow.org/install/pip).

_Verify the install:_
```
(venv) tas@tutkain:~ $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2020-01-22 20:21:52.312444: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Tensor("Sum:0", shape=(), dtype=float32)
```

**Comment by mihaimaruseac** [comment] 2020-01-23 16:35
Can you use TF 1.15 or TF 2.1 (or TF 2.0) instead of TF 1.14?

See #32885.

**Comment by MarcoLeti** [comment] 2020-01-28 19:21
Same problem here, is there a resolution by any chance? Thanks

**Comment by ravikyram** [comment] 2020-01-29 10:41
@tuomassiren 

Can you please confirm if @mihaimaruseac's suggestion is working for you.Thanks!

**Comment by MarcoLeti** [comment] 2020-01-29 10:47
@ravikyram I am using TF > 2.0 installed with "pip install --upgrade tensorflow" but I got the same error. I am trying TF on a RaspPi 4 with Raspbian.

**Comment by mihaimaruseac** [comment] 2020-01-29 16:52
@MarcoLeti can you post output of `pip freeze`?

**Comment by MarcoLeti** [comment] 2020-01-29 19:28
I checked and I don't know why I have version 1.14, could you please advise? (pip version 20.0.2)

absl-py==0.9.0
astor==0.8.1
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
gast==0.2.2
google-auth==1.11.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.26.0
h5py==2.10.0
idna==2.8
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.18.1
oauthlib==3.1.0
opencv-python==3.4.6.27
opt-einsum==3.1.0
pkg-resources==0.0.0
protobuf==3.11.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
six==1.14.0
tensorboard==2.0.2
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
urllib3==1.25.8
Werkzeug==0.16.0
wrapt==1.11.2

**Comment by mihaimaruseac** [comment] 2020-01-29 19:58
@MarcoLeti please post the output of running `pip uninstall tensorflow tensorflow-estimator && pip install tensorflow==2.1`. Please use ` ``` ` before and after the output so the output is properly formatted.

**Comment by MarcoLeti** [comment] 2020-01-29 19:59
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.1 (from versions: 0.11.0, 1.12.0, 1.13.1, 1.14.0)
ERROR: No matching distribution found for tensorflow==2.1
```

**Comment by mihaimaruseac** [comment] 2020-01-29 20:02
What is the output of `pip version` and `pip debug verbose`?

**Comment by MarcoLeti** [comment] 2020-01-29 20:04
```
pip3 --version
pip 20.0.2 from /home/pi/Git/computer-vision/comp-vision/lib/python3.7/site-packages/pip (python 3.7)
```
```
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 20.0.2 from /home/pi/Git/computer-vision/comp-vision/lib/python3.7/site-packages/pip (python 3.7)
sys.version: 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0]
sys.executable: /home/pi/Git/computer-vision/comp-vision/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: iso8859-1
locale.getpreferredencoding: ISO-8859-1
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: global
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /home/pi/Git/computer-vision/comp-vision/lib/python3.7/site-packages/pip/_vendor/certifi/cacert.pem
Compatible tags: 44
  cp37-cp37m-manylinux2014_armv7l
  cp37-cp37m-linux_armv7l
  cp37-abi3-manylinux2014_armv7l
  cp37-abi3-linux_armv7l
  cp37-none-manylinux2014_armv7l
  cp37-none-linux_armv7l
  cp36-abi3-manylinux2014_armv7l
  cp36-abi3-linux_armv7l
  cp35-abi3-manylinux2014_armv7l
  cp35-abi3-linux_armv7l
  cp34-abi3-manylinux2014_armv7l
  cp34-abi3-linux_armv7l
  cp33-abi3-manylinux2014_armv7l
  cp33-abi3-linux_armv7l
  cp32-abi3-manylinux2014_armv7l
  cp32-abi3-linux_armv7l
  py37-none-manylinux2014_armv7l
  py37-none-linux_armv7l
  py3-none-manylinux2014_armv7l
  py3-none-linux_armv7l
  py36-none-manylinux2014_armv7l
  py36-none-linux_armv7l
  py35-none-manylinux2014_armv7l
  py35-none-linux_armv7l
  py34-none-manylinux2014_armv7l
  py34-none-linux_armv7l
  py33-none-manylinux2014_armv7l
  py33-none-linux_armv7l
  py32-none-manylinux2014_armv7l
  py32-none-linux_armv7l
  py31-none-manylinux2014_armv7l
  py31-none-linux_armv7l
  py30-none-manylinux2014_armv7l
  py30-none-linux_armv7l
  cp37-none-any
  py37-none-any
  py3-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

**Comment by MarcoLeti** [comment] 2020-01-29 20:15
Unfortunately still the same error and setuptools seems to be upgrade
```
pip3 install --upgrade pip setuptools
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in ./comp-vision/lib/python3.7/site-packages (20.0.2)
Requirement already up-to-date: setuptools in ./comp-vision/lib/python3.7/site-packages (45.1.0)
```

**Comment by mihaimaruseac** [comment] 2020-01-29 20:18
One more attempt at getting more information: `pip install --no-cache-dir -vvv tensorflow==2.1`. Please attach the full log, no matter how long it is

**Comment by mihaimaruseac** [comment] 2020-01-29 20:19
Also try adding `--force-reinstall ` flag on the above command too

**Comment by MarcoLeti** [comment] 2020-01-29 20:33
```
pip3 install --no-cache-dir -vvv tensorflow==2.1
```
[output.txt](https://github.com/tensorflow/tensorflow/files/4130585/output.txt)

**Comment by MarcoLeti** [comment] 2020-01-29 20:34
pip3 install --no-cache-dir -vvv tensorflow==2.1 --force-reinstall
[output2.txt](https://github.com/tensorflow/tensorflow/files/4130590/output2.txt)

**Comment by mihaimaruseac** [comment] 2020-01-29 20:59
None of the wheels that we publish on PyPi (https://pypi.org/project/tensorflow/2.1.0/#files) match the tags supported by your system.

You were able to install 0.11.0, 1.12.0, 1.13.1 and 1.14.0 only because they are on piwheels: https://www.piwheels.org/project/tensorflow/ But note that not all TF versions are there.

I think the only options left are to either get piwheels to upload the new pips (it seems they cannot upload pips after we switched to be manylinux2010 compliant) or to build them yourself from source.

**Comment by MarcoLeti** [comment] 2020-01-30 11:45
Ok, thank you. So basically TF > 1.4 cannot be installed on RaspberryPi through pip and must be built from source? This is not very clear and I also found a lot of people on the web who install it from pip...
Anyway I found this issue that may be useful: #29704

**Comment by mihaimaruseac** [comment] 2020-01-30 16:57
That issue is related to the install issue.

Yes, you are right, you have to build it from source, as we are not managing it ourselves. If people are installing from pip, **on RaspberryPi**, then the pip they use must come from a different source (i.e., someone compiled from source and installed it)

**Comment by baqwas** [comment] 2020-02-03 03:03
> ... you have to build it from source, ... on RaspberryPi,

A sentence to this requirement would save many people many hours. Please don't get _testy_ about a feedback on documentation.

Kind regards.

**Comment by SirPhemmiey** [comment] 2020-02-05 09:16
This issue still persists. Any luck with this?

**Comment by MarcoLeti** [comment] 2020-02-05 14:18
It seems the issue is with version 1.14, you can install version a different version and I think you won't have this problem. Unfortunately you cannot install from pip versions > 1.14. I can advice this repository where you can find already prepared wheels and you can avoid to create your own: https://github.com/PINTO0309/Tensorflow-bin
I installed version 2.1 and it worked for me!

**Comment by baqwas** [comment] 2020-02-06 00:20
@MarcoLeti Thx for the suggestion. I will definitely give it a try. Much appreciated.

Kind regards.

**Comment by baqwas** [comment] 2020-02-07 03:34
I guess I'll drop **arm6l** from consideration and focus more on arm7l, armv8 and aarch64 for my deployments. My mistake in not reading the "_fine print._"

**Comment by Jackie-L-Staiger** [comment] 2020-02-20 10:23
I am still getting this error on my raspberry pi 4, even after installing tensorflow 2.1.0 using the instructions in https://github.com/PINTO0309/Tensorflow-bin. I used the instructions for "Example of Python 3.x + Tensorflow v2 series" since I am using Python 3.7.3

**Comment by SirPhemmiey** [comment] 2020-02-20 11:40
I'm still getting the message however, i can do all my TensorFlow related tasks without issues. So i am guessing that your application should work normally even if this message shows up.

**Comment by Jackie-L-Staiger** [comment] 2020-02-20 19:24
Thanks so much @SirPhemmiey! You're right!

**Comment by SirPhemmiey** [comment] 2020-02-20 19:27
Yeah, man. Give a thumbs up! :)

**Comment by majidsh97** [comment] 2020-02-27 16:43
@SirPhemmiey Ty yes if you print tf.sin(2.2) for example it shows you 0 but if you load a simple model it works fine :)

**Comment by Gabriv93** [comment] 2020-02-28 17:11
So there's no way to find the wheels file of tensorflow >1.14 for arm6l? I have a RaspberryPI 2, I have the same problem of asking me libhdfs when I try to import tensor flow 1.14 and I don't know what to do...

**Comment by mihaimaruseac** [comment] 2020-02-28 17:46
rpi builds are community driven effort at the moment, so unfortunately this means that someone from the community has to build and release the pips.

**Comment by SirPhemmiey** [comment] 2020-02-28 18:44
@Gabriv93 after it shows the error, what else did it say? I don't know about RPi 2 but it works fine in higher models (RPi 3 and 4) even after showing this error message.

**Comment by Gabriv93** [comment] 2020-02-29 11:00
@SirPhemmiey actually it's true, after the error message it takes some seconds to actually import the package but then it seems to work normally... I will see if there will be issues with some scripts, thanks

**Comment by yoyojacky** [comment] 2020-03-04 16:40
![image](https://user-images.githubusercontent.com/6893075/75901613-c3f6b300-5e79-11ea-915c-3c83376c036e.png)
I got the same result.
env:  Raspbian buster  
(pp) pi@raspberrypi:~/pp $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
(pp) pi@raspberrypi:~/pp $ pip freeze
absl-py==0.9.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
decorator==4.4.1
defusedxml==0.6.0
dlib==19.19.0
entrypoints==0.3
gast==0.2.2
google-auth==1.11.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.27.2
h5py==2.10.0
idna==2.9
importlib-metadata==1.3.0
ipykernel==5.1.3
ipython==7.10.2
ipython-genutils==0.2.0
jedi==0.15.2
Jinja2==2.10.3
json5==0.8.5
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyterlab==1.2.4
jupyterlab-server==1.0.6
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.2.1
MarkupSafe==1.1.1
mistune==0.8.4
more-itertools==8.0.2
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
numpy==1.17.4
oauthlib==3.1.0
opencv-python==4.1.1.26
opt-einsum==3.1.0
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
pkg-resources==0.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.2
protobuf==3.11.3
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.5.2
pyqtgraph==0.10.0
pyrsistent==0.15.6
pyserial==3.4
python-dateutil==2.8.1
pyzmq==18.1.1
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
Send2Trash==1.5.0
six==1.13.0
tensorboard==2.0.2
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==1.0.0
wrapt==1.12.0
zipp==0.6.0

**Comment by tensorflowbutler** [comment] 2020-03-21 01:09
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by lclibardi** [comment] 2020-03-22 15:16
**Solution:** Don't use `tensorflow==1.14.0`. Install version `2.X.X` or higher.
 
That's how I stopped getting this error on the Raspberry Pi 4 running Buster v10.

If you want community precompiled wheels, you can get them [here](https://github.com/lhelontra/tensorflow-on-arm/releases).

**Comment by yoyojacky** [comment] 2020-03-26 05:14
@lclibardi Thanks a lot, my environment has been reset , I am going to try version 2.x.x as well .

**Comment by mihaimaruseac** [comment] 2020-03-26 18:01
In this case, can we close the issue as it has been solved?

**Comment by baqwas** [comment] 2020-03-26 18:29
I have no objection to closing the issue owing to any concern that I raised
previously.

Kind regards.

**Closed** 2020-03-26 18:48 UTC
Labels: stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by IanGe2000** [comment] 2020-04-30 13:32
I was installing TensorFlow on my Raspberry 3B, and I countered the same problem when I ask python3 to `import tensorflow`
and then things get magical:
I repeat the same order, and it made no complains, I even take a easy test and it nailed that as well.

**Comment by baqwas** [comment] 2020-04-30 14:07
Can you try the same with RPi0, please (if practical without too much extra
effort)? Thanks.

**Comment by mihaimaruseac** [comment] 2020-04-30 16:41
@IanGe2000 it is just a warning, so something like this should not print warning the second time:

```
$ python
> import tensorflow as tf
... prints warnings and stuff ...
> import tensorflow as tf
>
```

That is because all these warnings are printed only once, mostly

**Comment by ckcampbell248** [comment] 2020-05-08 18:39
> **Solution:** Don't use `tensorflow==1.14.0`. Install version `2.X.X` or higher.
> 
> That's how I stopped getting this error on the Raspberry Pi 4 running Buster v10.
> 
> If you want community precompiled wheels, you can get them [here](https://github.com/lhelontra/tensorflow-on-arm/releases).

Thanks to @lclibardi for this solution!

For the record, I executed "pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.1.0/tensorflow-2.1.0-cp37-none-linux_armv7l.whl" on my Pi 4 and my code ran...HDFS error gone!

**Comment by slowrunner** [comment] 2020-08-15 14:24
> For the record, I executed "pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.1.0/tensorflow-2.1.0-cp37-none-linux_armv7l.whl" on my Pi 4 and my code ran...HDFS error gone!

Thanks - worked for me rebuilding my Pi3B with Pi OS
```Linux deskpi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux ```

**Comment by TheAshwanik** [comment] 2020-08-16 10:33
> I executed "pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.1.0/tensorflow-2.1.0-cp37-none-linux_armv7l.whl" on my Pi 4 and my code ran...HDFS error gone!

This solved my issues as well.
