### ISSUE TITLE
Broken build due to LLVM

### ISSUE THREAD

**Issue by Ganesh-Devdas** [tensorflow/tensorflow#60922] opened 2023-06-19 14:47 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

No

### OS Platform and Distribution

Debian Bookworm plus Clang/LLVM 17.0.0 (experimental)

### Mobile device

not applicable

### Python version

3.11.4

### Bazel version

5.3.0 - as per original configuration

### GCC/Compiler version

GCC 12.2.0 / Clang 16.0.6 / Clang 17.0.0

### CUDA/cuDNN version

NO

### GPU model and memory

nothing to do with that

### Current Behaviour?

Compilation fails due to:
Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/b9232f9e27e5668bc0414879dcdedb2a59ea75f2.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/659147817805d17c7be2d60bd7bbca7e780f9c82.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/91d765cad5599f9710973d3e34d4dc22583e2e79.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

### Standalone code to reproduce the issue

```shell
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=/usr/lib/llvm-17/bin:${JAVA_HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Failure occurs for all compiler mentioned above:
Commands/examples:
CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow:tensorflow_cc 2>&1 | tee ../build-tensorflow_cc.log
CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow:tensorflow_framework 2>&1 | tee ../build-tensorflow_framework.log
CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow/tools/pip_package:build_pip_package 2>&1 | tee ../build-tensorflow_py3.log
```

I have also cleaned bazel cache directory and checked urls( not available also 404)

### Relevant log output

```shell
1). CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow:tensorflow_cc 2>&1 | tee ../build-tensorflow_cc.log

Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.11/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tpu in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=with_tpu_support=true
INFO: Found applicable config definition build:linux in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/91d765cad5599f9710973d3e34d4dc22583e2e79.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Loading: 0 packages loaded
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow:tensorflow_cc (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow:tensorflow_cc (34 packages loaded, 15 targets configured)
Analyzing: target //tensorflow:tensorflow_cc (34 packages loaded, 15 targets configured)
Analyzing: target //tensorflow:tensorflow_cc (34 packages loaded, 15 targets configured)
Analyzing: target //tensorflow:tensorflow_cc (95 packages loaded, 215 targets configured)
Analyzing: target //tensorflow:tensorflow_cc (424 packages loaded, 24010 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/659147817805d17c7be2d60bd7bbca7e780f9c82.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow:tensorflow_cc (427 packages loaded, 25063 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/b9232f9e27e5668bc0414879dcdedb2a59ea75f2.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow:tensorflow_cc (428 packages loaded, 26822 targets configured).
INFO: Found 1 target...
[0 / 7,736] [Prepa] Writing file tensorflow/libtensorflow_cc.so.2.12.0-2.params ... (4 actions, 0 running)
[277 / 9,815] Compiling llvm/lib/Support/Signals.cpp; 4s local ... (8 actions, 7 running)
ERROR: /home/...../.cache/bazel/_bazel_root/9c8aaa3c6704dd9093a3ba260ef8cc3f/external/llvm-project/llvm/BUILD.bazel:356:11: Compiling llvm/lib/TableGen/TableGenBackendSkeleton.cpp failed: undeclared inclusion(s) in rule '@llvm-project//llvm:TableGen':
this rule is missing dependency declarations for the following files included by 'llvm/lib/TableGen/TableGenBackendSkeleton.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow:tensorflow_cc failed to build
INFO: Elapsed time: 213.824s, Critical Path: 16.79s
INFO: 299 processes: 259 internal, 40 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

2). CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow:tensorflow_framework 2>&1 | tee ../build-tensorflow_framework.log
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.11/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tpu in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=with_tpu_support=true
INFO: Found applicable config definition build:linux in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
Loading: 
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/91d765cad5599f9710973d3e34d4dc22583e2e79.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow:tensorflow_framework (0 packages loaded, 0 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/b9232f9e27e5668bc0414879dcdedb2a59ea75f2.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow:tensorflow_framework (0 packages loaded, 1 target configured).
INFO: Found 1 target...
[3 / 204] [Prepa] Writing script tensorflow/tsl/platform/status.cppmap ... (2 actions, 0 running)
[13 / 1,949] Compiling src/google/protobuf/compiler/cpp/extension.cc; 1s local ... (8 actions, 7 running)
[13 / 1,949] Compiling src/google/protobuf/compiler/cpp/extension.cc; 2s local ... (8 actions running)
[18 / 1,949] Compiling src/google/protobuf/compiler/java/message.cc; 3s local ... (8 actions running)
[20 / 1,949] Compiling src/google/protobuf/compiler/java/message.cc; 4s local ... (8 actions running)
[21 / 1,949] Compiling src/google/protobuf/compiler/cpp/parse_function_generator.cc; 2s local ... (8 actions running)
[24 / 1,949] Compiling src/google/protobuf/compiler/cpp/parse_function_generator.cc; 3s local ... (8 actions running)
[26 / 1,949] Compiling src/google/protobuf/compiler/cpp/parse_function_generator.cc; 4s local ... (8 actions running)
[27 / 1,949] Compiling src/google/protobuf/compiler/cpp/parse_function_generator.cc; 6s local ... (8 actions running)
[29 / 1,949] Compiling src/google/protobuf/compiler/cpp/parse_function_generator.cc; 7s local ... (8 actions running)
[31 / 1,949] Compiling src/google/protobuf/compiler/php/php_generator.cc; 6s local ... (8 actions running)
[35 / 1,949] Compiling src/google/protobuf/compiler/php/php_generator.cc; 8s local ... (8 actions running)
[37 / 1,949] Compiling src/google/protobuf/compiler/php/php_generator.cc; 10s local ... (8 actions running)
[47 / 1,949] Compiling src/google/protobuf/stubs/substitute.cc; 1s local ... (8 actions running)
[54 / 1,949] Compiling src/google/protobuf/util/field_mask_util.cc; 3s local ... (8 actions running)
[67 / 1,949] Compiling src/google/protobuf/util/message_differencer.cc; 4s local ... (8 actions, 7 running)
[83 / 1,949] Compiling src/google/protobuf/compiler/cpp/enum.cc; 4s local ... (8 actions, 7 running)
[93 / 1,949] Compiling src/google/protobuf/compiler/cpp/message_field.cc; 3s local ... (8 actions, 7 running)
[104 / 1,949] Compiling src/google/protobuf/compiler/cpp/message.cc; 6s local ... (8 actions, 7 running)
[122 / 1,949] Compiling src/google/protobuf/compiler/cpp/message.cc; 12s local ... (8 actions, 7 running)
[141 / 1,949] Compiling src/google/protobuf/wire_format.cc; 4s local ... (8 actions, 7 running)
[161 / 1,949] Compiling src/google/protobuf/descriptor.cc; 6s local ... (8 actions, 7 running)
[176 / 1,949] Compiling src/google/protobuf/descriptor.cc; 16s local ... (8 actions, 7 running)
[217 / 2,179] Compiling src/google/protobuf/compiler/java/extension.cc; 4s local ... (8 actions, 7 running)
ERROR: /home/...../.cache/bazel/_bazel_root/9c8aaa3c6704dd9093a3ba260ef8cc3f/external/llvm-project/llvm/BUILD.bazel:593:11: Compiling llvm/utils/TableGen/Attributes.cpp failed: undeclared inclusion(s) in rule '@llvm-project//llvm:tblgen':
this rule is missing dependency declarations for the following files included by 'llvm/utils/TableGen/Attributes.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow:tensorflow_framework failed to build
INFO: Elapsed time: 92.924s, Critical Path: 31.68s
INFO: 257 processes: 43 internal, 214 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

3). CC=/usr/lib/llvm-17/bin/clang CXX=/usr/lib/llvm-16/bin/clang bazel-5.3.0 build --config=tpu --verbose_failures //tensorflow/tools/pip_package:build_pip_package 2>&1 | tee ../build-tensorflow_py3.log
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.11/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tpu in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=with_tpu_support=true
INFO: Found applicable config definition build:linux in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/...../libtensorflow-dev/tensorflow-2.12.0/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
Loading: 
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/91d765cad5599f9710973d3e34d4dc22583e2e79.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/b9232f9e27e5668bc0414879dcdedb2a59ea75f2.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (66 packages loaded, 992 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (153 packages loaded, 5342 targets configured)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/659147817805d17c7be2d60bd7bbca7e780f9c82.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (158 packages loaded, 6276 targets configured)
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (161 packages loaded, 7843 targets configured).

INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[199 / 8,018] Executing genrule @local_config_python//:python_include; 0s local ... (8 actions, 7 running)
[228 / 8,216] Executing genrule @local_config_python//:python_include; 2s local ... (8 actions running)
[232 / 8,216] Compiling llvm/utils/TableGen/AsmMatcherEmitter.cpp; 3s local ... (8 actions, 7 running)
[232 / 8,216] Compiling llvm/utils/TableGen/AsmMatcherEmitter.cpp; 5s local ... (8 actions running)
ERROR: /home/...../.cache/bazel/_bazel_root/9c8aaa3c6704dd9093a3ba260ef8cc3f/external/llvm-project/llvm/BUILD.bazel:593:11: Compiling llvm/utils/TableGen/AsmWriterInst.cpp failed: undeclared inclusion(s) in rule '@llvm-project//llvm:tblgen':
this rule is missing dependency declarations for the following files included by 'llvm/utils/TableGen/AsmWriterInst.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 11.675s, Critical Path: 6.79s
INFO: 240 processes: 83 internal, 157 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
</details>

**Comment by mihaimaruseac** [comment] 2023-06-20 21:15
Note that the issue is not the dependencies, but an error in LLVM

```
ERROR: /home/...../.cache/bazel/_bazel_root/9c8aaa3c6704dd9093a3ba260ef8cc3f/external/llvm-project/llvm/BUILD.bazel:356:11: Compiling llvm/lib/TableGen/TableGenBackendSkeleton.cpp failed: undeclared inclusion(s) in rule '@llvm-project//llvm:TableGen':
this rule is missing dependency declarations for the following files included by 'llvm/lib/TableGen/TableGenBackendSkeleton.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_zlib/zlib.cppmap'
```

Project dependencies are specified as coming from multiple URLs (the upstream and the mirror). Bazel tries both and reports failure when the first attempt fails, but then look at the second URL and downloads the file from there. The build will be broken much faster if the dependency cannot be downloaded from _both_ upstream and the mirror.

**Comment by ehzawad** [comment] 2023-08-21 17:56
I'm getting the same error while trying to build tensorflow 2.13 (CPU build)
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/129f64c1bf7a2ba048cf317d8c31c367/external/llvm-project/llvm/BUILD.bazel:605:10: Compiling llvm/utils/TableGen/Attributes.cpp [for host] failed: undeclared inclusion(s) in rule '@llvm-project//llvm:llvm-tblgen':
this rule is missing dependency declarations for the following files included by 'llvm/utils/TableGen/Attributes.cpp':
  'bazel-out/host/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/host/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/host/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 57.973s, Critical Path: 13.61s
INFO: 355 processes: 159 internal, 196 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment] 2023-08-21 18:03
This is a nearly daily occurrence. You can wait until a fix lands or try building either from a stable release branch (`r2.13` for example), or if you want from the main branch, trying to find a commit from before a "LLVM integrate" one.

Though now with the XLA and TSL separation, this might also be harder to do, you'd need to keep all of these in sync.

**Comment by mihaimaruseac** [comment] 2023-08-21 18:04
Also, closing this one, since the original issue has been resolved.

**Closed by mihaimaruseac** 2023-08-21 18:04 UTC
Labels: type:build/install, subtype:bazel, TF 2.12
