### ISSUE TITLE
Error converting saved_model.pb to .tflite

### ISSUE THREAD

**Issue by inakaaay** [tensorflow/tensorflow#20804] opened 2018-07-14 18:10 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.5.1-32 bit
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: nothing since i have AMD radeon
- **GPU model and memory**:
- **Exact command to reproduce**:

bazel run -c opt tensorflow/contrib/lite/toco:toco -- --savedmodel_directory=C:\Users\LENOVO-PC\DIZIZIT\saved_model -- output_file=C:\Users\LENOVO-PC\DIZIZIT\saved_model\maonani.tflite

### Describe the problem
Im trying to convert my saved_model.pb from object detection api file to tensorflow lite but it gives me error such as 

```
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/kernels/BUILD:63:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:gemm_support' failed (Exit 2)
.\tensorflow/contrib/lite/context.h(183): error C2144: syntax error: 'float' should be preceded by ';'
.\tensorflow/contrib/lite/context.h(183): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Target //tensorflow/contrib/lite/toco:toco failed to build

```

I tried reinstalling all the pre req of tensorflow and use  the code again and it gave different error saying

```
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/kernels/BUILD:41:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:eigen_support' failed (Exit 2)
cl : Command line error D8021 : invalid numeric argument '/Wno-error=reorder'
Target //tensorflow/contrib/lite/toco:toco failed to build

```
for the 3rd attempt it gives me error saying:

```
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/profiling/BUILD:37:1: C++ compilation of rule '//tensorflow/contrib/lite/profiling:time' failed (Exit 2)
tensorflow/contrib/lite/profiling/time.cc(17): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
Target //tensorflow/contrib/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

### Source code / logs
C:\Users\LENOVO-PC\tensorflow>bazel run -c opt tensorflow/contrib/lite/toco:toco -- --savedmodel_directory=C:\Users\LENOVO-PC\DIZIZIT\saved_model -- output_file=C:\Users\LENOVO-PC\DIZIZIT\saved_model\maonani.tflite
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //tensorflow/contrib/lite/toco:toco (1 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/lenovo-pc/tensorflow/tensorflow/contrib/lite/kernels/BUILD:63:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:gemm_support' failed (Exit 2)
.\tensorflow/contrib/lite/context.h(183): error C2144: syntax error: 'float' should be preceded by ';'
.\tensorflow/contrib/lite/context.h(183): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Target //tensorflow/contrib/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.715s, Critical Path: 1.81s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

2nd attempt was too long to post here

**Comment by aselle** [comment] 2018-07-24 18:32
Unfortunately, tflite is currently not supported under windows. We hope to improve this in the futrue.

**Comment by aselle** [comment] 2018-07-26 17:23
It will be added to the Tensorflow release notes.

**Comment by jdduke** [comment] 2018-08-09 18:56
Duplicate of #21085

**Comment by jdduke** [comment] 2018-08-15 17:19
TFLite and toco should now build and run on Windows. We haven't exhaustively tested all build permutations, but bazel + MSVC 2015 should be functional.

**Closed by jdduke** 2018-08-15 17:19 UTC
Labels: comp:lite, type:feature
