### ISSUE TITLE
Unable to serialize graph with Embedding layers with graph_util.convert_variables_to_constants

### ISSUE THREAD

**Issue by mmv** [tensorflow/tensorflow#21889] opened 2018-08-27 10:54 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: -
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-rc1-19-g656e7a2b34
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: 
- **Exact command to reproduce**: (run script inlined in this issue)

### Describe the problem
Attempting to serialize a model containing a keras Embeddings layer with `tf.graph_util.convert_variables_to_constants` yields a graph that can't be restored. Restoring the graph makes TF complain that some nodes are missing; forcing those into the graphdef will cause TF to complain about mismatching types.

### Source code / logs
The following script tries to serialize two very simple models — one without an embeddings layer and the other with such a layer. Restoring the model will the embeddings layer will fail with `Node 'embedding/embedding_lookup' expects to be colocated with unknown node 'embedding/embedding_lookup/Read/ReadVariableOp'`.

    import tensorflow as tf
    import numpy as np

    def serialize_graph(model):
        g = tf.graph_util.convert_variables_to_constants(
            tf.keras.backend.get_session(),
            tf.keras.backend.get_session().graph.as_graph_def(),
            #[n.name for n in tf.keras.backend.get_session().graph.as_graph_def().node],
            [t.op.name for t in model.outputs]
        )
        return g

    def build_save_restore(model):
        model.compile('sgd', loss='mse')
        model.fit(np.array([[1]]),np.array([[1]]), verbose=0)

        gdef = serialize_graph(model)
        newg = tf.Graph()
        with newg.as_default():
            tf.import_graph_def(gdef)
        print("*"*25)
        print("restored successfully")
        print("*"*25)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(1)
    ])
    build_save_restore(model)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Embedding(1, 1, input_length=1),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(1),
    ])
    build_save_restore(model)

**Comment by sungeuns** [comment] 2018-08-28 14:40
I have similar issue with here.

When I convert tf.keras model (containing `tf.keras.layers.Embeddings`) -> TF graph -> TF Lite model, The process of tf.keras to TF graph works, but when I convert TF graph to TF Lite, it calls `import_graph_def()` function internally and causes same error.

Any help would be appreciated.

**Comment by tensorflowbutler** [comment] 2018-09-16 02:31
Nagging Assignee @robieta: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 13:00
Nagging Assignee @robieta: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 13:00
Nagging Assignee @robieta: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:53
Nagging Assignee @robieta: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by muayyad-alsadi** [comment] 2018-12-20 13:34
Same issue here. I'm trying to export a `keras` model into a frozen graph, but it's failing for same reason.

**Comment by ashokramadass** [comment] 2018-12-20 16:18
I have a similar issue but with elmo embeddings
Node 'elmo/module_apply_tokens/bilm/embedding_lookup' expects to be colocated with unknown node 'elmo/module_apply_tokens/bilm/embedding_lookup/Read/ReadVariableOp'

**Comment by yangw1234** [comment] 2019-01-03 03:17
similar issue here. It seem tf.keras will use ResourceVariable by default, which caused the problem. Changing the default value of `use_resource` to `False` in `tf.keras.Layer.add_weight` seems to fix the problem ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L253)). But I still cannot a figure out a workaround without changing the TF source code. 
Is there any plans on fixing this? @gargn

**Comment by yangw1234** [comment] 2019-01-03 10:13
changing variable creator seems to be a workaround
```
def variable_creator(**kwargs):
    kwargs["use_resource"] = False
    return variable_scope.default_variable_creator(None, **kwargs)
getter = lambda next_creator, **kwargs: variable_creator(**kwargs)
with variable_scope.variable_creator_scope(getter):
    model = ...
```

**Comment by alcaster** [comment] 2019-01-14 11:04
Same issue. I'm trying to use frozen model which uses elmo but if fails with the same error.

**Comment by hengdos** [comment] 2019-01-15 13:12
@yangw1234 

Great!  Changing the default value of `use_resource` to `False` works. But, changing variable creator doesn't work well, and got the error like this:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1 is not in [0, 1)
	 [[{{node embedding/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@training_1/SGD/Assign"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding/embeddings/read, embedding/Cast, training_1/SGD/gradients/embedding/embedding_lookup_grad/concat/axis)]]
```

I leave my code in case:
```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import variable_scope

def serialize_graph(model):
    g = tf.graph_util.convert_variables_to_constants(
            tf.keras.backend.get_session(),
            tf.keras.backend.get_session().graph.as_graph_def(),
            #[n.name for n in tf.keras.backend.get_session().graph.as_graph_def().node],
            [t.op.name for t in model.outputs]
            )
    return g

def build_save_restore(model):
    model.compile('sgd', loss='mse')
    model.fit(np.array([[1]]),np.array([[1]]), verbose=0)
    gdef = serialize_graph(model)
    newg = tf.Graph()
    with newg.as_default():
        tf.import_graph_def(gdef)
        print("*"*25)
        print("restored successfully")
        print("*"*25)

def variable_creator(**kwargs):
    kwargs["use_resource"] = False
    return variable_scope.default_variable_creator(None, **kwargs)

model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(1)
        ])
build_save_restore(model)

getter = lambda next_creator, **kwargs: variable_creator(**kwargs)
with variable_scope.variable_creator_scope(getter):
    model = tf.keras.models.Sequential([
            tf.keras.layers.Embedding(1, 1, input_length=1),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(1),
            ])
    build_save_restore(model)
```

Could you show the entire code?

Thanks in advance!

**Comment by yangw1234** [comment] 2019-01-15 17:05
@hengdos your error is not caused by changing creator, is because you are setting the vocabulary size in the embedding layer to 1 (only index 0 is valid) and the training data you feed is 1 (thus not in  [0, 1)). Try feeding 0?

**Comment by suharshs** [comment] 2019-02-08 00:03
It look like the original issue has been resolved? Closing this. Please create a new issue if there is still a problem.

**Closed by suharshs** 2019-02-08 00:03 UTC
Labels: comp:lite

**Comment by mmv** [comment] 2019-02-08 18:30
@suharshs this is still a problem because:
* the feature should be available without any workaround, especially something as low level as overriding the variable creation
* the override in the workaround goes against the direction of tensorflow which is to use ResourceVariables by default

**Comment by gargn** [comment] 2019-03-21 18:22
cebce4a should fix this issue. Please reopen if it's still an issue.

**Comment by veqtor** [comment] 2019-05-23 14:34
I tried with the latest tf-nightly (installed just now) and I got this issue:
xxx/yyy/Embedding-Token/embedding_lookup' expects to be colocated with unknown node 'xxx/yyy/Embedding-Token/embedding_lookup/Read/ReadVariableOp

**Comment by siyuany** [comment] 2020-03-23 02:51
> ```
> I tried with the latest tf-nightly (installed just now) and I got this issue:
> xxx/yyy/Embedding-Token/embedding_lookup' expects to be colocated with unknown node 'xxx/yyy/Embedding-Token/embedding_lookup/Read/ReadVariableOp
> ```
> 
> Scratch that, I was still on 1.12

I also had this problem in tensorflow=1.12.0
