### ISSUE TITLE
Unable to run example trainer using GPU

### ISSUE THREAD

**Issue by macchakaran** [tensorflow/tensorflow#4577] opened 2016-09-26 03:33 UTC
Hi experts,

I am building tensorflow from source and using virtualenv. I followed all the steps in 
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources
but when i try to run the example trainer, i get a Floating point exception core dump error.
Please let me know if you need further information and how I can get it for you.

Much appreciated!
- Macchakaran

(tensorflow) macchakaran@macchakaran-pc:~/Work/tensorflow$ bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.683
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.47GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Floating point exception (core dumped)

**Comment by concretevitamin** [comment] 2016-09-28 22:46
Please fill out the question template when you click on "New issue"  --- this will help us a lot in figuring out what the issue is.

**Comment by aselle** [comment] 2016-10-11 00:11
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!

**Closed by aselle** 2016-10-11 00:11 UTC
Labels: awaiting response
