### ISSUE TITLE
Dataset not repeating when ignoring errors and shuffling before indefinite repetition

### ISSUE THREAD

**Issue by chhensel** [tensorflow/tensorflow#41530] opened 2020-07-18 19:23 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version: Python 3.x
- CUDA/cuDNN version: not using GPU
- GPU model and memory: not using GPU

**Describe the current behavior**

When using `tf.data.experimental.ignore_errors()`, indefinite repetition does not work if an error occurs during getting the elements to fill the shuffle buffer initially. I think it's a easier to see in code:

```
def assert_greater_0(x):
  tf.debugging.assert_greater(x, tf.convert_to_tensor(0))
  return x

dataset = tf.data.Dataset.from_tensor_slices([1, 2, 0, 3, 4])
dataset = dataset.map(assert_greater_0)
dataset = dataset.shuffle(buffer_size=3)
dataset = dataset.repeat()
dataset = tf.data.experimental.ignore_errors()(dataset)
```

yields a dataset that has 4 elements whereas adjusting the numbers in the initial list slightly

```
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 0, 4])
dataset = dataset.map(assert_greater_0)
dataset = dataset.shuffle(buffer_size=3)
dataset = dataset.repeat()
dataset = tf.data.experimental.ignore_errors()(dataset)
```

yields an infinitely repeating dataset.

More data:
* removing the shuffle produces infinite datasets in both cases.
* specifying the number of repetitions as 2 produces the same result (8 elements) in both cases,

**Describe the expected behavior**

I would expect that the two code snippets both produce infinite datasets.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1quYzXz3inEiG6D7tfUhoGjapZbO8-AAA?usp=sharing

**Comment by lordtt13** [comment] 2020-07-19 08:26
So I don't know why but the issue is with the ```assert_greater_0``` function, I tried it out using lambda in map and got infinite datasets, please check it out [here](https://gist.github.com/lordtt13/e79538a69ef69bb66fcfeeaa3a6701c7)

**Comment by chhensel** [comment] 2020-07-19 13:25
You are right in the sense that the problem appears only with this function and the reason is that for one of the elements in the dataset it triggers a (in this case forced) error. The snippet is the distillation of a much larger pipeline with different errors and I simply tried to have the smallest example showing the behavior I'm referring to.

The ticket is about what happens when an error (violated assertion and I assume it happens for other errors as well) happens in a pipeline that specifies `tf.data.experimental.ignore_errors()`, which is about ignoring exactly those errors. My observation is that when you use this functionality provided by tf, then indefinite dataset repetition after shuffling does not work if the error in the error occurs at a position that is smaller than the shuffle buffer size. If the error happens later, then `tf.data.experimental.ignore_errors()` correctly ignores the errors and the dataset is repeated just fine.

**Comment by saikumarchalla** [comment] 2020-07-20 15:45
@chhensel While running the code with TF -Nightly  I am getting different output. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/b341f0057575b19cca8c2698cbb28231/copy-of-repeat-error.ipynb).Thanks!

**Comment by chhensel** [comment] 2020-07-20 16:37
When I open the gist, it still shows the version that is not working (with tf 2.2.0), but I can confirm that using tf-nightly indeed shows the desired behavior, thanks!

**Comment by saikumarchalla** [comment] 2020-07-21 05:36
@chhensel Thank you for the update and marking this issue as closed since it is fixed in tf -nightly.

**Closed by saikumarchalla** 2020-07-21 05:36 UTC
Labels: TF 2.2, comp:data, stat:awaiting response, type:bug
