### ISSUE TITLE
Can't cross-compile TFLite "Minimal" for Raspberry Pi Zero (armv6 target)

### ISSUE THREAD

**Issue by covertg** [tensorflow/tensorflow#30181] opened 2019-06-26 16:27 UTC
**System information**
- OS Platform and Distribution: Linux Debian 10
- TensorFlow installed from: source
- TensorFlow version: master branch @ a6989c95e336eb9f73ac7dd2920bee76d7e7e49e
- GCC/Compiler version: 8.3.0 (Debian 8.3.0-2)
- Python, Installed using ..., Bazel, CUDA, GPU: n/a

**Background**
Hi,
I've been trying to build a Tensorflow Lite C++ project for the Raspberry Pi Zero. For a simple base, I'm working from the "minimal" example provided. Building the Tensorflow Lite static library natively can take upwards of 5-6 hours, and for simplicity I've been trying to cross-compile. However, I haven't yet gotten minimal to compile. Although there's documentation on compiling for armv7 Pi's, I haven't been able to find anything on an armv6 platform.

**Steps I've taken, following the docs [here](https://www.tensorflow.org/lite/guide/build_rpi).**
- Git clone the tf repo
- Run ``download_dependencies.sh``
- Modify ``build_rpi_lib.sh`` to target armv6, i.e. with:
```
CC_PREFIX=arm-linux-gnueabihf- make -j 3 -f tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6
```
- First attempt! Run that build script. It quickly errors out in a few different header, saying `` sorry, unimplemented: Thumb-1 hard-float VFP ABI``. For example:
```
In file included from /usr/arm-linux-gnueabihf/include/c++/8/bits/stl_algobase.h:62,
                 from /usr/arm-linux-gnueabihf/include/c++/8/memory:62,
                 from ./tensorflow/lite/arena_planner.h:18,
                 from tensorflow/lite/arena_planner.cc:15:
/usr/arm-linux-gnueabihf/include/c++/8/ext/type_traits.h: In function ‘bool __gnu_cxx::__is_null_pointer(std::nullptr_t)’:
/usr/arm-linux-gnueabihf/include/c++/8/ext/type_traits.h:162:35: sorry, unimplemented: Thumb-1 hard-float VFP ABI
   __is_null_pointer(std::nullptr_t)
                                   ^
make: *** [tensorflow/lite/tools/make/Makefile:242: /home/cgeary1/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/allocation.o] Error 1
```
**- I wonder if I could get away using the traditional ARM instruction set instead of Thumb...** Add``-marm`` to CFLAGS and CXXFLAGS in ``rpi_makefile.inc`` under the armv6 ifeq, then try again. I.e.:
```
  ifeq ($(TARGET_ARCH), armv6)
    CXXFLAGS += \
      -march=armv6 \
      -mfpu=vfp \
      -funsafe-math-optimizations \
      -ftree-vectorize \
      -fPIC \
      -marm

    CFLAGS += \
      -march=armv6 \
      -mfpu=vfp \
      -funsafe-math-optimizations \
      -ftree-vectorize \
      -fPIC \
      -marm

    LDFLAGS := \
      -Wl,--no-export-dynamic \
      -Wl,--exclude-libs,ALL \
      -Wl,--gc-sections \
      -Wl,--as-needed
  endif
```
- Compiles for a little while, and finishes libtensorflow-lite.a !! But it errors out as soon as it moves on to minimal. Complaints look like ``undefined reference to `__atomic_load_8'`` and ``undefined reference to `flatbuffers::ClassicLocale::instance_'``. Relevant log is attached for all the details.
[log.txt](https://github.com/tensorflow/tensorflow/files/3331025/log.txt)

I'm not sure whether I'm doing something wrong, whether there's a bug in the make system, or whether there may be a more intractable problem trying to cross-compile this codebase for the Pi Zero. I'm not really sure what else to try, so for now I'm just working on the Pi.

Edit: I'm not able to try this right now, but I've realized that the flatbuffers error is likely to be solved as in #29806. The __atomic_load_8 error is the one that I can't get past.

**Comment by andrey-utkin** [comment] 2019-07-26 08:17
> Complaints look like undefined reference to `__atomic_load_8'

@covertg Add `-latomic` to your LDFLAGS

**Comment by covertg** [comment] 2019-08-03 22:45
@andrew-utkin That did it! Thank you!

**Comment by gadagashwini** [comment] 2019-08-05 05:33
Closing this issue since the issue is resolved. Please reopen if the issue still persists. Thanks!

**Closed by gadagashwini** 2019-08-05 05:33 UTC
Labels: comp:lite, type:bug

**Comment by mgyong** [comment] 2019-08-13 06:31
@covertg I am trying to cross compile on Raspberry pi zero. Appreciate if you could share yr code in a github gist or repo? thanks

**Comment by mhashim6** [comment] 2019-11-26 07:21
@andrey-utkin
adding -latomic to LDFLAGS  didn't work for me.
I also tried adding  `set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")` to the end of every `CMakeLists.txt` but it also failed.
