### ISSUE TITLE
Graph Transform Tool unable to build in TF source r1.5?

### ISSUE THREAD

**Issue by kwotsin** [tensorflow/tensorflow#16205] opened 2018-01-18 02:06 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source 
- **TensorFlow version (use command below)**: r1.5
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.8.1
- **GCC/Compiler version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: 9.0/7.0.5
- **GPU model and memory**: 1080Ti
- **Exact command to reproduce**:
```
sudo sh -c "echo '/usr/local/cuda-8.0/lib64' >> /etc/ld.so.conf.d/nvidia.conf"
sudo ldconfig
bazel clean
bazel build tensorflow/tools/graph_transforms:transform_graph --verbose_failures
```

### Describe the problem
I'm having issue trying to build the graph transform tool with bazel although I've look at existing solutions to similar problem such as #13481. I have been able to build the graph transform tool in previous versions but not in this version, so I'm not too sure what went wrong. Note that previously I got a similar problem when I installed TF from source but it was related to CUDA and I solved it after reinstalling nvcc.

I also rebooted my comp just in case it was a temporary system error, but the error still persists.

Looking at the error, does it have anything to do with "JEMALLOC"? I enabled this option when configuring tensorflow as seen in the official installation guide.

### Source code / logs
```
ERROR: /home/kwotsin/tensorflow/tensorflow/core/kernels/BUILD:3945:1: C++ compilation of rule '//tensorflow/core/kernels:scatter_nd_op' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/kwotsin/.cache/bazel/_bazel_kwotsin/041f6cc3555a2d9f6211c6d126ede477/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-9.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7.0.5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \

  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-std=c++11' -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op_cpu_impl_5.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op_cpu_impl_5.o' -DEIGEN_MPL2_ONLY -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_JEMALLOC -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote external/jemalloc -iquote bazel-out/k8-opt/genfiles/external/jemalloc -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/k8-opt/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/k8-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/k8-opt/genfiles/external/local_config_cuda -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem external/jemalloc/include -isystem bazel-out/k8-opt/genfiles/external/jemalloc/include -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/k8-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/include -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' '-DGOOGLE_CUDA=1' -msse3 -pthread '-DGOOGLE_CUDA=1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/kernels/scatter_nd_op_cpu_impl_5.cc -o bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op_cpu_impl_5.o)
In file included from tensorflow/core/kernels/scatter_nd_op_cpu_impl_5.cc:18:0:
./tensorflow/core/kernels/scatter_nd_op_cpu_impl.h: In instantiation of 'Index tensorflow::functor::ScatterNdFunctor<Eigen::ThreadPoolDevice, T, Index, OP, IXDIM>::operator()(const CPUDevice&, Index, Eigen::array<long int, IXDIM>, typename tensorflow::TTypes<T, 2>::Tensor, typename tensorflow::TTypes<T, 2>::ConstTensor, typename tensorflow::TTypes<T, 2>::ConstTensor, typename tensorflow::TTypes<T, 2>::Tensor) [with T = float; Index = int; tensorflow::scatter_nd_op::UpdateOp OP = (tensorflow::scatter_nd_op::UpdateOp)0; int IXDIM = 5; tensorflow::CPUDevice = Eigen::ThreadPoolDevice; typename tensorflow::TTypes<T, 2>::Tensor = Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long int>, 16, Eigen::MakePointer>; typename tensorflow::TTypes<T, 2>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const int, 2, 1, long int>, 16, Eigen::MakePointer>; typename tensorflow::TTypes<T, 2>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>]':
./tensorflow/core/kernels/scatter_nd_op_cpu_impl.h:162:1:   required from here
./tensorflow/core/kernels/scatter_nd_op_cpu_impl.h:137:3: internal compiler error: Segmentation fault
   }
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //tensorflow/tools/graph_transforms:transform_graph failed to build
INFO: Elapsed time: 147.229s, Critical Path: 24.74s
FAILED: Build did NOT complete successfully

```

**Comment by aselle** [comment] 2018-01-21 01:08
You seem to have a version mismatch on your command line to do setup
```
sudo sh -c "echo '/usr/local/cuda-8.0/lib64' >> /etc/ld.so.conf.d/nvidia.conf"
```

but you are building with cuda 9.0. Try removing the cuda 8 stuff if it is still there.

**Comment by kwotsin** [comment] 2018-01-21 02:43
@aselle Thanks for the reply. My system doesn't have CUDA 8.0 anymore since the previous install but I've mistakenly typed 8.0 instead. However, after changing the command to use 9.0 instead, the same problem still appears, and is related to same op once again.

```
ERROR: /home/kwotsin/tensorflow/tensorflow/core/kernels/BUILD:3945:1: C++ compilation of rule '//tensorflow/core/kernels:scatter_nd_op' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/kwotsin/.cache/bazel/_bazel_kwotsin/041f6cc3555a2d9f6211c6d126ede477/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-9.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=9.0 \
    TF_CUDNN_VERSION=7.0.5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-std=c++11' -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op.o' -DEIGEN_MPL2_ONLY -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DTENSORFLOW_USE_JEMALLOC -DTENSORFLOW_USE_ABSL -DTF_USE_SNAPPY -iquote . -iquote bazel-out/k8-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote external/jemalloc -iquote bazel-out/k8-opt/genfiles/external/jemalloc -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/k8-opt/genfiles/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/k8-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote external/local_config_cuda -iquote bazel-out/k8-opt/genfiles/external/local_config_cuda -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem external/jemalloc/include -isystem bazel-out/k8-opt/genfiles/external/jemalloc/include -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/k8-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/include -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' '-DGOOGLE_CUDA=1' -msse3 -pthread '-DGOOGLE_CUDA=1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/kernels/scatter_nd_op.cc -o bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/scatter_nd_op/tensorflow/core/kernels/scatter_nd_op.o)
tensorflow/core/kernels/scatter_nd_op.cc: In constructor 'Eigen::Symbolic::SymbolExpr<tag>::SymbolExpr() [with tag = Eigen::placeholders::internal::symbolic_last_tag]':
tensorflow/core/kernels/scatter_nd_op.cc:556:1: internal compiler error: Segmentation fault
 }  // namespace tensorflow
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //tensorflow/tools/graph_transforms:transform_graph failed to build
INFO: Elapsed time: 160.245s, Critical Path: 24.60s
FAILED: Build did NOT complete successfully

```

**Comment by reedwm** [comment] 2018-01-31 23:25
/CC @gunan, any ideas what the issue could be?

Also, I doubt this makes a different, but the command 
```
sudo sh -c "echo '/usr/local/cuda-9.0/lib64' >> /etc/ld.so.conf.d/nvidia.conf"
```
appends the line to the file, keeping the old lines. Try replacing >> with >.

**Comment by reedwm** [comment] 2018-02-01 17:29
Since we cannot reproduce, marking as contributions welcome.

**Comment by kumariko** [comment] 2021-08-24 08:59
@kwotsin We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.Thanks!

**Closed** 2021-09-07 10:06 UTC
Labels: stat:contributions welcome, stat:awaiting response, type:build/install, stalled
