### ISSUE TITLE
Regression: PyUnicodeUCS4_AsUTF8String on 0.11.0rc0 to 0.11.0rc2

### ISSUE THREAD

**Issue by chenliu0831** [tensorflow/tensorflow#5336] opened 2016-11-01 19:18 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/33795982/undefined-symbol-pyunicodeucs4-fromstringandsize-with-tensorflow-on-heroku
### Environment info
Operating System:
Heroku
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### What other attempted solutions have you tried?
Confirmed working on https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
```
Nov 01 15:05:13 i23d-staging app/worker.1:      import tensorflow as tf 
Nov 01 15:05:13 i23d-staging app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module> 
Nov 01 15:05:13 i23d-staging app/worker.1:      from tensorflow.python import * 
Nov 01 15:05:13 i23d-staging app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module> 
Nov 01 15:05:13 i23d-staging app/worker.1:      from tensorflow.python import pywrap_tensorflow 
Nov 01 15:05:13 i23d-staging app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module> 
Nov 01 15:05:13 i23d-staging app/worker.1:      _pywrap_tensorflow = swig_import_helper() 
Nov 01 15:05:13 i23d-staging app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper 
Nov 01 15:05:13 i23d-staging app/worker.1:      _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description) 
Nov 01 15:05:13 i23d-staging app/worker.1:  ImportError: /app/.heroku/python/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_AsUTF8String 
```

**Comment by aselle** [comment] 2016-11-01 21:33
Just to be clear, how is this reproduced? Just importing tensorflow as 
```python
import tensorflow as tf
```
causes the problem?  This only occurs on Heroku? What version of Python?

**Comment by chenliu0831** [comment] 2016-11-02 14:19
@aselle Yeah. So far the target platform I tested was only heroku. The python version is 2.7.10.

**Comment by rgobbel** [comment] 2016-11-02 16:49
+1 on Centos 7. Python 2.7.12

$ python
Python 2.7.12 (default, Aug 31 2016, 14:30:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python-2.7.12/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python-2.7.12/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/python-2.7.12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/python-2.7.12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/python-2.7.12/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_AsUTF8String

**Comment by aselle** [comment] 2016-11-02 19:45
Could you try the nightly build and also other older versions and see if we can narrow it down to just that build?

It looks like your version of Python does not have UCS4 unicode checked in, see e.g.
https://groups.google.com/forum/#!topic/comp.lang.python/9dThp1h3TMM

Can you do?
```
>>> import sys
>>> print sys.maxunicode
```
and see what it returns (see e.g. http://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4)

**Comment by rgobbel** [comment] 2016-11-02 22:41
It looks like sys.maxunicode == 65535, which I would guess is UCS2.

I did try back to 0.11.0rc0 and saw the same issue. We've been running with a custom-compiled version, since we needed CUDA 8 support.

It's a little difficult to try a custom version without disrupting others' work, but I can try--we're running TF pretty much 24/7 now.

**Comment by aselle** [comment] 2016-11-02 22:46
I believe in general it is unlikely that our binary which is designed to work on Ubuntu will work on CentOS 7, because the build options on Python are possibly different between the two. Thus, on CentOS, you might need to use a custom built version. It appears CentOS7 and Ubuntu use different unicode options... @gunan might know better.  You could probably build a custom python just for tensorflow if you want to use the Ubuntu binary, but that might just be asking for trouble.

**Comment by gunan** [comment] 2016-11-02 23:14
We never tested our binary with CentOS, therefore the distributed pip package has no guarantees.
As @aselle suggested, rebuilding from source, or using docker images on CentOS should work for you.

Not sure about heroku platform. Again, it is never tested.
Therefore no guarantees on it.

**Comment by chenliu0831** [comment] 2016-11-03 03:12
@gunan @aselle Heroku also returns 65535. For us it's not a big deal and we already switched to EC2. But it does look like a regression since `0.10.0rc0` works.

**Comment by gunan** [comment] 2016-11-03 05:30
A quick google search showed that heroku instances are built on top of ubuntu 14.04.
Using docker, I tried the following:

$ docker run -it ubuntu:14.04 bash
$ apt-get update
$ apt-get install python python-dev python-pip -y
$ pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl
$ python -c "import tensorflow; print(tensorflow.__version__)"

Which results in:
0.11.0rc2

Looks like in the stackoverflow question @mrry was able to root cause the problem and provide a solution for the platform in question.
However, since we do not have official support for this platform, and issue does not affect ubuntu version we are supporting, and the one before that, I will close this issue.

I am really sorry for the inconvenience, but looks like the solution for heroku and centOS is to build the pip package from sources.

**Closed by gunan** 2016-11-03 05:30 UTC
Labels: type:bug/performance
