### ISSUE TITLE
Unsupported data type 14 in tensor

### ISSUE THREAD

**Issue by AnkushMahajan1** [tensorflow/tensorflow#53279] opened 2021-12-02 01:12 UTC
Hi,
I recently converted my custom LSTM model from TensorFlow '2.7.0' to TensorFlow lite so I can implement it on a Android Device  But, when I tried to test it I got this error 'Unsupported data type 14 in tensor'.
Can anyone help me understand this error?

Here is code for converting model to tflite
'''
converter = tf.lite.TFLiteConverter.from_saved_model(TRAIN_MODELS_DIR)
converter.post_training_quantize=True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
'''

**Comment by AnkushMahajan1** [comment] 2021-12-02 01:17
And yes data type of the tflite  is float32

**Comment by grewe** [comment] 2021-12-02 03:18
@sushreebarsa   I am working with Ankush and we are hoping you can help us.   The code that creates this error is when the Interpreter is being created.   


    
```
         lstmModel = FileUtil.loadMappedFile(activity, "lstm_lookLearn_classifier.tflite");


        // Create a TFLite interpreter instance
        lstmTflite = new Interpreter(lstmModel, tfliteOptions);
```



Note that this is our Android gradle file:


```
    /* TensorFlow Lite 2.0+ */
    implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') {changing = true}
    implementation('org.tensorflow:tensorflow-lite-support:0.0.0-nightly') {changing = true}
    implementation('org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly') {changing = true}
```

**Comment by grewe** [comment] 2021-12-02 03:19
@sushreebarsa   

Also, note that the exact same model architecture but trained a number of months ago (with a different version of TFLite for conversion) is able to run with this exact same code.   So, there seems to be some kind of issue either in the latest TFLite conversion or support with our tensorflowlite in Android.

**Comment by sanatmpa1** [comment] 2021-12-02 15:55
@AnkushMahajan1,

Can you share the complete stand-alone code to reproduce this issue? Thanks!

**Comment by grewe** [comment] 2021-12-02 17:17
@sanatmpa1 the github is located at [https://github.com/grewe/USquat](https://github.com/grewe/USquat )

And this is happening with the 2 new models we are trying to load and create Interpreter instances of.  One is the LSTM model that we reported the issue on and the other is another newly created Object Detection API EfficientDet model.   

The LSTM model is being created in this Classifier.java class .   Particuarly see these lines 235-244.   Note it the highlighted /bolded line that causes the error.   The old model lstm_classifier.tflite works perfectly fine.  Unfortunately, we do not know what combination of tensorflow version was used for training and at that time we had to use tf-nightly to get it to work for TFlite conversion.   As stated above we are trying to use version 2.7.0 for tensorflow training and again have used this for TFlite conversion.

```

//Now decide on the Model to use for LSTM - orginal (kelly) or LookLEarn(ankush)
        if(this.mUSquatModel.contains("Original"))
            lstmModel = FileUtil.loadMappedFile(activity, "lstm_classifier.tflite");
        else
        //    lstmModel = FileUtil.loadMappedFile(activity, "lstm_classifier.tflite");
           **lstmModel = FileUtil.loadMappedFile(activity, "lstm_lookLearn_classifier.tflite");**


        // Create a TFLite interpreter instance
        lstmTflite = new Interpreter(lstmModel, tfliteOptions);
```


The other newly created model that is also failing giving the same error is an Object Detector EfficientDet model  and it is being  created in the [LookLearnProcessor.java code](https://github.com/grewe/USquat/blob/main/app/src/main/java/com/edu/usquat/LookLearn/LookLearnProcessor.java)
See line 248 where it says:
```

         detector =
                    (TFLiteObjectDetectionEfficientDet) TFLiteObjectDetectionEfficientDet.create(
                            context.getAssets(),
                            TF_OD_API_MODEL_FILE,
                            TF_OD_API_LABELS_FILE,
                            TF_OD_API_INPUT_SIZE,
                            TF_OD_API_IS_QUANTIZED);
```

**Comment by AnkushMahajan1** [comment] 2021-12-02 23:51
@sanatmpa1 the github is located at https://github.com/grewe/USquat

And this is happening with the 2 new models we are trying to load and create Interpreter instances of. One is the LSTM model that we reported the issue on and the other is another newly created Object Detection API EfficientDet model.

The LSTM model is being created in this Classifier.java class . Particuarly see these lines 235-244. Note it the line lstmTflite = new Interpreter(lstmModel, tfliteOptions); using the lstmModel tied to the new lstm_lookLearnclassifier.tflite file which causes the error in the code snippet following from Classifier.java. The old model lstm_classifier.tflite works perfectly fine. Unfortunately, we do not know what combination of tensorflow version was used for training and at that time we had to use tf-nightly to get it to work for TFlite conversion. As stated above we are trying to use version 2.7.0 for tensorflow training and again have used this for TFlite conversion.

''''
//Now decide on the Model to use for LSTM - orginal (kelly) or LookLEarn(ankush)
        if(this.mUSquatModel.contains("Original"))
            lstmModel = FileUtil.loadMappedFile(activity, "lstm_classifier.tflite");
        else
        //    lstmModel = FileUtil.loadMappedFile(activity, "lstm_classifier.tflite");    //flipping back and forth for testing delete later
           lstmModel = FileUtil.loadMappedFile(activity, "lstm_lookLearn_classifier.tflite");


        // Create a TFLite interpreter instance
        lstmTflite = new Interpreter(lstmModel, tfliteOptions);
''''
The other newly created model that is also failing giving the same error is an Object Detector EfficientDet model and it is being created in the LookLearnProcessor.java code
See line 248 where it says:

''''
         detector =
                    (TFLiteObjectDetectionEfficientDet) TFLiteObjectDetectionEfficientDet.create(
                            context.getAssets(),
                            TF_OD_API_MODEL_FILE,
                            TF_OD_API_LABELS_FILE,
                            TF_OD_API_INPUT_SIZE,
                            TF_OD_API_IS_QUANTIZED);
'''

**Comment by grewe** [comment] 2021-12-03 19:56
@sushreebarsa @sanatmpa1 We are stuck on this issue and please need your guidance.

**Comment by grewe** [comment] 2021-12-06 22:01
@sachinprasadhs  It would be great if we could get some traction on this issue --more than reassignment --- is it possible for you to look at this?

**Comment by sachinprasadhs** [comment] 2021-12-08 22:43
If you are not using the latest Tensorflow and TensorFlow Lite runtime version please upgrade to the latest and try again.

**Comment by grewe** [comment] 2021-12-08 23:49
We are using the latest and have also tried an earlier version.   Neither
work and the error is as reported.

Lynne Grewe |  Professor Computer Science, Director iLab |  California
State University East Bay |
***@***.*** ***@***.***>  *

**Comment by gaurxvreddy** [comment] 2021-12-09 19:15
I'm facing the same issue.

**Comment by grewe** [comment] 2021-12-09 20:00
@sachinprasadhs @gaurxvreddy    Please note my previously converted TFLite models still work (but, do not know what version used to convert) and the NEWLY converted TFLite models do not ---and tried with a few different Tensorflow versions specified in  Android build gradle file .     The odd thing is I did try for my new models to retrain them and convert with a lower version too -- for version 2.6  just to see if maybe the TFLite was the issue but got different errors.   

AND NOTE this is for both a CNN and a LSTM model that both previously worked.

Do not know how to go about fixing this

**Comment by mohantym** [comment] 2022-02-25 11:02
Hi @AnkushMahajan1 ! Did you try with latest Tflite version yet?

**Comment by AnkushMahajan1** [comment] 2022-02-25 20:04
Hey @mohantym I was running it on  Tensorflow version 2.7.0

**Comment by hughjackman111** [comment] 2022-04-07 11:36
> > @grewe Actually I'm working arounf with Object Detection. It doesn't work either.
> > I recommend you to try **tflite-runtime**
> > ```
> > import tflite_runtime.interpreter as tflite
> > 
> > interpreter = tflite.Interpreter(model_path=args.model_file)
> > ```
> 
> https://www.tensorflow.org/lite/guide/python
> 
> follow the link
> 
> > It didn't quite work for me. I got more error when I've done this. You may give it a try and see !!
> 
> > And also @grewe, please let me know if you somehow figure out this.
> 
> Thanks

Hi @gauravreddy08 I get the same issue. It work when I use tf.lite.Interpreter.
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    interpreter = tflite.Interpreter(model_path)
  File "D:\anaconda3\envs\tflite\lib\site-packages\tflite_runtime\interpreter.py", line 205, in __init__
    model_path, self._custom_op_registerers))
ValueError: Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor

**Comment by mohantym** [comment] 2022-04-07 15:49
@AnkushMahajan1 ! I was able to run  both tflite models lstm_classifier.tflite and lstm_lookLearn_classifier.tflite in interpreter though. Attaching gist for [reference](https://colab.sandbox.google.com/gist/mohantym/717a7f41383b54f9e04cb476b04ef068/git_53279.ipynb#scrollTo=HX5JgWbV7-z-).

**Comment by hughjackman111** [comment] 2022-04-09 09:52
> @AnkushMahajan1 ! I was able to run both tflite models [lstm_classifier.tflite and lstm_lookLearn_classifier.tflite](https://github.com/tensorflow/tensorflow/issues/53279) in interpreter though. Attaching gist for [reference](https://colab.sandbox.google.com/gist/mohantym/717a7f41383b54f9e04cb476b04ef068/git_53279.ipynb#scrollTo=HX5JgWbV7-z-). Thanks!

- Hi! Actually, they both work with using **tensorflow**.  But the model [lstm_lookLearn_classifier.tflite] didn't work with **tflite-runtime**. And the model [lstm_classifier.tflite] works with **tflite-runtime** .

**Comment by mohantym** [comment] 2022-04-11 03:18
@hughjackman111 !I was able to load lstm_lookLearn_classifier.tflite and lstm_classifier.tflite with tflite-runtime 2.7. Please check the updated [gist](https://colab.sandbox.google.com/gist/mohantym/717a7f41383b54f9e04cb476b04ef068/git_53279.ipynb#scrollTo=jDacsHsh7Q8F). Thanks!

**Comment by hughjackman111** [comment] 2022-04-14 05:28
> @hughjackman111 !I was able to load **lstm_lookLearn_classifier.tflite and lstm_classifier.tflite** with tflite-runtime 2.7. Please check the updated [gist](https://colab.sandbox.google.com/gist/mohantym/717a7f41383b54f9e04cb476b04ef068/git_53279.ipynb#scrollTo=jDacsHsh7Q8F). Thanks!

Hi! @mohantym I mean you should try to load **lstm_lookLearn_classifier.tflite** without **"import tensorflow as tf"**. Please look this [gist](https://colab.research.google.com/drive/1Gqhsa2smR33JTqFwTPqICYnJhhCWbIQm#scrollTo=JVEcyEK_fkQY).  Thanks!

**Comment by mohantym** [comment] 2022-04-14 07:48
Yeah. I am getting a [select ops error](https://colab.sandbox.google.com/gist/mohantym/41dc6053a9bab2da4d7e33bfe825c70f/git_53279.ipynb#scrollTo=sAPN4NI27h9n) without doing "import tensorflow as tf" . But these issue gets mostly resolved by adding [select ops](https://www.tensorflow.org/lite/guide/ops_select) before converting to tflite model. @hughjackman111 @AnkushMahajan1 ! Can you let us know the results after using select ops and adding select ops dependencies in build.gradle() ? Thanks!

**Comment by Pranay772629** [comment] 2022-04-21 12:07
I have a custom model which has LSTM layers which produces the same error when creating an Interpreter in android studio. @grewe any updates on the error and its solution?

**Closed** 2022-05-05 13:14 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TFLiteConverter, TF 2.7

**Comment by lazyPy** [comment] 2023-04-16 02:55
Anyone here, solved this issue? I'm still facing this issue, my model was CNN+LSTM. Thanks
