### ISSUE TITLE
core dumped when using tflite_convert

### ISSUE THREAD

**Issue by huangxiao2008** [tensorflow/tensorflow#21300] opened 2018-08-01 08:59 UTC
When I use tflite_convert to get a tflite model, it coredumps everytime.

The model I trained is based on MobileNetV2 + SSD， and generate a pb file using export_inference_graph.py in object_detection.

here is the log:

'2018-08-01 08:43:35.857541: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.863758: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Equal\n2018-08-01 08:43:35.864497: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864561: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864673: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864710: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864720: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864731: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864739: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864810: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Equal\n2018-08-01 08:43:35.864827: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864856: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.864890: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.864940: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.864991: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.865011: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.865049: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865110: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.865191: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865271: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.865300: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.865351: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865390: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.865467: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865525: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.865546: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.865580: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865612: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.865662: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865708: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.865728: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.865762: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865793: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.865838: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865885: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.865906: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.865942: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.865974: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.866025: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866075: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.866097: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.866132: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866164: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.866212: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866260: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.866280: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.866312: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866345: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.866394: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866441: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.866461: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.866496: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866529: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.866579: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866629: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.866649: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.866681: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866713: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Unpack\n2018-08-01 08:43:35.866760: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Where\n2018-08-01 08:43:35.866807: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: NonMaxSuppressionV2\n2018-08-01 08:43:35.866829: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ZerosLike\n2018-08-01 08:43:35.866874: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Size\n2018-08-01 08:43:35.866884: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Equal\n2018-08-01 08:43:35.867413: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: ResizeNearestNeighbor\n2018-08-01 08:43:35.907700: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2041 operators, 3390 arrays (0 quantized)\n2018-08-01 08:43:35.954623: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 2001 operators, 3308 arrays (0 quantized)\n2018-08-01 08:43:36.014150: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2001 operators, 3308 arrays (0 quantized)\n2018-08-01 08:43:36.095756: F tensorflow/contrib/lite/toco/graph_transformations/resolve_tensorflow_switch.cc:95] Check failed: other_op->type == OperatorType::kTensorFlowMerge \nAborted (core dumped)\n'

Anyone can help ? Thanks a lot

**Comment by tensorflowbutler** [comment] 2018-08-01 18:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by achowdhery** [comment] 2018-08-02 19:51
Please use export_tflite_ssd_graph.py as described in this `[post](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193)`.

**Comment by tensorflowbutler** [comment] 2018-08-17 19:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by achowdhery** [comment] 2018-08-18 14:41
@huangxiao2008 What detection checkpoint did you start from? What platform did you try the conversion on? Please provide exact reproducible instructions.

**Comment by tensorflowbutler** [comment] 2018-09-02 18:35
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tofulawrence** [comment] 2018-09-06 18:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-09-06 18:52 UTC
Labels: comp:lite, stat:awaiting response
