### ISSUE TITLE
REGISTER_KERNEL_BUILDER fails type constraint check for valid integral types

### ISSUE THREAD

**Issue by Bidski** [tensorflow/tensorflow#20586] opened 2018-07-06 05:30 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 18.2 Sonya (based on Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: latest master (last commit https://github.com/tensorflow/tensorflow/commit/b2fe2a874bade4782aaca5c44bf29e7ff6c39200)
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 7.3.0
- **CUDA/cuDNN version**: 9.2/7.1
- **GPU model and memory**: GX1080Ti 11GB
- **Exact command to reproduce**: N/A

### Describe the problem
When writing a custom op and registering a kernel builder using `REGISTER_KERNEL_BUILDER`, specifying a type constraint of int64_t will fail on some machines. This also fails for unsigned types too (as you would expect).

The problem occurs due to lines 381-403 in `tensorflow/core/framework/types.h`
```
MATCH_TYPE_AND_ENUM(float, DT_FLOAT);
MATCH_TYPE_AND_ENUM(double, DT_DOUBLE);
MATCH_TYPE_AND_ENUM(int32, DT_INT32);
MATCH_TYPE_AND_ENUM(uint32, DT_UINT32);
MATCH_TYPE_AND_ENUM(uint16, DT_UINT16);
MATCH_TYPE_AND_ENUM(uint8, DT_UINT8);
MATCH_TYPE_AND_ENUM(int16, DT_INT16);
MATCH_TYPE_AND_ENUM(int8, DT_INT8);
MATCH_TYPE_AND_ENUM(string, DT_STRING);
MATCH_TYPE_AND_ENUM(complex64, DT_COMPLEX64);
MATCH_TYPE_AND_ENUM(complex128, DT_COMPLEX128);
MATCH_TYPE_AND_ENUM(int64, DT_INT64);
MATCH_TYPE_AND_ENUM(uint64, DT_UINT64);
MATCH_TYPE_AND_ENUM(bool, DT_BOOL);
MATCH_TYPE_AND_ENUM(qint8, DT_QINT8);
MATCH_TYPE_AND_ENUM(quint8, DT_QUINT8);
MATCH_TYPE_AND_ENUM(qint16, DT_QINT16);
MATCH_TYPE_AND_ENUM(quint16, DT_QUINT16);
MATCH_TYPE_AND_ENUM(qint32, DT_QINT32);
MATCH_TYPE_AND_ENUM(bfloat16, DT_BFLOAT16);
MATCH_TYPE_AND_ENUM(Eigen::half, DT_HALF);
MATCH_TYPE_AND_ENUM(ResourceHandle, DT_RESOURCE);
MATCH_TYPE_AND_ENUM(Variant, DT_VARIANT);
```
In this case, `int64` is being `typedef`'d to `long long` (`tensorflow/core/platform/default/integral_types.h`), however on some systems `int64_t` is `typedef`'d as `__int64` (or potentially some other variation that results in a 64-bit signed type). Because of this `int64_t != to int64` and the type constraint check fails.

On my system in particular, this code
```
#include <cstdint>
#include <iostream>

int main(void) {
    std::cout << "int64_t...............: "
              << "(" << typeid(int64_t).name() << ") " << sizeof(int64_t) << std::endl;
    std::cout << "long..................: "
              << "(" << typeid(long).name() << ") " << sizeof(long) << std::endl;
    std::cout << "long int..............: "
              << "(" << typeid(long int).name() << ") " << sizeof(long int) << std::endl;
    std::cout << "long long int.........: "
              << "(" << typeid(long long int).name() << ") " << sizeof(long long int) << std::endl;
    std::cout << "long long.............: "
              << "(" << typeid(long long).name() << ") " << sizeof(long long) << std::endl;
    std::cout << "uint64_t..............: "
              << "(" << typeid(uint64_t).name() << ") " << sizeof(int64_t) << std::endl;
    std::cout << "unsigned long.........: "
              << "(" << typeid(unsigned long).name() << ") " << sizeof(unsigned long) << std::endl;
    std::cout << "unsigned long int.....: "
              << "(" << typeid(unsigned long int).name() << ") " << sizeof(unsigned long int) << std::endl;
    std::cout << "unsigned long long int: "
              << "(" << typeid(unsigned long long int).name() << ") " << sizeof(unsigned long long int) << std::endl;
    std::cout << "unsigned long long....: "
              << "(" << typeid(unsigned long long).name() << ") " << sizeof(unsigned long long) << std::endl;
    std::cout << "long long == int64_t? " << (std::is_same<long long, int64_t>::value ? "yes" : "no") << std::endl;
    std::cout << "(sizeof(long long) == 8) && std::is_signed<long long>::value? "
              << ((sizeof(long long) == 8) && std::is_signed<long long>::value ? "yes" : "no") << std::endl;
    std::cout << "(sizeof(int64_t) == 8) && std::is_signed<int64_t>::value? "
              << ((sizeof(int64_t) == 8) && std::is_signed<int64_t>::value ? "yes" : "no") << std::endl;
    std::cout << "unsigned long long == uint64_t? "
              << (std::is_same<unsigned long long, uint64_t>::value ? "yes" : "no") << std::endl;
    std::cout << "(sizeof(unsigned long long) == 8) && !std::is_signed<unsigned long long>::value? "
              << ((sizeof(unsigned long long) == 8) && !std::is_signed<unsigned long long>::value ? "yes" : "no")
              << std::endl;
    std::cout << "(sizeof(uint64_t) == 8) && !std::is_signed<uint64_t>::value? "
              << ((sizeof(uint64_t) == 8) && !std::is_signed<uint64_t>::value ? "yes" : "no") << std::endl;
    return 0;
}

```
produces this output
```
int64_t...............: (l) 8
long..................: (l) 8
long int..............: (l) 8
long long int.........: (x) 8
long long.............: (x) 8
uint64_t..............: (m) 8
unsigned long.........: (m) 8
unsigned long int.....: (m) 8
unsigned long long int: (y) 8
unsigned long long....: (y) 8
long long == int64_t? no
(sizeof(long long) == 8) && std::is_signed<long long>::value? yes
(sizeof(int64_t) == 8) && std::is_signed<int64_t>::value? yes
unsigned long long == uint64_t? no
(sizeof(unsigned long long) == 8) && !std::is_signed<unsigned long long>::value? yes
(sizeof(uint64_t) == 8) && !std::is_signed<uint64_t>::value? yes

```

On a system where the current type constraint check works, the same code outputs this
```
int64_t...............: (x) 8
long..................: (l) 8
long int..............: (l) 8
long long int.........: (x) 8
long long.............: (x) 8
uint64_t..............: (y) 8
unsigned long.........: (m) 8
unsigned long int.....: (m) 8
unsigned long long int: (y) 8
unsigned long long....: (y) 8
long long == int64_t? yes
(sizeof(long long) == 8) && std::is_signed<long long>::value? yes
(sizeof(int64_t) == 8) && std::is_signed<int64_t>::value? yes
unsigned long long == uint64_t? yes
(sizeof(unsigned long long) == 8) && !std::is_signed<unsigned long long>::value? yes
(sizeof(uint64_t) == 8) && !std::is_signed<uint64_t>::value? yes
```

Since using an `int64_t` should be supported (as it is equivalent to `long long`), I propose that the code be modified to either use the integral types defined in `cstdint` (`int8_t`, `int16_t`, `int32_t`, `int64_t`), or the check should be changed to look for a 64-bit type that is signed using a combination of `sizeof` and `std::is_signed`

### Source code / logs
The following example produces the error
```
#include <tensorflow/core/framework/op.h>
#include <tensorflow/core/framework/op_kernel.h>

REGISTER_OP("ExampleOp").Attr("T: {int32, int64, uint32, uint64}");

template <typename T>
class ExampleOp : public tensorflow::OpKernel {
public:
  explicit ExampleOp(tensorflow::OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(tensorflow::OpKernelContext* context) override {}
};

REGISTER_KERNEL_BUILDER(Name("ExampleOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<int32_t>("T"), ExampleOp<int32_t>);
REGISTER_KERNEL_BUILDER(Name("ExampleOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<int64_t>("T"), ExampleOp<int64_t>);
REGISTER_KERNEL_BUILDER(Name("ExampleOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<uint32_t>("T"), ExampleOp<uint32_t>);
REGISTER_KERNEL_BUILDER(Name("ExampleOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<uint64_t>("T"), ExampleOp<uint64_t>);
```

Here is the resulting compilation log
```
/usr/bin/c++  -Dmwe_EXPORTS -isystem /usr/local/lib/python3.5/dist-packages/tensorflow/include -I../src -march=native -mtune=native -fPIC -O3 -DNDEBUG -fPIC   -march=native -mtune=native -MD -MT CMakeFiles/mwe.dir/mwe.cpp.o -MF CMakeFiles/mwe.dir/mwe.cpp.o.d -o CMakeFiles/mwe.dir/mwe.cpp.o -c ../mwe.cpp
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/tensor.h:23:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/device_base.h:23,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:26,
                 from ../mwe.cpp:2:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/types.h: In instantiation of ‘struct tensorflow::DataTypeToEnum<long int>’:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h:82:62:   required from ‘tensorflow::KernelDefBuilder& tensorflow::KernelDefBuilder::TypeConstraint(const char*) [with T = long int]’
../mwe.cpp:16:1:   required from here
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/types.h:356:3: error: static assertion failed: Specified Data Type not supported
   static_assert(IsValidDataType<T>::value, "Specified Data Type not supported");
   ^~~~~~~~~~~~~
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:28:0,
                 from ../mwe.cpp:2:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h: In instantiation of ‘tensorflow::KernelDefBuilder& tensorflow::KernelDefBuilder::TypeConstraint(const char*) [with T = long int]’:
../mwe.cpp:16:1:   required from here
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h:82:62: error: ‘v’ is not a member of ‘tensorflow::DataTypeToEnum<long int>’
   return this->TypeConstraint(attr_name, DataTypeToEnum<T>::v());
                                          ~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/tensor.h:23:0,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/device_base.h:23,
                 from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:26,
                 from ../mwe.cpp:2:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/types.h: In instantiation of ‘struct tensorflow::DataTypeToEnum<long unsigned int>’:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h:82:62:   required from ‘tensorflow::KernelDefBuilder& tensorflow::KernelDefBuilder::TypeConstraint(const char*) [with T = long unsigned int]’
../mwe.cpp:20:1:   required from here
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/types.h:356:3: error: static assertion failed: Specified Data Type not supported
   static_assert(IsValidDataType<T>::value, "Specified Data Type not supported");
   ^~~~~~~~~~~~~
In file included from /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:28:0,
                 from ../mwe.cpp:2:
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h: In instantiation of ‘tensorflow::KernelDefBuilder& tensorflow::KernelDefBuilder::TypeConstraint(const char*) [with T = long unsigned int]’:
../mwe.cpp:20:1:   required from here
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/kernel_def_builder.h:82:62: error: ‘v’ is not a member of ‘tensorflow::DataTypeToEnum<long unsigned int>’
   return this->TypeConstraint(attr_name, DataTypeToEnum<T>::v());
                                          ~~~~~~~~~~~~~~~~~~~~^~
```

EDIT: Added a minimal working example

**Comment by tensorflowbutler** [comment] 2018-07-06 12:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-07-23 23:03
It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Bidski** [comment] 2018-07-23 23:14
This is still an issue. A PR (#21042) has been created to address the problem.

**Comment by cy89** [comment] 2018-07-28 00:15
@alextp it looks like you've got opinions about this from the PR comment. Would you please run with this?

**Comment by alextp** [comment] 2018-07-30 15:53
Shouldn't we fix this by changing the typedefs using #ifdefs on the currently broken architectures?

Also my understanding is that calling the registration macros with our typedefs should work (that is, tensorflow::int64 instead of int64_t). If that's not the case then I think we have a bug which should be fixed in the way proposed in the PR.

**Comment by Bidski** [comment] 2018-07-30 23:13
Using `#ifdef`s (or similar) to figure out when a system is "broken" sounds like a pretty ugly hack to me. What would you even check for in this instance? 

As I explained in the PR, using `tensorflow::int64` and friends is only a viable solution if everyone knows

1. that these types exist (I had no idea of their existence until I stumbled across this error and began digging through the source to find the reason), and
1. that it is required that they are used to achieve the intended results

It is not obvious from any documentation that I have seen that either of these two things are the case, and I think it has been a large fluke that this issue has not arisen until now.

I would also argue that it would be more precise, and just better overall, if the `typedef`s were changed to use the standard types that are defined in `cstdint` (`std::int64_t` and friends) as these types will guarantee that values have an exact width on every system that supports the type. A `long long` is guaranteed to be "at least 64 bits", so there may be some systems where a `long long` is larger than 64 bits. In instances where a type must be _exactly_ 64 bits using a `long long` is asking for trouble.

In either case, the PR that I have proposed will guard you against all of these issues and will allow anything that the system deems is "a signed integral type that is 64 bits in size" to be matched up to the `DT_INT64` enum value. To me, this seems like what should be the intended behaviour.

**Comment by alextp** [comment] 2018-07-30 23:33
@Bidski the I agree with you that we should have much better documentation about adding ops to TensorFlow, and on how to write C++ code in the tensorflow project in general. Using the right int64 type is part of it, as is using the right string type (not std::string but tensorflow::string). I also agree that we should fix the current typedefs in the tensorflow codebase to be more precise (as you pointed out, "int64 = long long" is ok only on some architectures and compilers, and defining it to be int64_t would be better.

I'd welcome PRs which clarify our documentation or improve our typedefs.

I am a little concern about the code complexity vs benefit tradeoff in your pull request. While more precise, it's also more code, and can be wrong in ways that might be difficult for future maintainers to improve. Despite currently leading to broken code, the simple conceptual model of "1:1 mapping from these types to these enums" is very debuggable, while the model of "any type which matches these properties will map to these enums" can be weird to debug as new types arise (for example, what if there's something which makes the mapping no longer 1:1?).

The desired use case for these mappings, in the kernel registration path, is for most ops to be registered via the tf-maintained macros TF_CALL_int64, TF_CALL_ALL_TYPES, etc, which are expected to be free of bugs on all platforms we support.

Does this sound reasonable to you?

**Comment by Bidski** [comment] 2018-07-30 23:55
@alextp I agree with your concerns over the PR code complexity and the 1:1 mapping. The mapping is already not 1:1 with the PR code since `long long` and `int64_t` would be mapped to `DT_INT64` and we already know that some systems have an issue with `long long != int64_t` (namely mine). So while the forward mapping (type to enum) should be fine, the reverse mapping could be a problem.

I am happy with a solution that improves the documentation to make it clearer that there are correct types that should be used. Not just for adding ops, but for using the C++ API in general (it is quite obvious that there are tensorflow specific types in the Python API since all types are prefixed with a `tf.`, perhaps just less reliance on `using namespace tensorflow;` in the examples would resolve this issue). Further to this, I think the `typedef`s should be changed to use the C++ standard types (defined in `cstdint`).

**Comment by alextp** [comment] 2018-08-01 17:06
@Bidski I'd happily approve a PR to change our typedefs to be standard. Want to do it?

**Comment by tensorflowbutler** [comment] 2018-08-16 20:05
Nagging Assignee @alextp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 19:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-15 18:47
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by alextp** [comment] 2018-09-17 16:54
I think we should close this issue for now. Please reopen if you still think it should be addressed.

**Closed by alextp** 2018-09-17 16:54 UTC
Labels: stat:awaiting response

**Comment by maohuui** [comment] 2019-07-17 12:25
` auto gt_pts_trans = tensorflow::ops::Transpose(root, gt_pts, NULL);  `
I used 'tensorflow::ops::Transpose()' and occurred error despite gt_pts  is  DT_FLOAT

error: static assertion failed: Specified Data Type not supported
   static_assert(IsValidDataType<T>::value, "Specified Data Type not supported");
error: ‘v’ is not a member of ‘tensorflow::DataTypeToEnum<long int>’
       Tensor t(DataTypeToEnum<RealT>::v(), TensorShape());

**Comment by alextp** [comment] 2019-07-17 15:52
@maohuui this is a completely unrelated error on a completely unrelated piece of code. Please file a new issue following the template instead of spamming existing issues.
