### ISSUE TITLE
Online Hard Example Mining

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#17693] opened 2018-03-13 21:47 UTC
Is there a plan for OHEM in `tf.estimator.train_and_evaluate` or in combo with dataset api?

**Comment by tensorflowbutler** [comment] 2018-03-14 07:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jhseu** [comment] 2018-03-16 21:51
Reassigning to @xiejw who wrote train_and_evaluate. I doubt there's a plan, but if you have any suggestions, we're open to them.

**Comment by bhack** [comment] 2018-03-17 16:14
I think that generally there is a need of an intereplay between estimator train process and dataset api. Other than for OHEM this kind of interaction between could be useful for other tasks like identify labels with noise in a dataset etc.

**Comment by xiejw** [comment] 2018-03-19 14:41
assign @ispirmustafa for planning.

**Comment by tensorflowbutler** [comment] 2018-04-04 00:37
Nagging Assignee @ispirmustafa: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ispirmustafa** [comment] 2018-04-04 15:59
Hi @bhack 
We don't have any plan re: OHEM. Could you please elaborate more about your proposal?
Thank you

**Comment by bhack** [comment] 2018-04-04 17:13
Yes there are different approaches but just to make an example:
http://www.erogol.com/online-hard-example-mining-pytorch/

With high level api i.e. estimators, if we want to automate this process, we need a way to let estimators to interact with the dataset api and its iterators to handle hard cases mining.

There was also an old request on Keras: https://github.com/keras-team/keras/issues/6569

See also OHEM section in https://arxiv.org/pdf/1604.03540.pdf

**Comment by ispirmustafa** [comment] 2018-04-19 20:09
Closing since there isn't any plan. Having said that @bhack if you have come up examples i'll be happy to review.

**Closed by ispirmustafa** 2018-04-19 20:09 UTC
