### ISSUE TITLE
ConvLSTM2D Mixed Precision casting

### ISSUE THREAD

**Issue by nshoman** [tensorflow/tensorflow#37364] opened 2020-03-05 19:37 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes

- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 16.04

- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0

**Describe the current behavior**
Presumably, dtype isn't correctly cast for ConvLSTM2D when using mixed_precision policy. Issue is not present in other convolution layers such as Conv2D.

**Describe the expected behavior**
Filter of the Conv2D op for ConvLSTM2D should be float16 when using 'mixed_float16' mixed_precision policy

**Standalone code to reproduce the issue** 
````
import tensorflow as tf

policy=tf.keras.mixed_precision.experimental.Policy('mixed_float16')
tf.keras.mixed_precision.experimental.set_policy(policy)

x=tf.keras.Input(shape=(1,10,10,3))



clstm1 =  tf.keras.layers.ConvLSTM2D(
    filters=1,
    strides=1,
    kernel_size=1,
    padding='same',
    return_sequences=True)(x)
````

**Other info / logs** 

```
/tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    502                 "%s type %s of argument '%s'." %
    503                 (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
--> 504                  inferred_from[input_arg.type_attr]))
    505 
    506         types = [values.dtype]

TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type float16 of argument 'input'.
```

**Comment by amahendrakar** [comment] 2020-03-06 11:24
@nshoman,
I was able to reproduce the issue with [TF2.1](https://colab.sandbox.google.com/gist/amahendrakar/c45aca54869703bfd02b1e0b23203668/37364.ipynb), however the issue seems to be fixed with [TF-nightly](https://colab.sandbox.google.com/gist/amahendrakar/1d52785593f67345e46e6e9be01cf8e7/37364-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Closed** 2020-03-06 13:12 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug
