### ISSUE TITLE
TF Inverse operations fail on 2080ti GPU with a cublas error

### ISSUE THREAD

**Issue by krsna6** [tensorflow/tensorflow#33624] opened 2019-10-23 04:29 UTC
I'm trying to use a loss function which needs an inverse op, but fails on tf 2.0 with the following error:

![image](https://user-images.githubusercontent.com/1873401/67357639-c08a0d00-f512-11e9-960b-ed54e7378ebc.png)

Other models/loss functions that don't use inverse ops train as expected using the GPU. Any pointers would be most appreciated.

**Comment by oanush** [comment] 2019-10-24 08:41
@krsna6 ,
Thank you for reporting the issue, Can you share a simple and standalone code to reproduce the issue?
Provide the exact sequence of commands / steps that you executed before running into the problem.

**Comment by oanush** [comment] 2019-11-05 05:50
@krsna6 ,
Hi, any update on the issue ?Thanks!

**Comment by oanush** [comment] 2019-11-11 10:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-11-11 10:13 UTC
Labels: TF 2.0, comp:ops, stat:awaiting response, type:support
