### ISSUE TITLE
'tensorflow/core/framework/numeric_types.h' file not found

### ISSUE THREAD

**Issue by laiqb** [tensorflow/tensorflow#27030] opened 2019-03-22 09:57 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- OS Platform and Distribution : cenos7 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source code 
- TensorFlow version: 1.93
- Python version: 3.6
- Installed using virtualenv? pip? conda?: un installed virtualenv
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the documentation issue**
In centos, I downloaded the tensorflow project. I open '/root/tensorflow/tensorflow/core/framework/allocator.h' file,  Tips can not find thoese included files, such as 'tensorflow/core/framework/numeric_types.h' file not found.but those files are already exists. thanks 
**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by jvishnuvardhan** [comment] 2019-03-22 17:55
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by laiqb** [comment] 2019-03-22 23:37
if I change as  #include  ‘numberic_types.h’ , it works. it maybe the path problem. thanks

**Comment by jvishnuvardhan** [comment] 2019-03-23 02:09
@laiqb If it is resolved, please close the issue. Thanks!

**Comment by laiqb** [comment] 2019-03-23 06:38
I think there is a better way, otherwise I must modify many files.

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:26
@laiqb Could you check whether the bug persists in tf-nightly? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-05 21:02
@laiqb I don't see path issue here as all the files are in the correct path. I am not sure what we can do from tensorflow side as all the files are in right location. Thanks!

**Closed** 2019-04-12 09:39 UTC
Labels: comp:ops, stat:awaiting response, type:docs
