### ISSUE TITLE
TensorFlow 1.0 on Windows: OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits

### ISSUE THREAD

**Issue by rringham** [tensorflow/tensorflow#8500] opened 2017-03-17 14:20 UTC
Just installed TensorFlow 1.0 on Windows 10 (x64) on a Surface Pro 4 following the instructions from here: https://www.tensorflow.org/install/install_windows (e.g. pip3 install --upgrade tensorflow).

I'm unable to validate my installation, though - here's what I'm running into:

```~\Projects> python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf;
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'
>>>
```

There seem to be several similar reports that indicate this is fixed, but as far as I can tell, this is still effectively broken when you install a clean version of TensorFlow on Windows. Is installing a nightly build the only way to get past this?

**Comment by Carmezim** [comment] 2017-03-17 20:36
Duplicate of #7859.

**Comment by concretevitamin** [comment] 2017-03-17 21:12
Thanks @Carmezim.  Closing this for now, please re-open if using the nightly doesn't work for you.

**Closed by concretevitamin** 2017-03-17 21:12 UTC

**Comment by rringham** [comment] 2017-03-17 22:12
Are there instructions on how to install a nightly build? It's not clear how to get that set up.

**Comment by Carmezim** [comment] 2017-03-17 23:18
@rringham You download the wheel and install it with `pip` like the build on the website, but you will be doing that locally. 

For instance, [select the most recent working build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/) (blue) from the list on the left, choose the version you want, CPU or GPU, and download the wheel. On the terminal `cd` to the directory you downloaded the build to and install it with `pip install <name-of-the-wheel>`

**Comment by rringham** [comment] 2017-03-18 00:57
Thank you @Carmezim!

**Comment by anselal** [comment] 2017-04-20 20:44
Installing the latest nightly "tensorflow_gpu-1.1.0rc2-cp35-cp35m-win_amd64.whl" seems to fixe those errors but running the same code as @rringham I get:


2017-04-20 23:40:48.766978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE instructions, but these are available on your m
achine and could speed up CPU computations.
2017-04-20 23:40:48.766978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-04-20 23:40:48.766978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE3 instructions, but these are available on your
machine and could speed up CPU computations.
2017-04-20 23:40:48.766978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.1 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-04-20 23:40:48.767978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.2 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-04-20 23:40:48.767978: W c:\tf_jenkins\home\workspace\nightly-win\device\gp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX instructions, but these are available on your m
achine and could speed up CPU computations.

**Comment by Carmezim** [comment] 2017-04-20 21:17
@anselal 
http://stackoverflow.com/questions/43134753/tensorflow-wasnt-compiled-to-use-sse-etc-instructions-but-these-are-availab
http://stackoverflow.com/questions/43335531/how-to-use-sse4-1-instructions-without-install-tensorflow-from-source

**Comment by anselal** [comment] 2017-04-21 05:52
@Carmezim thank you for the hint !! :+1:
