### ISSUE TITLE
Custom Distributed Strategy

### ISSUE THREAD

**Issue by jpadrao** [tensorflow/tensorflow#32355] opened 2019-09-09 14:14 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

As Tensorflow stands, there is no easy and intuitive way to implement a new distribution strategy. The ones available, (MirroredStrategy, MultiWorkerMirroredStrategy, ...), work fine but the code seems very complex, and there isn't a tutorial/guide on how to develop a new one

**Will this change the current api? How?**

The api cloud be restructured to ease the support of new distributed strategy. A tutorial/guide on how to develop one would also be appreciated 

**Who will benefit with this feature?**

Researchers who want to reduce the time spent training distributed tensorflow models

**Any Other info.**

**Comment by ymodak** [comment] 2019-09-11 17:39
This is a good example of using TF Distribution Strategy from ground up. 
See https://www.tensorflow.org/tutorials/distribute/keras
Hope this helps. Thanks!

**Comment by jpadrao** [comment] 2019-09-11 18:10
hi ymodak, thanks for the response

I know how to apply strategies to model, and they work well. But what if you want to develop **your own** strategy? an alternative to MultiWorkerMirroredStrategy, for example. 

Is there any good tutorial on how to develop an alternative to the existing strategies?
Is the API prepared to support **new** distribution strategies?

thanks

**Comment by jpadrao** [comment] 2019-09-20 14:25
Any updates?

I found this [readme](https://github.com/tensorflow/community/blob/master/rfcs/20181016-replicator.md#use-case-4-users-who-will-create-new-distributionstrategy-implementations) which explains some aspects of the API, but doesn't really explains how to create a new Distribution Strategy, or at least, a new reduction method

thanks

**Comment by liyi193328** [comment] 2019-12-04 15:55
Look forward some examples

**Comment by saikumarchalla** [comment] 2020-06-25 10:51
@jpadrao Closing this issue as it was the intended behavior. Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by saikumarchalla** 2020-06-25 10:51 UTC
Labels: TF 1.14, comp:dist-strat, type:feature
