### ISSUE TITLE
F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine. Aborted

### ISSUE THREAD

**Issue by saurabhaec** [tensorflow/tensorflow#26241] opened 2019-03-01 05:52 UTC
Error :

tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted

 getting this error after running

**python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml**

Version:

 
My System Config

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 9
Model name:            AMD Opteron(tm) Processor 6128 HE
Stepping:              1
CPU MHz:               2000.000
BogoMIPS:              4000.00
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              10236K
NUMA node0 CPU(s):     0

**Comment by jvishnuvardhan** [comment] 2019-03-01 18:06
@saurabhaec hank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-03-16 12:46
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-03-18 20:31
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-18 20:31 UTC
Labels: stat:awaiting response, type:build/install

**Comment by zeffon** [comment] 2019-05-29 02:39
I have the same error

**Comment by MaxKKuznetsov** [comment] 2021-07-14 15:42
The error: 
F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine. Aborted (core dumped) 
my machine: Intel Celeron CPU J1900 1.99GHz

**Comment by jvishnuvardhan** [comment] 2021-07-14 18:49
@MaxKKuznetsov Please open a new issue as this was an old issue that was closed more than two years ago. Thanks!
