### ISSUE TITLE
'No module named tensorflow' after installing via pip

### ISSUE THREAD

**Issue by tristanbrown** [tensorflow/tensorflow#6548] opened 2016-12-29 01:43 UTC
I'm running Anaconda on win64. 
The files are in the correct site-packages directory, with an `__init__.py`, but python doesn't seem to be able to recognize the module, regardless of whether I'm working in a virtual environment or the root directory. 
None of the following has changed this result:
[This.](https://www.tensorflow.org/get_started/os_setup#pip_installation_on_windows)
[This.](https://github.com/tensorflow/tensorflow/issues/6136)
[This.](https://www.reddit.com/r/MachineLearning/comments/3tcxs6/something_does_not_work_for_me_i_get_no_module/)

**Comment by tristanbrown** [comment] 2016-12-29 03:15
I originally tried setting it up by generating an environment.yml file:
```
name: tensorflow
dependencies:
- python=3
- pip
- numpy
- scipy
- matplotlib
- pandas
- pip:
    - tensorflow
```
In the same directory, I use `conda env create`, followed by `activate tensorflow`. Running any `import tensorflow` statement then prints `ImportError: No module named 'tensorflow'`.

I've now found that I manually add 'C:\Program Files\Anaconda3\envs\tensorflow\Lib\site-packages' to my PYTHONPATH environment variable, I get past that error, though this workaround seems like it could cause problems with other environments. The next error that pops up is `ImportError: cannot import name 'multiarray'`, from numpy.

**Comment by gunan** [comment] 2016-12-29 07:24
There are some known anaconda issues.
In your pip install command, could you try adding the `--ignore_installed` flag

**Comment by Carmezim** [comment] 2016-12-29 14:56
When you said you tried the solution on #6136 if you just updated setuptools, as gunan pointed out the ignore flag may solve it.
If you had errors with `easy_install` during pip installation is a quirk between anaconda and pip that everytime both `setuptools` versions are out of sync this error happens.

**Comment by tristanbrown** [comment] 2016-12-30 04:14
I tried adding the `--ignore-installed` flag, and it doesn't change the result at all.

**Comment by Carmezim** [comment] 2016-12-30 04:33
Are you using anaconda 64-bit distr. and did you get any errors during pip installation? If possible can you show a log?

**Comment by tristanbrown** [comment] 2016-12-30 04:44
Yes, I'm using anaconda 64-bit, and there are no errors. 
```
(tensorflow) E:\Tristan\Mython\TensorFlowTutorial>pip install --ignore-installed tensorflow
Collecting tensorflow
  Using cached tensorflow-0.12.1-cp35-cp35m-win_amd64.whl
Collecting wheel>=0.26 (from tensorflow)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow)
  Using cached numpy-1.11.3-cp35-none-win_amd64.whl
Collecting six>=1.10.0 (from tensorflow)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.1.0 (from tensorflow)
  Using cached protobuf-3.1.0.post1-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.1.0->tensorflow)
  Using cached setuptools-32.3.1-py2.py3-none-any.whl
Installing collected packages: wheel, numpy, six, setuptools, protobuf, tensorflow
Successfully installed numpy-1.11.3 protobuf-3.1.0.post1 setuptools-32.3.1 six-1.10.0 tensorflow-0.12.1 wheel-0.29.0
```

**Comment by gunan** [comment] 2016-12-30 04:48
OK, one observation, you are installing tensorflow inside a conda environment, so tensorflow is only available in that conda environment.
by any chance, are you trying to run tensorflow outside this environment?

Another possible issue, is it possible you have multiple python distributions installed?

**Comment by Carmezim** [comment] 2016-12-30 05:01
Couldn't reproduce the error. It's something on your side.
```
C:\WINDOWS\system32>activate tensorflow

(tensorflow) C:\WINDOWS\system32>pip install --ignore-installed tensorflow
Collecting tensorflow
  Using cached tensorflow-0.12.1-cp35-cp35m-win_amd64.whl
Collecting numpy>=1.11.0 (from tensorflow)
  Downloading numpy-1.11.3-cp35-none-win_amd64.whl (7.6MB)
    100% |################################| 7.6MB 123kB/s
Collecting six>=1.10.0 (from tensorflow)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.1.0 (from tensorflow)
  Downloading protobuf-3.1.0.post1-py2.py3-none-any.whl (347kB)
    100% |################################| 348kB 907kB/s
Collecting wheel>=0.26 (from tensorflow)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 1.1MB/s
Collecting setuptools (from protobuf>=3.1.0->tensorflow)
  Downloading setuptools-32.3.1-py2.py3-none-any.whl (479kB)
    100% |################################| 481kB 415kB/s
Installing collected packages: numpy, six, setuptools, protobuf, wheel, tensorflow
Successfully installed numpy-1.11.3 protobuf-3.1.0.post1 setuptools-32.3.1 six-1.10.0 tensorflow-0.12.1 wheel-0.29.0

(tensorflow) C:\WINDOWS\system32>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, testing TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
b'Hello, testing TensorFlow!'
```

**Comment by zafartahirov** [comment] 2017-01-02 21:05
I might be mistaken, but I always thought that Anaconda has its own package and environment control and didn't use `pip` or `venv`. Have you tried following the [`conda` instructions](https://www.tensorflow.org/get_started/os_setup#anaconda_installation)? I am not sure if the instructions are the same for Windows, but it should as simple as

```bash
conda create -n tensorflow python=2.7
```

**Comment by gunan** [comment] 2017-01-03 03:30
virtualenv can still be made available when using anaconda, but you are right.
Anaconda has conda.

However, one important detail. We only have python 3.5 support in windows. so the `python=2.7` part in the command wont work in windows.

**Comment by michaelisard** [comment] 2017-01-06 00:22
@tristanbrown did these suggestions help?

**Comment by tristanbrown** [comment] 2017-01-10 21:56
The only other python distribution I have installed is WinPython, but I've already removed the path variables for that installation. 

I have followed the conda instructions. That line only creates the new environment, named "tensorflow." 

I have tried both:
1. Installing tensorflow within a conda environment and running it within that environment. 
2. Installing tensorflow to the root environment and running it outside of any environment. 

Both of these options render the same error. 

I can install and run other modules (e.g. theano, yahoo_finance, pandas_datareader) without issue, so this problem is unique to Tensorflow.

**Comment by gunan** [comment] 2017-01-10 22:02
What is your python installed with WinPython?
Also, I think when you say you followed Anaconda Instructions, that means you also have anaconda installed. So I believe you have two python distributions installed.
So maybe there is some confusion about your terminal which program is invoked?

**Comment by jart** [comment] 2017-01-13 23:57
@tristanbrown Could you also copy and paste your command line session into this bug similar to what @Carmezim did above? That should hopefully help us get a better idea of what's going on, since we can see the error message and the commands you're running.

**Comment by Carmezim** [comment] 2017-01-14 00:24
@jart I followed his same [steps](https://github.com/tensorflow/tensorflow/issues/6548#issuecomment-269576043) to try reporduce his error.
- Installed clean TensorFlow installation through `pip` with ignore flag
- Created new anaconda env 
- Activated it 
- Imported TensorFlow (where his error occurred) and ran snippet successfully
 
The difference is I have only one Python distribution which is Anaconda, while as @gunan pointed out @tristanbrown apparently has WinPython and Anaconda so is something to consider.

**Comment by jart** [comment] 2017-01-14 02:02
In that case I'll trust your judgement and close this one out. Thank you for your time @Carmezim.

**Comment by Carmezim** [comment] 2017-01-14 02:44
@jart Glad to help. If you try to install TensorFlow outside the conda env then try to import it inside the conda env it'll not work as expected and give the exact import error reported. 
But as he said he also tried within the environment and didn't succeed, I believe it's not a TensorFlow issue. (Sorry, I inverted the order of the steps above fixing on edit)

Here are the entire logs:

1. Testing TensorFlow installation within conda environment
```
C:\WINDOWS\system32>conda create -n tensorflow python=3.5
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Adriano\Anaconda3\envs\tensorflow:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1
    python:         3.5.2-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate tensorflow
#
# To deactivate this environment, use:
# > deactivate tensorflow
#
# * for power-users using bash, you must source
#


C:\WINDOWS\system32>activate tensorflow

(tensorflow) C:\WINDOWS\system32>pip install tensorflow --ignore-installed
Collecting tensorflow
  Using cached tensorflow-0.12.1-cp35-cp35m-win_amd64.whl
Collecting six>=1.10.0 (from tensorflow)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow)
  Using cached numpy-1.11.3-cp35-none-win_amd64.whl
Collecting wheel>=0.26 (from tensorflow)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting protobuf>=3.1.0 (from tensorflow)
  Using cached protobuf-3.1.0.post1-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.1.0->tensorflow)
  Using cached setuptools-32.3.1-py2.py3-none-any.whl
Installing collected packages: six, numpy, wheel, setuptools, protobuf, tensorflow
Successfully installed numpy-1.11.3 protobuf-3.1.0.post1 setuptools-32.3.1 six-1.10.0 tensorflow-0.12.1 wheel-0.29.0

(tensorflow) C:\WINDOWS\system32>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, testing installing TensorFlow inside conda environment!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
b'Hello, testing installing TensorFlow inside conda environment!'
```

2. Installing TensorFlow outside conda env then importing it within env
```
C:\WINDOWS\system32>pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-0.12.1-cp35-cp35m-win_amd64.whl
Requirement already satisfied: six>=1.10.0 in c:\users\adriano\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: protobuf>=3.1.0 in c:\users\adriano\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.11.0 in c:\users\adriano\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: wheel>=0.26 in c:\users\adriano\anaconda3\lib\site-packages (from tensorflow)
Requirement already satisfied: setuptools in c:\users\adriano\anaconda3\lib\site-packages (from protobuf>=3.1.0->tensorflow)
Installing collected packages: tensorflow
Successfully installed tensorflow-0.12.1

C:\WINDOWS\system32>conda create -n tensorflow-outside-conda python=3.5
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Adriano\Anaconda3\envs\tensorflow-outside-conda:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1
    python:         3.5.2-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate tensorflow-outside-conda
#
# To deactivate this environment, use:
# > deactivate tensorflow-outside-conda
#
# * for power-users using bash, you must source
#


C:\WINDOWS\system32>activate tensorflow-outside-conda

(tensorflow-outside-conda) C:\WINDOWS\system32>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'
```

**Closed** 2017-01-18 17:14 UTC
Labels: type:support

**Comment by ayushya2531** [comment] 2017-04-03 18:59
@Carmezim  I was also able to do the same things as you have shown in your post on 29th Dec. However, I am not being able to run a '.py' file. Anaconda gives the error that there is no module names tensorflow.

**Comment by Carmezim** [comment] 2017-04-03 19:05
Hi @ayushya2531, sorry you are having problems. Would you mind to please open a new issue filling the template with the necessary info and commenting me so we can better asses what is happening?

**Comment by veryvishal** [comment] 2017-04-11 13:35
I installed using pip3, and then it dint work on `python` prompt. Used `python3` prompt and it worked like a charm!

**Comment by ernestyalumni** [comment] 2017-07-11 10:56
@Carmezim 

I am on Fedora 23 Workstation (will upgrade soon with full reinstall) and --ignore_installed worked perfectly for me, with anaconda installed.  In my next reinstall on this system, I would NOT install anaconda because of how it places the site-packages separately other than from root, during pip.  

Since I also confirmed pip install --ignore-installed tensorflow-gpu worked without a hitch and I confirmed the GPU ran with import tensorflow-gpu I'll repeat your answer (worth repeating):

In your pip install command, could you try adding the --ignore_installed flag

Question: why did --ignore_installed work?  (for the future)

**Comment by aritrabasu104** [comment] 2017-08-29 07:27
I am having the same issue.. @tristanbrown were u able to solve ur issue?

**Comment by Kaiwen-Zhong** [comment] 2017-08-30 19:30
Same issue here and not yet able to solve it. Is it because you have multiple python distribution?

**Comment by tristanbrown** [comment] 2017-09-06 01:27
The error came from the multiple Python distributions I had installed. I removed all the other ones from my PATH file, and the issue was resolved.

**Comment by sunsided** [comment] 2017-09-23 23:51
For me it was similar with TensorFlow built from source. In the end I uninstalled `tensorflow` and `numpy` and then reinstalled both (`tensorflow` first, then `numpy` via conda); this solved the issue.

**Comment by seeiespi** [comment] 2017-11-21 22:54
For me, the error went I away when I went into the anaconda prompt and activated tensorflow using the pre-installation command: activate tensorflow
But I still have no idea why that worked :/

**Comment by superjose** [comment] 2018-01-23 13:48
I was having the same problem. I'm running Windows 10 Build 17074 and how I got it running was by opening a Command Prompt (CMD - Not PowerShell) as Administrator, and following[ the installation tutorial.](https://www.tensorflow.org/install/install_windows)

**Comment by madhusudangr** [comment] 2018-01-23 18:06
@superjose I tried it in CMD, nothing different. Installation finishes without any error, but I am not able to import tensorflow

**Comment by superjose** [comment] 2018-01-23 18:14
@madhusudangr Did you try running CMD as Administrator?

**Comment by superjose** [comment] 2018-01-23 18:23
@madhusudangr I don't know if this will help you, but here's my Path's content inside Environment Variables:
![image](https://user-images.githubusercontent.com/8230270/35292896-f1cd91e4-003f-11e8-96f2-8f6e0c8c5c68.png)

If you're using Windows 7/8,x, you can always do:

1) Go to Computer
2) Click System Properties.
3) Click Advanced System Settings
4) Under the Advanced Tab (Should be already selected) click Environment Variables.

OR:
Press WinKey + Break.

In Windows 10:
1) Go to Computer and Click System Properties OR Go to Settings and Click System and go to the About tab.
2) On the right panel, click "System info" which appears under Related Settings. 
3) Click "Advanced System Settings"
4) Click on "Environment Variables"

Check this image to see if it helps:
![image](https://user-images.githubusercontent.com/8230270/35293090-a25ac400-0040-11e8-9ac7-93aded5a59da.png)

**Comment by vfrank66** [comment] 2018-08-31 20:05
This is an old post but I had this same issue 8/2018 with conda environments and tensorflow (SE led me here). Maybe this will help someone else:

![image](https://user-images.githubusercontent.com/7524999/44933291-28d5c800-ad2e-11e8-9b67-e4ae013214e5.png)

Although in the conda environment as seen in the picture. And tensorflow being installed in the conda environment. I had to execute the python from the environment folder in order for python to recognize tensorflow. 

This is hobby work for me so I cannot verify why this is.

**Comment by aslandery** [comment] 2018-10-31 08:07
I met with the same problem after I upgrade Tensorflow(1.1->1.4) in Conda environment via `pip --ignore_installed`. Then I install via `conda install tensorflow==1.4` again. The tensorflow installed via pip seems to be covered by the conda installed one. Then the problem disappears. I dont know what is different between these two installation methods.

**Comment by amrithadevadiga** [comment] 2019-09-05 11:16
I have installed conda on centos7 ..later when i installed tensorflow by executing command 
conda create -y -n tensorflow python=2.7 
source activate tensorflow
conda install tensorflow

i logged in to container to test the tensorflow installation 

python
Python 2.7.16 |Anaconda, Inc.| (default, Aug 22 2019, 16:00:36)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf

am getting output without any error if i execute "source activate tensorflow" in the beginning else when i execute  import tensorflow as tf i will get "ImportError: No module named tensorflow
" so is it necessary that i should use  "source activate tensorflow" or any mistake is there in my installation

**Comment by sjtuytc** [comment] 2020-01-17 15:59
I solved it by removing other PATH in .bashrc, then restart the shell.

**Comment by unixrh** [comment] 2020-01-18 06:05
I solved this problem by update my $path. In my case, I installed Anaconda3 on my Mac OSX. The problem is because anaconda add its `bin` path to the beginning of $PATH, therefore you use its python. So you may try to update your $PATH to use maybe `/usr/local/bin/python`

**Comment by Diego87P** [comment] 2021-07-28 12:44
I solved it installing by 'conda install tensorflow', running CMD as Administrator.
