### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory on deep Q learning model

### ISSUE THREAD

**Issue by AlienSmith** [tensorflow/tensorflow#16061] opened 2018-01-12 01:18 UTC
I was having fun with the Deep Q learning model, which came from https://github.com/dennybritz/reinforcement-learning/blob/master/DQN. Then after 750 episodes this error popped up.
![1](https://user-images.githubusercontent.com/20869223/34855218-6ae8778a-f779-11e7-9a7f-bbe7670f47b0.png)
![2](https://user-images.githubusercontent.com/20869223/34855219-6b1bc496-f779-11e7-9183-24306a413c01.png)
![3](https://user-images.githubusercontent.com/20869223/34855220-6b4a6436-f779-11e7-84de-e66f157d5a68.png)
![4](https://user-images.githubusercontent.com/20869223/34855221-6b77d754-f779-11e7-90c8-2b700fd10d81.png)
![5](https://user-images.githubusercontent.com/20869223/34855222-6baf6d18-f779-11e7-9963-6a860225a0f2.png)
![6](https://user-images.githubusercontent.com/20869223/34855224-6bdfce68-f779-11e7-8a9a-16ddc709895e.png)
![7](https://user-images.githubusercontent.com/20869223/34855225-6c110014-f779-11e7-8738-c60e50059330.png)
I was running this code on Ubuntu 14.04 with a 8G graphic card(GTX 1070). I have had libav-tools installed before I ran the code.
I will try to reduce the batch size to see whether similar error will pop up again.
Please help me solve this problem.

**Comment by tensorflowbutler** [comment] 2018-01-12 12:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qmick** [comment] 2018-01-13 13:53
I suggest using `nvidia-smi` to monitor the GPU memory. If you find this is not a bug of TensorFlow, you can close this issue.

**Comment by tensorflowbutler** [comment] 2018-02-06 07:35
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:15
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 00:48
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:47
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatatodd** [comment] 2018-05-17 01:01
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Closed by tatatodd** 2018-05-17 01:01 UTC
Labels: stat:awaiting response
