### ISSUE TITLE
My TensorBoard isn't showing any data! What's wrong?

### ISSUE THREAD

**Issue by MartinThoma** [tensorflow/tensorflow#1942] opened 2016-04-14 13:50 UTC
I went through [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong):

1. `tensorboard --logdir=output/trash --debug` showed the expected path
2. `find output/trash | grep tfevents` showed two event files
3. `find output/trash | grep tfevents | xargs ls -lh` showed that they are 6.4M and 1.2M big.

Still, the tensorboard looks like this:

![Imgur](http://i.imgur.com/JLnLCB6.png)

The console shows:

    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
    I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
    WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG
    WARNING:tensorflow:Unable to read TensorBoard tag
    Starting TensorBoard  on port 6006
    (You can navigate to http://0.0.0.0:6006)
    WARNING:tensorflow:Found new file_version for event.proto. This will affect purging logic for TensorFlow restarts. Old: 1.0 New: 2.0
    WARNING:tensorflow:Found more than one graph event per run. Overwriting the graph with the newest event.
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET / HTTP/1.1" 200 -
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET /external/lodash/lodash.min.js HTTP/1.1" 200 -
    WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/lib/css/global.css' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/lib/css/global.css
    127.0.0.1 - - [14/Apr/2016 15:39:12] code 404, message Not Found
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET /external/d3/d3.min.js HTTP/1.1" 200 -
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET /external/plottable/plottable.min.js HTTP/1.1" 200 -
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET /external/plottable/plottable.css HTTP/1.1" 200 -
    127.0.0.1 - - [14/Apr/2016 15:39:12] "GET /external/graphlib/dist/graphlib.core.min.js HTTP/1.1" 200 -

### Environment info
Operating System: Linux Mint 17 Qiana

Installed version of CUDA and cuDNN: 

```bash
$ ls -l /usr/local/cuda-7.5/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
```

1. Which pip package you installed: pip 8.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".: 0.8.0rc0

### Steps to reproduce
1. Execute `tensorboard --logdir output/trash`
2. Open the browser with http://0.0.0.0:6006

**Comment by caisq** [comment] 2016-04-14 15:01
Possibly duplicate of https://github.com/tensorflow/tensorflow/issues/1923

**Comment by caisq** [comment] 2016-04-14 15:02
Fix to this issue in 0.8.0 RC0 is on the way and will be incorporate in the final 0.8.0 release. See #1926

**Closed** 2016-04-14 16:46 UTC
Labels: duplicate

**Comment by dayhaha** [comment] 2016-04-26 07:56
I met the same problem today and had fixed it. You just need to download the newest tensorflow source code from github and copy ./tensorflow/tensorboard to the tensorboard you installed(for you it's /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/)

**Comment by hechemeljed** [comment] 2016-04-26 08:37
I have fixed this issue as well few minutes ago , just merged between the :
$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
And TensorFlow source code from GitHub.
