### ISSUE TITLE
Converting MediaPipe Handpose model to TFLite model

### ISSUE THREAD

**Issue by akshayvernekar** [tensorflow/tensorflow#41800] opened 2020-07-24 07:40 UTC
HI team,

I am developing an embedded IOT device and I wanted to use the Handpose model for hand-tracking and gesture recognition but I didnt yet find a guide for converting Mediapipe models to TFLite model. Could you please provide a guide if its possible.

Thanks

**Comment by rmothukuru** [comment] 2020-07-28 06:51
@akshayvernekar,
I have transferred this issue from TF Hub repository to TF Lite Repository, as the issue is related to Lite.

**Comment by ymodak** [comment] 2020-07-29 23:29
@akshayvernekar Did you get a chance to look at [mediapipe/models](https://github.com/google/mediapipe/tree/master/mediapipe/models)?
For hand detection models see https://github.com/google/mediapipe/tree/master/mediapipe/models#hand-detection-and-tracking

**Comment by akshayvernekar** [comment] 2020-07-30 01:33
Thanks @ymodak this is exactly what I was looking for, the repository has the necessary .tflite files .

**Comment by ymodak** [comment] 2020-07-30 17:33
Glad I could help. Closing this issue now. Thanks!

**Closed by ymodak** 2020-07-30 17:33 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by TheBricktop** [comment] 2021-01-05 11:35
@ymodak link provided is void
the tflite model for hands was deleted from repo

**Comment by kinivi** [comment] 2021-01-08 21:17
The same problem, model was deleted

**Comment by kinivi** [comment] 2021-01-08 21:18
@TheBricktop I found this https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite

**Comment by TheBricktop** [comment] 2021-01-09 11:57
@kinivi do you have any idea how to convert pbtx to tflite? I need it for gpu accelerated palm and hand landmark

**Comment by kinivi** [comment] 2021-01-09 18:41
@TheBricktop I can mislead, but I think you can use tflite model with GPU acceleration just by checking one parameter in the interpretator.

**Comment by sgowroji** [comment] 2021-07-30 08:01
Hand tflite https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite

**Comment by jepious** [comment] 2023-06-28 15:42
Hello, the tflite model for hands was deleted from repo.
Could anyone please help me?
