### ISSUE TITLE
Tensorboard is missing css in lib/

### ISSUE THREAD

**Issue by piotr277** [tensorflow/tensorflow#1913] opened 2016-04-13 11:04 UTC
I've noticed that since April 2016 built python wheel files are missing css in tensorboard/lib.
Take a look at those two builds from Jenkins:
1. [13.04.2016](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-working/63/)
2. [31.03.2016](http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-working/50/)
and compare the contents of wheel file:
![tfboard-missing-css](https://cloud.githubusercontent.com/assets/18440238/14491109/3bfd4a3a-0177-11e6-91e9-8de4a8b34ec4.png)
This causes issues when trying to run tensorboard after installation of wheel file.
Manual installation from source provides the same result as above.

**Comment by danmane** [comment] 2016-04-14 20:34
Duplicate of https://github.com/tensorflow/tensorflow/issues/1923
Fixed by #1926

**Closed by danmane** 2016-04-14 20:34 UTC
Labels: bug, installation/startup, tensorboard
