### ISSUE TITLE
TocoConvertor: converting keras models to tflite doesn't support custom objects

### ISSUE THREAD

**Issue by ophiry** [tensorflow/tensorflow#21429] opened 2018-08-07 06:08 UTC
Have I written custom code: No
OS Platform and Distribution: Mac 
TensorFlow installed from: pip
TensorFlow version: 1.10-rc1
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: `tensorflow.contrib.lite.TocoConverter.from_keras_model_file(model_file, custom_objects=CUSTOM_OBJECTS)`
Mobile device: N/A

-----

This is required to convert models that use custom layers or loss functions

this is the fix (will submit a PR soon):
```
From 2c2179765cc9006762cf75c6a1b587e06895b869 Mon Sep 17 00:00:00 2001
From: Ophir Yoktan <ophir@ziprecruiter.com>
Date: Wed, 1 Aug 2018 10:16:10 +0300
Subject: [PATCH] add support for custom_objects when loading keras model for
 conversion

---
 tensorflow/contrib/lite/python/lite.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/tensorflow/contrib/lite/python/lite.py b/tensorflow/contrib/lite/python/lite.py
index 2f9b9d469a2..c12617df061 100644
--- a/tensorflow/contrib/lite/python/lite.py
+++ b/tensorflow/contrib/lite/python/lite.py
@@ -274,7 +274,8 @@ def from_keras_model_file(cls,
                             model_file,
                             input_arrays=None,
                             input_shapes=None,
-                            output_arrays=None):
+                            output_arrays=None,
+                            custom_objects=None):
     """Creates a TocoConverter class from a tf.keras model file.
 
     Args:
@@ -293,7 +294,7 @@ def from_keras_model_file(cls,
     """
     _keras.backend.clear_session()
     _keras.backend.set_learning_phase(False)
-    keras_model = _keras.models.load_model(model_file)
+    keras_model = _keras.models.load_model(model_file, custom_objects=custom_objects)
     sess = _keras.backend.get_session()
 
     # Get input and output tensors.
```

**Comment by tensorflowbutler** [comment] 2018-08-07 18:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by aselle** [comment] 2018-08-08 18:37
@gargn , PTAL.

**Comment by gargn** [comment] 2018-08-16 17:37
Is there a PR for this? If so, can you add a link?

**Comment by tensorflowbutler** [comment] 2018-09-08 18:46
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gargn** [comment] 2018-09-11 18:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gargn** 2018-09-11 18:40 UTC
Labels: comp:lite, type:feature

**Comment by ophiry** [comment] 2019-01-15 14:51
The issue is still open.
will appreciate if somebody will mere the patch from the original version (I have problems with submitting a  pull request with my user)

**Comment by gitman88** [comment] 2019-02-15 08:32
Did you manage to convert a Keras model with custom layers to tflite? If so how?

**Comment by ophiry** [comment] 2019-02-15 09:01
More or less. By applying the patch in this thread
There were other issues afterwards that are not keras related (unsupported
operations)

**Comment by gitman88** [comment] 2019-02-15 09:49
Okey! How did you apply the patch? I tried forking the repository and implement the functionality (like you did) and then install that version of tensorflow locally in an anaconda environment. Did not manage to do that however. Is there another approach or should it be doable?

**Comment by ophiry** [comment] 2019-02-15 10:39
I applied it on the installed package (to avoid recompiling everything)

**Comment by SJCaldwell** [comment] 2019-05-24 20:27
Is this fixed? I also like to use custom objects.

**Comment by gargn** [comment] 2019-05-24 21:27
This functionality has been added by 09deaeb.

**Comment by Lotte1990** [comment] 2020-01-22 15:33
Somehow, this functionality is not in TF2. In TensorFlow 2.1.0 I get:

TypeError: from_keras_model() got an unexpected keyword argument 'custom_objects'
when using `tf.lite.TFLiteConverter.from_keras_model`

or

AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_keras_model_file'
when using `tf.lite.TFLiteConverter.from_keras_model_file`

My model was created using TensorFlow 2.1.0 (Keras 2.2.4-tf) so I cannot use the V1 converter.

If I understand correctly, it is currently not possible to use custom objects in .tflite models for TF2. When I use `tf.lite.TFLiteConverter.from_keras_model` without `custom_objects` it creates the .tflite file without errors/warnings, but in TensorFlow Lite this results in failure of `interpreter->AllocateTensors()`. This is probably due to an error in the converted model, because this does not happen when I don't use custom objects. `interpreter->AllocateTensors()` clearly fails because I didn't define `custom_objects`, which makes sense. Please copy this functionality to TF2.

**Comment by ROAbb** [comment] 2020-02-13 19:24
@Lotte1990  I have also this problem. Could you find a solution?

**Comment by gargn** [comment] 2020-02-13 19:29
In 2.X you need to load your Keras model yourself with the `custom_objects` passed in and then call `from_keras_model`. Please reference [this](https://www.tensorflow.org/lite/convert/python_api#converting_a_keras_model_) example on how to convert a model using `from_keras_model`. Please reference [this](https://www.tensorflow.org/lite/convert/1x_compatibility) document on details on compatibility between 1.X and 2.X.
