### ISSUE TITLE
Unable to build "Hello World" for ESP32

### ISSUE THREAD

**Issue by mr-goldhands** [tensorflow/tensorflow#36189] opened 2020-01-24 19:34 UTC
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: source
- Tensorflow version: ca0d5142f640d42037f22367ce3530b6b7a23b44
- Target platform: ESP32

**Describe the problem**
Building the example Hello World for ESp32 fails.

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. I successfully generated example by command:
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project`

2. I run building project by command:
`idf.py build`

3. I receved compilation error:
`[ 84%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c/constants.pb-c.c.obj
In file included from /home/dmytro/esp/projects/hello_world_tf/components/tfmicro/tensorflow/lite/micro/kernels/svdf.cc:25:
/home/dmytro/esp/projects/hello_world_tf/components/tfmicro/tensorflow/lite/micro/kernels/activation_utils.h: In function 'float tflite::ops::micro::ActivationValFloat(TfLiteFusedActivation, float)':
/home/dmytro/esp/projects/hello_world_tf/components/tfmicro/tensorflow/lite/micro/kernels/activation_utils.h:45:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
`

**Comment by mr-goldhands** [comment] 2020-01-24 21:52
I suppose issue related to changes made by [this commit.](https://github.com/tensorflow/tensorflow/commit/38ca4ecbf7418ace4d8c7edaf179cae7fc4c1ca5#diff-e574b564bf79a94413a08244c308291dL46)

**Comment by yangchengwork** [comment] 2020-02-02 01:37
My English is very poor，show mofidy code
`
diff --git a/tensorflow/lite/micro/kernels/activation_utils.h b/tensorflow/lite/micro/kernels/activation_utils.h
index 62f3237bac..5fe05967ad 100644
--- a/tensorflow/lite/micro/kernels/activation_utils.h
+++ b/tensorflow/lite/micro/kernels/activation_utils.h
@@ -41,6 +41,8 @@ inline float ActivationValFloat(TfLiteFusedActivation act, float a) {
       return std::signbit(a);
     case kTfLiteActSigmoid:
       return 1.0f / (1.0f + std::exp(-a));
+    default:
+      return a;
   }
 }
`

**Comment by christophergeek** [comment] 2020-04-23 17:12
Any resolution on this yet? I am having the same problem.

**Comment by mr-goldhands** [comment] 2020-08-15 11:43
@rockyrhodes , @Saduf2019 
**The issue has updated.**

@tensorflow/micro

**System information**

- Host OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow sources version: 71ff216576
- Target platform: ESP32
- ESP IDF version: v4.0.1

**Describe the problem**
Building the example Hello World for ESp32 fails.

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. I have cloned TensorFlow sources.

2. I successfully generated example by command:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project

3. I run building project by command:
idf.py build

4. I receved compilation error:
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

Full txt log of building "Hello World" attached to this message.
[Unable_to_build__Hello_World__for_ESP32.txt](https://github.com/tensorflow/tensorflow/files/5078582/Unable_to_build__Hello_World__for_ESP32.txt)

**Comment by AdityaHPatwardhan** [comment] 2020-10-01 07:16
Hi @mr-goldhands. I think the build issue is fixed with [this PR](./tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world), can you please check. If the problem is fixed you may close the issue, thank you.

**Comment by tensorflowbutler** [comment] 2021-06-10 18:14
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Closed** 2021-06-17 19:22 UTC
Labels: comp:lite, comp:micro, comp:micro:espressif, type:bug
