### ISSUE TITLE
[TF r1.8][TensorRT 4.0.0.3] Output "munmap_chunk(): invalid pointer"

### ISSUE THREAD

**Issue by MacwinWin** [tensorflow/tensorflow#19142] opened 2018-05-08 10:38 UTC
## **System information**
- **HaveI written custom code (as opposed to using a stock example script provided in TensorFlow):** no

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 18.04

- **TensorFlow installed from (source or binary):** source

- **TensorFlow version (use command below):** 1.8.0

- **Bazel version (if compiling from source):** 0.10.1

- **CUDA/cuDNN version:** 9.0/7.1.3

- **GPU model and memory:** GTX 1080 8gb

- **Exact command to reproduce:**
python [test_tftrt.py](https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/contrib/tensorrt/test/test_tftrt.py)

## **Source code / logs**
`2018-05-08 16:11:39.979209: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2018-05-08 16:11:39.979516: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 1`
`2018-05-08 16:11:40.197749: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2660] Max batch size= 100 max workspace size= 33554432`
`2018-05-08 16:11:40.197774: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2666] starting build engine`
`munmap_chunk(): invalid pointer`
`Aborted (core dumped)`

**Comment by samikama** [comment] 2018-05-08 21:34
@MacwinWin TensorRT 4.0 is not officially supported yet but we didn't observe this issue in my builds. Can you give more information on how you build?

Thanks,
Sami

**Comment by MacwinWin** [comment] 2018-05-09 01:29
@samikama I build the environment follow the instruction below.

 **1. Install CUDA 9.0\CuDNN 7.1.3 from runfile and tar file**

- After install CUDA in /usr/local/cuda, add 
`export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}`
`export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`
`export CUDA_HOME=/usr/local/cuda`
to ~/.bashrc
- Move the target files from extracted cudnn file to /usr/local/cuda, and create soft links.

 **2. Install TensorRT from tar file**

- Extract the tar file to my home directory, and add
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/micro/TensorRT-4.0.0.3/lib`
to ~/.bashrc
- Make the samples, and run well.

 **3. Install TensorFlow r1.8.0 from source follow the [official instruction](https://www.tensorflow.org/install/install_sources)**

- Bazel version 0.10.1, GCC version 4.8.5
-  execution of the configure script
`...`
`Do you wish to build TensorFlow with CUDA support? [y/N]: y`
`CUDA support will be enabled for TensorFlow.`
`Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 9.0]: 9.0`
`Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: `
`Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7.0]: 7.1`
`Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:`
`Do you wish to build TensorFlow with TensorRT support? [y/N]: y`
`TensorRT support will be enabled for TensorFlow.`
`Please specify the location where TensorRT is installed. [Default is /usr/lib/x86_64-linux-gnu]:/home/micro/TensorRT-4.0.0.3` 
`...`

**I wonder if it is possible that TensorFlow can not find TensorRT. Because when I remove the TensorRT-4.0.0.3 directory, I got the same logs:**
`munmap_chunk(): invalid pointer`
`Aborted (core dumped)`

Can anyone help me:)

**Comment by samikama** [comment] 2018-05-09 02:01
@MacwinWin Can you ensure that there are no other TensorRT or TensorFlow installations in your system. Also I usually prefer prepending to LD_LIBRARY_PATH rather than appending, i.e. `export LD_LIBRARY_PATH=/home/micro/TensorRT-4.0.0.3/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`
To use TensorRT with TensorFlow, you don't need to compile the samples.

I see that you set ubuntu version 18.04. If this is not a typo, we haven't tried anything on Ubuntu 18.04 and it is not officially supported. TensorRT is not built for 18.04 and may not work there, especially in 4.0RC, when TensorRT is released, things may improve but it is not guaranteed.

**Comment by kahkeng** [comment] 2018-05-10 20:45
I'm also seeing this for Ubuntu 16.04 on GTX 1080 or TitanX Pascal GPUs.
```
2018-05-10 19:11:35.252280: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so return
ing NUMA node zero
2018-05-10 19:11:35.394301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so return
ing NUMA node zero
2018-05-10 19:11:35.517305: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so return
ing NUMA node zero
2018-05-10 19:11:35.661768: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 3
2018-05-10 19:11:36.218467: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2660] Max batch size= 100 max workspace size= 33554432
2018-05-10 19:11:36.218532: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2666] starting build engine
*** Error in `python': munmap_chunk(): invalid pointer: 0x00007ffc19df4fe0 ***
```

Here's the Dockerfile I used to reproduce the issue:

```
# Commands ran:
# docker build -t cuda9.0_tf1.8_trt4 .
# nvidia-docker run -it cuda9.0_tf1.8_trt4 bash
# python /install/test_tftrt.py

FROM nvidia/cuda:9.0-base-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cuda-command-line-tools-9-0 \
        cuda-cublas-9-0 \
        cuda-cufft-9-0 \
        cuda-curand-9-0 \
        cuda-cusolver-9-0 \
        cuda-cusparse-9-0 \
        cuda-libraries-dev-9-0 \
        curl \
        libcudnn7=7.0.5.15-1+cuda9.0 \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        rsync \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
        && \
    python -m ipykernel.kernelspec

ENV LD_LIBRARY_PATH=/TensorRT-4.0.0.3/lib:$LD_LIBRARY_PATH

COPY test_tftrt.py /install/
COPY TensorRT-4.0.0.3.Ubuntu-16.04.4.x86_64-gnu.cuda-9.0.cudnn7.0.tar.gz /install/

RUN tar xzvf /install/TensorRT-4.0.0.3.Ubuntu-16.04.4.x86_64-gnu.cuda-9.0.cudnn7.0.tar.gz && rm /install/TensorRT-4.0.0.3.Ubuntu-16.04.4.x86_64-gnu.cuda-9.0.cudnn7.0.tar.gz

RUN cd /TensorRT-4.0.0.3/python && pip2 install tensorrt-4.0.0.3-cp27-cp27mu-linux_x86_64.whl
RUN pip2 install tensorflow-gpu==1.8
```

FWIW I also tried TensorRT-3.0.4 and got the same error. Relevant changes to Dockerfile:
```
COPY TensorRT-3.0.4.Ubuntu-16.04.3.x86_64.cuda-9.0.cudnn7.0.tar.gz /install/

RUN tar xzvf /install/TensorRT-3.0.4.Ubuntu-16.04.3.x86_64.cuda-9.0.cudnn7.0.tar.gz && rm /install/TensorRT-3.0.4.Ubuntu-16.04.3.x86_64.cuda-9.0.cudnn7.0.tar.gz

RUN cd /TensorRT-3.0.4/python && pip2 install tensorrt-3.0.4-cp27-cp27mu-linux_x86_64.whl
RUN pip2 install tensorflow-gpu==1.8
```

Interestingly, I'm able to get the test_tftrt.py script to run fine in docker on a PX2 (with TensorRT 3.02 installed by the DriveWorks SDK, and Tensorflow 1.8 binary installed from https://github.com/peterlee0127/tensorflow-nvJetson).

**Comment by samikama** [comment] 2018-05-10 21:18
@MacwinWin ,
It looks like you ran out of memory on the card, see third line from the end. Can you try with changing gpu memory allocation parameters and workspace size and try again? Are you by any chance driving X on your GPU 0 as well? if you run nvidia-smi you can see which processes are running on the card and free memory.
@kahkeng, 

Please see my response above. You need to use **14.04** version of the TRT libraries **NOT 16.04**.

**Comment by kahkeng** [comment] 2018-05-10 21:46
@samikama Sorry, I didn't see any clear recommendation to use 14.04 above. I just tried that out and it works for me. Thanks!

**Comment by samikama** [comment] 2018-05-10 21:54
@kahkeng,

Sorry I confused this with another issue. I didn't mention it in this one. It is well hidden in official installation instructions though :)

**Comment by MacwinWin** [comment] 2018-05-11 01:07
@samikama Yeah, It really due to the lack of GPU memory. When I only select one precision mode at once to run, everything works fine.
```
#!/bin/bash
python tftrt_sample.py --INT8 \
                       --num_loops 10 \
                       --topN 5 \
                       --batch_size 1 \
                       --workspace_size 3000 \
                       --log_file log.txt \
                       --network resnet_v1_50_frozen.pb \
                       --input_node input \
                       --output_nodes resnet_v1_50/predictions/Reshape_1 \
                       --img_size 224 \
                       --img_file  grace_hopper.jpg
```
Thanks!

**Comment by samikama** [comment] 2018-05-14 18:49
@MacwinWin, if you want to be able to use TRT4.0RC you need to recompile TensorFlow. However we are still working on TRT4.0 support in interface layer so not all features of TRT4 will be available to you. TRT4.0 support in Tensorflow will be available after TensorRT4.0 is released.

**Comment by reedwm** [comment] 2018-05-14 22:48
Closing because the original issue seems to be resolved.

**Closed by reedwm** 2018-05-14 22:48 UTC
