### ISSUE TITLE
tf.compat.v1.keras.backend.get_session gives erroneous deprecation warning

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#33182] opened 2019-10-09 20:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Accessing `tf.compat.v1.keras.backend.get_session` gives a deprecation warning telling you to use `tf.compat.v1.keras.backend.get_session`.

**Describe the expected behavior**

Accessing `tf.compat.v1.keras.backend.get_session` should not give a deprecation warning (since we're explicitly accessing the `compat.v1` namespace). Or it should direct the user to the correct function, if `tf.compat.v1.keras.backend.get_session` is not the right access point, rather than telling the user to use the namespace they're already using.

**Code to reproduce the issue**
``` python
import tensorflow as tf

tf.compat.v1.keras.backend.get_session
```

This results in the warning
```
The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.
```
(note that we're accessing `tf.compat.v1.keras.backend.get_session`, not `tf.keras.backend.get_session`).

**Comment by oanush** [comment] 2019-10-10 03:11
@drasmuss ,
When tried running the given code, i didn't receive any warning for TF-2.0 and 2.0rc2. Please find the [gist](https://colab.sandbox.google.com/gist/oanush/d05cac5c0bc2d8ed785cbc67f7af0a83/33182.ipynb) of colab. 
Can you please provide gist if the issue is replicating from your end?Thanks!

**Comment by drasmuss** [comment] 2019-10-10 12:38
For some reason the warning doesn't show up when executing through colab, you need to run it as an external command. See [gist here](https://colab.research.google.com/gist/drasmuss/3be97c8968acee0c5476dba394f8a113/33182.ipynb).

**Comment by fperrotta** [comment] 2019-10-29 20:39
I have the same issue.

**Comment by jvishnuvardhan** [comment] 2019-10-29 23:28
@drasmuss @fperrotta I ran it in my local (Mac Os) as well as in Colab. I don't see any warnings. Later today I will check it on Windows10. Thanks!

**Comment by fperrotta** [comment] 2019-11-02 14:52
I wonder if this is happening because i am loading a trained model file (hdf5) with tensor 1.15 and now i am importing it to apply with K.session and loader updates to tensor 2.x.

**Comment by samijaba** [comment] 2020-01-17 16:29
Have the same issue here too

**Comment by gowthamkpr** [comment] 2020-03-30 16:55
Have tried it in my local(ubuntu 18.02) and also on colab with tensorflow 2.2.0-rc2 and I didn't run into any issue. I am closing this issue right now. Please add additional comments for us to open this issue again. Thanks!

**Comment by drasmuss** [comment] 2020-03-30 17:02
When I run the same gist from above (https://github.com/tensorflow/tensorflow/issues/33182#issuecomment-540553089), switching to TF2.2rc2, I still see exactly the same error.

**Comment by gowthamkpr** [comment] 2020-03-30 18:13
@drasmuss Can you please share the `test.py` file. Thanks!

**Comment by drasmuss** [comment] 2020-03-30 18:23
The file is created within the gist, see this code
```
with open("test.py", "w") as f:
  f.write("import tensorflow as tf\ntf.compat.v1.keras.backend.get_session")
```

**Comment by JackBuck** [comment] 2020-05-25 10:51
I'm also getting this problem. It doesn't happen if I paste the lines directly into an ipython console, but it does if I put them in a separate module and import that (or if I run that module directly from the command line)

**Comment by drasmuss** [comment] 2021-05-19 14:24
As mentioned [above](https://github.com/tensorflow/tensorflow/issues/33182#issuecomment-540553089), the warning doesn't show up when executing within colab, you have to run it as an external command. I have updated the [gist](https://colab.research.google.com/gist/drasmuss/3be97c8968acee0c5476dba394f8a113/33182.ipynb) to use 2.5.0, and it shows the same warning message as before.

**Comment by mohantym** [comment] 2021-08-06 05:35
was able to replicate and resolve the issue in TF 2.5 by adding these lines. 
```
import logging, os
logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = '3'  
```
please find the gist [here ](https://colab.research.google.com/gist/mohantym/e45f039055d195f34be5b0a6b15aa42a/33182.ipynb#scrollTo=Q-l4usR8oPQw)

**Comment by drasmuss** [comment] 2021-08-06 13:56
That doesn't fix the problem, it just hides the erroneous warning.

**Comment by kumariko** [comment] 2021-08-25 09:13
I could reproduce the issue with TF 2.6 .Please, find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/962a8e4a96825e344610e728c0b957c0/untitled40.ipynb#scrollTo=IsjrTaJEiwM0).Thanks!

**Comment by tensorflowbutler** [comment] 2021-12-14 23:25
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by drasmuss** [comment] 2021-12-15 13:44
The issue still persists in TF 2.7, I created a new issue in the Keras repo here https://github.com/keras-team/keras/issues/15792

**Closed** 2022-01-11 18:04 UTC
Labels: type:bug, comp:keras, subtype:windows, 2.6.0
