### ISSUE TITLE
CPU nodes are swapped out using /grappler/optimizers/gpu_swapping_kernel

### ISSUE THREAD

**Issue by akhilkedia** [tensorflow/tensorflow#22246] opened 2018-09-13 07:41 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.5
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Issue occurs on both pip binary and compiled from source
- **TensorFlow version (use command below)**: 'v1.8.0-8-g23c2187' 1.8.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- **CUDA/cuDNN version**: CUDA 9.0, cuDNN 7.2.1.38
- **GPU model and memory**: GeForce GTX 1080, 11178MiB
- **Exact command to reproduce**: Cannot share the exact codebase

### Describe the problem

Tensorflow attempts to swap-out a node to the CPU to save memory, even when the node is already on CPU.

This happens in `core/grappler/optimizers/memory_optimizers.cc` with the op `_CopyFromGpuToHost`.
But since this swapping is intended to save GPU memory by swapping temporarily nodes from GPU to the the CPU, the kernel for that op in `core/grappler/optimizers/gpu_swapping_kernels.cc` is only for GPU devices.

A suggested fix will be to simply check if the node to be swapped out is already in CPU before making it eligible for swap_out/swap_in. Note that on reducing the model size this error disappears as more memory becomes free.

#### Some more information confirming the issue - 
The op is correctly registered in OpRegistry as shown by `tensorflow::OpRegistry::Global()->DebugString(false)`.
The OpKernel `CopyFromGpuToHostKernel` is built according to bazel logs.
The OpKernel is loaded on importing tensorflow in python, verified by adding a print in that file using `__attribute__((constructor)) )`

### Source code / logs

The relevant error is -

tensorflow.python.framework.errors_impl.NotFoundError: No registered '_CopyFromGpuToHost' OpKernel for CPU devices compatible with node swap_out_context_zoom/GatherNd_2_0 = _CopyFromGpuToHost[T=DT_INT32, _class=["loc@context_zoom/GatherNd_2_0"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_context_sents_len_0_10)
	.  Registered:  device='GPU'

	 [[Node: swap_out_context_zoom/GatherNd_2_0 = _CopyFromGpuToHost[T=DT_INT32, _class=["loc@context_zoom/GatherNd_2_0"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_context_sents_len_0_10)

I have attached the full log here - 
https://gist.github.com/akhilkedia/c13ff191e08b4462a3870a0b3a091e93

**Comment by akhilkedia** [comment] 2018-09-13 07:46
I just noticed that this is probably a duplicate of #22134 . Should I perhaps close this?

**Comment by ymodak** [comment] 2018-09-13 22:33
@akhilkedia  Thank you for your post. Yes this is a duplicate of #22134 . Therefore I am going to close this issue. Please stay tuned to #22134 for the fix and feel free to reopen if your issue still persists.

**Closed by ymodak** 2018-09-13 22:33 UTC
