### ISSUE TITLE
tf.identity() not copying varying inputs

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#8010] opened 2017-03-02 13:09 UTC
When using `tf.identity()` it seems like a proper implementation to pass through the input tensor without copying. However, when the input is the value of a variable it might change later, leading to surprising behavior:

```python
var = tf.Variable(1)
old = tf.identity(var.value())
with tf.control_dependencies([old]):
  with tf.control_dependencies([var.assign_add(1)]):
    new = tf.identity(var.value())

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run([old, new]))  # Unexpected: [2, 2]
```

I would think this code should be equivalent to the following workaround that uses a second variable to remember the previous value:

```python
var = tf.Variable(1)
old = tf.Variable(var.initialized_value())
with tf.control_dependencies([old.assign(var.value())]):
  with tf.control_dependencies([var.assign_add(1)]):
    new = tf.identity(var.value())

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run([old, new]))  # Expected: [1, 2]
```

Can we make `tf.identity()` aware of whether its input is static or varying, to always return the value from the time it's executed?

**Comment by tatatodd** [comment] 2017-03-03 00:12
@danijar Thanks for filing this issue!

I believe it's a duplicate of #4663 , so I'm closing this out.  If you feel I've made a mistake, respond to this issue and I'll re-open it.

**Closed by tatatodd** 2017-03-03 00:12 UTC
