### ISSUE TITLE
not getting installed in python 3.8.1

### ISSUE THREAD

**Issue by vishwas1234567** [tensorflow/tensorflow#36196] opened 2020-01-25 06:03 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by vishwas1234567** [comment] 2020-01-25 06:03
![image](https://user-images.githubusercontent.com/48592314/73117078-7e83c380-3f66-11ea-855d-349ba8a2d448.png)

**Comment by ashutosh1919** [comment] 2020-01-25 11:49
@vishwas1234567, Please take a look at [this issue](https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-577331441). It says that tensorflow is not supported for python 3.8 as of now. And if we talk about tensorflow 2.0 specifically, it supports the python range 3.4 to 3.7. If your computer has python 3.8 installed then you can install 3.7 too and use virtualenv to install tensorflow. Below is what you can do :

```sh
$ virtualenv --python=python3.7 my_venv  
$ source my_venv/bin/activate 
$ pip install tensorflow  
```

If your issue resolves by this method then please close the issue.

**Comment by mihaimaruseac** [comment] 2020-01-26 02:46
Closing as duplicate of #33374. Please use search before opening new issues, especially when opening multiple related ones.

**Closed by mihaimaruseac** 2020-01-26 02:46 UTC
