### ISSUE TITLE
parameters in XML file comparison

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#56241] opened 2022-05-24 11:12 UTC
Hello,

i am a bit unsure about the new xml file i created with a labelling tool. the first example is a tool that doesn't support object tracking, meaning you have to mark each object yourself. in the second example (i use) you can see that more parameters are added. now i wanted to know if there can be any problems with the creation of the tfrecord files?

the normal process is:

xml file -> csv file -> tfrecord

the following scripts are used for this: 

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/xml_to_csv.py / 
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/generate_tfrecord.py

are the parameters ignored by the python script and only read which are defined? 

standard xml file:
```
<annotation>
	<folder>train</folder>
	<filename>IMG_2385.JPG</filename>
	<path>C:\tensorflow_cards\train\IMG_2385.JPG</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>378</width>
		<height>504</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>king</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>92</xmin>
			<ymin>183</ymin>
			<xmax>223</xmax>
			<ymax>348</ymax>
		</bndbox>
	</object>
</annotation>
```
new xml file:

```
<annotation>
  <folder>image</folder>
  <filename>image_14.jpg</filename>
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
  <size>
    <width>720</width>
    <height>720</height>
    <depth></depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>person</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>281.22</xmin>
      <ymin>688.92</ymin>
      <xmax>323.7</xmax>
      <ymax>718.45</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
      <attribute>
        <name>track_id</name>
        <value>63</value>
      </attribute>
      <attribute>
        <name>keyframe</name>
        <value>True</value>
      </attribute>
    </attributes>
  </object>
</annotation>
```

**Comment by sushreebarsa** [comment] 2022-05-25 10:42
@Petros626 In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thank you!

**Comment by Petros626** [comment] 2022-05-25 11:59
should i delete this issue and create a new one with the template?

**Comment by sushreebarsa** [comment] 2022-05-26 12:47
@Petros626 This issue is a duplicate of this [ticket](https://github.com/tensorflow/tensorflow/issues/56257). Closing this ticket as we will track the other one.
Thank you!

**Closed by sushreebarsa** 2022-05-26 12:47 UTC
Labels: stat:awaiting response
