### ISSUE TITLE
No supported kernel for GPU devices is available (Apple M1 - Metal GPU)

### ISSUE THREAD

**Issue by spagliarini** [tensorflow/tensorflow#53026] opened 2021-11-10 23:52 UTC
I am trying to replicate the results I obtained from a training I have already completed on both ubuntu and windows (the code works on GPU), and I also tried the code using CPU and it works properly (on MacOS). The problem is when I try to use the GPU. The error message I get is very long (I can paste it all if needed), but I believe that the core part is the following:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation loader/GeneratorDataset: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.

Tensorflow version is 2.6.0, and I checked that the GPU is recognized:

> I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
> True

Thanks to anyone that could give hints about how to solve this issue.

**Comment by mohantym** [comment] 2021-11-11 03:51
Hi @spagliarini!
Could you please the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced]. Attaching similar issues for reference . [link1](https://stackoverflow.com/questions/55248631/tensorflow-cant-assign-a-device-for-operation/55455490),[link2](https://stackoverflow.com/questions/55248631/tensorflow-cant-assign-a-device-for-operation/55455490).Thanks!

**Comment by spagliarini** [comment] 2021-11-12 16:33
Hi @mohantym !

I am using MAcOS Monterey (12.0.1), Chip Apple M1. My tensorflow version is 2.6.0  (I can correctly see the GPU if I check, and I used other scripts that run on GPU, and they run properly). 

The part of the code where I run into the problem is the following: 

>   # Run training
>   scaffold = tf.train.Scaffold(saver=tf.train.Saver(max_to_keep=2000))
>   with tf.train.MonitoredTrainingSession(
>   #it creates a monitored session for training. Return a monitored session which is as
>   #session-like object that handles initialization, recovery and hooks
>       checkpoint_dir=args.train_dir,
>       save_checkpoint_secs=args.train_save_secs,
>       save_summaries_secs=args.train_summary_secs,
>       scaffold=scaffold) as sess:
>     while True:
>       # Train discriminator
>       for i in xrange(args.wavegan_disc_nupdates):  #the discriminator is created 5x generator update
>         sess.run(D_train_op)
> 
>         # Enforce Lipschitz constraint for WGAN
>         if D_clip_weights is not None:
>           sess.run(D_clip_weights)
> 
>       # Train generator
>       sess.run(G_train_op)
> 

I don't have a colab to reproduce the code, but the original code is from this git repository (https://github.com/chrisdonahue/wavegan): as I said, successfully used GPU version on linux/windows, and CPU version on MacOS (of course, I adapted the code to TF2 by using the "compat.v1" version, as it was not adapted in the linked version). 

The full error message I have is the following: 

> WARNING:tensorflow:From /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-

> packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Found 9356 audio files in specified directory
> /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/keras/legacy_tf_layers/core.py:236: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
>   warnings.warn('`tf.layers.dense` is deprecated and '
> /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/keras/engine/base_layer_v1.py:1676: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
>   warnings.warn('`layer.apply` is deprecated and '
> /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/keras/legacy_tf_layers/convolutional.py:1660: UserWarning: `tf.layers.conv2d_transpose` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2DTranspose` instead.
>   warnings.warn('`tf.layers.conv2d_transpose` is deprecated and '
> Metal device set to: Apple M1
> 
> systemMemory: 16.00 GB
> maxCacheSize: 5.33 GB
> 
> 2021-11-12 08:32:28.008642: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
> 2021-11-12 08:32:28.008723: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
> WARNING:tensorflow:From /Users/silviapagliarini/Documents/Python/wavegan-master/loader.py:197: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
> --------------------------------------------------------------------------------
> Generator vars
> [3, 16384] (49152): G/z_project/dense/kernel:0
> [16384] (16384): G/z_project/dense/bias:0
> [1, 25, 512, 1024] (13107200): G/upconv_0/conv2d_transpose/kernel:0
> [512] (512): G/upconv_0/conv2d_transpose/bias:0
> [1, 25, 256, 512] (3276800): G/upconv_1/conv2d_transpose/kernel:0
> [256] (256): G/upconv_1/conv2d_transpose/bias:0
> [1, 25, 128, 256] (819200): G/upconv_2/conv2d_transpose/kernel:0
> [128] (128): G/upconv_2/conv2d_transpose/bias:0
> [1, 25, 64, 128] (204800): G/upconv_3/conv2d_transpose/kernel:0
> [64] (64): G/upconv_3/conv2d_transpose/bias:0
> [1, 25, 1, 64] (1600): G/upconv_4/conv2d_transpose/kernel:0
> [1] (1): G/upconv_4/conv2d_transpose/bias:0
> Total params: 17476097 (66.67 MB)
> /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/keras/legacy_tf_layers/convolutional.py:263: UserWarning: `tf.layers.conv1d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv1D` instead.
>   warnings.warn('`tf.layers.conv1d` is deprecated and '
> --------------------------------------------------------------------------------
> Discriminator vars
> [25, 1, 64] (1600): D/downconv_0/conv1d/kernel:0
> [64] (64): D/downconv_0/conv1d/bias:0
> [25, 64, 128] (204800): D/downconv_1/conv1d/kernel:0
> [128] (128): D/downconv_1/conv1d/bias:0
> [25, 128, 256] (819200): D/downconv_2/conv1d/kernel:0
> [256] (256): D/downconv_2/conv1d/bias:0
> [25, 256, 512] (3276800): D/downconv_3/conv1d/kernel:0
> [512] (512): D/downconv_3/conv1d/bias:0
> [25, 512, 1024] (13107200): D/downconv_4/conv1d/kernel:0
> [1024] (1024): D/downconv_4/conv1d/bias:0
> [16384, 1] (16384): D/output/dense/kernel:0
> [1] (1): D/output/dense/bias:0
> Total params: 17427969 (66.48 MB)
> --------------------------------------------------------------------------------
> WARNING:tensorflow:From /Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/training_util.py:235: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
> 2021-11-12 08:32:28.778728: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
> 2021-11-12 08:32:28.778748: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
> Traceback (most recent call last):
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
>     return fn(*args)
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
>     self._extend_graph()
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
>     tf_session.ExtendSession(self._session)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation loader/GeneratorDataset: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
> Colocation Debug Info:
> Colocation group had the following types and supported devices: 
> Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
> IteratorGetNext: CPU GPU 
> OneShotIterator: CPU 
> IteratorToStringHandle: CPU GPU 
> PrefetchDataset: CPU GPU 
> GeneratorDataset: CPU GPU 
> 
> Colocation members, user-requested devices, and framework assigned devices, if any:
>   loader/GeneratorDataset (GeneratorDataset) /device:GPU:0
>   loader/PrefetchDataset_1 (PrefetchDataset) /device:GPU:0
>   loader/OneShotIterator (OneShotIterator) /device:GPU:0
>   loader/IteratorToStringHandle (IteratorToStringHandle) /device:GPU:0
>   loader/IteratorGetNext (IteratorGetNext) /device:GPU:0
> 
> Op: GeneratorDataset
> Node attrs: Tfinalize_func_args=[DT_STRING], output_shapes=[[64,16384,1,1]], finalize_func=__inference__remote_finalize_func_466[], init_func=__inference__remote_init_func_441[], output_types=[DT_FLOAT], Tinit_func_args=[DT_STRING, DT_VARIANT], next_func=__inference__remote_next_func_454[experimental_ints_on_device=true], Tnext_func_args=[DT_STRING]
> Registered kernels:
>   device='GPU'
>   device='CPU'
>   device='XLA_CPU'
> 
> 	 [[{{node loader/GeneratorDataset}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/silviapagliarini/Documents/Python/wavegan-master/train_wavegan.py", line 929, in <module>
>     train(fps, args)
>   File "/Users/silviapagliarini/Documents/Python/wavegan-master/train_wavegan.py", line 209, in train
>     with tf.train.MonitoredTrainingSession(
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 602, in MonitoredTrainingSession
>     return MonitoredSession(
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1035, in __init__
>     super(MonitoredSession, self).__init__(
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 750, in __init__
>     self._sess = _RecoverableSession(self._coordinated_creator)
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1232, in __init__
>     _WrappedSession.__init__(self, self._create_session())
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 1237, in _create_session
>     return self._sess_creator.create_session()
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 903, in create_session
>     self.tf_sess = self._session_creator.create_session()
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/monitored_session.py", line 662, in create_session
>     return self._get_session_manager().prepare_session(
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/session_manager.py", line 327, in prepare_session
>     sess.run(init_op, feed_dict=init_feed_dict)
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
>     result = self._run(None, fetches, feed_dict, options_ptr,
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
>     results = self._do_run(handle, final_targets, final_fetches,
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
>     return self._do_call(_run_fn, feeds, fetches, targets, options,
>   File "/Users/silviapagliarini/miniforge3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
>     raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation loader/GeneratorDataset: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
> Colocation Debug Info:
> Colocation group had the following types and supported devices: 
> Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
> IteratorGetNext: CPU GPU 
> OneShotIterator: CPU 
> IteratorToStringHandle: CPU GPU 
> PrefetchDataset: CPU GPU 
> GeneratorDataset: CPU GPU 
> 
> Colocation members, user-requested devices, and framework assigned devices, if any:
>   loader/GeneratorDataset (GeneratorDataset) /device:GPU:0
>   loader/PrefetchDataset_1 (PrefetchDataset) /device:GPU:0
>   loader/OneShotIterator (OneShotIterator) /device:GPU:0
>   loader/IteratorToStringHandle (IteratorToStringHandle) /device:GPU:0
>   loader/IteratorGetNext (IteratorGetNext) /device:GPU:0
> 
> Op: GeneratorDataset
> Node attrs: Tfinalize_func_args=[DT_STRING], output_shapes=[[64,16384,1,1]], finalize_func=__inference__remote_finalize_func_466[], init_func=__inference__remote_init_func_441[], output_types=[DT_FLOAT], Tinit_func_args=[DT_STRING, DT_VARIANT], next_func=__inference__remote_next_func_454[experimental_ints_on_device=true], Tnext_func_args=[DT_STRING]
> Registered kernels:
>   device='GPU'
>   device='CPU'
>   device='XLA_CPU'
> 
> 	 [[node loader/GeneratorDataset (defined at /Documents/Python/wavegan-master/loader.py:192) ]]

**Comment by mohantym** [comment] 2021-11-14 16:11
Hi @sachinprasadhs! Could you look at this issue?

**Comment by sachinprasadhs** [comment] 2021-11-16 02:50
Could you please try to configure the GPU device with [logical_device_configuration](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration?hl=zh-cn) and set some memory to see if the code runs without any issues.
Optionally, you can also try  [set_visible_devices](https://www.tensorflow.org/api_docs/python/tf/config/set_visible_devices) like below.
```
physical_devices = tf.config.list_physical_devices('GPU')
 tf.config.set_visible_devices(physical_devices[0], 'GPU')
```

**Comment by spagliarini** [comment] 2021-11-16 18:54
I have tried both options:
* allocated some memories using the instructions on logical_device_configuration
* added the set_visible_devices at the beginning of my code as suggested

I end up with the same error message. 

If this can help, I think the problem comes when I try to do the following:
```
      dataset = dataset.apply(
          tf.data.experimental.prefetch_to_device(
            '/device:GPU:{}'.format(prefetch_gpu_num)))
```

I also tried to give explicitely the device name (/device:GPU:0) but the error message does not change.

**Comment by kevint324** [comment] 2021-11-17 06:13
`pluggable_device` and `GPU` are completely two different things within TensorFlow
GPU is just for nvidia and AMP graphic cards and I'm pretty sure they don't have M1 support as a plugable device.

In short, you can't assign and OP on `/device:GPU:` with your apple M1.

**Comment by sachinprasadhs** [comment] 2021-11-17 18:35
Try the below sample code for the above module and let us know the output.

```
with tf.device('/GPU'):
  dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
  dataset = dataset.apply(tf.data.experimental.prefetch_to_device("GPU:0"))

for element in dataset:
  print(f'Tensor {element} is on device {element.device}')

Result:
#Tensor 1 is on device /job:localhost/replica:0/task:0/device:GPU:0
#Tensor 2 is on device /job:localhost/replica:0/task:0/device:GPU:0
#Tensor 3 is on device /job:localhost/replica:0/task:0/device:GPU:0
```

**Comment by spagliarini** [comment] 2021-11-17 18:50
Yes. Here is the output. 

```
with tf.device('/GPU'):
...   dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
...   dataset = dataset.apply(tf.data.experimental.prefetch_to_device("GPU:0"))
```

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2021-11-17 10:48:35.562861: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-11-17 10:48:35.563156: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

```
for element in dataset:
...   print(f'Tensor {element} is on device {element.device}')

```
2021-11-17 10:48:44.547542: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-11-17 10:48:44.552936: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2021-11-17 10:48:44.554274: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-11-17 10:48:44.574873: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
Tensor 1 is on device /job:localhost/replica:0/task:0/device:GPU:0
Tensor 2 is on device /job:localhost/replica:0/task:0/device:GPU:0
Tensor 3 is on device /job:localhost/replica:0/task:0/device:GPU:0

**Comment by sachinprasadhs** [comment] 2021-11-17 19:16
This is working as expected by seeing the result and it is able to detect the GPU as well, the problem is not with `prefetch_to_device`.

**Comment by spagliarini** [comment] 2021-11-17 20:10
Ok. So somehow there something that does not go well when I start the training with 

`tf.train.MonitoredTrainingSession`

If this is a problem related to how tensorflow works on Apple M1, do you have any suggestion about how to get around it?

**Comment by sachinprasadhs** [comment] 2021-11-20 00:58
`tf.train.MonitoredTrainingSession` is deprediated and you have to use with [tf.compat.v1.train.MonitoredTrainingSession](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/MonitoredTrainingSession). 
For Apple related issues you can raise it in their dedicated [forum](https://developer.apple.com/forums/).

**Comment by spagliarini** [comment] 2021-11-22 19:41
`tf.compat.v1.train.MonitoredTrainingSession` arises the same error message. 

I was reading again the whole error message from the beginning. Coming back to your point about the memory, I can see this warning:

`I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)`

I tried both your suggestions but I always have this warning. Could it be related to the issue I have later when starting Monitored Session - I tried also Session but I run into the same error).

**Comment by sachinprasadhs** [comment] 2021-11-24 16:53
Please refer to the similar issue on apple forum [here](https://developer.apple.com/forums/thread/684178), if that doesn't helps you please raise the new issue in the forum and close the issue here, Thanks!

**Comment by spagliarini** [comment] 2021-12-02 00:36
That apple forum didn't help (I already have the latest version of OS). I fairly don't know what to do and was trying to dig in but had to stop for other priorities this week. I will get back to this issue next week.

**Comment by sachinprasadhs** [comment] 2021-12-07 20:03
Let us know if you have any update as per the above comment. Thanks!

**Comment by spagliarini** [comment] 2021-12-16 23:06
The apple forum where they discuss the problem is this: https://developer.apple.com/forums/thread/683780?login=true&page=1#698656022 

But it looks like the problem hasn't been solved yet.

**Comment by jvishnuvardhan** [comment] 2022-01-22 00:09
This is more related to Apple. TF team doesn't have access to that hardware. However, TF Community is trying to build TF for Apple M1 [here](https://github.com/tensorflow/tensorflow/issues/52160). Please follow that thread for more discussion. Thanks!

**Closed** 2022-02-05 01:16 UTC
Labels: stat:awaiting response, type:build/install, stalled, comp:gpu, subtype:macOS, 2.6.0

**Comment by JH-Lam** [comment] 2023-05-31 16:03
hi @ spagliarini , I had this issue too(though it was about "Cannot assign a device for operation ResourceStridedSliceAssign"). did you solve it already?

**Comment by spagliarini** [comment] 2023-06-01 06:39
> hi @ spagliarini , I had this issue too(though it was about "Cannot assign a device for operation ResourceStridedSliceAssign"). did you solve it already?

Honestly, I haven't recently tried again. Sorry not to be helpful with this.

**Comment by JH-Lam** [comment] 2023-06-02 01:54
hi, after I googled some more materials, my code works well. there are a couple steps to address it:
1. uses lower tensorflow-macos 2.9 instead of 2.11 ( tf-metal 0.5 but not 0.7 ). 2.11 is not listed in the official site, maybe it's not tested.
good luck ~
