### ISSUE TITLE
Autograd cannot handle if conditions with line brakes when accessing fields

### ISSUE THREAD

**Issue by MaximusMutschler** [tensorflow/tensorflow#36899] opened 2020-02-19 13:50 UTC
### System information
- custom code:
- Linux Ubuntu 18.04
- TensorFlow installed from binary:
-  tensorflow-gpu 2.1.0:
-  3.6.8:
- cuda 10.0:
- Nvidia Geforce 1080ti 11Gb:

### Describe the problem
BUG: Autograd cannot handle if conditions with line brakes when accessing fields.

### Source code / logs
This works:

import tensorflow as tf
class Test:
    a = tf.Variable(1.0)

    @tf.function
    def test_function(self):
        if False or self.a < 1.0:
            pass
t = Test()
t.test_function()

But this does not:

import tensorflow as tf
class Test:
    a = tf.Variable(1.0)

    @tf.function
    def test_function(self):
        if False or\
                self.a < 1.0:
            pass
t = Test()
t.test_function()

Error Message: 
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by Saduf2019** [comment] 2020-02-20 06:56
@MaximusMutschler I have tried to replicate the code shared by you in our local environment and the error faced is not the same ,please find the [gist](https://colab.sandbox.google.com/gist/Saduf2019/8ac933dbbc61451341ec65164107318c/36899.ipynb) attached.
please share complete code for us to replicate your issue.

**Comment by MaximusMutschler** [comment] 2020-02-20 12:16
@Saduf2019  Just changed the code so that it reproduces the error: see [my_gist](https://colab.research.google.com/gist/MaximusMutschler/9d41805c5bd7cd91a974871e42e08f65/36899.ipynb)
Interestingly the error does not occur when using jupyter notebooks.
But if the code is run directly on the system i can recreate the error in google colab
It works with tf2.0 but fails with tf2.1

**Comment by Saduf2019** [comment] 2020-02-24 08:58
@MaximusMutschler 
Please, go through the below [link](https://github.com/tensorflow/tensorflow/issues/32383) and see if it helps you.Thanks!
#32319

**Comment by MaximusMutschler** [comment] 2020-02-24 16:03
@Saduf2019  thanks!! Unfortunately, the linked thread does not help, they solved their problem by installing gast==0.2.2, which is already installed in my case.

**Comment by zhuzilin** [comment] 2020-03-24 03:13
There is problem with `\` in autograph and I've commited a pr to it #37851

**Comment by jvishnuvardhan** [comment] 2020-03-24 16:55
@MaximusMutschler This was resolved in recent `tf-nightly`. Please check a [similar issue](https://github.com/tensorflow/tensorflow/issues/35765#event-2963029936) that initiated the resolution.  I ran your code with `tf-nightly` and I cannot reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/45dabcc649839fc9d8fbd5a1c87b1a50/36899.ipynb).

Please close the issue if this was resolved for you. Thanks!

**Comment by MaximusMutschler** [comment] 2020-03-25 12:29
@jvishnuvardhan  It works. Thanks a lot!

**Closed** 2020-03-25 12:31 UTC
Labels: TF 2.1, comp:autograph, stat:awaiting response, type:support
