### ISSUE TITLE
ModelCheckpoint does not save the model when `_is_graph_network` is False

### ISSUE THREAD

**Issue by TrentHouliston** [tensorflow/tensorflow#37620] opened 2020-03-16 03:19 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): `tensorflow/tensorflow:2.1.0-gpu-py3`

**Describe the current behavior**
When using tf.keras.callbacks.ModelCheckpoint it implies that when save_weights_only is False it will save the model using model.save, however it does not.
Due to the code in set_model that checks `model._is_graph_network` save_weights_only becomes True for my usecase.
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/callbacks.py#L920-L923

**Describe the expected behavior**
When `save_weights_only=False` the network should be saved using `model.save` instead of `model.save_weights`.
It is not clear to me what the `_is_graph_network` variable is influenced by and how one would make it True. At the very least this is a documentation issue where the documentation implies that settings `save_weights_only` will save the model using `model.save` when this is not true.

Additionally, if I run `model.save` outside of the callback it succeeds, therefore there is no reason why the callback should not be able to do the same.

**Comment by ravikyram** [comment] 2020-03-16 06:10
@TrentHouliston 

Request you to help us with colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-31 01:15
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-31 05:48
@TrentHouliston 

Any update on this issue please. Thanks!

**Comment by TrentHouliston** [comment] 2020-04-03 02:36
Hi @ravikyram, Sorry the covid19 has slowed me down a bit. I'll try to provide a mwe today or tomorrow.

**Comment by TrentHouliston** [comment] 2020-04-15 03:03
Hi @ravikyram 
Here is a mwe that is close to my current usage that shows the issue.
I have two "identical" setups one with a sequential model and one with a custom one.
When the checkpoint is run in the custom one, instead of saving the model (despite the `save_weights_only=False`) it saves weights only. Which is very misleading and also incorrect behaviour.
When I save the model manually it works fine.

The sequential model works as expected.

```python
#!/usr/bin/env python3

import tensorflow as tf
import numpy as np


class TestModel(tf.keras.Model):
    def __init__(self, n_layers, **kwargs):
        super(TestModel, self).__init__(**kwargs)

        self.n_layers = n_layers
        self.map = {}
        for i in range(self.n_layers):
            self.map[str(i)] = tf.keras.layers.Dense(units=1)

    def call(self, X, training=False):

        for i in range(self.n_layers):
            X = self.map[str(i)](X)

        return X


if __name__ == "__main__":
    n_layers = 5

    # Custom model
    custom = TestModel(n_layers)
    custom.compile(optimizer="adam", loss="mse")
    custom.fit(
        x=np.ones((10000), np.float32),
        y=np.ones((10000), np.float32),
        epochs=10,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                filepath="output/custom/callback/model{epoch}", save_weights_only=False,
            )
        ],
    )
    custom.save("output/custom/manual/model")

    # Sequential model
    sequential = tf.keras.Sequential([tf.keras.layers.Dense(units=1) for i in range(n_layers)])
    sequential.compile(optimizer="adam", loss="mse")
    sequential.fit(
        x=np.ones((10000), np.float32),
        y=np.ones((10000), np.float32),
        epochs=10,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                filepath="output/sequential/callback/model{epoch}",
                save_weights_only=False,
            )
        ],
    )
    sequential.save("output/sequential/manual/model")
```

**Comment by ravikyram** [comment] 2020-04-16 11:18
I have tried on colab with TF version 2.1.0, 2.2.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/ae978fd07b63367d1af63d53a4a5a03a/untitled779.ipynb). Thanks!

**Comment by a-ninomiya** [comment] 2021-02-08 13:44
Any updates on this issue?

**Comment by buesma** [comment] 2021-02-18 15:36
While we wait for a fix for this issue, here is a workaround posted by @marwan116 in a #42741:

> my current workaround is to implement my own ModelCheckpoint - that overrides set_model ...
> ```
> class CustomCheckpoint(tf.keras.callbacks.ModelCheckpoint):
>     def set_model(self, model):
>         self.model = model
> ```

**Comment by bhack** [comment] 2021-04-16 14:41
@geetachavan1 As we are on RC1 I don't it could still in https://github.com/orgs/tensorflow/projects/11

**Comment by bhack** [comment] 2021-04-16 14:42
Do you think that we could add a postponed (or something other naming) column?

**Comment by jvishnuvardhan** [comment] 2021-05-25 00:35
@TrentHouliston Looks like this was resolved. I checked with `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/66c2b11e00b205a421fd49057cdd447d/untitled991.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-06-04 01:45
Closing this issue as this was resolved in recent `tf-nightly`. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2021-06-04 01:45 UTC
Labels: TF 2.1, comp:keras, stalled, stat:awaiting response, type:bug

**Comment by Alirezanltv** [comment] 2023-05-02 17:30
import tensorflow as tf
from tensorflow.keras.models import load_model

# # Load the model
model = load_model('model2019_fullHead.h5')
here's the error : ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x7f724affbf10>. what shall I do ?
