### ISSUE TITLE
tf.linalg.solve segfaults on invalid matrix dimensions

### ISSUE THREAD

**Issue by darthdeus** [tensorflow/tensorflow#25391] opened 2019-01-31 15:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6 (17G4015)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-rc2-3-ga6d8ffae09 1.12.0
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Calling `tf.linalg.solve(A, b)` with `b.shape == (n,)` causes a segfault.

**Describe the expected behavior**

Invalid shape error expected. This seems to happen on the GPU version I've tested on another system, but crashes on the CPU version on my Mac.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
tf.enable_eager_execution()
# This is ok
tf.linalg.solve([[.1, .0], [.0, .1]], [[.1], [.1]])
# This line causes segfault
tf.linalg.solve([[.1, .0], [.0, .1]], [.1, .1])
```

**Other info / logs**

Same thing happens on the latest nightly build, that is `b'v1.12.0-6726-g5522d670af' 1.13.0-dev20190126`

**Comment by jvishnuvardhan** [comment] 2019-02-16 00:12
@darthdeus I see the following error in CPU
InvalidArgumentError: All input tensors must have the same rank. [Op:MatrixSolve]

On TF GPU, I see the following error 
ValueError: Shape must be at least rank 2 but is rank 1 for 'MatrixSolve_3' (op: 'MatrixSolve') with input shapes: [2,2], [2].

I think in both the cases it is clearly describing that the error is due to shape or Rank. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-02-22 17:36
Closing due to lack of recent activity and type of issue (not build/install and not bug/performance). Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by NathanWycoff** [comment] 2019-04-01 14:44
I encounter the same issue on TF 1.13.1 on Ubuntu 18.04.2 LTS. Code to reproduce:

> import tensorflow as tf
> import tensorflow_probability as tfp
> import numpy as np
> tf.enable_eager_execution()
> 
> N = 10
> A = tf.Variable(np.random.normal(size=[N,N]))
> b = tf.Variable(np.random.normal(size=[N]))
> tf.linalg.solve(A, b)

This results in a segfault.

Replacing the b assignment with 
> b = tf.Variable(np.random.normal(size=[N,1]))

prevents the issue from occurring.

**Comment by darthdeus** [comment] 2019-04-01 14:54
@jvishnuvardhan It's probably related to a specific version/OS, because in some cases you do get the shape error, but as @NathanWycoff just reporetd, I'm not the only one getting a segfault.

**Comment by jvishnuvardhan** [comment] 2019-04-01 18:47
@darthdeus I agree with you. This could be an issue specific to environment. I am not seeing this segfault error but seeing the following error on Mac with TF1.13.1

ValueError: Shape must be at least rank 2 but is rank 1 for 'MatrixSolve' (op: 'MatrixSolve') with input shapes: [10,10], [10].

I get the following error with google colab with TF1.13.1
InvalidArgumentError: Input and right-hand side must have same rank, got 2 != 1 [Op:MatrixSolve]

We will try to resolve the root cause. Thanks!

**Comment by jacksonloper** [comment] 2019-11-04 19:17
This is still a problem on latest docker image for py3 at least:

**Comment by rmothukuru** [comment] 2021-04-21 11:32
@darthdeus,
I ran your code in `Google Colab` and in `Jupyter Notebook` in `Linux` Machine and I could see the error, 

> InvalidArgumentError: All input tensors must have the same rank. [Op:MatrixSolve] 

Please find the [Gist of the Google Colab](https://colab.research.google.com/gist/rmothukuru/bb4173404c62ce4b3cf5784dc7afb1b4/gh_25391.ipynb). 

Can you please confirm if we can close this issue as the expected Error is being raised? Thanks!

**Closed** 2021-05-05 11:38 UTC
Labels: comp:ops, stalled, stat:awaiting response, type:bug
