### ISSUE TITLE
No op named GatherTree using BeamSearchDecoder

### ISSUE THREAD

**Issue by Michael0134** [tensorflow/tensorflow#12927] opened 2017-09-09 03:33 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.5
- **GPU model and memory**: GeForce GTX 1080 (8 GB)

### Describe the problem
I was implementing a seq2seq model, and inference went well using greedy algorithm(GreedyEmbeddingHelper). But when I tried to use BeamSearchDecoder to infer from a trained model, I encountered "No op named GatherTree in defined operations.". Strangely enough, I couldn't find the same error elsewhere. 

### Error message
```
Traceback (most recent call last):
  File "infer.py", line 88, in <module>
    out_file='result/result.out', checkpoint=checkpoint)
  File "infer.py", line 48, in predict
    loader = tf.train.import_meta_graph(checkpoint + '.meta')
  File "/home/user0/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/home/user0/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/user0/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named GatherTree in defined operations.
```

### Source code to reproduce the problem
```
# Inference module
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
	loader = tf.train.import_meta_graph(checkpoint + '.meta')
	loader.restore(sess, checkpoint)

	input_data = loaded_graph.get_tensor_by_name('inputs:0')
	logits = loaded_graph.get_tensor_by_name('inferences:0')
	src_seq_len = loaded_graph.get_tensor_by_name('source_sequence_length:0')
	tgt_seq_len = loaded_graph.get_tensor_by_name('target_sequence_length:0')

	for i in range(len(text)):
		text_seq = src2seq_word(text[i], True)
		answer = sess.run(logits, {input_data: [text_seq] * batch_size,
			                                  tgt_seq_len: [len(text_seq)] * batch_size,
			                                  src_seq_len: [len(text_seq)] * batch_size}
			                         )[:, :, 0]
```
Program failed at ```loader = tf.train.import_meta_graph(checkpoint + '.meta')```

```
# Related code
training_logits = tf.identity(train_decoder_output.rnn_output, name='logits')
inference_logits = tf.identity(infer_decoder_output.predicted_ids, name='inferences')
```

**Comment by reedwm** [comment] 2017-09-11 17:58
@ebrevdo, any ideas what the problem is?

**Comment by ebrevdo** [comment] 2017-10-12 02:58
Try a newer version of TensorFlow?

**Comment by gamersover** [comment] 2017-10-16 09:39
i have occured the same problem, do you have any ideas about it? or do you solved it? thanks

**Comment by melgor** [comment] 2017-10-19 05:22
I have same problem using TF 1.3 (CPU version). What should we do to use this model for interference?

**Comment by ebrevdo** [comment] 2017-10-21 21:14
Try doing this early on:

from tensorflow.contrib.seq2seq.python.ops import beam_search_ops

I have the feeling that when importing a graphdef that the dynamic loading of the .so with the GatherTree ops hasn't happened.  So adding that import should force the library to load.

**Comment by ebrevdo** [comment] 2017-10-21 21:32
@allenlavoie @sherrym any ideas how to ensure we load the proper dynamic library as part of import meta graph?  Alternatively should we just eagerly import contrib .so's during import tensorflow?

**Comment by allenlavoie** [comment] 2017-10-23 16:58
If we're going to eagerly load the contrib shared objects, we might as well just statically link them into the binary (which I don't have a particular problem with, but may be somewhat contentious). We could also catch op/kernel not found errors in a few places and try again after loading contrib, which might be more palatable.

Longer-term there are hopes of making some sort of repository where sessions can find the kernels (and ops in this case) they need and load them dynamically. @martinwicke would know more about whether it's being worked on.

**Comment by martinwicke** [comment] 2017-10-31 16:22
It's too far out to really reason about. 

We will for now eagerly load all the dlls we find (which are appropriate for the machine architecture we're on, e.g., we may skip the one containing GPU kernels on a machine without GPU, or the one built with AVX512 on a machine without that SIMD instruction set. @gunan FYI.

**Comment by tensorflowbutler** [comment] 2017-12-20 01:09
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:18
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment] 2018-01-12 17:27
I'd like to bring this back to our attention.  As we try to make TF more
modular, including loading of external kernels, this kind of issue will
come up over and over again.  We need a way to describe that a certain
plugin/kernel is needed when loading a metagraph, and at least issuing an
error message like "please import the following python module before
loading the metagraph"; perhaps with a centralized hint table that maps
kernels to c++ library names / python module names.

**Comment by ebrevdo** [comment] 2018-01-12 17:48
+anna

**Comment by martinwicke** [comment] 2018-01-12 18:30
cc/ @gunan 

The plan so far is to make this less terrible by *removing* the need to kernels loaded in python modules, which would address this particular issue. 

But in general, you are correct: We have no mechanism to map a kernel/op name to a package in which is might be defined. This is no different between static or dynamic linking, if you build a static TF with a specific op, and save a Graph and load it on a TF without that Op, things don't work. 

We can (and should) make this better (by namespacing, and probably, the equivalent of a TF package manager), but again, this is some time away -- @gunan has the plan.

**Comment by ebrevdo** [comment] 2018-01-12 19:12
OK; I'll assign to @gunan as he can close it out when the master plan is executed ;)

**Comment by tensorflowbutler** [comment] 2018-01-23 23:19
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment] 2018-02-07 13:49
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-22 13:06
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-09 13:38
Nagging Assignees @allenlavoie, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 03:47
Nagging Assignees @allenlavoie, @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:36
Nagging Assignee @allenlavoie: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Closed** 2018-04-09 03:27 UTC
