### ISSUE TITLE
Enable sparse_matmul(a,b) when a and b are sparse, conformable

### ISSUE THREAD

**Issue by buddha314** [tensorflow/tensorflow#10792] opened 2017-06-17 04:55 UTC
Current tf.sparse_matmul(a,b) requires both a and b to be dense, apparently.

```
n = 500000
k = 5000
with tf.Session() as sess:
    rep = 1.0
    sparse1 = tf.SparseTensor(indices=list(xys),values=np.repeat(rep,k),dense_shape=[n,n])
    sparse2 = tf.SparseTensor(indices=list(xys),values=np.repeat(rep,k),dense_shape=[n,n])
    sparse1 = tf.cast(sparse1, tf.float32)
    sparse2 = tf.cast(sparse2, tf.float32)

    sq = tf.sparse_matmul(
            tf.sparse_tensor_to_dense(sparse1, 0.0)
            , tf.sparse_tensor_to_dense(sparse2, 0.0)
            , a_is_sparse=True
            , b_is_sparse=True
)
```

The cast of `sparse_tensor_to_dense()` seem inappropriate.  Please enable

```
n = 500000
k = 5000
with tf.Session() as sess:
    rep = 1.0
    sparse1 = tf.SparseTensor(indices=list(xys),values=np.repeat(rep,k),dense_shape=[n,n])
    sparse2 = tf.SparseTensor(indices=list(xys),values=np.repeat(rep,k),dense_shape=[n,n])
    sparse1 = tf.cast(sparse1, tf.float32)
    sparse2 = tf.cast(sparse2, tf.float32)

    sq = tf.sparse_matmul(
            sparse1
            , sparse2
            , a_is_sparse=True
            , b_is_sparse=True
)
```

**Comment by lakshayg** [comment] 2017-06-17 09:46
Related issue: https://github.com/tensorflow/tensorflow/issues/10003

**Comment by aselle** [comment] 2017-06-17 19:45
@lakshayg, yes this is a dupe of #10003, closing for now. thanks!

**Closed by aselle** 2017-06-17 19:45 UTC
Labels: type:feature
