### ISSUE TITLE
"TypeError: list indices must be integers or slices, not str" in preempted_hook.py 

### ISSUE THREAD

**Issue by prashastk** [tensorflow/tensorflow#32694] opened 2019-09-20 16:51 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below):1.14
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory: Cloud TPU v2

**Describe the current behavior**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/tpu/preempted_hook.py", line 89, in run
    self._cluster._tpu, response['state'], response['health'])  # pylint: disable=protected-access
TypeError: list indices must be integers or slices, not str
```
Looks like response is a list and not a dictionary.

**Describe the expected behavior**
No exception thrown

**Other info / logs**
N/A

**Comment by oanush** [comment] 2019-09-23 06:25
@prashastk ,
Can you share a simple and standalone code to reproduce the issue?Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-07 12:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by oanush** [comment] 2019-10-14 12:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-10-14 12:30 UTC
Labels: TF 1.14, comp:ops, stat:awaiting response, type:support
