### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tensorflow#28512] opened 2019-05-08 08:19 UTC
Hello, dear guys.

I build the tensorflow(CPU) version in Windows 10.

I install tensorflow-2.0-beta.

I want to run some tensorflow old-version code:
```
#
#  ColorHandPose3DNetwork - Network for estimating 3D Hand Pose from a single RGB Image
#  Copyright (C) 2017  Christian Zimmermann
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from __future__ import print_function, unicode_literals

import tensorflow as tf
import numpy as np
import scipy.misc
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from nets.ColorHandPose3DNetwork import ColorHandPose3DNetwork
from utils.general import detect_keypoints, trafo_coords, plot_hand, plot_hand_3d
import datetime

if __name__ == '__main__':
    # images to be shown
    image_list = list()
    '''
    image_list.append('./data_new/img.png')
    image_list.append('./data_new/img2.png')
    image_list.append('./data_new/img3.png')
    image_list.append('./data_new/img4.png')
    image_list.append('./data_new/img5.png')
    '''
    starttime = datetime.datetime.now()
    image_list.append('./data_new/demo1.jpg')
    # network input
    image_tf = tf.placeholder(tf.float32, shape=(1, 240, 320, 3))
    hand_side_tf = tf.constant([[1.0, 0.0]])  # left hand (true for all samples provided)
    evaluation = tf.placeholder_with_default(True, shape=())

    # build network
    net = ColorHandPose3DNetwork()
    hand_scoremap_tf, image_crop_tf, scale_tf, center_tf,\
    keypoints_scoremap_tf, keypoint_coord3d_tf = net.inference(image_tf, hand_side_tf, evaluation)

    # Start TF
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8)
    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

    # initialize network
    net.init(sess)

    # Feed image list through network
    for img_name in image_list:
        starttime = datetime.datetime.now()
        image_raw = scipy.misc.imread(img_name)
        image_raw = scipy.misc.imresize(image_raw, (240, 320))
        image_v = np.expand_dims((image_raw.astype('float') / 255.0) - 0.5, 0)

        hand_scoremap_v, image_crop_v, scale_v, center_v,\
        keypoints_scoremap_v, keypoint_coord3d_v = sess.run([hand_scoremap_tf, image_crop_tf, scale_tf, center_tf,
                                                             keypoints_scoremap_tf, keypoint_coord3d_tf],
                                                            feed_dict={image_tf: image_v})

        hand_scoremap_v = np.squeeze(hand_scoremap_v)
        image_crop_v = np.squeeze(image_crop_v)
        keypoints_scoremap_v = np.squeeze(keypoints_scoremap_v)
        keypoint_coord3d_v = np.squeeze(keypoint_coord3d_v)

        # post processing
        image_crop_v = ((image_crop_v + 0.5) * 255).astype('uint8')
        coord_hw_crop = detect_keypoints(np.squeeze(keypoints_scoremap_v))
        coord_hw = trafo_coords(coord_hw_crop, center_v, scale_v, 256)

        # visualize
        fig = plt.figure(1)
        ax1 = fig.add_subplot(221)
        ax2 = fig.add_subplot(222)
        ax3 = fig.add_subplot(223)
        ax4 = fig.add_subplot(224, projection='3d')
        ax1.imshow(image_raw)
        plot_hand(coord_hw, ax1)
        ax2.imshow(image_crop_v)
        plot_hand(coord_hw_crop, ax2)
        ax3.imshow(np.argmax(hand_scoremap_v, 2))
        plot_hand_3d(keypoint_coord3d_v, ax4)
        ax4.view_init(azim=-90.0, elev=-90.0)  # aligns the 3d coord with the camera view
        ax4.set_xlim([-3, 3])
        ax4.set_ylim([-3, 1])
        ax4.set_zlim([-3, 3])
        endtime2 = datetime.datetime.now()
        print(endtime2-starttime)
        plt.show()

```

However, it reports the error:

> Traceback (most recent call last):
>   File "run.py", line 43, in <module>
>     image_tf = tf.placeholder(tf.float32, shape=(1, 240, 320, 3))
> AttributeError: module 'tensorflow' has no attribute 'placeholder'

I wonder how can I  make my old code compatible with new version software?

Thanks & Regards!

**Comment by wdirons** [comment] 2019-05-08 18:42
try running the `tf_upgrade_v2` script against the code to see what changes it suggest.

**Comment by momo1986** [comment] 2019-05-09 05:57
Hello, @wdirons , William.

Thanks for your reply.

However, when I run the script, some problems happen.

> Traceback (most recent call last):
>   File "c:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python\Python37\Scripts\tf_upgrade_v2.exe\__main__.py", line 9, in <module>
>   File "c:\python\python37\lib\site-packages\tensorflow\tools\compatibility\tf_upgrade_v2_main.py", line 123, in main
>     args.input_tree, output_tree, args.copy_other_files)
>   File "c:\python\python37\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 624, in process_tree
>     _, l_report, l_errors = self.process_file(input_path, output_path)
>   File "c:\python\python37\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 494, in process_file
>     temp_file)
>   File "c:\python\python37\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 546, in process_opened_file
>     lines = in_file.readlines()
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 2352: illegal multibyte sequence

I am not sure what type of language features in my old code will cause the error-report? How can I fix the problem?
Thanks & Regards!

**Comment by achandraa** [comment] 2019-05-09 11:06
@momo1986 : Did you get chance to have a look on this [link](https://www.tensorflow.org/alpha/guide/migration_guide). Let us know if that helps. Thanks!

**Comment by achandraa** [comment] 2019-05-14 09:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-05-14 09:21 UTC
Labels: 2.0, comp:ops, stat:awaiting response, type:support

**Comment by acollins1331** [comment] 2019-08-02 15:18
Just wanted to leave a comment on this, that with the new 2.0 API, this can be caused by using a separate installation of keras than the one included in tf 2.0. Check and make sure your backend is not coming from import Keras but is coming from tf.keras.backend, solved it for me.

**Comment by kbronik2017** [comment] 2019-11-26 15:42
First, Try to uninstall any previous  Keras version and install Keras==2.3.1 using: 
pip install git+git://github.com/keras-team/keras.git

**Comment by rs777795** [comment] 2020-04-23 17:54
i am using windows 10
tensorflow version 2.0

from data_prepare import gen_vocab
from data_prepare import gen_id_seqs
from RNNLM import RNNLM
import os
# It seems that there are some little bugs in tensorflow 1.4.1.
# You can find more details in
# https://github.com/tensorflow/tensorflow/issues/12414
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf

# Set TRAIN to true will build a new model
TRAIN = True

# If VERBOSE is true, then print the ppl of every sequence when we
# are testing.
VERBOSE = True

# To indicate your test corpus
test_file = "./gap_filling_exercise/gap_filling_exercise"

if not os.path.isfile("data/vocab"):
    gen_vocab("ptb/train")
if not os.path.isfile("data/train.ids"):
    gen_id_seqs("ptb/train")
    gen_id_seqs("ptb/valid")

with open("data/train.ids") as fp:
    num_train_samples = len(fp.readlines())
with open("data/valid.ids") as fp:
    num_valid_samples = len(fp.readlines())

with open("data/vocab") as vocab:
    vocab_size = len(vocab.readlines())

def create_model(sess):
    model = RNNLM(vocab_size=vocab_size,
                  batch_size=64,
                  num_epochs=80,
                  check_point_step=100,
                  num_train_samples=num_train_samples,
                  num_valid_samples=num_valid_samples,
                  num_layers=2,
                  num_hidden_units=600,
                  initial_learning_rate=1.0,
                  final_learning_rate=0.0005,
                  max_gradient_norm=5.0, 
                  )
    sess.run(tf.compat.v1.global_variables_initializer())
    return model

if TRAIN:
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.35)
    with tf.session() as sess:
        model = create_model(sess)

        saver = tf.train.Saver()

        model.batch_train(sess, saver)

tf.compat.v1.reset_default_graph()
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.35)
with tf.compat.v1.Session() as sess:
    model = create_model(sess)
    saver = tf.compat.v1.train.Saver()
    saver.restore(sess, "model/best_model.ckpt")
    predict_id_file = os.path.join("data", test_file.split("/")[-1]+".ids")
    if not os.path.isfile(predict_id_file):
        gen_id_seqs(test_file)
    model.predict(sess, predict_id_file, test_file, verbose=VERBOSE)

and my error is:
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.35)
AttributeError: module 'tensorflow' has no attribute 'GPUOptions'

**Comment by rs777795** [comment] 2020-04-23 17:55
kindly help me with the above error

**Comment by kbronik2017** [comment] 2020-04-24 14:55
try this:
import keras.backend as K
gpu_options=K. tf.GPUOptions(per_process_gpu_memory_fraction=0.35)
