### ISSUE TITLE
 cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by ljafari** [tensorflow/tensorflow#37978] opened 2020-03-27 15:59 UTC
I installed Anaconda 2020(64 bit) after uninstalling every installation and files related to python before that and then used these instructions:
conda install tensorflow
conda install tensorflow-gpu
now I have 
cudatoolkit               10.0.130                      0
cudnn                     7.6.5                cuda10.0_0
 and NVIDIA Graphics Driver 388.73

Then I run these instructions in spyder:

checkpointer = ModelCheckpoint(filepath='/tmp/checkpoint.h5', verbose=1, save_best_only=True)
class_weights = {0:1, 1:1, 2:1, 3:1}
fittedModel = model.fit(X_train, Y_train, batch_size = 16, epochs = 10, 
                        verbose = 1, validation_data=(X_validate, Y_validate),
                        callbacks=[checkpointer], class_weight = class_weights)
 
and I have this error:
Train on 144 samples, validate on 72 samples
Traceback (most recent call last):

  File "<ipython-input-2-4eb902219300>", line 3, in <module>
    callbacks=[checkpointer],class_weight = class_weights)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 780, in fit
    steps_name='steps_per_epoch')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 250, in model_iteration
    model.reset_metrics()

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1084, in reset_metrics
    m.reset_states()

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py", line 199, in reset_states
    K.batch_set_value([(v, 0) for v in self.variables])

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3071, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 459, in get_session
    session = _get_session(op_input_list)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 431, in _get_session
    config=get_default_session_config())

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)

InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

 what should I do?
Please help me. thanks

**Comment by ljafari** [comment] 2020-03-29 07:26
please help

**Comment by ljafari** [comment] 2020-03-29 07:27
please help

**Comment by amahendrakar** [comment] 2020-03-30 13:59
@ljafari,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment] 2020-04-07 13:32
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-14 16:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-14 16:38 UTC
Labels: stat:awaiting response, type:others
