### ISSUE TITLE
DataType error: DataType 6 is not recognized in Java (version 2.4.0)

### ISSUE THREAD

**Issue by ambujbansal** [tensorflow/tensorflow#41212] opened 2020-07-08 21:16 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: custom
- TensorFlow installed from (source or binary):org.tensorflow:tensorflow-lite:0.0.0-nightly
- TensorFlow version (use command below):version 2.4.0
- Python version:
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source): Android SDK Java API 28
- CUDA/cuDNN version: N/A - CPU
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Loaded a TTS mel generator tflite model in java on the android target.
runForMultipleInputsOutputs function. The model takes 4 tensors as input with INT32 (1, 1), BOOL(1,1), INT32 and Float. 
Trying to print and feed input tensors with type boolean and dynamic size, however, it is crashing in printing and also later in 
It is printing first input tensor details, however crashes while printing the seconds tensor details
 
D/SnsTTS: input tensors count: 4
D/SnsTTS: tensor[0] Shape: [1, 1] data type: INT32
java.lang.IllegalArgumentException: DataType error: DataType 6 is not recognized in Java (version 2.4.0)
        at org.tensorflow.lite.DataType.fromC(DataType.java:79)
        at org.tensorflow.lite.Tensor.<init>(Tensor.java:484)
        at org.tensorflow.lite.Tensor.fromIndex(Tensor.java:44)
        at org.tensorflow.lite.NativeInterpreterWrapper.getInputTensor(NativeInterpreterWrapper.java:303)
        at org.tensorflow.lite.Interpreter.getInputTensor(Interpreter.java:423)

**Describe the expected behavior**
It should print the input tensor details, for boolean type and also accept it in the run function in java

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

private void printTensor(Tensor tensor, int index){
        int[] shape = tensor.shape();
        DataType dataType = tensor.dataType();
        Log.d(Tag, "tensor[" + index + "] Shape: " + Arrays.toString(shape) + " data type: " + dataType.toString());
    }

    private void printInterpreterDetails(Interpreter interpreter){

        int inputTensorCount = interpreter.getInputTensorCount();
        Log.d(Tag, String.format("input tensors count: %d", inputTensorCount));
        for (int inputTensorIndex =0; inputTensorIndex<inputTensorCount; inputTensorIndex++) {
            printTensor(interpreter.getInputTensor(inputTensorIndex), inputTensorIndex);
        }
}

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here is the link to python implementation
https://github.com/TensorSpeech/TensorflowTTS

**Comment by abattery** [comment] 2020-07-08 22:37
Java API's DataType enum should be updated. Team will work on this.

**Comment by thaink** [comment] 2020-07-09 00:16
Hi @ambujbansal Can you uploaded the model here so I can reproduce it quicker?

**Comment by ambujbansal** [comment] 2020-07-09 00:23
[fastspeech_quant.zip](https://github.com/tensorflow/tensorflow/files/4893822/fastspeech_quant.zip)
```
private Interpreter loadModel(String modelpath){
        try {
            FileInputStream inputStream = new FileInputStream(modelpath);
            FileChannel fileChannel = inputStream.getChannel();
            MappedByteBuffer tfliteModel = fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, fileChannel.size());

            Interpreter.Options tfliteOptions = new Interpreter.Options();
            tfliteOptions.setNumThreads(1);
            Interpreter interpreter = new Interpreter(tfliteModel, tfliteOptions);
            return interpreter;
        } catch (Exception e) {
            Log.e(Tag, "Error loading model", e);
        }
        return null;
    }
```

**Comment by thaink** [comment] 2020-07-24 06:45
It is supported at the master head.
Could you give it a try.

**Comment by thaink** [comment] 2020-07-28 07:33
A fix is submitted at commit 11d919f0a51aeb835230dc3a0a36df10346eb493

**Comment by AR-fan** [comment] 2020-12-12 14:39
i meet the same problem:  
model output: 
```  
output = tf.cast(output, tf.bool)
```  


produce the error in Android Studio
```  
E/libc: Access denied finding property "ro.hardware.chipname"
E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo_mobilenet2unet_KrzysztofV_9, PID: 6336
    java.lang.IllegalArgumentException: DataType error: DataType 6 is not recognized in Java (version 2.4.0)
        at org.tensorflow.lite.DataType.fromC(DataType.java:79)
        at org.tensorflow.lite.Tensor.<init>(Tensor.java:484)
        at org.tensorflow.lite.Tensor.fromIndex(Tensor.java:44)
        at org.tensorflow.lite.NativeInterpreterWrapper.getOutputTensor(NativeInterpreterWrapper.java:326)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:170)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:304)
        at com.example.android.mobilenet2unet_KrzysztofV_9.ImageSegmentorFloatMobileUnet.runInference(ImageSegmentorFloatMobileUnet.java:148)
        at com.example.android.mobilenet2unet_KrzysztofV_9.ImageSegmentor.segmentFrame(ImageSegmentor.java:134)
        at com.example.android.mobilenet2unet_KrzysztofV_9.Camera2BasicFragment.segmentFrame(Camera2BasicFragment.java:1060)
        at com.example.android.mobilenet2unet_KrzysztofV_9.Camera2BasicFragment.access$1100(Camera2BasicFragment.java:103)
        at com.example.android.mobilenet2unet_KrzysztofV_9.Camera2BasicFragment$11.run(Camera2BasicFragment.java:943)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by thaink** [comment] 2020-12-14 01:37
@AR-fan Can you specify the exact version of TFLite you are using?
If you are using nightly, what exact date is that nightly version? Otherwise, what is used in your gradle file?

**Comment by micosacak** [comment] 2021-03-20 02:17
@thaink I also have the sane problem with tensorflow.

Exception in thread "main" java.lang.IllegalArgumentException: DataType 20 is not recognized in Java (version 1.15.0)
	at org.tensorflow.DataType.fromC(DataType.java:85)
	at org.tensorflow.Tensor.fromHandle(Tensor.java:540)
	at org.tensorflow.Session$Runner.runHelper(Session.java:343)
	at org.tensorflow.Session$Runner.run(Session.java:276)
	at tftest3.main(tftest3.java:46)

it has similar issue with tensflor-lite as well [#1079](https://github.com/xamarin/XamarinComponents/issues/1079)

**Comment by micosacak** [comment] 2021-03-20 03:49
[ReportProblem.zip](https://github.com/tensorflow/tensorflow/files/6174838/ReportProblem.zip)
Here, I create the model by runing "runMe.py" in "CreateModelWithPythonTensorflow" and saved the model in "model".
The maven project is given. I get the same problem. I added all files that may help to solve this issue.

Here is the output if you run the Java project:

`test_images\test_00001.png
28-28
1
4
inputTensor is: FLOAT tensor with shape [1, 28, 28, 1]
FLOAT

1.15.0
2021-03-20 03:47:26.040919: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: CreateModelWithPythonTensorflow/model
2021-03-20 03:47:26.042983: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2021-03-20 03:47:26.046158: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-03-20 03:47:26.058207: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2021-03-20 03:47:26.091805: I tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle at path: CreateModelWithPythonTensorflow/model
2021-03-20 03:47:26.099182: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 58246 microseconds.
predicting...

Exception in thread "main" java.lang.IllegalArgumentException: DataType 20 is not recognized in Java (version 1.15.0)
	at org.tensorflow.DataType.fromC(DataType.java:85)
	at org.tensorflow.Tensor.fromHandle(Tensor.java:540)
	at org.tensorflow.Session$Runner.runHelper(Session.java:343)
	at org.tensorflow.Session$Runner.run(Session.java:276)
	at TfDataTypeIssue.main(TfDataTypeIssue.java:43)
`

**Comment by abattery** [comment] 2021-03-20 07:43
@micosacak TF 1.15 version is too old to be supported. Could you try upgrading your code to the recent TF version?

**Comment by micosacak** [comment] 2021-03-20 17:33
I use tensorflow 2.2. in Python. In java, the latest version is 1.15.

**Comment by abattery** [comment] 2021-03-20 22:07
@micosacak could you file a separate issue? The original case is for the TensorFlow Lite library while your case is about TensorFlow java API. They are different and it would be better to address them separately.

**Comment by sushreebarsa** [comment] 2021-08-03 17:12
@ambujbansal It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.3
