### ISSUE TITLE
Weird Bug in Tf.keras.Model.Predict(x=tf.Dataset iterator)

### ISSUE THREAD

**Issue by Abhijit-2592** [tensorflow/tensorflow#23702] opened 2018-11-13 06:29 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.9.0 and 1.12.0 (I am using 1.9.0 but the bug is present in 1.12.0 also)
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:M60 16 GB (two 8GB GPUs)

**Describe the current behavior**
when using tf.data.Dataset.Iterator in tf.keras.Model.predict(x=tf.data.Dataset.Iterator, steps). I am getting a weird value error:

> Please provide data as a list or tuple of 2 elements  - input and target pair. Received Tensor("IteratorGetNext:0", dtype=int64)

The above error is misleading. why does it need (X,Y) for prediction?

My Testing tf.Dataset iterator obviously does not give a (X,Y) tuple. It gives only X in batches. When I give a numpy array of X as input it works as intended. If I use the dataset iterator with **eager_execution** enabled: I get this error (my batch size is 2):

> Please provide data as a list or tuple of 2 elements  - input and target pair. Received tf.Tensor(
> [[     68       5     521 ...       0       0       0]
>  [   6705 1235757    2411 ...    2804     147      13]], shape=(2, 5000), dtype=int64). We do not use the `target` value here. 

Which makes it clear that when eager execution is enabled, Y is not used.

Moreover, why does tf.Dataset iterator need to output a tuple of (X,Y) ? when using tf.keras.Model.predict() ? Is this the expected behaviour?

NOTE: My model is a single input model not a multi input model

EDIT:
I worked around the error by providing (X,Y), But the keras progress bar doesn't seem to work with it.

**Comment by Abhijit-2592** [comment] 2018-11-14 04:04
@wt-huang were you able to reproduce this issue? Or am I missing something?

**Comment by wt-huang** [comment] 2018-11-17 03:01
@Abhijit-2592 You should be able to feed inputs to model.predict() method without getting any errors. 

Make sure your model is instantiated properly and invoke model.fit() to feed inputs and outputs. You can find more details on [Keras Documentation](https://keras.io).  

You can also post your code snippet here.

**Comment by Abhijit-2592** [comment] 2018-11-17 04:03
@wt-huang I am able to use model.fit() there isn't any issue there. But the problem is model.predict() requires (X,Y) When I am passing a tf.dataset.iterator But if I pass a numpy it takes only X and works as intended.

**Comment by tensorflowbutler** [comment] 2018-12-01 18:44
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by XYudong** [comment] 2019-01-21 17:30
> @wt-huang I am able to use model.fit() there isn't any issue there. But the problem is model.predict() requires (X,Y) When I am passing a tf.dataset.iterator But if I pass a numpy it takes only X and works as intended.

What if numpy X is too large to fit in memory when I call mode.predict()? I am trying to use tf.dataset to batch it. BUt it requires (X, Y)...

**Comment by Abhijit-2592** [comment] 2019-01-22 04:50
@XYudong exactly the same issue

**Comment by jvishnuvardhan** [comment] 2019-02-09 01:00
@Abhijit-2592 and @XYudong Is this still an issue? Could you try loading newer TF version and check it? Please let me know the progress. Thanks!

**Comment by Abhijit-2592** [comment] 2019-02-09 02:42
@jvishnuvardhan , I checked on Tensorflow 1.12.0 (pip released on 6th Nov 2018) and the bug still exists. You want me to check on the 1.13.0rc1 version? which was released on 8th Feb 2019?

**Comment by jvishnuvardhan** [comment] 2019-02-11 18:49
@Abhijit-2592 Yes. It would be great if you can check with the 1.13.0rc1 version. Thanks!

**Comment by mrry** [comment] 2019-02-11 19:06
@Abhijit-2592 If this still fails with 1.13.0rc1, please share a code snippet that reproduces the problem so that we can investigate further.

**Comment by Abhijit-2592** [comment] 2019-02-14 07:31
@mrry  and @jvishnuvardhan. Thanks! This appears to be **fixed** in 

`tf-nightly-1.13.0-dev20190213.`

The following code snippet threw the error I mentioned when running with <=1.12.0 (stable version)
```python
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_test = x_test.reshape((10000,28,28,1))
y_test = tf.keras.utils.to_categorical(y=y_test)
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(8, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(10, activation='softmax'))
dataset = tf.data.Dataset.from_tensor_slices((x_test)) # I need to provide y_test also until version 1.12.0
dataset = dataset.batch(batch_size=10)
data = dataset.make_one_shot_iterator()
output = model.predict(x=data,steps=1000,verbose=True)
```
**This runs as intended in nightly version for both normal and eager mode**. 

One more thing which I really liked was, It doesn't look like I need to create a `one_shot_iterator` or `initializable_iterator`.  I can directly pass the `dataset object` to `model.predict` which feels more natural :+1: . Before, while using `tf.data` with Embedding layers, I had to write a few boilerplate code to initialize lookup tables:

```python
train_iterator = train_data.make_initializable_iterator()
valid_iterator = valid_data.make_initializable_iterator()

# initialize tables and iterators using sess from tf.keras
init_sess = tf.keras.backend.get_session()
init_sess.run(train_iterator.initializer)
init_sess.run(valid_iterator.initializer)
init_sess.run(tf.tables_initializer())
```
My question is do I need to run this boilerplate code in upcoming versions of tensorflow?

**Comment by lnshi** [comment] 2019-07-05 10:28
i guess i am encountering this error in `tensorflow==1.14.0`, the `model.fit` is finished successfully with tf.data.Dataset input, but the `model.predict` keep giving error:
```
ValueError: Please provide model inputs as a list or tuple of 2 or 3 elements: (input, target) or (input, target, sample_weights) Received (<tf.Tensor 'IteratorGetNext_1:0' shape=(224, 224, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext_1:1' shape=(224, 224, 3) dtype=float32>)
```
 when i construct the dataset with X only, looks it is expecting Y also?

**Comment by samra-irshad** [comment] 2019-08-18 10:54
I am having the same issue with tensorflow version==1.12.0. Any solution?

**Comment by jvishnuvardhan** [comment] 2019-08-19 21:53
@lnshi @samra-irshad I don't see any issues with TF1.14.0 which is also a stable version or you could try with tf-nightly also. With recent versions, you need to pass `dataset` and not `dataset iterator`. Please check the code below. Please let us know whether it was resolved for you. Thanks!

```
!pip install tensorflow==1.14.0
import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_test = x_test.reshape((10000,28,28,1))
y_test = tf.keras.utils.to_categorical(y=y_test)
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(8, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(10, activation='softmax'))
dataset = tf.data.Dataset.from_tensor_slices((x_test)) # I need to provide y_test also until version 1.12.0
dataset = dataset.batch(batch_size=10)
data = dataset.make_one_shot_iterator()
output = model.predict(x=dataset,steps=1000,verbose=True)
```

**Comment by samra-irshad** [comment] 2019-08-19 23:25
> @lnshi @samra-irshad I don't see any issues with TF1.14.0 which is also a stable version or you could try with tf-nightly also. With recent versions, you need to pass `dataset` and not `dataset iterator`. Please check the code below. Please let us know whether it was resolved for you. Thanks!
> 
> ```
> !pip install tensorflow==1.14.0
> import tensorflow as tf
> 
> (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
> x_test = x_test.reshape((10000,28,28,1))
> y_test = tf.keras.utils.to_categorical(y=y_test)
> model = tf.keras.models.Sequential()
> model.add(tf.keras.layers.Conv2D(8, kernel_size=3, activation='relu', input_shape=(28,28,1)))
> model.add(tf.keras.layers.Flatten())
> model.add(tf.keras.layers.Dense(10, activation='softmax'))
> dataset = tf.data.Dataset.from_tensor_slices((x_test)) # I need to provide y_test also until version 1.12.0
> dataset = dataset.batch(batch_size=10)
> data = dataset.make_one_shot_iterator()
> output = model.predict(x=dataset,steps=1000,verbose=True)
> ```

@jvishnuvardhan I was able to resolve this issue. I have tensorflow version 1.12.0. The predict function demands target labels in tensorflow version 1.12.0 where logically it should not. Anyhow I provided the targets (since it does not use them, so I guess it should not matter whether I provide it the labels or not)

**Comment by jvishnuvardhan** [comment] 2019-08-20 16:53
@samra-irshad Got it. There were lot of modifications and improvements between TF1.12.0 and current version. I would suggest you to upgrade to TF1.14.0 which is also a stable version. If you are familiar with TF2.0, then it is better to upgrade to TF2.0. Thanks.

Automatically closing this out since I understand it to be resolved in TF1.14.0, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-08-20 16:53 UTC
Labels: comp:apis, comp:keras, type:bug
