### ISSUE TITLE
image classifier error

### ISSUE THREAD

**Issue by anujchampjain** [tensorflow/tensorflow#12815] opened 2017-09-05 07:19 UTC
Source : [tensorflow for poets](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4)

```
Anujs-iMac:tensorflow-for-poets-2 anujchampjain$ python -m scripts.label_image     --graph=tf_files/retrained_graph.pb      --image=tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg
2017-09-05 12:48:36.936100: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 12:48:36.936140: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 12:48:36.936144: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-05 12:48:36.936148: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/Users/anujchampjain/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/anujchampjain/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anujchampjain/Desktop/Workspace/Tensorflow/tensorflow-for-poets-2/scripts/label_image.py", line 120, in <module>
    input_operation = graph.get_operation_by_name(input_name);
  File "/Users/anujchampjain/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2836, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/Users/anujchampjain/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/anujchampjain/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2768, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/input' refers to an Operation not in the graph."
```

**Comment by prashanthsun9** [comment] 2017-09-06 05:06
Is there no solution for this issue I am getting the same error and I am stuck, 
knock knock anybody there? need help!!!

**Comment by drpngx** [comment] 2017-09-07 01:04
@petewarden any clue?

**Comment by prashanthsun9** [comment] 2017-09-07 12:53
I found the solution it is this, 

change height to 299 as shown below and input layer to Mul and it will work........:)
  input_height = 299
  input_width = 299
input_layer = "Mul"

**Comment by quaeler** [comment] 2017-09-07 17:32
Seems like a duplicate of https://github.com/tensorflow/tensorflow/issues/12736

**Comment by drpngx** [comment] 2017-09-07 18:58
Closing in favor of other bug. Thanks @quaeler !

**Closed by drpngx** 2017-09-07 18:58 UTC

**Comment by RenanRosa** [comment] 2017-10-09 19:10
Thanks for the solution @prashanthsun9 !
