### ISSUE TITLE
ValueError: trainable_variables cannot be None. Given None

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/tensorflow#38476] opened 2020-04-12 17:05 UTC
when i use model_fn and tf2.1，
my_head = tf.estimator.BinaryClassHead()
  return my_head.EstimatorSpec(
      features=features,
      mode=mode,
      labels=labels,
      optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
      logits=logits)

i get: 
File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 278, in create_estimator_spec
    regularization_losses=regularization_losses))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/head/binary_class_head.py", line 513, in _create_tpu_estimator_spec
    loss_reduction=self._loss_reduction)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 870, in create_estimator_spec_train_op
    validate_trainable_variables(trainable_variables)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/head/base_head.py", line 636, in validate_trainable_variables
    trainable_variables))
ValueError: trainable_variables cannot be None. Given None

**Comment by saikumarchalla** [comment] 2020-04-13 10:08
@Jasperty In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by saikumarchalla** [comment] 2020-04-20 12:16
@Jasperty Any updates regarding this issue? Thanks!

**Comment by saikumarchalla** [comment] 2020-04-27 04:47
@Jasperty  Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2020-04-27 04:47 UTC
Labels: TF 2.1, stat:awaiting response, type:build/install
