### ISSUE TITLE
tf.contrib.memory_stats.MaxBytesInUse() got `Op type not registered 'MaxBytesInUse' in binary running` error

### ISSUE THREAD

**Issue by germunwang** [tensorflow/tensorflow#15412] opened 2017-12-16 02:42 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Should be Yes, as subtitle Source code below.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 7 x64
- **TensorFlow installed from (source or binary)**:
`pip install tensorflow-gpu` with Anaconda on windows prompt following the tensorflow official tutorial
- **TensorFlow version (use command below)**:
tensorflow-gpu 1.4.0
- **Python version**: 
3.6, Anaconda
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
8.0/6.0
- **GPU model and memory**:
GTX 1080TI
- **Exact command to reproduce**:
a simply `python code.py` or following source in python

### Describe the problem
The GPU training is all fine on my placement. 
But when I wanna track the memory usage I got the error using MaxBytesInUse(),
the problem is not solved even I upgrade TF from 1.3 to 1.4.
And of course the same error using BytesInUse().

Is any solution or is the possibility that the method not support for Win7? Thanks.

### Source code / logs
The Op created failed even the simple code execute as follow, when I run MaxBytesInUse() to get a tensor to `a` then it failed.

```
import tensorflow as tf
a = tf.contrib.memory_stats.MaxBytesInUse()
```
And got the message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\contrib\memory_stats\python\ops\memory_stats_ops.py", line 41, in MaxBytesInUse
    return gen_memory_stats_ops.max_bytes_in_use()
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\contrib\memory_stats\ops\gen_memory_stats_ops.py", line 88, in max_bytes_in_use
    "MaxBytesInUse", name=name)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Users\my\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'MaxBytesInUse' in binary running on MY-PC. Make sure the Op and Kernel are registered in the binary running in this process.
```

**Comment by tensorflowbutler** [comment] 2017-12-16 13:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow installed from
Bazel version
Exact command to reproduce

**Comment by germunwang** [comment] 2017-12-16 13:48
Yup I have leave them some as N/A and now I have updated them more in detail. In addition, the package version should be `tensorflow-gpu` 1.4.0. Thanks.

**Comment by qmick** [comment] 2017-12-19 04:53
This op (and some other ops under `tf.contrib`) is not supported under windows cmake build yet. Unfortunately, there is no simple work around. But if you are able to build tensorflow from source, you can add command to `tf_python.cmake` for `tf.contrib.memory_stats` like this (as https://github.com/tensorflow/models/issues/2511#issuecomment-335279353 suggests):
https://github.com/tensorflow/tensorflow/blob/e210cb140a60a74d5e9ce3bf9ebedb21b4910f1c/tensorflow/contrib/cmake/tf_python.cmake#L604-L640
Then rebuild it may work.

**Comment by germunwang** [comment] 2017-12-21 21:47
OK I see, thanks for your replying.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:07
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by Overdrivr** [comment] 2018-01-12 11:44
Any plans to fix the build for this ?

**Comment by qmick** [comment] 2018-01-12 13:33
@Overdrivr As far as I know, the answer is no. @shivaniag Maybe we can mark it as contribution welcome?

**Comment by tensorflowbutler** [comment] 2018-01-23 22:53
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by wujingyue** [comment] 2018-02-02 22:13
@drpngx After reading the thread, I guess the right fix is to add something similar to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_python.cmake#L627-L663 for memory_stats. However, I don't have a Windows machine, so I won't be able to verify my fix. Any ideas?

**Comment by drpngx** [comment] 2018-02-02 22:22
Can this be written as a test? If so, it's great because we can check moving forward and also it will run on windows as part of our battery of tests.

**Comment by tensorflowbutler** [comment] 2018-02-17 13:30
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-04 13:04
Nagging Assignee @wujingyue: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-19 15:10
Nagging Assignee @wujingyue: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-04 00:38
Nagging Assignee @wujingyue: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-18 12:35
Nagging Assignee @wujingyue: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 02:58
Nagging Assignee @wujingyue: It has been 112 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:47
Nagging Assignee @wujingyue: It has been 127 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:11
Nagging Assignee @wujingyue: It has been 142 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:03
Nagging Assignee @wujingyue: It has been 157 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:58
Nagging Assignee @wujingyue: It has been 172 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:02
Nagging Assignee @wujingyue: It has been 187 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:44
Nagging Assignee @wujingyue: It has been 202 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:38
Nagging Assignee @wujingyue: It has been 217 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:45
Nagging Assignee @wujingyue: It has been 232 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:44
Nagging Assignee @wujingyue: It has been 247 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:47
Nagging Assignee @wujingyue: It has been 262 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:08
Nagging Assignee @wujingyue: It has been 277 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:43
Nagging Assignee @wujingyue: It has been 292 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2019-08-06 22:11
Closing due to staleness. Please check with the latest version of TensorFlow. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-08-06 22:11 UTC

**Comment by patrickvonplaten** [comment] 2020-06-11 18:58
How is it possible to use `tf.contrib.memory_stats.MaxBytesInUse()` in TF 2.0+ ?

**Comment by Wasiiiii** [comment] 2020-06-15 00:55
I use custom dateset while using code of stylegan. when it building tensorflow graph the following error will come: ValueError: Op type not registered 'MaxBytesInUse' in binary running on DESKTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. while building NodeDef 'MaxBytesInUse'

**Comment by Wasiiiii** [comment] 2020-06-15 00:56
i also use differernt version of tensorflow but same result
Anyone here who fix this issue

**Comment by chandragupta0001** [comment] 2021-06-03 08:49
in stylgan repo, itst recommended to use TensorFlow 1.10.0 which led to the "MaxByteinUse" error, 
changing to'tensorflow-gpu==1.11.0' worked for me
