### ISSUE TITLE
Noisy loss in distributed training

### ISSUE THREAD

**Issue by shahriar49** [tensorflow/tensorflow#32787] opened 2019-09-24 19:05 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12 & 1.13
- Python version: 3.6.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am working on distributed learning in tensorflow through estimators API using below simple code template:

```
runConfig = tf.estimator.RunConfig(session_config=config, 
                                model_dir=log_dir,
                                save_summary_steps=1,
                                save_checkpoints_steps=train_steps)
estimator = tf.keras.estimator.model_to_estimator(model, model_dir=log_dir, config=runConfig) 
train_spec = tf.estimator.TrainSpec(input_fn=lambda: read_dataset(...), max_steps=...) 
eval_spec = tf.estimator.EvalSpec(input_fn=lambda: read_dataset(...), start_delay_secs=1,
                                throttle_secs=1, steps=None) 
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

My model is defined as a simple 2-layer LSTM model in keras, and read_dataset() functions return datasets that I use for training and validation purposes.  The training/validation data files  and model directory are set in a shared place available to all workers. The whole code is exactly the same for servers (ps, chief, and worker) except the task setting in TF_CONFIG.
When I train model in single-worker configuration, the loss graph I see in tensorboard is gradually downward and reasonable.

![single](https://user-images.githubusercontent.com/17579773/65541564-975a6a80-dedb-11e9-9a56-f77d2b5906a8.jpg)

When using two machines of one chief and one worker, the total run time is less (as expected) but the loss graph is very noisy and higher than single-server case.

![double](https://user-images.githubusercontent.com/17579773/65541692-d092da80-dedb-11e9-96bc-a3a3b0f0d92e.jpg)

I expected to see the same performance in both cases, but it seems that training in the second server ruins the situation. Is there any special provision/setting/additional code that I should include in my work?

**Comment by gadagashwini** [comment] 2019-09-25 08:40
@shahriar49, Please provide the simple and standalone code to reproduce the issue reported here. Thanks!

**Comment by shahriar49** [comment] 2019-09-25 12:18
@gadagashwini Thanks for note, but the data that I am using for my work is not a public data, so its reproduction here may not be possible. Isn't there any possibility to discuss this issue by itself? I was thinking that maybe somebody has seen such a behavior before or there is a clear mistake in my approach.

**Comment by gadagashwini** [comment] 2019-09-26 06:39
@shahriar49, 
Will it be possible to use the publicly available data and provide the code to investigate the root cause of the issue. Thanks!

**Comment by shahriar49** [comment] 2019-09-26 13:48
@gadagashwini 
Thank you very much for your attention! I tested a simpler code with mnist data and that noisy loss was not showing. So I will investigate more my code and data and will return to this issue later.
But I faced some other problems that I want to know more about it and I appreciate any help. I used below code for mnist_estimator for my test:

```
import json
import os
import tensorflow as tf
from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
data_dir = '.\\MNIST_data'
log_dir = '.\log_dist'
batch_size = 512
tf.logging.set_verbosity(tf.logging.INFO)

def keras_model(lr, decay):
    """Return a CNN Keras model"""
    input_tensor = tf.keras.layers.Input(shape=(784,), name='input')

    temp = tf.keras.layers.Reshape([28, 28, 1], name='input_image')(input_tensor)
    for i, n_units in enumerate([32, 64]):
        temp = tf.keras.layers.Conv2D(n_units, kernel_size=3, strides=(2, 2),
                                      activation='relu', name='cnn'+str(i))(temp)
        temp = tf.keras.layers.Dropout(0.5, name='dropout'+str(i))(temp)
    temp = tf.keras.layers.GlobalAvgPool2D(name='average')(temp)
    output = tf.keras.layers.Dense(10, activation='softmax', name='output')(temp)

    model = tf.keras.models.Model(inputs=input_tensor, outputs=output)
    optimizer = tf.keras.optimizers.Adam(lr=lr, decay=decay)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    print(model.summary())
    return model


def main():
    """Main function"""
    data = read_data_sets(data_dir,
                          one_hot=False,
                          fake_data=False)
    model = keras_model(lr=0.001, decay=0.001)
    config = tf.estimator.RunConfig(
                model_dir=log_dir,
                save_summary_steps=1,
                save_checkpoints_steps=100)
    estimator = tf.keras.estimator.model_to_estimator(model, model_dir=log_dir, config=config)

    train_input_fn = tf.estimator.inputs.numpy_input_fn(
                         x={'input': data.train.images},
                         y=data.train.labels,
                         num_epochs=None,   # run forever
                         batch_size=batch_size,
                         shuffle=True)
    eval_input_fn = tf.estimator.inputs.numpy_input_fn(
                         x={'input': data.test.images},
                         y=data.test.labels,
                         num_epochs=1,
                         shuffle=False)

    train_spec = tf.estimator.TrainSpec(input_fn=train_input_fn,
                                        max_steps=2000)
    eval_spec = tf.estimator.EvalSpec(input_fn=eval_input_fn,
                                      #throttle_secs=1,
                                      steps=None    # until the end of evaluation data
                                      )

    evaluate_result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
    print("Evaluation results:")
    for key in evaluate_result[0].keys():
        print("   {}: {}".format(key, evaluate_result[0][key]))
```

And then the rest of the code just included the TF_CONFIG definition for chief, worker and ps. I faced below issues:

- I was able to run this code on Tensorflow 1.12 but not on Tensorflow 1.13, where I got the error `ValueError: Can not squeeze dim[1], expected a dimension of 1, got 10 for 'metrics/acc/remove_squeezable_dimensions/Squeeze' (op: 'Squeeze') with input shapes: [512,10].
` What is the reason?
- I could get evaluation results printed at the end of training when I was running program in non-distributed mode, but I get below error when it tries to print the final evaluation results in distributed mode:
```
Traceback (most recent call last):
  File "mnist_estimator.py", line 81, in <module>
    main()
  File "mnist_estimator.py", line 62, in main
    for key in evaluate_result[0].keys():
TypeError: 'NoneType' object is not subscriptable
```
- The final loss for distributed learning was higher than non-distributed learning (for the same number of training steps). What can be the reason? Is it the nature of distribution?
- When running in distributed mode, the chief or worker are not waiting for the other party to start and immediately starts training (when the other party joins they do the task together, though). I thought they should wait for each other to be ready (as it was in my previous experiences with Tensorflow distributed training), isn't it?

**Comment by gadagashwini** [comment] 2019-09-30 09:42
@shahriar49, Any update on reproducible code. Thanks!

**Comment by shahriar49** [comment] 2019-09-30 12:05
@gadagashwini 
Sorry I was very busy and generating sample data and code takes a while. I will close this issue at this time and maybe return to it later.

**Comment by shahriar49** [comment] 2019-09-30 12:21
@gadagashwini 
But I was actually thinking of something that may be a clue: The worker loads the saved model to start working on its batch, but if saved model was a bit old (because models are not saved on each batch), the chief's model may have been way better than worker model and therefore their combination will not be as good as the chief alone. What do you think about it? How such a problem can be avoided in asynchronous distributed learning?

**Comment by rmothukuru** [comment] 2019-10-01 10:26
@shahriar49,
Can you please confirm if you are using `Tensorflow Distribution Strategy` for Distributed Training. 

If you are not using it, can you please try using that. The Tutorial for Distributed Training using `Distribution Strategy` is mentioned in [this link](https://www.tensorflow.org/guide/distributed_training). 

Please use `tf.distribute.Strategy` as described in the above link and let us know if your issue still persists. Thanks!

**Comment by shahriar49** [comment] 2019-10-01 19:15
@rmothukuru 
No I have not defined the distribution strategy, but I see the worker and chief are communicating and training the network together (and the global step per second is increased when having both chief and worker). How does it work without the strategy defined?
And to be honest, I don't understand from the explanations in Tensorflow page which kind of strategy is suitable for my application (i.e. different machines, each have a CPU but may or may not have GPU). Can you tell me which strategy is suitable for this case?

**Comment by rmothukuru** [comment] 2019-10-03 10:40
@shahriar49,
For your case, MultiWorkerMirroredStrategy explained in [this link](https://www.tensorflow.org/guide/distributed_training#multiworkermirroredstrategy) should work. Can you please check and let us know if it works. Thanks!

**Comment by shahriar49** [comment] 2019-10-03 16:28
@rmothukuru 
I used the below mnist_estimator implementation to check the strategy on Tensorflow 1.14. 

```
import json
import os
import tensorflow as tf
from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
data_dir = '.\\MNIST_data'
log_dir = '.\\log_dist_y'
batch_size = 512
tf.logging.set_verbosity(tf.logging.INFO)

def keras_model(lr, decay):
    """Return a CNN Keras model"""
    input_tensor = tf.keras.layers.Input(shape=(784,), name='input')

    temp = tf.keras.layers.Reshape([28, 28, 1], name='input_image')(input_tensor)
    for i, n_units in enumerate([32, 64]):
        temp = tf.keras.layers.Conv2D(n_units, kernel_size=3, strides=(2, 2),
                                      activation='relu', name='cnn'+str(i))(temp)
        temp = tf.keras.layers.Dropout(0.5, name='dropout'+str(i))(temp)
    temp = tf.keras.layers.GlobalAvgPool2D(name='average')(temp)
    output = tf.keras.layers.Dense(10, activation='softmax', name='output')(temp)

    model = tf.keras.models.Model(inputs=input_tensor, outputs=output)
    optimizer = tf.keras.optimizers.Adam(lr=lr, decay=decay)
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    print(model.summary())
    return model


def main():
    """Main function"""
    data = read_data_sets(data_dir,
                          one_hot=False,
                          fake_data=False)
    model = keras_model(lr=0.001, decay=0.001)
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    config = tf.estimator.RunConfig(
                train_distribute=strategy,
                eval_distribute=strategy,
                model_dir=log_dir,
                save_summary_steps=1,
                save_checkpoints_steps=100)
    estimator = tf.keras.estimator.model_to_estimator(model, model_dir=log_dir, config=config)

    train_input_fn = tf.estimator.inputs.numpy_input_fn(
                         x={'input': data.train.images},
                         y=data.train.labels,
                         num_epochs=None,   # run forever
                         batch_size=batch_size,
                         shuffle=True)
    eval_input_fn = tf.estimator.inputs.numpy_input_fn(
                         x={'input': data.test.images},
                         y=data.test.labels,
                         num_epochs=1,
                         shuffle=False)

    train_spec = tf.estimator.TrainSpec(input_fn=train_input_fn,
                                        max_steps=100)
    eval_spec = tf.estimator.EvalSpec(input_fn=eval_input_fn,
                                      #throttle_secs=1,
                                      steps=None    # until the end of evaluation data
                                      )

    evaluate_result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
    print("Evaluation results:")
    for key in evaluate_result[0].keys():
        print("   {}: {}".format(key, evaluate_result[0][key]))

```

Without setting TF_CONFIG and running the code, it does the job (of course, without distribution). But when I define the TF_CONFIG, I get below error:

```
Traceback (most recent call last):
  File "mnist_estimator2.py", line 84, in <module>
    main()
  File "mnist_estimator2.py", line 63, in main
    evaluate_result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 464, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\estimator_training.py", line 290, in train_and_evaluate
    session_config=run_config.session_config)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\distribute_coordinator.py", line 853, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\estimator_training.py", line 252, in _worker_fn
    hooks=hooks)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1156, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1219, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1255, in _actual_train_model_distributed
    input_fn, ModeKeys.TRAIN, strategy)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1009, in _get_iterator_from_input_fn
    lambda input_context: self._call_input_fn(input_fn, mode,
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 774, in make_input_fn_iterator
    input_fn, replication_mode)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 406, in make_input_fn_iterator
    input_fn, replication_mode=replication_mode)
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 380, in _make_input_fn_iterator
    self._container_strategy())
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\distribute\input_lib.py", line 558, in __init__
    "input_fn must return a tf.data.Dataset or a callable.")
ValueError: input_fn must return a tf.data.Dataset or a callable.
Exception ignored in: <bound method Server.__del__ of <tensorflow.python.training.server_lib.Server object at 0x000002AD4A35FF98>>
Traceback (most recent call last):
  File "D:\Shahriar\tf1.14_venv\lib\site-packages\tensorflow\python\training\server_lib.py", line 158, in __del__
AttributeError: 'NoneType' object has no attribute 'UnimplementedError'

```

This is very strange. What does it say?

**Comment by karmel** [comment] 2019-10-06 22:04
@tanzhenyu -- is this potentially related to the bug you fixed for losses in model_to_estimator?

**Comment by tanzhenyu** [comment] 2019-10-07 15:34
@karmel It shouldn't be related to that (that fixes both single training and dist training), this seems more related to estimator distributed training scheme.

**Comment by isaprykin** [comment] 2019-10-07 17:12
@shahriar49     The issue is that in order to use distribution strategies with Estimator the input fn needs to return a dataset.  However, numpy_input_fn doesn't return a dataset, it returns tensors instead.

**Comment by shahriar49** [comment] 2019-10-07 17:41
@isaprykin  OK that seems to be the case (although this lack of support was not expected). However, I am still confused do I need to put the strategy clause in my code or not. As I mentioned earlier, I see the worker and chief are communicating and training the network together (and the global step per second is increased when having both chief and worker) even without this clause.

**Comment by rmothukuru** [comment] 2019-10-09 06:09
@shahriar49,
Please confirm if we can close this issue as the concern about Distributed Strategy is being addressed and as the problem about Distributed Training without using Distributed Strategy is being addressed in #32841. Thanks!

**Comment by shahriar49** [comment] 2019-10-09 12:06
@rmothukuru 
I am still waiting for an answer to clarify how the worker and chief are communicating and training the network together without strategy clause. If they work without it, what is the benefit of including this clause?

**Comment by tensorflowbutler** [comment] 2021-02-01 14:08
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:54 UTC
Labels: TF 1.13, comp:dist-strat, stat:awaiting tensorflower, type:bug
