### ISSUE TITLE
feed_dict performance

### ISSUE THREAD

**Issue by nanddalal** [tensorflow/tensorflow#2919] opened 2016-06-17 01:27 UTC
I have been experimenting with different way of reading data in tensorflow, namely:
- input ops / queues
- feed_dict / placeholders

I am finding that feed_dict is much slower on my alexnet benchmark. I have adapted the alexnet benchmark code from the [convnet-benchmarks](https://github.com/soumith/convnet-benchmarks/blob/master/tensorflow/benchmark_alexnet.py). You can find my benchmarking code [here](https://gist.github.com/nanddalal/a0fdd6798ea52afaaeb6e1a78aaeb6db). The main diff is the addition of a `feed_dict` flag which switches between using tf.Variable and tf.Placeholder for the inputs/labels.

In all my tests, I only run the fprop.
My first test was running the benchmark on a GPU using NCHW:
```
feed_dict=True: 102 ms/minibatch
feed_dict=False 28 ms/minibatch
```
As you can see, with `feed_dict=False`, it matches the benchmark, but with `feed_dict=True`, it is 4-5x slower. You can find the full output for `feed_dict=True` [here](https://github.com/tensorflow/tensorflow/files/319610/benchmark_with_feed_dict.txt)
 and `feed_dict=False` [here](https://github.com/tensorflow/tensorflow/files/319611/benchmark_without_feed_dict.txt). These contain yappi profiling output which shows that the bottleneck does not seem to be in the python code. I have also attached the tf timeline output and would appreciate if you can tell me how to interpret it in chrome://tracing. 
[timeline_with_feed_dict.json.txt](https://github.com/tensorflow/tensorflow/files/319613/timeline_with_feed_dict.json.txt)
[timeline_without_feed_dict.json.txt](https://github.com/tensorflow/tensorflow/files/319614/timeline_without_feed_dict.json.txt)

I also ran the same test on CPU using NHWC:
```
feed_dict=True: 727 ms/minibatch
feed_dict=False: 664 ms/minibatch
```
So using `feed_dict` appears to have a constant/one time cost.

I was able to gain almost 2x speedup by changing this [line](https://github.com/tensorflow/tensorflow/blob/9425f822d8a5dc657022eed5c5142b4bf7b1087a/tensorflow/python/client/session.py#L619) from `np.array` to `np.asarray`, but feed_dict is still quite slow.

Please let me know what your thoughts are about this and whether feed_dict is supposed to be this much slower than a pipeline using tfrecords/queues.

**Comment by yaroslavvb** [comment] 2016-06-17 01:39
Feed_dict does a single-threaded memcpy of contents from Python runtime into TensorFlow runtime. If data is needed on GPU, then you'll have an additional CPU->GPU transfer. I'm used to seeing up to 10x improvement in performance when switching from feed_dict to native TensorFlow (Variable/Queue)

**Comment by nanddalal** [comment] 2016-06-17 02:12
It seems like there are a lot of copies being made of the values in the feed dict as it moves from the numpy array to the tensor proto's bytes. Do you think we can reduce some of these? For example changing the `np.array` to `np.asarray`. Or even better is it possible to directly assign the tensor proto's byte field to look at the numpy array's pointer?

**Comment by yaroslavvb** [comment] 2016-06-17 20:29
@nanddalal extra copy in `np.array` seems like a bug, good catch. 

As far as feasibility of removing the extra copy, I believe the memcpy is happening in [TF_wrapper_helper](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/python/client/tf_session_helper.cc#L445). There's a note from @mrry that memcpy is there to prevent having to acquire GIL on deallocation.

Since numpy array object is owned by Python runtime, when it's destroyed Python will try to de-allocate the data. If there's a way to tell numpy to release the ownership of the data buffer, this wouldn't be an issue. 

Perhaps an intermediate step would be to replace memcpy with multi-threaded memcpy. There's a six-year old [post on SO](http://stackoverflow.com/questions/4260602/how-to-increase-performance-of-memcpy) suggesting 6x improvement

**Comment by prb12** [comment] 2016-06-21 20:36
@mrry Did you just fix this?

**Comment by mrry** [comment] 2016-06-21 20:43
@prb12: The s/`np.array`/`np.asarray`/ change should appear soon (obsoleting #2931), but it was intended to reduce memory pressure&mdash;I haven't measured the performance impact, although the comments here suggest it will be a ~2x improvement for some patterns....

**Comment by sjperkins** [comment] 2016-07-14 21:44
> Since numpy array object is owned by Python runtime, when it's destroyed Python will try to de-allocate the data. If there's a way to tell numpy to release the ownership of the data buffer, that could be a work-around.

I see there's already a Py_DECREF "associated" with the numpy input arrays when they are wrapped in unique_ptr's  with `make_safe`. I guess this is to ensure they're there to encourage release of the numpy base arrays on exit of TF_wrapper_helper. Am I reading this correctly?

How about using Py_INCREF on the numpy inputs to make sure they exist for the duration of `session.run` (which is guarded by the GIL) and then Py_DECREF them afterwards . This should prevent release of the underlying buffer during `session.run` which I guess is what the guard is for?

**Comment by michaelisard** [comment] 2016-07-25 21:54
@mrry did this change get pushed?

**Comment by mrry** [comment] 2016-07-25 22:44
Yep, in https://github.com/tensorflow/tensorflow/commit/f68cbf19fb8f67a5dce889a5464a358ec0035f18

**Comment by michaelisard** [comment] 2016-07-25 22:56
@nanddalal is this fixed adequately now?

**Comment by aselle** [comment] 2016-08-08 16:25
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-08-08 16:25 UTC
Labels: awaiting response

**Comment by JohnAllen** [comment] 2016-10-03 14:55
Does the above fix mean that using `feed_dict` isn't slow now?

**Comment by yaroslavvb** [comment] 2016-10-03 15:35
@JohnAllen it's still slow

**Comment by nanddalal** [comment] 2016-10-03 15:44
@JohnAllen I would recommend https://github.com/tensorflow/tensorflow/issues/3377#issuecomment-239969809
