### ISSUE TITLE
ModelCheckpoint callback can't save entire subclassed models

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#37839] opened 2020-03-23 20:35 UTC
The keras callback `ModelCheckpoint` won't save a subclassed model in SavedModel format. It only ever saves the checkpoints.

```python
import tensorflow as tf
import numpy as np

class TestModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(64, activation='relu')
        self.dense2 = tf.keras.layers.Dense(64, activation='relu')
        self.dense3 = tf.keras.layers.Dense(10)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)


model = TestModel()
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss='mse',      
              metrics=['mae'])  

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(
    data, labels, epochs=10, batch_size=32,
    callbacks=[tf.keras.callbacks.ModelCheckpoint('model_{epoch:02d}.ckpt',
                                                  save_weights_only=False)])
```

It seems as if the callback forces weights_only saving [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L1148). While this makes sense if the model is in `.h5` format, it doesn't make sense for `SavedModel` format.

**Comment by ravikyram** [comment] 2020-03-24 06:01
@lminer 

Can you please share simple standalone code to reproduce the issue.It helps us in localizing the issue faster. Please, let us know TF version as well. Thanks!

**Comment by pandrey-fr** [comment] 2020-03-24 11:12
If I read well the source code, if you custom model inherits from `Model` and is a graph network (_i.e._ not running eagerly) it should be working...

**Comment by lminer** [comment] 2020-03-24 16:05
@pandrey-fr @ravikyram I'll try to get a standalone example together. The problem must be that the model is being run eagerly. How to you force it to be a graph network? Also, why is it a problem if it's run eagerly? I made my own version of the callback where I deleted the check for whether it is running eagerly and it saves without a problem.

**Comment by lminer** [comment] 2020-03-25 21:19
@ravikyram @pandrey-fr it's updated.

**Comment by pandrey-fr** [comment] 2020-03-26 09:33
Okay, actually it turns out that `_is_graph_network` is _not_ about `Eager` execution, but about the distinction between the functional and subclass APIs.

In functional API, you would define your example network as:
```python
dense1 = tf.keras.layers.Dense(64, activation='relu')
dense2 = tf.keras.layers.Dense(64, activation='relu')
dense3 = tf.keras.layers.Dense(10)
inputs = tf.keras.Input((32,), dtype='float32')
output = dense3(dense2(dense1(inputs)))
model = tf.keras.Model(inputs, output)
```
Which would have the computation graph built at instantiation, notably through the clear definition of inputs' (and thus, all nodes') specification.

In the subclass API however, the instantiation procedure differs ([this method](https://github.com/tensorflow/tensorflow/blob/dc05a7a6b94e65f92924c82841a5332c86cbc3c9/tensorflow/python/keras/engine/network.py#L366) is called), which results in a Model with somehow reduced capabilities. To be fair, the point of this is to allow defining `Model` constructor subclasses which implement alternative behaviours, _e.g._ different train step procedures, yet remain general enough to be used in functional API.

Now in your example, I would advise writing your model architecture as a `tf.keras.layers.Layer` subclass, and then using the functional API to instantiate a `Model` out of it:
```python
class TestModel(tf.keras.layers.Layer):

    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(64, activation='relu')
        self.dense2 = tf.keras.layers.Dense(64, activation='relu')
        self.dense3 = tf.keras.layers.Dense(10)

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return self.dense3(x)

inputs = tf.keras.Input((32,), dtype='float32')
network = TestModel()
model = tf.keras.Model(inputs, network(inputs))
```

**Comment by lminer** [comment] 2020-03-26 16:11
Is it necessary to use that approach anymore? In tensorflow 2.2.0-rc1 I can save a subclassed model in the SavedModel format and restore it without a problem. Maybe this check is now obsolete.

**Comment by pandrey-fr** [comment] 2020-03-27 09:24
> In tensorflow 2.2.0-rc1 I can save a subclassed model in the SavedModel format and restore it without a problem.

I have to admit I don't quite get why it works in 2.2 and not in previous versions, but great! If I understand well, some specifications are inferred / set within the `fit` call, which explains why I was initially able to replicate the issue by attempting to use `model.save` _before_ `model.fit`.

> is the problem that it wouldn't be possible to serialize the model into the SavedModel format if I overrode train_step as then it really would involve serializing code?

Normally this should not be an issue. The checkpoints should allow you to resume training with an instance of the same custom model class; I don't think that checkpoints do not contain the `train_step` code, but to be honest I do not know much about the checkpointing system.

**Comment by lminer** [comment] 2020-03-27 16:16
Should we perhaps alter that check to only apply for h5 format?

**Comment by gowthamkpr** [comment] 2020-04-05 08:46
@lminer This is the intended behaviour of checkpointing as it only saves weights of the model not the model itself.

**Comment by lminer** [comment] 2020-04-05 15:53
@gowthamkpr the callback has the option of either saving weights or saving the entire model. Given that it has this option, and that it has the ability to delivery this functionality provided you are saving in SavedModel format, why not enable it?

**Comment by claudio525** [comment] 2020-04-19 20:42
I am running in this same issue as well, have a sub-classed keras model that I can save fine manually using the SaveModel format. However when using the ModelCheckpoint this is not possible, as model._is_graph_network is False for a sub-classed model (which results in save_weights_only flag to be set to True ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L1161)).

**Comment by lminer** [comment] 2020-04-23 00:10
@gowthamkpr Any update on this? I understand why this was the intended behavior back when subclassed models couldn't be saved. But now that this functionality has been added in tensorflow 2.2.0, it makes sense to update the callback so that there is feature parity between subclassed models and functional api models.

**Comment by gowthamkpr** [comment] 2020-05-14 04:17
@lminer  @claudio525 Thanks for the update.

**Comment by sedghi** [comment] 2020-08-05 15:45
Is there an update here?

**Comment by relativeflux** [comment] 2020-08-09 21:44
Yes, let's have an update on this ASAP, please.

Thanks.

**Comment by snehalscribd** [comment] 2020-08-29 20:59
I still see this issue in TF 2.3.0. When I reload model, it doesn't have custom train_step method. Is there any fix yet?

**Comment by ghannum** [comment] 2020-09-15 18:23
Upvote here. I would love to see this fixed.

**Comment by zara44** [comment] 2020-09-16 20:41
I m facing the same issue as well subclass model is the only option for the keras CRF layer and as result of this issue we can't save the best model post early stopping.

**Comment by ccrusius** [comment] 2020-11-06 18:20
Duplicate of #37620

**Closed by ccrusius** 2020-11-06 18:20 UTC
Labels: comp:keras, stat:awaiting tensorflower, type:bug

**Comment by ramshi236** [comment] 2021-08-23 12:25
any progress ?
