### ISSUE TITLE
Cannot register 2 metrics with the same name error.

### ISSUE THREAD

**Issue by VladimirRoaming** [tensorflow/tensorflow#13522] opened 2017-10-06 13:23 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Swift API for TensorFlow
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS 10.12.6 (16G29), Darwin MacBookPro.local 16.7.0 Darwin Kernel Version 16.7.0
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
master branch [d864489]
- **Python version**: 
Python 2.7.13
- **Bazel version (if compiling from source)**:
bazel release 0.5.4
- **CUDA/cuDNN version**:
no
- **GPU model and memory**:
no
- **Exact command to reproduce**:

Dear TensorFlow contributors, 
 I am working on swift height-level API for TensorFlow. To provide that, I am [using system module](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#require-system-libraries) to provide access to C and C++ API. C API is clear in swift code, for C++ library I am writing my own wrappers. After update master branch I can't pass tests in my framework. Launch tests leads to error: 
> Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count

My guess is:
After commit [a674130] ''Expose C API symbols on OS X", all C API available on C++ library. 
[more info](https://github.com/tensorflow/tensorflow/pull/12741)
You can see all C interfaces are available at C++ library:
`
$ nm bazel-bin/tensorflow/libtensorflow_cc.so | grep 'TF_New'
000000000000f5f0 T _TF_NewBuffer
000000000000f610 T _TF_NewBufferFromString
000000000000f6b0 T _TF_NewDeprecatedSession
00000000000176f0 T _TF_NewGraph
0000000000017aa0 T _TF_NewImportGraphDefOptions
0000000000013190 T _TF_NewOperation
000000000001a170 T _TF_NewSession
000000000000f500 T _TF_NewSessionOptions
000000000000ea90 T _TF_NewStatus
000000000000ee80 T _TF_NewTensor
0000000000018a70 T _TF_NewWhile
000000000001cbb0 t __ZZ22TF_NewBufferFromStringEN3$_08__invokeEPvm
`

So, my question/request is: 
1) Is it well-considered and final decision to provide C API in C++ library?
2) Will it be default and public configuration to provide C API in C++ library?
3) Is there any way to configure and build tensorflow library without changing 
`tools/tf_env_collect.sh` file?
Thank you for your work.

**Comment by asimshankar** [comment] 2017-10-09 07:22
I'm sorry, but from your description I'm not quite certain what the problem is. On the surface it seems the same initializers are being linked into your binary multiple times and precisely why that is happening isn't clear to me as I'm not sure about the details of the process being used to link. Unfortunately, the TensorFlow maintainers do not have enough background in Swift to be helpful there. Perhaps you could look at how other Swift bindings such as https://github.com/PerfectlySoft/Perfect-TensorFlow work?

**Comment by VladimirRoaming** [comment] 2017-10-09 09:29
Hello,  
 >>On the surface it seems the same initializers are being linked into your binary multiple times...
As you can see, any binary has only one  linking: 
```

$ otool -L ./.build/x86_64-apple-macosx10.10/debug/OpProducer
./.build/x86_64-apple-macosx10.10/debug/OpProducer:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1443.13.0)
	/usr/local/opt/protobuf/lib/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	/server/repository/tensorflow/bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow_cc.so (compatibility version 0.0.0, current version 0.0.0)
	/server/repository/tensorflow/bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftIOKit.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftSwiftOnoneSupport.dylib (compatibility version 1.0.0, current version 900.0.65)
```

Are there any way to trace library code ?

**Comment by VladimirRoaming** [comment] 2017-10-09 09:54
I rebuild build without C++ API and C++ library

```
otool -L ./.build/x86_64-apple-macosx10.10/debug/OpProducer
./.build/x86_64-apple-macosx10.10/debug/OpProducer:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1443.13.0)
	/usr/local/opt/protobuf/lib/libprotobuf.14.dylib (compatibility version 15.0.0, current version 15.0.0)
	/server/repository/tensorflow/bazel-out/darwin_x86_64-opt/bin/tensorflow/libtensorflow.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftIOKit.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 900.0.65)
	@rpath/libswiftSwiftOnoneSupport.dylib (compatibility version 1.0.0, current version 900.0.65)
```

And that is works fine. It means, that I can't use C and C++ libraries in the same code at the same time.
But in **r1.3** it is **works**. That means, somebody (I think @fritzo at [a651023](https://github.com/tensorflow/tensorflow/commit/a6510237f06f03babfbcce1bcfa77f07f0d03c50)) added C code to C++ library. And after that you can't use both libraries in your code.
I tried build only with C++ library, but unfortunately It doesn't work. There is no enough implementation C code in C++ library.

**Comment by VladimirRoaming** [comment] 2017-10-09 12:22
Rebuild with latest changes in master only with C++ library. 
Yes, it is works fine on mac os. Linking pass, tests pass.
On Linux (Linux kraken 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux):
+ Build and run C API related code.
- Can't link C++ code in binary and tests, error:
```
$ swift build --product OpProducer -Xcxx -std=c++11
Compile CCAPI EventsWriter.cc
Compile Swift Module 'OpProducer' (3 sources)
Linking ./.build/x86_64-unknown-linux/debug/OpProducer
/server/repository/TensorFlow/Sources/CCAPI/EventsWriter.cc:32: error: undefined reference to 'tensorflow::Event::Event()'
/server/repository/TensorFlow/Sources/CCAPI/EventsWriter.cc:36: error: undefined reference to 'tensorflow::EventsWriter::WriteEvent(tensorflow::Event const&)'
/server/repository/TensorFlow/Sources/CCAPI/EventsWriter.cc:38: error: undefined reference to 'tensorflow::Event::~Event()'
/server/repository/TensorFlow/Sources/CCAPI/EventsWriter.cc:38: error: undefined reference to 'tensorflow::Event::~Event()'
/server/repository/TensorFlow/Sources/CCAPI/EventsWriter.cc:41: error: undefined reference to 'tensorflow::EventsWriter::EventsWriter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/server/repository/tensorflow/bazel-genfiles/tensorflow/core/util/event.pb.h:1105: error: undefined reference to 'tensorflow::Event::clear_what()'
/server/repository/tensorflow/tensorflow/core/util/events_writer.h:46: error: undefined reference to 'tensorflow::EventsWriter::Close()'
//usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:76: error: undefined reference to 'tensorflow::io::RecordWriter::~RecordWriter()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /server/repository/TensorFlow/.build/debug.yaml OpProducer
```
Tested as static and dynamic (own) libraries. 
The same with tests. Log attached.


For example EventWriter wrapper is really simple: 
```
#include "include/EventsWriter.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/util/events_writer.h"

using namespace std;
using namespace tensorflow;

void write(const void* serializedGraph, size_t serializedGraphSize, EventsWriter* writer, double wall_time, int64 step) {
	
	Event event;
	event.set_wall_time(wall_time);
	event.set_step(step);
	event.set_graph_def(serializedGraph, serializedGraphSize);
	writer->WriteEvent(event);
	
}

void createEventWriter(const void* serializedGraph, size_t serializedGraphSize, char * filePath, double wall_time, long long step) {
	EventsWriter eventsWriter(filePath);
	write(serializedGraph, serializedGraphSize, &eventsWriter, wall_time, step);
}
```

**Comment by VladimirRoaming** [comment] 2017-10-09 15:25
I tred to build that [example project](https://www.octadero.com/wp-content/uploads/2017/10/TFBuildTest.zip) with **r1.3** c++ library:

```
export LD_LIBRARY_PATH=/server/repository/tensorflow_1.3/tensorflow/bazel-bin/tensorflow:/server/repository/tensorflow_1.3/protobuf/src/.libs/
swift build -Xcxx -std=c++11 -Xlinker -L/server/repository/tensorflow_1.3/protobuf/src/.libs/ -Xlinker -lprotobuf -Xcxx -I/server/repository/tensorflow_1.3/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public/ -Xcxx -I/server/repository/tensorflow_1.3/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src/ -Xcxx -I/server/repository/tensorflow_1.3/tensorflow/ -Xcxx -I/server/repository/tensorflow_1.3/tensorflow/bazel-genfiles -Xlinker -L/server/repository/tensorflow_1.3/tensorflow/bazel-bin/tensorflow -Xlinker -ltensorflow_cc 
``` 
It is ok.
[build log](https://www.octadero.com/wp-content/uploads/2017/10/simple_build_1.3.txt)

And tried with **master** brunch:
```
export LD_LIBRARY_PATH=/server/repository/tensorflow/bazel-bin/tensorflow:/usr/local/lib/
swift build -Xcxx -std=c++11 -Xlinker -L/usr/local/lib -Xlinker -lprotobuf -Xcxx -I/server/repository/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public/ -Xcxx -I/server/repository/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src/ -Xcxx -I/server/repository/tensorflow/ -Xcxx -I/server/repository/tensorflow/bazel-genfiles -Xlinker -L/server/repository/tensorflow/bazel-bin/tensorflow -Xlinker -ltensorflow_cc 
```

Error: 
```
**/usr/bin/swiftc --driver-mode=swift -L /usr/lib/swift/pm/4 -lPackageDescription -swift-version 4 -I /usr/lib/swift/pm/4 -sdk / /server/repository/TFBuildTest/Package.swift -fileno 6
/usr/bin/swift-build-tool -f /server/repository/TFBuildTest/.build/debug.yaml main -v
/usr/bin/clang -target 'x86_64-unknown-linux' --sysroot / -fPIC -g '-O0' '-std=c++11' -I/server/repository/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public/ -I/server/repository/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src/ -I/server/repository/tensorflow/ -I/server/repository/tensorflow/bazel-genfiles -fmodules -fmodule-name=CCAPI -I /server/repository/TFBuildTest/Sources/CCAPI/include '-fmodules-cache-path=/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/ModuleCache' -MD -MT dependencies -MF '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/CCAPI.build/EventsWriter.cc.d' -c /server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc -o '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/CCAPI.build/EventsWriter.cc.o'
arcr/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/libCCAPI.a/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/CCAPI.build/EventsWriter.cc.o
/usr/bin/swiftc -module-name TFBuildTest -incremental -emit-dependencies -emit-module -emit-module-path /server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/TFBuildTest.swiftmodule -output-file-map /server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/TFBuildTest.build/output-file-map.json -num-threads 8 -c /server/repository/TFBuildTest/Sources/TFBuildTest/main.swift -I /server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug -swift-version 4 -target x86_64-unknown-linux -sdk / -Onone -g -enable-testing -j8 -DSWIFT_PACKAGE -Xcc -fmodule-map-file=/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/CCAPI.build/module.modulemap -I /server/repository/TFBuildTest/Sources/CCAPI/include -module-cache-path /server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/ModuleCache
/usr/bin/swiftc -target 'x86_64-unknown-linux' -sdk / -Xlinker -L/usr/local/lib -Xlinker -lprotobuf -Xlinker -L/server/repository/tensorflow/bazel-bin/tensorflow -Xlinker -ltensorflow_cc -lstdc++ -g -L '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug' -o '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/TFBuildTest' -module-name TFBuildTest -emit-executable -Xlinker '-rpath=$ORIGIN' '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/CCAPI.build/EventsWriter.cc.o' '/server/repository/TFBuildTest/.build/x86_64-unknown-linux/debug/TFBuildTest.build/main.swift.o'
/server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc:26: error: undefined reference to 'tensorflow::Event::Event()'
/server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc:30: error: undefined reference to 'tensorflow::EventsWriter::WriteEvent(tensorflow::Event const&)'
/server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc:32: error: undefined reference to 'tensorflow::Event::~Event()'
/server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc:32: error: undefined reference to 'tensorflow::Event::~Event()'
/server/repository/TFBuildTest/Sources/CCAPI/EventsWriter.cc:35: error: undefined reference to 'tensorflow::EventsWriter::EventsWriter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/server/repository/tensorflow/bazel-genfiles/tensorflow/core/util/event.pb.h:1105: error: undefined reference to 'tensorflow::Event::clear_what()'
/server/repository/tensorflow/tensorflow/core/util/events_writer.h:46: error: undefined reference to 'tensorflow::EventsWriter::Close()'
//usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:76: error: undefined reference to 'tensorflow::io::RecordWriter::~RecordWriter()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /server/repository/TFBuildTest/.build/debug.yaml main -v** 
```

[build log](https://www.octadero.com/wp-content/uploads/2017/10/simple_build_master.txt)

**Comment by tatatodd** [comment] 2017-10-11 04:06
@VladimirRoaming I'm also somewhat confused by your description of the problem.  Let me attempt to re-phrase the questions I think you're asking:

1) Are `libtensorflow.so` and `libtensorflow_cc.so` intended to be used together, or separately?  I.e. is the user allowed to link both into the same binary?

2) Should we expect that C API symbols are exported via `libtensorflow_cc.so`?  Or should they only be exported via `libtensorflow.so`?

3) It seems that the behavior has changed between r1.3 and master on MacOS, possibly due to a651023.

@asimshankar Perhaps you can comment on these questions.

**Comment by asimshankar** [comment] 2017-10-11 07:18
@VladimirRoaming : Can you reduce the problem to linking of a C++ binary? From what you've shared, it's hard for us to comment since there are many layers (including swift code which we're not familiar with) to wade through. 

That said, I think [the change to split the TensorFlow shared libraries](https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc) into `libtensorflow_framework.so` + language API (e.g., `libtensorflow.so` for C, `libtensorflow_cc.so` for C++, `pywrap_tensorflow.so` for Python) is the one that is probably causing you trouble. As a result of this change, most of the framework symbols are in `libtensorflow_framework.so` now. And from the error messages above, it seems that the linker was having trouble finding `tensorflow::Event::Event()`, which will be in that library.

The fix should be simple enough, include `-ltensorflow_framework.so` in your command-line.
(This change [is mentioned in the updated documentation](https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc#diff-4bef2b6f872037e4e6daaf3b93c6f253), however the documentation on tensorflow.org is tied to the latest stable release, not the master branch at github).


As an example, I did the following on Linux which seems to work out well:

```sh
# Build the C++ library from source
bazel build -c opt //tensorflow:libtensorflow_cc.so

# Create the test program
cat >/tmp/test.cc <<EOF
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/util/events_writer.h"

int main() {
  tensorflow::EventsWriter writer("/tmp/events");
  writer.WriteEvent(tensorflow::Event());
  writer.Close();
}
EOF

# Build the test program
EXTERNAL_DIR="$(bazel info output_base)/external"
g++ /tmp/test.cc \
 -std=c++11 \
 -I. -Ibazel-genfiles \
 -I ${EXTERNAL_DIR}/protobuf_archive/src \
 -I ${EXTERNAL_DIR}/nsync/public \
 -Lbazel-bin/tensorflow -ltensorflow_cc -ltensorflow_framework

# Run the test program
LD_LIBRARY_PATH=bazel-bin/tensorflow ./a.out
```
As for the questions Todd mentioned above:

1. `libtensorflow_cc.so` is a strict superset of `libtensorflow.so` so you shouldn't have to link against both in the same binary. Though, this may change in the future.

2. For now, yes, `libtensorflow_cc.so` exports all the symbols defined in the C API. Though, this may change in the future.

3. If the analysis above is correct, this issue is not specific to macOS or Linux - in both you'll have to include `libtensorflow_framework.so` when linking/running, or build with `--config=monolithic`.

**Comment by VladimirRoaming** [comment] 2017-10-11 07:18
Sorry for my flow of consciousness,
I faced several issues in the new version and tried to resolve them.
Yes, you're absolutely right with those 3 points.
There is one more issue with linking phase at linux, I will describe it in a special ticket.

**Comment by asimshankar** [comment] 2017-10-11 07:24
@VladimirRoaming : It seems our posts might have collided. Does adding `-ltensorflow_framework` solve your issue? If not, please provide a short reproduction of the problem (similar to the commands and example program I shared above).

**Comment by VladimirRoaming** [comment] 2017-10-11 07:44
Had to rebuild tensorflow from the scratch.
Yes, `-ltensorflow_framework` helped. Thanks a lot.

**Comment by asimshankar** [comment] 2017-10-11 07:50
Closing this issue out since it seems it has been addressed.

**Closed by asimshankar** 2017-10-11 07:50 UTC
Labels: stat:awaiting response, type:support

**Comment by Kmarconi** [comment] 2020-06-09 12:08
I'm sorry to reopen this issue but I'm facing the same issue even with the solution proposed here. I'm using autotools to generate an executable file which is using opencv and tensorflow. To do this, i've set this libraries flags : AM_LDFLAGS = -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_videoio -ltensorflow_cc -ltensorflow_framework -lprotobuf -lprotoc . My make command is working well but I'm trying to run my executable, I always have this error : 

`2020-06-09 14:02:25.158088: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count
2020-06-09 14:02:25.158383: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency
2020-06-09 14:02:25.158467: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency_by_stage
2020-06-09 14:02:25.159111: F tensorflow/core/framework/variant_op_registry.cc:53] Check failed: existing == nullptr (0x55a3931838 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::data::WrappedDatasetVariant already registered
Aborted (core dumped)`

Any suggestion would be much appreciated !

**Comment by sandeep22-v** [comment] 2021-06-06 14:30
> I'm sorry to reopen this issue but I'm facing the same issue even with the solution proposed here. I'm using autotools to generate an executable file which is using opencv and tensorflow. To do this, i've set this libraries flags : AM_LDFLAGS = -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_videoio -ltensorflow_cc -ltensorflow_framework -lprotobuf -lprotoc . My make command is working well but I'm trying to run my executable, I always have this error :
> 
> `2020-06-09 14:02:25.158088: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count 2020-06-09 14:02:25.158383: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency 2020-06-09 14:02:25.158467: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency_by_stage 2020-06-09 14:02:25.159111: F tensorflow/core/framework/variant_op_registry.cc:53] Check failed: existing == nullptr (0x55a3931838 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::data::WrappedDatasetVariant already registered Aborted (core dumped)`
> 
> Any suggestion would be much appreciated !

Have you solved it sir??I am also facing the same issue
