### ISSUE TITLE
pip install error could not find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by EmadElDinH** [tensorflow/tensorflow#47140] opened 2021-02-14 06:49 UTC
I'm using python 3.9.1 64-bit, win10 and I try to install TesorFlow using either pip, pip3 or pip3.9, but I always receive the error:

ERROR: Could not find a version that satisfies the requirement tesorflow
ERROR: No matching distribution found for tesorflow

![image](https://user-images.githubusercontent.com/79036528/107870484-5896cd00-6ea1-11eb-8267-aee1f3e27e88.png)

can you please help!

**Comment by Zethson** [comment] 2021-02-14 11:02
You wrote tesorflow and not tensorflow.

**Comment by EmadElDinH** [comment] 2021-02-15 01:01
it's a typing mistake of course, it seems that chose the only one time in which i misspelled TensorFlow 
anyway here another trial that shows the error i'm trying to solve
![image](https://user-images.githubusercontent.com/79036528/107894858-c7276980-6f39-11eb-966c-b81e2b30fcb8.png)
can you please help!
N.B: I'm using win10 & python 3.9,1 64-bit

**Comment by amahendrakar** [comment] 2021-02-15 06:32
@EmadElDinH,
TensorFlow v2.2 is compatible with Python 3.5 - 3.8. For, more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#cpu).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1

Could you please install Python 3.8 and let us know if you are facing the same issue.

Thanks!

**Comment by mihaimaruseac** [comment] 2021-02-15 18:26
TensorFlow has no release for Python 3.9. Closing as duplicate of #44485

**Closed by mihaimaruseac** 2021-02-15 18:26 UTC
Labels: TF 2.2, stat:awaiting response, subtype:windows, type:build/install

**Comment by EmadElDinH** [comment] 2021-02-15 22:08
I have uninstalled python 3.9 and then installed python 3.8, after that I could successfully install the TensorFlow module ,,,
BUT now I'm encountering another issue; although I was able to install all the needed modules using the pip install command on my virtual environment, I always get an error in importing them through my program: e.g.: I could install the pandas_datareader module, but it returns the error "**ModuleNotFoundError: No module named 'pandas_datareader**" when I import it in my python program !!!
I've been trying for the whole day, can you please help!
thanks!

**Comment by amahendrakar** [comment] 2021-02-24 07:07
@EmadElDinH,
This repository is only for tracking TensorFlow bugs and feature requests. 

For help with the `pandas_datareader`module, please raise an issue in the [pydata/pandas-datareader](https://github.com/pydata/pandas-datareader/issues) repo.

Thanks!
