### ISSUE TITLE
tf.cond leads to memory leak?

### ISSUE THREAD

**Issue by tsing-cv** [tensorflow/tensorflow#30020] opened 2019-06-21 08:01 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): Tf=1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: TITAN RTX 24G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```python
2019-06-25 10:59:25.073825: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_true_34339
2019-06-25 10:59:25.073932: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_false_34340
2019-06-25 10:59:25.073977: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_1_true_34395
2019-06-25 10:59:25.074019: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_1_false_34396
2019-06-25 10:59:25.074057: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_true_34482
2019-06-25 10:59:25.074136: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_false_34483
2019-06-25 10:59:25.074170: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_true_34568
2019-06-25 10:59:25.074219: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_false_34569
2019-06-25 10:59:25.074256: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_true_34568_rewritten
2019-06-25 10:59:25.074353: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_false_34569_rewritten
2019-06-25 10:59:25.074425: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_true_34568_grad_34687
2019-06-25 10:59:25.074600: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_3_false_34569_grad_34755
2019-06-25 10:59:25.074654: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_true_34482_rewritten
2019-06-25 10:59:25.074817: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_false_34483_rewritten
2019-06-25 10:59:25.074884: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_true_34482_grad_34822
2019-06-25 10:59:25.075129: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_2_false_34483_grad_34926
2019-06-25 10:59:25.075177: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_1_true_34395_grad_34994
2019-06-25 10:59:25.075268: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_1_false_34396_grad_35015
2019-06-25 10:59:25.075303: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_true_34339_grad_35033
2019-06-25 10:59:25.075362: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: cond_false_34340_grad_35044
```
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-06-24 10:53
@tsing-cv In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by tsing-cv** [comment] 2019-06-25 03:03
training loop
```python
        @tf.function
        def train_step(inputs):
            with tf.GradientTape() as tape:
                rpn_class_logits, rpn_bbox, mrcnn_box_outputs, mrcnn_mask, target_class_ids, target_bbox, target_mask, active_class_ids = ood_str(inputs)
                rpn_class_loss = losses.rpn_cla_loss(inputs[-2], rpn_class_logits)
                rpn_bbox_loss = losses.rpn_bbox_loss(inputs[-1], inputs[-2], rpn_bbox)
                mrcnn_class_loss = losses.mrcnn_cla_loss(target_class_ids, mrcnn_box_outputs["mrcnn_class_logits"], active_class_ids)
                mrcnn_bbox_loss = losses.mrcnn_bbox_loss(target_bbox, target_class_ids, mrcnn_box_outputs["mrcnn_bbox"])
                mrcnn_mask_loss = losses.mrcnn_mask_loss(target_mask, target_class_ids, mrcnn_mask)

                total_loss = rpn_bbox_loss+rpn_class_loss+mrcnn_class_loss+mrcnn_bbox_loss+mrcnn_mask_loss
                tf.get_default_graph().get_collection(tf.GraphKeys.LOSSES)
            grads = tape.gradient(total_loss, ood_str.trainable_variables)   
            optimizer.apply_gradients(zip(grads, ood_str.trainable_variables))
            print("================",len(tf.get_default_graph().get_collection(tf.GraphKeys.LOSSES)))
            return total_loss,rpn_class_loss,rpn_bbox_loss,mrcnn_class_loss,mrcnn_bbox_loss,mrcnn_mask_loss

        def eval_step(inputs):
            with tf.GradientTape() as tape:
                detections, mask = ood_str(inputs)
            
        
        for epoch in range(start_epoch, 400):
            for (batch, inputs) in enumerate(train_generator):
                # print (inputs)
                print (f"batch num: {batch}")
                # rpn_class_logits, rpn_bbox, mrcnn_box_outputs, mrcnn_mask, target_class_ids, target_bbox, target_mask, active_class_ids = ood_str(inputs)
                total_loss,rpn_class_loss,rpn_bbox_loss,mrcnn_class_loss,mrcnn_bbox_loss,mrcnn_mask_loss = train_step(inputs)
                print (f"collection: {gc.collect()}")
                print (f"Total Loss: {total_loss.numpy():.6f}")
                print (f"RPN Loss:   class_loss={rpn_class_loss.numpy():.6f} \tbbox_loss={rpn_bbox_loss.numpy():.6f}")
                print (f"MRCNN Loss: class_loss={mrcnn_class_loss.numpy():.6f} \tbbox_loss={mrcnn_bbox_loss.numpy():.6f}\tmask_loss={mrcnn_mask_loss.numpy():.6f}")
                print (gc.collect())
                tf.keras.backend.clear_session()
            # ckpt_manager.save()
```

**Comment by tsing-cv** [comment] 2019-06-25 03:37
leak has nothing to do with tf.cond, because i replace all tf.cond. But gpu using increasing.

**Comment by gadagashwini** [comment] 2019-06-26 05:17
@tsing-cv Will it possible to provide the minimal code snippet to reproduce the reported issue here. Thanks!

**Comment by gadagashwini** [comment] 2019-07-03 04:53
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-03 04:53 UTC
Labels: TF 1.13, comp:autograph, comp:ops, stat:awaiting response, type:support
