### ISSUE TITLE
Feature request : sparse tensor in map_fn

### ISSUE THREAD

**Issue by unrealwill** [tensorflow/tensorflow#21313] opened 2018-08-01 18:05 UTC
Hello,

I find that a class of useful ops is missing from Tensorflow : the ability to return outputs of various length while iterating over a tensor. Ideally it would support GPU.

I tried to return a sparse_tensor inside map_fn but currently if fails with (TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor )

It would be useful to have a way to raster, i.e., iterate over a tensor and apply a function which can return tensor of different shapes.

For example, input tensor could be the coords of the vertices of a triangle, output for each triangle the list of pixels which would be turned on. We can then use unsorted_segment_xxx on the joint list.

Another example would be for a tensor [[start1,end1],[start2,end2],...,[startn,endn]] -> concat( [range(start1,end1), range(start2,end2),..., range(startn,endn)] )

**Comment by tensorflowbutler** [comment] 2018-08-02 01:53
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by alextp** [comment] 2018-08-02 23:15
You could fake-return a SparseTensor by returning the tuple of its elements (index, values, and dense_shape) but this would likely fail because tf would be incapable of properly stacking the contents.

tf.map_fn wasn't really designed for the thing you want, though. It expects the shapes of the outputs to be uniform so it can stack them.

I think you should try implementing the behavior you want with tf.while_loop directly (tf.map_fn is just a thin wrapper over that anyway); maybe using tf.contrib.autograph to rewrite python code into an efficient while loop.

Closing as intended behavior.

**Closed by alextp** 2018-08-02 23:15 UTC
Labels: stat:awaiting response
