### ISSUE TITLE
[FusedBatchNormGradOp] Actual shapes of outputs NOT consistent with the shapes derived by shapeFn

### ISSUE THREAD

**Issue by dMokaMoka** [tensorflow/tensorflow#34780] opened 2019-12-03 02:22 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
> Binary
- TensorFlow version (use command below):
> 1.12.0
- Python version:
> 3.6.3

**Describe the current behavior**
For the operator FusedBatchNormGradOp, the `shape derived by shapeFn` is inconsistent with the `run-time shape of the actual output` when set `is_training = False` , and this difference is caused by the obvious code. I wonder if this is a bug? In fact, I rely on the shape derived by Tensorflow to build my network...

**Describe the expected behavior**
The shapefn derivation gives the same result as the runtime, unless it's an so called `unknown shape operator`.

**Code to reproduce the issue**
- Just as an example:
> the comment line illustrates the problem
```python
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops

y_backprop=np.random.random((32,32,2,1024)).astype(np.float32)
x=np.random.random((32,32,2,1024)).astype(np.float32)
scale=np.random.random((1024)).astype(np.float32)
reserve_space_1=np.random.random((1024)).astype(np.float32)
reserve_space_2=np.random.random((1024)).astype(np.float32)
fused_batch_norm_grad_result = gen_nn_ops.fused_batch_norm_grad(y_backprop, x, scale, reserve_space_1, reserve_space_2, epsilon=0.0001, data_format="NHWC", is_training=False)

print(fused_batch_norm_grad_result)
# printed: (32, 32, 2, 1024), (1024,), (1024,), (1024,), (1024,)
fused_batch_norm_grad_result=tf.Session().run(fused_batch_norm_grad_result)
for t in fused_batch_norm_grad_result:
    print(np.shape(t))
# printed: (32, 32, 2, 1024), (1024,), (1024,), (), ()
```

**Other info / logs**
The code that causes this problem is easily found in the Compute method of FusedBatchNormGradOp as follows:
```c
    ctx->SetOutput(1, scale_backprop);
    ctx->SetOutput(2, offset_backprop);
    ctx->SetConstantOutput(3, Tensor());
    ctx->SetConstantOutput(4, Tensor());
```
However, the following derivation is made in shapefn:
```c
  // Set the correct shapes for reserve_spaces
  // so that gradients can be performed when
  // the op is in a symbolic condition.
  if (is_training) {
    c->set_output(3, c->Vector(0));
    c->set_output(4, c->Vector(0));
  } else {
    c->set_output(3, c->Vector(channel_dim));
    c->set_output(4, c->Vector(channel_dim));
  }
```
I noticed the comment above that says this branch is to set the proper shape for reserve_spaces, but I can't understand what that really means...

**Comment by oanush** [comment] 2019-12-04 06:34
Issue replicating for Tf-1.12 and TF-1.15 also, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/5c84d5aabb47b85a792e7c0d474336bd/34780.ipynb) of colab.Thanks!

**Comment by saikumarchalla** [comment] 2020-04-24 08:39
@dMokaMoka  It seems the issue is fixed now.Could you please confirm still if you are facing the same issue?.Thanks!

**Comment by saikumarchalla** [comment] 2020-05-04 03:56
@dMokaMoka  Any updates regarding on this issue?.Thanks!

**Closed** 2020-05-18 04:44 UTC
Labels: TF 1.15, comp:ops, stalled, stat:awaiting response, type:bug
