### ISSUE TITLE
Tflite_convert error

### ISSUE THREAD

**Issue by savageyusuff** [tensorflow/tensorflow#20909] opened 2018-07-18 06:14 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: tensorflow 1.9
- **Python version**: Python 2.7

### Describe the problem
I have written a script to convert my frozen file(.pb) into a quantized tflite (quant.lite). I keep getting the error shown below. Anyone can help me? 

tflite_convert: error: --default_ranges_min and --default_ranges_max must be used together

### Source code / logs
`INPUT=INPUT
OUTPUT=output_node0
INFILE=./mobilenet_v1_0.25_32_2class_batchsize1_eyes.h5.pb
TYPE=QUANTIZED_UINT8
OUTFILE=./mobilenet_v1_0.25_32_2class_batchsize1_eyes.quant.tflite
IMAGE_SIZE=32
MEAN=128 
STD=128
MIN=0
MAX=6'
tflite_convert \
  --graph_def_file=$INFILE \
  --output_file=$OUTFILE \
  --output_format=TFLITE \
  --inference_type=$TYPE \
  --input_arrays=$INPUT \
  --output_arrays=$OUTPUT \
  --mean_values=${MEAN} \
  --std_dev_values=${STD} \
  --default_ranges_min=${MIN} \
  --default_ranges_max=${MAX} \
  --input_shapes=1,${IMAGE_SIZE},${IMAGE_SIZE},3`

**Comment by tensorflowbutler** [comment] 2018-07-18 19:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by savageyusuff** [comment] 2018-07-19 04:48
Bazel version: Not installed
CUDA/cuDNN version: release 9.0, V9.0.176
GPU model and memory:  GeFroce GTX 1080 8GB
Exact command to reproduce: No error. Quantized Tflite model produced

**Comment by shashishekhar** [comment] 2018-07-20 20:54
Looks like you are hitting this:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/python/tflite_convert.py#L203

do you have '\' at the end of line between default_ranges_min/max lines.

**Comment by savageyusuff** [comment] 2018-07-20 22:45
No, this is how i type for the tflite_convert command. 

tflite_convert \
--graph_def_file=$INFILE \
--output_file=$OUTFILE \
--output_format=TFLITE \
--inference_type=$TYPE \
--input_arrays=$INPUT \
--output_arrays=$OUTPUT \
--mean_values=${MEAN}  \
--std_dev_values=${STD} \
--default_ranges_min=${MIN} \
--default_ranges_max=${MAX} \
--input_shapes=1,${IMAGE_SIZE},${IMAGE_SIZE},3

**Comment by shashishekhar** [comment] 2018-07-20 23:39
@savageyusuff : Can you attach the original graph which you are trying to convert.

**Comment by savageyusuff** [comment] 2018-07-23 01:07
[graphfile.zip](https://github.com/tensorflow/tensorflow/files/2217607/graphfile.zip)

**Comment by shashishekhar** [comment] 2018-07-23 19:58
Thanks @savageyusuff I can reproduce the error with tflite_convert in Tensorflow 1.9, but when I build from master I see a different error.
@gargn : Any ideas about this error.

**Comment by gargn** [comment] 2018-07-25 21:16
This [bug fix](https://github.com/tensorflow/tensorflow/commit/b5fa781337ad8becaab893d001b04f2b995575b5#diff-89aadee1025f2c5098d86824417059c1)  wasn't included in 1.9. Please use the nightly build. You can do that by either using "pip install --upgrade tf_nightly" or follow the instructions [here](https://www.tensorflow.org/install/install_sources).

Doing this, results in another error (in the form of a suggestion to use a flag that is no longer supported). I will work on adding a fix for it in the coming days.

**Comment by gargn** [comment] 2018-07-27 20:01
The error regarding the unsupported flag mentioned in the previous comment has been fixed in the repository. Your model should convert successfully via `tflite_convert` after today's nightly build. Please reopen this bug if you encounter anymore errors using `tflite_convert` to convert this model.

**Closed by gargn** 2018-07-27 20:01 UTC
Labels: comp:lite
