### ISSUE TITLE
The same op seed gives different results in eager execution

### ISSUE THREAD

**Issue by batzner** [tensorflow/tensorflow#23882] opened 2018-11-20 13:29 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux openSUSE Leap 42.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.4
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: none
- GPU model and memory: none

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

```
import tensorflow as tf

tf.enable_eager_execution()

a = tf.random_uniform((3, ), seed=0)
b = tf.random_uniform((3, ), seed=0)
print(a)
print(b)
```

prints

```
tf.Tensor([0.10086262 0.9701668  0.8487642 ], shape=(3,), dtype=float32)
tf.Tensor([0.5689162  0.31256282 0.09009469], shape=(3,), dtype=float32)
```

When run in a graph, the output is the same.

**Describe the expected behavior**

I would have expected the output to be same in eager mode as well, just like in graph mode.

**Comment by wangpengmit** [comment] 2018-12-27 18:38
The behavior is caused by the fact that eager engine caches and reuses the same op node, and the random_uniform node has an internal state so multiple executions of it give different results. We are addressing this problem by a comprehensive overhaul in RFC [](https://github.com/tensorflow/community/pull/38). Please comment on that.

**Comment by wangpengmit** [comment] 2019-04-12 16:58
I'm closing this since the new RNGs (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/stateful_random_ops.py) are ready.

**Closed by wangpengmit** 2019-04-12 16:58 UTC
Labels: comp:eager
