### ISSUE TITLE
tf.gfile.Glob blocks forever

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#4753] opened 2016-10-04 12:10 UTC
### minimal reproducible example

``` python
import tensorflow as tf
tf.gfile.Glob('/path/to/imagenet/validation-*')
```
### environment info

Operating System: Ubuntu 14.04 
TensorFlow version (installed using the official binary): 0.11.0rc0
Python version: 3.4.3

**Comment by jonasrauber** [comment] 2016-10-04 12:14
Updates:

1. The problem exists in Python 2 and 3.
2. Seems to be a bug in 0.11.0rc0, because it does work with 0.10.

**Comment by tatatodd** [comment] 2016-10-05 00:13
@rohan100jain has done some work on gfile.Glob, can you take a look?  Thanks!

**Comment by rohan100jain** [comment] 2016-10-05 18:34
What filesystem do you have these stored on? I tried to reproduce this with the files local but didn't seem to be slow.

**Comment by jonasrauber** [comment] 2016-10-05 20:41
[https://en.wikipedia.org/wiki/IBM_General_Parallel_File_System](GPFS)

Python's builtin globbing seems to work fine.

**Comment by rohan100jain** [comment] 2016-10-05 22:13
I see... How is IsDirectory() implemented for that file system? How expensive is that call? Any pointers would be great to look into.

My hunch is that if that involves network I/O etc. to accomplish and we're doing that call serially in GetMatchingPaths() that would be the bottleneck. Multi-threading that piece of code should help... but I want to get to a reproducible scenario first so that we can compare the time taken before and after.

**Comment by jonasrauber** [comment] 2016-10-05 22:19
Thanks a lot for looking into this. I don't know how IsDirectory() is implemented or where to look it up, but I'll try to find something.

@rohan100jain Does your hypothesis explain why TensorFlow 0.10 seemed to work fine and 0.11.0RC0 does not?

**Comment by rohan100jain** [comment] 2016-10-05 22:25
**0.10/0.11:** Yeah.. Tensorflow 0.10 used an older version of GetMatchingFiles that just looked at the base directory for matches and couldn't recursive look into sub dirs etc. We updated that in 0.11.

**IsDirectory():** We have a plugin model for file systems... for a new file system like this I would imagine that someone would have implemented our file_system interface (tensorflow/core/platform/file_system.h). Would be good to see that implementation.

**Comment by jonasrauber** [comment] 2016-10-05 22:44
We haven't implemented anything particular for this, if that answers parts of your question?! Will try to get some details on our exact setup of the cluster filesystem tomorrow.

**Comment by rohan100jain** [comment] 2016-10-19 00:50
I created a patch that might help your use case. Can you try it out and see if there is any difference? 
[parallelize_matching.txt](https://github.com/tensorflow/tensorflow/files/537671/parallelize_matching.txt)

If this helps then I can test / make that change.

**Comment by jonasrauber** [comment] 2016-10-19 14:31
Unfortunately, it doesn't help. While the parallelization might make sense nevertheless, the main issue here seems to be that tf.gfile.Glob searches through all subfolders of "/path/to/imagenet", despite that a pattern like /path/to/imagenet/validation-* makes it impossible for any file in subfolders (that don't not start with validation) to match this pattern. Therefore, I think the solution is to make tf.gfile.Glob's recursion to stop earlier and not search in subfolders that already violate the pattern.

**Comment by jonasrauber** [comment] 2016-10-19 14:41
To make it more concrete (sorry I didn't post this earlier):
Running `tf.gfile.Glob('/path/to/imagenet/validation-*')` takes about 10 minutes when there exists a subfolder `/path/to/imagenet/raw-data/` that contains roughly 1000 folders with roughly 1000 images each. Clearly, it shouldn't matter whether there is a subfolder `raw-data` or not, because no file in that folder can ever match `'/path/to/imagenet/validation-*'`. When I move `raw-data` somewhere else (outside of the `imagenet` folder), tf.gfile.Glob runs as fast as Python's native globbing (milliseconds).

**Comment by rohan100jain** [comment] 2016-10-19 18:44
Okay yeah.. that makes a lot of sense... let me look into that a bit and perhaps come up with something better.

**Comment by gunan** [comment] 2016-10-23 05:32
@rohan100jain do we want to fix this in 0.11?
It looks like a new feature, so it might be better to add it in the next release.

**Comment by rohan100jain** [comment] 2016-10-24 17:27
yeah.. this might take a little time to fix anyways and won't really make any API changes.

**Comment by rohan100jain** [comment] 2016-10-28 16:47
I made commit https://github.com/tensorflow/tensorflow/commit/c15bb7b6f64fbc4bfd19aeccfd8b8df99012b74c

Let me know if that helps... it bails out on paths that have no chances to match.

**Comment by rohan100jain** [comment] 2017-01-06 01:31
I think this should be fixed now. Closing issue. Please reopen if its still a problem.

**Closed by rohan100jain** 2017-01-06 01:31 UTC
