### ISSUE TITLE
[Bug] embedding_lookup_sparse divide by zero when use mean combiner

### ISSUE THREAD

**Issue by wenmin-wu** [tensorflow/tensorflow#36359] opened 2020-01-31 04:52 UTC
I come across this issue with TF==1.14.
I found this bug was fixed in this PR: https://github.com/tensorflow/tensorflow/pull/21757.
However, when I checked the implementations in 1.13, 1.14 and 1.15 I found all of them implemented as following:

```
elif combiner == "mean":
        embeddings = math_ops.segment_sum(embeddings, segment_ids)
        weight_sum = math_ops.segment_sum(weights, segment_ids)
        embeddings = math_ops.div(embeddings, weight_sum, name=name)
```

Should this be fixed with `math_ops. div_no_nan ` ?

**Comment by Saduf2019** [comment] 2020-01-31 05:57
Please note,I have found the same issue for code in TF 2.x as well.

**Comment by gowthamkpr** [comment] 2020-02-03 23:51
@wenmin-wu Please take a look at this [comment](https://github.com/tensorflow/tensorflow/pull/21757#issuecomment-416835941) i.e.,
in the documentation of `tf.nn.embedding_lookup_sparse` its mentioned that **This op assumes that there is at least one id for each row in the dense tensor represented by sp_ids**

So, due to this, the change has not been merged.

**Comment by wenmin-wu** [comment] 2020-02-04 03:17
@gowthamkpr Even though this is true, the sum of weights can also be zero. 
I come across this problem because I want to embed user actions on items. Some people don't have any action on items. So for these users, I can only set `sp_ids=[0]`, `sp_weights=[0]`. With the current implementation, it will divide by 0.

**Comment by gowthamkpr** [comment] 2020-02-04 20:56
@wenmin-wu Can you please share a reproducible test case where the sum of weights are zero. Thanks!

**Comment by wenmin-wu** [comment] 2020-02-06 16:07
This issue is solved with `tf.nn.safe_embedding_lookup_sparse` in `1.14.0`. Here's the code snippets to produce the problem.

```Python
import tensorflow as tf

E = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
ids = tf.SparseTensor([[0,0]], np.array([0], dtype='int64'), dense_shape=[1,1])
weights = tf.SparseTensor([[0,0]], [0.0], dense_shape=[1,1])

with tf.Session() as sess:
    print(sess.run(tf.nn.embedding_lookup_sparse(E, ids, weights, combiner='mean')))
# ouput: [[nan nan nan]]

with tf.Session() as sess:
    print(sess.run(tf.nn.safe_embedding_lookup_sparse(E, ids, weights, combiner='mean')))

# output: [[0. 0. 0.]]
```

**Closed** 2020-02-06 16:11 UTC
Labels: TF 1.15, comp:ops, stat:awaiting response, type:bug
