### ISSUE TITLE
Tensorboard example not reproducing GPU profile

### ISSUE THREAD

**Issue by eduardo4jesus** [tensorflow/tensorflow#34844] opened 2019-12-05 00:05 UTC
When running this notebook on Colab:

https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

I am not getting the same profile output for profiling: on my side no GPU device is shown.

This is what is expected:
[![enter image description here][1]][1]

This is what I am getting:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/o5w0G.png
  [2]: https://i.stack.imgur.com/mDlXb.png

**Comment by gowthamkpr** [comment] 2019-12-05 00:36
I was not able to reproduce this issue using tf-nightly @eduardo4jesus Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/53d60d2765423c83e931981c486bb811/external-tensorboard_profiling_keras.ipynb). Thank you!

**Comment by eduardo4jesus** [comment] 2019-12-05 03:22
I just reproduced it using your gist.

I only have /host:CPU, as seen bellow.

<a href="https://ibb.co/vYTY4my"><img src="https://i.ibb.co/Dpvpfkc/Screen-Shot-2019-12-04-at-10-18-19-PM.png" alt="Screen-Shot-2019-12-04-at-10-18-19-PM" border="0"></a>

No /gpu as listed.

Here is my log/profile folder

https://drive.google.com/open?id=1whK5diV9pAd1Eems_-nfW_5YFlyz5zMh

**Comment by qiuminxu** [comment] 2019-12-07 01:08
I can reproduce the issue @eduardo4jesus mentioned using the gist.
Jose, do you know if this relates to the recent changes in profiling interface?

**Comment by dtim1985** [comment] 2020-01-29 13:51
Hi! We have the same issue with the profiler. Here some simpler gists that reproduce the problem:
TF 2.1-rc, no GPU in trace devices: https://colab.research.google.com/drive/1WLUSb9inSabMm4x7IdHuM5CEwJq9QX5j
TF 2.2 the nightly build, there is a GPU device in the trace: https://colab.research.google.com/drive/1GVlisiFGl5Hkjg0SIhCAQSDAKnJkN0HL

Though for TF 2.2 nightly build I wasn't able to run tensorboard, and also from the parsed trace I don't see any events with GPU device but maybe I read it wrong.

**Comment by trisolaran** [comment] 2020-01-29 18:16
I suspect that the libcupti.so is not located.
if I run !ldconfig -p | grep libcupti, I see nothing.

**Comment by trisolaran** [comment] 2020-01-29 19:11
colab team confirm this is LD_LIBRARY_PATH problem,
you can run this 
!ldconfig /usr/local/cuda-10.1/extras/CUPTI/lib64 /usr/local/lib /usr/local/lib/python3.6/dist-packages/ideep4py/lib
before profiling as a temporary fix.

**Comment by trisolaran** [comment] 2020-01-30 01:10
this should be fixed after cl/292248849 lands and docker is rebuilt.

**Closed** 2020-01-30 01:11 UTC
Labels: TF 2.0, comp:tensorboard, type:bug
