### ISSUE TITLE
Tensorflow 2.0 failed to get convolution algorithm

### ISSUE THREAD

**Issue by Atom-101** [tensorflow/tensorflow#27141] opened 2019-03-26 09:37 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0-alpha
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: virtualenv and pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA-10.0, cuDNN 7.4.2 and 7.5.0
- GPU model and memory: RTX 2080, 8 GB

**Describe the problem**

Installed tensorflow 2.0 using pip in a virtualenv. Trying to train a model gives the following error message(tried both cuDNN 7.4 and 7.5)

2019-03-26 14:44:26.468142: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-26 14:44:26.471383: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-03-26 14:44:26.580198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1009] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-26 14:44:26.580761: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x1e8c600 executing computations on platform CUDA. Devices:
2019-03-26 14:44:26.580775: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2019-03-26 14:44:26.593170: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696000000 Hz
2019-03-26 14:44:26.593891: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x1ee6d40 executing computations on platform Host. Devices:
2019-03-26 14:44:26.593903: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-26 14:44:26.594049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
totalMemory: 7.76GiB freeMemory: 7.21GiB
2019-03-26 14:44:26.594061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-03-26 14:44:26.594091: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-03-26 14:44:26.594521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-26 14:44:26.594530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 
2019-03-26 14:44:26.594534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N 
2019-03-26 14:44:26.594620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7014 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-03-26 14:44:26.890272: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-03-26 14:44:27.510334: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-26 14:44:27.514389: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 196, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1078, in __call__
    return self.conv_op(inp, filter)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 634, in __call__
    return self.call(inp, filter)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 233, in __call__
    name=self.name)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1130, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "/home/atom/PythonEnvs/Tensorflow_2_alpha/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]  

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Minimal code snippet which raises the error:
    tf.keras.layers.Conv2D(3,3,1)(tf.ones((1,5,5,3)))

**Comment by jvishnuvardhan** [comment] 2019-03-29 18:58
@Atom-101 I think root-cause of the error ("CUDNN_STATUS_INTERNAL_ERROR") is due to problem in initializing CUDNN. Could you run the same code on a cpu based virtual env and see whether the bug persists? There is solution to similar issue by another user [here](https://github.com/tensorflow/tensorflow/issues/14048). Please follow those instructions and let us know how it progresses. Thanks!

**Comment by Atom-101** [comment] 2019-03-30 07:26
The problem does not occur when using CPU. 
I checked out the issue you referenced. I'm not really having a problem related to paths(I can import tensorflow just fine). As for running python as root, as suggested by one user, I haven't tried it yet. Although, I never needed to run python as root for tensorflow-gpu 1.12 or lower, so I'm not really hopeful about it.

**Comment by jvishnuvardhan** [comment] 2019-03-30 16:11
@Atom-101 did you install tf_gpu version in VM or tf_cpu version? Could you share a code to reproduce the bug? The one line code was working well for me. Thanks!

**Comment by Atom-101** [comment] 2019-03-30 17:11
I installed tf_gpu version in a virtual environment. Not a VM. Tf_gpu gives the aforementioned issue. Right now I have installed tf_cpu. Tf_cpu works without issues. 
As for code to reproduce the bug, any simple snippet that runs a convolution on any matrix will give the error. If you can run my snippet without issues, your cuDNN is working correctly, I guess.

**Comment by jvishnuvardhan** [comment] 2019-04-17 21:09
@Atom-101 Yes. In order to run tf_gpu in vitrual env, you need to install NVIDIA driver, CUDA and cuDNN. I can run any convolution code without any issue. Please check other issues here in GitHub and Stackoverflow to install CUDA and cuDNN correctly. Please close the issue. thanks!

**Closed** 2019-04-18 05:15 UTC
Labels: 2.0.0-alpha0, comp:ops, stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by MokkeMeguru** [comment] 2020-02-27 12:12
This problem may cause with tensorflow's docker (2.1.0-gpu-py3) in the below host

- OS: 5.5.2-1-MANJARO
- Cuda: 10.1
- cuddn: 7.6.5

Tensorflow is affected by HOST OS?

**Comment by rajprasad001** [comment] 2021-02-09 08:00
For those who are facing issues regarding the above error, I sorted it just by installing CuDNN version compatible with the CUDA already installed in the system.

1. - This suitable version can be downloaded from the website 'https://developer.nvidia.com/rdp/cudnn-archive'. You might need Nvidia account for it. This will be easily created by providing mail id and filling a questionnaire.
2. - To check the CUDA version, run `NVCC --version`.
3. - Once the suitable version is downloaded, extract the folder from the zip file. 
4. - Go to the bin folder of the extracted folder. copy the `cudnn64:7.dll` and paste it in the CUDA's bin folder. In my case, the location where Cuda is installed is `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin`.
5. - This would most probably solve the problem.

My system details:

1. Windows 10
2. CUDA 10.0
3. TensorFlow 2.0
4. GPU- Nvidia GTX 1060
