### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'ADD' version '1'

### ISSUE THREAD

**Issue by kavyaprasad22** [tensorflow/tensorflow#47334] opened 2021-02-23 03:57 UTC
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, with MCU Expresso
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.3.1
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33, etc.): IMX RT 1060

**Describe the problem**
The application as per [this code](https://github.com/kavyaprasad22/MNV3) is saved as .pb file and converted to .tflite using [this convert.py](https://github.com/kavyaprasad22/MNV3/blob/main/conver.py). After uploading this to IMX RT 1060, the debugger throws an ```ERROR: Didn't find op for built-in opcode 'ADD' version '1'```. Is the opcode ADD failed to  be converted by the tflite or is it because of any missing header files in the client end?

**Please provide the exact sequence of commands/steps when you ran into the problem**
```
python train_RJ.py
python conver.py
``` 
after this converted to *.h using ``` xxd -i model.tflite > model.h``` 
and uploaded with MCU Xpresso to IMX RT 1060 using tensorflow_lite_cifar_10 example provided under eiq folder from SDK 2.9.1 build from [this builder](https://mcuxpresso.nxp.com/en/builder?hw=EVK-MIMXRT1060).

**Comment by abattery** [comment] 2021-02-23 05:18
Could you share which ops are being included in your model? At least, could you share at least the operation name of the problematic operation node?

**Comment by kavyaprasad22** [comment] 2021-02-23 19:31
@abattery My opcode for 'ADD' seems to be causing the issue. All my layers for the model are defined in dpd_format.py in this [link](https://github.com/kavyaprasad22/MNV3). Please let me know if any additional information is needed.

**Comment by abattery** [comment] 2021-02-23 22:43
Is it possible to share your model to us? The reproducible steps to create a model also would be helpful.

**Comment by Arjun-NA** [comment] 2021-02-26 03:07
Hi @abattery, I was working with @kavyaprasad22. The code of the model is already there in the link provided by @kavyaprasad22  in the reply 

> @abattery My opcode for 'ADD' seems to be causing the issue. All my layers for the model are defined in dpd_format.py in this [link](https://github.com/kavyaprasad22/MNV3). Please let me know if any additional information is needed.

Do you want the *.tflite file of the model?

Thanks,
Arjun.

**Comment by kavyaprasad22** [comment] 2021-02-26 03:33
This [link](https://github.com/kavyaprasad22/MNV3/tree/main/tflite) has the files for running the model on client side (IMXRT 1060).

**Comment by abattery** [comment] 2021-02-26 05:00
Generally, there are two TF versions, one for executions and one for conversion. Could you make sure that the TF version used for executions should have the same TF version with the one for conversion or higher? We do not guarantee the compatibility that the TF for executions has a lower version than the TF for conversion.

**Comment by Arjun-NA** [comment] 2021-02-27 03:13
Hi @abattery  both training and conversion was done using TensorFlow 2.3.1 CPU versions.

**Comment by abattery** [comment] 2021-02-27 04:21
Is the installed TF version of IMX RT 1060 TF 2.3.1 or higher?

To make sure whether the converted model is correct or not, could you verify that the converted model is runnable  in the machine done at the training and conversion stage?

**Comment by Arjun-NA** [comment] 2021-02-27 05:13
Hi,
We downgraded the tensor flow in the host PC to 2.3.1 so that it matches with with the version mentioned in the SDK provided by the NXP for the Target IMX RT 1060 found [here](https://mcuxpresso.nxp.com/en/builder?hw=EVK-MIMXRT1060).

Thanks,
Arjun.

**Comment by abattery** [comment] 2021-02-27 06:24
Once all the TF versions is aligned, it will not encounter the versioning issues. After the alignment, is it possible to run the model on the device?

**Comment by abattery** [comment] 2021-02-27 06:55
If possible, could you share the converted model and the full error log messages to us for debugging?

**Comment by Arjun-NA** [comment] 2021-03-15 22:23
Hi, 

We solved the error by adding the missing opcodes in the IMX microcontroller software part.

It was not the error of TensorFlow but of the target.

Thank you,
Arjun.

**Comment by sanatmpa1** [comment] 2021-11-03 13:47
@kavyaprasad22,

As @Arjun-NA has pointed out that the issue is solved and also its not from TF end, Can you confirm if we are good to close this issue? Thanks!

**Closed** 2021-11-17 14:36 UTC
Labels: stat:awaiting response, type:support, stalled, comp:lite, comp:micro, TF 2.3
