### ISSUE TITLE
xla kernel load error

### ISSUE THREAD

**Issue by SunNy820828449** [tensorflow/tensorflow#38785] opened 2020-04-22 06:46 UTC
W0422 13:19:03.825152 25290 tf_model.cpp:326] TF error: 2 root error(s) found.
(0) Internal: Unable to load kernel 'fusion_22'
[[{{node cluster_86_1/xla_run}}]]
[[cluster_86_1/merge_oidx_0/_3]]
(1) Internal: Unable to load kernel 'fusion_22'
[[{{node cluster_86_1/xla_run}}]]
0 successful operations.
0 derived errors ignored.
W0422 13:19:04.673285 25290 tf_model.cpp:326] TF error: 2 root error(s) found.
(0) Internal: Unable to load kernel 'fusion_22'
[[{{node cluster_86_1/xla_run}}]]
[[cluster_86_1/merge_oidx_0/_3]]
(1) Internal: Unable to load kernel 'fusion_22'
[[{{node cluster_86_1/xla_run}}]]

========================
we used c api to load model from graph_def. the tf version is 1.14. this error ocurs when the online system try to load new model to replace the old one.the online system update the tf model for every two hours. we can't replicate this issue on our offline system.

**Comment by Saduf2019** [comment] 2020-04-22 11:32
closing this as duplicate of #38784

**Closed by Saduf2019** 2020-04-22 11:32 UTC
Labels: type:others
