### ISSUE TITLE
tensorflow on Python 3.7

### ISSUE THREAD

**Issue by dataneupane** [tensorflow/tensorflow#21205] opened 2018-07-28 12:33 UTC
I upgraded to python 3.7. 

Now when I try to run it in jupyter notebook or in terminal, I receive following errors: 

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-39d68f4585c2>", line 4, in <module>
    import tensorflow as tf

  File "/usr/local/lib/python3.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                             ^
SyntaxError: invalid syntax

**Comment by tensorflowbutler** [comment] 2018-07-29 00:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ppwwyyxx** [comment] 2018-07-29 02:21
duplicate of #20517

**Closed** 2018-07-29 21:32 UTC
Labels: stat:awaiting response
