### ISSUE TITLE
Tensorboard slow with S3

### ISSUE THREAD

**Issue by ShashiUpadhyay** [tensorflow/tensorflow#22773] opened 2018-10-05 18:16 UTC
TensorBoard version - 1.5.1
TensorFlow version if different from TensorBoard - No
OS Platform and version (e.g., Linux Ubuntu 16.04) - Tensorflow installed on EC2 instance of AWS

Description of issue:
I have placed all event files in S3 bucket of AWS cloud. And its content size will be around 6 GB. The problem which I am facing is that the tensorboard is very slow in scanning all the event files. It is taking more than an hour. Is there a way to reduce the processing time.

**Comment by tensorflowbutler** [comment] 2018-10-06 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ymodak** [comment] 2018-10-08 19:07
I am closing this issue since it belongs to Tensorboard related query. I would encourage you to post it on [Tensorboard repository](https://github.com/tensorflow/tensorboard/issues) if you haven't already.

**Closed by ymodak** 2018-10-08 19:07 UTC
Labels: stat:awaiting response
