### ISSUE TITLE
tf.get_variable() cannot recognize existing variables

### ISSUE THREAD

**Issue by mightyroy** [tensorflow/tensorflow#1325] opened 2016-02-28 09:16 UTC
`with tf.variable_scope("conv", reuse=True):
    x = tf.get_variable("w",[1])`

The above code cannot recognize an existing variable, but clearly the existing variable was created before as print out of the variable .name shows : `conv/w:0`

I get an error when using tf.get_variable:
`ValueError: Under-sharing: Variable conv/w does not exist, disallowed. Did you mean to set reuse=None in VarScope?`

If set to reuse=None...
`with tf.variable_scope("conv", reuse=None):
    x = tf.get_variable("w",[1])`

Then it creates another variable with .name  `conv/w_1:0`

It's a bug! Now I have 2 variables, with names `'conv/w'`  and `'conv/w_1'`

**Comment by mightyroy** [comment] 2016-02-28 17:56
I check the `self._vars = {}` in python/ops/variable_scope.py, got it to print the `_vars`, and the dictionary was empty `{}`. None of the variables created previously got stored in `_vars`

**Comment by mightyroy** [comment] 2016-02-28 18:08
Creating the variable the usual way using `tf.Variable` does not add the variable name to `self._vars` of `tf.variable_scope`

**Comment by lukaszkaiser** [comment] 2016-02-29 22:28
Indeed -- variables created in other ways than with tf.get_variable(...), esp. by the lower-level tf.Variable, are not added or recognized by variable_scope. This is partly intentional (as some special variables may need to be treated specially) and partly a result of how the variable sharing process developed.

My suggestion for you would be to always use tf.get_variable if you're relying on it later -- why not?

**Comment by mightyroy** [comment] 2016-02-29 23:35
Thanks!

**Comment by mightyroy** [comment] 2016-02-29 23:37
Perhaps this should be made part of the documentation.

**Comment by lukaszkaiser** [comment] 2016-02-29 23:39
Definitely! Re-opening so we don't forget it, thanks!

**Comment by gear** [comment] 2016-03-10 02:29
Thank you for the answer. I had the same problem. 
On the other hand, I would like to add a note that if `tf.get_variable_scope().reuse_variable()` is (accidentally)  used without a context manager `with tf.variable_scope(...):`, it will set any variable scope's `reuse` to True.

```python
with tf.variable_scope('foo'):
  print (tf.get_variable_scope().reuse)
  print (tf.get_variable_scope().name)
  # >>> False
  # >>> foo

# Set reuse without a context manager
tf.get_variable_scope().reuse_variables()

# Any variable scope's reuse is changed to True
with tf.variable_scope('foo'):
  print (tf.get_variable_scope().reuse)
  # >>> True

with tf.variable_scope('other_name'):
  print(tf.get_variable_scope().reuse)
  # >>> True
```

**Comment by lukaszkaiser** [comment] 2016-03-10 03:24
Indeed - any sub-scope of a reusing scope is also reusing. So just setting things with .reuse_variables() can be a bit dangerous. We could forbid it and have only context, but on the other hand it's convenient from time to time.

**Comment by mightyroy** [comment] 2016-03-10 05:59
Actually why not just make all variables callable with `tf.get_variable()`? It would be so much more convenient and there wont be any confusion.

**Comment by rlrs** [comment] 2016-04-29 09:41
Some input on this issue, variable loaded by `tf.Saver.restore()` are also not recognized by `tf.get_variable()`. The cleanest method I could think of for accessing individual variables loaded as such was to create a dictionary with the variable names:

```
saved = tf.train.import_meta_graph('save.ckpt.meta')
saved.restore(self.sess, 'save.ckpt')
saved_dict = {}
for x in tf.trainable_variables():
  saved_dict[x.name] = x
# access e.g. saved_dict['some/scope/weight:0']
```

**Comment by mightyroy** [comment] 2016-05-01 06:19
Yeah I got this bug too! Variables loaded by tf.Saver.restore() don't work with tf.get_variable()!

**Comment by girving** [comment] 2016-06-06 21:36
@lukaszkaiser: Are you planning to make the documentation fix, or should I mark this contributions welcome or close?

**Comment by lukaszkaiser** [comment] 2016-06-06 22:11
I think there is a true bug here, not a documentation problem. Variables loaded with saver should be imported to with with get_variable. It is being addressed in tf.learn (and also in the context to make partitioned variables work ok). I think Illia was working on that, but I'm not sure how far it got.

**Comment by girving** [comment] 2016-06-06 22:13
@ilblackdragon: Reassigning to you; feel free to adjust if that's wrong.

**Comment by mlinxiang** [comment] 2016-07-04 01:18
did this problem fix ? my code used get_varaible(), and  validation when train is ok, but when i restore from checkpoint, predict will always the same weight, not correct
@girving

**Comment by MingStar** [comment] 2016-07-21 11:42
+1, got the same problem symptom as @mlinxiang

**Comment by eringrant** [comment] 2016-07-26 19:41
+1. I have the same problem as @rlrs,, @mightyroy, @mlinxiang & @MingStar: I can't load variables with tf.Saver.restore() if they were created with tf.get_variable().

I can easily use the workaround described by @rlrs for some of the variables, but I can't find an easy way to do the same with variables that were created with a call to tf.nn.rnn(...), which uses tf.get_variable().

**Comment by MingStar** [comment] 2016-07-27 00:59
I have actually got this problem fixed for my case. 

The way I did it was to construct the graph, restore the checkpoint file (of tf variables) and run the session in the SAME thread.

**Comment by tatatodd** [comment] 2016-08-15 23:14
@ilblackdragon Friendly ping, please update this bug with the current status.  Thanks!

**Comment by thatsvishalhere** [comment] 2016-09-26 14:01
I'm facing the same issue. I was wondering if somebody has found a way around it. I can't really use the trainable variables hack that @rlrs suggested as I'm also using the default RNN code of tensorflow and don't really want to hack into the rnn definitions for reusing the variables. It would be great if somebody can suggest a way around this without having the need to hack into the rnn code definition in tensorflow. Thanks!

**Comment by ilblackdragon** [comment] 2016-10-28 04:14
I'm not exactly sure where the problem occurs.

If you are using tf.learn - currently you need to have the code around to restore the model. E.g. recreate `Estimator` with the same `model_fn` and pass the `model_dir` for the directory with checkpoints.

The same thing is true if you are using `Saver` - you should recreate graph as well first and then run `Saver.restore`.

There is `saved_model` functionality is built, to be able to load packaged graph and checkpoints without having code. If that's what you want.

**Comment by thatsvishalhere** [comment] 2016-10-31 21:47
@ilblackdragon While following the directions as given on https://www.tensorflow.org/versions/master/api_docs/python/state_ops.html#exporting-and-importing-meta-graphs, when I use the code:

`new_saver = tf.train.import_meta_graph('my-save-dir/my-model-10000.meta')`
`new_saver.restore(sess, 'my-save-dir/my-model-10000')`

and then try to reuse the variables, it says the variables aren't defined. I can see the variable names in `tf.trainable_variables()` but still it's giving the error about variables being undefined. On the other hand, when I don't use the metagraph and just use `tf.train.Saver()` instead of `tf.train.import_meta_graph()`, the variables seem to have loaded. I've recreated the graph for both the above cases before restoring the model. Sorry if I'm really wrong, I initially felt that by loading the metagraph, I can directly reuse the variables without having to recreate the graph. I felt the metagraph functionality was initially created in order to remove the requirement of recreating the graph.  I'm currently just using the `tf.train.Saver()` in order to load my variables. Let me know if I can be of any help by providing any more details.

Thanks!

**Comment by IsaacBanjo** [comment] 2016-11-08 03:51
@lukaszkaiser  Thanks for your comments and I found the same phenomenon (not retrievable by get_variable) with any defining method other than tf.get_variable(). As noticing you are one of the main contributor of TF, may I kindly ask you 2 questions:
1. It seems even in the same scope, if using tf.Variable([1], name='weights') to define multiple variables (every parameter are the same including the string name), there won't be any conflict; the resulted variables actually will have different string names, whereby the system will add postfix to each string such as weights1, weights2, ... So my question is, does this imply that the variables defined using tf.Variable() are local variables instead of global (static) variables defined by tf.get_variable()?
2. If the answer to question 1 is True, then if we define a variable with tf.Variable() in a function, and when each time this function gets called, will a new local variable be created that does not store previous state? Does that mean when defining a neural network graph, we HAVE TO USE tf.get_variable() to define weights and biases, so that the weights can be shared and previous state got kept? However, I saw some examples that use tf.Variable in graph definition function and the training also works...
I am so confused.
Thank you very much for your help!

**Comment by lukaszkaiser** [comment] 2016-11-08 04:05
(1) Yes: tf.Variable is a low-level function that will always create a variable node. It is used inside tf.get_variable. The variables can be local and global -- the only difference is that it's low-level. I'd recommend to never use it.

(2) It's not about local and global, tf.Variable is just lower-level. It's used inside tf.get_variable, so in principle you can do everything just with it, yes. But it will not respect variable scope, not use the initializer you defined there, not do partitioning, and not do bookkeeping. It's just low-level. Use tf.get_variable to avoid problems.

**Comment by IsaacBanjo** [comment] 2016-11-08 19:08
@lukaszkaiser  Thanks for your response! As for the local/global issue, may I confirm that 
1. Anything defined with tf.get_variable() is guaranteed to be global, so even it's defined in a function it can be retrieved, shared and its old information kept (Just like a static variable in C++)? 
2. While with tf.Variable(), it can be either local or global, but I am just wondering that, if I define a graph's weights using tf.Variable() in a function, and not setting it as a class member, it cannot be retrieved by tf.get_variable(), and each time we run that function, it creates a new variable, how can the session.run(optimizer, feed_dict={...}) retrieve the unique variable and update its value based on its old value (I heard it works in this way)?

Sorry to bother with many questions. Hope these are the last two, otherwise I got to read through the source code. I just hope to get everything clear other than blindly following some example to use tensorflow.
Thanks again!

**Comment by lukaszkaiser** [comment] 2016-11-08 19:25
I think you have a different notion of local and global than the TF one (which only concerns distributed training). In the notion you say, I think you're right with (1) -- but it's hard for me to be clear about what "global" means for you. All nodes in TF are part of the graph, so they are global in this sense.

If you define something with tf.Variable, it will not be retrieved by tf.get_variable, that's right. It still has a node name in the graph, so you can feed to it -- but you need to be careful which suffix tf.Variable added to the name and be sure to use exactly this suffix.

**Comment by IsaacBanjo** [comment] 2016-11-08 19:39
@lukaszkaiser I think I kind of get the big idea. So previously when I say "global" I mean its life time does not end when the function exits, unlike a variable defined in stack in C/C++. It is either defined in stationary memory or in heap, because our initialize_graph function is just a function, every variable is defined inside the function, if it is a stack variable, after calling the initialize_graph function, those variables are freed, the session.run() function won't see/retrieve it. That's why I say the reason to use tf.get_variable() is to not define it in stack, and make it global for later use.
Now I kindly get it that, even we define those variables WITHIN A Function, those variables are actually attached to a hidden "graph" class, so they are global and life persisting. Thus the session.run() function can somehow retrieve them by calling graph.some_weights/biases. 
In terms of the suffix thing, truely that I noticed the system will add a suffix to the string name we gave when defining, yielding a string_suffix name in reality.

**Comment by lukaszkaiser** [comment] 2016-11-08 19:49
You wite: "those variables are actually attached to a hidden "graph" class, so they are global and life persisting" -- and that's true. It might be one of the harder things to grasp about TF, but this is the case, there is a global graph and all nodes are global as they belong there.

The get_variable is in this sense just a bookkeeping function that tried to help you not get lost in this large global graph. It can help you make 4 copies of your model to run on 4 gpus but still sharing variables, things like that. Hope this helps :).

**Comment by IsaacBanjo** [comment] 2016-11-08 20:11
@lukaszkaiser  Definitely very helpful. In terms of the "hidden graph", would you please point out in which code line does the variables be attached to the graph class(belong it)? Is the graph just the entire program space so that in any code space, in any function, any variable defined as a "variable" type other than a "tensor" type are automatically belonging to the "graph" class? Danke!

**Comment by lukaszkaiser** [comment] 2016-11-08 20:21
Every TensorFlow operation (tf.Variable, tf.add, even t1 * t2 when t1 and t2 are tensors) creates, in the background, an op that is stored in the graph. So if you write y = t1 * t2  then you're creating an Mul-Op in the global TF graph. It all happens in the background, you can look in python/framework/ops.py if you want to know more. The graph is created (and can be changed) in the with tf.Graph().as_default(): context.

**Comment by IsaacBanjo** [comment] 2016-11-15 22:22
@lukaszkaiser OK, I read through the tf.Variable class in github. Combining what you said above, can I summarize in the way below:
1. In any code line, any function, or in global space, All the TF operations, including tf.some_operation and primitive operation such as t1 * t2 if t1 or t2 is a tensor, will be automatically added to the graph. But operation such as np.arange(10).reshape((2,5)), a * 3, will NOT be added to the graph.

2. In any code line, any function, or in global space, All the variables defined with tf.Variable() or tf.get_variable(), during their construction, will be automatically added to the graph. They will also be added to the global_variables list, some will be added to the trainable_global_variables also if trainable is not set to False.

3. In any code line, any function, or in global space, All the tensor type such as defined by placeholder, or as an output of some operation on variables/tensors such as t3 = t1 * t2 will be added to the graph, and there will be a new tensor with automatically generated name such as "mul_10:0" created in the global graph whereby t3 will be pointing to this new created tensor. In comparison, non-tf specific variables such as a = np.arange(10).reshape((2,5)), b = a * 3, will NOT be added to the graph.

All the variables, tensors and operations THAT ARE ON GRAPH are global, can be retrieved, and life persisting until training finished. I do not know how to retrieve variables not defined by get_variable(), but there should be some way to retrieve it, like graph.GraphKeys.GLOBAL_VARIABLES['variable_string_name']? The get_variable() function facilitates the weights sharing among different GPUs/Machines because it applied a string name check before re-defining in other gpus/machines, while other variable definition methods are used to define outputs/place_holders of layers, which will be labeled with new string names in different GPUs/Machines, so that they can hold separate values in distributed training process.

The graph can contain multiple paths, such as a = placeholder(...name='foo'), b = a * 3, c = placeholder(...name='bar'), d = c + 4. when we do sess.run(b, feed_dict={a:...}), the tensor is like water flows on graph wherever it can reach. For the path it can't reach such as c->d, it just has nothing happens. So far b is a python variable pointing to a tf tensor probably named as "mul", If I add one more line at the end saying b = d * 7,  then it will create a new tensor called "mul1" in global graph too, and the python variable b will now point to this tensor, but the previous "mul" tensor will persist in graph, just no python variable pointing to.

Thanks and I actually tried to send you email regarding this post because it seems it digresses from the topic of this post, but I don't want you to feel abrupt on receiving stranger's email.

**Comment by SJTUzhanglj** [comment] 2016-12-14 05:54
So the phenomenon that variables restored by Saver.restore func are not retrievable by get_variable is bug for fix?

**Comment by fengsky401** [comment] 2017-01-17 02:15
@lukaszkaiser  When I use tf.get_variable instead of tf.Variable(), my training process is not very good. Specifically, I think the parameters does not update in every epoch. I have experimented it  in the program publiced in tensorflow tutorial, it does has something wrong. Have you experiment it in your program? or I use it in a wrong way?

**Comment by fengsky401** [comment] 2017-01-17 02:16
@MingStar   I came across the same thing, how do you fix it latter?

**Comment by lukaszkaiser** [comment] 2017-01-17 05:40
The function tf.get_variable() returns a tf.Variable, it has generally no influence on how it is updated later. One thing that might cause differences in training is initialization: what values are you initializing your tf.Variable with? What initializer are you using with tf.get_variable?

**Comment by fengsky401** [comment] 2017-01-17 06:14
@lukaszkaiser I initialized the parameters like these:
def weight_variable(name,shape):
	initial=tf.truncated_normal(shape,stddev=0.1)
  	return tf.Variable(initial,name)
def weight_variable(name,shape):
	return tf.get_variable(name=name,shape=shape,initializer=tf.random_normal_initializer())

**Comment by lukaszkaiser** [comment] 2017-01-17 06:21
Looks like in the first case you initialize with standard deviation of 0.1 (and truncate, but that's probably less important), and in the second case you use the default standard deviation of 1.0 in tf.random_normal_initializer. That's probably too high a deviaiton for your model. Try using the same initializer in the second case, i.e., change the last line to `return tf.get_variable(name=name,shape=shape,initializer=tf.truncated_normal_initializer(stddev=0.1))`. Hope that helps!

**Comment by fengsky401** [comment] 2017-01-17 07:08
@lukaszkaiser  It is very helpful, the program works well now.Thank you soooooo much！

**Comment by jrajagopal** [comment] 2017-01-22 14:34
@IsaacBanjo @lukaszkaiser @SJTUzhanglj I am running into the same issue with tf.get_variable not recognizing variables restored by tf.train.import_meta_graph(). Kindly advise how to proceed.

**Comment by jrajagopal** [comment] 2017-01-22 21:38
@eringrant Not sure if you are still seeing this problem. I am able to save variables created with tf.get_variable() using tf.train.saver.

**Comment by jrajagopal** [comment] 2017-01-24 00:03
An update - to run inference, I am now using tf.get_variable to initialize the model parameters (randomly), and am then overwriting the values for each parameter with the learned model loaded using tf.train.import_meta_graph(). Clearly a workaround and sub-optimal, but necessary given the situation.

**Comment by VerityStone** [comment] 2017-01-25 18:30
@jrajagopal were you able to do that with an RNN model? I'm using tf.nn.bidirectional_dynamic_rnn() and struggling to restore the weights any sense...

**Comment by jrajagopal** [comment] 2017-02-02 23:49
@VerityStone Yes, I am using the same. I had to load the variables into a dictionary where each variable is referenced by its name. At the same time, I use the same code which contains tf.nn.bidirectional_dynamic_rnn() for inference, which means it will create the same set of variables but with an "_1" suffix in the name. It will also initialize each variable randomly.

Then I overwrite the value of each "_1" variable thus initialized, with the value of the corresponding variable in the dictionary, i.e., the ones without the "_1" . To do that, I use "for v in tf.trainable_variables()" along with v.assign(). 

Just keep in mind that this creates two superflous copies of the parameters in memory, the one that is loaded and the one in the dictionary. So, if you are running a multi-layer net, with large node sizes and input and/or output projections, you are looking at many GBs and may run out of memory.

**Comment by IsaacBanjo** [comment] 2017-02-03 00:27
@jrajagopal I did not use the skflow package at that time, instead I wrote my own graph which worked, but I heard the skflow people have updated their library and they re-defined the restore function.

**Comment by jrajagopal** [comment] 2017-02-03 16:31
@IsaacBanjo Ok good to know - thanks!

**Comment by aselle** [comment] 2017-03-09 17:56
It seems like this is working as intended, so I am automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by pankajvela** [comment] 2017-06-04 02:55
Bumped into the same problem as many of you: Variables loaded by tf.Saver.restore() don't work with tf.get_variable() . What's the final solution ?

**Comment by davidpham87** [comment] 2017-06-17 12:36
I am running into a similar problem: 

0. In the contrib.learn.Estimator`  class, define some variable say `W`.
1. Export a `contrib.learn.Estimator` with `export_savedmodel`. End the python process.
2. Restart a new python process, and import the `SavedModel` back into python with `saved_model.load`
3. `tf.get_variable` do not recognize the variable `W` defined in step 0.

Is it really working as intended?

**Comment by rustyoz** [comment] 2017-06-22 07:36
Hello, 
I think this issue still persists. 
On loading a file I can print out a list of variables from the checkpoint file using the below code. 
```
checkpoint_file=tf.train.latest_checkpoint("model/.")
print(checkpoint_file)
saver =	tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
saver.restore(sess,checkpoint_file)
for t in tf.global_variables():
	print(t.name)
```
Resulting in:
```
model/.\acgan-1-0
global_step:0
generator/biases:0
generator/weights:0
```
It then fails to load using:
```
def Generator(Z, outputsize, batchsize, reuse=None):
	print("Generator")
	for t in tf.global_variables():
		print(t.name)
	with tf.variable_scope("generator") as scope:
		if reuse:
			scope.reuse_variables()

		inputsize =  Z.shape[1]
		G_b1 = tf.get_variable("biases", [outputsize],initializer=tf.constant_initializer(0))
```

Which results in:
```
ValueError: Variable generator/biases does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

**Comment by aselle** [comment] 2017-07-07 19:05
@lukaszkaiser , any suggestions?

**Comment by lukaszkaiser** [comment] 2017-07-07 19:10
This is a very old problem with saving, Sherry worked on it a while ago, no idea why it was dropped.

**Comment by michaelisard** [comment] 2017-07-10 16:46
@sherrym do you have any idea of the current status of this?

**Comment by JinmingZhao** [comment] 2017-07-27 15:56
I have the same problem as @rustyoz .

**Comment by kashefy** [comment] 2017-09-07 09:13
Variables restored from the saver are assigned a different output index. So the variable I'm creating using tf.get_variable ends up being a completely different one.

`with tf.variable_scope("var_scope"):
    W = tf.get_variable('W', shape=[784, 10], initializer=tf.random_normal_initializer(stddev=0.1))`

If I restore variables from the saver I end up with two sets of variables:
The first: 'var_scope/W'
And the second restored by the saver: 'var_scope/W_1' (Notice the added output index)
I don't get why the saver won't use the variable defined by `tf.get_variable()`

I uploaded this small program to demonstrate the effect. If anyone wants to try it out. [here](https://gist.github.com/kashefy/9f8c57a7b1eb41b8491d8c37b94b0f82).

So far I've only managed to restore variables defined with `tf.get_variable()` by calling graph.get_tensor_by_name(full_var_scope_and_var_name_and_output_index) after restoring them from the saver.

Thanks!

**Comment by tensorflowbutler** [comment] 2017-12-22 07:41
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-12 19:00
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-06 07:43
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by michaelisard** [comment] 2018-02-06 16:35
Are people still experiencing this problem?

**Comment by tensorflowbutler** [comment] 2018-02-21 13:20
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by cohimame** [comment] 2018-02-21 14:31
@michaelisard, yes, i do experience )

**Comment by tensorflowbutler** [comment] 2018-03-08 19:29
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by rbedi** [comment] 2018-03-14 05:33
Also having this issue. Any updates?

**Comment by Dateios** [comment] 2018-03-21 13:28
`tf.variable_scope().reuse_variables()
tf.variable_scope().reuse_variables()`

change to

`with tf.variable_scope("model") as scope:
  scope.reuse_variables()
with tf.variable_scope("generator") as scope:
  scope.reuse_variables()`

it works. I'm new in tensorflow. Now I can't tell what happened.

**Comment by poxvoculi** [comment] 2018-04-06 20:11
@sherrym Could you update with the status of this issue?

**Comment by tensorflowbutler** [comment] 2018-05-10 01:14
Nagging Assignee @sherrym: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:14
Nagging Assignee @sherrym: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by v-mostafapour** [comment] 2018-06-04 10:30
insert  tf.reset_default_graph() at the beginning of the block.
be running the script multiple times on the same graph,  you are adding the variables to the graph for each run...

**Comment by tensorflowbutler** [comment] 2018-06-19 18:41
Nagging Assignee @sherrym: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-04 18:38
Nagging Assignee @sherrym: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by azraelkuan** [comment] 2018-07-09 06:01
sample proble, use `import_meta_graph` can not get variable by `tf.get_variable()`

**Comment by constantinembufung** [comment] 2018-07-11 17:40
just run tf.reset_default_graph()

**Comment by tensorflowbutler** [comment] 2018-07-26 19:10
Nagging Assignee @sherrym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-14 19:46
Nagging Assignee @sherrym: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Nagging Assignee @sherrym: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jamesqo** [comment] 2018-09-09 23:15
I'm having this problem too...

**Comment by tensorflowbutler** [comment] 2018-09-24 12:46
Nagging Assignee @sherrym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-09 18:42
Nagging Assignee @sherrym: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-24 12:39
Nagging Assignee @sherrym: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-10-31 15:47
@sherrym  - Any update on this ?

**Comment by pablomainar** [comment] 2018-11-01 14:32
Any news on this? When I load variables from the saver they are not recognized by tf.get_variable, which creates a new variable with the same name plus '_1'. How can I get the reference to the variables loaded from the saver?

**Comment by tensorflowbutler** [comment] 2018-11-19 23:21
Nagging Assignee @sherrym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:47
Nagging Assignee @sherrym: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2019-03-22 20:47
@mightyroy Is this issue resolved? Please close If it was resolved already. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-20 15:25
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-07-20 15:25 UTC
Labels: type:support

**Comment by wenting-zhao** [comment] 2019-10-27 20:36
Tested with v1.15 and this issue still exists.

**Comment by jvishnuvardhan** [comment] 2019-10-29 21:56
@wenting-zhao Please create a new issue by providing a standalone code to reproduce the issue. thanks!
