### ISSUE TITLE
Group convolutions UnimplementedError for nightly build

### ISSUE THREAD

**Issue by ahsabali** [tensorflow/tensorflow#29005] opened 2019-05-24 19:41 UTC
I am getting the following error message while running the following code using the nightly version of tensorflow 1.14.1-dev20190524. When will this feature be available?

Code:
`weights = tf.ones([3,3,1,3])`
`X = tf.ones([3,1024,1024,3])`
`Y = tf.nn.conv2d(X, weights, [1, 1, 1, 1], "VALID")`

Error:
UnimplementedError: Generic conv implementation does not support grouped convolutions for now.
	 [[node Conv2D_4 (defined at <ipython-input-13-3298cb87493e>:4) ]]

**Comment by gadagashwini** [comment] 2019-05-27 06:08
@ahsabali I try reproducing the issue with tf-nightly-1.14.1.dev20190524 but the code executed without any error. Can you try once again and let us know if that still throws an error. Thanks!

**Comment by ahsabali** [comment] 2019-05-27 19:17
Here is the complete code snippet that is generating the error:

`weights = tf.ones([3,3,1,3])`
`X = tf.ones([3,1024,1024,3])`
`Y = tf.nn.conv2d(X, weights, [1, 1, 1, 1], "VALID")`
`sess = tf.Session()`
`sess.run(Y)`
`sess.close()`

**Comment by gadagashwini** [comment] 2019-05-28 09:24
I am able to reproduce the mentioned issue with tf-nightly-1.14.1.dev20190524.

**Comment by alextp** [comment] 2019-05-29 21:31
@aaroey can you take a look?

**Comment by aaroey** [comment] 2019-05-29 21:42
@reedwm could you help to take a look?

**Comment by reedwm** [comment] 2019-05-30 16:57
Grouped convolutions are currently only supported on GPUs, not CPUs. You are using a grouped convolution because the input channel dimension of 3 (`X.shape[3]`) does not match the filter in-depth dimension of 1 (`weights.shape[2]`). @chsigg, any idea when support is coming for CPUs?

Also the error message is a bit unclear. I'll fix the error message.

**Comment by chsigg** [comment] 2019-06-03 11:43
Thanks for improving the error message. I have no idea if/when grouped
convs are supported on CPU.

**Comment by lgeiger** [comment] 2019-12-30 00:02
For now grouped convolutions on CPU are only supported using [XLA](https://www.tensorflow.org/xla).

You can try it by using `@tf.function(experimental_compile=True)` (see [this colab](https://colab.research.google.com/drive/1M9jxNv3Y3a2lGlNLNg-rvdS7YxuN-Y1p)).

**Comment by SchernHe** [comment] 2021-03-12 17:37
Hey, are there any news regarding when grouped convolutions are available for CPU? Using tensorflow 2.4.0 and it seems that it is still not available.

I can use it with `@tf.function(experimental_compile=True)`, but only with multiple retracing warnings.

**Comment by reedwm** [comment] 2021-03-12 18:23
@sanjoy @cheshire could we use `@tf.function(experimental_compile=True)` by default for grouped convolutions, so that we don't have to implement this on the CPU?

**Comment by sanjoy** [comment] 2021-03-17 07:19
That sounds reasonable, though the performance can get pretty bad if there is a lot of dynamism in the shapes.

@d0k WDYT?

**Comment by sanjoy** [comment] 2021-03-17 07:19
CC @tatianashp

**Comment by d0k** [comment] 2021-03-17 10:40
> That sounds reasonable, though the performance can get pretty bad if there is a lot of dynamism in the shapes.

You get both recompilation on every shape change and an unoptimized implementation from XLA:CPU. It should be good enough for completeness but it won't be a great user experience.

Also note that XLA jitting isn't really supported on Windows, there's some investment needed to make that work and keep it working.

In the long term this would be a great use case for CPU kernelgen, but there's a lot of unknowns there when it comes to convolutions, it's not something that can be done in a couple of days of hacking.

**Comment by cheshire** [comment] 2021-03-17 23:22
> Also note that XLA jitting isn't really supported on Windows, there's some investment needed to make that work and keep it working.

We already advertise JITing as a "core" feature, so I don't think this should be a factor in making a decision.

**Comment by nukes** [comment] 2021-03-19 14:05
Can anyone make a group conv on cpu ?

**Comment by ezhulenev** [comment] 2021-03-19 21:11
I have a pending PR for that, should be submitted soon, although currently it has few unresolved TODOs that are needed to get to top performance.

**Comment by nukes** [comment] 2021-03-24 12:48
> I have a pending PR for that, should be submitted soon, although currently it has few unresolved TODOs that are needed to get to top performance.

Looking forward...

**Comment by reedwm** [comment] 2021-03-24 17:52
Closing, as this was fixed in 7b8db6083b34520688dbc71f341f7aeaf156bf17.

**Closed by reedwm** 2021-03-24 17:52 UTC
Labels: comp:ops, type:feature

**Comment by ashutosh1919** [comment] 2021-07-24 09:57
Anyone who is facing the same issue even after using tf version `2.6.0rc1`, you need to pass the batch size of exactly 1. If you pass more than 1, then it won't work on CPU.
