### ISSUE TITLE
MKL Build Failing with new PR Merge

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/tensorflow#21642] opened 2018-08-16 02:06 UTC
Hello,

It looks like with the latest changes to the BUILD file under `tools/pip_package`, the references to MKL DNN is not being picked up any longer, because there's no `intel_mkl_ml` folder under `third_party`. There are `mkl` and `mkl_dnn` but not `intel_mkl_ml` under `third_party`, and that being said, it looks like PR #408 which has this MKL "fix" actually passed all the build tests (red X next to the commit)...

For what it's worth, I have both MKL and MKL-DNN built in my environment with the correct paths set, but TF always seems to want to build the MKL-DNN libraries themselves, so if I could even explicitly point to my environment's MKL library files, then that'd also work.

## Build command:
```
echo "startup --batch" >>/etc/bazel.bazelrc && \
    echo "build --spawn_strategy=standalone --genrule_strategy=standalone" >>/etc/bazel.bazelrc && \
    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
    apt-get update && apt-get install -y bazel  && rm -rf /var/lib/apt/lists/* && \
    ldconfig && \
    pip uninstall -y tensorflow-tensorboard tb-nightly tf-nightly tensorflow && \
    cd /opt && \
    git clone https://github.com/tensorflow/tensorflow.git && \
    cd /opt/tensorflow && \
    # cp /opt/tensorflow/third_party/mkl/LICENSE /opt/tensorflow/third_party/mkl_dnn/LICENSE && \
    /bin/bash ./configure \
    && \
    bazel build \
    --config=mkl --config=opt  \
    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    --copt=-msse4.2 --copt=-msse4.1 --copt=-mavx --copt=-msse2 --copt=-msse3  \
    --copt=-O3 --copt=-mfpmath=both \
    --copt="-DMKL_LP64" \
    --copt="-fPIC" \
    --linkopt="-lmkl_gf_lp64" \
    --linkopt="-lmkl_gnu_thread" \
    --linkopt="-dl" \
    --linkopt="-lpthread" \
    --linkopt="-lmkl_core" \
    --linkopt="-lm" \
    --linkopt="-lmkl_rt" \
    --linkopt="-lmkldnn" \
    tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip install --no-deps /tmp/pip/tensorflow-*.whl 
```

## Error:
```
/opt/tensorflow/tensorflow/tools/pip_package/BUILD:206:1: no such package 'third_party/intel_mkl_ml': BUILD file not found on package path and referenced by '//tensorflow/tools/pip_package:build_pip_package'```

**Comment by tensorflowbutler** [comment] 2018-08-16 12:39
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment] 2018-08-16 14:40
@gunan could you take a look or redirect as necessary? Thanks!

**Comment by sadatnfs** [comment] 2018-08-19 23:03
Thanks @skye!

@gunan it looks like there's more than one place where `intel_mkl_ml` is being referred to, whereas everywhere else they don't? https://github.com/tensorflow/tensorflow/search?q=third_party%2Fintel_mkl_ml&unscoped_q=third_party%2Fintel_mkl_ml

**Comment by gunan** [comment] 2018-08-19 23:08
I think @tomerk made this change.
Tomer, could you take a look?

**Comment by tomerk** [comment] 2018-08-19 23:37
Hi @gunan, I don't recall ever making any changes to intel_mkl_ml, mkl, or mkl_dnn

**Comment by gunan** [comment] 2018-08-20 00:05
I am really sorry, read the author user id wrong. @jktomer made the change in https://github.com/tensorflow/tensorflow/commit/00590b6973cb071744cdd1335a161b17866dea87

**Comment by sadatnfs** [comment] 2018-08-20 17:01
Hmm but there's still like 5 referenes to `intel_mkl_ml` (see link in my previous post). Shouldn't all those scripts be fixed as well?

**Comment by freedomtan** [comment] 2018-08-21 01:29
I ran into this problem yesterday, 'git pull' just now, it seems the problem is fixed in https://github.com/tensorflow/tensorflow/pull/21640 or say c09a0176

**Comment by sadatnfs** [comment] 2018-08-21 02:34
Yep it's building for me now all good. Still concerned about the references

**Comment by sadatnfs** [comment] 2018-08-21 19:07
I'll wait for a bit to see if any of the devs have anything to point out regarding the references to `intel_mkl_ml` in the C code, and then close the issue since the primary problem is solved.

**Comment by gunan** [comment] 2018-08-21 19:27
Ping, @jktomer
Could you weight in about https://github.com/tensorflow/tensorflow/commit/c09a0176795a321b13caaa3126541290c235c95f ?

**Comment by sadatnfs** [comment] 2018-08-29 02:39
Build failing again: #21938

**Closed** 2018-09-24 04:30 UTC
Labels: stat:awaiting tensorflower
