### ISSUE TITLE
issues in the tflite_camera_example on IOS

### ISSUE THREAD

**Issue by liyancas** [tensorflow/tensorflow#18379] opened 2018-04-10 11:46 UTC
------------------------

### System information
- **Xcode 9.3 and Mac OS is 10.13.4  **:
- **TensorFlow r1.2**:
- **iPhone 7 plus**:

### Describe the problem
NSString* graph_path = FilePathForResourceName(model_file_name, @"tflite");
  model = **tflite::FlatBufferModel::BuildFromFile**([graph_path UTF8String]);
  if (!model) {
    LOG(FATAL) << "Failed to mmap model " << graph_path;
  }
  LOG(INFO) << "Loaded model " << graph_path;
  model->error_reporter();
  LOG(INFO) << "resolved reporter";

### Source code / logs
After "tflite::FlatBufferModel::BuildFromFile" is excuted, and it returns
nnapi error: unable to open library libneuralnetworks.so
Loaded model 1resolved reporter(lldb) 

Does anyone know how to solve this issue? Thanks in advance.

**Comment by glenn-jocher** [comment] 2018-04-10 16:11
This is a duplicate of issue #18343

**Comment by asimshankar** [comment] 2018-04-11 01:05
Thanks @glenn-jocher - closing this since it is a duplicate.

**Closed by asimshankar** 2018-04-11 01:05 UTC
