### ISSUE TITLE
Memory leaks when using tf.strings.split in map_func for tf.data.Dataset.map with eager execution.

### ISSUE THREAD

**Issue by workingloong** [tensorflow/tensorflow#35152] opened 2019-12-16 12:26 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): 2.1.0rc1
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A 
- GCC/Compiler version (if compiling from source): N/A 
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A 

**Describe the current behavior**
If we use `tf.strings.split` in map_func to process each element in tf.data.Dataset, the used memory grows when we iterate the dataset and the used memory is not freed after iteration. What's more, the used memory continues to grow greatly if we repeatedly create the same tf.data.Dataset instance. However, the used memory keeps stable if we use tf.py_function to implement the split logic.
![image](https://user-images.githubusercontent.com/18071380/70906668-debb4780-2041-11ea-945c-bf2a05cbb637.png)

**Describe the expected behavior**
The used memory when iterating the dataset should be freed and should grow the create the same tf.data.Dataset instance.

**Code to reproduce the issue**
#### Experiment
```python
import psutil
import tensorflow as tf
import pandas as pd
import numpy as np

FEATURE_COUNT = 400

# mock feature names and feature data
def gen_feature_names(feature_count):
    feature_names = []
    for i in range(feature_count):
        feature_names.append("f{}".format(i))
    return feature_names


def gen_samples(feature_names, sample_count=5000):
    samples = []
    for _ in range(sample_count):
        feature_str = ""
        for name in feature_names:
            feature_str += "{};".format(np.random.random())
        feature_str += str(np.random.randint(0,2))
        yield feature_str
        
def dataset_fn(dataset):
    def _py_parse_data(record):
        record = record.numpy()
        feature_labels = bytes.decode(record).split(";")
        return feature_labels

    def _parse_data(*record):
        feature_values = record[0:-1]
        features = {}
        for i,feature_name in enumerate(FEATURE_NAMES):
            features[feature_name] = feature_values[i]
        label = tf.strings.to_number(record[-1], tf.int64)
        return features, label
    
    tout = [tf.string] * FEATURE_COUNT
    tout.append(tf.string)
    
    dataset = dataset.map(
        lambda record: tf.py_function(
            _py_parse_data,
            [record],
            tout
        )
    )
    dataset = dataset.map(_parse_data)
    dataset = dataset.shuffle(buffer_size=100)
    return dataset


def dataset_fn_using_split(dataset):
    def _parse_data(record):
        feature_label = tf.strings.split([record], sep=';')[0]
        feature_values = feature_label[0:-1]
        features = {}
        for i, feature_name in enumerate(FEATURE_NAMES):
            features[feature_name] = feature_values[i]
        label = feature_label[-1]

        return features, label
    
    dataset = dataset.map(_parse_data)
    dataset = dataset.shuffle(buffer_size=100)
    return dataset

def create_dataset(feature_names, using_split=True):
    dataset = tf.data.Dataset.from_generator(
        lambda : gen_samples(feature_names), tf.string
    )
    if using_split:
        dataset = dataset_fn_using_split(dataset)
    else:
        dataset = dataset_fn(dataset)
    dataset = dataset.batch(512)
    return dataset


def view_used_mem():
    used_mem = psutil.virtual_memory().used
    print('used memory: {} Mb'.format(used_mem / 1024 / 1024))

FEATURE_NAMES = gen_feature_names(FEATURE_COUNT)

# Test used memory by using tf.strings.split in `map_func`
FEATURE_NAMES = gen_feature_names(FEATURE_COUNT)

start_time = time.time()
for i in range(4):
    print("loop {}".format(i))
    view_used_mem()
    dataset = create_dataset(FEATURE_NAMES, using_split=True)
    for batch in dataset:
        pass
print("Consume time : {}".format(time.time() - start_time))
print("end")
view_used_mem()

# Test used memory by using `tf.py_function`
start_time = time.time()
for i in range(4):
    print("loop {}".format(i))
    view_used_mem()
    dataset = create_dataset(FEATURE_NAMES, using_split=False)
    for batch in dataset:
        pass
print("Consume time : {}".format(time.time() - start_time))
print("end")
view_used_mem()

**Other info / logs**
We encounter this issue when building inputs pipeline using `tf.data.Dataset` in [ElasticDL](https://github.com/sql-machine-learning/elasticdl)

**Comment by gadagashwini** [comment] 2019-12-17 11:05
I could reproduce the issue with Tf 2.1.
Please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/4184e630cb4e5ff57c6bc0b5c3a800f3/untitled313.ipynb). Thanks!

**Comment by jsimsa** [comment] 2019-12-21 00:45
When I change the order in which the `tf.strings.split` and `tf.py_function` experiments are executed, I see fast memory growth for `tf.py_function` experiment and not the `tf.strings.split`. This suggests that the memory behavior you are observing is unrelated to `tf.strings.split` vs `tf.py_function` -- as it occurs irrespective of which experiment you run first -- and is more likely related to caching of objects inside of TensorFlow's implementation and the deferred nature of Python's garbage collection.

**Comment by workingloong** [comment] 2019-12-23 08:02
But, I also see fast memory growth for the only `tf.strings.split` experiment and slow memory growth for the only `tf.py_function` experiment. 
Using `tf.py_function` in `dataset_fn`, I see fast memory growth when the first dataset variable is created and slow memory growth when other dataset variables are created.
![image](https://user-images.githubusercontent.com/18071380/71344373-4f5fe800-259d-11ea-9445-5ea64c0bf1a6.png)

Using `tf.strings.split` in `dataset_fn`, I see fast memory growth when every dataset variable is created.
![image](https://user-images.githubusercontent.com/18071380/71344476-9948ce00-259d-11ea-86a1-9ba868120c3e.png)

**Comment by jsimsa** [comment] 2019-12-30 19:40
What happens when you run the `tf.strings.split` for 20 epochs? Does the memory use plateau?

Can you reproduce the issue without `tf.data` (simply wrapping your `_parse_data` for both with and without `strings.split` in `tf.function` and applying it to elements generated by `gen_samples` in your inner loop)?

**Comment by workingloong** [comment] 2020-01-06 03:34
The memory use does not plateau when running for 20 epochs.
```
loop 0 
Used memory:  303.28515625 Mb
loop 1
Used memory:  457.7109375 Mb
loop 2
Used memory:  591.4921875 Mb
loop 3
Used memory:  714.41796875 Mb
loop 4
Used memory:  797.890625 Mb
loop 5
Used memory:  898.14453125 Mb
loop 6
Used memory:  965.6875 Mb
loop 7
Used memory:  1083.3515625 Mb
loop 8
Used memory:  1150.41015625 Mb
loop 9
Used memory:  1254.76171875 Mb
loop 10
Used memory:  1310.88671875 Mb
loop 11
Used memory:  1299.33203125 Mb
loop 12
Used memory:  1377.38671875 Mb
loop 13
Used memory:  1420.7109375 Mb
loop 14
Used memory:  1489.80859375 Mb
loop 15
Used memory:  1587.70703125 Mb
loop 16
Used memory:  1652.21484375 Mb
loop 17
Used memory:  1672.3828125 Mb
loop 18
Used memory:  1680.796875 Mb
loop 19
Used memory:  1739.9296875 Mb
```

However, the memory use plateaus if I use `dataset.repeat(20)` not create dataset instance for each epoch like:
```python
FEATURE_NAMES = gen_feature_names(FEATURE_COUNT)

start_time = time.time()
dataset = create_dataset(FEATURE_NAMES, using_split=True)
dataset = dataset.repeat(20)

num = 0
for batch in dataset:
    num += 1
    if num % 10 == 0:
        view_used_mem()
    pass
```
![image](https://user-images.githubusercontent.com/18071380/71793526-2dc02f80-3078-11ea-8a37-8140b8eac2f3.png)

So, i think the reason may be that TF retraces the graph in dataset map function when i create dataset instance for each epoch and does not release the graph even if i delete the dataset instance by `del dataset`.

**Comment by jsimsa** [comment] 2020-01-08 17:48
@kkimdev could you try running this through your tooling for checking leaks of Python objects? Thank you.

**Comment by kkimdev** [comment] 2020-01-08 18:35
- using_split=True https://paste.googleplex.com/6404943990751232
- using_split=False https://paste.googleplex.com/5515399179272192

It looks both are leaking.

`_GeneratorState` reference graph for "using_split=True" case.
https://graphviz.corp.google.com/svg?graph_id=cfe456a9651f00885270edff9f269e4f

In the graph, I see `_py_funcs_used_in_graph` which is unexpected for "using_split=True" case.  Is there any place that tf.data uses py_function underneath?

**Comment by jsimsa** [comment] 2020-01-08 18:41
`from_generator` uses PyFunc

**Comment by kkimdev** [comment] 2020-01-08 19:03
If I apply this commit https://github.com/tensorflow/tensorflow/commit/3b74a63c0f7e1ec4618563958079f538cd9de076 then seems there is no more leak https://paste.googleplex.com/4555021112836096

But that commit unfortunately got reverted https://github.com/tensorflow/tensorflow/commit/8a0cd10c92f9c62f3dfbd261f0481fad93a6ae8c .  Sorry but re-landing that doesn't seem easy at this point and I don't have eta yet.

**Comment by jvishnuvardhan** [comment] 2020-10-08 07:27
@workingloong Looks like this was resolved in recent `tf-nightly`. I ran the loop 40 time and don't see memory increase. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/aa5e7857d176b5319390bba324a21c1d/untitled313.ipynb). 

Please verify once and close the issue if this was resolved for you. Thanks!

```
loop 0
used memory: 772.234375 Mb
loop 1
used memory: 772.10546875 Mb
loop 2
used memory: 772.71875 Mb
loop 3
used memory: 774.7421875 Mb
Consume time : 58.04884696006775
end
used memory: 776.3984375 Mb
loop 0
used memory: 776.3984375 Mb
loop 1
used memory: 780.72265625 Mb
loop 2
used memory: 778.90625 Mb
loop 3
used memory: 778.30078125 Mb
loop 4
used memory: 778.12109375 Mb
loop 5
used memory: 778.40625 Mb
loop 6
used memory: 777.7109375 Mb
loop 7
used memory: 776.3046875 Mb
loop 8
used memory: 6938.546875 Mb
loop 9
used memory: 778.83984375 Mb
loop 10
used memory: 778.28515625 Mb
loop 11
used memory: 778.0703125 Mb
loop 12
used memory: 776.921875 Mb
loop 13
used memory: 776.703125 Mb
loop 14
used memory: 776.51171875 Mb
loop 15
used memory: 776.61328125 Mb
loop 16
used memory: 776.2578125 Mb
loop 17
used memory: 775.0234375 Mb
loop 18
used memory: 774.71875 Mb
loop 19
used memory: 774.38671875 Mb
loop 20
used memory: 773.9375 Mb
loop 21
used memory: 772.953125 Mb
loop 22
used memory: 775.59375 Mb
loop 23
used memory: 776.03515625 Mb
loop 24
used memory: 777.40625 Mb
loop 25
used memory: 776.89453125 Mb
loop 26
used memory: 776.49609375 Mb
loop 27
used memory: 777.05078125 Mb
loop 28
used memory: 776.2578125 Mb
loop 29
used memory: 779.3359375 Mb
loop 30
used memory: 778.94140625 Mb
loop 31
used memory: 779.13671875 Mb
loop 32
used memory: 778.921875 Mb
loop 33
used memory: 779.0546875 Mb
loop 34
used memory: 778.93359375 Mb
loop 35
used memory: 778.9921875 Mb
loop 36
used memory: 777.9140625 Mb
loop 37
used memory: 778.5625 Mb
loop 38
used memory: 777.80859375 Mb
loop 39
used memory: 777.97265625 Mb
Consume time : 1582.0767142772675
end
used memory: 778.08203125 Mb
```

**Comment by jvishnuvardhan** [comment] 2020-10-15 22:16
I am closing this issue as this was resolved. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2020-10-15 22:16 UTC
Labels: Fixed in Nightly, TF 2.1, comp:eager, type:performance
