### ISSUE TITLE
Tensorflow 1.10.1 incompatible with latest numpy version 1.15.1 

### ISSUE THREAD

**Issue by alexforever86** [tensorflow/tensorflow#21939] opened 2018-08-29 03:21 UTC
Installed TF with following command `pip3 install tensorflow`. The installation is successful but gave me this error.
`tensorflow 1.10.1 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.15.1 which is incompatible.`

Do I need to downgrade my numpy version?

**Comment by iteachmachines** [comment] 2018-08-29 06:41
Yeah if the given error shows "numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.15.1" this then  i think you should downgrade it once and check if it works successfully if not then try to update by the command " conda update --all

**Comment by facaiy** [comment] 2018-08-29 22:01
duplicate of 21866

**Closed** 2018-08-31 01:42 UTC

**Comment by bellahcenmarwane** [comment] 2018-10-14 10:38
I was able to solve this with :
 sudo pip3 uninstall numpy
 pip install numpy==1.14.5

**Comment by Afef00** [comment] 2019-01-20 00:57
If i have to use numpy 1.11.0 what version of tensorflow  should i use ?

**Comment by ayesha168** [comment] 2019-09-06 10:20
how can I solve this problem ?
distributed 1.21.8 requires msgpack, which is not installed.
tensorflow 1.14.0 has requirement numpy<2.0,>=1.14.5, but you'll have numpy 1.14.3 which is incompatible.
Installing collected packages: wrapt, tensorflow, deephyp, setuptools
  Found existing installation: wrapt 1.10.11
Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
You are using pip version 10.0.1, however version 19.2.3 is available.
