### ISSUE TITLE
No OpKernel was registered to support Op 'GatherV2' with these attrs.

### ISSUE THREAD

**Issue by cruigo93** [tensorflow/tensorflow#30641] opened 2019-07-12 10:51 UTC
Hi there! Facing with this problem after training pytorch model, converting to pb file and runing on android with tensorflow 1.13.1. Can anybody guide me what I am doing wrong?

**Comment by ravikyram** [comment] 2019-07-15 13:28
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github ](https://github.com/tensorflow/tensorflow/issues/new/choose)new issue template.
Also, can you elaborate more on your issue.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by cruigo93** [comment] 2019-07-16 04:17
@ravikyram I trained unet model on pytorch (1.0), converted it to onnx using api provided by pytorch which was following by converting to pb using tensorflow (1.13). And finally, after trying to run it on android (tensorflow also 1.13) it gave this error. I didnt compile anything, just used provided api. Other details: Ubuntu 18 x64.

        val graph = tensorFlowInference.graph()
        graph.operations().forEach {
            println(it.name())
        }
        tensorFlowInference.feed(inputName, imageNormalizedPixels,
                1L, imageSize, imageSize, COLOR_CHANNELS.toLong())
        tensorFlowInference.run(arrayOf(outputName))
        tensorFlowInference.fetch(outputName, results)

**Comment by ravikyram** [comment] 2019-07-16 09:03
@cruigo93 
Just to verify did you convert .pb model into TF lite to run it on android. Thanks!

**Comment by cruigo93** [comment] 2019-07-16 09:57
Just used pb without converting into tflite

**Comment by ravikyram** [comment] 2019-07-16 12:18
Please, go through the below links if it helps you.Thanks!
https://www.tensorflow.org/lite
https://www.tensorflow.org/lite/examples

**Comment by ravikyram** [comment] 2019-07-23 06:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-23 06:18 UTC
Labels: TF 1.13, stat:awaiting response, type:support
