### ISSUE TITLE
Feature Columns stock example fails on GPU

### ISSUE THREAD

**Issue by johnkabler** [tensorflow/tensorflow#29445] opened 2019-06-05 16:12 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No. this is a stock example, see collab notebook here to reproduce 
https://colab.research.google.com/drive/1O8dCWeYBVjFEax-ZK1XbJE_vfEzB2Ieq
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): '2.0.0-dev20190605'
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Collab

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
model.fit fails in the stock example with the following error:
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Expected D2 of index to be 2 got 3 at position 1
	 [[node sequential/dense_features_6/age_bucketized_X_thal_indicator/SparseCross (defined at <ipython-input-20-bf1fb22dfeb0>:14) ]]
  (1) Invalid argument:  Expected D2 of index to be 2 got 3 at position 1
	 [[node sequential/dense_features_6/age_bucketized_X_thal_indicator/SparseCross (defined at <ipython-input-20-bf1fb22dfeb0>:14) ]]
	 [[sequential/dense_features_6/age_bucketized_X_thal_indicator/SparseToDense/_56]]
0 successful operations.
0 derived errors ignored. [Op:__inference_keras_scratch_graph_2134]

**Describe the expected behavior**

**Code to reproduce the issue**
https://colab.research.google.com/drive/1O8dCWeYBVjFEax-ZK1XbJE_vfEzB2Ieq

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ghego** [comment] 2019-06-08 04:33
Following

**Comment by achandraa** [comment] 2019-06-10 12:15
I was able to reproduce the issue on Colab (GPU) with TF 2.0.0-dev20190610 but the code ran fine on TF 2.0.0-alpha0.

**Comment by jvishnuvardhan** [comment] 2019-07-24 21:09
@johnkabler I could not reproduce the issue with the latest `tf-nightly`. This might have been resolved in `tf-nightly-gpu-2.0-preview==2.0.0.dev20190724`. Thanks!

I am closing the issue. Please feel free to reopen the issue if the bug persists. Thanks!

**Closed by jvishnuvardhan** 2019-07-24 21:09 UTC
Labels: 2.0, comp:keras, stat:awaiting tensorflower, type:bug
