### ISSUE TITLE
Segmentation fault error when running Makefile

### ISSUE THREAD

**Issue by AntonioDeVita** [tensorflow/tensorflow#36061] opened 2020-01-20 12:41 UTC
@tensorflow/micro

- Host OS Platform and Distribution: Windows 10
- TensorFlow installed using "git clone https://github.com/tensorflow/tensorflow.git"
- Tensorflow version: 2.1.0
- Target platform: Laptop

Hello, I'm following the tutorial provided on the book "TinyML - Machine Learning with TensorFlow Lite on Arduino and Ultra-Low-Power Microcontrollers". The aim is to run the "hello world" test. The problem is that I got a "Segmentation fault" error when I run the command:

mingw32-make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

In the following I attach a screenshot of the error:
![Immagine](https://user-images.githubusercontent.com/59959289/72727161-87e9e600-3b8a-11ea-8fe5-b8f994d61ab5.png)

How can I fix this issue?

**Comment by AntonioDeVita** [comment] 2020-01-20 15:29
I obtained more info and it seems to be related to C++ issue. I attach the picture. How can I fix that?

![Immagine](https://user-images.githubusercontent.com/59959289/72738466-ecfd0600-3ba1-11ea-8d93-90412d382935.png)

**Comment by AntonioDeVita** [comment] 2020-01-23 11:02
Waiting for someone to answer, I tried a trivial solution. I a modified the file micro_test.h at line 95. I removed the %s and I only used "Testing" as argument. Now I have not errors, and what I see is this:

![Immagine](https://user-images.githubusercontent.com/59959289/72979016-bc061680-3dd7-11ea-88b2-5961ca56e98f.png)

Can I consider that as the test was successfully passed?  If so, it seems clear that the problem is related to the %s format which is incompatible with the *char in C++.  So, how can I fix that?

**Comment by MeghnaNatraj** [comment] 2020-02-06 00:47
@AntonioDeVita it looks like the issue is fixed indeed after you remove the %s sign. This issue does not occur in Linux whether you keep the %s sign or not, and so we never encountered this issue before.

Thank for reporting and providing us with a possible fix. We'll look into this issue and fix this on our end.

**Closed by MeghnaNatraj** 2020-02-06 00:47 UTC
Labels: TF 2.1, comp:lite, comp:micro, type:support
