### ISSUE TITLE
TF1 Keras Model Errors on Loading using TF2 - IndexError: list index out of range

### ISSUE THREAD

**Issue by HollowMan6** [tensorflow/tensorflow#43561] opened 2020-09-25 10:10 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu **18.04**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.1**
- Python version: **3.7.3**

**Describe the current behavior**

When When trying to load the sequential model [here](https://github.com/vogon101/skincancer/blob/master/models/model_6_combined_2_DA.h5) using `tf.keras.models.load_model` in **TF 2.3.1**, an error is thrown at the following location:

```bash
~/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py in _should_skip_first_node(layer)
   1031   return (isinstance(layer, Functional) and
   1032           # Filter out Sequential models without an input shape.
-> 1033           isinstance(layer._layers[0], input_layer_module.InputLayer))
   1034 
   1035 
IndexError: list index out of range
```

The model is believed to be trained using keras and under TF1.9, and the structure of the model can be found [here](https://github.com/vogon101/skincancer/blob/master/src/sandbox/ml_lib/combined_model_v2.py), and here's [the code for training](https://github.com/vogon101/skincancer/blob/master/src/sandbox/v6_combined_model_v2.py).

Here you can find the full stack trace and running code under TF 2.3.1: https://colab.research.google.com/drive/1Lfo0O7D0cM8EtR0h6noqCoWqoqf8bzAD?usp=sharing

Then I downgraded to TF 2.2 and 2.1 with the same code above, it threw the error just as #35934 .

Then I downgraded to TF 2.0, the code was executing indefinitely. Finally I had to manually stop it:

```bash
/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py in IsMapping(o)
   2569 
   2570     """
-> 2571     return _pywrap_tensorflow_internal.IsMapping(o)
   2572 
   2573 def IsMappingView(o):
KeyboardInterrupt: 
```

Here you can find the full stack trace when I stopped the code under TF 2.0: https://colab.research.google.com/drive/1fCR-ci05NuYhQ8M9O2lRVG0F0YzI9Ggo?usp=sharing

Then I had no choice but to use TF 1.15.4 and Keras 2.3.1, and finally it worked out fine, inputs, outputs, summary etc. are all parsed correctly, as well as being able to run data through the model: https://colab.research.google.com/drive/1XaRMeiT1SefS6Q10wsa0y9rEercyFlCR?usp=sharing

**Describe the expected behavior**

I hope the Bug can be resolved so that TF2 can enhance the support for old models.

**Comment by bhack** [comment] 2020-09-25 12:14
I don't see your model definition but please double check our compatibility checklist:
https://www.tensorflow.org/guide/versions#compatibility_of_savedmodels_graphs_and_checkpoints

**Comment by HollowMan6** [comment] 2020-09-25 13:51
> I don't see your model definition but please double check our compatibility checklist:
> https://www.tensorflow.org/guide/versions#compatibility_of_savedmodels_graphs_and_checkpoints

Thanks for your suggestion. It's a Keras Model, and I don't believe the compatibility checklist includes my issue. The model definition is [here](https://github.com/vogon101/skincancer/blob/master/src/sandbox/ml_lib/combined_model_v2.py), and here's [the code for training](https://github.com/vogon101/skincancer/blob/master/src/sandbox/v6_combined_model_v2.py).

**Comment by bhack** [comment] 2020-09-25 14:24
I think you can try to update your code:
https://www.tensorflow.org/guide/upgrade

Also in the model definition you was using `from keras import` but keras in Tensorflow is now `from tensorflow.keras import`

**Comment by HollowMan6** [comment] 2020-09-25 14:52
> I think you can try to upgrade your code:
> https://www.tensorflow.org/guide/upgrade
> 
> Also in the model definition you was using `from keras import` but keras in Tensorflow is now `from tensorflow.keras import`

Thank you for your quick reply. I know the code needs to upgrade since it was the code for TF1, but what I'm asking is that can I just reuse in TF2 the model [model_6_combined_2_DA.h5](https://github.com/vogon101/skincancer/blob/master/models/model_6_combined_2_DA.h5) trained in TF1? When I was trying to load the model in TF2.3.1 with the following code:
```python3 
from tensorflow.keras.models import load_model
model = load_model("model_6_combined_2_DA.h5")
print(model.summary())
```
An error was thrown:

```bash
~/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py in _should_skip_first_node(layer)
   1031   return (isinstance(layer, Functional) and
   1032           # Filter out Sequential models without an input shape.
-> 1033           isinstance(layer._layers[0], input_layer_module.InputLayer))
   1034 
   1035 
IndexError: list index out of range
```

Other details can be found in the description part above.

**Comment by bhack** [comment] 2020-09-25 15:21
You can try to use Keras instead of `tf.keras` for model loading:
`from keras.models import load_model` but with a TF version that is compatible with Keras 2.3.1

**Comment by HollowMan6** [comment] 2020-09-25 15:55
> You can try to use Keras instead of `tf.keras` for model loading:
> `from keras.models import load_model` but with a TF version that is compatible with Keras 2.3.1

Well, I have tried to use `keras` instead of `tf.keras` with TF 2.3.1 and Keras 2.3.1, first I encountered an error that can be solved in this way: https://github.com/tensorflow/tensorflow/issues/38589#issuecomment-665930503 . Then another error occurs:

```bash
~/.local/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in function(inputs, outputs, updates, name, **kwargs)
   3931     if updates:
   3932       raise ValueError('`updates` argument is not supported during '
-> 3933                        'eager execution. You passed: %s' % (updates,))
   3934     from tensorflow.python.keras import models  # pylint: disable=g-import-not-at-top
   3935     from tensorflow.python.keras.utils import tf_utils  # pylint: disable=g-import-not-at-top

ValueError: `updates` argument is not supported during eager execution. You passed: [<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=0>, <tf.Variable 'UnreadVariable' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.],
......
```

The gist is here: https://colab.research.google.com/drive/1OovMHVrMBsIwcwn2PUcgbEXHUfPLMdyM?usp=sharing

Any suggestions?

**Comment by HollowMan6** [comment] 2020-09-25 16:16
> 
> ```python
> from tensorflow.keras.models import load_model
> model = load_model("model_6_combined_2_DA.h5")
> print(model.summary())
> ```
> 
> An error was thrown:
> 
> ```shell
> ~/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py in _should_skip_first_node(layer)
>    1031   return (isinstance(layer, Functional) and
>    1032           # Filter out Sequential models without an input shape.
> -> 1033           isinstance(layer._layers[0], input_layer_module.InputLayer))
>    1034 
>    1035 
> IndexError: list index out of range
> ```
> 
> Other details can be found in the description part above.


I am able to fix this issue when replace [the code](https://github.com/tensorflow/tensorflow/blob/5d5534edf7d0b73cb23f7069135d674e1d27250b/tensorflow/python/keras/engine/functional.py#L1078-L1085) into following:
```python3
def _should_skip_first_node(layer):
  """Returns True if the first layer node should not be saved or loaded."""
  # Networks that are constructed with an Input layer/shape start with a
  # pre-existing node linking their input to output. This node is excluded from
  # the network config.
  if layer._layers:
    return (isinstance(layer, Functional) and
          # Filter out Sequential models without an input shape.
          isinstance(layer._layers[0], input_layer_module.InputLayer))
  else:
    return isinstance(layer, Functional)
```

Can you suggest if there's some side effects, if no, I will make a pull request?

**Comment by bhack** [comment] 2020-09-25 16:28
As it is not a bug I suggest you to close this and post you example in https://stackoverflow.com/questions/tagged/tensorflow

**Closed** 2020-09-25 16:30 UTC
Labels: TF 2.3, type:bug
