### ISSUE TITLE
TypeError: 'Tensor' object does not support item assignment ,  in tf.while_loop

### ISSUE THREAD

**Issue by TentuVenkatesh** [tensorflow/tensorflow#32387] opened 2019-09-10 18:53 UTC
i am training an unsupervised CNN, for this, I defined a loss function in which CNN input is mapped to the cnn output through a complicated expression.  i am using  tf.while_loop to update the variables of "gamma_tilde_tensor_local " and "D_mat_tensor_local ".  i have uploaded my code  & the error below.
please suggest me how to update tensor variables in while_loop. 

to avoid confusion, i have avoided the complex loops. originally  "gamma_tilde_tensor_local " size (batch_size, M,M,K,K).   

```
def function(self):
        gamma_tilde_tensor_local = tf.Variable(tf.zeros(shape = [self.mini_batchSize, self.num_users]),dtype=tf.float32)
        D_mat_tensor_local = tf.Variable(tf.zeros(shape = [self.mini_batchSize, , self.num_users]), dtype=tf.float32)
        condition_g1  = lambda k_iter1, gamma_tilde_tensor_local, D_mat_tensor_local : k_iter1 < self.num_users
        def body_gm1( k_iter1, gamma_tilde_tensor_local, D_mat_tensor_local):
            tf_x_k = tf.expand_dims(self.PHI_batch[:,:,k_iter1],axis=-1)          
            tf_x_kd = tf.expand_dims(self.PHI_batch[:,:,k_iter2],axis=-1)        
            phi_to_reduce =  tf.matmul( tf.transpose(tf_x_kd, perm=[0, 2, 1]), tf_x_k)
            phi_t = tf.squeeze(phi_to_reduce,[1,2])
            gamma_till = tf.divide(  tf.multiply( self.gammafun[:,1, 2 ], self.channel_Gain[:,1, k_iter1]), self.channel_Gain[:,1, 2])
            
            gamma_tilde_tensor_local[: k_iter1] = tf.multiply(phi_t, gamma_till )    
            D_mat_tensor_local[:,k_iter1] = tf.sqrt(  tf.multiply( self.gammafun[1, 2], self.channel_Gain[1,k_iter1] ))                 
              
            return tf.add(k_iter1, 1), gamma_tilde_tensor_local, D_mat_tensor_local
        k_iter1, gamma_tilde_tensor_local, D_mat_tensor_local = tf.while_loop(condition_g1, body_gm1, [0, gamma_tilde_tensor_local, D_mat_tensor_local])
```

**> TypeError: 'Tensor' object does not support item assignment
>         gamma_till = tf.divide(  tf.multiply( self.gammafun[:,1, 2 ], self.channel_Gain[:,1, k_iter1]), self.channel_Gain[:,1, 2])**

**Comment by ravikyram** [comment] 2019-09-11 06:30
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the full code snippet to reproduce the issue in our environment. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2019-09-19 11:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-09-19 11:13 UTC
Labels: comp:ops, stat:awaiting response, type:support
