### ISSUE TITLE
encounter error when session run in c++:Invalid argument: No OpKernel was registered to support Op 'Sub' with these attrs

### ISSUE THREAD

**Issue by u4lr451** [tensorflow/tensorflow#4053] opened 2016-08-26 09:40 UTC
tensorflow version :0.8.0

1) use python to train model
2) use freeze_graph.py to freeze the mode and graph def as freeze.pb
3) load the  freeze.pb  is ok . but when  run session get this error

'''CreateGlobalVariables ...
pn predict fail:Invalid argument: No OpKernel was registered to support Op 'Sub' with these attrs
         [[Node: train_correct/dp_11/random_uniform/sub = Sub[T=DT_FLOAT](train_correct/dp_11/random_uniform/max, train_correct/dp_11/random_uniform/min)]] '''

**Comment by prb12** [comment] 2016-08-26 15:30
Could you possibly try to reproduce this on a newer version of TensorFlow?

**Comment by rieram** [comment] 2016-08-31 16:01
I had similar problem with Dequantization Kernel not being register when trying to execute inception V3 in 8bit mode. I fixed it in the bazel script under the target and included the quantization operators as dependencies. The kernel registrations should happen as file globals (I believe) so it looks like there is a disconnect with the "Sub" operator and the dependencies in bazel for that particular target.

**Comment by tatatodd** [comment] 2016-09-06 23:12
@u4lr451 Have you been able to reproduce on a newer version of TensorFlow?  The latest released version is 0.10.0

**Comment by aselle** [comment] 2016-09-16 16:40
Automatically closing due to lack of recent activity, please reopen or provide more information when it becomes available.

**Closed by aselle** 2016-09-16 16:40 UTC
Labels: awaiting response
