### ISSUE TITLE
Install of Tensorflow Lite error - :app:compiledebugjavawithjavac

### ISSUE THREAD

**Issue by gearsmotion789** [tensorflow/tensorflow#19342] opened 2018-05-17 03:45 UTC
Hi,
I am trying to test out the Tensorflow Lite Android demo on Android Studio, but I am always getting the build error: :app:compiledebugjavawithjavac. I set the JDK path and rebuilt the project. I have done everything the instructions have said. I recently installed the latest Android Studio 3.1.2 just before importing the Tensorflow Lite demo. So how can I fix this?

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows - on Android Studio
- **TensorFlow installed from (source or binary)**: Android Studio Demo Code
- **TensorFlow version (use command below)**: NA
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.0 / 7.0
- **GPU model and memory**: GeForce GTX 750
- **Exact command to reproduce**: NA

**Comment by tensorflowbutler** [comment] 2018-05-17 12:45
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gearsmotion789** [comment] 2018-05-17 14:33
I've updated the fields.

**Comment by tensorflowbutler** [comment] 2018-06-02 13:59
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by andrehentz** [comment] 2018-06-12 16:54
Could you describe how you are building tf lite?

**Comment by tensorflowbutler** [comment] 2018-06-27 18:50
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-12 19:08
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-27 18:53
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-08-09 20:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-08-09 20:43 UTC
Labels: comp:lite
