### ISSUE TITLE
Unable to access resources using tf.data.experimental.service

### ISSUE THREAD

**Issue by ialdencoots** [tensorflow/tensorflow#47531] opened 2021-03-03 15:15 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 4.19.160-2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.7 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf resources used in mapped functions are not available to workers when using `tf.data.experimental.service.distribute` to process a dataset. When the dataset is iterated over locally, this does not produce an error.

**Describe the expected behavior**
The expected behavior would be that locally run calls to `Dataset.map` and ones which use `tf.data.experimental.service.distribute` work equally.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

keys = 'abcdefghijklmnopqrstuvwxyz'
table = tf.lookup.StaticHashTable(tf.lookup.KeyValueTensorInitializer(list(keys), range(len(keys))), -1)

ds = tf.data.Dataset.from_tensor_slices([['a', 'b'], ['c', 'd'], ['e','f']])
ds = ds.map(lambda x: table.lookup(x))

# When True, this produces an error, but works when set to False
USE_DATA_SERVICE = True
if USE_DATA_SERVICE:
  # Set up data service
  dispatcher = tf.data.experimental.service.DispatchServer()
  dispatcher_address = dispatcher.target.split("://")[1]
  workers = [
    tf.data.experimental.service.WorkerServer(
      tf.data.experimental.service.WorkerConfig(
          dispatcher_address=dispatcher_address)) for _ in range(2)
  ]

  processing_mode = "parallel_epochs"
  ds = ds.apply(tf.data.experimental.service.distribute(
    processing_mode=processing_mode, service=dispatcher.target))

ds.__iter__().get_next()
```

**Other info / logs** Include any logs or source code that would be helpful to
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2112       ctx.executor = executor_new
-> 2113       yield
   2114     finally:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    732           output_types=self._flat_output_types,
--> 733           output_shapes=self._flat_output_shapes)
    734 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2578     except _core._NotOkStatusException as e:
-> 2579       _ops.raise_from_not_ok_status(e, name)
   2580     except _core._FallbackException:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

NotFoundError: Failed to get element: Container localhost does not exist. (Could not find resource: localhost/28)
	 [[{{node None_Lookup/LookupTableFindV2}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-2-e1a0821191f4> in <module>
     22     processing_mode=processing_mode, service=dispatcher.target))
     23 
---> 24 ds.__iter__().get_next()

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in get_next(self)
    798 
    799   def get_next(self):
--> 800     return self._next_internal()
    801 
    802   def get_next_as_optional(self):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    737         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    738       except AttributeError:
--> 739         return structure.from_compatible_tensor_list(self._element_spec, ret)
    740 
    741   @property

/opt/conda/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2114     finally:
   2115       ctx.executor = executor_old
-> 2116       executor_new.wait()
   2117 
   2118 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/executor.py in wait(self)
     67   def wait(self):
     68     """Waits for ops dispatched in this executor to finish."""
---> 69     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     70 
     71   def clear_error(self):

NotFoundError: Failed to get element: Container localhost does not exist. (Could not find resource: localhost/28)
	 [[{{node None_Lookup/LookupTableFindV2}}]]
```

**Comment by amahendrakar** [comment] 2021-03-04 13:40
Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/128826b210f2d4b5598040e902fce4ed/47531.ipynb) and TF-nightly.

Whereas on running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/658b9346d3e74da9a03c269c8f09169b/47531-2-3.ipynb#scrollTo=5dc9GGSJcknG), I am facing an error stating `TypeError: __init__() missing 1 required positional argument: 'port'`. Please check the linked gist for reference. Thanks!

**Comment by aaudiber** [comment] 2021-03-08 22:42
Thanks for reporting this @ialdencoots. The error happens because the serialized Dataset sent to the tf.data servers contains only a handle to the lookup table. We hope to fix the issue in TF 2.5 by serializing the information needed to re-instantiate the lookup table on the tf.data servers (e.g. filename for lookup table initialization, or possibly a serialization of the full lookup table content).

In the short term, the workaround is to move the lookup table transformation to happen after the call to `tf.data.experimental.service.distribute` if possible.

**Comment by ialdencoots** [comment] 2021-03-11 09:11
Thanks for the information! Unfortunately for me, the lookup occurs within the expensive operation that I'm hoping to distribute, so moving the call to happen later isn't possible.

This may be outside of the scope of this repo, but I was wondering if there is any intention of adding more built in support for things like cluster resolution in deploying the distribute dispatch and worker servers. When running as a GCP AI Platform job, I would like to be able to spin up additional worker machines to do data preprocessing as part of the job I'm submitting, much like when one trains with `tf.distribute.Strategy`. I'm not too familiar with the internals, but I'm assuming proper grpc channels would have to be opened between the machines and that it might be something the AI Platform would have to do. Do you have any knowledge on the topic?

**Comment by sushreebarsa** [comment] 2021-06-01 12:55
Was able to replicate the issue in [TF v2.5 ](https://colab.research.google.com/gist/sushreebarsa/1381b4518359bed9c195ff0a908894b3/untitled173.ipynb)& [TF 2.6.0-dev20210531](https://colab.research.google.com/gist/sushreebarsa/1e147c87dbf1f27308e9630cbcc1dc27/untitled172.ipynb#scrollTo=rJFumDKB2xNv),please find the gists for your  reference ....Thanks !

**Comment by aaudiber** [comment] 2021-06-01 20:22
This issue should be fixed in TF v2.5. @sushreebarsa When I run those colabs I don't see any errors, do you see an error?

**Comment by sushreebarsa** [comment] 2021-06-02 03:31
@aaudiber I also didn't see any error in TF 2.5 and nightly ...it seems to fixed .

**Comment by sushreebarsa** [comment] 2021-06-04 11:14
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by sushreebarsa** 2021-06-04 11:14 UTC
Labels: TF 2.4, comp:data, type:bug
