### ISSUE TITLE
.bazelversion and configure.py conflicts

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#39248] opened 2020-05-07 08:54 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  source master
- TensorFlow version: master 2.1.0
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: GTX1080Ti GDDR5X 11GB

**Describe the problem**

.bazelversion and configure.py. bazel version requirements are different from each other,
causing error.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
.configure

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

\.configure
```
Traceback (most recent call last):
  File "./configure.py", line 1557, in <module>
    main()
  File "./configure.py", line 1369, in main
    current_bazel_version = check_bazel_version(_TF_MIN_BAZEL_VERSION,
  File "./configure.py", line 482, in check_bazel_version
    curr_version = run_shell(
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/home/wmind/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/wmind/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.
```

bazel --version
```
ERROR: The project you're trying to build requires Bazel 3.0.0 (specified in /home/wmind/repo/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-3.0.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```

**Comment by Saduf2019** [comment] 2020-05-07 13:59
@alanpurple 
Could you please downgrade your python version and try the same.
Also please refer to this [link](https://stackoverflow.com/questions/56563041/calledprocesserror-while-installing-tensorflow-using-bazel) , [link1](https://github.com/tensorflow/tensorflow/issues/37702#issuecomment-601370963) , [link2](https://github.com/FloopCZ/tensorflow_cc/issues/216#issuecomment-616306768)
#38736 #37702 #38325 #22743

**Comment by mihaimaruseac** [comment] 2020-05-07 17:41
Master branch seems ok as the version in `.bazelversion` is included in the range from `configure.py`: https://github.com/tensorflow/tensorflow/blob/62d50aa8e28209c701e8919d315ed0cb3ca804de/configure.py#L52-L53 and https://github.com/tensorflow/tensorflow/blob/62d50aa8e28209c701e8919d315ed0cb3ca804de/.bazelversion#L1

The same happens on `r2.2` and `r2.1` branches. `.bazelversion` does not exist before that.

**Comment by alanpurple** [comment] 2020-05-08 00:45
@Saduf2019 
done, same error with python 3.8.1

@mihaimaruseac 
yes, that's what i'm saying, master branch should be okay, but error occurs

**Comment by mihaimaruseac** [comment] 2020-05-08 18:04
What is the output of `bazel version` (not `bazel --version`)?

**Comment by yongtang** [comment] 2020-05-10 05:16
@mihaimaruseac @alanpurple From the https://github.com/bazelbuild/bazel/issues/10465#issuecomment-567842873, my understanding is that:
- bazelversion is meant to be used by a "bazel wrapper" (installed form `apt-get install bazel`, or binary download of `bazelisk`)
- the "bazel wrapper" will selectively choose the exact version of the bazel (3.0.0 in this case) to run.

However, since traditionally tensorflow developers outside of google normally download and install bazel directly (not through the wrapper), a downloaded version might be different and the error happens.

My suggestion is to either update the documentation for installation and ask people to use bazel wrapper instead (and remove version range in configure.py), or remove bazelversion restriction,

**Comment by alanpurple** [comment] 2020-05-10 07:47
@yongtang 
no, I've already known that apt install bazel and I use that version of bazel, this is not the install type problem after all

**Comment by alanpurple** [comment] 2020-05-10 09:08
this is not happening in windows 10 anyway

**Comment by Saduf2019** [comment] 2020-06-05 05:30
@alanpurple 
Is this still an issue

**Comment by alanpurple** [comment] 2020-06-05 07:35
@Saduf2019 

yes same, nothing's been resolved

**Comment by alanpurple** [comment] 2020-06-06 06:18
@mihaimaruseac 

this time, 3.2.0, and .bazelversion has 3.1.0

**Comment by mihaimaruseac** [comment] 2020-06-06 13:24
Sorry, please post the exact output.

**Comment by alanpurple** [comment] 2020-06-08 00:28
@mihaimaruseac 

```
ERROR: The project you're trying to build requires Bazel 3.0.0 (specified in /home/wmind/repo/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-3.0.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```

**Comment by mihaimaruseac** [comment] 2020-06-08 15:36
This seems to be caused by a logic error in `configure.py`. Will try to send a fix soon.

**Comment by mihaimaruseac** [comment] 2020-06-22 21:24
This should be fixed on master by 56a99d6. Can you please try again from `master` branch, syncing to a fresh hash? If it fails, can you please post the commit hash you are building from?

Preferably, can you post the full output of running the following commands?

```
bazel clean --expunge
git checkout master
git pull --rebase
git show
python configure.py
```

Apologies for the delay, spent a while tried to replicate before I thought of looking into the code and saw the code change

**Comment by alanpurple** [comment] 2020-06-23 01:56
@mihaimaruseac 

```
wmind@wmind-deep:~/repo/tensorflow$ bazel clean --expunge
ERROR: The project you're trying to build requires Bazel 3.1.0 (specified in /home/wmind/repo/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-3.1.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
wmind@wmind-deep:~/repo/tensorflow$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
wmind@wmind-deep:~/repo/tensorflow$ git pull --rebase
Already up to date.
wmind@wmind-deep:~/repo/tensorflow$ git show
commit d8b90acf95bdff09e29b1065739e28e8bd7500d9 (HEAD -> master, origin/master, origin/HEAD)
Author: Dan Moldovan <mdan@google.com>
Date:   Mon Jun 22 18:46:12 2020 -0700

    Enable type annotations for python/ops.
    
    PiperOrigin-RevId: 317779660
    Change-Id: Ife6b7319ef394b611798f5d01b64ebdb3c0a01cc

diff --git a/tensorflow/python/ops/logging_ops.py b/tensorflow/python/ops/logging_ops.py
index 8ca63f5598..02fce27769 100644
--- a/tensorflow/python/ops/logging_ops.py
+++ b/tensorflow/python/ops/logging_ops.py
@@ -54,11 +54,9 @@ except NameError:
 # call relies on certain conditionals for its dependencies.  Use
 # control_flow_ops.Assert.
 
-# Assert and Print are special symbols in python, so we must
-# have an upper-case version of them.
-#
-# For users with Python 3 or Python 2.7
wmind@wmind-deep:~/repo/tensorflow$ python configure.py
WARNING: current bazel installation is not a release version.
Make sure you are running at least bazel 3.1.0
Please specify the location of python. [Default is /home/wmind/anaconda3/bin/python]: 
```

**Comment by mihaimaruseac** [comment] 2020-06-23 02:08
This seems consistent with what we have

https://github.com/tensorflow/tensorflow/blob/d8b90acf95bdff09e29b1065739e28e8bd7500d9/configure.py#L52-L53

https://github.com/tensorflow/tensorflow/blob/d8b90acf95bdff09e29b1065739e28e8bd7500d9/.bazelversion#L1

Seems you have a broken bazelisk? Or a bazelisk which cannot automatically install bazel? What is the output of `type bazel`?

**Comment by alanpurple** [comment] 2020-06-23 02:43
@mihaimaruseac 
outside tensorflow repo, bazel is fine, my bazel version is 3.2.0

with modification to .bazeversion(to 3.2.0) works fine

**Comment by alanpurple** [comment] 2020-06-23 02:44
```
wmind@wmind-deep:~/repo/tensorflow$ type bazel
bazel is hashed (/usr/bin/bazel)
wmind@wmind-deep:~/repo/tensorflow$ bazel version
ERROR: The project you're trying to build requires Bazel 3.1.0 (specified in /home/wmind/repo/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-3.1.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
wmind@wmind-deep:~/repo/tensorflow$ cd ..
wmind@wmind-deep:~/repo$ bazel version
Build label: 3.3.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:55:32 2020 (1592398532)
Build timestamp: 1592398532
Build timestamp as int: 1592398532
wmind@wmind-deep:~/repo$ 
```

**Comment by alanpurple** [comment] 2020-06-23 02:45
```
wmind@wmind-deep:~/repo/tensorflow$ vim .bazelversion 
wmind@wmind-deep:~/repo/tensorflow$ bazel version
Build label: 3.3.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:55:32 2020 (1592398532)
Build timestamp: 1592398532
Build timestamp as int: 1592398532
wmind@wmind-deep:~/repo/tensorflow$ ./configure 
You have bazel 3.3.0 installed.
Please specify the location of python. [Default is /home/wmind/anaconda3/bin/python3]: 
```

**Comment by alanpurple** [comment] 2020-06-23 02:46
so it's not my bazel's fault after all

**Comment by mihaimaruseac** [comment] 2020-06-23 15:20
This is what I see on my end, on a Docker container with bazelisk installed.

```
root@faa022ec076e:/src# bazel version
2020/06/23 15:09:08 Downloading https://releases.bazel.build/3.3.0/release/bazel-3.3.0-linux-x86_64...
Bazelisk version: v1.1.0
Extracting Bazel installation... 
Build label: 3.3.0                                                                                                                 
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:55:32 2020 (1592398532)
Build timestamp: 1592398532                                      
Build timestamp as int: 1592398532
root@faa022ec076e:/src# bazel version
Bazelisk version: v1.1.0                                         
Build label: 3.3.0      
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:55:32 2020 (1592398532)
Build timestamp: 1592398532                                                                                                        
Build timestamp as int: 1592398532               
root@faa022ec076e:/src# cd -
/src/tensorflow                                                  
root@faa022ec076e:/src/tensorflow# bazel version
Bazelisk version: v1.1.0
Starting local Bazel server and connecting to it...
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
root@faa022ec076e:/src/tensorflow# type bazel
bazel is hashed (/usr/bin/bazel) 
root@faa022ec076e:/src/tensorflow# file /usr/bin/bazel
/usr/bin/bazel: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

Note how bazelisk is able to download the missing bazel on my system.

If I change `.bazelversion` to something which does not exist then I am able to reproduce your output:

```
root@faa022ec076e:/src/tensorflow# git diff  
diff --git a/.bazelversion b/.bazelversion                 
index fd2a0186..18091983 100644
--- a/.bazelversion
+++ b/.bazelversion                                              
@@ -1 +1 @@
-3.1.0
+3.4.0
root@faa022ec076e:/src/tensorflow# bazel version
2020/06/23 15:14:22 Downloading https://releases.bazel.build/3.4.0/release/bazel-3.4.0-linux-x86_64...
2020/06/23 15:14:23 could not download Bazel: HTTP GET https://releases.bazel.build/3.4.0/release/bazel-3.4.0-linux-x86_64 failed w
ith error 404
root@faa022ec076e:/src/tensorflow# python configure.py
WARNING: current bazel installation is not a release version.
Make sure you are running at least bazel 3.1.0
Please specify the location of python. [Default is /usr/local/bin/python]:
```

To go further, can you run the following two commands in the `tensorflow` directory please? (Install `strace` if missing)

```
strace -f -o bazel_version.log bazel version
strace -f -o configure.log python configure.py
```

And then attach the `bazel_version.log` and `configure.log` files.

**Comment by alanpurple** [comment] 2020-06-24 01:35
[configure.log](https://github.com/tensorflow/tensorflow/files/4822727/configure.log)
[bazel_version.log](https://github.com/tensorflow/tensorflow/files/4822728/bazel_version.log)

@mihaimaruseac

**Comment by mihaimaruseac** [comment] 2020-06-24 21:39
You have `bazel`, not `bazelisk` (`/usr/bin/bazel-real` is the binary that runs). Bazelisk is the process which should read `.bazelversion` and install the corresponding Bazel. It seems Bazel now checks the `.bazelversion` file too.

**Comment by mihaimaruseac** [comment] 2020-06-24 21:42
That is, if you install Bazelisk (and uninstall Bazel), this should not happen anymore

**Comment by alanpurple** [comment] 2020-06-25 02:53
@mihaimaruseac 
so what u mean is, this is bazel's s problem?

and bazelisk is okay but original bazel is not.

is this right?

I'd rather modify .bazelversion, is it okay?


thank you

**Comment by mihaimaruseac** [comment] 2020-06-25 05:54
`.bazelversion` is used by Bazelisk. In all my tests Bazel would just ignore the file. Don't know why the binary that executes when you call `bazel` on your system does not ignore the file.

`.bazelversion` lists the version of Bazel that we built with. As long as you change it to a version that is in the range specified by `configure.py` that should be ok

**Comment by alanpurple** [comment] 2020-06-25 13:50
@mihaimaruseac 

thank you for your efforts, but it seems that this issue is not resolved

**Comment by mihaimaruseac** [comment] 2020-06-25 16:21
What do you mean by "is not resolved"? What changed since https://github.com/tensorflow/tensorflow/issues/39248#issuecomment-649235945 ?

**Comment by alanpurple** [comment] 2020-06-26 00:09
@mihaimaruseac 
I mean, since official bazel has problem with tensorflow build, even though bazelisk has no problem

**Comment by mihaimaruseac** [comment] 2020-06-26 00:21
I am not sure what is the problem You are able to run `./configure` and `bazel build`, right? There is no more a conflict between `.bazelversion` and `configure.py`

On a docker container, with no bazelisk, no bazel, I am able to build even if using bazel 3.3.0.

```
root@dde9f7f2f021:/src/tensorflow# wget -O /usr/bin/bazel https://github.com/bazelbuild/bazel/releases/download/3.3.0/bazel-3.3.0-linux-x86_64 
oot@dde9f7f2f021:/src/tensorflow# chmod +x /usr/bin/bazel        
root@dde9f7f2f021:/src/tensorflow# bazel version                                                                                   
Extracting Bazel installation...                 
Starting local Bazel server and connecting to it...
Build label: 3.3.0                                                                                                                 
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:55:32 2020 (1592398532)        
Build timestamp: 1592398532                                                                                                        
Build timestamp as int: 1592398532                                                                                                 
root@dde9f7f2f021:/src/tensorflow# bazel --version        
bazel 3.3.0                                                                                                                        
root@dde9f7f2f021:/src/tensorflow# python configure.py                                                                             
You have bazel 3.3.0 installed.                                                                                                    
Please specify the location of python. [Default is /usr/local/bin/python]: 
...
root@dde9f7f2f021:/src/tensorflow# bazel build tensorflow/tools/pip_package:build_pip_package
...
root@dde9f7f2f021:/src/tensorflow# cat .bazelversion 
3.1.0
...

So, I am unsure what is left to be solved on this issue.

**Comment by Saduf2019** [comment] 2021-04-29 18:25
@alanpurple 
Could you please check on tf 2.4.1/upgrade tf version to latest and let us know if you still face the issue.

**Closed** 2021-04-30 07:33 UTC
Labels: TF 2.1, stat:awaiting response, subtype: ubuntu/linux, type:build/install
