### ISSUE TITLE
tf_cc_binary() makes opencv unable to load an image

### ISSUE THREAD

**Issue by CodingJonas** [tensorflow/tensorflow#13278] opened 2017-09-24 20:09 UTC
I try to load an image with opencv and work further on it with the tensorflow framework. Unfortunately I get a really weird behaviour:

The image is loaded without problems using `cc_binary(...)` in Bazel. Changing it to `tf_cc_binary(...)` doesn't stop the code from compilation or running, but opencv can't load any images any more.

### Source code / logs
This is my BUILD file:

    load("//tensorflow:tensorflow.bzl", "tf_cc_binary")

    #tf_cc_binary( <-- using this, no image could be loaded anymore
    cc_binary(
        name = "main",
        srcs = ["main.cpp"],
        linkopts = [
            "-lopencv_core",
            "-lopencv_highgui",
            "-lopencv_imgcodecs",
            "-lopencv_imgproc",
        ],
        visibility=["//visibility:public"]
    )

I use the standard example code from the opencv website. Again, it is working and the image gets loaded using `cc_binary(`:

    #include <opencv2/core/core.hpp>
    #include <opencv2/highgui/highgui.hpp>
    #include <iostream>
    
    using namespace cv;
    using namespace std;
    
    int main( int argc, char** argv )
    {
        Mat image;
        image = imread("tensorflow/test/imageHolder/data/example.jpg", CV_LOAD_IMAGE_COLOR);   // Read the file
    
        if(! image.data )                              // Check for invalid input
        {
            cout <<  "Could not open or find the image" << std::endl ;
            return -1;
        }
    
        namedWindow( "Display window", WINDOW_AUTOSIZE );// Create a window for display.
        imshow( "Display window", image );                   // Show our image inside it.
    
        waitKey(0);                                          // Wait for a keystroke in the window
        return 0;
    }

This is my file structure in case it matters:

    ├── data
        ├── example.jpg
    └── src
        ├── BUILD
        ├── main.cpp

**Comment by aselle** [comment] 2017-09-24 23:43
I think this may be a duplicate of #1924. There has been a history of conflicts between opencv and tensorflow see  #7378. This is usually caused by conflicting libraries that both depend on. Try following the advice in #1924, and let us know how it goes. @allenlavoie , will your library isolation stuff help here?

**Comment by CodingJonas** [comment] 2017-09-25 13:24
I try to follow the advice to compile a shared library. That worked fine. But there is hardly any documentation about how to work in an external project with the tensorflow_cc.so library.
Is there any example project, that shows how to compile projects with it? I'm mainly confused about which headers to include and where I can find them.

**Comment by allenlavoie** [comment] 2017-09-25 16:35
We may want to shift some symbols to a private shared object (or the language bindings) so we don't conflict with symbols in extensions, but it doesn't sound like that's an issue here. If you want to use TensorFlow rather than adding ops/kernels, use the C++ or C API, not tf_cc_binary rules.

@skye is working on a distribution for the C++ API AFAIK. The C API [has one](https://www.tensorflow.org/install/install_c).

**Comment by skye** [comment] 2017-09-25 16:47
Unfortunately no one is working on a distribution for the C++ API right now, so if you're trying to use the C++ API, building against TF with bazel is probably the best way. If you can use the C API and follow the instructions Allen linked to, that should avoid this issue.

**Comment by CodingJonas** [comment] 2017-10-04 15:47
I struggle quite a bit using the C API. Except for an introduction of how to install the library I can't find any working examples nor any documentation except for some helpful comments in the source code. Why is there a C++ API documentation, but no C API documentation?
Can you give me some help to start with the C API? That would be great!

**Comment by skye** [comment] 2017-10-04 16:20
I would look at the C API tests, e.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_test.cc#L686 (this goes over building and running a graph). Note that it uses some helper functions defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_test_util.cc.

**Closed** 2017-12-05 17:21 UTC
Labels: type:build/install
