### ISSUE TITLE
TF2.3 converter.convert ValueError: Input 0 of node StatefulPartitionedCall/functional_1/resnet50/conv1_bn/AssignNewValue was passed float from Func/StatefulPartitionedCall/input/_5:0 incompatible with expected resource.

### ISSUE THREAD

**Issue by tolry418** [tensorflow/tensorflow#43833] opened 2020-10-07 01:24 UTC
**System information**
- OS Platform and Distribution (Ubuntu 18.04, cuda 10.1):
- TensorFlow installed from (binary):
- TensorFlow version (TF 2.3):

Here is the part of my code. 
```
       export_path './test_model'
        tf.saved_model.save(model, export_path)
        converter = tf.lite.TFLiteConverter.from_saved_model(export_path)
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
        tflite_model = converter.convert()
        open("./converted_model.tflite", "wb").write(tflite_model)
```

Here is my model summary, which is a typical image classification model using pre_trained ResNet50 model for transfer-learning. 

```
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, 160, 160, 3)]     0         
_________________________________________________________________
sequential (Sequential)      (None, 160, 160, 3)       0         
_________________________________________________________________
tf_op_layer_RealDiv (TensorF [(None, 160, 160, 3)]     0         
_________________________________________________________________
tf_op_layer_Sub (TensorFlowO [(None, 160, 160, 3)]     0         
_________________________________________________________________
resnet50 (Functional)        (None, 5, 5, 2048)        23587712  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
dropout (Dropout)            (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 3)                 6147      
=================================================================
Total params: 23,593,859
Trainable params: 23,540,739
Non-trainable params: 53,120
_________________________________________________________________
```

Here is the failure errors. 
```
Traceback (most recent call last):
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node StatefulPartitionedCall/functional_1/resnet50/conv1_bn/AssignNewValue was passed float from Func/StatefulPartitionedCall/input/_5:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "main.py", line 321, in <module>
    main(train='lite')
  File "main.py", line 210, in main
    tflite_model = converter.convert()
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 878, in convert
    self._funcs[0], lower_control_flow=False))
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1109, in convert_variables_to_constants_v2_as_graph
    converted_input_indices)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1001, in _construct_concrete_function
    new_output_names)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 628, in wrap_function
    collections={}),
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/ktatc/anaconda3/envs/HHproject/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
**ValueError: Input 0 of node StatefulPartitionedCall/functional_1/resnet50/conv1_bn/AssignNewValue was passed float from Func/StatefulPartitionedCall/input/_5:0 incompatible with expected resource.**

```

How can i solve it? I don't know the reason why these kind of error happen. please let me know in detail.
Thanks in advance.

**Comment by ravikyram** [comment] 2020-10-07 02:16
@tolry418 

Please, share colab link or code with supporting files (`model file)` to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by tolry418** [comment] 2020-10-07 04:24
Thank you for your reply. 
My saved model is here.  
[saved_model.zip](https://github.com/tensorflow/tensorflow/files/5338241/saved_model.zip)
Thanks.

**Comment by ravikyram** [comment] 2020-10-07 07:11
I have tried in colab with TF version 2.3 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/86b909fb62d4b691f61bea5da3ec53af/untitled429.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment] 2020-10-07 20:22
@tolry418 I am seeing different exception error as shown below. Can you please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/94b2fd060335f1177cfa4c830ba5277b/untitled429.ipynb).

Can you please share model building code? Thanks!

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    211                                                  debug_info_str,
--> 212                                                  enable_mlir_converter)
    213       return model_str

4 frames
Exception: <unknown>:0: error: loc("Conv_1_bn/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    213       return model_str
    214     except Exception as e:
--> 215       raise ConverterError(str(e))
    216 
    217   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("Conv_1_bn/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable
```

**Comment by tolry418** [comment] 2020-10-08 00:13
@jvishnuvardhan I used TF 2.3, not tf-nightly. And my python version is 3.7. 

Here is my code. 

```
import os
import tensorflow as tf
import cv2
from datetime import datetime

from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.models import Model

def main(train=True):
    now = datetime.now()
    
    PATH = './HHI_Edit'
    train_dir = os.path.join(PATH, 'train')
    validation_dir = os.path.join(PATH, 'validation')
    
    BATCH_SIZE = 32
    IMG_SIZE = (160, 160)
    
    train_dataset = image_dataset_from_directory(train_dir,
                                                 label_mode='int',
                                                 shuffle=True,
                                                 batch_size=BATCH_SIZE,
                                                 image_size=IMG_SIZE)
        

    validation_dataset = image_dataset_from_directory(validation_dir,
                                                      label_mode='int',
                                                      shuffle=True,
                                                      batch_size=BATCH_SIZE,
                                                      image_size=IMG_SIZE)


    val_batches = tf.data.experimental.cardinality(validation_dataset)
    test_dataset = validation_dataset.take(val_batches // 5)
    validation_dataset = validation_dataset.skip(val_batches // 5)
    
    AUTOTUNE = tf.data.experimental.AUTOTUNE #-1
    train_dataset = train_dataset.prefetch(buffer_size=AUTOTUNE)
    validation_dataset = validation_dataset.prefetch(buffer_size=AUTOTUNE)
    test_dataset = test_dataset.prefetch(buffer_size=AUTOTUNE)

    data_augmentation = tf.keras.Sequential([
    tf.keras.layers.experimental.preprocessing.RandomFlip('horizontal'),
    tf.keras.layers.experimental.preprocessing.RandomRotation(0.2),
    ])
    
    preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input
    rescale = tf.keras.layers.experimental.preprocessing.Rescaling(1./127.5, offset= -1)
    IMG_SHAPE = IMG_SIZE + (3,)

    # base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
    #                                            include_top=False,
    #                                            weights='imagenet')
    base_model = tf.keras.applications.ResNet50(input_shape=IMG_SHAPE,
                                           include_top=False,
                                           weights='imagenet')

    image_batch, label_batch = next(iter(train_dataset))
    feature_batch = base_model(image_batch)

    print ("start!!")
    if train=='true':
        base_model.trainable = True
      
        global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
        feature_batch_average = global_average_layer(feature_batch)
        
        prediction_layer = tf.keras.layers.Dense(3)
        prediction_batch = prediction_layer(feature_batch_average)

        
        inputs = tf.keras.Input(shape=(160, 160, 3))
        x = data_augmentation(inputs)
        x = preprocess_input(x)     
        # outputs = rescale(x)
        x = base_model(x, training=True)
        x = global_average_layer(x)
        x = tf.keras.layers.Dropout(0.2)(x)
        outputs = prediction_layer(x)
        model = tf.keras.Model(inputs, outputs)
        
        base_learning_rate = 0.0001
        model.compile(optimizer=tf.keras.optimizers.Adam(lr=base_learning_rate),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
        print (model.summary())    
        print ("len(model.trainable_variables", len(model.trainable_variables))
        
        initial_epochs = 1
        
        loss0, accuracy0 = model.evaluate(validation_dataset)
        print("initial loss: {:.2f}".format(loss0))
        print("initial accuracy: {:.2f}".format(accuracy0))
        
        history = model.fit(train_dataset,
                            epochs=initial_epochs,
                            validation_data=validation_dataset)
        
        dt_string = now.strftime("%d%m%Y_%H:%M:%S.hdf5")
        export_path = "./Weight/{}".format(dt_string)
        # model.save(filepath = export_path, save_format='tf')
        # tf.keras.models.save_model(model, export_path, save_format='h5')
        tf.saved_model.save(model, export_path)    
         
    elif train=='lite':
        load_path = './Weight/08102020_09:04:46/'
        converter = tf.lite.TFLiteConverter.from_saved_model(load_path)
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
        tflite_model = converter.convert()
        open("./converted_model.tflite", "wb").write(tflite_model)    
        
        
if __name__ == "__main__":
    main(train='lite')
```

If you done the training, change the path of 'load_path' in train=='lite' phase, then you can reproduce it. 
Thanks you.

**Comment by jvishnuvardhan** [comment] 2020-10-22 01:01
@tolry418 Can you please share a simple dataset or any similar public data?

> PATH = './my data' # << here is my own data

**Comment by tolry418** [comment] 2020-10-22 01:19
@jvishnuvardhan 
You can download datasets from the link .
﻿Cats and dogs filtered image datasets.

https://www.kaggle.com/birajsth/cats-and-dogs-filtered

Thanks.

**Comment by hoaquocphan** [comment] 2020-10-29 06:18
Hi All,

I have the same issues when I convert saved model to onnx model by below command:
> python3 -m tf2onnx.convert --saved-model . --output tf2-preview_inception_v3_classification_4.onnx --concrete_function 0
Error log:
> ValueError: Input 0 of node StatefulPartitionedCall/StatefulPartitionedCall/train/InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/AssignMovingAvg_1/AssignSubVariableOp was passed float from Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_410:0 incompatible with expected resource.

if there are anyone know this issue, please help me.

**Comment by majianjia** [comment] 2020-12-11 01:46
I met the same issue while converting a RNN model (GRU) with stateful enabled to tflite.

**Comment by lminer** [comment] 2020-12-12 21:39
I have the same issue when converting to tensorrt

**Comment by abattery** [comment] 2020-12-13 23:31
Sorry for encountering this issue in my side. Both TFRT and TFLite converter do not support mutable resource variable use cases yet. We are working on supporting the missing features in the MLIR converter.

**Comment by rahulzag** [comment] 2020-12-31 15:57
so now I have to scrape off my project :/

**Comment by rahulzag** [comment] 2021-01-01 08:35
can someone please convert the model to tflite and send me it would be a great help this is the model file -https://drive.google.com/drive/folders/1-1jAHa_N2YoA28sLCa2a0xJFkEfJu4Td?usp=sharing

**Comment by sayakpaul** [comment] 2021-03-12 16:08
@abattery this does not seem to be a problem when I disable the experimental converter:

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("mobilenetv2_student_no_true_labels_e_125_t_2")
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
open("student_mobilenetv2.tflite", 'wb').write(tflite_model)
print('Model size is %f MBs.' % (len(tflite_model) / 1024 / 1024.0))
```

If you are on Colab, simply copy over the SavedModel like so - `!gsutil cp -r gs://mai-scene-detection-21/mobilenetv2_student_no_true_labels_e_125_t_2 .`.

**Comment by Damcy** [comment] 2021-04-14 02:35
@abattery Thanks for your hint. Any update on this issue?

**Comment by abattery** [comment] 2021-04-14 02:39
Please use the saved model converter at the recent TF version. We have improved the support for resources and variants both. For mutable variable cases, you can enable the experimental feature, `converter._enable_tflite_resource_variables = True`>

**Comment by abattery** [comment] 2021-04-14 02:41
If you experince the simliar issue, please open a new issue to make issues be focused.

**Comment by ciklista** [comment] 2021-04-22 16:18
Thanks @abattery, however this is not solving it for me. I am having a similar issue with converting to tf-trt. Is there a similar flag for tf-trt?

**Comment by abattery** [comment] 2021-04-22 21:50
@ciklista If you experience the similar issue, please open a new issue to make issues be focused.

**Comment by Damcy** [comment] 2021-04-23 01:35
@ciklista I meet a similar issue when using TF-TRT (the model uses Embedding layer). I solve it using "TF to ONNX to TRT" instead of "TF to TRT". Hope this method can help you.

**Comment by ciklista** [comment] 2021-04-23 05:37
@abattery I know, sorry, I thought if this is a quick answer this might fit better here. Especially since others in this thread also had issues with tf-trt. As this seems not to be the case, I will go ahead and open a new issue. 

@Damcy yes, you are right, going to "bare bones" trt might be a solution but I specifically want to use TensorFlowTRT.

**Comment by raimondasl** [comment] 2021-04-26 20:50
@abattery I also have the same issue with tf-trt and would like to know if/when there is a solution for it.

@ciklista Please let me know if you open a new issue for this problem in the tf-trt context.

Thank you.

**Comment by abattery** [comment] 2021-04-26 22:23
Closing since the nightly version can support variables in the TFLite.

Please file another issue for tfrt..

**Comment by abattery** [comment] 2021-04-26 22:24
For the TFLite conversion, please use the saved model converter from the recent TF version. We have improved the support for resources and variants both in the saved model converter. For mutable variable cases, you can enable the experimental feature, converter._enable_tflite_resource_variables = True.

**Closed by abattery** 2021-04-26 22:23 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, type:bug

**Comment by EricSchwerzel** [comment] 2021-06-27 03:31
The bug can be recreated with the following code.  It would be good to have it fixed.

`import tensorflow as tf
from keras.models import Model
from keras.layers import BatchNormalization
from keras.models import Input

# Create minimalistic model that creates the error (full model is much bigger)
in_image = Input(shape=(256,256,3))
d7 = BatchNormalization()(in_image, training=True)  # This is the line that creates the error.  Error goes away when this line is removed or if "training=True" is removed
model = Model(in_image, d7)
model.compile(loss='mse')

# Convert model to tflite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)`

**Comment by sayakpaul** [comment] 2021-06-27 03:34
> d7 = BatchNormalization()(in_image, training=True)

Why are you specifying that argument, though? Based on where and how your model is being used this layer can adapt its behavior. [This Keras guide](https://keras.io/guides/transfer_learning) sheds some more details on it.

**Comment by EricSchwerzel** [comment] 2021-06-27 03:47
That is how the code in a book on [GANs](https://machinelearningmastery.com/generative_adversarial_networks/) is.  I think that saying "training=True" should not trip up the conversion process to tflite.

**Comment by sayakpaul** [comment] 2021-06-27 04:01
During conversion, the BatchNorm layer is supposed to be running in inference mode I think. Is there any particular reason why you'd want it to run in training mode?

/cc: @abattery @karimnosseir

**Comment by EricSchwerzel** [comment] 2021-06-27 04:57
In the book it says:-

In Keras, layers like Dropout and BatchNormalization operate differently during training
and in inference model. We can set the training argument when calling these layers to True
to ensure that they always operate in training-model, even when used during inference. For
example, a Dropout layer that will drop out during inference as well as training can be added
to the model as follows ...

**Comment by sayakpaul** [comment] 2021-06-27 05:05
You'd want those models to actually run in inference mode really. See the following notes:

* https://cs231n.github.io/neural-networks-2/#reg
* https://cs231n.github.io/neural-networks-2/#batchnorm

**Comment by EricSchwerzel** [comment] 2021-06-27 18:24
If I remove "training=True" from all the lines that have BatchNormalization(), the GAN model doesn't train nearly as well.  Remember that with GAN training "Inference" is used as a part of the model training.  During training "Inference" is done one each image and that image is passed to the Discriminator who gives it a Real/Fake score.  I'm not an expert, but it looks as though the code in the [book](https://machinelearningmastery.com/generative_adversarial_networks/) is correct.

I can see that having "training=True" for TensorFlowLite is an issue because TensorFlowLite is designed to be for inference only.  Maybe TensorFlowLite  should ignore "training=True" for BatchNormalization() and Dropout() layers.

It would be good to have this issue fixed so that we can use TensorFlowLite for generating GAN images.

**Comment by abattery** [comment] 2021-06-28 00:54
Please consider uploading a new issue if there are leftover issues here. It is hard to track the closed issue when we have different contexts per user.
