### ISSUE TITLE
deployment of isolation Forest with TensorFlow serving

### ISSUE THREAD

**Issue by yarapathineni** [tensorflow/tensorflow#28894] opened 2019-05-21 04:04 UTC
Hi All,

I have developed anomaly detection model using sklearn Isolation Forest Algorithm, now would like to go for live inference.
can i use tensorflow service for live inference, if it possible , can you please provide me an example for same.

**Comment by muddham** [comment] 2019-05-21 14:21
@yarapathineni This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-05-27 10:44
@yarapathineni Please post your query in the [TF Serving repsoitory link](https://github.com/tensorflow/serving/issues/new), Closing this issue since it is not a bug or feature request

**Closed by muddham** 2019-05-27 10:44 UTC
Labels: comp:model, type:support
