### ISSUE TITLE
Android example: symbolic link error when running on Android Studio

### ISSUE THREAD

**Issue by Andrechang** [tensorflow/tensorflow#8406] opened 2017-03-14 18:59 UTC
I am trying to run android example app on Android studio. It builds fine with Bazel and Android Studio. But it gives this error when I run the app using Android Studio.

```
Error:Could not list contents of '/home/a/.cache/bazel/_bazel_root/6c98a6c54aeed71fa731445a9f51836b/execroot/tensorflow/external/local_jdk/src.zip'. Couldn't follow symbolic link.

**Comment by andrewharp** [comment] 2017-03-14 19:45
What version of bazel are you using? Are there any more logs around the error to give context?

Can you find the built APK and manually push it to your device and run?

**Comment by Andrechang** [comment] 2017-03-14 20:02
Bazel version: Build label: 0.4.4
I was able to push the apk by following the readme:
`adb install -r bazel-bin/tensorflow/examples/android/tensorflow_demo.apk`

But when I open the project in Android Studio it gives me only that error.
Event log gives only: 
`Error during Sync: Remote object doesn't exist!`

**Comment by andrewharp** [comment] 2017-03-14 20:11
I just tried running the project in AS on a fresh sync and am unable to reproduce -- I'd double check your Android Studio install (problematic plugins maybe?) and search for possible workaround that people with similarly errors are getting. Possibly a [device issue](https://code.google.com/p/android/issues/detail?id=57024)?

In any case I don't think this doesn't seem to be a TensorFlow issue, closing.

**Closed by andrewharp** 2017-03-14 20:11 UTC
