### ISSUE TITLE
can´t train image segmentation with model.fit

### ISSUE THREAD

**Issue by manuel-lincbiotech** [tensorflow/tensorflow#35499] opened 2019-12-30 15:50 UTC
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10.0.18362
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): through pip 
TensorFlow version (use command below): 2.0
Python version: 3.7
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: using CPU
GPU model and memory: using CPU

Hi there,
I'm just getting started with tensorflow and keras. So far I kind of understand how to do training on images and how to create my network. But I got some issues which I´m not sure how to solve, and could be due to some bug:

Basically I want to do image segmentation. I´m first trying to use data that is already in numpy. So I have numpy array of (10,180,180,1) (so 10 cases of images with 180x180 and 1 channel) for both the images and its respective segmentations. I have a simple network defined as:

inputs = tf.keras.layers.Input((180,180,1))
c1 = tf.keras.layers.SeparableConv2D(15,(5,5), use_bias=True, activation='relu',kernel_initializer='he_normal',padding='same')(inputs) 

c2 = tf.keras.layers.SeparableConv2D(20,(3,3),use_bias=True, activation='relu',kernel_initializer='he_normal',padding='same')(c1)

outputs = tf.keras.layers.Conv2D(1, (1, 1), activation='softmax')(c2)

Then I try to train it using:
`model.fit(training_ims,training_labels,batch_size=2,epochs=1)`

This gives this error:

> Train on 10 samples
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 496, in _call
    raise ValueError("Creating variables on a non-first call to a function"
ValueError: Creating variables on a non-first call to a function decorated with tf.function.
 2/10 [=====>........................] - ETA: 1s>>> training_ims

I´m quite new with this so I´m not remotely sure what is happening, tried looking for something similar before but didn´t find anything.

Thanks in advance

**Comment by manuel-lincbiotech** [comment] 2019-12-30 15:53
extra note:
If I suppress the batch_size input I get this different error:
`Train on 10 samples
10/10 [==============================] - 0s 1ms/sample
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Manuel_LincBiotech\Desktop\LincBiotech\python programs\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 487, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
TypeError: 'NoneType' object is not callable
`

**Comment by gadagashwini** [comment] 2019-12-31 04:29
@manuel-lincbiotech, Please provide the complete code to reproduce the reported issue. Thanks!

**Comment by manuel-lincbiotech** [comment] 2019-12-31 12:13
The complete code was just that:
inputs = tf.keras.layers.Input((180,180,1))
c1 = tf.keras.layers.SeparableConv2D(15,(5,5), use_bias=True, activation='relu',kernel_initializer='he_normal',padding='same')(inputs)

c2 = tf.keras.layers.SeparableConv2D(20,(3,3),use_bias=True, activation='relu',kernel_initializer='he_normal',padding='same')(c1)

outputs = tf.keras.layers.Conv2D(1, (1, 1), activation='softmax')(c2)

Then I try to train it using:
model.fit(training_ims,training_labels,batch_size=2,epochs=1)


However I think I discovered by myself the problem. It seems I needed to specify the output differently, after changing the the output to have the number of channels as the number of labels it worked. Seems we can´t use one channel with multiple label values.

**Comment by gadagashwini** [comment] 2020-01-03 05:50
@manuel-lincbiotech, Tried replicating the reported issue but looks like incomplete code, please take a look at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/4cf42bafafdf0127596c3095fef725af/untitled14.ipynb) and provide more information to analyze the issue. Thanks!

**Comment by gadagashwini** [comment] 2020-01-16 08:54
@manuel-lincbiotech, any update!

**Comment by gadagashwini** [comment] 2020-01-20 13:42
@manuel-lincbiotech, 
Issue is resolved. Are you happy to close this issue. Thanks!

**Comment by gadagashwini** [comment] 2020-01-29 08:31
Closing this, looks like issue is resolved. Please feel free to open if still issue persists.  Thanks

**Closed by gadagashwini** 2020-01-29 08:31 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by surya-narayanan** [comment] 2022-10-31 17:00
Similarly, earlier, my labels were y = np.array(0) or y = np.array(1). Changing them to y = np.array([1]) or the equivalent for 0, solved the problem.
