### ISSUE TITLE
tensorflow GPU-util on V100

### ISSUE THREAD

**Issue by colourful-tree** [tensorflow/tensorflow#35183] opened 2019-12-17 12:35 UTC
I trained a BERT model use 4 V100 GPU on one machine, and I noticed that:
A: batch_size = 60, Volatile GPU-util almost 80%~90%(nvidia-smi), global_step/sec=3.57(tf estimator log) 
B: batch_size = 80, Volatile GPU-util almost 80%~90%(nvidia-smi), global_step/sec=3.21(tf estimator log)
C: batch_size =10, Volatile GPU-util almost 60%~70%(nvidia-smi), global_step/sec=5.2(tf estimator log)

So, i was a little confused about these result. I suppose that throughput of A is 60*3.57=214, B is 80*3.21=256, C is 10*5.2=52. But Volatile GPU-util almost "same", which i mean 80%-90%, 80%-90%, 60%-70%. 

To be more specific, for experiment A, i suppose that 80%~90% GPU core was used, which is same  Volatile GPU-util when increase batch_size to 80(experiment B), so why Volatile GPU-util of A and B is almost same? Even reduce batch_size to 10, Volatile GPU-util even 60%~70%.

**Comment by ravikyram** [comment] 2019-12-19 08:23
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Request you to provide minimal standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by colourful-tree** [comment] 2019-12-19 09:07
**System information**
- Have I written custom code : with horovod, no others custom code.
- Mobile device : No
- TensorFlow installed from (source or binary): official docker
- TensorFlow version (use command below): 1.13.1 GPU
- Python version: 3.6.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: V100 with 16GB * 4

**Comment by ravikyram** [comment] 2019-12-19 09:46
@colourful-tree 

Will it be possible to share simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2019-12-30 08:45
@colourful-tree 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-01-10 10:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-01-10 10:52 UTC
Labels: TF 1.13, comp:gpu, stat:awaiting response, type:support
