### ISSUE TITLE
Analysis of target '@local_config_cc//:cc-compiler-x64_windows' failed;

### ISSUE THREAD

**Issue by nfk93** [tensorflow/tensorflow#23719] opened 2018-11-13 15:06 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source, both nightly and 1.12 tried
- TensorFlow version: 1.12 and nightly
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda environment
- Bazel version (if compiling from source): 0.19.1
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 9.0 and 7.4
- GPU model and memory: Geforce 770 4gb

**Describe the problem**
I'm trying to compile from source and I keep running into the same problem regardless of what release i try to build. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the guide https://www.tensorflow.org/install/source_windows promptly. Below is what i get when i try to make the package builder by running 'bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package'

**Any other info / logs**

(venv) B:\tensorflow>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
b:\tensorflow/tools/bazel.rc
nul
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.19.1 installed.
Please specify the location of python. [Default is B:\Program Files\Anaconda\envs\venv\python.exe]:

Found possible Python library paths:
  B:\Program Files\Anaconda\envs\venv\lib\site-packages
Please input the desired Python library path to use.  Default is [B:\Program Files\Anaconda\envs\venv\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]:

Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:

Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:

Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 3.0

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.

(venv) B:\tensorflow>bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
b:\tensorflow/.bazelrc
b:\tensorflow/tools/bazel.rc
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/local_config_cc/BUILD:106:1: in cc_toolchain rule @local_config_cc//:cc-compiler-x64_windows: Error while selecting cc_toolchain: Toolchain identifier 'msvc_x64' was not found, valid identifiers are [local_linux, local_darwin, local_windows]
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-x64_windows' failed; build aborted
INFO: Elapsed time: 29.408s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 55 targets configured)
    currently loading: tensorflow/python

**Comment by ymodak** [comment] 2018-11-14 00:08
Duplicate of #23674

**Comment by nfk93** [comment] 2018-11-15 12:33
I don't think it's just the .rc files that have a problem

I lowered bazel to 0.18.1, and I now get different errors. The full cmd output can be seen here https://pastebin.com/X8f8VZ5Z
The error on line 560 might be of interest, but I can't really make sense of all of it.

I'm compiling the nightly build. I'll try and checkout r1.12 and post the results of that aswell

**Comment by nfk93** [comment] 2018-11-15 12:42
Branch 1.12 fails much earlier. This is what I get:

B:\tensorflow>bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: Processed legacy workspace file b:\tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@png_archive//': Traceback (most recent call last):
        File "B:/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "B:/tensorflow/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "B:/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'B:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/nikolaj/_bazel_nikolaj/rm3fg6i6/external/png_archive" "-i" "B:/tensorflow/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 55.283s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (295 packages loaded)

**Comment by byronyi** [comment] 2018-11-16 01:56
@ymodak Met the same problem on Ubuntu Linux 16.04. I do not think it is a duplicate of #23674.

```bash
$ ./configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.19.1 installed.
Please specify the location of python. [Default is /home/byronyi/tf/bin/python]:


Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
Found possible Python library paths:
  /home/byronyi/tf/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/home/byronyi/tf/lib/python2.7/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]:
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]:
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]:


Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Do you wish to build TensorFlow with TensorRT support? [y/N]:
No TensorRT support will be enabled for TensorFlow.

Please specify the locally installed NCCL version you want to use. [Default is to use https://github.com/nvidia/nccl]:


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 7.0


Do you want to use clang as CUDA compiler? [y/N]:
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:


Do you wish to build TensorFlow with MPI support? [y/N]:
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apacha Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
Configuration finished
$ bazel build -c opt --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
ERROR: /srv/nfs4/home/byronyi/.cache/bazel/_bazel_byronyi/fe336f47afec8b033fb4b29a6628548f/external/local_config_cc/BUILD:57:1: in cc_toolchain rule @local_config_cc//:cc-compiler-k8: Error while selecting cc_toolchain: Toolchain identifier 'local' was not found, valid identifiers are [local_linux, local_darwin, local_windows]
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-k8' failed; build aborted
INFO: Elapsed time: 2.701s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (228 packages loaded, 1224 targets configured)
    currently loading: tensorflow/core ... (6 packages)
```

**Comment by cvanbogaert** [comment] 2018-11-16 16:21
A temporarty workaround is changing the cc toolchain from local to local_linux in (your home)/.cache/bazel/_bazel_(your name)/(your hash)/external/local_config_cc/BUILD

**Comment by nfk93** [comment] 2018-11-16 20:20
Unfortunately, this does not fix my issue, since I'm building on windows. I tried changing occurances of 'local' to 'local_windows' in the build file in C:\Users\<user name>\_bazel_<user name>\<hash>\external\local_config_cc, and it didn't help
Your issue might be related, but I think it's worth its own thread perhaps, so other users can more easily find it.

**Comment by tensorflowbutler** [comment] 2018-12-01 18:44
Nagging Assignee @meteorcloudy: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by meteorcloudy** [comment] 2018-12-03 09:47
This might be a bug in 0.19.1, can you try upgrading Bazel to 0.19.2?
Related issue https://github.com/bazelbuild/bazel/issues/6662

**Closed by meteorcloudy** 2018-12-03 09:47 UTC
Labels: type:build/install

**Comment by Qiuzhuang** [comment] 2019-01-21 05:46
> This might be a bug in 0.19.1, can you try upgrading Bazel to 0.19.2?
> Related issue [bazelbuild/bazel#6662](https://github.com/bazelbuild/bazel/issues/6662)

Upgrading to 0.19.2 looks good to me.

**Comment by nfk93** [comment] 2019-01-21 10:14
I ended up using Bazel 0.15.0 to compile tf r1.12. I did experience some timeout issues at first try, but a quick google search shows how to get around these, however I didn't need to do this, since it worked on the second try.

**Comment by shoutOutYangJie** [comment] 2019-06-23 08:29
> 
> 
> I ended up using Bazel 0.15.0 to compile tf r1.12. I did experience some timeout issues at first try, but a quick google search shows how to get around these, however I didn't need to do this, since it worked on the second try.
> 
> E: I should add, that i used a clean install of python, not using conda, and a virtuel environment (using virtualenv)

so you just used original python to solve this problem?

**Comment by danedang** [comment] 2020-04-13 10:06
bazel build :hello_main
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:143:15):
 - <builtin>
 - C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:317:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: E:/tensorflow/02/BUILD:8:1: //:hello_main depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//:hello_main' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):  
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 1.231s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
PS E:\TensorFlow\02> bazel clean --expunge
INFO: Starting clean.
PS E:\TensorFlow\02> bazel build :hello_main
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:143:15):
 - <builtin>
 - C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:317:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: E:/tensorflow/02/BUILD:8:1: //:hello_main depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//:hello_main' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):  
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 7.744s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 18 targets configured)
PS E:\TensorFlow\02> bazel
                                                           [bazel release 3.0.0]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specified in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
PS E:\TensorFlow\02> bazel version
Build label: 3.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:56:01 2020 (1586177761)
Build timestamp: 1586177761
Build timestamp as int: 1586177761
PS E:\TensorFlow\02>
