### ISSUE TITLE
Time Series Forecasting with LSTM and different/mixed frequencies

### ISSUE THREAD

**Issue by janwendt** [tensorflow/tensorflow#33408] opened 2019-10-16 06:40 UTC
I could not find anything in the docs about how to handle different frequencies of time series. I have a Dataset A with monthly data that i want to use to predict the values from Dataset B that contains quarterly based data. So the target value e.g. quarter 1 is based on the values from month 1-3.

Dataset A (Features):

| Month  | Value1 | Value2 | Value3 |
| ------------- | ------------- | ------------- | ------------- |
| 1  | 91  | 72 | 23 |
| 2  | 93  | 68 | 33 |
| 3  | 92  | 57 | 27 |
| 4  | 91  | 72 | 23 |
| 5  | 93  | 68 | 33 |
| 6  | 92  | 57 | 27 |

Dataset B (Target):

| Quarter   | Target_Value |
| ------------- | ------------- |
| 1  | 51  |
| 2  | 57  |

**Comment by oanush** [comment] 2019-10-17 08:35
@janwendt ,
Hi,This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
You can also refer this link related to [LSTM time series with mixed frequency data](https://stats.stackexchange.com/questions/210930/lstm-time-series-with-mixed-frequency-data) and also [article](http://roseyu.com/time-series-workshop/submissions/TSW2017_paper_10.pdf).Thanks!

**Comment by oanush** [comment] 2019-10-29 09:54
@janwendt ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2019-11-04 09:10
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-11-04 09:10 UTC
Labels: comp:apis, stat:awaiting response, type:support
