### ISSUE TITLE
tf.function should trace the additional attributes of a tensor

### ISSUE THREAD

**Issue by thadumi** [tensorflow/tensorflow#34270] opened 2019-11-14 12:41 UTC
Hello, I'm not sure if this should be considered as a Feature or a Bug

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Let's consider the following code (from TF 1.8) of the [loginctensornetwork](https://github.com/logictensornetworks/logictensornetworks/blob/master/logictensornetworks.py) project

```
def And(*wffs):
    if len(wffs) == 0:
        result = tf.constant(1.0)
        result.doms = []
    else:
        cross_wffs,_ = cross_args(wffs)
        label = "_AND_".join([wff.name.split(":")[0] for wff in wffs])
        result = tf.identity(F_And(cross_wffs),name=label)
        result.doms = cross_wffs.doms
    return result

def constant(label,value=None,
                 min_value=None,
                 max_value=None):
    label = "ltn_constant_"+label
    if value is not None:
        result = tf.constant(value,name=label)
    else:
        result = tf.Variable(tf.random_uniform(
                shape=(1,len(min_value)),
                minval=min_value,
                maxval=max_value,name=label))
    result.doms = []
    return result

def cross_args(args):
    result = args[0]
    for arg in args[1:]:
        result,_ = cross_2args(result,arg)
    result_flat = tf.reshape(result,
                             (tf.reduce_prod(tf.shape(result)[:-1]),
                              tf.shape(result)[-1]))
    result_args = tf.split(result_flat,[tf.shape(arg)[-1] for arg in args],1)
    return result, result_args

def cross_2args(X,Y):
    if X.doms == [] and Y.doms == []:
        result = tf.concat([X,Y],axis=-1)
        result.doms = []
        return result,[X,Y]
    X_Y = set(X.doms) - set(Y.doms)
    Y_X = set(Y.doms) - set(X.doms)
    eX = X
    eX_doms = [x for x in X.doms]
    for y in Y_X:
        eX = tf.expand_dims(eX,0)
        eX_doms = [y] + eX_doms
    eY = Y
    eY_doms = [y for y in Y.doms]
    for x in X_Y:
        eY = tf.expand_dims(eY,-2)
        eY_doms.append(x)
    perm_eY = []
    for y in eY_doms:
        perm_eY.append(eX_doms.index(y))
    eY = tf.transpose(eY,perm=perm_eY + [len(perm_eY)])
    mult_eX = [1]*(len(eX_doms)+1)
    mult_eY = [1]*(len(eY_doms)+1)
    for i in range(len(mult_eX)-1):
        mult_eX[i] = tf.maximum(1,tf.floor_div(tf.shape(eY)[i],tf.shape(eX)[i]))
        mult_eY[i] = tf.maximum(1,tf.floor_div(tf.shape(eX)[i],tf.shape(eY)[i]))
    result1 = tf.tile(eX,mult_eX)
    result2 = tf.tile(eY,mult_eY)
    result = tf.concat([result1,result2],axis=-1)
    result1.doms = eX_doms
    result2.doms = eX_doms
    result.doms = eX_doms
    return result,[result1,result2]
```

In this project, we need to store some metainformation within every tensor for ensuring the correct behaviour of functions like And regardless of the order of the arguments. 
Migrating to Tensorflow 2.0 if I decorate a function with @tf.function this function will not return the additional doms attribute of the tensor. This attributes, as you can see in functions like cross_2args are mandatory for ensuring the correctness of the flow. 
My goal is to ensure that if a function is adding a set of attributes to a tensor before returning it, decorating the same function with tf.function should in the same way return a tensor which has the same set of additional attributes.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone who wants to add new attributes to a tensor for having meta-information about it during the forward process

**Any Other info.**

**Comment by gadagashwini** [comment] 2019-11-15 08:58
@thadumi, Thanks for reporting this issue.
Will it be possible to provide the complete standalone code to reproduce the reported issue here. Thanks!

**Comment by thadumi** [comment] 2019-11-15 13:18
Hi @gadagashwini ,
please take a look at the following example

```python
import tensorflow as tf

def foo(label, tensor=None, min_value=None, max_value=None):
    if tensor is not None and tf.is_tensor(tensor):
        result = tf.identity(tensor, name=label)
    else:
        result = tf.random.uniform(shape=(1, len(min_value)),
                                   minval=min_value,
                                   maxval=max_value, name=label)
    result._bar = [label]
    return result


@tf.function
def fooAutoGraph(label, tensor=None, min_value=None, max_value=None):
    if tensor is not None and tf.is_tensor(tensor):
        result = tf.identity(tensor, name=label)
    else:
        result = tf.random.uniform(shape=(1, len(min_value)),
                                   minval=min_value,
                                   maxval=max_value, name=label)
    result._bar = [label]
    return result


assert hasattr(foo('a', min_value=[0.] * 10, max_value=[1.] * 10), '_bar') # this works
assert hasattr(fooAutoGraph('a', min_value=[0.] * 10, max_value=[1.] * 10), '_bar') # this will fail
```

**Comment by thadumi** [comment] 2019-11-17 22:32
I'd like to point out that the same issue exists also for Keras subclassing
The workaround for Keras is the following 

```python
class MyLayer(KL.Layer):

    def __init__(self, *args, **kwargs):
        super(MyLayer, self).__init__(*args, **kwargs)

    def __call__(self, inputs, *args, **kwargs):
        outputs = super(MyLayer, self).__call__(inputs, *args, **kwargs)
        flat_outputs = nest.flatten(outputs)

        meta = self.compute_meta(inputs, **kwargs)
        for output in flat_outputs:
            output._my_meta = meta

        return outputs

    def compute_meta(self, inputs, **kwargs):
        return [] # no metadata
```

**Comment by thadumi** [comment] 2019-11-19 11:00
@jvishnuvardhan I'd like to contribute. Could you tell me where I should add this feature?

**Comment by kkimdev** [comment] 2019-11-20 08:51
@mdanatg FYI

Unfortunately, `@tf.function` is supposed to trace only direct Tensor manipulations.  I agree that it's not ideal but currently it's out of the scope for `@tf.function`.  For now, I suggest to manage the metadata outside of `@tf.function`

FYI, `@tf.function` is defined here https://github.com/tensorflow/tensorflow/blob/7cebef3019e9ec10fd81a021e56233527ae7c9d1/tensorflow/python/eager/def_function.py#L970

**Comment by mdanatg** [comment] 2019-11-20 14:31
Indeed, it would be cleaner to encapsulate those tensors inside structures that `tf.function` supports, like `namedtuple` objects. These structures could then carry the values along with the metadata. In general, tensors generally have semantics of opaque values (unfortunately not uniformly implemented right now), so in theory they should not allow setting custom attributes (they should behave more like `int` or `np.ndarray` in that regard).

Here's an example which uses `namedtuple`:

```
LblStruct = collections.namedtuple('LblStruct', ('value', 'bar'))

@tf.function
def foo_with_namedtuple(lbl_struct, tensor=None, min_value=None, max_value=None):
    label = lbl_struct.value
    if tensor is not None and tf.is_tensor(tensor):
        result = tf.identity(tensor, name=label)
    else:
        result = tf.random.uniform(shape=(1, len(min_value)),
                                   minval=min_value,
                                   maxval=max_value, name=label)
    return LblStruct(result, [label])

lbl_struct = LblStruct('a', '_bar')
assert hasattr(foo_with_namedtuple(lbl_struct, min_value=[0.] * 10, max_value=[1.] * 10), 'bar')
```

Side discussion --

Technically speaking, preserving custom attributes would be doable for static attribute modifications (that is, not for attributes that are set inside data-dependent control flow), like in this hand-coded example:

```
def foo(label, tensor=None, min_value=None, max_value=None):
    if tensor is not None and tf.is_tensor(tensor):
        result = tf.identity(tensor, name=label)
    else:
        result = tf.random.uniform(shape=(1, len(min_value)),
                                   minval=min_value,
                                   maxval=max_value, name=label)
    result._bar = [label]
    return result

def foo_with_custom_attributes(label, tensor=None, min_value=None, max_value=None):

  @tf.function
  def wrapper(label, tensor, min_value, max_value):
    return foo(label, tensor, min_value, max_value)

  result = wrapper(label, tensor, min_value, max_value)
  result._bar = [label]
  return result

assert hasattr(foo('a', min_value=[0.] * 10, max_value=[1.] * 10), '_bar') # this works
assert hasattr(foo_with_custom_attributes('a', min_value=[0.] * 10, max_value=[1.] * 10), '_bar') # this works too
assert hasattr(tf.function(foo)('a', min_value=[0.] * 10, max_value=[1.] * 10), '_bar') # this fails
```

When it traces its body, `tf.function` creates new tensor objects for its arguments and return values (e.g. arguments are replaced with placeholders that will be fed at execution), which is when custom attributes get lost. So `tf.function` could copy them over, if this was done with care, to avoid copying attributes that it should not (we don't want to accidentally set a non-user attribute).

If you'd like to experiment with it, that's probably best done deep inside `tf.function` around the point when if calls the original function, which should be [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/func_graph.py#L978). That's where AutoGraph proper is applied as well, if you look a couple of lines up.

Again, the above is purely an academic point, because I think this caveat is valid not just for `tf.function`, but may other ops as well, like `tf.cond, `tf.while_loop`, even `tf.identity` - any of these are expected to replace respective arguments without warning - they only preserve values; so if anything,  would require a lot of code.

**Comment by thadumi** [comment] 2019-11-26 12:52
Hi @mdanatg sorry for the delay.
Thanks for the explanation. I refactored the code for working with something very similar to the wrapper proposal.

**Comment by rmothukuru** [comment] 2021-06-29 12:59
@thadumi,
Can you please let us know if [this comment](https://github.com/tensorflow/tensorflow/issues/34270#issuecomment-556028137) has resolved your issue so that we can close it? Thanks!

**Closed** 2021-07-13 14:34 UTC
Labels: TF 2.0, comp:core, stalled, stat:awaiting response, type:feature
