### ISSUE TITLE
Allow use of gitter.im for tensorflow/tensorflow repo

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#3078] opened 2016-06-28 15:18 UTC
As far as I could tell, there is no place for the community to discuss tensorflow in realtime; the recommendations all seem to be about asking specific questions in a detailed async fashion.

It would be nice if there was a gitter.im or IRC channel for tensorflow so that the community could interact more easily. not even as a dedicated support channel.

There is already a gitter.im for skflow, but since fewer people know about skflow, let alone the gitter.im for it, it's pretty small: https://gitter.im/tensorflow/skflow

It would be even nicer if the channel was linked from the repo, but gitter.im is nice since it has some automatic discoverability if you're already familiar with gitter

**Comment by aselle** [comment] 2016-06-28 17:39
This is a duplicate of #132, and unfortunately our bandwidth is quite limited right now. Things have not changed in terms of our ability to support another official channel of communication, unfortunately.

**Closed by aselle** 2016-06-28 17:39 UTC
Labels: docs, duplicate, triaged

**Comment by kuza55** [comment] 2016-06-29 14:36
Is there a way to have an unofficial but discoverable place for real-time communication? I'm more interested in talking to members of the community than recieving official support.
