### ISSUE TITLE
Tensorflow Lite demo app with inception-v3/Mobilenet_v1 (float) model crashes

### ISSUE THREAD

**Issue by atrah22** [tensorflow/tensorflow#14719] opened 2017-11-20 12:23 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 14.04
- **Python version**: 3.4.3
- **Bazel version (if compiling from source)**: 0.5.4

### Describe the problem
Device: Galaxy S8
I downloaded the "Inception V3 Slim 2016" from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md . I pushed the imagenet_2015_label_strings.txt and the "inceptionv3_non_slim_2015.tflite" to the asset folder

I edited the ImageClassifier.java of tflite demo app. The changes are the followings:
private static final String MODEL_PATH = "/inceptionv3_non_slim_2015.tflite";
static final int DIM_IMG_SIZE_X = 299;
static final int DIM_IMG_SIZE_Y = 299;

The app hangs when it starts! (I could run the app with the default mobilenet quantized graph).
Similar is the case with mobilenet_v1_224_Float graph as well (the app hangs or crashes). I assume, the float model graph is not yet supported by TF Lite. However, in the documentation its written that it does support float for most operations. I am thinking the error is due to image pre-processing output and input size of float model grpah. The error log is stated below:

The Error log:
11-21 14:31:43.034 2111-2416/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                                    Process: android.example.com.tflitecamerademo, PID: 2111
                                                                                    java.lang.IllegalArgumentException: Failed to get input dimensions. 0-th input should have 1072812 bytes, but found 268203 bytes.
                                                                                        at org.tensorflow.lite.NativeInterpreterWrapper.getInputDims(Native Method)
                                                                                        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:82)
                                                                                        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
                                                                                        at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                                                                                        at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:112)
                                                                                        at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:663)
                                                                                        at com.example.android.tflitecamerademo.Camera2BasicFragment.-wrap0(Camera2BasicFragment.java)
                                                                                        at com.example.android.tflitecamerademo.Camera2BasicFragment$4.run(Camera2BasicFragment.java:558)
                                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

### Additional Questions:
1) On the app the the tensorflow lite graph format is ".tflite". However, on the documentation https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md the format is written as ".lite"

**Comment by pkurogerjs** [comment] 2017-11-21 09:28
I met the same problem and I think I've found how to solve it.
First of all, the demo app is designed to use the quantized model, in which the input type and parameters' type are both 8-bit. But for the float version, the input type should be 32-bit. You can see from your error log that the expected bytes is exactly 4 times of the actual bytes!

So I think you need to modify the input type of the demo app to fit the 32-bit input.

**Comment by atrah22** [comment] 2017-11-21 10:59
Thank you for the reply. @pkurogerjs
However, The image data is already converted to floating point in the TFLiteDemo ImageClassifier.java file

"/** Writes Image data into a {@code ByteBuffer}. */
  private void convertBitmapToByteBuffer(Bitmap bitmap) {
    if (imgData == null) {
      return;
    }
    imgData.rewind();
    bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
    // Convert the image to floating point.
    int pixel = 0;
    long startTime = SystemClock.uptimeMillis();
    for (int i = 0; i < DIM_IMG_SIZE_X; ++i) {
      for (int j = 0; j < DIM_IMG_SIZE_Y; ++j) {
        final int val = intValues[pixel++];
        imgData.put((byte) ((val >> 16) & 0xFF));
        imgData.put((byte) ((val >> 8) & 0xFF));
        imgData.put((byte) (val & 0xFF));
      }
    }
"

**Comment by pkurogerjs** [comment] 2017-11-22 02:44
Well, I don't agree with the comment in the code. It just extract the RGB value from a pixel into 8-bit bytes. 
You can see in ImageClassifier.java that the line "tflite.run(imgData, labelProbArray);"  takes a 8-bit format input and a 8-bit format output tensors. You need to change both of them to 32-bit float arrays.

I've successfully run the mobilenet_224 float version. the input is a 4-dim float array and the output put is a 1*num_of_label_types array.

I found this problem by reading the source code in the directory org.tenslow.lite. 

Hope this will help you.

**Comment by atrah22** [comment] 2017-11-22 05:02
@pkurogerjs ,
I tried to make 4-dim float array for the input and it shows the errore below. Mainly "ava.lang.IllegalArgumentException: Cannot convert an TensorFlowLite tensor with type FLOAT32 to a Java object of type [[B (which is compatible with the TensorFlowLite type UINT8)". So the input "imgData" is expected to be "ByteBuffer" only! I am confused. Again on the TF lite java api documentation it says that input can multidimensional array / ByteBuffer but ByteBuffer is preferred. Can you please show me how you resolved this issue or what parts of the code did you change ?

E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                  Process: android.example.com.tflitecamerademo, PID: 4036
                  java.lang.IllegalArgumentException: Cannot convert an TensorFlowLite tensor with type FLOAT32 to a Java object of type [[B (which is compatible with the TensorFlowLite type UINT8)
                      at org.tensorflow.lite.Tensor.copyTo(Tensor.java:36)
                      at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:122)
                      at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                      at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:116)
                      at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:666)
                      at com.example.android.tflitecamerademo.Camera2BasicFragment.access$900(Camera2BasicFragment.java:69)
                      at com.example.android.tflitecamerademo.Camera2BasicFragment$5.run(Camera2BasicFragment.java:561)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pkurogerjs** [comment] 2017-11-22 05:16
I think this exception is because your labelProbArray(line 77) is still a byte array. Change its type to float, please. The exception is thrown when calling something like input.copyTo(output) in Tensorflow Lite's java code, which requires that the type input and  output should be the same.

Besides, it seems that for inception v3, the input image size should be 299*299.
I ran this model, the recognition results seems right, but the output probabilities are larger than 1.0. I'm confused about that

**Comment by atrah22** [comment] 2017-11-22 05:29
@pkurogerjs, Thankyou for the help. It works. I am initially more eager towards performance benchmarking between quantized vs float models.

**Comment by kidsung** [comment] 2017-11-24 10:57
Any difference between Slim and non-slim one? I have had also the output probabilities are larger than 1.0. and the recognition does work well. It does not return a right answer

**Comment by drricksanchez321** [comment] 2017-11-29 19:26
I was able to get it working with inception v3 non-slim 2015 by making @kidsung 's changes plus:

replacing the imgData.put's with:
```
 imgData[0][i][j][0] = (float) ((val >> 16) & 0xFF);
 imgData[0][i][j][1] = (float) ((val >> 8) & 0xFF);
 imgData[0][i][j][2] = (float) (val  & 0xFF);
```
commenting out 
```
imgData.rewind();
```
and 
```
imgData.order(ByteOrder.nativeOrder());
```

and modifying the declarations:
```
private float[][][][] imgData = null;
private float[][] labelProbArray = null;
```

Additionally, I received a tensor length error for the labels, the file had 1001 and (somewhere) it expected 1008, so I filled in 7 lines of foo1, foo2, etc.

**Comment by aselle** [comment] 2017-11-29 20:45
Seems like the issue is resolved. Could you please close it if it is?

**Closed** 2017-11-30 01:16 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by kidsung** [comment] 2017-11-30 18:10
Thank you (@drricksanchez321) But it still does not work well. It returns pill bottle or honeycomb when a camer see a mouse).
I don't know what it is wrong with that. 

Please help me to sort it out (@pkurogerjs @atrah22 ) if you does not have those issues before it is closed

My full change of code is like below. (in the case of non_slim, I put 8 padding you mentioned. @drricksanchez321

 public class ImageClassifier {
@@ -43,21 +43,21 @@ public class ImageClassifier {
   private static final String TAG = "TfLiteCameraDemo";
 
   /** Name of the model file stored in Assets. */
-  private static final String MODEL_PATH = "mobilenet_quant_v1_224.tflite";
+  private static final String MODEL_PATH = "inceptionv3_non_slim_2015.tflite";
 
   /** Name of the label file stored in Assets. */
-  private static final String LABEL_PATH = "labels.txt";
+  private static final String LABEL_PATH = "labels_noslim.txt";
 
   /** Number of results to show in the UI. */
-  private static final int RESULTS_TO_SHOW = 3;
+  private static final int RESULTS_TO_SHOW = 1;
 
   /** Dimensions of inputs. */
   private static final int DIM_BATCH_SIZE = 1;
 
   private static final int DIM_PIXEL_SIZE = 3;
 
-  static final int DIM_IMG_SIZE_X = 224;
-  static final int DIM_IMG_SIZE_Y = 224;
+  static final int DIM_IMG_SIZE_X = 299;
+  static final int DIM_IMG_SIZE_Y = 299;
 
   /* Preallocated buffers for storing image data in. */
   private int[] intValues = new int[DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y];
@@ -69,10 +69,12 @@ public class ImageClassifier {
   private List<String> labelList;
 
   /** A ByteBuffer to hold image data, to be feed into Tensorflow Lite as inputs. */
-  private ByteBuffer imgData = null;
+  //private ByteBuffer imgData = null;
+  private float[][][][] imgData = null;
 
   /** An array to hold inference results, to be feed into Tensorflow Lite as outputs. */
-  private byte[][] labelProbArray = null;
+  //private byte[][] labelProbArray = null;
+  private float[][] labelProbArray = null;
 
   private PriorityQueue<Map.Entry<String, Float>> sortedLabels =
       new PriorityQueue<>(
@@ -88,11 +90,13 @@ public class ImageClassifier {
   ImageClassifier(Activity activity) throws IOException {
     tflite = new Interpreter(loadModelFile(activity));
     labelList = loadLabelList(activity);
-    imgData =
-        ByteBuffer.allocateDirect(
-            DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
-    imgData.order(ByteOrder.nativeOrder());
-    labelProbArray = new byte[1][labelList.size()];
+    //imgData =
+    //    ByteBuffer.allocateDirect(
+    //        DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
+    //imgData.order(ByteOrder.nativeOrder());
+    //labelProbArray = new byte[1][labelList.size()];
+    imgData = new float[DIM_BATCH_SIZE][DIM_IMG_SIZE_X][DIM_IMG_SIZE_Y][DIM_PIXEL_SIZE];
+    labelProbArray = new float[1][labelList.size()];
     Log.d(TAG, "Created a Tensorflow Lite Image Classifier.");
   }
 
@@ -147,7 +151,7 @@ public class ImageClassifier {
     if (imgData == null) {
       return;
     }
-    imgData.rewind();
+    //imgData.rewind();
     bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
     // Convert the image to floating point.
     int pixel = 0;
@@ -155,9 +159,12 @@ public class ImageClassifier {
     for (int i = 0; i < DIM_IMG_SIZE_X; ++i) {
       for (int j = 0; j < DIM_IMG_SIZE_Y; ++j) {
         final int val = intValues[pixel++];
-        imgData.put((byte) ((val >> 16) & 0xFF));
-        imgData.put((byte) ((val >> 8) & 0xFF));
-        imgData.put((byte) (val & 0xFF));
+        //imgData.put((byte) ((val >> 16) & 0xFF));
+        //imgData.put((byte) ((val >> 8) & 0xFF));
+        //imgData.put((byte) (val & 0xFF));
+        imgData[0][i][j][0] = ((float)((val >> 16) & 0xFF));
+        imgData[0][i][j][1] = ((float)((val >> 8) & 0xFF));
+        imgData[0][i][j][2] = ((float)(val & 0xFF));
       }
     }
     long endTime = SystemClock.uptimeMillis();
@@ -168,7 +175,7 @@ public class ImageClassifier {
   private String printTopKLabels() {
     for (int i = 0; i < labelList.size(); ++i) {
       sortedLabels.add(
-          new AbstractMap.SimpleEntry<>(labelList.get(i), (labelProbArray[0][i] & 0xff) / 255.0f));
+          new AbstractMap.SimpleEntry<>(labelList.get(i), (labelProbArray[0][i])));
       if (sortedLabels.size() > RESULTS_TO_SHOW) {
         sortedLabels.poll();
       }

**Comment by OdingdongO** [comment] 2017-12-04 14:08
I have the same problem with   @kidsung 
Is there a solution?

**Comment by OdingdongO** [comment] 2017-12-04 14:15
After changing the float inceptionv3 model, can the model correctly identify common items?
Such as the mouse @atrah22 @pkurogerjs @drricksanchez321

**Comment by OdingdongO** [comment] 2017-12-04 15:14
After modifying ImageClassifier.java , I can run float model from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md;
test the Inception model(Inception V3 Slim 2016)and  Mobilenet model(Mobilenet 1.0 224 Float)
the inceptionv3_slim_2016.tflite model inference time is 2260ms,
the  mobilenet_v1_1.0_224.tflite model inference time is 500ms and mobilenet_quant_v1_224.tflite is 65ms.
 add:
  private static final int IMAGE_MEAN = 128;
  private static final float IMAGE_STD = 128.0f;
change:
 private byte[][] labelProbArray = null;
.............................................................
 private float[][] labelProbArray = null;

imgData = ByteBuffer.allocateDirect(
            DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
................................................................
imgData = ByteBuffer.allocateDirect(
            4*DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
   
 labelProbArray = new byte[1][labelList.size()];
-----------------------------------------------------------
 labelProbArray = new float[1][labelList.size()];

imgData.put((byte) ((val >> 16) & 0xFF));
imgData.put((byte) ((val >> 8) & 0xFF));
imgData.put((byte) (val & 0xFF));
------------------------------------------------------------------
  imgData.putFloat((((val >> 16) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
  imgData.putFloat((((val >> 8) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
  imgData.putFloat(((val & 0xFF)-IMAGE_MEAN)/IMAGE_STD);

if use the inception model,modifying
 static final int DIM_IMG_SIZE_X = 224;
 static final int DIM_IMG_SIZE_Y = 224;
----------------------------------------------------------
static final int DIM_IMG_SIZE_X  =  299;
static final int DIM_IMG_SIZE_Y  =  299;

**Comment by austingg** [comment] 2017-12-10 04:19
@atrah22  Is there any result about quantized mode vs. float model ?

**Comment by trjoker** [comment] 2017-12-27 03:20
@OdingdongO

**Comment by trjoker** [comment] 2017-12-27 03:31
@OdingdongO  
I tried your code and got  an error.
`    new AbstractMap.SimpleEntry<>(labelList.get(i), (labelProbArray[0][i] & 0xff) / 255.0f));`
Operatpr '&' cannot be applied to 'float','int'
I use two way to  fix .
` sortedLabels.add(new AbstractMap.SimpleEntry<>(labelList.get(i), (labelProbArray[0][i])));`
and 
`sortedLabels.add(new AbstractMap.SimpleEntry<>(labelList.get(i), ((int)labelProbArray[0][i] & 0xff) / 255.0f));`
I can run inceptionv3_slim_2016 model, but the predication get a bad result. It has no original effect.
Can you help me to solve the problem? Do you had a better prediction？

**Comment by offbye** [comment] 2017-12-29 07:55
I  can  run  inceptionv3_slim_2016.tflite model after change some code.  The inference time is about 1200ms on my Huawei kirin960 phone.  It' s  too slow!!

https://stackoverflow.com/questions/47463204/tensorflow-lite-convert-error-for-the-quantized-graphdef

**Comment by ghostsun89** [comment] 2018-01-24 10:57
Hi @OdingdongO, I have a question about the image mean and std value of the inceptionv3_slim_2016 model, why the mean and std value are 128? How did you get the value?

**Comment by Johnson145** [comment] 2018-02-07 14:41
@ghostsun89 The mean and std values are e.g. listed [in this script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py). They don't refer explicitly to the slim model though.

I combined the results collected here and created a pr: #16833.
The inception confidence score is still unnormalized though. Has anybody here already managed to scale it to [0, 1]? Any further help is appreciated very much.

**Comment by freedomtan** [comment] 2018-02-08 02:03
it seems the output of the [inceptionv3 tflite model released by google](https://storage.googleapis.com/download.tensorflow.org/models/tflite/inception_v3_slim_2016_android_2017_11_10.zip) is problematic. I'll create another issue later. If you run [label_image for tflite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/label_image/label_image.md), you'll get

```bash
> ./label_image -m inceptionv3_slim_2016.tflite
Loaded model inceptionv3_slim_2016.tflite
resolved reporter
invoked 
average time: 1009.48 ms 
8.06111: 653 military uniform
6.19022: 668 mortarboard
5.83456: 401 academic gown
5.26993: 835 suit
4.80701: 855 theater curtain
```

If you convert InceptionV3 yourself, 
```bash
> curl http://download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz \
 | tar -C /tmp -xzf -
> bazel run --config=opt   //tensorflow/contrib/lite/toco:toco --  \
--input_file=/tmp/inception_v3_2016_08_28_frozen.pb  \
--output_file=/tmp/inceptionv3.tflite   --input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE   --inference_type=FLOAT   --input_shape=1,299,299,3 \
--input_array=input   --output_array=InceptionV3/Predictions/Reshape_1
```

and push the /tmp/inceptionv3.tflite to your android devices, then you can see expected results like

```bash
> ./label_image -m inceptionv3.tflite             
Loaded model inceptionv3.tflite
resolved reporter
invoked 
average time: 1020.93 ms 
0.496246: 653 military uniform
0.0764156: 668 mortarboard
0.0535454: 401 academic gown
0.030444: 835 suit
0.0191629: 855 theater curtain
```

**Comment by Johnson145** [comment] 2018-02-12 13:56
@ghostsun89 @OdingdongO I checked the mean and std values again and think the ones posted above are incorrect. They are correct for the usage of the "old non-slim" inception-v3 version. However, the discussed slim version requires `mean=0` and `std=255`. [See this](https://github.com/tensorflow/models/issues/3346) for some additional information.

**Comment by duplex143** [comment] 2018-06-19 08:30
@atrah22 @drricksanchez321 @pkurogerjs I'm trying to modify [MainActivity.java](https://github.com/googlecodelabs/mlkit-android/blob/master/custom-model/final/app/src/main/java/com/google/firebase/codelab/mlkit_custommodel/MainActivity.java) at [googlecodelabs/mlkit-android](https://github.com/googlecodelabs/mlkit-android/tree/master/custom-model/final) and ran into a similar issue. I followed the above modifications and I finally ran into **java.nio.BufferOverflowException** error.
See [this](https://github.com/googlecodelabs/mlkit-android/issues/5) for more info.

**Comment by alokranjan007** [comment] 2018-08-21 11:42
Hello all @pkurogerjs @OdingdongO @aselle @atrah22 ,

I am facing the same problem with `inference_type=FLOAT`. However, the model i am trying is ssd_mobilenet_v1_coco. I had successfully trained the model on my custom data sets and is working fine.
But when porting to android it is throwing error related to  

> mismatched Tensor + input buffer size. The error reads as
8-16 10:26:42.107 28242 28257 E AndroidRuntime: FATAL EXCEPTION: inference
08-16 10:26:42.107 28242 28257 E AndroidRuntime: Process: org.tensorflow.lite.demo, PID: 28242
08-16 10:26:42.107 28242 28257 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.

where should I change the input size for the float inference. I would appreciate your pain if you could share any detailed steps (i am new to tensorflow and tflite).

Thank you for your time!

**Comment by duplex143** [comment] 2018-08-21 13:28
@alokranjan007 Go through the comments in both [question and answer](https://stackoverflow.com/questions/50923996/changes-required-for-using-non-quantized-tflite-files-in-mainactivity-java). It may help you a bit.

**Comment by alokranjan007** [comment] 2018-08-21 14:36
@duplex143 Thank you for you help! But I could not find any MainActivity.java file for SSD_Mobilenet_V1. Since I am using the detection app there is detectorActivity file. Nevertheless, there is no such line related to ByteBuffer like the one discussed above and the mentioned link by you.
Could you help me to understand about the necessary changes to be made for SSD_Mobilenet for float inference.

Thank you,

**Comment by shahid14** [comment] 2018-12-14 16:53
> After modifying ImageClassifier.java , I can run float model from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md;
> test the Inception model(Inception V3 Slim 2016)and Mobilenet model(Mobilenet 1.0 224 Float)
> the inceptionv3_slim_2016.tflite model inference time is 2260ms,
> the mobilenet_v1_1.0_224.tflite model inference time is 500ms and mobilenet_quant_v1_224.tflite is 65ms.
> add:
> private static final int IMAGE_MEAN = 128;
> private static final float IMAGE_STD = 128.0f;
> change:
> private byte[][] labelProbArray = null;
> .............................................................
> private float[][] labelProbArray = null;
> 
> imgData = ByteBuffer.allocateDirect(
> DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
> ................................................................
> imgData = ByteBuffer.allocateDirect(
> 4*DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
> 
> labelProbArray = new byte[1][labelList.size()];
> .............................................................
> labelProbArray = new float[1][labelList.size()];
> 
> imgData.put((byte) ((val >> 16) & 0xFF));
> imgData.put((byte) ((val >> 8) & 0xFF));
> imgData.put((byte) (val & 0xFF));
> .............................................................
> imgData.putFloat((((val >> 16) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
> imgData.putFloat((((val >> 8) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
> imgData.putFloat(((val & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
> 
> if use the inception model,modifying
> static final int DIM_IMG_SIZE_X = 224;
> static final int DIM_IMG_SIZE_Y = 224;
> .............................................................
> static final int DIM_IMG_SIZE_X = 299;
> static final int DIM_IMG_SIZE_Y = 299;

**The above solutions is differentiating between byte type & float type Buffers configuration, for resizing your input tensor, you can check following link :**
 https://github.com/tensorflow/tensorflow/issues/23940#issuecomment-447380387

**Comment by Ammu1991** [comment] 2020-01-13 07:22
Hello All,

I am working on the similar issue.I want to use latest ssd_mobilenet_v3_small_coco_2019_08_14.
I am getting error as TensorFlowLite buffer with 307200 bytes and a Java Buffer with 270000 bytes.
I checked few of the mentioned  method above to solve this.Still no luck !!
Could you help me to understand about the necessary changes to be made for float inference.

Thank you,

**Comment by freedomtan** [comment] 2020-01-13 08:02
@Ammu1991  307200 = 320x320x3 and 270000 = 300x300x3. It's quite obvious that the model is expecting 320x320 and the Java code assumes 300x300x3.

**Comment by Ammu1991** [comment] 2020-01-13 08:46
Hello All,

For coco_ssd_mobilenet_v1_1.0_quant_2018_06_29 model in the sample example project.In
download_model.gradle their is web link from where v1 model   is getting downloaded.

http://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip

Anybody knows similar link for  latest ssd_mobilenet_v3_small_coco_2019_08_14 for download_model.gradle 

Thank you,

**Comment by Ammu1991** [comment] 2020-01-13 09:13
@freedomtan  Thank you for you help!.I know but what change I have to make in the code.
I have replaced V1 model with V3 version.Since I do not have label.txt file for v3. Can you guide me how to use V3 model in the project.

Thank you,

**Comment by Ammu1991** [comment] 2020-01-13 09:17
@freedomtan Thank you for you help!.I know but what change I have to make in the code.
I have replaced V1 model with V3 version.Since I do not have labelmap.txt file for v3. Can you guide me how to use V3 model in the project.

Thank you,

**Comment by Ammu1991** [comment] 2020-01-13 09:29
Hello All,

For coco_ssd_mobilenet_v1_1.0_quant_2018_06_29 model in the sample example project.In
download_model.gradle their is web link from where v1 model is getting downloaded.

http://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip

Anybody knows similar link for latest ssd_mobilenet_v3_small_coco_2019_08_14 in download_model.gradle from where I can get complete repository with all corresponding file set

Thank you,
