### ISSUE TITLE
two neural networks running at the same time GPU-Util drops 

### ISSUE THREAD

**Issue by andres0820m** [tensorflow/tensorflow#31285] opened 2019-08-02 17:26 UTC
I'm running two neural networks on the same process, one depends  on the other. the first one is an image classifier (YOLO) the other one is a Lstm that depends on the deteccions of the yolo, when I run more than one YOLO network everythings goin right, the util of the gpu is hight, same when I run more than one Lstm, the problem is when the two networks runs together, the gpu-uils drops and the all process is slow. I tried in python and c++ tensorflow api same results any help ?

**Comment by gadagashwini** [comment] 2019-08-05 05:46
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Thanks!

**Comment by andres0820m** [comment] 2019-08-05 11:59
I'm using Ubuntu 18.04 x86 64 bits, I'm using tensorflow 1.14 I've tried from binary and compiling from source, same problem

**Comment by andres0820m** [comment] 2019-08-05 14:43
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> Thanks!

I'm using Ubuntu 18.04 x86 64 bits, I'm using tensorflow 1.14 I've tried from binary and compiling from source, same problem hope we can figure out what's going on

**Comment by gadagashwini** [comment] 2019-08-06 05:06
@andres0820m Please provide us the minimal reproducible code snippet. It will indeed help us to move faster.Thanks!

**Comment by gadagashwini** [comment] 2019-08-16 08:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-16 08:32 UTC
Labels: TF 1.14, comp:model, stat:awaiting response, type:support
