### ISSUE TITLE
Cuda Configuration Error: Cannot find libdevice.10.bc under /usr/local/cuda-8.0

### ISSUE THREAD

**Issue by TonyTangYu** [tensorflow/tensorflow#20614] opened 2018-07-07 13:15 UTC
I want to install TensorFlow through compiling from source. After I finished the configure, I run the command `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`. But some errors occurs. Here are the info:
```
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
		_create_local_cuda_repository(repository_ctx)
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 1001, in _create_local_cuda_repository
		_find_nvvm_libdevice_dir(repository_ctx, cuda_config)
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 724, in _find_nvvm_libdevice_dir
		auto_configure_fail(("Cannot find libdevice.10.bc un...))
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find libdevice.10.bc under /usr/local/cuda-8.0
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 1166
		_create_local_cuda_repository(repository_ctx)
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 1001, in _create_local_cuda_repository
		_find_nvvm_libdevice_dir(repository_ctx, cuda_config)
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 724, in _find_nvvm_libdevice_dir
		auto_configure_fail(("Cannot find libdevice.10.bc un...))
	File "/home/cxt/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find libdevice.10.bc under /usr/local/cuda-8.0
```
I tried the solution on this [link](https://github.com/tensorflow/tensorflow/issues/17801). But it didn't work. 
The following are the info about my PC.
### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
- **Python version**:3.6 
- **Bazel version**:0.15.0
- **GCC/Compiler version**:5.5.0
- **CUDA/cuDNN version**:8.0/5.1.10
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
I want to install TensorFlow on my system. But I tried plenty of ways, none of them works. It took me a lot of time. Can anybody help me out or provide me a useful way?
Thanks a lot!

**Comment by tensorflowbutler** [comment] 2018-07-08 00:43
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow version
GPU model and memory
Exact command to reproduce

**Comment by TonyTangYu** [comment] 2018-07-08 02:07
@tensorflowbutler Thank you for your response. I feel so sorry for my fault. I have update this issue as you command. Wish your response. Thank you.

**Comment by reedwm** [comment] 2018-07-09 17:44
This is a duplicate of #17801. Unfortunately, it seems TensorFlow does not currently work with Cuda 8.0, so I recommend upgrading to at least Cuda 9.0.

**Closed by reedwm** 2018-07-09 17:44 UTC
