### ISSUE TITLE
Input depth should be equal to filter depth, conv2d, Tensorflow, Convolution operation, CNN

### ISSUE THREAD

**Issue by manp-git** [tensorflow/tensorflow#48933] opened 2021-05-06 09:55 UTC
Tensorflow version 2.0

Python version 3.7

Following tensors extracted from TF Resnet50 model for experimentation on convolution.
in1.shape = (1,56,56,64)
weight_kernel.shape = (64,3,3,64)

Method1:-
image_conv = tensorflow.nn.conv2d(in1, weight_kernel, strides=(1,1), padding='SAME', dilations=None, data_format='NHWC')

Method2:-
image_conv = tensorflow.keras.backend.conv2d(in1, kernel=weight_kernel, strides=(1, 1), padding='same', dilation_rate=(1,1), data_format='channels_last')

Error:-
InvalidArgumentError: input depth must be evenly divisible by filter depth: 64 vs 3 [Op:Conv2D]

Tried changing the padding; data_format, strides also.

When the convolution has no issue happening in resnet model, why recreating outside is an issue with same tensor size; secondly  there is not depedency of filter depth as such in convolution, On what basis is 64 vs 3 coming up?
If i keep one tensor in channels first format and other one in channels last format, it starts giving error on 56 vs 3,  though I believe both should be in same format for the convolution operation.

**Comment by manp-git** [comment] 2021-05-07 04:23
Hi,
I figured out that following is the format to pass conv data:-

in1.shape = (1,56,56,64)
weight_kernel.shape = (64,3,3,64)

in1         ->     [1, height, width, channels]              -> (1,56,56,64)
weight_kernel           ->      [height, width, in_channels, out_channels]           -> (3,3,64,64)


Apply:-
image_conv = tensorflow.nn.conv2d(in1, weight_kernel, strides=(1,1), padding='SAME', dilations=None)


Now this gives me shape of output of conv, same as input shape         -> (1,56,56,64)

Is this correct?

Over this I have added the biases that were extracted from the resnet model , my_bias.shape (64,) - as shown in python

this is done by simply doing  image_conv + my_bias

the output dimension remains the same - (1,56,56,64)

**Comment by tilakrayal** [comment] 2021-05-07 04:32
@manp-git ,

Please refer these issues with similar error log.It helps.#28777,[link1](https://stackoverflow.com/questions/60174964/invalidargumenterror-input-depth-must-be-evenly-divisible-by-filter-depth-4-v/60212961#60212961),[link2](https://github.com/llSourcell/deep_dream_challenge/issues/5)

**Comment by tilakrayal** [comment] 2021-05-07 04:41
@manp-git ,

Looks like this is duplicate of issue #48879.Can you please confirm if we close this issue, since it is already being tracked there? Thanks!

**Comment by manp-git** [comment] 2021-05-07 04:46
https://github.com/tensorflow/tensorflow/issues/48933#issuecomment-834059960

Sure , @tilakrayal I have checked the similar error logs links that you have mentioned these did not help me resolve.

Hence I posted my resolve here to my own question to check if this is fine.

If it can be tracked in #48879 , I am happy with it.

**Comment by tilakrayal** [comment] 2021-05-10 14:29
@manp-git ,

Please feel free to close this issue as it is being tracked #48879.

Thanks!

**Closed** 2021-05-24 15:48 UTC
Labels: TF 2.0, comp:apis, comp:keras, stalled, stat:awaiting response, type:bug
