### ISSUE TITLE
Tensorflow failed to build due to error C2039 C3861 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [tensorflow/tensorflow#47501] opened 2021-03-02 10:47 UTC
Hi All,

Tensorflow failed to build due to error C2039 C3861 on windows with MSVC. It can be reproduced on latest master branch commit. Could you please help take a look at this issue? Thanks in advance!

Environment
Tensorflow(latest master branch revision from github) + VS 2019 + Windows Server 2016

Note: 
build.log in build.zip attachment.
[build.zip](https://github.com/tensorflow/tensorflow/files/6067995/build.zip)

tensorflow_set_bazel_version.patch in tensorflow_set_bazel_version.zip
[tensorflow_set_bazel_version.zip](https://github.com/tensorflow/tensorflow/files/6068012/tensorflow_set_bazel_version.zip)

Repro steps:
1. Open x64 native tools command prompt for VS2019
2. git clone https://github.com/tensorflow/tensorflow F:\gitP\tensorflow\tensorflow
3. git submodule init
4. git submodule update --recursive
5. Apply tensorflow_set_bazel_version.patch in attachment tensorflow_set_bazel_version.zip
6. cd F:\gitP\tensorflow\tensorflow
7. pip3 install six numpy wheel
8. pip3 install keras_applications==1.0.6 --no-deps
9. pip3 install keras_preprocessing==1.0.5 --no-deps
10. set PATH=F:\gitP\tensorflow\tensorflow\..\tools;%path%
11. set PATH=F:\gitP\tensorflow\tensorflow\..\tools\msys64\usr\bin;%path%
12. yes "" 2>nul | python ./configure.py
13. set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
14. set BAZEL_VC_FULL_VERSION=14.28.29333
15. bazel --output_user_root F:\bazelTemp build --config=opt --subcommands //tensorflow/tools/pip_package:build_pip_package

Actual result:
SUBCOMMAND: # //tensorflow/core/platform:error [action 'Compiling tensorflow/core/platform/error.cc', configuration: b0b8ead46223da3f6648bba4bb6404871eb4a1826bc4e150e3d35eeda28b2f74]
SUBCOMMAND: # //tensorflow/core/platform:error [action 'Linking tensorflow/core/platform/error.lib', configuration: b0b8ead46223da3f6648bba4bb6404871eb4a1826bc4e150e3d35eeda28b2f74]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\complex(674): error C2039: 'copysign': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\complex(674): error C3861: 'copysign': identifier not found
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 9803.671s, Critical Path: 681.63s
INFO: 9288 processes: 9288 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
##[debug] Command #6 exited with code [1].
##[error] Detected error code [1].

**Comment by amahendrakar** [comment] 2021-03-02 11:38
@spacelg,
Looks like this is a duplicate of issue [#46902](https://github.com/tensorflow/tensorflow/issues/46902), which has already been addressed by a member of the TensorFlow team.

Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/46902#issuecomment-780667266) for more information. Thanks!

**Closed** 2021-03-16 12:55 UTC
Labels: TF 2.5, stalled, stat:awaiting response, subtype:windows, type:build/install
