### ISSUE TITLE
pasta.base.annotate.AnnotationError: Indent detection failed (line 300)

### ISSUE THREAD

**Issue by GuesmiAbd** [tensorflow/tensorflow#30432] opened 2019-07-05 10:59 UTC
Hello,
I use google colab and I have this error:
Traceback (most recent call last):
  File "/usr/local/bin/tf_upgrade_v2", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/tf_upgrade_v2_main.py", line 139, in main
    args.input_file, output_file, upgrade)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/tf_upgrade_v2_main.py", line 40, in process_file
    upgrader.process_file(in_filename, out_filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/ast_edits.py", line 900, in process_file
    temp_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/ast_edits.py", line 960, in process_opened_file
    self.update_string_pasta("".join(lines), in_filename))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/ast_edits.py", line 916, in update_string_pasta
    t = pasta.parse(text)
  File "/usr/local/lib/python3.6/dist-packages/pasta/__init__.py", line 25, in parse
    annotator.visit(t)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 47, in wrapped
    f(self, node, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 220, in visit_Module
    self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
    f(self, node, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 411, in visit_FunctionDef
    self.visit(stmt)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
    f(self, node, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 291, in visit_For
    self.visit(stmt)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
    f(self, node, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 290, in visit_For
    for stmt in self.indented(node, 'body'):
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1224, in indented
    'more than the outer indentation.' % cur_loc[0])
pasta.base.annotate.AnnotationError: Indent detection failed (line 300); inner indentation level is not more than the outer indentation.

thanks for help me

**Comment by lc0** [comment] 2019-07-05 17:43
@GuesmiAbd do you have an example of what you are trying to convert?

it looks like you have a code, that has one line that is an extra indentation - whitespace

**Comment by lc0** [comment] 2019-07-05 18:02
@GuesmiAbd It looks like you have less indentation. Would you mind to copy here lines `299-301`?

**Comment by GuesmiAbd** [comment] 2019-07-06 20:06
@lc0  You can see my code lines 297-301
        for l in range(NUM_CLASSES):
            total_seen_class[l] += np.sum((batch_label==l) & (batch_smpw>0))
            total_correct_class[l] += np.sum((pred_val==l) & (batch_label==l) & (batch_smpw>0))
        for b in range(batch_label.shape[0]):
	         _, uvlabel, _ = pc_util.point_cloud_label_to_surface_voxel_label_fast(aug_data[b,batch_smpw[b,:]>0,:], np.concatenate((np.expand_dims(batch_label[b,batch_smpw[b,:]>0],1),np.expand_dims(pred_val[b,batch_smpw[b,:]>0],1)),axis=1), res=0.02)

**Comment by ravikyram** [comment] 2019-07-08 13:17
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by GuesmiAbd** [comment] 2019-07-08 14:36
Hello @ravikyram ,
I'm trying to upgrade my code to TF2.0.First I install TF2.0alpha0-gpu  on google colab (python 3.6)then I typed the command  !tf_upgrade_v2 --infile train.py --outfile train_upgraded.py  to generate the upgraded version.
The link of the code:https://github.com/charlesq34/pointnet2/blob/master/scannet/train.py

I got the following error:
process_opened_file
self.update_string_pasta("".join(lines), in_filename))
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/tools/compatibility/ast_edits.py", line 916, in update_string_pasta
t = pasta.parse(text)
File "/usr/local/lib/python3.6/dist-packages/pasta/init.py", line 25, in parse
annotator.visit(t)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
super(AstAnnotator, self).visit(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
super(BaseVisitor, self).visit(node)
File "/usr/lib/python3.6/ast.py", line 253, in visit
return visitor(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 47, in wrapped
f(self, node, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 220, in visit_Module
self.generic_visit(node)
File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
self.visit(item)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
super(AstAnnotator, self).visit(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
super(BaseVisitor, self).visit(node)
File "/usr/lib/python3.6/ast.py", line 253, in visit
return visitor(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
f(self, node, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 411, in visit_FunctionDef
self.visit(stmt)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
super(AstAnnotator, self).visit(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
super(BaseVisitor, self).visit(node)
File "/usr/lib/python3.6/ast.py", line 253, in visit
return visitor(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
f(self, node, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 291, in visit_For
self.visit(stmt)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1194, in visit
super(AstAnnotator, self).visit(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 132, in visit
super(BaseVisitor, self).visit(node)
File "/usr/lib/python3.6/ast.py", line 253, in visit
return visitor(node)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 95, in wrapped
f(self, node, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 290, in visit_For
for stmt in self.indented(node, 'body'):
File "/usr/local/lib/python3.6/dist-packages/pasta/base/annotate.py", line 1224, in indented
'more than the outer indentation.' % cur_loc[0])
pasta.base.annotate.AnnotationError: Indent detection failed (line 300); inner indentation level is not more than the outer indentation.

Thanks,

**Comment by ravikyram** [comment] 2019-07-09 08:08
@GuesmiAbd This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2019-07-12 04:56
@GuesmiAbd Were you able to resolve the issue?.Thanks!

**Comment by lc0** [comment] 2019-07-14 20:13
@GuesmiAbd Please double check indentation, used in code. Seems like authors combine tabs with whitespaces, that causing the issue.

@soupytwist what do you think?

**Comment by soupytwist** [comment] 2019-07-15 17:34
Yes, it's a bug in pasta due to mixed tabs + spaces. Opened: https://github.com/google/pasta/issues/70

**Comment by ravikyram** [comment] 2019-07-16 06:02
@GuesmiAbd 
Can we close this issue and track the issue in pasta repository: google/pasta#70.Thanks!

**Comment by ravikyram** [comment] 2019-07-23 05:52
We are closing this issue and we can track the issue in  google/pasta#70.Thanks!

**Closed by ravikyram** 2019-07-23 05:52 UTC
Labels: comp:apis, stat:awaiting response, type:bug

**Comment by GuesmiAbd** [comment] 2019-07-23 12:23
Thank you for all!
the problem was solved.
