### ISSUE TITLE
NaN problem on tutorials_example_trainer with tensorflow 0.8

### ISSUE THREAD

**Issue by ernest-tg** [tensorflow/tensorflow#2037] opened 2016-04-20 16:09 UTC
I worked for several months on versions of tensorflow installed from sources. Today, I tried to upgrade it to 0.8. The installation seemed to go fine.  "bazel-bin/tensorflow/cc/tutorials_example_trainer" gave the expected result. However, the output of "bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu" is unexpected: the first lines seem to be fine but then NaN values appear, the proportion of NaN values increases until there is nothing but NaN values (see the first half of the output here http://pastebin.com/EhuD2Z5S , the remaining lines are only "nan" lines which I omitted because the total output exceeded pastebin limit).

I expected this tutorials_example_trainer to either work seamlessly or not at all (if I provided wrong paths for CUDA and CuDNN), but this in-between puzzles me.

I tried to debug it with my own programs, but I can not import tensorflow :
```
import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
```
I am not sure whether the two problems are related.

In the case I made a mistake during configuration, I typed:
```
matthieu@gpu2:~/external/tensorflow$ ./configure 
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc nvcc should use as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.0
Please specify the location where CUDA 7.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 4
Please specify the location where cuDNN 4 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Setting up Cuda include
Setting up Cuda lib64
Setting up Cuda bin
Setting up Cuda nvvm
Setting up CUPTI include
Setting up CUPTI lib64
Configuration finished"
```

I hope this issue belongs here, else I will try stackoverflow.

Thanks in advance,

### Environment info
I work on ubuntu 14.04

With CUDA 7.0 and cuDNN 4
```
ls /usr/local/cuda-7.0/lib/libcud*        
/usr/local/cuda-7.0/lib/libcudadevrt.a  /usr/local/cuda-7.0/lib/libcudart.so.7.0     /usr/local/cuda-7.0/lib/libcudart_static.a
/usr/local/cuda-7.0/lib/libcudart.so    /usr/local/cuda-7.0/lib/libcudart.so.7.0.28
```

Commit hash: e1c017624fd6bd8562c1da27e0014b32f389b524

**Comment by prb12** [comment] 2016-04-20 19:02
I don't believe that this is the expected behavior, but I have been unable to reproduce this on my installation (admittedly using a single K40 GPU).   Since the example should only be using one of the GPUs I can't think why this might be happening.

Could you please provide me some more information about how you installed TensorFlow?

**Comment by prb12** [comment] 2016-04-20 20:02
PS.  Your error when trying to import tensorflow looks like the error message I once got when I tried to run an interactive python session in the root of a tensorflow source tree.  Is this possibly what's happening?

**Comment by ernest-tg** [comment] 2016-04-21 09:32
Thanks for the answers:
## Concerning my installation
I typed the following
```
$ git pull origin
$ ./configure  # with the parameters I detailed above
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
```
At this point, I tried $ bazel-bin/tensorflow/cc/tutorials_example_trainer, and I encountered the NaN problem. So I went back to the "Download and Setup" page to determine if I had missed a step

```
$ git submodule update --recursive
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer # changed nothing
```

I downloaded and installed the last version of bazel
```
$ wget https://github.com/bazelbuild/bazel/releases/download/0.2.1/bazel-0.2.1-installer-linux-x86_64.sh
$ chmod +x bazel-0.2.1-installer-linux-x86_64.sh
$ ./bazel-0.2.1-installer-linux-x86_64.sh  --user
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer # changed nothing
```
I upgraded all my packages -> changed nothing.
Then I tried to google my problem, but nobody seems to have the same issue.

## Concerning the interactive python session
This was indeed the issue, but when I run the python session from another directory, I have another import issue.

```
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.0 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matthieu/external/tensorflow/_python_build/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/matthieu/external/tensorflow/_python_build/tensorflow/python/__init__.py", line 59, in <module>
    from tensorflow.core.protobuf.config_pb2 import *
ImportError: No module named config_pb2
```

Indeed, The config_pb2 file is not in the directory. I will investigate this further.

**Comment by ngovanmao** [comment] 2016-04-27 04:59
@ernest-tg How did you solve this problem? 
I face the same issue as describe here. Please give your solution if possible. Thank you.

**Comment by ernest-tg** [comment] 2016-04-27 11:58
I did not solve the problem. I ended up reinstalling the 0.7.0 version. This week-end, I plan to find by dichotomy, the first commit which gives me this behaviour. Hopefully, it will help the tensorflow team to understand/solve this problem.

**Comment by weiliu620** [comment] 2016-05-13 19:03
Found the issue when I searched the same problem. I git pulled the latest source and got this same issue: tutorials_example_trainer output some NaNs. Here are the last few lines of the output. 

======== log ===========
000004/000005 lambda =      nan x = [     nan      nan] y = [     nan      nan]
000009/000005 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000004/000003 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000001/000007 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
000006/000009 lambda =      nan x = [     nan      nan] y = [     nan      nan]
============================
I'm on Ubuntu 14.04 LTS 64 bit, gcc 4.8.4, CUDA 7.5.

**Comment by girving** [comment] 2016-06-07 05:03
@ernest-tg: Does this problem persist, or did you manage to get any further information?

**Comment by prb12** [comment] 2016-06-07 21:03
So far, I have been unable to reproduce the NaN behavior building source from the current head, or using the binary distros.

**Comment by ethereon** [comment] 2016-06-08 21:00
I can reproduce this on the current head (592675b2b8d1cabbf923638942ea6f200abe353a)

Environment: Ubuntu 14.04.4, CUDA 7.0, cuDNN 4.0

**Comment by prb12** [comment] 2016-06-09 18:13
I have the exact same software versions here, but don't get the NaNs.  Perhaps this is a hardware related issue, e.g. placement of ops on multiple GPUs?   
@zheng-xq Are there any known multi-gpu issues with TF0.9/Cuda7.0/cuDNN4  ?

@weiliu620, @ethereon   Are you also running a multi-gpu config?  

@ernest-tg  Could you please try running this with the environment variable CUDA_VISIBLE_DEVICES=0 

Does the same problem happen with newer CUDA SDKs and cuDNN?

Might also be warth checking where ops are running as follows:

```
diff --git a/tensorflow/cc/tutorials/example_trainer.cc b/tensorflow/cc/tutorials/example_trainer.cc
index a465d98..02b42ab 100644
--- a/tensorflow/cc/tutorials/example_trainer.cc
+++ b/tensorflow/cc/tutorials/example_trainer.cc
@@ -93,6 +93,7 @@ string DebugString(const Tensor& x, const Tensor& y) {
 void ConcurrentSteps(const Options* opts, int session_index) {
   // Creates a session.
   SessionOptions options;
+  options.config.set_log_device_placement(true);
   std::unique_ptr<Session> session(NewSession(options));
   GraphDef def = CreateGraphDef();
   if (options.target.empty()) {
```

**Comment by ethereon** [comment] 2016-06-13 18:32
@prb12 I'm running a single GPU config (Titan X). This appears to be a bit of a heisenbug: it occurred on every single run last week, but everything seems fine today. The build hasn't changed - everything's untouched.

**Comment by zheng-xq** [comment] 2016-06-13 19:29
>> Are there any known multi-gpu issues with TF0.9/Cuda7.0/cuDNN4 ?

Not to my knowledge yet.

**Comment by aselle** [comment] 2016-07-19 17:57
Closing this bug, as we cannot reproduce it.

**Closed by aselle** 2016-07-19 17:57 UTC
Labels: awaiting response

**Comment by tuba** [comment] 2016-08-21 21:04
I can reproduce it always on GPU, on CPU all works fine. If you need the code or ssh to check it - notify me.

**Comment by tuba** [comment] 2016-08-21 21:07
Ubuntu 16.04, nVidia driver 367.35, GTX 1080

**Comment by yaroslavvb** [comment] 2016-08-21 21:16
GTX 1080 doesn't work correctly with CUDA 7.5
You need CUDA 8.0, but there's no stable release of CUDA 8.0 yet
However, I tried the release candidate and it worked for me

**Comment by andycui97** [comment] 2016-08-23 19:51
Same issue, Ubuntu 16.04, nVidia driver 367.35, GTX 1070, CUDA 8

**Comment by Mazecreator** [comment] 2016-08-23 21:27
Make sure you have cuDNN 5.0 for the GTX10x0 NVIDIA cards.

**Comment by andycui97** [comment] 2016-08-29 04:11
Yup I made sure, still didn't work.

**Comment by Mistobaan** [comment] 2016-08-29 04:55
did you tried the latest version of tensorflow ? 0.10 ? does the problem still persist?

**Comment by andycui97** [comment] 2016-08-29 05:16
I'm building it from source, so I should be on the latest version right?

**Comment by fbolanos** [comment] 2016-08-30 21:44
Can also reproduce, Ubuntu 16.04, nVidia driver 367.35, GTX 1080, CUDA 8.0, cuDNN 5.1, compiled tensorflow from source. 

Output comes out as expected from CPU, but when GPU is enabled, nans are made on some of the output lines. Also, lines that have nans change each time you run the test program. Also sometimes when you run the test program it crashes by saying  Floating point exception. 

cuda-gdb gave if I got the floating point exception: 
`0x0000555556057e80 in tensorflow::functor::CastFunctor<Eigen::GpuDevice, float, int>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<int const, 1, 1, long>, 16>) ()
`

Even stranger is that when the program ran successfully using cuda-gdb, the output would be completely normal. Except whenever I got the above floating point exception. This is so bizarre...

**Comment by cr145** [comment] 2016-08-31 17:18
I have the same problem as @fbolanos. I have not been able to resolve the issue, but I thought I'd mention that someone uploaded their pip wheel in another thread (https://github.com/tensorflow/tensorflow/issues/4030). I downloaded and installed it and it seem to be working fine on my system (Ubuntu 16.04, GTX 1080, CUDA 8.0 RC + Patch, cuDNN 5.1).

**Comment by zheng-xq** [comment] 2016-08-31 22:53
@fbolanos, @cr145, I put on a GTX 1080 on my local machine, but couldn't reproduce the problem. 

My exact steps:
* git clone http://github.com/tensorflow/tensorflow --recursive
  ** f974e8d0c2420c6f7e2a2791febb4781a266823f for my experiment. 
* cd tensorflow
* printf "\n\n\ny\n\n8.0\n/usr/local/cuda-8.0\n5.0.5\n/usr/local/cudnn-5.0\n\n" | ./configure
* bazel build -c opt --config=cuda tensorflow/cc/tutorials_example_trainer
* LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:/usr/local/cudnn-5.0/lib64 \
  bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

Output: 
>> ...
>> 000001/000009 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]
>> 000001/000009 lambda = 2.000000 x = [0.894427 -0.447214] y = [1.788854 -0.894427]

Setup: 
* GTX 1080, Ubuntu 14.04, Cuda 8.0, Cudnn 5.0.5, bazel 0.3.0, Cuda driver 367.35

Please let me know if you still have problem if you match my steps as close as possible. If so, something very fishy is going on.

**Comment by zhudanhao** [comment] 2016-09-01 05:00
i met the same problem when i set up it in a titianx. but after a few days，the example run well automatically. however，the machine is about 5x slower when running lstm. I don't know whether these are related.

发自我的 iPhone

**Comment by fbolanos** [comment] 2016-09-02 05:05
Ok! So it appears that after rebooting the machine the output is correct. However, the floating point exception I showed above occurs randomly when running the test program several times. However, no more Nans! :)

**Comment by vrv** [comment] 2016-09-02 05:06
I think we need to get rid of the multi-threading of this example -- it's actually not safe to do in its current implementation.

**Comment by zheng-xq** [comment] 2016-09-02 19:58
@fbolanos, Vijay was correct. The example uses DirectSession that didn't share the underlying GPUDevice. They are not good for parallel execution. Other types of sessions do not have this problem. There are other effort trying to unite the session implementations that will address this problem at the same time. 

Please try "--num_concurrent_sessions=1" and "--num_concurrent_steps=1" for your experiments. If you don't see any exceptions with those, then everything is good.

**Comment by cianeastwood** [comment] 2017-06-05 22:45
Was this solved? I'm having the same problem. Code here: https://github.com/openai/InfoGAN ran fine on CPU. On GPU, it ran successfully for a small number of epochs before loss returned NaN. All (fresh) runs now return NaN as loss. Ubuntu 14, TensforFlow 0.9.0rc0, CUDA 7.0, cuDNN 4.0, 3x geforce titan X.

**Comment by cr145** [comment] 2017-06-06 02:44
It's fixed in newer versions of TF
