### ISSUE TITLE
TF 2.3 broken hierarchical functional model loading (e.g. HAN) [ValueError: Unknown layer: Functional]

### ISSUE THREAD

**Issue by Jordy-VL** [tensorflow/tensorflow#41929] opened 2020-07-31 09:04 UTC
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): v2.3
Python version: 3.6.9
CUDA/cuDNN version: v10.2
GPU model and memory: GeForce GTX 1070 - 8117MiB

Describe the current behavior:
I cannot load a model trained with TF 2.3 in TF 2.2 -> **breaking change**
In TF 2.3 the release notes mention the following: 
`Functional models now get constructed if any tensor in a layer call's arguments/keyword arguments comes from a keras input. Previously the functional api would only work if all of the elements in the first argument to the layer came from a keras input.`

I have a hierarchical attention model, trained either with TF2.2 with the following underlying config: 
```
{'name': 'HAN_DocSent', 'layers': [{'class_name': 'InputLayer', 'config': {'batch_input_shape': (None, 150, None), 'dtype': 'int32', 'sparse': False, 'ragged': False, 'name': 'input_1'}, 'name': 'input_1', 'inbound_nodes': []}, {'class_name': 'TimeDistributed', 'config': {'name': 'time_distributed', 'trainable': True, 'dtype': 'float32', 'layer': {'class_name': 'Model', 'config': {'name': 'HAN_SentWord', 'layers': [{'class_name': 'InputLayer', 'config': {'batch_input_shape': (None, None), 'dtype': 'int32', 'sparse': False, 'ragged': False, 'name': 'word/sentence_input'}, 'name': 'word/sentence_input', 'inbound_nodes': []}, {'class_name': 'Embedding', 'config': {'name': 'word_embedding', 'trainable': True, 'batch_input_shape': (None, None), 'dtype': 'float32', 'input_dim': 20002, 'output_dim': 300, 'embeddings_initializer': {'class_name': 'RandomUniform', 'config': {'minval': -0.05, 'maxval': 0.05, 'seed': None}}, 'embeddings_regularizer': None, 'activity_regularizer': None, 'embeddings_constraint': None, 'mask_zero': True, 'input_length': None}, 'name': 'word_embedding', 'inbound_nodes': [[['word/sentence_input', 0, 0, {}]]]}, {'class_name': 'Bidirectional', 'config': {'name': 'bidirectional', 'trainable': True, 'dtype': 'float32', 'layer': {'class_name': 'GRU', 'config': {'name': 'gru', 'trainable': True, 'dtype': 'float32', 'return_sequences': True, 'return_state': False, 'go_backwards': False, 'stateful': False, 'unroll': False, 'time_major': False, 'units': 100, 'activation': 'tanh', 'recurrent_activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'recurrent_initializer': {'class_name': 'Orthogonal', 'config': {'gain': 1.0, 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'recurrent_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'recurrent_constraint': None, 'bias_constraint': None, 'dropout': 0.25, 'recurrent_dropout': 0.25, 'implementation': 1, 'reset_after': True}}, 'merge_mode': 'concat'}, 'name': 'bidirectional', 'inbound_nodes': [[['word_embedding', 0, 0, {}]]]}, {'class_name': 'HierarchicalAttention', 'config': {'name': 'word_attention', 'trainable': True, 'dtype': 'float32'}, 'name': 'word_attention', 'inbound_nodes': [[['bidirectional', 0, 0, {}]]]}], 'input_layers': [['word/sentence_input', 0, 0]], 'output_layers': [['word_attention', 0, 0]]}}}, 'name': 'time_distributed', 'inbound_nodes': [[['input_1', 0, 0, {}]]]}, {'class_name': 'Bidirectional', 'config': {'name': 'bidirectional_1', 'trainable': True, 'dtype': 'float32', 'layer': {'class_name': 'GRU', 'config': {'name': 'gru_1', 'trainable': True, 'dtype': 'float32', 'return_sequences': True, 'return_state': False, 'go_backwards': False, 'stateful': False, 'unroll': False, 'time_major': False, 'units': 100, 'activation': 'tanh', 'recurrent_activation': 'sigmoid', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'recurrent_initializer': {'class_name': 'Orthogonal', 'config': {'gain': 1.0, 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'recurrent_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'recurrent_constraint': None, 'bias_constraint': None, 'dropout': 0.25, 'recurrent_dropout': 0.25, 'implementation': 1, 'reset_after': True}}, 'merge_mode': 'concat'}, 'name': 'bidirectional_1', 'inbound_nodes': [[['time_distributed', 0, 0, {}]]]}, {'class_name': 'HierarchicalAttention', 'config': {'name': 'sentence_attention', 'trainable': True, 'dtype': 'float32'}, 'name': 'sentence_attention', 'inbound_nodes': [[['bidirectional_1', 0, 0, {}]]]}, {'class_name': 'Dense', 'config': {'name': 'dense_2', 'trainable': True, 'dtype': 'float32', 'units': 31, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}, 'name': 'dense_2', 'inbound_nodes': [[['sentence_attention', 0, 0, {}]]]}], 'input_layers': [['input_1', 0, 0]], 'output_layers': [['dense_2', 0, 0]]}
```
Yet in TF 2.3 the saved config is differently wrapped with "Functional": 
```
{"class_name": "Functional", "config": {"name": "HAN_DocSent", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 30, null], "dtype": "int32", "sparse": false, "ragged": false, "name": "input_1"}, "name": "input_1", "inbound_nodes": []}, {"class_name": "TimeDistributed", "config": {"name": "time_distributed", "trainable": true, "dtype": "float32", "layer": {"class_name": "Functional", "config": {"name": "HAN_SentWord", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, null], "dtype": "int32", "sparse": false, "ragged": false, "name": "word/sentence_input"}, "name": "word/sentence_input", "inbound_nodes": []}, {"class_name": "Embedding", "config": {"name": "word_embedding", "trainable": true, "batch_input_shape": [null, null], "dtype": "float32", "input_dim": 20000, "output_dim": 50, "embeddings_initializer": {"class_name": "RandomUniform", "config": {"minval": -0.05, "maxval": 0.05, "seed": null}}, "embeddings_regularizer": null, "activity_regularizer": null, "embeddings_constraint": null, "mask_zero": true, "input_length": null}, "name": "word_embedding", "inbound_nodes": [[["word/sentence_input", 0, 0, {}]]]}, {"class_name": "Bidirectional", "config": {"name": "bidirectional", "trainable": true, "dtype": "float32", "layer": {"class_name": "GRU", "config": {"name": "gru", "trainable": true, "dtype": "float32", "return_sequences": true, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "time_major": false, "units": 100, "activation": "tanh", "recurrent_activation": "sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "recurrent_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "recurrent_constraint": null, "bias_constraint": null, "dropout": 0.5, "recurrent_dropout": 0.25, "implementation": 1, "reset_after": true}}, "merge_mode": "concat"}, "name": "bidirectional", "inbound_nodes": [[["word_embedding", 0, 0, {}]]]}, {"class_name": "HierarchicalAttention", "config": {"name": "word_attention", "trainable": true, "dtype": "float32"}, "name": "word_attention", "inbound_nodes": [[["bidirectional", 0, 0, {}]]]}], "input_layers": [["word/sentence_input", 0, 0]], "output_layers": [["word_attention", 0, 0]]}}}, "name": "time_distributed", "inbound_nodes": [[["input_1", 0, 0, {}]]]}, {"class_name": "Bidirectional", "config": {"name": "bidirectional_1", "trainable": true, "dtype": "float32", "layer": {"class_name": "GRU", "config": {"name": "gru_1", "trainable": true, "dtype": "float32", "return_sequences": true, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "time_major": false, "units": 100, "activation": "tanh", "recurrent_activation": "sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "recurrent_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "recurrent_constraint": null, "bias_constraint": null, "dropout": 0.5, "recurrent_dropout": 0.25, "implementation": 1, "reset_after": true}}, "merge_mode": "concat"}, "name": "bidirectional_1", "inbound_nodes": [[["time_distributed", 0, 0, {}]]]}, {"class_name": "HierarchicalAttention", "config": {"name": "sentence_attention", "trainable": true, "dtype": "float32"}, "name": "sentence_attention", "inbound_nodes": [[["bidirectional_1", 0, 0, {}]]]}, {"class_name": "Dense", "config": {"name": "dense_2", "trainable": true, "dtype": "float32", "units": 5, "activation": "softmax", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "name": "dense_2", "inbound_nodes": [[["sentence_attention", 0, 0, {}]]]}], "input_layers": [["input_1", 0, 0]], "output_layers": [["dense_2", 0, 0]]}}'
```
The error, of course, relates to the internal model which now compiles to a "Functional" model: 
`ValueError: Unknown layer: Functional`
The errors occurs in this line: 
```/media/hdd/.virtualenvs/arkham/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py(177)load_model_from_hdf5()
-> model = model_config_lib.model_from_config(model_config, ...)
```

Describe the expected behavior:
Model loading stays stable between releases...

Standalone code to reproduce the issue
I cannot share the code due to proprietary rights... yet since it is reported in the release, it should be straightforward to find a solution.
E.g. should I change the way I load my model?

**Comment by amahendrakar** [comment] 2020-07-31 11:58
@Jordy-VL,
>I cannot share the code due to proprietary rights... yet since it is reported in the release, it should be straightforward to find a solution.

Could you please provide a dummy model or a minimal working example to reproduce the issue reported here? Thanks!

**Comment by lithuak** [comment] 2020-08-07 12:25
@amahendrakar The similar errors has been recenlty reported in TF mailing list as well as at SO: https://stackoverflow.com/questions/63068639/valueerror-unknown-layer-functional

**Comment by Jordy-VL** [comment] 2020-08-07 16:06
Exacty as @lithuak mentions. However, the solution proposed to recompile and only load the weights does not solve the issue...

**Comment by jvishnuvardhan** [comment] 2020-08-10 18:44
@Jordy-VL Thanks for reporting this issue. Can you please provide a standalone code to reproduce the issue? Thanks!

**Comment by Jordy-VL** [comment] 2020-08-11 08:09
> @Jordy-VL Thanks for reporting this issue. Can you please provide a standalone code to reproduce the issue? Thanks!

I'll start on a dummy model first thing tomorrow. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-08-25 23:39
@Jordy-VL I am not sure how much we can resolve without looking at the model creation code as the current error is "Unknown layer". But, let's try it. Thanks!

**Comment by Jordy-VL** [comment] 2020-08-26 13:07
Sorry for the delay @jvishnuvardhan 

For best resolution, I created a colab gist with the model creation code; instructions are contained inside. 
https://colab.research.google.com/drive/1fL9q5-ThAbYXJ_EgALhAHQ3x2OXb99jd?usp=sharing 

Thanks for nudging me to complete this model gist ;) I was a bit too swamped the last days.

**Comment by jvishnuvardhan** [comment] 2020-08-27 03:45
@Jordy-VL Why do you `backend.symbolic_learning_phase()`? When we define a keras function, we need to provide input and output of the model but you are providing `learning_phase` also.

when I removed `learning_phase` from the keras function, it didn't throw any error. Thanks!

`model_mc = tf.keras.backend.function([new_model.input], [out_layer])`

**Comment by Jordy-VL** [comment] 2020-08-27 06:12
I need it to use MonteCarlo Dropout, where you activate learning rate to simulate dropout at inference time. If you know of an alternative, do tell :)

**Comment by parasjain06** [comment] 2020-09-09 08:40
Hi , i am getting similar issue while training a model. 
![image](https://user-images.githubusercontent.com/63651642/92575159-a16ca900-f2a5-11ea-97ea-f24d2752c1c7.png)

project link:- https://github.com/kairess/eye_blink_detector

first run preprocess.ipynb and the train.ipynb, after this model is trained and stored .
Now when i try to load model as below, gives above error
![image](https://user-images.githubusercontent.com/63651642/92575596-248dff00-f2a6-11ea-9e25-e045a34b64df.png)

**Comment by parasjain06** [comment] 2020-09-09 10:37
Issue resolved , actually problem was that while training i was using tensorflow 2.3.0, while running i was using tensorflow 2.2.0.
Hence this issue occured.
Later i tried compiling and running with tensorflow 2.2.0 only and it got through.

**Comment by Cospel** [comment] 2020-12-24 20:37
Still happening during loading (tf 2.2) h5 model trained in colab (tf 2.4)

Shouldn't this be fixed in a way that even older versions of tf2+ (2.0, 2.1, 2.2) are compatible with tf 2.3, tf 2.4 +?

**Comment by yichenj** [comment] 2021-03-14 07:24
I do not think make the training TF version same with the  prediction TF version is a good idea. I met this issue because i have deployed the prediction model to our customer site with TF version 2.2, but out training system recently upgrade TF version to 2.4. Therefore, our new trained model cannot use on our clients' site. Upgrade TF version of all our clients is infeasible, nor keep our GPU training system to TF 2.2 is a good idea i suppose. 

Could we add an args to model.save() to export model in old format?

**Comment by sushreebarsa** [comment] 2021-05-30 11:19
Was able to replicate the issue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a24796e1da830332ed3df755c7236e51/untitled107.ipynb)..Thanks !

**Comment by gowthamkpr** [comment] 2022-08-26 23:09
We are sorry. But the solution to this error is very simple, ex. the reason is that you have trained the model on version '2.3.0' of Tensorflow & '2.4.3' of Keras (On Colab or local). and now you are accessing the saved model(.h5) via another version of Keras & TensorFlow. It will give you the error. The solution is that re-trained model with upgraded versions or downgrades your TF&Keras to the same version as on which model is trained.

You can also look at the solution [here](https://stackoverflow.com/questions/63068639/valueerror-unknown-layer-functional)

**Closed** 2022-09-09 23:50 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:keras, TF 2.3
