### ISSUE TITLE
Could not satisfy explicit device specification '' because the node placed on device Device assignments active during op was colocated with a group of nodes that required incompatible device

### ISSUE THREAD

**Issue by DontGiveUpEasily** [tensorflow/tensorflow#33447] opened 2019-10-17 02:45 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I didn't write custom code
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==1.14.0
- Python version: 3.6.9
- CUDA/cuDNN version: 8.0, cuDNN 6.0
- GPU model and memory: 2 x 1080 TI
**Describe the current behavior**
I try to train a simple convolutional neural network defined by tf.keras.layers.Conv2D with random normal initialization, the network should be trained on GPU:

I use the following code to initialize the code:

config = tf.compat.v1.ConfigProto()
config.log_device_placement=False
sess = tf.compat.v1.InteractiveSession(config=config)
with tf.device('/gpu:0'):
     setup the network and train
**Describe the expected behavior**
It should train without bugs

I tried to use config.allow_soft_placement=True and it didn't throw out the bug anymore but the network can only be trained on cpu instead of GPU. Please help to figure out this issue as I've seen multiple issue reported in many places but the problem is never solved with a clean solution.

**Other info / logs**
Could not satisfy explicit device specification '' because the node placed on device Device assignments active during op was colocated with a group of nodes that required incompatible device

**Comment by gadagashwini** [comment] 2019-10-18 05:42
@DontGiveUpEasily, Please provide the complete code with neural network to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2019-10-30 08:34
@DontGiveUpEasily, Any update on standalone code!.

**Comment by gadagashwini** [comment] 2019-11-07 11:38
@DontGiveUpEasily, Please refer this [link](https://www.tensorflow.org/guide/gpu#manual_device_placement) for manual device placement. The doc describes, TensorFlow runtime will choose one based on the operation and available devices and automatically copy tensors between devices if required. Thanks!

**Comment by gadagashwini** [comment] 2019-11-07 11:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-11-07 11:38 UTC
Labels: TF 1.14, comp:gpu, stat:awaiting response, type:support

**Comment by davystrong** [comment] 2022-03-10 18:19
To anyone with the same issue, creating the generator in a device context fixes the problem:
```
with tf.device('/CPU:0'):
    _rng = tf.random.Generator.from_seed(123, alg='philox')
```

**Comment by tariffon** [comment] 2024-04-29 17:13
Maybe some config or param not have the compatibility  with the GPU.
