### ISSUE TITLE
`tf.nn.embedding_lookup`: unexpected behaviour with sharded `params` in "div" mode

### ISSUE THREAD

**Issue by syltruong** [tensorflow/tensorflow#19265] opened 2018-05-14 11:18 UTC
The following code shows what appears to be a [misbehaviour](https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup) when trying to lookup sharded embeddings in "div" mode:

```python
def test_shard_embedding_lookup(index):
   embeddings_1 = tf.constant([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
   embeddings_2 = tf.constant([[4,4,4],[5,5,5]])
   indices = tf.constant([index])
    
   with tf.Session() as sess:
      ret = sess.run(\
                  tf.nn.embedding_lookup(\
                     [embeddings_1, embeddings_2],\
                     indices,\
                     partition_strategy='div'\
                  )\
                )

   return ret

test_shard_embedding_lookup(2) # [2,2,2]
test_shard_embedding_lookup(3) # [4,4,4] instead of [3,3,3]
```

Tested with

- Python 3.6.5
- TF 1.8

**Comment by tensorflowbutler** [comment] 2018-05-14 18:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by syltruong** [comment] 2018-05-15 01:19
- Have I written custom code: No
- OS Platform and Distribution: macOS 10.13.4
- TensorFlow installed from: `pipenv install tensorflow`
- TensorFlow version: 1.8
- Python version: 3.6.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Exact command to reproduce: see previous comment

**Comment by robieta** [comment] 2018-05-15 23:25
Thank you for providing such a clear minimal case. I am able to replicate this behavior, and it appears to go back to at least version 1.0.0. I'll update when I know more.

**Comment by syltruong** [comment] 2018-05-24 10:48
@ccolby I cannot find the documentation you are referring to. Could you please attach here? Also, is there any reason for `tf.nn.embedding_lookup` not to be usable to un-balanced sharded tensors?

**Comment by ccolby** [comment] 2018-05-24 13:05
@syltruong I'm referring to the [`tf.nn.embedding_lookup` documentation](https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup). That documentation describes how the two supported partitioning strategies work—`"div"` and `"mod"`. It also clarifies that for the `params` argument:

> Each element must be appropriately sized for the given `partition_strategy`

As for why `tf.nn.embedding_lookup` doesn't support arbitrary partitioning, it is most likely because the `"div"` and `"mod"` strategies cover the common use case of balanced partitions and are easy to compute. It is a simple and efficient formula to map from `index` to `(partition number, index within partition)`. There is certainly no reason why you can't implement the more general case, but the code will be more complex, with more ops required to implement that index mapping.

@robieta I suggest closing this issue, since there is no bug. (I cannot do it.)
@syltruong Consider posting further questions to stackoverflow.

**Comment by robieta** [comment] 2018-05-24 16:12
Thanks for your help. I learned a lot as well.

**Closed by robieta** 2018-05-24 16:12 UTC
