### ISSUE TITLE
XLA Compilation Bug

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#43723] opened 2020-10-02 09:20 UTC
**System information**
Colab with TensorFlow 2.4.0-dev20201001

**Describe the current behavior**
When using `experimental_compile=True`, I get the following error:

```
InvalidArgumentError: Output shapes of then and else branches do not match: (f32[100,1]) vs. (f32[100])
	 [[{{node gradient_tape/loop_body/logistic_loss/Select/pfor/cond_1}}]] [Op:__inference_train_step_2474]
```

**Describe the expected behavior**
The code should run without errors just like with `experimental_compile=False`

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1TqFDfhxeM6JueuNYbiVBKj1gdUMw03GG?usp=sharing

**Comment by ravikyram** [comment] 2020-10-05 09:46
I have tried in colab with TF nightly version(`2.4.0-dev20201004`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a8888d1e368e78b9660feb932a434133/untitled422.ipynb).Thanks!

**Comment by sachinprasadhs** [comment] 2021-06-02 06:30
Was able to run your code successfully without any errors in Tf Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ff0541286012b1e1837ad364a67e9ecf/43723.ipynb).
Closing this issue since it is fixed, feel free to reopen. Thanks!

**Closed by sachinprasadhs** 2021-06-02 06:30 UTC
Labels: TF 2.3, comp:xla, stat:awaiting tensorflower, type:bug
