### ISSUE TITLE
[RNN] dynamic input shape support

### ISSUE THREAD

**Issue by superlyy** [tensorflow/tensorflow#40185] opened 2020-06-05 09:50 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): tf-nightly (2.3.0.dev20200604)

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
https://colab.research.google.com/drive/1BtT2DkitM6PQKxOAsd-S0IU2Fwh2Reo1?usp=sharing
```

**Failure details**
I was heard about the support for unknown dimensions in TF Lite (https://github.com/tensorflow/tensorflow/issues/29590#issuecomment-580951882), then I tried to convert my model mainly followed by the instructions (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb), but with replacing specific dimensions in TensorSpec() to None, the model exported to SavedModel format successfully. However, the conversion of TF Lite converter didn't work fine (errors shown in Colab).

Before this, I've also tried fixed size in TenserSpec(), then called resize_tensor_input() & allocate_tensors() on the TF Lite interpreter's side, but it didn't work either :(

Are there any proper ways for model in TF Lite to accept variable shape data?

**Comment by Saduf2019** [comment] 2020-06-05 11:35
@superlyy 
I ran the code shared, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/02e436b2bcecb88fb846e2859b8a988d/untitled217.ipynb) , please let us know if this confirms the issue.

**Comment by superlyy** [comment] 2020-06-05 12:06
@Saduf2019 
I ran this code successfully before, but I think it doesn't mention about variable size input tensor any.

**Comment by ElPapi42** [comment] 2020-06-06 16:58
Hello @superlyy i dont know your use case, i was having this same issue with images, but later i realize that i will not work with image tensor but with byte strings tensor, maybe you can update your approach to work that way. i have an implementation here https://github.com/ElPapi42/deep-deblurring-model/blob/tflite/deblurrer/model/wrapper.py, check the decorator, maybe can be helpful for you.

**Comment by Saduf2019** [comment] 2020-06-07 14:57
@superlyy
Please update as per above comment.

**Comment by superlyy** [comment] 2020-06-07 19:38
Hey guys, @ElPapi42, thanks for the suggestions again. I try with a [subclassed Model](https://colab.research.google.com/drive/11OeYjwm4CUfL9wSnbAtQaMSyXqQOGlNK?usp=sharing), but it still doesn't work well with LSTM. Btw, the model is actually made for MIR-related task, the inputs are time-series of preprocessed features.

**Comment by ElPapi42** [comment] 2020-06-07 19:50
Hello again! i don't have a solution, but I noticed you don't initialize the model weights before saving to disk, can you try to forward pass a batch of sample data through the architecture before doing ```tf.saved_model.save()```?

**Comment by superlyy** [comment] 2020-06-08 04:47
Absolutely. Before saving model, I forward a random data to model by using fit() [in here](https://colab.research.google.com/drive/11OeYjwm4CUfL9wSnbAtQaMSyXqQOGlNK#scrollTo=-FJBTa9cN88y). But it shows another error in convert.convert():
`None is only supported in the 1st dimension. Tensor 'args_0' has invalid shape '[None, None, 256]'.`
I'm wondering if TF Lite can not only support the dynamic shape in batch size, but also the other dimensions?

**Comment by ElPapi42** [comment] 2020-06-08 15:22
I decide to write another bare minimum example, and I can confirm this only happens with LSTM layer, when changed to GRU everything works:
```
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Bidirectional, GRU

class SubClassedModel(tf.keras.Model):
    def __init__(self):
        super(SubClassedModel, self).__init__()
        self.model = Bidirectional(GRU(4, time_major=True, return_sequences=True), name='BILSTM_OUTPUT')

    @tf.function(input_signature=[tf.TensorSpec(shape=[None, None, 256], dtype=tf.float32)])
    def call(self, inputs):
        return self.model(inputs)

def convert(model):
    converter = tf.lite.TFLiteConverter.from_keras_model(model) 
    return converter.convert()

model = SubClassedModel()
test_input = tf.random.uniform(shape=[2, 2, 256], dtype=tf.float32)
with tf.device('/cpu:0'):
    test_output = model(test_input)

tflite = convert(model)
```
Dont know the reason for this error, but surely must be inspected @Saduf2019

**Comment by Saduf2019** [comment] 2020-06-09 14:18
@superlyy @ElPapi42 
Please share a colab gist of the error faced for us to analyse

**Comment by ElPapi42** [comment] 2020-06-09 14:28
@Saduf2019 https://colab.research.google.com/drive/1sPKS9ZhRmCVV9JB9KmY0ywH7ZxWHFKxQ?usp=sharing

If you change the LSTM layer to a GRU, everything works on 2.3.0-dev20200609. On 2.2.0 both are broken.

**Comment by jvishnuvardhan** [comment] 2020-12-13 02:42
@ElPapi42 @superlyy Looks like this was resolved in recent `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3658c3ba00ffa7a6f09f23b0007c88ef/untitled227.ipynb). thanks!

**Closed** 2020-12-27 03:33 UTC
Labels: TF 2.3, TFLiteConverter, stalled, stat:awaiting response, type:bug
