### ISSUE TITLE
Bug in TF2.0 & V100: Inconsistent 2d convolution results w.r.t batch size

### ISSUE THREAD

**Issue by jaywalnut310** [tensorflow/tensorflow#30975] opened 2019-07-24 05:32 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: Python 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10 / cuDNN 7
- GPU model and memory: NVIDIA V100 / 32GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I set inputs are tensors which contain only ones.
Then, the output of `tf.nn.conv2d` is different when batch_sizes are 64 and 128.

**Describe the expected behavior**
The output of `tf.nn.conv2d` should not be different w.r.t batch sizes.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
code:
```python
import tensorflow as tf
print("TF_VERSION: %s" % tf.__version__)

x = tf.ones((128, 28, 28, 32))
kernel = tf.ones((3, 3, 32, 64))

ya = tf.nn.conv2d(x[:64], kernel, [1, 1], "SAME")
yb = tf.nn.conv2d(x, kernel, [1, 1], "SAME")[:64]
print(tf.reduce_sum(tf.math.abs(ya- yb)))
```
printed outputs:
```
TF_VERSION: 2.0.0-beta1
tf.Tensor(144.375, shape=(), dtype=float32)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

From the code I'm given, the values of `ya` and `yb` are as below:
`ya`:
```
<tf.Tensor: id=10, shape=(64, 28, 28, 64), dtype=float32, numpy=
array([[[[128., 128., 128., ..., 128., 128., 128.],
         [192., 192., 192., ..., 192., 192., 192.],
         [192., 192., 192., ..., 192., 192., 192.],
         ...,
         [192., 192., 192., ..., 192., 192., 192.],
         [192., 192., 192., ..., 192., 192., 192.],
         [128., 128., 128., ..., 128., 128., 128.]]]], dtype=float32)>
```
`yb`:
```
<tf.Tensor: id=15, shape=(64, 28, 28, 64), dtype=float32, numpy=
array([[[[128.00009, 128.00009, 128.00009, ..., 128.00009, 128.00009,
          128.00009],
         [192.0001 , 192.0001 , 192.0001 , ..., 192.0001 , 192.0001 ,
          192.0001 ],
         [192.00009, 192.00009, 192.00009, ..., 192.00009, 192.00009,
          192.00009],
         ...,
         [192.00012, 192.00012, 192.00012, ..., 192.00012, 192.00012,
          192.00012],
         [192.00012, 192.00012, 192.00012, ..., 192.00012, 192.00012,
          192.00012],
         [128.0001 , 128.0001 , 128.0001 , ..., 128.0001 , 128.0001 ,
          128.0001 ]]]], dtype=float32)>
```

**Comment by gadagashwini** [comment] 2019-07-26 05:38
@jaywalnut310, I tried reproducing the reported issue on Colab with TF 2.0.0.beta1 but i got same result for `ya` and `yb`. The result of the above code is 
```
TF_VERSION: 2.0.0-beta1
tf.Tensor(0.0, shape=(), dtype=float32)
```
Please try once and let us know the expected behavior. Thanks!

**Comment by gadagashwini** [comment] 2019-08-01 05:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-01 05:24 UTC
Labels: 2.0.0-beta0, comp:apis, stat:awaiting response, type:support
