### ISSUE TITLE
from google.protobuf import descriptor as _descriptor ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by aerointern16** [tensorflow/tensorflow#3086] opened 2016-06-28 20:51 UTC
Hey guys I'm working on a project using tensorflow on the Amazon Web Services microservices platform and I've run into a few problems. I installed tensorflow using pip into a virtualenv. Then I took the contents of /env/lib/python2.7/site-packages/ and zipped it along with my source code into a development package for AWS Lambda (env is the name of my virtualenv). This is the process for using python libraries for an AWS Lambda process and I haven't run into any problems with other libraries. I've done this for numpy,scipy,Pillow, and a bunch of other far less supported libraries and they have all worked fine with Lambda.

However when I attempt to use tensorflow it returns this:

Unable to import module 'classify': Traceback (most recent call last): File `"/var/task/tensorflow/python/__init__.py",` line 52, in <module> from tensorflow.core.framework.graph_pb2 import * File "/var/task/tensorflow/core/framework/graph_pb2.py", line 6, in <module> from google.protobuf import descriptor as _descriptor ImportError: No module named google.protobuf   Error importing tensorflow. Unless you are using bazel, you should not try to import tensorflow from its source directory; please exit the tensorflow source tree, and relaunch your python interpreter from there.

classify is the source script AWS Lambda calls when it is invoked and was zipped along with the contents of  /env/lib/python2.7/site-packages/  as I described.

These errors have been addressed a couple of other places but none of the solutions I found on those pages have worked for me, probably because none of them were using lambda. Is it possible that tensorflow just will not work with lambda because of the way lambda imports libraries? If so is there anyway import the tensorflow package from just a source folder that I upload as a zip?

Specific Steps to Reproduce:

- virtualenv env 
- env/bin/pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
- zip contents of /env/lib/python2.7/site-packages with .py file classify
- upload to aws lambda function
- invoke aws lambda function which calls classify and runs into an issue with "import tensorflow as tf"

It's occurred to me that this probably isn't something tensorflow is probably supporting given that most people aren't using tensorflow inside AWS containers but hopefully someone can help or at least give it their best shot even if they don't specifically have experience with AWS.

Thanks!!

**Comment by aerointern16** [comment] 2016-06-28 21:29
Okay I have no idea what this does but it fixed this whole issue::

cd into site-packages
touch google/__init__.py

^bash

**Comment by martinwicke** [comment] 2016-06-30 20:23
That is fascinating. I have no idea what the problem is, but it may be endemic to AWS lambda. I'll close this issue.

**Closed by martinwicke** 2016-06-30 20:23 UTC

**Comment by JamesBelchamber** [comment] 2016-09-14 11:42
Stumbled over this on my travels. It's not Lambda, it's the `protobuf` module: https://github.com/google/protobuf/issues/1296

**Comment by adityap86** [comment] 2017-03-09 13:27
@JamesBelchamber Did you face the same problem after doing `touch google/__init__.py ` . I am not able to solve it. Trying to make pyrebase work on AWS Lambda. @aerointern16 . Any idea why this is not working in this case ?
