### ISSUE TITLE
warn("IPython.utils.traitlets has moved to a top-level traitlets package.") google colab

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/tensorflow#38692] opened 2020-04-19 19:06 UTC
I was running a code in colab notebook and  my colab crashed after some iterations and logs showed me this-
warn("IPython.utils.traitlets has moved to a top-level traitlets package.") 

can anyone one help me about what happened and how can i solve this

**Comment by ravikyram** [comment] 2020-04-20 06:41
@maxkaustav 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by JVikoren** [comment] 2020-04-25 18:13
It may be helpful to know I'm having the same issue building a CNN with PyTorch in Colab
- Mac OSX 10.13.6
- Torch version 1.4.0
- Torch Vision version 0.5.0

**Comment by khordoo** [comment] 2020-04-29 17:54
Same Issue here.Building a seq2seq model with Pytorch in Colab
- Mac OSX 10.14.6 , Torch 1.5.0
The notebook keeps crashing and recovering. 

Here's a detailed message of the recovery crash report:

`/usr/local/lib/python3.6/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.`

**Comment by ravikyram** [comment] 2020-04-30 06:39
@maxkaustav 

Looks like this is not Tensorflow issue. Here we address only Tensorflow bug or feature request.Please,close this thread if your issue is not related to Tensorflow. Thanks!

**Closed** 2020-05-14 07:44 UTC
Labels: stalled, stat:awaiting response, type:others
