### ISSUE TITLE
tf.name_scope has no effect when used with tf.cond and autograph

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#38756] opened 2020-04-21 16:04 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5 Beta
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Using `tf.summary.scalar` in a method that is called in `tf.cond` logs the scalar without the `name_scope`. The results are different than when eager execution is used.

**Describe the expected behavior**
`tf.name_scope` should be used.

**Standalone code to reproduce the issue**
### Eager Execution
```python
import tensorflow as tf


def test_summary():
    with tf.name_scope('MyScope') as scope:
        mynum = tf.convert_to_tensor(43.9, name=scope)

        def log_mynum():
            tf.summary.scalar('mynum', data=mynum)
        tf.cond(tf.math.equal(mynum, 43.9), true_fn=log_mynum,
                false_fn=lambda: None, name='tb-mynum')

        log_mynum()

with tf.summary.create_file_writer('./logs').as_default():
    tf.summary.experimental.set_step(0)
    test_summary()
```
![eager](https://user-images.githubusercontent.com/31281983/79886925-e2802180-83c7-11ea-8579-f7a5fddb5fa6.png)

### Autograph
```python
import tensorflow as tf


@tf.function
def test_summary():
    with tf.name_scope('MyScope') as scope:
        mynum = tf.convert_to_tensor(43.9, name=scope)

        def log_mynum():
            tf.summary.scalar('mynum', data=mynum)
        tf.cond(tf.math.equal(mynum, 43.9), true_fn=log_mynum,
                false_fn=lambda: None, name='tb-mynum')

        log_mynum()

with tf.summary.create_file_writer('./logs').as_default():
    tf.summary.experimental.set_step(0)
    test_summary()
```
![autograph](https://user-images.githubusercontent.com/31281983/79887247-689c6800-83c8-11ea-8d3d-e4fb7465ad04.png)

**Other info / logs**
n/a

**Comment by saxenasaurabh** [comment] 2020-04-23 18:26
Could you try this in nightly? 8c1ead8 partially fixes this by propagating the parent `name_scope`. Although, I think there might still be a difference between graph and eager mode because graph mode adds an additional name_scope "cond". We should reconcile those.

**Comment by sumanthratna** [comment] 2020-04-23 19:11
I just ran on `tf-nightly` and I got the following warning:
```
2020-04-23 15:07:04.707011: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: MyScope/tb-mynum/branch_executed/_7
```
However, the TensorBoard output for autograph was the same as the eager execution output. 

As for the additional name_scope, I don't see it in the TensorBoard output, but on 2.1.0 I do remember seeing that a "cond" op is added to the graph (which makes sense).

**Comment by saxenasaurabh** [comment] 2020-04-24 00:24
Thanks for trying that. I have a fix that should make the eager tensorboard consistent with the graph one. I am testing it out.

**Comment by sushreebarsa** [comment] 2021-07-13 14:59
@sumanthratna Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by sumanthratna** [comment] 2021-07-13 21:23
> @sumanthratna Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

I just tried on tf 2.5.0 and the results have not changed since https://github.com/tensorflow/tensorflow/commit/8c1ead8d919c7536c3d8f52fbab44e1dfcd9fd79 was merged. It appears to be the same issue that @saxenasaurabh described in https://github.com/tensorflow/tensorflow/issues/38756#issuecomment-618571584. 

# Eager
![Screen Shot 2021-07-13 at 17 17 37](https://user-images.githubusercontent.com/31281983/125526527-b58bbc6f-aad5-42a3-922b-5e9defabc7c5.png)

# Autograph
when running, I see this in stdout: 
```
2021-07-13 17:19:49.308004: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-13 17:19:49.342490: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: MyScope/tb-mynum/branch_executed/_7
```

![Screen Shot 2021-07-13 at 17 20 59](https://user-images.githubusercontent.com/31281983/125526794-3d4d764c-974c-461c-8869-1ce4bd05d859.png)

**Comment by gadagashwini** [comment] 2022-07-19 05:44
Was able to reproduce the issue with Tf 2.9.1 please find the [gist](https://colab.research.google.com/drive/1acNFpgmHF-2mDLbGMO4m2mu6aWaREfm7?usp=sharing). Thank you!

**Comment by tomytsai1** [comment] 2022-07-26 00:28
Hi @gadagashwini ,
To confirm , the issue you were seeing is not the same as the very original post (that the name_scope of cond didn't show in tf.function mode), but rather the missing graph in eager mode, is that right?

**Comment by tomytsai1** [comment] 2022-07-27 23:08
Hi @gadagashwini ,

Got some findings:
- In eager mode we only see one graph in the summary because both calling `tf.summary.scalar` directly and from `tf.cond` use the same scope prefix, namely "MyScope/".  Hence, the summary was written twice, with the same name and value, so we only saw one graph.
- This is an intentional behavior in the internal version of `name_scope` ([code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L6715)) to ignore the `name` argument in `tf.cond(... , name='tb-mynum')`. From the above name_scope's code, we can see by default eager mode doesn't preserve op level name_scope.
    - Note that the op level name_scope was set by using `ops.name_scope`, different from the public API `tf.name_scope` that adds the name prefix regardless of eager mode or not.  This ticket's original issues was about the public scope and it was fixed earlier.

Therefore, it is not just `tf.cond`, but in general all TensorFlow ops don't add prefix to the name_scope, in eager mode. If you want to debug or output summary in eager mode, please be aware of this behavior and, if need, use `tf.name_scope` to expand name scopes explicitly.

As this is the designed behavior, we don't have plan to change it now and will close this ticket as won't fix. Let us know if you have any further questions. Thanks!

**Closed by tomytsai1** 2022-07-27 23:08 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:core, TF 2.5
