### ISSUE TITLE
i use tensoflow model to predict with java api,why it is more slowly than python or c++ api?

### ISSUE THREAD

**Issue by mengpengfei** [tensorflow/tensorflow#28030] opened 2019-04-22 05:46 UTC
i use tensoflow model to predict with java api,why it is more slowly than python or c++ api?

**Comment by gadagashwini** [comment] 2019-04-24 04:56
@mengpengfei This looks duplicate of [#27999](https://github.com/tensorflow/tensorflow/issues/27999). Can we close this. Thanks!

**Comment by mengpengfei** [comment] 2019-04-24 05:08
yes， no problems

**Closed** 2019-04-24 05:59 UTC
Labels: comp:runtime, type:bug/performance
