### ISSUE TITLE
ESP32 doenst run correct anymore - Person Detection with Esp32 Camera

### ISSUE THREAD

**Issue by filzek** [tensorflow/tensorflow#40956] opened 2020-06-30 20:47 UTC
Hello Folks,

the project build in ESP32 even 4.0, 4.1, 4.2 or latest master of esp-idf build correct but when running there is an error with the camera acquisition.

./components/esp32-camera/driver/camera.c:1412 (discriminator 2)

or in ./components/esp32-camera/driver/camera.c:1415 (discriminator 2)

So, right now cant tell if a tensorflow lite/micro problem or with the camera driver/settings on it.

Can someone in this area test it again???

**Comment by Saduf2019** [comment] 2020-07-01 10:00
@filzek 
Please share simple stand alone code to replicate the issue faced, along with error logs for us to analyse or if possible share a colab gist with the issue faced.

**Comment by filzek** [comment] 2020-07-01 11:19
Hi

The code is the Person Detector example from tensorflow micro github, as it
is, without any addition, following the Readme to build and compile it.

Upload to the device and run.

And return the error and rebooting loop forever.

Em qua, 1 de jul de 2020 07:00, Saduf2019 <notifications@github.com>
escreveu:

**Comment by Saduf2019** [comment] 2020-07-01 14:06
@filzek 
Please share the tensor flow version on which the issue is faced.

**Comment by filzek** [comment] 2020-07-01 16:10
It is the latest version as of in master.

git describe --tags
v1.12.1-35363-gf3ccf59812

git branch -a --contains
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

git show-branch
[master] compat: Update forward compatibility horizon to 2020-06-29

**Comment by advaitjain** [comment] 2020-07-06 17:24
Adding @petewarden and @fredrec for ESP32 integration issues.

**Comment by vikramdattu** [comment] 2020-10-01 07:41
@filzek few questions:

1. Are you using ESP-EYE dev board or something else?
2. Can you please add the logs?

**Comment by bhavikapanara** [comment] 2020-11-03 13:08
@filzek 
which TF version you have used for person detection model training?

**Comment by sushreebarsa** [comment] 2021-07-29 15:51
@filzek 
It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest stable version of TF 2.4.1 or 2.5.0  and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.2, comp:micro:espressif
