### ISSUE TITLE
Calling predict with a keras.Sequence on a keras.saved_model fail if no previous call on numpy

### ISSUE THREAD

**Issue by ClementWalter** [tensorflow/tensorflow#40408] opened 2020-06-12 12:27 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Python 3.6.9 (default, Mar 13 2020, 17:02:25) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)] on darwin
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Tensorflow raises an error when calling the loaded model onto a keras.Sequence. Calling model.build does not solve the issue

**Describe the expected behavior**

It should be possible to call the model onto a keras.Sequence as it works with tf.data.Dataset

**Standalone code to reproduce the issue**

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dense
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import Sequence

#%% Create dummy Sequential
model = Sequential([Input((224, 224, 3)), GlobalAveragePooling2D(), Dense(1)])
model.summary()
assert model.built
model.input_shape
tf.saved_model.save(model, "model")

#%% Make prediction with loaded model and Sequence
tf_model = load_model("model")
class DataGen(Sequence):
    def __init__(self, data, batch_size):
        self.data = data
        self.batch_size = batch_size

    def __getitem__(self, index):
        return self.data[index * self.batch_size : (index + 1) * self.batch_size]

    def __len__(self):
        return len(self.data) // self.batch_size


X = np.random.rand(16, 224, 224, 3)
tf_model.predict(DataGen(X, batch_size=2))
# ValueError: Please provide model inputs as a list or tuple of 2 or 3 elements: (input, target) or (input, target, sample_weights) Received tf.Tensor(...)

#%% Manual build does not fix the issue
assert not tf_model.built
tf_model.build((None, 224, 224, 3))
assert tf_model.built
tf_model.predict(DataGen(X, batch_size=2))

#%% Try with tf.data.Dataset instead: OK
tf_model.predict(tf.data.Dataset.from_tensor_slices(X).batch(2))

#%% Call first on np.array does fix the issue
tf_model.predict(X[:2])
tf_model.predict(DataGen(X, batch_size=2))

#%% But model still does not have input_shape and has "multiple" in summary
tf_model.inputs
tf_model.input_shape
tf_model.summary()
```

**Comment by Saduf2019** [comment] 2020-06-12 14:14
@ClementWalter 
I ran the code shared by you and face this error, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/87d1cb1e22902f78346944ad9df181c1/untitled.ipynb)

**Comment by ClementWalter** [comment] 2020-06-15 08:01
Hi, I have just rerun exactly your notebook and found the expected error, see this [gist](https://colab.research.google.com/gist/ClementWalter/581e1bf23cfdf591ec7b4b77732fa5e0/untitled.ipynb)

**Comment by jvishnuvardhan** [comment] 2020-08-11 01:44
@ClementWalter I think this was resolved in recent TF versions. I tried in `tf-nightly` and I cannot reproduce the error you were facing with `tf2.1` version.

I noticed that you are trying to save a keras (Sequential) model using tensorflow saved_model using `tf.saved_model.save(model, "model")`. However, best approach is to use keras `model.save` like `model.save("model", save_format='tf')`.

Please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2020-08-29 00:22 UTC
Labels: TF 2.1, comp:keras, stalled, stat:awaiting response, type:bug
