### ISSUE TITLE
Issue: Structure of Python function inputs does not match input_signature while trying to save a subclassed model

### ISSUE THREAD

**Issue by datitran** [tensorflow/tensorflow#32488] opened 2019-09-13 07:27 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.14.0-0-g87989f6959 1.14.0 / tensorflow-gpu==2.0.0-rc0
- Python version: 3.6.8
- GPU model and memory: Google Colab (Nvidia T4)

Similar to this issue #28165, I have defined the following Encoder class with a tf.function signature hoping to be able to save it using the SavedModel format. In my case, I'm using a LSTM layer though instead of GRUs:

```
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_size, lstm_size):
        super(Encoder, self).__init__()
        self.lstm_size = lstm_size
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_size)
        self.lstm = tf.keras.layers.LSTM(
            lstm_size, return_sequences=True, return_state=True)

    @tf.function(input_signature=(
        tf.TensorSpec([None, None], tf.int32, name='sequence'),
        (tf.TensorSpec([None, 64], tf.float32, name='states_1'), tf.TensorSpec([None, 64], tf.float32, name='states_2'))
    )) 
    def call(self, sequence, states):
        embed = self.embedding(sequence)
        output, state_h, state_c = self.lstm(embed, initial_state=states)

        return output, state_h, state_c

    def init_states(self, batch_size):
        return (tf.zeros([batch_size, self.lstm_size]),
                tf.zeros([batch_size, self.lstm_size]))

# Some more code for training the seq2seq model...

tf.saved_model.save(
    encoder,  # instance of Encoder
    './some/directory/',
    signatures=encoder.call
)
```
Here's also the Colab notebook to reproduce the results: [Google Colab Link](https://colab.research.google.com/drive/11rgiI7oYT9uiRWG3ZT9NvRhuRJ5ubEQY)

Since the issue was closed I hope it would work now but now I get this weird error that the Python function input does not match the input_signature although they clearly match each other:

```
ValueError: Structure of Python function inputs does not match input_signature:
  inputs: (
    [<tf.Tensor 'sequence:0' shape=(None, None) dtype=int32>, (<tf.Tensor 'states_1:0' shape=(None, 64) dtype=float32>, <tf.Tensor 'states_2:0' shape=(None, 64) dtype=float32>)])
  input_signature: (
    TensorSpec(shape=(None, None), dtype=tf.int32, name='sequence'),
    (TensorSpec(shape=(None, 64), dtype=tf.float32, name='states_1'), TensorSpec(shape=(None, 64), dtype=tf.float32, name='states_2')))
```

**Comment by keotic** [comment] 2019-10-24 10:59
Any updates on this issue, still happens on 2.0 release

**Comment by withme6696** [comment] 2019-11-29 07:41
Have you solved it？I had the same problem.

**Comment by withme6696** [comment] 2019-12-02 06:13
I use this method to solve it.
call fuction has only one param: inputs, package the multi inputs, eg: inputs=[x1, x2]
and the input_signature is:
`@tf.function(input_signature=[[tf.TensorSpec([None, 22], dtype=tf.int64, name='x1'),
                                   tf.TensorSpec([None, 22], dtype=tf.float32, name='x2')]])`

**Comment by jvishnuvardhan** [comment] 2020-03-03 22:24
@datitran Can you please provide a simple standalone code to reproduce the issue? Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-19 01:16
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Saduf2019** [comment] 2020-03-23 11:50
@datitran 
please update on the above comment

**Comment by Saduf2019** [comment] 2020-03-31 11:55
@datitran
please update on the above comment

**Comment by Saduf2019** [comment] 2020-04-07 08:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by Saduf2019** 2020-04-07 08:30 UTC
Labels: TF 2.0-rc0, comp:apis, comp:keras, stat:awaiting response, type:bug

**Comment by taichuai** [comment] 2020-05-07 07:31
ValueError: Structure of Python function inputs does not match input_signature:
  inputs: (
    [<tf.Tensor 'transf_in:0' shape=(None, None) dtype=int32>, <tf.Tensor 'transf_out:0' shape=(None, None) dtype=int32>, <tf.Tensor 'enc_padding_mask:0' shape=(None, None, None) dtype=float32>, <tf.Tensor 'look_ahead_mask:0' shape=(None, None, None) dtype=float32>, <tf.Tensor 'dec_padding_mask:0' shape=(None, None, None) dtype=float32>, <tf.Tensor 'trainable:0' shape=() dtype=bool>],
    False)
  input_signature: (
    TensorSpec(shape=(None, None), dtype=tf.int32, name='transf_in'),
    TensorSpec(shape=(None, None), dtype=tf.int32, name='transf_out'),
    TensorSpec(shape=(None, None, None), dtype=tf.float32, name='enc_padding_mask'),
    TensorSpec(shape=(None, None, None), dtype=tf.float32, name='look_ahead_mask'),
    TensorSpec(shape=(None, None, None), dtype=tf.float32, name='dec_padding_mask'),
    TensorSpec(shape=(), dtype=tf.bool, name='trainable'))

i also meet this error

**Comment by vrdd21** [comment] 2020-06-24 23:34
@taichuai Hello, I have a really same issue. I'm using transformer model and encounter that same error message! If you solved that problem, please give me what was wrong with that...
