### ISSUE TITLE
How can I use the tensorflow.python.profiler.model_analyzer under the estimator framework

### ISSUE THREAD

**Issue by SakuraGit** [tensorflow/tensorflow#31401] opened 2019-08-07 07:39 UTC
I use the estiamtor framework and I want to run profiler within it.
for the feature of estimator, I just write the profiler code like following:
```
with tf.contrib.tfprof.ProfileContext(<my config>) as pctx:
    pctx.add_auto_profiling(<my profiler>)
    estimator.train(<my params>)
```
Luckly, It's work! I can get the profiler and show it on the profiler ui [(profiler ui)](https://github.com/tensorflow/profiler-ui)
Then, I want to use the model_analyzer just like following(just add after the train ):
```
from tensorflow.python.profiler import model_analyzer
model_analyzer(options=model_analyzer.ALL_ADVICE)
```
here is a tip that: No RunMeta.
I know in the normal pipline the runmeta will produce by the profiler, but under estimator, do not need the runmeta.
I would be very grateful for any reply.

**Comment by anush-o** [comment] 2019-08-08 03:51
@SakuraGit ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks

**Comment by oanush** [comment] 2019-08-16 05:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-16 05:00 UTC
Labels: comp:tfdbg, stat:awaiting response, type:support
