### ISSUE TITLE
TF_gradient

### ISSUE THREAD

**Issue by eghbalhosseini** [tensorflow/tensorflow#25694] opened 2019-02-12 17:56 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: Python 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0, V9.0.176
- GPU model and memory: GeForce GT 750M

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

I am trying to use @tf.custom gradient for a one of the layers in a RNN, and running to the following problem, when I compute the gradient of loss in the output layer with respect to weights in hidden layer, I get gradient values, however when I try to compute the gradient of the output of the hidden layer with respect to the input to the layer or states in the layer (y=f(x) and calculating dy/dx ) I get [None]. I am using tf.gradients to compute gradients. I am doing the second part to see if I have implemented the custom gradient correctly. 
this is the activation function from hidden state and output 
```
@tf.custom_gradient
def _calcualte_crossings(x):
    """input :x : a 2D tensor with batch x n
    outputs a tensor with the same size as x
    and values of 0 or 1 depending on comparison between
    x and threshold"""
    dtype=x.dtype
    res=tf.greater_equal(x,0.0)
    def grad(dy):
        # calculate 1-|x|
        temp=1-tf.abs(x)
        dyres=tf.scalar_mul(0.3,tf.maximum(temp,0.0))
        return dyres
    return tf.cast(res,dtype=dtype), grad
```

**Comment by ymodak** [comment] 2019-02-12 18:02
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by ebrevdo** [comment] 2019-02-19 22:48
It would be helpful if you had a minimal reproducing example.

**Comment by tensorflowbutler** [comment] 2019-03-06 18:56
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2019-03-07 18:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-07 18:12 UTC
Labels: comp:ops, stat:awaiting response, type:support
