### ISSUE TITLE
Update Docker description to state CPU requirements

### ISSUE THREAD

**Issue by dpotter-intoto** [tensorflow/tensorflow#21907] opened 2018-08-27 19:49 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary (Docker tensorflow/tensorflow)
- **TensorFlow version (use command below)**: 1.10.1 (from core/public/version.h)
- **Python version**:2.7.12
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: 
\# docker run -it tensorflow/tensorflow bash
root@xxxxxxx:/notebooks# python2.7 -c "import tensorflow as tf"
Illegal instruction

### Describe the problem
This is a request to update documentation to include minimal system requirements, especially the description for Docker images that include prebuilt binaries.

For example, the main Docker image on DockerHub (tensorflow/tensorflow, 19M downloads) [currently does not operate on CPU's without AVX support](https://github.com/tensorflow/tensorflow/issues/17411).  This includes CPUs sold as recently as 4 years ago.

This requirement should be stated in the Docker image description displayed in DockerHub.  Perhaps also include a link to an alternative docker image that users with non-AVX CPUs may utilize to build from source.

### Source code / logs
n/a

**Comment by tensorflowbutler** [comment] 2018-09-16 02:31
Nagging Assignee @jart: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 13:00
Nagging Assignee @jart: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by maritaria** [comment] 2018-10-04 14:18
Also, you can indicate the requirement on the docker image:
https://docs.docker.com/registry/spec/manifest-v2-2/#example-manifest-list
Then users will be notified as soon as trying to pull/execute the image that their platform is insufficient and also the reason why it is.

**Comment by tensorflowbutler** [comment] 2018-11-03 12:32
Nagging Assignee @jart: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-20 07:48
Nagging Assignee @jart: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-04 18:53
Nagging Assignee @jart: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2019-05-17 21:02
@dpotter-intoto Is this still an issue? Thanks!

**Comment by angersson** [comment] 2019-05-17 21:27
Duplicate of #19584.

This is a general issue with TensorFlow's official packages, not the Docker images specifically.

**Comment by dpotter-intoto** [comment] 2019-05-17 21:27
Yes, this is still an issue. Neither
https://hub.docker.com/r/tensorflow/tensorflow nor
https://www.tensorflow.org/install mention that Tensorflow requires a CPU
with AVX support.

**Closed by angersson** 2019-05-17 21:27 UTC
Labels: type:build/install, type:docs

**Comment by angersson** [comment] 2019-05-17 21:30
I have also added a quick note to the Docker hub description for the TensorFlow images.

**Comment by Ark-kun** [comment] 2019-08-01 06:10
> I have also added a quick note to the Docker hub description for the TensorFlow images.

Why didn't you do it the official way? https://docs.docker.com/registry/spec/manifest-v2-2/#example-manifest-list
