### ISSUE TITLE
TensorFlow Lite bazel ios build fails

### ISSUE THREAD

**Issue by lackhole** [tensorflow/tensorflow#39290] opened 2020-05-08 02:15 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2(latest - cloned yesterday)
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source): clang 11.0.3
- CUDA/cuDNN version:
- GPU model and memory:

I've made a code that uses `tensorflowlite_c` and `libtensorflowlite_gpu_delegate.so` in android. And it's build was successful and works well in Android devices.
So I wanted to build the same libraries for ios.
But building `tensorflowlite_c` fails when I'm trying to build for ios.

I've installed the latest XCode from the AppStore, and commandline tools works fine.

### configure
```
➜  tensorflow git:(master) ./configure                                          
You have bazel 3.0.0 installed.
Please specify the location of python. [Default is /Library/Frameworks/Python.framework/Versions/3.7/bin/python3]: 


Found possible Python library paths:
  /Applications/root_v6.19.02/lib
  /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/Applications/root_v6.19.02/lib]
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -D_GLIBCXX_USE_CXX11_ABI=0 -O3


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: y
iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
```

### build
```
➜  tensorflow git:(master) bazel build -c opt --config=ios //tensorflow/lite/c:tensorflowlite_c
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=210
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 --action_env PYTHON_LIB_PATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:ios in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing
INFO: Found applicable config definition build:macos in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Analyzed target //tensorflow/lite/c:tensorflowlite_c (64 packages loaded, 1589 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_yonggyulee/85757772b8505423f8a25bcdc8f80746/sandbox
ERROR: /private/var/tmp/_bazel_yonggyulee/85757772b8505423f8a25bcdc8f80746/external/fft2d/BUILD.bazel:27:1: C++ compilation of rule '@fft2d//:fft2d' failed (Exit 1)
clang: error: invalid version number in '-mmacosx-version-min=13.4'
Target //tensorflow/lite/c:tensorflowlite_c failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.723s, Critical Path: 0.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by teijeong** [comment] 2020-05-09 07:54
Can you specify `--config=ios_fat` instead of `--config=ios` and try again?
https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L104

**Comment by lackhole** [comment] 2020-05-11 01:14
@teijeong 

Build failed with same issue.
I don't understand why `-mmacosx-version-min=13.4` error occurs.

```
➜  tensorflow git:(master) bazel build -c opt --cxxopt=--std=c++11 --config=ios_fat //tensorflow/lite/c:tensorflowlite_c
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/yonggyulee/tf/tf6/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 --action_env PYTHON_LIB_PATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:ios_fat in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --config=ios --ios_multi_cpus=armv7,arm64,i386,x86_64
INFO: Found applicable config definition build:ios in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing
INFO: Found applicable config definition build:macos in file /Users/yonggyulee/tf/tf6/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Analyzed target //tensorflow/lite/c:tensorflowlite_c (64 packages loaded, 1589 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_yonggyulee/85757772b8505423f8a25bcdc8f80746/sandbox
ERROR: /Users/yonggyulee/tf/tf6/tensorflow/tensorflow/lite/kernels/internal/BUILD:695:1: C++ compilation of rule '//tensorflow/lite/kernels/internal:audio_utils' failed (Exit 1)
clang: error: invalid version number in '-mmacosx-version-min=13.4'
Target //tensorflow/lite/c:tensorflowlite_c failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.379s, Critical Path: 0.56s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by teijeong** [comment] 2020-05-11 23:58
Oh I see the problem. I can reproduce this, but not sure if that target was designed to be built for iOS.

For iOS, you can try
`bazel build -c opt --config=ios_fat //tensorflow/lite/experimental/ios:TensorFlowLiteC_framework` to generate .framework file and then include it in your app. Can you try this path?

**Comment by lackhole** [comment] 2020-05-12 01:23
@teijeong 
Thanks. That works.
I'm totally new to iOS, XCode, Swift, and Objective-C so just one more question.
Is .framework file available to use in C++?

**Comment by teijeong** [comment] 2020-05-12 03:58
Only C API is exposed with the framework, but yes it's totally ok to use it with the C++. 
Please see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h for available APIs. Please let me know if your use case can't be covered by the provided C API.

**Comment by lackhole** [comment] 2020-05-12 07:01
@teijeong 
Thanks for your help.
I'll give it a try and come back if a problem happens.

**Comment by teijeong** [comment] 2020-05-15 04:57
Hi lackhole, If everything goes well, can you close the issue?

**Comment by teijeong** [comment] 2020-05-18 02:13
Closing this - if you encounter other problems (besides iOS build issue), please file another bug :)

**Closed by teijeong** 2020-05-18 02:13 UTC
Labels: TF 2.2, comp:lite, type:build/install

**Comment by Miko2x** [comment] 2022-01-05 02:34
Hi @teijeong I'm facing the same issue when i run this bazel command:
`bazel build --action_env PYTHON_BIN_PATH=/usr/bin/python --verbose_failures --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteCMetal_framework`

**Configure**
Same configuration

**Output**
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=164
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-master/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:ios_arm64 in file /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc: --config=ios --cpu=ios_arm64
INFO: Found applicable config definition build:ios in file /Users/adityadwipamungkas/Downloads/tensorflow-master/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/f47028debe93d9514d4c35e1db2957c04950e602.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/apple_support/releases/download/0.10.0/apple_support.0.10.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_swift/releases/download/0.21.0/rules_swift.0.21.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /Users/adityadwipamungkas/Downloads/tensorflow-master/WORKSPACE:23:14: in <toplevel>
  /Users/adityadwipamungkas/Downloads/tensorflow-master/tensorflow/workspace0.bzl:108:34: in workspace
  /private/var/tmp/_bazel_adityadwipamungkas/246c1b33c44a840eaa0052f321b57c7b/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_adityadwipamungkas/246c1b33c44a840eaa0052f321b57c7b/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/gemmlowp/archive/e844ffd17118c1e17d94e1ba4354c075a4577b88.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/322055148b47dccb76bc03ad010f16c1e3a94817.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/lite/ios:TensorFlowLiteCMetal_framework (110 packages loaded, 3980 targets configured).
INFO: Found 1 target...
ERROR: /Users/adityadwipamungkas/Downloads/tensorflow-master/tensorflow/lite/ios/BUILD:185:21: Executing genrule //tensorflow/lite/ios:TensorFlowLiteCMetal_framework failed: (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_adityadwipamungkas/246c1b33c44a840eaa0052f321b57c7b/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adityadwipamungkas/Developer/Flutter/flutter_v1/bin:/Users/adityadwipamungkas/Developer/Flutter/flutter_v1/.pub-cache/bin:/Users/adityadwipamungkas/Developer/Flutter/flutter_v1/bin:/Users/adityadwipamungkas/Developer/Flutter/flutter_v1/.pub-cache/bin \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; INPUT_FRAMEWORK="bazel-out/applebin_ios-ios_arm64-opt-ST-c2e45b3824d7/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteCMetal_framework.zip" BUNDLE_NAME="TensorFlowLiteCMetal" ALLOWLIST_FILE_PATH="tensorflow/lite/ios/allowlist_TensorFlowLiteCMetal.txt" EXTRACT_SCRIPT_PATH="bazel-out/host/bin/tensorflow/lite/ios/extract_object_files_main" OUTPUT="bazel-out/ios_arm64-opt/bin/tensorflow/lite/ios/TensorFlowLiteCMetal_framework.zip" "bazel-out/host/bin/tensorflow/lite/ios/hide_symbols_with_allowlist"')
Execution platform: @local_execution_config_platform//:platform
  File "/private/var/tmp/_bazel_adityadwipamungkas/246c1b33c44a840eaa0052f321b57c7b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/lite/ios/extract_object_files_main.runfiles/org_tensorflow/tensorflow/lite/ios/extract_object_files_main.py", line 27
    def main(argv: Sequence[str]) -> None:
                 ^
SyntaxError: invalid syntax
Archive:  bazel-out/applebin_ios-ios_arm64-opt-ST-c2e45b3824d7/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteCMetal_framework.zip
  inflating: /var/folders/nh/8rbl1_fd01g1lc3ylj5rs09m0000gn/T/framework.6il99Zk3/TensorFlowLiteCMetal.framework/Headers/TensorFlowLiteCMetal.h  
  inflating: /var/folders/nh/8rbl1_fd01g1lc3ylj5rs09m0000gn/T/framework.6il99Zk3/TensorFlowLiteCMetal.framework/Headers/metal_delegate.h  
  inflating: /var/folders/nh/8rbl1_fd01g1lc3ylj5rs09m0000gn/T/framework.6il99Zk3/TensorFlowLiteCMetal.framework/Modules/module.modulemap  
  inflating: /var/folders/nh/8rbl1_fd01g1lc3ylj5rs09m0000gn/T/framework.6il99Zk3/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal  
Target //tensorflow/lite/ios:TensorFlowLiteCMetal_framework failed to build
INFO: Elapsed time: 409.138s, Critical Path: 34.96s
INFO: 867 processes: 339 internal, 528 local.
FAILED: Build did NOT complete successfully
```

**Comment by yyoon** [comment] 2022-01-05 02:49
@Miko2x That error suggests that your Python interpreter doesn't understand the type hinting syntax, which was introduced in Python 3.5. What is your Python version? Can you try the build again with Python 3.5 or higher?

**Comment by Miko2x** [comment] 2022-01-05 03:09
@yyoon, Thanks for the reply.

On this report I'm using 2.7.18. After that when I try to use Python 3.7.2, it's give me another error message. Looks like the program can't find numpy path, is there any file that i can set the numpy path?

```
adityadwipamungkas@Adityas-MacBook-Pro tensorflow-master % pip3 show numpy
Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: 
Required-by:
```

**Configure file**

<img width="494" alt="Screen Shot 2022-01-05 at 10 05 47" src="https://user-images.githubusercontent.com/41611726/148154437-d013facc-674a-453a-806a-0bbe4f6083fe.png">

**Output**

```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/Users/adityadwipamungkas/Downloads/tensorflow-master/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//tensorflow/lite/ios:TensorFlowLiteCMetal_framework' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 211.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 66 targets configured)
    Fetching @go_sdk; fetching 28s
    Fetching @local_config_cc; fetching
```

**Comment by yyoon** [comment] 2022-01-05 04:36
Could you file a new issue for your issue and cc me?
I don't think it's appropriate to continue this on an issue closed a long time ago.

**Comment by Miko2x** [comment] 2022-01-05 04:40
> Could you file a new issue for your issue and cc me? I don't think it's appropriate to continue this on an issue closed a long time ago.

Sure.
