### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute 'strategy_supports_no_merge_call'

### ISSUE THREAD

**Issue by DL-stack** [tensorflow/tensorflow#55724] opened 2022-04-24 10:34 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.7.0-rc1-69-gc256c071bb2 2.7.0

### Custom Code

Yes

### OS Platform and Distribution

NAME="CentOS Linux" VERSION="7 (Core)"

### Python version

Python 3.7.13

### CUDA/cuDNN version

Cuda 8.x and Cuda 11.x

### GPU model and memory

NVIDIA GeForce GTX 1080 Ti  11178MiB

### Current Behaviour?

```shell
When I want to train my model I get the error shown below. I couldn't find any solution our hint. 
Can you explain why this error occurs and how to solve it?

Many thanks in advance!
```

### Standalone code to reproduce the issue

```shell
This error arises in my own code, which is a simple U-net taking in 3D numpy arrays
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "./training.py", line 299, in launch
    sample_weight=sample_weight,
  File "./python3.7/site-packages/keras/engine/training.py", line 2093, in train_on_batch
    logs = self.train_function(iterator)
  File "./python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "./.local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    File "./lib/python3.7/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "./lib/python3.7/site-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "./lib/python3.7/site-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "./lib/python3.7/site-packages/keras/engine/training.py", line 863, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "./lib/python3.7/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "./lib/python3.7/site-packages/keras/optimizer_v2/optimizer_v2.py", line 668, in apply_gradients
        grads_and_vars = self._aggregate_gradients(grads_and_vars)
    File "./lib/python3.7/site-packages/keras/optimizer_v2/optimizer_v2.py", line 484, in _aggregate_gradients
        return self.gradient_aggregator(grads_and_vars)
    File "./lib/python3.7/site-packages/keras/optimizer_v2/utils.py", line 33, in all_reduce_sum_gradients
        if tf.__internal__.distribute.strategy_supports_no_merge_call():

    AttributeError: module 'tensorflow.compat.v2.__internal__.distribute' has no attribute 'strategy_supports_no_merge_call'
```
</details>

**Comment by sushreebarsa** [comment] 2022-04-24 10:39
@DL-stack 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by iwen-kang** [comment] 2022-04-25 23:45
@sushreebarsa I did provide code snippet in my PR, not sure why it disappeared, here it is:
pip install tensorflow==2.6
pip install keras==2.6.0
pip install --upgrade tensorflow-hub
#conda install -c conda-forge tensorflow-hub

pip install tensorflow_datasets
pip install tensorflow-text==2.6 --no-dependencies
pip install --upgrade tensorflow-estimator==2.6.0
python -c "import tensorflow as tf; import tensorflow_datasets as tfds; print('tfds.__version__:' + tfds.__version__)"

**Comment by sushreebarsa** [comment] 2022-04-26 03:04
@DL-stack I tried to replicate the issue on colab using TF v2.8.0 and didn't face any issue as reported here.Could you please have a look at this [gist ](https://colab.research.google.com/gist/sushreebarsa/3286d5010c86f1ba8c23f5cd96e58549/55724.ipynb)and  try with the latest TF version ?Please let us know if it helps?  Thank you!

**Comment by iwen-kang** [comment] 2022-04-27 21:37
@sushreebarsa This appears to be conflict caused by new release of python setuptools lib. After making sure it is not in the path this problem is gone. Please feel free to close this issue. Thanks!

**Comment by sushreebarsa** [comment] 2022-04-28 02:24
@DL-stack Thank you for the update!
Glad it is resolved.
Closing this ticket as per your request ,please feel free to reopen if you still have any concern.Thanks!

**Closed by sushreebarsa** 2022-04-28 02:24 UTC
Labels: stat:awaiting response, type:bug, TF 2.7
