### ISSUE TITLE
[BUG] Cifar10 mutigpu loss does not decrease and is oscillating 

### ISSUE THREAD

**Issue by creativesh** [tensorflow/tensorflow#15428] opened 2017-12-17 19:25 UTC
Hi
I want to develope a resnet50 multigpu system in tensorflow,
so I want to replace my model in [**cifar10_multigpu_train**](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py)
but when I run this code, loss does not decrease efficiently,until step 5000
my question is : can I trust this code? Is  the code correct?
**I use:**
ubuntu 16.04
installed tensorflow with pip2
tensorflow 1.4
cudnn       6 
cuda     8.0.44
Gtx 1080 (2 gpus/8g memory)

command to produce:
go to the above link,download **cifar10_multi_gpu_train.py** and run it

**Comment by tensorflowbutler** [comment] 2017-12-18 07:23
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-03 19:07
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:09
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-06 07:32
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-20 19:31
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:09
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 00:50
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by angersson** [comment] 2018-04-03 01:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by angersson** 2018-04-03 01:26 UTC
Labels: stat:awaiting response
