### ISSUE TITLE
Cant convert my model to tflite. Show the following error. (included code).

### ISSUE THREAD

**Issue by chandanchinta** [tensorflow/tensorflow#25162] opened 2019-01-24 06:59 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):anaconda
- TensorFlow version (use command below):latest
- Python version:3.6.5
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:No
- GPU model and memory:920m

code used to convert the file:
from tensorflow.contrib import lite
keras_file = "movie_classifier.h5"
keras.models.save_model(model, keras_file)
converter = lite.TocoConverter.from_keras_model_file(keras_file)
tflite_model = converter.convert()
open("linear.h5" , wb).write(tflite_model)

Error is as follows:
RuntimeError: TOCO failed see console for info.
b'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nTraceback (most recent call last):\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\ProgramData\\Anaconda3\\Scripts\\toco_from_protos-script.py", line 6, in <module>\r\n    from tensorflow.contrib.lite.toco.python.toco_from_protos import main\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nModuleNotFoundError: No module named \'_tensorflow_wrap_toco\'\r\n'
None

**Comment by ANSHUMAN87** [comment] 2019-01-24 10:20
Can you try like below
`from tensorflow import lite`

instead of
`from tensorflow.contrib import lite`

**Comment by chandanchinta** [comment] 2019-01-24 11:04
> Can you try like below
> `from tensorflow import lite`
> 
> instead of
> `from tensorflow.contrib import lite`

@ANSHUMAN87 

I tried but its giving the following error

ImportError: cannot import name 'lite'

**Comment by ANSHUMAN87** [comment] 2019-01-24 11:53
Try to follow the steps in below link:
https://www.tensorflow.org/install/pip

I suspect because you are using Python 3.7, the package released does not support Python 3.7 yet.
![image](https://user-images.githubusercontent.com/32511895/51676448-a3182900-1ffc-11e9-8db0-c49345797fb4.png)

Try to use respective versions and check once.
Suggest try with Python 3.6.
Please do let me know your outcomes.

**Comment by chandanchinta** [comment] 2019-01-24 15:33
> Try to follow the steps in below link:
> https://www.tensorflow.org/install/pip
> 
> I suspect because you are using Python 3.7, the package released does not support Python 3.7 yet.
> ![image](https://user-images.githubusercontent.com/32511895/51676448-a3182900-1ffc-11e9-8db0-c49345797fb4.png)
> 
> Try to use respective versions and check once.
> Suggest try with Python 3.6.
> Please do let me know your outcomes.

I thought the same but I am using python 3.6.5.
what should be the problem.
Thanks for putting up with me .

**Comment by ymodak** [comment] 2019-01-24 23:15
Can you try,
>converter = tf.contrib.lite.TocoConverter.from_keras_model_file(keras_file)
Also can you print the current TF version you are using?

**Comment by chandanchinta** [comment] 2019-01-25 04:55
> converter = tf.contrib.lite.TocoConverter.from_keras_model_file(keras_file)

I have tried it out.
It is giving the same error as before.

**Comment by ymodak** [comment] 2019-01-25 21:52
Can you try with tf-nightly build?

**Comment by jdduke** [comment] 2019-02-07 23:47
Duplicate of #23678.

**Closed by jdduke** 2019-02-07 23:47 UTC
Labels: comp:lite

**Comment by Jakejaga5** [comment] 2019-02-09 14:36
why

**Comment by akinpelu746** [comment] 2019-08-08 03:55
hello
my code is


import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model_file( r'/content/drive/My Drive/inceptionv3-transfer-learning__fine_tune.h5') # Your model's name
model = converter.convert()
file = open( 'model.tflite' , 'wb' )
file.write( model )

ValueError: None is only supported in the 1st dimension. Tensor 'input_1' has invalid shape '[None, None, None, 3]'.

what can ido?

**Comment by jdduke** [comment] 2019-08-08 15:51
@akinpelu746, that's a separate issue, you need to specify the inputs and input shapes for inputs that use placeholder shapes (see https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model_file).

**Comment by akinpelu746** [comment] 2019-08-17 22:29
how can  I stop my model from predicting what is not trained for?
I trained my model based on tomato leaves but if I feed in any picture apart from tomato leaves my model will still classifier it?
what can I do?

**Comment by ashishmagar600** [comment] 2020-02-12 13:16
> converter = lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()



Why are there not any updates after this...??

**Comment by Jakejaga5** [comment] 2020-02-12 13:24
@ashishmagar600 could be elaborate more?

**Comment by ashishmagar600** [comment] 2020-02-13 05:54
The error still persists...

`ImportError: cannot import name lite
`

**Comment by Jakejaga5** [comment] 2020-02-13 06:56
@ashishmagar600  please upload the screenshot of your terminal
