### ISSUE TITLE
`tf.experimental.numpy.sqrt` lack support for bfloat16

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54818] opened 2022-03-02 05:37 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.random.uniform([2,1], dtype=tf.bfloat16) 
print(tf.math.sqrt(x)) # pass
print(tf.experimental.numpy.sqrt(x)) # AttributeError
```

**Describe the current behavior**
`tf.experimental.numpy.sqrt` cannot accept a tensor of type `bfloat16`. 
For the above code snippet, the error message is:
```
AttributeError: 
        'EagerTensor' object has no attribute 'astype'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()
```

**Comment by tilakrayal** [comment] 2022-03-02 10:44
@chunduriv ,
I was able to reproduce the issue in tf v2.8, 2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/113610cd7f5c1fd4a18dfe258f73f66d/54818.ipynb).

**Comment by rthadur** [comment] 2022-03-02 16:21
Thank you , will submit a fix soon.

**Comment by ArrowIntoTheSky** [comment] 2022-03-10 02:30
Thanks @rthadur .
Here are more `tf.experimental.numpy` APIs that also lack `bfloat16` support:
```
tf.experimental.numpy.cos
tf.experimental.numpy.exp
tf.experimental.numpy.log1p
tf.experimental.numpy.expm1
tf.experimental.numpy.cosh
tf.experimental.numpy.tanh
tf.experimental.numpy.exp2
tf.experimental.numpy.log2
```

**Comment by mohantym** [comment] 2023-01-24 10:02
Hi @ArrowIntoTheSky !
We are checking to see whether you still need help in this issue .This seems to be resolving with  below changes (Followed tnp guide) . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/7883b69a3276fa66212a29c20372d328/54818.ipynb#scrollTo=yxZ1gvZB8dId) from 2.11 for reference. 

```
import tensorflow as tf

#Followed tnp syntax - REf-  https://www.tensorflow.org/guide/tf_numpy
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

x = tf.random.uniform([2,1], dtype=tf.bfloat16)
print(tf.math.sqrt(x)) # pass
print(tf.experimental.numpy.sqrt(x)) # AttributeError 
```

Thank you!

**Closed** 2023-02-07 11:07 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.7
