### ISSUE TITLE
Non-OK-status: tensorflow::Env::Default()->DeleteFile(ptx_path) status: Not found: 

### ISSUE THREAD

**Issue by qianzhang613** [tensorflow/tensorflow#39712] opened 2020-05-20 11:24 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Centos7.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip install officail
- TensorFlow version (use command below):
1.15.2 with gpu
- Python version:
3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0/ 7.6
- GPU model and memory:
v100 32G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Can't find ptxas binary in ${CUDA_DIR}/bin.  Will back to the GPU driver for PTX -> sass compilation.  This is OK so long as you don't see a warning below about an out-of-date driver version.
2020-04-07 16:28:20.691087: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Searched for CUDA in the following directories:
2020-04-07 16:28:20.691210: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   ./cuda_sdk_lib
2020-04-07 16:28:20.691315: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   /usr/local/cuda
2020-04-07 16:28:20.691454: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   .
2020-04-07 16:28:20.691571: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:75] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2020-04-07 16:28:20.725596: F tensorflow/stream_executor/cuda/ptxas_utils.cc:181] Non-OK-status: tensorflow::Env::Default()->DeleteFile(ptx_path) status: Not found: /tmp/tempfile-72d9c7c8-2841-4447-bd7d-3947098f8e24-6a7fc700-2624-5a2af2a888f80; No such file or directory
Fatal Python error: Aborted

**Describe the expected behavior**
1. the code in follows log the mislead warning? 
https://github.com/tensorflow/tensorflow/blob/4386a6640c9fb65503750c37714971031f3dc1fd/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc#L405
```
       bool log_warning = true;
          if (maybe_cubin.status().code() ==
              tensorflow::error::Code::NOT_FOUND) {
            // Missing ptxas is expected in some environments where CUDA SDK
            // binaries are not available. We don't want to spam logs with
            // identical warnings in this case.

            // TODO(jlebar): we should implement a LOG_FIRST_N and LOG_EVERY_N
            // for more general usage.
            static std::atomic<bool> warning_done(false);
            log_warning = !warning_done.exchange(true);
          }
          if (log_warning) {
            PrintCantFindCudaMessage(
```
2. if some exception that the ptx_path did not create, there will rasie a error that : `2020-04-07 16:28:20.725596: F tensorflow/stream_executor/cuda/ptxas_utils.cc:181] Non-OK-status: tensorflow::Env::Default()->DeleteFile(ptx_path) status: Not found:`

https://github.com/tensorflow/tensorflow/blob/4386a6640c9fb65503750c37714971031f3dc1fd/tensorflow/stream_executor/cuda/ptxas_utils.cc#L184
```

  // Write ptx into a temporary file.
  string ptx_path;
  if (!env->LocalTempFilename(&ptx_path)) {
    return port::InternalError("couldn't get temp PTX file name");
  }
  auto ptx_cleaner = tensorflow::gtl::MakeCleanup([&ptx_path] {
    TF_CHECK_OK(tensorflow::Env::Default()->DeleteFile(ptx_path));
  });

  TF_RETURN_IF_ERROR(
      tensorflow::WriteStringToFile(env, ptx_path, ptx_contents));
  VLOG(2) << "ptx written to: " << ptx_path;

```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by qianzhang613** [comment] 2020-05-26 11:08
@ymodak  could you look at this problem?

**Comment by sanjoy** [comment] 2020-06-12 06:49
Does this reproduce on tensorflow-nightly?

**Comment by qianzhang613** [comment] 2020-06-24 02:40
> Does this reproduce on tensorflow-nightly?

i didnot try , because we are using tf v1.15

**Comment by mihaimaruseac** [comment] 2020-06-24 22:12
Most likely it has been solved in nightly. If it has, we can attempt a backport when doing a patch release on 1.15.

In the end, we are doing development only on master branch and the releases are snapshots of the code at that time, with some cherry-picks. So you will have to move to newer versions at one point

**Comment by GuoYL36** [comment] 2020-09-24 02:10
Has it been solved? I have a same problem using TF2.0.0. Please tell me the solution, thank you !

**Comment by mihaimaruseac** [comment] 2020-09-25 16:42
@GuoYL36 can you try reproducer with `tf-nightly`?

**Comment by GuoYL36** [comment] 2020-09-26 10:17
> @GuoYL36 can you try reproducer with `tf-nightly`?

No, I did not try. Now I can run code normally without doing anything, and I just want to say it is amazing.<^_^>

**Comment by GuoYL36** [comment] 2020-09-27 16:36
> @GuoYL36 can you try reproducer with `tf-nightly`?

This bug is solved now, which caused by GPU which is in non-ok status. I found no gpu is used to run code, but gpu-memory is used. So I kill the hidden-process, then everything is ok.

**Comment by mihaimaruseac** [comment] 2020-09-28 17:22
So it seems it has been solved. I think we can close the issue and reopen if there is a resurgence

**Closed by mihaimaruseac** 2020-09-28 17:22 UTC
Labels: TF 1.15, comp:gpu, type:bug
