### ISSUE TITLE
Learning Rate Scheduler with multi GPU

### ISSUE THREAD

**Issue by Robmosh91** [tensorflow/tensorflow#31796] opened 2019-08-20 13:28 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- CUDA/cuDNN version: 10.0
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**
When using single GPU model and Training the LearningRateScheduler Callback works fine and everything runs as expected.
If I change to multi gpu training I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    workers=min(multiprocessing.cpu_count()//2, 32)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 208, in model_iteration
    callbacks.on_epoch_begin(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 295, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 1351, in on_epoch_begin
    raise ValueError('Optimizer must have a "lr" attribute.')
ValueError: Optimizer must have a "lr" attribute.
```

Only thing change is single to multi gpu.

**Comment by ravikyram** [comment] 2019-08-21 09:25
In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-08-29 08:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-08-29 08:12 UTC
Labels: TF 1.14, comp:gpu, comp:keras, stat:awaiting response, type:support
