### ISSUE TITLE
ImportError: cannot import name 'audio' from 'tensorflow._api.v1'

### ISSUE THREAD

**Issue by 2014bcs007** [tensorflow/tensorflow#26881] opened 2019-03-19 13:20 UTC
Am new in Tensor flow,i was running my first example in tensor flow but found this issue.
How can i go about it    

"TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))

ConverterError: TOCO failed. See console for info.
Traceback (most recent call last):
  File "D:\Software\Scripts\toco_from_protos-script.py", line 6, in <module>
    from tensorflow.lite.toco.python.toco_from_protos import main
  File "D:\Software\lib\site-packages\tensorflow\__init__.py", line 31, in <module>
    from tensorflow._api.v1 import audio
ImportError: cannot import name 'audio' from 'tensorflow._api.v1' (D:\Software\lib\site-packages\tensorflow\_api\v1\__init__.py)

**Comment by ymodak** [comment] 2019-03-19 20:34
Please provide following information. Thanks!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-03-25 17:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-25 17:24 UTC
Labels: stat:awaiting response
