### ISSUE TITLE
pickling showing error : <<TypeError: can't pickle _thread._local objects>> working with tensorflow2.0 while it works with tensorflow 1.14

### ISSUE THREAD

**Issue by tseth92** [tensorflow/tensorflow#33283] opened 2019-10-12 11:42 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9.11 (stretch)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): 2.0
- Python version: Python 3.7.3
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behaviour**
Currently, if I pickle in 2.0, it gives error TypeError: can't pickle _thread._local objects whereas in tensorflow version 1.14, it works fine

**Describe the expected behavior
[tp.txt](https://github.com/tensorflow/tensorflow/files/3720599/tp.txt)
**
pickling should work in in tf 2.0

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
in the attached file, run get_model method for tf2.0  and get_model_prev to run for tf1.14.
You will see that pickle model is generated for 1.14 but not for 2.0

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-10-14 07:04
@tseth92, I tried to replicate the reported issue but i got different error message. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/4e14c5835a91961694b93612c9bc14a5/untitled194.ipynb) and help us provide the issue. Thanks!

**Comment by tseth92** [comment] 2019-10-16 04:05
@gadagashwini I just ran the gist, the code will work fine if you choose !pip install tensorflow==1.14

But if you choose !pip install tensorflow==2.0 and if you uncomment get_model() and comment get_model_prev(), you will get to see the issue:
```
model = get_model()
#model = get_model_prev()
```
Error: 	
**TypeError: can't pickle _thread._local objects**

I have added these two methods to show that with get_model_prev() ie. model with normal Keras, its working fine and able to pickle if you use previous version of tensorflow and use keras to build layers.

But, if you try to use tf 2.0 directly and build layers using that, it shows error as in get_model()
TypeError: can't pickle _thread._local objects

**Comment by gadagashwini** [comment] 2019-10-18 07:13
I could reproduce the issue with changes mentioned in last comment. Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/079ecb24dcfb0130a41c4cc8f7a69aba/untitled209.ipynb). Thanks!

**Comment by mihaimaruseac** [comment] 2019-10-18 17:12
Closing as duplicate of #33204 (although different error, the main concept is that thread dynamic objects cannot be pickled)

**Comment by AlexFuster** [comment] 2019-10-30 18:27
I'm having the same problem

**Comment by gadagashwini** [comment] 2019-10-31 05:40
@AlexFuster,
Please post a new issue and provide all the information asked by the template. We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!

**Comment by AlexFuster** [comment] 2019-10-31 09:56
But my problem is literally the one described in this issue. Why not to reopen it?

**Comment by tseth92** [comment] 2019-10-31 10:26
@gadagashwini I also need to reopen the issue as the issue linked by @mihaimaruseac is different from this one. I have raised concern over this via tensorflow-bot, but no response form tensorflow team i received. Please reopen this issue as there is no reason to create a new issue when one unresolved issue is already present. Thanks

**Comment by gowthamkpr** [comment] 2019-11-16 00:58
@mihaimaruseac Can you PTAL? Thanks!

**Comment by mihaimaruseac** [comment] 2019-11-16 00:59
Afaik pickling dynamic objects is not supported. I am not a good assignee if that changed.

**Comment by gowthamkpr** [comment] 2019-11-21 22:24
@tseth92 @AlexFuster Did the above comment help you in understanding the root of the problem?

**Comment by tseth92** [comment] 2019-11-22 20:24
@gowthamkpr if someone can really confirm that pickling is not supported for dynamic objects, then this should be considered as a feature request as it is an important part of TF.

**Comment by AlexFuster** [comment] 2019-11-25 09:28
Totally agree with @tseth92 , pickling the entire model object is easier than saving just the weights. Especially for complex models with multiple networks involved. It is very convenient as long as it does not introduce performance issues.

**Comment by gowthamkpr** [comment] 2019-11-25 17:56
@tseth92 @AlexFuster I am going to close this issue. Please create a new issue with the feature request template as mentioned [here](https://github.com/tensorflow/tensorflow/issues/new/choose) and we can take it forward from there. Thanks!

**Closed by gowthamkpr** 2019-11-25 17:56 UTC
Labels: TF 2.0, comp:keras, type:bug

**Comment by renatobellotti** [comment] 2019-12-03 16:11
Did somebody make the feature request?

**Comment by AlexFuster** [comment] 2019-12-04 15:42
@renatobellotti  I don't think so

**Comment by AlexFuster** [comment] 2019-12-04 16:45
I'm looking at Tensorflow's code and the problem is produced by the class base_layer.Layer (note that tf.keras.Model inherits from this class)

So the error can be replicated like this
```python
from tensorflow.python.keras.engine import base_layer
import pickle
with open('foo.pkl','wb') as f:
    pickle.dump(base_layer.Layer(),f)
```

**Comment by AlexFuster** [comment] 2019-12-04 18:13
Hey guys, came out with a solution. It's ugly but it seems to work. I hope it helps   
By the way, I'm using dill because pickle does not serialize weakref objects.

```python
import tensorflow as tf
import dill
import threading
def extractfromlocal(model): #extracts attributes from the local thrading container
    model._thread_local=model._thread_local.__dict__
    for attr in model.__dict__.values():
        if '_thread_local' in dir(attr):
            extractfromlocal(attr)

def loadtolocal(model): #puts attributes back to the local threading container
    aux=threading.local()
    aux.__dict__.update(model._thread_local)
    model._thread_local = aux
    for attr in model.__dict__.values():
        if '_thread_local' in dir(attr):
            loadtolocal(attr)
            
def save_tf_model(model): #saves the model
    extractfromlocal(model)
    with open('mymodel.pkl','wb') as f:
        dill.dump(model,f)
    loadtolocal(model)

def load_tf_model(model):#loads the model
    with open('mymodel.pkl','rb') as f:
        model=dill.load(f)
        loadtolocal(model)
    return model

#just a quick example of this working
class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    def call(self, x):
        return self.d(x)

data=tf.random.normal((2, 3))
model = Model()
print('Before saving',model(data))
save_tf_model(model)
print('After saving',model(data))
model=load_tf_model(model)
print('After loading',model(data))
```

**Comment by NEGU93** [comment] 2020-02-19 13:10
> Did somebody make the feature request?

@renatobellotti  I just did [#36897](https://github.com/tensorflow/tensorflow/issues/36897). It is the first time I use GitHub to ask for a feature so I hope it is well written.

**Comment by renatobellotti** [comment] 2020-03-09 10:33
> > Did somebody make the feature request?
> 
> @renatobellotti I just did [#36897](https://github.com/tensorflow/tensorflow/issues/36897). It is the first time I use GitHub to ask for a feature so I hope it is well written.

Thank you! :)

**Comment by kamran-arabesque** [comment] 2020-03-28 20:05
Doesn't fix the issue, but a potential workaround.
Use keras version 2.3.1 and tensorflow 2.X, and use keras rather than tf.keras and the pickling works:
```
!pip install tensorflow
!pip install keras==2.3.1

import numpy as np
import keras
import tensorflow as tf
import pickle

def keras_model():
    model = keras.Sequential()
    model.add(keras.layers.Dense(20, input_shape=(1,), activation='relu'))
    model.add(keras.layers.Dense(1))
    model.compile(loss='mse', optimizer='adam')
    return model

def tf_model():
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(20, input_shape=(1,), activation='relu'))
    model.add(tf.keras.layers.Dense(1))
    model.compile(loss='mse', optimizer='adam')
    return model

def data():
    n_samples = 1000
    mid_range = 10 
    X = np.random.random((n_samples,1))*mid_range-(mid_range/2)
    y = X*X
    return X,y

def train():
    if tf_or_keras == 'tf':
        model = tf_model()
    elif tf_or_keras == 'keras':
        model = keras_model()
    X,y = data()
    h = model.fit(X, y,
               epochs=10,
               verbose=1)
    pickle.dump(model, open(tf_or_keras, 'wb'))

tf_type = tf.__version__
print(tf_type)
keras_type = keras.__version__
print(keras_type)
tf_or_keras = 'keras'
train()
```

**Comment by SuperKam91** [comment] 2020-03-28 20:15
Doesn't fix the issue, but a potential workaround.
Use keras version 2.3.1 and tensorflow 2.X, and use keras rather than tf.keras and the pickling works:

```
!pip install tensorflow
!pip install keras==2.3.1

import numpy as np
import keras
import tensorflow as tf
import pickle

def keras_model():
    model = keras.Sequential()
    model.add(keras.layers.Dense(20, input_shape=(1,), activation='relu'))
    model.add(keras.layers.Dense(1))
    model.compile(loss='mse', optimizer='adam')
    return model

def tf_model():
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(20, input_shape=(1,), activation='relu'))
    model.add(tf.keras.layers.Dense(1))
    model.compile(loss='mse', optimizer='adam')
    return model

def data():
    n_samples = 1000
    mid_range = 10 
    X = np.random.random((n_samples,1))*mid_range-(mid_range/2)
    y = X*X
    return X,y

def train():
    if tf_or_keras == 'tf':
        model = tf_model()
    elif tf_or_keras == 'keras':
        model = keras_model()
    X,y = data()
    h = model.fit(X, y,
               epochs=10,
               verbose=1)
    pickle.dump(model, open(tf_or_keras, 'wb'))

tf_type = tf.__version__
print(tf_type)
keras_type = keras.__version__
print(keras_type)
tf_or_keras = 'keras'
train()
```
