### ISSUE TITLE
[tensorflow.org] Site not working; Potential service worker issue

### ISSUE THREAD

**Issue by EivindArvesen** [tensorflow/tensorflow#26449] opened 2019-03-07 14:42 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:
- Doc Link: https://www.tensorflow.org

**Describe the documentation issue**

None of http://tensorflow.org  is working on Safari (latest macOS) for me; seems related to Service Worker. Works fine on Safari Technology Preview and on @googlechrome.
Might have visited the page during the last 48h (pre-launch).

![skjermbilde 2019-03-06 kl 23 11 45](https://user-images.githubusercontent.com/939844/53964361-81c45580-40ef-11e9-9812-d42291dfb970.png)

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
Yes, if applicable.

**Comment by jvishnuvardhan** [comment] 2019-03-07 15:25
@eivind88 It is working on my Mac without any problem. Could you check it by clearing cache and reload it. Thanks!

**Comment by eivind88** [comment] 2019-03-07 15:47
Emptied cache, and did a hard reload and got the site.

Did another normal reload – same error.

Restarted Safari, and it's the same thing.
Can only seem to get the new site when ignoring cache and reloading using <kbd>alt</kbd>+<kbd>cmd</kbd>+<kbd>R</kbd> (no hero-graphics, though) – every normal reload gives me the same error. Emptying my cache does nothing.

I'm thinking there's been an error with whatever service worker I hit first during the last couple of days, which leads to bad cache-handling in the browser.

**Comment by eivind88** [comment] 2019-03-07 15:50
This seems related: 
https://github.com/angular/angular/issues/26500

**Comment by lamberta** [comment] 2019-03-22 16:56
Thanks. Tested on Safari and this issue seems resolved when the redesign rollout completed.

**Comment by eivind88** [comment] 2019-03-23 00:16
@lamberta @jvishnuvardhan 
Actually, if this is what I suspect it is (bungled service worker at some point) you wouldn't be able to reproduce this issue if you didn't access the site at the same time as I must have originally done (at the time when the service worker was incorrect).

I'm still having the exact same issue.

**Comment by lamberta** [comment] 2019-03-23 00:21
I can file an internal ticket, but will need to be able to reproduce the issue. Is there anything about your setup that needs to be taken into account? (JavaScript blockers, etc.) Thanks

**Comment by lamberta** [comment] 2019-03-28 00:06
Hi @eivind88, I've filed an internal issue.

Can you load the site with the developer console open and let us know if there are any errors in the console? Thank you

**Comment by eivind88** [comment] 2019-03-28 16:11
Hey, @lamberta 

Nothing in the console when loading:

![Skjermbilde 2019-03-28 kl  12 07 19](https://user-images.githubusercontent.com/939844/55173423-113eb080-5152-11e9-948e-efbf3288eaee.png)

When I empty the cache and reload, there's a bunch. All of them include "TypeError: Failed writing data to the file system" or otherwise failing to load resources. This is also similar to the Safari error-screen I see when trying to load the page normally, which is part of why I think it's related to service workers.

![Skjermbilde 2019-03-28 kl  12 09 32](https://user-images.githubusercontent.com/939844/55173604-5f53b400-5152-11e9-856c-02f02f5b2062.png)

Textual representation:

```
[Error] FetchEvent.respondWith received an error: TypeError: Failed writing data to the file system
[Error] Cannot load https://www.tensorflow.org/root_7bf9d7a55c4703d1d1fd5d9b6fca665eea25a03bc986290c9a6352762ed8402a.frame.
[Error] Failed to load resource: FetchEvent.respondWith received an error: TypeError: Failed writing data to the file system (root_7bf9d7a55c4703d1d1fd5d9b6fca665eea25a03bc986290c9a6352762ed8402a.frame, line 0)
[Info] Successfuly preconnected to https://fonts.googleapis.com/
[Info] Successfuly preconnected to https://www.gstatic.com/
[Info] Successfuly preconnected to https://fonts.gstatic.com/
[Error] Failed to load resource: the server responded with a status of 404 () (devsite_app__nb.js, line 0)
[Error] Refused to execute https://www.gstatic.com/devrel-devsite/vc9bb015437ae3e13b823152db938df0b60068cf5df8dd0c787a73605454011ee/tensorflow/js/devsite_app__nb.js as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Cache API operation failed: Failed writing data to the file system
[Error] Unhandled Promise Rejection: TypeError: Failed writing data to the file system
	(anonym funksjon)
	rejectPromise
	promiseReactionJob
[Error] FetchEvent.respondWith received an error: TypeError: Failed writing data to the file system
[Error] Cannot load https://www.tensorflow.org/root_7bf9d7a55c4703d1d1fd5d9b6fca665eea25a03bc986290c9a6352762ed8402a.frame.
[Error] Failed to load resource: FetchEvent.respondWith received an error: TypeError: Failed writing data to the file system (root_7bf9d7a55c4703d1d1fd5d9b6fca665eea25a03bc986290c9a6352762ed8402a.frame, line 0)
[Error] FetchEvent.respondWith received an error: TypeError: Failed writing data to the file system
```

**Comment by lamberta** [comment] 2019-03-28 16:27
Thanks. Tracking in b/129421358

**Comment by samthor** [comment] 2019-03-29 01:56
@eivind88 are you experiencing this problem on all sites with Service Workers?

e.g. airhorner.com, chromestatus.com

There's very little control about where we store things—SW just lets us put data into `Cache`.

**Comment by eivind88** [comment] 2019-04-02 18:52
@samthor no problem anywhere else.

**Comment by lamberta** [comment] 2019-07-12 16:36
Still tracking this webserver bug internally but closing this since it's not a TensorFlow issue. Thanks

**Closed by lamberta** 2019-07-12 16:36 UTC
Labels: 2.0, type:docs
