### ISSUE TITLE
issue while installing tensorflow 

### ISSUE THREAD

**Issue by swaritras** [tensorflow/tensorflow#13290] opened 2017-09-25 10:15 UTC
sws@sws-Aspire-5830T:~$ source activate tensorflow
(tensorflow) sws@sws-Aspire-5830T:~$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
(tensorflow) sws@sws-Aspire-5830T:~$ (tensorflow)$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
bash: syntax error near unexpected token `$'
(tensorflow) sws@sws-Aspire-5830T:~$ (tensorflow)$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
bash: syntax error near unexpected token `$'
(tensorflow) sws@sws-Aspire-5830T:~$ (tensorflow)$ pip3 install --ignore-installed --upgrade TF_BINARY_URL
bash: syntax error near unexpected token `$'
(tensorflow) sws@sws-Aspire-5830T:~$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow==0.12.1 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl (43.1MB)
    100% |████████████████████████████████| 43.1MB 22kB/s 
Collecting protobuf>=3.1.0 (from tensorflow==0.12.1)
  Downloading protobuf-3.4.0-cp35-cp35m-manylinux1_x86_64.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 124kB/s 
Collecting wheel>=0.26 (from tensorflow==0.12.1)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 3.6MB/s 
Collecting numpy>=1.11.0 (from tensorflow==0.12.1)
  Downloading numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 62kB/s 
Collecting six>=1.10.0 (from tensorflow==0.12.1)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.1.0->tensorflow==0.12.1)
  Downloading setuptools-36.5.0-py2.py3-none-any.whl (478kB)
    100% |████████████████████████████████| 481kB 202kB/s 
Installing collected packages: six, setuptools, protobuf, wheel, numpy, tensorflow
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/six.py'
(tensorflow) sws@sws-Aspire-5830T:~$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow==0.12.1 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
Collecting six>=1.10.0 (from tensorflow==0.12.1)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow==0.12.1)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow==0.12.1)
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting protobuf>=3.1.0 (from tensorflow==0.12.1)
  Using cached protobuf-3.4.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting setuptools (from protobuf>=3.1.0->tensorflow==0.12.1)
  Using cached setuptools-36.5.0-py2.py3-none-any.whl
Installing collected packages: six, wheel, numpy, setuptools, protobuf, tensorflow
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted

**Comment by fakabbir** [comment] 2017-09-25 14:02
I believe the problem is with the USER PERMISSSIONS. Try : 
`sudo pip3 install --ignore-installed --upgrade $TF_BINARY_URL`

**Comment by aselle** [comment] 2017-09-25 21:15
Does this solver your problem @swaritras?

**Comment by gunan** [comment] 2017-10-15 05:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gunan** 2017-10-15 05:43 UTC
Labels: stat:awaiting response, type:build/install
