### ISSUE TITLE
Basic Usage - Variables: incorrect variable name

### ISSUE THREAD

**Issue by ovpiNU** [tensorflow/tensorflow#239] opened 2015-11-16 07:23 UTC
The state variable is named 'var', but it is referred as 'state' afterwards.
Changing this:
new_value = tf.add(**state**, one)
update = tf.assign(**state**, new_value)
To this:
new_value = tf.add(**var**, one)
update = tf.assign(**var**, new_value)
Solves the problem.

**Comment by girving** [comment] 2015-11-16 15:47
Duplicate of https://github.com/tensorflow/tensorflow/issues/236, which is itself a duplicate of an earlier bug.

**Closed by girving** 2015-11-16 15:47 UTC
Labels: duplicate
