### ISSUE TITLE
python: ../nptl/pthread_mutex_lock.c:349: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != EDEADLK || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)' failed.

### ISSUE THREAD

**Issue by pedropgusmao** [tensorflow/tensorflow#8466] opened 2017-03-16 12:16 UTC
Tensorflow is crashing when run using multiple GPUs (2,3,and 4) on cifar10_multi_gpu .py example in a Power8 computer.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
We have found some suggestions regarding updating glibc (https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1642390?cm_mc_uid=49967414488814888059863&cm_mc_sid_50200000=1489663906), but our system is already updated to the latest version and the problem remains.
We have also used ppc64_pc to reduce SMT (to 2)  and also turned off. Still the problem remains. 

### Environment info
_Operating System:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
Linux minsky31 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 17:05:51 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux_

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
_CUDA
-rw-r--r-- 1 root root 559800 gen 27 00:10 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 gen 27 00:13 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root     19 gen 27 00:13 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
-rw-r--r-- 1 root root 476024 gen 27 00:10 /usr/local/cuda/lib64/libcudart.so.8.0.61
-rw-r--r-- 1 root root 966166 gen 27 00:10 /usr/local/cuda/lib64/libcudart_static.a
cuDNN
/usr/lib/powerpc64le-linux-gnu/libcudnn_static.a
/usr/lib/powerpc64le-linux-gnu/libcudnn.so.5.1.10
/usr/lib/powerpc64le-linux-gnu/libcudnn.so
/usr/lib/powerpc64le-linux-gnu/libcudnn_static_v5.a
/usr/lib/powerpc64le-linux-gnu/libcudnn.so.5_

If installed from source, provide 
_1. The commit hash (`git rev-parse HEAD`):
012f9c10dcc27a838ed4b170b9036483bc2c5869_

2. The output of `bazel version`:
_Build label: 0.4.3-2017-01-24 (@6fc5c53)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 24 20:34:16 2017 (1485290056)
Build timestamp: 1485290056
Build timestamp as int: 1485290056_

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
_We downloaded the files from https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10
and tried to run the cifar10_multi_gpu example using four P100 gpus._ 

### What other attempted solutions have you tried?
We tried removing the calls from measuring time, logging etc, but the problem remains. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

_When it blocks, it simply hangs 
2017-03-16 12:09:56.391752: step 800, loss = 3.33 (2982.8 examples/sec; 0.011 sec/batch)
2017-03-16 12:09:57.002419: step 810, loss = 3.49 (3998.9 examples/sec; 0.008 sec/batch)
2017-03-16 12:09:57.476172: step 820, loss = 3.24 (3003.8 examples/sec; 0.011 sec/batch)
and the result from strace when it blocks:
strace: Process 111228 attached
futex(0x3fffd5d49744, FUTEX_WAIT_PRIVATE, 1, NULL_

Otherwise, when it gives the error : 
futex(0x10013f8cf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x10013f8cf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x10013f8cf10, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x10013f8cf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x10013f8cf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x10013f8cf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x10013f8cf10, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3fffd1afc324, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3fffd1afc2f8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3fffd1afc324, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
+++ killed by SIGABRT (core dumped) +++

strace gives as last lines:
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3bff90000020, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x3ffff8dbd158, FUTEX_WAKE_PRIVATE, 1) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2692, ...}) = 0
write(1, "2017-03-16 12:22:38.084717: step"..., 90) = 90
futex(0x1001efacf10, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x1001efacf10, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x3ffff8dbd184, FUTEX_WAIT_PRIVATE, 1, NULL

**Comment by pedropgusmao** [comment] 2017-03-16 13:15
Also, increasing the batch_size for a single GPU (from 128 to 512) gives the same error, i.e. the process starts but then after a few iterations it halts again. 
_2017-03-16 13:56:24.380589: step 390, loss = 3.90 (918.7 examples/sec; 0.557 sec/batch)
2017-03-16 13:56:30.259091: step 400, loss = 3.89 (831.1 examples/sec; 0.616 sec/batch)
2017-03-16 13:56:36.581468: step 410, loss = 3.87 (909.2 examples/sec; 0.563 sec/batch)
python: ../nptl/pthread_mutex_lock.c:349: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != EDEADLK || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)' failed.
Aborted (core dumped)_

**Comment by abdasgupta** [comment] 2017-03-18 05:37
Exactly same issue I am getting.

**Comment by antoajayraj** [comment] 2017-03-21 14:46
I am using Power8 box.. and dont see this issue. 
python ./cifar10_multi_gpu_train.py --data_dir=/mldl/NVME/scratch/inception_output_data/ --train_dir=/tmp/ --num_gpus 4 --batch_size 512 --max_steps 200

I tried it with TensorFlow 1.0.1 and using libc6_2.23-0ubuntu5_ppc64el.deb 
Kernel : 4.4.0-59-generic

**Comment by skye** [comment] 2017-03-21 20:36
@pedropgusmao would it be possible to try version 1.0.1? That will help narrow down the problem.

Similarly, @abdasgupta which TensorFlow version are you running?

**Comment by abdasgupta** [comment] 2017-03-23 12:07
Hi @skye  and  @antoajayraj ,

First let me describe my setup - I am running tensorflow training on inception v3 model to fine tune for Flowers data set(see https://github.com/tensorflow/models/tree/master/inception), through docker in a small kubernetes cluster made of power 8 machines. I have 4GPUs at my disposal.
My container and host OS are Ubuntu 16.04.
Host kernel is : 4.4.0-64-generic
GLibc version: Ubuntu GLIBC 2.23-0ubuntu7

I was hitting the above mentioned issue with tensorflow version 1.0.0 only when I ran 1000 iterations of training or above. The above error was appearing approx after 600-900 iterations.

After I upgraded to version 1.0.1, I am seeing no such error within 10000 iterations.
But if I run 100000 iterations, the training is getting stuck at around 50k and stack trace is showing that it is executing some waitpid(-1..) and stuck there. 

Command to run the training in docker container:
`docker run -it --privileged -v /usr/local/cuda-8.0/:/usr/local/cuda-8.0/ -v /usr/lib/powerpc64le-linux-gnu/:/usr/lib/powerpc64le-linux-gnu/ -v /usr/lib/nvidia-375/:/usr/lib/nvidia-375/  tf-inception-trainer-flowers-v101 /bin/bash -c "./run-trainer.sh 100000"`

Image name : tf-inception-trainer-flowers-v101 
This is the same image I am using for Kubernetes. This is a locally built image with tensorflow 1.0.1 installed.

Content of run-trainer.sh:
```bash
#!/bin/bash

if [ $1 ];  then
  ITERATIONS=$1
else
  echo $0": usage: ./run-traner.sh [iterations]"
  exit 1
fi

curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz && \
tar xzf inception-v3-2016-03-01.tar.gz && \
ls inception-v3

mkdir /flowers-data

cd /models/inception && \
export LD_LIBRARY_PATH=/usr/lib/powerpc64le-linux-gnu/ && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64/ && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-375/ && \
bazel build inception/download_and_preprocess_flowers && \
bazel-bin/inception/download_and_preprocess_flowers /flowers-data && \

# Build the model. Note that we need to make sure the TensorFlow is ready to
# use before this as this command will not build TensorFlow.
bazel build inception/flowers_train

# Path to the downloaded Inception-v3 model.
MODEL_PATH="/inception-v3/model.ckpt-157585"

# Directory where the flowers data resides.
FLOWERS_DATA_DIR=/flowers-data/

# Directory where to save the checkpoint and events files.
TRAIN_DIR=/flowers_train/

# Run the fine-tuning on the flowers data set starting from the pre-trained
# Imagenet-v3 model.
bazel-bin/inception/flowers_train \
  --train_dir="${TRAIN_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --pretrained_model_checkpoint_path="${MODEL_PATH}" \
  --fine_tune=True \
  --initial_learning_rate=0.001 \
  --max_steps="${ITERATIONS}" \
  --input_queue_memory_factor=1
```
Is the behaviour expected? Am I doing something wrong? Please, guide me. Though my current purpose is served as I can run the training now till 5000 iterations through docker. It gives me about 99.8% of accuracy. And accuracy is same while the iterations go up to 50k. But the accuracy is hurt while I lower the iterations to , say 2000 (Only 93.4%)

I will update my findings after I run the training on P8 bare-metal till 100000 iterations.

Thank you.

**Comment by skye** [comment] 2017-03-23 14:45
So it sounds like the crash was resolved in 1.0.1. That's good. @pedropgusmao please let us know if you still see this after upgrading to 1.0.1.

@abdasgupta you mention a stacktrace with waitpid(-1), could you post the full stacktrace? Also how are you collecting it?

**Comment by pedropgusmao** [comment] 2017-03-27 18:47
Hi everyone. I was also using a Power8 with IBM's packages (https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?htmlfid=POO03514WWEN&) which included Tensorflow 1.0.0 . I solved the problem by using CUDA8 for Power8, which is NOT(!!!!) the same for the general pc64_el architecture. You must use the cuda-repo-ubuntu1604-8-0-local-ga2_8.0.54-1_ppc64el-deb from https://developer.nvidia.com/cuda-downloads-power8 .

**Comment by abdasgupta** [comment] 2017-03-27 19:06
@skye  I ran the tensorflow training on bare-metal. The error is sporadic; though after using Tensorflow 1.0.1, the error is seldom coming within 50000 iterations.  I am collecting stacktrace with "strace -p <pid>" and during the error , it only shows waitpid(-1), nothing more.
@pedropgusmao Yes, I am using CUDA8 from cuda-repo-ubuntu1604-8-0-local-ga2_8.0.54-1_ppc64el-deb from https://developer.nvidia.com/cuda-downloads-power8 .

**Comment by pedropgusmao** [comment] 2017-03-27 20:14
@abdasgupta , I am also using  Nvidia  Driver Version: 361.10. From line `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-375/ && \` and `docker run` it seems that you are using the new 375 driver. Could you try and downgrade to 361.10?

**Comment by bcbrock** [comment] 2017-05-13 00:13
I've also experienced this error using TensorFlow on POWER8, and have now also
just hit it on a source installation of caffe2 on POWER8. So this may not be
an issue with TensorFlow. My environment:

System:        Power8 Minsky, 4xP100
OS:            Ubuntu 16.04.2
CUDA:          cuda-repo-ubuntu1604-8-0-local-ga2v2_8.0.61-1_ppc64el.deb
cuDNN:         5.1.10
Python:        2.7
NVIDIA Driver: 375.51

I'm curious, what kinds of GPUs is everyone running? @pedrogusmao and I are on
P100 and having this issue. How about @abdasgupta and @antoajayraj?

**Comment by dahlem** [comment] 2017-05-29 16:17
@bcbrock I have the same issue on a Minsky machine:

System: Power8 Minsky, 4xP100
OS: Ubuntu 16.04.2
CUDA: 8.0.61
cuDNN: 5.1.10/6.0.20
Python: 2.7.12
NVIDIA Driver: 375.51
TensorFlow: 1.0.1

Any more ideas on this issue?

**Comment by antoajayraj** [comment] 2017-05-29 16:32
@dahlem What is the command or recreate steps ? and is it consistent ?

**Comment by dahlem** [comment] 2017-05-30 09:51
@antoajayraj I'm using Mozilla's deepspeech [1] to build a speech transcription model using the LibriSpeech dataset. It does not happen consistently.

[1] https://github.com/mozilla/DeepSpeech

**Comment by hartb** [comment] 2017-05-30 21:39
I'm able to reproduce this on a POWER system with:

- TensorFlow        1.1.0
- Ubuntu            16.04.2 (kernel 4.4.0-77-generic)
- libc6:ppc64el     2.23-0ubuntu7
- cuda-cudart-8-0   8.0.61-1
- GPU driver        375.51

In a crash I caught, it looks like there are 2 mutexes and 2 or 3 threads involved.

First mutex is wanted by thread 1 (110471 / 0x1af87), and seems to be owned by thead 17 (110465 / 0x1af81). Thread 1 detects a deadlock while trying to acquire and asserts.

(In the core file, this mutex appears locked by thread 113 (110449 / 0x1af71) which conflicts with the ownership recorded in the mutex. But it also appears to be marked as if the owner has died, so maybe thread 113 had been waiting and made a bit of progress after thread 1 hit the assert().)

    (gdb) x/20x 0x100056c7e40
    0x100056c7e40:  0xc001af71      0x00000001      0x0001af81      0x00000001
                    __lock          __count         __owner         __nusers
    0x100056c7e50:  0x00000021      0x00000000      0x00000000      0x00000000
                    __kind

Second mutex is wanted by thead 17 (110465 / 0x1af81) and is locked by thread 1 (110471 / 0x1af87).

    (gdb) x/8x 0x3fff57d39e78
    0x3fff57d39e78: 0x8001af87      0x00000001      0x00000000      0x00000000
                    __lock          __count         __owner         __nusers
    0x3fff57d39e88: 0x00000021      0x00000000      0x00000000      0x00000000
                    __kind

All three of the involved threads had come through cudaLaunch() and are somewhere in libcuda:

    Thread 1 (Thread 0x3bffad57f1a0 (LWP 110471)):
    #0  0x00003fffa027edb0 in __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00003fffa0281270 in __GI_abort () at abort.c:89
    #2  0x00003fffa0274290 in __assert_fail_base (fmt=<optimized out>,
        assertion=0x3fffa04296e8 "INTERNAL_SYSCALL_ERRNO (e, __err) != EDEADLK || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)",
        file=0x3fffa04296c8 "../nptl/pthread_mutex_lock.c", line=<optimized out>, function=<optimized out>) at assert.c:92
    #3  0x00003fffa0274384 in __GI___assert_fail (
        assertion=0x3fffa04296e8 "INTERNAL_SYSCALL_ERRNO (e, __err) != EDEADLK || (kind != PTHREAD_MUTEX_ERRORCHECK_NP && kind != PTHREAD_MUTEX_RECURSIVE_NP)",
        file=0x3fffa04296c8 "../nptl/pthread_mutex_lock.c", line=<optimized out>, function=0x3fffa0429830 <__PRETTY_FUNCTION__.9294> "__pthread_mutex_lock_full") at assert.c:101
    #4  0x00003fffa041b400 in __pthread_mutex_lock_full (mutex=0x100056c7e40) at ../nptl/pthread_mutex_lock.c:347
    #5  0x00003fff8b94e268 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #6  0x00003fff8b9202d8 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #7  0x00003fff8b806ef4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #8  0x00003fff8b9a46f8 in cuLaunchKernel () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #9  0x00003fff7596f0b8 in ?? () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #10 0x00003fff759bda88 in cudaLaunch () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #11 0x00003fff909d4678 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #12 0x00003fff909e95e0 in tensorflow::functor::CastFunctor<Eigen::GpuDevice, float, unsigned char>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16,
     Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<unsigned char const, 1, 1, long>, 16, Eigen::MakePointer>) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #13 0x00003fff909d0c6c in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #14 0x00003fff9096c03c in tensorflow::CastOpBase::Compute(tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #15 0x00003fff91a8332c in tensorflow::BaseGPUDevice::ComputeHelper(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #16 0x00003fff91a83778 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #17 0x00003fff91ac6e20 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #18 0x00003fff91ee0d30 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #19 0x00003fff91ee1688 in std::_Function_handler<void (), Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::NonBlockingThreadPoolTempl(int, bool, tensorflow::thread::E
    igenEnvironment)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #20 0x00003fff91eddf74 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #21 0x00003fff91f12f90 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #22 0x00003fff758049a4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
    #23 0x00003fffa0418070 in start_thread (arg=0x3bffad57f1a0) at pthread_create.c:335
    #24 0x00003fffa0363230 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:96


    Thread 17 (Thread 0x3bffb057f1a0 (LWP 110465)):
    #0  0x00003fffa041adc4 in __pthread_mutex_lock_full (mutex=0x3fff57d39e78) at ../nptl/pthread_mutex_lock.c:339
    #1  0x00003fff8b94e268 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #2  0x00003fff8b9202d8 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #3  0x00003fff8b929e28 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #4  0x00003fff8b8f95ac in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #5  0x00003fff8b90cab0 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #6  0x00003fff8ba9a454 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #7  0x00003fff8b806cec in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #8  0x00003fff8b806f38 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #9  0x00003fff8b9a46f8 in cuLaunchKernel () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #10 0x00003fff7596f0b8 in ?? () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #11 0x00003fff759bda88 in cudaLaunch () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #12 0x00003fff90bc9e08 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #13 0x00003fff90be4a50 in void tensorflow::functor::ReduceFunctor<Eigen::GpuDevice, Eigen::internal::ProdReducer<int> >::Reduce<Eigen::TensorMap<Eigen::Tensor<int, 0, 1, long>, 16, Eigen::Ma
    kePointer>, Eigen::TensorMap<Eigen::Tensor<int const, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::array<long, 1ul> >(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 0, 1, long>
    , 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<int const, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::array<long, 1ul> const&, Eigen::internal::ProdReducer<int> const&) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #14 0x00003fff90b919c4 in tensorflow::ReductionOp<Eigen::GpuDevice, int, Eigen::internal::ProdReducer<int> >::Compute(tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #15 0x00003fff91a8332c in tensorflow::BaseGPUDevice::ComputeHelper(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #16 0x00003fff91a83778 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #17 0x00003fff91ac6e20 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #18 0x00003fff91ee0d30 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #19 0x00003fff91ee1688 in std::_Function_handler<void (), Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::NonBlockingThreadPoolTempl(int, bool, tensorflow::thread::E
    igenEnvironment)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #20 0x00003fff91eddf74 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #21 0x00003fff91f12f90 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #22 0x00003fff758049a4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
    #23 0x00003fffa0418070 in start_thread (arg=0x3bffb057f1a0) at pthread_create.c:335
    #24 0x00003fffa0363230 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:96


    Thread 113 (Thread 0x3bffb857f1a0 (LWP 110449)):
    #0  0x00003fffa041adc4 in __pthread_mutex_lock_full (mutex=0x100056c7e40) at ../nptl/pthread_mutex_lock.c:339
    #1  0x00003fff8b94e268 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #2  0x00003fff8b9202d8 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #3  0x00003fff8b806ef4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #4  0x00003fff8b9a46f8 in cuLaunchKernel () from /usr/lib/powerpc64le-linux-gnu/libcuda.so.1
    #5  0x00003fff7596f0b8 in ?? () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #6  0x00003fff759bda88 in cudaLaunch () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
    #7  0x00003fff909d3238 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #8  0x00003fff909e38e0 in tensorflow::functor::CastFunctor<Eigen::GpuDevice, int, unsigned char>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 1, 1, long>, 16, Eig
    en::MakePointer>, Eigen::TensorMap<Eigen::Tensor<unsigned char const, 1, 1, long>, 16, Eigen::MakePointer>) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #9  0x00003fff909d099c in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #10 0x00003fff9096c03c in tensorflow::CastOpBase::Compute(tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #11 0x00003fff91a8332c in tensorflow::BaseGPUDevice::ComputeHelper(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #12 0x00003fff91a83778 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #13 0x00003fff91ac6e20 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #14 0x00003fff91ee0d30 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #15 0x00003fff91ee1688 in std::_Function_handler<void (), Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::NonBlockingThreadPoolTempl(int, bool, tensorflow::thread::E
    igenEnvironment)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #16 0x00003fff91eddf74 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
       from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #17 0x00003fff91f12f90 in ?? () from /opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
    #18 0x00003fff758049a4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
    ---Type <return> to continue, or q <return> to quit---
    #19 0x00003fffa0418070 in start_thread (arg=0x3bffb857f1a0) at pthread_create.c:335
    #20 0x00003fffa0363230 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:96

**Comment by hartb** [comment] 2017-05-30 22:47
Confirmed that I also see this with NVIDIA driver 375.66.  I've asked NVIDIA to take a look as well.

**Comment by hartb** [comment] 2017-05-31 16:41
The results of my testing so far as as follows. All tests with Ubuntu 16.04.2 (kernel 4.4.0-72 or -78) and CUDA 8.0.61:

    TF      Driver    cuDNN     Comment
    1.0.1   361.119   5.0.10    OK
    1.0.1   375.51    5.1.10    Hang/Assert
    1.0.1   375.51    6.0.20    Hang/Assert
    1.1.0   361.119   5.0.10    OK
    1.1.0   375.51    6.0.20    Assert
    1.1.0   375.66    6.0.20    Assert/Hang

The problem seems not to occur with the 361 series driver, but does with the 375 series driver.

Generally, I see much higher throughput (images / sec) with TF 1.1.0 and with the system more aggressively tuned (with adjustments to performance governor, SMT mode, and GPU clock settings).

- In the lower-throughput configs the symptom is more likely a process hang.
- In the higher-throughput configs the symptom is more likely the assert.

Will share these results with NVIDIA.

For now, I'd suggest using the 361-series driver, and would be interested in any reports of hangs or asserts with that driver.

**Comment by eric-aquaronne** [comment] 2017-06-07 14:23
Just got recheck from our IBM PowerAI experts: this is a known bug in the current Nvidia 375 GPU driver: back-leveling the driver to the 361 level will fix the issue.

**Closed** 2017-09-08 04:55 UTC
Labels: stat:awaiting response, type:support
