### ISSUE TITLE
AttributeError: module 'gast' has no attribute 'Num'

### ISSUE THREAD

**Issue by LMXKO** [tensorflow/tensorflow#33159] opened 2019-10-09 01:51 UTC
System Information：
    python == 3.5.4
    tensorflow == 2.0.0-beta0

Description：
When I running the seq2seq with attention ,it report an warning
WARNING:tensorflow:Entity <function train_step at 0x000000002BF42510> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function train_step at 0x000000002BF42510>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Encoder.call of <__main__.Encoder object at 0x00000000307476A0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Encoder.call of <__main__.Encoder object at 0x00000000307476A0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x00000000143B1400> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x00000000143B1400>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x00000000143B16A8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x00000000143B16A8>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Decoder.call of <__main__.Decoder object at 0x00000000307AE160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Decoder.call of <__main__.Decoder object at 0x00000000307AE160>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Attention.call of <__main__.Attention object at 0x00000000307AA358>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Attention.call of <__main__.Attention object at 0x00000000307AA358>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by ziyigogogo** [comment] 2019-10-09 05:28
pip install gast==0.2.2

**Comment by mihaimaruseac** [comment] 2019-10-09 16:20
Please upgrade pip and then you should be able to install tensorflow 2.0 which already has the issue fixed.

Or, manually install gast 0.2.2

Closing as duplicate of #32319

**Closed by mihaimaruseac** 2019-10-09 16:20 UTC
