### ISSUE TITLE
tensorflow protobuf problem about:A protocolmessage was rejected because it was too big (more than 67108864 bytes) 

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#3931] opened 2016-08-19 19:14 UTC
I got this problem when trying to run a chief worker of distribute tensorflow. The tensorflow was installed by pip,not from source. Then I uninstalled protobuf by pip and then download the source and changed 256 << 20 in coded_stream.h .
And I installed protobuf as Readme said.But the same problem occurred, It seems that tensorflow did not use the new compiled libprotobuf.  How could I fixed this issue? If I have to reinstall tensorflow? Or someone can give me a updated protobuf that can fix the 64m limit? Thanks If someone could help me, I am going to mad about this issue(T_T)

**Comment by prb12** [comment] 2016-08-22 21:40
Duplicate of #3938   

Please see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues

**Closed by prb12** 2016-08-22 21:40 UTC
