### ISSUE TITLE
Error in bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h

### ISSUE THREAD

**Issue by Stepiii** [tensorflow/tensorflow#26679] opened 2019-03-13 17:27 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: checkout from `master` branch
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?: conda 4.6.8
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): cl.exe C/C++ Optimizing Compiler Version 19.16.27027.1 for x64, Visual Studio Build Tools 2017
- CUDA/cuDNN version: CUDA Toolkit V10.0.130, cuDNN 7.5.0
- GPU model and memory: GTX 1060 6GB

**Describe the problem**

Compile error.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
(neural) Stepii@STEPII D:\Neural
$ git clone https://github.com/tensorflow/tensorflow.git
Cloning into 'tensorflow'...
remote: Enumerating objects: 7251, done.
remote: Counting objects: 100% (7251/7251), done.
remote: Compressing objects: 100% (2280/2280), done.
remote: Total 557207 (delta 4925), reused 7233 (delta 4916), pack-reused 549956
Receiving objects: 100% (557207/557207), 330.05 MiB | 378.00 KiB/s, done.
Resolving deltas: 100% (448922/448922), done.
Checking out files: 100% (16777/16777), done.

(neural) Stepii@STEPII D:\Neural
$ cd tensorflow

(neural) Stepii@STEPII D:\Neural\tensorflow
$ python configure.py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 1f6b8c12-47e3-4c5e-80f4-5d3d74fb17b1
You have bazel 0.22.0- (@non-git) installed.
Please specify the location of python. [Default is D:\Programs\Anaconda3\envs\neural\python.exe]:


Found possible Python library paths:
  D:\Programs\Anaconda3\envs\neural\lib\site-packages
Please input the desired Python library path to use.  Default is [D:\Programs\Anaconda3\envs\neural\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]:


Please specify the location where CUDA 10.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0]:


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 6.1


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apache Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(neural) Stepii@STEPII D:\Neural\tensorflow
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

[...]

ERROR: D:/neural/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:572:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:runtime_fft' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/stepii/_bazel_stepii/5mniti2w/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/Programs/Anaconda3/envs/neural/python.exe
    SET PYTHON_LIB_PATH=D:/Programs/Anaconda3/envs/neural/lib/site-packages
    SET TEMP=C:\Users\Stepii\AppData\Local\Temp
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\Stepii\AppData\Local\Temp
  D:/Programs/Anaconda3/envs/neural/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /showIncludes /MD /O2 /DNDEBUG -w -DWIN32_LEAN_AND_MEAN /arch:AVX2 -DEIGEN_AVOID_STL_ARRAY /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/runtime_fft/runtime_fft.o /c tensorflow/compiler/xla/service/cpu/runtime_fft.cc
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(290): error C2059: syntax error: 'constant'
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(290): error C3805: 'constant': unexpected token, expected either '}' or a ','
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1458.697s, Critical Path: 391.20s
INFO: 3277 processes: 3277 local.
FAILED: Build did NOT complete successfully
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Full log [here](https://github.com/tensorflow/tensorflow/files/3044240/FullLog.txt)

**Comment by jvishnuvardhan** [comment] 2019-03-14 21:22
@ZunDubCore Did you install python through Anaconda? Did you check whether the CUDA and cuDNN are referenced correctly. Could you check the [instructions](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) to verify whether the CUDA paths are referenced correctly. Thanks!

**Comment by ZunDubCore** [comment] 2019-03-16 15:18
@jvishnuvardhan Python installed through Anaconda
```
(tf_gpu) D:\Neural\tensorflow>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Double checked, all CUDA paths are referenced correctly and are in the PATH environment variable.

**Comment by ZunDubCore** [comment] 2019-03-16 16:30
Similar issue #25773

**Comment by ZunDubCore** [comment] 2019-03-20 20:20
Not getting this error anymore. Instead see #26958. Closing the issue

**Comment by Opbrave** [comment] 2019-03-24 02:26
> Similar issue #25773

Hi ZunDubCore, How did you pass the issue you mentioned?

**Comment by ZunDubCore** [comment] 2019-03-24 11:09
@Opbrave Actually, I don't know what I've done. The error just disappeared by itself. But instead, a different error appeared.

**Comment by ZunDubCore** [comment] 2019-03-24 12:06
Okey, the error returned.

**Comment by ZunDubCore** [comment] 2019-03-28 19:10
@jvishnuvardhan anything I can do to fix this?

**Comment by jvishnuvardhan** [comment] 2019-04-02 22:43
@Stepiii Sorry for the delay in my response.
Could you check with latest TF1.13.1 and please let us know whether the bug persists? Thanks!

**Comment by Stepiii** [comment] 2019-04-03 05:43
@jvishnuvardhan which branch do I have to checkout? There's no r.1.13.1.

**Comment by jvishnuvardhan** [comment] 2019-04-03 11:56
@Stepiii https://pypi.org/project/tensorflow/ Thanks!

**Comment by Stepiii** [comment] 2019-04-03 12:49
@jvishnuvardhan That site has no downloads for source code, only .whl's. I want to compile tensorflow from sources.

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:08
@Stepiii Current master is [TF1.13.1](https://github.com/tensorflow/tensorflow). Thanks!

**Comment by Stepiii** [comment] 2019-04-03 21:35
@jvishnuvardhan So I need to checkout the `master` branch (not `r1.13`) and compile tensorflow from there?

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:43
@Stepiii Correct. Thanks!

**Comment by Stepiii** [comment] 2019-04-04 15:32
@jvishnuvardhan Thanks! I have updated the post with the new logs. Now I have tried to build from master branch, but similar error appeared.

**Comment by jlebar** [comment] 2019-04-09 05:59
Hi @Stepiii, sorry for the delay getting back to you, I was OOO when this bug was assigned to me.

```
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(290): error C2059: syntax error: 'constant'
bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h(290): error C3805: 'constant': unexpected token, expected either '}' or a ','
```

This is failing when building a protocol buffer, which is generated code.  IOW the problem here is either with protobuf, or with nvcc/msvc.  In fact I'd say that if you answered "n" to "use XLA?" there's a good chance you'd get a build error in one of TensorFlow's protocol buffer files.  (If you don't, that would also be kind of interesting...)

I don't have a Windows machine to debug this on.  If you're willing to attach the contents of `bazel-out/x64_windows-opt/genfiles\tensorflow/compiler/xla/xla_data.pb.h` I might be able to help some, but no promises.  The Windows build is kind of unloved, as I guess you're discovering, so even if we fix this one problem, how long will it stay green?  I have no good answers for you, I'm afraid.  :-/

**Comment by alexrobomind** [comment] 2019-04-09 06:34
Dear @jlebar, I assume the root cause here is the same one as in the equivalent issue for TF2.0 #25773, which is not an inherent problem of protobuf but a name clash of a message field name with a windows header macro (see my comment on the referenced issue), leading to a weird error in the generated header as the compiler sees a "2 = 14" entry.

**Comment by jlebar** [comment] 2019-04-09 06:40
Ah, wonderful, thank you!

Let's dupe this to #25773.

**Closed by jlebar** 2019-04-09 06:40 UTC
Labels: comp:xla, stat:awaiting tensorflower, subtype:windows, type:build/install
