### ISSUE TITLE
saver.restore(sess,modelpath) is able to normal run in tensorflow1.0.1,but have a problem in tensorflow 1.2.1

### ISSUE THREAD

**Issue by luckynote** [tensorflow/tensorflow#12289] opened 2017-08-15 08:33 UTC
### System information
- **OS Platform and Distribution**:Ubuntu 14.04
- **TensorFlow installed from**binary
- **TensorFlow version**:Tensorflow1.0.1 and Tensorflow1.2.1
- **Python version**: Python 2.6
- **GPU model and memory**:1080 Ti

### Describe the problem
I meet this problem at following. My predict.py is able to normal run in Tensorflow 1.0.1, but have shown this proble in Tensorflow 1.2.1. I don't resovle this problem. I need help. Please!

### Source code / logs
Source code：
restore_dict = {}
    for i in variables[:]:  # the first is global step
        restore_dict[i.name.replace(':0', '')] = i
        print('restore variable: ', i.name.replace(':0', ''))
saver = tf.train.Saver(restore_dict) 
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
saver.restore(sess, 'news_tf_model/model.ckpt') #the path is real
predict = sess.run(pred, feed_dict={x: imgs})
sess.close()

logs：
2017-08-15 16:10:46.657837: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
2017-08-15 16:10:46.658229: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.658870: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.659232: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/bias not found in checkpoint
2017-08-15 16:10:46.660554: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.684510: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.742777: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.742852: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.743000: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.743241: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.825494: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.826179: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.826199: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.826309: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.826419: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.826988: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.833507: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
2017-08-15 16:10:46.843310: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    result_dict = news_demo.newsAggreg({image_path})
  File "/home/rszj/liutao/news_aggreg/news_demo.py", line 32, in newsAggreg
    predict = news_predict.run(images_path)
  File "/home/rszj/liutao/news_aggreg/news_predict.py", line 196, in run
    saver.restore(sess, module_file)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_112_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_1', defined at:
  File "demo.py", line 25, in <module>
    result_dict = news_demo.newsAggreg({image_path})
  File "/home/rszj/liutao/news_aggreg/news_demo.py", line 32, in newsAggreg
    predict = news_predict.run(images_path)
  File "/home/rszj/liutao/news_aggreg/news_predict.py", line 176, in run
    saver = tf.train.Saver(restore_dict)  # when you want to save model
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/rszj/liutao/virtualenv/liutao_py2/mpy2tf1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key LSTM/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_112_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by luckynote** [comment] 2017-08-15 09:58
By print variables, I find following.
1.0.1 | 1.2.1
-- | --
LSTM/basic_lstm_cell/weights | LSTM/basic_lstm_cell/kernel
LSTM/basic_lstm_cell/biases | LSTM/basic_lstm_cell/bias

tf1.0.1 LSTM is different to tf1.2.1 LSTM, but I don't know how to continue doing.

**Comment by luckynote** [comment] 2017-08-15 09:59
By print variables, I find following.

1.0.1 | 1.2.1
-- | --
LSTM/basic_lstm_cell/weights | LSTM/basic_lstm_cell/kernel
LSTM/basic_lstm_cell/biases | LSTM/basic_lstm_cell/bias

tf1.0.1 LSTM is different to tf1.2.1 LSTM, but I don't know how to continue doing.

**Comment by skye** [comment] 2017-08-16 20:51
@concretevitamin do you know about any changes to Saver between 1.0 and 1.2?

@luckynote are you loading a checkpoint created in TF 1.0 with TF 1.2?

**Comment by luckynote** [comment] 2017-08-17 02:17
yes. I do it. 
Now, I have found method.
It is a updating ckpt. The source is following:
===================================================================

def` RenameCkpt():
    vars_to_rename = {
    "LSTM/basic_lstm_cell/weights": "LSTM/basic_lstm_cell/kernel",
    "LSTM/basic_lstm_cell/biases": "LSTM/basic_lstm_cell/bias",
    }
    new_checkpoint_vars = {}
    reader = tf.train.NewCheckpointReader(FLAGS.checkpoint_path)
    for old_name in reader.get_variable_to_shape_map():
      if old_name in vars_to_rename:
        new_name = vars_to_rename[old_name]
      else:
        new_name = old_name
      new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))
    init = tf.global_variables_initializer()
    saver = tf.train.Saver(new_checkpoint_vars)
    with tf.Session() as sess:
       sess.run(init)
       saver.save(sess, "/home/ndscbigdata/work/change/tf/gan/im2txt/ckpt/newmodel.ckpt-2000000")
    print("checkpoint file rename successful... ")

According to that, I think LSTM variables of checkpoint is different in TF1.0 and TF1.2. 
No updating ckpt, it could be success in TF1.2. For that, I try to alter my source use to RenameCkpt(), my codes following:
===================================================================
restore_dict = {}
for i in variables[:]:  # the first is global step
    if i.name.replace(':0', '')=='LSTM/basic_lstm_cell/bias':        restore_dict[i.name.replace('LSTM/basic_lstm_cell/bias:0',                                 'LSTM/basic_lstm_cell/biases')] = tf.get_variable('LSTM/basic_lstm_cell/biases',[2048,])
elif i.name.replace(':0', '')=='LSTM/basic_lstm_cell/kernel':        restore_dict[i.name.replace('LSTM/basic_lstm_cell/kernel:0',
                                    'LSTM/basic_lstm_cell/weights')] = tf.get_variable('LSTM/basic_lstm_cell/weights',[1536, 2048])
    else:
        restore_dict[i.name.replace(':0', '')] = i
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
saver.restore(sess, ckpt_path)

Before altering：
===================================================================
restore_dict = {}
for i in variables[:]:  # the first is global step
      restore_dict[i.name.replace(':0', '')] = i
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
saver.restore(sess, ckpt_path)

After altering, the predict.py running have not error in TF1.2, but running results is different to TF1.0 .
This is a multi-labels predict classification.
TF1.0 is able to be predict 2 results, but TF1.2 is just predict 1 result.
Other, I found if no using LSTM variable, it alse just predict 1 result.. The code following:
===================================================================
restore_dict = {}
for i in variables[:]:  # the first is global step
if i.name.replace(':0', '')=='LSTM/basic_lstm_cell/bias': 
print()                                        
#restore_dict[i.name.replace('LSTM/basic_lstm_cell/bias:0','LSTM/basic_lstm_cell/biases')] = tf.get_variable('LSTM/basic_lstm_cell/biases',[2048,])
elif i.name.replace(':0', '')=='LSTM/basic_lstm_cell/kernel':  
print()
#restore_dict[i.name.replace('LSTM/basic_lstm_cell/kernel:0', 'LSTM/basic_lstm_cell/weights')] = tf.get_variable('LSTM/basic_lstm_cell/weights',[1536, 2048])
    else:
        restore_dict[i.name.replace(':0', '')] = i
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
saver.restore(sess, ckpt_path)

**Comment by skye** [comment] 2017-08-17 20:01
I'm not super familiar with this part of the code, but can you use https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/tools/checkpoint_convert.py?

**Comment by luckynote** [comment] 2017-08-18 01:55
Ok, Thanks!

**Comment by aselle** [comment] 2017-10-03 17:27
If the issue is resolved with checkpointconvert, please let us know so we can close the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2017-12-20 01:15
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:09
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Closed** 2018-02-02 15:32 UTC
Labels: stat:awaiting response, type:support
