### ISSUE TITLE
'VBN' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by hadaev8** [tensorflow/tensorflow#20431] opened 2018-06-29 21:40 UTC
Its broken or I do wrong something?

version 1.9.0-rc1

i = tf.layers.conv2d_transpose(i, filters, 4, strides=2, activation=tf.nn.leaky_relu, padding='same')
i = tf.contrib.gan.features.VBN(i)

**Comment by tensorflowbutler** [comment] 2018-06-30 06:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hadaev8** [comment] 2018-06-30 12:02
Its google colab virtual machine

**Comment by yongtang** [comment] 2018-07-14 18:08
@hadaev8 I am not able to reproduce with v1.9.0. Can you share the full code snippet that trigger the error?

**Comment by joel-shor** [comment] 2018-07-15 10:45
I'm closing this out as not reproducible unless someone objects.

**Closed by joel-shor** 2018-07-15 10:45 UTC

**Comment by hadaev8** [comment] 2018-07-15 12:13
https://pastebin.com/czeQ3UUv
Here is my code, checked on colab tensorflow 1.9.0 rc2 just now
