### ISSUE TITLE
wrong error message from tf.data.Dataset when GPU OOM

### ISSUE THREAD

**Issue by jiayiliu** [tensorflow/tensorflow#36520] opened 2020-02-06 18:52 UTC
I am filing this issue in case someone else ran into the same problem.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1/7
- GPU model and memory:Titan XP/12GB

**Describe the current behavior**

When GPU memory is `fully` taken by another tf session, I failed to run the following script:

```python
tf.data.Dataset.list_files("some files")
```

and got the following error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero. [Op:ShuffleDatasetV2]
```

**Describe the expected behavior**

I expected to get an OOM error, which is much clear about the real root cause of the problem.

**Code to reproduce the issue**

In one python session, run some tensorflow code to take all the GPU memory  (I ran some MobileNet inference to take  11879MiB / 12194MiB of the GPU memory).
In another python session, run `tf.data.Dataset.list_files("./*")`  will reproduce the misleading error message.

**Comment by sushreebarsa** [comment] 2021-08-11 08:09
@jiayiliu It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by jsimsa** [comment] 2021-08-11 15:44
The error indicates that the `shuffle` buffer size used by the implementation of `list_files` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L1241-L1246), which indicates that the pattern that you provided did not match any files. This should be caught by the [following check](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L1235-L1238), which was  introduced after TF 2.1. 

All in all, the error you are seeing has nothing to do with GPU memory and instead is caused by the fact that your file pattern does not match any files. Latest version of TF provides a clear error message for this.

**Closed by jsimsa** 2021-08-11 15:44 UTC
Labels: stat:awaiting response, type:bug, comp:gpu, comp:data, TF 2.1
