### ISSUE TITLE
Reduce size of published wheel files (_pywrap_tensorflow_internal.so)

### ISSUE THREAD

**Issue by aaliddell** [tensorflow/tensorflow#40492] opened 2020-06-15 22:29 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): N/A

**Describe the feature and the current behavior/state.**
The size of the wheel files published for Tensorflow over the 2.x.x releases has increased dramatically and is reaching somewhat absurd levels. Taking for example the cp37 manylinux2010 wheel:

2.0.0: 84 MB
2.1.0: 422 MB
2.2.0: 516 MB

Presently, anyone depending on these wheels may have seen their download and build times quintuple over the 2.x.x lifespan, with resulting images etc also now significantly larger than before.

The increase in size appears to be dominated by a single 1.2 GB shared library file `_pywrap_tensorflow_internal.so`. Presumably this increase might relate to the switch from swig to pybind, with this .so file containing nearly half a million symbols. Many of these symbols are stacks of variations of parameters to single functions.

Obviously just asking for a file to be smaller isn't much help, but I would hope this can prompt some discussion about ways this can be remedied? Assuming it is related to the pybind switch, is there anything that can be learned from the prior swig architecture and applied in the current process?

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
All users who depend on the Python .whl files published to PyPI. Users with custom builds of Tensorflow will likely also have this large .so issue.

**Any Other info.**
There may already be an issue or discussion related to this, but GitHub search didn't reveal much.

**Comment by av8ramit** [comment] 2020-06-16 00:08
Hey @aaliddell So the migration to pybind11 is not the primary cause of the size increase. It's the [CUDA compute capabilities](https://github.com/tensorflow/tensorflow/blob/692bb1da53493a6cf37dc28a4c1e1a82df32d9fa/tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/pip.sh#L43) that we package with each version. I think we may have packaged less with 2.0.0, but if you look at [1.15](https://files.pythonhosted.org/packages/92/2b/e3af15221da9ff323521565fa3324b0d7c7c5b1d7a8ca66984c8d59cb0ce/tensorflow-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl) we were hovering around 412MB as well. 

That being said we are looking into packaging compressed versions of the computes. @chsigg has [submitted this](https://github.com/tensorflow/tensorflow/commit/cf1b6b3dfe9ba82e805fddf7f4462b2d92fe550a#diff-6c70c9243b0c415aafd2f909a553ee22) and we have already seen a size decrease in the `tf-nightly` binaries to around [350MB](https://pypi.org/project/tf-nightly/2.3.0.dev20200614/#files).

**Comment by aaliddell** [comment] 2020-06-16 10:56
Ok, that's great to hear and I'm glad it's being look at; I see the .so file is now halved in size in the nightly wheel that you've linked. I guess other inputs to that library have been looked at to see if similar gains are available? I don't have much visibility into what now dominates the size of this file.

In terms of this issue: is it worth holding to track actions for reducing the size, or are there better more-specific issues available to track this? I'll trust your judgement on what you'd like to do with this one.

**Comment by av8ramit** [comment] 2020-06-16 19:28
So we have internal trackers and goals to monitor and reduce the size. Since the particular issue you referenced is not the root cause, and we have significantly decreased the size for now, I'll close this issue and link it internally. Hope that is okay. Thanks for filing the issue and looking into this!

**Closed by av8ramit** 2020-06-16 19:28 UTC
Labels: stat:awaiting response, type:feature
