### ISSUE TITLE
Bug in Keras Guide

### ISSUE THREAD

**Issue by pouannes** [tensorflow/tensorflow#28519] opened 2019-05-08 12:23 UTC
## URL(s) with the issue:

https://www.tensorflow.org/guide/keras#multiple_gpus

## Description of issue (what needs changing):

The last line of this guide produces a bug when ran on the associated colab notebook (maybe everywhere, I haven't checked).

### Raises listed and defined

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

19 frames
InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node training/TFOptimizer/NcclAllReduce}}with these attrs: [reduction="sum", shared_name="c0", T=DT_FLOAT, num_devices=1]
Registered devices: [CPU, GPU, XLA_CPU, XLA_GPU]
Registered kernels:
  <no registered kernels>

	 [[{{node training/TFOptimizer/NcclAllReduce}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by node training/TFOptimizer/NcclAllReduce (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1254) with these attrs: [reduction="sum", shared_name="c0", T=DT_FLOAT, num_devices=1]
Registered devices: [CPU, GPU, XLA_CPU, XLA_GPU]
Registered kernels:
  <no registered kernels>
```
Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

No, I'm only beginning in TF/Keras :)

**Comment by ymodak** [comment] 2019-05-08 17:36
@pouannes Thanks for trying TF Keras colab. I was able to execute the colab successfully as is. Are you changing any module version or parameter in the colab?

**Comment by pouannes** [comment] 2019-05-10 11:36
I've checked again, the issue was that by habit I used a GPU in colab. Maybe it's not a bug anymore then? I don't really know, but you should be able to reproduce the exception by choosing a GPU as the hardware accelerator.

**Comment by ymodak** [comment] 2019-05-10 21:11
I see. You have to install TF-gpu to use gpu accelerator. Closing this issue since it's not a bug and works in colab (without hardware accelerator). Thanks!

**Closed by ymodak** 2019-05-10 21:11 UTC
Labels: comp:keras, type:docs
