### ISSUE TITLE
NameError:

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51745] opened 2021-08-30 07:54 UTC
![4](https://user-images.githubusercontent.com/26819449/131285254-1698b895-d3d7-4c10-9251-8c169d7d5dd8.JPG)

![5](https://user-images.githubusercontent.com/26819449/131285259-61b09421-68ae-490e-9a1d-30aeefa364a5.JPG)

TensorFlow version : 2.2
Keras version: 2.4.3
Even after defining it. It's telling to define it.
Please assign someone who can reply fast.
Thank You.

**Comment by sushreebarsa** [comment] 2021-08-30 10:13
@starboyvarun We see that you have attached the snapshot of the issue .In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Could you please try on the latest version of TF 2.6 and let us know if it helps?Thanks!

**Comment by starboyvarun** [comment] 2021-08-30 10:21
![i](https://user-images.githubusercontent.com/26819449/131324477-5c1bd7b3-67a2-44de-8957-9c1a59bd7809.JPG)

![j](https://user-images.githubusercontent.com/26819449/131324500-18585d5d-9648-4a7e-85a9-82ae6f309a02.JPG)

Actually, the framework [janggu], I am using that supports only this version. and a member of that repo advised me to use these versions. Even it's mentioned in read me.

**Comment by sushreebarsa** [comment] 2021-08-30 11:08
@starboyvarun Please provide us the complete code of colab gist, notebook or github link to reproduce the issue reported here.Thanks!

**Comment by starboyvarun** [comment] 2021-08-30 11:32
@sushreebarsa sure.
link: https://colab.research.google.com/drive/1h8ECIVvp3sezj2q_hRHC3D3pacT9oooO?usp=sharing

**Comment by sushreebarsa** [comment] 2021-08-30 12:17
@starboyvarun Thanks for the quick update! I tried to run your code on Colab and didn't face the error reported as `NameError: name GlobalAveragePooling2D is not defined`. I faced `NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.`error while running your code, Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/3b3699df13663c538aea37eca89b717c/30augsolved.ipynb#scrollTo=RU9QSOaW8nL_) for reference. As we can see the issue is not related to TensorFlow and more specific to Janggu so you should post this issue on Janggu repo .Please close this issue here and open a new ticket in that Janggu repo if you have further concerns .We hope you'll get the right help there! Thank you!

**Comment by starboyvarun** [comment] 2021-08-30 12:52
I just created a copy of my google collab.
And sent you the link, its showing NameError: name GlobalAveragePooling2D is not defined

**Comment by sushreebarsa** [comment] 2021-08-30 13:12
@starboyvarun Can you please let us know if you have tried to use **`from keras.layers import GlobalAveragePooling2D`** to resolve the NameError ? Thanks!

**Closed** 2021-08-31 10:26 UTC
Labels: type:others, comp:ops, TF 2.2
