### ISSUE TITLE
Unity3D ml-agents not working properly in TF 2.0

### ISSUE THREAD

**Issue by SetoKaiba** [tensorflow/tensorflow#27425] opened 2019-04-02 12:54 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.0.0-alpha0
- Python version:3.6

**Describe the current behavior**
The value estimate became an array instead of scalar float after 8000+ steps

**Describe the expected behavior**
The value estimate should be a scalar float

**Code to reproduce the issue**
https://github.com/SetoKaiba/ml-agents/tree/tf2

**Other info / logs**
After some deep dig, I found the problem is here. It uses the tf session to estimate the value. The value became an array instead of scalar float after 8000+ steps
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L198

**Comment by SetoKaiba** [comment] 2019-04-02 14:47
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L199-L200
I finally get it working by some trick. If the value_estimate[0][0] is an array of (1,1). I'll get the value_estimate[0][0].
Why does it became an array? 
The value is calculate by the code here.
```
        value = tf.layers.dense(hidden_value, 1, activation=None)
        self.value = tf.identity(value, name="value_estimate")
```
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/models.py#L298-L299

**Comment by SetoKaiba** [comment] 2019-04-05 12:31
Anyone helps? Is it a bug of TF 2.0?

**Comment by SetoKaiba** [comment] 2019-04-05 12:34
Is it read by Tensorflow official? Is it a bug? The code below sometime generate an ndarray instead of a float.
```Python
        value = tf.layers.dense(hidden_value, 1, activation=None)
        self.value = tf.identity(value, name="value_estimate")
```

**Comment by SetoKaiba** [comment] 2019-04-08 06:27
Can any one reply or help?

**Comment by achandraa** [comment] 2019-04-15 06:08
Closing the issue since it is a duplicate of #27669 . Thank you!

**Closed by achandraa** 2019-04-15 06:08 UTC
Labels: 2.0.0-alpha0, comp:model, type:support
