### ISSUE TITLE
tf_upgrade_v2 can't work on windows

### ISSUE THREAD

**Issue by Jinnrry** [tensorflow/tensorflow#33927] opened 2019-11-02 01:55 UTC
This is my command
```
tf_upgrade_v2 --infile model_train_testByreallydata.py --outfile model_train_testByreallydata_tf2.py
```

It will get 

```
(tensorflow2) C:\Users\63110\OneDrive\github-backup\mhxy-captcha>tf_upgrade_v2 --infile model_train_testByreallydata.py --outfile model_train_testByreallydata_tf2.py
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\tensorflow2\Scripts\tf_upgrade_v2-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\tools\compatibility\tf_upgrade_v2_main.py", line 139, in main
    args.input_file, output_file, upgrade)
  File "E:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\tools\compatibility\tf_upgrade_v2_main.py", line 40, in process_file
    upgrader.process_file(in_filename, out_filename)
  File "E:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\tools\compatibility\ast_edits.py", line 900, in process_file
    temp_file)
  File "E:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\tools\compatibility\ast_edits.py", line 958, in process_opened_file
    lines = in_file.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 300: illegal multibyte sequence

```

Os:
windows 10 

Python Version:
3.7 from Anaconda

**Comment by nikochiko** [comment] 2019-11-02 06:36
Can you share your file model_train_testByreallydata.py if it doesn't have any sensitive data. I can try working with tweaks on my system.

**Comment by Jinnrry** [comment] 2019-11-04 03:40
```
# -*- coding:utf-8 -*-
# name: model_train.py
import os

import tensorflow as tf
from datetime import datetime
from util import get_next_batch, get_test_batch
from captcha_gen import CAPTCHA_HEIGHT, CAPTCHA_WIDTH, CAPTCHA_LEN, CAPTCHA_LIST


def weight_variable(shape, w_alpha=0.01):
    """
    初始化权值
    :param shape:
    :param w_alpha:
    :return:
   """
    initial = w_alpha * tf.random_normal(shape)
    return tf.Variable(initial)


def bias_variable(shape, b_alpha=0.1):
    """
    初始化偏置项
    :param shape:
    :param b_alpha:
    :return:
    """
    initial = b_alpha * tf.random_normal(shape)
    return tf.Variable(initial)


def conv2d(x, w):
    """
    卷基层 ：局部变量线性组合，步长为1，模式‘SAME’代表卷积后图片尺寸不变，即零边距
    :param x:
    :param w:
    :return:
    """
    return tf.nn.conv2d(x, w, strides=[1, 1, 1, 1], padding='SAME')


def max_pool_2x2(x):
    """
    池化层：max pooling,取出区域内最大值为代表特征， 2x2 的pool，图片尺寸变为1/2
    :param x:
    :return:
    """
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')


def cnn_graph(x, keep_prob, size, captcha_list=CAPTCHA_LIST, captcha_len=CAPTCHA_LEN):
    """
    三层卷积神经网络
    :param x:   训练集 image x
    :param keep_prob:   神经元利用率
    :param size:        大小 (高,宽)
    :param captcha_list:
    :param captcha_len:
    :return: y_conv
    """
    # 需要将图片reshape为4维向量
    image_height, image_width = size
    x_image = tf.reshape(x, shape=[-1, image_height, image_width, 1])

    # 第一层
    # filter定义为3x3x1， 输出32个特征, 即32个filter
    w_conv1 = weight_variable([3, 3, 1, 32])  # 3*3的采样窗口，32个（通道）卷积核从1个平面抽取特征得到32个特征平面
    b_conv1 = bias_variable([32])
    h_conv1 = tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)  # rulu激活函数
    h_pool1 = max_pool_2x2(h_conv1)  # 池化
    h_drop1 = tf.nn.dropout(h_pool1, keep_prob)  # dropout防止过拟合

    # 第二层
    w_conv2 = weight_variable([3, 3, 32, 64])
    b_conv2 = bias_variable([64])
    h_conv2 = tf.nn.relu(conv2d(h_drop1, w_conv2) + b_conv2)
    h_pool2 = max_pool_2x2(h_conv2)
    h_drop2 = tf.nn.dropout(h_pool2, keep_prob)

    # 第三层
    w_conv3 = weight_variable([3, 3, 64, 64])
    b_conv3 = bias_variable([64])
    h_conv3 = tf.nn.relu(conv2d(h_drop2, w_conv3) + b_conv3)
    h_pool3 = max_pool_2x2(h_conv3)
    h_drop3 = tf.nn.dropout(h_pool3, keep_prob)

    """
    原始：60*160图片 第一次卷积后 60*160 第一池化后 30*80
    第二次卷积后 30*80 ，第二次池化后 15*40
    第三次卷积后 15*40 ，第三次池化后 7.5*20 = > 向下取整 7*20
    经过上面操作后得到7*20的平面
    """

    # 全连接层
    image_height = int(h_drop3.shape[1])
    image_width = int(h_drop3.shape[2])
    w_fc = weight_variable([image_height * image_width * 64, 1024])  # 上一层有64个神经元 全连接层有1024个神经元
    b_fc = bias_variable([1024])
    h_drop3_re = tf.reshape(h_drop3, [-1, image_height * image_width * 64])
    h_fc = tf.nn.relu(tf.matmul(h_drop3_re, w_fc) + b_fc)
    h_drop_fc = tf.nn.dropout(h_fc, keep_prob)

    # 输出层
    w_out = weight_variable([1024, len(captcha_list) * captcha_len])
    b_out = bias_variable([len(captcha_list) * captcha_len])
    y_conv = tf.matmul(h_drop_fc, w_out) + b_out
    return y_conv


def optimize_graph(y, y_conv):
    """
    优化计算图
    :param y: 正确值
    :param y_conv:  预测值
    :return: optimizer
    """
    # 交叉熵代价函数计算loss 注意logits输入是在函数内部进行sigmod操作
    # sigmod_cross适用于每个类别相互独立但不互斥，如图中可以有字母和数字
    # softmax_cross适用于每个类别独立且排斥的情况，如数字和字母不可以同时出现
    loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=y_conv))
    # 最小化loss优化 AdaminOptimizer优化
    optimizer = tf.train.AdamOptimizer(1e-3).minimize(loss)
    return optimizer


def accuracy_graph(y, y_conv, width=len(CAPTCHA_LIST), height=CAPTCHA_LEN):
    """
    偏差计算图，正确值和预测值，计算准确度
    :param y: 正确值 标签
    :param y_conv:  预测值
    :param width:   验证码预备字符列表长度
    :param height:  验证码的大小，默认为4
    :return:    正确率
    """
    # 这里区分了大小写 实际上验证码一般不区分大小写,有四个值，不同于手写体识别
    # 预测值
    predict = tf.reshape(y_conv, [-1, height, width])  #
    max_predict_idx = tf.argmax(predict, 2)
    # 标签
    label = tf.reshape(y, [-1, height, width])
    max_label_idx = tf.argmax(label, 2)
    correct_p = tf.equal(max_predict_idx, max_label_idx)  # 判断是否相等
    accuracy = tf.reduce_mean(tf.cast(correct_p, tf.float32))
    return accuracy


def train(height=CAPTCHA_HEIGHT, width=CAPTCHA_WIDTH, y_size=len(CAPTCHA_LIST) * CAPTCHA_LEN):
    """
    cnn训练
    :param height: 验证码高度
    :param width:   验证码宽度
    :param y_size:  验证码预备字符列表长度*验证码长度（默认为4）
    :return:
    """
    # cnn在图像大小是2的倍数时性能最高, 如果图像大小不是2的倍数，可以在图像边缘补无用像素
    # 在图像上补2行，下补3行，左补2行，右补2行
    # np.pad(image,((2,3),(2,2)), 'constant', constant_values=(255,))
    show = open("show.txt", 'a')

    acc_rate = 0.95  # 预设模型准确率标准
    # 按照图片大小申请占位符
    x = tf.placeholder(tf.float32, [None, height * width])
    y = tf.placeholder(tf.float32, [None, y_size])
    # 防止过拟合 训练时启用 测试时不启用 神经元使用率
    keep_prob = tf.placeholder(tf.float32)
    # cnn模型
    y_conv = cnn_graph(x, keep_prob, (height, width))
    # 优化
    optimizer = optimize_graph(y, y_conv)
    # 计算准确率
    accuracy = accuracy_graph(y, y_conv)
    # 启动会话.开始训练
    saver = tf.train.Saver(max_to_keep=3)
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())  # 初始化

    # 基于当前已有模型训练
    if os.path.exists("model/checkpoint"):
        model_file = tf.train.latest_checkpoint('model')
        saver.restore(sess, model_file)
    step = 0  # 步数

    really_acc_max = 0

    while 1:
        batch_x, batch_y = get_next_batch(64)
        sess.run(optimizer, feed_dict={x: batch_x, y: batch_y, keep_prob: 0.75})
        # 每训练一百次测试一次
        if step % 100 == 0:
            batch_x_test, batch_y_test = get_test_batch()
            acc = sess.run(accuracy, feed_dict={x: batch_x_test, y: batch_y_test, keep_prob: 1.0})
            show.writelines(
                "really：    " + datetime.now().strftime('%c') + ' step:' + str(step) + ' accuracy:' + str(acc) + "\n")
            show.tell()
            print("really：  " + datetime.now().strftime('%c'), ' step:', step, ' accuracy:', acc)

            if acc > really_acc_max:
                really_acc_max = acc
                model_path = "./model/really_max/captcha.model"
                saver.save(sess, model_path, global_step=step)

            batch_x_test, batch_y_test = get_next_batch(100)
            acc = sess.run(accuracy, feed_dict={x: batch_x_test, y: batch_y_test, keep_prob: 1.0})
            show.writelines(
                "moni：  " + datetime.now().strftime('%c') + ' step:' + str(step) + ' accuracy:' + str(acc) + "\n")
            show.tell()
            print("moni：    " + datetime.now().strftime('%c'), ' step:', step, ' accuracy:', acc)

            # 准确率满足要求，保存模型
            if acc > acc_rate:
                model_path = "./model/captcha.model"
                saver.save(sess, model_path, global_step=step)
                acc_rate += 0.01
                if acc_rate > 0.99:  # 准确率达到99%则退出
                    pass
        step += 1
    sess.close()


if __name__ == '__main__':
    train()

```


It works fine on ubuntu.

**Comment by minemine1126** [comment] 2019-11-22 01:22
I get the same result, is there a solution?

**Comment by minemine1126** [comment] 2019-11-22 08:07
This error may be caused by the punctuation of the Chinese input method in the code and some Chinese characters, such as ‘需’, ‘为’, ‘第一层',etc. I deleted the Chinese characters in the code and replaced the Chinese punctuation with English punctuation.it works well.
The result:

    INFO line 17:24: Renamed 'tf.random_normal' to 'tf.random.normal'
    INFO line 27:24: Renamed 'tf.random_normal' to 'tf.random.normal'
    INFO line 37:11: Added keywords to args of function 'tf.nn.conv2d'
    INFO line 37:11: Renamed keyword argument for tf.nn.conv2d from filter to filters
    INFO line 45:11: Added keywords to args of function 'tf.nn.max_pool'
    INFO line 45:11: Renamed keyword argument for tf.nn.max_pool from value to input
    INFO line 45:11: Renamed 'tf.nn.max_pool' to 'tf.nn.max_pool2d'
    INFO line 65:14: Changing keep_prob arg of tf.nn.dropout to rate, and recomputing value.

    INFO line 71:14: Changing keep_prob arg of tf.nn.dropout to rate, and recomputing value.

    INFO line 77:14: Changing keep_prob arg of tf.nn.dropout to rate, and recomputing value.

    INFO line 85:16: Changing keep_prob arg of tf.nn.dropout to rate, and recomputing value.

    INFO line 100:11: Added keywords to args of function 'tf.reduce_mean'
    INFO line 102:16: Renamed 'tf.train.AdamOptimizer' to 'tf.compat.v1.train.AdamOptimizer'
    INFO line 116:22: Added keywords to args of function 'tf.argmax'
    INFO line 119:20: Added keywords to args of function 'tf.argmax'
    INFO line 121:15: Added keywords to args of function 'tf.reduce_mean'
    INFO line 139:8: Renamed 'tf.placeholder' to 'tf.compat.v1.placeholder'
    INFO line 140:8: Renamed 'tf.placeholder' to 'tf.compat.v1.placeholder'
    INFO line 142:16: Renamed 'tf.placeholder' to 'tf.compat.v1.placeholder'
    INFO line 150:12: Renamed 'tf.train.Saver' to 'tf.compat.v1.train.Saver'
    INFO line 151:11: Renamed 'tf.Session' to 'tf.compat.v1.Session'
    INFO line 152:13: Renamed 'tf.global_variables_initializer' to 'tf.compat.v1.global_variables_initializer'
    WARNING line 176:16: *.save requires manual check. (This warning is only applicable if the code saves a tf.Keras model) Keras model.save now saves to the Tensorflow SavedModel format by default, instead of HDF5. To continue saving to HDF5, add the argument save_format='h5' to the save() function.
    WARNING line 187:16: *.save requires manual check. (This warning is only applicable if the code saves a tf.Keras model) Keras model.save now saves to the Tensorflow SavedModel format by default, instead of HDF5. To continue saving to HDF5, add the argument save_format='h5' to the save() function.

    TensorFlow 2.0 Upgrade Script
    -----------------------------
    Converted 1 files
    Detected 2 issues that require attention
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    File: model_train_testByreallydata.py
    --------------------------------------------------------------------------------
    model_train_testByreallydata.py:176:16: WARNING: *.save requires manual check. (This warning is only applicable if the code saves a tf.Keras model) Keras model.save now saves to the Tensorflow SavedModel format by default, instead of HDF5. To continue saving to HDF5, add the argument save_format='h5' to the save() function.
    model_train_testByreallydata.py:187:16: WARNING: *.save requires manual check. (This warning is only applicable if the code saves a tf.Keras model) Keras model.save now saves to the Tensorflow SavedModel format by default, instead of HDF5. To continue saving to HDF5, add the argument save_format='h5' to the save() function.


    Make sure to read the detailed log 'report.txt'

The code:

    # -*- coding:utf-8 -*-
    # name: model_train.py
    import os

    import tensorflow as tf
    from datetime import datetime
    from util import get_next_batch, get_test_batch
    from captcha_gen import CAPTCHA_HEIGHT, CAPTCHA_WIDTH, CAPTCHA_LEN, CAPTCHA_LIST


    def weight_variable(shape, w_alpha=0.01):
        """
        :param shape:
        :param w_alpha:
        :return:
    """
        initial = w_alpha * tf.random_normal(shape)
        return tf.Variable(initial)


    def bias_variable(shape, b_alpha=0.1):
        """
        :param shape:
        :param b_alpha:
        :return:
        """
        initial = b_alpha * tf.random_normal(shape)
        return tf.Variable(initial)


    def conv2d(x, w):
        """
        :param x:
        :param w:
        :return:
        """
        return tf.nn.conv2d(x, w, strides=[1, 1, 1, 1], padding='SAME')


    def max_pool_2x2(x):
        """
        :param x:
        :return:
        """
        return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')


    def cnn_graph(x, keep_prob, size, captcha_list=CAPTCHA_LIST, captcha_len=CAPTCHA_LEN):
        """
        :param x:image x
        :param keep_prob:
        :param size:
        :param captcha_list:
        :param captcha_len:
        :return: y_conv
        """

        image_height, image_width = size
        x_image = tf.reshape(x, shape=[-1, image_height, image_width, 1])

        w_conv1 = weight_variable([3, 3, 1, 32])
        b_conv1 = bias_variable([32])
        h_conv1 = tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)
        h_pool1 = max_pool_2x2(h_conv1)
        h_drop1 = tf.nn.dropout(h_pool1, keep_prob)

        w_conv2 = weight_variable([3, 3, 32, 64])
        b_conv2 = bias_variable([64])
        h_conv2 = tf.nn.relu(conv2d(h_drop1, w_conv2) + b_conv2)
        h_pool2 = max_pool_2x2(h_conv2)
        h_drop2 = tf.nn.dropout(h_pool2, keep_prob)

        w_conv3 = weight_variable([3, 3, 64, 64])
        b_conv3 = bias_variable([64])
        h_conv3 = tf.nn.relu(conv2d(h_drop2, w_conv3) + b_conv3)
        h_pool3 = max_pool_2x2(h_conv3)
        h_drop3 = tf.nn.dropout(h_pool3, keep_prob)

        image_height = int(h_drop3.shape[1])
        image_width = int(h_drop3.shape[2])
        w_fc = weight_variable([image_height * image_width * 64, 1024])
        b_fc = bias_variable([1024])
        h_drop3_re = tf.reshape(h_drop3, [-1, image_height * image_width * 64])
        h_fc = tf.nn.relu(tf.matmul(h_drop3_re, w_fc) + b_fc)
        h_drop_fc = tf.nn.dropout(h_fc, keep_prob)

        w_out = weight_variable([1024, len(captcha_list) * captcha_len])
        b_out = bias_variable([len(captcha_list) * captcha_len])
        y_conv = tf.matmul(h_drop_fc, w_out) + b_out
        return y_conv


    def optimize_graph(y, y_conv):
        """
        :param y:
        :param y_conv:
        :return: optimizer
        """

        loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=y_conv))

        optimizer = tf.train.AdamOptimizer(1e-3).minimize(loss)
        return optimizer


    def accuracy_graph(y, y_conv, width=len(CAPTCHA_LIST), height=CAPTCHA_LEN):
        """
        :param y:
        :param y_conv:
        :param width:
        :param height:
        :return:
        """

        predict = tf.reshape(y_conv, [-1, height, width])  #
        max_predict_idx = tf.argmax(predict, 2)

        label = tf.reshape(y, [-1, height, width])
        max_label_idx = tf.argmax(label, 2)
        correct_p = tf.equal(max_predict_idx, max_label_idx)
        accuracy = tf.reduce_mean(tf.cast(correct_p, tf.float32))
        return accuracy


    def train(height=CAPTCHA_HEIGHT, width=CAPTCHA_WIDTH, y_size=len(CAPTCHA_LIST) * CAPTCHA_LEN):
        """
        cnn train
        :param height:
        :param width:
        :param y_size:
        :return:
        """

        # np.pad(image,((2,3),(2,2)), 'constant', constant_values=(255,))
        show = open("show.txt", 'a')

        acc_rate = 0.95

        x = tf.placeholder(tf.float32, [None, height * width])
        y = tf.placeholder(tf.float32, [None, y_size])

        keep_prob = tf.placeholder(tf.float32)

        y_conv = cnn_graph(x, keep_prob, (height, width))

        optimizer = optimize_graph(y, y_conv)

        accuracy = accuracy_graph(y, y_conv)

        saver = tf.train.Saver(max_to_keep=3)
        sess = tf.Session()
        sess.run(tf.global_variables_initializer())

        if os.path.exists("model/checkpoint"):
            model_file = tf.train.latest_checkpoint('model')
            saver.restore(sess, model_file)
        step = 0

        really_acc_max = 0

        while 1:
            batch_x, batch_y = get_next_batch(64)
            sess.run(optimizer, feed_dict={x: batch_x, y: batch_y, keep_prob: 0.75})

            if step % 100 == 0:
                batch_x_test, batch_y_test = get_test_batch()
                acc = sess.run(accuracy, feed_dict={x: batch_x_test, y: batch_y_test, keep_prob: 1.0})
                show.writelines(
                    "really:" + datetime.now().strftime('%c') + ' step:' + str(step) + ' accuracy:' + str(acc) + "\n")
                show.tell()
                print("really:" + datetime.now().strftime('%c'), ' step:', step, ' accuracy:', acc)

                if acc > really_acc_max:
                    really_acc_max = acc
                    model_path = "./model/really_max/captcha.model"
                    saver.save(sess, model_path, global_step=step)

                batch_x_test, batch_y_test = get_next_batch(100)
                acc = sess.run(accuracy, feed_dict={x: batch_x_test, y: batch_y_test, keep_prob: 1.0})
                show.writelines(
                    "moni:" + datetime.now().strftime('%c') + ' step:' + str(step) + ' accuracy:' + str(acc) + "\n")
                show.tell()
                print("moni:" + datetime.now().strftime('%c'), ' step:', step, ' accuracy:', acc)

                if acc > acc_rate:
                    model_path = "./model/captcha.model"
                    saver.save(sess, model_path, global_step=step)
                    acc_rate += 0.01
                    if acc_rate > 0.99:
                        pass
            step += 1
        sess.close()


    if __name__ == '__main__':
        train()

**Comment by nikochiko** [comment] 2019-11-22 09:56
@minemine1126 @Jinnrry , Looks like an encoding bug to me. The default encoding while using `open` to open a file is `unicode` so this method won't be compatible with `utf-8` characters as Chinese strings as @minemine1126 pointed out.
@jvishnuvardhan , please see.

**Comment by zenglian** [comment] 2020-02-09 02:54
Add `, encoding='UTF-8'` in `...\tensorflow_core\tools\compatibility\ast_edits.py`, line 897 **and** line 898 as below:

    # Write to a temporary file, just in case we are doing an implace modify.
    # pylint: disable=g-backslash-continuation
    with open(in_filename, "r", encoding='UTF-8') as in_file, \
        tempfile.NamedTemporaryFile("w", delete=False, encoding='UTF-8') as temp_file:
      ret = self.process_opened_file(in_filename, in_file, out_filename, temp_file)

**Comment by mihaimaruseac** [comment] 2020-02-10 19:18
It is an encoding bug related to Windows, not a TensorFlow issue. As such, we move to close the issue, especially given that there is a workaround in the comment above.

**Closed by mihaimaruseac** 2020-02-10 19:18 UTC
Labels: TF 2.0, comp:ops, type:support

**Comment by 00x0101101** [comment] 2024-06-23 09:20
Just like what @zenglian said, in `...\tensorflow_core\tools\compatibility\ipynb.py` add `,encoding = "UTF-8"` at line 43 **AND** line 108 may help, as a quick-fix, when similiar issue encountered when upgrading a Jupyter Notebook.

当在升级JupyterNotebook中的代码时，在同文件夹里面的`ipynb.py` 里面的 43行和 108行指定文件读取的编码格式应该可以解决类似的问题。
