### ISSUE TITLE
tf.ragged.boolean_mask not working in symbolic mode

### ISSUE THREAD

**Issue by adriang133** [tensorflow/tensorflow#45340] opened 2020-12-02 14:15 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.8

**Describe the current behavior**
```python
x = tf.keras.Input(shape=(101,), dtype=tf.float32)
mask = tf.where(tf.math.greater(x, 1.), True, False)
ragged_x = tf.ragged.boolean_mask(x, mask)
```
throws
```
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: <tf.Tensor 'Cumsum_1:0' shape=(None,) dtype=int64>
```

**Describe the expected behavior**

The above should work. 
It works if x is an eager tensor.

**Standalone code to reproduce the issue**
See above.

**Other info / logs** Include any logs or source code that would be helpful to
---------------------------------------------------------------------------

> ValueError                                Traceback (most recent call last)
> <ipython-input-2-9d996c714f77> in <module>()
>       1 x = tf.keras.Input(shape=(101,), dtype=tf.float32)
>       2 mask = tf.where(tf.math.greater(x, 1.), True, False)
> ----> 3 ragged_x = tf.ragged.boolean_mask(x, mask)
> 
> 9 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
>     199     """Call target, and fall back on dispatchers if there is a TypeError."""
>     200     try:
> --> 201       return target(*args, **kwargs)
>     202     except (TypeError, ValueError):
>     203       # Note: convert_to_eager_tensor currently raises a ValueError, not a
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/ragged/ragged_array_ops.py in boolean_mask(data, mask, name)
>     191         flattened_masked_lengths = array_ops.reshape(masked_lengths, [-1])
>     192         masked_values = ragged_tensor.RaggedTensor.from_row_lengths(
> --> 193             masked_values, flattened_masked_lengths, validate=False)
>     194 
>     195         # Wrap remaining ragged dimensions.
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/ragged/ragged_tensor.py in from_row_lengths(cls, values, row_lengths, name, validate)
>     473           row_lengths=row_lengths,
>     474           validate=validate,
> --> 475           preferred_dtype=_get_optional_partition_dtype(values))
>     476       return cls._from_row_partition(values, row_partition, validate=validate)
>     477 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/ragged/row_partition.py in from_row_lengths(cls, row_lengths, validate, preferred_dtype)
>     392 
>     393       row_limits = math_ops.cumsum(row_lengths)
> --> 394       row_splits = array_ops.concat([[0], row_limits], axis=0)
>     395       return cls(
>     396           row_splits=row_splits,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
>     199     """Call target, and fall back on dispatchers if there is a TypeError."""
>     200     try:
> --> 201       return target(*args, **kwargs)
>     202     except (TypeError, ValueError):
>     203       # Note: convert_to_eager_tensor currently raises a ValueError, not a
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in concat(values, axis, name)
>    1652           dtype=dtypes.int32).get_shape().assert_has_rank(0)
>    1653       return identity(values[0], name=name)
> -> 1654   return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
>    1655 
>    1656 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in concat_v2(values, axis, name)
>    1210     try:
>    1211       return concat_v2_eager_fallback(
> -> 1212           values, axis, name=name, ctx=_ctx)
>    1213     except _core._SymbolicException:
>    1214       pass  # Add nodes to the TensorFlow graph.
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in concat_v2_eager_fallback(values, axis, name, ctx)
>    1240         "'concat_v2' Op, not %r." % values)
>    1241   _attr_N = len(values)
> -> 1242   _attr_T, values = _execute.args_to_matching_eager(list(values), ctx)
>    1243   _attr_Tidx, (axis,) = _execute.args_to_matching_eager([axis], ctx, _dtypes.int32)
>    1244   _inputs_flat = list(values) + [axis]
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in args_to_matching_eager(l, ctx, default_dtype)
>     261       ret.append(
>     262           ops.convert_to_tensor(
> --> 263               t, dtype, preferred_dtype=default_dtype, ctx=ctx))
>     264       if dtype is None:
>     265         dtype = ret[-1].dtype
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
>    1473       raise ValueError(
>    1474           "Tensor conversion requested dtype %s for Tensor with dtype %s: %r" %
> -> 1475           (dtype.name, value.dtype.name, value))
>    1476     return value
>    1477 
> 
> ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: <tf.Tensor 'Cumsum:0' shape=(None,) dtype=int64>

**Comment by amahendrakar** [comment] 2020-12-03 09:21
@adriang133,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/c61bb05dd71a50b2085cbf0e5463aa50/45340.ipynb).

However, the issue seems to be fixed in the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/13e81ba348f9d1ea9bd4f911854bac3c/45340-tf-nightly.ipynb). I was able to run the code without any errors. Please check the linked gist for reference. Thanks!

**Comment by adriang133** [comment] 2020-12-03 14:33
Thanks @amahendrakar!

This issue can be closed then.

**Comment by amahendrakar** [comment] 2020-12-08 07:50
@adriang133,
Thank you for the udpate. Closing the issue as it is fixed in the latest TF-nightly.

**Closed by amahendrakar** 2020-12-08 07:50 UTC
Labels: Fixed in Nightly, TF 2.3, comp:ops, type:bug
