### ISSUE TITLE
Error when running tensorflow.python.ops.gen_math_ops.sparse_segment_sum

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59385] opened 2023-01-21 23:54 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Empty input
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_math_ops
try:
  try:
    with tf.device('/CPU'):
      data_tensor = tf.random.uniform([3, 3, 3], dtype=tf.float64)
      data = tf.identity(data_tensor)
      indices = []
      segment_ids = []
      out = gen_math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      data = tf.identity(data_tensor)
      data = tf.cast(data, tf.float64)
      indices = []
      segment_ids = []
      gen_math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-21 18:52:59.679628: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 18:53:00.427623: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-21 18:53:00.427812: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-21 18:53:00.427820: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-21 18:53:01.052135: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.057293: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.057426: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.057751: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 18:53:01.058518: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.058652: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.058766: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.497108: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.497256: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.497364: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 18:53:01.497456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4276 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
2023-01-21 18:53:01.555407: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1159] failed to enqueue async memcpy from device to host: CUDA_ERROR_INVALID_VALUE: invalid argument; host dst: 0x7fe84f600000; GPU src: 0xfffffffffffffffc; size: 4=0x4
Error:{{function_node __wrapped__SparseSegmentSum_device_/job:localhost/replica:0/task:0/device:GPU:0}} SparseSegmentSum: failed to copy last_segment_id from device [Op:SparseSegmentSum]

```
```
</details>

**Comment by gaikwadrahul8** [comment] 2023-01-24 08:24
Hi, @nimashiri 

Apologize for the delay and I was able to replicate the same issue and it seems like we are facing some issue while executing the same code with `Tensorflow-GPU with version 2.11 `on `ubuntu==22.04` but after changing below lines of code, code is running fine on CPU but same error occurring while executing with GPU so it seems like some data types compatibility issue with Data types used by CUDA driver but again we have to dig more into this issue so it may take some time to find out root cause for error with GPU and you can refer [gist file ](https://colab.research.google.com/gist/gaikwadrahul8/eb7dab344a3219b893b68e0a3d966da3/-59385.ipynb)where code is working fine with CPU but same error with GPU 

```
indices = tf.constant([],dtype=np.int32)
segment_ids = tf.constant([],dtype=np.int32)
```

For sparse_segment_sum(), we should pass arguments with correct datatypes as below mentioned :

```
Args:

data: A Tensor. Must be one of the following types: float32, float64, int32, uint8, int16, int8, int64, bfloat16, uint16, half, uint32, uint64.
  
indices: A Tensor. Must be one of the following types: int32, int64.
    A 1-D tensor. Has same rank as segment_ids.
    
segment_ids: A Tensor. Must be one of the following types: int32, int64.
    A 1-D tensor. Values should be sorted and can be repeated.
    
name: A name for the operation (optional).

Returns:
  A Tensor. Has the same type as data.
```

For you reference I have added screenshot where I have tested code on ubuntu 22.04 with GPU configuration and getting same error so we will dig more into it and we'll update you here soon about this issue, Thank you!

![image](https://user-images.githubusercontent.com/115997457/214243082-81bb7be1-8897-4d75-a872-2ca288b08197.png)

**Comment by mihaimaruseac** [comment] 2023-02-02 01:12
Closing as this is valid execution.

**Closed by mihaimaruseac** 2023-02-02 01:12 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.11
