### ISSUE TITLE
Tensorflow 2.1.0 failed to list GPU devices and detect GPU devices automatically

### ISSUE THREAD

**Issue by crownk1997** [tensorflow/tensorflow#35702] opened 2020-01-09 12:43 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): pip3 install tensorflow --upgrade
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.5
- CUDA/cuDNN version: 10.2
- GPU model and memory: GTX2080Ti 11GB

**Describe the current behavior**
I try to implement the official distributed training example by using `strategy = tf.distribute.MirroredStrategy()` to detect the GPU devices. It is supposed to detect all gpu devices automatically. However, when I use this API under my environment, it can only find the CPU devices. 
**Describe the expected behavior**

It should have the same output like the Tensorflow 2.0.0b1.
**Code to reproduce the issue**

```
import tensorflow as tf 
strategy = tf.distribute.MirroredStrategy()
print("Number of devices: {}".format(strategy.num_replicas_in_sync))
```

**Other info / logs**
I also find that the API `tf.config.experimental.list_physical_devices('GPU')` cannot list the GPU devices. After I check, my gpu device type is XLA_GPU. But I can use the same API to list all my GPU devices.

**Comment by ravikyram** [comment] 2020-01-10 05:38
@crownk1997 
Can you please go through the [link ](https://www.tensorflow.org/guide/gpu#manual_device_placement)and see if it helps you.Thanks!

**Comment by crownk1997** [comment] 2020-01-10 06:12
@ravikyram I have checked this link. Actually, there is a toy example in this tutorial which uses `gpus = tf.config.experimental.list_physical_devices('GPU')`this API to check if there is any avaliable gpu device. However, in my case, I have 9 GTX2080Ti and I always get an empty list from the same API. Thank you !

**Comment by sfleisch** [comment] 2020-01-11 06:50
Try 'XLA_GPU'. 

tf.config.list_physical_devices shows XLA_GPU instead of GPU. 

Is there a way to disable this in TF 2.1.0?
The problem is that I'm getting the following error:
/usr/local/anaconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

**InternalError: Device type: XLA_GPU is currently unsupported for remote function executions
	 [[{{node RemoteCall}}]] [Op:IteratorGetNextAsOptional]**
Or alternatively: What is a "remote function execution"?

**Comment by sfleisch** [comment] 2020-01-12 06:38
The problem was in fact that CUDA 10.2 was installed in the Docker image and not 10.1.  Once that was done both device type GPU and XLA_GPU show up.  So specifying GPU instead of XLA_GPU works.  I'm not sure what a remote function is but I suspect that this is due to using mirrored distribution strategy.

So to the OP: Make sure that CUDA 10.1 is installed in your environment.

**Comment by crownk1997** [comment] 2020-01-12 10:46
@sfleisch Thank you for your instruction and I will have a try soon.

**Comment by trangnm58** [comment] 2020-01-24 18:01
Hi!
@crownk1997 Have you resolved this issue?
I installed tensorflow-gpu 2.1 with cuda 10.1 but I my GPU (GTX 1060) is not detected by tensorflow as well and I don't know why because I followed the exact instructions and got all the versions right.

**Comment by ravikyram** [comment] 2020-01-30 10:02
@crownk1997 

Any update on this issue please. Thanks!

**Comment by crownk1997** [comment] 2020-01-30 12:09
@trangnm58 I am so sorry about that. Because I do not have the permission to change the CUDA version on our server.

**Comment by sfleisch** [comment] 2020-01-30 15:47
If you are using a Docker container you need CUDA 10.1 in the container image not the host OS level. You just need a compatible driver and if CUDA 10.2 is installed on the host then you, in fact, do.

**Comment by ymodak** [comment] 2020-02-11 20:06
Setting cuda version to 10.1 with TF 2.1 should provide gpu support. Closing this issue now. Thanks!

**Closed by ymodak** 2020-02-11 20:06 UTC
Labels: TF 2.1, comp:gpu, stat:awaiting response, type:support
