### ISSUE TITLE
TensorFlow r0.11 C impl protobuf package incompatible with Python 3.5

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#5580] opened 2016-11-13 14:21 UTC
When building from source (master branch as r0.11 does not build; see https://github.com/tensorflow/tensorflow/issues/5578) bazel builds a protobuf python implementation.

```
$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
python
```

The C implementation referenced in the documentation is incompatible with Python 3.5 in Ubuntu 16.04:

```
$ pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp3-none-linux_x86_64.whl
protobuf-3.0.0-cp3-none-linux_x86_64.whl is not a supported wheel on this platform.
```

Regression?? https://github.com/tensorflow/tensorflow/issues/3856

**Comment by girving** [comment] 2016-11-14 16:47
@martinwicke Is this a regression?

**Comment by martinwicke** [comment] 2016-11-15 00:30
It's quite possible that renaming this file to `protobuf-3.0.0-cp3-none-any.whl` will fix this. @yifeif did you make the new files? Maybe we should put those through `audit-wheel`?

**Comment by yifeif** [comment] 2016-11-15 19:19
`protobuf-3.0.0-cp3-none-any.whl` is supported according to `pep425` tags for `pip  8.1.2`, so renaming hack should work :)
Looks like we might need to rebuild these packages if we want to pass them through `auditwheel`, as `cp3-none-linux_x86_64` is still not a supported tag.

**Comment by gunan** [comment] 2016-12-21 09:46
@yifeif with our regular protobuf builds, is this now resolved?

**Comment by yifeif** [comment] 2016-12-21 18:26
Sorry this hasn't bump up the piles as it can be simply resolved by renaming the downloaded package tags to "cp3-none-any".

**Comment by yifeif** [comment] 2016-12-21 18:29
Actually just took a look at the downloading link on [install page ](https://www.tensorflow.org/get_started/os_setup#protobuf_library_related_issues), the binary is now named "protobuf-3.0.0-**cp35-cp35m**-linux_x86_64.whl", which should be a supported wheel name. Closing this issue. @hholst80 please feel free to re-open if it is still not working for you. Thanks!

**Closed by yifeif** 2016-12-21 18:29 UTC
Labels: awaiting googler
