### ISSUE TITLE
Runs regex filter doesn't work in tensorboard v1.1

### ISSUE THREAD

**Issue by rightaditya** [tensorflow/tensorflow#9519] opened 2017-04-28 18:57 UTC
### System information
- Custom code, worked fine on 1.0
- OS: Linux Ubuntu 16.04
- installed binary via pip3
- TensorFlow version v1.1.0-rc0-61-g1ec6ed5, 1.1.0
- CUDA v8.0, cuDNN v5.1
- GTX 1070, 8GB RAM
- To reproduce: run tensorboard, try to filter runs in web interface, nothing happens

### Problem description
Running tensorboard with v1.1 gives me the following warnings in the console (repeated four times) once the web interface is opened:

`WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404`

At first I ignored it, but it turns out that when examining the runs in the web interface, the regex filter for the runs doesn't work at all. This exact command in the exact same folder with the exact same logs worked without issue with v1.0.

**Comment by rightaditya** [comment] 2017-04-28 19:00
This warning was also referenced in #9382.

**Comment by aselle** [comment] 2017-04-28 20:32
@dandelionmane, could you place take a look. Thanks!

**Comment by braddengross** [comment] 2017-05-03 13:01
I'm seeing the same warnings and some major issues in viewing scalar data on tensorboard. I'm currently viewing tensorboard for 6 different training sessions all with different run id's. If I hide and show runs using the checkboxes the data will change for old runs that are no longer in progress. Also, some runs will show their data sometimes and others won't.

**Comment by nrishoj** [comment] 2017-05-03 19:23
Just upgraded from 1.0.1 to 1.1 and got the same issue.

Same setup as @rightaditya, except for GTX 1080.

Note, TensorBoard does seem to have problems finding the address (still available from localhost tho). Letting you know in case this issue is somehow connected with the warnings.

```
Starting TensorBoard b'47' at http://0.0.0.0:6007
(Press CTRL+C to quit)
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
```

**Comment by KangHsi** [comment] 2017-05-04 08:49
I got the same issue when I use the Google Cloud Platform with tensorflow version  1.10
I'm not sure, but the first time I use tensorboard, it works without the issue, and after that, tensor board cannot work properly at all.

`Starting TensorBoard 47 at http://0.0.0.0:8080
(Press CTRL+C to quit)
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404`

**Comment by foxik** [comment] 2017-05-05 08:37
BTW, duplicate of #9285.

**Comment by dandelionmane** [comment] 2017-05-05 18:25
Thanks for the report. Both of these issues are fixed at master, so they won't be present in the next release.

**Closed by dandelionmane** 2017-05-05 18:25 UTC
Labels: stat:awaiting tensorflower, type:bug/performance

**Comment by danieljl** [comment] 2017-05-07 03:01
@dandelionmane Can you mention the commit so it can be cherry-picked?

**Comment by astrung** [comment] 2017-06-13 09:13
hey, is this issue is fixed on master ? I have installed from pip, it is ok from local, but when i tried it with my domain and access from internet, i got same error

**Comment by astrung** [comment] 2017-06-14 02:26
hey, any feedback ?

**Comment by fventer** [comment] 2017-06-19 18:25
I have the same problem. runs regex works fine at localhost, but not when running on another host.

**Comment by dandelionmane** [comment] 2017-06-19 19:47
Please pip install the latest tensorboard via `pip install tensorflow-tensorboard`. If it's still happening, open an issue at https://github.com/tensorflow/tensorboard with precise reproduction steps
