### ISSUE TITLE
"no such package '@com_google_protobuf//'" while running "bazel test" (r1.13)

### ISSUE THREAD

**Issue by huljar** [tensorflow/tensorflow#25000] opened 2019-01-17 15:53 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- TensorFlow version: 1.13
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: created virtualenv for build process
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0.130 / 7.4.2.24
- GPU model and memory: Tesla P40 (inside virtual machine via Nvidia Virtual GPU), 8GB memory

**Describe the problem**
During the build process described on the tensorflow website for r1.13, the command `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...` fails due to not finding the package `'@com_google_protobuf//'`. The full error message is:
```
ERROR: /home/cgv/tensorflow/tensorflow/core/BUILD:255:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: no such package '@com_google_protobuf//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: Analysis of target '//tensorflow/core:example_protos' failed; build aborted: Analysis failed
```
If I use the switch `--incompatible_remove_native_http_archive=false` as the error message suggests, I receive different errors:
```
ERROR: /home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/BUILD:597:1: Traceback (most recent call last):
	File "/home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/BUILD", line 597
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/protobuf.bzl", line 266, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: /home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/cgv/.cache/bazel/_bazel_cgv/ad496aba49fed364b29fcfdc32e3267a/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows_msvc' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/cgv/tensorflow/tensorflow/core/BUILD:255:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//tensorflow/core:example_protos' failed; build aborted: Analysis failed
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Install `python3-dev` and other dependencies directly from Ubuntu via apt
2. Install `bazel` from repository https://storage.googleapis.com/bazel-apt via apt
3. Clone the r1.13 branch of TensorFlow via `git clone https://github.com/tensorflow/tensorflow.git --branch r1.13 --single-branch`
4. Create a virtual environment with `python3 -m venv tensorflow-build` and activate it
5. Install the remaining dependencies via pip as stated on https://www.tensorflow.org/install/source
`pip install -U --user pip six numpy wheel mock`
`pip install -U --user keras_applications==1.0.6 --no-deps`
`pip install -U --user keras_preprocessing==1.0.5 --no-deps`
6. run `./configure` in the cloned repo (full output in [configure.log](https://github.com/tensorflow/tensorflow/files/2769428/configure.log))
7. run `bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...`

Then after a few seconds of loading packages and analyzing (and a few deprecation warnings), the described error occurs.

Please let me know if I can provide any further information. Thanks!

**Comment by gunan** [comment] 2019-01-17 23:20
Looks like bazel 0.21.0 is not fully working with the protobuf repo we have.
I think @case540 ran into this before @meteorcloudy from bazel team to help route this problem.

**Comment by meteorcloudy** [comment] 2019-01-18 09:15
Yes, this is due to an incompatible change in 0.21.0, https://github.com/bazelbuild/bazel/issues/6570

You can [upgrade the protobuf version](https://github.com/tensorflow/tensorflow/commit/b0d7d8a477d3041e2d0ebd0cb1d35e4a7fa09663) or use an old version of Bazel (eg, 0.20.0)

**Comment by huljar** [comment] 2019-01-18 10:40
The protobuf version apparently was already set to 3.6.1.2 (I cloned branch r1.13). I have now downgraded to bazel 0.20.0, which seems to have fixed the issue that I had. Unfortunately, I get a different error now:
```
ERROR: /home/cgv/tensorflow/tensorflow/contrib/resampler/BUILD:103:1: in deps attribute of py_test rule //tensorflow/contrib/resampler:resampler_ops_xla_test_gpu: '//tensorflow/compiler/tf2xla/kernels:resampler_ops' does not have mandatory providers: 'py'. Since this rule was created by the macro 'tf_xla_py_test', the error might have been caused by the macro implementation in /home/cgv/tensorflow/tensorflow/compiler/tests/build_defs.bzl:94:20
ERROR: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted
```
I can open a new issue for this if you prefer that.

**Comment by meteorcloudy** [comment] 2019-01-18 11:16
I debugged a bit on this, looks like you also have to cherry-pick https://github.com/tensorflow/tensorflow/commit/8c22259497e9914c37a7adcd33aebaf754473a02 into r1.13

**Comment by meteorcloudy** [comment] 2019-01-18 11:20
It's quite annoying the error message didn't report where `com_google_protobuf` is defined @aehlig. In ./tensorflow/workspace.bzl it defines `com_google_protobuf` without using native `http_archive`, but the actual external repo comes from `rules_closure` transitively.

**Comment by huljar** [comment] 2019-01-18 11:39
I can confirm that cherry-picking 8c22259497e9914c37a7adcd33aebaf754473a02 fixes the protobuf issue with bazel 0.21.0. Thank you!

**Comment by jvishnuvardhan** [comment] 2019-01-18 18:21
@huljar 
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-01-18 18:21 UTC
Labels: 2.0, type:build/install

**Comment by wmcnally** [comment] 2019-01-18 18:24
@jvishnuvardhan I have same issue as @huljar.

> ERROR: /home/wmcnally/tensorflow/tensorflow/contrib/resampler/BUILD:103:1: in deps attribute of py_test rule //tensorflow/contrib/resampler:resampler_ops_xla_test_gpu: '//tensorflow/compiler/tf2xla/kernels:resampler_ops' does not have mandatory providers: 'py'. Since this rule was created by the macro 'tf_xla_py_test', the error might have been caused by the macro implementation in /home/wmcnally/tensorflow/tensorflow/compiler/tests/build_defs.bzl:96:20
ERROR: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted

I tried cherry-picking 8c22259 but it did not work (I'm very new to git so maybe I'm doing something wrong).

**Comment by christk1** [comment] 2019-01-20 20:56
> @jvishnuvardhan I have same issue as @huljar.
> 
> > ERROR: /home/wmcnally/tensorflow/tensorflow/contrib/resampler/BUILD:103:1: in deps attribute of py_test rule //tensorflow/contrib/resampler:resampler_ops_xla_test_gpu: '//tensorflow/compiler/tf2xla/kernels:resampler_ops' does not have mandatory providers: 'py'. Since this rule was created by the macro 'tf_xla_py_test', the error might have been caused by the macro implementation in /home/wmcnally/tensorflow/tensorflow/compiler/tests/build_defs.bzl:96:20
> > ERROR: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted
> 
> I tried cherry-picking [8c22259](https://github.com/tensorflow/tensorflow/commit/8c22259497e9914c37a7adcd33aebaf754473a02) but it did not work (I'm very new to git so maybe I'm doing something wrong).

download Bazel v 0.19.1 , apply cherry-pick and run tests.Worked for me.

**Comment by Habardeen** [comment] 2019-01-29 12:09
Same issue as @wmcnally here. 

`ERROR: /tensorflow/tensorflow/contrib/resampler/BUILD:103:1: in deps attribute of py_test rule //tensorflow/contrib/resampler:resampler_ops_xla_test_gpu: '//tensorflow/compiler/tf2xla/kernels:resampler_ops' does not have mandatory providers: 'py'. Since this rule was created by the macro 'tf_xla_py_test', the error might have been caused by the macro implementation in /tensorflow/tensorflow/compiler/tests/build_defs.bzl:96:20
ERROR: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted: Analysis of target '//tensorflow/contrib/resampler:resampler_ops_xla_test_gpu' failed; build aborted`

[8c22259](https://github.com/tensorflow/tensorflow/commit/8c22259497e9914c37a7adcd33aebaf754473a02) seems to be integrated in WORKPLACE as of today, but I got the same error as above running bazel 0.21. Also failed with bazel 0.22 and 0.20.

**Comment by scm-ns** [comment] 2019-01-29 21:05
I see the same issue.

**Comment by scm-ns** [comment] 2019-01-31 00:45
I solved it by removing the resampler from the BUILD file. That fixed the issue. Seems to be an issue in a BUILD file present in the resampler lib.

**Comment by peome** [comment] 2019-01-31 16:06
Same issue with bazel 0.21 and 0.22

**Comment by dmitryponv** [comment] 2019-08-15 18:41
This is ridiculous. I downgraded Bazel to 0.20 because of this issue, now it's giving me this error: 
https://github.com/grpc/grpc-web/issues/510 which is telling me to go upgrade bazel
This is the most widely used Machine Learnign API, CAN you please properly support C++ developers instead of catering to python
