### ISSUE TITLE
Issues with Eigen when building tf_tutorials_example_trainer on Windows 10

### ISSUE THREAD

**Issue by Katuali** [tensorflow/tensorflow#7374] opened 2017-02-09 02:23 UTC
I'm attempting to build Tensorflow C++ on Windows 10 following the instructions of the cmake readme. However, I'm getting issues with compiling at the Eigen step.

```Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio has expired.

The evaluation period for this product has ended.

Performing C++ SOURCE FILE Test COMPILER_SUPPORT_FASTMATH failed with the following output:
Change Dir: C:/Users/Irene/Documents/tensorflow/tensorflow/contrib/cmake/build/eigen/src/eigen-build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_70ffc.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 9/02/2017 3:13:30 PM.

Project "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_70ffc.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_70ffc.dir\Debug\".

  Creating directory "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_70ffc.dir\Debug\cmTC_70ffc.tlog\".

InitializeBuildStatus:

  Creating "cmTC_70ffc.dir\Debug\cmTC_70ffc.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W4 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_WARNINGS /D COMPILER_SUPPORT_FASTMATH /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_70ffc.dir\Debug\\" /Fd"cmTC_70ffc.dir\Debug\vc140.pdb" /Gd /TP /wd4127 /wd4505 /wd4714 /errorReport:queue  -ffast-math "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\src.cxx"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W4 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_WARNINGS /D COMPILER_SUPPORT_FASTMATH /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_70ffc.dir\Debug\\" /Fd"cmTC_70ffc.dir\Debug\vc140.pdb" /Gd /TP /wd4127 /wd4505 /wd4714 /errorReport:queue  -ffast-math "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\src.cxx"

  

cl : Command line warning D9002: ignoring unknown option '-ffast-math' [C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_70ffc.vcxproj]

  src.cxx

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\Debug\cmTC_70ffc.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/8i/Documents/tensorflow/tensorflow/contrib/cmake/build/eigen/src/eigen-build/CMakeFiles/CMakeTmp/Debug/cmTC_70ffc.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/8i/Documents/tensorflow/tensorflow/contrib/cmake/build/eigen/src/eigen-build/CMakeFiles/CMakeTmp/Debug/cmTC_70ffc.lib" /MACHINE:X64  /machine:x64 cmTC_70ffc.dir\Debug\src.obj

  cmTC_70ffc.vcxproj -> C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\Debug\cmTC_70ffc.exe

FinalizeBuildStatus:

  Deleting file "cmTC_70ffc.dir\Debug\cmTC_70ffc.tlog\unsuccessfulbuild".

  Touching "cmTC_70ffc.dir\Debug\cmTC_70ffc.tlog\cmTC_70ffc.lastbuildstate".

Done Building Project "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_70ffc.vcxproj" (default targets).



Build succeeded.



"C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_70ffc.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  cl : Command line warning D9002: ignoring unknown option '-ffast-math' [C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_70ffc.vcxproj]



    1 Warning(s)

    0 Error(s)



Time Elapsed 00:00:00.54


Source file was:
int main() { return 0; }
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/Irene/Documents/tensorflow/tensorflow/contrib/cmake/build/eigen/src/eigen-build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_55681.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 9/02/2017 3:13:37 PM.

Project "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_55681.dir\Debug\".

  Creating directory "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_55681.dir\Debug\cmTC_55681.tlog\".

InitializeBuildStatus:

  Creating "cmTC_55681.dir\Debug\cmTC_55681.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_55681.dir\Debug\\" /Fd"cmTC_55681.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_55681.dir\Debug\\" /Fd"cmTC_55681.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  

  CheckIncludeFile.c

C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj]

Done Building Project "C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.24
```

**Comment by ferrouswheel** [comment] 2017-02-09 02:54
The line with the error is:

`C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Irene\Documents\tensorflow\tensorflow\contrib\cmake\build\eigen\src\eigen-build\CMakeFiles\CMakeTmp\cmTC_55681.vcxproj]`

So I guess the question is why is eigen trying to include `pthread.h` on Windows?

I was able to reproduce this on my box, when previously (Dec 2016, commit 2531ebc0fe7fc96) it worked fine. However even that previously good commit no longer functions now. This suggests Eigen upstream has changed something to break the tensorflow cmake build.

**Comment by girving** [comment] 2017-02-09 16:38
@mrry `pthread.h` on Windows does seem anomalous.

**Comment by mrry** [comment] 2017-02-13 02:11
@Katuali and @ferrouswheel: What command are you using to start the build? Since Eigen is header-only, we shouldn't need to build anything for it, and our [CI is currently green](http://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/), so I suspect something is different in your configuration.

Also, @Katuali, I notice that MSBuild seems to be building in `Debug` configuration. For various reasons, we haven't been able to build on Windows in `Debug`, but you can instead try `Release` or `RelWithDebInfo` (if you need symbols).

**Comment by ferrouswheel** [comment] 2017-02-16 00:59
I tried `MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj` and `MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`. So definitely using `Release` configuration

Both result in the same issue. I've tried building master branch, tag v1.0.0, and an older commit. Which suggests this may be our environment somehow.

I've found the build log from the CI, so I'm going to try to track down where things diverge and report back here!

**Comment by mrry** [comment] 2017-02-16 01:03
That's weird! I can confirm that it builds correctly for me, in a fresh checkout. It's possible that the CMake build leaves some droppings behind (sadly, it's not hermetic like the Bazel build) and this could be causing the build to fail. Looking forward to hear what you find out....

**Comment by ferrouswheel** [comment] 2017-02-16 03:06
I've tracked this down to a Windows Boost distribution with a bad CMakeLists.txt. It would set `BOOST_ROOT` in the windows environment, and eigen would try and configure against it and then fail.

Sorry for the noise! Please feel free to close this.

**Comment by girving** [comment] 2017-02-16 16:10
@ferrouswheel That you for tracking it down!

**Closed by girving** 2017-02-16 16:10 UTC
Labels: stat:awaiting response, type:build/install

**Comment by mrry** [comment] 2017-02-16 16:59
@ferrouswheel Thanks for looking into this! I took a look at the Eigen CMakeLists, and it looks like we're doing more than we need to in the Eigen build—when in fact all we really need to do is copy some headers to the right location. The build testing is enabled by default, and attempts to pick up Boost. I'm not sure why it breaks, but we can at least avoid the problem in future by avoiding that part of the build.

**Comment by ferrouswheel** [comment] 2017-02-16 20:58
@mrry Nice - I'm glad our Boost hiccup will help speed up the tensorflow build :-)
