### ISSUE TITLE
Unable to import frozen graph with RMSProp

### ISSUE THREAD

**Issue by PumayHui** [tensorflow/tensorflow#17996] opened 2018-03-26 03:43 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:0.5.2
- **GCC/Compiler version (if compiling from source)**:5.3.0
- **CUDA/cuDNN version**:8/5
- **GPU model and memory**:GTX 1080Ti
- **Exact command to reproduce**:

### Describe the problem
 Some errors occured when loading the frozen graph:

`
ValueError: graph_def is invalid at node 'RMSProp/update_InceptionV1/Conv2d_1a_7x7/weights/ApplyRMSProp': Input tensor 'InceptionV1/Conv2d_1a_7x7/weights:0' Cannot convert a tensor of type float32 to an input of type float32_ref.
`

**Comment by asimshankar** [comment] 2018-03-26 22:07
Could you share some more details, specifically, steps to reproduce the problem?

**Comment by PumayHui** [comment] 2018-03-28 02:50
@asimshankar 
Thanks!
Command I get the pb file:
`
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=model.pbtxt --input_checkpoint=model.ckpt --input_binary=false --output_graph=frozen_model.pb --output_node_names=<more than 1000 nodes>
`
When I load the pb file, it occurs such errors as above.

**Comment by asimshankar** [comment] 2018-03-28 05:02
@PumayHui : Thanks, but I can't reproduce the problem without knowing what `model.pbtxt` is. How did you generate it? Or can you share the existing one?

It's possible there is a bug in freeze-graph, CCing @suharshs to take a look.
Instructions to reproduce will be helpful.

Thanks.

**Comment by asimshankar** [comment] 2018-03-28 05:10
I should also add: It seems that you're trying to freeze a graph where the path from inputs to outputs involves the RMSPropOptimizer kicking in.

Note that Optimizers change weights (variables) in a model. While "freeze_graph" is meant for "freezing" weights, i.e., converting all variables to constants. So, if the computation involves changing weights, the graph cannot be frozen.

Are you trying to apply "freeze graph" to a training step or something?

**Comment by asimshankar** [comment] 2018-04-07 01:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2018-04-07 01:41 UTC
Labels: stat:awaiting response
