### ISSUE TITLE
Android tensorflow lite kernel_util.cc:34 input_product_scale < output_scale

### ISSUE THREAD

**Issue by weiting4802** [tensorflow/tensorflow#19607] opened 2018-05-29 03:32 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:1.8
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
1.I retrained and quantized the openpose model(add tf.contrib.quantize.create_training_graph() in my code）

2.Generate .pb (add tf.contrib.quantize.create_eval_graph() in my code) 

3.Then, I converted my own pb model to lite.
It was succeed,the command:

./bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_file=models/freeze/frozen_q_256.pb \
  --output_file=tf_files/lite/frozen_q_256.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --input_array=image \
  --input_shape=1,256,256,3\
  --output_array=Openpose/concat_stage7 \
  --std_value=127.5 \
  --mean_value=127.5 \

4.But when I put it on android, I got an error.

### Source code / logs
ava.lang.NullPointerException: Can not allocate memory for the given inputs: tensorflow/contrib/lite/kernels/kernel_util.cc:34 input_product_scale < output_scale was not true.
                                                                                  at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
                                                                                  at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:95)
                                                                                  at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
                                                                                  at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                                                                                  at com.asus.android.poseestimator.ImageClassifier.classifyFrame(ImageClassifier.java:167)
                                                                                  at com.asus.android.poseestimator.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:740)
                                                                                  at com.asus.android.poseestimator.Camera2BasicFragment.access$1000(Camera2BasicFragment.java:74)
                                                                                  at com.asus.android.poseestimator.Camera2BasicFragment$5.run(Camera2BasicFragment.java:621)
                                                                                  at android.os.Handler.handleCallback(Handler.java:836)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                  at android.os.Looper.loop(Looper.java:208)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

my tensorflow lite version is 0.1.1. Does this version support qauntized lite??
How can I solve this problem?

**Comment by suharshs** [comment] 2018-05-30 06:29
this may be resolved in the latest version of TensorFlow Lite, but to be sure, could you provide me the your graph.pbtxt. In particular I would like to figure out what the culprit TFLite operation is. Thanks.

**Comment by weiting4802** [comment] 2018-05-30 08:13
Thanks for your reply.  I changed version to tensorflow 0.1.7, but a new error occurred.

Logs:
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.asus.android.poseestimator/com.asus.android.poseestimator.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter

**Comment by MistLiao** [comment] 2018-05-31 03:52
it looks like same issue as
https://github.com/tensorflow/tensorflow/issues/19372

**Comment by MistLiao** [comment] 2018-05-31 16:44
@suharshs The issue should be caused by the operator CONCATENATION when quantization:

`

127 | [340, 370, 13] | [433] | {'axis': 3, 'fused_activation_function': 'NONE'} | CONCATENATION (opcode=1)

340 | Openpose/MConv_Stage5_L1_5_pointwise/add_fold | UINT8 | [1, 32, 32, 38] | 347 | {'min': [-1.05201], 'max': [6.00753], 'scale': [0.027684], 'zero_point': [38]}
371 | Openpose/MConv_Stage5_L2_5_pointwise/weights_quant/FakeQuantWithMinMaxVars | UINT8 | [19, 1, 1, 64] | 139 | {'min': [-9.128201], 'max': [9.394188], 'scale': [0.072637], 'zero_point': [126]}
13 | MobilenetV1/Conv2d_11_pointwise/Relu6 | UINT8 | [1, 32, 32, 256] | 240 | {'min': [-1.05201], 'max': [6.00753], 'scale': [0.027684], 'zero_point': [38]}

the warning message when do Toco convert:
2018-05-29 12:09:56.228183: W tensorflow/contrib/lite/toco/graph_transformations/hardcode_min_max.cc:105] Tweaking the MinMax of array Openpose/MConv_Stage1_L2_5_pointwise/add_fold, which is an input to {Concatenation operator with output Openpose/MConv_Stage2_concat}, because we want all inputs and outputs of a Concatenation operator to have the same MinMax so that it can be implemented as a pure byte-copy, no arithmetic.

any suggestions?











`

**Comment by suharshs** [comment] 2018-05-31 17:44
Thanks for the extra info. This may be a recent issue we found and fixed. The issue has to do with TOCO trying to guarantee that the input and output scales of Concatentation operations match. This may be resolved by providing `--change_concat_input_ranges=false` to your commandline TOCO invocation. 

Please let me know if that doesn't help. Thanks!

**Comment by MistLiao** [comment] 2018-06-01 01:46
Still not work. It still fails when load tflite file.
The Interpreter fail to execute AllocateTensors
 Caused by: java.lang.NullPointerException: Can not allocate memory for the interpreter
                      at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
                      at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
                      at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
                      at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:90)
                      at com.asus.android.poseestimator.ImageClassifier.<init>(ImageClassifier.java:117)

I try to skip the Concatentation when call tf.contrib.quantize.create_eval_graph() and it can load successfully.

Any other solution?

Thanks.

**Comment by 1icas** [comment] 2018-06-01 03:19
waiting for solve this issue : )

**Comment by tensorflowbutler** [comment] 2018-06-15 18:40
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-30 18:33
Nagging Assignee @suharshs: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hellottt20012001** [comment] 2018-07-03 09:24
I have met the same problem when I load openpose quantized model to Android.
`     Caused by: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/pooling.cc:104 input->params.scale != output->params.scale (3 != 3)
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:52)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)`
How can I solve it?
Thanks.

**Comment by raghuraman-k** [comment] 2018-07-18 23:43
Can you explain the issue more clearly and provide an example to reproduce the problem?
Thanks,

**Comment by tensorflowbutler** [comment] 2018-08-02 19:07
Nagging Assignee @liyunlu0618: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by liyunlu0618** [comment] 2018-08-09 21:25
Can you try and see if this issue persists with the most recent release? If so can you provide a openpose quantized model for me to reproduce? Thanks!

**Comment by tofulawrence** [comment] 2018-08-24 20:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tofulawrence** 2018-08-24 20:11 UTC
Labels: comp:lite

**Comment by tensorflowbutler** [comment] 2018-08-24 21:52
Nagging Assignee @liyunlu0618: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
