### ISSUE TITLE
Installation failed of C API on Ubuntu

### ISSUE THREAD

**Issue by slargo-IT** [tensorflow/tensorflow#24807] opened 2019-01-09 16:45 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:/
- TensorFlow installed from (source or binary): Tensorflow C API
- TensorFlow version: Latest
- Python version:
- Installed using virtualenv? pip? conda?:No
- Bazel version (if compiling from source):/
- GCC/Compiler version (if compiling from source): Update
- CUDA/cuDNN version: NaN
- GPU model and memory: NaN

**THE GUIDE IS NOT COMPLETE / THAT IS NOT WORKING*

**TF_VERSION ISN'T RECOGNIZE AS A FUNCTION**

**LOVE**

**Comment by jvishnuvardhan** [comment] 2019-01-16 18:57
@slargo-IT Please provide as many details as possible to find the root cause of the issue. Which TF version you are installing? what was the steps/commands you have used for installation? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-01-28 23:55
@slargo-IT Please provide more details as requested. Also, try these [suggestions](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and let us know the status. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-02-06 17:19
I think it might have been resolved. I am closing the issue. Please open new ticket if you see similar issue again. Thanks!

**Closed by jvishnuvardhan** 2019-02-06 17:19 UTC
Labels: stat:awaiting response, type:build/install
