### ISSUE TITLE
Performance Issue in C# Example

### ISSUE THREAD

**Issue by ys10** [tensorflow/tensorflow#31527] opened 2019-08-12 06:11 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): use code in TF# demo
- OS Platform and Distribution: **Windows 10**
- TensorFlow installed from (source or binary): **source(by pip)**
- TensorFlow version (use command below): **1.13**
- Python version: **3.7**
- CUDA/cuDNN version: run on **CPU**

**Describe the current behavior**
I implemented a Griffin-Lim algorithm(GL, a speech processing method used for reconstructing wave from mel-spectrogram) with TF-python, and dump it into a pb file.
Then I load graph of Griffin-Lim from the pb file, and using runner.Run() to call the computing graph and get the output of the last Node.

The result of output is correct and the voice quality is on par with TF-python generated.
But runner.Run() in TF# runs 5-10 times slower than session.Run() in TF-python.
For example, to generate a 3 seconds wave, runner.Run() in TF# need about 2.7 seconds, but session.Run() in TF-python only need 0.3-0.6 seconds.

here are the generate key codes in C#:

            TFTensor input = new TFTensor(melSpectrum);
            var runner = this.session.GetRunner();
            runner.AddInput(this.input, input);
            runner.Fetch(this.output);
            TFTensor[] results = runner.Run();

I went back and checked the related code I call runner.Run().

1. I have already kept a TFSession instant.
2. When I initialize the session & graph, I also warm up them by faking a melSpectrum and calling upper codes. If sess& graph weren't warmed up, runner.Run() will cost 6.8-7seconds to generate a 3 seconds wav.

**Describe the expected behavior**
I think runner.Run() in TF# should run as fast as session.Run() in TF-python

Any clues?
Thanks

**Comment by oanush** [comment] 2019-08-13 06:40
@ys10 ,
In order to expedite the trouble-shooting process, please provide compelete code snippet to reproduce the issue reported here. Thanks!

**Comment by oanush** [comment] 2019-08-20 09:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-20 09:46 UTC
Labels: comp:apis, stat:awaiting response, type:performance
