### ISSUE TITLE
tensorflow cannot launch operator: NormalizeWithDimensions

### ISSUE THREAD

**Issue by Adopteruf** [tensorflow/tensorflow#24725] opened 2019-01-06 08:45 UTC
2019-01-06 03:31:37.602215: E tensorflow/stream_executor/cuda/cuda_dnn.cc:4063] failed to run cudnnLRNCrossChannelForward
Traceback (most recent call last):
  File "main_segnet.py", line 124, in <module>
    main()
  File "main_segnet.py", line 119, in main
    segnet_solver.train()
  File "/home/jingwei/RA_XJTLU__10_12_2018_to_2_28_2019/KTF/scripts/Segmentation_Nets/Seg_net/solver_segnet.py", line 188, in train
    _, loss, cur_lr = sess.run([self.train_op, self.net.Loss, self.lr_node], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: NormalizeWithDimensions launch failed
	 [[Node: norm1 = LRN[T=DT_FLOAT, alpha=0.0001, beta=0.75, bias=1, depth_radius=5, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_x_0_3/_87)]]

Caused by op u'norm1', defined at:
  File "main_segnet.py", line 124, in <module>
    main()
  File "main_segnet.py", line 91, in main
    is_bw_loss=False)
  File "/home/jingwei/RA_XJTLU__10_12_2018_to_2_28_2019/KTF/scripts/Segmentation_Nets/Seg_net/model_segnet.py", line 56, in __init__
    phase_train=self.phase_train)
  File "/home/jingwei/RA_XJTLU__10_12_2018_to_2_28_2019/KTF/scripts/Segmentation_Nets/Seg_net/layers_segnet.py", line 207, in inference
    norm1 = tf.nn.lrn(images, depth_radius=5, bias=1.0, alpha=0.0001, beta=0.75, name='norm1')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 4380, in lrn
    beta=beta, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): NormalizeWithDimensions launch failed
	 [[Node: norm1 = LRN[T=DT_FLOAT, alpha=0.0001, beta=0.75, bias=1, depth_radius=5, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_x_0_3/_87)]]

This bug happens in GTX2080ti only. Tensorflow works fine in GTX1080ti.
I try to upgrade the version of tensorflow from 1.5.0 to 1.9.0 but it does not help.
My operating system is Ubuntu 18.04.

**Comment by ymodak** [comment] 2019-01-07 20:50
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Adopteruf** [comment] 2019-01-09 14:52
Issues happen when run a operator in tensorflow on GTX2080ti.
I get this issues done through just assigning the operator on CPU.

**Comment by ymodak** [comment] 2019-01-18 00:58
@Adopteruf  What is the cuda version you are using? @samikama Do you think it can be related possibly cuda version?Thanks!

**Comment by ymodak** [comment] 2019-01-24 21:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-01-24 21:26 UTC
Labels: comp:gpu, stat:awaiting response
