### ISSUE TITLE
ValueError: sequence_length must be a vector of length batch_size, but saw shape: (24, 1, 2)

### ISSUE THREAD

**Issue by tayyabvohra** [tensorflow/tensorflow#22969] opened 2018-10-14 10:24 UTC
import tensorflow as tf

I am working with lstm using tensor flow when I am running the code it is showing me the error. the code is running fine but when I am running the function tf.nn.dynamic_rnn(lstmCell, data, dtype=tf.float64) it is showing Value ERROR

wordsList = np.load('urduwords.npy')
wordVectors = np.load('urduwordsMatrix.npy')

batchSize = 24
lstmUnits = 64
numClasses = 2
iterations = 10000

tf.reset_default_graph()

labels = tf.placeholder(tf.float32, [batchSize, numClasses])
input_data = tf.placeholder(tf.int32, [batchSize, maxSeqLength])

print(labels)

data = tf.Variable(tf.zeros([batchSize, maxSeqLength, numDimensions]),dtype=tf.float32)
print(data)

data = tf.nn.embedding_lookup(wordVectors,input_data)
print(data)

lstmCell = tf.contrib.rnn.BasicLSTMCell(lstmUnits)
lstmCell = tf.contrib.rnn.DropoutWrapper(cell=lstmCell, output_keep_prob=0.1)

value, _ = tf.nn.dynamic_rnn(lstmCell, data, dtype=tf.float64)

data_mask = tf.cast(data, tf.bool)
data_len = tf.reduce_sum(tf.cast(data_mask, tf.float32), axis=1)
tf.nn.dynamic_rnn(lstmCell, data, sequence_length=data_len, initial_state=initial_state)

sequence_length must be a vector of length batch_size, but saw shape: (24, 1, 2)

**Comment by tensorflowbutler** [comment] 2018-10-14 18:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tayyabvohra** [comment] 2018-10-22 15:04
this is the shape of data when i am running  tf.nn.embedding_lookup(wordVectors,input_data) and the ouput i get 

Tensor("embedding_lookup:0", shape=(24, 30, 1, 2), dtype=int32)

**Comment by tayyabvohra** [comment] 2018-10-22 15:07
this is the shape of wordVectors array

[[[    0     1]]

 [[    1     1]]

 [[    2     1]]

 ...

 [[14784     1]]

 [[14784     1]]

 [[11095     1]]]

**Comment by tayyabvohra** [comment] 2018-10-24 14:49
any help from anyone @harshini-gadige  @tensorflowbutler

**Comment by yifeif** [comment] 2018-10-24 18:08
@tayyabvohra, you might want to double check the shape of the wordVectors loaded. Looks like it might have an extra dimension.
This issue is more suitable for stackoverflow, so I'm going to go ahead and close it. Let us know if you run into any bug or usability issue in the code. Thanks!

**Closed by yifeif** 2018-10-24 18:08 UTC
Labels: comp:ops, type:bug/performance
