### ISSUE TITLE
conv2d_transpose param tensor shapes after loading the model differ (NCHW format)

### ISSUE THREAD

**Issue by kassemyu** [tensorflow/tensorflow#30178] opened 2019-06-26 15:04 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 16.04
- Mobile device: Not tested
- TensorFlow installed from: binary
- TensorFlow version: 1.13.1
- Python version: 3.7.3
- Bazel version:
- GCC/Compiler version:
- CUDA/cuDNN version: 10.0/7.3.1
- GPU model and memory: Nvidia, driver 418.56, 11178MiB

**Describe the current behavior**
When training a model which contains conv2d_transpose layers (using the NCHW format), the last 2 dimensions of the layers weight tensor swap when reloading the model. 

Example: 
- after building the model: transpose_layer1 has the weight tensor (3, 3, 63, 61)
- when reloading the model: transpose_layer1 has the weight tensor (3, 3, 61, 63)

After swapping the two dimensions via numpys transpose method the shape (3, 3, 63, 61) is restored and the model successfully trains.

**Describe the expected behavior**
The expected behaviour would be that the last 2 dimensions don't swap which is the case for all conv2d layers. This occurs only in the conv2d_transpose layers.

**Setup to reproduce the issue**
The minimum is a small model which has a conv2d_transpose layer in it in which the last two dimensions differ from each other. After training it on GPU with NCHW data format the described behaviour occurs.

**Comment by gadagashwini** [comment] 2019-06-27 06:20
@kassemyu In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-07-03 05:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-03 05:06 UTC
Labels: TF 1.13, comp:apis, stat:awaiting response, type:support

**Comment by kassemyu** [comment] 2019-07-28 18:23
Hey, sorry for the long wait. 

Here is a small code snippet for reproduction. Please set the breakpoint at the last `print(...)` and evaluate the shapes-dictionary. You will see that 'conv1' has the kernel shape (3, 3, 1, 32), indicating that 1 is the depth/number of channels for the input. 
32 is the number of filters/outputs/feature maps. 

If you look at the conv2d_transposed layer 'up1' the number of outputs is set to 16 but the kernel shape is (3,3,16,32) indicating that the input dimensions are 16 even though they are 32 from the conv2d layer 'conv3' preceding it. I believe that this shape should instead be (3,3,32,16) because the number of outputs for the conv2d_transposed layer is set to 16. This would then behave the same way conv2d layers are at the moment.

Can you please take a look at this behaviour?

So far I have experienced this in tf 1.12 and 1.13.

With kind regards,
Yussuf

```
import tensorflow as tf
import tensorflow.contrib.layers as layers


from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
train_X = mnist.train.images
train_Y = mnist.train.labels
test_X = mnist.test.images


def shapes_of_built_model(layer_names):
    layer_names_and_shapes = {}
    for name in layer_names:
        layer_names_and_shapes[name] = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope=name)[0].shape
    return layer_names_and_shapes


def model(inputs_):
    # Encoder
    conv1 = layers.conv2d(inputs_, num_outputs=32, kernel_size=(3, 3), scope='conv1')
    conv_str2 = layers.conv2d(conv1, num_outputs=32, kernel_size=(3, 3), stride=2, scope='conv_str2')
    conv2 = layers.conv2d(conv_str2, num_outputs=32, kernel_size=(3, 3), scope='conv2')
    encoded = layers.conv2d(conv2, num_outputs=32, kernel_size=(3, 3), stride=2, scope='encoding')

    conv3 = layers.conv2d(encoded, num_outputs=32, kernel_size=(3, 3), scope='conv3')
    upsample1 = layers.conv2d_transpose(conv3, num_outputs=16, kernel_size=3, stride=2, scope='up1')
    upsample2 = layers.conv2d_transpose(upsample1, num_outputs=32, kernel_size=3,  stride=2, scope='up2')
    logits = layers.conv2d(upsample2, num_outputs=1, kernel_size=(3, 3),  scope='logits', padding='SAME')
    decoded = tf.sigmoid(logits, name='reconstruct')
    return decoded


with tf.name_scope('Input'):
    x = tf.placeholder(tf.float32, shape=[None, 28, 28, 1], name='X')
    y = tf.placeholder(tf.float32, shape=[None, 28, 28, 1], name='Y')

output_logits = model(x)

with tf.variable_scope('Train'):
    with tf.variable_scope('Loss'):
        loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=output_logits), name='loss')
    tf.summary.scalar('loss', loss)
    with tf.variable_scope('Optimizer'):
        optimizer = tf.train.AdamOptimizer(learning_rate=0.05, name='Adam-op')
        optimizer = optimizer.minimize(loss)
    with tf.variable_scope('Accuracy'):
        correct_prediction = tf.equal(tf.argmax(output_logits, 1), tf.argmax(y, 1), name='correct_pred')
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32), name='accuracy')
    tf.summary.scalar('accuracy', accuracy)
    with tf.variable_scope('Prediction'):
        cls_prediction = tf.argmax(output_logits, axis=1, name='predictions')


init = tf.global_variables_initializer()
merged = tf.summary.merge_all()
sess = tf.InteractiveSession()
sess.run(init)

names = ['conv1', 'conv_str2', 'conv2', 'encoding', 'conv3', 'up1', 'up2']
shapes = shapes_of_built_model(names)
print('set breakpoint here')
```

**Comment by kassemyu** [comment] 2019-07-28 18:34
> @kassemyu In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

I supplied some code and apologise for the long wait.

**Comment by kassemyu** [comment] 2019-07-31 10:32
This issue is continued at: https://github.com/tensorflow/tensorflow/issues/31192
