### ISSUE TITLE
Bug: ProtoBuf tokenizer crashes when loading single_image_random_dot_stereograms OP

### ISSUE THREAD

**Issue by MaximilianKoestler** [tensorflow/tensorflow#10370] opened 2017-06-01 12:55 UTC
### System information
- No custom code
- Ubuntu 17.04 (also confirmed on 16.04)
- TensorFlow installed from source
- TensorFlow version: v1.2.0-rc0-486-g95d90ab2e 1.2.0-rc1
- Bazel version: 0.5.0
- Python version: 3.5.3 (also confirmed on 2.7.12):
- Not tested with GPU support:

Reproduction
------------------

    import tensorflow as tf
    regressor = tf.contrib.learn.LinearRegressor(feature_columns=[])

Alternative:

    import keras

Reference: [Stackoverflow](https://stackoverflow.com/questions/44291072/google-protobuf-text-format-parseerror-when-instantiating-a-tensorflow-model-wit)

Manifestation of the error
---------------------------------

The first method to reproduce should cause an assert due to the empty `feature_columns`.
Instead, the protobuf tokenizer crashes with:

> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
>    module = self._load()
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
>    module = importlib.import_module(self.__name__)
>  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
>  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 35, in <module>
>    from tensorflow.contrib import image
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/image/__init__.py", line 40, in <module>
>    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 26, in <module>
>    "_single_image_random_dot_stereograms.so"))
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
>    ret = load_library.load_op_library(path)
>  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 84, in load_op_library
>    exec(wrappers, module.__dict__)
>  File "<string>", line 248, in <module>
>  File "<string>", line 114, in _InitOpDefLibrary
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 481, in Merge
>    descriptor_pool=descriptor_pool)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 535, in MergeLines
>    return parser.MergeLines(lines, message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 568, in MergeLines
>    self._ParseOrMerge(lines, message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 583, in _ParseOrMerge
>    self._MergeField(tokenizer, message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 684, in _MergeField
>    merger(tokenizer, message, field)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 773, in _MergeMessageField
>    self._MergeField(tokenizer, sub_message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 684, in _MergeField
>    merger(tokenizer, message, field)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 773, in _MergeMessageField
>    self._MergeField(tokenizer, sub_message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 684, in _MergeField
>    merger(tokenizer, message, field)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 773, in _MergeMessageField
>    self._MergeField(tokenizer, sub_message)
>  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 652, in _MergeField
>    (message_descriptor.full_name, name))
>google.protobuf.text_format.ParseError: 48:12 : Message type "tensorflow.AttrValue" has no field named "5".

What causes this exception?
--------------------------------------

The problem is the information extracted from the `_single_image_random_dot_stereograms.so` library file from `/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/image/python/ops/`
This file contains encoded information passed to protobuf.

The problem occurs when a line with a `float` default is parsed.

In this case, it is the sequence

    eye_separation: float = 2.5

at offset *0xa3b4* in `emphasized _single_image_random_dot_stereograms.so`

Somehow, the parser replaces decimal points with commas. In the end, this is created:

    attr {\n'
      name: "eye_separation"\n'
      type: "float"\n'
      default_value {\n'
        f: 2,5\n'
      }\n'
    }\n'

The tokenizer (at `google/protobuf/text_format.py`) gets confused by the `,` in the default value and thinks that `5` is a separate field.

Root of the error
---------------------

The error occurs during the execution of [load_library.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/load_library.py#L72).

    op_list_str = py_tf.TF_GetOpList(lib_handle)
    op_list = op_def_pb2.OpList()
    op_list.ParseFromString(compat.as_bytes(op_list_str))
    wrappers = py_tf.GetPythonWrappers(op_list_str)

`op_list` contains the correct default value of `2.5`, whereas `wrappers`, the wrapped list returned from [python_op_gen.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/python_op_gen.cc#L762) contains a `2,5`.

This is what `GetPythonWrappers` does:

    string GetPythonWrappers(const char* op_list_buf, size_t op_list_len) {
      string op_list_str(op_list_buf, op_list_len);
      OpList ops;
      ops.ParseFromString(op_list_str);
      return GetPythonOps(ops, {}, false);
    }

The appended files include the contents of the `op_list` and the `wrappers` variable:
[op_list.txt](https://github.com/tensorflow/tensorflow/files/1044775/op_list.txt)
[wrapper.txt](https://github.com/tensorflow/tensorflow/files/1044777/wrapper.txt)

**Comment by jart** [comment] 2017-06-01 21:52
@josh11b has been doing some work on these pbtxt op definitions. Any idea why periods would get replaced with commas?

**Comment by josh11b** [comment] 2017-06-02 00:51
I'm going to have to defer to @cwhipkey for this one.

**Comment by cwhipkey** [comment] 2017-06-02 01:33
my guess is that a localization setting on the machine is set to use comma as the decimal separator.  We are probably using a locale-specific function to re-serialize the floating point value.

Is that possibly what is happening on your machine?  If so, I can track down which proto-text serialization is doing this and try to fix it there.

**Comment by cwhipkey** [comment] 2017-06-02 02:40
I think that is probably the cause - appending uses AppendNumeric in proto_text_util.h, which calls StrCat() on the value.  This ends up calling FloatToBuffer, which looks like it uses locale-specific snprintf for printing.

**Comment by MxKy** [comment] 2017-06-02 05:50
@cwhipkey
I can confirm that changing the decimal separator in my locale settings resolved the problem.

**Comment by Mazecreator** [comment] 2017-06-02 14:51
Let me know if you think there is something that I can correct in  _single_image_random_dot_stereograms but it seems like this is outside of that Op at the moment.

**Comment by NatLun091238** [comment] 2017-08-25 09:21
I got the same problem with import tensorflow.contrib.keras as K resulting in identical error message as being reported here. 
System and related details:
Linux Mint 18.2; TF r1.2; Python 3.6

And indeed changing the decimal separator made everything work as it supposed.
1/ edit locale file located /usr/share/i18n/locales/
 ```
LC_NUMERIC
decimal_point   "<U002E>"
thousands_sep   "<U002C>"
grouping        3;3
END LC_NUMERIC
```
2/ sudo locale-gen
3/ reboot computer and check:
`locale -k LC_NUMERIC`

**Comment by tensorflowbutler** [comment] 2018-01-04 19:15
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:28
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:03
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:14
Nagging Assignee @cwhipkey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:36
Nagging Assignee @cwhipkey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:36
Nagging Assignee @cwhipkey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:07
Nagging Assignee @cwhipkey: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:05
Nagging Assignee @cwhipkey: It has been 274 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cwhipkey** [comment] 2018-05-29 03:51
Changing assignee for triaging.

**Comment by tensorflowbutler** [comment] 2018-06-12 19:12
Nagging Assignee @josh11b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by josh11b** [comment] 2018-06-13 15:59
This seems like a real bug, we should be using a numeric serialization that will round trip independent of the locale settings.

**Comment by tensorflowbutler** [comment] 2018-06-28 12:36
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-13 18:56
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-28 18:48
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:51
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:52
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:31
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:42
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:43
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:38
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-11-14 18:56
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by yongtang** [comment] 2018-11-17 19:38
@MaximilianKoestler I had a PR #22044 which might have fixed the issue you encounter. The PR has been merged into the master. I think this issue could be closed, but feel free to reopen if the issue still exists.

**Closed by yongtang** 2018-11-17 19:38 UTC
Labels: stat:contributions welcome
