### ISSUE TITLE
Possible incorrect implementation of inception_v3.py

### ISSUE THREAD

**Issue by colt18** [tensorflow/tensorflow#36262] opened 2020-01-27 20:54 UTC
"Mixed 0" between lines 138-152 is the implementation of the figure 5 in the paper. There should be 4 branches that does and have the layer name as :

branch 1x1 = 1x1 conv
branch pool = pooling + 1x1 conv
branch 3x3 = 1x1 conv + 3x3 conv
branch 5x5 = 1x1 conv + 3x3 conv +3x3 conv

The last one is is named as branch3x3dbl in the implementation and its fine doing two 3x3 convs to substitute 5x5 conv, but what should be branch 3x3 is named as branch 5x5 and involves a 5x5 convolution which contradicts the paper. So lines 140 and 141 should be rewritten as:
```
  branch3x3 = conv2d_bn(x, 48, 1, 1)
  branch3x3 = conv2d_bn(branch3x3, 64, 3, 3)  
```

This is not limited to this section and followup codes have the same wrong implementations. I think it should be taken care of. The idea of avoiding bigger convolutions is the main point of this paper and 5x5 convolutions are taking part in the code regardless of this fact.

**Comment by ravikyram** [comment] 2020-01-28 13:18
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Please, provide simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by colt18** [comment] 2020-01-28 19:09
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (Windown 10-64 bit):
- TensorFlow installed from (source or binary): binary from conda
- TensorFlow version (use command below): 2.0
- Python version: 3.7
- CUDA/cuDNN version: 
- GPU model and memory: GTX 1070

**Describe the current behavior**
"Mixed 0" between lines 138-152 is the implementation of the figure 5 in the paper. There should be 4 branches that does and have the layer name as :

branch 1x1 = 1x1 conv
branch pool = pooling + 1x1 conv
branch 3x3 = 1x1 conv + 3x3 conv
branch 5x5 = 1x1 conv + 3x3 conv +3x3 conv

The last one is is named as branch3x3dbl in the implementation and its fine doing two 3x3 convs to substitute 5x5 conv, but what should be branch 3x3 is named as branch 5x5 and involves a 5x5 convolution which contradicts the paper. So lines 140 and 141 should be rewritten as:

```

  branch3x3 = conv2d_bn(x, 48, 1, 1)
  branch3x3 = conv2d_bn(branch3x3, 64, 3, 3) 
```

This is not limited to this section and followup codes have the same wrong implementations. I think it should be taken care of. The idea of avoiding bigger convolutions is the main point of this paper and 5x5 convolutions are taking part in the code regardless of this fact.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-01-29 09:11
@colt18 
Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment] 2020-02-10 11:59
@colt18 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-02-20 10:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-20 10:42 UTC
Labels: TF 2.0, stat:awaiting response, type:support
