### ISSUE TITLE
Wav to Spectogram wrong expected height

### ISSUE THREAD

**Issue by rychnal** [tensorflow/tensorflow#22838] opened 2018-10-09 13:37 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: pip install tensorflow
- **TensorFlow version (use command below)**:1.11.0
- **Python version**: 2.7.15rc1
- **Bazel version (if compiling from source)**: 0.17.2
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram -- --input_wav=/home/lukas/Downloads/music.wav --output_image=/home/lukas/Downloads/spectrogram.png

### Describe the problem
Hi I have problem with build this example from tensorflow guide.
 bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram 
I get error "Expected height 18711 but got 18712" 
I tried three differenr wav files and got same error with different height. "Expected height x but got x + 1"
When I tried with default image spectrogram_test_data/short_test_segment.wav so it works good 

### Source code / logs
bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram -- --input_wav=/home/lukas/Downloads/music.wav --output_image=/home/lukas/Downloads/spectrogram.png
INFO: Analysed target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (65 packages loaded).
INFO: Found 1 target...
Target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram up-to-date:
  bazel-bin/tensorflow/examples/wav_to_spectrogram/wav_to_spectrogram
INFO: Elapsed time: 149.081s, Critical Path: 4.61s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorflow/examples/wav_to_spectrogram/wav_to_spectrogram '--input_wav=/home/lukas/Downloads/music.wav' INFO: Build completed successfully, 1 total action
2018-10-09 17:44:25.818539: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-10-09 17:44:26.909131: E tensorflow/examples/wav_to_spectrogram/main.cc:61] WavToSpectrogram failed with Invalid argument: Spectrogram size calculation failed: Expected height 18711 but got 18712
   [[Node: spectrogram = AudioSpectrogram[magnitude_squared=false, stride=128, window_size=256, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wav_decoder)]]

**Comment by ymodak** [comment] 2018-10-12 01:17
Were you able to execute the [Spectrogram example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/wav_to_spectrogram#tensorflow-spectrogram-example) successfully?

**Comment by rychnal** [comment] 2018-10-12 07:41
Yes, i get spectogram for default image  spectrogram_test_data/short_test_segment.wav from repository . Can I sent the file which is problem ?

BTW in options example is mistake. window -> window_size

**Comment by ymodak** [comment] 2018-10-12 16:34
Thanks for catching the mistake in example. Yes please send a sample audio file. Also did you try writing the spectrogram image by changing window_size and stride?

**Comment by rychnal** [comment] 2018-10-14 02:49
I tried change window_size and stride get same error sometimes with +X height, sometimes with -X height
[music.zip](https://github.com/tensorflow/tensorflow/files/2476050/music.zip)

**Comment by ymodak** [comment] 2018-10-23 04:07
The error arises from this line in [spectrogram_op.cc](https://github.com/tensorflow/tensorflow/blob/57d31b5a9ad9ddb9434796b6253decabda61a972/tensorflow/core/kernels/spectrogram_op.cc#L87) . But not sure what should be the correct window_size and stride. Assigning to pete for more insights on this.

**Comment by tensorflowbutler** [comment] 2018-11-06 18:55
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-21 18:57
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-06 18:57
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment] 2019-02-23 00:05
The wav_to_spectrogram tool is only designed to be a debugging tool, so this hasn't made it onto our priority list to fix yet. I'm adding this to contributions welcome.

**Comment by astropeak** [comment] 2019-04-28 01:04
Hey, I'd like to take a crack at this! Is that alright?

**Comment by astropeak** [comment] 2019-05-13 14:26
I found the root cause. The AudioSpectrogramOp only works for one channel wav files. For a two channel wav file(as the above attached one), the problem would happen, because the 'samples_to_next_step_' in spectrogram.cc won't be initialized correctly when processing the second channel.

After initializing the 'samples_to_next_step_' correctly, the unmatching height problem disappears. But I met another problem about the dimension of the output of the AudioSpectrogramOp.

The output dimension of the AudioSpectrogramOp is (channel_count, height, width), but the encode_png op requires a dimension of (height, width, channel_count).  In wave_to_spectrogram.cc, the dimension conversion is done by first expand_dims at the end and then squeeze at axis 0. But this only works when channel_count equals to 1.

So my question is how to convert a tensor's dimension from (channel_count, height, width) to (height, width, channel_count)? I believe after doing that conversion the problem should be fixed. Can you give me some help on this, I am new to tensorflow and don't know how to do it in c++. Thanks!

**Comment by mohantym** [comment] 2022-03-24 11:17
I could replicate this issue in [2.8 version](https://colab.sandbox.google.com/gist/mohantym/7f529af5b3f5ad51a578856e84d8b434/gtihub_42694.ipynb) too .

**Comment by mohantym** [comment] 2022-03-24 11:36
Hi @rychnal ! The above example on wave_to_spectrogram (is there till 1.15) has been removed from the 2.x version now . Attaching [audio recognition ](https://www.tensorflow.org/tutorials/audio/simple_audio)documentation from the 2.8 version for reference.  Some lite examples on sound classification and speech recognition can be found from [here](https://github.com/tensorflow/examples/tree/master/lite/examples ). Thanks!

**Closed** 2022-04-07 12:59 UTC
Labels: stat:awaiting response, stalled
