### ISSUE TITLE
Saving model with tf.keras.layers.RNN and stateful=True with save_format='tf' fails

### ISSUE THREAD

**Issue by padoremu** [tensorflow/tensorflow#37250] opened 2020-03-03 07:58 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- Mobile device if the issue happens on mobile device: -
- TensorFlow installed from: binary
- TensorFlow version: 2.2.0-dev20200228
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: CPU only
- GPU model and memory: CPU only

**Describe the current behavior**
Saving a `tf.keras.Sequential` model with `tf.keras.layers.RNN` and `stateful=True` with `save_format=tf` fails.

**Describe the expected behavior**
Saving should succeed.

**Code to reproduce the issue**
```python
import tensorflow as tf

number_of_cells = 2

model = tf.keras.Sequential()

model.add(tf.keras.layers.Input(batch_input_shape=(1, 1, 1)))

cells = []

for _ in range(number_of_cells):
    cells.append(tf.keras.layers.GRUCell(10))

model.add(tf.keras.layers.RNN(cells, stateful=True))

model.compile()

model.save('rnn.tf', save_format='tf')

model2 = tf.keras.models.load_model('rnn.tf')

```

**Other info / logs**
Saving succeeds with `save_format='h5'`.

Traceback in case of failure:
```bash
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model.save('rnn.tf', save_format='tf')
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1044, in save
    signatures, options)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 138, in save_model
    signatures, options)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1027, in _build_meta_graph
    options.namespace_whitelist)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 629, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 497, in _generate_signatures
    function, mapped_inputs, resource_map)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 449, in _call_function_with_mapped_captures
    resource_map)
  File "/home/test/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 372, in _map_captures_to_created_tensors
    ).format(interior))
AssertionError: Tried to export a function which references untracked object Tensor("2164:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```

**Comment by ravikyram** [comment] 2020-03-03 11:03
I have tried on colab with TF Nightly version and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e38aae55dc2b68e5852c2524e2d2b02c/untitled700.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-03 18:56
@padoremu I was able to reproduce the issue with `tf-nightly==2.2.0-dev20200228`. However, it looks like this was resolved recently. With the recently `tf-nightly` (!pip install tf-nightly==2.2.0-dev20200303), I was not able to reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/31e9ae78106e740000deae010a8c4b30/37250.ipynb). Thanks!

I am closing this issue as it was resolved. Please feel free to reopen if there is any related issue. Thanks!

**Closed by jvishnuvardhan** 2020-03-03 18:56 UTC
Labels: TF 2.1, comp:keras, type:bug
