### ISSUE TITLE
different output size for avg_pool and max_pool

### ISSUE THREAD

**Issue by corner200** [tensorflow/tensorflow#15251] opened 2017-12-10 16:34 UTC
Hello,

I have the same bug as this user.

https://stackoverflow.com/questions/47423172/tensorflow-why-does-avg-pool-ignore-one-stride-dimension

My version is uo-to-date

Have I written custom code: Yes
OS Platform and Distribution: Linux Mint 18.3, codename "Sylvia"
TensorFlow installed from Tensorflow Website
TensorFlow version 14.1.0
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory GeForce 940MX
Exact command to reproduce: see link

**Comment by tensorflowbutler** [comment] 2017-12-11 01:01
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by corner200** [comment] 2017-12-11 01:39
Thanks you.
I changed it.

And I have a question.
Why is it not possible to give the ksize of tf.nn.avg_pool or max_pool as a
tensor? It makes no sense, that it has to be an int.


Sincerely
Viktor

Am 11.12.2017 10:04 schrieb "Alfred" <notifications@github.com>:

**Comment by corner200** [comment] 2017-12-11 01:42
Thanks you. I changed it
 And I have a question. Why is it not possible to give the ksize of tf.nn.avg_pool or max_pool as a tensor? It makes no sense, that it has to be an int.
https://stackoverflow.com/questions/47740967/tf-avg-pool-with-dynamic-ksize

Sincerely Viktor

**Comment by facaiy** [comment] 2017-12-11 06:29
Related issue: Hvass-Labs/TensorFlow-Tutorials#19

**Comment by angersson** [comment] 2017-12-11 21:02
This looks like a duplicate of #14886 -- please add any further comments there.

**Closed by angersson** 2017-12-11 21:02 UTC
