### ISSUE TITLE
MultiWorkerMirroredStrategy rendezvous Did not find key 

### ISSUE THREAD

**Issue by Jianbing-D** [tensorflow/tensorflow#47257] opened 2021-02-19 06:47 UTC
Hi, I want to use rendezvous to transfer tensor between two machines within the scope of MultiWorkerMirroredStrategy, but it complains an Internal error `Did not find key my_tensor_name`.

What is the device name different machines used to identify each other in the cluster? Can two machines identify each other with such device name? 
```c++
const char* dst_device_name = "/job:worker/replica:0/task:1/device:CPU:0";
const char* src_device_name= "/job:worker/replica:0/task:0/device:CPU:0";
```

BTW, `typeid(*OpKernelContext->rendezvous()).name()` show `SimpleRendezvous` in one machine and `IntraProcessRendezvous` for another machine. Why not `*Remote*Rendezvous` is created? 

Here is my code snippet:
1. my custom op
```c++
#include "tensorflow/core/framework/op_kernel.h"
#include <chrono>
#include <thread>

namespace tensorflow {

using GPUDevice = Eigen::GpuDevice;
using CPUDevice = Eigen::ThreadPoolDevice; 

class TestRendezvousMultiWorkerOp : public AsyncOpKernel {
public:
    explicit TestRendezvousMultiWorkerOp(OpKernelConstruction* ctx) : AsyncOpKernel(ctx) {
        OP_REQUIRES_OK(ctx, ctx->GetAttr("task_id", &task_id_));
        OP_REQUIRES(ctx, task_id_ >= 0, 
            errors::Internal("task_id should be >= 0, but got ", task_id_));
    }
    void ComputeAsync(OpKernelContext* ctx, DoneCallback done) override {
        OP_REQUIRES_ASYNC(ctx, ctx->rendezvous() != nullptr,
            errors::Internal("Op kernel context needs to provide a rendezvous."), done);

        const char* dst_device_name = "/job:worker/replica:0/task:1/device:CPU:0";
        const char* src_device_name = "/job:worker/replica:0/task:0/device:CPU:0";

        std::string send_key = Rendezvous::CreateKey(
                            src_device_name /*src_device*/,
                            123/*src_incarnation*/,
                            dst_device_name /*dst_device*/,
                            "test_rendezvous_string"/*name*/,
                            FrameAndIter(0, 0)/*frame_and_iter*/);

        Rendezvous::ParsedKey parsed_key;
        OP_REQUIRES_OK_ASYNC(ctx, Rendezvous::ParseKey(send_key, &parsed_key), done);
        
        Rendezvous::Args args;

        const Tensor* input_tensor = nullptr;
        OP_REQUIRES_OK_ASYNC(ctx, ctx->input("value", &input_tensor), done);
        Tensor* out_tensor = nullptr;
        OP_REQUIRES_OK_ASYNC(ctx, ctx->allocate_output(0, input_tensor->shape(), &out_tensor), done);

        if (task_id_ == 0) {
            OP_REQUIRES_OK_ASYNC(ctx, ctx->rendezvous()->Send(parsed_key, args, *input_tensor, ctx->is_input_dead()), done);
            std::memcpy(out_tensor->data(), input_tensor->data(), input_tensor->TotalBytes());
            std::this_thread::sleep_for(std::chrono::seconds(5));
        } else {
            bool is_dead = false;
            OP_REQUIRES_OK_ASYNC(ctx, ctx->rendezvous()->Recv(parsed_key, args, out_tensor, &is_dead), done);
        }

        done();
        
    }
private:
    int task_id_;
};

REGISTER_KERNEL_BUILDER(Name("TestRendezvousMultiWorker").Device(DEVICE_CPU), 
                        TestRendezvousMultiWorkerOp);

} // namespace tensorflow
```

2. my python script
```python
import tensorflow as tf
import os, json

os.environ['CUDA_VISIBLE_DEVICES'] = ""

os.environ["TF_CONFIG"] = json.dumps({
    "cluster": {"worker": ["host1:port", "host2:port"]},
    "task": {"type": "worker", "index": args.task_id}
})

resolver = tf.distribute.cluster_resolver.TFConfigClusterResolver()
strategy = tf.distribute.MultiWorkerMirroredStrategy(resolver)

import my_custom_lib

@tf.function
def _test_step(task_id):
    value = tf.constant([1.0, 2.0])
    out = my_custom_lib.test_rendezvous_multi_worker(value, task_id=task_id)
    return out

out = strategy.run(_test_step, args=(args.task_id,))
print(out)
```

3. the python3 command
```python
python3 file.py --task_id=0 # on machine 1
python3 file.py --task_id=1 # on machine 2
```

**Comment by crccw** [comment] 2021-02-25 01:44
This is not supported. With MultiWorkerMirroredStrategy, you only have access to your local devices. Normally people use collective operations like all-reduce and all-gather to communicate between devices.

**Comment by crccw** [comment] 2021-02-25 01:46
This seems to be a duplicate of #47277. There's no plan to support using rendezvous to communicate between workers with MultiWorkerMirroredStrategy. We can discuss in #47277 about your use case and alternatives.

**Closed by crccw** 2021-02-25 01:46 UTC
Labels: comp:dist-strat, stat:awaiting tensorflower, type:support
