### ISSUE TITLE
Error installing tf-nightly-2.0-preview with pip

### ISSUE THREAD

**Issue by wxdao** [tensorflow/tensorflow#28691] opened 2019-05-14 06:35 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version: latest tf-nightly-2.0-preview
- Python version: Python 3.6.7
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Official colab link for tensorboard 2.0 demo is able to reproduce the bug:

https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/r2/get_started.ipynb

```
$ pip install -q tf-nightly-2.0-preview

ERROR: thinc 6.12.1 has requirement wrapt<1.11.0,>=1.10.0, but you'll have wrapt 1.11.1 which is incompatible.
```

**Comment by muddham** [comment] 2019-05-16 09:33
@wxdao When I ran the command pip install -q tf-nightly-2.0-preview , I get the error. And if I remove -q then the error is not shown.

**Comment by wxdao** [comment] 2019-05-16 11:14
It does work with the method you mentioned, i.e without the -q parameter. Thank you.

But why? It's so frustrating.

**Comment by jvishnuvardhan** [comment] 2019-05-18 14:53
@wxdao Where did you see that `-q` command? In TF website, [check](https://www.tensorflow.org/install/pip) check this page. Thanks!

**Comment by wxdao** [comment] 2019-05-19 07:03
> @wxdao Where did you see that `-q` command? In [TF website](https://www.tensorflow.org/install/pip), it was not mentioned with `-q`. Thanks!

It's in every official tutorial colab notebook, like [this one](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/r2/get_started.ipynb), so I thought I was supposed to add -q too.

**Comment by mihaimaruseac** [comment] 2019-05-20 16:43
`-q` is a `pip` flag:

```
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
```

The issue here is not caused by TensorFlow. In the python environment you're using (virtualenv? global install?) you already have an incompatible version of `thinc`. You can try uninstalling and reinstalling that with the required version number

**Comment by jvishnuvardhan** [comment] 2019-05-29 21:12
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-05-29 21:12 UTC
Labels: type:build/install, type:docs
