### ISSUE TITLE
Feature request: tensordot

### ISSUE THREAD

**Issue by entron** [tensorflow/tensorflow#2466] opened 2016-05-22 20:43 UTC
I found one useful tensor operation "tensordot" is missing in tensorflow. [Theano has an implementation of it](http://deeplearning.net/software/theano/library/tensor/basic.html). It would be great to have tensordot also in tensorflow.

**Comment by vrv** [comment] 2016-05-23 18:42
Duplicate of #216

**Closed by vrv** 2016-05-23 18:42 UTC

**Comment by shoyer** [comment] 2016-05-25 05:28
@vrv tensordot is related to but not exactly the same as a broadcasting matmul -- with tensordot, there is an explicit axes argument.

**Comment by entron** [comment] 2016-05-26 10:07
`tensordot` can contract multiple indices at the same time which is different with what mentioned in #216

**Comment by vrv** [comment] 2016-05-27 01:11
Agreed, I just wanted to have one issue that tracks them both, since they are closely related and we already have a billion issues.
