### ISSUE TITLE
Calling set_session before fit_generator causes training to freeze when using multiprocessing

### ISSUE THREAD

**Issue by moberweger** [tensorflow/tensorflow#33973] opened 2019-11-04 13:21 UTC
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device if the issue happens on mobile device: N/A
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.5
- Bazel version: N/A
- GCC/Compiler version: N/A
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**
I am trying to modify TF session parameters in combination with Keras (e.g. the allowed GPU memory) and use `set_session()` to store these parameters. However, if `set_session()` is called  before `fit_generator()`, it causes the training to freeze when using multiprocessing. To reproduce the error, set `if True` in the main function.

**Describe the expected behavior**
No freeze should occur.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence


def get_model(input_shape, output_shape, compile_batch_size):
    assert K.image_data_format() == 'channels_last'
    m_input = Input(shape=input_shape, batch_size=compile_batch_size)
    m_output = Conv2D(output_shape[-1], 1, activation=None)(m_input)
    model = Model(inputs=m_input, outputs=m_output)
    return model


class DataGenerator(Sequence):
    def __init__(self, batch_size, image_size, num_batches):
        assert K.image_data_format() == 'channels_last'

        self.batch_size = batch_size
        self.image_size = image_size
        self.num_batches = num_batches
        self.on_epoch_end()

    def __len__(self):
        assert self.num_batches > 0
        return self.num_batches

    def __getitem__(self, index):
        return np.zeros((self.batch_size,) + self.image_size).astype('float32'), np.zeros(
            (self.batch_size,) + self.image_size).astype('float32')

    def on_epoch_end(self):
        pass


if __name__ == '__main__':
    print(tf.version.GIT_VERSION, tf.version.VERSION)

    # set to True to trigger infinite wait
    if True:
        # limit GPU memory
        config = tf.ConfigProto()
        config.gpu_options.allow_growth = True
        config.gpu_options.per_process_gpu_memory_fraction = 0.5
        tf.keras.backend.set_session(tf.Session(config=config))

    inp_shape = (128, 64, 2)
    outp_shape = (128, 64, 2)
    batch_size = 16

    gen = DataGenerator(batch_size, inp_shape, 10)
    model = get_model(inp_shape, outp_shape, batch_size)
    model.summary()
    model.compile(loss=["mse"], optimizer="adam", metrics=["accuracy"])
    model.fit_generator(gen, steps_per_epoch=10, epochs=5, workers=2, use_multiprocessing=True)

```

**Other info / logs**
```
Traceback (most recent call last):
  File "keras_mwe.py", line 57, in <module>
    model.fit_generator(gen, steps_per_epoch=10, epochs=5, workers=2, use_multiprocessing=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 779, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 602, in get
    self.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 599, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by ravikyram** [comment] 2019-11-05 06:41
I have tried on colab with TF version 1.14 , 1.15 and i am not seeing any error message. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/68747e5a584d105ac7130e411721d251/untitled330.ipynb). Thanks!

**Comment by moberweger** [comment] 2019-11-05 10:05
Thanks @ravikyram for creating the colab gist. Accidentally, the bug was disabled in the code snippet I posted (`if False`), but I updated it accordingly. The colab gist can now reproduce the error, with slightly different message, though.

**Comment by gowthamkpr** [comment] 2019-11-06 21:30
@moberweger I tried reproducing your issue using Tensorflow 1.15 but was not able to reproduce it. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/c7d13ee8fb33c915980d9a1845d0d3d5/untitled217.ipynb).

**Comment by moberweger** [comment] 2019-11-07 06:19
Thanks @gowthamkpr Interestingly, the gist worked also for me when executed for the first time, but still I could reproduce the error it in your colab after running a few times with TF 1.14 and 1.15. I also checked TF 2.0 through the `compat` interface, and could trigger the same error, see my gist [here](https://colab.research.google.com/gist/moberweger/2553560a5deeb2eaa5e3cfc23516ef34/untitled217.ipynb) The colab execution of the code in question is not responding, so I stopped executing after 10 min, which ultimately gives me the error.

**Comment by gowthamkpr** [comment] 2019-11-09 00:08
@moberweger I can run it with TF1.15-gpu without any issues but with TF 2.0 I can see the issue is persisting. I am closing this issue but Please create a new issue specifying Tensorflow 2.0 and we can deal with it separately. Thanks!

**Closed by gowthamkpr** 2019-11-09 00:08 UTC
Labels: TF 1.14, comp:keras, type:support
