### ISSUE TITLE
seq2seq: Cannot parse tensor from proto: dtype: DT_FLOAT

### ISSUE THREAD

**Issue by zhaopku** [tensorflow/tensorflow#4218] opened 2016-09-06 01:15 UTC
My platform is ubuntu 14.04 with tensorflow version of 0.10, CPU version.

I am using functions in `seq2seq.py` to build a model. The code works fine when I use the `embedding_rnn_seq2seq` function, but when I use `embedding_attention_seq2seq`, it has error like this:

`AttributeError: 'LSTMStateTuple' object has no attribute 'get_shape'`

To fix this, I turned the `state_is_tuple` to `false`, but now it has another problem:

```
W tensorflow/core/framework/op_kernel.cc:926] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_29 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:926] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_28 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
W tensorflow/core/framework/op_kernel.cc:926] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_28 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E tensorflow/core/client/tensor_c_api.cc:485] Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_28 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 730, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 712, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_28 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/mnt/d/DeepQA/chatbot/chatbot.py", line 208, in main
    self.sess.run(tf.initialize_all_variables())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 52772
  }
  dim {
    size: 52767
  }
}
float_val: 0

         [[Node: zeros_28 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 52772 } dim { size: 52767 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op 'zeros_28', defined at:
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/mnt/d/DeepQA/chatbot/chatbot.py", line 169, in main
    self.model = Model(self.args, self.textData)
  File "/mnt/d/DeepQA/chatbot/model.py", line 58, in __init__
    self.buildNetwork()
  File "/mnt/d/DeepQA/chatbot/model.py", line 118, in buildNetwork
    self.optOp = opt.minimize(self.lossFct)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 198, in minimize
    name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 300, in apply_gradients
    self._create_slots(var_list)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/adam.py", line 118, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 494, in _zeros_slot
    named_slots[var] = slot_creator.create_zeros_slot(var, op_name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/slot_creator.py", line 106, in create_zeros_slot
    val = array_ops.zeros(primary.get_shape().as_list(), dtype=dtype)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/array_ops.py", line 1131, in zeros
    output = constant(0, shape=shape, dtype=dtype, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 167, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()
```

Code is as follows:

```
# Creation of the rnn cell
encoDecoCell = tf.nn.rnn_cell.BasicLSTMCell(self.args.hiddenSize, state_is_tuple=False)  # Or GRUCell, LSTMCell(args.hiddenSize)
#encoDecoCell = tf.nn.rnn_cell.DropoutWrapper(encoDecoCell, input_keep_prob=1.0, output_keep_prob=1.0)  # TODO: Custom values (WARNING: No dropout when testing !!!)
encoDecoCell = tf.nn.rnn_cell.MultiRNNCell([encoDecoCell] * self.args.numLayers, state_is_tuple=False)

# Network input (placeholders)

self.encoderInputs  = [tf.placeholder(tf.int32,   [None, ]) for _ in range(self.args.maxLengthEnco)]  # Batch size * sequence length * input dim

self.decoderInputs  = [tf.placeholder(tf.int32,   [None, ], name='inputs') for _ in range(self.args.maxLengthDeco)]  # Same sentence length for input and output (Right ?)
self.decoderTargets = [tf.placeholder(tf.int32,   [None, ], name='targets') for _ in range(self.args.maxLengthDeco)]
self.decoderWeights = [tf.placeholder(tf.float32, [None, ], name='weights') for _ in range(self.args.maxLengthDeco)]

# Define the network
# Here we use an embedding model, it takes integer as input and convert them into word vector for
# better word representation
decoderOutputs, states = tf.nn.seq2seq.embedding_attention_seq2seq(
	self.encoderInputs,  # List<[batch=?, inputDim=1]>, list of size args.maxLength
	self.decoderInputs,  # For training, we force the correct output (feed_previous=False)
	encoDecoCell,
	self.textData.getVocabularySize(),
	self.textData.getVocabularySize(),  # Both encoder and decoder have the same number of class
	embedding_size=self.args.embeddingSize,  # Dimension of each word
	output_projection=None,  # Eventually
	feed_previous=bool(self.args.test)  # When we test (self.args.test), we use previous output as next input (feed_previous)
)
```

**Comment by tatatodd** [comment] 2016-09-07 05:38
@zhaopku Please add the following information - at least the OS / version info.  FYI this is the default template when you click the green "New issue" button on the webpage for this issue.  Thanks!

```
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

### What other attempted solutions have you tried?

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
```

**Comment by zhaopku** [comment] 2016-09-08 00:25
Operating System: ubuntu 14.04
CPU version, no cuda installed
I installed that from pip3
tensorflow version: 0.10, link: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp34-cp34m-linux_x86_64.whl

reproductive sample is just as I mentioned before:
```
encoDecoCell = tf.nn.rnn_cell.BasicLSTMCell(hiddenSize, state_is_tuple=False)  # Or GRUCell, LSTMCell(hiddenSize)
#encoDecoCell = tf.nn.rnn_cell.DropoutWrapper(encoDecoCell, input_keep_prob=1.0, output_keep_prob=1.0)  # TODO: Custom values (WARNING: No dropout when testing !!!)
encoDecoCell = tf.nn.rnn_cell.MultiRNNCell([encoDecoCell] * numLayers, state_is_tuple=False)


encoderInputs  = [tf.placeholder(tf.int32,   [None, ]) for _ in range(maxLengthEnco)]  # Batch size * sequence length * input dim

decoderInputs  = [tf.placeholder(tf.int32,   [None, ], name='inputs') for _ in range(maxLengthDeco)]  # Same sentence length for input and output (Right ?)
decoderTargets = [tf.placeholder(tf.int32,   [None, ], name='targets') for _ in range(maxLengthDeco)]
decoderWeights = [tf.placeholder(tf.float32, [None, ], name='weights') for _ in range(maxLengthDeco)]

decoderOutputs, states = tf.nn.seq2seq.embedding_attention_seq2seq(
    self.encoderInputs,
    self.decoderInputs, 
    encoDecoCell,
    self.textData.getVocabularySize(),
    self.textData.getVocabularySize(),  
    embedding_size=self.args.embeddingSize, 
    output_projection=None, 
    feed_previous=bool(test)  
)


```

**Comment by tatatodd** [comment] 2016-09-08 08:02
@ebrevdo might have some ideas.

**Comment by ebrevdo** [comment] 2016-09-08 15:59
I think @lukaszkaiser knows more about what's going on in the seq2seq code.

**Comment by zhaopku** [comment] 2016-09-09 00:40
@lukaszkaiser Actually the original code is like this:

        with tf.device(getDevice()):
            model = Model(args, textData)

        writer = tf.train.SummaryWriter(_getSummaryName())
        saver = tf.train.Saver(max_to_keep=200)  # Arbitrary limit ?

        sess = tf.Session()  # TODO: Replace all sess by sess (not necessary a good idea) ?

        embedding_key_0 = 'embedding_rnn_seq2seq/RNN/EmbeddingWrapper/embedding:0'
        embedding_key_1 = 'embedding_rnn_seq2seq/embedding_rnn_decoder/embedding:0'

        var_list = []
        embedding_list = []
        cnt = 0
        for v in tf.all_variables():
            print(v.name)
            if v.name != embedding_key_0 and v.name != embedding_key_1:
                cnt += 1
                var_list.append(v)
            else:
                cnt += 1
                embedding_list.append(v)
        print(cnt)
        print('Initialize variables...')

        sess.run(tf.initialize_all_variables())


        print('embedding_0 shape')
        print(embedding_list[0].get_shape())
        print('embedding_1 shape')
        print(embedding_list[1].get_shape())

        print('initializing embeddings from pre-trained word embeddings')
        embed = loadEmbeddings()
        embed = np.asarray(embed).reshape([vocab_size, 300])

        assign_op_0 = tf.assign(embedding_list[0], embed)
        assign_op_1 = tf.assign(embedding_list[1], embed)


        sess.run(assign_op_0)
        sess.run(assign_op_1)

The code in my first post is part of the `Model `function in the second line. I rewrite the embeddings with pretrained word embeddings.

**Comment by lukaszkaiser** [comment] 2016-09-09 06:03
It looks like you're calling get_shape() on a tuple -- it's not supposed to have a shape, as it's a tuple. You can get all its elements and their shapes by iterating. I'm closing it as it looks fine, but please -- let me know if there is another problem or if get_shape() is called from some library function (it shouldn't).

**Closed by lukaszkaiser** 2016-09-09 06:03 UTC
Labels: awaiting googler

**Comment by lokesh005** [comment] 2017-01-20 01:16
@lukaszkaiser I am facing the same problem. I have same specification as the previous one. My code is
`Final_dataset.csv` contains 456 X 147457

    `train = pd.read_csv('Final_dataset.csv')
     x = tf.placeholder(tf.float32, shape=[None, 128*128*3])
     y_ = tf.placeholder(tf.float32, shape=[None, 128*256*3])
     W = tf.Variable(tf.zeros([128*128*3,128*256*3]))
     b = tf.Variable(tf.zeros([128*256*3]))`

Whenever I run below command
     `sess.run(tf.global_variables_initializer())`

I am getting this error

    `W tensorflow/core/framework/op_kernel.cc:965] Invalid argument: Cannot parse tensor from proto:    dtype: DT_FLOAT
      tensor_shape {
          dim {
             size: 49152
          }
          dim {
             size: 98304
          }
      }
      float_val: 0

      E tensorflow/core/common_runtime/executor.cc:390] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
      tensor_shape {
         dim {
            size: 49152
         }
        dim {
            size: 98304
        }
     }
    float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
       Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
         File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
        File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
       File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
     tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
     tensor_shape {
       dim {
          size: 49152
        }
        dim {
            size: 98304
        }
     }
      float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

    Caused by op u'zeros_2', defined at:
    File "<stdin>", line 1, in <module>
    File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1437, in zeros
    output = constant(zero, shape=shape, dtype=dtype, name=name)
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 169, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
     File "/home/lokesh/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

    InvalidArgumentError (see above for traceback): Cannot parse tensor from proto: dtype: DT_FLOAT
    tensor_shape {
     dim {
        size: 49152
     }
     dim {
       size: 98304
     }
     }
     float_val: 0

	 [[Node: zeros_2 = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 49152 } dim { size: 98304 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

**Comment by lukaszkaiser** [comment] 2017-01-20 01:32
Sorry, this looks like an unrelated problem with data reading and parsing.

**Comment by lokesh005** [comment] 2017-01-20 02:25
@lukaszkaiser but if you clearly see the error then it is the same error

**Comment by lukaszkaiser** [comment] 2017-01-20 02:32
Right - but we solved the underlying cause of that previous problem, which was related to seq2seq and state_is_tuple -- that's what this bug is about. The 5 lines of code you've shown that generate your problem are definitely not related to seq2seq. Maybe you just have some wrong sizes somewhere.
