### ISSUE TITLE
tf.image.decode_png returns wrong values for uint16 images

### ISSUE THREAD

**Issue by beopst** [tensorflow/tensorflow#2619] opened 2016-06-02 07:59 UTC
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN R4

If installed from sources, provide the commit hash: d8eb4bb6470d4cb3d0f67f2111a39fa50f1c28e5

### Steps to reproduce

Please see the below code. After saving numpy array as uint16 png image, I loaded it using tf.image.decode_png. It returns different values from the original array. 

```python
import numpy as np
import tensorflow as tf
from skimage import io

original = np.array([[1,4096],[15000,30000]],dtype=np.uint16)
io.imsave('test.png',original)

sk_im = io.imread('test.png')

image = tf.image.decode_png(tf.read_file('test.png'),dtype=tf.uint16)
sess = tf.Session()
tf_im = sess.run(image)

print sk_im
print tf_im
```

Results are
```
sk_im = [[1, 4096], [15000, 30000]] #same as original
tf_im[:,:,0] = [[256, 16], [38970, 12405]]
```
I checked the function works properly in case of uint8 png image.

**Comment by aselle** [comment] 2016-06-02 16:44
What architecture are you running on (little endian or big endian)?

**Comment by beopst** [comment] 2016-06-03 01:57
It is little endian (x86 processors).

> $ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               2599.968
BogoMIPS:              4797.20
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-11

**Comment by mrjel** [comment] 2016-06-07 10:35
As a workaround, the values can be fixed by swapping the bytes via integer-operations
```
# Decode image
image = tf.image.decode_png(png, dtype=tf.uint16)
image = tf.reshape(image, [depth, height, width])

# Swap Bytes 
tensor256 = tf.fill(image.get_shape(), 256)
image_div = tf.div(tf.cast(image, tf.int32), tensor256)
image_mod = tf.mod(tf.cast(image, tf.int32), tensor256)
image = tf.add(tf.mul(image_mod, tensor256), image_div)
```
This is obviously a dirty hack and would break correct values on systems where the decode function works correctly

**Comment by girving** [comment] 2016-06-11 00:07
@dave-andersen Could you take a look since you touched the png reading most recently? :)

**Comment by dave-andersen** [comment] 2016-06-14 22:02
Urgh.  I'm concerned that we're not properly setting the IS_LITTLE_ENDIAN flag in the OSS build:
https://github.com/tensorflow/tensorflow/search?utf8=%E2%9C%93&q=IS_LITTLE_ENDIAN

I'll take this on.  @girving - do you know off the top of your head if we have an existing flag for little endian I can repurpose here?  (I'll dig, just trying to be lazy. :)

**Comment by girving** [comment] 2016-06-14 22:12
@dave-andersen I don't remember, nor do I envy you this task. :)

**Comment by dave-andersen** [comment] 2016-06-14 22:15
I'm, um, just going to use the existing flag and assume it's someone else's responsibility to make the flag work. :)
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/host_info.h#L25

(static const bool kLittleEndian = true; )

**Comment by girving** [comment] 2016-06-14 22:20
Actually, I'm not sure that flag is the issue.  @beopst Are you on a little endian machine?

**Comment by dave-andersen** [comment] 2016-06-14 22:22
@girving - the issue is that we don't use that flag in the PNG decoder, we use the IS_LITTLE_ENDIAN flag, which is only defined by some transitively included google-internal header.

The second part of the issue is that we don't have any tests for the png decode op that would catch this on jenkins.

Fixing.

**Comment by dave-andersen** [comment] 2016-06-15 01:14
Fix submitted, should hit github at next sync.  Will let the fix close it.
@beopst - huge thanks for providing an easy way to reproduce with your bug report!

**Closed** 2016-06-15 05:52 UTC
Labels: bug, triaged
