### ISSUE TITLE
tf.function fails to parse for-loop in some circumstances

### ISSUE THREAD

**Issue by jackshi0912** [tensorflow/tensorflow#29504] opened 2019-06-06 17:34 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
```python
@tf.function
def tf_function_with_loop(num_iter):
  digit_list = []
  for i in tf.range(num_iter):
    digit_list.append(i)
  return tf.add_n(digit_list)

tf_function_with_loop(5)
fails with log posted in log section.

def function_with_loop(num_iter):
  digit_list = []
  for i in tf.range(num_iter):
    digit_list.append(i)
  return tf.add_n(digit_list)

function_with_loop(5)  # samething without @tf.function
returns tf.Tensor(10, shape=(), dtype=int32)
```
**Describe the expected behavior**
tf_function_with_loop(5) should return tf.Tensor(10, shape=(), dtype=int32)

**Code to reproduce the issue**
written above.

**Other info / logs**

ValueError: Trying to capture a tensor from an inner function. This can be caused by accessing a tensor defined inside a loop or conditional body, or a subfunction, from a calling function, without going through the proper return value mechanism. Consider using TensorFlow mechanisms such as TensorArrays to return tensors from inner functions or loop / conditional bodies. Tensor: Tensor("TensorArrayV2Read/TensorListGetItem:0", shape=(), dtype=int32); tensor graph: FuncGraph(name=while_body_40, id=139946430861008); this graph: FuncGraph(name=tf_function_with_loop, id=139946437179024)

**Comment by gadagashwini** [comment] 2019-06-14 09:54
I am able to reproduce the issue on colab with Tf 2.0.0.beta0. Thanks!

**Comment by jackshi0912** [comment] 2019-06-14 15:26
Found this in a autograph example. It seems that you need TensorArray for this. Feel free to close it. I'm not sure if supporting python list was intended or not (since Autograph otherwise support parsing python list).

@tf.function
def square_if_positive_naive(x):
  result = tf.TensorArray(tf.int32, size=x.shape[0])
  for i in tf.range(x.shape[0]):
    if x[i] > 0:
      result = result.write(i, x[i] ** 2)
    else:
      result = result.write(i, x[i])
  return result.stack()


square_if_positive_naive(tf.range(-5, 5))

**Comment by ymodak** [comment] 2019-06-15 18:05
Closing this issue since the error message helps resolving it.  Feel free to reopen if have further questions. Thanks!

**Comment by rhezab** [comment] 2019-08-06 19:01
I think this deserves another look. Especially since the solution provided by the poster stops gradients from flowing back in graph mode. See: 

`@tf.function
def tf_function(x):
  arr = tf.TensorArray(tf.float32, size=5)
  with tf.GradientTape() as tape:
    for i in range(5):
      arr.write(i, i)
    result = tf.reduce_sum(x * arr.stack())
  grad = tape.gradient(result, x)
  return grad

def py_function(x):
  arr = tf.TensorArray(tf.float32, size=5)
  with tf.GradientTape() as tape:
    for i in range(5):
      arr.write(i, i)
    result = tf.reduce_sum(x * arr.stack())
  grad = tape.gradient(result, x)
  return grad

x = tf.Variable(tf.constant(1.))
g = tf_function(x)
tf.print('return from tf_function: ', g)
g = py_function(x)
tf.print('return from py_function: ', g)
`

Returns:

`return from tf_function:  0
return from py_function:  10`

See this colab notebook: https://colab.research.google.com/drive/1d5E9Xs58t6lJuKFfnXwcnaxsE_fGHj7Z

**Comment by ymodak** [comment] 2019-08-09 19:10
@rhezab Can you please post another issue to report your problem? Thanks!

**Closed by ymodak** 2019-08-09 19:10 UTC
Labels: 2.0.0-beta0, comp:autograph, type:bug

**Comment by rhezab** [comment] 2019-08-12 16:31
@ymodak  So I realized this was a stupid mistake where I should've been doing 

`arr = arr.write(i,i)`

Apparently this is required in graph mode - perhaps a side effect problem. Is this the same problem with using list appends? Why does it sometimes work and sometimes not?

I guess some explanation of the above would be nice... then again maybe I need to read the AutoGraph documentation more carefully. 

Thanks!
