### ISSUE TITLE
1.9 RC2 build from source fails cc1plus: warning: unrecognized command line option "-Wno-writable-strings"

### ISSUE THREAD

**Issue by crawforc3** [tensorflow/tensorflow#20938] opened 2018-07-18 18:58 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Debian 9

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
n/a

- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
1.9 rc2
- **Python version**:
3.6

- **Bazel version (if compiling from source)**:
0.15.2

- **GCC/Compiler version (if compiling from source)**:
gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)

- **CUDA/cuDNN version**:
n/a

- **GPU model and memory**:
n/a

- **Exact command to reproduce**:
```
cd /usr/local/src 
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
cat /dev/null | ./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow*.whl

```

### Describe the problem

Building Tensorflow from source fails with the error below. We're trying to update the docker images for over at Kaggle (https://github.com/kaggle/docker-python )

### Source code / logs
[tf.log](https://github.com/tensorflow/tensorflow/files/2206995/tf.log)

At global scope:
cc1plus: warning: unrecognized command line option "-Wno-writable-strings"
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 295.663s, Critical Path: 79.71s
INFO: 2072 processes: 2072 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by evdcush** [comment] 2018-07-23 03:40
I'm having the same failure message as @crawforc3 


## System information


#### Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No

#### OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04, 4.15.0-29-generic

#### Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a

#### TensorFlow installed from (source or binary):
Source

#### TensorFlow version (use command below):
`1.9.0`

#### Python version:
3.7

#### Bazel version (if compiling from source):
0.15.2

#### GCC/Compiler version (if compiling from source):
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)`

#### CUDA/cuDNN version:
9.1/7.1

#### GPU model and memory:
GeForce GTX 1070, 8g

#### Exact command to reproduce:
```bash
`git clone https://github.com/tensorflow/tensorflow && cd tensorflow`
`./configure`
`bazel build  //tensorflow/tools/pip_package:build_pip_package`
```
Also tried:
`bazel build  --config=opt //tensorflow/tools/pip_package:build_pip_package`
`bazel build  --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
`bazel build  --config=opt --config=cuda --config=mkl //tensorflow/tools/pip_package:build_pip_package`


## Describe the problem
Building TF from source fails with the error below. Trying to update current TF build from 3.6.6/1.8 (GPU), to 3.7.0/1.9 (GPU). Never had issues with building TF before. Built many times.

## Source code/logs

```bash
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-writable-strings'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 157.161s, Critical Path: 31.02s
INFO: 1198 processes: 1198 local.
```

**Comment by tensorflowbutler** [comment] 2018-08-06 18:51
Nagging Assignee @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by SilverMight** [comment] 2018-08-21 03:38
Also getting this. An update?

**Comment by evdcush** [comment] 2018-08-21 12:41
@SilverMight  are you trying to build from python 3.7? That ended up being the issue in my situation. Apparently TF doesn't support 3.7 yet, which is one reason this error occurs. I was able to build 1.10.0 from 3.6 without issue.

**Comment by tensorflowbutler** [comment] 2018-09-05 18:49
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment] 2018-09-05 20:10
What is pasted is just a warning. It did not cause your build to fail.
Could you use pastebin to share the full log?

**Comment by rosbo** [comment] 2018-09-13 03:16
@gunan I am experiencing the same issue. Here is my full log: https://pastebin.com/5T4C9841

**Comment by gunan** [comment] 2018-09-13 03:54
The actual compilation failure is right here:
```
ERROR: /root/.cache/bazel/_bazel_root/bbcc73fcc5c2b01ab08b6bcf7c29e42e/external/protobuf_archive/BUILD:659:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/pyext/_message.so' failed (Exit 1)
external/protobuf_archive/python/google/protobuf/pyext/descriptor_pool.cc: In function 'PyObject* google::protobuf::python::cdescriptor_pool::New(PyTypeObject*, PyObject*, PyObject*)':
external/protobuf_archive/python/google/protobuf/pyext/descriptor_pool.cc:139:46: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   static char* kwlist[] = {"descriptor_db", 0};
```

Looks to be a protobuf issue.

**Comment by tensorflowbutler** [comment] 2018-09-27 19:07
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-12 12:48
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-27 12:35
Nagging Assignee @gunan: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-11 18:37
Nagging Assignee @gunan: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-26 18:54
Nagging Assignee @gunan: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mirh** [comment] 2019-10-23 16:56
Warnings *by definition* don't make anything fail (and this can just be solved with https://github.com/protocolbuffers/protobuf/pull/5516)
Both OP and the last post had probably something to do with some quirk in python instead.

**Comment by gunan** [comment] 2019-10-23 17:37
Looks like from TF side only issue was compiler warnings, which are OK.
All other compilation issues seem to be protobuf compilation issues.
Therefore, I will close this issue.

**Closed by gunan** 2019-10-23 17:37 UTC
