### ISSUE TITLE
Adding support to TensorFlow Lite for more ops

### ISSUE THREAD

**Issue by sharmaninaad** [tensorflow/tensorflow#37246] opened 2020-03-03 06:18 UTC
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.

**Comment by gadagashwini** [comment] 2020-03-03 06:43
@sharmaninaad,
Can you please share a standalone code to reproduce the issue. Did you try adding converter.allow_custom_ops = True to enable custom ops in the tf.lite? Thanks!

**Comment by gadagashwini** [comment] 2020-03-13 10:22
@sharmaninaad,Let us know if this is still issue. Thanks

**Comment by gadagashwini** [comment] 2020-03-26 08:03
@sharmaninaad, Closing this issue since its resolved. Please feel free to reopen if issue still persists. Thanks!

**Closed** 2020-03-26 08:03 UTC
Labels: comp:lite, stat:awaiting response, type:support
