### ISSUE TITLE
tf.train.Saver() problem when running session: Cannot assign a device for operation save/SaveV2: Could not satisfy explicit device specification '/device:GPU:1' because no supported kernel for GPU devices is available. Registered kernels

### ISSUE THREAD

**Issue by sidhomj** [tensorflow/tensorflow#29761] opened 2019-06-13 20:13 UTC
Having an issue when specificying graph/device placement and saving the model.

graph_model = tf.Graph()
 with graph_model.device(self.device):
        with graph_model.as_default():
         ...
         ...
         saver = tf.train.Saver()
 config = tf.ConfigProto()
 config.gpu_options.allow_growth = True
 with tf.Session(graph=graph_model,config=config) as sess:
       sess.run(tf.global_variables_initializer())

and i get this error..

Caused by op 'save/SaveV2', defined at:
  File "/usr/local/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/usr/local/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/local/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/local/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jsidhom1/DeepTCR/ancillary_analysis/supervised/Supervised_Repertoire_Human.py", line 119, in <module>
    gcn=True,batch_size=10)
  File "/home/jsidhom1/DeepTCR/DeepTCR/DeepTCR.py", line 3643, in Monte_Carlo_CrossVal
    embedding_dim_genes=embedding_dim_genes,embedding_dim_hla=embedding_dim_hla)
  File "/home/jsidhom1/DeepTCR/DeepTCR/DeepTCR.py", line 3400, in Train
    GO.saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 510, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 210, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 124, in save_op
    tensors)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1807, in save_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()
InvalidArgumentError (see above for traceback): Cannot assign a device for operation save/SaveV2: Could not satisfy explicit device specification '/device:GPU:1' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'
	 [[node save/SaveV2 (defined at /home/jsidhom1/DeepTCR/DeepTCR/DeepTCR.py:3400) ]]

**Comment by ravikyram** [comment] 2019-06-20 11:24
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment] 2019-06-28 06:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-06-28 06:46 UTC
Labels: comp:gpu, stat:awaiting response, type:support
