### ISSUE TITLE
Pip install of Tensorflow may be causing issues with MacOS

### ISSUE THREAD

**Issue by Salvo9879** [tensorflow/tensorflow#73561] opened 2024-08-11 21:52 UTC
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

MacOS Sonoma 14.1

### Python version

3.12.4

### Current behavior?

I recently installed tensorflow (2 days ago) using Pip. Ever since downloading Tensorflow I have had an issue with my MacBook. Specifically a process called “fileproviderd” has been using over 110% of my CPU usage. This is causing my laptop to heat up and is draining the battery. I have since deleted tensorflow from my virtual environment and have noticed a slight improvement (averaging out at about 40%-90% - which is still not normal). I have just reinstalled Tensorflow and the process’ activity skyrocketed using about 140% of the CPU usage. 

I am also contacting Apple support with the issue and will report any solutions that we discover however I do believe that this is an issue with Tensorflow as I’ve never had this issue before installing it. 

Also not that I never ran any code the second time I installed tensorflow, just installed it using Pip. 

### Standalone code to reproduce the issue

```shell
1. Installing Tensorflow using Pip to a virtual environment.
2. Activity monitor reports a high CPU usage from a process called “fileproviderd”.
3. Deleting Tensorflow from the virtual environment and a restart.
4. Slightly lower usage from the process.
```

**Comment by mihaimaruseac** [comment] 2024-08-12 16:21
Can you post the output of `pip list` once TF is installed?

**Comment by mihaimaruseac** [comment] 2024-08-13 13:37
Cannot reproduce with the exact same versions.

Is it possible you are syncing the virtual environment to the cloud? You should not. There are many files in these wheels and there's nothing to be gained by syncing them compared to just installing them again when needed.

**Comment by Salvo9879** [comment] 2024-08-13 13:41
Yes, My project is stored using iCloud. However I have deleted the environment completely yet the issue persists. I will investigate further. Thank you for the response.

**Comment by mihaimaruseac** [comment] 2024-08-13 14:09
It takes a while for the sync to finish. And when you delete your files, the deletion needs to be synced to the cloud too.

**Comment by mihaimaruseac** [comment] 2024-08-13 14:09
Closing this since it is not a TF issue.

**Closed by mihaimaruseac** 2024-08-13 14:09 UTC
Labels: type:support, 2.17
