### ISSUE TITLE
Center Loss in TF 2.0

### ISSUE THREAD

**Issue by suraj-maniyar** [tensorflow/tensorflow#37410] opened 2020-03-07 07:28 UTC
I am trying to implement center loss in Tensorflow 2.0 by referring to code in following repositories:

- https://github.com/handongfeng/MNIST-center-loss

- https://github.com/mjDelta/keras-center-loss-MNIST

- https://github.com/Kakoedlinnoeslovo/center_loss

I noticed that some arguments in the method "self.add_update((self.centers,new_centers),x)" when creating a custom layer, are deprecated. The code (linked above) does not throw any error, but the centers are never updated when run in Tensorflow 2.0. 

You can find the related description for the problem here:
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/keras/engine/base_layer.py#L1170-L1259

I am trying to update the weights of the layer after every forward pass so I can use it as tf.Variable which can persist the updated centroids for the next iteration.

Any help on this would be appreciated.
Thanks

**Comment by ravikyram** [comment] 2020-03-09 09:52
@suraj-maniyar 

Thanks for reporting the issue. Can you please share the simple standalone code to reproduce the issue. It helps us in localizing the issue faster. Thanks!

**Comment by tensorflowbutler** [comment] 2020-03-25 01:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2020-03-26 09:16
@suraj-maniyar 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment] 2020-04-03 11:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-03 11:18 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by pgaggar** [comment] 2020-10-06 18:10
Is there a solution to this? I'm also facing exactly the same problem.

**Comment by pgaggar** [comment] 2020-10-07 07:51
To update this, we need to use 

> tf.keras.backend.update(x, new_x)

 as the argument to the add_update function, as it expects an update operation.
