### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by deepankar1994** [tensorflow/tensorflow#7031] opened 2017-01-24 03:08 UTC
Hi,
I am using TF ver 0.12.head on Ubuntu 16.04 Python 2.7 and following [this](https://github.com/tensorflow/models/blob/master/slim/slim_walkthough.ipynb) for learning inception model in TF Slim
```

import numpy as np
import os
import tensorflow as tf
import urllib2

from datasets import imagenet
from nets import inception
from preprocessing import inception_preprocessing

slim = tf.contrib.slim

batch_size = 3
image_size = inception.inception_v1.default_image_size
checkpoints_dir = '/tmp/checkpoints/'
with tf.Graph().as_default():
    url = 'https://upload.wikimedia.org/wikipedia/commons/7/70/EnglishCockerSpaniel_simon.jpg'
    image_string = urllib2.urlopen(url).read()
    image = tf.image.decode_jpeg(image_string, channels=3)
    processed_image = inception_preprocessing.preprocess_image(image, image_size, image_size, is_training=False)
    processed_images  = tf.expand_dims(processed_image, 0)
    
    # Create the model, use the default arg scope to configure the batch norm parameters.
    with slim.arg_scope(inception.inception_v1_arg_scope()):
        logits, _ = inception.inception_v1(processed_images, num_classes=1001, is_training=False)
    probabilities = tf.nn.softmax(logits)
    
    init_fn = slim.assign_from_checkpoint_fn(
        os.path.join(checkpoints_dir, 'inception_v1.ckpt'),
        slim.get_model_variables('InceptionV1'))
    
    with tf.Session() as sess:
        init_fn(sess)
        np_image, probabilities = sess.run([image, probabilities])
        probabilities = probabilities[0, 0:]
        sorted_inds = [i[0] for i in sorted(enumerate(-probabilities), key=lambda x:x[1])]
        
    plt.figure()
    plt.imshow(np_image.astype(np.uint8))
    plt.axis('off')
    plt.show()

    names = imagenet.create_readable_names_for_imagenet_labels()
    for i in range(5):
        index = sorted_inds[i]
        print('Probability %0.2f%% => [%s]' % (probabilities[index], names[index]))
```
However I am getting the following issue when running this:
```
    logits, _ = inception.inception_v1(processed_images, num_classes=1001, is_training=False)
  File "/home/deepankar1994/Desktop/MTP/TensorFlowEx/TFSlim/models/slim/nets/inception_v1.py", line 290, in inception_v1
    net, end_points = inception_v1_base(inputs, scope=scope)
  File "/home/deepankar1994/Desktop/MTP/TensorFlowEx/TFSlim/models/slim/nets/inception_v1.py", line 96, in inception_v1_base
    net = tf.concat(3, [branch_0, branch_1, branch_2, branch_3])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1053, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by drpngx** [comment] 2017-01-24 03:35
Thanks for contacting us! This is better asked on stackoverflow, where we monitor all questions with the `tensorflow` tag.

**Comment by deepankar1994** [comment] 2017-01-24 04:03
I did actually ask this on StackOverflow  [here](http://stackoverflow.com/questions/41813665/tensorflow-slim-typeerror-expected-int32-got-list-containing-tensors-of-type). Please feel free to respond.

**Comment by drpngx** [comment] 2017-01-24 18:31
Oh, I didn't realize it was working on 0.11. Our tensorflow/models are woefully out of date and we don't really have the bandwidth to support them.

**Comment by deepankar1994** [comment] 2017-01-25 04:33
For now, I have reverted to TF 0.11 to get this to work until this is resolved in TF0.12.

**Comment by drpngx** [comment] 2017-01-25 20:27
Looks similar to a problem when the parameter order was swapped. Maybe @sguada knows something about that.

**Comment by mlucool** [comment] 2017-02-13 02:57
I am seeing this error when running this example for the udacity course: [/examples/udacity/6_lstm.ipynb](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/6_lstm.ipynb)

**Comment by inflation** [comment] 2017-02-14 02:51
@mlucool `tf.concat` has changed the order of parameters. You can check the doc to see the difference.

**Comment by mlucool** [comment] 2017-02-14 03:11
Ah that solved it! Thanks! I should have downloaded from the 0.12.1 tag to be sure

**Comment by mmaaww** [comment] 2017-02-21 07:10
@inflation can you be more specific on what the changes are?

**Comment by brucelau-github** [comment] 2017-02-24 00:12
I have the same problem.

**Comment by brucelau-github** [comment] 2017-02-24 00:13
I should be told to use the slim instead of inception

**Comment by tollytao** [comment] 2017-02-27 09:47
Hi, 
I am using TF 1.0.0 on ubuntu 14.04 64bit os , I also meets this error, can you help to resolve it, thank you.

Traceback (most recent call last):
  File "JP_train.py", line 409, in <module>
    initial_weights=initial_weights)
  File "JP_train.py", line 277, in train
    x, y, y_t = JP_model.get_googlenet_min_model(batch_size,0.5)
  File "/mnt/tolly/work/git/10.5.253.119/tools/2D/AP/Deep_ANPR/JP/JP_model.py", line 195, in get_googlenet_min_model
    incept3a = _inception(pool3,    192, 64, 96, 128, 16, 32, 3, 32)
  File "/mnt/tolly/work/git/10.5.253.119/tools/2D/AP/Deep_ANPR/JP/JP_model.py", line 113, in _inception
    incept = array_ops.concat(3, [conv1, conv3, conv5, pool])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by hkkatti** [comment] 2017-02-27 14:55
I also get this error while executing "ptb_word_lm.py" . Any help appreciated

**Comment by ahmadtausif** [comment] 2017-03-05 02:15
hi all the issue is due to Keras version. I tried above all without any success. Uninstall Keras and install via pip. It worked for me.

I was facing this error with Keras 1.0.2 & resolved with Keras 1.2.0

Hope this will help. Thank you

**Comment by xtr33me** [comment] 2017-03-13 00:25
Unfortunately I seem to be having the same issue with the latest keras-1.2.2. 

```
Traceback (most recent call last):
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/daniel/Documents/git/serving/tf_models/bazel-bin/textsum/seq2seq_attention.runfiles/__main__/textsum/seq2seq_attention.py", line 208, in main
    decoder = seq2seq_attention_decode.BSDecoder(model, batcher, hps, vocab)
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_decode.py", line 92, in __init__
    self._model.build_graph()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 298, in build_graph
    self._add_seq2seq()
  File "/home/daniel/Documents/git/serving/tf_models/textsum/seq2seq_attention_model.py", line 201, in _add_seq2seq
    self._enc_top_states = tf.concat(1, encoder_outputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

```

**Comment by nafizh** [comment] 2017-03-19 21:00
I am getting the same error on Keras 2.0.1

**Comment by samfk6** [comment] 2017-03-24 05:27
@tollytao 
incept = array_ops.concat(3, [conv1, conv3, conv5, pool])
it need to change to
incept = array_ops.concat( [conv1, conv3, conv5, pool], 3)
or
incept = tf.concat( [conv1, conv3, conv5, pool], 3)

**Comment by tollytao** [comment] 2017-03-24 05:35
@samfk6  
I will try it later, thank you very much :)

**Comment by omar-florez** [comment] 2017-03-28 00:53
Just to contextualize, these changes have been placed to have a consistent format with Numpy. Ex: numpy.concatenate((a1, a2, ...), axis=0)

**Comment by girving** [comment] 2017-06-16 21:03
Closing as WAI.

**Closed by girving** 2017-06-16 21:03 UTC
Labels: stat:community support

**Comment by linyia01** [comment] 2017-07-20 02:41
i have the same problem ？

**Comment by zzks** [comment] 2017-07-20 06:33
why change the order of tf.concat's arguments???

**Comment by girving** [comment] 2017-07-20 16:26
@zzks It was changed to match numpy.

**Comment by tiru1930** [comment] 2017-07-26 14:31
i am also having the same issue,
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
outputs_forward,- shape,(1, 2, 100)
outputs_backward-shape (1, 2, 100)
output = tf.concat([outputs_forward, outputs_backward],2,name='output_sequence')

tf version -tensorflow-gpu==0.12.0

**Comment by tiru1930** [comment] 2017-07-26 14:35
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import time
import logging

import numpy as np
# from six.moves import xrange 
import tensorflow as tf
from tensorflow.python import debug as tf_debug

logging.basicConfig(level=logging.INFO)


class Encoder(object):

    def __init__(self,hidden_size,initializer=lambda:None):
        self.hidden_size=hidden_size
        self.initializer=initializer

    def encode(self,inputs,span):

        document,answer = inputs
        start_idx,end_idx = span




        with tf.variable_scope('encode'):
            # weights = tf.Variable(tf.random_normal([2,3], stddev=0.35),name="weights")
            # biases = tf.Variable(tf.zeros([1]), name="biases")
            # label  = tf.Variable(tf.random_normal([2,3],stddev=0.35),name='lable')
            # weights = tf.Variable(shape=[None,None],name="weights")
            # biases = tf.Variable(tf.zeros([None]), name="biases")
            # label  = tf.Variable(shape=[None,None],name='lable')
            print(document.get_shape())
            document_vector_orig=bidirectional_LSTM(document,self.hidden_size,self.initializer,sequence_length=None)
            document_vector=document_vector_orig
            for i in range(tf.shape(document_vector)[0]):
                document_vector[i]=document_vector[i][start_idx:end_idx]
            annotation_sequence=tf.concat(document_vector,answer,axis=2, name='annotation_sequence')
            answer_vector=self.bidirectional_LSTM(annotation_sequence,self.hidden_size,self.initializer,output_sequence=False)

            r=tf.matmul(lable,answer_vector)+(tf.reduce_sum(document_vector_orig,2,keep_dims=True))
            intial_state=tf.tanh(tf.matmul(r,weights)+biases)

        return document_vector_orig,answer_vector ,intial_state

            


def bidirectional_LSTM(input, hidden_state_dimension, initializer, sequence_length=None, output_sequence=True):

    with tf.variable_scope("bidirectional_LSTM"):
        initializer=None
        print(sequence_length)
        if sequence_length == None:
            batch_size = 1
            sequence_length = tf.shape(input)[1]
            sequence_length = tf.expand_dims(sequence_length, axis=0, name='sequence_length')
        else:
            batch_size = tf.shape(sequence_length)[0]

        lstm_cell = {}
        initial_state = {}
        for direction in ["forward", "backward"]:
            with tf.variable_scope(direction):
                # LSTM cell
                lstm_cell[direction] = tf.contrib.rnn.CoupledInputForgetGateLSTMCell(hidden_state_dimension, \
                                        forget_bias=1.0, initializer=initializer, state_is_tuple=True)
                # initial state: http://stackoverflow.com/questions/38441589/tensorflow-rnn-initial-state
                initial_cell_state = tf.get_variable("initial_cell_state", shape=[1, hidden_state_dimension], \
                                                    dtype=tf.float32, initializer=initializer)
                initial_output_state = tf.get_variable("initial_output_state", shape=[1, hidden_state_dimension],\
                                                     dtype=tf.float32, initializer=initializer)
                c_states = tf.tile(initial_cell_state, tf.stack([batch_size, 1]))
                h_states = tf.tile(initial_output_state, tf.stack([batch_size, 1]))
                initial_state[direction] = tf.nn.rnn_cell.LSTMStateTuple(c_states, h_states)

        # sequence_length must be provided for tf.nn.bidirectional_dynamic_rnn due to internal bug
        outputs, final_states = tf.nn.bidirectional_dynamic_rnn(lstm_cell["forward"],
                                                                    lstm_cell["backward"],
                                                                    input,
                                                                    dtype=tf.float32,
                                                                    sequence_length=sequence_length,
                                                                    initial_state_fw=initial_state["forward"],
                                                                    initial_state_bw=initial_state["backward"])
        if output_sequence == True:
            outputs_forward, outputs_backward = outputs
            print(outputs)
            print(outputs_forward.get_shape())
            print(outputs_backward.get_shape())
            # print(outputs_forward[0][1][1])
            output = tf.concat([outputs_forward, outputs_backward],2,name='output_sequence')
        else:

            final_states_forward, final_states_backward = final_states
            output = tf.concat([final_states_forward[1], final_states_backward[1]], 1, name='output')

    return output






def test():

    hidden_size=100
    encoder=Encoder(hidden_size)
    document_placeholder=tf.placeholder(tf.float32,(None,2,4),name='Document_placeholder')
    answer_paceholder=tf.placeholder(tf.float32,(None,2,3),name='Answer_paceholder')
    start_id=tf.placeholder(tf.float32,(None),name='start_id')
    end_id=tf.placeholder(tf.float32,(None),name='end_id')

    paragraph =[[0,1],[1,0],[0,2],[5,3]]

    question = [[3,3],[5,5],[1,1]]
    func = encoder.encode([document_placeholder,answer_paceholder],[start_id,end_id])

    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        HQ,HP,state = sess.run(func, feed_dict = {document_placeholder :paragraph, answer_paceholder : question,start_id : 1, \
            end_id : 2}) 
    print(HQ.get_shape().as_list())
    print(HP.get_shape().as_list())


if __name__ == '__main__':
    test()

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
(?, 2, 4)
None
(<tf.Tensor 'encode/bidirectional_LSTM/BiRNN/FW/FW/transpose:0' shape=(1, 2, 100) dtype=float32>, <tf.Tensor 'encode/bidirectional_LSTM/ReverseSequence:0' shape=(1, 2, 100) dtype=float32>)
(1, 2, 100)
(1, 2, 100)
Traceback (most recent call last):
  File "q_gen_model.py", line 132, in <module>
    test()
  File "q_gen_model.py", line 120, in test
    func = encoder.encode([document_placeholder,answer_paceholder],[start_id,end_id])
  File "q_gen_model.py", line 38, in encode
    document_vector_orig=bidirectional_LSTM(document,self.hidden_size,self.initializer,sequence_length=None)
  File "q_gen_model.py", line 95, in bidirectional_LSTM
    output = tf.concat([outputs_forward, outputs_backward],2,name='output_sequence')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by beyhangl** [comment] 2017-11-16 11:01
parameters changed 

`tf.concat(0,[t1, t2])  
`
to 
`tf.concat([t1, t2], 0) `

solved my issue but why they need to change it ? i dont understand why some parameters is changing always like this way.

**Comment by gopala-kr** [comment] 2018-01-18 20:58
examples of api doc

 https://www.tensorflow.org/api_docs/python/tf/concat


      t1 = [[1, 2, 3], [4, 5, 6]]
      t2 = [[7, 8, 9], [10, 11, 12]]
      tf.concat([t1, t2], 0)  # [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
      tf.concat([t1, t2], 1)  # [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]

      # tensor t3 with shape [2, 3]
      # tensor t4 with shape [2, 3]
       tf.shape(tf.concat([t3, t4], 0))  # [4, 3]
       tf.shape(tf.concat([t3, t4], 1))  # [2, 6]

**Comment by MarwaDF** [comment] 2018-03-28 14:22
(dtype.name, repr(mismatch), type(mismatch).__name__))

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.



I tried the following versions:
 tf 1.4 / keras: 2.1.5
1.1 / keras 1.2.2
tf 1.2.1 / keras 1.22 and keras 2.0.6
  also I changed the file tensorflow bakend.py (tf.concat to tf.concat_v2)
but always the same error

Any help please ?

**Comment by yick2232** [comment] 2018-08-21 03:49
Try to your tensorflow version if your tensorflow==0.12.0

**Comment by autkid** [comment] 2018-09-18 10:07
> parameters changed
> 
> `tf.concat(0,[t1, t2])`
> to
> `tf.concat([t1, t2], 0)`
> 
> solved my issue but why they need to change it ? i dont understand why some parameters is changing always like this way.

Worked For me Too :P

**Comment by dezibelkarate** [comment] 2018-11-20 13:22
Hi, i get the same TypeError message but i don't know why. I do not use `tf.concat()`
I'd appreciate it if you could help me solve this issue. I have keras version 2.2.4 and tensorflow version 1.11.0 but i have tried it with several different versions as well. Furthermore i have python 3.6.3 on a MacOS 10.10.5. 
Here's a snippet from the code
`word_model_in = Input(shape=(context_window,))`
`word_model_out = Embedding(output_dim=embedding_matrix.shape[1],
                         input_dim=embedding_matrix.shape[0],
                         input_length=context_window,
                         weights=[embedding_matrix],
                         mask_zero=True)(word_model_in)`
`word_model_out1 = Bidirectional(LSTM(100,input_shape=(None,3,300),return_sequences=False))(word_model_out)`
`word_model = Model(word_model_in, word_model_out1)`
`word_model.summary()`

And here's the error message
TypeError                                 Traceback (most recent call last)
<ipython-input-41-4a0bf7e03efd> in <module>()
      5                          weights=[embedding_matrix],
      6                          mask_zero=True)(word_model_in)
----> 7 word_model_out1 = Bidirectional(LSTM(100,input_shape=(None,3,300),return_sequences=False))(word_model_out)
      8 word_model = Model(word_model_in, word_model_out1)
      9 word_model.summary()

~/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)

~/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py in call(self, inputs, mask)
    210         kwargs = {}
    211         if has_arg(self.layer.call, 'training'):
--> 212             kwargs['training'] = training
    213         uses_learning_phase = False
    214 

~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py in call(self, inputs, mask, initial_state, training)
    288             (e.g. via the `input_shape` argument)
    289 
--> 290     # Input shape
    291         3D tensor with shape `(batch_size, timesteps, input_dim)`.
    292 

~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py in preprocess_input(self, inputs, training)
   1031             warnings.warn('The `implementation` argument '
   1032                           'in `SimpleRNN` has been deprecated. '
-> 1033                           'Please remove it from your layer call.')
   1034         if K.backend() == 'theano' and (dropout or recurrent_dropout):
   1035             warnings.warn(

~/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in concatenate(tensors, axis)
   1525     """Computes log(sum(exp(elements across dimensions of a tensor))).
   1526 
-> 1527     This function is more numerically stable than log(sum(exp(x))).
   1528     It avoids overflows caused by taking the exp of large inputs and
   1529     underflows caused by taking the log of small inputs.

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py in concat(concat_dim, values, name)
   1073   ```
   1074 
-> 1075   would produce:
   1076 
   1077   ```python

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    667       `TypeError`.
    668     """
--> 669     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    670                     "Use `if t is not None:` instead of `if t:` to test if a "
    671                     "tensor is defined, and use TensorFlow ops such as "

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    174     TypeError: if shape is incorrectly specified or unsupported.
    175   """
--> 176   ctx = context.context()
    177   if ctx.executing_eagerly():
    178     t = convert_to_eager_tensor(value, ctx, dtype)

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    163 
    164     shape:          Optional dimensions of resulting tensor.
--> 165 
    166     name:           Optional name for the tensor.
    167 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    365 
    366   Returns:
--> 367     A `TensorProto`. Depending on the type, it may contain data in the
    368     "tensor_content" attribute, which is not directly useful to Python programs.
    369     To access the values you should convert the proto back to a numpy ndarray

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in _AssertCompatible(values, dtype)
    300 
    301 
--> 302 def _FilterStr(v):
    303   if isinstance(v, (list, tuple)):
    304     return _FirstNotNone([_FilterStr(x) for x in v])

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`
