### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by sth4nth** [tensorflow/tensorflow#6876] opened 2017-01-16 10:35 UTC
Run pip install tensorflow under python 3.6 get following:
 pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by asimshankar** [comment] 2017-01-16 17:10
I'm guessing you mean python 3.6?

We haven't finished testing with it just yet, so there are no releases for it. 

CC @martinwicke @gunan @yifeif - Will pips for py 3.6 be coming soon?

**Comment by sth4nth** [comment] 2017-01-17 04:15
Yes, you are right. I've modified the title. Thanks.

**Comment by gunan** [comment] 2017-01-17 06:14
Duplicate of #6876
Not in immediate plans, but we are considering py 3.6
Please follow instructions in the above issue to install for python 3.6.

**Closed by gunan** 2017-01-17 06:14 UTC
Labels: awaiting googler

**Comment by jerome-tan-git** [comment] 2017-03-29 06:29
> # **_[](url)_**
