### ISSUE TITLE
Feature Request: Argument of a complex number

### ISSUE THREAD

**Issue by zhengwx11** [tensorflow/tensorflow#6062] opened 2016-12-04 06:16 UTC
There has been `tf.complex_abs` for absolute value.
I request for something like `tf.complex_arg` which calculate the argument of complex numbers.
Constructor like `tf.complex_polar(abs, arg, name=None)` is also nice.

**Comment by shoyer** [comment] 2016-12-04 09:40
This is a dupe of https://github.com/tensorflow/tensorflow/issues/483

**Closed by shoyer** 2016-12-04 09:40 UTC
