### ISSUE TITLE
Tensort RT Engine Object Detection

### ISSUE THREAD

**Issue by snownus** [tensorflow/tensorflow#21081] opened 2018-07-24 08:11 UTC
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Requested batch size is not available and engine cache is full
	 [[Node: import/my_trt_op_16 = TRTEngineOp[InT=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], OutT=[DT_FLOAT], cached_engine_batches=[1], calibration_data="", fixed_input_size=true, input_shapes=[[?,1], [?,1], [?,1], [?,1]], max_cached_engines_count=1, output_shapes=[[?,4]], precision_mode="FP32", segment_funcdef_name="my_trt_op_16_native_segment", serialized_segment="\2007\000\...00\000\000", static_engine=true, workspace_size_bytes=65075264, _device="/job:localhost/replica:0/task:0/device:GPU:0"](import/MultiClassNonMaxSuppression/ClipToWindow/split, import/MultiClassNonMaxSuppression/ClipToWindow/split:2, import/MultiClassNonMaxSuppression/ClipToWindow/split:1, import/MultiClassNonMaxSuppression/ClipToWindow/split:3)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: import/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/strided_slice/_89 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1900_...ided_slice", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by tensorflowbutler** [comment] 2018-07-24 19:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by cy89** [comment] 2018-08-08 00:04
@samikama not clear whether this is a bug or working-as-intended. Would you please take a look?

**Comment by samikama** [comment] 2018-08-08 00:11
It looks like @snownus created the engine with a batch size smaller than the execution time. Either a bigger batch size should be used or dynamic op should be generated.

**Comment by tensorflowbutler** [comment] 2018-08-23 19:10
Nagging Assignee @samikama: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by snownus** [comment] 2018-08-24 01:19
@samikama , in faster rcnn, the second stage will have one more dimension. It seems tensorflow/tensorrt see another dimension as batch size and in fact, it isn't. Faster RCNN, at the second stage have 300 boxes.

**Comment by tensorflowbutler** [comment] 2018-09-07 18:54
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anhtu812** [comment] 2018-09-22 07:28
I have same error:

ResourceExhaustedError (see above for traceback): Requested batch size is not available and engine cache is full
         [[Node: model_1/prior_layer_1/my_trt_op_11 = TRTEngineOp[InT=[DT_FLOAT], OutT=[DT_FLOAT], cached_engine_batches=[10], calibration_data="", fixed_input_size=true, input_shapes=[[?,2]], max_cached_engines_count=1, output_shapes=[[?,2]], precision_mode="FP32", segment_funcdef_name="model_1/prior_layer_1/my_trt_op_11_native_segment", serialized_segment="\270\020\0...00\000\000", static_engine=true, workspace_size_bytes=18292682, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/prior_layer_1/ToFloat)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: while/Switch_2/_85 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2429_while/Switch_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopwhile/strided_slice_5/stack/_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

System:
ubuntu 16.04
tensorflow v1.10.1 from source
cuda 9, cudnn 7.1
tensorrt 4.1
python 3.5

**Comment by tensorflowbutler** [comment] 2018-10-07 12:36
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-22 19:04
Nagging Assignee @samikama: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by samikama** [comment] 2018-10-22 23:07
@snownus,

In your case it is a known issue of integration. Since TF doesn't have batch dimension concept and TRT requires a batch dimension, our assumption of Rank0 being the batch dimension is failing in FasterRCNN. It is being worked on.

**Comment by tensorflowbutler** [comment] 2018-11-06 18:54
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-21 18:55
Nagging Assignee @samikama: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-06 18:56
Nagging Assignee @samikama: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2019-02-09 18:46
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-02-24 18:43
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by samikama** [comment] 2019-03-01 02:48
@trevor-m @pooyadavoodi  Can you PTAL

**Comment by tensorflowbutler** [comment] 2019-03-15 12:53
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-04-02 21:35
It has been 32 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by trevor-m** [comment] 2019-04-03 00:05
Our (somewhat) recent improvements to the engine cache fixes this issue. It is available in the master branch of tensorflow (tf-nightly-gpu).

**Comment by jvishnuvardhan** [comment] 2019-04-16 00:25
I think it was resolved. I am closing the issue. If you think I made a mistake, please open another issue.

**Closed by jvishnuvardhan** 2019-04-16 00:25 UTC
Labels: comp:gpu, stat:awaiting response, type:bug/performance
