### ISSUE TITLE
bidirectional_rnn return state

### ISSUE THREAD

**Issue by lucaswiser** [tensorflow/tensorflow#1037] opened 2016-02-09 20:54 UTC
Hi I am wondering why the bi-directional rnn doesn't return a final state? From a code point of view it would be very easy to return. I.e line 301 in rnn.py  

 output_fw, _ = rnn(cell_fw, inputs, initial_state_fw, dtype,
                       sequence_length)

One could just return _ (named as final_state or whatever) with the concatenated outputs at the end. Is there any theoretical reason why you would never want the final output state? I was planning on feeding the final forward state as the initial state of the forward and backward rnn's on the next pass. The reason I am wanting to do this is the sequences I am working on are much longer than the number of steps I can unroll (seqs are about 15k on average, I'm unrolling 1000 steps) so continuing state is pretty important. It seems weird that the bidirectional rnn would even have the ability to input an initial state but you can't return the output state (what state would you feed in if not the output of the last pass?) 

Let me know what you think, i'm no rnn expert. 

Off topic but does anyone have any advice for super long sequences? What is the maximum you think I could unroll? Are there other techniques I could use besides long unroll and refeeding the outputs? Can LSTM even learn 1000+ step dependencies?

**Comment by vrv** [comment] 2016-02-09 20:56
Assigned to @lukaszkaiser because his name is so close to yours.

**Comment by lucaswiser** [comment] 2016-02-10 23:58
@lukaszkaiser Any word on this?

**Comment by vrv** [comment] 2016-02-11 05:37
@ebrevdo @ludimagister too

**Comment by lukaszkaiser** [comment] 2016-02-11 07:22
Sorry for the late reply. I think it is exactly as you said: the original reason was probably that there are 2 states, so it's not immediately clear whether to return them separately or concatenated or how, and so it was just not done until needed -- but it's clear we need this for long unrolls.

Eugene worked a lot recently on dynamic RNNs and it should probably also come to bidirectional RNNs. So I'm re-assinging to Eugene to make sure it's in line with the recent work. But if you have a small PR that just adds states on output from the forward and backward lines, then send it in, of course!

**Comment by ebrevdo** [comment] 2016-02-11 17:34
re: long sequences, what lukasz said.  dynamic RNN is coming.

re: outputting the final state.  PRs that return (outputs, final_state_fw, final_state_bw) are welcome.  please add unit tests.

since bidirectional_rnn is not yet part of the official API (not documented) we can still break the function signature.

**Comment by lucaswiser** [comment] 2016-02-11 18:07
@ebrevdo @lukaszkaiser I will make the pull request with (outputs, final_state_fw, final_state_bw) as the return value. Where do I add the unit tests?

**Comment by lukaszkaiser** [comment] 2016-02-12 00:41
Yes - I think it suffices if you modify the existing BidirectionalRNNTest there to test for the returned state. Thanks!

**Comment by girving** [comment] 2016-06-06 19:05
@ebrevdo: Do we have dynamic RNNs yet?

**Comment by ebrevdo** [comment] 2016-06-08 06:11
Do you need the final state?  The forward or backward?  How would you combine them?

**Comment by ebrevdo** [comment] 2016-06-08 06:12
And yes, tf.nn.dynamic_rnn.

**Comment by ebrevdo** [comment] 2016-06-10 18:50
See the PR coming in now that has a dynamic_bidirectional_rnn.  That will return the split final states.  We can't modify the output signature of bidirectional_rnn now for backwards compatibility reasons.

**Comment by ebrevdo** [comment] 2016-06-10 18:51
Marking "works as intended" for now, since the dynamic birnn should solve your problem.

**Closed by ebrevdo** 2016-06-10 18:51 UTC
Labels: triaged
