### ISSUE TITLE
Dataset.from_generator() returns a Dataset which freezes execution upon iteration

### ISSUE THREAD

**Issue by yonatankarimish** [tensorflow/tensorflow#43768] opened 2020-10-04 11:17 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Google Colab, running Ubuntu 18.04.5 LTS (Bionic Beaver)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **None**
- TensorFlow installed from (source or binary): **Source** (according to [this link](https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=8UvRkm1JGUrk))
- TensorFlow version (use command below): **v2.3.0-0-gb36436b087 2.3.0**
- Python version: **Python 3.6.9**

**running !bash tf_env_collect.sh threw an error, could not collect the following parameters:**
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source): ?
- CUDA/cuDNN version: ?
- GPU model and memory: ? (dynamically allocated by Google colab)

**Describe the current behavior**
According to the docs, tf.data.Dataset has a static method called from_generator(), constructing a dataset from a given iterable. I performed the following actions:

```
1) downloaded a text file from a link
2) parsed the file using a TextLineDataset (called raw_lines), then limited the size using dataset.take(100)

3) Created a new dataset (called after_generator_a) using an identity generator on the lines of raw_lines
4) used take(1) to obtain a subset dataset (from after_generator_a), containing a single record
5) iterated over the dataset to print the only record. The record was successfully printed

6) Created a new dataset (called after_generator_b) using an identity generator on the lines of after_generator_a
7) used take(1) to obtain a subset dataset (from after_generator_a), containing a single record
8) iterated over the dataset to print the only record. Nothing prints, and the Google Colab environment no longer responds
```

**Describe the expected behavior**
The code in 8) should print the value successfully, and not crash the Colab environment

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/11ILZUYpb-8Solip6xTbdV8elvPGOpngo?usp=sharing

**Other info / logs** 
None

**Comment by Saduf2019** [comment] 2020-10-05 10:39
I ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a65df5c1151a2d6185384c0200d4d266/untitled418.ipynb)

**Comment by aaudiber** [comment] 2020-10-07 16:54
@yonatankarimish This looks like an issue with the Python global interpreter lock (GIL). The function passed to `from_generator` will be executed in Python, which requires holding the GIL. If the function iterates over a second `from_generator` dataset, it will deadlock because the second `from_generator` dataset executes in a different thread, and that thread will also need to acquire the GIL.

Can you share the goal of using `from_generator` this way? We may be able to find simpler way to achieve the same thing.

**Comment by yonatankarimish** [comment] 2020-10-08 10:30
@aaudiber I would like to begin by mentioning I am relatively new to Python, and definitely new to Tensorflow.

1. The real-life code I was writing was an adaptation of mine to one of the official Keras tutorials, which involved some preprocessing of text. Considering that any medium-sized (and above) text files would probably cause an out-of-memory error if held in memory, I wrote a generator function to extract values from a text file into a Tensorflow `dataset`. Then used nearly identical code to extract values from the first dataset using a second generator into a second dataset.

(Of course, the first dataset is already held in-memory, so no memory usage improvements by using the second generator)

2. I didn't really wait for the issue to be resolved and just abandoned the `tf.data.Datasets` altogether. I got the code to work using standard python lists, but I was lucky my dataset was small enough to be held in memory. If my text files were too big to be held in memory, I'd have needed to persist the data to text files between generators, and this would have been a real issue.

3. I'd expect that if I perform an assignment of the form `my_dataset = tf.data.Dataset.from_generator()`, then by the next line of code the variable my_dataset will contain all my required data, with the generator function yielding all it's values. Therefore - i'd expect the global interpreter lock to be released by the thread performing the generator. Am I right making that assumption? if not, why would a thread that has nothing more to execute maintain a lock on the GIL?

4. Whatever the answer to 3) might be, the bug still persists. I think it's up to you guys to consider if you want to fix it. If you decide not to do so, I think it would have made things more clear if the documentation mentioned you cannot invoke the `from_dataset` function twice in a row.

**Comment by aaudiber** [comment] 2020-10-08 17:32
I agree this is a bug and would like to see it fixed. 

Regarding (3), it's important to understand that `tf.data.Dataset` objects don't perform any computation or contain any data. Datasets act like blueprints for creating iterators, which do the actual computation to produce data. When you assign `my_dataset = tf.data.Dataset.from_generator(...)`, the generator function will only be executed when you iterate through the dataset. Identity generators are not necessary to create dataset copies. You can reuse the same dataset instead. For example:

```
dataset = tf.data.Dataset.range(4)

times_two = dataset.map(lambda x: x*2)  
print(list(times_two.as_numpy_iterator()))  # prints [0, 2, 4, 6]

plus_one = dataset.map(lambda x: x+1)
print(list(plus_one.as_numpy_iterator()))  # prints [1, 2, 3, 4]

first_element = dataset.take(1)
print(list(first_element.as_numpy_iterator()))  # prints [0]
```

**Comment by yonatankarimish** [comment] 2020-10-09 12:03
@aaudiber Thanks for the clarification, I think I understand the bug now.

**Comment by sachinprasadhs** [comment] 2021-05-28 11:44
While trying to reproduce your issue in Tf Nightly 2.6 faced different error, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/6d8b5b0754747b67a886ba303bfc8a7d/43768.ipynb). Thanks!

**Comment by talipini** [comment] 2021-07-09 16:43
@aaudiber I might be running this same issue but not entirely sure. Any insights into [50637](https://github.com/tensorflow/tensorflow/issues/50637) - model.fit with dataset generator results in deadlock/hang. Appreciate any thoughts. Thanks

**Comment by chunduriv** [comment] 2022-06-25 11:17
@yonatankarimish,

Sorry for the late response. The freeze issue was fixed now. 

```
# The dataset is created
one_item = after_generator_b.take(1)
print(one_item)

# Iteration working now
for line in one_item:
  print(line)
```
Output:
```
<TakeDataset element_spec=TensorSpec(shape=<unknown>, dtype=tf.string, name=None)>
tf.Tensor(b'Go.\t\xd7\x9c\xd7\x9a!\tCC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #9435252 (Alkrasnov)', shape=(), dtype=string)
```

Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/01fa1a4f0001cc2865c786be085fefab/tensorflow-dataset-crash-case.ipynb) for reference. Thank you.

**Closed** 2022-07-09 12:39 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:data, TF 2.3
