### ISSUE TITLE
Deploy .pb frozen model in Android mobile

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#30064] opened 2019-06-23 23:53 UTC
Hello,
I have worked on iris detection ( in the human eye ) in the real-time project using deep learning. So I have used a CNN model based on facial landmarks detection using Tensorflow GPU version with regression predict and I have modified the number of points to get only the iris region, 
I have now .ckpt files trained the model with 146 000 steps and I have tried to freeze the model but I'm not sure that the process of the freeze is correct or no.
I get a .pb file with size 28 Mo.
I want to deploy and use this .pb file into an Android application to detect the iris region by drawing the landmarks on it.
How can I use a .pb file for Android application?
How can I extract the prediction from .pb file in the Android application?
Thanks

**Comment by gadagashwini** [comment] 2019-06-24 06:27
@abdou31 This [document](https://www.tensorflow.org/lite/convert/cmdline_examples) will guide you how to convert frozen graph to lite model. Let us know if that helps you. Thanks!

**Comment by abdou31** [comment] 2019-06-24 12:31
Thanks, I will see it

**Comment by gadagashwini** [comment] 2019-06-26 05:48
@abdou31 Can we close this issue.Since it is not bug/performance or build/install issue. Thanks!

**Comment by abdou31** [comment] 2019-06-26 07:16
I have successfully converted .pb frozen model to tflite model but the problem I didn't know that this is correct or no.
Do you have idea how can I know that the file generated ( tflite ) is corrected?
I write this because I didn't have any about output and input nodes setted are correct or no?

**Comment by gadagashwini** [comment] 2019-06-26 11:04
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by abdou31** [comment] 2019-06-26 11:33
Ok, but can you tell me where I can post this issue?

**Comment by gadagashwini** [comment] 2019-06-26 11:55
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). Thanks!

**Comment by gadagashwini** [comment] 2019-06-26 12:00
@abdou31 Have look on [tensorflow lite guide](https://www.tensorflow.org/lite/guide/android) for android app. Thanks!

**Comment by abdou31** [comment] 2019-06-26 12:07
Actually, I ask this question in StackOverflow but I didn't get any answer.
I don't know why but I think that the community didn't give any importance to questions related to IA (Deep learning  and Machine learning).

**Comment by ymodak** [comment] 2019-07-03 18:33
Closing this issue since the original title of the issue is resolved. Please post a new issue if facing additional problems unrelated to original issue. This will help us to keep track of the topics discussed. Thanks!

**Closed by ymodak** 2019-07-03 18:33 UTC
Labels: comp:lite, type:support

**Comment by abdou31** [comment] 2019-07-03 19:00
This problem is solved.
To deploy a model into Android Studio. it should using a tflite model not a pb model

**Comment by shbnm21** [comment] 2020-01-20 14:11
@abdou31 have u able to deploy the model into Android?
If yes can u tell me how did u test  tflite model?

**Comment by gadagashwini** [comment] 2020-01-21 05:05
@shbnm21, 
Please take a look at [android guide doc](https://www.tensorflow.org/lite/guide/android).

**Comment by shbnm21** [comment] 2020-01-21 09:04
@gadagashwini I will look into that.
I have used a pretrained model (GAN model) for face attribute manipulation .converted into .pb file.The size of .pb file is 166mb.The model is based on tensorflow 1.15 .I have googled about deployment of the model on Android.some blogs says to use .pb file into Android and some says to use tflite .
Now I am confused can u provide any documentation on how to convert .pb file into tflite and to test it's accuracy.
Also I want to know whether tflite can be used to convert GAN models.

**Comment by gadagashwini** [comment] 2020-01-22 09:36
@shbnm21,
Please find the documentation on how to convert pb to lite model in this [link](https://www.tensorflow.org/lite/convert/cmdline_examples#convert_a_tensorflow_graphdef_). Thanks!

**Comment by shbnm21** [comment] 2020-01-22 23:05
@gadagashwini thank you

**Comment by nihkilft123** [comment] 2020-07-30 05:10
You are right there are some apps [like this](https://play.google.com/store/apps/details?id=com.bgstudio.auto.removebg) which using direct .pb file in their app. I don't know how but I found they are using .pb (Frozen model) in their app! So, its possible there is some technique must be to use it!

**Comment by shbnm21** [comment] 2020-08-21 04:41
@nihkilft123 
Do u know anything how faceapp has deployed their model on android?
My understanding is they have created API and process the image on server and send back the results on Android.
