### ISSUE TITLE
get error when get labels of TFRecord dataset made by myself

### ISSUE THREAD

**Issue by yangkun1993** [tensorflow/tensorflow#5963] opened 2016-11-30 02:22 UTC
I use the cifar10 model train my own TFRecord dataset ,it's running on Ubuntu 14.4 without error,but getting these errors when I run it on Mac or GPU server。And I am sure the labels of my dataset are right ,I don't know why get labels bigger than 10 ,I just have 10 classifications。

I use this code write images and labels in binfile:

image_raw = image.tostring()
        example = tf.train.Example(features=tf.train.Features(feature={
            'image_raw' : _bytes_feature(image_raw),
            'height' : _int64_feature(image.shape[0]),
            'width' : _int64_feature(image.shape[1]),
            'deepth' : _int64_feature(image.shape[2]),
            'label' : _int64_feature(label)
            }))
        writer.write(example.SerializeToString())
    writer.close()

The errors:

W tensorflow/core/framework/op_kernel.cc:975] Invalid argument: Received a label value of 245 which is outside the valid range of [0, 10).  Label values: 180 96 226 166 162 179 147 115 162 141 150 136 129 118 162 141 78 154 133 155 89 184 116 179 176 70 209 177 65 177 89 36 80 139 117 187 115 182 106 42 203 120 48 72 96 126 74 123 134 115 112 154 128 163 64 113 35 140 198 193 189 67 164 110 117 61 215 186 189 84 95 206 163 82 122 160 37 179 236 157 140 181 178 128 67 114 43 211 143 70 0 91 184 142 172 127 80 160 127 90 62 151 158 23 180 192 21 97 125 94 98 136 125 190 158 128 119 30 198 111 206 66 137 126 245 210 158 188
Traceback (most recent call last):
  File "/Users/yangk/cifar10/cifar10_train.py", line 137, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/yangk/cifar10/cifar10_train.py", line 133, in main
    train()
  File "/Users/yangk/cifar10/cifar10_train.py", line 103, in train
    _, loss_value = sess.run([train_op, loss])
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of 245 which is outside the valid range of [0, 10).  Label values: 180 96 226 166 162 179 147 115 162 141 150 136 129 118 162 141 78 154 133 155 89 184 116 179 176 70 209 177 65 177 89 36 80 139 117 187 115 182 106 42 203 120 48 72 96 126 74 123 134 115 112 154 128 163 64 113 35 140 198 193 189 67 164 110 117 61 215 186 189 84 95 206 163 82 122 160 37 179 236 157 140 181 178 128 67 114 43 211 143 70 0 91 184 142 172 127 80 160 127 90 62 151 158 23 180 192 21 97 125 94 98 136 125 190 158 128 119 30 198 111 206 66 137 126 245 210 158 188
	 [[Node: cross_entropy_per_example/cross_entropy_per_example = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](softmax_linear/softmax_linear, Cast_4)]]

Caused by op u'cross_entropy_per_example/cross_entropy_per_example', defined at:
  File "/Users/yangk/cifar10/cifar10_train.py", line 137, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/yangk/cifar10/cifar10_train.py", line 133, in main
    train()
  File "/Users/yangk/cifar10/cifar10_train.py", line 76, in train
    loss = cifar10.loss(logits, labels)
  File "/Users/yangk/cifar10/cifar10.py", line 289, in loss
    logits, labels, name='cross_entropy_per_example')
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1537, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2378, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Received a label value of 245 which is outside the valid range of [0, 10).  Label values: 180 96 226 166 162 179 147 115 162 141 150 136 129 118 162 141 78 154 133 155 89 184 116 179 176 70 209 177 65 177 89 36 80 139 117 187 115 182 106 42 203 120 48 72 96 126 74 123 134 115 112 154 128 163 64 113 35 140 198 193 189 67 164 110 117 61 215 186 189 84 95 206 163 82 122 160 37 179 236 157 140 181 178 128 67 114 43 211 143 70 0 91 184 142 172 127 80 160 127 90 62 151 158 23 180 192 21 97 125 94 98 136 125 190 158 128 119 30 198 111 206 66 137 126 245 210 158 188
	 [[Node: cross_entropy_per_example/cross_entropy_per_example = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](softmax_linear/softmax_linear, Cast_4)]]

**Comment by poxvoculi** [comment] 2016-12-01 00:20
This looks like a duplicate of #5932.  There's some new information, but not enough that I can easily reproduce or diagnose the problem.  Unless there's good evidence of a bug, this kind of question is better asked on stackoverflow.  You're more likely to get a helpful response if you can reduce it to an easily reproduced problem.  Just guessing, I think maybe your model structure isn't what you think it is, so the wrong values are being propagated where labels are expected.  Or alternatively, you're feeding the wrong format data.

**Closed** 2016-12-01 00:20 UTC
Labels: stackoverflow
