### ISSUE TITLE
 C++ compilation of rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed: 

### ISSUE THREAD

**Issue by ElviseZhou** [tensorflow/tensorflow#8973] opened 2017-04-05 08:58 UTC
I am installing tensorflow with GPU and meeting some problems:

WARNING: /home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING:  #/home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/EI/tensorflow/tensorflow/core/BUILD:1280:1: C++ compilation of rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 41 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1994.312s, Critical Path: 8.68s

Operating System: Ubuntu 16.04LTS
gcc  4.9.3
bazel :0.4.5
python:3.6.0
CUDA:8.0.61_375.62
cuDNN:5.1.1

**Comment by asimshankar** [comment] 2017-04-05 17:11
As suggested in the logs, try using the `--verbose_failures` flag for bazel to get the exact command being executed that fails. Then you should be able to execute that command and get more information as to the cause of the failure.

**Comment by ElviseZhou** [comment] 2017-04-06 01:28
@asimshankar  well ,I did use --verbose_failures, but I still can't found what's wrong with it .
en...can the problem be related with anaconda ? the java version "1.8.0_121"seems like no problem.

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: /home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/EI/tensorflow/tensorflow/core/BUILD:1280:1: C++ compilation of rule '//tensorflow/core:lib_hash_crc32c_accelerate_internal' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/EI/.cache/bazel/_bazel_EI/2e0782785985dd9cb1b5d0cb62ad2606/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH='/usr/local/cuda-8.0/lib64:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:/usr/local/cuda/lib64' \
    PATH='/usr/local/cuda-8.0/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/home/EI/bin:/home/EI/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/usr/local/cuda/bin:/home/EI/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin' \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/core/_objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.d '-frandom-seed=bazel-out/host/bin/tensorflow/core/_objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.o' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-DGOOGLE_CUDA=1' -msse3 -pthread -msse4.2 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/lib/hash/crc32c_accelerate.cc -o bazel-out/host/bin/tensorflow/core/_objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2.081s, Critical Path: 1.32s

**Comment by asimshankar** [comment] 2017-04-06 08:22
@ElviseZhou - with `--verbose_failures` you have the exact command that failed (in this case, some invocation of `gcc`). Perhaps you can execute that and see what the error is. From the log above, it seems that the command is something like:

```
cd /home/EI/.cache/bazel/bazel_EI/2e0782785985dd9cb1b5d0cb62ad2606/execroot/tensorflow && exec env - LD_LIBRARY_PATH='/usr/local/cuda-8.0/lib64:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:/usr/local/cuda/lib64' PATH='/usr/local/cuda-8.0/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/home/EI/bin:/home/EI/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/usr/local/cuda/bin:/home/EI/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin' external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -MD -MF bazel-out/host/bin/tensorflow/core/objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.d '-frandom-seed=bazel-out/host/bin/tensorflow/core/objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.o' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-DGOOGLE_CUDA=1' -msse3 -pthread -msse4.2 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE="redacted"' '-D__TIMESTAMP_="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/core/lib/hash/crc32c_accelerate.cc -o bazel-out/host/bin/tensorflow/core/_objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.o
```

**Comment by ElviseZhou** [comment] 2017-04-06 09:10
@asimshankar  thanks ,the probblem solved ,but  en... it seems like another problem appears .it's 
weird...[https://github.com/tensorflow/tensorflow/issues/9015](url)

**Comment by asimshankar** [comment] 2017-04-06 09:18
How was the problem solved? Did you figure out what the error was?

Closing this out since it seems you've filed a duplicate.

**Closed by asimshankar** 2017-04-06 09:18 UTC
Labels: stat:awaiting response
