### ISSUE TITLE
no such package '@png_archive//

### ISSUE THREAD

**Issue by yanhaiming56** [tensorflow/tensorflow#21880] opened 2018-08-26 08:02 UTC
When I compile tensorflow 1.10 from source code on windows10, it reported the error "no such package '@png_archive//"
I have installed the bazel, msys2, vs2017 and set the environment of PAHT,bazel_sh,bazel_vc.

**Comment by elvys-zhang** [comment] 2018-08-31 03:30
I have met the same question using tf-serving 1.9.0, bazel 0.15.2, while compiling GPU version. Looking forward to a solution.

**Comment by gunan** [comment] 2018-08-31 20:36
@meteorcloudy 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by meteorcloudy** [comment] 2018-09-03 07:49
@yanhaiming56 Can you provide information about which Bazel version you are using and the exact error message? 
Although you shouldn't have to, but did you try run `bazel clean --expunge` before running the build command?

**Comment by meteorcloudy** [comment] 2018-09-12 10:31
@elvys-zhang Can you provide the exact error message Bazel output? I'm not able to reproduce the same issue on my Linux machine.

**Comment by PinkySan** [comment] 2018-09-12 20:17
Having the same problem. 
Windows 10
bazel 0.16.1
tensorflow 1.10.1

`bazel --output_user_root=build_temp build -c opt --copt=/arch:AVX tensorflow:libtensorflow_cc.so`

got this command from the \tensorflow\tools\ci_build\windows\libtensorflow_cpu.sh

**Comment by elvys-zhang** [comment] 2018-09-13 02:08
@meteorcloudy Have figured it out. I missed some info before. After installing patch by "yum install -y patch", it worked fine. Thx.

**Comment by gunan** [comment] 2018-09-13 07:30
@PinkySan Please refer to this doc to build TF on windows:
https://www.tensorflow.org/install/install_sources_windows

You should not be building libtensorflow_cc.so on windows.
However, the problem you are facing is due to missing packages on your system
`/usr/bin/bash: patch: Could not find command`
Please see the bazel installation instructions, and make sure you follow all the steps.

Looks like the initial report is missing vital information, and later reported issues do not seem to fully relate to the original issue.
Closing until we get the detailed information we need to debug.

**Closed by gunan** 2018-09-13 07:30 UTC

**Comment by pmvsnlab** [comment] 2018-09-24 20:41
@gunan 

> You should not be building libtensorflow_cc.so on windows.

How can we use C++ Tensorflow with Windows therefore?

**Comment by UndeadBlow** [comment] 2018-09-24 20:42
@gunan 

> You should not be building libtensorflow_cc.so on windows.

How can we use C++ Tensorflow with Windows therefore?

**Comment by gunan** [comment] 2018-09-24 20:50
@meteorcloudy @asimshankar to include in the discussion.
But the ".so" file extensions are the shared object extensions for linux.
Unless bazel intelligently replaces the "so" with "dll", your OS would be confused trying to load the resulting "so" file.

If bazel does this intelligently, still our build target should not have the "so" extension.
It should just be libtensorflow, and on macos the result will be a dylib, on windows it will be a dll, on linux it will be a so.

**Comment by meteorcloudy** [comment] 2018-09-25 07:51
@UndeadBlow You might find this script useful:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh

As pointed out by @gunan, the .so file built is actually a .dll file on Windows, you'll have to rename it to .dll to make it work on Windows.

**Comment by PinkySan** [comment] 2018-09-25 18:44
Do you rename the generated file from *.so into *.dll or do you rename it in the sh-file? Why does bazel not provide an OS independent target?

**Comment by meteorcloudy** [comment] 2018-09-26 12:35
@PinkySan you can just rename the generated file. The reason it's still generating a .so file on Windows is because the .so extension is embedded in the target name. This issue will be resolved in the future. Sorry for the trouble.

**Comment by PinkySan** [comment] 2018-09-26 18:45
@meteorcloudy That is a very uncommon behaviour. If it is a known problem, i can totally live with that. But does bazel support an installing target? It is pretty simple in CMake to create an INSTALL-Target, which contains the relevant binaries, includes, etc.

I therefore cannot understand the release note in 1.10, which discontinues the CMake support. Especially the integration of c++ tensorflow into another c++ project with CMake is really simple

`find_package(Tensorflow)`
`add_executable(myExe ...)`
`target_link_libraries(myExe PRIVATE tensorflow)`

#21409

**Comment by meteorcloudy** [comment] 2018-09-27 13:47
@PinkySan I totally under stand your concern. I'll be working on a solution to make the C++ library easier to use on Windows.

**Comment by Bowyee** [comment] 2018-11-14 12:20
I used following command to fix the issue on windows.
pip install png

**Comment by yonghenghuanmie** [comment] 2019-03-26 12:17
pacman -S msys/patch

**Comment by crazyn2** [comment] 2019-04-15 10:58
I solved this problem by using a VPN network.If the problem is different when you're trying , I guess  you like me the problem is due to the local network of your operator or country .
