### ISSUE TITLE
distributed tensorflow does not use GPU 1,2,3 on server B 

### ISSUE THREAD

**Issue by hellf** [tensorflow/tensorflow#3234] opened 2016-07-08 07:13 UTC
### Environment info
Operating System: Ubuntu 14.04 desktop
Installed version of CUDA and cuDNN: 7.5,  5.0.5
 tensorflow 0.9.0.rc0 is installed from source.

--------------------------------------------------------------------------------------------------------------------

I'm using distributed tensorflow with 8 Titan-x GPUs in two servers.
4 GPUs are in one server.

GU=gpu utilization

These are what I tested, changing ps and workers.
Cifar-10, ResNet. batchsize=32.

1) serverA (1 ps, 1 worker),  serverB (None) ==> Mem allocated on (serverA: GPU 0: GU>30%)

2) serverA (1 ps, 4 workers),  serverB (None)  ==> Mem allocated on (serverA: GPU 0,1,2,3: GU>30%)

3) serverA (1 ps, 1 workers),  serverB (1 ps, 1 worker)  ==> Mem allocated on (serverA: GPU 0,1: GU>30%), (serverB: GPU 0: GU ~8%). 

4) serverA (1 ps, 1 workers),  serverB (1 ps, 2 workers)  ==> Mem allocated on (serverA: GPU 0,1,2: GU>30%), (serverB: GPU 0: GU ~8%).

5) serverA (1 ps, 1 workers),  serverB (1 ps, 3 workers)  ==> Mem allocated on (serverA: GPU 0,1,2,3: GU>30%), (serverB: GPU 0: GU ~8%).

6) serverA (1 ps, 4 workers),  serverB (1 ps, 4 workers)  ==> Mem allocated on (serverA: GPU 0,1,2,3: GU>50%), (serverB: GPU 0: GU ~8%).

It looks dist tensorflow does not use GPU on serverB.

next is "nvidia-smi" in case of 6)

((serverA)) Mem allocated on GPU 0,1,2,3
![image](https://cloud.githubusercontent.com/assets/9377459/16659014/75379c00-44a3-11e6-957c-845bed33f492.png)

((serverB)) Mem allocated on GPU 0 (last one is 0)
![image](https://cloud.githubusercontent.com/assets/9377459/16658977/5748e794-44a3-11e6-94d1-f2eac24639cf.png)

I use replica_device_setter to allocate workers to GPU.

    if FLAGS.job == "ps":
        server.join()
    elif FLAGS.job == "worker":
        # Assigns ops to the local worker by default.
        with tf.device(tf.train.replica_device_setter(worker_device="/gpu:%d" % (FLAGS.task_id%4), cluster=cluster)):

please help me.

**Comment by aselle** [comment] 2016-07-09 01:01
Could you please take a look @mrry.

**Comment by hellf** [comment] 2016-07-10 15:26
https://github.com/aselle I could not find anything related with this issue in  https://github.com/mrry

Could you tell me which file or directory should I look at?

**Comment by jhollowayj** [comment] 2016-07-11 16:58
@hellf, mrry is a person.  That link goes to his personal github page.
aselle was asking mrry to to take a look at the issue.

**Comment by mrry** [comment] 2016-07-12 04:57
Hi there! I'm on vacation right now, but if this is still a problem in a fortnight, feel free to reassign to me.

**Comment by hellf** [comment] 2016-07-13 05:19
Thanks all :)
I'm still in this problem.

**Comment by mrry** [comment] 2016-08-01 15:15
It looks like the problem is in your `worker_device="/gpu:%d" % (FLAGS.task_id%4)` argument to `tf.train.replica_device_setter()`. There are two parts to the problem:

1. The device string doesn't specify a task ID (i.e. `"/task:%d" % (FLAGS.task_id)`). Unless you have specified `device_filters` in your session configuration, this will result in all ops being placed in task 0, which runs in server A.

2. Each process on a particular server is creating devices `"/gpu:0"`, ... ,`"/gpu:3"`, because by default a server (or a single-process `tf.Session`) will create one TensorFlow device per physical device on the system. This will lead to inefficient memory allocation between the processes. You should use the `CUDA_VISIBLE_DEVICES` environment variable to limit each server to being able to see only a single device, which will be available as `"/gpu:0"` in that process. 

After setting `CUDA_VISIBLE_DEVICES` appropriately, you can use `worker_device="/job:worker/task:%d/gpu:0" % (FLAGS.task_id)` as the argument to `tf.train.replica_device_setter()`, and the utilization should be balanced across the GPUs (assuming that you build the same graph in each of your worker processes, and use something like the `tf.train.Supervisor` to manage the distributed execution).

**Comment by girving** [comment] 2016-08-08 17:52
Closing for now due to lack of response.  @hellf I'm happy to reopen if more details emerge.

**Closed by girving** 2016-08-08 17:52 UTC
Labels: awaiting response
