### ISSUE TITLE
pass sample weight into py_func

### ISSUE THREAD

**Issue by acmilannesta** [tensorflow/tensorflow#28619] opened 2019-05-11 01:54 UTC
I tried to use the sklearn roc_auc_score function in a customized metric and would like to pass the sample weight. Here is my code:

```
from sklearn.metrics import roc_auc_score
from keras.layers import Input, Dense
from keras.models import Model
from keras import backend as K
import tensorflow as tf
import numpy as np
from functools import partial

def auc(weight):
    def metric(y_true, y_pred):
        score = tf.py_func(partial(roc_auc_score, sample_weight=weight), (y_true, y_pred), tf.float32)
        K.get_session().run(tf.local_variables_initializer())
        return score
    return metric

x=Input(shape=(10, ))
weights = Input(shape=(1,))
hidden = Dense(10, activation='relu')(x)
result = Dense(1, activation='sigmoid')(hidden)
model = Model(inputs=[x, weights], outputs=result)
model.compile('adam', 'binary_crossentropy', metrics=[auc(weights)])

X = np.random.rand(10000, 10)
y = np.random.randint(2, size=(10000, 1))
w = np.random.rand(10000, 1)
X_val = np.random.rand(100, 10)
y_val = np.random.randint(2, size=(100, 1))
w_val = np.random.rand(100, 1)
model.fit([X, w], y, epochs=20, sample_weight=w.flatten(), validation_data=([X_val, w_val], y_val), verbose=2)

```
But I got the error message:
TypeError: object of type 'Tensor' has no len()
	 [[{{node metrics_7/metric/PyFunc}} = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_dense_4_target_5_0_2, dense_4/Sigmoid)]]

**Comment by achandraa** [comment] 2019-05-17 09:50
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by acmilannesta** [comment] 2019-05-18 12:52
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

Sure. I'm using tensorflow 1.13.1 on Python 3.6 and Win 10. I pip installed tensorflow.

**Comment by achandraa** [comment] 2019-05-20 09:41
I was able to reproduce the mentioned output on Colab with TensorFlow version 1.13.1.

**Comment by acmilannesta** [comment] 2019-05-20 14:43
> I was able to reproduce the mentioned output on Colab with TensorFlow version 1.13.1.

I also ran on Colab, but got the following error:

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From <ipython-input-2-ac708db9cd1d>:3: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 10000 samples, validate on 100 samples
Epoch 1/20
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-ac708db9cd1d> in <module>()
     19 y_val = np.random.randint(2, size=(100, 1))
     20 w_val = np.random.rand(100, 1)
---> 21 model.fit([X, w], y, epochs=20, sample_weight=w.flatten(), validation_data=([X_val, w_val], y_val), verbose=2)

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: TypeError: object of type 'Tensor' has no len()
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/ranking.py", line 356, in roc_auc_score
    sample_weight=sample_weight)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/ranking.py", line 328, in _binary_roc_auc_score
    sample_weight=sample_weight)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/ranking.py", line 618, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/ranking.py", line 399, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)

  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 231, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]

  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 231, in <listcomp>
    lengths = [_num_samples(X) for X in arrays if X is not None]

  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 148, in _num_samples
    return len(x)

TypeError: object of type 'Tensor' has no len()


	 [[{{node metrics/metric/PyFunc}}]]

**Comment by jvishnuvardhan** [comment] 2019-05-24 16:57
@acmilannesta The issue is with sklearn not with Tensorflow. Please post this issue in sklearn as `validation.py` in sklearn need to be updated with exception handling for this data type. Length estimation is throwing error. Thanks!

I am closing here. You can open it in sklearn repo. thanks!

**Closed by jvishnuvardhan** 2019-05-24 16:57 UTC
Labels: TF 1.13, comp:ops, type:support

**Comment by robieta** [comment] 2019-07-15 00:35
To follow up on this for anyone who comes across it.

The issue is that by passing sample weights through partial rather than as arguments in py_func (p.s. you can change to [numpy_function](https://www.tensorflow.org/api_docs/python/tf/numpy_function) to get rid of the deprecation warning), you're actually passing a symbolic Tensor to `roc_auc_score`, which doesn't know how to handle it. scikit-learn is going to add clearer error messaging (https://github.com/scikit-learn/scikit-learn/pull/14369), and I'm going to make make Tensors more explicit about when they can't be converted to NumPy arrays (https://github.com/tensorflow/tensorflow/pull/30694).
