### ISSUE TITLE
Gradient computation return None

### ISSUE THREAD

**Issue by dingevin** [tensorflow/tensorflow#34478] opened 2019-11-21 08:39 UTC
hello, i write an example to test **tf.while_loop** and **tf.TensorArray**,  it return None when compute gradients, it seem that there is no connection from input to output, i don't know why?

tensorflow version:  1.10.1
code:  https://github.com/dingevin/example/blob/master/example.py

log:
<tf.Variable 'forward/dense/kernel:0' shape=(1024, 512) dtype=float32_ref>
<tf.Variable 'forward/dense/bias:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'output/dense/kernel:0' shape=(10, 21504) dtype=float32_ref>
<tf.Variable 'output/dense/bias:0' shape=(10,) dtype=float32_ref>
**[(None, <tf.Variable 'forward/dense/kernel:0' shape=(1024, 512) dtype=float32_ref>), (None, <tf.Variable 'forward/dense/bias:0' shape=(1024,) dtype=float32_ref>), (<tf.Tensor 'gradients/output/dense/dense/MatMul_grad/tuple/control_dependency_1:0' shape=(10, 21504) dtype=float32>, <tf.Variable 'output/dense/kernel:0' shape=(10, 21504) dtype=float32_ref>), (<tf.Tensor 'gradients/output/dense/dense/add_grad/tuple/control_dependency_1:0' shape=(10,) dtype=float32>, <tf.Variable 'output/dense/bias:0' shape=(10,) dtype=float32_ref>)]**
Traceback (most recent call last):
  File "1.py", line 203, in <module>
    tf.app.run(main)
  File "/home/dingzhenyou/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "1.py", line 188, in main
    model.build_train_model()
  File "1.py", line 81, in build_train_model
    grads_and_vars = self.average_gradients(gv_list)
  File "1.py", line 100, in average_gradients
    expanded_g = tf.expand_dims(g, 0)
  File "/home/dingzhenyou/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/dingzhenyou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 136, in expand_dims
    return gen_array_ops.expand_dims(input, axis, name)
  File "/home/dingzhenyou/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2020, in expand_dims
    "ExpandDims", input=input, dim=axis, name=name)
  File "/home/dingzhenyou/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
**ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.**

**Comment by gadagashwini** [comment] 2019-11-22 08:13
@dingevin, Can you try with Tf latest 1.15 version and check still error persists or not. And also if possible provide the minimum code snippet to localize the reported issue. Thanks!

**Comment by dingevin** [comment] 2019-11-26 10:37
@gadagashwini  I have written the minimum code snippet as flow. other Tf version (1.14, 1.13) have been tried except 1.15, still error.  the variables in tf.while_loop has no gradients.
code:  [https://github.com/dingevin/example/blob/master/example.py](url)
log:
`<tf.Variable 'dense/kernel:0' shape=(512, 128) dtype=float32_ref>`
`<tf.Variable 'dense/bias:0' shape=(128,) dtype=float32_ref>`
`<tf.Variable 'output/output/kernel:0' shape=(128, 10) dtype=float32_ref>`
`<tf.Variable 'output/output/bias:0' shape=(10,) dtype=float32_ref>`
`(None, <tf.Variable 'dense/kernel:0' shape=(512, 128) dtype=float32_ref>)`
`(None, <tf.Variable 'dense/bias:0' shape=(128,) dtype=float32_ref>)`
`(<tf.Tensor 'gradients/output/output/MatMul_grad/tuple/control_dependency_1:0' shape=(128, 10) dtype=float32>, <tf.Variable 'output/output/kernel:0' shape=(128, 10) dtype=float32_ref>)`
`(<tf.Tensor 'gradients/output/output/add_grad/tuple/control_dependency_1:0' shape=(10,) dtype=float32>, <tf.Variable 'output/output/bias:0' shape=(10,) dtype=float32_ref>)`

**Comment by gadagashwini** [comment] 2019-11-28 10:24
@dingevin, Tried reproducing the reported issue, Looks like some entities are not defined.
Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/67f894fcd027eefdcf8a86e1fbba58c6/untitled277.ipynb) and provide the more info. Thanks!

**Comment by dingevin** [comment] 2019-11-29 07:51
i am sorry. that's complete code. https://github.com/dingevin/example/blob/1f3800fecd4251800cd59a41028b51402bae9e29/example.py#L21

**Comment by gadagashwini** [comment] 2019-12-05 05:40
@dingevin, Tried replicate the reported issue but got different error. 
Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/037682e77154d98c5b53f69e0c69a312/untitled277.ipynb). Thanks!

**Comment by dingevin** [comment] 2019-12-06 08:15
@gadagashwini  that is my asked question.
`(None, <tf.Variable 'dense/kernel:0' shape=(512, 128) dtype=float32_ref>)`
`(None, <tf.Variable 'dense/bias:0' shape=(128,) dtype=float32_ref>)`
`(<tf.Tensor 'gradients/output/output/MatMul_grad/tuple/control_dependency_1:0' shape=(128, 10) dtype=float32>, <tf.Variable 'output/output/kernel:0' shape=(128, 10) dtype=float32_ref>)`
`(<tf.Tensor 'gradients/output/output/add_grad/tuple/control_dependency_1:0' shape=(10,) dtype=float32>, <tf.Variable 'output/output/bias:0' shape=(10,) dtype=float32_ref>)`

parameters outside the loop has gradients but inside return none. that confused me.

**Comment by dingevin** [comment] 2019-12-13 03:21
@ymodak  Any progress?

**Comment by dingevin** [comment] 2019-12-16 08:07
I known it, the finial output to be a function of gather_x, not x.

**Comment by ymodak** [comment] 2020-01-10 23:02
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2020-01-10 23:02 UTC
Labels: TF 1.15, comp:ops, type:bug
