### ISSUE TITLE
what is the model inception5h?

### ISSUE THREAD

**Issue by molo32** [tensorflow/tensorflow#34673] opened 2019-11-28 04:50 UTC
With what data is this model trained?

How do I keep training it?

**Comment by ravikyram** [comment] 2019-11-29 06:03
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ymodak** [comment] 2019-12-04 22:10
@molo32 The inception model is trained using the Imagenet dataset.
See http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
You may use transfer learning approach to continue training further.

**Comment by tensorflowbutler** [comment] 2019-12-19 12:29
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2019-12-20 08:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-12-20 08:26 UTC
Labels: comp:model, stat:awaiting response, type:support
