### ISSUE TITLE
An error occurred while starting the kernel on Windows

### ISSUE THREAD

**Issue by SMH17** [tensorflow/tensorflow#8334] opened 2017-03-13 00:44 UTC
I get this error when start the execution of some optical recognition routines
Tensorflow: 1.0.1 
OS: Windows 10 x64
Nvidia cuDNN: 5.1
Nvidia CUDA: 8.0

```
An error occurred while starting the kernel
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 670
major: 3 minor: 0 memoryClockRate (GHz) 0.95
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.36GiB
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0 
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0: Y 
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) ‑> (device: 0, name: GeForce GTX 670, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) ‑> (device: 0, name: GeForce GTX 670, pci bus id: 0000:01:00.0)
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) ‑> (device: 0, name: GeForce GTX 670, pci bus id: 0000:01:00.0)
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) ‑> (device: 0, name: GeForce GTX 670, pci bus id: 0000:01:00.0)
I c:\tf_jenkins\home\workspace\release‑win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) ‑> (device: 0, name: GeForce GTX 670, pci bus id: 0000:01:00.0)

...
```

**Comment by mrry** [comment] 2017-03-13 15:14
This has been fixed at HEAD since January 17th. You can safely ignore this error message, or upgrade to a nightly build to use the fix. Closing as a duplicate of #8336.

**Closed by mrry** 2017-03-13 15:14 UTC

**Comment by SMH17** [comment] 2017-03-13 15:42
@mrry The linked issue was reported for the previous 1.0.0 version compared to the latest 1.0.1 that I'm using. In what release will be included?

**Comment by mrry** [comment] 2017-03-13 15:46
Sadly the fix was not cherry-picked into the 1.0.1 release. It will be in 1.1.

(@gunan I assume we're still not doing a 1.0.2? If we are, we should definitely cherry-pick this fix.)

**Comment by gunan** [comment] 2017-03-13 17:34
We will start working on 1.1 soon, that will definitely have the fix. since 1.1 is around the corner, I think we will not do 1.0.2

**Comment by githubhaohao** [comment] 2017-03-15 01:13
I get it.Thanks.

**Comment by mrnameless123** [comment] 2017-03-26 03:52
@gunan sadly I just installed Tensorflow today March 26th and received the same message.

**Comment by gunan** [comment] 2017-03-26 05:53
@mrnameless123 Could you file a new issue, filling in the issue template as much as you can?
