### ISSUE TITLE
Share variable across devices in Tensorflow 2 cluster

### ISSUE THREAD

**Issue by Fabien-Couthouis** [tensorflow/tensorflow#47930] opened 2021-03-19 19:25 UTC
Hello,
I would like to use Tensorflow 2.4 in order to share a variable across devices on a cluster. In my use case, I want to share a queue stored on a parameter server that can be filled by all the workers. I know this was possible with tensorflow 1 but I do not understand how to do this in tf2 with the strategy API and the documentation does not seem to mention it. 
Here is my code to do this with a simple variable:

```python
# run.py
import tensorflow as tf
import os
import json
import argparse
import time

parser = argparse.ArgumentParser()
parser.add_argument('--type', type=str, default='ps', required=False)
parser.add_argument('--index', type=int, default=0, required=False)
args = parser.parse_args()

cluster_dict = {
    "cluster": {
        "worker": ['localhost:50848'],
        "ps": ['localhost:50849'],
    },
    "task": {"type": args.type, "index": args.index}
}


os.environ["GRPC_FAIL_FAST"] = "use_caller"
os.environ["TF_CONFIG"] = json.dumps(cluster_dict)
cluster_resolver = tf.distribute.cluster_resolver.TFConfigClusterResolver()

server = tf.distribute.Server(
    cluster_resolver.cluster_spec(), job_name=cluster_resolver.task_type,
    task_index=cluster_resolver.task_id, protocol="grpc"
)
# Initializes tf server internally.
strategy = tf.distribute.experimental.ParameterServerStrategy(cluster_resolver)


with tf.device('/job:ps/task:0'):
    v = tf.Variable(
        1, name='test')

if cluster_resolver.task_type == "worker":
    while True:
        with tf.device('/job:ps/task:0'):
            # <tf.Variable 'test:0' shape=() dtype=int32, numpy=>: ok
            print(v.device)
            # Increments variable on the worker
            v.assign_add(1)
            # v is incremented: ok
            print('v:', v)

            time.sleep(1)
elif cluster_resolver.task_type == "ps":
    with tf.device('/job:ps/task:0'):
        while True:
            # <tf.Variable 'test:0' shape=() dtype=int32, numpy=>: ok
            print(v.device)
            # v should be incremented by the worker
            print(v)
            # v=1: not working
            time.sleep(1)

else:
    pass
```

I then launch the worker and the parameter server using:
```
python run.py --type ps
```
and
```
python run.py --type worker
```

However the code in its current form does not work: the variable stored in the parameter server is updated by the worker but not visible by the parameter server. Note that I use the PS strategy but I have also tried the Mirrored Strategy. 

Is this behavior (i.e. sharing a custom variable over different workers of the cluster) supported in tf2? If so, could someone help me with the synthax, I would be very grateful! 

Thanks!

**Comment by Saduf2019** [comment] 2021-03-26 10:50
@Fabien-Couthouis 

Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!

**Comment by Fabien-Couthouis** [comment] 2021-03-28 12:34
Hi @Saduf2019,

Thanks for the answer, a [stackoverflow issue](https://stackoverflow.com/questions/66669910/share-variable-across-devices-in-tensorflow-2-cluster) has already be opened (without any answer unfortunately). I understand you have a lot of work with tensorflow and you cannot provide the support but I was just wondering if my use case was doable in tensorflow 2, and if not, this would be a usefull feature to add in the future.

**Comment by jvishnuvardhan** [comment] 2021-03-31 20:09
@Fabien-Couthouis Please follow the guide on distribution strategy [here](https://www.tensorflow.org/guide/distributed_training).  In the tutorial section of TF website, there are lot of tutorials on [distribution strategies](https://www.tensorflow.org/tutorials/distribute/keras). 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks! 

Please verify those guides and tutorials on distribution strategies and close this issue. thanks!

**Closed** 2021-04-01 13:18 UTC
Labels: TF 2.4, comp:dist-strat, stat:awaiting response, type:support
