### ISSUE TITLE
Issue with tf.InteractiveSession()

### ISSUE THREAD

**Issue by wgmao** [tensorflow/tensorflow#6553] opened 2016-12-29 03:37 UTC
I try to train a neural net with nested loop `tf.while_loop`. If I start the session with `sess = tf.Session()`, the training process will start with the following log for one batch. There seems to be some memory issue, but it still works.
[log1.txt](https://github.com/tensorflow/tensorflow/files/676557/log1.txt)

But if I start with `sess = tf.InteractiveSession()`, there will be errors. The log is as follows. `tf.InteractiveSession()` isn't really different from `tf.Session()` by tutorial. I just wonder what is wrong here.
[log2.txt](https://github.com/tensorflow/tensorflow/files/676555/log2.txt)

### Environment info
- Ubuntu  14.04.5 LTS
- Python 2.7.6
- cuda 8, V8.0.44
- cudnn 5.1.3
- TensorFlow 0.12.0-rc0
- GeForce GTX 1080

**Comment by yaroslavvb** [comment] 2017-01-03 18:46
You can see [from implementation](https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/python/client/session.py#L1315) that `InteractiveSession` uses regular `Session`, and registers it to be the default session. So I can't see how the difference would cause DeviceAssignment error you are seeing. If this is still a problem, can you provide a reproducible example?


```
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'gradients/while/while/TensorArrayWriteV2_grad/TensorArrayReadV2/f_acc': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'
Colocation Debug Info:
Colocation group had the following types and devices: 
TensorArrayWriteV2: GPU CPU 
TensorArrayReadV2: GPU CPU 
TensorArrayScatterV2: GPU CPU 
TensorArrayGatherV2: GPU CPU 
Range: GPU CPU 
TensorArraySizeV2: GPU CPU 
TensorArrayV2: GPU CPU 
Stack: GPU CPU 
StackPop: GPU CPU 
ControlTrigger: GPU CPU 
Const: GPU CPU 
RefEnter: GPU CPU 
Enter: GPU CPU 
TensorArrayGradV2: GPU CPU 
Identity: GPU CPU 
StackPush: GPU CPU 
Exit: GPU CPU 
	 [[Node: gradients/while/while/TensorArrayWriteV2_grad/TensorArrayReadV2/f_acc = Stack[_class=["loc:@while/TensorArray_2", "loc:@while/while/Identity_1"], elem_type=DT_INT32, stack_name=""]()]]
```

**Comment by aselle** [comment] 2017-01-17 19:20
Closing due to lack of recent activity. We will reopen when additional information becomes available. Thanks!

**Closed by aselle** 2017-01-17 19:20 UTC
Labels: awaiting response
