### ISSUE TITLE
MultiWorkerMirroredStrategy distribution error BaseCollectiveExecutor::StartAbort Invalid argument: Lower bound check fail for input 1 from node Mkl2Tf/_30 to node scoped_allocator_concat_1_1

### ISSUE THREAD

**Issue by RogueLogix** [tensorflow/tensorflow#34213] opened 2019-11-13 02:41 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no-ish, [keras multi-worker mirrored example](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora Server 31
- TensorFlow installed from (source or binary): source (master branch, commit 73a34133f6a414a03e54971f4975584c3d6251cc), identical on both machines
- TensorFlow version (use command below): v1.12.1-17924-g73a34133f6 2.0.0
- Python version: 3.7.5
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source): GCC 9.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Crashes at model.fit

**Describe the expected behavior**
Not, crash?

**Code to reproduce the issue**
Exact code used
[Node0](https://pastebin.com/CtTjs146)
[Node1](https://pastebin.com/5LtGA6Hd)

**Other info / logs**
Logs from run
[Node0](https://pastebin.com/HQAQwtBg)
[Node1](https://pastebin.com/ZFUjWkzf)

To compile on Fedora 31 I did need to use a grpc version patch, this patch can be found [here](https://github.com/tensorflow/tensorflow/issues/33758#issuecomment-547867642) in issue #33758. It consists of running this command before compiling tensorflow.
```
curl -L https://github.com/tensorflow/tensorflow/compare/master...hi-ogawa:grpc-backport-pr-18950.patch | git apply
```

bazel configured with Python 3 directory, and default otherwise.
bazel build command used is as follows
```
bazel build --config=mkl --config=opt //tensorflow/tools/pip_package:build_pip_package
```

**Comment by RogueLogix** [comment] 2019-11-17 00:20
This seems to be a MKL related issue, as I got it working by recompiling without --config=mkl in the build, though with some seeming unrelated dataset overrun issues there

**Comment by penpornk** [comment] 2019-11-21 18:13
@TensorFlow-MKL Could you please help take a look? Thank you very much!

**Comment by preethivenkatesh** [comment] 2019-11-21 23:53
we are looking into this issue. will keep you posted on our findings shortly

**Comment by penpornk** [comment] 2020-01-29 23:46
@preethivenkatesh Any updates?

**Comment by preethivenkatesh** [comment] 2020-02-12 00:32
We have an engineer looking into this issue now. I'll keep you posted

**Comment by penpornk** [comment] 2020-02-12 00:33
@preethivenkatesh Thank you very much!

**Comment by RogueLogix** [comment] 2020-04-27 02:14
any updates?

**Comment by ashraf-bhuiyan** [comment] 2020-05-22 00:00
We looked at the issue. The issue is coming form the fact that Intel optimization does not support Scope allocator optimization. Scope allocator optimization is applied by default to Tensorflow's own distributed strategy. We can temporarily disable this optimization (scope allocator optimization) from multi-worker distribution strategy when used Intel optimization. The example should still run correctly. Will this be ok? Moreover, we are planning to support Scope allocator optimization for Intel Optimized Tensorflow in few months, and then we will again enable Scope allocator optimization.

**Comment by RogueLogix** [comment] 2020-05-22 02:38
I'm not in need of the fix right now, I just ran into this issue, so do whatever you believe is best.

**Comment by NeoZhangJianyu** [comment] 2020-06-23 08:24
@RogueLogix Is it possible that you close this issue?

**Comment by NeoZhangJianyu** [comment] 2020-11-05 07:53
@RogueLogix Could you close this issue?

**Closed** 2020-11-05 08:00 UTC
Labels: TF 2.0, comp:dist-strat, comp:mkl, type:bug

**Comment by NeoZhangJianyu** [comment] 2020-11-05 08:45
@RogueLogix  Thank you very much!

**Comment by yixinshi** [comment] 2021-02-23 03:51
@ashraf-bhuiyan seems TF 2.4 MKL build still has the issue. I can reproduce using https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras
As a quick workaround, how can I disable scope allocator optimization from multi-worker distribution strategy? Any macro I can set? Or any patch I can apply to re-compile TF 2.4. Thank you!

 File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Upper bound check fail for input 5 from node Mkl2Tf/_30 to node scoped_allocator_concat_1_4 input bounds = [0x7fd53c18ff00, 0x7fd53c18ff80] backing_tensor bounds = [0x7fd4af3dc740, 0x7fd4afe6e280]
	 [[{{node scoped_allocator_concat_1_4}}]] [Op:__inference_train_function_740]
