### ISSUE TITLE
 run time error:could not find cudnnConvolutionBackwardData_v2 in cudnn DSO

### ISSUE THREAD

**Issue by lfwin** [tensorflow/tensorflow#1359] opened 2016-03-02 14:29 UTC
Operating System:ubuntu 14.04LTS
pip install 0.6 and  sudo pip install --upgrade .. to 0.7
The output from python -c "import tensorflow; print(tensorflow.__version__)" is:
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.7.1

below is errors when running cifar10_train.py:
 tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:73] Allocating 10.57GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:83] GPU 0 memory begins at 0x13047a0000 extends to 0x15a8b24400
F tensorflow/stream_executor/cuda/cuda_dnn.cc:220] could not find cudnnConvolutionBackwardFilter_v2 in cudnn DSO; dlerror: /usr/local/lib/libcudnn.so: undefined symbol: cudnnConvolutionBackwardFilter_v2

**Comment by vrv** [comment] 2016-03-02 18:03
What version of cudnn do you have?  The pip package at 0.7.1 is built assuming you have cudnn r4.  You have to build from sources if you want to support earlier versions.

**Comment by lfwin** [comment] 2016-03-03 01:45
Hi,
I have cuda installed folders such as: cuda, cuda-7.0, cuda-7.5, all they under this path /usr/local/. I copy cudnn r2, r3, r4 in all folders:cuda, cuda-7.0, cuda-7.5, but this did not work? how to check my tensorflow actually use which version of cudnn and cuda?

**Comment by lfwin** [comment] 2016-03-03 01:59
Hi, 
finally sovled, cudnn lib64 files placed in /usr/local/cuda/lib64 according to the install tutorial:
tar xvzf cudnn-6.5-linux-x64-v2.tgz
sudo cp cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda/include
sudo cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/lib64/libcudnn*
but actually my program search in /usr/local/lib, thank you very much

**Comment by lfwin** [comment] 2016-03-03 02:02
In addtion i use cudnn-7.0-linux-x64-v4.0-rc.tgz this cudnn, so tutorial above cudnn-6.5* will be replaced by cudnn-7.0*, hope this maybe helps someone has the same problem

**Comment by kibtes** [comment] 2016-03-03 09:37
@lfwin  I still have the same error after placing cudnn lib 64 files in usr/local/cuda/lib64. what should i do?

**Comment by yi374700** [comment] 2016-03-04 09:49
@kibtes I encountered the same problem today and after replacing the cuddn v2 stuff with v3 and it works. Try to make sure that the cuda dir is in your loading path.

**Comment by shoc2005** [comment] 2016-03-17 10:10
@kibtes just correctly provide path to cudnn libraries. For example in .bashrc file put line: 
`export LD_LIBRARY_PATH="/path_to_your_cudnn/cuda/lib64":$LD_LIBRARY_PATH`
Then logout and login. Check path with command: `env | grep cundd`.

**Comment by stgzr** [comment] 2016-03-26 18:56
I met this problem before. Error log is "F tensorflow/stream_executor/cuda/cuda_dnn.cc:220] could not find cudnnConvolutionBackwardData_v2 in cudnn DSO; dlerror: /usr/local/cuda-7.0/lib64/libcudnn.so: undefined symbol: cudnnConvolutionBackwardData_v2".
So I tried to update cuDNN libraries to the latest version. So I download cudnn-7.0-linux-x64-v4.0-prod.tgz then export LD_LIBRARY_PATH, it works. Thank you!

**Comment by girving** [comment] 2016-06-06 21:28
It sounds like this issue is caused by system irregularities which I'm not sure we'll be able to work around on our end, so closing for now.

**Closed by girving** 2016-06-06 21:28 UTC
