### ISSUE TITLE
DatasetVariantWrapper "No unary variant device copy function found"

### ISSUE THREAD

**Issue by mwalmsley** [tensorflow/tensorflow#34112] opened 2019-11-08 23:47 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (but running on an official image)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04, running the Ubuntu 18.04 tensorflow-gpu Docker image provided by GCloud
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-gpu-2.0.0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: P100 x1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm running Tensorflow on GCloud using the gcr.io/deeplearning-platform-release/tf2-gpu.2-0 image. I'm attempting to train a subclassed tf.keras.Model. 

I can train my image both on my local machine and GCloud, provided the --runtime=nvidia arg is NOT provided. When I add that argument, the GCloud image fails with the following error:

tensorflow.python.framework.errors_impl.InternalError:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node MapDataset/_8}}]] [Op:__inference_get_input_516]

**Describe the expected behavior**

I expect TensorFlow to continue to run successfully when using the --runtime=nvidia arg, i.e. enabling CUDA.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Because I have no understanding of the origin of this internal error, I am not sure how to create such a minimal case. Please advise.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Full failing log:

  File "/home/zoobot/zoobot/estimators/run_estimator.py", line 33, in run_estimator
    train_dataset = input_utils.get_input(config=config.train_config)
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/root/miniconda3/lib/python3.5/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node MapDataset/_8}}]] [Op:__inference_get_input_516]

Full successful log, without using --runtime=nvidia:

2019-11-08 23:34:49.753010: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-08 23:34:59.531666: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2019-11-08 23:34:59.531739: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-11-08 23:34:59.531778: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2019-11-08 23:34:59.532239: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-08 23:34:59.540322: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-11-08 23:34:59.540738: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cf105c9a70 executing computations on platform Host. Devices:
2019-11-08 23:34:59.540776: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:root:Loading multiple tfrecords with interleaving, shuffle=False
WARNING:root:Loading multiple tfrecords with interleaving, shuffle=False
2019-11-08 23:35:37.148322: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2019-11-08 23:35:37.148432: E tensorflow/core/platform/default/device_tracer.cc:70] CUDA error: <unknown>
...
Epoch 1/100
...

**Comment by mwalmsley** [comment] 2019-11-08 23:52
I should perhaps add that I have successfully trained models on the same GCloud machine (with the same CUDA install) on TF 1.14.

**Comment by mwalmsley** [comment] 2019-11-11 11:34
Thanks @oanush. A brief update - I have changed my setup to run on the GCP AI Platform VM (https://cloud.google.com/ai-platform/deep-learning-vm/docs/) directly (i.e. without docker) and receive the same error.

**Comment by keotic** [comment] 2019-11-13 15:59
Seeing the same issue on TF2.0 , it only happens when using a GPU and a @tf.functions (graph mode), Everything seems to run ok when running on eager mode, or CPU only

**Comment by sanjoy** [comment] 2019-12-13 23:57
Jiri, it looks like the graph is trying to copy an instance of `DatasetVariantWrapper` from CPU to GPU.   Should that ever happen?

**Comment by jsimsa** [comment] 2019-12-17 01:30
In general, it is possible the happen -- for instance if the user program makes incorrect use of device scopes.

@mwalmsley you can create a minimal reproducible example by starting with your user program and repeatedly removing complexity from it (e.g. replacing a complex model with a trivial one, replacing complex input pipeline with a trivial one) until there is nothing that can be removed without the issue going away. In the absence of knowing what the root cause is, this process is helpful in zeroing in on the issue.

**Comment by sanjoy** [comment] 2019-12-26 22:20
> In general, this can happen -- for instance if the user program makes incorrect use of device scopes.

Can this ever happen in a _correct_ program?

**Comment by jsimsa** [comment] 2019-12-30 21:03
Yes, for instance https://github.com/tensorflow/tensorflow/issues/34519.

**Comment by sanjoy** [comment] 2019-12-30 21:47
> Yes, for instance #34519.

I did not phrase this unambiguously: is there a situation where TF should legitimately need to copy a `DatasetVariantWrapper` between CPU and GPU?  If yes, the right fix should be to teach TF to do this copy, right?

**Comment by jsimsa** [comment] 2019-12-30 22:08
In that case the answer is no. The tf.data implementation prevents such copies from happening silently (by not implementing / registering a method for copying the dataset variant) and instead relies on explicit APIs (such as the multi-device iterator [API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/multi_device_iterator_ops.py used by tf.distribute) to copy data between devices.

**Comment by lindong28** [comment] 2020-01-03 16:27
@jsimsa @sanjoy: since tf.data intentionally prevented `DatasetVariantWrapper` from being copied (I assume it is for performance reason), there should be extra logic (specific to `DatasetVariantWrapper`) to ensure we never try to copy `DatasetVariantWrapper` between devices, right? Do you know how is this achieved?

**Comment by sanjoy** [comment] 2020-01-03 18:48
> Do you know how is this achieved?

Probably placer needs to understand and respect this constraint.  Maybe @iganichev knows?

**Comment by lindong28** [comment] 2020-01-03 19:33
As far as I know, the only dataset specific logic in placer is [1], which explicitly avoids copy of DatasetVariantWrapper between two DatasetOp nodes. I think we need logic in placer that prevents copy of DatasetVariantWrapper if we don't already have this. But that probably requires some expertise in tf.data to expose the necessary information.

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/colocation_graph.cc#L722

**Comment by iganichev** [comment] 2020-01-03 20:36
> > Do you know how is this achieved?
> 
> Probably placer needs to understand and respect this constraint. Maybe @iganichev knows?

As @lindong28 mentioned, placer does not know the type inside DT_VARIANT at placement time. So, it can't automatically colocate nodes based on it. If the relevant nodes, always take the same underlying types and they are not copiable, it should be easy to add logic similar to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/colocation_graph.cc#L722

**Comment by mgoutay** [comment] 2020-04-08 15:43
Hi,
I'm running Tensorflow 2.2.0-rc2 on Google Colab with GPU enabled, and I have the same error when I run this little peace of code:

``` python
import tensorflow as tf

@tf.function
def loop():
    
    H = tf.random.uniform(shape=[100, 1])
    DS = tf.data.Dataset.from_tensor_slices(H).batch(10)  

    for i in tf.range(100): 
        for h in DS:
            test = h + h
            
loop()
```

The exact error is the following:

> InternalError                             Traceback (most recent call last)
> <ipython-input-13-d7fba13d49c2> in <module>()
>      11             test = h + h
>      12 
> ---> 13 loop()
> 
> 5 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      58     ctx.ensure_initialized()
>      59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> ---> 60                                         inputs, attrs, num_outputs)
>      61   except core._NotOkStatusException as e:
>      62     if name is not None:
> 
> InternalError: 2 root error(s) found.
>   (0) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
> 	 [[{{node BatchDatasetV2/_18}}]]
> 	 [[Func/while/body/_1/input/_51/_46]]
>   (1) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
> 	 [[{{node BatchDatasetV2/_18}}]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_loop_5186]
> 
> Function call stack:
> loop -> loop

Strangely, if I unroll the for loop (as defined [there])(https://www.tensorflow.org/tutorials/customization/performance#for_loops), I don't have any error:

```python
import tensorflow as tf

@tf.function
def loop():
    
    H = tf.random.uniform(shape=[100, 1])
    DS = tf.data.Dataset.from_tensor_slices(H).batch(10)  

    for i in range(100): 
        for h in DS:
            test = h + h

loop()
```

I have been able to reproduce this error on my own computer running Ubuntu 18.04.3 LTS, CUDA 10.2, and Tensorflow 2.2.0-rc2 installed with pip.

Can you spot what is causing the error and if it's related to the problem described in this thread?

**Comment by iganichev** [comment] 2020-04-08 17:58
@jsimsa, I remember you guys looked at this some time ago. What was the conclusion?

**Comment by jsimsa** [comment] 2020-04-08 22:14
This is related to https://github.com/tensorflow/tensorflow/issues/34519. Alex made a suggestion there that @saxenasaurabh agree with but I don't think anyone is actively working towards fixing this.

**Comment by ppwwyyxx** [comment] 2020-07-11 21:08
With TF 2.2 I'm still running into the error in the title of the issue

**Comment by Ryan-Rudes** [comment] 2020-07-21 22:01
I have not been able to solve this all day; I'm getting the exact error in the title, verbatum, and all of the things discussed in the first several comments in this thread apply to my situation exactly, as well.

**Comment by lindong28** [comment] 2020-07-27 13:48
Hey @Ryan-Rudes, @ppwwyyxx, @mgoutay, @mwalmsley, sorry and I know it is disappointing that TF team has not been able to provide a timely workaround solution.

As I am trying to finding a workaround to this issue, I came across this reply by @AdrienCorenflos and validated that the proposed solution works. I have yet to confirm with owners of the respective TF components to understand whether this workaround (i.e. use `tf.device` to place iterator on the CPU device) is expected to be a general solution to this issue.

Could you try it out and see if this solution unblocks your work? I am hoping it helps.

[1] https://github.com/tensorflow/tensorflow/issues/34519#issuecomment-636138360

**Comment by rachellim** [comment] 2020-09-02 19:55
This issue should be fixed as of TF 2.3. 

@Ryan-Rudes , @ppwwyyxx, @mwalmsley etc - can you see if you're still encountering this and reopen if so?

**Comment by lindong28** [comment] 2020-09-03 06:04
Hey Rachel and everyone, I think the issue still exists in TF 2.3. But it has been fixed in tf-nightly==2.4.0.dev20200902 and thus it should be fixed in the upcoming TF 2.4 release.

It can be validated using this colab example: https://colab.research.google.com/drive/1C4AXS8cyEsA_JmU7QVVk7UXM_uygVf05?authuser=1#scrollTo=jJBsJsRSR6AD

**Comment by rachellim** [comment] 2020-09-03 19:12
Ah, I see that there are two subtly different issues here:

(1) 
```
    dataset = tf.data.Dataset.range(10)

    @tf.function
    def f():
      for i in tf.range(1):
        for x in dataset:
          tf.print(x)

    f()
```

(2) 
```
    @tf.function
    def f():
      dataset = tf.data.Dataset.range(10)
      for i in tf.range(1):
        for x in dataset:
          tf.print(x)
    f()
```

(1) has been fixed as of TF 2.3. (see #34519)

(2) is still an open issue. 

Depending on how your tf.function is defined, you might still be seeing this bug. I'm reopening this issue to track (2).

**Comment by sushreebarsa** [comment] 2021-05-29 11:52
Was able to replicate the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/6e008edb0b84e3b5527264d3de09e12f/untitled77.ipynb)..Thanks !

**Comment by Saduf2019** [comment] 2021-09-09 18:50
@mwalmsley 
This has been fixed in nightly please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e6b288651a3944a6b720b30e2ffd3b86/untitled635.ipynb).

**Closed** 2021-09-23 19:24 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:gpu, TF 2.0
