### ISSUE TITLE
TF 2.0 Upgrade Script: Unable to handle the @ operator for matrix multiplication

### ISSUE THREAD

**Issue by pzobel** [tensorflow/tensorflow#29871] opened 2019-06-17 11:21 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.7.3

**Describe the current behavior**
Running the tf_upgrade_v2 script with a file containing the @ operator results in an exception (see below).

**Code to reproduce the issue**
Using the file tmp.py with the following content:

import numpy as np
def mul(a, b):
     z = a @ b

Then run: 
 .\tf_upgrade_v2.exe --infile "C:\any\path\tmp.py" --outfile "C:\another\path\tmp.py"

**Other info / logs**

Traceback (most recent call last):
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "C:\Program Files\Python37\lib\ast.py", line 262, in visit
    return visitor(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 47, in wrapped
    f(self, node, *args, **kwargs)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 690, in visit_BinOp
    op_symbol = ast_constants.NODE_TYPE_TO_TOKENS[type(node.op)][0]
KeyError: <class '_ast.MatMult'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pzobel\PycharmProjects\TF2_0_Beta_Test\venv\Scripts\tf_upgrade_v2.exe\__main__.py", line 9, in <module>
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\tensorflow\tools\compatibility\tf_upgrade_v2_main.py", line 139, in main
    args.input_file, output_file, upgrade)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\tensorflow\tools\compatibility\tf_upgrade_v2_main.py", line 40, in process_file
    upgrader.process_file(in_filename, out_filename)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 900, in process_file
    temp_file)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 960, in process_opened_file
    self.update_string_pasta("".join(lines), in_filename))
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\tensorflow\tools\compatibility\ast_edits.py", line 916, in update_string_pasta
    t = pasta.parse(text)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\__init__.py", line 25, in parse
    annotator.visit(t)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "C:\Program Files\Python37\lib\ast.py", line 262, in visit
    return visitor(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 47, in wrapped
    f(self, node, *args, **kwargs)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 220, in visit_Module
    self.generic_visit(node)
  File "C:\Program Files\Python37\lib\ast.py", line 270, in generic_visit
    self.visit(item)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "C:\Program Files\Python37\lib\ast.py", line 262, in visit
    return visitor(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 95, in wrapped
    f(self, node, *args, **kwargs)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 411, in visit_FunctionDef
    self.visit(stmt)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 1194, in visit
    super(AstAnnotator, self).visit(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 132, in visit
    super(BaseVisitor, self).visit(node)
  File "C:\Program Files\Python37\lib\ast.py", line 262, in visit
    return visitor(node)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 47, in wrapped
    f(self, node, *args, **kwargs)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 530, in visit_Assign
    self.visit(node.value)
  File "c:\users\pzobel\pycharmprojects\tf2_0_beta_test\venv\lib\site-packages\pasta\base\annotate.py", line 1196, in visit
    raise AnnotationError(e)
pasta.base.annotate.AnnotationError: <class '_ast.MatMult'>

**Comment by achandraa** [comment] 2019-06-21 12:06
I have tried to reproduce the issue on my system and was able to do it.

**Comment by martinwicke** [comment] 2019-06-22 00:21
@soupytwist, FYI. I'll send you a PR.

**Comment by jvishnuvardhan** [comment] 2019-06-25 21:51
Automatically closing this out since I understand it to be resolved by the PR https://github.com/google/pasta/pull/67 (merged already), but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-06-25 21:51 UTC
Labels: 2.0.0-beta0, comp:ops, type:bug/performance

**Comment by martinwicke** [comment] 2019-06-25 22:12
That will resolve it, but until pasta is released with the change, and I
add an updated dependency, users might have to reinstall pasta manually.
It's probably ok to close.

**Comment by TrentBrick** [comment] 2019-11-03 01:37
I am running into the same issue but not sure how to resolve it. My pasta library is updated but I am still getting the same error and can't upgrade to TensorFlow 2.

**Comment by pzobel** [comment] 2019-11-04 09:34
Hi @TrentBrick,
it seems that the latest release of pasta is from [May 29](https://github.com/google/pasta/releases) and therefore @martinwicke 's fix is not in the latest release yet. 
Please install pasta from source or manually add the [fix](https://github.com/google/pasta/pull/67) to your code until they added a new release.

**Comment by soupytwist** [comment] 2019-11-04 18:48
Hi, I've just released pasta v0.1.8 which contains the latest fixes. Sorry for the delay!

**Comment by martinwicke** [comment] 2019-11-04 22:18
I don't yet see a v0.1.8 tag or release on GitHub, am I just not seeing it?

**Comment by soupytwist** [comment] 2019-11-04 22:33
> I don't yet see a v0.1.8 tag or release on GitHub, am I just not seeing it?

Pushed the tag up now, forgot this. Thanks
