### ISSUE TITLE
TF 1.14 Keras model throws exception when inputs are not the deepest nodes

### ISSUE THREAD

**Issue by peastman** [tensorflow/tensorflow#31174] opened 2019-07-30 22:43 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.1
- GPU model and memory: Titan V

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

TensorFlow 1.14 introduced a bug in Keras models.  The specific change is the introduction of these lines:

https://github.com/tensorflow/tensorflow/blob/a5120db4d6917f943176ef3c5bb938064604c761/tensorflow/python/keras/engine/network.py#L849-L850

They make the assumption that a model's inputs will be deeper than any other node.  When that is not true, any nodes whose depth is equal to or greater than the inputs does not get evaluated, producing an exception.

The problem is demonstrated by the following script.  It creates a model where an input and a variable have the same depth.  In TensorFlow 1.13 this runs correctly, but in 1.14 it throws an exception:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print(model(model.inputs))
  File "/home/peastman/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/peastman/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 751, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/home/peastman/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 903, in _run_internal_graph
    assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("add/add:0", shape=(?, 1), dtype=float32)
```

**Describe the expected behavior**

Calling the model should return a Tensor, not throw an exception.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
import tensorflow.keras.layers as layers

class Variable(layers.Layer):

  def __init__(self, initial_value, **kwargs):
    super(Variable, self).__init__(**kwargs)
    self.var = tf.Variable(initial_value)

  def call(self, inputs):
    return self.var

var = Variable([1.0])([])
input = layers.Input(shape=(1,))
output = layers.Add()([input, var])
model = tf.keras.Model(inputs=[input], outputs=[output])
print(model(model.inputs))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by peastman** [comment] 2019-08-05 22:41
After searching for a workaround, I've concluded this bug is more severe than I originally thought.  It doesn't actually matter where in the tree the `Variable` layer appears.  All that matters is that it takes no inputs, but is not itself an `Input` layer.  Any layer with those properties anywhere in a model produces the exception.

**Comment by ymodak** [comment] 2019-08-16 21:12
This issue exists tf-nightly version 1.15.0-dev20190816

**Comment by omalleyt12** [comment] 2019-08-16 22:35
@peastman You'll have to make a Layer that creates a Variable and adds it to input, it's not possible to have a Keras Layer that takes no inputs in the Functional API

**Comment by peastman** [comment] 2019-08-16 22:48
In what sense is it not possible?  It worked perfectly up through TF 1.13.

**Comment by peastman** [comment] 2019-08-16 22:51
Note that the sample script is just a minimal reproduction.  The real models where I'm encountering this error are much more complicated.  But generally speaking, it's very common for computation graphs to have branches that don't depend on any inputs, just on variables.

**Comment by saikumarchalla** [comment] 2020-04-03 09:13
@peastman Closing this issue as it is the intended behaviour.Thanks!

**Closed by saikumarchalla** 2020-04-03 09:13 UTC
Labels: TF 1.14, comp:keras, type:bug
