### ISSUE TITLE
After tensorflow-lite-0.1.7 update Image classification using inception-v3 model stops working

### ISSUE THREAD

**Issue by princekumar15** [tensorflow/tensorflow#19051] opened 2018-05-03 10:05 UTC
Image classification using inceptionv3_slim_2016.tflite is not working after the recent update of 0.1.7 version. Cannot allocate memory for the interpreter.
It gives the below exception :

java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter

**Comment by princekumar15** [comment] 2018-05-04 04:59
Have I written custom code : NA
OS Platform and Distribution : Android
TensorFlow installed from : 'org.tensorflow:tensorflow-lite:+'
TensorFlow version : tensorflow-lite-0.1.7
Bazel version : NA
CUDA/cuDNN version : NA
GPU model and memory : NA
Exact command to reproduce : NA(using TfLite InceptionV3 in Android 8.1)

**Comment by ljdang** [comment] 2018-05-04 10:05
I also met the same problem, and the float model is so slow.

**Comment by hablema** [comment] 2018-05-07 06:05
Same here

**Comment by jbuisson1** [comment] 2018-05-14 17:36
Same here

**Comment by alanchiao** [comment] 2018-05-16 18:14
Thanks princekumar15@ for reporting this issue! I'll start looking into what caused this breakage.

**Comment by alanchiao** [comment] 2018-05-21 21:59
@princekumar15 : I tried but was unable to reproduce your issue. Everyone, is there something I did differently?

I suspect you were following the [tflite Android demo instructions](https://www.tensorflow.org/mobile/tflite/demo_android).

1. I followed the instructions: "Or, download the floating point Inception-v3 model and unzip and copy inceptionv3_non_slim_2015.tflite to the assets directory. Change the chosen classifier in Camera2BasicFragment.java from: classifier = new ImageClassifierQuantizedMobileNet(getActivity()); to: classifier = new ImageClassifierFloatInception(getActivity());"

2. I ran into the [setNumThreads issue](https://github.com/tensorflow/tensorflow/issues/18821) and commented the lines out as Bob suggested.
In the build.gradle file, I tried compile 'org.tensorflow:tensorflow-lite:0.1.7' and compile 'org.tensorflow:+'. I didn't see the error when running the demo in either case.

3. I also just tried building from HEAD with bazel without using Android Studio and didn't see the error.

This was on a Pixel 2 running on Android 8.1.0.

**Comment by jbuisson1** [comment] 2018-05-25 09:28
The way I get this error is when following the tutorial TensorFlow for poets 2.

I first tried the TensorFlow for poets (https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html?index=..%2F..%2Findex#0) to retrain a model with my data (this part works just fine even when using the retrained .pb graph on android but the detection time is still slow and the battery usage high).

I wanted to try and implement TFLite to help fix these problems, so I followed the tutorial TensorFlow for poets 2 (https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#0) to convert my .pb model into a .tflite model. The output model is the one that causes the java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter when imported in Android, but the inceptionv3_slim_2016.tflite works fine, it just does not work with my retrained model.

I'm running this on Samsung Galaxy S6 running Android 7.0 by the way, I hope this gives you more information on how to reproduce the problem.

**Comment by alanchiao** [comment] 2018-05-29 23:01
@jbuisson1: for the pre-made Android app, are you using the one linked to in Tensorflow for Poets 2 (from the codebase cloned in Tensorflow for Poets 1, as opposed to this [one](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/java/demo))? I followed both Tensorflow for Poets 1 and 2, and it's worked for me on a Nexus 6 emulator running Android 7.0 and my Pixel. I tried hacking the model/labels into the tensorflow/tensorflow repo also and it worked fine.

Let's try to see what differences there might be.

1. Your data is special somehow (e.g. different image dimensions). Did you have the same problem when using the tutorial retraining data (daisy, sunflower, ... categories)?
2. There have been tflite updates to tensorflow-lite:0.1.7 since you last tried. Try [making sure that Android Studio/Gradle has picked up on the changes](https://stackoverflow.com/questions/28683327/how-to-check-if-gradle-dependency-has-new-version).
3. If there aren't other differences that you can think of, I may need to find a Samsung Galaxy S6 to reproduce.

**Dismissed Differences**
1. I'm running from HEAD. The codebase hasn't really been [updated recently](https://github.com/googlecodelabs/tensorflow-for-poets-2/commits/master/android/tflite).

**Comment by alanchiao** [comment] 2018-06-11 23:33
Closing this issue.

I suspect that if you make sure that Android Studio/Gradle has picked up on tensorflow-lite:0.1.7 changes, the problem will go away. 

Reasoning:
I confirmed that the tensorflow-lite:0.1.7 AAR that Gradle uses was re-released once. This is not something we should be doing in the future, but would explain why I couldn't reproduce the issue (I'm using the newer version of the tensorflow-lite:0.1.7 AAR and some people picked up the older version around the release time).

**Closed by alanchiao** 2018-06-11 23:33 UTC
Labels: comp:lite, stat:awaiting response
