### ISSUE TITLE
timeline export has bug for multiple gpu case

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#30734] opened 2019-07-16 03:50 UTC
Timeline export has bug when using multiple tower on multiple gpu: the exported ops are almost all placed on gpu:0, while the other device(gpu:1, gpu:2) has almost no ops. I dumped the device placement, and find out that the placement is not the same as those in timeline.json.

**Comment by ravikyram** [comment] 2019-07-17 11:18
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github ](https://github.com/tensorflow/tensorflow/issues/new/choose)new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2019-07-24 06:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-07-24 06:25 UTC
Labels: comp:gpu, stat:awaiting response, type:support
