### ISSUE TITLE
ModuleNotFoundError: No module named 'utility'

### ISSUE THREAD

**Issue by tonyamrtin** [tensorflow/tensorflow#37222] opened 2020-03-02 06:40 UTC
![0](https://user-images.githubusercontent.com/61679488/75651231-4d9c5a00-5c9b-11ea-8054-bc2c8a22a1d1.PNG)

hi
i wanna use '**from utility import lazy_property**' code but i can't
 i think that code for TF1. can you let me know what is the Code that serves the same role in tf2?

If not, please let me know the appropriate code thanks

**Comment by ayushmankumar7** [comment] 2020-03-02 08:51
is utility a part of Tensorflow? Can you provide the directory you are in?

**Comment by tonyamrtin** [comment] 2020-03-02 09:15
> is utility a part of Tensorflow? Can you provide the directory you are in?

I don't think the utility folder exists I'm just copying a book

**Comment by ayushmankumar7** [comment] 2020-03-02 10:05
Yes. Absolutely.

**Comment by tonyamrtin** [comment] 2020-03-02 10:54
> Yes. Absolutely.

should i downgrade the tensorflow same as  book ?

**Comment by ayushmankumar7** [comment] 2020-03-02 11:35
Downgrading Tensorflow may not help, i guess. 
Utility maybe a different library.

**Comment by pandrey-fr** [comment] 2020-03-02 13:59
Hi, sorry but this is not a tensorflow issue. In your example, `utility` is some kind of third-party package, or home-made library, not a part of tensorflow, as is clear from your import syntax.

**Comment by tonyamrtin** [comment] 2020-03-03 05:08
> Hi, sorry but this is not a tensorflow issue. In your example, `utility` is some kind of third-party package, or home-made library, not a part of tensorflow, as is clear from your import syntax.

THANKS

**Comment by Saduf2019** [comment] 2020-03-03 05:11
@tonyamrtin 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Hence moving this issue to resolved status.

**Closed by Saduf2019** 2020-03-03 05:11 UTC
Labels: TF 2.1, type:docs
