### ISSUE TITLE
Build error: Eigen/src/Core/arch/CUDA/PacketMathHalf.h(45): error: identifier "__half2half2" is undefined

### ISSUE THREAD

**Issue by gokceneraslan** [tensorflow/tensorflow#5327] opened 2016-11-01 14:57 UTC
I'm getting the following errors when I try to build TensorFlow:

```
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(45): error: identifier "__half2half2" is undefined                                                                                                                   [136/14011]
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(53): error: identifier "__halves2half2" is undefined
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(57): error: identifier "__halves2half2" is undefined
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(65): error: identifier "__low2half" is undefined
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(66): error: identifier "__high2half" is undefined
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(81): error: identifier "__halves2half2" is undefined
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(88): error: identifier "__halves2half2" is undefined
```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Nothing.

### Environment info
Operating System:
Ubuntu 14.04.1
gcc-4.8.4
bazel 0.3.2
TensorFlow: Master 6f7cf60a4158a6d

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda: 7.5
cudnn: 5.1.5
```
 ❯ ls -lh /usr/local/cuda-7.5/lib64/libcud*
-rw-r--r-- 1 root root 316K Aug  7  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root   16 Aug  7  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root   18 Aug  7  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.7
-rwxr-xr-x 1 root root 375K Aug  7  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.7
-rw-r--r-- 1 root root 704K Aug  7  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
 ❯ ls -lh /usr/local/cudnn-5.1/lib64 
lrwxrwxrwx 1 root root  13 Oct 21 18:33 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root  17 Oct 21 18:33 libcudnn.so.5 -> libcudnn.so.5.1.5
-r-xr-xr-x 1 root root 76M Oct 21 18:33 libcudnn.so.5.1.5
-r-xr-xr-x 1 root root 67M Oct 21 18:33 libcudnn_static.a

```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
6f7cf60a4158a6d7861dc1b41a6446b575153a2e
2. The output of `bazel version`
```
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by gokceneraslan** [comment] 2016-11-01 15:01
Maybe @benoitsteiner might help.

**Comment by gokceneraslan** [comment] 2016-11-01 15:34
` ❯ grep half2half2 /usr/local/cuda-7.5/include/cuda_fp16.h -2`
```c++

__CUDA_FP16_DECL__ __half __high2half(const __half2 h);
__CUDA_FP16_DECL__ __half2 __halves2half2(const __half l, const __half h);
__CUDA_FP16_DECL__ __half2 __half2half2(const __half lh);
__CUDA_FP16_DECL__ __half2 __floats2half2_rn(const float f1, const float f2);
__CUDA_FP16_DECL__ __half2 __float22half2_rn(const float2 f);
--
   return val;
}
__CUDA_FP16_DECL__ __half2 __half2half2(const __half lh)
{
   __half2 val;
```

**Comment by gokceneraslan** [comment] 2016-11-01 15:44
Same on 0.11 branch.

**Comment by benoitsteiner** [comment] 2016-11-01 16:12
@gokceneraslan: it looks like bazel is picking up an older version of CUDA that doesn't support fp16. Do you have cuda 7.0 (or older) installed in  /usr/local/cuda by any chance ?

**Comment by gokceneraslan** [comment] 2016-11-01 17:30
No, I have only cuda 7.5 installed. In bazel cache, I can also see that it picks up the right cuda:

```
 ❯ pwd
.../.bazel-cache/107ff11f0584ee207e19ea91624e574d/external/local_config_cuda/cuda
 ❯ ls
bin  extras  include  lib64  nvvm  BUILD  build_defs.bzl  cuda_config.h  platform.bzl
 ❯ ls -alh include/cuda_fp16.h
lrwxrwxrwx 1 user users 39 Nov  1 10:20 include/cuda_fp16.h -> /usr/local/cuda-7.5/include/cuda_fp16.h
 ❯ grep half2half2 include/cuda_fp16.h -2
__CUDA_FP16_DECL__ __half __high2half(const __half2 h);
__CUDA_FP16_DECL__ __half2 __halves2half2(const __half l, const __half h);
__CUDA_FP16_DECL__ __half2 __half2half2(const __half lh);
__CUDA_FP16_DECL__ __half2 __floats2half2_rn(const float f1, const float f2);
__CUDA_FP16_DECL__ __half2 __float22half2_rn(const float2 f);
--
   return val;
}
__CUDA_FP16_DECL__ __half2 __half2half2(const __half lh)
{
   __half2 val;
```

**Comment by benoitsteiner** [comment] 2016-11-01 18:47
@gokceneraslan Which .cc file(s) trigger these error messages ?

**Comment by gokceneraslan** [comment] 2016-11-01 18:56
I think `contrib/rnn/kernels/gru_ops_gpu.cu.cc`. The output is as follows:

```
INFO: From Compiling tensorflow/contrib/rnn/kernels/gru_ops_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(45):error: identifier "__half2half2" is undefined

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(53):error: identifier "__halves2half2" is undefined

... (several of these error messages)

external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/TypeCasting.h(100): error: identifier "__floats2half2_rn" is undefined

71 errors detected in the compilation of "/tmp/user/tmpxft_00002ecc_00000000-10_gru_ops_gpu.cu.compute_52.cpp1.ii".
ERROR: /users/user/Code/tensorflow/tensorflow/contrib/rnn/BUILD:73:1: output 'tensorflow/contrib/rnn/_objs/python/ops/_gru_ops_gpu/tensorflow/contrib/rnn/kernels/gru_ops_gpu.cu.pic.o' was not created.
ERROR: /users/user/Code/tensorflow/tensorflow/contrib/rnn/BUILD:73:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /users/user/Code/tensorflow/tensorflow/tools/pip_package/BUILD:23:1 not all outputs were created.
INFO: Elapsed time: 12.422s, Critical Path: 11.16s
```

**Comment by gokceneraslan** [comment] 2016-11-01 19:01
Sometimes another cc file triggers the error, like `tensorflow/core/kernels/depthtospace_op_gpu.cu.cc`

**Comment by benoitsteiner** [comment] 2016-11-04 00:31
@gokceneraslan I can't reproduce the issue locally, so it's kind of a shot in the dark, but can you check if https://github.com/tensorflow/tensorflow/commit/0b730a0d9351a89bf0abff8b18ff382f4559d239 fixed the issue ?

**Comment by gokceneraslan** [comment] 2016-11-04 05:33
No, it didn't fix it. But it seems there is something weird about my setup, because I also cannot reproduce it on another machine with same CUDA and cudnn.

**Comment by benoitsteiner** [comment] 2016-11-05 04:04
Thanks for the update. I'm closing this issue.

**Closed by benoitsteiner** 2016-11-05 04:04 UTC
Labels: type:build/install
