### ISSUE TITLE
[TF 2.0 keras] Unable save and load weights for double nested models

### ISSUE THREAD

**Issue by zzh8829** [tensorflow/tensorflow#27769] opened 2019-04-12 05:30 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7

**Describe the current behavior**
load_weights throw exception on a doubly nested model

**Describe the expected behavior**
load_weights should work

This problem only happens on two+ layers of nested model with non-trainable weights.
The reason is save_weights and load_weights handles nested model differently
save_weights -> call layer.weights for each layer
load_weights -> recursively call model.weights if layer is a nested Model

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization

shape = (None, None, 3)

def BNModel():
    x = inputs = Input(shape)
    x = Conv2D(3, 1)(x)
    x = BatchNormalization()(x)
    return Model(inputs, x)

x = inner_inputs = Input(shape)
x = BNModel()(x)
x = BNModel()(x)
inner_model = Model(inner_inputs, x)

inputs = Input(shape)
model = Model(inputs, inner_model(inputs))

inner_model.save_weights('test.h5')
inner_model.load_weights('test.h5')  # works fine

model.save_weights('test.h5')
model.load_weights('test.h5')   # Exception: axes don't match array !!!
```

**Other info / logs**
This bug is also reported on upstream keras https://github.com/keras-team/keras/pull/11847
Here is a detailed analysis on why this is happening https://github.com/keras-team/keras/pull/11847#issuecomment-482438283

Full Exception
```
  File "test.py", line 27, in <module>
    model.load_weights('test.h5')   # Exception: axes don't match array !!!
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1497, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 751, in load_weights_from_hdf5_group
    layer, weight_values, original_keras_version, original_backend)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 377, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 365, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 377, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 353, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 459, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 598, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```

**Comment by zzh8829** [comment] 2019-04-12 14:09
This only affected .h5 format, tensorflow checkpoints format works fine.
I guess alternatively we can tell users to not use h5 format instead of fixing it

**Comment by abhigyank** [comment] 2019-05-03 06:42
@zzh8829  What is the alternative way to save a model/weights? I am having this proble min .hdf5 fromat too.

**Comment by zzh8829** [comment] 2019-05-04 21:05
@abhigyank the alternative is save to `*.tf` which will create tensorflow checkpoint files instead of hdf5.

**Comment by bbrito** [comment] 2019-06-18 16:14
Any news on this issue?

I tried the *.tf and it works.

**Comment by veqtor** [comment] 2019-06-20 09:50
It might seem like .tf saving works but in my experience the only difference is that it doesn't throw an error. 
Steps to reproduce:
Make a model with nested models and set some layers to trainable=False
Train for some epochs
Save weights
Evaluate and save metrics
Clear everything
Make model
Load weights
Evaluate

**Comment by k-w-w** [comment] 2019-06-20 22:06
I am currently submitting a fix for H5. 

@veqtor What problem are you seeing with using the TF format?

**Comment by torinaki** [comment] 2019-07-01 00:11
@k-w-w I was tried to apply your fix and now getting following error:
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-4-b53d1fd98fb2> in <module>
     28     #AaeClustering.evaluate(x_test, y_test, classifier, metric_func=metric_func)
     29 
---> 30 test_sussex()

<ipython-input-4-b53d1fd98fb2> in test_sussex(generator_softmax_path, epochs, verbose, batchsize, code_len, test_size, include_test)
     22     # classifier.load_weights(generator_softmax_path)
     23 
---> 24     classifier = tf.keras.models.load_model(generator_softmax_path)
     25 
     26     metric_func = lambda y_pred, y_true: f1_score(y_pred, y_true, average='macro')

~/.miniconda3/envs/space-type-recognition/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    235 
    236     # set weights
--> 237     load_weights_from_hdf5_group(f['model_weights'], model.layers)
    238 
    239     if compile:

~/.miniconda3/envs/space-type-recognition/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers)
    837                        str(len(symbolic_weights)) +
    838                        ' weights, but the saved weights have ' +
--> 839                        str(len(weight_values)) + ' elements.')
    840     weight_value_tuples += zip(symbolic_weights, weight_values)
    841   K.batch_set_value(weight_value_tuples)

ValueError: Layer #0 (named "generator" in the current model) was found to correspond to layer generator in the save file. However the new layer generator expects 70 weights, but the saved weights have 0 elements.
```

**Comment by torinaki** [comment] 2019-07-01 00:23
@k-w-w I have tested your fix and it works for me 😃 Thank you a lot!

**Comment by 19giorgosts** [comment] 2019-08-05 11:24
@k-w-w How can I use your fix? I have the same problem.

**Comment by k-w-w** [comment] 2019-08-05 19:49
@19giorgosts The fix should be in tensorflow-nightly, which you can install using `pip install tf-nightly`

**Comment by Lannist** [comment] 2019-08-07 02:56
> Make model
> Load weights
> Evaluate
I am new coder to keras。 Can you show me a demo about your description? 
Thx

**Comment by Lannist** [comment] 2019-08-07 02:57
> It might seem like .tf saving works but in my experience the only difference is that it doesn't throw an error.
> Steps to reproduce:
> Make a model with nested models and set some layers to trainable=False
> Train for some epochs
> Save weights
> Evaluate and save metrics
> Clear everything
> Make model
> Load weights
> Evaluate

I am new coder to keras。 Can you show me a demo about your description?
Thx

**Comment by jvishnuvardhan** [comment] 2019-08-09 17:45
@Lannist [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/0153524fb3f6e0b114ace9da25ac3f77/tf_27769_saveweights_tfformat.ipynb) is the colab gist to save/load the weights in *.tf format. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/48daec236b2c8a5c8cf7a482f258ee8a/tf_27769_saveweights_h5format.ipynb) to save/load the weights in *.h5 format. The only difference is in changing the extension. Thanks!

I am closing the issue as it was resolved in `tf-nightly`. Please feel free to open if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-08-09 17:45 UTC
Labels: comp:keras, type:bug

**Comment by ysyyork** [comment] 2020-05-06 09:08
is this change gonna be in tf 1 ?

**Comment by aii-guo** [comment] 2020-05-13 01:39
> is this change gonna be in tf 1 ?

have you found the solution?
I using the tensorflow 1.1.4 and meet the same error but can not find way to fix it

**Comment by aii-guo** [comment] 2020-05-13 01:39
> @19giorgosts The fix should be in tensorflow-nightly, which you can install using `pip install tf-nightly`

how about tensorflow 1.1.4 or 1.1.5
can not install tensorflow-nightly by pip

**Comment by paulaceccon** [comment] 2021-10-05 21:35
> I am currently submitting a fix for H5.
> 
> @veqtor What problem are you seeing with using the TF format?

That didn't work for me, using that fix in tf-nightly
