### ISSUE TITLE
TF freezes and gets killed while training /saving a network

### ISSUE THREAD

**Issue by deeptigp** [tensorflow/tensorflow#5289] opened 2016-10-30 20:25 UTC
I am trying to train a deep network from scratch (a 4 layer [CIFAR](https://www.tensorflow.org/versions/r0.11/tutorials/deep_cnn/index.html#cifar-10-model) network) on an image collection of 100K images. The TF instance hangs (while training or while saving using tf.Saver) and then gets killed without any error message.

I've tried the following things without any use:

a. Reduced the batch size from 32 to 8.

b. Set config's allow GPU growth option to True

But the problem still persists. 

Has anybody else faced this issue? Is this because of insufficient memory? Is there a way to train a model under constrained memory conditions (although, 12 GB isn't bad)? 
 Any tips to avoid this would be very helpful. 
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I've looked at other similar issues posted but haven't found any useful solution.
https://github.com/tensorflow/tensorflow/issues/2121
http://stackoverflow.com/questions/38958737/tensorflow-training-got-stuck-after-some-steps-how-to-investigate
https://github.com/tensorflow/tensorflow/issues/1962
### Environment info

GPU details: I am running this model on a  Tesla K40c (12GB memory).
Operating System:  4.7.0-1-amd64 #1 SMP Debian 4.7.6-1 (2016-10-07) x86_64 GNU/Linux

Installed version of CUDA and cuDNN: 
/opt/cuda-8.0/lib64/libcudnn.so.5
/opt/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0

(Cuda version: 8.0 and cuDNN version 5)
1. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   0.11.0rc1

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
   ec7f37e40fedb23435bfb7e28668e5fa63ff52f3
2. The output of `bazel version`

Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

This issue is happening when I am trying to train/ save a model

**Comment by drpngx** [comment] 2016-10-30 21:24
There should always be a log somewhere when you get killed, unless you actually run out of memory.

Try setting the env var `GLOG_logtostderr=1`, and also look at `dmesg` to see if you have been sacrificed.

**Comment by yaroslavvb** [comment] 2016-10-30 22:28
Does GLOG_logtostderr do anything? I thought that was for gflags only which
isn't in TF

**Comment by drpngx** [comment] 2016-10-30 22:49
Oh, we don't use glog, right.

**Comment by nroth1** [comment] 2016-11-01 21:45
I am seeing what I think is a similar issue, but am only training on CPU; when I sample the process in a hung state, I see get the following info. In my case, I just see an indefinite hang. Seems to happen randomly, but consistently if I run the program for a few hours, unfortunately. I am also on version, 0.11.0rc0, if that matters. 

[tflow_hang.txt](https://github.com/tensorflow/tensorflow/files/565125/tflow_hang.txt)

**Comment by yaroslavvb** [comment] 2016-11-01 22:08
@nroth1 -- a common way for "random hangs" is by causing a deadlock with
queues, partial solution  is to set operation timeout as [here](
https://github.com/tensorflow/tensorflow/issues/2130#issuecomment-215180165)
and retry on error. More fundamentally is to analyze your queues and
prevent deadlock from occuring, as [here](
https://github.com/tensorflow/tensorflow/issues/4917)

**Comment by nroth1** [comment] 2016-11-01 23:22
Hi, thanks for writing back!

I agree that the partial solution would maybe be a work around, but I was hoping to understand what was happening and maybe get a cleaner fix. I am actually producing my issue without queues, in the strictest sense; I just have some python threads running in parallel (I am aware that I won't get true multithreading in python). In pseudo code this just boils down to: 

`thread1:
       session.run(some_op)
  thread2:
       save.save(session)
`

In this case, there is no dequeue op or queue set of threads that I explicitly call, so it seems like I ought not get the deadlocking issue as described in #4917? But maybe under the covers tensorflow parallelizes access to this shared session object in a way which still leaves this problem open even if you aren't using tensorflow threads/queues to make your calls? 

Thanks a bunch for your help!!

**Comment by yaroslavvb** [comment] 2016-11-01 23:48
If you don't have queues, you shouldn't get deadlocks like this. The only thing I can think of is that your write to disk is hanging on the OS level, so the saving op never terminates

**Comment by nroth1** [comment] 2016-11-01 23:50
hmm, ok, thanks a bunch! I will poke around and update if I find any more information.

**Comment by nroth1** [comment] 2016-11-03 01:40
So, I have been able to isolate the issue to roughly when I call save on a session at the same time that I evaluate an op on the session. When I do so, I get the following backtrace: 

`
2592 _wrap_TF_Run(_object*, _object*)  (in _pywrap_tensorflow.so) + 1301  [0x106599365]
                                                                                                                                                                                                       2592 tensorflow::TF_Run_wrapper(TF_Session*, TF_Buffer const*, _object*, tensorflow::gtl::InlinedVector<char const*, 8> const&, tensorflow::gtl::InlinedVector<char const*, 8> const&, TF_Status*, tensorflow::gtl::InlinedVector<_object*, 8>*, TF_Buffer*)  (in _pywrap_tensorflow.so) + 55  [0x1065b25e7]
                                                                                                                                                                                                         2592 tensorflow::TF_Run_wrapper_helper(TF_Session*, char const*, TF_Buffer const*, _object*, tensorflow::gtl::InlinedVector<char const*, 8> const&, tensorflow::gtl::InlinedVector<char const*, 8> const&, TF_Status*, tensorflow::gtl::InlinedVector<_object*, 8>*, TF_Buffer*)  (in _pywrap_tensorflow.so) + 4930  [0x1065b1492]
                                                                                                                                                                                                           2592 PyEval_RestoreThread  (in Python) + 62  [0x10577defa]
                                                                                                                                                                                                             2592 PyThread_acquire_lock  (in Python) + 101  [0x1057ad790]
                                                                                                                                                                                                               2592 _pthread_cond_wait  (in libsystem_pthread.dylib) + 712  [0x7fffaed7c97a]
                                                                                                                                                                                                          2592 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fffaec93c8a]`

It looks like the session run call is trying to acquire a lock? Is that expected? 

Is it not safe to a save a session at the same time it is being evaluated? I can't find this discussed explicitly in the docs. Thanks again so much for the help!

**Comment by yaroslavvb** [comment] 2016-11-03 02:38
"PyThread_acquire_lock" is how Python GIL is acquired. If GIL is the issue,
there must be another Python thread holding the lock. However, session.run
is supposed to be releasing the lock because of line below in tf_session.i,
so running saver ops shouldn't block evaluation.

// Release the Python GIL for the duration of most methods.
%exception {
  Py_BEGIN_ALLOW_THREADS;
  $action
  Py_END_ALLOW_THREADS;
}

https://github.com/tensorflow/tensorflow/blob/47dd089db3cd16d76595791b2e8483e2fd0b0a25/tensorflow/python/client/tf_session.i#L45

You could look at existing Python threads to see which other thread is
hanging onto the GIL

 def stacktraces(self):
        code = []
        for threadId, stack in sys._current_frames().items():
            code.append("\n thread: %s" % threadId)
            for filename, lineno, name, line in
traceback.extract_stack(stack):
                code.append('\n***  File: "%s", line %d, in %s' % (filename,
                                                                lineno,
name))
                if line:
                    code.append("  %s" % (line.strip()))

        for line in code:
            sys.stderr.write(line)
        sys.stderr.write("\n*** STACKTRACE - END ***\n")

**Comment by nroth1** [comment] 2016-11-09 18:58
So I am still able to occasionally reproduce the freezing. This only occurs when a save operation and a session.run operation occur at roughly the same time. I see the  following backtrace (abbreviated to just show the tensorflow call where the deadlock happens), which seems to indicate that the hang is happening when tflow tries to acquire a lock in ops.py:

`
***  File: "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run  run_metadata_ptr)
***  File: "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 869, in _run  allow_operation=False)
***  File: "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2457, in as_graph_element  with self._lock:`

Any idea on why we would see deadlock there? Or what else could be holding that graph. As before, the save op seems to successfully terminate. 

For what it is worth, I had a very similar version of this code running before I updated to the latest tensorflow (was all the way back on .8) , and did not observe this behavior. 

Thanks a bunch for the time and help!

**Comment by yaroslavvb** [comment] 2017-01-18 17:12
@nroth1 could this be a freeze connected to you running out of memory? If you switch from `Supervisor` to the new MonitoredTrainingSession framework, saving happens in the same Python thread as everything else, so you don't have unlucky parallel `.run` exploding the memory occasionally

**Comment by nroth1** [comment] 2017-02-17 00:35
Hi, sorry for the delayed response. I don't believe the freeze correlated to high memory usage. I have recently upgraded to tensorflow 1.0, so will write back with more details if the problem reproduces itself.

**Comment by nroth1** [comment] 2017-02-17 19:16
I am able to reproduce the issue on version 1.0, and will follow up with more details. Thanks again for all your time!

**Comment by nroth1** [comment] 2017-02-19 21:26
I'm able to reproduce the hangs on a smaller example, and have logs attached. I'm not sure if this is necessarily the same hang as I was seeing above, as the freeze seems to happen in a numpy call, not at the tensorflow level. The example is pretty silly, but I basically just make and evaluate two graphs, while saving them in the background on separate threads. Eventually, it hangs at:

***  File: "crash_eg.py", line 93, in <module>  main_thread2()
***  File: "crash_eg.py", line 79, in main_thread2  session2.run(outputs2,feed_dict = fd)
***  File: "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run  run_metadata_ptr)
***  File: "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 938, in _run  np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
***  File: "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray  return array(a, dtype, copy=False, order=order)

I have attached the full logs below. Need to investigate more about whether this is the same issue as reported above, but thought I would leave the info just in case. I should mention I am on a mac, and have read that there can be some issues with numpy and threading on Mac OS, so maybe that is involved. I am not sure if anyone else has ever seen a similar issue? Thanks again for all your time!

[hang_logs.txt](https://github.com/tensorflow/tensorflow/files/786206/hang_logs.txt)

```
import tensorflow as tf
import threading
import numpy as np
import time
import sys
import traceback

g1 = tf.Graph()
g2 = tf.Graph()

embedding_size = 150
pad_len = 100

with g1.as_default():
    batch_sentence = [tf.placeholder(tf.float32, shape = [None,embedding_size],name= 'tokens') for _ in range(pad_len)]
    cell = tf.contrib.rnn.GRUCell(embedding_size) 
    output1, states1 = tf.contrib.rnn.static_rnn(cell, batch_sentence, dtype = tf.float32)
    loss = tf.reduce_sum(output1[0] - output1[99])
    optimizer = tf.train.AdamOptimizer(1, epsilon=1e-5)
    optimizer.minimize(loss)
    session1 = tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=1))
    session1.run(tf.initialize_all_variables())
    saver1 = tf.train.Saver()

with g2.as_default():
    batch_sentence2 = [tf.placeholder(tf.float32, shape = [None,embedding_size],name= 'tokens') for _ in range(pad_len)]
    cell = tf.contrib.rnn.GRUCell(embedding_size) 
    outputs2, states2 = tf.contrib.rnn.static_rnn(cell, batch_sentence2, dtype = tf.float32)
    loss = tf.reduce_sum(outputs2[0] - outputs2[99])
    optimizer = tf.train.AdamOptimizer(1, epsilon=1e-5)
    optimizer.minimize(loss)
    session2 = tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=1))
    session2.run(tf.initialize_all_variables())
    saver2 = tf.train.Saver()

lock_map = [threading.Lock(),threading.Lock()]


def report_thread():
    while(True):
        def stacktraces():
            code = []
            for threadId, stack in sys._current_frames().items():
                code.append("\n thread: %s" % threadId)
                for filename, lineno, name, line in traceback.extract_stack(stack):
                    code.append('\n***  File: "%s", line %d, in %s' % (filename, lineno, name))
                    if line:
                        code.append("  %s" % (line.strip()))
            for line in code:
                sys.stderr.write(line)
            sys.stderr.write("\n")
        stacktraces()
        time.sleep(300)


def save_wrapper():
    print time.time()
    curr_lock = lock_map[0]
    with curr_lock:
        saver1.save(session1,'out1')
    print time.time()

def save_wrapper2():
    print time.time()
    curr_lock = lock_map[1]
    with curr_lock:
        saver2.save(session2,'out2')
    print time.time()

def main_thread2():
    X = np.random.random((5,150))
    while(True):
        print '------'
        for _ in range(60):
            fd = {}

            for i in range(pad_len):
                fd[batch_sentence2[i]] = X
            session2.run(outputs2,feed_dict = fd)
        save_thread = threading.Thread(target = save_wrapper2)
        save_thread.start()

        for _ in range(60):
            fd = {}
            for i in range(pad_len):
                fd[batch_sentence[i]] = X
            session1.run(output1,feed_dict = fd)
        save_thread = threading.Thread(target = save_wrapper)
        save_thread.start()
        
t1 = threading.Thread(target = report_thread)
t1.start()
main_thread2()


```

**Comment by aselle** [comment] 2017-03-03 23:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2017-03-03 23:39 UTC
Labels: stat:awaiting response, stat:community support, type:bug/performance
