### ISSUE TITLE
tensorflow.keras.layers.TimeDistributed seems to reset batch-size

### ISSUE THREAD

**Issue by constiDisch** [tensorflow/tensorflow#31028] opened 2019-07-25 13:14 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below):1.14.0
- Python version:3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
TimeDistributed resets the batch_shape given in the Input layer.
Could be that this is intended. If so, could you give me a hint how to run the example below? Would be really appreciated.
**Describe the expected behavior**
When using keras (not tensorflow.keras) the example below works fine
So, I expect that wen given the batchsize, TimeDistributed keeps the batchsize.

**Code to reproduce the issue**
```
import tensorflow.keras as keras
keras.backend.set_image_data_format('channels_first')
resnet = keras.applications.resnet50.ResNet50(include_top=False, weights='imagenet')

inputShape = (1,None,3,224,224)
input = keras.layers.Input(batch_shape = inputShape)
x = keras.layers.TimeDistributed(resnet)(input)
x = keras.layers.TimeDistributed(keras.layers.Flatten())(x)
x = keras.layers.LSTM(256, stateful=True)(x)
```

**Other info / logs**
```
ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.
```

**Comment by ravikyram** [comment] 2019-07-26 09:05
I have tried on colab with TF version 1.14.0 was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1vNktBX2U5T6-KilL3zbBDz67FGA3dTnt) here.Thanks!

**Comment by omalleyt12** [comment] 2019-08-12 03:37
@constiDisch TimeDistributed internally combines the batch and 2nd dimension into one dimension, then computes the computation of the time-distributed layer, that's why shape info is getting lost here. We can probably do better shape inference. As a workaround in the meantime, you can do a `set_shape` after the last TimeDistributed layer:

```
inputShape = (1,None,3,224,224)
input = keras.layers.Input(batch_shape = inputShape)
x = keras.layers.TimeDistributed(resnet)(input)
x = keras.layers.TimeDistributed(keras.layers.Flatten())(x)
x.set_shape(<the shape with batch defined here>)
x = keras.layers.LSTM(256, stateful=True)(x)
```

**Comment by jvishnuvardhan** [comment] 2019-08-23 21:14
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-08-23 21:14 UTC
Labels: TF 1.14, comp:keras, stat:awaiting tensorflower, type:bug
