### ISSUE TITLE
Issue is not managed well

### ISSUE THREAD

**Issue by MaxxTr** [tensorflow/tensorflow#46850] opened 2021-02-02 08:40 UTC
Friends, I opened this issue https://github.com/tensorflow/tensorflow/issues/46315 already 3 weeks ago and it look like it is not prioritized and no ETA.... And actually for me it looks like "talking" and not "doing" progress.
I would like to understand if it is regular situation when the updates from support side come a week after ?

Thanks

**Comment by amahendrakar** [comment] 2021-02-02 13:51
@MaxxTr,
I have gone through #46315 and was unable to reproduce the issue. I am facing an `AssertionError` while running the code, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9355221e3586c753152bfdd9823a4247/46315.ipynb#scrollTo=vezHfbbD89dF).

The zip file you have provided is fairly complicated and it would be difficult for us to pinpoint the source of the error. 

Could you please get the example down to the simplest possible repro and provide a **minimal** code snippet which we can copy/paste and run on our end. Thanks!

**Comment by mihaimaruseac** [comment] 2021-02-02 19:55
Please don't create issues to talk about other issues. It just creates work for the triage team.

Closing as duplicate.

**Closed by mihaimaruseac** 2021-02-02 19:55 UTC
Labels: TF 2.4, comp:lite, stat:awaiting response, type:support

**Comment by MaxxTr** [comment] 2021-02-07 08:20
@mihaimaruseac once there was no answer on the original thread I didn't have other solution then open a duplication

**Comment by mihaimaruseac** [comment] 2021-02-08 17:14
You can comment back on that thread to resurface it.
