### ISSUE TITLE
python/keras/engine/network.py:layers took great deal of prediction time on deep networks when using methods like predict_on_batch

### ISSUE THREAD

**Issue by ThinerDAS** [tensorflow/tensorflow#34097] opened 2019-11-08 12:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary, docker
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0

**Describe the current behavior**

When I am using keras and profiling with cProfile, I found that seemly innocent `@property`s of `network.py` become performance bottleneck.

```
  @property
  def dynamic(self):
    if self._is_graph_network:
      return any(layer.dynamic for layer in self.layers)
    return self._dynamic or any(layer.dynamic for layer in self.layers)
  @property
  def layers(self):
    return trackable_layer_utils.filter_empty_layer_containers(
        self._layers)
```

The functions are called fairly frequently without caching the results, and as a result I see them along with related functions (`filter_empty_layer_containers` for example) took inproportional amount of cpu cycles when gpu is hungry. It does not seem right to call the functions again and again when their values are fixed, and they are using 2/3 of the training time. (When will anyone train a network whose dynamicness and number of layers are constantly fluctuating?)

Anyone may try with standard deep resnet with predict_generator/fit_generator and find out whether they are most time consuming.

**Comment by ymodak** [comment] 2019-11-11 19:37
Please provide minimal reproducible code snippet to validate the reported issue. Thanks!

**Comment by ymodak** [comment] 2019-12-09 20:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-12-09 20:16 UTC
Labels: TF 2.0, comp:keras, type:support
