### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus

### ISSUE THREAD

**Issue by naatje80** [tensorflow/tensorflow#8652] opened 2017-03-23 08:39 UTC
In the latest sources the issue: https://github.com/tensorflow/tensorflow/issues/3388 is fixed in the thensorflow/python/client/session.py, But I now receive the following error instead:
```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fb2e08cee48>>
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 595, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'

```
I compiled the model manually using the latest version sources and using Bazel 0.4.5. The same seems to be true as with the issue 3388: The error is not always popping up and the run seems to have ended normally. However, now and then to above error message is displayed.

**Comment by skye** [comment] 2017-03-23 21:18
@naatje80 can you provide a script to repro this?

**Comment by naatje80** [comment] 2017-03-28 07:12
Dear skye, 

thank you for your response. Triggered by your question, I found out that this issue is only occurring when using the Keras module. When I use the Tensorflow module directly I'm not able to reproduce the issue. I assumed that the tensorflow was the issue, as issue #3388 was also occurring at the same moment when I ran my Keras test scripts. Next to that, the error message also reported the issue was occurring in the session.py python script that is part of tensorflow. I will report the issue at the Keras project. Sorry for the inconvenience....

**Comment by skye** [comment] 2017-03-29 16:39
No problem, thanks for digging into this!

**Comment by jonathanve** [comment] 2017-03-29 22:02
Hi @skye and @naatje80 I got the same issue. After installing tensorflow 1.0.1 from source, I no longer get the error. Used keras v2 with MNIST dataset and it took 799s using the terminal.

For some reason, when I use jupyter notebook, it gets blocked. From terminal using py files, everything works ok

**Comment by sdcubber** [comment] 2017-04-27 13:55
Hi, I also have this issue. It pops up from time to time. Keras 2.0.3 and tensorflow 1.1.0.

**Comment by sffc** [comment] 2017-05-01 17:44
This issue reproduces with the following code, which is based on [this example](https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py):

```
import sys

import numpy as np
import tensorflow as tf
import tensorflow.contrib.keras as keras

def main(argv):
	# Get data into numpy arrays of size (?,num_unroll) where ? is the number of
	# data points and num_unroll is the number of time steps...
	x_train = ...
	x_test = ...
	y_train = ...
	y_test = ...

	# Build and run the model
	model = keras.models.Sequential()
	model.add(keras.layers.Embedding(MAX_FEATURES, 128))
	model.add(keras.layers.LSTM(128, dropout=0.2, recurrent_dropout=0.2))
	model.add(keras.layers.Dense(1, activation='sigmoid'))
	model.compile(loss='binary_crossentropy',
	              optimizer='adam',
	              metrics=['accuracy'])
	print('Train...')
	model.fit(x_train, y_train,
	          batch_size=FLAGS.batch_size,
	          epochs=15,
	          validation_data=(x_test, y_test))
	score, acc = model.evaluate(x_test, y_test,
	                            batch_size=FLAGS.batch_size)
	print('Validation score:', score)
	print('Validation accuracy:', acc)

if __name__ == "__main__":
	main(sys.argv)
```

I don't get the error when I `import keras` instead of `import tensorflow.contrib.keras as keras`.

**Comment by zeka0** [comment] 2017-06-04 02:18
It happens to me as well, from time to time.
I used tensorflow-gpu

**Comment by kishorenayar** [comment] 2017-06-06 15:46
It's happening in Tensorflow 1.1.0 tensorflow-gpu 
**Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001A62301DC50>>
Traceback (most recent call last):
  File "D:\Programs\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'**

**Comment by posstrofee** [comment] 2017-06-07 17:31
Getting similar error. Has only happened in last 24-36 hours or so:

**AttributeError: 'NoneType' object has no attribute 'update'**

**Comment by Pr0duktiv** [comment] 2017-06-10 23:36
I had the same problem and checking the code in the file /lib/python3.5/site-packages/tensorflow/python/client/session.py shows this:
```
try:
        status = tf_session.TF_NewStatus()
        tf_session.TF_DeleteDeprecatedSession(self._session, status)
```

the error could be avoided with something like this:
```
try:
        if tf_session is not None:
            status = tf_session.TF_NewStatus()
            tf_session.TF_DeleteDeprecatedSession(self._session, status)
```

**Comment by jabacrack** [comment] 2017-06-15 08:40
windows, python 3.5 in anaconda, tensorflow 1.1.0, keras 2.0.5
when I try to run example perceptron from documentation (https://keras.io/getting-started/sequential-model-guide/) get error 
```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000026A0153E978>>
Traceback (most recent call last):
  File "C:\Miniconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus' 
```
Code that I run
```
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate(x_test, y_test, batch_size=128)
```

**Comment by HughWen** [comment] 2017-06-28 07:05
Same as me.

**Comment by baloodevil** [comment] 2017-07-19 03:09
I'm running windows, python 3.5 in anaconda, tensorflow 1.1.0, keras 2.0.**6**.
When I run the code @jabacrack quoted, I **do not** get the error.  However I **do** get the error when running keras/examples/pretrained_word_embeddings.py.  FYI.

**Comment by jabacrack** [comment] 2017-07-19 10:11
@baloodevil, I get this error sometimes, even if I run some code several times.

**Comment by sausax** [comment] 2017-07-29 03:35
@Pr0duktiv's solution worked for me.

**Comment by mlrobsmt** [comment] 2017-08-25 08:55
any ideas? I only get when I LOAD a model on Py27 Keras 2.0.4 TF 1.1

**Comment by MartinBasti** [comment] 2017-12-20 16:43
This happens to me as well, but python guide warns about usage of `__del__` method, that the other variables can be already garbage collected and thus set to `None`

https://docs.python.org/3/reference/datamodel.html#object.__del__

**Comment by tensorflowbutler** [comment] 2018-01-04 19:15
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:20
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bamartin-ua** [comment] 2018-02-07 19:34
I'm not sure if this is the same error or not; it's saying not callable rather than the attribute, but seems to be in the same method anyway...

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f4cfbc42e10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```

using tensorflow 1.4.1 in docker, using `tensorflow/tensorflow:latest-gpu-py3`
*not* using keras, but I am using `sess = tf.Session()` and `sess.close()` instead of `with tf.Session() as sess:` but that doesn't seem to be sufficient to recreate the error reliably in say ipython3, it only happens when I run my script. perhaps some sort of race condition?

**Comment by marcuniq** [comment] 2018-02-08 10:42
I'm using tensorflow 1.5.0 via docker (gcr.io/tensorflow/tensorflow:1.5.0-devel-gpu-py3) and keras 2.1.3. The following exception sometimes occurs:

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fa52147f898>>
Traceback (most recent call last): 
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 702, in __del__
TypeError: 'NoneType' object is not callable
```

I'm not sure if it's related, but other times my script does not exit and keeps hanging. This makes automatic parameter tuning a hassle.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:07
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by donand** [comment] 2018-02-23 14:20
Same here. I'm usingpython 3.5, tensorflow 1.4.0 and keras 2.1.0 and I get the following error:

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fe252d53dd8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```

I noticed that in the relative code block only the AttributeError exception is catched, but not the TypeError we are getting, probably it should be added.

```
if self._session is not None:
    try:
        status = c_api_util.ScopedTFStatus()
        if self._created_with_new_api:
            tf_session.TF_DeleteSession(self._session, status)
        else:
            tf_session.TF_DeleteDeprecatedSession(self._session, status)
    except AttributeError:
        # At shutdown, `c_api_util` or `tf_session` may have been garbage
        # collected, causing the above method calls to fail. In this case,
        # silently leak since the program is about to terminate anyway.
        pass
    self._session = None
```

**Comment by assif** [comment] 2018-03-10 17:17
Reproduced on an EC2 p2.xlarge (GPU) instance, running ubuntu 16.04.3, keras 2.1.3, tensorflow 1.5.1
`Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f37d83267b8>>
Traceback (most recent call last):
  File "/home/ubuntu/safedk/dl_env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'
`

**Comment by Nimi42** [comment] 2018-03-23 16:58
I get the same error.

'''python
from keras import backend as K
K.clear_session()
'''

This seems to fix it. It feels like a work around though.

**Comment by R-Miner** [comment] 2018-03-28 15:20
It worked for me too. Thanks

**Comment by tensorflowbutler** [comment] 2018-04-12 12:34
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Ares513** [comment] 2018-04-14 01:33
Same problem. I was able to fix this (tensorflow 1.7.0 keras 2.1.5) by simply adding `import tensorflow as tf` before importing keras.

**Comment by tensorflowbutler** [comment] 2018-04-28 18:30
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ghonk** [comment] 2018-05-04 19:39
same issue as reported above.`import tensorflow as tf` solution worked for me

**Comment by tensorflowbutler** [comment] 2018-05-27 03:09
Nagging Assignee @fchollet: It has been 34 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-14 18:48
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by xiaohk** [comment] 2018-06-18 19:34
@assif I am also running my job on AWS p2 instance and having the same issue. Did you solve it?

**Comment by assif** [comment] 2018-06-19 13:57
@xiaohk I used the snippet provided by @Nimi42 and it worked.
(using k.clear_session() at the end of the code).
I agree it's an ugly hack though :)

**Comment by xiaohk** [comment] 2018-06-19 14:49
@assif Thanks! I will try it when I get connection to AWS again. I think I have cuda 8.0 on P2 and I am using Tensorflow 1.4. Are you using Tensorflow 1.5 with cuda 8.0?

**Comment by assif** [comment] 2018-06-19 15:54
@xiaohk Indeed. I'm using tensorflow 1.5.1 with CUDA 8.0.61

**Comment by tensorflowbutler** [comment] 2018-07-04 18:38
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-20 01:16
Nagging Assignee @fchollet: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by weiaicunzai** [comment] 2018-07-29 09:41
Im using tf 1.4 with keras 2.1.5
```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fda61cd9828>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```
this message pops up every 5 or 6 times when I run my code, even with the same code. but besides
this message, nothing really effects me, my code still can run correctly with this error message.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:51
Nagging Assignee @fchollet: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hansioux** [comment] 2018-08-28 08:26
Using python 3.5.2, tf 1.9, and tensorflow.contrib.keras

Seeing this issue intermittently as well. It is fairly annoying as it sometimes splits my output in half.

**Comment by tensorflowbutler** [comment] 2018-09-12 12:40
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-27 19:06
Nagging Assignee @fchollet: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-12 12:46
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-27 12:33
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-11 18:35
Nagging Assignee @fchollet: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-26 18:52
Nagging Assignee @fchollet: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by juebrauer** [comment] 2019-02-22 12:27
Solution of Nimi42 worked for me as well to solve this issue. I added:

from keras import backend as K
K.clear_session()

**Comment by jvishnuvardhan** [comment] 2019-03-22 21:13
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken.

**Closed by jvishnuvardhan** 2019-03-22 21:13 UTC
