### ISSUE TITLE
CSV decode error

### ISSUE THREAD

**Issue by ramnath-k** [tensorflow/tensorflow#3851] opened 2016-08-16 16:49 UTC
I am using Tensorflow 0.9.0. I have CUDA Driver Version = 7.5 and CUDNN 4 on Ubuntu 14.04
This maybe related to another issue I found [here](https://github.com/tensorflow/tensorflow/issues/633)

I have a simple csv file which has a single line like this

```
"field with
newline",0
```

where the newline has been added by pressing Enter key in vim on Ubuntu.
I am able to read this file in pandas using the read_csv function where the text field is shown as containing a single \n character.

But when I try to read it in tensorflow, I get the following error:
`tensorflow.python.framework.errors.InvalidArgumentError: Quoted field has to end with quote followed by delim or end`

My tensorflow code to read the csv uses this function to read a single row.

```
def read_single_example(filename_queue, skip_header_lines, record_defaults, feature_index, label_index):
    reader = tf.TextLineReader(skip_header_lines=skip_header_lines)
    key, value = reader.read(filename_queue)
    record = tf.decode_csv(
            value,
            record_defaults=record_defaults)
    features, label = record[feature_index], record[label_index]
    return features, label
```

If I read using pandas and replace all newlines with spaces, the tensorflow code is able to parse the csv successfully.

But it will be really helpful if newlines can be handled within the Tensorflow CSV pipeline itself.

**Comment by ramnath-k** [comment] 2016-08-17 04:42
I tried this on Tensorflow 0.10 and the issue is still there. Please advise on possible ways to solve the problem.

**Comment by aselle** [comment] 2016-08-17 17:25
@jmchen-g, it looks like you wrote the CSVReader original. It seems like it is possible that each row of a csv may need to consume an arbitrary number of lines, because embedded unescaped newlines are allowed in the format.  https://tools.ietf.org/html/rfc4180.  Section 2 talks about CRLF's even being allowed.

**Comment by vrv** [comment] 2016-08-17 17:28
Isn't the use of TextLineReader the problem?

**Comment by aselle** [comment] 2016-08-17 17:33
Good point... to expand on @vrv's suggestion... He pointed out ot me that maybe WholeFileReader could possibly work. Can you try that and let us know if that solves your problem?

**Comment by ramnath-k** [comment] 2016-08-18 05:30
I tried this in Tensorflow 0.10. I changed to use WholeFileReader instead of TextLineReader.
I get the following error `tensorflow.python.framework.errors.InvalidArgumentError: Unquoted fields cannot have quotes/CRLFs inside`

Also I have another question about using a WholeFileReader. If the input csv file is large wouldn't WholeFileReader bring all of the data into memory, causing an out of memory error?

**Comment by aselle** [comment] 2016-08-18 16:53
Yeah WholeFileReader is not a great solution for large files, but it at least allowed testing whether the CSVReader was robust to CRLFs. In any case it seems like a bug in the csv reader. Assigning to @jmchen-g.

**Comment by jmchen-g** [comment] 2016-08-23 05:45
This is not a bug but intended behavior. In decode_csv, the input is expected to be a tensor of string/record, each element string is expected to be a record. Inside the record, it is already supported that you can have '\n' in a string field. It is expected that some pre-processing is done to satisfy this requirement. 

If we don't have such constraint, the example below will have a problem to decide if 5 is from the second or third record:
"  
    1,2,3, (first record)
    ,4,  (second)
    5,6,7 (third)
"

**Comment by aselle** [comment] 2016-08-23 16:43
@jmchen-g, That reasoning  makes sense from a simplicity of implementation stand point, but then we are technically not adhering to the RFC.
https://tools.ietf.org/html/rfc4180
Section 2  item 6 specifically mentions this case. If we aren't going to change it, I suggest we just add this deviation from the standard in the documentation to make it easier for users to know to do the preprocessing. It is also true that CSV is a very de facto standard anyways and there are many variants.

**Comment by ramnath-k** [comment] 2016-08-24 21:41
hi @aselle and @jmchen-g , I think I understand that if some preprocessing is done to extract records from the file and feed it to decode_csv.
Currently there is no CSVReader which can read a single csv record for decode_csv. I think all that is required is to wrap TextLineReader, and read till a \n, determine if we are within a quoted field. Will counting number of double quotes and seeing if it is odd suffice to validate this? 

Then if we are inside quoted field read more lines until number of quotes becomes even. When that happens return the record.

I don't know how to write this class and replace TextLineReader with this. Can you guide me to write it?

**Comment by jmchen-g** [comment] 2016-08-26 22:31
@aselle We already allow section 2 item 6 case in the current implementation. The only issue here is that the current op expect a tensor of records, each of which is a record. 

You will need to either preprocess the csv to generate the tensor of records or have a new op that takes the whole file and process on the fly. It is better to just convert it directly instead of composing tensor of records and do another traversal of it in this op.

**Comment by darrengarvey** [comment] 2016-11-07 11:30
I hit this issue too. I was hoping to be able to use the in-graph loading of data to simplify a multi-GPU pipeline.

If `decode_csv()` really needs just one record then the reader needs to itself do some parsing of the CSV just to see when a record ends, which seems a bit counter to the current separation of reader/decoder. Using `WholeFileReader` would work for me (I can just split up the inputs into multiple files) and I was thinking of having a go making `decode_csv()` handle multiple input/output records.

An alternative would be to have something like a `CSVLineReader` that just has a simple "am I inside a quoted field" check and is otherwise like `TextLineReader`. Sounds from the comments above that this might be a more welcome addition?

**Comment by drpngx** [comment] 2017-01-24 22:04
@darrengarvey I suppose you could go ahead and have a `CSVLineReader`. Note that this will complicate things when we allow splittable files.

**Comment by darrengarvey** [comment] 2017-01-24 22:17
@drpngx - Can you give any more information on what you mean by "splittable files"?

In the end I've been going more in the direction of writing (a much more complicated) input function that feeds this data into a tf.learn `Estimator` using multiple threads in Python that feed data into a queue. This is basically done but seemingly very complicated to get right.

**Comment by drpngx** [comment] 2017-01-25 02:09
"Splittable file" is hadoop parlance for files that can be split for parallel processing. An example of that is a simple file, say, that has fixed-length records. Each thread can skip to an offset and read from there. An example of a non-skippable file is stream-compressed file.

**Comment by slothkong** [comment] 2018-02-01 08:41
I experienced this error when moving my code to windows ( running tensorflow in Anaconda3). In my case, I also work with csv data created by myself.  However, the error occurs only when I create the csv data running my code in Windows, so it is definitely related to the way the OS ends each line of the file. The question is, what extra consideration should I make in order to create the file  in Windows that does not have this problem?  To create the file  I use the csv library available in python.

**Comment by drpngx** [comment] 2018-02-02 19:19
@slothkong please ask this question on stackoverflow.

**Comment by gunan** [comment] 2018-02-07 23:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gunan** 2018-02-07 23:23 UTC
Labels: stat:contributions welcome

**Comment by mkruglyak** [comment] 2021-08-11 14:06
Here's the updated link for [`tf.data.experimental.CsvDataset`](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset)
