### ISSUE TITLE
tf.enable_eager_execution() bug?

### ISSUE THREAD

**Issue by Q82822** [tensorflow/tensorflow#21872] opened 2018-08-25 12:52 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:window10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**:3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
i used the` tf.enable_eager_execution()` and create InceptionResNetV2 mode will be error and only InceptionResNetV2 have. I need use  `tf.enable_eager_execution()` can't without. 

how to fix it?

### Source code / logs
`import tensorflow as tf`
`tf.enable_eager_execution()`
`image_model =tf.keras.applications.InceptionResNetV2(include_top=False, weights='imagenet')
`
--error---
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b40bb13774b9> in <module>()
----> 1 image_model =tf.keras.applications.InceptionResNetV2(include_top=False, weights='imagenet')

D:\anaconda\lib\site-packages\tensorflow\python\keras\applications\inception_resnet_v2.py in InceptionResNetV2(include_top, weights, input_tensor, input_shape, pooling, classes)
    304   for block_idx in range(1, 11):
    305     x = inception_resnet_block(
--> 306         x, scale=0.17, block_type='block35', block_idx=block_idx)
    307 
    308   # Mixed 6a (Reduction-A block): 17 x 17 x 1088

D:\anaconda\lib\site-packages\tensorflow\python\keras\applications\inception_resnet_v2.py in inception_resnet_block(x, scale, block_type, block_idx, activation)
    187       output_shape=K.int_shape(x)[1:],
    188       arguments={'scale': scale},
--> 189       name=block_name)([x, up])
    190   if activation is not None:
    191     x = Activation(activation, name=block_name + '_ac')(x)

D:\anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    745           input_shapes = nest.map_structure(lambda x: x.shape, inputs)
    746 
--> 747         output_shapes = self.compute_output_shape(input_shapes)
    748         output_shapes = nest.flatten(output_shapes)
    749         outputs = [

D:\anaconda\lib\site-packages\tensorflow\python\keras\layers\core.py in compute_output_shape(self, input_shape)
    678 
    679   def compute_output_shape(self, input_shape):
--> 680     input_shape = tuple(tensor_shape.TensorShape(input_shape).as_list())
    681 
    682     if self._output_shape is None:

D:\anaconda\lib\site-packages\tensorflow\python\framework\tensor_shape.py in __init__(self, dims)
    539       else:
    540         # Got a list of dimensions
--> 541         self._dims = [as_dimension(d) for d in dims_iter]
    542     self._ndims = None
    543 

D:\anaconda\lib\site-packages\tensorflow\python\framework\tensor_shape.py in <listcomp>(.0)
    539       else:
    540         # Got a list of dimensions
--> 541         self._dims = [as_dimension(d) for d in dims_iter]
    542     self._ndims = None
    543 

D:\anaconda\lib\site-packages\tensorflow\python\framework\tensor_shape.py in as_dimension(value)
    480     return value
    481   else:
--> 482     return Dimension(value)
    483 
    484 

D:\anaconda\lib\site-packages\tensorflow\python\framework\tensor_shape.py in __init__(self, value)
     35       raise TypeError("Cannot convert %s to Dimension" % value)
     36     else:
---> 37       self._value = int(value)
     38       if (not isinstance(value, compat.bytes_or_text_types) and
     39           self._value != value):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'TensorShape'

**Comment by yongtang** [comment] 2018-08-25 18:02
@Q82822 I am able to reproduce with 1.10 but not the latest nightly build. Can you try with tf-nightly and see if the issue has been resolved?

**Comment by Q82822** [comment] 2018-08-26 05:56
it is still not work
have the same problem

**Comment by yongtang** [comment] 2018-08-26 17:48
I am working on a Linux machine. With tf-nightly (`1.11.0-dev20180826`) it seems to be working:
```
# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.VERSION
'1.11.0-dev20180826'
>>> tf.enable_eager_execution()
>>> image_model =tf.keras.applications.InceptionResNetV2(include_top=False, weights='imagenet')
2018-08-26 17:47:03.515629: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.7/inception_resnet_v2_weights_tf_dim_ordering_tf_kernels_notop.h5
219062272/219055592 [==============================] - 2s 0us/step
219070464/219055592 [==============================] - 2s 0us/step
>>> 
```

**Comment by yongtang** [comment] 2018-08-27 20:31
@Q82822 Which version are you using? Can you check:
```
>>> import tensorflow as tf
>>> tf.VERSION
'1.11.0-dev20180826'
```

**Comment by Q82822** [comment] 2018-08-28 08:42
my tensorflow version is 1.10 and  CUDA/cuDNN version: 9.2/7.1
```
>>> import tensorflow as tf
>>> print(tf.__version__)
1.10.1
```

**Comment by yongtang** [comment] 2018-08-28 20:56
@Q82822 Can you uninstall tensorflow and reinstall with `pip install tf-nightly` to get the nightly build?

**Comment by Q82822** [comment] 2018-09-06 06:55
very appreciate you help. i can build mode now

**Comment by drpngx** [comment] 2018-09-17 22:27
@yongtang thank you for helping out!
@Q82822 closing since it seems that you have a solution.

**Closed by drpngx** 2018-09-17 22:27 UTC
Labels: comp:eager
