### ISSUE TITLE
the output of `tf.sigmoid` is abnormal when input has nans.

### ISSUE THREAD

**Issue by r05323028** [tensorflow/tensorflow#29048] opened 2019-05-27 08:36 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 64bit, AWS EC2 p3.2xlarge instance
- TensorFlow installed from (source or binary): `pip install tensorflow-gpu`
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA Tesla V100 16GB

**Describe the current behavior**

the output of the `tf.sigmoid` function seems abnormal when the input has nans.
```python
In [1]: import tensorflow as tf
In [2]: tf.enable_eager_execution()
In [3]: a = tf.constant([float('nan')]*5)
In [4]: tf.sigmoid(a)
Out[4]: <tf.Tensor: id=1, shape=(5,), dtype=float32, numpy=array([ 1.,  1.,  1.,  1., nan], dtype=float32)>
```
**Describe the expected behavior**
```python
In [4]: tf.sigmoid(a)
Out[4]: <tf.Tensor: id=1, shape=(5,), dtype=float32, numpy=array([ nan,  nan,  nan,  nan, nan], dtype=float32)>
```
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
import tensorflow as tf
tf.enable_eager_execution()
a = tf.constant([float('nan')]*5)
b = tf.sigmoid(a)
print(b)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment] 2019-05-28 08:04
@r05323028 Able to reproduce the issue in 1.13.1 and 2.0.0-alpha0

**Comment by kmh4321** [comment] 2019-05-29 18:04
I am unable to reproduce this issue with `1.13.1`.

**Comment by jvishnuvardhan** [comment] 2019-05-29 18:13
@r05323028 I agree. The output is not normal when you use T1.13.1. Gist is [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/08420246eaf7319304607499f604091d/tf29048_1p13.ipynb)
Output: `tf.Tensor([ 1.  1.  1.  1. nan], shape=(5,), dtype=float32)`

But in TF2.0.0-alpha0, everything works as expected. Gist is [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/3b9cb892db87a9ae38dfae8d5e56a0ad/tf29048.ipynb).
Output: `tf.Tensor([nan nan nan nan nan], shape=(5,), dtype=float32)`

Can you upgrade to TF2.0? Thanks!

**Comment by r05323028** [comment] 2019-05-30 05:37
@jvishnuvardhan Thanks for your response!
I tried TF2.0 on `AWS ec2 p3.2xlarge` gpu instance which uses `NVIDIA Tesla V100-SXM2-16GB` but it still has the same problem.

<img width="1236" alt="螢幕快照 2019-05-30 下午1 32 53" src="https://user-images.githubusercontent.com/37167503/58610851-9c1d6200-82df-11e9-9cdf-080ae1439b36.png">

Machine's spec is as follows

<img width="1234" alt="螢幕快照 2019-05-30 下午1 33 22" src="https://user-images.githubusercontent.com/37167503/58610942-eacafc00-82df-11e9-8837-9692afa4c45c.png">

**Comment by jvishnuvardhan** [comment] 2019-05-30 13:00
@r05323028 Sorry for my mistake. I ran tf-cpu version in GPU and I don't see any error so I reported that as my last response. However, i can reproduce the issue with tf-gpu version. Thanks for finding this. Thanks!

**Comment by alextp** [comment] 2019-05-31 18:24
@rmlarsen @azaks2 this is the known issue around GPU kernels sometimes losing NaNs altogether, right?

**Comment by tensorflowbutler** [comment] 2021-02-19 19:10
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jvishnuvardhan** [comment] 2021-02-20 02:23
@r05323028 I think this is resolved in recent `tf-nightly-gpu`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/308ea7491c7923cc25705036afebc46f/tf29048.ipynb).

Output is 
`tf.Tensor([nan nan nan nan nan], shape=(5,), dtype=float32)`

I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-02-20 02:23 UTC
Labels: TF 1.13, comp:ops, type:bug
