### ISSUE TITLE
tensorflow/core/common_runtime/bfc_allocator.cc:246] tried to allocate 0 bytes 

### ISSUE THREAD

**Issue by nm46nm** [tensorflow/tensorflow#27998] opened 2019-04-20 04:56 UTC
I'm training some yolo models using 

> qqwweee/keras-yolo3

When I trained with 50 epochs, the test can be done although the results is bad.
So I trained with 150 epochs, and when I want to test with this model, I got the following ... (it's not an error but like an error):

Input image filename:eagle.jpg
(416, 416, 3)
2019-04-20 12:33:44.137176: E tensorflow/core/common_runtime/bfc_allocator.cc:246] tried to allocate 0 bytes
2019-04-20 12:33:44.140305: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2019-04-20 12:33:44.143018: E tensorflow/core/common_runtime/bfc_allocator.cc:246] tried to allocate 0 bytes
2019-04-20 12:33:44.145718: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2019-04-20 12:33:44.149139: E tensorflow/core/common_runtime/bfc_allocator.cc:246] tried to allocate 0 bytes
2019-04-20 12:33:44.151644: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2019-04-20 12:33:44.154246: E tensorflow/core/common_runtime/bfc_allocator.cc:381] tried to deallocate nullptr
2019-04-20 12:33:44.157496: E tensorflow/core/common_runtime/bfc_allocator.cc:381] tried to deallocate nullptr
2019-04-20 12:33:44.160937: E tensorflow/core/common_runtime/bfc_allocator.cc:381] tried to deallocate nullptr
Found 0 boxes for img
6.07202067316063

I think it's something wrong in TF.
environment: Anaconda python(3.6.8), keras 2.1.5, tensorflow (cpu) 1.10.0.
I use "qqwweee/keras-yolo3" and made a train data as its requirement like follows :

> Generate your own annotation file and class names file.
One row for one image;
Row format: image_file_path box1 box2 ... boxN;
Box format: x_min,y_min,x_max,y_max,class_id (no space).
For VOC dataset, try python voc_annotation.py
Here is an example:
path/to/img1.jpg 50,100,150,200,0 30,50,200,120,3
path/to/img2.jpg 120,300,250,600,2
...

**Comment by byronyi** [comment] 2019-04-20 04:59
Please fill in the information of your environment so we could know how to reproduce this error.

Thanks.

**Comment by nm46nm** [comment] 2019-04-20 05:15
> Please fill in the information of your environment so we could know how to reproduce this error.
> 
> Thanks.

I updated the problem with environment.

**Comment by byronyi** [comment] 2019-04-20 05:20
Could you try to install the latest tf-nightly package? I believe this issue has been fixed.

**Comment by nm46nm** [comment] 2019-04-20 06:09
But if I use TF 1.13.1,  there will be another problem. See #27906

**Comment by byronyi** [comment] 2019-04-20 07:38
Could you try tf-nightly? It helps us to reproduce your problem.

We cannot fix your issue if we cannot reproduce it.

**Comment by gadagashwini** [comment] 2019-04-29 11:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-04-29 11:28 UTC
Labels: comp:model, comp:runtime, stat:awaiting response
