### ISSUE TITLE
A model results inconsistent output values depending on input batch size

### ISSUE THREAD

**Issue by donguklim** [tensorflow/tensorflow#35691] opened 2020-01-09 06:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): python:3.7.5-slim docker image, macOS Catalina 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip 19.3.1
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.5(docker), 3.7.4(macOs)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
The `predict` method of `tf.keras.applications.mobilenet.MobileNet`, gives different output values when the batch sizes are different even though all input value are the same.
This problem does not occur with Tensorflow 2.0.0 and occurs with 2.1.0

**Describe the expected behavior**
The output value of an input does not change as it is in another batch with different size.

**Code to reproduce the issue**
``` python
import numpy as np
import tensorflow as tf


def test_mobile_net():
    four_black_images = np.zeros((4, 224, 224, 3), dtype='uint8')
    one_black_image = np.zeros((1, 224, 224, 3), dtype='uint8')

    four_input = tf.keras.applications.mobilenet.preprocess_input(four_black_images)
    one_input = tf.keras.applications.mobilenet.preprocess_input(one_black_image)

    # below assert statement passes, meaning all input batches have the same input values
    for i in range(4):
        assert (four_input[i] == one_input[0]).all()

    model = tf.keras.applications.mobilenet.MobileNet(input_shape=(224, 224, 3), include_top=False, pooling='avg')

    one_image_result = model.predict(one_input)
    four_images_result = model.predict(four_input)

    # bellow assert statement passes
    # There is no inter-differences between  output values within the same batch
    for i in range(4):
        for j in range(4):
            assert (four_images_result[i] == four_images_result[j]).all()

    # Bellow assert statement fails with Tensorflow 2.1.0 but passes with 2.0.0
    assert (four_images_result[0] == one_image_result[0]).all()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I also have tested with batch size with 4 and 7, wondering if the output result is only different when the batch has size 1, but it also gave inconsistent results. 
So the output value changes as batch size changes with version 2.1.0.

**Comment by ravikyram** [comment] 2020-01-09 10:01
I have tried on colab with TF version 2.0 and i am not seeing any issue. However with TF version 2.1 i am seeing `AssertionError: `.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c67db102bcfbfbeaeda51e28c3620efc/untitled541.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-10 17:23
@donguklim I agree. `AssertionError: ` is reproducible with `tf-nightly` but not with `TF2.0`. However, the inconsistency is in 5th decimal when I applied `tf.reduce_sum` for the two data. So I would say the inconsistency could be due to precision related. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/4009ed5d1e5f99b942c4f175e1439809/untitled741.ipynb).

Output of your code with `tf.reduce_sum` as follows. You can check the results differ only in the 5th decimal. Thanks

```
Four tf.Tensor(76.64975, shape=(), dtype=float32)
Single: tf.Tensor(76.64976, shape=(), dtype=float32)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-646cdf461c0a> in <module>()
     29     print('Single:',tf.reduce_sum(one_image_result[0]))
     30     assert (four_images_result[0] == one_image_result[0]).all()
---> 31 test_mobile_net()

<ipython-input-8-646cdf461c0a> in test_mobile_net()
     28     print("Four",tf.reduce_sum(four_images_result[0]))
     29     print('Single:',tf.reduce_sum(one_image_result[0]))
---> 30     assert (four_images_result[0] == one_image_result[0]).all()
     31 test_mobile_net()

AssertionError: 
```

**Comment by qlzh727** [comment] 2020-01-13 05:25
I agree with  @jvishnuvardhan that the numerical difference is precision related and very insignificant. Rather than use "==", you can use np.allclose() which will return True.

Closing this bug since there is nothing need to be addressed here.

**Closed by qlzh727** 2020-01-13 05:25 UTC
Labels: TF 2.1, comp:keras, stat:awaiting tensorflower, type:bug
