### ISSUE TITLE
iterating over 'tf.Tensor' is not allowed AutoGraph did not convert this function. 

### ISSUE THREAD

**Issue by suwoncjh** [tensorflow/tensorflow#33308] opened 2019-10-13 15:13 UTC
Hi, I am trying to convert below function to tensorflow graph using tf.function decorator.

However, I got an error message. 

My question is which part should I change the code below to use tf.function?

thanks. 

```python
@tf.function 
def band2bin(bands):
        tensor_list = [tf.tile(tf.expand_dims(bands[:, b, :], axis=1), [1, hp.band[b, 1]-hp.band[b, 0]+1, 1]) for b in tf.range(bands.shape[1])]
        bins = tf.concat(tensor_list, axis=1)
    return bins
```
error message: 
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by Yablon** [comment] 2019-10-13 16:54
As the error message says, I think maybe you can try to avoid using "for" loop in the function. And maybe you can choose tf.numpy_function as an alternertive.

**Comment by gadagashwini** [comment] 2019-10-14 09:19
@suwoncjh, Can you try @Yablon's workaround and let us know if issue still persists. Thanks!

**Comment by suwoncjh** [comment] 2019-10-16 07:34
Thanks @Yablon 

I solved it by changing tf.range to range and it works.

**Comment by gadagashwini** [comment] 2019-10-16 09:17
@suwoncjh, Glad that it resolved. 
Closing the issue now. Feel free to reopen if issue still persists. Thanks!

**Closed by gadagashwini** 2019-10-16 09:17 UTC
Labels: comp:ops, stat:awaiting response, type:support

**Comment by schlichtkrull** [comment] 2020-03-13 23:08
I faced the same error, luckily I solved it.
My code
```python
rnn = rnn_cell(units)
_, state = rnn(inputs, hidden_state) # Outputs only the state (the mistake I made)
```
And for some reason you can't split a tensor with shape (10,100) in two, which makes perfectly sense, but I think the error message is really misleading, so it would be helpful to either to make the error message more leading or give me the file where error messages is displayed, checked or something and then I'll create a pull request.

**Comment by msh855** [comment] 2020-04-20 07:08
I was not able to solve a similar problem. 

I have understood what the problem is, but I am not sure how to get around it using in order to decorate my function. 

In a part of my code, I have to loop over different parameter values to solve a nonlinear equation. Because of this loop, however, my defined function cannot be decorated with `@tf.function`

Here is a MWE to replicate the error: 

```
import numpy  as np 
import tensorflow as tf
import scipy.optimize 

# fixed parameters
kon = 0.01
mu  = 1.5
fi  = 0.5 
kappa = 22
w = 0.63

# varying parameters 
n =100
xs = tf.random.normal(shape=(n,), stddev=0.2)
eps = tf.random.normal(shape=(n,), stddev=0.17)
z = tf.sigmoid(tf.random.normal(shape=(n,), stddev=0.22))
```

This is the function that I am trying to decorate: 
```

def get_leisure(z, eps, x0):
    hvec = np.empty((0,))
    # leisure today
    for ze,ei,xs in zip(z, eps, x0):
        ei=np.exp(ei)
        xs=np.exp(xs)
        # define the function for leisure 
        def leisure_function(hi):
            return (mu/fi)*np.log(hi) -(1-mu)*kappa*(hi)**(1+(1/fi))- mu*(np.log(w*ei*xs)-np.log(kon))-np.log(ze)

        htemp = scipy.optimize.newton_krylov(leisure_function, 0.5)
        hvec = np.append(hvec, htemp)
    return hvec
```

Without decoration, it works fine. when I call the function. But I try to decorate it, fails giving me the same error message as in this issue.
