### ISSUE TITLE
Problem anaconda tensorflow Windows : Traceback <most recent call last>:   File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by salmiadu** [tensorflow/tensorflow#9033] opened 2017-04-06 22:48 UTC
Hi Guys!  [ # if you don't won't to read everything go down directly to # SOLUTION ]
here is the way how i fixed the problem of installing tensorflow on Windows. I will start 👍from the begining 👍 
1. I downloaded the Anaconda 4.3.1 For Windows with Python 3.6 version. 
2. Create a conda environment named tensorflow by invoking the following command:
C:> conda create -n tensorflow 

3. Activate the conda environment by issuing the following command:
C:> activate tensorflow
 (tensorflow)C:>  # Your prompt should change 

3. Issue the appropriate command to install TensorFlow inside your conda environment. To install the CPU-only version of TensorFlow, enter the following command:

(tensorflow)C:> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl 

Message appear : can not install this wheel ......... [ i forgot the message, it's just couldn't find the point]
To install the GPU version of TensorFlow, enter the following command (on a single line):
(tensorflow)C:> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl  

same message appear couldn't install 

so after that i wanted to write my first code 👍 
c>python
python version 3.6 .... (anaconda).............
>>> import tensorflow as tf
[it appears this Error : ]

Traceback <most recent call last>:
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

-----------------------------------------------------------------------------
SOLUTION
Fix The Problem :
https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

tensorflow-1.0.1 -cp35-cp35m-win_amd64.whl
tensorflow version 1.0.1 
-cp 35 : python version needed
win_amd64 : windows x64 

so the Anaconda 4.3.1 For Windows with Python 3.6 version so we need python 3.5 i downloaded it from other this web site cause anaconda has only the version 4.3.1 &  for python 2.7 : 
so this anaconda for python 3.5 : http://www.gurobi.com/downloads/get-anaconda 
then i followed the other steps & everything worked fine :), i hope everything will work with you

**Comment by asimshankar** [comment] 2017-04-07 00:07
Closing as a duplicate of #6999

**Closed by asimshankar** 2017-04-07 00:07 UTC

**Comment by salmiadu** [comment] 2017-04-07 00:15
#aismshankar i read about that, to rename it cp36 won't help, it is still the same issue, :) that's why i posted this solution, i worked on it yesterday
Thank you shankar

**Comment by kislaysr** [comment] 2017-07-17 19:49
Changing version from 3.6 to 3.5 worked for me.
The full process was : 
(inside virtual env)
conda install python=3.5
pip install tensorflow

**Comment by tayyabbutt2007** [comment] 2018-06-21 15:29
I'm using tensorflow for the first time, I've installed it successfully but when I try to run it gives me the following error kindly help me it's been 2 days I haven't found the solution.

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

**Comment by Therapy2018** [comment] 2018-10-14 20:32
> I'm using tensorflow for the first time, I've installed it successfully but when I try to run it gives me the following error kindly help me it's been 2 days I haven't found the solution.
> 
> > > > import tensorflow as tf
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ModuleNotFoundError: No module named 'tensorflow'

You have to install tensorflow first. To do it print in your Shell:

pip install tensorflow

**Comment by ugrgarciar** [comment] 2021-02-21 06:09
python 3.9 does not work with tensorflow-2.4. you have to try python 3.7
