### ISSUE TITLE
ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization'

### ISSUE THREAD

**Issue by Mather10** [tensorflow/tensorflow#54514] opened 2022-02-24 10:36 UTC
How to fix the error below? Thanks.

`ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/normalization/__init__.py)
`

**Comment by tilakrayal** [comment] 2022-02-24 16:40
@Mather10 ,
Can you please take a look at this link [1](https://github.com/kingoflolz/mesh-transformer-jax/issues/97) [2](https://github.com/tensorflow/tensorflow/issues/54401) and SO link [1](https://stackoverflow.com/questions/68080345/importerror-cannot-import-name-layernormalization-from-tensorflow-python-ker) [2](https://stackoverflow.com/questions/67549661/importerror-cannot-import-name-layernormalization-from-tensorflow-python-ker) with the similar error.It helps.Thanks!

**Comment by Mather10** [comment] 2022-02-25 09:44
@tilakrayal    

Thank you for your reply, but as I tried that, the error still occurs. So how to fix it? 

Thanks.

**Comment by tilakrayal** [comment] 2022-02-25 11:03
@Mather10 ,
I was able to import.Can you please try as suggested in the [gist](https://colab.research.google.com/gist/tilakrayal/5d91dd701d6e0986be43263b3ec70f69/untitled241.ipynb).It helps.Thanks!

**Comment by Mather10** [comment] 2022-02-26 01:39
@tilakrayal  

 from tensorflow.keras.layers import LayerNormalization

Thank you for your reply, but as I tried to run "import tensorflow as tf", the error "ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization'" still occurs. So how to fix it?

Thanks.

**Comment by sampathweb** [comment] 2022-02-28 04:49
@Mather10 - You may want to use 
```
from tensorflow.keras.layers import LayerNormalization
```

Seems to be duplicate of #54637

**Comment by tilakrayal** [comment] 2022-02-28 09:32
@Mather10 ,
Can you please find the attached [gist](https://colab.research.google.com/gist/tilakrayal/5d91dd701d6e0986be43263b3ec70f69/untitled241.ipynb) and try the code as requested.It helps.Thanks

**Comment by Bhavya-official** [comment] 2022-03-01 08:12
> @Mather10 - You may want to use
> 
> ```
> from tensorflow.keras.layers import LayerNormalization
> ```
> 
> Seems to be duplicate of #54637

That works

**Closed** 2022-03-15 09:27 UTC
Labels: stat:awaiting response, type:support, stalled, comp:keras
