### ISSUE TITLE
TF Lite: error: use of deleted function 'std::atomic<bool> in tensorflow/tensorflow/lite/core/async/task_internal.h

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#62988] opened 2024-02-18 18:18 UTC
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

No

### OS platform and distribution

Ubuntu Linux 22.04

### Python version

3.10

### Bazel version

6.1

### GCC/compiler version

Ubuntu clang version 14.0.0-1ubuntu1.1

### Current behavior?

When compiling libcoral from [here](https://github.com/feranick/libcoral) - a fork of the [libcoral](https://github.com/google-coral/libedgetpu) library to allow support for modern versions of TFs, tensorflow is downloaded, and compiled. However, compilation stops because of the use of a deleted functions `deleted function 'std::atomic<bool>::atomic(const std::atomic<bool>&)'` and `'std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = TfLiteStatus]' in `org_tensorflow/tensorflow/lite/core/async/task_internal.h` (see log below). Normally this is not compiled when building the regular `tflite_runtime`, but it is called for compilation in this specific case when it is used to link to the `libcoral` library.

The two calls in 
`std::atomic_bool scheduled_ = false;`
and
`std::atomic<TfLiteStatus> status_ = kTfLiteOk;`

should be changed to allow for correct initialization.

### Standalone code to reproduce the issue

```shell
git clone https://github.com/feranick/libcoral
cd libcoral
git submodule init && git submodule update
make DOCKER_IMAGE=ubuntu:22.04 DOCKER_CPUS="k8" DOCKER_TARGETS=tests docker-build
```

### Relevant log output

```shell
--sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:15:
external/org_tensorflow/tensorflow/lite/core/async/task_internal.h:141:33: error: use of deleted function 'std::atomic<bool>::atomic(const std::atomic<bool>&)'
  141 |   std::atomic_bool scheduled_ = false;
      |                                 ^~~~~
In file included from external/org_tensorflow/tensorflow/lite/core/async/task_internal.h:18,
                 from external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:15:
/usr/include/c++/11/atomic:72:5: note: declared here
   72 |     atomic(const atomic&) = delete;
      |     ^~~~~~
/usr/include/c++/11/atomic:76:15: note:   after user-defined conversion: 'constexpr std::atomic<bool>::atomic(bool)'
   76 |     constexpr atomic(bool __i) noexcept : _M_base(__i) { }
      |               ^~~~~~
In file included from external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:15:
external/org_tensorflow/tensorflow/lite/core/async/task_internal.h:144:39: error: use of deleted function 'std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = TfLiteStatus]'
  144 |   std::atomic<TfLiteStatus> status_ = kTfLiteOk;
      |                                       ^~~~~~~~~
In file included from external/org_tensorflow/tensorflow/lite/core/async/task_internal.h:18,
                 from external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:15:
/usr/include/c++/11/atomic:227:7: note: declared here
  227 |       atomic(const atomic&) = delete;
      |       ^~~~~~
/usr/include/c++/11/atomic:231:17: note:   after user-defined conversion: 'constexpr std::atomic<_Tp>::atomic(_Tp) [with _Tp = TfLiteStatus]'
  231 |       constexpr atomic(_Tp __i) noexcept : _M_i(__i) { }
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc: In member function 'bool tflite::async::ExecutionTask::GetTensorIdx(TfLiteIoType, const char*, int*) const':
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:40:7: warning: init-statement in selection statements only available with '-std=c++17' or '-std=gnu++17'
   40 |   if (auto it_idx = map->find(name); it_idx != map->end()) {
      |       ^~~~
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc: In member function 'TfLiteBufferHandle tflite::async::ExecutionTask::GetBufferHandle(int) const':
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:57:7: warning: init-statement in selection statements only available with '-std=c++17' or '-std=gnu++17'
   57 |   if (auto it = io_data_.find(tensor_index); it != io_data_.end()) {
      |       ^~~~
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc: In member function 'TfLiteSynchronization* tflite::async::ExecutionTask::GetSynchronization(int) const':
external/org_tensorflow/tensorflow/lite/core/async/task_internal.cc:90:7: warning: init-statement in selection statements only available with '-std=c++17' or '-std=gnu++17'
   90 |   if (auto it = io_data_.find(tensor_index); it != io_data_.end()) {
      |       ^~~~
INFO: Elapsed time: 29.134s, Critical Path: 17.36s
INFO: 442 processes: 259 internal, 183 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by feranick** [comment] 2024-02-21 21:54
This is resolved when setting c++17 as default.:
```
        @@ -37,7 +37,7 @@   @org_tensorflow//tensorflow:workspace0.bzl
 
        load("@coral_crosstool//:configure.bzl", "cc_crosstool")
        cc_crosstool(name = "crosstool", cpp_version = "c++14")  
=>   cc_crosstool(name = "crosstool", cpp_version = "c++17")

```

**Comment by LakshmiKalaKadali** [comment] 2024-02-23 05:26
Hi @feranick,

 As you mentioned, the issue is resolved, could please feel free to close the issue.

Thank You

**Closed** 2024-02-23 05:32 UTC
Labels: stat:awaiting response, type:build/install, comp:lite, subtype: ubuntu/linux, TF 2.15
