### ISSUE TITLE
CUDA 10 Support

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorflow#23219] opened 2018-10-24 18:10 UTC
I am using a containerized env on CentOS with Anaconda, and a RTX 2080 Ti GPU card with 540 Tensor Core Processing Units.

According to the docs: https://www.tensorflow.org/install/gpu
it may not work due to lack of versioning support.

Also - how do I leverage the NVIDIA TPUs/is there support for that?

**Comment by pldelisle** [comment] 2018-10-24 18:46
I'm also interested in this issue. Planning to upgrade my hardware for new RTX boards and CUDA 10. Would like to know if all this works properly and how to use FP16 Tensor core end to end (I know MaxPool3D is only FP32 which is very impactful on performance).

**Comment by joehoeller** [comment] 2018-10-25 12:19
@alanpurple what methods do you use to pipe data to GPU vs TPU?

**Comment by reedwm** [comment] 2018-10-26 00:06
The phrase "TPU" refers to [Google's TPUs](https://cloud.google.com/tpu/). If you are using a GPU, you are not using a TPU, but Volta and Turing GPUs, like the RTX 2080, do have [Tensor Cores](https://www.nvidia.com/en-us/data-center/tensorcore/).

As @alanpurple said, you can use CUDA 10 by building from source, and TensorFlow has full support for Volta's tensor cores. I am not sure if any special support is need for Turing's tensor cores. @jlebar, do you know if anything special is needed for Turing support?

**Comment by jlebar** [comment] 2018-10-26 00:12
Nothing special should be needed for Turing support per se.  TF may have to grow support for int4 and int1 convolutions, I dunno.

**Comment by reedwm** [comment] 2018-10-26 00:16
Ok, it seems this is mostly a duplicate of #22706 then, so I'm closing this issue.

**Closed by reedwm** 2018-10-26 00:16 UTC
Labels: comp:tpus, type:support

**Comment by nlinker** [comment] 2018-10-26 05:31
@alanpurple Could you share a brief instructions how to rebuild TF with Cuda 10 support. Thanks in advance.
