### ISSUE TITLE
Penalty in the contractive auto-encoder

### ISSUE THREAD

**Issue by Ramzi09** [tensorflow/tensorflow#30747] opened 2019-07-16 10:34 UTC
How can I compute a contraction penalty with Tensorflow? The contraction penalty is the squared of Frobenius norm ‖ · ‖F of the Jacobian matrix of the encoder.

**Comment by anush-o** [comment] 2019-07-17 11:47
@Ramzi09 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Ramzi09** [comment] 2019-07-17 14:12
OS: Ubuntu 16.04 (64-bit)
CPU: core i5-3230M CPU 2.60GHZ
RAM: 8Go
TensorFlow 1.10.1 
I did install a binary 
I found the code in Keras. The link is : 
https://wiseodd.github.io/techblog/2016/12/05/contractive-autoencoder/
How can I change in TensorFlow?

**Comment by anush-o** [comment] 2019-07-18 10:11
@Ramzi09 ,
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Ramzi09** [comment] 2019-07-18 10:46
Thanks, I asked this question on StackOverflow, but no answer until now

**Comment by anush-o** [comment] 2019-07-23 09:05
Closing since this is not a bug or feature request.Thanks!

**Closed by anush-o** 2019-07-23 09:05 UTC
Labels: comp:keras, stat:awaiting response, type:support
