### ISSUE TITLE
TF 2.0 Dataset.shuffle() is deterministic

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#31706] opened 2019-08-16 20:54 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tf-nightly-gpu-2.0-preview==2.0.0.dev20190815
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview==2.0.0.dev20190815
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`Dataset.shuffle()` returns results in the same order across invocations and across runs.

**Describe the expected behavior**
Previously, `Dataset.shuffle()` would return randomized results.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

(TF 2.0)
```python
import tensorflow as tf
ds = tf.data.Dataset.from_tensor_slices(list(range(10)))
print([x.numpy() for x in ds])
for i in range(10):
    print([x.numpy() for x in ds.shuffle(10)])
```

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
[1, 9, 0, 7, 2, 3, 8, 5, 6, 4]
```

(TF 1.14)
```python
import tensorflow as tf
tf.enable_eager_execution()
ds = tf.data.Dataset.from_tensor_slices(list(range(10)))
print([x.numpy() for x in ds])
for i in range(10):
    print([x.numpy() for x in ds.shuffle(10)])
```

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 8, 3, 5, 6, 0, 7, 2, 9, 4]
[7, 0, 8, 5, 1, 6, 4, 3, 9, 2]
[4, 5, 3, 0, 7, 1, 2, 6, 9, 8]
[6, 1, 9, 4, 3, 2, 8, 7, 0, 5]
[3, 0, 4, 6, 5, 2, 8, 9, 7, 1]
[5, 9, 3, 4, 0, 6, 7, 1, 2, 8]
[4, 8, 2, 1, 0, 9, 3, 6, 5, 7]
[3, 5, 7, 0, 2, 4, 8, 6, 9, 1]
[8, 0, 6, 2, 7, 3, 4, 5, 9, 1]
[8, 4, 2, 6, 5, 0, 1, 7, 9, 3]
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

cc @martinwicke

**Comment by martinwicke** [comment] 2019-08-16 21:10
@jsimsa This does look problematic. I recall some changes, but maybe those went further than we wanted?

**Comment by jsimsa** [comment] 2019-08-16 21:30
This is working as intended. In TF 2.0, the shuffling order is determined by a resource whose initial state is derived from the random seed.

To retain the TF 1.X behavior, one can do:

```
ds = tf.data.Dataset.from_tensor_slices(list(range(10)))
print([x.numpy() for x in ds])
ds = ds.shuffle(10)
for i in range(10):
  print([x.numpy() for x in ds])
```

This will reuse the state used for determining the shuffle order across epochs (resulting in reshuffling between epochs).

Or, you can change the random seed used for creating the resource that controls the shuffle order:

```
ds = tf.data.Dataset.from_tensor_slices(list(range(10)))
print([x.numpy() for x in ds])
for i in range(10):
  tf.random.set_random_seed(i)
  print([x.numpy() for x in ds.shuffle(10)])
```

**Comment by alsrgv** [comment] 2019-08-16 21:33
@jsimsa, thanks for the quick reply!  Is it expected that random seed is kept the same across process invocations though?

**Comment by jsimsa** [comment] 2019-08-16 23:38
I was wrong. This was not working as intended. I have tracked down the issue and have a pending fix for this, that will be cherry picked into the 2.0 release. After the fix, your original program works the same between TF 1.X and TF 2.0. Thank you for reporting the issue.

**Comment by alsrgv** [comment] 2019-08-16 23:46
@jsimsa, thanks!

**Closed** 2019-08-17 00:54 UTC
Labels: 2.0-rc0, regression issue
