### ISSUE TITLE
Won't build tf r1.12rc2 because of MPI support

### ISSUE THREAD

**Issue by inscite** [tensorflow/tensorflow#23471] opened 2018-11-03 03:03 UTC
**System information**
- OS Platform and Distribution: CentOS Linux release 7.5.1804 (Core)
- TensorFlow installed from (source or binary): source, official release r1.12rc2
- TensorFlow version: r1.12rc2
- Python version: 3.6.6 (anaconda)
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source): 8.2.0 with experimental clang support (of configure),
but also not working on gcc4 (centos7-native), gcc6 (rh-scl-devtoolset-6), gcc7 (rh-scl-devtoolset-7)
- CUDA/cuDNN version: None, integrated nGraph
- GPU model and memory: None, CPU: AMD Ryzen 7 1800X

**Describe the problem**
A released source won't build if I enable MPI support flags while configuring.
Tried multiple gcc versions, however there was no luck.
OpenMPI was also installed from official OMPI src release v3.1.2.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1> Usual ./configure after tarball extract
2> config: Apache Ignite (Y) / XLA JIT (Y) / SYCL (N) / ROCm (N) / CUDA (N) / clang (Y) / MPI (Y) / COPT (-march=native) / Android (N)
3>  bazel --server_javabase=$JAVA_HOME build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=ngraph //tensorflow/tools/pip_package:build_pip_package
4> (optional) if I disable MPI support while ./configure -ing, then tf r1.12rc2 builds successfully.

**Any other info / logs**
_Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached._

[Manual Patch]
I applied this manual fix: [[Pull req #20147](https://github.com/tensorflow/tensorflow/pull/20147/files)] of tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc only.

[Logs]
INFO: From Compiling tensorflow/stream_executor/device_description.cc [for host]:
tensorflow/stream_executor/device_description.cc:148:18: warning: 'DivideCeil' is deprecated: Use MathUtil::CeilOfRatio directly instead. [-Wdeprecated-declarations]
  *block_count = DivideCeil(element_count, *threads_per_block);
                 ^
./tensorflow/stream_executor/device_description.h:362:1: note: 'DivideCeil' has been explicitly marked deprecated here
ABSL_DEPRECATED("Use MathUtil::CeilOfRatio directly instead.")
^
external/com_google_absl/absl/base/macros.h:149:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
1 warning generated.
ERROR: /home/xo/pyenv-ngraph/mpicol/tensorflow-1.12.0-rc2/tensorflow/contrib/mpi_collectives/BUILD:40:1: C++ compilation of rule '//tensorflow/contrib/mpi_collectives:python/ops/_mpi_ops.so' failed (Exit 1)
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:58:6: error: explicit specialization of 'CopyTensorData<Eigen::ThreadPoolDevice>' after instantiation**
void CopyTensorData<CPUDevice>(void* dst, void* src, size_t size) {
     ^
**./tensorflow/contrib/mpi_collectives/kernels/ring.h:165:3:** note: implicit instantiation first required here
  CopyTensorData<Device>((void*)buffer, (void*)input->tensor_data().data(),
  ^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:71:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, int>' after instantiation**
GENERATE_ACCUMULATE(int);
^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8:** note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
**./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5:** note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:72:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, long long>' after instantiation**
GENERATE_ACCUMULATE(long long);
^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8:** note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
**./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5:** note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:73:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, float>' after instantiation**
GENERATE_ACCUMULATE(float);
^
**tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8:** note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
**./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5:** note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
4 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
**INFO:** Elapsed time: 1532.667s, Critical Path: 295.58s
**INFO:** 6912 processes: 6912 local.
**FAILED:** Build did NOT complete successfully

**Comment by byronyi** [comment] 2018-11-03 04:56
Ping @@jthestness

**Comment by jthestness** [comment] 2018-11-03 16:36
Hi guys. I'm afraid we haven't moved beyond TF 1.7 yet, so I haven't encountered these issues myself. However, there might be some things that could help track down the issue:

First, I don't think you should need to manually apply #20147, since it has already been merged. That change was in response to TF changes that moved the namespaces for threading between roughly TF 1.4 and 1.7. Also this summer, TF again changed namespaces (maybe for devices?) in roughly v1.8, and I suspect we will need to make changes analogous to #20147 to find the right includes and get the appropriate device types. (I'm actually surprised that the errors show Eigen::ThreadPoolDevice as the specialization type, since I believe the device specializations should be CPUDevice, GPUDevice, etc. --- that's a big red flag).

If I had time to debug this, I'd start by trying to bisect the builds starting around TF 1.8 and identify the PR that caused MPI collectives to stop building correctly. From there, it should be straightforward to figure out the appropriate includes to get correct device types.

I'd also recommend a quick test to declare the explicit specializations with Eigen::ThreadPoolDevice right after the CopyTensorData and AccumulateTensorData declarations in `mpi_collectives/kernels/ring.h` just to see if that might fix the problem.

**Comment by harshini-gadige** [comment] 2018-11-09 17:18
@inscite  Any update ?

**Comment by inscite** [comment] 2018-11-12 08:42
@harshini-gadige Sorry for late response. Currently, I omitted the MPI support by skipping build flags (not to use distributed tensorflow, for a while.) Moreover, the brand-new release 1.12.0 came out recently; therefore, I have lots of configurations to test.

As @jthestness mentioned about several configurations for baseline, I'll try multiple builds for my desire.
- OS: CentOS 7.5 x86_64
- Host: KVM (due to the lack of physical hosts however it won't give any hardship)
- GCC: 8.2.0 (custom build, since native 4.8.x won't build r1.12.0rc2 in my experience)
- TF: 1.8/1.9/1.10.0/1.11.0/1.12.0

If there are any progresses or unexpected results, I'll leave some comments.
Thx for your consideration.

Regards,
@inscite

**Comment by jthestness** [comment] 2018-11-12 21:44
Hi guys. Just a little update from my side: Although I haven't gotten to the root cause of the problem posted here, I was able to build and run with TF version 1.8.0. There is a small bug that needed to be fixed manually (though it was fixed in TF with #18907, commit 26b2814096bf6d9dd0af91a37a0706e17450b9ec). The patch for that fix is below.

This build indicates that TF 1.8.0 should work for @inscite 's needs with a small change. I will hopefully be able to test newer TF versions this week.

```
diff --git a/tensorflow/contrib/mpi/mpi_utils.h b/tensorflow/contrib/mpi/mpi_utils.h
index df055ff567..4091925fc0 100644
--- a/tensorflow/contrib/mpi/mpi_utils.h
+++ b/tensorflow/contrib/mpi/mpi_utils.h
@@ -22,6 +22,7 @@ limitations under the License.
 #include <string>
 #include <vector>
 
+#include "tensorflow/core/platform/logging.h"
 #include "tensorflow/core/lib/strings/str_util.h"
 
 // Skip MPI C++ bindings support, this matches the usage in other places
```

**Comment by jthestness** [comment] 2018-11-13 20:15
Update: I've been able to build all minor versions of TF up to 1.12.0 (1.8.0, 1.9.0, 1.10.0, 1.11.0 with 89979f42e82, and 1.12.0). They all appear to run a small test correctly. Here's my configuration so you can try to match most of it:
Ubuntu 18.04
GCC 7.3.0
Python 3.6.5
Environment: VirtualEnv
Bazel version: For TF v1.7.0, v1.8.0: 0.10.0. For TF v1.9.0: 0.11.0. For TF v1.10.0, v1.11.0, v1.12.0: 0.15.0 (Following: https://www.tensorflow.org/install/source#tested_source_configurations)
CUDA 9.2.88, cuDNN 7.1.4
Intel CPUs, NVIDIA GPUs

Here are some small caveats worth noting:
TF 1.8.0: Requires a patch with #18907, commit 26b2814
TF 1.9.0: Requires a patch with #20147, commit 1b79572c2d4 (HUGE THANKS TO @yongtang for both of these patches!)
TF 1.11.0 and 1.12.0: Requires that the virtual environment install Keras pip packages, keras_applications and keras_preprocessing (and maybe h5py?), per issue #21518

At this point, the most likely issue in @incite's original post is the Bazel version. I'd try changing that first.

**Comment by harshini-gadige** [comment] 2018-11-13 21:47
@inscite  -  Any update ?

**Comment by inscite** [comment] 2018-11-15 15:51
Greetings!

Here's some progress about tensorflow source build.
I'll update extra progress for multiple releases.

**[Common DevEnv]**
CPU: Intel(R) Xeon(R) Gold 6126 (skylake)
OS: CentOS 7.3.1611
GCC: 8.2.0
OpenMPI: Mellanox HPC-X MPI (v3.0.1a1)
PYENV: Anaconda Virtualenv w/ python 3.6.5
JDK: 11.0.1

**[Bootstrapping]**
Before every bazel build, I did..
```
$ bazel clean --expunge --async
$ bazel shutdown
$ rm -rf <bazel cache>
```

**[r1.12.0]**
* XLA | MPI | MKL optz:
```
$ bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package
```
* NOXLA | MPI | nGraph optz:
```
$ bazel build --config=opt --config=ngraph //tensorflow/tools/pip_package:build_pip_package
```
- bazel 0.15.0 | XLA | MPI | MKL optz: Success
- bazel 0.18.0 | XLA | MPI | MKL optz: Success (bazel version may not an issue)
- bazel 0.18.0 | NOXLA | MPI | nGraph optz: Success (graph compiler may not an issue)

**[r1.11.0]**
* XLA | MPI | MKL optz:
```
$ bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package
# after I met build error,
$ git clone https://github.com/tensorflow/tensorflow.git
$ git checkout 89979f42e827d9eb5c349259a5aa2ec32d38c86a
```
* NOXLA | MPI | nGraph optz:
```
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```
- bazel 0.18.0 | XLA | MPI | MKL optz | no patch 89979f42e827d9eb5c349259a5aa2ec32d38c86a: Fail
- bazel 0.18.0 | XLA | MPI | MKL optz | patch 89979f42e827d9eb5c349259a5aa2ec32d38c86a: Success
- bazel 0.18.0 | NOXLA | MPI | nGraph optz: Fail (however the error is related to nGraph, not a MPI)

One suspicious log I found is related to bazel warning:
```
WARNING: Output base '/home/xo/.cache/bazel/_bazel_xo/385bf1ed0f5ed6366bd1e06f79b126ed' is on NFS. This may lead to surprising failures and undetermined behavior.
```
Actually, I moved 'base source build partition' from NFS to Lustre (there are no local storage) since I experienced multiple errors while building several applications with gcc.
Does it cause any errors while building tensorflow? I still have no idea.

**[Conclusion]**
I also succeed to build TF r1.11.0/1.12.0 with minimal revision.
Since there are a couple of new stable releases, I'll only stick with r1.11.0, r1.12.0.
Still, for backup usage, I'll test for MPI support.
Thank you for your support: @jthestness @harshini-gadige @byronyi @yongtang 

May I close the issue?

**Comment by yongtang** [comment] 2018-11-18 01:32
@inscite Thanks for the investigation! It looks like the issue could be closed, but feel free to reopen if the issue remains.

**Closed by yongtang** 2018-11-18 01:32 UTC
Labels: type:build/install

**Comment by rvallari1** [comment] 2019-08-16 06:40
Hey, I am using tf1.14 with Intel MKL dependency [gcc 7.4.0; Machine: Sky Lake-E ;bazel:0.26.1] and the problem persists :

ERROR: /home/vallari/tensorflow-master/tensorflow/contrib/mpi_collectives/BUILD:40:1: C++ compilation of rule '//tensorflow/contrib/mpi_collectives:python/ops/_mpi_ops.so' failed (Exit 1)
tensorflow/contrib/mpi_collectives/kernels/ring.cc:58:6: error: explicit specialization of 'CopyTensorData<Eigen::ThreadPoolDevice>' after instantiation
void CopyTensorData<CPUDevice>(void* dst, void* src, size_t size) {
     ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:165:3: note: implicit instantiation first required here
  CopyTensorData<Device>((void*)buffer, (void*)input->tensor_data().data(),
  ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:71:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, int>' after instantiation
GENERATE_ACCUMULATE(int);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:72:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, long long>' after instantiation
GENERATE_ACCUMULATE(long long);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:73:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, float>' after instantiation
GENERATE_ACCUMULATE(float);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
4 errors generated.

**Comment by inscite** [comment] 2019-08-20 06:36
Greetings @rvallari1,

It seems like your situation is quite far from the initial problem of this issue.
Still, I can confirm that tensorflow r1.14 source build with MKL/MPI support have an ISSUE.

This issue can be fixed with two file patch. (Thanks to [17437#issuecomment-372552174)](https://github.com/tensorflow/tensorflow/issues/17437#issuecomment-372552174)
The patch below contains an additional fix (since r1.14 have a different configuration from r1.10)

diff -r tensorflow-1.14.0-org/tensorflow/contrib/mpi_collectives/BUILD tensorflow-1.14.0/tensorflow/contrib/mpi_collectives/BUILD
55a56
>         "//tensorflow/stream_executor",
diff -r tensorflow-1.14.0-org/tensorflow/tensorflow.bzl tensorflow-1.14.0/tensorflow/tensorflow.bzl
1773c1773
<             clean_dep("//tensorflow/core:lib"),
---
>             # clean_dep("//tensorflow/core:lib"),

INFO: Elapsed time: 8634.383s, Critical Path: 346.61s
INFO: 12862 processes: 12862 local.
INFO: Build completed successfully, 13719 total actions

As a result, this build ends in success, finally.
I had not built the package as whl yet, but you can try.

Furthermore...
1. DO NOT FORGET to include mpi directory in LD_LIBRARY_PATH or ldconfig.
The easiest way to check this configuration actually visible while executing './configure'.
If the library path of OMPI set correctly, the configuration process get path automatically.
If not, then you have to make sure the right environmental setup.
2. Whenever you initiate new build, please clean-up previous bazelrc configuration.
Try 'bazel clean --expunge --async' and 'rm -f .tf_configure.bazelrc' if exists.

Good luck!

Tested environment:
OS: CentOS 7.6 x86_64
GCC: 7.4.0 with manual source build
OpenMPI: 3.1.4 with manual source build

**Comment by inscite** [comment] 2019-08-20 06:38
Greetings @rvallari1,

It seems like your situation is quite far from the initial problem of this issue.
Still, I can confirm that tensorflow r1.14 source build with MKL/MPI support have an ISSUE.

This issue can be fixed with two file patch. (Thanks to [17437#issuecomment-372552174)](https://github.com/tensorflow/tensorflow/issues/17437#issuecomment-372552174)
The patch below contains an additional fix (since r1.14 have a different configuration from r1.10)

>diff -r tensorflow-1.14.0-org/tensorflow/contrib/mpi_collectives/BUILD tensorflow-1.14.0/tensorflow/contrib/mpi_collectives/BUILD
>55a56
>         "//tensorflow/stream_executor",
>diff -r tensorflow-1.14.0-org/tensorflow/tensorflow.bzl tensorflow-1.14.0/tensorflow/tensorflow.bzl
>1773c1773
><             clean_dep("//tensorflow/core:lib"),
>---
>             # clean_dep("//tensorflow/core:lib"),

INFO: Elapsed time: 8634.383s, Critical Path: 346.61s
INFO: 12862 processes: 12862 local.
INFO: Build completed successfully, 13719 total actions

As a result, this build ends in success, finally.
I had not built the package as whl yet, but you can try.

Furthermore...
1. DO NOT FORGET to include mpi directory in LD_LIBRARY_PATH or ldconfig.
The easiest way to check this configuration actually visible while executing './configure'.
If the library path of OMPI set correctly, the configuration process get path automatically.
If not, then you have to make sure the right environmental setup.
2. Whenever you initiate new build, please clean-up previous bazelrc configuration.
Try 'bazel clean --expunge --async' and 'rm -f .tf_configure.bazelrc' if exists.

Good luck!

Tested environment:
OS: CentOS 7.6 x86_64
GCC: 7.4.0 with manual source build
OpenMPI: 3.1.4 with manual source build

**Comment by inscite** [comment] 2019-08-20 06:41
Greetings @rvallari1,

It seems like your situation is quite far from the initial problem of this issue.
Still, I can confirm that tensorflow r1.14 source build with MKL/MPI support have an ISSUE.

This issue can be fixed with two file patch. (Thanks to [17437#issuecomment-372552174)](https://github.com/tensorflow/tensorflow/issues/17437#issuecomment-372552174)
The patch below contains an additional fix (since r1.14 have a different configuration from r1.10)

```
diff -r tensorflow-1.14.0-org/tensorflow/contrib/mpi_collectives/BUILD tensorflow-1.14.0/tensorflow/contrib/mpi_collectives/BUILD
55a56
>         "//tensorflow/stream_executor",
diff -r tensorflow-1.14.0-org/tensorflow/tensorflow.bzl tensorflow-1.14.0/tensorflow/tensorflow.bzl
1773c1773
<             clean_dep("//tensorflow/core:lib"),
---
>             # clean_dep("//tensorflow/core:lib"),
```

```
INFO: Elapsed time: 8634.383s, Critical Path: 346.61s
INFO: 12862 processes: 12862 local.
INFO: Build completed successfully, 13719 total actions
```

As a result, this build ends in success, finally.
I had not built the package as whl yet, but you can try.

Furthermore...
1. DO NOT FORGET to include mpi directory in LD_LIBRARY_PATH or ldconfig.
The easiest way to check this configuration actually visible while executing './configure'.
If the library path of OMPI set correctly, the configuration process get path automatically.
If not, then you have to make sure the right environmental setup.
2. Whenever you initiate new build, please clean-up previous bazelrc configuration.
Try 'bazel clean --expunge --async' and 'rm -f .tf_configure.bazelrc' if exists.

Good luck!

Tested environment:
OS: CentOS 7.6 x86_64
GCC: 7.4.0 with manual source build
OpenMPI: 3.1.4 with manual source build

**Comment by rvallari1** [comment] 2019-08-21 05:00
@inscite the problem persists. used bazel clean --expunge --async' and 'rm -f .tf_configure.bazelrc..
put all the paths in library and editted the code as per you suggested.
gcc: 7.4.0
OpenMPI: 4.0.1

**Comment by rvallari1** [comment] 2019-08-22 10:33
Also, I am able to build tf1.12 with mkl support from source , but I require an updated version of tf[1.13.1 or higher]..

**Comment by inscite** [comment] 2019-08-22 12:32
@rvallari1 May I request the error log you have seen? Is it same with your previous log?
Meanwhile, how about the MPI directory lookup while tensorflow setup configuration?
Below is an example of my previous configuration output.
See and check if there exist any differences.

```
$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Please specify the location of python. [Default is /home/<user>/miniconda3/envs/tf1140mklmpi/bin/python]:


Found possible Python library paths:
  /home/<user>/miniconda3/envs/tf1140mklmpi/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/<user>/miniconda3/envs/tf1140mklmpi/lib/python3.6/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]:
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]:
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]:
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: y
MPI support will be enabled for TensorFlow.

Please specify the MPI toolkit folder. [Default is ]: /home/<user>/opt/openmpi-3.1.4
(Comment: In my case, This directory does not show automatically in wrong case.
Otherwise, try fill your OpenMPI path.)

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apache Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

$ bazel --server_javabase=$JAVA_HOME build --copt="-DEIGEN_USE_VML" --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

**Comment by rvallari1** [comment] 2019-08-22 13:40
COMMAND: 
bazel build --config=mkl -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512er //tensorflow/tools/pip_package:build_pip_package 


ERROR:
ERROR: /home/vallari/tensorflow-master/tensorflow/contrib/mpi_collectives/BUILD:40:1: C++ compilation of rule '//tensorflow/contrib/mpi_collectives:python/ops/_mpi_ops.so' failed (Exit 1)
tensorflow/contrib/mpi_collectives/kernels/ring.cc:58:6: error: explicit specialization of 'CopyTensorData<Eigen::ThreadPoolDevice>' after instantiation
void CopyTensorData<CPUDevice>(void* dst, void* src, size_t size) {
     ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:165:3: note: implicit instantiation first required here
  CopyTensorData<Device>((void*)buffer, (void*)input->tensor_data().data(),
  ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:71:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, int>' after instantiation
GENERATE_ACCUMULATE(int);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:72:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, long long>' after instantiation
GENERATE_ACCUMULATE(long long);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:73:1: error: explicit specialization of 'AccumulateTensorData<Eigen::ThreadPoolDevice, float>' after instantiation
GENERATE_ACCUMULATE(float);
^
tensorflow/contrib/mpi_collectives/kernels/ring.cc:65:8: note: expanded from macro 'GENERATE_ACCUMULATE'
  void AccumulateTensorData<CPUDevice, type>(type * dst, type * src, \
       ^
./tensorflow/contrib/mpi_collectives/kernels/ring.h:221:5: note: implicit instantiation first required here
    AccumulateTensorData<Device, T>(segment_update, segment_recv,
    ^
4 errors generated.

**Comment by inscite** [comment] 2019-08-28 23:31
Dear @rvallari1,
how's going with your issue?
Based on my survey, I would like to ask you some questions.

- Are you going to build your own tensorflow with Intel Parallel Studio XE?
- (If so, ) Do you have a separate installation of anaconda or miniconda?
- (If not, ) Do you really have an installation of OpenMPI?
