### ISSUE TITLE
Java API does not include quantize operations

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#10829] opened 2017-06-19 17:40 UTC
When trying to run a quantized model with the Tensorflow Java API in version 1.2-rc0, I get the following exception in Java:

```
java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: encoder/encoder_layer_0/Conv2D_eightbit_quantize_normalize/sub = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST"](normalize/sub, encoder/encoder_layer_0/Conv2D_eightbit_min_normalize/sub, encoder/encoder_layer_0/Conv2D_eightbit_max_normalize/sub)]]

	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:295)
	at org.tensorflow.Session$Runner.run(Session.java:245)
	...
```

It seams the kernels for quantized graphs are not included in the Java API binary of tensorflow. Can you add these kernels?

Note: The frozen model I used to create the quantized model runs perfect with the same code.
Note2: I quantized the graph with the current r1.2 branch of tensorflow.

**Comment by aselle** [comment] 2017-06-19 17:54
@asimshankar, could you comment?

**Comment by asimshankar** [comment] 2017-06-19 22:43
@andreas-eberle : The `QuantizeV2` op should be linked in with the Java JNI distribution. Is it possible that you're somehow using an older version of the TensorFlow Java native library?

To validate and simulate the environment you're in, I tried the following:

1. Construct a graph in Python

```python
import tensorflow as tf

x = tf.placeholder(tf.float32, name='input')
q, mn, mx = tf.quantize_v2(x, 0., 100., tf.quint8)
y = tf.dequantize(q, mn, mx, name='output')
with open('/tmp/graph.pb', 'w') as f:
  f.write(tf.get_default_graph().as_graph_def().SerializeToString())
```

2. Load and execute this graph in a Java program:

```java
import org.tensorflow.*;
import java.nio.file.Files;
import java.nio.file.Paths;

public class HelloTF {
  public static void main(String[] args) throws Exception {
    try (Graph g = new Graph()) {
      g.importGraphDef(Files.readAllBytes(Paths.get("/tmp/graph.pb")), "");
      try (Session s = new Session(g);
          Tensor input = Tensor.create(50.0f);
          Tensor output = s.runner().feed("input", input).fetch("output").run().get(0)) {
        System.out.println(output.floatValue());
        System.out.println("TensorFlow Version: " + TensorFlow.version());
      }
    }
  }
}
```

Executing the Java program seemed to work out fine, executing the quantize and dequantize operations and printing:

```
50.19608
TensorFlow Version: 1.2.0
```

Could you try the same in your setup? If you get the same error as you do now, is there some instructions to reproduce that you can share?

Thanks!

**Comment by asimshankar** [comment] 2017-07-12 04:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2017-07-12 04:46 UTC
Labels: stat:awaiting response, type:bug/performance
