### ISSUE TITLE
RandomUniform

### ISSUE THREAD

**Issue by cicido** [tensorflow/tensorflow#26137] opened 2019-02-26 13:28 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, DEPTHWISE_CONV_2D, DIV, FLOOR, FULLY_CONNECTED, MAX_POOL_2D, MUL, RESHAPE, SHAPE, SUB. Here is a list of operators for which you will need custom implementations: RandomUniform

**Comment by jvishnuvardhan** [comment] 2019-02-27 00:14
@cicido 
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-07 00:59
I think it was resolved. I am closing the issue. Please open a new ticket when new information is available. Thanks!

**Closed by jvishnuvardhan** 2019-03-07 00:59 UTC
Labels: comp:lite, stat:awaiting response
