### ISSUE TITLE
tf.keras.preprocessing.image_dataset_from_directory doesn't work on TPU

### ISSUE THREAD

**Issue by mjang2000** [tensorflow/tensorflow#42010] opened 2020-08-03 18:20 UTC
**System information**
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.6
- TPU model and memory: TPU v3-8 (Kaggle default)

**Describe the current behavior**
`tf.keras.preprocessing.image_dataset_from_directory` doesn't work on TPU.

Error message:
`InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=TensorSliceDataset; signature=components: -> handle:variant; attr=Toutput_types:list(type),min=1; attr=output_shapes:list(shape),min=1; is_stateful=true>; NodeDef: {{node TensorSliceDataset}} [Op:MapDataset]`

**Comment by Saduf2019** [comment] 2020-08-04 07:40
@mjang2000 
I ran the code shared it is working as expected on tf 2.3, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/617a402fc005658237a2ce10695d167d/untitled312.ipynb) for the same.
I see there is a spelling mistake in the code shared, `"image_dataseet_from_directory" should be "set"`, please make the correction and let us know.

**Comment by mjang2000** [comment] 2020-08-04 21:36
This is the error message I get while running on a Kaggle kernel. The code can be found [here](https://www.kaggle.com/amyjang/alzheimer-mri-model-tensorflow-2-3-data-loading). Please note that this notebook viewers shows the run on GPU so it does not show this error. When the accelerator is changed to TPU, the following error pops up.
![image](https://user-images.githubusercontent.com/43710235/89347428-99469b80-d65f-11ea-9a0f-72553cdc6fdd.png)

**Comment by Saduf2019** [comment] 2020-08-05 11:08
@mjang2000 
i ran the code shared by you on tpu in the issue template as well, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ef719fa6e56583d65fd15c83dd2b4cd6/untitled319.ipynb). please let me know if i am doing something incorrect.

**Comment by mjang2000** [comment] 2020-08-06 16:22
The gist doesn't seem to run the method or load in images from a directory. I've attached the run on a TPU [here](https://www.kaggle.com/amyjang/bug-testing?scriptVersionId=40276706).

**Comment by haowang-ms89** [comment] 2020-08-20 09:21
I am using TPU on Google Colab Pro. Just want to add that tf.keras.preprocessing.image_dataset_from_directory produce another kind of error message when using TPU:
NotImplementedError: unable to open file: _gcs_config_ops.so, from paths: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so']
caused by: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb']

**Comment by jvishnuvardhan** [comment] 2020-08-20 16:35
@haowang-ms89 Can you please provide a standalone code to reproduce the issue? Thanks!

**Comment by haowang-ms89** [comment] 2020-08-20 17:15
@jvishnuvardhan Sorry, I just figured out that this is caused by tensorflow 2.4.0-dev. When I switch to 2.3.0, the function works. So I think it is a tensorflow dev version issue. The code:
`data_dir_train = pathlib.Path('./train')`
`train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  data_dir_train,
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size,
  label_mode="categorical")`
(One thing to complain is that one can't switch freely. To use 2.3.0, I can't choose TPU and Large RAM in Colab)

**Comment by nikitamaia** [comment] 2020-08-21 00:50
Hi @mjang2000, I believe the error message you are seeing has to do with a version mismatch, as noted in [this comment here](https://github.com/tensorflow/tensorflow/issues/40622#issuecomment-654488935).

@haowang-ms89, Unfortunately I don't think that `image_dataset_from_directory` accepts a GCS bucket. I just tried it out and am unable to get it to work.

**Comment by nikitamaia** [comment] 2020-08-31 17:16
Closing this issue now since it seems to be due to the Kaggle kernel and not `tf.keras`

**Closed by nikitamaia** 2020-08-31 17:16 UTC
Labels: TF 2.2, comp:tpus, stat:awaiting response, type:support
