### ISSUE TITLE
TensorFlow 2.0 Unknown entries in loss dictionary when recovering saved model with tf.keras.models.load_model

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#35750] opened 2020-01-10 19:20 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): based on an official example, but modified
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): docker image `tensorflow/tensorflow:2.0.0-gpu-py3-jupyter`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a `tf.keras` model initialized via the "functional" API, e.g.

```python
input = tf.keras.Input(...)
y = tf.keras.layers.Dense(...)(input)
...
logits = tf.keras.layers.Dense(..., name="logit_layer")(y)

model = tf.keras.models.Model(inputs, logits)
```

I then compile it with a custom loss:

```python
def my_loss(labels, logits):
    # here just wrapping a known loss to remove errors that could come from me
    # however there may be additional functionality here
    loss = tf.nn.softmax_cross_entropy_with_logits(
        labels=labels,
        logits=logits
    )
    return loss

model.compile(
    ...,
    loss ={
        'logit_layer': my_loss
    },
)

```

I then proceed to train this model with `ModelCheckpoint` callbacks, and after training save it in a myriad of ways:

```python
model.save(...)
tf.keras.experimental.export_saved_model(model, ...)
tf.keras.models.save_model(model, ...)
model.save_weights(...)
```

Now I try to load my saved model:

```
custom = {
    'my_loss': my_loss
}
model_file = # one of the files from above
model = tf.keras.models.load_model(model_file, custom)
```

Each and every one of these models gives me the following error:

```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-52082d68b682> in <module>
      1 model_file = os.path.join(model_to_use)
----> 2 model = tf.keras.models.load_model(model_file, custom)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    145   if isinstance(filepath, six.string_types):
    146     loader_impl.parse_saved_model(filepath)
--> 147     return saved_model_load.load(filepath, compile)
    148 
    149   raise IOError(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/load.py in load(path, compile)
     91     if model._training_config is not None:  # pylint: disable=protected-access
     92       model.compile(**saving_utils.compile_args_from_training_config(
---> 93           model._training_config))  # pylint: disable=protected-access
     94 
     95   return model

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    334     # Prepare list of loss functions, same size of model outputs.
    335     self.loss_functions = training_utils.prepare_loss_functions(
--> 336         self.loss, self.output_names)
    337 
    338     target_tensors = self._process_target_tensor_for_compile(target_tensors)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_utils.py in prepare_loss_functions(loss, output_names)
   1337   """
   1338   if isinstance(loss, collections_abc.Mapping):
-> 1339     generic_utils.check_for_unexpected_keys('loss', loss, output_names)
   1340     loss_functions = []
   1341     for name in output_names:

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py in check_for_unexpected_keys(name, input_dict, expected_values)
    589     raise ValueError('Unknown entries in {} dictionary: {}. Only expected '
    590                      'following keys: {}'.format(name, list(unknown),
--> 591                                                  expected_values))
    592 
    593 

ValueError: Unknown entries in loss dictionary: ['logit_layer']. Only expected following keys: ['output_1']
```

I have found several github issues related to this:

1. https://github.com/qqwweee/keras-yolo3/issues/481
2. https://github.com/tensorflow/tensorflow/issues/28059
3. https://github.com/tensorflow/tensorflow/issues/25938

The second issue claims to be duplicate of the third and seems different from what I do above.
The first issue, uses an actual layer to be the loss, and passes a permissive lambda function as the loss:

```python
lambda y_pred, y_true: y_pred
``` 
This does not seem the same as what I am doing.

**Describe the expected behavior**
That providing the `customs` object is sufficient. 

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

A MWE can be found here: https://gitlab.com/SumNeuron/neumf
Clone it then run
```
python docker.py -w ai -c build
python docker.py -w ai -c up
```

The notebook to run is: https://gitlab.com/SumNeuron/neumf/blob/master/notebooks/NeuMF.ipynb

This is based off of the official recommendations model

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment] 2020-01-15 00:30
@SumNeuron Can you please provide simple standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-24 00:26
@SumNeuron Can you please provide simple standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-27 22:58
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-01-27 22:58 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by Lu1352** [comment] 2020-06-11 02:05
i meet same issue too

**Comment by jvishnuvardhan** [comment] 2020-06-11 22:40
@Lu1352 Can you please open a new issue with a simple standalone code to reproduce the error? Thanks!
