### ISSUE TITLE
tflite_convert deletes (almost) all nodes and edges, .pb to .tflite, 585929kb to 1kb

### ISSUE THREAD

**Issue by st170911** [tensorflow/tensorflow#35986] opened 2020-01-17 12:56 UTC
Hello,
I'm having problems with conversion from frozen graph (.pb) to tflite, using tflite_convert.
It does safe a .tflite file, but it's only got a size of 1kb.
Apparently it gets rid of almost every node and all edges.
Can anybody give me advice on how to do it without losing all the information or what I'm doing wrong?
Best regards

**System information**
Windows 10
Tensorflow Version 1.14.0 obtained via pip

**Command used to run the converter or code if you’re using the Python API**

```
tflite_convert --graph_def_file=categorical_model.pb --output_file=optimized_graph.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=1,224,224,3 --input_array=input_1 --output_array=training/SGD/Variable_215
```

**The output from the converter invocation**

```
2020-01-17 12:22:40.734881: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
2020-01-17 12:22:51.425546: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-01-17 12:22:51.432588: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2020-01-17 12:23:42.194315: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2020-01-17 12:23:42.199502: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 2 nodes (-1929), 0 edges (-2004), time = 45374.7031ms.
```

**Failure details**
Original file (categorical_model.pb) has got 585 929kb, output file (optimized_graph.tflite) has only got 1kb.

**Comment by jvishnuvardhan** [comment] 2020-01-21 22:27
@st170911 Can you please create a simple standalone code to reproduce the issue? Please share the model *.pb. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-01-27 22:57
@st170911 Can you please create a simple standalone code to reproduce the issue? Please share the model *.pb. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-02-02 00:22
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-02-02 00:22 UTC
Labels: TF 1.14, comp:lite, stat:awaiting response, type:bug
