### ISSUE TITLE
Questions regarding tensorflow code (trying to learn and understand)

### ISSUE THREAD

**Issue by ion-elgreco** [tensorflow/tensorflow#44808] opened 2020-11-12 16:56 UTC
Hi everyone,

Sorry if this is not the right place, if it's not please remove.

But I have some questions regarding the source code of TensorFlow. I am trying to get a better understanding of the way TF is build up.

- What is the difference between `@keras_export('keras.layers.LSTMCell', v1=[]) `and `@keras_export(v1=['keras.layers.LSTMCell'])`. In the second on it's pointing to version 1, so if you using v1 of keras you will use that class?

- I am also curious about what the best way is to import things from tensorflow. I want to import stuff from the `tensorflow.python.keras.layers.recurrent` I need to import for example `ops, tensor_shape`, but these functions are imported in this recurrent.py file: `from tensorflow.python.framework import ops`, and `from tensorflow.python.framework import tensor_shape`. So what is the best approach, import them straight from the corresponding locations, so `tensorflow.python.framework`, or just import them from `tensorflow.python.keras.layers.recurrent`? 

Importing them from `tensorflow.python.keras.layers.recurrent` really simplifies the code, because you are importing it from one location, but I do not know what the standard approach is.

**Comment by Saduf2019** [comment] 2020-11-13 15:25
@ion-elgreco 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ion-elgreco** [comment] 2020-11-13 15:27
> @ion-elgreco
> This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Alright! Thank you!

**Comment by Saduf2019** [comment] 2020-11-13 17:15
moving this to closed status with confirmation.

**Closed** 2020-11-13 17:15 UTC
Labels: comp:keras, stat:awaiting response, type:others
