### ISSUE TITLE
tensorflow r1.10  gpu slow when createDevices

### ISSUE THREAD

**Issue by AnberLu** [tensorflow/tensorflow#31233] opened 2019-08-01 11:31 UTC
when i run tensorflowr1.10 in gpu , i found createDevice is slow . and Pause 4 minutes .

problem:
```
2019-07-31 23:15:38.412176: I server.cpp:152] Starting the server
2019-07-31 23:19:23.888051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966  Device interconnect StreamExecutor with stiength 1 edge matrix
```

code
```
bool CreateSessionFromGraph(
        const string& graph,
        std::unique_ptr<tensorflow::Session>& session) {
      tensorflow::GraphDef graph_def;
      Status status = ReadBinaryProto(tensorflow::Env::Default(),
          graph, &graph_def);
      LOG(INFO) << "load " << graph;
      if (!status.ok()) {
        LOG(FATAL) << "Failed to load: " << graph;
        return false;
      }
      tensorflow::SessionOptions options;
      options.config.set_allow_soft_placement(true);
      options.config.mutable_gpu_options()->set_per_process_gpu_memory_fraction(0.5);
      options.config.mutable_gpu_options()->set_allow_growth(true);
      options.config.set_intra_op_parallelism_threads(0);
      options.config.set_inter_op_parallelism_threads(0);
      session.reset(tensorflow::NewSession(options));
      status = session->Create(graph_def);
      if (!status.ok()) {
        LOG(FATAL) << "Failed to create session.";
        return false;
      }
      return true;
    }

    TFModel::TFModel(
        const Device& device,
        const string& graph): device_(device), graph_(graph){
      CreateSessionFromGraph(graph_, session_);
    }

    TFModel::~TFModel() {
      session_->Close();
    }
```

env:
```

$ nvidia-smi 
Thu Aug  1 19:03:57 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:0D:00.0 Off |                    0 |
| N/A   34C    P0    39W / 250W |   5136MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 

$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

**Comment by anush-o** [comment] 2019-08-02 08:34
@AnberLu ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by oanush** [comment] 2019-08-09 09:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-09 09:21 UTC
Labels: comp:gpu, stat:awaiting response, type:support
