### ISSUE TITLE
SpatialConvolution in tflite is very slow

### ISSUE THREAD

**Issue by lucaswu** [tensorflow/tensorflow#16497] opened 2018-01-27 15:24 UTC
Hi, i build tflite ,using bazel build --cxxopt='--std=c++11' //tensorflow/contrib/lite/java:tensorflowlite 
--crosstool_top=//external:android/crosstool \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--cpu=armeabi-v7a
I test my CNN model, but it's very slow in google piexl. I analyze time cost of my CNN model. SpatialConvolution function is very slow, only 20%  of the peak flops of my hardware.
my model's data type is kTfLiteFloat32. 
Is build script for android right ？I doubt my build script is wrong , so run the SpatialConvolution function with ARM NEON.  (I don't know how Eigen is organized in tflite, i can't add log code in the source code to prove my suspicion)

**Comment by petewarden** [comment] 2018-01-31 20:16
Can you try a few things to help us get more information:

 - Is your model slow when run in Android on regular TensorFlow (not TF Lite)?

 - If it is, can you run the steps described [here](https://www.tensorflow.org/mobile/optimizing) in "Profiling your model" and add the log output?

**Comment by tensorflowbutler** [comment] 2018-02-15 13:13
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:47
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-17 14:53
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-01 12:33
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ianholing** [comment] 2018-04-11 15:43
Hey! 
Something similar happens to me recently with a really simple convolutional encoder. The ".tflite" file exported with this:
https://colab.research.google.com/drive/1KMQQjuSfurog3n-Ut7BMSfv1TXGFonbX#scrollTo=WZlb35eHCchl

And executed with "implementation 'org.tensorflow:tensorflow-lite:+'" in Android was almost twice slow than the exported as a usual ".pb" and executed with "implementation 'org.tensorflow:tensorflow-android:+'" in Android.

**Comment by tensorflowbutler** [comment] 2018-04-26 18:51
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-11 18:48
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:03
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:51
Nagging Assignee @petewarden: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging Assignee @petewarden: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging Assignee @petewarden: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anitha-v** [comment] 2018-07-12 22:42
Closing this one, since original poster did not clarify and provide reproducible test cases.

@ianholing :  Please create a new bug with reproducible tests

**Closed by anitha-v** 2018-07-12 22:42 UTC
Labels: comp:lite
