### ISSUE TITLE
Bug in tf,keras.layers.Conv2D when use dilation_rate

### ISSUE THREAD

**Issue by xiaohu2015** [tensorflow/tensorflow#28788] opened 2019-05-17 04:54 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

```python
import tensorflow as tf # TF2

class Conv2D_BN_ReLU(tf.keras.Model):
    """Conv2D + BN + ReLU"""
    def __init__(self,
            filters,
            kernel_size,
            strides=1,
            padding="SAME",
            dilation_rate=1,
            use_bias=False,
            kernel_initializer="he_normal",
            kernel_regularizer=None,
            **bn_params):
        super(Conv2D_BN_ReLU, self).__init__()

        self.conv = tf.keras.layers.Conv2D(filters, kernel_size, strides=strides,
                padding=padding, dilation_rate=dilation_rate, use_bias=use_bias,
                kernel_initializer=kernel_initializer, kernel_regularizer=kernel_regularizer)
        self.bn = tf.keras.layers.BatchNormalization(**bn_params)

    def call(self, x, training=None):
        x = self.conv(x)
        x = tf.nn.relu(self.bn(x, training=training))
        return x

if __name__ == "__main__":
    import os
    os.environ["CUDA_VISIBLE_DEVICES"] = "6"

    net = Conv2D_BN_ReLU(64, 1, 1, dilation_rate=6)
    x = tf.ones((1, 32, 32, 64))
    y = net(x)

    x = tf.ones((1, 64, 64, 64))
    y = net(x)
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=68 is not divisible by block_shape[0]=6 [Op:SpaceToBatchND]

**Describe the expected behavior**

I think the second evaluation should also work, because I use padding="SAME"

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment] 2019-05-17 07:56
@xiaohu2015 Able to reproduce the issue with the provided code.
InvalidArgumentError: padded_shape[0]=68 is not divisible by block_shape[0]=6 [Op:SpaceToBatchND]

**Comment by xiaohu2015** [comment] 2019-05-17 09:09
@muddham @jvishnuvardhan I think the padding="SAME" not work with expectation, it is really a big trouble. The reason behind this, I think it is "deferring weight creation until the shape of the inputs is known" :
```
class Linear(layers.Layer):

  def __init__(self, units=32):
    super(Linear, self).__init__()
    self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(shape=(input_shape[-1], self.units),
                             initializer='random_normal',
                             trainable=True)
    self.b = self.add_weight(shape=(self.units,),
                             initializer='random_normal',
                             trainable=True)

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b
```
The __call__ method of your layer will automatically run build the first time it is called. You now have a layer that's lazy and easy to use.

but for different input shape, maybe the configuration of the first call is improper

**Comment by ppwwyyxx** [comment] 2019-05-19 05:13
Looks like the same bug I reported 2 months ago: https://github.com/tensorflow/tensorflow/issues/26797
I've already switched to my own implementation of dilated conv https://github.com/tensorpack/tensorpack/commit/353cd04fe81ea8920bc67f702bf492174b000768 since they are slow at fixing bugs.

**Comment by xiaohu2015** [comment] 2019-06-04 07:20
@jvishnuvardhan something update???

**Comment by yuanzhedong** [comment] 2019-10-16 23:19
having the same issue, can't train with data that have various lengths...

**Comment by yhliang2018** [comment] 2019-10-25 21:22
Thanks for reporting the issue! We have a fix for the issue. Can you run your code with tf-nightly to verify it? Let us know if the issue still exists.

**Comment by yhliang2018** [comment] 2019-11-08 18:25
Close the issue for now as the fix has been submitted.

**Closed by yhliang2018** 2019-11-08 18:25 UTC
Labels: TF 2.0, comp:keras, type:bug

**Comment by yuanzhedong** [comment] 2019-11-08 23:45
Hi @yhliang2018 , thank you for helping with this. We have a question about how to install the tf-nightly you mentioned above. We tried both `pip install tf-nightly-gpu-2.0-preview` and `pip install tf-nightly` but still get that error.

We dig a little bit about why we can't it fails and found that this function [tf.space_to_batch_nd](https://www.tensorflow.org/api_docs/python/tf/space_to_batch_nd) will be called when using dilation conv, which requires the length of the input should be divisible by the dilation rate. TF will calculate the number of padding needed to make it divisible using `tf.required_space_to_batch_paddings` just once based on the first input of the model. However since that calculation only happens once, for the second input with different lengths, TF will still do the same number of padding, which with high chance will cause the length of the input is not divisible by the dilation rate and throw that error.

**Comment by yhliang2018** [comment] 2019-11-09 00:16
Hi @yuanzhedong Yes, you are right. What you descripted was indeed the root cause, and [our fix](https://github.com/tensorflow/tensorflow/blob/7a07f274d65bed12b91b6c6dbe4987a6e1649429/tensorflow/python/keras/layers/convolutional.py#L196) to recreate conv_op when a different input is provided is to resolve this issue. I have verified the code example @xiaohu2015 provided works correctly with tf-nightly [here](https://colab.research.google.com/gist/yhliang2018/ba449f1299ed1476c3ad06560e00f403/verify-github-issue-28788.ipynb). What error do you get for your use case? Could you share a minimal code to reproduce that? Thanks!

**Comment by yuanzhedong** [comment] 2019-11-09 22:58
Thank you for sharing the colab! I find `pip install tf-nightly` installed an older version on my own laptop. Retried on ec2 instance and it correctly installs the same version as yours. The code shared by @xiaohu2015 works now!!

But when I run my training code (which was working with tf version `2.0.0` if I pad all the inputs to the same length) now fails after two epochs with another error pops up:

```
Traceback (most recent call last):
  File "models/ms_tcn/tensorflow/model.py", line 245, in <module>
    app.run(train_ms_tcn)
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/ms_tcn/tensorflow/model.py", line 237, in train_ms_tcn
    tf.TensorSpec(shape=[], dtype=tf.bool, name="training"),
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 909, in save
    meta_graph_def, saveable_view, signatures, options.namespace_whitelist)
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 553, in _fill_meta_graph_\
def
    object_map, resource_map, asset_info = saveable_view.map_resources()
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 280, in map_resources
    capture_constant_value = tensor_util.constant_value(capture)
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 827, in constant_val\
ue
    ret = _ConstantValue(tensor, partial)
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 673, in _ConstantVal\
ue
    if tensor.op.type == "Const":
  File "/home/ubuntu/anaconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 2220, in type
    return c_api.TF_OperationOpType(self._c_op)
AttributeError: 'Operation' object has no attribute '_c_op'

```
Seems not related with this issue anymore? We will keep investigating. 

By the way, do you know when this fix will be officially released?

**Comment by yhliang2018** [comment] 2019-11-11 17:35
The fix should be included in TF 2.1.0. 

Looking at the error message, and looks like it means some non-Eager tensors are accessed outside of tf.function. Not sure if it's caused by this fix. Could you share your code to reproduce this error by opening another issue? I can dig more into it. Thanks!

**Comment by yuanzhedong** [comment] 2019-11-11 18:19
@yhliang2018 thank you for the reply, I pasted the code here: https://colab.research.google.com/gist/yhliang2018/ba449f1299ed1476c3ad06560e00f403/verify-github-issue-28788.ipynb

**Comment by yuanzhedong** [comment] 2019-11-11 18:31
Hi @yhliang2018, somehow when I use `conv1d`, the error still exists, 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=26 is not divisible by block_shape[0]=4 [Op:SpaceToBatchND]
```
the code below  be able to reproduce that error.

```
from absl import app
from absl import flags
import numpy as np
import os


import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import optimizers
from tensorflow.keras import losses
from tensorflow.keras.layers import Layer
from tensorflow.keras.layers import Activation, Lambda, add, Softmax, ReLU, Concatenate
from tensorflow.keras.layers import Conv1D, Dropout, Dense, MaxPooling1D, GlobalAvgPool1D

print(tf.__version__) #2.1.0-dev20191111

def get_gen():
    x_train = [np.ones((1, 16, 1024)),
               np.ones((1, 130, 1024))]
    y_train = np.ones((2, 1))
    while True:
        for i, x in enumerate(x_train):
            print(x.shape)
            yield x, y_train[i]

train_gen = get_gen()

model = tf.keras.models.Sequential()
model.add(Conv1D(32, 3,
                 activation='relu',
                 #input_shape = (None, 1024),                                                                                                          
                 padding = "same",
))

model.add(Conv1D(32, 3,
                 activation='relu',
                 #input_shape = (None, 1024),                                                                                                          
                 padding = "same",
                 dilation_rate=2
))

model.add(Conv1D(2, 1, padding="same"))
model.add(GlobalAvgPool1D())

optimizer = tf.keras.optimizers.Adam(learning_rate=0.00001)

train_epoch_loss = []
for features, labels in train_gen:
    with tf.GradientTape() as tape:
        predictions = model(features, training=True)
        loss = tf.keras.losses.sparse_categorical_crossentropy(labels, predictions)

    grads = tape.gradient(loss, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))

    train_epoch_loss.append(loss.numpy())

    print("Train_Loss_EPOCH:", sum(train_epoch_loss) / len(train_epoch_loss))
```

**Comment by yhliang2018** [comment] 2019-11-12 22:21
@yuanzhedong The issue should be fixed for all conv layers, and I cannot reproduce the error you mentioned by [running your code](https://colab.research.google.com/gist/yhliang2018/7eabaa3a107a063741e552dea3ac234c/verify-github-issue-28788-conv1d.ipynb).

**Comment by yuanzhedong** [comment] 2019-11-13 01:50
> @yuanzhedong The issue should be fixed for all conv layers, and I cannot reproduce the error you mentioned by [running your code](https://colab.research.google.com/gist/yhliang2018/7eabaa3a107a063741e552dea3ac234c/verify-github-issue-28788-conv1d.ipynb).

Interesting...I tried both my local env(ubuntu18.04 + rtx 2080) and ec2 instance(ubuntu16.04 + k80) and the error is still there, I use conda virtual env, not sure if that's the issue

````
conda create -n=tf-nightly python=3.6
conda activate tf-nightly
pip install tf-nightly
# check the tf version is correct but still crash
````

**Comment by yuanzhedong** [comment] 2019-11-13 02:36
Not quite related, but do you know how to set GPU env for codelab? I changed the runtime to be GPU but seems the code is running on CPU?

![Screen Shot 2019-11-12 at 6 27 19 PM](https://user-images.githubusercontent.com/5069709/68728134-43830e00-057b-11ea-802a-b474c826a502.png)

**Comment by yhliang2018** [comment] 2019-11-13 17:39
@yuanzhedong can you open another thread for your second question? This issue has been closed for a while. We try to resolve one issue in one thread, and this will help other people with similar problems. Thanks!

**Comment by yuanzhedong** [comment] 2019-11-13 19:48
Sure, thank you for your help!

**Comment by albenoit** [comment] 2020-05-01 13:12
Hi, unfortunately, it seems that the bug is still not fixed on tf2.1.0.
I obtain the same error as described when using padding='same' with tf.keras.layers.Conv2D with dilation rate=(2,2)

Is there any proper way to fix this ?

**Comment by albenoit** [comment] 2020-05-01 14:17
Hi, the issue is still there on tf 2.1.0, is there any proper way to change the code while still making code upgradable to next version (maintainability is preferred...)?

**Comment by petoor** [comment] 2020-06-06 08:25
@yhliang2018 in tf 2.2 the error is still there. 
This is the output i get when calling a conv2d with dilation=16. Where the input is in parentheses 
```
(6, 12, 16, 256)
Step : 1 - Loss is : 3.9648172855377197
(6, 8, 16, 256)
Step : 2 - Loss is : 3.227323293685913
(6, 20, 16, 256)
Step : 3 - Loss is : 2.098637819290161
(6, 12, 16, 256)
2020-06-06 10:18:51.440173: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=56 is not divisible by block_shape[0]=16

```

**Comment by petoor** [comment] 2020-06-06 08:34
@yhliang2018 in tf 2.2 the error is still there. 
This is the output i get when calling a conv2d with dilation=16. Where the input is in parentheses 
```
(6, 12, 16, 256)
Step : 1 - Loss is : 3.9648172855377197
(6, 8, 16, 256)
Step : 2 - Loss is : 3.227323293685913
(6, 20, 16, 256)
Step : 3 - Loss is : 2.098637819290161
(6, 12, 16, 256)
2020-06-06 10:18:51.440173: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=56 is not divisible by block_shape[0]=16

```

**Comment by 888yyh** [comment] 2021-08-12 08:26
> Hi, the issue is still there on tf 2.1.0, is there any proper way to change the code while still making code upgradable to next version (maintainability is preferred...)?
> Typical error is
> ` File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 917, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper return func(*args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 433, in train_on_batch output_loss_metrics=model._output_loss_metrics) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 312, in train_on_batch output_loss_metrics=output_loss_metrics)) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 253, in _process_single_batch training=training)) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss outs = model(inputs, **kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__ outputs = call_fn(cast_inputs, *args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call convert_kwargs_to_constants=base_layer_utils.call_context().saving) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph output_tensors = layer(computed_tensors, **kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__ outputs = call_fn(cast_inputs, *args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/convolutional.py", line 209, in call outputs = self._convolution_op(inputs, self.kernel) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 1135, in __call__ return self.conv_op(inp, filter) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 640, in __call__ return self.call(inp, filter) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_ops.py", line 616, in _with_space_to_batch_call block_shape=self.dilation_rate) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 3303, in required_space_to_batch_paddings const_block_shape = tensor_util.constant_value(block_shape) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_util.py", line 827, in constant_value ret = _ConstantValue(tensor, partial) File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_util.py", line 673, in _ConstantValue if tensor.op.type == "Const": File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 2220, in type return c_api.TF_OperationOpType(self._c_op) AttributeError: 'Operation' object has no attribute '_c_op'`

dear sir, met the same error, did you solve it?i ran with tf2.1,it still got this error.I changed the input from array to tensor, not working.Could you help me?hope for your reply.
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    imgs_mask_test = model.predict(imagestest, verbose=1)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 85, in distributed_function
    per_replica_function, args=args)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 763, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1819, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2164, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 212, in _predict_on_batch
    result = predict_on_batch(model, x)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 556, in predict_on_batch
    return predict_on_batch_fn(inputs)  # pylint: disable=not-callable
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 209, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1135, in __call__
    return self.conv_op(inp, filter)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 640, in __call__
    return self.call(inp, filter)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 616, in _with_space_to_batch_call
    block_shape=self.dilation_rate)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3303, in required_space_to_batch_paddings
    const_block_shape = tensor_util.constant_value(block_shape)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 827, in constant_value
    ret = _ConstantValue(tensor, partial)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 673, in _ConstantValue
    if tensor.op.type == "Const":
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2220, in type
    return c_api.TF_OperationOpType(self._c_op)
AttributeError: 'Operation' object has no attribute '_c_op'
