### ISSUE TITLE
CMake build fails v1.13.1 fatal error: tensorflow/stream_executor/dnn.pb.h: No such file or directory  #include "tensorflow/stream_executor/dnn.pb.h"

### ISSUE THREAD

**Issue by samhodge** [tensorflow/tensorflow#29042] opened 2019-05-26 19:47 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source 
- TensorFlow version: v1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.25 NA
- GCC/Compiler version (if compiling from source): gcc/4.8.5
- CUDA/cuDNN version: 10.0.130, 7.4.2.24
- GPU model and memory: GTX 1060 6Gb

**Describe the problem**

CMake build doesnt complete

```
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_scope.cc.o
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_op.cc.o
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_show_multi.cc.o
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_show.cc.o
[ 18%] Building CXX object CMakeFiles/tf_stream_executor.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/blas.cc.o
[ 18%] Building CXX object CMakeFiles/tf_stream_executor.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/device_description.cc.o
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_stats.cc.o
[ 18%] Building CXX object CMakeFiles/tf_stream_executor.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/dnn.cc.o
[ 18%] Linking CXX executable proto_text
In file included from /home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/dnn.cc:16:0:
/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/dnn.h:34:47: fatal error: tensorflow/stream_executor/dnn.pb.h: No such file or directory
 #include "tensorflow/stream_executor/dnn.pb.h"
                                               ^
compilation terminated.
[ 18%] Built target proto_text
[ 18%] Building CXX object CMakeFiles/tf_stream_executor.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/dso_loader.cc.o
make[2]: *** [CMakeFiles/tf_stream_executor.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/stream_executor/dnn.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_tensor.cc.o
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_timeline.cc.o
make[1]: *** [CMakeFiles/tf_stream_executor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/internal/tfprof_utils.cc.o
[ 19%] Building CXX object CMakeFiles/tf_core_profiler.dir/home/kognat/dev/tensorflow-v1.13.1-static-gpu-centos6/tensorflow/tensorflow/core/profiler/tfprof_options.cc.o
[ 19%] Built target tf_core_profiler
make: *** [all] Error 2
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**

git checkout https://github.com/tensorflow/tensorflow.git
cd tensorflow/tensorflow/contrib/cmake
mkdir build && cd build
CUDA_HOME=/usr/local/cuda-10.0 cmake3 .. -DCMAKE_PREFIX_PATH=/usr/local/cuda-10.0:/usr/local/cudnn-7.4.2.24/cuda -DCMAKE_INSTALL_PREFIX=/home/samh/opt/tensorflow-v1.13.1-static-gpu -Dtensorflow_BUILD_PYTHON_BINDING=off -Dtensorflow_ENABLE_GPU=on -Dtensorflow_ENABLE_GRPC_SUPPORT=on -Dtensorflow_ENABLE_POSITION_INDEPENDENT_CODE=on -Dtensorflow_ENABLE_SNAPPY_SUPPORT=on -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=on -Dtensorflow_PATH_CUDA_LIB=/usr/local/cuda-10.0/lib -Dtensorflow_PATH_CUDNN_LIB=/usr/local/cudnn-7.4.2.24/cuda/lib  -Dtensorflow_CUDNN_INCLUDE=/usr/local/cudnn-7.4.2.24/cuda/include -Dtensorflow_BUILD_SHARED_LIB=on -Dtensorflow_NCCL_INCLUDE=/usr/local/nccl-2.4.7/include -Dtensorflow_PATH_NCCL_LIB=/usr/local/nccl-2.4.7/lib -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DCUDA_cupti_LIBRARY=/usr/local/cuda-10.0/extras/CUPTI/lib -DOPENSSL_NO_ASM=1
make -j12

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I need a static build with GPU support, any process to do this would be considered an alternative.

Sam

**Comment by muddham** [comment] 2019-05-27 08:30
@samhodge Request you to please follow the [link](https://www.tensorflow.org/install/source#tested_build_configurations), as per this reference it supports Bazel, Please use bazel.

**Comment by samhodge** [comment] 2019-05-27 10:01
I need a static version of the library I will link the reasons why.

**Comment by samhodge** [comment] 2019-05-27 10:05
@muddham 

Using Bazel will produce libtensorflow_cc.so with GPU support which is excellent.

But the product I am writing a plugin for is also using Tensorflow, hence when Tensorflow::Port::init() is called this segfault the parent application.

My current workaround is to statically link tensorflow using contrib/makefile but this doesnt have CUDA support.

contrib/cmake does have CUDA support but doesnt work as detailed in the post above.

I am not running Python I am creating a plugin in C++

see:
https://github.com/tensorflow/tensorflow/issues/22810

Which was put up in September 2018 and is still not solved.

**Comment by muddham** [comment] 2019-05-27 10:19
@samhodge Can you please confirm if this is duplicate of #22810

**Comment by samhodge** [comment] 2019-05-27 10:22
No this file:

https://github.com/tensorflow/tensorflow/commit/219bb5d8dc9d16fa2e9895d8d4c6adaf45ee3c34#diff-39f23d578b0023a4931f812a68725235

Was added in v1.12.1 so the cmake needs to be updated to deal with this change I will see if I can work with v1.12.0

**Comment by samhodge** [comment] 2019-05-27 10:23
No #22810 is the cause of the issue, needing the cmake build to work allows the workaround to #22810 and build a static library.

**Comment by samhodge** [comment] 2019-05-27 10:26
https://github.com/tensorflow/tensorflow/commits/v1.13.1/tensorflow/contrib/cmake has not been updated since December 2018 and the dnn.proto file was added after that time.

**Comment by samhodge** [comment] 2019-05-27 20:56
https://github.com/tensorflow/tensorflow/issues/29042#issuecomment-496163002 In response no it is not a duplicate

**Comment by samhodge** [comment] 2019-05-28 12:12
Building on v1.12.0 was a little better, but my build environment was  gcc 4.4.7 in /usr/bin/gcc and another gcc 4.8.5 in a non standard location on CentOS 6.10

It is demanding CUDA 9.0 although I know the source runs with CUDA 10.0.130

Compiling issues were related to not finding a C++11 compiler.

The same CentOS 6.10 image has been used to compile Tensorflow 1.12.0 with Bazel for CPU, CUDA 9.0 CUDNN 7.3.1 and CUDA 10.0 CUDNN 7.4.24.2

It seems the CMake compiler directive is not passed to sub projects.

I will find the fix for some relocation of files not updated in the .cmake files

**Comment by samhodge** [comment] 2019-05-28 12:16
https://github.com/tensorflow/tensorflow/issues/22634#issuecomment-438616945 Is a link to fixes that need to be made to v1.12.0

**Comment by samhodge** [comment] 2019-05-28 22:03
Here is the latest build command for my machine for v1.12.0

```
CUDA_HOME=/usr/local/cuda-10.0 cmake3 .. -DCMAKE_PREFIX_PATH=/usr/local/cuda-10.0:/usr/local/cudnn-7.4.2.24/cuda -DCMAKE_INSTALL_PREFIX=/home/samh/opt/tensorflow-v1.13.1-static-gpu -Dtensorflow_BUILD_PYTHON_BINDING=off -Dtensorflow_ENABLE_GPU=on -Dtensorflow_ENABLE_GRPC_SUPPORT=on -Dtensorflow_ENABLE_POSITION_INDEPENDENT_CODE=on -Dtensorflow_ENABLE_SNAPPY_SUPPORT=on -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=on -Dtensorflow_PATH_CUDA_LIB=/usr/local/cuda-10.0/lib -Dtensorflow_PATH_CUDNN_LIB=/usr/local/cudnn-7.4.2.24/cuda/lib -Dtensorflow_CUDNN_INCLUDE=/usr/local/cudnn-7.4.2.24/cuda/include -Dtensorflow_BUILD_SHARED_LIB=on -Dtensorflow_NCCL_INCLUDE=/usr/local/nccl-2.4.7/include -Dtensorflow_PATH_NCCL_LIB=/usr/local/nccl-2.4.7/lib -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -Dtensorflow_PATH_NCCL_STATIC_LIB=/usr/local/nccl-2.4.7/lib -Dtensorflow_PATH_CUDNN_STATIC_LIB=/usr/local/cudnn-7.4.2.24/cuda/lib -DCUDA_cupti_LIBRARY=/usr/local/cuda-10.0/extras/CUPTI/lib -Dculibos_STATIC_LIBRARY=/usr/local/cuda-10.0/lib64/libculibos.a -DOPENSSL_NO_ASM=1

````

**Comment by samhodge** [comment] 2019-05-29 12:37
After trying to hack abseil-cpp into the include and CXX_FLAGS via the flags.make

After the fact I am left with the following

```
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/io/path.cc.o: In function `tensorflow::io::internal::SplitPath(absl::string_view)':
path.cc:(.text+0x337): undefined reference to `absl::string_view::rfind(char, unsigned long) const'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/io/path.cc.o: In function `tensorflow::io::internal::SplitBasename(absl::string_view)':
path.cc:(.text+0x57b): undefined reference to `absl::string_view::rfind(char, unsigned long) const'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/io/path.cc.o: In function `absl::string_view::substr(unsigned long, unsigned long) const':
path.cc:(.text._ZNK4absl11string_view6substrEmm[_ZNK4absl11string_view6substrEmm]+0x33): undefined reference to `absl::base_internal::ThrowStdOutOfRange(char const*)'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/monitoring/collection_registry.cc.o: In function `tensorflow::monitoring::CollectionRegistry::Register(tensorflow::monitoring::AbstractMetricDef const*, std::function<void (tensorflow::monitoring::MetricCollectorGetter)> const&)':
collection_registry.cc:(.text+0x5a4): undefined reference to `absl::operator<<(std::ostream&, absl::string_view)'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/strings/str_util.cc.o: In function `tensorflow::str_util::TitlecaseString(std::string*, absl::string_view)':
str_util.cc:(.text+0x126a): undefined reference to `absl::string_view::find(char, unsigned long) const'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/lib/strings/str_util.cc.o: In function `std::vector<std::string, std::allocator<std::string> > tensorflow::str_util::Split<tensorflow::str_util::AllowEmpty>(absl::string_view, absl::string_view, tensorflow::str_util::AllowEmpty)':
str_util.cc:(.text._ZN10tensorflow8str_util5SplitINS0_10AllowEmptyEEESt6vectorISsSaISsEEN4absl11string_viewES7_T_[_ZN10tensorflow8str_util5SplitINS0_10AllowEmptyEEESt6vectorISsSaISsEEN4absl11string_viewES7_T_]+0xa1): undefined reference to `absl::string_view::find(char, unsigned long) const'
CMakeFiles/tf_core_lib.dir/home/kognat/dev/tensorflow-1.12.0-static-gpu/tensorflow/tensorflow/core/platform/posix/port.cc.o: In function `tensorflow::port::NominalCPUFrequency()':
port.cc:(.text+0x3de): undefined reference to `absl::base_internal::NominalCPUFrequency()'
collect2: error: ld returned 1 exit status
make[2]: *** [proto_text] Error 1
make[1]: *** [CMakeFiles/proto_text.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This contrib/cmake was probably only working back in v1.8.0 or before.

**Comment by Huangswust182** [comment] 2019-07-08 04:30
@samhodge Hello, can you tell me how you modified tf_stream_executor.cmake?

**Comment by samhodge** [comment] 2019-07-08 06:39
I never got a successful build

**Comment by Huangswust182** [comment] 2019-07-08 07:46
That's really depressing.

**Comment by gadagashwini** [comment] 2019-07-31 10:10
@samhodge, Is this still an issue? Thanks!

**Comment by tensorflowbutler** [comment] 2019-08-15 12:29
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by samhodge** [comment] 2019-08-15 22:06
It is still open, is the CMake build system abandoned by Tensorflow developers, last time I got it to work was 1.8.

Is bazel the only way to built Tensorflow?

If this is so there is no straightfoward way to build an archive of .o files for statically linking Tensorflow to a C++ application.

If the CMake tree doesnt work it should be removed from the code base rather than giving users false hope that it actually works.

**Comment by gadagashwini** [comment] 2019-08-16 10:44
@angersson can you please take a look?

**Comment by angersson** [comment] 2019-08-19 19:34
Bazel is the only supported way to build TensorFlow, sorry. Since contrib is being removed as a part of TF 2.0, the cmake files will go away at the same time.

**Comment by salamanderrake** [comment] 2019-12-08 14:55
> 
> 
> Bazel is the only supported way to build TensorFlow, sorry. Since contrib is being removed as a part of TF 2.0, the cmake files will go away at the same time.

That is sad and short sighted on the part of the developers, why support Bazel only, and not the widely used CMake?

**Comment by yl255** [comment] 2020-05-19 00:47
> It is still open, is the CMake build system abandoned by Tensorflow developers, last time I got it to work was 1.8.
> 
> Is bazel the only way to built Tensorflow?
> 
> If this is so there is no straightfoward way to build an archive of .o files for statically linking Tensorflow to a C++ application.
> 
> If the CMake tree doesnt work it should be removed from the code base rather than giving users false hope that it actually works.

@samhodge Hi, I made a try to build tensorflow v1.13.1 with vs2017 using cuda 10.1.
I builded without python and successed.
https://github.com/yl255/Build-tensorflow-v1.31.1-with-vs2017-using-cuda-10.1)
Maybe you can have a try.
Good luck!

**Comment by samhodge** [comment] 2020-05-19 00:58
I will see if this comes a priority again, thanks so much for sharing.

**Comment by mohantym** [comment] 2021-08-16 04:22
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.5  version or later and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Closed** 2021-08-30 05:36 UTC
Labels: stat:contributions welcome, stat:awaiting response, type:build/install, stalled, TF 1.13, subtype:centos
