### ISSUE TITLE
Tensor flow issue

### ISSUE THREAD

**Issue by Deepu777yt** [tensorflow/tensorflow#72257] opened 2024-07-21 14:00 UTC
import cv2
import time
import numpy as np
import HandTrackingModule as htm
import math
from ctypes import cast, POINTER
from comtypes import CLSCTX_ALL
from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume

wCam, hCam = 640, 480

cap = cv2.VideoCapture(0)
cap.set(3, wCam)
cap.set(4, hCam)

detector = htm.HandDetector(detectionCon=0.7)

devices = AudioUtilities.GetSpeakers()
interface = devices.Activate(
    IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
volume = cast(interface, POINTER(IAudioEndpointVolume))
volRange = volume.GetVolumeRange()
minVol = volRange[0]
maxVol = volRange[1]

while True:
    success, img = cap.read()
    img = detector.findHands(img)
    lmList = detector.findPosition(img, draw=False)
    if len(lmList) != 0:
        x1, y1 = lmList[4][1], lmList[4][2]
        x2, y2 = lmList[8][1], lmList[8][2]
        length = math.hypot(x2 - x1, y2 - y1)
        vol = np.interp(length, [50, 300], [minVol, maxVol])
        volBar = np.interp(length, [50, 300], [400, 150])
        volPer = np.interp(length, [50, 300], [0, 100])
        print(int(length), vol)
        volume.SetMasterVolumeLevel(vol, None)
        if length < 50:
            cv2.circle(img, (cx, cy), 15, (0, 255, 0), cv2.FILLED)
    
    cv2.imshow("Img", img)
    cv2.waitKey(1)

error is:
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================= RESTART: C:/Users/nagad/Desktop/import PIL.py ================
Traceback (most recent call last):
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/nagad/Desktop/import PIL.py", line 4, in <module>
    import HandTrackingModule as htm
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\HandTrackingModule\__init__.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.tasks.python as tasks
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\tasks\python\__init__.py", line 17, in <module>
    from . import audio
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\tasks\python\audio\__init__.py", line 18, in <module>
    import mediapipe.tasks.python.audio.audio_classifier
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\tasks\python\audio\audio_classifier.py", line 26, in <module>
    from mediapipe.tasks.python.audio.core import base_audio_task_api
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\tasks\python\audio\core\base_audio_task_api.py", line 25, in <module>
    from mediapipe.tasks.python.core.optional_dependencies import doc_controls
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\mediapipe\tasks\python\core\optional_dependencies.py", line 20, in <module>
    from tensorflow.tools.docs import doc_controls
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\tensorflow\python\pywrap_tensorflow.py", line 85, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\nagad\AppData\Roaming\Python\Python312\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

**Comment by mihaimaruseac** [comment] 2024-07-21 14:12
Duplicate of #72120

**Closed by mihaimaruseac** 2024-07-21 14:12 UTC
