### ISSUE TITLE
Custom loss function fails with sample_weight and batch_size > 1

### ISSUE THREAD

**Issue by ingo-m** [tensorflow/tensorflow#31309] opened 2019-08-03 20:08 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Debian 9.9
- TensorFlow installed from: conda (-c anaconda)
- TensorFlow version: 1.14.0
- Python version: 3.7.3
- GPU model and memory: n/a - tested in CPU mode

**Describe the current behavior**

An error occurs when training an LSTM with a custom loss function, using `sample_weight` and `batch_size > 1`. The error does not occur if `batch_size = 1`, or if `sample_weight = None`.

**Describe the expected behavior**

I would expect custom loss functions to work irrespective of batch size and sample weights.

**Code to reproduce the issue**

Here’s a minimal example:
```python
import numpy as np
import tensorflow as tf

batch_size = 32  # no problem if this is 1
sequence_len = 1
embedding_size = 100

x_train = np.random.randn(batch_size, sequence_len, embedding_size)
y_train = np.random.randn(batch_size, embedding_size)
sample_weight = np.random.randn(batch_size)  # no problem if this is None

train_input = tf.keras.Input(shape=(sequence_len, embedding_size),
                             batch_size=batch_size)

lstm_layer = tf.keras.layers.LSTM(200,
                                  return_sequences=False,
                                  )(train_input)

dense_layer = tf.keras.layers.Dense(embedding_size,
                                    )(lstm_layer)

model = tf.keras.models.Model(inputs=train_input, outputs=dense_layer)

model.summary()

# Custom loss function. This function could of course be replaced with
# tf.keras.losses.mean_squared_error, but I have a use case where I need a
# custom loss function.
class customLoss(tf.keras.losses.Loss):
    def call(self, y_true, y_pred):
        return tf.reduce_mean(tf.math.squared_difference(y_true, y_pred))

model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.001),
              loss=customLoss())

loss = model.train_on_batch(x_train,
                            y=y_train,
                            sample_weight=sample_weight)

```

**Other info / logs**

In #29026, @pavithrasv has pointed out that loss functions from `tf.losses` do not work with keras, and suggested to use loss functions from `tf.keras.losses` instead (thanks again!). Consequently, I thought that defining a custom loss function using the `tf.keras.losses.Loss` base class should be possible. (Please note that in my actual use case I have a more complex custom loss function for which I need some math operations from `tf.math`.)

Traceback:
```bash
Traceback (most recent call last):
  File "/home/john/PhD/GitLab/literary_lstm/bug_minimal_example_03.py", line 38, in <module>
    sample_weight=sample_weight)
  File "/home/john/miniconda3/envs/py_tf/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/john/miniconda3/envs/py_tf/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/john/miniconda3/envs/py_tf/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 32
	 [[{{node loss_1/dense_loss/weighted_loss/Squeeze}}]]
```

**Comment by ChiHangChen** [comment] 2019-12-17 16:40
I have exactly the same issue.

**Comment by pavithrasv** [comment] 2019-12-17 20:33
Thank for reporting this @ingo-m . The issue is because of how the custom loss is expected to be implemented. The `call` in `Loss` class is expected to return per-sample loss values. 

Please take a look at the documentation for `y_true`, `y_pred`, `sample_weight` here: https://www.tensorflow.org/api_docs/python/tf/keras/losses/Loss?version=nightly#__call__

`call` basically reduces y_true and y_pred with shape [batch_size, d0, .. dN] to loss values of shape [batch_size, d0, .. dN-1]. The reduce_mean is along the last dimension. To this result sample_weight that is broadcastable to shape [batch_size, d0, .. dN-1] is applied.

In your code updating the loss function like: 
`return tf.reduce_mean(tf.math.squared_difference(y_true, y_pred), axis=-1)` will fix the issue.

Hope this helps :) Closing out the issue, please feel free to add comments if you have more questions.

**Closed by pavithrasv** 2019-12-17 20:33 UTC
Labels: comp:keras, type:bug

**Comment by oholimoli** [comment] 2020-07-29 15:26
I'm currently trying to extend the example here with sample weights: https://www.tensorflow.org/guide/keras/custom_layers_and_models

Until now I had no luck :(.

@pavithrasv Could you please explain how the example can be modified to use sample weights?  (or class_weights)

**Comment by pavithrasv** [comment] 2020-08-17 23:07
@oholimoli  You will have to provide the weights when calling the loss function in the custom training loop. here -> https://www.tensorflow.org/guide/keras/custom_layers_and_models#putting_it_all_together_an_end-to-end_example
