### ISSUE TITLE
Tflite metal gpu ios model reload

### ISSUE THREAD

**Issue by zuoshaobo** [tensorflow/tensorflow#28753] opened 2019-05-16 00:32 UTC
My target is ios device ,Target backend is metal gpu , Durining our test ,I found that 'memory leak'  occured when switch different models  about 100 times ,so  how to release last neural models ?like below:
interpreter=nullptr
DeleteGpuDelegate(delegate)
is it right ?

**Comment by gadagashwini** [comment] 2019-05-20 12:01
@zuoshaobo It looks, This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide greater support. If you think it is a bug. Please let us know. Thanks!

**Comment by gadagashwini** [comment] 2019-05-27 05:07
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-05-27 05:07 UTC
Labels: comp:lite, stat:awaiting response, type:support
