### ISSUE TITLE
mnasnet with squeeze and excite can not be quantized

### ISSUE THREAD

**Issue by danilopau** [tensorflow/tensorflow#45082] opened 2020-11-22 19:45 UTC
I wrote a Colab document with Mnasnet in keras and added a squeeze and excite block
TensorFlow was 2.3.0
I have been able to generate the .h5 file correctly 
However when I apply the post training quantization procedure, I have this error
RuntimeError: Unsupported output type INT8 for output tensor 'Identity' of type FLOAT32.
Without the squeeze and excite block it works nicely generating int8 version
Attached the notebook
[Quantize_procedure_mnasnet_se.zip](https://github.com/tensorflow/tensorflow/files/5580189/Quantize_procedure_mnasnet_se.zip)
Thanks and kind regards
Danilo

**Comment by amahendrakar** [comment] 2020-11-23 15:24
@danilopau,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: 'ILSVRC2012_img_val'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7a2bc45ee8dd09b316f2232c58bdeea9/45082.ipynb). 

In order to expedite the trouble-shooting process, could you please provide all the supporting files necessary to reproduce the issue. Thanks!

**Comment by amahendrakar** [comment] 2020-11-23 15:30
> However when I apply the post training quantization procedure, I have this error
> RuntimeError: Unsupported output type INT8 for output tensor 'Identity' of type FLOAT32.

@danilopau,
Also, please take a look at issues [#42082](https://github.com/tensorflow/tensorflow/issues/42082) and [#38285](https://github.com/tensorflow/tensorflow/issues/38285) with a similar error and let us know if it helps. Thanks!

**Comment by danilopau** [comment] 2020-11-23 19:39
I used pip install tensorflow==2.4.0-rc2
with code
model = tf.keras.models.load_model(selected_model_path_h5)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_data_gen
converter.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()

but got error
RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor input_1
Empty min/max for tensor input_1

**Comment by danilopau** [comment] 2020-11-23 19:42
and network is a simple squeeze and excite
def seblock(input_shape=None, nb_classes=10):
    img_input = layers.Input(shape=input_shape)
    
    x = layers.Conv2D(filters=320, kernel_size=(3,3))(img_input)
    x = layers.GlobalAveragePooling2D()(x)
    # x = layers.GlobalMaxPooling2D()(x)
    # start squeeze and excite block
    ratio=16
    filters=320 #depends on previous x shape
    se_shape = (1, 1, 320)
    se = x
    se = layers.Reshape(se_shape)(se)
    se = layers.Dense(filters // ratio, activation='relu', kernel_initializer='he_normal', use_bias=False)(se)
    se = layers.Dense(640, activation='sigmoid', kernel_initializer='he_normal', use_bias=False)(se)
    y = layers.Dense(640, activation='sigmoid', kernel_initializer='he_normal', use_bias=False)(x)
    w = layers.Multiply()([y, se])
    # end squeeze and excite block

    z = layers.Dense(nb_classes, activation='softmax', use_bias=True, name='proba')(w)
    
    inputs = img_input
    
    model = Model(inputs, z, name='seblock')
    return model

can you try to quantize it using ILVRC 1000 classes dataset please ?

**Comment by danilopau** [comment] 2020-11-23 19:43
Guy, I need a step by step tutorial not pointing me to half million ticket to surf between. If you want tensorflow used by ordinary programming guys you need to be humble and simple

**Comment by amahendrakar** [comment] 2020-11-30 16:27
@danilopau,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/a75a39c0587d8b0915ef0c51201f1e36/45082.ipynb). 

However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8e7b269ac8f42da2422cce0423aa1f55/45082-tf-nightly.ipynb), please check the linked gist for reference. Thanks!

**Comment by danilopau** [comment] 2020-11-30 16:58
Greatly appreciated Abhilash!

When do you expect tf 2.5.0 stable and released ?

Kindest regards
Danilo

**Comment by amahendrakar** [comment] 2020-12-22 16:13
@danilopau,
Sorry for the delayed response. I was waiting to check if the issue would be resolved with TF v2.4 stable version, but it did not. 

> When do you expect tf 2.5.0 stable and released ?

I do not have an exact date but it should be released by Q1 2021. Thanks!

**Closed** 2021-01-05 16:55 UTC
Labels: Fixed in Nightly, TF 2.3, TFLiteConverter, comp:lite, stalled, stat:awaiting response, type:support
