### ISSUE TITLE
Truncated Distributions in TensorFlow

### ISSUE THREAD

**Issue by ZigaSajovic** [tensorflow/tensorflow#20283] opened 2018-06-25 18:15 UTC
At this point, only [tf.truncated_normal](https://www.tensorflow.org/api_docs/python/tf/truncated_normal) is implemented within TensorFlow. Are there any plans for implementing others aswell? ex. Truncated Gamma, Truncated Exponential etc. Truncated distributions come up often in probabilistic programming, a branch in which TensorFlow is becoming prominent. I for one do most of my probabilistic work and sampling in TensorFlow, due to the GPU support and the control it offers me.

Each truncated distribution offers a different method of efficiently sampling from it, so distribution specific algorithms would be ideal.

In the mean time, I implemented a general method for personal use. I attach the specifications bellow, in case there is any interest in this general solution (the implementation, documentation and examples are available [here](https://github.com/ZigaSajovic/truncatedDistribution)). Note that I am willing to work on improving it, in case interest is present.

**TruncatedDistribution**

The class [TruncatedDistribution](https://github.com/ZigaSajovic/truncatedDistribution) extends any existing TensorFlow distribution, i.e. classes inheriting from [tf.distribution](https://www.tensorflow.org/api_docs/python/tf/distributions/Distribution), to enable their truncated counterparts, with full support of broadcasting.

**Methods:**

* \_\_init\_\_(disttribution,left,right, n_points=1000)
* sample(sample_shape=())
* cdf(X)
* log_cdf(X)
* survival_function(X)
* log_survival_function(X)
* prob(X)
* log_prob(X)
* mean(n_samples=1000)
* variance(n_samples=1000)
* stddev(n_samples=1000)

**Comment by tensorflowbutler** [comment] 2018-06-26 07:12
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ZigaSajovic** [comment] 2018-06-26 12:12
Have I written custom code: Yes
OS Platform and Distribution Ubuntu: 16.0
TensorFlow installed from: N/A
TensorFlow version: 1.8
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by cy89** [comment] 2018-07-11 00:43
@ringw Dan, it looks like some of this code was yours. Can you comment on future plans, or points us at someone who can, please?

**Comment by ringw** [comment] 2018-07-13 16:21
Hello,

I had started writing [a new truncated normal kernel for arbitrary intervals](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/parameterized_truncated_normal_op.cc), but then had another 20% project that took priority. The eventual plan was to benchmark that kernel against the current tf.truncated_normal on the same fixed interval, and once it's ready, add a new truncated_normal function (maybe initially in tf.contrib) that takes vectors of mean/stddev/low/high values. However, if no one wants to get that implementation running, I'm also fine with deleting it. I don't know of any plans for other distributions, and @ebrevdo is my point of contact within the Brain team.

**Comment by ebrevdo** [comment] 2018-07-13 16:40
I don't think we plan to have a generic Truncated distribution object, at least unless we can add [automatic implicit reparameterization gradients](https://arxiv.org/abs/1805.08498) as part of the generic implementation.

**Comment by ebrevdo** [comment] 2018-07-13 16:41
I'm assuming here you mean for any distribution with a scalar event shape (i.e., single variate distributions).

**Comment by cy89** [comment] 2018-07-13 16:42
Thanks, @ringw and @ebrevdo. I'll mark "contributions welcome". @ZigaSajovic thanks for being willing to work on this!

**Comment by ebrevdo** [comment] 2018-07-13 16:46
If you'd like to work on this, I do suggest reading the paper I linked
above, especially section #4.

**Comment by tensorflowbutler** [comment] 2018-07-28 18:51
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by hesenp** [comment] 2018-09-25 18:35
hey folks @cy89 @ringw 

I happen to have stumbled upon this issue for some of my research and am wondering what would be the plan here? 

My thought is quite aligned with what @ZigaSajovic 's solution: for truncated univariate distributions with simple left or right truncation, have a wrapper class that wraps around the base distribution and make adjustment on the PDF and CDF. I think this is consistent with  
@ebrevdo 's paper section 4. 

Here I'm assuming that the underlying infrastructure could take over the `tf.distribution` instance that we have and conduct differentiation etc accordingly. As long as we have re-defined PDF and CDF in the new class. Please enlighten me if this is consistent with what ya'll are thinking? Thanks

**Comment by meereeum** [comment] 2018-10-02 23:52
Would also be useful if `tf.truncated_normal` permitted custom upper/lower bounds, independent of the variance (rather than the symmetric +/- 2 SDs)

**Comment by jvishnuvardhan** [comment] 2021-09-16 18:23
This is a stale issue. Looks like this was resolved.
Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-09-16 18:23 UTC
Labels: stat:contributions welcome, type:feature

**Comment by ringw** [comment] 2021-09-18 14:16
Thanks -- I don't have full context into how this is being used, but the first pass is definitely complete.

[TensorFlow Probability](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/TruncatedNormal) is still intended to be the entry point for the more general (arbitrary bounds) distribution; the kernel for this was originally implemented in TensorFlow proper.
