### ISSUE TITLE
Keras load weights fails to load model from directory containing [[

### ISSUE THREAD

**Issue by racinmat** [tensorflow/tensorflow#33978] opened 2019-11-04 17:01 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.6.1810 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, using conda
- TensorFlow version (use command below): unknown 1.14.0, with intel MKL
- Python version: 3.7.4
- CUDA/cuDNN version: no gpu
- GPU model and memory: no gpu

**Describe the current behavior**
When model checkpoint is stored in a directory containing `[[` in its name, the model fails to load, looks like the model files are missing, throwing NotFoundError

`model.load_weights(osp.join(model_dir, 'model'))` throws exception when for example, the model_dir='/home/projects/my_ml/data/sims/bs=2048_dataset=[[2019_9_13],[2019_9_12,2019_9_11,2019_9_10,2019_9_9]]'

**Describe the expected behavior**

`model.load_weights(osp.join(model_dir, 'model'))` should load the data without problems

**Code to reproduce the issue**
Here is [google colab code](https://colab.research.google.com/drive/1N1oPDXcmijzXs49C3DDLjm2pVHsUQvYP) with mnist example.

**Other info / logs**
The error is NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bs=2048_dataset=[[2019_9_13],[2019_9_12,2019_9_11,2019_9_10,2019_9_9]]/model

**Comment by oanush** [comment] 2019-11-05 05:00
@racinmat ,
Thanks for reporting the issue,  can you please provide access to link` google colab code` provided?

**Comment by racinmat** [comment] 2019-11-05 08:20
Fixed, I put here new link, it should be accessible now.

**Comment by oanush** [comment] 2019-11-05 09:17
Issue replicating for the given code in both TF-1.14 and 1.15. Thanks!

**Comment by racinmat** [comment] 2019-11-05 15:49
Is there some additional response needed? Or why the tag?

**Comment by jvishnuvardhan** [comment] 2020-03-16 21:57
@racinmat Model directory name looks very interesting. What kind of use case you have that requires this interesting model directory? Thanks!

**Comment by racinmat** [comment] 2020-03-17 08:50
I just cast list of parameters of training the model to string, and some parameters are 2D arrays, and I am using this string as a directory with all files related to that run. I made my quick fix by replacing [ with ( and ] with ), but I consider it a workaround, not a proper solution.

**Comment by k-w-w** [comment] 2020-03-17 18:06
Hi @racinmat, this does seem like a bug in our checkpoint loading code. We're not able to fix this right away, so I'll mark this as open for contributions if anyone wants to help resolve this.

**Comment by eewindfly** [comment] 2020-07-30 09:03
I have the same issue
when there is any char between [], it will fail to load
e.g. [a] doesn't work, but [] works

**Comment by AnimeshSinha1309** [comment] 2020-08-11 04:31
I can replicate this issue in TensorFlow 2.3.0. Hope I can take a try at fixing the issue.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:10
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by racinmat** [comment] 2021-02-03 20:42
@ymodak  Hi, since this issue is still there in Tensorflow 2.3, can you prevent this from automatic closing until this is fixed? Thanks.

**Comment by sachinprasadhs** [comment] 2021-05-20 12:05
Was able to reproduce your issue in TF Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/99d6bc061e5f29c90db6886ea8e4b2fd/untitled43.ipynb).

**Comment by bhack** [comment] 2021-05-20 12:21
You need to use in your colab:
```python
model = model.load_weights(osp.join(re.escape(model_dir), 'model'))
```
I don't know if we could escape internally

**Comment by sanatmpa1** [comment] 2021-08-04 11:28
@racinmat ,

Can you please respond to the above comment?

**Comment by racinmat** [comment] 2021-08-05 07:00
So I can save the model without escaping, but I need to escape it for loading?
In the documentation I can not find any mention of regular expressions, so it's unclear why it does help.
So this should be mentioned in the docs if this is the proper way to escape model names, right?
I understand this is workaround, not fix of the issue, right?

**Comment by bhack** [comment] 2021-08-05 09:15
Can you reproduce this with TF 2.5.0?

**Comment by mohantym** [comment] 2021-08-05 15:14
Was able to replicate the issue with TF v2.5 ,please find the [gist ](https://colab.research.google.com/gist/mohantym/aed6490aedca803357a48b577946d1cc/33798.ipynb)here.

**Comment by mihaimaruseac** [comment] 2021-08-06 18:30
So I think the issue here is that loading the model needs to identify all files in a subdirectory and to do that it uses `GetMatchingPaths`. But `[` is a special character for `GetMatchingPaths`.

**Comment by bhack** [comment] 2021-08-06 18:49
Yes I think is the same as https://github.com/tensorflow/tensorflow/issues/35489

**Comment by mihaimaruseac** [comment] 2021-08-07 21:28
Confirmed. Closing this as duplicate of #35489

It will take some time until this gets fixed, but hopefully we can get this fixed in the near future.

**Closed by mihaimaruseac** 2021-08-07 21:28 UTC
Labels: stat:contributions welcome, stat:awaiting response, type:bug, comp:keras, TF 1.15
