### ISSUE TITLE
Model Maker Object Detection Tutorial crashes in colab at model.export line (TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems')

### ISSUE THREAD

**Issue by rolfvandam** [tensorflow/tensorflow#56970] opened 2022-08-01 19:20 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Google Colab

### Python version

3.7.14

### Current Behaviour?

```shell
When running the Google Colab for Model Maker Object Detection (https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb#scrollTo=Hm_UULdW7A9T) it crashes at the model.export stage.

I was running the colab because running it locally produces the same error and I was trying to tease out the exact combination of versions of libraries to make this work. Sadly it crashed in colab just the same.

From what I can figure out from comments elsewhere this might have to do with a wrong version of FlatBuffers (or a bad combination of libraries).
```

### Standalone code to reproduce the issue

```shell
Run all the preceding code in the colab. It crashes on this line:

model.export(export_dir='.')
```

### Relevant log output

```shell
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-10-4c3d25dac6cc> in <module>()
----> 1 model.export(export_dir='.')

8 frames

/usr/local/lib/python3.7/dist-packages/tensorflow_lite_support/metadata/metadata_schema_py_generated.py in Pack(self, builder)
   2562                 for i in reversed(range(len(self.mean))):
   2563                     builder.PrependFloat32(self.mean[i])
-> 2564                 mean = builder.EndVector()
   2565         if self.std is not None:
   2566             if np is not None and type(self.std) is np.ndarray:

TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems'
```
</details>

**Comment by mohantym** [comment] 2022-08-02 13:59
Hi @rolfvandam !
Thanks for reporting this bug. It is replicating even when valid path is given . 

@rthadur !
Could you look at this issue . Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/1aedb9ec55c5f5275f10496a3fdaa5fd/model-maker-object-detection-tutorial.ipynb#scrollTo=ZQpahAIBqBPp) for reference.
Thank you!

**Comment by Abdullah-208** [comment] 2022-08-16 12:51
I am currently facing this issue.
any solution or alternative?

**Comment by rolfvandam** [comment] 2022-08-16 13:19
> I am currently facing this issue.
> any solution or alternative?

I've switched to a different platform for object detection (YOLOv5 which is pytorch based).

**Comment by Abdullah-208** [comment] 2022-08-16 13:27
@rolfvandam actually I am training a custom object detection model to use it in android application.
I have already trained the model but can't export it in tflite format!

**Comment by Abdullah-208** [comment] 2022-08-16 16:49
@rthadur !
have you found anything to solve this problem?
I need the solution ASAP!

**Comment by JunyoungLim** [comment] 2022-09-21 00:56
Hi! Sorry for the delayed response. Will https://github.com/tensorflow/tensorflow/pull/57394 address this issue? If so, I will re-assign it to @mohantym .

**Comment by mohantym** [comment] 2022-09-28 12:53
Hi @rolfvandam  @JunyoungLim !
I think this issue has been fixed now (might be because of flatbuffer version upgrade ). I ran the notebook today and did not find any issue with the model saving part.

Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/f82c9820482cd92249b7955f49355b59/model-maker-object-detection-tutorial.ipynb)for reference.

Thank you!

**Comment by JunyoungLim** [comment] 2022-10-05 18:49
Thanks, @mohantym ! 

Hi, @rolfvandam , I will close this issue as the PR seemed to fix it, but please feel free to open it again if the issue is still present.

**Closed by JunyoungLim** 2022-10-05 18:49 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite-examples, TF 2.9
