### ISSUE TITLE
Error while Building tensorflow using cross-tool for aarch64 

### ISSUE THREAD

**Issue by TropSpirit** [tensorflow/tensorflow#25607] opened 2019-02-08 02:51 UTC
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): - Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source trying to build and install for aarch64 (arm64)
- TensorFlow version:  1.12.0 (trying to install)
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NO - virtualenv or pip
- Bazel version (if compiling from source): 0.19.0 (tried with new version same issue)
- GCC/Compiler version (if compiling from source): - gcc-aarch64-linux-gnu & g++-arch64-linux-gnu
- CUDA/cuDNN version: No CUDA or XcuDNN
- GPU model and memory:  NO GPU used 

Installed bazel - 0.19.0 version
Tensorflow source latest from git
Building in Ubuntu for arm64 bit(aarch64) cpu using cross-tool. 

Command for building:
bazel build -c opt //tensorflow/examples/label_image --cpu=aarch64 -- crosstool_top=//tools/aarch64_compiler:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --verbose_failures

And here is the error logs:
****ERROR**: /home/cmp/.cache/bazel/_bazel_root/b7eb2acccd1b56cb3e56479bb5f07f48/external/mkl_dnn/BUILD.bazel:71:1: C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1): aarch64-linux-gnu-gcc failed: error executing command** 
  (cd /home/cmp/.cache/bazel/_bazel_root/b7eb2acccd1b56cb3e56479bb5f07f48/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3.6 \
    PYTHON_LIB_PATH=/usr/lib/python3.6 \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
  /usr/bin/aarch64-linux-gnu-gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.o' -iquote external/mkl_dnn -iquote bazel-out/aarch64-opt/genfiles/external/mkl_dnn -iquote bazel-out/aarch64-opt/bin/external/mkl_dnn -iquote external/bazel_tools -iquote bazel-out/aarch64-opt/genfiles/external/bazel_tools -iquote bazel-out/aarch64-opt/bin/external/bazel_tools -isystem external/mkl_dnn/include -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/include -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/common -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu/gemm -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu/xbyak -fexceptions '-DMKLDNN_THR=MKLDNN_THR_SEQ' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp -o bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.o)
In file included from external/mkl_dnn/src/cpu/cpu_isa_traits.hpp:35:0,
                 from external/mkl_dnn/src/cpu/jit_generator.hpp:21,
                 from external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.hpp:23,
                 from external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp:23:
external/mkl_dnn/src/cpu/xbyak/xbyak_util.h:84:21: **fatal error: cpuid.h: No such file or directory**
compilation terminated.
Target //tensorflow/examples/label_image:label_image failed to build
INFO: Elapsed time: 49.893s, Critical Path: 10.85s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 194 processes: 194 local.
FAILED: Build did NOT complete successfully

**Comment by jvishnuvardhan** [comment] 2019-02-08 17:12
Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Thanks!

**Comment by TropSpirit** [comment] 2019-02-08 17:32
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): - Ubuntu 16.04
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
* TensorFlow installed from (source or binary): source trying to build and install for aarch64 (arm64)
* TensorFlow version:  1.12.0 (trying to install)
* Python version: 3.6
* Installed using virtualenv? pip? conda?: NO - virtualenv or pip
* Bazel version (if compiling from source): 0.19.0 (tried with new version same issue)
* GCC/Compiler version (if compiling from source): - gcc-aarch64-linux-gnu & g++-arch64-linux-gnu
* CUDA/cuDNN version: No CUDA or XcuDNN
* GPU model and memory:  NO GPU used

Installed bazel - 0.19.0 version
Tensorflow source latest from git
Building in Ubuntu for arm64 bit(aarch64) cpu using cross-tool.

Command for building:
bazel build -c opt //tensorflow/examples/label_image --cpu=aarch64 -- crosstool_top=//tools/aarch64_compiler:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --verbose_failures

And here is the error logs:
****ERROR**: /home/cmp/.cache/bazel/_bazel_root/b7eb2acccd1b56cb3e56479bb5f07f48/external/mkl_dnn/BUILD.bazel:71:1: C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1): aarch64-linux-gnu-gcc failed: error executing command**
(cd /home/cmp/.cache/bazel/_bazel_root/b7eb2acccd1b56cb3e56479bb5f07f48/execroot/org_tensorflow && exec env - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin PWD=/proc/self/cwd PYTHON_BIN_PATH=/usr/bin/python3.6 PYTHON_LIB_PATH=/usr/lib/python3.6 TF_DOWNLOAD_CLANG=0 TF_NEED_CUDA=0 TF_NEED_OPENCL_SYCL=0 TF_NEED_ROCM=0 /usr/bin/aarch64-linux-gnu-gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.o' -iquote external/mkl_dnn -iquote bazel-out/aarch64-opt/genfiles/external/mkl_dnn -iquote bazel-out/aarch64-opt/bin/external/mkl_dnn -iquote external/bazel_tools -iquote bazel-out/aarch64-opt/genfiles/external/bazel_tools -iquote bazel-out/aarch64-opt/bin/external/bazel_tools -isystem external/mkl_dnn/include -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/include -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/common -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu/gemm -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/aarch64-opt/genfiles/external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn/src/cpu/xbyak -fexceptions '-DMKLDNN_THR=MKLDNN_THR_SEQ' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp -o bazel-out/aarch64-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/jit_avx512_core_x8s8s32x_conv_kernel.o)
In file included from external/mkl_dnn/src/cpu/cpu_isa_traits.hpp:35:0,
from external/mkl_dnn/src/cpu/jit_generator.hpp:21,
from external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.hpp:23,
from external/mkl_dnn/src/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp:23:
external/mkl_dnn/src/cpu/xbyak/xbyak_util.h:84:21: **fatal error: cpuid.h: No such file or directory**
compilation terminated.
Target //tensorflow/examples/label_image:label_image failed to build
INFO: Elapsed time: 49.893s, Critical Path: 10.85s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 194 processes: 194 local.
FAILED: Build did NOT complete successfully

**Comment by jvishnuvardhan** [comment] 2019-02-08 21:43
@TropSpirit One thing I quickly noticed is version of Bazel. Please check the test build configuration [here](https://www.tensorflow.org/install/source#linux). DO you mind downgrading Bazel to 0.15.0 and test whether the error is same or not. Meanwhile I will also take a deeper look at the issue. Thanks!

**Comment by TropSpirit** [comment] 2019-02-09 01:27
I tried using bazel 0.15.0 for crosscompiling still same error. i even tried tensorflow 1.8 and bazel 0.10.0

$ bazel build -c opt //tensorflow/examples/label_image --cpu=aarch64 --crosstool_top=//tools/aarch64_compiler:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --verbose_failures


**_ERROR: /home/cmp/.cache/bazel/_bazel_nshivash/a20291383e693f326d5a9bf14cdd7b80/external/nsync/BUILD:466:13: Configurable attribute "copts" doesn't match this configuration (would a default condition help?).
Conditions checked:_**
 @nsync//:android_arm
 @nsync//:android_arm64
 @nsync//:android_armeabi
 @nsync//:android_x86_32
 @nsync//:android_x86_64
 @nsync//:clang_macos_x86_64
 @nsync//:freebsd
 @nsync//:gcc_linux_aarch64
 @nsync//:gcc_linux_ppc64
 @nsync//:gcc_linux_s390x
 @nsync//:gcc_linux_x86_32_1
 @nsync//:gcc_linux_x86_64_1
 @nsync//:gcc_linux_x86_64_2
 @nsync//:ios_x86_64
 @nsync//:msvc_windows_x86_64
ERROR: Analysis of target '//tensorflow/examples/label_image:label_image' failed; build aborted:

**Comment by TropSpirit** [comment] 2019-02-13 19:05
Any update on this ?

**Comment by NKucza** [comment] 2019-02-19 07:09
i have the same issue.. is there a way around?

**Comment by AlbertoLanaro** [comment] 2019-02-22 14:53
Hi, I had the same issue. It seems to be solved with this flag in the `baze build` command:

`bazel build --define tensorflow_mkldnn_contraction_kernel=0 ...`

**Comment by jvishnuvardhan** [comment] 2019-02-22 17:25
@AlbertoLanaro Thanks for the solution. @TropSpirit and @NKucza Could you both try the solution? Thanks!

**Comment by petewarden** [comment] 2019-02-22 23:26
Sorry for the slow response! We don't officially support aarch64 linux builds (we don't have continuous integration, etc set up to catch these sort of issues, so it's hard to offer a great experience) but the suggestions for disabling MKL in this case make sense. Closing since that seems like a fix.

**Closed by petewarden** 2019-02-22 23:26 UTC
Labels: TF 1.12, stat:awaiting tensorflower, type:build/install
