### ISSUE TITLE
'Math Processing Error' in web docs

### ISSUE THREAD

**Issue by yazabaza** [tensorflow/tensorflow#1499] opened 2016-03-14 22:16 UTC
See; tensorflow.org/versions/r0.7/tutorials/mnist/beginners/index.html  --> Training section. "Math Processing Error" appears in multiple places in page. Used OSX / Safari, Firefox, and Chrome.  Screen shot attached.
![screen shot 2016-03-14 at 3 15 14 pm](https://cloud.githubusercontent.com/assets/351870/13761735/a3f2a3b6-e9f7-11e5-9373-5b7eb37fd534.png)

**Comment by mrry** [comment] 2016-03-14 22:45
It looks like the encoded apostrophes are causing problems for rendering on OS X.

**Comment by danmane** [comment] 2016-03-18 21:36
Closing this as a duplicate of https://github.com/tensorflow/tensorflow/issues/1377.
We're working on a fix and it should be in soon - as a workaround for now, you can right click on the equation and select the SVG renderer.

**Closed by danmane** 2016-03-18 21:36 UTC
Labels: docs
