### ISSUE TITLE
something wrong with  tf.image.draw_bounding_boxes

### ISSUE THREAD

**Issue by zyj183247166** [tensorflow/tensorflow#20434] opened 2018-06-30 04:38 UTC
```
import matplotlib.pyplot as plt
import tensorflow as tf   
import numpy as np
image_raw_data = tf.gfile.FastGFile("./datasets/cat.jpg",'rb').read()

with tf.Session() as sess:
    img_data = tf.image.decode_jpeg(image_raw_data)
    boxes = tf.constant([[[0.05, 0.05, 0.9, 0.7], [0.3, 0.4, 0.5, 0.6]]])
    batched = tf.expand_dims(tf.image.convert_image_dtype(img_data, tf.float32), 0)
    image_with_box = tf.image.draw_bounding_boxes(batched, boxes)
    #print (image_with_box[0].eval())
    plt.imshow(image_with_box[0].eval()),plt.title("result")
    plt.show()

```
绘制的结果是：
![image](https://user-images.githubusercontent.com/7501074/42121467-536e4792-7c62-11e8-92da-040141d562d3.png)
no matter in windows or linux, it get the same result. i think it is not the issue of the version of tensorflow and the environment, but something very amazing which i do not know. 
Who can help me? Thanks very much

**Comment by tensorflowbutler** [comment] 2018-06-30 12:33
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zyj183247166** [comment] 2018-07-02 00:59
OS Platform and Distribution：windows10
TensorFlow installed from：using anacond3 and pip to install tensorflow1.8.0 version.
cuda version 9.0 cudnn.

reproducing my code is very easy. just run it. @tensorflowbutler

**Comment by drpngx** [comment] 2018-07-23 16:54
The first box appears to be OK. What happens if you draw the second box only?

**Comment by tensorflowbutler** [comment] 2018-08-07 19:03
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-06 18:55
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-21 19:01
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by XingBin111** [comment] 2018-09-25 09:42
I have the same problems as yours, have you solved your problems?

**Comment by tensorflowbutler** [comment] 2018-10-10 12:40
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-25 12:40
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-10-26 21:10
Closing due to staleness. Please use the latest version for TensorFlow and test again. Feel free to open a new issue if it still persists. Thanks!

**Closed by ymodak** 2018-10-26 21:10 UTC
Labels: stat:awaiting response

**Comment by LlewynWan** [comment] 2018-12-07 07:11
I have the same problem. There are always some lines that are missing.
Also, I found this function extremely memory-consuming.
