### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by sjuvekar** [tensorflow/tensorflow#6] opened 2015-11-09 16:22 UTC
Is there any plan to include caffe-like pre-trained models to use for predictions?

**Comment by raingo** [comment] 2015-11-09 16:38
+1

**Comment by petewarden** [comment] 2015-11-09 19:45
You can find one pre-trained network as part of the Android example, at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/assets/tensorflow_inception_graph.pb
This implements a version of the Inception architecture for Imagenet classification.

**Comment by sjuvekar** [comment] 2015-11-09 19:48
:thumbsup:

**Comment by vrv** [comment] 2015-11-09 23:02
Reopening to de-dupe future requests for this

**Comment by ry** [comment] 2015-11-14 06:31
I converted the VGG-16 caffemodel to TensorFlow https://github.com/ry/tensorflow-vgg16 which might be helpful for a generalized script

**Comment by AshishBora** [comment] 2015-12-13 12:48
The link to pretrained model of inception for imagenet seems broken
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/assets/tensorflow_inception_graph.pb

**Comment by petewarden** [comment] 2015-12-13 20:20
This is working as expected. We've moved the model out of the source repo, but it's available for separate download. See the android example README for the latest instructions:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md
Currently the link is https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip but the README will hold the most up-to-date location going forward.

**Comment by Jin-Yu** [comment] 2015-12-24 07:55
How to generate pre-trained model like "tensorflow_inception_graph.pb". I trained the cifar using the python API. and I want to predict on Android devices. I had build the computation graph using `tf.train.write_graph()`, but how to restore the parameters by C++ API

**Comment by martinwicke** [comment] 2016-04-15 16:35
The inception model checkpoint is downloadable (and we have examples using it for classification and deepdream), and more models are being added to https://github.com/tensorflow/models. Closing this.

**Closed by martinwicke** 2016-04-15 16:35 UTC

**Comment by vodp** [comment] 2016-05-12 23:53
I found that the file size of https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip is very small, ~50MB. The Inception v3 model in tensorflow/tensorflow/examples/label_image/data/inception_dec_2015.zip is rather larger ~100MB but still portable on mobile devices. However when I tried to convert VGG-16 models into .pb file, it cost ~500MB. Is that the architecture of Inception is more superior than VGG in term of portability?

**Comment by martinwicke** [comment] 2016-05-13 00:17
@shlens, can you comment on this?

**Comment by vodp** [comment] 2016-05-13 11:58
@martinwicke I think my guess is right. I tried to freeze the inception-v1 (GoogleNet) and found it just 27MB, a half of inception-v3. This is probably due to the less number of fully connected layers used (infact just one layer in the case of inception-v1) compared to VGG-x architectures. This turns out that  inception arch is really friendly for embedding apps.

**Comment by shlens** [comment] 2016-05-13 14:47
Yes, Inception is known to be far smaller in terms of parameter count then VGG. The first version of Inception contained roughly 5M model parameters; VGG was >75M model parameters (I don't know the exact the number for VGG). As @vodp mentions, the primary reason for this difference in parameter count is due to the fact that VGG uses several large fully connected layers at the top where as Inception minimizes to just 1 layer for classification.

**Comment by jtoy** [comment] 2016-08-11 22:13
for this inceptiion5h model, anyway to see the code that it was trained with?

**Comment by pkmital** [comment] 2016-08-30 20:13
As part of our free course on [Creative Applications of Deep Learning](https://www.kadenze.com/courses/creative-applications-of-deep-learning-with-tensorflow/info), I've included code for loading pre-trained networks for inception v3,v5, vgg16, vgg face, i2v, and i2v tag: https://github.com/pkmital/CADL/tree/master/session-4/libs

**Comment by GeorgianaPetria** [comment] 2017-02-10 23:16
Is there any way to load a graph partially in tensorflow? 

I would like to be able to use the weights trained for classification, but replace the fully connected layers and retrain for regression. 

This can be done in Keras using the "by_name" option when loading a model, but I couldn't find a way to do it in tensorflow.

**Comment by petewarden** [comment] 2017-02-11 01:31
You might take a look at the TensorFlow for Poets codelab and sample code to see a similar approach to removing the final fully-connected layer:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html#0
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py

**Comment by GeorgianaPetria** [comment] 2017-02-11 22:17
Thanks @petewarden!
The code in retrain.py is very helpful!
However, since inception has 3 output layers, don't I need to retrain all the 3 outputs?
In the retrain.py code a new layer is added on top of the bottleneck 'pool_3', but won't my regression be affected by not replacing all the outputs?

**Comment by ProGamerGov** [comment] 2017-05-17 01:50
The inception5h model doesn't look like it can be used for classification or transfer learning, because it is missing the required layers: https://stackoverflow.com/questions/42003846/retraining-inception5h-model-from-tensorflow-android-camera-demo

**Comment by astrung** [comment] 2017-05-20 09:55
pls check answers and comments on stackoverflow link @ProGamerGov

**Comment by Charles808** [comment] 2017-05-24 07:30
@GeorgianaPetria Hi ! I also want to add regression to the current inception v3 model.
if you already did it. Do you have any useful clue for it ?

Thank you b4.

**Comment by rish321** [comment] 2017-12-23 15:21
Hi guys, is there any pre trained model file for person identification in tf using inception? Re-training isn't working for me and I need to use model file in my Android project.

**Comment by mrgloom** [comment] 2019-05-26 00:50
How to see content of `http://download.tensorflow.org/models/` ?
