### ISSUE TITLE
Converting a keras Sequential CNN to estimator and training it removes all layers, then crashes for want of layers

### ISSUE THREAD

**Issue by haemaenpaa** [tensorflow/tensorflow#25459] opened 2019-02-02 16:54 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): ('v1.12.0-0-ga6d8ffae09', '1.12.0')
- Python version: 2.7.15rc1
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: Not installed
- GPU model and memory: GeForce GTX 1050 Ti, 4GB

**Describe the current behavior**

This issue was also mentioned in #21778, but I believe this warrants an issue of its own.

I ran into this problem trying tho make a CNN using the `fashion_mnist` dataset. Instead of training the model, invoking `train` on the model seems to drop all the layers of the original model, and then crash because there are no layers. 

The example below has this output:

````
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp_l6v51cf
[<tensorflow.python.keras.layers.core.Reshape object at 0x7fcb25244a90>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7fcb07f670f0>, <tensorflow.python.keras.layers.core.Flatten object at 0x7fcb07f7fa20>, <tensorflow.python.keras.layers.core.Dense object at 0x7fcb07f7fb00>]
WARNING:tensorflow:From /home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[]
```` 

**Describe the expected behavior**
I would expect `train` to train the model without emptying the `layers`-array. Also, the deprecation warning probably shouldn't be there either.

**Code to reproduce the issue**
````
import numpy as np
import tensorflow as tf
from tensorflow import keras

network = keras.Sequential([
            keras.layers.Reshape((10, 10, 1)),
            keras.layers.Conv2D(filters=8, kernel_size=(4, 4), activation=tf.nn.elu),
            keras.layers.Flatten(),
            keras.layers.Dense(1, activation=tf.nn.relu)
        ])

network.compile(optimizer=tf.keras.optimizers.SGD(lr=0.0001, momentum=0.9),
                loss='categorical_crossentropy',
                metric='accuracy')

estimator = tf.keras.estimator.model_to_estimator(keras_model=network)

train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x=np.random.rand(10, 100),
        y=np.random.rand(10, 1),
        num_epochs=1,
        shuffle=False)

print(network.layers)

try:
    estimator.train(input_fn=train_input_fn, steps=10)
except:
    print(network.layers)

````

**Other info / logs**
Without the try/except, the error thrown is 

````
Traceback (most recent call last):
  File "/home/heikki/Koodaus/python_sketches/Estimator.py", line 26, in <module>
    estimator.train(input_fn=train_input_fn, steps=10)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py", line 278, in model_fn
    labels)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py", line 201, in _clone_and_build_model
    optimizer_iterations=global_step)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 448, in clone_and_build_model
    _in_place_subclassed_model_reset(clone)
  File "/home/heikki/Koodaus/python_sketches/venv/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 318, in _in_place_subclassed_model_reset
    name = layers_to_names[layer]
KeyError: <tensorflow.python.keras.layers.core.Reshape object at 0x7fde28e5ca90>
````

**Comment by ymodak** [comment] 2019-02-04 21:58
I was able to reproduce your error message in TF 1.12.0
However using TF 1.13.rc0 gave more clear error message as below:
```ERROR:tensorflow:Model diverged with loss = NaN.```
By solving this error message I was able to use ```train``` to train the model.

**Comment by haemaenpaa** [comment] 2019-02-05 20:52
How does one solve that error? I tried changing the loss function to `tf.losses.mean_squared_error`, but that didn't change the result on 1.12.0.

**Comment by ymodak** [comment] 2019-02-05 21:40
The error arises due to the assignment of ```x``` ```y```` args to ```tf.estimator.inputs.numpy_input_fn``` . If you rerun the code snippet as is multiple times it should pass at next try. I see that currently it is random assignment to x, y which leads to model diverging in some runs.

**Comment by haemaenpaa** [comment] 2019-02-10 10:49
I see. I tried to change the code to this:

````
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

input_height = test_images.shape[1]
input_width = test_images.shape[2]
network = keras.Sequential([
    keras.layers.Reshape((input_height, input_width, 1)),
    keras.layers.Conv2D(filters=8, kernel_size=(4, 4), activation=tf.nn.elu),
            keras.layers.Flatten(),
            keras.layers.Dense(10, activation=tf.nn.relu)
        ])

network.compile(optimizer=tf.keras.optimizers.SGD(lr=0.00001, momentum=0.9),
                loss=tf.losses.mean_squared_error,
                metric='accuracy')

estimator = tf.keras.estimator.model_to_estimator(keras_model=network)

train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x=test_images,
        y=test_labels,
        num_epochs=1,
        shuffle=False)

print(network.layers)

try:
    estimator.train(input_fn=train_input_fn, steps=10)
except:
    print(network.layers)
````

But the behavior repeats, including emptying the network's layers.

**Comment by ymodak** [comment] 2019-03-09 00:21
Apologies for the delay in response. The new version of code snippet you provided throws a different error in TF 1.13.1 Can you please confirm? Thanks!

**Comment by haemaenpaa** [comment] 2019-03-10 13:16
The error I'm getting now is this:

```
Traceback (most recent call last):
  File "Estimator.py", line 31, in <module>
    estimator.train(input_fn=train_input_fn, steps=10)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/keras.py", line 278, in model_fn
    labels)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/keras.py", line 201, in _clone_and_build_model
    optimizer_iterations=global_step)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/keras/models.py", line 511, in clone_and_build_model
    target_tensors=target_tensors)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 449, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 647, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 669, in mean_squared_error
    predictions.get_shape().assert_is_compatible_with(labels.get_shape())
  File "/home/heikki/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1023, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?, 10) and (?,) are incompatible
```

The layers, however, seem to be intact now, so I'm willing to call this fixed.

**Comment by ymodak** [comment] 2019-03-11 17:46
Closing this issue since the original error has now been resolved. Feel free to post a new issue if have further problem. Thanks!

**Closed by ymodak** 2019-03-11 17:46 UTC
Labels: comp:keras, type:support
