### ISSUE TITLE
Can't install tensorflow successfully

### ISSUE THREAD

**Issue by Mulf** [tensorflow/tensorflow#9038] opened 2017-04-07 06:27 UTC
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: No
- *TensorFlow installed from (source or binary)?*: binary
- *TensorFlow version*:1.0
- *Bazel version (if compiling from source)*: 
- *CUDA/cuDNN version*:NA
- *GPU Model and Memory*:HD5500 /  intrel core i5-5200
- *Exact command to reproduce*:  NA

### Describe the problem clearly
I try to install tensorflow with Anaconda in my win10 following the instructions on [install_windows]https://www.tensorflow.org/install/install_windows).  When i move to step4:
I type the code
 `pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl`

it fails and shows
`tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.`

How can I fix it?

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by mrnameless123** [comment] 2017-04-07 06:30
have u tried conda install, and granted administration mode

**Comment by Carmezim** [comment] 2017-04-07 12:05
@Mulf Hi, sorry you're facing issues. Could you please share your Python version?

**Comment by sibyjackgrove** [comment] 2017-04-07 16:03
I have faced the same problem when I tried to install TensorFlow with Anaconda 4.3 (the latest version) which uses Python 3.6. Unfortunately this Python version is not supported by TensorFlow on Windows. I think the easiest solution is to uninstall Anaconda 4.3 and install Anaconda 4.2. (from https://repo.continuum.io/archive/index.html) Then install TensorFlow again. It worked for me. Hope it helpls

**Comment by Mulf** [comment] 2017-04-07 17:00
My version is 3.6

After I type Python,  the command window gives me:
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41)
[MSC v.1900 64 bit (AMD64)] on win32

2017-04-07 12:05 GMT-04:00 Siby Jose Plathottam <notifications@github.com>:

**Comment by Carmezim** [comment] 2017-04-07 17:22
@Mulf as you can observe, the wheel you are trying to download TensorFlow for is compatible with Python 3.5 (`cp35-cp35m-win`). There are a couple of options:

1. Create a conda environment for Python=3.5 and install TF on it
2. Download a previous version of Anaconda with Python 3.5
3. Build from source

The simplest is the first but you may choose what works best for you.
If you have any further doubts feel free to ask. If not this issue can be closed.

**Comment by asimshankar** [comment] 2017-04-07 17:41
Yup, TensorFlow on Windows does not support Python 3.6 yet (see #6999 for details).
You'll need a Python 3.5 environment.

Closing this out as a duplicate of #6999.

Thanks!

**Closed by asimshankar** 2017-04-07 17:41 UTC
