### ISSUE TITLE
Windows Installation?

### ISSUE THREAD

**Issue by hugman** [tensorflow/tensorflow#122] opened 2015-11-11 07:27 UTC
Is it possible to install TF in windows environment?
I checked "pip install" is not supported in windows. 

Any plan for it?

**Comment by nowrock** [comment] 2015-11-11 07:39
I have the same question.

**Comment by icoxfog417** [comment] 2015-11-11 08:09
Please refer #17.

**Comment by mrry** [comment] 2015-11-11 15:41
Closing this as a duplicate of #17 - please feel free to continue the discussion there.

**Closed by mrry** 2015-11-11 15:41 UTC

**Comment by zkl99999** [comment] 2016-02-29 14:06
C:\Users\\Desktop>docker run -it b.gcr.io/tensorflow/tensorflow

Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally

docker: Error response from daemon: unable to ping registry endpoint https://b.g
cr.io/v0/
v2 ping attempt failed with error: Get https://b.gcr.io/v2/: dial tcp 64.233.188
.82:443: i/o timeout
