### ISSUE TITLE
Beam Search

### ISSUE THREAD

**Issue by cinjon** [tensorflow/tensorflow#214] opened 2015-11-14 04:42 UTC
Is there anything in place supporting this yet? Wanted to ask before I implement my own.

**Comment by ebrevdo** [comment] 2015-11-15 01:45
I'd probably encourage you to write a C++-based beam search instead of trying to do it with graph ops.  That said, we will likely provide some sort of specialized self-contained beam search for CTC with the CTC loss.  Additionally there's a PriorityQueue in the works which, when completed, will provide the ability to sort groups of Tensors.  Not sure if this would help you.  Another good project to look at for implementing a beam search is [OpenFST](http://www.openfst.org/), which was coincidentally partly developed within Google Research :)

**Comment by evanthebouncy** [comment] 2016-02-25 22:19
so what's the verdict? I am using the python API now, should I do it in python?

i.e. is beam-search even possible in the graph ops, if it's not possible then clearly there's no option, but if it is possible is the issue of being inefficient or more difficult to implement than its worth?

**Comment by cinjon** [comment] 2016-02-25 22:59
@evanthebouncy, see #654

**Comment by ebrevdo** [comment] 2016-02-26 19:12
Marking this as a duplicate of #654  cause it seems like that's what you want to do.

**Closed by ebrevdo** 2016-02-26 19:12 UTC

**Comment by zer0n** [comment] 2016-05-27 06:18
@ebrevdo Can you provide a pointer to how to do beam search using the C++ API?

**Comment by ebrevdo** [comment] 2016-06-01 05:46
Do you mean CTC beam search specifically?

**Comment by lingz** [comment] 2016-06-26 10:01
@ebrevdo I'd like to see an example of a CTC beam search

**Comment by hellbago** [comment] 2018-02-18 18:52
I've frozen a model that has as last node ctc beam search. Now I want to use this .pb file in C++ but I don't know exactly how to process the output tensor in order to get the final sequence of labels. Anyone with previous experience in this kind of issue?
