### ISSUE TITLE
For loop as 'unknown type' Tensorflow dimensions

### ISSUE THREAD

**Issue by HeewonChung92** [tensorflow/tensorflow#29947] opened 2019-06-19 06:51 UTC
I want to use the shape (size) of a tf.where for the bound of a for-loop using Tensorflow in Pycharm. 
However, when I try to do this, 
I get the error: **'Tensor' object cannot be interpreted as an integer.**

How can I solve this problem?
**How can I get the size of idxCut to use a for-loop?**

**Development contents.**
1. Find the index (idxCut) corresponding to the threshold in the data.
2. Check whether data corresponding to idxCut is TPR.

I want to find the TPR (Turning Point Ratio) about idxCut in the data using a for-loop.
I used a for-loop to obtain the TPR between idx, idx-1 and idx + 1.
I want to find data[idx] is higher than the others data[idx-1, idx+1].

Here's my code:

> def funCalculate(data):
>     ### Cut-off Threshold
>     idxCut = tf.where(data > cutoff)
>     idxCut = tf.squeeze(idxCut)   # The size of idxCut is always variable.
> 
>     ### Compute by the size of idxCut
>     valueCut = []
>     for ii in range(0, tf.shape(idxCut)[0]):
>         v1 = tf.where(data[idxCut[ii]] > data[idxCut[ii] - 1], 1, 0)
>         v2 = tf.where(data[idxCut[ii]] > data[idxCut[ii] + 1], 1, 0)
>         v3 = tf.where(v1 + v2 > 1, 1, 0)
>         valueCut.append(v3)
>     return valueCut

**Comment by gadagashwini** [comment] 2019-06-20 06:18
@HeewonChung92 Please provide details TensorFlow version. Also, did you compile from source or install a binary? In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-06-26 04:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-26 04:54 UTC
Labels: comp:ops, stat:awaiting response, type:support
