### ISSUE TITLE
[tf.keras] predict_generator stuck with using use_multiprocessing=True

### ISSUE THREAD

**Issue by jashshah** [tensorflow/tensorflow#30306] opened 2019-07-02 11:20 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.14
- Python version: 3.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla P100 - 16280MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I use `model.predict_generator` with `use_multiprocessing=True` the code gets stuck.
**Describe the expected behavior**
Ideally the code should not get stuck and all cores should be used for predictions.
**Code to reproduce the issue**

```
from tensorflow.keras.layers import Conv3D, MaxPool3D, Flatten, Dense
from tensorflow.keras.layers import Dropout, Input, BatchNormalization
from tensorflow.keras.layers import AvgPool3D
from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import Sequence
from tensorflow.keras import callbacks
from tensorflow.keras.layers import Concatenate, Add
from tensorflow.keras.estimator import model_to_estimator
from tensorflow.keras.utils import multi_gpu_model
from tensorflow.keras.utils import Sequence
import tensorflow as tf


def build_model(input_shape=(128, 128, 50, 1), n_class=3, multilabel=False):
   
    def spatial_reduction_block(inputs, block_name):
        filters = inputs._shape_as_list()[-1]
        with tf.name_scope(block_name):
            maxpool = MaxPool3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='same')(inputs)
            conv_a_0 = Conv3D(filters=filters//4, kernel_size=(3, 3, 3), strides=(2, 2, 2), padding='same', activation='relu')(inputs)
            conv_b_0 = Conv3D(filters=filters, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(inputs)
            conv_c_0 = Conv3D(filters=filters, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(inputs)

            conv_b_1 = Conv3D(filters=(5*filters)//16, kernel_size=(3, 3, 3), strides=(2, 2, 2), 
                              padding='same', activation='relu')(conv_b_0)
            conv_c_1 = Conv3D(filters=(5*filters)//16, kernel_size=(3, 3, 3), strides=(1, 1, 1), 
                              padding='same', activation='relu')(conv_c_0)
            conv_c_2 = Conv3D(filters=(7*filters)//16, kernel_size=(3, 3, 3), strides=(2, 2, 2), 
                              padding='same', activation='relu')(conv_c_1)

            concat_output = Concatenate()([maxpool, conv_a_0, conv_b_1, conv_c_2])

        return concat_output

    def residual_convolution_block(inputs, block_name):
        filters = inputs._shape_as_list()[-1]
        with tf.name_scope(block_name):
            conv_a_0 = Conv3D(filters=filters//2, kernel_size=(3, 3, 3), strides=(1, 1, 1), padding='same', activation='relu')(inputs)
            conv_b_0 = Conv3D(filters=filters//2, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(inputs)
            conv_c_0 = Conv3D(filters=filters//2, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(inputs)

            conv_b_1 = Conv3D(filters=filters//2, kernel_size=(3, 3, 3), strides=(1, 1, 1), padding='same', activation='relu')(conv_b_0)
            conv_c_1 = Conv3D(filters=filters//2, kernel_size=(3, 3, 3), strides=(1, 1, 1), padding='same', activation='relu')(conv_c_0)
            conv_c_2 = Conv3D(filters=filters//2, kernel_size=(3, 3, 3), strides=(1, 1, 1), padding='same', activation='relu')(conv_c_1)

            concat_output = Concatenate()([conv_a_0, conv_b_1, conv_c_2])

            conv_d_0 = Conv3D(filters=filters, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(concat_output)

            add_1 = Add()([conv_d_0, inputs])

        return add_1
    
    if not multilabel:
        activation_fn = 'softmax'
    else:
        activation_fn = 'sigmoid'
    
    inputs = Input(shape=input_shape, name='inputs')
    conv_1 = Conv3D(filters=64, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(inputs)
    spatial_reduction_block_1 = spatial_reduction_block(conv_1, 'spatial_reduction_block_1')
    residual_convolution_block_1 = residual_convolution_block(spatial_reduction_block_1, 'residual_convolution_block_1')
    spatial_reduction_block_2 = spatial_reduction_block(residual_convolution_block_1, 'spatial_reduction_block_2')
    residual_convolution_block_2 = residual_convolution_block(spatial_reduction_block_2, 'residual_convolution_block_2')
    conv_2 = Conv3D(filters=512, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(residual_convolution_block_2)
    maxpool_1 = MaxPool3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid')(conv_2)
    conv_3 = Conv3D(filters=1024, kernel_size=(1, 1, 1), strides=(1, 1, 1), padding='same', activation='relu')(maxpool_1)
    maxpool_2 = MaxPool3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid')(conv_3)
    flatten = Flatten()(maxpool_2)
    dropout_1 = Dropout(rate=0.2)(flatten)
    dense_1 = Dense(512, activation='sigmoid')(dropout_1)
    dropout_2 = Dropout(rate=0.2)(dense_1)
    outputs = Dense(n_class, activation=activation_fn, name='outputs')(dropout_2)
    
    model = Model(inputs=inputs, outputs=outputs)
    return model

model = build_model((128,128,50, 1), 3, False)

class mygenerator(Sequence):
    def __init__(self, x_set, y_set, batch_size, augment=False):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size
        self.augment = augment
    
    def __len__(self):
        return int(np.ceil(len(self.x) / float(self.batch_size)))
    
    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]
        
        x = [read_image(filename, self.augment) for filename in batch_x] # read a numpy array named filename
        y = [read_label(label) for label in batch_y]
        
        return np.array(x), np.array(y)

test_generator = mygenerator(X_TEST, Y_TEST, eval_batch_size, augment=False)

preds = model.predict_generator(test_generator, verbose=1, use_multiprocessing=True, steps=eval_steps)

```
**Other info / logs**
NA

**Comment by rmothukuru** [comment] 2019-07-04 13:04
@jashshah ,
When trying to reproduce the issue, NameError: name 'model' is not defined. Can you please share the complete reproducible code.

**Comment by jashshah** [comment] 2019-07-05 06:28
@rmothukuru I have shared the code to create the model. Do you want the code used to train the model as well?

**Comment by rmothukuru** [comment] 2019-07-05 10:04
@jashshah ,
Thank you for the code. When I tried executing it, I am getting the error,
`ValueError: Input 0 of layer conv3d is incompatible with the layer: expected ndim=5, found ndim=4. Full shape received: [None, 128, 128, 50]`.

**Comment by jashshah** [comment] 2019-07-05 10:47
@rmothukuru My apologies for the error. I have updated the code.

**Comment by rmothukuru** [comment] 2019-07-08 10:47
@jashshah ,
Can you please confirm if you are getting below mentioned Exception when the execution is stuck.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 742, in _run
    sequence = list(range(len(self.sequence)))
  File "<ipython-input-1-f6db4c2102ca>", line 93, in __len__
    return int(np.ceil(len(self.x) / float(self.batch_size)))
TypeError: object of type 'int' has no len()
```

**Comment by jashshah** [comment] 2019-07-08 12:53
@rmothukuru I am not getting any sort of error. The execution just remains stuck with 0% volatile GPU-Utilization even though the GPU memory usage is around 15GB.

**Comment by jashshah** [comment] 2019-07-08 20:14
@rmothukuru is there any work around for now while the bug is fixed? I am unable to speed up inference since I cannot use multiprocessing.

**Comment by ymodak** [comment] 2019-07-17 20:55
@jashshah The code snippet you provided is incomplete. Can you please update it and also as a sanity check for gpu config., Can you please try to execute your code in [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true) using gpu (clcik edit notebook settings and select gpu from the drop down). Thanks!

**Comment by jashshah** [comment] 2019-07-18 08:32
@ymodak can you tell me where it is incomplete? I believe @rmothukuru was able to reproduce the issue. The only thing that I cannot provide you with is the data since that is proprietary.

**Comment by rmothukuru** [comment] 2019-07-18 09:25
@ymodak ,
Sorry for the confusion. Reproduced the code in Google Colab with GPU as Runtime, with TF Version, 1.14 and with Dummy Data. This is the [Gist](https://colab.sandbox.google.com/drive/1BmaVlJHPX9dsJ1QNpkZKbbZkgWBvdaLR#scrollTo=VjoPXkL5SNbN).

Execution was stuck as explained by @jashshah,  with the exception shown below, as I might have used X_TEST and Y_TEST as simple integers. Thanks.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 742, in _run
    sequence = list(range(len(self.sequence)))
  File "<ipython-input-10-c2c93000e6bc>", line 10, in __len__
    return int(np.ceil(len(self.x) / float(self.batch_size)))
TypeError: object of type 'int' has no len()
```

**Comment by ymodak** [comment] 2019-08-02 00:33
@jashshah Apologies for the delay in response. I believe ```use_multiprocessing``` argument is irrelevant in this case, since the code snippet fails with same error even after setting it to false.
Were you able to execute it by setting it to false?

**Comment by jashshah** [comment] 2019-08-02 06:14
@ymodak I am able to execute it when `use_multiprocessing` argument is set to `False`.

**Comment by bananabowl** [comment] 2019-08-22 23:09
My guess is that a deadlock occurred within keras.utils.OrderedEnqueuer (which is used when the generator is a sequence). Please confirm if you experience the same stall with fit_generator or evaluate_generator. Also please check if keras.experimental.terminate_keras_multiprocessing_pools returns any useful errors: https://www.tensorflow.org/api_docs/python/tf/keras/experimental/terminate_keras_multiprocessing_pools

Thanks!

**Comment by robieta** [comment] 2019-09-13 12:05
Closing as there isn't enough information to reproduce the issue. Feel free to re-open if you have a run-able colab.

**Closed by robieta** 2019-09-13 12:05 UTC
Labels: comp:keras, type:bug

**Comment by hbellafkir** [comment] 2020-07-06 08:35
@rmothukuru  did you solved the problem? I'm getting the same error
