### ISSUE TITLE
TF 1.4 build_all_android.sh fails with nsync.a

### ISSUE THREAD

**Issue by eaigner** [tensorflow/tensorflow#14186] opened 2017-11-02 13:46 UTC
Running

    NDK_ROOT="$HOME/Library/Android/sdk/ndk-bundle" bash $MAKEFILE_DIR/build_all_android.sh

results in this error

```
/Users/era/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: malformed archive header name at 8
/Users/era/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: malformed archive header name at 8
/Users/era/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: attempt to map 60 bytes at offset 67800 exceeds size of file; the file may be corrupt
collect2: error: ld returned 1 exit status
make: *** [.../tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
```

NDK version 15c, Android Studio 3.0, macOS High Sierra 10.13.1

**Comment by eaigner** [comment] 2017-11-03 08:30
Also fails on `master`

**Comment by jart** [comment] 2017-11-06 17:49
Searching the Internet, this type of error seems to happen quite rarely in general. Could you check if that nsync.a file exists? See https://github.com/openframeworks/openFrameworks/issues/4869#issuecomment-186440569 Were those files built with a different compiler? See [this question](https://stackoverflow.com/questions/13508332/how-to-import-non-standard-library-packages-use-gccgo).

**Comment by eaigner** [comment] 2017-11-10 07:57
`nsync.a` exists. Everything was compiled with the NDK, not with a different compiler (unless one of the build scripts does that internal).

As I said, I only run the build normally with setting the `NDK_ROOT`. That's it.

    NDK_ROOT="$HOME/Library/Android/sdk/ndk-bundle" bash $MAKEFILE_DIR/build_all_android.sh

**Comment by umangmehta12** [comment] 2017-11-16 19:08
I am also facing the same issue. Using the instructions on [README for Makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#android). 

Configuration:
MacOS Sierra 10.12.6
Android NDK r15c

```android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: malformed archive header name at 8
android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: malformed archive header name at 8
android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: tensorflow/contrib/makefile/downloads/nsync/builds/armeabi-v7a.android.c++11/nsync.a: attempt to map 60 bytes at offset 68372 exceeds size of file; the file may be corrupt```

**Comment by sujitpoudel123** [comment] 2017-12-06 17:28
Any update on this issue? I've exact same issue and `build_all_android.sh` never completes. I've tried changing NDK versions, tweaking some parts of the makefile, but this still persists.

**Comment by umangmehta12** [comment] 2017-12-06 21:07
I didn't encounter issues when building for `arm64-v8a`.

**Comment by sujitpoudel123** [comment] 2017-12-07 17:18
@keyongyu That brings to about 50 different
`error: invalid argument '-std=c++11' not allowed with 'C/ObjC'`

**Comment by sujitpoudel123** [comment] 2017-12-07 22:32
I was basically able to remove the error after removing a particular nsync build folder corresponding to the architecture I was trying to build. For example, I had problem with armeabi and so, I removed `./tensorflow/contrib/makefile/downloads/nsync/builds/armeabi.android.c++11` folder and it built fine after that for that arch

**Comment by eaigner** [comment] 2017-12-13 12:27
I would be delighted if Google just for ONCE released a TF version that doesn't break anything on mobile. TF has been a non-stop self patching project for me on mobile since 1.0. Every new release just breaks about everything.

**Comment by eaigner** [comment] 2017-12-15 14:05
Can confirm @keyongyu s solution does work. Overriding `AR` resolves this.

**Comment by Cpruce** [comment] 2017-12-28 05:24
Thanks @keyongyu. The fix works for me too

**Comment by umangmehta12** [comment] 2017-12-29 17:37
@drpngx @jart when can we expected to see this be promoted to master?

**Comment by drpngx** [comment] 2017-12-29 23:27
feel free to submit a PR and we can take a look

**Comment by tensorflowbutler** [comment] 2018-01-13 18:55
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by AngryPowman** [comment] 2018-02-27 14:49
The same issue, any patches with it?

**Comment by cosmos180** [comment] 2018-03-15 12:12
This is another method I have confirmed.

**Comment by joelteply** [comment] 2018-03-26 16:45
So far the best strategy is to build several times and comment out various sections of the build, which allows me to get the nsync built, then use it in the tensorflow make call. I think OSX is relatively hosed at the moment. If I come up with a fix I will post it or create a pull request. 

When are we moving to CMake?

**Comment by Hwangzhiyoung** [comment] 2018-05-10 03:29
thansk! @keyongyu I follow your step.it works!
first,I compile the build_all_android.sh,then I got the same error. then I remove nsync builds armeabi-v7a.android.c++11 folder ,update the compile_nsync.sh,  cover build_all_android.sh about dowloading and front of nsync. Finally compile build_all_android.sh again.here are my bash.
sudo NDK_ROOT=/Users/a1707001/android-ndk-r14b sh tensorflow/contrib/makefile/build_all_android.sh
btw my tensorflow version is v1.4.0 ,ndk version is r14b.

**Comment by zh794390558** [comment] 2018-09-21 03:31
@drpngx Can you give a table of tf version and NDK version, when using tf.contrib.makefile?

**Comment by mohantym** [comment] 2021-09-10 07:57
Hi @eaigner ,
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Closed** 2021-09-24 09:24 UTC
Labels: stat:awaiting response, type:build/install, stalled
