### ISSUE TITLE
'tensorflow' has no attribute 'enable_eager_execution'

### ISSUE THREAD

**Issue by howareyoudoing** [tensorflow/tensorflow#25808] opened 2019-02-17 08:11 UTC
**System information**
-Google Colab 
-GPU
-Python 3
-Tensorflow tf-nightly-2.0-preview

When I write the code:
  `from __future__ import absolute_import, division, print_function`
  `!pip install tf-nightly-2.0-preview`
  `import tensorflow as tf`
  `tf.enable_eager_execution()`
It gives me the error **AttributeError: 'module' object has no attribute 'enable_eager_execution'**

whereas when I simply run the code as:
  `from __future__ import absolute_import, division, print_function`
  `!pip install tf-nightly-2.0-preview`
  `import tensorflow as tf`
  `tf.executing_eagerly()` 
It returns **'True'**, which means that eager execution is working by default without even enabling it before.
If I proceed without using tf.enable_eager_execution() in this collab tutorial [https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/image_captioning.ipynb#scrollTo=U8l4RJ0XRPEm](url)
In the cell Caching the features extracted from InceptionV3, 
the last line with "np.save(path_of_feature, bf.numpy())" gives me an error saying **"Tensor has no attribute called numpy()"**
If I see the type() of batch_features in the line:
`batch_features = image_features_extract_model(img)` line is returning a graph tensor, instead of an eager tensor. It's not supposed to do that. Does this means that eager execution is not yet enabled or is this a bug.

**Comment by ParasharaRamesh** [comment] 2019-02-19 14:43
hey @howareyoudoing  even i am facing the same error while following this colab tutorial.
Somone has already raised this issue precisely and someone from the tensorflow team has taken up this  issue to resolve so you could probably watch this issue page for now..

https://github.com/tensorflow/tensorflow/issues/25731

**Comment by howareyoudoing** [comment] 2019-02-19 16:55
@ParasharaRamesh Thanks for providing the link.

**Comment by howareyoudoing** [comment] 2019-02-19 16:55
Thanks for providing the link.

**Comment by ymodak** [comment] 2019-02-20 21:08
Closing this issue since its a duplicate of #25731.
Lets track it there. Thanks!

**Closed by ymodak** 2019-02-20 21:08 UTC
