### ISSUE TITLE
Image load error

### ISSUE THREAD

**Issue by GaranceRichard** [tensorflow/tensorflow#32945] opened 2019-10-01 08:19 UTC
I'm using tf: '2.0.0-rc1'

In the process to load image, you said

for image, label in labeled_ds.take(1):
  print("Image shape: ", image.numpy().shape)
  print("Label: ", label.numpy())

InvalidArgumentError: {{function_node __inference_Dataset_map_process_path_378}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync]

and then:
train_ds = prepare_for_training(labeled_ds)

image_batch, label_batch = next(iter(train_ds))

InvalidArgumentError: {{function_node __inference_Dataset_map_process_path_378}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync]

some kind of problem...

**Comment by gowthamkpr** [comment] 2019-10-02 17:42
@GaranceRichard Can you please provide the github gist of this issue as its too vauge for us right noew to look into it. Thanks!

**Comment by ymodak** [comment] 2019-10-02 17:58
Duplicate #32908

**Comment by gowthamkpr** [comment] 2019-10-02 18:05
I was unsuccessful in reproducing it using tensorflow 2rc2([gist](https://colab.sandbox.google.com/gist/gowthamkpr/0ffa44c454f3f5d9a9e271cdfb770216/copy-of-images.ipynb)) and tensorflow  2rc1([gist](https://colab.sandbox.google.com/gist/gowthamkpr/ca59490892b25e4074fa8598d590d6b2/copy-of-images1.ipynb)). Please provide the details as mentioned above. Thanks!

**Comment by GaranceRichard** [comment] 2019-10-03 12:22
pip freeze
absl-py==0.8.0
alabaster==0.7.12
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
cloudpickle==1.2.2
colorama==0.4.1
cryptography==2.7
cycler==0.10.0
DateTime==4.3
decorator==4.4.0
defusedxml==0.6.0
docutils==0.15.2
entrypoints==0.3
gast==0.2.2
google-pasta==0.1.7
grpcio==1.23.0
h5py==2.10.0
helpdev==0.6.10
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.2
jupyter-client==5.3.3
jupyter-core==4.5.0
jupyter-tensorboard==0.1.10
Keras==2.3.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keras-radam==0.15.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.0
nbformat==4.4.0
networkx==2.3
notebook==6.0.1
numpy==1.17.2
numpydoc==0.9.1
opencv-python==4.1.1.26
opt-einsum==3.0.1
packaging==19.2
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
Pillow==6.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.9.2
psutil==5.6.3
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.14.11
PySocks==1.7.1
python-dateutil==2.8.0
pytz==2019.2
PyWavelets==1.0.3
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
QDarkStyle==2.7
QtAwesome==0.6.0
qtconsole==4.5.5
QtPy==1.9.0
requests==2.22.0
rope==0.14.0
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
sklearn==0.0
snowballstemmer==1.9.1
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==3.3.6
spyder-kernels==0.5.1
tb-nightly==1.15.0a20190806
tensorboard==2.0.0
tensorflow-gpu==2.0.0rc1
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019080601
tornado==6.0.3
traitlets==4.3.2
typed-ast==1.3.4
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
zipp==0.6.0
zope.interface==4.6.0

**Comment by GaranceRichard** [comment] 2019-10-03 12:23
what do you need more ?

**Comment by GaranceRichard** [comment] 2019-10-03 12:41
also valid with :
absl-py==0.7.1
altgraph==0.16.1
astor==0.8.0
attrs==19.1.0
auto-py-to-exe==2.6.5
backcall==0.1.0
beautifulsoup4==4.8.0
bleach==3.1.0
bottle==0.12.17
bottle-websocket==0.2.9
cffi==1.12.3
colorama==0.4.1
cx-Freeze==5.1.1
cycler==0.10.0
Cython==0.29.13
decorator==4.4.0
defusedxml==0.6.0
Eel==0.10.4
entrypoints==0.3
enum34==1.1.6
future==0.17.1
gast==0.2.2
gevent==1.4.0
gevent-websocket==0.10.1
google==2.0.2
google-pasta==0.1.7
greenlet==0.4.15
grpcio==1.22.0
h5py==2.9.0
imageio==2.5.0
imutils==0.5.2
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
jedi==0.14.0
Jinja2==2.10.1
joblib==0.13.2
json5==0.8.5
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyter-http-over-ws==0.0.6
jupyter-tensorboard==0.1.10
jupyterlab==1.1.3
jupyterlab-server==1.0.6
Keras==2.3.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keras-rectified-adam==0.9.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
mock==3.0.5
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numexpr==2.6.9
numpy==1.17.2
opencv-python==4.1.0.25
opt-einsum==3.0.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.0
pefile==2019.4.18
pickleshare==0.7.5
Pillow==6.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.8.0
pycparser==2.19
Pygments==2.4.2
PyInstaller==3.5
pyocr==0.7.2
pyparsing==2.4.0
pyrsistent==0.15.3
pytesseract==0.2.7
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32-ctypes==0.2.0
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.0.2
qtconsole==4.5.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
soupsieve==1.9.3
tables==3.5.2
tb-nightly==1.15.0a20190806
tensorboard==2.0.0
tensorflow==2.0.0rc1
tensorflow-estimator==2.0.0
tensorflow-estimator-2.0-preview==2.0.0
tensorflow-radam==0.12.0
termcolor==1.1.0
terminado==0.8.2
tesseract==0.1.3
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019080601
tornado==6.0.3
traitlets==4.3.2
virtualenv==16.7.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
whichcraft==0.6.0
widgetsnbextension==3.5.0
wrapt==1.11.2
xlrd==1.2.0
xlwt==1.3.0

**Comment by GaranceRichard** [comment] 2019-10-04 13:22
> I was unsuccessful in reproducing it using tensorflow 2rc2([gist](https://colab.sandbox.google.com/gist/gowthamkpr/0ffa44c454f3f5d9a9e271cdfb770216/copy-of-images.ipynb)) and tensorflow 2rc1([gist](https://colab.sandbox.google.com/gist/gowthamkpr/ca59490892b25e4074fa8598d590d6b2/copy-of-images1.ipynb)). Please provide the details as mentioned above. Thanks!

Did you reproduce it now ?

**Comment by GaranceRichard** [comment] 2019-10-04 13:23
> Can you please share your system configuration? Thanks!
> Duplicate #32908

Is this ok ?

**Comment by ouy160** [comment] 2019-10-07 11:49
The code error message I encountered is very similar to yours. See my https://github.com/tensorflow/tensorflow/issues/32908 for details.

**Comment by GaranceRichard** [comment] 2019-10-07 12:03
https://github.com/tensorflow/tensorflow/issues/32908#issuecomment-537329762

I'm on windows 10...

**Comment by gowthamkpr** [comment] 2019-10-11 18:22
Unable to reproduce it. @GaranceRichard

**Comment by ouy160** [comment] 2019-10-13 11:37
> Unable to reproduce it. @GaranceRichard

Can you share your pip list under the win10 version?

**Comment by GaranceRichard** [comment] 2019-10-16 08:02
> > Unable to reproduce it. @GaranceRichard
> 
> Can you share your pip list under the win10 version?

On win10 : just see above : you'll have my venv (tf gpu version) and my local (tf cpu version)

**Comment by mihaimaruseac** [comment] 2019-10-16 17:27
Can you test with 2.0.0 release?

**Comment by ouy160** [comment] 2019-10-17 02:04
> > > Unable to reproduce it. @GaranceRichard
> > 
> > 
> > Can you share your pip list under the win10 version?
> 
> On win10 : just see above : you'll have my venv (tf gpu version) and my local (tf cpu version)

Specifically, what is the version number of tensorflow you use?

**Comment by GaranceRichard** [comment] 2019-10-17 06:02
> > > > Unable to reproduce it. @GaranceRichard
> > > 
> > > 
> > > Can you share your pip list under the win10 version?
> > 
> > 
> > On win10 : just see above : you'll have my venv (tf gpu version) and my local (tf cpu version)
> 
> Specifically, what is the version number of tensorflow you use?

on cpu :  tensorflow==2.0.0rc1
on gpu : tensorflow-gpu==2.0.0rc1

**Comment by ouy160** [comment] 2019-10-17 07:17
> > > > > 无法复制。@GaranceRichard
> > > > 
> > > > 
> > > > 您可以在win10版本下共享您的点子列表吗？
> > > 
> > > 
> > > 在win10上：如上所示：您将拥有我的venv（tf gpu版本）和本地（tf cpu版本）
> > 
> > 
> > 具体来说，您使用的张量流的版本号是多少？
> 
> 在cpu上：tensorflow == 2.0.0rc1
> 在gpu上：tensorflow-gpu == 2.0.0rc1



> > > > > Unable to reproduce it. @GaranceRichard
> > > > 
> > > > 
> > > > Can you share your pip list under the win10 version?
> > > 
> > > 
> > > On win10 : just see above : you'll have my venv (tf gpu version) and my local (tf cpu version)
> > 
> > 
> > Specifically, what is the version number of tensorflow you use?
> 
> on cpu : tensorflow==2.0.0rc1
> on gpu : tensorflow-gpu==2.0.0rc1

I am sorry, I got the error code using tensorflow==2.0.0rc1. You can try running the demo code of tensorflow, https://tensorflow.google.cn/tutorials/load_data/images

**Comment by mihaimaruseac** [comment] 2019-10-17 16:17
Please switch to 2.0.0 final release as there were bug fixes between the rc and the final release.

**Comment by gowthamkpr** [comment] 2019-10-18 17:22
@GaranceRichard  @ouy160  Can you please try the recommendation above and let me know if you are able to solve your issue. Thanks

**Comment by GaranceRichard** [comment] 2019-10-22 10:03
![image](https://user-images.githubusercontent.com/29459554/67275875-c86e9080-f4c3-11e9-8267-dde40205a54a.png)
with tf final release on playing Load images collab

**Comment by GaranceRichard** [comment] 2019-10-22 10:03
![image](https://user-images.githubusercontent.com/29459554/67275957-f8b62f00-f4c3-11e9-9771-ae839db8061e.png)

**Comment by GaranceRichard** [comment] 2019-10-22 10:03
![image](https://user-images.githubusercontent.com/29459554/67275977-0370c400-f4c4-11e9-8448-61c2bd3b6ad4.png)

**Comment by ouy160** [comment] 2019-10-22 13:01
> @GaranceRichard @ouy160 Can you please try the recommendation above and let me know if you are able to solve your issue. Thanks

I am sorry, I got the same error message using tensorflow==2.0.0rc1. You can try running the demo code of tensorflow, https://tensorflow.google.cn/tutorials/load_data/images.

**Comment by mihaimaruseac** [comment] 2019-10-22 16:05
Please switch to 2.0.0 final release, @ouy160 

@GaranceRichard code snippets (using proper markdown syntax: three backticks before and after) are always better than screenshots

**Comment by ouy160** [comment] 2019-10-23 06:35
> Please switch to 2.0.0 final release, @ouy160
> 
> @GaranceRichard code snippets (using proper markdown syntax: three backticks before and after) are always better than screenshots

I am running this demo code.
https://tensorflow.google.cn/tutorials/load_data/images
It still returns the same error message.

InvalidArgumentError: {{function_node __inference_Dataset_map_process_path_117}} slice index -1 of dimension 0 out of bounds.
[[{{node strided_slice}}]] [Op:IteratorGetNextSync]

**Comment by GaranceRichard** [comment] 2019-10-23 08:42
here is my pip :
`C:\Users\Garance>pip freeze
absl-py==0.7.1
altgraph==0.16.1
astor==0.8.0
attrs==19.1.0
auto-py-to-exe==2.6.5
backcall==0.1.0
beautifulsoup4==4.8.0
bleach==3.1.0
bottle==0.12.17
bottle-websocket==0.2.9
cffi==1.12.3
colorama==0.4.1
cx-Freeze==5.1.1
cycler==0.10.0
Cython==0.29.13
decorator==4.4.0
defusedxml==0.6.0
Django==2.2.6
Eel==0.10.4
entrypoints==0.3
enum34==1.1.6
future==0.17.1
gast==0.2.2
gevent==1.4.0
gevent-websocket==0.10.1
google==2.0.2
google-pasta==0.1.7
greenlet==0.4.15
grpcio==1.22.0
h5py==2.9.0
HeapDict==1.0.1
imageio==2.5.0
imutils==0.5.2
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
jedi==0.14.0
Jinja2==2.10.1
joblib==0.14.0
json5==0.8.5
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyter-http-over-ws==0.0.6
jupyter-tensorboard==0.1.10
jupyterlab==1.1.3
jupyterlab-server==1.0.6
Keras==2.2.5
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keras-rectified-adam==0.9.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
mock==3.0.5
more-itertools==7.2.0
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
notebook==5.7.8
numexpr==2.6.9
numpy==1.17.2
opencv-python==4.1.0.25
opt-einsum==3.0.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.0
pathlib==1.0.1
pefile==2019.4.18
pickleshare==0.7.5
Pillow==6.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.8.0
pycparser==2.19
Pygments==2.4.2
PyInstaller==3.5
pyocr==0.7.2
pyparsing==2.4.2
pyrsistent==0.15.3
pytesseract==0.2.7
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32-ctypes==0.2.0
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.1
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
soupsieve==1.9.3
sqlparse==0.3.0
tables==3.5.2
tb-nightly==1.15.0a20190806
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
tensorflow-estimator-2.0-preview==2.0.0
tensorflow-radam==0.12.0
termcolor==1.1.0
terminado==0.8.2
tesseract==0.1.3
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019080601
tornado==6.0.3
traitlets==4.3.2
virtualenv==16.7.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
whichcraft==0.6.0
widgetsnbextension==3.5.0
wrapt==1.11.2
xlrd==1.2.0
xlwt==1.3.0
yellowbrick==0.9.1
zict==1.0.0
zipp==0.6.0
zmq==0.0.0` 

**tensorflow==2.0.0** with that error

**Comment by mihaimaruseac** [comment] 2019-10-23 13:05
Not the proper assignee for this

**Comment by mihaimaruseac** [comment] 2019-10-23 13:07
@GaranceRichard please create a new environment and `pip install tensorflow==2.0 tensorflow_estimator=2.0` (and all other dependencies you need) in it. I see you have 3 estimator pips in your dependencies and we don't know if any of them causes the issue or not.

**Comment by GaranceRichard** [comment] 2019-10-23 13:50
`absl-py==0.8.1
astor==0.8.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
colorama==0.4.1
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
enum34==1.1.6
gast==0.2.2
google-pasta==0.1.7
grpcio==1.24.3
h5py==2.10.0
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.0
jupyter-http-over-ws==0.0.6
jupyter-tensorboard==0.1.10
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keras-rectified-adam==0.17.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.17.3
opencv-python==4.1.1.26
opt-einsum==3.1.0
pandas==0.25.2
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
Pillow==6.2.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.10.0
Pygments==2.4.2
pyparsing==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
pytz==2019.3
pywin32==225
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.3
virtualenv==16.7.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0`
same error
![image](https://user-images.githubusercontent.com/29459554/67399583-c16f7d00-f5ac-11e9-897a-910e46fd366a.png)

**Comment by GaranceRichard** [comment] 2019-10-23 13:50
upgrade my python to 3.7.5

**Comment by mihaimaruseac** [comment] 2019-10-23 14:26
Please post (minimal) code and attach image that is giving this error. Use **3** backticks before and after the code so the formatting is clear.

**Comment by ouy160** [comment] 2019-10-23 16:20
I got the same error with GaranceRichard, the code is in https://tensorflow.google.cn/tutorials/load_data/images. 
The error code segment is in the 22nd code segment. The error message is  {{function_node __inference_Dataset_map_process_path_117}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync].

The running python environment is recreated python3.7 and reinstalled tensorflow and its related components.

On the win10 computer, the way to install tensorflow is to use ‘pip install’

![捕获](https://user-images.githubusercontent.com/32807088/67413345-8e041100-f5f3-11e9-93a2-638c23b575f0.PNG)

**Comment by alefemacedo** [comment] 2019-11-06 04:39
I have the same issue.

Python: 3.6.9
tensorflow: 2.0.0
tensorflow-gpu: 2.0.0
OS: Windows 10

Error message:

InvalidArgumentError: {{function_node __inference_Dataset_map_parse_image_77925}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync]

**Comment by mihaimaruseac** [comment] 2019-11-06 16:27
Please post **code** not images. Make sure the code you post is complete and minimal. Make sure you use markdown formatting so it is easy to understand.

Try to post code from outside a notebook as notebooks can have cells run in different order and that would cause more headaches while trying to debug.

**Comment by gadagashwini** [comment] 2019-11-07 11:00
@GaranceRichard and @ouy160 
Similar issue [#33363](https://github.com/tensorflow/tensorflow/issues/33363).

**Comment by gadagashwini** [comment] 2019-11-22 09:22
Closing since its duplicate [#33363](https://github.com/tensorflow/tensorflow/issues/33363).

**Closed by gadagashwini** 2019-11-22 09:22 UTC
Labels: TF 2.0, comp:ops, subtype:windows, type:bug
