### ISSUE TITLE
Can't save stateful LSTM as savedmodel (TF 2.0)

### ISSUE THREAD

**Issue by optiluca** [tensorflow/tensorflow#34644] opened 2019-11-27 12:07 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): UBUNTU
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  DOCKER IMAGE
- TensorFlow version (use command below): DOCKER IMAGE 2.0
- Python version: DOCKER IMAGE 2.0
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: DOCKER IMAGE 2.0
- GPU model and memory: N/A

**Describe the current behavior**
Attemping to save a model containing a stateful LSTM to savedmodel format fails with the following error:

> AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_1:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.

**Describe the expected behavior**
No errors, and a correctly saved model :-)

**Code to reproduce the issue**

```
import tensorflow as tf
from tensorflow.keras import layers


def get_model(stateful=False, batch_size=None):
    n_channels = 1
    sample_size = 10
    n_units = 5

    inputs = layers.Input(batch_shape=(batch_size, sample_size, n_channels),
                          name='timeseries_inputs')
    y = layers.LSTM(units=n_units, input_shape=(sample_size, n_channels),
                    activation='tanh', recurrent_activation='sigmoid', return_sequences=False,
                    stateful=stateful)(inputs)

    y = layers.Dense(1)(y)

    model = tf.keras.models.Model(inputs=inputs, outputs=y)

    return model


stateless_model = get_model(stateful=False)

stateful_model = get_model(stateful=True, batch_size=1)

stateless_model.save('stateless.h5')
stateful_model.save('stateful.h5')

stateless_model.save('stateless.tf')
stateful_model.save('stateful.tf')
```

**Comment by ravikyram** [comment] 2019-11-29 06:42
I have tried on colab with TF version 2.0 ,2.1.0-dev20191128 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/7ff3594c234a8a39408abf72bdaeee8f/untitled417.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2019-11-29 07:03
Error is similar to the issue, #33247.

**Comment by optiluca** [comment] 2020-01-20 10:37
Any news on this?  Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-03 20:30
@optiluca This was resolved in the recently `tf-nightly`. I am not able to reproduce the issue with recent `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/7bde0bf225d272e883240afe5f7bf62f/34644.ipynb). Thank!

I am closing this issue as it was resolved. Please feel free to reopen if the issue didn't resolve for you.  Thanks!

**Closed by jvishnuvardhan** 2020-03-03 20:30 UTC
Labels: TF 2.0, comp:keras, stat:awaiting tensorflower, type:bug
