### ISSUE TITLE
Batches handled differently in the int reference fully connected kernel

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#53501] opened 2021-12-21 10:41 UTC
**System information**
-- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): SHA1: 403b4b19f9d143b4868d8a822c325acb6fdd8704

**Describe the current behavior**
Almost all fully connected kernels handle batches differently than the int8 reference fully connected kernel. Is this really intentional or a bug?

We have seen models (with keep_num_dims=True for fully_connected) where batches can be different in fully connected when a model has been converted from float to int8.

find . -name "fully_connected.h" |xargs grep "const int batches"|grep -v "//"
./lite/kernels/internal/reference/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dims_count - 1);
./lite/kernels/internal/reference/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
./lite/kernels/internal/reference/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
./lite/kernels/internal/reference/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
./lite/kernels/internal/reference/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
./lite/kernels/internal/reference/integer_ops/fully_connected.h:  const int batches = output_shape.Dims(0);
./lite/kernels/internal/reference/integer_ops/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
./lite/kernels/internal/optimized/sparse_ops/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dims_count - 1);
./lite/kernels/internal/optimized/sparse_ops/fully_connected.h:  const int batches = thread_end - thread_start;
./lite/kernels/internal/optimized/sparse_ops/fully_connected.h:  const int batches =
./lite/kernels/internal/optimized/integer_ops/fully_connected.h:  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);

The typical case is const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1)
In the int8 ref case: const int batches = output_shape.Dims(0);

**Describe the expected behavior**
Batches are handled the same way for int and float fc kernels.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
Change const int batches = output_shape.Dims(0);
To
const int output_dims_count = output_shape.DimensionsCount();
const int batches = FlatSizeSkipDim(output_shape, output_dims_count - 1);

**Comment by dansitu** [comment] 2022-01-20 20:03
We are also seeing this issue. As a workaround, conv layers with 1x1 filter kernels can substitute for fully connected layers. Note that for quantized models this will result in per-channel quantization, which may impact your model size and accuracy.

There's a related issue here tracking fixing the problem for optimized kernels on Arm embedded devices that use TensorFlow Lite for Microcontrollers: https://github.com/ARM-software/CMSIS_5/issues/1398

**Comment by Tessil** [comment] 2022-04-13 15:09
With https://github.com/tensorflow/tensorflow/pull/54223 merged the problem should now be solved. The fix was also imported in tflite-micro  (see commit https://github.com/tensorflow/tflite-micro/commit/1501b574b74fd7877aba30aa9d8b667f41b139c3).

**Comment by sachinprasadhs** [comment] 2022-04-13 18:53
@mansnils , Could you please try it in Nightly version and let us know if the problem is fixed as per the above comment. Thanks!

**Closed** 2022-04-27 20:22 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.7
