### ISSUE TITLE
low-level compilation

### ISSUE THREAD

**Issue by never-to-never** [tensorflow/tensorflow#57093] opened 2022-08-11 01:06 UTC
Before tensorflow 2.0, tensorflow was a static graph mode, and it was necessary to build a graph and get an HLO IR. XLA accepts computational graphs defined in HLO for goal-independent optimization. Then, the xla backend performs further HLO-level optimizations. After that, xla backend converts the HLO IR to LLVM IR, which performs low-level optimizations and generates machine code. After tensorflow 2.0, tensorflow has become a dynamic graph mode similar to pytorch, without first building a static graph. Can you answer, what is the logic from the top to the bottom under the dynamic graph concept?

**Comment by tilakrayal** [comment] 2022-08-12 06:37
@never-to-never,
Looks like this is a duplicate of issue #57040. Could you please close this issue, since it is already being tracked there? Thank you!

**Closed** 2022-08-14 06:18 UTC
Labels: stat:awaiting response, type:others, comp:xla
