### ISSUE TITLE
Generalize TensorFlowTestCase to handle arbitrary devices

### ISSUE THREAD

**Issue by spmckenney** [tensorflow/tensorflow#7789] opened 2017-02-22 18:17 UTC
Currently, TensorFlowTestCase can only handle CPU and GPU devices.

```python
class TensorFlowTestCase(googletest.TestCase):
  def test_session(self,
                   graph=None,
                   config=None,
                   use_gpu=False,
                   force_gpu=False)
```

We are currently extending TensorFlow to run on another device and would like to update the signature to handle arbitrary devices. This could be done by changing the signature as follows, for example:

```python
class TensorFlowTestCase(googletest.TestCase):
  def test_session(self,
                   graph=None,
                   config=None,
                   use_device=None,
                   force_device=False)
```

This would certainly have some significant ripples in the test cases, so I would like like to get some feedback before I start anything.

Thoughts?

**Comment by yaroslavvb** [comment] 2017-02-23 04:08
So how would you tell a test to force GPU? Set `force_device=True`? That seems a bit counter-intuitive.

I think the easiest thing to do may be first fork `TensorFlowTestCase` to a new version that supports other devices, and once things stabilize, look at two versions side by side and see if it makes sense to factor out common functionality (and that the refactoring effort justifies the costs imposed by Conway's Law)

**Comment by spmckenney** [comment] 2017-02-23 17:01
Perhaps it would be a little more clear to have an interface such as:
```python
class TensorFlowTestCase(googletest.TestCase):
  def test_session(self,
                   graph=None,
                   config=None,
                   use_device="/device:CPU:0",
                   force_device_placement=False)
```
Forcing GPU use could then be done with `sess = self.test_session(use_device="/device:GPU:0, force_device_placement=True)`. This would also deconvolve the selecting of a device and the forcing of its use, unlike the current implementation (i.e. `sess = self.test_session(use_gpu=False, force_gpu=True)` <- what happens?).

However, the goal of the change is to generalize all of the tests, which may also impose significant costs. There is also a bit more gpu-specific code in the method that would have to be dealt with. I agree that forking and seeing how it plays out is a good idea. I'll report back in a couple of days with how it is going.

**Comment by yaroslavvb** [comment] 2017-02-23 17:22
The `test_session` code was not really planned in advance and grew organically. There are probably bugs. @drpngx saw some weird/unexpected behavior in `force_gpu` --https://github.com/tensorflow/tensorflow/issues/7026#issuecomment-281741007

**Comment by drpngx** [comment] 2017-02-23 17:36
Yeah, `force_gpu` was ineffectual when I tried it. Looking at the code, it basically just says `allow_soft_placement=False` and `with sess.graph.device("/gpu:0"): yield sess`, so it should work.

**Comment by aselle** [comment] 2017-03-03 23:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2017-03-03 23:37 UTC
Labels: stat:awaiting response, type:feature
