### ISSUE TITLE
TFRecordWriter doesn't throw an error when disk partition gets out of space

### ISSUE THREAD

**Issue by sulc** [tensorflow/tensorflow#8745] opened 2017-03-27 07:50 UTC
## Problem
When tensorflow.python_io.TFRecordWriter(path) is initialized with a path leading to a device out of free storage space, one can still write() and close() it without receiving an error or exception. The resulting file is empty (0B).

## Environment info
TF v.1.0.1 installed from pip3 (package tensorflow-gpu) with Python 3.4.2 on a Linux server.

## Minimal example
    writer = tf.python_io.TFRecordWriter(output_file)
    for i in files_in_shard:
      # ....
      # [prepare record]
      writer.write(example.SerializeToString())
    writer.close()
Working example e.g. https://github.com/tensorflow/models/blob/master/inception/inception/data/build_image_data.py

**Comment by aselle** [comment] 2017-03-28 23:17
@concretevitamin, is this expected behavior for IO?

**Comment by concretevitamin** [comment] 2017-03-29 22:35
@saxenasaurabh: can you take a look?

**Comment by tensorflowbutler** [comment] 2017-12-22 07:45
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:12
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:20
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:07
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:16
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:38
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-10 12:37
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-25 19:01
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 12:45
Nagging Assignee @tatatodd: It has been 327 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatatodd** [comment] 2018-05-16 23:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatatodd** 2018-05-16 23:27 UTC
Labels: stat:awaiting tensorflower, type:bug/performance, type:support

**Comment by mxh** [comment] 2018-06-25 12:10
This is still an issue with v1.7.0. A loop that writes one record each iteration happily continues when the disk has run out of space.
