### ISSUE TITLE
[tf.keras] Mixed precision policy "mixed_bfloat16" not supported in Keras compile

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#34782] opened 2019-12-03 05:11 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Co-lab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TF 2.1-rc0
- Python version: 3.6

**Describe the current behavior**

We are porting a GPU based model to CloudTPU. We are using Keras **mixed_float16** mixed-precision policy to enable TensorCore on GPU. Without any code change, we are trying to use **mixed_bfloat16** for CloudTPU for maximal performance.

**Describe the expected behavior**

``model.compile`` with **mixed_bfloat16** policy to enable mixed-precision training on CloudTPU.

**Code to reproduce the issue**

Colab link: https://colab.research.google.com/drive/1-SBnqhsmyjVNJxntB8ZZdqRUk7h7tRs8

```
def compile_keras_model(dtype):
  policy = tf.keras.mixed_precision.experimental.Policy(dtype)
  tf.compat.v2.keras.mixed_precision.experimental.set_policy(policy)

  optimizer = tf.optimizers.SGD(learning_rate=0.1, momentum=0.9)

  model = tf.keras.applications.resnet50.ResNet50(weights=None)
  model.compile(loss='sparse_categorical_crossentropy',
                optimizer=optimizer, 
                metrics=['sparse_categorical_accuracy'])
  return model
  
gpu_model = compile_keras_model('mixed_float16')
tpu_model = compile_keras_model('mixed_bfloat16')
```

**Other info / logs**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-ad9cf91bd793> in <module>()
     12 
     13 gpu_model = compile_keras_model('mixed_float16')
---> 14 tpu_model = compile_keras_model('mixed_bfloat16')

12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     59           "allowed values: %s" %
     60           (param_name, dtypes.as_dtype(dtype).name,
---> 61            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     62 
     63 

TypeError: Value passed to parameter 'x' has DataType bfloat16 not in list of allowed values: float16, float32, float64, complex64, complex128
```

**Comment by ravikyram** [comment] 2019-12-04 08:41
I have tried on colab with TF version 2.1.0-rc0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/0d0639c5e7a5dae0937d7aa16b042d59/untitled444.ipynb). Thanks!

**Comment by byronyi** [comment] 2019-12-04 08:55
Gently ping @reedwm; is this behavior intended?

**Comment by reedwm** [comment] 2019-12-05 22:40
The issue is that we are calling an op that does not support bfloat16 in the Loss. We should do all Losses in float32, but I haven't implemented that yet. I regret not doing this for 2.1, but this will definitely be fixed in 2.2.

Because of this issue, in 2.1, models should end in float32. For models which you cannot modify, like `tf.keras.applications.resnet50.ResNet50`, you can wrap the model with a version that has a float32 output, as follows:

```python
def compile_keras_model(dtype):
  policy = tf.keras.mixed_precision.experimental.Policy(dtype)
  tf.compat.v2.keras.mixed_precision.experimental.set_policy(policy)

  optimizer = tf.optimizers.SGD(learning_rate=0.1, momentum=0.9)

  model = tf.keras.applications.resnet50.ResNet50(weights=None)

  # Create new model that is `model` except the output is float32
  inp = tf.keras.layers.Input(batch_shape=model.input_shape)
  out = model(inp)
  # This layer simply casts to float32
  out = tf.keras.layers.Activation('linear', dtype='float32')(out)
  model = tf.keras.Model(inp, out)

  model.compile(loss='sparse_categorical_crossentropy',
                optimizer=optimizer,
                metrics=['sparse_categorical_accuracy'])
  return model

gpu_model = compile_keras_model('mixed_float16')
tpu_model = compile_keras_model('mixed_bfloat16')
```

Additionally, if your model ends in softmax, you should also do the softmax in float32, as a few models require this for numeric stability and it has very little impact on performance. Only softmaxes at the end of the model need to be float32; if a softmax is in the middle of the model, doing it in float16 is fine. For example, if your model ends with the following
```python
out = tf.keras.layers.Dense(32, activation='softmax')(out)
```

Replace it with the following:

```python
out = tf.keras.layers.Dense(32)(out)
out = tf.keras.layers.Activation('softmax', dtype='float32')(out)
```
This will cause the softmax to be in float32, and the output of the model in float32.

Unfortunately, none of the keras application models currently do the last softmax in float32, but I will fix in a future release. If feasible, I will try to have this done automatically. Luckily, for most models, including resnet50, doing the softmax at the end of the model in float16 is fine

**Comment by byronyi** [comment] 2019-12-06 00:21
@reedwm that’s very helpful, thanks Reed!

I’ll leave this issue as a marker and close it once it’s fixed in master.

**Comment by jvishnuvardhan** [comment] 2020-03-16 18:59
@byronyi Looks like this was already implemented in the recent `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/12876c8f6f6e2e185b6952ebea37a4da/untitled444.ipynb). Thanks.

Please close the issue if this was resolved for you. Thanks!

**Comment by reedwm** [comment] 2020-03-16 19:35
Ah yeah, this was fixed fairly recently.

It turns out doing softmax + loss in fp16 or bf16 is fine in most cases. For this particular issue, the error came from the div_no_nan op, which Keras will now always do in fp32 to avoid the error.

**Closed by reedwm** 2020-03-16 19:35 UTC
Labels: TF 2.1, comp:keras, type:bug
