### ISSUE TITLE
Input shape for converted tflite model is wrong

### ISSUE THREAD

**Issue by raagapranitha** [tensorflow/tensorflow#42157] opened 2020-08-09 00:15 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Android 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):2.4.0-dev20200808

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/117z3RoXIdk-yhptaQIzjuj_WQ5mIO8wP?usp=sharing

```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/saved_model/',signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with tf.io.gfile.GFile('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**The output from the converter invocation**

TFLite file: https://drive.google.com/file/d/12lFDByC29jYNa-9V4vzm8poJfTH1zNMI/view?usp=sharing

**Failure details**
Able to produce the TFLite model, after visualizing the generated .tflite with https://lutzroeder.github.io/netron/ found the input shape of the model is [1,1,1,3] instead of [1,640,640,3].
Android Object Detection sample fails to run. I have modified TF_OD_API_SIZE, TF_OD_API_IS_QUANTIZED, TF_OD_API_MODEL_FILE accordingly.

**Any other info / logs**
```
ADB logcat: Cannot copy to a TensorFlowLite tensor (serving_default_input_tensor:0) with 3 bytes from a Java Buffer with 4915200 bytes.
```

**Comment by amahendrakar** [comment] 2020-08-10 10:12
Looks like a duplicate of [#42153](https://github.com/tensorflow/tensorflow/issues/42153).

**Comment by abattery** [comment] 2020-11-03 14:14
Current tflite has limited dynamic shape support.

You can either set a fixed shape during conversion or resize the input shape.

**Comment by AdamChrist** [comment] 2020-11-05 00:19
@abattery Can you provide some example code for convert SSD ResNet model ?

**Comment by tucachmo2202** [comment] 2020-11-29 14:40
> Current tflite has limited dynamic shape support.
> 
> You can either set a fixed shape during conversion or resize the input shape.

How to fix? Tell me, please. Thank you so much

**Comment by Saduf2019** [comment] 2021-04-23 19:01
@raagapranitha 
Could you please try on latest version of tf [2.5] or nightly and let us know if you still face the issue.

**Closed** 2021-05-10 19:59 UTC
Labels: TF 2.3, comp:lite, stalled, stat:awaiting response, type:bug

**Comment by haozha111** [comment] 2022-08-16 20:41
TF Lite converter has already supported dynamic shapes. If your model has dynamic input shapes and you didn't specify a dimension size when building and converting your model, the converter will use 1 as the default dimension size. However, at inference time you can use Interpreter's ResizeInputTensor API to change the input shape of the model:
https://github.com/tensorflow/tensorflow/blob/2d13fc51f7eef6d77db1b7d1e0c22b1169453725/tensorflow/lite/python/interpreter.py#L699
