### ISSUE TITLE
Mention that GPU reductions are nondeterministic in docs

### ISSUE THREAD

**Issue by shiviser** [tensorflow/tensorflow#2732] opened 2016-06-08 14:38 UTC
# The problem

I am trying out the [MNIST for experts tutorial](https://www.tensorflow.org/versions/r0.7/tutorials/mnist/pros/index.html#deep-mnist-for-experts) and I have inconsistent results on the GPU.
### What do I mean by inconsistent?

With the exactly same network parameters (and randomness removed: read below in the post) every time I run the complete train-then-test process the accuracy is slightly different.
### What have I done to visualize this problem?

For each iteration, I have calculated the differences between the variables (weights, biases) from two _independent but identical_ runs and computed the L1 norm of those differences - <br/>
- [plot](http://i.stack.imgur.com/W5PqZ.png) of L1 norm for the first 1000 iterations in steps of 20.

In a consistent world, these differences should be always zero! 
### How did I remove randomness in the code?
- Removed dropout entirely
- added a graph level seed (`tf.set_random_seed(1234)`). With this the variable initialization is deterministic and also any other randomization in the code. 
- The [MNIST for experts tutorial](https://www.tensorflow.org/versions/r0.7/tutorials/mnist/pros/index.html#deep-mnist-for-experts) uses [this script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/mnist.py) to download/load the MNIST data. I have added `numpy.random.seed(3)` in `DataSet.__init__(self, images, labels, fake_data=False, one_hot=False, dtype=dtypes.float32)` in this script to remove randomness during the shuffling process (line 154 in `DataSet.next_batch(self, batch_size, fake_data=False)`)
- `config = tf.ConfigProto(inter_op_parallelism_threads=1, intra_op_parallelism_threads=1)` which goes into the creation of session as `sess = tf.Session(config=config)`
### What system am I using?
- tensorflow 0.8 gpu version (installed via pip)
- OpenSUSE LEAP 42.1 (x86_64)
- Cuda Toolkit 7.5
- CuDNN 4.0
- Tesla K20c card with Nvidia driver 352.79

**Comment by yaroslavvb** [comment] 2016-06-08 15:49
Do you get deterministic results if you run this on CPU? Results of optimized GPU computations for NN ops are usually a little bit non-deterministic, I think it's a nature of how modern GPUs work, @zheng-xq may have more understanding of this

**Comment by jiaboli007** [comment] 2016-06-08 16:14
I have the same observation on both GPU and CPU. I think whenever parallel computing is use (either multiple core CPU or GPU), the results will not be deterministic. This is due to the randomness of the order of collecting the partial results from all threads, and this can lead to very small difference within machine accuracy at the beginning and then this tiny tiny difference gets amplified during iterations.

**Comment by shiviser** [comment] 2016-06-08 16:14
Yes I do get deterministic results on the CPU.

To problem is, in a bigger network I have designed for another dataset the inconsistencies are quite large (up to +/-25%).

**Comment by shiviser** [comment] 2016-06-08 16:19
@jiaboli007 I have seen that it is possible to have parallel computations and yet have deterministic behaviour (e.g.: Matlab simulink can optimize models for parallel computations yet assuring deterministic behaviour).

**Comment by zheng-xq** [comment] 2016-06-08 17:12
On GPU, small amount of non-deterministic results is expected. TensorFlow uses the Eigen library, which uses Cuda atomics to implement reduction operations, such as tf.reduce_sum etc. Those operations are non-determnistical. Each operation can introduce a small difference. If your model is not stable, it could accumulate into large errors, after many steps. 

If you see a large difference, after one or two operations, it would be problematic. Otherwise, it is somewhat expected. Regularizers such as dropout helps the model tolerate that.

**Comment by girving** [comment] 2016-06-08 21:47
This is expected behavior: see #2652 for more discussion.

**Comment by shiviser** [comment] 2016-06-09 15:35
@zheng-xq I have already tried dropout, it didn't help. After a bit of research over the internet, I have come to know that torch had a similar [non-deterministic behaviour](https://github.com/torch/cunn/issues/84) with their SpatialMaxPooling operation but it has been fixed now. Perhaps something along the lines?

@girving Having said the above, and that this "non-deterministic behaviour" is not mentioned in the documentation, I would like to re-open the issue.

**Comment by girving** [comment] 2016-06-09 15:40
Reopened: We'd be happy to accept a PR adding a note to this effect.

**Comment by shiviser** [comment] 2016-06-09 15:46
@girving Thank you for re-opening the issue but I believe tensorflow could do better than just documenting this, what seems to be an unintended non-deterministic behaviour. Also, I would have loved to work on the PR but will be too much digression from my work at the moment.

P.S.: Don't know if you saw my last edit - on the [same post](https://github.com/torch/cunn/issues/84) one can read that Caffe has already accomplished deterministic backward passes. Perhaps this is interesting to you!

**Comment by shiviser** [comment] 2016-06-09 15:50
@girving Also we are not yet sure if it is actually the GPU reductions and not something else which is causing the non-deterministic behaviour - this need verification before allowing entry into the docs.

**Comment by girving** [comment] 2016-06-09 15:57
@shiviser Let us know what you find out!

**Comment by zheng-xq** [comment] 2016-06-09 16:21
@shiviser, that particular kernel was fixed to be determnistics. I believe TensorFlow picked up the same fix. However, other Cudnn conv algorithms are still non-deterministic, since they use atomics inherently. Most frameworks may encounter them depending on the input and kernel shapes. 

That being said, if your investigation reveals something else that is causing the problem, a PR to address the doc and the code is welcome.

**Comment by jkschin** [comment] 2017-05-12 03:51
BUILD
TensorFlow GPU 1.1.0
Ubuntu 16.04
CUDA 8.0.61
CUDNN 5.1

@zheng-xq why is the forward pass deterministic but the very first backward pass not deterministic?

On a simple MNIST example, the logits are 100% deterministic over 100 runs (I did more runs than that but plotted 100).

![logits](https://cloud.githubusercontent.com/assets/6997460/25981433/a9473ee0-3707-11e7-8a60-240963c6c471.png)

However, when we look at the gradients computed on the last set of variables, we see small errors of scale 1e-8.

![3d](https://cloud.githubusercontent.com/assets/6997460/25981444/c9561e0e-3707-11e7-8ce9-20ced60186e2.png)

I proceeded to do a simpler example of simply trying to train a neural network to add.

Inputs: 10x1 (numpy generated with same seed)
Weights: 10x1 (random normal initialized with same seed)
Labels: Sum of the 10x1 input.

Effectively, the neural network is trying to tune the weights such that they all become 1.0.

In fact, it's strange because the randomness has some form of determinism, as seen in the graph below.

![run1](https://cloud.githubusercontent.com/assets/6997460/25981528/4ea32fca-3708-11e7-98b0-a6abcfd58347.png)
![run5](https://cloud.githubusercontent.com/assets/6997460/25981532/516018a4-3708-11e7-8712-6b3824a664cf.png)
![run7](https://cloud.githubusercontent.com/assets/6997460/25981535/54733dc8-3708-11e7-9fe8-9911f64942c5.png)
![run11](https://cloud.githubusercontent.com/assets/6997460/25981537/596a5de8-3708-11e7-83fe-b10af531501b.png)

Furthermore, the anomalous gradients are consistently the same throughout the runs!

![screenshot from 2017-05-12 11-45-15](https://cloud.githubusercontent.com/assets/6997460/25981559/7d6c0926-3708-11e7-849d-bc30beb2591f.png)

@asimshankar mentioned [here](https://github.com/tensorflow/tensorflow/issues/5527) that mismatches between CUDA and Drivers could be the problem. So I upgraded my driver to 381, and then I got these results. 1 - 7 gradients have errors, but previously, only 5 had errors and when errors happened, these 5 gradients had exactly the same values.

![11](https://cloud.githubusercontent.com/assets/6997460/25981589/b574d00a-3708-11e7-8fc9-22e0575ec94b.png)

I haven't looked deeply into the exact 7 gradients that have errors but a brief glance showed that they are the same as the 5 before and more.

If anyone has any insight into what experiments to try next, I'll be glad to do them and post the results here.

**Comment by yaroslavvb** [comment] 2017-05-12 14:11
You could try a simple feed-forward network with squared loss. Training can be implemented with only `matmul` and `reduce_sum`, if there's non-determinism there, then pretty much everything is potentially non-deterministic. Addition of floating point numbers is not-associative, so if the other of summing things together in matmul/reduce_sum changes, that can affect results. Typically this is not considered a bug as long as the precision of results stays within machine epsilon (1e-7 for float32)

**Comment by jkschin** [comment] 2017-05-12 14:55
@yaroslavvb I'll try that out and post some results here.
@girving any other things to try so we can include in the docs? I'd be happy to do a PR for this if it's within my capabilities.

**Comment by girving** [comment] 2017-05-12 19:08
@jkschin Not sure what you mean by other things.  If the PR is just adding a note that reductions are nondeterministic, keeping is small seems good.

More broadly, I'd love a determinism push to make everything we can actually deterministic, but that will take more work.

**Comment by jkschin** [comment] 2017-05-15 01:09
@yaroslavvb I realized I'm already doing a simple feed-forward network above.

```python
def add_model(v):
    w = tf.get_variable(name='w', shape=[vector_size],
            dtype=tf.float32,
            initializer=tf.random_normal_initializer)
    output = tf.reduce_sum(tf.multiply(w, v), axis=1)
    tf.add_to_collection('weights', w)
    return output
```
@girving yeah you mentioned adding a note to this effect. Where should it be added? Agree on a deterministic push!

**Comment by yaroslavvb** [comment] 2017-05-15 01:46
@jkschin as an end-user who got tripped up by non-determinism, you might have an idea where this note should go, so that other people like you would see it

**Comment by jkschin** [comment] 2017-05-16 01:21
Would a post [here](https://www.tensorflow.org/performance/) titled "Non-determinism in TensorFlow" with some example code help?

**Comment by girving** [comment] 2017-05-16 15:50
Yes!  @martinwicke: That a good place for an overview of TensorFlow nondeterminism?

**Comment by martinwicke** [comment] 2017-05-16 15:57
I think it should go into the programmer's guide section, but @wolffg has a better overview of where to put this. 

Either way, the content would be the same, and we'd be enthusiastic about it.

**Comment by benjrossi** [comment] 2017-05-27 21:53
Check out a [workaround](https://twosigma.com/insights/a-workaround-for-non-determinism-in-tensorflow) for training a simple fully-connected net with repeatable results on the GPU. It's no panacea, but it seems relevant to the discussion!

**Comment by jkschin** [comment] 2017-06-08 04:06
@benjrossi nice post. I'm working on a short guide and hope to push a first draft within the next 2 weeks.

**Comment by wolffg** [comment] 2017-06-08 14:03
I think this is a note for the Programmer's Guide.  We're working on a
redesign of the table of contents for the Programmer's Guide, but I would
suggest you create a fresh doc entitled "Non-determinism in TensorFlow".
If you submit it as a separate doc in
tensorflow/docs_src/programmers_guide, we may glom it into another document
when we reorganize.

Thanks for writing it up!

**Comment by rahuljha** [comment] 2017-08-30 20:59
The link from benjrossi doesn't work anymore, here is an updated link to the same page: https://www.twosigma.com/insights/a-workaround-for-non-determinism-in-tensorflow.

**Comment by ekelsen** [comment] 2017-09-14 15:40
Reductions are now deterministic.

**Comment by huanghoujing** [comment] 2017-09-16 08:17
One of the problems I encountered that cause randomness is **multi-thread pre-fetching** training samples. In the multi-thread way, in a new run the samples are put into the queue in a new order, determined by the relative speed of the threads. I have to set the number of pre-fetching threads to 1 to solve the problem.

**Comment by wwwyn** [comment] 2017-09-27 02:30
@ekelsen which tensorflow version is deterministic?

**Comment by ekelsen** [comment] 2017-09-27 02:36
It's been in head for a few weeks now.

**Comment by ekelsen** [comment] 2017-09-27 02:37
so currently only master has deterministic GPU reductions; the next release, 1.4 should have them.

**Comment by jaekyeom** [comment] 2018-01-10 10:39
@ekelsen Could you please elaborate on how it went?

**Comment by ranshadmi** [comment] 2018-02-12 18:44
As far as I can tell, TF 1.5 still shows non-deterministic results on GPU (and deterministic on CPU). However, I'm using reduce_mean not reduce_sum. I assume it is the same problem.
I would love to know if there are concrete plans to improve the reproduciblity of training.

**Comment by lucb** [comment] 2018-02-19 15:36
From my own experiences non-determinism can be found in the backward pass of the convolution filter and in the computation of the softmax cross-entropy loss function.

The convolution issue can be solved by using a deterministic algorithm from cudnn instead of letting tensorflow decide the "best" algorithm to use.

**Comment by yaroslavvb** [comment] 2018-02-19 23:14
Perhaps `export TF_CUDNN_USE_AUTOTUNE=0`

**Comment by nikonikolov** [comment] 2018-04-25 13:41
As far as I can tell TF 1.6 also shows non-deterministic results on GPU. Has this been fixed in the master branch or a later release? If not, are there any plans to "fix" it? Even if not, in the mean time it seems very necessary to at least note this in the official documentation. Sorry if it is already there, but I was not able to find it (which suggests others might also not be able to).

**Comment by martinwicke** [comment] 2018-04-25 16:12
@ekelsen is this still expected? 

It's fine for these to be non-deterministic, but we should mention it in the docs if so.

**Comment by jkschin** [comment] 2018-04-25 21:26
Happy to re-open this PR and refine it: https://github.com/tensorflow/tensorflow/pull/10636. Thoughts @martinwicke?

**Comment by martinwicke** [comment] 2018-05-04 00:11
Sounds good. Thank you!

**Comment by jkschin** [comment] 2018-05-07 14:13
https://github.com/tensorflow/tensorflow/pull/10636 is outdated so I won't be refining it.

It seems like both `tf.reduce_sum` and `tf.reduce_mean` are deterministic now. @nikonikolov do you have a small example to reproduce the non-deterministic behaviour?

**Comment by nikonikolov** [comment] 2018-05-07 22:02
@jkschin Unfortunately I do not have a simple one. Are **all** operators determinisitc on GPU now? If they are supposed to be, I can dig into it and compose an example. I am using much more operators than `tf.reduce_sum` and `tf.reduce_mean` so there is a chance there is another operator causing the non-deterministic behavior. 

Also which version exactly has the deterministic behavior?

**Comment by nikonikolov** [comment] 2018-05-14 17:41
@jkschin Assuming that `tf.reduce_sum` and `tf.reduce_mean` are now deterministic, are all gradient based operations deterministic too (assuming the same data is passed to the neural network). I am still experiencing the problem in TF 1.8 and the non-determinism happens after a gradient step is taken. I can try to provide example, but first wanted to make sure determinism is expected with gradients.

**Comment by martinwicke** [comment] 2018-05-14 17:54
The gradient pass often contains ops that are rare in the forward pass. Is there a way to narrow this down further? There may be a reduction or something else which is non-deterministic. 

We probably cannot claim that all of TF is deterministic yet.

**Comment by nikonikolov** [comment] 2018-05-14 21:04
Hey, so here is a relatively simple example to reproduce. I tried it on CPU and results were the same. However, on GPU they were not. When I decreased number of iterations to 1 or 2, all the time I was able to get the same results (although I did not do a lot of runs). When the number of iterations is higher, say >10, I almost always get different results. Also when there is only 1 dense layer, the results are almost always reproducible.

```
import numpy as np
import tensorflow as tf

ITERATIONS=20

tf.set_random_seed(42)
np.random.seed(42)

x_data = np.random.normal(size=[32, 10])
y_data = np.random.normal(size=[32, 1])
x_test = np.random.normal(size=[32, 10])

x_in  = tf.placeholder(tf.float32, [None, 10])
y_in  = tf.placeholder(tf.float32, [None, 1])
x     = x_in
x     = tf.layers.dense(x, 200, tf.nn.relu)
x     = tf.layers.dense(x, 1, tf.nn.relu)
loss  = tf.losses.mean_squared_error(y_in, x)

mvars = tf.get_default_graph().get_collection(tf.GraphKeys.GLOBAL_VARIABLES)

opt   = tf.train.AdamOptimizer(use_locking=True)
train = opt.minimize(loss)
config= tf.ConfigProto(inter_op_parallelism_threads=1, intra_op_parallelism_threads=1)
sess  = tf.Session(config=config)

allvars = tf.get_default_graph().get_collection(tf.GraphKeys.GLOBAL_VARIABLES)

sess.run(tf.global_variables_initializer())
init_vals = sess.run(allvars)

def run():
  for val, v in zip(init_vals, allvars):
    sess.run(tf.assign(v, val))
  
  ivals = sess.run(allvars)
  out = []
  allvals = []

  for i in range(ITERATIONS):
    l, _ = sess.run([loss, train], feed_dict={x_in: x_data, y_in: y_data})
    out.append(sess.run(x, feed_dict={x_in: x_test}))
    allvals.append(sess.run(allvars))

  fvals = sess.run(allvars)
  # return np.asarray(ivals), np.asarray(fvals), np.asarray(out)
  return np.asarray(ivals), np.asarray(fvals), np.asarray(out), allvals

ivals1, fvals1, out1, all1 = run()
ivals2, fvals2, out2, all2 = run()

same_init = [np.all(v1 == v2) for v1, v2 in zip(ivals1, ivals2)] 
same_fin = [np.all(v1 == v2) for v1, v2 in zip(fvals1, fvals2)] 
print("Forward passes were the same: {}".format( np.all(out1 == out2) ))
print("Final value of variables are the same: {}".format( np.all(same_fin) ))
print("Variables initialized to same values: {}".format( np.all(same_init) ))
```
Unfortunately I am really busy with experiments at the moment and do not have the time to narrow this down further, but I hope it will be a good starting point. I tested with python 3.6.5, CUDA 9.0, cudnn 7.1
 and TF 1.8.

It will be great if we manage to make all operations deterministic. I am running some Reinforcement Learning algorithms and over time I get huge difference in performance even if I use the same seed.

**Comment by tensorflowbutler** [comment] 2018-05-30 15:10
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-06-14 18:48
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-06-29 18:54
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-14 18:38
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-07-29 18:32
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:50
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:30
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by ekelsen** [comment] 2018-09-18 17:10
GPU reduction are now deterministic.

**Closed by ekelsen** 2018-09-18 17:10 UTC
Labels: stat:contributions welcome, type:docs

**Comment by albertz** [comment] 2018-11-29 17:14
@ekelsen Which ops are deterministic exactly? Since when / which TF version? Is this documented?

**Comment by nikonikolov** [comment] 2019-03-17 18:51
@ekelsen, I still experience non-deterministic GPU operations. In comparison, same code is absolutely deterministic when it runs on CPU. I am using TF 1.12.0 and CUDA 9.0

**Comment by ekelsen** [comment] 2019-03-17 21:58
Reductions are deterministic.  Many other things are not:

0) Forward passes of anything that uses auto-tune (convolutions are the prime culprit, but I think also gemm now)
1) Backward passes of convolutions
2) Backward passes of bias_add (sometimes depending on auto-tune)
3) I think cross entropy still hasn't been switched to use the faster and deterministic reductions under the hood.
4) unsorted_segment_sum (possibly also sorted_segment_sum)
5) scatter_add/sub
6) backward pass of depthwise conv, some less common ops used in preprocessing
Possibly more I've forgotten or never knew about.

**Comment by nikonikolov** [comment] 2019-03-17 22:20
Thanks for clarifying. Are there any plans to make all these deterministic? PyTorch can be completely deterministic on GPU which can often be very useful. In particular, while the non-determinism might be acceptable in supervised learning, in Reinforcement Learning it has very non-trivial impact on results, sometimes leading to big variance due to the constantly shifting data distribution.

**Comment by Robbie-Palmer** [comment] 2019-09-18 08:53
For anyone still encountering this issue, @duncanriach has done great work on this problem which he presented at NVIDIA's GTC 2019 conference.
His findings being that there are a multitude of reasons for the non-determinism we see
He has set-up a [repository](https://github.com/NVIDIA/tensorflow-determinism) to track the issue which also contains a link to his talk

**Comment by duncanriach** [comment] 2019-10-08 22:33
Thanks @Robbie-Palmer. The current high-level status is that there are now solutions for TensorFlow determinism when running on GPUs related to cuDNN (convolutions and max-pooling) and bias_add. Please see the following repo for up-to-date status: https://github.com/NVIDIA/tensorflow-determinism
