### ISSUE TITLE
What is the difference between model.__call__ on TensorSpec and Tensor

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [tensorflow/tensorflow#56677] opened 2022-07-05 01:46 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
I have a subclassed Keras model which uses a custom layer. 

I find that model.__call__ on TensorSpec behaves differently from model.__call__ on Tensor.
For model.__call__ on TensorSpec, I cannot see the logs from Model.call() and Layer.call().
For model.__call__ on Tensor, I can see these logs.

Please note that I use tf.print() within Model.call() and Layer.call() to print the logs.

The reason why I ask this is that I want to confirm whether the internal forward step is executed when TensorSpec is fed. The use case is that the execution of the custom layer is depending on a service, which is not started before I save the model graph. As you may know, saving the model graph requires model.__call__() first, and I don't want this model.__call__() on TensorSpec to invoke the actual execution of the custom layer.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

def test(values):
    vector  = tf.zeros_like(values)
    return vector


class TestLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(TestLayer, self).__init__(**kwargs)

    # @tf.function
    def call(self, inputs, training=False):
        tf.print("=============TestLayer.call()============")
        emb_vector = test(values = inputs)
        return emb_vector

class Demo(tf.keras.models.Model):
    def __init__(self, **kwargs):
        super(Demo, self).__init__(**kwargs)
        
        self.test_layer = TestLayer()        
        self.dense_layer = tf.keras.layers.Dense(units=1, activation=None,
                                                 kernel_initializer="ones",
                                                 bias_initializer="zeros")

    def call(self, inputs):
        tf.print("=============Demo.call()============")
        vector = self.test_layer(inputs)
        logit = self.dense_layer(vector)
        return logit, vector

    def summary(self):
        inputs = tf.keras.Input(shape=(10,))
        model = tf.keras.models.Model(inputs=inputs, outputs=self.call(inputs))
        return model.summary()

global_batch_size = 16384
input1 = tf.keras.Input(shape=(10,))
input2 = tf.ones(shape=(global_batch_size,10))

model = Demo()
print("**************Feed TensorSpec*************")
logit1, vector1 = model(input1)

print("**************Feed Tensor*************")
logit2, vector2 = model(input2)
```

### Relevant log output

```shell
2022-07-05 01:40:06.508993: I tensorflow/core/platform/cpu_feature_guard.cc:152] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-05 01:40:07.020352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14649 MB memory:  -> device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:06:00.0, compute capability: 7.0
**************Feed TensorSpec*************
**************Feed Tensor*************
=============Demo.call()============
=============TestLayer.call()============
```
</details>

**Comment by tilakrayal** [comment] 2022-07-05 10:56
@KingsleyLiu-NV,
I was able to execute the provided code without any issues/errors. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/84bdaac0fd5274ca623b1e12d6350357/untitled417.ipynb).

And To call a model on an input, always use the __call__() method, i.e. model(inputs), which relies on the underlying call() method and please take a look at this doc [link](https://www.tensorflow.org/api_docs/python/tf/keras/Model) which delivers the information. Thank you!

**Comment by KingsleyLiu-NV** [comment] 2022-07-05 12:19
@tilakrayal 
I don't think you are answering my questions. I want to know whether there are differences for `model(inputs)` between when inputs are `TensorSpec` and when inputs are `Tensor`. Based on what I see in the log, they are different.

Besides, I don't think `call()` is used directly by `model(inputs)`. Instead, `__call__()` is used by `model(inputs)`, which do some internal operations as well as the operations in `call()`.

**Comment by KingsleyLiu-NV** [comment] 2022-07-05 12:20
@tilakrayal Can you explain this log? Why log is printed when inputs are Tensor, but is NOT when inputs are TensorSpec?
```bash
**************Feed TensorSpec*************
**************Feed Tensor*************
=============Demo.call()============
=============TestLayer.call()============
```

**Comment by KingsleyLiu-NV** [comment] 2022-07-05 23:42
@tilakrayal Any progress here?

**Comment by KingsleyLiu-NV** [comment] 2022-07-06 23:52
@tilakrayal  Any progress here?

**Comment by tilakrayal** [comment] 2022-07-07 09:28
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1966b55b78469e9369d71239041a6f6c/56677.ipynb).

**Comment by KingsleyLiu-NV** [comment] 2022-07-07 09:43
I think `model.__call__(inputs)` goes into `model.call()` when inputs are `Tensor`, but does not go into `model.call()` when inputs are `TensorSpec`. I want to know the reasons here. @tilakrayal @gowthamkpr

**Comment by gowthamkpr** [comment] 2022-07-07 20:49
@KingsleyLiu-NV` tf.keras.Input()` produces a symbolic tensor-like object (i.e. a placeholder) whereas you are directly passing in the data when you pass `tf.ones()` into the data and that is the reason why model is not getting executed as you are passing a placeholder, not the data itself. You can refer to this [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Input) for deeper understanding.

**Comment by KingsleyLiu-NV** [comment] 2022-07-14 09:09
@gowthamkpr I don't think feeding `tf.keras.Input(shape=(10,))` will not get the model executed: if  I replace `tf.print()` with `print()`, I can see the log like this:

```shell
**************Feed TensorSpec*************
=============Demo.call()============
=============TestLayer.call()============
**************Feed Tensor*************
=============Demo.call()============
=============TestLayer.call()============
```

Can you explain this? I think the model is executed when feeding `tf.keras.Input(shape=(10,))` but `tf.print()` does **NOT** print the log, while `print()` does. This is really confusing for users.

**Comment by KingsleyLiu-NV** [comment] 2022-07-21 03:08
@gowthamkpr Any progress here?

**Comment by gowthamkpr** [comment] 2022-08-02 23:14
@KingsleyLiu-NV Will get back to you on this

**Comment by gowthamkpr** [comment] 2022-08-04 18:37
@KingsleyLiu-NV As mentioned [here](https://github.com/keras-team/keras/issues/16862#issuecomment-1205601013), this is expected behavior.

**Comment by gowthamkpr** [comment] 2022-08-11 16:06
Closing this issue as it has been answered. Thanks!

**Closed by gowthamkpr** 2022-08-11 16:06 UTC
Labels: stat:awaiting response, type:others, comp:keras, TF 2.8
