### ISSUE TITLE
Cannot build the code including stream_executor/rng.h on Windows

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#29785] opened 2019-06-14 08:04 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 x64
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.14-rc0
- Python version:3.6
- Bazel version (if compiling from source):0.26.0

**Describe the current behavior**
I cannot build the code including stream_executor/rng.h on Visual Studio 2015 as following.
```
tensorflow/compiler/jit/graphcycles/graphcycles.cc(62): note: see reference to class template instantiation 'tensorflow::OrderedSet<tensorflow::int32>' being compiled
ERROR: D:/a/1/s/tensorflow/tensorflow/stream_executor/BUILD:102:1: C++ compilation of rule '//tensorflow/stream_executor:kernel' failed (Exit 2): cl.exe failed: error executing command 
  cd D:/a/1/b/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\windows\system32
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\VSSADM~1\AppData\Local\Temp
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\VSSADM~1\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/bin/external/gif_archive /Iexternal/jpeg /Ibazel-out/x64_windows-opt/bin/external/jpeg /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/gif_archive/lib /Ibazel-out/x64_windows-opt/bin/external/gif_archive/lib /Iexternal/gif_archive/windows /Ibazel-out/x64_windows-opt/bin/external/gif_archive/windows /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /D__CLANG_SUPPORT_DYN_ANNOTATION__ /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /DTF_USE_SNAPPY /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/stream_executor/_objs/kernel/kernel.obj /c tensorflow/stream_executor/kernel.cc
Execution platform: @bazel_tools//platforms:host_platform
.\tensorflow/stream_executor/rng.h(66): error C2589: 'constant': illegal token on right side of '::'
.\tensorflow/stream_executor/rng.h(66): error C2059: syntax error: '::'
.\tensorflow/stream_executor/rng.h(72): error C2589: 'constant': illegal token on right side of '::'
.\tensorflow/stream_executor/rng.h(72): error C2059: syntax error: '::'
Target //tensorflow/compiler/aot:tfcompile failed to build
```

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
bazel build -c opt --color=yes --config=monolithic --verbose_failures //tensorflow/compiler/aot:tfcompile
```

It seems that two odd newline character was mixed into [rng.h](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/stream_executor/rng.h#L64) as follows.
```
  virtual bool DoPopulateRandGaussian(Stream *stream, float mean, float stddev,
                                      DeviceMemory<float> *v) {
    LOG(ERROR)
        << "platform's random number generator does not support gaussian";
    return false;
  }
  virtual bool DoPopulateRandGaussian(Stream *stream, double mean,
                                      double stddev, DeviceMemory<double> *v) {
    LOG(ERROR)
        << "platform's random number generator does not support gaussian";
    return false;
  }
```

This issue is critical for us.
Would you like to modify the code?

**Comment by timshen91** [comment] 2019-07-15 18:57
I have a theory. In `LOG(ERROR)`, ERROR is replaced by some windows-defined macro that's called ERROR. An easy fix would be moving these function implementations into the strean.cc file.

But I don't know how to build TF on windows to verify it. Passing onto @gunan

**Comment by gunan** [comment] 2019-07-15 19:52
From what I can see, our continuous builds for windows are green with msvc 2015.
Are you building TF together with something else?

**Comment by stakemura** [comment] 2019-07-17 04:33
I prepared [CI environment with Azure DevOps](https://dev.azure.com/mlops/build-tfcompile/_build/results?buildId=181&view=logs&j=37ac93e3-95ad-598b-a5c9-c557853b15ab&t=eafe61f6-d619-5846-d967-e9cd72823209&l=764).
As for r1.14 branch, it seems to cause different compile error as follows.

```
ERROR: D:/a/1/s/tensorflow/tensorflow/compiler/xla/service/BUILD:2276:1: C++ compilation of rule '//tensorflow/compiler/xla/service:hlo_execution_profile' failed (Exit 2): cl.exe failed: error executing command |  
-- | --
  | .\tensorflow/compiler/xla/service/hlo_cost_analysis.h(42): error C2131: expression did not evaluate to a constant |  
  | cd D:/a/1/b/execroot/org_tensorflow |  
  | SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt; |  
  | SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\windows\system32
```

**Comment by gunan** [comment] 2019-07-17 06:54
a-ha, I think the issue is you are trying to build XLA on windows.
This is still known to be broken. There may be some progress, but I cannot commit to any dates to get this working.
Here is another relevant issue:
https://github.com/tensorflow/tensorflow/issues/30415

**Comment by sugarflourish** [comment] 2019-09-16 11:35
I build it with msvc 2019 and get the same error. Should I uninstall the 2019 and reinstall the 2015?

**Comment by samhodge** [comment] 2020-06-19 05:53
OK I can reproduce this on MSVC 2017

**Comment by samhodge** [comment] 2020-06-19 05:53
With XLA turned OFF.

**Comment by gunan** [comment] 2020-06-19 16:46
If you are building `tensorflow/compiler/aot:tfcompile` you have to build XLA.

This actually should be resolved in master. XLA now can build on windows. I am trying it again, and will close the issue if the command reported on the original issue works. I am building on master right now
Branches cut before february will now work. but I think 2.2 has all the fixes needed to build this target.

**Comment by gunan** [comment] 2020-06-19 17:54
Just successfully built this target:
```
Target //tensorflow/compiler/aot:tfcompile up-to-date:
  bazel-bin/tensorflow/compiler/aot/tfcompile.exe
INFO: Elapsed time: 1660.510s, Critical Path: 276.99s
INFO: 7933 processes: 7933 local.
INFO: Build completed successfully, 8200 total actions
```
As I mentioned, this will definitely not work with older branches. But branches after 2.2, and master branch, using visual studio 2019 you should be able to build this.

**Closed by gunan** 2020-06-19 17:54 UTC
Labels: comp:runtime, type:bug
