### ISSUE TITLE
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.   np_resource = np.dtype([("resource", np.ubyte, 1)])

### ISSUE THREAD

**Issue by AlexBritoOfficial** [tensorflow/tensorflow#36346] opened 2020-01-30 19:31 UTC
I am receiving this future warning message after compiling my code. I am following this gentleman's video https://www.youtube.com/watch?v=6g4O5UOH304 online. I don't know what kind of complications it might give me further along as we go through the video. Is this something to worry about?

**Comment by ravikyram** [comment] 2020-01-31 06:25
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Please,provide simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment] 2020-02-10 12:04
@AlexBritoOfficial 

Any update on this issue please. Thanks!

**Comment by AlexBritoOfficial** [comment] 2020-02-11 03:58
Sorry @ravikyram I have been busy with some other work, but I got it to work.

**Comment by ravikyram** [comment] 2020-02-24 08:06
@AlexBritoOfficial 

Please, let us know is this still an issue.Please, close this thread if it is already resolved. Thanks!

**Comment by ravikyram** [comment] 2020-02-28 11:53
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-02-28 11:53 UTC
Labels: stat:awaiting response, type:support
