### ISSUE TITLE
Unresolved symbol EigenMatMulF64 when linking a compiled graph with XLA AOT runtime

### ISSUE THREAD

**Issue by battuzz** [tensorflow/tensorflow#41938] opened 2020-07-31 16:31 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6.8
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

When compiling a Tensorflow graph compiled using `saved_model_cli aot_compile_cpu`, the following linking error occurs:

```
libcholesky.o : error LNK2019: unresolved external symbol __xla_cpu_runtime_EigenMatMulF64 referenced in function entry_34875272679f13979ced813466bdebb0 [C:\Projects\aot\aot\tests\mve\build\main.vcxproj]
C:\Projects\aot\aot\tests\mve\build\Release\main.exe : fatal error LNK1120: 1 unresolved externals [C:\Projects\aot\aot\tests\mve\build\main.vcxproj]
```

I think this is because the AOT compile references "tensorflow/include/tensorflow/compiler/xla/service/cpu/runtime_matmul.h" instead of "tensorflow/include/tensorflow/compiler/xla/service/cpu/runtime_single_threaded_matmul.h".

**Describe the expected behavior**

I expect that the exported model can be compiled by referencing only the files in "tensorflow/xla_aot_runtime_src", as stated [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/BUILD#L193).

**Standalone code to reproduce the issue**

I used and saved the following graph:

```python
def cholesky(A, b):
    """ Builds a graph """    
    A = tf.linalg.cholesky(A) 
    res = tf.linalg.triangular_solve(A, b)     
    return res

M = 4
predict_fn = tf.function(cholesky,
        input_signature=[tf.TensorSpec(shape=[M,M], dtype=tf.float64, name='A'), tf.TensorSpec(shape=[M,1], dtype=tf.float64, name='b')], experimental_compile=False)

module_to_save = tf.Module()
module_to_save.predict = predict_fn
tf.saved_model.save(module_to_save, 'saved_model', signatures={'serving_default': module_to_save.predict})
```

Then I compiled the graph using the `saved_model_cli` script:

```bash
$ cd saved_model
$ saved_model_cli aot_compile_cpu --checkpoint_path .\variables\variables --dir . --signature_def_key serving_default --target_triple x86_64-none-windows --cpp_class cholesky --output_prefix libs64/libcholesky --tag_set serve
```

Compiling this sample `main.cpp` and linking it against the generated library above and the [XLA AOT CPU runtime that ships with the pip package](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/BUILD#L193) produces the linking error above.

```cpp
#include <iostream>
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
#include "libcholesky.h" // generated

#define M 4

int main(int argc, char** argv) {  
  cholesky model;  

  int i, j, idx;
  double test_A[] = {1.0583131 , 0.8570645 , 0.77131426, 0.9754439, 0.8570645 , 0.8788354 , 0.6582537 , 0.88981044,0.77131426, 0.6582537 , 0.6411602 , 0.7668645,
       0.9754439 , 0.88981044, 0.7668645 , 1.3106735 };

  double test_b[] = {1, 2, 3, 4};

  std::copy(test_A, test_A+M*M, model.arg0_data());
  std::copy(test_b, test_b+M, model.arg1_data());
  model.Run();
 
  std::cout << model.result0_data()[0] << std::endl;

  return 0;
}
```

**Other info / logs**

**Comment by marcoadurno** [comment] 2020-08-13 19:46
Hi @r4nt ,

Have you been able to replicate the issue? Do you need any further information?

Best Regards,

Marco

**Comment by sanjoy** [comment] 2020-08-20 00:18
@ebrevdo Any idea what's going on?  `__xla_cpu_runtime_EigenMatMulF64` is defined in `compiler/xla/service/cpu/runtime_matmul.cc`, maybe `saved_model_cli` is not picking it up for some reason?

**Comment by marcoadurno** [comment] 2020-08-20 09:57
Hi @sanjoy , @ebrevdo,

The strange bit is that when compiling graphs with `saved_model_cli` that for example only have `dgemm`, everything works as expected: `saved_model_cli` picks up `__xla_cpu_runtime_EigenSingleThreadedMatMulF64`, linking with mini-runtime that comes with pip succeeds.

However, when the graph contains `cholesky` and/or `triangular_solve` ops, it's picking `__xla_cpu_runtime_EigenMatMulF64` which is not part of the single threaded mini-runtime that ships with the pip package. Hence linking fails.

If using `bazel`, the linking succeeds (as it successfully finds `__xla_cpu_runtime_EigenMatMulF64`). But then you still have the performance issues described in #41940.

**Comment by sanjoy** [comment] 2020-08-20 21:10
@d0k any ideas why this ^ would happen?

**Comment by d0k** [comment] 2020-08-20 22:07
The only thing I can think of is that something overwrites the `xla_cpu_multi_thread_eigen` flag. I don't know what could do that yet.

**Comment by ebrevdo** [comment] 2020-08-24 16:34
I'm not sure we ever test large enough matmuls in our unit tests to properly test that this env var is being set.  I can try a bigger unit test.  @sanjoy  Do we have any existing saved_models containing large variables/tensors in matmul?  [This one](https://github.com/tensorflow/tensorflow/blob/e483e7f29c1994b349ae8abff3986b75abe6e2ef/tensorflow/python/tools/BUILD#L354) is small

**Comment by sanjoy** [comment] 2020-08-24 20:30
> @sanjoy Do we have any existing saved_models containing large variables/tensors in matmul?

Not sure if we have such models checked in.  Can we just use the test case in this issue?

**Comment by ebrevdo** [comment] 2020-08-24 20:39
Yes; absolutely.  I may not get to it this week, but it should be easy to add a genrule that creates this savedmodel, and extend the aot_compiled_test rule to run it.

**Comment by marcoadurno** [comment] 2020-08-26 16:07
> [This line](https://github.com/tensorflow/tensorflow/blob/768165d2bc8a596a5274bd026295cc28e0ca1f4f/tensorflow/python/tools/saved_model_aot_compile.py#L274) may not have the intended effect in windows?

I just tested explicitly setting the env variable on Windows directly from ps and I still run into the same issue.

**Comment by ebrevdo** [comment] 2020-10-22 03:19
I *think* https://github.com/tensorflow/tensorflow/commit/84967b39fa98d27f5984648f9ec47a159206cfda may help.  I'm not sure it resolves the env var issue in Windows (I can't debug, lacking a windows machine); but if you run with tf nightly and use `--multithreading true`, it should emit an object file containing the multithreaded matmul code.  You may need to include headers for `libnsync` when compiling + linking, and use a [ThreadPool](https://github.com/tensorflow/tensorflow/commit/84967b39fa98d27f5984648f9ec47a159206cfda#diff-007b11909ecd62d8a55d1880a4d38e9aa1e36382f2bbadd150ba17de5a884865R71) when running the compiled code.

On the other hand, you'll get multithreaded matmuls now.

LMK if this doesn't resolve your issue; we can find someone with access to windows to debug the single threaded case as well.

**Comment by battuzz** [comment] 2020-10-28 08:45
Hi @ebrevdo ,
I had some free time today and I tried to compile the AOT sources shipped with the last tensorflow nightly 2.4 (tf-nightly 2.4.0.dev20201023).

When compiling for 64bit everything works fine, without additional linking, and also the `--multithreading true` option works ok using a ThreadPool. Great work! :D 

However when I compile for 32bit I keep getting this error:
```
C:\VirtualEnvs\tf_nightly\Lib\site-packages\tensorflow\include\Eigen\src/Core/arch/AVX/PacketMath.h(707,49): error C3861: '_mm256_extract_epi64': identifier not found 
```

Do you know where it may come from?

**Comment by ebrevdo** [comment] 2020-10-28 17:01
+Rasmus Larsen <rmlarsen@google.com> does eigen support 32bit?

**Comment by battuzz** [comment] 2020-10-28 17:25
Just to add, with the shipped pip package of Tensorflow 2.3 I didn't have any problem compiling in 32bit with the same procedure (of course using `multithreading=false`)

**Comment by ebrevdo** [comment] 2020-10-28 19:27
+George Karpenkov <cheshire@google.com> that's unexpected. I'm out of
office this week but maybe George can also take a look.

**Comment by ebrevdo** [comment] 2020-10-28 19:27
Can you give a full compile trace?

**Comment by battuzz** [comment] 2020-10-29 09:23
Well the compiler output doesn't say very much. I'm using CMake with Visual Studio 2019 to compile the XLA AOT sources shipped with the package:

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.5
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'


    Directory: C:\Projects\aot\aot


Mode                LastWriteTime         Length Name                                                                                                 
----                -------------         ------ ----                                                                                                 
d-----         27/10/20     18:56                buildtf32                                                                                            


    Directory: C:\Projects\aot\aot\buildtf32


Mode                LastWriteTime         Length Name                                                                                                 
----                -------------         ------ ----                                                                                                 
d-----         27/10/20     18:56                cmake                                                                                                
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/aot/aot/buildtf32
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/VirtualEnvs/tf_nightly/Lib/site-packages/tensorflow/xla_aot_runtime_src/CMakeLists.txt

C:\VirtualEnvs\tf_nightly\Lib\site-packages\tensorflow\include\Eigen\src/Core/arch/AVX/PacketMath.h(707,49): error C3861: '_mm256_extract_epi64': identifier not found [C:\Projects\aot\aot\buildtf32\tf_xla_runtime_objects.vcxproj]
[repeated several times]
```

The compiler generates a library, but then when I link it with the lib generated with `saved_model_cli` it gives me this error:
```
C:\VirtualEnvs\tf_nightly\Lib\site-packages\tensorflow\include\Eigen\src/Core/arch/AVX/PacketMath.h(707,49): error C3861: '_mm256_extract_epi64': iden
tifier not found
```

I don't know if it is something missing on my side or in the sources shipped with the pip package, but anyway this did work properly for tensorflow 2.3..

**Comment by sanjoy** [comment] 2020-10-30 04:00
I believe `_mm256_extract_epi64` is not available on 32bit (see another instance of the same issue: https://github.com/pytorch/pytorch/issues/40988).

Probably Eigen should have some `#ifdef` logic to not use this symbol when building for 32bit.  @rmlarsen WDYT?

**Comment by battuzz** [comment] 2020-11-03 16:06
Hi, 
We managed to get it compiled with 32bit by disabling AVX, as described in this [issue](https://github.com/pytorch/pytorch/issues/17901)

Hope it helps..

**Comment by ebrevdo** [comment] 2020-11-03 16:30
+1 this sounds like an issue in Eigen not detecting 32bit systems.

**Comment by mohantym** [comment] 2021-11-04 07:11
Hi @battuzz! 
We are checking to see whether you still need help in this issue . Please create a new issue if the issue is replicating in Latest version TF 2.6 . Thanks!

**Comment by battuzz** [comment] 2021-11-05 15:15
Hi @mohantym , thanks for coming back to this issue!

I've tried with TF 2.6 and it should work fine now... I don't have this error anymore and the compilation runs successfully, even though the performance of the compiled version of this cholesky decomposition seems quite slow on CPU..

**Comment by ebrevdo** [comment] 2021-11-05 15:34
I suggest opening a separate bug for the performance of cholesky on CPU.  I
don't think anyone's bothered optimizing it, it's likely implemented as a
series of loops in HLO.

**Comment by battuzz** [comment] 2021-11-05 15:52
@ebrevdo Ok, thanks!

**Comment by mohantym** [comment] 2021-11-08 03:32
Ok @battuzz! Closing this issue as it seems to be resolved . Please create a new issue if you need further assistance . Thanks!

**Closed by mohantym** 2021-11-08 03:32 UTC
Labels: type:bug, comp:runtime, comp:xla, TF 2.2
