### ISSUE TITLE
Max_pool with dynamic ksize

### ISSUE THREAD

**Issue by filipealeixo** [tensorflow/tensorflow#9394] opened 2017-04-23 17:10 UTC
I have the following code for a convolutional layer. This layer is part a larger computational graph.

```
# Define the shape of the filter
filter_shape = [1,
                config.char_filter_size,
                config.dim_char,
                config.dim_char]

# Define the convolutional layer weights and biases
W_conv = tf.Variable(tf.truncated_normal(filter_shape, stddev=0.1),
                     name="W_conv")
b_conv = tf.Variable(tf.constant(0.1, shape=[config.dim_char]),
                     name="b_conv")
# Do 2d convolution
conv = tf.nn.conv2d(char_embeddings,
                    W_conv,
                    strides=[1, 1, 1, 1],
                    padding="VALID",
                    name="conv")
# Apply nonlinearity
# h_conv has the same shape as conv
h_conv = tf.nn.relu(tf.nn.bias_add(conv, b_conv),
                    name="conv_relu")
# Maxpooling h_conv over dim 2 (char dim)

# ERROR HERE
conv_pooled = tf.nn.max_pool(h_conv,
                             ksize=[1, 1, tf.shape(h_conv)[-2], 1],
                             strides=[1, 1, 1, 1],
                             padding='VALID',
                             name="conv_max_pool")
```

When trying to run, I get the error:

> TypeError: Expected int for argument 'ksize' not tf.Tensor shape=() dtype=int32.

is tf.nn.max_pool unable to handle dynamic ksize?

**Comment by girving** [comment] 2017-04-24 16:28
This looks like it should work via Derek's auto-stack machinery.  I'll briefly try to reproduce...

**Comment by girving** [comment] 2017-04-24 16:33
Ah, correct: `tf.nn.max_pool` does not support dynamic size.  `ksize` is an attr, therefore must be a constant.  This would be reasonable to fix, but would require a `MaxPoolV2` op kernel similar to `TopKV2`.  I'll leave it open as contributions welcome.

**Comment by girving** [comment] 2017-04-24 17:06
Duplicate of https://github.com/tensorflow/tensorflow/issues/4746.

**Closed** 2017-04-24 17:06 UTC
Labels: stat:contributions welcome, type:feature

**Comment by nkszjx** [comment] 2019-04-08 08:43
tf.reduce_max(activation, axis=1, keep_dims=True)

**Comment by nkszjx** [comment] 2019-04-08 08:43
see https://stackoverflow.com/questions/46760927/using-the-shape-of-a-tensor-with-dynamic-shape-in-tensorflow-operations
